### ISSUE TITLE
CppTools Debugger says "Debug adapter process has terminated unexpectedly" on Arch Linux

### ISSUE THREAD

**Issue by equinoxr** [microsoft/vscode-cpptools#100]
When I try to Debug my cpp which has a a.out file (made with -g in g++) vscode brings this failure on Arch Linux. Cant fix it because i have even no clue where vscode puts its log for this failure or even if it is producing logs...

is there hope to fix this? at least to include logs for problems like that?

Greetz Marcel

**Comment by pieandcakes** [comment]
@equinoxr would you be able to provide your launch.json file? Does this happen with a simple hello world project also? Which version of Arch Linux are you using?

**Comment by equinoxr** [comment]
@pieandcakes : hi,
thx 4 ur reply. here is my json file:

`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (GDB)",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "x64",
            "miDebuggerPath": "/usr/bin/gdb",
            "program": "/home/equinox/code/test1/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "/home/equinox/code/test1",
            "environment": []
        }
    ]
}
`

this is my .cpp : 

#include <iostream>

int main ()
{
     std::cout << "hello";

```
 return 0;
```

}

cat /proc/version gives: 

Linux version 4.6.4-1-ARCH (builduser@tobias) (gcc version 6.1.1 20160707 (GCC) ) #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016

greets equinoxr

**Comment by equinoxr** [comment]
Hi, some update fixed my problem its working now. 
Thanks ! ;)
