### ISSUE TITLE
Environment variable syntax in tasks.json and c_cpp_properties.json is different 

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#1000]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.1
csharp|ms-|1.11.0

---

Steps to Reproduce:

1. Create project with c_cpp_properties.json include path that has "${INCLUDE}" where INCLUDE is an environment variable
2. Create tasks file where the command is "${env:MSBUILD}" where MSBUILD is an environment variable

Expected: Syntax is the same for both environment variable expansions.
Actual: c_cpp_properties.json and tasks use different syntaxes.  One of them requires the "env:" prefix and the other one doesn't.

Reproduces without extensions: Yes/No

**Comment by azydevelopment** [comment]
I actually can't tell if environment variables are working at all.  Closing this for now in favor of this: https://github.com/Microsoft/vscode-cpptools/issues/999.

**Comment by azydevelopment** [comment]
Okay as it turns out, I was right the first time and it's just that the environment variable syntax is just different.  In the CPP tools, it seems to be ${ENVIRONEMNTVARIABLE}.

In tasks.json for example, if I use %MSBUILD% as my environment variable for where my build tools are, it's written as ${env:MSBUILD}.  The prefixed "env:" seems to not be accepted in c_cpp_properties.json.

Reopening this one.

**Comment by azydevelopment** [comment]
Also be aware that I had to move the test header file around every time I wanted to change the environment variable that has the include path as a test because VSCode will seem to cache the location even if I change the environment variable and restart VSCode.

**Comment by bobbrow** [comment]
This is tracked by #697

**Comment by bobbrow** [comment]
#697 was closed and doesn't specifically ask for ${env:VARIABLE} so we can use this issue to track it instead.

**Comment by bobbrow** [comment]
This is fixed in 0.12.4

**Comment by azydevelopment** [comment]
Thanks.  I can confirm this works now.
