### ISSUE TITLE
"Forced include" property in c_cpp_properties.json needs file path validation

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#10010]
On the c_cpp_properties.json file or IntelliSense configuration UI, properties that have file paths as input usually have file path validation. That is if a file path is not validate, a UI feedback should display that there is an error with the file path input.

**Example of error if file path is not valid:** 
On IntelliSense configuration UI
![image](https://user-images.githubusercontent.com/38734287/195939814-4b596b28-d7e2-4665-9dd0-c6c70339ee7c.png)

On c_cpp_properties.json file
![image](https://user-images.githubusercontent.com/38734287/195940050-35a3c073-7d07-4095-a9b1-0dad7832a569.png)

**Issue:**
For the property "Forced include", there is no file path validation for Linux and Mac.

**Expected behavior:**
There should be file path validation for "Forced include" property for Linux and Mac platforms.

**Comment by Bernardin-MS** [comment]
Can I get more details on how to reproduce this issue? ForcedIncludes seems to be working

**Comment by sean-mcmanus** [comment]
Yeah, it appears the bug is already fixed.

**Comment by sean-mcmanus** [comment]
Oh -- the bug is for Mac/Linux (not Windows).

**Comment by sean-mcmanus** [comment]
...but I also don't repro it on Linux. Maybe we might need more repro info from @michelleangela

**Comment by michelleangela** [comment]
It looks like this got fixed. I wasn't able to reproduce on mac and Linux.
