### ISSUE TITLE
[Feature Request] Parse semicolon delimited paths for environment variables as include paths

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#1001]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:07:25.676Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.3

---

Requesting a feature to allow easier use of environment variables for standard include paths.  For instance, consider the following:

- Create directories C:/lib0 and C:/lib1
- Create test files in both those directories
- Create environment variable %INCLUDE% that has the value "C:/lib0; C:/lib1"
- Add ${INCLUDE} to the includePath in c_cpp_properties.json file

As far as I can tell, this is not currently supported.  It'd be great to get this so we can have a standard environment variable that includes multiple libraries and just have ${INCLUDE} in the c_cpp_properties.json file.

Thanks
AY

**Comment by azydevelopment** [comment]
Thanks Bob.  I'll validate when available (any ETA?)

**Comment by sean-mcmanus** [comment]
0.12.4 with the fix was released yesterday. Let us know if there's still a problem.

**Comment by azydevelopment** [comment]
Thanks. Confirmed fixed.

**Comment by azydevelopment** [comment]
Appears to be broken again in 0.13.1.  Test project attached (super simple).

My %INCLUDE% variable path looks like this:

`C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/include;C:/include`

[test.zip](https://github.com/Microsoft/vscode-cpptools/files/1367279/test.zip)
