### ISSUE TITLE
Localization - C_Cpp.CodeAnalysis.ClangTidy.CodeAction.ShowDisable in CHS

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#10011]
highlighting of text and ' incorrect for error for "C_Cpp.CodeAnalysis.ClangTidy.CodeAction.ShowDisable"in CHS

CHS:
![image](https://user-images.githubusercontent.com/38734287/195946788-f5cafa87-651f-4e3a-8f87-e676bc524508.png)

ENU:
![image](https://user-images.githubusercontent.com/38734287/195946802-866eab4b-fa5c-49bf-95a7-1bf00f30f624.png)

**Comment by sean-mcmanus** [comment]
@Colengms Looks like the translators messed up the markdown. Are you able to file a bug on this?
