### ISSUE TITLE
Compiler selection via QuickPick

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#10027]
Add the ability to select a compiler to configure for IntelliSense if there is no compiler configured during first usage of the extension. Additionally, the extension will no longer automatically query a default compiler if one is found on a machine unless it is confirmed by the user to use the compiler.

**Comment by sean-mcmanus** [comment]
@michelleangela The spec is an internal document (in progress). Are you saying we should add an external spec too?

**Comment by michelleangela** [comment]
@sean-mcmanus, the specification for this issue would be for any user facing experience.
