### ISSUE TITLE
Thread-local variables available when debugging

### ISSUE THREAD

**Issue by aahaselgrove** [microsoft/vscode-cpptools#1002]
When I saw that C/Cpp supported [multithreaded debugging](https://code.visualstudio.com/docs/languages/cpp#_debugging), I was excited. However, it appears that this feature currently extends only to displaying the call stack. Could thread-local variables also be shown? Currently, only one thread's thread-local variables are displayed (I assume, the last thread to execute).

**Comment by aahaselgrove** [comment]
feature-request
debugging
multiprocessing

**Comment by pieandcakes** [comment]
@dimpl when you double click on the stack of a different thread, that should show the variables for that thread. If that isn't what you are looking for, can you explain further?

**Comment by aahaselgrove** [comment]
I'm confused as to what I was asking for. Only one thread can hit a particular breakpoint at a time, so it makes sense that only one set of thread-local variables is available.
