### ISSUE TITLE
no autocompletion for local variables

### ISSUE THREAD

**Issue by micheleciaramicoli** [microsoft/vscode-cpptools#10036]
I'm using esp-idf extension and I can't have autocompletion working for any of the variables define by me. 
![image](https://user-images.githubusercontent.com/66261094/196710112-97024542-d01e-4848-bb0f-8b6a92774b80.png)

**Comment by Colengms** [comment]
Hi @micheleciaramicoli .  The C/C++ extension  should be able to provide auto-complete for local variables.  It's possible the compiler you are using is not fully supported, and failures to parse prior code in the translation unit is resulting in limited functionality.

Can you provide a stand-alone repro, perhaps in the form of a zip file or github repo, that we could use to investigate further?

**Comment by bobbrow** [comment]
Also, local variables don't participate in autocomplete when in "tag parser" mode too.  Check the value of the `C_Cpp.intelliSenseEngine` setting.

**Comment by micheleciaramicoli** [comment]
[test.zip](https://github.com/microsoft/vscode-cpptools/files/9858149/test.zip)
Here the template I am using, I don't know if it is enough for troubleshooting, let me know.
Thanks

**Comment by Colengms** [comment]
Hi @micheleciaramicoli .  Looking at the project you provided, I see the follow in `settings.json`:

```
"C_Cpp.intelliSenseEngine": "Tag Parser"
```

bobbrow referred to this in his comment.  In this mode, semantic IntelliSense is disabled, and local variable completion is not provided.

Removing this setting, I see that local variables are being completed properly.  Does that resolve the issue for you?

**Comment by micheleciaramicoli** [comment]
this wil make the autocompletion work, thank you, but It creates another issue because the functions like pdMS_TO_TICKS(100) now are not recognized, also the constants like M_PI that I'm using in the final version of my code, this error appears that I don't know how to solve: 
![image](https://user-images.githubusercontent.com/66261094/198285214-3e278e8f-c68a-40a2-aa46-15cce366ebe1.png)
and in the C/C++ configuration I have this, I tried to add the path
![image](https://user-images.githubusercontent.com/66261094/198284471-9a7c35cc-4a9b-46f6-8f56-2e69d20ed8e3.png)
I can delete everything and insert the path to components folder but at that point I cannon include the library esp_dsp.h that I have in a components folder inside my project, vscode suggest to update my includepath but this time adding it does not work
![image](https://user-images.githubusercontent.com/66261094/198287484-d39da597-a56e-46b8-978a-da1620e23de6.png)

**Comment by Colengms** [comment]
Hi @micheleciaramicoli .  In the container you provided, I did notice that those paths were not defined.  The environment variables referred to were not set.

I'm not sure how to advise you on how to configure esp projects.  Perhaps there is a repo or page for esp-specific support that might be more appropriate?

**Comment by micheleciaramicoli** [comment]
I searched in the documentation but I can't find anything about this type of problems. Do you think that setting up the enviromental variables can do the trick? I cannot set them easily because it is my work pc but I can do that
