### ISSUE TITLE
Does not recognize gdb/lldb under NixOS

### ISSUE THREAD

**Issue by schuelermine** [microsoft/vscode-cpptools#10047]
Type: <b>Bug</b>

Create a C file while having gdb or lldb installed via Nix, and try to debug it.

When launching or debugging the C file, VS Code complains that the “miDebuggerPath” is invalid.

Even when supplying a correct miDebuggerPath via launch.json, it still fails.

Extension version: 1.11.0
VS Code version: Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:23:00.760Z)
OS version: Linux x64 6.0.2
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 3899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|23.36GB (16.72GB free)|
|Process Argv|. --crash-reporter-id e7edef01-ae1d-47d1-84c4-8bfe16d21f3f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by WardenGnaw** [comment]
Can you add the following `"logging": { "engineLogging": true, "trace": true, "traceResponse": true }`to your launch.json file and share the Debug Console output?

**Comment by schuelermine** [comment]
I’ve set that and the debugging console is empty. The terminal has the following output:
```
 *  Executing task: C/C++: clang build active file 

Starting build...
/nix/store/bbqcshyz1rir24p2yc09djkqxccdx44v-clang-wrapper-11.1.0/bin/clang -fdiagnostics-color=always -g /media/external-data/Code/code-experiments/C/fibonacci.c -o /media/external-data/Code/code-experiments/C/fibonacci

Build finished successfully.
```

**Comment by WardenGnaw** [comment]
Can you share the config that its outputted to one of the output windows? It should display your program, args and miDebuggerPath.

**Comment by schuelermine** [comment]
I have added the logging setting but I don’t see anything like that in the Debug Console, the Output tab or the Terminal. Here is a screen recording so you can see what I saw:
![vscode_C_Cpp_invalid_miDebuggerPath](https://user-images.githubusercontent.com/48802534/198708775-7a8aead7-c9d3-4334-8f23-43d76aedfbfe.gif)

**Comment by schuelermine** [comment]
The exact same thing happens if I provide a `miDebuggerPath`.

**Comment by WardenGnaw** [comment]
How are you starting to debug? Are you clicking the green play button on the top left or using F5? Those are the entrypoints of using your launch.json. The json configuration in this [commit's video](https://github.com/microsoft/vscode-cpptools/issues/10047#issuecomment-1295334511) looks correct.

**Comment by schuelermine** [comment]
I'm pressing the top right button with the play icon and the debugging symbol

**Comment by WardenGnaw** [comment]
Do you see the error message you click on the top left green run button or use F5?

The top right button is single file debugging.
@elahehrashedi How can you configure the miDebuggerPath with single file debug?
