### ISSUE TITLE
Warning, C++ compiler Arm architecture

### ISSUE THREAD

**Issue by danielbuubble** [microsoft/vscode-cpptools#10046]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/10044

<div type='discussions-op-text'>

<sup>Originally posted by **danielbuubble** October 21, 2022</sup>
Hi!

I am taking a course at my university and I am pretty new to C++. I have been stuck on this "bug" where, whenever I press the play button to compile and run the file, I get this warning "default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]". And when I look at the debug console I get this message "Warning: Debuggee TargetArchitecture not detected, assuming x86_64.". From my limited knowledge, it looks like vscode assumes I am using arch x86, but I have a M2 arch Arm. My question is do you guys have any fix to my problem? Because I can run the code using commands in the terminal, but I would like the play button to work (Invested to much time in this to give up on the play button). I have looked all over the internett, but the solutions are way over my knowledge, and to advanced for me, I think. 
<img width="1470" alt="Skjermbilde 2022-10-21 kl  15 14 35" src="https://user-images.githubusercontent.com/116361422/197204793-114db8ff-b000-4873-9377-d5c7ac3eabf9.png">

Thank you for your help, and sorry for my limited knowledge and mispokenes. :D
</div>

**Comment by sean-mcmanus** [comment]
I answered in the discussion: https://github.com/microsoft/vscode-cpptools/discussions/10044 .
