### ISSUE TITLE
C++ TestMate as part of Extension Pack

### ISSUE THREAD

**Issue by matepek** [microsoft/vscode-cpptools#10049]
### Feature Request

Hello,

I'm de developer of [C++ TestMate](https://github.com/matepek/vscode-catch2-test-adapter).

I've just bumped into the Extension Pack. I was wondering that would the users find useful if TestMate would be part of the extension pack.

Thank for your consideration.

**Comment by Colengms** [comment]
Hi @matepek .  We've recently removed some extensions from the C/C++ Extension pack, based on feedback requesting that only the most essential extensions for C/C++ be included.  If that changes, or we create an additional extension pack, we could revisit this.

We can leave this issue open as a feature request, so others can vote on it.

**Comment by H-G-Hristov** [comment]
As a user:  cpptools + cmake-tools + c++test mate functionality should be tightly integrated. Even better than they are now. 👍
