### ISSUE TITLE
ctrl+click doesn't underline/highlight the whole name if it contains a `-`

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cpptools#10051]
Type: <b>Bug</b>

An example would be:

```c++
#include <wayland-client-protocol.h>
```

Extension version: 1.13.2
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.15.0-52-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 1200)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.42GB (3.25GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 20280fc3-3c6d-43d3-9eb5-55c536b003d8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
vsccc:30566497
pyindex848cf:30577861
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by Colengms** [comment]
Hi @Zingam .  Are you using the C/C++ Extension?  I believe I see the behavior you are describing if the C/C++ Extension is not enabled.  With it enabled, I don't see any selection occurring when I control-click.  Instead, control-click triggers navigation to what was clicked on.  It appears to navigate to the correct file when used on a header file with dashes in the name.

**Comment by Zingam** [comment]
Yes, I am using the extension. I think you haven't understood my remark. Navigation everything is working fine. 
What I mean is if you have a header like:
`a-long-header-name.hpp`
`#include "my-header-abc.`<ins>`hpp`</ins>`"`
If  I try to ctrl+click a line is rendered only on a part of the whole name. The characters `-` and `.` break the line. If the mouse is over `hpp` only this word will be underlined. It is a bit ugly and confusing at first.
Can we have instead the option to click anywhere on the line:
`#include <my-header-abc.hpp>`

e.g.


<ins>`#include "my-header-abc.hpp"`</ins>

**Comment by Colengms** [comment]
Hi @Zingam .  It looks like VS Code is providing the underline (or text selection, if the C/C++ Extension is not installed).  There does not appear to be a way for an extension to influence that text range.  You might consider opening a similar issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).

**Comment by Colengms** [comment]
Closing an external.
