### ISSUE TITLE
Additional problem matchers - ARMCC, IAR, Keil

### ISSUE THREAD

**Issue by morsisko** [microsoft/vscode-cpptools#10054]
### Feature Request

Hello,

I use few different compilers to compile C programs (ARMCC, IAR, Keil) those compilers outputs warnings and errors in different format than GCC compiler. Currently there is only problem matcher for GCC compiler, so if you compile your code with those I've listed above, erorrs and warnings won't be present in "Problems" window.

If I made pull request with problem matchers for those compilers, would you consider merging it to the main branch, or should I rather made my own vsc extension with those matchers?

**Comment by Colengms** [comment]
Hi @morsisko .  Yes, we would be open to a contribution of problem matchers.  :)

**Comment by sean-mcmanus** [comment]
Your fix is available with 1.13.4 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.4

**Comment by morsisko** [comment]
Thanks for the information
