### ISSUE TITLE
Need to fix include errors for "endian.h" on Mac

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#1005]
It was bothering me that "endian.h" was being demanded in projects where we had correctly set the includePath based on the compiler's output.  "endian.h" could not be found in the system headers.

It turns out the "endian.h" issue is actually caused by a missing default preprocessor symbol.  The Xcode header files expect `__LITTLE_ENDIAN__` to be set by the compiler.  For those who have already added the path to "endian.h" to their c_cpp_properties.json, you should be able to remove that path if you add `"__LITTLE_ENDIAN__"` to the `"defines"` array in c_cpp_properties.json instead. I am going to update the extension to add this define by default.

**Comment by Leedehai** [comment]
I suggest you file a complaint to XCode.. the sacred standard header files should not be tinkered with.

**Comment by JeffreyCA** [comment]
Thanks! Removed the extra include path and modified it like so:
```
    "defines": [
        "__LITTLE_ENDIAN__"
    ],
```

**Comment by bobbrow** [comment]
The fix for this is in the update we pushed yesterday.  You shouldn't need to specify `__LITTLE_ENDIAN__` in your `"defines"` anymore either.
