### ISSUE TITLE
Unable to start debugging. Launch options string provided by the project system is invalid.

### ISSUE THREAD

**Issue by miradesne** [microsoft/vscode-cpptools#1006]
Hi, 

I'm following tho documentation to setup C++ debugging with MinGW. However after the build task VS Code failed at starting debugging with error `Unable to start debugging. Launch options string provided by the project system is invalid. at line 6 position 27` in the `launch.json`. 

Here's my `launch.json`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\bin\\gdb.exe",
            "preLaunchTask": "build hello world"            
        }
    ]
}
```

  * Operating System and version:
 ** Windows 10 Home
  * VS Code version 
 **  1.15.1
  * C/C++ extension version
 ** 0.12.3

Please help! I have no clue what went wrong.

**Comment by pieandcakes** [comment]
@miradesne your `miDebuggerPath` is missing a \ between `MinGW` and `bin`. Also, is your application called `a.exe` in your root of your workspace? Can you also share your preLaunchTask (`tasks.json`) ?

**Comment by pieandcakes** [comment]
@miradesne I can't duplicate this and I haven't heard back from you. If this is still not working for you, please provide the information requested and reopen this issue.

**Comment by iamphc** [comment]
@pieandcakes  I also got this trouble .
my launch.json is:
`{ 
    "version": "2.0.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files (x86)\\mingw-w64\\i686-7.2.0-posix-dwarf-rt_v5-rev1\\mingw32\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++"
        }
    ]
}`

and my tasks.json is:
`{
    "version": "2.0.0",
    "command": "g++",
    "args": ["-g","${file}","-o","${fileBasenameNoExtension}.exe"],    
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
} `

**Comment by iamphc** [comment]
@pieandcakes I also got this trouble .
my launch.json is:
```
{ 
    "version": "2.0.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files (x86)\\mingw-w64\\i686-7.2.0-posix-dwarf-rt_v5-rev1\\mingw32\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++"
        }
    ]
} 
```

and mu tasks.json is:
```
{
    "version": "2.0.0",
    "command": "g++",
    "args": ["-g","${file}","-o","${fileBasenameNoExtension}.exe"],    
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
} 
```

and i got Unable to start debugging. Launch options string provided by the project system is invalid.

**Comment by pieandcakes** [comment]
@iamphc please enable `engineLogging` and provide the engine log so we can see which string is missing/invalid.

**Comment by newyeo** [comment]
Hi, @pieandcakes 
I encounter the same issue. That's 
> Unable to start debugging. Launch options string provided by the project system is invalid. Unable to determine path to debugger. Please specify the "MIDebuggerPath" option.

Bug description:
Hit the green button at left it can debug successfully while hit the debug button at bottom it launch the Unable to start debugging and show the above error message.

- Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.15063

- OS: win10 pro

- List of extensions that have installed:
c/c++ 0.28.1
CMake 0.0.17
CMake Tools 1.4.0
Python 2020.5.80290

- Reproducible steps (1... 2... 3...) that cause the issue
Hit the debug button at bottom it launch the error above.

- What you expected to see, versus what you actually saw
Expect it enter the debug process.

- Images, animations, or a link to a video showing the issue occurring
![image](https://user-images.githubusercontent.com/26040261/82780133-ca009c80-9e88-11ea-90a8-efc98fe5685a.png)

- A code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally
launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-win32-sjlj-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++.exe build active file",
            "logging": {
                "trace": false,
                "traceResponse": false,
                "engineLogging": true
            }
        }
        
    ]
}
```

task.json
```
{
    "tasks": [
        {
            "type": "shell",
            "label": "g++.exe build active file",
            "command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-win32-sjlj-rt_v6-rev0\\mingw64\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-win32-sjlj-rt_v6-rev0\\mingw64\\bin"
            }
        }
    ],
    "version": "2.0.0"
}
```


- Result from output after enabling the engineLogger:
[output.log](https://github.com/microsoft/vscode-cpptools/files/4675296/output.log)

**Comment by pieandcakes** [comment]
@WardenGnaw Please investigate @newyeo 's issue. It looks like they are using quick debug?

@newyeo The log you provided is for intellisense. Can you take a picture of the `green button` you are pressing so we can confirm? According to your `launch.json` I see that you are specifying the `miDebuggerPath`. Does that path exist on your computer?

**Comment by newyeo** [comment]
@pieandcakes 
Thanks a lot for your prompt reply!
I checked again. The path does exist.
I followed the link https://code.visualstudio.com/docs/cpp/enable-logging-cpp to enable the engingLoggering. And I don't know where to find the log you need.
The green triangle button in red rectangle at left top is what I mentioned green button.  Click it and it will enter the debug process correctly and gdb info is normally output at the output panel below.
![image](https://user-images.githubusercontent.com/26040261/82964378-ea9b3480-9ff7-11ea-9022-b58b8a7f4a0e.png)

The worm likely button in green rectangle at bottom is what I clicked and then appear the mentioned issue.
![image](https://user-images.githubusercontent.com/26040261/82964482-28985880-9ff8-11ea-82be-95e94516e134.png)

**Comment by pieandcakes** [comment]
@WardenGnaw Do you know what that bottom button is? Is that something new?

**Comment by WardenGnaw** [comment]
The c/c++ extension does not contribute to the status bar for the bug icon. That seems to be another extension. 

The built in `start debugging` button in VS Code for the status bar is the `|> g++.exe` in status bar.

**Comment by newyeo** [comment]
I checked. This debug button at buttom is appeared as CMake tool extension enabled and it disappeared after CMake tool is disabled. So it might be issues of CMakes tool. I find similar issue at vscode-cmake-tools repository https://github.com/microsoft/vscode-cmake-tools/issues/692 and it said it might be the issue of c++ extension. Haha....
![image](https://user-images.githubusercontent.com/26040261/83087663-61056880-a0c4-11ea-95fc-9a62d7143569.png)

Anyway, I will repost this issue to vscode-cmake-tools repository. And thanks very much for your  quick support! @WardenGnaw @pieandcakes
