### ISSUE TITLE
Hover tooltip still showing old colors

### ISSUE THREAD

**Issue by KaeLL** [microsoft/vscode-cpptools#10061]
### Environment

- VS Code: 1.72.2
- cpptools: 1.13.2
- cpptools-themes: 2.0.0

### Bug Summary and Steps to Reproduce

Bug Summary:
Seems you missed updating the hover tooltip token colorization, as it's still using the old colors.

![image](https://user-images.githubusercontent.com/4423144/197850799-f2224aee-8cce-4e6a-8215-746ba880114b.png)

**Comment by Colengms** [comment]
Hi @KaeLL .  I believe the behavior you are seeing is determined by VS Code itself.  A theme is basically a set of colors and rules associated with 'tokens'.  Syntactic tokens are determined by VS Code itself, using TextMate grammar rules.  Semantic tokens are determined by the extension, but only in response to requests from VS Code for semantic tokens.  It doesn't look like VS Code is requesting semantic tokens for the contents of tooltips.

You might consider opening an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).

Closing this issue as external.
