### ISSUE TITLE
Can't recognize *.c++ files automatically on Windows

### ISSUE THREAD

**Issue by Heromyth** [microsoft/vscode-cpptools#1007]
It must set the file format associations to cpp in local settings.

``` json
    "files.associations": {
        "*.c++": "cpp"
    }
```

All the tools are latest.

**Comment by bobbrow** [comment]
If you have some time to help out, you can modify this file: [extensions/cpp/package.json](https://github.com/Microsoft/vscode/blob/master/extensions/cpp/package.json) and submit a pull request to VS Code

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
