### ISSUE TITLE
Invalid variable reference ${which_declare} in string:

### ISSUE THREAD

**Issue by jiangbo** [microsoft/vscode-cpptools#10089]
### Environment

- OS and version: window 10
- VS Code: 1.72.2
- C/C++ extension: 1.12.4
- OS and version of remote machine (if applicable): wsl2(AlmaLinux release 8.6)
- GDB / LLDB version:  GNU gdb (GDB) Red Hat Enterprise Linux 8.2-18.el8

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Cargo init test

2. in main.rs:
```rust
fn main() {
    println!("hello world");
}
```
3. click Debug in main function

install RA vscode extension: https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer

![debug-error](https://user-images.githubusercontent.com/14179422/199057436-e83d8e4d-e5a4-4fed-8ffd-6e1f461e32d2.png)

### Debugger Configurations

```shell
no configurations, only click Debug on main.
```

### Debugger Logs

```shell
Invalid variable reference ${which_declare} in string: () {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}.
```

**Comment by sean-mcmanus** [comment]
@WardenGnaw Is this a debugger issue?

**Comment by WardenGnaw** [comment]
It seems like an automatically generated launch config passing in a bad environment variable to the debugger.

**Comment by jiangbo** [comment]
I changed wsl os from AlmaLinux to Ubuntu, and the error disappeared. Thanks.
