### ISSUE TITLE
Allow for indented formatting of namespaces.

### ISSUE THREAD

**Issue by deathly809** [microsoft/vscode-cpptools#1008]
Currently when I have nested namespaces they are flattened when I format:
```
namespace Foo {
namespace Bar {
class Bang {
};
}
}
```
Would it be possible to add a flag to not do this and instead do this:
```
namespace Foo {
    namespace Bar {
        class Bang {
        };
    }
}
```

**Comment by sean-mcmanus** [comment]
Using `NamespaceIndentation: All` works. See http://releases.llvm.org/4.0.0/tools/clang/docs/ClangFormatStyleOptions.html .
