### ISSUE TITLE
not able to run the code

### ISSUE THREAD

**Issue by radhikachauhan** [microsoft/vscode-cpptools#10081]
We have written the needed data into yo
Type: <b>Bug</b>

when i run the code it always show "g++ is not recognized as an internal or external command".

Extension version: 1.3.0
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.78GB free)|
|Process Argv|--crash-reporter-id 4d93cb85-7e0e-4096-8750-ce6ae4ddf660|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

ur clipboard because it was too large to send. Please paste.

**Comment by browntarik** [comment]
Have you set the appropriate compiler path to point to your g++ installation? This can be done by editing your c_cpp_properties.json file. Consider running the extension command "Edit Configurations (UI)" and check the compiler path option.

**Comment by browntarik** [comment]
Additionally, how exactly are you trying to run g++? Are you using tasks.json or the command line? Can you provide the tasks.json “type” and “command’?
