### ISSUE TITLE
Namespace Cairo has no member Context

### ISSUE THREAD

**Issue by kramer04** [microsoft/vscode-cpptools#10082]
### Environment

- OS and version: Ubuntu 22.04 LTS 5.15.0-52-generic
- VS Code: 1.73.0-insider
Commit: 3544aabd5a2b0da2cd3a6f3fa3f00759aa9d9709
Date: 2022-10-27T21:32:20.730Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-52-generic snap
Sandboxed: Yes
- C/C++ extension:Version 1.13.3: October 26, 2022
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:
IntelliSense says `namespace "Cairo" has no member "Context"`, although the code compiles without errors.

![bug_no_member](https://user-images.githubusercontent.com/29018157/198819513-4967696c-febe-492d-9776-c4d5563669f2.png)

Steps to reproduce:
Just type the code and error appears
Set : `"C_Cpp.intelliSenseEngine":"default",`

With `"C_Cpp.intelliSenseEngine":"default",` theme colors are displayed correctly
![correct_colors](https://user-images.githubusercontent.com/29018157/198819874-e1bfc0cb-31ea-47f3-9d6b-f209a5af67c5.png)
![set_default](https://user-images.githubusercontent.com/29018157/198820133-4fa8d9e6-8a0d-48e3-ac53-9fc0452df370.png)

With `"C_Cpp.intelliSenseEngine":"Tag Parser",`theme colors are not displayed correctly
but Intellisense Engine works (no squigles)
![tag_parser](https://user-images.githubusercontent.com/29018157/198820249-285d9b60-8e42-4496-af44-f65477a35b46.png)

### Additional Information

`c_cpp_properties.json`
`{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/include/**",
                "/usr/include/**",
                "/usr/lib/**",
                "/usr/local/include/**",
                "/usr/local/lib/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}`

`settings.json`
`{
    "C_Cpp.intelliSenseEngine":"Tag Parser",
    "editor.semanticHighlighting.enabled": true,
    "editor.letterSpacing": 0.3,
    "editor.tabSize": 2
}`

- [ ] Add log

> -------- Diagnostics - 30/10/2022, 11:14:11
Version: 1.13.3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/include/**",
        "/usr/include/cairomm-1.16/**",
        "/usr/include/cairomm-1.16",
        "/usr/local/include/sigc++-3.0/sigc++/**",
        "/usr/local/include/sigc++-3.0/sigc++",
        "/usr/include/cairo/**",
        "/usr/include/gtkmm-4.0/**",
        "/usr/include/giomm-2.68/**",
        "/usr/include/glibmm-2.68/**",
        "/usr/include/pangomm-2.48/**",
        "/usr/include/freetype2/**",
        "/usr/include/glib-2.0/**",
        "/usr/include/pango-1.0/**",
        "/usr/include/harfbuzz/**",
        "/usr/include/gtk-4.0/**",
        "/usr/include/gdk-pixbuf-2.0/**",
        "/usr/include/graphene-1.0/**",
        "/usr/lib/**",
        "/usr/local/include/**",
        "/usr/local/lib/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/g++",
    "cStandard": "gnu17",
    "cppStandard": "gnu++20",
    "intelliSenseMode": "linux-gcc-x64",
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "/usr/include",
            "/usr/local/include",
            "${workspaceFolder}/include"
        ],
        "databaseFilename": "${default}"
    },
    "mergeConfigurations": false,
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true
}
Translation Unit Mappings:
[ /media/blabla/Android/Le_c++/gtkmm4-v3_multiple_entry/include/entree.h ]:
    /media/blabla/Android/Le_c++/gtkmm4-v3_multiple_entry/include/entree.h
Translation Unit Configurations:
[ /media/blabla/Android/Le_c++/gtkmm4-v3_multiple_entry/include/entree.h ]:
    Process ID: 13574
    Memory Usage: 169 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/include/cairomm-1.16
        /usr/local/include/sigc++-3.0/sigc++
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
        /usr/local/include/sigc++-3.0
        /usr/include/gtkmm-4.0
        /usr/include/glibmm-2.68
        /usr/include/giomm-2.68
        /usr/include/pangomm-2.48
        /usr/lib/x86_64-linux-gnu/glibmm-2.4/include
        /usr/include/glib-2.0
        /usr/lib/x86_64-linux-gnu/sigc++-2.0/include
        /usr/lib/x86_64-linux-gnu/gdkmm-3.0/include
        /usr/include/gtk-4.0
        /usr/lib/x86_64-linux-gnu/gtkmm-3.0/include
        /usr/lib/x86_64-linux-gnu/giomm-2.4/include
        /usr/include/pango-1.0
        /usr/lib/x86_64-linux-gnu/pangomm-1.4/include
        /usr/include/cairo
        /usr/lib/x86_64-linux-gnu/glib-2.0/include
        /usr/lib/x86_64-linux-gnu/cairomm-1.0/include
        /usr/include/gdk-pixbuf-2.0
        /usr/include/harfbuzz
        /usr/include/freetype2
        /usr/include/graphene-1.0
        /usr/lib/x86_64-linux-gnu/perl/5.34.0/CORE
        /usr/lib/x86_64-linux-gnu/graphene-1.0/include
    Standard Version: c++20
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110300
        --header_only_fallback
Total Memory Usage: 169 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 8548

**Comment by Colengms** [comment]
Hi @kramer04 .  Can you provide an isolated repro, in the form of a zipped folder or a GitHub repo (and instructions for installing dependencies), that we might use to investigate further?

Looking at the info you provided, my first suspicion is about multiple include paths related to cairo.  I see "/usr/include/cairomm-1.16", "/usr/include/cairo", and "/usr/lib/x86_64-linux-gnu/cairomm-1.0/include".  Perhaps IntelliSense is picking up a different version of cairo than your compiler?  You might try adjusting your include paths to refer to a specific version of cairo, rather than picking up multiple using a glob pattern.

**Comment by kramer04** [comment]
Hello @Colengms 
you can see my project to [https://github.com/kramer04/sudoku_game/tree/beta](url)

-------- Diagnostics - 01/11/2022, 09:25:59
Version: 1.13.3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/include/**",
        "/usr/include/cairomm-1.16/**",
        "/usr/local/include/sigc++-3.0/sigc++/**",
        "/usr/local/include/sigc++-3.0/sigc++",
        "/usr/include/cairo/**",
        "/usr/include/gtkmm-4.0/**",
        "/usr/include/giomm-2.68/**",
        "/usr/include/glibmm-2.68/**",
        "/usr/include/pangomm-2.48/**",
        "/usr/include/freetype2/**",
        "/usr/include/glib-2.0/**",
        "/usr/include/pango-1.0/**",
        "/usr/include/harfbuzz/**",
        "/usr/include/gtk-4.0/**",
        "/usr/include/gdk-pixbuf-2.0/**",
        "/usr/include/graphene-1.0/**",
        "/usr/lib/**",
        "/usr/local/include/**",
        "/usr/local/lib/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/g++",
    "cStandard": "gnu17",
    "cppStandard": "gnu++20",
    "intelliSenseMode": "linux-gcc-x64",
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "/usr/include",
            "/usr/local/include",
            "${workspaceFolder}/include"
        ],
        "databaseFilename": "${default}"
    },
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false
}
Translation Unit Mappings:
[ /media/blabla/Android/Le_c++/gtkmm4-v3_multiple_entry/src/drawgrid.cpp ]:
    /media/blabla/Android/Le_c++/gtkmm4-v3_multiple_entry/src/drawgrid.cpp
    /media/blabla/Android/Le_c++/gtkmm4-v3_multiple_entry/include/drawgrid.h *
Translation Unit Configurations:
[ /media/blabla/Android/Le_c++/gtkmm4-v3_multiple_entry/src/drawgrid.cpp ]:
    Process ID: 4971
    Memory Usage: 177 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/local/include/sigc++-3.0/sigc++
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
        /media/blabla/Android/Le_c++/gtkmm4-v3_multiple_entry/include
        /usr/include/cairomm-1.16
        /usr/include/cairo
        /usr/include/glibmm-2.68
        /usr/local/include/sigc++-3.0
        /usr/include/gtkmm-4.0
        /usr/lib/x86_64-linux-gnu/cairomm-1.0/include
        /usr/lib/x86_64-linux-gnu/glibmm-2.4/include
        /usr/include/glib-2.0
        /usr/lib/x86_64-linux-gnu/gtkmm-3.0/include
        /usr/include/pangomm-2.48
        /usr/include/giomm-2.68
        /usr/include/freetype2
        /usr/lib/x86_64-linux-gnu/sigc++-2.0/include
        /usr/lib/x86_64-linux-gnu/gdkmm-3.0/include
        /usr/include/pango-1.0
        /usr/include/gtk-4.0
        /usr/lib/x86_64-linux-gnu/giomm-2.4/include
        /usr/lib/x86_64-linux-gnu/glib-2.0/include
        /usr/lib/x86_64-linux-gnu/pangomm-1.4/include
        /usr/include/harfbuzz
        /usr/include/gdk-pixbuf-2.0
        /usr/include/graphene-1.0
        /usr/lib/x86_64-linux-gnu/perl/5.34.0/CORE
        /usr/lib/x86_64-linux-gnu/graphene-1.0/include
    Standard Version: c++20
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110300
Total Memory Usage: 177 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 8548

**Comment by Colengms** [comment]
Hi @kramer04 .  The `c_cpp_properties.json` content you provided includes:

```
         "includePath":[
            "${workspaceFolder}/include/**",
            "/usr/include/**",
            "/usr/lib/**",
            "/usr/local/include/**",
            "/usr/local/lib/**"
         ],
```

The  `**` indicates it should scan subdirectories as well.  You might consider removing the `**`, and explicitly adding any required library include paths.

Or, perhaps you could uninstall one of the conflicting `cairo` related packages.  Perhaps this one, as it appears to be an older version: `/usr/lib/x86_64-linux-gnu/cairomm-1.0`

Or, if you are building using CMake or a Makefile, you might consider using the CMake Tools extension or Makefile Tools extension.  The C/C++ extension can be configured (using `configurationProvider`) to leverage the build information generated by those extensions to configure IntelliSense.

**Comment by kramer04** [comment]
Hello @Colengms 
Thanks for your help
I think my `c_cpp_properties.json` was not specific enough for intellisense engine to find all include files.

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/include/**",
                "/usr/lib/gtkmm-4.0/include/**",
                "/usr/include/c++/11/**",
                "/usr/include/glibmm-2.68/**",
                "/usr/lib/glibmm-2.68/**",
                "/usr/lib/giomm-2.68/include/**",
                "/usr/lib/pangomm-2.48/**",
                "/usr/lib/x86_64-linux-gnu/glib-2.0/include/**",
                "/usr/local/lib/sigc++-3.0/**",
                "/usr/lib/cairomm-1.16/**",
                "/usr/lib/x86_64-linux-gnu/graphene-1.0/**",
                "/usr/include/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "gnu17",
            "cppStandard": "c++20",
            "intelliSenseMode": "linux-gcc-x64",
            "compilerArgs": []
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
Usually, you should avoid having system includes from your compiler in the includePath and you should avoid using `"**"` for external libraries. Otherwise, you could run into issues with the include pat orderings being incorrect and the `"**"` causes a "random" ordering to be used. If you run C/C++: Log Diagnostics after opening a file you can see what the recursive includes resolved into and use that to potentially create a more reliable includePath without the `"**"`.

**Comment by Colengms** [comment]
Good point, I didn't notice that.  System include paths don't need to be specified in `includePath`, as those are automatically retrieved from the compiler in `compilerPath`.  Generally, `includePath` should be used only for paths that need to be added to a compile command line to successfully compile a source file.

**Comment by kramer04** [comment]
@sean-mcmanus  thanks for your advice.
@Colengms I think it's because there's no gtkmm-4.0 deb package for debian and so ubuntu. So i've installed it manually. 
I have two API that coexist : gtkmm-3.0 and gtkmm-4.0. I think there is confusion for intellisense which cannot clearly identify all header files.
