### ISSUE TITLE
BUG : identifier "__null" not defined - Code analysis before compilation (MacOS - Ventura 13.0) 

### ISSUE THREAD

**Issue by westindev-lbr** [microsoft/vscode-cpptools#10084]
### Environment

- OS and Version: macOS Ventura 13.0
- VS Code Version:  1.72.2
- C/C++ Extension Version: v1.12.4
- Other extensions you installed (and if the issue persists after disabling them):  
- If using SSH remote, specify OS of remote machine:  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc). 

The extension notice that `identifier "__null" not defined` when i initialize my pointer with `NULL`
![Capture d’écran 2022-10-30 à 12 22 12](https://user-images.githubusercontent.com/102034752/198875896-bb276975-b117-4123-bffb-e8dba8305a97.png)
![Capture d’écran 2022-10-30 à 12 22 39](https://user-images.githubusercontent.com/102034752/198875897-bb5c1816-638b-41f0-a843-ea57a88edbf0.png)

### Bug Summary and Steps to Reproduce

Bug Summary:
1. Create a file.c 
2. Declare and initialize a pointer with `NULL`
3. Notice the error during automatic code analysis.

Steps to reproduce:
1. Declare for example : int * pointer = NULL;
2. See error

### Code sample and Logs

```shell
#include <stdlib.h>

typedef struct arbre_comp
{
    unsigned char symbole;     // charactères unicode
    unsigned int occurrence;   // nombre d'occurences du symbole
    unsigned int code_binaire; // code binaire
    unsigned int nombre_bits;  // nombre de bits
    struct arbre_comp *g;      // sous-arbre gauche
    struct arbre_comp *d;      // sous-arbre droit
} Arbre_t;

int main() {
    Arbre_t* arbre = malloc(sizeof(*arbre));
    arbre->g = NULL;
    arbre->d = NULL;
    free(arbre);
}


Configurations :
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${default}"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "macos-clang-arm",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}

Diagnostics : 

[ /Users/axellbr/Documents/L3/Algorithmique Avancée/TP4-Image/arbre.c ]:
    Process ID: 53566
    Memory Usage: 10 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c17
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 29 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3314
```

### Screenshots

![Capture d’écran 2022-10-30 à 11 44 16](https://user-images.githubusercontent.com/102034752/198876385-1daa02dc-989c-432b-b491-b91e7155e438.png)
![Capture d’écran 2022-10-30 à 11 59 34](https://user-images.githubusercontent.com/102034752/198876387-0cad2e5e-769c-42ba-9a42-61212faf6cdb.png)
![Capture d’écran 2022-10-30 à 12 22 12](https://user-images.githubusercontent.com/102034752/198876388-f1a70b90-3761-4e7e-ab89-db2365e84a06.png)
![Capture d’écran 2022-10-30 à 12 22 39](https://user-images.githubusercontent.com/102034752/198876389-0f5c7f11-194b-460f-9520-322dbb311ca8.png)

**Comment by sean-mcmanus** [comment]
The include path `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1` appears incorrect -- it's for C++ and it seems like your intention is to use C. Do you know where that is coming from? Also, you Makefile Tools set as your configuration provider. Does your logging show what info they're sending us? They may be sending us incorrect configuration info.
