### ISSUE TITLE
Clang-Tidy analysis appears to be stuck (macOS)

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#10090]
Type: <b>Bug</b>

It looks like clang-tidy is stuck. Probably the same old IntelliSense issue. I think that doc comment tooltips also failed.

Extension version: 1.13.3
VS Code version: Code 1.72.2 (Universal) (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:30.254Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id a7eaff19-94ae-4653-b917-d9aaab19da5d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30566497
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by H-G-Hristov** [comment]
Log: 
[login-test.log.zip](https://github.com/microsoft/vscode-cpptools/files/9903805/login-test.log.zip)

**Comment by sean-mcmanus** [comment]
@H-G-Hristov Did you attach the wrong log? Do you mean the clang-tidy process is stuck or cpptools? Can you get a call stack when it's stuck? Or other repro info?

**Comment by H-G-Hristov** [comment]
> @H-G-Hristov Did you attach the wrong log? Do you mean the clang-tidy process is stuck or cpptools? Can you get a call stack when it's stuck? Or other repro info?

I'm seeing the flame (clang-tidy): Running clang-tidy 0/1 - that was yesterday.
Now I see: Updating IntelliSense: Running clang-tidy 0/1

It looks like the situation in 1.13.3 got worse for me than on 1.13.2 on Apple Silicon + Ventura.

**Comment by H-G-Hristov** [comment]
Maybe related issue:
https://github.com/microsoft/vscode-cpptools/issues/10091
https://github.com/microsoft/vscode-cpptools/issues/9688

**Comment by H-G-Hristov** [comment]
It seems that on opening a new CPP file the clang-tidy is not spawned. Here are two logs - one is from when opening a file and clang-tidy is working OK and the other one when clang-tidy is not working.
[Archive.zip](https://github.com/microsoft/vscode-cpptools/files/9914335/Archive.zip)

**Comment by sean-mcmanus** [comment]
It looks like you're using the runAutomatically mode and it's not being run on open.

**Comment by H-G-Hristov** [comment]
I answered some of your question here: https://github.com/microsoft/vscode-cpptools/issues/10091#issuecomment-1299648927

runAuthomatically is on
clangTidy enabled is on

I wrote here:
https://github.com/microsoft/vscode-cpptools/issues/10091#issuecomment-1299653680

> What I am experiencing right now. After I start VSCode and I open a C++ file. Clang-tidy runs and displays some results. I continue working in the code editor - random stuff - editing, opining more files, and after a while I don't see the yellow squiggles anymore and the flame is stuck forever.

**Comment by H-G-Hristov** [comment]
Something which may be important I have the following setting to mimic Xcode and other Apple apps behavior:
`  "files.autoSave": "afterDelay",`
I've noticed that it is causing some issues with the cmake extension when I edit CMakeLists.txt, because cmake is called too often. Maybe something similar is happening with clang-tidy.

**Comment by sean-mcmanus** [comment]
Ah, yeah, the autoSave afterDelay could be a factor, since we do that check that setting when changes are made in order to cancel clang-tidy earlier, since the pending save would cancel it anyways. I'll see if I can repro/find an issue with that...

**Comment by sean-mcmanus** [comment]
@H-G-Hristov And it sounds like you believe this is a regression compared to 1.13.2? We didn't make an intentional change in this area of code, but there were some widespread internal changes that may have caused the regression, which I could look into.

**Comment by H-G-Hristov** [comment]
One more fact: I am also sometimes rebuilding my project from the command line on the built-in terminal by calling a build script, which is calling cmake to reconfigure and build the project. I have noticed that rebuilding from the CLI also impacts the project while it is opened in VSCode.

**Comment by cjwijtmans** [comment]
Is cmake canceling a configure job when a new configure job is spawned? Because i think thats the issue.

**Comment by H-G-Hristov** [comment]
@sean-mcmanus This issue on macOS continues to plague me. Is there something I can do to help get more info?

**Comment by sean-mcmanus** [comment]
Sorry about that. I just need investigate. Looking into some clang-tidy issues like this has been on my TODO list for a while.

**Comment by sean-mcmanus** [comment]
I wasn't able to repro this yet. We fixed some clang-tidy issues with 1.15.0: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.0 . Are you still reproing this?

**Comment by H-G-Hristov** [comment]
@sean-mcmanus In the past couple of months I did use the C++ extension a little less than usual for C++ so I wasn't quite sure if the issues was fix. I believe it is much better now but somehow after I type in the changes it takes too long to get back the new results, it almost feels like the analysis gets stuck. Maybe it is normal I have no idea. I am using the most basic model M1 Pro, 8 core, 16Mb.

**Comment by H-G-Hristov** [comment]
@sean-mcmanus As of today the clang-tidy checks work much, much better. They even update much faster I think.
I feel that the feature is already usable and complete on macOS.
Thank you very much for the great work.
