### ISSUE TITLE
cannot change tabsize (stuck on the default 4)

### ISSUE THREAD

**Issue by ehsangifani** [microsoft/vscode-cpptools#1009]
Following documentation, I used :
"C_Cpp.clang_format_fallbackStyle": "{BasedOnStyle: none, UseTab: true, IndentWidth: 8, ColumnLimit: 80}"
and also
"C_Cpp.clang_format_fallbackStyle": "{BasedOnStyle: LLVM, UseTab: true, IndentWidth: 8, ColumnLimit: 80}"
and even
"C_Cpp.clang_format_fallbackStyle": "{BasedOnStyle: Visual Studio, UseTab: true, IndentWidth: 8, ColumnLimit: 80}"
and even the example provided in 'setting'
"C_Cpp.clang_format_fallbackStyle": "{BasedOnStyle: LLVM, IndentWidth: 8}"
But it didn't work

**Comment by horvay** [comment]
I couldn't get this to work either. What worked for me eventually was creating a .clang-format file, and putting the following:
```
UseTab: Never
IndentWidth: 4
BreakBeforeBraces: Allman
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
NamespaceIndentation: All
AccessModifierOffset: -4
PointerAlignment: Left
```

Obviously you'll have to change it to 8. Also you may want to try setting editor.detectIndentation to false in your settings file.

**Comment by sean-mcmanus** [comment]
@ehsangifani "true" is not a valid value for UseTab. What are the results of the formatting? Is the ColumnLimit setting working? I am able to get the fallbackStyle setting to be used. Your `C_Cpp.clang_format_style` needs to be "file" (the default). Also, no .clang-format file can exist in the workspace or any of its parent folders.

**Comment by ehsangifani** [comment]
Well UseTab was mentioned in the [doc](https://code.visualstudio.com/docs/languages/cpp) but was undocumented regarding its value so I assumed 'true' would be logical. Anyhow, none of the settings work. The key-values inside the fallbackStyle have no effect whatsoever; only my editor's defaults get used.
`C_Cpp.clang_format_style` is the default 'file' and there is no .clang-format file.
And I even tried `"C_Cpp.clang_format_fallbackStyle": "{IndentWidth: 8}"` which didn't work.

I think it's helpful if I add the following info as well:
- OS: Windows 10 x64 Home
- VSCode 1.15.1
- my tabSize is set on the default `"editor.tabSize": 4`

_I changed `"editor.tabSize":` to 2 and then checked my .c file. Then I deleted the setting but tabSize of 2 persisted although it was now set to the default `"editor.tabSize": 4`. And I had to close VSCode and reopen it to get my setting back. Therefore, it is possible that this problem is the result of a bug in VSCode itself._

**Comment by sean-mcmanus** [comment]
Do you have a _clang-format file? We also look for that. Do any of these below have an effect?

`"C_Cpp.clang_format_fallbackStyle": "{ ColumnLimit: 5 }"`
`"C_Cpp.clang_format_style": "{ ColumnLimit: 5 }"`

It sounds like the fallbackStyle is failing to be used at all. I don't see any places in the code where a bug could exist. I think we me need a repro somehow so we can debug it. Does this problem occur with a simple workspace with a single C++ file?

**Comment by sean-mcmanus** [comment]
Yeah, and the docs are confusing and not really accurate when it says "(VS Code current setting)". I'll see if I can get someone to fix it. It should say that the Visual Studio style uses the "Never" when editor.insertSpaces is true and "Always" otherwise. And IndentWidth is set to the editor.tabSize value, which also sets TabWidth (missing from the list in the docs), although if editor.detectIndentation is true (the default), then VS code may overwrite the tabSize with whatever it computes for the current document.

**Comment by bobbrow** [comment]
Are you still having problems with formatting?

Can you please try out 0.16.0 and look at the "C/C++" log channel of the Output window when your formatting fails? If you are unable to resolve your clang-format issues with the logging message, please reopen this issue and we can take another look.
