### ISSUE TITLE
Unable to load schema from c_cpp_properties.schema.json

### ISSUE THREAD

**Issue by realjf** [microsoft/vscode-cpptools#10095]
Type: <b>Bug</b>

Problems loading reference 'schemaservice://combinedschema/cpptools-schema:/c_cpp_properties.schema.json': Unable to load schema from 'schemaservice://combinedschema/cpptools-schema:/c_cpp_properties.schema.json': cannot open schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json. Detail: Unable to resolve resource schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json.

Extension version: 1.12.4
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.15.0-kali3-amd64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.29GB (22.24GB free)|
|Process Argv|--unity-launch --crash-reporter-id 8527ce77-6f2c-426c-b4e8-635453e80430|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by browntarik** [comment]
Could you explain the steps you took to create this error message?

**Comment by bobbrow** [comment]
I think this is a VS Code issue.  I see a similar issue resolved a while ago here: https://github.com/microsoft/vscode/issues/115419

**Comment by realjf** [comment]
Steps to Reproduce:

1. Install the latest version of VS Code and install the extensions: C/C++ Extension Pack

2. Create .vscode/c_cpp_properties.json with the following content:
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-linux-gnu/11/include",
                "/usr/include/c++/11"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++-11",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.makefile-tools",
            "browse": {
                "path": [
                    "${workspaceFolder}/**",
                    "/usr/local/include",
                    "/usr/include",
                    "/usr/lib/gcc/x86_64-linux-gnu/11/include",
                    "/usr/include/c++/11"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 4
}
```
3. I'm getting the following error in the "PROBLEMS" tab:
```json
[{
	"resource": "/home/realjf/cpp_projects/cli_demo/.vscode/c_cpp_properties.json",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'schemaservice://combinedschema/cpptools-schema:/c_cpp_properties.schema.json': Unable to load schema from 'schemaservice://combinedschema/cpptools-schema:/c_cpp_properties.schema.json': cannot open schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json. Detail: Unable to resolve resource schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
```

**Comment by browntarik** [comment]
Thank you for providing these steps. I am currently investigating this issue closely and will get back to you soon.
