### ISSUE TITLE
Add a "Find All Definitions" feature, to find all definitions of the same name

### ISSUE THREAD

**Issue by andy1990zx** [microsoft/vscode-cpptools#10094]
### Environment

- OS and Version: Windows 11 22621
- VS Code Version: 1.72.2
- C/C++ Extension Version: v1.13.3
- Other extensions you installed (and if the issue persists after disabling them):  the issue persists after disabling all others
- If using SSH remote, specify OS of remote machine:  no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
10000+ files project, we have typedef UINT64 UINTN; in many .h files for different CPU types.
If I click [Go To Definition], I expect VSCODE to list all typedef, but it jump to one of them directly.

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

### Code sample and Logs

```shell
X64.h: typedef UINT64 UINTN;
IA32.h: typedef UINT32 UINTN;
AArch64.h: typedef UINT64 UINTN;
......

somefile.c:
{
  UINTN xx;
  ......
}

[Go To Definition] for the UINTN in somefile.c, it jump to the AArch64.h directly, not list all typedef.

Logs:

textDocument/definition: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\AmiModulePkg\EfiOsBootOptionNames\EobonPriorityMap\EobonPriorityMap.c (id: 106)
textDocument/hover: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\AmiModulePkg\EfiOsBootOptionNames\EobonPriorityMap\EobonPriorityMap.c (id: 107)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\AmiModulePkg\EfiOsBootOptionNames\EobonPriorityMap\EobonPriorityMap.c (id: 108)
cpptools/activeDocumentChange: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\AmiModulePkg\EfiOsBootOptionNames\EobonPriorityMap\EobonPriorityMap.c
textDocument/definition: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\AmiModulePkg\EfiOsBootOptionNames\EobonPriorityMap\EobonPriorityMap.c (id: 109)
cpptools/getCodeActions: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\MdePkg\Include\AArch64\ProcessorBind.h (id: 110)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\MdePkg\Include\AArch64\ProcessorBind.h
cpptools/getFoldingRanges: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\MdePkg\Include\AArch64\ProcessorBind.h (id: 111)
cpptools/getCodeActions: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\MdePkg\Include\AArch64\ProcessorBind.h (id: 112)
textDocument/hover: D:\Project\XuanWu2.0\EagleStream_Xuanwu20_BIOS_develop\Code\MdePkg\Include\AArch64\ProcessorBind.h (id: 113)
idle loop: reparsing the active document
loggingLevel has changed to: Error
$/setTrace
cpptools/didChangeSettings
Enhanced Colorization is enabled.
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
```

### Screenshots

When I use Source Insight on the same project, it behaviors correctly.

![image](https://user-images.githubusercontent.com/37032134/199149154-3143aa1a-8d8a-4b63-994b-3e2b6e888bbe.png)

**Comment by andy1990zx** [comment]
Also I found some similar issues.
Could you help show me how to debug such case? Maybe where is the tag file, how does it generated, and what happend whiling generating.

**Comment by Colengms** [comment]
Hi @andy1990zx .  When `Go To Definition` is used on a type, the currently intended behavior of the C/C++ Extension is that it navigates only to the definition of that type associated with the occurrence you had issued the operation on.  This is by-design.  Would you like to use this issue as a Feature Request for a (i.e.) "Find All Definitions For Name" feature?

**Comment by Colengms** [comment]
Hi @andy1990zx .  The C/C++ Extension performs a semantic scan of the source file.  When using `Go To Definition` on the use of a type, it knows exactly which typedef or struct/class declaration, etc., is associated with that name when that file is compiled.  Find All References and Rename features are similar, in that they only find references to the semantic type you referred to, and not other types that have the same name.  That behavior is useful if you have different types of the same name used in different parts/libraries of a large project.

I think the usual pattern is that a type is defined in a header, and sources that need that type include that common header.  Redefining the same type in many places seems less common.  But we do generally prioritize community feedback, particularly when up-voted by multiple users.

If you want to disable all semantic features, you could set:

```
"C_Cpp.intelliSenseEngine": "Tag Parser",
```

Without semantic information, that would fall back to behavior that would cast a wider net.  In that case `Go To Definition` would return all results with the same name.  But that would seem to disable various other features.  So, perhaps a `Find All Definitions` would be a useful addition.

**Comment by andy1990zx** [comment]
> 

Hi @Colengms , thanks, that means the C/C++ Extension did a "automatic" selection in the default intelliSenseEngine setting.
But it obviously made a mistake at least in my case, we have different *.h for different typedef, and the proper *.h is decided by build time from some makefile definition or build parameters. BTW, we are developing BIOS firmware base on EDK2 open source code.
So back to the issue here, I think the best suggestions is:
To improve intelliSenseEngine [default] setting code logic, if it can't find proper definition, just show all.


BTW, after change intelliSenseEngine to By Tag, I found perhaps a new issue:
After I use [Go To Definition] on a BOOLEAN, it shows typedef BOOLEAN (XXXX) ();
But this is a typedef of function, not typedef variable type.
![image](https://user-images.githubusercontent.com/37032134/200251082-d33f43ab-4928-4fb7-a994-46c091f160f7.png)

**Comment by andy1990zx** [comment]
> 
@Colengms Are you still there?

**Comment by sean-mcmanus** [comment]
@andy1990zx I think he may have missed your message earlier -- he should be back later this week.

**Comment by Colengms** [comment]
Hi @andy1990zx .   Using the default IntelliSense mode, IntelliSense will try its best to associate headers with include statements.  This logic isn't perfect.  (Header file searching varies slightly between compilers and platforms).  But it should be possible to configure the C/C++ Extension to match a particular build configuration, such as by specifying only specific include paths used by a particular build config.  Configuration provider extensions, such as CMake Tools and Makefile Tools, can configure IntelliSense directly based on information from a build system.

> To improve intelliSenseEngine [default] setting code logic, if it can't find proper definition, just show all.

When the default IntelliSense engine fails to locate a definition, it should fall back to Tag Parser mode and provide a list of all found candidates.  Is that not what you are seeing?

> BTW, after change intelliSenseEngine to By Tag, I found perhaps a new issue:

It looks like it's incorrectly interpreting typedefs of function pointer types as typedefs of the return type.  I believe I've seen this before and it has to do with the macro (in your case `EFIAPI`) confusing the tag parser.  I was able to repro this issue, then address it by adding `#define EFIAPI` to a `cpp.hint` file.  Some background on `cpp.hint` files and why they are needed, is here: https://learn.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170

**Comment by andy1990zx** [comment]
> 

Hi @Colengms , I've learned the cpp.hint knowledge, thanks.
Back to my case, because in BIOS developing, we have both 32bit and 64bit CPU environments, also we need to support different CPU archs. So our codebase have different *.h to typedef , e.g.
For X64: typedef UINT64 UINTN; in MdePkg/Include/X64/ProcessorBind.h
For IA32: typedef UINT32 UINTN; in MdePkg/Include/Ia32/ProcessorBind.h
For ARM: typedef UINT64 UINTN; in MdePkg/Include/AArch64/ProcessorBind.h
......

`Go To Definition` always jump to the third typedef without any hinting or warning.

I don't know is VS Code is able to deal with such case. Need your suggestion:
1. Show all of the typedefs just as other tool
2. Maybe add a new feature "Find All Definitions For Name"?

**Comment by sean-mcmanus** [comment]
@andy1990zx Is using Find All References sufficient?

**Comment by andy1990zx** [comment]
> 

@sean-mcmanus To solve my problem, `Find All References` is not sufficient: 
![image](https://user-images.githubusercontent.com/37032134/202995605-46ae375b-8d8d-4b86-be3a-364cbf9cacef.png)
![image](https://user-images.githubusercontent.com/37032134/202996021-f2e7a133-855f-4972-baab-6aaed617ace9.png)
Of cause I can locate the correct typedef which is in MdePkg/Include/X64/ProcessorBind.h manually.

But the value discuss here is to design a good feature that let VS Code could find the correct typedef or just list all.

**Comment by sean-mcmanus** [comment]
Feature https://github.com/microsoft/vscode-cpptools/issues/4245 would sort of cover this. (i.e. enable finding all definition references).

**Comment by andy1990zx** [comment]
> 
@sean-mcmanus actually, it's not "sufficient" but "too much".
`Find All References` will show tens of thousands of code lines...

So what I want is to find the typedef UINTN XXXX accurately.

**Comment by sean-mcmanus** [comment]
Yeah, I mean if we had the ability to only find definition references then in theory it would include the other definitions and not the thousands of use references.

**Comment by andy1990zx** [comment]
> 

@sean-mcmanus Yes, that should be OK.

**Comment by Colengms** [comment]
> Go To Definition always jump to the third typedef without any hinting or warning.

Hi @andy1990zx .  

If you're using 'Tag Parser' mode, there is not enough information available to determine which of those definition is the active definition.  That would require parsing code semantically such that #if/#ifdef are interpreted based on the macros that have been defined in the configuration.  So, that behavior is 'by design' for Tag Parser mode.

If I understand correctly, I think we should repurpose this issue as a feature request for "Find All Definitions", to make it possible to find all definitions of the same name without having to disable semantic IntelliSense.
