### ISSUE TITLE
Prioritize parsing opened files

### ISSUE THREAD

**Issue by jmlewis1** [microsoft/vscode-cpptools#101]
Currently, you seem to parse in whatever order you find files in.

On a large project this is annoying.  If I explicitly open some file, those symbols may not become available until much later, when you finally get around to parsing that file.

It would be smarter if you could prioritize parsing any files I open first, then continue parsing other files in the background, to make code usable much faster.

Currently, I've never been able to finish parsing my entire project, due to the other bug of you deleting the database file on ever VS Code restart.

Either way, it takes many hours, possibly longer than a day, to parse my entire source tree, which means Code is unusable for most of that time, since it won't get to the files I'm actually looking at until some random time during its parsing.

**Comment by jgoshi** [comment]
This is fixed and will appear in the next release (version 0.9.0)
