### ISSUE TITLE
The C/C++ extension installed does not match your system

### ISSUE THREAD

**Issue by mfaghani** [microsoft/vscode-cpptools#10104]
### Environment

- OS and version:
- VS Code:
- C/C++ extension:
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do '...'
4. See error...

**Comment by sean-mcmanus** [comment]
I don't repro the issue. Are you installing the extensions via the VS Code extensions window? If so, it would be a bug with them: https://github.com/microsoft/vscode/issues

Maybe try uninstalling, reloading window, and then reinstalling?

Why are you referencing manualling installing the Alpine Linux arm64 vsix when you seem to be on Windows?

**Comment by mfaghani** [comment]
I'm running on Win 10 64-bit and I can not install from VS Code Extension window because of some internet problem. So VS Code gives me a link to download vsix manually and that downloads this file: 'mailto:ms-vscode.cpptools-1.12.4@alpine-arm64.vsix'. How can I get the vsix for Win 10 64-bit?

**Comment by mfaghani** [comment]
> I have the same problem with this extension. Did you download the extension using a VPN too? Can it be the reason why the downloaded VSIX doesn't match the system?

I get 'XHR failed' while using a VPN.

**Comment by sean-mcmanus** [comment]
@mfaghani It sounds like VS Code is giving you the wrong URL (sounds like it's there bug, although it would help to see exactly what message you're seeing). You should install the Windows x64 one from https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history .

**Comment by mfaghani** [comment]
@sean-mcmanus I uninstalled PlatformIO IDE and C/C++ extention in order to reproduce error messages for you. First I tried to install the C/C++ extension from the VS Code and probably because of some Internet problems, it showed me a pop up message with a 'Download VSIX manually' button as follows:
`Error while installing 'C/C++' extension. Please check the [log](command:workbench.action.showWindowLog) for more details.`
and the log messages in OUTPUT Log (Window) are as follows:
```
[2022-11-03 22:57:50.543] [renderer1] [error] RequestService#request (browser) - error https://ms-vscode.gallerycdn.vsassets.io/extensions/ms-vscode/cpptools/1.12.4/1661989482765/Microsoft.VisualStudio.Code.Manifest?targetPlatform=win32-x64 {}
[2022-11-03 22:58:21.318] [renderer1] [error] RequestService#request (browser) - error https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools/1.12.4/assetbyname/Microsoft.VisualStudio.Code.Manifest?targetPlatform=win32-x64 {}
[2022-11-03 22:58:21.328] [renderer1] [error] Error: XHR timeout: undefinedms
    at v.ontimeout (vscode-file://vscode-app/c:/Users/OSTAD/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:8904)
[2022-11-03 22:58:21.331] [renderer1] [error] XHR timeout: undefinedms: Error: XHR timeout: undefinedms
    at v.ontimeout (vscode-file://vscode-app/c:/Users/OSTAD/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:8904)
```
Clicking the download bottun leads to download the following vsix file which perhaps is the wrong file for Windows OS:
`ms-vscode.cpptools-1.12.4@alpine-arm64.vsix`
After download completes, a pop up with following message and the 'Install from VSIX...' button appears:
`Once downloaded, please manually install the downloaded VSIX of 'ms-vscode.cpptools'.`
By clicking the button and choosing the vsix file, and finally reloading VS Code, following pop up appears:
`Completed installing C/C++ extension from VSIX.`
Now after reloading VS Code, I get following two message pop ups when I open a cpp file:
`Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at c:\Users\OSTAD\.vscode\extensions\ms-vscode.cpptools-1.12.4\bin\cpptools.exe`
`The C/C++ extension installed does not match your system.`
and following massages in Log (Window):
```
[2022-11-03 23:15:48.332] [renderer1] [error] RequestService#request (browser) - error https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json {}
[2022-11-03 23:16:39.880] [renderer1] [error] [Extension Host] (node:3060) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
```

**Comment by Colengms** [comment]
Hi @mfaghani .  I assume you're not running on an Arm64 Alpine Linux machine, correct?  :)  As Sean mentioned, this appears to be a VS Code or VS Code Marketplace bug.  Our extension includes native binaries, so the appropriate install media (VSIX) must be used for the target platform.  We attribute our VSIX's with information that identifies their target platforms when we publish them to the marketplace.  If the wrong VSIX is being offered, that would seem to be an issue with either VS Code or VS Code Marketplace.  Would you like to open this issue in [the VS Code repo](https://github.com/microsoft/vscode/issues)?

**Comment by mfaghani** [comment]
Hi @Colengms, thanks. Correct, I'm not running on an Arm64 Alpine Linux machine. Now I just need to know where I can download the correct VSIX. Will that be any help if I open this issue in [the VS Code repo](https://github.com/microsoft/vscode/issues)? And should I close this issue here? Please let me know.

**Comment by Colengms** [comment]
Hi @mfaghani .  You should be able to download the correct extension here: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

If you click on the `Download Extension` drop-down, it should offer downloads for each platform:

![image](https://user-images.githubusercontent.com/49173979/200391832-18d39e7d-c9a1-4108-87ba-a848c6770521.png)

Yes, please open an issue in the VS Code repo.  https://github.com/microsoft/vscode/issues  Or, if you'd prefer not to, I can follow up.  I like to give people the opportunity to do that, so the person experiencing the issue essentially owns the issue in the other repo, and is on the thread if they ask follow-up questions.

I'll close this one as external.
