### ISSUE TITLE
Debugger throws error "stdout maxBuffer exceeded"

### ISSUE THREAD

**Issue by marcoschou** [microsoft/vscode-cpptools#10107]
Type: <b>Bug</b>

1. Open a c++ project
2. Set up your launch.json. Th debug task specifies the process ID as  "processId":"${command:pickProcess}".
3. Run -> Start Debugging
4. The error "stdout maxBuffer exceeded is thrown"

Extension version: 1.12.4
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.76.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.76.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.34GB free)|
|Process Argv|--crash-reporter-id 786768c0-d188-4f92-a2ad-02c742f90339|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|OS|Linux x64 3.10.0-1160.76.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (64 x 999)|
|Memory (System)|125.42GB (42.72GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: nueli6047.nurnberg.cd-adapco.com|
|OS|Linux x64 3.10.0-1160.76.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (64 x 999)|
|Memory (System)|125.42GB (42.69GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
3d0df643:30602300

```

</details>

**Comment by WardenGnaw** [comment]
Looks like the new API we added in https://github.com/microsoft/vscode-cpptools/commit/4016be17d05380e5af074ae8591c1c174cb0b1d9 for listing processes on window produces a lot for data.

We should move to child_process.spawn to not have a buffering issue.
https://github.com/microsoft/vscode-cpptools/blob/4016be17d05380e5af074ae8591c1c174cb0b1d9/Extension/src/Debugger/nativeAttach.ts#L172
