### ISSUE TITLE
Can't attach to process on Windows: Unexpected token \ in JSON at position 31227

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode-cpptools#10108]
### Environment

- OS and version: Windows 21H1 (Windows_NT x64 10.0.19043)
- VS Code: 1.73.0 (user setup)
- C/C++ extension: v1.12.4
- OS and version of remote machine (if applicable): /
- GDB / LLDB version: GNU gdb (GDB) (Cygwin 9.2-1) 9.2

### Bug Summary and Steps to Reproduce

Steps to reproduce:
1. Open a new empty folder in VS Code
2. Create a new `launch.json` file (see debugger configurations)
4. Start debugging/Press F5
5. See error:

   > [Window Title]
   > Visual Studio Code
   > 
   > [Content]
   > Unexpected token \ in JSON at position 31227
   > 
   > [Open "launch.json"] [Cancel]

### Debugger Configurations

```shell
// launch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "windows attach",
			"type": "cppvsdbg",
			"request": "attach",
			"processId": "${command:pickProcess}"
		}
	]
}
```

### Debugger Logs

```shell
not applicable
```

### Other Extensions

The problem persists if all other extensions are disabled.

### Additional Information

Logs from the extension host:

```
SyntaxError: Unexpected token \ in JSON at position 31227
    at JSON.parse (<anonymous>)
    at Function.ParseProcessFromCim (c:\Users\Christoph\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:36110:35)
    at CimAttachItemsProvider.<anonymous> (c:\Users\Christoph\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:36101:37)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\Christoph\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\dist\main.js:35896:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) extension.pickNativeProcess {"value":"ms-vscode.cpptools","_lower":"ms-vscode.cpptools"}

```

**Comment by WardenGnaw** [comment]
Can you share the output of `Get-CimInstance Win32_Process | Select-Object Name,ProcessId,CommandLine | ConvertTo-JSON` from your machine? 

If that fails can you just run `Get-CimInstance Win32_Process | Select-Object Name,ProcessId,CommandLine`

**Comment by LinqLover** [comment]
> Can you share the output of `Get-CimInstance Win32_Process | Select-Object Name,ProcessId,CommandLine | ConvertTo-JSON` from your machine?

Sure, here you are: [procs.json.txt](https://github.com/microsoft/vscode-cpptools/files/9954552/procs.json.txt)

**Comment by WardenGnaw** [comment]
With the large output, my guess its being affected by the buffer size which should be resolved by: https://github.com/microsoft/vscode-cpptools/pull/10119

**Comment by LinqLover** [comment]
Wow, thank you! This change is not yet (pre)released, is it? If I should try out the patch, could you maybe send me a VSIX bundle so I do not need to rebuild it from scratch?

**Comment by WardenGnaw** [comment]
This has been added to version v1.13.4 and later.
