### ISSUE TITLE
No symbol found in all my .cpp files on Linux CentOs7

### ISSUE THREAD

**Issue by tonimoro** [microsoft/vscode-cpptools#1011]
Hi,

Visual Code seems great and I would like to make a try. Unfortunately, I get a problem with the C/C++ extension. When I open any of my cpp file and then press "ctrl+shit+o" to view the symbols , no symbol are found. In the same way, go to defintion always returns "No definition found for..."
All my includes files are well regonized (I don't see any green squiggle ) . Is there a way to force the symbol list generation ? or to check that the symbol generation is ok ?
Moreover I don't see any flam indicator in the bottom blue line to show that a tag parsing is currently running...

I am complete newbee in Visual Code , maybe I miss something...

Regards.

Visual studio code 
Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959
Date 2017-08-16T17:16:27.618Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64

**Comment by tonimoro** [comment]
One more detail, I saw that I have no "vc.db" file present in the .vscode folder. Only  the "c_cpp_properties.json"file

**Comment by sean-mcmanus** [comment]
Our extension process won't run on CentOS7 due to a dependency on glibc 2.18. See https://github.com/Microsoft/vscode-cpptools/issues/19 for a potential workaround.

**Comment by tonimoro** [comment]
ok thanks. It's ok now with the workarounk provided in the previous thread.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4, so the workaround is no longer needed.
