### ISSUE TITLE
Persistent error when trying to include file

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#10118]
### Environment

- OS and Version: `Windows 10`
- VS Code Version: `v1.73.0`
- C/C++ Extension Version: `v1.3.0`
- Other extensions you installed (and if the issue persists after disabling them): `Irrelevant - disabling all extensions doesn't stop the bug from ocurring`
- If using SSH remote, specify OS of remote machine:  -
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc): `The workspace is a single project with multiple files - an error occurs when trying to include a file (using #include <fileiwant>) - the "squiggle" of the error shows only 1 line before the actual path inputted on the include statement (see images) and additionally changing the line affected won't delete the error - it will remain the same and cannot be deleted no matter what.`

### Bug Summary and Steps to Reproduce

Bug Summary:
- There is a constant error "squiggle" reported on the first line of the file even when commented out and restarting vscode.
- Moving the line moves the error to a different line and even when deleting the entire line the error still persists.
- The error is always an include exception saying the file "chould not be found" even though i have included it's path within my c++ settings.
- The squiggle itself can change size according to context - for example when moving it i've found it sometimes hooks onto other items such as `int` and will fill 3 spaces for the 3 letter in `int`.
- I found sometimes multiple errors were occuring on the same line all of similar nature (involving a path error)

Steps to reproduce:
Uknown. Namely i just installed the C++ extension and configured it with default settings according to the instructions shown here https://code.visualstudio.com/docs/languages/cpp.

### Expected behavior

I expect the squiggle to dissapear when there is no error or the line has been commented out or changed. I also expect the error to highlight the entire line affected not the line before - the error "squiggle" shouldn't be persistent and unkillable either ;P

#### Script (BasicHook.cpp)
```shell
#include "<mono/jit/jit.h>"
#include "<mono/metatdata/assembly.h>"

// Mono\include\mono-2.0\mono\jit

// https://www.mono-project.com/docs/advanced/embedding/

/*
int main(int argc, char *argv[]){
    // Initialize
    MonoDomain *domain;
    domain = mono_jit_init ("Cheese");

    // Load
    MonoAssembly *assembly;

    assembly = mono_domain_assembly_open (domain, "D:/BroMods/BroforceModSoftware/bin/Debug/netcoreapp3.1/BROMODS.exe");
}*/
```
#### Config (c_cpp_properties.json)
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/Mono/include/mono-2.0"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/msys64/mingw64/bin/gcc.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-gcc-x64",
            "configurationProvider": "ms-vscode.cpptools"
        }
    ],
    "version": 4
}
```
### Screenshots
```
https://user-images.githubusercontent.com/59062738/200187437-3bd5215c-0b45-466c-aca4-9e6c65267a46.png
https://user-images.githubusercontent.com/59062738/200188015-f2f540a0-4180-4b26-a234-1ceae3496942.png
https://user-images.githubusercontent.com/59062738/200188030-baa6f015-818e-4e56-905c-07231d7635bc.png
```
### Additional context
I have already tried instructions at these following links:
- https://stackoverflow.com/questions/45583473/include-errors-detected-in-vscode
- https://stackoverflow.com/questions/57324999/vs-code-thinks-first-line-of-any-file-is-an-include-error
- https://stackoverflow.com/questions/51883754/visual-studio-code-gives-me-include-error-detected-for-c
- https://stackoverflow.com/questions/57458423/vscode-not-recognizing-includes-from-includepath

Also to note i have tried clearning cache, Reinstalling the extension, Deleting the file and creating a new one, Double - triple checking the path included is correct and yet still no luck. The behaviour the bug presents is identical to this issue --> https://stackoverflow.com/questions/57324999/vs-code-thinks-first-line-of-any-file-is-an-include-error 

Edit: Oh, also if it helps; I've tried changing compilers, (G++, GCC, CPP, CL) and intellisense mode.

**Comment by sean-mcmanus** [comment]
Can you remove `"configurationProvider": "ms-vscode.cpptools"`?

What version of the C/C++ extension are you using? Your bug report shows `1.3.0` which is very old.

**Comment by Loki-Hornsby** [comment]
I belive i'm on the latest version so `v1.12.4`. Additionally i've already tried removing `"configurationProvider": "ms-vscode.cpptools"` and yet no luck. I actually tried adding that line to resolve the issue. This ones really got me stumped.

**Comment by sean-mcmanus** [comment]
Can you provide the output from running the C/C++: Log Diagnostics command from the Command Palette? That should show what include paths are being used for configuring IntelliSense. It's probably missing a required path.

**Comment by Loki-Hornsby** [comment]
Also to note i've tried multiple variations of the same path. As aforementioned 3 errors may occur on the same line - after including these paths the issue is normally resolved excluding of course the last error squiggle which still remains.

`-------- Diagnostics - 08/11/2022, 08:07:20
Version: 1.13.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "C:/Mono/include/mono-2.0"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/msys64/mingw64/bin/g++.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-clang-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "C:/Mono/include/mono-2.0"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\BroMods\BroforceModEngine\BroforceEngineHook\BasicHook.cpp ]:
    D:\BroMods\BroforceModEngine\BroforceEngineHook\BasicHook.cpp
Translation Unit Configurations:
[ D:\BroMods\BroforceModEngine\BroforceEngineHook\BasicHook.cpp ]:
    Process ID: 7276
    Memory Usage: 24 MB
    Compiler Path: C:\msys64\mingw64\bin\g++.exe
    Includes:
        C:\Mono\include\mono-2.0
        C:\msys64\mingw64\include\c++\12.2.0
        C:\msys64\mingw64\include\c++\12.2.0\x86_64-w64-mingw32
        C:\msys64\mingw64\include\c++\12.2.0\backward
        C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\12.2.0\include
        C:\msys64\mingw64\include
        C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\12.2.0\include-fixed
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++17
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=120200
Total Memory Usage: 24 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3420`

**Comment by Loki-Hornsby** [comment]
Oh also to note i was testing out a prerelease earlier to see if that changed anything hence the version number is `v1.13.3`

**Comment by sean-mcmanus** [comment]
Oh, sorry, I didn't look at the errors in your screenshot before -- those errors are coming from your gcc build task and not our extension. You need to add a "-I", and "C:\\Mono\\include\\mono-2.0" to the args in your tasks.json.

**Comment by Loki-Hornsby** [comment]
Awesome - it works! Thankyou @sean-mcmanus your help does not go underappreciated. 
I'd also like to point out that there was a spelling mistake in `<mono/metatdata/assembly.h> --> metatdata` and i needed to have `int main` uncommented otherwise the extension doesn't work correctly - sorry about that on my part i'm fairly new to this in terms of c++.
