### ISSUE TITLE
compile_commands.json with bear not work in vscode

### ISSUE THREAD

**Issue by ewall-cauc** [microsoft/vscode-cpptools#10117]
### Environment

- OS and version: ubuntu20.04
- VS Code: 1.73.0
- C/C++ extension: C/C++ , C/C++ Extension Pack 
- OS and version of remote machine (if applicable):
- GDB / LLDB version: gdb  9.2

### Bug Summary and Steps to Reproduce

Bug Summary:
   bear compile project, then generate compile_commands.json, add config  compileCommands: ${workspaceFolder}/compile_commands.json, and reload project

### Debugger Configurations

```shell
{
    "configurations": [{
        "name": "Linux",
        "includePath": [
            "${default}"
        ],
        "defines": [],
        "compilerPath": "/usr/bin/clang",
        "cStandard": "c17",
        "cppStandard": "c++14",
        "intelliSenseMode": "linux-clang-x64",
        "compileCommands": "${workspaceFolder}/compile_commands.json",
        "configurationProvider": "ms-vscode.cmake-tools"
    }],
    "version": 4
}
```

### Debugger Logs

```shell
no output
```

**Comment by sean-mcmanus** [comment]
Can you remove `"configurationProvider": "ms-vscode.cmake-tools"`? What errors are you getting? Can you give an example of a compile commands entry that is giving a problem?
