### ISSUE TITLE
"Switch header/source" in split view always opens a new file in current editor group

### ISSUE THREAD

**Issue by windless0530** [microsoft/vscode-cpptools#10127]
### Environment

- OS and version: OS X Ventura 13.0
- VS Code: 1.73.0
- C/C++ extension: v1.12.4
- OS and version of remote machine (if applicable): Ubuntu 20.04.5 LTS
- GDB / LLDB version: 

### Bug Summary and Steps to Reproduce

Bug Summary:

"Switch header/source" in split view always opens a new file in current editor group

Steps to reproduce:

1. I have my Code split in to 2 editor groups horizontally.
2. Now that a.h is to the left, a.cc is to the right. 
3. When I run "C/C++ : Switch Header/Source" when focusing a.h, a new a.cc is always opened to the left.
4. Also, when I run "C/C++ : Switch Header/Source" when focusing a.cc, a new a.h is always opened to the right.

Expected behavior:

Always focus existing header or source in the other editor group.

### Debugger Configurations

```shell
None
```

### Debugger Logs

```shell
None
```

### Additional Information

As mentioned in [#444](https://github.com/microsoft/vscode-cpptools/issues/444), it seemed to have been long since this bug fixed. However, here on my computing, this seems not like that.

**Comment by sean-mcmanus** [comment]
Setting `editor.revealIfOpen` to true should enable the behavior you expect. Is that working for you?

**Comment by windless0530** [comment]
> Setting `editor.revealIfOpen` to true should enable the behavior you expect. Is that working for you?

Thanks. But unfortunately, it doesn't.

And what's more, this option seemed to be unknown for Code.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/4645959/201023128-971c4b13-7c25-4cbd-bea5-81f69043ac5b.png">

**Comment by sean-mcmanus** [comment]
@windless0530 Thanks for reporting this -- it looks like VS Code recently renamed the setting workbench.editor.revealIfOpen -- but we need to change our code to look at the new setting.

**Comment by sean-mcmanus** [comment]
@windless0530 Oops, sorry, ignore my previous comment -- using `"workbench.editor.reavelIfOpen": true` should work.

**Comment by windless0530** [comment]
> @windless0530 Oops, sorry, ignore my previous comment -- using `"workbench.editor.reavelIfOpen": true` should work -- right?

Thanks a lot! This time it works!
