### ISSUE TITLE
Syntax Highlight Export

### ISSUE THREAD

**Issue by ClaasMeints** [microsoft/vscode-cpptools#10139]
### Feature Request

As the extension has all the information on the best highlighting of code it would be very helpful for documataion it there was a possability to export these information (e.g. as html etc.) for a file or a code block. This would improve the possability to use highlighted code in webpages or for latex.

**Comment by browntarik** [comment]
Could you provide an example of what you would like to see? This will help us get a clearer picture of what you would like.

**Comment by sean-mcmanus** [comment]
Are you referring to Semantic or Lexical colors?

Semantic info is at https://code.visualstudio.com/docs/cpp/colorization-cpp .

Lexical info is from VS Code itself, from https://github.com/jeff-hykin/better-cpp-syntax .

The C/C++ extension ships a theme pack separately, see https://github.com/microsoft/vscode-cpptools/tree/main/Themes .

**Comment by ClaasMeints** [comment]
I dont really know how the vscode coloring work internally, but i was expecting that the extension gives the information on how to color each word or char etc. to the vscode api. My question is if there was a way to access these information as a user, so in my case a latex extension could parse the data and color the code in the same way vscode does. The Format of the data is relatively irrelavant as long as it is documented anywhere.

Thanks in advance

**Comment by sean-mcmanus** [comment]
You would need to file a feature request on VS Code itself at https://github.com/microsoft/vscode/issues . Our C/C++ extension only sends VS Code semantic token information. VS Code itself has all the lexical info, along with our semantic token info, and info on the themes in use, so it has all the info on what colors are going to be used, and not our extension.
