### ISSUE TITLE
a code definition window like visual studio

### ISSUE THREAD

**Issue by Shaka0723** [microsoft/vscode-cpptools#10130]
### Feature Request

Hi
Can your team add a code definition window like visual studio already has.
![image](https://user-images.githubusercontent.com/56809930/201008280-74c877e0-dce3-4e51-97b4-a1227b7cbd12.png)

I know there is already a peek window in vscode, but it is not enough, for :
1) it needs ctrl+click to call peek window
2) peek window can not be seen when user scroll screen up or down

what I am expecting is :
1) the definition window shows the symbol definition automatically when I put the cursor to the symbol (like visual studio) 
2) the definition window is a independent window but not build-in control in the editor (like visual studio) 
3) when I scroll down and up in the definition window, I can see the other part of codes in the file where the symbol defined.(like visual studio) 
4) when I double-click anywhere in the definition window, a new editor opened to the 2nd editor group, to show the file where I clicked
5) when I click other symbol in the definition window, then window jumps to the new clicked symbol's defined location

**Comment by browntarik** [comment]
Thank you for suggesting this feature. This may be something that more languages could benefit from as well. This suggestion would be better poised toward the VS Code Team rather than the extension. Suggesting it to the VS Code Team will be a better fit since they are more suited to implement it.

**Comment by bobbrow** [comment]
@isidorn, Is this feature something the VS Code team would consider doing?  We don't have permission to transfer issues to your repo, but we can copy it over if you'd like.

**Comment by Shaka0723** [comment]
> @isidorn, Is this feature something the VS Code team would consider doing? We don't have permission to transfer issues to your repo, but we can copy it over if you'd like.
I raised the issue to VSCode team yesterday.
Thanks all the same.

**Comment by isidorn** [comment]
@bobbrow thanks for the ping. I do not think this is something we would want to have in VS Code out of the box.
Though I think it would be best to follow the development in this issue https://github.com/microsoft/vscode/issues/166340

**Comment by sean-mcmanus** [comment]
Sure, we'll close this issue then.
