### ISSUE TITLE
Side-loading of C/C++ extension

### ISSUE THREAD

**Issue by jtlimback** [microsoft/vscode-cpptools#1013]
I've been able to install/use this extension with great success on a machine with access to the VSCode marketplace.  I now find that I need to install on a machine on an isolated network.  I've downloaded the VSIXPackage file and installed from that.  However, on reload the extension wants to download/install dependencies.  Is there any way for you to let me know what the dependencies are so I can download the VSIXPackage files?  I would need publisher, extension name and version to resolve the URL for the package files.

VSCode v 1.14.0 (Linux)
C/C++ extension 0.12.2

**Comment by sean-mcmanus** [comment]
Instead of copying/installing the .vsix, can you copy/paste the installed folder after the dependencies have downloaded/installed (assuming the OS is the same), e.g. at `/home/username/.vscode/extensions/ms-vscode.cpptools-version`? That is the recommended way. You could also try using the runtimeDependencies links in our package.json to manually download the dependencies, but that bypasses our install steps, which may cause issues.

**Comment by jtlimback** [comment]
I originally copy/pasted the ms-vscode-.cpptools-0.12.2 directory from my local .vscode directory to the corresponding directory under the user on the machine that is on the isolated network.  The extension seems to work fine but when I tried to run the debugger I would get a failure.  I thought installing by copy/paste may be the problem.  I noticed the hardcoded paths in the package.json file and changed them accordingly but the debugger still would not work.  Sounds like I may have another issue.  I'm going to try to get some more information about the debugger issue when I get back into the lab.

**Comment by jtlimback** [comment]
As stated previously, after I copied my .vscode/extensions/ms-vscode.cpptools-0.12.2 directory to the isolated machine, I was getting "Debug adapter process has terminated unexpectedly".  This led me to believe that I needed to install the extension differently because I wasn't sure that copying the directory was a valid way to install.  After your comment that copying was the preferred way to install an extension on a machine without marketplace access, I went back to trying to figure out the debugger termination issue.  Turns out .vscode/extensions/ms-vscode.cpptools-0.12.2/debugAdapters/mono.linux-x86_64 did not have executable permission, causing the unexpected debug adapter termination.  How the permissions on that file changed during the copy is a mystery.  Anyway, I've been able to launch/debug via gdb on a remote target.  So I'm going to close this issue.  Thank you for the confirmation that copying the extension directory is the correct procedure for installing on a machine without marketplace access

**Comment by sean-mcmanus** [comment]
Ah, yeah, sorry -- I forgot to mention that you should do a copy or zip that copies the executable permissions too (our install step does that normally). I found some info at https://askubuntu.com/questions/225865/copy-files-without-losing-file-folder-permissions in case other users hit the same issue. We've considered eventually adding a "export/import" command for offline installation.
