### ISSUE TITLE
clang-format cannot recognize ${workspacefolder}\.vscode\.clang-format

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#10141]
### Environment

名称: C/C++
ID: ms-vscode.cpptools
说明: C/C++ IntelliSense, debugging, and code browsing.
版本: 1.13.3
发布者: Microsoft
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

### Bug Summary and Steps to Reproduce

Bug Summary:

格式化失败: c:\Users\heart\.vscode\extensions\ms-vscode.cpptools-1.13.3-win32-x64/bin/../LLVM/bin/clang-format.exe -style=${workspacefolder}\.vscode\.clang-format -fallback-style=LLVM 
```json
{

    "C_Cpp.clang_format_style": "${workspaceFolder}\\.vscode\\.clang-format",
}
```

**Comment by browntarik** [comment]
Have you tried replacing ${workspaceFolder} with its full path? For example, the complete path to my .clang-format file is C:\Example\VS\src\vc\.vscode\.clang-format. I would then insert
`{

    "C_Cpp.clang_format_style": "C:\Example\VS\src\vc\.vscode\.clang-format",
}
`
Can you let me know if this works for you?

**Comment by heartacker** [comment]
both fail
```
格式化失败:
c:\Users\heart\.vscode\extensions\ms-vscode.cpptools-1.13.3-win32-x64/bin/../LLVM/bin/clang-format.exe -style=${workspacefolder}\.vscode\.clang-format -fallback-style=LLVM -assume-filename=D:\heart\Git\HQA\HQA\src\ac7840x_hqa_acmp.c
```
```
格式化失败:
c:\Users\heart\.vscode\extensions\ms-vscode.cpptools-1.13.3-win32-x64/bin/../LLVM/bin/clang-format.exe -style=d:\heart\git\hqa\.vscode\.clang-format -fallback-style=LLVM -assume-filename=D:\heart\Git\HQA\HQA\src\ac7840x_hqa_acmp.c
```

**Comment by sean-mcmanus** [comment]
You need to set the style like `-style=file:<path>`. See the docs at https://releases.llvm.org/15.0.0/tools/clang/docs/ClangFormat.html.

If you use 1.13.3, then the `${workspaceFolder}` is also supported, see https://github.com/microsoft/vscode-cpptools/issues/9786 .

Does that solve your issue?

**Comment by heartacker** [comment]
add `file:` frist, and it works
