### ISSUE TITLE
gdb error

### ISSUE THREAD

**Issue by 0Kaizoku** [microsoft/vscode-cpptools#10151]
### Environment

- OS and version: windows 11
- VS Code:
- C/C++ extension: microsoft C/C++ for Visual Studio Code
- OS and version of remote machine (if applicable):
- GDB / LLDB version: GNU gdb (GDB) 7.6.1

### Bug Summary and Steps to Reproduce

idk

### Debugger Configurations

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\MinGW\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "windows-gcc-x86"
        }
    ],
    "version": 4
}
```

### Debugger Logs

```shell
Loaded 'C:\WINDOWS\SysWOW64\kernel32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\KernelBase.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\msvcrt.dll'. Symbols loaded.
The program 'c:\Users\amine\OneDrive\Desktop\my_project\c files\random\calculator.exe' has exited with code 0 (0x00000000).
```

### Other Extensions

none

### Additional Information

![image](https://user-images.githubusercontent.com/114872954/202314999-b484571b-fdd5-4a63-a4ea-0d8a4fede3a4.png)

Can you help me with this error

**Comment by WardenGnaw** [comment]
What is the error message that you are getting?

**Comment by 0Kaizoku** [comment]
Loaded 'C:\WINDOWS\SysWOW64\kernel32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\KernelBase.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\msvcrt.dll'. Symbols loaded.
this one how can i get rid of

**Comment by 0Kaizoku** [comment]
> What is the error message that you are getting?

i installed the mingw compiler correctly and when i run my program this appears

**Comment by WardenGnaw** [comment]
That is not an error message, that is a symbol load message.

If you want to disable symbol loading messages use:
```
"logging": {
   "moduleLoad": false
}
```

For more options please see https://code.visualstudio.com/docs/cpp/launch-json-reference#_logging

**Comment by 0Kaizoku** [comment]
> That is not an error message, that is a symbol load message.
> 
> If you want to disable symbol loading messages use:
> 
> ```
> "logging": {
>    "moduleLoad": false
> }
> ```
> 
> For more options please see https://code.visualstudio.com/docs/cpp/launch-json-reference#_logging

I solved the problem I was installing a mingw32 compiler for my 64 bit OS that's why
thank you
