### ISSUE TITLE
Picking a process ID for attaching with the GDB debugger is not possible anymore

### ISSUE THREAD

**Issue by ByteBender747** [microsoft/vscode-cpptools#1016]
VSCode Version: 1.15.1
OS Version: Windows 7 Enterprise 6.1 (Build 7601: Service Pack 1)
C/C++ Extension Version: 0.12.3

I use the following launch.json configuration:

{
"version": "0.2.0",
"configurations": [
{
"name": "(gdb) Attach",
"type": "cppdbg",
"request": "attach",
"program": "C:/02_tools/00_executables/BT_RTSIM.exe",
"args": [],
"stopAtEntry": false,
"processId": "${command.pickProcess}",
"cwd": "${workspaceRoot}",
"environment": [],
"externalConsole": true,
"MIMode": "gdb",
"miDebuggerPath": "c:/MinGW/bin/gdb.exe",
"setupCommands": [
{
"description": "Enable pretty-printing for gdb",
"text": "-enable-pretty-printing",
"ignoreFailures": true
}
]
}
]
}

With version 1.12.2 it works as expected and I can select the process for connecting with the Debugger.:
![2c9e2bf](https://user-images.githubusercontent.com/26296473/30165066-fa82c9a8-93de-11e7-945f-6b73a982df65.PNG)

Since version VSCode version 1.15.0 I get the following error message:
![process_picker](https://user-images.githubusercontent.com/26296473/30165083-0f1f9256-93df-11e7-8920-5ee8603cbc89.png)

**Comment by pieandcakes** [comment]
@Lichtbogen Can you try updating yourself to VS Code 1.16? I wasn't able to find 1.15.0 or 1.15.1 to install and test it with but I just downloaded 1.16.0 and the 0.12.3 version of the extension and I don't see an issue with using the process picker.

**Comment by pieandcakes** [comment]
@Lichtbogen I notice that you have green squiggles under `request: "attach"` and `"processId"`. Can you reinstall the extension? Looks like VSCode isn't recognizing our extension properly.

**Comment by pieandcakes** [comment]
I also have a colleague with 1.15.1 and we tested this with MinGW and are not seeing any errors.

**Comment by ByteBender747** [comment]
I have updated to VSCode version 1.16.0 and I have also reinstalled the C/C++ plugin. But the error is still there. Should I try to reinstall the whole VSCode?

**Comment by ByteBender747** [comment]
My colleague has the same problem. He had installed VS version 1.12 and it worked. After updating to version 1.15.1 using the auto updater he has the same issue.

**Comment by pieandcakes** [comment]
@Lichtbogen I've uninstalled, reinstalled to VSCode 1.16 and installed 0.12.3 of the extension and I can't duplicate this. Can you confirm that when you reinstall the green squiggles under type is gone? Also, when you install the extension and first restart VSCode can you confirm that there is output in the Output window for downloading components?

**Comment by pieandcakes** [comment]
If this is still happening, please provide more information. I can't duplicate this.
