### ISSUE TITLE
Over-indentation on multi-line statements

### ISSUE THREAD

**Issue by WinfredHuang** [microsoft/vscode-cpptools#10167]
### Environment

- OS and Version: OpenAnolis 8.6 (compatible with CentOS 8)
- VS Code Version: 1.71
- C/C++ Extension Version: 1.12.4

### Bug Summary and Steps to Reproduce

Bug Summary:
If line breaks occurs at the left parentheses, excessive spaces are used when formatting the document even I have set that indentation should start from the beginning of the statement rather than the parentheses.

Steps to reproduce:
Just write a multi-line statement like below:
`obj.f1(f2(a,b),`
`c,d,e)`
The `c` will be aligned with the parenthesis at `f1(`, with dozens of spaces before.

### Expected behavior

The `c` should be aligned with `obj` and have one tab indent only. 

### Code sample and Logs

```shell
// The following is from settings.json
{
    "workbench.colorTheme": "Default Light+",
    "C_Cpp.default.cppStandard": "c++11",
    "C_Cpp.default.cStandard": "c11",
    "C_Cpp.vcFormat.indent.caseLabels": true,
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.block": "newLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.function": "newLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.namespace": "newLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.type": "newLine",
    "C_Cpp.vcFormat.space.pointerReferenceAlignment": "right",
    "C_Cpp.vcFormat.wrap.preserveBlocks": "never",
    "editor.fontSize": 12,
    "C_Cpp.vcFormat.newLine.scopeBracesOnSeparateLines": true,
    "C_Cpp.vcFormat.indent.preserveComments": true,
    "C_Cpp.vcFormat.indent.multiLineRelativeTo": "statementBegin"
}
```

**Comment by sean-mcmanus** [comment]
The behavior I'm seeing seems "by design", correct:
```cpp
    obj.f1(f2(a, b),
        c, d, e);
```
What output were you expecting? The "o" is the beginning of the statement and the indentation is relative to that.

**Comment by AurusHuang** [comment]
Sorry, I mean the "c" is aligned to "(".

发自我的iPhone

在 2022年11月19日，06:30，Sean McManus ***@***.***> 写道：

﻿

The behavior I'm seeing seems "by design", correct:

    obj.f1(f2(a, b),
        c, d, e);

What output were you expecting? The "o" is the beginning of the statement and the indentation is relative to that.

**Comment by AurusHuang** [comment]
Sorry, I mean the "c" is aligned to "(". 
```
object.function1(function2(a,b)),   
                 c,d,e));
```

**Comment by sean-mcmanus** [comment]
Your code doesn't appear valid. There not matching ( and ). Are you able to get a repro that compiles?

**Comment by AurusHuang** [comment]
Typo corrected.

**Comment by sean-mcmanus** [comment]
I don't repro the issue -- I'm guessing it's becausing you're formatting with clangFormat instead. For vcFormat settings to be applied, you need to use setting `    "C_Cpp.formatting": "vcFormat",`.

**Comment by AurusHuang** [comment]
It works, but I saw the setting was set to "Default" instead of "clangFormat"...how could this happen?

**Comment by sean-mcmanus** [comment]
The "Default" setting is the same as "clangFormat", since clangFormat is the default.

**Comment by sean-mcmanus** [comment]
@AurusHuang See the setting info:
![image](https://user-images.githubusercontent.com/19859882/203189100-0bb1b93e-c0df-49d9-a532-849e38334ba0.png)
