### ISSUE TITLE
No error squiggles when non-member function cannot have a cv-qualifier

### ISSUE THREAD

**Issue by rohanbari** [microsoft/vscode-cpptools#10179]
### Environment

- OS and Version: Windows 10 Pro 22H2
- VS Code Version: 1.73.1 `(user setup)`
- C/C++ Extension Version: v1.13.4
- Other extensions you installed (and if the issue persists after disabling them):

```
- cschlosser.doxdocgen
- eamodio.gitlens
- esbenp.prettier-vscode
- GitHub.github-vscode-theme
- isudox.vscode-jetbrains-keybindings
- ms-vscode.cpptools
- PKief.material-icon-theme
- redhat.java
- ritwickdey.LiveServer
- VisualStudioExptTeam.vscodeintellicode
- vscjava.vscode-java-debug
- vscjava.vscode-java-dependency
- vscjava.vscode-java-pack
- vscjava.vscode-java-test
- vscjava.vscode-maven
- yzhang.markdown-all-in-one
```

- If using SSH remotely, specify the OS of the remote machine: `<none>` 

<hr />

Today, I found a peculiar condition in which the C/C++ extension did not report a single error. The workspace is a single repository in which there are multiple C++ files — this is not a project, though.

**Consider the following class definition:**

```cpp
template <typename T>
class Demo {
    const T& member;

public:
    Demo() = default;
    constexpr Demo(const T& rhs)
        : member(rhs)
    {
    }
    constexpr Demo(const Demo& rhs)
        : member(rhs.member)
    {
    }

    // The problem is in the 'const' cv-qualifier at the end below.
    friend ostream& operator<<(ostream& out, const Demo& rhs) const
    {
        out << rhs.member;
        return out;
    }
};
```

As `friend ostream& operator<<` is an operator overload and not a member method, a cv-qualifier is not allowed. When compiled, the error is generated. However, the C/C++ extension does not report it.

### Bug Summary and Steps to Reproduce

**Bug Summary:**
The compiler correctly generates the following error as expected.

    non-member function 'std::ostream& operator<<(std::ostream&, const Demo<T>&)' cannot have cv-qualifier

However, the C/C++ extension (with `cppStandard="c++20"`) does not display error squiggles about this.

**Steps to reproduce:**
1. Copy-paste the attached code into a CPP file in VS Code.
2. Wait for a few seconds until the code scanning finishes.
3. No errors were reported.
4. Now, compile and see the error.

### Expected behavior

The C/C++ extension error squiggles are supposed to display the information about the error.

### Code sample and Logs

```shell
Code sample: Provided above.

c_cpp_properties.json:

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": ["${workspaceFolder}/**"],
            "defines": ["_DEBUG", "UNICODE", "_UNICODE"],
            "compilerPath": "C:\\TDM-GCC-64\\bin\\gcc.exe",
            "cStandard": "c99",
            "cppStandard": "c++20",
            "intelliSenseMode": "windows-gcc-x64"
        }
    ],
    "version": 4
}
```

C/C++: Log Diagnostics:
```
-------- Diagnostics - 11/22/2022, 1:19:31 PM
Version: 1.13.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\TDM-GCC-64\\bin\\gcc.exe",
    "cStandard": "c99",
    "cppStandard": "c++20",
    "intelliSenseMode": "windows-gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Rohan\Desktop\code\CPlusPlus\src\code.cpp ]:
    C:\Users\Rohan\Desktop\code\CPlusPlus\src\code.cpp
Translation Unit Configurations:
[ C:\Users\Rohan\Desktop\code\CPlusPlus\src\code.cpp ]:
    Process ID: 5640
    Memory Usage: 82 MB
    Compiler Path: C:\TDM-GCC-64\bin\gcc.exe
    Includes:
        C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\10.3.0\include\c++
        C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\10.3.0\include\c++\x86_64-w64-mingw32
        C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\10.3.0\include\c++\backward
        C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\10.3.0\include
        C:\TDM-GCC-64\include
        C:\TDM-GCC-64\lib\gcc\x86_64-w64-mingw32\10.3.0\include-fixed
        C:\TDM-GCC-64\x86_64-w64-mingw32\include
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++20
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=100300
Total Memory Usage: 82 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2485
```
```


### Screenshots

_No response_

### Additional context

_No response_

**Comment by sean-mcmanus** [comment]
We haven't implemented error squiggles for templates. That is tracked by https://github.com/microsoft/vscode-cpptools/issues/1946 . If you remove the template stuff then you get the errors.

**Comment by rohanbari** [comment]
Awesome to know that this issue has already been opened. You are correct about removing the `template` — the extension works appropriately when removed.

![Error](https://user-images.githubusercontent.com/54104015/203464247-7461b022-4384-4cfd-954f-80c51a2feb1c.png)
