### ISSUE TITLE
[cppvsdbg] Option to disable thread exit logging in launch.json

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-cpptools#1017]
_From @akbyrd on September 7, 2017 21:20_

Desired Behavior:

I'd like the ability to disable thread exit messages in the Debug Console. Options already exist for other types of messages such as module loads (under logging.moduleLoad), so this would simply be another one added to the list.

![vscode thread exit messages](https://user-images.githubusercontent.com/484784/30185717-47708c06-93e8-11e7-9b27-205b1aa4484e.png)

- VSCode Version: Code - Insiders 1.17.0-insider (ac167c41bababe6c47180012723fa2bc52610ff4, 2017-09-07T05:24:04.020Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
Lua|key|0.0.9
cpptools|ms-|0.12.3
code-settings-sync|Sha|2.8.3

---

Steps to Reproduce:

1. Launch a C++ program under the debugger
2. Notice "The thread #### has exited with code 0 (0x0)" messages in the Debug Console

_Copied from original issue: Microsoft/vscode#33965_

**Comment by dfdumaresq** [comment]
This would be a huge help for those, like me, who often work on a single laptop screen!

**Comment by GoaLitiuM** [comment]
This would help everyone, especially if the program you are debugging has tens of threads starting and stopping at times. The option already exists in Visual Studio, so why not in VSCode as well?

**Comment by cooper352** [comment]
@GoaLitiuM Where is this option in Visual Studio? I've been trying to disable thread exit messages in the console window, but can only find an option to disable them in the  output window.

**Comment by akbyrd** [comment]
Right clicking in the Output Window is the way I normally get to it:

![thread exit](https://user-images.githubusercontent.com/484784/44881333-1b540b80-ac64-11e8-8311-2ed2c2ef0c9e.png)

**Comment by dfdumaresq** [comment]
Has there been any progress on this for VS Code users?

**Comment by dfdumaresq** [comment]
Can you give us an update please?

**Comment by sean-mcmanus** [comment]
@WardenGnaw ? I don't think any work has been done on this.

**Comment by dcarapic** [comment]
I would also really like this. Currently I have a mix of standard console output and bunch of Loaded/thread exited messages which do not provide any value.

**Comment by dfdumaresq** [comment]
While we've been waiting for this, searching the VSCode console has improved greatly. 
Try clicking in the console and typing (On Mac) CMD-F, then type your search term. Use the arrow keys to jump to next and previous.

**Comment by ChronosWS** [comment]
+1, thread exit messages are almost completely useless, especially in ASP.NET Core apps where there are always threads starting and stopping.

**Comment by akbyrd** [comment]
Issue created 2 years ago. Eesh.

**Comment by GoaLitiuM** [comment]
We get a pretty useless "enableDebugHeap" option but not this? Come on...

**Comment by ssg** [comment]
We would benefit from this too.

**Comment by awarwick** [comment]
This makes it extremely difficult to verify the result of unit tests (note the scrollbar on the right):

![Image](https://i.imgur.com/Wk6qJzG.png)

Thread exit messages are not helpful in most cases. Can we please get an option to disable them?

**Comment by GoaLitiuM** [comment]
I don't understand why this has not been implemented yet. The debugging engine is the same used by Visual Studio, so this should be a trivial fix of just exposing the option to VSCode extension.

**Comment by GoaLitiuM** [comment]
Latest extension (0.28.0) does not seem to print any thread exit message anymore 👍, yet there was no new logging options added or any mentions about this in changelogs.

**Comment by GoaLitiuM** [comment]
Update 0.28.1 brought back the thread exit messages... Can we please have the option to disable these?

**Comment by WardenGnaw** [comment]
Most of the comments and images indicate the issue is the threadExit messages are from debugger type `cppvsdbg`. 

Add the following to your launch.json to remove those messages:
```
"logging": {
   "threadExit": true
}
```

If you are looking to disable threadEvents from GDB, see https://github.com/microsoft/vscode-cpptools/issues/5660

**Comment by dfdumaresq** [comment]
I'm seeing this in Microsoft .NET Core Debugger (vsdbg). Have I logged the issue in the wrong repo?

The fix above does not work for me.

[Information] 20:08:11 Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 35.6332ms 200 image/jpeg
The thread 203181 has exited with code 0 (0x0).
The thread 202213 has exited with code 0 (0x0).
The thread 203288 has exited with code 0 (0x0).
The thread 203922 has exited with code 0 (0x0).
The thread 203171 has exited with code 0 (0x0).
The thread 203169 has exited with code 0 (0x0).
The thread 203306 has exited with code 0 (0x0).
The thread 203578 has exited with code 0 (0x0).
The thread 203579 has exited with code 0 (0x0).
The thread 202296 has exited with code 0 (0x0).

**Comment by sean-mcmanus** [comment]
@dfdumaresq The fix hasn't been shipped yet. It's planned for 0.29.0-insiders for the C/C++ extension (not sure how that relates to the .NET Core debugger). @WardenGnaw probably know.

**Comment by WardenGnaw** [comment]
@dfdumaresq You will want to see the options in logging for the VS Code Omnisharp C# extension. Heres is the schema: https://github.com/OmniSharp/omnisharp-vscode/blob/aa85edeace0abd981c0c468c4c323dcd6faf60aa/package.json#L450

**Comment by dfdumaresq** [comment]
Thanks @sean-mcmanus and @WardenGnaw for the above link to logging options. 

Just a comment as an enduser: it would be more helpful if all the descriptions for logging options included a sentence saying what the default is, like the threadExit and processExit do. 
Right now, it's not consistent and I have a bunch that were set to defaults, unbeknownst to me.
