### ISSUE TITLE
Support `cpptools`' IntelliSense services with the `GitHub Pull Request Extension and Issues`: Clang-Tidy, type information, Go-To etc.

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#10185]
### Feature Request

I think it would be beneficial if the following cpptools features are also available in the PR side-by-side code review panel provided by the GitHub pull request extension:

1. InlayHints & type info
2. Clang-Tidy warnings
3. GoTo defintion/declaration/source file, etc.
4. Function signature and doxygen comments

**Comment by sean-mcmanus** [comment]
This appears to be an issue with the GitHub extension (https://github.com/microsoft/vscode-pull-request-github/issues) or possibly VS Code itself, i.e. it repros with TypeScript files as well.
