### ISSUE TITLE
Large number of spaces inserted on file save

### ISSUE THREAD

**Issue by mikehaines1** [microsoft/vscode-cpptools#10181]
Type: <b>Bug</b>

Check out x.cpp source file
Make simple change to x.cpp source file 
Save x.cpp source file
See several lines of constructor variable intializers get deleted and replaced by funky coloring.
Can undo the problem with CTRL+Z to restore deleted lines
Extension Bisect determined problem to be with ms-vscode.cpptools
With this extension disabled problem is not happening.

Extension version: 1.12.4
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.15.0-53-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: disabled_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|25.41GB (22.87GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 5cbe0297-4a53-4fad-a7ef-d3bc8090d3e7|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by browntarik** [comment]
Thanks for submitting your issue! We will begin investigating this as soon as possible and get back to you soon.

**Comment by mikehaines1** [comment]
Update: The lines are not actually deleted.  The save operation inserts MANY spaces (150) before the constructor initialize statements which pushes them out of view in the editor.

For example this constructor:
MyThread::MyThread(uint16_t port) : BaseThread(port),
    m_mon(),

Becomes this after the save
MyThread::MyThread(uint16_t port) : BaseThread(port),
                                                                                                                                                      m_mon(),

**Comment by browntarik** [comment]
This seems to be a formatting issue. Do you currently have format on save enabled. Does the issue persist when it is disabled?

**Comment by mikehaines1** [comment]
This is a formatting issue caused by Format on Save as you mentioned. Closing issue. Thank you very much for your fast responses & solution.
