### ISSUE TITLE
External terminal setting not applied to C/C++ extension

### ISSUE THREAD

**Issue by hungys** [microsoft/vscode-cpptools#102]
I am trying this C/C++ extension on OS X. Every time I launch the C++ program from VSCode, it will open an OS X's built-in Terminal, even if I have set `terminal.external.osxExec` to be `iTerm.app`.

Is there any way to open iTerm instead of OS X's built-in Terminal app? and is there any plan to support using VSCode's integrated terminal without opening additional window?

**Comment by edumunoz** [comment]
> Is there any way to open iTerm instead of OS X's built-in Terminal app?

Currently, no.

For the other two questions, you can check here some pointers for the code that does this in case you have suggestions or would like to submit a PR: https://github.com/Microsoft/vscppsamples/issues/98#issuecomment-232811482.

**Comment by clankill3r** [comment]
I haven't try this and it it probably a horrible idea but maybe you can rename `iTerm.app` to `Terminal.app` 😃
