### ISSUE TITLE
VSCode disassembly view on MAC M1 doesn't work properly

### ISSUE THREAD

**Issue by michuhu** [microsoft/vscode-cpptools#10215]
### Environment

- OS and version: Mac OS Ventura 13.0.1
- VS Code: 1.73.1 (Universal)
- C/C++ extension: v1.12.4
- LLDB version: lldb-1400.0.38.13

### Bug Summary and Steps to Reproduce

In **Visual Studio Code** on **Mac M1**, coding in **C++**, if I do a breakpoint and right click -> `Open disassembly view`, the highlighting of the code line doesn't work nor it doesn't follow the code when I click in `Step Into`. 

According to [this official Microsoft post](https://devblogs.microsoft.com/cppblog/visual-studio-code-c-july-2021-update-disassembly-view-macro-expansion-and-windows-arm64-debugging/) it should work. I know it says windows arm64, but does that mean Mac M1's are not compatible?

### Debugger Configurations

tasks.json

```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: clang++ compile",
            "command": "/usr/bin/clang++",
            "args": [
                "-fcolor-diagnostics",
                "-fansi-escape-codes",
                "-g",
                "\"${workspaceFolder}\"/*.cpp",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "debuger"
        }
    ],
    "version": "2.0.0"
}
```

launch.json

```json
{
    "configurations": [
        {
            "name": "C/C++: clang++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang++ compile"
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

I could post debugger logs, but it's not applicable I guess?

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.

**Comment by michuhu** [comment]
@WardenGnaw Hello, any news on this?

**Comment by luckforyou** [comment]
macos,vscode

if I do a breakpoint and right click -> `Open disassembly view`, I get the view as the following:

<img width="920" alt="image" src="https://user-images.githubusercontent.com/5405555/229676422-d3dd42ce-244d-40dc-bbd0-8cbcfa36f5cc.png">

1. it does not show the byte code of the asm
2. it does note show the asm language, it just show `??`
