### ISSUE TITLE
Optionally include control structures in generated outline information

### ISSUE THREAD

**Issue by BenBE** [microsoft/vscode-cpptools#10230]
### Feature Request

This is a follow-up for https://github.com/microsoft/vscode/issues/163872

With the recent addition of the Sticky Scroll feature there is a possibility to display a sticky navigation line for each block of the code you are currently navigating through. It would be nice if the provided outline information from the CPP extension could be configured to include block-level information in addition to the raw namespace, class and function level information that are currently included.

The aim would be, that for each opening block, a line in the sticky scroll could be displayed.

As this might not be suitable for everybody, a setting to do so (may be off by default) would fully suffice.

**Comment by thefasquelle** [comment]
My workaround is to use the foldingProviderModel. Only downside is that multi-line comments also become sticky and might steal the last slot
