### ISSUE TITLE
Freshness Pass on C++ Extension Docs 

### ISSUE THREAD

**Issue by AlexandraKemperMS** [microsoft/vscode-cpptools#10235]
# See updates here: https://github.com/microsoft/vscode-cpptools/issues/11194

### Feature Request

It is time for the yearly freshness pass of our docs. If everyone on the team could walk through one or two of the docs and see if there is anything out of date (screenshots, instructions, etc. ) this should be really quick. 

If there are any issues you find, feel free to add them to the excel sheet I shared or create a PR with a quick fix. 

List of docs to review: 

- [x] 1. [GCC on Linux](https://code.visualstudio.com/docs/cpp/config-linux)
- [x] 2. [GCC on Windows](https://code.visualstudio.com/docs/cpp/config-mingw) [Tarik]
- [x] 3. [GCC on Windows Subsystem for Linux](https://code.visualstudio.com/docs/cpp/config-wsl)
- [x] 4. [Clang on macOS](https://code.visualstudio.com/docs/cpp/config-clang-mac)
- [x] 5. [Microsoft C++ on Windows](https://code.visualstudio.com/docs/cpp/config-msvc) [Tarik]
  - https://github.com/microsoft/vscode-docs/pull/6116
- [x] 7. [CMake Tools on Linux](https://code.visualstudio.com/docs/cpp/cmake-linux) [Tarik]
- [x] 8. [Editing](https://code.visualstudio.com/docs/cpp/cpp-ide) 
- [ ] 9. [Debugging](https://code.visualstudio.com/docs/cpp/cpp-debug) [Tarik] [Andrew]
  - [ ] Add Data Breakpoints Documentation
  - [ ] Add Log Messages (Tracepoints) Documentation
  - [ ] Add Exception Breakpoints Documentation
  - [ ] Add Debug Via Remote Documentation
- [x] 10. [Configure debugging](https://code.visualstudio.com/docs/cpp/launch-json-reference)
  - https://github.com/microsoft/vscode-cpptools/issues/9359
- [x] 11. [Settings](https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp) [Tarik]
  - https://github.com/microsoft/vscode-docs/pull/6117
- [X] 12. [Configure IntelliSense for cross-compiling](https://code.visualstudio.com/docs/cpp/configure-intellisense-crosscompilation)
  - https://github.com/microsoft/vscode-docs/pull/5924
- [X] 13.[FAQ](https://code.visualstudio.com/docs/cpp/faq-cpp)
  - https://github.com/microsoft/vscode-docs/pull/5903
- [x] 14. [Intro Videos](https://code.visualstudio.com/docs/cpp/introvideos-cpp) [Tarik]
- [x] 15. [c_cpp_properties.json schema reference](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference)
  - https://github.com/microsoft/vscode-cpptools/issues/9767
- [x] 16. [Enhanced colorization](https://code.visualstudio.com/docs/cpp/colorization-cpp) [Tarik]
- [x] 17. [C/C++ logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) [Tarik]
- [ ] 18. Add cpp.hint usage to FAQ or configuration (for content and example, see https://learn.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170)

Please make a note if you are in the process of walking through one of the tutorials/check it off if you have completed it.

**Comment by sean-mcmanus** [comment]
@AlexandraKemperMS https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/README.md is huge and external to cpptools -- should an issue be filed on the CMake Tools repo to review that?

**Comment by AlexandraKemperMS** [comment]
> @AlexandraKemperMS https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/README.md is huge and external to cpptools -- should an issue be filed on the CMake Tools repo to review that?

Good point, you are right this is outside of our scope, removed. This is up to the CMake team.

**Comment by bobbrow** [comment]
This issue is quite stale at this point. We should open a new one if we have remaining documents to audit.

**Comment by AlexandraKemperMS** [comment]
I updated the comment with the current status, all other long running documentation plans/changes can be tracked here: https://github.com/microsoft/vscode-cpptools/issues/11194
