### ISSUE TITLE
The files.associations doesn't work with 1.13.6

### ISSUE THREAD

**Issue by JeanMiK** [microsoft/vscode-cpptools#10244]
### Environment

- OS and Version: RedHat Linux 7.9
- VS Code Version: 1.72.1
- C/C++ Extension Version: 1.13.6

### Bug Summary and Steps to Reproduce

Bug Summary:

If one has C++ code in a file with a '.C' extension, the C++ standard header finds are no longer found, instead, Intellisense indicates an error "cannot open source file "iostream"" and "#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit ".

Quick Fix proposes to add the standard path to includePath, e.g.
    /usr/include/c++/4.8.2
but his does not work, either.

Bug appeared (for me) with version v1.13.6. Downgrading to previous version (v1.12.4) solves the issue for me. From the outside, it is basically the same as the previous, sucessfully solved issue #6497.

compile_commands.json is being used.

Steps to reproduce:

Write a simple HelloWorld program in a file HelloWorld.C using e.g <iostream>

### Expected behavior

C++ standard include files shold be found

### Code sample and Logs

```shell
#include <iostream>

int main()
{
    std::cout << "Hello world!\n";
}
```

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.7
