### ISSUE TITLE
Navigate to the definition of specific derived class when Ctrl+Click a virtual function of base class. 

### ISSUE THREAD

**Issue by Mulf** [microsoft/vscode-cpptools#10240]
### Feature Request

My project includes a base class and several derived classes for different version. 
When I Ctrl+click a virtual function of a base-class object, it always jumps to the declaration in the header file of that base class, is it possible to cofigure the cpp-tools so that it nagvigates to the definition of a specific derived class, or show a list of definitions from possible derived class so that I can choose the source location to jump over?

**Comment by sean-mcmanus** [comment]
We're tracking this with https://github.com/microsoft/vscode-cpptools/issues/3941. You can upvote that.
