### ISSUE TITLE
g++ with -Wall warning stops the launching of the program with no error

### ISSUE THREAD

**Issue by ZZYSonny** [microsoft/vscode-cpptools#1024]
That happens after a VSCode update that problems showed by g++ was put to the place of terminal. I am not quite sure whether this is a issue of vscode or cpptools.
Without -Wall in tasks, the problem part (Intellisense Engine) don't show the warning. Sometimes warning provides things that can prevent unnecessary debug while sometimes I ignore them. If I still want the -Wall, I wouldn't be able to run my program until there is no warnings.

Can that happen because of my tasks.json part.
Here is part of my tasks.json
{
            "taskName":"g++(-Wall)",
            "command": "g++",
            "args": ["-o2","-m64","-Wall","-g","${file}","-o","${file}.exe"],
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation":"absolute",
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }

**Comment by sean-mcmanus** [comment]
I don't understand. Is this a problem with the IntelliSense engine output or the g++ build task output? Our extension adds problems from our IntelliSense engine (change `C_Cpp.errorSquiggles` to Disabled to disable them). We also add a "gcc" problem matcher. Any other bugs would probably be a VS Code issue. Does this issue reproduce when you disable the C++ extension?

**Comment by ZZYSonny** [comment]
This problem is related to the launch of C++.
The problem is that if I want g++ warning (things like unused variable) in intellisense engine or command part, I have to write -Wall in g++ command in tasks.json . Thus I have to press "Debug Anyway" to run the program with no syntax error but some warnings can't run because vscode(or plugin) thought g++ returned error code 1. Is it possible to add a configuration that allows continue to debug such program?

![image](https://user-images.githubusercontent.com/28442838/30249916-593449b8-9678-11e7-8ed2-216aa54f37e5.png)

**Comment by pieandcakes** [comment]
@ZZYSonny This sounds like an issue with g++ returning an exit code of 1 when there is a warning and VS Code's `task.json` code thinking that's an error and asking you to debug anyways. You may want to try and file it at https://github.com/Microsoft/vscode as we don't provide anything different beyond the default VS Code behavior when linking debugging to building.

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.
