### ISSUE TITLE
--using_directoryC/C++(571)

### ISSUE THREAD

**Issue by PasqualeAndreola** [microsoft/vscode-cpptools#10249]
### Environment

- OS and Version: 
**Ubuntu 22.04.1 LTS, 64bit** 

- VS Code Version: 
**1.74.0**

- C/C++ Extension Version: 
**1.13.6**

- Other extensions you installed (and if the issue persists after disabling them):  
**Installed: C/C++ Extension Pack; CMake; CMake Tools; Italian Language Pack; Jupyter Keymap; Makefile Tools; Remote-SSH; Remote-SSH Editing Code.
The issue persists even if I disable all the other extensions **

- If using SSH remote, specify OS of remote machine:  
**Not using any SSH remote**

- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
**There is an error on the first line of each file which constitutes the workspace (a single folder with some source files and some header files, nothing too complicated). This error in Italian says "Errore nella riga di comando: opzione non valida: --using_directoryC/C++(571)". It should be something like: "Error in command line: options not valid: --using_directoryC/C++(571)". This error appears whenever I update to C/C++ 1.13.6 but it disappears as soon as I switch back to the old version  of the extension (1.12.4). I didn't find any info about this issue**

### Bug Summary and Steps to Reproduce

Bug Summary:
**  "Error in command line: options not valid: --using_directoryC/C++(571)" **

Steps to reproduce:
1. Go to any *.cpp or *.h file
2. Click on the first line
3. Wait some seconds

### Code sample and Logs

```shell
-------- Diagnostics - 8/12/2022, 14:12:17
Version: 1.13.6
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.makefile-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": []
}
Translation Unit Mappings:
[ /home/pasqualeandreola/DarkALP/SourceFiles/main.cpp ]:
    /home/pasqualeandreola/DarkALP/SourceFiles/main.cpp
[ /home/pasqualeandreola/DarkALP/SourceFiles/Fitter2DMass.cpp ]:
    /home/pasqualeandreola/DarkALP/SourceFiles/Fitter2DMass.cpp
Translation Unit Configurations:
[ /home/pasqualeandreola/DarkALP/SourceFiles/main.cpp ]:
    Process ID: 25440
    Memory Usage: 85 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --using_directory
        /home/pasqualeandreola/ROOT/lib
        --g++
        --gnu_version=110300
[ /home/pasqualeandreola/DarkALP/SourceFiles/Fitter2DMass.cpp ]:
    Process ID: 25452
    Memory Usage: 85 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --using_directory
        /home/pasqualeandreola/ROOT/lib
        --g++
        --gnu_version=110300
Total Memory Usage: 171 MB
```

### Screenshots

![Schermata del 2022-12-08 14-09-47](https://user-images.githubusercontent.com/55702526/206454876-8d3c252d-8c9c-4c43-be00-306c1f326a7e.png)

**Comment by Colengms** [comment]
Hi @PasqualeAndreola .  Could you enable the setting `"C_Cpp.loggingLevel": "Debug"` and provide the output from the C/C++ output channel, from launch up to the repro?

Normally, I wouldn't expect to see `--using_directory` added when in gcc mode on Linux.  It's related to Managed C++, C++/CLI.  It should only happen if the `/AI` arg was specified on a compile command line, or if there is a `LIBPATH` environment variable present.  Perhaps you have a LIBPATH environment variant defined for some purpose?  Or, the logs may show if `ms-vscode.makefile-tools` is providing a `/AI` arg.

**Comment by asdw159632** [comment]
Well, I'm facing the same issue. And my `LIBPATH` is defined which is required by `CERN ROOT`. So how can I fix this?

**Comment by sean-mcmanus** [comment]
The workaround is to downgrade to 1.12.4 until we can fix it in 1.13.8 (or run VS Code without the LIBPATH set).

**Comment by chrishanw** [comment]
I see the same issue on
OS: Ubuntu 20.04 (Linux x64 5.15.0-56-generic)
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Datum: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
C/C++: v1.13.7

Besides that default configuration, but using clang instead of gcc.
And funny enough, also using `CERN ROOT`, and having a `LIBPATH` set.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.8

**Comment by scaryrawr** [comment]
@sean-mcmanus is this fixed in 1.13.8? Or is it coming out after 1.13.8?

I'm seeing this still on Windows 11 ARM64 when launching from a Developer Command Prompt with 1.13.8.

**Comment by sean-mcmanus** [comment]
For the developer command prompt with cl.exe the LIBPATH is intententionally processed -- what issue are you hitting with it?

**Comment by scaryrawr** [comment]
> For the developer command prompt with cl.exe the LIBPATH is intententionally processed -- what issue are you hitting with it? i.e. 1.13.8 has the fix for Linux/Mac non-cl.exe scenarios.

@sean-mcmanus , I'm using `Visual Studio 2022 Developer Command Prompt v17.5.0-pre.2.0` on Windows 11 Pro Dev Insiders arm64.

```sh
> echo $env:LIBPATH
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\ATLMFC\lib\ARM64;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\lib\ARM64;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319
```

I use CMake based projects and get the `command-line error: invalid option: --using_directory`:

```
[{
	"resource": "/C:/Users/micha/GitHub/advent2022/beacon/main.cpp",
	"owner": "C/C++",
	"code": "571",
	"severity": 8,
	"message": "command-line error: invalid option: --using_directory",
	"source": "C/C++",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
```

If I launch the folder from a non-developer prompt, I do not see the error.

VSCode Information:
```
Version: 1.75.0-insider (user setup)
Commit: 717d7d62c8b4566ab6704de931e7fe8e0649d810
Date: 2023-01-03T08:53:30.938Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
Sandboxed: Yes
```
