### ISSUE TITLE
Create Declaration / Definition results can be delayed and inserted at an invalid position after the target file is modified

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10241]
1. Make the Create Declaration / Definition code action visible.
2. Do something to cause cpptools to get stuck, such as have IntelliSense update and the stuck on a hover.
3. Do Create Declaration / Definition (it should not complete yet)
4. Make changes to the target file such that the location the definition would be inserted is no longer valid (e.g. add new lines such that the definition would be put inside a function).

Bug: The definition will get inserted at an invalid spot. The reason is that there is no check if the target file is changed from when the request was initially made. Fixing this would require somehow getting the name of the target file (and then its version) before requesting the CDD result (and then canceling the edit if the version changed). Not sure if this is worth fixing compared to the work involved.

**Comment by michelleangela** [comment]
Closing as a won't fix because of very edge case.
