### ISSUE TITLE
malloc "a value of type "void *" cannot be used to initialize an entity of type "int *""

### ISSUE THREAD

**Issue by dennis0324** [microsoft/vscode-cpptools#10250]
### Environment

- OS and version: `window 10`
- VS Code: `1.74.0`
- C/C++ extension: `1.12.4` (i downgraded version due to #10244)
- OS and version of remote machine (if applicable): `ubuntu(WSL) 20.04.4`

### Bug Summary and Steps to Reproduce

Bug Summary:
currently i'm working on c .
Using malloc in header file but it seems vscode praser recognize header file as cpp's header file.

`main.h`
![image](https://user-images.githubusercontent.com/50710829/206465084-6a45e720-2703-48cc-9e72-d99c13586afd.png)

`main.c`
![image](https://user-images.githubusercontent.com/50710829/206466265-3f264026-e3ad-4905-9c12-d7af65d849a7.png)

`definition of stdlib.h`
they all go to same file
![image](https://user-images.githubusercontent.com/50710829/206466572-241919cd-87ea-46a9-92cc-f46e1731a3f6.png)

Steps to reproduce:
1. use malloc without casting data type in header file

**Comment by browntarik** [comment]
Thank you for your issue! Could you please respond with code snippets that I can copy and use to debug this issue myself?

**Comment by dennis0324** [comment]
Forgive me for being late.
When i tried in other project then `malloc` worked.
So I tried to find difference betwwen two project.

project that doesn't work use this `settings.json` 
```
{
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.default.compilerPath": "/usr/bin/gcc",
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.cStandard": "c99",
    "files.associations": {
        "*.h": "c",
    },
}
```
when i compare two project setting.json there was a line in `files.associations` which is `"stdlib.h":"c"`. So I try put stdlib.h in my not working project and i fixed my malloc problem!

but i wonder that `"*.h":"c"` should make all header to c compatible?

here's my fixed `settings.json` btw
```
{
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.default.compilerPath": "/usr/bin/gcc",
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.cStandard": "c99",
    "files.associations": {
        "*.h": "c",
        "stdlib.h":"c"
    },
}
```
