### ISSUE TITLE
Debugger arrow does not show up near the lines

### ISSUE THREAD

**Issue by ocpalo** [microsoft/vscode-cpptools#10256]
### Environment

- OS and version: Linux-Ubuntu 22.04
- VS Code:1.73.1
- C/C++ extension:g++11
- OS and version of remote machine (if applicable):
- GDB / LLDB version:12.1

### Bug Summary and Steps to Reproduce

Bug Summary: I cant see the arrow near the lines to debug. I am able to debug but somehow it does not show the arrow to show me which line i am at.

It creates a new file called `libc_start_call_main.h`. Inside of this file:
```cpp
Could not load source './csu/../sysdeps/nptl/libc_start_call_main.h': 'SourceRequest' not supported..
```

### Debugger Configurations

```shell
{
    "configurations": [
        {
            "name": "Engine Debug",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/engine",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}/build",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
        }
    ],
}
```

### Debugger Logs

```shell
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-w03xjkce.24r" 1>"/tmp/Microsoft-MIEngine-Out-w3jvvgpc.nxv"
```

**Comment by WardenGnaw** [comment]
In your `launch.json` file can you add the following block to your configuration and share the output in the `Debug Console`?

```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

**Comment by ocpalo** [comment]
@WardenGnaw Sorry I forgot to update here. I was compiling in `Release` mod. That is why it was not appearing. My bad.
