### ISSUE TITLE
debug works on Windows and fails on Linux

### ISSUE THREAD

**Issue by zhelnio** [microsoft/vscode-cpptools#1026]
Hello!
I am using VSCode for remote debugging of MIPSfpga-plus SoC: https://github.com/zhelnio/mipsfpga-plus/
All its build and debug scripts are cross platform (Windows 7 and Ubuntu 17.04, both x64). And I have no problems with gdb console debug in both cases. The gdb releases I am using are also very similar (different builds of one version).
So I have one common launch.json. But it works good only on Windows host, not Linux. On Linux I can Load program, but can not stop (pause) it. It just ignore all my actions.

My config:
https://github.com/zhelnio/mipsfpga-plus/blob/0e7c0bd42c5e74528989a352c4fad6742b382ed3/scripts/vscode/launch.json

VSCode debugger Log and gdb version/config info:
https://gist.github.com/zhelnio/54789029bc4bf5fdab0e2db1179005a2

Please help me with this problem.
I can give you some remote access if you need it.

Thanks.

**Comment by pieandcakes** [comment]
@zhelnio Can you provide an engine log of the repro? My assumption is that it is missing the '-g' compile flag to include symbols and it can't determine where to put the breakpoint.

**Comment by zhelnio** [comment]
Hello @pieandcakes !
The program was compiled with "-g -gdwarf-2" options.
I have added the full linux log to 
https://gist.github.com/zhelnio/54789029bc4bf5fdab0e2db1179005a2
There are successful program load, some steps, list command to view source, then run ...and ignore.

By the way: is this standalone DebuggerTerminal window is normal during debug? 
It contains nothing...
![vscode_debug_linux_screen](https://user-images.githubusercontent.com/6334288/30323109-9f3b072e-97c4-11e7-8c89-9930de91f8b2.png)
