### ISSUE TITLE
C_Cpp.files.exclude not works when filtering out non-c non-cpp files

### ISSUE THREAD

**Issue by Shaka0723** [microsoft/vscode-cpptools#10266]
### Environment

- OS and Version: win64-21H2
- VS Code Version:1.74.0
- C/C++ Extension Version: 1.13.7
- Other extensions you installed (and if the issue persists after disabling them):  
- If using SSH remote, specify OS of remote machine:  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

### Bug Summary and Steps to Reproduce

Bug Summary:
if your workspace contains both c and python files,  and you have already set cpptools configuration like below:
{
"C_Cpp.files.exclude": {
  "**/*.py": true, //exclude *.py
}

when you executing _**goto symbol in workspace_**, you can still find symbol defined in *.py

Steps to reproduce:
please see below screen shot to know what I was saying above

### Expected behavior

don't show symbols defined in non-c non-cpp files. e.g. *.py when user executing "go to symbol in workspace"

### Code sample and Logs

```shell
{
"C_Cpp.files.exclude": {
  "**/*.py": true, //exclude *.py
}

}
```

### Screenshots

![image](https://user-images.githubusercontent.com/56809930/207003177-c08bd212-2a05-4682-93c9-3efae3f773f0.png)

**Comment by browntarik** [comment]
Thank you for submitting this issue. I am currently looking into it and will get back to you soon.

**Comment by browntarik** [comment]
For our extension, we only consider excluding .cpp files. I suggest submitting an issue against the VSCode python extension found here: https://github.com/microsoft/vscode-python

This thread will now be closed unless there are further concerns.
