### ISSUE TITLE
C_Cpp.vcFormat.space.beforeInheritanceColon inverted effect

### ISSUE THREAD

**Issue by jb2170** [microsoft/vscode-cpptools#10263]
### Environment

- OS and Version: Arch Linux 2022-12-11
- VS Code Version: 1.73.1 6261075646f055b99068d3688932416f2346dd3b x64
- C/C++ Extension Version: v1.13.7
- Other extensions you installed (and if the issue persists after disabling them):  NA
- If using SSH remote, specify OS of remote machine:  NA
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The setting `C_Cpp.vcFormat.space.beforeInheritanceColon` has inverted effect, that is when set to `true` (default), there is no space between parent struct and colon before child struct eg
```cpp
struct Foo {};
struct Bar: Foo {};
```
with the setting `false` we obtain
```cpp
struct Foo {};
struct Bar : Foo {};
```

### Bug Summary and Steps to Reproduce

Create a .cpp file with the following
```cpp
struct Foo {};
struct Bar: Foo {}; /* LINE X */
```
Observe how the formatter does not insert a space before the `:` on the line with comment 'LINE X'.
Now toggle the setting to false in settings, and rerun the formatter; a space is inserted.

### Expected behavior

The setting's effect should be inverted

### Code sample and Logs

```shell
NA
```

### Additional context

Similar to #10262

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.2 .
