### ISSUE TITLE
Are all dependencies listed in ThirdPartyNotices.txt truly runtime?

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode-cpptools#10275]
Hello folks,

This is a follow up of previous question:

https://github.com/microsoft/vscode-cpptools/issues/9980

which you kindly answered already. The question this time is about the type of dependencies included on [ThirdPartyNotices.txt](https://github.com/microsoft/vscode-cpptools/blob/main/Extension/ThirdPartyNotices.txt). 

Would you say they are all runtime dependencies? Or, some may also be internal development dependencies? (eg for building, testing, docs generation, etc).

Thank you advance,
Merry xmas as well.

**Comment by sean-mcmanus** [comment]
They are runtime dependencies and not build time or internal dependencies. Was there a particular dependency you had a concern about?

**Comment by dariomx** [comment]
Thanks for confirming, Sean. No particular concern, just wanted to know if these were really runtime.

**Comment by sean-mcmanus** [comment]
But FYI, some stuff like "Clang (https://clang.llvm.org/)" is just because we build and bundle clang-format and clang-tidy and gcc is just for the glibc runtime on Linux/Mac, and we don't actually use any clang or gcc code in cpptools or cpptools to do any parsing, etc.

**Comment by sean-mcmanus** [comment]
And the list excludes third party closed source code that is licensed.

**Comment by dariomx** [comment]
Got it, thanks for letting me know Sean. Merry xmas.
