### ISSUE TITLE
The cpptools extension is not display in the extension column.

### ISSUE THREAD

**Issue by dalianzhi** [microsoft/vscode-cpptools#10278]
### Environment

- OS and version: ubuntu
- VS Code:1.74.0
- C/C++ extension:1.13.7
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:
The cpptools extension is not display in the extension column.

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do '...'
4. See error...

**Comment by sean-mcmanus** [comment]
Could you provide more info, such as a screenshot? I don't understand what you're referring to.

**Comment by dalianzhi** [comment]
![installed](https://user-images.githubusercontent.com/83261758/207488645-ba2985de-1569-44be-b0ff-b22c037b7d22.png)
![installed_dir](https://user-images.githubusercontent.com/83261758/207488654-f48774ec-cd71-48e4-96c1-41ec18a6acb9.png)
I installed the cpptools 1.13.7 and I can see the extension under the dir .vscode/extension.But I can not see the extension in the installed column.Please see the attached 2 png pictures.

**Comment by sean-mcmanus** [comment]
It looks VS Code is having some issue with installing our extension. Can you file a bug report at https://github.com/microsoft/vscode/issues ? Our extension isn't involved with our installation or with the Extensions UI window. You might also want to check for any VS Code error logging.
