### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by agrawalkaushik** [microsoft/vscode-cpptools#10273]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.13.7`
- OS Version: `Darwin x64 21.5.0`
- VS Code version: `1.72.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/3b/mfd0g8js5vg6_n5y6q8zlbnm0000gn/T/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by michelleangela** [comment]
@agrawalkaushik 
Could you provide more info such was when the extension is causing high cpu load? Is it during startup or when the extension is idle? Could you also provide the following logs when the extension is causing high cpu load:

1. Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
2. Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
