### ISSUE TITLE
intellisense does not work can't update

### ISSUE THREAD

**Issue by Lasybro** [microsoft/vscode-cpptools#10289]
Issue Type: <b>Bug</b>

I can't Update the c/c++ extension 
I tried update it manually but it didn't work
also the intelliSense doesn't work 
please help

Extension version: 0.27.1
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.86GB (0.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @Lasybro .  

Can you elaborate on the behavior when the extension failed to update?  Was a particular error reported?  How did you determine that the update failed?

Extension installs and updates are handled by VS Code itself.  Extensions don't generally have control over that behavior. You might consider opening an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).

You might try manually deleting the extension directory from: `%USERPROFILE%\.vscode\extensions`

**Comment by sean-mcmanus** [comment]
Yeah, as @Colengms mentioned, we're not involved in installing our selves. You should file an issue at https://github.com/microsoft/vscode/issues .
