### ISSUE TITLE
Not displaying C++ syntax errors in WSL Ubuntu subsystem.

### ISSUE THREAD

**Issue by jsouliss** [microsoft/vscode-cpptools#10291]
Type: <b>Bug</b>

Any .cpp file that is opened does not display error squiggles when there is a syntax error within the code while using the WSL Ubuntu subsystem.

Extension version: 1.13.8
VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.89GB (12.32GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/jerrysolis/OneDrive/Education/Fall%202022/CS%202400/Udemy%20Data%20Structures/Section_07 --remote=wsl+Ubuntu --crash-reporter-id 66c56b44-5bb5-42ef-b3de-acdbe533392e|
|Screen Reader|no|
|VM|29%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3693)|
|Memory (System)|15.57GB (14.52GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by sean-mcmanus** [comment]
You need to open a folder in order to get error squiggles (not open file). We have an issue tracking improving that at https://github.com/microsoft/vscode-cpptools/issues/10062 . Is that issue you're hitting?
