### ISSUE TITLE
Add to watch when caret within variable name, without selection

### ISSUE THREAD

**Issue by dev-joss** [microsoft/vscode-cpptools#10293]
Type: <b>Feature Request</b>

When the caret is within a variable name, be able to add to watch, without having to to create a text selection (select some characters within the variable name)

1. Create new C++ project
2. Debug..
3. Place left click on variable name to place caret on / in variable.
4. Right click
5. No option to watch variable.
6. Select some characters of the variable name (even just 1)
7. Right click
8. Option to watch variable.

This is the behaviour of visual studio

1. Create new C++ project
2. Debug..
3. Place left click on variable name to place caret on / in variable.
4. Right click
5. Option to watch variable

Extension version: 1.13.8
VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by TryerGit** [comment]
If you are willing to install an extension

https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command

this is possible:

Within keybindings.json:
```

{
        "key": "ctrl+alt+numpad1", // Or any other keyboard shortcut you want
        "command": "extension.multiCommand.execute",
        "args": {
            "command": "multiCommand.cursorwatch"
        }
}
```

Within settings.json:

```

{
            "command": "multiCommand.cursorwatch",
            "interval": 100,
            "sequence": [
                "editor.action.addSelectionToNextFindMatch",
                "editor.debug.action.selectionToWatch",
                "workbench.debug.action.focusWatchView",
                "list.focusLast",
                "list.focusPageDown"
            ]
}
```

**Comment by WardenGnaw** [comment]
The editor window is owned by the VS Code team. 

As this would be a UI change in the editor and a feature that could be used across multiple debug adapters, please file a bug at https://github.com/microsoft/vscode/issues
