### ISSUE TITLE
Create Declaration / Definition generates invalid code for a friend declaration in a template class

### ISSUE THREAD

**Issue by Stellarist** [microsoft/vscode-cpptools#10307]
### Feature Request
win10 x64 vscode
C/C++ extension version 1.13.8
1. The newly-added functions noticing the undefined function definations works not accurately right on template class, like:
 friend std::ostream& operator<< <>( std::ostream&, const ThisClass<T>& );   // inside a class
The intellisense will hint you it was not defined, but actually the defination outside doesn't require token "<>", leading to mismatching.
2. The intellisense and code analysis often work down, and if I click "restart code intellsense" or "run code anlaysis", it often work again once only, and  work no longer, so I need to click again or restart the project. And it often works down and shows the header problem at top of codes.

**Comment by sean-mcmanus** [comment]
I've reproed a bug with friend template declarations in general, and I've filed a bug on our shared VS component at https://developercommunity.visualstudio.com/t/C-Create-Definition-generates-invalid/10237634 .

But the I'm not getting `friend std::ostream& operator<< <>( std::ostream&, const ThisClass& );` to compile -- can you provide example of the full class template you're using that compiles?

For issue 2, we may need more repro info. Are you getting any crash messages in your C/C++ logging window?

**Comment by Stellarist** [comment]
Thank you for your replying.

1.	It seems that only overloading output operator may cause the problem, but obviously, the code can work, and I haven’t discover other phenomena like this in other functions. (in picture)

My code:
#include <iostream>
using std::cout, std::cin, std::ostream, std::istream;
template <typename T> class A;
template <typename T> ostream& operator<<(ostream&, const A<T>&);
template <typename T> istream& operator>>(istream&, A<T>&);
template <typename T> 
class A{
private:
    T value;
public:
    A()=default;
    A(T rhs): value(rhs) {}
friend ostream& operator<< <>(ostream&, const A&);
friend istream& operator>> <>(istream&, A&);
};
template <typename T>
ostream& operator<<(ostream& out, const A<T>& rhs)
{out<<rhs.value; return out;}
template <typename T>
istream& operator>>(istream& in, A<T>& rhs)
{...}

![Screenshot (5)](https://user-images.githubusercontent.com/93859937/209256175-f5861ca7-ee07-441b-8e6d-4422b653e3be.png)

2.	I forget to save my pictures. But code analysis does work down in some time: some variables may not be detected(become white color), and it can not detect easy problems momentarily, and sometimes it cannot detect headers unless I restart vscode occasionally(well, I'm sorry if it may be the problem of vscode and appear on other languages as well).

**Comment by sean-mcmanus** [comment]
Okay, thanks for the info -- it looks like the root bug may be due to the "friend function" handling in general, but I've added the additional repro to the VS bug in case that's a different case.
