### ISSUE TITLE
[OS X] Debug adapter process has terminated unexpectedly for the latest version

### ISSUE THREAD

**Issue by tekkamanblade0** [microsoft/vscode-cpptools#1030]
I got Version 0.12.4 yesterday but it doesn't work ("Debug adapter process has terminated unexpectedly") when I tried to debug a simple C++ project, which worked very well for the previous versions. 
My launch.json file:
```
 {
    "version": "0.2.0",
    "configurations": [

        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${file}.o",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb"
            }
        },
        {
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "${file}.o",
            "processId": "${command:pickProcess}",
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb"
            }
        }
    ]
 }
```

**Comment by sean-mcmanus** [comment]
What OS are you on? Debugging works for me on Windows/Linux but I haven't tried with your config. As a workaround you can try reverting to the previous version: http://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools/0.12.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage (renaming the zip to vsix and using the Install from vsix command).

**Comment by tekkamanblade0** [comment]
Thanks for your reply.
It is MacOS Sierra.

**Comment by sean-mcmanus** [comment]
Debugging on macOS Sierra with 0.12.4 works for me. I'll wait for Pierson to chime in.

**Comment by pieandcakes** [comment]
@tekkamanblade0 Can you go to your ~/.vscode/extensions folder and see if in the debugAdapter/bin/ folder there is an lldb folder? If you reinstall 0.12.4, can you confirm that the downloads happen when you restart VS Code?

**Comment by tekkamanblade0** [comment]
No, there is no folder called"lldb" under debugAdapter/bin/. But when I reinstalled 0.12.4, there were outputs saying that it is downloading some files, like "lldb"...

**Comment by tekkamanblade0** [comment]
Oh, I think it works. I deleted the whole folder "ms-vscode.cpptools-0.12.4" and reinstalled it. It works this time though I doesn't quite understand what happened:) Thank you!

**Comment by sean-mcmanus** [comment]
Yeah, that is strange. If a download fails we're supposed to give a failure message and retry the downloads the next time (the install.lock file that prevents additional downloads should only be written on success). Let us know if anyone has a repro for this issue.

**Comment by WardenGnaw** [comment]
Closing issue.

Please file another ticket if you experience this issue again.
