### ISSUE TITLE
No function suggestion when using namespace scope

### ISSUE THREAD

**Issue by silvio3105** [microsoft/vscode-cpptools#10305]
### Environment

- OS and Version: Windows 10 Pro
- VS Code Version: 1.74.2
- C/C++ Extension Version: 1.13.8

### Bug Summary and Steps to Reproduce

Bug Summary:

When I type namespace name(`sStd::`), autocomplete does not show any member of namespace.
If I type just function name, I get suggestion.

![2022-12-21 (1)](https://user-images.githubusercontent.com/104866334/208984216-3a11ba3c-cbaa-43c8-a7cf-ec6354fe8c9d.png)
![2022-12-21 (2)](https://user-images.githubusercontent.com/104866334/208984218-2aa8297b-e803-4c02-bd6a-ef1e49c454c7.png)
![2022-12-21](https://user-images.githubusercontent.com/104866334/208984219-4bfebf56-1abd-4767-a427-3b49380462d9.png)

### Configuration and Logs

```shell
`{
    "configurations": [
        {
            "name": "STM32F103x8",
            "includePath": [
                "Core/Inc",
                "Drivers/STM32F1xx_HAL_Driver/Inc",
                "Drivers/STM32F1xx_HAL_Driver/Inc/Legacy"
            ],
            "defines": [
                "UNICODE",
                "_UNICODE",
                "USE_HAL_DRIVER",
                "STM32F103x8",
                "__cplusplus"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-arm",
            "compilerPath": "${env:ARM-GCC}/arm-none-eabi-g++.exe",
            "compilerArgs": [
                "-mcpu=cortex-m3",
                "-mthumb"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true
            }
        }
    ],
    "version": 4
}`

`-------- Diagnostics - 21. 12. 2022. 20:08:47
Version: 1.13.8
Current Configuration:
{
    "name": "STM32F103x8",
    "includePath": [
        "Core/Inc",
        "Drivers/STM32F1xx_HAL_Driver/Inc",
        "Drivers/STM32F1xx_HAL_Driver/Inc/Legacy"
    ],
    "defines": [
        "UNICODE",
        "_UNICODE",
        "USE_HAL_DRIVER",
        "STM32F103x8",
        "__cplusplus"
    ],
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-arm",
    "compilerPath": "C:\\Development Tools\\ARM-GCC\\bin/arm-none-eabi-g++.exe",
    "compilerArgs": [
        "-mcpu=cortex-m3",
        "-mthumb"
    ],
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "Core/Inc",
            "Drivers/STM32F1xx_HAL_Driver/Inc",
            "Drivers/STM32F1xx_HAL_Driver/Inc/Legacy",
            "${workspaceFolder}"
        ]
    },
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false
}
Translation Unit Mappings:
[ C:\Users\silvi\OneDrive\Blue Pill\Core\Src\main.c ]:
    C:\Users\silvi\OneDrive\Blue Pill\Core\Src\main.c
Translation Unit Configurations:
[ C:\Users\silvi\OneDrive\Blue Pill\Core\Src\main.c ]:
    Process ID: 11412
    Memory Usage: 62 MB
    Compiler Path: C:\Development Tools\ARM-GCC\bin\arm-none-eabi-g++.exe
    Includes:
        C:\Users\silvi\OneDrive\Blue Pill\Core\Inc
        C:\Users\silvi\OneDrive\Blue Pill\Drivers\STM32F1xx_HAL_Driver\Inc
        C:\Users\silvi\OneDrive\Blue Pill\Drivers\STM32F1xx_HAL_Driver\Inc\Legacy
        C:\Development Tools\ARM-GCC\lib\gcc\arm-none-eabi\10.3.1\include
        C:\Development Tools\ARM-GCC\lib\gcc\arm-none-eabi\10.3.1\include-fixed
        C:\Development Tools\ARM-GCC\arm-none-eabi\include
    Defines:
        UNICODE
        _UNICODE
        USE_HAL_DRIVER
        STM32F103x8
        __cplusplus
    Standard Version: c17
    IntelliSense Mode: windows-gcc-arm
    Other Flags:
        --gcc
        --gnu_version=100301
Total Memory Usage: 62 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 1809
Number of files parsed: 233

`
```

### Other Extensions

![image](https://user-images.githubusercontent.com/104866334/208984379-47feb91c-9a7b-4c6b-a616-8122de7faf6c.png)

**Comment by sean-mcmanus** [comment]
Is your code supposed to be parsed as C or C++ -- IntelliSense is using C, but then why are defining __cplusplus and using a g++ compiler ? If you want to treat .c files as C++ you should add `"*.c": "cpp"` to your files.associations setting.

**Comment by silvio3105** [comment]
I changed c_cpp file to this

`{
    "configurations": [
        {
            "name": "STM32F103x8",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "UNICODE",
                "_UNICODE",
                "USE_HAL_DRIVER",
                "STM32F103x8",
                "__cplusplus"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-arm",
            "compilerPath": "${env:ARM-GCC}/arm-none-eabi-g++.exe",
            "compilerArgs": [
                "-mcpu=cortex-m3",
                "-mthumb"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true
            }
        }
    ],
    "version": 4
}`

and settings.json

`{
    "files.associations": {
		"*.c": "cpp",
		"*.h": "cpp"
    },
    "C_Cpp.intelliSenseEngineFallback": "enabled",
    "C_Cpp.intelliSenseEngine": "Tag Parser"
}`

It works but for some reason I don't see option to reset intellisense from right click menu. It's gone.
Also, before, on hover over string(eg. `printf("Hello World!");` it will display length of string(without NULL char). Now it's gone too.

Btw how I can reset whole extension to default values? I cannot reinstall it since other extensions depend on C/C++ extension.

**Comment by sean-mcmanus** [comment]
Using `"C_Cpp.intelliSenseEngine": "Tag Parser"` is not ideal and will result in "fuzzy" suggestions.

Reset IntelliSense Database is run from the VS Code Command Palette.

We don't provide a way to reset the extension to default values. You can reinstall our extension via disabling or uninstalling the extensions that have a dependency.

**Comment by mhtvsSFrpHdE** [comment]
## Environment
- OS and Version: Windows 10 Pro 22H2
- VS Code Version: 1.74.3
- C/C++ Extension Version: v1.13.9

@sean-mcmanus 

files.associations
![image](https://user-images.githubusercontent.com/10773245/214785341-fa48cab3-264e-4296-bacd-a04289401607.png)

header1
![image](https://user-images.githubusercontent.com/10773245/214785408-d06d9e5b-2d24-46f4-bde4-8e3cf7c7d836.png)

header1, namespace or class, no suggestions
![image](https://user-images.githubusercontent.com/10773245/214785558-1140641f-06ca-404c-95b6-de2a3e0bdf25.png)

header2
![image](https://user-images.githubusercontent.com/10773245/214785683-bdfeeb3b-9b39-4d87-95f5-214396b7ef9d.png)

header2, direct member, able to suggest
![image](https://user-images.githubusercontent.com/10773245/214785775-fd2a5779-0e82-4b0a-9c2e-0da7f9ecdc17.png)
