### ISSUE TITLE
typedef recognition (Suggestion)

### ISSUE THREAD

**Issue by Morvalyn** [microsoft/vscode-cpptools#1031]
It would be nice to be able to recognized custom typedefs..
an example is a simple struct with a custom typedef are all meta.block 

```
typedef uint8_t U8;
typedef volatile uint16_t V16;

struct {
    U8 tmpCnt;
    V16 Cntr;
} Counter;
```

**Comment by sean-mcmanus** [comment]
I don't understand what you're asking for. Counter in your example has the type of an unnamed struct. You didn't add a typedef. The other 2 typedefs are recognized. What do you mean by "meta.block"?

**Comment by Morvalyn** [comment]
Sorry i didn't clarify enough. Syntax highlighting - but having it be recognized as type, highlights is the same meaning V16 is part of the meta.block and Cntr is also part of the meta.block (Themes (using the TM inspect tool (forgot exact name). So when doing custom typedefs they are not recognized by the syntax highlighter. Which means they are the same color, all custom typedefs dont actual changes colors or at least for the version I'm using I know this may sound somewhat trivial, but not have the styling for custom types, can sometimes throw you off. As for the struct it's a typo my apologies, it should have a typedef added. I'll update it so its correct.

**Comment by bobbrow** [comment]
This would be covered by issue #230, but since the textmate grammars are all regular expression-based, I'm not sure how we're going to be able to do this unless we can update the grammars on the fly (not something that we've tried yet).
