### ISSUE TITLE
vs code giving incorrect output

### ISSUE THREAD

**Issue by daminiip** [microsoft/vscode-cpptools#10319]
```cpp
#include<iostream>
#include<math.h>
using namespace std;
int main()
{
    int n;
    
    int bit=0;
    int i=0;
    int bin=0;
    cout<<"enter n: ";
    cin>>n;
    while (n!=0)
    {
        bit=n&1;
        bin=(bit*pow(10,i))+bin;
        n=n>>1;
        i++;
    }
    cout<<"the binary representation is "<<bin<<endl;
    
}
```
this is the code i'm trying to run. this is the required output that i'm getting on an online compiler.
enter n: 16
the binary representation is 10000

however on vs code, this is the output:
enter n: 16
the binary representation is 9999

**Comment by sean-mcmanus** [comment]
I don't know why you're getting 9999. I get 10000 with cl.exe and gcc. How are you building?
