### ISSUE TITLE
Intellisense not finding local include files with MSVC when folder is accessible via WSL

### ISSUE THREAD

**Issue by tsherif** [microsoft/vscode-cpptools#10320]
### Environment

- OS and Version: Windows 10, build 19045.2364
- VS Code Version: 1.74.2
- C/C++ Extension Version: 1.13.8
- MSVC Version: 19.28.29335 for x64

### Bug Summary and Steps to Reproduce

Bug Summary: Intellisense seems unable to find local include files. I'm using `cl` to build, and the built executable works fine.

![image](https://user-images.githubusercontent.com/476017/209666937-6c247dd5-3651-41d6-9b32-a5fe94ef15f9.png)
![image](https://user-images.githubusercontent.com/476017/209667008-ce434627-0c51-4a75-a91b-23264aa53ce0.png)

Steps to reproduce:
I've created a test repo with a couple of test cases to demonstrate the issue: https://github.com/tsherif/vscode-cpp-test
It contains two directories that show slightly different behavior. Open VSCode in either one of these directories. 
1. The "flat" project keeps all files in the same directory. This one seemed to work fine when I first created it, but after I closed and opened VSCode, it could no longer find the includes.
2. The "nested" project keeps `main` in a "src" directory, and the included support files in a "lib" directory. Intellisense never worked for this one.

Expected behavior: Intellisense should find included files.

### Configuration and Logs

```shell
Log Diagnostics Output:
-------- Diagnostics - 12/26/2022, 8:12:34 PM
Version: 1.13.8
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\tarek\Code\vscode-cpp-test\flat\main.c ]:
    C:\Users\tarek\Code\vscode-cpp-test\flat\main.c
Translation Unit Configurations:
[ C:\Users\tarek\Code\vscode-cpp-test\flat\main.c ]:
    Process ID: 16492
    Memory Usage: 44 MB
    Compiler Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe
    Includes:
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\atlmfc\include
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c17
    IntelliSense Mode: windows-msvc-x64
    Other Flags:
        --using_directory
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\lib\x64
        --using_directory
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\lib\x64
        --using_directory
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\lib\x86\store\references
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0
        --using_directory
        C:\Windows\Microsoft.NET\Framework64\v4.0.30319
Total Memory Usage: 44 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 4958
```

### Other Extensions

- GLSL Lint v1.8.0
- HTML CSS Support v1.13.1
- Shader languages support for VS Code v1.1.5

**Comment by CLOUDERHEM** [comment]
add `${workspaceFolder}/**/**` to the  `includePath`, It works on my vscode

**Comment by tsherif** [comment]
Note that I didn't include a `c_cpp_properties.json` file in the test directories because it didn't seem to make a difference. He's what it looks like with the `includePath` explicitly given in a config file.

![image](https://user-images.githubusercontent.com/476017/209667336-ebf75f00-fc42-4147-9bce-eedcc082401c.png)
![image](https://user-images.githubusercontent.com/476017/209667436-f32496d5-e467-4f3c-aa6d-0d1b5397f9df.png)

**Comment by tsherif** [comment]
>add ${workspaceFolder}/**/** to the includePath, It works on my vscode

Tried this and it didn't seem to work for me. Are you using the same compiler?
![image](https://user-images.githubusercontent.com/476017/209667518-351997bb-7679-4a8d-8a90-357724d5619b.png)
![image](https://user-images.githubusercontent.com/476017/209667603-13cc325a-34bc-4ac1-9065-f6f87fca7cd2.png)

**Comment by sean-mcmanus** [comment]
Yeah, using the `#include "lib.h` should work. I'm not sure what could cause it to not work.

**Comment by tsherif** [comment]
I've figured out the issue, though I don't know the details of why it doesn't work. I was accessing the project via a directory that I frequently mount in WSL. If I move it to another directory that I don't access via WSL, it works properly.

I remember reading somewhere that Windows handles directories mounted via WSL differently so it can handle, e.g. Linux case-sensitivity, and that's what made me think of trying this. I'll share a resource that describes the details if I can find one (or maybe your colleagues would know?).

**Comment by tsherif** [comment]
There's some info here: https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

I can confirm that the directory I was having the problems in is case sensitive, while the directory I got things working in is not. Maybe `cl` has issues in case-sensitive directories? I have no problem compiling code with it in the case-sensitive directory, but maybe the functionality you're using doesn't fare as well?

**Comment by sean-mcmanus** [comment]
Yeah, we don't support case sensitive file paths on Windows by default -- the C_Cpp.caseSensitiveFileSupport setting needs to be set to "enabled". Does it work after changing that setting?

**Comment by tsherif** [comment]
Yup! That does it, thanks. Any downside to having that setting enabled? Is there a reason it’s not on by default?

**Comment by sean-mcmanus** [comment]
It's not the default because the Windows default is for the folders to not be case sensitive, and it theoretically could cause some feature to not work correctly in a case insensitive scenario, such as if the user had a #include <FILE.H> and `#include <file.h>` and they expect both to work, although I've not confirmed that.
