### ISSUE TITLE
Stop at a breakpoint which belongs to other file

### ISSUE THREAD

**Issue by CLOUDERHEM** [microsoft/vscode-cpptools#10323]
### Environment

- OS and version:
```
Edition	Windows 10 Pro
Version	22H2
Installed on	‎12/‎3/‎2022
OS build	19045.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0
```
- VS Code:
```
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```
- C/C++ extension:
```
Published 3/30/2016, 09:27:12
Last released 12/16/2022, 11:00:23
Last updated 12/17/2022, 18:42:13
Identifier ms-vscode.cpptools
```
- OS and version of remote machine (if applicable):
- GDB / LLDB version:
```
GNU gdb (GDB) 8.1
```

### Bug Summary and Steps to Reproduce

Bug Summary:

This is my project , I set some breakpoints in `ListNode/main.cpp`, then I code in `zero/main.cpp` and debug `zero/main.cpp`, the program stops at the breakpoints which are set in `ListNode/main.cpp` (happening only the same fileName )

> project tree
```
.
├── ListNode
│   ├── main.cpp
│   └── main.exe
└── zero
    ├── main.cpp
    └── main.exe
```

> screenshot

![image](https://user-images.githubusercontent.com/78064276/209608943-61405244-53da-4b1e-8c1b-2633b613251c.png)

### Debugger Configurations

1. task.json
```shell

{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "cppbuild",
            "command": "g++",
            "args": [
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}.exe",
                "-g",
                // "-Wall",
                // "-static-libgcc",
                "-fdiagnostics-color=always"
            ],
            "type": "cppbuild",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "cwd": "${fileDirname}"
            },
            "presentation": {
                "echo": true,
                "reveal": "silent",
                "focus": false,
                "panel": "shared"
            },
            "problemMatcher": [
                "$gcc"
            ]
        },
    ]
}
```
2. launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "cppdbg",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "cppbuild"
        }
    ]
}
```

### Debugger Logs

```shell
no error log
```

**Comment by WardenGnaw** [comment]
By default, the debugger sets breakpoints based on file name.

E.g. `-break-insert -f main.cpp:15`

If you want to use full file paths, you will want to add the following to your launch.json:
```
"sourceFileMap": {
   "${workspaceFolder}": { 
      "editorPath": "${workspaceFolder}",
      "useForBreakpoints": true
   }
}
```

[Reference](https://code.visualstudio.com/docs/cpp/launch-json-reference#_sourcefilemap)

**Comment by CLOUDERHEM** [comment]
> By default, the debugger sets breakpoints based on file name.
> 
> E.g. `-break-insert -f main.cpp:15`
> 
> If you want to use full file paths, you will want to add the following to your launch.json:
> 
> ```
> "sourceFileMap": {
>    "${workspaceFolder}": { 
>       "editorPath": "${workspaceFolder}",
>       "useForBreakpoints": true
>    }
> }
> ```
> 
> [Reference](https://code.visualstudio.com/docs/cpp/launch-json-reference#_sourcefilemap)

get it, thank you. so have you considered setting full file path as the default?
