### ISSUE TITLE
vcFormat incorrect using lambda functions

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10326]
Using Lambda-Functions:
```cpp
function_call([]() {
    char x;
char z;
char z;
    });
```
Expected:

```cpp
function_call([]() {
    char x;
    char z;
    char z;
});
```

Originally reported at https://github.com/microsoft/vscode-cpptools/issues/9800#issuecomment-1364539881

**Comment by GURKE** [comment]
Your expectations are wrong. I would expect an output like this:

    function_call( {
        char x;
        char y;
        char z;
    });

**Comment by sean-mcmanus** [comment]
@GURKE Sorry, it looks like the issue didn't get formatted correctly. I've updated it.

**Comment by sean-mcmanus** [comment]
The fix is available with 1.14.0 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.0

**Comment by GURKE** [comment]
> The fix is available with 1.14.0 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.0

Thanks for your work! I now get the following output:

    function_call( {
        char x;
        char y;
        char z;
        });

I personally would expect the last line not to be indentated (so same indentation as the function call itself), because this function is closed there. Like the following:

    function_call( {
        char x;
        char y;
        char z;
    });

This would be the same like having a "normal" function:

    function_call() {
        char x;
        char y;
        char z;
    }

**Comment by sean-mcmanus** [comment]
@GURKE I'll look into that.

**Comment by sean-mcmanus** [comment]
@GURKE I found out we have a setting for that -- set "C_Cpp.vcFormat.indent.lambdaBracesWhenParameter": false.

**Comment by GURKE** [comment]
You are true, it works! Thanks a lot for bugfixing and this investigation!
