### ISSUE TITLE
c_cpp_properties.json & compilerArgs : ' ' are automatically added to command line interpretation 

### ISSUE THREAD

**Issue by davrot** [microsoft/vscode-cpptools#10334]
### Environment

- OS and Version: 
Fedora 37

- VS Code Version: 
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:27:19.253Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.8-300.fc37.x86_64
Sandboxed: No

- C/C++ Extension Version: 
ms-vscode.cpptools@1.13.8

### Bug Summary and Steps to Reproduce

Bug Summary:

If I do this in the c_cpp_properties.json
            "compilerPath": "/usr/local/cuda-12/bin/nvcc",
            "compilerArgs": [
                "-allow-unsupported-compiler",
                "-ccbin /usr/lib64/ccache/clang++"
            ],
then I get this in C/C++ output window (C/Cpp logging level: debug):
**Invoking nvcc with command line: /usr/local/cuda-12/bin/nvcc -allow-unsupported-compiler '-ccbin /usr/lib64/ccache/clang++'  [....]**
where the latter parameter is not allowed (and everything cuda related stops working correctly. i.e. "Unable to find host compile command in output of nvcc."  & identifier "__device__" is undefined  & "expected a ';'" ). These ' ' are magically appearing but the user doesn't know that without debug enabled... 
 
If I change it to "-ccbin=/usr/lib64/ccache/clang++" then I get 
**Invoking nvcc with command line: /usr/local/cuda-12/bin/nvcc -allow-unsupported-compiler -ccbin=/usr/lib64/ccache/clang++ [...]**
which works nicely. 

### Configuration and Logs

```shell
Broken c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/local/cuda-12/bin/nvcc",
            "cStandard": "c17",
            "intelliSenseMode": "linux-clang-x64",
            "configurationProvider": "ms-vscode.makefile-tools",
            "compilerArgs": [
                "-allow-unsupported-compiler",
                "-ccbin /usr/lib64/ccache/clang++"
            ],
            "cppStandard": "c++14"
        }
    ],
    "version": 4
}

Leads to:
[...]
Invoking nvcc with command line: /usr/local/cuda-12/bin/nvcc -allow-unsupported-compiler '-ccbin /usr/lib64/ccache/clang++' /home/davrot/.vscode-server/data/User/workspaceStorage/504c0727523b326e8247a03ffadc5eae/ms-vscode.cpptools/nvcc_temp/temp.cu -c -x cu -odir /home/davrot/.vscode-server/data/User/workspaceStorage/504c0727523b326e8247a03ffadc5eae/ms-vscode.cpptools/nvcc_temp -keep -keep-dir /home/davrot/.vscode-server/data/User/workspaceStorage/504c0727523b326e8247a03ffadc5eae/ms-vscode.cpptools/nvcc_temp -v
Unable to find host compile command in output of nvcc.
[...]
```

### Other Extensions

nvidia.nsight-vscode-edition@2022.2.31663688
cuda 12

**Comment by bobbrow** [comment]
This is the expected behavior.  Each arg in `compilerArgs` is treated as one arg.  If there is a space in the arg, we add quotes around it so that it is treated as a single arg.  It sounds like the correct way to express this is as follows:
```
            "compilerArgs": [
                "-allow-unsupported-compiler",
                "-ccbin",
                "/usr/lib64/ccache/clang++"
            ],
```

**Comment by davrot** [comment]
But it is normal that one(!) compiler argument contains a space... 
e.g. from nvcc --help
--compiler-bindir <path>                        (-ccbin)                        
        Specify the directory in which the host compiler executable resides. 
--x {c|c++|cu}                                  (-x)                            
        Explicitly specify the language for the input files, rather than letting
        the compiler choose a default based on the file name suffix.

Adding silently quotes around that (inside of VS Code without information for the user) makes the resulting command un-executable and breaks stuff.  

How should the user expect this behavior from this description: 

"Compiler arguments
Compiler arguments to modify the includes or defines used, e.g. -nostdinc++, -m32, etc.
One argument per line."

And --compiler-bindir <path>  is one argument...

**Comment by sean-mcmanus** [comment]
Yeah, the space is when entered via the command line. For everywhere on the command line where you'd have an unquoted space you'd use a new element in the compilerArgs array. The command line shell will split those spaces into array elements to pass to the compiler.

I have a PR that updates the description at https://github.com/microsoft/vscode-cpptools/pull/10339 .
