### ISSUE TITLE
Auto format puts "#ifndef" (and "#endif") at beginning of line

### ISSUE THREAD

**Issue by delgermurun** [microsoft/vscode-cpptools#1033]
* Operating System and version: Ubuntu 17.04
* VS Code version and if you are using the Insiders build: Version 1.17.0-insider, Commit 06529dbcacb796d59e7fc2ca0ac5dbe7c29c099e
* C/C++ extension version: 0.12.4

Auto format moves any `#*` to beginning of the line. How can I disable it for at least on lines that begin with `#ifndef`/`#endif`.

formatted version:

```c++
int main()
{
  ios::sync_with_stdio(0), cin.tie(0);
#ifndef ONLINE_JUDGE
  freopen("input.txt", "r", stdin);
// freopen("output.txt", "w", stdout);
#endif
  return 0;
}
```

what I want is:

```c++
int main()
{
  ios::sync_with_stdio(0), cin.tie(0);
  #ifndef ONLINE_JUDGE
  freopen("input.txt", "r", stdin);
  // freopen("output.txt", "w", stdout);
  #endif
  return 0;
}
```

Thanks in advance.

**Comment by sean-mcmanus** [comment]
Our extension doesn't implement any auto formatting involving preprocessors. Our format on type functionality is limited to after typing a semicolon. How are you invoking the formatting? What other extensions do you have installed that could be doing the formatting? Does the bug still repro after uninstalling the C/C++ extension? Are you doing a Format Document command? That behavior is configurable via clang-format (http://releases.llvm.org/4.0.0/tools/clang/docs/ClangFormatStyleOptions.html , I haven't checked yet if there's an option for preprocessor indentation).

**Comment by delgermurun** [comment]
> How are you invoking the formatting?

Format on save is enabled (`"editor.formatOnSave": true`). Every time I hit `Ctrl+S`, formatting invoked.

> What other extensions do you have installed that could be doing the formatting?

I guess there is no other extension that could be doing the formatting on `.cpp` file.
My installed extensions are:
![screenshot from 2017-09-15 08-24-14](https://user-images.githubusercontent.com/492616/30461217-aea8a826-99f7-11e7-8c34-822f99ddf6e3.png)

> Does the bug still repro after uninstalling the C/C++ extension?

After I disable this extension, formatting doesn't happen at all on `.cpp` files.

> Are you doing a Format Document command?

As I said before, I just save file. No command calling, maybe `formatOnSave` calls this command.

**Comment by sean-mcmanus** [comment]
Unfortunately, clang-format doesn't support this style of formatting yet. Someone would have to add it to clang-format 6.0 -- see https://github.com/llvm-mirror/clang/commit/31c7a3b61a7c35ae586c7e36fbff1361e051d5ad . I think you want a "BeforeHash" option.

**Comment by delgermurun** [comment]
Okay. Thank you.
