### ISSUE TITLE
C++ Dark Theme: Inconsistent colorization

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cpptools#10332]
Type: <b>Bug</b>

Variables are not properly colorized as seen on the screenshot:

![image](https://user-images.githubusercontent.com/3337419/209951967-daedef52-6b94-4302-bb62-5d7331f77e0f.png)

I think this theme supports contextual colorization for local, member, parameter variables.

Extension version: 2.0.0
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.65GB (1.87GB free)|
|Process Argv|--crash-reporter-id c7a16f6b-33fc-42c2-aedd-68d1d1ff8687|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by sean-mcmanus** [comment]
The semantic colorization for local variables is enabled via `"C_Cpp.enhancedColorization": "enabled"` (in which case the theme also colors it differently). Have you changed that to "disabled" or is IntelliSense not enabled/configured?

The Developer: Inspect Editor Tokens and Scopes command can help diagnose issues related to the colors.

**Comment by Zingam** [comment]
> The semantic colorization for local variables is enabled via `"C_Cpp.enhancedColorization": "enabled"` (in which case the theme also colors it differently). Have you changed that to "disabled" or is IntelliSense not enabled/configured?
> 
> The Developer: Inspect Editor Tokens and Scopes command can help diagnose issues related to the colors.

I'm pretty sure that everything is setup correctly but I'll double check later and report if I'm mistaken.

Meanwhile I noticed similar issue on Ubunut 22.04. Please note the `window` variable in `main()`. To my understading the colorization pattern is:

- gray for parameters
- white for member fields
- blue for local variables 

![Screenshot from 2023-01-01 13-28-16](https://user-images.githubusercontent.com/3337419/210169158-ac860319-d38d-4184-b30a-4227c7556887.png)

The settings are:

![Screenshot from 2023-01-01 13-32-54](https://user-images.githubusercontent.com/3337419/210169307-17e9daef-4241-4ff0-90b9-e958925b8985.png)
![Screenshot from 2023-01-01 13-33-11](https://user-images.githubusercontent.com/3337419/210169309-beb81004-7d47-41ae-a221-8e64a3e3aeeb.png)

**Comment by Zingam** [comment]
It looks the above example is something different. Here is a minimal reproduction:

```c++
namespace namespace
{
  class C {};
  int i;
}

int
main(int argc, const char** argv)
{
  namespace::C c;
  namespace::i = 1;
}

**Comment by Zingam** [comment]
OK. The above example may be a different case than:|

```c++
namespace FirstEngine {

/// @brief
class Window
{
};

} // namespace FirstEngine
```
which is declared in another header in a static CMake library linked to the executable.

**Comment by Zingam** [comment]
If we compare the top screenshot with the current one bellow, we can notice the same effect with the `window` variable. So I guess the LS is unable to colorize the variable when declared in a namespace in another header. This looks like a bug to me:
![Screenshot from 2023-01-01 13-47-23](https://user-images.githubusercontent.com/3337419/210169642-cd7a7d40-b000-4ac9-8b7f-5790f22c8133.png)

**Comment by sean-mcmanus** [comment]
I don't repro the bug. I see the type Window in namespace FirstEngine having a semantic token of "Type" (green color). Could there be some IntelliSense parsing error that is breaking this? Does hover over the variable show correct info? The source file includes the header where the class is defined, right?

**Comment by Zingam** [comment]
The original report was on Windows.
Then I opened some configured project on Linux and observed similar issue. (as seen above).
I deleted the build directory and the cmake cash, reconfigured, rebuild and the issue fixed itself.
I don't know what to say.

**Comment by sean-mcmanus** [comment]
That's fine. Let us know if you figure out repro steps and we can investigate further. FYI, the latest CMake Tools 1.13.33 has a regression with IntelliSense configuration so using 1.13.31 is recommended till that's fixed if you're using that extension.
