### ISSUE TITLE
add auto switch header/source

### ISSUE THREAD

**Issue by cjwijtmans** [microsoft/vscode-cpptools#10346]
### Feature Request

Currently I have two editors open and I  am constantly switching header files in one editor. I would like to have an option to have an editor auto switch to header. Should be fairly simple to do as switch header/source function already exists. The option could exist in the three dots or a special  pane can be made that can be moved around with an editor inside that auto switches to header.

**Comment by sean-mcmanus** [comment]
I don't understand. Can you just run the Switch Header/Source command?

**Comment by cjwijtmans** [comment]
There would be a problem with that. Lets say i am able to run the command every time i switch source file in the main editor. How do i make sure the header file opens in the other editor? How do i make sure the header file is switched in the same tab of that editor so i don't end up with an editor that has 100 tabs open? If there's an easy way to script i would do it. But the extension could also provide a tab in the editor to do it for me?
How do i make an automation script in vscode? I am not familiar with js/ts let alone vs code api. if you can give me a reference to start that would be great.

**Comment by cjwijtmans** [comment]
Now that i think about it. It would be cool to be able to set a regex rule on an editor to determine files should open there. This would be an overal vscode feature though. That solves half the problem. Now the problem that i want a tab in the editor that is dedicated to automatically opening the header file when i open a source file.
