### ISSUE TITLE
command 'C_Cpp.ConfigurationProviderSelect' not found

### ISSUE THREAD

**Issue by ShreedharSutar** [microsoft/vscode-cpptools#10342]
Type: <b>Feature Request</b>

Type: Debugger
**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):

Extension version: 1.3.0
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by MeShreedhar** [comment]
c/c++ extension pack running status noy yet activated

**Comment by sean-mcmanus** [comment]
Can you upgrade from 1.3.0 to 1.13.8?
