### ISSUE TITLE
C++ standard in compile_commands should be respected

### ISSUE THREAD

**Issue by paul-reilly** [microsoft/vscode-cpptools#10345]
### Environment

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.85-1-MANJARO
Sandboxed: No
C/C++ Extension Version: 1.13.8

### Bug Summary and Steps to Reproduce

Bug Summary: C++ standard used in compile_commands is ignored

Reproduce: Use a compile_commands file with a different `-std=` than is set in vscode cpp properties.

Expected behavior: The compile_commands version should be respected.

--------------------

I understand that this has been considered in #1755, in particular with the comment:

>UPDATE: -std is sort of special case because it also sets flags we pass to our compiler -- not sure if it should overwrite the cppStandard or cStandard (which have a smaller range of values than -std).

I do think that the C++ version in compile_commands should be respected since it's what's live in the project. If a closest approximation or match of compile_commands `-std=` vs vscode compiler compatible `-std=` cannot be deduced then falling back to a map of one to another or a global default in the absence of such a thing could make sense.

### Configuration and Logs

```shell
c_cpp_properties.json

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "intelliSenseMode": "linux-clang-x64",
            "compileCommands": "${workspaceFolder}/.vscode/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
I agree.

**Comment by sean-mcmanus** [comment]
Oh, the -std in compile_commands should already be used (i.e. that's what I see when I try it). Do you have more repro info for when you're seeing it not being used?

**Comment by paul-reilly** [comment]
Of course, thanks for looking into this so quickly! I've uploaded a zip of a minimal repro project here that might be of help. 

It seems that VSCode is stuck at C++14, it doesn't matter if the compile_commands file is C++17 or C++20 here, I get a case of the dreaded squiggles when using > C++14 features.

[stdtest.zip](https://github.com/microsoft/vscode-cpptools/files/10346491/stdtest.zip)

**Comment by sean-mcmanus** [comment]
@paul-reilly Can you remove the compilerPath from your c_cpp_properties.json -- I believe that is causing it to skip using the compilerPath and compilerArgs in your compile_commands.json? It's possible there might be some other issues as well that I'm still investigating....

**Comment by paul-reilly** [comment]
Yes, that worked, I didn't think of changing that from the template created on first run of `C/C++: Edit Configurations (JSON)`. Although the two, C++ version and compiler, still seem too independent to me to intertwine.

Anyhoo at least I know what the issue is so thanks very much for investigating and clarifying!
