### ISSUE TITLE
undefines reference to this function

### ISSUE THREAD

**Issue by PYRET1C** [microsoft/vscode-cpptools#10341]
### Environment

- OS and Version:  windows 10
- VS Code Version: latest
- C/C++ Extension Version:  intellisense

### Bug Summary and Steps to Reproduce

Bug Summary:
Greetings, i am trying to create a user defined header file in cpp in vs code and i keep getting the error of "undefined reference to this function."  please help me determine what is wrong here i am attaching screenshots of the error and also my 3 files:
1. the header file
2. the cpp implementation file of the header file
3. the main function file
my goal here is to create a user defined header file, i can easily add a class in the main file itself but i want to learn more about the creation of header file.

Screenshot:
![screenshot](https://user-images.githubusercontent.com/88980503/210125447-b4ee6cb7-ce51-4ae1-97f8-14d92a21114c.JPG)

### Configuration and Logs

```shell
//Header file: 

#pragma once
class haha
{
private:
    int a = 0, b = 9;

public:
    int sum();
};


//Implementation file:

#include "haha.h"
#include <iostream>
int haha::sum()
{
    return a + b;
}


//Main function file

#include "haha.h"
#include <iostream>
int main()
{
    haha c;
    int a=0;
    a=c.sum();
    std::cout << a << std::endl;
    return 0;
}
```

**Comment by sean-mcmanus** [comment]
You need to compile the "implementation" file haha.cpp and then add the haha.o file for linking.

**Comment by PYRET1C** [comment]
hello sir, how can i compile the haha.cpp file in vs code? if i run it, it shows the following error: 
![1](https://user-images.githubusercontent.com/88980503/210989491-6088d5d6-3dc8-415d-8f59-e9a82ffae815.JPG)
and also  please show me how can i link the haha.o file and where do i neeed to link it.
regards.

**Comment by sean-mcmanus** [comment]
@PYRET1C See https://code.visualstudio.com/docs/cpp/config-linux#_modifying-tasksjson . That should work. Let me know if you hit an issue.

**Comment by sean-mcmanus** [comment]
Oh, you're on Windows, see https://code.visualstudio.com/docs/cpp/config-mingw#_modifying-tasksjson .

**Comment by PYRET1C** [comment]
//here is my tasks.json file:

{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\MinGW\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${workspaceFolder}/*.cpp",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}

**Comment by sean-mcmanus** [comment]
I'm not sure why it's not working, i.e. it works for me. One possibility is that your mingw g++.exe compiler might be an older version that doesn't support the particular arguments.
