### ISSUE TITLE
Supports format the code without already saving to a file.

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/vscode-cpptools#10351]
### Feature Request

Now, if you create a new file (not saved) in VSCode, and paste some C/C++ code in it for formatting, it will show you "no cpp formatter installed". If you save the file to disk, then retry again, it works well.

**Comment by sean-mcmanus** [comment]
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/4143 (you can upvote that issue).
