### ISSUE TITLE
Linking error: VS Code c++ will not compile all project files

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#10364]
I am using VS Code on Windows 10 with the "C/C++" extension and the Mingw-w64 compiler.  I was reading through a book on c++ where they use header files to organize code into other files. Since I have never tried linking files before, I thought the errors I got after running may have had to do with the program itself, so I made a smaller program that adds two numbers together. I still got the same error, which is `undefined reference to`.

here is my code

### test.cpp
```
#include "op.h"

int main(){
    add(1, 2);
    subtract(3, 4);

    return 0;
}
```
### op.h
```
#ifndef GUARD_OP
#define GUARD_OP

int add(int a, int b);
int subtract(int a, int b);

#endif
```
### op.cpp
```
#include "op.h"

int add(int a, int b){
    return a + b;
}

int subtract(int a, int b){
    return a - b;
}
```

I have tried editing my `tasks.json` file to accommodate the files but nothing seems to be working.

### tasks.json
```
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\msys64\\mingw64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                //"${fileDirname}/op.cpp",
                //"'${fileDirname}'/*.cpp",
                //"${fileDirname}/*.cpp",
                //"${fileDirname}/*.h",
                //"${workspaceFolder}\\*.cpp",
                //"${workspaceFolder}\\*.h",
                //"${workspaceFolder}/*.cpp",
                //"${workspaceFolder}/*.h",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
                //"${workspaceFolder}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```
The comments in `args` are all variants that I have tried. I have also tried some others that I did not document. Additionally, I code with the Arduino extension in VS Code and these types of files work fine, I have not explored very deeply into them with Arduino as they are all libraries I use and I did not code them myself.

This is very similar to this issue: https://github.com/microsoft/vscode-cpptools/issues/6753
I did what they tried in this one and it did not work.

Does anyone know how to fix this? Is it a VS Code issue or a c++ issue or something else? I have been trying to fix this forever and no one seems to have an answer that works for me.

**Comment by sean-mcmanus** [comment]
@JGuarnery See https://code.visualstudio.com/docs/cpp/config-linux#_modifying-tasksjson . That should work, i.e. use `"${workspaceFolder}/*.cpp"` instead of `${file}`. Let me know if you hit an issue.
