### ISSUE TITLE
Line |    1 |  … bugLauncher.exe' '--stdin=Microsoft-MIEngine-In-j0ldnqz2.lgi' '--stdo …      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      | Unexpected token ''--stdin=Microsoft-MIEngine-In-j0ldnqz2.lgi'' in expression or statement.

### ISSUE THREAD

**Issue by kishore7353** [microsoft/vscode-cpptools#10365]
### Environment

- OS and Version: 
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
please help me i cannot code in vsc
```

### Other Extensions

installed all extensions

**Comment by WardenGnaw** [comment]
Can you share the output from the `Debug Console` when you enable logging by adding the following to your `launch.json`:
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

**Comment by kishore7353** [comment]
i have tried in all the ways to solve  the issue, i cannot able to solve it and i thought the issue is in .exe file only,,,
so i changed my ide to codeblocks,,, now codeblocks is working fine to write c programs 
thankyou @WardenGnaw
