### ISSUE TITLE
right-click menu inaccessible in variable window when using GDB with custom pretty printers on type int

### ISSUE THREAD

**Issue by jamesrobb** [microsoft/vscode-cpptools#10363]
### Environment

- OS and version: Linux (Manjaro 22.0.0)
- VS Code: 1.74.2
- C/C++ extension:  1.13.9
- OS and version of remote machine (if applicable): Ubuntu 20.04
- GDB / LLDB version:  9.2 (inside remote container) 

### Bug Summary and Steps to Reproduce

Bug Summary:

When using [GDB pretty printing](https://sourceware.org/gdb/onlinedocs/gdb/Writing-a-Pretty_002dPrinter.html#Writing-a-Pretty_002dPrinter) I am no longer able to access the right-click menu on variables in the variable window if the type is an `int`. See the following image for clarification on what right-click menu I mean (I'm right-clicking on a `bool`).

![image](https://user-images.githubusercontent.com/3089512/211097091-58dc57a3-0724-47d7-9412-3dc9a9e880c6.png)

Once I have a pretty printer registered for `int`, I'm unable to right-click on the variables. I do see the intended pretty printing, though (see next image). If I want to copy the value I have to manually add it to the watch window, then right-click from there (where the right-click menu is accessible).  I have tried other data types, like `struct` and `bool`, but the ability to right-click remains - strangely just `int` seems to be the issue.

![image](https://user-images.githubusercontent.com/3089512/211101253-c0bcc4bc-9962-4aea-9f39-2387d4055542.png)

Steps to reproduce:
1. I use the Remote Explorer plugin to connect to my container
2. I launch a GDB debugging session with pretty printing registered for type `int`
3. When I hit a break point such that there are int variables in the variables window, I right-click
4. At this point the right-click does nothing, irrespective of what data type I click on.
5. If I start over again but have pretty printing enable for `bool` instead of `int` I can get the right-click menu for all entries in the variable window.

### Debugger Configurations

```shell
{
    "configurations": [
        {
            "name": "(GDB) PG",
            "type": "cppdbg",
            "request": "attach",
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "processId": "${input:processIdSql}",
            "program": "BINARY",
            "linux": {
                "MIMode": "gdb"
            },
            "logging": {
                "programOutput": true,
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            },
            "symbolLoadInfo": {
                "loadAll": false
            },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "text": "source ~/pp.py",
                    "description": "pretty print",
                    "ignoreFailures": false
                }
            ]
        }
    ]
}
```

### Debugger Logs

https://pastebin.com/4G8yp9gh

(the logs were too large to paste here)

### Additional Information

Contents of `pp.py`

```
class MoeWrapper:

  # The constructor takes the value and stores it for later.

  def __init__(self, val):
    self.val = val

  def to_string(self):
      return "Hey Homer"

def my_pp_func(val):
  if str(val.type.name) == "int":
      return MoeWrapper(val)

gdb.printing.register_pretty_printer(None, my_pp_func)
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
