### ISSUE TITLE
cpptools may incorrectly exit due to the 5 minute timeout check after re-awaking from a sleep state

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10362]
It seems to just happen in the background as I'm doing normal work, or I notice it when I come back to my desk after something else. I haven't seen any obvious cause from my end. Maybe it's related to coming in/out of sleep on my machine?

_Originally posted by @ryanmda in https://github.com/microsoft/vscode-cpptools/issues/10274#issuecomment-1372709802_

**Comment by sean-mcmanus** [comment]
@ryanmda Actually, when the 5 minute timeout occurs we kill the process with SIGINT and not SIGSEGV, so your issue seems like it might have a different cause...although I don't think we have enough info yet.

Maybe @Colengms might have an idea.

**Comment by ryanmda** [comment]
So, I got another core dump from `cpptools` today and it appears to coincide with when I woke my computer from sleep after a team meeting.

For reference, my working environment is:
1. VSCode 1.72.2 running on Windows 10 (10.0.19044.2364 if it matters)
2. Development is being performed in a Docker container based on Ubuntu 20.04
3. Container infrastructure is [Rancher Desktop](https://rancherdesktop.io/) for Windows, version 1.7.0, which is effectively running Docker inside WSL2

Hopefully it should be reproducible from that 😄

**Comment by sean-mcmanus** [comment]
A (potential) fix is available with 1.14.1 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.1 , i.e. let us know if you still repro it with that release.

**Comment by ryanmda** [comment]
I updated to the pre-release channel and it's been stable for a couple days now. Thanks!
