### ISSUE TITLE
Unable to start debugging. Unexpected GDB output from command "-environment -cd".

### ISSUE THREAD

**Issue by Laxaro-Void** [microsoft/vscode-cpptools#10366]
### Environment

- OS and version: Windows 10 Pro 22H2
- VS Code: 1.74.2
- C/C++ extension: v1.13.9
- GDB / LLDB version: GNU gdb 12.1

### Bug Summary and Steps to Reproduce

Bug Summary:
Is unable to start debugging. Unexpected GDB output from command "environment -cd". I trying test and explore Visual Studio Code in depth, I start learning C++ like a weak ago.

I follow Mysy64 and C/C++ extension installation in VsCode web GCC on Windows, i check environment variables path to match C:\msys64\mingw64\bin.
Then I create a HelloWorld.cpp like in the article.
And try run the debugger.

I did the troubleshooting `pacman -S --needed base-devel mingw-w64-x86_64-toolchain`  but no luck.

### Debugger Configurations

```shell
launch.json:
{
    "version": "0.2.0",
    "configurations": [
    {
        "name": "C/C++: g++.exe build and debug active file",
        "type": "cppdbg",
        "request": "launch",
        "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${fileDirname}",
        "environment": [],
        "externalConsole": false,
        "MIMode": "gdb",
        "miDebuggerPath": "C:\\msys64\\mingw64\\bin\\gdb.exe",
        "setupCommands": [
        {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
        }
        ],
        "preLaunchTask": "C/C++: g++.exe build active file"
    }
    ]
}

task.json:
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: cpp.exe build active file",
            "command": "C:\\msys64\\mingw64\\bin\\cpp.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
            "detail": "Task generated by Debugger."
        },
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\msys64\\mingw64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

```shell
Window popup.
Unable to start debugging. Unexpected GDB output from command "-environment-cd" (file direction) "" (file direction):No such file or directory.
```

### Other Extensions

C/C++ Extension Pack

### Additional Information

![image_2023-01-09_012149785](https://user-images.githubusercontent.com/122228807/211240671-12dc703f-cf5f-4e19-bb84-10065c17abfd.png)

**Comment by Laxaro-Void** [comment]
After a clean windows 10 reinstall, is still having the same issue. I follow ever single step in Vs code installation :/

**Comment by WardenGnaw** [comment]
GDB has a difficult time with folder paths with special characters. Can you move your project into a folder with no spaces or `+` or `,`. 

Keeping it simple with just characters works best.

**Comment by OneOfLosers** [comment]
have the same issue here with onedrive!
at first it ran and now it gives the same error above.
it even can not run the codes from the older directories without spaces.
Had to rename some folders and kill .json!

**Comment by K1ethoang** [comment]
Check your path? Can your path have special character

**Comment by Kuo0216** [comment]
With no space or no any special character in your path, this is a classical json problem.
/Program Project/........(X)
/ProgramProject/.........(O)

**Comment by davidcastillo2005** [comment]
https://stackoverflow.com/questions/69619818/unable-to-start-debugging-unexpected-gdb-output-from-the-command-environment-c
