### ISSUE TITLE
Can't go to the operator override method

### ISSUE THREAD

**Issue by aengusjiang** [microsoft/vscode-cpptools#1037]
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
logcat|abh|0.0.7
include-autocomplete|ajs|0.0.4
GBKtoUTF8|buk|0.0.2
compulim-vscode-dictionary|Com|0.0.5
githistory|don|0.2.3
xml|Dot|1.9.2
java-debug|DSn|0.0.2
vscode-javac|geo|0.0.46
CppSnippets|har|0.0.12
changeEncode|lan|0.0.8
cppcheck|mat|0.2.1
cpptools|ms-|0.12.4
PowerShell|ms-|1.4.3
vscode-icons|rob|7.12.0
vscode-header-source|ryz|1.1.0
code-settings-sync|Sha|2.8.3
guides|spy|0.8.4
java-imports-snippets|tus|0.0.1
java-snippets|tus|0.0.1
cmake|twx|0.0.17
vscode-lldb|vad|0.6.2
cmake-tools|vec|0.10.2
code-navigation|vik|0.2.0
vscode-react-native|vsm|0.4.1
change-case|wma|1.0.0
plsql-language|xyz|1.0.4
vscode-proto3|zxh|0.1.2

such as:
void operator += (const int st);

**Comment by sean-mcmanus** [comment]
It doesn't even work when the .operator+=() syntax is used (it tries to do a Go to Def on just the "operator" part).

**Comment by Colengms** [comment]
This looks to be working now.  F12 to go to definition on use of an overloaded operator is navigating to the definition.
