### ISSUE TITLE
class name not declared in this scope

### ISSUE THREAD

**Issue by PYRET1C** [microsoft/vscode-cpptools#10371]
### Environment

- OS and Version: windows 10
- VS Code Version: latest
- C/C++ Extension Version: intellisense

### Bug Summary and Steps to Reproduce

Bug Summary: Greetings. i am trying to make a custom header file and i am encountering a number of issues. below are my declaration file and implementation file:

//declaration file (haha.h)
#pragma once
class haha
{
private:
    int a = 0, b = 9;

public:
    int sum();
};

//implementation file  (haha.cpp)
#include "haha.h"

int haha::sum()
{
    return a + b;
}

now whenever i try to run the command: g++ haha.cpp 
it gives this error: 
![1](https://user-images.githubusercontent.com/88980503/211843731-c79adca0-2e24-4716-9016-cf7101d1d2ab.jpeg)

i want to know why does it say class not declared when i am including the .h file?

### Configuration and Logs

```shell
//here is my tasks.json:

{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\MinGW\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

**Comment by Colengms** [comment]
Hi @PYRET1C .  It looks like you are seeing a compiler error when compiling with g++.  That would not seem to be an issue with the C/C++ Extension, which provides IntelliSense services to VS Code for C/C++ source files.

My only guess, since you did not receive an error that `haha.h` could not be found, would be that you may have another header file of the same name that is getting picked up which does not declare `haha`.

**Comment by sean-mcmanus** [comment]
Also, where is haha.h located in relation to haha.cpp?

**Comment by PYRET1C** [comment]
thanks sir it is working now i was using an outdated compiler.
