### ISSUE TITLE
Temp files are generated at the incorrect path

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#10386]
This bug occurs when VSCode is opened with the Arduino extension enabled. After disabling the Arduino extension and using it for a few weeks, the bug still occurs and I think it is caused by a C/C++ extension.

![화면 캡처 2022-12-26 174857](https://user-images.githubusercontent.com/114203630/212680511-a653da30-cbfc-41d3-914f-a7d0a0c8027b.png)

**Comment by Colengms** [comment]
Hi @icedrocket .  Thanks for reporting this.  It looks like these are being created by the C/C++ Extension.  We may be able to fix this by simply adding a path delimiter to the existing logic.

**Comment by sean-mcmanus** [comment]
A fix is available with 1.14.1 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.1
