### ISSUE TITLE
`compile_commands.json` could not be parsed

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-cpptools#10387]
### Environment

- OS and Version: Windows 11
- VS Code Version:  1.74.3
- C/C++ Extension Version: 1.13.9
- If using SSH remote, specify OS of remote machine: Ubuntu 20.04

### Bug Summary and Steps to Reproduce

Bug Summary:

compile_commands.json:

```json
[
{
  "directory": "/data/git/scitt-ccf-ledger/build/app",
  "command": "/usr/bin/clang++-10 -DHAVE_ARPA_INET_H=1 -DINSIDE_ENCLAVE -DNGHTTP2_STATICLIB -DOE_BUILD_ENCLAVE -DPLATFORM_SGX -D_LIBCPP_HAS_THREAD_API_PTHREAD -Dscitt_enclave_EXPORTS -isystem /data/git/scitt-ccf-ledger/app/src -isystem /data/git/scitt-ccf-ledger/build/app/src -isystem /opt/ccf_sgx/include/ccf/_private -isystem /opt/openenclave/include -isystem /opt/openenclave/include/openenclave/3rdparty/libcxx -isystem /opt/openenclave/include/openenclave/3rdparty/libc -isystem /opt/ccf_sgx/include/ccf -isystem /opt/ccf_sgx/include -isystem /opt/ccf_sgx/include/3rdparty -isystem /opt/openenclave/include/openenclave/3rdparty -isystem /opt/ccf_sgx/include/3rdparty/quickjs -isystem /opt/ccf_sgx/include/3rdparty/QCBOR -isystem /opt/ccf_sgx/include/3rdparty/t_cose/inc -isystem /opt/ccf_sgx/include/3rdparty/nghttp2 -O3 -DNDEBUG -fPIC -fcolor-diagnostics -Wall -Wextra -Werror -Wundef -Wpedantic -Wno-unused -Wno-unused-parameter -m64 -fPIE -nostdinc -fstack-protector-strong -fvisibility=hidden -fno-omit-frame-pointer -ffunction-sections -fdata-sections -ftls-model=local-exec -nostdinc++ -mllvm -x86-speculative-load-hardening -DCONFIG_VERSION=\\\"2021-03-27\\\" -DEMSCRIPTEN -DCONFIG_STACK_CHECK -DCONFIG_BIGNUM -std=gnu++2a -o CMakeFiles/scitt.enclave.dir/src/main.cpp.o -c /data/git/scitt-ccf-ledger/app/src/main.cpp",
  "file": "/data/git/scitt-ccf-ledger/app/src/main.cpp"
}
]
```

See output pane:
> [1/16/2023, 9:48:09 PM] "${workspaceFolder}/build/app/compile_commands.json" could not be parsed. 'includePath' from c_cpp_properties.json in folder '...' will be used instead.

Expected behavior:
`compile_commands.json` is valid JSON and should be parsed correctly.

### Configuration and Logs

```shell
C/C++: Log Diagnostics:

-------- Diagnostics - 1/16/2023, 9:58:14 PM
Version: 1.13.9
Current Configuration:
{
    "name": "Linux",
    "compileCommands": "${workspaceFolder}/build/app/compile_commands.json",
    "compilerPathIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "intelliSenseModeIsExplicit": false,
    "mergeConfigurations": false,
    "browse": {
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 271271
```

**Comment by Colengms** [comment]
Hi @letmaik .  Are you certain that compile command line can be run successfully?

I tried reproducing this issue but was unable to.  I did not have your `-isystem` paths, so I had to remove those from the command line.  Also, I did not have clang++10, and used a different version of clang.  With those changes, and other minor changes such as the path to the file itself and output file, the command line appeared to be parsed fine for me.

Can you provide an stand-alone repro, perhaps in the form of a zip file or a github repo that we could clone, so we can investigate further?

**Comment by letmaik** [comment]
I tried to reproduce it in a fresh repo and devcontainer with the same dependencies etc. but it's all working as expected. Is there anything else I can do to debug this?

**Comment by Colengms** [comment]
Hi @letmaik .

Could you try temporarily removing all of the arguments from an entry in your `compile_commands.json`, then adding them back in one at a time until the issue repros?  Depending on which argument is triggering the issue, that might point us in the right direction.

**Comment by Colengms** [comment]
Hi @letmaik .  Following those steps, I do not repro a `could not be parsed` issue.  I get an initial:

```
"${workspaceFolder}/build/app/compile_commands.json" could not be found. 'includePath' from c_cpp_properties.json in folder 'scitt-ccf-ledger' will be used instead.
```

Due to the file not existing yet.  Then, after running the command you provided, and opening `app/src/main.cpp` (the only source file referred to in `compile_commands.json`), I get no further error about `compile_commands.json`.

I do see some issues.  It fails to find the `span` header.  This appears to be due to having specified a `compilerPath` in `c_cpp_properties.json`, which takes precedence over the compiler specified in `compile_commands.json`.  Removing the `compilerPath` from `c_cpp_properties.json`, I see the squiggles go away, and IntelliSense for `main.cpp` appears to be working properly, based on the args in `compile_commands.json`.  For example, if I paste in `CONFIG_VERSION` and hover over it, I see that it has the value that was specified on the command line.

**Comment by letmaik** [comment]
@Colengms Thanks for looking into this. With your changes and actually using a `c_cpp_properties.json` (which I only added in this branch) it seems to work. I think without that file there may have been some confusion. Generally, having many folders in the workspace the C++ extension would ask silly questions like "do you want to use A/compile_commands.json for B?". Why would it suggest to use a `compile_commands.json` from a different folder?

I'll keep an eye out for this error but adding an explicit `c_cpp_properties.json` seems to do the trick.
