### ISSUE TITLE
The server will not be restarted.

### ISSUE THREAD

**Issue by razrdog** [microsoft/vscode-cpptools#10389]

**Comment by Bernardin-MS** [comment]
@razrdog 
The message "The server will not be restarted." means that the language server crashed while processing.

Could you please provide the following information listed below to help us determine the cause of the crash:

**General:**
- Summary of the issue:
- Steps to reproduce it:

**Environment**:
- OS and Version: 
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 
 
**Any sample code** (that could have caused the crash):
