### ISSUE TITLE
-fms-extensions has no effect with an empty compilerPath

### ISSUE THREAD

**Issue by HampusAdolfsson** [microsoft/vscode-cpptools#10392]
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.74.3
- C/C++ Extension Version: 1.13.9

### Bug Summary and Steps to Reproduce

Bug Summary:
I am a developer on the [IAR Build](https://github.com/IARSystems/iar-vsc-build/) extension, which provides intellisense configurations for IAR projects to cpptools. Since cpptools doesn't support IAR compilers, the best approximation would be to:
* Set compilerPath to ""
* Set intellisense mode to clang-arm
* Enable ms-extensions with `-fms-extensions`

However, adding `-fms-extensions` to compilerArgs does not have any effect. From the discussion on #7886, I would think that the presence of the argument should be enough to enable the extensions, regardless of the compiler.

I've included a json config that demonstrates the issue below. With that config, the following C snippet produces a false-positive error when accessing members of the ms-style anonymous union:
```c
typedef struct {
    union _u {
        int a;
    };
} AnonymousMember;
void main()
{
    AnonymousMember str;
    str.a = 1; // error: struct "<unnamed>" has no field "a"
}
```

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compilerArgs": ["-fms-extensions"],
            "compilerPath": "",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-clang-arm",
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @HampusAdolfsson .  This is currently by-design.  `compilerArgs` has no meaning without a `compilerPath`.

We could keep this issue as a feature request, to provide access to certain IntelliSense options without having specified a compiler.

A hacky work-around would be to modify the files associated with IntelliSense mode you are using, in the extension install directory.  i.e. `%USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.13.9-win32-x64\bin\windows.clang.arm.json`

and adding the following argument to the `defaults` list it contains:
```
--ms_extensions
```

That should instruct the IntelliSense process to enable that setting.  However, without providing any other information related to the compiler, there could be other details missing that may be necessarily to get fully functional IntelliSense.

Ultimately, we'd like to support the IAR compiler.  The best issue to track that is likely: https://github.com/microsoft/vscode-cpptools/issues/7653
