### ISSUE TITLE
clang-tidy settings `UseColor` breaks clang-tidy integration

### ISSUE THREAD

**Issue by tnixeu** [microsoft/vscode-cpptools#10407]
### Environment

- OS and Version: Windows 11
- VS Code Version: v1.74.3
- C/C++ Extension Version: v1.13.9
- clang-tidy Version: v15.0.6

### Bug Summary and Steps to Reproduce

Bug Summary:

The clang-tidy integration does not work if in the clang-tidy configuration file `UseColor` is set to `true`. It seems that the coloring information breaks the parser.

Steps to reproduce:
1. Create a clang-tidy configuration file
2. Set UserColor to true
3. set `"C_Cpp.loggingLevel": "Information"` // not need but helps debugging it
4. Run Code Analysis 
5. Clang-tidy finishes but no warnings or errors are highlighted by squiggles 
6. Output in C/C++ log shows the clang-tidy output as 
![grafik](https://user-images.githubusercontent.com/4436784/213663437-3fe9ac04-2183-4543-8398-01b1edba3026.png)

Expected behavior:

Ignore coloring information when parsing clang-tidy output or silently configure clang-tidy to not use color in its output by adding `--use-color=false` to the command line.

Workaround:

For now I am using `"C_Cpp.codeAnalysis.clangTidy.args": ["--use-color=false"]` in order to get the clang-tidy integration working again.

### Configuration and Logs

```shell
I do not think this is need for this bug
```

**Comment by browntarik** [comment]
Could you please provide a snippet of the .clang-tidy file you are using?
