### ISSUE TITLE
IntelliSense shows a wrong type for a non-suffixed decimal integer literal

### ISSUE THREAD

**Issue by yang-example** [microsoft/vscode-cpptools#10412]
### Environment

- OS and Version: Windows 10 Enterprise; Version 0.0.19044
- VS Code Version: 1.74.3
- C/C++ Extension Version: 1.14.0
- If using SSH remote, specify OS of remote machine: None

### Bug Summary and Steps to Reproduce

Bug Summary:
For a decimal integer literal without any suffix like 3'000'000'000, the type should be the first type that can represent it in the list: int, long, and long long per standards. But the IntelliSense pops unsigned long instead of long long.

Steps to reproduce:
Write an expression including a literal that int cannot represent, like 3000000000, and move the cursor over it.
![bug](https://user-images.githubusercontent.com/90231054/213963758-de870d3e-c7ed-4aee-a94e-528c7afa48fa.png)

Expected behavior:
It should be long long.

### Configuration and Logs

```shell
c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.22000.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by browntarik** [comment]
Could you provide a code snippet I can use to reproduce this behavior?

**Comment by yang-example** [comment]
For example:
`int i = 3'000'000'000; `
When your cursor hovers over the number, the IntelliSense will show its type as _unsigned long_.
I find that it is a problem with the Microsoft compiler. In _c_cpp_properties.json_, the "compilerPath" is set to cl.exe by default.
If I change it to the path to the GCC compiler, the type of the integer literal can be correctly shown as _long long_.

**Comment by browntarik** [comment]
Thank you, it seems as though this is a compiler specific issue. I am currently looking into this further.

**Comment by sean-mcmanus** [comment]
This bug is caused by our not defaulting to using
```
            "compilerArgs": ["/permissive-"]
```.

The bug is "fixed" if you add that argument.

**Comment by sean-mcmanus** [comment]
This is actually "by design" for the previously stated reason -- cl.exe with the default argument of /permissive.
