### ISSUE TITLE
#include errors detected ... cannot open source file "iostream

### ISSUE THREAD

**Issue by NikoGP** [microsoft/vscode-cpptools#1041]
Hello, so I am new to coding and wanted to use VS Code to code in C++, so I installed it, installed C/C++ IntelliSense v0.12.4 and followed instructions on the VS Code website to make a c_cpp_properties.json file and copied the code into it like they said. When I open my .cpp project that I had made in notepad++, I get the error:
"#include errors detected. Please update your includePath. IntelliSense features for this translation unit (directory\file.cpp) will be provided by the Tag Parser. (9, 1)
cannot open source file "iostream" (9, 1)"

My .cpp code
`#include <iostream>

using namespace std;

int main()
    {
        string firstName, lastName;
        double hourRate, numHours;
        
        cout << "+----------------------------------------+" << endl;
        cout << " Your first name and last name: ";
        cin >> firstName >> lastName;
        cout << " Your hourly rate: ";
        cin >> hourRate;
        cout << " Number of hours worked last week: ";
        cin >> numHours;
        cout << endl;
        
        double regPay, overTPay, gPay, socSec, med, netPay;
        if (numHours <= 40)
        {
            regPay = hourRate * numHours;
            gPay = regPay;
            overTPay = 0;
        }
            else
            {
                double oTHours;
                oTHours = numHours - 40;
                regPay = hourRate * (numHours - (numHours - 40));
                overTPay = (hourRate * 1.5) * oTHours;
                gPay = regPay + overTPay;
            }
        socSec = gPay * 0.062;
        med = gPay * 0.0145;
        netPay = gPay - (socSec + med);
        cout << "+----------------------------------------+" << endl << endl;
        cout << " Pay Stub\n" << " Regular pay  $" << regPay << endl;
        cout << " Overtime pay $" << overTPay << endl;
        cout << " Gross pay    $" << gPay << endl;
        cout << " Social Sec.  $" << socSec << endl;
        cout << " Medicare     $" << med << endl;
        cout << " Net Pay      $" << netPay << endl << endl;
        cout << "+----------------------------------------+" << endl << endl;
        cout << " Pay to: " << firstName << " " << lastName << endl;
        cout << " Total Pay: $" << netPay << endl << "\t\t\t   ";
        cout << "Signed: P inc." << endl;
        cout << "+----------------------------------------+" << endl;
        
        return 0;
    }`

My c_cpp_properties.json file
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++",
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```

Also, when I hover over the "<iostream>" this shows up:
"#include errors detected. Please update your includePath. IntelliSense features for this translation unit (E:\Stuff\CS11-Things\Homeworks\A3\paycheck.cpp) will be provided by the Tag Parser.
cannot open source file "iostream""

Let me know if you need any more information

**Comment by sean-mcmanus** [comment]
Your includePath only has `${workspaceRoot}`. You need to add the path to your system directories. If you're using MinGW, see https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md .

**Comment by GiBg1aN** [comment]
If you are using Linux you have to add the path `/usr/include/linux`

**Comment by ZoeVonFeng** [comment]
I had same issue on windows, after I add the  `"C:\\cygwin64\\lib\\gcc\\x86_64-pc-cygwin\\6.4.0\\include\\c++"` at includePath, I got this error: `cannot open source file "bits/c++config.h" (dependency of "iostream")`

**Comment by bobbrow** [comment]
What does gcc tell you the include path should be?  Run this command and make sure all of the paths printed out are listed in your c_cpp_properties.json: `gcc -v -E -x c++ -`

**Comment by NikoGP** [comment]
@sean-mcmanus after adding the code from the link you gave it still complains, I didn't add "C_Cpp.intelliSenseEngine": "Default" to my settings.json file because I have no clue where it is. Anyway, this is the new error I am getting.
"#include errors detected. Please update your includePath. IntelliSense features for this translation unit (E:\\\program.cpp) will be provided by the Tag Parser. (9, 1) cannot open source file "iostream" (9, 1)"

**Comment by sean-mcmanus** [comment]
@NikoGP Go to File->Preferences->Settings and search for "intelliSenseEngine" to find the setting. You have "Default" set already though. Did you run the gcc command @bobbrow mentioned? Can you provide your updated c_cpp_properties.json? You basically need to find where your iostream header is getting pulled from by your compiler and add the path to the includePath setting (and make sure the defines are correct). Does Go to Definition work on the header file? If so, that means the iostream file was found via a recursive search of your browse.path setting.

**Comment by NikoGP** [comment]
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "configurations": [
                {
                    "name": "Win32",
                    "intelliSenseMode": "clang-x64",
                    "includePath": [
                        "${workspaceRoot}",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include/c++",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include/c++/mingw32",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include/c++/backward",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include",
                        "C:/MinGW/include",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include-fixed"
                    ],
                    "defines": [
                        "_DEBUG",
                        "UNICODE",
                        "__GNUC__=5",
                        "__cdecl=__attribute__((__cdecl__))"
                    ],
                    "browse": {
                        "path": [
                            "C:/MinGW/lib/gcc/mingw32/5.3.0/include",
                            "C:/MinGW/lib/gcc/mingw32/5.3.0/include-fixed",
                            "C:/MinGW/include/*"
                        ],
                        "limitSymbolsToIncludedHeaders": true,
                        "databaseFilename": ""
                    }
                }
            ],
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 3
}
```

Here is my current c_cpp_properties.json file, when I hover over the "{" before configurations Win32 it says "missing property "name""
Also, I installed cygwin before installing MingW, I'm not sure if that messes anything up or not

**Comment by bobbrow** [comment]
I reformatted your comment.  There is a "configurations" element inside your "configurations" which is invalid syntax for the c_cpp_properties.json file.  Fix it like below:

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
                    "name": "Win32",
                    "intelliSenseMode": "clang-x64",
                    "includePath": [
                        "${workspaceRoot}",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include/c++",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include/c++/mingw32",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include/c++/backward",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include",
                        "C:/MinGW/include",
                        "C:/MinGW/lib/gcc/mingw32/5.3.0/include-fixed"
                    ],
                    "defines": [
                        "_DEBUG",
                        "UNICODE",
                        "__GNUC__=5",
                        "__cdecl=__attribute__((__cdecl__))"
                    ],
                    "browse": {
                        "path": [
                            "C:/MinGW/lib/gcc/mingw32/5.3.0/include",
                            "C:/MinGW/lib/gcc/mingw32/5.3.0/include-fixed",
                            "C:/MinGW/include/*"
                        ],
                        "limitSymbolsToIncludedHeaders": true,
                        "databaseFilename": ""
                    }
        }
    ],
    "version": 3
}
```

**Comment by NikoGP** [comment]
Even using the code above @bobbrow VSC still complains and says;
"#include errors detected. Please update your includePath. IntelliSense features for this translation unit (E:\\program.cpp) will be provided by the Tag Parser. (9, 1) cannot open source file "iostream" (9, 1)"
in the problems section below my code

![Screenshot of output](https://user-images.githubusercontent.com/6447047/30668556-fdb13d04-9e0f-11e7-9556-90c93b31ad86.png)

**Comment by bobbrow** [comment]
What version of MinGW are you using?  In your first post, it looked like you had 6.3.0 in your include path.  In your most recent post, it looked like you pasted in include paths for 5.3.0 from our MinGW page.

**Comment by NikoGP** [comment]
Okay, I think that my problem lies in the fact that I had installed cygwin prior to MingW, and then I incorrectly installed the required packages for MingW to properly function.
Is there somewhere that I can find what packages I need to install for VS Code to work properly with MingW?

**Comment by smithalexk** [comment]
I am also having the issue seen by @NikoGP with my Intellisense after upgrading to v0.13.0.  When I turned on the "Default" setting on the Intellisense engine, I keep receiving an iostream include path error (see attached files).  I'm running MacOS 10.12.6, and have updated the LLVM engine as well.

The error under the iostream include is: 
#include errors detected. Please update your includePath. IntelliSense features for this translation unit /pathToProgram/) will be provided by the Tag Parser.
cannot open source file "wchar.h" (dependency of "iostream")

Simple "Hello World" example showing the error:
![helloworld_example](https://user-images.githubusercontent.com/16105853/30923114-f2263b40-a3a2-11e7-8c67-408a0c189367.png)

My c_pp_properties.json file:
![c_pp_properties](https://user-images.githubusercontent.com/16105853/30923147-0337b77e-a3a3-11e7-83a7-e6c7813f9f83.png)

**Comment by bobbrow** [comment]
@smithalexk, for me, this file resides in `/usr/include`.  What does `clang -Wp,-v -E -xc -x c++ /dev/null` show as your include path?  The "includePath" in your c_cpp_properties.json file should match that.

**Comment by smithalexk** [comment]
Yep that looks to have fixed it.  Thanks for the help!

For reference, I was missing:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks

**Comment by dorsa1986** [comment]
I'm new at coding, I installed Visual Studio code to code in c++ based on the instructions of https://code.visualstudio.com/docs/languages/cpp, after following all steps, I got a lot of error.

<img width="1421" alt="screen shot 2017-09-29 at 3 58 45 pm" src="https://user-images.githubusercontent.com/32402167/31039042-33274fac-a52f-11e7-9f8b-cf1765400a7d.png">


my c_cpp_properties.json file:

<img width="992" alt="screen shot 2017-09-29 at 4 04 25 pm" src="https://user-images.githubusercontent.com/32402167/31039137-07668f08-a530-11e7-8135-d5e7ebc5a98b.png">

My tasks.json file:

<img width="553" alt="screen shot 2017-09-29 at 4 06 27 pm" src="https://user-images.githubusercontent.com/32402167/31039151-2cde1706-a530-11e7-9df8-ce5e59a130e1.png">

My launch.json file:

   
<img width="652" alt="screen shot 2017-09-29 at 4 22 52 pm" src="https://user-images.githubusercontent.com/32402167/31039439-86e80d40-a532-11e7-90be-a9ea773cc8a9.png">

My User Setting is: 

<img width="1125" alt="screen shot 2017-09-29 at 4 15 53 pm" src="https://user-images.githubusercontent.com/32402167/31039293-867a1048-a531-11e7-8eb0-a530f22b43cc.png">

The path of the FirstProg folder is :

<img width="252" alt="screen shot 2017-09-29 at 4 17 15 pm" src="https://user-images.githubusercontent.com/32402167/31039460-aef85876-a532-11e7-9b05-4b04e37b6209.png">

**Comment by bobbrow** [comment]
@dorsa1986, what does `g++ -Wp,-v -E -xc -x c++ /dev/null` show as your include path?  The "includePath" in your c_cpp_properties.json file should match that.

**Comment by smithalexk** [comment]
Hi @dorsa1986, I also noticed that you spelled "iostream" incorrectly.  You are currently including the "ioastream" header.  That looks like it could be causing your error.

**Comment by dorsa1986** [comment]
@smithalexk Thanks, I corrected but still, I got error

<img width="1100" alt="screen shot 2017-10-02 at 9 25 07 am" src="https://user-images.githubusercontent.com/32402167/31087895-a60a025a-a753-11e7-88f0-5c635878202f.png">

**Comment by dorsa1986** [comment]
@bobbrow  they matched. 

<img width="600" alt="screen shot 2017-10-02 at 9 27 57 am" src="https://user-images.githubusercontent.com/32402167/31087998-033ba6f4-a754-11e7-8db3-803d6a9cd439.png">

**Comment by bobbrow** [comment]
According to that error, either your tasks.json is not building your program correctly, or your launch.json has an incorrect path to the built program.  But this is not an issue with IntelliSense.  I don't see any red squiggles in your editor.

**Comment by dorsa1986** [comment]
how can I solve them?

**Comment by bobbrow** [comment]
Open tasks.json or launch.json (in the .vscode folder) and verify that they are correct

**Comment by dorsa1986** [comment]
it's my launch.jason file:

<img width="652" alt="screen shot 2017-10-02 at 9 38 59 am" src="https://user-images.githubusercontent.com/32402167/31088478-a54fb880-a755-11e7-9d06-2d58c8ea435d.png">

**Comment by dorsa1986** [comment]
This is my tasks.json:

<img width="529" alt="screen shot 2017-10-02 at 9 40 40 am" src="https://user-images.githubusercontent.com/32402167/31088556-e5ffa71e-a755-11e7-9d5f-767087ec9575.png">

I've been working on this about 4 days. I can't find my mistake.

**Comment by bobbrow** [comment]
Based on what I see in your previous posts, I'm going to guess that the path should be `/Users/dorsat/Desktop/FirstProg/a.out`

**Comment by dorsa1986** [comment]
I got the same error.

**Comment by bobbrow** [comment]
Did you build it yet?  Open your terminal or a Finder window and tell me where your compiled program lives.

**Comment by sean-mcmanus** [comment]
@dorsa1986 Is a.out the name of the executable? Does it have executable permissions? Can you run it without VS Code from a command line?

**Comment by dorsa1986** [comment]
When I built it from the VScode terminal, I got this error:
<img width="473" alt="screen shot 2017-10-02 at 12 07 01 pm" src="https://user-images.githubusercontent.com/32402167/31094514-5dbd2bf0-a76a-11e7-875a-f6ad3a4e99ec.png">

when I used Debug menu, I got this page:
<img width="524" alt="screen shot 2017-10-02 at 12 09 47 pm" src="https://user-images.githubusercontent.com/32402167/31094598-9ed28194-a76a-11e7-8b02-d5dc8b236cce.png">

**Comment by bobbrow** [comment]
Are you able to build in a Mac terminal?  Try adding `-std=c++11` to the command line.

**Comment by dorsa1986** [comment]
@sean-mcmanus  I'm new in coding, I think so. However, It's made automatically in my folder.

<img width="142" alt="screen shot 2017-10-02 at 1 06 36 pm" src="https://user-images.githubusercontent.com/32402167/31097000-acba8fec-a772-11e7-87bc-f1cb51035539.png">

**Comment by dorsa1986** [comment]
@bobbrow No, I'm not. I got the same error.

<img width="581" alt="screen shot 2017-10-02 at 1 08 49 pm" src="https://user-images.githubusercontent.com/32402167/31097066-edf37122-a772-11e7-8c62-0087ebc45fc2.png">

I got this error when I added -std=c++11 to the command line.

![image](https://user-images.githubusercontent.com/32402167/31097214-645af542-a773-11e7-86cf-f5e915dd55bf.png)

**Comment by bobbrow** [comment]
It looks like it's trying to compile your code as C code, not C++.  Add `-x c++` to the command line.

**Comment by dorsa1986** [comment]
<img width="572" alt="screen shot 2017-10-02 at 2 31 53 pm" src="https://user-images.githubusercontent.com/32402167/31100492-74c6266c-a77e-11e7-8383-a46f979befa9.png">

**Comment by dorsa1986** [comment]
@bobbrow Do you have specific instructions for Mac book pro? to follow those steps and reinstall it. However, I've tried it several times based on https://code.visualstudio.com/docs/languages/cpp. But I've gotten the same error at each time. I can't find my mistakes.

**Comment by bobbrow** [comment]
There should be plenty of websites out there that can walk you through the steps of getting your code to build.  This forum is for troubleshooting bugs in the VS Code Extension and your issue doesn't appear to be a bug since it doesn't appear to work for you in the terminal either.

I'm running out of ideas for you, but these came to mind:
- Check your filesystem to make sure the headers are there (look at the include paths that your compiler tells you it's using)
- Did you install XCode, or run xcode-select --install?
- Did you install a different compiler you can try?  (your tasks.json references g++, but your terminal screenshots show cpp)
- It looks like you have an a.out in your folder already.  How did you get it?

**Comment by perryizgr8** [comment]
I am trying to solve the same error "#include errors detected. Please update your includePath. IntelliSense features for this translation unit will be provided by the Tag Parser.'" and "cannot open source file "iostream"".

I have followed all the suggestions in this thread and now my browse.path and includePath are same as the entries found using "g++ -Wp,-v -E -xc -x c++ /dev/null".

However, I still cannot include iostream or atomic or stdio, basically any standard header. My own headers from a sub-directory are fine. 

To be clear, mine is not a build issue (I'm using my own build system), but an intellisense issue. A peculiarity is that my code resides on a remote Ubuntu server, and I am running VS code on my Windows laptop with the Z: drive mounted to / on the server. I'd be grateful if anybody has any ideas.

Thanks.

**Comment by bobbrow** [comment]
Can you share the include path given by g++?  Is it the path on the Ubuntu server or the mapped location on Windows?  The includePath needs to match the filesystem of the OS you're working on (in this case Windows with the Z: path).

**Comment by perryizgr8** [comment]
This is the output of the g++ command on the Ubuntu machine:

`ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/5"`
`ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"`
`ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/include"`
`#include "..." search starts here:`
`#include <...> search starts here:`
 `/usr/include/c++/5`
` /usr/include/x86_64-linux-gnu/c++/5`
` /usr/include/c++/5/backward`
` /usr/lib/gcc/x86_64-linux-gnu/5/include`
` /usr/local/include`
` /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed`
` /usr/include/x86_64-linux-gnu`
` /usr/include`
`End of search list.`
`# 1 "/dev/null"`
`# 1 "<built-in>"`
`# 1 "<command-line>"`
`# 1 "/usr/include/stdc-predef.h" 1 3 4`
`# 1 "<command-line>" 2`
`# 1 "/dev/null"`

I have / mounted to drive letter Z, so my includePath looks like this:

            "includePath": [
                "z:\\usr\\include\\",
                "z:\\usr\\include\\linux\\",
                "z:\\usr\\include\\x86_64-linux-gnu\\",
                "z:\\usr\\include\\x86_64-linux-gnu\\c++\\5\\",
                "z:\\usr\\include\\x86_64-linux-gnu\\5\\include\\",
                "z:\\usr\\include\\x86_64-linux-gnu\\5\\include-fixed\\",
                "z:\\usr\\bin\\..\\lib\\gcc\\x86_64-linux-gnu\\5.4.0\\..\\..\\..\\..\\include\\c++\\5.4.0\\",
                "z:\\usr\\bin\\..\\lib\\gcc\\x86_64-linux-gnu\\5.4.0\\..\\..\\..\\..\\include\\x86_64-linux-gnu\\c++\\5.4.0\\",
                "z:\\usr\\bin\\..\\lib\\gcc\\x86_64-linux-gnu\\5.4.0\\..\\..\\..\\..\\include\\c++\\5.4.0\\backward\\",
                "z:\\usr\\include\\c++\\5\\",
                "z:\\usr\\include\\c++\\5\\backward\\",
                "z:\\usr\\local\\include\\",
                "z:\\path\\to\\my\\own\\includes\\"
            ],

As you can see, I have translated each path to the equivalent path on my Windows system. I can access the headers using these paths in Windows Explorer, so the path is correct. So even though I can open the iostream header by navigating to "z:\usr\include\x86_64-linux-gnu\c++\5\" and opening the file in any editor, VS code still shows a green squiggle below its include.

I am accessing the server over the internet, so I'm worried this might have something to do with VS code being unable to parse files that are slow to read. Is that likely to cause this problem? The fire icon in the bottom right does go away after a while (1-2 min). 

Thanks for responding.

PS: Sorry for the inconsistent formatting.

**Comment by 1st** [comment]
Hello. As @smithalexk  said above, the `C++` extension doesn't work by default. But when I've added these 3 lines (see below) - all becomes working.

```
{
            "includePath": [
                // - 1st -
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include"
                // ...
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    // - 2nd -
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include",
                    // ...
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                // - 3rd -
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks",
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
}
```

Can you please make these changes to the plugin to make people on **Mac** happy? Thank you.

**Comment by grigosback** [comment]
Hello , I'm having problems with #Includes when I'm coding in C, my c_cpp_properties.json:

{

    "configurations": [{
        "name": "Win32",
        "intelliSenseMode": "clang-x64",
        "includePath": [
            "${workspaceRoot}",
            "C:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include",
            "C:\\MinGW\\include",
            "C:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include-fixed"
        ],
        "defines": [
            "_DEBUG",
            "UNICODE",
            "__GNUC__=6",
            "__cdecl=__attribute__((__cdecl__))"
        ],
        "browse": {
            "path": [
                "C:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include",
                "C:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include-fixed",
                "C:\\MinGW\\include\\*"
            ],
            "limitSymbolsToIncludedHeaders": true,
            "databaseFilename": ""
        }
    }],
    "version": 3
}

The error I've got:

![image](https://user-images.githubusercontent.com/33532159/32635970-617ef684-c591-11e7-93bd-0a5e97521e64.png)


My 'gcc -v -E -x c' output:

```
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gcc.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
COLLECT_GCC_OPTIONS='-v' '-E' '-mtune=generic' '-march=i586'
 c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/cc1.exe -E -quiet -v -iprefix c:\mingw\bin\../lib/gcc/mingw32/6.3.0/ - -mtune=generic -march=i586
ignoring nonexistent directory "c:\mingw\bin\../lib/gcc/mingw32/6.3.0/../../../../mingw32/include"
ignoring duplicate directory "c:/mingw/lib/gcc/../../lib/gcc/mingw32/6.3.0/include"
ignoring duplicate directory "/mingw/lib/gcc/mingw32/6.3.0/../../../../include"
ignoring duplicate directory "c:/mingw/lib/gcc/../../include"
ignoring duplicate directory "c:/mingw/lib/gcc/../../lib/gcc/mingw32/6.3.0/include-fixed"
ignoring nonexistent directory "c:/mingw/lib/gcc/../../lib/gcc/mingw32/6.3.0/../../../../mingw32/include"
ignoring duplicate directory "/mingw/include"
#include "..." search starts here:
#include <...> search starts here:
 c:\mingw\bin\../lib/gcc/mingw32/6.3.0/include
 c:\mingw\bin\../lib/gcc/mingw32/6.3.0/../../../../include
 c:\mingw\bin\../lib/gcc/mingw32/6.3.0/include-fixed
End of search list.
```

My "INCLUDE" files are in c:/MinGW/include/

Thank you!

**Comment by sean-mcmanus** [comment]
@grigosback The `'stdio.h' file not found` message is not from our extension. Another user hit this same issue: https://github.com/Microsoft/vscode-cpptools/issues/1203 .

**Comment by grigosback** [comment]
That was the problem @sean-mcmanus, I don't know why I had the C/C++ Clang Command Adapter, I uninstalled it and now I don't have that message anymore. Thanks a lot!

**Comment by bobbrow** [comment]
We recently updated the way the extension searches for default includes.  This issue forked into a bunch of other issues so if we missed anything and you are still having problems, please open a new issue.

**Comment by codercodingthecode** [comment]
still does not work. but that is a way of running from it.

**Comment by bobbrow** [comment]
@andythedandyone, please open a new issue and we'll be happy to investigate.

**Comment by mohamedotnet** [comment]
@andythedandyone: kindly, go to settings.json and set `"C_Cpp.intelliSenseEngine"` from `"Default"` to 
`"Tag Parser"`

**Comment by Ladinstar** [comment]
Hello here ! I have the same problem but i use codeblocks in windows to compile. Help me please !

**Comment by sean-mcmanus** [comment]
@Ladinstar Can you provide more repro info, preferably in a new issue: https://github.com/Microsoft/vscode-cpptools/issues/new .

**Comment by Ladinstar** [comment]
thank you i have founded the solution !

**Comment by admercs** [comment]
Note to MacOS users, if you are using `gcc` version 8.1.0 (for example) from Homebrew, your MacOS configuration should look like this:

```json
{
    "name": "Mac",
    "browse": {
        "path": [
            "${workspaceRoot}"
        ],
        "limitSymbolsToIncludedHeaders": true
     },
     "includePath": [
         "${workspaceRoot}/**",
         "/usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0",
         "/usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/x86_64-apple-darwin16.7.0"
     ],
     "defines": [],
     "compilerPath": "/usr/local/Cellar/gcc/8.1.0/bin/gcc-8",
     "cStandard": "c11",
     "cppStandard": "c++17",
     "intelliSenseMode": "clang-x64"
}
```

Very simple. You do not need to include headers from XCode. Do not set  `compilerPath` to `/usr/local/bin/gcc-8`, as this is a symbolic link that may mess up IntelliSense. If you are still having issues as I did, set the following user setting in `settings.json` as others have to get around a recent issue: `"C_Cpp.intelliSenseEngine": "Tag Parser",`

**Comment by prdas31** [comment]
What include files needed to run my code using cl.exe from MSVS 2015?

I've included these folders in c_cpp_properties.json:


>  "C:/Program Files (x86)/Windows Kits/8.1/Include/shared",
>         "D:/Program Files (x86)/Microsoft Visual Studio/2017Community/VC/include",
>         "D:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/*",
>         "D:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.13.26128/include",
>         "D:/Program Files (x86)/Windows Kits/10/Include/10.0.10240.0/ucrt",
>         "D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/include",
>         "D:/Program Files (x86)/Mirucrosoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/atlmfc/include",
>         "D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/crt/src/x64",


But still I get an error while try to build:
```
> Executing task: & 'D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe' 'h:\C++ Programs\ExBox01.cpp' <

Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26128 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

ExBox01.cpp
h:\C++ Programs\ExBox01.cpp(2): fatal error C1034: iostream: no include path set
The terminal process terminated with exit code: 1
```

**Comment by sean-mcmanus** [comment]
@adam-erickson There's a crashing bug with gcc 8.1 you may be hitting (https://github.com/Microsoft/vscode-cpptools/issues/2328 ) -- our latest insider release has the fix: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.8-insiders .

@prdas31 Our extension doesn't currently support any build features -- the c_cpp_properties.json is for the IntelliSense feature and not actual compiling. For building with MSVS 2015, you may need to build from the developer command prompt that ships with VS.

**Comment by prdas31** [comment]
>  @prdas31 Our extension doesn't currently support any build features -- the c_cpp_properties.json is for the IntelliSense feature and not actual compiling. For building with MSVS 2015, you may need to build from the developer command prompt that ships with VS.

Thanks a lot for the clarification and suggestion. I now use build files to include the paths like this:

```
if exist "D:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" (
    call "D:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
) else (
    call "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
)
```
This idea is taken from an VSCODE extension called Easy C/C++ Project.

Thanks.

**Comment by leslienguyn** [comment]
[issue moved]

**Comment by bobbrow** [comment]
@leslienguyn, I moved your issue to #2582.  This issue is closed.
