### ISSUE TITLE
Handle follow up issues for Language Status Bar

### ISSUE THREAD

**Issue by Bernardin-MS** [microsoft/vscode-cpptools#10413]
- [x] "Parsing Open Files | Parsing Workspace: Paused" -> "Parsing Workspace: Paused" once file parsing finished
- [x] #10401
- [x] "Parsing Workspace" when both parsings are happening

**Comment by H-G-Hristov** [comment]
The language status isn't very visible unless you know where and what to look for.

**Comment by sean-mcmanus** [comment]
@H-G-Hristov It has a spinning arrow which seems visible to me. Are you saying it's not visible if it's not spinning?

![image](https://user-images.githubusercontent.com/19859882/217356562-6afb8382-ed28-4602-a300-75c5583a8ab6.png)

**Comment by H-G-Hristov** [comment]
> @H-G-Hristov It has a spinning arrow which seems visible to me. Are you saying it's not visible if it's not spinning?
> 
> ![image](https://user-images.githubusercontent.com/19859882/217356562-6afb8382-ed28-4602-a300-75c5583a8ab6.png)

@sean-mcmanus My initial comment was related. to the discoverability of the feature. I saw the PR and I wanted to check out the results. So unless  users know what they need to look for they may miss it. Maybe something can be improved to make it more obvious.

But now fear it stopped working is that possible: 
![Screenshot 2023-02-10 at 9 35 11](https://user-images.githubusercontent.com/47526411/218032333-8484478f-b5e9-4a69-96f6-fcaff624b451.png)
![Screenshot 2023-02-10 at 9 45 51](https://user-images.githubusercontent.com/47526411/218032565-8352ba0b-cf22-4eaf-8386-82638de9429c.png)

In the same repository I also have Swift/Objective C/Python/Shell scripts and the SwiftLint and Swift, etc extensions.

**Comment by sean-mcmanus** [comment]
@H-G-Hristov You need to set C_Cpp.experimentalFeatures to `true`; otherwise it's "random" whether you get the feature enabled or not.

**Comment by sean-mcmanus** [comment]
@H-G-Hristov In terms of discoverability, did you have some suggestion? We're using the VS Code language status bar feature that other languages like TypeScript use.

**Comment by H-G-Hristov** [comment]
> @H-G-Hristov You need to set C_Cpp.experimentalFeatures to `true`; otherwise it's "random" whether you get the feature enabled or not.

It seems setting "C_Cpp.experimentalFeatures": "enabled", disabling the Swift extension and reloading the workspace made the feature work again.



> @H-G-Hristov In terms of discoverability, did you have some suggestion? Do other language status bars do something differently than us to make it more discoverable? We're using the VS Code language status bar feature that other languages like TypeScript use.

In VS code I don't think I have observed any other language status bars. I can think of Android Studio and Visual Studio, even Xcode but I haven't used those in a long time as a use VSCode mostly.

`{}` is a bit obscure. Maybe the hover can popup automatically (with the option to disable it) when processing starts.

**Comment by bobbrow** [comment]
> `{}` is a bit obscure. Maybe the hover can popup automatically (with the option to disable it) when processing starts.

The VS Code team makes the `{}` icon "wiggle" to try to draw attention to it for status updates.  You can also pin some of the items to the status bar if you would like to keep them visible.  We'll need to iterate on feedback with the VS Code team though.  We've asked them for a few features and are looking for additional feedback from our users that we can also take back to them.
