### ISSUE TITLE
Extension always shows some C++ file specific commands in the command palette 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-cpptools#10421]
### Environment

- C/C++ Extension Version: v1.14.0 pre-released

### Bug Summary and Steps to Reproduce

1. Install extension
2. Open a non c++ file, such as a `.py` file
3. Open command plate and search `c++`

**bug**
A bunch of commands that are specific to c/c++ files are shown in the command palette. A good example is `Go to next preprocessor directive`

![Screenshot 2023-01-25 at 3 46 57 PM](https://user-images.githubusercontent.com/12821956/214719230-7ec4ddd1-beec-43b8-bd8a-5dabc42b4e74.png)

These commands should  be reviewed and any that only apply in c++ files should be hidden when not in relevant files

### Configuration and Logs

```shell
NA
```

### Additional context

These commands can be hidden by adding an `enablement` clause to the `command` contribution, or using the `menus.commandPalette` contribution

**Comment by Colengms** [comment]
It looks like the following are specific to the active file and should be hidden if the active file is not C/C++/CUDA:

```
SwitchHeaderSource
EnableErrorSquiggles
DisableErrorSquiggles
ToggleDimInactiveRegions
RestartIntelliSenseForFile
GoToNextDirectiveInGroup
GoToPrevDirectiveInGroup
CreateDeclarationOrDefinition
RunCodeAnalysisOnActiveFile
BuildAndDebugFile
BuildAndRunFile
AddDebugConfiguration
GenerateDoxygenComment
```

It looks like the following can be removed entirely:

```
ToggleIncludeFallback
TakeSurvey
```

**Comment by sean-mcmanus** [comment]
I ran across this issue while investigating the pending Extract Function commands and code actions changes in package.json.

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.1.

**Comment by michelleangela** [comment]
Fixed in release version https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2.
