### ISSUE TITLE
"Updating C/C++ dependencies" fails and "Go to Declaration" doesn't work

### ISSUE THREAD

**Issue by danielboehm2** [microsoft/vscode-cpptools#1042]
I am using:
* Windows 7
* VS Code 1.16.0
* C/C++ 0.12.3

When I start VS Code, I always get the following output:

_Updating C/C++ dependencies..._

_Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
Failed at stage: downloadPackages
Error: getaddrinfo ENOTFOUND go.microsoft.com go.microsoft.com:443
	at errnoException (dns.js:28:10)
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)_

_Finished_

And "Go to Declaration" doesn't work. Probably because of the failed update?

I have already search for a solution here and compared my settings with a colleague where it is working.
But I couldn't find a solution.

**Comment by sean-mcmanus** [comment]
Can you upgrade to 0.12.4? It looks like your internet connection is not able to use DNS to resolve go.microsoft.com into an IP address. Go to Definition and other features won't work unless the required components are downloaded/installed.

**Comment by danielboehm2** [comment]
Same problem with 0.12.4

**Comment by pieandcakes** [comment]
@danielboehm2 If you copy one of the links in the package.json in your extension folder, can you see if you are able to download the package? I'm wondering why your machine isn't able to resolve the URL.

**Comment by sean-mcmanus** [comment]
@danielboehm2 Can you tell us what country/region you're located in? This info could help us fix the issue.

**Comment by danielboehm2** [comment]
@pieandcakes Which package.json do you mean? In the cpp subfolder? And which link do you mean?
@sean-mcmanus Leonberg/Germany

**Comment by pieandcakes** [comment]
@danielboehm2 in your `C:\Users\<username>\.vscode\<cpp extension folder>\` there should be a package.json file. At the bottom of the file there are a list of components with links. If you choose one of them, see if the browser will allow you to download the file. 

Are you behind a proxy?

**Comment by danielboehm2** [comment]
Yes, I can download it with the browser.

Yes, a colleague has the same settings and there it is working.
Is it possible that any other programm blocks it? I.e. Visual Studio, LLVM...

**Comment by danielboehm2** [comment]
No further ideas?

Can I install it manually if I can download with the browser?

**Comment by sean-mcmanus** [comment]
@danielboehm2 Yeah, you can try to download/install packages manually. Let us know if you hit any problems. We didn't see any networking problems in Germany. It could be your VS Code proxy settings blocking the download.

**Comment by danielboehm2** [comment]
How can I install it? I have downloaded it. But how can I execute the files?
Do I have to copy it in a certain folder and start VS Code so that it executes automatically?

**Comment by sean-mcmanus** [comment]
Copy the files into the cpptools extension folder at: `C:\Users\USER\.vscode\extensions\ms-vscode.cpptools-VERSION`. Oh, you also should add a file called install.lock to that folder to prevent additional download attempts.

**Comment by danielboehm2** [comment]
I think it has made an update. I had to restart VS Code because of an update and afterwards the release note of the extension was open. But "Go to / Peek Declaration" still doesn't work.

**Comment by sean-mcmanus** [comment]
Did our extension update? You may need to disable auto-updating of extensions if that's happening. Is the Microsoft.VSCode.CPP.Extension.exe running? What is the size of your browse database (somewhere at C:\Users\USER\AppData\Roaming\Code\User\workspaceStorage\GUID\ms-vscode.cpptools or set via the browse.databaseFilename)?

**Comment by danielboehm2** [comment]
I assume that the extension updated because the release note was open.
When I start Microsoft.VSCode.CPP.Extension.exe in the extension folder, nothing happens, the window stays black.
In ..\workspaceStorage, there are only two empty folders (0aaf3ca454a867eed686cf52877c1fb3 and a5dc579c60f9b243cc74739f28ef48ac)

**Comment by sean-mcmanus** [comment]
Our extension typescript code is supposed to launch that process from VS Code (running it standalone won't work). Is that process in the bin folder? If you go to Help->Toggle Developer Tools you might be able to see some relevant errors. If no database file appears, then the extension is failing early on and most functionality will not work.

**Comment by danielboehm2** [comment]
Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
extensionHost.ts:384 [Extension Host] ApplicationInsights:Sender Array(1)
t._logExtensionHostMessage @ extensionHost.ts:384
extensionHost.ts:384 [Extension Host] (node:10472) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t._logExtensionHostMessage @ extensionHost.ts:384
extensionHost.ts:384 [Extension Host] ApplicationInsights:Sender [Object]
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

**Comment by danielboehm2** [comment]
How can I launch the process from VS Code?

**Comment by sean-mcmanus** [comment]
It sounds like your proxy setting are incorrect. We also download a cpptools.json file at runtime and the 407 Proxy Authentication Required message is probably from that (that file is not required to be downloaded though). The extension process is supposed to launch automatically when a C+ workspace is opened. Do you see the process being run?

**Comment by danielboehm2** [comment]
No, nothing!
What can I do against the proxy setting problem?

**Comment by sean-mcmanus** [comment]
You could try setting "http.proxyStrictSSL" to false. Also, the Microsoft.VSCode.CPP.Extension.exe is supposed to go in the extension's `bin` folder (the zip file should contain that).

**Comment by danielboehm2** [comment]
Unfortunately this didn't help.
Yes, Microsoft.VSCode.CPP.Extension.exe is unzipped in ..\.vscode\extensions\ms-vscode.cpptools-0.13.0\bin

**Comment by danielboehm2** [comment]
Setting "http.proxy" to the right value solved the problem. :)
