### ISSUE TITLE
Annoying warnings in launch.json for configs that don't apply to current platform.

### ISSUE THREAD

**Issue by hcldan** [microsoft/vscode-cpptools#10425]
### Environment

- OS and version: RHEL 9.1
- VS Code: 1.74.3
- C/C++ extension: 1.13.9
- OS and version of remote machine (if applicable): N/A
- GDB / LLDB version: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. In this environment...
2. With this config...
3. Look at problems tab
4. See warnings for platforms you are not on.

![image](https://user-images.githubusercontent.com/648319/219119736-85b283d5-d845-4de4-bac0-b3f4f89fccbf.png)

### Debugger Configurations

```shell
launch.json:


{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Attach",
        "request": "attach",
        "program": "${workspaceFolder}/target/debug/program",
        "type": "cppdbg",

        "windows": {
          "name": "(Windows) Attach",
          "type": "cppvsdbg",
          "request": "attach",
          "program": "${workspaceFolder}/target/debug/program.exe",
        },
        "linux": {
          "name": "(gdb) Attach",
          "type": "cppdbg",
          "request": "attach",
          "program": "${workspaceFolder}/target/debug/program",
          "MIMode": "gdb",
          "setupCommands": [
            {
              "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": true
            },
            {
              "description": "Set Disassembly Flavor to Intel",
              "text": "-gdb-set disassembly-flavor intel",
              "ignoreFailures": true
            }
          ],
        }
      }
    ]
}
```

### Debugger Logs

```shell
The debug type is not recognized. Make sure that you have a corresponding debug extension installed and that it is enabled.
```

**Comment by hcldan** [comment]
same thing is happening in c_cpp_properties.json for platforms I'm not on.

![image](https://user-images.githubusercontent.com/648319/215155445-1e2f7faf-ae76-4306-aa5b-783245339338.png)

**Comment by browntarik** [comment]
After further investigation, this is not a debugger or extension issue. This is a VS Code issue or by design because we do not register cppvsdbg for non-windows and VS Code itself is complaining. Please feel free to file your bug here: https://github.com/microsoft/vscode. Since it is not relevant to our extension, this issue will be closed.
