### ISSUE TITLE
Code analysis don't work when I'm typing, which affects experience and continuity

### ISSUE THREAD

**Issue by traversebitree** [microsoft/vscode-cpptools#10429]
### Environment

- OS and Version:  Windows 11 22621.1105
- VS Code Version: 1.74.3
- C/C++ Extension Version: 1.14.0
- If using SSH remote, specify OS of remote machine: No

### Bug Summary and Steps to Reproduce

Bug Summary:
Code analysis don't work when I'm typing, which affects experience and continuity.

**CMake code**:
```cmake
cmake_minimum_required(VERSION 3.25)
project(app)
enable_language(CXX)
set(CMAKE_CXX_STANDARD 23)
add_executable(main main.cpp)
```

**C++ code**:
```cpp
int main(int argc, char const *argv[])
{
    int a;
    a=1;      
    return 0;
}
```

Steps to reproduce:
1. Type codes above, warning from code analysis is shown.
![image](https://user-images.githubusercontent.com/30373236/215238402-7d1491c9-cc5e-4268-b358-dbd84144c6f0.png)
2. Typing the right code later, the warning disappears.
![gif1](https://user-images.githubusercontent.com/30373236/215238535-2a3d3c22-fb6b-467d-9bda-0c0986b927d9.gif)
3. (**Bug appears here**) But I still continue typing, and the warning always remains. The syntax error check performs ok.
![gif2](https://user-images.githubusercontent.com/30373236/215238710-6387281f-fe9b-488c-9688-8705187c541a.gif)
4. (**And bug appears here**) And even if I delete these lines, the warning still remains. The problem affects coding experience and continuity
![gif3](https://user-images.githubusercontent.com/30373236/215238915-b2289ba5-ce1b-4658-9a07-7b725b3f302a.gif)

Expected behavior:
The warning should disappear, despite the delay, but code analysis should work even if I'm typing. The plugin `clangd` doesn't have this problem, and code analysis works very quickly.

### Configuration and Logs

- Plugin configurations:
```json
    "C_Cpp.inlayHints.autoDeclarationTypes.showOnLeft": true,
    "C_Cpp.inlayHints.parameterNames.suppressWhenArgumentContainsName": true,
    "C_Cpp.inlayHints.parameterNames.hideLeadingUnderscores": false,
    "C_Cpp.inlayHints.autoDeclarationTypes.enabled": true,
    "C_Cpp.inlayHints.parameterNames.enabled": true,
    "C_Cpp.inlayHints.referenceOperator.enabled": true,
    "C_Cpp.inlayHints.referenceOperator.showSpace": true,
    "C_Cpp.intelliSenseUpdateDelay": 500,
    "C_Cpp.enhancedColorization": "enabled",
    "C_Cpp.doxygen.generateOnType": false,
    "C_Cpp.codeAnalysis.clangTidy.enabled": true,
    "C_Cpp.codeAnalysis.updateDelay": 1,
```
- No `c_cpp_properties.json`, I use CMake.

- Logs from running C/C++: Log Diagnostics
```shell
-------- Diagnostics - 2023/1/28 11:08:16
Version: 1.14.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "e:\\WorkSpace\\CPP\\CPPT028/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.22000.0",
    "compilerPath": "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "e:/workspace/cpp/cppt028"
    ],
    "compilerPath": "c:/program files/microsoft visual studio/2022/professional/vc/tools/msvc/14.34.31933/bin/hostx64/x64/cl.exe",
    "compilerArgs": [],
    "compilerFragments": [
        "/DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -MT",
        "-std:c++latest"
    ]
}
Custom configurations:
[ E:\WorkSpace\CPP\CPPT028\main.cpp ]
{
    "includePath": [],
    "defines": [],
    "compilerPath": "c:/program files/microsoft visual studio/2022/professional/vc/tools/msvc/14.34.31933/bin/hostx64/x64/cl.exe",
    "compilerArgs": [],
    "compilerFragments": [
        "/DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -MT",
        "-std:c++latest"
    ]
}
Translation Unit Mappings:
[ E:\WorkSpace\CPP\CPPT028\main.cpp ]:
    E:\WorkSpace\CPP\CPPT028\main.cpp
Translation Unit Configurations:
[ E:\WorkSpace\CPP\CPPT028\main.cpp ]:
    Process ID: 1048
    Memory Usage: 45 MB
    Compiler Path: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe
    Includes:
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\atlmfc\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\cppwinrt
    Defines:
        WIN32
        _WINDOWS
        NDEBUG
    Standard Version: ms_c++latest
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 45 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5208
```

### Other Extensions

- CMake Tools

**Comment by michelleangela** [comment]
@traversebitree 
Code analysis or Clang-Tidy will only run after a document is opened or saved. It doesn't run automatically while typing.

The description for setting `C_Cpp.codeAnalysis.clangTidy.enabled` seems to imply that code analysis will run "automatically" as in while typing. Though the automatic part refers to the related setting `C_Cpp.codeAnalysis.runAutomatically` being set to `true`.

![image](https://user-images.githubusercontent.com/38734287/215941250-5445b6d2-936d-416b-a4e5-6d8ec4610750.png)


![image](https://user-images.githubusercontent.com/38734287/215941192-7f5ee42b-f068-4044-963a-d521d54c0446.png)

**Comment by traversebitree** [comment]
@michelleangela
In fact, even if the automatic code analysis (`"C_Cpp.codeAnalysis.runAutomatically": true,`) is turned on, the problem is still.
![git1](https://user-images.githubusercontent.com/30373236/215959315-e4f5365e-0b0c-416c-b619-13b2876f86d8.gif)

**Comment by michelleangela** [comment]
Does code analysis run after saving the file? Please note that code analysis does not run automatically while typing. It only runs automatically on a file after the file is opened or the file is saved. 

The description of `C_Cpp.codeAnalysis.runAutomatically` is "if true, code analysis will run automatically on a file after the file is opened or saved".
