### ISSUE TITLE
Why isn't my variable highlighted?

### ISSUE THREAD

**Issue by Visreborn** [microsoft/vscode-cpptools#10422]
### Environment

- OS and Version: Windows 10 (21H2)
- VS Code Version: 1.74.3
- C/C++ Extension Version: 1.13.9
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary: The variables and some commands are not highlighted after i started to use git.

Expected behavior:
Highlighted commands printf and cout :
![image](https://user-images.githubusercontent.com/122996485/214758556-5029321c-b032-449c-8e72-b294c91f96ec.png)
Actual behaviror :
![image](https://user-images.githubusercontent.com/122996485/214758601-e449a7cd-3572-4bae-9c19-3b0915958066.png)

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${default}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "windows-gcc-x64"
        }
    ],
    "version": 4
}
```

### Additional context

![image](https://user-images.githubusercontent.com/122996485/214759058-2de1aeee-adec-477d-8ef5-afbdc542f2e3.png)
![image](https://user-images.githubusercontent.com/122996485/214759068-32a9c53d-62eb-4a03-8c07-f3ca8b80e201.png)

**Comment by Colengms** [comment]
Hi @Visreborn .  Does this issue resolve itself if you wait a while?

Could you set `"C_Cpp.loggingLevel": "Debug"` and provide the output of the `C/C++` output channel leading up to the repro?  Also could you run the `C/C++: Log Diagnostics` command while the repro'ing file is active.  That should tell us how/if IntelliSense is configured for that file.
