### ISSUE TITLE
DebuggerTerminal autocloses

### ISSUE THREAD

**Issue by axelvuylsteke** [microsoft/vscode-cpptools#1044]
Hello,

I am new to using VS Code and have been wondering around stackoverflow and here for some tips and tricks. I am using VS Code for C++ programming in gnome. 
When I am executing a simple program for input and output, my debuggerTerminal opens to perform the actions. However the terminal closes automatically. 

I have noticed as well there is no internal terminal usage to be used for these kind of programs. As this is in backlog?
Are there any other tips that you have for other terminals to be opened when running a program or should I be using this debuggerTerminal?

Thanks for the help already.

![selection_075](https://user-images.githubusercontent.com/24873146/30586218-8c96c0de-9d2f-11e7-92f7-a53ec3bdc8e6.png)
![selection_074](https://user-images.githubusercontent.com/24873146/30586217-8c95ef74-9d2f-11e7-9835-38afba085d80.png)
![selection_073](https://user-images.githubusercontent.com/24873146/30586219-8c9fc1a2-9d2f-11e7-8657-94dadfff6e0e.png)

**Comment by axelvuylsteke** [comment]
Found a workaround to test my programs in the terminal of VSC
g++ helloworld.cpp -o Program
./Program

**Comment by pieandcakes** [comment]
@axelvuylsteke we currently support gnome-terminal with a fallback to XTerm. With some instances of Linux, if you turn `"externalConsole": false`, the program output will show up in the debug console but you can't interact with it (such as `cin`).

**Comment by pieandcakes** [comment]
we have #390 and #515 in the backlog for supporting different terminal applications and #35 for transitioning to the debug console inside of VS Code.

**Comment by nscheer** [comment]
@pieandcakes Sorry to dig this up again - Is there some setting to prevent xterm from being closed after the debugging finishes? I'd like to see the output there, as I currently have a problem with starting a specific debug session.

**Comment by pieandcakes** [comment]
@scopev24 If you are having a problem starting a debugging session, I'd suggest two things:
* Enabling [logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) to see if debugging starts at all.
* Change `stopAtEntry` to be `true` and debugging should stop at the first possible moment. Then you can continue debugging from there.

**Comment by nscheer** [comment]
@pieandcakes Sorry for not being very specific here. Debugging using breakpoints works fine, so does using stopAtEntry.
Now I have a specific launch.json with two command line arguments for my binary that I'd like to debug.
Here something is wrong, such that the xterm closes so fast, I can not see the error output - i.e. the debugging stops immediately stating that my program exited with status 1.
If I launch the command in a separate terminal, it works fine.
So I do not see any other way other than keeping the xterm open after termination in order so see the specific error message. So the question is, is there any way to keep the xterm open - I would not mind closing it myself...

**Comment by pieandcakes** [comment]
@scopev24 We haven't implemented a way for users to keep the terminal window open.

**Comment by nscheer** [comment]
@pieandcakes Ok, thanks for your feedback!

**Comment by bobbrow** [comment]
Sure, @mrx23dot. I don't think this will be implemented.
