### ISSUE TITLE
Intellisense remains disable when enabling in profile

### ISSUE THREAD

**Issue by Nahor** [microsoft/vscode-cpptools#10446]
### Environment

- OS and Version: Windows 11
- VS Code Version: 1.74.3
- C/C++ Extension Version: 1.13.9

### Bug Summary and Steps to Reproduce

Bug Summary:
If intellisense is disabled in the default profile, it remains disabled in other profiles.

Steps to reproduce:
1. Make sure to have the default profile selected (command: "Profiles: Switch..." and select "Default") 
2. In this default profile, disable intellisense ("Intelli Sense Engine" = "disabled")
3. Create a new empty profile (command "Profiles: Create an Empty Profile...", )
4. Install the C/C++ extension
5. Reload VSCode
6. Check the C/C++ log output, notice that it says "intelliSenseEngine is disabled"

alternatively, starting at step 3:
3. Create a new profile based on the current one
4. Go to the setting and set the IntellisenseEngine to default
5. Reload VSCode
6. Notice the "disabled" message in C/C++ logs

Expected behavior:
There shouldn't be any C/C++ terminal output (or it shouldn't say anything about the engine being disabled)

### Configuration and Logs

```shell
`c_cpp_properties.json`: irrelevant

`C/C++: Log Diagnostics`: When running the command, a notification pops up saying:
> IntelliSense-related commands cannot be executed when `C_Cpp.intelliSenseEngine` is set to `disabled`.

language server logging:
> loggingLevel: Debug
> intelliSenseEngine is disabled
```

### Additional context

When checking the profile JSON file, the C_Cpp.intelliSenseEngine setting is deleted when set to "default". If I manually add the setting, then Intellisense is correctly enabled.
So it seems that when the setting is missing, the extension uses the value from the default profile instead of the default value of the extension.

**Comment by michelleangela** [comment]
@Nahor 
Thank you for reporting this issue. The settings management by profiles is controlled by VS Code. Please report this at https://github.com/microsoft/vscode/issues. 

The expected behavior seems like a current profile should not inherit settings value from a default profile.
