### ISSUE TITLE
Microsoft.VSCode.CPP.Extension.linux 0.12.4 SIGSEGV on Fedora 26 x64

### ISSUE THREAD

**Issue by pquantin** [microsoft/vscode-cpptools#1045]
Hi,
yesterday I experienced a crash when running vscode-cpptools 0.12.4 with VSCode 1.16.0 on my up-to-date Fedora 26 x64.
Here is the corresponding backtrace generated by GDB. I'm also attaching the corresponding ABRT folder.

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000061231e in code_store::a_store::get_thread_pimpl(std::__1::shared_ptr<code_store::a_store::a_thread_impl>&) ()
[Current thread is 1 (Thread 0x7fd27a7fc700 (LWP 5958))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.25-10.fc26.x86_64 libgcc-7.2.1-2.fc26.x86_64
(gdb) bt
#0  0x000000000061231e in code_store::a_store::get_thread_pimpl(std::__1::shared_ptr<code_store::a_store::a_thread_impl>&) ()
#1  0x0000000000617234 in code_store::a_store::get_file(char const*, code_store::a_file_record&) ()
#2  0x00000000005ebfff in browse_engine::query_cik_in_file(code_store::a_code_item_kind, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<code_store::a_full_code_item_record, std::__1::allocator<code_store::a_full_code_item_record> >&) ()
#3  0x00000000005eaca3 in browse_engine::parse_file(char const*) ()
#4  0x00000000005fdb40 in parser::add_files(microsoft::vc::path_utf8&, bool)::{lambda(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)#1}::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const ()
#5  0x00000000005fdada in std::__1::__function::__func<parser::add_files(microsoft::vc::path_utf8&, bool)::{lambda(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)#1}, std::__1::allocator<{lambda(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)#1}>, microsoft::vc::result_t (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#6  0x00000000005fbcba in microsoft::vc::result_t parser::process_path<microsoft::vc::recursive_directory_iterator_utf8>(microsoft::vc::path_utf8 const&, std::__1::function<microsoft::vc::result_t (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::function<microsoft::vc::result_t (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) ()
#7  0x00000000005fb248 in parser::add_files(microsoft::vc::path_utf8&, bool) ()
#8  0x00000000005e8561 in browse_engine::generate_file_list(bool, bool) ()
#9  0x00000000005ada30 in message_handler::parse_root() ()
#10 0x00000000005acdd6 in vscode::handler_base<message_handler>::main_loop()::{lambda()#3}::operator()() const ()
#11 0x00000000005acd2d in void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::{lambda()#3}> >(std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::{lambda()#3}>) ()
#12 0x00007fd28485536d in start_thread () from /lib64/libpthread.so.0
#13 0x00007fd28458dbbf in clone () from /lib64/libc.so.6

**Comment by pquantin** [comment]
As the archive is too big to be attached here, I uploaded it here: https://www.dropbox.com/s/579eccbxyz1adi8/issue1045.zip?dl=0

**Comment by sean-mcmanus** [comment]
Very few users appear to be hitting this crash. Are you able to repro it consistently or is it random? Does it only repro with certain workspaces? It's trying to do a database operation, so maybe your database is somehow corrupt. Can you try a "Reset IntelliSense Database" command?

**Comment by pquantin** [comment]
So far I faced it only once. I did a reset of the database and will monitor any new crash.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
