### ISSUE TITLE
Update documentation for C_Cpp.codeAnalysis.clangTidy.enabled setting

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#10454]
Updated:
Change documentation for `C_Cpp.codeAnalysis.clangTidy.enabled` setting by replacing "run automatically" with something like "run after ...".

**Comment by bobbrow** [comment]
We specifically called it 'runAutomatically' because it will not prevent us from having additional triggers in the future, perhaps from other code analysis providers.  I'm fine with updating the description for now, but I don't see the need to rename the setting.

What are you recommending we update the language status to say?

**Comment by sean-mcmanus** [comment]
@bobbrow This was supposed to be for updating the description for C_Cpp.codeAnalysis.clangTidy.enabled. The runAutomatically setting already shows "after it is opened or saved.", i.e. the TODO is to replace "run automatically" with something like "run automatically (after it is opened or saved)".

**Comment by bobbrow** [comment]
This was in the original message:
> rename setting

As long as we're not renaming the setting, I'm fine.

**Comment by michelleangela** [comment]
>What are you recommending we update the language status to say?

Something that would indicate code analysis will execute or run after a trigger instead of running automatically without any event.

For something generic without mentioning specific triggers, here are some quick brainstormed ideas:
- Run on trigger
- Run after event
- Run after action

Perhaps the UX team can give suggestions too.

**Comment by AlexandraKemperMS** [comment]
For the language status bar, we can just go with "Run on save" rather than automatic - it is more clear. Using "action" or "trigger" might confuse users because they have not explicitly set an action/trigger and we currently do not have a way for them to do so.
