### ISSUE TITLE
Create Declaration / Definition incorrectly adds the definition into a namespace it doesn't belong to

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10464]
test.cpp
```cpp
namespace ns {

}
```

test.h
```cpp
class foo {
public:
    foo();
};
```

1. Do Create Declaration / Definition on the foo() constructor in test.h.

Bug: It adds the foo() definition to the namespace block that it doesn't belong to (IntelliSense squiggles). The bug doesn't repro in VS -- the definition is correctly placed after the namespace block.

**Comment by michelleangela** [comment]
If there are at least 2 lines after the last function or namespace scope, then it doesn't repro.

So this is the same issue as #10500
