### ISSUE TITLE
cl.exe path not displayed in "select a compiler" quick pick

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#10462]
### Environment

- C/C++ Extension Version: 1.14.1

### Bug Summary and Steps to Reproduce

When I run the Select a Compiler command, the cl.exe instances found are coalesced into a single entry.  This is correct, but we also wanted to show the path of the default one so that the user can confirm it.  Currently, we don't show it.  The correct path should already be in the first entry returned by the language service, so we just need to display it.

![image](https://user-images.githubusercontent.com/12818240/216650736-41508add-c4a3-47a0-bfd0-3cb8e321f88c.png)

### Configuration and Logs

```shell
n/a
```

**Comment by sean-mcmanus** [comment]
@bobbrow No, that's not what we talked about...maybe you weren't in that discussion? The path is unnecessary to show since we don't query it and the compilerPath settings gets populated with jsut "cl.exe" -- same with the build tasks which don't show the path to cl.exe. And even if we showed the path, after a user upgrades their compiler, the path won't exist.

**Comment by bobbrow** [comment]
For a very long time, even as a Visual Studio user, I did not know the MSVC compiler was named cl.exe.  For the sake of our newer users, please put the path in the quick pick to help them identify that this is Visual Studio's compiler.

**Comment by bobbrow** [comment]
Everything else stays the same.  We won't use the full path for the C_Cpp.default.compilerPath setting.  It will still just be "cl.exe"

**Comment by Colengms** [comment]
@bobbrow Would it be better to display MSVC ?

**Comment by bobbrow** [comment]
It would be better to show "Visual Studio 2022" in the detail (I believe we talked about that last week), but it requires more work to get that string back up to TypeScript and there was the question as to whether we should do it for other compilers too.  For now, let's just do the path.

**Comment by bobbrow** [comment]
Though I guess "Visual Studio NNNN" will also be the path.  I suppose if you want to grab it from the path we could display that instead.

**Comment by sean-mcmanus** [comment]
@bobbrow Sure, I can add back the path -- we don't think Visual Studio NNNN will always be in the path.

**Comment by sean-mcmanus** [comment]
@bobbrow So currently it shows the full path in the quick pick, but when it's added to the default.compilerPath it only shows "cl.exe", but if no default.compilerPath is set then it generates the full path for compilerPath in compile_commands.json (as it did previously). Is that okay?

**Comment by sean-mcmanus** [comment]
> The fix looks good to me. Thank you. I don't follow what you said about compile_commands.json. When do we generate that file?

@bobbrow Oops, by "compile_commands.json" I meant "c_cpp_properties.json".

**Comment by sean-mcmanus** [comment]
@bobbrow Probably, I can look into doing that if you want.
