### ISSUE TITLE
warnings in c_cpp_properties.json

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#10465]
same thing is happening in c_cpp_properties.json for platforms I'm not on.

![image](https://user-images.githubusercontent.com/648319/215155445-1e2f7faf-ae76-4306-aa5b-783245339338.png)

_Originally posted by @hcldan in https://github.com/microsoft/vscode-cpptools/issues/10425#issuecomment-1406838884_

**Comment by browntarik** [comment]
@hcldan Could you provide more clear repro steps for getting this warning?

**Comment by hcldan** [comment]
Hey there!

Thanks for looking at this.

I had this in the other ticket... I figured it would just work if you used it:


launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Attach",
        "request": "attach",
        "program": "${workspaceFolder}/target/debug/program",
        "type": "cppdbg",

        "windows": {
          "name": "(Windows) Attach",
          "type": "cppvsdbg",
          "request": "attach",
          "program": "${workspaceFolder}/target/debug/program.exe",
        },
        "linux": {
          "name": "(gdb) Attach",
          "type": "cppdbg",
          "request": "attach",
          "program": "${workspaceFolder}/target/debug/program",
          "MIMode": "gdb",
          "setupCommands": [
            {
              "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": true
            },
            {
              "description": "Set Disassembly Flavor to Intel",
              "text": "-gdb-set disassembly-flavor intel",
              "ignoreFailures": true
            }
          ],
        }
      }
    ]
}
```

**Comment by hcldan** [comment]
So I use that one in my vscode, while I'm on linux and see warnings about stuff in the windows section:
![image](https://user-images.githubusercontent.com/648319/216718903-3c98aab1-0615-441f-8c08-2209da3ca559.png)

and here's my cpp config:
```json
{
  "configurations": [
    {
      "name": "Win32",
      "includePath": [
        "${workspaceFolder}/**",
        "F:/inc",
        "F:/inc/**"
      ],
      "forcedInclude": [
        "win64.h"
      ],
      "defines": [
        "_DEBUG",
      ],
      "windowsSdkVersion": "10.0.17763.0",
      "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
      "cStandard": "c11",
      "cppStandard": "c++11",
      "intelliSenseMode": "msvc-x64"
    },
    {
      "name": "Linux",
      "includePath": [
        "${workspaceFolder}/../notes/**"
      ],
      "defines": [
        "_DEBUG",
      ],
      "cStandard": "c11",
      "cppStandard": "c++11",
      "compilerPath": "/usr/bin/gcc"
    }
  ],
  "version": 4
}

```

**Comment by hcldan** [comment]
When I'm on linux it gives me grief about the win64.h

**Comment by sean-mcmanus** [comment]
@hcldan What is your active config when it's giving you the win64.h warning?

**Comment by hcldan** [comment]
I read somewhere that it would auto detect based on name for the platform, but just realized yesterday that I needed to activate the Linux one to get my defines right.  
 
I did not get a chance to see if it fixed the warnings, but I will update this when I get a chance to look.




 
 
Dan Dumont

E-mail:  ***@***.***





 
 
----- Original message ----- From: "Sean McManus" ***@***.***> To: "microsoft/vscode-cpptools" ***@***.***> Cc: "Dan Dumont" ***@***.***>, "Mention" ***@***.***> Subject: Re: [microsoft/vscode-cpptools] warnings in c_cpp_properties.json (Issue #10465)Date: Wed, Feb 8, 2023 9:09 PM 
 
@hcldan What is your active config when it's giving you the win64.h warning?

**Comment by sean-mcmanus** [comment]
@hcldan Your screenshot shows a squiggle in launch.json which is unrelated to the "Linux" configuration shown in your status bar. I think the launch.json squiggle is "by design" and you should just ignore the squiggle or delete the configuration. See the duplicate issue at https://github.com/microsoft/vscode-cpptools/issues/10425 .

Was there a squiggle in c_cpp_properties.json? That is the file that is sensitive to the "Linux" configuration in the status bar.

**Comment by hcldan** [comment]
@sean-mcmanus that's exactly my point though.   I am using the linux config on linux.  Why is it telling me that the other config has issues?  I'm not on windows, and I don't care about it. It's showing up in my project problems area:

![image](https://user-images.githubusercontent.com/648319/219117798-a39ac651-2b30-474c-8f02-5bcae85824a2.png)

**Comment by hcldan** [comment]
The cpp_properties config i think stopped giving warnings when I activated linux

**Comment by hcldan** [comment]
I realize this belongs in another issue now, I thought the problems were more closely related and got them confused.
This should be closed and I can go file something against vscode I guess.
