### ISSUE TITLE
Wrong tooltip in launch.json for natvisDiagnostics

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cpptools#10466]
### Environment

N/A
- OS and version:
- VS Code:
- C/C++ extension:
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

https://github.com/microsoft/vscode-cpptools/blob/2d3cac0dea96a8b973cbea95cc0a1e302c28ad31/Extension/package.json#L3512, should be c_cpp.debuggers.logging.natvisDiagnostics.description

### Debugger Configurations

```shell
N/A
```

### Debugger Logs

```shell
N/A
```

**Comment by bobbrow** [comment]
@browntarik can you fix up this typo real quick?

**Comment by bobbrow** [comment]
@browntarik 
Bug is on line 135 of `Extension/tools/OptionsSchema.json`.  Fix it there and then run `yarn generateOptionsSchema` in the terminal.  (I think that's how it works, right @WardenGnaw?)

**Comment by WardenGnaw** [comment]
> @browntarik Bug is on line 135 of `Extension/tools/OptionsSchema.json`. Fix it there and then run `yarn generateOptionsSchema` in the terminal. (I think that's how it works, right @WardenGnaw?)

Yep.
