### ISSUE TITLE
Add Ada to supported languages for debugging

### ISSUE THREAD

**Issue by AnthonyLeonardoGracio** [microsoft/vscode-cpptools#10475]
### Feature Request

Hello everyone!

I suggest to add Ada to the list of supported languages for debugging. Ada is debuggable through GDB, and modifying the extension's `package.json` file to add Ada makes everything work out of the box.

This would be very useful for us since we are developing our own VS Code extension for Ada (https://github.com/AdaCore/ada_language_server): the idea would be to bind `vscode-cpptools` as an `extensionPack` to allow users to easily debug their Ada code, with a very minimal JSON configuration.

**Comment by WardenGnaw** [comment]
I'm fine with adding this similar to how we added `Rust` in https://github.com/microsoft/vscode-cpptools/pull/9484

The caveat for Ada debugger users is that any issues we ask for the community to help investigate since this extension focuses on C/C++.

**Comment by sean-mcmanus** [comment]
@WardenGnaw There's a PR at https://github.com/microsoft/vscode-cpptools/pull/10476 .

**Comment by AnthonyLeonardoGracio** [comment]
> 

No problem @WardenGnaw, we and the whole Ada community will help when needed!

**Comment by sean-mcmanus** [comment]
@AnthonyLeonardoGracio Your fix is available with 1.14.2 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.2 .

**Comment by AnthonyLeonardoGracio** [comment]
Thank you @sean-mcmanus ! I'll try that ASAP ;)
