### ISSUE TITLE
No completions in scoped variable

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10480]
## Environment
- OS and Version: Windows 10 Pro 22H2
- VS Code Version: 1.74.3
- C/C++ Extension Version: v1.13.9

@sean-mcmanus 

files.associations
![image](https://user-images.githubusercontent.com/10773245/214785341-fa48cab3-264e-4296-bacd-a04289401607.png)

header1
![image](https://user-images.githubusercontent.com/10773245/214785408-d06d9e5b-2d24-46f4-bde4-8e3cf7c7d836.png)

header1, namespace or class, no suggestions
![image](https://user-images.githubusercontent.com/10773245/214785558-1140641f-06ca-404c-95b6-de2a3e0bdf25.png)

header2
![image](https://user-images.githubusercontent.com/10773245/214785683-bdfeeb3b-9b39-4d87-95f5-214396b7ef9d.png)

header2, direct member, able to suggest
![image](https://user-images.githubusercontent.com/10773245/214785775-fd2a5779-0e82-4b0a-9c2e-0da7f9ecdc17.png)

_Originally posted by @mhtvsSFrpHdE in https://github.com/microsoft/vscode-cpptools/issues/10305#issuecomment-1404669925_

**Comment by sean-mcmanus** [comment]
@mhtvsSFrpHdE Are you able to provide any more repro info? Such as from running the C/C++: Log Diagnostics command? Do you get any IntelliSense error squiggles or crash messages in the C/C++ logging?

**Comment by mhtvsSFrpHdE** [comment]
> @mhtvsSFrpHdE Are you able to provide any more repro info? Such as from running the C/C++: Log Diagnostics command? Do you get any IntelliSense error squiggles or crash messages in the C/C++ logging?

I'm no use cpptools anymore, sorry.
