### ISSUE TITLE
goto definition successfully but still has red squiggly lines

### ISSUE THREAD

**Issue by ShenCastle** [microsoft/vscode-cpptools#10488]
### Environment

- OS and Version: macOS Monterey 12.3
- VS Code Version: 1.69.2
- C/C++ Extension Version: 1.13.9

### Bug Summary and Steps to Reproduce

Sorry to trouble you. I use vscode to read c++ code rather than compile it, so I copy source code of third party library into 
`${workspaceFolder}/include/`. Judging from the results, including `.h` and `.cpp` successfully, but ide always show red wave lines. When I change the `"C_Cpp.intelliSenseEngine" : "Tag Parser"` the goto definition works fine but IntelliSense engine which is not context aware. I also added the `"C_Cpp.intelliSenseEngineFallback": "disabled"` in the settings file but nothing changed. I want to get rid of the red squiggly lines while keeping context aware and goto definition.

c_cpp_properties.json:
```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/include/**"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "${workspaceFolder}/include"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang++",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-x64"
        }
    ],
    "version": 4
}
```

settings.json:
```json
{
    "C_Cpp.errorSquiggles": "enabled",
    "editor.minimap.maxColumn": 40,
    "C_Cpp.intelliSenseCacheSize": 10240,
    "C_Cpp.intelliSenseMemoryLimit": 8192,
    "C_Cpp.autocomplete": "default",
    "C_Cpp.intelliSenseEngine": "Tag Parser",
    "C_Cpp.intelliSenseEngineFallback": "disabled"
}
```

### Configuration and Logs

```shell
c_cpp_properties.json and settings.json show above.
```

**Comment by sean-mcmanus** [comment]
You can set "C_Cpp.errorSquiggles": "disabled" to disable squiggles. You'll need C_Cpp.intelliSenseEngine set to "Default" in order to get context-sensitive go to definition. And keep "C_Cpp.intelliSenseEngineFallback": "disabled". Let us know if you're still having an issue.
