### ISSUE TITLE
VSCode 64 bit: Intellisense cant find symbols or include files for Arduino code. VSCode 32 bit can.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1049]
VSCode Version: 1.16.1 64 bit
OS Version: Windows 10 
Arduino IDE/tooling: 1.8.4
C/C++ extension: 0.12.4

Steps to Reproduce:
1. Install Arduino IDE (not from windows store) and  VS Code 64 bit
2. Install Arduino extension
3. edit and compile code like : https://www.arduino.cc/en/Tutorial/DigitalReadSerial 

Code compiles and runs on arduino, but intellisense complains about missing symbols (like Serial etc). 
Same problems are mentioned in : 
- https://github.com/Microsoft/vscode-cpptools/issues/743
- https://github.com/Microsoft/vscode-cpptools/issues/842

Completely uninstalled VSCode 64 bit and extensions  (also removed files in user dir and appdata dir). 
Then installed VSCode 32 bit. The 32 bit version of VSCode installation does not show the problematic behaviour using the same extensions..

**Comment by sean-mcmanus** [comment]
It sounds like in your 64-bit version the `intelliSenseEngine` setting default is being set to "Default", but in the 32-bit version it's being set to "Tag Parser". We set it randomly based on the "user", which is probably different for different installs. Does changing that setting to "Tag Parser" fix the issue for you? Changing the errorSquiggles setting to "Disabled" may also work.

**Comment by ghost** [comment]
Great idea. Will try soon and let you know.

**Comment by ghost** [comment]
Using File->Preference -> Settings

Setting in the (working) VSCode 32 bit are: 
"C_Cpp.intelliSenseEngine": "Tag Parser",
"C_Cpp.intelliSenseEngineFallback": "Enabled",

Uninstalled VSCode 32 bit (also deleted .vscode in user dir and Code dir in appdata/roaming.
Then installed VSCode 64 bit.

Now... can't reproduce the problems. So I checked the settings for the intellisense engine. They are now the same as when VSCode 32 bit was installed.

Looks like I did not remove VSCode 32 bit and its settings completely. Or I got an installation of VSCode 64 bit that has the same settings as the (working) 32 bit version, instead of the settings of the earlier (problematic) 64bit install.

After setting the User Settings to 
 "C_Cpp.intelliSenseEngine": "Default"
I got the red errorSquiggles back, but i CAN navigate to definitions like "Serial" in my Arduino code.

**Comment by sean-mcmanus** [comment]
It sounds like this is resolved then?
