### ISSUE TITLE
Include file not found

### ISSUE THREAD

**Issue by vsamy** [microsoft/vscode-cpptools#105]
Hi everyone,

So i ran into an issue when trying to include libraries like eigen or spacevecalg (https://github.com/jorisv/SpaceVecAlg). 

The include is: `#include <Eigen/Core>`

I updated the include path in c_cpp_properties.json with
`"includePath": ["/usr/include/c++/4.9.3/", "/usr/include/eigen3/"]`
The Core module is indeed installed by default in "/usr/include/eigen3/Eigen/Core". 

Same when trying to include SpaceVecAlg with `#include <SpaceVecAlg/SpaceVecAlg>`

Im using Ubuntu 14.04. I don't know whether or not it is something i have done wrong.
Thanks for the help.

**Comment by jgoshi** [comment]
This was just fixed an should appear in the next release (version 0.9.0)
