### ISSUE TITLE
extention takes too long to activate

### ISSUE THREAD

**Issue by scriptking** [microsoft/vscode-cpptools#10509]
Type: <b>Bug</b>

after opening c file, it takes too much time to activate c/c++ and related extention.

Extension version: 1.13.9
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.17-2136.314.6.3.el7uek.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 5, 4|
|Memory (System)|32.00GB (1.14GB free)|
|Process Argv|--crash-reporter-id 2f6d2125-6b6f-4614-8cb5-03baa44274d5 --crash-reporter-id 2f6d2125-6b6f-4614-8cb5-03baa44274d5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ol|
|OS|Linux x64 5.4.17-2136.314.6.3.el7uek.x86_64|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (4 x 2308)|
|Memory (System)|7.49GB (6.81GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30657576
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983
vscodeenable:30660116

```

</details>

**Comment by browntarik** [comment]
Could you provide the output from the Log Diagnostics command?
