### ISSUE TITLE
Create Declaration / Definition incorrectly adds the definition into a function

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10500]
test.h
```cpp
void func();
```

test.cpp
```cpp
int main()
{
    return 0;
}
```

Bug: It creates invalid code:

```cpp
#include "test.h"
int main()
{

    void func()
    {
    }
    return 0;
}
```

**Comment by michelleangela** [comment]
This is the same issue as https://github.com/microsoft/vscode-cpptools/issues/10464. The issue is in typescript, where there are two text edits and it calculates or adjusts the edit positions.

If there are at least 2 spaces after the last function or namespace scope, then it doesn't repro.
