### ISSUE TITLE
Not able to use C++17 features though the std is set to c++17 by default

### ISSUE THREAD

**Issue by mhdshameel** [microsoft/vscode-cpptools#10510]
### Environment

- OS and Version: Windows 10 Pro and version 21H2
- VS Code Version: 1.75.0
- C/C++ Extension Version: v1.13.9 (C/C++ version), v1.3.0 (extension pack version)

## Bug Summary:
Not able to use the following though the cpp standard is set to c++17 both from the edit configurations UI and I verified in the `c_cpp_properties.json`. I know this issue has been reported and closed earlier (https://github.com/Microsoft/vscode-cpptools/issues/1579) and the mentioned stuffs does not work for me.

```
for (auto &[type, ls] : mp)
```
I am basically trying to use the above C++17 feature of iterating through a map by specifying `[key, value]` directly instead of using any intermediate variables.

Here is the error list
![image](https://user-images.githubusercontent.com/16662695/218322722-8972163a-2f39-4bb9-8168-45d0b97f41f0.png)

I also added the `/std:c++17` to the compiler flags.

Have attached my `c_cpp_properties.json` below.

## Steps to reproduce:
1. Try to use the above code in vs code.

I checked the [faq](https://code.visualstudio.com/docs/cpp/faq-cpp#_why-do-i-see-red-squiggles-under-standard-library-types) as well and it suggests to verify the compiler path. The compiler path is right as well.

Any quick help would be appreciated as I intend to use the IDE for later cpp std stuffs as well.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64",
            "compilerArgs": []
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
You're getting build errors -- you need to set the standard version in your tasks.json file or whatever you're using to build. The c_cpp_properties.json cppStandard isn't applied to builds -- only IntelliSense.

**Comment by mhdshameel** [comment]
Thanks it worked. I had actually tried adding -std:c++17, instead of /std:c++17.

**Comment by sean-mcmanus** [comment]
Okay, but -std:c++17 and /std:c++17 should be identical for cl.exe.

**Comment by mhdshameel** [comment]
@sean-mcmanus the above compilation errors where showing when the compiler switch was -std:c++17. Even now I simply added the hyphen one along with the backslash one, I get a compiler warning saying unidentified compiler switch.

**Comment by Colengms** [comment]
> added the hyphen one along with the backslash one

@mhdshameel Can you clarify what arguments you're passing when compiling?  How are you building your code?

There are a few different ways to use the C/C++ extension to generate a build task(.json file) to compile a single file, such as via the `Tasks: Configure Default Build Task` command.  You can then modify the command line arguments it uses.  But the contents of `c_cpp_properties.json` are related only to the IntelliSense configuration.

Alternatively, if you use a build system such as CMake, the build system can be integrated into the C/C++ Extension using a configuration provider extension such as CMake Tools.  That approach allows the C/C++ Extension to ingest the command line used by your build system, to configure IntelliSense.

**Comment by mhdshameel** [comment]
@Colengms I am using the `tasks.json` file to compile the single file. Earlier I had used the `-std:c++17` and I had those compilation issues I raised the original issue. Once I added the compiler flag  `/std:c++17` to the tasks.json, it actually worked. And the switch -std:c++17 doesn't get recognized by the c++ extension, the following warning is generated.

```
cl.exe /std:c++17 -std=c++17 -I /Zi /EHsc /nologo "/Fe<output file>" "source file"
cl : Command line warning D9002 : ignoring unknown option '-std=c++17'
```

Here is the tasks.json content for your reference:
```
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: cl.exe build active file",
            "command": "cl.exe",
            "args": [
                "/std:c++17",
                "-std=c++17",
                "-I",
                "/Zi",
                "/EHsc",
                "/nologo",
                "/Fe${fileDirname}\\${fileBasenameNoExtension}.exe",
                "${file}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$msCompile"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```
Hope this clears up the confusion.
cc: @Colengms @sean-mcmanus
