### ISSUE TITLE
structure's type definition syntax highlight absence

### ISSUE THREAD

**Issue by lefedehd** [microsoft/vscode-cpptools#1051]
Environments:
Windows 7 sp1
VS Code 1.16.1
ms-vscode.cpptools, solely

issues:
/*code sample
/****************DMA CONTROL Register define *************************/
typedef struct _DMA_CHANNEL_REG
{
	volatile unsigned int DMACC0SADDR;
	volatile unsigned int DMACC0DADDR;
	volatile unsigned int DMACC0LLI;
	volatile unsigned int DMACC0CTRL;
	volatile unsigned int DMACC0CONFIG;
}DMA_CHANNEL_REG;
*/

Just like the preceeding code I pasted,  DMA_CHANNEL_REG is NOT highlighted!
But, when I hover over it, I can see its definition.

**Comment by sean-mcmanus** [comment]
I don't see any unexpected behavior. `typedef int DMA_CHANNEL_REG` gives the same colorization. What are you expecting? Also, our extension doesn't implement any C/C++ colorization -- it comes from atom/language-c, so any bug fixes would need to be filed/fixed there: https://github.com/atom/language-c/issues .

**Comment by lefedehd** [comment]
Oh, I got it. I thought that C language typedefed structure highlight was related to ms-vscode.cpptools regarding the definiton pop-up when I hover over it. I am sorry for the mistake. Thanks for your replay. I will move my question to https://github.com/atom/language-c/issues .

**Comment by lefedehd** [comment]
Find another reference but no solutions.
https://github.com/atom/language-c/issues/243

**Comment by sean-mcmanus** [comment]
We're responsible for the hover, but not any of the colorization. We're tracking this via https://github.com/Microsoft/vscode-cpptools/issues/230 .
