### ISSUE TITLE
Debugger: natvis breaks when using enum (class) template argument types when using gdb

### ISSUE THREAD

**Issue by lukas-lang** [microsoft/vscode-cpptools#10511]
### Environment

- OS and version: Ubuntu 20.04 LTS
- VS Code: 1.75.1
- C/C++ extension: 1.13.9
- GDB / LLDB version: gdb 10.2

### Bug Summary and Steps to Reproduce

Bug Summary:
This is effectively the same as #6422 (which is closed), but it seems that it still doesn't work on my machine using Ubuntu and gdb.
Setup is the same/very similar to the linked issue:
`natvis.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
    <Type Name="foo&lt;*&gt;">
        <DisplayString>{{ size=0 }}</DisplayString>
        <Expand>
        </Expand>
    </Type>
</AutoVisualizer>
```

`main.cpp`:
```cpp
enum my_enum
{
    a
};

template <my_enum E = a>
struct foo
{
    int value{2};
};

int main()
{
    foo<> f{};

    return f.value;
}
```

Other templates display the custom views as expected, so it must have something to do with the enum.

### Debugger Configurations
`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/${workspaceFolderBasename}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "externalConsole": false,
            "visualizerFile": "${workspaceFolder}/natvis.xml",
            "showDisplayString": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: make (debug)"
        }
    ]
}
```

### Debugger Logs

```shell
-
```

### Other Extensions

All other extensions were disabled

### Additional Information

I noticed that on Windows, the type of `f` is displayed as `foo<0>` when hovering over the variable in the debugger, while it is displayed as `foo<(my_enum)0>` when on Ubuntu - could that be causing the different behavior?

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
