### ISSUE TITLE
can not open source file cpp on wsl ubuntu 18.04

### ISSUE THREAD

**Issue by wyfSunflower** [microsoft/vscode-cpptools#10519]
### Environment

- OS and Version: win11 home edition 22621.1194 windwos  subsystem for linux ubuntu 18.04
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

### Bug Summary and Steps to Reproduce

Bug Summary:
it can compile and link and run ok.
include system header file ok.
but failed to include user define header file.

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/home/tusk/merlin5.0/merlin/",
                "/home/tusk/merlin5.0/merlin/**",
                "/home/tusk/merlin5.0/merlin/*",
                "${default}",
                "${workspaceFolder}/**",
                "/usr/include/c++/7/**",
                "/usr/include/x86_64-linux-gnu/c++/7/**",
                "/usr/include/c++/7/backward/**",
                "/usr/lib/gcc/x86_64-linux-gnu/7/include/**",
                "/usr/local/include/**",
                "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/**",
                "/usr/include/x86_64-linux-gnu/**",
                "/usr/include/**"
            ],
            "defines": [],
            "macFrameworkPath": [],
            // "compilerPath": "/usr/bin/clang++",
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-arm64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

**Comment by browntarik** [comment]
Thank you for submitting this issue! We are currently looking into it.

**Comment by browntarik** [comment]
It seems to be the case that you might be configuring cmake correctly. Did you try running the Cmake: Configure command?

**Comment by wyfSunflower** [comment]
> Cmake: Configure

could you please tell me how to configure cmake.
it is ok when I run `cmake  .`  and  `make -j4`
it just can  not find user define header file .

**Comment by browntarik** [comment]
Do you have the Cmake Tools extension installed?

**Comment by wyfSunflower** [comment]
it's ok when I delelte all and re create
