### ISSUE TITLE
Goto Symbol works only when databaseFilename is located in .vscode 

### ISSUE THREAD

**Issue by mrvkino** [microsoft/vscode-cpptools#1052]
I am not able to have goto symbol work when the databaseFilename is empty or located in the default location (~/Library/Application Support/Code/User/workspaceStorage/<GUID>/ms-vscode.cpptools/<any_filename.vc.db>). I usually get the not symbol found or the infinite scrollbar (parsing).

Also, if put the databaseFilename under the .vscode of my project, it only works if the file does not start with a ".".
This will not work:
```
"databaseFilename": "${workspaceRoot}/.vscode/.browse.VC.db"
```
This is the only databaseFilename that worked for me:
```
"databaseFilename": "${workspaceRoot}/.vscode/browse.VC.db"
```
This is my setup:
MacOS 10.12.6
VSCode 1.16.1
C/C++ for Visual Studio Code 0.12.4
Disabled all extension, issue still persists
My working c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/usr/local/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/usr/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                    "/usr/local/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceRoot}/.vscode/browse.VC.db"
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include",
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```

**Comment by sean-mcmanus** [comment]
I'm not able to repro the problem. Does anyone else have any ideas?

**Comment by owent** [comment]
I have the same problem.
When using "intelliSenseMode": "clang-x64" and the file not be opened yet."Goto Symbol" do not work.
```json
"browse": {
    "databaseFilename": "", 
    "path": [
        "..."
    ], 
    "limitSymbolsToIncludedHeaders": true
}, 
"includePath": ["..."]
"intelliSenseMode": "clang-x64", 
"name": "WSL", 
"defines": [
    "__linux__", 
    "__x86_64__"
]
```
When "databaseFilename" not set, "Goto Symbol" do not work for all files not opened.

**Comment by sean-mcmanus** [comment]
@owt5008137 Does setting your browse.databaseFilename fix it?

**Comment by owent** [comment]
@sean-mcmanus 
No.
Symbols in files have not been opened still can not be "Goto" by setting browse.databaseFilename.
But it works after I open and then close these files.
So, I think maybe all files not indexed have the same problem.

**Comment by sean-mcmanus** [comment]
@owt5008137 Then you're describing a different bug from the original issue. Can you file a new issue? And can you provide more repro details, such as your browse.path? It sounds like your browse.path is not set correctly. What is the behavior of the database icon in the bottom right? Does it finish parsing? Does setting limitSymbolsToIncludedHeaders to false fix it (doing that is not recommended, because it can end up processing a lot of system headers)? Can you see what the size of the database file is? Do you see any errors when you increase the C_Cpp.loggingLevel to "Information"?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
