### ISSUE TITLE
Language Status follow up for compilerPath

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#10527]
When no compiler is configured, the link for IntelliSense Status in the Language Status flyout should run the "select a compiler" command.  Alex's suggested text for the link is "Improve IntelliSense."

**Comment by sean-mcmanus** [comment]
I would prefer something like "Configure IntelliSense" over "Improve IntelliSense". Was there a reason to use "improve" instead?

**Comment by sean-mcmanus** [comment]
I don't understand. If no compiler is configured then we've selected on own. To "configure" implies "an explicit action to configure something correctly". The verb "improve" seems too generic and seems to imply that the link will enable IntelliSense to be better, faster, more accurate, etc., when it's really just "configuring" to work correctly with a particular compiler.

**Comment by bobbrow** [comment]
> If no compiler is configured then we've selected one on own.

I believe this is for the case where we would have shown the prompt to confirm our compiler selection.  If they dismiss that, we don't have a compiler at all.  We configure without it.  I'm not particular about the text here.  Please sync with @AlexandraKemperMS and come to a consensus if you would like to have different text.

**Comment by bobbrow** [comment]
This issue has been replaced by #10685
