### ISSUE TITLE
Update Images/Markdown in Getting started walkthrough

### ISSUE THREAD

**Issue by AlexandraKemperMS** [microsoft/vscode-cpptools#10537]
### Feature Request

This issue is to track what new svgs we need to release a new version of the walkthrough.

**Comment by bobbrow** [comment]
There were some uploaded to #8470.  Take a look and see if any of those are still useful.

**Comment by AlexandraKemperMS** [comment]
Items that we need: 

1. An updated Run/Debug svg that shows the play button in the top right corner. For a visual, you can reference [these docs](https://code.visualstudio.com/docs/cpp/config-msvc#_explore-intellisense). It should look like the run/debug svg in the Getting Started with Python Development walkthrough. 
2. A new svg for the customize debugging step  - this is a new section that will be added to the walkthrough. We need the svg to show the Add Debug Configuration menu item in the play button, and maybe launch.json. 

For more background, this is the text that will be associated with the debugging svg:  "Sometimes you need to customize your debug configuration (like if you need to pass args to your program at runtime). To customize debugging, select "Add Debug Configuration" from the play button dropdown. The custom debug configuration is saved in your project's launch.json file. [Learn more](https://code.visualstudio.com/docs/cpp/config-linux#_debug-helloworldcpp)"

**Comment by AlexandraKemperMS** [comment]
@daviddossett could you help with this?
