### ISSUE TITLE
"Find references" absence

### ISSUE THREAD

**Issue by lefedehd** [microsoft/vscode-cpptools#1053]
Environments:
 Windows 7 sp1
 VS Code 1.16.1
 ms-vscode.cpptools, solely

Issues:
According to VS code online documentation about "Peek" function, "We think there's nothing worse than a big context switch when all you want is to quickly check something. That's why we support peeked editors. When you execute a Find All References search (via Shift+F12), or a Peek Definition (via Alt+F12), we embed the result inline". 
It seems that "find All reference" exists and works. But when I tried it out , I failed. I can't find it in the right-click context menu nor quick-key(via Shift+F12).

Do I misunderstand it or can you add it later?

**Comment by lefedehd** [comment]
Find references.
https://github.com/Microsoft/vscode-cpptools/issues/615
https://github.com/Microsoft/vscode-cpptools/issues/404

**Comment by sean-mcmanus** [comment]
Yeah, we're still in Preview and haven't implemented Find All References yet. We're tracking this in https://github.com/Microsoft/vscode-cpptools/issues/15 .

**Comment by sean-mcmanus** [comment]
Find All References is available in 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders , but you'll need to set the C_Cpp.experimentalFeatures setting to "Enabled".
