### ISSUE TITLE
Including standard library headers doesn't work since 1.14.3

### ISSUE THREAD

**Issue by K1T3K1** [microsoft/vscode-cpptools#10531]
### Environment

- OS and Version: macOS Ventura 13.1 M1 Pro Arm64 Apple Silicon
- VS Code Version: 1.75.1
- C/C++ Extension Version: 1.14.3 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary: can't `#include <header>` from standard library on 1.14.3. Reverting to 1.13.9 fixes the problem

Expected behavior:

### Configuration and Logs

```shell
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (/Users/kpz/repositories/cpp_projects/std_lib_impl/function.h).C/C++(1696)
cannot open source file "memory"C/C++(1696)

settings.json:
    "C_Cpp.intelliSenseEngine":"default",
    "C_Cpp.clang_format_fallbackStyle": "{BasedOnStyle: Google, ColumnLimit: 0}",
    "C_Cpp.clang_format_style": "file",
    "C_Cpp.formatting": "default",
    "C_Cpp.vcFormat.newLine.beforeElse": false,
    "C_Cpp.vcFormat.space.beforeInheritanceColon": false,
    "C_Cpp.codeAnalysis.clangTidy.enabled": false,
    "C_Cpp.codeAnalysis.clangTidy.checks.enabled": [
        "clang-analyzer-*"
    ],
    "C_Cpp.codeAnalysis.clangTidy.fallbackConfig": "",
    "C_Cpp.codeAnalysis.runAutomatically": true,
    "C_Cpp.codeAnalysis.clangTidy.useBuildPath": true,
    //"C_Cpp.codeAnalysis.clangTidy.args": ["--extra-arg=--target=gcc-arm-none-eabi"],
    "C_Cpp.default.includePath": [
        "${workspaceFolder}/**",
        //"/Users/kpz/esp/esp-idf/components/**"
```

**Comment by bobbrow** [comment]
Do you use `c_cpp_properties.json` to configure IntelliSense?  If not, you'll need to run the "Select a Compiler" command to tell us which compiler you want us to emulate.  We don't automatically pick one for you anymore unless it's in your $PATH and there should have been a prompt to select one after you upgraded the extension.  This command effectively sets the `C_Cpp.default.compilerPath` setting for you.

**Comment by K1T3K1** [comment]
Adding C_Cpp.default.compilerPath in my settings.json helped me! Thank You, wish there was note on this in patch notes tho..

**Comment by bobbrow** [comment]
Also, I think we might be able to add a better error message for the failed resolution of `#include` for system headers to make it more obvious what you need to do.  I'm reopening this issue and will discuss options with the team.

**Comment by bobbrow** [comment]
The current plan is to add an additional message to the `#include` error and also add a code action (fixit) for the squiggle to run the "Select Default Compiler" command.

The include error can say something like `cannot open source file "memory". Please run the "Select Default Compiler" command to help the C/C++ extension locate your system headers`.  Check with @AlexandraKemperMS on the exact wording.

The code action can have the label like `Select a compiler to locate system headers`.
