### ISSUE TITLE
Semantic tokens for user defined literals lose information compared to plain textmate syntax tokens

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#10548]
### Environment

OS and Version: Windows 10 22H2 19045
VS Code Version: 1.75.1
C/C++ Extension Version: 1.14.3

### Bug Summary and Steps to Reproduce

Bug Summary:

Here is a user defined literal _without_ semantic highlighting

![image](https://user-images.githubusercontent.com/484784/219937314-3a4269d5-f2be-43b0-b5c6-7f356ed8ca15.png)

Here is a user defined literal _with_ semantic highlighting

![image](https://user-images.githubusercontent.com/484784/219937334-de1f8686-cb5b-4588-9887-156303f6c1f3.png)

The problem here is that `1.2_w` all gets munged together in a single semantic token, whereas it's normally multiple syntax tokens. `_w` is correctly recognized as `keyword.other.unit.user-defined.cpp` by the textmate grammar.

![image](https://user-images.githubusercontent.com/484784/219937501-023a046d-cd66-4960-9469-ad7922c6c564.png)

Once semantic highlighting is enabled it becomes one giant token. Also both the function declaration and literal are set to semantic `numberLiteral`. I don't think this makes sense on the function declaration (or definition) at all.

![image](https://user-images.githubusercontent.com/484784/219937533-bb3221e8-c5d8-439d-b7a9-d04fe890a61c.png)

The desired result here is that
* `1.2` is a standard series of `constant.numeric.decimal.cpp` tokens
* `_w` is semantic `userDefinedLiteral` and is mapped to `entity.name.function.operator.literal.cpp` or something else similar to user-defined operators.
* The function declaration is not set to `numberLiteral`. This leaves it as the default `keyword.other.operator.overload.cpp` and `entity.name.operator.custom-literal.cpp`.

### Configuration and Logs

```shell
N/A
```

**Comment by sean-mcmanus** [comment]
This is "by design". We could treat this as a request to change the design, but it's unlikely that it would be changed. This matches what VS does.
