### ISSUE TITLE
Semantic tokens for overloaded operators lose information compared to plain textmate syntax tokens

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#10549]
### Environment

OS and Version: Windows 10 22H2 19045
VS Code Version: 1.75.1
C/C++ Extension Version: 1.14.3

### Bug Summary and Steps to Reproduce

Bug Summary:

Without semantic highlighting enabled and overloaded operator has two tokens for the function name:
* `keyword.other.operator.overload.cpp` for the `operator` keyword
* `entity.name.operator.cpp` for the symbol being overloaded (`&` in the example below)

![image](https://user-images.githubusercontent.com/484784/219938225-c1698c25-17f3-4986-81ca-e0c196bef9d6.png)

With semantic highlighting enabled both tokens are combined into semantic `memberOperatorOverload` and mapped to syntax `entity.name.function.operator.member.cpp`

![image](https://user-images.githubusercontent.com/484784/219938360-4a758001-f944-4d06-b965-277b6457d413.png)

This breaks the ability to color the overload keyword separately from the specific "function name".

The desired outcome is that the semantic token only includes the `&`, or multiple tokens are emitted that can be colored independently. The example above without semantic highlighting is the desired appearance.

### Configuration and Logs

```shell
N/A
```

**Comment by sean-mcmanus** [comment]
This is "by design" and matches what VS does. It is unlikely that we would change this.
