### ISSUE TITLE
Cannot distinguish textmate scopes for built-in vs overloaded `new` and `delete` operators

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#10545]
### Environment

OS and Version: Windows 10 22H2 19045
VS Code Version: 1.75.1
C/C++ Extension Version: 1.14.3

### Bug Summary and Steps to Reproduce

Bug Summary:

All operators except `new` and `delete` have unique textmate scopes when they have been overloaded. This allows them to have different syntax highlighting that makes it clear they are custom functions and not language built-in behavior.

Notice how `operator++` is colored green for `Foo` but not for `int`.
Then notice how `new` in `new Foo` is not able to be colored green.
(Apologies for the awful colors. Github appears to have mangled the colorspace)

![image](https://user-images.githubusercontent.com/484784/219922862-3767a231-39f2-4cd6-89a3-3a029703a2ea.png)

This is the desired output

![image](https://user-images.githubusercontent.com/484784/219922967-6b73f656-f31f-4343-b98c-56a6c9bbac7a.png)

You can see here that a built-in post increment operator is classified as `keyword.operator.increment.cpp` while an overloaded operator is classified as `entity.name.function.operator.member.cpp`

![image](https://user-images.githubusercontent.com/484784/219923158-95d691a2-0268-40c1-baa3-eadbab0d4251.png)

But an analogous difference does not exist for `new` and `delete`. Both built-in and overloaded `new` is classified as `keyword.operator.new.cpp`. 

![image](https://user-images.githubusercontent.com/484784/219923209-2ea9bbd4-bf85-4d30-8690-c1b1e94377f8.png)

Built-in `new` doesn't even get a semantic type at all. Built-in `delete` does, so this is technically a second bug.

### Configuration and Logs

```shell
N/A
```

**Comment by sean-mcmanus** [comment]
Everything looks correct to me. The semantic colors should be coming from your color theme. You can change it with a setting like

```json
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "newOperator": "#FFFFFF"
        }
    }
```

![image](https://user-images.githubusercontent.com/19859882/220452417-fa80dbc9-6ef8-4088-83b6-6a5567a4a3d0.png)

**Comment by akbyrd** [comment]
Apologies, I misunderstood a couple of things.

I thought `newOperator` was being applied to all new and delete operators and was not limited to overloaded ones. It turns out that's just msvc's global new and delete implementations causing all new and delete to be considered overloaded. I suppose that's technically correct and probably what I want, even though it's going to lead to every new/delete in existed to be highlighted.
![image](https://user-images.githubusercontent.com/484784/220548260-e4956923-748a-49c5-b781-81b0a30eefd7.png)

This was compounded by the fact that when inside a template, new does not get recognized as overloaded, while delete still does. I believe this is a bug?
![image](https://user-images.githubusercontent.com/484784/220549358-a3b3befc-4062-48fc-9a9d-327c1e2eae4f.png)


My second point of confusion was that the `newOperator` semantic scope is not mapped to a textmate scope. What is the philosophy on this? Other semantic scopes such as `memberOperatorOverload` are mapped to textmate scopes, for example. I believe there's a simplicity and consistency argument to be made for mapping all semantic scopes to textmate scopes.

Thanks for clarifying.

**Comment by sean-mcmanus** [comment]
When inside a template, IntelliSense and semantic colorization may not work (see https://github.com/microsoft/vscode-cpptools/issues/1946 ).

We have some docs at https://code.visualstudio.com/docs/cpp/colorization-cpp that mention "keyword.operator.new" being a fallback TextMate scope for newOperator.

@Colengms Do you know about the semantic scope mapping to textmate scope?

**Comment by akbyrd** [comment]
I'm a little bit fuzzy on whether this is the same issue. The linked one is about the fact that error squiggles are not shown inside templates. What's interesting in this case is that intellisense is "kind of on, kind of off". I'm assuming it's on because _some_ keywords are classified. But it's not clear why other, analogous keywords are not. Particularly when they don't depend on a template parameter.

> "keyword.operator.new" being a fallback TextMate scope for newOperator
I looked through each of the mappings on the documentation page (except C++/CLI ones. I need to set up a test file for that). All of them seem to get mapped except `newOperator` and `namespace`.

Though, I'd hope `newOperator` gets mapped to something that specifically indicates it's overloaded like `keyword.operator.overload.new`. Also, delete is normally `keyword.operator.delete` and it wouldn't be ideal if it ended up being mapped to something like `keyword.operator.new`.

Side note, it looks like `member` and `member.static` in the documentation have been deprecated and replaced with `method` and `method.static`.

**Comment by sean-mcmanus** [comment]
@akbyrd Looks like our IntelliSense engine only gives us a newDelete token and not separate ones. The "keyword.operator.overload.new" scope isn't used by the grammar: https://github.com/jeff-hykin/better-cpp-syntax .

I have a PR with updated docs for the member/member.static at https://github.com/microsoft/vscode-docs/pull/6075.

**Comment by sean-mcmanus** [comment]
@akbyrd Did you want to file a VS feature request on adding a separate deleteOperator semantic token? https://developercommunity.visualstudio.com/VisualStudio/suggest ?

**Comment by akbyrd** [comment]
> "keyword.operator.overload.new" scope isn't used by the grammar

I don't believe that's a requirement. Considering vscode has default [semantic token mappings](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#predefined-textmate-scope-mappings) and there's no guarantee any of those fallback scopes are actually used by a given grammar.

The semantic knowledge is by definition greater than the lexical knowledge and therefore it's very likely to encounter cases where the grammar has no existing category for something it can't reasonably know about.

> Did you want to file a VS feature request on adding a separate deleteOperator semantic token? 

No. While it's a bummer that reusing Intellisense's tokenization washes out useful textmate scope information this particular case isn't enough of a practical problem to try to get teh behavior changed.

I do think it's worth keeping open to address `newOperator` and `namespace` not being mapped to a textmate scope at all.

**Comment by akbyrd** [comment]
This has me thinking. When mapping semantic tokens to textmate scopes is it possible to map to multiple scopes? If so, I wonder if it would be possible to map semantic tokens to the same scopes they have from the grammar with the fallback scope simply added on top. Effectively "just add the semantic info on top" without erasing/replacing the scopes from the grammar.

It will lead to a few cases where the scopes are a little weird, but because the semantic information is on top it should always be possible to highlight things correctly. With subtraction for scope selectors this would be strictly more powerful and I could implement every bit of precise highlighting I have in mind.

**Comment by sean-mcmanus** [comment]
@Colengms Can you chime in? I'm not understanding the issue around "newOperator and namespace not being mapped to a textmate scope at all." and https://github.com/microsoft/vscode-cpptools/issues/10545#issuecomment-1442850131. And should we switch to using "keyword.operator.overload.new"?

**Comment by akbyrd** [comment]
`newOperator` and `namespace` are _documented_ as being mapped to a textmate scope.
https://code.visualstudio.com/docs/cpp/colorization-cpp

I think the only "extra" thing I'm asking for is that it would be nice if it were mapped to something that still communicates that it's an overload.

**Comment by akbyrd** [comment]
Same as newOperator. It looks like it doesn't actually get mapped to a textmate scope.

![image](https://user-images.githubusercontent.com/484784/222064049-24ac6fb3-0d12-46c4-947a-5e449fb205ed.png)

It happens to be classified by the textmate grammar, but it looks like the semantic token is not actually being mapped by the extension. If the grammar happens to get it wrong it won't be colored correctly.

Compare this with enumMember.

![image](https://user-images.githubusercontent.com/484784/222064330-4d4a3339-203b-4278-8387-aedaf606d875.png)

Even though the grammar also gets it correct here, you can see that the extension maps the semantic token to a textmate scope.

**Comment by Colengms** [comment]
Hi @akbyrd .  In the first image in your last message, I see the correct semantic token and fallback textmate scopes associated with the token.  The `foreground` field refers to which of those (semantic token or one of the textmate scopes) that was found in your current VS Code Theme and was used to set the token's color/style.  In your case, it looks like your theme does not have a color/style associated with any of those, and the closest match it could find was for `source`(`.cpp`), so used the Theme's foreground color associated with that.

Could you confirm which theme you are using?  If your theme does have an associated color/style for that tokens/scopes, the issue could potentially be with VS Code and how it makes those associations.  The C/C++ extension only returns semantic token values for the document (which appear to be as expected) and a some textmate scopes to fall back to for theme color associations if the Theme does not provide one for that semantic token directly.  Choosing which color from the Theme to use, if done by VS Code itself.

**Comment by akbyrd** [comment]
Ah, the super confusing thing here is that the scopes assigned to the semantic token are not displayed unless they match something in the theme. In contrast to the normal textmate scopes which are visible even when there is no match in the theme.

That makes it hard to work on a theme because I can't see the fallback scope for a semantic token unless I happen to guess it first or it's documented on the web somewhere.

Once the fallback scope just so happens to be in the theme it shows up in the scope inspection tool
![image](https://user-images.githubusercontent.com/484784/222992487-12120e38-e842-47c0-8941-a50b34b739f5.png)

The theme is my own
https://marketplace.visualstudio.com/items?itemName=akbyrd.akbyrd-vsc-theme

You are correct that I don't have a scope for `entity.name.namespace`. I was mistakenly assuming the scope inspector would show me fallback scopes even if they had no match, the same way it works for textmate scopes.
