### ISSUE TITLE
Inaccurate textmate scope for the `throw` specifier on a function

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#10544]
### Environment

- OS and Version: Windows 10 22H2 19045
- VS Code Version: 1.75.1
- C/C++ Extension Version: 1.14.3

### Bug Summary and Steps to Reproduce

Bug Summary: The `throw` keyword receives the same textmate scopes when it's a throw expression and when it's an exception specifier on a function. These have different semantics and should receive different textmate scopes to allow them to be colored independently.

`throw` as control flow is correct:

![image](https://user-images.githubusercontent.com/484784/219921651-0d220afa-4922-474f-af17-aeb7608bedbd.png)

`throw` as a function specifier is indistinguishable from the above:

![image](https://user-images.githubusercontent.com/484784/219921667-f667964f-9f5d-4f60-89a0-1fb378cb80a4.png)

If instead it was categorized more like its sibling `noexpect` it would be more accurate and allow more precise syntax highlighting. Since `noexcept` is `keyword.operator.noexcept.cpp` I'd suggest `keyword.operator.throw.cpp`.

![image](https://user-images.githubusercontent.com/484784/219921678-ad97ac75-87a6-47c7-9cd0-63cb55be6a6e.png)

### Configuration and Logs

```shell
N/A
```

**Comment by sean-mcmanus** [comment]
The TextMake scopes come from VS Code itself, which come from https://github.com/jeff-hykin/better-cpp-syntax/issues , so you should report this bug there.
