### ISSUE TITLE
No semantic token information for `alignas` keyword

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#10546]
### Environment

OS and Version: Windows 10 22H2 19045
VS Code Version: 1.75.1
C/C++ Extension Version: 1.14.3

### Bug Summary and Steps to Reproduce

Bug Summary:

The built-in textmate grammar doesn't handle `alignas(n)` on a struct well. Note how the parentheses end up highlighted. The opening paren is actually part of the `alignas` token so there's no way to color the keyword without coloring the parens.

![image](https://user-images.githubusercontent.com/484784/219936317-578679f6-637d-4848-a928-e1ffd315ce0e.png)

This is a place we we need a little help from the extension. The extension should emit a semantic token for `alignas`.

### Configuration and Logs

```shell
N/A
```

**Comment by sean-mcmanus** [comment]
It doesn't need to be (and shouldn't be) a semantic token. The TextMake scopes come from VS Code itself, which come from https://github.com/jeff-hykin/better-cpp-syntax/issues , so you should report this bug there.

The current behavior seems fine to me and I'm not sure exactly what change you want with the lexical tokens.

**Comment by akbyrd** [comment]
> I'm not sure exactly what change you want with the lexical tokens.

The parenthesis should not be part of the token. No other keyword includes the parenthesis.

Looks like `alignas` has a bit of history.
https://github.com/jeff-hykin/better-cpp-syntax/issues/215
https://github.com/jeff-hykin/better-cpp-syntax/issues/497
https://github.com/jeff-hykin/better-cpp-syntax/issues/626
