### ISSUE TITLE
Autocomplete deletes code on the right side of the line

### ISSUE THREAD

**Issue by dortamiguel** [microsoft/vscode-cpptools#10553]
### Environment

- OS and Version:  macOS 13.2.1
- VS Code Version: 1.75.1
- C/C++ Extension Version: 1.14.3

### Bug Summary and Steps to Reproduce

Bug Summary:

When I autocomplete a param it deletes the content on the right side of the line

https://user-images.githubusercontent.com/3449006/219973582-d5ee7546-dce3-4429-ac87-4ceb96b4ca03.mp4

Steps to reproduce:
1. Copy this code
```c++
struct Something {
    int something;
};
struct Foo {
    Something first, second;
};

Foo foo;
foo.first.something;
```
2. delete `first.` and place the cursor just after `foo`
3. `command + space` or `ctrl + space (in windows)` to toggle the autocomplete menu
4. select option (see video above)

Expected behavior:

I will like the behaviour I usually get when working with typescript, where when I call the autocomplete it respects what is written on the right of the line (see video below)

https://user-images.githubusercontent.com/3449006/219973550-777a4f5c-91d1-47be-b786-3a6ea7693599.mp4

### Configuration and Logs

```shell
{
  "C_Cpp.default.cppStandard": "c++20"
}
```

**Comment by sean-mcmanus** [comment]
This is "by design". You can get the behavior you want by using
```json
    "[cpp]": {
        "editor.suggest.insertMode": "insert"
    }
```

**Comment by sean-mcmanus** [comment]
However, I'm not sure why we changed that setting to replace, so we can change it back to "insert" as the default.

**Comment by dortamiguel** [comment]
Thanks! It works fine now

**Comment by sean-mcmanus** [comment]
Yeah, we may want to update our default insertion mode though so users don't have to use that setting, not sure yet.

**Comment by Longhanks** [comment]
This issue prevails, even with `"editor.suggest.insertMode": "insert", "[cpp]": { "editor.suggest.insertMode": "insert" }`:

![actual](https://user-images.githubusercontent.com/9538837/221896188-806284f2-69f7-4ba7-b872-81c5ac34faa1.gif)

I would expect the editor with the above settings to never ever ever delete characters, e. g. expect the following outcome:

![expected](https://user-images.githubusercontent.com/9538837/221896339-a6c4b8a1-ef0a-4273-99a9-81ab58473bef.png)

**Comment by sean-mcmanus** [comment]
@Longhanks Yes, our autocomplete behavior in your example matches VS and not TypeScript, i.e. even in insert mode it may do a replace. I've moved your request to https://github.com/microsoft/vscode-cpptools/issues/10613 .
