### ISSUE TITLE
Incorrect symbols provided in some cases

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#10551]
### Environment

OS and Version: Windows 10 22H2 19045
VS Code Version: 1.75.1
C/C++ Extension Version: 1.14.3

### Bug Summary and Steps to Reproduce

Bug Summary:

Given this code:
```
#define GUARD [&]()

void Foo()
{
	auto guard = GUARD
	{
		int x = 0;
	};

	int y = 0;
}
```

The extension gets confused about `Foo`. It reports the wrong range for the function, ending it after the guard.

![image](https://user-images.githubusercontent.com/484784/219940010-3f28354a-ff6b-47f1-8905-7a2de2428b1c.png)

It then returns random lines within the function as additional symbols. Normally the extension does not return local variables within functions in the outline for a file, but it ends up returning `y` in this case.

![image](https://user-images.githubusercontent.com/484784/219940018-b91130f9-e901-42ef-9490-10c2449f67e0.png)

In more realistic files this leads to a bunch of incorrect symbols in functions where this occurs. Eventually symbol provider recovers when it reaches the next function or class in the file. This can bloat the symbol list substantially.

### Configuration and Logs

```shell
N/A
```

**Comment by sean-mcmanus** [comment]
This is a "by design" limitation with our global symbol parser which doesn't process the defines automatically -- you need to create a cpp.hint file with contents

```
#define GUARD [&]()
```
whenever a define needs to be evaluated in order to correctly lexically parse the code.
