### ISSUE TITLE
VS Code Intellisense mishandles CONDITIONAL #include if include file does not exist

### ISSUE THREAD

**Issue by davidbaril** [microsoft/vscode-cpptools#10557]
When creating a program that will be compiled on multiple platforms, you may use conditional preprocessor macros to fence off #include statements not appropriate for the current platform.
Ex: compiling on Linux, you may fence off include statements that only apply to Windows.  This conditional include will generate Intellisense info warnings if the target include file does not exist on the current platform.

I took the sample helloworld.cpp source for VS Code and added a conditional #include which demonstrates the problem. I was running VS Code with WSL2 Ubuntu 22.0ymbol4. As this is a LINUX environment, the symbol WIN32 is undefined.

```cpp
// Start of example
// the first 3 include statements should have includes of iostream, vector, and string with angle brackets.
// however the include file names do not display in this posting window.
#include <iostream> 
#include <vector>
#include <string>

// WIN32 is not defined, and the file errno.h does exist on the include paths
#ifndef WIN32
    #include <errno.h>
#endif

// WIN32 is not defined and the #include statement should NOT be be processed,
// yet Intellisense flags that the include file is not on the include path ... which is correct, but the
// #include statement should NOT have been processed.  Intellisense incorrectly displays a // // // squiggly line underneath the #include statement and shows a warning.
#ifdef WIN32
    #include "stdafx.h"
#endif

using namespace std;

int main()
{
   vector<string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};

   for (const string& word : msg)
   {
      cout << word << " ";
   }
   cout << endl;
}
```

It appears that Intellisense is always checking #include statements, even if they are inside a conditional preprocessor block that is inactive.  This is incorrect behavior.

This sample file compiles (g++ -Wall) with no errors or warnings and runs properly, yet VS Code Intellisense complains.
[hello_world_with_cond_includes.txt](https://github.com/microsoft/vscode-cpptools/files/10789881/hello_world_with_cond_includes.txt)

**Comment by sean-mcmanus** [comment]
WIN32 should not be defined on Linux and IntelliSense shouldn't be defining it. Can you run the C/C++: Log Diagnostics command from the Command Palette and look for if it shows WIN32 being defined?

**Comment by davidbaril** [comment]
Hi Sean,

 

Thank you for the prompt reply.

 

I should have mentioned it in the posting, but the issue is not related to the specific symbol WIN32.  You can change the #ifdef/#ifndef statements to any pre-processor conditional that evaluates to false … including “#if 0”, and the incorrect behavior is the same.

 

If you change the name of the include file to a file that happens to exist, the error goes away. I did not test to see if the file was present, is the file actually processed (and symbols visible).

 

I also think it is interesting to interactively position to the problem include statement, and delete the “stdafx.h” and interactively attempt to add the file name back in. You will notice that Intellisense will try to find the file as you type.  This means that Intellisense is trying to perform file name completion, even though the pre-processor condition is false.

 

The question is should Intellisense features be active within a false preprocessor conditional?  There is value in having this extra syntax checking without having the conditional be “true”, which may be difficult to generate.

 

Could a #pragma warning xxxxx statement fence off the warning?  I’m not sure.  No error number is displayed in VS code, so you can’t do error-specific masking.

 

However, I inserted the following lines:

                #pragma warning push

                #pragma warning disable

                ….. #include statement to non-present file

                #pragma warning pop

 

And the Intellisense warning went away.  This is a but coarse, but it does work FOR THIS platform.  If you were developing on a Windows platform, where the symbol WIN32 exists … and you had the “#pragma warning disable”, you would use the Intellisense warning and also the compiler warning when compiling,

 

This #pragma warning behavior also demonstrates that the #pragma warning statement IS also being processed within a false pre-processor conditional (like the #include statement is).

 

Is the root problem actually that Intellisense is ignoring pre-processor conditionals?  That would explain the #include warning and the #pragma statement changing behavior.

 

 

The log diagnostics showed nothing related to WIN32.  The output is below:

 

-------- Diagnostics - 2/21/2023, 8:55:15 PM

Version: 1.14.3

Current Configuration:

{

    "name": "Linux",

    "includePath": [

        "/home/dbaril/iotest/**"

    ],

    "defines": [],

    "cStandard": "c17",

    "cppStandard": "gnu++17",

    "intelliSenseMode": "linux-gcc-x64",

    "intelliSenseModeIsExplicit": false,

    "cStandardIsExplicit": false,

    "cppStandardIsExplicit": false,

    "mergeConfigurations": false,

    "compilerPath": "/usr/bin/gcc",

    "compilerPathIsExplicit": false,

    "browse": {

        "limitSymbolsToIncludedHeaders": true,

        "path": [

            "${workspaceFolder}/**"

        ]

    }

}

Translation Unit Mappings:

[ /home/dbaril/dave_master_doc/swdev/iotest_linux/iotest/hello_world_with_cond_includes.cpp ]:

    /home/dbaril/dave_master_doc/swdev/iotest_linux/iotest/hello_world_with_cond_includes.cpp

Translation Unit Configurations:

[ /home/dbaril/dave_master_doc/swdev/iotest_linux/iotest/hello_world_with_cond_includes.cpp ]:

    Process ID: 1257

    Memory Usage: 30 MB

    Compiler Path: /usr/bin/gcc

    Includes:

        /usr/include/c++/11

        /usr/include/x86_64-linux-gnu/c++/11

        /usr/include/c++/11/backward

        /usr/lib/gcc/x86_64-linux-gnu/11/include

        /usr/local/include

        /usr/include/x86_64-linux-gnu

        /usr/include

    Standard Version: c++17

    IntelliSense Mode: linux-gcc-x64

    Other Flags:

        --g++

        --gnu_version=110300

Total Memory Usage: 30 MB

 

------- Workspace parsing diagnostics -------

Number of files discovered (not excluded): 2668

 

 

For now, I will probably use the #pragma warning disable workaround to remove the Intellisense warnings for the actual source code.

 

Thank you for your help.

 

Dave Baril

**Comment by davidbaril** [comment]
Hi Sean,

 

Correction …. The “#pragma warning disable” does NOT completely remove the warning.  

 

One of the proposed “fixes” is to Disable error squiggles.  This removes the squiggle highlighting, but not the error.  It still shows up as an “Info” condition.

 

Dave Baril

 

From: David Baril ***@***.***> 
Sent: Tuesday, February 21, 2023 9:46 PM
To: 'microsoft/vscode-cpptools' ***@***.***>
Subject: RE: [microsoft/vscode-cpptools] VS Code Intellisense mishandles CONDITIONAL #include if include file does not exist (Issue #10557)

 

Hi Sean,

 

Thank you for the prompt reply.

 

I should have mentioned it in the posting, but the issue is not related to the specific symbol WIN32.  You can change the #ifdef/#ifndef statements to any pre-processor conditional that evaluates to false … including “#if 0”, and the incorrect behavior is the same.

 

If you change the name of the include file to a file that happens to exist, the error goes away. I did not test to see if the file was present, is the file actually processed (and symbols visible).

 

I also think it is interesting to interactively position to the problem include statement, and delete the “stdafx.h” and interactively attempt to add the file name back in. You will notice that Intellisense will try to find the file as you type.  This means that Intellisense is trying to perform file name completion, even though the pre-processor condition is false.

 

The question is should Intellisense features be active within a false preprocessor conditional?  There is value in having this extra syntax checking without having the conditional be “true”, which may be difficult to generate.

 

Could a #pragma warning xxxxx statement fence off the warning?  I’m not sure.  No error number is displayed in VS code, so you can’t do error-specific masking.

 

However, I inserted the following lines:

                #pragma warning push

                #pragma warning disable

                ….. #include statement to non-present file

                #pragma warning pop

 

And the Intellisense warning went away.  This is a but coarse, but it does work FOR THIS platform.  If you were developing on a Windows platform, where the symbol WIN32 exists … and you had the “#pragma warning disable”, you would use the Intellisense warning and also the compiler warning when compiling,

 

This #pragma warning behavior also demonstrates that the #pragma warning statement IS also being processed within a false pre-processor conditional (like the #include statement is).

 

Is the root problem actually that Intellisense is ignoring pre-processor conditionals?  That would explain the #include warning and the #pragma statement changing behavior.

 

 

The log diagnostics showed nothing related to WIN32.  The output is below:

 

-------- Diagnostics - 2/21/2023, 8:55:15 PM

Version: 1.14.3

Current Configuration:

{

    "name": "Linux",

    "includePath": [

        "/home/dbaril/iotest/**"

    ],

    "defines": [],

    "cStandard": "c17",

    "cppStandard": "gnu++17",

    "intelliSenseMode": "linux-gcc-x64",

    "intelliSenseModeIsExplicit": false,

    "cStandardIsExplicit": false,

    "cppStandardIsExplicit": false,

    "mergeConfigurations": false,

    "compilerPath": "/usr/bin/gcc",

    "compilerPathIsExplicit": false,

    "browse": {

        "limitSymbolsToIncludedHeaders": true,

        "path": [

            "${workspaceFolder}/**"

        ]

    }

}

Translation Unit Mappings:

[ /home/dbaril/dave_master_doc/swdev/iotest_linux/iotest/hello_world_with_cond_includes.cpp ]:

    /home/dbaril/dave_master_doc/swdev/iotest_linux/iotest/hello_world_with_cond_includes.cpp

Translation Unit Configurations:

[ /home/dbaril/dave_master_doc/swdev/iotest_linux/iotest/hello_world_with_cond_includes.cpp ]:

    Process ID: 1257

    Memory Usage: 30 MB

    Compiler Path: /usr/bin/gcc

    Includes:

        /usr/include/c++/11

        /usr/include/x86_64-linux-gnu/c++/11

        /usr/include/c++/11/backward

        /usr/lib/gcc/x86_64-linux-gnu/11/include

        /usr/local/include

        /usr/include/x86_64-linux-gnu

        /usr/include

    Standard Version: c++17

    IntelliSense Mode: linux-gcc-x64

    Other Flags:

        --g++

        --gnu_version=110300

Total Memory Usage: 30 MB

 

------- Workspace parsing diagnostics -------

Number of files discovered (not excluded): 2668

 

 

For now, I will probably use the #pragma warning disable workaround to remove the Intellisense warnings for the actual source code.

 

Thank you for your help.

 

Dave Baril

**Comment by sean-mcmanus** [comment]
What is the exact text of the error you're seeing related to the file not being found?

It sounds like you may be seeing the tag parser include error which should normally go away after IntelliSense is finished updating.

**Comment by davidbaril** [comment]
Here is the screen shot.  The problem is easily reproduced.

 



 

Dave

**Comment by davidbaril** [comment]
Sometimes the error is :

Include file not found in browse.path.

 



 

The “error” is legitimate, except it is not honoring the preprocessor conditional which is false.

 

Dave

 

 

 

 

 

 

From: David Baril ***@***.***> 
Sent: Tuesday, February 21, 2023 10:36 PM
To: 'microsoft/vscode-cpptools' ***@***.***>
Subject: RE: [microsoft/vscode-cpptools] VS Code Intellisense mishandles CONDITIONAL #include if include file does not exist (Issue #10557)

 

Here is the screen shot.  The problem is easily reproduced.

 



 

Dave

**Comment by sean-mcmanus** [comment]
Yes, the "Include file not found in browse.path." is coming from our "Tag Parser" engine which never evaluates the preprocessor statements. A previous related issue is at https://github.com/microsoft/vscode-cpptools/issues/5402 .

Is are your C_Cpp.intelliSenseEngine and C_Cpp.intelliSenseEngineFallback settings?

**Comment by sean-mcmanus** [comment]
Or is the include error just temporary after just opening a file, but before IntelliSense has finished initializing for the file? (that would be "by design").

**Comment by davidbaril** [comment]
Hi Sean,

The C_Cpp.intelliSenseEngine is set to default, and C_Cpp.intelliSenseEngineFallback was originally set to tags.  

I set the fallback  setting to disabled, and it appears to correct the behavior … there are no problems reported on the small hello world test source file.

 

However, my actual large c++ source file, still shows the problem.  I closed the large source window, and shut down vscode, and then restarted vscode.  The problem was still reported on the large source (which has not been modified).

 

Is there an intellisense cache that needs to be cleared or reset?  If so, how the cache clear accomplished.

 

Thank you for your help.  It looks like we’re getting close to a resolution.

 

Dave

**Comment by sean-mcmanus** [comment]
If you're seeing "Include file not found in browse.path." with a large source file that could indicate that the IntelliSense process is either taking too long to get results, is stuck, or has crashed. If you look at your C/C++ logging window you may be able to see a failure message, crash, or a results message (with C_Cpp.loggingLevel set to "Debug" you should normally see a message like "Update IntelliSense time (sec):"). If you see a cpptools-srv process using CPU and the status bar indicates IntelliSense is updating then it could just taking a long time or be stuck for some reason.

**Comment by davidbaril** [comment]
Hi Sea

Thank you for the prompt reply.

I have done some additional testing and I can confirm that the small hello world example DOES still exhibit the behavior with the problem message reported is “Include file not found in browse.path.”

 

My confusion where I saw a few cases where the error message was not displayed happened when the file (small or large) was in the editor window when I exited VSCode.  When I restarted VSCode, the previous editor window was displayed … and Intellisense was competing with all the other background startup tasks … which delayed Intellisense analysis and the resulting error message display.  If you just wait 2-5 seconds … the error is found and displayed.

 

I did some additional testing.  I found that there looks like there are 3 settings that may affect the behavior.

C_Cpp:Error Squiggles                   (enabled, disabled, enabledIncludesResolve/default)

C_Cpp:Intelli Sense Engine           (default(context-aware), Tag Parser, disabled)

C_Cpp:Intelli Sense Engine Fallback (enabled, disabled/default)

 

The settings also are available at the User, WSL(remote), and Workspace level.  In this last testing, I ensured the same values were set at all three levels. This ensured that any potential problems with setting precedence would have no effect.  Opening up the setting window in Vscode, and searching for the setting name was an easy way to isolate the setting, and tab between the 3 levels to see there respective values.  You could also open the json view of the settings … and verify that the UI was setting the value in the json file.  “Default” values were subsumed and did not appear in the json files, but correctly showed in the UI view.

 

I tried all possible combinations, exiting and restarting Vscode each time. Other than fully disabling the Intellisence engine or Error Squiggles, the include file error was always detected and the error displayed.

 

I tried “enabled” and “enabledIncludesResolve” for C_Cpp:Error Squiggles and there was NO difference.  This was surprising to me.  Reading the documentation on the Error Squiggles setting looked like there were 2 forms of “Enabled” … One that included include files not found errors, and a second were missing include files were ignored.  However …. Switching between the two enable versions did NOT change the behavior.  

 

It seems that “Enabled” (without IncludesResolve) should ignore (all) missing include file errors … but that did not happen.  I was not sure of the “polarity” of these two enabled options, so I tried them both … with no difference?  Is this a bug?

 

Is there any specially formatted source code format that can disable Intellisense for the next source code line?  Compilers have a pragma syntax to disable warnings for one line, and many linters have a similar specially formatted comment that performs a similar function.  

Is there a 1-line Intellisense disable comment??

 

Thank you for your help.

 

Regards,

 

Dave B

**Comment by sean-mcmanus** [comment]
The "Include file not found in browse.path" is from the Tag Parser and not IntelliSense and is not affected by the errorSquiggles setting. We don't have a setting to disable that message -- if you're seeing it and it doesn't go away, that means we weren't able to locate those headers in the browse.path.

If you have intelliSenseEngine set to "default" then the "Include file not found in browse.path" should disappear after it's finished initializing.

Otherwise, you can do some workaround like add a folder to your browse.path and place files in there with the names it's complaining about.
