### ISSUE TITLE
Highlighting error

### ISSUE THREAD

**Issue by aahaselgrove** [microsoft/vscode-cpptools#1055]
I have encountered a highlighting issue for the line after #define _GNU_SOURCE inside an #ifndef block.

![untitled](https://user-images.githubusercontent.com/2556805/30726483-6e79d5ee-9f8e-11e7-9c85-65458a4ef7ef.png)

[thread_pool.txt](https://github.com/Microsoft/vscode-cpptools/files/1323247/thread_pool.txt)

Windows 10 version 1703
VS Code version 1.16.0
C/C++ extension version 0.12.4

**Comment by sean-mcmanus** [comment]
The root cause is https://github.com/Microsoft/vscode-textmate/issues/40 . Our extension doesn't provide keyword colorization for C/C++. It's implemented via vscode-textmate and atom/language-c packages. They said they had a fix a few months ago, but it's still reproing.
