### ISSUE TITLE
IntelliSense not picking up cppStandard c++20 on Mac

### ISSUE THREAD

**Issue by joepdegroot** [microsoft/vscode-cpptools#10554]
### Environment

- OS and Version: macOS 13.1 (22C65) 
- VS Code Version: 1.75.1
- C/C++ Extension Version: v1.14.3

### Bug Summary and Steps to Reproduce

Bug Summary:
When creating a project using the c++20 language standard intelliSense does not recognize symbols defined in this standard such as std::numbers::pi (from the numbers header). Looking at the __cplusplus and __cpp_concepts macros, these are respectively incorrectely set to 17 and left undefined.

Work around: when setting the C_Cpp > Default: Cpp Standard to c++20 (via the @ext:ms-vscode.cpptools settings) the issue is resolved. However, I prefer not to set a global default cpp standard, since I would like to configure it on a project basis.

Steps to reproduce:
1. Create a project following the instructions in: https://code.visualstudio.com/docs/cpp/config-clang-mac
2. Set the "cppStandard" in c_cpp_properties.json to "c++20".
3. Write a statement using a c++20 expression. For example: cout << "pi=" << std::numbers::pi << '\n';
4. The project will compile and run just fine, but the numbers namespace is unknown and therefore underlined red by intelliSense.

Expected behavior:
All concepts from the c++20 standard should be recognized by intelliSense when the cppStandard is set to "c++20" in c_cpp_properties.json.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "macos-clang-arm64",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
This is because you have "configurationProvider": "ms-vscode.makefile-tools" set and so the cppStandard is getting set by that. You can verify that by running the C/C++: Log Diagnostics command with the file active and looking at the Custom configurations for a compilerArg or compilerFragment that has the -std set there.

**Comment by joepdegroot** [comment]
Thanks a lot for pointing this out. Appologies for reporting this false positive. A small addition (-std=c++20) to the makefile indeed solved the issue.
