### ISSUE TITLE
argument of type "const char *" is incompatible with parameter of type "LPCWSTR"

### ISSUE THREAD

**Issue by dortamiguel** [microsoft/vscode-cpptools#10552]
### Environment

- OS and Version:  Windows 11
- VS Code Version: 1.75.1
- C/C++ Extension Version: 1.14.3

### Bug Summary and Steps to Reproduce

Bug Summary:
I get the following error in the vscode errors `argument of type "const char *" is incompatible with parameter of type "LPCWSTR"` but when I compile it clang doesn't complains.

Steps to reproduce:
```c++
 std::string url = "my_url";
 ShellExecute(NULL, "open", url.c_str(), NULL, NULL, SW_SHOWNORMAL);
```

Expected behavior:
I don't get an error message

### Configuration and Logs
This is my vscode config:

```json
{
  "C_Cpp.default.cppStandard": "c++20"
  "C_Cpp.default.compilerPath": "C:\\Program Files\\LLVM\\bin\\clang.exe"
}
```

And my clang version is
```
clang version 15.0.7
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**Comment by sean-mcmanus** [comment]
Remove
```
                "UNICODE",
                "_UNICODE"
```
from your c_cpp_properties.json defines.

Let us know if that doesn't fix your issue.

**Comment by sean-mcmanus** [comment]
Oh, it sounds like you're not using c_cpp_properties.json -- in that case you need to add
```json
"C_Cpp.default.defines": []
```
and then Reload Window.

**Comment by dortamiguel** [comment]
thank you @sean-mcmanus that worked!
