### ISSUE TITLE
Error 'redefinition of '_OSSwapInt16' can occur when running clang-tidy on Mac arm64

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#10569]
Type: <b>Bug</b>

On opening a file I get:

`Error while processing C/C++ (clang-diagnostic-error)`

![Screenshot 2023-02-22 at 13 55 25](https://user-images.githubusercontent.com/47526411/220613576-f332f120-bacd-4e89-a45c-6ec82fa125e5.png)

Extension version: 1.14.3
VS Code version: Code 1.75.1 (Universal) (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:59.000Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 2|
|Memory (System)|16.00GB (2.05GB free)|
|Process Argv|--crash-reporter-id a7eaff19-94ae-4653-b917-d9aaab19da5d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30662993
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983
vsccsb:30662443
pythonb192:30669360

```

</details>

**Comment by sean-mcmanus** [comment]
Can you provide any more repro info?

**Comment by H-G-Hristov** [comment]
These are Apple's system headers: https://opensource.apple.com/source/xnu/xnu-344.2/libkern/libkern/OSByteOrder.h.auto.html
I don't use them directly in the project. I've seen this issue many times, I don't know where they are coming from.
I'll see if I am able to reproduce this issue in a smaller project.

**Comment by sean-mcmanus** [comment]
@H-G-Hristov Thanks -- yeah, I ran code analysis using that header on Mac arm64, but I don't get the code analysis error when using
```cpp
#include <libkern/OSByteOrder.h>
```
but I get it when using
```cpp
#define __x86_64__
#include <libkern/OSByteOrder.h>
```
So there is some define and/or include path setup that is triggering the _OSSWAPINT to be defined multiple times when it should not. You should be able to click on the error and the "previous definition is here" error to see the 2 locations where it's being defined. The fix would be for either you or us to prevent both definitions from being used (if we should be filtering out some compiler define, for example).

**Comment by H-G-Hristov** [comment]
@sean-mcmanus Here is an almost minimal project, which should reproduce the same issue:

[Archive.zip](https://github.com/microsoft/vscode-cpptools/files/10831108/Archive.zip)

![Screenshot 2023-02-25 at 14 14 59](https://user-images.githubusercontent.com/47526411/221356334-88da3d4c-bd4d-4bd5-a37f-8ffaec076cd0.png)


I added these:

```cmake
target_link_libraries(${PROJECT_NAME}
    "$<$<PLATFORM_ID:Darwin>:-framework CoreFoundation>"
    "$<$<PLATFORM_ID:Darwin>:curl>"
)
```
and in `Test.cpp`
```c++
#include <CoreFoundation/CoreFoundation.h>
```

**Comment by sean-mcmanus** [comment]
@H-G-Hristov Sure, I'll look into that issue, but why do you think it's the same issue as the other? It seems like it could be different to me since there errors are different.

**Comment by sean-mcmanus** [comment]
@H-G-Hristov It looks like that code only compiles with APPLE clang due to some extension, not sure which exactly, i.e. clang or clang-tidy that is from the LLVM repo doesn't compile this code below:

```cpp

typedef signed long CFIndex;
#define __CF_ENUM_ATTRIBUTES
#define __CF_ANON_ENUM(_type)             enum __CF_ENUM_ATTRIBUTES : _type
#define __CF_NAMED_ENUM(_type, _name)     enum __CF_ENUM_ATTRIBUTES _name : _type _name; enum _name : _type
#define __CF_ENUM_GET_MACRO(_1, _2, NAME, ...) NAME

#define CF_ENUM(...) __CF_ENUM_GET_MACRO(__VA_ARGS__, __CF_NAMED_ENUM, __CF_ANON_ENUM, )(__VA_ARGS__)

/* Values returned from comparison functions */
typedef CF_ENUM(CFIndex, CFComparisonResult) {
    kCFCompareLessThan = -1L,
    kCFCompareEqualTo = 0,
    kCFCompareGreaterThan = 1
};

int main() { return 0; }
```
and gives `error: non-defining declaration of enumeration with a fixed underlying type is only permitted as a standalone declaration; missing list of enumerators? [-Welaborated-enum-base]`.

However, it looks like adding `"C_Cpp.codeAnalysis.clangTidy.args": ["--extra-arg=-Wno-elaborated-enum-base"]` is a workaround for the issue. It seems to me like we should automatically add that.

**Comment by H-G-Hristov** [comment]
The error I see depends on the context and the includes.
I added:

```json
{
  "C_Cpp.codeAnalysis.clangTidy.args": [
    "--extra-arg=-Wno-pragma-once-outside-header",
    "--extra-arg=-Wno-elaborated-enum-base",
  ],
```
In the same file where I was previously seen the "enum" error I now see the first error "OSByteOrder".


It's not a deal breaker but at first it may be confusing and a big annoying. I have no expertise in that area but to complain about it.

Thank you for your support!

**Comment by sean-mcmanus** [comment]
Do you know what is triggering the OSByteOrder error? I'm not able to repro the issue. I think it requires certain defines. If you click on the errors that complain about redefinition you may be able to see what defines are being set to cause the 2nd definition to be hit.

**Comment by H-G-Hristov** [comment]
I am still unable to provide more info. But the issue is still there.

BTW. Is there an issue about `#pragma once` I thought it will be fixed but I can see it still. Do I need to create a FR for `#pragma once`?

**Comment by sean-mcmanus** [comment]
@H-G-Hristov Yeah, I still need more repro info to figure out why it thinks it's compiling such that OSByteOrder is defined twice.

We add "-Wno-pragma-once-outside-header" if C_Cpp.codeAnalysis.clangTidy.useBuildPath is false. Is there another issue with pragma once or do you not see that argument being added in the debug logging?

**Comment by H-G-Hristov** [comment]
Here are three logs demonstrating both issues:

1. Started VSCode and opened the project
2. Opened a H file  check for -Wno-pragma-once-outside-header - **it was there - no error**

1. Started VSCode and opened the project
3. Opened a CPP file and check for -Wno-pragma-once-outside-header - **it was there**
4. Opened the H file and the error appeared, from the log:

> LSP: cpptools/getFoldingRanges: file:///Users/hh/Projects/GitHub/n-central-agent-nix/agent/src/CommandRunner.h (id: 30)
Error while processing /Users/hh/Projects/GitHub/n-central-agent-nix/agent/src/CommandRunner.h.
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/arm/OSByteOrder.h:15:1: error: redefinition of '_OSSwapInt16' [clang-diagnostic-error]
_OSSwapInt16(
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/i386/_OSByteOrder.h:46:1: note: previous definition is here
_OSSwapInt16(
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/arm/OSByteOrder.h:25:1: error: redefinition of '_OSSwapInt32' [clang-diagnostic-error]
_OSSwapInt32(
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/i386/_OSByteOrder.h:55:1: note: previous definition is here
_OSSwapInt32(
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/arm/OSByteOrder.h:41:1: error: redefinition of '_OSSwapInt64' [clang-diagnostic-error]
_OSSwapInt64(
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/i386/_OSByteOrder.h:70:1: note: previous definition is here
_OSSwapInt64(
^
/Users/hh/Projects/GitHub/n-central-agent-nix/agent/src/CommandRunner.h:1:9: warning: #pragma once in main file [clang-diagnostic-pragma-once-outside-header]
#pragma once
        ^
/Users/hh/Projects/GitHub/n-central-agent-nix/agent/src/CommandRunner.h:8:7: warning: class 'ICommandRunner' defines a default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [hicpp-special-member-functions]
class ICommandRunner

[Archive 2.zip](https://github.com/microsoft/vscode-cpptools/files/11325066/Archive.2.zip)


![Screenshot 2023-04-25 at 20 05 42](https://user-images.githubusercontent.com/47526411/234350959-44f1cc99-b115-4835-8484-a74701dd47c3.png)
![Screenshot 2023-04-25 at 20 05 35](https://user-images.githubusercontent.com/47526411/234350963-58dd90a3-dd70-4bb4-b3eb-b428fb15fbed.png)
![Screenshot 2023-04-25 at 20 08 01](https://user-images.githubusercontent.com/47526411/234351358-49a62aed-9662-4321-8b2f-9306ef90f679.png)

**Comment by H-G-Hristov** [comment]
> Hey @sean-mcmanus, this issue might need further attention.
> 
> @H-G-Hristov, you can help us out by closing this issue if the problem no longer exists, or adding more information.

The problem still exists.

**Comment by H-G-Hristov** [comment]
There are now a few CMake improvements regarding macOS support and also the corresponding change in the extension"
https://github.com/microsoft/vscode-cmake-tools/blob/21548dcea07e7471c85c8761042ea1afc9b6cc0c/CHANGELOG.md?plain=1#L14
> IntelliSense resolves headers coming from MacOS frameworks. CMake 3.27 or later is required. [#2324](https://github.com/microsoft/vscode-cmake-tools/issues/2324)

- https://cmake.org/cmake/help/latest/release/3.27.html#file-based-api
- https://cmake.org/cmake/help/git-stage/release/index.html

Q: Are these related? Could this be the actual solution to the above issue?

I have yet to investigate.

**Comment by sean-mcmanus** [comment]
Our tests hit the "redefinition of '_OSSwapInt16'" error, but it was caused by incorrectly using the x64 clang-tidy binary on arm64 -- clang-tidy internally had defines causing it to add the i386 definitions but we were sending it arm64 system defines.
