### ISSUE TITLE
Code analysis does not cancel a paused task when starting a new task

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#10562]
Steps to reproduce:

1. Run code analysis
2. Pause code analysis
3. Start a new code analysis task
Result: the new code analysis task does not execute

![issue5](https://user-images.githubusercontent.com/38734287/220452290-8a05e158-289a-4813-a295-daa1e5cd1927.gif)

**Comment by sean-mcmanus** [comment]
I think this "by design" -- when code analysis is paused, it's supposed to stay paused until it's explicitly resumed.
