### ISSUE TITLE
Some "Code Analysis" strings need translation

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#10564]
The following commands have "code analysis" strings that are not translated. "Code analysis" should be translated. There are other strings in settings that also need translation.

**Actual:** 'Code Analysis' not translated
PTB:
 
![image](https://user-images.githubusercontent.com/38734287/220454464-b942237c-7f97-4e3f-b514-5d5cf4883415.png)

DEU:
 
![image](https://user-images.githubusercontent.com/38734287/220454471-82129055-691e-4a92-8aa2-7eda9867d854.png)

**Expected:**

CHT:
![image](https://user-images.githubusercontent.com/38734287/220454553-9fd85c34-3365-4921-92f7-9fac7510ea0f.png)

**Comment by sean-mcmanus** [comment]
I think the bug is the opposite -- "Code Analysis" should be translated. Code Analysis doesn't refer to anything specific, it's just a general term. If it referred to "clang-tidy" then it would be not translated. The only reason I could see to not translate "code analysis" is if the language doesn't really have a way to translate the concept.

**Comment by Yingzi1234** [comment]
@bobbrow @sean-mcmanus This issue hasn't been solved, we can still reproduced this issue on latest C/C++ version v1.23.0(pre-release), you can get the details below. We reopened the issue. Thank you!

PTB:
![Image](https://github.com/user-attachments/assets/24d447db-0ac1-4c61-b1aa-97070ddcad18)

DEU:
![Image](https://github.com/user-attachments/assets/1b703a24-4071-4eeb-996e-9ad2e4532679)

**Comment by bobbrow** [comment]
@Yingzi1234 this should be addressed starting in version 1.23.2

**Comment by Yingzi1234** [comment]
@bobbrow Thank you for your update! This issue has been fixed on latest C/C++ version 1.23.2(pre-release), you can get the details below. 
DEU
![Image](https://github.com/user-attachments/assets/54c2f30a-54ce-4804-a53f-9deb42e5798a)

PTB
![Image](https://github.com/user-attachments/assets/58d3d2de-3594-47db-88f2-8880d5ba4a4c)
