### ISSUE TITLE
Feature Request: Access cursor context

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#1057]
When the cursor is currently in a function (for example) the function name is displayed in the status bar.

Would it be possible to make this data available somehow, either via the snippets (which could be a vscode language extension) or maybe allowing it to be copied to the paste buffer when it is clicked (currently it opens the navigation dropdown)?

**Comment by sean-mcmanus** [comment]
Hmm...why do you want to copy that? We don't show the entire function signature (return type and other things are removed). The data is available at `"C:\Users\user\.vscode\extensions\ms-vscode.cpptools-version\out\src\LanguageServer\C_Cpp.js"` (or a similar location for Linux/Mac). You could modify that file to output the data to the output channel via replacing the first lines of the showStatusBarNavigator function with something like 
`var outputChannel;
function getOutputChannel() {
    if (outputChannel == undefined)
        outputChannel = vscode.window.createOutputChannel("C/C++");
    return outputChannel;
}
function showStatusBarNavigator() {
getOutputChannel().appendLine(currentNavigation);
...
}`
I'm not sure where the best place to expose that data would be yet.

**Comment by Gruntfuggly** [comment]
It would be useful for copying into debug statements for tracing code.

I'll have a look at that file - thanks...

**Comment by bobbrow** [comment]
Thank you for your feature request.  We are closing it because there does not appear to be enough interest from the community.  If we get more votes on this, we will reconsider and reopen the issue.
