### ISSUE TITLE
Toggle inlay hints - works in other languages

### ISSUE THREAD

**Issue by yagnasrinath** [microsoft/vscode-cpptools#10575]
### Feature Request

C/C++ extension started supporting hints inline. It would be good to support toggling them, which is already offered by some of the other language extensions.

**Comment by sean-mcmanus** [comment]
We do support toggling via settings like
```json
    "editor.inlayHints.enabled": "offUnlessPressed",
    "C_Cpp.inlayHints.autoDeclarationTypes.enabled": false,
    "C_Cpp.inlayHints.parameterNames.enabled": false
```

Can you give an example of what other toggling you are referring to?

**Comment by yagnasrinath** [comment]
Thank you for responding. Language extensions like typescript support toggle via keyboard shortcut, upon which will refresh the screen with/out inlay hints. Also, I don't see an option to show full type. The type is always shortened and only first few and last few characters are shown.

**Comment by sean-mcmanus** [comment]
Yes, off by keyboard shortcut is enabled via a setting like `"editor.inlayHints.enabled": "offUnlessPressed"` -- are you referring to something different with TypeScript?

There is no option to show the full type. You can file a new feature request on that or on VS itself, which is where we inherit the shortening behavior from: https://developercommunity.visualstudio.com/VisualStudio/suggest

**Comment by yagnasrinath** [comment]
Thank you. That is exactly what I was looking for. Will raise a request for showing full type.
