### ISSUE TITLE
I run cpp file in terminal normally but not in vscode, what's wrong?

### ISSUE THREAD

**Issue by grantsimongrant** [microsoft/vscode-cpptools#10585]
terminal: 
![image](https://user-images.githubusercontent.com/47892240/221102913-b2a1deec-7fdb-4e6c-a62b-121b3a0b7d45.png)
cpptools: 
![image](https://user-images.githubusercontent.com/47892240/221104281-0fb45cf7-796b-4386-8dec-28b2ebd97b6e.png)
my tasks.json:
![image](https://user-images.githubusercontent.com/47892240/221095093-07471efd-c8ef-4130-88cb-7e581dffdf4b.png)
Code Runner Extension:
![image](https://user-images.githubusercontent.com/47892240/221105395-92936fe9-18cc-4cf0-996a-d3aa313a9284.png)

**Comment by bobbrow** [comment]
I don't reproduce this problem on my Windows PC.  Does it still happen if you update the `"cwd"` in your `tasks.json` to `D:\\MSYS2\\mingw64\\bin`?  That's the only significant difference I see between your `tasks.json` and mine.  If the %PATH% was updated recently to include `D:\\MSYS2\\mingw64\\bin`, it's possible VS Code didn't pick that up.
