### ISSUE TITLE
C_Cpp.clang_format_formatOnSave is ignored in some cases

### ISSUE THREAD

**Issue by daltairwalter** [microsoft/vscode-cpptools#1058]
There are a few cases where format on save doesn't happen.
1. When there is high CPU utilization on my system.
2. If I open multiple documents and do a save all or search and replace throughout my project.

I am using clang-format with a custom .clang-format file.

This is happening on multiple windows operating systems.  Windows 10 and windows 7.
VS Code 1.16.1 standard release 32 and 64 bit
C/C++ addin version 0.12.4

**Comment by sean-mcmanus** [comment]
We implemented `clang_format_formatOnSave` that before VS Code exposed the editor.formatOnSave setting and there were scenarios like the SaveAll that were known to be buggy (due to limitations in the API that VS Code exposed). One thing you could try is to turn the clang_format_formatOnSave to false and the editor.formatOnSave to true -- that seems to work for me. I think we should delete the `clang_format_formatOnSave` setting. VS Code already has `	"[cpp]": {
		"editor.formatOnSave": false
	}` for overriding the global editor setting for C++, so our setting isn't needed.

**Comment by daltairwalter** [comment]
The editor.formatOnSave appears to solve the formatting problem when CPU utilization is high, but the save all situation remains.  Now that this is happening with the general VS Code editor.formatOnSave, should I report this on a different list?

Also, one of my coworkers noted that files.autoSave does not work with the more general editor.formatOnSave.  Other editor options are being looked at for this.

**Comment by sean-mcmanus** [comment]
That's strange. I'm not able to repro a problem with editor.formatOnSave set to true using Save All (it does repro with the "clang_format_formatOnSave" set to true though). What exactly is happening? Is the format not being run on the non-active file? Have you tried with just 2 files? Do you have any other C++ formatting extensions installed? Are you able to repro this issue using some other formatter, like typescript? Yeah, I remember reading that files.autoSave doesn't work with editor.formatOnSave -- I assumed it was by design. Is the format not being run on the non-active file? If you report this to VS Code, they might still blame us, because we handle the formatting -- VS Code just sends us a formatting event after the save.

**Comment by daltairwalter** [comment]
With just 2 files edited manually, Save All did work.  When I did a search and replace followed by a Save All, it did not.

**Comment by sean-mcmanus** [comment]
I did a search, replace, Save All and the 2 files got formatted. Does it require a particular number of files? Is a particular file causing an error or is it located a spot without a .clang-format at the root?

**Comment by daltairwalter** [comment]
This worked for me with 2 files and failed on my replace with 56 files - I am not sure if there is some number of files or replacements that needs to happen.  One other thing that happens frequently for me which may be related is that I get an error "Failed to save '...': A system error occurred (EBUSY: resource busy or locked, open '...').   When I get this error, the files are locked by some part of VS Code and I need to restart VS Code sometimes several times before I can save the file.

**Comment by sean-mcmanus** [comment]
What do you mean by "failed"? Does formatting work on some files and not others or do all files fail to format? Do the files that fail to format format correctly if you do a save on just the one file? The EBUSY issue is https://github.com/Microsoft/vscode-cpptools/issues/1040 , our pending update should reduce the occurrence of this (via removing a bunch of calls to stat), but we're still investigating additional bugs that may contribute to this (we're having trouble getting process monitor to log the event that is permanently locking the file).

**Comment by daltairwalter** [comment]
I did not see any of the files format correctly, I did not check all 56.  I tried individually saving 2 files after the big search and replace and they did not format.

**Comment by sean-mcmanus** [comment]
It looks like the formatting is hitting some error. Unfortunately, we haven't added code to log the clang-format errors. One way to see the errors (and/or the results clang-format returns) would be to run clang-format manually on the file, such as via `/home/user/.vscode/extensions/ms-vscode.cpptools-version/LLVM/bin/clang-format /path/file.cpp`. It may be a bug with clang-format too. What are your other "C_Cpp.clang_format_*" settings? If there's no ".clang-format" file found in a parent of the source file, it'll use the fallback formatting.

**Comment by daltairwalter** [comment]
I regularly invoke the clang-format from this path through a makefile that goes through all of the files in our project and I have never seen an error from it.  If I do this after the search and replace and save-all, it corrects all of the formatting as I would expect it too.
The only "C_Cpp.clang_format_*" setting is "C_Cpp.clang_format_style": "file" and there is a .clang-format file in the root directory of our project.

**Comment by sean-mcmanus** [comment]
If clang-format is not failing, then it means the Microsoft.VSCode.CPP.Extension.exe process is failing. Does it appear to be working in general? Does hover and Go to Definition work? What if you manually invoke a format document on the search/replaced file?

**Comment by daltairwalter** [comment]
On one computer  "Go to Definition" finds everything it should, and on another computer it doesn't.  That question is another mystery.  Both computers are exhibiting the same save behavior after the search and replace though.
I am not sure what the proper way to force a format is, but I type spaces and save and this works in general and for the search/replaced files.

**Comment by bobbrow** [comment]
Are you still having formatting issues?  In 0.16.0 we log formatting errors to the Output window in the "C/C++" log channel.  Can you check that in the cases that your formatting fails?  You can reopen this issue if you are not able to correct the problem based on the logging.

If there is no error reported in the Output window and both formatting and go to definition operations seem to be hung, then that is a different issue that we are working on fixing.

**Comment by daltairwalter** [comment]
I still see failures to format fairly regularly, but I now realize that they happen when files are being scanned for problems.  Is this the different issue that you are working on fixing?

**Comment by sean-mcmanus** [comment]
What do you mean by "failures to format"? Do you mean the format operation has no effect? If there's a red flame in the bottom right, the formatting thread could be blocked by the red flame (IntelliSense parsing). We could make it so the non-IntelliSense operations like formatting aren't blocked by IntelliSense (but IntelliSense-based operations would still be blocked).

**Comment by daltairwalter** [comment]
Yes, the format operation has no effect.  When I saw this happening today, the red flame was active.
