### ISSUE TITLE
Memory view shows empty window with only addresses.

### ISSUE THREAD

**Issue by HubKing** [microsoft/vscode-cpptools#10587]
### Environment

- OS and version: Manjaro Gnome Wayland
- VS Code: Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.1.12-1-MANJARO
Sandboxed: No
- C/C++ extension: v1.14.3
- OS and version of remote machine (if applicable):
- GDB / LLDB version: GNU gdb (GDB) 12.1

### Bug Summary and Steps to Reproduce

Bug Summary: The memory view is empty. It looks something briefly appears but soon it becomes black.

Steps to reproduce:
1. Create a C file.
2. Set a break point and run.
3. Click a variable on the left panel, and click the memory view icon
4. Empty view appears.

Also, after ending debugging, a pop-up at the bottom-right corner appears and asks about overwriting the memory.bin. This is annoying.

### Debugger Configurations

```shell
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc build active file",
            "command": "/usr/bin/gcc",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

```shell
I have no launch.json file but only tasks.json file.
```

### Additional Information

[Screencast from 2023-02-25 01-11-10.webm](https://user-images.githubusercontent.com/10900489/221231098-c7830fb5-7e48-45f9-ba47-6102766e2390.webm)

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
