### ISSUE TITLE
Can you send me the C debugger json code that will be required in launch.json? I am using in MacOS. Thanks

### ISSUE THREAD

**Issue by Parushgit** [microsoft/vscode-cpptools#1059]

**Comment by sean-mcmanus** [comment]
Maybe @pieandcakes will know more, but I just click the `Configure or fix launch.json` button and then the Add Configuration button in the bottom right if needed, and then change the `program` to the app name. Does that work for you?

**Comment by Parushgit** [comment]
Hey!

Nah, It doesn't work for me. Which option do you choose after clicking on
configure?

*Regards*
*Parush Garg*

**Comment by sean-mcmanus** [comment]
I'm using the (lldb Attach) configuration and it works for me. You need to make sure to provide the full path to the executable. What error are you getting?

**Comment by sean-mcmanus** [comment]
This is my launch.json:
![image](https://user-images.githubusercontent.com/19859882/30766471-39860c2e-9faa-11e7-8d19-5366543c9f90.png)

**Comment by Parushgit** [comment]
Yes, I am providing the path to my C code executable file. I get spawn access error.

**Comment by Parushgit** [comment]
Are you using a Mac OS platform?

**Comment by sean-mcmanus** [comment]
Yes, 10.12.6 macOS Sierra.

**Comment by sean-mcmanus** [comment]
Can you provide the exact text of the spawn access error?

**Comment by Parushgit** [comment]
I use this now which you provided in your last comment : 

{
    "version": "0.2.0",
    "configurations": [
{
    "name": "(lldb) Launch",
    "type": "cppdbg",
    "request": "launch",
    "program": "enter program name, for example ${workspaceRoot}/tcp_client_server.c",
    "args": [],
    "stopAtEntry": false,
    "cwd": "${workspaceRoot}",
    "environment": [],
    "externalConsole": true,
    "MIMode": "lldb"
}
        
    ]
}


I get Configuration gdb launch is missing in json file.

**Comment by sean-mcmanus** [comment]
Your `program` is incorrect. It needs to be the full path of the binary you want to debug.

**Comment by Parushgit** [comment]
Hey!

Thanks for your reply but I did that as well and I get one message which is "spawn access error".

{
    "version": "0.2.0",
    "configurations": [
{
    "name": "(lldb) Launch",
    "type": "cppdbg",
    "request": "launch",
    "program": "/Users/parushgarg/Desktop/SocketProgramming/tcp_client_server",
    "args": [],
    "stopAtEntry": false,
    "environment": [],
    "externalConsole": true,
    "MIMode": "lldb"
}
        
    ]
}

**Comment by sean-mcmanus** [comment]
I assume tcp_client_server is the name of the binary. Does the program launch successfully or is it crashing on launch? I'm not familiar with what a "spawn access error" could be so you may have to wait till @pieandcakes gets back Monday (he's our debugger guy).

**Comment by Parushgit** [comment]
It is not launching with debugger mode however if I run it through terminal, I am able to see the output. 
I see!

**Comment by pieandcakes** [comment]
@Parushgit The first time running the debugger, it will pop up a screen asking for elevation as the debugger needs su access in order to attach/launch another application in debug mode. Are you getting this elevation prompt? If so, you need to approve it. if you cancel that request you will get the `spawn access error` you mention.

**Comment by Parushgit** [comment]
Hi, 

Thanks for your response. No, I didn't get that prompt. Can you tell me how can I get it?

**Comment by agauniyal** [comment]
@Parushgit you should replace -
```"program": "enter program name, for example ${workspaceRoot}/tcp_client_server.c",```
with
``` "program": "${workspaceRoot}/tcp_client_server"```

and then actually create that binary by compiling your program.

**Comment by pieandcakes** [comment]
@Parushgit for me to get it, I needed to reinstall the extension. What @agauniyal says is also true. The target of your `"program"` needs to be a compiled binary, not source code. You will need to compile your source and the output of your source goes in the "`program`" field.

**Comment by Yensan** [comment]
hey, I am using vs code cpp plugin in Win/Mac, you can find all settings in my github. And I have create a task to delete output file (such as a.o  a.out)
https://github.com/Yensan/LinuxAndC/tree/master/.vscode

**Comment by WardenGnaw** [comment]
Closing issue.

Please file another issue if you have any other questions using the latest extension.

**Comment by Yura-1** [comment]
> hey, I am using vs code cpp plugin in Win/Mac, you can find all settings in my github. And I have create a task to delete output file (such as a.o a.out)
> https://github.com/Yensan/LinuxAndC/tree/master/.vscode

the link is not available anymore (((
