### ISSUE TITLE
Macro detected as function without definition

### ISSUE THREAD

**Issue by FilipNur** [microsoft/vscode-cpptools#10593]
### Environment

- OS and Version: Windows 10 Home 22H2
- VS Code Version: 1.75.1
- C/C++ Extension Version: started with 1.13.6

### Bug Summary and Steps to Reproduce

If macro with arguments is used in struct body with semicolon after it, then it is interpreted by extension as function without definition. The issue is probably connecetd with addition of "Add the ability to generate definitions from declarations and vice versa." [#664 ](https://github.com/microsoft/vscode-cpptools/issues/664)

Used macro :
![obraz](https://user-images.githubusercontent.com/48691554/221378985-328d95ff-dd80-49dc-87c9-e0fad66d943c.png)

Macro used in struct body without semicolon :
![obraz](https://user-images.githubusercontent.com/48691554/221379037-bd96de3a-c5a2-4372-9cee-def1cd037ff3.png)

Macro used in struct body with semicolon :
![obraz](https://user-images.githubusercontent.com/48691554/221379344-f845f10a-4405-4819-af02-82ff6e020e7c.png)

If this can not be fixed because of how extension detects function declaration, is there any way of disabling this feature?

### Configuration and Logs

```shell
Configuration and Logs : -
```

**Comment by sean-mcmanus** [comment]
This is "by design". You need to add `#define CONSTR(object_type) object_type(){}` to a cpp.hint file at the root of your workspace folder, reload window, and then Reset IntelliSense Database (or just edit/save the files reproing the issue).
