### ISSUE TITLE
Create declaration / definition doesn't work when there's a `#include` in the source file or the header has less than 2 code elements

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10619]
Use test1.cpp
with 
```cpp
#include <string>

int func(){}
```

Do Create Declaration / Definition on the `func`.

Bug: It creates a blank test1.h with no func declaration. The bug doesn't repro if the `#include <string>` is removed. The bug also stops reproing if 
```cpp
int iii;
int jjj;
```
is added to test1.h.

**Comment by michelleangela** [comment]
This no longer reproduces. It may have been fixed with an issue related to `editPositionAdjustment`
