### ISSUE TITLE
clang-tidy support for extended floating-point types

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10610]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/10595

<div type='discussions-op-text'>

<sup>Originally posted by **blackteahamburger** February 25, 2023</sup>
With

    "C_Cpp.default.cppStandard": "c++23",
    "C_Cpp.default.compilerPath": "/usr/bin/g++-13"

The following code:

    int main()
    {
        _Float16 f;
    }

causes `_Float16 is not supported on this target C/C++(clang-diagnostic-error)`.

However, running `clang-tidy` directly produces no warnings or errors.</div>

**Comment by sean-mcmanus** [comment]
@blackteahamburger You can use `"C_Cpp.codeAnalysis.clangTidy.args": ["--extra-arg=-msse2"]` as a workaround.

**Comment by sean-mcmanus** [comment]
The fix is available with 1.15.0 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.0

**Comment by blackteahamburger** [comment]
> The fix is available with 1.15.0 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.0

However, there is still no `_Float32`, `_Float64` or `_Float128` support.
