### ISSUE TITLE
Squigglies completely missing, everything else works.

### ISSUE THREAD

**Issue by TheFurnace** [microsoft/vscode-cpptools#1061]
Windows 10.0.16288
C/C++ extension version 3
Reproducible with no other extensions
Only reproducible on my PC, my laptop doesn't have this issue even with the same exact settings.
c_cpp_properties.json: 
![c_cpp_properties.json](https://i.imgur.com/MY4jyjs.png)
user settings:
![user settings](https://i.imgur.com/vLO4NCb.png)
example of an obvious error that should have squigglies:
![example of an obvious error that should have squigglies](https://i.imgur.com/jowwjiq.png)

I've been troubleshooting this for a while now, have read the documentation top to bottom, and have made little progress, any ideas what could cause this?

**Comment by sean-mcmanus** [comment]
What is C/C++ extensions version 3? Can you try 0.12.4? We also plan to release 0.13.0 today, unless we discover any last minute issues.

Hover over a literal number such as 0 -- does it say (int)0 as the tooltip or nothing at all or Loading.... If it says (int)0 then the "Default" IntelliSense engine is working correctly.

No squiggles can occur if the Microsoft.VSCode.CPP.IntelliSense.Msvc.exe process is crashing. Do you see that process working? Does the problem repro with a simple C++ file with no headers?

What Windows version does your laptop have? I'm not sure if we've tested with RS3 yet. You may also want to try upgrading your Windows SDK to the latest 10.0.15063 (or a newer RS3 version).

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
