### ISSUE TITLE
"C_Cpp.default.___" properties no longer inherited by other workspace folders since v1.14.3

### ISSUE THREAD

**Issue by JamesOatley** [microsoft/vscode-cpptools#10628]
### Environment

- OS and Version: 
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Create a multi-folder workspace e.g. "main.code-workspace" with two folders, in this case the main workspace folder and a separate folder called "module":

    "folders": [
        {
            "path": "../"
        },
        {
            "path": "../../../../module"
        }
    ],

Add a "default" property so that intellisense inherits the property value when editing files within the modules folder e.g.:

        "C_Cpp.default.defines": [
            "EXAMPLE_DEFINE",
         ],

Since version v1.14.3, with the workspace open, intellisense will fail to find the definition "EXAMPLE_DEFINE" for files within the "modules" folder. This applies also to "C_Cpp.default.includePath" values.

Here is an example with some include files, they exist within the directories specified within "C_Cpp.default.includePath" but are no longer found by intellisense when working on the "subscriber.c", they were found on previous versions of the extension:

![example_a](https://user-images.githubusercontent.com/54938366/222706961-4adeef4e-2534-4cf8-b23a-519a0859e4ce.png)
![example_b](https://user-images.githubusercontent.com/54938366/222707007-7f4435a7-a179-4a3d-81c4-947816c6f2cd.png)

### Configuration and Logs

```shell
c_cpp_properties.json (sensitive files removed):

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                ".",
                "../../../sdk/SDK_2_12_1_EVK-MCIMX7ULP/rtos/freertos/freertos_kernel/include/**",
                "../../../sdk/SDK_2_12_1_EVK-MCIMX7ULP/rtos/freertos/freertos_kernel/portable/GCC/ARM_CM4F",
            ],
            "defines": [
                "EXAMPLE_DEFINE",
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "${env:ARMGCC_DIR}/bin/arm-none-eabi-gcc.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-arm"
        }
    ],
    "version": 4
}
```

### Other Extensions

Plastic SCM (issue still occurs without use of this extension)

**Comment by browntarik** [comment]
Thanks for submitting this issue! We are currently looking into it.

**Comment by Colengms** [comment]
Hi @JamesOatleyCirrus .  I'm not sure I fully understand how to reproduce the issue.  I see in the `c_cpp_properties.json` you provided that `EXAMPLE_DEFINE` is specified there.  That should definitely result in that define being present in that particular workspace folder.  Is that not what you're seeing?

> Add a "default" property so that intellisense inherits the property value when editing files within the modules folder

Could you clarify where you are adding this setting?  If you are adding it to your user-level `settings.json` or under a `settings` node in the workspace file itself, this should apply to all folders in your workspace.  This appears to be working properly for me with 1.14.4.  If this isn't working for you, could you perhaps create a self-contained repro to share with us?  (I don't see any reference to this define in the images you posted.)

If you're expecting settings specific to workspace A to also apply to workspace B if it happens to be a subfolder of workspace A, I don't believe that is something we specifically support.  I believe we recently addressed an issue in which settings for the first workspace folder were always being incorrectly applied to all other workspace folders.  Perhaps you had been relying on this unintended behavior?  If so, perhaps we could use this issue as a feature request for something that might better address your scenario.

**Comment by JamesOatleyCirrus** [comment]
Hi @Colengms, thank you for the response.

I have created a bare-minimum project to recreate the issue I am seeing, which does in fact slightly differ from what I was trying to explain before:

https://bitbucket.org/jamesoatley/bug/src/master/

If you flick between v1.14.3 and older versions you will see the red squiggle underline appear underneath `#include "dog.h"` on the newer version.

The issue I have is that on versions of the plugin older than v1.14.3 the **relative** directories specified within `main.code-workspace` were **resolved** with respect to the root directory of the local project.

In new versions of the plugin the **relative** directories specified within `main.code-workspace` are **resolved** with respect to each workspace folder.

This new behaviour makes `C_Cpp.default.includePath` less useful as the relative directories must now resolve correctly for each workspace folder.

**Comment by Colengms** [comment]
Hi @JamesOatleyCirrus .

Internally, when the extension retrieves a setting value, the effective value could arise due to a setting in the global user-specific `settings.json`, a workspace folder-specific `settings.json`, the workspace file, or in a location specific to a remote session.  VS Code applies a priority order to these locations (and considers each setting's individual [settings 'scope'](https://code.visualstudio.com/api/references/contribution-points)) and delivers an effective setting value to the extension.  As you've seen, we're currently interpreting relative paths in setting values as relative to the workspace folder in which they are being evaluated.  Potentially, we could determine which of those `settings.json` files the effective value has arisen from, and interpret paths are relative to that location, but that doesn't necessarily seem like a better behavior (and wouldn't address the scenario you're describing).

If you'd prefer not to use absolutely paths in settings in your workspace file, have you considered varying the paths using environment variable expansion, such as `${env:<environment variable name>}` ?

Perhaps we could use this issue as a feature request to track adding support for variable expansions for index-specific workspaces folders in a multi-root workspace?  Perhaps `${workspaceFolder:1}`, `${workspaceFolder:2}` ?

**Comment by sean-mcmanus** [comment]
@JamesOatleyCirrus You should be able to set
```json
        "C_Cpp.default.includePath": [
            "${workspaceFolder:main_project}",
            "${workspaceFolder:main_project}/../library",
	    "${workspaceFolder:main_project}/../compiler_toolchain"
        ],
```
to get the previous behavior. The current behavior is intentional and the previous behavior was a bug.

**Comment by Colengms** [comment]
That syntax is documented here: https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder

**Comment by JamesOatleyCirrus** [comment]
Thank you @Colengms @sean-mcmanus .
