### ISSUE TITLE
VSCode C/C++ Extension(ms-vscode.cpptools) can be cached?

### ISSUE THREAD

**Issue by wlya** [microsoft/vscode-cpptools#1062]
As my usage, I usually open 2 or more Linux Kernel Source projects in vscode, it's very huge.
When I open vscode, ms-vscode.cpptools will auto start preparation of C/C++ IntelliSense, such as symbol search ing, goto defination and so on.
But as I say, the project of kernel source code is very huge and ms-vscode.cpptools will take a lot of time to finish. Every time I open vscode, this preparation job will run again and take a lot of time.
I'm thinking that ms-vscode.cpptools should add cache support for a project.

**Comment by sean-mcmanus** [comment]
We store the symbols in a database, but we still need to search through the browse.path to see if there's any new/old files that require a database update (or if there are any files that haven't been parsed yet). The preparation job should not interfere with any functionality. Are you seeing any problems? After the database is finished parsing the files in a workspace, the next time it won't have to parse the file contents, so it should complete faster.

**Comment by wlya** [comment]
When I re-open vscode, cpu usage will keep 25% for about 5 minutes. 
It's should not keep so much time in such high cpu usage, because I didn't change anything in the project.
I'm using MacOS Sierra, Macbook Pro 2015 13.3', with PCIE SSD(700+MB/s in R/W).

I'll retry this ASAP.

**Comment by sean-mcmanus** [comment]
25% CPU usage for 5 minutes may be normal, as long as it's faster than the 1st time (we use one core to scan files for changes that don't match the database, even if it never parses any contents).

**Comment by sean-mcmanus** [comment]
We have a bug/regression that is causing the database to rebuild on every workspace open. We'll try to get a fix soon.

**Comment by ghost** [comment]
i'm using vscode to read Linux kernel code on win10, and still having this problem. And in my case, everytime i re-open vscode, the C/C++ Extension will spend very long time (30+ minutes) to re-parse the whole codes. 
VScode: 1.18.1
C/C++ Extension: 0.14.4

**Comment by sean-mcmanus** [comment]
@donkey1120 We have a pre-release with the fix if you want to try it out (https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.14.6-insiders) and let us know if there are any fixes we should make before our release next week.

**Comment by lumonix** [comment]
@sean-mcmanus did this fix make it into the latest vs_code (for Linux)?
Our code base is also enormous (100,000's of files), but I'm ok with the initial cache building taking an hour or more as long as it is quicker next time opening VS code..

Is there a github link to the bug-fix you mentioned went into the pre-release?
Thanks!

**Comment by sean-mcmanus** [comment]
Yeah, this was fixed with 0.14.6. Looks like I just forgot to close this duplicate issue (https://github.com/Microsoft/vscode-cpptools/issues/1288 ).
