### ISSUE TITLE
IntelliSense false failure when  config provider ms-vscode.cmake-tools

### ISSUE THREAD

**Issue by hgtsoi** [microsoft/vscode-cpptools#10627]
### Environment

- OS and Version: windows 11
- VS Code Version: 1.76.0
- C/C++ Extension Version: 1.14.4
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Boost included in CMake list file and project can compiled successfully.
But boost::function, boost::bind complains incomplete type.

Expected behavior:
No intellisense errors.  1.13.x is fine. But 1.14.x start to have this issue.

### Configuration and Logs

```shell
{
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
```

### Other Extensions

cmake tools

**Comment by sean-mcmanus** [comment]
Setting "configurationProvider": "ms-vscode.cmake-tools" works in general, so we need more repro info. Can you provide the output of C/C++: Log Diagnostics? It should show what Custom Configurations are being sent to us by CMake Tools. Can you give more info on the IntelliSense error, such as what it says? It could just be a regression with our IntelliSense parser if the configuration diagnostics output appears to be correct.
