### ISSUE TITLE
Parsing language status says "Initializing Workspace" instead of Indexing/Parsing

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10623]
It might only repro with configurationProvider set.

**Comment by sean-mcmanus** [comment]
I currently see the status become correct once it enters the Parsing phase (unless that situation is harder to repro), but it's incorrect still during the Indexing phase. Indexing Workspace appears correctly if Rescan Workspace is used.

**Comment by michelleangela** [comment]
Closing this issue and added it to https://github.com/microsoft/vscode-cpptools/issues/10749.
