### ISSUE TITLE
mac error squiggle not showing even when enabled

### ISSUE THREAD

**Issue by CoolJosh0221** [microsoft/vscode-cpptools#10633]
### Environment

- OS and Version:  macOS Monterey
- VS Code Version:  Version: 1.76.0
- C/C++ Extension Version: Version 1.14.4
- If using SSH remote, specify OS of remote machine: x

### Bug Summary and Steps to Reproduce

Bug Summary:
I'm using llvm the clang compiler(clangd) and when the code has syntax error, there is no error squiggle even when I enable it.

<img width="1002" alt="Screen Shot 2023-03-04 at 11 15 28 PM" src="https://user-images.githubusercontent.com/88709160/222914041-3eafb02f-6e1f-4dad-8ee5-22b34dfe13fa.png">

<img width="906" alt="Screen Shot 2023-03-04 at 11 16 19 PM" src="https://user-images.githubusercontent.com/88709160/222914095-9dd01e63-90cb-43cf-9255-1ebde50bbe80.png">

<img width="806" alt="Screen Shot 2023-03-04 at 11 20 07 PM" src="https://user-images.githubusercontent.com/88709160/222914307-bccb4386-993a-4554-a160-42a3b0a469ea.png">

Expected behavior:
Expected to have error squiggles below the code with syntax error.

### Configuration and Logs

```shell
IntelliSense process crash detected.
IntelliSense process crash detected.
IntelliSense process crash detected.
IntelliSense process crash detected.
IntelliSense process crash detected.
IntelliSense process crash detected.
IntelliSense process crash detected.
IntelliSense process crash detected.
```

**Comment by CoolJosh0221** [comment]
plus every time I type a word the "IntelliSense process crash detected." increases

**Comment by sean-mcmanus** [comment]
Are you able to get a call stack for the crash somehow, such as via attaching a debugger or enabling a core dump to be generated? https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv .

Are you able to do something to make it not crash, i.e. does it crash after changing something?

**Comment by sean-mcmanus** [comment]
Also, do you know if downgrading to version 1.13.9 of our extension has the same issue?

**Comment by CoolJosh0221** [comment]
> Are you able to get a call stack for the crash somehow, such as via attaching a debugger or enabling a core dump to be generated? https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv .
> 
> Are you able to do something to make it not crash, i.e. does it crash after changing something?

I'm not able to let it not crash

**Comment by sean-mcmanus** [comment]
And it still crashes with 1.13.9 and 1.15.2?

Also, I believe there's a way to get the Mac OS to log a crash log somewhere which should have the call stack.

**Comment by CoolJosh0221** [comment]
It stops crashing but it's very laggy

https://user-images.githubusercontent.com/88709160/232790880-34123670-5f67-40e7-b3d3-c1c31cfd69c8.mp4

https://user-images.githubusercontent.com/88709160/232791070-1f097534-4369-400d-97ff-3b78127e5123.mp4

**Comment by sean-mcmanus** [comment]
It stops crashing with both 1.13.9 and 1.15.2? What is causing the lag? Is cpptools or cpptools-srv using a lot of memory or CPU?

**Comment by bobbrow** [comment]
The lag in the videos looks like our intentional delay for reparsing the file.
