### ISSUE TITLE
Cannot Open Source File

### ISSUE THREAD

**Issue by Grey41** [microsoft/vscode-cpptools#10648]
### Environment

- OS and Version: MacOS ARM64
- VS Code Version: 1.76.0
- C/C++ Extension Version: v1.14.4

### Bug Summary and Steps to Reproduce

VSCode cannot open header files, even if they are directly within the workspace directory. I get error squiggles under each `#include` - IntelliSense cannot seem to open `.h` files even when they are on the include path.

I also have the following suggestion: `Add to "includePath": ${workspaceFolder}`. The extension can detect the presence of my header files but it can seem to read them.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/local/include/fuse"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-arm64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
We need more info. Can you run C/C++: Log Diagnostics from the command palette and look if the include paths reported at the bottom are the paths to the headers that are reported as being not found?

**Comment by Grey41** [comment]
For some reason, it has started working as expected. Reinstalling Code and it's extensions may have solved the problem. I can't reproduce the error anymore so I'll close this issue.
