### ISSUE TITLE
Syntax highlight fails for "class", "public", "protected", "private" when inheriting from templated class

### ISSUE THREAD

**Issue by jmigual** [microsoft/vscode-cpptools#10644]
### Environment

- OS and Version: Windows 11 22H2 (OS Build 22621.1344
- VS Code Version: 1.76.0
- C/C++ Extension Version: v1.14.4
- If using SSH remote, specify OS of remote machine: Not using SSH

### Bug Summary and Steps to Reproduce

Bug Summary: When inheriting a templated class with a template the keywords "class", "public", "protected", and "private" do not get highlighed if the line does not terminate with a "{"

Steps to reproduce:
1. Open VSCode with the c++ extension enabled
2. Create a ".cpp" file with the following contents:

```cpp
// With templates
template <typename T> class MyClass {
};
template <typename T> class MyDerivedClass : public MyClass<T> 
{
};
template <typename T> class MyDerivedClass2 : public MyClass<T> {
};

// Without templates
class NonTemplate {
};
template <typename t> class MyDerivedClass3 : public NonTemplate 
{
};
template <typename t> class MyDerivedClass4 : public NonTemplate {
};
```

The highlight is as follows:
![code](https://user-images.githubusercontent.com/6493651/223760369-f9713e94-8a3b-4a8a-8d4d-d7426538db68.png)

Notice how line 3 is not highlighted properly.

Expected behavior: the keywords "class" and "public" are highlighted.

### Configuration and Logs

```shell
-------- Diagnostics - 3/8/2023, 4:48:44 PM
Version: 1.14.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "c:\\Users\\20204729\\Projects\\test\\cpp/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "compilerPath": "cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\20204729\Projects\test\cpp\src\main.cpp ]:
    C:\Users\20204729\Projects\test\cpp\src\main.cpp
Translation Unit Configurations:
[ C:\Users\20204729\Projects\test\cpp\src\main.cpp ]:
    Process ID: 6856
    Memory Usage: 44 MB
    Compiler Path: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe
    Includes:
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\atlmfc\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 44 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5195
Number of files parsed: 415
```

### Other Extensions

Also installed `codesnap` to take the screenshot. The issue persists if the extension is not enabled.

**Comment by Colengms** [comment]
Hi @jmigual .  The C/C++ Extension provides semantic colorization, but syntax colorization (for language keywords, etc.) is actually provided by VS Code itself.  It's done using a TextMate grammar.  For C/C++, VS Code ingests that grammar from a 3rd party, which is hosted [here](https://github.com/jeff-hykin/better-cpp-syntax).  I'd suggest opening this issue there.  Also, you might try the "Better C++ Syntax" extension (which is built from that repo), as it often includes fixes that haven't been ingested by VS Code yet.

Closing this issue as external.
