### ISSUE TITLE
C/C++ typedef data type highlight

### ISSUE THREAD

**Issue by MrDeSanta** [microsoft/vscode-cpptools#10643]
Type: <b>Bug</b>

I defined a typedef with C/C++ language, such as typedef unsigned char uint8, and I use "uint8" in other place, but the "uint8" doesn't appear with different color. For other codes folder, the "uint8" appear with different color, but some folders, it's same with normal codes' color

Extension version: 1.14.4
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.23GB free)|
|Process Argv|Y:\\Source --crash-reporter-id 3a11e45e-ef7f-41a1-8c50-8e9dac1f6825|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30672706
vsccsb:30677849
vscodedisable:30660115
pythonb192:30669360
pythonms35cf:30676801

```

</details>

**Comment by sean-mcmanus** [comment]
Can you give more repro info? What are you seeing? What are you C_Cpp.enhancedColorization settings? Are you getting IntelliSense working for all the folders? Semantic colors won't appear if IntelliSense is failing to parse the file.

With enhancedColorization:
![image](https://user-images.githubusercontent.com/19859882/223878034-f31a4c73-cabb-4f30-ab89-cdc7f1134ca9.png)
Without:
![image](https://user-images.githubusercontent.com/19859882/223878211-22e373e7-1c82-40f3-8ca9-c7950530793d.png)

**Comment by sean-mcmanus** [comment]
Also, running this command can show info on where the colors are coming from:
![image](https://user-images.githubusercontent.com/19859882/223878385-c40cd01f-9695-475a-9b74-a32d7da637e8.png)
