### ISSUE TITLE
Colorization  for const variable 

### ISSUE THREAD

**Issue by AlessandroScrem** [microsoft/vscode-cpptools#10661]
### Feature Request

Could be useful to have different colorization for constant variables.

example:

![image](https://user-images.githubusercontent.com/48774358/224566418-49db1247-1866-463c-bbc9-f89319e20b18.png)

**Comment by Colengms** [comment]
Hi @AlessandroScrem .  The C/C++ Extension shares the same IntelliSense engine with VS.  I've opened a similar feature request against VS [here](https://developercommunity.visualstudio.com/t/Colorization-for-C-const-variable/10308461) , in case that might encourage VS users to up-vote it as well.
