### ISSUE TITLE
Please stop constantly writing "C_Cpp.codeAnalysis.clangTidy.path" to .vscode/settings.json

### ISSUE THREAD

**Issue by headhunter45** [microsoft/vscode-cpptools#10663]
### Feature Request

This value contains a user/machine specific path. In my case  "/Users/tom/Applications/llvm-mos/bin/clang-tidy". This is a problem because I like to commit the settings.json i.e the Workspace Settings with project specific settings and keep user/machine specific settings in my personal settings.json i.e. the User Settings.

I've tried copying the key into my user settings, but it still adds it to my workspace settings. It does this constantly for some reason as well. If I edit the workspace settings to remove the key it overwrites the file as soon as I save or delete it.

I'm hoping this is a minor oversight and not actually intentional. Since every other plugin I use that stores machine specific settings puts them in user settings instead. I'm ok with a workaround too, but I think that the extension should at least not write this key to the workspace settings if it is already present in user settings.

Thank You.

**Comment by Colengms** [comment]
Hi @headhunter45 .  I'm not easily able to find a location in the code where the C/C++ extension would explicitly write this particular setting to a `settings.json` file.  I can't find any cases in which that particular setting value would be passed through to `WorkspaceConfiguration.update()`.  Can you clarify if there is some scenario that is causing this to occur?  Do you perhaps have another extension that might be writing this setting?

**Comment by headhunter45** [comment]
Sorry, searching for that key pointed me to this addon, but with only C/C++, C/C++ Extension Pack, and C/C++ Themes enabled it's not happening. I'll sort through my addons this weekend to see what combination is causing it.
If this is still open when I find it I'll let you know in case you can/want to do something about it.
It's weird that this is the only value that gets written constantly like this.
