### ISSUE TITLE
support for bugprone-assignment-in-if-condition

### ISSUE THREAD

**Issue by lvlerber** [microsoft/vscode-cpptools#10667]
Settings for vscode > Extensions > C/C++ > Code Analysis > Clang Tidy > Checks: Enabled
allow to add checks from a list that contains 
...
bugprone-argument-comment
bugprone-assert-side-effect
bugprone-bad-signal-to-kill-thread
...
but not bugprone-assignment-in-if-condition.

Is there a way to add this support by config or extra install?  If not, can this check be added to the standard?

**Comment by sean-mcmanus** [comment]
You should be able to add that value to the setting -- it'll just give a warning about the value not being supported. You can also use the check in a .clang-tidy file. We have a fix at https://github.com/microsoft/vscode-cpptools/pull/10668, but I'm not sure when it'll be released yet.
