### ISSUE TITLE
Debugger - opens wrong path.

### ISSUE THREAD

**Issue by rutexd** [microsoft/vscode-cpptools#10672]
### Environment

- OS and version: ``Windows: 10 / 19044.2604``
- VS Code: ``1.76.1 (user setup)``
- C/C++ extension: ``1.14.4``
- OS and version of remote machine (if applicable): ``N/A``
- GDB / LLDB version:t ``GNU gdb (GDB) 11.1``

### Bug Summary and Steps to Reproduce

Bug Summary:
__Paths are messed.__ 
After breakpoint is set and it occurs, debugger tries to open the file where breakpoint was set. Instead of real file ``c:\dev\cpp\src\main.cpp``, debugger tries to open ``C:\dev\cpp\C\dev\cpp\src\main.cpp`` which is obliviosly invalid.

My project tree: 
```
c:\dev\cpp:
    .vscode: ...
    src:
        - main.cpp
   - main.exe (compiled main.cpp)
 ```

#### Tasks.json
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "MinGW build project",
            "type": "cppbuild",
            "command": "g++.exe",
            "args": [
                "-g",
                "${file}",
                "-lsfml-graphics",
                "-lsfml-window",
                "-lsfml-system",
                "-lsfml-audio",
                "-lsfml-network",
                "-o",
                "${workspaceFolder}\\main.exe"
                
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
        },
    ]
}
```
____

#### Launch.json

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(gdb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}\\main.exe",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": true,
      "MIMode": "gdb",
      "miDebuggerPath": "C:\\msys64\\usr\\bin\\gdb.exe",
      "logging": {
        "engineLogging": true,
        "trace": true,
        "traceResponse": true
      },
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
    },
  ]
}
```

### Debugger Logs

```shell
https://pastebin.com/raw/GwHV3G4M
```

### Other Extensions

Everything except C++ extension is disabled

### Additional Information

Screenshoot

![image](https://user-images.githubusercontent.com/112971914/224979828-b1097826-8e78-4fd9-a286-708c8a287027.png)

gdb and gcc are installed via MSYS2.  

breakpoint is set directly on first line of my main function.

**Comment by WardenGnaw** [comment]
> https://pastebin.com/raw/GwHV3G4M

I am unable to see the paste. 

but from the logs it seems like the debug adapter is not getting the correct path and is appending an additional path.

`c:\dev\cpp\src\main.cpp` vs `C:\dev\cpp\C<?>\dev\cpp\src\main.cpp`

**Comment by rutexd** [comment]
Im sorry, seems like pastebin has changed something. Here is the log.

[GwHV3G4M.txt](https://github.com/microsoft/vscode-cpptools/files/10976716/GwHV3G4M.txt)

**Comment by WardenGnaw** [comment]
Can you elaborate on your build/debug environment with MSYS2?

I was unable to reproduce this with:
1. Downloaded MSYS2 at https://www.msys2.org/
2. Added `C:\msys64\usr\bin` to Windows PATH environment variable
3. Create a project outside of the MSYS2 shell environment. e.g. not under `C:\msys64\home\*`
4. Open VS Code and open the project folder.
5. Create a task.json and launch.json pointing to C:\msys64\bin\g++ and gdb.
6. Hit F5 to build and debug project.

**Comment by rutexd** [comment]
Just reinstalled everything and seems like i installed wrong build tools for first time. Now it works properly.

Seems like instead of ``mingw-w64-x86_64-toolchain`` I installed almost 'raw' gcc and gdb (``mingw-w64-x86_64-gcc``, ``gdb``), so it looks like they arent fully compatible or in second scenario there no nessesary install scripts, idc. But now it works.

Thanks for your time and for help.
