### ISSUE TITLE
Attaching a running process to LLDB is killing the process 

### ISSUE THREAD

**Issue by Sooryaa-A** [microsoft/vscode-cpptools#10671]
### Environment

- OS and version:MacOs Monterey 12.6.2
- VS Code: 1.76.1 (Universal)
- C/C++ extension: 1.14.4
- OS and version of remote machine (if applicable):
- GDB / LLDB version: lldb-1400.0.38.17

### Bug Summary and Steps to Reproduce

Bug Summary:
Im not able to attach to a signed c++ binary from lldb, though I can run the process from lldb, attaching to a running process is sending stop signal and exiting. Without VSCode, simple lldb itself not attaching.

tried with a simple main.cpp test code also.

Note : using Rosetta to run the x86_64 binaries.

Steps to reproduce:

I have a c++ project which I have compiled using rosetta , using grade build. Debug build process is running and can debug it independently when started along with LLDB.

When tried to attach to an already running process from VSCode,the process gets killed.

I tried to reproduce it with a simple main.cpp , that also gets killed

In rosetta terminal, Im starting a c++ binary and trying to attach it with lldb.
the process gets killed.

```
lldb
(lldb)  attach -p 74131
Process 74131 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007ff808f1f2be libsystem_kernel.dylib`__semwait_signal + 10
libsystem_kernel.dylib`:
->  0x7ff808f1f2be <+10>: jae    0x7ff808f1f2c8            ; <+20>
    0x7ff808f1f2c0 <+12>: movq   %rax, %rdi
    0x7ff808f1f2c3 <+15>: jmp    0x7ff808f1ddb9            ; cerror
    0x7ff808f1f2c8 <+20>: retq   
Target 0: (minbin) stopped.
Executable module set to "/Users/soorya.a/CPP_Code/minbin".
Architecture set to: x86_64-apple-macos-.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007ff808f1f2be libsystem_kernel.dylib`__semwait_signal + 10
    frame #1: 0x00007ff808e33863 libsystem_c.dylib`nanosleep + 196
    frame #2: 0x00007ff808e3e6e8 libsystem_c.dylib`sleep + 41
    frame #3: 0x0000000100cfe03b minbin`main + 59
    frame #4: 0x0000000200e1852e dyld`start + 462
(lldb) exit
```

### Debugger Configurations

```shell
not using tasks.json or launch.json for build and lunch .Manually building and launching
```

### Debugger Logs

```shell
NA
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
