### ISSUE TITLE
"Compiler query command line" slows startup performence.

### ISSUE THREAD

**Issue by Kztpia** [microsoft/vscode-cpptools#10680]
### Environment

- OS and Version:  windows 10
- VS Code Version:  1.76.0
- C/C++ Extension Version:  1.14.4
- If using SSH remote, specify OS of remote machine:  ubuntu 14.04

### Bug Summary and Steps to Reproduce

Bug Summary:
cpp server takes very long time before provide any info at startup. C/C++ output keeps printing" Attempting to get defaults from C compiler in compile_commands.json file." " Compiler query command line."

This happens when compile_commands info provided by "command" filed in compile_commands.json.

It seems the language server refuse to parse current opened file before " Compiler query command line" for all files listed in compile_commands.json. Maybe these could happens at the same time ? ---- Parse current opened file while walking all entries in compile_commands.json

Steps to reproduce:
1. download kernel source( linux 6.1 for example)
2. build kernel with any handy config and generate compile_command.json at the same time. cmd would like "cd ${kernel_source}; make cc=${compiler} ${other_arguments} all compile_commands.json"
3. open any file in kernel source with vscode and choose to use generated compile_commands.json.

Expected behavior:
opened file should be parsed immediately.

Actual behavior:
opened file will no be parsed until all entries in compile_commands.json are walked.

### Configuration and Logs

```shell
The build server have internet access so I cannot post any raw logs here. But I can help confirming if any specific output shows up in log.
```

**Comment by sean-mcmanus** [comment]
We have a fix for the "Attempting to get defaults from C compiler in compile_commands.json file" log messages for our pending 1.15.0, but I'm guessing the performance issue would still exist since I believe the issue is due to the parsing of the compile_commands.json itself.

**Comment by Kztpia** [comment]
> We have a fix for the "Attempting to get defaults from C compiler in compile_commands.json file" log messages for our pending 1.15.0, but I'm guessing the performance issue would still exist since I believe the issue is due to the parsing of the compile_commands.json itself.

Yes, I think this is about the strategy of how compile_commands.json is used. 

When it comes to provide semantic info for a specific c file (or one translation unit), only one enrty in compile_commands.json is required. This should be ready very soon after cppserver load compile_commands.json. 

But for now, cppserver will try to get defaults from C compiler for every single entry in compile_commands.json before it provide any semantic info( which I think is unnecessary).
