### ISSUE TITLE
Add support for multi-root workspaces

### ISSUE THREAD

**Issue by dnmiller** [microsoft/vscode-cpptools#1070]
There's a mention by @bobbrow at the bottom of #368 that multi-root workspaces will be added in a future release, but I couldn't find an open issue to track its progress.

This would be a great feature. Apologies if there's already an issue for this.

**Comment by bobbrow** [comment]
We opened an issue in our internal database, but didn't mirror it here.  I will link this issue to that one in our backlog sync tool.

**Comment by lmapii** [comment]
has/will this feature be released? is there any information on how it'll look like already?

**Comment by sean-mcmanus** [comment]
Yes, it was released in November. We close all fixed issues after they're released. See https://blogs.msdn.microsoft.com/vcblog/2017/11/09/visual-studio-code-cc-extension-nov-2017-update-multi-root-workspaces-support-is-here/ . Let us know if you have any questions or hit any bugs.

**Comment by lmapii** [comment]
ah i see - thanks! my approach is typically quite different - a multi-folder project in my case means that i have to drag various folders into my workspace (e.g., common self-developed units, third party libraries, project specific code) which depend on one another - but do not have the same root folder and thus need to be included like this. e.g., my unit A needs an include from a third party library.

my typical approach is to setup a workspace _per project_. any project includes multiple folders, e.g., a certain third party library (that might also be used in another workspace). BUT:

project specific files need the includePath/browse settings from this library, i.e., i need to be able to have these resolutions in all the folders added to the workspace. is there a possibility for a "workspace" (!= folder) configuration such that i actually "merge" those?

i can elaborate on this if it helps.

**Comment by sean-mcmanus** [comment]
@lmapii I don't understand what you're asking. Are you asking about getting the C/C++ extension to be setup correctly or something to with VS Code itself? You can do an Edit Configuration to set the includePath and browse.path settings on a per workspace folder basis. Are you asking for workspace settings? We currently only have c_cpp_properties.json settings for each workspace root/folder and there's no shared one per user or per workspace. We have plans to move the c_cpp_properties.json settings into the normal settings.json, so it would be available per user/workspace/folder.

**Comment by lmapii** [comment]
it is about the C/C++ extension and i think it is exactly what you are planning to do: moving the c_cpp_properties.json to the normal settings.json > which is also available per workspace.

this would allow me to use the includePaths/browse from one workspace folder A in another workspace folder B, i.e., modules from workspace folder A can use includes from workspace folder B. is there an issue# for that i could subscribe to?

**Comment by sean-mcmanus** [comment]
One existing issue is https://github.com/Microsoft/vscode-cpptools/issues/1229 and another is https://github.com/Microsoft/vscode-cpptools/issues/368 .

**Comment by lmapii** [comment]
subscribed to #1229, looking for updates there. thanks :) !
