### ISSUE TITLE
`#import` of `.tlb` files fail due to `/Fo` argument to `cl.exe` not being considered.

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#10710]
### Environment

- OS and Version: Win 10 22H2
- VS Code Version: 1.76.2
- C/C++ Extension Version: 1.14.4

### Bug Summary and Steps to Reproduce

Bug Summary:
`#import` statements are not resolved in C++/CLI code. This leads to error squiggles being disabled for the entire translation unit if `C_Cpp.errorSquiggles` is set to `enabledIfIncludesResolve` which makes that setting unusable in C++/CLI codebases.

Notice the error squiggle, despite the tlb sitting right there.
![image](https://user-images.githubusercontent.com/484784/226543125-687f6a6f-aad3-427b-ab6d-232d8d178fa3.png)

But this compiles just fine
![image](https://user-images.githubusercontent.com/484784/226543165-bb18edff-f42e-4d15-8a3d-22b933620813.png)

Expected behavior:
`#import`s should resolve

### Configuration and Logs

```shell
{
	"C_Cpp.default.compilerPath": "cl.exe",
	"C_Cpp.default.compilerArgs": [ "/clr" ],
}
```

**Comment by akbyrd** [comment]
Even with the extra files present it doesn't resolve. It works if the tlh is next to the cpp, but not if it's in another directory, even if it's added to the path. It's fine if the tlb is in a another directory.

![image](https://user-images.githubusercontent.com/484784/227074215-d7ecdada-14fa-4825-8007-e97e9f13f37e.png)

Here's a repro:
[Bug.zip](https://github.com/microsoft/vscode-cpptools/files/11046026/Bug.zip)

**Comment by Colengms** [comment]
Hi @akbyrd .  When I compile with `cl.exe` without any additional arguments, I see that the `.tlh` file is generated in the same directory as the including file (not the location of the `.tlb` file.  When I run a build, the file is found where `cl.exe` put it.  So, given the command line args you've provided, IntelliSense appears to be looking in the correct location, and this appears to be by-design.

However, a `/Fo` argument to `cl.exe` should influence the expected location for those files, which is something we do not appear to be handling correctly.  That is something we can fix.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.2 .

**Comment by akbyrd** [comment]
I'm testing the new release (1.15.4) and still running into some issues.

*Issue 1*
Quotes don't seem to be handled correctly.
This works:
`"C_Cpp.default.compilerArgs": [ "/Iinclude", "/Foobj/" ],`
This does not:
`"C_Cpp.default.compilerArgs": [ "/Iinclude", "/F\"oobj/\"" ],`
Same effect in settings.json or c_cpp_properties.json

*Issue 2*
Symbols from the tlb aren't resolving.
```
#import "LCDHardwareMonitor.PluginLoader.CLR.Interface.tlb"
ILHMPluginLoader* foo;
```
`ILHMPluginLoader` is one of the symbols provided by the tlb. This resolves in Visual Studio but still shows a red error squiggle in VS Code. The import resolves, but the symbol does not.

*Issue 3*
Should "go to definition" work on the import filename?
