### ISSUE TITLE
stdarg.h file not found, only erroring if I put it in header file, not the .cpp file

### ISSUE THREAD

**Issue by olliepop777** [microsoft/vscode-cpptools#10711]
### Environment

- OS and Version: macOS 13.2.1
- VS Code Version: 1.76.2
- C/C++ Extension Version: 1.14.4

### Bug Summary and Steps to Reproduce

Bug Summary: When I `#include <stdarg.h>` in a header file like `my_file.h`, it gives an error when building the project `fatal error: 'stdarg.h' file not found`. But when I move the include to a .cpp file like `my_file.cpp` it suddenly goes away and compiles/builds fine. If I build outside of VSCode, it also works fine no matter where the include is. I am a bit of a novice with C++, so not sure if I did something wrong but that is not what I expect the behavior to be. 

I see a few others issues related to stdarg.h but none of the solutions worked for me and it seems they were never really resolved in the end.
https://github.com/microsoft/vscode-cpptools/issues/5349
https://github.com/microsoft/vscode-cpptools/issues/1144

I left the compilerPath blank b/c it keeps switching back to `macos-clang-arm64` IntelliSense Mode if I don't leave it blank. If I leave it blank a lot of the IntelliSense is breaking though. I am trying to build for `x86_64` on an M1 Mac (arm64). Maybe I just misconfigured something? How do I stop it from switching back to `macos-clang-arm64` if I set the compiler path?

### Configuration and Logs

```shell
c_cpp_properties.json

{
    "configurations": [
        {
            "name": "my_custom",
            "includePath": [
                "${workspaceFolder}/**",
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang++",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-x64"
        }
    ],
    "version": 4
}
```

Log Diagnostics:
```
-------- Diagnostics - 3/21/2023, 12:53:21 AM
Version: 1.14.4
Current Configuration:
{
    "name": "my_custom",
    "includePath": [
        "/Users/user/Documents/src/test/**",
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "macos-clang-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 6240
```
```


### Other Extensions

_No response_

### Additional context

_No response_

**Comment by sean-mcmanus** [comment]
c_cpp_properties.json is only for configuring IntelliSense and not building. Your build would be done in a tasks.json or other means (another build extension, etc.). I don't know how the header is being built, but it sounds like the build of the source file is including the correct system includes and the build of the header is not.

You can configure IntelliSense to use an x64 target in the same way you do for compiling, one potential way is setting `"compilerArgs": ["-target=x64"],`.

**Comment by olliepop777** [comment]
After reading your comment I found you are right, this is not an issue in the C/C++ extension, but an issue with the CMake Tools extension I am also using. Thanks for the tip, I found that it is due to CMake Tools including the system includes on top of it already being included from the SDK I am using. I don't why it's doing that or how to turn it off, the only way I found was removing the compilers option in the `cmake-kits.json` file. I will ask in the CMake Tools project instead how to stop that behavior. Thanks for the help

**Comment by olliepop777** [comment]
> and our extension would query the compiler to add the system includes/defines.

Yea I think this is the part that I wanted to turn off? When I compile outside of VSCode I notice in the output that those extra includes are not happening. At least, they don't print in the console anymore. It also stops happening if I remove the compilers option from `cmake-kits.json` like I mentioned earlier
