### ISSUE TITLE
[FR] Update `clang-format` & `clang-tidy` from the latest LLVM 16 release

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#10718]
### Feature Request

Just a reminder I guess

**Comment by sean-mcmanus** [comment]
Yes, we know -- I had already created https://github.com/microsoft/vscode-cpptools/issues/10725 and didn't see this issue.

As described in that issue -- we're hitting a build issue for Linux aarch64 we probably need to resolve first.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.2 .
