### ISSUE TITLE
Request: Don't set the `UNICODE` define by default on Windows

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode-cpptools#10722]
### Environment

- OS and Version: Win10
- C/C++ Extension Version: v1.14.4

### Bug Summary and Steps to Reproduce

Bug Summary:

in UTF-8 files, when calling a `<<name_1>>` function from Win32 API, its expanded into `<<name_1>>W` and not `<<name_1>>A` , this leads to error warnings in some scripts .

Steps to reproduce:
1. write a script which uses 1 of relevant commands, wait for the Intelisense to process it .

Expected behavior:

according to MSVC docs, the choice should be done based on Unicode BOM, and default to, as i understand, values of OS settings -- "Language for non-Unicode programs" . VSC provides a more relevant value per file . regardless, the current behavior is clearly not desired because the 2ndary OS encoding which is set in the subject case, uses 8 bit characters .

### Configuration and Logs

```shell
-
```

**Comment by Colengms** [comment]
Hi @irvnriir .

> write a script which uses 1 of relevant commands, wait for the Intelisense to process it .

Are you hovering over the function name, and is your issue based on seeing it resolve incorrectly?

![image](https://user-images.githubusercontent.com/49173979/227037283-0d5ef585-5335-474f-89e7-1c14bbba23e8.png)

The result above is based on the existence of a definition for `UNICODE` in my configuration.  The macro value is what would be used when the code is compiled, if also passing the the `UNICODE` macro on a compile command line.  This behavior is related to how the code would be compiled, not the text encoding of the source file itself.

Perhaps you're using the default configuration for the C/C++ Extension, which includes "UNICODE"?  If you run `C/C++: Edit Configuration (JSON)`, you should see something like this:

```
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.22000.0",
            "compilerPath": "C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.34.31721/bin/Hostx64/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64"
        },
```

If I comment out the define for `"UNICODE"`, I see the following on hover:

![image](https://user-images.githubusercontent.com/49173979/227037839-04a96023-bf5e-4765-995e-d8a05c12173c.png)

More information on how to configure the C/C++ Extension can be found [here](https://code.visualstudio.com/docs/cpp/config-msvc#_cc-configurations).

If using a build system such as Make or CMake, IntelliSense configurations can be automatically imported from the build system, using custom configuration providers (VS Code extensions) such as Makefile Tools or CMake Tools.

**Comment by irvnriir** [comment]
@Colengms yes, that is an outcome of the issue .

im using no custom configuration . as i described, the default behavior is undesired .

**Comment by Colengms** [comment]
It's been our default to include the `UNICODE` define in the default configuration, for quite a while. There are several advantages to using the UNCODE versions of Windows API functions (as the ANSI versions do not support UNICODE at all - they are not UTF-8).

In your case, I'd suggest adding the following to your global settings: `"C_Cpp.default.defines": []`
With no `c_cpp_properties.json` present, that should ensure a default define of `UNICODE` is not provided.

Changing the default would impact a lot of users.  We can keep this issue open as a feature request, in case there are sufficient users who up-vote it.

**Comment by irvnriir** [comment]
@Colengms
im pretty sure this is not true
> as the ANSI versions do not support UNICODE at all - they are not UTF-8

if you compile a program with "W" versions of the functions, output of chars beyond basic ANSI will be even more screwed . the functions gotta be differing only in char size .

**Comment by Colengms** [comment]
Hi @irvnriir .  The ANSI functions use the current system code page, which likely is not UTF-8 in most cases.  This means that the "A" functions can only be relied upon when the input text is known to be encoded using whatever the current system code page is set to.

https://learn.microsoft.com/en-us/windows/win32/intl/unicode-and-character-sets
https://docs.microsoft.com/en-us/windows/win32/intl/code-pages
https://docs.microsoft.com/en-us/windows/win32/intl/windows-data-types-for-strings

In the native portions of the C/C++ extension, we use UTF-8 (as that is exclusively what VS Code passes to us, regardless of the original encoding of the file opened in the editor).  We need to convert from UTF-8 internally to UTF-16 for any calls to Windows API functions that require it, in order to ensure proper encoding.

**Comment by irvnriir** [comment]
@Colengms apparently you're right . i did some tests in other environment -- the "W" functions are correctly processing unicode; compilation, and source files', setups don't affect the functions . im questioning some design decisions, but this issue is closed .
