### ISSUE TITLE
cpptools uses >100% CPU everytime

### ISSUE THREAD

**Issue by asfernandes** [microsoft/vscode-cpptools#10727]
### Environment

- OS and Version: Ubuntu 22.10
- VS Code Version: 1.76.1 (but is happening since many versions)
- C/C++ Extension Version: v1.14.4 (but also tried the pre-release version - and is happening since many time)

### Bug Summary and Steps to Reproduce

Bug Summary:

It's almost impossible to continue using the extension.

cpptools process always goes above 100% CPU and in most cases the only way to resolve is closing vscode.
And when starting work again, it happens again.

Steps to reproduce:
My main workflow is using https://github.com/FirebirdSQL/firebird but this also happens with others personal projects.

Expected behavior:

cpptools work correctly.

### Configuration and Logs

```shell
The problem is that there are others issues that people already sent these things and nothing was resolved!
```

**Comment by asfernandes** [comment]
This issue is happening by a long time for me, but recently it's happening with much more frequency (or I'm just seeing it more because my laptop cooler is weird and noise).
Here is cpptools stack trace.
[cpptools-stack.txt](https://github.com/microsoft/vscode-cpptools/files/11045840/cpptools-stack.txt)

**Comment by asfernandes** [comment]
After disconnect from debugger or suspending the laptop and activating it again, the process became normal again.

**Comment by sean-mcmanus** [comment]
Those call stacks show no work -- all the threads are idle, so there should be not CPU usage. If you repro the issue again, a call stack of thread that is doing the work could help us identify what is going wrong.

**Comment by asfernandes** [comment]
I will try to get more stack traces.
Where can I find the extension logs? I don't see anything related with this extension in vscode tab where there are others extensions logs.

**Comment by sean-mcmanus** [comment]
If you set C_Cpp.loggingLevel to "Debug" you can see the logging in the "C/C++" pane. Some info on how to get stack traces is at https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv .

**Comment by asfernandes** [comment]
Sometime in the past I really had problems with this extensions using 100% CPU for so much time that needed vscode restart. That was happening again and again.

The current problem seems some pikes that is making my failing hardware fan to be very loud for much more time than the pikes.

**Comment by sean-mcmanus** [comment]
We need to know if the CPU is being used by the cpptools process or cpptools-srv and also the Debug logging or a call stack in order to determine what is going on and potential solutions.
