### ISSUE TITLE
Question? EDG 6.5 update

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#10739]
### Feature Request

I think VSCode uses EDG for C++. I've seen a few new features in EDG 6.5 implemented. Will we be getting these soon?

**Comment by sean-mcmanus** [comment]
Yeah, not for 1.15.x though.

**Comment by sean-mcmanus** [comment]
@H-G-Hristov It looks like we may or potentially may get "some" of the EDG 6.5 features -- was there a specific feature you were looking for, such as one marked as added by 6.5 at https://en.cppreference.com/w/cpp/compiler_support/23 ?

**Comment by H-G-Hristov** [comment]
@sean-mcmanus  Thanks exactly these C++23 shown on the cppreference page, so I can have less red squiggles in C++23.

**Comment by sean-mcmanus** [comment]
We should have `Literal suffix for (signed) size_t ` support in 1.16.0 (pre-release). The other two 6.5 features I don't know about yet (i.e. might be after 1.16.x).

**Comment by H-G-Hristov** [comment]
@sean-mcmanus Thank you sounds, great!
Off-topic question: I am curious, does implementing a feature such as `Literal suffix for (signed) size_t` require additional work on your side? Doesn't the EDG parser provide this support out of the box?

**Comment by sean-mcmanus** [comment]
@H-G-Hristov I don't do that work so I'm not 100% sure, but from what I understand there's no additional work unless we need to make some change related to something we've added/modified on top of EDG.

And any GitHub issue we mark as "Visual Studio" usually just involves merging the fix in (maybe fixing some merge or test issue) and verifying that it works, but sometimes a fix needs to be ported/copied if it's not directly shared.
