### ISSUE TITLE
Connect notification prompts for compile commands and configuration provider with Configure IntelliSense status

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#10731]
Work item reference (GitHub issue link, etc.): https://github.com/microsoft/vscode-cpptools/issues/10685

Problem:
• Users may want to configure their compiler through compile commands or configuration provider instead of the compiler quickpick
. We should hide the "Configure IntelliSense" status whenever this is done.

**Comment by bobbrow** [comment]
I believe this is handled by #10756
