### ISSUE TITLE
Endless loop, 100% CPU usage and no results while opening sqlite3.c

### ISSUE THREAD

**Issue by parghami** [microsoft/vscode-cpptools#10744]
### Environment

- OS and Version: Fedora 37
- VS Code Version: 1.76.2
- C/C++ Extension Version: 1.14.5
- If using SSH remote, specify OS of remote machine: NO

### Bug Summary and Steps to Reproduce

Bug Summary:
It seems to be an endless loop in the intellisense implementation.

Steps to reproduce:
1. Just open the latest sqlite3.c file (you can download it from sqlite.org) and watch the CPU usage!
2. CPU usage 100%, fan speed MAX and after a couple of minutes run-time, nothing! no results, no intellisense goodness. And the best of all, it never stops, it keeps the CPU nice and warm at 100% all the time. Until you close the VS-Code. Even closing the C-file does not stop the intellisense junk!
3. The best extension ever! From the best company ever! Microsoft cares about the CO2 emissions, right?

Expected behavior:
No high CPU usage while opening a large C-file.

### Configuration and Logs

```shell
Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:57:21.103Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 6.2.7-200.fc37.x86_64
Sandboxed: No
```

**Comment by sean-mcmanus** [comment]
I don't repro the issue with 3.41.2 -- what version of sqlite3.c are you using?

**Comment by sean-mcmanus** [comment]
Okay, nevermind -- I repro the issue now.

**Comment by sean-mcmanus** [comment]
I don't repro this with 1.18.5. 1.19.2 will improve the handling of the large file more.
