### ISSUE TITLE
cppbuild tasks do not set cwd to the workspace folder

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#10742]
### Environment

- OS and Version: 22H2 19045
- VS Code Version: 1.76.2
- C/C++ Extension Version: 1.14.5

### Bug Summary and Steps to Reproduce

Bug Summary: shell tasks set the current working directory to the workspace folder. cppbuild tasks do not. This means that converting a working shell task to a cppbuild task does not work.

The working directory is set to the installation directory of vscode, which doesn't seem particularly useful.

Steps to reproduce:
* Execute this task:
    ```
    {
        "label": "build",
        "group": "build",
        "type": "shell",
        "command": "dir",
        "args": [],
    }
    ```
* Notice cwd is the workspace folder
* Execute this task:
    ```
    {
        "label": "build",
        "group": "build",
        "type": "cppbuild",
        "command": "dir",
        "args": [],
    }
    ```
* Notice cwd is the vscode installation folder

Expected behavior:
* shell and cppbuild tasks have the same working directory
* cppbuild tasks use the workspace folder as the working directory

### Configuration and Logs

```shell
N/A
```

**Comment by sean-mcmanus** [comment]
You can workaround this via adding
```json
            "options": {
                "cwd": "${workspaceFolder}"
            },
```
to the task in tasks.json

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.15.2 .
