### ISSUE TITLE
Parsing status says "complete" when it is not (causing workspace parsing pausing not to be available)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10749]
See the screenshot with 1.14.5:

![image](https://user-images.githubusercontent.com/19859882/228101510-c9adfe7d-a90b-4e17-a3c7-2bf24011c7bb.png)

Not 100% sure of the repro, but I used Linux with a simple test workspace.

Also, this causes the Pause Workspace Parsing option to not be available.

**Comment by sean-mcmanus** [comment]
This might be fixed by https://github.com/microsoft/vscode-cpptools/pull/10974 (not sure yet).

**Comment by michelleangela** [comment]
It seems that the initial state of parsing is incorrect and inconsistent. When "pause" command becomes available, it needs to be clicked twice before the language server will actually pause parsing. From debugging, the flag `_pausing` is initially set to true on on startup on the language server for some reason.

**Comment by sean-mcmanus** [comment]
@michelleangela Workspace parsing may become paused in cpptools when it goes to process a recursive includes and it's paused in TypeScript when a configuration provider first registers.
