### ISSUE TITLE
Incorrect "explicitly instantiated more than once" warnings in C++

### ISSUE THREAD

**Issue by gcp** [microsoft/vscode-cpptools#1074]
- VSCode Version: 1.16.1
- OS Version: Ubuntu 16.04
- Version 0.13.0: September 25, 2017

Steps to Reproduce:

1. Load https://github.com/gcp/Stockfish/src
2. Open pawns.cpp, navigate to bottom

```C++
template<Color Us>
Score Entry::do_king_safety(const Position& pos, Square ksq) {
...
}

// Explicit template instantiation
template Score Entry::do_king_safety<WHITE>(const Position& pos, Square ksq);
template Score Entry::do_king_safety<BLACK>(const Position& pos, Square ksq);
```

VSCode's C++ IntelliSense red underlines these, claiming a duplicate explicit instantiation. But as you can see, that's not correct.

**Comment by bobbrow** [comment]
Thanks for the bug report.  It turns out we are already tracking this issue with #871.
