### ISSUE TITLE
Macro expansion within #if/#elseif/#else/#endif construct prevents parsing of ensuing function

### ISSUE THREAD

**Issue by soonercode** [microsoft/vscode-cpptools#10746]
### Environment

- OS and Version:  Windows 10 Enterprise 21H2 build 19044.2604
- VS Code Version: 1.76.2
- C/C++ Extension Version: 1.14.5

### Bug Summary and Steps to Reproduce

Bug Summary:
After certain #if/#elseif/#else/#endif constructs containing macros that accept arguments, the Intellisense parser fails to recognize the next function definition.  By "fails to recognize" I mean the definition of that function does not appear in the "outline" view, and the breadcrumb bar does not show that function's name when the cursor is placed within the function body.

Steps to reproduce:
1. Unzip [test.zip](https://github.com/microsoft/vscode-cpptools/files/11079490/test.zip) and open the enclosed test.c file
2. Select the "Explorer" in the primary side bar
3. Open the "Outline" section of the Explorer
4. Note that Function1 and Function3 appear in the Outline, but Function2 does not
5. Place the cursor in the body of Function2 (line 19)
6. Note that Function2 is not shown in the breadcrumb bar

Expected behavior:

Function2 should appear in Outline and in breadcrumb bar.

### Configuration and Logs

```shell
I could not find a c_cpp_properties.json file in my workspace or in my user directory.

-------- Diagnostics - 3/27/2023, 9:53:35 AM
Version: 1.14.5
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "c:\\WDLabs\\foo/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\gnu1_06\\bin\\gcc.exe",
    "cppStandard": "c++98",
    "intelliSenseMode": "windows-gcc-x86",
    "cStandard": "c99",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\WDLabs\foo\test.c ]:
    C:\WDLabs\foo\test.c
Translation Unit Configurations:
[ C:\WDLabs\foo\test.c ]:
    Process ID: 18272
    Memory Usage: 45 MB
    Compiler Path: C:\gnu1_06\bin\gcc.exe
    Includes:
        C:\gnu1_06\include
        C:\gnu1_06\lib\gcc\mingw32\3.4.5\include
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c99
    IntelliSense Mode: windows-gcc-x86
    Other Flags:
        --gcc
        --gnu_version=30405
Total Memory Usage: 45 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 627

Language log does not look interesting:
loggingLevel: Debug
loggingLevel has changed to: Debug
LSP: cpptools/fileCreated: file:///c%3A/WDLabs/foo/.vscode/settings.json
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/activeDocumentChange: file:///c%3A/WDLabs/foo/test.c
LSP: cpptools/getCodeActions: file:///c%3A/WDLabs/foo/test.c (id: 30)
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/getCodeActions: file:///c%3A/WDLabs/foo/test.c (id: 31)
LSP: cpptools/getFoldingRanges: file:///c%3A/WDLabs/foo/test.c (id: 32)
LSP: textDocument/hover: file:///c%3A/WDLabs/foo/test.c (id: 33)
LSP: textDocument/hover: file:///c%3A/WDLabs/foo/test.c (id: 34)
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/getCodeActions: file:///c%3A/WDLabs/foo/test.c (id: 35)
LSP: textDocument/hover: file:///c%3A/WDLabs/foo/test.c (id: 36)
LSP: textDocument/documentHighlight: file:///c%3A/WDLabs/foo/test.c (id: 37)
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/getCodeActions: file:///c%3A/WDLabs/foo/test.c (id: 38)
LSP: textDocument/hover: file:///c%3A/WDLabs/foo/test.c (id: 39)
```

### Additional context

The issue seems to occur only when the #if/#elif/#else/#endif construct contains 3 or more clauses, AND when the macros expanded therein are macros that accept arguments.  

It does not seem to matter which clause is active, nor does it seem to matter what is contained in the macro definition.  (The sample code has an empty definition of ARGUMENT_MACRO(x) in order to show the simplest possible case.)

The issue occurs whether the final clause is #else or #elseif, provided that there are at least 3 total clauses.

**Comment by Colengms** [comment]
Hi @soonercode .  I believe what you're seeing is by-design and due to how macros are handled by the browse database parser.  Detailed information can be found here: https://learn.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170

Using your example, I created a `cpp.hint` file in the same directory, containing:

```
#define ARGUMENT_MACRO(x) 
```

Then I ran `C/C++: Reset IntelliSense Database` to force regeneration of the tag parser database, and reloaded the window.  That resulted in:

![image](https://user-images.githubusercontent.com/49173979/228051986-1a601465-7f02-4937-8b46-83095384f770.png) 

Closing this issue as by-design.
