### ISSUE TITLE
analyse header file failed with clang-tidy

### ISSUE THREAD

**Issue by AlanKing95** [microsoft/vscode-cpptools#10759]
### Environment

- OS and Version: win10
- VS Code Version: 1.76.2
- C/C++ Extension Version: v1.14.5
- If using SSH remote, specify OS of remote machine: 
remote is ubuntu 20.04

### Bug Summary and Steps to Reproduce

**when I try to analyse some .h file, c_cpp reports:**

/usr/bin/clang-tidy
--export-fixes=/tmp/{18310183704467754583}/fixes139947239515904.yaml
--quiet
/home/alan/work/video-umd/src/base/pool.h
-p=/home/alan/work/video-umd/build/
Error while processing /home/alan/work/video-umd/src/base/pool.h.
/home/alan/work/video-umd/src/base/alias_base_type.h:15:1: error: unknown type name 'namespace' [clang-diagnostic-error]
namespace icube {
^
/home/alan/work/video-umd/src/base/alias_base_type.h:15:16: error: expected ';' after top level declarator [clang-diagnostic-error]
namespace icube {
               ^
               ;
/home/alan/work/video-umd/src/base/alias_std.h:12:10: error: 'algorithm' file not found [clang-diagnostic-error]
#include <algorithm>
         ^~~~~~~~~~~

**however, I can run in shell correctly with command "/usr/bin/clang-tidy --quiet /home/alan/work/video-umd/src/base/pool.h -p=/home/alan/work/video-umd/build/ -- -x c++ -I src"**
**but I don't know how to pass "-- -x c++ -I src" to clang-tidy through c_cpp**

**i think the cause is that /home/alan/work/video-umd/build/compile_commands.json does not contain "*.h"**
**so is there a way to handle this correctly?**

### Configuration and Logs

```shell
**here is my configuration:**
    "C_Cpp.autoAddFileAssociations": false,
    "C_Cpp.default.compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "C_Cpp.clang_format_style": "file",
    "C_Cpp.clang_format_fallbackStyle": "none",
    "C_Cpp.intelliSenseEngine": "default",
    "C_Cpp.intelliSenseCachePath": "${workspaceFolder}",
    "C_Cpp.codeAnalysis.clangTidy.enabled": true,
    "C_Cpp.codeAnalysis.clangTidy.useBuildPath": true,
    "C_Cpp.codeAnalysis.clangTidy.path": "/usr/bin/clang-tidy",
    "C_Cpp.loggingLevel": "Information",
```

**Comment by AlanKing95** [comment]
@sean-mcmanus 
do you have any idea about this issue?

**Comment by sean-mcmanus** [comment]
Yeah, you can use 
```json
        "C_Cpp.codeAnalysis.clangTidy.args": [
            "--extra-arg=-x c++",
            "--extra-arg=-I src"
        ],
```

**Comment by AlanKing95** [comment]
/usr/bin/clang-tidy
--extra-arg=-x c++
--extra-arg=-I src
--export-fixes=/tmp/{18310183704467754583}/fixes140459087214336.yaml
--quiet
/home/alan/work/video-umd/src/base/pool.h
-p=/home/alan/work/video-umd/build/
Error while processing /home/alan/work/video-umd/src/base/pool.h.
error: language not recognized: ' c++' [clang-diagnostic-error]
error: unable to handle compilation, expected exactly one compiler job in '' [clang-diagnostic-error]
LSP: cpptools/fileChanged: file:///home/alan/work/video-umd/src/base/pool.h

that not works for me，it seems that the args can only be passed after "--" in the end of commandline？
@sean-mcmanus

**Comment by sean-mcmanus** [comment]
@AlanKing95 Oops, change it to `--extra-arg=-xc++` and that should work although I still see the warning "warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [clang-diagnostic-deprecated]" (not sure why, but it doesn't appear to cause any failure currently).

**Comment by AlanKing95** [comment]
@sean-mcmanus 
Sadly， it still not works.
```
$ /usr/bin/clang-tidy --extra-arg=-xc++ --extra-arg=-Isrc /home/alan/work/video-umd/src/base/pool.h -p=/home/alan/work/video-umd/build/
1883 warnings and 21 errors generated.
Error while processing /home/alan/work/video-umd/src/base/pool.h.
error: invalid argument '-std=gnu99' not allowed with 'C++' [clang-diagnostic-error]
error: too many errors emitted, stopping now [clang-diagnostic-error]
/home/alan/work/video-umd/src/base/alias_base_type.h:15:1: error: unknown type name 'namespace' [clang-diagnostic-error]
```
`-x c++ `seem can only be added after `--`
I suggest to add another way (such as `C_Cpp.codeAnalysis.clangTidy.lastArgs`) to pass some other arguments like `-- -x c++`

**Comment by AlanKing95** [comment]
@sean-mcmanus 
Sadly， it still not works.
```
$ /usr/bin/clang-tidy --extra-arg=-xc++ --extra-arg=-Isrc /home/alan/work/video-umd/src/base/pool.h -p=/home/alan/work/video-umd/build/
1883 warnings and 21 errors generated.
Error while processing /home/alan/work/video-umd/src/base/pool.h.
error: invalid argument '-std=gnu99' not allowed with 'C++' [clang-diagnostic-error]
error: too many errors emitted, stopping now [clang-diagnostic-error]
/home/alan/work/video-umd/src/base/alias_base_type.h:15:1: error: unknown type name 'namespace' [clang-diagnostic-error]
```
`-x c++ `seem can only be added after `--`
I suggest to add another way (such as `C_Cpp.codeAnalysis.clangTidy.lastArgs`) to pass some other arguments like `-- -x c++`

**Comment by sean-mcmanus** [comment]
Normally, your compile commands would not have `-std=gnu99` for compiling with C++. You can add something like `"--extra-arg=-std=c++17"` to work around that.

**Comment by AlanKing95** [comment]
@sean-mcmanus 
sry，it cannot be worked around by that

```
$ /usr/bin/clang-tidy --extra-arg=-std=c++14 --extra-arg=-Isrc /home/alan/work/video-umd/src/base/pool.h -p=/home/alan/work/video-umd/build/ 
282 warnings and 2 errors generated.
Error while processing /home/alan/work/video-umd/src/base/pool.h.
error: invalid argument '-std=c++14' not allowed with 'C' [clang-diagnostic-error]
/home/alan/work/video-umd/src/base/alias_std.h:12:10: error: 'algorithm' file not found [clang-diagnostic-error]
```

**Comment by AlanKing95** [comment]
@sean-mcmanus 
sry，it cannot be worked around by that

```
$ /usr/bin/clang-tidy --extra-arg=-std=c++14 --extra-arg=-Isrc /home/alan/work/video-umd/src/base/pool.h -p=/home/alan/work/video-umd/build/ 
282 warnings and 2 errors generated.
Error while processing /home/alan/work/video-umd/src/base/pool.h.
error: invalid argument '-std=c++14' not allowed with 'C' [clang-diagnostic-error]
/home/alan/work/video-umd/src/base/alias_std.h:12:10: error: 'algorithm' file not found [clang-diagnostic-error]
```

**Comment by sean-mcmanus** [comment]
@AlanKing95 You removed `--extra-arg=-xc++` that should be added back.
