### ISSUE TITLE
All in one configuration selection experience

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#10756]
This issue covers the implementation of the new all-in-one experience for onboarding configurations.

This feature will be enabled as part of the new status bar button A|B experiment.  Use code in `telemetry.ts` to determine whether the experiment is active.

* Disable notification messages related to configuration when the experiment is active
  * Allowing a configuration provider
  * Use a compile_commands.json that we discovered
  * "Configure your IntelliSense settings to help find missing headers"
  * We found [compiler], do you want to use it to configure IntelliSense
* We still keep logic that auto-selects stuff without a prompt regardless of the experiment state
  * auto-select configuration provider
  * auto-select trusted compilers
* If we detect that a user is not configured, we show the status bar button for "Configure IntelliSense" when the experiment is active (this should already be implemented). Clicking on this button will show a new QuickPick with all the configuration options (configuration provider/compile commands/compilerPath).  This new quick pick is shown instead of the "Select a Compiler" quick pick which is the current implementation.
  * see Mock up below
  * A user is “configured” if:
    * If the user has set configurationProvider, compileCommands, or compilerPath in c_cpp_properties.json  
      * Even if the configProvider or compileCommands doesn’t cover the active source file, for now, I think we want to consider those folks as “configured” because the new quick pick will suggest that they set one of these fields and that would be confusing.  We can revisit this decision in a “v2” if we change our minds, or the experiment data guides us this way
      * Setting compilerPath to “” should also be consider “configured”
    * If the user has set C_Cpp.default.configurationProvider, C_Cpp.default.compileCommands, or C_Cpp.default.compilerPath in the Workspace/Folder settings (User settings too? I believe this means that they used “select a compiler” already).
    * If we auto-enabled a configuration provider.
    * If we auto-selected a compiler for them and there is no better configuration option available (e.g. configurationProvider or compileCommands)

Mock up
![image](https://user-images.githubusercontent.com/12818240/228638208-46b463e7-cf55-43f8-b001-8a2ea5c0ce7b.png)

Sample code
```ts
class Item implements vscode.QuickPickItem {
    constructor(public label: string, public description?: string, public detail?: string, public kind?: vscode.QuickPickItemKind) {
    }
}

const qp = vscode.window.createQuickPick<Item>();
qp.items = [
    new Item('extensions', undefined, undefined, vscode.QuickPickItemKind.Separator),
    new Item('Use information provided by CMake Tools'),
    new Item('Use information provided by Makefile Tools'),
    new Item('compile_commands.json', undefined, undefined, vscode.QuickPickItemKind.Separator),
    new Item('Use information from ${workspaceFolder}/build/compile_commands.json'),
    new Item('compilers', undefined, undefined, vscode.QuickPickItemKind.Separator),
    new Item('Use system headers from Visual Studio 2022'),
    new Item('Use system headers from g++', 'c:/msys2/mingw64/bin/g++.exe'),
    new Item('Select another compiler on my machine'),
    new Item('Help me install a compiler'),
    new Item('Don\'t configure IntelliSense for this workspace (not recommended)')
];
qp.title = 'Configure IntelliSense';
qp.placeholder = 'How would you like to configure IntelliSense for this workspace?';
qp.show();
qp.onDidAccept(() => {
    // `qp.selectedItems` should have the selected choice
    qp.hide();
    qp.dispose();
});
// there may be other events to subscribe to

**Comment by sean-mcmanus** [comment]
@bobbrow Can/should the "Select Default Compiler" command should be replaced by a "Configure IntelliSense" command? Otherwise, there's no way to manually invoke it and the Select Default Compiler dropdown is only hittable via the command.

**Comment by sean-mcmanus** [comment]
I'm currently going with "Select IntelliSense Configuration" as the new command.

Also, a sub-issue is I think we'll need to change the compiler selection to actually change the c_cpp_properties.json compilerPath if that is set already to avoid the confusion of it appearing to not work if that's already set, i.e. the concept of setting a "default" compiler will should go away, i.e. it'll set it in this order: user default, workspace default, workspace folder default, or c_cpp_properties.json depending on which is already set.

**Comment by sean-mcmanus** [comment]
@bobbrow The change from "Select Default Compiler" to "Select IntelliSense Configuration" is actually independent of the "Configure IntelliSense" UI -- it doesn't seem like we really need an experiment for that part of the change. We're basically just adding the config provider and compile commands options to the existing experience, while the experiment is just about the change from the status bar UI from the prompt.

**Comment by bobbrow** [comment]
I believe that "select default compiler" is still part of the flow we shipped in 1.14 where we identified a compiler for you but didn't automatically select it.  You can either accept our choice or pop open the "select default compiler" quick pick, right?

I think we should add a new command and quick pick for this experience.  We can share code between the two as appropriate.

**Comment by bobbrow** [comment]
When the experiment ends I think we'll have an opportunity to remove the "select default compiler" quick pick if we so desire.

**Comment by bobbrow** [comment]
> I'm currently going with "Select IntelliSense Configuration" as the new command.
> 
> Also, a sub-issue is I think we'll need to change the compiler selection to actually change the c_cpp_properties.json compilerPath if that is set already to avoid the confusion of it appearing to not work if that's already set, i.e. the concept of setting a "default" compiler will go away, i.e. it'll set it in this order: user default, workspace default, workspace folder default, or c_cpp_properties.json depending on which is already set.

We'll talk about this in our next sync up meeting.  If any of those is already set, I don't think people will see the new status bar button, but if they manually run the command we may need to add a follow up quick pick to let them decide where to store the setting.  Not sure about that part yet.

**Comment by sean-mcmanus** [comment]
@bobbrow Yeah, I've changed it so that the pre-existing prompt with the "Yes" button shows "Select IntelliSense Configuration" instead of "Select Default Compiler". Keeping "Select Default Compiler" is problematic in the implementation, particular due to the native side changes.

We can fix the c_cpp_properties.json compilerPath being updated in a later PR since it's not essential.

**Comment by sean-mcmanus** [comment]
@bobbrow FYI, I'm delaying showing the Configure IntelliSense status until we've had a chance to look for compile_commands.json -- otherwise, those will be missing -- that would also likely give configuration providers time to register and appear in the dropdown too.

**Comment by sean-mcmanus** [comment]
@bobbrow FYI, there might be some "issues" in the multi-root scenario that we may need to follow up on.

**Comment by bobbrow** [comment]
For now, I think we should only make this available (e.g. show the button) for single root - no multi-root or single file support yet.

**Comment by sean-mcmanus** [comment]
@bobbrow The existing code for the existing prompts already supported single/multi-root so there wasn't really any additional work required for that, i.e. the status bar may appear/disappear depending on which workspace folder is active and is not configured and the quick pick result will update the current workspace's config provider or compile commands and the compilerPath updating is the same as before where it updates the user setting and then updates the workspace and workspace folder depending on which is already set.

**Comment by bobbrow** [comment]
That sounds ok with me. You may want to check with @Colengms and see if he has any other concerns about multi-root.

**Comment by Colengms** [comment]
> compilerPath updating is the same as before where it updates the user setting

@sean-mcmanus If the guidance says, "How would you like to configure IntelliSense for this workspace", a selected compilerPath should be applied only to the current workspace.  Applying it in the user settings would seem incorrect.  If they do this in one workspace, then a second workspace, the user will not expect their selection to alter how they had configured a previous workspace.

**Comment by sean-mcmanus** [comment]
> @sean-mcmanus If the guidance says, "How would you like to configure IntelliSense for this workspace", a selected compilerPath should be applied only to the current workspace. Applying it in the user settings would seem incorrect. If they do this in one workspace, then a second workspace, the user will not expect their selection to alter how they had configured a previous workspace.

The guidance omits "this workspace".
