### ISSUE TITLE
C/C++ IntelliSense without error indication for undefined function in C language.

### ISSUE THREAD

**Issue by duohe** [microsoft/vscode-cpptools#10764]
### Environment

- OS and Version: WIN 10 22H2
- VS Code Version: x64 1.77.0
- C/C++ Extension Version: 1.7.1
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Create a main.c file, and write down: 
void test(void)
{
    aaaa();
}
There is no error indication for undefined function aaaaa().
Like this:
![image](https://user-images.githubusercontent.com/39433530/229165217-ee2a2ae1-4fa8-4e9e-805d-edcbed23365d.png)

But if change main.c to main.cpp.
There will be a indication “identifier “aaaa” is undefined C/C++ 20” for undefined function aaaaa().
Like this:
![image](https://user-images.githubusercontent.com/39433530/229165089-b88a3372-e5ba-4d3c-a36f-99e14c8e0bf7.png)

### Configuration and Logs

```shell
All configurations are in default values.
```

**Comment by bobbrow** [comment]
Thank you for reporting this issue. It looks to be the same as another issue we're tracking, so we will close this one. #828
