### ISSUE TITLE
GTK+ module libcanberra-gtk-module.so cannot be loaded

### ISSUE THREAD

**Issue by Petros626** [microsoft/vscode-cpptools#10763]
Hello guys,

I'm using _OpenCV_ in VSCode (Ubuntu Software installation) and everything worked fine, until I updated my libraries (`sudo apt-get update/upgrade/full-upgrade`) I guess. But now VSCode or rather _OpenCV_ can't find the _GTK_ library. 

I've tested this succesfully:
 `GTK_PATH=/usr/lib/x86_64-linux-gnu/gtk-2.0 ./test` --> works

But when I specify the version gtk-3.0:
`GTK_PATH=/usr/lib/x86_64-linux-gnu/gtk-3.0 ./test` --> fails

 Normally the loaded version without using GTK_PATH is gtk-3.0 and then it shows me this error:
![image](https://user-images.githubusercontent.com/62354721/229435079-a85c5ff1-a8c3-4870-9340-bdc9404e595b.png)

I verified that the in `/usr/lib/x86_64-linux-gnu/gtk-3.0/modules` is:

![image](https://user-images.githubusercontent.com/62354721/229059188-4171f730-d2d9-4b6c-b103-447ca8ee727b.png)

Would appreciate to solve this warning and to understand why the .so cannot be loaded.

Thanks in advance

**UPDATE:** the example code can be executed without warnings in the normal gnome terminal, but VSCode seems to habe problems to find the specific libraries, so it's definitely _VSCode_.

**Comment by sean-mcmanus** [comment]
This is unrelated to our C/C++ extension. You should file an issue with VS Code at https://github.com/microsoft/vscode/issues .

**Comment by Petros626** [comment]
Sorry mixing this two issues everytime.
