### ISSUE TITLE
cpptools maybe leak after starting for a while

### ISSUE THREAD

**Issue by tuduweb** [microsoft/vscode-cpptools#10768]
### Environment

- OS and version: win10
- VS Code: 1.76.1
- C/C++ extension: v1.15.1
- OS and version of remote machine (if applicable): Ubuntu20 Ubuntu18
- GDB / LLDB version: 8.4.0

### Bug Summary and Steps to Reproduce

Bug Summary:
cpptools maybe leak

Steps to reproduce:
I don't know how to reproduce, I probably opened 10 project via vscode-remote, and just one or two have cpp file in those project.

![memory-too-high](https://user-images.githubusercontent.com/30559085/229685486-f2d993e5-63a6-4760-b450-1ae5d40f570d.jpg)

and I just shutdown the `c/c++ extension...` process and close that project which includes cpp files, and the task launch again

![cppleak](https://user-images.githubusercontent.com/30559085/229685506-851f8dc6-b923-4055-87ed-8547b7da6e82.jpg)

### Debugger Configurations

```shell
/
```

### Debugger Logs

```shell
/
```

**Comment by sean-mcmanus** [comment]
Also, you bug report mentions remote Linux, but your screenshot shows our Windows process/extension using the memory -- is  your repro on Linux or Windows? On Linux you can use some program like "top" to see the memory usage.

**Comment by tuduweb** [comment]
> Also, your bug report mentions remote Linux, but your screenshot shows our Windows process/extension using the memory -- is your repro on Linux or Windows? On Linux you can use some program like "top" to see the memory usage.

thx for your reply. I rechecked my situation, I found this is caused by Win10 local project, not Linux.
And I overlooked this before, this memory usage may be caused by a large number of files in that project(maybe > 3milion files. I'm not sure of the accurate number).

And this project doesn't have any CPP files, just some picture files, and Python files.
And after I kill the process, the process will relaunch again, and keep small memory usage(about 250M?)
After a long time(maybe some hours), the usage will increase rapidly.

Now it is increasing again, with no disk usage but memory increases every second.

**Comment by tuduweb** [comment]
The numbers stopped increasing, maybe related to my files size.
![Screenshot 2023-04-05 032521](https://user-images.githubusercontent.com/30559085/229899178-6a08d104-a392-4863-b1b8-2161821324c0.jpg)

So maybe it's not a bug? But the disk usage increase to 22.xMB/s again

**Comment by sean-mcmanus** [comment]
Our extension should not be activating if there's no no C/C++ files or no c_cpp_properties.json -- do you know what is causing our extension to be activating. It might also activate if debugging is started.

If you set C_Cpp.loggingLevel to "Debug" you may be able to see what is going on and add the folders to the C_Cpp.files.exclude setting to avoid processing those folders shown in the logging.

**Comment by bobbrow** [comment]
If you suspect an incorrect activation, you can run the `Developer: Startup Performance` command in VS Code. It will print out a table under `Extension Activation Stats` that will show the event that caused the C++ extension to activate.

**Comment by tuduweb** [comment]
> Our extension should not be activating if there's no no C/C++ files or no c_cpp_properties.json -- do you know what is causing our extension to be activating. It might also activate if debugging is started.
> 
> If you set C_Cpp.loggingLevel to "Debug" you may be able to see what is going on and add the folders to the C_Cpp.files.exclude setting to avoid processing those folders shown in the logging (i.e. potentially the root folder).

I guess that should be I opened a CPP file which directory in windows file manager out of the project, and the extension actived in that moment.

**Comment by tuduweb** [comment]
> If you suspect an incorrect activation, you can run the `Developer: Startup Performance` command in VS Code. It will print out a table under `Extension Activation Stats` that will show the event that caused the C++ extension to activate.

Thx for your reply, I get it, but I have closed the project.

**Comment by haolongzhangm** [comment]
![lADPKIJfUDcjG2nNAXbNBig_1576_374 jpg_720x720q90g](https://github.com/microsoft/vscode-cpptools/assets/10891471/df025d6a-9292-4928-a327-12563fbb9bd5)

**Comment by haolongzhangm** [comment]
why cpptools have so stupid issue

**Comment by haolongzhangm** [comment]
cpptools-1.16.3-linux-x64

**Comment by sean-mcmanus** [comment]
@haolongzhangm Because we haven't found a repro yet.

**Comment by tuduweb** [comment]
> ![lADPKIJfUDcjG2nNAXbNBig_1576_374 jpg_720x720q90g](https://user-images.githubusercontent.com/10891471/251143629-df025d6a-9292-4928-a327-12563fbb9bd5.jpg)

your vscode also open a folder with amount files or large files?

**Comment by sean-mcmanus** [comment]
@tuduweb Can you restrict your browse.path setting to include less files, such as a c_cpp_properties.json with
```json
            "browse": {
                "path": []
            }
```
