### ISSUE TITLE
The extension makes computer crash when hovering "hard to expand" macros

### ISSUE THREAD

**Issue by brvtalcake** [microsoft/vscode-cpptools#10775]
### Environment

- OS and Version: Ubuntu 22.10
- VS Code Version: 1.77
- C/C++ Extension Version: 1.14.5
- If using SSH remote, specify OS of remote machine: none

### Bug Summary and Steps to Reproduce

Bug Summary: 
I made a foreach macro for C, using [metalang99](https://github.com/Hirrolot/metalang99) : 

```c
#if defined(foreach) || defined(foreach_counter) || defined(foreach_stop_cond) || defined(LOOP_TO_THE_END) || defined(LOOP_WHILE)
    #undef foreach
    #undef foreach_counter
    #undef foreach_stop_cond
    #undef LOOP_TO_THE_END
    #undef LOOP_WHILE
#endif
#define LOOP_TO_THE_END ML99_nothing()
#define LOOP_WHILE(x) ML99_just(v(x))
#define foreach_counter(lines_after_foreach) FMC_CONCAT_2(base_index, FMC_DECR_BY(__LINE__, lines_after_foreach))
#define foreach_stop_cond(x, array) ML99_EVAL(ML99_EVAL(ML99_call(ML99_if, ML99_isNothing(x), v(ML99_id(ML99_id(v(foreach_counter(0) < sizeof(array)/sizeof(array[0]))))), v(ML99_maybeUnwrap(x)))))
#define foreach(elem, array, start, stop_index_cond) size_t foreach_counter(0) = start; for(typeof(array[foreach_counter(0)]) elem = array[foreach_counter(0)]; foreach_stop_cond(stop_index_cond, array) ; foreach_counter(0)++, elem = array[foreach_counter(0)])
```
(The foreach macro has to be on one line, otherwise I would have to change `foreach_counter`)

When I tried to use it in a 1000 lines file, and tried to verify what it expands to, my computer litteraly froze, and crashed with a black screen. This is the very first time I ran into this kind of issue to be honest. My computer is not even an old PC nor usually particularly slow. Here is my config : 

- **CPU** : 
```
axel@axel-ubuntu:~$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
  Model name:            12th Gen Intel(R) Core(TM) i3-12100
    CPU family:          6
    Model:               151
    Thread(s) per core:  2
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            5
    CPU(s) scaling MHz:  39%
    CPU max MHz:         5500,0000
    CPU min MHz:         800,0000
    BogoMIPS:            6604.80
    Flags:               [...]
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   192 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    5 MiB (4 instances)
  L3:                    12 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-7
[...]
```
- **RAM** : 16Go DDR5 (4800 MT/s speed)
- **GPU** : none (Intel graphics)
- [...] tell me if you need more

Note that GCC successfully compiled my file with the macro, and the code worked.

Steps to reproduce:
1. Get [my fork of metalang99](https://github.com/brvtalcake/metalang99) (if you can) (don't take the original one because foreach_counter will otherwise only work in very little files (i.e more than ~70 lines or something like that)
2. Copy the macro (and use it somehow)
3. Put your mouse on the macro
4. See error (for some reasons I tried again and it worked like 2-3 times without any error so I kept working, and then I tried another time it went wrong again)

Expected behavior:
Supposed to not crash.

### Configuration and Logs

**c_cpp_properties.json** : 

```shell

axel@axel-ubuntu:~$ cat /home/axel/Documents/programmation/c/FManC/.vscode/c_cpp_properties.json
{
    "version": 4,
    "configurations": [
        {
            "name": "Linux_FManC",
            "includePath": [
                "${workspaceFolder}/**",
                "/home/axel/Documents/programmation/c/FManC/third_party_libs/metalang99/include/"
            ],
            "defines": [
                "_DEFAULT_SOURCE",
                "_LARGEFILE64_SOURCE",
                "_FILE_OFFSET_BITS=64"
            ],
            "compilerPath": "/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64",
            "compilerArgs": [],
            "mergeConfigurations": false
        }
    ]
}
```

**C/C++: Log diagnostics** (I think it's useless since I (and I had to) restarted my computer) : 
```
Version: 1.14.5
Current Configuration:
{
    "name": "Linux_FManC",
    "includePath": [
        "/home/axel/Documents/programmation/c/FManC/**",
        "/home/axel/Documents/programmation/c/FManC/third_party_libs/metalang99/include/"
    ],
    "defines": [
        "_DEFAULT_SOURCE",
        "_LARGEFILE64_SOURCE",
        "_FILE_OFFSET_BITS=64"
    ],
    "compilerPath": "/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [],
    "mergeConfigurations": false,
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "configurationProvider": "vector-of-bool.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "/home/axel/Documents/programmation/c/FManC/third_party_libs/metalang99/include/"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/axel/Documents/programmation/c/FManC/src/file_management/io/FMC_file_read.c ]:
    /home/axel/Documents/programmation/c/FManC/src/file_management/io/FMC_file_read.c
    /home/axel/Documents/programmation/c/FManC/src/general/preprocessor/FMC_macros.h *
Translation Unit Configurations:
[ /home/axel/Documents/programmation/c/FManC/src/file_management/io/FMC_file_read.c ]:
    Process ID: 4753
    Memory Usage: 119 MB
    Compiler Path: /bin/gcc
    Includes:
        /home/axel/Documents/programmation/c/FManC/third_party_libs/metalang99/include
        /usr/lib/gcc/x86_64-linux-gnu/12/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
        /home/axel/Documents/programmation/c/FManC/third_party_libs/mimalloc/include
    Defines:
        _DEFAULT_SOURCE
        _LARGEFILE64_SOURCE
        _FILE_OFFSET_BITS=64
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=120200
Total Memory Usage: 119 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 24259
Number of files parsed: 1248
```

**C/C++** : 
I preferred to put it in a text file because it's huge. It also seems to be more relevant : 
[issue.txt](https://github.com/microsoft/vscode-cpptools/files/11165019/issue.txt)

### Other Extensions

I'll put only those related to C/C++, or at least probably running in the same time : 

42-formatter : ID = keyhr.42-c-format
better align : ID = chouzz.vscode-better-align
C/C++ (your extension)
C/C++ Include Gards : ID = akiramiyakoda.cppincludeguard
C/C++ Snippets : ID = hars.CppSnippets 
Doxygen (two different ones) : - ID = bbenoist.Doxygen
                               - ID = cschlosser.doxdocgen
Error Lens : ID = usernamehw.errorlens
Git graph : ID = mhutchie.git-graph
Github theme : ID = GitHub.github-vscode-theme
Intellicode : ID = VisualStudioExptTeam.vscodeintellicode
Wakatime : ID = WakaTime.vscode-wakatime

And others that are disabled

 

### Additional context

None

**Comment by sean-mcmanus** [comment]
I'm guessing the cpptools-srv process is stuck in some loop which causes an endless amount of memory to be used. The Linux OS doesn't seem to handle a process using too much memory particularly well compared to Windows or Mac, which tend to still allow enough UI access to kill the process using too much memory.

**Comment by browntarik** [comment]
Could you provide a specific example of how you used the foreach macro so I can get an accurate reproduction of the crash?

**Comment by brvtalcake** [comment]
> I'm guessing the cpptools-srv process is stuck in some loop which causes an endless amount of memory to be used. The Linux OS doesn't seem to handle a process using too much memory particularly well compared to Windows or Mac, which tend to still allow enough UI access to kill the process using too much memory (or maybe you need enough disk space for the OS to swap the memory out, etc.).

Yes, or maybe I installed too much extensions ? By the way my swap partition is ~32Go (I forgot to mention it).



> Could you provide a specific example of how you used the foreach macro so I can get an accurate reproduction of the crash?

For instance : 

```c
int int_array[42] = {0};
// fill it with what you want
foreach(int_elem, int_array, 0, LOOP_TO_THE_END)
{
    printf("%d\t", int_array[foreach_counter(2)] /* or just int_elem */);
}
```

Or even something like : 


```c
int int_array[42] = {0};
// fill it with what you want
foreach(int_elem, int_array, 0, LOOP_WHILE(foreach_counter(0) < 42))
{
    printf("%d\t", int_elem);
}
```

There is a for loop under the hood, and the counter is something like CONCAT(baseindex, __LINE__). So if you need to reference the counter, you need to specify the number of line after the foreach line.

**Comment by browntarik** [comment]
In your example macro, it looks like you are using size_t which is a c++ convention, are you using a c compiler or c++ compiler?

**Comment by browntarik** [comment]
`#include <metalang99.h>

#include <stdio.h>
#define size_t int
#define typeof(x) int
#define FMC_CONCAT(x, y) x ## y
#define FMC_CONCAT_2(x, y) FMC_CONCAT(x, y)

#if defined(foreach) || defined(foreach_counter) || defined(foreach_stop_cond) || defined(LOOP_TO_THE_END) || defined(LOOP_WHILE)
    #undef foreach
    #undef foreach_counter
    #undef foreach_stop_cond
    #undef LOOP_TO_THE_END
    #undef LOOP_WHILE
#endif
#define LOOP_TO_THE_END ML99_nothing()
#define LOOP_WHILE(x) ML99_just(v(x))
#define FMC_DECR_BY(x, y) ML99_EVAL(ML99_call(ML99_sub, v(x), v(y)))
#define foreach_counter(lines_after_foreach) FMC_CONCAT_2(base_index, FMC_DECR_BY(__LINE__, lines_after_foreach))
#define foreach_stop_cond(x, array) ML99_EVAL(ML99_EVAL(ML99_call(ML99_if, ML99_isNothing(x), v(ML99_id(ML99_id(v(foreach_counter(0) < sizeof(array)/sizeof(array[0]))))), v(ML99_maybeUnwrap(x)))))
#define foreach(elem, array, start, stop_index_cond) size_t foreach_counter(0) = start; for(typeof(array[foreach_counter(0)]) elem = array[foreach_counter(0)]; foreach_stop_cond(stop_index_cond, array) ; foreach_counter(0)++, elem = array[foreach_counter(0)])

int main2()
{
    int int_array[42] = {0};
    // fill it with what you want
    foreach(int_elem, int_array, 0, LOOP_TO_THE_END)
    {
        printf("%d\t", int_array[foreach_counter(2)] /* or just int_elem */);
    }
}

`

I had to make these changes in order to compile correctly and still have been able to reproduce the crash. Any extra information would be helpful.

**Comment by brvtalcake** [comment]
@browntarik I don't understand, did you manage to reproduce at least the freeze ?
I don't understand why you needed to make these changes. The example I gave you works on my machine : 

```c
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <metalang99.h>

#define FMC_DECR_BY(x, y) ML99_EVAL(ML99_call(ML99_sub, v(x), v(y)))
#define FMC_CONCAT(_x, _y) x##x
#define FMC_CONCAT_2(_x, _y) FMC_CONCAT(_x, _y)
#define LOOP_TO_THE_END ML99_nothing()
#define LOOP_WHILE(x) ML99_just(v(x))
#define foreach_counter(lines_after_foreach) FMC_CONCAT_2(base_index, FMC_DECR_BY(__LINE__, lines_after_foreach))
#define foreach_stop_cond(x, array) ML99_EVAL(ML99_EVAL(ML99_call(ML99_if, ML99_isNothing(x), v(ML99_id(ML99_id(v(foreach_counter(0) < sizeof(array)/sizeof(array[0]))))), v(ML99_maybeUnwrap(x)))))
#define foreach(elem, array, start, stop_index_cond) size_t foreach_counter(0) = start; for(typeof(array[foreach_counter(0)]) elem = array[foreach_counter(0)]; foreach_stop_cond(stop_index_cond, array) ; foreach_counter(0)++, elem = array[foreach_counter(0)])


int main(int argc, char** argv)
{
    int int_array[42] = {[0 ... 41] = 42};
    // fill it with what you want
    foreach(int_elem, int_array, 0, LOOP_TO_THE_END)
    {
        fprintf(stderr, "%d\t", int_array[foreach_counter(2)] /* or just int_elem */);
    }
    fprintf(stderr, "\n");
    return 0;
}
```

I don't wanna try to reproduce the freeze / crash again, because I'm working on my PC right now, but I'm pretty sure it "works".

**Comment by brvtalcake** [comment]
> Could you provide a simplified source file that I could use to easily debug, this source file should be able to expand the macro.

Btw I'm sorry I didn't see your reply but then here is it (the one above)

**Comment by bobbrow** [comment]
I tried it out on Ubuntu 22.04 and didn't have any issues.

![image](https://user-images.githubusercontent.com/12818240/231018525-463a58b3-9a72-4c66-a794-86432f327400.png)

**Comment by brvtalcake** [comment]
> I tried it out on Ubuntu 22.04 and didn't have any issues.
> 
> ![image](https://user-images.githubusercontent.com/12818240/231018525-463a58b3-9a72-4c66-a794-86432f327400.png)

Yes, I tried it again too, and it worked well. It may just be my computer, so for now it seems to be OK to close the issue, since I'm unable to reproduce it today. Maybe that was a one-time bug, or maybe I had too much tabs opened in VS Code (and in my browser). If it happens again I'll try to record my screen with my phone so you can clearly see what happens.
