### ISSUE TITLE
GDB Debug pause not working in 1.16.1(Windows)

### ISSUE THREAD

**Issue by tim37021** [microsoft/vscode-cpptools#1077]
I am not able to pause the process. Adding breakpoint when running always fails.
toolchain: x86_64-7.1.0-posix-seh-rt_v5-rev2 mingw-w64

**Comment by tim37021** [comment]
Only remote debug(gdb attach) works

**Comment by pieandcakes** [comment]
@tim37021 Yes, this is a limitation of MinGW/Cygwin. you need to break in the UI and then break in your terminal window in order for us to be able to change state. Alternatively you can set `"stopAtEntry": true` in your `launch.json` and then when it stops in your `main()` method, you can setup your breakpoints and then continue debugging
