### ISSUE TITLE
@throws is not highligted in doxygen comments

### ISSUE THREAD

**Issue by dlech** [microsoft/vscode-cpptools#10781]
### Environment

- OS and Version: Ubuntu 22.04
- VS Code Version: 1.77.0
- C/C++ Extension Version: 1.14.5
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:

As seen in the screenshots below, `@throws` is not highlighted while `@throw` is. 

![image](https://user-images.githubusercontent.com/963645/230644658-76149991-04cb-4a36-8653-011392b067b2.png)

![image](https://user-images.githubusercontent.com/963645/230644746-28d98814-e273-48f8-a1a4-c1aba1581f71.png)

Steps to reproduce:

Create a C/C++ source code file with the following comment:
```c++
/**
 * @returns something
 * @throws error
 */
int my_func() { }
```

Expected behavior:

Both variants should work just like  `@returns` and `@return` do.

### Configuration and Logs

```shell
Logs don't seem particularly useful for this issue.
```

**Comment by dlech** [comment]
I was going to attempt to fix and make a pull request, but I can't seem to find the relevant code anywhere. Am I missing something?

**Comment by dlech** [comment]
Additional change that would be nice while fixing this:

`@exception` and it's aliases `@throw` and `@throws` has one argument that is the exception object.

```
\exception <exception-object> { exception description }
```

It would be nice if the exception object got special highlighting similar to how the name of a `@param` works.

**Comment by sean-mcmanus** [comment]
The C/C++ extension doesn't implement that. You should file an issue at https://github.com/jeff-hykin/better-cpp-syntax/issues (that is pulled into VS Code).

But I don't repro the throws issue with the latest VS Code.

**Comment by dlech** [comment]
Thanks for the info. Looks like it should have been fixed years ago, so not sure why I would be seeing it.

https://github.com/jeff-hykin/better-cpp-syntax/issues/444
