### ISSUE TITLE
Set up path environment variable for debug

### ISSUE THREAD

**Issue by lightgoleft** [microsoft/vscode-cpptools#1078]
Hello, 

I wonder if there is a way to set up path env or dll search path for debug. I have tried additionalSOLibSearchPath in settings.json but it doesn't work. 

Best, 
Hao.

**Comment by pieandcakes** [comment]
@lightgoleft that should be the right command if you are trying to load dlls outside of your workspace during debugging. Which OS/Debugger are you using? Is it `cppvsdbg` type you are trying to debug (Visual C++) or `cppdbg` (GNU C++) ?

Also, if you are just trying to set environment variables (not dll search path), try the `"environment"` tag in your `launch.json`.

**Comment by lightgoleft** [comment]
@pieandcakes It was cppdbg. I used MinGW as compiler and dbg toolset.

**Comment by pieandcakes** [comment]
@lightgoleft Library loads should be in the debugConsole. if you look, does it say it isn't loaded for your library? A common problem is not compiling with `-g` to include debug symbols. Can you confirm that you have compiled with `-g` ?

**Comment by lightgoleft** [comment]
@pieandcakes First thing to clarify, I used CMake Tools extension to build and initiate debugger. Since CMake extension trigger the debugger by generating launch.json, I don't think there is any difference other than debuging in debug tab with a manuscripted json file. 

Back to your question, I did compiled with -g but the symbols were not shown loaded in debug console. My temporary solution is to set cwd as library directory and the symbols are loaded fine.

**Comment by dimztimz** [comment]
I had a project that builds a shared library (with the help of `libtool`) and executable that links to the library. Had trouble to set it up.
First I tried with configuring debugging with `libtool --mode=execute` and pipe launches etc and failed.

Then I found out libtool --mode=execute pretty much sets only LD_LIBRARY_PATH on linux. First tried with additionalSOLibSearchPath and failed. Then I manually set LD_LIBRARY_PATH and that worked.

The thing is, what enviroment variables additionalSOLibSearchPath actually sets? It should set LD_LIBRARY_PATH on Linux.

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
