### ISSUE TITLE
concepts-requires IntelliSense and autocomplete

### ISSUE THREAD

**Issue by rdwnsjjd** [microsoft/vscode-cpptools#10794]
### Feature Request

I don't know this feature is now available in extension, however I didn't find it in existing feature requests.
concepts and requires expression autocomplete are very weak in extension. I want when I have a function with type constraint using `requires`, the extension suggest me available options.
for example:
```c
    template<typename T>
    concept Clone = requires(T t) { t.clone() };

    template<typename T>
      requires Clone<T>
    int test_func(T t) {
        t.clone();
    }
```
this case works fine and when I write `t.` in `test_func`, extension will show me `clone()`.

but just in this case it works.
when I add another `requires` it shows nothing:
```c
    template<typename T>
    concept Clone = requires(T t) { t.clone(); } || requires(T t) { t.copy(); };
```
in this case nothing will be suggested.

in other case:
```c
    template<typename T>
    concept Clone = requires(T t) { { t.clone() } -> std::convertible_to<int>; };
```

it will be good that extension detects `{} -> std::convertible_to<int>` is return type of method and shows it as return type. because all return types for suggested methods (when something will be suggested) are "unnamed".

another case:
```c
    template<typename T>
    concept Clone = requires(T t) { std::is_same_t<T, vector<int>>; };
```

it also will be great that in this case and same cases like this:
```c
    template<typename T>
    concept Clone = std::is_same_t<T, vector<int>>;
```

extension detects type of `T` and suggests methods and members of `vector`.

there are another cases that considering these, makes this extension more powerful and useful for all.

thank you.

**Comment by rdwnsjjd** [comment]
wasn't interesting? :/

**Comment by bobbrow** [comment]
Sorry for the delay in responding to this one.  We were in a crunch mode last week trying to finish some features for 1.15 and got a little behind on issue triage.  We share our IntelliSense code with Visual Studio and we see the same results there.  We'll open a feature request for Visual Studio and when it is implemented it will flow back to VS Code.
