### ISSUE TITLE
Quickfix for missing header file

### ISSUE THREAD

**Issue by m-zellner** [microsoft/vscode-cpptools#10791]
### Feature Request

During development it is cumbersome to add missing header files. There should be a quickfix option on an unknown symbol which adds the corresponding header to the current file.

![quickfix_for_symbolspng](https://user-images.githubusercontent.com/60292507/230771834-3a595c7e-d801-4a00-b71a-5d6b7a3f7838.png)

The languageClient in src/LanguageServer/client.ts can be used to query the symbol information and determine the header location. I already implemented the feature as a draft ;)

**Comment by Mazhar012** [comment]
add include

**Comment by sean-mcmanus** [comment]
@M1Z3 This is available in 1.18.4. Some known issues are https://github.com/microsoft/vscode-cpptools/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature%3A+Add+%27%23include%27%22

**Comment by M1Z3** [comment]
> @M1Z3 This is available in 1.18.4. Some known issues are https://github.com/microsoft/vscode-cpptools/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature%3A+Add+%27%23include%27%22

Thanks for the heads-up :)! I followed the activity on this issue and already tested it on pre-release. It seems to work for system headers 🎉

As far as I can see this https://github.com/microsoft/vscode-cpptools/pull/10792 is not needed anymore. So I'm going to close it 😉
