### ISSUE TITLE
Inconsistent treatment of braces in macros

### ISSUE THREAD

**Issue by SRNissen** [microsoft/vscode-cpptools#10790]
### Environment

- OS and Version: op!_OS 22.04 LTS
- VS Code Version: 1.67.2
- C/C++ Extension Version: 1.14.5

# Bug Summary and Steps to Reproduce

## Summary

Macros with braces confuse the formatter. No similar issues appear to have been reported.

## Steps to reproduce:

**(1) Write the following code**

```c++
    int main(int argc, char **argv)
    {
        if (argc > 1)
            return argc;
        else
            return 0;
    }

    #define START {
    #define END }

    int main(int argc, char **argv)
    START
        if (argc > 1)
            return argc;
        else
            return 0;
    END
    
    START
        START
            START
            END
        END
    END
```

**(2) Activate the formatter**

**(3) Observe changes:**

    01  int main(int argc, char **argv)
    02  {
    03      if (argc > 1)
    04          return argc;
    05      else
    06          return 0;
    07  }
    08  
    09  #define START {
    10  #define END }
    11  
    12  int main(int argc, char **argv)
    13      START
    14      if (argc > 1) return argc;
    15  else return 0;
    16  END
    17  
    18  START
    19      START
    20          START
    21              END
    22                  END
    23                      END

* Line 03-04 - `return argc` is on a separate line from the conditional
* Line 13 -  `START` is indented to the fifth column
* Line 14 - `return argc` has been moved up to the same line as the conditional
* Line 15 - `return 0` has been moved to the same line as the `else` AND
* Line 15 - `else` has moved to the first column
* Line 21 - `END` has been indented by 4 spaces
* Line 22 - `END` has been indented by 12 spaces
* Line 23 - `END` has been indented by 20 spaces

## Expected behavior:

* Line 13 - The indentation of `START` should not have changed
* Line 14 and 15 - the `return` statements should not have been moved
* Line 15 - The indentation of `else` should not have changed
* Lines 21 to 23 - the indentation of `END` should not have changed.

# Configuration and Logs

```shell
Running

    PS /home/srnissen/.config/Code> get-childitem -r *c_cpp_pro*

returns no results so I don't think I have any special configurations here

Diagnostics log:

    -------- Diagnostics - 4/9/2023, 12:27:48 PM
    Version: 1.14.5
    Current Configuration:
    {
        "name": "Linux",
        "includePath": [
            "/home/srnissen/repos/snns/cpp/bird/**"
        ],
        "defines": [],
        "cStandard": "c17",
        "cppStandard": "c++14",
        "intelliSenseMode": "linux-clang-x64",
        "intelliSenseModeIsExplicit": false,
        "cStandardIsExplicit": false,
        "cppStandardIsExplicit": false,
        "mergeConfigurations": false,
        "compilerPath": "/usr/bin/clang",
        "compilerPathIsExplicit": false,
        "browse": {
            "limitSymbolsToIncludedHeaders": true,
            "path": [
                "${workspaceFolder}/**"
            ]
        }
    }
    Translation Unit Mappings:
    [ /home/srnissen/repos/snns/cpp/bird/birdtest1.cpp ]:
        /home/srnissen/repos/snns/cpp/bird/bird.h *
    Translation Unit Configurations:
    [ /home/srnissen/repos/snns/cpp/bird/birdtest1.cpp ]:
        Process ID: 521649
        Memory Usage: 116 MB
        Compiler Path: /usr/bin/clang
        Includes:
            /usr/include/c++
            /usr/lib/llvm-14/lib/clang/14.0.0/include
            /usr/local/include
            /usr/include/x86_64-linux-gnu
            /usr/include
        Standard Version: c++14
        IntelliSense Mode: linux-clang-x64
        Other Flags:
            --clang
            --clang_version=140000
    Total Memory Usage: 116 MB

    ------- Workspace parsing diagnostics -------
    Number of files discovered (not excluded): 10145
    Number of files parsed: 1
```

**Comment by sean-mcmanus** [comment]
It sounds like this is a clang-format issue.

**Comment by SRNissen** [comment]
...possibly? This is without clang-format installed directly, but perhaps your extension uses clang-format internally?

**Comment by sean-mcmanus** [comment]
Yes, by default we use clang-format. You can set "C_Cpp.formatting" to "vcFormat" to change that the vcFormat formatter, which doesn't repro this bug (although it may not give you the results you want for other reasons).

**Comment by SRNissen** [comment]
In that case this issue can be closed - clang-format does indeed similar behavior, which is as-designed (clang-format does not do macro expansion)
