### ISSUE TITLE
Need problem matcher for Google Test

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode-cpptools#1079]
It seems that `Google Test` is pretty much the standard unit test framework for C++ these days.  Could we get a problem matcher for gtest in this extension?

**Comment by bobbrow** [comment]
We don't use it internally here, but if you or someone else watching this thread wants to post some sample output, that would expedite cooking up a regular expression that meets your needs.

[Defining a problem matcher](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher) is fairly easy once you know what the output is supposed to look like so if you or someone else wants to help with that, we would gladly include it in the extension.

**Comment by agauniyal** [comment]
gtest is by no means the standard unit test framework(not even crossed 50% yet), lots of other frameworks have a large number of users. See https://www.jetbrains.com/research/devecosystem-2017/cpp/ for more details. That said, having a matcher for gtest would be welcomed addition but I think the right way would to use XML output that gtest produces and mark the code(individual tests) as failing or passing inside the editor as well. Several IDEs already do that :p

**Comment by kkaja123** [comment]
Here's a sample output:
```
[ RUN      ] TestSuite.TestCase1
[       OK ] TestSuite.TestCase1(0 ms)
[ RUN      ] TestSuite.TestCase2
C:\file\path\TestFile.cpp:547: Failure
Actual function call count doesn't match EXPECT_CALL(observer, HandleFunction(&argument))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] TestSuite.TestCase2(32 ms)
[ RUN      ] TestSuite.TestCase3
[       OK ] TestSuite.TestCase3(0 ms)
```

I've tried creating a problem matcher for this but I can't seem to get it right:
```
"problemMatcher": {
  "base": "$gcc",
  "owner": "cpp",
  "fileLocation": [
    "absolute"
  ],
  "pattern": [
    {
      "regexp": "^(.*):(\\d+):\\s+(Failure)$",
      "file": 1,
      "line": 2,
      "message": 3,
    }
  ]
}
```
or for multiline capturing:
```
"problemMatcher": {
  "base": "$gcc",
  "owner": "cpp",
  "fileLocation": [
    "absolute"
  ],
  "pattern": [
    {
      "regexp": "^(.*):(\\d+):\\s+(Failure)$",
      "file": 1,
      "line": 2,
      "severity": 3,
    },
    {
      "regexp": "^(?!\\[).*$",
      "message": 1,
      "loop": true,
    }
  ]
}
```
https://regex101.com/r/QbYxwf/1 shows that the main regex should be correct, but I don't see any problems generated after running the task.

**Comment by bobbrow** [comment]
Thank you for the feature suggestion.  There are a few Google Test extensions available for VS Code now, and we believe that adding a problem matcher to those extensions is the better route.
