### ISSUE TITLE
Removal of compilerPath, compileCommands, or configurationProvider settings/properties doesn't update the "Configure IntelliSense" UI

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10807]
i.e. re-adding it if it should.

The pre-requisite is to get the "Configure IntelliSense" status bar UI to appear, i.e. if no trusted compiler is installed.

Then do something to cause the Configure IntelliSense status bar UI to go away that also sets the compilerPath, compileCommands, or configurationProvider settings, but also doesn't add a trusted compiler to the current sessions.

The bug is that the removal of the compilerPath, compileCommands, or configurationProvider settings doesn't re-trigger the check to whether the Configure IntelliSense status bar UI should re-appear if there is still no trusted compiler available after the deletion of that setting.

**Comment by michelleangela** [comment]
Issue doesn't reproduce. Perhaps it got fixed? 

Are these the repro steps to reproduce it?
1. Create c_cpp_properties.json with default values by running `Edit Configuration (JSON)`.
2. Add properties `compilerPath`, `compileCommands`, and `configurationProvider` to c_cpp_properties.json.
3. Open the configuration UI by running `Edit Configuration (UI)`.
4. Go back to c_cpp_properties.json and remove properties `compilerPath`, `compileCommands`, and `configurationProvider`.
5. Go back to configuration UI and see corresponding properties are empty.

**Comment by bobbrow** [comment]
Closing lower priority issue with no upvotes
