### ISSUE TITLE
Selecting a compiler from "Select IntelliSense Configuration" doesn't update the compilerPath in c_cpp_properties.json

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10808]
It probably should. It currently will just update the C_Cpp.default.compilerPath, but the existence of compilerPath in c_cpp_properties.json causes the C_Cpp.default.compilerPath to not be used.

**Comment by michelleangela** [comment]
Pending to discuss the expected behavior of running "Select IntelliSense Configuration" when `compilerPath` in c_cpp_properties.json exists.

**Comment by michelleangela** [comment]
Discussed with @AlexandraKemperMS .

The command "Select IntelliSense Configuration" should change both `compilerPath` (if it exists) in c_cpp_properties.json and the `C_Cpp.default.compilerPath`.

**Comment by sean-mcmanus** [comment]
@michelleangela That sounds fine to me.

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.1.
