### ISSUE TITLE
Debug point not being hit

### ISSUE THREAD

**Issue by shagunsodhani** [microsoft/vscode-cpptools#1080]
OS: macOS Sierra
VS Code version: 1.16.1
C/C++: 0.13

I am running a multi-threaded code. When I run the code in the debug mode, no breakpoint is hit. I have set up the breakpoint at the first statement of the `main` function.

This is the output of `DEBUG_CONSOLE`

`For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
=cmd-param-changed,param="startup-with-shell",value="off"
=cmd-param-changed,param="pagination",value="off"
[New Thread 0x1403 of process 30157]
Thread 2 hit Breakpoint 1, 0x0000000100003984 in main ()`

This does mention that the breakpoint is hit but I do not see it in the debugger. Also, the first breakpoint is the first line of the `main` function.

My `launch.json` file is as follows:

```
{
        "version": "0.2.0",
        "configurations": [
            {
                "name": "foobar",
                "type": "cppdbg",
                "request": "launch",
                "program": "${workspaceRoot}/foobar",
                "args": [],
                "stopAtEntry": false,
                "cwd": "${workspaceRoot}",
                "environment": [],
                "externalConsole": false,
                "MIMode": "gdb",
                "preLaunchTask": "build foobar"
                // "logging": {
                    // "programOutput": false
                // }
            }
        ]
    }
```

**Comment by pieandcakes** [comment]
@shagunsodhani Can you confirm you compiled with the `-g` flag to enable symbols? If not, debugging will not work. Also, did you mean to use `gdb` and not `lldb` on MacOS?

**Comment by shagunsodhani** [comment]
@pieandcakes I am fine with both `gdb` and `lldb`. Its just that I have used `gdb` in the past so I installed that. Regarding the `-g` symbol, no I had not added that. I added the `-g` symbol and it worked like a charm. Thank you very much.
