### ISSUE TITLE
List members when input dot(.) after an iterator (or any type that overrides operator->)

### ISSUE THREAD

**Issue by FlyinCow** [microsoft/vscode-cpptools#10818]
### Feature Request

When input a member access operator `.` after a native pointer :
```cpp
struct S {
  int id;
  int data;
};

S* p;

p.// IntelliSense engine will offer its members
```
like this:
![image](https://user-images.githubusercontent.com/23637371/231702047-b93090e3-6ac4-4866-8fa1-786c2d0724e8.png)

After hit Tab it will be auto converted into `p->data`.

This feature is great so is it possible to have it too on an iterator or any type that overrides operator->?

**Comment by browntarik** [comment]
Thank you for your request. If you are able to get more upvotes on this issue, it will raise the priority of the Feature Request and you may see it implemented sooner.
