### ISSUE TITLE
Intellisense gives incorrect results

### ISSUE THREAD

**Issue by omern1** [microsoft/vscode-cpptools#1081]
VS Code 1.17.0-insider
macOS 10.13
vscode-cpptools Version 0.13.0: September 25, 2017

Trying to get intellisense shows incorrect data and sometimes only shows tag parser results.

**Comment by sean-mcmanus** [comment]
What feature exactly? Autocomplete?

**Comment by omern1** [comment]
@sean-mcmanus yes
