### ISSUE TITLE
Can't debug multi exe in one extended-remote target

### ISSUE THREAD

**Issue by fbs2016** [microsoft/vscode-cpptools#10817]
### Environment

Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:20:37.202Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-35-generic
Sandboxed: No
Gdb: 12.1

### Bug Summary and Steps to Reproduce

Steps to reproduce:
1. Start gdbserver with multi mode on remote target: gdbserver --multi :23456, that I run the target on QEMU
2. Debug the exe1 from VSC on localhost, set extended-remote as true in launch configuration, and break on some line;
3. Debug the exe2 from the same VSC and same configuration with exe1, set some bp on it. The debug totally corrupt.

If try on linux host not in QEMU, the gdb connection with extended-remote will timeout if try 2 connection in 2 gdb client.
I guess gdbserver multi mode don't support multi gdb connection, and QEMU can work maybe due to QEMU proxy transfer.

### Debugger Configurations

```shell
None
```

### Debugger Logs

```shell
None
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
