### ISSUE TITLE
Extension does not correctly deal with "no-break" whitespace chars (0xA0)

### ISSUE THREAD

**Issue by omern1** [microsoft/vscode-cpptools#1082]
VS Code 1.17.0-insider
macOS 10.13
vscode-cpptools Version 0.13.0: September 25, 2017

Pressing `option + shift + F` to format the document ADDS strange values to the source file.

This:
```cpp
#pragma once
// https://github.com/antlr/grammars-v4/blob/master/lua/Lua.g4
namespace AST
{
class Block;

class VariableList
{
};
```
Changed to:
```cpp
#pragma once
//  : his e::e;

{   c a   B oc : x * > bl  = e fret rn h : h : (t
 la s Bl  k;         B oc

ceas
}l
k)lckeblebl
```

**Comment by sean-mcmanus** [comment]
I'm not able to repro this. Is there some other requirement? Another user has reported corruption after formatting too. If this is a 0.13.0 regression, you could try using http://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools/0.12.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage (renaming the zip to vsix and using the Install from vsix command). Let us know if 0.12.4 has this problem too.

**Comment by bobbrow** [comment]
Just a hunch based on the corruption... I'm wondering if your second line has a "no-break" space char (0xA0) instead of a regular space char (0x20).  If you still have the original code file, can you try deleting that second line or just the whitespace on it and see if you still get garbage results?

**Comment by omern1** [comment]
@bobbrow You were right, it works fine after deleting that space, I don't know how it got there though.
Seems like both the issues (#1081 and this) I filed are resolved. For now at least.

**Comment by bobbrow** [comment]
I want to leave this issue open if you don't mind.  We shouldn't mess up your code when these types of spaces are encountered and we can use this issue to track fixing that bug in our extension.

**Comment by omern1** [comment]
@bobbrow Yeah, sure. I'm more concerned about how that got there, I just press space on my keyboard to add spaces. Is it there smart spaces kind of thing in VS Code?

**Comment by bobbrow** [comment]
Did you copy/paste the URL from somewhere?  My thought was that maybe you happened to grab one of those characters when you selected the URL from some web page.  I believe this character is the browser's representation of `&nbsp;`

**Comment by omern1** [comment]
I did copy that URL, but that comment has been there ever since I started working on that file and everything was fine till about 4 or 5 days ago.

**Comment by bobbrow** [comment]
¯\\\_(ツ)\_/¯
😄

**Comment by omern1** [comment]
@bobbrow So something is really wrong, because its now again corrupting the file and this time there are no special characters.

**Comment by omern1** [comment]
The files which don't get corrupted are not getting formatted either.

**Comment by sean-mcmanus** [comment]
How does the corruption occur or first get noticed?

**Comment by pbnjay** [comment]
Sounds like the same as mine. I've reverted to 0.12.4 that you posted and will report if I see more issues.

**Comment by bobbrow** [comment]
We're going to use #1073 as the tracking issue for this.
