### ISSUE TITLE
"Configure IntelliSense" warning shows up in non-c++ folders if C++ extension gets activated

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#10827]
**Summary:**
The warning "Configure IntelliSense" shows up for folders that have no C++ files if the C++ extension gets activated.

**Repro steps:**
1. Ensure there is no default C++ IntelliSense configuration set under the user scope setting.
2. Open a folder that have no C++ files, like a Typescript project.
3. Open Walkthrough page for C++ extension.
4. Close walkthrough.
5. Observe "Configure IntelliSense" is on the status bar.

**Expected behavior:**
 "Configure IntelliSense" warning should only show up for workspaces with C++ files even if C++ extension gets activated.

**Comment by sean-mcmanus** [comment]
FYI, it goes away after a non-C++ is activated. I think I just need to add a check.
