### ISSUE TITLE
Support cross-compilation configurations for IntelliSense

### ISSUE THREAD

**Issue by jfroy** [microsoft/vscode-cpptools#1083]
I am sometimes working on my project using a cross-compilation toolchain (for example, working on a Mac laptop; the project targets Linux). I tried to configure IntelliSense to only search the project and the cross-compilation sysroot. But I got this error:

```
file: 'file:///<redacted>.cc'
severity: 'Info'
message: 'cannot open source file "Availability.h" (dependency of "<redacted>.h")'
at: '1,1'
source: ''
```

This is of course a macOS header. I am guessing the indexer might be scanning hard-coded host paths. It seems likely that to properly support cross-compilation, there would need to be a sysroot parameter to act as a final catch-all.

**Comment by sean-mcmanus** [comment]
What is the configuration you're using in c_cpp_properties.json? It sounds like it may be using the macFrameworkPath. We don't scan any hard-coded host paths that aren't in the c_cpp_properties.json.

**Comment by jfroy** [comment]
This is my c_cpp_properties.json, with minor edits for confidentiality.

```json
{
    "configurations": [
        {
            "name": "Foo",
            "includePath": [
                "${workspaceRoot}",
                "${workspaceRoot}/build/vscode/gen",
                "${workspaceRoot}/build/vscode/GLog-prefix/install/include",
                "${workspaceRoot}/third_party/gflags/include/linux",
                "${workspaceRoot}/third_party/googletest/googletest/include",
                "${workspaceRoot}/third_party/protobuf/src",
                "${workspaceRoot}/tools/sdk/toolchain/include/c++/v1",
                "${workspaceRoot}/tools/sdk/toolchain/lib/clang/4.0.1/include",
                "${workspaceRoot}/tools/sdk/sysroot/usr/include",
                "${workspaceRoot}/tools/sdk/sysroot/usr/include/x86_64-linux-gnu"
            ],
            "defines": [
            ],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "${workspaceRoot}/build/vscode/gen",
                    "${workspaceRoot}/build/vscode/GLog-prefix/install/include",
                    "${workspaceRoot}/third_party/gflags/include/linux",
                    "${workspaceRoot}/third_party/googletest/googletest/include",
                    "${workspaceRoot}/third_party/protobuf/src",
                    "${workspaceRoot}/tools/sdk/toolchain/include/c++/v1",
                    "${workspaceRoot}/tools/sdk/toolchain/lib/clang/4.0.1/include",
                    "${workspaceRoot}/tools/sdk/sysroot/usr/include",
                    "${workspaceRoot}/tools/sdk/sysroot/usr/include/x86_64-linux-gnu"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```

Using VSCode 1.17.0 (1.17.0), ms-vscode.cpptools 0.13.1

**Comment by llatta** [comment]
I'm running into the same issue, cross compiling emscripten code from a Mac. It seems to be caused by some headers doing some 
```
#ifdef __APPLE__
#include <SomeMacSpecificHeader.h> // error: file can't be found in Intellisense session, because no Mac specific include paths in my config
```
If I manually add `#undef __APPLE__
`at the top of my source file, the intellisense errors go away. Of course modifying the source in this way is ugly. Is there a way to add this to the config options for the plugin? Either something to allow undefining options, or maybe an option for preventing whatever default defines the intellisense engine adds?

**Comment by jfroy** [comment]
Ah, this good insight. The setting we may be missing the clang's -target. If we could specify that for the indexer, then we could convey the target platform and all the relevant compiler built-in defines would be set correctly.

**Comment by sean-mcmanus** [comment]
You can use `clang -v -E -x c++ - < /dev/null` to see what includePath/defines you should use, but we don't currently have a way to remove defines that are hard-coded (they're currently built into the mac binary), but I think we eventually plan to make this configurable.

**Comment by bobbrow** [comment]
I think @llatta nailed it.  IntelliSense built for Mac always has `__APPLE__` defined.  The engine API doesn't currently give us an option for changing the target.  I'll need to ask for it.

**Comment by rizickus** [comment]
Is there any progress regarding this issue?

**Comment by sean-mcmanus** [comment]
@rizickus No progress has been made on this, but we just need to change the compile-time Linux/Mac defines to be based on some new setting. In regards to _WIN32, that should stop being defined when you change the intelliSenseMode to "clang-x64" -- do you use a cl.exe or gcc/clang when _WIN32 shouldn't be defined? Or make intelliSenseMode have more possible values for all the compiler/OS combinations.

**Comment by rizickus** [comment]
Yes, changing to "clang-x64" removed _WIN32 define, thanks! I am using armclang.

**Comment by cody-greene** [comment]
Is there an issue# on the main vscode repo for for this option that I can track? And possibly help with? I'd love to use vscode + mingw to cross compile for windows from mac/linux.

**Comment by sean-mcmanus** [comment]
@cody-greene The main vscode repo wouldn't be tracking this issue, because it's a C++ extension issue. The TODO work is on our closed-source side so there's nothing you could help with. We support cross-compilation in general via setting the compilerPath/intelliSenseMode, but there are just a bunch of hardcoded defines, mostly regarding Mac that can't be changed yet (using forcedInclude to do #undef might be a workaround).

**Comment by koutheir** [comment]
Without fixing this issue, working in VSCode with cross device projects is not an option, as devices usually have different operating systems and architecture than the development computer. So VSCode for embedded programming? nope...

**Comment by koutheir** [comment]
For the moment, I found an ugly hack to work around the issue of hard-coded preprocessor defines.

I created a file `vscode-fake.h` whose contents is something like the following:
```
#undef __linux__
#undef __x86_64__
```

Then I added the following to the `c_cpp_properties.json` file:
```
"forcedInclude": [ "${workspaceFolder}/vscode-fake.h" ],
```

Of course `vscode-fake.h` is not actually included by the sources files when building. It is only there to correct the wrong assumptions of VSCode.

**Comment by koutheir** [comment]
**Could someone list all hard-coded preprocessor defines in VSCode?** This would enable a complete specification of the `vscode-fake.h` file previously mentioned.

**Comment by sean-mcmanus** [comment]
@koutheir Here's the list, but I noticed some of them are defined by the C++ language and some are internal to our compiler, so undefining them could break stuff, etc., so you should probably only undefine things you really know you don't want.
```
#undef unix
#undef __ARRAY_OF_OPERATORS
#undef __BASE_FILE__
#undef __builtin_va_list
#undef __CHAR16_TYPE__
#undef __CHAR32_TYPE__
#undef __clang__
#undef __clang_major__
#undef __clang_minor__
#undef __clang_patchlevel__
#undef __COUNTER__
#undef __cplusplus
#undef __cpp_aggregate_nsdmi
#undef __cpp_alias_templates
#undef __cpp_aligned_new
#undef __cpp_attributes
#undef __cpp_binary_literals
#undef __cpp_capture_star_this
#undef __cpp_constexpr
#undef __cpp_decltype
#undef __cpp_decltype_auto
#undef __cpp_delegating_constructors
#undef __cpp_enumerator_attributes
#undef __cpp_exceptions
#undef __cpp_fold_expressions
#undef __cpp_generic_lambdas
#undef __cpp_hex_float
#undef __cpp_if_constexpr
#undef __cpp_inheriting_constructors
#undef __cpp_init_captures
#undef __cpp_initializer_lists
#undef __cpp_inline_variables
#undef __cpp_lambdas
#undef __cpp_namespace_definitions
#undef __cpp_noexcept_template_args
#undef __cpp_nsdmi
#undef __cpp_range_based_for
#undef __cpp_raw_strings
#undef __cpp_ref_qualifiers
#undef __cpp_return_type_deduction
#undef __cpp_rtti
#undef __cpp_rvalue_references
#undef __cpp_sized_deallocation
#undef __cpp_static_assert
#undef __cpp_structured_bindings
#undef __cpp_unicode_characters
#undef __cpp_unicode_literals
#undef __cpp_user_defined_literals
#undef __cpp_variable_templates
#undef __cpp_variadic_templates
#undef __DATE__
#undef __EDG__
#undef __EDG_CONSTEXPR_ENABLED__
#undef __EDG_PTRDIFF_TYPE__
#undef __EDG_RUNTIME_USERS_NAMESPACES
#undef __EDG_SIZE_TYPE__
#undef __EDG_TYPE_TRAITS_ENABLED
#undef __EDG_VERSION__
#undef __event
#undef __EXCEPTIONS
#undef __FILE__
#undef __GNUC_STDC_INLINE
#undef __GXX_RTTI
#undef __has_attribute
#undef __has_builtin
#undef __has_extension
#undef __has_feature
#undef __has_include
#undef __has_include_next
#undef __hook
#undef __INTELLISENSE__
#undef __LINE__
#undef __linux__
#undef __make_integer_seq
#undef __PLACEMENT_DELETE
#undef __PRAGMA_REDEFINE_EXTNAME
#undef __PTRDIFF_TYPE__
#undef __raise
#undef __RTTI
#undef __SIGNED_CHARS__
#undef __SIZE_TYPE__
#undef __STDC__
#undef __STDC_HOSTED__
#undef __STDCPP_DEFAULT_NEW_ALIGNMENT__
#undef __STDCPP_THREADS__
#undef __TIME__
#undef __TIMESTAMP__
#undef __unhook
#undef __unix__
#undef __var_list_tag
#undef __VARIDIC_TEMPLATES
#undef __WCHAR_TYPE__
#undef __x86_64
#undef __x86_64__
#undef _EDG_COMPILER
#undef _GNU_SOURCE
#undef _HAS_CHAR16_T_LANGUAGE_SUPPORT
#undef _Pragma
#undef _USE_DECLSPECS_FOR_SAL
```

You can see the list via setting the compilerPath to "" and then invoking autocompletion in a file with no #include.

Also, it looks like undefining works for squiggles, but other parts of our code like autocomplete still treat the variables as being defined.

**Comment by koutheir** [comment]
> but other parts of our code like autocomplete still treat the variables as being defined.

Yeah, this is really an ugly hack. It has to be fixed correctly for VSCode to make sense for embedded and cross-platform development.

**Comment by tthrift** [comment]
Any progress toward target independence/cross compilation on the Mac side?

**Comment by sean-mcmanus** [comment]
@tthrift Unfortunately, no work has been done on this yet and it's not currently on our short-term schedule, but it seems like something we would want to fix eventually.

**Comment by bneff** [comment]
+1 . Also looking to do cross compilation using VSCode

**Comment by jazzmx** [comment]
+1 !!

**Comment by astei** [comment]
I would very much like this so that I can use this extension to do OS development within Visual Studio Code more effectively (cross-compiling from macOS/Ubuntu with a freestanding compiler). I can work without it but I appreciate having feedback as I work.

**Comment by aenima1891** [comment]
+1!!!!

**Comment by bobbrow** [comment]
Please upvote this issue by clicking the thumbs up on the original post.  +1 comments don't get added to the vote count correctly.

**Comment by Donpampa** [comment]
I would upvote it more then once if it was possible :-)
+1

**Comment by Machinegon** [comment]
+1 please, I had pulled off some tweaks to make it work but it doesn't anymore.

**Comment by rosek86** [comment]
Hi,

When compileCommands is defined the vscode-fake hack doesn't seem to work on Mac, to fix IntelliSense errors I had to remove compileCommands, manually specify include paths and forcedInclude vscode-fake.h file.

My vscode-fake looks like this:
```c
#ifndef VSCODE_FAKE_H__
#define VSCODE_FAKE_H__

#undef __APPLE__ 

#endif // VSCODE_FAKE_H__
```

**Comment by saileshs** [comment]
+1 Please!!

**Comment by MonaTheMonad** [comment]
`#defines` aside, which actually takes precedence? The system header paths in `includePath` (e.g. of a standalone sysroot for cross compilation), or what the extension thinks are my system header directories?

**Comment by sean-mcmanus** [comment]
@MonaTheMonad You can run C/C++: Log Diagnostics to see the final includePath ordering we use (the precendence/ordering we use could change for various reasons). If you set your compilerPath to be "" , then we should not be adding any local system headers into the includePath. You can also try setting C_Cpp.default.systemIncludePath (The value to use for the system include path. If set, it overrides the system include path acquired via "compilerPath" and "compileCommands" settings.).

**Comment by MonaTheMonad** [comment]
If I instead put the sysroot's header paths in `includePath`, as if it were just a regular set of library headers, would IntelliSense be intelligent enough to sense extra stuff in the sysroot's standard library headers that my system's standard library headers do not have? Namely, for example, if my sysroot's `vector` class in `<vector>`, for whatever hypothetical reason, has an extra member function `shuffle()`, would it skip over the default `<vector>` header and detect the custom one that has that declaration?

**Comment by sean-mcmanus** [comment]
No, putting sysroot headers in the includePath will not cause all the other system includes to be added in the correct orders by our extension, hence the breakage that can occur.

If you have some custom vector file that you want to be used, it's path would need to appear first in the include path list that is output with C/C++: Log Diagnostics.

**Comment by bigbrett** [comment]
Oh my god +1 this issue please this has been driving me crazy

**Comment by fincs** [comment]
I almost exclusively use vscode in cross compilation scenarios. In the platform I target `sizeof(long) == 8`, however since my development machine happens to run Windows it's convinced that `sizeof(long) == 4`. As a result I've also had to use a forced include file to redefine standard types (uint64_t, size_t) to use long long instead of long; which also breaks other things that don't rely on these types. This issue has been extremely annoying throughout my development time.

**Comment by TuxSH** [comment]
The same issue leads to having squiggles when using string_view literals: "Type of 2nd parameter invalid (unsigned long) ... must be size_t" (have to undefine `__SIZE_TYPE__` with forcedInclude first)

**Comment by ce3a** [comment]
+1 !!!!

**Comment by icegood** [comment]
any news regarding this issue?

**Comment by sean-mcmanus** [comment]
@icegood Yeah, it's being worked on for the next release. We'll post an update here when it's available to try in an insiders release.

**Comment by zakkie** [comment]
I'm working on a project that targets embedded systems.
- working on Macbook Pro
- target system: Arduino (tiny ARM board)

#6745 added definitions for Linux, macOS, WIndows, but no other definitions.

I think it would be nice to have a option that allows users to define their own settings for a particular system without automatically adding them. (like `"intelliSenseMode": "bare"`)

**Comment by icegood** [comment]
Just checked and it seems to work as expected. 
One more question: my project is cmake-based and contains custom third party libraries that provide custom header paths. Is it possible to propagate these paths from "CMake Tools" plugin to vscode-cpptools to make search/highlight correct? Or all we can do is to manually add all these extra headers?

**Comment by sean-mcmanus** [comment]
@icegood The PR at https://github.com/microsoft/vscode-cpptools/pull/6823/files enables cpptools to consume the new IntelliSense modes, but CMake-Tools hasn't been changed yet to send them. Is that what you're referring to? The existing releases should already support configuring IntelliSense includes/defines from CMake-Tools, but it's just the cross-compilation that is new.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 (although there are some related TODOs, such as https://github.com/microsoft/vscode-cpptools/pull/6823/files mentioned earlier).

**Comment by pablojrl123** [comment]
The new IntelliSense modes that specify a  platform seem to work as intended. However, the "generic" ones (those that specify only <compiler>-<architecture>) seem to still add definitions. For example, in my case, the 'gcc-arm' mode still defines '__linux__'. Is this the intended behavior?

**Comment by pablojrl123** [comment]
The new IntelliSense modes that specify a platform seem to work as intended. However, the "generic" ones (those that specify only compiler-architecture) seem to still add definitions. For example, in my case, the 'gcc-arm' mode still defines '\_\_linux\_\_' and '\_\_unix\_\_'. In other words, on my linux box, 'gcc-arm' is that same as 'linux-gcc-arm'. Is this the intended behavior?

**Comment by bobbrow** [comment]
Yes, the old ("generic") enum values always implicitly add the platform based on your host OS.  So if you use the extension on linux with 'gcc-arm', we will promote that to 'linux-gcc-arm'.  The new enum values allow you to target other platforms.

**Comment by sean-mcmanus** [comment]
@pablojrl123 See https://github.com/microsoft/vscode-cpptools/issues/6813
