### ISSUE TITLE
"build finished with warning(s)." whenever compiling a file whose filename contains "warnings" using build task when building with cmake

### ISSUE THREAD

**Issue by Longhanks** [microsoft/vscode-cpptools#10833]
### Environment

- OS and Version: Any, Linux g++ and Windows cl.exe tested
- VS Code Version: latest, any
- C/C++ Extension Version: 1.14.5

### Bug Summary and Steps to Reproduce

**Bug Summary**: When using a build task to compile a C++ project where a file is called e.g. `warnings.cpp`, the extension prints the build summary "build finished with warning(s)." despite there no being any warnings.

**Steps to reproduce:**

[test.zip](https://github.com/microsoft/vscode-cpptools/files/11263235/test.zip)

1. Download attached sample project and VS Code configuration
  - `test/CMakeLists.txt`
  - `test/CMakePresets.json`
  - `test/.vscode/tasks.json`
  - `test/warnings.cpp`
3. Use VS Code with vscode-cpptools and vscode-cmake-tools to open the directory.
4. Run command "CMake: Select build preset" and select x64-debug
5. Run command "CMake: Configure"
6. Run command "Tasks: Run Build task"

**Expected behavior:**

Windows:
```
 *  Executing task: build 

build task started....
"C:\Program Files\CMake\bin\cmake.EXE" --build C:/Users/aschulz/Desktop/test/out/build/x64-Debug-win --target test
[1/2] Building CXX object CMakeFiles\test.dir\warnings.cpp.obj
[2/2] Linking CXX executable test.exe
build finished successfully.
```

Linux:
```
 *  Executing task: build 

build task started....
/usr/local/bin/cmake --build /home/aschulz/Desktop/test/out/build/x64-Debug-linux --target test
[ 50%] Building CXX object CMakeFiles/test.dir/warnings.cpp.o
[100%] Linking CXX executable test
[100%] Built target test
build finished successfully.
```

**Actual output:**

Windows:
```
 *  Executing task: build 

build task started....
"C:\Program Files\CMake\bin\cmake.EXE" --build C:/Users/aschulz/Desktop/test/out/build/x64-Debug-win --target test
[1/2] Building CXX object CMakeFiles\test.dir\warnings.cpp.obj
[2/2] Linking CXX executable test.exe
build finished with warning(s).
```

Linux:
```
 *  Executing task: build 

build task started....
/usr/local/bin/cmake --build /home/aschulz/schulz/Desktop/test/out/build/x64-Debug-linux  --target test
[ 50%] Building CXX object CMakeFiles/test.dir/warnings.cpp.o
[100%] Linking CXX executable test
[100%] Built target test
build finished with warning(s).
```

### Configuration and Logs

```shell
No c_cpp_properties.json used.



-------- Diagnostics - 4/18/2023, 4:54:53 PM
Version: 1.14.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/aschulz/Desktop/test/**"
    ],
    "defines": [],
    "cStandard": "c17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPath": "/usr/bin/gcc",
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "${workspaceFolder}/**"
        ]
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/home/schulz/Desktop/test"
    ],
    "compilerPath": "/usr/bin/g++",
    "compilerArgs": [],
    "compilerFragments": []
}
No active translation units.

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3578
Number of files parsed: 3
```

### Other Extensions

vscode-cmake-tools

**Comment by sean-mcmanus** [comment]
This is caused by code at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/cppBuildTaskProvider.ts#L481 if anyone sees a way to fix it.

From looking at that implementation, I'm not sure how it could happening, and I'm unable to repro it so far.

**Comment by sean-mcmanus** [comment]
I believe it's caused by the usage of cmake to build instead of gcc/cl.exe directly. The code checks for output that it expects to be gcc/cl output and not cmake output.

**Comment by Longhanks** [comment]
> I believe it's caused by the usage of cmake to build instead of gcc/cl.exe directly. The code checks for output that it expects to be gcc/cl output and not cmake output.

Does this mean using anything other than plain cl/gcc in a build task in tasks.json is essentially unsupported?

Or which specific output of CMake is to blame for the occurrence of the "finished with warning(s)" line? I can’t find "waning: C" in the above logs and I am sadly not proficient in TypeScript to analyse the call stack of the linked line that prints the "finished with waning(s)".

But thank you for your work so far.

**Comment by Longhanks** [comment]
> FYI, the CMake Tools extension has its own build mechanism which is recommended to be used instead of the cppbuild tasks.json mechanism, which wasn't designed to support building with cmake.

This is true and thanks for the advice, but the CMake build mechanism puts output to the "Output" panel in VS Code, which does not support ansi color. Building with tasks is explicitly supported and since tasks run in the terminal, there is color support. Also, the language-agnostic keyboarding for "Tasks: Run default build task" can be used with this approach.

**Comment by sean-mcmanus** [comment]
We only tested the cppbuild task with gcc/clang/cl compilers so cmake.exe is unsupported in that regard. I think it's caused by this conditional check `(!stdout && stderr)` being true so the fix might be to skip that check if cmake is being used.

**Comment by sean-mcmanus** [comment]
Ah, okay -- I thought your tasks.json had an explicit command assumed to cmake.exe. Yeah, looks like a CMake Tools bug -- I could move this issue there if you have not already created an issue.

**Comment by Longhanks** [comment]
Thanks! I already filed an issue at vscode-cmake-tools, and it looks like they’re looking into it 😃

https://github.com/microsoft/vscode-cmake-tools/issues/3118
