### ISSUE TITLE
[Feature Request] Resolve CTRL clicks for identifiers that are defined 2+ base classes up

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#1084]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---

cpptools|ms-|0.13.0

Please see the attached project.  When an inheritance identifier that doesn't exist in the parent class but is defined in the parent class' parent, ctrl clicking does not resolve all the way up until it finds an identifier.  I believe this is part of the C++ inheritance spec but you may want to double verify that.
[test.zip](https://github.com/Microsoft/vscode/files/1346857/test.zip)

Note: This seems to work in Visual Studio 2013

**Comment by bobbrow** [comment]
In the sample you provided, Class1 has no members and does not inherit from Class0.  Am I missing something?

Inlining the code below for us to comment on:

```
class Class0
{
public:
    struct STRUCT
    {};
};

class Class1
{
public:
    //struct STRUCT : Class0::STRUCT
    //{};
};

class Class2
{
public:
    struct STRUCT : Class1::STRUCT  // <-- squiggle here
    {};
};
```

If I make Class1 derive from Class0, then the squiggle goes away, but CTL+click navigation for Class1::STRUCT doesn't work.  Is this the issue you are requesting that we fix?

**Comment by azydevelopment** [comment]
Oh what? How did I mess that up. I tested in VS2013 so I must have copied wrong. The intent is that class2 inherits from class1 which inherits from class0. Also that the structs inherit in the same manner. If struct 1 doesnt exist, I believe class2::struct should still be able to reaolve up to class0::struct *even if* class2::struct inherits from class1::struct, a seemingly nonexistent thing.

**Comment by azydevelopment** [comment]
It's intended to be the below. I can confirm that when I paste this into VSCode that ctrl+clicking on Class1::STRUCT at the bottom in Class2 it does not go up the inheritance chain and find Class0::STRUCT.

Copied and pasted into VS2013 as well and it does work there.

Admittedly, I can't tell for 100% certain if this is fully within standard C++ spec. I think it is but it could be a VC++ specific inheritance behaviour; I somewhat doubt that though.

```
class Class0
{
public:
    struct STRUCT
    {};
};

class Class1 : public Class0
{
public:
    //struct STRUCT : Class0::STRUCT
    //{};
};

class Class2 : public Class1
{
public:
    struct STRUCT : Class1::STRUCT  // <-- squiggle here
    {};
};
```

**Comment by bobbrow** [comment]
This appears to work as expected with the latest version of the extension.  If you are still seeing issues, please let us know.
