### ISSUE TITLE
Add support for C++ modules IFC version 0.43

### ISSUE THREAD

**Issue by smilediver** [microsoft/vscode-cpptools#10843]
### Environment

- OS and Version: Windows 22621.1555
- VS Code Version: 1.77.3
- C/C++ Extension Version: v1.14.5

### Bug Summary and Steps to Reproduce

Same issue as in #9884, just for new IFC version 0.43

### Configuration and Logs

```shell
-
```

**Comment by sean-mcmanus** [comment]
VS hasn't added this support yet, so we'll get this soon after they add it.

**Comment by bobbrow** [comment]
Are you reporting a problem with VS or VS Code?  Please note that modules are not officially supported in VS Code.

VS should be able to deal with the difference between 0.42 in IntelliSense and 0.43 in the compiler because it manages the modules in a special way.  But still, the modules support in IntelliSense for VS has a ways to go.  We should be getting the 0.43 update from EDG this month and hopefully other fixes.

**Comment by MathiasMagnus** [comment]
@bobbrow I am working in VS Code.

- Latest VS Code
- Latest cpptools
- Latest cmake-tools
- Latest CMake
- Latest MSVC Build Tools
- Project uses CMake presets and Ninja Multi-Config

If it's not officially supported, than please disregard my comment on release schedules. I am developing a C API wrapper in C++23 and I was looking to maybe not just develop as an ordinary header _then_ wrap it with a module interface, but perhaps also develop it as a module with IntelliSense. I guess the tooling isn't there yet and it wasn't just CMake 3.28 that needed landing but we also need to wait a few cpptools releases.

**Comment by sean-mcmanus** [comment]
@smilediver Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.20.0

**Comment by GGsrvg** [comment]
I created a project for testing modules https://github.com/GGsrvg/tModule.

It works, but IntelliSense shows me an error like "could not find module file for module "ttt.Anchor"C/C++""
These errors are confusing
Clean and rebuild didn't help

VSCode: 1.87.2
Extensions
C/C++: 1.20.0 (pre-release)
CMakeTools: 1.18.15 (pre-release)

Clang: 17.0.6

<img width="420" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/29120457/8376c5fe-60d3-465c-9996-8c9e8aab76ee">

**Comment by bobbrow** [comment]
@GGsrvg, we don't have full modules support in the C++ extension yet. It is being tracked with issue #6302. It is possible to get it working with some caveats, but it requires the Visual Studio compiler right now. A guide to configuring can be found here: https://github.com/microsoft/vscode-cpptools/issues/6302#issuecomment-1930791901

**Comment by GGsrvg** [comment]
@bobbrow thanks for your comment. Oh I use mac
