### ISSUE TITLE
Deadlock can occur when doing a Find All References (or call hierarchy) and didChangeCppProperties/didChangeCustomBrowseConfiguration is received

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10855]
The lsp processing thread becomes deadlocked waiting for the references thread to finish (which is waiting for lsp processing to finish).

Only when configured with a configuration provider.

Repros with 1.14.5 too. An easy repro is to do Find All References with a large enough case (i.e. 20+ files to confirm) and then do Rescan Workspace. Another repro is to invoke it before a configuration provider has finished sending the browse configuration.

**Comment by michelleangela** [comment]
This is resolved in https://github.com/microsoft/vscode-cpptools/releases/tag/1.16.0.
