### ISSUE TITLE
Create Declaration in source file for static function and in header file for non-static functions

### ISSUE THREAD

**Issue by Yangnaan** [microsoft/vscode-cpptools#10868]
### Feature Request

a static function declaration in header file is useless.  placing a declaration  in different place according the type of function is better.

**Comment by sean-mcmanus** [comment]
Adding the static declaration to a header is a valid scenario. The source files that include the header just need to add their own definition if they reference the function.

Can you give an example in which adding the declaration to header to existing code (that builds/links) to fail to link?

**Comment by carepayer** [comment]
i usually place all the static function declarations below the includes of source file, to limit the function visual scope in that source file. 


```c
#include "test.h"
#include <stdint.h>

//here i place static function proto
static void test_static(void);

//a public function
void test_public(void)
{
//involve the static function in current file
test_static();
}

//a static function
static void test_static(void)
{


}

``` 
header 
```c
//a public function proto
void test_public(void);

```

**Comment by sean-mcmanus** [comment]
Okay, I've filed a feature request on VS at https://developercommunity.visualstudio.com/t/Enable-CC-Create-Declaration-on-stati/10348363 (it's implemented in a shared component).
