### ISSUE TITLE
Problem window can't find the right file

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#1086]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.13.0

---

Steps to Reproduce:

1. Open the test solution (where the .vscode folder is of course)
[test.zip](https://github.com/Microsoft/vscode-cpptools/files/1346901/test.zip)
2. Build (task is configured to use MSBuild with the ${env:MSBUILD} environment variable)
3. Notice there's an error
4. Open the problems window
5. Click on the problem

Expected: Goes to the problem
Actual: Can't find the file with the problem.  In this case \src\bar.cpp

Note: This works using the Error List in Visual Studio 2013.

**Comment by pieandcakes** [comment]
@azydevelopment Has this worked in VS Code before?

**Comment by azydevelopment** [comment]
Not sure.  I can't recall and/or never had quite this exact repro.

**Comment by bobbrow** [comment]
Is it this error, or are you getting something else?

`d:\test\customer1086\test\test\embedded_core\embedded_core.vcxproj(26,3): error MSB4019: ....`

I'm looking at the regular expression for the $msCompile problem matcher and I see that it only matches two non-digit characters after the "error" text.  This case has 3 characters (MSB), so it doesn't match.

**Comment by azydevelopment** [comment]
I'll try this when I get home.

**Comment by bobbrow** [comment]
No, maybe it's not.  Re-reading the issue, it looks like it should be failing on a source file.  Let me figure out what went wrong with my configuration of the task.

**Comment by azydevelopment** [comment]
Alright. Let me know if you need me to try something.

**Comment by bobbrow** [comment]
I upgraded the SLN to VS 2017 (sorry, I don't have VS 2013 installed) and rebuilt and the problem matcher worked ok for me. Clicking on the issue in the list opened the file and went to the correct line.

![image](https://user-images.githubusercontent.com/12818240/31795166-9eaaf9fe-b4d9-11e7-9a9c-ac5bb7b03a08.png)

The path shown should be relative to ${workspaceRoot}.  What do you see?

**Comment by azydevelopment** [comment]
This is what I see. I downloaded the test project above and tried it in VSCode as well as VS2013 without modifications for a clean test. The result is the issue in VSCode and not in VS2013 (ie. VS2013 opens the correct file).

Looks like there's a slight difference in that yours shows 'embedded_core\src' and mine just shows '\src'

![inkedcapture_li_moment](https://user-images.githubusercontent.com/29720335/31802312-4b86c9dc-b502-11e7-9373-404f04b1a284.jpg)

![capture2](https://user-images.githubusercontent.com/29720335/31801991-820bbf64-b500-11e7-8646-e56bc659af2f.PNG)

**Comment by azydevelopment** [comment]
Not sure if this was ever root caused.

**Comment by bobbrow** [comment]
Can you paste the build output from VS 2013?

**Comment by azydevelopment** [comment]
Here you go:

```
1>------ Build started: Project: embedded_core, Configuration: Debug x64 ------
1>  foo.cpp
1>  bar.cpp
1>src\bar.cpp(6): error C2511: 'Bar::Bar(Foo *const )' : overloaded member function not found in 'Bar'
1>          C:\Users\azy48\Desktop\test\test\test\embedded_core\include\bar.h(6) : see declaration of 'Bar'
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Here's my VS2013 Error List entry as well:

![image](https://user-images.githubusercontent.com/29720335/43929929-c97416c6-9beb-11e8-81ad-e4637c1ab84f.png)

**Comment by azydevelopment** [comment]
Also, I tried it in VSCode again, and it seems like it might have been fixed in an update but can't be sure:

I snipping tooled the problem window in my most current build of VSCode and it now does show the file in "embedded_core\src" instead of just "\src" as mentioned in a comment I made above.

![image](https://user-images.githubusercontent.com/29720335/43930038-30b646ce-9bec-11e8-84ec-3e5387cde71b.png)

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
