### ISSUE TITLE
Prompt menu shows private members

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/vscode-cpptools#10869]
### Environment

- OS and Version: Win11 22642
- VS Code Version: 1.77.3
- C/C++ Extension Version: v1.15.2

### Bug Summary and Steps to Reproduce

Bug Summary:
Prompt menu shows private members

Steps to reproduce:
```cpp
class Dog
{
private:
    int _age;

public:
    Dog() = default;
    Dog(int age) : _age(age) {}
}

class Person
{
private:
    Dog _dog;

public:
    Person()
    {
       // type ._ will show the private member
        _dog
    }
}
```
![image](https://user-images.githubusercontent.com/65096819/234019419-4da71da9-3540-41b2-afe5-219f8d1a2214.png)

Expected behavior:
`._age` shouldn't be on the menu

### Configuration and Logs

```shell
### configure

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "D:/MinGW/mingw64/bin/g++.exe"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
That is "by design" when completion is invoked at the same location more than once. Can you confirm that invoking completion at a different location and then invoking it at the _dog. causes it to stop showing the _age?

**Comment by zhiyiYo** [comment]
Yes, I type `_dog.` in another method and no prompt menu appears. Can we make this "by design" configurable in setting interface?

**Comment by sean-mcmanus** [comment]
Yeah, that is possible to do.
