### ISSUE TITLE
I can't run my code because of compilor issues

### ISSUE THREAD

**Issue by Menna929** [microsoft/vscode-cpptools#10866]
Type: <b>Feature Request</b>

I installed c++ pack and code runner . I also Installed compilor but it don't work.

Extension version: 1.14.5
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

**Comment by michelleangela** [comment]
@Menna929 
What compiler was installed?

We have tutorials for getting started with the C/C++ extension. If you're using the Microsoft C++ compiler, you can follow the guide https://code.visualstudio.com/docs/cpp/config-msvc. If you're using a GCC compiler on a Windows machine, you can follow the guide https://code.visualstudio.com/docs/cpp/config-mingw.

**Comment by Menna929** [comment]
Thank you mr.Michelle . The problem is solved .  Sent from Mail for Windows From: Michelle MatiasSent: 25 April 2023 05:23To: microsoft/vscode-cpptoolsCc: Menna929; MentionSubject: Re: [microsoft/vscode-cpptools] I can't run my code because of compilor issues (Issue ***@***.*** compiler was installed?We have tutorials for getting started with the C/C++ extension. If you're using the Microsoft C++ compiler, you can follow the guide https://code.visualstudio.com/docs/cpp/config-msvc. If you're using a GCC compiler on a Windows machine, you can follow the guide https://code.visualstudio.com/docs/cpp/config-mingw.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
