### ISSUE TITLE
Tooltip ‘C/C++ Configuration’ on status bar needs localization

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#10880]
![image](https://user-images.githubusercontent.com/38734287/234163731-8b4898b6-3861-4cdb-9a68-e8525c8da446.png)

Note: check if this is an issue with the code and not due to a missing string.

**Comment by sean-mcmanus** [comment]
The string appears localized and translated to me and the translation is old, i.e. I don't understand what could be causing the translation to not appear.

**Comment by sean-mcmanus** [comment]
Oops, wrong issue got marked fixed.

**Comment by sean-mcmanus** [comment]
This doesn't repro with 1.14.5 or 1.15.4 -- I think they might have been using a vsix that didn't have the localization correct.
