### ISSUE TITLE
Extension crashes and intellisense doesn't work

### ISSUE THREAD

**Issue by AarjavPatni** [microsoft/vscode-cpptools#10894]
Type: <b>Bug</b>

Just install the extension

Extension version: 1.14.4
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.53GB free)|
|Process Argv|C:\\Users\\Aarjav\\Documents\\codeforces.code-workspace --crash-reporter-id c0a3c96b-c1a1-4374-9ccc-52d41f1dca46|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30725893

```

</details>

**Comment by Colengms** [comment]
Hi @AarjavPatni .  There does not appear to be an issue causing the extension to fail for most users, so there would seem to be something about your environment or scenario that would help us reproduce and investigate the problem.

Could you provide details about your environment and repro steps?  Could you [get the crash stack](https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv)?

Some additional information can be found here: https://github.com/microsoft/vscode-cpptools/issues/10651

**Comment by AarjavPatni** [comment]
The problem seems to be fixed after I set the cache to 0. This can be closed until I encounter further issues.

**Comment by sean-mcmanus** [comment]
This sounds like the same issue hit in https://github.com/microsoft/vscode-cpptools/issues/10789 , i.e. cpptools-srv is crashing (not cpptools).
