### ISSUE TITLE
Go to Declaration

### ISSUE THREAD

**Issue by lizp08780** [microsoft/vscode-cpptools#109]
源代码在_.pc中，Go to Declaration只能到_.h文件中，而不是*.pc中。

**Comment by sridmad** [comment]
Translation from search engine.

.pc The source code , Go to Declaration only to the .h file instead of \* .pc in .

**Comment by jgoshi** [comment]
If this is a class member function, it has just been fixed and will appear in the next release. If it still repros at that time (or if this is a different issue) please reopen with more details.
