### ISSUE TITLE
Formatting Occasionally Breaks with the Latest Update

### ISSUE THREAD

**Issue by SE2Dev** [microsoft/vscode-cpptools#1090]
Operating System: Debian Stretch (9.1)
Extension Version: Latest
VSCode Version: Latest (Stable)

As of the most recent C/Cpp extension update - formatting breaks occasionally, and will remain broken until VSCode is restarted. I've yet to figure out exactly what triggers this as it's occurred several times over the past two days - but it *is* recurring.

Video demonstrating the issue can be found [here](https://youtu.be/gPNwvyQOkys).

I do have some custom configuration settings (.clangformat, json configs, etc.) and will add them here later today.

**Comment by bobbrow** [comment]
Please post any additional information on issue #1073.  We're actively trying to reproduce this error in-house.  We've seen reports on Mac/Linux so far.  Not sure if Windows is affected yet.

**Comment by sean-mcmanus** [comment]
In particular, we would like the steps or a video of what occurs before the corruption appears. The appearance of corruption after doing a formatting most likely means the internal document format was already corrupted prior to the formatting.
