### ISSUE TITLE
`cppbuild` tasks do not use the configured shell

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#10909]
### Environment

- OS and Version: Win 10 22H2
- VS Code Version: 1.77.3
- C/C++ Extension Version: 1.15.4

### Bug Summary and Steps to Reproduce

Bug Summary:
`cppbuild` tasks don't use the shell selected by the user. On windows it appears to always use `cmd` even if `pwsh` is selected (which I believe is the default).

Steps to reproduce:
* Execute this task
    ```
    {
        "label": "build",
        "group": "build",
        "type": "shell",
        "command": "Get-Host",
        "args": [],
    }
    ```
* Notice `Get-Host` is recognized
* Execute this task:
    ```
    {
        "label": "build",
        "group": "build",
        "type": "cppbuild",
        "command": "Get-Host",
        "args": [],
    }
    ```
* Notice `Get-Host` is not recognized

Expected behavior:
I'm not actually sure. I can't find any documentation for `cppbuild` tasks. What functionality does it provide? Should I always use it over a normal `shell` task? Is it supposed to use my selected shell?

### Configuration and Logs

```shell
N/A
```

**Comment by sean-mcmanus** [comment]
The implementation is at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/cppBuildTaskProvider.ts#L423 . It's using `cmd`. If 'cppbuild' isn't doing what you want, you could try using 'shell'. Where is your configured shell coming from? Which VS Code setting? It sounds like you want it to use PowerShell?

**Comment by akbyrd** [comment]
> Where is your configured shell coming from? Which VS Code setting?
It looks like it comes from `terminal.integrated.defaultProfile.windows` (or whichever platform you're on). I don't have it set manually, it just defaults to `pwsh` on Windows if it's installed.

If I make a custom task should I even be using `cppbuild`? Or is it just for auto-provided tasks? It showed up as an option for `type` when I was creating tasks for a project of mine and I assumed I was supposed to use it (I assumed the extension was using it to scrape information from the compiler output or something). Now that I think about it, I'm guessing I'm not supposed to be using `cppbuild` for user-created tasks? That would explain why I can't find documentation for it.

**Comment by sean-mcmanus** [comment]
Yeah, I'd say don't use the "cppbuild" task type. That was intended for simple scenarios.

**Comment by sean-mcmanus** [comment]
And the build task is not connected to the IntelliSense experience, which only gets information from sources like c_cpp_properties.json or C_Cpp.default settings and not tasks.json.
