### ISSUE TITLE
Browse database is not rebuilt after a Reset IntelliSense Database if compilerPath is set to ""

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10914]
Have a c_cpp_properties.json with compilerPath set to "" and do a Reset IntelliSense Database.

Bug: The workspace files are not tag parsed again (causing lots of features to fail to give results, such as Find All References), even after doing a reload window. Explicitly invoking Rescan Workspace fixes it.

**Comment by sean-mcmanus** [comment]
Repros with 1.14.5 too. Not sure when/if this actually worked.

**Comment by michelleangela** [comment]
This is resolved in https://github.com/microsoft/vscode-cpptools/releases/tag/1.16.0.
