### ISSUE TITLE
C/C++ extension IntelliSense

### ISSUE THREAD

**Issue by luka223** [microsoft/vscode-cpptools#1091]
Can someone help me with setting up c_cpp_properties.json?

I want IntelliSense only for headers that I included and file itself (for struct members, etc.), but I always get suggestions from every file in "usr/include".

For example, I only include <stdio.h>, but I get suggestions for strcmp, etc.

I'm using VS Code on Linux and using Microsoft's extension for C/C++.

**Comment by sean-mcmanus** [comment]
I'm not able to repro the bug. If you set your limitSymbolsToIncludedHeaders to "true" then it should only show symbols for strcmp if you #include a file that defines it. Can you try running the "Reset IntelliSense Database" command?

**Comment by luka223** [comment]
I just realized that I need to create c_cpp_properties.json file in a folder opened in VS Code, not in /home/username/.vscode, it works now. Thank you very much for response!
