### ISSUE TITLE
Intellisense server crashing

### ISSUE THREAD

**Issue by captainparticles** [microsoft/vscode-cpptools#1092]
Hi guys,

I work on a project that lives in a fairly large codebase. The project includes tmh header files and SAL annotations. 

Windows 10 64 bit
VS Code 1.16.1
CPP Tools 0.12.4 (Latest one fails to display results after some time of having VS Code running).

I'm hitting a crash (AV) trying to use intellisense, which is reverting my project to tag parsing. From the log:
> failed to read response from server: 16
> errorSquiggles count: 0
> IntelliSense client has disconnected from the server

I've attached a minidump with the crash. Please let me know if you need additional information.
[memory.zip](https://github.com/Microsoft/vscode-cpptools/files/1350513/memory.zip)

Stack:
> 0:008:x86> kc
>  # 
> 00 Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::an_edge_translation_unit_impl::get_error_to_source_file_mapping
> 01 Microsoft_VSCode_CPP_IntelliSense_Msvc!edge::translation_unit::get_error_to_source_file_mapping
> 02 Microsoft_VSCode_CPP_IntelliSense_Msvc!<lambda_7d36825f9243f31fb67e4d2d461e33fb>::operator()
> 03 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Find_if_unchecked<edge::isense_error *,<lambda_7d36825f9243f31fb67e4d2d461e33fb> >
> 04 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Remove_if_unchecked<edge::isense_error *,<lambda_7d36825f9243f31fb67e4d2d461e33fb> >
> 05 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::remove_if<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<edge::isense_error> > >,<lambda_7d36825f9243f31fb67e4d2d461e33fb> >
> 06 Microsoft_VSCode_CPP_IntelliSense_Msvc!edge_intellisense_server_impl::map_include_errors_to_source_file
> 07 Microsoft_VSCode_CPP_IntelliSense_Msvc!edge_intellisense_server_impl::handle_get_errors
> 08 Microsoft_VSCode_CPP_IntelliSense_Msvc!intellisense_server_base::attach_queued_handler::__l2::<lambda_b8377c655ed9b9546d3aebd1ab7b4a0c>::()::__l2::<lambda_b9a143cfae807225c5cf432458ff48d9>::operator()
> 09 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Invoker_functor::_Call
> 0a Microsoft_VSCode_CPP_IntelliSense_Msvc!std::invoke
> 0b Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Invoke_ret
> 0c Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Func_impl<<lambda_b9a143cfae807225c5cf432458ff48d9>,std::allocator<int>,void>::_Do_call
> 0d Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Func_class<void>::operator()
> 0e Microsoft_VSCode_CPP_IntelliSense_Msvc!work_queue::worker_proc
> 0f Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Func_class<void>::operator()
> 10 Microsoft_VSCode_CPP_IntelliSense_Msvc!microsoft::vc::thread_pool::enqueue::__l2::<lambda_d98e38b1a6e10e6cf9deb414519bcf3c>::operator()
> 11 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Invoker_functor::_Call<<lambda_d98e38b1a6e10e6cf9deb414519bcf3c> &>
> 12 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::invoke
> 13 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Invoke_ret
> 14 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Func_impl<<lambda_d98e38b1a6e10e6cf9deb414519bcf3c>,std::allocator<int>,void>::_Do_call
> 15 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Func_class<void>::operator()
> 16 Microsoft_VSCode_CPP_IntelliSense_Msvc!<lambda_c5fccf9798ea402fe7d0b4b7aa66471a>::operator()
> 17 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Invoker_functor::_Call
> 18 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::invoke
> 19 Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_c5fccf9798ea402fe7d0b4b7aa66471a> >,std::default_delete<std::tuple<<lambda_c5fccf9798ea402fe7d0b4b7aa66471a> > > > >::_Execute
> 1a Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_c5fccf9798ea402fe7d0b4b7aa66471a> >,std::default_delete<std::tuple<<lambda_c5fccf9798ea402fe7d0b4b7aa66471a> > > > >::_Run
> 1b Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_c5fccf9798ea402fe7d0b4b7aa66471a> >,std::default_delete<std::tuple<<lambda_c5fccf9798ea402fe7d0b4b7aa66471a> > > > >::_Go
> 1c Microsoft_VSCode_CPP_IntelliSense_Msvc!std::_Pad::_Call_func
> 1d Microsoft_VSCode_CPP_IntelliSense_Msvc!invoke_thread_procedure
> 1e Microsoft_VSCode_CPP_IntelliSense_Msvc!thread_start<unsigned int (__stdcall*)(void *)>
> 1f KERNEL32!BaseThreadInitThunk
> 20 ntdll_775e0000!__RtlUserThreadStart
> 21 ntdll_775e0000!_RtlUserThreadStart

Cheers,

**Comment by captainparticles** [comment]
Update:
The crash dump above seems to be crashing due to missing includes. While it shouldn't kill the server, I've added the necessary include paths and Intellisense got a bit further in parsing before hitting another AV, for which I've attached the dump. Without source access this one has me at more of a loss.

[memory2.zip](https://github.com/Microsoft/vscode-cpptools/files/1350658/memory2.zip)

**Comment by sean-mcmanus** [comment]
Yes, we've seen the get_error_to_source_file_mapping crash, but the hits have been too low to investigate so far (about 1% of all crashes). Your dmp's are 64-bit dumps of a 32-bit process, which doesn't work. Can you collect a 32-bit dump?

**Comment by bobbrow** [comment]
@sean-mcmanus.  The dumps look like they were captured with 64-bit WinDbg.  I was able to open them with that.  It looks like a corrupted pointer.  I haven't been able to reproduce it though.

**Comment by sean-mcmanus** [comment]
This was fixed starting with 0.15.0 in February, 2018.
