### ISSUE TITLE
Call Hierarchy doesn't work for templated methods

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10923]
Repro is
```cpp
void func11() {}
template <typename T>
void ttf(){ func11(); }
void func22() { ttf<int>(); }
```
and doing Call Hierarchy on tff. Doing Find All References works.

**Comment by michelleangela** [comment]
This is resolved in https://github.com/microsoft/vscode-cpptools/releases/tag/1.16.0.
