### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 0dminnimda** [microsoft/vscode-cpptools#10926]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.15.4`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.78.0`

[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cpptools/files/11421148/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

I've seen C/C++ extention taking up a lot of memory for some time already. I am working on a tool that generates C/C++ files. So currently in the folder there is a file with about ~6k lines of code, most of which are comments + some includes of hand-written files

**Comment by sean-mcmanus** [comment]
I'm not able to get any useful info from that .cpuprofile.

Which process is using a lot of memory? How much is "a lot"?

Can you provide the C/C++ logging with C_Cpp.loggingLevel set to "Debug" and/or look at that logging to see what operation is occurring that could be using the CPU?
