### ISSUE TITLE
Apple clang to LLVM clang mapping is incorrect for Apple clang 12.0.0 or later

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10920]
They're all get mapped to 110000.

Bug2: There was also a bug with Apple clang 10.0.1 incorrectly mapping to LLVM clang 6.0.1 instead of 7.0.0 and 11.0.3 mapping to 8.0.0 instead of 9.0.0.

This was discovered in the discussion at https://github.com/microsoft/vscode-cpptools/discussions/10622

**Comment by michelleangela** [comment]
This is resolved in https://github.com/microsoft/vscode-cpptools/releases/tag/1.16.0.
