### ISSUE TITLE
Nested peek definition

### ISSUE THREAD

**Issue by kterhorst** [microsoft/vscode-cpptools#1093]
Are there any plans to allow using peek definition within the peek definition popup window itself? Just like in Visual Studio for loaded project (not Open Folder). IMO it is the last step to make VS Code an excellent tool for exploring large code bases.

**Comment by bobbrow** [comment]
Can you file an issue with VS Code?  This isn't something that our extension can provide.  I think that they expect you to use backward navigation to get back to the previous peek, but I also understand that it can be hard to maintain a back stack in your head while exploring a new codebase.
