### ISSUE TITLE
Not showing std::string as string during debugging if I use clang++

### ISSUE THREAD

**Issue by qawserx** [microsoft/vscode-cpptools#10932]
### Environment

- OS and version: Fedora release 37 (Thirty Seven)
- VS Code: 1.78.0
- C/C++ extension: ms-vscode.cpptools
- OS and version of remote machine (if applicable):
- GDB / LLDB version: GDB

### Bug Summary and Steps to Reproduce

Bug Summary:
I can debug my program normally.
If I `std::cout` a `std::string` I can see the correct content by in the debugging panel the strings are not shown (I see integer , I can navigate list of list, a.s.o)

**Important: The problem is only if I build using `clang++`. With `g++` everything is fine.**

It may be related to 
https://github.com/microsoft/vscode-cpptools/issues/201

I'm not 100% sure that is an error; what I would like to know is how I find out the reason.

Steps to reproduce:
1. Compile my C++ program with '-g'
2. Edit `launch.json` as above
3. Start Debug

### Debugger Configurations

```shell
launch.json:

{
  "version": "0.2.2",
  "configurations": [
    {
      "name": "GNU - C/C++ Runner: Debug Session",
      "type": "cppdbg",
      "request": "launch",
      "args": [],
      "cwd": "${workspaceFolder}",
      "program": "${workspaceFolder}/hello",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}

```
```


### Debugger Logs

There are no error



### Other Extensions

_No response_

### Additional Information

Example program

```c++
#include <iostream>
#include <string>

int main()
{
    std::string str = "Hello, world!";
    std::cout << str << std::endl;
    return 0;
}
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.

**Comment by Wulfheart** [comment]
I have the same problem.

**Comment by wbf22** [comment]
Having this issue as well. Clang 18 on linux
