### ISSUE TITLE
Intellisense does not show suggestions when trying to autocomplete calls of methods on instances of a class

### ISSUE THREAD

**Issue by mskordal** [microsoft/vscode-cpptools#10939]
### Environment

- OS and Version:  Ubuntu 22.04
- VS Code Version:  1.78.1
- C/C++ Extension Version: 1.15.4

### Bug Summary and Steps to Reproduce

Bug Summary:

I have the following simple c++ file created
```c++
#include <iostream>
#include <string>
#include <vector>

using namespace std;

int main(int argc, char const *argv[])
{
    vector<int> x = {5, 6, 5, 4};
    x.push_back(25);
    return 0;
}
```
C/C++ Extension Pack is installed on my vscode

When I type `x.` and then press Ctrl-Space or when I start typing the method e.g. `x.pus` Intellisense does not provide any suggestions. However when i right-click on `vector` and then click `Go to definition`, intellisense pops up the stl_vector.h file and in there I can also see the definition for the push back method. If I manually type push_back and then pick its definition it will prompt me to the correct location of the function definition too.

Steps to reproduce:
1. Have C/C++ Extension Pack installed
2. Create a C++ project
3. Have a c_cpp_properties.json file configured
4. Create a vector instance and have your intellisense suggest a method e.g. push_back by typing . after the variable name and Ctrl-Space

Expected behavior:
It should provide suggestion for the push_back method, since `x` is of type `vector`

### Configuration and Logs

```shell
I have the following c_cpp_properties.json file in my .vscode directory:

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/c++/11"
            ],
            "defines": [],
            "cppStandard": "c++11",
            "intelliSenseMode": "linux-clang-x64"
        }
    ],
    "version": 4
}
```

### Other Extensions

I have also installed several other extensions. Even by disabling them all except the C/C++ and reloading the editor, the problem still persists. The extensions installed on my vscode are the following:

Avetis.tokyo-night
bkromhout.vscode-tcl
eamodio.gitlens
luveti.kconfig
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.makefile-tools
ms-vscode.remote-explorer
ms-vscode.remote-server
sleistner.vscode-fileutils
stkb.rewrap

### Additional context

Below I provide 3 pictures demonstrating the issue on my machine:

![Screenshot from 2023-05-11 10-40-21](https://github.com/microsoft/vscode/assets/2452170/bf3e7df0-a4c7-4a8c-9802-1ac418c36b1f)

![Screenshot from 2023-05-11 10-40-51](https://github.com/microsoft/vscode/assets/2452170/51b61012-b678-41f9-9021-1a835b9261b4)

![Screenshot from 2023-05-11 10-43-28](https://github.com/microsoft/vscode/assets/2452170/72b49236-d3d9-4c76-ab22-63d8fd597e50)

**Comment by Colengms** [comment]
Hi @mskordal .  I'm not able to repro this issue using the code and configuration your provided.  However, I see a squiggle in one of the images you posted, indicating something closer to the root of the issue:

![image](https://github.com/microsoft/vscode-cpptools/assets/49173979/d240916b-a10b-47f7-bdbf-d703cca1973b)

The squiggle on `iostream` would seem to suggest that some header files are missing.  Could you provide more information on the error message associated with that squiggle?  Is it possible you do not have the `g++` or `libstdc++` packages installed on your system?

**Comment by mskordal** [comment]
Hi @Colengms ,

Thank you so much. The problem ended up being on the squiggle. As shown in my json file I have included the `/usr/include/c++/11` path. I looked for the complaints on the missing headers in the iostream library. Apparently, it seems that several header files are in a different path, specifically `/usr/include/x86_64-linux-gnu/c++/11`. Once I added that path to my `includePath` variable in the `c_cpp_properties.json` file, the squiggle dissappeared and the autocompletion started working as a charm.

I mistakenly thought that since there were no missing dependencies in the vector header, the suggestions would work.

As a side note, the following versions of g++ and libstdc++ are installed in my system:
```console
$ /sbin/ldconfig -p | grep stdc++
	libstdc++.so.6 (libc6,x86-64) => /lib/x86_64-linux-gnu/libstdc++.so.6
	libstdc++.so.6 (libc6) => /lib/i386-linux-gnu/libstdc++.so.6
	libstdc++.so.6 (libc6) => /usr/lib32/libstdc++.so.6

$ g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

For my current project I am using clang:
```console
$ clang --version
Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```
Cheers
