### ISSUE TITLE
"Select IntelliSense Configuration" and Run&Debug button do not offer user-specified compilerPath

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#10943]
Repro steps:
* Install a non-standard C++ compiler into an arbitrary location.  My repro was using a compiler toolchain downloaded here: https://github.com/mstorsjo/llvm-mingw/releases
* Specify a path to that compiler in the `compilerPath` field of `c_cpp_properties.json`. (IntelliSense properly queries the compiler and uses its settings for IntelliSense).  In my case, this was; `"compilerPath": "Z:\\llvm-mingw-20220906-msvcrt-x86_64\\bin\\clang++"`
* Use either the "Select IntelliSense Configuration" command or click on the "Debug C++ file" (run and debug) button. 
![image](https://github.com/microsoft/vscode-cpptools/assets/49173979/bd69cadb-99b6-4b89-965a-3d43e1d0fc97)

Note that the compiler specified in `compilerPath` is not offered as an option on either of those lists.

Also, there are two similarly named commands: "C/C++: Select IntelliSense Configuration..." and "C/C++: Select a Configuration...".  Perhaps these names could be revisited to make them less ambiguous.

**Comment by Colengms** [comment]
The Run & Debug scenario is more obviously wrong, as the user should be able to build using the same `compilerPath` they've configured IntelliSense with.

**Comment by sean-mcmanus** [comment]
@Colengms What did you have in mind for the command names? That's a completely separate issue so I'm not sure why it's added to this issue. "C/C++: Select IntelliSense Configuration..." is short for "C/C++: Select IntelliSense Configuration Source..." but I was worried that would be too long.

**Comment by michelleangela** [comment]
This is resolved in https://github.com/microsoft/vscode-cpptools/releases/tag/1.16.0.
