### ISSUE TITLE
Cancel button for Find All References or Call Hierarchy when confirming references doesn't kill the currently running cpptools-srv processes

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10947]
This is a regression compared to the original Find All References release in 0.25.0 (3 years ago). Appears to have started around 18 months ago due to changes from the clang-tidy work.

This causes the cancel to not complete until the cpptools-srv is done processing the TU.

This is different from https://github.com/microsoft/vscode-cpptools/issues/4052 (which is only during the initial Processing Source stage, which is typically faster to complete).

**Comment by michelleangela** [comment]
This is resolved in https://github.com/microsoft/vscode-cpptools/releases/tag/1.16.0.
