### ISSUE TITLE
#define Variable Argument error

### ISSUE THREAD

**Issue by iblea** [microsoft/vscode-cpptools#10952]
### Environment

- OS and Version: macOS (13.3.1)
- VS Code Version: Visual Studio Code - Insiders 1.79.0-insider
- C/C++ Extension version : (1.15.4, 1.14.5 test)
- If using SSH remote, specify OS of remote machine: local

### Bug Summary and Steps to Reproduce

Bug Summary:
Failure to read header file results in an error.
It didn't happen on Linux and checked in macOS.

![image](https://github.com/microsoft/vscode-cpptools/assets/25794008/ccd6785d-7cdd-4c5b-ad4c-52e5ec62180e)

![image](https://github.com/microsoft/vscode-cpptools/assets/25794008/9314bd21-3825-4701-9e00-b8d89749f08e)

### Configuration and Logs

```shell
my c_cpp_properties.json
{
    "configurations": [
        {
            "name": "Linux",
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu11",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "macos-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}

my code-workspace
{
    "folders": [
        {
            "name": "test",
            //"path": ".."
            "path": "../"
        },
    ],
    "settings": {
        "C_Cpp.formatting": "vcFormat",
        // "C_Cpp.errorSquiggles": "enabled",
        "C_Cpp.errorSquiggles": "enabledIfIncludesResolve",
        "C_Cpp.intelliSenseEngineFallback": "enabled",
        "C_Cpp.intelliSenseEngine": "default",
        "C_Cpp.vcFormat.space.pointerReferenceAlignment": "right",
        "C_Cpp.loggingLevel": "Debug",
        "C_Cpp.default.cppStandard": "c++14",
        "C_Cpp.default.cStandard": "c11",
    }
}
```

**Comment by sean-mcmanus** [comment]
Sorry, I'm not understand what the error is that you're hitting. Can you provide more info or explanation?

**Comment by jhh9232** [comment]
The letter "..." representing the C/C++ variable argument is being changed  incorrectly as ")  ".

`#define DEBUG (format, a...)` -> `#define DEBUG(format )  )`

**Comment by sean-mcmanus** [comment]
That error is caused by your include test.h header not being found and your setting `"C_Cpp.intelliSenseEngineFallback": "enabled",` -- you should either fix the `#include` error or remove the `"C_Cpp.intelliSenseEngineFallback": "enabled",` setting (or change it to disabled).

**Comment by jhh9232** [comment]
The problem has been resolved. Thank you.
