### ISSUE TITLE
Anonymous struct members not viewable in debugger

### ISSUE THREAD

**Issue by divonlan** [microsoft/vscode-cpptools#10979]
Effectively reopening #966, as it is still only partially working.
See screenshot, I have a struct containing a member which is an anonymous struct.
1. In "Variables" I can see the anonymous member of the struct, but it incorrectly labels it as an anonymous union while it is in fact an anonymous struct.
2. In "Watch" I am trying to view a member of the anonymous struct, but its not working.
3. In debug mode, when hovering over a member of the anonymous struct in the editor, expecting its value to be shown, but it isn't.

Visual Studio Code version 1.78.2 on Windows 10 / mingw, using gcc with -fms-extensions / gdb
![anonymous-struct-vsc-bug](https://github.com/microsoft/vscode-cpptools/assets/56345591/589786ef-f28c-479a-bddf-d26818e85dda)

_Originally posted by @divonlan in https://github.com/microsoft/vscode-cpptools/issues/966#issuecomment-1556171509_

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
