### ISSUE TITLE
IntelliSense avoid saving new created files in Code

### ISSUE THREAD

**Issue by fazaldegui** [microsoft/vscode-cpptools#1097]
Hello,
Is not a big problem, but is annoying.
I create a new file in Visual Studio Code, using the Code's explorer: right-click on folder, new file and give a name for it.
But I can't save it, it gives me: 

> Error del sistema (EBUSY: resource busy or locked, open 'c:\xxx\newfile.h')

With the Process Explorer of Sysinternals I can see that this file is handled by the process "Microsoft.VSCode.CPP.IntelliSense.Msvc.exe"

If I kill this process using the Process Explorer, only this process not the whole VS Code, then I can save the file. Of course, if I close the Vs Code and reopen it I can save the file.
So IntelliSense is doing something that avoid to save the file in VS Code.

My configuration:
* OS: Windows 7 Pro
* VS Code v1.16.1 x64
* C++ extension 0.13.0

Thank you

**Comment by bobbrow** [comment]
We have a fix for this coming out soon.  This is issue #1040.
