### ISSUE TITLE
IntelliSense doesn't register valid C/C++ objects.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#10977]
### Environment

- OS and Version: Windows 11
- VS Code Version: 1.78.2
- C/C++ Extension Version:  v1.15.4

### Bug Summary and Steps to Reproduce

Bug Summary:
IntelliSense doesn't register valid C/C++ objects.

Steps to reproduce:
1. Setup any C/C++ project
2. Call or create something.

Expected behavior:
 The text will become different keyword highlighters, but it should not be.

### Configuration and Logs

```shell
{
    "C_Cpp.errorSquiggles": "enabled"
}
```

### Additional context

WPARAM AliaInternalGetWParamFromUintPtr(UINT_PTR source) {
	return (WPARAM)source;
}

### Temporary fixes until patched

Just save the file, then reopen it.

**Comment by Colengms** [comment]
Hi @CalDevx .  I don't believe we have enough information here to investigate further.  Your repro steps describe what most users are doing, so it's unclear what might be unique about your use scenario that would explain why you're seeing something unexpected.

> The text will become different keyword highlighters, but it should not be.

Could you provide more detail about what you're seeing and what you're expecting to happen instead?  Perhaps you could provide screenshots, or a stand-alone example that we could use to reproduce the issue?
