### ISSUE TITLE
Compiler path used by base configuration should be listed first in Run&Debug

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#10985]
This is related to: https://github.com/microsoft/vscode-cpptools/issues/10943

With the fix to that issue, a `compilerPath` specified explicitly in the base configuration is the last compiler listed in Run&Debug (and in `Select IntelliSense Configuration`).  It should probably be listed first.

When a user specifies a compiler (particularly one that wasn't auto detected), that is the compiler they are likely to want to use with Run&Debug.  It should be easy to locate, not at the bottom of the list.

**Comment by michelleangela** [comment]
Fixed in 1.16.1 https://github.com/microsoft/vscode-cpptools/releases/tag/v1.16.1.

**Comment by michelleangela** [comment]
Fix is now available in [release version 1.16.2](https://github.com/microsoft/vscode-cpptools/releases/tag/v1.16.2).
