### ISSUE TITLE
Find/Peek reference doesn't work correctly if use "Tag Parser" intelliSenseEngine

### ISSUE THREAD

**Issue by JohnBro** [microsoft/vscode-cpptools#10983]
### Environment

- OS and Version: Windows_NT x64 10.0.19045
- VS Code Version: 1.78.2 (user setup)
- C/C++ Extension Version: v1.15.4 release
- If using SSH remote, specify OS of remote machine: 4.15.0-193-generic #204~16.04.1-Ubuntu

### Bug Summary and Steps to Reproduce

Bug Summary:
change `C_Cpp.intelliSenseEngine` to "Tag Parser", the Peek References or Find all reference would show "No references found" but actually all the references result can be seen in "References" page.

Steps to reproduce:
1. make `C_Cpp.intelliSenseEngine` to "Tag Parser"
2. relaunch your project or workspace
3. right mouse click any code, select "Find All references" or "Peek References"
4. See error of "No references found xxx"

Expected behavior:
1. No error log.
2. Peek normally.

### Configuration and Logs

```shell
"C_Cpp.intelliSenseEngine"="Tag Parser"
```

### Other Extensions

Test the issue can be seen if only installed C/C++ extension.

**Comment by sean-mcmanus** [comment]
The "Tag Parser" mode is not recommended and isn't designed to support features like Find All References. If we did improve this to show some references, the references would not be "confirmed", i.e. could be inaccurate, i.e. similar results to VS Code's textual search feature.

**Comment by JohnBro** [comment]
> The "Tag Parser" mode is not recommended and isn't designed to support features like Find All References. If we did improve this to show some references, the references would not be "confirmed", i.e. could be inaccurate, i.e. similar results to VS Code's textual search feature.

Hi Seans,

Thanks for your reply, I understand your worries.
But as an "Feature Request", could you please consider add an option to "force show/peek references" if "Tag Parser" intelliSenseEngine has been selected? Disable it by default and give some tips that 'the reference results would not be "confirmed"'.

Because regards to some big C++ projects in one workspace, eg the native code for Android AOSP code, if we only add a part of repository, it's hard to add all C/C++ header path in `c_cpp_properties.json`, but the fuzzy result is also helpful to review code. To make the consistent experience in VSCode, this option should be very helpful.

Thanks & Regards
