### ISSUE TITLE
Format document (clang-format) does not work if fallbackStyle="" is defined in settings.json

### ISSUE THREAD

**Issue by illegal-instruction** [microsoft/vscode-cpptools#10994]
Type: <b>Bug</b>

Reproduce the issue with the UI settings.
1 - I modified the  C_Cpp.clang_format_fallbackStyle setting using the UI to 'LLVM'.
2 - The modified it to  ''

VSCode throws a 'formatting failed error' when settings.json looks like this
{
    "C_Cpp.clang_format_fallbackStyle": "",
    "files.associations": {
        "*.tcc": "cpp"
    }
}

However, deleting the line fixes it, and formatting is done without errors (since I have the 'file' value in format style and a valid .clang-format file)
{
    "files.associations": {
        "*.tcc": "cpp"
    }
}

Might this be considered an inconsistent behavior?

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. It also repros with clang_format_style.

**Comment by michelleangela** [comment]
Fixed in pre-release 1.16.1 https://github.com/microsoft/vscode-cpptools/releases/tag/v1.16.1.

**Comment by illegal-instruction** [comment]
Thank you @sean-mcmanus  !
