### ISSUE TITLE
Add file path to details of a call hierarchy result

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#10997]
Worked great when I used it before 👌 Only one detail on my wishlist which is to easily view which file the call resides in without clicking.

_Originally posted by @csholmq in https://github.com/microsoft/vscode-cpptools/issues/16#issuecomment-1559947744_

**Comment by csholmq** [comment]
When having multiple definitions it's easy to get confused which is which.
![image](https://github.com/microsoft/vscode-cpptools/assets/1297882/382b7772-2825-4a5b-ae0a-8b214ad6130e)

Perhaps something similar to how the search view works.
![image](https://github.com/microsoft/vscode-cpptools/assets/1297882/8dad9805-06ef-45f7-bfbf-5b7d8c9902c0)

**Comment by michelleangela** [comment]
For what structure is shown in the results panel, this is actually managed by VS Code. For this change request, an issue will need to filed at https://github.com/Microsoft/vscode to change the UI panel.

What the extension edit is the details properties of each function shown in the call tree. Currently the details display the containing name, such as namespace, of a function.
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/6e6b98d9-eb73-436d-b09a-98ef5f87d4de)

**Comment by csholmq** [comment]
File path would be nice but would be obscured for longer function names. Perhaps the hover could be utilized here and the function definition (which the hover seem to currently display) could be what's listed in the UI?

**Comment by sean-mcmanus** [comment]
Our extension doesn't have control over what is shown in the hover UI, but if the file path were added to the details then it would appear in the hover. We could also probably add the line and column info too.

**Comment by michelleangela** [comment]
Just to clarify, the details properties of a call hierarchy item is the info used for hover. This info will show up on the right side of the call hierarchy item. Here is an example:

![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/857f7d57-5aa6-4f4d-87a5-8c52aca447b1)

Adding @AlexandraKemperMS for input.

**Comment by sean-mcmanus** [comment]
Yeah, that seems good to me, but I'm not sure what punctuation is ideal to separate the namespace/class from the file.

**Comment by michelleangela** [comment]
Suggested text format to display:

`myFunction - myNamespace testFile.cpp (C:\myfolder\project)`

This way, users can see the file name first.

**Comment by sean-mcmanus** [comment]
@michelleangela Yeah, sounds good to me.

**Comment by AlexandraKemperMS** [comment]
@michelleangela wouldn't we want to only show the file name in this case? Or show:

testFile.cpp (C:\myfolder\project)- myNamespace

so that the filename is first and namespace is second?

**Comment by sean-mcmanus** [comment]
@AlexandraKemperMS I think the namespace should go first, since it's more important than the file info.

**Comment by AlexandraKemperMS** [comment]
@sean-mcmanus I chatted with michelle, yes, namespace first is the way to go. Michelle's original suggestion is fine to me.

**Comment by michelleangela** [comment]
Fixed in pre-release 1.16.1 https://github.com/microsoft/vscode-cpptools/releases/tag/v1.16.1.

**Comment by michelleangela** [comment]
Fix is now available in [release version 1.16.2](https://github.com/microsoft/vscode-cpptools/releases/tag/v1.16.2).
