### ISSUE TITLE
CppDbg Debugger broken ( Version 1.15.4: May, 2023 )

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#10999]
I have the same thing happening as the original post by OP.
## VSCode details:
> Version: 1.78.2 (user setup)
> Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
> Date: 2023-05-10T14:39:26.248Z
> Electron: 22.5.2
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19044
> Sandboxed: N

## launch.json:
```
"configurations": [
        {
            "name": "Debug",
            "type": "cppdbg",
            "request": "launch",
            "externalConsole": false,
            "program": "/home/linux/code/bin/myexe",
            "cwd": "/home/linux/code/bin",
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "stopAtEntry": true,
            "environment": [
                { "name": "LD_LIBRARY_PATH", "value": "/home/linux/code/bin" },
                { "name": "PATH", "value": "${env:LD_LIBRARY_PATH}:${env:PATH}" },
                { "name": "DISPLAY", "value": "localhost:10.0" },
            ],
        }
```
## Extension:
> C/C++ for Visual Studio Code - Version 1.15.4: May 1, 2023

I'm ssh'ing into a Linux machine. On the integrated terminal, I am able to manually start the debugger on the exe successfully but not via the VSCode task. The next-step-restart-stop bar at the top (see OP's video) pops up for few seconds before vanishing. No output in any of the windows.

I have tried deleting
1. %USERPROFILE%.vscode\extensions\ms-vscode.cpptools-*\install.lock
2. %USERPROFILE%.vscode\extensions\ms-vscode.cpptools-*\debugAdapters
from both the Windows host machine and the Linux machine but that didn't work. Tried using older versions of the extensions too.

Any help would be appreciated. I have no idea where to begin since logs are not being generated.

@WardenGnaw @kvelezgh @sean-mcmanus @Colengms

_Originally posted by @abhi-k9 in https://github.com/microsoft/vscode-cpptools/issues/7971#issuecomment-1558454208_

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
