### ISSUE TITLE
Parsing of NFS mounted drive is really slow (Ubuntu)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-cpptools#11]
_From @ashwinaj on April 14, 2016 22:47_
- VSCode Version: 1.0.0
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:
1. Open an NFS mounted folder in VS Code with a mix of C++, js and python source code (1000's of files)
2. Let the parsing (indexing) begin i.e. creation of the symbols database for intelliSense 

It is really slow (it's been running for 4 hours). This isn't the case with a similar setup with Sublime Text 3 on the same NFS mounted folder.

_Copied from original issue: Microsoft/vscode#5282_

**Comment by bpasero** [comment]
@ashwinaj what do you mean by "parsing" / "indexing"?

**Comment by bpasero** [comment]
_From @ashwinaj on April 15, 2016 10:59_

@bpasero  I mean creation of symbols for intellisense. The bar at the bottom always says "parsing" and never moves to complete.

**Comment by bpasero** [comment]
@ashwinaj is this from an extension? can you attach a screenshot?

**Comment by bpasero** [comment]
_From @ashwinaj on April 15, 2016 22:16_

@bpasero I apologize, I should've mentioned, it's using the following extension from Microsoft: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

Attached is a screenshot of this, highlighted in red at the bottom.

![vs_code](https://cloud.githubusercontent.com/assets/7064045/14576321/ea90d7b4-031c-11e6-8667-05aae5dc4f93.png)

**Comment by sridmad** [comment]
We are adding a way for the developer to specify path to database file in 0.8.0 that can be used as a mitigation. 

Next step is to identify reliable way to determine that a path points to network share (on Linux and Mac) and create the database under temp folder.

**Comment by jgoshi** [comment]
In the next release, version 0.8.0, we also add a new setting to the c_cpp_properties.json file called databaseFilename. If you point that to a local drive this will speed things up.
