### ISSUE TITLE
Can't install on macOS

### ISSUE THREAD

**Issue by xingdl2007** [microsoft/vscode-cpptools#110]
Still "Installing" after a long time.
VS Code version : 1.3.1

**Comment by xiongyu0523** [comment]
Yeah, I have the same problem on Windows 10, with the latest release. 
I'm in China, is a google service used? or is a VPN required? I can install other extensions

**Comment by delmyers** [comment]
Thanks, for your input. It seems that there have been problems with the marketplace these past couple of weeks. We are tracking down the right people to talk to try and get the issue resolved.
