### ISSUE TITLE
Exclude files from IntelliSense

### ISSUE THREAD

**Issue by morsisko** [microsoft/vscode-cpptools#11004]
### Feature Request

I have workspace that contains core source code, and source code of unit tests. There are two separate makefiles, one to build the core, and another one to build unit tests.

It happens, that inside unit tests there are symbols with the same name as in the core source code.

The problem is, sometimes when I work on new feature in core and use "Go to definition" or left click a symbol while holding CTRL, text editor jumps to unit test code, or small window is opened, in which all the files where the symbol was found are displayed (instead of immediately jumping to the correct place).

I already excluded the unit test files using VSC built-in setting search.exclude, however this option is not respected by cpptools. When I add those files to files.exclude in VSC workspace configuration, IntelliSense works correctly and the text editor doesn't jump to unit tests code when I want it to follow a symbol. However then those files disappear from file tree view inside visual studio code, and I would like to keep those files there.

My proposition is to add another way to exclude files, that would be exclusive to the IntelliSense. Such option could be included inside the c_cpp_properties.json

**Comment by michelleangela** [comment]
There are these file exclude settings specifically for the extension. Would this be what you're looking for?

![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/1ccedab8-4026-4a5e-9c98-da05de85d0c1)

**Comment by morsisko** [comment]
Yes, this is what I was looking for. Sorry, I didn't notice this before.
