### ISSUE TITLE
References and Call Hierarchy buttons show up twice

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#11002]
I just tested this on an Autosar project.
There is just a limited number of returned results.
It looks like is just analyzing the local file.

The issue I have with my VSCode installation is that it looks funny.
All the buttons are doubled:
![image](https://github.com/microsoft/vscode-cpptools/assets/4079754/4a826538-a79d-4fa6-961c-69180c2c117d)

And also the context menu shows the option twice.
![image](https://github.com/microsoft/vscode-cpptools/assets/4079754/ac233e0f-e787-4ed2-8934-7015c02f2cb8)

I am just using the zip installation version of VSCode.

_Originally posted by @RaveGun in https://github.com/microsoft/vscode-cpptools/issues/16#issuecomment-1560596220_

**Comment by michelleangela** [comment]
@RaveGun
Do you have other extensions installed? Also what version of VS Code are you using and for what platform?

The UI for call hierarchy, such as buttons and context menu is implemented and managed by VS Code, so I my initial thought is this could be an installation issue or registration issue of the extension.

**Comment by RaveGun** [comment]
I have this version installed:
```
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

And this is a list of extensions I have (the code --list-extensions does not return anything for me)
![image](https://github.com/microsoft/vscode-cpptools/assets/4079754/e98c6009-2302-4389-8520-21719c364f2a)


Thank you for the ticket!

**Comment by RaveGun** [comment]
I think I managed to cleanup my installation. 
Delete all the folder with the string "cache" in the name from the Data folder.
Now it look fine.

The ticket can be closed.
