### ISSUE TITLE
Copy definition/declaration string

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#11008]
The current string for "Copy definition/declaration..." code action is currently "Copy definition [name of function]"
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/041815cf-8fc7-4c23-9767-3ea2b505ea7c)

Per the spec, the strings should have "**to clipboard**" as shown below:

- “Copy definition of ‘[name of function]’ to clipboard”
- “Copy declaration of ‘[name of function]’ to clipboard”

**Comment by bobbrow** [comment]
I think @sean-mcmanus was opposed to having this text and the thread where we talked about it lost steam. I don't have a super strong opinion on this one, but the fix is easy if we decide to go this route.

**Comment by sean-mcmanus** [comment]
Yeah, I think we should omit "to clipboard", i.e. close this issue as "Won't Fix".

All other "Copy" commands in VS Code omit references to the clipboard.

**Comment by michelleangela** [comment]
Closing issue.
