### ISSUE TITLE
Multiline Comments: option to activate with /* instead of /**

### ISSUE THREAD

**Issue by john-coloccia** [microsoft/vscode-cpptools#1100]
I like that you now support multiline comments, but I would love it if you could add an option to activate them with a /* instead of just /**. To work around this, I've created a snippet to insert a completed comment block, but I'd rather hit /* and then start typing away, if that's possible. Related to #579

**Comment by bobbrow** [comment]
We can consider adding a setting to allow both forms, but I wouldn't want to turn this behavior on by default.

**Comment by john-coloccia** [comment]
Thanks, Bob! Just having the option, even if it's off by default, would make me (and I bunch of other people I suspect) very happy. :)

**Comment by bobbrow** [comment]
This issue is going to be tracked by #1539 which will support this request and other generalized patterns.  Thank you for your input to help the extension get better.
