### ISSUE TITLE
无法显示引用

### ISSUE THREAD

**Issue by houyufeng** [microsoft/vscode-cpptools#11017]
Type: <b>Bug</b>

无法显示变量、宏定义等的引用位置

Extension version: 1.15.4
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (1.79GB free)|
|Process Argv|--crash-reporter-id a01c87d5-1805-42bc-b4f0-3bdbdacf8ddd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1|
|OS|Linux x64 5.15.0-72-generic|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (4 x 1689)|
|Memory (System)|7.76GB (5.53GB free)|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
pythongtdpath:30739704

```

</details>

**Comment by browntarik** [comment]
Translation: 

Title: Unable to display reference

Type: Bug

You cannot display reference locations for variables, macro definitions, and so on

Extension version: 1.15.4
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-72-generic
