### ISSUE TITLE
The 1.15.4 version does not automatically generate the "launch.json" file

### ISSUE THREAD

**Issue by NianBroken** [microsoft/vscode-cpptools#11012]
After version 1.8.4, until the current version 1.15.4, it has not been able to automatically generate the "launch. json" file. Only when I switched to version 1.8.4, it could automatically generate the "launch. json" file. This problem has been bothering me for over a year. I hope it can be solved soon!

**Comment by sean-mcmanus** [comment]
The gear icon in the top right of a .c/.cpp file can be used to generate a launch.json: 
![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/8474fd1a-fbb9-4654-bf34-b459d6a78e73)

Does that work for you ?

**Comment by sean-mcmanus** [comment]
Our hope is that users will be able to locate the documentation at https://code.visualstudio.com/docs/cpp/config-msvc#_customize-debugging-with-launchjson or https://code.visualstudio.com/docs/cpp/config-linux#_customize-debugging-with-launchjson , but for some reason other users also haven't found that.
