### ISSUE TITLE
Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Error: Pending response rejected since connection got disposed

### ISSUE THREAD

**Issue by angelNexSpec** [microsoft/vscode-cpptools#11013]
### Environment

- OS and Version:  MacOS Ventura 13.3.1
- VS Code Version: 1.77.0 (Universal)
- C/C++ Extension Version: 1.15.4
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary: IntelliSense never available on fresh install of C/C++ extension. Tried reinstalling VSCode and different versions of the extension but could never get it to work. I can write some code, hover over and will output "loading...". After a minute, VSCode produce 
- Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Error: Pending response rejected since connection got disposed
- Sending request cpptools/queryCompilerDefaults failed.
- The language server crashed. Restarting...

### Configuration and Logs

```shell
?
```

**Comment by sean-mcmanus** [comment]
Can you go to the ~/.vscode/extensions folder and look for the extensions folder with some name like ms-vscode.cpptools-1.15.4-darwin-x64 (the -darwin-x64 part might be missing) and go to the bin folder and see what happens when you run `/.cpptools` and `file ./cpptools`?

**Comment by bobbrow** [comment]
Can you check inside the `bin` folder of the `ms-vscode.cpptools...` folder?

**Comment by angelNexSpec** [comment]
<img width="777" alt="Screenshot 2023-05-25 at 2 45 49 PM" src="https://github.com/microsoft/vscode-cpptools/assets/129427762/6cc83e37-2c0d-4344-af57-84d9369eb962">

Stopped it after about 5 minutes of waiting. Should I rerun it and wait longer?

**Comment by sean-mcmanus** [comment]
Yeah, if you get no output and you have to ^C then it's working. What is the output of `file ./cpptools`?

**Comment by angelNexSpec** [comment]
./cpptools: Mach-O 64-bit executable arm64

**Comment by sean-mcmanus** [comment]
Yeah, that looks as expected so far -- what about `ls -l ./cpptools`? In particular, the executable permissions on the left.

**Comment by angelNexSpec** [comment]
-rwxr-xr-x@ 1 angel.cueva  staff  23774736 May 25 12:10 ./cpptools

**Comment by sean-mcmanus** [comment]
Yeah, that looks good too. Unfortunately, you appear to be hitting some unusual failure we haven't encountered before. You could try switching to the 1.16.0 (pre-release) version or installing 1.15.4 from the vsix at https://github.com/microsoft/vscode-cpptools/releases/download/v1.15.4/cpptools-osx-arm64.vsix , but I'm doubtful that doing that would solve your issue.

@bobbrow Any other ideas?

**Comment by angelNexSpec** [comment]
It worked after switching to 1.16.0 (pre-release) this time but didn't switching to it before. It prompted me to choose a compiler path and worked after that. Thank you!

**Comment by bobbrow** [comment]
Seems like it was some kind of installation issue. Glad to hear you're unblocked now.

**Comment by XiaotaoChen** [comment]
> It worked after switching to 1.16.0 (pre-release) this time but didn't switching to it before. It prompted me to choose a compiler path and worked after that. Thank you!

Hi, i met this problem too, and update c/c++ extension to 1.16.0, it still tells the same error info.  don't you have any suggestions? @bobbrow @angelNexSpec

**Comment by bobbrow** [comment]
@XiaotaoChen did you try to uninstall and reinstall the extension?  The best way to ensure the extension is uninstalled is to go to the `~/.vscode/extensions` folder and delete the folder for our extension, something like `ms-vscode.cpptools-1.16.0`.  VS Code sometimes delays the uninstall if you do it through their UI.

**Comment by XiaotaoChen** [comment]
> @XiaotaoChen did you try to uninstall and reinstall the extension? The best way to ensure the extension is uninstalled is to go to the `~/.vscode/extensions` folder and delete the folder for our extension, something like `ms-vscode.cpptools-1.16.0`. VS Code sometimes delays the uninstall if you do it through their UI.

i tried to delete `~/.vscode/extensions/ms-vscode.cpptools-1.16.0-darwin-arm64` and reinstall it, but still tells the same error. And this problem seems like disappear， my vscode work normally, i don't know why. those two day i turn to use cland with `compile_commands.json`

**Comment by bobbrow** [comment]
Do you have the ARM64 macOS?  Does installing the x64 version work?  Here: https://github.com/microsoft/vscode-cpptools/releases/download/v1.15.4/cpptools-osx.vsix
