### ISSUE TITLE
FR: Always show full inlay hints for parameters

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#11010]
Type: <b>Bug</b>

Currently inlay hints are not shown for parameters having arguments with the same name.

This feature appears to use some sort of heuristics as it also displays strange results such as:

![Screenshot 2023-05-25 at 15 46 10](https://github.com/microsoft/vscode-cpptools/assets/47526411/5bca1f0d-71fb-42d8-aea1-2145a054410d)

I'd like to have an option to always display the full inlay hints.

Extension version: 1.16.0
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id a7eaff19-94ae-4653-b917-d9aaab19da5d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by michelleangela** [comment]
@H-G-Hristov 
The extension has the following settings for inlay hints. If you'd like to display the parameter names even with the argument contains the parameter name, set `"C_Cpp.inlayHints.parameterNames.suppressWhenArgumentContainsName": false`.

![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/6bb47e5d-4df0-4078-8ca2-0f4db21a28ec)
