### ISSUE TITLE
C++ on visual studios code (Mac)

### ISSUE THREAD

**Issue by Brenton393** [microsoft/vscode-cpptools#1101]
following the steps here https://code.visualstudio.com/docs/languages/cpp im trying to get C++ running on my mac. Ive followed all the step till it says "With the C/C++ extension installed, open a folder that contains your C/C++ source code. VS Code will place various settings files into a .vscode subfolder."

not sure what it mean, honestly. not really sure what steps i need to take from here to get C++ to debug.

**Comment by pieandcakes** [comment]
@Brenton393 You need to open your folder that contains your C++ code. If you want to debug, you will first need to compile your source. If you are on Mac OS X, you can use clang++ to compile your code from a Terminal window or you can configure a `task.json` file (`Tasks` in the tool bar) to have VS Code run the command for you. Please make sure when compiling, you add the `-g` flag to compile with symbols or debugging will not work.

Once that is done, you will need to configure a Debug Configuration and point it at the output from the C++ compiler, which is your program.

**Comment by pieandcakes** [comment]
Please comment if you still need help with this. Closing for now.

**Comment by heroinamagazine** [comment]
@pieandcakes can you give me a step by step method on how to do that? Everything you said. I downloaded VScode and i have xcode updated as well as of today (May 3, 2018). for a completely new programmer who know's nothing about how to do this sorta of thing.

**Comment by sean-mcmanus** [comment]
@pieandcakes is OOF currently. What exactly do you need help with first? You use clang++ to compile your code. You can do that from the command line, terminal window, or task.json. You can type clang++ --help for info on the args. Have you gotten your code to compile yet?
