### ISSUE TITLE
The whole bazel output base is often indexed

### ISSUE THREAD

**Issue by cameron-martin** [microsoft/vscode-cpptools#11011]
### Environment

- OS and Version: Ubuntu 22.04
- VS Code Version: 1.78.2
- C/C++ Extension Version: v1.15.4
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary: When using a compile_commands.json file, the vscode C/C++ extension often decides to index the whole bazel output base, which is very slow and unnecessary. Which directories it decides to index seems quite inconsistent, and relies on how the path of the file is factored into `file` and `directory` in the compile_commands.json file.

Steps to reproduce:
1. Ensure bazel is installed, preferably via [bazelisk](https://github.com/bazelbuild/bazelisk).
2. Clone this repository: https://github.com/cameron-martin/vscode_cpp_bazel_output_base
3. Run the commands shown in the README to generate different compile_commands.json files, and see the directories that are indexed.

Expected behavior:

In the first case, I would not expect it to index the whole output base, instead only indexing the directory containing main.cpp.

### Configuration and Logs

```shell
See the above reproducer
```

**Comment by sean-mcmanus** [comment]
Our code is incorrectly thinks `"file": "foo/main.cpp"` is an absolute path (resolved by the current working directory of the workspace folder), so it uses the parent directory of `${workspaceFolder}/foo` as the browse.path instead of `OUTPUT_BASE/external/foo`.

When `"file": "external/foo/main.cpp"` is used (and not found in the workspace folder) it falls back to using `"directory": "OUTPUT_BASE"` as the browse.path.

**Comment by cameron-martin** [comment]
So are you saying that using whatever is in `directory` as the `browse.path` is the correct behaviour?

**Comment by sean-mcmanus** [comment]
Yes, if file is a relative path, then the intent of the original implementation was to use the directory as the browse.path. I'm not sure why exactly that was done, so we could also change it to use just the folder containing the file. Is that what you'd prefer? I'll also ask our team about it.

**Comment by sean-mcmanus** [comment]
The difference is that if we start using the parent folder of the absolute path then that could potentially be excluding some folders that we previously were including -- it's possible some of those folders may include source files that would be desirable in a global symbol search even though they are not yet being built by the compile commands file (we're not sure yet).

And it's been like this for 3 years and haven't received other complaints yet (https://github.com/microsoft/vscode-cpptools/issues/1163). The bug where we incorrectly process a relative path as an absolute path might be a more recent regression.

But I'd agree that the behavior seems strange and not expected, so we're still discussing whether to change it now or maybe create a new issue to track that.

**Comment by sean-mcmanus** [comment]
I filed an issue to track this remaining issue at https://github.com/microsoft/vscode-cpptools/issues/11036 .

**Comment by sean-mcmanus** [comment]
The bug mentioned at https://github.com/microsoft/vscode-cpptools/issues/11011#issuecomment-1563656487 is fixed.
