### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by duaneellissd** [microsoft/vscode-cpptools#11021]
### Feature Request

Ability to create your own internal mirror of the VS Code Market place.

Example - I work in  a closed environment. We have mirrors of numerous things like Linux Distroes, and PyPy - and the old PERL CPAN. Want to setup the same thing for VSCODE so team can access from closed room easily.

Current problem: 
(1) Must download package - burn to CD in Room (PUBLIC) where we have internet,
(2) IT verifies (virus scan etc, they perform a séance and bless the file with 'holy security-guy-water')
(3) File is copied/burned to CDROM, 
(4) Somebody from IT CD taken into room (CLOSED-SECURED) I am not allowed to.
(5)  I can install on isolated machine.

Similar things with Windows Activation and MS Office installs, and weekly virus scan updates. 
Painful, it is all OFF LINE work and required to be offline.

Repeat for each thing to install, or update this means it takes days to get something done.
Would be nice to have a local mirror that can be quickly updated.

**Comment by browntarik** [comment]
Hi! Please file this issue with the VS Code Team (https://github.com/microsoft/vscode/issues) as this is unrelated to the C++ Extension. Closing this issue as out of scope.
