### ISSUE TITLE
Problem setting the cppStandard on Windows: unknown option '-std=c++20'

### ISSUE THREAD

**Issue by AleCaste** [microsoft/vscode-cpptools#11039]
### Environment

- OS and Version:  Windows 10 Home 21H2
- VS Code Version: 1.77.3
- C/C++ Extension Version: 1.16.0 Pre-Release
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
When using cl.exe, the "std" argument is being set as "-std=c++20" instead of "/std:c++20" and cl.exe complains on Windows

Steps to reproduce:
1. Open the Developer Command Prompt for VS
2. Create a Hello World project following steps from https://code.visualstudio.com/docs/cpp/config-msvc
3. Add "#include &lt;any&gt;" in main.cpp
4. Change the "C Standard" setting of the C/C++ Extension to "c++20"
5. Compile main.cpp using cl.exe

Expected behavior:
Project should compile just fine.

The command executed by the C/C++ extension is the following:
cl.exe -std=c++20 /Zi /EHsc /nologo /FeC:\projects\hello\main.exe C:\projects\hello\main.cpp

If I manually execute the same command but using "/std:c++20" arg...
cl.exe /std:c++20 /Zi /EHsc /nologo /FeC:\projects\hello\main.exe C:\projects\hello\main.cpp
... then the project compiles just fine.

### Configuration and Logs

```shell
c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.22000.0",
            "compilerPath": "cl.exe",
            "cStandard": "c23",
            "cppStandard": "c++20",
            "intelliSenseMode": "windows-msvc-x64"
        }
    ],
    "version": 4
}


tasks.json:
{
  "tasks": [
    {
      "type": "cppbuild",
      "label": "C/C++: cl.exe build active file",
      "command": "cl.exe",
      "args": [
        "/Zi",
        "/EHsc",
        "/nologo",
        "/Fe${fileDirname}\\${fileBasenameNoExtension}.exe",
        "${file}"
      ],
      "options": {
        "cwd": "${fileDirname}"
      },
      "problemMatcher": [
        "$msCompile"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "detail": "Task generated by Debugger."
    }
  ],
  "version": "2.0.0"
}

Output from compiler:
Starting build...
cl.exe -std=c++20 /Zi /EHsc /nologo /FeC:\projects\hello\main.exe C:\projects\hello\main.cpp
cl : Command line warning D9002 : ignoring unknown option '-std=c++20'
main.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\any(13): warning STL4038: The contents of <any> are available only with C++17 or later.
```

**Comment by AleCaste** [comment]
My mistake, I forgot that tasks.json and c_cpp_properties.json are not linked one another, so I need to properly add the arg "/std:c++20" in tasks.json

**Comment by Colengms** [comment]
Hi @AleCaste .  Doing what you described, I did not see the standard arg added.  I don't see (obvious) code in the C/C++ extension that would be automatically adding to that task command line.

It sound like you may have figured it out?  I'll close the issue.  If there is still an issue here that you need assistance with, just let us know. We can reactivate.
