### ISSUE TITLE
In windows, `"console": "integratedTerminal"` option works better?

### ISSUE THREAD

**Issue by caiohamamura** [microsoft/vscode-cpptools#11032]
In this line, the `externalTerminal` is hardcoded. But for Windows `cl.exe` as suggested by the [VSCode documentation](https://code.visualstudio.com/docs/cpp/config-msvc), at least, this won't work. We have to manually change everytime to `integratedTerminal` to work, or else the Debugger won't attach.

https://github.com/microsoft/vscode-cpptools/blob/e394edb63096b1b6995c3e1dd8b1ad9d47603690/Extension/src/Debugger/configurationProvider.ts#L437

Can anyone else confirm this, or am I missing something?

If that is true shouldn't the extension check if the user is running `cl.exe` and use `integratedTerminal` instead by default?

**Comment by michelleangela** [comment]
Fixed in pre-release 1.16.1 https://github.com/microsoft/vscode-cpptools/releases/tag/v1.16.1.

**Comment by michelleangela** [comment]
Fix is now available in [release version 1.16.2](https://github.com/microsoft/vscode-cpptools/releases/tag/v1.16.2).
