### ISSUE TITLE
${workspaceRoot} in launch.json is not the Folder path

### ISSUE THREAD

**Issue by karimmansour** [microsoft/vscode-cpptools#1104]
`${workspaceRoot}` in launch.json is not the project Folder path that contains task.json

OS: Windows:
Programming Language: C++
Compiler: g++
Debugger: gdb
Visual Studio Code Version: 1.17.0
C/C++ Microsoft Extension Version: 0.13.1

For the debugger program configuration, I have to place the absolute path in the launch.script to be able to debug
`
"program": "C:\\Absolute\\Path\\to\\debugFile.exe",
`
`
"program": "${workspaceRoot}\\build\\debugFile.exe", //Doesn't work
`

**Comment by pieandcakes** [comment]
@karimmansour ${workspaceRoot} is defined by VS Code itself. This is the folder you opened when you used "Open Folder" option in "File". Please make sure that this is where you expect it. It looks like in your example you have an extra `\\build\\` folder in the `//Doesn't work` example. if it is a typo and if ${workspaceRoot} is not resolving to the right directory, you can file an issue with them at https://github.com/Microsoft/vscode/issues .

**Comment by mikecancilla** [comment]
Is there a way to print/echo the value of $workspaceRoot?

**Comment by pieandcakes** [comment]
@mikecancilla We rely on [VSCode](https://github.com/microsoft/vscode/issues) to resolve ${workspaceRoot} and ${workspaceFolder} so therefore we don't have a way to query it. You may want to ask over on their issues page.

**Comment by sean-mcmanus** [comment]
@mikecancilla I don't think VS Code uses ${workspaceRoot} -- they replaced it with ${workspaceFolder}. Our c_cpp_properties.json is the only thing that still uses it. If you have at least 2 workspace folders in the VS Code Explorer tab, you can right-click one of the folders and do a Copy Path to get the associated ${workspaceFolder}.

**Comment by mikecancilla** [comment]
Thank you for the replies.

**Comment by saichaitanyaeruvaram** [comment]
My workspaceRoot is D:\ws
in tasks.json .. ${workspaceRoot} resolves to D:ws
However, it works correctly in launch.json .. ${workspaceRoot} resolves to D:\ws

version 1.19.2, x64

Can anyone provide inputs?

**Comment by sean-mcmanus** [comment]
@saichaitanyaeruvaram Can you switch everything to `${workspaceFolder}`?

**Comment by saichaitanyaeruvaram** [comment]
@sean-mcmanus For me .. workspaceFolder and worksapceRoot are same and I tried both.. 
tasks.json

` "command": "${workspaceRoot}/node_modules/.bin/tsc.cmd -p ${workspaceRoot}"`
` "command": "${workspaceFolder}/node_modules/.bin/tsc.cmd -p ${workspaceFolder}"`
` "command": "D:/ws/node_modules/.bin/tsc.cmd -p D:/ws"`
Only the last 1 works ..where I hard-code path

**Comment by sean-mcmanus** [comment]
@saichaitanyaeruvaram Can you file a VS Code bug? https://github.com/Microsoft/vscode . The docs say it's supposed to work https://code.visualstudio.com/docs/editor/variables-reference .

**Comment by saichaitanyaeruvaram** [comment]
@sean-mcmanus  https://github.com/Microsoft/vscode/issues/42228

**Comment by jyavenard** [comment]
I believe the issue on windows is that $workspaceRoot contains single \ in the path.
When used as part of a command the single \ are removed... $workspaceRoot should be using either / or \\ when used with tasks.json

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
