### ISSUE TITLE
Editor does not shows basic errors in syntax but compiler shows

### ISSUE THREAD

**Issue by Fady2007** [microsoft/vscode-cpptools#11044]
### Environment

- OS and Version: 
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
{
  "configurations": [
    {
      "name": "Win32",
      "includePath": ["${default}"],
      "defines": ["_DEBUG", "UNICODE", "_UNICODE"],
      "cStandard": "c17",
      "cppStandard": "gnu++17",
      "intelliSenseMode": "windows-gcc-x64"
    }
  ],
  "version": 4
}
```

### Additional context

compiler shows errors but visual studio code editor does not show any basic errors in syntax

For Example: 

`#include <iostream>
using namespace std;
int main()
{
  cout << "Line One\n";
  cout << "Line Two\n" 
  cout << "Line Three\n";
  return 0;
 this is a comment with out "//"
}`

NO Formatting or shows syntax error by editor

**Comment by michelleangela** [comment]
@Fady2007 
Could you provide the following logs and other info below? IntelliSense may need further configuration and the logs may show what could be the issue.

**Please provide info for:**

- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- If using SSH remote, specify OS of remote machine:

**Please provide the following two logs:**
- Logs from running C/C++: Log Diagnostics from the VS Code command palette
- Logs from the language server (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Comment by Colengms** [comment]
Hi @Fady2007 .  I noticed that you're trying to `#include <iostream>`, however I don't see a compiler specified in your configuration. In order for IntelliSense to find system headers, a compiler toolchain (and its headers) need to be located on your system.  The C/C++ Extension does not currently bundle a free C++ compiler. Do you have a C++ compiler installed? If so, could you try specifying it in your configuration using the `compilerPath` field?
