### ISSUE TITLE
Configuring Clang on macOS document is obsolete

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#11059]
https://code.visualstudio.com/docs/cpp/config-clang-mac

This article is obsolete and when I followed the tutorial, my VSC didn't produce the exact tasks.json and I couldn't quite follow the tutorial. Besides, using default tasks.json produced by VSC will cause error, using the code provided in the article. Could you please update this article for C developers using Macs like me? I'd really appreciate that!

**Comment by AlexandraKemperMS** [comment]
Hi @ghost, thank you for pointing this out. With [this PR](https://github.com/microsoft/vscode-docs/pull/6915) the mac configuration docs have been fixed and updated. I am closing this issue, but feel free to leave a comment/create a new issue if there are still problems.
