### ISSUE TITLE
Syntax highlighting - failure on C++ raw strings containing single quote chars

### ISSUE THREAD

**Issue by heriberto-delgado-ev** [microsoft/vscode-cpptools#11058]
### Environment

- OS and Version: Windows 11 Enterprise
- VS Code Version: 1.78.2
- C/C++ Extension Version: 1.15.4
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:
Syntax coloring in raw strings fails to determine right colors after a raw string is processed, if the raw string itself contains a single quote ( ' ) character.

Steps to reproduce:
1. Create a new .cpp file in Visual Studio Code
2. Type the following code in it:

```
#include "MyAwesomeDatabaseLibrary.h"
#include <string>
#include <iostream>

int main(int argc, char** argv)
{
    std::string plate = argv[1];

    AwesomeDBConnection conn;

    conn.Open("myconnectionstring");

    auto query = conn.Execute(R"sql(

        SELECT uid, part_name, install_date FROM CarParts
         WHERE plate = ')sql" + plate + "' ORDER BY install_date");

    for (const auto& entry : query)
    {
        std::cout << entry["uid"] << ": ";
        std::cout << entry["part_name"] << ", ";
        std::cout << entry["install_date"] << std::endl;
    }

    conn.Close();

    return 0;
}
```

3. The colors in the recently typed code look like this:
<img width="1053" alt="Screenshot 2023-06-08 114206" src="https://github.com/microsoft/vscode-cpptools/assets/47340659/83a4fda9-4df7-47c3-bf2c-6699c7dfd351">

Expected behavior:
(Not like above image)

### Configuration and Logs

```shell
N/A
```

**Comment by Colengms** [comment]
Hi @heriberto-delgado .  This appears to be an issue with VS Code, not the C/C++ extension.  It repro's with the C/C++ extension disabled.

Syntax colorization is provided by VS Code directly.  VS Code ingests a grammar provided by a 3rd party, and that grammar is here: https://github.com/jeff-hykin/better-cpp-syntax

The C/C++ extension provided semantic colorization.  Though, I don't believe semantic colorization could be used to address the incorrect syntax colorization following the repro.

I'd suggest opening this issue in that repo, or [the VS Code repo](https://github.com/microsoft/vscode/issues).

Closing this as external.
