### ISSUE TITLE
C/C++ IntelliSense browsing stops working - how to reset?

### ISSUE THREAD

**Issue by n808** [microsoft/vscode-cpptools#1105]
Frequently IntelliSense browsing stops working for my simple C project. The "scanner" indicator never stops, and then after restarting VS Code, I get No definition found for all functions and variables. I have been trying to find out how to reset the database or whatever the plugin uses, but the only way I have found is to start working on the project in a different folder (different name), since even cleaning out everything and checking files back out does not work. 
macOS 10.12.6
VS Code 1.16.1
IntelliSense 0.13.0
Unable to provide sample project to repro.
Settings pretty much defaults.
EDIT: Eventually I received a message that VS Code installation had become corrupt and needed to be re-installed. Fortunately there was an auto-update ready. After this was installed and VS Code restarted, IntelliSense browsing started working again. Note that when I had this problem before, VS Code re-installation and C/C++ re-installation did not work to fix this problem.

**Comment by sean-mcmanus** [comment]
Update to 0.13.1 -- it should be more stable. We have additional stability fixes on the way for our next update. There's a Reset IntelliSense Database command which will reset the database. I don't think our extension can corrupt the VS Code installation. Let us know if you're still having problems with 0.13.1.

**Comment by n808** [comment]
Thanks! the Reset IntelliSense Database command really was what I was looking for. The next time this occurs, if it does, that will probably clear things right up. Closing issue, since it's impossible to provide a repro case.
