### ISSUE TITLE
[msys2/mingw64] recommend using ucrt64 instead of mingw64

### ISSUE THREAD

**Issue by 1480c1** [microsoft/vscode-cpptools#11063]
Hi,

msys2 has recently moved towards recommending using the [ucrt64/clang64 environment over the mingw64 environment][1] and instead now recommends installing `mingw-w64-ucrt-x86_64-toolchain` rather than `mingw-w64-x86_64-toolchain` as mentioned in [Using GCC with MinGW](https://code.visualstudio.com/docs/cpp/config-mingw).
Doing so would also require updating the path mentioned from `C:\msys64\mingw64\bin` to `C:\msys64\ucrt64\bin`.

The only limitations would be that ucrt is not installed by default on Windows 7 and msys2 does not currently provide an ucrt32 environment. However, since [vscode's requirements page](https://code.visualstudio.com/Docs/supporting/requirements) shows `Windows 8.0, 8.1 and 10, 11 (32-bit and 64-bit)`, I would assume the first limitation does not apply, and the second matters less on the basis that 32-bit is only mentioned in a small section leading to msys2's page.

[1]: <https://www.msys2.org/news/#2022-10-29-changing-the-default-environment-from-mingw64-to-ucrt64>

**Comment by gregvanl** [comment]
Here's a communty to update the path. https://github.com/microsoft/vscode-docs/pull/6276

Also related is a version bump on the existing path https://github.com/microsoft/vscode-docs/pull/6387

**Comment by Colengms** [comment]
This has been addressed.  Docs were updated to refer to the `ucrt64` toolchain.
