### ISSUE TITLE
clang++ vscode mac os compilation problem

### ISSUE THREAD

**Issue by agathelhm** [microsoft/vscode-cpptools#11062]
Hello, I am having a problem compiling c++ code in vscode on my mac. 
I was following this tutorial : [https://code.visualstudio.com/docs/cpp/config-clang-mac](url)
Except when I try the first compilation I get an error :` " launch: program '/Users/Agathe/projects/helloworld/helloworld' does not exist ".`

This is the launch.json file : 
`{
    // Utilisez IntelliSense pour en savoir plus sur les attributs possibles.
    // Pointez pour afficher la description des attributs existants.
    // Pour plus d'informations, visitez : https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
          "name": "C/C++: clang++ build and debug active file",
          "type": "cppdbg",
          "request": "launch",
          "program": "${fileDirname}/${fileBasenameNoExtension}",
          "args": [],
          "stopAtEntry": true,
          "cwd": "${workspaceFolder}",
          "environment": [],
          "externalConsole": false,
          "MIMode": "lldb",
          "preLaunchTask": "C/C++: clang++ build active file"
        }
      ]
}`

I was able to compile using the command `g++ -std=c++11 helloworld.cpp -o helloworld` but how don't know how to apply this method in the case where I have a CMakeLists file.

I also have a warning ` warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const string& word : msg)`
and part of my c_cpp_properties.json file is `"cStandard": "c17",
            "cppStandard": "c++11",`

**Comment by bobbrow** [comment]
Hi there.  Sorry this issue didn't get any attention earlier.  We made an improvement in version 1.17 to make the play button work for the sample code on mac.  The sample code uses C++11 features, but Apple's version of clang does not compile with C++11 features enabled by default.

To set a specific standard version in your CMakeLists.txt, use:
```
set(CMAKE_CXX_STANDARD 11)
```
(source: https://stackoverflow.com/questions/10851247/how-do-i-activate-c-11-in-cmake)
