### ISSUE TITLE
no go to definition

### ISSUE THREAD

**Issue by golf-gl** [microsoft/vscode-cpptools#11074]
Type: <b>Bug</b>

missing go to definition

Extension version: 1.15.4
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Remote OS version: Linux x64 3.10.107-1-tlinux2_kvm_guest-0049

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.89GB (21.57GB free)|
|Process Argv|--crash-reporter-id 5be6109e-1b99-4fb8-8ac9-d2bc582de2b2|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: 9.134.184.226|
|OS|Linux x64 3.10.107-1-tlinux2_kvm_guest-0049|
|CPUs|AMD EPYC 7K62 48-Core Processor (8 x 2595)|
|Memory (System)|15.42GB (13.50GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpathcf:30739705
dh2dc718:30763024

```

</details>

**Comment by Colengms** [comment]
Hi @golf-gl .  I'm afraid we don't have enough information to investigate this issue.  `Go To Definition` seems to be working in a simple scenario and for the majority of users.  Can you provide any further information that might enable us to reproduce the issue you're seeing?

**Comment by golf-gl** [comment]
Hi there,

It worked before but suddenly won't work several days ago, have no idea why. I have tried uninstall vs, as well as all extensions but no help.

I googled and found out some users also encountered this problem, checkout this link out https://stackoverflow.com/questions/37341849/vscode-go-to-definition-not-working. The solution does not work for me though.

Kindly let me know if you need anything further information.

Regards,
Golf
***@***.***?v=73d79a89bded]<https://stackoverflow.com/questions/37341849/vscode-go-to-definition-not-working>
VSCode "go to definition" not working<https://stackoverflow.com/questions/37341849/vscode-go-to-definition-not-working>
I installed Visual Studio Code 1.1 with the C/C++ extension, opened my C++ project and tried to use "Go to definition" in vain. The "Go to definition" is not working at all. Example, go to definit...
stackoverflow.com

________________________________

**Comment by Colengms** [comment]
Hi @golf-gl .  Issues with various C/C++ Extension features are often related to how it's been configured. For example, if include paths are not set up, the header containing a definition may not be findable.  Could you go to our [`Bug Report - Language Service` form](https://github.com/microsoft/vscode-cpptools/issues/new/choose) and provide the information requested there, particularly the `Configuration and Logs` section?

Or, could you create a simple stand-alone repro of the issue you're seeing, and provide that in the form of a zip file or GitHub repo, so that we might use to that investigate further?
