### ISSUE TITLE
Cannot open source file "sys/time.h"

### ISSUE THREAD

**Issue by ettore-passaro** [microsoft/vscode-cpptools#1107]
I'm using Unreal Engine 4.18 and coding with VSCode. In the project header I included the Core.h which includes all the libraries necessary to the project, included sys/time.h. Thing is, I get the "#include errors detected" error with IntelliSense, specifically: 

> 'cannot open source file "sys/time.h" (dependency of "Core.h")'.

I didn't get the error yesterday, but today I updated VSCode and the vscode-cpptools to their latest versions, and this issue showed up.
The c_cpp_properties.json file has this in the Win32 include path:
```
"includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/include/*",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/um",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/shared",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/winrt",
                "${workspaceRoot}",
                "${workspaceRoot}/Intermediate",
                "E:/Epic Games/UE_4.18/Engine/Source/Runtime/",
                "E:/Epic Games/UE_4.18/Engine/Source/Runtime/Engine/Classes",
                "E:/Epic Games/UE_4.18/Engine/Source/Runtime/Core/Public",
                "E:/Epic Games/UE_4.18/Engine/Source/Runtime/Core/Public/Containers",
                "E:/Epic Games/UE_4.18/Engine/Source/Runtime/Core/Public/Templates",
                "E:/Epic Games/UE_4.18/Engine/Source/Runtime/Core/Public/HAL"
            ],
```

**Comment by sean-mcmanus** [comment]
Do you get a code action for adding the missing path? What is the full path of the sys/time.h file?

**Comment by ettore-passaro** [comment]
It didn't show any code action, it just told me to modify the includePath, but I made a broader search into Unreal's install folder and I managed to find the correct file, which was in a completely different folder than the ones I already added.
I'm sorry I filed a wrong issue. I'll try harder next time.
Thank you anyway for the fast answer and for your help.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
