### ISSUE TITLE
vector is leaking memory?

### ISSUE THREAD

**Issue by taaheer** [microsoft/vscode-cpptools#11079]
### Environment

- OS and Version: **Ubuntu 23.04**, **Linux 6.2.0-20-generic**
- VS Code Version: **1.79.0**
- C/C++ Extension Version:  **1.15.4**
- Compiler: **GCC/G++**
- Compiler Version: **(Ubuntu 12.2.0-17ubuntu1) 12.2.0**
- C_Cpp: Intelli Sense Engine: **Default**
- Enabled flags in G++ 
>                 "-std=c++23",          
>                 "-Wall",                
>                 "-Wextra",         
>                 "-Wshadow",             
>                 "-Wnon-virtual-dtor",   
>                 "-pedantic",             
>                 "-Wold-style-cast",
>                 "-Wcast-align",
>                 "-Wunused",
>                 "-Woverloaded-virtual",
>                 "-Wpedantic",
>                 "-Wconversion",
>                 "-Wsign-conversion",
>                 "-Wmisleading-indentation",
>                 "-Wduplicated-cond",
>                 "-Wduplicated-branches",
>                 "-Wlogical-op",
>                 "-Wnull-dereference",
>                 "-Wuseless-cast",
>                 "-Wdouble-promotion",
>                 "-Wformat=2",
>                 "-Wimplicit-fallthrough",
>                 "-Weffc++",
>                 "-fanalyzer",
>                 "-fdiagnostics-color=always",
>                 "-ggdb",
>                 "-Werror",

### Bug Summary and Steps to Reproduce

Bug Summary: Getting error about vector leaking memory

Steps to reproduce:
1. write this code
```
int main()
{
    std::vector<int> vec(2);
    vec[0] = 7;
    vec[1] = 2;
    std::cout << "Success!\n";

    return 0;   
}
```
2. Try to compile it and you will get this error.
`leak of ‘vec.std::vector<int>::<anonymous>.std::_Vector_base<int, std::allocator<int> >::_M_impl.std::_Vector_base<int, std::allocator<int> >::_Vector_impl::<anonymous>.std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data::_M_start’ [CWE-401] [-Werror=analyzer-malloc-leak]`

Expected behavior:
output: Success!

### Configuration and Logs

```shell
-------- Diagnostics - 13/06/2023, 16:10:28
Version: 1.15.4
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/aiden/Visual Studio Code/**"
    ],
    "defines": [],
    "cStandard": "c17",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "cppStandard": "c++23",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "configurationProviderInCppPropertiesJson": "ms-vscode.cmake-tools",
    "mergeConfigurations": false,
    "compilerPath": "/usr/bin/g++-12",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/home/aiden/Visual Studio Code/SDL2"
    ],
    "compilerPath": "/usr/bin/g++",
    "compilerArgs": [],
    "compilerFragments": [
        "-g",
        "-Wall",
        "-Wextra",
        "-Wshadow",
        "-Wnon-virtual-dtor",
        "-pedantic",
        "-Wold-style-cast",
        "-Wcast-align",
        "-Wunused",
        "-Woverloaded-virtual",
        "-Wpedantic",
        "-Wconversion",
        "-Wsign-conversion",
        "-Wmisleading-indentation",
        "-Wduplicated-cond",
        "-Wduplicated-branches",
        "-Wlogical-op",
        "-Wnull-dereference",
        "-Wuseless-cast",
        "-Wdouble-promotion",
        "-Wformat=2",
        "-Wimplicit-fallthrough",
        "-Weffc++",
        "-fanalyzer",
        "-Werror",
        "-std=gnu++23"
    ]
}
Translation Unit Mappings:
[ /home/aiden/Visual Studio Code/Principles and Practice/class first program.cpp ]:
    /home/aiden/Visual Studio Code/Principles and Practice/class first program.cpp
Translation Unit Configurations:
[ /home/aiden/Visual Studio Code/Principles and Practice/class first program.cpp ]:
    Process ID: 19926
    Memory Usage: 58 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/include/c++/12
        /usr/include/x86_64-linux-gnu/c++/12
        /usr/include/c++/12/backward
        /usr/lib/gcc/x86_64-linux-gnu/12/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++23
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=120200
Total Memory Usage: 58 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 6675
```

**Comment by aiden47** [comment]
but this says its from cpptools

```
[{
	"resource": "/home/aiden/Visual Studio Code/Principles and Practice/class first program.cpp",
	"owner": "cpptools",
	"severity": 8,
	"message": "leak of ‘vec.std::vector<int>::<anonymous>.std::_Vector_base<int, std::allocator<int> >::_M_impl.std::_Vector_base<int, std::allocator<int> >::_Vector_impl::<anonymous>.std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data::_M_start’ [CWE-401] [-Werror=analyzer-malloc-leak]",
	"source": "gcc",
	"startLineNumber": 13,
	"startColumn": 1,
	"endLineNumber": 13,
	"endColumn": 1
}]
```
