### ISSUE TITLE
compiler shows errors but visual studio code editor does not show any basic errors in syntax

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11075]
compiler shows errors but visual studio code editor does not show any basic errors in syntax

For Example:
```cpp
#include <iostream>
 using namespace std;
 int main() 
{ 
cout << "Line One\n";
 cout << "Line Two\n"
  cout << "Line Three\n";
 return 0;
 this is a comment without "//" 
}
```
NO Formatting or shows syntax error by editor

How can i solve this problem ?

_Originally posted by @Fady2007 in https://github.com/microsoft/vscode-cpptools/issues/11027#issuecomment-1575548546_

**Comment by bobbrow** [comment]
You may also want to check if VS Code is treating the file as C++.  It should show you in the status bar.
![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/7a9291e4-04c2-4ae0-a7ea-0a36b4ff9dd9)
