### ISSUE TITLE
C. Autocomplete not show local variables

### ISSUE THREAD

**Issue by ithamsteri** [microsoft/vscode-cpptools#1108]
**Operation system:** Manjaro Linux x64
**Compilators:** gcc 7.2.0, clang 5.0.0
**VS Code:** 1.17.0
**vscode-cpptools:** 0.13.1

Autocomplete don't have local variables in list.
Default settings for vscode-cpptools and VS Code. Changing "C_Cpp.intelliSenseEngine" setting on "Default" not fix problem.

```c
// file: example.c
#include <stdio.h>

void example(int number) {
   char mychar;

   // If start type 'my' -> autocomplete not contain 'mychar' variable
}

void use_function() {
    // If start type 'examp' -> autocomplete work for my functions
}

```

![screenshot_20171007_101525](https://user-images.githubusercontent.com/208579/31305696-8221d31a-ab48-11e7-8e34-73503459f668.png)

![screenshot_20171007_102357](https://user-images.githubusercontent.com/208579/31305742-a41200ca-ab49-11e7-804d-eabf4c1635d7.png)

**Comment by sean-mcmanus** [comment]
This is currently "by design" and the autocomplete for local variables is being tracked by https://github.com/Microsoft/vscode-cpptools/issues/13 .
