### ISSUE TITLE
Localization Walkthrough - There is an extra parenthesis for "ordinary shell" in CHS

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#11088]
Note:
- Repro language: CHS.
- No Repro languages: 12 languages other than CHS.
- This is only for the Windows platform walkthrough.

ENU:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/1ff03dfa-794e-4b1a-af32-e1170d8c9c60)

CHS has extra parenthesis:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/c7b445ff-e4f8-468b-b491-84f3e33ecfb3)

CHT no extra parenthesis:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/d44802bf-80bc-4676-be35-8c4a2ba5b228)

**Comment by v-ericawu** [comment]
Depending on the actual linguistic context CHS version is translated correctly (parentheses are required), **CHT version is translated incorrectly** (should be parentheses as in the CHS context)

**Expected Result:**
CHS:
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/93403e72-6233-4e47-90be-481668d16c6d)

CHT:
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/c503cec4-cf1d-4dba-87a9-a7e16601d93a)

**Comment by bobbrow** [comment]
@v-ericawu it looks like this issue was never reported to the Localization team and it's unclear to me what exactly we should report.  In English the parentheses don't belong there and if the parentheses should exist on CHS, there should be 3 items within them (PowerShell, Bash, Windows Command Prompt), not 2.

Also it appears that "shell" might have been translated in CHT, but not CHS.

**Comment by v-ericawu** [comment]
@bobbrow 
1. According to the Chinese language environment, the brackets in this sentence are correct in CHS: An ordinary shell only includes (**PowerShell, Bash**)
Therefore, the actual result now is that the CHS translation is correct, while the CHT translation is incorrect.
And the CHT should be expected to translate as:
備註: 若要從命令列或 VS Code 使用 MSVC，您必須從 VS 的開發人員命令提示 執行。**一般殼層(例如 PowerShell、Bash)或 Windows 命令提示字元**，沒有設定必要的路徑環境變數集。

Actual Result in CHT:
![Image](https://github.com/user-attachments/assets/121479cf-d2bd-48e2-b8b0-b13a976df10d)

2. The “shell” does not need to be translated in CHS but only in CHT:
https://termstudio.microsoft.com/
![Image](https://github.com/user-attachments/assets/28715849-7958-4bee-ad99-ad5428db1352)

**Comment by bobbrow** [comment]
> 1. According to the Chinese language environment, the brackets in this sentence are correct in CHS: An ordinary shell only includes (**PowerShell, Bash**)

This is not the intent of the original English.  The original string says "ordinary shell" meaning "one that does not have the correct environment variables set" and it includes PowerShell, Bash, and the Windows Command Prompt.  The environment variables are only set when running the "Developer Command Prompt for VS" or "Developer PowerShell for VS" shortcuts.

**Comment by v-ericawu** [comment]
@bobbrow Got it, so the actual result is incorrectly translated in CHS and correctly translated in CHT.
In CHS it should be translated as follows: Remove the parentheses or there should be 3 items in the parentheses (PowerShell, Bash, Windows Command Prompt)

**Remove the parentheses:**
注意: 要从命令行或 VS Code 使用 MSVC，必须从 VS 的开发人员命令提示 运行。普通 shell，例如 PowerShell、Bash或 Windows 命令提示符未设置必要的路径环境变量。
**There should be 3 items in the parentheses (PowerShell, Bash, Windows Command Prompt):**
注意: 要从命令行或 VS Code 使用 MSVC，必须从 VS 的开发人员命令提示 运行。普通 shell (例如 PowerShell、 Bash或 Windows 命令提示符)未设置必要的路径环境变量。

**Comment by bobbrow** [comment]
@v-ericawu, thank you for the guidance. A new loc bug has been opened.

**Comment by bobbrow** [comment]
@v-ericawu  this should be addressed starting in version 1.23.2

**Comment by v-ericawu** [comment]
@bobbrow Verified on C/C++ v1.23.2 (pre-release), this issue has been fixed:

![Image](https://github.com/user-attachments/assets/43ca0205-d68d-4a6d-84bd-e25fed6400c7)
