### ISSUE TITLE
Language Status experiment shows for all users in experiment

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#11083]
The current language status experiment is being rolled out to 50% of users but there is an error in logic which shows 100% of users the experimental UI.

**Comment by michelleangela** [comment]
This feature also be disabled if `C_Cpp: Experimental Features` is disabled. The default value of `C_Cpp: Experimental Features` is enabled. If it set to disabled, it means a user explicitly do not want to use the experimental features and it should be disabled for that user.
