### ISSUE TITLE
Localization Walkthrough - One more '提示' in 'Developer Command Prompt' in CHS 

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#11089]
Note:
- Repro language: CHS.
- No Repro languages: 12 languages other than CHS.
- This is only for the Windows platform walkthrough.

ENU:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/1e83b415-8df1-4da1-8b9a-0f6850c23c69)

CHS:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/6f4dbad7-89c3-4340-943f-b44175d7f807)

See below for relevant translations
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/880a62e2-cdaa-4592-b282-5fac80a2c272)

**Comment by bobbrow** [comment]
Localization bug  opened. The fix should arrive through the Loc process.
