### ISSUE TITLE
Incorrect typedef deduced

### ISSUE THREAD

**Issue by iam-TJ** [microsoft/vscode-cpptools#11091]
### Environment

- OS and Version: Debian 11 Bullseye amd64
- VS Code Version: 1.79.1
- C/C++ Extension Version: 1.15.4 

### Bug Summary and Steps to Reproduce

Bug Summary: Incorrect typedef is deduced which causes a reported "undefined function" symbol

Possibly related to issue #10367 (closed)  "typedef may not be parsed correctly if using ()"

1. Create a Linux kernel project on mainline kernel source-code
2. Open `drivers/video/fbdev/core/cfbfillrect.c`
3. Navigate to function definition `cfb_fillrect()`
4. See the error squiggle on the equals symbol on the line `u32 bpp = p->var.bits_per_pixel;`
5. Goto Definition of `u32`
6. Shows `include/acpi/actypes.h` around line 1034
```
typedef u32
 (ACPI_SYSTEM_XFACE * acpi_osd_handler) (void *context);
```
If doing a linear search of the `include` directory this turns out to be the last match for the regular expression  `u32$` in the first file with a match when the files are ordered lexically - in other words, when directory/file-names are processed in alphanumeric order `include/acpi/actyles.h` is the first file matching the regular expression.

This is made even stranger because there is a guarded ACPI definition of `u32` earlier in the same file (also not the correct definition):
```
#if ACPI_MACHINE_WIDTH == 64

#ifndef ACPI_USE_SYSTEM_INTTYPES

typedef unsigned int u32;
```

Expected behavior:

The correct typedef for `u32` is most likely at:
```
$ grep -rn ' u32;$' include
...
include/asm-generic/int-ll64.h:21:typedef __u32 u32;
...
```
Following the `#includes` ends at the same conclusion:
```
drivers/video/fbdev/core/cfbfillrect.c #include <asm/types.h>
  arch/powerpc/include/asm/types.h #include <uapi/asm/types.h>
    arch/powerpc/include/uapi/asm/types.h # include <asm-generic/int-ll64.h>
      include/asm-generic/int-ll64.h typedef __u32 u32
```

Note that the above reflects that the project is currently configured for (cross-)building a PowerPC 64-bit kernel.

### Configuration and Logs

```shell
$ cat .vscode/c_cpp_properties.json 
{
    "configurations": [
        {
            "name": "Linux",
            "cStandard": "c11",
            "intelliSenseMode": "gcc-x64",
            "compileCommands": "${workspaceFolder}/compile_commands.json"
        }
    ],
    "version": 4
```

```
idle loop: reparsing the active document
Checking for syntax errors: /srv/NAS/Sunny/SourceCode/linux/drivers/video/fbdev/core/cfbfillrect.c
Queueing IntelliSense update for files in translation unit of: /srv/NAS/Sunny/SourceCode/linux/drivers/video/fbdev/core/cfbfillrect.c
LSP: cpptools/getFoldingRanges: file:///srv/NAS/Sunny/SourceCode/linux/drivers/video/fbdev/core/cfbfillrect.c (id: 597)
LSP: cpptools/getCodeActions: file:///srv/NAS/Sunny/SourceCode/linux/drivers/video/fbdev/core/cfbfillrect.c (id: 598)
LSP: cpptools/getSemanticTokens: file:///srv/NAS/Sunny/SourceCode/linux/drivers/video/fbdev/core/cfbfillrect.c (id: 599)
Error squiggle count: 17
Error squiggle count: 1
Error squiggle count: 2
Error squiggle count: 1
Update IntelliSense time (sec): 0.316
LSP: cpptools/getSemanticTokens: file:///srv/NAS/Sunny/SourceCode/linux/drivers/video/fbdev/core/cfbfillrect.c (id: 600)
LSP: cpptools/getFoldingRanges: file:///srv/NAS/Sunny/SourceCode/linux/drivers/video/fbdev/core/cfbfillrect.c (id: 601)
LSP: cpptools/getCodeActions: file:///srv/NAS/Sunny/SourceCode/linux/drivers/video/fbdev/core/cfbfillrect.c (id: 602)
LSP: cpptools/getInlayHints: file:///srv/NAS/Sunny/SourceCode/linux/drivers/video/fbdev/core/cfbfillrect.c (id: 603)
```
```


### Other Extensions

No other extensions
[ccpp-log-diagnostics.txt](https://github.com/microsoft/vscode-cpptools/files/11744248/ccpp-log-diagnostics.txt)


### Additional context

_No response_

**Comment by Colengms** [comment]
Hi @iam-TJ .  I'm having a difficult time replicating the scenario as described.  Would it be possible for you to isolate this into a simple repro that you could share with us in the form of a zip file or a GitHub repo?

**Comment by iam-TJ** [comment]
I'm not sure I can - I only installed VS Code to find out if it could be useful in working on the kernel but due to this issue it is too unreliable.
