### ISSUE TITLE
When the mouse hovers over the place where the macro is expanded, the identifier in the previewed Object code is displayed as a wide byte code.

### ISSUE THREAD

**Issue by w4454962** [microsoft/vscode-cpptools#11090]
### Feature Request

![image](https://github.com/microsoft/vscode-cpptools/assets/24670862/21cb0187-cd0e-4235-bef6-aca7d6625d49)

**Comment by sean-mcmanus** [comment]
@Colengms Do we have repro code for this? Is this a world ready, encoding bug? A bug shared with VS?
