### ISSUE TITLE
 C/C++ include <header_with_underscore> not found

### ISSUE THREAD

**Issue by m-j-w** [microsoft/vscode-cpptools#111]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:
1. install the C/C++ extension
2. set the include path correctly to the system headers' directory in c_cpp_properties.json
3. create a new C++ file that includes e.g. `<array>` and `<type_traits>`
4. observe that `<array>` is found, but `<type_traits>` is not, although both being in the same directory.

![image1](https://cloud.githubusercontent.com/assets/14040010/17051916/6a5f16e2-4ffb-11e6-81a5-a60edd41ff9c.png)

Tested on Windows with Cygwin, Mingw64 and MSVC header directories. Same behaviour for all of them. Restarting VS Code doesn't solve the problem.

**Comment by m-j-w** [comment]
It also appears that the underscore only affects include files without file extension. E.g. 

```
#include <boost/fusion/algorithm/iteration/for_each.hpp>
```

works quite fine.

**Comment by jgoshi** [comment]
![image](https://cloud.githubusercontent.com/assets/19478941/17194207/91a673da-53f2-11e6-9cc8-f267bade00df.png)
This works with the latest c++ extension (version 0.8.0). If you want any updates you make to the extensionless file to be parsed (for browsing) you need to update the file type as shown in the attached screenshot.
