### ISSUE TITLE
Alternate format styles do not respect tab settings

### ISSUE THREAD

**Issue by aahaselgrove** [microsoft/vscode-cpptools#1110]
OS: Windows 10 version 1703
VS Code version 1.17.0
C/C++ extension version 0.13.1

Today I tried choosing a different format style (using "C_Cpp.clang_format_fallbackStyle"), and it seems that styles other than 'Visual Studio' do not respect the editor tab setting. For example, using "C_Cpp.clang_format_fallbackStyle": "Google", with Spaces: 4 on the toolbar, I get 2-space formatting.

Current workaround: specify spaces in the style (eg. "C_Cpp.clang_format_fallbackStyle": "{BasedOnStyle: Google, IndentWidth: 4}"), but this renders "editor.detectIndentation" useless.

**Comment by Colengms** [comment]
It looks like "Visual Studio" is a synthetic clang-format style.  For that style, we construct a command line to clang-format based on the LLVM style, with an IndentWidth and TabWidth based on the VS Code tab size, and various other settings.  For all other styles, we are using the predefined clang-format styles without changes.

Is this by-design, or should we always override the clang-format styles with the tab sized passed to us by VS Code?

**Comment by bobbrow** [comment]
We could add a setting that allows you to override the tab width with the one provided by VS Code.  This would be a feature request.

**Comment by bobbrow** [comment]
We won't be making any changes to the default styles.  The second case you offered ("BasedOn": Google) could work if we do the feature requested in #5736.  I think we'll track this request with that issue instead.
