### ISSUE TITLE
Support for embedded microcontrollers (E.g. STM32g0).

### ISSUE THREAD

**Issue by umangkaswala** [microsoft/vscode-cpptools#11107]
### Feature Request

Hello,

There is no proper support for integrating VS Code for embedded programming(C/C++).

I wanted to integrate my IAR compiler with the extension but it was impossible. Reason: The extension is not able to find the compiler (even after giving the specific path)

There is a vast community using C/C++ for programming embedded devices using microcontrollers. And may many companies are also integrating VS Code into their development process. As a result, I see a vast community wanting to use the extension and VS Code in this direction.

Thank you,
Umang Kaswala

**Comment by bobbrow** [comment]
We are actually working on some improvements in this area.  [#6931](https://github.com/microsoft/vscode-cpptools/issues/6931) will hopefully be available in version 1.18 and we plan to add some support for IAR's compiler and a few others.
