### ISSUE TITLE
content is displayed repeatedly when the mouse is hovering

### ISSUE THREAD

**Issue by xujian2019** [microsoft/vscode-cpptools#11106]
### Environment

vscode：1.79.2

### Bug Summary and Steps to Reproduce

Hi, I'm having a problem with vscode levitating. When I levitate over a function, its content is repeatedly displayed
![image](https://github.com/microsoft/vscode-cpptools/assets/50616753/f863b427-f878-4f4c-a6b4-82817a00b1c2)

### Configuration and Logs

```shell
none
```

**Comment by sean-mcmanus** [comment]
What language are you using? Is "var" supposed to be a C/C++ type or JavaScript/TypeScript?

That could be caused by C_Cpp.intelliSenseEngine set to "Tag Parser" or the IntelliSense process may not be finished initializing yet.

**Comment by xujian2019** [comment]
I am currently using typescript.This problem occurs on the latest version of vscode, and it also occurs on my colleague's computer.It can be excluded that IntelliSense has been initialized.

**Comment by sean-mcmanus** [comment]
This is the repo for the C/C++ extension. For TypeScript, you should file a bug at https://github.com/microsoft/vscode/issues or https://github.com/microsoft/TypeScript/issues .
