### ISSUE TITLE
Editor indentation incorrect around tabbed function parameters

### ISSUE THREAD

**Issue by aahaselgrove** [microsoft/vscode-cpptools#1111]
OS: Windows 10 version 1703
VS Code version 1.17.0
C/C++ extension version 0.13.1

Indentation does not seem to work correctly for multi-line function signatures. It is based off the indentation on the previous line, rather than the appropriate scope (which in this case, is the indentation level of the first line of the function).

Outcome after typing the following, and pressing enter between the braces. '|' represents the cursor position.

Expected:
```
void test(int first, int second,
        int third) {
    |
}

void test2(int first, int second,
           int third) {
    |
}
```

Actual:
```
void test(int first, int second,
        int third) {
        |
    }

void test2(int first, int second,
           int third) {
               |
           }
```

I don't know if this belongs here in cpptools or in vscode, please let me know if it should be moved.

**Comment by sean-mcmanus** [comment]
The issue reproduces without the cpptools extension, so can you file a bug with VS Code itself? It's possible they may ask us to implement better support as a feature request.

**Comment by aahaselgrove** [comment]
https://github.com/Microsoft/vscode/issues/35952

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.
