### ISSUE TITLE
VSCode recognizing certain CUDA specific tokens.

### ISSUE THREAD

**Issue by anoban** [microsoft/vscode-cpptools#11129]
### Feature Request

Hi there! I'm on Windows 11, using VSCode to develop (learn, actually) CUDA applications. I'm aware that NVIDIA's official `Nsight Visual Studio Code Edition` doesn't support development on Windows, and I'm relying on MS's C/C++ tools for basic editing assistance (hover hints, autocomplete suggestions, and syntax highlighting) and the experience has been descent so far except for a minor inconvenience.

I don't know how the VSCode's C/C++ extension's parser works, but the CUDA tokens `<<<` and `>>>` used to launch GPU kernels seem not to be recognized by VSCode's parser/lexer. VSCode recognizes the first `<<` as one token (perhaps as a C++ iostream std::cout `<<` token?) and the second `<` as two separate tokens and automatically inserts a space between them, so a `<<<` token gets split into `<< <` and an expression like `<<<n_blocks, n_thread_per_block>>>` becomes `<< <n_blocks, n_thread_per_block> >>`.

I do understand that this is not a critical issue, but it is annoying. Is there a way users can add custom tokens to VSCode's lexer or does this need to be done by the developers? I'd like to know whether this is possible and if not could this feature be possibly implemented in future releases of VSCode?

P.S: I have the same issue in Visual Studio as well. (VS2022). I'm annexing pictures for reference. Thank you.

![Screenshot (46)](https://github.com/microsoft/vscode-cpptools/assets/99625466/432f527b-4a96-4e4c-9a60-03de6a55c857)
![Screenshot (47)](https://github.com/microsoft/vscode-cpptools/assets/99625466/be84eca0-184c-47a0-9a50-9efa1e706a55)

**Comment by bobbrow** [comment]
Hi there.  I'm not a CUDA dev, but my understanding of this token is that it does not support spaces between the `<` and `>` characters and must be typed as `<<<` or `>>>` explicitly to be recognized.  Does `nvcc` accept spaces between those characters when you compile?  We worked with nVidia to get the code support for this language extension so I didn't think so.

**Comment by bobbrow** [comment]
Or is this an issue with the formatter splitting your tokens?  Which formatter setting do you use, `clangFormat` or the Visual Studio formatter `vcFormat`?

**Comment by anoban** [comment]
Hi there, thanks for the response. nvcc does not seem to mind the space. It compiles the code just fine with a space splitting those tokens as `<< <` and `>> >`. I've even checked the source with Notepad++, the space is still there, but compilation works just fine (It doesn't even issue a warning about the split tokens). 

![Screenshot (74)](https://github.com/microsoft/vscode-cpptools/assets/99625466/8182d946-ece2-453f-9650-9494dcd98f75)


![Screenshot (75)](https://github.com/microsoft/vscode-cpptools/assets/99625466/92b04461-0429-460e-a43e-cc5ade1c0cd5)


I'm using vcFormat in VSCode since I'm not a fan of clang-format's defaults and honestly don't fancy setting up custom configs for formatting. Since you mentioned, I'm starting to wonder this could be a doing of vcFormat because I get the same issue in VisualStudio as well.

**Comment by bobbrow** [comment]
If you delete the spaces do the errors go away?  And if you run the formatter after that do the spaces return?

**Comment by Colengms** [comment]
Hi @anoban .

> P.S: I have the same issue in Visual Studio as well. (VS2022). I'm annexing pictures for reference. Thank you.

Have you opened a similar issue against Visual Studio, on https://developercommunity.visualstudio.com/ ?  If so, we should inherit a fix associated with that, as the IntelliSense component is shared between VS and the C/C++ Extension for VS Code.

Let me know if you haven't opened an issue against VS and would prefer not to, and I'll follow up with opening an issue for this internally.

**Comment by Colengms** [comment]
Hi @anoban .

To redirect, it looks like the CUDA support in the C/C++ Extension is actually its own implementation, not shared with VS.

> but the extension seems not to recognize <<< and >>> as valid tokens.

The formatting issue aside, I'm unable to reproduce an IntelliSense issue with `<<<`/`>>>`.  These appear to be handled properly for me in a simple example.  If you are seeing an issue with these that is unrelated to formatting, could you provide a simple, stand-alone example that we might use to reproduce the issue and investigate further?

**Comment by anoban** [comment]
Okay, here's an example https://github.com/anoban/CUDA/tree/main/vscode-issue (It's a VS solution, so please open the `kernel.cu` file in VSCode), (It's Hello world equivalent of CUDA, that VisualStudio's CUDA extension provides on opening new CUDA projects). 

I disabled the formatters, and here are the errors from intellisense.
![Screenshot (88)](https://github.com/microsoft/vscode-cpptools/assets/99625466/07614d21-caf5-422e-be08-7b55b01a8160)
![Screenshot (89)](https://github.com/microsoft/vscode-cpptools/assets/99625466/2bcfe50d-8e48-4099-a178-1f7228194e3f)
![Screenshot (90)](https://github.com/microsoft/vscode-cpptools/assets/99625466/da2d23ba-aa4a-4747-9005-c2d6c096e8f0)

Here are my C/C++ extension configs, in case they are helpful.

```json

"C_Cpp.autocompleteAddParentheses": true,
    "C_Cpp.codeFolding": "disabled",
    "C_Cpp.default.cStandard": "c17",
    "C_Cpp.inlayHints.autoDeclarationTypes.enabled": true,
    "C_Cpp.inlayHints.autoDeclarationTypes.showOnLeft": true,
    "C_Cpp.inlayHints.parameterNames.enabled": true,
    "C_Cpp.vcFormat.indent.preprocessor": "oneLeft",
    "C_Cpp.vcFormat.indent.caseContentsWhenBlock": true,
    "C_Cpp.vcFormat.indent.caseLabels": true,
    "C_Cpp.vcFormat.newLine.beforeCatch": false,
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.block": "sameLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.function": "sameLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.type": "sameLine",
    "C_Cpp.vcFormat.newLine.closeBraceSameLine.emptyFunction": true,
    "C_Cpp.vcFormat.newLine.closeBraceSameLine.emptyType": true,
    "C_Cpp.vcFormat.newLine.scopeBracesOnSeparateLines": true,
    "C_Cpp.vcFormat.space.afterCastCloseParenthesis": true,
    "C_Cpp.vcFormat.space.beforeConstructorColon": false,
    "C_Cpp.vcFormat.space.beforeInheritanceColon": false,
    "C_Cpp.vcFormat.space.betweenEmptyBraces": true,
    "C_Cpp.doxygen.generateOnType": false,
    "C_Cpp.codeAnalysis.clangTidy.enabled": true,
    "editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.organizeImports": true
    },
    "C_Cpp.intelliSenseEngineFallback": "enabled",
    "C_Cpp.clang_format_fallbackStyle": "",
    "C_Cpp.vcFormat.indent.lambdaBracesWhenParameter": false,
    "C_Cpp.vcFormat.indent.namespaceContents": false,
    "C_Cpp.vcFormat.newLine.beforeWhileInDoWhile": true,
    "C_Cpp.vcFormat.space.preserveInInitializerList": false,
    "C_Cpp.intelliSenseUpdateDelay": 500,
    "files.associations": {
        "*.cu": "cuda-cpp"
    },
    "C_Cpp.default.intelliSenseMode": "windows-msvc-x64"
```

**Comment by anoban** [comment]
Hi there, I know this is going to make me look dumb, but It was `clang-tidy`.  
```json
"C_Cpp.codeAnalysis.clangTidy.enabled": false
```
made the squiggles go away. Still wondering why I get then in VS though?

**Comment by Colengms** [comment]
Hi @anoban .

Do you have the CUDA SDK installed on your system?  That's required to enable CUDA support.  If so, which version?

I'm able to open `kernel.cu`, without errors.  

![image](https://github.com/microsoft/vscode-cpptools/assets/49173979/c0ce6566-c9d5-4786-9e68-cb47b8a1c527)

If you do have the CUDA SDK installed, could you provide the output of the `C/C++: Log Diagnostics` command, while the file is open?  That may provide some clues.

There are a few steps involved internally, to enable CUDA support.
 * The file must be associated with the CUDA language ID in VS Code.  (In one of your images, that looks correct.)
 * `nvcc` needs to be (installed and) in the environment/path.  (Or explicated specified by a custom configuration provider or `compile_commands.json`. It's also possible to specify `nvcc` as a `compilerPath`, though that would cause it to be used for C and C++ files as well).
 * `nvcc` is invoked (potentially with provided compiler args) with no actual source file, and its output parsed to detect the command line it would use internally to compile a file with your underlying C++ compiler.  That compile command line is then used to fully configure IntelliSense (plus CUDA support).

If the issue is not apparent from the above information, could you provide the output from the C/C++ channel, from launch until repro, with `"C_Cpp.loggingLevel": "Debug"` set?

**Comment by Colengms** [comment]
>Still wondering why I get then in VS though?

If I understand correctly, our CUDA support is specific to the C/C++ Extension for VS Code.  For VS, I believe you'd need: https://developer.nvidia.com/nsight-visual-studio-edition
