### ISSUE TITLE
pipeTransport: pipeEnv property not working

### ISSUE THREAD

**Issue by lemmsen** [microsoft/vscode-cpptools#11139]
### Environment

- OS and version: Windows 11/WSL (Windows_NT x64 10.0.22621/Debian 11 bullseye)
- VS Code: 1.79.2
- C/C++ extension: 1.16.3

### Bug Summary and Steps to Reproduce

Bug Summary:
My launch.json is using a 'pipeTransport' setup for one of the debug configurations. The 'pipeEnv' option seems to have no effect.

Steps to reproduce:
1. Extract attached zip-file in WSL Linux. I tested it on Debian bullseye, but it shouldn't be relevant.
2. Open VSCode by typing `code .` from within the extracted folder in WSL Linux.
3. Press 'F5' or select 'Start Debugging' from the 'Run' menu.
4. See error message: It should be "Hello World ." but "World" is missing from the output.
![ErrorMessage](https://github.com/microsoft/vscode-cpptools/assets/43368701/24802b0a-c02e-4d69-a97b-775a59e3191f)
I know that my example does not really make sense. I used "echo" only for showing the problem.
[example.zip](https://github.com/microsoft/vscode-cpptools/files/11896117/example.zip)

### Debugger Configurations

```shell
See attached zip-file for details.
```

### Debugger Logs

```shell
See attached png for details.
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
