### ISSUE TITLE
`cpptools.activeConfigCustomVariable` is not available when `C_Cpp.intelliSenseEngine` is set to `disabled`

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-cpptools#11130]
Type: <b>Bug</b>

- set `C_Cpp.intelliSenseEngine` to `disabled`
- start debugging cppdbg/launch config

popup: IntelliSense-related commands cannot be executed when `C_Cpp.intelliSenseEngine` is set to `disabled`.

C/C++ output:
```
loggingLevel: Debug
intelliSenseEngine is disabled
```

intellisense shouldn't be required for debugging. really, the c/c++ debugger should be in a separate extension.

Extension version: 1.16.3
VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.85GB (8.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|23.40GB (14.68GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|23.40GB (14.68GB free)|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue. Do you have a tasks.json and/or lanuch.json created? What command are you running to start the debugging?

**Comment by sean-mcmanus** [comment]
Also, does the issue repro still if you downgrade to version 1.15.4 of the C/C++ extension?

**Comment by Spongman** [comment]
it's `activeConfigCustomVariable` :

`settings.json` :
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "start debugging",
			"type": "cppdbg",
			"request": "launch",
			"program": "/usr/bin/ls",
			"MIMode": "${input:debuggerType}"
		}
	],
	"inputs": [
		{
			"id": "debuggerType",
			"type": "command",
			"command": "cpptools.activeConfigCustomVariable",
			"args": "debuggerType"
		}
	]
}
```

**Comment by bobbrow** [comment]
If IntelliSense is disabled, the `cpptools.activeConfigCustomVariable` command is not available because active configs are an IntelliSense concept and IntelliSense is not running.

**Comment by Spongman** [comment]
> active configs are an IntelliSense concept
that's your bug, right there...

**Comment by bobbrow** [comment]
Sorry, why do you think it's a bug?  The configurations are for IntelliSense, but IntelliSense is disabled, so we don't load them.

**Comment by Spongman** [comment]
I'm not using them for intellisense, i'm using them for launch configuration. disabling intellisense shouldn't disable them.

**Comment by bobbrow** [comment]
Sure, we can mark this as a feature request instead and see if other members of the community have interest in it.

In the meantime though, I would recommend using an input like this:
```
	"inputs": [
		{
			"id": "debuggerType",
			"type": "pickString",
			"description": "Select the MIMode",
			"options": [ "gdb", "lldb" ],
			"default": "gdb"
		}
	]

```

**Comment by Spongman** [comment]
Using a `pickString` type means i have to choose from the UI every time I start debugging.

I have 21 `inputs` defined in my `launch.json` file.

**Comment by bobbrow** [comment]
Yeah, if you have 21 inputs, that wouldn't be a good approach.  In your comment I only saw a single input for a property that had 2 values which is why I suggested it as a workaround.

**Comment by Spongman** [comment]
https://en.wikipedia.org/wiki/Minimal_reproducible_example

**Comment by Spongman** [comment]
anyway. i was able to work around this using the `rioj7.command-variable` extension which allows me to just return a constant value from the `inputs` section of `launch.json`

**Comment by Dilant** [comment]
Not sure if this is the same cause, but I'll post it here.

I'm using vscode on Windows (and build tools from MSYS2), to **edit a single `.cpp` file, without opening a directory, no `launch.json` or `tasks.json` or anything related**. 

When setting `C_Cpp.intelliSenseEngine = default`, I can use `F5` -> `C++ (GDB/LLDB)` -> `C/C++: g++.exe build and debug active file` to instantly start debugging.

But when setting `C_Cpp.intelliSenseEngine = disabled`, I fail to do so. When I press `F5` and click `C++ (GDB/LLDB)`, it returns me this error: `Variable ${workspaceFolder} can not be resolved. Please open a folder.`

IMO `${workspaceFolder}` is nothing related to intellisense.  :/
