### ISSUE TITLE
clang-format segmentation fault

### ISSUE THREAD

**Issue by Benjamin-Tan** [microsoft/vscode-cpptools#11145]
### Environment

- OS and Version: Ubuntu 20.04
- VS Code Version: 1.79.2
- C/C++ Extension Version: 1.16.3
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary: The clang-format that comes alongside with this extension is having segmentation fault

Steps to reproduce:
1. Run `$HOME/.vscode/extensions/ms-vscode.cpptools-1.16.3-linux-x64/LLVM/bin/clang-format` in a terminal, segmentation would occur. clang-tidy binary has no issue at all.

Expected behavior:
no segmentation fault and be able to run clang-format as per normal

### Configuration and Logs

```shell
C/C++ Log Diagnostics
-------- Diagnostics - 6/30/2023, 12:50:02 PM
Version: 1.16.3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/betan/dummy_dir/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerPathInCppPropertiesJson": "/usr/bin/gcc",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.16.3.0
No active translation units.
========================================
Language server logging
Formatting document: file:///home/betan/dummy_dir/a.cpp
Formatting Engine: clangFormat
Formatting failed:
/home/betan/.vscode/extensions/ms-vscode.cpptools-1.16.3-linux-x64/bin/../LLVM/bin/clang-format '-style={ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All, FixNamespaceComments: false }' -fallback-style=LLVM -sort-includes=0 --Wno-error=unknown -assume-filename=/home/betan/dummy_dir/a.cpp
LSP: cpptools/getInlayHints: file:///home/betan/dummy_dir/a.cpp (id: 33)
```

**Comment by sean-mcmanus** [comment]
Are you using 32-bit Linux?

Otherwise, I don't repro this and I don't know what could be causing this. Have you tried uninstalling/reinstalling the extension? What does `/home/betan/.vscode/extensions/ms-vscode.cpptools-1.16.3-linux-x64/bin/../LLVM/bin/clang-format --version` give?

**Comment by Benjamin-Tan** [comment]
I still face segmentation fault upon running `/home/betan/.vscode/extensions/ms-vscode.cpptools-1.16.3-linux-x64/bin/../LLVM/bin/clang-format --version` after reinstalling the extensions.

What I realised was the extensions was not removed cleanly in `$HOME/.vscode/extensions`. I manage to resolve this issue by removing the entire folder `$HOME/.vscode/extensions/ms-vscode.cpptools*` manually, reinstall the extensions and the segmentation fault issue went away.

Thanks for your comment on reinstalling it.
