### ISSUE TITLE
Call Hierarchy should show the function that use it as a parameter

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode-cpptools#11142]
### Feature Request

Thanks for this wonderful tool, and I think there can be an improvement.
---
use scenario:

A function called by another function as 'function parameter'. like: 
```c
void f(void);
void g(void(*func)(void));
...
g(f);
```
call hierarchy should show that `g` is a caller of `f`.    
And there's a inconsistence between `Find Reference` and this functionality: the `Find Ref` will find `g`.

In C code, I think this kind of call hierarchy is normal and important.

Thanks again.

**Comment by michelleangela** [comment]
@JoeyRxy 
Thank you for submitting this feature. However, it is by design that call hierarchy does not find references to functions used as a parameter. This is because a function as a parameter is not a function call, but is being used as a parameter. Also, the actual function of `void(*func)(void)` in `void g(void(*func)(void))` is not determined until runtime.

**Comment by JoeyRxy** [comment]
> @JoeyRxy Thank you for submitting this feature. However, it is by design that call hierarchy does not find references to functions used as a parameter. This is because a function as a parameter is not a function call, but is being used as a parameter or a function pointer. A function pointer is a variable that stores the memory address of a function. When the function pointer is called, it will execute the function whose address it holds. Therefore, the actual function of the example `void(*func)(void)` in `void g(void(*func)(void))` is not determined until runtime.

What? I don't think a Microsoft guy should have made such mistakes. 

```c
// Following is two DECLARATIONS, not some runtime code or what!
void f(void);
void g(void(*func)(void));
...
// This is where the `Call Hierarchy` should figure out, I DON'T think this need to be located in RUNTIME
void whatever_the_name() {
    g(f);
}
```

BTW, there's no RUNTIME concept in C/C++, there're only compile or link, I assume you're not very familiar with C/C++. So, I'm wondering, are you the tech guy in your team or not?

Hey, friendly reminder: Think twice before underestimating others as fools, and try to not be so ARROGANT.

**Comment by bobbrow** [comment]
@JoeyRxy It's ok if you disagree with statements that are made on this forum, but we ask that you be respectful of others as is explained in our [Code of Conduct](https://opensource.microsoft.com/codeofconduct/).  Unkind statements are subject to moderation.

**Comment by bobbrow** [comment]
Pasting a full example. 

```cpp
void f(void);
void g(void(*func)(void));

void whatever_the_name() {
    g(f);   // function referenced but not used yet
}

void f()
{
}

void g(void(*func)(void))
{
    func(); // `f` is used here but our engine doesn't know that func == f.
}
```

The way the call hierarchy is implemented doesn't use the compilation of the code, and that is what @michelleangela is referring to as "runtime."  When we look to see what `g` calls, we don't go look at all of the inputs to `g`.  We are just looking at what's inside `g`, not the layer above it.  We can track this as a feature request.

**Comment by JoeyRxy** [comment]
> @JoeyRxy It's ok if you disagree with statements that are made on this forum, but we ask that you be respectful of others as is explained in our [Code of Conduct](https://opensource.microsoft.com/codeofconduct/). Unkind statements are subject to moderation.

I don't know how you define KNID or UNKIND, I don't think this guy @michelleangela is KIND. So arrogant and ignorant. 
Look at what he/she said, use a naive mistake to underestimate me? Even explain those simple concepts to a C/C++ tech guy? I don't think that's a so-called KIND conduct.  And if that is the conduct or standards of your team member, I don't think that's a guy in Microsoft, such a great company, should've done. 

And hey, I don't think your reply about so-called "runtime" is the meaning of @michelleangela 's original post, I think he/she simply just don't know that concept. So what's the difficulty to admit that. Should've bother another guy in team to explain how the mistake is not a mistake? Of course, my point is not about some "runtime" concept, but the knowing-nothing-and-didn't-read-thoroughly and arrogant response of @michelleangela.

And what am I doing here? I've been using clangd, just want to try this tool because of trust for Microsoft and hoping there's something that shines there, and there are great features actually, but I found this little problem so I post this Feature Request, but hey, look at this mess. I'm done with it.
