### ISSUE TITLE
C++ Parsing Never Stops

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-cpptools#1114]
_From @ahmedbilal on October 8, 2017 13:20_

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.9.52-1-MANJARO
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
python|don|0.7.0
Go|luk|0.6.66
cpptools|ms-|0.13.1
preview-vscode|sea|1.3.4
markdown-all-in-one|yzh|0.10.3

(9 theme extensions excluded)

---

Steps to Reproduce:

1. Install Microsoft C/C++ extension.
2. It never stop parsing in Visual Code 1.17

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#35831_

**Comment by bobbrow** [comment]
Can you share more information about your project?  How many files are being parsed?  Is it open source so we can debug locally?  Can you share your c_cpp_properties.json file so we can check the browse.path setting?

**Comment by bobbrow** [comment]
Forgot to mention: @ahmedbilal since this issue was copied from vscode.

**Comment by sean-mcmanus** [comment]
@ahmedbilal Also, checking if your browse database is increasing in size or not would help to see if actual work is being done -- it's located at `/home/<user>/.config/Code/User/workspaceStorage/<guid>/ms-vscode.cpptools/.browse.vc.db` location) or the browse.databaseFilename path in c_cpp_properties.json. Also, enabling logging would probably show what processing is occurring: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md .

**Comment by ahmedbilal** [comment]
@bobbrow It does the same thing on hello world file.
```c
#include <stdio.h>

int main()
{
    printf("Hello World");
}
```
I don't know where c_cpp_properties.json resides. However, here is output of [User Setting > C/C++ Configuration ](https://justpaste.it/1c9xq)

**Comment by ahmedbilal** [comment]
@sean-mcmanus It is increasing in size with time and using 25% of my CPU. I will post my logging details as I get sometime.

**Comment by bobbrow** [comment]
Did you open a folder, or just a single file?  There is an issue on linux/mac where the extension will parse through all of your system's headers if you don't open a folder first.  We have a fix for it, but it isn't available yet.  Does the problem still happen if you open a folder before opening the code file? (just not `/`, `/usr/`, or `/usr/include` - you get the gist)

**Comment by ahmedbilal** [comment]
I tried both and it happened in both cases. Actually the file I opened is on Desktop. And Desktop have only 10-15 files.

**Comment by bobbrow** [comment]
I'm specifically referring to this when I say "open folder".  I just wanted to double check and make sure we're talking about the same thing.

![open folder](https://user-images.githubusercontent.com/12818240/31454370-1818a276-ae6a-11e7-92d9-dbdc11981d26.png)

**Comment by sean-mcmanus** [comment]
@ahmedbilal The database increasing in size with time and using 25% of CPU (all the CPU on one out of four cores) sounds like normal behavior. How big does the database grow and how long is the processing exactly? If it's behaving correctly, it will try to parse all the #include files up the path for stdio.h and any other header files that are #included . c_cpp_properties.json is in the `${workspaceRoot}/.vscode` folder and generated via the Edit Configurations command (otherwise, it uses an internal default).

**Comment by bobbrow** [comment]
For the example provided, that should complete well under a minute.

**Comment by ahmedbilal** [comment]
@bobbrow I close the folder File > Close The Folder. Then open the file it works fine no long parsing.
But, as soon as I opened the folder the parsing never stops. I think there is some issue with parser when some folder is opened.

**Comment by gofawer** [comment]
I have same issue, 
- Visual Code 1.17.2
- ms-vscode.cpptools 0.14.0 
- Linux 4.4.0-96-generic #119-Ubuntu x86_64 GNU/Linux

**Comment by sean-mcmanus** [comment]
@torys2 We need more info. If you hover over the database icon in the bottom right what does it say in the tooltip over time?

**Comment by gofawer** [comment]
@sean-mcmanus, My bad, I didn't notice this icon, thanks for pointing it out, I've opened too big folder where there was ~60k files, when parsing was finished cpu usage dropped out

**Comment by ahmedbilal** [comment]
Ooh. My bad. I opened my desktop folder thinking that it have very few files. But, when I hover over the db icon it says indexing 9849/~100k. Then I looked on my desktop and what I found is linux414 kernel source extracted. oops.
