### ISSUE TITLE
Create definition via `Quick Fix...` hover - not working

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#11157]
Type: <b>Bug</b>

# Scenario 1

1. Create a class
2. Click on the `...`
3. Select `QuickFix: Create definition in <filename>.cpp`

- Nothing happens.

# Scenario 2

1. Create a class
2. COMMAND CLICK ON THE METHOD NAME
2. Click on the `...`
3. Select `QuickFix: Create definition in <filename>.cpp`

- Works.

Also if classes contain nested types these types are not prepended with the class name, e.g.

```c++

namespace N {
class C {
public:
  enum class E;
  struct S;

  std::expected<S, E> GetStuff(const S& s);
};
}
```
Produces: `std::expected<S, E> C::GetStuff(const S& s);`, which is not optimal.

This probably was reported before but I could't find it.

Extension version: 1.16.3
VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.78GB free)|
|Process Argv|--crash-reporter-id a7eaff19-94ae-4653-b917-d9aaab19da5d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnoceb:30776495

```

</details>

**Comment by H-G-Hristov** [comment]
The above scenario is reproduced in a complex CMake based project with conan dependancies, etc.

**Comment by sean-mcmanus** [comment]
I don't understand scenario 1. Where is the "..."? What's an example?

Why is `std::expected<S, E> C::GetStuff(const S& s);` not optimal? What do you consider optimal? Also, that is a declaration, I assume you mean `std::expected<S, E> C::GetStuff(const S& s) {}`.

**Comment by H-G-Hristov** [comment]
These three dots under the method name seem to point to methods without implementation.

![Screenshot 2023-07-10 at 10 32 31](https://github.com/microsoft/vscode-cpptools/assets/47526411/636a1939-77f4-4432-a7d6-380edec79834)

When I hover over them I see a Quick fix in the hover.

![Screenshot 2023-07-10 at 10 34 16](https://github.com/microsoft/vscode-cpptools/assets/47526411/08423e51-1cd3-4f5e-b5ed-2cbc40445fff)

If I click on Quick fix I get the options.

![Screenshot 2023-07-10 at 10 35 45](https://github.com/microsoft/vscode-cpptools/assets/47526411/e274bb06-fdbe-4365-b2bf-b4b3345ece9f)

None of these two options work.


Now, if I cmd+click on the method name first. I can select the method (in this case I have multiple method of the same name in the project): 

![Screenshot 2023-07-10 at 10 34 16](https://github.com/microsoft/vscode-cpptools/assets/47526411/9086279a-6003-49da-afe2-ba68a7ddcab6)

And after I repeat the Quick fix steps above, the method gets generated:

![Screenshot 2023-07-10 at 10 42 42](https://github.com/microsoft/vscode-cpptools/assets/47526411/05d0f2a2-a965-464f-9e3c-348908842fc6)

**Comment by sean-mcmanus** [comment]
Are you able to create a sample code that repros the issue? With the code provided, I get

![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/a17570ce-e937-4d0f-9ea6-9cbcbd48f438)

**Comment by H-G-Hristov** [comment]
@sean-mcmanus On my machine I can reproduce the issue also with this small test project:

[Archive.zip](https://github.com/microsoft/vscode-cpptools/files/12047046/Archive.zip)

Here is a screen recording following the above reproduction steps:

![VSCode-Bug-2-Jul-14-2023 09-43-21](https://github.com/microsoft/vscode-cpptools/assets/47526411/c917e2df-2ac6-4ec4-8cc4-943dfe2b533d)


Also this is a recording of my large CMake based project:

![VSCode-bug-Jul-14-2023 09-24-45](https://github.com/microsoft/vscode-cpptools/assets/47526411/4cb92624-1dcf-4540-b13a-b21acdd6489b)

**Comment by H-G-Hristov** [comment]
> I don't understand scenario 1. Where is the "..."? What's an example?
> 
> Why is `std::expected<S, E> C::GetStuff(const S& s);` not optimal? What do you consider optimal? Also, that is a declaration, I assume you mean `std::expected<S, E> C::GetStuff(const S& s) {}`.

Here is a screenshot:

![Screenshot 2023-07-14 at 10 08 07](https://github.com/microsoft/vscode-cpptools/assets/47526411/196123cc-48cd-45be-99aa-07dc66f8a4e8)

`Error` is defined in the header:

```c++
class PatchManager
{
public:
...
using Error = std::string;
...
::tl::expected<std::filesystem::path, Error> PatchManager::Download();
...
};
```

Maybe I need to fully qualify the names for the generator to do right thing. I guess it is just copying the name and doesn't analyze them?

```c++
class PatchManager
{
public:
...
using Error = std::string;
...
::tl::expected<std::filesystem::path, PatchManager::Error> PatchManager::Download();
...
};
```

**Comment by H-G-Hristov** [comment]
Additional info: If I want to add definitions for multiple methods, I need to repeat the steps for each method, e.g. I need to command+click on each method before selecting the Quick Fix.

**Comment by sean-mcmanus** [comment]
@H-G-Hristov The multiple definitions scenario is tracked by https://github.com/microsoft/vscode-cpptools/issues/10414 .

**Comment by michelleangela** [comment]
I was able to reproduce the issue on Windows too. 

The issue only reproduces when invoking the "Create definition..." code action through:

1. Hover over a function
2. Click on "Quick Fix..." from the tool tip that pops up.
3. Select "Create definition..." from the code action (aka Quick Fix...) selections that pop up.
4. Result: from the language server logs, the request `cpptools/createDeclDef` to create the definition is canceled by the server.

**Note:** when the code action "Create definition..." is invoked via clicking on the Quick Fix light bulb, it works, as described in this issue's "scenario 2".

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.0.

**Comment by michelleangela** [comment]
Fixed in release version https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2.
