### ISSUE TITLE
Semicolon delimited environment variables in includePath seems to be broken again

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#1115]
Appears to be broken again in 0.13.1. Test project attached (super simple).

My %INCLUDE% variable path looks like this:

`C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/include;C:/include`

[test.zip](https://github.com/Microsoft/vscode-cpptools/files/1367280/test.zip)

Original bug here: https://github.com/Microsoft/vscode-cpptools/issues/1001

Tried uninstalling the C++ plugin and reinstalling to no avail.

**Comment by bobbrow** [comment]
I found the bad merge on Sept 14.  Will get this fixed for the next version.

**Comment by azydevelopment** [comment]
Thanks. I can validate whenever.
