### ISSUE TITLE
Anonymous structures and unions do not display correctly in debug views or with natvis (LLDB/GDB)

### ISSUE THREAD

**Issue by KazNX** [microsoft/vscode-cpptools#1116]
Hi,

I've been debugging with some structures containing anonymous unions and structures and have noticed that MacOS + LLDB in particular does not correctly display them in the debugger. My use case is based on the OpenGL Mathematics (GLM) library structure glm::tvec3<>, but a simplified version of the structure is shown below:

```struct UnionVectorA
{
  union
  {
    struct { float x, y, z; };
    struct { float r, g, b; };
    struct { float s, t, p; };
  };
};
```

For variables of this type, MacOS + LLDB show an expandable variable, but on expanding there are no children to display. Using a natvis file to view the structure results in error expressions attempting to access any of the data members, except for 'p', which seems to display as a pointer (without digging, I'm not sure to what).

I've expanded testing to include the following OS/compiler combinations and attached source code to illustrate the issues. Please refer to the comments in main.cpp for steps to reproduce and  results.
- Windows 10 + CDB (Visual Studio 2017). Works as expected with and without natvis.
- Ubuntu 16.04 + GDB 7.11.1. Works without natvis, generates expression errors with.
- MacOS 10.12.6 + LLDB 370.0.42 (XCode 8.3.2 installed). Fails with or without natvis.

[vscode-natvis-bug.zip](https://github.com/Microsoft/vscode-cpptools/files/1367283/vscode-natvis-bug.zip)

**Comment by pieandcakes** [comment]
@KazNX Is this the same as #966?

**Comment by KazNX** [comment]
@pieandcakes yes, this looks like the same issue. I've noted other issues too now with displaying members of base classes. Basically natvis expressions referencing members from a base class won't resolve properly either. Would you like a seperate bug report?

**Comment by pieandcakes** [comment]
@KazNX You can either report it here or the right place for them to actually go is into https://github.com/Microsoft/MIEngine since that is where all the .natvis handling is done.

**Comment by KazNX** [comment]
@pieandcakes I'll report it against MIEngine then. Thanks.

**Comment by pieandcakes** [comment]
@KazNX when using your MacOS scenario, does it work better or worse with the included lldb that we bundle with the extension?

**Comment by KazNX** [comment]
@pieandcakes Sorry, I'm not sure how to change between one or the other. I had assumed that it was finding lldb on the path and using that.

**Comment by KazNX** [comment]
@pieandcakes I've confirmed that the behaviour is identical with either version of LLDB, based on Xcode 9.0 and 9.2.

**Comment by KazNX** [comment]
Please note the additional comments on https://github.com/Microsoft/MIEngine/issues/657

**Comment by pieandcakes** [comment]
This will be tracked via the MIEngine bug.
