### ISSUE TITLE
warning: GDB: Failed to set controlling terminal: Operation not permitted

### ISSUE THREAD

**Issue by lijh8** [microsoft/vscode-cpptools#11173]
### Environment

- OS and version: fedora 38 linux
- VS Code: 1.80.0
- C/C++ extension: 1.16.3
- OS and version of remote machine (if applicable): ms-vscode-remote.remote-ssh 0.102.0
- GDB / LLDB version: GNU gdb (GDB) Fedora Linux 13.2-2.fc38

### Bug Summary and Steps to Reproduce

Bug Summary & Steps to reproduce:

when i debugging in ms-vscode.cpptools, this error flashes on the vscode built-in terminal

```
&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"
```

### Debugger Configurations

```shell
.vscode/launch.json


{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "cppdbg", // "lldb" for CodeLLDB
      "request": "launch",
      "name": "Debug",
      "program": "${fileDirname}/${fileBasenameNoExtension}", //new
      "args": [],
      "cwd": "${fileDirname}",
      "preLaunchTask": "make", //new
    }
  ]
}
```

### Debugger Logs

```shell
Launch configuration:
{
  "type": "cppdbg",
  "request": "launch",
  "name": "Debug",
  "program": "/home/ljh/Documents/hello_cpp/src/main/main",
  "args": [],
  "cwd": "/home/ljh/Documents/hello_cpp/src/main",
  "preLaunchTask": "make",
  "logging": {
    "engineLogging": true,
    "trace": true,
    "traceResponse": true
  },
  "__configurationTarget": 6,
  "configSource": "workspaceFolder",
  "debugType": "debug"
}
```

**Comment by WardenGnaw** [comment]
This is a warning message from GDB. This this preventing any debugging functionality?

**Comment by ljhm** [comment]
i don't see the warning if i start gdb on command line though

**Comment by jqknono** [comment]
I encounter this problem, too. These ways do not work for my situation:

- Restart vscode
- Reboot linux
- Downgrade gdb version from 12.1 to 9.2

finally, this is about the vscode-server. I am working on a remote linux, even though I terminate all the vscode windows, there are still many process about vscode like this:
![image](https://github.com/microsoft/vscode-cpptools/assets/12892734/aa312bd2-648e-4f41-86a5-6786d9198329)

**Just terminate them one by one, then start your project again, it's OK now.**

**Comment by Stargazer1209** [comment]
> I encounter this problem, too. These ways do not work for my situation:
> 
> * Restart vscode
> * Reboot linux
> * Downgrade gdb version from 12.1 to 9.2
> 
> finally, this is about the vscode-server. I am working on a remote linux, even though I terminate all the vscode windows, there are still many process about vscode like this: ![image](https://github.com/microsoft/vscode-cpptools/assets/12892734/aa312bd2-648e-4f41-86a5-6786d9198329)
> 
> **Just terminate them one by one, then start your project again, it's OK now.**

Thank you! Your approach solved my problem! Since terminating those server process one by one is kinda exhausting, I had to reboot my machine, but finally it worked. 
What's more, this is OBVIOUSLY a problem with vscode (server, wsl2 components, etc) itself instead of gdb. As there is still an [highly similar  open issue](https://github.com/microsoft/vscode-cpptools/issues/121) from 2016, and what's worse, different people encounter this problem every few months. 
And when I got this problem, output from vscode server(remote) reported several errors, if necessary to fix this, I would try to reproduce this error and paste the errors to the related issue.

**Comment by Simx72** [comment]
I have the same problem on my laptop
It has to do with the computer because in my pc I don't have that problem

My laptop is running ubuntu studio. (although fastfetch says kubuntu)
Kubuntu 25.10 (Questing Quokka) x86_64

It happens both if I start the extension or if I use it in terminal

**Comment by feliwir** [comment]
I have the same issue on Ubuntu 26.04
