### ISSUE TITLE
(Darwin) Exclude Xcode and /usr/include symbols from Workspace Symbols Search

### ISSUE THREAD

**Issue by loganintech** [microsoft/vscode-cpptools#1119]
Maybe I just can't find it, but when using workspace symbols search, it seems like there should be an option to exclude Xcode and /usr/include symbols. 

This is what happens when I search for workspace symbols now:

![](https://i.imgur.com/ElDi1w9.png)

It's not useful to me to have 99% of the results be constants or parts defined from other places.

**Comment by loganintech** [comment]
Any update on this?

**Comment by bobbrow** [comment]
I'm sorry, we don't have an update for you on this.  Just checking though... do you really want to exclude all of the standard libraries from your symbol search?  Or maybe just move them down in the list?

**Comment by loganintech** [comment]
I suppose it depends on the context. The optimal would probably be to put them at the end of the list, but most of the time I'm writing pure C I don't need all of apple's default C libraries. Just my two cents. I'm betting at the end of the day having an option to move them or exclude them couldn't be too difficult. I'm sad this extension is closed source.

**Comment by loganintech** [comment]
Didn't mean to close, my mistake.

**Comment by sean-mcmanus** [comment]
Have you tried removing the paths you don't want from browse.path?

**Comment by loganintech** [comment]
@sean-mcmanus I had not, but I just did yielding the same results.

**Comment by sean-mcmanus** [comment]
@HazardDev Oh, I think this is a bug. I hit this issue on November 3rd on Linux where I would remove all the paths, but it was still picking up stdio.h somehow. I'll investigate for our January release.

**Comment by sean-mcmanus** [comment]
I'm not able to repro this with the 0.14.5. You may need to clear out the "macFrameworkPath" setting.

**Comment by sean-mcmanus** [comment]
Fixed with 0.18.0.
