### ISSUE TITLE
can't find .h file while it does in includePath

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/vscode-cpptools#11197]
### Environment

- OS and version: Darwin arm64 22.5.0
- VS Code:   1.80.0 (Universal)
- C/C++ extension: 1.16.3
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Bug Summary:
![image](https://github.com/microsoft/vscode-cpptools/assets/49113249/79d770f5-8def-4e60-bf52-eb9c409046b7)

- clone https://github.com/git/git  
- open any file in `builtin` folder

### Debugger Configurations

```shell
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/local/include/node"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-arm64"
        }
    ],
    "version": 4
}
```

### Debugger Logs

```shell
'builtin.h' file not found
```

**Comment by Colengms** [comment]
Hi @HomyeeKing .  The image you posted appears to refer to a `gcc` compilation error, not an issue with the C/C++ Extension, per se:

![image](https://github.com/microsoft/vscode-cpptools/assets/49173979/80ebc7db-547b-41ac-b15e-92f9ea2dcff0)

Error squiggles emitted by the `C/C++` extension are associated with a `C/C++` identifier:

![image](https://github.com/microsoft/vscode-cpptools/assets/49173979/534c2ecf-10ce-43e9-8f4e-9a04ec287351)

Given the nature of the project folder, I suspect you're not using the C/C++ Extension's limited build features to build this project.  Can you clarify if there is a `C/C++` extension issue here?

**Comment by bobbrow** [comment]
@HomyeeKing, you can also try installing the [Makefile Tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools) extension to configure the IntelliSense for you.  The Git repository is on the list of tested repos: https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/repositories.md

cc: @andreeis

**Comment by HomyeeKing** [comment]
thanks for reply, the error is gone now without any modification, I will offer more information if I can reproduce it again.

thanks!
