### ISSUE TITLE
Inappropriate auto-completion

### ISSUE THREAD

**Issue by fcharlie** [microsoft/vscode-cpptools#112]
Why comment line has AutoCompletion ?

C++ Extensions for auto-completion feature a lot of invalid insert, including header files do not have to be included, this problem has occurred in Visual Studio 2015 update 3 is almost disastrous.

![2016-07-25 16-23-33](https://cloud.githubusercontent.com/assets/6904176/17094918/9923f804-5284-11e6-922b-0a36688d1c1a.png)

![2016-07-25 16-35-48](https://cloud.githubusercontent.com/assets/6904176/17095208/e4bd97ba-5285-11e6-95d9-56ef3932f23c.png)

**Comment by sridmad** [comment]
#13  covers enabling accurate auto completion
