### ISSUE TITLE
vscode can't create c_cpp_properties.json

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode-cpptools#1120]
* Operating System and version
   macos 10.13
* VS Code version and if you are using the Insiders build
   1.17
* C/C++ extension version
   0.13.1
* Other extensions you installed and if the issue persists after disabling them
  no
* step-by-step instructions to reproduce the issue
* A small code sample, zipped up project, or open source repo we can use to verify the bug
* Relevant settings from your settings.json, c_cpp_properties.json, and/or launch.json files

I use samba edit project on linux, vscode can't create c_cpp_properties.json.
My home dir on linux is /home/users/shiwz.
(EACCES: permission denied, open '/Volumes/shiwz/.../.vscode/c_cpp_properties.json')
"OPEN EDITORS" show nothing.

![image](https://user-images.githubusercontent.com/7554917/31384851-5968f756-ad86-11e7-901e-10626eb0b1ee.png)

**Comment by bobbrow** [comment]
Is VS Code able to create launch.json or tasks.json in the .vscode folder?

**Comment by Kurt-Shiwz** [comment]
On macOS 10.13 i use samba connect a linux server, vscode can't create c_cpp_properties.json, but launch.json and tasks.json can be created. If I create c_cpp_properties.json on external terminal, vscode can modify the file, I don't know why. @bobbrow

**Comment by Kurt-Shiwz** [comment]
if other info need please let me know @bobbrow

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
