### ISSUE TITLE
Update MSYS paths to search all "environments" (usr, ucrt64, clangarm64, etc)

### ISSUE THREAD

**Issue by AlexandraKemperMS** [microsoft/vscode-cpptools#11211]
MinGW now recommends to install using the path C:\msys64\ucrt64\bin, We need to update the path that we search for this toolchain on the native side. Once that is complete, we can also update our corresponding docs.

**Comment by michelleangela** [comment]
Adding additional context:

The extension currently looks for environments `mingw64` and `mingw32`.

[MSYS2 changed the default environment](https://www.msys2.org/news/#2022-10-29-changing-the-default-environment-from-mingw64-to-ucrt64) from to `mingw64` to `ucrt64`. With this change, the extension should now look for this new default environment.

Reference of all MSYS2 environments listed at https://www.msys2.org/docs/environments.

**Comment by Colengms** [comment]
Perhaps we should make sure we're always checking for *all* of the various locations that the different compiler packages for MSYS install to, not just the default?

**Comment by michelleangela** [comment]
I talked to Bob and it was decided to go with the minimum and search for the default path for now. We'll add other paths If there is feedback to add them as well.

**Comment by Colengms** [comment]
The work needed would just be to collect a list of paths.  I'm not suggesting handling any crazy user scenarios, just the gcc and clang packages for each of their 'environments'.  https://www.msys2.org/docs/environments/ (i.e. the "gcc" package from the "msys" env).  We have had users (recently) using these compilers.  I don't know that we'll ever have any user "requesting" that we auto-detect a default compiler in their particular compilers location.  It takes less effort for a user to specify a compiler path than to open an issue against us to detect it by default.

**Comment by michelleangela** [comment]
Upon further discussions, the other prefix paths for the other environments from the list below are also getting added to the search.

![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/f290cb06-a2b1-4639-a1d7-bc478fd64394)

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.0.

**Comment by michelleangela** [comment]
Fixed in release version https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2.

**Comment by AlexandraKemperMS** [comment]
Doc update for this fix is also out for review: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2
