### ISSUE TITLE
Debugging without the debug heap

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode-cpptools#1121]
By default running under a debugger uses the debug heap for allocations. This massively slows down a memory heavy portion of my application so I'm looking to be able to turn the debug heap on and off. Normally this is done as a command line argument to the debugger. Is it possible to do this through VS Code?

I notice the .NET Core Debugger (VsDbg.exe) is being used, but it's unclear how I can communicate with that to disable the debug heap.

**Comment by pieandcakes** [comment]
@akbyrd you can issue commands to the debugger using `-exec <command>` in the debug console. Which command do you normally use to disable this? I can verify if that exists or not.

**Comment by akbyrd** [comment]
The memory heavy portion happens at startup, so I need to be able to make changes through the launch command.

The command used depends on the debugger and the development environment. In CDB/NTSD  and WinDbg it's done with the `-hd` switch. So firing up the debugger would look like `cdb -hd <...>`.
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/cdb-command-line-options

However, I just found out the system debug heap can be disabled through an environment variable. Namely, `_NO_DEBUG_HEAP=1`. That removes the immediate need for this functionality.
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-a-user-mode-process-using-windbg

It still may be useful for these tools to provide a way to specify additional parameters to the debugger, though I'm able to find very little in the way of options for VsDbg.

**Comment by pieandcakes** [comment]
Thanks for sharing the environment variable. 

>It still may be useful for these tools to provide a way to specify additional parameters to the debugger, though I'm able to find very little in the way of options for VsDbg.

The list of supported parameters are shown when you call `vsdbg.exe /?` from a commandline. I'll add an issue to allow the ability for users to specify additional flags in `launch.json` to pass to the debugger.

**Comment by akbyrd** [comment]
`vsdbg.exe /?` lists a small number of startup switches, but lists none of the actual debugger commands. With `--interpreter=mi` it appears to emulate the GDB MI mode. However, with `--interpreter=vscode` the interface is different and I have been unable to find any documentation listing valid commands.

You mentioned being able to send commands to the debugger via `-exec <command>`. Can you point me in the direction of any available documentation?

**Comment by pieandcakes** [comment]
@akbyrd I confused what the debugger you were using with its capabilities. vsdbg.exe  (`"type": cppvsdbg`) doesn't support the `-exec <command>` command. That command exists in our implementation that supports gdb/lldb to offer users a way to issue gdb/lldb commands. 

The `--interpreter=mi` mode in vsdbg is legacy code that has not been removed yet. `--interpreter=vscode` is what we need now to run under VS Code.

**Comment by akbyrd** [comment]
Thanks for the clarification.

So there's no equivalent to `-exec <command>` when using `"type": cppvsdbg` and no documentation for supported commands with `--interpreter=vscode` if it were to be used manually?

**Comment by pieandcakes** [comment]
@akbyrd Correct, there is no equivalent to `-exec` for `"type": cppvsdbg`.

vsdbg.exe is not meant to be run manually. The licensing states that too (it is in the folder above where vsdbg.exe sits).
