### ISSUE TITLE
`files.encoding` setting is ignored on launch (must be modified to take effect)

### ISSUE THREAD

**Issue by bitssly** [microsoft/vscode-cpptools#11210]
### Environment

- OS and Version: windows 11 22621.1992
- VS Code Version: 1.80.1
- C/C++ Extension Version:  1.16.3
- If using SSH remote, specify OS of remote machine: no

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

1: When the file code is GBK, the Chinese of the IntelliSense Tooltip is displayed in garbled format;
2: When the file code is GBK and the file where the function is located is opened in advance, the Chinese display of the IntelliSense Tooltip is normal;
3: When using UTF-8 encoding format, the Tooltip of IntelliSense displays normally in Chinese.

May I ask if this situation will be updated and handled in the future?

Expected behavior:

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "C:\\Espressif\\tools\\xtensa-esp32s3-elf\\esp-2021r2-patch5-8.4.0\\xtensa-esp32s3-elf\\bin\\xtensa-esp32s3-elf-gcc.exe",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**",
                "C:/Espressif/frameworks/esp-idf-v4.4.4/components/**"

            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            },
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

### Additional context

![image](https://github.com/microsoft/vscode-cpptools/assets/37575865/a849c308-60e0-49bc-939b-87c0a3086fb4)

![image](https://github.com/microsoft/vscode-cpptools/assets/37575865/83ef8973-fa99-4291-b97d-2a93dc80e3ba)

**Comment by bitssly** [comment]
Hi @Colengms .

This is the status of my current vscode configuration information. I have used the relevant settings, but it cannot solve the problem of garbled code.

![image](https://github.com/microsoft/vscode-cpptools/assets/37575865/e6f27ef7-bd6e-4a95-865e-fa0569fffa16)

**Comment by bitssly** [comment]
Hi @Colengms .
I went to solve this problem and finally used the second method to solve the problem of garbled code;
1: I tried changing the GB2313 encoding format to GBK format, but the phenomenon did not improve;
2: Rolling back the C/C++version from V1.16.3 to 1.15.4 can display Chinese normally;
![微信截图_20230721094659](https://github.com/microsoft/vscode-cpptools/assets/37575865/e4e6ae2a-3b05-4a19-ae8d-2b86b004beeb)
![微信截图_20230721094756](https://github.com/microsoft/vscode-cpptools/assets/37575865/c0b6a33f-8233-4df9-b84b-b11d8145ee69)

**Comment by Colengms** [comment]
Hi @bitssly .  I'm unable to reproduce a regression in 1.16.3 related to this.  If I set `files.encode`, I see that this encoding is used to decode the header file contain the text to be displayed on hover (when it's not already open in the editor).

Can you provide a simple, self-contain repro, such as in the form of a GitHub repo or zip file, that we might use to investigate the problem?

Also, in the first image in your last comment, doesn't the C/C++ Extension display the Chinese equivalent of "Reload Required"?  If so, that would suggest perhaps you were not reproducing the issue with the version of the extension you thought?

**Comment by bitssly** [comment]
Hi @Colengms .
[hello_world.zip](https://github.com/microsoft/vscode-cpptools/files/12135823/hello_world.zip)
1：This project can reproduce this problem
2：about“Reload required”The reason is that at this time, I rolled back from version 1.16.3 to the installation of version 1.15.4 without reloading it
3：I have taken a new screenshot, please review it
![微信截图_20230722141613](https://github.com/microsoft/vscode-cpptools/assets/37575865/844d83a0-a142-4eb6-aac9-28dd0a9eae4f)
![微信截图_20230722141802](https://github.com/microsoft/vscode-cpptools/assets/37575865/434493aa-5698-44af-be09-e50a767fe50f)
4：‘files.encode’ Opening and closing the project cannot solve this problem

**Comment by bitssly** [comment]
Hi @Colengms .
Encoding format is GBK

**Comment by Colengms** [comment]
Hi @bitssly .  Using the zip file you provided (directly on Windows, as the container file gave me an error), and opening `hello_world_main.c`, I see garbled text when I hover over `test_one`.  If I then open `.vscode/settings.json` and add `"files.encoding": "gbk"`, then return to `hello_world_main.c`, I get the correct text when hovering over `test_one`.

However, I do see a bug here.  If I then reload the window, the text no longer displays correctly on hover.  If I modify the `files.encoding` setting, then restore it to `gbk`, the text can be displayed properly again.  The bug appears to be with our initial handling of the settings, and gets corrected whenever the setting is updated, for the duration of that session.

**Comment by bitssly** [comment]
Hi @Colengms . 
Congratulations on finding the bug,

My phenomenon here is not very consistent with yours. In order to more intuitively reflect it, I recorded a video，
In order to reduce the impact of other plugins, I only enabled the C/C++plugin, which is version 1.16.3;
Uninstall vscode Chinese language pack；

I don't know if the regional setting of my Windows is in Chinese and it will affect this
![image](https://github.com/microsoft/vscode-cpptools/assets/37575865/544a05db-5dc2-4f7b-aa8c-24295e753a11)


[Video_20230725100006.zip](https://github.com/microsoft/vscode-cpptools/files/12156425/Video_20230725100006.zip)

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.0.

**Comment by bitssly** [comment]
Hi @Colengms  , @michelleangela
Thank you very much. After verification, the issue has been completely fixed in this version. Thank you for your efforts
 pre-release  https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.0

**Comment by michelleangela** [comment]
Fixed in release version https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2.
