### ISSUE TITLE
Intellisense and search files seams not working

### ISSUE THREAD

**Issue by capocc** [microsoft/vscode-cpptools#11214]
### Environment

- OS version: Windows_NT x64 10.0.22621
- VS Code version: Code 1.80.0 
- C/C++ Extension Version: 1.16.3
- SSH remote : NO

### Bug Summary and Steps to Reproduce

Type: Performance Issue

I don't understand why I have revision marks (red) on many variable types defined in other files (but included in the project).
When I press F12 on a marked variable, it opens the definition and then removes the red revision mark. Is it an intellisense problem?

Language is for C.
I start opening VScode rigt clicking on the project folder, open with VSCode.
The project has some folders.
![image](https://github.com/microsoft/vscode-cpptools/assets/75210557/f9bdaa51-63d4-4923-8163-cd9479ebb62e)

Every folder has 2 subfolders named "src" and "inc". "Src" subfolders contain the .c files and "inc" subfolders contain .h files.
For example the "lib" folders has:

"src" subfolder with "modules.c" file
"inc" subfolder with "modules.h" file
![image](https://github.com/microsoft/vscode-cpptools/assets/75210557/eb655690-accb-4c2e-8769-6a17297cf2c7)

When I open modules.c in VSCode I find the types and other things highlighted in red.
![image](https://github.com/microsoft/vscode-cpptools/assets/75210557/202bc0d3-f5bd-4e49-9ff0-5a079cf254b8)

Now I press F12 (go to definition) and automatically VSCode open the "modules.h" files with the definitions of types.
Then I go back to the "modules.c" and the variables are not highlighted:
![image](https://github.com/microsoft/vscode-cpptools/assets/75210557/f623e04d-eb00-46d6-8254-801cfe9efb47)

I'm using C/C++ extension, in the includePath there is: _"${workspaceFolder}/",_**, so every files on the project should be included.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "HA WIFI for bootloader",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
            ],
            "defines": [
                "rand=_rand",
                "HOST_ADAPTER",
                "WLCON_WIFI",
                "WATCHDOG",
                "CONSOLE_UART=1",
                "CONSOLE_SPEED=115200",
                "PROFILE_MODULES ",
                "PHY_AT86RF233"
            ],
            "cStandard": "c99",
            "intelliSenseMode": "windows-gcc-arm",
            "compilerPath": "",
            "mergeConfigurations": false,
            "forcedInclude": [
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include\\samr21g18a.h"
            ],
            "browse": {
                "path": [ //senza questo se premo F12 non mi va alla definizione ma alla dichiarazione
                    "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        },
        {
            "name": "HA debug",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
            ],
            "defines": [
                "rand=_rand",
                "DEBUG",
                "HOST_ADAPTER",
                "WLCON_WIFI",
                "CONSOLE_UART=1",
                "CONSOLE_SPEED=115200",
                "PROFILE_MODULES",
                "PHY_AT86RF233"
            ],
            "cStandard": "c99",
            "intelliSenseMode": "${default}",
            "compilerPath": "",
            "mergeConfigurations": false,
            "forcedInclude": [
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include\\samr21g18a.h"
            ],
            "browse": {
                "path": [],
                "limitSymbolsToIncludedHeaders": false
            }
        },
        {
            "name": "HA release = HA WIFI for bootloader release",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
            ],
            "defines": [
                "rand=_rand",
                "WATCHDOG",
                "HOST_ADAPTER",
                "WLCON_WIFI",
                "CONSOLE_UART=1",
                "CONSOLE_SPEED=115200",
                "PROFILE_MODULES",
                "PHY_AT86RF233"
            ],
            "cStandard": "c99",
            "intelliSenseMode": "windows-gcc-arm",
            "compilerPath": "C:\\ST\\STM32CubeIDE_1.12.0\\STM32CubeIDE\\plugins\\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.200.202301161003\\tools\\bin\\arm-none-eabi-gcc.exe",
            "mergeConfigurations": false,
            "forcedInclude": [
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include\\samr21g18a.h"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        },
        {
            "name": "node debug",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
            ],
            "defines": [
                "rand=_rand",
                "DEBUG",
                "CONSOLE_UART=1",
                "CONSOLE_SPEED=115200",
                "PROFILE_MODULES",
                "PHY_AT86RF233"
            ],
            "cStandard": "c99",
            "intelliSenseMode": "windows-gcc-arm",
            "compilerPath": "C:\\ST\\STM32CubeIDE_1.12.0\\STM32CubeIDE\\plugins\\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.200.202301161003\\tools\\bin\\arm-none-eabi-gcc.exe",
            "mergeConfigurations": false,
            "forcedInclude": [
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include\\samr21g18a.h"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        },
        {
            "name": "node release = node for bootlader release",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
            ],
            "defines": [
                "rand=_rand",
                "WATCHDOG",
                "CONSOLE_UART=1",
                "CONSOLE_SPEED=115200",
                "PROFILE_MODULES",
                "PHY_AT86RF233"
            ],
            "cStandard": "c99",
            "intelliSenseMode": "windows-gcc-arm",
            "compilerPath": "C:\\Program Files\\Microchip\\xc8\\v2.36\\avr\\bin\\avr-cpp.exe",
            "mergeConfigurations": false,
            "forcedInclude": [
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include\\samr21g18a.h"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        },
        {
            "name": "node 6788 debug",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
            ],
            "defines": [
                "rand=_rand",
                "DEBUG",
                "CONSOLE_UART=2",
                "CONSOLE_SPEED=115200",
                "PROFILE_MODULES",
                "PHY_AT86RF233",
                "SK6788"
            ],
            "cStandard": "c99",
            "intelliSenseMode": "windows-gcc-arm",
            "compilerPath": "C:\\ST\\STM32CubeIDE_1.12.0\\STM32CubeIDE\\plugins\\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.200.202301161003\\tools\\bin\\arm-none-eabi-gcc.exe",
            "mergeConfigurations": false,
            "forcedInclude": [
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include\\samr21g18a.h"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        },
        {
            "name": "node 6788 release = node 6788 release for bootloader",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
            ],
            "defines": [
                "rand=_rand",
                "WATCHDOG",
                "CONSOLE_UART=2",
                "CONSOLE_SPEED=115200",
                "PROFILE_MODULES",
                "PHY_AT86RF233",
                "SK6788"
            ],
            "cStandard": "c99",
            "intelliSenseMode": "windows-gcc-arm",
            "compilerPath": "C:\\ST\\STM32CubeIDE_1.12.0\\STM32CubeIDE\\plugins\\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.200.202301161003\\tools\\bin\\arm-none-eabi-gcc.exe",
            "mergeConfigurations": false,
            "forcedInclude": [
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include\\samr21g18a.h"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}/**",
                "C:\\Keil_v5\\ARM\\ARMCC\\include\\",
                "C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include",
                "C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
```

### Other Extensions

Pylance
Python
Todo Tree
Italian Language Pack for Visual Studio Code
File Templates

### Additional context

I'm using VsCode only for texting, not for debugging and running the code.

**Comment by michelleangela** [comment]
@capocc 
Could you enable logging for the language server (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) and share the logs here? It will show which include paths are getting sent to the IntelliSense engine.

**Comment by capocc** [comment]
This is the log:

loggingLevel: Debug
cpptools version (TypeScript): 1.16.3
cpptools version (native): 1.16.3.0
Autocomplete is enabled.
Error squiggles are enabled.
Hover is enabled.
IntelliSense Engine = default.
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/queryCompilerDefaults (id: 1)
LSP: cpptools/didChangeCppProperties (id: 2)
LSP: cpptools/queryCompilerDefaults (id: 3)
LSP: Message ignored due to no registered handler: $/setTrace
Code browsing service initialized
Skipping query of compiler due to explicitly empty compilerPath
Skipping query of compiler due to explicitly empty compilerPath
  Folder: C:/USERS/ANDREA.CAPOCCIA/DESKTOP/HIGHBAY/TRUNK/HIGHBAY/ will be indexed
  Folder: C:/KEIL_V5/ARM/ARMCC/INCLUDE/ will be indexed
  Folder: C:/KEIL_V5/ARM/PACK/ARM/CMSIS/4.5.0/CMSIS/INCLUDE/ will be indexed
  Folder: C:/KEIL_V5/ARM/PACK/KEIL/SAMR21_DFP/1.1.0/DEVICE/SAMR21/INCLUDE/ will be indexed
Discovering files...
  Processing folder (recursive): C:/USERS/ANDREA.CAPOCCIA/DESKTOP/HIGHBAY/TRUNK/HIGHBAY/
  Processing folder (recursive): C:/KEIL_V5/ARM/ARMCC/INCLUDE/
  Processing folder (recursive): C:/KEIL_V5/ARM/PACK/ARM/CMSIS/4.5.0/CMSIS/INCLUDE/
  Processing folder (recursive): C:/KEIL_V5/ARM/PACK/KEIL/SAMR21_DFP/1.1.0/DEVICE/SAMR21/INCLUDE/
  Discovering files: 602 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/didChangeCppProperties (id: 4)
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: textDocument/didOpen: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/getCodeActions: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c (id: 5)
LSP: cpptools/getInlayHints: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c (id: 6)
LSP: cpptools/getDocumentSymbols: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c (id: 7)
LSP: cpptools/getFoldingRanges: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c (id: 8)
LSP: cpptools/activeDocumentChange: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c
LSP: cpptools/getSemanticTokens: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c (id: 9)
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
sending compilation args for C:\Users\andrea.capoccia\Desktop\HighBay\trunk\HighBay\lib\src\modules.c
  include: C:\KEIL_V5\ARM\ARMCC\INCLUDE
  include: C:\KEIL_V5\ARM\PACK\ARM\CMSIS\4.5.0\CMSIS\INCLUDE
  include: C:\KEIL_V5\ARM\PACK\KEIL\SAMR21_DFP\1.1.0\DEVICE\SAMR21\INCLUDE
  include: C:\USERS\ANDREA.CAPOCCIA\DESKTOP\HIGHBAY\TRUNK\HIGHBAY\HAL\INC
  include: C:\USERS\ANDREA.CAPOCCIA\DESKTOP\HIGHBAY\TRUNK\HIGHBAY\TKLIB\INC
  include: C:\USERS\ANDREA.CAPOCCIA\DESKTOP\HIGHBAY\TRUNK\HIGHBAY\LIB\INC
  include: C:\USERS\ANDREA.CAPOCCIA\DESKTOP\HIGHBAY\TRUNK\HIGHBAY\KLIB\INC
  include: C:\USERS\ANDREA.CAPOCCIA\DESKTOP\HIGHBAY\TRUNK\HIGHBAY\PLATFORM
  include: C:\USERS\ANDREA.CAPOCCIA\DESKTOP\HIGHBAY\TRUNK\HIGHBAY\APP\INC
  define: rand=_rand
  define: HOST_ADAPTER
  define: WLCON_WIFI
  define: WATCHDOG
  define: CONSOLE_UART=1
  define: CONSOLE_SPEED=115200
  define: PROFILE_MODULES 
  define: PHY_AT86RF233
  preinclude: C:/Keil_v5/ARM/Pack/Keil/SAMR21_DFP/1.1.0/Device/SAMR21/Include/samr21g18a.h
  other: --gcc
  other: --gnu_version=130100
  stdver: c99
  intelliSenseMode: windows-gcc-arm
Checking for syntax errors: C:\Users\andrea.capoccia\Desktop\HighBay\trunk\HighBay\lib\src\modules.c
Queueing IntelliSense update for files in translation unit of: C:\Users\andrea.capoccia\Desktop\HighBay\trunk\HighBay\lib\src\modules.c
LSP: cpptools/getCodeActions: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c (id: 10)
LSP: cpptools/getDocumentSymbols: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c (id: 11)
Error squiggle count: 76
PCH warning: header stop not at file scope.  An IntelliSense PCH file was not generated.
Update IntelliSense time (sec): 0.958
LSP: cpptools/getCodeActions: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c (id: 12)
LSP: cpptools/getFoldingRanges: file:///c%3A/Users/andrea.capoccia/Desktop/HighBay/trunk/HighBay/lib/src/modules.c (id: 13)

**Comment by michelleangela** [comment]
@capocc 
Thank you for the logs. Sorry I forgot to ask about what error message are the squiggles showing? Or what errors are listed under the "PROBLEMS" window for the file modules.c?

And do the other include paths need to be searched recursively? If so, could you try adding `**` after those paths:
```
"C:\\Keil_v5\\ARM\\ARMCC\\include\\**",
"C:\\Keil_v5\\ARM\\Pack\\ARM\\CMSIS\\4.5.0\\CMSIS\\Include\\**",
"C:\\Keil_v5\\ARM\\Pack\\Keil\\SAMR21_DFP\\1.1.0\\Device\\SAMR21\\Include\\**"
```

**Comment by capocc** [comment]
Thanky you for your help.

Error messages are all "identifier not defined"
![image](https://github.com/microsoft/vscode-cpptools/assets/75210557/b43832f8-7095-427d-9373-e20f07479916)

The strange thing is that pressing F12 VsCode finds the definition and the error disappears.

The include paths contain only header files, so I don't think they need to be searched recursively.

**Comment by capocc** [comment]
I still have the problem. Could it be because the project is too big?

**Comment by michelleangela** [comment]
The size of the project shouldn't be the cause of this issue. For some reason, the IntelliSense engine is not fully resolving the symbols.

Could you try the following:

1.) Try setting `C_Cpp.intelliSenseCacheSize` to 0 to disable PCH.
2.) Try running the command "C/C++: Restart IntelliSense for Active File" and see if that resolves the error squiggles.
3.) If the error squiggles are not resolving by doing 1 or 2, could you get log diagnostic (run command "C/C++: Log Diagnostics") before and after the error squiggles are resolved.

**Comment by capocc** [comment]
Thank you @michelleangela! By setting `C_Cpp.intelliSenseCacheSize` to 0, the issue seems to be resolved.
I will try to reset it to the default value to see if the issue reoccurs.
Thank you!
