### ISSUE TITLE
Support RISC-V `AT` keyword without requiring a cpp.hint file

### ISSUE THREAD

**Issue by Jwchen120** [microsoft/vscode-cpptools#11222]
### Feature Request
```
AT(.text.func.btring.msg)
void sfunc_bt_ring_message(u16 msg)
{
    if(msg){
        sfunc_bt_ring_message_do(msg);
    }
}
```
or
``` 
AT(x)
void sfunc_bt_ring_message(u16 msg)
{
    if(msg){
        sfunc_bt_ring_message_do(msg);
    }
}
```
Like this function above，C/C++ Extension 0.28.3 can recognize this function name。The outline can also show function names。  C/C++ Extension 1.16.3 can not recognize this function name。The outline also fails to show function names
```[tasklist]
### Tasks
```

**Comment by Colengms** [comment]
Hi @Jwchen120 . I'm not familiar with this syntax.  `AT` would appear to be a macro defined somewhere else in the codebase.  Is that correct?  If so, it's possible this may be a known limitation of our syntactic parser, which can be addressed by specifying the macro in a `cpp.hint` file.  More information on this issue and on `cpp.hint` files can be found here:  https://learn.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170

Or, if this syntax is something other than a macro, such as a feature of a particular compiler, could you provide additional information on what it is?

**Comment by Jwchen120** [comment]
HI&nbsp;




老陈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-cpptools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月20日(星期四) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-cpptools] C/C++ Extension 1.16.3 If the function header has more address information like AT(.text.loact), it cannot recognize the function (Issue #11222)





 
Hi @Jwchen120 . I'm not familiar with this syntax.  AT would appear to be a macro defined somewhere else in the codebase.  Is that correct?  If so, it's possible this may be a known limitation of our syntactic parser, which can be addressed by specifying the macro in a cpp.hint file.  More information on this issue and on cpp.hint files can be found here:  https://learn.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170
 
Or, if this syntax is something other than a macro, such as a feature of a particular compiler, could you provide additional information on what it is?

**Comment by Jwchen120** [comment]
HI 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;In Risc-v embedded development, some toolchains need to specify the "AT(segment information)" location of the code in flash.The function is preceded by AT(segment information) to specify the segment position of the current function in flash.&nbsp;&nbsp;I added some macro definitions to solve the error problem.


For example：Can solve the syntax error，However, the cpptools version can recognize function names in 0.28.3, and later versions cannot recognize function names.It can't be shown in the outline.


But the new version features are very good, I want to use the new version, so I hope to solve this problem.


For example：v0.28.3:&nbsp; &nbsp;

For example：v1.16.3:



&nbsp; &nbsp; &nbsp; &nbsp;在Risc-v嵌入式开发中，有些工具链需要指定代码在flash中的存储段位置“AT(段信息)”。就是在函数前面加上AT(段信息)指定当前函数在flash中的段位置。自己加了些宏定义解决报错问题。但是 cpptools 版本在0.28.3可以识别函数名，在之后的版本都无法识别函数名。也无法在大纲显示。
但是新版本功能特性非常不错，想使用新版本，所以希望能解决这个问题。


老陈
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "microsoft/vscode-cpptools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月20日(星期四) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-cpptools] C/C++ Extension 1.16.3 If the function header has more address information like AT(.text.loact), it cannot recognize the function (Issue #11222)





 
Hi @Jwchen120 . I'm not familiar with this syntax.  AT would appear to be a macro defined somewhere else in the codebase.  Is that correct?  If so, it's possible this may be a known limitation of our syntactic parser, which can be addressed by specifying the macro in a cpp.hint file.  More information on this issue and on cpp.hint files can be found here:  https://learn.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170
 
Or, if this syntax is something other than a macro, such as a feature of a particular compiler, could you provide additional information on what it is?

**Comment by Colengms** [comment]
Hi @Jwchen120 .  We can keep this issue open as a 'feature request' to support the syntax of the `AT` keyword used by RISC-V compilers.  However, I believe you should be able to work around the issues you're describing using a `cpp.hint` file.  Use of a `cpp.hint` file is documented here: https://learn.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170  Even though `AT` is not actually a macro, you should still be able to specify it in a `cpp.hint` as if it were a macro, to enable the extension to avoid it when parsing.
