### ISSUE TITLE
Don't create .bat files on startup in .vscode

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-cpptools#1122]
When I open a C/C++ project then I can see a lot of .bat files appearing and disappearing in the .vscode folder which not only makes VS Code's git extension react on that but other extensions as well which had registered a workspace file change listener.
~The screenshot below is the result of vscode-cpptools sometimes not even cleaning up the generated .bat files.~ (EDIT: In fact, it's the [CMake extension](https://github.com/vector-of-bool/vscode-cmake-tools)'s fault, see comments below)
Is it really necessary to persist those .bat files to disk to fetch the relevant values? If yes, it would be better to store them in the system temp folder instead of .vscode to prevent any mess.

![image](https://user-images.githubusercontent.com/530988/31401472-dad9e25a-adea-11e7-9733-89b2a895b63c.png)
The file content is something like:
```bat
@echo off
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat" -no_logo -arch=arm || exit
echo CL := %CL%
echo _CL_ := %_CL_%
echo INCLUDE := %INCLUDE%
echo LIBPATH := %LIBPATH%
echo LINK := %LINK%
echo _LINK_ := %_LINK_%
echo LIB := %LIB%
echo PATH := %PATH%
echo TMP := %TMP%
echo FRAMEWORKDIR := %FRAMEWORKDIR%
echo FRAMEWORKDIR64 := %FRAMEWORKDIR64%
echo FRAMEWORKVERSION := %FRAMEWORKVERSION%
echo FRAMEWORKVERSION64 := %FRAMEWORKVERSION64%
echo UCRTCONTEXTROOT := %UCRTCONTEXTROOT%
...
```

**Comment by bobbrow** [comment]
What other extensions do you have installed?  Our extension does not write any `.bat` files to the .vscode folder.  Is it the CMake extension perhaps?

**Comment by letmaik** [comment]
Hmmm that could actually be the case. Yes, I have the CMake extension installed as well. I will open an issue there and link to this one for reference.
They really should add a header to the .bat files with something like.... "generated by vector-of-bool.cmake-tools".

**Comment by letmaik** [comment]
Here it is: https://github.com/vector-of-bool/vscode-cmake-tools/issues/240
And I also found the relevant piece of code that does it: https://github.com/vector-of-bool/vscode-cmake-tools/blob/6a73f47d97dc7fd631c0f97eafeeadc84303914e/src/environment.ts#L69
Sorry for the noise! Closing.
