### ISSUE TITLE
Unable to open 'libc-start.c': File not found...

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1123]
Hello,

I use VSCode (version seems to be 1.17.1) on 64-bit Ubuntu 17.04. I have installed Clang/LLVM tools and try to debug my C-code. Everything works fine when stepping over until I reach the return statement. When return statement is highlighted and I click "Step over" once more, I get error message saying "Unable to open 'libc-start.c': File not found (file:///build/glibc-mXZSwJ/glibc-2.24/csu/../csu/libc-start.c)." Why would that happen?

Same happens when using gdb as debugger and gcc as compiler, but a bit later step, i.e. when the last closing curly bracket is highlighted and pressing "Step over". 

Sample code:

```c
#include <stdio.h>

int main(void)
{
	int a = 21;
	int b = 4;
	int c = a % b;

	printf("%d mod %d = %d\n", a, b, c);
	return 0;
}
```

Regards,
Miika

**Comment by sean-mcmanus** [comment]
This is "by design". After you return from main, the code belongs to the library code, in this case, libc-start.c, which is not available on your machine, unless you happened to have built the libc runtime you're using from the source. In generally, you shouldn't need to look at code that is not yours, so you can just ignore the pop about a missing file. In your example, you can put a breakpoint on the return 0, but you shouldn't need to step beyond that.

**Comment by ghost** [comment]
Ok, I understand. Though I would suggest to somehow end the debugging process or something like that rather than displaying an error message. It's confusing etc. to see error message there.

**Comment by ghost** [comment]
Yeah I agree it's a confusing message. I mean, it caused me to look up what was going on, so that's not really all that elegant. Great stuff, though.

**Comment by xerebz** [comment]
This is a terrible user experience. There's really no way to suppress this error or than breakpointing before main's exit?

**Comment by sean-mcmanus** [comment]
@xerebz You should only get the message when you tell the debugger to step into code that you don't have access to (i.e. stepping past a main's return). Are you seeing this when just running your program with no breakpoints set?

**Comment by ghost** [comment]
[redacted]

**Comment by sean-mcmanus** [comment]
@dmarinescu I mean you shouldn't need to look at code whose source code is not available, such as the c runtime code that executes after returning from main (e.g. libc-start.c). If you're building using open source libraries that are not "your own" then you should be able to view and debug the source code using our tool.

**Comment by bobbrow** [comment]
@dmarinescu, let's please keep comments respectful.  You may disagree with something someone posts online, but it is better to ask for clarification than to rush in with insults.  We will moderate comments that we deem inappropriate as per our [Code of Conduct](https://opensource.microsoft.com/codeofconduct/).

**Comment by dmarinescu** [comment]
> This is "by design". After you return from main, the code belongs to the library code, in this case, libc-start.c, which is not available on your machine, unless you happened to have built the libc runtime you're using from the source. In generally, you shouldn't need to look at code that is not yours, so you can just ignore the pop about a missing file. In your example, you can put a breakpoint on the return 0, but you shouldn't need to step beyond that.

you do not need to look at code which is not yours?!? nice... in-house, flipping invoices sunday prgrammers should stick with quick basic (or python) GOOD ONE!!!

**Comment by xerebz** [comment]
use vim and gdb, problem solved

**Comment by benripka** [comment]
I've noticed that for me this occurs often when I try to debug with gdb's follow-fork-mode enabled. This makes the debugger try to jump into code it may not have access to. Just a note.

**Comment by karln-create** [comment]
I agree that the error message is arbitrary, especially for beginners. Would it be possible to add a message along the line "you are stepping beyond the scope of the project." or something?

Thank you.

**Comment by CastleBomber** [comment]
sup dudes, we in 2021 && still dealing with such obscure errors thrown? Hehe well glad it has a purpose

**Comment by Conghuajidaner** [comment]
This is really confusing
