### ISSUE TITLE
Problem reading "#include" part in c files

### ISSUE THREAD

**Issue by gabrielryanft** [microsoft/vscode-cpptools#11235]
Type: <b>Bug</b>

I installed the c/c++ extension but when I try to run the code it doesn't work. The problem is always in the "#include" lines.

`**_#include <stdio.h>_**

int main(void)
{
    printf("Hello, World\n");
}`

Extension version: 1.16.3
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:
![Captura de tela 2023-07-24 081232](https://github.com/microsoft/vscode-cpptools/assets/135415258/c655c1ab-3f2b-478e-81e3-a986eb6fe23a)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.90GB free)|
|Process Argv|--crash-reporter-id 4c92afaf-e344-4df8-93d6-3b0e4c1addf1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
89544117:30613380
vscrp:30673768
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnoceb:30776495
e537b577:30795824
dsvsc013:30795093

```

</details>

**Comment by gabrielryanft** [comment]
Hello, Bob!

i did this: 
I clicked on the yellow light that was appearing in the "#include" line. 3 options appeared, one of them being: 
" learn how to install libraries for this header with vcpkg".
 i clicked on that got into that site : "https://vcpkg.io/en/getting-started" did the things i needed to do at the prompt  
(minus this:
Install libraries for your project:
   vcpkg install [packages to install]

I don't know what I need to write in the [packages to install] log. and i I also don't know what a compiler is (you asked: "Have you installed a compiler yet?")
)
![Captura de tela 2023-07-24 143303](https://github.com/microsoft/vscode-cpptools/assets/135415258/2474fc38-35e7-428f-9653-ac018f75a94a)

**Comment by bobbrow** [comment]
Hi @gabrielryanft,

vcpkg isn't what you want here.  The extension apparently hasn't made the distinction between the standard C++ headers and other library headers that you may want to use.  We should make a fix to remove that menu entry for system headers so people don't get confused.

> i I also don't know what a compiler is (you asked: "Have you installed a compiler yet?")

A compiler is a tool that turns your code into a program and is required if you want to make C++ programs.  There are a couple of options out there for you, but here are some getting started docs that can help you:

* [Getting started with the Microsoft Visual C++ compiler](https://code.visualstudio.com/docs/cpp/config-msvc)
* [Getting started with the gcc compiler](https://code.visualstudio.com/docs/cpp/config-mingw)

**Comment by sean-mcmanus** [comment]
Oops, my last comment was wrong -- the bug exists for C++ headers as well.
