### ISSUE TITLE
C/C++ Themes v2.0.0 causing monitor-wide HDR-like color changes when VSCode takes up > 50% of the screen

### ISSUE THREAD

**Issue by btgoodwin** [microsoft/vscode-cpptools#11236]
### Environment

- OS and Version: Windows 11 21H2
- VS Code Version: 1.80.3
- C/C++ Extension Version: 2.2.0
- If using SSH remote, specify OS of remote machine: None.

### Bug Summary and Steps to Reproduce

Bug Summary:

On an SD display, VSCode themes in this theme pack seem to perform an "auto HDR" behavior that both should not be occuring on an SD monitor nor should it be altering the entire Windows display environment.  It currently makes using the application at or near full-screen unusable while also making the taskbar and any visible portion of the desktop unusable by causing excessive eyestrain.

Steps to reproduce:
1. Disable HDR on your monitor and windows settings
2. Make your VSCode window size be fewer than roughly half the screen, you may have to play with this.
3. Pick one of the theme pack's included ones, one that shows this easily is `Dark (Visual Studio Code - C++)`, but all of them seem to display the behavior.
4. Maximize VSCode (or resize it so that it covers most of the screen).
5. Observe that your Window task bar's colors have saturated as if the brightness has been increased significantly, contrast as well.
6. Resize the window to very small and watch carefully.  The whole display will dim back to normal.
7. Switch to some other theme, I used Monokai, and repeat the process (Step 3+).  You should observe that the Windows task bar doesn't change brightness, contrast, etc. based on the size of your VSCode window's relationship to the whole monitor size.

Expected behavior:

Two things:
1. I would not expect resizing the VSCode window to alter its own brightness or contrast as if it's performing some kind of "auto HDR" feature when the display is not HDR.
2. I would not expect VSCode's manipulation of its own color pallet to be altering the whole Windows desktop experience.

See related ticket, a couple of us thought this was VSCode itself, but I've found it's tied to these themes:

https://github.com/microsoft/vscode/issues/183619#issuecomment-1647952469

### Configuration and Logs

```shell
(Working in WSL2 instance right now, hence the linux paths)

{
    "configurations": [
        {
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceFolder}/builddir/compile_commands.json"
        }
    ],
    "version": 4
}
```
```


### Other Extensions

_No response_

### Additional context

_No response_

**Comment by bobbrow** [comment]
Let's have this discussion on VS Code's issues page.  The themes API and how colors are interpreted should be owned by them.  There was no reason for us to believe that the colors we specified would be anything other than sRGB colors.  When I did HDR stuff in the past it required setting color channels outside of the [0-1] (or 0-255) range, which should not be possible when using hex color codes.  If it is determined that there is something we need to change as a result of that discussion, we can reopen this issue and release an update to our theme extension.
