### ISSUE TITLE
#elif syntax highlighting is not consistent

### ISSUE THREAD

**Issue by aengus** [microsoft/vscode-cpptools#11248]
Type: <b>Bug</b>

#elif cases are colored differently depending on which of the conditions in the #if-#elif-#else tree is active.

Steps to reproduce:

Paste this snippet into a C/C++ source file:
```
#define A   (0)
#define B   (0)
#define C   (0)

#if A
int x;
#elif B
int y;
#elif C
int z;
#else
int w;
#endif
```

![image](https://github.com/microsoft/vscode-cpptools/assets/175610/382204ea-6c1d-4ac2-b85c-3946cb404db0)

Note that the symbols A, B and C are all colored blue (using the default dark theme). The #else case is the active case.

Now modify the code snippet so that A==1

```
#define A   (1)
#define B   (0)
#define C   (0)

#if A
int x;
#elif B
int y;
#elif C
int z;
#else
int w;
#endif
```

The color of the B and C symbols is now white. A is now the active case.

![image](https://github.com/microsoft/vscode-cpptools/assets/175610/ab27c2ce-243f-437f-afff-6fd83a6cda80)

In both screenshots, neither B or C is the active condition, but they are colored differently depending on which condition is active.

I would expect the color of the symbols B and C to be the same in both of the code snippets above.

Extension version: 2.0.0
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (3.23GB free)|
|Process Argv|--folder-uri file://wsl%24/Ubuntu/home/awesthead/work/frl-ha --crash-reporter-id a4a0932c-b13e-4118-a962-76d27866a4db|
|Screen Reader|no|
|VM|0%|
</details><details>

</details>

**Comment by sean-mcmanus** [comment]
This appears to be "by design". When the 1st `#if` evaluates to false, then our IntelliSense processor skips running until the `#endif` so the B and C doing get evaluated as macros for semantic highlighting, so the color you get is from lexical highlighting.

**Comment by aengus** [comment]
I think this behaviour makes intellisense unreliable when it comes to macros. For example, if the second code snippet is modified to:

```
#define A   (1)
#define B   (0)
#define C   (0)

#if A
int x;
#elif B
int y;
#elif C
int z;
#else
int w;
#endif

#if C
int a;
#endif
```

Intellisense is going to give me different information depending on which C I hover over, even though they are the same macro with the same value, with both preprocessor conditionals evaluating to false. This isn't intuitive to me, especially because it is valid to undefine or change the values of macros throughout source files. It will be hard to know if I am being shown different information because it has genuinely changed, or because of a design quirk.

**Comment by bobbrow** [comment]
Would it help if those `#elif` lines that are not processed by our internal compiler were dimmed like the other source lines?

**Comment by sean-mcmanus** [comment]
@bobbrow I would say yes. It makes it more obvious that the macro itself is inactive.

**Comment by billgan1024** [comment]
I also have a macro-related issue; not sure if this is intended.
When using macros defined in certain files like `windows.h`, the tokens/scopes are incorrect for macros inside the macro call.

For example:
![image](https://github.com/microsoft/vscode-cpptools/assets/17630457/7ad63d38-3b07-4747-8e71-7102ee0715e7)
`CW_USEDEFAULT` is a windows macro but for some reason it is white instead of blue.

**Comment by sean-mcmanus** [comment]
@billgan1024 Your issue is different. I've moved it to https://github.com/microsoft/vscode-cpptools/issues/11416 .
