### ISSUE TITLE
Call Hierarchy child items aren't formatted correctly (default arguments are shown)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11247]
See the screenshot. The root definition is formatted correctly but the children are not, which makes the arguments harder to read.

![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/8ac6f7ad-e066-48cd-aa6c-96f9bc6ede02)

Repro code is like

```cpp
#include <unordered_map>

int foo() { return 0; }

bool func(std::unordered_map<int, int> * d = nullptr)
{
    return foo() == 1;
}
```

The bug should be easy to fix by doing the formatting that is done for the root definition on the child items.

**Comment by michelleangela** [comment]
**Before fix:**
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/beeee721-1830-4efa-aef2-6b0a2bd35bd7)


**After fix:**
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/c32169c7-153b-4fbd-b45f-149741ef80fa)

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.1.
