### ISSUE TITLE
cpptools complete has some problems

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode-cpptools#1125]
* Operating System and version
       macos 10.13
    * VS Code version and if you are using the Insiders build
       1.17.1
    * C/C++ extension version
       0.13.1
    * Other extensions you installed and if the issue persists after disabling them
    * step-by-step instructions to reproduce the issue
    * A small code sample, zipped up project, or open source repo we can use to verify the bug
    * Relevant settings from your settings.json, c_cpp_properties.json, and/or launch.json files

1. Can't complete 
![image](https://user-images.githubusercontent.com/7554917/31441547-1d13e288-ae59-11e7-8685-526b1993a18a.png)
    // c++
    "C_Cpp.addWorkspaceRootToIncludePath": true,
    "C_Cpp.autocomplete": "Default",
    "C_Cpp.errorSquiggles": "Enabled",
    "C_Cpp.intelliSenseEngine": "Default",
    // "C_Cpp.intelliSenseEngine": "Tag Parser",
    "C_Cpp.intelliSenseEngineFallback": "Enabled",

2.It  can't complete the  class members at first
![image](https://user-images.githubusercontent.com/7554917/31445094-018b6374-ae63-11e7-816c-2de5eb698172.png)

![image](https://user-images.githubusercontent.com/7554917/31445367-82de2024-ae63-11e7-991f-bccac5c8b9fb.png)

**Comment by bobbrow** [comment]
1. This is issue #13 
2. `HttpContext` appears to inherit members from another class.  Are those methods not in one of the base classes?

**Comment by Kurt-Shiwz** [comment]
Yes, but "_cntl" is not completed first also @bobbrow

**Comment by bobbrow** [comment]
Fields starting with `_` are sorted to the bottom of the list.  Is it not there?

**Comment by Kurt-Shiwz** [comment]
![image](https://user-images.githubusercontent.com/7554917/31480002-d36d9d3a-aee0-11e7-9593-d68dc9b6f9f4.png)

In my opinion cpptools shoud always completed the class members whatever i input something or not.

**Comment by sean-mcmanus** [comment]
@Kurt-Shiwz Your second screenshot seems to show that you're falling back to the tag parser's autocomplete results.

**Comment by Kurt-Shiwz** [comment]
There is two test cpp:
![image](https://user-images.githubusercontent.com/7554917/31525564-c6ebc1d0-af86-11e7-9fbb-4ae5c288c68c.png)
![image](https://user-images.githubusercontent.com/7554917/31525574-d3267526-af86-11e7-95a0-6a26d211c17b.png)


when c_cpp_properties.json is that:
![image](https://user-images.githubusercontent.com/7554917/31525607-0aef68dc-af87-11e7-9570-9da43e50ce6d.png)
all include file is ok.  the class ttt declare in current file and class yyy declare in testb.cpp can autocomplete.
![image](https://user-images.githubusercontent.com/7554917/31525613-23a3204e-af87-11e7-8b52-1cb9495dac69.png)
![image](https://user-images.githubusercontent.com/7554917/31525682-b534f5a0-af87-11e7-8032-40d7e334b457.png)


but when c_cpp_properties.json is that:
![image](https://user-images.githubusercontent.com/7554917/31525546-a08acab8-af86-11e7-934f-82308e9cd898.png)

cpptools show some include error in "iostream" and class ttt and yyy don't complete.
<img width="531" alt="qq20171013-091221 2x" src="https://user-images.githubusercontent.com/7554917/31525989-ba1af130-af89-11e7-9350-7c64bc6e5e52.png">
<img width="556" alt="qq20171013-091158 2x" src="https://user-images.githubusercontent.com/7554917/31525990-ba4af9f2-af89-11e7-83f9-b43b15d5a334.png">

I think "iostream" has include error shoudon't effect current file and others, testb.h is sample and right, but it can't autocomplete.
Sometimes cpptools crash without any message, I can just close the project and reopen it and wait, the experience is not good.
@bobbrow 
@sean-mcmanus

**Comment by 2bdkid** [comment]
I'm not sure if I have the same issue but my vscode can't resolve anything from namespace std. The tool tip says "namespace "std" has no member "whatever"".

`{
    "name": "Win32",
    "includePath": ["C:\\MSYS2\\mingw64\\include\\c++\\7.2.0",
                    "C:\\MSYS2\\mingw64\\include\\c++\\7.2.0\\x86_64-w64-mingw32",
                    "C:\\MSYS2\\mingw64\\x86_64-w64-mingw32\\include"],
    "defines": [],
    "intelliSenseMode": "msvc-x64",
    "browse": {
        "path": [
            "${workspaceRoot}"
        ],
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": ""
    }
}`

**Comment by 2bdkid** [comment]
I don't know if my problems are related but the problem checker gives me some weird errors.
![cpp](https://user-images.githubusercontent.com/6799602/31592631-ae4229d0-b1f7-11e7-8ebf-41944f009bde.png)
This is my config.
`{
    "configurations": [
        {
            "name": "Win32",
            "includePath": ["C:\\MSYS2\\mingw64\\include\\c++\\7.2.0",
                            "C:\\MSYS2\\mingw64\\include\\c++\\7.2.0\\x86_64-w64-mingw32",
                            "C:\\MSYS2\\mingw64\\x86_64-w64-mingw32\\include"],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": ["C:\\MSYS2\\mingw64\\include\\c++\\7.2.0",
                         "C:\\MSYS2\\mingw64\\include\\c++\\7.2.0\\x86_64-w64-mingw32",
                         "C:\\MSYS2\\mingw64\\x86_64-w64-mingw32\\include"],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}`

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
