### ISSUE TITLE
File path info in the Call Hierarchy should show relative paths for files in the current workspace

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11254]
Call Hierarchy file info on the right shows the full path instead of the workspace relative path. This makes it harder to see the important part of the path and it could show potentially unwanted path details like usernames/projects in screenshots/videos.

![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/dae1e89c-5fed-45d0-8a1c-964062a0f498)

The path should match or be similar to what VS Code shows in the Open Editors pane (D2 is a folder at the root of the workspace).

![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/02b9aafe-c465-4578-adc9-3b77b2e60f11)

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.1.
