### ISSUE TITLE
Remove vcpkg code action from missing include scenarios

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11252]
This used to work at some point with an internal build, but I'm not sure if it ever worked with a public release (i.e. the ones I tried all don't work).

The code action implementation is supposed to check if it's a system header and show different code actions.

You can set compilerPath to "" for a repro.

I reviewed the code and it seems to be setup to do the right thing, but it's going wrong at some point either in cpptools or the TypeScript that handles the result.

![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/16668534-bd1b-4741-9fc4-c96c881686e4)

**Comment by bobbrow** [comment]
It would be nice to remove the "vcpkg" code action as part of this if possible.

**Comment by sean-mcmanus** [comment]
@bobbrow You mean remove the vcpkg code action entirely? Even for non-system includes?

**Comment by bobbrow** [comment]
No, just for system includes since it's not going to help for that case.

**Comment by sean-mcmanus** [comment]
@bobbrow Yeah, the code already handles/checks that -- it's just a matter of figuring out why it's not working as expected (like it used to).

**Comment by browntarik** [comment]
The edit compiler path code action appearing is expected behavior. A fix for the vcpkg code action can be found here: https://github.com/microsoft/vscode-cpptools/pull/11280

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.1.
