### ISSUE TITLE
Coloring arguments in macros is wrong sometimes (v1.17.0)

### ISSUE THREAD

**Issue by ebaumotte** [microsoft/vscode-cpptools#11256]
### Environment

- OS and Version: Fedora Linux 38
- VS Code Version: v1.80.1
- C/C++ Extension Version: v1.17.0 (Pre-Release)
- If using SSH remote, specify OS of remote machine: Fedora Linux 38

### Bug Summary and Steps to Reproduce

Bug Summary:

Macro coloring seems to be wrong sometimes. It's inconsistent between same lines of code and sometimes just straight up doens't work correctly. The easiest I've been able to reproduce it has been with gtest `TEST`/`EXPECT_` macros.

Copying a block of incorrectly colored code also has the same incorrect colors while writing same lines of code surrounded by other code sometimes leads to different results. 

All examples are using an ssh remote connection, haven't tested locally. Reloading window/ closing+reopening VS Code does not fix the issue, the exact same coloring mistakes are made after it loads. Switching between extension versions also just reproduces the exact same coloring when switching to v1.17.0.

Example I:

v1.16.3 (correct):
![Screenshot from 2023-07-27 08-14-14](https://github.com/microsoft/vscode-cpptools/assets/116485083/a6f48722-9e0b-4543-ae1f-9cb9af9a26c0)

v1.17.0 (inconsistent colors):
![Screenshot from 2023-07-27 08-13-23](https://github.com/microsoft/vscode-cpptools/assets/116485083/cba38df2-8f0c-4f3a-bcc8-0eb8c516cd5f)

Example II:

v1.16.3:
![Screenshot from 2023-07-27 08-14-07](https://github.com/microsoft/vscode-cpptools/assets/116485083/4821989b-c923-4b32-a746-f9bc38b8f9dc)

v1.17.0 (just wrong):
![Screenshot from 2023-07-27 08-13-31](https://github.com/microsoft/vscode-cpptools/assets/116485083/88909c36-90f1-4306-b35a-bae191dfe21a)

### Configuration and Logs

```shell
-------- Diagnostics - 27/07/2023, 08:28:19
Version: 1.17.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        ...
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "linux-clang-x64",
    "compilerPathInCppPropertiesJson": "/usr/bin/clang",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "/home/ebaumotte/fieldplacer-core/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        ...
    ],
    "compilerPath": "/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        " -fPIC -fPIC -fPIC -fext-numeric-literals -Wall -pthread -O3 -DNDEBUG -std=c++20",
        "-Wall -Wshadow -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers"
    ]
}
Custom configurations:
[ ... ]
{
    "includePath": [
        ...
    ],
    "defines": [
        ...
    ],
    "compilerPath": "/usr/bin/c++",
    "compilerArgs": [],
    "compilerFragments": [
        " -fPIC -fPIC -fPIC -fext-numeric-literals -Wall -pthread  -Wextra -pedantic -Werror -pedantic-errors -Wno-array-bounds -Wno-stringop-overflow -O3 -DNDEBUG -std=gnu++20 -fPIC"
    ]
}
cpptools version (native): 1.17.0.0
Translation Unit Mappings:
[ ... ]:
    ...
Translation Unit Configurations:
[ ... ]:
    Process ID: 2028650
    Memory Usage: 560 MB
    Compiler Path: /usr/bin/c++
    Includes:
        ...
    Defines:
        ...
    Standard Version: c++20
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=130101
Total Memory Usage: 560 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 26510
```

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. The team responsible has been informed, but we'll do some additional follow up as well...

**Comment by nickelpro** [comment]
To expand a little, the `macro` semantic token scope is eating adjacent characters under some conditions:
![image](https://github.com/microsoft/vscode-cpptools/assets/1032552/0f9789b7-ed3a-4363-ba55-46b2292f2852)

And in others is failing to recognize macros at all (resulting in the textmate grammar taking over)

**Comment by michelleangela** [comment]
@ebaumotte 
Thank you for submitting this issue. We'll let you know if we need more information.

**Comment by michelleangela** [comment]
Internal bug number 1864661.

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.1.

**Comment by michelleangela** [comment]
Fixed in release version https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2.
