### ISSUE TITLE
Inline Macro requires invoking hover first

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11260]
It's noticeable if you navigate to the macro using the keyboard instead of the mouse.

Invoking hover via Ctrl+k, Ctrl+i is a workaround.

The fix would involve detecting if the cursor is on a macro, change the code action to send a command to get the expanded macro, and then do the edit. Currently the code action just invokes the edit that was obtained from the hover.

UPDATE: Actually, I thought of a simpler fix by just invoking hover when the keyboard code action is triggered.

**Comment by bobbrow** [comment]
If we're planning to release 1.17 this week, we should hold this for 1.18 because the Loc strings won't likely be ready in time.

**Comment by sean-mcmanus** [comment]
Sure, I'm fine with that (then I could re-add my other loc change). But I thought 1.17.1 was this week and 1.17.2 would be next week? Not sure if that matters.
