### ISSUE TITLE
cpptools using 100% CPU when building intellisense on a C file for up to 6-7 minutes

### ISSUE THREAD

**Issue by dev31337** [microsoft/vscode-cpptools#11272]
### Environment

- OS and Version: Ubuntu 22.04 LTS
- VS Code Version:  1.80.2
- C/C++ Extension Version: 1.16.3
- If using SSH remote, specify OS of remote machine: No
-

### Bug Summary and Steps to Reproduce

Hi,

When I usually open C files the intellisense is being built and at the end of the search cpptools is using 100% CPU for a few seconds.

But for a certain C file, when the intellisense is being built, at the end the cpptools is using 100% CPU for up to 6 minutes.

This C file has 34K lines (so a little big compared to other C files) but, based on its content, I don't see why it would require so much CPU time for cpptools to build the intellisense.

The other issue is that sometimes when switching from another C file tab to this one, cpptools restarts to use 100% CPU for up to 6 minutes.

I tried to debug this by enabling C_Cpp.loggingLevel = Debug, but there is no output while cpptools uses 100% CPU for 6 minutes.

At the end I only get "Update IntelliSense time (sec): 360.213".

Is there a way to know what cpptools is doing somehow during these 6 minutes ?

I also have others questions who may help me debug the issue:

. Does cpptools also scan the folders or just build the .ipch files (while another process does the scan) ?
. Is it normal that each time I open a C file the intellisense is being built again ? (as if the stored .ipch files were ignored)
. Is it normal that when I select "C/C++: Reset Intellisense Database" it does not remove the stored .ipch files ?
. This particular file triggers the "editor.foldingMaximumRegions" limit asking to increase it, is it possible that it could be the reason of the issue with the intellisense ?

Finally I would like to add that I don't have this issue with an old VSCode version v1.46.0/cpp-extension-v1.01) (but I also have the issue with a less older version v1.70.2/cpp-extension-v1.15.4)

Regards.

### Configuration and Logs

```shell
c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/src/",
                "${workspaceFolder}/.vsincludes/include1/",
                "${workspaceFolder}/.vsincludes/include2/",
                "${workspaceFolder}/.vsincludes/include3/",
                "${workspaceFolder}/.vsincludes/include4/",
                "${workspaceFolder}/.vsincludes/include5/",
                "${workspaceFolder}/.vsincludes/include6/"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "__x86_64__",
                "__LP64__"
            ],
            "compilerPath": "",
            "intelliSenseMode": "gcc-x64",
            "browse": {
                "path": [
                ]
            }
        }
    ],
    "version": 4
}

C/C++: Log Diagnostics:
-------- Diagnostics - 7/31/2023, 9:35:44 PM
Version: 1.16.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "/mnt/project/src/",
        "/mnt/project/.vsincludes/include1/",
        "/mnt/project/.vsincludes/include2/",
        "/mnt/project/.vsincludes/include3/",
        "/mnt/project/.vsincludes/include4/",
        "/mnt/project/.vsincludes/include5/",
        "/mnt/project/.vsincludes/include6/"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE",
        "__x86_64__",
        "__LP64__"
    ],
    "compilerPath": "",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [],
        "limitSymbolsToIncludedHeaders": true
    },
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "",
    "mergeConfigurations": false
}
cpptools version (native): 1.16.3.0
No active translation units.

Logs from the language server logging:
loggingLevel: Debug
cpptools version (TypeScript): 1.16.3
cpptools version (native): 1.16.3.0
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/queryCompilerDefaults (id: 1)
LSP: cpptools/didChangeCppProperties (id: 2)
LSP: cpptools/queryCompilerDefaults (id: 3)
Querying compiler for default C++ language standard using command line: /usr/bin/gcc -x c++ -E -dM /dev/null
Detected language standard version: gnu++17
Querying compiler's default target using command line: "/usr/bin/gcc" -dumpmachine
Compiler returned default target value: x86_64-linux-gnu
Compiler query command line: /usr/bin/gcc -std=c17 -m64 -Wp,-v -E -dM -x c /dev/null
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/gcc'
Compiler query command line: /usr/bin/gcc -std=gnu++17 -m64 -Wp,-v -E -dM -x c++ /dev/null
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/gcc'
Code browsing service initialized
Skipping query of compiler due to explicitly empty compilerPath
Skipping query of compiler due to explicitly empty compilerPath
Discovering files...
  Discovering files: 0 file(s) processed
LSP: cpptools/didChangeCppProperties (id: 4)
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
  4 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: cpptools/textEditorSelectionChange
LSP: textDocument/didOpen: file:///mnt/project/src/data.c
LSP: cpptools/activeDocumentChange: file:///mnt/project/src/data.c
LSP: cpptools/getCodeActions: file:///mnt/project/src/data.c (id: 5)
LSP: cpptools/getDocumentSymbols: file:///mnt/project/src/data.c (id: 6)
LSP: cpptools/textEditorSelectionChange
LSP: cpptools/getSemanticTokens: file:///mnt/project/src/data.c (id: 7)
sending compilation args for /mnt/project/src/data.c
  include: /mnt/project/src
  include: /mnt/project/.vsincludes/include1
  include: /mnt/project/.vsincludes/include2
  include: /mnt/project/.vsincludes/include3
  include: /mnt/project/.vsincludes/include4
  include: /mnt/project/.vsincludes/include5
  include: /mnt/project/.vsincludes/include6
  define: _DEBUG
  define: UNICODE
  define: _UNICODE
  define: __x86_64__
  define: __LP64__
  other: --gcc
  other: --gnu_version=130100
  stdver: c17
  intelliSenseMode: linux-gcc-x64
Checking for syntax errors: /mnt/project/src/data.c
Queueing IntelliSense update for files in translation unit of: /mnt/project/src/data.c
  tag parsing file: /mnt/project/src/data.c
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 8)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 9)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 10)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 11)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 12)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 13)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 14)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 15)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 16)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 17)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 18)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 19)
LSP: cpptools/getCodeActions: file:///mnt/project/src/data.c (id: 20)
LSP: cpptools/getFoldingRanges: file:///mnt/project/src/data.c (id: 21)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 8)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 9)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 10)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 11)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 12)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 13)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 14)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 15)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 16)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 17)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 18)
LSP: cpptools/getCodeActions: file:///mnt/project/src/data.c (id: 22)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 23)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 24)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 25)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 26)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 27)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 28)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 29)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 30)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 31)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 32)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 33)
LSP: cpptools/getInlayHints: file:///mnt/project/src/data.c (id: 34)
LSP: $/cancelRequest (cpptools/getInlayHints, id: 19)
LSP: Request canceled by server (<unknown/completed>, code: -32802, id: 19)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 23)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 24)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 25)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 26)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 27)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 28)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 29)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 30)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 31)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 32)
LSP: Request canceled by server (cpptools/getInlayHints, code: -32802, id: 33)
Error squiggle count: 0
LSP: cpptools/getCodeActions: file:///mnt/project/src/data.c (id: 35)
LSP: cpptools/getFoldingRanges: file:///mnt/project/src/data.c (id: 36)
Update IntelliSense time (sec): 360.213
```

### Other Extensions

No other extension

**Comment by sean-mcmanus** [comment]
When you say cpptools is using CPU for 6 minutes, I assume you actually mean cpptools-srv, which is the process that does the IntelliSense parsing. You could attach a debugger to the process using CPU and get a call stack: https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

Your usage of a /mnt directory could impact performance if it has to a slow remote operation for file access, i.e. if you're trying to connect to files on a Windows OS from within WSL.

cpptools builds a browse .db database (for all files in the workspace) and cpptools-srv builds .ipch files (for one TU).

The .ipch file would only help if using a large header file -- if your source file is 34k then it wouldn't be helping.

Reset IntelliSense Database only removes the .db file and not .ipch, which could be removed manually or C_Cpp.intelliSenseCacheSize could be set to 0.

The folding regions maximum shouldn't matter.

It sounds like this may be a regression, but the good version was from such a long time ago it would be hard to narrow down what change caused it, and/or the increased processing may be from a bug fix where the older version was bailing out before finishing the parsing.

Are you able to share any repro sample that exhibits the slow behavior?

I recall we have noticed a slowdown with the large sqlite3.c file with hundreds of thousands of lines of code, so that might be a repro we could follow up on.

**Comment by dev31337** [comment]
Than you for your reply and for very useful explanations.

I do really mean "cpptools" which is running for 5-6 minutes with 100% CPU usage.

Not "cpptools-srv" which is quickly running before "cpptools" and uses very few CPU (peak at 5% at most).

I will check how to attach a debugger to "cpptools" to see if I can find something useful.

Can you tell me more about "cpptools builds a browse .db database (for all files in the workspace) " so I can have a look at it.

Where is this .db database located or its full name so I can find it ? 
What is the purpose of this database, is it used by the intellisense  ? (I thought only .ipch files were used by intellisense)
Does "cpptools" really browse every files in the workspace AND all its sub-directories ?
Does "cpptools" also browse the configured includePath ?
Does "cpptools" limit its browsing to what is configured as "browse: { [ path ] }" in the settings JSON file ?

I tried to uninstall/re-install cpp extensions until I found a perfectly working version.

Everything is working perfectly fine up to v1.12.4. (the higher the version you use the longer it takes to build intellisense but cpptools runs quickly at the end and does not consume 100% CPU for 6 minutes)

As soon as I install the higher one v1.13.6 the issue starts to happen, when the debug console shows "Error squiggle count: 0" then immediately "cpptools" starts using 100% CPU for 6 minutes.

I was unable to find v1.13.0 (or something between 1.12.4 and 1.13.16) to test it.

**Comment by sean-mcmanus** [comment]
We have notes on attaching a debugger to get a call stack at https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv . Setting C_Cpp.loggingLevel to "Debug" may also provide info.

The cpptools database building will be shown in the debug logging as a "tag parsing" message.

The easiest way to locate the database is to set the C_Cpp.default.browse.databaseFilename setting (or the equivalent setting in c_cpp_properties.json) to something like `"${workspaceFolder}/.vscode/vc.db"`.

The database is used for global symbol information that crosses the TUs.

Yes, cpptools does a parse on all the source files under the workspace folder, unless they are excluded via C_Cpp.files.exclude. It will only parse the header files if the name of the header matches a header that is included by a source file.

You could also limit the parsing by changing `"browse": { "path": }` in c_cpp_properties.json, which defaults to the includePath.

It sounds like you're describing what might be a regression bug.

**Comment by sean-mcmanus** [comment]
The logging "Update IntelliSense time (sec): 360.213" means that cpptools-srv is processing for 6 minutes and not cpptools. I don't  know how that logging could appear with cpptools using CPU. Maybe your tasks report is treating the cpptools-srv process CPU usage as belonging to cpptools since cpptools-srv is a child process?

**Comment by dev31337** [comment]
Thank for your reply.

To answer your very last comment, I use "top" on Linux and I can clearly see the difference between cpptools-srv and cpptools, and it is definitely cpptools that uses 100% CPU for 6 minutes.

I can see cpptools-srv using around 5% CPU before and immediately after C_Cpp.loggingLevel to "Debug" outputs the line "Error squiggle count: 0" then cpptools starts using the CPU at 100% for 5 minutes straight. (while cpptools-srv runs less than a minute)

In the debug log I pasted in my initial comment (which I wished included timestamp at each line in the future) I can tell you that the "tag parser" is running fine up the to line "Error squiggle count: 0" from which the issue with cpptools starts.

Can you please tell me more about "C_Cpp.files.exclude" can I put it in the file "c_cpp_properties.json" or should I create another JSON file ?

I will also try attaching a debug to  cpptools  and stop it while it uses all the CPU several time to check the stack trace.

**Comment by sean-mcmanus** [comment]
C_Cpp.files.exclude is a VS Code settings, i.e. from the settings editor or a settings json file.

Yeah, a call stack would be helpful.

**Comment by dev31337** [comment]
Hi,

I just tested C/C++ extension v1.17.5 (with Code v1.82.2) and the issue is gone.

I'm closing this issue

Regards.
