### ISSUE TITLE
Symbol need many time to load

### ISSUE THREAD

**Issue by Jackie-Yang** [microsoft/vscode-cpptools#1127]
- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.13.1
sublime-keybindings|ms-|2.9.1

---

Steps to Reproduce:

1. It needs almost 10 sec to loading when I use "Go to symbol in File..." at the first time in a file. (My working folder almost 20G)
![loading](https://user-images.githubusercontent.com/18381153/31482524-4ddcaf1e-af5b-11e7-853c-1acf9a9472d9.png)

2. Seach file using Ctrl+P is faster then before, but sometimes it still needs to loading for a long time (Rebuild Index ?)

Reproduces without extensions: Yes/No

**Comment by bobbrow** [comment]
Does the 10 second delay happen only the first time you open the file, or every time you open the same file?  The symbols should be saved to a database the first time you open the file so subsequent file opens should be faster unless the file has changed in another editor or you switched branches and the timestamp of the file changed.

**Comment by sean-mcmanus** [comment]
The symbol searching does some sort of filename cache generation the first time. It seems too slow to me, and we could probably improve it.

**Comment by Jackie-Yang** [comment]
@bobbrow Only at the first time

**Comment by bobbrow** [comment]
This should have been addressed in 1.19
