### ISSUE TITLE
cwd option in tasks.json ignored, cwd is awlays in current file directory

### ISSUE THREAD

**Issue by dznshfvt** [microsoft/vscode-cpptools#11273]
### Environment

- OS and version: Linux Mint 21.1 x86_64 (Kernel: 5.15.0-76-generic)
- VS Code: 1.80.2
- C/C++ extension: 1.16.3
- GDB / LLDB version: GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1

### Bug Summary and Steps to Reproduce

Bug Summary:
C++ scripts are searching for files in ${fileDirname}

main.cpp
```
#include <fstream>

using namespace std;

int main()
{

    ofstream file;

    file.open("file.txt");
    file << "Hello World!" << endl;
    file.close();
}
```
will alwayys create file "file.txt" in same directory as main.cpp, option "cwd" in tasks.json is ignored

Steps to reproduce:
1. Create empty folder, open it with vs code
2. Create src folder
3. In src folder create main.cpp and write script to create file and write something to it
4. create tasks.json and change ${fileDirname} to ${workspaceFolder}
5. Run "Debug/Run C/C++ File" from main.cpp (it will create file in same directory as main.cpp file
6. Create any name directory and place main.cpp there
7. Run "Debug/Run C/C++ File" from main.cpp (it will again create file in same directory as main.cpp file, not in workspace folder)

### Debugger Configurations

tasks.json
```
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${workspaceFolder}/src/*.cpp",
                "-o",
                "${workspaceFolder}/bin/main"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs
```
The program '/home/username/project_folder/src/main' has exited with code 0 (0x00000000).
```

**Comment by bobbrow** [comment]
Hi there. `tasks.json` sets the cwd for the step that builds your code.  When you run the built program, that goes through the `launch.json` file instead.  Can you check that file and see if setting `"cwd"` in there addresses your issue?

**Comment by dznshfvt** [comment]
Hello. I didnt used `launch.json` file until that moment. I created it and set `"cwd"` to `"${forkspaceFolder}"` and it seems to be working fine. However, i have some questinable moment, before creation of ```launch.json``` i was able to press `F5` and my project was (p)re-builded before debugging. how can i have that again?

Thank you.

**Comment by bobbrow** [comment]
`launch.json` should have a property called `preLaunchTask` in it.  Set that to match the `label` of the build task in `tasks.json` that you want to run before starting debugging.
