### ISSUE TITLE
Support for C++ attributes

### ISSUE THREAD

**Issue by Tymon13** [microsoft/vscode-cpptools#11270]
### Feature Request

Currently, [C++ attributes](https://en.cppreference.com/w/cpp/language/attributes) like `[[noreturn]]` or `[[maybe_unused]]` are interpreted as two nested scopes of `[]` and something (?) inside. 
![image](https://github.com/microsoft/vscode-cpptools/assets/25457529/74cefab0-8a9d-4bdb-bb7b-cf25918e6d13)

What I'd like to see as a user:
* There's a code completion feature after typing in `[[`, suggesting all attributes available for C++ standard set
* There's separate colour setting for them
  * Since it's rare to actually have multiple attributes in one list, it's could be fine if there's just one colour for both `[[` and the attribute name
  * But attribute parameters (like `[[deprecated("reason")]]`) should be considered like function parameters for example
  * Colour setting should be documented (especially if internally implementation uses e.g. `decorator` to represent attribute token)

**Comment by ldeng-ustc** [comment]
Support. This is very useful for me. There is currently no completion for any attributes, so when typing an attribute like `[[maybe_unused]]` or `[[unlikely]]` you must type the full text. I'm not quite sure why this question isn't getting attention, are there so few people using standard attributes?

**Comment by sean-mcmanus** [comment]
@ldeng-ustc @Tymon13 FYI, GitHub Copilot can suggest completions for C++ attributes, but it will only suggest the one it thinks is the most likely and not the complete list of possible attributes:

![Image](https://github.com/user-attachments/assets/55750469-b19d-4c84-af23-07e9a6de5bfe)

![Image](https://github.com/user-attachments/assets/196b2e80-4a39-4dc0-8872-e42e12d36dcf)

![Image](https://github.com/user-attachments/assets/8a15d08f-0ad9-4746-ab29-d6774e6a60a9)
