### ISSUE TITLE
postDebugTask not executed if attaching to a remote process with GDB was unsuccessful

### ISSUE THREAD

**Issue by kyselejsyrecek** [microsoft/vscode-cpptools#11285]
### Environment

- OS and version: Ubuntu 23.04
- VS Code: 1.80.2
- C/C++ extension: ms-vscode.cpptools 1.16.3
- OS and version of remote machine (if applicable): Linux, ARM
- GDB / LLDB version: GNU gdb (Ubuntu 13.1-2ubuntu2) 13.1 (gdb-multiarch)

### Bug Summary and Steps to Reproduce

When launching the debugging session configured to attach to a process, VS Code displays a pop-up dialog forcing the developer to pick a process running on the target machine. The list seems to be obtained directly from GDB which then drops the connection to GDB Server. GDB is then launched again, for the purpose of actually attaching to the chosen process via GDB Server running on the target machine.

To simplify the process, our configuration of remote debugging using GDB involves launching GDB Server remotely via SSH using a VS Code task. However, since the first GDB/GDB Server session is used by the VS Code merely for obtaining process list, GDB Server cannot be launched with the `--once` switch which would force it to quit immediately after disconnection of the first GDB client instance. We have thus set a `"preLaunchTask": "startGDBServer"` and a corresponding `"postDebugTask": "stopGDBServer"`. The problem is that `preLaunchTask` is launched as soon as the developer hits the "start debugging" button, but the `postDebugTask` is not executed if he/she does not pick a running process from the list and stops the debugging prematurely or if attaching to the process is unsuccessful. And it is unpleasantly easy not to pick a process - all one has to do is to click outside of the list or to simply switch windows (e.g., to an SSH window for launching the process in question). This way, `gdbserver` ends up running on the target machine forever.

### Debugger Configurations

```shell
// launch.json
    {
      "name": "C/C++: remote debugging",
      "type": "cppdbg",
      "request": "attach",
      "useExtendedRemote": true,
      "program": "${input:pathToBinary}", // <<< debugged executable // FIXME
      "MIMode": "gdb", 
      "miDebuggerPath": "gdb-multiarch",
      "miDebuggerServerAddress": "${input:targetIP}:1234",
      "preLaunchTask": "startGDBServer",
      "postDebugTask": "stopGDBServer"
    }

// tasks.json
  "tasks":[
    {
      "label": "startGDBServer",
      "type": "process",
      "command": "sshpass",
      "args": [
        "-p",
        "password", 
        "ssh",
        "user@${input:targetIP}",
        "nohup gdbserver --multi :1234 >/dev/null 2>&1 &"
      ],
      "presentation": {
        "reveal": "silent"
      }
    },
    {
      "label": "stopGDBServer",
      "type": "process",
      "command": "sshpass",
      "args": [
        "-p",
        "password", 
        "ssh",
        "user@${input:targetIP}",
        "killall gdbserver"
      ],
      "presentation": {
        "reveal": "silent"
      }
    }
  ]
```

### Debugger Logs

```shell
N/A
```

**Comment by WardenGnaw** [comment]
`postDebugTask` is owned by VS Code, you will want to make an issue at https://github.com/microsoft/vscode/issues

**Comment by kyselejsyrecek** [comment]
Dear Mr. WardenGnaw, 

may I suggest that you or your colleague from the appropriate team at Microsoft transfer this issue among your respective project repositories? The GitHub interface allows project managers to do so: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

As a member of the community, I would consider that an appreciated form of support from the side of project owners. Certainly, not being employed at Microsoft myself, I cannot tell straight from an observed defect, which team from the company is actually responsible for handling it.

I would be very thankful for such treatment of future reported issues and this one in particular, as it is already quite time consuming to describe a problem in a reproducible and comprehensible enough way.

Kind regards.

**Comment by sean-mcmanus** [comment]
@kyselejsyrecek We don't have the ability to transfer issues to the VS Code repo:

<img width="244" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/83f933a4-cec0-4ae1-a566-358299bbe712">
