### ISSUE TITLE
Debugging of multiple processes with GDB is terminated when any child process exits

### ISSUE THREAD

**Issue by kyselejsyrecek** [microsoft/vscode-cpptools#11283]
### Environment

- OS and version: Ubuntu 23.04
- VS Code: 1.80.2
- C/C++ extension: ms-vscode.cpptools 1.16.3
- OS and version of remote machine (if applicable): Linux, ARM
- GDB / LLDB version: GNU gdb (Ubuntu 13.1-2ubuntu2) 13.1 (gdb-multiarch)

### Bug Summary and Steps to Reproduce

When debugging a multi-process executable with GDB configured to attach to child processess and to disable detaching on `fork()` using setup commands listed below, VS Code terminates GDB as soon as the first child process exits.

In such situation, the GDB would normally continue debugging remaining processes when `set detach-on-fork off` is set.

My scenario involves attaching to the main process (before child processess are made with `fork()`) on a remote Linux machine (ARM platform). I am using `gdb-multiarch` from the official repository of Ubuntu 23.04 for this purpose, but the issue could probably be reproduced without remote debugging on an x86_64 machine.

This problem was reported once in 2019 at https://github.com/microsoft/vscode-cpptools/issues/1723#issuecomment-527114626 (see section Observed Bugs, bug 1).

### Debugger Configurations

```shell
"setupCommands": [
        {
          "description": "Follow child process instead of parent process after fork",
          "text": "set follow-fork-mode child",
          "ignoreFailures": false
        },
        {
          "description": "After fork, both parent and child processess remain being debugged.",
          "text": "set detach-on-fork off",
          "ignoreFailures": false
        }
]
```

### Debugger Logs

```shell
1: (757927) ->*running,thread-id="2"
1: (758145) ->(gdb)
1: (758256) ->~"[Inferior 2 (process 11995) exited normally]\n"
1: (758256) ->=thread-exited,id="2",group-id="i2"
1: (758256) ->=thread-group-exited,id="i2",exit-code="0"
[Inferior 2 (process 11995) exited normally]
1: (758258) Send Event AD7ThreadDestroyEvent
1: (758298) ->*stopped,reason="exited-normally"
1: (758299) <--gdb-exit
1: (758299) ->^exit
1: (758304) <-logout
1: (758319) Send Event AD7ProgramDestroyEvent
Debugger has disconnected from the program 'fork_test'.
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.

**Comment by thelex0** [comment]
Hi, 
are there any workarounds?
