### ISSUE TITLE
Slow intellisense, switch header/code file in c++.

### ISSUE THREAD

**Issue by dezbracaty** [microsoft/vscode-cpptools#11293]
### Environment

- OS and version: macos 13.5  M1 pro 
- VS Code:  1.81.0
- C/C++ extension: 1.16.3
- OS and version of remote machine (if applicable): local compiler
- GDB / LLDB version: clang 14.0.3  .lldb-1403.0.17.67

### Bug Summary and Steps to Reproduce

Bug Summary:
If I enable cMAKE-Tools extension , the intellisense service will become very very slow .  Include  go to declare or definition , find reference , switch code / header file .  If I disable this extension , the service will become very fase .

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do '...'
4. See error...

### Debugger Configurations

```shell
Do not need configurations , I had not change any thing.
```

### Debugger Logs

```shell
No logs, if anyone need any logs, tell me .
```

### Other Extensions

C/C++

**Comment by michelleangela** [comment]
@dezbracaty 
Could you enable logging of the language server for the C++ extension (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server). After the logging is enabled for the C++ extension, could you reload the VS Code window and share the full logs here? The logs will show configurations coming from the [vscode-cmake-tools](https://github.com/microsoft/vscode-cmake-tools/issues) provider.
