### ISSUE TITLE
Formatting of selection no longer work

### ISSUE THREAD

**Issue by jyavenard** [microsoft/vscode-cpptools#1130]
Originally opened as https://github.com/Microsoft/vscode/issues/36126

Steps to Reproduce:

    Select text to format
    Press Command-K Command-F
    You get the message in the status bar that "the key combination (command-K command-F) isn't a command.
    However, when you go to see the shortcuts we see:
    {
    "command": "editor.action.formatSelection",
    "key": "cmd+k cmd+f",
    "when": "editorHasDocumentSelectionFormattingProvider && editorHasSelection && editorTextFocus && !editorReadonly"
    }

so command-k command-f is certainly defined.

VS Code issue was closed with

> Looks like the C++ extension doesn't provide a formatter that can support the selection only. I suggest that you file a feature request against the C++ extension https://github.com/Microsoft/vscode-cpptools, nothing we can do about this on the VS Code side.

**Comment by jyavenard** [comment]
this used to work just fine until I upgraded VS Code earlier in the morning.

I have clang-format configured with the following workspace option:
    "C_Cpp.clang_format_path": "/Users/jyavenard/.mozbuild/clang-format-5.0",
    "C_Cpp.intelliSenseEngine": "Default",

**Comment by sean-mcmanus** [comment]
It works for me (I can't repro any problem). We support range based formatting and none of this code has changed recently. What VS Code, OS, and cpptools versions do you have?

**Comment by jyavenard** [comment]
@sean-mcmanus indeed, it works.... it appears to be an intermittent issue with VS code
https://github.com/Microsoft/vscode/issues/36126#issuecomment-336259189

**Comment by sean-mcmanus** [comment]
@jyavenard It sounds like an intermittent issue with our extension. If hover doesn't work show info, then it means our main thread is blocked and formatting also will fail to work. We're continuing to work on making our extension not fail intermittently.

**Comment by jyavenard** [comment]
other than formatting, everything else appeared to work just fine... looking for symbols, debugging, stepping in etc...

only thing that didn't work was the formatting

**Comment by sean-mcmanus** [comment]
@jyavenard Okay, if you hit the repro again, you could enable logging to see the inputs/outputs of our formatting operation to see if it's a bug on our side or VS Code (or clang-format). We've received reports of our internal document becoming corrupted, such that the input to formatting is incorrect (causing the output to appear incorrect), but this is the only report we've seen so far of formatting not working.

**Comment by jyavenard** [comment]
do you have instructions on how to enable logging and where to look?

**Comment by sean-mcmanus** [comment]
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md . You need at least log level 5 set. You should search for "Formatting input" (our internal document data), "Formatting raw output" (output from clang-format) and "Formatting diffed output" (what we send to VS Code).

**Comment by jyavenard** [comment]
if you need to restart to enable logging, it's unlikely i'll get anything meaningful, seeing that a restart typically fixes the problem

**Comment by sean-mcmanus** [comment]
@jyavenard Our next update will change this so you don't need to restart to enable logging (it'll be a setting and logging will appear in the output window), and formatting logging will start at level 6 instead of 5.
