### ISSUE TITLE
unable to switch to automatic code analysis mode

### ISSUE THREAD

**Issue by ozhang3** [microsoft/vscode-cpptools#11316]
### Environment

- OS and Version: win10 1703
- VS Code Version: 1.80.1
- C/C++ Extension Version: v1.16.3
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
unable to switch to automatic code analysis mode

Steps to reproduce:
1. click on code analysis mode
2. shows manual (not modifiable)

Expected behavior:
allows toggling between auto/manual

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux-g++",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/local/bin/g++",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
That is by design -- it's not changeable from the status bar, which just reports it as Manual or Automatic. You need to set C_Cpp.codeAnalysis.clangTidy.enabled to true (and verify C_Cpp.codeAnalysis.runAutomatically is set to the default of true).

Did you have an alternative design in mind? We're somewhat limited by the VS Code status bar UI capabilities.

**Comment by ozhang3** [comment]
Thanks a bunch! Setting "C_Cpp.codeAnalysis.clangTidy.enabled" to true resolves the issue: the status bar now displays Automatic for Code Analysis Mode. And yes allowing toggling directly from the status bar would be a more user-friendly design...

**Comment by sean-mcmanus** [comment]
@ozhang3 The VS Code UI only allows 1 command link in the status bar UI and we currently show a "Run Now" command which shows the 3 options for a "manual run". What do you think about adding a 4th option for "Switch to Run Code Analysis Automatically" that would set 1-2 of the required settings to change it to run automatically?
