### ISSUE TITLE
Localization - [Copy declaration of 'my_function'] translated as [‘my_function’ 的复制声明’] in CHS

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#11313]
Internal bug number: 882874

English:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/6a6ea99f-5eab-4a92-92b7-e9d1a4baf3d0)

CHS:
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/15c7db21-5a56-43ee-aeab-7c8cd9c75fcc)

Expected (CHT example):
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/0a8cb5b6-a12b-4b8d-a5c0-9079636df6cf)

**Comment by bobbrow** [comment]
This was fixed with #11290
