### ISSUE TITLE
Semantic colorization should not be applied if `editor.semanticTokenColorCustomizations`  is not enabled

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#11311]
Semantic colorization is still applied even if `editor.semanticTokenColorCustomizations` is not enabled.

**Sample code:**
```cpp
namespace myNamespace
{
    void myFunction()
    {}
}


int main()
{
    myNamespace::myFunction();
}
```

**Settings to use:**
```json
    "C_Cpp.enhancedColorization": "enabled",
    "editor.semanticTokenColorCustomizations": {
        "enabled": false,
        "rules": {
            "namespace": "#f700ff"
        }
    }
```

**Repro steps;**
1. Use sample code.
2. use provided settings.
3. Note: run command "Developer: Inspect Tokens and Scopes" to see colorization info of a symbol.

**Actual result:**
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/5af784bd-e246-4379-b63e-071b451f67a4)

**Expected result:**
![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/6b1afc37-6529-4b71-a4d9-9aa59a964baa)

**Comment by michelleangela** [comment]
This is actually a VS Code, since if `editor.semanticTokenColorCustomizations` is disabled, then the semantic provider should not get invoked to request for results from the language server.

**Comment by Colengms** [comment]
This isn't a cpptools issue.  I opened a VS Code issue instead.
