### ISSUE TITLE
Some characters rendered incorrectly in Markdown comments when inline/block code is used

### ISSUE THREAD

**Issue by bshoshany** [microsoft/vscode-cpptools#11322]
### Environment

- OS and Version: Windows 11 v22621.2134
- VS Code Version: 1.81.1
- C/C++ Extension Version: 1.17.2

### Bug Summary and Steps to Reproduce

Bug Summary:

Thanks for adding this feature following issue #6020! It is very useful, but there are a few kinks to iron out.

1. Some characters such as `<`, `>`, and `_` within inline code or fenced code blocks in Markdown comments are incorrectly rendered with an escape character in front, e.g. `\<`, `\>`, and `\_`.
2. Indentation is not preserved in fenced code blocks, hindering readability.

Steps to reproduce:

Create the following sample program:

```cpp
#include <iostream>
#include <vector>

// This function returns an `std::vector<size_t>` with `n` elements initialized to consecutive values.
//
// Usage example:
// ```
// std::vector<size_t> vec;
// vec = test();
// ```
std::vector<size_t> test(const size_t n)
{
    std::vector<size_t> temp(32);
    for (size_t i = 0; i < n; ++i)
        temp[i] = i;
    return temp;
}

int main()
{
    std::vector<size_t> vec = test(32);
    for (const size_t k : vec)
        std::cout << k << ' ';
}
```

Expected behavior: The Markdown comment should be rendered correctly.

Actual behavior: See screenshot.

![image](https://github.com/microsoft/vscode-cpptools/assets/61846320/ad339e65-5231-4c07-afc0-ec646034eb10)

### Configuration and Logs

```shell
I don't think any of these are relevant since the problem is just with Markdown rendering and not actual code, but I can attach them later if needed.
```

**Comment by bobbrow** [comment]
Thanks for reporting this.  We'll get it fixed.

**Comment by bshoshany** [comment]
Great, thank you! :)

**Comment by bobbrow** [comment]
The fix for this is available in 1.17.5

**Comment by bshoshany** [comment]
Awesome, thanks! However, the indentation in fenced code blocks still doesn't show correctly. My apologies, this is totally my fault - the code I put in my original comment isn't the right code. It doesn't match the screenshot and doesn't properly demonstrate the issue. I fixed it now. 

In 1.17.5 the first problem I mentioned (some characters are rendered with a redundant escape character) is fixed, but the fenced code blocks are still not correctly indented - see screenshot:

![image](https://github.com/microsoft/vscode-cpptools/assets/61846320/8e0a7af6-07c9-43fe-b11c-c72b74306b28)

The `for` loop should be indented for readability, but it is not. Would it be possible to fix this? Thanks again.

**Comment by bobbrow** [comment]
@browntarik does our comment parser eat all the leading whitespace?  If so, we should open a new bug to tell it to stop eating whitespace between backticks so that the VS Code markdown renderer can do the right thing.  If not, then we need to forward this bug on to the VS Code team.

**Comment by sean-mcmanus** [comment]
I think it's our comment processing code since TypeScript doesn't repro the issue. Would the new bug be for 1.18.0 or 1.17.6?

**Comment by bobbrow** [comment]
1.18.0

**Comment by bobbrow** [comment]
This is tracked by #11379 now
