### ISSUE TITLE
VS code 1.81.1:unable to start debugging

### ISSUE THREAD

**Issue by sunlightxhw** [microsoft/vscode-cpptools#11323]
### Environment

- OS and version:Windows_NT x64 10.0.19045
- VS Code:1.81.1 (user setup)
- C/C++ extension: v1.17.2
- OS and version of remote machine (if applicable):
- GDB / LLDB version: GNU gdb (GNU Arm Embedded Toolchain 10.3-2021.10) 10.2.90.20210621-git
- QEMU emulator version 7.1.0 (v7.1.0-11925-g4ec481870e-dirty)
- 
CODE VERSION INFORMATION:
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

### Bug Summary and Steps to Reproduce

Bug Summary:
1. I am using qemu to simulate embeded arm enviroment. I have compiled a embeded program rtthread.elf for debugging. 
2. I could debug it successfully via command line executable : arm-none-eabi-gdb.exe.  But when I used vscode interface to debug it it always failed becuase of unsuccessful run of my executable via vscode launch.json. See details at below.
3. When I begun to start debug via vscode with launch.json I found my program rtthread.elf could not be run successfully because the WINDOWS TERMINAL started by my exectuble(rtthread.elf) just showed shortly and then disappeared  (meant the executable exited), which caused vscode could not start remote debug via localhost:1234 leading to connection timeout failure.

[YOU COULD REPRODUCE THIS ISSUE ACCORDING TO ENVIROMENTS OF THE FOLLOWING LINKS：
enviroment :https://download-sh-cmcc.rt-thread.org:9151/www/aozima/env_released_1.3.5.7z
rtthread src code: https://github.com/RT-Thread/rt-thread.git  (version : lts-v4.1.x)
producing steps :https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/application-note/setup/qemu/vscode/an0021-qemu-vscode?id=%e6%ad%a5%e9%aa%a4%e5%9b%9b-%e4%bf%ae%e6%94%b9-qemu-dbgbat-%e6%96%87%e4%bb%b6

Steps to reproduce:
1. In this environment: 
- OS and version:Windows_NT x64 10.0.19045
- VS Code:1.81.1 (user setup)
- C/C++ extension: v1.17.2
- OS and version of remote machine (if applicable):
- GDB / LLDB version: GNU gdb (GNU Arm Embedded Toolchain 10.3-2021.10) 10.2.90.20210621-git

3. With this config...
            "name": "Debug @ Windows",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}\\rtthread.elf",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "miDebuggerServerAddress": "localhost:1234",
            "serverLaunchTimeout": 2000,
            "targetArchitecture": "ARM",
            "logging": { "engineLogging": true },
            "setupCommands": [
                {
                    "text": "cd ${workspaceRoot}"
                },
                {
                    "text": "shell qemu-dbg.bat"
                },
                {
                    "text": "target remote localhost:1234"
                },
                {
                    "text": "file rtthread.elf"
                },
                {
                    "text": "break main"
                }
            ],
            
            "customLaunchSetupCommands": [],
            "launchCompleteCommand": "exec-run",
            "osx": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb"
            },
            "linux": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb"
            },
            "windows": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb.exe"
            }
5. Do 
    DEBGUG @ WINDOWS
7. See error...
![image](https://github.com/microsoft/vscode-cpptools/assets/20431657/20882f81-9f1c-4960-b0b8-730a95b0e6c4)

### Debugger Configurations

```shell
my tasks.json:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "scons",
            "problemMatcher": [
                "$gcc"
            ],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared",
                "showReuseMessage": true
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "clean",
            "type": "shell",
            "command": "scons -c",
            "problemMatcher": [],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared",
                "showReuseMessage": true
            }
        },
        {
            "label": "qemu simulator",
            "type": "shell",
            "command": "qemu.bat",
            "problemMatcher" : []
        }
    ]
}

my launch.json:
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Debug @ Mac/Linux",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/rtthread.elf",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "miDebuggerServerAddress": "localhost:1234",
            "serverLaunchTimeout": 2000,
            "targetArchitecture": "ARM",
            "setupCommands": [
                {
                    "text": "cd ${workspaceRoot}"
                },
                {
                    "text": "shell qemu-dbg.sh"
                },
                {
                    "text": "target remote localhost:1234"
                },
                {
                    "text": "file rtthread.elf"
                },
                {
                    "text": "break application_start"
                }
            ],
            "customLaunchSetupCommands": [],
            "launchCompleteCommand": "exec-run",
            "preLaunchTask": "qemu debug",
            "osx": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb"
            },
            "linux": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb"
            },
            "windows": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb.exe"
            }
        },
        {
            "name": "Debug @ Windows",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}\\rtthread.elf",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "miDebuggerServerAddress": "localhost:1234",
            "serverLaunchTimeout": 2000,
            "targetArchitecture": "ARM",
            "logging": { "engineLogging": true },
            "setupCommands": [
                {
                    "text": "cd ${workspaceRoot}"
                },
                {
                    "text": "shell qemu-dbg.bat"
                },
                {
                    "text": "target remote localhost:1234"
                },
                {
                    "text": "file rtthread.elf"
                },
                {
                    "text": "break main"
                }
            ],
            
            "customLaunchSetupCommands": [],
            "launchCompleteCommand": "exec-run",
            "osx": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb"
            },
            "linux": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb"
            },
            "windows": {
                "MIMode": "gdb",
                "miDebuggerPath": "arm-none-eabi-gdb.exe"
            }
        },
    ]
}


my qemu-dbg.bat:
@echo off
if exist sd.bin goto run
qemu-img create -f raw sd.bin 64M

:run
start qemu-system-arm -M vexpress-a9  -kernel rtthread.elf -serial stdio -sd sd.bin -s -S
```

### Debugger Logs

```shell
1: (81) LaunchOptions{"name":"Debug @ Windows","type":"cppdbg","request":"launch","program":"D:\\rtthrd\\rt-thread-lts-v4.1.x\\bsp\\qemu-vexpress-a9\\rtthread.elf","args":[],"stopAtEntry":true,"cwd":"D:\\rtthrd\\rt-thread-lts-v4.1.x\\bsp\\qemu-vexpress-a9","environment":[],"externalConsole":true,"miDebuggerServerAddress":"localhost:1234","serverLaunchTimeout":2000,"targetArchitecture":"ARM","logging":{"engineLogging":true},"setupCommands":[{"text":"cd D:\\rtthrd\\rt-thread-lts-v4.1.x\\bsp\\qemu-vexpress-a9"},{"text":"shell qemu-dbg.bat"},{"text":"target remote localhost:1234"},{"text":"file rtthread.elf"},{"text":"break main"}],"customLaunchSetupCommands":[],"launchCompleteCommand":"exec-run","__configurationTarget":6,"MIMode":"gdb","miDebuggerPath":"arm-none-eabi-gdb.exe","__sessionId":"c8420137-3872-4026-bd0b-d7b3516943f1"}
1: (135) Starting: "D:\rtthrd\env-windows-v1.3.5\tools\ConEmu\ConEmu\..\..\..\tools\gnu_gcc\arm_gcc\mingw\bin\arm-none-eabi-gdb.exe" --interpreter=mi
1: (148) DebuggerPid=24776
[Warning] 1: (183) STDERR: D:\rtthrd\env-windows-v1.3.5\tools\gnu_gcc\arm_gcc\mingw\bin\arm-none-eabi-gdb.exe: warning: Couldn't determine a path for the index cache directory.
1: (187) ->=thread-group-added,id="i1"
1: (188) ->~"GNU gdb (GNU Arm Embedded Toolchain 10.3-2021.10) 10.2.90.20210621-git\n"
1: (194) ->~"Copyright (C) 2021 Free Software Foundation, Inc.\n"
1: (194) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
1: (194) ->~"\nType \"show copying\" and \"show warranty\" for details.\n"
1: (194) ->~"This GDB was configured as \"--host=i686-w64-mingw32 --target=arm-none-eabi\".\n"
1: (194) ->~"Type \"show configuration\" for configuration details.\n"
1: (194) ->~"For bug reporting instructions, please see:\n"
1: (194) ->~"<https://www.gnu.org/software/gdb/bugs/>.\n"
1: (194) ->~"Find the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>."
1: (194) ->~"\n\n"
1: (194) ->~"For help, type \"help\".\n"
1: (194) ->~"Type \"apropos word\" to search for commands related to \"word\".\n"
1: (194) ->(gdb)
1: (201) <-1001-gdb-set mi-async on
1: (217) ->1001^done
1: (217) ->(gdb)
1: (217) ->&"\n"
1: (217) ->^done
1: (217) ->(gdb)
1: (220) 1001: elapsed time 19
1: (223) <-1002-interpreter-exec console "show configuration"
1: (232) ->~"This GDB was configured as follows:\n   configure --host="
1: (232) ->~"i686-w64-mingw32 --target=arm-none-eabi\n"
1: (233) ->~"             --with-auto-load-dir=$debugdir:$datadir/auto-load\n             --with-auto-load-safe-path="
1: (233) ->~"$debugdir:$datadir/auto-load\n"
1: (233) ->~"             --with-expat\n"
1: (233) ->~"             --with-gdb-datadir=/mnt/workspace/workspace/GCC-10-pipeline/jenkins-GCC-10-pipeline-338_20211018_1634516203/install-mingw/arm-none-eabi/share/gdb (relocatable)\n"
1: (233) ->~"             --with-jit-reader-dir=/mnt/workspace/workspace/GCC-10-pipeline/jenkins-GCC-10-pipeline-338_20211018_1634516203/install-mingw/lib/gdb (relocatable)\n"
1: (233) ->~"             --without-libunwind-ia64\n"
1: (233) ->~"             --without-lzma\n"
1: (233) ->~"             --without-babeltrace\n"
1: (233) ->~"             --without-intel-pt\n"
1: (233) ->~"             --without-mpfr\n"
1: (233) ->~"             --without-xxhash\n"
1: (233) ->~"             --without-python\n"
1: (234) ->~"             --without-python-libdir\n"
1: (234) ->~"             --without-debuginfod\n"
1: (234) ->~"             --without-guile\n"
1: (234) ->~"             --disable-source-highlight\n"
1: (234) ->~"             --with-separate-debug-dir=/mnt/workspace/workspace/GCC-10-pipeline/jenkins-GCC-10-pipeline-338_20211018_1634516203/install-mingw/lib/debug (relocatable)\n"
1: (234) ->~"             --with-system-gdbinit=/mnt/workspace/workspace/GCC-10-pipeline/jenkins-GCC-10-pipeline-338_20211018_1634516203/install-mingw/i686-w64-mingw32/arm-none-eabi/lib/gdbinit (relocatable)\n"
1: (234) ->~"\n(\"Relocatable\" means the directory can be moved with the GDB installation\ntree, and GDB will still find it.)\n"
1: (234) ->1002^done
1: (234) ->(gdb)
1: (234) ->&"\n"
1: (234) ->^done
1: (234) 1002: elapsed time 11
1: (234) ->(gdb)
1: (250) <-1003-interpreter-exec console "cd D:\\rtthrd\\rt-thread-lts-v4.1.x\\bsp\\qemu-vexpress-a9"
1: (263) ->~"Working directory D:\\rtthrd\\rt-thread-lts-v4.1.x\\bsp\\qemu-vexpress-a9.\n"
1: (264) ->1003^done
1: (264) ->(gdb)
1: (264) ->&"\n"
1: (264) ->^done
1: (264) 1003: elapsed time 13
1: (264) ->(gdb)
1: (264) <-1004-interpreter-exec console "shell qemu-dbg.bat"
1: (307) ->1004^done
1: (307) ->(gdb)
1: (307) 1004: elapsed time 43
1: (307) ->&"\n"
1: (307) ->^done
1: (307) ->(gdb)
1: (307) <-1005-interpreter-exec console "target remote localhost:1234"
1: (14646) ->&"localhost:1234: Connection timed out.\n"
1: (14647) ->1005^error,msg="localhost:1234: Connection timed out."
1: (14647) ->(gdb)
1: (14647) ->&"\n"
1: (14647) ->^done
1: (14647) ->(gdb)
1: (14650) 1005: elapsed time 14342
1: (14654) Send Event AD7MessageEvent
1: (14654) <--gdb-exit
1: (14657) <-logout
```

### Additional Information

Here is terminal OUTPUT:
[8/11/2023, 9:45:24 AM] For C++ source files, IntelliSenseMode was changed from "windows-clang-x64" to "windows-gcc-arm" based on compiler args and querying compilerPath: "D:/rtthrd/env-windows-v1.3.5/tools/gnu_gcc/arm_gcc/mingw/bin/arm-none-eabi-gcc"
[8/11/2023, 9:45:24 AM] For C source files, IntelliSenseMode was changed from "windows-clang-x64" to "windows-gcc-arm" based on compiler args and querying compilerPath: "D:/rtthrd/env-windows-v1.3.5/tools/gnu_gcc/arm_gcc/mingw/bin/arm-none-eabi-gcc"

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.

**Comment by sunlightxhw** [comment]
Hi,thank You.

**Comment by xuming** [comment]
me too

**Comment by Agomezvi** [comment]
I have a similar issue. Using the c++ compilation of a helloworld.cpp, I try to use the debug launch with the following configuration:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) TC1 - Custom Attach to HelloWorld",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/hello",
            "stopAtEntry": false,
            "targetArchitecture": "x64",
            "cwd": "${workspaceFolder}",
            "customLaunchSetupCommands": [
              { "text": "target-run", "description": "run target", "ignoreFailures": false }
            ],
            "launchCompleteCommand": "exec-run",
            "linux": {
              "MIMode": "gdb",
              "miDebuggerPath": "/usr/bin/gdb"
            },
        },
    ]
}
```
And I get the following issue:

![LaunchDebugIssue](https://github.com/microsoft/vscode-cpptools/assets/123369385/cafa96d5-ff75-40f9-a566-0f8a37841092)

**Comment by borjamunozf** [comment]
Similar/same issue here. Also affects 1.82.2 VSCode release. That config example is coming from your official documentation, by the way.

The **target-run** or **target-attach** throws that error message. 

> I have a similar issue. Using the c++ compilation of a helloworld.cpp, I try to use the debug launch with the following configuration:
> 
> ```json
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "(gdb) TC1 - Custom Attach to HelloWorld",
>             "type": "cppdbg",
>             "request": "launch",
>             "program": "${workspaceFolder}/hello",
>             "stopAtEntry": false,
>             "targetArchitecture": "x64",
>             "cwd": "${workspaceFolder}",
>             "customLaunchSetupCommands": [
>               { "text": "target-run", "description": "run target", "ignoreFailures": false }
>             ],
>             "launchCompleteCommand": "exec-run",
>             "linux": {
>               "MIMode": "gdb",
>               "miDebuggerPath": "/usr/bin/gdb"
>             },
>         },
>     ]
> }
> ```
> 
> And I get the following issue:
> 
> ![LaunchDebugIssue](https://user-images.githubusercontent.com/123369385/271307592-cafa96d5-ff75-40f9-a566-0f8a37841092.png)

**Comment by pekotte** [comment]
I've the same issue :(
