### ISSUE TITLE
Walkthrough Improvement: Updated wording for "Customize Debugging" step

### ISSUE THREAD

**Issue by AlexandraKemperMS** [microsoft/vscode-cpptools#11320]
In the "Customize Debugging" step of the walkthrough, we currently state: 

"You can customize your debug configuration (e.g. to pass arguments to your program at run time) by selecting "Add Debug Configuration" to the right of the play button. The custom debug configuration is saved to your project's launch.json file" 

However, at this point in the walkthrough, a user has only opened a cpp file as a single file. Seeing the gear icon to add a debug configuration is only available if they have opened their code in a folder. We need to instruct users in this step that they need to open their code in a folder. 

Proposed new text for the "Customize debugging" step: 

"To customize your debug configuration, select the Explorer in the activity bar and open a folder that includes your C++ file. Open the C++ file, and select "Add Debug Configuration" to the right of the play button. The new debug configuration is saved to your project's launch.json file."

**Comment by darker16** [comment]
> လမ်းညွှန်ချက်၏ "Customize Debugging" အဆင့်တွင်၊ ကျွန်ုပ်တို့သည် လက်ရှိတွင် အောက်ပါအတိုင်းဖြစ်သည်-
> 
> "ကစားရန် ခလုတ်၏ ညာဘက်ရှိ "အမှားပြင်ဆင်မှု ထည့်ရန်" ကို ရွေးချယ်ခြင်းဖြင့် သင်၏ အမှားရှာပြင်ဆင်မှု ပုံစံကို စိတ်ကြိုက်ပြင်ဆင်နိုင်သည် (ဥပမာ- သင့်ပရိုဂရမ်သို့ အကြောင်းပြချက်များ ပေးပို့ရန်)၊ ပရောဂျက်၏ launch.json ဖိုင်တွင် စိတ်ကြိုက် အမှားရှာပြင်ဆင်ခြင်းကို သိမ်းဆည်းထားသည်။
> 
> သို့သော်၊ ဤအဆင့်တွင်၊ အသုံးပြုသူတစ်ဦးသည် cpp ဖိုင်ကို ဖိုင်တစ်ခုတည်းအဖြစ်သာ ဖွင့်ထားသည်။ အမှားရှာပြင်ဆင်မှုထည့်သွင်းရန် ဂီယာသင်္ကေတကို ဖိုင်တွဲတစ်ခုတွင် ၎င်းတို့၏ကုဒ်ကိုဖွင့်ထားမှသာ ရနိုင်သည်။ ဤအဆင့်တွင် သုံးစွဲသူများအား ၎င်းတို့၏ကုဒ်ကို ဖိုဒါတစ်ခုတွင် ဖွင့်ရန် လိုအပ်ကြောင်း ညွှန်ကြားရန် လိုအပ်သည်။
> 
> "Customize debugging" အဆင့်အတွက် စာသားအသစ် အဆိုပြုထားသည်-
> 
> "သင်၏ အမှားရှာပြင်ဆင်မှုကို စိတ်ကြိုက်ပြင်ဆင်ရန်၊ လုပ်ဆောင်ချက်ဘားရှိ Explorer ကို ရွေးပြီး သင်၏ C++ ဖိုင်ပါဝင်သော ဖိုင်တွဲကိုဖွင့်ပါ။ C++ ဖိုင်ကိုဖွင့်ပြီး ကစားခလုတ်၏ညာဘက်ရှိ "ဒက်ဂ်ပြင်ဆင်မှုထည့်ရန်" ကိုရွေးချယ်ပါ။ အမှားပြင်ဆင်မှုအသစ်ကို သိမ်းဆည်းထားသည်။ သင့်ပရောဂျက်၏ launch.json ဖိုင်သို့။"
