### ISSUE TITLE
 1.17.3 regression: IntelliSense crashes when certain error messages occur with any language pack

### ISSUE THREAD

**Issue by warzone-oier** [microsoft/vscode-cpptools#11336]
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.81.1
- C/C++ Extension Version: v1.17.3
- If using SSH remote, specify OS of remote machine: no SSH

### Bug Summary and Steps to Reproduce

Bug Summary:
IntelliSense has error between brackets like this below:
![a](https://github.com/microsoft/vscode-cpptools/assets/74630986/4cab2f10-bf1f-404b-805e-1c7ac66bf13b)
However, it didn't occur in v1.16.3:
 
![b](https://github.com/microsoft/vscode-cpptools/assets/74630986/41465333-cdad-481c-ae5a-990bb2d2fdfd)

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "D:/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
            "intelliSenseMode": "windows-msvc-x64"
        }
    ],
    "version": 4
}
```

**Comment by michelleangela** [comment]
@wangr-x 
I'm not able to reproduce the auto-complete behavior you're seeing in 1.17.3. Could you provide the following logs? Could you also check if other IntelliSense features are working, such as "Find All References"?

- Logs from running C/C++: Log Diagnostics from the VS Code command palette
- Enable Logs from the language server (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) and reload window and reproduce the issue.

**Comment by wangr-x** [comment]
@michelleangela 
I have found that the problem only occurs if the Chinese (Simplified) (简体中文) Language Pack is installed

**Comment by sean-mcmanus** [comment]
@wangr-x Thanks for reporting this -- we have a fix at https://github.com/microsoft/vscode-cpptools/pull/11339 for 1.17.4 on Monday. In the meanwhile, you can work around it downgrading to 1.16.3, disabling the language pack, or updating the file in your extension install corresponding to `<pathTo>/.vscode/extensions/ms-vscode.cpptools-1.17.3-<osInfo>/bin/messages/zh-cn/messages.json` with the contents at https://raw.githubusercontent.com/microsoft/vscode-cpptools/0ee2cd89f5e3de9a163f02a8713bbb7a7915c488/Extension/bin/messages/zh-cn/messages.json.

The issue should repro with any language pack, not just Chinese (Simplified).

We'll improve our internal update processes to prevent this type of issue in the future.

**Comment by sean-mcmanus** [comment]
@warzone-oier @TsXor Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.4

**Comment by LiRWZ** [comment]
version1.17.3 has been torturing me for two days。

**Comment by sean-mcmanus** [comment]
@bobbrow My impression was that @LiRWZ saw the previous "Fixed with" comment and was just expressing their feelings in regards to the past 2 days before the fix was released.
