### ISSUE TITLE
C code can not be parsed correctly by compile_commands.json

### ISSUE THREAD

**Issue by TegraFu** [microsoft/vscode-cpptools#11344]
Type: <b>Bug</b>

The compile_commands.json generated by CMake can not be parsed correctly when I upgrade C/C++ extension to v1.17.x. There are a lot of errors will be reported. But if I roll back to v1.16.x, everything is ok. Are there any other special settings should be configured for the newer version? My compile_commands.json file format is as below:
[{
"directory": "/mnt/work/project/camera/swallow/build/hi3516cv500/lib/lstlib",
"command": "/opt/hisi-linux/x86-arm/arm-himix200-linux/bin/arm-himix200-linux-gcc  -I/mnt/work/project/camera/swallow/include",
"file": "/mnt/work/project/camera/swallow/lib/lstlib/lstLib.c"
}]

Extension version: 1.16.3
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'ssh-remote+192.168.134.100' could not be established
Remote OS version: Linux x64 5.19.0-50-generic
Connection to 'ssh-remote+192.168.134.100' could not be established
Connection to 'ssh-remote+192.168.134.100' could not be established
Remote OS version: Linux x64 5.19.0-50-generic
Connection to 'ssh-remote+192.168.134.100' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (21.20GB free)|
|Process Argv|--crash-reporter-id c80a984a-a37a-465d-ad33-6b30fd2b6095|
|Screen Reader|no|
|VM|33%|

Connection to 'ssh-remote+192.168.134.100' could not be established

|Item|Value|
|---|---|
|Remote|SSH: 192.168.134.100|
|OS|Linux x64 5.19.0-50-generic|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (6 x 2687)|
|Memory (System)|15.61GB (8.61GB free)|
|VM|100%|

Connection to 'ssh-remote+192.168.134.100' could not be established

Connection to 'ssh-remote+192.168.134.100' could not be established

|Item|Value|
|---|---|
|Remote|SSH: 192.168.134.100|
|OS|Linux x64 5.19.0-50-generic|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (6 x 2687)|
|Memory (System)|15.61GB (8.61GB free)|
|VM|100%|

Connection to 'ssh-remote+192.168.134.100' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by Colengms** [comment]
Hi @tenggui .  Can you provide additional information?  Is there something specific (such as in a log) that suggests this is directly related to your compile_commands.json?

Could you try running the `C/C++: Log Diagnostics` command using both 1.17.x and 1.16.x.  Differences in what that reports might point to an issue, if related to IntelliSense configuration.  It's also possible there were recent regressions in the IntelliSense engine, causing code that used to be parsed properly to no longer be parsed properly, resulting in unexpected squiggles.  Could you provide some details about the squiggles that are reported with 1.17.x?  If possible, can you isolate one of those issues into a simple example that you can share with us in the form of a zip file or github repo?  That could be particularly useful for investigating the issue and validating a fix.

**Comment by rubiot** [comment]
It looks like this is the same problem reported in #11326.

**Comment by sean-mcmanus** [comment]
@rubiot Why do you think this issue is related to https://github.com/microsoft/vscode-cpptools/issues/11326 ?

**Comment by Colengms** [comment]
Hi @tenggui .  I don't believe we have enough information here yet to be of assistance.  As mentioned in my previous comment, could you provide the following information here?

> a lot of errors will be reported

Could you provide a list of these errors?  Your initial posting referred to errors related to `ssh-remote`, which are unrelated to the C/C++ Extension.  Are those the only errors you are seeing?  Or, are you referring to IntelliSense errors, or errors specifically referring to parsing a `compile_commands.json` file?  Could you please post those errors to this thread?

Could you try running the `C/C++: Log Diagnostics` command using both 1.17.x and 1.16.x and report them both here?  If there is an issue with IntelliSense being configured differently between versions, that should provide us with those differences.

If the issue you're seeing is actually that IntelliSense squiggles are being displayed where not expected, could you provide details about those squiggles?  Could you isolate one of those issues into a simple example that you can share with us in the form of a zip file or a github repo? That would be particularly useful for us to investigate the issue and validating a fix.

**Comment by tenggui** [comment]
For the attached socket project, the issue can be reproduced above C/C++ 1.17.x.  When open the project, the output window will show the following errors. Maybe the IntelliSenseMode and compilerPath were detected incorrectly.
`[11/12/2023, 5:14:25 PM] For C++ source files, IntelliSenseMode was changed from "linux-gcc-x64" to "linux-clang-x64" based on compiler args and querying compilerPath: "/usr/bin/clang"
[11/12/2023, 5:14:25 PM] IntelliSenseMode was changed because it didn't match the detected compiler.  Consider setting "compilerPath" instead.  Set "compilerPath" to "" to disable detection of system includes and defines.
[11/12/2023, 5:14:25 PM] For C source files, IntelliSenseMode was changed from "linux-gcc-x64" to "linux-clang-x64" based on compiler args and querying compilerPath: "/usr/bin/clang"
[11/12/2023, 5:14:25 PM] IntelliSenseMode was changed because it didn't match the detected compiler.  Consider setting "compilerPath" instead.  Set "compilerPath" to "" to disable detection of system includes and defines.`

[socket_project.tar.gz](https://github.com/microsoft/vscode-cpptools/files/13327615/socket_project.tar.gz)
