### ISSUE TITLE
Cant find the "xxxx.h", "Go to define" and somefunction is useless.

### ISSUE THREAD

**Issue by JcobCN** [microsoft/vscode-cpptools#1134]
It is possible my opening folder have too many files , but it works well in cpptools version: 0.13.0.

**Comment by JcobCN** [comment]
* Operating System and version: windows7 x64
    * VS Code version: 1.17.0 & 1.17.1 x64
    * C/C++ extension version: 0.13.1

**Comment by JcobCN** [comment]
![image](https://user-images.githubusercontent.com/19268110/31591587-a35aa0e0-b253-11e7-806c-0e981a371809.png)
# cpp json
```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}",
                "e:/project/trunk_8.1/include/",
                "D:/msys64/mingw32/include",
                "D:/msys64/mingw32/include/c++/7.1.0/tr1",
                "D:/msys64/mingw32/include/c++/7.1.0",
                "${workspaceRoot}/include/mpp_include_3531A"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "e:/project/trunk_8.1/include",
                    "D:/msys64/mingw32/include"
                ],
                "limitSymbolsToIncludedHeaders": false,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```
# setting json
```json
{
  "files.encoding": "gbk",
    "C_Cpp.errorSquiggles": "Enabled",
    "C_Cpp.autocomplete": "Disabled",
    "C_Cpp.intelliSenseEngine": "Tag Parser",
    "clang.completion.enable": true,
    "clang.cflags": [
        "-IE:/project/trunk_8.1/include/",
       "-IE:/project/trunk_8.1/include/mpp_include_3531",
    //    , "-IE:/project/trunk_8.1/project/a4sComponent/ftpc/",
    //    ,
        "-D __3536__"/* , "-I${workspaceRoot}/include", "-I${cwd}" */]
}
```

**Comment by taianwxh** [comment]
I meet the same problem, so back to 0.13.0 version.

**Comment by bobbrow** [comment]
@JiangCN, it looks like you have the "clang" extension installed.  Does the problem still happen when you disable that extension?  Also, we released an update (0.14.0), so please let us know if you continue to see the problem with 0.14.0.

Thanks!

**Comment by JcobCN** [comment]
@bobbrow  thanks!
![image](https://user-images.githubusercontent.com/19268110/31801531-6e005d4c-b57b-11e7-87d8-f0644b7e8950.png)

It dose happen in version 0.14.0, and i disable "clang" extension.

**Comment by sean-mcmanus** [comment]
When you hover over the database icon in the bottom right, what does it say? Can you change your C_Cpp.loggingLevel to Warning or Information and see the C/C++ output window for why language.h is not being added to the file database?

**Comment by JcobCN** [comment]
@sean-mcmanus 
When database have parsed, the icon disappeared.
I changed C_Cpp.loggingLevel to Warning, and nothing output. 
I find cpp_error_sugguestion did not work in many old version with this project, but work well in other project with few files almost 5.

**Comment by JcobCN** [comment]
@sean-mcmanus 
It did not work in the lastest version 0.14.5, some function can not go to define.
Mouse hover the function, it tell me can not find defination.
But in version 0.13.0 it works well.
Please sloved this problem.

**Comment by JcobCN** [comment]
@sean-mcmanus 
The same happen in Manjaro 64bit.(cpptools version 0.14.0).
I install back 0.13.0, it works well.

**Comment by sean-mcmanus** [comment]
We don't know what change could have broken this. We need to find a repro. Are you able to provide a simple repro? We've found/fixed a performance regression that was introduced in 0.13.1 for our next update, but I don't think it would cause any functionality change. You can set your loggingLevel to a higher value like (6) to see more processing info, but be sure to get rid of that afterwards because it slows stuff down a lot.

**Comment by JcobCN** [comment]
@sean-mcmanus It work well in 0.14.6.
Thank you for your effort.

**Comment by sean-mcmanus** [comment]
Yeah, we had an unfortunate regression in 0.13.1, but we didn't realize it was a wide spread issue until we debugged a specific repro case (`\\u` usage) from another user's report ( https://github.com/Microsoft/vscode-cpptools/issues/1197 ).
