### ISSUE TITLE
Outline not updating whatever I do, shows definitions from a long time ago

### ISSUE THREAD

**Issue by marralesfios** [microsoft/vscode-cpptools#11341]
### Environment

- OS and Version: Windows 10 22H2
- VS Code Version: 1.82.0-insider (user setup)
Commit: 501baeb5e07b5a404f862d922bacb93771d91331
Date: 2023-08-18T05:32:38.035Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

- C/C++ Extension Version: v1.17.3
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
Hard to consistently reproduce(only shows after extensive editing): see screenshot

Expected behavior:
Outline, breadcrumbs and "No function definition" error be updated

### Configuration and Logs

```json
{
  "configurations": [
    {
      "name": "windows-gcc-x64",
      "includePath": [
        "E:\\",
        "E:\\include"
      ],
      "compilerPath": "D:\\msys64\\mingw64\\bin\\g++.exe",
      "cStandard": "${default}",
      "cppStandard": "c++23",
      "intelliSenseMode": "windows-gcc-x64",
      "compilerArgs": [
        "-fno-ms-extensions"
      ]
    }
  ],
  "version": 4
}
```
, Log diagnostics:
```
-------- Diagnostics - 8/19/2023, 9:52:23 AM
Version: 1.17.3
Current Configuration:
{
    "name": "windows-gcc-x64",
    "includePath": [
        "E:\\",
        "E:/include"
    ],
    "compilerPath": "D:\\msys64\\mingw64\\bin\\g++.exe",
    "cStandard": "c23",
    "cppStandard": "c++23",
    "intelliSenseMode": "windows-gcc-x64",
    "compilerArgs": [
        "-fno-ms-extensions"
    ],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "D:\\msys64\\mingw64\\bin\\g++.exe",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "E:\\",
            "E:/include",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.17.2.0
Translation Unit Mappings:
[ E:\Scrypt\test.cpp ]:
    E:\Scrypt\test.cpp
    E:\Scrypt\lib\obj.hpp *
    E:\Scrypt\lib\parse.hpp *
    E:\Scrypt\scrypt.hpp *
Translation Unit Configurations:
[ E:\Scrypt\test.cpp ]:
    Process ID: 681156
    Memory Usage: 299 MB
    Compiler Path: D:\msys64\mingw64\bin\g++.exe
    Includes:
        E:
        E:\include
        D:\msys64\mingw64\include\c++\13.2.0
        D:\msys64\mingw64\include\c++\13.2.0\x86_64-w64-mingw32
        D:\msys64\mingw64\include\c++\13.2.0\backward
        D:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\13.2.0\include
        D:\msys64\mingw64\include
        D:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\13.2.0\include-fixed
    Standard Version: c++23
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=130200
        --no_ms_extensions
Total Memory Usage: 299 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3692
```
[lang_svlog.txt](https://github.com/microsoft/vscode-cpptools/files/12384762/lang_svlog.txt)

### Other Extensions

None interfering

### Additional context

![image](https://github.com/microsoft/vscode-cpptools/assets/50442757/3b28bbb5-0b17-4e1c-aa04-a21c9c718555)
![image](https://github.com/microsoft/vscode-cpptools/assets/50442757/e98738a8-9f9b-43bb-84b3-501b0ee31ff1)

**Comment by Colengms** [comment]
Hi @00001H .  Could you enable debug logging by setting `"C_Cpp.loggingLevel": "Debug"`?  That should result in log output to the C/C++ output channel, as the extension runs.

What you're seeing sounds like a case of IntelliSense not updating quickly enough, resulting in old information in the Outline.

One detail that stands out from your information is that you've specified an include path that points to the root of a volume:

```
      "includePath": [
        "E:\\",
```

I suspect that is resulting in the entire E drive being indexed as source code.  If that is a large volume, that could lead to some significant performance issues.  Assuming this is not a volume dedicated specifically to this one project, you might try isolating your project under a single folder.

Otherwise, you might try monitoring the debug output to see what it's doing at the point the issue repro's, in case that indicates it's stuck doing something in particular, or has indicated some error.

**Comment by 00001H** [comment]
@Colengms Ah, I see. I'm not currently on my computer right now, but I'll give an update once I tested it. The E drive contains quite some code(about twenty thousand lines last time I checked), so maybe that was the issue.
