### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ahmedtareksohsah** [microsoft/vscode-cpptools#11343]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `1.8.4`
- OS Version: `Windows_NT ia32 6.1.7600`
- VS Code version: `1.70.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bobbrow** [comment]
Hi @ahmedtareksohsah, please paste the information from VS Code into the issue and we can take a look. We'll close this issue until then.
