### ISSUE TITLE
/Zc:alignedNew- compiler option results in an intellisense command line error: "invalid option: --no_overaligned_allocation

### ISSUE THREAD

**Issue by neerajsi-msft** [microsoft/vscode-cpptools#11350]
### Environment

- OS and Version: Windows 23532.1001.amd64fre.ni_moment_liof.230819-1700
- VS Code Version: 1.81.1
- C/C++ Extension Version: v1.17.4

### Bug Summary and Steps to Reproduce

Bug Summary:
/Zc:alignedNew- is not being translated correctly for the intellisense frontend. We're getting a command line error.

Steps to reproduce:

1. I created a simple hello-world console application in VS2022.
2. I opened the folder in VSCode with the C++ extension
3. In the C++ extension settings I adjusted the arguments setting:
"C_Cpp.default.compilerArgs": [
  "/Zc:alignedNew-"
]
4. Observe this in the "Problems" pane reported by the C++ extension:
command-line error: invalid option: --no_overaligned_allocation

This is mimicking an error I am seeing in the Windows Razzle build environment for some projects that pass the /Zc:alignedNew- flag.

Expected behavior:
Intellisense should be able to parse my file successfully even if I pass "/Zc:alignedNew-".

### Configuration and Logs

```shell
"C_Cpp.default.compilerArgs": [
  "/Zc:alignedNew-"
]
```

**Comment by sean-mcmanus** [comment]
@neerajsi-msft Downgrading to 1.16.3 is the recommended workaround until we can get a fix into 1.17.5.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.5 .
