### ISSUE TITLE
Extension API for requesting information about the code

### ISSUE THREAD

**Issue by rowanG077** [microsoft/vscode-cpptools#1136]
Hello everyone,

I am working on a code plugin and I need to parse C++ function declarations. After a couple of hours of working at it myself I noticed how bad of an idea this was. I have searched online and I can't find any information on this. But what I would like to ask this existing language server for information about my function declaration. Parameters, return types. Is it templated etc.

Is this possible or not?

**Comment by bobbrow** [comment]
Unfortunately, this is not possible to do with our extension and we don't have any plans at this time to expose this information in an API for other extensions to consume.
