### ISSUE TITLE
Error while debugging: ERROR: GDB exited unexpectedly. Debugging will now abort.

### ISSUE THREAD

**Issue by Ethereal-Echoes** [microsoft/vscode-cpptools#11360]
### Environment

- OS and version: Microsoft Windows [Version 10.0.22621.2134]
- VS Code: VS Code 1.81.1
- C/C++ extension: v1.17.4
- OS and version of remote machine (if applicable):
- GDB / LLDB version: v8.1

### Bug Summary and Steps to Reproduce

Bug Summary:
When I try to use the monitor function in running and debugging to monitor an expression (this is the first time I use this function, I monitor the value of a pointer variable i, I fill in the expression: *i) and then the program Exit automatically and prompt ERROR: GDB exited unexpectedly. Debugging will now abort.

Steps to reproduce:

### Debugger Configurations

```shell
tasks.json:
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "使用C++14/GCC9生成",
            "command": "F:\\VS Code\\mingw64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "调试器生成的任务。"
        }
    ],
    "version": "2.0.0"
}
launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "使用C++14/GCC9进行调试",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "F:\\VS Code\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "将反汇编风格设置为 Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "使用C++14/GCC9生成"
        },
        {
            "name": "(Windows) 启动",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "输入程序名称，例如 ${workspaceFolder}/a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "externalTerminal"
        }
    ]
}
```

### Debugger Logs

```shell
The Output window doesn't appear to output anything
The "Debug Console Window" does not seem to output detailed information about the error. The following is all the information output by the "Modulation Console" window:

Loaded 'C:\WINDOWS\System32\gdi32full.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\System32\msvcp_win.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\System32\ucrtbase.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\System32\imm32.dll'. Symbols loaded.

Thread 1 hit Breakpoint 2, main () at F:\C++\luogu\P1059.cpp:15
15 for (auto j = list.begin(); (*j<*i); j++){
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
ERROR: GDB exited unexpectedly. Debugging will now abort.
The program 'F:\C++\luogu\P1059.exe' has exited with code -1 (0xffffffff).
```

### Other Extensions

Uninstalled all extensions (except those necessary for debugging), the error still occurs

### Additional Information

This is my first time asking an issue on GitHub, so there may be some deficiencies, please let me know if I'm missing any information, thanks.

**Comment by lzy20110519** [comment]
To add some info, this is the code I debugged:
`#include <bits/stdc++.h>

using namespace std;

int main(){
    list<int> list;
    int num,numx,if_remove = 1;
    cin >> num;
    for(int i = 0; i < num; i++){
        cin >> numx;
        list.push_back(numx);
    }
    list.sort();
    for(auto i = list.begin(); i != list.end(); i++){
        for (auto j = list.begin(); (*j<*i); j++){
            if(*i == *j){
                if_remove = 0;
            }
        }
        if(if_remove){
            cout << *i << " ";
        }
        if_remove = 1;
    }
    return 0;
}`

**Comment by lzy20110519** [comment]
To add some info, this is the code I debugged：
#include <bits/stdc++.h>

using namespace std;

int main(){
    list<int> list;
    int num,numx,if_remove = 1;
    cin >> num;
    for(int i = 0; i < num; i++){
        cin >> numx;
        list.push_back(numx);
    }
    list.sort();
    for(auto i = list.begin(); i != list.end(); i++){
        for (auto j = list.begin(); (*j<*i); j++){
            if(*i == *j){
                if_remove = 0;
            }
        }
        if(if_remove){
            cout << *i << " ";
        }
        if_remove = 1;
    }
    return 0;
}

**Comment by WardenGnaw** [comment]
In your launch.json, could you add the following and share the logs in the Debug Console?
```json
"logging": {
   "engineLogging": true,
   "trace": true,
   "traceResponse": true
}
```
