### ISSUE TITLE
Intellisense parser never finishes initializing

### ISSUE THREAD

**Issue by knetworx** [microsoft/vscode-cpptools#11361]
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.18.1
- C/C++ Extension Version: 1.17.4
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

When I attempt to use VSCode with cpptools for my UE5 (Unreal Engine 5) project, I get no Intellisense information, and the database icon in the bottom right corner just says "Initializing..." when I mouse over it. Attempting to auto-complete using Ctrl+Space or mousing over any item in the editor just shows "Loading..." and never retrieves any information. Clicking on "Rescan Workspace" does nothing.

![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/aafca3d1-7fbe-49d0-b9d1-40d063ec4004)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/e08360a4-f603-4668-a536-df765bbef3fd)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/6ce9b9e7-7d49-4c71-8b52-eb1e7ba6eb2a)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/84949978-97eb-4269-ae44-71fe4ec85855)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/54f80d51-b005-427b-ba78-d422d12a539e)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/f6c7fcc0-1955-4edd-be25-c676d7fa2c08)

Expected behavior:
Parsing completes, auto-completion is shown.
Notable: This issue occurs on my work computer. On my personal computer, I have a different UE5 project open in VSCode, and Intellisense is working correctly there. All my VSCode settings and plugins are automatically synced between the two. My work computer has VS2022 Professional and Windows 10. My personal computer has VS2022 Community and Windows 11. It may be a factor of the project setup, the OS, or (what I suspect) something corrupt in my local environment.

### Configuration and Logs

c_cpp_properties.json was generated by Unreal's automated tools, but contains a bunch of configurations. This is the one I'm using (edited for NDA reasons):
```
    "configurations": [
        {
            "name": "<project>Editor Editor Win64 Development (<project>)",
            "compilerPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64",
            "configurationProvider": "epic.ue",
            "compileCommands": "C:\\<project>\\<projectsub>\\Unreal\\.vscode\\compileCommands_<project>.json"
        },
```

Attempting to run C/C++: Log Diagnostics appears to do nothing (unless it's printing info to a log somewhere that I can't see).

With logging level set to Debug, this is everything that shows up:
```
loggingLevel: Debug
cpptools version (TypeScript): 1.17.4
cpptools version (native): 1.17.2.0
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = tag parser.
LSP: cpptools/didChangeCppProperties (id: 1)
LSP: cpptools/queryCompilerDefaults (id: 2)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe'
Attempting to get defaults from C compiler in "compilerPath" property: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe'
LSP: Message ignored due to no registered handler: $/setTrace
LSP: Message ignored due to no registered handler: $/setTrace
```

### Other Extensions

I have a fair number of extensions, but as mentioned before, they're synced to my other computer, and intellisense is working correctly there. I have a feeling the issue I'm having is related either to the layout and/or size of the project on my work computer, or something corrupt on that machine which needs to be reset.

### Additional context

I have tried uninstalling and reinstalling the extension, including deleting the folder in C:\\Users\\&lt;myname&gt;\\.vscode\\extensions
I've also tried adding things to C_Cpp.files.exclude, manually setting C_Cpp.default.compilerPath, manually adding the folders to the includePath in c_cpp_properties.json, and messing around with the various settings to no avail. I've tried all the suggestions I've found online and in other issues posted for this extension. I'm sure it's going to be something simple, but I can't seem to figure it out.

**Comment by knetworx** [comment]
Here is Intellisense running in VSCode with all the same extensions on my personal computer on another UE5 project:

![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/a223482b-3a52-4700-91d9-45b3ed8cf14a)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/e0ff0e9f-51d9-4074-b30c-443a6a4562b1)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/71952d28-dcbd-4a6d-8eba-193351d48dc8)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/8ba3898c-f3a8-43f8-9950-cdaabc815f5f)

**Comment by knetworx** [comment]
Alright, time for the facepalm. As embarrassing as it is, I'm going to leave this here in case someone else runs into the same issue. The solution was indeed a difference between the project layouts, as suspected. I had looked over the workspace settings before, but since they looked the same and there wasn't much in either of them, I didn't think much of it. The difference was in the "folders" property of the Project.code-workspace file.

Here was the one for my personal project:
```
	"folders": [
		{
			"name": "FirstPersonProject",
			"path": "."
		},
		{
			"name": "UE5",
			"path": "C:\\Program Files\\Epic Games\\UE_5.1"
		}
	],
```
And here was the setting for my work project:
```
	"folders": [
		{
			"name": "ProjectName",
			"path": "."
		}
	],
```
However, the base of my work project is a stream that contains the project folder and Unreal Engine embedded in another folder. So I needed to update the folders to look like this:
```
	"folders": [
		{
			"name": "ProjectName",
			"path": "ProjectName"
		},
		{
			"name": "UE5",
			"path": "Engine"
		}
	],
```
And now my workspace is parsing, and I'm starting to see the Intellisense data.

**Comment by knetworx** [comment]
Never mind. The workspace change fixed the parser, but now it doesn't see my launch.json, so I can't build the game. I tried adding the .vscode folder directly like this:
```
		{
			"name": "ProjectName",
			"path": "ProjectName"
		},
```
And while it shows up as expected in the project explorer, the run/debug tab still doesn't recognize the existence of launch.json.

**Comment by knetworx** [comment]
I've now changed back to setting the path to be the current directory, and explicitly excluding everything but .vscode, my project folder, and the engine folder. I can build and run the game again, but Intellisense is back to being locked at initializing. I don't know if it's choking on the extensive list of compile commands files in the .vscode folder, or if it's looking for something that it can only find when I explicitly list my project folder in the workspace.

**Comment by Colengms** [comment]
Hi @knetworx .  The C/++ Extension (and VS Code itself) looks for the `.vscode` folder immediately under the 'workspace folder'.  When you changed that workspace folder path, I'm assuming you did not relocate the `.vscode` folder?  If so, in which scenario was the `.vscode` folder in the expected location?  Hopefully things work properly when the `.vscode` folder is in the expected location.  Otherwise, the issue would seem related to configuration information in that folder.  Can you confirm?

**Comment by knetworx** [comment]
I didn't move the .vscode folder. And I'm not sure if I can - the compile commands, launch.json, c_cpp_properties.json, etc are all generated by automated scripts that I don't have control over. I could maybe try moving it and making a symlink from its previous location, but I'm not sure what other repercussions that might have. I can try it out and see what happens when I regenerate the project.

When you say it looks for the .vscode folder directly under the 'workspace folder', is the 'workspace folder' in this case the location of the .code-workspace file, or is it the first folder listed within the .code-workspace file?

**Comment by knetworx** [comment]
Ok, so I went the other way instead - I figured if I made a symlink in the top-level folder, it might get deleted and recreated by the automated scripts, so instead I made a symlink in my project folder that pointed to the one at the top level, and....it seems to have worked. The Run/Debug sidebar shows the correct build options, and while Intellisense still seems to be parsing, I *am* starting to see auto-complete suggestions when I type.
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/c4addc6c-9f3b-4aea-ac1a-527a5dd17427)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/a0f9c926-3c7c-4337-a091-e149e15fab9d)
![image](https://github.com/microsoft/vscode-cpptools/assets/3292803/33eb1bed-a0c1-4594-aa6e-29c428e20597)

**Comment by Colengms** [comment]
> When you say it looks for the .vscode folder directly under the 'workspace folder', is the 'workspace folder' in this case the location of the .code-workspace file.

By 'workspace folder', I meant the individual folder within the workspace, not the location of the workspace file.

> Ok, so I went the other way instead - I figured if I made a symlink in the top-level folder, it might get deleted and recreated by the automated scripts, so instead I made a symlink in my project folder that pointed to the one at the top level

I'm not entirely sure I follow your comments here. Can you show a brief diagram of the location of the .vscode folder/link(?), before and after.  It's unclear to me why it would be necessary to point the workspace to a folder one level below and relocate/link the `.vscode` folder there.  I would assume, since any relative paths (or paths that refer to `${workspaceFolder}`) in `.vscode` should be relative to the 'workspace folder', which has changed, those paths would no longer be correct.  Perhaps the Unreal Engine editor is generating your workspace file incorrectly?

> I am starting to see auto-complete suggestions when I type.

Great!  I'm not sure if we've fully addressed your issue.  But, if so, feel free to close it.  :)

**Comment by knetworx** [comment]
Here's the gist of the layout.

Before:
```
BaseFolder
|- .vscode
|- Project
   |- Source
|- Engine
|- Project.code-workspace
```

After:
```
BaseFolder
|- .vscode
|- Project
   |- .vscode -> BaseFolder/.vscode
   |- Source
|- Engine
|- Project.code-workspace
```

On my personal computer, the layout is a bit simpler:
```
Project
|- .vscode
|- Source
|- Project.code-workspace

C:\Program Files\....\UE_5.2 ("Engine" - referenced by multi-root workspace)
```

On my personal machine, the project folder *is* the base folder, and the engine code is in ProgramFiles and referenced as a second folder by Project.code-workspace.
On my work machine, the project folder is *within* the base folder, and the engine code is in another folder, also within the base folder. I agree, doing the symlink seems like it should be unnecessary and possibly even bad, but it does seem to work. I think the issue is that I can't specify where it should look for .vscode and/or c_cpp_properties.json, and because of the non-standard layout of my work project, the intellisense parser is looking in one place, and the run/debug panel is looking in another place, so my (ugly, but functional) workaround is to simply have it in both places (or at least, have a symlink to it in the second location).
