### ISSUE TITLE
Indentation missing in Markdown fenced code blocks

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#11379]
Awesome, thanks! However, the indentation in fenced code blocks still doesn't show correctly. My apologies, this is totally my fault - the code I put in my original comment isn't the right code. It doesn't match the screenshot and doesn't properly demonstrate the issue. I fixed it now. 

In 1.17.5 the first problem I mentioned (some characters are rendered with a redundant escape character) is fixed, but the fenced code blocks are still not correctly indented - see screenshot:

![image](https://github.com/microsoft/vscode-cpptools/assets/61846320/8e0a7af6-07c9-43fe-b11c-c72b74306b28)

The `for` loop should be indented for readability, but it is not. Would it be possible to fix this? Thanks again.

_Originally posted by @bshoshany in https://github.com/microsoft/vscode-cpptools/issues/11322#issuecomment-1696547379_

**Comment by bshoshany** [comment]
Hi, I just noticed that for some reason the source code in issue #11322 still doesn't match the screenshot, even though I'm 100% sure I fixed it already. Here is the correct code:

```cpp
#include <iostream>
#include <vector>

// This function returns an `std::vector<size_t>` with `n` elements initialized to consecutive values.
//
// Usage example:
// ```
//     std::vector<size_t> vec = test(32);
//     for (const size_t k : vec)
//         std::cout << k << ' ';
// ```
std::vector<size_t> test(const size_t n)
{
    std::vector<size_t> temp(32);
    for (size_t i = 0; i < n; ++i)
        temp[i] = i;
    return temp;
}

int main()
{
    std::vector<size_t> vec = test(32);
    for (const size_t k : vec)
        std::cout << k << ' ';
}
```

Thanks again for your efforts to fix this issue! Currently in pre-release version 1.18.0 it is still not fixed - hoping to see it in the release version!

**Comment by sean-mcmanus** [comment]
@bshoshany Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.0 (pre-release)

**Comment by bshoshany** [comment]
Thanks so much! I can confirm that with v1.19.0 I do not encounter this error any more.
