### ISSUE TITLE
Unable to start debugging. GDB exited unexpectedly.

### ISSUE THREAD

**Issue by gotothemars** [microsoft/vscode-cpptools#11374]
**Brief Issue Summary:**
Hi everyone, 

I just set up xmake project with a very simple code just cout "Hello world" in one single file.The program runs and compiles as expected. However, when I want to debug it with F5, it crashes with the message: "The program '/home/hello_xmake/build/linux/x86_64/debug/hello_xmake' has exited with code 0 (0x00000000)." and with the assert box "Unable to start debugging. GDB exited unexpectedly." The bin itself has no problem, because I can use gdb directly to set breakpoint and exec gdb command.
My launch.json is
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/hello_xmake/build/linux/x86_64/debug/hello_xmake",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

I'm thankfull for any help I can get on this.
Best Regards

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
