### ISSUE TITLE
Replace "Fix this clang-diagnostic-error problem" code action text with "Fix 'use of undeclared identifier 'X'; did you mean 'X2'?"

### ISSUE THREAD

**Issue by skewballfox** [microsoft/vscode-cpptools#11387]
### Feature Request

Not sure if this is a bug report, a feature request, or user error. 

Occasionally I'll be provided with lint that has a suggestion as to what to change. take the example below:
```
class "cse4733::Process" has no member "setCompletionTime"C/C++(135)
no member named 'setCompletionTime' in 'cse4733::Process'; 

did you mean 'set_completion_time'? C/C++(clang-diagnostic-error)
```
if you activate quick fix to see the suggested code actions, you won't have the option to implement that suggestion, only to disable the lint. If the lint provides a suggested fix, the language server should provide a code action.

If this is already possible, what do I need to change in my configuration?  this is currently the extension related content in my `settings.json`
```
"C_Cpp.codeAnalysis.clangTidy.enabled": true,
    "C_Cpp.default.cStandard": "gnu17",
    "C_Cpp.default.intelliSenseMode": "linux-gcc-x64",
    "C_Cpp.experimentalFeatures": "enabled",
    "C_Cpp.formatting": "vcFormat",
    "C_Cpp.intelliSenseEngineFallback": "enabled",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.block": "sameLine",
    "C_Cpp.vcFormat.newLine.beforeOpenBrace.function": "newLine",
    "C_Cpp.vcFormat.newLine.closeBraceSameLine.emptyFunction": true,
    "C_Cpp.autocompleteAddParentheses": true,
    "C_Cpp.clang_format_sortIncludes": true,
    "C_Cpp.default.cppStandard": "c++20",
```

**Comment by sean-mcmanus** [comment]
We do support clang-tidy code action fixes. It works for me in a simple case. See the screenshot:

<img width="245" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/81141121-3414-43df-9b27-4731a01f5576">

Can you provide a repro case? There might be a bug in our handling of the case that is causing the code action fix to not be correctly generated.

**Comment by skewballfox** [comment]
During the process to reproduce this I realized that first message was a fix, so  user error. It does seem as though the message attached is easily confused for the rest. Would it be a good idea to simply pass the hint as the text for the quick fix?

for reference, this is the quick fix text for a similar issue from rust-analyzer:
![image](https://github.com/microsoft/vscode-cpptools/assets/29311431/122bdb4f-7c5f-489f-980b-1d0a13a6fe4b)

I can change the title of the feature request if this warrants a feature request, otherwise I can go ahead and close the issue

**Comment by sean-mcmanus** [comment]
Yeah, the current clang-tidy quick fix support is "generic" and meant to work on all the checks the same way, i.e. "Fix this <clang-type problem type>`, but it sounds like you're suggesting adding a special case for this case to show the message in the code action instead of just the "clang-diagnostic-error" type. I think that seems do-able.

But FYI, the hint text is also shown in the problems window, which code actions can also be invoked from:

<img width="504" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/0920fd5e-921e-4e1f-8206-10ba1cefab21">
