### ISSUE TITLE
[Debug] Running Win32 from status bar (>) does not show the app window...

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cpptools#11399]
Type: <b>Bug</b>

I have a strange situation: A minimal app with `main()`, which displays a standard Win32 window.
- If I execute the app by double clicking on the executable from the Windows shell, the app windows is displayed.
- If I execute the app by clicking on (de)Bug button on the status bar the app window appears (without any console attached).
- If I execute the app by clicking on the Run button the app runs until the Win32 window is created and then I can see it in the Task Manager as a subprocess of PowerShell but the app window does not appera and the app is stuck.

Any ideas what's going on?

I cannot use Visual Studio itself with my project as it needs CMake 2.37. I may try a simplified version later.

Extension version: 1.17.5
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.65GB (1.54GB free)|
|Process Argv|--crash-reporter-id c7a16f6b-33fc-42c2-aedd-68d1d1ff8687|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
0bi6i642:30823812
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by Zingam** [comment]
It looks like it's an issue with PowerShell. The app won't show the window when run from PowerShell. Is there a workaround this? Can apps be executed without wrapped in PowerShell or anything else?

**Comment by sean-mcmanus** [comment]
I don't know. Is this related to our debugger or VS Code itself or some other extension. I'm not sure what "bug" button in the status bar you're referring to (out extension doesn't add that).
