### ISSUE TITLE
Losing case sensitive path causes problem on Linux

### ISSUE THREAD

**Issue by b3sigma** [microsoft/vscode-cpptools#114]
Only reproduced when the vscpp extension is installed.

Repro: Linux Mint 17.3
- Open a folder with c source with a mixed case path like /home/user/Document/thing/
- Go to definition at least twice in a way that goes to two different files using a keyboard shortcut
  *\* Ex: start in main.c, then go to def of function in other.c, then go to def of function in third.c
- Use the keyboard shortcut for going back (ctrl+alt+- on my system) twice
  Result: Error message saying /home/user/document/thing/other.c not found
  Note the different case of "Document" vs "document"

**Comment by jgoshi** [comment]
This works for me with the latest. Does it still repro for you?

**Comment by b3sigma** [comment]
Nope, looks like it's fixed. Thanks!

**Comment by b3sigma** [comment]
Sorry, it looks like maybe the repro is just more finicky than I thought? Anyway, it's still happening. Here's some additional info: 
- I have this setting different than default which might be relevant:
  // Controls if opened editors show as preview. Preview editors are reused until they are kept (e.g. via double click or editing).
  "workbench.editor.enablePreview": false,

Repro steps this time included:
- Open a folder with cpp source with a mixed case path like /home/user/Documents/thing/, verify no files are already open
- We are going to need a function which has a similar function signature in multiple different files, all of which are in the folder or subdirectories
- Open just one of the files with that definition
- Use the go to definition shortcut from within that file, select one of the other files
- Do the same thing on the new file for the same function, go to a third file
- Now go back to the first file, use go to definition, notice it includes the file you are actually in, select that with the mouse
- Notice that you now have two of the files apparently open (we will denote these the 1st and 4th files opened)
- Click on the 2nd file tab
- Now close the 4th file tab (the duplicated file)
- Notice you are back to three tabs, with the three distinct files
- Now use the back shortcut a few times
- Result: Error message saying /home/user/documents/thing/firstfile.c not found 
- Note the different case of "Document" vs "document"

**Comment by jgoshi** [comment]
I'm sorry, I'm still not able to repro this. I might not be setting the files up (or the settings file) properly. Can you attach your sample (including your settings file)?

**Comment by jgoshi** [comment]
I was able to repro and this has been fixed. It will appear in the next release of cpptools (version 0.9.0).
