### ISSUE TITLE
The Language Server Crashed

### ISSUE THREAD

**Issue by MArKy1998** [microsoft/vscode-cpptools#11409]
Type: <b>Bug</b>

The Language Server crashed 5 times in the last 3 minutes.
I can not use this extension

Extension version: 1.17.5
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.83GB free)|
|Process Argv|--crash-reporter-id 3bf35534-04c6-466f-a527-642cbd1261c5|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

```[tasklist]
### Tasks
```

**Comment by browntarik** [comment]
I am sorry that you are having this experience! It would be valuable to us to have you help to fix this issue for you and future users. 

Could you please provide more information about when you experienced the crash? Are there certain actions that we can do to reproduce the crash?

**Comment by hmolds** [comment]
I have the same issue. 

It crashes during starting of the language server and/or when using go to definition/declaration. 
I've not been able to reproduce the error consistently, as the error only sometimes crashes during starting of the language server, or when using "go to definition/declaration".

Is there any information I can provide to assist?

Extension version: 1.17.5,
VS Code version: 1.18.1

OS: Windows 10 Enterprise, version 10.0.19045

**Comment by FangLin2001** [comment]
@browntarik Perhaps my comment could be of assistance.
https://github.com/microsoft/vscode-cpptools/issues/11401#issuecomment-1711027404

**Comment by hmolds** [comment]
@browntarik Apologies for the late answer. There seems to have been user error on our teams end. 
In our `c_cpp_properties.json` we both set `configurationProvider` and other stuff like `cppStandards` & `cStandards`. 

Changing to this solved our issues.
```
"configurations": [
    {
        "name": "CMake-Tools",
        "configurationProvider": "ms-vscode.cmake-tools"
    }
],
```
