### ISSUE TITLE
Does this vscode-cpptools extension support debugging  embedded(risc-v MCU)  program officially? 

### ISSUE THREAD

**Issue by googlehim** [microsoft/vscode-cpptools#11402]
### Feature Request

Does this vscode-cpptools extension support debugging  embedded(risc-v MCU)  program officially? 
With following tools:
riscv-none-eabi-gdb as gdb
openocd as gdbserver
vscode + vscode-cpptools extension

can you team confirm yes or no? I googled a lot and can't figure it out how to setup this debug situation and failed .

**Comment by sean-mcmanus** [comment]
@WardenGnaw ?

**Comment by heartacker** [comment]
?
