### ISSUE TITLE
Can't handle wildcards in compileCommands path

### ISSUE THREAD

**Issue by parsley72** [microsoft/vscode-cpptools#11404]
### Environment

OS and Version: Windows 11 connecting to WSL2 running Ubuntu 22.04
VS Code Version: 1.81.1
C/C++ Extension Version: 1.17.5
If using SSH remote, specify OS of remote machine: Ubuntu 22.04

### Bug Summary and Steps to Reproduce

Bug Summary: If I put a wildcard in the path in .vscode/settings.json the path isn't read correctly.

Steps to reproduce:
1. Change "C_Cpp.default.compileCommands" to "${workspaceFolder}/oe-workdir/my-app-*/compile_commands.json"
2. Open "C/C++ Configuration Warnings" tab.
3. See error:
```
[9/5/2023, 1:32:55 PM] "${workspaceFolder}/oe-workdir/my-app-service-/compile_commands.json" could not be parsed. 'includePath' from c_cpp_properties.json in folder 'my-app' will be used instead.
```

Expected behavior:
Should load the compile_commands.json file.

### Configuration and Logs

```shell
No c_cpp_properties.json (see https://github.com/microsoft/vscode-cpptools/issues/11395 for explanation).

settings.json:
{
    "C_Cpp.default.defines": [],
    "C_Cpp.default.compilerPath": "${workspaceFolder}/oe-workdir/recipe-sysroot-native/usr/bin/aarch64-oclea-linux/aarch64-oclea-linux-g++",
    "C_Cpp.default.cStandard": "c17",
    "C_Cpp.default.cppStandard": "gnu++17",
    "C_Cpp.default.intelliSenseMode": "linux-gcc-arm64",
    "C_Cpp.default.compileCommands": "${workspaceFolder}/oe-workdir/my-app-*/compile_commands.json",
}
```

### Additional context

The reason I have this path to compile_commands.json is that I'm using Yocto/Bitbake to run my CMake build. Bitbake adds a symbolic link `oe-workdir` to the app directory that points to the build environment. The compile_commands.json file is in a directory named after the app and any version tags or commits, so for example `oe-workdir/my-app-1.0.57/compile_commands.json`. But if you change the version that directory changes, hence the need for wildcards.

So this is a problem that others will also encounter.

**Comment by Colengms** [comment]
Hi @parsley72 .  Thanks for reporting this.  We'll add this to our backlog as a feature request.
