### ISSUE TITLE
Error underlines with - using std::cout, std::endl expressions

### ISSUE THREAD

**Issue by agauniyal** [microsoft/vscode-cpptools#1140]
This compiles successfully with `-std=c++17` flag by both gcc/clang but extension marks this as error. 

```
#include <iostream>
using std::cout, std::endl;
int main(){}
```

**Comment by bobbrow** [comment]
Please share your c_cpp_properties.json file and OS information.  Your includePath is probably incorrect.

**Comment by agauniyal** [comment]
Wow, I didn't create any c_cpp_properties.json file and auto-completion was working fine so I never noticed! I'm on arch linux (`4.13.7-1`).

**Comment by bobbrow** [comment]
Sorry, I spoke too soon.  It looks like this is simply a feature our IntelliSense engine doesn't support yet.  We don't have full C++ 17 support yet.  Thank you for reporting this.

**Comment by agauniyal** [comment]
May I ask how my completions are working without creating c_cpp_properties.json file!

**Comment by sean-mcmanus** [comment]
We use a default (the same that appears when you create the file for the 1st time).

**Comment by Colengms** [comment]
This appears to have been addressed.  That code no longer squiggles.
