### ISSUE TITLE
Red squiggle with "no operator "|" matches these operands" on compiling code

### ISSUE THREAD

**Issue by dehanjl** [microsoft/vscode-cpptools#11403]
### Environment

- OS and Version: MacOS 13.5.1 with Apple Clang 15
- VS Code Version: 1.82.0-insider
- C/C++ Extension Version: 1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary:
With the following code:
```c++
#include <iomanip>
#include <iostream>
#include <ranges>
#include <string>
#include <string_view>

int main() {
    std::string blob = "test1.test2.test3";

    auto tokensRanges = blob | std::ranges::views::split('.');

    for (const auto &tokenRange : tokensRanges) {
        std::cout << std::string(tokenRange.begin(), tokenRange.end()) << "\n";
    }

    return 0;
}
```
I get the following red squiggle: `no operator "|" matches these operands`, with the following details:
1. `operand types are: std::__1::string | std::__1::__range_adaptor_closure_t<std::__1::__bind_back_t<std::__1::ranges::views::__split_view::__fn, std::__1::tuple<char>>>`
2. `candidate function template "std::__1::operator|(const std::__1::bitset<_Size> &__x, const std::__1::bitset<_Size> &__y) noexcept" failed deduction`
3. `function "std::operator|" does not match because argument #1 does not match parameter`
4. `built-in operator|(<promoted integral>, <promoted integral>) does not match because argument #1 does not match parameter`

Expected behavior:
There should not be error squiggles when the code compiles.

I believe it might be similar to the following issue: https://github.com/Microsoft/vscode-cpptools/issues/2133. However, there also seem to be issues with the example code from https://en.cppreference.com/w/cpp/ranges/split_view, which compiles perfectly fine as well.

### Configuration and Logs

```shell
I have no configuration other than: `"C_Cpp.default.cppStandard": "gnu++20"`
```

**Comment by michelleangela** [comment]
@dehan-jl 
Could you provide the following logs to help us further investigate the issue:

1. Logs from running C/C++: Log Diagnostics from the VS Code command palette
2. Logs from the language server (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
