### ISSUE TITLE
Wrong file on switch header/source

### ISSUE THREAD

**Issue by dpkristensen** [microsoft/vscode-cpptools#11414]
### Environment

- OS and Version: Windows 11 Pro v22H2 build 22621.2215
- VS Code Version: 1.81.1
- C/C++ Extension Version: 1.17.5
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:
Switching header/source will frequently find the wrong file.

Steps to reproduce:
1. Create a folder with empty files using the following structure:
~~~~
a/test.c
b/test.c
include/a/test.h
include/b/test.h
~~~~
2. Open the folder in VS code

Expected behavior:
When b/test.h is selected, and I press ALT+O, b/test.c should be opened.
When a/test.h is selected, and I press ALT+O, a/test.c should be opened.

### Configuration and Logs

```shell
No c_cpp_properties.json, and "C/C++: Log Diagnostics" is not a valid command.
```

### Other Extensions

Installed extensions:

- dan-c-underwood.arm
- grimmer.vscode-back-forward-button
- eugenwiens.bitbake
- ms-vscode.cpptools
- ms-vscode.cpptools-extension-pack
- ms-vscode.cpptools-themes
- vs-publisher-1448185.keyoti-changeallendoflinesequence
- twxs.cmake
- ms-vscode.cmake-tools
- marus25.cortex-debug
- mcu-debug.debug-tracker-vscode
- mrmlnc.vscode-duplicate
- trond-snekvik.gnu-mapfiles
- jeremyfunk.hidefiles
- zixuanwang.linkerscript
- davidanson.vscode-markdownlint
- mcu-debug.memory-view
- webfreak.debug
- nordic-semiconductor.nrf-connect-extension-pack
- nordic-semiconductor.nrf-devicetree
- nordic-semiconductor.nrf-kconfig
- nordic-semiconductor.nrf-terminal
- drmerfy.overtype
- mcu-debug.peripheral-viewer
- ms-python.vscode-pylance
- ms-python.python
- mcu-debug.rtos-views
- dpkristensen-garmin.udev-rules
- zxh404.vscode-proto3
- dotjoshjohnson.xml
- nordic-semiconductor.nrf-connect (disabled globally)

The issue is still reproducible after disabling all extensions except ms-vscode.cpptools

### Additional context

While this can be a problem for projects that have files with the same name in the current project, it can also present a problem when your source files conflict with a file found in an external SDK provided by a configuration manager like CMake.

For example, if I am using a project that imports the Zephyr SDK via CMake tools, the Zephyr sources are not in the workspace itself, but can be found outside of the workspace.

I propose that if there are multiple files in the Intellisense DB matching the current file, it should show a list of all files.  Ideally the first "preferred option" has the longest shared path with the current file.  The pseudo code for the scoring algorithm could be written like this:

~~~~
file_match_score(viewer_file_name, idb_file_name)
{
    base_idb_file_name = basename(idb_file_name); // idb_file_name without the extension
    base_viewer_file_name = basename(viewer_file_name); // viewer_file_name without the extension
    score = 0;
    score += num_matching_left_chars(viewer_file_name, base_idb_file_name);
    score += num_matching_right_chars(base_viewer_file_name, base_idb_file_name);
    return score
}

file_match_score("C:/test/a/test.c", "C:/test/a/test.h") == 14 left + 14 right == 28
file_match_score("C:/test/a/test.c", "C:/test/b/test.h") == 8 left + 4 right = 12
file_match_score("C:/test/a/test.c", "C:/external_sdk/some_path/test.h") == 3 left + 4 right = 7
~~~~

So you can see this will attempt to prioritize files for matching based on higher score:
1. In the current directory
2. In the same project directory and a matching component folder path
3. In the same project directory and a non-matching component folder path
4. Files from an external SDK

**Comment by browntarik** [comment]
Thank you for letting us know. These are known limitations within our implementation of Switch Header/Source and will be addressed in the future. Please follow this issue: https://github.com/microsoft/vscode-cpptools/issues/2635 to stay up to date with our progress. 

This current issue will be closed as a duplicate unless there are further concerns.
