### ISSUE TITLE
Unclear error message: Quick info operation failed: FE: 'Unknown error'

### ISSUE THREAD

**Issue by AlexanderHD27** [microsoft/vscode-cpptools#11423]
### Environment

- OS and Version: Ubuntu 22.04 LTS
- VS Code Version: 1.82.0
- C/C++ Extension Version: v1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary:
I'm trying to develop a simple c-application for the rpi-pico but somethings seems to go wrong. Sadly I cannot provided more detail besides the error message "Quick info operation failed: FE: 'Unknown error'", that is unclear. And having this error, IntelliSens stops working completely.

Steps to reproduce:
This is a big problem because this problem pops up randomly, and maybe cause be different types of problems. But this happens (often, but not every time), when I create a new .c file (not .h file)

Expected behavior:
It would be nice to have a more informative error message, the actually provides information about the underling course of the error.

**To make it clear, the issue here is not that fact that I get an error (maybe, I am the sources of the error, because I misconfiguration something idk), but the absents of a more informative error message**, so this Issue could be seen also as a feature request

There are also related Issues like [#11209](https://github.com/microsoft/vscode-cpptools/issues/11209) and [#6114](https://github.com/microsoft/vscode-cpptools/issues/6114)

### Configuration and Logs

```shell
Quick info operation failed: FE: 'Unknown error'
```

### Other Extensions

I use these these extension:
- Arduino v0.6.0
- Arm Assembly v1.7.4
- C/C++ v1.17.5
- C/C++ Themes v2.0.0
- CMake v0.0.17
- CMake Tools v1.15.31
- Cortex-Debug v1.12.0
- debug-tracker-vscode v0.0.15
- Makefile Tools v0.7.0

### Additional context

I'm not familiar with the vscode extension system, so this also maybe a issue in some other component, so pardon me if this is issues, is nonsensical

**Comment by Colengms** [comment]
Hi @AlexanderHD27 .  An `FE: 'Unknown error'` is an IntelliSense front-end related internal error.  It's likely a bug related to failing to parse some unexpected construct in code.

Can you isolate a repro to a specific segment of code that triggers it, and provide a minimal repro in the form of a zip file for GitHub repo?  That could be very useful to us to investigate and validate a fix.

**Comment by AlexanderHD27** [comment]
For sure! I have run into this error on multiple occasions, so due to the unclear nature of the error message, I cannot ensure that the problem is always the same, but here is a semi-stable way to reproduce this issue:

For that to work you need to have the PICO-SDK setup. Just follow the [Getting-Started-Guide](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf), Chapter 2.1 and make sure that the $PICO_SDK variable is loaded and points to the correct location

0. Load the provide Vscode-Profile
1.  Create two copies of the project
2. Open the first project and let CMake Conf configure your project (chose as the compile arm-none-eabi)
3. Open the main.c
4. Open the main.c in the other project folder.

This should result in the error.
To be clear, the purpose of this issue is not to fixing the error itself, but just to implement a more clear error message

Here is an base64-encode tar archive containg everything: https://gist.github.com/AlexanderHD27/85e3167cb13abf4ad25f5bb39fe011ba

**Comment by AlexanderHD27** [comment]
Okay, I started toying around a bit and I found a simpler way to reproduce this issue:
(For this you only need cmake and gcc, nothing else like in my prevouse example)

1. Create a clean VSCode Profile and install these extensions:
- C/C++ v1.17.5
- CMake Tools v1.16.7
(Vscode Version: 1.82.2)
2. Open an empty folder and create CMakeLists.txt and main.c. The CMakeLists.txt should contain this (main.c should remain empty):
```cmake
cmake_minimum_required(VERSION 3.22.1)
project(sitk_example)
add_executable ( main main.c )
```
3. Then if Configure CMake by pressing CTRL+P and `CMake: Configure`
4. Create a new empty file: This should trigger the issue

**Comment by Colengms** [comment]
Hi @AlexanderHD27 .  I'm unable to easily reproduce an issue using the simple repro steps you described (on Ubuntu 22.04, with gcc 13).  Also, it's unclear to me why a `Quick info operation failed` would occur with an empty file.

Could you enable `"C_Cpp.loggingLevel": "Debug"` and provide the output of the C/C++ output channel leading up to the repro?  Also, could you provide the content of your `c_cpp_properties.json` file (if any), or any relevant `C_Cpp.` settings?
