### ISSUE TITLE
Shortcut keys for switching headers/sources not working

### ISSUE THREAD

**Issue by ichangyu** [microsoft/vscode-cpptools#11431]

**Comment by sean-mcmanus** [comment]
What shortcut key are you using? Alt+O? Has another command been mapped to that? The File->Preferences->Keyboard Shortcuts page shows what keyboard settings are used.

**Comment by ichangyu** [comment]
> 您使用什么快捷键？Alt+O？是否已将另一个命令映射到该命令？“文件>首选项”>键盘快捷键页面显示使用的键盘设置。

Use the default Alt+O, to which no other commands are mapped.
![image](https://github.com/microsoft/vscode-cpptools/assets/144758088/4c1d26ff-ae29-4f64-807b-da6b3870602d)

It has been verified that rolling back the version to V1.16.3 can be used normally. V1.17.2-V1.17.5 cannot be used.
![image](https://github.com/microsoft/vscode-cpptools/assets/144758088/915f96bf-a7ac-4378-a610-a30f88cc843d)

**Comment by ethanul** [comment]
I'm experiencing the same issue.  It's not just a keyboard shortcut issue.  The "C/C++: Switch Header/Source" command is missing from the command palette.  The command exists in 1.16.3 and disappeared in 1.17.x.

**Comment by ichangyu** [comment]
@ethanul 
Have you solved this problem? I have been using version 1.16.3.
