### ISSUE TITLE
The language server crashed. Restarting...

### ISSUE THREAD

**Issue by BinaryBearzz** [microsoft/vscode-cpptools#11432]
### Environment

- OS and Version: 
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
The language server crashed. Restarting...[
The language server crashed 5 times in the last 3 minutes. It will not be restarted.
```

### Other Extensions

-

**Comment by sean-mcmanus** [comment]
We need more info. See https://github.com/microsoft/vscode-cpptools/issues/10651 .
