### ISSUE TITLE
Ctrl+left click does not find declaration

### ISSUE THREAD

**Issue by Omcsesz** [microsoft/vscode-cpptools#11434]
Type: <b>Bug</b>

Hello, Team!

When I try to jump to the declaration of a variable within a function, the extension offers me a few options for the possible declaration, when in fact the declaration is a few lines above the place I clicked. I have disabled all my other extensions. Can you please support?

Extension version: 1.17.5
VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:45:05.575Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (1.90GB free)|
|Process Argv|--crash-reporter-id 5d464342-4569-4e40-9715-034b47c41cba|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by sean-mcmanus** [comment]
It looks like your IntelliSense is not configured and it's falling back to the tag parser. What is your C_Cpp.intelliSenseEngine setting? What do you get when you run the C/C++: Log Diagnostics command from the Command Palette?

**Comment by Omcsesz** [comment]
> It looks like your IntelliSense is not configured and it's falling back to the tag parser. What is your C_Cpp.intelliSenseEngine setting? What do you get when you run the C/C++: Log Diagnostics command from the Command Palette?

This is my C_Cpp.intelliSenseEngine setting:
[image](https://github.com/microsoft/vscode-cpptools/assets/1839739/8d52f55c-ce10-4506-b0c4-1128fb6ee64d)

**Comment by sean-mcmanus** [comment]
Your original screenshot shows red errors in the source file in the Problems window. Those could be causing IntelliSense parsing to fail. You may have include paths missing. It looks like you may be missing the Windows SDK headers (from your diagnostics logging).

**Comment by Omcsesz** [comment]
> Your original screenshot shows red errors in the source file in the Problems window. Those could be causing IntelliSense parsing to fail. You may have include paths missing. It looks like you may be missing the `C:\MinGW\lib\gcc\mingw32\include` includePath (from your diagnostics logging).

After I added `C:\MinGW\lib\gcc\mingw32\include` to the include path, a few errors went away, but some remained, even if `${workspaceFolder}/**` is added to the include path.

**Comment by sean-mcmanus** [comment]
Normally, you shouldn't have any system includes in your includePath -- those should be automatically computed from the compiler path. If you have system includes in your includePath, the ordering of the paths could be incorrect. Are all the headers being found?

**Comment by Omcsesz** [comment]
> Normally, you shouldn't have any system includes in your includePath -- those should be automatically computed from the compiler path. If you have system includes in your includePath, the ordering of the paths could be incorrect. Are all the headers being found?

No, one of them is not available on the branch I'm on.

**Comment by sean-mcmanus** [comment]
Are you able to add the folder to the includePath so that the header can be found?

**Comment by Omcsesz** [comment]
> Are you able to add the folder to the includePath so that the header can be found?

Yes.

**Comment by sean-mcmanus** [comment]
So does going to the declaration work after that? Are there any more squiggles?

**Comment by Omcsesz** [comment]
> So does going to the declaration work after that? Are there any more squiggles?

Sadly, there are. In the gif below, the extension say EINVAL is not defined, when Ctrl+left click is maneuvering to it's definition, and the file containing it is included:
[JumpToDefinitionFails_2](https://github.com/microsoft/vscode-cpptools/assets/1839739/c0f39fe0-49ee-4f4c-ae81-f7e41a0532bb)

**Comment by sean-mcmanus** [comment]
The TU is probably picking up a different errno.h at a different location. Go to def uses the browse database and doesn't reflect what is seen by the TU/IntelliSense, which isn't finding the errno.h definitions. Can you run C/C++: Log Diagnostics to see if the path containing the headers is in the include path list and there's not another include path that contains errno.h in that list? It's possible your system includes are in the wrong order.

**Comment by Omcsesz** [comment]
> The TU is probably picking up a different errno.h at a different location. Go to def uses the browse database and doesn't reflect what is seen by the TU/IntelliSense, which isn't finding the errno.h definitions. Can you run C/C++: Log Diagnostics to see if the path containing the headers is in the include path list and there's not another include path that contains errno.h in that list? It's possible your system includes are in the wrong order.

There is another errno.h in the C:\MinGW\include folder as well, but it is not on the includePath.

**Comment by sean-mcmanus** [comment]
What file is opened when you right-click on the errno.h in `#include "errno.h"` and choose Go to Definition? I assume it would be a different folder than C:\MinGW\include.

**Comment by sean-mcmanus** [comment]
That folder is in your includePath, right? You should either remove that path or force it to the end via `"compilerArgs": ["-idirafter=<the directory>"]`. If you're building with CMake, you may also want to consider installing the CMake Tools extension and setting and using that to configure so that the includePaths match what CMake uses to build.

**Comment by Omcsesz** [comment]
I moved it to the end of the list, but even after that, there are some squiggles remaining that I don't understand:

[JumpToDefinitionFails_3](https://github.com/microsoft/vscode-cpptools/assets/1839739/d764ccbc-b49c-4142-930c-83596c68c287)
The header uwb_config.h is included in the .c file, and the jump to definition works, but the Problems view lists the definitions as missing.

**Comment by sean-mcmanus** [comment]
@Omcsesz Your video appears to show that you don't have the correct define. I see the definition inactive in a `#ifdef CONFIG_DWT_UWB` block.

**Comment by Omcsesz** [comment]
> @Omcsesz Your video appears to show that you don't have the correct define. I see the definition inactive in a `#ifdef CONFIG_DWT_UWB` block.

Does it mean that that definition will not be resolved?
