### ISSUE TITLE
C++98-style enum definitions not seen under the namespace

### ISSUE THREAD

**Issue by gsikorski** [microsoft/vscode-cpptools#1143]
Consider this code:
```
namespace foo {
enum bar {
    baz = 0
};
}

auto tmp1 = foo::baz;
auto tmp2 = foo::bar::baz;
```

Although this code compiles, intellisense cannot find `foo::baz` definition (displays error: "No definition found for 'baz'). `foo::bar::baz` is found though.

**Comment by sean-mcmanus** [comment]
foo::baz appears in the completion list for me with 0.13.1. Can you give more repro details?

**Comment by gsikorski** [comment]
Hmm, not really. I am also using version 0.13.1. This is definitely not working on my setup. I tried similar code snippet (in the same file) with no namespace around and it is working fine:
```
namespace foo {
enum bar {
    baz = 0
};
}

auto tmp1 = foo::baz; // not found
auto tmp2 = foo::bar::baz;// found

enum bar2 {
    baz2 = 0
};

auto tmp3 = baz2; // found
auto tmp4 = bar2::baz2; // also found
```

Are you sure you tried with `namespace`?

**Comment by sean-mcmanus** [comment]
What is your OS?

**Comment by gsikorski** [comment]
Windows 7

**Comment by gsikorski** [comment]
I have some marvelous corpo firewall though, if this makes any difference. I had to manually install C/C++ dev tools, including manual fetch of all dependencies. But I would expect intellisense not working at all should I had incorrect set it up.

**Comment by sean-mcmanus** [comment]
Oh, I see. You're using the Tag Parser (so it looks like a bug in that). You should switch your intelliSenseEngine to "Default" if you want this to work.

**Comment by gsikorski** [comment]
Yes, change to `"C_Cpp.intelliSenseEngine": "Default"` seems to solve this example problem. However, it still does not work in my original (large) codebase, but I did not yet fully figure out small example to give you back. Still playing...

**Comment by sean-mcmanus** [comment]
Your large code base is probably falling back to using the Tag Parser for completion due to missing include paths. You could change the intelliSenseEngineFallback to Disabled.

**Comment by gsikorski** [comment]
Yes, that is correct. With this setting disabled I have tons of complains about missing includes.

**Comment by sean-mcmanus** [comment]
@gsikorski If the missing includes are found recursively via the browse.path, you should be able to add them to the includePath via a code action.

**Comment by Colengms** [comment]
It looks like this has been addressed.  I cannot repro (with Tag Parser or Default) on a recent build.  Closing.  If there is still an issue here, please let us know.
