### ISSUE TITLE
`${env:MY_VAR}` is not handled correctly on macOS and Linux if it returns undefined value

### ISSUE THREAD

**Issue by ryuujo1573** [microsoft/vscode-cpptools#11447]
### Environment

- OS and Version: macOS 13
- VS Code Version: any
- C/C++ Extension Version: latest

### Bug Summary and Steps to Reproduce

Bug Summary:

When specifying the `includePath` property of `c_cpp_properties.json` configurations,
I was told that either `${env` or `SOME_VAR}/lib/include/**` is not a path.
<img width="841" alt="Screenshot 2023-09-19 at 12 00 08" src="https://github.com/microsoft/vscode-cpptools/assets/16525512/2ab30a81-2986-42bf-8d05-0f20685d5ea0">

> The hidden path is cwd

Steps to reproduce:
1. add a item of `${env:SOME_VAR}/lib/include/**` to `includePath`.
2. boom

Expected behavior:
[This should work](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables)

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "${env:EMSCRIPTEN_ROOT}/libexec/system/include/**"
            ],
            "defines": [
                "WASM"
            ],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-arm64"
        }
    ],
    "version": 4
}
```

```[tasklist]
### Tasks
```

**Comment by michelleangela** [comment]
@ryuujo1573 
To use env variables in the [c_cpp_properties.json file](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference), they need to be defined as follows:

![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/4e70ca9f-ff55-4b17-9056-02c296429941)

Could you try defining `EMSCRIPTEN_ROOT` in c_cpp_properties.json under the config ` "env": {  }`?

**Comment by michelleangela** [comment]
Update: the parser for resolving variables on macOS and Linux is broken. It works for Windows.

**Comment by ryuujo1573** [comment]
Sorry for late reply 😢 

- [x] `${env:VAR}` parsing is broken on posix os :)

Since `:` is widely used as path separator, which, may be the cause of breaking.
I've tried escape the colon but it doesn't work (vscode does not consider `\:` is something to escape)

Thanks for your efforts.

**Comment by bobbrow** [comment]
@ryuujo1573 did you try `${EMSCRIPTEN_ROOT}` without the `env:`?  We'll fix the separator bug, but in the meantime, you should be able to get access to that variable without `env:`.

**Comment by ryuujo1573** [comment]
> @ryuujo1573 did you try `${EMSCRIPTEN_ROOT}` without the `env:`? We'll fix the separator bug, but in the meantime, you should be able to get access to that variable without `env:`.

<img width="679" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/16525512/5936750f-b772-4273-8255-6a9f0a73d96b">

It seems not working on my machine. 

I've turned to `ms-vscode.cmake-tools` as config provider, and it's a cmake project indeed, which works for now.

<details><summary>p.s.  cmake conf</summary>
<pre>{
  "cmake.environment": {
    "EMSCRIPTEN_ROOT": "/opt/homebrew/opt/emscripten"
  },
  "cmake.configureEnvironment": {
    "CMAKE_TOOLCHAIN_FILE": "${env:EMSCRIPTEN_ROOT}/libexec/cmake/Modules/Platform/Emscripten.cmake"
  },
  // ...
}</pre>
</details>

**Comment by bobbrow** [comment]
> {
>   "cmake.environment": {
>     "EMSCRIPTEN_ROOT": "/opt/homebrew/opt/emscripten"
>   },
> }

ohhhh...  We can't see the `cmake.environment`. It doesn't leak into our process.  But the variable you defined in `env` in your screenshot should have been picked up.  I don't repro this on Windows (don't have a mac handy), but we'll take a look.

**Comment by michelleangela** [comment]
@ryuujo1573 
Could you share how you installed Emscripten and how the environment variables were set?

I followed https://emscripten.org/docs/getting_started/downloads.html#updating-the-sdk and it didn't save or export the environment variables so that they're available globally.

**Comment by ryuujo1573** [comment]
> @ryuujo1573 Could you share how you installed Emscripten and how the environment variables were set?
> 
> I followed https://emscripten.org/docs/getting_started/downloads.html#updating-the-sdk and it didn't save or export the environment variables so that they're available globally.

About `EMSCRIPTEN_ROOT`, it's just a custom variable exported using `export EMSCRIPTEN_ROOT=$(brew --prefix emscripten)`

**Comment by michelleangela** [comment]
@ryuujo1573 
>About EMSCRIPTEN_ROOT, it's just a custom variable exported using export EMSCRIPTEN_ROOT=$(brew --prefix emscripten),
and I installed emscripten by brew install emscripten

If the command `export EMSCRIPTEN_ROOT=$(brew --prefix emscripten)` was called only in a Terminal's session, then it only makes that variable available in that Terminal's session where that command is executed. The variable will also be available to any app that gets executed from that Terminal's session (that is if VS Code was started from that Terminal, then VS Code will also inherit the environment variables from that terminal's session).

Per instructions in https://support.apple.com/guide/terminal/use-environment-variables-apd382cc5fa-4f58-4449-b20a-41c53c006f8f/2.13/mac/13.0, it says that "After you close a Terminal window, variables you set in that window are no longer available. If you want the value of a variable to persist across sessions and in all Terminal windows, you must set it in a shell startup script." 

For my setup, I added the line `export EMSCRIPTEN_ROOT=$(brew --prefix emscripten)` in file the `~/.zshrc`, which gets executed during the startup of the Terminal. Then I verified that the custom variable is available in any new session via command `env`, which prints all available environment variables in that session.

Could you try adding `export EMSCRIPTEN_ROOT=$(brew --prefix emscripten)` to your shell startup script (see https://stackoverflow.com/questions/65597552/how-exactly-to-set-up-and-use-environment-variables-on-a-mac for the different shell script options depending on what shell you're using) and see if that works?

Note: there is still the bug with the extension, where it should handle the case if no value is returned for some environment variable -- for this I have a fix.

**Comment by ryuujo1573** [comment]
Sorry for the late reply. 
I'm pretty convinced that envvar is properly exported and accessible from vscode instance.
See also: https://github.com/microsoft/vscode/issues/194084
> Env var replacement works with existing env_vars like ${env:HOME}.'
Thanks for your reply ♥

**Comment by michelleangela** [comment]
@ryuujo1573 
Could run the command `env` from the VS Code terminal and copy the log output here? The log will print out what variables are accessible to that session of VS Code.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.18.0
