### ISSUE TITLE
CMake 'add_compile_definitions' is ignored causing false positive `C/C++` problems.

### ISSUE THREAD

**Issue by yosefgor** [microsoft/vscode-cpptools#11452]
### Environment

- OS and Version: `Microsoft Windows 11 Enterprise 10.0.22000`
- VS Code Version:
```
cmd> code --version
1.82.2
abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
x64
```
- C/C++ Extension Version: `v1.17.5`
- SSH remote?: No.
- Additional dependencies:
           1.  `CMake Tools` extension version `v1.15.31`
           2. `Clang 12.0.0 (GNU CLI) for MSVS 16.11.32228.343 (Visual Studio Professional 2019 Release)` - used as cmake's kit.

**Hint: I have seen this issue on different OS's, and different cmake kits.**

### Bug Summary and Steps to Reproduce

# Bug Summary:
When using cmake with the `C/C++` extension - if the `add_compile_definitions` command is used:
cmake will properly process it, but the `C/C++` will ignore it.
This can result with the `C/C++` extension displaying errors that should not exit.

# Example
The example showcases `C/C++` presenting a problem which clearly does not exist.

The following picture summarizes the example:
![image](https://github.com/microsoft/vscode-cpptools/assets/102896220/82319118-4f0e-46b8-a074-2b215a415b5d)

The project has just a source file `myapp.cpp` and the `CMakeLists.txt` file.
Both files are in the currently opened directory `tmp`.

As can be seen in `OUTPUT` in the bottom right, compilation is successful - meaning `MYDEF` is defined in the pre-processor's environment.
Meanwhile, as can be seen in `PROBLEMS` in the bottom left,  the `C/C++` extension is producing an error about `foo( )` being undefined. From this we can deduce that whatever is producing this error must not have `MYDEF` defined.

# Steps to reproduce:
1. Create some test directory, add files `myapp.cpp` and `CMakeLists.txt` as in the example to the directory.
4. Open that folder as the current working directory in vscode.
5. Run `CMake Configure`.
6. build the `myapp` target.

# Expected behavior:
`C/C++` extension should not show any errors in the example.

# Configuration and Logs

`c_cpp_properties.json` does not exit in the example.

The `C/C++: Log Diagnostics` does not seem to exist in my VS Code command palette.

However I run the command `CMake: Log Diagnostices`. Here is the output:

```
{
  "os": "win32",
  "vscodeVersion": "1.82.2",
  "cmtVersion": "1.15.31",
  "configurations": [
    {
      "folder": "c:\\Users\\yosefgor\\OneDrive - Intel Corporation\\Desktop\\tmp",
      "cmakeVersion": "3.20.21032501",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/x64/bin/clang.exe",
        "CXX": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/x64/bin/clang.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 1,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "myapp",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Other Extensions

1. `CMake Tools` extension version `v1.15.31`
2. `CMake` extension version `v0.0.17`

**Comment by yosefgor** [comment]
I have also noticed these false positive problems sometimes disappear when there is not editor with the problematic source file opened.

**Comment by yosefgor** [comment]
Quick patch for anyone with the same issue:
Add compiler definition in the `.vscode/c_cpp_properties.json` file, for the example:
```
{
	"configurations": [
		{
                        .
                        .
                        .
			"compilerArgs" : ["-DMYDEF"]
		}
	]
}
```

**Comment by yosefgor** [comment]
Running `C/C++: Change Configuration Provider` and selecting `CMake Tools` **fixed the issue**.
<br>
<br>

Although, there are no other configuration providers detected:
![image](https://github.com/microsoft/vscode-cpptools/assets/102896220/a27c1d9b-53c7-4767-9f73-0ad954809359)

I would expect that when there is only one provider detected - it will be automatically used.
Perhaps this is a sperate issue.

**Comment by bobbrow** [comment]
Yeah, I'm not sure what the problem was.  I do know that CMake Tools does not usually register as a provider until it has run the "configure" command, but in your original report the CMake log showed that configure had been run.  Sorry for the inconvenience.  If you run into this again and can help us isolate the steps to reproduce it, we'll investigate and put a fix out for it.

**Comment by yosefgor** [comment]
Deleting cmake's `build` directory and `.vscode` causes the issue to come back.

This is with the same example I have given before, I have also detailed steps to reproduce:
```
1. Create some test directory, add files myapp.cpp and CMakeLists.txt as in the example to the directory.
2. Open that folder and the current working directory in vscode.
3. Run CMake Configure.
4. build the myapp target.
```

If you are interested in tracking down the cause for the missing configuration provider detection, I would be happy to provide additional details.

**Comment by bobbrow** [comment]
When you say "Open that folder and the current working directory in vscode" what are the two folders you're opening?  The test directory from step 1 and its parent folder?  I don't know what the current working directory is and why you'd want to open that one.

**Comment by yosefgor** [comment]
There was a **typo** in _steps to reproduce_.
I meant to write _open that folder **AS** the current working directory_ not _open that folder **AND** the current working directory_.

Also, _that folder_ refers to _some test directory_:
![image](https://github.com/microsoft/vscode-cpptools/assets/102896220/229d4199-c1fa-4539-be54-c803e1a941bf)
