### ISSUE TITLE
Problem matcher for scons

### ISSUE THREAD

**Issue by Tabaie** [microsoft/vscode-cpptools#1146]
It would be awesome if, as in actual Visual Studio, clicking on a compiler error message takes you to the line of code causing that error.

**Comment by bobbrow** [comment]
If you configure a problem matcher in your tasks.json, you can get that behavior.  Are you compiling using tasks.json, or in an external terminal window?

**Comment by Tabaie** [comment]
I'm calling SCons from tasks.json.
