### ISSUE TITLE
The vscode-cpptools build of LLVM (clang-tidy/clang-format) 17.0.1 fails to build for Windows arm64

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11472]
The commit that triggers this is https://github.com/llvm/llvm-project/commit/c28506ba4b6961950849f8fdecd0cf7e503a14f9#diff-bfe07ea7ccd5eb23550d79ee367a9eac1fcb678629bffaeffe0793e42940ff16 (it works with the prior LLVM commit). It seems to get stuck in some sort of build loop.

We might need to file a bug on LLVM or find a fix ourselves, not sure.

**Comment by Colengms** [comment]
The issue appears to be with arm64 cl.exe.  It does built, it just spends 2 hours on that file for some reason.  I opened: https://developercommunity.visualstudio.com/t/clexe-takes-forever-to-compile-llvm-pro/10479079
