### ISSUE TITLE
Problem with location in WSL in Windows 10 Fall Creators Update

### ISSUE THREAD

**Issue by sandhilt** [microsoft/vscode-cpptools#1148]
With Windows 10 Fall Creators Update (1709 ~ 16299.19), the SO don't put WSL in %localappdata%\lxss and
[this](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md)  no more working with Ubuntu because location no more exist.

**Comment by icylogic** [comment]
change from
`${localappdata}/lxss/rootfs/$YOUR_LINUX_PATH`
to
`${localappdata}/Packages/$PACKAGE_NAME/LocalState/rootfs/$YOUR_LINUX_PATH`
where $PACKAGE_NAME could be:
- `CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc` for Ubuntu
- `46932SUSE.openSUSELeap42.2_022rs5jcyhyac` for openSUSE Leap
- `46932SUSE.SUSELinuxEnterpriseServer12SP2_022rs5jcyhyac` for SUSE Linux Enterprise Server
