### ISSUE TITLE
Create Declaration / Definition failed: Unknown error

### ISSUE THREAD

**Issue by avelinobego** [microsoft/vscode-cpptools#11483]
### Environment

- OS and Version: Arch Linux x64 bits
- VS Code Version: C/C++ for Visual Studio Code (Microsoft)
- C/C++ Extension Version: v1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary:
Extension fails to create a definition of member function from hpp file to cpp file

Steps to reproduce:
1. Go to last definition in public part of any class.
2. Press "CTRL" + "."
3. Show popup error "Create Declaration / Definition failed: Unknown error".

Expected behavior:

### Configuration and Logs

```shell
"C_Cpp.autocompleteAddParentheses": true,
  "C_Cpp.intelliSenseEngineFallback": "enabled",
```

**Comment by michelleangela** [comment]
@avelinobego 
Is there a sample code or hpp and cpp files that you could provide that reproduces the issue? I am not able to reproduce the issue with:

Test.hpp
```cpp
class Test
{
public:
    Test();
    void myMethod();
    void myMethod2();
};
```

Test.cpp

```cpp
#include "Test.hpp"

Test::Test()
{
}

void Test::myMethod()
{
}
```

Steps:
1. Use sample code
2. Place cursor on `myMethod2` in Test.hpp.
3. Either click on lightbulb or press `Ctrl` + `.` to display code actions.

![image](https://github.com/microsoft/vscode-cpptools/assets/38734287/901b084c-a78e-4ab5-8cbd-588031110a2e)
