### ISSUE TITLE
Tried debug Core dump in VSCode after succesfull debug in WSL terminal

### ISSUE THREAD

**Issue by pekotte** [microsoft/vscode-cpptools#11484]
### Environment

- OS and version: Windows 11 Enterprise 21H2
- VS Code: 1.82.2
- WSL version: 2
- WSL Distro: Ubuntu 22.04
- C/C++ extension: 1.17.5
- GDB version: 12.1

### Bug Summary and Steps to Reproduce

Bug Summary:
I'm debugging a core dump using *gdb-multiarch*, the thing is it's working fine in the WSL terminal (gdb-multiarch file -c core) but when I try to debug it in VSocde crash right after stop in the core segmentation fault. I replace the app names to unknow for client confidenciality.
I also try with differents gdb versions like 9.2 (Ubuntu 20.04), 10.1 and finally 12.1 all with the same issue.

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do '...'
4. See error...
![github_1](https://github.com/microsoft/vscode-cpptools/assets/146330304/6b3fff51-3192-40db-a084-93b543a671c7)

### Debugger Configurations

```shell
launch.json
-----------
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [                
        {
            "name": "(gdb) Launch Core Dump",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/<unknow>.debug",
            "args": ["-g "],
            "stopAtEntry": true,
            "coreDumpPath": "${workspaceFolder}/<unknow>Core",
            "cwd": "${fileDirname}",
            "miDebuggerPath": "/usr/bin/gdb-multiarch",
            "MIMode": "gdb",
        }
    ]
}
```

### Debugger Logs

```shell
The log is attach on Additional Information
```

### Additional Information

[log_Core.txt](https://github.com/microsoft/vscode-cpptools/files/12763166/log_Core.txt)

**Comment by Agomezvi** [comment]
Similar/same issue here.
