### ISSUE TITLE
System include paths should always be after recursive include paths

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode-cpptools#11485]
Type: <b>Bug</b>

#include "adc.h"

includes adc.h from minGW first (at least for browsing), instead of local folder,

if I wanted that then I would use
#include <adc.h>

Extension version: 1.17.5
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Using IntelliSense, `#include ""` prioritizes the local folder in regards to which adc.h file it chooses, as can be verified via using Go to Definition on the include line or running C/C++: Log Diagnostics. What do you mean by "at least for browsing"? Can you provide more repro details or the Log Diagnostics output?

**Comment by mrx23dot** [comment]
Please don't close this.

I don't know what else can be more important than locating the correct include files.

**Comment by bobbrow** [comment]
I think I know what's going on here.  It's because we prioritize exact paths over recursive includes.  When we add the compiler include paths at the end they are being prioritized ahead of the workspace include paths, but compiler paths should always be last.

I thought this worked in the past, but it's been a while since I worked on this part of the code.  We need to investigate what's going on here and make sure the compiler includes are at the end.

**Comment by sean-mcmanus** [comment]
@mrx23dot This should be fixed/changed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.22.0

**Comment by sean-mcmanus** [comment]
@mrx23dot -- if you were using 1.22.1, you may have hit a random deadlock that got fixed with 1.22.2.
