### ISSUE TITLE
Hint missing standard header suggestion

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode-cpptools#11497]
Type: <b>Bug</b>

Pointing to std lib function brings up hint, this hint should say what header to include for it, same way as in Eclipse.

![image](https://github.com/microsoft/vscode-cpptools/assets/4163396/a1a3fdc3-56ab-47dd-930f-d073af3243b2)

Extension version: 1.17.5
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by browntarik** [comment]
Hi! Thank you for your suggestion. Adding this functionality is something that we have on our radar. To see any future updates, feel free to continue tracking this issue.
