### ISSUE TITLE
compile_commands.json include directories not being seen

### ISSUE THREAD

**Issue by wjk** [microsoft/vscode-cpptools#11492]
### Environment

- OS and Version: macOS 14.0
- VS Code Version: 1.82.2
- C/C++ Extension Version: 1.17.5
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:

My project contains its own SDK (standard headers and whatnot). As such, the `-nostdinc` flag is used. This also means that I must supply the location of every header used on the command line. I am doing this. Everything compiles. However, every file in part of the project says that it cannot find any `#include` files. I have verified that the correct `-I` flags are present in my `compile_commands.json`.

Steps to reproduce:
1. Clone https://github.com/PureDarwin/PureDarwin
2. Open VSCode and configure CMake, using `vscode/settings.json` to ensure `CMAKE_EXPORT_COMPILE_COMMANDS` is TRUE.
3. Open the following file: `src/Kernel/Extensions/ApplePS2Controller/ApplePS2Controller.cpp`

Expected behavior:

All headers should resolve and autocompletion should function normally.

### Configuration and Logs

```shell
c_cpp_properties.json: not using
C/C++ Log Diagnostics command: see attached file below
Language server output: see attached file below
```

### Additional context

Since the logs are too long to paste into GitHub directly, here are links to the log files requested above:

[C/C++ Log Diagnostics command output](https://github.com/microsoft/vscode-cpptools/files/12785654/diagnostics.txt)
[Language server input](https://github.com/microsoft/vscode-cpptools/files/12785656/output.txt)

**Comment by Colengms** [comment]
Hi @wjk .  It sounds like you're relying on the C/C++ Extension's default behavior of automatically configuring for use with CMake Tools, if it's the only valid 'configuration provider' extension provider that has registered.

I've cloned the repro you suggested (and installed OpenSSL headers, which appear to be required).  Initially, I could replicate the issue you're referring to.  But, once I built the project, that appeared to generate required files, and all headers resolved properly from that point on.

For some insight into what CMake Tools is providing to the C/C++ Extension, consider enabling the setting  `"C_Cpp.loggingLevel": "Debug"` and checking the C/C++ output channel for a `custom configurations received:` message.  You can also see similar information using `C/C++: Log Diagnostics` with the repro'ing file open. In these places, I see the same paths as get written to `compile_commands.json`.  Can you confirm you are seeing the same information there?

**Comment by wjk** [comment]
My apologies for the lack of instructions re OpenSSL. I will endeavor to change that.

I just realized my problem: I am using a case-sensitive volume, and the paths VSCode is using are all lowercase. I’ve just retried on a normal volume and all is well.
