### ISSUE TITLE
Every time I create and save a new C document, I get EBUSY: Resource busy or locked

### ISSUE THREAD

**Issue by sonicbhoc** [microsoft/vscode-cpptools#1150]
This was a bug I encountered in earlier versions of VS code that was fixed for a while, but has come back now.

Every time I save a new C file the first time, it fails with "Failed to save ${filename}: A system error occurred (EBUSY: resource busy or locked, open ${the full file name and path}). 

Sometimes, I save the file, the message comes up, I press "retry" and it works. This was the same as it was before. But sometimes, *that* doesn't even work and I have to ***restart the entire program*** to get my new file to save. This is a problem because I'm working on a project in which pretty much all I'm doing is splitting functions into files, and it's drastically slowing everything down.

OS: Windows 7 Pro 64-bit
VS Code version : 1.18.0-Insider, commit 82dcf9835265cd0a45ec135587ae2a82673f1c8f
Also happens with 1.17.2 commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
C/C++ v.0.14.0; C/C++ clang command adapter 0.2.2; C++ Intellisense 0.2.2

**Comment by sean-mcmanus** [comment]
Oh, this looks bad. I'm not sure if it's a regression form 0.13.1, but we'll try to get a fix out soon. Changing the intelliSenseEngine to "Tag Parser" before creating the files is one workaround. We believe the issue occurs when both the tag parser and intellisense process parse the same file at the same time. Killing the Microsoft.VSCode.Cpp.IntelliSense.Msvc.exe process should also allow saving of the file.

**Comment by sonicbhoc** [comment]
Okay, and thank you for the workaround.

**Comment by sonicbhoc** [comment]
Sorry about that, I pressed the wrong button.

**Comment by sean-mcmanus** [comment]
We have a fix pending. See bug https://github.com/Microsoft/vscode-cpptools/issues/1040 . I'm closing this as a duplicate.
