### ISSUE TITLE
Support for `hipcc` compiler

### ISSUE THREAD

**Issue by SimeonEhrig** [microsoft/vscode-cpptools#11500]
### Brief Issue Summary

Normally I use the `compile_commands.json` for intelliSense, which works pretty well. In case of using AMD hip and the `hipcc` compiler or the AMD fork of `clang++` there is special behavior. The compiler adds internally, automatically the include path of the hip headers. This means I can use `#include <hip/hip_runtime.h>` with following compile command (copied from the `compile_commands.json`:

```json
{
  "directory": "/home/user/projects/MyCpp/gpu/compute_cuda_hip/build",
  "command": "/opt/rocm-5.6.1/llvm/bin/clang++  -g -std=gnu++20 -o CMakeFiles/computeCudaHip.dir/main.cpp.o -c /home/user/projects/MyCpp/gpu/compute_cuda_hip/main.cpp",
  "file": "/home/user/projects/MyCpp/gpu/compute_cuda_hip/main.cpp",
  "output": "CMakeFiles/computeCudaHip.dir/main.cpp.o"
}
```

vsc throws an error, that it cannot find the header `hip/hip_runtime.h`, which makes totally sense, because the include path is not part of the compile command. Is there an option, to add extra include paths to intelliSense? Adding the include path in the `CMakeLists.txt` is not an option, because this causes other problems.

The `CMakeLists.txt`

```cmake
cmake_minimum_required(VERSION 3.22)

project(computeCudaHip LANGUAGES HIP)

set(CMAKE_HIP_STANDARD 20)
set(CMAKE_HIP_STANDARD_REQUIRED ON)

set_source_files_properties(main.cpp PROPERTIES LANGUAGE HIP)
add_executable(${CMAKE_PROJECT_NAME})
target_sources(${CMAKE_PROJECT_NAME} PRIVATE main.cpp)
```

**Comment by SimeonEhrig** [comment]
@sean-mcmanus Can you please link the transferred issue here. I see no link and I cannot find it it the [issue section](https://github.com/microsoft/vscode-cpptools/issues).

**Comment by bobbrow** [comment]
@SimeonEhrig when an issue is transferred, GitHub does not create a new item to link to.  The URL changes as part of the transfer, so if you take a closer look you'll see vscode-cpptools in the URL now instead of vscode-cmake-tools.

**Comment by SimeonEhrig** [comment]
Thanks for clarification. I didn't know the feature.

**Comment by Colengms** [comment]
Hi @SimeonEhrig .  Normally, a gcc/clang-like compiler should indicate any include paths it will use when provided the `-Wp,-v` argument (and any other args that might influence that information).  For example:

```
clang++ -std=c++17 -m64 -Wp,-v -E -x c++  /dev/null
```

Results in the following, on my system:

```
clang -cc1 version 16.0.0 based upon LLVM 16.0.0 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13
 /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/x86_64-linux-gnu/c++/13
 /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/backward
 /usr/lib/llvm-16/lib/clang/16/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 434 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2
```

Could you try running invoking that particular clang++ to see if it's correctly returning the include path that appears to be missing from the IntelliSense configuration?  If that include path is present, this would seem to be a bug in the C/C++ Extension.  If that path is not present there, consider opening a bug against `hipcc`, requesting that they correctly reflect any include paths that are added by the compiler itself to that output.  We could consider this a feature request to add a way to arbitrarily augment include paths when using `compile_commands.json` files.  However, in this case, if the path is not returned by a compiler query command line, that would seem to be a compiler bug.

**Comment by SimeonEhrig** [comment]
I tested the current ROCm version 5.7 to be sure, that the bug is not already fixed. The bug is still there. I get following output:

```bash
/opt/rocm-5.7.0/llvm/bin/clang++ -std=c++17 -m64 -Wp,-v -E -x c++  /dev/null
clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12
 /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12
 /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward
 /opt/rocm-5.7.0/llvm/lib/clang/17.0.0/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 430 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2

```

The `hip_runtime.h` is locate in `/opt/rocm-5.7.0/include/hip/hip_runtime.h` and `/opt/rocm-5.7.0/hip/include/hip/hip_runtime.h` (deprecated).

**Comment by SimeonEhrig** [comment]
Sorry, I forgot the output of `hipcc`:

```bash
/opt/rocm-5.7.0/bin/hipcc -std=c++17 -m64 -Wp,-v -E -x c++  /dev/null
clang++: warning: argument unused during compilation: '--hip-path=/opt/rocm-5.7.0' [-Wunused-command-line-argument]
clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rocm-5.7.0/include
 /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12
 /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12
 /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward
 /opt/rocm-5.7.0/llvm/lib/clang/17.0.0/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 430 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2

```
But in the end, `hipcc` is wrapper script which calls ether `clang++` for AMD GPUs (my case) or `nvcc` for Nvidia GPUs.

**Comment by Colengms** [comment]
Hi @SimeonEhrig .  The C/C++ Extension supports querying of gcc/clang compilers, as well as nvcc.  However, based on what you've described about `hipcc`, I believe we would need to add support specifically for it.  (nvcc and clang++ are queried in very different ways by the extension).

In your case, it looks like invoking `hipcc` as your compiler instead of clang++ might work, as the missing include path (`/opt/rocm-5.7.0/include`) does appear to be returned in the output you provided.  Is there a reason why your `compile_commands.json` file doesn't refer directly to `hipcc` as the compiler?  As a work around, you might try specifying `/opt/rocm-5.7.0/bin/hipcc` in the `compilerPath` frield of `c_cpp_properties.json`.  I believe that should override only the compiler specified in `compile_commands.json`, and use the rest of the args there to correctly configure IntelliSense.  However, in order to support its integration with nvcc, we would need to add support to the extension specifically for that.  We could use this issue as a feature request to add that support.

**Comment by Colengms** [comment]
Hi @SimeonEhrig .  `c_cpp_properties.json` contains the 'base' configuration for your workspace folder.  (Though, defaults are used if this file does not exist.)  This is where you would specify that the C/C++ extension should leverage a `compile_commands.json`, using the `compileCommands` field.  These settings are also settable using equivalent `C_Cpp.` VS Code settings.

It sounds like you have a work-around, to configure the workspace folder to use `hipcc` directly in `c_cpp_properties.json`, which we do appear to properly support.  (So, I'm going to make this issue no longer a 'feature request'.)

I believe the issue you encountered when trying to use the `compile_commands.json` file generated by CMake may actually be due to a bug in CMake's support of `hipcc`.  Could you confirm this, by attempting to compile files (with dependencies on the 'missing' include directory) using a command line from that `compile_commands.json`?  I suspect CMake is incorrect outputting `clang++` command lines when it should be outputting `hipcc` command lines.  Or, if that is intentional, it should be providing new `-I` args for any include path that `hipcc` would have implicitly added when run directly.

Let me know if that sounds correct to you.  If so, I will close this issue as external.

**Comment by SimeonEhrig** [comment]
`hipcc` is adding the argument `-isystem /opt/rocm-5.7.0/include`. If found it out, when I executed the command `hipcc -### -std=c++17 -m64 -Wp,-v -E -x c++  /dev/null`:

```bash
hipcc -### -std=c++17 -m64 -Wp,-v -E -x c++  /dev/null
AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.7.0 23352 d1e13c532a947d0cbfc94759c00dcf152294aa13)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.7.0/llvm/bin
clang++: warning: argument unused during compilation: '--hip-path=/opt/rocm-5.7.0' [-Wunused-command-line-argument]
 (in-process)
 "/opt/rocm-5.7.0/llvm/bin/clang-17" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-E" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "null" "-mrelocation-model" "static" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/home/simeon" "-resource-dir" "/opt/rocm-5.7.0/llvm/lib/clang/17.0.0" "-isystem" "/opt/rocm-5.7.0/include" "-v" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward" "-internal-isystem" "/opt/rocm-5.7.0/llvm/lib/clang/17.0.0/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-O3" "-std=c++17" "-fdeprecated-macro" "-fdebug-compilation-dir=/home/simeon" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "-" "-x" "c++" "/dev/null"
```
With the knowledge, I modified a `CMakeLists.txt`, that the `clang++` compile command contains the `/opt/rocm-5.7.0/include`. Using `hipcc` insteand `clang++` as `CMAKE_HIP_COMPILER` was not possible, because this throws an error in CMake, that only `clang++` and `nvcc` are possible values for`CMAKE_HIP_COMPILER`.

```cmake
cmake_minimum_required(VERSION 3.27)

project(hipcc_test LANGUAGES HIP CXX)

set_source_files_properties(main.cpp PROPERTIES LANGUAGE HIP)
add_executable(tgt_foo)
# /opt/rocm-5.7.0/include is not working, because CMake "blacklist" it in some way.
# Also a symbolic link is not working. I need to copy the whole rocm-5.7.0 folder to another location.
target_include_directories(tgt_foo SYSTEM PUBLIC "/opt/foo/include")
target_sources(tgt_foo
    PRIVATE
    main.cpp
)
set_target_properties(tgt_foo PROPERTIES
    HIP_STANDARD 17
)
```

Therefore I agree with you. It is not a bug in vscode-cpptools. I will open an issue in CMake. Ether they fix it or they upstream the issue the AMD, that they fix the compiler.

**Comment by SimeonEhrig** [comment]
Only for documentation, this should be a good workaround:

```cmake
cmake_minimum_required(VERSION 3.21)

project(hipcc_test LANGUAGES HIP)

# determine the ROCm base path and set it as -isytem compiler argument
execute_process(COMMAND hipconfig --rocmpath
    OUTPUT_VARIABLE rocm_path)
message(STATUS "ROCm SDK path: ${rocm_path}")
set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} -isystem ${rocm_path}/include")

set_source_files_properties(main.cpp PROPERTIES LANGUAGE HIP)
add_executable(tgt_foo)
target_sources(tgt_foo
    PRIVATE
    main.cpp
)
set_target_properties(tgt_foo PROPERTIES
    HIP_STANDARD 17
)
```

**Comment by bradking** [comment]
From https://github.com/microsoft/vscode-cpptools/issues/11500#issuecomment-1748417410:

> `/opt/rocm-5.7.0/llvm/bin/clang++ -std=c++17 -m64 -Wp,-v -E -x c++  /dev/null`

This doesn't print the ROCm/HIP include directory because `-x c++` tells Clang to compile as C++.  Using `-x hip` instead tells Clang to compile as HIP, and shows the expected include directory.

I tested the example from https://github.com/microsoft/vscode-cpptools/issues/11500#issue-1924722859 locally, and when CMake generates `compile_commands.json` entries for HIP sources, the compilation command lines do show `-x hip` for me.  It works with both CMake 3.22.6 and 3.27.7.

**Comment by Colengms** [comment]
Hi @bradking .  It sounds like 'hip' is its own language, similar to CUDA.  Adding support for hip appears to be more involved than addressing a missing include directory.  The C/C++ extension currently supports C, C++ and CUDA languages.  Some work would be required to support hip, similarly to how CUDA is supported.  Like CUDA, it would also require some support in VS Code itself (such as to add a language identifier and lexical grammar).  We can use this issue as a feature request to add support for hip/hipcc to VS Code and the C/C++ Extension.

**Comment by SimeonEhrig** [comment]
> Hi @bradking . It sounds like 'hip' is its own language, similar to CUDA. Adding support for hip appears to be more involved than addressing a missing include directory. The C/C++ extension currently supports C, C++ and CUDA languages. Some work would be required to support hip, similarly to how CUDA is supported. Like CUDA, it would also require some support in VS Code itself (such as to add a language identifier and lexical grammar). We can use this issue as a feature request to add support for hip/hipcc to VS Code and the C/C++ Extension.

Originally, HIP was pure C++ (I don't know if does it matter the split between host and device code for auto completion). Unfortunately AMD starts to support the ugly CUDA syntax like the special kernel launch syntax: `kernel<<<1,1>>>(d_pointer)` instead of `hipLaunchKernelGGL(hello, dim3(1), dim3(1), 0, 0, d_pointer);`. Therefore a partial HIP support which for example set the correct include paths would already help, if you avoid the cuda like syntax.
