### ISSUE TITLE
Many squiggles after update

### ISSUE THREAD

**Issue by sycorax** [microsoft/vscode-cpptools#11509]
Type: <b>Bug</b>

Just opened my current SSH project hosted remote. It is a very large C++ Linux project. Many identifier undefined warnings but ctrl+click opens their definition. Tried several Intellisense configurations with no success.
Eg:
identifier "T0" is undefined
namespace "std" has no member "string"

Extension version: 1.17.5
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.3.18-150300.59.63-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.02GB free)|
|Process Argv|--crash-reporter-id e253914c-9ece-4fcc-adc6-23f20e15b611|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: chappy3-guest2|
|OS|Linux x64 5.3.18-150300.59.63-default|
|CPUs|QEMU Virtual CPU version 2.5+ (2 x 3192)|
|Memory (System)|11.69GB (10.71GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
vscrpc:30673769
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmhint1:30842940
dsvsc015:30845448

```

</details>

**Comment by jan-vavrin** [comment]
I have also started getting similar issues with the new update. Always in the form namespace "std" has no member "...". The exact unrecognized symbols depend on the C++ version I set. (E.g., in c++11, "thread" is ok - though syntax highlighting is broken - but in later versions, "thread" is not recognised.) C++23 does not even recognise "cin" and "cout".

**Comment by sean-mcmanus** [comment]
When you run the C/C++: Log diagnostics command, does the output look correct? When did this last work for you?

@jan-vavrin What "new update" are you referring to?

**Comment by sycorax** [comment]
It last worked about a week ago. I do not track the VSC versions.
C/C++: Log diagnostics output below. I've removed the work related paths.

-------- Diagnostics - 10/11/2023, 9:29:50 AM
Version: 1.17.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
    ],
    "defines": [
        "CPIJ"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/usr/bin/clang",
    "configurationProviderInCppPropertiesJson": "ms-vscode.cmake-tools",
    "mergeConfigurations": false,
    "browse": {
        "path": [
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.17.5.0
Translation Unit Mappings:
[ ...cc ]:
    ...cc
Translation Unit Configurations:
[ ...cc ]:
    Process ID: 11340
    Memory Usage: 13 MB
    Compiler Path: /usr/bin/clang
    Includes:
    ...
        /usr/include/c++
        /usr/local/include
        /usr/lib64/clang/9.0.1/include
        /usr/include
    Defines:
        
    Standard Version: c++17
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=90001
Total Memory Usage: 13 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 68262

**Comment by adaml-at-eargo** [comment]
@sycorax, do you see yellow squiggles in your JSON C/C++ configuration file? Or do you see the C/C++ Extension switch to another compiler in the Output > C/C++ Configuration Warnings window? 

I use LLVM Embedded Toolchain for ARM with VS Code on Windows. I see similar IntelliSesnse output to you if there are issues in the configuration JSON or the extension can't understand the compiler I've specified. Or if I've manually selected the wrong compiler configuration. The output in the Output > C/C++ window can help understand why the extension isn't giving the expected results when the extension debug level is set to DEBUG.

**Comment by sean-mcmanus** [comment]
@sycorax https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.5 shipped August 28, so the issue is most likely not a change/bug with the C/C++ extension. It's most likely due to `"configurationProvider": "ms-vscode.cmake-tools",` -- we receive the project includes and defines from that extension. You may need to run `CMake: Configure`. If you can't get it to work, you might try removing that configurationProvider setting or switch to using the compileCommands setting or filing a bug at https://github.com/microsoft/vscode-cmake-tools/issues if you believe they're sending us the wrong configurations for you project.
