### ISSUE TITLE
Auto-complete ignores setting  "editor.suggest.insertMode": "insert" and always deletes the next word

### ISSUE THREAD

**Issue by n808** [microsoft/vscode-cpptools#11502]
### Environment

- OS and Version: MacOS Ventura 13.6
- VS Code Version: 1.82.3
- C/C++ Extension Version: 1.17.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Auto-complete ignores setting  "editor.suggest.insertMode": "insert" and always deletes the next word.

Steps to reproduce:
1. Set cursor before some word.
2. Start to type code
3. Select one suggestion
4. Instead of inserting suggestion at cursor, the following word is deleted and replaced by suggestion

Expected behavior:
editor.suggest.insertMode setting should be honored and suggestions inserted instead of replacing the following word.
I have set insertmode to "insert" both globally and for [c] and [cpp]. 

### Configuration and Logs

```shell
// Place your settings in this file to overwrite the default settings
{
    "editor.suggest.insertMode": "insert",
	// Configure settings to be overridden for the c language.
	"[c]":  {
		"editor.wordBasedSuggestions": false,
		"editor.suggest.insertMode": "insert",
		"editor.semanticHighlighting.enabled": true
	},

	// Configure settings to be overridden for the cpp language.
	"[cpp]":  {
		"editor.wordBasedSuggestions": false,
		"editor.suggest.insertMode": "insert",
		"editor.semanticHighlighting.enabled": true
	}
}
```

**Comment by browntarik** [comment]
Thank you for submitting this issue! This is something that we are currently looking at right now. This issue will be closed as a duplicate but you can track further updates here: https://github.com/microsoft/vscode-cpptools/issues/10613.

Thank you!
