### ISSUE TITLE
C++ Intellisense does not working anymore

### ISSUE THREAD

**Issue by kappa95** [microsoft/vscode-cpptools#11512]
### Environment

- OS and Version: Ubuntu 22.04.3 LTS (Linux x64 6.2.0-34-generic)
- VS Code Version: 1.83.0 Commit: e7e037083ff4455cf320e344325dacb480062c3c
- C/C++ Extension Version: v1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary:

Intellisense does not work anymore on older C++/ROS projects neither in newer project (folder with only C++ file).
It does not show any suggestion, never.
It does not ask to create newer Configurations and it is not possible to add configuration.

### Configuration and Logs

```shell
It is not possible to run C/C++: Log Diagnostics. It shows the error: "'Command C/C++:%c_cpp.command.logDiagnostics.title%' resulted in an error. Command 'C_Cpp.LogDiagnostics' not found."
```

**Comment by michelleangela** [comment]
@kappa95 
Does this issue only occur for that one project or does it also occur for a simple hello world project?

Could you provide more details or repro steps on what you mean by:
>It does not show any suggestion, never.
It does not ask to create newer Configurations and it is not possible to add configuration.

Could you provide any `Cpp.*` settings you have configured and also your `c_cpp_properties.json` or any IntelliSense configurations? Are you also using any providers such as `vscode-cmake-tools`?

If possible, could you get logs from the language server (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)?

**Comment by kappa95** [comment]
It happened for all the projects. To solve the problem faster I have renamed all the configuration folders and I have uninstalled everything and installed again and it seems working now.

**Comment by michelleangela** [comment]
I will close this issue for now as resolved. Please re-open if the issue re-occurs.
