### ISSUE TITLE
the output is not showing

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#11519]
Type: <b>Feature Request</b>

i have made all the necessary setting for c language code to run ,but my code output is not shown in the output window . the code runs and shows output in terminal. when in try to run it in output window it says that the active file is not a c source file. please help me resolve this issue.

Extension version: 1.17.5
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by sean-mcmanus** [comment]
Output is not supposed to go to the Output window, it's supposed to go to the Terminal as you describe. Why do you believe/want it to go to the Output window?
