### ISSUE TITLE
Feature Request: Command to reset / reload the language server

### ISSUE THREAD

**Issue by SE2Dev** [microsoft/vscode-cpptools#1152]
Currently (v0.14.0) this extension provides a command to unload the language server, but no way to restart, or reload it without actually closing and reopening VSCode. I feel that this would be relatively trivial to add and would be a valuable addition to this extension.

**Comment by sean-mcmanus** [comment]
I usually just do a Close/Open folder. We have a problem with our language server not restarting correctly after a crash or after an unload, so hopefully we can get that fixed. The Unload command kills the language client executable, but the typescript part is still running so it's not recommended to use. What is the scenario where you want to unload/reload the language server? When it's stuck? Another option may be to use the VS Code's Disable option on the extension, although it requires a reload.

**Comment by bobbrow** [comment]
Use VS Code's "Reload Window" command to restart the language server.  We should remove the Unload command from our extension.

**Comment by roberth** [comment]
@bobbrow "Reload Window" also kills running Terminals and may have other side effects.

I don't think anyone will discover this method unless they're vscode maintainers.

**Comment by bobbrow** [comment]
I am currently working on a "rescan workspace" feature that should have a similar effect.  #3658
