### ISSUE TITLE
My code will not run after pressing run, and it will show different errors at different times inconsistently

### ISSUE THREAD

**Issue by hiphop4eva** [microsoft/vscode-cpptools#11534]
### Environment

Windows 11 22H2
- GDB / LLDB version: 13.2
- VS Code version: 1.83.1

### Bug Summary and Steps to Reproduce

I have a few files of very simple codes and get very inconsistent errors when I try to run them.
There are three files called Attempt.cpp, Addition.cpp and Addition.h. These files are inside a folder called "Attempt", which is inside a folder called "C++". The C++ folder also includes another folder called .vscode which it builds on its own.
There are generally three results that appear when I try to run:
1. The program runs just fine.
2. It gives me an error saying "launch: program "Attempt.exe" does not exist". This is bizarre considering that there is a program called Attempt.exe in the same folder as Attempt.cpp.
3. It gives this error message:
"Unable to start debugging. Program path '(Path)' is missing or invalid"
"GDB failed with the message: "(Path)": not in executable format: File format not recognized."

And sometimes, after I press the run button, it gives me an error saying "The preLaunchTask 'C/C++: g++.exe build active file' terminated with exit code -1.". This error seemingly doesn't affect the result of the program, becuase sometimes the program runs just fine despite this error appearing, and other times it won't run after this error appears.

I have absolutely zero idea as to what is going on, and the program seemingly just does whatever it wants at any time. One time I tried to run it and it worked perfectly fine, and after trying it one more time without touching anything whatsoever, it started giving me an error message again. I tried a few things that I looked up online, but nothing is working.

### Debugger Configurations

```shell
Launch.json:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C/C++: g++.exe build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "Attempt.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\msys64\\ucrt64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}



tasks.json:

{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\msys64\\ucrt64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "Attempt.cpp",
                "Addition.cpp",
                "Addition.h",
                "-o",
                "Attempt.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        },
        {
            "type": "cppbuild",
            "label": "C/C++: cpp.exe build active file",
            "command": "C:\\msys64\\ucrt64\\bin\\cpp.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}




The code files below:

Attempt.cpp:

#include <iostream>
#include "Addition.h"

main() {
    std::cout << "Please enter a number ";
    int x{};
    std::cin >> x;

    std::cout << "Please enter another number ";
    int y{};
    std::cin >> y;

    std::cout << "The sum of " << x << " and " << y << " is " << Addition(x, y) << std::endl;

    return 0;
}





Addition.cpp:

int Addition(int x, int y) {
    return x + y;
}



Addition.h:

int Addition(int x, int y);
```

### Debugger Logs

```shell
Executing task: C/C++: g++.exe build active file 

Starting build...
C:\msys64\ucrt64\bin\g++.exe -fdiagnostics-color=always -g Attempt.cpp Addition.cpp Addition.h -o Attempt.exe
cc1plus.exe: fatal error: Attempt.cpp: No such file or directory
compilation terminated.
cc1plus.exe: fatal error: Addition.cpp: No such file or directory
compilation terminated.
cc1plus.exe: fatal error: Addition.h: No such file or directory
compilation terminated.

Build finished with error(s).
```

**Comment by bobbrow** [comment]
Hello there,

Sorry we missed the notification for this issue. From what you've reported it looks like you have not added `C:\\msys64\\ucrt64\\bin` to your Windows `Path` environment variable.  If you add this path to the `%Path%`, I think it will resolve most of your issues.  If you don't want to add this to your `Path`, then you will need to change the value of `"cwd"` in your `launch.json` and `tasks.json` to point to that location instead.

I also recommend removing the task that builds with `cpp.exe` as I don't believe that exe will produce a running executable for you.
