### ISSUE TITLE
Unable to find C/C++ extension's navigation database file

### ISSUE THREAD

**Issue by sandman786** [microsoft/vscode-cpptools#1153]
I am unable to get C/C++ extension navigation working for my installation of Visual Studio Code on Centos 7.
After loading a code files folder, navigation does not work.  I get following error:
"No Definition Found for ...."

I do not see anywhere in the GUI where a progress or confirmation is displayed for code database (folder is quite large).  I have looked for database file under following path
bash-4.2$ pwd
/home/xxxx/.config/Code/User/workspaceStorage
There are two folders and both empty
c3893c1ecb2e391533533e63b5b3cc79  de8cd046df78d7b4b6a760ba70d267ac

Next: changed the default location in c_cpp_properties.json file, linux section:
"databaseFilename": "/drive2/VisualCode/browse.vc.db"
No luck with finding the file there as well.
Re-installed extension multiple time with enable, no luck.

Visual Studio Version: 
Version 1.17.1
Commit 1e9d36539b0ae51ac09b9d4673ebea4e447e5353
Date 2017-10-10T14:21:18.489Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

CentOS 7 Version:
bash-4.2$ cat /proc/version 
Linux version 3.10.0-123.6.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Wed Aug 6 21:12:36 UTC 2014
bash-4.2$ 

C/C++ Extension Version:
﻿# C/C++ for Visual Studio Code Change Log
Version 0.14.0: October 19, 2017

Please let me know how to get C/C++ navigation working, that is to get the database file created first

**Comment by lazy-coder-1** [comment]
How can we compile any language program in Visual Studio Code?

**Comment by sean-mcmanus** [comment]
@akhilkathi97 This GitHub page is for the C++ extension. You can use tasks in VS Code to do compiling: https://code.visualstudio.com/Docs/editor/tasks .

**Comment by sandman786** [comment]
Hello Sean-mcmanus,

Any suggestions for me?  I don't believe any of the other issues opened about database apply to my query.  I am trying to get C/C++ extension navigation working and first thing I see is that database file is not created.  Please advise on how to get the database generated?

Thanks

**Comment by jophippe** [comment]
@sandman786 your issues are most likely related to #19. Unfortunately, we haven't been able to lower our glibc 2.18 dependency yet, which I believe CentOS 7 doesn't have. There are some workarounds in the issue I linked that you can try.

**Comment by sandman786** [comment]
@jophippe Thanks for your help! workaround seems to be working for me.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4, so the workaround is no longer necessary.
