### ISSUE TITLE
Trigger IntelliSense queue when add missing include code action inserts text

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#11549]
![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/db146385-bf25-4daf-ba6c-3cb8e63e27ec)

The squiggle still doesn't go away after it's used (works in VS)

**Comment by sean-mcmanus** [comment]
The workaround is to move your cursor to a new line and wait.

**Comment by sean-mcmanus** [comment]
I think this might be a regression (not sure where it started) -- there should be code that triggers a clean update when an edit with a newline is detected.
