### ISSUE TITLE
"Vector is not a template" error (when the vector is member in a class) should be addressed

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#11543]
![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/8bcb5d84-5d11-4bf0-b278-80d54add4768)

**Comment by browntarik** [comment]
Closed as a duplicate to https://github.com/microsoft/vscode-cpptools/issues/11541

**Comment by sean-mcmanus** [comment]
@browntarik FYI, from what I understand, this fix is not related to the duplicate.

**Comment by sean-mcmanus** [comment]
This bug repros when the vector is a member in a class and `using namespace std;` is in scope, so the fix isn't to suggest adding the `std::`.
