### ISSUE TITLE
Unable to Debug - launch: program 'enter program name, for example /Users/Ashish/Documents/C++ files/a.out' does not exist

### ISSUE THREAD

**Issue by heyAyushh** [microsoft/vscode-cpptools#1154]
* OS - macOS High Sierra 10.13
*VS Code Version 1.17.2 (1.17.2)
* c/c++ extension Version 0.14.0

it says - launch: program 'enter program name, for example /Users/Ashish/Documents/C++ files/a.out' does not exist
but it do exist as you can see in terminal

<img width="1440" alt="screen shot 2017-10-21 at 02 49 06" src="https://user-images.githubusercontent.com/17379963/31845619-480d7a0c-b620-11e7-8325-72c189f3b4f8.png">

P.S. I am a newbie

**Comment by abhatnag** [comment]
Ayush, 
What was the resolution?
