### ISSUE TITLE
cpptools at 100% CPU without touching any C/C++ files

### ISSUE THREAD

**Issue by sim642** [microsoft/vscode-cpptools#11559]
### Environment

- OS and Version: Ubuntu 22.04.3 LTS
- VS Code Version:

> Version: 1.83.1
> Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
> Date: 2023-10-10T23:45:31.402Z
> Electron: 25.8.4
> ElectronBuildId: 24154031
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Linux x64 5.15.0-78-generic

- C/C++ Extension Version: v1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary:
The spawned `cpptools` process just revs away at 100% CPU and my laptop is about to take off from just opening a single VSCode workspace. I don't even open a single C/C++ file.

Steps to reproduce:
Open VSCode, that's it!
I'm guessing there's something more going on to cause this, but I can't tell what `cpptools` is heavily working on to know what triggers it.

Expected behavior:
`cpptools` doesn't run at 100% CPU for no apparent reason.

### Configuration and Logs
No `c_cpp_properties.json`, it's an OCaml project in the workspace. I don't have "C/C++: Log Diagnostics" in the command palette.

```
loggingLevel: Debug
cpptools version (TypeScript): 1.17.5
cpptools version (native): 1.17.5.0
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
LSP: cpptools/queryCompilerDefaults (id: 1)
Querying compiler for default C++ language standard using command line: /usr/bin/clang -x c++ -E -dM /dev/null
Detected language standard version: c++14
Querying compiler's default target using command line: "/usr/bin/clang" -dumpmachine
Compiler returned default target value: x86_64-pc-linux-gnu
Compiler query command line: /usr/bin/clang -std=c17 -m64 -Wp,-v -fno-blocks -E -dM -x c /dev/null
Attempting to get defaults from C compiler in "compilerPath" property: '/usr/bin/clang'
Custom configuration provider 'Makefile Tools' registered
Compiler query command line: /usr/bin/clang -std=c++14 -m64 -Wp,-v -fno-blocks -E -dM -x c++ /dev/null
Attempting to get defaults from C++ compiler in "compilerPath" property: '/usr/bin/clang'
LSP: cpptools/queryCompilerDefaults (id: 2)
LSP: cpptools/didChangeCppProperties (id: 3)
LSP: cpptools/didChangeCppProperties (id: 4)
LSP: cpptools/pauseParsing
LSP: cpptools/clearCustomConfigurations
LSP: cpptools/clearCustomConfigurations
Code browsing service initialized
  Folder: /usr/include/ will be indexed
  Folder: /usr/lib/llvm-14/lib/clang/14.0.0/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /home/simmo/... will be indexed
Discovering files...
LSP: cpptools/clearCustomConfigurations
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /usr/lib/llvm-14/lib/clang/14.0.0/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /home/...
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: Message ignored due to no registered handler: $/setTrace
LSP: cpptools/didChangeSettings
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
Enhanced Colorization is enabled.
LSP: cpptools/resumeParsing
```

**Comment by bobbrow** [comment]
The C++ extension indexes your workspace when you first open it.  This enables navigation features like: Go To Definition, Find All References, etc.

If you would like to reduce the CPU usage (e.g. slow down the indexer, but it will take longer), you can use the Workspace Parsing Priority setting.

![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/5bd0b950-df44-4d4c-92e4-0a2060adad5e)

**Comment by sim642** [comment]
Is there some way to see what the indexer is indexing? I'm surprised this suddenly is taking so much processing and time (I haven't bothered to wait for it to terminate). Previously I never even noticed this happening with this workspace and the workspace hasn't suddenly changed to cause such drastic change. I suppose the indexing process hasn't suddenly been made much more expensive either?

**Comment by bobbrow** [comment]
Yes, you can monitor the indexer's progress by setting the Logging Level to Debug:
![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/f51465b8-c29d-4c5a-9e44-21769189629a)


Then open the Output panel and select C/C++ from the drop down:
![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/3282660b-29cd-4fa4-81fb-0a99133728e6)

You should see lots of `tag parsing file: ...` type messages scrolling by.  If it looks stuck, let us know and we can investigate whether the indexer is getting stuck on one of your files.

**Comment by sim642** [comment]
That's what I did to get the log in the original issue. That log is all I see there. There isn't even a single "tag parsing file" message.

**Comment by bobbrow** [comment]
Sorry, I missed that.  It looks like cpptools is resetting. If that's the end of the log, it sounds like we ran into either an infinite loop or an extremely expensive file enumeration.  Does your workspace folder have any symlinks back to a folder above it?  If you would be willing to [attach a debugger to the cpptools process](https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) and share a callstack, we could more quickly narrow this down.
