### ISSUE TITLE
Minimize Unrelated Test Failures during New Feature Integration

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#11556]
- Use specific assets that don't trigger unrelated features.
Ex: Avoid unimplemented functions in IntelliSense squiggles tests to prevent CDD triggering.

- If asset simplification isn't possible, turn off other features for that specific test.
Ex:  Temporarily turn off CDD to focus on IntelliSense squiggles.

Helps filter out unrelated warnings/errors.

**Comment by bobbrow** [comment]
I'm not certain that this is currently a priority.
