### ISSUE TITLE
 C/C++ dependencies: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by georgehao** [microsoft/vscode-cpptools#1155]
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (OS X)' (6525 KB) .................... Done!
Downloading package 'ClangFormat (OS X)' (740 KB) .................... Done!
Downloading package 'Mono Framework Assemblies' (4751 KB) .................... Done!
Downloading package 'Mono Runtime (OS X)' (1549 KB) .................... Done!
Downloading package 'LLDB 3.8.0 (OS X)' (19125 KB) .................... Done!

Installing package 'C/C++ language components (OS X)'

Warning: File '/Users/wuling/.vscode/extensions/ms-vscode.cpptools-0.14.0/debugAdapters/lldb/lib/python2.7/site-packages/lldb/utils/symbolication.py' already exists and was not updated.

Warning: File '/Users/wuling/.vscode/extensions/ms-vscode.cpptools-0.14.0/debugAdapters/lldb/lib/python2.7/site-packages/six.py' already exists and was not updated.

Failed at stage: removeUnnecessaryFile

TypeError: Cannot read property 'indexOf' of undefined

Finished

how to resolve?

**Comment by sean-mcmanus** [comment]
Can you uninstall the extension and make sure the ms-vscode.cpptools-0.14.0 folder is gone before re-installing it?

**Comment by georgehao** [comment]
just reinstall, its ok
