### ISSUE TITLE
Crash when running code analysis from std::regex

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11554]
I experience crashes on opening some of my C++ project files (not every file) since I've updated cpptools extension to v.1.17.0
All versions after 1.17.0  (including 1.17.0) are affected by same crash
I've disabled ALL other extensions - nothing helped
 
Attached crashstack files for 1.17.0 and 1.18.0. 
[crashstack_cpptools_1.17.0.log](https://github.com/microsoft/vscode-cpptools/files/13032365/crashstack_cpptools_1.17.0.log)
[crashstack_cpptools_1.18.0.log](https://github.com/microsoft/vscode-cpptools/files/13032366/crashstack_cpptools_1.18.0.log)

_Originally posted by @lexx-spb-ru in https://github.com/microsoft/vscode-cpptools/issues/10651#issuecomment-1769108199_

**Comment by sean-mcmanus** [comment]
@lexx-spb-ru It's crashing from the implementation of the C++ std::regex. You're on Linux, right? Can you try https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.1 and/or can you set C_Cpp.loggingLevel to "Debug" and provide the last line or so of output that appears to be from clang-tidy -- that is the output that is causing the std::regex to infinite loop and crash.

**Comment by lexx-spb-ru** [comment]
> @lexx-spb-ru It's crashing from the implementation of the C++ std::regex. You're on Linux, right? Can you try https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.1 and/or can you set C_Cpp.loggingLevel to "Debug" and provide the last line or so of output that appears to be from clang-tidy -- that is the output that is causing the std::regex to infinite loop and crash.

Yes, I'm on Linux (Debian 11). Using extension-bundled clang-tidy (it's not installed in system)
I've checked, that it's clang-tidy causing crashes (as you assumed) -  crashes go away if I set "C_Cpp.codeAnalysis.clangTidy.enabled"  to "false".

I've done what you suggested:
- installed cpptools v.1.17.1 (it's pre-release version as I see) via vscode extension manager
- set C_Cpp.loggingLevel to "Debug"
- tried to troubleshoot problem via debug output of C/C++ and catch exact cause of crash

IMO, that it's impossible to distinguish what is causing crash this way (via logs). As I see architecture of this extension is based on IPC between `cpptools` and vscode extension and things happen too quickly: last clang-tidy message in C/C++ extension log is always different.

I can say, that my project has complex structure and contains a lot of C-style headers with C-structures macros and etc. Crashes appear only when aimed-parsing of structures in header-files is executed (e.g. when I hover over some structure in my C++ code)

**Comment by sean-mcmanus** [comment]
@lexx-spb-ru We fixed a crash related to std::regex when running code analysis as part of https://github.com/Microsoft/vscode-cpptools/issues/12285 . So I believe this is fixed. Let me know if it still repros for you with the latest release.
