### ISSUE TITLE
gcc inline asm produces error even when compiler set to gcc

### ISSUE THREAD

**Issue by srobertjames** [microsoft/vscode-cpptools#11560]
### Environment

- OS and Version:  Ubuntu 22.04.3 LTS
- VS Code Version: Version: 1.82.2, Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
- C/C++ Extension Version: 1.17.5
- If using SSH remote, specify OS of remote machine:  N/A

### Bug Summary and Steps to Reproduce

Bug Summary:
`__asm volatile ( "nop" ::: "memory" );` produces `expected a ')'C/C++(18)` even though compiler is set to `"compilerPath": "/usr/bin/arm-none-eabi-gcc"`

Steps to reproduce:
See config files below
`arm-gcc` is the only defined C/C++ config, and the status bar confirms we are using it

Expected behavior:
No error

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "arm-gcc",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "cStandard": "c23",
            "cppStandard": "gnu++20",
            "intelliSenseMode": "linux-gcc-arm",
            "compilerPath": "/usr/bin/arm-none-eabi-gcc"
        }
    ],
    "version": 4
}
```

```
{
    "files.associations": {
        "inttypes.h": "c",
        "stdbool.h": "c",
 ...
   },
    "cortex-debug.variableUseNaturalFormat": false,
    "C_Cpp.default.compileCommands": "build/dbg/compile_commands.json"
}
```

# `compile_commands.json`
```
[
  {
    "directory": ...
    "command": "arm-none-eabi-gcc ... -../../src/main.c",
    "file": "../../src/main.c",
    "output": "....p/src_main.c.o"
  },

```
```


### Other Extensions

_No response_

### Additional context

_No response_

**Comment by srobertjames** [comment]
The error seems to not always show right away.  Then, for no apparent reason, it shows.  Then, later, for no apparent reason, it sometimes disappears.  I'm not sure if this is just time passing (e.g. cache updates) or the fact that I've been changing other vscode settings somehow triggers a rescan.

Also: If I have the `compile_commands.json` point to GCC, do I still need the `c_cpp_properties.json` settings as above?

**Comment by srobertjames** [comment]
The squiggles went away, and now came back, even though I haven't edited those lines! At one point there was a notification that it couldn't parse `compile_commands.json` and was using `c_cpp_properties.json` instead.

**Comment by srobertjames** [comment]
Even making no changes to the codebase, and just opening and close the file in vscode, can cause it to go from green to red or red to green.

Perhaps it is switching between the configured arm-gcc and, for some reason, clang?

**Comment by srobertjames** [comment]
Looking at this further, I think there were two independent issues:

1. The `c_cpp_properties.json` file was set to the c23 std, not gnu c std, which handles `asm` differently
2. For some reason, sometimes vscode would produce use the c23 std `c_cpp_properties.json`  file, and sometimes it would use the `compile_commands.json`, which did not produce those errors.  vscode would therefore alternate (or sometimes show both) which messages, errors, and warnings it shows.

**Comment by sean-mcmanus** [comment]
@srobertjames Sorry for the delayed response -- do you think our extension has a bug still?

**Comment by srobertjames** [comment]
Well, I believe the above shows it acts irregularly under certain configurations.  Whether that's a bug or a feature is perhaps a design question?
