### ISSUE TITLE
Restrict intellesense to specific directories

### ISSUE THREAD

**Issue by duaneellissd** [microsoft/vscode-cpptools#11572]
### Environment

- OS and Version: LINUX
- VS Code Version: 1.82.2
- C/C++ Extension Version: 1.17.5
- If using SSH remote, specify OS of remote machine: - local machine.

### Bug Summary and Steps to Reproduce

Bug Summary:
Need to restrict where Intellisense searches for definitions.

Steps to reproduce:
Construct a source directory structure like this:

board_FOO/src/-- various C files
board_FOO/include/-- Various header files

Create mulitple board_BAR, and board_XYZ and board_ABC with simular, to almost exact filenames
and simular to almost exact #defines in these files.

For instance:  board_FOO/include/board.h  has:  #define CPU_CLK_FREQ_MHZ   50
But board_BAR/include/board.h has #dfeine CPU_CLK_FREQ_MHZ  100

Using intellisense, it just scans *ALL* directories and is finding a dozen or so different "board.h" files.
what file can I create to list the places that Intellisense *SHOULD* examine?

ie: If I am working on project_FOO, then intellisense should examine board_FOO (and sub directories), and not board_BAR or board_XYZ, or board_ABC.

Expected behavior:

### Configuration and Logs

```shell
not sure what to put here.
```

### Other Extensions

n/a

### Additional context

n/a

**Comment by Colengms** [comment]
Hi @duaneellissd .  There are existing features that can be used to restrict what files are scanned into the 'browse' database used internally by the C/C++ Extension.  The `browsePath` field in a `c_cpp_properties.json` configuration can be used to specify exactly what set of directories to use.  The VS Code settings for `files.exclude` is also honored, as well as an equivalent `C_Cpp.files.exclude` that applies only to the C/C++ extension.  Does one of these address your scenario?

**Comment by arathburgos05** [comment]
@Colengms 

Hello, I'm looking for a similar feature.

I have my multi-workspace set. I tried with 'C_Cpp.files.exclude' but this didn't work. Is there any special requirement? Does it support glob patterns? I tried also reestarting my workspace and resetting the Intellisense database.

Currently, I'm using 'c_cpp.includePath' to include the needed header paths. Tomorrow I'll try with 'browsePath' field in a 'c_cpp_properties.json' (I don't have it but I can try to configure it).

Do you know if there is any way to exclude a specific file or folder completely from intellisense but not from workspace?

Regards.
