### ISSUE TITLE
Error in installation of mingw-w64-x86_64-toolchain

### ISSUE THREAD

**Issue by VBhat20** [microsoft/vscode-cpptools#11578]
I´m facing the error attached in the screenshot while the installation of mingw-w64. I´m not able to install the gcc compiler.

error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-ada-13.1.0-6-any.pkg.tar.zst' from mirror.iscas.ac.cn : CONNECT tunnel failed, response 407
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-objc-13.1.0-6-any.pkg.tar.zst' from mirror.iscas.ac.cn : CONNECT tunnel failed, response 407
warning: too many errors from mirror.iscas.ac.cn, skipping for the remainder of this transaction
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-fortran-13.1.0-6-any.pkg.tar.zst' from mirror.iscas.ac.cn : CONNECT tunnel failed, response 407
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-13.1.0-6-any.pkg.tar.zst' from mirror.iscas.ac.cn : CONNECT tunnel failed, response 407
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-objc-13.1.0-6-any.pkg.tar.zst' from mirrors.tencent.com : CONNECT tunnel failed, response 407
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-fortran-13.1.0-6-any.pkg.tar.zst' from mirrors.tencent.com : CONNECT tunnel failed, response 407
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-13.1.0-6-any.pkg.tar.zst' from mirrors.tencent.com : CONNECT tunnel failed, response 407
warning: too many errors from mirrors.tencent.com, skipping for the remainder of this transaction
error: failed retrieving file 'mingw-w64-ucrt-x86_64-python-3.10.11-1-any.pkg.tar.zst' from mirrors.tencent.com : CONNECT tunnel failed, response 407
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-ada-13.1.0-6-any.pkg.tar.zst' from mirrors.tencent.com : CONNECT tunnel failed, response 407
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

**Comment by Colengms** [comment]
Hi @gregvanl .  HTTP 407 errors appears to be related to proxy server authentication. Perhaps you're on a private network with a proxy server, which requires authentication that isn't configured correctly, or perhaps was experiencing an outage at the time?  I'm going to close this as external, since this is not related directly to the C/C++ Extension or documentation.
