### ISSUE TITLE
Is it possible to customize the Goto Definition behavior?

### ISSUE THREAD

**Issue by smwikipedia** [microsoft/vscode-cpptools#1157]
My C project has some special symbol resolving rules. I want to customize the Goto Definition behavior. Is it possible? How to?

**Comment by sean-mcmanus** [comment]
What special symbol resolving rules? The Go to Definition behavior is not really customizable. You can use files.exclude to remove files/folders from being targets of Go to Definition.

**Comment by smwikipedia** [comment]
I am working on the UEFI codebase. The same C function prototype can be invoked in different C files. But linked to different implementations. The linkage choice is specified by some configuration files. I hope the F12 can intelligently parsing these config files and jump to the right implementation rather than let me pick from many candidates.

**Comment by sean-mcmanus** [comment]
You could write a script that read your config files and the c_cpp_properties.json and modifies the browse.path and databaseFilename for different implementations, and then you could switch configurations to go to choose different implementation, e.g. 

`{
	"configurations": [
		{
			"name": "Implementation1",
			"defines": [
			],
			"intelliSenseMode": "msvc-x64",
			"browse": {
				"path": [
					"/path/to/implementation1"
					"${workspaceRoot}"
				],
				"limitSymbolsToIncludedHeaders": true,
				"databaseFilename": "${workspaceRoot}/.vscode/implementation1.db"
			}
		}
	],
	"version": 3
}`

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
