### ISSUE TITLE
Add missing include should handle the multi-root scenario correctly when types from the other workspace are used

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#11586]
it's adding a relative path instead of a direct path.

![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/54660328-a412-471c-875a-7d404a1f2f89)

includePath in test1 has ${workspaceFolder} and ${workspaceFolder:test2} so only "test1.h" needs to be added but it's adding "../test2/test1.h" instead.

**Comment by sean-mcmanus** [comment]
This appears to be fixed now.
