### ISSUE TITLE
Unable to add file to database.  error = -2147467259

### ISSUE THREAD

**Issue by chichihchen** [microsoft/vscode-cpptools#1158]
Hi, 

I've just installed a fresh copy of VS Code in Ubuntu 17.10.  The extension was installed successfully and it asked me to reload the windows.  So I went ahead and reload the windows to start the cpptools extension for the first time.  It downloaded all the required dependencies and it installed them successfully.  But right after it said "Finished", there were like 40 some repeating errors saying "Unable to add file to database.  error = -214746259.  Was this because the BROWSE.VC.DB not created in .vscode so the post installation could not be completed?  The version I am running is VS Code 1.17 and the extension version was 0.14.0.

I scrolled up to where it said "Finished" and took the screenshot.   

Thank You

Chi 

![screen shot 2017-10-23 at 10 07 20 pm](https://user-images.githubusercontent.com/33030310/31894205-4a6eafc4-b840-11e7-9318-a87b7ef11926.png)

**Comment by sean-mcmanus** [comment]
The errors have nothing to do with installation and we plan to change it to not run the parser until the extension is reloaded after initialization. And we should improve that message to actually show the file name that can't be added. If your databaseFilename is set to something invalid or the database is being used by another process already, then it could cause a failure.

**Comment by chichihchen** [comment]
I have not gotten a chance to modify databaseFilename just yet.  It's just happened during the installation.  So what you said was I could just ignore these errors because the installation was finished successfully.  But how do I restart the parser again after I reload the extension?  I went ahead and open a folder and save a default c_cpp_properties.json file.  It did automatically create the database file with the default filename .browse.VC.db in the workspaceStorage directory.  Would the missing files be parsed to the database again during the database re-creation?

**Comment by sean-mcmanus** [comment]
I just reproed this bug. It occurs when you install the extension without a workspace folder open. The output logging is a new feature so we're stilling working out all the kinks with it. The error messages are benign and you can ignore them.

**Comment by chichihchen** [comment]
Thank You Sean
