### ISSUE TITLE
扩展远程主机在过去 5 分钟内意外终止了 3 次。

### ISSUE THREAD

**Issue by Ericiiiiii** [microsoft/vscode-cpptools#11591]
Type: <b>Bug</b>

When you jump the code

Extension version: 1.17.5
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Connection to 'ssh-remote+az' could not be established
Remote OS version: Linux x64 5.4.0-150-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (1.94GB free)|
|Process Argv|--crash-reporter-id 0b15ed58-ca70-4493-b641-c9304cce43db|
|Screen Reader|no|
|VM|67%|

Connection to 'ssh-remote+az' could not be established

|Item|Value|
|---|---|
|Remote|SSH: az|
|OS|Linux x64 5.4.0-150-generic|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|Memory (System)|3.81GB (0.80GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
0bi6i642:30841073
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythontbext0:30864172

```

</details>

**Comment by sean-mcmanus** [comment]
Does this repro for a simple project? Are you able to provide a repro?

**Comment by sean-mcmanus** [comment]
We're tracking this issue with https://github.com/microsoft/vscode-cpptools/issues/11523

**Comment by sean-mcmanus** [comment]
@Ericiiiiii This might be a duplicate of https://github.com/microsoft/vscode/issues/186912 . Can you switch to VS Code Insiders to see if it's fixed with that?

**Comment by Ericiiiiii** [comment]
Sorry, I just saw your reply now. I didn't seem to find any similar issues after I updated the version

**Comment by Ericiiiiii** [comment]
when i use ssh to control remote computer in the vscode,it will have such errror
![无标题](https://github.com/microsoft/vscode-cpptools/assets/109200545/4a906f4e-9839-443d-8450-d7b0fe4dbadc)
local pc no found this problem,As with code, so with plug-ins,

**Comment by sean-mcmanus** [comment]
@Ericiiiiii Can you translate that error to English? Is it saying the language server crashed?

**Comment by sean-mcmanus** [comment]
@Ericiiiiii Is this https://github.com/microsoft/vscode/issues/195632 , i.e. the Remote Extension host failed message? Do you have the GitHub Copilot extension installed?

**Comment by Ericiiiiii** [comment]
i donot installer GitHub Copilot extension,it saying my c/c++ extension language error and The extended remote host has accidentally terminated 3 times in the last 5 minutes
![error](https://github.com/microsoft/vscode-cpptools/assets/109200545/aaea81cb-7247-4f54-8c7d-5639b8008313)

**Comment by Ericiiiiii** [comment]
Do these two plugins conflict when used together? when i use vscode in my local host ,it not problem ,code and plugins just the same.
