### ISSUE TITLE
No warnings shown even after adding `-Weverything` in compilerArgs

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode-cpptools#11595]
### Environment

- OS and Version: Win 11
- VS Code Version: insiders
- C/C++ Extension Version: 1.18.0
- If using SSH remote, specify OS of remote machine: NA

### Bug Summary and Steps to Reproduce

Main Issue: In the title

Bug Summary:
I am using Vscode insiders here. Below is my c_cpp_properties.json file. Please read this and then resolve my doubt, "Why i am not getting any warnings (that would have been given in terminal if i used -Weverything) here" ?

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${default}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.22000.0",
            "intelliSenseMode": "windows-clang-x64",
            "compilerPath": "C:/tools/mingw64/bin/clang++.exe",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "compilerArgs": [
                "-Weverything"
            ]
        }
    ],
    "version": 4
}

```

I have freshly installed the extension. I have only one cpp file in the directory.

<img width="390" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/54276661/045b6453-218a-4558-b8a2-3e0a1e910176">

Below in my main vscode, I am using clangd extension and it gives me warnings perfectly fine.

<img width="721" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/54276661/36fc68cc-73d6-4b10-8ba3-41348e7d0ff6">

Expected behavior:
just tell me a way to get all warnings

### Configuration and Logs

```shell
-------- Diagnostics - 10/30/2023, 3:54:35 PM
Version: 1.18.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "C://tools//mingw64//include//c++//12.2.0//x86_64-w64-mingw32/\\"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.22000.0",
    "intelliSenseMode": "windows-clang-x64",
    "compilerPath": "C:/tools/mingw64/bin/clang++.exe",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "compilerArgs": [
        "-Weverything"
    ],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "C:/tools/mingw64/bin/clang++.exe",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "C://tools//mingw64//include//c++//12.2.0//x86_64-w64-mingw32/\\",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.18.0.0
Translation Unit Mappings:
[ C:\Users\JohnDoe\testing\a.cpp ]:
    C:\Users\JohnDoe\testing\a.cpp
Translation Unit Configurations:
[ C:\Users\JohnDoe\testing\a.cpp ]:
    Process ID: 10900
    Memory Usage: 260 MB
    Compiler Path: C:\tools\mingw64\bin\clang++.exe
    Includes:
        C:\tools\mingw64\include\c++\12.2.0
        C:\tools\mingw64\include\c++\12.2.0\x86_64-w64-mingw32
        C:\tools\mingw64\include\c++\12.2.0\backward
        C:\tools\mingw64\lib\clang\14.0.6\include
        C:\tools\mingw64\x86_64-w64-mingw32\include
        C:\tools\mingw64\include
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++14
    IntelliSense Mode: windows-clang-x64
    Other Flags:
        --clang
        --clang_version=140006
Total Memory Usage: 260 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3999
Number of files parsed: 1495
```

### Additional context

I am using my compiiler from here: https://winlibs.com/
its readme:

winlibs personal build version gcc-12.2.0-llvm-14.0.6-mingw-w64ucrt-10.0.0-r2

This is the winlibs 64-bit standalone build of:
- GCC 12.2.0
- GDB 12.1
- LLVM/Clang/LLD/LLDB 14.0.6
- MinGW-w64 10.0.0 (linked with ucrt)
- GNU Binutils 2.39
- GNU Make 4.3
- PExports 0.47
- dos2unix 7.4.3
- Yasm 1.3.0
- NASM 2.15.05
- JWasm 2.12pre
- ninja 1.11.0
- doxygen 1.9.5

This build was compiled with GCC 12.2.0 and packaged on 2022-08-28.

Please check out http://winlibs.com/ for the latest personal build.

**Comment by sean-mcmanus** [comment]
@lakshits11 Warnings are not supported by IntelliSense (c_cpp_properties.json). We're tracking that with https://github.com/microsoft/vscode-cpptools/issues/828 . Warnings are only supported via running code analysis (clang-tidy) or when building.

**Comment by lakshits11** [comment]
This issue you mentioned has been opened from a long long time. Any tentative time you can tell when it will be implemented?

**Comment by sean-mcmanus** [comment]
@lakshits11 I don't know. It's not on our schedule. More upvotes could help it get on our schedule.
