### ISSUE TITLE
C block not recognized

### ISSUE THREAD

**Issue by peterhagelund** [microsoft/vscode-cpptools#11596]
### Environment

- OS and Version: macOS Sonoma 14.1
- VS Code Version: Version: 1.83.1 (Universal)
- C/C++ Extension Version: v1.17.5
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:

C/C++ extension does not recognize a C block typedef; the use of the type in e.g., a function, and invoking the block.

In a typedef like:
`typedef void(^cb)(unsigned long);`
the ^ caret is squiggled with the error "expected an identifier C/C++ (40)".

When using a type defined as above, like e.g.,:
`void gen_fib(int n, cb callback) {`
the type, cb in this case, is squiggled with the error "identifier "cb" is undefined C/C++ (20)".

When using a block of the type above, like this:
`gen_fib(n, ^(unsigned long fib) {`
the ^ caret is squiggled with the error "expected an expression C/C++ (29)".

Steps to reproduce:
1. Go to C/C++ edit configurations and add the "-fblocks" flag to the compiler settings.
2. Create a program like this:

```
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

typedef void(^cb)(unsigned long);

void gen_fib(int n, cb callback) {
    unsigned long a = 0, b = 1;
    for (int i = 0; i < n; i++) {
        callback(a);
        unsigned long tmp = a;
        a = b;
        b = tmp + b;
    }
}

int main(int argc, char *argv[]) {
    printf("How many Fibonacci numbers do you want to generate? ");
    int n;
    scanf("%i", &n);
    gen_fib(n, ^(unsigned long fib) {
        printf("%lu ", fib);
    });
    printf("\n");
    return EXIT_SUCCESS;
}
```

3. Notice the errors described above.

Expected behavior:

With the - in this case "clang" - compiler configured for C blocks, the C/C++ extension should recognize them and treat them correctly.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-arm64",
            "configurationProvider": "ms-vscode.makefile-tools",
            "compilerArgs": [
                "-fblocks"
            ]
        }
    ],
    "version": 4
}
```

### Other Extensions

- C/C++ Extension Pack
- C/C++ Themes
- Black Formatter
- CMake
- CMake Tools
- Dev Containers
- GitHub Copilot
- GitHub Copilot Chat
- Go
- isort
- Makefile Tools
- Pylance
- Python
- Remote - SSH
- Remote - SSH: Editing configuration files
- Remote - Tunnels
- Remote Development
- Remote Explorer
- reStructuredText Syntax Highlighting
- WSL
-

**Comment by sean-mcmanus** [comment]
We don't currently support -fblocks. It's a feature request tracked by https://github.com/microsoft/vscode-cpptools/issues/3636 .
