### ISSUE TITLE
Its Killing my VS Code Extention Host. Fix It !

### ISSUE THREAD

**Issue by mreshank** [microsoft/vscode-cpptools#11590]
Type: <b>Bug</b>

i was getting error as Extension host terminated unexpectedly 3 times within the last 5 minutes. I used the extention bisect and found that this program is causing all the problem. and other than c++ now things are fine... but i maily use it for c++ only , so fix it asap !

Extension version: 1.17.5
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.38GB (3.98GB free)|
|Process Argv|C:\\Mr Psiace\\EshankXpsiace\\CodeXpsiace\\Binary Tree - by Babbar --crash-reporter-id 1b7db2ae-af97-461f-8189-8b88a6c3e636|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30859726
h48ei257:30870396
pythontbext0:30864172

```

</details>

**Comment by sean-mcmanus** [comment]
We can't fix it unless we have more repro details. Does it repro for all projects? Or do you have a sample repro project that repros it? Can you set C_Cpp.loggingLevel to "Debug" and see if there is any relevant logging in the C/C++ output pane? When does the extension host terminated message appear? After opening a workspace folder? Does the bug repro with 1.18.0 (pre-release)?

**Comment by sean-mcmanus** [comment]
@mreshank It looks like another user hit this too in https://github.com/microsoft/vscode-cpptools/issues/11523 . This looks like a VS Code issue. Can you log a bug at https://github.com/microsoft/vscode/issues and tell them you already reported it on the C/C++ extension and we don't think it's our issue.

**Comment by sean-mcmanus** [comment]
@mreshank Well, looks like there's also ready a VS Code issue at https://github.com/microsoft/vscode/issues/195632 -- they blamed it on our extension so I'm trying to see if I can get them to re-open it.

**Comment by sean-mcmanus** [comment]
We're tracking this issue with https://github.com/microsoft/vscode-cpptools/issues/11523

**Comment by sean-mcmanus** [comment]
@mreshank This might be a duplicate of https://github.com/microsoft/vscode/issues/186912 . Can you switch to VS Code Insiders to see if it's fixed with that?

**Comment by mreshank** [comment]
@sean-mcmanus  i'll try insider ... and let you know...
