### ISSUE TITLE
Where can I find the vscode-cpptools source code?

### ISSUE THREAD

**Issue by smwikipedia** [microsoft/vscode-cpptools#1159]
Is this extension open-source?

**Comment by sean-mcmanus** [comment]
No, but we have plans to open source the typescript part (the javascript is visible in the extension installation folder)...no ETA on when that will be available though.

**Comment by sean-mcmanus** [comment]
The typescript part of our extension has been open sourced: https://github.com/Microsoft/vscode-cpptools . The 2 language server processes that do parsing stuff hasn't been open sourced.

**Comment by Kronuz** [comment]
What are the terms of use of those 2 language server binaries? Also, those haven't been open sourced yet?

**Comment by sean-mcmanus** [comment]
@Kronuz The license for the binaries is at https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/LICENSE.txt . They haven't been open sourced.
