### ISSUE TITLE
Don't move "Updating C/C++ dependencies" output to foreground

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-cpptools#1160]
It feels like almost every time I open VS Code Insiders with the extension installed, this output is forced to the foreground. This annoyance, plus the fact I don't use C++ often, forces me to uninstall the extension and only keep it installed when using.

The output could easily be kept in the background and only moved to the foreground when an error is detected.

![image](https://user-images.githubusercontent.com/2193314/31908118-bb72749a-b7ea-11e7-8a78-61821a7176c8.png)

**Comment by sean-mcmanus** [comment]
What about the reload pop up that appears? I would think that would be more annoying than the output window. I'm thinking maybe we should only download dependencies and require a reload when someone first uses a C/C++ project (i.e. keep our stricter activation events as default).

**Comment by Tyriar** [comment]
@sean-mcmanus that's annoying too, I'm kind of used to it at this point and that sort of thing will eventually be improved via an improved notifications system in VS Code. Any improvements to that are certainly welcome.

Hijacking the panel is a much bigger annoyance for me, I don't mind if the extension grabs new deps in the background silently though.

**Comment by sean-mcmanus** [comment]
Sounds good. We've made these changes for our next update:
1. We no longer force showing the C/C++ output channel unless the install fails.
2. We won't try to download the dependencies until our activation events are hit (C/C++ file opened, c_cpp_properties.json exists in the workspace, C/Cpp command used, etc.).
3. We no longer require an additional reload window. Instead, the reload prompt only appears if launch.json is opened and it explains that the reload is only required if you want the debugger configuration snippets.

**Comment by Tyriar** [comment]
Perfect :ok_hand:
