### ISSUE TITLE
How to disable the message: "IntelliSense-related commands cannot be executed when `C_Cpp.intelliSenseEngine` is set to `disabled`"

### ISSUE THREAD

**Issue by nmoa** [microsoft/vscode-cpptools#11600]
### Environment

- OS and Version: Windows 10 22H2 (build19045.3570)
- VS Code Version: 1.83.1
- C/C++ Extension Version: v1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary:

The following message appears in a popup after opening vscode when `C_Cpp.intelliSenseEngine` is disabled.
> IntelliSense-related commands cannot be executed when `C_Cpp.intelliSenseEngine` is set to `disabled`.

I have installed the `clangd` extension, and I'm using the C/C++ extension only for debugging. So I don't want the message to appear.
Are there any settings that should be configured to disable the message?

In my `settings.json`, the relevant settings are as follows:

```json
  "C_Cpp.commentContinuationPatterns": [
    "/*"
  ],
  "C_Cpp.doxygen.generatedStyle": "/**",
  "C_Cpp.formatting": "disabled",
  "C_Cpp.intelliSenseEngine": "disabled",
```
I have both `launch.json` and `tasks.json` in my project.

Steps to reproduce:

1. Set `C_Cpp.intelliSenseEngine` to disable.
2. Open C++ project in vscode.
3. The following message appears in a popup.
> IntelliSense-related commands cannot be executed when `C_Cpp.intelliSenseEngine` is set to `disabled`.

Expected behavior:

The message will not appear.

### Configuration and Logs
- I don't have `c_cpp_properties.json` in my project.
- I can't run `C/C++: Log Diagnostics`.
- Logs from the language server logging:

```
intelliSenseEngine is disabled
```

### Other Extensions

"ms-vscode.cmake-tools",
"llvm-vs-code-extensions.vscode-clangd",

**Comment by sean-mcmanus** [comment]
@nmoa I don't repro the issue -- the cause would be some thing is issuing a C_Cpp.* related command, possibly some other extension. The relevant code is at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/extension.ts#L390 if you wanted to debug it.

**Comment by nmoa** [comment]
@sean-mcmanus Thank you for your reply. 

> What version of CMake Tools do you have installed?

I have installed v1.15.31 (It seems to be the newest).

I noticed that I have also installed the C/C++ Themes Extension (ms-vscode.cpptools-themes) v2.0.0. Does this extension use the IntelliSense Engine?

**Comment by nmoa** [comment]
I disabled all the other extensions, and I found that the "C/C++ Advanced Lint" extension causes the message.
I'm sorry for confusing. I will close this issue.
