### ISSUE TITLE
Collapse first comment

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode-cpptools#11603]
Type: <b>Feature Request</b>

Eclipse has this neat feature where it collapses the first comment in C/C++ files.

Comments can be 
```
/*  */  multiline
/**  */ multiline
// many lines like this
///  many lines like this
```

Usually they are a mile long version/disclaimer comments.
It would be silly to create a new addon just for this, so this would be a nice little addition to this addon.

Extension version: 1.17.5
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
You can manually collapse the comment.

I assume it would be a setting that is settable per workspace folder, since only a subset of code bases have unimportant comments at the start of files, and other code bases might have important comments at the top.

**Comment by sean-mcmanus** [comment]
Unfortunately, our extension isn't able to implement this until the VS Code issue https://github.com/microsoft/vscode/issues/40338 is addressed, so you can upvote that issue.
