### ISSUE TITLE
New Possible Feature (after following the definition go back)

### ISSUE THREAD

**Issue by manathan1984** [microsoft/vscode-cpptools#1161]
A new feature idea: once one follows the declaration (using ctrl-click) then they should be able to go back where they were (for example with alt+left arrow).

**Comment by sean-mcmanus** [comment]
This is being tracked as a VS Code feature request at: https://github.com/Microsoft/vscode/issues/22739 . The current workaround is to use Go->Back (Alt+Left Arrow).
