### ISSUE TITLE
Automatically switch the newly created build task to being the default

### ISSUE THREAD

**Issue by NiclasSchwalbe** [microsoft/vscode-cpptools#11622]
### Environment

- OS and version: macOS Sonoma 14.1
- VS Code: 1.84.0 
- C/C++ extension: 1.17.5

### Bug Summary and Steps to Reproduce

Bug Summary:

With a freshly installed macOS follow that tutorial https://code.visualstudio.com/docs/languages/cpp

Create a folder name Test01
Create a main.cpp there and write:

```
#include <iostream>

int main() {
    std::cout << "Hello there" << std::endl;
}
```

Choose 

<img width="661" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/29840347/39270dca-5842-4d61-a484-eef51e18e982">

clang++ as compiler. 

Visual Studio will still choose clang to be the compiler. This however runs directly into an error, because we need clang++ to compile C++ code. 

### Debugger Configurations

```shell
-Does not apply
```

### Debugger Logs

```shell
-Does not apply
```

### Additional Information

Is this a users mistake?

**Comment by sean-mcmanus** [comment]
@NiclasSchwalbe Your screenshot shows the clang compiler highlighted -- you choosing that or the clang++ compiler below?

**Comment by NiclasSchwalbe** [comment]
Hi,

yes - I think I do:

```
{
    "configurations": [
        {
            "name": "C/C++: clang++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang++ build active file"
        }
    ],
    "version": "2.0.0"
}
```

**Comment by sean-mcmanus** [comment]
@NiclasSchwalbe Do you have a tasks.json with the "C/C++ clang++ build active file" task in it? Can you change the command from clang to clang++ in that file?

**Comment by NiclasSchwalbe** [comment]
I think I understand the problem now. (Did not was fully aware of the task.json till you mentioned it)
I first choose the normal clang wrongly and later tried the clang++ configuration.
This creates the file below, where the same label and typed are defined twice. My suspision is that thus always the first one was chosen, is that correct?

`{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: clang build active file",
            "command": "/usr/bin/clang",
            "args": [
                "-fcolor-diagnostics",
                "-fansi-escape-codes",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        },
        {
            "type": "cppbuild",
            "label": "C/C++: clang++ build active file",
            "command": "/usr/bin/clang++",
            "args": [
                "-fcolor-diagnostics",
                "-fansi-escape-codes",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
            "detail": "Task generated by Debugger."
        },
        {
            "type": "cppbuild",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}`

**Comment by sean-mcmanus** [comment]
I don't see the same labels defined in that task.json file. Do you still believe this is a bug with our extension?

**Comment by NiclasSchwalbe** [comment]
@sean-mcmanus 

I am not exactly sure. Is the user supposed to know about task.json and should not the extension just replace the task it added, when the user changes it with the "Add Debug Configuration" - Button?

Thank you for your support! 👍

**Comment by NiclasSchwalbe** [comment]
I will try to explain myself. (It entirely possible I am just dumb ;))

I tried to compile my program with the wrong configuration (clang was chosen.)
It did not work.

<img width="1791" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/29840347/bc875138-ce04-43fa-917b-a7ed0f1bc293">

I try to correct for that by clicking:

<img width="629" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/29840347/926b933b-15f7-4ee0-80ba-0e05787220e3">

launch.json pops up. I save.
I go back to main.cpp
I again hit run.

It still does not compile.

**Comment by sean-mcmanus** [comment]
@NiclasSchwalbe The "clang" build tasks is getting set as the default when it's first created and the 2nd one is not get switched as being the default automatically when it's added, so you need to manually run the Tasks: Configure Default Build Tasks command from the Command Palette and select the clang++ build task. It's possible we may be able to change it so that it automatically switch the newly created build task to the default (I'm not sure if that's desirable/expected behavior though).

**Comment by sean-mcmanus** [comment]
https://github.com/microsoft/vscode-cpptools/issues/8928 is a related discussion
