### ISSUE TITLE
A C language function is not listed in VS Code Workspace Symbols list (Ctrl+T), and Editor Symbols list (Ctrl + Shift + O)

### ISSUE THREAD

**Issue by seetharamc** [microsoft/vscode-cpptools#11623]
Type: <b>Bug</b>

A C language function is not listed in VS Code Workspace Symbols list (Ctrl+T), and Editor Symbols list (Ctrl + Shift + O)
A C language function having the definition below is not listed.

```
void funcA(void)
{
#if TEST
    if (var1 >= var2) {
        var3 = 1;
#else
    if (var4 >= var5) {
        var3 = 1;
#endif
    } else if (var5 >= var6) {
        var3 = 1;
    }
}
```

But the function is getting listed when the definition is changed like below.

```
void funcA(void)
{
#if TEST
    if (var1 >= var2) {
        var3 = 1;
        } else
#else
    if (var4 >= var5) {
        var3 = 1;
        } else
#endif
    if (var5 >= var6) {
        var3 = 1;
    }
}
```
This behavior is the same irrespective of whether the macro TEST is defined or not.

Could you fix this problem in VS Code Extension C/C++?

Extension version: 1.17.5
VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 6.2.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (15.51GB free)|
|Process Argv|--crash-reporter-id c8fb41f2-11fd-4869-bd6c-65727b2c259c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.10.26.110|
|OS|Linux x64 6.2.0-34-generic|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 3700)|
|Memory (System)|7.54GB (5.63GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc016cf:30880770
dsvsc018cf:30880895

```

</details>

**Comment by sean-mcmanus** [comment]
This is a "by design" limitation of our outline symbol parser. One potential workaround is to add something like

```cpp
#if 0
}
#endif
```

such that the `{}` are balanced regardless of the macro defines.
