### ISSUE TITLE
It is unable to load libraries.

### ISSUE THREAD

**Issue by KT-1114** [microsoft/vscode-cpptools#11625]
Type: <b>Performance Issue</b>

It shows this errors:
[{
	"resource": "/d:/C/Tree.c",
	"owner": "C/C++: IntelliSense",
	"code": "1696",
	"severity": 8,
	"message": "cannot open source file \"stdio.h\". Please run the 'Select IntelliSense Configuration...' command to locate your system headers.",
	"source": "C/C++",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 19
}]

and

[{
	"resource": "/d:/C/Tree.c",
	"owner": "C/C++: IntelliSense",
	"code": "1696",
	"severity": 8,
	"message": "cannot open source file \"stdlib.h\". Please run the 'Select IntelliSense Configuration...' command to locate your system headers.",
	"source": "C/C++",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 20
}]
please help me out.

Extension version: 1.17.5
VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz (8 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (0.69GB free)|
|Process Argv|--crash-reporter-id 1b1c5c64-e9a7-453c-b7f6-3f6c605fb10d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    97	  1084	code main
    0	    29	  1640	   crashpad-handler
    0	   101	  3300	shared-process
    0	   182	  5580	   gpu-process
    0	    40	 12420	   utility-network-service
    0	    76	 13688	fileWatcher [1]
    0	   186	 16432	window [1] (C/C++ Configurations - C - Visual Studio Code)
    0	    93	 18912	   window
    0	   151	 22148	extensionHost [1]
    0	    16	 17704	     c:\Users\Lion\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe
    0	     7	 11676	       "c:\Users\Lion\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64\bin\cpptools.exe"
    0	    16	 24160	         c:\Users\Lion\.vscode\extensions\ms-vscode.cpptools-1.17.5-win32-x64/bin/cpptools-srv.exe 17704 {0B58EB88-B99C-4D7A-9DC5-5323F9924308}
    0	    11	 21400	           C:\WINDOWS\system32\conhost.exe 0x4
    0	    11	 17260	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    79	 22164	     electron-nodejs ("C:\Users\Lion\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Lion\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=22148)
    0	   133	 25300	     electron-nodejs ("C:\Users\Lion\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Lion\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\node_modules\vscode-webhint\dist\src\server.js c:\Users\Lion\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools "Microsoft Edge Tools" --node-ipc --clientProcessId=22148)
    0	    92	 25868	window [2] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (C/C++ Configurations - C - Visual Studio Code)
|    Folder (C): 65 files
|      File types: c(30) exe(17) json(6) zip(4) cpp(1) ini(1) txt(1)
|      Conf files: tasks.json(2) launch.json(1) settings.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc018cf:30880895

```

</details>

**Comment by bobbrow** [comment]
Hello, did you try running the "Select IntelliSense Configuration" command as the error suggested?  On Windows you can open the command palette by pressing F1 or CTL+SHIFT+P. Then start typing the name of the command and it will appear.  This command will give you some options as to how to configure your workspace so that we can find stdlib.h and make IntelliSense work for you.
