### ISSUE TITLE
Source/header switch for tpp files as well as cpp files

### ISSUE THREAD

**Issue by EliasL** [microsoft/vscode-cpptools#11627]
### Feature Request

Pressing Alt+O works very well for switching between .h and .cpp files, but I can't make it work for .h and .tpp files. Could there be a setting to define header and source files? 

Example: 
```
"header extensions": {
    ".h",
    ".hpp"
}, 
"source extensions": {
    ".c", 
    ".cpp", 
    ".tpp"
}
```

**Comment by sean-mcmanus** [comment]
We're tracking this with https://github.com/microsoft/vscode-cpptools/issues/4608 .
