### ISSUE TITLE
Warnings are shown only for recently changed/added source lines, but not for old

### ISSUE THREAD

**Issue by itxs** [microsoft/vscode-cpptools#11636]
### Environment

Version: 1.84.0 (user setup)
VSCode C/C++ Extension version: v1.18.1
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Bug Summary and Steps to Reproduce

Sometimes (its hard to understand when it was started and under what circumstances), clang-tidy.exe v17 based code analysis, shows code warnings problems only for those lines that was recently changed, even after saving the file. The old lines remains without warnings highlighting, even though they have exactly the same code problems, like, for example, formatting in camel case while in .clang-tidy file there is requirement to be snake case, etc.
You can even change the old line somehow, leaving the issue, and the warning will appear. But once you do Ctrl-Z, or just manually delete your changes, then save file again, the warning disappears, even though the actual issue remains.
If I press "Fix this readability-identifier-naming-problem" in popup, only recently changed lines will be fixed. The old lines remain unchanged.
As many lines I edit, as many problems shown, if they all actually have some code analysis issues, so it shouldn't be that 100- or 50- threshold problem.
Commands like "Reset intellisense database", "Restart intellisense for active file" - all dont give any effect on the problem.
If I run command "Clear all code analysis problems", the problems become cleared. Then after running "Run code analysis on active file", problems again shown but still only for recently changed lines. I turned the logging verbosity of extensions to Debug and have seen this:

It looks like only changes are sent to the server, thus only changes are sent to clang-tidy. Is it correct?
If yes, the case where we lost "zero coordinate" by working only with changes may occur, and clang-tidy may lost old context.

### Configuration and Logs

```shell
Checking for syntax errors: C:\Users\...\myawesomesourcefile.c
Queueing IntelliSense update for files in translation unit of: C:\Users\...\myawesomesourcefile.c
idle loop: reparsing the active document
sending 1 changes to server
Checking for syntax errors: C:\Users\...\myawesomesourcefile.c
Queueing IntelliSense update for files in translation unit of: C:\Users\...\myawesomesourcefile.c
Error squiggle count: 0
Update IntelliSense time (sec): 0.587
```

**Comment by sean-mcmanus** [comment]
@itxs With a file that is supposed to show clang-tidy warnings, but does not, can you look at the C/C++ debug logging and see if you see the warning in the debug logging? clang-tidy is running on files from the disk. I'm not sure how our extension could be causing this issue. It's possible it may repro when running clang-tidy via the command line.

The "Checking for syntax errors..." logging is unrelated and is for the IntelliSense errors.
