### ISSUE TITLE
Switching configurations doesn't correctly automatically rescan the browse.path after a configuration change

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11649]
It currently only does a rescan if the browse.path or compilerPath settings are different, so if compile_commands.json results in a different browse.path it's not rescanned.

The workaround is to run C/C++: Rescan Workspace.

I hit this bug while testing the fix for https://github.com/microsoft/vscode-cpptools/issues/11631 .

**Comment by AnElectricalEngineer** [comment]
Doesn't the C++ extension only used compile_commands for intellisense, and not for code browsing? How can "compile_commands.json result in a different browse.path"?
