### ISSUE TITLE
MSVC setup flow seems to encourage breaching the build tools license?

### ISSUE THREAD

**Issue by dead-claudia** [microsoft/vscode-cpptools#11646]
Link: https://code.visualstudio.com/docs/cpp/config-msvc

**Important: consult with your internal legal team on this.**

Per https://visualstudio.microsoft.com/license-terms/vs2022-ga-diagnosticbuildtools/

> 1. INSTALLATION AND USE RIGHTS.
>     a. You may install and use any number of copies of the software to use solely with Visual Studio Community, Visual Studio Professional, and Visual Studio Enterprise (collectively, “Visual Studio Products”), to develop and test your applications; and
>     b. Build Tools additional use right. Regardless of whether you have a Visual Studio license as described above, you may install and use copies of the software to compile and build C++ components that both have been released by their owner under an open-source software license approved by the Open Source Initiative and are reasonably required to build your applications (“Open Source Dependencies”).
>         i. You may not use the software pursuant to subsection (b) to develop and test the Open Source Dependencies, except, and only to the extent, minor modifications are necessary so that the Open Source Dependencies can be compiled and built with the software.

The program being developed in the guide is very much not assembling a subcomponent or dependency, and VS Code is not in the list of products as defined in 1.a.

**You should contact your legal team to get this sorted out and clarified as soon as possible.** It's even raised some alarms in https://law.stackexchange.com/questions/49477/microsoft-c-build-tools-2019-not-allowed-for-use-with-visual-studio-code for the apparent legal contradiction. (This issue has existed since at least the 2019 version.)

I believe the intent is the following, based on what I see elsewhere in various Microsoft sites:

1. The phrase "use solely with" is very broad, encompassing not just direct use, but also coexistence with.
2. The "Open Source Dependencies" section was intended to allow general Windows-targeted open source library developer use without a developer license.

Both of these are considerable stretches. The first's phrasing is very non-standard, so much it's almost nonsensical. The second's section clarifies "and are reasonably required to build your applications", so it's plainly insufficient for authorizing pure library development outside the immediate scope of an end application.

**Comment by bobbrow** [comment]
I agree the language in 1.a is unclear as to the intent and will forward this feedback to our legal team for further iteration on this point to make it more clear.  I am not a lawyer, but my comments below align with all the discussions I've had with our program management and legal teams at Microsoft.

The intent of 1.a is that use of the Visual Studio Build Tools require you to have a license to one of the 3 Visual Studio SKU's listed (Community, Pro, Enterprise).  That is what the "solely with" clause is supposed to mean.  It means you cannot use the Visual Studio Build Tools without owning a license to one of the 3 SKUs listed.  This is supported by the language in 1.b which states "Regardless of whether you have a Visual Studio license as described above."

As anyone who has used the Visual Studio Build Tools can attest, you do not generally use them within the context of the Visual Studio IDE so 1.a is nonsensical if "solely with" is interpreted to mean "within the IDE itself".  You generally use them on the command line or as part of a build server. Visual Studio Code is a newer environment in which the use of the Build Tools is also approved, so long as the user owns a license to one of the 3 SKUs mentioned in 1.a or satisfies the conditions of 1.b.

When using the Visual Studio Build Tools you are expected to operate within the terms of the rights that you qualify for.  For example: if you own a Community license, your rights to use the Visual Studio Build Tools for your projects are governed by the terms of that license.  If you are working with open source software and do not have a Visual Studio license, you would be governed by the terms of 1.b.

We tried to make this point more accessible to readers of the Getting Started documentation you linked by summarizing the requirements in the following note, though I think this could be improved as well to include "configure IntelliSense" as one of the approved usages of the Build Tools:
> Note: You can use the C++ toolset from Visual Studio Build Tools along with Visual Studio Code to compile, build, and verify any C++ codebase as long as you also have a valid Visual Studio license (either Community, Pro, or Enterprise) that you are actively using to develop that C++ codebase.

Thank you for bringing this to our attention.

**Comment by bobbrow** [comment]
The license for the Visual Studio build tools has been updated: https://visualstudio.microsoft.com/license-terms/vs2022-ga-diagnosticbuildtools/
