### ISSUE TITLE
gcd function in MSVC

### ISSUE THREAD

**Issue by ethanolboi** [microsoft/vscode-cpptools#11655]
### Feature Request

The __gcd function is very useful, especially in competitive programming. But it seams like it's not included in MSVC. 
![image](https://github.com/microsoft/vscode-cpptools/assets/125242504/89252e40-a544-4938-99d8-fba94887c98d)

Please include the function

**Comment by sam20908** [comment]
That is not a standard function, thus MSVC has no obligation to have it.
Look at `std::gcd` which is standardized
