### ISSUE TITLE
Function parameters tooltip goes away once you start adding parameters.

### ISSUE THREAD

**Issue by rdlaner** [microsoft/vscode-cpptools#1165]
Windows 10
VS Code Insiders 1.18.0
C/C++ extension version: 0.14.0

When I start a function call, the extension gives a tooltip for completing the function parameters:
![image](https://user-images.githubusercontent.com/17415937/31966661-3ad8ea90-b8c0-11e7-942e-d21adc2296a1.png)

However, as soon as the first parameter is added, the tool tip goes away. Is there any way/hot-key to invoke the tooltip again so that I can complete the function invocation? Ideally, it wouldn't go away at all.

**Comment by sean-mcmanus** [comment]
@rdlaner Yeah, the parameter hint isn't supposed to go away until all the parameters are added (maybe the template is messing it up). You can try to use Ctrl+Shift+Space after the starting ( to reinvoke the signature help. I'm not able to repro this bug, so if you can provide a repro that would help to fix it (a normal template method didn't repro the issue for me). We do some special case parsing, so it's probably some special character in your argument list that is messing it up.

**Comment by rdlaner** [comment]
@sean-mcmanus I did a few more tests and found that the parameter hint sticks around if I am adding POD types, but if I need to dereference a pointer or access a member variable or use the scope operator the hint goes away after adding one of those types of parameters.

Does the hint stick around for you if you try any of those parameter types?

**Comment by sean-mcmanus** [comment]
Yes, I'm able to repro this now -- the signature help is disappearing whenever a ":" or ">" is used. This might be a VS Code bug, but we'll need to investigate more to be sure.

**Comment by sean-mcmanus** [comment]
Yes, I've verified that these are bugs with our extension code (I believe regressions starting in 0.13.0 when we made changes to the signature help implementation). Thanks for reporting this issue. The "identifier:" bug only repros with the "Default" IntelliSense engine, but the other bug also repros with the Tag Parser. We should be able to fix this.

**Comment by rdlaner** [comment]
Great, thanks @sean-mcmanus !

**Comment by bobbrow** [comment]
This should be fixed with version 0.14.3
