### ISSUE TITLE
MacOS C language   `NULL`  tips `identifier "__null" is undefinedC/C++(20)`

### ISSUE THREAD

**Issue by au-top** [microsoft/vscode-cpptools#11665]
### Environment

- OS and Version:  MACOS 14.0 arm64 
- VS Code Version: 
```
Version: 1.85.0-insider (Universal)
Commit: f346494c77e1245505e53a2ddcab3bfb4ee52e08
Date: 2023-11-09T05:36:20.154Z (3 days ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```
- C/C++ Extension Version: v1.18.2 Pre-Release
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

**test.c**
  `NULL`  tips `identifier "__null" is undefinedC/C++(20)`

Steps to reproduce:

create c file. example `a.c`

input code ` void* a=NULL;`

Expected behavior:

not any error 

### Configuration and Logs

```shell
my config


{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-arm64",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}
```

### Other Extensions

-

**Comment by sean-mcmanus** [comment]
@au-top NULL is not defined by the C language -- it requires `#include <stddef.h>` -- are you using that?

Does the issue repro with 1.17.5?
