### ISSUE TITLE
Incorrect include statement insertion in Add Missing Include for MacOS

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#11672]
![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/714dafd7-6907-4bc8-a5f3-3489cbab3021)

The include statement "#include "test.h"" is inserted under main()

**Comment by H-G-Hristov** [comment]
@browntarik  On `macOS` I experienced all sorts of garbage replacements such as:
- includes of internal headers of libc++, instead of the real header
- GTest headers 
```
#include <gmock/gmock.h>
#include <gtest/gtest.h>
```
Were replaced by internal implementation headers....

Etc.... a lot of false results.

**Comment by sean-mcmanus** [comment]
@H-G-Hristov There is special case code for C/C++ system headers and this issue tracks special handling of frameworks. Can you give an example of a unknown type/function that triggers an internal libc++ header? Handling other external libraries like gmock/gtest would probably require a setting that mapped types to headers.

**Comment by Zingam** [comment]
@sean-mcmanus My quick two cents: I think even the above screenshot is such an example "_types.h".

**Comment by H-G-Hristov** [comment]
@sean-mcmanus  Resolving:

```c++
namespace {

constexpr auto kTimeout = 30s;

}  // namespace
```

results in: `#include <__chrono/duration.h>`

```c++
#include <__chrono/duration.h>

#include <chrono>
...
```

**Comment by H-G-Hristov** [comment]
On this screenshot two headers are getting an error message: "these headerse are not used directly". But others don't.
I am using the `fmt` library which is imported via conan, and the other header is in a git submodule. 

![Screenshot 2023-11-21 at 11 09 16](https://github.com/microsoft/vscode-cpptools/assets/47526411/e2ab2d28-6ba5-466d-98c5-fa3584c0fb27)

Executing the fix command on a GTest macro imported via conan results in:

![Screenshot 2023-11-21 at 11 15 34](https://github.com/microsoft/vscode-cpptools/assets/47526411/d4932150-9907-43ca-9d90-9749dad6ca30)

**Comment by browntarik** [comment]
@H-G-Hristov Could you please follow-up with more information in this issue: https://github.com/microsoft/vscode-cpptools/issues/11741

That will help diagnose the problem you are facing.
