### ISSUE TITLE
Error squiggles not working when open single cpp file

### ISSUE THREAD

**Issue by Haizs** [microsoft/vscode-cpptools#1167]
VS Code 1.17.2, macOS 10.13, C/C++ extension 0.14.0

```
IntelliSense Engine = Default.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
Unable to determine real path of . Error = 2
  Folder: /usr/local/include/ will be indexed
  Folder: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/ will be indexed
  Folder: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/ will be indexed
  Folder: /usr/include/ will be indexed
Checking for syntax errors: file:///Users/haizs/Documents/code/test.cpp
Discovering files...
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/
  Processing folder (recursive): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/
  Processing folder (recursive): /usr/include/
  Indexing: 16451 file(s) processed
  Indexing: 1 file(s) removed from database
Done discovering files.
Parsing open files...
Checking for edits and parsing remaining files...
  Indexing: 0 file(s) processed
Done parsing remaining files.
Done parsing open files.
```

And if open folder, it works fine.

```
IntelliSense Engine = Default.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: /usr/local/include/ will be indexed
  Folder: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/ will be indexed
  Folder: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /Users/haizs/Documents/code/ will be indexed
Discovering files...
  Processing folder (recursive): /usr/local/include/
Checking for syntax errors: file:///Users/haizs/Documents/code/test.cpp
  Processing folder (recursive): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/
  Processing folder (recursive): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /Users/haizs/Documents/code/
  Indexing: 16505 file(s) processed
  Indexing: 0 file(s) removed from database
Done discovering files.
Parsing open files...
Checking for edits and parsing remaining files...
  Processing folder (recursive): /Users/haizs/Documents/code/
Done parsing open files.
Unable to finalize updates for file. error = -2140930043
  Indexing: 54 file(s) processed
Done parsing remaining files.
```

**Comment by jophippe** [comment]
Yup, I can repro this. Looks like we aren't parsing the . folder correctly (Hence the "Unable to determine the real path of ."), ~~so the currently opened file never gets indexed or parsed~~. Thanks for reporting this.

Edit: Forgot that open files are always parsed, so that shouldn't be an issue. see my comment below

**Comment by jophippe** [comment]
Oh wait, squiggles are working in Linux even with that same error. Just to check, are you getting the green squiggles under your includes? Also, do you get the message "Failed to read response from server" when editing the open file? That message was why squiggles disappeared when I tested on Mac

**Comment by Haizs** [comment]
Oh I forget to mention that I have `"C_Cpp.intelliSenseEngineFallback": "Disabled"` in my settings.json. 

And if I include a wrong file it has red squiggle under it.

<img width="1552" alt="2017-10-26 16 26 45" src="https://user-images.githubusercontent.com/5794171/32043199-9b0e82e6-ba6c-11e7-9a71-a9f7c88f14d1.png">

And after removing the wrong include and editing the file, it just shows checking again and again.

<img width="1552" alt="2017-10-26 16 28 32" src="https://user-images.githubusercontent.com/5794171/32043265-d3f6ee86-ba6c-11e7-86bb-d42aff3fc457.png">

---

Well I found that if I remove the FallbackDisabled setting, it seems couldn't resolve includes even if the includes are right.

<img width="741" alt="2017-10-26 16 37 06" src="https://user-images.githubusercontent.com/5794171/32043273-ded0cab6-ba6c-11e7-984c-28c1a63d7fa1.png">

```
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
Unable to determine real path of . Error = 2
  Folder: /usr/local/include/ will be indexed
  Folder: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/ will be indexed
  Folder: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/ will be indexed
  Folder: /usr/include/ will be indexed
Checking for syntax errors: file:///Users/haizs/Documents/code/test.cpp
Discovering files...
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/
  Processing folder (recursive): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/
  Processing folder (recursive): /usr/include/
  Indexing: 16926 file(s) processed
  Indexing: 1 file(s) removed from database
Done discovering files.
Parsing open files...
Checking for edits and parsing remaining files...
  Indexing: 0 file(s) processed
Done parsing remaining files.
Done parsing open files.
Checking for syntax errors: file:///Users/haizs/Documents/code/test.cpp
Checking for syntax errors: file:///Users/haizs/Documents/code/test.cpp
Checking for syntax errors: file:///Users/haizs/Documents/code/test.cpp
```

And now adding the wrong include it can also shows green squiggles.

<img width="861" alt="2017-10-26 16 38 47" src="https://user-images.githubusercontent.com/5794171/32043295-f16a7514-ba6c-11e7-8166-8e0f1cae2daf.png">

------

Errrrr it says includes don't resolve also when opening folder. 

<img width="1199" alt="2017-10-26 17 04 03" src="https://user-images.githubusercontent.com/5794171/32044377-f4746550-ba6f-11e7-830f-a0fd7d7f9522.png">

**Comment by bobbrow** [comment]
Responding to each of your pictures:
1. It looks like this is the bug. Seems to only happen when you don't have a folder open.  I see the same thing on my PC. We'll investigate.
2. This is the expected behavior. We check for errors as you type.
3. That message basically means `C_Cpp.intelliSenseEngineFallback == "Enabled"`
4. This is the expected behavior. When fallback is enabled, we show unresolved includes as green squiggles and we disable all red squiggles in the file.
5. Same as (3)

**Comment by Haizs** [comment]
Well I set "6" as "C_Cpp.loggingLevel" and I found the errorSquiggles count right in output.
Is there a `textDocument/codeAction` missing when don't have a folder open?

![image](https://user-images.githubusercontent.com/5794171/37075262-f5bb5960-220b-11e8-9e29-d2ed554e1a35.png)
![image](https://user-images.githubusercontent.com/5794171/37075258-f0b79744-220b-11e8-8778-c747d34cc73f.png)

**Comment by bobbrow** [comment]
When you don't have a folder open, we intentionally don't show the squiggles because users can't configure the include path for single files right now and people would get upset seeing squiggles that they can't fix.  IntelliSense should work for the symbols that we are able to resolve though.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
