### ISSUE TITLE
WPARAM is undefined 

### ISSUE THREAD

**Issue by hopjoppes** [microsoft/vscode-cpptools#1168]
I have included the correct header files i.e windows.h and even when i peek at the definition or go to the definition in my file,  it takes me to the correct file i.e windef.h where it shows me typedef UINT_PTR WPARAM however WPARAM is underlined in Parameters of function implementation as undefined and asks me to add file destination in include for properties of project , but the include paths already contain everything that is needed  

"name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include",
                "C:/MinGW/include",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include"

**Comment by jophippe** [comment]
Since you're using MinGW, check out https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md. There are some specific includes and defines that need to be there in order to make MinGW happy. Let us know if you're still having this issue after adding those.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
