### ISSUE TITLE
1.18.3 fails to activate with older VS Code versions

### ISSUE THREAD

**Issue by xizhan0513** [microsoft/vscode-cpptools#11680]
### Environment

- OS and Version: win10 x64 version 10.0.19045.2728
- VS Code Version: 
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

- C/C++ Extension Version: 1.18.3
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
when C/C++ extension Version is 1.18.3, go to definition function cannot be used
When I roll back the version to 1.17.5, go to definition function available

### Configuration and Logs

```shell
1
```

**Comment by blueWALL-E** [comment]
I had the same problem as you, and after switching to a lower version, the situation improved.

**Comment by utkuucak** [comment]
Having a similar problem. Contextual options such as `Go to definition` or `Go to declaration` when right clicking a function name does not appear.

Outline tabs says *No symbols found in document \<filename\>.c*.

**Comment by sean-mcmanus** [comment]
It looks like @tmedicci is seeing the extension fail to activate -- is everyone seeing that? i.e. does all extension functionality not work, or it just a problem with symbols (go to def)? Assuming the extension activates, does doing a C/C++: Reset IntelliSense Database command fix the issue?

**Comment by tmedicci** [comment]
> It looks like @tmedicci is seeing the extension fail to activate -- is everyone else seeing that too? i.e. does all extension functionality not work, or it just a problem with symbols (go to def)? Assuming the extension activates, does doing a C/C++: Reset IntelliSense Database command fix the issue?

It's exactly that. No functionality is available because the extension fails to initialize. No command works (including `Reset IntelliSense Database` ). Downgrading to the last version prior the newest one "solves" it.

**Comment by dpkrxl** [comment]
Got error: [Uncaught ReferenceError: node is not defined] for c++ extension so extension was not getting activated at all. Updated VSCode to latest 1.84.2 and all is fine now!

**Comment by tmedicci** [comment]
> Does anyone have any idea what is "special" about your setup, i.e. why our team isn't able to repro this?
> 
> Our team is testing with the latest VS Code 1.84.2 or the latest Insiders -- it looks like one person has 1.79.2 -- is everyone else using an older VS Code version. FYI, older VS Code versions don't have security issues fixes, so it's recommended to upgrade, e.g. [microsoft/vscode#192906](https://github.com/microsoft/vscode/issues/192906).
> 
> i.e. if that's the issue, then the potential "fix" would be to ship 1.18.4 with a higher VS Code dependency, so if you can't upgrade your VS Code version, then using 1.17.5 is the recommended workaround.

I'm using Manjaro and I was building VS Code. Updating it to the latest version fixed it.

**Comment by aharonamir** [comment]
Got the same error: **"ReferenceError: fetch is not defined"**, updated to the latest vscode, reinstalled extensions and now it works fine.

**Comment by musteresel** [comment]
I have that issue, too:

~~~
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.5.6
~~~


~~~
2023-11-14 21:35:08.336 [error] Activating extension ms-vscode.cpptools failed due to an error:
2023-11-14 21:35:08.336 [error] ReferenceError: fetch is not defined
	at Object.preReleaseCheck (/home/musteresel/.vscode/extensions/ms-vscode.cpptools-1.18.3-linux-x64/dist/src/main.js:53947:26)
	at activate (/home/musteresel/.vscode/extensions/ms-vscode.cpptools-1.18.3-linux-x64/dist/src/main.js:93776:26)
	at async p.n (/nix/store/jxjlqqrld7dilz5nhdflqy3cskyrs9pj-vscode-1.81.1/lib/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:6206)
	at async p.m (/nix/store/jxjlqqrld7dilz5nhdflqy3cskyrs9pj-vscode-1.81.1/lib/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:6169)
	at async p.l (/nix/store/jxjlqqrld7dilz5nhdflqy3cskyrs9pj-vscode-1.81.1/lib/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:5626)
~~~

Result is no working intellisense which is quite annoying.

**Comment by musteresel** [comment]
It's this fetch: https://github.com/microsoft/vscode-cpptools/blob/e896231d882f8bac6ed451e4e58ed756c14e6b1a/Extension/src/LanguageServer/extension.ts#L1184

**Comment by musteresel** [comment]
And the function with that fetch has been introduced in that commit:
https://github.com/microsoft/vscode-cpptools/commit/8fbc56a6884c5a841cb599ea7364d0cd321e439d

**Comment by sean-mcmanus** [comment]
@musteresel Thanks for the info -- that helped a lot. We have a pending fix at https://github.com/microsoft/vscode-cpptools/pull/11683

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.18.4 .
