### ISSUE TITLE
Intellisense is processing a file while editing that is protected by a compiler directive that is not defined

### ISSUE THREAD

**Issue by michael-mayes** [microsoft/vscode-cpptools#1169]
* Operating System and version

Windows 7 Enterprise Service Pack 1

    * VS Code version and if you are using the Insiders build

1.17.2 32-bit Release

    * C/C++ extension version

0.14.0

    * Other extensions you installed and if the issue persists after disabling them

Disabled C/C++ Clang Command Adapter extension and the issue persisted

Disabled all extensions other than C/C++ and the issue persisted

    * step-by-step instructions to reproduce the issue

Open a file in VSC that is protected by a compiler directive XXX_HOST_TESTING that is not defined

Nothing is seen in the Problems window on opening the file

On editing the file, either a single line or in multi-select mode, a series of warnings are seen from Intellisense after the flame icon is next displayed

![image](https://user-images.githubusercontent.com/11037231/31994471-ae7b187a-b978-11e7-9a49-df058b2c610d.png)

The warnings persist until the next flame icon is displayed after while they are cleared

I would not expect Intellisense to be processing the contents of the file as the protecting compiler directive is not set - the settings in my JSON files are for use of target console code rather than this test MFC code so I would not expect Intellisense to be able to process it, hence the protection

    * A small code sample, zipped up project, or open source repo we can use to verify the bug

//The contents of this file should only be compiled when host testing
#ifdef XXX_HOST_TESTING
    ...
    ...
    ...
#endif //End of XXX_HOST_TESTING

    * Relevant settings from your settings.json, c_cpp_properties.json, and/or launch.json files

XXX_HOST_TESTING is not defined in any .json file

    * Any log messages present in the Output window (use "C_Cpp.loggingLevel": "Information" in settings.json)

No log messages in Output window when set to Information

**Comment by michael-mayes** [comment]
If I enter Ctrl+S immediately after the edit then the flame icon that appears then does not result in these temporary warnings

So to see, make the edit and then leave it unsaved for a couple of seconds

**Comment by michael-mayes** [comment]
If I enter Ctrl+S immediately on the temporary warnings being displayed the flame icon happens immediately and clears the warnings

So the clearing down of the temporary warnings on the next automatic flame icon can be manually accelerated

**Comment by michael-mayes** [comment]
* Any log messages present in the Output window (use "C_Cpp.loggingLevel": "Information" in settings.json)

OK, I understand the Output window a bit better now, and how to display C/C++ output, but still nothing too much of interest

* Initially

IntelliSense Engine = Default.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: D:/XXX/CODE/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/UM/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/SHARED/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/WINRT/ will be indexed
  Folder: D:/TOOLS/MICROSOFT VISUAL STUDIO 12.0/VC/INCLUDE/ will be indexed
  Folder: D:/TOOLS/MICROSOFT VISUAL STUDIO 12.0/VC/ATLMFC/INCLUDE/ will be indexed

* On edit

Checking for syntax errors: file:///d%3A/XXX/CODE/XXX/XXX.cpp

* On clearing temporary warnings

Checking for syntax errors: file:///d%3A/XXX/CODE/XXX/XXX.cpp

**Comment by bobbrow** [comment]
Do you get a tooltip when you hover over the XXX_HOST_TESTING symbol on your #ifdef line?  If you do, that would explain why you are seeing squiggles and we need to figure out where this symbol is being defined.

What does your c_cpp_properties.json look like?  (e.g. are you using compile_commands.json or do you set the includePath and defines for your configuration?)

The fact that you get no squiggles until you edit the file sounds like a different bug, but I did notice that one yesterday and a fix for it will be in the next release.

**Comment by michael-mayes** [comment]
* What does your c_cpp_properties.json look like?

I have excluded a few compiler directives that are proprietary to our closed source code base, but they would not affect the inclusion of XXX_HOST_TESTING

        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}/CODE",
                "C:/Program Files (x86)/Windows Kits/8.1/Include/um",
                "C:/Program Files (x86)/Windows Kits/8.1/Include/shared",
                "C:/Program Files (x86)/Windows Kits/8.1/Include/winrt",
                "D:/Tools/Microsoft Visual Studio 12.0/VC/include",
                "D:/Tools/Microsoft Visual Studio 12.0/VC/atlmfc/include"
            ],
            "defines": [
                "_UNICODE",
                "UNICODE",
                "WIN32",
                "_DEBUG",
                "_CONSOLE",
                "_LIB",
                "CPU=PENTIUM4",
                "WIN32_LEAN_AND_MEAN",
                "WIN32_EXTRA_LEAN",
                "VC_EXTRALEAN",
                "NOGDI",
                "_CRT_NONSTDC_NO_WARNINGS",
                "_CRT_SECURE_NO_WARNINGS",
                "_WINSOCK_DEPRECATED_NO_WARNINGS"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}/CODE",
                    "C:/Program Files (x86)/Windows Kits/8.1/Include/um",
                    "C:/Program Files (x86)/Windows Kits/8.1/Include/shared",
                    "C:/Program Files (x86)/Windows Kits/8.1/Include/winrt",
                    "D:/Tools/Microsoft Visual Studio 12.0/VC/include",
                    "D:/Tools/Microsoft Visual Studio 12.0/VC/atlmfc/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }

**Comment by michael-mayes** [comment]
* Do you get a tooltip when you hover over the XXX_HOST_TESTING symbol on your #ifdef line? If you do, that would explain why you are seeing squiggles and we need to figure out where this symbol is being defined.

No tool tip for XXX_HOST_TESTING before, during or after the issue

**Comment by jophippe** [comment]
Does this happen when you add or remove a single character, like a space? I've seen behavior similar to this when I'm making a long edit, and intellisense tries to check for errors before I'm done. Since it will look at a half-edited file, it will put error squiggles under lines that are actually valid when the edit is complete. Since saving kicks off a new error check, it sees the fully edited file and gets rid of those squiggles. Although I've never seen this problem cause it to treat an undefined compiler directive as defined...

**Comment by michael-mayes** [comment]
Adding or removing a single space with a C++ // comment causes it

**Comment by bobbrow** [comment]
Sorry, I know this issue is old, but do you still have a problem with this?  Code within a disabled preprocessor block should not be evaluated by the linter.

**Comment by michael-mayes** [comment]
Hi Bob. This problem did persist for quite some time after my original report, but certainly has not shown it self in the last few months

Thanks for getting back to me and for your continued efforts
