### ISSUE TITLE
Incorrect lint with GCC option -fpermissive

### ISSUE THREAD

**Issue by NLH-FTU** [microsoft/vscode-cpptools#11690]
### Environment

- OS and Version: Microsoft Windows 10 Version 22H2 (OS Build 19045.3570)
- VS Code Version: 1.84.2
- C/C++ Extension Version: v1.18.4

### Bug Summary and Steps to Reproduce

Bug Summary:
Use of the GCC command line option "-fpermissive" option is not correctly downgrading the error with Code "C/C++ (372)" and Message "class "TEST" has no suitable assignment operator" to a warning in the case of assigning to a bit field reference.

Steps to reproduce:
1. Use the files as shown in the configurations and logs portion, substitute ... in any file path for the appropriate paths for your system.
2. Use the source file as provided. (There should total three files in the project folder).
3. Allow C/C++ Intellisense to detect errors.

Expected behavior:
The problems window should, at worst, show a warning for this code.

### Configuration and Logs

Contents of .\\.vscode\c_cpp_properties.json:
```json
{
    "configurations": [
        {
            "name": "GCC",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compilerPath": "...\\gcc",
            "cStandard": "gnu11",
            "cppStandard": "gnu++11",
            "intelliSenseMode": "windows-gcc-x64",
            "compilerArgs": [
              "-w",
              "-fpermissive"
            ]
        }
    ],
    "version": 4
}
```

Contents of .\\.vscode\tasks.json:
```json
{
	"version": "2.0.0",
	"tasks": [
    {
      "type": "cppbuild",
      "label": "C/C++: gcc.exe build active file",
      "command": "...\\gcc",
      "args": [
        "-w",
        "-fpermissive",
        "-std=gnu++11",
        "${file}",
        "-o",
        "${fileDirname}\\${fileBasenameNoExtension}.exe"
      ],
      "options": {
        "cwd": "${fileDirname}"
      },
      "problemMatcher": [
        "$gcc"
      ],
      "group": "build"
    }
  ]
}
```

Results of build:
```
Starting build...
"...\gcc" -w -fpermissive -std=gnu++11 ...\test.cpp -o ...\test.exe

Build finished successfully.
```

### Additional context

Contents of .\\test.cpp:
```c++
struct TEST {
  int a : 2;
  int b : 3;
} inline volatile& test = (*(volatile TEST*)(0xFFFF));

int main() {
  test = {1, 1};
}
```

![image](https://github.com/microsoft/vscode-cpptools/assets/149102847/a1606da9-d9ba-4a3b-aa4b-79238e2bc2ba)

![image](https://github.com/microsoft/vscode-cpptools/assets/149102847/1e48097d-1e25-4d7c-b518-715fd3e27f74)

I have also created this instructive example on godbolt.org: https://godbolt.org/z/Y77xErajT

**Comment by sean-mcmanus** [comment]
Our IntelliSense parser doesn't currently support the `-fpermissive` gcc flag.

**Comment by NLH-FTU** [comment]
That's a shame. If you need a reason to develop this feature, it would benefit the functionality of the Microsoft published extension vsciot-vscode.vscode-arduino, as the Arduino build chain invokes -fpermissive on avr-gcc during compilation.
