### ISSUE TITLE
"error: incorrectly formed universal character name" from a comment

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode-cpptools#11695]
### Environment

- OS and Version: Windows_NT x64 10.0.22621
- VS Code Version: 1.84.2 (system setup)
- C/C++ Extension Version: v1.18.4
- If using SSH remote, specify OS of remote machine: n/a

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Go to OUTPUT window "C/C++"
2. Look for error message "error: incorrectly formed universal character name"
3. Click on the file name and navigate to the line & character.
4. Line & character is inside a comment. This has happened on multiple files. Redacted example:
  tag parsing file: C:\<path>\<header>.h
    tag parsing error (this can be ignored unless symbols can't be found):
    line 35 (col. 74): error: incorrectly formed universal character name
That line contains a comment:
   Xxx xxxxxx xxxxx xxx xxxxxxxxx xxxxx xxx Xxxxxx xxxx ...\xxx_xxx_xxx\xx_xxxx\xxxxx\xx_xxxx_Xxxxxxxx_xx_xxx_xxxx_xxxxx_xxx.m
Similar seen in other places where there is a file path inside a comment
Other redacted examples:
  tag parsing file: C:\Xxxxx\XXX_XXXXX\xx_xxxxxx\xxxxxxxxx\xxx_xxxxxxxxxx.h
    tag parsing error (this can be ignored unless symbols can't be found):
    line 863 (col. 35): error: incorrectly formed universal character name
Comment on lines 862 and 863:
/* Xxxxxxxxx'x xxxxxx() xx xxxxxx xxxx, xxx xxxXX xxxxx'x xxxx xx xxxxxx_x().
   Xxxx xx xxxxxxx xx xxx_xx_xxx\xxxxx\xxxxxx_xxxxx_xxx.c */
Again a path inside a comment.
Expected behavior:

### Configuration and Logs

```shell
{
   "env": {
      "forcedInclude": [
         "${workspaceFolder}/.vscode/forced_include.h"
      ],
      "includePath": [
            "${workspaceFolder}/<redacted include path",
... lots of paths.. Note: using configuration "compile_commands Target"
            "${workspaceFolder}/<redacted include path",
     ]
   },
   "configurations": [
      {
         "name": "Win32",
         "includePath": [
            "${includePath}"
         ],
         "forcedInclude": [
            "${forcedInclude}"
         ],
         "intelliSenseMode": "windows-msvc-x64",
         "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio 16.0/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe",
         "cStandard": "c89",
         "cppStandard": "c++14"
      },
      {
         "name": "compile_commands Target",
         "includePath": [
               "${workspaceFolder}/**"
         ],
         "windowsSdkVersion": "10.0.19041.0",
         "cStandard": "c17",
         "cppStandard": "c++17",
         "intelliSenseMode": "windows-msvc-x64",
         "compileCommands": "${workspaceFolder}/.vscode/compile_commands.json"
      }
   ],
   "version": 4
}
```

**Comment by sean-mcmanus** [comment]
@BillDenton See the logging "(this can be ignored unless symbols can't be found)" -- are you seeing any missing symbols? I've seen "incorrectly formed universal character name" before and in those cases it could be ignored.

**Comment by BillDenton** [comment]
@sean-mcmanus I don't understand why the parser is tripping over something that is inside a comment. It is a very large workspace, so I don't know if there are missing symbols.

**Comment by sean-mcmanus** [comment]
@BillDenton The missing symbols would be in the Outline view of the particular document. The error is output while the parser is lexing the comment to find the end of the comment (no symbols in the comment are parsed). The error could potentially be suppressed by us instead of forwarding in our logging to avoid confusion.

**Comment by BillDenton** [comment]
@sean-mcmanus In addition to our product code, a lot of the errors are showing in the Boost libraries. For example:
  tag parsing file: C:\<path to specific version of boost>\boost\function.hpp
    tag parsing error (this can be ignored unless symbols can't be found):
    line 70 (col. 1): error: expected a file name
 // What is the '3' for?
#  define BOOST_PP_ITERATION_PARAMS_1 (3,(0,BOOST_FUNCTION_MAX_ARGS,<boost/function/detail/function_iterate.hpp>))
#  include BOOST_PP_ITERATE()
#  undef BOOST_PP_ITERATION_PARAMS_1

I think this is a different problem as the issue is not inside a comment.

**Comment by sean-mcmanus** [comment]
@BillDenton The tag parser doesn't parse or process preprocessor statements so I believe that error can be ignored. It's only an actual error if a particular symbol is missing when "Go to symbol in workspace" or document is used (or find all references for references not in the currently open TU, etc.).

**Comment by BillDenton** [comment]
@sean-mcmanus Does the Intellisense parser handle preprocessor statements?
I am having problems with using "compile_commands.json" but will raise that separately.

**Comment by sean-mcmanus** [comment]
@BillDenton The "tag parser" doesn't handle preprocessor statements (`#if 0` inactive blocks are not excluded and definitions of `#define` macros aren't available or stored in the database), but the IntelliSense parser handles them (processing of results within a single TU).
