### ISSUE TITLE
[c_cpp_properties.json]: a Syntax intellige cannot be used. The following error message is reported.

### ISSUE THREAD

**Issue by RedHeartSecretMan** [microsoft/vscode-cpptools#11692]
Type: <b>Bug</b>

Problems loading reference 'schemaservice://combinedschema/cpptools-schema:/c_cpp_properties.schema.json': Unable to load schema from 'schemaservice://combinedschema/cpptools-schema:/c_cpp_properties.schema.json': cannot open schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json. Detail: Unable to resolve resource schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json.

Extension version: 1.18.4
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:57.054Z)
OS version: Darwin arm64 23.0.0
Modes:
Remote OS version: Linux x64 5.4.0-166-generic
Remote OS version: Linux x64 5.4.0-166-generic
Remote OS version: Linux x64 4.15.0-213-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id 5556c8ad-a755-4e36-a242-8d91584795e9 --crash-reporter-id 5556c8ad-a755-4e36-a242-8d91584795e9 --crash-reporter-id 5556c8ad-a755-4e36-a242-8d91584795e9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: TLKJ2.233|
|OS|Linux x64 5.4.0-166-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz (48 x 1200)|
|Memory (System)|31.27GB (20.27GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: TLKJ2.233.9111|
|OS|Linux x64 5.4.0-166-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz (48 x 1200)|
|Memory (System)|31.27GB (20.27GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: TLKJ3.36|
|OS|Linux x64 4.15.0-213-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz (48 x 1838)|
|Memory (System)|62.78GB (41.05GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30886110
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by sean-mcmanus** [comment]
@RedHeartSecretMan I'm not able to repro that. Do you have any more repro info? Does this require a particular language-pack enabled?
