### ISSUE TITLE
Consider enabling code folding on C++ namespaces

### ISSUE THREAD

**Issue by m-j-w** [microsoft/vscode-cpptools#117]
Code folding is enabled on structs and control flow statements. Unfortunately not on namespaces.
In files with lots of helpers scattered throughout the file, code folding/collapsing those namespaces would be really helpful.

Thus, please consider enabling code folding on C++ namespaces. Thanks !

**Comment by ma-ric** [comment]
Please enable code folding also 
* on whole class definitions (all between {}; ), not only on the  subsections defined by class access modifiers (private,  protected, public).

* and on continues comment blocks.

Thanks!

**Comment by sean-mcmanus** [comment]
The code folding behavior is from VS Code itself and is based on the indent position only. VS Code doesn't currently have any API for modifying the code folding behavior. This is being tracked at https://github.com/Microsoft/vscode/issues/3422 .

**Comment by sean-mcmanus** [comment]
We're tracking this with https://github.com/Microsoft/vscode-cpptools/issues/407 .
