### ISSUE TITLE
How to ignore certain files while parsing?

### ISSUE THREAD

**Issue by t19903** [microsoft/vscode-cpptools#1170]
I have cloned linux kernel and opened by VSCode. However, I don't want to parse all the source files since it takes very long time to do it and keep making my cpu usage high. I want to trace block and fs related source files and ignore all the other files (i.e. net, mm, etc.) except for some necessary include files. Is there any way to make it parse files under linux/block, linux/fs, linux/include only? I tried setting files.exclude but seems still takes a long time and not sure whether the parser ignore the files or not.

**Comment by jophippe** [comment]
files.exclude is the way to ignore files when parsing. We've had problems honoring the files.exclude in the past, so this could very well be a bug. I recommend going to settings, changing the C_Cpp.loggingLevel to "Information", and then reloading VS Code. You should get output of which folders are ignored and which are parsed, just to make sure this is actually the problem.

**Comment by sean-mcmanus** [comment]
You should remove "${workspaceRoot}" from the browse.path (in c_cpp_properties.json) and just list the paths you want to parse for symbols. files.exclude won't work for items outside of the workspaceRoot.
