### ISSUE TITLE
Enhancements for Large-Scale Project Development: Improving Tag Parser Intellisense Performance and Code Navigation in VS Code

### ISSUE THREAD

**Issue by WittHickmanYoung** [microsoft/vscode-cpptools#11710]
Type: <b>Performance Issue</b>

Description of the Scenario we are using:
We are working on a large-scale project consisting of multiple components, including the Linux kernel. The project code is differentiated based on shell scripts for compiling, targeting different CPU types and host purposes. Different CPUs and host purposes have different function implementations. However, VS Code cannot recognize these compile macros, and the project requires multiple target file compilations. In this case, the default Engine of Intellisense does not work properly. Therefore, we switched to using the "Tag Parser" engine. However, when scanning the workspace with "Tag Parser," it becomes slow, consumes a significant amount of space, and the "show call hierarchy" feature does not display any content.

Suggested Improvements:
Provide an option to specify the directories to be scanned by Intellisense. Although VS Code offers the functionality to exclude directories, some files still need to be viewed in the project but should not be scanned for functions, variables, etc.
Integrate tools like cscope/universal-ctags to scan files. These tools can improve scanning speed and provide more comprehensive code navigation and structural information, enhancing the overall development experience.

Extension version: 1.18.5
VS Code version: Code 1.70.3 (a21a160d630530476218b85db95b0fd2a8cd1230, 2022-08-31T08:03:55.990Z)
OS version: Windows_NT x64 6.1.7601
Modes:

**Comment by browntarik** [comment]
Thank you for your suggestion, we are aware of ways our IntelliSense parsing can be improved and will take your feedback into consideration. Please track this issue for any progress we make.
