### ISSUE TITLE
"compile_commands.json" Unable to resolve configuration with compilerPath "...",   Using "cl.exe" instead.

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode-cpptools#11719]
### Environment

- OS and Version: Windows_NT x64 10.0.22621
- VS Code Version: 1.84.2 (system setup)
- C/C++ Extension Version: v1.18.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Using a C/C++ configuration in .vscode\c_cpp_properties.json that is configured for "compileCommands" with compile_commands.json:
...
   "configurations": [
      {
         "name": "compile_commands Target",
         "includePath": [
               "${workspaceFolder}/**"
         ],
         "windowsSdkVersion": "10.0.19041.0",
         "cStandard": "c17",
         "cppStandard": "c++17",
         "intelliSenseMode": "windows-msvc-x64",
         "compileCommands": "${workspaceFolder}/.vscode/compile_commands.json"
      }
   ],
   "version": 4

"compile_commands.json" is about 31Mbytes. It is from a cross-compilation. The Output C/C++ Configuration Warnings shows lots of:
[11/20/2023, 5:39:47 PM] Unable to resolve configuration with compilerPath "C:/<directory redacted>/<directory redacted>/bin/x86_64-linux-gnu-gcc.exe".  Using "cl.exe" instead.

"compile_commands.json" contains:
[
  {
    "arguments": [
      "C:/<directory redacted>/<directory redacted>/bin/x86_64-linux-gnu-gcc.exe",
      "-D<define redacted>",
      ... lots more lines of defines ...
      "-I../<include path>/include",
      ... lots more lines of include paths ...
      various other compiler options,
   ],
    "directory": "C:\\directory\\directory\\directory",
    "file": "../directory/directory/directory/directory/file.c",
    "output": "C:\\directory\\directory\\directory\\\\file.o"
  },

Expected behavior:
Not expecting to see the warning and expecting the Intellisense to use the cross compiler.

### Configuration and Logs

```shell
Using a C/C++ configuration in .vscode\c_cpp_properties.json that is configured for "compileCommands" with compile_commands.json:
...
   "configurations": [
      {
         "name": "compile_commands Target",
         "includePath": [
               "${workspaceFolder}/**"
         ],
         "windowsSdkVersion": "10.0.19041.0",
         "cStandard": "c17",
         "cppStandard": "c++17",
         "intelliSenseMode": "windows-msvc-x64",
         "compileCommands": "${workspaceFolder}/.vscode/compile_commands.json"
      }
   ],
   "version": 4
```

**Comment by sean-mcmanus** [comment]
Does adding `"compilerPath": "C:///bin/x86_64-linux-gnu-gcc.exe"` to c_cpp_properties.json fix the issue?

What other logging related to the compiler querying of that compiler do you see in the C/C++ logging with C_Cpp.loggingLevel set to Debug?

**Comment by BillDenton** [comment]
Does adding "compilerPath": "C://bin//x86_64-linux-gnu-gcc.exe" to c_cpp_properties.json fix the issue?
No. It should be using the value from "compile_commands.json". It also won't be a general solution as a different compiler is used for C++ files (x86_64-linux-gnu-g++.exe).

Note I have used the actual compiler path in my config rather the redacted version shown here. The path to the compiler is 86 characters including the filename. Or if using "\" backslashes "C:\bin\etc" it is 80 characters.
Note I have tried using "\\" and "/" by search & replace in "compile_commands.json". The same "compile_commands.json" file works with NeoWin (I don't know the details as it was tested by a colleague). The same error message is shown both times with the path being different.
I am confused as to what VS Code C/C++ extension expects for the directory separator under Windows. Is it "/" or "\\"? What should be under Linux.

From C/C++ logging with Debug with 
Code browsing service initialized
Querying compiler for default C++ language standard using command line: C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++.exe -x c++ -E -dM nul
Querying compiler for default C++ language standard using command line: C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++.exe -x c++ -E -dM /dev/null
Detected language standard version: c++98
Querying compiler's default target using command line: "C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++.exe" -dumpmachine
Compiler query command line: C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++.exe -march=haswell -maes -O3 -Wall -Wmissing-declarations -Wno-array-bounds -Wmissing-include-dirs -fno-common -fasynchronous-unwind-tables -fstack-protector-strong -fexceptions -g -fPIC -Wno-deprecated-declarations -m64 -Wextra -Wdouble-promotion -std=c++17 -Wp,-v -E -dM -x c++ nul
Attempting to get defaults from C++ compiler in compile_commands.json file: 'C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++.exe'
Querying compiler for default C++ language standard using command line: C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc.exe -x c++ -E -dM nul
Querying compiler for default C++ language standard using command line: C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc.exe -x c++ -E -dM /dev/null
Detected language standard version: c++98
Querying compiler's default target using command line: "C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc.exe" -dumpmachine
Compiler query command line: C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc.exe -march=haswell -maes -O3 -Wall -Wmissing-declarations -Wno-array-bounds -Wmissing-include-dirs -fno-common -fasynchronous-unwind-tables -fstack-protector-strong -fexceptions -g -fPIC -Wno-deprecated-declarations -m64 -Wnested-externs -Wdeclaration-after-statement -std=c17 -Wp,-v -E -dM -x c nul
Attempting to get defaults from C compiler in compile_commands.json file: 'C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc.exe'
Querying compiler for default C++ language standard using command line: C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++.exe -x c++ -E -dM nul
Querying compiler for default C++ language standard using command line: C:/BuildTools/gnu_xcompile/Deb11_B/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++.exe -x c++ -E -dM /dev/null
Detected language standard version: c++98

**Comment by Colengms** [comment]
Hi @BillDenton .  The configuration warning you're seeing should be associated with a failed compiler query in your logs.  The partial log you posted appears to indicate some successfully compiler querying.  Could you comb through your logs to find the failure, and post that?

The C/C++ Extension invokes the compiler to determine predefined macros and system include paths.  It will pass along any command line arguments that are known to influence those results (or not known not to influence them).  It's possible you have a command line in your `compile_commands.json` that includes a command line argument that is being mishandled, or cannot be used in combination with another argument we're adding in order to query the compiler, etc..  If you can identify the specific command line that's failing, that might help us investigate further.
