### ISSUE TITLE
intelliSenseMode gcc-arm64 auto expands to <host platform>-gcc-arm64

### ISSUE THREAD

**Issue by paulober** [microsoft/vscode-cpptools#11712]
### Environment

- OS and Version: macOS Sonoma
- VS Code Version: v1.84.2
- C/C++ Extension Version: newest
- If using SSH remote, specify OS of remote machine: NO

### Bug Summary and Steps to Reproduce

Bug Summary:
I'm working on a project for a platform that's not macOS, Windows or linux. So it set the intelliSenseMode to `gcc-arm64` but the extension automatically expands it to `macOS-gcc-arm64`, causing `#ifdef __APPLE__` flags in headers for IntelliSense fallthrought though the target platform doesn't support `__APPLE_`, if you know what I mean.

Steps to reproduce:
Described above

Expected behavior:
Work like a `none` target and don't define any Linux, macOS or Windows specific flags for IntelliSense!

### Configuration and Logs

```shell
{
  "configurations": [
    {
      "name": "DKP aarch64",
      "includePath": [
        "${workspaceFolder}/**",
        "mypath/include/**",
      ],
      "defines": ["MYPLATFORM", "__MYPLATFORM__", "DEBUG"],
      "compilerPath": "mypath/bin/aarch64-none-elf-g++",
      "cStandard": "c11",
      "cppStandard": "c++17",
      "intelliSenseMode": "gcc-arm64"
    }
  ],
  "version": 4
}
```

**Comment by sean-mcmanus** [comment]
@paulober "gcc-arm64" is deprecated -- does using "linux-gcc-arm64" work? If not, we're tracking a platform agnostic IntelliSense mode at https://github.com/microsoft/vscode-cpptools/issues/4653 , and we have work in progress that may accomplish this.

**Comment by paulober** [comment]
Yes I switched to linux-gcc-arm64 though it's not ideal cause I think this also will trigger some linux platform specific conditionals... But its OK

**Comment by paulober** [comment]
> @paulober "gcc-arm64" is deprecated -- does using "linux-gcc-arm64" work? If not, we're tracking a platform agnostic IntelliSense mode at #4653 , and we have work in progress that may accomplish this.

Ok, closing as duplicate
