### ISSUE TITLE
Extension upgrade failed to copy all dependencies

### ISSUE THREAD

**Issue by dwilliamson** [microsoft/vscode-cpptools#1171]
System:
```
macOS Sierra 10.12.6
Code Version 1.12.2 - not Insiders build
C/C++ Version 0.14.0
No other extension installed
```

Just got latest this morning and Intellisense appears to think that `_MSC_VER`, `_WIN32` and `_WIN64` are all defined. It's compiling this code:

```c
#if defined(_DURANGO) || defined(_XBOX_ONE)
#	undef  BX_PLATFORM_XBOXONE
#	define BX_PLATFORM_XBOXONE 1
#elif defined(_WIN32) || defined(_WIN64)
// http://msdn.microsoft.com/en-us/library/6sehtctf.aspx
#	ifndef NOMINMAX
#		define NOMINMAX
#	endif // NOMINMAX
//  If _USING_V110_SDK71_ is defined it means we are using the v110_xp or v120_xp toolset.
#	if defined(_MSC_VER) && (_MSC_VER >= 1700) && (!_USING_V110_SDK71_)
#		include <winapifamily.h>
#	endif // defined(_MSC_VER) && (_MSC_VER >= 1700) && (!_USING_V110_SDK71_)
```
and breaking when it tries to include `winapifamily.h` (https://github.com/bkaradzic/bx/blob/master/include/bx/platform.h#L145)

Edit: I verified both `_WIN32` and `_WIN64` were being set by independently removing them.

**Comment by michael-mayes** [comment]
Related to #1169 maybe?

**Comment by dwilliamson** [comment]
Yup, saw yours first; didn't want to interrupt the support.

**Comment by michael-mayes** [comment]
Appreciated. I will leave it to our friends over at Microsoft to determine whether they can be treated together

**Comment by dwilliamson** [comment]
OK, I have the easiest repro. It appears everything's broken on Mac.

1. Create a new folder and open it with VSCode.
2. Create a file called `test.cpp` in that folder and add the code:

```cpp
#ifdef _WIN32
x
#endif
```
3. Save the file and note that it's issuing a compile error for the `x` in the macro bounds.

This is all with `"C_Cpp.intelliSenseEngine": "Default"`. 

My `c_cpp_properties.json` file:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/usr/local/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/usr/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                    "/usr/local/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include",
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```

**Comment by bobbrow** [comment]
@dwilliamson, I followed your steps and I don't reproduce your issue.  If I set `intelliSenseMode` to **msvc-x64** I can repro, but that's expected because that compiler always sets `_WIN32=1`.

**Comment by dwilliamson** [comment]
If I add `"defines":["BLAH"]` to the `Mac` configuration and `#ifdef` on that I also get errors. When I add that to the `Win32` configuration there are no such errors. This should be as expected and is informing me that VSCode is picking the right configuration and either ignoring `intelliSenseMode` or defining Win32 macros for some other reason.

Is there nothing I can try here to get to the bottom of this problem?

**Comment by bobbrow** [comment]
Ok, I'm lost now.  Which configuration is active when you are developing code, "Mac"?  So you're using clang-x64 intelliSenseMode and seeing that _WIN32 is defined?  Clang mode does not set this define.  Is your project defining it in a header somewhere?

During the update we turned on the new compiler-based IntelliSense engine by default for everyone.  Before the update, did you ever manually set `"C_Cpp.intelliSenseEngine": "Default"` in your settings.json file?  If not, then the errors you're seeing were always present, but we never showed them to you before.   Can you confirm if you changed this setting yourself or not?

**Comment by dwilliamson** [comment]
As per the repro steps I gave you: this is a new, from-scratch folder with no pre-existing settings beyond my user preferences. There are no other defines, no other includes, nothing but an empty .cpp file with an `#ifdef` in it.

This is running on the Mac, hence it should be using the `Mac` configuration. I proved that in my last post by setting defines that were applied only in that config.

I set `"C_Cpp.intelliSenseEngine": "Default"` in my user preferences many months ago with this was experimental and have not changed anything since.

**Comment by bobbrow** [comment]
Yes, I followed your steps on Mac.  I even uninstalled and reinstalled the extension, but I don't get any squiggles with:
```
#ifdef _WIN32
x
#endif
```
which suggests that it is being defined in your project somewhere.  You lost me when you said you added "BLAH" to the defines and then did:
```
#ifdef BLAH
x
#endif
```
You complained that this case also had squiggles and I didn't understand why because it is very clear that this case should have squiggles.  If you remove "BLAH" from your Mac configuration for that case, the squiggles will go away.

I only see two possibilities left if _WIN32 is not set in your c_cpp_properties.json file:
1. _WIN32 is being defined by your project
    * If this is the case, and the browse.path has been fully parsed by the extension, you should be able to do "Go To Definition" on the _WIN32 symbol and find the offending header file.
2. _WIN32 is being defined in one of the extension's resource files
    * This would have required manual changes from you, so I doubt this is the case. The files live in `~/.vscode/extensions/ms-vscode.cpptools-0.14.0/bin`.  For Mac, only msvc.json and msvc.64.darwin.json are used when the IntelliSense mode is clang-x64.

**Comment by dwilliamson** [comment]
The intent of adding `BLAH` to defines was to demonstrate that the `Mac` configuration was being used and not the `Win32` configuration. That there were red squigglies was a good thing as it proved `Mac` was indeed in use.

What I'm not fully getting is your use of the term "project". All I'm doing is opening a folder/directory, so I see no other way for any other header files to be pulled into compilation.

**Comment by dwilliamson** [comment]
Let me work through each of the `browse.path` entries and get back to you. I've not changed anything in any of those folders though, so hoping...

**Comment by bobbrow** [comment]
> What I'm not fully getting is your use of the term "project". All I'm doing is opening a folder/directory, so I see no other way for any other header files to be pulled into compilation.

"project" == "folder".  And I was thinking of your original post when I wrote that, not the small repro you mentioned.  Sorry about that.  So when you hover the mouse cusror over the `_WIN32` symbol in your test file, does IntelliSense give you a tooltip for it?

**Comment by dwilliamson** [comment]
Hovering over the define gives me `#define _WIN32 1`. Trying to Go To Definition yields `No definition found for '_WIN32'`.

I've also just reduced my `c_cpp_properties.json` file down to:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": []
        }
    ],
    "version": 3
}
```

Same problem.

**Comment by dwilliamson** [comment]
Hmmm... there is a `msvc.json` but no `msvc.64.darwin.json` in my `ms-vscode.cpptools-0.14.0` folder.

There is one in my `ms-vscode.cpptools-0.13.0` folder.

OH MY! I copied the `msvc.64.darwin.json` file into the `0.14.0` folder, restarted and everything's working again!

Curiously... the `0.13.0` folder has also just disappeared...

**Comment by bobbrow** [comment]
Yeah, without that file, we wouldn't tell the IntelliSense engine that you wanted Clang mode.  It's making sense now.  MSVC is the default mode, so that's what you were getting.

But this is a serious problem if upgrading the extension cannot be relied on to lay out the files properly.  The extension has had issues in the past of not shutting down cleanly on Mac and Linux, but we've fixed up most of those in 0.14.0.  I suspect that VS Code was unable to delete the previous folder because the process was still in use, but I can't explain why you wouldn't have gotten the json files.

**Comment by bobbrow** [comment]
I'm glad everything is working for you now though!

**Comment by dwilliamson** [comment]
Thanks for helping out.
