### ISSUE TITLE
cannot run c program file .

### ISSUE THREAD

**Issue by Naveenbandari26** [microsoft/vscode-cpptools#11722]
Type: <b>Feature Request</b>

i can't compile c program file.

Extension version: 1.19.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by browntarik** [comment]
Could you please provide more context? What type of project are you trying to compile?

Could you provide the log diagnostics using the C/C++ Log Diagnostics Command? 

Some troubleshooting options:

- Make sure you have a compiler installed and your PATH environment variable is set to point to that compiler
- Make sure your compiler is set in c_cpp_properties.json
- Ensure the extension is enabled
