### ISSUE TITLE
'.' to '->' completion doesn't work the 1st time unless Ctrl+Space is used

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11723]
Repro code is

```cpp
class foo{ int i;};

int func() {
    foo *f = new foo();
    f.; // f. doesn't suggest i the 1st time unless Ctrl+Space is used.
    return 0;
}
```

Deleting the `.` and retyping it causes it to work.

The original issue was https://github.com/microsoft/vscode-cpptools/issues/862

**Comment by sean-mcmanus** [comment]
@bobbrow It's "by design" due to "i" not having public accessibility.

This doesn't repro it.
```cpp
struct foo{ int i;};
int func() {
    foo *f = new foo();
    f.; // f. doesn't suggest i the 1st time unless Ctrl+Space is used.
    return 0;
}
```

**Comment by bobbrow** [comment]
@sean-mcmanus Ah, that makes sense.  Sorry I didn't help spot that sooner.
