### ISSUE TITLE
C23 boolean keywords incorrectly flagged as undefined

### ISSUE THREAD

**Issue by nickelpro** [microsoft/vscode-cpptools#11739]
### Environment

- OS and Version: Arch Linux
- VS Code Version: 1.84.2
- C/C++ Extension Version: v1.19.1

### Bug Summary and Steps to Reproduce

Bug Summary: `true` and `false` under C23 are incorrectly red-squiggled regardless of configuration provider

Steps to reproduce:
1. Clone the following repo: https://github.com/nickelpro/bools-borked
2. Configure the repo with your configuration provider of choice, ensuring to enable C23 language standard (Tested with compile_commands.json, CMake Tools, gcc, and c_cpp_properties.json)
3. See red squiggles under `true` and `false`. Error is `identifier "true" is undefined C/C++(20)` (or `"false"`)

Expected behavior:
No red squiggles under the boolean keywords

### Configuration and Logs

`c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "cStandard": "c23",
            "cppStandard": "c++23",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

### Additional context

Image:

![image](https://github.com/microsoft/vscode-cpptools/assets/1032552/f901c446-b7b4-460f-81fe-a41c3dfb65db)

Notes:
* Curiously there are no red squiggles under `bool` itself
* Including `stdbool.h` does not fix this, because the macros are disabled under C23

**Comment by nickelpro** [comment]
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/10696, closing

**Comment by bobbrow** [comment]
A workaround option is here: https://github.com/microsoft/vscode-cpptools/discussions/11718#discussioncomment-7635890
