### ISSUE TITLE
Problem with C++ scope detection

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-cpptools#1173]
Moved from https://github.com/Microsoft/vscode/issues/32815
From @Leedehai 

---

- VSCode Version: 1.15.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create this `.cpp` file, put the cursor in the function body of `foo()`.
<img width="609" alt="screen shot 2017-08-18 at 20 18 45" src="https://user-images.githubusercontent.com/18319900/29483043-d846cb96-8452-11e7-985e-1e3e8d3bda66.png">

2.Check the scope at the down-right corner of VSCode window. It says "Global scope", but it should be a function scope (if I understand this feature correctly).

3. If the cursor is inside a class definition, it still says "Global scope".

Reproduces without extensions: Yes

**Comment by bobbrow** [comment]
Did you save the file yet?  The navigation doesn't update until the file is saved.  If you didn't save yet, this is a known issue, but I forget the issue # right now.

**Comment by Leedehai** [comment]
@bobbrow Oh yes I didn't save the change (I just saved it after creating the file, but didn't save it again after adding the function `foo()`). After saving the change, the scope is correct.

**Comment by jackie-qiu** [comment]
Was this problem fixed?

**Comment by sean-mcmanus** [comment]
@jackie-qiu Nothing was changed in regards to this issue. You still need to save a file before the symbols will be found. The IntelliSense error squiggles should still work without saving.
