### ISSUE TITLE
Public API for language server (LSP)

### ISSUE THREAD

**Issue by HackXIt** [microsoft/vscode-cpptools#11732]
### Feature Request

Is there a public API that would allow for the language server of the extension to be called from another extension?

I'm particularly interested in this, according to my discussion here:
https://github.com/microsoft/vscode-cpptools/discussions/11730

If it doesn't work at all, would it be possible to add functionality (possibly through a PR), to add syntax highlighting for embedded C code inside PIO assembly files (Raspberry Pi pico) inside the C/C++ extension?

**Comment by sean-mcmanus** [comment]
There is no public/documented/supported/versioned/etc. API for the cpptools process (which receives LSP messages from VS Code and messages from this open source TypeScript component) or the cpptools-srv process (which receives messages from cpptools).

But our extension doesn't provide any syntax highlighting, unless you're referring to semantic highlighting -- VS Code gets its C/C++ syntax highlighting from https://github.com/jeff-hykin/better-cpp-syntax .

**Comment by HackXIt** [comment]
I'll check out that repo, thanks, didn't know that the plugin uses that.

My goal indeed would be to have syntax highlighting for the various PIO instructions and also for the embedded c-code.
Semantic highlighting probably won't be possible for this use-case.. At least not on my time.

I'll close the issue and going to see if I can use the better-cpp-syntax somehow for my purpose.
