### ISSUE TITLE
Remap header includes for linux/mac systems

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#11741]
There is incorrect mapping for resolving includes on linux/mac systems

```c++
namespace {

constexpr auto kTimeout = 30s;

}  // namespace
```

results in: `#include <__chrono/duration.h>`

```c++
#include <__chrono/duration.h>

#include <chrono>
...
```

_Originally posted by @H-G-Hristov in https://github.com/microsoft/vscode-cpptools/issues/11672#issuecomment-1820507919_

**Comment by sean-mcmanus** [comment]
I don't know the root cause, but it's possible may be we want to just add a heuristic which skips any files/folders that begin with an underscore -- since those tend to be system implementation details.
