### ISSUE TITLE
Cancel/timeout for "Go to definition"

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-cpptools#1174]
_From @fo-fo on October 26, 2017 13:55_

VSCode sometimes gets stuck for an overly long time with C++ code when using the "Go to Definition" feature. Trying to use the feature with a different symbol after this does nothing, and the only recourse I know is to restart the editor.

Would be nice if there was a way to cancel and/or time out the search. Unfortunately I can't give instructions for reproducing since this happens fairly randomly.

- VSCode Version: 1.17.2
- OS Version: Ubuntu 16.04.3 LTS

_Copied from original issue: Microsoft/vscode#36985_

**Comment by dbaeumer** [comment]
VS Code actually cancel the request but it looks like the cpp extension is not reacting to it.

**Comment by sean-mcmanus** [comment]
@fo-fo We don't respond to cancel requests, but the problem here sounds like our language service process is crashing and not restarting properly (which we plan to fix), so I don't think responding to a cancel request would fix this (the go to definition is not normally a slow request and shouldn't need to be canceled).

**Comment by fo-fo** [comment]
I see. Is there any way that I can help you? Does the language service produce logs somewhere?

**Comment by sean-mcmanus** [comment]
@fo-fo We show logs in the C/C++ part of the Output pane. You can setting the C_Cpp.loggingLevel to Information for more logging. You can also look if the Microsoft.VSCode.Cpp.Extension.linux process is crashing and try to attach a debugger to get a call stack. Our next update might fix the restart on crashing problem too.

**Comment by sean-mcmanus** [comment]
0.22.0 added the ability to cancel IntelliSense-based Go to Definition requests, but VS Code isn't sending us any cancelRequests for that ID, see https://github.com/Microsoft/vscode/issues/70602 .
