### ISSUE TITLE
Developer: Inspect Editor Tokens and Scopes command stuck at 'Loading'

### ISSUE THREAD

**Issue by lolzz77** [microsoft/vscode-cpptools#11743]
Type: <b>Bug</b>

1. Enable extension C/C++
2. Open command palette (CTRL + SHIFT + P)
3. Select `Developer: Inspect Editor Tokens and Scopes`
4. A small window pops up with string 'Loading' and it shows this string forever [Issue]

Expected Output: 
A small window pops up with information rather than just 'Loading'.

Extension version: 1.17.5
VS Code version: Code - Insiders 1.85.0-insider (444e73750b99b11c3597a5f5d210d2b52257e377, 2023-11-16T05:36:13.931Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'attached-container+7b22636f6e7461696e65724e616d65223a222f7673636f6465227d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.36GB (15.35GB free)|
|Process Argv|--crash-reporter-id a8891a18-51ef-42d7-8eb2-14df2f89a638|
|Screen Reader|no|
|VM|0%|

Connection to 'attached-container+7b22636f6e7461696e65724e616d65223a222f7673636f6465227d' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30901775
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by Colengms** [comment]
Hi @lolzz77 .  The C/C++ extension is not directly involved in the display of the Editor Tokens and Scopes UI.  I'd suggest opening an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).
