### ISSUE TITLE
Support for `${userHome}`

### ISSUE THREAD

**Issue by paulober** [microsoft/vscode-cpptools#11756]
### Feature Request

You can find the official variables here: https://code.visualstudio.com/docs/editor/variables-reference

Currently the only what to make system independent configuration for `c_cpp_properties.json` is to use stuff like
`${env:HOME}/compiler/arm-none-eabi-gcc`. As you can see this isn't platform independent as it doesn't work on Windows, 
where the alternative would be `${env:USERPROFILE}/compiler/arm-none-eabi-gcc`.

So please implement support for `${userHome}` as platform independent alias for the node.js `homedir()`:
https://nodejs.org/api/os.html#oshomedir

**Comment by bobbrow** [comment]
This shouldn't be hard to do. Updating tags.

**Comment by sean-mcmanus** [comment]
@paulober Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.20.0

**Comment by paulober** [comment]
Thanks for implementing. This really solves some issues in my projects.
