### ISSUE TITLE
CPP extension hangs JS intellisense

### ISSUE THREAD

**Issue by baybal** [microsoft/vscode-cpptools#11754]
Type: <b>Bug</b>

CPP extension hangs JS intellisense

Extension version: 1.18.5
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.5.1-gentoo-x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2099)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|8, 5, 3|
|Memory (System)|7.50GB (0.77GB free)|
|Process Argv|--force-device-scale-factor=1 --unity-launch --crash-reporter-id 6c77bbc6-ae75-4344-8524-24d952db388b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|Xfce Session|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sean-mcmanus** [comment]
Can you provide more info?

**Comment by baybal** [comment]
No, unfortunately
