### ISSUE TITLE
"Go to Definition" function is not working for C files

### ISSUE THREAD

**Issue by Densi27** [microsoft/vscode-cpptools#1175]
Hello, 

I´m pretty new to VSCode (coming from Sublime 3) and I can not figure out how to get the "Go to Definition" function working. Same for menu, F12 and hyperlink. I installed the C/C++ extension already.

Many thanks for your help!

Kind regards, Daniel

VSCode Version: Code 1.17.2 (b813d12, 2017-10-16T13:59:46.104Z)
OS Version: Windows 7 x64

**Comment by jophippe** [comment]
Hi Daniel,
I assume you're getting the "No definition found" message, right? Could you give an example of what you're using Go To Definition on? If it's on something that's defined in a different file, then you need to either open a folder that contains both files or edit your c_cpp_properties.json file (see https://code.visualstudio.com/docs/languages/cpp under the "IntelliSense" header for help) and add the path to that file to the browse path array.

**Comment by Densi27** [comment]
Hi,
I now figured out, that I had a network problem and the extension wasn´t load properly. Now it works within a file! :-) Thanks for the hint with the folder and the properties, I will try this also.
Cheers and thanks Daniel
