### ISSUE TITLE
Can not find reference of the overload of operator

### ISSUE THREAD

**Issue by void-mian** [microsoft/vscode-cpptools#11762]
### Environment

- OS and Version: Ubuntu 22.04.3
- VS Code Version: 1.84.2
- C/C++ Extension Version: 1.18.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

"Find All Reference" shows no result of overloaded operator function, neither the "Call Hierarchy".
Also wish to support templated class.

### Configuration and Logs

```shell
default configuration
```

**Comment by browntarik** [comment]
Could you please provide a code snippet and your log diagnostics using the C/C++: Log Diagnostics command so that we can better reproduce the issue you are facing?
