### ISSUE TITLE
IntelliSense results for a source file should include any error discovered in its headers

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#11779]
Opening this issue to track reporting errors for unopen headers.  In the IntelliSense results for a source file, VS will report errors encountered in header.  Cpptools is not currently reporting these.  Doing so will require some work to manage merging/deduping of header results from multiple TUs, and to properly clear out header results when all associated source files have been closed.

**Comment by starball5** [comment]
even those found as system headers when using a compile commands database?

**Comment by bobbrow** [comment]
This is a duplicate of #3873
