### ISSUE TITLE
F5 -> wmic process get Name,ProcessId,CommandLine /FORMAT:list" exited with code: "2147749902"

### ISSUE THREAD

**Issue by maxenko** [microsoft/vscode-cpptools#11789]
### Environment

- OS and version: Windows 10 19045.3803
- VS Code: 1.85.1
- C/C++ extension: v1.18.5
- GDB / LLDB version: cppvsdbg

### Bug Summary and Steps to Reproduce

Bug Summary:
This is happening AFTER windows update. I see many files were updated in: ```C:\Windows\System32\wbem```, with names like ```*wmi*.exe/dll``` etc. _This used to work before the this windows update._

To reproduce:
Just hit F5, instead of being presented with a process selection list, it now throws this error:
```
[Window Title]
Visual Studio Code

[Content]
"wmic process get Name,ProcessId,CommandLine /FORMAT:list" exited with code: "2147749902".
ERROR:

Description = Invalid namespace
[Open 'launch.json'] [Cancel]
```

![Screenshot 2023-12-18 122518](https://github.com/microsoft/vscode-cpptools/assets/1999105/e7400090-9231-4041-b319-bdc0b1136870)

There is not much else to include, worked last week, broken today. Only thing changed was windows via update.

### Debugger Configurations

```shell
launch.json:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Photoshop",
            "type": "cppvsdbg", // Use cppvsdbg for Visual Studio debugger on Windows, cppdbg for others
            "request": "attach",
            "processId": "${command:pickProcess}",
            "sourceFileMap": {
                "/": "${workspaceFolder}" // Optional, adjust as needed for source mapping
            }
        }
    ]
}
```

### Debugger Logs

```shell
*
```

**Comment by bobbrow** [comment]
Are you able to run that command directly in a CMD window?
`wmic process get Name,ProcessId,CommandLine /FORMAT:list`

**Comment by maxenko** [comment]
> Are you able to run that command directly in a CMD window? `wmic process get Name,ProcessId,CommandLine /FORMAT:list`
> 
> EDIT: It works for me on Windows 11. I don't have a Windows 10 PC anymore.

Yes with similar output:
```
wmic process get Name,ProcessId,CommandLine /FORMAT:list
ERROR:
Description = Invalid namespace
```

**Comment by maxenko** [comment]
Visual Studio 2022 works still when Attaching to process manually.

**Comment by bobbrow** [comment]
Something may be corrupt with WMI after the update.  There is some information here you can check to see if Windows can show you what the problem is: https://techcommunity.microsoft.com/t5/ask-the-performance-team/wmi-missing-or-failing-wmi-providers-or-invalid-wmi-class/ba-p/375485

Unfortunately, we just use the Windows tool to determine the list of processes to pick from.  If you are unable to repair WMI, you would need to manually paste the "processId" into your launch.json before pressing F5.
