### ISSUE TITLE
Colors seem to be not working for operator overloading

### ISSUE THREAD

**Issue by KKghub** [microsoft/vscode-cpptools#11784]
### Environment

- OS and Version: MacOS Ventura 13.6.1
- VS Code Version: 1.85.0 (Universal)
- C/C++ Extension Version: 1.18.5
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Create a cpp extension file
2. Write the following code:
```
struct compare {
    bool operator()(const int l, const int r) {
        return l > r;
    }
};
```
3. I see that `operator()` is colored separately i.e yellow `operator` and pink `()`, see below screenshot:
<img width="368" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/25261656/192037a7-13e6-4baa-987a-f7693433d08d">

4. I have tested this with Dark+ Theme and other themes as well, while switching themes it momentarily makes it completely pink but then again splits into two colors

Expected behavior:
I believe `operator()` should be colored in the same color, probably pink

### Configuration and Logs

```shell
c_cpp_properties.json

{
    // These configurations are for gcc only (not msvc or clang compilers)
    // Make sure gcc/g++ are available in the PATH environment variable
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "windows-gcc-x64"
        },
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/usr/local/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "macos-gcc-x64"
        },
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
Our extension doesn't generate those colors. They're coming from VS Code's paren matching colors.

<img width="183" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/8d2b9890-8868-48fd-b0b5-49dd7650632c">

You can set "editor.bracketPairColorization.enabled": false to disable that.

<img width="196" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/aa56d829-132a-4930-8c77-835881e6e950">

**Comment by KKghub** [comment]
@sean-mcmanus Well... I was not looking for a solution to just disable the brackets syntax highlighting but more of saying that when we perform operator overloading for example `operator()` `operator+` `operator-` etc. it would be helpful to just highlight all the characters in the same color including the brackets if present to denote that this is operator overloading happening...

For example in leetcode website, syntax highlighting for operator overloading looks evident:
<img width="389" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/25261656/b90e7937-7b14-4af8-bac7-d81ee2d3d855">
 
 I can understand if syntax highlighting is not part of your extension or this is not achievable from your side
