### ISSUE TITLE
Syntax colouring - can I distinguish between local variables and member variables?

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#11787]
### Environment

All versions

### Bug Summary and Steps to Reproduce

This isn't a bug 'per se', more of an enquiry to determine if it is possible?

I've tried various themes, but it doesn't seem to be possible. There is an old extension https://marketplace.visualstudio.com/items?itemName=reloadedextensions.reloaded-cpp which does allow this to work (using naming conventions) but I was hoping there was some support built in?

### Configuration and Logs

```shell
N/A
```

**Comment by bobbrow** [comment]
Yes, you can do this.  Your settings would look something like this.  You can have different colors for different themes.

```json
    "editor.semanticTokenColorCustomizations": {
        "[*Light*]": {
            "rules": {
                "property": "#ff0000"
            }
        },
        "[*Dark*]": {
            "rules": {
                "property": "#ffffff"
            }
        },
    }
```

![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/71068afa-4f6c-4a97-baeb-6f7d39aed337)

**Comment by bobbrow** [comment]
(Sorry for the dumb field name. It was originally 'n' but I wanted to make it longer for the screenshot and the first thing that I thought of that started with 'n' was 'name', but I didn't change the type. 😄 )

**Comment by Colengms** [comment]
Hi @Gruntfuggly .
You can find a list of the semantic tokens supported by the C/C++ Extension, and their token names, here: https://code.visualstudio.com/docs/cpp/colorization-cpp#_intellisense-tokens-and-scopes
