### ISSUE TITLE
Add inlay hints  for designators in aggregate initialization.

### ISSUE THREAD

**Issue by ProudRabbit** [microsoft/vscode-cpptools#11793]
### Feature Request

Add inlay hints for indexes in aggregation initialization.

eg:
When the function is open
`std::vector<int> arr = {[0]= 1, [1]= 2} ;`
close
`std::vector<int> arr = {1, 2}`

This prompt is useful when initializing large arrays.

**Comment by browntarik** [comment]
Thank you for submitting this request, please spread the word as the more upvotes this request receives the higher priority it gets.
