### ISSUE TITLE
ctrl-shift-o shows too many symbols in version 0.8.0

### ISSUE THREAD

**Issue by delmyers** [microsoft/vscode-cpptools#118]
Taken from the reviews on our extension page:

shift+ctrl+o, to show current file symbols. but vscode show 9999 and more symbols? why? Is this a bug? when I change 0.8.0 to 0.7.1, it works well. Mac OS 10.11.5

**Comment by nikibobi** [comment]
I can confirm this. I think it includes symbols from all of your includes and maybe is related to 

```
            "includePath": ["/usr/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
```

I'm on Ubuntu 16.04

**Comment by jgoshi** [comment]
This is fixed and will appear in the next release (version 0.9.0)
