### ISSUE TITLE
Including header and cpp files from downloaded libraries

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1180]
Hello,

I'm new to C++ and I'm using Visual Studio Code on Linux to do the development. For a little project I downloaded this library [curlcpp](https://github.com/JosephP91/curlcpp). I followed the instructions for cmake, but I did not do the steps from the library path and the include path. I couldn't find any documentation that explains how to incorporate libraries from other people in your own program when using Visual Studio Code. It could be that I just lack general C++ knowledge that is applicable with any editor / IDE and not just specifically for my situation with VS Code. Now when I add an include statement in my code like so `#include "curl_easy.h"` the compiler complains that there is no such file or directory. What are the standards for using other people's libraries in your own C++ program, and how do I resolve this issue?

Also, if this is not the right place to ask, apologies, on the official docs page it says for any questions or issues go to GitHub and ask there. [vscodedocs](https://code.visualstudio.com/docs/languages/cpp)

**Comment by agauniyal** [comment]
vscode is not c++ compiler neither is this plugin. You've to find where you installed curlcpp header file and then use `#include` statement with absolute path to it. Not really the right place to ask this question.

**Comment by ghost** [comment]
Thanks for the reply!

**Comment by agauniyal** [comment]
@MatthijsHoogendoorn you can try cpplang.slack.com where you can ask such questions. Get invite email from here - https://cpplang.now.sh

**Comment by ghost** [comment]
@agauniyal Thanks a lot for this!
