### ISSUE TITLE
Code Navigation Not working

### ISSUE THREAD

**Issue by sudhee-d** [microsoft/vscode-cpptools#11802]
Type: <b>Bug</b>

Hi,
I am using VS code for C++ development under devcontainer. It is a big project, code navigation works fine upon launching VS Code, but , after some time, Code Navigation/F12 doesn't work..

Extension version: 1.18.5
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.6.4-200.fc39.x86_64
Modes:
Remote OS version: Linux x64 6.6.4-200.fc39.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 4300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.05GB (21.84GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6eefd61b-04a1-42d6-8c0e-19be9b4e8b13|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|Container localhost/vsc-idaa-server1-1cd1c183524d8cf96f53c69b0dcfe7b959c155207b0224192942a02c082f9740-uid:latest (idaa2)|
|OS|Linux x64 6.6.4-200.fc39.x86_64|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 4301)|
|Memory (System)|31.05GB (21.84GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pythonregdiag2:30926735
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184t:30925682

```

</details>

**Comment by browntarik** [comment]
Could you please provide more details about your project? Also, could you provide the details from the C/C++: Log Diagnositcs Command?

Creating a concise reproducible scenario can help us diagnose the issue. 

Thank you
