### ISSUE TITLE
Simpler - Compile, Run, Debug button for Students

### ISSUE THREAD

**Issue by antoniocaruso** [microsoft/vscode-cpptools#11815]
### Feature Request

I really like to use Visual Studio Code in class, for math or physics students learning how to program mostly in C, or C++.

There is however a very large gap between VSC and other IDE like CodeBlock or others, in the C/C++ extension.
I don't know if it depends on the extensions or on the core. However I point some of it:

* It is really complex to define a simple 'toolchain' folder with the bin containing the compiler and library to be used, this affect in particular windows, if I'd like to compiler without using WSL, it must be a simple way to say 'hey, c:\mingw64' is the dir that you are looking for, just check EVERYTHING there.
* There is NO WAY to just compile a simple file, I don't want to run it, just compile it.
* There is NO WAY it seems to run it, without compiling.
* There is a really complicated way (tasks.json, build.json, etc) to configure the debugger vs the compilation tasks. But in all the case, nowhere easy enough to just let a student, install the extension, point it to a compiler folder and
just compile, and run the program WITHOUT DEBUG. or compile it with debug info, and run (without debugging) or with debugging. It seems the overall idea of developers is...automate things, maybe use make or other tools for large project. While the life of a student is: write stuff inside a single main function for almost one month, and work with just one file for at least another.

So, I don't know if it is possibile to see in VSC a simple C/C++ extension that is able to provide a VERY SIMPLE SETUP for just 'push this-> compile", "push this -> run", "push this -> run with debug". Students do not spend their time in reading docs, never. If they don't have a working environment out of the box, they just avoid to do their hands-on programming by themself, and just read the code from the lesson, without caring to really make experience.

**Comment by browntarik** [comment]
I apologize for your inconvenience. There are a few approaches you could make, while it is by design that we run and compile code in one operation using f5, you can split this within two separate operations in the following ways:

1) Using the command line:
- Based on your compiler you can use the terminal to compile your c++ code (example: `g++ -o myprogram myfile.cpp)`
- Once compiled, you can then run it separately using `./myprogram`

2) Using tasks.json:
- While this takes more setup, this approach lets you use the VS Code API
- Once you have installed a compiler, use the "Tasks: Configure Task" command to create a build task, by default the generated tasks.json will compile your active file and place it in the directly it exists in
- Once you have created a build task, use the ctrl+shift+B hot key to quickly build/compile as neccessary
- To run as neccessary, just use run the program using `./{insert program name}`

**Comment by antoniocaruso** [comment]
Dear all,

I perfectly know how to compile, that is not an issue, I'd also usually teach to student how to use the console and command line to compile (they will maybe use gcc/g++/gdb on a server with ssh). but of course it is simpler to have shortcut in an IDE, that is the point of having an IDE.

So, I understand your guide for tasks.json, but all guide have the same problems. they are abstract, NO REAL example is really working, and I have no time to figure out how to write one correctly, so this is a simple question:
Suppose that there is a path like  c:\compiler\ and that ALL file related to the compiler is there (c:\mingw64) within the bin directory, could you just replay here a COMPLETE tasks.json that simply build the current file? already with the keybinding associated (there is another issue that I was not able to complete).

Morever, the point of launching the code from the command line is exactly *a problem*. Think about a student at his first program or that is going to test the program of a book, or the ones that I gave, they loop around 

the build, fix problems, run, check

a million times, for even the simplest program, so compared to other GUI, Dev-Cpp, CodeBlock, even Emacs, 
VSC is really lacking in usability for simpler stuff. 

I perfectly know that the environment is built for real developers that usually have to use much complex tools, make, cmake, and so on, and several different languages, but since at this moment VSC is the most advanced PORTABLE modern IDE, excluding maybe vim and emacs, I would really see, a way to just 'compile file', 'run file', in it.

Thanks, for everything, in any case, I'll keep trying with tasks.json and follow the issue here.

**Comment by antoniocaruso** [comment]
I'm not asking a feature, I'm asking a replay. Could you produce a complete set of tasks.json and launch.json that works? with gcc in the this path: C:\mingw64\bin\gcc.exe, just to understand.
