### ISSUE TITLE
Error for referencing undefined functions showing in C++ but not in C

### ISSUE THREAD

**Issue by TommasoTricker** [microsoft/vscode-cpptools#11817]
### Environment

- OS and Version: Windows 10 Pro Version 22H2 OS build 19045.3803
- VS Code Version: 1.85.1
- C/C++ Extension Version: 1.18.5
- If using SSH remote, specify OS of remote machine: No

### Bug Summary and Steps to Reproduce

Bug Summary:
The error that appears when calling an undefined function is shown in C++ as "identifier "function name" is undefined" but nothing appears C files unless a code analysis is triggered manually.

Steps to reproduce:
1. Open a folder in vscode
2. Create a .cpp file and reference an undefined function
```
int main()
{
    hi();
    return 0;
}
```
3. Observe that the error "identifier "hi" is undefined" appears
4. Change the extension to .c
5. Observe that no error appears even after editing and saving

Expected behavior:
Some sort of error appears automatically stating that the referenced function is undefined

### Configuration and Logs
c_cpp_properties.json
```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.22000.0",
            "compilerPath": "C:/msys64/mingw64/bin/gcc.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-gcc-x64"
        }
    ],
    "version": 4
}
```

### Additional context
settings.json
```shell
{
    "security.workspace.trust.enabled": false,
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "git.autofetch": true,
    "git.confirmSync": false,
    "git.enableSmartCommit": true,
    "[python]": {
        "editor.formatOnSaveMode": "file",
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.formatOnType": false
    },
    "explorer.confirmDelete": false,
    "editor.fontSize": 15,
    "redhat.telemetry.enabled": false,
    "isort.check": true,
    "ruff.organizeImports": false,
    "window.zoomLevel": 1,
    "cmake.cmakePath": "C:\\Program Files\\CMake\\bin\\cmake.exe",
    "cmake.configureOnOpen": true,
}
```

**Comment by sean-mcmanus** [comment]
This is "by design". The C language compiles without errors with undefined variables. You can get a warning via running code analysis (clang-tidy):
<img width="439" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/a9e43be7-c00a-4493-afb1-7929392d5c9f">
