### ISSUE TITLE
cant use pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain

### ISSUE THREAD

**Issue by DankAvii** [microsoft/vscode-cpptools#11812]
![Screenshot (11)](https://github.com/microsoft/vscode-docs/assets/145327837/131c1a9a-dabc-4e6a-8d1f-ba4bd5694193)

**Comment by browntarik** [comment]
The command is slightly incorrect, "devil" should be "devel". Please use the following command instead:

pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain
