### ISSUE TITLE
IntelliSense not working properly with PCL

### ISSUE THREAD

**Issue by linyz0100** [microsoft/vscode-cpptools#11825]
### Environment

- OS and Version: Ubuntu 22.04
- VS Code Version: 1.85.1
- C/C++ Extension Version: 1.3.0
- If using SSH remote, specify OS of remote machine: NA

### Bug Summary and Steps to Reproduce

Bug Summary:
IntelliSense works fine except for PCL. Some types are not recognized but give autocompletion.
![pcl_err](https://github.com/microsoft/vscode-cpptools/assets/63493856/394d730c-785d-4a4f-a018-a35a8f72c8ba)
![pcl_err2](https://github.com/microsoft/vscode-cpptools/assets/63493856/e280b7f7-e002-4c1b-b19e-efd8bd38c689)
![pcl_err3](https://github.com/microsoft/vscode-cpptools/assets/63493856/b2e26496-f7e0-4414-9fd1-0462f7c3cec9)
Sometimes it finds the struct file like so; sometimes it doesn't find anything. Other libraries like OpenCV is good.

Steps to reproduce:
1. install pcl `sudo apt install libpcl-dev`
2. cpp file 

```
#include <iostream>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/visualization/cloud_viewer.h>
void foo()
{
    pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud;
    //... populate cloud
    pcl::visualization::CloudViewer viewer("Simple Cloud Viewer");
    viewer.showCloud(cloud);
    while (!viewer.wasStopped()) {
    }
}
```
Expected behavior:

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "browse": {
                "databaseFilename": "${default}",
                "limitSymbolsToIncludedHeaders": false
            },
            "includePath": [
                "/opt/ros/humble/include/**",
                "/home/linyz0100/Desktop/workspace3/src/goto_x/include/**",
                "/home/linyz0100/Desktop/workspace3/src/send_image/include/**",
                "/usr/include/**",
                "/usr/include/opencv4",
                "/usr/include/eigen3",
                "/usr/include/pcl-1.12",
                "/usr/include/vtk-9.1"
            ],
            "name": "ROS",
            "intelliSenseMode": "gcc-arm64",
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu11",
            "cppStandard": "c++14"
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @linyz0100 . I'm not able to easily repro an issue using the information provided.  I installed `libpcl-dev`, in my case on Ubuntu 23.04 x64. Using your configuration (excluding the directories I do not have), the code example you provided is not producing any squiggles for me.

Is it possible that one of your include directories (which I don't have) contains identically named header which IntelliSense may be finding instead of the proper PCL headers?

Could you also provide the output of the `Log Diagnostics` command with the repro'ing file open?
