### ISSUE TITLE
[error] Variable ${file} can not be resolved. Please open an editor

### ISSUE THREAD

**Issue by chicken-suop** [microsoft/vscode-cpptools#11823]
Type: <b>Bug</b>

When the setting `terminal.integrated.defaultLocation` is `editor`, then I can't run or debug a simple helloworld program. Running the default `C/C++: g++ build active file` task opens a new window that says "Executing task: C/C++: g++ build active file", and the output tab (filtered to Window) shows the error `[error] Variable ${file} can not be resolved. Please open an editor`. Changing the setting back to default, fixes this issue.

Extension version: 1.18.5
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 5.15.0-91-generic
Modes:

**Comment by browntarik** [comment]
This does not sound like it is related to the setting you are changing, could you please provide your logging from the C/C++: Log Diagnostics command?

I am currently not able to reproduce your issue.
