### ISSUE TITLE
Update docs to Windows Subsystem for Linux

### ISSUE THREAD

**Issue by sandhilt** [microsoft/vscode-cpptools#1182]
Docs will update location of old lxss to new location. https://github.com/Microsoft/vscode-cpptools/pull/1176

Fix this file: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md

**Comment by bobbrow** [comment]
I'm not exactly sure what you're asking for.  #1176 is under review.  We don't need another issue to track it.
