### ISSUE TITLE
cpptools using all memory

### ISSUE THREAD

**Issue by abergmeier** [microsoft/vscode-cpptools#11832]
### Environment

- OS and Version: Ubuntu 22.04
- VS Code Version: 1.85.1
- C/C++ Extension Version: latest

### Bug Summary and Steps to Reproduce

Bug Summary: Indexing seems to take up all available memory

Steps to reproduce:
1. Clone https://github.com/aluntzer/gtknodes
2. Configure meson build in `builddir`. Content:
  ```meson
project('gtknode', 'c')

gnome = import('gnome')
pkg = import('pkgconfig')

gtkdep = dependency('gtk4')

sources = [
    'src/gtknode.c',
    #'src/gtknodesocket.c',
    #'src/gtknodeview.c',
]

lib = shared_library(
    'gtknode',
    sources,
    c_args: ['-Wall', '-Wfatal-errors', '-Werror', '-Wpedantic'],
    include_directories: include_directories('src'),
    dependencies: gtkdep,
    version: '0.1',
)
pkg.generate(
    lib,
    description: 'A GTK+ based widget library to create functional flow graphs',
    url: 'https://space.univie.ac.at',
)
gnome.generate_gir(
    lib,
    nsversion: '0.1',
    namespace: 'Nodes',
)
```
3. Make C Plugin use `builddir/compile_commands.json`. Content:
  ```
[
  {
    "directory": "/home/user/Projects/gtknodes/builddir",
    "command": "ccache cc -Ilibgtknode.so.0.1.p -I. -I.. -I../src -I/usr/include/gtk-4.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/graphene-1.0 -I/usr/lib/x86_64-linux-gnu/graphene-1.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -mfpmath=sse -msse -msse2 -pthread -Wall -Wfatal-errors -Werror -Wpedantic -MD -MQ libgtknode.so.0.1.p/src_gtknode.c.o -MF libgtknode.so.0.1.p/src_gtknode.c.o.d -o libgtknode.so.0.1.p/src_gtknode.c.o -c ../src/gtknode.c",
    "file": "../src/gtknode.c",
    "output": "libgtknode.so.0.1.p/src_gtknode.c.o"
  }
]
```
4. Notice how cpptools will slowly eat away all RAM (16GB) and make desktop crash with OOM

Expected behavior:
It should not take up all memory

### Configuration and Logs

```shell
-------- Diagnostics - 1/3/2024, 6:08:09 PM
Version: 1.18.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/user/Projects/gtknodes/**"
    ],
    "defines": [],
    "cStandard": "c17",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "compileCommands": "/home/user/Projects/gtknodes/builddir/compile_commands.json",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "/home/user/Projects/gtknodes/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.18.3.0
No active translation units.
Browse Paths from compile_commands.json, from workspace folder: /home/user/Projects/gtknodes
    /home/user/Projects/gtknodes/builddir
    /home/user/Projects/gtknodes/builddir/.
    /home/user/Projects/gtknodes/builddir/..
    /home/user/Projects/gtknodes/builddir/../src
    /home/user/Projects/gtknodes/builddir/libgtknode.so.0.1.p
    /usr/include/blkid
    /usr/include/cairo
    /usr/include/freetype2
    /usr/include/fribidi
    /usr/include/gdk-pixbuf-2.0
    /usr/include/gio-unix-2.0
    /usr/include/glib-2.0
    /usr/include/graphene-1.0
    /usr/include/gtk-4.0
    /usr/include/harfbuzz
    /usr/include/libmount
    /usr/include/libpng16
    /usr/include/pango-1.0
    /usr/include/pixman-1
    /usr/include/uuid
    /usr/include/x86_64-linux-gnu
    /usr/lib/x86_64-linux-gnu/glib-2.0/include
    /usr/lib/x86_64-linux-gnu/graphene-1.0/include

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 27434
```

### Other Extensions

Meson and a gazillion others.

**Comment by browntarik** [comment]
Hi! 

After investigating and setting up the project as described I am unable to reproduce your issue. I am using the same compile commands.json that you provided with a meson build and get no indexing issue
![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/0d495ba3-d652-4d38-bd4a-65ce4870ca05)

The only difference between my log diagnostics and yours is the number of files that are being indexed:
-------- Diagnostics - 1/9/2024, 2:35:10 PM
Version: 1.18.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/browntarik/git/Investigations/11832/gtknodes/**"
    ],
    "defines": [],
    "cStandard": "c17",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "compileCommands": "/home/browntarik/git/Investigations/11832/gtknodes/compile_commands.json",
    "compilerPathIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compileCommandsInCppPropertiesJson": "/home/browntarik/git/Investigations/11832/gtknodes/compile_commands.json",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "/home/browntarik/git/Investigations/11832/gtknodes/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.18.3.0
Translation Unit Mappings:
[ /home/browntarik/git/Investigations/11832/gtknodes/src/gtknode.c ]:
    /home/browntarik/git/Investigations/11832/gtknodes/src/gtknode.c
Translation Unit Configurations:
[ /home/browntarik/git/Investigations/11832/gtknodes/src/gtknode.c ]:
    Process ID: 7580
    Memory Usage: 73 MB
    Compiler Path: /usr/bin/cc
    Includes:
        /home/browntarik/git/Investigations/11832/gtknodes/builddir/libgtknode.so.0.1.p
        /home/browntarik/git/Investigations/11832/gtknodes/builddir
        /home/browntarik/git/Investigations/11832/gtknodes
        /home/browntarik/git/Investigations/11832/gtknodes/src
        /usr/include/gtk-4.0
        /usr/include/gio-unix-2.0
        /usr/include/cairo
        /usr/include/pango-1.0
        /usr/include/harfbuzz
        /usr/include/fribidi
        /usr/include/gdk-pixbuf-2.0
        /usr/include/pixman-1
        /usr/include/uuid
        /usr/include/freetype2
        /usr/include/libpng16
        /usr/include/graphene-1.0
        /usr/lib/x86_64-linux-gnu/graphene-1.0/include
        /usr/include/libmount
        /usr/include/blkid
        /usr/include/glib-2.0
        /usr/lib/x86_64-linux-gnu/glib-2.0/include
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Defines:
        _FILE_OFFSET_BITS=64
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=110400
    compile_commands.json entry:
        directory: /home/browntarik/git/Investigations/11832/gtknodes/builddir
        file: ../src/gtknode.c
        command: ccache cc -Ilibgtknode.so.0.1.p -I. -I.. -I../src -I/usr/include/gtk-4.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/graphene-1.0 -I/usr/lib/x86_64-linux-gnu/graphene-1.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -mfpmath=sse -msse -msse2 -pthread -Wall -Wfatal-errors -Werror -Wpedantic -MD -MQ libgtknode.so.0.1.p/src_gtknode.c.o -MF libgtknode.so.0.1.p/src_gtknode.c.o.d -o libgtknode.so.0.1.p/src_gtknode.c.o -c ../src/gtknode.c
        output: libgtknode.so.0.1.p/src_gtknode.c.o
Total Memory Usage: 73 MB
Browse Paths from compile_commands.json, from workspace folder: /home/browntarik/git/Investigations/11832/gtknodes
    /home/browntarik/git/Investigations/11832/gtknodes/builddir
    /home/browntarik/git/Investigations/11832/gtknodes/builddir/.
    /home/browntarik/git/Investigations/11832/gtknodes/builddir/..
    /home/browntarik/git/Investigations/11832/gtknodes/builddir/../src
    /home/browntarik/git/Investigations/11832/gtknodes/builddir/libgtknode.so.0.1.p
    /usr/include/blkid
    /usr/include/cairo
    /usr/include/freetype2
    /usr/include/fribidi
    /usr/include/gdk-pixbuf-2.0
    /usr/include/gio-unix-2.0
    /usr/include/glib-2.0
    /usr/include/graphene-1.0
    /usr/include/gtk-4.0
    /usr/include/harfbuzz
    /usr/include/libmount
    /usr/include/libpng16
    /usr/include/pango-1.0
    /usr/include/pixman-1
    /usr/include/uuid
    /usr/include/x86_64-linux-gnu
    /usr/lib/x86_64-linux-gnu/glib-2.0/include
    /usr/lib/x86_64-linux-gnu/graphene-1.0/include

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 6077

Your number indicates 27434 vs my 6077, given that we are supposedly working within the same code repository, this suggests the crash is coming from a project elsewhere on your machine. The culprit could be a symbolic link in your filesystem that points to a parent folder on your machine causing a recursive crash.

Please provide more information to give a more accurate repro of your issue.
