### ISSUE TITLE
Language Server crashes after opening any XML file

### ISSUE THREAD

**Issue by HerrCraziDev** [microsoft/vscode-cpptools#11831]
### Environment

- OS and Version: Windows 11 Pro (latest)
- VS Code Version: 1.85.1 (latest)
- C/C++ Extension Version: 1.18.5, 1.19.1

### Bug Summary and Steps to Reproduce

This is an exact duplicate of #11453, which was closed when the OP had solved the issue by reinstalling VSCode.

Reinstalling VSCode and the C/Cpp extensions has no effect.

### Configuration and Logs

```shell
Occurs on the most basic projects. No specific configuration, a single `main.c` hello world and a single `sample.xml`.
```

### Other Extensions

**Disabling extensions has no effect - issue persists**

AbdAlMoniem-AlHifnawy.c-call-hierarchy
abusaidm.html-snippets
angelo-breuer.clock
anseki.vscode-color
arcensoth.language-mcfunction
Arm.cmsis-csolution
Arm.device-manager
Arm.embedded-debug
Arm.environment-manager
Arm.keil-studio-pack
Arm.remote-build
Arm.virtual-hardware
azemoh.one-monokai
ban.spellright
bedrankara.hoverconverter
blacktop.vscode-calc
cortex-debug.svd-viewer
dan-c-underwood.arm
DotJoshJohnson.xml
drkryz.drkryz-theme
eamodio.gitlens
ecmel.vscode-html-css
fes300.split-dig
firefox-devtools.vscode-firefox-debug
golang.go
GrapeCity.gc-excelviewer
gurumukhi.selected-lines-count
hashicorp.terraform
helsmy.autohotkey-debug
icrawl.discord-vscode
James-Yu.latex-workshop
jebbs.plantuml
jeff-hykin.better-cpp-syntax
JohnChabot.kos-vscode
mads-hartmann.bash-ide-vscode
maxerbox.vscode-discord
mgt19937.typst-preview
MinecraftCommands.syntax-mcfunction
monokai.theme-monokai-pro-vscode
MS-CEINTL.vscode-language-pack-fr
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.atom-keybindings
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.hexeditor
ms-vscode.vscode-embedded-tools
ms-vsliveshare.vsliveshare
notblank00.hexeditor
nvarner.typst-lsp
octref.vetur
qub.qub-xml-vscode
redhat.java
redhat.vscode-commons
redhat.vscode-xml
redhat.vscode-yaml
rioj7.FileGroup
rioj7.html-related-links
rogalmic.vscode-xml-complete
ryuta46.multi-command
shakram02.bash-beautify
shd101wyy.markdown-preview-enhanced
SPGoding.datapack-language-server
stkb.rewrap
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-french
stuart.unique-window-colors
tao-cumplido.inspector-hex
thqby.vscode-autohotkey2-lsp
timreilly.typewriter-sounds
tomoki1207.pdf
twxs.cmake
victoriadrake.kabukicho
VisualStudioExptTeam.vscodeintellicode
vsciot-vscode.vscode-arduino
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscode-icons-team.vscode-icons
xabikos.JavaScriptSnippets
xiaoyongdong.srecord
xuedao.super-themes
Zignd.html-css-class-completion

**Comment by browntarik** [comment]
Could you give more context, is your extension crashing every time you open a new xml file? Could you provide the files that are causing this issue? This will help to reproduce what you are experiencing. 

In the meantime, I would consider reinstalling the extension and VS Code to see if that works as well.

**Comment by browntarik** [comment]
Have you been able to reproduce this issue while disabling all other extensions. I am not able to reproduce it but my guess is this may be due to another extension. Our extension does not interact with xml files at all and should not crash the C++ extension.

Could you enable "C_Cpp.loggingLevel": "Debug" and provide the output of the C/C++ output channel? If you could provide crash stacks using the debugger as well that would help: https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv
