### ISSUE TITLE
Clang-Tidy is not working properly (clang-diagnostic-error)

### ISSUE THREAD

**Issue by RoyalXXX** [microsoft/vscode-cpptools#11838]
### Environment

**- OS and Version:** Windows_NT x64 10.0.19045
**- VS Code Version:** 1.85.1 (system setup)
**- C/C++ Extension Version:** v1.18.5

### Bug Summary and Steps to Reproduce

I enabled Clang-Tidy
![Screenshot 2024-01-04 142153](https://github.com/microsoft/vscode-cpptools/assets/125651292/015ea5e9-15c1-43cb-8935-449749b2abc8)
and now I see a lot of errors
![Screenshot 2024-01-04 142311](https://github.com/microsoft/vscode-cpptools/assets/125651292/041ed920-d121-475e-81c3-3b529b8a10da)
The linter triggers falsely.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "GCC-x64",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c23",
            "cppStandard": "c++23",
            "intelliSenseMode": "windows-gcc-x64",
            "compilerPath": "C:\\msys64\\ucrt64\\bin\\g++.exe"
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @RoyalXXX .  I believe what you're seeing is specific to clang-tidy itself.  Clang-tidy is based on clang.  Clang mimics GCC very closely, and is intended as a drop-in replacement.  What you're seeing is likely related to recent changes in GCC 13 not yet supported by clang-tidy.  Searching the web, I see various other tools impacted by similar errors with GCC's new float types.

We bundle a version of clang-tidy with the C/C++ extension, but it's also possible to specify your own executable, if you'd like to install newer or prerelease versions of clang-tidy. That can be done with the `C_Cpp.codeAnalysis.clangTidy.path` setting.

I'm closing this issue, as I don't believe there is any action for us that could address this.
