### ISSUE TITLE
incomplete type is not allowed: ::google::protobuf::Message

### ISSUE THREAD

**Issue by sillykelvin** [microsoft/vscode-cpptools#1183]
When opening the header file generated by google's protobuf, it reports:

    incomplete type is not allowed
    namespace "google::protobuf" has no member "Metadata"

- OS: Ubuntu 16.04
- VSCode version: 1.17.2
- C/C++ extension version: 0.14.0
- Reproduce step:

```
    mkdir /tmp/test
    cd /tmp/test
    echo 'message hello { optional int32 world = 1; }' > test.proto
    /path/to/protoc --cpp_out=. test.proto
```
now open the folder in vscode, and open file `test.pb.h`, the errors will be there.

- c_cpp_properties.json

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include/c++/5.4.0",
                "/usr/include/x86_64-linux-gnu/c++/5.4.0",
                "/usr/local/include",
                "/usr/lib/clang/3.8.0/include",
                "/usr/include",
                "/usr/include/x86_64-linux-gnu",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include/c++/5.4.0",
                    "/usr/include/x86_64-linux-gnu/c++/5.4.0",
                    "/usr/local/include",
                    "/usr/lib/clang/3.8.0/include",
                    "/usr/include",
                    "/usr/include/x86_64-linux-gnu",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```

- C/C++ related configuration in settings.json:

```
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.loggingLevel": "Information",
    "C_Cpp.clang_format_path": "/usr/bin/clang-format",
```

- Other information: protobuf version: 2.6.1, installed with `sudo apt install libprotobuf-dev`, header files are installed in `/usr/include`, when using "Go to Definition", vscode can successfully find the definition of `::google::protobuf::Message` defined in `/usr/include/google/protobuf/message.h`.

**Comment by bobbrow** [comment]
If the protobuf headers are in your browse.path and navigation is working, then the light bulb suggestions for updating your `includePath` should also be available.  Go to the #include line where you include protobuf headers, click on the squiggle and then click on the light bulb to add the necessary paths to the `includePath`.

**Comment by sillykelvin** [comment]
No, there are no any suggestions about `includePath` updating, the headers included in `test.pb.h` are all placed in `/usr/include/google/protobuf`, which is already added to `includePath`, the following are the included headers:

```
#include <string>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>

// ... other irrelevant code here
```

**Comment by bobbrow** [comment]
Ok, I figured it out.  You need to add "GOOGLE_PROTOBUF_NO_THREAD_SAFETY" to the `"defines"` array in your **c_cpp_properties.json**.  <google/protobuf/stubs/once.h> seems to need this define set in order to define types required by some of the classes.

**Comment by sillykelvin** [comment]
Wow, that works now! Thanks for your great help!

However, there might be many other similar problems like this (errors at last turn out to be an irrelevant macro definition problem), especially for these third party libraries, is there a better way or generic solution to find out the root cause of this kind of problem?

**Comment by bobbrow** [comment]
We recently added support for reading the compile_commands.json format that a few build systems are capable of generating.  But in general, it's hard to know what includes and defines a random file is going to be dependent on without getting some information from your build system.

**Comment by sillykelvin** [comment]
As you mentioned build system, I then realized that I have never defined the macro `GOOGLE_PROTOBUF_NO_THREAD_SAFETY` in my build system (cmake), and the project **compiles without error**. So why do we need to define this macro in c_cpp_properties.json to make vscode happy?

**Comment by bobbrow** [comment]
Oh, I'm sure there's something else that should be set (or is set by the library if some other define is set), but I don't know this library well enough and didn't have the time to solve it.  The name of the define I sent you was suspect to me, but should work for now as far as IntelliSense is concerned.  Do you define anything else in your build system?  This library could be dependent on some other standard define that we're not sending down by default.  We plan to send more of Clang's default defines to the IntelliSense engine in a future update, but we haven't identified the most important ones yet.

**Comment by sillykelvin** [comment]
I think you mean something looks like the following:

```
#ifdef ANOTHER_MACRO
    #define GOOGLE_PROTOBUF_NO_THREAD_SAFETY
#endif
```

But unfortunately, there is no macros defined in the build system, in the example I gave in my first comment, the source file can be compiled with a simple command: `clang++ -c test.pb.cc` without any error, besides, a `grep` in `/usr/include/google/protobuf` gives the following result:

```
stubs/atomicops.h:57:#ifndef GOOGLE_PROTOBUF_NO_THREAD_SAFETY
stubs/atomicops.h:225:#endif  // GOOGLE_PROTOBUF_NO_THREAD_SAFETY
stubs/once.h:87:#ifdef GOOGLE_PROTOBUF_NO_THREAD_SAFETY
stubs/once.h:140:#endif  // GOOGLE_PROTOBUF_NO_THREAD_SAFETY
```

So it seems this macro has nothing to do with other macros, I thinks there might still be some problems in the IntelliSense engine.

**Comment by zz1120122573** [comment]
Hi, I'm using VS2015 and get a simillar error. How can I set CPPFLAGS in VS2015? I cannot find the solution on Google. Thanks.
