### ISSUE TITLE
Troubleshooting VSCode Terminal Crash when trying to open Python terminal

### ISSUE THREAD

**Issue by josemanuel22** [microsoft/vscode-cpptools#11840]
### Environment

- OS and version: Darwin arm64 22.3.0
- VS Code: 1.83.0 (Universal)
- Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:15.449Z (3 mos ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
- python extension: Python 3.10.9

### Bug Summary and Steps to Reproduce

Bug Summary:

I have the following problem when trying to launch and execute Python code in the integrated terminal of my VSCode or even when I simply try to open it. The terminal opens for a few seconds and then automatically closes (crashes) and a popup warning appears indicating Cannot read properties of undefined (reading 'show')

The console developper tools is:
<img width="751" alt="Screenshot 2024-01-05 at 11 20 50" src="https://github.com/microsoft/vscode-cpptools/assets/10698012/e5e29dc4-1997-4e06-8bf2-93378008617a">
. Attached are images.

### Debugger Configurations

```shell
`launch.json`
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true
        }
    ]
}
```

### Debugger Logs

```shell
`launch.json`
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true
        }
    ]
}
```

**Comment by browntarik** [comment]
Hi! It looks like this is an issue that should be filed with the VS Code Python team which you can do here: https://github.com/microsoft/vscode-python/issues

I will now close this issue as unrelated to the C++ extension.
