### ISSUE TITLE
Doxygen @details support

### ISSUE THREAD

**Issue by davidheiss** [microsoft/vscode-cpptools#11842]
### Feature Request

Hey, just want to make a feature request for the Doxygen support.
Besides the support for the `@brief` keyword, I think it would make sense to support the `@details` keyword as well.

This feature request also kinda relates to this: #5903.

```c
/*!
 * @brief Brief description.
 * @details Detailed description.
 */
int f() {
    return 0;
}

**Comment by browntarik** [comment]
Thank you for submitting your request!

**Comment by browntarik** [comment]
After further investigation, it looks like we do support this tag within our tooltip. To use this tag simply add details to the list of doxygen section tags.

![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/f6d43abe-8f03-4fb5-b458-6bcb06f6fdd9)

 I will close this issue unless there are further concerns.

**Comment by 0Grit** [comment]
@browntarik I believe it's broken though. Please see https://github.com/microsoft/vscode-cpptools/issues/5903

**Comment by Mode-77** [comment]
> @browntarik I believe it's broken though. Please see #5903

You have to mark the details section with `@details` or `\details` for the tooltip to show it. The implied style without the marker doesn't work.
