### ISSUE TITLE
No Goto Definition available

### ISSUE THREAD

**Issue by Tecnologic** [microsoft/vscode-cpptools#11865]
Type: <b>Bug</b>

Open a .c/.cpp file, then right click a local symbol. I expect to have the point "go to definition" in that menu but nothing. CTRL+Click does not work as well as F12 and in the command palette there is also not "go to definition" to befound. Intellisense is active according to settings.

Extension version: 1.19.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-11855M CPU @ 3.20GHz (12 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.20GB (19.62GB free)|
|Process Argv|--crash-reporter-id 422fca08-6870-49f8-bc1f-2864aa7dae39|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by browntarik** [comment]
There could be a few causes of your issue. Could you please provide the output from the C/C++: Log Diagnostics command? This will allow us to find the specific cause of your issue.

**Comment by Tecnologic** [comment]
[Extension_host_log.txt](https://github.com/microsoft/vscode-cpptools/files/13954688/Extension_host_log.txt)
Here is a log from the extension host.

**Comment by browntarik** [comment]
![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/7087ffb7-ab95-4def-85f6-38f6782d1a8d)

When viewing a cpp file, you should be able to run the above command which will give you output that looks something like this:

**Comment by Tecnologic** [comment]
![image](https://github.com/microsoft/vscode-cpptools/assets/1442404/e0274f70-0b81-41ec-8cd5-aa93c8c1d4ab)
sry i dont have that option.

**Comment by Tecnologic** [comment]
![image](https://github.com/microsoft/vscode-cpptools/assets/1442404/f87d4f01-6909-49e5-a851-56f9592b8d34)
i dont know whats wrong with my cpp extension. this was all working but no it does not. Everywere i looked it says the cpp extension is up an running fine but. looks like nothing is running. Even other extension like "better c++ Syntax" are not working. Can it be that a .cpp file is somehow not accociated with being acutal C++ code?

**Comment by Tecnologic** [comment]
I checked that option several times. it was set to default. i tryed clang and msvc as well there but that did not change anything. 
i now deleted my cloud settings and the settings in appdata. And now the issue is gone. So i think its some sort of setting i made or was coming though an update which screwed everthing up. I will now put my settings back as i want them if i encounter the issue again i'll reopen this issue.

Thanks for ur help.
