### ISSUE TITLE
IntelliSense Deactivation Leads to Formatting Failure

### ISSUE THREAD

**Issue by andylizf** [microsoft/vscode-cpptools#11867]
### Environment

- OS and Version: Windows 11 Pro 22H2 22621.2861
- VS Code Version: 1.85.1
- C/C++ Extension Version: 1.18.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

When IntelliSense is disabled in Visual Studio Code using the C/C++ extension, code formatting features also cease to function. This behavior seems unintended and limits functionality when IntelliSense is not needed.

Steps to reproduce:
1. Disable IntelliSense of the C/C++ extension in the Visual Studio Code settings.
2. Attempt to format a C/C++ file using the standard format command or keyboard shortcut.

Expected behavior:

### Configuration and Logs

```shell
loggingLevel: Debug
intelliSenseEngine is disabled
```

**Comment by browntarik** [comment]
Hi! This is a known feature request from our users. You can find more information and track the issue here: https://github.com/microsoft/vscode-cpptools/issues/7083

For now this issue will be closed as a duplicate. 

Thank you.
