### ISSUE TITLE
Spurious error squiggles in large numbers, not seen in Atom PIO

### ISSUE THREAD

**Issue by frank3141** [microsoft/vscode-cpptools#1186]
OS WIndows 10 Pro Version 1703
VSCode Version 1.17.2 regular version
Platform espressif32
Framework framework = espidf
board = esp32dev

Problem, Many definitions in include files are listed as undefined when they are not
in in he following code
void connected_cb(void *self, void *params)
{
    mqtt_client *client = (mqtt_client *)self;
    mqtt_subscribe(client, "/test", 0);
    mqtt_publish(client, "/test", "howdy!", 6, 0, 0);
}
mqtt_client is listed as undefined  
The line is flagged by expected an expression and as missing a ;
The Program links and loads and executes properly, the message to /test "howdy" appears at the broker, as it should.
None of this occurs in the Atom variant of Platformio
Another example
In this code
mqtt_settings settings = {
    .host = "1xxx.xxx.xxx.xxx",
#if defined(CONFIG_MQTT_SECURITY_ON)
    .port = 8883, // encrypted
#else
    .port = 1883, // unencrypted
#endif
    .client_id = "mqtt_client_id",
    .username = "user",
    .password = "pass",
    .clean_session = 0,
    .keepalive = 120,
    .lwt_topic = "/lwt",
    .lwt_msg = "offline",
    .lwt_qos = 0,
    .lwt_retain = 0,
    .connected_cb = connected_cb,
    .disconnected_cb = disconnected_cb,
    .subscribe_cb = subscribe_cb,
    .publish_cb = publish_cb,
    .data_cb = data_cb
};

mqtt_settings is flagged as undefined.
It is defined in mqtt.h
typedef struct mqtt_settings {
    mqtt_connect_callback connect_cb;
    mqtt_disconnect_callback disconnect_cb;

    mqtt_read_callback read_cb;
    mqtt_write_callback write_cb;

    mqtt_event_callback connected_cb;
    mqtt_event_callback disconnected_cb;

    mqtt_event_callback subscribe_cb;
    mqtt_event_callback publish_cb;
    mqtt_event_callback data_cb;

    char host[CONFIG_MQTT_MAX_HOST_LEN];
    uint32_t port;
    char client_id[CONFIG_MQTT_MAX_CLIENT_LEN];
    char username[CONFIG_MQTT_MAX_USERNAME_LEN];
    char password[CONFIG_MQTT_MAX_PASSWORD_LEN];
    char lwt_topic[CONFIG_MQTT_MAX_LWT_TOPIC];
    char lwt_msg[CONFIG_MQTT_MAX_LWT_MSG];
    uint32_t lwt_msg_len;
    uint32_t lwt_qos;
    uint32_t lwt_retain;
    uint32_t clean_session;
    uint32_t keepalive;
    bool auto_reconnect;
} mqtt_settings;

Which is included in the source file in which it is flagged, app_main.c
There are 25 of theses in app _main alone
Exit and reenter vscode has no effect, trivial edits and compiles has no effect
clean and compile has no effect
Program does link and run correctly so the error flags are being ignored by the linker in these cases.  If a real error is introduced it will not link or execute.

**Comment by bobbrow** [comment]
Arduino?  Our extension doesn't know anything about Arduino default includes right now, so unless you explicitly add them with #include, we can't find the symbols you're listing here.

**Comment by sean-mcmanus** [comment]
You might want to try the Arduino extension: https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino

**Comment by frank3141** [comment]
Thanks for the response. The Arduino extension is not able to do what I need to do.  
Frank


Sent from my Samsung Galaxy Tab®|PRO

-------- Original message --------

**Comment by frank3141** [comment]
Not using Arduino, using espidf wit freertos. Includes are explicit in the code, e.g. #include "mqtt.h"  Frank




Sent from my Samsung Galaxy Tab®|PRO

-------- Original message --------

**Comment by bobbrow** [comment]
Ok.  A quick search tells me this uses MinGW on Windows.  Have you looked at our [example c_cpp_properties.json for MinGW](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md)?

The most important thing to check is that "intelliSenseMode" is set to "clang-x64" in your **c_cpp_properties.json** since Windows configs default to msvc-x64 which won't work well with MinGW.

**Comment by bobbrow** [comment]
We believe this issue has been addressed in the latest version of the extension.  If you are still experiencing problems, please let us know.
