### ISSUE TITLE
Include path settings don't trim white space

### ISSUE THREAD

**Issue by pwintz** [microsoft/vscode-cpptools#11862]
Type: <b>Bug</b>

I have files I want C++ to include in the directory /usr/local/include. 
When I added "/usr/local/include " (with a space at the end) to the "Include path" configuration for the C/C++ extension, a warning is shown below the box that says, "Cannot find: /usr/local/include "
The trailing white space for each line should be trimmed so that such a warning is not shown.

Extension version: 1.18.5
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.22GB free)|
|Process Argv|--crash-reporter-id 52a0bd83-cab4-40c3-bdc8-a0e3553af2a2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Scarab-MPC Development Container|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|7.63GB (5.70GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by pwintz** [comment]
Here is a screenshot of the warning:
![image](https://github.com/microsoft/vscode-cpptools/assets/19618780/bc398fb2-9304-42dd-aed9-8cc93a720f64)

**Comment by browntarik** [comment]
Thank you for submitting this issue! We are currently looking into this.

**Comment by Colengms** [comment]
It's valid for there to be spaces in directory or file names. It seems wrong to me to trim whitespace from a user-provided path, and prevent a valid scenario, regardless of how unlikely.  I'd suggest we put quotes around the path in the error message, so the spaces are apparent rather than invisible.

**Comment by bobbrow** [comment]
The current plan is to only automatically remove the whitespace if the path with whitespace does not exist.

**Comment by sean-mcmanus** [comment]
@pwintz Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.3
