### ISSUE TITLE
Fuzzy Search for C/C++ Global Symbols

### ISSUE THREAD

**Issue by aboutzero** [microsoft/vscode-cpptools#11866]
### Feature Request

It is not convenient that someone wants to search global symbols but has forgotten a concrete spelling when users are reading large projects.
So, creating a feature to support fuzzy search is brilliant.

**Comment by sean-mcmanus** [comment]
You can upvote the existing issue that we're already tracking at https://github.com/microsoft/vscode-cpptools/issues/2751 .
