### ISSUE TITLE
Add support for clang IntelliSense mode with compile_commands.json

### ISSUE THREAD

**Issue by ruipires** [microsoft/vscode-cpptools#1187]
Configuring project to use compileCommands.json generated by CMake for a simple test project is failing to include compiler's built in include directories.

Using this sample project: https://github.com/jameskbride/cmake-hello-world
I am unable to get cpptools to recognize stdio.h or iostream.

I am able to compile (by running make externally) ok.

Unsure what I am doing wrong, is there a way to inform cpptools of where the compiler's default include directories are?

    * Operating System and version: Windows 7
    * VS Code version: 1.17.2
    * C/C++ extension version 0.14.0

**Comment by jophippe** [comment]
Do you have Visual Studio installed? Right now on Windows we only pull the system headers from the MSVC compiler from Visual Studio. Based on the fact that you build using make, it sounds like you're using Linux subsystem for Windows, correct? We should try to pull system headers from there if Visual Studio isn't installed, instead of just giving up. Thanks for bringing this to our attention. Unfortunately, there is no way to give intellisense include paths when using compileCommands, so the workarounds for now are either install Visual Studio or go back to using includePath. We'll work on fixing this

**Comment by ruipires** [comment]
My scenario is a bit on the unusual side.

I have a local checkout for code that I want to edit.
The compiler itself (and its includes) in on a remote linux server.
I have a version gcc installed locally that I used to check the code was compiling (I don't actually use it for anything else).

I assumed cpptools was using clang internally.

I will try to install some version of visual studio and see if this serves as a workaround in my particular case.

If there was a way to specify where the builtin headers are I could get a copy of them on my local machine and everything else should (in theory) work.

**Comment by bobbrow** [comment]
Can you share one of the entries from your compile_commands.json so that we have it for a reference?

**Comment by ruipires** [comment]
Of course I can.

compile_commands.json:
```
[
{
  "directory": "C:/Data/rupires/Desktop/dev/sample_cmake/cmake-hello-world/bin",
  "command": "C:/Strawberry/c/bin/c++.exe   @CMakeFiles/CMakeHelloWorld.dir/includes_CXX.rsp   -o CMakeFiles/CMakeHelloWorld.dir/HelloWorld.cpp.obj -c C:/Data/rupires/Desktop/dev/sample_cmake/cmake-hello-world/HelloWorld.cpp",
  "file": "C:/Data/rupires/Desktop/dev/sample_cmake/cmake-hello-world/HelloWorld.cpp"
},
{
  "directory": "C:/Data/rupires/Desktop/dev/sample_cmake/cmake-hello-world/bin/Hello",
  "command": "C:/Strawberry/c/bin/c++.exe      -o CMakeFiles/Hello.dir/Speaker.cpp.obj -c C:/Data/rupires/Desktop/dev/sample_cmake/cmake-hello-world/Hello/Speaker.cpp",
  "file": "C:/Data/rupires/Desktop/dev/sample_cmake/cmake-hello-world/Hello/Speaker.cpp"
}
]
```

"Strawberry" in the path refers to https://chocolatey.org/packages/StrawberryPerl .
As I said, I just used that compiler to do a quick test on the code, it is not what I use to compile code usually (but it works!).

The command line arguments file referenced in the json (@CMakeFiles/CMakeHelloWorld.dir/includes_CXX.rsp) has the following contents: 

`-IC:/Data/rupires/Desktop/dev/sample_cmake/cmake-hello-world/Hello 
`

**Comment by jwatt** [comment]
I seem to have the same problem, but with clang. The includes only seem to be resolved against the paths in compile_commands.json, so includes of headers that should be found under clang's built-in include paths are not resolving.

**Comment by bobbrow** [comment]
@jwatt, are you also using MinGW on Windows?  If not, please open a new issue as we would like to understand your case better.

**Comment by ruipires** [comment]
Installed [visual studio 2017 (only the build tools)](http://landinghub.visualstudio.com/visual-cpp-build-tools), specifically for testing this.
Issue remains, but is a bit different now:
stdio.h is still not found.
iostreams now shows that corecrt.h is not found (dependency of iostream).

**Comment by bobbrow** [comment]
Sorry @ruipires, I should have noticed sooner.  For Windows and msvc-x64 intelliSenseMode, the expectation is that you are using Visual Studio and have a [Windows SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk) installed.  The missing headers are in the Windows SDK.

We will work to improve your case though by supporting clang-x64 mode with compile_commands.json in a future release.

**Comment by ruipires** [comment]
Thanks for taking the time to understand my issue :)

Just one note, since I have a very particular setup.
I use visual studio code under windows to navigate and edit code that I will ultimately compile in a remote linux server.
This may mean that the built-in headers for the compiler I end up using are not the same as clang-x64 running under windows (my target architecture is ppc).

I'd like to ask you to take this into consideration and add an option to add additional include paths to those declared in the json compilation db.
I guess adding those defined in the c_cpp_properties.json to the ones defined in the json compilation db would do the trick.

But for other more straightforward use cases, detecting them automatically would certainly be more user friendly.

**Comment by ngg** [comment]
I think I have this same problem on Linux with clang. My compile_commands.json contains some include files for dependencies but do not include the usual default include paths like `/usr/include` and `/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6`. These are properly found when generating `c_cpp_properties.json`, but if I set `compileCommands` then those do not work anymore. Is there any progress on this issue?

**Comment by sean-mcmanus** [comment]
@ngg Your issue appears to be different. Can you file a new issue with more repro info? The original issue is using compile_commands.json on Windows with clang-x64 intelliSenseMode. Our compile commands code attempts to query the compile commands compiler for default include path settings. Your issue might be https://github.com/Microsoft/vscode-cpptools/issues/1251 if your command doesn't include the compiler. Otherwise, it could be a bug caused by the ordering of the compile commands include paths, which appears to be incorrect (compiler defaults, then workspaceRoot, then -I/isystem paths).

**Comment by gagbo** [comment]
@ngg Did you find a workaround eventually ? I'm running in the same issue as you and can't find any help on the subject

EDIT : small but *not* a minimal example, but if you can compile against Qt5 you can try using a compilation database on this [small repo](https://github.com/gagbo/flocking)

**Comment by sean-mcmanus** [comment]
@gagbo It could be due to the fact that we don't query the compiler for the defines set and we don't pass in the language version (or we're picking the unintended compiler, because with compileCommands we use the compiler in the "command" but without it we just guess), which we're in the process of fixing. There is no workaround yet if you're using a compile_commands.json.

**Comment by gagbo** [comment]
Thanks for your answer, for the record it definitely seems to be related to not querying the compiler for includes : 
- When I keep a default (blank) c_cpp_properties.json file, I have no issues with system includes but the project includes are not found (in a rather complex cmake project)
- When I add the compileCommands key to the c_cpp_properties json, all project includes are found without problem until it hits system includes, which Code doesn't get (`cannot open source file "map" (dependency of "other_file.h")` or `cannot open source file "stddef.h" (dependency of "yet_another_file.h")`)

**Comment by jwatt** [comment]
> we don't query the compiler for the defines set

I think I read a comment from you elsewhere saying that is now fixed. Presumably also for compiler default include paths.

**Comment by Colengms** [comment]
I believe this issue has been addressed.  Clang should receive clang mode intelliSense, unless Windows SDK headers are detected.    There have also been some fixes to querying clang for system includes and defines  If anyone on this thread is still experiencing a problem reported here, please open a new issue.
