### ISSUE TITLE
defines c_cpp_properties.json seems not processed 

### ISSUE THREAD

**Issue by lonejack** [microsoft/vscode-cpptools#11880]
### Environment

- OS and Version: Linux claudio-i7 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- VS Code Version: 1.85.1
- C/C++ Extension Version: v1.18.5
- If using SSH remote, specify OS of remote machine: NO

### Bug Summary and Steps to Reproduce

Bug Summary:
When I open a file the processed file seems invalid

Steps to reproduce:
In configuration I've set these:
"configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "MG_ARCH=5
..

When open a header file like this:
#if !defined(MG_ARCH)
/* (A) */
#if defined(__unix__) || defined(__APPLE__)
**#define MG_ARCH MG_ARCH_UNIX**
#elif defined(_WIN32)
#define MG_ARCH MG_ARCH_WIN32
#elif defined(ICACHE_FLASH) || defined(ICACHE_RAM_ATTR)
#define MG_ARCH MG_ARCH_ESP8266
#elif defined(__ZEPHYR__)
..
/* (B) */
#endif

Expected behavior:
Because I set MG_ARCH in c_cpp_properties.json I would expect to skip the file form (A) to (B). Instead this don't happen. The VinsualStudioCode consider valid the bold line:
MG_ARCH MG_ARCH_UNIX
![image](https://github.com/microsoft/vscode-cpptools/assets/933876/f079c74e-e656-4961-9046-7a2676e37cad)

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "MG_ARCH=5",
                "MG_DEVICE=MG_DEVICE_STM32H7",
                "MG_ENABLE_TCPIP=1",
                "MG_ENABLE_DRIVER_STM32H=1",
                "MG_IO_SIZE=4096",
                "MG_ENABLE_CUSTOM_RANDOM=1",
                "MG_ENABLE_PACKED_FS=1",
                "MG_ENABLE_FILE=0"
            ],
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "gcc-arm",
            "mergeConfigurations": false,
            "compileCommands": "${workspaceFolder}/build/compile_commands.json",
            "compilerPath": "/opt/st/stm32cubeide_1.14.0/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.11.3.rel1.linux64_1.1.100.202309141235/tools/bin/arm-none-eabi-gcc",
            "browse": {
                "path": [
                    "${workspaceFolder}/**"
                ],
                "limitSymbolsToIncludedHeaders": true
            }
        },
        {
            "name": "NucleoBoard",
            "includePath": [
                "${default}"
            ],
            "defines": [
                "MG_ARCH=5",
                "MG_DEVICE=MG_DEVICE_STM32H7",
                "MG_ENABLE_TCPIP=1",
                "MG_ENABLE_DRIVER_STM32H=1",
                "MG_IO_SIZE=4096",
                "MG_ENABLE_CUSTOM_RANDOM=1",
                "MG_ENABLE_PACKED_FS=1",
                "MG_ENABLE_FILE=0"
            ],
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "gcc-arm",
            "mergeConfigurations": false,
            "compileCommands": "${workspaceFolder}/build/compile_commands.json",
            "compilerPath": "/opt/st/stm32cubeide_1.14.0/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.11.3.rel1.linux64_1.1.100.202309141235/tools/bin/arm-none-eabi-gcc",
            "browse": {
                "path": [
                    "${workspaceFolder}/**"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
```

**Comment by lonejack** [comment]
After I set this(.vscode/settings.json):
"C_Cpp.default.intelliSenseMode": "gcc-arm"
it works

**Comment by Colengms** [comment]
Hi @lonejack .  I see in your configuration that you have specified a `compileCommands` file.

```
            "compileCommands": "${workspaceFolder}/build/compile_commands.json",
```

If a file is found in a `compile_commands.json`, the command line there will supersede the configuration in your `c_cpp_properties.json`.  Could this explain why you're seeing a configuration for a file differ from your `c_cpp_properties.json`?
