### ISSUE TITLE
include thirdParty's  header file and lib(gtest), cannot compile

### ISSUE THREAD

**Issue by Yensan** [microsoft/vscode-cpptools#1188]
I want to use gtest (google C/C++ unittest frame) in Win+MinGW+VScode, but when I 
1. build the gtest and copy the header file and lib file to the project folder
2. edit `c_cpp_properties.json` 's  ` "includePath": ` and  `"browse": {"path": ` successfully( VS code can broswer the hearder files,  Include Autocomplete && C/C++ plugin intelliSenseEngine works fine, not pop up error about the header)
3.  c**annot compile with gtest.**

How can I use gtest in VScode? And, how to use third party's `source  file` / `header_file+lib_file` to create a  new project in VScode? thank you.

**Comment by sean-mcmanus** [comment]
This isn't a gtest issue page, but it looks like you've already posted a question there: https://github.com/google/googletest/issues/1314 . According to this vscode post (https://github.com/Microsoft/vscode/issues/24867 ), other VS Code users are able to use gtest. Maybe @o-lim can help you.

**Comment by Yensan** [comment]
@sean-mcmanus 
sean,  I have compiled the gtest iframe, and got the header file/ binary lib file.
but , I can't compile my test case with the gtest header file/ binary lib file（gtest 1.7.0）. Although I can put the frame in MinGW dir and compile/run it,  but for most IDE, combine thirdParty's src or header&lib in a project is not rare. But I don't know how to do it (or, it just can't)
So, this is not gtest's issue! Maybe you would re-open this issue. 
Thank you for reply and help.

**Comment by Yensan** [comment]
@sean-mcmanus
Hi, Sean, I solved this problem. Now I use Gtest in VScode to write C code. That is so great.
Maybe I can draft a markdown to you, so that VScode users all can use gtest.
