### ISSUE TITLE
VS Code showing output of old version of code

### ISSUE THREAD

**Issue by printfpratham** [microsoft/vscode-cpptools#11883]
I am facing this weird issue.
whenever I start VS Code and compile my C program it successfully gets compiled and run but when I tweak the code or make some changes and again try to build and compile, the output of the program does not change means the output and everything stays the same like the first time i ran the code. It does not show my changes like it compiled the old version of my program again. 

To get the output of latest code i have to reopen the VS Code again then build the project every time. It is so annoying that i have to close and reopen the app to see the small changes in my code.

**Comment by Colengms** [comment]
Hi @printfpratham .  Aside from features that can generate a command line for a `task.json` or `launch.json`, to build/debug a single source-file (for simple, single-source scenarios), the C/C++ Extension itself is not involved in the build process.  It's a language service extension (for IntelliSense and other editor features). It doesn't provide a compiler and doesn't itself perform build operations. Your issue would seem to be related to the build process.

How are you building your program? Are you using a single command line or a build system such as CMake? Is there anything output from that build when it fails to update the built binary?
