### ISSUE TITLE
Strange result of sizeof operator for size_t type

### ISSUE THREAD

**Issue by AlanTeixeiraNM** [microsoft/vscode-cpptools#11881]
### Environment

- OS and Version:  Windows 11 Home single language version 10.0.22621
- VS Code Version: Code 1.85.2
- C/C++ Extension Version: v1.18.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary: 
In my C++ implementation _size_t_ is an alias for _unsigned long long_ which has size 8 bytes, but _sizeof_ operator returns different results when applied to _size_t_ and _unsigned long long_

Steps to reproduce:
Just compile and run a source file with the code:

```
std::cout<<sizeof(size_t)<<'\n';
std::cout<<sizeof(unsigned long long);
```

Expected behavior:
The first line prints 4 and the second line prints 8.

### Configuration and Logs

```shell
c_cpp_properties.json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.20348.0",
            "compilerPath": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx86/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++23",
            "intelliSenseMode": "windows-msvc-x64"
        }
    ],
    "version": 4
}

C/C++ Log Diagnostics
-------- Diagnostics - 1/19/2024, 9:10:15 AM
Version: 1.18.5
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "c:/Users/alant/Codeprojects/test/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.20348.0",
    "compilerPath": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx86/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++23",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx86/x64/cl.exe",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "c:/Users/alant/Codeprojects/test/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.18.3.0
Translation Unit Mappings:
[ C:\Users\alant\Codeprojects\test\test.cpp ]:
    C:\Users\alant\Codeprojects\test\test.cpp
Translation Unit Configurations:
[ C:\Users\alant\Codeprojects\test\test.cpp ]:
    Process ID: 15428
    Memory Usage: 376 MB
    Compiler Path: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx86\x64\cl.exe
    Includes:
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\atlmfc\include
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt
        C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\Include\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\cppwinrt
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++latest
    IntelliSense Mode: windows-msvc-x64
    Other Flags:
        --using_directory
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\lib\x86
        --using_directory
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib\x86
        --using_directory
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib\x86\store\references
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0
        --using_directory
        C:\Windows\Microsoft.NET\Framework\v4.0.30319
Total Memory Usage: 376 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 9864
```

### Other Extensions

<html>
<body>

The issue persists after disabling the extensions.

List of Extension | version:

doxdocgen | 1.4.0

better-cpp-syntax | 1.17.2

vscode-language-pack-pt-BR | 1.85.2024011709

python | 2023.22.1

vscode-pylance | 2023.12.1

cpptools | 1.18.5

cpptools-extension-pack | 1.3.0

<span style="color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(24, 31, 47); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(1 theme extensions excluded)</span>
</body>
</html>

**Comment by Colengms** [comment]
Hi @AlanTeixeiraNM .  `size_t` should be 4 bytes when compiling for x86, and 8 bytes when compiling for x64.  In your configuration, an x64 compiler and IntelliSenseMode are specified.

```
"intelliSenseMode": "windows-msvc-x64"
```

Given that your compilation is generating code that produces a value of 4, it sounds like you're compiling for x86.  If you want to compile for x86, I believe you'll need to update your build system or compile command line to use the appropriate `cl.exe` executable path.  The 'Host' part of the path refers to the host system architecture. If you're running on x64 Windows, you'll want to use a `Hostx64` path.  The next part of the path refers to the target architecture. You'll want to change that to `x86`, if you prefer to target x86. If so, you'll also want to update the `intelliSenseMode` value in your configuration to refer to x86. (I believe you could also remove that field, and it should match the compiler by default). If the compiler is missing from any of these paths, it should be possible to install it using the Visual Studio Installer.

**Comment by AlanTeixeiraNM** [comment]
Hi @Colengms, thanks for commenting. I'm running on x64 Windows and targeting x64 Windows (just studying the new standard). 
I changed the executable path to

_C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe_

and selected _${default}_ option for intelliSenseMode, closed the working folder and relaunched VS Code from there again but still have the same result.

**Comment by Colengms** [comment]
Hi @AlanTeixeiraNM .  Where did you change the path?  It sounds like you've changed your IntelliSense configuration to refer to the x64-hosted version of the compiler. Since the C/C++ Extension doesn't actually invoke `cl.exe`, that change would not have an effect. Your IntelliSense was already configured for an x64 target.  Rather, since you're seeing a size of 4 for `size_t` output from your compiled program, that would suggest your compilation command line is referring to an x86-targeting compiler.  (For x64, that size should be 8). If you're using a generated `tasks.json` or `launch.json`, the compiler path there likely needs to be updated to refer to an x64-targeting version of `cl.exe`.  Or, if you're using a build system such as CMake, the compiler may need to be explicitly specified there.

**Comment by AlanTeixeiraNM** [comment]
These are my tasks.jason and launch.jason. I don't fully understand all the details of the cofiguration of all .jason files, so I might be doing something wrong. 

```
"tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: cl.exe build active file",
            "command": "C:/Program Files/Microsoft VisualStudio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe",
            "args": [
                "/Zi",
                "/EHsc",
                "/nologo",
                "/std:c++latest",
                "/Fe${fileDirname}\\${fileBasenameNoExtension}.exe",
                "test.cpp",
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$msCompile"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"


 "configurations": [
        {
            "name": "C/C++: cl.exe build and debug active file",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "integratedTerminal",
            "preLaunchTask": "C/C++: cl.exe build active file"
        }
    ],
    "version": "2.0.0"
```

**Comment by Colengms** [comment]
Hi @AlanTeixeiraNM .  Can you provide the output of running a build?  That should reflect exactly what command-line is invoked.  When using equivalent paths, args and the following code:

```
void main()
{
    std::cout << sizeof(size_t) << '\n';
    std::cout << sizeof(unsigned long long);
}
```

I'm getting the following output:

```
8
8
```

Perhaps you have an older built executable that you're running? You might try removing the old built exe, to make sure you're running a newly built one.

**Comment by bobbrow** [comment]
Is it possible that you're running VS Code from within an x86 Developer Command prompt (or perhaps none at all because you're using the full path to the compiler)?

**Comment by AlanTeixeiraNM** [comment]
@Colengms output you mean what is printed in the integrated terminal?

```
4
8
PS C:\Users\alant\Codeprojects\test>
```
Hi @bobbrow, I run VS Code from  Visual Studio 2022 Developer Command Prompt v17.8.3. I also use VS 2022. Recently I was building some C++ project in VS 2022 targeting x86, could this interfere somehow in VS Code?

I notice that at the end of Log Diagnostics (provided at the begining of the open issue), in Other Flags, the first three directories are x86 architecture. Could it be a problem?

**Comment by Colengms** [comment]
Hi @AlanTeixeiraNM .  When building and running, multiple (integrated) terminals are opened. The one with the build output should be titled, "C/C++: cl.exe build active file".  That output should indicate the command line used to build the executable.

I just tried this out. It looks like the built-in task generation for 'build and debug' only works on Windows when launching VS Code from a VS Command Prompt and doesn't seem to allow replacing `cl.exe` there with a full path. It looks like you'll need to launch VS Code from an x64 VS Command Prompt. That should also correct the `--using_directory` arguments you're seeing in your IntelliSense configuration.

**Comment by AlanTeixeiraNM** [comment]
Problem solved. I just found a VS developer command prompt for x64 environment and launched VS Code from there. Thanks @Colengms and @bobbrow.
