### ISSUE TITLE
Tag Parser Fails when using "extended" characters 

### ISSUE THREAD

**Issue by UR3IQO** [microsoft/vscode-cpptools#1189]
VSCode v1.17.2
cpptools v0.14.0
Windows 8

Tag Parser fails if "extended" characters are used. For example the following code with Cyrillic 'A' in windows 1251 encoding will result in Tag Parser Fail:
```
int  F(char ch)
{
   return ch - 'А';
}
``` 
Two files are attached - one in win1251 and one in utf-8.
[1.zip](https://github.com/Microsoft/vscode-cpptools/files/1429804/1.zip)

Changing encoding to UTF-8 solves the problem. If the logging is off the parser/intellisense just dies silently showing no errors but completely ignoring the contents of the file.

This problem appeared in the last releases (as far as I remember June/July cpptools releases worked with win1251 encoding without problems). 

It should not be a big problem for me to change encoding to utf-8, but I think such a behavior should be documented or the problem should be corrected.

**Comment by sean-mcmanus** [comment]
We only officially support utf-8 at the moment (https://github.com/Microsoft/vscode-cpptools/issues/414 ). Additional encoding would require porting additional conversion code, but it's possible this particular issue might be fixable if it's a regression, since some of the utf-8 special handling code got changed around 0.13.1, so we'll try to take a look...

**Comment by UR3IQO** [comment]
@sean-mcmanus I moved to UTF-8, so it is not a problem anymore for me. 
But it would be nice to provide some diagnostic messages when Tag Parser fails so the problems like this one could be easily found. I spent almost an hour to determine what caused the problem (it was a large file with only several extended characters).

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
