### ISSUE TITLE
C/Cpp Language Server server crashed, when I click the "Go to Declaration"

### ISSUE THREAD

**Issue by orsmile** [microsoft/vscode-cpptools#119]
When I click the Go to Declaration , I can't get no any response and vscode just show
"The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."

I use windows 7 and source file in the remote server. 
I use [https://github.com/Foreveryone-cz/win-sshfs](win-sshfs) to connect my remote server.

Please solved this issue thanks.

**Comment by songwenshuai** [comment]
Hello, I also appeared in this error, how should I do?

**Comment by jgoshi** [comment]
Can you try this again with the next release (VSCode 1.4, cpptools 0.9.0)? If this still repros for you please reopen this bug.

**Comment by evser** [comment]
@jgoshi, where can I find version 0.9.0??
I see only 0.81 here: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

**Comment by songwenshuai** [comment]
After the update, the problem does not appear
