### ISSUE TITLE
Include path doesn't include the custom paths inserted

### ISSUE THREAD

**Issue by sskieller** [microsoft/vscode-cpptools#1190]
Since I updated to the newest version of Visual Code I have had problems with intellisense and include-paths. I have tried for several hours now to get intellisense to use the paths I've written into includepath and browsepath with no luck.

This is the errors I am getting. 
![errors](https://user-images.githubusercontent.com/11709063/32216488-6ca17e60-be25-11e7-95d3-54abcfbe6bfa.png)

My _c_cpp_properties.json_ file looks like this:

![propertiesjson](https://user-images.githubusercontent.com/11709063/32217083-359da630-be27-11e7-8169-63d2e505ba49.png)

and the code for the file is below. (Couldn't get it to format correct, sorry!)

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceRoot}",
                "/home/stud/sources/rpi-4.9/include/linux",
                "/home/stud/sources/rpi-4.9/include",
                "/usr/include/x86_64-linux-gnu/c++/6.3.0",
                "/usr/include/c++/6.3.0",
                "/usr/local/include",
                "/usr/lib/clang/4.0.0/include",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include/linux"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "/home/stud/sources/rpi-4.9/include/linux",
                    "/home/stud/sources/rpi-4.9/include",
                    "/usr/include/x86_64-linux-gnu/c++/6.3.0",
                    "/usr/include/c++/6.3.0",
                    "/usr/local/include",
                    "/usr/lib/clang/4.0.0/include",
                    "/usr/include/x86_64-linux-gnu",
                    "/usr/include/linux"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
    ],
    "version": 3
}
```

The point is to get intellisense to reach into the files on the rpi-4.9 but it never even updates the path. 
When using the command `clang -Wp,-v -E -xc -x c++ /dev/null` the following picture is seen:

![console-command](https://user-images.githubusercontent.com/11709063/32216896-99136d72-be26-11e7-8d61-85c18147be84.png)

The settings for intellisense is the following:

![intellisense settings](https://user-images.githubusercontent.com/11709063/32216969-d1450138-be26-11e7-93fc-0e4d2a7c1cfe.png)

I have tried rebooting the system several times also to no avail. As shown from the clang console command, the include paths that I write into the properties file never even make it to the paths.

**Comment by bobbrow** [comment]
Can you try reordering your include path to match the output from clang (keep your rpi stuff at the top of the list)?  If any of those missing dependencies is coming from an #include_next directive, the compiler may not be able to find them when the include path is out of order...

**Comment by sskieller** [comment]
I have reordered the include path to match the default setup which vs code creates the file like, while adding the two custom paths. I still have the same error.

![sorted properties](https://user-images.githubusercontent.com/11709063/32244619-61b4565e-be79-11e7-82d5-0f8e72f26cc0.png)

**Comment by bobbrow** [comment]
Actually, this is what I meant (and you're pointing to the wrong folder for clang includes):

```
"includePath": [
  "/home/stud/sources/rpi-4.9/include/linux",
  "/home/stud/sources/rpi-4.9/include",
  "/usr/include/c++/6.3.0",
  "/usr/include/x86_64-linux-gnu/c++/6.3.0",
  "/usr/include/c++/6.3.0/backward",
  "/usr/include/clang/4.0.0/include",
  "/usr/local/include",
  "/usr/include/x86_64-linux-gnu",
  "/usr/include"
],
```

Though if this is C code, you might want to remove the c++ paths.  (re-run your clang command without `-x c++`)

**Comment by sskieller** [comment]
This is C++ code. I rearranged the path according to your suggestions and there is still no change. I still recieve the errors from above.

**Comment by bobbrow** [comment]
Hmm, ok.  Your original screenshot showed files with a `.c` extension.

So where do those missing header files reside in your filesystem?  I searched for them on my Ubuntu box, but didn't find them.  Looking at the Rapsberry Pi GitHub repo online, it looks like these files live in the "asm-generic" folder under "include".  Is there some setup step you are missing that is supposed to copy them from "asm-generic" to "asm"?

**Comment by LizardLad** [comment]
Hi all I've got a simmilar problem again on linux.

I'm trying to include the glm library and the standard way of including it is "#include <glm/glm.hpp>"
however vscode says
![screenshot_2019-01-04_15-51-35](https://user-images.githubusercontent.com/19244685/50675405-c07b5800-1039-11e9-9ce5-2024c7c4d8cc.png)

These are my include paths
`{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include/SDL2/",
                "/usr/include/",
                "/usr/local/include/",
                "${workspaceFolder}/"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 4
}`
Since glm is a directory under /usr/include then shouldn't it pick it up from the /usr/include line?
Sorry about the formatting

**Comment by obiwanus** [comment]
Looks like the `includePath` in `c_cpp_properties.json` is only used for `include ""` lookups, not for system header includes.

**Comment by LizardLad** [comment]
It affects system header includes because SDL wasn't being found before however now I have that in my path it can be found successfully.

**Comment by obiwanus** [comment]
I have the same problem. But when I add a path to `includePath`, it can find the header files when they are included with `include "..."`, but not with `include <...>`. 

Hope it's not a bug.

**Comment by sean-mcmanus** [comment]
@obiwanus `#include ""` will add the directory of the current file to the include path.

If you [enable Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) you can see what the actual "includes" are that we end up using.

**Comment by LizardLad** [comment]
Is there a problem where it just cannot search recursively in /usr/include/? Since that's where most stuff will be on linux.

Just a suggestion it would also be nice if once this is fixed the editor can add this as default so linux users don't have to go through this everytime. It will help retain users, otherwise linux users would likely go to some other IDE.

**Comment by sean-mcmanus** [comment]
@OllieLollie1 System includes should obtained via the compiler, but you can use `"**"` at the end of an includePath to make it recursive. Using /usr/include/** is potentially problematic if system headers with the same name exist under that path in different folders, because if the wrong folder gets chosen it could break the include resolution.

**Comment by journeytosilius** [comment]
I am having the same problem with the latest version of vscode. I update my include paths like this : 

```
${workspaceFolder}
${workspaceFolder}/lib/json/single_include/nlohmann
${workspaceFolder}/lib/influxdb-cpp
```
But it won't find it when I run the build task ... 

```
/home/xavier/autoplot++/src/main.cpp:2:10: fatal error: influxdb.hpp: No such file or directory
 #include <influxdb.hpp>
          ^~~~~~~~~~~~~~
compilation terminated.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

**Comment by journeytosilius** [comment]
I believe the problem is that  `"${workspaceFolder}"` is not really the workspace directory, but the root of the user directory in the system. When I #include with absolute paths aka `/home/user/workspacefolder/lib/include/header.hpp` it does work. Which is weird as the extension assumes that the home directory is `${workspaceFolder}` and not the project directory.

**Comment by journeytosilius** [comment]
Ok, after setting up a workspace and pointing $"${workspaceFolder}" to the include paths, still doesn't work. So I don't really know what's going on here.

**Comment by sean-mcmanus** [comment]
@chromafunk The includePath setting of our C/C++ extension doesn't apply to build tasks. You need to add the "-I" args (or whatever) to your build task args list.

**Comment by githibsaeid** [comment]
some guy solved this problem with this solution
https://www.gamedev.net/forums/topic/695078-include-sdl2-using-visual-studio-code-help/5370564/

**Comment by Colengms** [comment]
There hasn't been activity regarding the original issue for quite a while.  Additional issues appear to have been related to compilation.  If there is still an issue here, let us know, and we can re-open.
