### ISSUE TITLE
Config UI shows incorrect error message that `compilerPath` is not found, despite picked up correctly from PATH

### ISSUE THREAD

**Issue by geissdoerfer** [microsoft/vscode-cpptools#11903]
### Environment

- OS and Version: Arch Linux x64 6.6.10-1-lts
- VS Code Version: 1.85.2
- C/C++ Extension Version: v1.18.5

### Bug Summary and Steps to Reproduce

Bug Summary:

I have a project opened in vscode in the directory /home/myuser/myworkspace.  arm-none-eabi-gcc is on my PATH:

```shell
myuser@mymachine ~> arm-none-eabi-gcc --version
arm-none-eabi-gcc (Arch Repository) 13.2.0
```

When specifying `"compilerPath": "arm-none-eabi-gcc"` in `c_cpp_properties.json`, the following problem is reported: _Cannot find "/home/myuser/myworkspace/arm-none-eabi-gcc"_.

Expected behavior:

Since compilerPath is specified as a relative path, I would expect that it is found on my PATH. This seems to be the intended behavior implemented with 5ca9f34769bb19263bb94a3fd6c107630e503d2c.

### Configuration and Logs

```shell
`c_cpp_properties.json`:


{
    "configurations": [
        {
            "name": "${config:operSys}",
            "includePath": [
                "${config:rioteeSdkRoot}/core/include",
            ],
            "defines": [
                "mcpu=cortex-m4",
            ],
            "compilerPath": "arm-none-eabi-gcc",
            "intelliSenseMode": "gcc-arm",
            "cStandard": "c17",
            "cppStandard": "c++14"
        }
    ],
    "version": 4
}
``
```

**Comment by Colengms** [comment]
Hi @geissdoerfer . I believe the error message you are seeing is incorrect and a bug in our path validation in the Config UI. However, using a relative path should actually function correctly.

Using a simple example, using `g++` and `clang-16`, which are installed on my Linux system and accessibly via the PATH, it successfully locates `g++` and `clang-16`, without any path specified, and configures the file correctly.

We can use this issue to track correcting the invalid error message in the Config UI.

**Comment by sean-mcmanus** [comment]
@geissdoerfer Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.3
