### ISSUE TITLE
Intellisense go to definition is not still not working 

### ISSUE THREAD

**Issue by billgan1024** [microsoft/vscode-cpptools#11917]
no, still not working.

https://github.com/microsoft/vscode-cpptools/assets/17630457/76135302-b218-43f2-825b-36619a78f71e

_Originally posted by @billgan1024 in https://github.com/microsoft/vscode-cpptools/issues/11446#issuecomment-1924940564_

**Comment by bobbrow** [comment]
Closing in favor of keeping the original issue.
