### ISSUE TITLE
Intellisense gives errors and other hints with both includePath and compile_commands.json

### ISSUE THREAD

**Issue by slim71** [microsoft/vscode-cpptools#11922]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/11901

<div type='discussions-op-text'>

<sup>Originally posted by **slim71** January 27, 2024</sup>
Hi all,
I don't know whether this is a bug or rather something I'm doing/understanding wrong, so here goes.
\
I have a ROS2 project I'm developing mainly in C++, using VSCode and the C/C++ extension. Here's a [link to the complete project](https://github.com/slim71/SpartanLIFT), if needed, but I'll post the important details here.
\
I have the following `c_cpp_properties.json` file
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/src/pelican/**",
                "${workspaceFolder}/src/datapad/**",
                "${workspaceFolder}/src/Micro-XRCE-DDS-Agent/include/uxr/agent/**",
                "/opt/ros/humble/include/**",
                "${workspaceFolder}/install/comms/include/**",
                "${workspaceFolder}/install/px4_msgs/include/px4_msgs/**",
                "${workspaceFolder}/install/px4_ros_com/include/px4_ros_com/**",
                "/home/slim71/Documents/git/pugixml",
                "/usr/include/**",
                "/usr/include/",
                "/usr/local/include/**",
                "/usr/local/include/"
            ],
            "defines": [],
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "${default}",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4,
    "enableConfigurationSquiggles": true
}
```
and this `settings.json` file
```json5
{
  "C_Cpp.clang_format_path": "/usr/bin/clang-format-17",
  "C_Cpp.clang_format_style": "file:${workspaceFolder}/.vscode/.clang-format",
  "C_Cpp.default.cStandard": "c17",
  "C_Cpp.default.cppStandard": "c++17",
  "C_Cpp.default.intelliSenseMode": "linux-gcc-x64",
  "C_Cpp.formatting": "clangFormat",
  "C_Cpp.intelliSenseEngine": "default",
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "editor.tabSize": 4
  },
  "autopep8.args": [
    "\"--max-line-length=100\""
  ],
  "clang-format.executable": "/usr/bin/clang-format-17",
  "editor.foldingStrategy": "indentation",
  "python.analysis.extraPaths": [
    "/opt/ros/humble/lib/python3.10/site-packages",
    "/opt/ros/humble/local/lib/python3.10/dist-packages"
  ],
  "python.analysis.typeCheckingMode": "basic",
  "python.autoComplete.extraPaths": [
    "/opt/ros/humble/lib/python3.10/site-packages",
    "/opt/ros/humble/local/lib/python3.10/dist-packages"
  ],
  "python.envFile": "${workspaceFolder}/.env",
  "ros.distro": "humble",
  "ros.isolateEnvironment": false,
  "ros.rosSetupScript": "${workspaceFolder}/install/setup.bash",
  "search.exclude": {
    "**/*.code-search": true,
    "**/bower_components": true,
    "**/build": true,
    "**/install": true,
    "**/log": true,
    "**/node_modules": true
  },
  "uncrustify.configPath.linux": "/opt/ros/humble/lib/python3.10/site-packages/ament_uncrustify/configuration/ament_code_style.cfg",
  "editor.foldingImportsByDefault": true,
  "clang-format.fallbackStyle": "",
  "C_Cpp.default.compilerPath": "/usr/bin/gcc",
  "files.associations": 
    # deleted to make this shorter
  },
  "todo-tree.general.debug": true,
  "todo-tree.tree.scanMode": "workspace only",
  "todo-tree.general.tags": [
    # deleted to make this shorter
  ]
}

```
\
As you can see, I'm using a `compile_commands.json` file (generated by colcon) though I'm still new to this, and I've also set the `includePath` value with all folders in which I have possible used includes.
Right now most of the code seems to be recognized, but I still have some red squiggles saying "cannot open source file math.h"
![image](https://github.com/microsoft/vscode-cpptools/assets/39267642/74ead01f-a06c-48a0-903e-51ccb914368f)
![image](https://github.com/microsoft/vscode-cpptools/assets/39267642/4019c337-865d-4e5c-a465-8ccc4e2b70f4)
and the functions definitions seem not to be found.
I've tried adding the `compilerPath` setting, linking to `/usr/bin/gcc`, but strangely enough that seems to make things worse: the scan job seems to be spinning forever and it won't complete. I guess there's too much to scan?
\
**EDIT**: after **a long** time, it finished scanning but things are not looking good: now the issue for `math.h` is fine, it seems, but it says functions definitions are not found. I have found [this issue](https://github.com/microsoft/vscode-cpptools/issues/11889) which might be related to this though, so I think using `compilerPath` is a no-go for now...
\
So now I'm trying to understand how I can get rid of the error for math.h (which of course is present in `/usr/include/`) to get everything nice and clear.
Any suggestions? 😄 

**EDIT2**: some details:
VSCode version: 1.85.2 --> updated to 1.86.0
C/C++ extension version: 1.18.5</div>

**Comment by Colengms** [comment]
Hi @slim71 .  I see a number of issues in your logs.

```
------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.
```

This indicates multiple headers with the same name that are all in your specified `includePath`.  This can lead to ambiguouty as to which headers should be correctly matched, and can often lead to incorrect IntelliSense.  I'd highly recommend restricting your `includePath` paths to only the paths that are used.

For complex project, I'd suggest leveraging a build system such as CMake and using CMake Tools to provide configurations to the C/C++ Extension.  Or, a generated `compile_commands.json` should also work well.  These approaches should configure IntelliSense using exactly the same information as is used to compile the file.

In your logs, I do not see any evidence that the source files you have open were found in your `compile_commands.json` file.  I would expect to see a `compile_commands.json entry:` section in your Log Diagnostics output, if it were used.  I do not see that for any of the files indicated there.  Can you confirm that your `compile_commands.json` is where it's expected to be and contains an exact match in a `file` field for one of the files you're expecting to get an IntelliSense configuration for?

I'd also suggest focusing on a single file that repro's the issue, for now, and capturing logs and diagnostics for only that one file, to simplify the log output.

**Comment by slim71** [comment]
> This indicates multiple headers with the same name that are all in your specified `includePath`. This can lead to ambiguouty as to which headers should be correctly matched, and can often lead to incorrect IntelliSense. I'd highly recommend restricting your `includePath` paths to only the paths that are used.

Is this valid even if the files with the same name are located in different folders/paths?
But anyway, the `compile_commands.json` file is located in the `build/` folder of my workspace, so I would expect for it to work for my case.
Inspecting it more thoroughly, it does seem not to list all of the files in the workspace subfolders though, so I guess this should be the first thing to analyze for me... 

> For complex project, I'd suggest leveraging a build system such as CMake and using CMake Tools to provide configurations to the C/C++ Extension. Or, a generated `compile_commands.json` should also work well. These approaches should configure IntelliSense using exactly the same information as is used to compile the file.

Well, I do have that, since I'm working on a ROS2 project, but maybe I have to research why not everything is listed then.

**Comment by slim71** [comment]
I've finally solved this. It was indeed not due to Intellisense, but to how I was building my ROS2 workspace.
Using the right command produced the complete `compile_commands.json`, which is then correctly parsed from Intellisense: I don't see any squiggles now.
Thanks @Colengms for your answers!
