### ISSUE TITLE
Unable to include header folder (Ubuntu 21,04)

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/vscode-cpptools#11924]
### Environment

- OS and Version: ~22.04.1-Ubuntu
- VS Code Version:  1.85.2
- C/C++ Extension Version: 1.18.5

### Bug Summary and Steps to Reproduce

Bug Summary:
Unable to include header files

Steps to reproduce:
folder structure // Adjust the version number accordingly
```bash
├── Header_Files
│   └── header_1.h
└── Source_Files
    ├── yekshemesh_world
    └── yekshemesh_world.cpp
```
```c++
#include <iostream>
#include <math.h>
#include "header_1.h"
int main()
{
    std::cout << "yekshemesh World" << std::endl;
}
```
settings
```json
"C_Cpp.default.includePath": [
        "${workspaceFolder} ",
        "${workspaceFolder}/**",
        "${workspaceFolder:Header_Files}",
        "${workspaceFolder:Header_files}",
        "${workspaceFolder:Source_files}",
        "/usr/include/c++/11",
        "/usr/lib/llvm-16/lib/clang/16/include",
        "/usr/include/x86_64-linux-gnu/c++/11",
        "/usr/include/c++/11/backward",
        "/usr/lib/gcc/x86_64-linux-gnu/11/include",
        "/usr/local/include",
        "/usr/lib/gcc/x86_64-linux-gnu/11/include-fixed",
        "/usr/include/x86_64-linux-gnu",
        "/usr/include"
    ],
```
Expected behavior:
it imports the header.
real:

No such file or directory

### Configuration and Logs

```shell
No such file or directory
```

**Comment by browntarik** [comment]
Could you please provide the output from the C/C++: Log Diagnostics command when you open the project? This will help diagnose what you include path is actually picking up.

Additionally, the path "${workspaceFolder} ", is technically incorrect because it has trailing whitespace. This could possibly result in unexpected behavior and should probably be removed.
