### ISSUE TITLE
Intellisense "includePath" non effective, completely useless

### ISSUE THREAD

**Issue by toenails6** [microsoft/vscode-cpptools#11920]
Type: <b>Bug</b>

Using ** wildcard path include does nothing, subdirectory files could not be scanned. 
Manually specifying path undert workspace does nothing, file still could not be scanned. 
Deleting the entire includePath does not affect compile results, if I put the header in the workspace root directory or specify path in the #include line, it works with or without intelliSense includePath setups. 

Similar thing with tasks.json, adding `${workspaceFolder}/**.cpp`, `${workspaceFolder}/**.c` does not link source files to the compiler. 

This highly limits code factoring. 

Extension version: 1.18.5
VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.83GB (18.29GB free)|
|Process Argv|--crash-reporter-id fefd6d48-ca57-478f-9b08-162b02005610|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by browntarik** [comment]
Could you please provide the output from the C/C++: Log Diagnostics command when you open the project? This will help diagnose what you include path is actually picking up.

**Comment by toenails6** [comment]
By open the project I am assuming you mean by trying to compile, below is the output when I try to use wildcard imports and do not manually specify paths. 
I am also assuming you want the terminal log that shows up upon compile failure, which is given below: 

 *  Executing task: C/C++: cl.exe build active file 

Starting build...
cl.exe /Zi /EHsc /nologo /FeD:\YRD\OneDrive\Documents\Engineering\C_C++\JMS6_Protocol\Test.exe D:\YRD\OneDrive\Documents\Engineering\C_C++\JMS6_Protocol\Test.cpp D:\YRD\OneDrive\Documents\Engineering\C_C++\JMS6_Protocol/JMS6_Protocol/JMS6_Protocol.c
Test.cpp
Generating Code...
Compiling...
JMS6_Protocol.c
Generating Code...

Build finished successfully.
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: C/C++: cl.exe build active file 

Starting build...
cl.exe /Zi /EHsc /nologo /FeD:\YRD\OneDrive\Documents\Engineering\C_C++\JMS6_Protocol\Test.exe D:\YRD\OneDrive\Documents\Engineering\C_C++\JMS6_Protocol\Test.cpp D:\YRD\OneDrive\Documents\Engineering\C_C++\JMS6_Protocol/**.c
Test.cpp
D:\YRD\OneDrive\Documents\Engineering\C_C++\JMS6_Protocol\Test.cpp(4): fatal error C1083: Cannot open include file: 'JMS6_Protocol.h': No such file or directory
Generating Code...
Compiling...
**.c
c1: fatal error C1083: Cannot open source file: 'D:\YRD\OneDrive\Documents\Engineering\C_C++\JMS6_Protocol/**.c': No such file or directory
Generating Code...

Build finished with error(s).

 *  The terminal process terminated with exit code: -1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 *

**Comment by Colengms** [comment]
Hi @toenails6 .  I don't believe we have enough information here to understand the issue you're reporting.  The C/C++ Extension is not directly involving in compiling and linking code.  It provides language services such as IntelliSense, Find All References, and code navigation features.  The `includePath` setting in a `c_cpp_properties.json` is used to configure IntelliSense (which essentially requires the same information as a build). 

The `build active file` feature will generate a `tasks.json` file that should be suitable to build a single file.  A `tasks.json` is basically just a wrapper for executing a command line.  Use of asterisks in that command line would depend on the underlying command line allowing them.  If you need to build multiple source files, generally you'll want to use a C/C++ build system, such as `make` or `cmake`.  Though, I suspect you could repurpose `tasks.json` to execute any command-line.

**Comment by toenails6** [comment]
I know what the tasks.json does and I did refit it as should be, as I mentioned at the top most comment: I added wildcard args for the sources files (github is not displaying the two asterisks), and they did nothing useful, only to make things worse as the compiler does not seem to understand it, and tried looking for a file with the asterisks which does not even make sense. If I wanted to compile a single file I would use ${file}, but I should also be allowed to use wildcard directories. 

Look, I can use cmake, and I sometimes have to in order to compile .so files, but the point is that I want to test my functions quickly without typing in the terminal all the time. 
I do hardware as much as I do software and my hands are not as nimble as elite software engineers who spend all of their days on top of keyboards. 

The point of this extension is so that I can test a function just as I would like to factor it, if I need more special things such as .so files, then I can turn to cmake. 

What is not right is, neither the intellisense configuration file, nor the compiler arguments file, functions as intended. I remember seeing this extension announcing that it does support wildcard directories, but obviously it does not. I looked around quite a fair bit, and I am surely not the only one with this issue. This has been around for a long time. 

Most answers for other similar issues is to add wildcard directories to the .jsons, because not everyone knows this, and that is normal. But what is not normal, is adding the necessary statements just as the manuals says, only to find out that this supposedly offically supported feature is actually not working as intended. 

If you really want to confirm that I did add the wildcard statements as I should have before posting this issue, see these snapshots: 
![image](https://github.com/microsoft/vscode-cpptools/assets/43344304/bb68ef8a-32b5-4cc7-9d49-681f9f096ff7)
![image](https://github.com/microsoft/vscode-cpptools/assets/43344304/4364a316-2608-483b-b521-ff77b5307112)
![image](https://github.com/microsoft/vscode-cpptools/assets/43344304/4594ff74-64a7-4627-9395-2736ed671202)

This does not work, but if I explicitly list all the files, I can compile, but again, this limits code factoring, and is not preferred: 
![image](https://github.com/microsoft/vscode-cpptools/assets/43344304/4c6164d4-0984-4999-b5a2-17ddd2215d97)
![image](https://github.com/microsoft/vscode-cpptools/assets/43344304/0cb90908-37da-4105-acef-f0047bf52f5e)
![image](https://github.com/microsoft/vscode-cpptools/assets/43344304/93cd0e22-57c6-48b3-8eaa-d24aba2924b2)
 As you can see, the wildcard include in the intellisense configuration files does nothing, as I have to specify the relative path in the main.cpp file. And I had to list my c source file in the compiler arguments.

**Comment by toenails6** [comment]
If I missed something in the tasks.json, please point out my mistake, and thanks. But this setup does actually work for some other computers, which is the weird thing. That is why I believe this has to be a bug.

**Comment by toenails6** [comment]
I will switch to using g++ instead of MSVC when I have time, this microsoft compiler might be the source of the issue.

**Comment by browntarik** [comment]
Following up from my previous comment, if you open a c++ file you should be able to run the C/C++: Log Diagnostics command, the output from this command will actually let you determine if you wildcard paths are configuring correctly in your includes.

![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/2cc6d862-22f0-44d3-9244-2ab268546432)

This is a great way for us to diagnose what is happening with your includes.

Example:

![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/581aa460-500b-4113-a9ba-b2f13bbd14f3)

**Comment by toenails6** [comment]
-------- Diagnostics - 2/5/2024, 5:57:05 PM
Version: 1.18.5
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "d:/YRD/OneDrive/Documents/Engineering/C_C++/Cyclic_Redundancy_Check/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.22000.0",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPath": "cl.exe",
    "browse": {
        "path": [
            "d:/YRD/OneDrive/Documents/Engineering/C_C++/Cyclic_Redundancy_Check/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.18.3.0
Translation Unit Mappings:
[ D:\YRD\OneDrive\Documents\Engineering\C_C++\Cyclic_Redundancy_Check\Test.cpp ]:
    D:\YRD\OneDrive\Documents\Engineering\C_C++\Cyclic_Redundancy_Check\Test.cpp
Translation Unit Configurations:
[ D:\YRD\OneDrive\Documents\Engineering\C_C++\Cyclic_Redundancy_Check\Test.cpp ]:
    Process ID: 26308
    Memory Usage: 135 MB
    Compiler Path: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe
    Includes:
        C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include
        C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\cppwinrt
        D:\YRD\OneDrive\Documents\Engineering\C_C++\Cyclic_Redundancy_Check\dynamixelCRC
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
    Other Flags:
        --using_directory
        C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\lib\x86
        --using_directory
        C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\lib\x86\store\references
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22000.0
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\References\10.0.22000.0
        --using_directory
        C:\Windows\Microsoft.NET\Framework\v4.0.30319
Total Memory Usage: 135 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5086

I changed to g++ and managed to fix this issue on my other project. This log is from one of my older projects that used MSVC, and it can be seen that intellisense did locate the header via the wildcard import. 

It would seem it was a compiler problem, MSVC must require special arguments in the tasks.json for the search paths, I did not know this. 

I do know how to operate this for g++: 
![image](https://github.com/microsoft/vscode-cpptools/assets/43344304/693e4025-b892-4df3-91be-470e705a67be)
![image](https://github.com/microsoft/vscode-cpptools/assets/43344304/272630af-b96a-443d-880a-ac6f88121f88)

As a bonus, I no longer have to open vscode from the powershell by using g++, either, as I don't need the path to cl.exe in the powershell. 
This can be used for reference for anyone else.

**Comment by browntarik** [comment]
I am glad you were able to resolve your issue, I will now close this unless there are any further concerns. This will still be available for future reference.
