### ISSUE TITLE
Copy only common subset of params with @copydetails

### ISSUE THREAD

**Issue by lukasberbuer** [microsoft/vscode-cpptools#11921]
### Feature Request

It would be great to share the documentation of common parameters. Currently, doxygen shows all params, even if they don't exist on the function. This limits the usage of `@copydetails` to reuse the parameter documentation.
Would it be possible to check the existence of params and only show those in the documentation?

### What I have to do now

```cpp
/**
 * My demo function.
 * @param object Object instance
 * @param value The value to assign to the object
 * @param policy How to assign the value
 */
void func(Object& object, int value, MyEnum policy);

/**
 * My simplified demo function.
 * @param object Object instance
 * @param value The value to assign to the object
 */
void funcSimplified(Object& object, int value);

/**
 * Assign the value to the object.
 * @param value The value to assign to the object
 * @param policy How to assign the value
 */
void Object::func(int value, MyEnum policy)
```

### What I like to do in the future

```cpp
/**
 * My demo function.
 * @param object Object instance
 * @param value The value to assign to the object
 * @param policy How to assign the value
 */
void func(Object& object, int value, MyEnum policy);

/**
 * My simplified demo function.
 * @copydetails func
 */
void funcSimplified(Object& object, int value);

/**
 * Assign the value to the object.
 * @copydetails func
 */
void Object::func(int value, MyEnum policy)
```

**Comment by browntarik** [comment]
Thank you for your Request! Please use this issue to track any progress on the adoption of this enhancement to Doxygen support.

**Comment by lukasberbuer** [comment]
I wanted to create issue for doxygen. I wonder how it ended up here? 🤔
Please delete it if I made an mistake.

**Comment by lukasberbuer** [comment]
Recreated the feature request in the right repository: https://github.com/doxygen/doxygen/issues/10628
