### ISSUE TITLE
c_cpp_properties only contains "null" configuration

### ISSUE THREAD

**Issue by cmazakas** [microsoft/vscode-cpptools#1193]
I recently cloned a project from GitHub and opened up the folder with VS Code and for some reason, this is my c_cpp_properties.json file:
```
{
    "configurations": [
        {
            "name": "null",
            "includePath": [],
            "defines": [],
            "browse": {
                "path": [
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 3
}
```
I'm not sure what information would be relevant for correctly detecting configuration types but I can gather info at request.

Edit: It seems like this is related to CMake and the CMake extensions, namely vector-of-bool's CMake Tools.

**Comment by bobbrow** [comment]
Yes, this is an issue with the CMake tools helper (I believe that code was recently incorporated into vector-of-bool's CMake tools extension).  Feel free to file an issue over in that repository.
