### ISSUE TITLE
Fail in switching header/source when multiple files with same name are present

### ISSUE THREAD

**Issue by StefanoPierini** [microsoft/vscode-cpptools#11938]
Type: <b>Bug</b>

When multiple files with same name present in different directories, for example in different templates, vscode fails to recognize the right source when switching from header. This happens even with system files.

To reproduce:
- create a project with different subprojects and files with same names (even in different namespace)
- go on source and toggle to header

Or, using some system files:
- install mingw64
- create a class named System
- try to switch from source to header
- vscode bring you to "C:\msys64\mingw64\include\curl\system.h"

Actual behavior:
sometimes the opened header not correspond to right source

Expected behavior:
open the header corresponding to the right source

Workaround:
the extension C-mantic give the correct behavior

Extension version: 1.18.5
VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
We're using https://github.com/microsoft/vscode-cpptools/issues/2635 to track issues with file selection in the Header/Source Switch feature.  I'll close this as a duplicate.  I'd suggest up-voting https://github.com/microsoft/vscode-cpptools/issues/2635 .

**Comment by StefanoPierini** [comment]
Ok, thank you very much.
