### ISSUE TITLE
Error opening the file when click on error entry in problems pane

### ISSUE THREAD

**Issue by lijh8** [microsoft/vscode-cpptools#11934]
### Environment

- OS and Version: macOS 12.7.3 (21H1015), 
- VS Code Version: Version: 1.86.0 (Universal)
- C/C++ Extension Version: v1.18.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

Hi,
When I click on the entries on the problems pane, 
it will not open the c++ source file and go to the line with error.
It seems the directory part is losing from the filename, `/main.cpp`.

It reports:
`The editor could not be opened because the file was not found.`

I call make in preLaunchTask in launch.json to build. 
It works in extension CodeLLDB though.

Thanks.

```
$ cat launch.json 
{
  "configurations": [
    {
      "name": "Debug",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${fileDirname}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "lldb",
      "preLaunchTask": "make",
    }
  ],
  "version": "0.2.0",
}
$ 
```

```
$ cat tasks.json 
{
  "tasks": [
    {
      "type": "cppbuild",
      "label": "make",
      "command": "/usr/bin/make",
      "args": [],
      "options": {
        "cwd": "${fileDirname}",
      },
      "problemMatcher": ["$gcc"],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "detail": "Task generated by Debugger.",
    }
  ],
  "version": "2.0.0",
}
$ 
```

![Screen Shot 2024-02-06 at 23 33 16](https://github.com/microsoft/vscode-cpptools/assets/9011764/d6e380c4-da62-411d-8da1-24f6d975276a)
![Screen Shot 2024-02-06 at 23 33 23](https://github.com/microsoft/vscode-cpptools/assets/9011764/57ee30b3-4d73-404a-a81b-1bb11f635be1)

Expected behavior:

### Configuration and Logs

```
-------- Diagnostics - 2/7/2024, 3:23:44 AM
Version: 1.19.2
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "/Users/ljh/Documents/hello_cpp/src/foo"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "intelliSenseMode": "macos-clang-x64",
    "compilerPathInCppPropertiesJson": "/usr/bin/clang",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "/Users/ljh/Documents/hello_cpp/src/foo",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.19.2.0
No active translation units.

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 12293

```

**Comment by browntarik** [comment]
Could you provide the output to the C/C++: Log Diagnostics command when you open the file you are trying to navigate? This will help see what paths are being recognized in the translation units.

**Comment by lijh8** [comment]
> Could you provide the output to the C/C++: Log Diagnostics command when you open the file you are trying to navigate? This will help see what paths are being recognized in the translation units.
> 
> Since we send the filename information to VS Code to use for navigation when there are squiggles, it is possible there is a bug with resolving the file path somewhere within our extension.

Hi, it's included and updated.
Thanks

**Comment by browntarik** [comment]
Given the output of your log diagnostics, it looks like there are no active translation units in your project. This means that IntelliSense is not providing you these error squiggles and thus will not result in the correct navigation. 

![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/d40f5f78-e728-4e87-9c43-c7f2f67c009b)

It looks like you may have the IntelliSense engine disabled, or another extension is interfering with ours.

**Comment by lijh8** [comment]
It seems that values in `args` field is relevant. 
If I use the following new tasks.json and compile a single file, clicking on the error entry in problems pane works.
It can not be wildcard with clang++ as it compiles all files even those unchanged.
It occurs if it's built with Makefile and leave the args empty.

```
// tasks.json:

{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "make",
            "command": "/usr/bin/clang++",
            "args": [
                "-fcolor-diagnostics",
                "-fansi-escape-codes",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            }
        }
    ],
    "version": "2.0.0"
}

```

**Comment by browntarik** [comment]
Could you provide a sample setup/workspace where I can easily reproduce the error? This will allow us to look into a fix.

**Comment by lijh8** [comment]
I just tried it on linux, it does not even show any errors or warnings in the problems pane.
