### ISSUE TITLE
Cannot access 'this' variable in watch window

### ISSUE THREAD

**Issue by KytoDragon** [microsoft/vscode-cpptools#1194]
I am using the cpptools extension primarily to debug D applications where i have the following problem:
When I am stepping through a member function while debugging, the "VARIABLES" window contains a "this" variable (the current object) but typing any expression containing "this" in the "WATCH" window brings the following error message:
`'this' may only be used inside a nonstatic member function`
Is there anything that can be done to make the watch window realize that "this" references a variable and not the implicit C++ object reference?
Using VSCode 1.17.2, CppTools 0.14.0 an Windows

**Comment by pieandcakes** [comment]
Hi @KytoDragon ,

This sounds like an issue with the debugger and not the extension. How would you do this with `gdb` or `lldb` normally?

**Comment by KytoDragon** [comment]
I have only ever debugged using the extension or Visual Studio 2015 and it works fine in VS.

**Comment by pieandcakes** [comment]
@KytoDragon Can you provide a small repro for me and I can see what the problem is. I'm not familiar with D applications at all.

**Comment by KytoDragon** [comment]
You will of course need a D compiler (I use ldc2).
Source `test.d`:
```
class Foo {
    int x = 0;
    void bar() {
        for(int i = 0; i < 10; i++) {
            x++;
        }
    }
}

void main() {
    new Foo().bar();
}
```
Place a breakpoint inside the loop ("breakpoints everywhere" enabled) and compile with `ldc2 -g test.d`.
Configure cpptools with a launch.json and point is to the generated `test.exe` file. Start debugging.
You should see the variables `i` and `this` under `Locals`, unfolding `this` reveals `x` but adding it to the watch, either manually or using the `Add to Watch` context menu will result in the error message.
