### ISSUE TITLE
Auto-complete issue with Conda headers

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#1195]
Copied from #962.
From @dcervenkov

I've a replicable situation of the problem with the "Default" IntelliSense engine. I've just tested it on a brand new Ubuntu 16.04.3 64-bit VM. The procedure is as follows:
1. Install Ubuntu 16.04.3 64-bit
2. Install and setup Conda (a package manager I'll need to easily repro the problem)
```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
```
(I'll assume you installed miniconda to `~/miniconda3/`)

3. `export PATH=$HOME/miniconda3/bin:$PATH`
4. Setup a Conda environment
```
conda config --add channels https://conda.anaconda.org/NLeSC
conda create --name=rootenv root=6 python=3
source activate rootenv
```
5. Install VS Code, add your C/C++ Extension and activate the "Default" IntelliSense engine
6. Make a dir to host the project, I'll assume `$HOME/test`
6. Put the following to `.vscode/c_cpp_properties.json`
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "~/miniconda3/envs/rootenv/include",
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "~/miniconda3/envs/rootenv/include",
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
        }
    ],
    "version": 3
}
```

7. Add the following content to `test.cc`
```c++
#include "RooRealVar.h"
void main() {
    RooRealVar foo;
    foo.SetMinimum();
}
```
8. Run VS Code from the terminal where you ran `source activate rootenv` by executing `code .`
9. Open `test.cc` and try auto-completing any method from `foo`, for example `SetMinimum()`
10. Check that it works with "Tag Parser"

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
