### ISSUE TITLE
C/C++ highlighting cannot be displayed in the mounted folder on Linux

### ISSUE THREAD

**Issue by FlashMan2008** [microsoft/vscode-cpptools#11958]
### Environment

- OS and Version: Ubuntu 20.04
- VS Code Version: 1.86.1 (system setup)
- C/C++ Extension Version: v1.18.5

### Bug Summary and Steps to Reproduce

Bug Summary: C/C++ highlighting cannot be displayed in the mounted folder on Linux.

Steps to reproduce:
1. Create a folder with a normal .cpp file;
2. When opening the folder with VSCode, the code highlighting can be displayed properly;
3. Use the terminal command `ln -s *** ***` to create a symbolic link for this folder;
4. When opening the mounted folder with VSCode, it is observed that extensions cannot function properly.

Expected behavior: Code highlighting and code analysis are both unable to be displayed.

### Configuration and Logs

```shell
-------- Diagnostics - 2/13/2024, 2:30:31 PM
Version: 1.18.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/flashman/contest/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerPathInCppPropertiesJson": "/usr/bin/gcc",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "/home/flashman/contest/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.18.3.0
Translation Unit Mappings:
[ /mnt/d/noip/train.cpp ]:
    /mnt/d/noip/train.cpp
Translation Unit Configurations:
[ /mnt/d/noip/train.cpp ]:
    Process ID: 215124
    Memory Usage: 44 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/x86_64-linux-gnu/c++/11
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-linux-gnu/11/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110400
Total Memory Usage: 44 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2482
```

**Comment by FlashMan2008** [comment]
For the OS part, Ubuntu 22.04 also experiences the same issue.

**Comment by Colengms** [comment]
This is a known issue related to symlinks.  We're tracking this with https://github.com/microsoft/vscode-cpptools/issues/4573 .  I'd suggest up-voting that issue.  Closing this issue as a duplicate.
