### ISSUE TITLE
Rename symbol simply does a dumb string search and replace

### ISSUE THREAD

**Issue by clauderobi** [microsoft/vscode-cpptools#11952]
### Environment

Ubuntu 23.10
VS code: 1.86.1
C/C++ Extension: 1.18.5

### Bug Summary and Steps to Reproduce

Bug Summary:

Hitting F2 to rename a class name (or a variable) result in vscode doing a dumb string search and replace. 

Steps to reproduce:
1. Place cursor over a class name
2. Press F2
3. Enter a new class name value
4. Wait for the search to complete
5. In the Refactor Preview, notice that ALL matching strings, regardless if they are a class symbol instance are selected to be replaced

Expected behavior:

Only where the class name symbol is used should be changed

### Configuration and Logs

```shell
Configuration

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "cStandard": "c17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}

-------- Diagnostics - 2/11/2024, 3:31:59 PM
Version: 1.18.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/mnt/data/sbox/NearEDGE/latchyPro/**"
    ],
    "defines": [],
    "cStandard": "c17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPath": "/usr/bin/gcc",
    "browse": {
        "path": [
            "/mnt/data/sbox/NearEDGE/latchyPro/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.18.3.0
Translation Unit Mappings:
[ /mnt/data/sbox/NearEDGE/latchyPro/latchy/src/assets/assets.cpp ]:
    /mnt/data/sbox/NearEDGE/latchyPro/latchy/src/assets/assets.cpp
Translation Unit Configurations:
[ /mnt/data/sbox/NearEDGE/latchyPro/latchy/src/assets/assets.cpp ]:
    Process ID: 841798
    Memory Usage: 247 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/13
        /usr/include/x86_64-linux-gnu/c++/13
        /usr/include/c++/13/backward
        /usr/lib/gcc/x86_64-linux-gnu/13/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
        /mnt/data/sbox/NearEDGE/latchyPro/latchy/src
        /mnt/data/sbox/NearEDGE/latchyPro/build/latchy/models
        /mnt/data/sbox/NearEDGE/latchyPro/vcpkg/packages/protobuf_x64-linux/include
        /mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/protobuf/src/v3.18.0-296107ec8b.clean/src
        /mnt/data/sbox/NearEDGE/latchyPro/vcpkg/ports/libmspack
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=130200
Total Memory Usage: 247 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 38599

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: /usr/include/assert.h
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/packages/botan_x64-linux/include/botan"
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/botan/x64-linux-rel/build/include/botan"
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/botan/x64-linux-dbg/build/include/botan"
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/botan/src/74631e6ae3-97e092b8e0.clean/src/lib/utils"
Using: /mnt/data/sbox/NearEDGE/latchyPro/vcpkg/ports/libmspack/config.h
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/ports/ragel"
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/ports/libaiff"
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/ports/cityhash"
Using: /mnt/data/sbox/NearEDGE/latchyPro/vcpkg/packages/protobuf_x64-linux/include/google/protobuf/any.h
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/protobuf/src/v3.18.0-296107ec8b.clean/src"
Using: /mnt/data/sbox/NearEDGE/latchyPro/vcpkg/packages/protobuf_x64-linux/include/google/protobuf/arena.h
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/protobuf/src/v3.18.0-296107ec8b.clean/php/ext"
Using: /mnt/data/sbox/NearEDGE/latchyPro/vcpkg/packages/protobuf_x64-linux/include/google/protobuf/extension_set.h
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/build/vcpkg_installed/x64-linux/include"
Using: /usr/include/semaphore.h
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/botan/x64-linux-rel/build/include/botan/internal"
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/botan/x64-linux-dbg/build/include/botan/internal"
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/botan/src/74631e6ae3-97e092b8e0.clean/src/lib/utils/thread_utils"
Using: /usr/include/time.h
    Alternative: "/mnt/data/sbox/NearEDGE/latchyPro/vcpkg/buildtrees/protobuf/src/v3.18.0-296107ec8b.clean/src/google/protobuf/stubs"

```
```


### Other Extensions

_No response_

### Additional context

_No response_

**Comment by sean-mcmanus** [comment]
I'm not able to repro that and it's not the normal behavior. Can you provide more repro details as to when the incorrect behavior starts to happen? Does the bug repro for you with this simple workspace example? With C_Cpp.loggingLevel set to "Debug" do you see any errors in the "C/C++" output?

<img width="373" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/882adee4-23fd-4ab0-926f-55804080a5e6">

**Comment by clauderobi** [comment]
Good question. 

I am new to vscode and I am simply opening "folders". You mentioned "workspace " so I went that route. Initially, with just 1 .h and 1 .cpp of course renaming using F2 worked. But there is no other files anyway. So,

1 - my project is using vcpkg and cmake so I copied the necessary files, converted by new project to git and added vcpkg as a sub module. Now, there is a lots of files in the filesystem but still renaming worked. But I am not seeing in the GUI the manually added files nor the file vcpkg produced so I guess it is normal that renaming works properly; vscode is not aware of the extra files.

2 - I close the workspace and reopen vscode using the open folder method. Now, all the files are there and renaming does not work as expected.

I am not sure about the logs. I did set to debug but C/C++ Log Diagnostics did not show anything new after invoking F2. Is it the correct log to look for?

Here is a screen shot, you can see that event comments were updated (well not since I hit discard....). 

I made sure to use a name, **code**, that is likely to be found somewhere else. (code() is just a dummy for the purpose of testing here)

Observations, for what it is worth:
- I am  inside a namespace.
- I had a mistake when I added code where I only had 1 colon between the class and method name. Hitting F12 would render tons of hits but none in the include file where the class is defined. 

![image](https://github.com/microsoft/vscode-cpptools/assets/5255742/b089f7eb-e931-40f1-be86-16b59594b239)

**Comment by bobbrow** [comment]
The icon for the matches indicates that they are within a comment block and the checkboxes are not selected by default so they will not be replaced without your consent.

This is actually expected behavior because developers often want to update references to type names in comments as part of the rename and we try to help with that.  Since we know that not all matches will be correct we do not enable the checkbox by default for those matches and those changes will not be applied unless you activate the checkbox.

I can understand that you might not want us to look in the vcpkg folder since those are libraries and not necessarily your code.  @sean-mcmanus does the `C_Cpp.files.exclude` setting apply to rename? If so, you could put that `vcpkg_installed` folder in the list and we'd skip it when looking for symbols to rename.  If it doesn't, we should consider supporting that.

> I had a mistake when I added code where I only had 1 colon between the class and method name. Hitting F12 would render tons of hits but none in the include file where the class is defined.

I believe this may also be expected behavior since we would not have been able to properly identify the symbol you wanted to rename.

**Comment by clauderobi** [comment]
Ok makes sense.

I few comments:
- The Refactor preview should focus on the "real" confirmed reference. Ideally by sorting them at the beginning
- The folding should be consistent; ATM a number of items at the top of the list are expended and the rest if folded. It so happens that the ones at the top are irrelevant

I would also add the build directory to the normal exclusion list.

**Comment by clauderobi** [comment]
Oh and another comment.

Some of the wrongly listed hit (although disabled) are "CANNOT CONFIRM REFERENCE". In at least 1 case, I noticed that the reference was effectively invalid since in a different namespace. I am not sure why they should be listed.

**Comment by bobbrow** [comment]
The CANNOT CONFIRM REFERENCE cases are when we're unable to get the language server to work on a file that has the possibility of matching the symbol being renamed.  Similar to the string matches in comments, we'll show these as a "just in case" but leave them unchecked. We try to strike a balance between not doing something that will break your build in either direction (missing a reference vs. returning false positives) so we submit it to the developer for confirmation.

**Comment by sean-mcmanus** [comment]
This sounds like a VS Code rename UI issue -- I filed https://github.com/microsoft/vscode/issues/94210 but it didn't get enough votes.

The Find All References UI is better in that it shows the Confirmed references at the top.

**Comment by bobbrow** [comment]
Yikes, I just clicked through the discussion and VS Code did the exact opposite of what we had originally asked. The closed issue was marked "help wanted" which means maybe they'll accept a PR?

**Comment by sean-mcmanus** [comment]
@bobbrow The user can add the build or vcpkg_installed folder to C_Cpp.files.exclude. Normally, I don't think that folder is supposed to be under the workspace folder, so it would be automatically excluded from rename (were it outside the workspace folder).

**Comment by bobbrow** [comment]
> Normally, I don't think that folder is supposed to be under the workspace folder, so it would be automatically excluded from rename (were it outside the workspace folder).

If they are using CMake Tools, the build folder is in ${workspaceFolder} by default.  I don't think we have any data that confirms this assertion.  But good to know about `C_Cpp.files.exclude`.  @clauderobi, you should give it a try.

**Comment by clauderobi** [comment]
Just tested with "build": true, and it indeed works

Major boost in performance!!!

**Comment by clauderobi** [comment]
Humm but under File/Open there is Open Folder and Open Workspace from file what is the difference? Obviously _from file_ mean there is a Workspace definition file so this is not what I am asking; are there functional differences between the 2 type of opens?

**Comment by bobbrow** [comment]
If you are asking about a difference when working with a single folder, I'd say that there is no practical difference besides the existence of the `.code-workspace` file.

**Comment by clauderobi** [comment]
Ok good to know.
