### ISSUE TITLE
The "You do not have IntelliSense configured" prompt no longer appears

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#11960]
It used to appear when a user selects the “Do not configure with a compiler (not recommended) option and maybe some other cases.

It looks like it was incorrectly moved in PR https://github.com/microsoft/vscode-cpptools/pull/11427 .

I didn't find this bug -- it was reported by another "internal team".

**Comment by Colengms** [comment]
This should be addressed in 1.19.4.
