### ISSUE TITLE
clang-format run failed

### ISSUE THREAD

**Issue by viordash** [microsoft/vscode-cpptools#11967]
### Environment

Version: 1.86.1
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:07:19.849Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 5.15.0-88-generic

### Bug Summary and Steps to Reproduce

Bug Summary:
Formatting failed:
/home/viordash/.vscode/extensions/ms-vscode.cpptools-1.18.5-linux-x64/bin/../LLVM/bin/clang-format -style=file -fallback-style=LLVM --Wno-error=unknown -assume-filename=/home/viordash/projects/tszI/tests/unit_tests/tests/swd/wchar_stdio_tests.c

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
-
```

### Additional context

v1.17.4 works successfully

**Comment by Colengms** [comment]
Hi @viordash . Could you try out the most recent pre-release version of the extension (1.19.3) ?  We're not currently tracking any general issues with clang-format, which would impact a large number of users.  There would seem to be something about your environment or configuration that we'd need to uncover to understand what's happening. For instance, what distro of Linux are you using? Does the issue occur with a particular file or project, or does it happen even with a simple project and no related settings (or .clang-format file)? If you run the command line that was logged, does it run when invoked directly?

**Comment by viordash** [comment]
version 1.19.3 showed more advanced error details, and this error was in my .clang-format file:
`/home/projects/.clang-format:19:1: error: duplicated mapping key 'SpacesInContainerLiterals'`
probably the old versions skipped this error.
Thank you
