### ISSUE TITLE
Depricated

### ISSUE THREAD

**Issue by Tanmay011101** [microsoft/vscode-cpptools#11985]
### Environment

- OS and Version: 
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
"C_Cpp.updateChannel": "Insiders",           // This is depricated on 2022 , fix it ASAP.
```

```[tasklist]
### Tasks
```

**Comment by sean-mcmanus** [comment]
@Tanmay011101 There is no more "update channel". You can access the Insiders/pre-release build via the Extensions window and clicking the config icon and choosing Switch to Pre-release.
<img width="191" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/a9e373fa-0897-4bfa-b6a0-d97d3a314c3a">

**Comment by bobbrow** [comment]
@sean-mcmanus I think the issue is that we need to remove the setting.  It's still in package.json
