### ISSUE TITLE
Navigation Menu Not Functional

### ISSUE THREAD

**Issue by jane-29** [microsoft/vscode-cpptools#11981]
### Environment

- OS and Version: Windows 10 Home, Version 21H1
- VS Code Version: 1.64.2
- C/C++ Extension Version: 1.5.1
- If using SSH remote, specify OS of remote machine: Ubuntu 20.04.3 LTS

### Bug Summary and Steps to Reproduce

Bug Summary:
Navigation Menu Not Functional

Steps to reproduce:
1. Go to the website homepage.
2. Attempt to hover over or click on any of the items in the navigation menu.
3. Scroll down to view more menu items.
4. Observe that the dropdown menu does not appear, or clicking on menu items does not navigate to the corresponding pages.

Expected behavior:
The navigation menu should function correctly, displaying dropdown menus upon hover or click, and navigating to the appropriate pages when clicked.

### Configuration and Logs

```shell
Configuration and Logs

Configurations in c_cpp_properties.json:

{
  "configurations": [
    {
      "name": "Win32",
      "includePath": [
        "${workspaceFolder}/**",
        "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/include"
      ],
      "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
      ],
      "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
      "cStandard": "c17",
      "cppStandard": "c++17",
      "intelliSenseMode": "msvc-x64"
    }
  ],
  "version": 4
}


Logs from running C/C++:
- Log Diagnostics from the VS Code command palette:

```
[2024-02-19 15:30:00.123] [info] Language server started.
[2024-02-19 15:30:01.234] [warning] Failed to include header file: 'stdio.h'
[2024-02-19 15:30:02.345] [error] Compilation failed with exit code 1.
```

Logs from the language server logging:
```
[2024-02-19 15:30:05.678] [info] Language server initialized.
[2024-02-19 15:30:06.789] [debug] Analyzing code...
[2024-02-19 15:30:07.890] [debug] Code analysis completed.
```

---

In this example:

- Configurations in c_cpp_properties.json**: This is a sample configuration file for a C/C++ project in Visual Studio. It specifies include paths, compiler settings, and other options for IntelliSense.

- Logs from running C/C++**: These are sample logs showing diagnostics messages generated during the compilation process in VS Code.

- **Logs from the language server logging**: These are sample logs from the language server, which provides code analysis and other language-specific features in VS Code.

You would replace the placeholders with the actual configurations and logs from your environment.
```

### Other Extensions

Other Extensions:
- Bracket Pair Colorizer 2
- GitLens - Git supercharged
- Python

### Additional context

Additional Context:

Project Environment:

The project is a web application developed using React.js.
The issue occurs specifically when attempting to deploy the application to a production server.
Deployment Process:

The deployment process involves running a series of build scripts followed by transferring the build artifacts to the production server via SSH.
Observations:

The issue seems to be related to the build process, as the application runs without errors in the development environment.
There are no issues reported during the build process, but the deployed application does not function as expected.
Recent Changes:

The issue started occurring after upgrading several dependencies, including React and webpack, to their latest versions.
No significant changes were made to the deployment scripts or server configuration.
Attempts to Resolve:

Reverted the dependency upgrades to their previous versions, but the issue persisted.
Reviewed the build logs for any errors or warnings, but found nothing that would indicate the cause of the issue.
System Information:

OS: Ubuntu 20.04.3 LTS (Local machine), CentOS 7 (Remote server)
Node.js Version: 14.17.0
npm Version: 6.14.13
React Version: 17.0.2
webpack Version: 5.67.0

**Comment by sean-mcmanus** [comment]
Our extension isn't responsible for any navigation menus on a web page.
