### ISSUE TITLE
Included definitions subject to __USE_GNU not found

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#1200]
Windows: 10 1703
VS Code: 1.17.2
C/C++ ext: 0.14.0

I am developing some code destined for Linux on my Windows PC.  The Linux system files are in a folder on my local PC.  The plugin finds most included paths ok but has a problem with definitions such as this in sched.h:

    #ifdef __USE_GNU
    /* Get index of currently used CPU.  */
    extern int sched_getcpu (void) __THROW;
    #endif

My json file contains:

        {
            "name": "Win32",
            "includePath": [
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/linux",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0/tr1",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0/x86_64-wrs-linux",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/python2.7",
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/bits",
                "${workspaceRoot}/driver/pcie",
                "${workspaceRoot}/driver/pcie/include",
                "${workspaceRoot}/Source/pugixml/src",
                "${workspaceRoot}/Source/LedaAP/includes",
                "${workspaceRoot}/Source/LedaAP/SysParam",
                "${workspaceRoot}/Source/LedaAP/FAPI",
                "${workspaceRoot}/Source/LedaCommon/includes",
                "${workspaceRoot}/../vendor/altera/QuartusPrimePro16.0.2/hld/host/include",
                "${workspaceRoot}/Source/LedaAP/BF/includes",
                "${workspaceRoot}/Source/LedaDpdkSock/include",
                "${workspaceRoot}/Source/FixedRegisterSpecification",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/um",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/shared",
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"
            ],
            "defines": [ "__x86_64__", "__USE_GNU" ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceRoot}/.vscode/.browse2.vc.db",
                "path": [
                    "c:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0/um",
                    "${workspaceRoot}"
                ]
            },
            "intelliSenseMode": "clang-x64"
        }

In VS Code, my code is:

![image](https://user-images.githubusercontent.com/7724321/32371115-8221559e-c087-11e7-8986-de11eaeec5b4.png)

In VS Code, if I click on sched_getcpu() and click Go to Definition the editor correctly goes to the definition in sched.h.

Why, in my calling function, does the editor say that "sched_getcpu" is undefined? (i.e. see above screenshot).

**Comment by bobbrow** [comment]
Different engines work on the code browsing and the error squiggles.  The code browsing engine (aka tag parser) doesn't look at most #ifdef statements so the defines don't matter.  The squiggles use our front end compiler to analyze the code and do look at #ifdef statements.  So my suspicion is that there is some other define missing in your configuration.

When you Go To Definition on sched_getcpu() and it opens sched.h,  Do you get a tooltip when you hover over sched_getcpu?  If not, then it means that that section of code is actually inside an inactive preprocessor block (according to our compiler), so you'll need to search higher up in the header file to see which symbol(s) need to be defined to activate that section of code.

**Comment by daldr-ntml** [comment]
Thanks for your reply.  I expect that you are correct that there is a symbol higher in the header file that explains the lack of symbol definition, but I can't identify the reason. I have attached the header file that is causing this issue but this is not an important issue for us, so no need to spend a lot of time on it.
[sched.zip](https://github.com/Microsoft/vscode-cpptools/files/1446787/sched.zip)

**Comment by bobbrow** [comment]
The only thing suspicious I see in that file is `__BEGIN_DECLS`.  If that is not defined, it could be causing an error in the compiler which messes up the parsing of the rest of the file.  You can try adding `"__BEGIN_DECLS="` and `"__END_DECLS="` to your **"defines"** array and see if that resolves the issue. Otherwise, I don't think I have enough context to solve it.  I would need to see the set of files that results in this one being included in order to solve it.

**Comment by daldr-ntml** [comment]
I tried adding the defines you suggested but that didn't help.  Let's close this issue as it's rather obscure and doesn't indicate a problem with the plugin. Thanks for your help.
