### ISSUE TITLE
[DONE!]Fix the c++stl cross-platform intellisence error 

### ISSUE THREAD

**Issue by Lioncky** [microsoft/vscode-cpptools#12000]
### Environment
Bug type: IntelliSense

- OS and Version: win11
- VS Code Version: latest
- C/C++ Extension Version: latest
- If using SSH remote, specify OS of remote machine: 
arm64 android

### Bug Summary and Steps to Reproduce

Bug Summary:
![image](https://github.com/microsoft/vscode-cpptools/assets/73447685/cf99726a-6e87-49e2-a40e-f9e15c87e965)

I don't think it's error but it shows that.

Steps to reproduce:
```c
#include <string> // 1.Ctrl+Click

int src_test()
{
    std::string tmp = "1";
    return 0;
}
```

### Configuration and Logs

```shell
{
    // defines intelliscene
    "configurations": [
        {
            "name": "linux",
            "includePath": [
                "${env:NDKROOT}",
                "${env:NDKROOT}c++/v1/",
                "${env:NDKROOT}aarch64-linux-android/"

            ],

            // "${workspaceFolder}/**",
            // -- http s://github.com/SsageParuders/CheatUnityGames/tree/master
            // "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Linux/gcc_arm/arm-none-eabi/include/**",
            "compilerPath": "${env:NDKDIR}toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe",
            // "cStandard": "c11",
            // "cppStandard": "c++17",
            "cStandard": "gnu11",
            "cppStandard": "c++17",

            // - http s://github.com/microsoft/vscode-cmake-tools/issues/2343
            // - http s://code.visualstudio.com/docs/cpp/configure-intellisense-crosscompilation
            "compilerArgs": [
                "-g",
                "-std=gnu++17",
                "-g",
                "-std=gnu11"
            ],
            "defines": [
                // "__cplusplus=201703",
                // "_LIBCPP_USE_IS_CONVERTIBLE_FALLBACK=1",
                // "CMAKE_C_STANDARD_REQUIRED=1",
                // "CMAKE_CXX_STANDARD_REQUIRED=1",
                // "_LIBCPP_STD_VER=17",
                "__aarch64__"
            ]
            // "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

### Other Extensions
[{
	"resource": "/c:/Microsoft/AndroidNDK64/android-ndk-r26b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/string",
	"owner": "C/C++: IntelliSense",
	"code": "276",
	"severity": 8,
	"message": "name followed by '::' must be a class or namespace name",
	"source": "C/C++",
	"startLineNumber": 2021,
	"startColumn": 30,
	"endLineNumber": 2021,
	"endColumn": 44
},{
	"resource": "/c:/Microsoft/AndroidNDK64/android-ndk-r26b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/string",
	"owner": "C/C++: IntelliSense",
	"code": "276",
	"severity": 8,
	"message": "name followed by '::' must be a class or namespace name",
	"source": "C/C++",
	"startLineNumber": 2029,
	"startColumn": 30,
	"endLineNumber": 2029,
	"endColumn": 44
},{
	"resource": "/c:/Microsoft/AndroidNDK64/android-ndk-r26b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/string",
	"owner": "C/C++: IntelliSense",
	"code": "757",
	"severity": 8,
	"message": "overloaded function \"basic_string_view\" is not a type name",
	"source": "C/C++",
	"startLineNumber": 2031,
	"startColumn": 23,
	"endLineNumber": 2031,
	"endColumn": 57
},{
	"resource": "/c:/Microsoft/AndroidNDK64/android-ndk-r26b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/string",
	"owner": "C/C++: IntelliSense",
	"code": "276",
	"severity": 8,
	"message": "name followed by '::' must be a class or namespace name",
	"source": "C/C++",
	"startLineNumber": 2037,
	"startColumn": 30,
	"endLineNumber": 2037,
	"endColumn": 44
},{
	"resource": "/c:/Microsoft/AndroidNDK64/android-ndk-r26b/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/string",
	"owner": "C/C++: IntelliSense",
	"code": "757",
	"severity": 8,
	"message": "overloaded function \"basic_string_view\" is not a type name",
	"source": "C/C++",
	"startLineNumber": 2040,
	"startColumn": 14,
	"endLineNumber": 2040,
	"endColumn": 48
}]

**Comment by Lioncky** [comment]
not support <__algorithm/clamp.h> as well
```c
// use for test
int i = 1;
i = std::clamp(i, 0, 100); // error intellisence namespace has not member 'clamp' 
```

**Comment by Colengms** [comment]
Hi @Lioncky .  Could you run the `C/C++: Log Diagnostics` command, while the reproing file is open, and provide that log?  That would tell us how IntelliSense has been configured for that file.

I do see a possible issue with your `compilerArgs`:

```
            "compilerArgs": [
                "-g",
                "-std=gnu++17",
                "-g",
                "-std=gnu11"
            ],
```

`compilerArgs` will take precedence over `cStandard` and `cppStandard` settings, so it's possible IntelliSense is misconfigured to use C11 even for C++ files,.  (The last `std` argument takes precedence over previous ones.)

Also, I see that you're specifing aarch64 using a define.

```
            "defines": [
...
                "__aarch64__"
            ]
```

That would be insufficient to configure IntelliSense for arm64 IntelliSense.  I'd suggest either using the `IntelliSenseMode` field, or providing the related compiler arg for setting the target architecture in `compilerArgs`.

```
            // "compileCommands": "${workspaceFolder}/build/compile_commands.json"
```

If you do have a `compile_commands.json` file, that should be a reliable way to configure IntelliSense for a particular file.  If an entry for a file is present in your `compile_commands.json`, the compiler command line there would be used to configure IntelliSense for that file to exactly match how it is compiled.

If you're building with CMake or a makefile, you might consider using the CMake Tools or Makefile Tools extensions, as they can be used to provide configurations directly to the C/C++ Extension based on information available to the build system.

**Comment by Lioncky** [comment]
> Hi ! @Colengms, thank you for your reply.
I have tried every thing you say, and found something funny.
```
1. If specified the 'compilerPath', the 'cppStandard' and 'cStandard' won't work.
2. Even if exist the errors, the intelliscene work, just not very pefert.
3. I dont't have compile_commands.json, just referenced other guys.
4. the compilerArgs has both C and C++ two defines, change will let intelliscene complete crash.
5. my solution can solve my 90% problems, I want to seek an offical method.
6. intelliSenseMode is an selectable option I think, won't solve this.
```
after my check out, I think the vscode intelliscene has something wrong,  and the cmakelists.txt file won't effect the intelliscene
