### ISSUE TITLE
Not all compilers are listed

### ISSUE THREAD

**Issue by cctv130** [microsoft/vscode-cpptools#12006]
### Environment

- OS and Version: latest
- VS Code Version: latest
- C/C++ Extension Version: latest
- If using SSH remote, specify OS of remote machine: ubuntu22.04 server

### Bug Summary and Steps to Reproduce

![image](https://github.com/microsoft/vscode-cpptools/assets/133784576/da0c7bd1-cec9-45f2-92f9-44121f184177)
I have installed clang and gcc, but using ssh link to remote ubuntu can only list gcc but not clang, what do I need to do?
should be found by all compilers in the system

### Configuration and Logs

```shell
![image](https://github.com/microsoft/vscode-cpptools/assets/133784576/da0c7bd1-cec9-45f2-92f9-44121f184177)
```

**Comment by Colengms** [comment]
This would appear to be related to not detecting lldb/lldb-mi on the system.  Currently, both "Debug" and "Run" operations appear to be considered debugging operations, and lldb is required to debug when building with clang (?).

**Comment by browntarik** [comment]
This issue will be closed as a duplicate due to https://github.com/microsoft/vscode-cpptools/issues/5415#issuecomment-629693051
