### ISSUE TITLE
Can't see the run and debug button after installing C/C++ extension.

### ISSUE THREAD

**Issue by UchihaYuki** [microsoft/vscode-cpptools#12004]
### Environment

- OS and version: Windows 10
- VS Code: 1.86.2
- C/C++ extension: 1.19.4
- OS and version of remote machine (if applicable):
- GDB / LLDB version: I use WinGW, the g++ version is 13.2.0

### Bug Summary and Steps to Reproduce

Bug Summary:
![image](https://github.com/microsoft/vscode-cpptools/assets/38900426/199fc186-40bd-4bd4-bd50-6ab7c3e74e77)
You can see from the above picture, there isn't a triangle run button.

Steps to reproduce:
I saw this button appearing automatically for others after installing the extension, but it didn't come up for me. I have to install other extensions to have a run button like Code Runner, but it doesn't have debug function.

### Debugger Configurations

```shell
NA
```

### Debugger Logs

```shell
NA
```

**Comment by UchihaYuki** [comment]
I tried the following, but the button still doesn't appear:
```
  "C_Cpp.intelliSenseEngine": "default",
  "C_Cpp.debugShortcut": true,
```

**Comment by UchihaYuki** [comment]
Any updates?

**Comment by sean-mcmanus** [comment]
@UchihaYuki Sorry for the delayed response -- in the status bar (bottom right) what language is being shown? C++?

**Comment by rababR1** [comment]
https://github.com/microsoft/vscode-cpptools/assets/65360255/95ea0691-bfed-4adb-a473-6be352b56e76

Same issue here. Let's hope that this gets fixed soon. I'm using Insiders. the latest build...

**Comment by sean-mcmanus** [comment]
@rababR1 Your issue may be caused by some other C/C++ code runner extension. Can you try disabling the other extension?
