### ISSUE TITLE
Doxygen multi-whitespace parsing regression

### ISSUE THREAD

**Issue by alexandruavadanii** [microsoft/vscode-cpptools#12015]
Type: <b>Bug</b>

Before v1.19.4 (~up to and including v1.19.3~ sorry, I mixed up the versions, apparently it was already broken in v1.19.x, but it works fine in v1.18.5), both Doxygen comments for these 2 functions were parsed correctly:

``` c
/**
 * @fn cpptools_test1
 * @brief desc for this void func
 * 
 * @param p1   some pointer
 * @param p2   some other pointer
 */
static void
cpptools_test1(void *p1, void *p2)
{
   (void)p1;
   (void)p2;
}

/**
 * @fn cpptools_test2
 * @brief      desc for this void func
 * 
 * @param  p1  some pointer
 * @param  p2  some other pointer
 */
static void
cpptools_test2(void *p1, void *p2)
{
   (void)p1;
   (void)p2;
}
```

Starting with v1.19.4, the comment for `cpptools_test1` is parsed correctly, but `cpptools_test2` (which has 2 or more spaces after the Doxygen keywords) is broken - note the coalescing of the parameter name with its description, as well as keyword highlighting in the function description. Looks like the @fn keyword works with 1...4 spaces, but not more.

![image](https://github.com/microsoft/vscode-cpptools/assets/11544783/9855a503-ee7d-4fa1-8984-56747ecf7a78)

![image](https://github.com/microsoft/vscode-cpptools/assets/11544783/990e2519-ed51-47db-b12b-59fb491995c6)

Extension version: 1.19.4
VS Code version: Code - Insiders 1.87.0-insider (c11a2dd4d52e38cb92b8c464f47a7b02bb7c8762, 2024-02-24T01:20:40.384Z)
OS version: Windows_NT x64 10.0.18362
Modes:
Remote OS version: Linux x64 4.18.0-372.19.1.el8_6.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sestolabccv8|
|OS|Linux x64 4.18.0-372.19.1.el8_6.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|31.21GB (17.83GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: sestolabccv8|
|OS|Linux x64 4.18.0-372.19.1.el8_6.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2095)|
|Memory (System)|31.21GB (17.83GB free)|
|VM|100%|
</details>

**Comment by sean-mcmanus** [comment]
@alexandruavadanii Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.5

**Comment by alexandruavadanii** [comment]
@sean-mcmanus Verified, all ok, thank you!
