### ISSUE TITLE
C/C++ intellisense extension shows false positive matches

### ISSUE THREAD

**Issue by adam2farkas** [microsoft/vscode-cpptools#12018]
### Environment

- OS and Version: RedHat 8
- VS Code Version: 1.86.2
- C/C++ Extension Version: 1.19.4
- If using SSH remote, specify OS of remote machine: RedHat 8

### Bug Summary and Steps to Reproduce

Bug Summary:
Hovering over a token, the plugin is supposed to show information regarding the token, eg. signature for a method or definition for a type. Now, the plugin shows all possible matches, so if you want information about a method, it shows the signature of all the methods in the project with the given name rather than the ones within the given context ( e.g. class). See the picture attached.

Steps to reproduce:
Just open a project with some files that contains samely named methods in different classes.

Expected behavior:
Show just members and methods belonging to the current context.
![Képernyőkép 2024-01-16 133718](https://github.com/microsoft/vscode-cpptools/assets/159886449/f9c7fda8-8c8a-47a5-8850-bcc5f5cdb8d5)

### Configuration and Logs

I was only able to find the schema file of c_cpp_properties.json

**Comment by bobbrow** [comment]
Hi @adam2farkas,

Did you by chance set the `C_Cpp.intelliSenseEngine` setting to `"Tag Parser"`?  This looks like the type of result you can get when you disable the higher-fidelity "default" engine.  The other issue you opened #12019 may also be a result of using this setting.
