### ISSUE TITLE
The 'Add #include' code action incorrectly uses "../" instead of <> when an includePath is used that is lexicographically less than the source file's parent directory

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#12010]
See the 2 screenshots: If the includePath has "${workspaceFolder}/a" then the bug repros,

<img width="360" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/ac1fe3c8-f33a-4c6b-b854-7fd98d001543">

but with "${workspaceFolder}/t" it behaves correctly -- t is lexicographically greater than the source's parent directory "sub".
<img width="354" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/19859882/ff9ebd1a-8f54-4510-8d38-9c28383e7f58">

Tests added for https://github.com/microsoft/vscode-cpptools/issues/11989 caused this to start to be hit (after a lexigraphically smaller includePath was added).

**Comment by AlexandraKemperMS** [comment]
Also repos for me when removing the algorithms library from the ship.cpp file in endless sky (https://github.com/endless-sky/endless-sky/blob/master/source/Ship.cpp) and adding a call to transform: 
![image](https://github.com/microsoft/vscode-cpptools/assets/67650598/bf52ff6e-6b9d-4638-bd5d-c3e333acf470)

**Comment by browntarik** [comment]
This issue no longer reproes as of version 1.22.4.

**Comment by sean-mcmanus** [comment]
I got a repro with a our internal test project.
