### ISSUE TITLE
Support MSVC prior to Visual Studio 2015 (older standard versions, system include paths)

### ISSUE THREAD

**Issue by ZivDero** [microsoft/vscode-cpptools#12029]
### Environment

- OS and Version: Windows 11 23H2 22635.3212
- VS Code Version: 1.86.2
- C/C++ Extension Version: 1.19.4
- If using SSH remote, specify OS of remote machine: not using SSH

### Bug Summary and Steps to Reproduce

Bug Summary: Intellisense refuses to downgrade the C and C++ standards' versions. Trying to use C++98 and C19 results in the following messages in the output:

```
[2/27/2024, 6:33:17 PM] For C++ source files, the cppStandard was changed from "c++98" to "c++14" based on compiler args and querying compilerPath: "cl.exe"
[2/27/2024, 6:33:18 PM] For C source files, the cStandard was changed from "c99" to "c17" based on compiler args and querying compilerPath: "cl.exe"
```

Intellisense then proceeds to function with supposedly the specified versions (e. g. the auto keyword is recognized as valid).
The complier I am using is MSVC6.3 from VS6 SP3 (for legacy reasons). VS code was launched from the terminal after running VSVARS32.BAT to set up the environment variables. VSVARS.BAT has had `set DevEnvDir=Path\To\VS6\Bin` added to the end to make the extension recognize it as DevEnv. The build task does function properly and executes CL.EXE from MSCV6.3.

Moreover, the `_MSC_VER` define contains a newer version than expected (1200 expected).

Steps to reproduce:
1. Go to 'C/C++ Configurations'
2. Set C/C++ versions to C99/C++98 respectively

Expected behavior: Version of C/C++ used by Intellisense is set correctly

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "WIN32",
                "NDEBUG",
                "_WINDOWS",
                "_MBCS",
                "WINSOCK_IPX",
                "_MSC_VER=1200"
            ],
            "windowsSdkVersion": "10.0.22621.0",
            "compilerPath": "cl.exe",
            "cStandard": "c99",
            "cppStandard": "c++98",
            "intelliSenseMode": "msvc-x86",
            "compilerArgs": [
                "/nologo",
                "/Gr",
                "/Zp8",
                "/MT",
                "/W3",
                "/GR",
                "/Z7",
                "/Ot",
                "/Og",
                "/Oi",
                "/Oy",
                "/Ob2",
                "/Gf",
                "/FD"
            ]
        }
    ],
    "version": 4
}
```

```
loggingLevel: Debug
loggingLevel has changed to: Debug
LSP: (invoked) cpptools/didChangeCppProperties (id: 344)
LSP: Sending response (id: 344)
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) textDocument/didOpen: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp
LSP: (invoked) textDocument/didOpen: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
Intellisense update pending for: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp
LSP: (received) cpptools/didChangeActiveEditor: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp
LSP: (received) cpptools/getCodeActions: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 345)
LSP: (invoked) cpptools/didChangeActiveEditor: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp
LSP: (received) cpptools/getDocumentSymbols: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 346)
LSP: (invoked) cpptools/getDocumentSymbols: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 346)
LSP: (received) cpptools/didChangeTextEditorSelection
LSP: (invoked) cpptools/getCodeActions: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 345)
LSP: Sending response (id: 345)
LSP: (invoked) cpptools/didChangeTextEditorSelection
LSP: Sending response (id: 346)
IntelliSense update scheduled and TU acquisition started for: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp
Resolving recursive includes...
Done resolving recursive includes.
sending compilation args for D:\Projects\OpenYR\gamemd\Lib\Vector.hpp
  include: G:\MICROSOFT VISUAL STUDIO\VC98\ATL\INCLUDE
  include: G:\MICROSOFT VISUAL STUDIO\VC98\INCLUDE
  include: G:\MICROSOFT VISUAL STUDIO\VC98\MFC\INCLUDE
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\UM
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\UCRT
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\SHARED
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\WINRT
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\CPPWINRT
  define: _MT
  define: WIN32
  define: NDEBUG
  define: _WINDOWS
  define: _MBCS
  define: WINSOCK_IPX
  define: _MSC_VER=1200
  other: --pack_alignment
  other: 8
  other: --rtti
  stdver: ms_c++14
  intelliSenseMode: windows-msvc-x86
Update IntelliSense time (sec): 0.083
LSP: (received) cpptools/getCodeActions: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 347)
LSP: (invoked) cpptools/getCodeActions: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 347)
LSP: Sending response (id: 347)
LSP: (received) cpptools/getFoldingRanges: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 348)
LSP: (invoked) cpptools/getFoldingRanges: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 348)
LSP: Sending response (id: 348)
LSP: (received) cpptools/getCodeActions: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 349)
LSP: (invoked) cpptools/getCodeActions: file:///d%3A/Projects/OpenYR/gamemd/Lib/Vector.hpp (id: 349)
LSP: Sending response (id: 349)
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) textDocument/documentHighlight: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 350)
LSP: (invoked) textDocument/documentHighlight: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 350)
LSP: Sending response (id: 350)
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
Intellisense update pending for: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp
LSP: (received) cpptools/didChangeActiveEditor: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp
LSP: (received) cpptools/getCodeActions: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 351)
LSP: (received) cpptools/didChangeTextEditorSelection
LSP: (invoked) cpptools/didChangeActiveEditor: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp
LSP: (invoked) cpptools/getCodeActions: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 351)
LSP: Sending response (id: 351)
LSP: (invoked) cpptools/didChangeTextEditorSelection
IntelliSense update scheduled and TU acquisition started for: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp
Resolving recursive includes...
  tag parsing file: D:\Projects\OpenYR\gamemd\AbstractType.hpp
Done resolving recursive includes.
sending compilation args for D:\Projects\OpenYR\gamemd\AbstractType.hpp
  include: G:\MICROSOFT VISUAL STUDIO\VC98\ATL\INCLUDE
  include: G:\MICROSOFT VISUAL STUDIO\VC98\INCLUDE
  include: G:\MICROSOFT VISUAL STUDIO\VC98\MFC\INCLUDE
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\UM
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\UCRT
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\SHARED
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\WINRT
  include: G:\WINDOWS KITS\10\INCLUDE\10.0.22621.0\CPPWINRT
  define: _MT
  define: WIN32
  define: NDEBUG
  define: _WINDOWS
  define: _MBCS
  define: WINSOCK_IPX
  define: _MSC_VER=1200
  other: --pack_alignment
  other: 8
  other: --rtti
  stdver: ms_c++14
  intelliSenseMode: windows-msvc-x86
LSP: (received) cpptools/getFoldingRanges: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 352)
LSP: (invoked) cpptools/getFoldingRanges: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 352)
Error squiggles will be disabled in: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp
Update IntelliSense time (sec): 0.147
LSP: $/cancelRequest (cpptools/getFoldingRanges, id: 352)
LSP: Request canceled by server (<unknown/completed>, code: -32802, id: 352)
LSP: (received) cpptools/getFoldingRanges: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 353)
LSP: (invoked) cpptools/getFoldingRanges: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 353)
LSP: Sending response (id: 353)
Database safe to open.
LSP: (received) textDocument/definition: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 354)
LSP: (invoked) textDocument/definition: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 354)
LSP: Sending response (id: 354)
LSP: (received) textDocument/hover: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 355)
LSP: (invoked) textDocument/hover: file:///d%3A/Projects/OpenYR/gamemd/AbstractType.hpp (id: 355)
LSP: Sending response (id: 355)
```
```


### Other Extensions

_No response_

### Additional context

_No response_

**Comment by Colengms** [comment]
Hi @ZivDero .  I believe what you're seeing is because MVSC (`cl.exe`) does not support `c99` or `c++98`, so this setting is getting reverted to its default.

Supported standard values for `cl.exe` are listed here: https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170

```
/std:c++14
/std:c++17
/std:c++20
/std:c++latest
/std:c11
/std:c17
/std:clatest
```

**Comment by ZivDero** [comment]
> Hi @ZivDero . I believe what you're seeing is because MVSC (`cl.exe`) does not support `c99` or `c++98`, so this setting is getting reverted to its default.
> 
> Supported standard values for `cl.exe` are listed here: https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170
> 
> ```
> /std:c++14
> /std:c++17
> /std:c++20
> /std:c++latest
> /std:c11
> /std:c17
> /std:clatest
> ```

Hi @Colengms. It is true that modern MSVC does not in fact support `c99` or `c++98`. However, the really old version of MSVC that I'm using does in fact support them. The extension's features for working with MSVC seems absolutely able to handle that old version, but this automatic forcing of the standard is not helpful since I can't have version-accurate Intellisense.

**Comment by Colengms** [comment]
Hi @ZivDero .  Currently, the C/C++ Extension for VS Code supports MSVC only as far back as Visual Studio 2015.  We can use this issue as a feature request to track supporting prior versions of MSVC.

**Comment by ZivDero** [comment]
> Hi @ZivDero . Currently, the C/C++ Extension for VS Code supports MSVC only as far back as Visual Studio 2015. We can use this issue as a feature request to track supporting prior versions of MSVC.

I'm glad that it's being considered.

One thing I can give input on is that what is now called DevEnv used to be called MSDev. Currently, the extesions looks for the `DevEnvDir` environment variable, which prior to the renaming used to be called `MSDevDir`. As such, to get the extension to recognize that you're running the "Developer Console" you need to add that variable to VCVARS32.BAT manually currently.

**Comment by bobbrow** [comment]
@Colengms we did have an issue open requesting pre-VS2015 support here: #3687.  It was closed as needing more votes.  I suspect that this may turn into a "help wanted" task when we add the infrastructure to support additional compilers.

**Comment by ZivDero** [comment]
@bobbrow Actually, the specific issue mentioned in that issue seems to have already been resolved (perhaps when automatic include path querying was introduced) and as of now I am having no issues with includes, the files it finds are correctly located in the compiler's includes.

**Comment by bobbrow** [comment]
> @bobbrow Actually, the specific issue mentioned in that issue seems to have already been resolved (perhaps when automatic include path querying was introduced) and as of now I am having no issues with includes, the files it finds are correctly located in the compiler's includes.

Which version of the compiler are you using?  This surprises me because we haven't done any work to support VS2013 and earlier that I am aware of.

**Comment by ZivDero** [comment]
> > @bobbrow Actually, the specific issue mentioned in that issue seems to have already been resolved (perhaps when automatic include path querying was introduced) and as of now I am having no issues with includes, the files it finds are correctly located in the compiler's includes.
> 
> Which version of the compiler are you using? This surprises me because we haven't done any work to support VS2013 and earlier that I am aware of.

Yeah, I was very pleasantly surprised how *few* issues I am having.
I'm using the complier supplied with Visual Studio 6 SP3, which would be MSVC 6.3, I think, _MSC_VER=1200 (this define is resolved incorrectly by Intellisense for me, btw, to 19-something).

**Comment by Colengms** [comment]
> @Colengms we did have an issue opened requesting pre-VS2015 support here: https://github.com/microsoft/vscode-cpptools/issues/3687. It was closed as needing more votes. I suspect that this may turn into a "help wanted" task when we add the infrastructure to support additional compilers (https://github.com/microsoft/vscode-cpptools/issues/6931).

Closing this as a duplicate.  @ZivDero , I'd suggest up-voting that issue: https://github.com/microsoft/vscode-cpptools/issues/3687

**Comment by ZivDero** [comment]
> > @Colengms we did have an issue opened requesting pre-VS2015 support here: #3687. It was closed as needing more votes. I suspect that this may turn into a "help wanted" task when we add the infrastructure to support additional compilers (#6931).
> 
> Closing this as a duplicate. @ZivDero , I'd suggest up-voting that issue: #3687

I don't seem to be able to? Sorry if this is somethin obvious I'm missing, but I'd be grateful if you could provide a small guide.

**Comment by Colengms** [comment]
Hi @ZivDero .  We track up-votes using thumbs-up reactions on the initial comment.  Is that accessible to you on the other issue?

![image](https://github.com/microsoft/vscode-cpptools/assets/49173979/7b8ab456-657c-4fd2-9a6f-9d39fa905055)
