### ISSUE TITLE
Header file not find in workspace？

### ISSUE THREAD

**Issue by deweixu** [microsoft/vscode-cpptools#1203]
<img width="392" alt="2017-11-04 1 01 50" src="https://user-images.githubusercontent.com/10754726/32402512-c9a96ab6-c0f3-11e7-8377-08251e8bdfa4.png">

`tlpi_hdr.h` path is `${workspaceRoot}/lib/` and my includePath configuration:

```
"includePath": [
    "/usr/include/c++/4.2.1",
    "/usr/local/include",
    "/usr/include",
    "${workspaceRoot}/lib",
    "${workspaceRoot}"
 ]

```

**Comment by sean-mcmanus** [comment]
The tooltip message shown in the screenshot is not from our extension. Do you have another extension installed?
