### ISSUE TITLE
Performance Investigation: time-to-colorization

### ISSUE THREAD

**Issue by fearthecowboy** [microsoft/vscode-cpptools#12030]
Looking at opportunities to globally improve the speed of time-to-colorization (and tag parsing)

Currently, it looks like there can be benefits in some deep I/O optimization (early enumerating folders, quicker include file lookups ,pre-populating caches with expected files, etc)

**Comment by heartacker** [comment]
we need this

**Comment by sean-mcmanus** [comment]
@heartacker The fix/improvements are available with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.22.0

**Comment by heartacker** [comment]
> @heartacker The fix/improvements are available with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.22.0

thank you :D
