### ISSUE TITLE
__STDC_VERSION__ macro expanding to wrong value

### ISSUE THREAD

**Issue by settingsadmin** [microsoft/vscode-cpptools#12047]
Type: <b>Bug</b>

Expands to value 201710L, even when C standard is specified as some other value in the extension's settings. 

Extension version: 1.19.4
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
cppperfnew:30973185
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
8f97e687:30977000
dsvsc020:30976470

```

</details>

**Comment by Colengms** [comment]
Hi @uitkering .  I'm not able to reproduce this issue.  If I specify `"cStandard": "c23"`, I see:

![image](https://github.com/microsoft/vscode-cpptools/assets/49173979/5d9be16e-8442-4e4f-bf43-8559a5a5120a)

Can you please provide the extension settings you are using?  I suspect there is a setting, such as a custom configuration provider extension or compile_commands.json file, that is taking precedence over C standard setting.
