### ISSUE TITLE
"#include errors detected. Consider updating..." | Unexpected Intellisense errors occuring on v1.19.4

### ISSUE THREAD

**Issue by 3thanjmac** [microsoft/vscode-cpptools#12049]
### Environment

- OS and Version: macOS | Sonoma 14.3.1
- VS Code Version: 1.87.0
- C/C++ Extension Version: 1.19.4
- If using SSH remote, specify OS of remote machine:  N/A

### Bug Summary and Steps to Reproduce

Bug Summary:
Intellisense displays error on Unreal Engine 5 C++ files stating source files could not be opened. Tried rebuilding from Visual Studio as well as refreshing Visual Studio code from the Unreal Editor. Error is not present in C/C++ version 1.18.5.

Steps to reproduce:
1. Update C/C++ Intellisense extension to version 1.19.4
2. Open Unreal Engine 5 project and corresponding C++ files in Visual Studio

Expected behavior:
Intellisense errors appear on project's ".h" and ".cpp" files with the following errors:

" #include errors detected. Consider updating your compile_commands.json or includePath. Squiggles are disabled for this translation unit (/Users/ethanjmac/Documents/Unreal Projects/DungeonCrypt/Source/DungeonCrypt/TriggerComponent.cpp).C/C++(1696) "

" cannot open source file "initializer_list" (dependency of "/Users/ethanjmac/Documents/Unreal Projects/DungeonCrypt/Intermediate/Build/Mac/arm64/DungeonCryptEditor/Development/Engine/SharedPCH.Engine.Cpp20.h")C/C++(1696) "

[c_cpp_properties.json](https://github.com/microsoft/vscode-cpptools/files/14470940/c_cpp_properties.json)
[log_diagnostics.txt](https://github.com/microsoft/vscode-cpptools/files/14470941/log_diagnostics.txt)

### Configuration and Logs

```shell
Configuration and logs submitted above.
```

**Comment by sean-mcmanus** [comment]
This looks like it's caused by the C++ system includes not being used. Can you look at your C/C++ logging with C_Cpp.loggingLevel set to "Debug". Can look for a failure in your C/C++ logging in regards to compiler querying?

**Comment by sean-mcmanus** [comment]
Another user reported this at https://github.com/Microsoft/vscode-cpptools/issues/12940 .
