### ISSUE TITLE
setting 'editor.suggest.showSnippets'=false disables snippets in button "Add Configuration..." of launch.json

### ISSUE THREAD

**Issue by godgnidoc** [microsoft/vscode-cpptools#12059]
### Environment

- OS and version: Ubuntu 22.04.4 LTS
- VS Code: 1.87.0
- C/C++ extension: v1.19.5
- OS and version of remote machine (if applicable):
- GDB / LLDB version: 12.1

### Bug Summary and Steps to Reproduce

Bug Summary:

Since I set the setting `editor.suggest.showSnippets=false`, I cannot find following items in the hint box:

- `C/C++: (gdb) Attach`
- `C/C++: (gdb) Launch`
- `C/C++: (gdb) Pipe Attach`
- `C/C++ (gdb) Pipe Launch`

Steps to reproduce:
1. Create a workspace with some `cpp` source file.
2. Open one of them, hit the hot key `f5` to try to start debug.
3. There's no `launch.json`, follow the instruction to create one, and open the editor for it.
4. Hit "**Add Configuration...**" button on the bottom right corner.
5. Look for items listed above, none of then appears.

### Debugger Configurations

```shell
not yet
```

### Debugger Logs

```shell
not yet
```

**Comment by sean-mcmanus** [comment]
@godgnidoc We have a fix pending at https://github.com/microsoft/vscode-cpptools/pull/12080, but you can also work around this via using

```jsonc
    "editor.suggest.showSnippets": false,
    "[jsonc]": {
        "editor.suggest.showSnippets": true
    }
```

which will enable snippets for the launch.json file.

**Comment by godgnidoc** [comment]
@sean-mcmanus 

Such an amazing architecture, appreciate your bug fix and temporary solution.

**Comment by sean-mcmanus** [comment]
@godgnidoc Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.20.0
