### ISSUE TITLE
Failed at stage: removeUnnecessaryFile

### ISSUE THREAD

**Issue by georgehao** [microsoft/vscode-cpptools#1205]
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (OS X)' (6525 KB) .................... Done!
Downloading package 'ClangFormat (OS X)' (806 KB) .................... Done!
Downloading package 'Mono Framework Assemblies' (4751 KB) .................... Done!
Downloading package 'Mono Runtime (OS X)' (1549 KB) .................... Done!
Downloading package 'LLDB 3.8.0 (OS X)' (19125 KB) .................... Done!

Installing package 'C/C++ language components (OS X)'
Installing package 'ClangFormat (OS X)'
Installing package 'Mono Framework Assemblies'
Installing package 'Mono Runtime (OS X)'
Installing package 'LLDB 3.8.0 (OS X)'
Failed at stage: removeUnnecessaryFile
TypeError: Cannot read property 'indexOf' of undefined

Finished

how to do it ?

**Comment by georgehao** [comment]
my os is macos 10.13

**Comment by pieandcakes** [comment]
@georgehao Which version of the extension are you using?

I tested it on my Mac running mac OS 10.11 and with version 0.14.0 of the Cpp extension and it works. I don't know if it is an issue with Mac OS 10.13 though.

That step is to rename a file that can cause problems on platforms other than windows. Its located in `~/.vscode/extensions/ms-vscode.cpptools-0.14.0/debugAdapters/bin/` and is supposed to rename `OpenDebugAD7.exe.config` to `OpenDebugAD7.exe.config.unused`. If you reload VSCode does it succeed the second time?

**Comment by sean-mcmanus** [comment]
Yeah, I don't see an indexOf call in the code. You could try modifying the javaScript to try to unblock you or troubleshoot the cause: `/Users/<user>/.vscode/extensions/ms-vscode.cpptools-0.14.0/out/src/main.js` search for "removeUnnecessaryFile".

**Comment by georgehao** [comment]
@pieandcakes @sean-mcmanus  I try it, it's ok,

**Comment by georgehao** [comment]
my extension is  0.14.0
