### ISSUE TITLE
Terminal running vscode tool cannot function properly

### ISSUE THREAD

**Issue by xiaofeixia190716** [microsoft/vscode-cpptools#12062]
My computer Window 10专业版  version：21H2
vscode version：VSCodeUserSetup-x64-1.87.0
Terminal error sharescreen：
![vscode issue1](https://github.com/microsoft/vscode-cpptools/assets/153441703/0336f395-01ef-4acc-a043-96e7100b6427)

**Comment by bobbrow** [comment]
Can you please [report this to the VS Code team](https://github.com/microsoft/vscode/issues/new/choose)?  The C++ extension does not have any interactions with the launching of VS Code itself.

**Comment by xiaofeixia190716** [comment]
Can you give me a way to contact the vscode team?
Or can you help me transfer to the vscode team?
