### ISSUE TITLE
Can you support single 'arguments' instead of args array in launch.json?

### ISSUE THREAD

**Issue by xbcnn** [microsoft/vscode-cpptools#1206]
VSCode Version: 1.17.2
OS Version: win10
Steps to Reproduce:

1.  Config launch.json for Windows C++ project.

2.  Config "args"
     If there are multiple args, then we have to list them one by one with quotation and comma seperated. For example:
         "program": "${workspaceRoot}\a.exe",
         "args": [ "a", "b=1", "c=2" ]
3.  I hope to use a single 'arguments' like shell command line in this way:
        "program": "${workspaceRoot}\a.exe",
        "arguments": [ "a b=1 c=2" ]

    Which is much easier than args arrays in 2.
    Thanks.

**Comment by bobbrow** [comment]
Unfortunately, we don't own the format of this file so this is not something we can change.  You can make the suggestion to the VS Code team and see if they would like to support your case.  https://github.com/Microsoft/vscode/issues

**Comment by xbcnn** [comment]
I did.  See:  https://github.com/Microsoft/vscode/issues/37200

"We have no plans to change this for the builtin debugger extension. However, the attributes available in a launch config are defined by the debug extension. So you might want to file this feature request against the C++ debug extension."
