### ISSUE TITLE
Can't use globstar in the middle of the path in includePath

### ISSUE THREAD

**Issue by ggladilov** [microsoft/vscode-cpptools#12070]
### Environment

- OS and Version: macOS Sonoma Version 14.3.1
- VS Code Version: 1.87.0 (Universal)
- C/C++ Extension Version: 1.19.5

### Bug Summary and Steps to Reproduce

Bug Summary:

Path with globstar in the middle of the path doesn't work in `includePath` of `c_cpp_properties.json`. Example of usage:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/opt/homebrew/opt/**/include", <- faulty path
                "/opt/homebrew/opt/opencv/include/opencv4",
                "/opt/homebrew/opt/openvino/include"
            ],
...
    "version": 4
}
```

Per https://github.com/microsoft/vscode-cpptools/issues/723 I tried both `**` and `*`, but the result is the same:

<img width="596" alt="Screenshot 2024-03-06 at 19 39 29" src="https://github.com/microsoft/vscode-cpptools/assets/8751635/b77d9055-1eeb-41f7-b5d8-2bbcc2a21942">

Using `ls /opt/homebrew/opt/**/include` locally in external terminal shows multiple matches as expected.

Steps to reproduce:
1. Go to 'c_cpp_properties.json' file and add path with globstar in the middle to `includePath`
2. See error

Expected behavior: multiple directories as a result of globstar expansion would be added to `includePath`

### Configuration and Logs

```shell
`c_cpp_properties.json`:


{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/opt/homebrew/opt/**/include",
                "/opt/homebrew/opt/opencv/include/opencv4",
                "/opt/homebrew/opt/openvino/include"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/opt/homebrew/opt/llvm/bin/clang++",
            "cStandard": "c23",
            "cppStandard": "c++23",
            "intelliSenseMode": "macos-clang-arm64",
            "compileCommands": "${command:cmake.buildDirectory}/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Comment by browntarik** [comment]
Thank you for reporting your issue, we will have a fix out shortly.

**Comment by browntarik** [comment]
After further investigation, this seems to just be a squiggle issue. Could you please provide the output from the C/C++: Log Diagnostics command? It is likely that the paths are correctly expanded and the squiggle is just appearing incorrectly.

**Comment by sean-mcmanus** [comment]
@ggladilov Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.20.0
