### ISSUE TITLE
VSCode is no longer supporting specifiying a commandId in the "initialConfigurations" contribution

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-cpptools#1207]
Hi,

We noticed your extension in `package.json` is using a `"initialConfigurations"` contribution in a deprecated way by specifiying a command id.
We wanted to let you know that we plan to delete support for this specific use of "initialConfigurations" soon.
More about this deprecation can be found [here](https://github.com/Microsoft/vscode/issues/33791) and in our release notes.
A good example on how to use the `DebugConfigurarationProvider` which is the new way of doing this can be found [here](https://github.com/Microsoft/vscode-node-debug/blob/d61ac00e16069fe63a5a5b6c65a4040de013e7f2/src/node/extension/configurationProvider.ts#L18)

Also note other deprecations which are specified in our release notes (which can be found on our site).

Kind regards,
Isidor from the VSCode team

**Comment by bobbrow** [comment]
I believe @pieandcakes has already addressed this and it will be updated in our release this week.  Thanks.

**Comment by pieandcakes** [comment]
@wardengnaw this is something you fixed right?

**Comment by WardenGnaw** [comment]
@pieandcakes Yes.
