### ISSUE TITLE
Non-existent relative path variables (i.e {workspaceFolderBasename}) do not squiggle even though it results in an incorrect path

### ISSUE THREAD

**Issue by browntarik** [microsoft/vscode-cpptools#12089]
![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/4e18ec52-cfdf-403f-aeda-14bdd092b9d5)

{workspaceFolderBasename} does not squiggle though it expands to an incorrect path

**Comment by sean-mcmanus** [comment]
This issue only seems to repro for variables that result in a relative path. I'm seeing it give a squiggle with a full path, e.g. ${workspaceFolder}.
