### ISSUE TITLE
Debugging Call Stack with pipeTransport

### ISSUE THREAD

**Issue by chaneyw** [microsoft/vscode-cpptools#1209]
Is it possible to provide a separate root path to the call stack for debugging?

Here is the use case where there is a problem (maybe I am missing something):

I have mapped directories to a docker container (docker run -v argument). The absolute path to the files inside the docker container is different from my local environment. Using pipeTransport, I can launch and debug .. I pipe my program via docker exec -c. 

The problem is that the links to the files in the stack trace don't work making it seemingly impossible to use the stack trace with docker volume mounting unless the local and container paths are exactly aligned. 

Here is example of launch.json

            {
                "name": "(gdb) Launch",
                "type": "cppdbg",
                "request": "launch",
                "program": "/code/build/app",
                "args": ["--path", "/data/"],
                "stopAtEntry": false,
                "cwd": "/",
                "environment": [],
                "externalConsole": false,
                "pipeTransport": {
                    "pipeCwd": "/",
                    "pipeProgram": "docker",
                    "pipeArgs": ["exec", "-i", "DockerName", "sh", "-c"],
                    "debuggerPath": "/usr/bin/gdb"
                },
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }

Is there anyway around this?

**Comment by pieandcakes** [comment]
@chaneyw You should be able to add `"sourceFileMap"` { "docker-file-path": "local-file-path" }` and do a folder level replacement. 

Example: If in the docker container your code resides in `/src/file/path/a.cpp` and locally it is in `/src/folder/path/a.cpp` you can add:

`"sourceFileMap": { "/src/file":"/src/folder" }` and all files and folders under there will now be updated.
