### ISSUE TITLE
Run button goes away after reopening. 

### ISSUE THREAD

**Issue by nshahdoost** [microsoft/vscode-cpptools#12096]
### Environment

- OS and Version: Ubuntu 2022.04.4 LTS
- VS Code Version:  1.87.1
- C/C++ Extension Version: 1.19.7
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Rub button goes away apparently before today. but when i cliched i reset menu it came back.
from the time i start using source control it is gone and desen't go back by resting menu or reopening vs code.

Steps to reproduce:
1-open vs code
2-  select a cpp code
there is no way to run file 

Expected behavior:

### Configuration and Logs

```shell
{

    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/home/nima/Projects/libs/opencv/installed/include/opencv4"           
            ],
            "defines": ["DEBUG__", "MY_FEATURE=1"],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "linux-clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by nshahdoost** [comment]
start bottom goes away. no way to run the program

**Comment by sean-mcmanus** [comment]
@nshahdoost Which run/start button? Can you provide a screenshot?

**Comment by nshahdoost** [comment]
sure

![Screenshot from 2024-03-16 13-17-02](https://github.com/microsoft/vscode-cpptools/assets/68805542/795d684f-ea84-470f-96f9-ee66bb6bed28)

and this is my c_cpp_properties.json:

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/home/nima/Projects/libs/opencv/installed/include/opencv4" 
            ],
            "defines": [],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "linux-clang-x64"
        }
    ],
    "version": 4
}

I found that when I change  "cppStandard" to  "c++17" this problem occurs (default value was c++14)
I should mention than i am using last version of g++ which supports c++17

**Comment by Limitlessindustries** [comment]
> ### Environment
> 
> - OS and Version: Ubuntu 2022.04.4 LTS
> - VS Code Version:  1.87.1
> - C/C++ Extension Version: 1.19.7
> - If using SSH remote, specify the OS of remote machine: 
> 
> 
> ### Bug Summary and Steps to Reproduce
> 
> Bug Summary:
> Rub button goes away apparently before today. but when i cliched i reset menu it came back.
> from the time i start using source control it is gone and desen't go back by resting menu or reopening vs code.
> 
> Steps to reproduce:
> 1-open vs code
> 2-  select a cpp code
> there is no way to run file 
> 
> Expected behavior:
> 
> 
> ### Configuration and Logs
> 
> ```shell
> {
> 
>     "configurations": [
>         {
>             "name": "Linux",
>             "includePath": [
>                 "${workspaceFolder}/**",
>                 "/home/nima/Projects/libs/opencv/installed/include/opencv4"           
>             ],
>             "defines": ["DEBUG__", "MY_FEATURE=1"],
>             "cStandard": "c17",
>             "cppStandard": "c++17",
>             "intelliSenseMode": "linux-clang-x64"
>         }
>     ],
>     "version": 4
> }
> ```
> 
> 
> ### Other Extensions
> good guardians[$]_
> _No response_!
> ###[]()
> ### Additional context
> httpforeverforward 
> _No response_¤
- >Thankyou#[]()MAKEGOODCHOICES!

**Comment by Limitlessindustries** [comment]
Mind you I literally created spacebound \Spacebound.Industries! MAKEGOODCHOICES from a Samsung Galaxy A53 for the past 4 months. The fact I made it this far with no computer knowledge.
>#makeyourbed_
>
>[]()

**Comment by browntarik** [comment]
This usually occurs when the IntelliSense process is no longer available. Could you provide the output to the C/C++: Log Diagnostics command while reproducing the error?
