### ISSUE TITLE
Slightly different IntelliSense hanging issue

### ISSUE THREAD

**Issue by KokopelliP** [microsoft/vscode-cpptools#12104]
### Environment

- OS and Version: Windows 10 22H2 19045.4046. Additional info: Building with GCC in WSL2/Ubuntu 22.04.3 using makefiles.
- VS Code Version: 1.87.2
- C/C++ Extension Version: 1.19.8
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:
While writing my C programs, regardless of workspace or file, IntelliSense features don't work. For example, parts of my code fail to colorize and no info is shown when hovering over parts of my code. Instead, the hover box shows "Loading..." When I hover over the C/C++ button at the bottom (looks like "{ } C") it says "Initializing..." While this issue occurs, I am unable to run any C/C++ extension commands until the extension stops hanging, at which point any executed commands will run before the extension hangs again.

I have both cpptools.exe and cpptools-srv.exe in the extension's folder, and both run without error from CLI. When running VS Code with the extension, I do not see cpptools-srv in the list of processes but I do see cpptools. the cpptools process has 0 CPU usage.

I get the following error(s) in the cpptools output:

[Error - 2:17:15 PM] The language server crashed. Restarting...
[Error - 2:17:15 PM] Sending document notification textDocument/didOpen failed
  Message: Client is not running
  Code: -32096 

Steps to reproduce:
1. Open or create a C file
2. Write some code (note failure to colorize and hover functionality not working)
3. Wait some time (Somewhere around 2-5 minutes)
4. See error(s)

Expected behavior:
Variables or other pieces of C-language code colorizing. Hovering over such pieces of code giving information like definitions. Extension commands running when executed.

### Configuration and Logs

```shell
I am not using any workspace-specific configuration as this issue occurs even in a new folder with a single test file.

////////////////////////////////////////////////////////
Log Diagnostics:

-------- Diagnostics - 3/14/2024, 2:23:50 PM
Version: 1.19.8
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "c:/vscode test/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "c:/vscode test/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.19.8.0
No active translation units.

////////////////////////////////////////////////////////
Language server logging:

loggingLevel: Debug
LSP: (received) cpptools/initialize (id: 1)
LSP: (invoked) cpptools/initialize (id: 1)
cpptools version (TypeScript): 1.19.8
cpptools version (native): 1.19.8.0
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
LSP: Sending response (id: 1)
LSP: (received) cpptools/queryCompilerDefaults (id: 2)
LSP: (invoked) cpptools/queryCompilerDefaults (id: 2)
LSP: (received) cpptools/initialize (id: 1)
LSP: (invoked) cpptools/initialize (id: 1)
cpptools version (TypeScript): 1.19.8
cpptools version (native): 1.19.8.0
Autocomplete is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Hover is enabled.
IntelliSense Engine = default.
LSP: Sending response (id: 1)
LSP: (received) cpptools/queryCompilerDefaults (id: 2)
LSP: (invoked) cpptools/queryCompilerDefaults (id: 2)
LSP: (received - deferred) cpptools/getDocumentSymbols: file:///c%3A/vscode%20test/test.c (id: 3)
LSP: (received - deferred) cpptools/getCodeActions: file:///c%3A/vscode%20test/test.c (id: 4)
LSP: (received - deferred) cpptools/getDocumentSymbols: file:///c%3A/vscode%20test/test.c (id: 5)
LSP: (received - deferred) cpptools/getFoldingRanges: file:///c%3A/vscode%20test/test.c (id: 6)
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeActiveEditor: file:///c%3A/vscode%20test/test.c
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeActiveEditor: file:///c%3A/vscode%20test/test.c
LSP: (received - deferred) cpptools/getDiagnostics (id: 7)
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeActiveEditor: file:///c%3A/vscode%20test/test.c
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: (received - deferred) cpptools/didChangeVisibleTextEditors
LSP: Sending response (id: 2)
LSP: (received) cpptools/didChangeCppProperties (id: 8)
LSP: (invoked) cpptools/didChangeCppProperties (id: 8)
enabling full-text triggers
Code browsing service initialized
Unable to configure for compiler cl.exe.
Unable to configure for compiler cl.exe.
  Folder: C:/VSCODE TEST/ will be indexed
LSP: (queued) cpptools/getDocumentSymbols: file:///c%3A/vscode%20test/test.c (id: 3)
LSP: (queued) cpptools/getCodeActions: file:///c%3A/vscode%20test/test.c (id: 4)
LSP: (queued) cpptools/getDocumentSymbols: file:///c%3A/vscode%20test/test.c (id: 5)
LSP: (queued) cpptools/getFoldingRanges: file:///c%3A/vscode%20test/test.c (id: 6)
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeActiveEditor: file:///c%3A/vscode%20test/test.c
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeActiveEditor: file:///c%3A/vscode%20test/test.c
LSP: (queued) cpptools/getDiagnostics (id: 7)
LSP: (invoked) cpptools/getDocumentSymbols: file:///c%3A/vscode%20test/test.c (id: 3)
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeActiveEditor: file:///c%3A/vscode%20test/test.c
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: (queued) cpptools/didChangeVisibleTextEditors
LSP: Sending response (id: 8)
LSP: (invoked) cpptools/getDocumentSymbols: file:///c%3A/vscode%20test/test.c (id: 5)
LSP: (invoked) cpptools/getCodeActions: file:///c%3A/vscode%20test/test.c (id: 4)
Discovering files...
LSP: Sending response (id: 4)
LSP: (invoked) cpptools/getFoldingRanges: file:///c%3A/vscode%20test/test.c (id: 6)
LSP: (invoked) cpptools/getDiagnostics (id: 7)
LSP: Sending response (id: 7)
LSP: (invoked) cpptools/didChangeActiveEditor: file:///c%3A/vscode%20test/test.c
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: Sending response (id: 6)
  Processing folder (recursive): C:/VSCODE TEST/
  Discovering files: 1 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
LSP: Sending response (id: 3)
LSP: Sending response (id: 5)
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
LSP: (received) cpptools/didChangeActiveEditor: file:///c%3A/vscode%20test/test.c
LSP: (invoked) cpptools/didChangeActiveEditor: file:///c%3A/vscode%20test/test.c
LSP: (received) cpptools/didChangeVisibleTextEditors
LSP: (invoked) cpptools/didChangeVisibleTextEditors
```

### Other Extensions

Aside from the C/C++ extension, I am using the Github Copilot extension and its associated Github Copilot Chat extension. Issue persists even with all other extensions disabled.

### Additional context

![image](https://github.com/microsoft/vscode-cpptools/assets/28608699/0885af31-247d-4971-a57d-613e8d835aac)
![image](https://github.com/microsoft/vscode-cpptools/assets/28608699/fc26357b-04f8-429c-8d7f-cf2d87fc8921)
![image](https://github.com/microsoft/vscode-cpptools/assets/28608699/3fc8b0de-78bc-405c-aca4-8375da7b60eb)

Code Sample:
#include <stdio.h>

int main() {
    int num1, num2, sum;
    
    printf("Enter two numbers: ");
    scanf("%d %d", &num1, &num2);
    
    sum = num1 + num2;
    
    printf("The sum of %d and %d is %d\n", num1, num2, sum);
    
    return 0;
}

**Comment by KokopelliP** [comment]
Sorry, forgot to mention that the issue does still happen with all other extensions disabled.

**Comment by sean-mcmanus** [comment]
@KokopelliP Are you using WSL1 or WSL2? It looks like you're using WSL1 and Windows paths, which I don't think we support.

**Comment by KokopelliP** [comment]
> @KokopelliP Are you using WSL1 or WSL2? It looks like you're using WSL1 and Windows paths, which I don't think we support.

I don't know if it is relevant because I am writing in VS Code in Windows 10, not from within WSL. If it is relevant, then I am using WSL2 as far as I know. That is what I installed, and what is shown in the WSL terminal. I have never set up VS Code to use, or run in, WSL.

**Comment by sean-mcmanus** [comment]
@KokopelliP Okay, if it's a just a Windows repro that makes more sense. Your initial repro details mentioned WSL/Ubuntu, but your logging indicated Windows.

So far I haven't reproed the issue.

Does it crash immediately or are you able to attach a debugger to the cpptools.exe process to get a crash call stack? https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

**Comment by sean-mcmanus** [comment]
@KokopelliP What compiler do you have installed? The logging "Unable to configure for compiler cl.exe." seems suspicious. Does setting a compilerPath fix the issue?

**Comment by KokopelliP** [comment]
Apologies, I am not very experienced with C and VS Code. I have a very minimal setup that has allowed me to just write code in VS Code and then build from within WSL, I am unsure if I have ever set up a compiler. I don't remember doing so. I can look into setting that up.

The extension initializes for a while (about 5 minutes or so) and then pops the error. Can I run the debugger without any additional setup or do I need to fix that compiler issue before doing so? Thank you for your patience.

**Comment by sean-mcmanus** [comment]
@KokopelliP If you are building in WSL (ideally version 2), you should use the WSL extension and install the C/C++ extension in WSL. See https://code.visualstudio.com/docs/cpp/config-wsl .

Do attach a debugger you need to set your launch.json correctly, as in 

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "symbolSearchPath": "https://msdl.microsoft.com/download/symbols",
            "logging": {
                "engineLogging": true,
                "trace": true
            },
        }
    ]
}
```

If you're on Windows, with no compiler installed, then our extension won't be able to resolve the `#include <stdio.h>` in your code.

**Comment by KokopelliP** [comment]
When I run the debugger attached to cpptools.exe, it shows threads in the call stack while running. Once the errors pop up in VS Code, the threads all exit and cpptools.exe exits with code 0, which leaves the call stack box empty. I am going to look into setting up the WSL extension like you suggested and report back.

**Comment by KokopelliP** [comment]
Running VS Code with the C/C++ extension using WSL has solved the issue. I will just run through WSL from now on. Thank you for your help!

![image](https://github.com/microsoft/vscode-cpptools/assets/28608699/7f52035b-8b59-4da3-b317-4b450e653cbe)
![image](https://github.com/microsoft/vscode-cpptools/assets/28608699/0406ed3a-eeca-48fe-8093-e7e1c4b1d59a)
