### ISSUE TITLE
vscode terminal cursor  position of vscode is inaccurate

### ISSUE THREAD

**Issue by chall1123** [microsoft/vscode-cpptools#12108]
### Feature Request

in vscode terminal,   I keep holding down the left button and moving the cursor will not be accurate，May I ask how to solve this problem，
vscode version：1.81.1

**Comment by bobbrow** [comment]
Hi @likui1123, can you open an issue for the VS Code editor to investigate?  https://github.com/microsoft/vscode/issues/new/choose

Our extension does not own the terminal.
