### ISSUE TITLE
plugin fuzzy search function bug

### ISSUE THREAD

**Issue by chall1123** [microsoft/vscode-cpptools#12109]
### Feature Request

i input globalrea,i can get globalbwatchrecread, but i input globalread i cannot get globalbwatchrecread

**Comment by bobbrow** [comment]
@likui1123, this is a known issue. There is currently a 16 character limit across which the fuzzy search operates. We're considering making this configurable.  Can you add your comment here where we are tracking the issue? https://github.com/microsoft/vscode-cpptools/issues/11557

Thank you!

**Comment by likui1123** [comment]
thanks very much ,so  i want to delete my issue,thanks

**Comment by likui1123** [comment]
> @likui1123, this is a known issue. There is currently a 16 character limit across which the fuzzy search operates. We're considering making this configurable. Can you add your comment here where we are tracking the issue? #11557
> 
> Thank you!
thanks very much ,so i want to delete my issue,thanks

**Comment by sean-mcmanus** [comment]
@likui1123 Your example has been fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.20.0 , i.e. the fuzzy character limit has increased to 28.
