### ISSUE TITLE
C/C++ Intellisense slow and unresponsive (v1.19.9)

### ISSUE THREAD

**Issue by AlexDai54202** [microsoft/vscode-cpptools#12126]
### Environment

- OS and Version:  Windows 11 Home, version 23H2
- VS Code Version: 
```
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```
- C/C++ Extension Version:  v1.19.9
- If using SSH remote, specify OS of remote machine:  `Linux d893f64b1111 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 GNU/Linux`

### Bug Summary and Steps to Reproduce

Bug Summary:
Intellisense takes multiple seconds to autofill or hint. 

https://github.com/microsoft/vscode-cpptools/assets/84922496/1ae9ccc3-e68b-4d96-ae94-36dfff74eaa0

Steps to reproduce
1. Open .c file in VScode.
2. Attempt to reference a variable
3. Variable takes multiple seconds to autocomplete/hint

Expected behavior:
1. Open .c file in VScode
2. Attempt to reference a variable
3. Variable hinted during typing with minimal delay

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

### Other Extensions

![image](https://github.com/microsoft/vscode-cpptools/assets/84922496/ef093046-bdaf-4a3d-96a7-489e75623ccd)

### Additional context

Apologies in advance if this issue is written to be extremely informal; I'm an undergraduate student trying their best to complete their programming assignment. I can't seem to find a fix to this issue anywhere and this is genuinely driving me insane.

I don't think the issue is that there are too many active variables either; making a new .c file and writing something like `int aintegervariable = 0;` takes multiple seconds for intellisense to recognize and autofill and demonstrates the same issue.

https://github.com/microsoft/vscode-cpptools/assets/84922496/46f2f98d-e910-4e49-a6e6-0fa2c49ccb90

Additional context: 
This issue has persisted for almost the entire time I've used C/C++, so I would likely have the same issue even with the last couple dozen versions of this extension.
My device has 16 GB of RAM, and the CPU utilization is <40% half the time, and my SSD has around 500 GB of unused storage space, so I don't think the issue is in the hardware.

Once again, apologies for wasting your time if the issue isn't well written or through enough to debug.

**Comment by Colengms** [comment]
Hi @AlexDai54202 .  Would you be able to reproduce your captures with the `Output` panel open, set to the `C/C++` output channel, and with the `"C_Cpp.loggingLevel": "Debug"` setting set?  That should show us what's going on internally in the extension, simultaneously with your actions.  There are various intentional delays (such as `C_Cpp.intelliSenseUpdateDelay`, which delays squiggle passes until you've stopped typing for 1s), and it's possible VS Code's requests for these features may not be routed to the extension immediately, or as quickly as you might expect.  There are also various other settings or conditions that might be contributing, which may be apparent based on that log output.

**Comment by AlexDai54202** [comment]
Gotcha! This capture is after I set the logging level to Debug.

Apologies for the video not being embedded; the file is over 10 MB and I assume clarity is important here.
https://www.youtube.com/watch?v=bMeNMm5CAQQ

Additionally, the intellisense update delay does appear to be 1000ms.
I'm unfortunately not familiar with types of delay I should be looking for, but a quick search yielded:
![image](https://github.com/microsoft/vscode-cpptools/assets/84922496/c6dd7e01-7c6e-4747-b9c8-8003d2ab6deb)

**Comment by Colengms** [comment]
Hi @AlexDai54202 .  Have you set any of the following settings to values other than their defaults? `C_Cpp.intelliSenseMemoryLimit`, `C_Cpp.maxCachedProcesses`, `C_Cpp.maxMemory`, `C_Cpp.intelliSense.maxCachedProcesses`, `C_Cpp.intelliSense.maxMemory`

Those settings influence when we recycle IntelliSense translation units.  Hypothetically, I might expect a problem like this to occur if those limits are set too low, causing IntelliSense translation units to be recycled almost immediately.

Otherwise, we're looking for some clue as to why your IntelliSense processes are only sticking around for a very short time.  They appear to be getting shut down gracefully, before being immediately started again. Does this happen for you with multiple different projects, or on a different machine?

**Comment by AlexDai54202** [comment]
I don't believe I have set any of those as anything other than default.
![image](https://github.com/microsoft/vscode-cpptools/assets/84922496/77da45de-5546-4304-93e9-0d62aded9549)
![image](https://github.com/microsoft/vscode-cpptools/assets/84922496/51d2f997-432e-474f-9315-3521771ae613)
![image](https://github.com/microsoft/vscode-cpptools/assets/84922496/0175cf61-3a67-4dca-89d7-3166dca613d0)
![image](https://github.com/microsoft/vscode-cpptools/assets/84922496/d1566810-6cd3-4ffa-989c-6c577338d54d)
![image](https://github.com/microsoft/vscode-cpptools/assets/84922496/a80108c7-9ef8-47c9-8180-0d83f94ad5e5)

Not sure if this helps, but the only thing I've changed from default would be the setting "C_Cpp.default.cStandard": "gnu17".

This behavior doesn't seem to happen outside of the WSL/Docker server.

**Comment by bobbrow** [comment]
Can you share how you configured your WSL/Docker server?  I'm not sure if anyone on our team has worked with that before or not.

**Comment by AlexDai54202** [comment]
Unfortunately, the docker image is not configured by me, rather by the course staff, so I'm not of much help there.
With that said, my WSL configuration is as follows:
```
[wsl2]
memory=2GB
```
(Located at C:\Users\myusername\.wslconfig)

And my container configuration for vscode is
```
{
	"workspaceFolder": "/home/student",
	"extensions": [
		"ms-vscode.cmake-tools",
		"ms-vscode.cpptools",
		"ms-vscode.cpptools-extension-pack",
		"ms-vscode.cpptools-themes",
		"ms-vscode.makefile-tools",
		"twxs.cmake"
	],
	"settings": {
		"C_Cpp.default.cStandard": "gnu17"
	}
}
```
Which I got from the command palate (Open attached container configuration file)

**Comment by sean-mcmanus** [comment]
@AlexDai54202 Yeah, 2 GB of memory is likely going to be insufficient (4-8 GB is recommended as a minimum). You could use some program like top to see the memory usage of cpptools and cpptools-srv and your free memory? It looks like we'll tear down cpptools-srv if the free memory drops below 256 MB. Is your repro with just 1 .cpp file open or are you switching between multiple source files?

**Comment by bobbrow** [comment]
@sean-mcmanus there's only one file open and we're tearing down IntelliSense while it's still in focus.

**Comment by sean-mcmanus** [comment]
@bobbrow I'm seeing the memory usage by the OS, VS Code, and cpptools be > 2 GB. I think it can be fixed by ensuring 2 clients are kept active (and adding logging for when the IntelliSense processes are shutdown due to resource limits).

**Comment by sean-mcmanus** [comment]
@AlexDai54202 Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.20.0, although let us know if you're still seeing other issues in your scenario with the 2 GB docker container.

**Comment by AlexDai54202** [comment]
Horribly sorry for not keeping up - this project was absolutely killing me.
Configuring the WSL2 to be 2 GBs fixed the issue. I cannot express how much gratitude I have for all of you for walking me through this. Once again, thank you all so much!
