### ISSUE TITLE
IntelliSense doesn't recognize uint32_t type only.

### ISSUE THREAD

**Issue by z14git** [microsoft/vscode-cpptools#1212]
+ Operating System and version: windows 10 x64 1709 / windows 7 x32

+ VS Code version: 1.17.2
+ C/C++ extension version: 0.14.0
+ demo: <https://github.com/z14git/stm32demo.git>
+ "C_Cpp.intelliSenseEngine": "Default"

1. As the gif shows, it seems that intellisense doesn't recognize uint32_t type. However, other types like uint8_t and int32_t are just fine.![bug1](https://user-images.githubusercontent.com/31793423/32480258-b46926fa-c3c8-11e7-8b6f-80ece02336bf.gif)

1. Go to Definition, Peek Definiton, Go to Declaration, and Peek Declaration still work on uin32_t.![bug2](https://user-images.githubusercontent.com/31793423/32480271-c9e39290-c3c8-11e7-8d95-4f9d690ba5f9.gif)

1. Sometimes there is a message "Unable to begin adding code symbols for file. error = -2147467259" showed on the OUTPUT window. I don't known if this is related to the problem.

**Comment by sean-mcmanus** [comment]
It's not a bug -- in core_cm3.h, it needs to have a compiler define set, such as "__CC_ARM" or it hits a "#error Unknown compiler". Adding it to the defines fixes the issue. It would be nice if we showed all the errors for the current translation unit in compiler order, which would make this particular omission easier to detect. The current implementation requires that you open all the include files until you discover the first error. "Unable to begin adding code symbols..." is a different issue -- do you know how to repro that? We should make that error message more detailed.

**Comment by pdemil** [comment]
Described here: http://shadetail.com/blog/using-visual-studio-code-for-arm-development-defines/
