### ISSUE TITLE
function call

### ISSUE THREAD

**Issue by chall1123** [microsoft/vscode-cpptools#12128]
### Feature Request

![image](https://github.com/microsoft/vscode-cpptools/assets/37236882/0d710bf9-ebfa-4ba1-a708-810039cff036)
Does this extension have a function call viewing function similar to sourceinsight? This viewing is very intuitive

**Comment by sean-mcmanus** [comment]
@likui1123 Yes, use the "Show Call Hierarchy" command from the command palette or right-click menu.

**Comment by heartacker** [comment]
GUI Graph
