### ISSUE TITLE
When a config provider can't provide a configuration, the base configuration should be used (not the browse configuration)

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#12144]
We have a long-standing bug where, when a config provider can't provide a configuration for a file, the browse configuration is used to configure that file instead of the intended behavior of falling back to the base configuration.  Opening this issue to track restoring that behavior to using the base configuration.

**Comment by hamammmm** [comment]
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\USERWD\Downloads\CMakeFiles\Untitled-1.cpp).C/C++(1696)
cannot open source file "iostream". Please run the 'Select IntelliSense Configuration...' command to locate your system headers.C/C++(1696) [I have this problem]

**Comment by Colengms** [comment]
Hi @hamammmm . I don't believe that error message would be related to this issue. Could you open a new issue, and provide the information requested in the new issue template? Given the error message, it would seem your configuration does not have a compiler associated with it, or an attempt to query your selected compiler has failed.

**Comment by hamammmm** [comment]
You may only use the C/C++ Extension for Visual Studio Code
with Visual Studio Code, Visual Studio or Visual Studio for Mac
software to help you develop and test your applications.(This is the
message I received).

في الأربعاء، ١٠ أبريل ٢٠٢٤، ٤:٢١ ص Sean McManus ***@***.***>
كتب:
