### ISSUE TITLE
Code formating: flow control space

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode-cpptools#12146]
Type: <b>Bug</b>

I have configured:
![image](https://github.com/microsoft/vscode-cpptools/assets/4163396/d72bf8e7-7eb1-4ffa-9802-3f799cda9270)

but there is still space inserted after 'for' 
![image](https://github.com/microsoft/vscode-cpptools/assets/4163396/d94588fd-65c3-426b-9d71-a4a15d2f9be3)

when it's originally 
![image](https://github.com/microsoft/vscode-cpptools/assets/4163396/5647bbd5-378b-4fae-90b4-a42644d59c5a)

and every other flow control: if, while, do

also there should be a multi-choice option like
![image](https://github.com/microsoft/vscode-cpptools/assets/4163396/1a3d2f51-025b-4ed5-9b4b-5c70e000ccb0)

Extension version: 1.17.5
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @mrx23dot .  I'm unable to reproduce this issue with the following settings:

```
    "C_Cpp.formatting": "vcFormat",
    "C_Cpp.vcFormat.space.afterKeywordsInControlFlowStatements": false,
```

Note that `vcFormat` is not the default formatting engine used by the C/C++ Extension.  `clang-format` is used by default. You would need to set `"C_Cpp.formatting": "vcFormat"` in order for the `vcFormat`-related settings to apply.
