### ISSUE TITLE
Create an IntelliSense client when a completion (and other) IntelliSense requests occur

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#12143]
Hi,

We have  found one solution which works after opening the CPP file in background using vscode API "vscode.workspace.openTextDocument" and it does trigger "textDocument/didOpen" on the file and then calling the code completion API. The code completion works only after first some edit in the cpp files.  for clangd extension it is working without doing any edit of cpp file in the IDE with the same approach. https://github.com/clangd/vscode-clangd/issues/589 . Could you please see if we have some option to achieve the same in C/C++ extension?

Thanks,
Rajesh Kumar.

_Originally posted by @Rajsmit in https://github.com/microsoft/vscode-cpptools/discussions/8404#discussioncomment-8914832_

**Comment by sean-mcmanus** [comment]
signatureHelp and documentHighlight should also be fixed.

**Comment by sean-mcmanus** [comment]
@Rajsmit Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.20.1

**Comment by Rajsmit** [comment]
Hi @sean-mcmanus , Tested with v1.20.1 (pre-release) now the code completion is working with first time itself. Thanks for quick resolution.
