### ISSUE TITLE
Allow sharing of task environments

### ISSUE THREAD

**Issue by zjturner** [microsoft/vscode-cpptools#1214]
Various tasks need environment variable s set up to work properly.  Currently a task can use the "tasks/options/env" property to define additional variables per task.  

However, you may have many different tasks, and all of them need the same environment.  It is cumbersome to duplicate this in every single task.  It would be nice if there was a syntax to inherit this somehow.

**Comment by sean-mcmanus** [comment]
This sounds like a VS Code issue. Can you report it at https://github.com/Microsoft/vscode/issues ?

**Comment by zjturner** [comment]
You are right, silly me :)
