### ISSUE TITLE
errorSquiggles is Incorrect

### ISSUE THREAD

**Issue by chall1123** [microsoft/vscode-cpptools#12155]
### Environment

- OS and version:
- VS Code:1.81.1
- C/C++ extension:1.19.8
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Bug Summary:
extension hint error，can not find SYS_ENOMEM define,but i can click SYS_ENOMEM go its define and i can compile
 
if i include  SYS_ENOMEM header file in current file,this error will disappear

### Debugger Configurations

```shell
cpp.error.Squiggles:"enbaled"
cpp.experimentalFeatures:"enbaled"
```

### Debugger Logs

```shell
null
```

**Comment by sean-mcmanus** [comment]
What is the exact error message you are seeing?

IntelliSense isn't getting compiled with the SYS_ENOMEM defined. If you run C/C++: Log Diagnostics the "Includes" section will show what IntelliSense is using.

**Comment by likui1123** [comment]
> What is the exact error message you are seeing?
> 
> IntelliSense isn't getting compiled with the SYS_ENOMEM defined. If you run C/C++: Log Diagnostics the "Includes" section will show what IntelliSense is using.

![image](https://github.com/microsoft/vscode-cpptools/assets/37236882/8ea0915a-9c2e-45f2-bed4-f9dbebb582d5)

**Comment by sean-mcmanus** [comment]
@chall1123 I don't understand. What is the error? Is it "identifier SYS_ENOMEM is undefined"? If you open the header file with SYS_ENOMEM does it re-use the same TU or does it create a new one? The TU that isn't finding SYS_ENOMEM may be picking up other include files causing the definition to not be included.
