### ISSUE TITLE
Can delete text, but cannot type in text - Resolved only by reinstallation

### ISSUE THREAD

**Issue by michael-mayes** [microsoft/vscode-cpptools#1215]
* Operating System and version

Windows_NT ia32 6.1.7601

    * VS Code version and if you are using the Insiders build

Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)

    * C/C++ extension version

cpptools|ms-|0.14.0

    * Other extensions you installed

include-autocomplete|ajs|0.0.4
ada|Ale|0.0.1
spellright|ban|2.0.2
unique-lines|bib|1.0.0
bracket-pair-colorizer|Coe|0.10.10
whitespace-plus|dav|0.0.5
tortoise-svn|fan|0.1.1
macros|ged|1.2.1
docomment|k--|0.0.17
vscode-clang|mit|0.2.2
cpptools|ms-|0.14.0
vscode-code-outline|pat|0.0.12
selectline-statusbar|tom|0.0.2
sort-lines|Tyr|1.3.0
mib|Ver|0.0.4
expand-selection-to-scope|vit|0.2.0
vscode-todo-highlight|way|0.5.11

    * if the issue persists after disabling them

Only disabling the C/C++ extension makes a difference to the issue

    * step-by-step instructions to reproduce the issue

Opened code file that previously worked fine against C/C++ extension

Deleting text with backspace key

Tried to type in replacement text and none seen

    * A small code sample, zipped up project, or open source repo we can use to verify the bug

N/A

    * Relevant settings from your settings.json, c_cpp_properties.json, and/or launch.json files

N/A

    * Any log messages present in the Output window (use "C_Cpp.loggingLevel": "Information" in settings.json)

No messages were present

**Comment by michael-mayes** [comment]
Potentially related to https://github.com/Microsoft/vscode/issues/37736 and https://github.com/Microsoft/vscode/issues/37775

**Comment by michael-mayes** [comment]
Looking in Process Explorer, I saw that the Intellisense process was not running

Uninstalling the extension and reinstalling it has brought the Intellisense process back and restored the ability to type

**Comment by michael-mayes** [comment]
This suggests that the C/C++ extension was intercepting the typing and trying to pass it to the  Intellisense process, but the absence of the process was preventing it appearing on screen

**Comment by michael-mayes** [comment]
Not sure what can be done to replicate, but I am not the only one to experience this it would seem, so there may be an issue here with the  Intellisense process not being started alongside VS Code

**Comment by bobbrow** [comment]
This is strange.  Extensions are not capable of intercepting keystrokes.  VS Code is responsible for displaying the characters that you type.  VS Code then sends our extension a message that tells us what changed in the document.  I haven't seen what you're describing, so I'm not sure what's causing it.  The callstack in the issue you linked doesn't look like ours.  It seems like the issue reporters have quite a few extensions running at once.  Perhaps this contributes to the problem.

I'm curious to see if our extension is processing any messages at all when you are in this state.  You can enable some of our debug logging by adding this setting `"C_Cpp.loggingLevel": "6"`.  Ignore the squiggles in the settings.json file, this is an intentionally undocumented option.  After changing that, try to type some characters in your C++ file and see if `textDocument/didChange` messages are appearing in the Output panel for the "C/C++" channel.  You can paste a sample of the output in this issue so we can see if anything is amiss.

**Comment by michael-mayes** [comment]
Seems definitely seen independently as under https://github.com/Microsoft/vscode/issues/37775

Seeing as I have resolved (for now) by reinstalling extension, I have asked if they can try out your suggestions for investigation

**Comment by michael-mayes** [comment]
It looked in my case that the Intellisense process was not running. This was cured only by the re-installation of the  #C/C++ extension (*not* the re-installation of VS Code for clarity)

Is it possible that the inability for the C/C++ extension to detect the Intellisense process as running caused it to stall its completion of startup, so holding off the Emmet extension and preventing typing?

**Comment by bobbrow** [comment]
Extensions are run in a separate process from the VS Code editor, so even if an extension is misbehaving, there shouldn't be a way for it to interfere with the editor's ability to service keystrokes.  This issue is truly disturbing.  If you have a way to reproduce the issue, we would be very interested to know so that we can help the VS Code team get it resolved.

**Comment by michael-mayes** [comment]
The suggestion from @alexandrudima here https://github.com/Microsoft/vscode/issues/37736#issuecomment-343942581 seems to be that a delay in the built-in emmet extension getting activated can prevent typing appearing

Now that was apparently a bug that was rectified in VSCode 1.18, but it does seem to suggest the issue I had with C/C++ extension was holding the built-in emmet extension off from activation on the main extension thread with knock on impact (though a bug) of preventing typing

**Comment by michael-mayes** [comment]
So the knock on impact may be resolved by VSCode 1.18, but I think this issue needs to stay open for now, or be replaced with a more specific issue, concerning how the C/C++ extension can hold off other extensions in this case

**Comment by sean-mcmanus** [comment]
This issue seems resolved now.
