### ISSUE TITLE
C compiler fail to recognize specific flags

### ISSUE THREAD

**Issue by pugibela** [microsoft/vscode-cpptools#12157]
Type: <b>Bug</b>

Using VS code rev 1.87.2 on ubuntu 6.5.0-25-generic
Code fail to compile the program with bellow Error: Starting build... /usr/bin/gcc -fdiagnostics-color=always -g program.c -o program -lX11 'imlib2-config --cflags' 
/usr/bin/ld: cannot find imlib2-config --cflags: No such file or directory collect2: error: ld returned 1 exit status

This is in contrust to a succsfull comilation on a terminal command line as in:
$ gcc -g program.c -o program -lX11 `imlib2-config --cflags`

My tasks.json args list :
"args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}",
                "-lX11",
                "imlib2-config --cflags"
]

Extension version: 1.19.9
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 6.5.0-25-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics (12 x 3066)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|27.29GB (22.36GB free)|
|Process Argv|--unity-launch --crash-reporter-id 0ffafefc-b3d9-40e2-887a-9c1398ddd613|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sean-mcmanus** [comment]
Can you try

```json
"imlib2-config",
"--cflags"
```

in tasks.json?

**Comment by pugibela** [comment]
that is what it looks like now and it works even added another flag...
**"-lX11","`imlib2-config","--cflags`","`imlib2-config","--libs`"**

THANKS
I wish to documentation about these things was a little more detailed and include some examples for these type of uses cases
