### ISSUE TITLE
Add a "default" value to C_Cpp.experimentalFeatures (i.e. make the current default of "disabled" actually disable it)

### ISSUE THREAD

**Issue by AlexandraKemperMS** [microsoft/vscode-cpptools#12163]
### Feature Request

At this point, we have overloaded the "Experimental Features" setting and need a separate setting for A/B experimentation. The experimental features setting was originally created to roll out beta features to users. 
![image](https://github.com/microsoft/vscode-cpptools/assets/67650598/86c21088-f7d1-4c21-b861-93a4f6ce2f56)

With the A/B testing, we need a new setting. This setting should have three options: 
* Default: The A/B service determines whether the user is in the treatment or control group for an experiment. 
     * Description: You may get included in proposed enhancements and/or features.
* Enabled: They are hard coded into the treatment experience in code. This lets any user get access to the treatment experience, no matter what group they are assigned to by the ExP service. 
* Disabled: They are, in code, opting out of any experiments or the potential of being in an experiment. 

Since we usually do not have multiple A/B experiments running at once, we do not need multiple settings to opt in/out (like Python has). We can wordsmith what the descriptions would say with the UI/UX team.

**Comment by sean-mcmanus** [comment]
I'm not understanding why we need a new setting and can't just change the existing setting's setting from "disabled" to "default", i.e. I think we should do that instead. The meaning of the existing experimentalFeatures settings seems valid still and not really in conflict with the A/B experiment.

**Comment by AlexandraKemperMS** [comment]
When I talked to Bob about this he had mentioned that we still want to keep the original setting since we might have "beta" features that we want to release as an experimental feature. These are separate from A/B experiments. You can see other extensions do this as well: 
![image](https://github.com/microsoft/vscode-cpptools/assets/67650598/70fca366-a516-4bed-87d0-1f450628fe48)

**Comment by sean-mcmanus** [comment]
@AlexandraKemperMS @bobbrow I'm still not understanding. We can still have beta non-A/B experimental features with the one setting still.
* Disable: No experimental
* Enable: All experimental
* Default: beta experimental features are disabled, A/B experimental features are subject to the "rollout" randomness
I don't see a good reason for a user to want to differentiate between the two either.
