### ISSUE TITLE
When generating Doxygen comments, can choose to use the @ or \ characters.

### ISSUE THREAD

**Issue by ProudRabbit** [microsoft/vscode-cpptools#12164]
### Feature Request

Due to the company's QAC testing rules, the `@` symbol cannot appear in code comments. But when I use `/**` to generate comments, the default is to use the @ character, and there are no options to modify it in the settings.

I hope to add an option to set whether to use the `@` or `\` characters when generating comments.

Now
![image](https://github.com/microsoft/vscode-cpptools/assets/56437960/0fedb827-1e8b-4517-bbcc-6251e32180f2)

Feature
![image](https://github.com/microsoft/vscode-cpptools/assets/56437960/702af555-303d-41b5-9ae8-0267cf9bdfef)

**Comment by sean-mcmanus** [comment]
Until we add a setting to enable the `\`, you could set `"C_Cpp.doxygen.generateOnType": false,` to disable the `@` generation.

**Comment by ProudRabbit** [comment]
Thanks. 👍
