### ISSUE TITLE
Option to disable hover tooltips

### ISSUE THREAD

**Issue by palapapa** [microsoft/vscode-cpptools#12160]
### Feature Request

If you use clangd with this extension, whenever you hover over a symbol, both the tooltips from this extension and clangd will show up at the same time. Currently, there's no way to disable this other than using `"C_Cpp.intelliSenseEngine": "disabled"`, but that also disables the ability to debug. It would be nice to have an option that can disable just this feature.

**Comment by sean-mcmanus** [comment]
@palapapa Oh, we already have a setting C_Cpp.hover -- set it to "disabled" and do a Reload Window.
