### ISSUE TITLE
intellisense hover of const type * const var produces incorrect information

### ISSUE THREAD

**Issue by draeger-charles-wilson** [microsoft/vscode-cpptools#1216]
given:

platform Windows
VS Code 1.17.2
C/C++ 0.14.0

```
struct foo { int a; };

const struct foo * const p_foo[10];
```

hovering foo will display:

```
const const struct foo * p_foo[10]
```

**Comment by bobbrow** [comment]
Just checking, you're using C, not C++?  ("struct" doesn't show up in the tooltip for me when using C++).  I don't see what you're seeing.  Hovering "foo" gets me `struct foo`.  Hovering the variable gets me closer to what you're reporting, but it still looks ok to me.

![image](https://user-images.githubusercontent.com/12818240/32564974-a5f4d1bc-c46a-11e7-88bb-5c793debce5d.png)

I'm not seeing any difference in the result between `msvc-x64` or `clang-x64` intelliSenseMode on Windows, but can you let us know which one you're using?

**Comment by draeger-charles-wilson** [comment]
The code in question is C.

I'm bootstrapping an ARM RVCT toolchain. IntelliSenseMode is clang-x64.

**Comment by draeger-charles-wilson** [comment]
I'm not able to generate it in isolation. Here's a screenshot of in place.
![image](https://user-images.githubusercontent.com/33490168/32574960-aa7adac0-c4a0-11e7-983a-e761eccb461b.png)

**Comment by sean-mcmanus** [comment]
I'm seeing the same thing Bob is (i.e. I don't see any error).

**Comment by draeger-charles-wilson** [comment]
I've extracted the entire chain to a separate file and the problem does not manifest there.

I will report back if I hit a second instance of this.
