### ISSUE TITLE
cpptools DDOS'ing our file server

### ISSUE THREAD

**Issue by clhedrick** [microsoft/vscode-cpptools#12179]
### Environment

- OS and Version:  Ubuntu 22.04
- VS Code Version: unknown. Users install it themselves
- C/C++ Extension Version:  unknown Users install it themselves
- If using SSH remote, specify OS of remote machine:  unknown
-

### Bug Summary and Steps to Reproduce

Bug Summary:

cpptools is continuously doing the following sort of thing:

[pid 3831115] readlink("/common", 0x7f8debffccb0, 1023) = -1 EINVAL (Invalid argument)
[pid 3831115] readlink("/common/home", 0x7f8debffccb0, 1023) = -1 EINVAL (Invalid argument)
[pid 3831115] readlink("/common/home/xxxxx", 0x7f8debffccb0, 1023) = -1 EINVAL (Invalid argument)
[pid 3831115] readlink("/common/home/xxxxx/Downloads", 0x7f8debffccb0, 1023) = -1 EINVAL (Invalid argument)
[pid 3831115] readlink("/common/home/xxxxx/Downloads/operating", 0x7f8debffccb0, 1023) = -1 EINVAL (Invalid argument)
[pid 3831115] readlink("/common/home/xxxxx/Downloads/operating/project3", 0x7f8debffccb0, 1023) = -1 EINVAL (Invalid argument)
[pid 3831115] readlink("/common/home/xxxxx/Downloads/operating/project3/test.c", 0x7f8debffccb0, 1023) = -1 EINVAL (Invalid argument)

We don't know how it is set up. It seems that users are doing it themselves as a remote server. Unfortunately it seems to be a large class. This generates large large numbers of transactions to the file server hosting home directories.

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
unknown. set up by users remotely.
```

**Comment by sean-mcmanus** [comment]
@clhedrick What is your request? If users specify a particular directory for workspace folder then cpptools will iterate over the files in those directories to get workspace symbols unless paths are added to C_Cpp.files.exclude.

**Comment by clhedrick** [comment]
How would they do that? I'm not a vscode user. This is students either on their own or under instructions by a faculty member. I'll need good enough instructions to give to students.

**Comment by sean-mcmanus** [comment]
The users could add some path to C_Cpp.files.exclude in settings.json, e.g.

```json
    "C_Cpp.files.exclude": {
        "**/.vscode": true,
        "**/.vs": true,
        "**/common": true
    }
```

but I don't think the users should be using VS Code with our C/C++ extension to access the remote files. It sounds like it would be better to copy the files locally.
