### ISSUE TITLE
incorrect comment syntax highlight

### ISSUE THREAD

**Issue by tdjastrzebski** [microsoft/vscode-cpptools#12170]
### Environment

- OS and Version:  Windows 11
- VS Code Version: 1.88.0
- C/C++ Extension Version: the latest 1.19.9
- If using SSH remote, specify OS of remote machine: no

### Bug Summary and Steps to Reproduce

Bug Summary:
/* */ comments which do not start the line and end on the next line are parsed/highlighted incorrectly

![image](https://github.com/microsoft/vscode-cpptools/assets/7325277/61e84603-21e1-45f7-ba87-ae86ca34cac6)

### Configuration and Logs

```shell
c_cpp_properties.json 
{
"name": "test",
"intelliSenseMode": "gcc-arm",
"cStandard": "c17",
"cppStandard": "c++17",
"compilerPath": "${env:MBED_GCC_ARM_PATH}/arm-none-eabi-g++"
}
```

**Comment by sean-mcmanus** [comment]
This is being tracked by https://github.com/jeff-hykin/better-cpp-syntax/issues/527 , which is where VS Code itself gets its C++ lexical colorization.
