### ISSUE TITLE
Extension not working at all

### ISSUE THREAD

**Issue by zuhayrl** [microsoft/vscode-cpptools#12173]
I have downloaded the extension to use according to the VS Code C++ installation guide and have followed all the other steps as well. The extension is installed but provides no functionality, the code completion with intellisense doesnt work, the run button doesnt show, the debugger isnt picked up by vs code etc. Please advise

**Comment by sean-mcmanus** [comment]
@zuhayrl What version of VS Code and the C/C++ extension are you using and what is your OS?

**Comment by zuhayrl** [comment]
VS Code version 1.88, C/C++ extension version 1.19.9 on windows 11

**Comment by Colengms** [comment]
Hi @zuhayrl .  We're not tracking any general issue like this, so there would seem to be some information we would need about your system, environment, etc. (details requested in the 'new issue' template), to investigate further.

If you enable the setting `"C_Cpp.loggingLevel": "Debug"`, does that result in a C/C++ output channel (in the OUTPUT panel)?  If so, that log might provide some clues as to what's going on.  You might also consider using the "Snipping Tool" to record a brief video of what you're seeing.

**Comment by sean-mcmanus** [comment]
@zuhayrl Do you have C_Cpp.intelliSenseEngine set to "disabled"?
