### ISSUE TITLE
Trying to use Intellisense causes keyboard to stop working (no messages)

### ISSUE THREAD

**Issue by MarkY-LunarG** [microsoft/vscode-cpptools#1217]
OS: Linux - Fedora Core 26
VS Code Version: 1.17.2
C/C++ Extension Version: 0.14.0
Other enabled extensions:  Clang-Format 1.6.0 (does not appear to affect)

If I try to use intellisense to look up a declaration for a type, it hangs with no logging information and never returns my keyboard controls until I disable the C/C++ Extension.  I've tried outputting information with  "C_Cpp.loggingLevel": "Information" and I see nothing in the output window.

My settings file doesn't have anything specific for the C/C++ extension.

Before recent upgrade to 0.14.0, it used to tell me I needed to update my "include" paths for Intellisense, but I don't even see that anymore. 

I can get my keyboard back by disabling the extension and reloading Code.

**Comment by bobbrow** [comment]
Just checking... Did you set the output channel to `C/C++`?
![image](https://user-images.githubusercontent.com/12818240/32565632-fdaf05b6-c46b-11e7-895e-88b1933a80d3.png)

It's also possible that the extension crashed.  The restart logic never worked correctly before - it would launch a new extension process, but the new process didn't communicate with VS Code. We have a fix for it in 0.14.1 which we will be releasing soon.  Using the "reload window" command is the workaround until the update comes out.

**Comment by MarkY-LunarG** [comment]
No, my output panel only lists: "Search, Tasks, Extensions".  Is there something else required to get that to appear as an option of the output window?

Is there a key that will cause "reload window" to occur, or do I have to manually do it from the extension page?

**Comment by bobbrow** [comment]
Open the command palette: <kbd>CTL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> and type "reload window" to use the command.

**Comment by bobbrow** [comment]
The `C/C++` option won't appear in the Output window until we send our first message to it.  So if you have set the logging level to "Information" and there is no logging, then it sounds like the extension never loaded.  Do you have any `Microsoft.VSCode.CPP.Extension.linux` processes running?

**Comment by MarkY-LunarG** [comment]
I don't see any processes (using ps -elF) that contain the string "vscode" or even "vs" (case-insensitive).  I looked in Code and I didn't see anyway to list processes there, and there are no running tasks.

**Comment by bobbrow** [comment]
VS Code won't activate our extension until you open a C or C++ file in the editor (you might have to give it focus too).  If you reload the window while a C or C++ file is open in the editor, does that start the extension process for you?

**Comment by bobbrow** [comment]
VS Code won't activate our extension until you open a C or C++ file in the editor (you might have to give it focus too).  If you reload the window while a C or C++ file is open in the editor, does that start the extension process for you?

**Comment by MarkY-LunarG** [comment]
I have a C++ file open, and all I see in Gnome System Monitor are
 * 6 plain-vanilla "code" processes
 * A single "code --type=gpu_process --no_sandbox..." process
 * A single "code --unity-launch" process.

Also, I show nothing containing "Microsoft" at all.

Also, I tried to enable the "Bookmarks" extension, and it enables, but when I try to toggle a bookmark it says there are no command for "bookmarks.toggle".  Could something be blocking all extensions on my system?  All this worked fairly recently (say a week or so ago).

**Comment by bobbrow** [comment]
Can you try uninstalling/reinstalling the C/C++ extension, maybe?  I saw one case of a corrupted upgrade here on GitHub last week.

**Comment by sean-mcmanus** [comment]
The VS Code extension model doesn't allow extensions to trap keystrokes, so it sounds like an issue with VS Code itself. Maybe uninstall/reinstalling it might fix it. You can also try using Help->Toggle Developer Console to see if there are any errors occurring.

**Comment by MarkY-LunarG** [comment]
I actually tried that.  I even uninstalled and re-installed code.  Although, the data files (settings.json, etc) still appear untouched from before.  So, if one of the data files is messed up, that wouldn't help.

**Comment by sean-mcmanus** [comment]
Other users have reported that uninstall/reinstalling the extension fixes it: https://github.com/Microsoft/vscode-cpptools/issues/1215 . That didn't work for you?

**Comment by MarkY-LunarG** [comment]
No, not for me.  But the issue sounds very similar.  I have seen times when then delete works, but other keys don't.

**Comment by sean-mcmanus** [comment]
If you could zip/tar/send us (or post) your `/home/<user>/.vscode/extensions/ms-vscode.cpptools-0.14.0` folder that could help us diagnose the issue. We believe that VS Code or something else external is causing this, even though our extension is somehow a factor.

**Comment by MarkY-LunarG** [comment]
[ms-vscode.cpptools-0.14.zip](https://github.com/Microsoft/vscode-cpptools/files/1455582/ms-vscode.cpptools-0.14.zip)

Sure thing (attached above).  Wow, that's fairly massive.  Let me know if there's any other experiments you want me to try.

**Comment by sean-mcmanus** [comment]
I diffed the files and they're exactly the same (other than the package.json, which is expected) and using those files doesn't repro the bug for me. We believe that VS Code itself is entering some bad state.

**Comment by MarkY-LunarG** [comment]
Based on what you're saying, I think it's a valid conclusion.  Closing this issue.

**Comment by Jefisovas** [comment]
I really like how you are "fixing" bugs. 
So, if you use cpptools, it makes VS Code to enter 'bad state'. 
If you disable cpptools, you have no issues.
So, quick summary, obviously there is something wrong with Vs Code ;)

**Comment by sean-mcmanus** [comment]
I’m not sure what you’re saying or what happened to your response on github, but VS Code had a bug that was causing this ( https://github.com/Microsoft/vscode/issues/36575 ) and not our extension, but it should be fixed now.

**Comment by MarkY-LunarG** [comment]
I agree, this kind of comment has no place.  As a developer, you learn that bugs can happen in anyone's code, and the issue will originally appear in one location while being caused by something completely different.  What the developer's here have stated is not unrealistic or blame-shifting in the least.  Please keep things to constructive/productive discussions on Github repos.
