### ISSUE TITLE
VSC not seeing symbols in outline for c language (No symbols found in document eg_name.c) 

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode-cpptools#12181]
### Environment

- OS and Version: 
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
https://github.com/microsoft/vscode/issues/209982
Not sure is ext problem or VSC

Steps to reproduce:
Use any c code like
```
#include <stdio.h>
int main() {
   // printf() displays the string inside quotation
   printf("Hello, World!");
   return 0;
}
```
Expected behavior:
I expected to see function lists and class, etc. like on python.

### Configuration and Logs

```shell
test
```

### Other Extensions

C/C++ v1.20.0 (pre-release)
C/C++ Extension Pack v1.3.0
C/C++ Themes v2.0.0

### Additional context

test

**Comment by browntarik** [comment]
Are you saying that IntelliSense isn't working correctly? Could you provide a screenshot of the issue you are seeing?

**Comment by ManPython** [comment]
Not sure.. intelisense or dock window with outliner (more this).
![test_c](https://github.com/microsoft/vscode-cpptools/assets/25403861/39967d0b-0cd4-48ff-8146-8bfdb9a83955)

**Comment by browntarik** [comment]
So there could be a few things here:

1) I am not sure your .c file has been opened correctly, it looks like it is missing the c symbol I usually see:
![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/e8becace-bf7e-4be7-bbbe-93c5b12aa974)

2) This would seem to suggest and IntelliSense issue. Could you provide output from the C/C++: Log Diagnostics command you would have access to once you open the file?

**Comment by ManPython** [comment]
Let me see.. I added test2.c file where have problem. Will be great to see your file. Maybe is coding problem.. not sure. But is strange.
[test2.zip](https://github.com/microsoft/vscode-cpptools/files/14923225/test2.zip)

**Comment by sean-mcmanus** [comment]
@ManPython Symbols might not be found if there's some issue with your database. You can set C_Cpp.loggingLevel to "Debug" and look for database error messages, and/or run the C/C++: Reset IntelliSense Database command, and/or add this setting to your workspace's settings.json: "C_Cpp.default.browse.databaseFilename": "${workspaceFolder}/.vscode/browse.vc.db" and verify that the database is created successfully.

**Comment by ManPython** [comment]
Don't understanding nothing here : )

1. Soo.. symbols are in database for each language? Where?
2. I tried re-instal extensions as related c/c++ and nothing.
3. The test.c code is not only for c/c++ but also for ca65 cl65 as ASM to include.. soo.. should be independent I think in relation to `"${workspaceFolder}/.vscode/browse.vc.db`
4. C_Cpp.loggingLevel to "Debug" and look for database error messages ..but no errors around (F1 > Open View... > Shared
5. "C_Cpp.default.browse.databaseFilename": "${workspaceFolder}/.vscode/browse.vc.db" and verify that the database is created successfully. - where this database should be created, how to check, I do this but not see sense here

**Comment by sean-mcmanus** [comment]
@ManPython Our C/C++ extension creates a database of symbols for C/C++ files for the Outline view. It's normally storied in some default location, but you can override that default location to put the database in your workspace folder (perhaps temporarily) to see if that fixes the issue and/or if the database is being created or not. With that setting set, the database should be in the .vscode folder of your workspace folder, the same folder that might contain a setting.json or c_cpp_properties.json files if you've modified those settings.

**Comment by ManPython** [comment]
Ok, got it.. but.. base exist, and some issue around coding? Or it's normal? 

![browse vc db](https://github.com/microsoft/vscode-cpptools/assets/25403861/17f1ea11-4f82-4425-bcb3-6af3fcdbdd94)

**Comment by sean-mcmanus** [comment]
@ManPython What do you mean by "base exist"? Do you mean the bug still repros? Your screenshot doesn't show anything unusual. The "code_items" table is where you should seem symbols.

**Comment by ManPython** [comment]
Data base exist. Symbols list not exist. Soo.. if no symbols, then some type of bug.. 
Did you try my file? Sent me other own example to check how can be done data base on this.. if possible.

**Comment by sean-mcmanus** [comment]
@ManPython Did you look for database or tag parsing errors in the "C/C++" logging pane? This one:

![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/11d854a5-781f-434d-a244-e1b6432f2eca)

**Comment by ManPython** [comment]
In output I dont have C/C++ when .c
But.. I save .c file as .cpp and symbols exist (and then I have in combolist C/C++), so it's problem only when .c file as extension.

**Comment by sean-mcmanus** [comment]
@ManPython We just found a bug with 1.20.1 -- you should try downgrading to 1.20.0 or 1.19.9.

**Comment by ManPython** [comment]
Not working also on v1.19.8 soo waiting for upgrade.

**Comment by sean-mcmanus** [comment]
@ManPython Oh, sorry -- it turns out I was reproing a different issue. You're using the x64 vsix, right?

**Comment by ManPython** [comment]
Not sure about ` x64 vsix`, Windows x64.

**Comment by sean-mcmanus** [comment]
Yeah, that should be the x64 vsix.

We don't currently know what could be causing this failure, but the symptom is similar to a tag parser failure which could be caused if vcmeta.dll can't be loaded by our cpptools.exe process. You may want to verify vcmeta.dll exists at "C:\Users\username\.vscode\extensions\ms-vscode.cpptools-1.20.1-win32-x64\bin\vcmeta.dll" in case it's being deleted externally.

**Comment by ManPython** [comment]
Exist ver. 14.38.33135.0
But if working with cpp then is just case for c not .dll I think.

**Comment by sean-mcmanus** [comment]
@ManPython You're right -- a problem with vcmeta.dll would affect cpp files too. I'm not sure why there would be a failure just with c files (which we're not able to repro so far).

**Comment by ManPython** [comment]
I'm suggest to produce test example as .cx or .cc extension to see it's VSC problem or not.

**Comment by ManPython** [comment]
Problem still exist with `v1.20.4 (pre-release)` and `v1.20.5`
```
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by ManPython** [comment]
But any changes around?

**Comment by ManPython** [comment]
Not resolved.

**Comment by ManPython** [comment]
https://github.com/Microsoft/vscode/issues/61933
