### ISSUE TITLE
Cpp debug attach to process not working in VScode 1.17.2 on Mac

### ISSUE THREAD

**Issue by echosys** [microsoft/vscode-cpptools#1218]
Hi, I am trying to attach to a process for  cpp and following some documentation I learned that I need to add  "processId": "${command.pickProcess}" 
But I get "Property processId is not allowed
"
and a green line. I have tried install and reinstall vscode and the cpp extension with no difference. 

Here are my configs. 
{
        "version": "0.2.0",
        "configurations": [
            {
                "name": "(lldb) Launch",
                "type": "cppdbg",
                "request": "launch",
                "program": "${workspaceRoot}/a.out",
                "args": ["<testa8t.txt"],
                "stopAtEntry": false,
                "cwd": "${workspaceRoot}",
                "environment": [],
                "externalConsole": true,
                "osx": {
                    "MIMode": "lldb"
                },
                "processId": "${command.pickProcess}" 
            }
        ]
    }

**Comment by sean-mcmanus** [comment]
You should click the Add Configuration... button and select the (lldb) Attach option, and then make sure the `program` field is set to match your executable path.

**Comment by pieandcakes** [comment]
@echosys What @sean-mcmanus said. When using `"request": "launch"` it is expecting it to launch gdb with the executable. if you want to attach to a running process, use the `"request"` value of `"attach"`

**Comment by echosys** [comment]
Thanks for the reply. So I did try the value of "attach" and it seems like vscode cpp debugger was able to attach to the program but not able to hit the breakpoints. 
I used a usleep statement for 15second so I have enough time to attach but as soon as I attach the program resumes executing and breakpoint was never hit. 
I did make sure I am using the same a.out file and breakpoint is indeed put on the correct source file. Any suggestions? 

Debugger Output:
Loaded '/usr/lib/system/libsystem_symptoms.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_trace.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libunwind.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libxpc.dylib'. Symbols loaded.
Loaded '/usr/lib/closure/libclosured.dylib'. Symbols loaded.
Loaded '/usr/lib/libobjc.A.dylib'. Symbols loaded.
Debugger has disconnected from the program ''.

**Comment by echosys** [comment]
I was using the usleep statement on Mac under include header file of #include <unistd.h>. 
Would that interfere with the debugger and be the cause of why as soon as I attach the debugger the usleep seems to stop and program resume executing?

**Comment by pieandcakes** [comment]
@echosys when you compiled did you compile with the `-g` flag to include debug symbols in your executable?

**Comment by SonnyBonds** [comment]
@sean-mcmanus A bit of a side track, but do you know why "program" is required when attaching really? If the binary is needed somehow, could it not at least be deduced from the selected process?

**Comment by sean-mcmanus** [comment]
@Dentoid I seem to recall complaining about this to @pieandcakes and he told me that "program" tells gdb/lldb where to locate symbols, but I don't recall why the path can't be deduced from the process id.

**Comment by SonnyBonds** [comment]
@sean-mcmanus Just did a quick test, and setting it to "/usr/bin/man" or whatever seems to work as well (breakpoints, stepping, variables, call stack, etc.), so it really looks a bit unneccessary.

**Comment by WardenGnaw** [comment]
Closing due to inactivty.
