### ISSUE TITLE
Unable to resolve configuration with compilerPath C:/cygwin64/bin/gcc.exe . Using C:\cygwin64\bin\gcc.exe instead.

### ISSUE THREAD

**Issue by RaeesRaqeeb** [microsoft/vscode-cpptools#12180]
how did you solved this problem? 
I am facing the same problem with error statement:
Unable to resolve configuration with compilerPath C:/cygwin64/bin/gcc.exe . Using C:\cygwin64\bin\gcc.exe instead.

This is showed as output whenever I open my vs code. It is indicating to same path.

**Comment by browntarik** [comment]
It seems to be the case that forward slashes are significant to the path being correct. What operating system are you on?

**Comment by Colengms** [comment]
Hi @RaeesRaqeeb .  I'm not able to repro an issue with the information provided.  On Windows, with the latest versions of the C/C++ Extension (1.19.9, as well as 1.20.1) and cygwin64 (not sure what version I had installed, but gcc says 11.3.0), I appear to be able to configure IntelliSense using the following in `c_cpp_properties.json`.

```
"compilerPath": "C:/cygwin64/bin/gcc.exe",
```

That said, there is a lot of information that could help us understand what's going on.  What version of the C/C++ Extension are you using?  How are you configuring IntelliSense? What is the output of the C/C++ output channel, with `"C_Cpp.loggingLevel": "Debug"` enabled?

Depending on how you've configured the extension, or a project folder, the C/C++ Extension may be attempting to query your compiler for system includes and system defines, using compiler arguments you've provided, which we're were unable to execute the compiler successfully with.  Details about a failed compiler query should be indicated in logs (requested in our new issue template).  I suspect this is what's happening, and it's falling back to the default compiler, which happens to be the same compiler, just without any of your additional arguments being provided to it.
