### ISSUE TITLE
Enabling customization of hover information in a similar way that natvis files improves data view in debugging

### ISSUE THREAD

**Issue by uxsu** [microsoft/vscode-cpptools#12196]
### Feature Request

When hovering over constexpr compile-time known variables, langauge servers provide useful information like this:

![Screenshot 2024-04-13 121213](https://github.com/microsoft/vscode-cpptools/assets/47246719/6c288249-db90-4a2a-9e34-7e25f92f9d84)

What I would like to do is to have something like a .natvis file that will change the way the information is presented dependent on my customization in the file. For the example screenshot above, I would like to customize it so that it will show:
`constexpr ct::String<15Ui64> str2 = "HelloHelloHello"`.

Here is a reference implementation of ct::String class in the screenshot:

```cpp
namespace ct {

template <std::uint64_t size>
class String;

template <std::uint64_t byte_size>
class String {
public:
  template <std::uint64_t>
  friend class String; //Creates friendship among all String template instantiations

  //Has to be public to make String class constexpr
  char bytes_[byte_size + 1] = {0}; //Initialize with null character
  //member functions...
};
}
```
With the increased usage of constexpr in C++ this additional customization can make life easier.

**Comment by browntarik** [comment]
Thank you for providing your feature request
