### ISSUE TITLE
Doxygen return parameter links to a GitHub user's account page

### ISSUE THREAD

**Issue by bastian2001** [microsoft/vscode-cpptools#12192]
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.88.1
- C/C++ Extension Version: 1.19.9

### Bug Summary and Steps to Reproduce

Bug Summary: Inconsistent popup behaviour

Steps to reproduce:
1. Write a doxygen style comment with @ return in it (space so he gets no ping from this issue)
2. Hover over the @ return label
3. A popup of GitHub user @ return appears
Expected behavior: No popup, just like with @ brief, @ param, ...

![grafik](https://github.com/microsoft/vscode-cpptools/assets/25935728/20334f6d-9e42-44b9-8da0-910c82aafa8a)

### Configuration and Logs

```shell
N/A
```

### Additional context

Seems to happen only in GitHub repositories.

**Comment by browntarik** [comment]
Can you verify that this issue doesn't repro after our extension is disabled? This will help us confirm that this issue is coming from the C/C++ Extension.

**Comment by bastian2001** [comment]
@browntarik you're right, I just assumed that because the C++ extension is responsible for the tooltip popups, that it would be responsible for _all_ popups of this style, but this popup seems to come from another extension or VS Code itself.

**Comment by bastian2001** [comment]
Seems to be the GitHub Pull Requests Extension
