### ISSUE TITLE
Remove "root permissions" prompt when attaching in GDB

### ISSUE THREAD

**Issue by delmyers** [microsoft/vscode-cpptools#122]
This is a request inside #115. I separated it out just for tracking purposes. Unfortunately, we can't fix it. This is a limitation of GDB. One cannot attach to a process without root permissions. The work around is to install VsCode as the root user and debug your applications from that instance of VsCode. Unfortunately, launching VsCode as root will not work because permissions are not passed to sub-processes on Linux using the process model that VsCode was built on.

**Comment by reoxb** [comment]
:v
