### ISSUE TITLE
fuzzy search bug

### ISSUE THREAD

**Issue by chall1123** [microsoft/vscode-cpptools#12204]
### Environment

- OS and version:
- VS Code:1.81.1
- C/C++ extension:1.20.0
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do '...'
4. See error...
coturndo cannot find my function coworker_turn_do

### Debugger Configurations

```shell
1
```

### Debugger Logs

```shell
1
```

**Comment by sean-mcmanus** [comment]
@chall1123 I don't understand why there's a text ` code/lib` in your query if that doesn't appear to match the symbol you intend to find.

Does the issue repro with a smaller workspace? There could be too many matches being returned. You could try increasing C_Cpp.maxSymbolSearchResults to 10000.

**Comment by chall1123** [comment]
> C_Cpp.maxSymbolSearchResults

I added a setting of 10000 for "C Cpp. maxSymbolSearchResults", but my function still cannot be searched. When I uninstalled the Python extension, my function can be searched normally, so there may be some conflict between these two extensions

**Comment by sean-mcmanus** [comment]
@chall1123 Which Python extension? It seems like it would be a bug with that extension? But from the docs on registerWorkspaceSymbolProvider at https://code.visualstudio.com/api/references/vscode-api, it says "Multiple providers can be registered. In that case providers are asked in parallel and the results are merged. A failing provider (rejected promise or exception) will not cause a failure of the whole operation."...so from that it doesn't sound like it's expected for the Python extension to be blocking our symbol results. It's possible it could be some bug with VS Code itself?

**Comment by chall1123** [comment]
> @chall1123 Which Python extension? It seems like it would be a bug with that extension? But from the docs on registerWorkspaceSymbolProvider at https://code.visualstudio.com/api/references/vscode-api, it says "Multiple providers can be registered. In that case providers are asked in parallel and the results are merged. A failing provider (rejected promise or exception) will not cause a failure of the whole operation."...so from that it doesn't sound like it's expected for the Python extension to be blocking our symbol results. It's possible it could be some bug with VS Code itself?

@sean-mcmanus python v2023.9.10, if this is vscode bug, I can only install one of the two extensions to use
![image](https://github.com/microsoft/vscode-cpptools/assets/37236882/7ac38636-0723-4902-8eb9-9da905eae9e1)

**Comment by sean-mcmanus** [comment]
@chall1123 Are you able to create a sample repro that demonstrates the bug? Or are able to find the necessary configuration settings to repro it? i.e. I don't know how to repro the issue. If you file a Pylance or VS Code bug, they also might need more repro info.

**Comment by chall1123** [comment]
> @chall1123 Are you able to create a sample repro that demonstrates the bug? Or are able to find the necessary configuration settings to repro it? i.e. I don't know how to repro the issue. If you file a Pylance or VS Code bug, they also might need more repro info.

@sean-mcmanus thanks，My project contains a large amount of Python and C code.There are no other operations，I just need to install and uninstall Python extensions simply. , and the problem can be solved and reproduced. I will use it alone for now. Thank you very much
