### ISSUE TITLE
Intelli Sense Cache Path setting not respected

### ISSUE THREAD

**Issue by vintas** [microsoft/vscode-cpptools#12212]
### Environment

- OS and Version: Windows 11
- VS Code Version: 1.85.2
- C/C++ Extension Version: v1.18.5
- If using SSH remote, specify OS of remote machine: Ubuntu 18.04

### Bug Summary and Steps to Reproduce

Bug Summary:
In Remote setting tab, Intelli Sense Cache Path is set to a folder on another drive but is not used for cache. Instead $HOME/.cache/vscode-cpptools is being used. $HOME/ is a tiny 10 GB NAS mount on my VM and this mount gets full with around 5 GB of intellisense cache.
It is creating a folder called `ipch` in the Intelli Sense Cache Path I have set but the bulk of the storage is used at $HOME/.cache/vscode-cpptool

Expected behavior: Create the folder vscode-cpptools in the folder specified by Intelli Sense Cache Path.

### Configuration and Logs

```shell
{
    "C_Cpp.intelliSenseCachePath": "/my_dev_config/my_c_intellisense_cache"
}
```

**Comment by sean-mcmanus** [comment]
@vintas For the database .db file you need to also set `C_Cpp.default.browse.databaseFilename` or the equivalent property in c_cpp_properties.json. Does that solve your issue?
