### ISSUE TITLE
The language server crashed. Restarting...

### ISSUE THREAD

**Issue by gmrparcerao** [microsoft/vscode-cpptools#12215]
Type: <b>Bug</b>

There is no steps, I just need to open a C/C++ code file and this error appears. I identified using extension bissect that cpptools is causing this error alone.

Extension version: 1.19.9
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:34:12.840Z)
OS version: Linux x64 6.8.0-76060800daily20240311-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2659)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (11.41GB free)|
|Process Argv|--unity-launch /home/guilherme/Codes/Embarcados/hello-cpp --crash-reporter-id 45f5b799-65b6-47c2-ac78-5f59ccb70896|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
724cj586:31013169

```

</details>

**Comment by Colengms** [comment]
Hi @gmrparcerao .  Since you have a Ryzen 3000-series processor, this is likely due to an underlying hardware issue which should be fixable by updating your motherboard BIOS.  Can you confirm?

We have https://github.com/microsoft/vscode-cpptools/issues/12201 tracking working around the hardware bug to prevent the crash.

If that does not address the issue, we may need more information to investigate further, as we're not tracking a similar issue impacting a large number of users.  For instance, does the issue persist if you install prior versions of the extensions?

**Comment by gmrparcerao** [comment]
> Hi @gmrparcerao .  Since you have a Ryzen 3000-series processor, this is likely due to an underlying hardware issue which should be fixable by updating your motherboard BIOS.  Can you confirm?
> 
> We have https://github.com/microsoft/vscode-cpptools/issues/12201 tracking working around the hardware bug to prevent the crash.
> 
> If that does not address the issue, we may need more information to investigate further, as we're not tracking a similar issue impacting a large number of users.  For instance, does the issue persist if you install prior versions of the extensions?

Hello @Colengms . Yes, O already tried to fix the problem downgrading the extensions to older versions, without any progress. I'm updating my BIOS right now and 'll keep informed about new information

**Comment by gmrparcerao** [comment]
The problem seems to be solved after the BIOS update, thank you very much for the help!
