### ISSUE TITLE
Fluent Terminal

### ISSUE THREAD

**Issue by HyperDragonIm** [microsoft/vscode-cpptools#12218]
A Terminal Emulator based on UWP and web technologies.

Features
Terminal for PowerShell, CMD, WSL or custom shells
Built-in support for SSH and Mosh connections
Supports tabs and multiple windows
Theming and appearance configuration
Import/Export themes
Import iTerm themes
Fullscreen mode
Editable keybindings
Search function
Configure shell profiles to quickly switch between different shells
Explorer context menu integration (Installation script can be found here) https://apps.microsoft.com/detail/9p2krlmfxf9t

**Comment by bobbrow** [comment]
Hi @HyperDragonIm,

Thank you for the feature request.  However, the C++ extension does not have the capability to modify the terminal as you describe.  You might have better luck asking the VS Code team for help with this.  Could you open your issue in their repo instead?

https://github.com/microsoft/vscode/issues/new/choose

Happy Coding!
