### ISSUE TITLE
Feature request: additional defines that are merged with compile_commands.json, but just for diagnostics

### ISSUE THREAD

**Issue by fredemmott** [microsoft/vscode-cpptools#12224]
### Feature Request

I would like this for a project that builds with `cl.exe`; unfortunately, some Windows headers can not be built with clang (powering the clang diagnostics) with the same parameters.

For example, `<DirectXMath.h>` will `#include <cpuid.h>` if `__clang__` is defined, which is not usable with the rest of the flags that are pointing at the MS C++ runtime.

It would be useful if:
- 'rebuild this file' would use `cl.exe` verbatim as in my `compile_commands.json`
- I could add extra defines/args purely for clang-based diagnostics without changing the `compile_commands.json`, e.g. `-DCLANG_FOR_DIAGNOSTICS`, or specifically for `DirectXMath.h`, `-D_XM_NO_INTRINSICS_`

AlternativesI've considered :
- I have tried setting `mergeConfigurations` in combination with `defines` and `compilerArgs`; based on the "C/C++ Log Diagnostics" output, it does not have any effect when compileCommands is being used.
- `compile_commands.json` is primarily for clang-based tools: i could just make my toolchain add the flags there. I don't like this because it breaks "build this file"

**Comment by sean-mcmanus** [comment]
@fredemmott You can use setting `    "C_Cpp.codeAnalysis.clangTidy.args": ["--extra-arg=-DCLANG_FOR_DIAGNOSTICS"]`. Does that solve your issue?

**Comment by fredemmott** [comment]
@sean-mcmanus I don't believe so - I have clean clang-tidy runs on command line with just `-p directory_containing_compile_commands.json`, but I still get these in VSCode - I'm assuming that the extension is doing more diagnostics than just clangTidy - or perhaps these errors are from intellisense? 
![image](https://github.com/microsoft/vscode-cpptools/assets/360927/e2537e57-b9d5-44b9-9f8b-50ee7c9b218b)

**Comment by sean-mcmanus** [comment]
@fredemmott Do you have `C_Cpp.codeAnalysis.clangTidy.useBuildPath` set to `true`?

**Comment by fredemmott** [comment]
No difference either way, or with it explicitly in the arguments

Will it by default use the clang-tidy from $PATH (which will be Visual Studio's version for me), or does it use a bundled one that's (closer to?) upstream (LLVM)?

**Comment by fredemmott** [comment]
It's a tangent, but in case other's find that last comment through search for CMake+MSBuild+compile_commands.json this is working with:

1. Enabling msbuild clang-tidy support: https://github.com/OpenKneeboard/OpenKneeboard/blob/8b9ec15d7391cc50df6348d758e86de48eb10bd3/CMakeLists.txt#L26-L38
2. Generating per-target flags and sources lists via `Directory.Build.targets` **copied to the root of the build directory, not the source directory**: https://github.com/OpenKneeboard/OpenKneeboard/blob/8b9ec15d7391cc50df6348d758e86de48eb10bd3/scripts/Directory.Build.targets
3. Generating per-target compile_commands.json with this script (invoked by `Directory.Build.targets`): https://github.com/OpenKneeboard/OpenKneeboard/blob/8b9ec15d7391cc50df6348d758e86de48eb10bd3/scripts/make-compile-commands.ps1
4. Merging them and passing them to the C/C++ extension with:

```JSON
  "cmake.mergedCompileCommands": "${workspaceFolder}/build/compile_commands.json",
  "C_Cpp.default.compileCommands": "${workspaceFolder}/build/compile_commands.json",
```
