### ISSUE TITLE
Latest vscode 1.18 update has broken code formatting

### ISSUE THREAD

**Issue by Pagghiu** [microsoft/vscode-cpptools#1222]
OS: macOS High Sierra
VS Code: 1.18.0
C/C++ extension version: 0.14
----
Latest vscode 1.18 update has broken code formatting. It displays "no formatter for cpp files installed".

![screen shot 2017-11-09 at 11 09 31](https://user-images.githubusercontent.com/5406873/32600972-8621af2c-c541-11e7-9db5-c8173f519534.jpg)

**Comment by Pagghiu** [comment]
Re-installing the C/C++ extension fixes the problem.

**Comment by bobbrow** [comment]
Hmm.. that's weird.  We don't have a message with that text in it.  It must have been some other extension hijacking the format commands.
