### ISSUE TITLE
Intelli Sense Cache Path Setting doesn’t work.

### ISSUE THREAD

**Issue by tkchips** [microsoft/vscode-cpptools#12220]
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.88.1
- C/C++ Extension Version: 1.19.9
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:

The config C_Cpp.intelliSenseCachePath  doesn't work on my windows. 
Steps to reproduce:
1. Set new path for C_Cpp.intelliSenseCachePath,such as G:/Caches/vscode-cpptools
2. Restart VSCode
3. The folder vscode-cpptools is created,it is empty
4. The cache is created in default folder like %LocalAppData%/Microsoft/vscode-cpptools.

Expected behavior:

### Configuration and Logs

```shell
{
"C_Cpp.intelliSenseCachePath": "G:/Caches/vscode-cpptools"
}
```

**Comment by Ceekinbox** [comment]
I guess I find the reason,see [https://github.com/microsoft/vscode-cpptools/issues/11839](11839)
