### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by agauniyal** [microsoft/vscode-cpptools#1223]
* Arch Linux
* VS Code 1.18
* C/C++ latest version
* All other extensions disabled
* Open any cpp file and wait for random time

More information here - https://github.com/Microsoft/vscode/issues/37924

**Comment by bobbrow** [comment]
We fixed the linked issue a while ago.  Is there still another problem that needs to be addressed here?  Thanks.
