### ISSUE TITLE
[FR] vcFormat: new lines for branches

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode-cpptools#12230]
Type: <b>Feature Request</b>

I couldn't find option for vcFormat (in json) to put branches onto new lines:

```
  } else if(strStartsWith(arg, "away"))
  {
```
into
```
  } 
  else if(strStartsWith(arg, "away"))
  {
```

Extension version: 1.17.5
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
@mrx23dot `"C_Cpp.vcFormat.newLine.beforeElse": true`.

**Comment by sean-mcmanus** [comment]
@mrx23dot The docs are the vcFormat settings are in the settings UI: 
![image](https://github.com/microsoft/vscode-cpptools/assets/19859882/366267f0-c591-4bcf-85d6-53e7d3dbbdf4)

The page at https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp only describes the IntelliSense compiler configuration settings.
