### ISSUE TITLE
The GitHub readme is great, but the marketplace readme is bare

### ISSUE THREAD

**Issue by DrLonnieJonesPFMP** [microsoft/vscode-cpptools#12257]
Your readme for in the GitHub is substantially better than the one in the Visual Studio Code Marketplace found here: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack. Could you replace it for your GitHub readme file? It can give users a better idea of the extension pack ideas.

**Comment by sean-mcmanus** [comment]
@DrLonnieJonesPFMP Your link is to the "extension pack". It is expected that users who want to know more will clink the individual extension in the pack and read their ReadMe's, i.e. is the ReadMe for https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools the one you wanted?
