### ISSUE TITLE
Lenguaje 

### ISSUE THREAD

**Issue by nickthe55** [microsoft/vscode-cpptools#12263]
### Environment

- OS and Version: 
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 

- [https://github.com/jlord/sheetsee.js/issues/26 ] 

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
"logging": {
    "engineLogging": false
}
```

### Other Extensions

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "symbolSearchPath": "https://msdl.microsoft.com/download/symbols",
            "logging": {
                "engineLogging": true,
                "trace": true
            },
        }
    ]
}

**Comment by sean-mcmanus** [comment]
@nickthe55 There is not enough information in this report.

**Comment by Zionsammy** [comment]
Thanks

**Comment by Saud9911** [comment]
I
