### ISSUE TITLE
c++ compiler does not ruun

### ISSUE THREAD

**Issue by fhbaloch442** [microsoft/vscode-cpptools#12265]
when i run a program (c++)
compiler say retrun  is not declared..

PS C:\c++ vs code.cpp> cd "c:\c++ vs code.cpp\" ; if ($?) { g++ tempCodeRunnerFile.cpp -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
tempCodeRunnerFile.cpp: In function 'int main()':
tempCodeRunnerFile.cpp:10:5: error: 'retrun' was not declared in this scope
     retrun 0;
     ^~~~~~
PS C:\c++ vs code.cpp> cd "c:\c++ vs code.cpp\" ; if ($?) { g++ tempCodeRunnerFile.cpp -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
tempCodeRunnerFile.cpp: In function 'int main()':
tempCodeRunnerFile.cpp:10:5: error: 'retrun' was not declared in this scope
     retrun 0;
     ^~~~~~
PS C:\c++ vs code.cpp> 
![IMG-20240501-WA0009.jpg](https://github.com/microsoft/vscode-cpptools/assets/168584613/feaf387e-26fb-455b-ac4c-1d5eb8855872)

**Comment by browntarik** [comment]
It looks like there may be some compilation errors in this issue, see "retrun". I believe it should be spelled "return". Does this answer your question?
