### ISSUE TITLE
Beginning C++ Tutorial

### ISSUE THREAD

**Issue by Absdidhav** [microsoft/vscode-cpptools#12270]
I've just set up Using GCC with MinGW and tried to compile and run the first program "Hello World" by copying and pasting it into VS.
When I ran the program it came up with the following error message:

The preLaunchTask 'C/C++: gcc.exe build active file' terminated with the exit code -1

I also noticed that there were only two files that were created in the workspace .vscode folder:
tasks.json  and
launch.json

c_cpp_properties.json was NOT CREATED

What's wrong? 
Can you please advise?

**Comment by browntarik** [comment]
@Absdidhav If you are compiling in C++, please ensure you are using a g++ compiler instead of gcc. It seems like you already fixed your issue so I will close this issue now.
