### ISSUE TITLE
Unsupported linux clients sending excessive telemetry

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#1227]
Clients that are unable to start the extension (e.g. CentOS7, x86 linux) are sending an excessive amount of telemetry while attempting to start the language server.

**Comment by bobbrow** [comment]
fixed in 0.14.2

**Comment by s-martin** [comment]
Is there a possibility that the source #19 for this issue (at least on CentOS) will be fixed?

**Comment by bobbrow** [comment]
Yes, we do plan to address #19.

**Comment by s-martin** [comment]
@bobbrow Appreciate it!
