### ISSUE TITLE
Intellisense fails to distinguish same name files in different directories

### ISSUE THREAD

**Issue by Saitama10000** [microsoft/vscode-cpptools#12296]
### Environment

- OS and Version:  Windows 11 and Ubuntu 22.04
- VS Code Version: 1.89.1
- C/C++ Extension Version: 1.20.5
- If using SSH remote, specify OS of remote machine: -

### Bug Summary and Steps to Reproduce

Bug Summary:
Intellisense fails to distinguish same name files in different directories

Steps to reproduce:
1. clone this: [link to github repo with bug](https://github.com/Saitama10000/intellisense-bug/tree/main)
2. create a build directory in root
3. run `cd build && cmake .. && cmake --build .` (build the repo to check that there are no errors from the compiler)
4. set extension c++ standard to c++20
5. open `./dir/dir0/src/main_0.cpp` and hover over `test_0_t`. Intellisense identifies it.
6. open `./dir/dir1/src/main_1.cpp` and hover over `test_1_t`. _**Intellisense doesn't identify it.**_

Expected behavior:
6. open `./dir/dir1/src/main_1.cpp` and hover over `test_1_t`. _**Intellisense should identify it like it did for `main_0.cpp`**_

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc"
        }
    ],
    "version": 4
}
```

**Comment by browntarik** [comment]
Thanks for reporting this issue. It looks like what you are experiencing is **by-design** behavior. Due to the limitations of what we can differentiate header files by, you can't use the filename as the relative path in this case. It would be more correct to provide the folder that each file resides in as well. See the example below:

![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/4957c9b6-9c96-4882-b4b3-d1e6081d3674)

Please let me know if this helps.

**Comment by sean-mcmanus** [comment]
@Saitama10000 To add more info, I believe it's caused by usage of `"${workspaceFolder}/**"` in which the include order is non-deterministic. You may be able to workaround the issue by adding a path to your include path before that to cause that path to get precedence.

**Comment by Saitama10000** [comment]
Thank you for the replies. I don't know why but now it works even though I haven't changed anything. I understand the issue now (which is a non-issue, it's how the engine works). You can close the thread.
