### ISSUE TITLE
Make hover menu show documentation from source file instead of header file if it's written in the Doxygen format

### ISSUE THREAD

**Issue by Aric5301** [microsoft/vscode-cpptools#12295]
### Feature Request

Hi.
My current convention for programming is that I write Doxygen styles documentation for functions source files, and only write a small description for functions in header files.
The current behavior of the feature in this extension that shows function documentation for functions that are defined on another compilation unit when I hover over their call seems to be the following:
1. If a function declaration in a header file has any documentation, display it.
2. Otherwise, if the source file has any documentation for that function, display it.

This means, that what I get shown is the small function description instead of the full documentation available in the source file.

My suggested feature it to either add an extension setting that let's me choose whether it first looks for the documentation in the header or source file, or add a setting that prioritizes taking the Doxygen style documentation (so in my case it will take documentation from the source file since the header style comment isn't written in Doxygen style.

So, in the case of:
![image](https://github.com/microsoft/vscode-cpptools/assets/25414752/49fa025e-1cc0-49f6-b3e2-5f548bb6c2c1)
![image](https://github.com/microsoft/vscode-cpptools/assets/25414752/d62e392f-55cc-422c-864d-2d4cf6298185)
### Current behavior
![image](https://github.com/microsoft/vscode-cpptools/assets/25414752/fcd79306-0779-4b94-90f0-c2382d337c65)
### Suggested behavior
![image](https://github.com/microsoft/vscode-cpptools/assets/25414752/4486cc63-508c-4e35-8b16-85dd1ead693b)

Thank you very much!

**Comment by browntarik** [comment]
Thank you for requesting this feature, please follow this thread for future updates.
