### ISSUE TITLE
Single c_cpp_properties.json for an entire workspace

### ISSUE THREAD

**Issue by rdlaner** [microsoft/vscode-cpptools#1229]
With the recent update to handle VS Code's multi-root workspaces there now must be a c_cpp_properties.json file for each root folder added to a workspace. For my project, it's far more convenient to have a single c_cpp_properties.json file that applies to the entire workspace. With that, I don't have to add a new one for each added folder. Additionally, since each root directory in my project is a separate git repo, requiring a .vscode folder in each root directory means updating the .gitignore file for each repo to ignore .vscode. I'd rather not have to update .gitignore for each repo since there are many in this project and the process around updating it is a pain.

Is this possible?

**Comment by bobbrow** [comment]
It's not currently possible but it's also not out of the question.  The tricky part is that your *.code-workspace  file doesn't have to live inside of a .vscode folder, so we wouldn't know where to look for the workspace's c_cpp_properties.json file.  Moving the contents of c_cpp_properties.json into the settings file would potentially resolve this, but we don't have consensus internally about making that change.  This could potentially tip the scales in favor of obsoleting c_cpp_properties.json.

**Comment by rdlaner** [comment]
I see, that makes sense. I, for one, vote for moving the contents of c_cpp_properties.json to the settings file.

I went ahead and made a .vscode folder and a c_cpp_properties.json for each root directory, but now I have a ton of error squiggles throughout the workspace. It looks like the tag parser is working fine, but the intellisense engine can't seem to find anything any longer. I'm really not sure how to get it backing to working again.

**Comment by floooh** [comment]
I have a similar situation, I generate one c_cpp_properties.json file with the combined header search paths for a main project and any number of dependencies which are integrated as workspace folders and live on the same directory level as the main project. Intellisense only works when editing files in the 'main project' which has the c_cpp_properties.json file in its .vscode directory, but fails when editing files in dependency projects.

I would too prefer a single place to define the header search paths for the entire workspace (main project and dependencies).

**Comment by sean-mcmanus** [comment]
@bobbrow We can add a C_Cpp.configurationPath setting. If this is set and the file exists, then the folder's `.vscode/c_cpp_properties.json` (or the internal default) would be ignored and the setting version would be used instead for all the folders. The ${workspaceRoot} variable (renamed workspaceFolder by VS Code) would still be evaluated differently for each folder.

However, the errors they're reporting seems like a different issue (I think we need more info, such as the includePath and an example of an error).

**Comment by rdlaner** [comment]
@sean-mcmanus Do you have an idea of when a C_Cpp.configurationPath setting will be added? I'm just getting back to trying to debug the issues arising from having multiple c_cpp_properties.json files and a setting like this would be really helpful. Thanks.

**Comment by sean-mcmanus** [comment]
I don't know yet. We have to discuss our plans in January.

**Comment by bobbrow** [comment]
We are investigating deprecating c_cpp_properties.json in favor of settings.json.  That work should resolve this issue.

**Comment by 3v1n0** [comment]
As a trick, what I do right now is saving a single `c_cpp_properties.json` file in the workspace folder and the using symlinks in all the other folders. It works fine even for tasks and other things that I want to share.

**Comment by bobbrow** [comment]
I have just posted a plan to issue #1338 that may address this issue.  I encourage those on this thread to take a look and provide feedback.

**Comment by ghuser404** [comment]
Ideally this should allow to specify separate properties for each "project", and be easily integratable with CMake.

Is this the plan?

**Comment by bobbrow** [comment]
This issue is about sharing configs across multiple projects, but we do have [something in the works](https://github.com/Microsoft/vscode-cpptools/pull/1804) in the form of an extension API that would allow another extension that understands "projects" (e.g. CMake, or other build system provider) to provide configurations for files as they are opened

**Comment by rdlaner** [comment]
@bobbrow , I'm starting to work through all of the new functionality and am getting a little bit lost. My first attempt to use a single configuration for an entire workspace is to:
* First create the workspace and add all of the folders to it.
* Update the workspace settings to implement the default C_Cpp settings I want (ie compilerPath, browsePath, IncludePath, etc.)
* For the browse and include paths, I am adding ${workspaceRoot}/** in an attempt to make all files in the workspace available.

I am assuming that the default settings set in the .code-workspace file will apply to my workspace of C++ folders, however, I am finding that it doesn't seem to work. None of my include paths are being found; I only get the green squiggly and "cannot open source" file error.

What am I doing wrong?

**Comment by bobbrow** [comment]
Are you trying to reference files from workspaceFolder1 in workspaceFolder2?

**Comment by rdlaner** [comment]
I am referring to files in different workspace folders. For example a .cpp file in workspaceFolder1 will have an include directive for a header file in workspaceFolder2.

I ended up getting it to work by specifying each individual directory path in the "C_Cpp.default.browse.path" and "C_Cpp.default.includePath" settings in the workspace settings file and having an individual c_cpp_properties.json file for each folder in the workspace. Each individual c_cpp_properties.json file simply uses ${default} on each setting in order to refer to the workspace settings. It now correctly locates all of my include directives.

The issue that I am having now is I am getting a lot of random red squiggly errors. For example, there are a lot stating that an identifier (like uint32_t) is undefined, however, I can click on the identifier and "Go to definition" and it goes to the definition just fine. I don't know why it considers this an error.
I'm also getting a lot of "name followed by '::' must be a class or namespace name" errors even though the name is obviously a class or namespace and will even navigate to the correct class or namespace correctly if I "Go to definition".

Any idea why these errors are popping up?
Also, do I really need an individual c_cpp_properties.json for each folder? It would be nice if it would automically use the workspace settings without needing a c_cpp_properties.json file just to call the ${default} env variable.

**Comment by rdlaner** [comment]
Ah, I think I'm getting all of the errors due to an incorrect compiler definition. So don't worry about that issue, I think that is on my side.

I'm still curious about the need for multiple c_cpp_properties files, though.

**Comment by bobbrow** [comment]
If you set the `C_Cpp.default.*` variables in your workspaces, the **c_cpp_properties.json** can be deleted.  If the settings values are the same for all folders, then you should be able to set it once at the workspace level instead of having to set it on each of the folders.

Regarding the squiggles, you can set `"C_Cpp.loggingLevel": "6"` and the extension will print out the includes and defines used to compile the translation unit in the Output window (select the C/C++ filter from the dropdown to see our extension's messages).  You don't want to leave this setting on forever though since it logs more than you generally need.

Navigation and squiggles are implemented with different data sources, so that's why one works when the other might not.

**Comment by rdlaner** [comment]
Ok, thanks for the info. I'm going to do a little bit more debugging.

**Comment by rdlaner** [comment]
So, the random error squiggles are back. They were briefly suspended until I had resolved an include path.

I'm really not sure how to debug them. In the end, I can just turn them off, but I'd kinda like to know why they are there.

Any idea on how I can debug them further?

**Comment by bobbrow** [comment]
Could you set the logging level to "6" and verify in the logs that the include paths are correct?  Or if you can share a small project that exhibits this behavior we can debug it.

**Comment by rdlaner** [comment]
Yes, I did set logging level to "6". It looks like all of the anticipated includes are being included. It is including a number of directories that I did not explicitly add, however; are these default for Windows setups? Below is a copy from the log output when parsing a single file. I have tried to indicate which paths that were included automatically and are not part of my build environment:

initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/*.o
File exclude: **/*.d
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
textDocument/didOpen
cpptools/queryCompilerDefaults
cpptools/activeDocumentChange
cpptools/resumeParsing
cpptools/textEditorSelectionChange
cpptools/didChangeFolderSettings
Code browsing service initialized

  **Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.11.25503/INCLUDE/\* will be indexed**
  **Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.11.25503/ATLMFC/INCLUDE/\* will be indexed**
  **Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.15063.0/UM/ will be indexed**
  **Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.15063.0/UCRT/ will be indexed**
  **Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.15063.0/SHARED/ will be indexed**
  **Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.15063.0/WINRT/ will be indexed**

  Folder: C:/USERS/PROJECTS/SW/OSAL/INCLUDE/ will be indexed
  Folder: C:/USERS/PROJECTS/SW/PSP/INCLUDE/ will be indexed
  Folder: C:/USERS/PROJECTS/SW/QP/INCLUDE/ will be indexed
  Folder: C:/USERS/PROJECTS/SW/QPP/INCLUDE/ will be indexed
  Folder: C:/USERS/PROJECTS/SW/SAFERTOS/CORE/INCLUDE/ will be indexed
  Folder: C:/USERS/PROJECTS/SW/SAFERTOS/ZYNQ/INCLUDE/ will be indexed
  Folder: C:/USERS/PROJECTS/SW/SOC/INCLUDE/ will be indexed
  Folder: C:/USERS/PROJECTS/SW/SOC/EP1/INCLUDE/ will be indexed
  Folder: C:/USERS/PROJECTS/SW/XPF/INCLUDE/ will be indexed
  Folder: C:/USERS/PROJECTS/SW/ZPF/INCLUDE/ will be indexed
  Folder: C:/XILINX/SDK/2017.3/GNU/AARCH32/NT/GCC-ARM-NONE-EABI/LIB/GCC/ARM-NONE-EABI/6.2.1/INCLUDE/ will be indexed
  Folder: C:/XILINX/SDK/2017.3/GNU/AARCH32/NT/GCC-ARM-NONE-EABI/LIB/GCC/ARM-NONE-EABI/6.2.1/INCLUDE-FIXED/ will be indexed
  Folder: C:/XILINX/SDK/2017.3/GNU/AARCH32/NT/GCC-ARM-NONE-EABI/ARM-NONE-EABI/INCLUDE/ will be indexed
  Folder: C:/XILINX/SDK/2017.3/GNU/AARCH32/NT/GCC-ARM-NONE-EABI/ARM-NONE-EABI/LIBC/USR/INCLUDE/ will be indexed
  Folder: C:/XILINX/SDK/2017.3/DATA/EMBEDDEDSW/LIB/BSP/STANDALONE_V6_4/SRC/ARM/CORTEXA9/ARMCC/ will be indexed
Discovering files...
cpptools/didChangeFolderSettings
textDocument/didOpen

  **Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.11.25503/INCLUDE**
  **Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.11.25503/ATLMFC/INCLUDE**
  Pr**ocessing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.15063.0/UM/**

sending compilation args for C:\USERS\PROJECTS\SW\XPF\XPFAO.CPP
  include: C:\Users\Projects\sw\osal\include
  include: C:\Users\Projects\sw\osal\include\soc_ep1
  include: C:\Users\Projects\sw\psp\include
  include: C:\Users\Projects\sw\psp\include\soc_ep1
  include: C:\Users\Projects\sw\qp\include
  include: C:\Users\Projects\sw\qpp\include
  include: C:\Users\Projects\sw\qpp\include\soc_ep1
  include: C:\Users\Projects\sw\safertos\core\include
  include: C:\Users\Projects\sw\safertos\zynq\include
  include: C:\Users\Projects\sw\safertos\zynq\include\soc_ep1
  include: C:\Users\Projects\sw\soc\include
  include: C:\Users\Projects\sw\soc\ep1\include
  include: C:\Users\Projects\sw\xpf\include
  include: C:\Users\Projects\sw\xpf\include\soc_ep1
  include: C:\Users\Projects\sw\zpf\include
  include: C:\Users\Projects\sw\zpf\include\soc_ep1
  include: C:\Xilinx\SDK\2017.3\gnu\aarch32\nt\gcc-arm-none-eabi\lib\gcc\arm-none-eabi\6.2.1\include
  include: C:\Xilinx\SDK\2017.3\gnu\aarch32\nt\gcc-arm-none-eabi\lib\gcc\arm-none-eabi\6.2.1\include-fixed
  include: C:\Xilinx\SDK\2017.3\gnu\aarch32\nt\gcc-arm-none-eabi\arm-none-eabi\include
  include: C:\Xilinx\SDK\2017.3\gnu\aarch32\nt\gcc-arm-none-eabi\arm-none-eabi\include\c++\6.2.1
  include: C:\Xilinx\SDK\2017.3\gnu\aarch32\nt\gcc-arm-none-eabi\arm-none-eabi\include\c++\6.2.1\arm-none-eabi
  include: C:\Xilinx\SDK\2017.3\gnu\aarch32\nt\gcc-arm-none-eabi\arm-none-eabi\include\c++\6.2.1\backward
  include: C:\Xilinx\SDK\2017.3\gnu\aarch32\nt\gcc-arm-none-eabi\arm-none-eabi\libc\usr\include
  include: C:\Xilinx\SDK\2017.3\data\embeddedsw\lib\bsp\standalone_v6_4\src\arm\cortexa9\armcc

  **include: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include**
  **include: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc\include**
  **include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um**
  **include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt**
  **include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared**
  **include: C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\winrt**

  stdver: --c++11

  **Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.15063.0/UCRT/**
  **Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.15063.0/SHARED/**

Checking for syntax errors: file:///c%3A/Users/Projects/sw/xpf/XpfAo.cpp
queue_update_intellisense for files in tu of: C:\USERS\PROJECTS\SW\XPF\XPFAO.CPP

  **Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.15063.0/WINRT/**

  Processing folder (recursive): C:/USERS/PROJECTS/SW/OSAL/INCLUDE/
  Processing folder (recursive): C:/USERS/PROJECTS/SW/PSP/INCLUDE/
  Processing folder (recursive): C:/USERS/PROJECTS/SW/QP/INCLUDE/
  Processing folder (recursive): C:/USERS/PROJECTS/SW/QPP/INCLUDE/
  Processing folder (recursive): C:/USERS/PROJECTS/SW/SAFERTOS/CORE/INCLUDE/
  Processing folder (recursive): C:/USERS/PROJECTS/SW/SAFERTOS/ZYNQ/INCLUDE/
  Processing folder (recursive): C:/USERS/PROJECTS/SW/SOC/INCLUDE/
  Processing folder (recursive): C:/USERS/PROJECTS/SW/SOC/EP1/INCLUDE/
  Processing folder (recursive): C:/USERS/PROJECTS/SW/XPF/INCLUDE/
  Processing folder (recursive): C:/USERS/PROJECTS/SW/ZPF/INCLUDE/
  Processing folder (recursive): C:/XILINX/SDK/2017.3/GNU/AARCH32/NT/GCC-ARM-NONE-EABI/LIB/GCC/ARM-NONE-EABI/6.2.1/INCLUDE/
  Processing folder (recursive): C:/XILINX/SDK/2017.3/GNU/AARCH32/NT/GCC-ARM-NONE-EABI/LIB/GCC/ARM-NONE-EABI/6.2.1/INCLUDE-FIXED/
  Processing folder (recursive): C:/XILINX/SDK/2017.3/GNU/AARCH32/NT/GCC-ARM-NONE-EABI/ARM-NONE-EABI/INCLUDE/
  Processing folder (recursive): C:/XILINX/SDK/2017.3/GNU/AARCH32/NT/GCC-ARM-NONE-EABI/ARM-NONE-EABI/LIBC/USR/INCLUDE/
  Processing folder (recursive): C:/XILINX/SDK/2017.3/DATA/EMBEDDEDSW/LIB/BSP/STANDALONE_V6_4/SRC/ARM/CORTEXA9/ARMCC/
  Discovering files: 5750 file(s) processed
  1 file(s) removed from database
Removed file: C:\USERS\PROJECTS\SW\XPF\XPFAO.CPP
errorSquiggles count: 5
Done discovering files.
Parsing open files...
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
  tag parsing file: C:\USERS\PROJECTS\SW\XPF\XPFAO.CPP
Done parsing open files.
cpptools/textEditorSelectionChange
Database safe to open

**Comment by bobbrow** [comment]
Could you try setting `"C_Cpp.default.compilerPath"` to `"C:\Xilinx\SDK\2017.3\gnu\aarch32\nt\gcc-arm-none-eabi\bin\gcc.exe"`? (I'm guessing the actual path based on what I see above).

**Comment by bobbrow** [comment]
We default to Visual Studio compilers on Windows if the "intelliSenseMode" is "msvc-x64" and compilerPath is not set.  Can you check the "intelliSenseMode" setting as well and make sure it's set to "clang-x64".

**Comment by rdlaner** [comment]
Ah, ok. So, I changed the compilePath to 'C:/Xilinx/SDK/2017.3/gnu/aarch32/nt/gcc-arm-none-eabi/bin/arm-none-eabi-g++.exe' and that ended up removing all of the VS files. However, I was still getting all of the random error squiggles. But, then I changed the intellisenseMode setting to "clang-x64" and that was what fixed all of the random error squiggles.
That's a little unintuitive since I'm working on a Windows machine. I assume needing to set the intellisenseMode to clang-x64 is so that it won't use the available Windows resources?

**Comment by bobbrow** [comment]
Would adding a "gcc-x64" mode remove the confusion?

**Comment by rdlaner** [comment]
Yes, I would find that more intuitive.

**Comment by bobbrow** [comment]
I added #2312 to track the intelliSenseMode addition.

**Comment by dsanz006** [comment]
How is #2312 related to having a single C_Cpp_properties.json file for the entire multi-root workspace? why is this issue closed?

**Comment by bobbrow** [comment]
We are using #2060 (your issue, I believe) to track that now.
