### ISSUE TITLE
launch.json

### ISSUE THREAD

**Issue by Sheshi-bit** [microsoft/vscode-cpptools#12291]
### Environment

- OS and version:
- VS Code:
- C/C++ extension:
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do '...'
4. See error...

### Debugger Configurations

```shell
launch.json
```

### Debugger Logs

```shell
launch.json
```

**Comment by browntarik** [comment]
Could provide more context to the error you are having?

1) What does the error say? Could you provide a screenshot?
2) When exactly are you experiencing the error?
