### ISSUE TITLE
Search freezes with cpptools enabled

### ISSUE THREAD

**Issue by dgloe-hpe** [microsoft/vscode-cpptools#12303]
Type: <b>Bug</b>

The search option in the sidebar is freezing for any search term I try, and never returns results. I used the extension bisect option to narrow it down to the cpptools extension causing the problem.

Extension version: 1.20.5
VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|32.00GB (2.24GB free)|
|Process Argv|--crash-reporter-id 705072a7-0786-4cdc-b0c7-96e51436c431|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
bdiig495:31013172
pythoncenvptcf:31043158
a69g1124:31046351
pythonprt:31039817
dwnewjupyter:31046869

```

</details>

**Comment by sean-mcmanus** [comment]
@dgloe-hpe What exactly do you mean by "the search option". I don't believe our extension runs when a VS Code search is done -- our extension doesn't hook into any API for that (if such an API even exists).

**Comment by dgloe-hpe** [comment]
It's a magnifying glass icon in the top left. With the extension enabled, the search hangs (I've waited for up to a few minutes with nothing returned). With the extension disabled, the search completes almost instantly.

**Comment by sean-mcmanus** [comment]
@dgloe-hpe You should file a bug on VS Code at https://github.com/microsoft/vscode/issues . Tell them our extension does not directly do anything when the Search UI is used so we don't believe it's our bug. It's possible VS Code itself could be changing its search behavior in response to our extension being installed.
