### ISSUE TITLE
[opensuse] language server crashes

### ISSUE THREAD

**Issue by linev** [microsoft/vscode-cpptools#12304]
### Environment

- OS and Version: openSUSE Tumbleweed, 64bit, 2024-04-28
- VS Code Version: 1.89.1
- C/C++ Extension Version: v1.20.5

Problem exists since a long time (~6 months)

### Bug Summary and Steps to Reproduce

Bug Summary:

The language server crashed. Restarting...

C++ logs:  [cpplog.txt](https://github.com/microsoft/vscode-cpptools/files/15308734/cpplog.txt)
debugger output: [debugger.txt](https://github.com/microsoft/vscode-cpptools/files/15308740/debugger.txt)

### Configuration and Logs

```shell
c_cpp_properties.json - not exists
C++ and debugger log attached
```

**Comment by sean-mcmanus** [comment]
@linev With 1.20.5, do you see a C/C++ Crash Call Stacks pane in the Output window after waiting 5 seconds after the crash?

**Comment by sean-mcmanus** [comment]
@linev Does the issue repro with 1.18.5 from November? Do you know which version it started reproing with?

**Comment by sean-mcmanus** [comment]
@linev From your logging, it appears that it might be crashing while tag parsing `tag parsing file: /home/linev/git/webgui/bindings/pyroot/cppyy/CPyCppyy/include/CPyCppyy/PyResult.h`. Can you try adding `"/home/linev/git/webgui/bindings/pyroot/cppyy/CPyCppyy/include/CPyCppyy": true` to your C_Cpp.files.exclude setting to get it to skip tag parsing that file and see if it stops crashing? (also, make sure that logging stops appearing).

**Comment by linev** [comment]
> Can you try adding "/home/linev/git/webgui/bindings/pyroot/cppyy/CPyCppyy/include/CPyCppyy": true to your C_Cpp.files.exclude setting to get it to skip tag parsing that file and see if it stops crashing? (also, make sure that logging stops appearing).

Adding such entry does not help. `....CPyCppyy/PyResult.h` still appears in list of parsed files and cpptools crashed.

> Does the issue repro with 1.18.5 from November? 

This version works! Also versions up to 1.19.1 are working. 
But trying to switch to 1.19.2 leads to crash.

**Comment by linev** [comment]
Problem remains, after version 1.19.1 it crashes for me. 
The only solution for me - downgrade plugin to 1.18.5

**Comment by linev** [comment]
Problem still exist - also with latest 1.21.0 version

**Comment by linev** [comment]
Problem resolved after  Tumbleweed upgrade and switching to `v1.22.2` of C/C++ for Visual Studio Code
