### ISSUE TITLE
Code analysis fails to get configured for non-open files the 1st time it's run

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#12313]
Do Run Code Analysis on All files in a project configured with a configuration provider.

Bug: The 1st time it's done, all the files are skipped because it thinks it doesn't have the configuration information. Using it a 2nd time and it'll work. We get the finishedRequestCustomConfig message before the didChangeCustomConfigurations message.

**Comment by Colengms** [comment]
Also applies to FAR and Rename.
