### ISSUE TITLE
Not All Doxygen Comment Blocks Supported

### ISSUE THREAD

**Issue by tristan-smith** [microsoft/vscode-cpptools#12316]
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.88.1
- C/C++ Extension Version: v1.20.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

**Bug Summary:**
My work's coding style guide specifies this format of Doxygen comment (No.4 on this page: [Doxygen Documentation](https://www.doxygen.nl/manual/docblocks.html)):

```
/***************************************************************************//**
* Example Code Block
*
*******************************************************************************/
```

Note the two forward slashes in the first line.

The VSCode C/C++ Extension doesn't seem to pick this up as a Doxygen comment:

Example with slashes:
![image](https://github.com/microsoft/vscode-cpptools/assets/31901577/340dca8d-a349-4314-b398-6491fffa85de)

Example without slashes:
![image](https://github.com/microsoft/vscode-cpptools/assets/31901577/71068ab5-7ffb-4fad-a98a-4854b0ddc772)

**Steps to reproduce:**
1. Create a comment block like the above example.
2. I also attached test.txt with the two examples.
[test.txt](https://github.com/microsoft/vscode-cpptools/files/15354863/test.txt)

**Expected behavior:**
I would expect any code block format specified on the [Doxygen documentation](https://www.doxygen.nl/manual/docblocks.html) to render properly like the second screenshot above.

Let me know if I can provide any other info! Thanks for your time and help with this.

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compileCommands": "${workspaceFolder}/build/compile_commands.json",
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

### Other Extensions

I also have CMake and NRF extensions installed.

**Comment by heartacker** [comment]
praise

**Comment by MikeWeller** [comment]
I would also like `@pre` (or `\pre`) (preconditions) to be visible. I see these as more important than `@note` which is currently displayed. In general it would be nice for all tags to be rendered (though there may need to be a list defined somewhere to determine how multiple tags are combined into a list/whatever).

**Comment by sean-mcmanus** [comment]
@tristan-smith Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.21.0

**Comment by tristan-smith** [comment]
Amazing, thank you @browntarik @bobbrow @sean-mcmanus !! Really appreciate the work.
