### ISSUE TITLE
If there are multiple functions with the same name,  cannot jump from the c++ header definition to the source file implementation

### ISSUE THREAD

**Issue by feng-xys** [microsoft/vscode-cpptools#12322]
### Environment

- OS and Version: 1.20.5
- VS Code Version: 1.89.1
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Jumping from the beginning to the cpp file lists all references instead of jumping to the cpp definition

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "M33",
            "includePath": [
                "${workspaceFolder}/**",
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "USE_HAL_DRIVER",
                "STM32H563xx",
            ],
            "compilerPath": "/opt/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-g++",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-arm"
        }
    ],
    "version": 4
}
```

**Comment by feng-xys** [comment]
![image](https://github.com/microsoft/vscode-cpptools/assets/79634743/995bc5e8-49a9-41dc-90a3-8514a99d839f)

**Comment by browntarik** [comment]
Could you provide a small example I could use to reproduce your issue on my machine?
