### ISSUE TITLE
Not registering a formatter for c files.

### ISSUE THREAD

**Issue by Alistair401** [microsoft/vscode-cpptools#1232]
C/C++ tools version 0.14.2
VSCode version 1.18

Attempting to format a c file raises the error: Sorry, but there is no formatter for c files installed.
Only started happening after updating both VSCode and C/C++ tools.

**Comment by bobbrow** [comment]
Hmm... This is this second report of that. We don't pop up that message. What other extensions do you have installed?

**Comment by Alistair401** [comment]
No other extensions installed

**Comment by bobbrow** [comment]
I looked at the source for VS Code and found where this message comes from.

I can only repro this when `"C_Cpp.formatting"` is set to `"Disabled"`.  Do you have this set in your settings.json file?

**Comment by Alistair401** [comment]
![image](https://user-images.githubusercontent.com/752182/32672706-fd9ebe48-c643-11e7-96e8-f80cb71f1410.png)

`"C_Cpp.formatting" ` is set to `"Default"`

**Comment by bobbrow** [comment]
That is the default setting, but do you have it overridden in your "User" or "Workspace" settings file?

The other possibility is that the extension is not actually running.  I don't know what OS you're using, but can you see if there is a "Microsoft.VSCode.CPP.Extension.*" process running or not?

**Comment by aseeon** [comment]
@bobbrow 
I think this might be connected to Issue https://github.com/Microsoft/vscode-cpptools/issues/1240

And might be a bit more general of a problem.

**Comment by Alistair401** [comment]
Apologies for the delay. 
Here are my user settings:
![image](https://user-images.githubusercontent.com/752182/32723417-4b976e88-c865-11e7-8e0d-843cdcdbb144.png)
I haven't made any changes to the C_Cpp.formatting option.

I'm on Windows, using task manager I can't see a Cpp Extension running but I may be looking in the wrong place.

**Comment by bobbrow** [comment]
Thanks @aseeon, I saw that issue this morning and have a fix for it.  @Alistair401, are you able to get it to work by applying the fix in #1240?

**Comment by rmrnc** [comment]
Same issue in VSCode on macOS. C formatting doesn't work after the update. It's not working with VSCode Insiders either

**Comment by bobbrow** [comment]
@rmrnc, can you try the fix in #1240?

**Comment by rmrnc** [comment]
Not sure whether the fix you've mentioned in #1240 was even meant to be applicable for this bug as well, but I tried anyway and it doesn't.

**Comment by rmrnc** [comment]
Sorry, our messages overlapped. No, unfortunately it doesn't.

**Comment by rmrnc** [comment]
Just to make sure, I've applied the fix  in `~/.vscode/extensions/ms-vscode.cpptools-0.14.2/out/src/LanguageServer/client.js` and this is how the file looks like now (lines 152-154)

```
if (vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length > 1) {
    storagePath = path.join(storagePath, serverName);
}
```

**Comment by bobbrow** [comment]
yes, that is the fix for #1240.  You're saying that this doesn't fix the formatter issue?  Do you have an instance of the extension's language server running (Microsoft.VSCode.CPP.Extension.darwin)?

**Comment by rmrnc** [comment]
Uh, I don't know why that is, but there appear to be multiple instances ...

```
$ ps aux | grep Microsoft.VSCode.CPP.Extension.darwin
xxx  78248   0.0  0.0  4546380    168   ??  S    Fri01PM   1:38.31 ~/.vscode/extensions/ms-vscode.cpptools-0.14.2/bin/Microsoft.VSCode.CPP.Extension.darwin
xxx  73977   0.0  0.0  4922016    168   ??  S    Fri10AM   1:44.85 ~/.vscode/extensions/ms-vscode.cpptools-0.14.2/bin/Microsoft.VSCode.CPP.Extension.darwin
xxx  97441   0.0  0.0  4276968   1032 s002  S+    2:20PM   0:00.00 grep Microsoft.VSCode.CPP.Extension.darwin
xxx  95100   0.0  1.0  4470928 163532   ??  S     1:05PM   0:50.78 ~/.vscode/extensions/ms-vscode.cpptools-0.14.2/bin/Microsoft.VSCode.CPP.Extension.darwin
```

**Comment by bobbrow** [comment]
Do you have multiple folders opened in VS Code?  This is expected if you have 3 folders open in VS Code.

**Comment by rmrnc** [comment]
Cleaned up (rebooted) so there is now only one instance running (and only one open folder). Still, no code formatting. And yes, applying the fix #1240 in `client.js` appears not to do the job on my box.

**Comment by bobbrow** [comment]
ok.  I can't seem to reproduce your problem. ☹️ Do you have any other extensions installed?

**Comment by aseeon** [comment]
@bobbrow just so you know - the fix in client.js fixed problems with formatting, at least on my machine that is

**Comment by sean-mcmanus** [comment]
Maybe @rmrnc modified the wrong client.js file? If you're on insiders you have to change the version under .vscode-insiders not the one under .vscode.

**Comment by rmrnc** [comment]
@bobbrow My VSCode Insiders has no other extension installed and I've stripped VSCode down to only one more extension which I really need to keep on working. 
@sean-mcmanus Nah, I've changed `client.js` in both `.vscode` extension folders, so ...

Ok, if I am the only one who is affected, so be it. Thank you all for your suggestions. Hope, it will work again on my box in a later release.

**Comment by rmrnc** [comment]
It just occured to me that the issue appears to be with `"C_Cpp.clang_format_style": "file"` and the location of the `.clang-format` file, although, I would have expected that the `C_Cpp.clang_format_fallbackStyle` would kick in when `.clang-format` couldn't be loaded. Where exactly is `.clang-format` supposed to be located starting with VSCode 1.18 (or is this a red-herring after all)?
Note: when using a standard style, e.g., `"C_Cpp.clang_format_style": "LLVM"`, fix #1240 works for me as well.

**Comment by sean-mcmanus** [comment]
@rmrnc Yes, the fallbackStyle should be used if the .clang-format file isn't found in the current or a parent folder. We haven't changed any of this behavior in a while.

**Comment by Strideradu** [comment]
Has the same problem for several days
C/C++ tools version 0.14.2
VSCode version 1.18.0

**Comment by totalamd** [comment]
Same problem for css
`Sorry, but there is no formatter for 'css'-files installed.`
VSCode version 1.18.1

**Comment by bobbrow** [comment]
Are you using version 0.14.3 of the extension?  We fixed #1240 which causes some of these errors, but there may be something else involved.

@totalamd `css` formatting support should be built in to VS Code.  The C/C++ extension does not supply a formatter for css.

**Comment by kihot122** [comment]
Same problem here, formating stopped working after recent update.
VSCode version 1.21.1
C++ extension version 0.15.0

**Comment by sean-mcmanus** [comment]
@kihot122 We're not able to repro a problem with formatting. Can you provide more repro details?

**Comment by kihot122** [comment]
Well, it's hard to describe really. Problem occurred after recent VS update to 1.21.1
Not re-installation nor deleting whole stuff from appdata solved the problem.
Looks like it has something to do with broken plugin configuration after VS patch since deleting VS plugins folder + clean reinstall solved it.

**Comment by aaravpandya** [comment]
faced the same problem. VS Code showed "there is no formatter for cpp-files installed.". Nothing worked(reinstallation, deleting appdata, above fixes) until i noticed that i had paused installation of vs 2017 in its installer. completed the installation and it started working fine.

**Comment by ZijunHui** [comment]
A similar situation happened to me as well. When I create a new file using ctrl-n and not save it on the disk, it gives me this error when formatting. When I do save it on the disk, it formats just fine. Is this a possible bug?

**Comment by sean-mcmanus** [comment]
@ZijunH Is this when the document name is "Untitled-1"? I don't even see a formatting option in that case. I don't think any of our extension's features work unless the file is first saved to disk.

**Comment by daltairwalter** [comment]
I am also seeing this error after updating to 0.17.0 - There is no document formatter for 'cpp'-files installed.

Immediately after update, I started seeing symantec errrors.  I am occasionally seeing this error now too: 

The language server crashed 5 times in the last 3 minutes. It will not be restarted.

I tried adding "C_Cpp.loggingLevel": "Information" to my settings, but I still don't see any log information - maybe I am looking in the wrong place.

**Comment by bobbrow** [comment]
To see the log, open the Output panel and select the "C/C++" log from the dropdown selector.

![image](https://user-images.githubusercontent.com/12818240/39768817-3763fbc4-529f-11e8-8ed0-e7b78c9caa02.png)

**Comment by daltairwalter** [comment]
The C/C++ log seems to go away when the language server crashes 5 times and isn't  restarted.  Other than Symantec Enpoint protection, I don't see a reason why it is crashing for me - though I don't see a log when it crashes either.

**Comment by bobbrow** [comment]
Really?  😕  I'll open a new issue for this and add you to it.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

**Comment by lorond** [comment]
> @ZijunH Is this when the document name is "Untitled-1"? I don't even see a formatting option in that case. I don't think any of our extension's features work unless the file is first saved to disk.

@sean-mcmanus I don't know about this extension, but some other extensions can format documents that was not saved on disk (like you say, "Untitled-n"). All you need to do is to set corresponding language manually via "Change Language Mode".

**Comment by lorond** [comment]
@bobbrow Issue still exist with documents that was not saved on disk. Version 0.25.0. Steps to  reproduce (via command palette):
1. New Untitled File
2. Change Language Mode -> C
3. Format Document

But if you save that document, problem will gone.
