### ISSUE TITLE
Missing hyperlink to file with error

### ISSUE THREAD

**Issue by afabri** [microsoft/vscode-cpptools#12329]
### Environment

- OS and Version:  Windows 11
- VS Code Version: 1.89.1
- C/C++ Extension Version: v1.20.5
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:

An error message concerning an included file, no hyperlink to the file is generated in the error message.  This is done when changing the kit to clang.

Steps to reproduce:
1. Clone  https://github.com/afabri/vscode-cmake
2.  go into directory Main and run `code .`
3. Configure 
4. Build

![image](https://github.com/microsoft/vscode-cpptools/assets/3263539/428274c0-19a5-4737-8c5f-aa5f36fa1153)

Expected behavior:
That I get a hyperlink to click on in order to get to the file and the line with the error.

### Configuration and Logs

```shell
No custom `c_cpp_properties.json`


{
  "os": "win32",
  "vscodeVersion": "1.89.1",
  "cmtVersion": "1.17.17",
  "configurations": [
    {
      "folder": "c:\\cgal\\users\\vscode-cmake\\Main",
      "cmakeVersion": "3.24.2",
      "configured": true,
      "generator": "Visual Studio 17 2022",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug",
      "Release",
      "MinSizeRel",
      "RelWithDebInfo"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 3,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "ALL_BUILD",
        "type": "UTILITY"
      },
      {
        "name": "ZERO_CHECK",
        "type": "UTILITY"
      },
      {
        "name": "main",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```
```


### Other Extensions

CMake Tools v1.17.17


### Additional context

_No response_

**Comment by sean-mcmanus** [comment]
@afabri Our extension doesn't generate that hyperlink. It's from VS Code: https://github.com/microsoft/vscode/issues
