### ISSUE TITLE
identifier "NULL" is undefined

### ISSUE THREAD

**Issue by alexmarkley** [microsoft/vscode-cpptools#1233]
Even though I've included the appropriate headers (and my code compiles without issue) I am getting red squiggles under standard C library symbols in my C++ code. Immediately obvious ones inside my codebase are "NULL", "fprintf", and "stderr"

![screenshot from 2017-11-10 07-38-45](https://user-images.githubusercontent.com/1566468/32659574-55e7918a-c5ed-11e7-91e5-c97cf6213173.png)

* Operating System and version
  * Fedora 26
* VS Code version and if you are using the Insiders build
  * About box says 1.17.2. Not an insiders build -- just using the regular yum repository.
* C/C++ extension version
  * 0.14.2
* Other extensions you installed and if the issue persists after disabling them
  * "CMake", "CMake Tools"
* step-by-step instructions to reproduce the issue
  * Open the project, observe red squiggles.
* A small code sample, zipped up project, or open source repo we can use to verify the bug
  * My code is available at this repository: https://github.com/markleybros/yer-face
* Relevant settings from your settings.json, c_cpp_properties.json, and/or launch.json files
  * "C_Cpp.intelliSenseEngine": "Default" (If I use "Tag Parser" I do not get the red squiggles.)
* Any log messages present in the Output window (use "C_Cpp.loggingLevel": "Information" in settings.json)
```
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: /usr/local/include/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /home/alex/Documents/MarkleyBros/yer-face/ will be indexed
Discovering files...
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/MarkerMapper.cpp
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /home/alex/Documents/MarkleyBros/yer-face/
  Indexing: 22862 file(s) processed
  Indexing: 1 file(s) removed from database
Unable to determine real path of /home/alex/Documents/MarkleyBros/yer-face/build/.cmserver.2988. Error = 2
Done discovering files.
Parsing open files...
Done parsing open files.
Checking for edits and parsing remaining files...
  Processing folder (recursive): /home/alex/Documents/MarkleyBros/yer-face/
  Parsing: 617 files(s) processed
Done parsing remaining files.
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/FaceTracker.cpp
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/Utilities.hpp
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/Utilities.cpp
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/MarkerTracker.hpp
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/MarkerTracker.cpp
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/EyeTracker.hpp
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/TrackerState.hpp
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/Metrics.hpp
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/MarkerType.hpp
Shutting down IntelliSense server: /home/alex/Documents/MarkleyBros/yer-face/src/MarkerMapper.cpp
Checking for syntax errors: file:///home/alex/Documents/MarkleyBros/yer-face/src/MarkerType.cpp
Shutting down IntelliSense server: /home/alex/Documents/MarkleyBros/yer-face/src/FaceTracker.cpp
Shutting down IntelliSense server: /home/alex/Documents/MarkleyBros/yer-face/src/Utilities.cpp
Shutting down IntelliSense server: /home/alex/Documents/MarkleyBros/yer-face/src/yer-face.cpp
Shutting down IntelliSense server: /home/alex/Documents/MarkleyBros/yer-face/src/MarkerTracker.cpp
Shutting down IntelliSense server: /home/alex/Documents/MarkleyBros/yer-face/src/MarkerType.cpp
Shutting down IntelliSense server: /home/alex/Documents/MarkleyBros/yer-face/src/Utilities.cpp
```

**Comment by sean-mcmanus** [comment]
It works for me. Can you delete your c_cpp_properties.json and create a new one? I'm seeing NULL getting defined at /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h on my Linux machine. I think you need to add more paths to your includePath.

**Comment by alexmarkley** [comment]
Oh that is super weird. Now that I have deleted the `c_cpp_properties.json` file, the problem has disappeared.

My initial creation of the file was due to following the "Show Fixes" recommendations which lead to automatically generating a `c_cpp_properties.json` file with a number of system include paths in it. (I did not manually include those paths, it found and recommended them itself.)

This time around, however, no `c_cpp_properties.json` file has been generated.

Is the behavior different between the current release of the extension and the previous release?


Anyway, the new behavior is working for me and I appreciate it. Thank you!

**Comment by bobbrow** [comment]
The behavior for discovering default includes did, in fact, change between 0.14.0 and 0.14.x.  For Linux and Mac, we now query the default include path directly from gcc/clang instead of basing it on the defaults for Ubuntu.  There are likely some differences between Ubuntu and Fedora that were unaccounted for previously.
