### ISSUE TITLE
A C/C++ extension process has crashed

### ISSUE THREAD

**Issue by oldnick85** [microsoft/vscode-cpptools#12347]
### Environment

- OS and Version: 22.04.1-Ubuntu
- VS Code Version: 1.89.1
- C/C++ Extension Version: Name: ms-vscode.cpptools 1.20.5

### Bug Summary and Steps to Reproduce

Bug Summary:
The language server crashed 5 times in the last 3 minutes. It will not be restarted.

Steps to reproduce:
1. Just open any cpp project

Expected behavior:
Not to crash

### Configuration and Logs

```shell
The crashing process name, date/time, signal, and call stack are below:

cpptools
03.06.2024, 20:43:50
SIGSEGV
cpp_intellisense::create_server(msvc::service_proxy_t&, std::shared_ptr<cpp_intellisense::server>&)+1197
intellisense_client::create_server()+344
intellisense_client::init()+49
…
thread_manager_t::do_work(unsigned long)+966
```

**Comment by sean-mcmanus** [comment]
@oldnick85 We believe this is https://github.com/microsoft/vscode-cpptools/issues/12201, if you have the Ryzen 3000 without the firmware update to fix the RDRAND bug.
