### ISSUE TITLE
Incorrect tokens highlight with "requires" clause with brackets

### ISSUE THREAD

**Issue by demidenko** [microsoft/vscode-cpptools#12356]
### Environment

- OS and Version: Ubuntu 24.04
- VS Code Version: 1.90.0
- C/C++ Extension Version: v1.20.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
This image contains basic example code
![изображение](https://github.com/microsoft/vscode-cpptools/assets/3053938/82c9d595-7543-4c97-a355-28f9b843bc22)

On this image one can see that some keywords colors are reset to white

Meanwhile if `requires` condition used greater instead of less then outer tokens highlighted correctly and only inner are reset to white
![изображение](https://github.com/microsoft/vscode-cpptools/assets/3053938/31c1b238-9d9b-49e8-a151-0aaeee7c7e4a)

In basic code if brackets after `requires` are missing (which will lead to compilation error) then highlight looks correct everywhere
![изображение](https://github.com/microsoft/vscode-cpptools/assets/3053938/04f7fc13-2cf4-4087-8e83-70afaec42621)

Steps to reproduce:
create cpp file with basic example code
```cpp
void fun(auto a) requires (true && 1 < 2 && true) {
	
}

int main() {
	for(int i=0; i <= 10; ++i)
		if(i % 2 == 0) fun(i);
	return 0;
}
```

Expected behavior:
correct colors on tokens `for`, `return`, `if`, `true`, `<=`, etc.

### Configuration and Logs

```shell
c_cpp_properties.json

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17"
        }
    ],
    "version": 4
}
```

### Additional context

Real code triggering this issue was
```cpp
auto& operator<<(ostream &o, ranges::range auto &&r) requires(!requires{o<<r;}) {
```
so situation is not synthetic

**Comment by sean-mcmanus** [comment]
Our extension doesn't implement the lexical highlighting in this case. It comes from VS Code and the Better C++ extension (which VS Code relies on). I believe the issue tracking this is https://github.com/jeff-hykin/better-cpp-syntax/issues/638 .
