### ISSUE TITLE
Option to remove _WIN32 define for Windows platform

### ISSUE THREAD

**Issue by rizickus** [microsoft/vscode-cpptools#1235]
In issue #185 Bob wrote:

>  _WIN32 and __MACH__ should be defined already on the relevant platforms, but if there are additional defines that you need to define, you can add them to the "defines" array in your c_cpp_properties.json file.

We have some common code for windows and embedded systems. When developing firmware for embedded systems having _WIN32 defined in #ifdef branches causes some extra includes, which are not available and rises errors about missing headers. Is it possible to remove _WIN32 define?

Suggestion: do not force _WIN32 define. Leave it as default for windows platform but add an option to remove it.

**Comment by bobbrow** [comment]
Thanks.  We are tracking this feature request with issue #1083

**Comment by andreaolivotto** [comment]
I'm very interested as well. I'm trying to use VS Code to work on an embedded project based on nrf52 platform. IntelliSense doesn't works as the _WIN32 define changes some include files. 

Here some lines from "nrf.h" form Nordic Semiconductor SDK:
```
#if defined(_WIN32)
    /* Do not include nrf specific files when building for PC host */
#elif defined(__unix)
    /* Do not include nrf specific files when building for PC host */
#elif defined(__APPLE__)
    /* Do not include nrf specific files when building for PC host */
#else
    /* Device selection for device includes */
    #if defined (NRF51)
        #include "nrf51.h"
        #include "nrf51_bitfields.h"
        #include "nrf51_deprecated.h"    
    #elif defined (NRF52810_XXAA)
        #include "nrf52810.h"
        #include "nrf52810_bitfields.h"
        #include "nrf51_to_nrf52810.h"
        #include "nrf52_to_nrf52810.h"
    #elif defined (NRF52832_XXAA) || defined (NRF52832_XXAB)
        #include "nrf52.h"
        #include "nrf52_bitfields.h"
        #include "nrf51_to_nrf52.h"
        #include "nrf52_name_change.h"
    #elif defined (NRF52840_XXAA)
        #include "nrf52840.h"
        #include "nrf52840_bitfields.h"
        #include "nrf51_to_nrf52840.h"
        #include "nrf52_to_nrf52840.h"    
    #else
        #error "Device must be defined. See nrf.h."
    #endif /* NRF51, NRF52810_XXAA, NRF52832_XXAA, NRF52832_XXAB, NRF52840_XXAA */
```

No problem for compiling the code using the makefile, though.

**Comment by sean-mcmanus** [comment]
@andreaolivotto You should be able to stop _WIN32 being defined by setting the compilerPath to a valid gcc/clang-based compiler that is executable on Windows (MinGW, WSL, etc.). You could also change the intelliSenseMode to "clang-x64" or "gcc-x64", but in that case you may have to manually add compiler-provided properties to the "defines" and "includePath" setting as well.

**Comment by gdeban** [comment]
@sean-mcmanus 
> @andreaolivotto You should be able to stop _WIN32 being defined by setting the compilerPath to a valid gcc/clang-based compiler that is executable on Windows (MinGW, WSL, etc.). You could also change the intelliSenseMode to "clang-x64" or "gcc-x64", but in that case you may have to manually add compiler-provided properties to the "defines" and "includePath" setting as well.

This does not work for me. I am having the same issue as @andreaolivotto even after changing the compiler path and intellisenseMode
```
"compilerPath": "C:/Keil_v5/ARM/ARMCC/bin/armcc.exe --c99 -c --cpu Cortex-M4.fp -D__MICROLIB -g -O0 --apcs=interwork --split_sections"
```
and
```
"intelliSenseMode": "gcc-x64"
```

_WIN32 is still seen as defined. Hovering over it displays the following tooltip:
```
#define _WIN32 1
```
No definition or declaration is found when using the context menu "go to ...".

**Comment by sean-mcmanus** [comment]
@gdeban It sounds like we may be failing to query the compiler (and falling back to a cl.exe compiler). Can you run the C/C++: Log Diagnostics command after opening a file and see what compiler and mode and include paths it's using? Or you could enable debug logging and see if the _WIN32 define is getting set by your compiler: https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md .

**Comment by gdeban** [comment]
@sean-mcmanus It is in fact falling back to an other compiler.
```
Compiler Path: C:\Program Files\LLVM\bin\clang.exe
```
I was just messing around without properly setting up the compiler, so I'll have to get this done before I can get more information from the debug logging option. It will certainly solve my issues. Thanks for the help!

**Comment by DigiTec** [comment]
If anyone else hits this, I was able to set clang-arm as the intellisenseMode and that fixed most of my problems. The clang compiler was pointing to one that was specified in an NDK of Android and was correct, but I still had _WIN32 until I changed the mode.

**Comment by sean-mcmanus** [comment]
Fixed for Linux/Mac/Windows targets with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0 , however, for other targets, we have a new issue at https://github.com/microsoft/vscode-cpptools/issues/6813 .
