### ISSUE TITLE
C++ stopped loading

### ISSUE THREAD

**Issue by sebsacuna** [microsoft/vscode-cpptools#12361]
## Environment
    OS and Version: Windows 11, 23H2
    VS Code Version: 1.90.0
    C/C++ Extension Version: v1.20.5

## Bug Summary
C++ extension does not activate and affects all the remaining extensions. This happens with several versions of C++ extensions and VS Code. It started when I installed Wireguard last Friday.

I've tried VS Code Insider 1.91, uninstalling and reinstalling everything. I attached the console output that appear when VS Code tries to activate the extension.

![image](https://github.com/microsoft/vscode-cpptools/assets/25981446/2fbda7f5-1b49-4086-b5a2-6d5883c6e46d)

The rest of the extensions work fine. However, as soon as C++ tries to activate, everything else stop working while C++ extensions gets stuck on the activation.

**Comment by sean-mcmanus** [comment]
VS Code itself activates our extension. If our extension has not been activated, then our code isn't involved in the failure. You should file an issue on VS Code at https://github.com/microsoft/vscode/issues , or possibly Wireguard if they're someone causing the failure.
