### ISSUE TITLE
"Now symbols found" with GB2312

### ISSUE THREAD

**Issue by hellspwj** [microsoft/vscode-cpptools#1236]
OS: Windows 7

VSCode version:
1.18
C/C++ extension:
0.14.2

"No symbols found"  When i use GB2312 encoding,when i use utf-8,it can be norma,I am working hard on my English .

**Comment by sean-mcmanus** [comment]
Most of our code assumes UTF-8 and we don't have a layer to convert from other encodings to UTF-8 yet. We plan to fix this, but we don't have an ETA. Our extension is still in "Preview" so we're not fully localized or world ready yet. https://github.com/Microsoft/vscode-cpptools/issues/414 is tracking this.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 . Let us know if you see any remaining bugs with non-UTF-8 encodings.
