### ISSUE TITLE
VS Code to Auto-detect language

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode-cpptools#12362]
### Feature Request

It will be nice if VS Code can auto detect the language, and use the appropriate compiler/SDK  just like what JetBrains IDE does.

**Comment by sean-mcmanus** [comment]
VS Code already auto-detects the programming language. Were you intending to make a feature request on VS Code or did you want our C/C++ extension to do something specific in regards to a compiler/SDK. The problem with C/C++ is that there are many different build systems. Our extension already does some auto-detection for cl.exe/clang/gcc.
