### ISSUE TITLE
Update `braces` to version 3.0.3

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#12363]
### Description

The NPM package `braces` fails to limit the number of characters it can handle, which could lead to Memory Exhaustion. In `lib/parse.js`, if a malicious user sends "imbalanced braces" as input, the parsing will enter a loop, which will cause the program to start allocating heap memory without freeing it at any moment of the loop. Eventually, the JavaScript heap limit is reached, and the program will crash.

### Recommendation

Upgrade braces from 3.0.2 to 3.0.3 to fix the vulnerability.
If you are using NPM 6 or above, you can run `npm audit fix` on your local machine to fix vulnerabilities. For more info, please visit https://docs.npmjs.com/cli/audit

**Comment by sean-mcmanus** [comment]
@bobbrow This was already fixed in https://github.com/microsoft/vscode-cpptools/pull/12317/files#diff-1c6916cb6b0e7cce91af9c264e269bb04365b00dd126935c767df68214f5e83bR1096 .

**Comment by sean-mcmanus** [comment]
@bobbrow The remaining issue was with .github/actions. Fixed at https://github.com/microsoft/vscode-cpptools/pull/12365
