### ISSUE TITLE
Display additional Doxygen tags in tooltip documentation

### ISSUE THREAD

**Issue by MikeWeller** [microsoft/vscode-cpptools#12384]
### Feature Request

It looks like VSCode only shows a certain subset of Doxygen tags/commands in the tooltip documentation, e.g. `\param`, `\note` are rendered, while others are not.

In particular I would also like `@pre` (or `\pre`) (preconditions) to be visible. I see these as more important than `@note` which is currently displayed. In general it would be nice for all tags to be rendered in some way (though there may need to be a list defined somewhere to determine how multiple tags of the same name are combined into a list vs. not, for example).

Another tag I would like visible is `@see`, e.g. `@see fooNon() for a version of this method that does not frob its input`

**Comment by bobbrow** [comment]
We allow you to select which tags you'd like to see in the structured comment tooltip if you'd like to see additional tags beyond the ones we chose as the defaults.

Can you try adding those tags to the `"C_Cpp.doxygen.sectionTags"` setting? It looks like we don't recognize "see" yet so no special header will be added to the tooltip, but we can use this issue as a reminder to add it.

![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/0aaad08f-27d8-4158-8f40-83cc1a9d1072)
![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/a6e1e596-ada7-489a-8bbe-f7d8c7e7f597)

**Comment by MikeWeller** [comment]
@bobbrow ah, great! Yes this solves the issue with `pre`, so for me this is now a relatively minor issue with `see` not being recognized (and I guess there may be other official commands in https://doxygen.nl/manual/commands.html that people would want, though I haven't reviewed the list)

**Comment by bobbrow** [comment]
You can also try setting `"C_Cpp.simplifyStructuredComments"` to false and it will do a more generic listing of all tags.

![image](https://github.com/microsoft/vscode-cpptools/assets/12818240/ab2b1763-70b0-405a-8de3-35d1a1428be7)

**Comment by sean-mcmanus** [comment]
@MikeWeller Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.21.1
