### ISSUE TITLE
Database may randomly have incorrect symbols after Close All Editors (without saving) is done

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#12380]
Due to VS Code issue https://github.com/microsoft/vscode/issues/215474 and possibly some bug with our extensions handling of that scenario. I reproed it with 1.20.5/1.21.0 (it might require using Ctrl+Left arrow to re-open the closed files right after their closed, I'm not sure since the repro is random).

Reload window doesn't fix the issue, but anything that triggers a re-tag parse of the affected files would fix it.

**Comment by bobbrow** [comment]
What is the correct behavior here though?  Should we revert the unsaved changes, or keep them in the database?  It's not entirely clear to me as I can see a case made for either outcome.  Whichever way though, it should be consistent, and hopefully the VS Code bug will address the inconsistency.

**Comment by sean-mcmanus** [comment]
The VS Code fix for https://github.com/microsoft/vscode/issues/215474 should cause this to no longer repro.
