### ISSUE TITLE
Have installed C/C++ extension but its not working as expected

### ISSUE THREAD

**Issue by basava157** [microsoft/vscode-cpptools#12383]
Hi Team,

I have installed C/C++ extension in remote desktop and its showing as "Extension is enabled on SSH : IP address'.
But the issue is when we start browsing code its not working as expected. when we click on "Go to definition/declaration" it will struck and always showing like loading only. 

No feature working for browse code. So please help on this.

**Comment by sean-mcmanus** [comment]
@basava157 There might be some problem with the database. Can you set C_Cpp.loggingLevel to "Debug" and look in the C/C++ logging window for any database error messages? Also, can you set `C_Cpp.default.browse.databaseFilename` to something like `"${workspaceFolder}/.vscode/vc.db"` to verify that the database file can be created (it might be trying to create it at an invalid location).

**Comment by basava157** [comment]
Log generated by C/C++ extension output window content:
"Warning: Expected file /home/basavaraj.m/.vscode-server/extensions/ms-vscode.cpptools-1.20.5/bin/libc.so is missing."

It looks in that home direcory inside .vscode folder there is no db file.
sh-4.4$ ls .vscode/
extensions.json
sh-4.4$ cd .vscode/
sh-4.4$ ls
extensions.json


Note : one more observation is when we reconnect it will show every time like : "The C/C++ extension installed does not match your system."

Installed extension pack details in remote machine are :
sh-4.4$ cd $HOME/.vscode-server/extensions/
sh-4.4$ ls
arzg.eclipse-0.2.0    extensions.json  ms-vscode.cmake-tools-1.18.42  ms-vscode.cpptools-extension-pack-1.3.0
davidanson.vscode-markdownlint-0.55.0  mitaki28.vscode-clang-0.2.4   **ms-vscode.cpptools-1.20.5**  ramyaraoa.show-offset-0.0.4

The machine details are:
The local machine is Microsoft Windows10 pro
The remote machine is ubuntu 18.04 Linux.

**Comment by sean-mcmanus** [comment]
@basava157 You have an extension that is for the wrong OS installed. You should uninstall your extension, reload window, and then install the Linux version of the extension in the remote instance. The marketplace is supposed to handle this correctly. Did you install it via the vsix on the GitHub page?

**Comment by basava157** [comment]
Ya correct, I have installed manually through VSIX / command prompt. As you suggested if its not correct version means, could you please suggest which is the compatible version for this platform.  Automatics installation is not working from extension option, so tried doing manually.

If I try to install Linux extension getting below error.

sh-4.4$ code --install-extension ms-vscode.cpptools-1.20.5\@linux-x64.vsix 
Installing extensions on SSH: 10.221.31.74...
Error: End of central directory record signature not found. Either not a zip file, or file is truncated.
    at y (/home/basavaraj.m/.vscode-server/cli/servers/Stable-611f9bfce64f25108829dd295f54a6894e87339d/server/out/vs/server/node/server.main.js:105:25790)
    at /home/basavaraj.m/.vscode-server/cli/servers/Stable-611f9bfce64f25108829dd295f54a6894e87339d/server/out/vs/server/node/server.main.js:105:27228
    at /home/basavaraj.m/.vscode-server/cli/servers/Stable-611f9bfce64f25108829dd295f54a6894e87339d/server/node_modules/yauzl/index.js:40:7
    at /home/basavaraj.m/.vscode-server/cli/servers/Stable-611f9bfce64f25108829dd295f54a6894e87339d/server/node_modules/yauzl/index.js:190:5
    at /home/basavaraj.m/.vscode-server/cli/servers/Stable-611f9bfce64f25108829dd295f54a6894e87339d/server/node_modules/yauzl/index.js:712:5
    at /home/basavaraj.m/.vscode-server/cli/servers/Stable-611f9bfce64f25108829dd295f54a6894e87339d/server/node_modules/yauzl/fd-slicer.js:33:7
    at callback (/home/basavaraj.m/.vscode-server/cli/servers/Stable-611f9bfce64f25108829dd295f54a6894e87339d/server/node_modules/graceful-fs/polyfills.js:138:21)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:688:5)
Failed Installing Extensions: vscode-remote://ssh-remote%2B10.221.31.74/home/basavaraj.m/personal/ms-vscode.cpptools-1.20.5%40linux-x64.vsix
sh-4.4$

**Comment by sean-mcmanus** [comment]
@basava157 It sounds like you may be installing the vsix incorrectly on the remote machine. You should either `scp` (or whatever copy mechanism) the vsix to the remote machine or use the "Show Local" button that appears after using the install extension command on the remote machine (if that doesn't work and gets stuck, then the scp should be used instead).
