### ISSUE TITLE
After setting win11 folder with file name case sensitive, IntelliSense can't parse symbol

### ISSUE THREAD

**Issue by Obelisk90** [microsoft/vscode-cpptools#12399]
### Environment

- OS and Version: Win11
- VS Code Version: 1.90.2
- C/C++ Extension Version: 1.20.5
- If using SSH remote, specify OS of remote machine: No

### Bug Summary and Steps to Reproduce

Bug Summary:
After setting win11 folder with file name case sensitive, IntelliSense can't parse symbol

Steps to reproduce:
1. create a new folder in Win11
2. set the new folder as case sensitive: fsutil.exe file queryCaseSensitiveInfo <path>
3. add source file to this folder and open it with vscode

Expected behavior:
IntelliSense can parse symbol of the source file

### Configuration and Logs

```shell
no useful log.
```

**Comment by Obelisk90** [comment]
After set `"C_Cpp.caseSensitiveFileSupport": "enabled"`, and restart vscode this issue is gone, thank you

**Comment by zhuliking** [comment]
thanks. This issue also block me a long time.
