### ISSUE TITLE
launch: program '/home/../a.out' does not exist

### ISSUE THREAD

**Issue by yyxiongzju** [microsoft/vscode-cpptools#124]
It is so frustrating to use visual studio code for compiling c++ code on linux, and Mac. Here is my launch.json on Ubantu,
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (GDB)",
            "type": "cppdbg",
            "request": "launch",
            "miDebuggerPath": "/usr/bin/gdb",
            "targetArchitecture": "x64",
            "program": "${workspaceRoot}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": []
        },
        {
            "name": "C++ Attach (GDB)",
            "type": "cppdbg",
            "request": "launch",
            "miDebuggerPath": "/usr/bin/gdb",
            "targetArchitecture": "x64",
            "program": "${workspaceRoot}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "processId": 100000
        }
    ]
}
tasks.json
{
    "version": "0.1.0",
    "command": "g++",
    "args": ["HelloVS.cpp"],
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(._):(\d+):(\d+):\s+(warning|error):\s+(._)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
}
When I click the button "start to debug", it shows that a.out file does not exist.
Can someone help me out?

**Comment by delmyers** [comment]
@yyxiongzju Are you attempting to compile your application? VsCode does not have a project system, so you have to either compile at the command line, or create a build task. There is documentation about how to do it [here](https://code.visualstudio.com/Docs/editor/tasks). Here is an example build task for compiling GCC:

``` javascript
{
    "version": "0.1.0",
    "command": "gcc",
    "args": ["-Wall", "helloWorld.c", "-o", "helloWorld"],
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
}
```

**Comment by yyxiongzju** [comment]
Thank you for your help. I did construct a build task, tasks.json, like what I posted in the question. It did not help anyway. Any insight about this problem?

**Comment by jacdavis** [comment]
Did you also add the prelaunch property to automatically execute your build task when you start debugging?
