### ISSUE TITLE
Constants defined c++ highlight not working

### ISSUE THREAD

**Issue by paulotovo** [microsoft/vscode-cpptools#12401]
### Environment

- OS and Version: Linux Mint 21.3
- VS Code Version: 1.90.1
- C/C++ Extension Version: 1.20.5
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary: In a .h file with code snippet surrounded by a constant definition, it is not displayed (highlight) correctly whether the constant is defined or not.

Steps to reproduce:

`#undef TEST_CONST
#ifdef TEST_CONST
  #define XXXXXXXX  10
#endif

#define TEST_CONST
#ifdef TEST_CONST
  #define XXXXXXXX  10
#endif`

Expected behavior:

The isolated code by the constant definition should appear highlighted if the constant is defined, otherwise it should appear disabled.

![image](https://github.com/microsoft/vscode-cpptools/assets/18484053/d0617501-fd04-443f-9d7c-c9c8e1b30372)

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
            ],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by browntarik** [comment]
Could you provide the output of the C/C++: Log Diagnostics function when you open this file? 

Do you have your C_Cpp.dimInactiveRegion setting set? If so, what is the current value?

Is IntelliSense working correctly otherwise?
