### ISSUE TITLE
Undefined reference to `WinMain`

### ISSUE THREAD

**Issue by Sabareesh-07** [microsoft/vscode-cpptools#12406]
I get this error when I try to run a simple C code in vs code![Screenshot 2024-06-22 184412.png](https://github.com/microsoft/vscode-cpptools/assets/173551025/c3bacc25-9f11-4cba-84ed-69aeff9c9b78)

**Comment by browntarik** [comment]
Could you share the code you are attempting to run?

The error "undefined reference to 'WinMain' is usually related to missing a correct implementation of the main function in your code (see below):
```
int main() 
{
    return 0
}
```

**Comment by Sabareesh-07** [comment]
> Could you share the code you are attempting to run?
> 
> The error "undefined reference to 'WinMain' is usually related to missing a correct implementation of the main function in your code (see below):
> ```
> int main() 
> {
>     return 0
> }
> ```

I get same error ![Screenshot 2024-06-24 224033.png](https://github.com/microsoft/vscode-cpptools/assets/173551025/9648603a-44c3-4935-96c6-2b7915a127b3)

**Comment by sean-mcmanus** [comment]
@Sabareesh-07 Did you save your changes to test.c? It appears unsaved in your screenshot.

**Comment by Sabareesh-07** [comment]
My bad 😶 i thought file will get saved when i click run😅.
Thanks for your help 🫡

**Comment by browntarik** [comment]
Closing this issue as resolved. Please let us know if you any further concerns.
