### ISSUE TITLE
Command 'C_Cpp.ConfigurationEdit' not found.

### ISSUE THREAD

**Issue by gainskills** [microsoft/vscode-cpptools#1240]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0 with XCode 9.1
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Go|luk|0.6.67
python|ms-|0.8.0
cpptools|ms-|0.14.2

Log in VSCode dev tools:
I found that the issue had been reported and fixed on windows platform (https://github.com/Microsoft/vscode-cpptools/issues/384) , but it should still exist in MAC OS.

[ms-vscode.cpptools] Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
	at DefaultClient.createLanguageClient (/Users/kz/.vscode/extensions/ms-vscode.cpptools-0.14.2/out/src/LanguageServer/client.js:152:46)
	at new DefaultClient (/Users/kz/.vscode/extensions/ms-vscode.cpptools-0.14.2/out/src/LanguageServer/client.js:92:35)
	at Object.createClient (/Users/kz/.vscode/extensions/ms-vscode.cpptools-0.14.2/out/src/LanguageServer/client.js:71:12)
	at new ClientCollection (/Users/kz/.vscode/extensions/ms-vscode.cpptools-0.14.2/out/src/LanguageServer/clientCollection.js:19:42)
	at Object.activate (/Users/kz/.vscode/extensions/ms-vscode.cpptools-0.14.2/out/src/LanguageServer/extension.js:41:15)
	at util.readFileText.then.catch.then (/Users/kz/.vscode/extensions/ms-vscode.cpptools-0.14.2/out/src/main.js:119:28)
	at <anonymous>
e.onUnexpectedError @ workbench.main.js:sourcemap:10
(anonymous) @ workbench.main.js:sourcemap:10
e.onUnexpectedError @ workbench.main.js:sourcemap:9
o @ workbench.main.js:sourcemap:9
e.$onUnexpectedError @ workbench.main.js:sourcemap:9
e.invoke @ workbench.main.js:sourcemap:9
e._invokeHandler @ workbench.main.js:sourcemap:9
e._receiveOneMessage @ workbench.main.js:sourcemap:9
(anonymous) @ workbench.main.js:sourcemap:9
(anonymous) @ workbench.main.js:sourcemap:9
e.invoke @ workbench.main.js:sourcemap:9
e.fire @ workbench.main.js:sourcemap:9
(anonymous) @ workbench.main.js:sourcemap:9
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
workbench.main.js:sourcemap:9 command 'C_Cpp.ConfigurationEdit' not found
e.doShow @ workbench.main.js:sourcemap:9
e.show @ workbench.main.js:sourcemap:9
e.resume @ workbench.main.js:sourcemap:9
(anonymous) @ workbench.main.js:sourcemap:10
e.invoke @ workbench.main.js:sourcemap:9
e.fire @ workbench.main.js:sourcemap:9
(anonymous) @ workbench.main.js:sourcemap:9

**Comment by aseeon** [comment]
@hanbaobao2005 

It re-appeared on Windows 10 64 bit too. 

Editor:
Version 1.18.0
Commit dcee2202709a4f223185514b9275aa4229841aa7
Architecture x64

Extension:
cpptools: 0.14.2

![C_Cpp.ConfigurationEdit not found on windows](https://i.imgur.com/1YWWQwM.png)

**Comment by bobbrow** [comment]
I have a fix for this.  Until the fix comes out, you can replace line 152 in that client.js file from this:
`        if (vscode.workspace.workspaceFolders.length > 1) {`
to this:
`        if (vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length > 1) {`

**Comment by aseeon** [comment]
Just wanted to confirm the fix indeed worked fine, and alleviated all of my issues!

**Comment by gainskills** [comment]
@bobbrow  Your solutions works, Thanks,

**Comment by Alistair401** [comment]
@bobbrow the fix you've suggested has fixed it for me

**Comment by bobbrow** [comment]
This should be fixed with version 0.14.3

**Comment by hamaney** [comment]
This issue happens also if u try to edit `c_cpp_properties.json` file while it is staged by git.
