### ISSUE TITLE
Found a Spelling mistake in the code snippet in time_t description

### ISSUE THREAD

**Issue by user23052036** [microsoft/vscode-cpptools#12414]
### Environment

- OS and Version: Microsoft Windows Version 23H2 (OS build 22631.3737)
- VS Code Version:  1.90.2
- C/C++ Extension Version: v1.20.5

### Bug Summary and Steps to Reproduce

Bug Summary: When i am making a c file and including time.h library. Inside the main function when i am declaring the data type (time_t) is shows a code snippet just beside it, and it has a spelling mistake "really" is misspelled as "royally". Below i am providing the screen shots to better understand the problem.

Steps to reproduce:
1. create a c file
2. include basic headers files like stdio.h and time.h ... and inside main function type time_t and it will show a description beside it
3. In that description "really" is misspelled as "royally"
![Screenshot 2024-06-25 131431](https://github.com/microsoft/vscode-cpptools/assets/155566244/284da480-a482-481e-ab2a-d5f913b6cbf1)
![Screenshot 2024-06-25 131447](https://github.com/microsoft/vscode-cpptools/assets/155566244/2707b301-5d98-4672-93cb-5524a431a495)

### Configuration and Logs

```shell
c_cpp_properties.json file below

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c23",
            "cppStandard": "gnu++23",
            "intelliSenseMode": "windows-gcc-x86"
        }
    ],
    "version": 4
}

c/c++: Log Diagnostics :

  Standard Version: c23
    IntelliSense Mode: windows-gcc-x86
    Other Flags:
        --gcc
        --gnu_version=60300
Total Memory Usage: 53 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 1239
```

**Comment by bobbrow** [comment]
Hi @user23052036,

We don't own these headers. You would need to report this to the owners of the compiler you're using.  Though the word "royally" can be used to mean "really" in English, so the usage looks ok to me.
