### ISSUE TITLE
strdup missing from intellisense

### ISSUE THREAD

**Issue by Altomixik** [microsoft/vscode-cpptools#12411]
### Feature Request

The strdup() function does not appear in intellisense suggestions. Minor issue but still annoying.

**Comment by browntarik** [comment]
You must include the string.h header for IntelliSense to present it as a suggestion (see below):

![image](https://github.com/microsoft/vscode-cpptools/assets/111317156/ebd78027-c0d3-4c26-a89a-c00cc163aeaa)

![Screenshot 2024-06-24 094431](https://github.com/microsoft/vscode-cpptools/assets/111317156/ce8784f5-64a8-4b4b-9872-1403bad7575e)

Do you still face this issue while having #include <string.h> at the beginning of your file?

**Comment by Altomixik** [comment]
The issue with missing strdup() intellisense persists even with the
string.h library included. All other functions appear as normal.

**Comment by bobbrow** [comment]
It's possible you did not set the language mode for C23. Can you run the "Edit Configurations (JSON)" command and check what the "cStandard" is set to?

**Comment by bobbrow** [comment]
It sounds like maybe your compiler doesn't support C23.  You might need to upgrade to a newer version.  Which MinGW version are you using?
