### ISSUE TITLE
launch: program '...' does not exist. But it does.

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vscode-cpptools#1241]
Do you know what could cause such a problem? Uncustomized VS Code 18.0 with CMakeTools and CppTools installed. 2 file project, CMakeLists.txt and Mainn.cpp, fails to debug. The CppTools extension cannot find the executable, but it seems to me it very much is there (see File Explorer sidebar).

![screenshot](https://user-images.githubusercontent.com/9763499/32697358-a7fc6d66-c786-11e7-87bb-71ea549abc13.png)

**Comment by LeThiHyVong** [comment]
It seems like CppTools still use workspaceRoot instead of workspaceFolder, my c_cpp_properties.json doesn't work if I change workspaceRoot to workspaceFolder.

**Comment by MathiasMagnus** [comment]
Neither does launch.json. I tried both workspaceRoot and workspaceFolder, but none work. Would be nice to hear from the extension dev guys. I guess they must be swamped with the most esoteric issues posted as a result of this change.

**Comment by bobbrow** [comment]
@MathiasMagnus, you are missing the `$` in front of the `${workspaceFolder}` variable for the "program" property. 😉
