### ISSUE TITLE
Ability to exclude files from intellisense

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode-cpptools#12421]
### Feature Request

I have a project that works fine with intellisense except for one enormous file which is 200k lines long (it's generated). If I open that file than the `cpptools` process hits 100% CPU and never goes back.

It would be really helpful to have a feature like `C_Cpp.codeAnalysis.exclude` or `C_Cpp.files.exclude` but that works for intellisense, like `C_Cpp.intellisense.exclude`.

**Comment by Colengms** [comment]
Hi @Timmmm .  Thank you the suggestion.

One possible solution, which may or may not work for you, might be to surround the contents of the file with:

```
#ifndef __INTELLISENSE__
#endif
```

The `__INTELLISENSE__` macro is defined by the IntelliSense engine, but wouldn't be defined when you compile.
