### ISSUE TITLE
Debug C code

### ISSUE THREAD

**Issue by adiarbili** [microsoft/vscode-cpptools#1242]
Hi,
I'm trying to debug c code on Ubuntu 17.04 32 bit but it doesn't work.
Does C/C++ extensions support 32 bit?

**Comment by sean-mcmanus** [comment]
The debugger is supposed to work on 32-bit Linux. Is it not? The language service process only works on 64-bit Linux. Oh...I think the language service crashing on 32-bit is probably causing the entire extension to get unloaded, including the debugger part.

**Comment by Dean-Coakley** [comment]
I am experiencing the same issues but I feel like my configuration may be the problem.

In my launch.json I have the following that I feel is likely incorrect for C:
```
"name": "(gdb) Launch",
"type": "cppdbg"
```

**Comment by sean-mcmanus** [comment]
@Dean-Coakley That configuration appears to be missing fields. Did you generate it via the Add Configuration button?

**Comment by Dean-Coakley** [comment]
@sean-mcmanus Oh no, sorry I misled you. I was guessing `cppdbg` could be wrong for a plain c project?
Here's my entire file which was generated from the add configuration button if it helps:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/dean.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

```

**Important EDIT** I also noticed the OP is on 32bit, just thought I should clarify I am having this issue on 17.04 64bit

**Comment by pieandcakes** [comment]
@Dean-Coakley Nope. that's the correct `type`. Did you specify `-g` flag when compiling? You need to do that to include symbols else the debugger doesn't have enough information.

**Comment by Dean-Coakley** [comment]
@pieandcakes I didn't specify the -g flag actually! After some more messing about I see to have gotten it running.
Is this debug output normal?
```
Type "apropos word" to search for commands related to "word".
=cmd-param-changed,param="pagination",value="off"
Stopped due to shared library event (no libraries added or removed)
Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.
Breakpoint 1, 0x000055555555468e in main ()
The program '[projectdir-hidden]/dean.out' has exited with code 0 (0x00000000).
```

**Comment by pieandcakes** [comment]
@adiarbili Please make sure you specified the `-g` flag when compiling.

**Comment by Dean-Coakley** [comment]
@pieandcakes I'm ashamed to admit you are correct that I forgot the `-g` flag.

To compile and run/run with debug. I have to do `cmd+shift+p` -> run task -> build C, `F5`. Is this really the best I can do workflow wise? Surely not?

**Comment by adiarbili** [comment]
@pieandcakes that works like a charm!!!
I have three questions:
1. Why do we need the -g for?
2. Where did you read about it? 
3.I compiled the C code on the terminal of VSC: " gcc hello.c -g". Is there another way?

Thanks for everyone!!!

**Comment by pieandcakes** [comment]
@Dean-Coakley @adiarbili Instead of compiling in the terminal window, you can create a task.json with your build command and add a `"preLaunchTask"` to your launch.json that will call the task before it starts debugging. To find out more about creating tasks, I can point you to the VS Code documentation on it [here](https://code.visualstudio.com/Docs/editor/tasks).

@adiarbili `-g` during compilation includes debugging information in the final executable (or symbol library).  You can read about it by running `man gcc` from a Linux prompt or searching the internet. I looked at it [here](https://linux.die.net/man/1/gcc). Without debugging information, the debugger doesn't know how to debug your executable in a meaningful way.

**Comment by adiarbili** [comment]
@pieandcakes Thanks a lot!!!!
