### ISSUE TITLE
Disable pre-release toasts

### ISSUE THREAD

**Issue by rongxin-liu** [microsoft/vscode-cpptools#12438]
### Feature Request

Would it be possible to have a setting that allows users to disable pre-release toasts like this one?
![toast](https://github.com/microsoft/vscode-cpptools/assets/10591665/2526344e-8d68-4a9c-87c2-60c78a952562)

In the educational context, many students use Codespace as their standardized online IDE. However, they rarely know what pre-release extensions would benefit them and might be distracting in most cases.

**Comment by rongxin-liu** [comment]
cc @dmalan

**Comment by sean-mcmanus** [comment]
The user would still have to set the setting though, right? Or are they getting the setting from some shared file?

We could also add a "More info" button that explains when the pre-release version should be used.

**Comment by dmalan** [comment]
In our educational use case, the student gets the setting from a common `.devcontainer.json` file. For instance, we set a number of C/C++ settings via key/value pairs like https://github.com/cs50/codespace/blob/44fa8e1811fddac4b9532c9582ff10c6b4a5423a/devcontainer.json#L47-L55. 

Ideally, then, there'd be a similar setting via which we could suppress any prompts to switch away from the defined configuration, so that students don't stray from a standardized environment. 

Thank you for considering!

**Comment by sean-mcmanus** [comment]
@dmalan Could you elaborate on "suppress any prompts to switch away from the defined configuration"? Are you wanting the setting to be more general or apply to other scenarios or just this one?

**Comment by dmalan** [comment]
Ah, just this one, ideally to suppress this toast, so that students don't opt into pre-releases:

![Screenshot 2024-07-04 at 8 05 28 PM](https://github.com/microsoft/vscode-cpptools/assets/788678/d28a149e-6a55-4502-a991-45be92561acb)

**Comment by sean-mcmanus** [comment]
@dmalan I have a potential fix (pending review on Monday) at https://github.com/microsoft/vscode-cpptools/pull/12447 that just checks the extensions.ignoreRecommendations setting.

**Comment by dmalan** [comment]
Oh that sounds great, thanks very much!

**Comment by sean-mcmanus** [comment]
@dmalan Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.21.1 (although you'll have to wait till later this week for the 1.21.2 non-prerelease version).

**Comment by dmalan** [comment]
Thanks so much, @sean-mcmanus, much appreciated!

**Comment by sean-mcmanus** [comment]
@dmalan Now it's in non-pre-release: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.21.2

**Comment by dmalan** [comment]
Thank you, @sean-mcmanus!
