### ISSUE TITLE
SystemC 2.3.2 on Xcode 9.1 Semantic Issue: No member named 'gets' in namespace 'std' in systemc.h

### ISSUE THREAD

**Issue by Tool007** [microsoft/vscode-cpptools#1243]
Hello, 

first of all I am new in GitHub.
I am useing a Mac OS X 10.12.6 and installed Xcode 9.1 also downloaded the SystemC 2.3.2 also Installed Command Line Tool.
I allready update my GCC to version 7.1.0:
```
Users-MBP:~ user$ gcc --version
gcc (GCC) 7.1.0
```
Command Line Tool:
<img width="794" alt="bildschirmfoto 2017-11-12 um 16 09 22" src="https://user-images.githubusercontent.com/12443170/32700372-60e14cec-c7c4-11e7-80a9-a28c536f3f9d.png">
```
Users-MBP:/ user$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
Users-MBP:/ user$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 9.0.0.0.1.1504363082
volume: /
location: /
install-time: 1510133759
groups: com.apple.FindSystemFiles.pkg-group 
Users-MBP:/ user$ 
```
If I want to run a "Hello World" program:
```
// All systemc modules should include systemc.h header file
#include "systemc.h"
// Hello_world is module name
SC_MODULE (hello_world) {
  SC_CTOR (hello_world) {
    // Nothing in constructor
  }
  void print_hello() {
    //Print "Hello World" to the console.
    cout << "Hello World.\n";
  }
};
// sc_main in top level function like in C++ main
int sc_main(int argc, char* argv[]) {
  hello_world hello("HELLO");
  // Print the hello world
  hello.print_hello();
  return(0);
}
```
... I am getting allways this ERROR:
```
Semantic Issue Group
/Library/SystemC/Current/include/systemc.h:135:16: No member named 'gets' in namespace 'std'.
```
I also tried to rename `using std::gets; ` or to command out this linke like here:

I tried to rename:  `using std::fgets;`
I tried to command out this line  `//  using std::gets;`
But nothing helps...

https://ibb.co/j2ro8G
<img width="1658" alt="bildschirmfoto 2017-11-12 um 15 52 33" src="https://user-images.githubusercontent.com/12443170/32700195-06021cd6-c7c2-11e7-807f-68345a0b0f0e.png">
Also if I run my code in "Terminal" with this line I am getting an ERROR
```
wlan-141-23-139-15:objdir user$ sudo g++ -I. -I$SYSTEMC_HOME/include -L. -L$SYSTEMC_HOME/lib-linux64 -Wl,-rpath=$SYSTEMC_HOME/lib-linux64 -o main /Users/user/Documents/xCode/WAD/MultiCoreSystem/VL01/VL001/VL001/main.cpp -lsystemc -lm
In file included from /Users/user/Documents/xCode/WAD/MultiCoreSystem/VL01/VL001/VL001/main.cpp:2:0:
/Library/SystemC/systemc-2.3.2//include/systemc.h:120:16: Fehler: »std::gets« wurde nicht deklariert
     using std::gets;
                ^~~~
wlan-141-23-139-15:objdir user$ 
```
This ERROR: »std::gets« was not declared.
I did everything at this site:
https://rkrara.blogspot.de/2012/12/install-systemc-230-on-linux.html?showComment=1468411507294#c7266050945646088690

Can someone help me to run SystemC 2.3.2 on my Xcode 9.1 please.
Thanks.

**Comment by sean-mcmanus** [comment]
This doesn't appear to be a problem with our cpptools extension. I think you'll need to find someone familiar with SystemC 2.3.2.
