### ISSUE TITLE
[Loc] ‘developer’ was localized in C++ Walkthrough page

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-cpptools#12439]
### Bug Summary and Steps to Reproduce

**Environment**:
VSCode 1.90.2+ C/C++ Extension 1.21.0 pre-release)

**More info**:
1. Repro platform: Windows
2. Different status in different languages:
•	1st part translated and kept ‘developer’ in 3rd part: CHS, JPN, KOR, ITA
•	3rd part translated and kept ‘developer’ in 1st part: ESN  
•	‘developer’ all translated: CHT, FRA, PLK, PTB, DEU, TRK 
•	1st and 3rd part **all keep ‘developer’**: RUS, CSY 

**Steps to reproduce**:
1. Open VScode and change the display language to loc languages (such as: CHS)
2. Open the command palette-> Type "Welcome: Open Walkthrough..." and hit enter
3. Select the "Get Started with C++ Development"
4. Check the string ‘developer’ status in 1st part _(Set up your c++ Environment)_ and 3rd part _(Launch from the developer command prompt)_

**Expected result**:
‘developer’ **needn’t localized** to launch Developer Command Prompt for VS 
(Such as: 3rd part on CHS version)
![developer_exp](https://github.com/microsoft/vscode-cpptools/assets/37648162/6a364a36-c1d3-45fa-8db4-8debce1a369f)

**Actual result**:
‘developer’ was translated on some part
(Such as: 1st part on CHS version)
![developer_act](https://github.com/microsoft/vscode-cpptools/assets/37648162/0670fa6a-586a-4291-be72-c383fa4bdd83)

### Configuration and Logs

```shell
loc issue not related to log
```

**Comment by browntarik** [comment]
Thank you for reporting this issue, this has been filed with our internal localization team (VS: 985101). Please track this issue for updates.

**Comment by Yingzi1234** [comment]
@bobbrow @PhoebeTf This issue has not yet been fully resolved in the latest C++ version xxx, it has been fixed for ITA, DEU, RUS, CSY but not yet for the other languages, you can get detailed screenshots from below. I will reopen this issue. Thank you!

Different status in different languages:
• 1st part translated and kept ‘developer’ in 3rd part: CHS, JPN, KOR
• 3rd part translated and kept ‘developer’ in 1st part: ESN
• ‘developer’ all translated: CHT, FRA, PLK, PTB, TRK
• 1st and 3rd part all keep ‘developer’: RUS, DEU, ITA,CSY

CHS: Should be “developer” in quotes not translated
![Image](https://github.com/user-attachments/assets/d91243cd-3bec-4ad4-b331-8ca7ffe23bee)

**Comment by bobbrow** [comment]
I spoke with the team that owns the "developer command prompt for VS" shortcuts and it looks like those won't ever be translated. It looks like they will be treated as product names going forward. I'll open a new bug to get all of these strings reverted to the product name (undoing the translations around them)
