### ISSUE TITLE
The language server crashed.

### ISSUE THREAD

**Issue by Stringod** [microsoft/vscode-cpptools#12433]
Type: <b>Performance Issue</b>

When I open my VS Code it show me an error named "The language server crashed 5 times in the last 3 minutes. It will not be restarted." I am working in my company and I have an IT department if you want to know it. I am using PlatformIO and C/C++ extensions. This is an urgent problem I need to fix it asap please.

Extension version: 1.20.5
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (19.08GB free)|
|Process Argv|--crash-reporter-id 30858aac-e42f-40a2-991b-d4a6f66903ad|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   106	 20044	code main
    0	   117	  5168	window [2] (Issue Reporter)
    0	   100	  9156	shared-process
    0	    77	 11484	fileWatcher [1]
    0	    36	 19000	   crashpad-handler
    0	   111	 23680	extensionHost [1]
    0	     8	 19384	     C:\Users\erayeroglu\.platformio\penv\Scripts\python.exe -m platformio -c vscode home --port 45181 --host 127.0.0.1 --session-id f2f6ee0605e8bc97221b7a7af73c2f899cf5b223 --shutdown-timeout 3600 --no-open
    0	    11	 28916	       C:\Windows\system32\conhost.exe 0x4
    0	    21	 29036	       "C:\Users\erayeroglu\.platformio\python3\python.exe" -m platformio -c vscode home --port 45181 --host 127.0.0.1 --session-id f2f6ee0605e8bc97221b7a7af73c2f899cf5b223 --shutdown-timeout 3600 --no-open
    0	    82	 24972	     "C:\Users\erayeroglu\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\erayeroglu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=23680
    0	   147	 24760	   gpu-process
    0	   209	 25372	window [1] (HP303B.h - nodeMCU32 - Visual Studio Code)
    0	    51	 29096	   utility-network-service
```

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by sean-mcmanus** [comment]
@Stringod Does it repro with 1.21.0 (pre-release) too? Does it crash immediately on startup or are you able to attach a debugger to the cpptools.exe process before it crashes to get a call stack? https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv . Are you able to use a simpler workspace or change your settings such as C_Cpp.files.exclude to get it to not crash? With C_Cpp.loggingLevel set to "Debug" what is the last logging in the "C/C++" logging pane before it crashes (usually it will output a initializing message on startup after it has crashed).

**Comment by Stringod** [comment]
The problem still exists with pre-release and older versions. I reinstall plugins and vs code but it did not work. Yes language server is instantly crash. I created simple workspace but error still goes on. 

This is error message in my logs:

notificationsAlerts.ts:42 The language server crashed. Restarting...
notificationsAlerts.ts:42 The language server crashed 5 times in the last 3 minutes. It will not be restarted.

**Comment by sean-mcmanus** [comment]
@Stringod That call stack does not indicate a crash. It says it's paused on a breakpoint. Can you expand the other thread call stacks to see if any are processing a crash? Then hit continue and see if it crashes later on. It looks like the debugger is broken into the process too early before it's actually started running our code.

**Comment by Stringod** [comment]
@sean-mcmanus I hit continue and crash did not happen. I want to add this informaiton when I click debug with windows attach 5 cpptools options appear in screen I tried every one of them but none of them didn't crash.
![cpp-tools](https://github.com/microsoft/vscode-cpptools/assets/67244479/ba7ce686-1dca-4731-a351-0d63575d2386)

**Comment by Stringod** [comment]
I solved the problem by following the steps in this link :
https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders

**Comment by sean-mcmanus** [comment]
@Stringod I don't see any steps in that link. Is that the correct link?
