### ISSUE TITLE
Debugger breakpoints

### ISSUE THREAD

**Issue by iusztinpaul** [microsoft/vscode-cpptools#1244]
Hello,

I am trying to setup the debugger for a c project. Everything works fine until i use an actual breakpoint.
So the debuggers runs all threw the program and never stops at the breakpoints. Here is my launch.json file ( I use Windows 10 and a 32 bit MinGW) :

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/build/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

**Comment by pieandcakes** [comment]
@PaulakaPaul This is usually a symptom of when you compiled, it was missing the `-g` flag to include symbols. Please make sure when you compiled your project, that the `-g` flag was specified.

**Comment by iusztinpaul** [comment]
Thank you a lot !  It worked

**Comment by pieandcakes** [comment]
@PaulakaPaul I'm going to close this issue. If you are still having issues, please post an update and reopen.
