### ISSUE TITLE
Enable switching between different workspace symbol search implementations using C_Cpp.experimentalFeatures

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#12448]
The different implementations give different fuzzy results and have different performance characteristics.
 
Setting C_Cpp.experimentalFeatures to "enabled" will use the "new" one (which also makes tag parsing faster, fixing https://github.com/microsoft/vscode-cpptools/issues/12292).

Setting C_Cpp.experimentalFeatures to "disabled" will use the implementation from 1.19.x. 

Setting C_Cpp.experimentalFeatures to "default" will select one for certain users based on whatever the experiment is currently set to.

**Comment by heartacker** [comment]
> Setting C_Cpp.experimentalFeatures to "enabled" will use the "new" one (which also makes tag parsing faster, fixing #12292).

great /firework
