### ISSUE TITLE
[Loc] Incorrect translation for “Verifying the compiler installation”

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-cpptools#12440]
### Environment

**Environment**:
VSCode 1.90.2+ C/C++ Extension 1.21.0 pre-release)

### Bug Summary and Steps to Reproduce
**More info**:
- Repro platform: Windows
- Repro languages: CHS, CHT _(Not familiar with other languages)_

**Steps to reproduce**:
1. Open VScode and change the display language to CHS or CHT
2. Open the command palette-> Type "Welcome: Open Walkthrough..." and hit enter
3. Select the "Get Started with C++ Development"
4. Check the string ‘Verifying the compiler installation’ status in 1st part (Set up your C++ Environment) 

**Expected result**:
CHS: 验证编译器安装
CHT: 驗證編譯器安裝

**Actual result**:
With extra string “正在”:
CHS: 正在验证编译器安装
CHT: 正在驗證編譯器安裝
![extrastring](https://github.com/microsoft/vscode-cpptools/assets/37648162/ca230b29-6061-46e0-b67d-d2a4f89bc540)

### Configuration and Logs

```shell
loc issue not related to log
```

**Comment by browntarik** [comment]
Thank you for reporting this issue, this has been filed with our internal localization team (VS: 985099). Please track this issue for updates.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.23.0

**Comment by Yingzi1234** [comment]
@PhoebeTf @sean-mcmanus This issue has been fixed on latest C/C++ version v1.23.0(pre-release), you can get the details below. Thank you!

CHS:
![Image](https://github.com/user-attachments/assets/f4089492-8e88-47ce-b356-27d788a14770)

CHT:
![Image](https://github.com/user-attachments/assets/5610fb66-791e-464d-9258-09c622e96210)
