### ISSUE TITLE
[Loc] CHS version “You should see a copyright message with the version and basic usage description” with extra string “情况”

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-cpptools#12441]
### Environment

VSCode 1.90.2+ C/C++ Extension 1.21.0 pre-release)

### Bug Summary and Steps to Reproduce

**More info**:
- Repro platform: Windows
- Repro languages: CHS

**Steps to reproduce**:
1. Open VScode and change the display language to CHS
2. Open the command palette-> Type "Welcome: Open Walkthrough..." and hit enter
3. Select the "Get Started with C++ Development"
4. Check the string ‘You should see a copyright message with the version and basic usage description’ status in 1st part _(Set up your C++ Environment)_

**Expected result**:
CHS: 你应该会看到包含版本和基本使用说明的版权消息
CHT: 您應該會看到内附版本及基本使用說明的著作權訊息
_(CHT screenshot as below)_
![string_Exp](https://github.com/microsoft/vscode-cpptools/assets/37648162/2734bcf0-3e56-43af-9599-cc6545ca469c)

**Actual result**:
CHS with extra string “情况”: 
你应该会看到包含版本和基本使用**情况**说明的版权消息

![String_Act](https://github.com/microsoft/vscode-cpptools/assets/37648162/29608dd6-a722-479a-8d82-66171a707d34)

### Configuration and Logs

```shell
loc issue not related to log
```

**Comment by browntarik** [comment]
Thank you for reporting this issue, this has been filed with our internal localization team (VS: 985105). Please track this issue for updates.

**Comment by sean-mcmanus** [comment]
FYI, this fix is pending for 1.23.0.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.23.0

**Comment by Yingzi1234** [comment]
@PhoebeTf @sean-mcmanus This issue has been fixed on latest C/C++ version v1.23.0(pre-release), you can get the details below. Thank you!

CHS:
![Image](https://github.com/user-attachments/assets/a9bb504f-d19a-47f7-8b51-9b619cca657a)

CHT:
![Image](https://github.com/user-attachments/assets/5a145645-ede9-432e-8dd8-26dd3d1fb9f8)
