### ISSUE TITLE
Request to let some functions to work for inactive regions, too.

### ISSUE THREAD

**Issue by thesis79** [microsoft/vscode-cpptools#12453]
### Feature Request

Hi.
I'm a newbie for VS code.
I've been a source insight user for a long time and I browsed kernel source code with the tool.

Recently, I met VS code and I'm trying to move to VS code.
I think VS code is definitely powerful IDE.
I think I can succeed in moving to VS code this time.

But A con of VS code is some functions don't work for inactive blocks.
I know similar issue has been addressed already here (https://github.com/microsoft/vscode-cpptools/issues/5398)
I know your answer the action is intended and normal but actually it's inconvenient.
When we compile source code, So many definitions are defined in many ways.
So when we browse source code, we need to consider inactive regions as target, too.

I'm not VS code IDE developer, but I think you just need to add an option for this and It won't be a big deal.
Please consider this enhancement seriously.

Thanks.

**Comment by sean-mcmanus** [comment]
@thesis79 How is your request differerent from https://github.com/microsoft/vscode-cpptools/issues/5398? What other feature are you referring to?

**Comment by thesis79** [comment]
> @thesis79 How is your request different from #5398? What other feature are you referring to?

In my case, I found same problem when I ran the command 'Show Call Hierachy'.
When I tried to find callers of a function with the command, I felt vs code took  inactive region out of search target areas.
