### ISSUE TITLE
could not be opened because the file was not found

### ISSUE THREAD

**Issue by shawn1j** [microsoft/vscode-cpptools#12478]
### Environment

- OS and version: Windows 10
- VS Code: v1.90.2
- C/C++ extension: v1.20.5
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Bug Summary:

My project uses a third-party library, and when I debug, an exception is raised, and vscode automatically opens the source file in which the exception was raised, but it tells me I can't open the editor because the file wasn't found.

![image](https://github.com/user-attachments/assets/240c46ba-5290-44f9-b489-f45a9b720065)

The file exists, its location is in the E disk, I do not know why it to go to the D disk to find the file, I need to do what, so that it can go to the E disk to find the file.

I used debugging in the CMake plugin, not launch.json
![image](https://github.com/user-attachments/assets/46931428-d42e-4e3f-a65f-88771c46bbf9)

### Debugger Configurations

```shell
I used debugging in the CMake plugin, not launch.json
```

### Debugger Logs

```shell
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code
with Visual Studio Code, Visual Studio or Visual Studio for Mac
software to help you develop and test your applications.
-------------------------------------------------------------------
Loaded 'E:\webrtc_examples\bin\client\Debug\peerconnect_client.exe'. Symbols loaded.
Loaded 'C:\Windows\System32\ntdll.dll'. 
Loaded 'C:\Windows\System32\kernel32.dll'. 
Loaded 'C:\Windows\System32\KernelBase.dll'. 
Loaded 'C:\Windows\System32\ws2_32.dll'. 
Loaded 'C:\Windows\System32\rpcrt4.dll'. 
Loaded 'C:\Windows\System32\user32.dll'. 
Loaded 'C:\Windows\System32\win32u.dll'. 
Loaded 'C:\Windows\System32\gdi32.dll'. 
Loaded 'C:\Windows\System32\gdi32full.dll'. 
Loaded 'C:\Windows\System32\msvcp_win.dll'. 
Loaded 'C:\Windows\System32\ucrtbase.dll'. 
Loaded 'C:\Windows\System32\ole32.dll'. 
Loaded 'C:\Windows\System32\combase.dll'. 
Loaded 'C:\Windows\System32\oleaut32.dll'. 
Loaded 'C:\Windows\System32\IPHLPAPI.DLL'. 
Loaded 'C:\Windows\System32\msdmo.dll'. 
Loaded 'C:\Windows\System32\winmm.dll'. 
2
Loaded 'C:\Windows\System32\msvcrt.dll'. 
Unloaded 'C:\Windows\System32\msvcrt.dll'.
Loaded 'C:\Windows\System32\advapi32.dll'. 
Loaded 'C:\Windows\System32\sechost.dll'. 
Loaded 'C:\Windows\System32\bcrypt.dll'.
```

### Other Extensions

I used CMake to build my project.
CMake  version  3.29.6

**Comment by bobbrow** [comment]
I'm guessing that something in the symbols is pointing to the D drive instead of the E drive.

If you're using CMake Tools to debug, you can try using the `cmake.debugConfig` setting to try to set a source file mapping and see if the debugger will fix it.  It should basically do a find/replace of the path on the left with the path on the right.

```json
  "cmake.debugConfig": {
    "sourceFileMap": {
      "D:\\": "E:\\"
    }
  }
```

**Comment by shawn1j** [comment]
I tried to set it up this way, but it didn't work as expected, and the debugger was still searching for files on disk D.
![Snipaste_2024-07-17_21-17-25](https://github.com/user-attachments/assets/cc0447d8-2733-494a-945a-2c4807a06b5c)
I guess it is my version of vscode that has a problem. vscode does not have a corresponding setting prompt when I enter these Settings. Is this setting deprecated in my version

**Comment by bobbrow** [comment]
No, it shouldn't be deprecated. I think it's just missing from the settings schema for CMake Tools.  Anything that supported in `launch.json` is supported in `cmake.debugConfig`.

I just tried it out in a simple project and it seems to work for me. I copied a source file from the build location to a subfolder, set up the mapping in the settings, and set a breakpoint in the file in the new folder and I was able to hit it.

Perhaps there is something else preventing the mapping from working, like maybe the source file does not match the one used for the build?  You can try adding the `"requireExactSource": false` option and see if that does it.  Or maybe play with the mappings and just do the direct folder instead of the whole hard drive.

e.g. this works for me in my test project:
```json
    "cmake.debugConfig": {
        "sourceFileMap": {
            "D:\\test\\cmaketest": "D:\\test\\cmaketest\\sourceMap"
        },
        "requireExactSource": false
    }
```

**Comment by shawn1j** [comment]
This setup doesn't seem to work for me, I try to map the rtc_base directory to E:\\webrtc_src\\rtc_base directory, but the debugger still looks for the file in disk D. Is there something wrong with my Settings?
![settingjosn](https://github.com/user-attachments/assets/a3db667c-471f-45fc-a0cf-10582dbc4598)


Here is where my code is located:
![source](https://github.com/user-attachments/assets/35fab1b8-a9f0-40b6-a7b3-bcf8384158a4)
Below is the location of the source code of the third-party library I used:
![源码位置](https://github.com/user-attachments/assets/28c02405-45a0-4b9c-9d8f-c33ac9c920be)

**Comment by shawn1j** [comment]
This setup doesn't seem to work for me, I try to map the rtc_base directory to E:\\webrtc_src\\rtc_base directory, but the debugger still looks for the file in disk D. Is there something wrong with my Settings?
![settingjosn](https://github.com/user-attachments/assets/a3db667c-471f-45fc-a0cf-10582dbc4598)


Here is where my code is located:
![source](https://github.com/user-attachments/assets/35fab1b8-a9f0-40b6-a7b3-bcf8384158a4)
Below is the location of the source code of the third-party library I used:
![源码位置](https://github.com/user-attachments/assets/28c02405-45a0-4b9c-9d8f-c33ac9c920be)

**Comment by bobbrow** [comment]
If the source file map isn't working, you could try creating a junction link to the other drive and see if that works instead?

`mklink /J D:\rtc_base E:\webrtc_src\src\rtc_base`

**Comment by shawn1j** [comment]
I tried to create links for them, but it didn't seem to work. It's still looking in disk D.
![image](https://github.com/user-attachments/assets/2df7f41f-0953-4e14-92e3-c1d804cb00fe)

**Comment by bobbrow** [comment]
I should have asked earlier, but are you building this library in your CMake script or is this a pre-built library you've downloaded from somewhere?

**Comment by shawn1j** [comment]
I downloaded the webrtc source code from Google's codebase and compiled it on my own machine

**Comment by bobbrow** [comment]
How did you build it (and which compiler)? It looks like Google uses their own build system (GN) for this component? I'm not sure how that ties in with CMake. I'm not aware of a case where building code on your own machine gets the paths wrong in the symbols. We may need to dig into the build logs or the symbols themselves, but I need to know the compiler before I have any idea what the next steps are.  (Please also note that this is not my area of expertise as I primarily work on the language service/IntelliSense)

**Comment by shawn1j** [comment]
I built webrtc on Windows 10, the compiler should be using clang in visual studio 2022, here is the build command I used when compiling:
`
gn gen out/debug --ide="VS2022" --args="is_debug=true enable_iterator_debugging=true use_custom_libcxx=false  rtc_use_h264 = true ffmpeg_branding = "Chrome""

autoninja -C out/debug
`
After using the compilation command above, it compiles a webrtc.lib static library. Later in my project I will link to this library to use the functionality of webrtc. My project is built using CMake.

**Comment by bobbrow** [comment]
Glad to hear you got it working.  Is the source mapping of everything on the E: drive to that subfolder still needed?  It seems like it could cause unforeseen problems later.

**Comment by shawn1j** [comment]
Yes, if you map everything on drive E, there are some C++ source code files that the debugger will not find. I think the correct approach is to map only partial folders.
![image](https://github.com/user-attachments/assets/1c30d7e3-3aad-4775-aedf-24ee07f20ebe)
