### ISSUE TITLE
cannot resolve namespace llvm on macos VS code 

### ISSUE THREAD

**Issue by cryptothunder** [microsoft/vscode-cpptools#12475]
Hi ,my macos Sonoma 14.5,and my VS code is : 1.91.1 (Universal)
commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
my clang: 
Homebrew clang version 18.1.7
Target: x86_64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

yet,on VS code ,when I write code 
```
using namespace llvm;
```

it hints me 
```
Expected namespace nameclang(expected_namespace_name)
```

when I change to using namespace clang;, still the same hints

how can I solved it ?

**Comment by sean-mcmanus** [comment]
@cryptothunder That error message is from clang and not from our extension. It sounds like you need to include the header that defines that namespace.
