### ISSUE TITLE
Cannot debug C++ codes with string variables defined

### ISSUE THREAD

**Issue by ComradeZeil** [microsoft/vscode-cpptools#1248]
* OS: Windows 10, Version 1703
* VS Code version: 1.18.0 no Insiders build
* C/C++ extension version: 0.14.2
* Other extensions: 

Extension name  | Author  |  Version
------------------ | --------- | --------
ESLint | Dirk Baeumer | 1.4.3
Python | Microsoft | 0.8.0

I find this issue when I define some C++ string variables in my code `cpp_string.cpp` below: 

```c++
#include <iostream>
#include <string>

using namespace std;

int main()
{
    ...
    string str1, str2, str3, temp;
    ...
}
```
the debug did not start but the debug console showed

```
ERROR: During startup program exited with code 0xc0000139.
The program 'd:\C++\cpp_string\cpp_string.exe' has exited with code 0 (0x00000000).
```

![image](https://user-images.githubusercontent.com/11332022/32761595-2a4e7c24-c92f-11e7-9f32-9fbf7fa9dc88.png)

And if I code C++ **without** defining any string variables, even I `#include<string>` the debug will start  and no `ERROR` message in debug console. 

Source and relevant JSON files are in `.zip` attachment. 
[attachment.zip](https://github.com/Microsoft/vscode-cpptools/files/1469486/attachment.zip)

**Comment by pieandcakes** [comment]
@ComradeZeil Can you provide the full build number for your Windows Build? Also what are you using to compile? I see you are using MinGW gdb.exe to debug, are you compiling with gcc.exe? Can you provide the version of MinGW you are trying to use? Does the program run itself from the command line?

this sounds like a compilation problem and not a debugging problem.

**Comment by ComradeZeil** [comment]
* Windows Build: 15063.726
* Compiler: MinGW g++  6.3.0

From command line the program prompts
```
The procedure entry point
_ZNKSt7__cxx1112basic_stringlcSt11char_traitslcESalcEE7compareERKS4_
could not be located in the dynamic link library D:\C++\cpp_string\cpp_string.exe.
```
![image](https://user-images.githubusercontent.com/11332022/32870444-f3f5a722-cab6-11e7-8217-1d9dd8560133.png)

**Comment by pieandcakes** [comment]
@ComradeZeil This doesn't sound like an issue with the extension. That sounds like a problem with the version of MinGW that you have. I verified that the one I have is MinGW g++ version 7.1.0 and I can't repro what you have. You may want to update the version of MinGW.

**Comment by ComradeZeil** [comment]
I updated my MinGW to 7.2.0 and the problem fixed. Thanks.

**Comment by ComradeZeil** [comment]
I updated my MinGW to 7.2.0 and the problem fixed. Thanks.

**Comment by GorvGoyl** [comment]
To get latest MinGW: https://mingw-w64.org/doku.php/download
