### ISSUE TITLE
Change outlining/regions to collapse function arguments (so the last argument isn't pinned in the sticky scroll feature)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#12489]
Otherwise, the sticky scroll shows the last line of the function signature that has the `{` instead of the first line that has the function name.

And/or maybe make this configurable via a setting.

The "workaround" is to look at the breadcrumb for the function name instead of the sticky area.

**Comment by Colengms** [comment]
To address this properly, I believe we would need VS Code to implement: https://github.com/microsoft/vscode/issues/168428

**Comment by TimHuecking-LR** [comment]
I would really fancy this 👍
