### ISSUE TITLE
v1.21.2 crashes on Linux ARM OS's

### ISSUE THREAD

**Issue by HKishere** [microsoft/vscode-cpptools#12497]
### Environment

- OS and Version: linux(remote)
- VS Code Version: 1.91.1(user setup)
- C/C++ Extension Version: 1.21.2
- If using SSH remote, specify OS of remote machine: 
`Linux  4.4.38 #530 SMP PREEMPT Sat Aug 8 10:58:10 CST 2020 aarch64 aarch64 aarch64 GNU/Linux`

### Bug Summary and Steps to Reproduce

Bug Summary:

When I start vscode this affternoon，I found my C++extension cashed. it reboot for 3 times automatly, but cash after every time when it boot. and it print some log on output like this：

```
语言服务器崩溃。正在重新启动...  
Server process exited with signal SIGSEGV.
```

I installed the version v1.20.5 after that, and it work correctly. so it seem that v1.21.2 may got something wrong.

### Configuration and Logs

```shell
All configurations is defualt
```

**Comment by stfufane** [comment]
Can confirm, I have the exact same problem on Linux ARM remote machine 
`Linux 5.4.0-189-generic #209-Ubuntu SMP Fri Jun 7 14:05:34 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`

It crashes repeatedly with the same output : 
```
[Error - 2:41:51 PM] The language server crashed. Restarting...
[Error - 2:41:51 PM] Server process exited with signal SIGSEGV.
```

**Comment by bobbrow** [comment]
Thank you for reporting this issue.  We are looking at the code shared in the callstack shared. @HKishere, @stfufane, @chrumck if you are also able to attach a debugger and share a callstack, that would help us confirm if you are all hitting the same issue.

If you can share any other information or logs related to what you were doing at the time of the crash, or if you are working on an open source project that we can clone, that can also help us in the investigation.

**Comment by TheRealOrange** [comment]
This error occurs whenever I open a `.cpp` file. The environment I am working in is an ubuntu dev container, and there are no issues on startup, but it errors when I open a `.cpp` source file. It also seems like all those who experience the issue are on `aarch64` an ARM64 architecture.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.21.3
