### ISSUE TITLE
Change translation in autocomplete setting to say "language" instead of "voice"

### ISSUE THREAD

**Issue by wangbingsum** [microsoft/vscode-cpptools#12492]
### Feature Request

![image](https://github.com/user-attachments/assets/19b8c9db-0086-47ca-a323-5270ed8f2d4f)

**Comment by bobbrow** [comment]
I'm sorry, we don't speak Chinese. Would you be able to explain what you expect the translation for this setting to say instead? We can send that suggestion to our translators.

Thank you!

**Comment by heartacker** [comment]
language:语言
voice:语音

**Comment by bobbrow** [comment]
Thank you!

@browntarik can you open a bug to get the text for this setting updated so that it says "language" instead of "voice".  The translation is above ^

**Comment by browntarik** [comment]
Thank you for reporting this issue. We have notified our internal localization team (987897). Please follow this issue for updates on when a fix has been made.
