### ISSUE TITLE
Newest version not find references about function and variables

### ISSUE THREAD

**Issue by jheffersonalves** [microsoft/vscode-cpptools#12498]
### Environment

- OS and Version: Linux Mint 20.1 Cinnamon
- VS Code Version: 1.69.1
- C/C++ Extension Version: 1.21.2

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Go to variables or function definition
2. Click on with "CTRL" on function or variables
3. And isn't working

Expected behavior:
Go to Declaration from function or variable

### Configuration and Logs

```shell
c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}

C/C++: Log Diagnostics:
loggingLevel: Debug
Custom configuration provider 'CMake Tools' registered
```

**Comment by sean-mcmanus** [comment]
@jheffersonalves Is your issue random? Does doing a Reset IntelliSense Database command from the command palette fix the issue? If you check your database size with 1.20.5 is the database size with 1.21.3 smaller? I'm trying to determine if your issue is the same as https://github.com/microsoft/vscode-cpptools/issues/12505 (the issue @otbu2 mentioned).

**Comment by sean-mcmanus** [comment]
@jheffersonalves @otbu2 Can someone temporarily set the C_Cpp.logginglevel to the hidden value of "7" and see if any SQLITE error messages are being reported? The database maybe in a corrupted state (resetting the database as mentioned in my prior comment would fix that, although it might get into that bad state again).

**Comment by sean-mcmanus** [comment]
@jheffersonalves @otbu2 Also, when you repro the issue, does adding new global variables/function not update the Outline view with symbols? (if you're seeing SQLITE error messages, then that is likely the case).

**Comment by sean-mcmanus** [comment]
@jheffersonalves @otbu2 Also, do you repro the issue if you do a Reset IntelliSense Database and then don't interact with the editor until the database is done populating? i.e. does the repro seem to require doing other actions such as editing files or symbol search, etc. while the database is populating?

**Comment by MarcelBrusius** [comment]
I also experienced Intellisense issues starting about two days ago (both with version 1.21.2 and 1.21.3. Neither in WSL nor in a Docker container opened from WSL Intellisense is working. It tries to determine suggestions for an eternity before it always ends up showing `no suggestions`.

C/C++ (debug) output looks like this everytime I hover over a variable/function/...:
`LSP: (received) textDocument/hover: file:///some/path/in/wsl/docker/main.cpp (id: 26)`
`LSP: (invoked) textDocument/hover: file:///some/path/in/wsl/docker/main.cpp (id: 26)`
`Quick info operation failed: FE: 'Compiler exited with error - No IL available'`
`using Tag Parser for quick info`
`LSP: Sending response (id: 26)`

On Windows however it seems to work.
`LSP: (received) textDocument/hover: file:///path/on/windows/main.cpp (id: 50)`
`LSP: (invoked) textDocument/hover: file:///path/on/windows/main.cpp (id: 50)`
`LSP: Sending response (id: 50)`

As already metioned, reverting to 1.20.5 solves the issuee.

**Comment by fevb** [comment]
+1, I have been experiencing these same intellisense issues since version >= `1.21.2` when running a workspace from a docker container.

I posted some details in https://github.com/microsoft/vscode-cpptools/issues/12505#issuecomment-2446557533
