### ISSUE TITLE
Intellisense is too agressive now

### ISSUE THREAD

**Issue by duncanhorn** [microsoft/vscode-cpptools#125]
E.g. If I type:

```
#include <string>
```

It'll give me suggestions after typing the closing '>' which is _super_ annoying since it's muscle memory to hit enter

**Comment by ro-kue** [comment]
Yep. I uninstalled the extension for this very reason.

**Comment by NOhs** [comment]
I think it is related to this issue: https://github.com/Microsoft/vscppsamples/issues/141

**Comment by sridmad** [comment]
Aggressive auto complete should be fixed in 0.9.0 of the extension. Please update and let us know if the issues still occurs in the updated version.
