### ISSUE TITLE
 The outline does not recognize functions, variables, and cannot jump when clicked in 1.21.2

### ISSUE THREAD

**Issue by caoweijian1** [microsoft/vscode-cpptools#12506]
Type: <b>Bug</b>

在打开C语言文件后大纲无法识别函数,变量,点击无法跳转

Extension version: 1.21.2
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.56GB free)|
|Process Argv|--folder-uri file:///f%3A/CWJ/%E5%8E%9F%E7%A8%8B%E5%BA%8F%E8%B5%84%E6%96%99/%E6%98%BE%E7%A4%BA%E5%B1%8F/%E8%B4%9D%E5%A1%94%E6%98%BE%E7%A4%BA%E5%B1%8F-STC15W204S-24M-20200907 --crash-reporter-id e23c7883-70d2-466e-8281-b54b50d96204|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactorc:31101458
ccplt:31103426
pythonrstrctxt:31103193
hdi1a554:31097393

```

</details>

**Comment by Wyler-Yue** [comment]
也遇到了这种情况，是否此功能默认关闭？如何重新打开？

**Comment by caoweijian1** [comment]
回退版本至1.20.5可以恢复正常




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-cpptools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月25日(星期四) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-cpptools] 最新版本无法识别函数变量 (Issue #12506)





 
也遇到了这种情况，是否此功能默认关闭？如何重新打开？

**Comment by Kernopike** [comment]
1.21.3 需求的 VS Code 是 ^1.82.0，可通过 OUTPUT/cpptools 中，有错误打印。

> The language client requires VS Code version ^1.82.0 but received version 1.79.2

感觉应该是release 包封的有问题吧？不然老版本的 1.79.2 (windows server limited) 是无法使用的。

**Comment by browntarik** [comment]
@caoweijian1 Can you try out version 1.21.4 of the extension to see if your issue reproduces? If so, could you give details to help us reproduce the issue?
