### ISSUE TITLE
Inlay hints for array initializers

### ISSUE THREAD

**Issue by Raildex** [microsoft/vscode-cpptools#12508]
### Feature Request

clangd shows inlay hints for array initializers.
![clangd](https://github.com/user-attachments/assets/53b5ccdc-eda4-4226-97dc-39bf0c3188fa)
Intellisense does not.
![intellisense](https://github.com/user-attachments/assets/e2e748ea-2f71-4f23-8943-a5e35852f49a)

**Comment by Colengms** [comment]
Hi @Raildex .  Thank you for the feature request.  FYI, we prioritize feature requests based on up-votes.
