### ISSUE TITLE
Unable to debug on Windows ARM64 with versions (1.21.*) . Debugging works with 1.20.5

### ISSUE THREAD

**Issue by ankurvdev** [microsoft/vscode-cpptools#12520]
### Environment

- OS and version: Windows 26100.1297 (ARM64) 
- VS Code: 1.91.1
- C/C++ extension: 1.21.4
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Bug Summary:
Unable to Launch programs in debugger. 
Reverting to 1.20.5 works fine but with all versions 1.21.* Clicking "Launch" in the "Run and Debug" section simply builds the cmake target without actually launching it

Steps to reproduce:
"Click Launch" with the following launch.json
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "cppvsdbg",
      "request": "launch",
      "program": "${command:cmake.launchTargetPath}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${command:cmake.getLaunchTargetDirectory}",
      "console": "integratedTerminal",
     }]
}```

### Debugger Configurations

```shell
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "cppvsdbg",
      "request": "launch",
      "program": "${command:cmake.launchTargetPath}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${command:cmake.getLaunchTargetDirectory}",
      "console": "integratedTerminal",
     }]
}
```

### Debugger Logs

```shell
No relevant errors observed
The only message (after clicking launch is below)

[build] Run Build Command(s): d:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v -j 12 main
[build] ninja: no work to do.
[build] 
[driver] Build completed: 00:00:00.114
[build] Build finished with exit code 0
```

**Comment by AndreasKunar** [comment]
Thanks a lot!!! It broke my debugs too, and I thought it was me/my machine (lost a day with reinstall, move to another machine,...). For now, your hint of moving to 1.20.5 works perfectly. Again thanks!

**Comment by sean-mcmanus** [comment]
@ankurvdev Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.21.5

**Comment by ankurvdev** [comment]
Verified . its working now. Thanks
