### ISSUE TITLE
not getting expected result

### ISSUE THREAD

**Issue by User-49** [microsoft/vscode-cpptools#12527]
Type: <b>Bug</b>

the compiled code in "c" is not giving expected results 
i tried running my code in a different platform an the result was different

the code is to print angstrom's numbers to 500
and the number 153 is not being printed

my code:

#include <stdio.h>
#include <math.h>

void main(){
    int n = 1, temp, sum;
    while (n!=500)
    {   temp = n;
        sum = 0;
        while (temp)
        {
            sum +=  pow(temp%10,3);
            temp /=10;
        }
        (n==sum?printf("%d\n",n):0) ;
        n++;
    }
    scanf("%d");   
}

Extension version: 1.21.4
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (7.94GB free)|
|Process Argv|--crash-reporter-id caadf33c-cb28-4e58-94a5-3a5deb8b0ab2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactorc:31101458
ccplt:31103426
pythonrstrctxtcf:31103194
wkspc-onlycs-t:31102394

```

</details>

**Comment by Colengms** [comment]
Hi @User-49 .  This repo is for the C/C++ Extension for VS Code, which provides language services (go to definition, hover, signature help, formatting, etc.) in VS Code.  It sounds like the issue you're seeing is with the output of compiled code.  The C/C++ Extension itself does not directly provide C/C++ a compiler.  I'm guessing that since you're on Windows that you're probably using MSVC (cl.exe) or MinGW GCC.  Though, using either of those compilers, I see the following numbers output by your code (153 is included) :

1
153
370
371
407

Closing this issue as external, since it's not directly related to the C/C++ Extension for VS Code.

**Comment by User-49** [comment]
If that's the case I'm very sorry for wasting your time and thank you for tending to my query
