### ISSUE TITLE
Memory leak when work with ssh

### ISSUE THREAD

**Issue by wuyoutech** [microsoft/vscode-cpptools#12526]
### Environment

- OS and Version: MacBook M2 Air, Sonoma 14.5 (23F79)
- VS Code Version: 1.91.1 (commit f1e16e1e6214d7c44d078b1f0607b2388f29d729)
- C/C++ Extension Version: v1.21.4
- If using SSH remote, specify OS of remote machine: Ubuntu 24.04 LTS

### Bug Summary and Steps to Reproduce

Bug Summary:

1. open vscode, connect to ubuntu through Remote-SSH
2. open a folder, open some .c file
3. wait about 30 miniutes
4. 
<img width="801" alt="8dd5bd3c02f7481c5fc3b09a5e8a3aa8" src="https://github.com/user-attachments/assets/007023f2-3796-4e17-9159-1a008de4002c">

### Configuration and Logs

```shell
nothing here
all settings keep default, and no log output
```

**Comment by Colengms** [comment]
Hi @wuyoutech .  Could enable the setting `"C_Cpp.loggingLevel": "Debug"` and provide the output of the C/C++ output channel?  Or, if that continues to log activity perpetually, that may indicate work that is causing the memory usage.  If so, could you let us know what that output is?

I don't believe we've had similar reports regarding memory usage with such a simple scenario.  There may be some additional information about your repro or system environment that might help us understand what's happening.

Could you check whether the folder you are opening contains a symbolic link that might point elsewhere in your file system, or even create a circular link?  The C/C++ Extension assumes a workspace folder corresponds with a `project` and will, by default, index the contents of all files within that folder, recursively.  Maybe excessive memory usage is related to parsing an excessive number of files?

**Comment by wuyoutech** [comment]
Thank you for the information. It is indeed the circular link that causes the problem. 


> Hi @wuyoutech . Could enable the setting `"C_Cpp.loggingLevel": "Debug"` and provide the output of the C/C++ output channel? Or, if that continues to log activity perpetually, that may indicate work that is causing the memory usage. If so, could you let us know what that output is?
> 
> I don't believe we've had similar reports regarding memory usage with such a simple scenario. There may be some additional information about your repro or system environment that might help us understand what's happening.
> 
> Could you check whether the folder you are opening contains a symbolic link that might point elsewhere in your file system, or even create a circular link? The C/C++ Extension assumes a workspace folder corresponds with a `project` and will, by default, index the contents of all files within that folder, recursively. Maybe excessive memory usage is related to parsing an excessive number of files?
