### ISSUE TITLE
Clang -include arguments (pre-includes) in compile_commands.json not processed correctly

### ISSUE THREAD

**Issue by jwatt** [microsoft/vscode-cpptools#1252]
I'm on macOS 10.13.1 using VSCode 1.19.0-insider with C/C++ Tools 0.14.2.

The "commands" in my compile_commands.json invoke clang with an `-include /absolute/path/to/a/header.h` argument. This header contains some preprocessor defines that are output by the configure stage. When compiling a given source file this header should be included before any includes that are specified in that source file so that all files are compiled with the same set of "configuration" defines. Unfortunately the file doesn't seem to be included at all.

**Comment by bobbrow** [comment]
Yes, unfortunately this is currently expected.  We need to route pre-includes to the IntelliSense engine.  I believe there is another issue tracking this (without compile_commands.json).  We plan to do it but don't have the support ready yet.

**Comment by sean-mcmanus** [comment]
-include is now supported in our Insiders build: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders . Let us know if you find are any issues we should fix before our final release next week.
