### ISSUE TITLE
Clang inline assembly is not colorized

### ISSUE THREAD

**Issue by luizfernandonb** [microsoft/vscode-cpptools#12535]
### Environment

- OS and Version: Windows 11 23H2
- VS Code Version: 1.91.1
- C/C++ Extension Version: 1.21.5

### Bug Summary and Steps to Reproduce

Bug Summary:
The inline assembly that can be written in Clang using the `__asm` keyword is not colorized

Steps to reproduce:
1. Open any C or C++ file and use Clang
2. Write any inline assembly within the `__asm` ​​keyword
3. See that it doesn't get colored

Example:
![image](https://github.com/user-attachments/assets/74d0dc44-14e8-4191-926b-ffead8f1b61d)

Expected behavior:
The assembly code has some color

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "x86 - Debug",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "X86",
                "DEBUG",

                "UNICODE",
            ],
            "intelliSenseMode": "clang-x86",
            "cStandard": "c23",
            "cppStandard": "c++23",
            "compilerArgs": [
                "-Wall",
                "-Wextra",
                "-Wpedantic"
            ]
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
Our extension doesn't implement lexical colorization. It repros with our C/C++ extension disabled. The implementation is from VS Code itself, which gets its implementation from https://github.com/jeff-hykin/better-cpp-syntax/issues, so you should file a bug in that repo.

It seems like it's being tracked by https://github.com/jeff-hykin/better-cpp-syntax/issues/367
