### ISSUE TITLE
First element of the QMap array is not colorized

### ISSUE THREAD

**Issue by ChnTamap** [microsoft/vscode-cpptools#12543]
### Environment

- OS and Version: Win10
- VS Code Version: 1.85.2
- C/C++ Extension Version: 1.21.5
- If using SSH remote, specify OS of remote machine:

### Bug Summary and Steps to Reproduce

Bug Summary:

When initializing a class member variable of type `QMap<enum, QString>`, the first element is not colorized

Steps to reproduce:
Write Qt with c++
#### Example:
```cpp
class Test {
    // ...
public:
    inline static QMap<enum Type, QString>Texts = {
        {Uint8, "uint8"},
        {Uint16, "uint16"},
        {Uint32, "uint32"},
    };
    // ...
};
```

Expected behavior:

![CB8F86FB-AB24-4b0f-9BD3-FE70B9A7A3CE](https://github.com/user-attachments/assets/c01ba607-9d80-4b2b-aad3-924bd619adc4)

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/../build-Test_Qt_5_15_2_MinGW_32_bit-Release/**",
                "E:\\Qt\\5.15.2\\mingw81_32\\include",
                "E:/Qt/Tools/mingw810_32/lib/gcc/i686-w64-mingw32/8.1.0/include/c++/**",
                "E:/Qt/5.15.2/mingw81_32/include/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "windows-gcc-x86",
            "compilerPath": "E:\\Qt\\Tools\\mingw810_32\\bin\\g++"
        }
    ],
    "version": 4
}
```

### Other Extensions

vscode.npm
vscode.json-language-features
vscode.extension-editing
vscode.typescript-language-features
vscode.git-base
vscode.markdown-language-features
shd101wyy.markdown-preview-enhanced
vscode.emmet
CodeInChinese.EnglishChineseDictionary
ms-vscode.cpptools
vscode.debug-auto-launch
vscode.git
mhutchie.git-graph
vscode.merge-conflict
vscode.markdown-math

**Comment by sean-mcmanus** [comment]
Our extension doesn't implement lexical colorization. It repros with our C/C++ extension disabled. The implementation is from VS Code itself, which gets its implementation from https://github.com/jeff-hykin/better-cpp-syntax/issues, so you should file a bug in that repo.
