### ISSUE TITLE
C files incorrectly interpreted as C++ (causing Intellisense errors)

### ISSUE THREAD

**Issue by niklas-ourmachinery** [microsoft/vscode-cpptools#1256]
Many of my `.c` files are incorrectly interpreted as C++ files:

![image](https://user-images.githubusercontent.com/26548514/32856440-b4484dd6-c9f9-11e7-8211-b6f803c993de.png)

This leads to lots of bogus Intellisense errors reported for these files:

* expected an expression
* a value of type "void *" cannot be used to initialize ...

Hard coding a file association in the settings doesn't seem to help. I have this in my user settings:

```
"files.associations": {"*.c": "c"}
```

This is with C/C++ 0.14.2 and Visual Studio Code 1.18.0.

**Comment by bobbrow** [comment]
Are there any `files.associations` in your workspace settings (which override the user settings)?

**Comment by niklas-ourmachinery** [comment]
Yes! That's it. A lot of the files are explicitly listed as `"cpp"` in the Workspace settings. This must have happened automatically somehow, because I haven't edited those settings.

**Comment by sean-mcmanus** [comment]
@niklas-ourmachinery Our extension automatically associations extensionless files with C++ if a .cpp file #includes it (and the file is a target of a Go to Definition). Let us know if you have repro details for how a .c file is getting associated with "cpp". We've had bugs related to this a while ago, but I thought they were all fixed since we haven't heard complaints so far.

**Comment by niklas-ourmachinery** [comment]
I'll keep a watch on this and let you know if it happens again. It might be that this got into the workspace settings a long time ago. It was only today that I started using Intellisense and noticed this.

**Comment by anatolyburakov** [comment]
It seems that this is an issue again. This is using Insiders build and SSH Remote extension, while working on a C codebase.

![vscode-cpptools](https://user-images.githubusercontent.com/37181601/62861304-ed43cc00-bcfa-11e9-9874-afe476ffe80a.PNG)
