### ISSUE TITLE
1.21.6 Automatically modify the Chinese code

### ISSUE THREAD

**Issue by hu-shi-xiong** [microsoft/vscode-cpptools#12578]
### Environment

- OS and Version: 
- VS Code Version: 
- C/C++ Extension Version: 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
Version 1.21.6 automatically modifies the Chinese encoding, resulting in garbled characters

Steps to reproduce:
1. Install the VS CODE Chinese extension
2. Install the C/C++ extension
3. Enable VS CODE to automatically guess coding(Auto Guess Encoding)
4. Enter Chinese in the file and save the file in GB 2312 encoding format
5. When you close the file and open it again, the encoding changes from GB2312 to UTF-8

Expected behavior:
Do not change the encoding format

### Configuration and Logs

```shell
no
```

**Comment by Colengms** [comment]
Hi @hu-shi-xiong .  I believe the scenario you've described is specific to VS Code itself and not the C/C++ Extension.  Extensions are not involved in determining the encoding used for files open in the editor.  I'd suggest opening an issue in [the VS Code repo](https://github.com/microsoft/vscode/issues).

**Comment by hu-shi-xiong** [comment]
I tried using an older version (v1.16.2), VS CODE automatically guessed the encoding function back to normal

**Comment by hu-shi-xiong** [comment]
I tried using an older version (v1.16.2), VS CODE automatically guessed the encoding function back to normal

**Comment by hu-shi-xiong** [comment]
With the old C/C++ extension (v1.16.2), the VS CODE auto-coding function returns to normal
