### ISSUE TITLE
Add risc-v debugging support

### ISSUE THREAD

**Issue by ksrp1984** [microsoft/vscode-cpptools#12581]
### Feature Request

Without risc-v the debugger is not complete!

**Comment by browntarik** [comment]
Could you provide more details on what behavior you would like to see specifically?

**Comment by ksrp1984** [comment]
> Could you provide more details on what behavior you would like to see specifically?

Now I have 2 boards. With microcontrollers Cortex-M and RISC-V. Cortex works stably. RISC-V has failures. Also for RISK-V the disassembler view does not work.
There is a plugin for Cortex that works. I configured RISK-V manually, maybe the problems are because of this. But Cortex works stably and with manual configuration (disassembler too).
