### ISSUE TITLE
Identifier "namespace" is undefined

### ISSUE THREAD

**Issue by dorinlazar** [microsoft/vscode-cpptools#1258]
OS: Linux, CentOS 7. Due to issue #19 I use a script that loads the extension against a custom built GLIBC.
VSCode: Stable, 1.18.0
C++ Extension: 0.14.2

Header is named X.H (capital H). 

```
#pragma once

namespace x {
}

```
I get a red squiggle with «identifier "namespace" is undefined»
No log messages in the Output window.

**Comment by sean-mcmanus** [comment]
I'm not able to repro this. Is this a transient/temporary error? What line/character is the error appearing on?

**Comment by dorinlazar** [comment]
It no longer reproduces with VSCode 1.18.1

**Comment by cpei-avalara** [comment]
I just installed  VS code 1.32.3 and found this problem. My OS is WSL+ RedHat. Not sure how to fix it.

Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.4.0-17763-Microsoft

Also I got errors like "variable class" is not a type name.

**Comment by bobbrow** [comment]
Hi @cpei-avalara, can you please open a new issue with additional details about your C or C+ configuration?  This issue is closed.
