### ISSUE TITLE
Formatting with clang-format doesn't work when using .clang-format file

### ISSUE THREAD

**Issue by python4ever** [microsoft/vscode-cpptools#1259]
Hi. I've installed official C/C++ extension, got the latest update. It works flawlessly. The one problem I faced is the fact, that when I use Format Document, it does format it, okay. But when I place .clang-format file (even generated with clang-format binary) it doesnt format the file. I can place it in workspaceRoot, or in directory above that, it just doesnt do anything. Here's my user_settings.json:

`{
    "python.formatting.provider": "autopep8",
    "python.formatting.formatOnSave": true,
    "C_Cpp.clang_format_style": "file"
}` 

When I delete the file, or I switch the `C_Cpp.clang_format_style` to f.e `"{IndentWidth: 4}"` it does work

**Comment by ghost** [comment]
I wonder if your `.clang-format` file is using options that don't exist anymore or using bad values. It didn't seem to tell me that my `.clang-format` was using options that didn't exist, but would fail to format silently.

try running `clang-format -dump-config` in the directory with your `.clang-format`.  I don't know if that's the problem that you're having, but its' the one I just did :)

**Comment by Pogsquog** [comment]
I had the same problem. It was due to some issue with my handcrafted .clang-format file.
I resolved the issue by using -dump-config as suggested above, to create a .clang-format file, and then modifying it to suit me. 
It is curious that clang-format gave no errors, despite there being something obviously wrong with the file I had supplied to it originally.

**Comment by bobbrow** [comment]
I am working on a change to the extension that will display the clang-format errors we encountered in the Output window so that you can figure out what is wrong.  I will try to have it ready for the March release next week.

**Comment by bobbrow** [comment]
The change I referenced above is in the main branch.  Starting with the March update, we will write the error text into the Output window so you can see what the error is.

**Comment by sean-mcmanus** [comment]
Our insider build added clang-format error logging. Did anyone try it out? Do we still have a bug or is this a user error? https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders .

**Comment by chunshun** [comment]
This solution works[](https://stackoverflow.com/questions/42756602/clang-format-not-working-in-vscode-linux-ubuntu)

**Comment by lassik** [comment]
Just in case someone stumbles here from a web search wondering why clang-format doesn't do anything to their code: Is your code inside an `#if 0` ... `#endif` pre-processor block? It doesn't seem to touch those at all, no matter what settings you have.
