### ISSUE TITLE
IntelliSense updating and Parsing Open Files take too much time and prevent building

### ISSUE THREAD

**Issue by rei-vilo** [microsoft/vscode-cpptools#12607]
### Environment

- OS and Version: Debian 12 
- VS Code Version: 1.92.2
- C/C++ Extension Version: 1.21.6
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:

**IntelliSense updating** and **Parsing Open Files** take too much time and prevent building.

![Capture d’écran du 2024-08-21 15-12-57](https://github.com/user-attachments/assets/8764f33c-e7c9-44a2-ac7f-df99240bb0e1)

Steps to reproduce:
1. Open a project.
2. Press CTRL+SHIFT+B or call menu > Tasks: Run Build Task to build.
4. Wait for IntelliSense updating and Parsing Open Files to be completed

The wait could be 5-minute-long.

Expected behaviour:

+ Building starts when CTRL+SHIFT+B pressed or menu > Tasks: Run Build Task called

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Raspberry_Pi_Pico_RP2040_DebugProbe_CMSIS_DAP",
            "includePath": [
                "${workspaceFolder}/**",
                "${env:HOME}/.arduino15/packages/rp2040/hardware/rp2040/3.9.5/**",
                "${env:HOME}/Projets/Arduino/libraries/**"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "",
                "path": [
                    "${workspaceFolder}/**",
                    "${env:HOME}/.arduino15/packages/rp2040/hardware/rp2040/3.9.5/**",
                    "${env:HOME}/Projets/Arduino/libraries/**"
                ]
            },
            "intelliSenseMode": "${default}",
            "compilerPath": "${env:HOME}/.arduino15/packages/rp2040/tools/pqt-gcc/2.2.0-d04e724/bin/arm-none-eabi-g++",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "defines": [
                "EMCODE=11011",
                "ARDUINO=10813"
            ],
            "forcedInclude": [
                "${env:HOME}/.arduino15/packages/rp2040/hardware/rp2040/3.9.5/cores/rp2040/Arduino.h",
                "${env:HOME}/.arduino15/packages/rp2040/hardware/rp2040/3.9.5/variants/rpipico/pins_arduino.h"
            ]
        },
    ],
    "version": 4
}
```

### Other Extensions

IntelliCode 1.3.1

### Additional context

-

**Comment by Colengms** [comment]
Hi @rei-vilo .  Does this repro for you with our latest insiders version (1.22.6).  We recently addressed some performance issues.

Can you provide the content of your build task?  Even if using the 'cppbuild' task type, I don't believe that feature is connected to tag parsing or IntelliSense related features.  If not using the 'cppbuild' task type, your build task would not be tied to the C/C++ Extension at all.

Are you remoting into a Raspberry Pi?  Could the issue be due to general performance of the remote system?

**Comment by rei-vilo** [comment]
The project targets the Raspberry Pi Pico, which is based on the RP2040 MCU, and not a Raspberry Pi B, which is an SBC.

The task file includes

```
    "tasks": [
        {
            "label": "Build",
            "type": "shell",
            "command": "make",
            "args": [
                "build",
                "-j",
                "SELECTED_BOARD=${command:cpptools.activeConfigName}"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Build with makefile"
        },
        {
            "label": "Fast",
            "type": "shell",
            "command": "make",
            "args": [
                "fast",
                "SELECTED_BOARD=${command:cpptools.activeConfigName}"
            ],
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "detail": "Fast with makefile"
        },
```

The build process calls a makefile to manage the cross-compilation.  

If the issue is not linked to `cppbuild`, what to investigate?

Thank you!

**Comment by Colengms** [comment]
Hi @rei-vilo .  Since you're using a "shell" task, that is handled entirely by VS Code itself, and should not involve any interaction with the C/C++ Extension.  Can you confirm that, if you disable just the C/C++ Extension, that your builds start more quickly?  If so, my next guess would be that it has something to do with resource contention (maybe CPU and disk).  Perhaps that is occurring because VS Code is either remoted into, or running on, a system that is struggling to handle the load incurred by the C/C++ Extension.  Are you remoting directly into (opening a workspace folder directly on) a Raspberry Pi Pico?

**Comment by rei-vilo** [comment]
Disabling the C/C++ extension results in an error.

```
Error: the description can't be converted into a problem matcher:
{
    "base": "$gcc",
    "fileLocation": [
        "absolute",
        "${workspaceFolder}"
    ]
}
```

I am using an i5-1240P processor with 12 cores / 16 threads, so I doubt this could be the cause.

I am not using a remote target. The Raspberry Pi Pico is not an SBC and can't run the remote SSH VSC.

It seems that the IntelliSence and Parsing Open Files process are taking time before the actual build takes place.

**Comment by sean-mcmanus** [comment]
@rei-vilo Our extension defines the gcc problem matcher: I think you can create your own similar problem matcher, see https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L431 .

**Comment by rei-vilo** [comment]
Thank you for your answer.

Unfortunately, I am not sure to understand the link between the problem matcher and the IntelliSence and Parsing Open Files processes.

Isn't the problem matcher is active during the compilation, not before? The IntelliSence and Parsing Open Files processes are before the compilation and delay its start.
