### ISSUE TITLE
Enable formatOnType after ":" is used after access specifiers

### ISSUE THREAD

**Issue by Willaaaaaaa** [microsoft/vscode-cpptools#12604]
Type: <b>Feature Request</b>

I strongly suggest:
1.  Automatically add a semicolon after the right brace when defining a class. Just like `class Example { // class defination }` **->** `class Example { // class defination };`. Adding semicolons after the brace every time really annoy users a lot.
2.  Automatically remove the indentations to the left of `public`, `protected` and `private` declarations. Just like `    public:` **->** `public:`. Additionally, I have noticed that when I enter `:` right behind `public`, VS will delete the indentation immediately.

Both of the features I mentioned above can be implemented in VS. I believe they can provide huge convenience for programmers, especially for those who are accustomed to VS if VScode can realize the same features.

Extension version: 1.21.6
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Willaaaaaaa** [comment]
Additionally, I have noticed that when I enter `:` right behind `public`, VS will delete the indentation immediately.

**Comment by Willaaaaaaa** [comment]
# Here is the differences between them:
## visual studio:
![vs style](https://github.com/user-attachments/assets/2b3de0f3-8ec3-4cad-ada0-b25c14ace131)

## visual studio code:
![vscode style](https://github.com/user-attachments/assets/287c5cce-d505-481d-955f-ed1ee1da1ce5)

**Comment by sean-mcmanus** [comment]
I had a pre-existing issue at https://github.com/microsoft/vscode-cpptools/issues/10703 so I've re-activated that one.

**Comment by Willaaaaaaa** [comment]
@sean-mcmanus Got it, sir. Thank you for re-activating that issue. And how about the indent issue?

**Comment by sean-mcmanus** [comment]
@Willaaaaaaa The ident issue is fixed if you run the formatter. I'm not sure how we could fix it in a different way.
