### ISSUE TITLE
Parentheses parsing and outline display errors

### ISSUE THREAD

**Issue by meijialun** [microsoft/vscode-cpptools#12625]
### Environment

- OS and Version: Win10 x64
- VS Code Version: 1.90.2
- C/C++ Extension Version: 1.21.6
- If using SSH remote, specify OS of remote machine: No

### Bug Summary and Steps to Reproduce

Bug Summary:
When there are macros in the code that define conditional judgments, parentheses parsing and outline display will have errors

Steps to reproduce:
1. Define three functions
2. The second one contains #if 0
3. The third one contains #if XX=X
4. Observe the brackets highlighted and outline displayed

Expected behavior:
Parentheses parsing and outline display correct

![parenthesis_highlighting](https://github.com/user-attachments/assets/a31d6b56-e024-4488-a296-73787bbd7996)
[parenthesis_highlighting.zip](https://github.com/user-attachments/files/16743467/parenthesis_highlighting.zip)

### Configuration and Logs

```shell
No specific settings.
```

**Comment by sean-mcmanus** [comment]
@meijialun We're already tracking this issue with https://github.com/microsoft/vscode-cpptools/issues/9573
