### ISSUE TITLE
Unable to start debugging cpp with vscode.

### ISSUE THREAD

**Issue by mohsen74** [microsoft/vscode-cpptools#1262]
hello
I have a problem with debugging my cpp code with vscode that when I try to I get an error said "Unable to start debugging. Program path 'c:\Users\Moh3n\Desktop\New folder\tst.cpp' is missing or invalid"
my launch.jason file:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/tst.cpp",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/mingw/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
            
        }
    ]
}`

**Comment by bobbrow** [comment]
That looks like a source code file, not an executable.  Are you building an exe first?  You should put the path to the exe in the "program" field.

**Comment by mohsen74** [comment]
yes, I did that but still have the same problem.

**Comment by bobbrow** [comment]
What is the name of your exe?  Put that in the "program" field instead of the name of the cpp file.

**Comment by mohsen74** [comment]
same as my cpp file. I did that still have the same problem

**Comment by bobbrow** [comment]
your exe is named `tst.cpp`?  Try naming it `tst.exe` and put `tst.exe` in the "program" field.

**Comment by pieandcakes** [comment]
if you run tst.cpp from the command line does your program execute? 
does this actually exist? 'c:\Users\Moh3n\Desktop\New folder\tst.cpp'

**Comment by mohsen74** [comment]
I put tst.exe in program field and didn't work.
Yes it exists

**Comment by mohsen74** [comment]
I think my compiler has a problem.because vscode make the .exe file but when I try to open it doesn't work but after I recompile it with dev c++ i can run the .exe file( not in vscode)

**Comment by pieandcakes** [comment]
What do you mean by "VS code makes your .exe file"? Are you using a `task.json` to compile your code? If so, can you share your `task.json`

**Comment by pieandcakes** [comment]
Do you still need help with this? Can you comment/reopen if you do?

**Comment by leanjunio** [comment]
The same issue is happening with me actually. main.exe exists in the main workfolder but vscode cannot run it.

```
// Launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/main.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

```
// Tasks.json

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "g++ -g -Wall -std=c++11 main.cpp -o main",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": "$gcc"
        }
    ]
}
```

**Comment by avetrella** [comment]
Using mingw-w64 should solve the problem. 
You can switch to:
> "miDebuggerPath": "C:\\mingw64\\bin\\gdb.exe",

**Comment by jordanlui** [comment]
I'm having the same issue as mohsen74, but worried that I'm misunderstanding how to debug. I have exact same launch.json as mohsen74. 

Can I debug my .cpp program if it cannot successfully compile to a .exe? Or can I only debug a .exe file that regularly compiles?

I was trying to point to .cpp file since my code can't compile to a .exe. How else can I debug my .cpp file?

**Comment by pieandcakes** [comment]
@jordanlui Our debugger uses `gdb` for GNU C++, which requires you to have code compiled.

 If you are having problems compiling code, you can share the error and we can try and help you. Once you have it compiled you can debug. Compilation errors are usually code syntax errors or missing compiler flags that you need to specify.

**Comment by Blendfoul** [comment]
I'm having a similar issue. I've already got it working but since a few days ago after a few code changes and a build after gdb actually stopped executing or it seems to be the case.
So what happens is every time I launch gdb I can see the small loading bar bellow the task selector going on and on and nothing more happens... 
I'm not sure if it is vscode related or a gnome shell quirk but I would apreciate the help however. :smiley: 

Here is my launch.json
`"version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/server",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}` 
I'm running this on arch just for context.

**Comment by pieandcakes** [comment]
@Blendfoul your issue might be related to #2787 or #2842 . refer to the comments there for updates and a possible workaround.

**Comment by HutchinsonVandyke** [comment]
OK I am having a similar problem, but I think it differs from the both. VS Code was working great until the debugger began giving me false positives on coding mistakes. I decided to compile in my command terminal with MinGW. After that I have been getting this message when I do a build task:

`cl.exe : The term 'cl.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ cl.exe /EHsc /Zi /Fe: main.exe main.cpp ExpTree.cpp PostFixTokens.cpp
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (cl.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`


When I try to run the debugger after, it says: 
launch: program 'C/...main.exe' doesn't exist
 and then prompts me to open my launch.json

also peculiarly now, there is no executable where there was in my workspace folder. 

here is my launch.json: 
`{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "(msvc) Launch",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "${workspaceFolder}/main.exe",
        "args": [],
        "stopAtEntry": true,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": true
      }
    ]
  }`

**Comment by pieandcakes** [comment]
@HutchinsonVandyke I think you are mixing toolsets. `cl.exe` is for Visual C++. MinGW uses `gcc` or `g++` for c/c++ compilation. If you want to use `cl.exe` make sure that you have the Visual C++ compiler installed and on the path.

**Comment by TheSoulsKeeper** [comment]
I am having a similar issue, when trying to debug I get the following error:
![Untitled3](https://user-images.githubusercontent.com/42913159/163332582-f8242071-e729-426e-9e97-fdbf4ca4fdb0.png)
which is not the full name of the folder for some reason, this is the full path
`C:\Users\*redacted*\Desktop\Projects\C\C Programming For Beginners - Master the C Language\Section 3\HelloWorld`

here are my launch.json and task,json files as well:

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": " ${workspaceFolder}/helloworld.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/cygwin64/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}`

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build hello world",
            "type": "shell",
            "command": "gcc",
            "args": [
                "-g",
                "-o",
                "helloworld",
                "helloworld.c"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}`

**Comment by TheSoulsKeeper** [comment]
Solved the issue by removing all the spaces in the folders names

**Comment by singhpriansh** [comment]
Can anyone help me to figure out whats wrong
Launch.json

        {
            "preLaunchTask": "g++ build active file (linux)",
            "name": "g++ debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "~/Public/programming_folder/./${fileBasenameNoExtension}.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                }
            ],
        },

Task.json
        {   // Linux executable maker
            "type": "shell",
            "label": "g++ build active file (linux)",
            "command": "g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "~/Public/programming_folder/${fileBasenameNoExtension}.out"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "group": "build",
            "problemMatcher": ["$gcc"],
        },

**Comment by singhpriansh** [comment]
The same error persists on mac
<img width="265" alt="Screenshot 2023-03-10 at 1 08 10 PM" src="https://user-images.githubusercontent.com/51377227/224253089-ac168664-ec9c-41bf-9c97-6ae848b9cc3f.png">

**Comment by sean-mcmanus** [comment]
@singhpriansh It looks like launch.json on Mac doesn't resolve the `~` -- it should work after you replace that by `/Users/<username>`

**Comment by singhpriansh** [comment]
This is my code:

       {
            "name": "g++ debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "/Users/singhpriansh/Public/programming_folder/./${fileBasenameNoExtension}.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "miDebuggerPath": "/usr/bin/dbg",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file (linux)",
        }, 

This is what happens


<img width="264" alt="Screenshot 2023-03-18 at 7 16 08 PM" src="https://user-images.githubusercontent.com/51377227/226109939-6274ffbb-5990-4d35-ae7d-9f0e14032d05.png">
