### ISSUE TITLE
please add visual studio C/C++ tool chains

### ISSUE THREAD

**Issue by Yensan** [microsoft/vscode-cpptools#1263]
I  have installed visual studio express and its C/C++ toolkit. But I find it is imposible using VC++ in VScode.(Or, just I don't know how to.)
So, please add the VC++ tool chain suport  into VScode (compiler/linker/header/lib/debugger)

**Comment by Yensan** [comment]
At present, I have achieved compiling by VC++, but can not debugging with VC++ tool (maybe it is cdb.exe)
**c_cpp_properties.json**

>  "includePath": [
                "${workspaceRoot}", "${workspaceRoot}/3rd/include",
                "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.10.25017/include",
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/"
            ],



**tasks.json**

> {"label": "VC_Compile",
            "group": "build",
            "windows": {"command": "\"C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcvarsall.bat\" amd64 && cl"},
            "args": ["/W4", "/MTd", "${file}",  "/link", "/out:${fileDirname}/${fileBasenameNoExtension}.o"],
            "type": "shell",
            // "dependsOn": "VC_ENV",
            "presentation": {"echo": true, "reveal": "always", "focus": false, "panel": "shared"},
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative","${workspaceRoot}"],
                "pattern": {"regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                            "file": 1,"line": 2,"column": 3,"severity": 4,"message": 5}
            }
        },

**Comment by sean-mcmanus** [comment]
I use the C++ Windows configuration of type "cppvsdbg" in launch.json. VS Code has a Debugger tab on the left with a Start Debugging button.

**Comment by Yensan** [comment]
Thank you for your anwser. 
I use MinGW for a long time,  because it is convinient cross to Linux/MacOS gcc. Now I write some C/C++ Extension to python project,  it must compiled with VC++ in Windows.
I can debug with MinGW. But I don't know how to setting with VC++. 
Edited tasks.json, now I have compiled it with VC++ to *.o(can run as same with *.exe)  and *.pdb file; edited launch.json, it has correct symbolSearchPath. **But VScode C/C++ say:**

> Loaded 'F:\Note\LinuxAndC-master\tcpl\tcpl1_1hello.o'. Symbols loaded.
Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.

Can you tell me, what should I do? thank you very much.
**tasks.json:**

>            {"label": "VC_Compile",
>              "group": "build",  
>             "windows": {"command": "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" amd64 && cl"},
>             "args": ["/W4", "/MTd", "${file}","/link", "/DEBUG","/out:${fileDirname}/${fileBasenameNoExtension}.o", "/PDB:${fileDirname}/${fileBasenameNoExtension}.pdb"],
>             "type": "shell",
>             "presentation": {"echo": true, "reveal": "always", "focus": false, "panel": "shared"},
>             "problemMatcher": {
>                 "owner": "cpp",
>                 "fileLocation": ["relative","${workspaceRoot}"],
>                 "pattern": {"regexp": "^(.*):(//d+):(//d+)://s+(warning|error)://s+(.*)$",
>                             "file": 1,"line": 2,"column": 3,"severity": 4,"message": 5}
>             }

**launch.json:**

>           {"name": "VC_Debug",
>             "type": "cppvsdbg",
>             "request": "launch",
>             "program": "${fileDirname}/${fileBasenameNoExtension}.o",
>             "args": [],
>             "stopAtEntry": true,
>             "cwd": "${fileDirname}",
>             "symbolSearchPath": "${fileDirname}",
>             "environment": [],
>             "externalConsole": false
>         },
