### ISSUE TITLE
1.22.2 has some recursive includes related crashes

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#12643]
One case might occur some times after deleting a file or folder.

**Comment by vishwa2006-creator** [comment]
![Uploading cording password.PNG…]()

**Comment by vishwa2006-creator** [comment]
the include < stdio.h > is showing error

**Comment by sean-mcmanus** [comment]
@vishwa2006-creator Your posts don't appear to be related to this issue and don't provide enough information.

**Comment by sean-mcmanus** [comment]
@Colengms Should this be closed as fixed by https://github.com/microsoft/vscode-cpptools/releases/tag/1.22.3 or not?

**Comment by Colengms** [comment]
@sean-mcmanus No, the root cause is still causing crashes via other routes and is going to require the proper fix.
