### ISSUE TITLE
Supply JSON schemas for YAML files

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-cpptools#12651]
### Feature Request

Files like `.clang-format` etc. have a JSON schema, see https://json.schemastore.org/clang-format.json.

Users can reference those schemas in a few ways in VS Code. For example if using the [most common YAML extension in VS Code](https://github.com/redhat-developer/vscode-yaml), one can associate a schema [like this](https://github.com/redhat-developer/vscode-yaml?tab=readme-ov-file#associating-a-schema-in-the-yaml-file):

```yaml
# yaml-language-server: $schema=<urlToTheSchema>
```

However, to avoid this manual addition, this extension should automatically contribute so that common file name conventions (`.clang-format`, `.clang-tidy` etc.) automatically gets the correct JSON schemas.

I believe this is one way to get this working: https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation

**Comment by bobbrow** [comment]
Thank you for the suggestion.

I took a look at this and it turns out that there is a whole YAML language server provided by the RedHat YAML extension.  It is not provided by VS Code so it's not something we can just plug into.  The contribution point VS Code offers will provide JSON language services, but it does not provide services for YAML (as far as my testing showed).

Unfortunately, it is too much work for us to re-implement YAML language services in our extension and I feel it is a bit out of scope for us, especially considering that the RedHat extension seems to already provide a good experience.  I did not need to run the command you mentioned to enable the support.  I just opened a `.clang-format` file, changed the language ID to YAML and selected the schema from the status bar.

**Comment by thernstig** [comment]
@bobbrow thank you for looking into this.

For some reason, VS Code gives automatic validation via the JSON schema store for e.g. `.clang-tidy`:

![image](https://github.com/user-attachments/assets/3dd8a9ea-2237-475c-a6bf-3537a10608d3)

It does not do that for `.clang-format`:

![image](https://github.com/user-attachments/assets/d60d3116-773f-4ecf-bbbc-3eefffc2e747)

I wonder how VS Code finds one, but not the other. If that problem is solved then I suppose this problem is solved anyway.

**Comment by bobbrow** [comment]
@thernstig are you saying that you are getting language services for .clang-tidy without the RedHat YAML extension installed?  That was not my experience.  Do you have other extensions installed that might be doing it?  Or are you saying you get validation only (no auto-complete, etc)?

**Comment by thernstig** [comment]
No, I do need the RedHat YAML extension. I am saying that with the extension, `.clang-tidy` gets automatically referenced to the correct JSON schema from the https://github.com/SchemaStore/, whilest `.clang-format` does not.

My feature request was an idea to solve this in another way, to make sure it works for everyone. But seeing as the VS Code API only supports contributions for JSON validation, and not YAML, this topic kind of turned into a "why does `.clang-format` not get JSON schema validation when using the RedHat YAML extension, whilst `.clang-tidy` does. 😆 

This was never my intention, and nothing you can affect in this repo, so if this was derailed I am sorry! I will try to figure this out.

**Comment by bobbrow** [comment]
Oh, I see now. 👍 I think you could open an issue for the RedHat extension to add clang-format's schema to the list.  https://github.com/redhat-developer/vscode-yaml/issues/new/choose.  Otherwise, you can edit the `yaml.schemas` setting manually to add it.

**Comment by thernstig** [comment]
Might do that. The problem is I searched their entire repo and found now difference in how they expose the clang-tidy and clang-format schemas in their code, both should be received from the SchemaStore. Maybe some caching issue. Will dig deeper, thanks!

**Comment by bobbrow** [comment]
I believe it's in their language server which I did not see implemented in that repo. I see a request here that looks like the entry point:

https://github.com/redhat-developer/vscode-yaml/blob/41e0be736f2d07cdf7489e1c1c591b35b990e096/src/schema-status-bar-item.ts#L116
