### ISSUE TITLE
${command:pickRemoteProcess} doesn't seem to work when using Bash on Windows

### ISSUE THREAD

**Issue by hajekj** [microsoft/vscode-cpptools#1265]
Reopening https://github.com/Microsoft/vscode-cpptools/issues/538

When trying to remotely debug a process with WSL, I hit following error:

```
Command failed: "C:\Windows\sysnative\bash.exe"  "bash -c 'uname && if [ $(uname) == "Linux" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) == "Darwin" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi'"
The system cannot find the path specified.
```

I went through the extension's source and discovered folowing: 
When I changed the path from _sysnative_ to _system32_ and corrected the quotes dirrectly within the extension's source, it executed however the exec never seems to finish. I tried reproducing by this simple code:
```javascript
const child_process = require("child_process");

child_process.exec(`C:\\Windows\\System32\\bash.exe -c "bash -c 'uname && if [ $(uname) == "Linux" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) == "Darwin" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi'"`, { cwd: "C:\\Users\\hajek\\Source\\Temp\\", maxBuffer: 500 * 1024 }, (error, stdout, stderr) => {
    console.log(error, stdout, stderr);
});
```
Simply the execution never seems to finish. When I execute the same command from my command line, it works fine.

cc: @pieandcakes

**Comment by pieandcakes** [comment]
@hajekj Which version of Windows are you running on? is it Creator's Update or newer?

**Comment by pieandcakes** [comment]
Documentation can be found [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/Windows%20Subsystem%20for%20Linux.md). You need to have Windows build 15063 or newer.

**Comment by pieandcakes** [comment]
@hajekj The reason for `sysnative` is that we are a 32-bit application. In 32-bit processes, `sysnative` allows us to access the `system32` folder that normally would only be accessible for 64-bit processes. I assume when you are calling it from the commandline, you are calling it from a 64-bit process which does not have `sysnative`. You can read more about it [here](https://support.microsoft.com/en-us/help/942589/a-32-bit-application-cannot-access-the-system32-folder-on-a-computer-t).

Your first quote is missing a "-c" between c:\windows\sysnative\bash.exe and the command.  The correct command should be `"C:\Windows\sysnative\bash.exe" "-c" "bash -c 'uname && if [ $(uname) == "Linux" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) == "Darwin" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi'"`

If you want to simulate how we call it, you can go to your `c:\windows\syswow64` folder and run `cmd.exe` there and then just paste the command above. you should see a list of processes running on that machine.

**Comment by hajekj** [comment]
@pieandcakes: I am running latest Windows 10 Fall Creators Update 1709 x64. Same with VS Code and CPP Tools version. VS Code version is 1.18.1, x64 version.

Thanks for the explanation related to the sysnative folder. I am sorry I forgot to mention that I am trying to work with remote attach and I tried using the code mentioned both in the [sample](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/Windows%20Subsystem%20for%20Linux.md) and generated by the extension itself as WSL Attach. I have tried running the line above from the syswow64 cmd and it works, however VS Code doesn't seem to work with it.

The sample provided in the docs results with:
```
Command failed: "c:\windows\sysnative\bash.exe" "-c" "bash -c 'uname && if [ $(uname) == "Linux" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) == "Darwin" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi'"
The system cannot find the path specified.
```

FYI, the extension itself generates following config for WSL Attach (any reason why is it missing the -c in pipeArgs and pickRemoteProcess as well?):
```json
        {
            "name": "(gdb) Bash on Windows Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "enter program name, for example ${workspaceFolder}/a.exe",
            "processId": "${command:pickProcess}",
            "pipeTransport": {
                "debuggerPath": "/usr/bin/gdb",
                "pipeProgram": "C:\\Windows\\sysnative\\bash.exe",
                "pipeArgs": [],
                "pipeCwd": ""
            }
        },
```

**Comment by pieandcakes** [comment]
@hajekj It looks like theres a problem in WSL: https://github.com/Microsoft/WSL/issues/2592 We need to wait until its fixed.
