### ISSUE TITLE
running slow

### ISSUE THREAD

**Issue by anurag166** [microsoft/vscode-cpptools#12669]
Type: <b>Bug</b>

taking more than 1 minute to run code

Extension version: 1.21.6
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (7.91GB free)|
|Process Argv|--crash-reporter-id 7d6b7089-b142-41dc-ba51-e3b2c25176cb|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
@anurag166 We need more info. What does "run code" mean?

**Comment by anurag166** [comment]
When I run a simple code like printing hello world it take about 1 minutes
to execute

**Comment by sean-mcmanus** [comment]
@anurag166 Does it repro with our C/C++ extension disabled? Do you know what is causing it to take so long? Our C/C++ extension is not generally involved in the running of the code you run.

**Comment by anurag166** [comment]
Yes all extension are disabled

**Comment by anurag166** [comment]
I have reinstalled and done everything but it is taking so much time to run
a simple code

**Comment by sean-mcmanus** [comment]
@anurag166 If the issue repros with our extension disabled, then it's not a bug with our extension. Is it slow when you run the program outside of vscode on the command line? If the bug only repros in VS Code, you should file an issue with VS Code at https://github.com/microsoft/vscode/issues . Otherwise, it might be a bug with your OS, compiler tools, or your application, etc.
