### ISSUE TITLE
"Macro calls" in the navigation list (alt-n)

### ISSUE THREAD

**Issue by sbrw** [microsoft/vscode-cpptools#1266]
- Ubuntu 17.10
- vscode 1.18.1
- C/C++ 0.14.2

1. Clone https://github.com/tmux/tmux.git
2. Install libevent-1.4.2 and libevent-dev for header file dependency in tmux
3. Open vscode and add the tmux folder to the workspace
4. Open the file tmux-file "alerts.c" in vscode
5. Navigate... (alt-n) and check the listed available symbols in alerts.c. The first two listed (TAILQ_FOREACH and TAILQ_FOREACH_SAFE) are actually macros used inside two functions defined in the file. These two functions show up in the list as well, but selecting them only puts the cursor at their declaration, never definition.
6. Selecting the macros in the list puts the cursor at the line of usage in the functions
7. Commenting out the macro usage in the functions removes them from the navigation list and the cursor is put at the function definition when selecting corresponding function.

Guess I can be missing some defines required for tmux configuration, but:
- I assume the macros should not appear at all in the navigation?
- Selecting a function from the navigation list should set the cursor on the function definition?

**Comment by sean-mcmanus** [comment]
This is "by design". The syntax breaking macros need to be added to a cpp.hint file in your workspace folder, see https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2017 , i.e. add something like
```
#define TAILQ_FOREACH(x, y)
```
