### ISSUE TITLE
c/cpp function navigation issues

### ISSUE THREAD

**Issue by lianzisong** [microsoft/vscode-cpptools#1267]
VSCode Version: 1.18
OS Version: win 10
Steps to Reproduce:

open the folders through the vscode
press the alt+N ,then check the result.
the cpp file navigation result :
![image](https://user-images.githubusercontent.com/16344340/32998807-17c8ff1c-cdd9-11e7-8f7b-2be16b3d4d0e.png)
and the H file navtigation result:
image
![image](https://user-images.githubusercontent.com/16344340/32998814-257c93da-cdd9-11e7-8c55-9e95df3c3153.png)

but not all the result is the same. some cpp may be OK.
![image](https://user-images.githubusercontent.com/16344340/32998816-2bbee130-cdd9-11e7-8349-81675b9d0bd5.png)

**Comment by bobbrow** [comment]
This function is for code navigation inside a single file.  It does not show results from outside of the active file.  Is it failing to list a function in the current file?

We will need more information in order to determine if there is a bug here or not.

**Comment by lianzisong** [comment]
Well, apparently I wanna show the function in the current file, other wise I will use the Ctrl+T.One day I update the vs code, then this issue shows up. So i create an issue in the vs code repository, but the administrator advise that this problem belongs to the c++ plug-in.in fact it works better before . It shows almost all files except some super complicate file ,it’s acceptable.but now, almost all cpp files don’t show the expect results .Btw, I can’t remember what version of vs code while this problem shows.
            On 11/21/2017 00:50, Bob Brown wrote: This function is for code navigation inside a single file.  It does not show results from outside of the active file.  Is it failing to list a function in the current file?
We will need more information in order to determine if there is a bug here or not.

**Comment by sean-mcmanus** [comment]
It sounds like navigation isn't working for you for particular C++ files. I think we need a repro. My guess is that we're failing to parse certain files. Do any other features work in the file that fails to show a navigation list?

**Comment by lianzisong** [comment]
@sean-mcmanus I'm not sure whether the "particular" C++ files is the key , but as I described by the pictures ,almost all cpp files can't show the expected results ,but only some(maybe one or two) of cpp files do.
then I try other open source projects ,it works well ,just my cpp files don't.that's weired .
BTW,the source insight 3/4 shows the function list well .

**Comment by lianzisong** [comment]
@sean-mcmanus I try the F12 ,it will jump to the H file which point to function declaration .
that's not what I mean to .

**Comment by sean-mcmanus** [comment]
If Go To Definition is not going to the actual definition (only the declaration) that means the definition is failing to get parsed and added to the symbol database, which would be why it's not being found for the navigation list. If you can set your C_Cpp.loggingLevel to Information you might see some diagnostic info. You might want to try a Reset IntelliSense Database command (or just editing the document and saving should also cause a reparse of the file).

**Comment by sean-mcmanus** [comment]
Also, what is your browse.path? I assume you have ${workspaceRoot} set and your source files are under there. If it's not set correctly, then the files could not be added to the database.

**Comment by lianzisong** [comment]
@sean-mcmanus I've tried to edit/save the files ,but the result still seems failed.
what do you mean browse.path? I edit my project by drag/move the folders into the vs-code, or just right click to open the folder by the vs-code.
I think I should let you know that ,my files is edited by the GBK not utf-8. it contains some chinese words ,is it will effect the parsing?

**Comment by sean-mcmanus** [comment]
Ah, that makes sense. Yeah, the use of GBK is the cause. We only support UTF-8 currently. See https://github.com/Microsoft/vscode-cpptools/issues/806 . If you do an Edit Configuration command it will create a c_cpp_properties.json file with a browse.path.

**Comment by lianzisong** [comment]
@sean-mcmanus OK ,maybe the encode/decode is the cause , but I still hope it can support more encoding ,not just only utf-8. 
I will try it again while it can support other encoding.
I will close this issue now .
thanks.
