### ISSUE TITLE
Cannot open outputfile ; No such file or directory

### ISSUE THREAD

**Issue by phching** [microsoft/vscode-cpptools#12675]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/12673

<div type='discussions-op-text'>

<sup>Originally posted by **phching** September  3, 2024</sup>
I am code beginner but i just find a problem that cofused me a lot , please help!
When i open the folder from the desktop and run the cpp file , the error appears. 
`Starting build...
cmd /c chcp 65001>nul && C:\mingw64\bin\g++.exe -fdiagnostics-color=always -g C:\Users\super\OneDrive\桌面\permission\main.cpp -std=c++20 -o C:\Users\super\OneDrive\桌面\permission\main.exe
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file C:\Users\super\OneDrive\桌面\permission\main.exe: No such file or directory
collect2.exe: error: ld returned 1 exit status

Build finished with error(s).

 *  The terminal process terminated with exit code: -1. 
 *  Terminal will be reused by tasks, press any key to close it. `
 
However , when I open the file from documents , the cpp file run properly . 
` *  Executing task: C/C++: g++.exe build active file 

Starting build...
cmd /c chcp 65001>nul && C:\mingw64\bin\g++.exe -fdiagnostics-color=always -g "C:\Users\super\OneDrive\Dokumen\C++ roadmap\C++\Ch.2_DivingIn\2.4_statement.cpp" -o "C:\Users\super\OneDrive\Dokumen\C++ roadmap\C++\Ch.2_DivingIn\2.4_statement.exe"

Build finished successfully.
 *  Terminal will be reused by tasks, press any key to close it. `</div>

**Comment by phching** [comment]
@sean-mcmanus Thank you for your advice but it seem that there is no issue about the permisson of Onedrive folder , as the permission of onedrive folder in documents and desktop are the same.  What should i do next please.

**Comment by sean-mcmanus** [comment]
@phching What happens if you run the command `C:\mingw64\bin\g++.exe -fdiagnostics-color=always -g C:\Users\super\OneDrive\桌面\permission\main.cpp -std=c++20 -o C:\Users\super\OneDrive\桌面\permission\main.exe` from the command line?

**Comment by phching** [comment]
@sean-mcmanus  C:\Users\super>C:\mingw64\bin\g++.exe -fdiagnostics-color=always -g C:\Users\super\OneDrive\桌面\permission\main.cpp -std=c++20 -o C:\Users\super\OneDrive\桌面\permission\main.exe
cc1plus.exe: fatal error: C:\Users\super\OneDrive\permission\main.cpp: No such file or directory
compilation terminated.

**Comment by sean-mcmanus** [comment]
@phching The issue repros with g++.exe on the command line so it's not a bug with our C/C++ extension. The incorrect output of `桌面` suggests that it could be a bug with the mingw g++.exe handling of those non-ASCII characters in the path. You may want to try using a new version of g++ that might have that bug fixed or switching to a folder that doesn't have `桌面` in the path.
