### ISSUE TITLE
Microsoft C/C++ extension not working

### ISSUE THREAD

**Issue by Cuper245** [microsoft/vscode-cpptools#12674]
### Environment

- OS and Version: Microsoft Windows 11 Home, 10.0.22631 Build 22631
- VS Code Version: 1.92.2
- C/C++ Extension Version: v1.21.6

### Bug Summary and Steps to Reproduce

Bug Summary:
I installed the "clangd" extension and it told me it interfered with the C/C++ extension so I uninstalled it but now the autocomplete function doesn't work.

### Configuration and Logs

```shell
I don't have the c_cpp_properties.json file.

And I can't run C/C++: Log Diagnostics, it doesn't appear when I try on the command palette.
```

**Comment by sean-mcmanus** [comment]
@Cuper245 You uninstalled which extension? You need to have a C/C++ file active for the C/C++: Log Diagnostics command to work.

**Comment by Cuper245** [comment]
I uninstalled "clangd" and I already have an active file. These are the only options I have when I search "C/C++".

![image](https://github.com/user-attachments/assets/11612530-d9cc-4425-a41e-3cf31fb15b19)

**Comment by sean-mcmanus** [comment]
@Cuper245 Change C_Cpp.intelliSenseEngine to "Default".

**Comment by Cuper245** [comment]
Just change that, and it works. Thank you for your help!!!
