### ISSUE TITLE
C++ debug in a strange way

### ISSUE THREAD

**Issue by Willaaaaaaa** [microsoft/vscode-cpptools#12689]
Type: <b>Bug</b>

I can't tell in certain words. Please watch the video I post below.

The code I run:
```cpp
#include <iostream>

int GCD(int a, int b) {
    if (b == 0) {
        return a;
    }
    else
        return GCD(b, a % b);
}

int main() {
    std::cout << "GCD Calculator\nPlease input 2 numbers: ";
    int a, b;
    std::cin >> a >> b;

    std::cout << "The GCD of the 2 nums is: " << GCD(a, b) << std::endl;
}
```

Extension version: 1.22.2
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (3.65GB free)|
|Process Argv|D:\\Workspace\\数据结构与算法.code-workspace --crash-reporter-id 8a99c087-27c5-481e-a460-d896e99f2536|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by Willaaaaaaa** [comment]
https://github.com/user-attachments/assets/89731785-9b07-411e-998d-85bd96fddcca

I really don't know how to handle this sort of question. Hope you guys can help me!

**Comment by Willaaaaaaa** [comment]
I don't know if this is a problem with my compiler. If this is not a common issue, please **let me know which compiler you have chosen** and I will replace it with the same one as yours. BTW, I am using mingw-w64 from msys2. My gdb version is 14.1.

**Comment by sean-mcmanus** [comment]
The value of a and b in the Watch window is just the value of the variables at the particular stack frame. The watch window doesn't show the return value. The code uses recursion so at the end it goes back up the stack and a and b change to their previous values before calling the recursive gcd call. The weird file that pops up in the end is just the a C runtime file. You can ignore it or just don't preset step over after you're done running your main method.
