### ISSUE TITLE
[Help]How to set mingw's includePath to c_cpp extension

### ISSUE THREAD

**Issue by EECSGEEK** [microsoft/vscode-cpptools#1269]
I am a nood, I don't know how to edit json files.
I open my C project folder,I don't know how to edit "c_cpp_properties.json"
<h2>1、here is my gcc/g++ include path</h2>
<img src="http://p2.cdn.img9.top/ipfs/QmZstVgDsqVHf5PJmGbEvwV32YQ4yA4EsX195p8hcKcgWc?2.PNG">

**Comment by EECSGEEK** [comment]
<h2>2、I try to add includePath to c_cpp_properties.json</h2>

>     {
            "name": "mingw",
            "includePath": [
                "C:/Users/76320/Software/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include",
                "C:/Users/76320/Software/mingw/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/tr1",
                "C:/Users/76320/Software/mingw/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++",
                "C:/Users/76320/Software/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include-fixed",
                "C:/Users/76320/Software/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Users/76320/Software/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }


<img src="http://p1.cdn.img9.top/ipfs/QmPmfwBHENxv7wG29D5ighFAXXt9xboEeV4a7RcELEDMHD?1.png">
</img>

**Comment by EECSGEEK** [comment]
<img src=”https://i.imgur.com/Ji49Npg.png“></img>
https://i.imgur.com/Ji49Npg.png
[](”https://i.imgur.com/Ji49Npg.png“)
I add gcc and g++ search path to it
But it can not recognize
>identifier "printf" is undefined
file: 'file:///c%3A/Users/76320/Code/C/itoa.cpp'
severity: 'Error'
message: 'identifier "itoa" is undefined'
at: '11,35'
source: ''
code: 'undefined'

#### windows.h not find
but I can run this program using gcc/g++ command

* OS:win10_1709
* vscode_version:1.8.1
* gcc/g++ version:7.2.0
* extension:0.14.2

**Comment by Yensan** [comment]
1. If you install the MinGW correctly (I use a simplificationdo: install codeblocks), it can include and link standard lib normally, just follow this c_cpp_properties.json

>             "includePath": [
>                 "${workspaceRoot}", 
>                 "C:/CodeBlocks/MinGW/include/",
>                 "C:/CodeBlocks/MinGW/lib/gcc/mingw32/4.9.2/include/",
>                 "C:/CodeBlocks/MinGW/lib/gcc/mingw32/4.9.2/include/c++",
>                 "C:/CodeBlocks/MinGW/lib/gcc/mingw32/4.9.2/include/c++/mingw32",

2. If you want to use third lib, there are some complex settings in c_cpp_properties.json and tasks.json. I use Gtest with MinGW, put gtest include file in `${workspaceRoot}\3rd\include`, lib files in `${workspaceRoot}/3rd/minGWlib`.  Then, 
c_cpp_properties.json add a path `${workspaceRoot}\3rd\include`
tasks.json use `-I` and `-L` tells gcc/g++ what paths for Include and Lib:
>         {"label": "Gtest_Compile",
>             "linux": {"command": "g++"},
>             "windows": {"command": "C:/CodeBlocks/MinGW/bin/g++.exe"},
>             "osx": {"command": "clang++"},
>             "args": ["${fileDirname}/${fileBasenameNoExtension}*", // ${fileDirname}/gtest*main*
>                  "-g", "-o", "${fileDirname}/${fileBasenameNoExtension}.o", "-lgtest",
>                  "-I", "${workspaceRoot}/3rd/include", "-L", "${workspaceRoot}/3rd/minGWlib"],
>             "type": "shell",
>             "dependsOn": "clear_o_files",
>             "presentation": {"echo": true, "reveal": "always", "focus": false, "panel": "shared"},
>             "problemMatcher": {
>                 "owner": "cpp",
>                 "fileLocation": ["relative","${workspaceRoot}"],
>                 "pattern": {"regexp": "^(.*):(//d+):(//d+)://s+(warning|error)://s+(.*)$",
>                             "file": 1,"line": 2,"column": 3,"severity": 4,"message": 5}
>             }
>         },

**Comment by EECSGEEK** [comment]
@Yensan I add all '#include <...> search starts here:' to "includePath" and "browse", it works.
#### I bulid a simple task to run it
>C:\Users\76320\Code\C>gcc itoa.cpp -o e && e
itoa.cpp is running
Time spent:501ms
### My mingw/bin has gdb.exe, how to use it(vscode)

**Comment by Yensan** [comment]
debug and build are two level things:  build(compile -- link) --run OR  debug
build is in tasks.json, debug is in launch.json
my launch.json, you can visit vscode doc for details.

>         {"name": "C Launch",
>             "type": "cppdbg",
>             "request": "launch",
>             "program": "${fileDirname}/${fileBasenameNoExtension}.o",//"${workspaceRoot}/${file}.exe"
>             "args": [],
>             "stopAtEntry": true,
>             "cwd": "${workspaceRoot}",
>             // "preLaunchTask": "Gtest_Compile", // "C_Compile",
>             "environment": [],
>             "externalConsole": true, //"console": "integratedTerminal",
>             "linux": {"MIMode": "gdb"},
>             "osx": {"MIMode": "lldb"},
>             "windows": {"MIMode": "gdb","miDebuggerPath":  "C:/CodeBlocks/MinGW/bin/gdb.exe"},
>             "setupCommands": [{
>                     "description": "Enable pretty-printing for gdb",
>                     "text": "-enable-pretty-printing",
>                     "ignoreFailures": true
>             }]
>         },

**Comment by EECSGEEK** [comment]
[Error]Unable to start debugging. The value of miDebuggerPath is invalid

> "miDebuggerPath": "C:/Users/76320/Software/mingw/mingw64/gdb.exe",

### My Tasks.json can work
### Using terminal gdb.exe is ok, but vscode gdb debuger don't work
```
C:\Users\76320\Code\C>gdb a.exe
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
```

@Yensan I can use gdb on terminal is enough,I think current version of vscode don't support gdb debug for windows.
I think I can press F5 build and run .cpp files is enough(like C-free software)

<img src="http://p0.cdn.img9.top/ipfs/QmXnC2MJ2k26paiNosoVoPf1s6QbfLA62Y9ncbLoQFP8Jm?0.PNG"></img>

**Comment by Yensan** [comment]
maybe vscode has not permission to access. As ususal, I will install such as:   c:/ python;   c:/ java;  c:/ MinGW....
But I think the best anwser is in VScode Doc, not me.    ^_.^

**Comment by sean-mcmanus** [comment]
@pieandcakes Do you know how to use gdb from VS Code on Windows?

**Comment by pieandcakes** [comment]
@EECSGEEK can you provide your `launch.json` ? If you are specifying that gdb, make sure it can run in `mi` mode. To test that, try and launch `gdb` with the commandline flag `--interpreter=mi`. We rely on that to launch `gdb` in the correct mode so we can communicate it. 

We support `gdb` on Windows. I think you might have a configuration issue. If you want to configure F5 to build AND run, you need to create a [`task.json`](https://code.visualstudio.com/Docs/editor/tasks) to do the build and add a line in your `launch.json` specifying your `"preLaunchTask"` which will tell it to kick off the build before the debugger launching starts.

**Comment by pieandcakes** [comment]
@EECSGEEK Also, when you compile with `gcc`, you need to specify `-g` compiler flag to include symbols so the debugger has enough info to debug your executable.

**Comment by EECSGEEK** [comment]
@pieandcakes My lauch.json:
<img src="http://p3.cdn.img9.top/ipfs/QmThfLYxuwmf3NpjnVbTWqojxZUB4AykeUXD5U5Wzpbncz?3.png"></img>

My tasks.json
>  "tasks": [
    {
      "label": "run",
      "type": "shell",
      "command": "gcc",
      "args": [
        "itoa.cpp", "-g && a"
      ]
    }
  ]

my mingw is ok,no problem with mingw path
both gdb and gcc is in my env_path.

**Comment by Yensan** [comment]
C/C++ plugin is working very well with MinGW(gcc in Win) and Clang(llvm in MacOS) in my settings. I have compiled/linked/run/debuged the C/C++ code smoothly with MinGW. And I also use MinGW/Clang with Gtest (this is "how to use third party lib"). C/C++ plugin works very well.

For my opinoin, you may search for "gcc compiler args", and look up VScode Doc in Github.

my tasks for MinGW:
delete output file every time. If you compile cpp, change to g++, but must use flag `-g` and `-Wall`.  Using `-o dir/filename`  to specify output target is better for debugging & lanching settings.
>         {"label": "C_Compile",
>             "group": {"kind": "build","isDefault": true},
>             "linux": {"command": "gcc"},
>             "windows": {"command": "C:/CodeBlocks/MinGW/bin/gcc.exe"},
>             "osx": {"command": "clang"},
>             "args": ["${file}", "-g","-std=c99", "-Wall", "-o", "debug/${fileBasenameNoExtension}.o"],
>             "type": "shell",
>             "dependsOn": "clear_o_files",
>             "presentation": {"echo": true, "reveal": "always", "focus": false, "panel": "shared"},
>             "problemMatcher": {
>                 "owner": "cpp",
>                 "fileLocation": ["relative","${workspaceRoot}"],
>                 "pattern": {"regexp": "^(.*):(//d+):(//d+)://s+(warning|error)://s+(.*)$",
>                             "file": 1,"line": 2,"column": 3,"severity": 4,"message": 5}
>             }
>         },
>         {"label": "clear_o_files",
>             "linux": {"command": "cd ${workspaceRoot} && find  ${fileDirname} -name '*.o' -exec rm -rf {} //;  "},
>             "windows": {"command": "cd ${workspaceRoot} && del /q/f/s *.o *.obj && del /q debug"},
>             "osx": {"command": "cd ${workspaceRoot} && find ${workspaceRoot} -name '*.o' -delete"},
>             "type": "shell",
>             "presentation": {"echo": true, "reveal": "always", "focus": false, "panel": "shared"},
>             "problemMatcher": ["$tsc"]
>         }

my launch

>         {"name": "C Launch",
>             "type": "cppdbg",
>             "request": "launch",
>             "program": "debug/${fileBasenameNoExtension}.o",// ${fileDirname}  "${workspaceRoot}/${file}.exe"
>             "args": [],
>             "stopAtEntry": true,
>             "cwd": "${workspaceRoot}",
>             "preLaunchTask": "C_Compile",
>             "environment": [],
>             "externalConsole": true, //"console": "integratedTerminal",
>             "linux": {"MIMode": "gdb"},
>             "osx": {"MIMode": "lldb"},
>             "windows": {"MIMode": "gdb","miDebuggerPath":  "C:/CodeBlocks/MinGW/bin/gdb.exe"},
>             "setupCommands": [{
>                     "description": "Enable pretty-printing for gdb",
>                     "text": "-enable-pretty-printing",
>                     "ignoreFailures": true
>             }]
>         },

**Comment by pieandcakes** [comment]
@EECSGEEK Does your app need that `arg` of `--interpreter=mi` ? We already send it to gdb so you don't need to add that. 

Your compile command seems strange as I don't know what `-g && a` does. To get what you want, you probably just need: 
```
"tasks": [
{
"label": "run",
"type": "shell",
"command": "gcc",
"args": [
"itoa.cpp", "-g", "-o", "a.exe"
]
}
]
```

**Comment by EECSGEEK** [comment]
@pieandcakes  gcc has no arv"--interpreter"
--interpreter=mi is the gdb.exe argument


> C:\Users\76320\Code\C>del a.exe
> 
> 
> C:\Users\76320\Code\C>gcc itoa.cpp -g
> 
> C:\Users\76320\Code\C>a.exe
>  is running
> Time spent:0ms
> C:\Users\76320\Code\C>gcc --interpreter=mi
> gcc: error: unrecognized command line option '--interpreter=mi'
> gcc: fatal error: no input files
> compilation terminated.
> 
> C:\Users\76320\Code\C>gdb a.exe --interpreter=mi
> =thread-group-added,id="i1"
> ~"GNU gdb (GDB) 8.0.1\n"
> ~"Copyright (C) 2017 Free Software Foundation, Inc.\n"
> ~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
> ~"This GDB was configured as \"x86_64-w64-mingw32\".\nType \"show configuration\" for configuration details."
> ~"\nFor bug reporting instructions, please see:\n"
> ~"<http://www.gnu.org/software/gdb/bugs/>.\n"

**Comment by pieandcakes** [comment]
Right. you don't need to specify `--interpreter=mi`. We pass that to `gdb` in the extension already.
