### ISSUE TITLE
mingw error

### ISSUE THREAD

**Issue by Eman-gif-commit** [microsoft/vscode-cpptools#12692]
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds

**Comment by Eman-gif-commit** [comment]
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
how to solve this issue

**Comment by sean-mcmanus** [comment]
This doesn't sound like a bug with our C/C++ extension.
