### ISSUE TITLE
Improve error output/hover popup info

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode-cpptools#12717]
### Feature Request

When enabling clang-tidy and there is an error, the output shows `GCC` as the source of the error. It would be much better if it showed eg `GCC - clang-tidy` as the source. This helps in case there are other faults for other linters in the future,

Example how it looks today:

![image](https://github.com/user-attachments/assets/e9fb2bb8-7482-4fb8-94ce-3b59f00535b2)

**Comment by sean-mcmanus** [comment]
That warning is not from our extension. It appears to be from another extension. Our extension reports the clang-tidy problems like: 

![image](https://github.com/user-attachments/assets/a6b21b81-f677-43b4-8d07-81c8aa0dc038)

**Comment by thernstig** [comment]
@sean-mcmanus I do not have any other C/C++ extensions in my repo. The problems look like this in the problems pane:

![image](https://github.com/user-attachments/assets/aadd5cff-6493-4059-bbcc-9f148b1d80fb)

These are the enabled extensions:

![image](https://github.com/user-attachments/assets/d8651536-eefa-4c85-a970-5e3c8f1c9619)

**Comment by sean-mcmanus** [comment]
@thernstig Yes, but the bug you're describing no longer repros in your new screenshot. It doesn't say "GCC" is the source. It shows the correct source of "C/C++".

**Comment by thernstig** [comment]
@sean-mcmanus the issue is still valid.

See here:

![image](https://github.com/user-attachments/assets/91b6d5f1-0f02-4d03-af11-7391d024035a)

The issue is that your extension does not say which **source** the error comes from. The error comes from **clang-tidy** and that is an important piece of information. Especially in the context of if you add more linters in the future, where you have settings to disable/enabled each linter individually (which you already do for clang-tidy).

A much better error message would have been:

```
variable 'as' is not initialized C/C++ (clang-tidy) [cppcoreguidelines-init-variables](https://releases.llvm.org/18.1.6/tools/clang/tools/extra/docs/clang-tidy/checks/cppcoreguidelines/init-variables.html)
```

or maybe better:

```
variable 'as' is not initialized C/C++ [clang-tidy: cppcoreguidelines-init-variables](https://releases.llvm.org/18.1.6/tools/clang/tools/extra/docs/clang-tidy/checks/cppcoreguidelines/init-variables.html)
```
