### ISSUE TITLE
Extract to function still extracts when canceled

### ISSUE THREAD

**Issue by KKhanhH** [microsoft/vscode-cpptools#12712]
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.91.1
- C/C++ Extension Version: 1.21.6 
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary:
After clicking on extract to function and receiving a prompt for the new function name, pressing escape does not cancel, but instead refactors to a new function named NewFunction.

Steps to reproduce:
1. Select any valid extractable code.
2. Do extract to function
3. When prompted for new function name, press escape
4. Code is extracted with name NewFunction

Expected behavior:
Do nothing when escape is pressed.

### Configuration and Logs

```shell
N/A
```

**Comment by sean-mcmanus** [comment]
@KKhanhH That is "by design". If you select `Extract to function` there is no way to cancel it during the renaming phase. The "cancel" that is mentioned in the rename dialog just applies to the renaming and not the `Extract to function`

**Comment by KKhanhH** [comment]
> @KKhanhH That is "by design". If you select `Extract to function` there is no way to cancel it during the renaming phase. The "cancel" that is mentioned in the rename dialog just applies to the renaming and not the `Extract to function`

I thought this would've been implemented by #11531? This behavior isn't exactly very intuitive and it's annoying especially because ctrl-z doesn't undo all files when you extract out of a member function since header files are changed as well.

**Comment by sean-mcmanus** [comment]
@KKhanhH The cancel still applies to the rename. Can you file a new issue on the Undo failure? Unless it's https://github.com/microsoft/vscode-cpptools/issues/11462 ?

**Comment by KKhanhH** [comment]
@sean-mcmanus Done, #12713
