### ISSUE TITLE
(macOS) Can't view 'BS' in vscode

### ISSUE THREAD

**Issue by yzlnew** [microsoft/vscode-cpptools#1271]
Maybe due to the default Chinese input method, I'm keep tying 'BS' (0x08 in ASCII) in vscode, which is annoying but I can't view.

In vscode:
![jietu20171120-141005](https://user-images.githubusercontent.com/4904877/33064693-8434a3f0-cee1-11e7-919b-1c1cbd4df823.jpg)

In Sublime Text:
![jietu20171120-140935](https://user-images.githubusercontent.com/4904877/33064713-917e89cc-cee1-11e7-8f37-97e303c52648.jpg)

**Comment by bobbrow** [comment]
This doesn't look like a C++ issue.  Am I missing something?
Can you file an issue for vscode?  https://github.com/Microsoft/vscode/issues

**Comment by yzlnew** [comment]
Sorry, I just posted on the wrong page.
Thanks anyway.
