### ISSUE TITLE
CMake+MinGW+Clang not start cppdbg debugger 

### ISSUE THREAD

**Issue by WittonBell** [microsoft/vscode-cpptools#12714]
### Environment

- OS and version: Win10 22H2
- VS Code: 1.93.1
- C/C++ extension: 1.21.6
- OS and version of remote machine (if applicable):
- GDB / LLDB version: 15.1  / 18.1.8

### Bug Summary and Steps to Reproduce

Bug Summary:

repro step:
1. create any simple c/c++ project.
main.c:
```
#include <stdio.h>

int main(int argc, char *argv[]) {
  printf("test\n");
  while (1) {
  
  }
  return 0;
}
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.25.0)
project(x)

add_compile_options(
    -gdwarf-4
)
aux_source_directory(. SRC)
add_executable(${PROJECT_NAME} ${SRC})
```

2. switch kit `[Clang 18.1.1 x86_64-w64-windows-gnu(mingw64)]` from VSCode status bar for `cmake-tools`
3. click debug button from VSCode status bar for `cmake-tools`
![image](https://github.com/microsoft/vscode-cmake-tools/assets/8215947/25c54376-3094-4c28-a381-071f80a2f4ee)
4. `cmake-tools` will start the `cppvsdbg` debugger, not `cppdbg`
![image](https://github.com/microsoft/vscode-cmake-tools/assets/8215947/1da90720-df09-401c-91c0-a583d1230f73)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/8215947/29514ef7-b97a-4d75-9682-3ce770ebaddb)

so, it does not hit the breakpoint when debugging.

![image](https://github.com/microsoft/vscode-cmake-tools/assets/8215947/91330a54-30dd-4026-8d73-54f134545401)

switch kit to `gcc`, it start the `cppdbg` debugger correctly.

### Debugger Configurations

```shell
No `launch.json` config.
```

### Debugger Logs

```shell
Nothing
```

### Additional Information

see: [https://github.com/microsoft/vscode-cmake-tools/issues/3667](https://github.com/microsoft/vscode-cmake-tools/issues/3667)

I don't know which plugin is the problem. I think it might be `ms-vscode.cpptools`.

**Comment by sean-mcmanus** [comment]
The Debug button in the status bar is from CMake Tools.
