### ISSUE TITLE
C++ module support

### ISSUE THREAD

**Issue by bnagababu** [microsoft/vscode-cpptools#12723]
### Environment

- OS and Version: Windows 11 
- VS Code Version: 1.93.1
- C/C++ Extension Version: 1.3.0
- If using SSH remote, specify OS of remote machine: 

### Bug Summary and Steps to Reproduce

Bug Summary: C++ module support

Steps to reproduce:
1. set C++ standard to c23 in cmake
2.write  import std; in source code
3. IntelliSense showing import std; as error

Expected behavior:
IntelliSense support for C++ modules

### Configuration and Logs

```shell
dont know
```

### Additional context

import std;

int main(){
    std::cout << "Hi Modules\n";
}

This code is compiling and running fine using cmake 2.30.
But IntelliSense showing error at """import std;"""

**Comment by sean-mcmanus** [comment]
I assume you mean c++23 and not c23. We're already tracking this with https://github.com/microsoft/vscode-cpptools/issues/6302.
