### ISSUE TITLE
Configuration selection

### ISSUE THREAD

**Issue by sbrw** [microsoft/vscode-cpptools#1273]
- Ubuntu 17.10
- vscode 1.18.1
- C/C++ 0.14.2

1. Add a custom configuration in c_cpp_properties.json
2. Open a C-file in the editor
3. Set your new custom configuration active in the toolbar in the lower right corner
4. Modify c_cpp_properties.json by e.g adding a path to your custom configuration
5. Reopen the C-file and the new configuration selected previously is not active
6. Close and restart vscode. The same
7. Save the workspace. The same
8. ...?

Problem:
- The configuration that was active prior to steps 4, 5, 6 and 7 above is not active any longer
- The configuration that is activated instead by default seems to be selected by "random". Neither  definition- nor alphabetic order in c_cpp_properties.json seems to matter

Feature (either):
- Would it be possible to keep the selected configuration so its kept until its intentionally changed?
- Define a default configuration in c_cpp_properties.json?
- Let the first configuration defined in c_cpp_properties.json be the default configuration?

**Comment by bobbrow** [comment]
If there is a definition called "Linux" in your config, we will select that one.  Otherwise we pick the last one.  I've been meaning to change this behavior and have it remember the previously selected config.  It's been this way since I joined the project earlier this year.

**Comment by sbrw** [comment]
I'm cross-compiling 99% of the time so Linux is not applicable target for me. I've seen both Mac and Win32 being selected on Linux.

Thanks for nice features!

**Comment by sean-mcmanus** [comment]
Yeah, this should be pretty quick to add via saving the previously set configuration name in the workspaceState. I believe the reason the config wasn't saved initially was because we didn't know where to save it (not sure when workspaceState was added).

**Comment by bobbrow** [comment]
This has been fixed in 0.14.4
