### ISSUE TITLE
Can't load the DevSkim extension into Visual Studio 2017

### ISSUE THREAD

**Issue by MichaelDennis** [microsoft/vscode-cpptools#1274]
When I attempted to load the DevSkim extension into Visual Studio 2017, I received the error msg: "The VSPackage did not load correctly".

The activity log file indicated an issue with "CompanyName" as shown below.

Any help you can give would be appreciated.

Here are some excerpts from the log file:

    <description>Missing/invalid &apos;CompanyName&apos; field in package registry</description>

    <description>Appid denied the loading of package</description>

**Comment by sean-mcmanus** [comment]
Did you mean to file an issue at https://github.com/Microsoft/DevSkim-VSCode-Plugin/issues ? This doesn't appear to be related to the cpptools extension. Although you're mentioning VS 2017, so maybe you want to try the VS site https://github.com/Microsoft/DevSkim-VisualStudio-Extension/issues .

**Comment by MichaelDennis** [comment]
Right, thanks Sean.

Thanks,

Michael McDonnell



 

    On Tuesday, November 21, 2017, 11:56:45 AM PST, Sean McManus <notifications@github.com> wrote:  
 
 
Did you mean to file an issue at https://github.com/Microsoft/DevSkim-VSCode-Plugin/issues ? This doesn't appear to be related to the cpptools extension.
