### ISSUE TITLE
Error Squiggles not working in c/++ fichier 

### ISSUE THREAD

**Issue by anboua** [microsoft/vscode-cpptools#1275]
Error Squiggles not working in c/c++ . error must be underline in the editor ! 
how can I make it work ?

![dsfsd](https://user-images.githubusercontent.com/20954351/33096245-9e120752-cf06-11e7-9987-3f6ee055d58f.png)

**Comment by sean-mcmanus** [comment]
What is your OS? The cpptools extension doesn't appear to be activated correctly (no config name in the bottom right).

**Comment by anboua** [comment]
windows 8.1 64 bit

**Comment by sean-mcmanus** [comment]
I suspect you do not have a folder open. Can you do an open folder instead of open file? I think our next update will fix the open file scenario.

**Comment by anboua** [comment]
I try it with open folder  it's the same ! 
![sanffffs titre](https://user-images.githubusercontent.com/20954351/33099786-68fd3f4e-cf12-11e7-82c8-b820855bdd35.png)

**Comment by sean-mcmanus** [comment]
The extension is working as expected now. You need to update your includePath in c_cpp_properties.json. If your browse.path is set, you might be able to use the lightbulb code action to locate the includePath to add. I have stdlib/stdio.h at `C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\` so you need to point it to whatever Windows SDK version you have installed. We're supposed to already automatically add the Windows Kit location to the includePath as a default though.

**Comment by anboua** [comment]
thank you so much .It worked !
