### ISSUE TITLE
Dim inactive code

### ISSUE THREAD

**Issue by veto-gh** [microsoft/vscode-cpptools#1276]
I'm sorry if this has been asked before.

Is there any feature/workaround to make inactive code sections (ruled out by the pre-processor) visually differentiable? I could not found anything on that matter.
I.e.:
![a](https://user-images.githubusercontent.com/25972036/33145448-b4556b52-cfc0-11e7-8aff-9c688e11c3a7.png)
It already works in trivial cases:
![a](https://user-images.githubusercontent.com/25972036/33132014-a0a9a744-cf98-11e7-9593-f28fd2637253.png)

If not consider this a feature request.
I would love to use VSCode for bigger projects with nested pre-processor checks and this would really help.

**Comment by bobbrow** [comment]
This is covered by #230.  I recently discovered a way that we can do this and I need to test it out.  I'm not sure if we'll get it for the December release though.

**Comment by veto-gh** [comment]
Thanks for the quick answer and for pointing me to the original issues, which I up-voted.

**Comment by sean-mcmanus** [comment]
@veto-gh Inactive code colorization has been added in 0.15.0 (intelliSenseEngine needs to be "Default" though).

**Comment by veto-gh** [comment]
Thank you for the heads-up! (I already followed #1466 closely)
And it works like a treat on Ubuntu 16.04, great work guys!

Off-topic: Is there a request/issue I can follow which allows the IntelliSenseEngine to parse defines and includes (obtained by pkg-config) from a makefile? Should I create one?

**Comment by bobbrow** [comment]
@veto-gh I don't think there is a feature request to parse defines and includes from a makefile.  Please create one.

**Comment by veto-gh** [comment]
> Please create one

Done, see #1587.

**Comment by bobbrow** [comment]
Thank you.

**Comment by codecae** [comment]
It appears this change is suddenly dimming large amounts of code in our project with multiple targets that span various configurations.  Unfortunately, I now have to disable this plugin in order to effectively browse my code and retain syntax highlighting.  Is there a way to make this feature configurable?

**Comment by veto-gh** [comment]
They are working on a setting (see #1574).

For a temporary workaround to disable it please see the thread I mentioned above (#1466).
