### ISSUE TITLE
Problem in Symbol Searching

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode-cpptools#1277]
* Operating System and version
       macOs 10.13.1
    * VS Code version and if you are using the Insiders build
      1.18.1
    * C/C++ extension version
      0.14.2

I just want search symbol in current file, but extension show so many symbol in other files, it make the lower.

![image](https://user-images.githubusercontent.com/7554917/33134157-f7aaaa20-cfd9-11e7-8f76-0477ada3c2c1.png)

**Comment by sean-mcmanus** [comment]
Use @ or the Go To Symbol in File command.

**Comment by Kurt-Shiwz** [comment]
@sean-mcmanus it show nothing
![image](https://user-images.githubusercontent.com/7554917/33158230-1b8cae8e-d043-11e7-8172-9a7c98ca39d0.png)

**Comment by sean-mcmanus** [comment]
It looks like the file is not being parsed correctly. If you edit/save the file, does it fix it? Can you increase the C_Cpp.loggingLevel to Information and view the C/C++ Output pane to see if there's a problem shown there? Can you create a dummy C++ file to verify that Go to Symbol in File works in general?

**Comment by Kurt-Shiwz** [comment]
utill.cpp, 7750 lines, 363K @sean-mcmanus 
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: .*
File exclude: *.a
File exclude: *.o
File exclude: *.so
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: /usr/local/include/ will be indexed
  Folder: /Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include/ will be indexed
  Folder: /Library/Developer/CommandLineTools/usr/include/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: a/ will be indexed
  Folder: /System/Library/Frameworks/ will be indexed
  Folder: /Library/Frameworks/ will be indexed
Discovering files...
Checking for syntax errors: file:///a/utill.cpp
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include/
  Processing folder (recursive): /Library/Developer/CommandLineTools/usr/include/
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): a
  Processing folder (recursive): /System/Library/Frameworks/
Failed to read response from server: 18
IntelliSense client has disconnected from the server - a/utill.cpp
Shutting down IntelliSense server: a/utill.cpp
Shutdown request failed.
Checking for syntax errors: file:///a/utill.cpp
  Processing folder (recursive): /Library/Frameworks/
  Indexing: 244628 file(s) processed
  Indexing: 2 file(s) removed from database
Done discovering files.
Parsing open files...
Checking for edits and parsing remaining files...
  Processing folder (recursive): a
Done parsing open files.
  Parsing: 360 files(s) processed
Done parsing remaining files.

**Comment by Kurt-Shiwz** [comment]
![image](https://user-images.githubusercontent.com/7554917/33166608-cddbd146-d075-11e7-8b1a-8040f656e96c.png)
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: .*
File exclude: *.a
File exclude: *.o
File exclude: *.so
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: /usr/local/include/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /Users/shiweize/project/test/ will be indexed
  Folder: /System/Library/Frameworks/ will be indexed
  Folder: /Library/Frameworks/ will be indexed
Discovering files...
Checking for syntax errors: file:///Users/shiweize/project/test/test.cc
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /Users/shiweize/project/test/
  Processing folder (recursive): /System/Library/Frameworks/
Tag Parser will be used for IntelliSense operations in: file:///Users/shiweize/project/test/test.cc
 @sean-mcmanus

**Comment by sean-mcmanus** [comment]
I don't see any symbol parsing errors, but the IntelliSense engine process appears to be crashing, which means the symbol parser could also be erroring (although I would expect to see a failure message).

Can you set your browse.path to be blank and set your logging level to the hidden value of 7, reload window, and then do a Reset IntelliSense Database command? The expected result should include text like the following if it's successful: 
`update_file_if_needed: /a/util.cpp
  File added. Time stamp: 1511812087
  tag parsing file: /a/util.cpp`

We have code that runs right after "Done parsing remaining files." that we just discovered/fixed a race condition crash for, so it's possible that could be causing the problem.

**Comment by Kurt-Shiwz** [comment]
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: .*
File exclude: *.a
File exclude: *.o
File exclude: *.so
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
Discovering files...
Checking for syntax errors: file:///a/utill.cpp
  Indexing: 0 file(s) processed
  Indexing: 1 file(s) removed from database
Done discovering files.
Parsing open files...
Checking for edits and parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Done parsing open files.
Failed to read response from server: 18
IntelliSense client has disconnected from the server - /a/utill.cpp
**Failed to send request to server: 3
IntelliSense engine is not responding. Using the Tag Parser instead.**

@sean-mcmanus  
1. after reset database, it work, and I find sublime text is more stable than vs with cpptools.

2.  it mean no error?
Failed to send request to server: 3
IntelliSense engine is not responding. Using the Tag Parser instead.

**Comment by sean-mcmanus** [comment]
The error message is about the IntelliSense engine failing, and shouldn't affect the symbol searching. So far, I haven't seen any symbol search (tag parsing) failure messages in your logs.

**Comment by TheDark** [comment]
I'm getting a similar error in Windows 10 Pro version 10.0.16299.64, VSCode version 1.18.1, C/C++ extension version 0.14.3, installed via Microsoft's Arduino extension version 0.2.10

Tag Parser fallback is disabled. I performed the actionsfrom your previous post (clear browse path, restart VSCode, reset Intellisense database), then tried to get suggestions for a class instance members, and got the following:

initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
textDocument/didOpen
cpptools/queryDefaultPaths
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/codeAction
cpptools/didChangeFolderSettings
Code browsing service initialized
textDocument/didOpen
Discovering files...
Checking for syntax errors: file:///c%3A/Users/TheDark/Documents/Arduino/oled-test2/oled-test2.ino
update_file_if_needed: C:\USERS\THEDARK\DOCUMENTS\ARDUINO\OLED-TEST2\OLED-TEST2.INO
  Indexing: 0 file(s) processed
  Indexing: 1 file(s) removed from database
  Same time stamp: 1512527311
Done discovering files.
Parsing open files...
Checking for edits and parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
update_file_if_needed: C:\USERS\THEDARK\DOCUMENTS\ARDUINO\OLED-TEST2\OLED-TEST2.INO
  File added. Time stamp: 1512527311
  tag parsing file: C:\USERS\THEDARK\DOCUMENTS\ARDUINO\OLED-TEST2\OLED-TEST2.INO
queue_get_errors_for_file: file:///c%3A/Users/TheDark/Documents/Arduino/oled-test2/oled-test2.ino
Done parsing open files.
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/codeAction
Failed to read response from server: 18
errorSquiggles count: 0
IntelliSense client has disconnected from the server - C:\USERS\THEDARK\DOCUMENTS\ARDUINO\OLED-TEST2\OLED-TEST2.INO
textDocument/codeAction
Database safe to open
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/resetDatabase
cpptools/resetDatabaseReady
Database safe to open
Code browsing service initialized
Discovering files...
  Indexing: 0 file(s) processed
  Indexing: 0 file(s) removed from database
Done discovering files.
Parsing open files...
Checking for edits and parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
update_file_if_needed: C:\USERS\THEDARK\DOCUMENTS\ARDUINO\OLED-TEST2\OLED-TEST2.INO
  File added. Time stamp: 1512527311
  tag parsing file: C:\USERS\THEDARK\DOCUMENTS\ARDUINO\OLED-TEST2\OLED-TEST2.INO
Done parsing open files.
textDocument/hover
textDocument_hover(): [3, 61]
IntelliSense client is currently disconnected
IntelliSense client not available, using Tag Parser for quick info.
using Tag Parser for quick info
textDocument/hover
textDocument_hover(): [3, 61]
IntelliSense client is currently disconnected
IntelliSense client not available, using Tag Parser for quick info.
using Tag Parser for quick info
Database safe to open
textDocument/didChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/completion
Resetting IntelliSense server: C:\USERS\THEDARK\DOCUMENTS\ARDUINO\OLED-TEST2\OLED-TEST2.INO
Shutdown request failed.
Closing the communication channel.
auto_complete::handle_completion: file:///c%3A/Users/TheDark/Documents/Arduino/oled-test2/oled-test2.ino (21:7)
Offering completion
sending 1 changes to server
textDocument/codeAction
Checking for syntax errors: file:///c%3A/Users/TheDark/Documents/Arduino/oled-test2/oled-test2.ino
queue_get_errors_for_file: file:///c%3A/Users/TheDark/Documents/Arduino/oled-test2/oled-test2.ino
Failed to read response from server: 18
errorSquiggles count: 0
IntelliSense client has disconnected from the server - C:\USERS\THEDARK\DOCUMENTS\ARDUINO\OLED-TEST2\OLED-TEST2.INO
Checking for syntax errors: file:///c%3A/Users/TheDark/Documents/Arduino/oled-test2/oled-test2.ino
IntelliSense client is currently disconnected

Sometimes I get a green squiggly under the # of the first include right after launching VSCode, saying there were too many errors. Can't remember the exact message, and I'm unable to provoke it again.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
