### ISSUE TITLE
Struct/union members are not highlighted consistently (if enclosed in a macro, such as for packing)

### ISSUE THREAD

**Issue by al20878** [microsoft/vscode-cpptools#12780]
### Environment

 Version: 1.93.1 (system setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

### Bug Summary and Steps to Reproduce

Bug Summary:

Struct/union members are not highlighted consistently (if enclosed in a macro, such as for packing).

Steps to reproduce:
Consider the following source code:
```
typedef unsigned int   uint4;
typedef   signed int    int4;
typedef unsigned short uint2;
typedef   signed short  int2;
typedef unsigned char  uint1;
typedef   signed char   int1;

struct mystruct {
    uint2 test_value;
    uint4 single_value;
    uint4 array[15];
    uint4 sys$array[20];
};


struct S_struct {
    uint2 H_help;
    uint1 H_print;
    uint4 H$print;
};

#if defined(_MSC_VER)
#  define PACKED(...)                           \
    __pragma(pack(push, 1))                     \
    __VA_ARGS__                                 \
    __pragma(pack(pop))
#else
#  if defined(__GNUC__)
#    define PACKED(...)                         \
    __VA_ARGS__                                 \
    __attribute__((packed))
#  endif
#endif

PACKED(struct S_newstruct {
    uint1   member1;
    uint2   member2[2];
    uint4   sys$member3;
    uint4   sys$member4[2];
});
```

And look what colors are used in the last structure members for highlighting.
Expected for them to be all light-cyan, but it looks like '$' has some sort of a delimiter role in there,
and also non $-contaning members are all white, for some reason.

Expected behavior (note syntax highlighting colors):
![RegularColoring](https://github.com/user-attachments/assets/91529e47-ec93-4792-a7eb-f399a9b7173d)

Actual behavior:
![WeirdColoring](https://github.com/user-attachments/assets/9ed67a92-72cc-40d9-ad20-93766fe45459)

Thanks for looking!

### Configuration and Logs

```shell
No special config is used
```

**Comment by sean-mcmanus** [comment]
I've added this info to https://developercommunity.visualstudio.com/t/CC-IntelliSense-operations-dont-work/10760638 from https://github.com/microsoft/vscode-cpptools/issues/12799 , since they likely share the same root cause.

**Comment by al20878** [comment]
@sean-mcmanus : In MSVC ticket you only mentioned that a struct name wasn't properly colorized as a class name;
but my report in here is a bit wider, because members are not correctly colorized, either; and that the '$' sign in the identifier name has a special "meaning" for members, which happen to be arrays (compare `sys$member3` and `sysmember4` above).
