### ISSUE TITLE
c/c++ ext error

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-cpptools#128]
_From @amither on August 4, 2016 5:13_
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.install c/c++ ext
2. in my c++ project , error info : The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

_Copied from original issue: Microsoft/vscode#10111_

**Comment by pieandcakes** [comment]
@sridmad Please investigate. Thanks

**Comment by jgoshi** [comment]
This should be fixed in the next release (cpp extension version 0.9.0) using VSCode version 1.4. If it still repros for you at that time please reopen this bug.

**Comment by andro78** [comment]
I am using VSCode 1.5.3 and cpp extenion version 0.9.2, "The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted." message appear.

**Comment by pieandcakes** [comment]
@jgoshi This looks like it is still an issue.

**Comment by andro78** [comment]
So I tried to install previous version of VSCODE(1.5.0), but same issue occurred.

**Comment by sean-mcmanus** [comment]
More repro details would be great, since we can't repro this. Do you just open a folder? Any folder? One thing we could do in the future is to add more enable/disable settings so users can turn off functionality that is potentially crashing. Also, what is your OS? You may be using an unsupported OS.

**Comment by natezhenghy** [comment]
OS: windows 10(14393.222)
No folder is opened. Just create a new file, set language to C++, type anything, then the issue would occur. I reinstall VSC, uninstall all other extensions, and reinstall C/C++ but it is still there.

**Comment by sean-mcmanus** [comment]
Yes, this is a known issue with using a newly created, unsaved file. You should save the new file to workaround this bug. Opening the folder the file is saved at would also be recommended.

**Comment by andro78** [comment]
There is no new unsaved files.

**Comment by throne-albert** [comment]
When I switch to C/C++, this still happen

**Comment by neilhhw** [comment]
VSCode 1.7.2
C/C++ Extention Version 0.9.2
Windows 10
Bug is still exsited.

**Comment by wqhyw** [comment]
VSCode 1.7.2
C/C++ Extenion Version 0.9.2
macOS Sierra
Bug is still exsited

**Comment by basitanwer** [comment]
- VSCode 1.8.1
 - C/C++ Extension Version 0.9.3: December 8, 2016
 - Windows 10

Bug still exists.

Workaround: Works only when file is saved.

**Comment by sean-mcmanus** [comment]
This bug doesn't seem to repro with 0.10.3.
