### ISSUE TITLE
error parsing multiline "command" in compile_commands.json

### ISSUE THREAD

**Issue by vitalyster** [microsoft/vscode-cpptools#1280]
I did generate compile_commands.json with `cmake . -G "NMake Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=1` and got "command" properties in this format:
```
"command": "C:\\PROGRA~2\\MICROS~1\\2017\\COMMUN~1\\VC\\Tools\\MSVC\\1411~1.255\\bin\\HostX86\\x86\\cl.exe @<<
 [...first line of params...] 
 [...second line of params...]
<<",
```
and it looks like that is not supported: `Unexpected end of string` message in "Problems" window at first "command" line
Using MSVS2017, CMake 3.8.2, VSCode 1.18.1, cpptools 0.14.2

**Comment by bobbrow** [comment]
That doesn't look like valid JSON to me.  Doesn't each line in the multi-line string need to end with a `\` character?  Is this a bug in CMake?

**Comment by ReeCocho** [comment]
I'm having the exact same issue with MSVS2017, CMake 3.7.1, VSCode 1.23.0, and cpptools 0.16.1. I'm also using CMake Tools by vector-of-bool. Might this have something to do with it?

EDIT: 
I just updated my CMake to version 3.11.1 and it's fixed. Must've been a CMake issue!

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
