### ISSUE TITLE
Copilot getIncludes with 2 includes only returns the first

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#12807]
1. Create a new workspace folder. (I think you need the latest GitHub Copilot extensions installed too).
2. Create a test1.cpp
```cpp
#include "test1.h"
#include "test2.h"
```
3. Create a test1.h with `int test1h;` and test2.h with `int test2h;`
4. Use Ctrl+Space or something to trigger the getIncludes call.

Bug: In the debugger you can see it only gets 1 of the includes. That seems like a bug to me (although the maxDepth is 1 and I'm not sure what that means). See the screenshot:

![image](https://github.com/user-attachments/assets/afb9cea8-f8a7-4a14-8419-ae9c371d6466)

I've reproed this on 2 machines, with VS Code Insiders.

It seems possible that some subset of the valid includes are getting lost in general, but I haven't investigated...but I did notice that it seems like includes were missing for our vc project (not sure what % were missing or if the maxDepth was the cause or not).

**Comment by lukka** [comment]
@sean-mcmanus was this a systematic behavior that you were seeing? I cannot repro it, headers are being provided as expected, as shown here:

![Image](https://github.com/user-attachments/assets/82a9206b-7d29-4222-8e3d-c8b8ab1fe1aa)

The list of headers is currently implemented in the native side of the extension, and if you could repro this, I'd be happy to investigate further by attaching a debugger to the machine with a repro.

@benmcmorran  @spebl @kuchungmsft

**Comment by sean-mcmanus** [comment]
@lukka Oh, interesting -- it no longer repros. I don't know what changed. My repro project is the same as when it reproed. I'll let you know if it happened again.
