### ISSUE TITLE
C/C++ syntax highlighting does not work when multiline comments follow include or define directives

### ISSUE THREAD

**Issue by aforster-mr** [microsoft/vscode-cpptools#12812]
### Environment

- OS and Version: Windows 11
- VS Code Version: 1.94.0
- C/C++ Extension Version: v1.21.6

### Bug Summary and Steps to Reproduce

C/C++ allows multiline comments following `#include` or `#define` directives. vscode does not highlight these cases properly.

![image](https://github.com/user-attachments/assets/e725dbff-92a4-4c8f-bbbb-b2badcd47984)

### Configuration and Logs

```shell
c_cpp_properties.json
empty (opened empty folder, added new main.cpp containing nothing except the screenshot content)
```

**Comment by sean-mcmanus** [comment]
Our C/C++ extension doesn't provide lexical colorization. That is from VS Code itself, which gets its implementation from the Better C++ Syntax extension, so you should report the issue at https://github.com/jeff-hykin/better-cpp-syntax/issues if it's not already reported.
