### ISSUE TITLE
VS Code fails to find stdlib headers on a MacOS after OS update

### ISSUE THREAD

**Issue by zencde** [microsoft/vscode-cpptools#12815]
### Environment

- OS and version:
- VS Code:
- C/C++ extension:
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

VS Code fails to find stdlib headers on a MacOS after OS update.

OS version: MacOS Sequioa 15.0.1
SDK : MacOSX15.0
Clang Version: Apple clang version 16.0.0 (clang-1600.0.26.3).

As a test I uninstalled VSCode and did a clean install. Followed steps from here and still see same error in compiling the helloworld.cpp code.

https://code.visualstudio.com/docs/cpp/config-clang-mac

Detailed error below.

[{
"resource": "/Users/../VSCodeProjects/helloworld/helloworld.cpp",
"owner": "C/C++: IntelliSense",
"code": "1696",
"severity": 8,
"message": "cannot open source file "iostream". Please run the 'Select IntelliSense Configuration...' command to locate your system headers.",
"source": "C/C++",
"startLineNumber": 2,
"startColumn": 1,
"endLineNumber": 2,
"endColumn": 20
}]

VS Code version: Code 1.94.0 (Universal) (https://github.com/microsoft/vscode/commit/d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)

### Debugger Configurations

```shell
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-clang-arm64"
        }
    ],
    "version": 4
}

{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: clang++ build active file",
            "command": "/usr/bin/clang++",
            "args": [
                "-fcolor-diagnostics",
                "-fansi-escape-codes",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

```shell
Compilation fails 

/Users/../VSCodeProjects/helloworld/helloworld.cpp:2:10: fatal error: 'iostream' file not found
    2 | #include <iostream>
      |          ^~~~~~~~~~
1 error generated.
```

**Comment by sean-mcmanus** [comment]
@zencde If clang isn't able to find iostream, I don't believe it's caused by our extension, i.e. it sounds like you would get the same error when running clang on the command line.

**Comment by zencde** [comment]
I did manage to make it work eventually. I just had to explicitly include the include path in the tasks.json file.
