### ISSUE TITLE
C++ Extension not installing

### ISSUE THREAD

**Issue by Rajab-Ali11** [microsoft/vscode-cpptools#12814]
### Environment

- OS and Version: Windows 10 pro
- VS Code Version: 1.94.0
- C/C++ Extension Version: v1.21.6

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
i installing C/C++ Extension but it still stuck on installing about half an hour.
```

**Comment by sean-mcmanus** [comment]
@Rajab-Ali11 Our extension is not involved in installing itself. You should file a bug with VS Code at https://github.com/microsoft/vscode/issues . They may require more logging (not sure which logs).
