### ISSUE TITLE
enums and their members

### ISSUE THREAD

**Issue by sbrw** [microsoft/vscode-cpptools#1282]
- Ubuntu 17.10, Ubuntu 16.04
- vscode 1.18.1
- C/C++ 0.14.2

I have a header file which is part of a big code base. The header file does not include any other header files. The file contains a typedef'ed enum. I expected that hovering over the enum-members would display its enumerated value. It doesn't.

As I cannot disclose protected code I added a dummy enum in the file to illustrate as shown below:

**The enum:**
![test_enum](https://user-images.githubusercontent.com/33813608/33222284-49ab6e36-d156-11e7-8510-ef757fdeb62a.png)

**Hovering over member 'd':**
![hover_d](https://user-images.githubusercontent.com/33813608/33222572-88fb55f4-d158-11e7-9cb3-f6bde0f11474.png)

The tooltip information displayed when hovering the member 'd' is extreme. I expect only information of the enumerated value for 'd'. No such information is present. Instead it seems that all symbols with the name 'd' in the workspace is displayed, which are not even in the header file namespace.

I also added a new identical header file to the workspace with a similar dummy enum. To my surprise hovering a member reveals it enumerated value...?

**Comment by bobbrow** [comment]
It looks like the "fuzzy" IntelliSense engine is providing results for you.  Can you check on a few things for me?
1. Is `C_Cpp.intelliSenseEngine` set to `Default` in your settings.json?
2. Are there any "Problems" in the problems window that say "include errors detected"?  By default if we can't resolve your includes, we disable the error squiggles and use the fuzzy IntelliSense engine for tooltips and autocomplete.  You can disable this policy by clicking the light bulb that appears in the editor when selecting the #include problem and choosing "force semantic IntelliSense".
3. Is there a Microsoft.VSCode.CPP.IntelliSense.Msvc.linux process running?  If the setting mentioned in (1) is set, but you don't have any of these processes running, then the IntelliSense engine may have crashed and we would be interested in getting more information about your code file(s) that caused the crash.

The extension is capable of providing better results for you:
![image](https://user-images.githubusercontent.com/12818240/33280407-d162d8da-d356-11e7-8687-2b74b49072e1.png)

**Comment by sbrw** [comment]
1. Yes, it is set to Default
2. Yes, there are "include errors detected". However they concern another workspace folder. Are these errors per workspace folder or  per vscode instance?
3. Yes, there is such a process.

I tried putting a test-enum in a new file at the same path as the one giving me problem. Hovering over the enum fields here yields expected correct result as you show. Should't this new enum and file suffer from the same errors?

**Comment by bobbrow** [comment]
2. The "include errors detected" fallback behavior is per translation unit (e.g. source file + included headers).  If your enum is defined in a.cpp and there is a problem reported for a.cpp, then you will get "fuzzy" IntelliSense for a.cpp and all its dependencies until you update your `includePath` such that the #include statements all resolve.  Usually you can use the light bulb suggestions that appear when you select the squiggled line to help populate your include path or disable the fallback behavior.

3. How many code files do you have open?  There will be one instance of this process running per translation unit you have open in the editor (note: we do shut down some instances if your total memory usage goes above some threshold).  To make sure that the IntelliSense process you have open is actually servicing your file, I recommend closing all open code files, verifying that there are no IntelliSense processes active, and then re-opening the code file with the enum definition in it.  If you still have no IntelliSense processes open at that point, then IntelliSense might have crashed.

**Comment by sbrw** [comment]
2. The enum is in a header file which do not include any other files and there are no squiggles in the file at all.
3. I closed all files files and then closed vscode. After closing vscode there where still 5 cpptools processes running. I killed them manually, restarted vscode and the opened the header file containing the enum and now 2 cpptools processes running. No valuable intellisense for the enum fields however.

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.

If you update to the latest version of the C/C++ extension and your issue persists, please re-open the issue and reply with additional information that can help us investigate your issue.
