### ISSUE TITLE
the code will not run in terminal window

### ISSUE THREAD

**Issue by mjeed02** [microsoft/vscode-cpptools#12829]
hi
im trying to run some c code but every time the terminal window that opened will not run the code
the window is called "gcc build active file" it will not display any output or will except any input because the window will close

```
Build finished successfully.
 *  Terminal will be reused by tasks, press any key to close it. 
```

im using a macbook

**Comment by sean-mcmanus** [comment]
@mjeed02 It sounds like you're using a task to build, but then you're not launching the debugger or running the code.
