### ISSUE TITLE
Symbol navigation and context

### ISSUE THREAD

**Issue by sbrw** [microsoft/vscode-cpptools#1283]
- Ubuntu 17.10
- vscode 1.18.1
- C/C++ 0.14.2

Often times when I browse all symbols using CTRL-T, the dropdown list cannot hold both the symbol name and its path. The path gets truncated (not viewable), which complicates navigation in e.g multi-target projects that may have the same symbol defined in different files.

Would it be possible to:
- 'Pop-out' the selected symbol with full symbol name and path
- Increase the size of the navigation dropdown list
- List the symbols in a new message box
- ...?

**Comment by bobbrow** [comment]
You can hover over the truncated path with your mouse to get a tooltip, but if you would rather navigate the list with your keyboard instead, this won't work for you.

Unfotunately, our extension doesn't have much say in what the VS Code UI does with the results we provide for this action.  We could consider modifying the extension to return shorter file paths for the symbols, but we don't know how wide VS Code will make the text area and may end up unnecessarily truncating paths that could fit.

This sounds like something you would need to ask the VS Code team to tune.

**Comment by michelleangela** [comment]
Closing as external issue.
