### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rayaanrizwan1234** [microsoft/vscode-cpptools#12833]
Type: <b>Bug</b>

Doesn't recognize git or anything

Extension version: 1.21.6
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 5.14.0-427.33.1.el9_4.x86_64
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
autoexpandse:31146404
iacca2:31156134
notype1cf:31151524
5fd0e150:31155592

```

</details>

**Comment by sean-mcmanus** [comment]
What isn't working? What do you mean by not recognizing git? Is this a VS Code bug unrelated to the C/C++ extension? If so, you should file it at https://github.com/microsoft/vscode/issues (and provide more info).
