### ISSUE TITLE
IntelliSense can't using C++20 standard

### ISSUE THREAD

**Issue by caijillx** [microsoft/vscode-cpptools#12865]
### Environment

- OS and Version:  MacOS 14.4.1 
- VS Code Version:  1.92.1 (Universal)
- C/C++ Extension Version:  v1.22.9
- If using SSH remote, specify OS of remote machine: No

```
#include <coroutine>
#include <iostream>
#include <thread>
struct Generator {
  struct promise_type {
    auto get_return_object() {
      return std::coroutine_handle<promise_type>::from_promise(*this);
    }
    std::suspend_always initial_suspend() noexcept { return {}; }
    std::suspend_always final_suspend() noexcept { return {}; }

    std::suspend_always yield_value(int val) {
      value_ = val;
      return {};
    }

    void return_void() {}
    void unhandled_exception() {}

    int value_;
  };
  Generator(std::coroutine_handle<promise_type> h) : handle(h) {}
  ~Generator() {
    if (handle) {
      handle.destroy();
    }
  }
  bool has_next() {
    handle();
    return !handle.done();
  }
  int next() { return handle.promise().value_; }

 private:
  std::coroutine_handle<promise_type> handle;
};


Generator fib(int no) noexcept {
  if (no <= 0) co_return;
  co_yield 1;
  if (no == 1) {
    co_return;
  }
  co_yield 1;
  if (no == 2) {
    co_return;
  }
  int a = 1;
  int b = 1;
  for (int i = 3; i <= no; ++i) {
    co_yield a + b;
    b = a + b;
    a = b - a;
  }
}

int main() {
  auto gen = fib(10);
  while (gen.has_next()) {
    std::cout << gen.next() << std::endl;
  }
}
```
For the code shown above, the following issues occur. However, the code can be compiled.
![Image](https://github.com/user-attachments/assets/a9e4f72f-ab47-4749-a9c2-89ce28c04fd6)

c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks"
            ],
            "cStandard": "c23",
            "intelliSenseMode": "macos-clang-arm64",
            "compilerPath": "/opt/homebrew/opt/llvm/bin/clang++",
            "cppStandard": "c++20"
        }
    ],
    "version": 4
}
```
settings.json
```
{
  "code-runner.executorMap": {
    "cpp": "cd $dir && clang++ -std=c++20 $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt"
  },
  "code-runner.runInTerminal": true,
  "C_Cpp.default.cppStandard": "c++20",
  "C_Cpp.default.compilerPath": "/opt/homebrew/opt/llvm/bin/clang++",
}
```

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:

Expected behavior:

### Configuration and Logs

-------- Diagnostics - 2024/10/21 17:08:29
Version: 1.22.9
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "/Users/llx/Test/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks"
    ],
    "cStandard": "c23",
    "intelliSenseMode": "macos-clang-arm64",
    "compilerPath": "/opt/homebrew/opt/llvm/bin/clang++",
    "cppStandard": "c++20",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/opt/homebrew/opt/llvm/bin/clang++",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "/Users/llx/Test/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Modified Settings:
{
    "C_Cpp.default.compilerPath": "/opt/homebrew/opt/llvm/bin/clang++",
    "C_Cpp.default.cppStandard": "c++20",
    "C_Cpp.clang_format_style": "Google",
    "C_Cpp.clang_format_fallbackStyle": "Google"
}
Additional Tracked Settings:
{
    "editorTabSize": 2,
    "editorInsertSpaces": true,
    "editorAutoClosingBrackets": "languageDefined",
    "filesEncoding": "utf8",
    "filesAssociations": {},
    "filesExclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/Thumbs.db": true
    },
    "filesAutoSaveAfterDelay": true,
    "editorInlayHintsEnabled": true,
    "editorParameterHintsEnabled": true,
    "searchExclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/*.code-search": true
    },
    "workbenchSettingsEditor": "ui"
}
cpptools version (native): 1.22.8.0
Current database path: /Users/llx/Library/Caches/vscode-cpptools/85df103b8bac00415963a80c0e62e944/.browse.VC.db
Translation Unit Mappings:
[ /Users/llx/Test/generator.cc - source TU]:
Translation Unit Configurations:
[ /Users/llx/Test/generator.cc ]
    Process ID: 13858
    Memory Usage: 8 MB
    Compiler Path: /opt/homebrew/opt/llvm/bin/clang++
    Includes:
    System Includes:
        /opt/homebrew/Cellar/llvm/19.1.2/include/c++/v1
        /opt/homebrew/Cellar/llvm/19.1.2/lib/clang/19/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/System/Library/Frameworks
    Standard Version: c++20
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=190102
Total Memory Usage: 8 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 10300

**Comment by sean-mcmanus** [comment]
@caijillx The errors in your screenshot are not from out extension. I'm not sure where they're from, maybe your compiler or another extension (I don't see the "source" of the problem in your screenshot).

**Comment by caijillx** [comment]
@sean-mcmanus Sorry，isn't the red wavy line below the code generated by IntelliSense?
![Image](https://github.com/user-attachments/assets/c54ac53d-b5bb-4e76-b872-1734b74aec4f)

**Comment by sean-mcmanus** [comment]
@caijillx What is the "source" of the problem? Does it say "C/C++"?
