### ISSUE TITLE
Problem matcher

### ISSUE THREAD

**Issue by sbrw** [microsoft/vscode-cpptools#1286]
- Ubuntu 17.10
- vscode 1.18.1
- C/C++ 0.14.2

I find it unfortunate to mix intellisense/lint errors and build errors/warnings in the "Problems" tab. I might have multiple workspaces open, some with broken intellisense include paths and others without. I would  still want to build a project and only attend to the build specific compilation errors in the "Problems" tab. Not interleaving it with non build related errors and warnings. Perhaps grouping problems in a single Problems tab, displaying in separate tabs, attending to build issues by clicking on them in the build output...

Another feature would be to have multiple "problemMatcher" per task in tasks.json. There might be two-stage compilation with unique output e.g first lint error matching, and then compiler error matching.

Alternatively a problem_matcher.json to define regex for the tools used, and match the build output against it.

**Comment by bobbrow** [comment]
Thanks for the feedback.  Unfortunately, this is not something our extension has any control over.  You would need to [ask the VS Code editor team](https://github.com/Microsoft/vscode/issues) for a feature like this.
