### ISSUE TITLE
Macro ifdef incorrectly parsed

### ISSUE THREAD

**Issue by raholly** [microsoft/vscode-cpptools#12879]
### Environment

- OS and Version: Windows 11 23H2 
- VS Code Version: v1.94.2
- C/C++ Extension Version:  v1.22.10
- If using SSH remote, specify OS of remote machine:  CentOS 7.9

### Bug Summary and Steps to Reproduce

Bug Summary:
I found that when Chinese characters appear in the middle of an ifdef macro, the code parsing will be incorrect.
The below screenshots show the issue. A very strange problem.
The first image is correct, while the parsing in the second and third images is incorrect.

![Image](https://github.com/user-attachments/assets/d5edf350-8c7f-4a40-a522-aa5f69d9c0ab)

![Image](https://github.com/user-attachments/assets/3f8a69fa-ed42-440f-b939-ecbd97c8a34c)

![Image](https://github.com/user-attachments/assets/d5b9412f-c549-428b-b92b-2fc82e14c2f0)

By the way, I tested version 1.21.6 of the C/C++ extension and didn't encounter this issue.

### Configuration and Logs

Here is c_cpp_properties.json

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/local/bin/clang",
            "intelliSenseMode": "linux-clang-x64"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
@raholly Thanks for reporting this. A minimal repro is

```cpp
#if 0
//测试e
#else
#endif
```

![Image](https://github.com/user-attachments/assets/ae06b7df-a0f8-47af-8e7b-847614862623)

**Comment by sean-mcmanus** [comment]
@raholly Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.23.0

**Comment by sean-mcmanus** [comment]
Also fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.22.11
