### ISSUE TITLE
Insert mode "insert" doesn't work

### ISSUE THREAD

**Issue by Rasie1** [microsoft/vscode-cpptools#12885]
### Environment

Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

### Bug Summary and Steps to Reproduce

I can't comment on https://github.com/microsoft/vscode-cpptools/issues/10553 and linked issues so I have to create another one. Refer to them for repro steps.

Right now, I have this set:

![Image](https://github.com/user-attachments/assets/9e5ece37-c105-4d8a-80ed-dc7ed9ab11f0)

However, it doesn't work and I still get the unreasonable behavior (from "replace"). 

How to fix it? I believe "insert" should be made the default

### Configuration and Logs

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.22621.0",
            "compilerPath": "cl.exe",
            "cStandard": "c17"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
@Rasie1 Set
```json
            "[cpp]": {
                "editor.suggest.insertMode": "insert"
            },
```

Is that sufficient?
