### ISSUE TITLE
c_cpp_properties.json support for extension command in includePath and forcedInclude

### ISSUE THREAD

**Issue by HeineHH** [microsoft/vscode-cpptools#12883]
### Feature Request

I have a project where the same code base is used to build a number of variants with different features enabled and customized applications on top of the commen code base. We use a VS Code extension to select the variant currently being worked on, the variant name is accessible via an extension command.

So instead of creating multiple c_cpp_properties configuration entries, I would like to have support for extension command expansion in includePath and forceInclude. In the example c_cpp_properties.json below, configuration Variant1 and Variant2 would simply be replace by the GenericVariant configuration.

```
{
    "configurations": [
        {
            "name": "GenericVariant",
            "includePath": [
                "${workspaceFolder}/src/${command:buildVariant.getVariant}/include"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "${default}",
            "forcedInclude": [
                "${workspaceFolder}/build/${command:buildVariant.getVariant}/include/autoconf.h"
            ]
        },
        {
            "name": "Variant1",
            "includePath": [
                "${workspaceFolder}/src/Variant1/include"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "${default}",
            "forcedInclude": [
                "${workspaceFolder}/build/Variant1/include/autoconf.h"
            ]
        },
        {
            "name": "Variant2",
            "includePath": [
                "${workspaceFolder}/src/Variant2/include"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "${default}",
            "forcedInclude": [
                "${workspaceFolder}/build/Variant2/include/autoconf.h"
            ]
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @HeineHH .  Thanks for submitting this suggestion.

I suspect we may not be able to do exactly what you've suggested, as the extension's configuration is leveraged constantly at runtime. Dynamically re-evaluating the configuration, invoking one or more VS Code commands and awaiting those results, could have a pretty significant performance implication. Currently, the configuration is only re-evaluated when modified. To support something like this, there may need to be some sort of trigger to notify when the configuration would be re-evaluated.
