### ISSUE TITLE
Visual Studio Code issue! Very important, idk what to do! Please help!

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#12888]
### Feature Request

[25.10.2024, 20:41:26] Не удалось разрешить конфигурацию с compilerPath: "gcc". Visual Studio Code. Как решить проблему?
> Translation: Failed to resolve configuration with compilerpath: "gcc". Visual Studio Code. How to solve the problem?

![Image](https://github.com/user-attachments/assets/70880155-d712-4719-95ff-93e050100d62)
![Image](https://github.com/user-attachments/assets/e99b23ec-67c6-476f-9199-90a98ad776d1)

**Comment by sean-mcmanus** [comment]
What is your tasks.json? It appears to be trying to launch an executable called outDebug (without an extension) -- normally it would end in .exe on Windows.
