### ISSUE TITLE
ChangeCompileCommandsNotification is sent/processed even if a configuration provider is used instead of compile commands

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#12889]
It seems like it should only be sent/processed if compile commands is actually being used for configuration.

**Comment by sean-mcmanus** [comment]
If compileCommands is set, then it could still be used as a fallback if the configuration provider doesn't have a configuration for a file, but if compileCommands is not set then there's no need to send an update for one.

**Comment by Colengms** [comment]
I don't think these notifications cause a perf issue.  They simply result in a dirty flag being set on the native side, causing the `compile_commands.json` to be re-parsed the next time its contents are required.

It would be nice to avoid sending redundant notifications, but I think that might need to be part of a more wholistic change, to ensure changes are properly synchronized with TU creation.

We have some work (currently on the back burner) to address https://github.com/microsoft/vscode-cpptools/issues/6931 , which may result in the current `compile_commands.json` handling being replaced (processed entirely on the TypeSide side).
