### ISSUE TITLE
 memory viewer in debug

### ISSUE THREAD

**Issue by ghamelin** [microsoft/vscode-cpptools#1289]
Since there has been an update to the vscode ( https://code.visualstudio.com/updates/v1_15#_loaded-scripts-explorer ) is there a way to view memory usage in debug mode?

**Comment by pieandcakes** [comment]
@redhedgh12 This looks to be implemented by the VS Code team in VS Code. I don't think they added extensibility for UI so if you want to have memory usage in debug mode as part of the UI you probably need to ask them [here](https://github.com/microsoft/vscode/issues).

**Comment by pieandcakes** [comment]
Duplicate of #509
