### ISSUE TITLE
Intellisense doesn't work at all

### ISSUE THREAD

**Issue by abbgl53** [microsoft/vscode-cpptools#12893]
### Environment

- OS and Version: Windows 11 Pro 23H2
- VS Code Version: 1.94.2
- C/C++ Extension Version: v1.22.10
- If using SSH remote, specify OS of remote machine: CentOS Linux release 7.9.2009 (Core)

### Bug Summary and Steps to Reproduce

Bug Summary:
Intellisense hasn't been working for about a week even though I haven't made any changes. includePath and cannot open source file error. In standard C++ libraries it doesn't give errors, but this time it doesn't find references. When I add my own libraries, it doesn't work at all.

What I tried:

- I updated includePath. I gave fullpath into includePath one by one.
- I tried on another centos machine and it works there.
- I installed the old version of cpp extension.
- I tried it on WSL2 and it works
- I completely deleted the vscode-server folder on the remote server and reinstalled everything

Everything was normal until a week ago, but suddenly it stopped working.

![Image](https://github.com/user-attachments/assets/6e44b643-7189-41c1-97d0-701542de2cc3)
![Image](https://github.com/user-attachments/assets/d33edb85-51c6-413e-8bf1-f9fafa8fd99d)

### Configuration and Logs

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/local/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}

**Comment by huttuh** [comment]
I encountered the same problem...

**Comment by sean-mcmanus** [comment]
@babaoglu53 @huttuh When you run the C/C++: Log Diagnostics command, do you see it repot an invalid configuration? Are you using -I with a system include? Does the issue not repro with 1.21.6?

**Comment by babaoglu53** [comment]
The problem persists with both of them. Also the Log Diagnostics command outputs is as follows:

-------- Diagnostics - 10/29/2024, 12:08:55 AM
Version: 1.22.10
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/data/user1/projects/test/**"
    ],
    "defines": [],
    "compilerPath": "/usr/local/bin/g++",
    "intelliSenseMode": "linux-gcc-x64",
    "cppStandard": "c++14",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/usr/local/bin/g++",
    "cStandard": "gnu23",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "/data/user1/projects/test/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Modified Settings:
{
    "C_Cpp.default.cStandard": "gnu23",
    "C_Cpp.default.cppStandard": "gnu++23"
}
Additional Tracked Settings:
{
    "editorTabSize": 4,
    "editorInsertSpaces": true,
    "editorAutoClosingBrackets": "always",
    "filesEncoding": "utf8",
    "filesAssociations": {},
    "filesExclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/Thumbs.db": true
    },
    "filesAutoSaveAfterDelay": true,
    "editorInlayHintsEnabled": true,
    "editorParameterHintsEnabled": true,
    "searchExclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/*.code-search": true
    },
    "workbenchSettingsEditor": "ui"
}
cpptools version (native): 1.22.10.0
Current database path: /home/user1/.cache/vscode-cpptools/b21412dcab1fff106533714f9fb12a21/.browse.VC.db
Translation Unit Mappings:
[ /data/user1/projects/test/newapp/NewApp.cpp - source TU]:
Translation Unit Configurations:
[ /data/user1/projects/test/newapp/NewApp.cpp ]
    Process ID: 12289
    Memory Usage: 10 MB
    Compiler Path: /usr/local/bin/g++
    Includes:
    System Includes:
        /usr/local/include/c++/5.4.0
        /usr/local/include/c++/5.4.0/x86_64-unknown-linux-gnu
        /usr/local/include/c++/5.4.0/backward
        /usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include
        /usr/local/include
        /usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include-fixed
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=50400
Total Memory Usage: 10 MB

==================================================================================

-------- Diagnostics - 10/29/2024, 12:11:20 AM
Version: 1.21.6
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/data/user1/projects/test/**"
    ],
    "defines": [],
    "compilerPath": "/usr/local/bin/g++",
    "intelliSenseMode": "linux-gcc-x64",
    "cppStandard": "c++14",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/usr/local/bin/g++",
    "cStandard": "gnu23",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "/data/user1/projects/test/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
cpptools version (native): 1.21.6.0
Translation Unit Mappings:
[ /data/user1/projects/test/newapp/NewApp.cpp - source TU]:
Translation Unit Configurations:
[ /data/user1/projects/test/newapp/NewApp.cpp ]:
    Process ID: 12584
    Memory Usage: 10 MB
    Compiler Path: /usr/local/bin/g++
    Includes:
    System Includes:
        /usr/local/include/c++/5.4.0
        /usr/local/include/c++/5.4.0/x86_64-unknown-linux-gnu
        /usr/local/include/c++/5.4.0/backward
        /usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include
        /usr/local/include
        /usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include-fixed
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=50400
Total Memory Usage: 10 MB

**Comment by sean-mcmanus** [comment]
@babaoglu53 I think gcc 5.4 was released in 2016, but your settings use gnu++23, which may require g++ 12 or newer. That might not be the issue though.

Can you try replacing `"/data/user1/projects/test/**"` with 

```json
"/data/user1/projects/test/newapp",
"/data/user1/projects/test/include"
```

or whatever other include directories you need?

It looks like something is causing the resolving of `"**"` in your includePath to fail, possibly due to a database issue.

Can you try doing a Reset IntelliSense Database after setting C_Cpp.loggingLevel to "Debug" and see if the "C/C++" window shows tag parsing messages or if there are database errors/failures?

**Comment by sean-mcmanus** [comment]
Also, you may want to confirm the database file `/home/user1/.cache/vscode-cpptools/b21412dcab1fff106533714f9fb12a21/.browse.VC.db` has write permissions.

**Comment by babaoglu53** [comment]
I think the problem was .cache. I reinstalled everything related to .vscode-server and .cache on the remote server and it works now. Thank you very much for your help.
