### ISSUE TITLE
Symbols lookup - different multifolder workspaces

### ISSUE THREAD

**Issue by Racer84** [microsoft/vscode-cpptools#12903]
### Environment

- OS and Version: Ubuntu 22.04.5 LTS
- VS Code Version: 
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.5.0-44-generic
- C/C++ Extension Version: v1.22.10

### Bug Summary and Steps to Reproduce

Being in the first workspace, I want to prevent searching for symbols from the second workspace. Both workspaces contain, among other things, definitions of the same symbols but from different branches.
I set in each workspace separately, in c_cpp_properties.json:
```

            "browse": {
                "path": [
                  "${workspaceFolder}/",
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceFolder}/.vscode/browse.db" // Workspace-specific index database
              }

```
and in .code-workspace:

`"C_Cpp.intelliSenseCachePath": "${workspaceFolder}/.vscode/ipch/"`

but unfortunately it didn't help. When I click on a symbol in the first workspace it opens its definition from the second workspace.[c_cpp_properties.json](https://github.com/user-attachments/files/17563265/c_cpp_properties.json)

### Configuration and Logs

-------- Diagnostics - 10/29/2024, 10:36:03 PM
Version: 1.22.10
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/grzes/sources/repo_aib/alior/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerPathInCppPropertiesJson": "/usr/bin/gcc",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "/home/grzes/sources/repo_aib/alior/**",
            "${workspaceFolder}"
        ]
    }
}
Modified Settings:
{
    "C_Cpp.default.includePath": [
        "${workspaceFolder}/**",
        "/usr/include"
    ],
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.default.compilerPath": "/usr/bin/gcc",
    "C_Cpp.default.browse.limitSymbolsToIncludedHeaders": false,
    "C_Cpp.default.enableConfigurationSquiggles": false,
    "C_Cpp.intelliSenseCachePath": "${workspaceFolder}/.vscode/ipch/",
    "C_Cpp.updateChannel": "Insiders"
}
Additional Tracked Settings:
{
    "editorTabSize": 4,
    "editorInsertSpaces": true,
    "editorAutoClosingBrackets": "languageDefined",
    "filesEncoding": "utf8",
    "filesAssociations": {
        "*.plsql": "sql",
        "*.inc": "xml",
        "*.cfg": "xml",
        "*.req": "xml",
        "readme": "cpp",
        "*.tcc": "cpp",
        "*.ipp": "cpp",
        "string": "cpp",
        "iostream": "cpp",
        "bitset": "cpp",
        "random": "cpp",
        "numeric": "cpp",
        "ostream": "cpp",
        "deque": "cpp",
        "rope": "cpp",
        "slist": "cpp",
        "list": "cpp",
        "fstream": "cpp",
        "*.ixx": "cpp",
        "iosfwd": "cpp",
        "thread": "cpp",
        "ranges": "cpp",
        "tuple": "cpp",
        "typeindex": "cpp",
        "typeinfo": "cpp",
        "string_view": "cpp",
        "map": "cpp",
        "algorithm": "cpp",
        "unordered_map": "cpp",
        "array": "cpp",
        "unordered_set": "cpp",
        "vector": "cpp",
        "initializer_list": "cpp",
        "span": "cpp",
        "regex": "cpp",
        "valarray": "cpp",
        "forward_list": "cpp",
        "hash_map": "cpp",
        "hash_set": "cpp",
        "utility": "cpp",
        "source_location": "cpp",
        "any": "cpp",
        "cstdlib": "cpp"
    },
    "filesExclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/Thumbs.db": true,
        "**/*.bak": true,
        "**/*.BAK": true,
        "**/*.d": true,
        "**/*.o": true
    },
    "filesAutoSaveAfterDelay": false,
    "editorInlayHintsEnabled": true,
    "editorParameterHintsEnabled": true,
    "searchExclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/*.code-search": true,
        "/home/grzes/sources/repo/*": true
    },
    "workbenchSettingsEditor": "ui"
}
cpptools version (native): 1.22.10.0
Current database path: /home/grzes/.cache/vscode-cpptools/8660d1e415d99c9445fc16bbcc1eec57/.browse.VC.db
No active translation units.

**Comment by sean-mcmanus** [comment]
@Racer84 Setting

```json
            "browse": {
                "path": []
            }
```

in your c_cpp_properties.json of the 2nd workspace should cause those symbols to not be found, unless you happen to open a file from the 2nd workspace, in which case, you should be able to fix that by adding

```json
    "C_Cpp.files.exclude": {
        "**": true
    }
}
```

to your settings.json in the 2nd workspace.

Does that work for you?

**Comment by Racer84** [comment]
No, it does not.

Here content of c_cpp_properties.json in the 1st workspace:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/home/grzes/sources/repo_aib/**",
                "/usr/include/libxml2"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++11",
            "intelliSenseMode": "linux-gcc-x64",
            "browse": {
                "path": [
                  "/home/grzes/sources/repo_aib/**"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceFolder}/.vscode/browse.db" // Workspace-specific index database
              }
        }
    ],
    "version": 4
}
```
and content of settings.json in 1st workspace:
```
{
    "files.associations": {
        "*.plsql": "sql",
        "*.inc": "xml",
        "*.cfg": "xml",
        "string": "cpp",
        "iostream": "cpp",
        "thread": "cpp",
        "readme": "cpp",
        "iosfwd": "cpp"
    },
    "C_Cpp.errorSquiggles": "Disabled"
}
```

Content of c_cpp_properties.json in the 2nd workspace:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/libxml2"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++20",
            "intelliSenseMode": "linux-gcc-x64",
            "browse": {
                "path": [],
//                  "${workspaceFolder}/",
//                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceFolder}/.vscode/browse.db" // Workspace-specific index database
              }
            }
    ],
    "version": 4
}
```
and content of settings.json in 2nd workspace:
```
{
    "files.associations": {
        "*.plsql": "sql",
        "*.inc": "xml",
        "*.cfg": "xml",
        "string": "cpp",
        "iostream": "cpp",
        "thread": "cpp",
        "readme": "cpp",
        "iosfwd": "cpp"
    },
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.files.exclude": {
        "**": true
    }
}
```

I've ran workspace rescan after applying changes you suggested. Still, when I click on certain symbol in the 1st workspace its definition from the 2nd workspace opens. Both workspaces are opened simultaneously, in separate vscode windows.

**Comment by sean-mcmanus** [comment]
@Racer84 When set C_Cpp.loggingLevel to "Debug" and do a Reset IntelliSense Database -- what is the 1st reference you see in the "C/C++" logging to files/folders in the 2nd workspace that shouldn't be scanned or tag parsed?

You're using a single workspace with 2 workspace folders, right? I'm not sure what you mean by "in separate vscode windows".

**Comment by Racer84** [comment]
> You're using a single workspace with 2 workspace folders, right? I'm not sure what you mean by "in separate vscode windows".

No. I'm using 2 separate workspaces with multi-folder configuration. Each workspace has its own directory tree.  Each workspace is opened in own vscode window/instance. 

1st workspace location: `/home/grzes/sources/repo_aib/repo_aib.code-workspace`, starts with:
```
{
  "folders": [
	{
		"path": "/home/grzes/sources/repo_aib/alior"
	},
	{
		"path": "/home/grzes/sources/repo_aib/ca"
	},
	{
		"path": "/home/grzes/sources/repo_aib/cards"
	},
	{
		"path": "/home/grzes/sources/repo_aib/wspolne"
	},
	{
		"path": "/home/grzes/sources/repo_aib/smid"
	},
	{ 
		"path": "/home/grzes/sources/repo_aib/narzedzia"
    },
  ],
```


2nd workspace location: `/home/grzes/sources/repo/repo.code-workspace`, start with:
```
{
  "folders": [
  	{
  		"path": "alior"
  	},
	{
		"path": "advantica_core_banking"
	},
	{
		"path": "bgk/h2h",
		"name": "bgk/h2h"
	},
	{
		"path": "bgk/libs",
		"name": "bgk/libs"
	},
	{
		"path": "bgk/progs",
		"name": "bgk/progs"
	},
	{
		"path": "bgk/schema",
		"name": "bgk/schema"
	},
	{
  		"path": "brutus"
  	},
	{
		"path": "ca"
	},
	{
		"path": "cards"
	},
  	{
		"path": "kir/ebpp2",
		"name": "ebpp"
	},
  	{
		"path": "lukas"
	},
	{
  		"path": "sonet"
  	},
	{
		"path": "wspolne"
	},
	{
		"path": "smid"
	},
	{ 
		"path": "narzedzia"
    },
	{
		"path": "/home/grzes/sources/grafana",
		"name": "grafana"
	}
  ],
```

**Comment by sean-mcmanus** [comment]
@Racer84 Every workspace should have it's own separate database file with symbols, as long as you aren't setting the databaseFilename property/setting to the same path (you can see the path via running C/C++: Log Diagnostics and in your logging I see it's 'Current database path: /home/grzes/.cache/vscode-cpptools/8660d1e415d99c9445fc16bbcc1eec57/.browse.VC.db"). I don't see paths from the 2nd workspace in the 1st workspace unless the 1st workspace happens to have a symlink to the 2nd workspace, in which case you could try adding the foldering containing the symlink to the 2nd folder to the C_Cpp.files.exclude in the 1st workspace.

**Comment by Racer84** [comment]
How to configure separate symbols database file for each workspace properly? I've tried to do this in the first place but it didn't work.

**Comment by sean-mcmanus** [comment]
@Racer84 It looks like you have `"databaseFilename": "${workspaceFolder}/.vscode/browse.db" ` set but for some reason it's using `/home/grzes/.cache/vscode-cpptools/8660d1e415d99c9445fc16bbcc1eec57/.browse.VC.db` instead, which is a different file, unless that is supposed to be different (for the 2nd workspace).

You may need to set the databaseFilename in the c_cpp_properties.json in the 1st workspace. You could also try setting the C_Cpp.default.browse.databaseFilename instead.

**Comment by Racer84** [comment]
> 
> You may need to set the databaseFilename in the c_cpp_properties.json in the 1st workspace. 

I've done so at the very beginning. It has no effect, database file is not created under given location.

> You could also try setting the C_Cpp.default.browse.databaseFilename instead.

I've set this in both workspaces. It didn't help neither. Dedicated database file is not created. Definition of symbol from 2nd workspace - indicated by path of opened file - opens when clicking it in 1st workspace.

Can I provide any diagnostics?

**Comment by Racer84** [comment]
Why /home/grzes/.cache/vscode-cpptools/8660d1e415d99c9445fc16bbcc1eec57/.browse.VC.db is used?

**Comment by Racer84** [comment]
Problem still exists. As I asked earlier - what info do you need?

**Comment by sean-mcmanus** [comment]
@Racer84 Sorry for not responding earlier. Can you double check that the databaseFilename property appears when you do C/C++: Log Diagnostics? The logging you provided earlier doesn't contain that so maybe you added that setting afterwards?

**Comment by Racer84** [comment]
> [@Racer84](https://github.com/Racer84) Sorry for not responding earlier. Can you double check that the databaseFilename property appears when you do C/C++: Log Diagnostics? The logging you provided earlier doesn't contain that so maybe you added that setting afterwards?
> 

From C/C++: Log Diagnostics: "Current database path: /home/grzes/sources/repo_aib/alior/.vscode/browse.db"

> Also, if you set C_Cpp.loggingLevel to "Debug" check the C/C++ for any database related error messages. Also, check if the extension has write permissions to that location.

There are no such error messages in C/C++: Log Diagnostics output. The extension has the same permissions as user and vscode I guess, so yes, it has write permission.

**Comment by sean-mcmanus** [comment]
@Racer84 So what is the bug? One workspace uses `/home/grzes/sources/repo_aib/alior/.vscode/browse.db` and the other workspace uses a different database? It sounded like you were saying they were using the same database? Does one workspace folder reference folders from the other workspace somehow?

**Comment by Racer84** [comment]
The bug is that I still see symbols from workspace B when working in workspace A. Workspaces use different folders with no cross links.

**Comment by heartacker** [comment]
yes ，i have same issue 
Gray  for fix

**Comment by sean-mcmanus** [comment]
@Racer84 @heartacker We have not seen this issue before and we're not sure how it's possible. If you do a Reset IntelliSense Database in the workspace folder that has the wrong symbols, where is the first place in the C/C++ logging and C_Cpp.loggingLevel set to "Debug" where you see references to the incorrect workspace folders/files, e.g. a "Processing folder" or "tag parsing" message?

**Comment by Racer84** [comment]
I don't see it in C/C++ Diagnostics. But when I Ctrl+click on symbol on workspace A it opens its definition from workspace B.

**Comment by Racer84** [comment]
I reset workspace B and reconfigured every workspace folder. Now it looks fine: when I ctrl+click on symbol its definition from workspace B opens. Maybe I had bad definition of includes for some of folders formerly. Anyway - it works now.

Thanks for your help.

**Comment by heartacker** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/20395775?s=64&amp;v=4">@Racer84](https://github.com/Racer84?rgh-link-date=2024-12-11T18%3A40%3A59.000Z) [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/1876302?s=64&amp;u=ddd7ad4764a65b6542ecf14db544a1f6192a0ceb&amp;v=4">@heartacker](https://github.com/heartacker?rgh-link-date=2024-12-11T18%3A40%3A59.000Z) We have not seen this issue before and we're not sure how it's possible. If you do a Reset IntelliSense Database in the workspace folder that has the wrong symbols, where is the first place in the C/C++ logging and C_Cpp.loggingLevel set to "Debug" where you see references to the incorrect workspace folders/files, e.g. a "Processing folder" or "tag parsing" message?

I Find that if  I open two folders-workspace which is in a soft-link folder
This is what happens

```
/a/b/c/d/e/f/gits/ws1
/a/b/c/d/e/f/gits/ws1

li -s /a/b/c/d/e/f/gits ~/gits

open ~/gits/ws1 and ~/gits/ws2

```

**Comment by heartacker** [comment]
@sean-mcmanus 
no

Even if I open the absolute path, it still shows things in different workspaces
![Image](https://github.com/user-attachments/assets/5d739696-1d57-48d6-988f-6d7e09b0942f)

M2 and D2 is different folder in one workspace
![Image](https://github.com/user-attachments/assets/f1746a9f-33b4-41e1-9ebc-44064bf08cc1)
