### ISSUE TITLE
Setting for turning off include with C++ definition

### ISSUE THREAD

**Issue by orichalcink** [microsoft/vscode-cpptools#12918]
### Feature Request

The option "Create Declaration / Definition" should have a setting to enable/disable automatically writting the '#include "file.hpp"' as sometimes it can get the path wrong and throw an error.

**Comment by sean-mcmanus** [comment]
Oh, it looks like this setting already exists: C_Cpp.refactoring.includeHeader (see https://github.com/microsoft/vscode-cpptools/issues/11271 ).

For reference, the known wrong include paths bugs are https://github.com/microsoft/vscode-cpptools/issues/11581 and https://github.com/microsoft/vscode-cpptools/issues/12897 .
