### ISSUE TITLE
.vscode folder not containing .json

### ISSUE THREAD

**Issue by ElBrineZ** [microsoft/vscode-cpptools#12920]
Type: <b>Feature Request</b>

tasks.json, launch.json, c_cpp_properties.json didn't show on the .vscode folder, do i have to make these files or?

my frist time using this so please forgive my stupidity

Extension version: 1.22.10
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by bobbrow** [comment]
Hi @ElBrineZ, there files are generally created on-demand.  tasks.json and launch.json are created when the corresponding menu options are selected in VS Code.  c_cpp_properties.json is created when you run one of the "C/C++: Edit Configurations" commands.  (for the UI version of the command, it may not actually be created until you edit something though)
