### ISSUE TITLE
"Include file not found in include directory" when directories contain environment variables"

### ISSUE THREAD

**Issue by mhallak** [microsoft/vscode-cpptools#1292]
Version:
`
Version 1.18.1

Commit 929bacba01ef658b873545e26034d1a8067445e9
Date 2017-11-16T18:34:22.110Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64`

OS: Ubuntu 16.04
`       {
            "name": "Linux",

            "includePath": [
                "/usr/include/c++/5",
                "/usr/include/x86_64-linux-gnu/c++/5",
                "/usr/include/c++/5/backward",
                "/usr/lib/gcc/x86_64-linux-gnu/5/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include",
                "/usr/include/ignition",
                "${workspaceRoot}",
                "${GZROOT}/devel_isolated/gazebo/include/gazebo-8",
                "${GZROOT}/devel_isolated/sdformat/include/sdformat-5.2",
                "/usr/include/ignition/math3",
                "/usr/include/ignition/msgs0",
                "/usr/include/ignition/transport3"
            ],`

It doesnt understand $GZROOT:

`robil@apollo:~/$ echo $GZROOT
/home/robil/gazebo8`

**Comment by bobbrow** [comment]
Hmm... it works for me.  Is it possible that $GZROOT isn't defined in the environment picked up by VS Code?  I tried using ${HOME} on my linux box and it worked fine.

**Comment by mhallak** [comment]
Following your advice, I exited and re-opened Visual Code and it seems that it works... Not really clear since $GZROOT was known in the Integrated Terminal... (That's the way I checked).
I am closing the issue... Thank you and sorry.
