### ISSUE TITLE
Incorrect preprocessor macro highlighting (with Chinese comment)

### ISSUE THREAD

**Issue by Gornerrrrr** [microsoft/vscode-cpptools#12928]
### Environment

- OS and Version:  Windows11 23H2
- VS Code Version:  v1.95.1
- C/C++ Extension Version:  v1.22.10

### Bug Summary and Steps to Reproduce

Bug Summary:
Preprocessor macro directives are not highlighted correctly.
![Image](https://github.com/user-attachments/assets/afe3694d-d4e2-4658-a237-b46ca91e927c)

Steps to reproduce:
Change the test file extension to '.h' and open it with VSCode.
[test_IntelliSense.txt](https://github.com/user-attachments/files/17628317/test_IntelliSense.txt)

Expected behavior:
Highlight the areas where the condition is true, and darken the areas where the condition is false.
![Image](https://github.com/user-attachments/assets/98cae378-7a8c-4ca9-84f2-a3519c774f1e)

### Configuration and Logs

//
// !!! WARNING !!! AUTO-GENERATED FILE!
// PLEASE DO NOT MODIFY IT AND USE "platformio.ini":
// https://docs.platformio.org/page/projectconf/section_env_build.html#build-flags
//
{
    "configurations": [
        {
            "name": "PlatformIO",
            "includePath": [
                "P:/Printer/HIM_SLA/Marlin",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/Wire/src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/SoftwareSerial/src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/Servo/src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/SPI/src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/IWatchdog/src",
                "P:/Printer/HIM_SLA/Marlin/model_cfg",
                "P:/Printer/HIM_SLA/Marlin/src/module/lcd",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/avr",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/LL",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/usb",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/OpenAMP",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/usb/hid",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/usb/cdc",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Drivers/STM32F4xx_HAL_Driver/Inc",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Drivers/STM32F4xx_HAL_Driver/Src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/STM32F4xx",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/OpenAMP",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/OpenAMP/open-amp/lib/include",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/OpenAMP/libmetal/lib/include",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/OpenAMP/virtual_driver",
                "S:/Work/platformIO/packages/framework-cmsis@2.50501.200527/CMSIS/Core/Include",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc",
                "S:/Work/platformIO/packages/framework-cmsis@2.50501.200527/CMSIS/DSP/Include",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/variants/HIM_16INCH_F407",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/CMSIS_DSP/src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/EEPROM/src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/Keyboard/src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/Mouse/src",
                "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/SrcWrapper/src",
                ""
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "path": [
                    "P:/Printer/HIM_SLA/Marlin",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/Wire/src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/SoftwareSerial/src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/Servo/src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/SPI/src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/IWatchdog/src",
                    "P:/Printer/HIM_SLA/Marlin/model_cfg",
                    "P:/Printer/HIM_SLA/Marlin/src/module/lcd",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/avr",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/LL",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/usb",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/OpenAMP",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/usb/hid",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/stm32/usb/cdc",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Drivers/STM32F4xx_HAL_Driver/Inc",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Drivers/STM32F4xx_HAL_Driver/Src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/STM32F4xx",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/OpenAMP",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/OpenAMP/open-amp/lib/include",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/OpenAMP/libmetal/lib/include",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Middlewares/OpenAMP/virtual_driver",
                    "S:/Work/platformIO/packages/framework-cmsis@2.50501.200527/CMSIS/Core/Include",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc",
                    "S:/Work/platformIO/packages/framework-cmsis@2.50501.200527/CMSIS/DSP/Include",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/cores/arduino",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/variants/HIM_16INCH_F407",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/CMSIS_DSP/src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/EEPROM/src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/Keyboard/src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/Mouse/src",
                    "S:/Work/platformIO/packages/framework-arduinoststm32@4.10900.200819/libraries/SrcWrapper/src",
                    ""
                ]
            },
            "defines": [
                "PLATFORMIO=60116",
                "STM32F407xx",
                "__MARLIN_FIRMWARE__",
                "NDEBUG",
                "HAL_STM32",
                "USBCON",
                "USBD_USE_CDC",
                "TIM_IRQ_PRIO=13",
                "ADC_RESOLUTION=12",
                "VECT_TAB_OFFSET=0x10000",
                "ARDUINO_BLACK_F407VE",
                "PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF",
                "PIO_FRAMEWORK_ARDUINO_ENABLE_CDC",
                "USBCON",
                "USBD_USE_CDC",
                "HAVE_HWSERIAL1",
                "HAVE_HWSERIAL2",
                "HAVE_HWSERIAL3",
                "HAVE_HWSERIAL6",
                "SERIAL_RX_BUFFER_SIZE=512",
                "SERIAL_TX_BUFFER_SIZE=512",
                "STM32F4xx",
                "ARDUINO=10808",
                "ARDUINO_ARCH_STM32",
                "ARDUINO_HIM_16INCH_F407",
                "BOARD_NAME=\"HIM_16INCH_F407\"",
                "HAL_UART_MODULE_ENABLED",
                "USBD_USE_CDC",
                "HAL_PCD_MODULE_ENABLED",
                ""
            ],
            "cStandard": "gnu11",
            "cppStandard": "gnu++14",
            "compilerPath": "S:/Work/platformIO/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/arm-none-eabi-gcc.exe",
            "compilerArgs": [
                "-mfpu=fpv4-sp-d16",
                "-mfloat-abi=hard",
                "-mcpu=cortex-m4",
                "-mthumb",
                ""
            ]
        }
    ],
    "version": 4
}

### Additional context

I have been using the [Marlin](https://github.com/MarlinFirmware/Marlin) project to control my 3D printer. This project uses a large number of [preprocessor directives](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/core/macros.h), and I often encounter some jumping or display issues. Have any good suggestions?

**Comment by Gornerrrrr** [comment]
This issue has already been fixed in the pre-release version.

**Comment by sean-mcmanus** [comment]
@Gornerrrrr Yes, it was fixed from https://github.com/microsoft/vscode-cpptools/issues/12879 .
