### ISSUE TITLE
IncludePath Set Correctly but VS Code Fails to Compile with g++

### ISSUE THREAD

**Issue by Willaaaaaaa** [microsoft/vscode-cpptools#12936]
Type: <b>Bug</b>

I'm new to C++ and currently self-studying Stanford cs106. Instead of using Qt as the course recommended, I chose vscode and g++(from MSYS2) to compile my code.
But I found myself couldn't run the code properly though I’ve adjusted the settings and added the include paths. And I'm sure the path is correct because I can go to the headers' definition by pressing F12. But it just can't compile.
Here’s the terminal output:
```
Starting build...
cmd /c chcp 65001>nul && E:\msys64\ucrt64\bin\g++.exe -fdiagnostics-color=always -g "D:\CS learning\self learning\CS 106B\Recursion2.cpp" -o "D:\CS learning\self learning\CS 106B/bin/Recursion2.exe" -I E:/Qt/6.8.0/mingw_64/include
D:\CS learning\self learning\CS 106B\Recursion2.cpp:8:10: fatal error: strlib.h: No such file or directory
    8 | #include "strlib.h"
      |          ^~~~~~~~~~
compilation terminated.

Build finished with error(s).
```
Any advice on how to resolve this error would be greatly appreciated! Thank you.

P.S. I wonder why there isn't a `Question` option. I have to choose `Bug Report` though I don't think it's a bug. Sorry to bother.

Extension version: 1.22.11
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Willaaaaaaa** [comment]
# More information
## **task.json:**
```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "E:\\msys64\\ucrt64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${workspaceFolder}/bin/${fileBasenameNoExtension}.exe",
                "-I",
                "D:/CS learning/self learning/CS 106B/CourseSrc/CS106/Library",
                "-I",
                "E:/Qt/6.8.0/mingw_64/include"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

## **c_cpp_properties.json:**
```json
{
    "configurations": [
      {
        "name": "Win32",
        "includePath": [
          "${workspaceFolder}/**",
          "D:/CS learning/self learning/CS 106B/CourseSrc/CS106/Library/**",
          "E:/Qt/6.8.0/mingw_64/include/**"
        ],
        "defines": [
          "_DEBUG",
          "UNICODE",
          "_UNICODE"
        ],
        "intelliSenseMode": "windows-gcc-x64",
        "compilerPath": "E:/msys64/ucrt64/bin/g++.exe",
        "cppStandard": "c++20",
        "cStandard": "c17"
      }
    ],
    "version": 4
  }
```

**Comment by sean-mcmanus** [comment]
@Willaaaaaaa You should remove system includes from your includePath and `-I` usage. Adding that can cause the wrong headers to resolve due to ordering of includes causing it to take priority over the system includes. They should normally be provided by the compiler already (there's like 5+ system includes that all generally need to specified in a specific order or it won't work). Does that fix your issue?

**Comment by Willaaaaaaa** [comment]
Sir, is this what you meant to do? But after I modified it, two errors appeared. What you said does make sense. It is really a very rigorous idea that includePath should follow a certain order.
![Image](https://github.com/user-attachments/assets/5afc0b0f-36cd-4a21-889b-e65ecfb3f224)

**Comment by Willaaaaaaa** [comment]
@sean-mcmanus  Sorry, sir. I found that I have put you in an awkward situation since you may have no idea about how this libary is constructed and implemented.
And after spending the past few days researching, I believe the issue might not only be related to the include path but also to the linker settings. Could you provide some general advice on how to address this problem? Unfortunately, I haven’t been able to find relevant documentation on https://code.visualstudio.com/docs.
(sorry, I'm really new to it.

**Comment by Willaaaaaaa** [comment]
Can cmake, Makefile or Premake deal with this?

**Comment by Willaaaaaaa** [comment]
> [@Willaaaaaaa](https://github.com/Willaaaaaaa) You should remove system includes from your includePath and `-I` usage. Adding that can cause the wrong headers to resolve due to ordering of includes causing it to take priority over the system includes. They should normally be provided by the compiler already (there's like 5+ system includes that all generally need to specified in a specific order or it won't work). Does that fix your issue?

@sean-mcmanus Thank you, sir. I finally managed it!! Your idea is right, it really gave me a lot of inspiration, thank you again!

**Comment by Willaaaaaaa** [comment]
I have uploaded my configuration file examples in my repository for your reference only, and suggestions are welcome.
https://github.com/Willaaaaaaa/StanfordPortableLibrary_VSCode.git
