### ISSUE TITLE
[XTENSA] Intellisense initialization failing for unrecognized gcc command

### ISSUE THREAD

**Issue by KonssnoK** [microsoft/vscode-cpptools#12934]
### Environment

- OS and Version: Win11
- VS Code Version: 1.95.1
- C/C++ Extension Version: v1.22.11

### Bug Summary and Steps to Reproduce

Bug Summary:

Apparently 
 `C:\src\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-gcc.exe -mlongcalls -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -fdiagnostics-color=always -ffunction-sections -fdata-sections -gdwarf-4 -ggdb -mdisable-hardware-atomics -Og -fno-shrink-wrap -fmacro-prefix-map=C:/src/v3/firmware=. -fmacro-prefix-map=C:/src/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -m32 -Wp,-v -E -dM -x c nul`
contains a comma after `-Wp,` that makes the compiler go angry:

![Image](https://github.com/user-attachments/assets/9fca543d-232c-4255-b37e-1f0c51d0b11e)

If i manually remove the comma, i get instead:

![Image](https://github.com/user-attachments/assets/69ccae35-864a-49ef-892a-870ae213570d)

is there a way to remove the comma? 

thanks

### Configuration and Logs

```
Attempting to get defaults from C compiler in "compilerPath" property: 'C:\src\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-gcc.exe'
Compiler query command line: C:\src\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-gcc.exe -mlongcalls -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -fdiagnostics-color=always -ffunction-sections -fdata-sections -gdwarf-4 -ggdb -mdisable-hardware-atomics -Og -fno-shrink-wrap -fmacro-prefix-map=C:/src/v3/firmware=. -fmacro-prefix-map=C:/src/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -m32 -Wp,-v -E -dM -x c nul
Failed to query compiler. Falling back to 64-bit intelliSenseMode.
Compiler query command line: C:\src\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-gcc.exe -mlongcalls -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -fdiagnostics-color=always -ffunction-sections -fdata-sections -gdwarf-4 -ggdb -mdisable-hardware-atomics -Og -fno-shrink-wrap -fmacro-prefix-map=C:/src/v3/firmware=. -fmacro-prefix-map=C:/src/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -m64 -Wp,-v -E -dM -x c nul
Failed to query compiler. Falling back to no bitness.
Compiler query command line: C:\src\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-gcc.exe -mlongcalls -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -fdiagnostics-color=always -ffunction-sections -fdata-sections -gdwarf-4 -ggdb -mdisable-hardware-atomics -Og -fno-shrink-wrap -fmacro-prefix-map=C:/src/v3/firmware=. -fmacro-prefix-map=C:/src/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -Wp,-v -E -dM -x c nul
[01m[Kxtensa-esp32s3-elf-gcc.exe:[m[K [01;31m[Kerror: [m[Kunrecognized command-line option '[01m[K-mdisable-hardware-atomics[m[K'

```

**Comment by sean-mcmanus** [comment]
@KonssnoK Does changing the `-Wp,v` to `-v` work? Does your compiler define `__EDG__` or something "similar"?

**Comment by KonssnoK** [comment]
@sean-mcmanus the line is `-Wp,-v`, not `-Wp,v`
`
C:\src\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-gcc.exe -mlongcalls -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -fdiagnostics-color=always -ffunction-sections -fdata-sections -gdwarf-4 -ggdb -mdisable-hardware-atomics -Og -fno-shrink-wrap -fmacro-prefix-map=C:/src/v3/firmware=. -fmacro-prefix-map=C:/src/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -m32 -Wp,-v -E -dM -x c nul`

if i remove the `,` and add a space `-Wp -v` the command goes through but some options are not recognized

`C:\src\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-gcc.exe -mlongcalls -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -fdiagnostics-color=always -ffunction-sections -fdata-sections -gdwarf-4 -ggdb -mdisable-hardware-atomics -Og -fno-shrink-wrap -fmacro-prefix-map=C:/src/v3/firmware=. -fmacro-prefix-map=C:/src/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -m32 -Wp -v -E -dM -x c nul`

```
xtensa-esp32s3-elf-gcc.exe: error: unrecognized command-line option '-mdisable-hardware-atomics'
xtensa-esp32s3-elf-gcc.exe: error: unrecognized command-line option '-m32'
xtensa-esp32s3-elf-gcc.exe: error: unrecognized command-line option '-Wp'; did you mean '-W'?
Target: xtensa-esp32s3-elf
Configured with: /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32s3-elf/src/gcc/configure --build=x86_64-build_pc-linux-gnu --host=x86_64-host_w64-mingw32 --target=xtensa-esp32s3-elf --prefix=/builds/idf/crosstool-NG/builds/xtensa-esp32s3-elf --exec_prefix=/builds/idf/crosstool-NG/builds/xtensa-esp32s3-elf --with-local-prefix=/builds/idf/crosstool-NG/builds/xtensa-esp32s3-elf/xtensa-esp32s3-elf --with-headers=/builds/idf/crosstool-NG/builds/xtensa-esp32s3-elf/xtensa-esp32s3-elf/include --with-newlib --enable-threads=no --disable-shared --with-pkgversion='crosstool-NG esp-2022r1' --disable-__cxa_atexit --enable-cxx-flags=-ffunction-sections --disable-libgomp --disable-libmudflap --disable-libmpx --disable-libssp --disable-libquadmath --disable-libquadmath-support --disable-libstdcxx-verbose --with-gmp=/builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32s3-elf/buildtools/complibs-host --with-mpfr=/builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32s3-elf/buildtools/complibs-host --with-mpc=/builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32s3-elf/buildtools/complibs-host --with-isl=/builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32s3-elf/buildtools/complibs-host --enable-lto --enable-target-optspace --without-long-double-128 --disable-nls --enable-multiarch --enable-languages=c,c++ --disable-libstdcxx-verbose --enable-threads=posix --enable-gcov-custom-rtio --enable-libstdcxx-time=yes --with-gnu-ld
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (crosstool-NG esp-2022r1)
```

**Comment by KonssnoK** [comment]
@sean-mcmanus 
I couldn't find any reference to `__EDG__` in the esp_idf repos.
The compiler itself provides these options, but i see no define that is always declared like for the ARM compilers.

```

Options:
  -pass-exit-codes         Exit with highest error code from a phase.
  --help                   Display this information.
  --target-help            Display target specific command line options.
  --help={common|optimizers|params|target|warnings|[^]{joined|separate|undocumented}}[,...].
                           Display specific types of command line options.
  (Use '-v --help' to display command line options of sub-processes).
  --version                Display compiler version information.
  -dumpspecs               Display all of the built in spec strings.
  -dumpversion             Display the version of the compiler.
  -dumpmachine             Display the compiler's target processor.
  -print-search-dirs       Display the directories in the compiler's search path.
  -print-libgcc-file-name  Display the name of the compiler's companion library.
  -print-file-name=<lib>   Display the full path to library <lib>.
  -print-prog-name=<prog>  Display the full path to compiler component <prog>.
  -print-multiarch         Display the target's normalized GNU triplet, used as
                           a component in the library path.
  -print-multi-directory   Display the root directory for versions of libgcc.
  -print-multi-lib         Display the mapping between command line options and
                           multiple library search directories.
  -print-multi-os-directory Display the relative path to OS libraries.
  -print-sysroot           Display the target libraries directory.
  -print-sysroot-headers-suffix Display the sysroot suffix used to find headers.
  -Wa,<options>            Pass comma-separated <options> on to the assembler.
  -Wp,<options>            Pass comma-separated <options> on to the preprocessor.
  -Wl,<options>            Pass comma-separated <options> on to the linker.
  -Xassembler <arg>        Pass <arg> on to the assembler.
  -Xpreprocessor <arg>     Pass <arg> on to the preprocessor.
  -Xlinker <arg>           Pass <arg> on to the linker.
  -save-temps              Do not delete intermediate files.
  -save-temps=<arg>        Do not delete intermediate files.
  -no-canonical-prefixes   Do not canonicalize paths when building relative
                           prefixes to other gcc components.
  -pipe                    Use pipes rather than intermediate files.
  -time                    Time the execution of each subprocess.
  -specs=<file>            Override built-in specs with the contents of <file>.
  -std=<standard>          Assume that the input sources are for <standard>.
  --sysroot=<directory>    Use <directory> as the root directory for headers
                           and libraries.
  -B <directory>           Add <directory> to the compiler's search paths.
  -v                       Display the programs invoked by the compiler.
  -###                     Like -v but options quoted and commands not executed.
  -E                       Preprocess only; do not compile, assemble or link.
  -S                       Compile only; do not assemble or link.
  -c                       Compile and assemble, but do not link.
  -o <file>                Place the output into <file>.
  -pie                     Create a dynamically linked position independent
                           executable.
  -shared                  Create a shared library.
  -x <language>            Specify the language of the following input files.
                           Permissible languages include: c c++ assembler none
                           'none' means revert to the default behavior of
                           guessing the language based on the file's extension.
```

Funny that there is this options set in the list:

`  -Wp,<options>            Pass comma-separated <options> on to the preprocessor.`

**Comment by KonssnoK** [comment]
Hi @sean-mcmanus did you have time to check on this? only my last message is relevant i think

**Comment by sean-mcmanus** [comment]
@KonssnoK Not yet, I'll check later today...

**Comment by Colengms** [comment]
Hi @KonssnoK .  The only issue I see here is the following:

```
xtensa-esp32s3-elf-gcc.exe: error: unrecognized command line option '-mdisable-hardware-atomics'
```

The prior 2 attempts to query the compiler involved trying to specifying -m32 and -m64 options to detect x86 and x64 support, which this compiler does not support.  The final compiler query fails only due to the error above.

Do you expect this compiler argument to be accepted?  If so, is there perhaps another compiler argument necessary to enable support for this one?  It's possible that another compiler argument was stripped out of the query and needs to be retained in order for the compiler to properly handle this argument.  Or if that argument isn't needed (or wouldn't influence IntelliSense), perhaps it could be removed.

**Comment by sean-mcmanus** [comment]
@Colengms Cool, thanks for answering (I was busy) :)

**Comment by KonssnoK** [comment]
> Hi [@KonssnoK](https://github.com/KonssnoK) . The only issue I see here is the following:
> 
> ```
> xtensa-esp32s3-elf-gcc.exe: error: unrecognized command line option '-mdisable-hardware-atomics'
> ```
> 
> The prior 2 attempts to query the compiler involved trying to specifying -m32 and -m64 options to detect x86 and x64 support, which this compiler does not support. The final compiler query fails only due to the error above.
> 
> Do you expect this compiler argument to be accepted? If so, is there perhaps another compiler argument necessary to enable support for this one? It's possible that another compiler argument was stripped out of the query and needs to be retained in order for the compiler to properly handle this argument. Or if that argument isn't needed (or wouldn't influence IntelliSense), perhaps it could be removed.
> 
> I'm not sure if running via PowerShell accurately reflects how the command line is actually executed by the C/C++ Extension (which uses `CreateProcessW`) . Using the command shell may be more accurate. On Windows, command line arguments are sent as a single string to the executable (unlike Linux/Mac, where command line parsing is done by a shell) and parsed by that process's runtime library. It's possible PowerShell may do some command line parsing of its own, leading to the incorrect results you're seeing there.

Hi @Colengms,
the compiler is based on GCC 11.2.0
for which i was not able to find the '-mdisable-hardware-atomics' option.
https://gcc.gnu.org/onlinedocs/gcc-11.5.0/gcc/Option-Summary.html
I was not able to find the the option above even in the latest gcc-14 documentation, am i looking the wrong place?

I did find something similar in the SH options `-matomic-model=atomic-model`, but I'm not sure the xtensa version supports it.

-m32 and -m64 exist only for SPARC x86 and few other architectures.

Yes manually trying the commands made me face the powershell issue before reaching the other errors.


How can i remove these options from the command run by intellisense?

Thanks

**Comment by sean-mcmanus** [comment]
@KonssnoK But where is `-mdisable-hardware-atomics` coming from? Does your code compile with that?

**Comment by Colengms** [comment]
Hi @KonssnoK .  Except for a couple specific arguments, the arguments used in the compiler query are not coming from the C/C++ Extension itself.  They would be coming from your configuration. (Your `cpp_properties.json`, `compiler_commands.json`, or a custom configuration provider you're using, such as CMake Tools or Makefile Tools.)  If not apparent, could you provide your `cpp_properties.json` contents and any `C_Cpp` related settings you may have set?

**Comment by KonssnoK** [comment]
thank you both, 
I think that command is coming from the customized version of newlib made by espressif

```
if(CONFIG_STDATOMIC_S32C1I_SPIRAM_WORKAROUND)
    idf_build_set_property(COMPILE_OPTIONS "-mdisable-hardware-atomics" APPEND)
endif()
```
```
config STDATOMIC_S32C1I_SPIRAM_WORKAROUND
    bool
    default SPIRAM && (IDF_TARGET_ESP32 || IDF_TARGET_ESP32S3) && !IDF_TOOLCHAIN_CLANG # TODO IDF-9032
```

but I cannot find documentation for this option anywhere

**Comment by KonssnoK** [comment]
In the end the issue was caused by the fact that the current compiler is not exposed by the espressif extension, so my cpp_properties file remained on an old compiler when we upgraded the SDK.

Changin to this solved:

`"compilerPath": "${config:idf.toolsPathWin}/tools/xtensa-esp-elf/esp-13.2.0_20240530/xtensa-esp-elf/bin/xtensa-esp32s3-elf-gcc.exe",`
