### ISSUE TITLE
Cannot find C++20 module files with relative path in commpile_commands.json

### ISSUE THREAD

**Issue by Juvwxyz** [microsoft/vscode-cpptools#12944]
### Environment

- OS and Version: Win11 24H2
- VS Code Version: 1.95.2
- C/C++ Extension Version: 1.23.1

### Bug Summary and Steps to Reproduce

Intellisense says it cannot find module file:
![Image](https://github.com/user-attachments/assets/21ec42e5-960c-443a-9fcd-e0046dc6c57f)

This path is provided from compile_commands.json generated by xmake. It's a relative path to the "directory" property:
![Image](https://github.com/user-attachments/assets/f9d95f7a-60e6-4937-8134-dd156b6aba0d)

If I edit the path to absolute path manually, intellisense works just fine.

### Configuration and Logs

Configuration:
```json
{
    "version": 4,
    "configurations": [
        {
            "name": "win32",
            "compileCommands": "${workspaceFolder}/compile_commands.json"
        }
    ]
}
```

**Comment by sean-mcmanus** [comment]
@Juvwxyz Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.23.2
