### ISSUE TITLE
Clang Intellisense Mode not recognizing std members

### ISSUE THREAD

**Issue by Sh0es** [microsoft/vscode-cpptools#1295]
**Bug Info:**
OS: Windows 10 (32-bit)
VS Code v. 1.18.1
C/C++ extension v. 0.14.3
Other extensions you installed and if the issue persists after disabling them:
(I have not tried disabling them)
- C/C++ Clang Command Adapter (v. 0.2.2)
- C/C++ Intellisense (v. 0.2.2)
- C# (v. 1.13.1)

Step-by-step instructions to reproduce the issue
- Open c_cpp_properties.json
- Set "intelliSenseMode" to "clang-x64"

Visuals
![vscerror](https://user-images.githubusercontent.com/10179811/33391179-dd6b64e6-d4fd-11e7-8c30-40a7e8eba4ca.png)
![vscsettings](https://user-images.githubusercontent.com/10179811/33391182-df4ecbf4-d4fd-11e7-8f74-e08c713049ca.png)

Additional Info: This error only seems to occur in my `.cpp` files. The names parse just fine in `.h` files.

**Comment by bobbrow** [comment]
If you are using MinGW, take a look at [this documentation](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md).  The Windows Kits and Visual Studio headers won't work in Clang mode, so you should remove them from the path.

**Comment by Sh0es** [comment]
That seemed to fix the problem. Thank you.
