### ISSUE TITLE
Intellisense is slow and non-responsive

### ISSUE THREAD

**Issue by Illya776** [microsoft/vscode-cpptools#12952]
Type: <b>Bug</b>

I'm using VScode with an SSH extension to connect to a remote linux C++ project. The intellisense doesn't seem to respond fast or at all.

Extension version: 1.22.11
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.15.0-213-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.12GB free)|
|Process Argv|--crash-reporter-id 430d46d9-380a-4d25-b0ce-d987031f262a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.7.34.102|
|OS|Linux x64 4.15.0-213-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz (6 x 0)|
|Memory (System)|11.73GB (2.14GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
h409b430:31179529

```

</details>

**Comment by sean-mcmanus** [comment]
@Illya776 We need more info. What does the language status bar show?
![Image](https://github.com/user-attachments/assets/b7b88a27-7a78-42ec-a830-e579cd182af9)

With C_Cpp.loggingLevel set to "Debug" is there any logging that would seem to indicate what is taking the time? Is it logging that an IntelliSense update is taking a long time or is it logging tag parsing messages, etc.?

**Comment by think120** [comment]
I have the same issue. The last working version for me is `v1.20.5` which is the last version whose installation file's name is `cpptools-linux.vsix`  instead of `cpptools-linux-x64.vsix`
