### ISSUE TITLE
I can not see the expand button in visual studio

### ISSUE THREAD

**Issue by Tlearntocode** [microsoft/vscode-cpptools#12967]
Next to the run button there is no expand button like introduction. I have installed the enviroment like introduction video and save the code but still can not run the code. How to solve it guys?
thank you

**Comment by sean-mcmanus** [comment]
@Tlearntocode I don't understand what the issue and I don't see any screenshot. Can you provide more info on what expand button you're referring to?

**Comment by Tlearntocode** [comment]
thanks for responding
It was expected like the first picture which you can see the red square
inside. next to the run button is an arrow(which i call expand button). But
for mine, it does not have one so I am a little bit confused. Additionally,
.when i run the code it said file format not regconized like in picture 3.
I have installed msys64 like introduction on visual studio website, done
step by step similar to video introduction except my visual studio does not
have expand button to click.
Thanks for reading. Hope you have a wonderful day.
Regards






Vào 04:31 AM T.7, 16 Th11, 2024 Sean McManus ***@***.***> đã
viết:
