### ISSUE TITLE
Auto-detect & use `compile_commands.json`

### ISSUE THREAD

**Issue by dapirian** [microsoft/vscode-cpptools#1297]
Mine is in my workspace root, it would be VERY nice if it automatically used it.

**Comment by sean-mcmanus** [comment]
compile_commands.json auto-detection has been added to 0.17.5. Be careful not to hit the "Don't Ask Again" button or the prompt won't ever show up again (we could change it to be per-workspaceFolder if enough users complain).

**Comment by rosenk** [comment]
@sean-mcmanus Quick question: Is there plans to open source this extension?

**Comment by sean-mcmanus** [comment]
@rosenk The typescript part is already open source. We don't currently plan to open source the C/C++ part, in part, due to dependency on licensed third party code that can't be open sourced.

**Comment by zhihaoy** [comment]
@sean-mcmanus  What do you mean of "won't ever show up again?" I reinstalled VS Code and still cannot get it back.

**Comment by sean-mcmanus** [comment]
@zhihaoy We save the state to the vscode.Memento -- it's possible that doing a reinstall doesn't clear that. It can be cleared/bypassed manually modifying the open source TypeScript code, i.e. for testing purposes. Maybe we could add some "clear saved state" command for scenarios like this though.
