### ISSUE TITLE
Provide Quick Fix action for clang-tidy warning 'readability-make-member-function-const'

### ISSUE THREAD

**Issue by davidavetyan** [microsoft/vscode-cpptools#12971]
### Feature Request

Currently, when a `Member function 'f' can be made const clang-tidy [readability-make-member-function-const]` warning pops up, no quick fix action is available in the tooltip.

Please add a code action, to append `const` to the method's declaration/definition.

**Comment by sean-mcmanus** [comment]
@davidavetyan It works for me. Your repro text is different from mine though -- it looks like you may be using another extension or an older version of clang-tidy?

![Image](https://github.com/user-attachments/assets/89d749c2-f276-4b89-92af-5527b9367b01)

![Image](https://github.com/user-attachments/assets/c25ed97e-ddfe-4d86-9ecc-9d87fb3ab301)

![Image](https://github.com/user-attachments/assets/0722f005-e0c0-433f-a6ca-44ebe212de60)


```cpp
class foo
{
  int i;
public:
    int bar() { return i; }
};
```

**Comment by davidavetyan** [comment]
@sean-mcmanus I also have the 'clangd' extension installed. After disabling it, I got the quick fix action for this warning. So I guess this is an issue in clangd, when the method is defined in a different file than the declaration (otherwise seems to work there also, like for your example). Thanks.
