### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 123hhhddd** [microsoft/vscode-cpptools#12980]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.22.11`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.95.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/yuca/AppData/Local/Temp/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
@123hhhddd The file:///c%3A/Users/yuca/AppData/Local/Temp/ms-vscode.cpptools-unresponsive.cpuprofile.txt is not attached.
