### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by Sh0es** [microsoft/vscode-cpptools#1299]
OS: Windows 10 Build 15063
VSCode: v. 1.18.1
Extension: v. 0.14.3
Other Extensions:
- Clang Command Adapter v. 0.2.2
- C# Extension v 1.13.1
- Haskero v. 1.3.1
- ANTLR4 Extension v. 1.1.10
- Clang Command Adapter may be causing the issue.

Issue:
![iostreamnotfound](https://user-images.githubusercontent.com/10179811/33457234-7393db3a-d5e7-11e7-95e4-b912765896d1.png)

**Comment by sean-mcmanus** [comment]
You are correct -- the "file not found" tooltip message is from the  C/C++ Clang Command Adapter extension and not the C++ extension.
