### ISSUE TITLE
IntelliSense process crash detected: handle_update_intellisense

### ISSUE THREAD

**Issue by hellowxy** [microsoft/vscode-cpptools#12999]
### Environment

- OS and Version: macOS Sonoma 16.6.1
- VS Code Version: Version: 1.95.3 (Universal)
- C/C++ Extension Version: v1.22.11
- If using SSH remote, specify OS of remote machine: Tencent tlinux 2.2 (Final)

### Bug Summary and Steps to Reproduce

cpptools-srv
11/26/2024, 3:59:42 PM
SIGSEGV
a_region_tracker::build_sections()+982
a_tracking_manager::check_edits(a_canonicalized_file_name, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, bool, bool*, bool*, a_tracked_region**, a_region_scope_info*) const+892
edge::scoped_query_manager::check_and_compile(edge::file_position const&, edge::file_position const&, edge::file_position const&, bool, bool, bool)+899
edge::scoped_query_manager::update_fragment(edge::file_position const&, edge::file_position const&, edge::file_position const&, edge::update_fragment_options const&)+51
edge::an_edge_translation_unit_impl::update_range(edge::allocator*, snapshot::snapshot_session_t, edge::file_position, edge::file_position, edge::update_range_options const&, edge::file_position, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>*, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>*, an_array_list<edge::update_range_action*, std::allocator<edge::update_range_action*>> const&, edge::query_action_data&)+1209
edge::translation_unit::update_range(edge::allocator*, snapshot::snapshot_session_t, edge::file_position, edge::file_position, edge::update_range_options const&, edge::file_position, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>*, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>*, an_array_list<edge::update_range_action*, std::allocator<edge::update_range_action*>> const&, edge::query_action_data&)+119
edge_intellisense_server_impl::update_range(std::shared_ptr<edge::translation_unit> const&, char const*, edge::update_range_options, snapshot::snapshot_session_t const&, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>&, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>&)+524
edge_intellisense_server_impl::handle_update_intellisense(cpp_intellisense::UpdateIntelliSenseRequest const&, cpp_intellisense::UpdateIntelliSenseResponse&, snapshot::snapshot_session_t const&)+521
cpp_intellisense::server_stub::handle_update_intellisense(msvc::deserializer_t&, msvc::serializer_t&)+292
msvc::base_channel_t::dispatch_message(std::vector<unsigned char, std::allocator<unsigned char>> const&, std::vector<unsigned char, std::allocator<unsigned char>>&)+571
msvc::common_channel_t::perform_call(unsigned int, std::vector<unsigned char, std::allocator<unsigned char>> const&)+66

### Configuration and Logs

```shell
cpptools-srv
11/26/2024, 3:59:42 PM
SIGSEGV
a_region_tracker::build_sections()+982
a_tracking_manager::check_edits(a_canonicalized_file_name, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, bool, bool*, bool*, a_tracked_region**, a_region_scope_info*) const+892
edge::scoped_query_manager::check_and_compile(edge::file_position const&, edge::file_position const&, edge::file_position const&, bool, bool, bool)+899
edge::scoped_query_manager::update_fragment(edge::file_position const&, edge::file_position const&, edge::file_position const&, edge::update_fragment_options const&)+51
edge::an_edge_translation_unit_impl::update_range(edge::allocator*, snapshot::snapshot_session_t, edge::file_position, edge::file_position, edge::update_range_options const&, edge::file_position, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>*, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>*, an_array_list<edge::update_range_action*, std::allocator<edge::update_range_action*>> const&, edge::query_action_data&)+1209
edge::translation_unit::update_range(edge::allocator*, snapshot::snapshot_session_t, edge::file_position, edge::file_position, edge::update_range_options const&, edge::file_position, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>*, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>*, an_array_list<edge::update_range_action*, std::allocator<edge::update_range_action*>> const&, edge::query_action_data&)+119
edge_intellisense_server_impl::update_range(std::shared_ptr<edge::translation_unit> const&, char const*, edge::update_range_options, snapshot::snapshot_session_t const&, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>&, msvc::strong_typedef<msvc::offset_traits<msvc::offset_tag_t>>&)+524
edge_intellisense_server_impl::handle_update_intellisense(cpp_intellisense::UpdateIntelliSenseRequest const&, cpp_intellisense::UpdateIntelliSenseResponse&, snapshot::snapshot_session_t const&)+521
cpp_intellisense::server_stub::handle_update_intellisense(msvc::deserializer_t&, msvc::serializer_t&)+292
msvc::base_channel_t::dispatch_message(std::vector<unsigned char, std::allocator<unsigned char>> const&, std::vector<unsigned char, std::allocator<unsigned char>>&)+571
msvc::common_channel_t::perform_call(unsigned int, std::vector<unsigned char, std::allocator<unsigned char>> const&)+66
```

**Comment by sean-mcmanus** [comment]
@hellowxy We're aware of this crash and it's being tracked by https://github.com/microsoft/vscode-cpptools/issues/12956 and https://github.com/microsoft/vscode-cpptools/issues/12666 .

**Comment by bobbrow** [comment]
@sean-mcmanus did we get a repro yet though?

**Comment by sean-mcmanus** [comment]
@bobbrow It sounds like there might be a repro at https://github.com/microsoft/vscode-cpptools/issues/12956 , but I haven't confirmed it yet.

**Comment by bobbrow** [comment]
@sean-mcmanus the stack for that one looked different. I didn't repro that crash with the code provided, but I also didn't follow the steps exactly. I didn't think the build setup should have anything to do with it, but it might in that case.

**Comment by x1ntt** [comment]
> [@sean-mcmanus](https://github.com/sean-mcmanus) the stack for that one looked different. I didn't repro that crash with the code provided, but I also didn't follow the steps exactly. I didn't think the build setup should have anything to do with it, but it might in that case.

Maybe Rockylinux is needed? Check this out https://github.com/microsoft/vscode-cpptools/issues/12956#issuecomment-2505191850
