### ISSUE TITLE
Auto-detect clang-format path

### ISSUE THREAD

**Issue by dapirian** [microsoft/vscode-cpptools#1300]
My clang-format is in my path, just use it. Override with an explicit clang-format path, but otherwise this should work out of the box without me giving an explicit path of where clang-format is.

**Comment by sean-mcmanus** [comment]
Our extension installs clang-format 5.0 (local to our extension folder) and uses that out-of-the-box. Is there a reason this isn't sufficient?

**Comment by dapirian** [comment]
Hmmm. Format on save with clang-format didn't work until I gave it an explicit path to clang-format. I figured that was because it didn't know where clang-format was, but apparently that's not the case.

Thanks for the quick response!

**Comment by sean-mcmanus** [comment]
I'm not able to repro any problem with `editor.formatOnSave: true`, so let me know if you have a repro I can try. We had an old `C_Cpp.clang_format_formatOnSave` setting that we removed a few updates ago. Oh, if our main input thread is stuck (typically doing some IntelliSense compilation), then the format would appear to fail. We could probably fix this by moving the formatting processing (and maybe some other stuff) to another thread, but we haven't received that many complaints yet.

**Comment by dapirian** [comment]
Maybe that's what was happening, intellisense compilation. But there's nothing in the UI to tell me that's happening is there?

**Comment by sean-mcmanus** [comment]
I think there should be a red flame in the bottom right.

**Comment by dapirian** [comment]
Right now if I remove my explicit path clang-format works anyway. There might be an issue with it working when first installing the extension without restarting vscode or something, as it definitely didn't previously work.

**Comment by bobbrow** [comment]
This will be addressed with #3569

**Comment by sean-mcmanus** [comment]
The clang-format on the PATH should be used as of https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3 .
