### ISSUE TITLE
"The language server crashed 5 times in the last 3 minutes. It will not be restarted" 

### ISSUE THREAD

**Issue by hjoergens** [microsoft/vscode-cpptools#1302]
This happens as soon as I open ANY file with a CPP extension, even if that file is empty.

CentOS Linux 7

Visual Studio Code Version 1.19.0-insider
Commit 5b0fa2eddbe82df90fb07eea120c9447c93dbd2f

CPPTools version 0.14.3, all other extensions DISABLED

I can reproduce it at any time by opening any CPP file, even an empty one, as long as the extension is "cpp"

There are no log messages in the output window.

If I can help in any way, please let me know!

Kind regards

Harald Joergens

**Comment by dtrudg** [comment]
I also have this issue on RedHat Enterprise Linux 7.4 with:

Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9

CPPTools 0.14.3

Same symptom. The language server crash is immediate on opening any .c file. There are no log messages in VSCode, or on the terminal code was started from.

**Comment by dtrudg** [comment]
Ahh - maybe this is expected... I just noted the extension homepage states it needs glibc 2.18 for intellisense, and CentOS7 / RHEL7 are at 2.17

**Comment by dtrudg** [comment]
@hjoergens  - I just saw issue #19 - try the insider build at the bottom of that. Working for me without the crash on RHEL7.

**Comment by bobbrow** [comment]
Thanks for linking to #19 @dctrud.  This is a duplicate of that issue.  Try out the insider build for now and then migrate to the mainline build when we release an update in a few weeks.

**Comment by zh-ngk-i** [comment]
When I open the java suffix file  vs 
prompt   `The Java Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`   
 issue no 1.22.2   64-bit windows 10

**Comment by sean-mcmanus** [comment]
@zh-ngk-i Our extension doesn't implement a Java Language Server and doesn't process java files. Can you open an issue with whatever java extension you're using?
