### ISSUE TITLE
Wrong color on #endif containing code with inline comment

### ISSUE THREAD

**Issue by xamix** [microsoft/vscode-cpptools#13041]
### Environment

- OS and Version: W10
- VS Code Version: 1.95.3
- C/C++ Extension Version: v1.23.2 (pre-release)

### Bug Summary and Steps to Reproduce

Bug Summary:

If you use the following C code (I compile with MSVC 2022 compiler Kit and CMake tools):

```
#ifdef USE_DEV_BOARD
    #define TEST_ENABLED  1
#else
    #define TEST_ENABLED  0  // FIXME
#endif
```

Then the `#endif` color comes RED:

![Image](https://github.com/user-attachments/assets/6d3e153e-a1d1-4b30-a957-0874022cc2a2)

But the code seem to compile correctly, and if you remove the comment then the color seem good (modulo the issue https://github.com/microsoft/vscode-cpptools/issues/13029 which seem to be also present with `#define`):

![Image](https://github.com/user-attachments/assets/cf44ca66-6cd9-4062-96ce-33a7afb6484d)

### Configuration and Logs

```shell
None
```

**Comment by sean-mcmanus** [comment]
@xamix Our extension doesn't implement that colorization (repros with the C/C++ extension disabled). It's from VS Code, which in turn gets it from https://github.com/jeff-hykin/better-cpp-syntax/issues . You should file an issue there if one doesn't already exist (I saw some existing issues which might cover this case, but I'm not sure).
