### ISSUE TITLE
Wrong translation in Format Settings - Simplified Chinese

### ISSUE THREAD

**Issue by WinfredHuang** [microsoft/vscode-cpptools#13048]
In this item: 
C_Cpp > Vc Format > Space: Around Binary Operator
the translation is wrong. 
The original translation is: "二进制运算符周围的空格。"
Correct translation is: "二元运算符周围的空格。"
The word "binary" here means the operator has two operands. "Unary" and "ternary" operators means the operator has one/three operands, hence "一元", "三元". “进制” is used for numeric systems, like decimal, hexadecimal, etc.

**Comment by sean-mcmanus** [comment]
@WinfredHuang Your fix is released with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.23.3 (pre-release).
