### ISSUE TITLE
Feature Request: option to use .clang_complete like settings

### ISSUE THREAD

**Issue by rene-aguirre** [microsoft/vscode-cpptools#1304]
Started by a vim plug-in that used clang for code completion, multiple "completer" engines based on Clang are using a `.clang_complete` file that just holds extra include and defines for a given project.

Example, content:

```
-DDEBUG
-include "../includes"
-I/home/me/includes
```

I think the idea is pretty much generic to any compiler, not only to clang, and `vscode-cpptools` could include a `CompleteOptionsFile` like settings to point to any `.complete` file that at least support common compilers define and include CLI options.

This is a really convenient way to auto-generate project settings from a make file just by dumping the extra compiler definitions and include paths to a file.

By the way, this is supported already by 3rd party extensions like `vscode_clang` but it would be great to have this as an easier completion setup for `vscode-cpptools`.

**Comment by AndiDog** [comment]
This would also allow adding include paths to IntelliSense which are relative to the current Git repo. That is important since usually workspace root(s) != Git repos.
