### ISSUE TITLE
Code format doesn't work: left brace can't goto the same line.

### ISSUE THREAD

**Issue by victorjee** [microsoft/vscode-cpptools#13042]
### Environment

- VS Code Version: 1.95.3 (Universal)
- OS Version: macOS 13.7.1 
- C/C++ Extension Version: v1.22.11

### Bug Summary and Steps to Reproduce

PLS SEE THE SCREENSHOT

![Image](https://github.com/user-attachments/assets/adbb08bc-2bc3-4ba1-ba52-8d730a542c6a)

### Configuration and Logs

```shell
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "${config:idf.toolsPath}/tools/xtensa-esp-elf/esp-13.2.0_20240530/xtensa-esp-elf/bin/xtensa-esp32-elf-gcc",
            "compileCommands": "${config:idf.buildPath}/compile_commands.json",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            }
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
@victorjee Do you have `"C_Cpp.formatting": "vcFormat",` set? If that doesn't fix it, can you set C_Cpp.loggingLevel to "Debug" and then look at the logging in the C/C++ window after you do a formatting to see if there's any error indication or if it's using clangFormat, etc.

**Comment by victorjee** [comment]
> [@victorjee](https://github.com/victorjee) Do you have `"C_Cpp.formatting": "vcFormat",` set? I don't repro the issue with that set. If that doesn't fix it, can you set C_Cpp.loggingLevel to "Debug" and then look at the logging in the C/C++ window after you do a formatting to see if there's any error indication or if it's using clangFormat, etc.

Thank you Sir! I have fixed the issue with your suggests to add **"C_Cpp.formatting": "vcFormat"** instead of  **"editor.defaultFormatter": "ms-vscode.cpptools"**

    /*"[c]": {
        "editor.defaultFormatter": "ms-vscode.cpptools"
    },*/
    "C_Cpp.formatting": "vcFormat",

But i don't know why the default setting is **editor.defaultFormatter** not the **C_Cpp.formatting**. 
OR means that I need config this **manually** when I create an new project.

**Comment by sean-mcmanus** [comment]
@victorjee The default formatter with "ms-vscode.cpptools" is "clangFormat" (unless a special case is detected such as an .editorConfig file). So you need `"editor.defaultFormatter": "ms-vscode.cpptools"` and `"C_Cpp.formatting": "vcFormat",`. You can set the settings at the User settings level so that they don't need to be set for every workspace.
