### ISSUE TITLE
C++ extension not working 

### ISSUE THREAD

**Issue by PantelisKyriakidis** [microsoft/vscode-cpptools#1305]
Hello, 
I am on windows 10 and I use VScode 1.18.1
and I downloaded the C/C++ extension version is: 0.14.3 .
But when I try to test it with a simple .cpp file it doesn't work at all . 
I built a properties.json file and it uses automatically my visual studio paths : 
![image](https://user-images.githubusercontent.com/18362812/33519230-9e9f8778-d7ab-11e7-87d8-aa315c6488a7.png)
Are these settings right? Because nothing seems to work.
Thanks in advance for your help

**Comment by bobbrow** [comment]
Did you remove the "Windows Kits" paths from your `"includePath"` or did the extension fail to populate that?  You won't get very good IntelliSense on Windows without setting the proper path to the Windows SDK that you're using.  (Do you have Visual Studio installed?)

**Comment by PantelisKyriakidis** [comment]
It looks like it failed to populate that. I tried to copy and pastingthem in the include path but nothing happens. 
And yes visual studio is installed

**Comment by sean-mcmanus** [comment]
The behavior you're describing in which the includePath isn't matching the browse.path should be impossible, because we set the includePath and browse.path identically. It's possible some other extension could be modifying the file. However, adding the new paths should cause them to be picked up by the IntelliSense engine. Can you provide more info? From your screenshot, you're missing the "ucrt" path. You might also want to try using a Windows 10 SDK instead of the 8.1. one.

**Comment by PantelisKyriakidis** [comment]
I don't know if it's right to have both 8.1 and 10 in the same properties file but i added ucrt :
![image](https://user-images.githubusercontent.com/18362812/33706385-aaa5d7ae-db3c-11e7-82af-9284d4930c4e.png)
Again, nothing seems to work.  
About more info, I dont know what to tell you, I use visual studio 2015. Tell me what other info you need and I will give it.

**Comment by bobbrow** [comment]
It's not a good idea to mix and match Windows SDKs.  The Windows 8.1 SDK does not have a "ucrt" path and the 10.0.10150 Windows SDK path is not really valid anyway, so go ahead and remove that line from both properties.

Can you share a screenshot of your test.cpp file and show or tell us what exactly is not working?

**Comment by PantelisKyriakidis** [comment]
Ok I revoved the line .
![image](https://user-images.githubusercontent.com/18362812/33742749-72389f84-dbb2-11e7-9cc4-1d5039acb1ec.png)
Now the test.cpp is a simple hello world i created just to check intellisense. But i wrote it and it didnt give me some completion. (I also checked it with one of my projects at visual studio. again nothing).

I just found out that the problem is not in vscode. In visual studio (C++) I couldn't get auto completion either .. I created a C# project and it is ok , so the problem is in C++.

**Comment by bobbrow** [comment]
What is the value of `"editor.quickSuggestions"` in your settings.json file?  I don't see any of our auto-complete trigger characters in this file `.`, `->`, `::`.

**Comment by PantelisKyriakidis** [comment]
"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },

and

![image](https://user-images.githubusercontent.com/18362812/33770021-de229d94-dc34-11e7-9b4e-69bef5821dc0.png)

**Comment by bobbrow** [comment]
Can you set `"C_Cpp.loggingLevel": "Information"` in your settings.json and then restart VS Code?  The extension should print out some information in the Output Window in the "C/C++" channel.  Please share that with us and we'll see if we can track down what is going on.

**Comment by sean-mcmanus** [comment]
There is no navigation section in the task bar, which indicates that the browse database failed to get created. If your user name has a non-ASCII character, then it could be bug https://github.com/Microsoft/vscode-cpptools/issues/1319, which has a workaround of setting the databaseFilename.

**Comment by PantelisKyriakidis** [comment]
@bobbrow thank you very much for your time and help.
@sean-mcmanus Yes my username is non-ASCII . It always falls back to that, doesn't it ? :P Thank you very much i read the bug #1319  
and I changed the value of databaseFilename to "${workspaceRoot}/.vscode/.browse.vc.db". Finally it works!!
But do I have to do this in every project? Maybe I should change the location of .vscode?
And what actually is that path "${workspaceRoot}/.vscode/.browse.vc.db" ? In my .vscode folder there is only a folder : extensions

**Comment by sean-mcmanus** [comment]
Yeah, you would have to set the databaseFilename for every project, but we'll be releasing a fix on Monday, and 2nd workaround that would work for all workspaces is to launch code.exe with the flag `--user-data-dir` with a folder that doesn't have a non-ASCII character in it, which will change the default workspace storage location. The ${workspaceRoot} path resolves to your TEST folder path (it's okay if it has non-ASCII characters in it).

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
