### ISSUE TITLE
The language server crashed 5 times in the last 3 minutes. It will not be restarted.

### ISSUE THREAD

**Issue by rdev1983** [microsoft/vscode-cpptools#1306]
*** Operating System and version**
`uname -a`
Linux nuc 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

`cat /etc/redhat-release`
CentOS Linux release 7.4.1708 (Core)'

 *** VS Code version and if you are using the Insiders build**
tried with
 code-1.18.1-1510857496.el7.x86_64.rpm
and code-insiders-1.19.0-1512109072.el7.x86_64.rpm
and code-stable-code_1.18.1-1510857349_amd64.tar.gz

tried 32 bit version of vscode also. same result

*** C/C++ extension version**

0.14.3

*** step-by-step instructions to reproduce the issue**
1> Install vscode or insider build on CentOS 7 or tar
2> Create a dir (foo), create a file bar.cpp (empty) in foo
3> Open foo directory in vscode
4> Click on bar.cpp in EXPLORER
5> vscode will ask to install c++ plugin, click on install and reload
6> Leave vscode for couple of minutes, it will display above mentioned crash error

**Comment by s-martin** [comment]
Will be fixed in 0.14.4, see #19

**Comment by bobbrow** [comment]
Thanks, @s-martin.  @rdev1983 we have a link to a preview package that you can download and install in issue #19.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
