### ISSUE TITLE
intellisense incompatible declaration error should link to source

### ISSUE THREAD

**Issue by draeger-charles-wilson** [microsoft/vscode-cpptools#1307]
VSCode 1.18.1
C/C++ 0.14.3
OS Windows 7

When Intellisense detects an incompatible declaration it reports the source of the conflict.

![image](https://user-images.githubusercontent.com/33490168/33553842-642e3c92-d8c8-11e7-8575-45a9dbe4cdbf.png)

It would be more helpful if it linked to the source.

**Comment by draeger-charles-wilson** [comment]
simple sample (bad_forward_dec.c)

```
int foo(void)
{
    bar();

    return 1;
}

void bar(void)
{
}

int main(int argc, char * argv[])
{
    return foo();
}

```

**Comment by bobbrow** [comment]
Hmm... that code sample results in a different error squiggle for me.

![image](https://user-images.githubusercontent.com/12818240/33572222-2ae8d27a-d8e7-11e7-948d-a94fd517b929.png)

And the tooltip for the original issue you reported seems to be working as expected:

![image](https://user-images.githubusercontent.com/12818240/33572303-63381f64-d8e7-11e7-830d-4c43e3198cd2.png)

Perhaps I am misunderstanding your request.  Can you clarify what you think would be more helpful?  I would have thought that listing the line of the mismatched declaration would be what you want (so that you could actually go find it).

**Comment by draeger-charles-wilson** [comment]
my bad main's bar() call should be foo() and foo() should have returned a value. [updated code]

**Comment by bobbrow** [comment]
Your updated code produces no error squiggles.

**Comment by draeger-charles-wilson** [comment]
![image](https://user-images.githubusercontent.com/33490168/33574055-d310499c-d905-11e7-89cc-1bf5141f5485.png)

![image](https://user-images.githubusercontent.com/33490168/33574126-0ae74de8-d906-11e7-9820-ea5301dc7da3.png)

**Comment by bobbrow** [comment]
Do you have any other language extensions installed? Do you have any problem matchers set for your build task(s)?  Our extension doesn't output any warnings, and I still don't see any errors reported when I paste your code into the editor.

**Comment by draeger-charles-wilson** [comment]
No other extensions.

The code is can be compiled using a gcc 3.3 variant. There is a problem checker in conjunction with the build task. When compiled this generate:

![image](https://user-images.githubusercontent.com/33490168/33606742-9357cb0e-d98c-11e7-8789-6d14c3911ec7.png)
![image](https://user-images.githubusercontent.com/33490168/33606751-9e739d6a-d98c-11e7-9eec-5497088c2655.png)

and apply the error parser:

```
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation":"absolute",
                "pattern": [
                    {
                        "regexp": "^\"(.*)\",\\s+line\\s+(\\d+):\\s+(Warning|Error):\\s+#(\\d+).*:\\s+(.*)",
                        "file": 1,
                        "line": 2,
                        "severity": 3,
                        "code": 4,
                        "message": 5,
                        "loop":true
                    }
                ]
            },

```
I did not anticipate that Intellisense was folding this data back. That gives the behavior a better context.

Is there a 'reference' field I can parse out of the issue that Intellisense can pick up on?

**Comment by bobbrow** [comment]
I suspect you should be able to add another "pattern" to the list that parses out the "declared at line (\\d+)"  and adds a problem for that line instead of the line from the "line\\s+(\\d+)" part of the message.

**Comment by draeger-charles-wilson** [comment]
Interesting. But that won't be a reference from the site of the issue. I'll see if I can build a second regex.

**Comment by bobbrow** [comment]
I had hoped that this would result in two problems generated for that line (one at the definition and one at the error) but the [documentation for problem matchers](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher) doesn't explicitly say that this will work though.  I'm not sure whether VS Code will pass the full line to both regexes so you might have to tell the first one not to parse the "(declared at line ...)" part.

**Comment by draeger-charles-wilson** [comment]
Yeah. It hits on one. This still doesn't solve the problem that you have an issue in one location referring to another (which may be in another file). It would be helpful to have a refers-to-file, refers-to-line, refers-to-start-position and refers-to-end-position that can also be captured. I don't imagine that this is the only tool chain capable of generating referential errors.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".

In this particular case, the functionality requested seems to be within the VSCode team's domain.  Our extension is not able to implement this behavior.
