### ISSUE TITLE
How can I configure terminal to show build errors in color?

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#1308]
In Visual Studio Code 1.18.1, C++ extension 0.14.3, I have a build task:

    {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "Build LedaAP",
                "type": "shell",
                "command": "c:/WindRiver/workbench-4/wrtool.bat -data c:/WindRiver/workspace_BR_SW_BFHW prj build LedaAP",
                "problemMatcher": [
                    "$gcc"
                ],
                "group": {
                    "kind": "build",
                    "isDefault": true
                },
                "presentation": {
                    "reveal": "always",
                    "panel": "new"
                }
            }
    }

The build output is in gcc style. Presently, all text is shown in black. How can I configure the terminal to show errors in red (or other highlight)?

**Comment by sean-mcmanus** [comment]
It seems like this might not be supported by VS Code yet? I found this discussion here: https://github.com/Microsoft/vscode/issues/243 .

**Comment by daldr-ntml** [comment]
Thanks for your reply. Yes, it seems to be unsupported. I wasn't sure if my question was relevant to the core editor or to the C++ extension.
