### ISSUE TITLE
Break POints doesn't trigger - 

### ISSUE THREAD

**Issue by kchsrikanth** [microsoft/vscode-cpptools#1309]
I tried using below launch.json and set breakpoints after successful build. The breakpoints, doesn't get triggered.

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/app ",
            "args": ["example.json"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb"
        }
    ]
}

OS: Mac OS X High Sierra
VS Code: Version 1.18.1 (1.18.1)
C/C++ Extension: Version 0.14.3: November 28, 2017

The console displays the log accurately with correct log ( written in main method ), which tells that the code is executed. However the breakpoints ( set in main method ) are not triggered. 

Any help would be appreciated.

Thanks,
Sri.

**Comment by pieandcakes** [comment]
@kchsrikanth Did you compile with `-g` to enable symbols?

**Comment by kchsrikanth** [comment]
Hi @pieandcakes 
Thanks for quick reply. I have used make command with -g option and it says its not an option. Any suggestions ?

Thanks,
Sri.

**Comment by pieandcakes** [comment]
@kchsrikanth You have to compile with Debug symbols or else the debugger (lldb) doesn't know how to debug your app. The `-g` flag would be one you pass to clang or g++ depending on which one you are using. You may want to do an internet search on how to setup makefiles to support debugging. I'm not experienced with them.

**Comment by kchsrikanth** [comment]
I tried various options in make file with no success. I tried various examples for windows but couldn't find much for mac. Any suggestions ?

Thanks,
Sri.

**Comment by kchsrikanth** [comment]
Here is my make file that I am trying to get debugger to trigger.

TARGET = app
OBJS += main.o
LIBS += -lm

CXX = clang++
CXXFLAGS += -std=c++11 
CXXFLAGS += -MMD -MP
CXXFLAGS += -I./
CXXFLAGS += -Wall -Werror 
LDFLAGS += $(LIBS)

all: CXXFLAGS += -O2
all: $(TARGET)

debug: CXXFLAGS += -ggdb  -D_GLIBCXX_DEBUG # debug flags
debug: $(TARGET)

debug: CXXFLAGS += -DDEBUG -g
debug: CCFLAGS += -DDEBUG -g
debug: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CXX) $(CXXFLAGS) -c -o $@ $<

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

DEPS = $(OBJS:%.o=%.d)
-include $(DEPS)

**Comment by pieandcakes** [comment]
@kchsrikanth Does it actually call the "debug" section when you run make? that looks like where it adds the `-g` flag. Look at the logs and see if the actual command that its calling shows it?

**Comment by WardenGnaw** [comment]
Closing issue.

If you are still encountering issues, please reopen another issue with additional information requested.
