### ISSUE TITLE
Regex debug output

### ISSUE THREAD

**Issue by lightgoleft** [microsoft/vscode-cpptools#1310]
Hello, 

I am seeking possibility to regex on debug info(stdout). Currently, using internal console shows no output on output tab. So is this any chance or extension I can use to achieve this? BTW, I called the debugger through vscode-cmake-tools. 

Thanks.

**Comment by pieandcakes** [comment]
@lightgoleft I assume it should open a console window and it won't show inside VS Code. does the output show up there? if not, you can try and use Unix redirection to redirect stdout to somewhere such as a file?

**Comment by lightgoleft** [comment]
@pieandcakes As configured as "externalConsole: true", yes, console window w/ output shows up. But I am seeking the opportunity if the output could redirect to VS Code so I can use some addon to filter the result at runtime. Thanks for the reply

**Comment by pieandcakes** [comment]
>But I am seeking the opportunity if the output could redirect to VS Code so I can use some addon to filter the result at runtime.

So you aren't looking for it to only appear in the VS Code debug console or terminal window, you want to be able to filter the output? #35 is on the backlog to use VS Code's integrated terminal but I don't know how any of the filtering would be implementable by us since once its sent to VS Code, that would be owned by them.

**Comment by lightgoleft** [comment]
Thanks for your reply!

As you said, what I seek is to filter output within integrated terminal. So what I found in these threads is that integrated terminal can neither accept std:in nor std:out. And redirect by adding argument ">log.txt" to debug didn't work as well(I have tried).

**Comment by pieandcakes** [comment]
@lightgoleft The first step would be to get our stuff integrated into the terminal, then you can possibly as VS Code to add filtering into their terminal.

**Comment by lightgoleft** [comment]
Ok. Got you. Thanks for the information. I will follow the thread to see the progress of integration.

**Comment by bobbrow** [comment]
This feature isn't on our roadmap
