### ISSUE TITLE
Navigation behaviour

### ISSUE THREAD

**Issue by sbrw** [microsoft/vscode-cpptools#1311]
- Ubuntu 17.10
- vscode 1.18.1
- C/C++ 0.14.2

1. Open a C-source file containing function prototypes and corresponding function definitions
2. Navigate the file (ALT-N)
3. The dropdown list for navigation contains both prototypes and definitions
- Is there a way to distinguish between the prototypes and definitions in the dropdown list? 
4. Select a definition and click/hit enter
5. Cursor jumps to the definition at a scroll position at the bottom of the screen
- Is it possible to put the scroll position at top so the function body is displayed by default, or at least center it? I guess the most obvious reason to navigate to a function is to see its contents, and not preceeding code?

**Comment by sean-mcmanus** [comment]
The existence of function prototypes in the navigation list is a bug -- the intention was to only show scopes (classes, namespaces, function definitions, etc.). The definition might be the 2nd one listed, but I'm not sure if that's always the case.

We have a fix for the 2nd issue. The navigation list currently uses the "Default" of scrolling as little as possible, but we'll switch to the InCenter option. The AtTop option isn't good when you want to see the comments before a scope.

**Comment by sean-mcmanus** [comment]
The 1st issue has been fixed as well for our next update -- we add the text "declaration: " to the start of declarations. Thanks for reporting these issues.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
