### ISSUE TITLE
Provide the ability to run a script to determine compilation option for a given file

### ISSUE THREAD

**Issue by jyavenard** [microsoft/vscode-cpptools#1315]
Opening a big projects (made of thousands of files) with headers often generated at compile time (and not living in the source tree) will see thousands of errors showing in problems due intellisync not finding the headers.

One can manually modify the includePath entry in the configuration, but that would take an extremely long time to do, and should any headers be changed, or the build system changed the object directory (where the generated headers are found). An ongoing and maintenance nightmare

YouCompleteMe extension in VIM, has the ability to run an external script that will retrieve the compilation option for the file that is about to be opened.
This would include all the -Idirectory directives, as well as compilation switches affection warnings and errors (like /D on Windows)

From this, intellisync could intelligently (pun intended) determine where to find the headers, without manual settings.

Feel free to close this bug if there's already a mechanism in place to achieve a similar outcome

**Comment by bobbrow** [comment]
Is your build system capable of producing a [compile_commands.json](http://clang.llvm.org/docs/JSONCompilationDatabase.html) file?  We have support for this in the extension today.

**Comment by jyavenard** [comment]
it doesn't for now... but it could.

We have a generator for Visual Studio project files.

Edit: ohhhhh, we do :)
./mach build-backend -b CompileDB

**Comment by bobbrow** [comment]
Great!  Just set the path to the compile commands file as the value of the "compileCommands" property in your c_cpp_properties.json file and we should pick it up.

**Comment by jyavenard** [comment]
the file contains path with the directory set to the object directory (outside of the source tree), like so:

[
{
"directory": "/Users/jyavenard/Work/Mozilla/obj-ff-dbg/mfbt", 
"command": "/usr/local/bin/icecc /usr/local/opt/llvm/bin/clang --target=x86_64-apple-darwin16.0.0 -mmacosx-version-min=10.11 -std=gnu99 -o /dev/null -c -fvisibility=hidden -fvisibility-inlines-hidden -DDEBUG=1 -DIMPL_MFBT -DLZ4LIB_VISIBILITY= -I/Users/jyavenard/Work/Mozilla/mozilla-central/mfbt -I/Users/jyavenard/Work/Mozilla/obj-ff-dbg/mfbt -I/Users/jyavenard/Work/Mozilla/mozilla-central/mfbt/double-conversion -I/Users/jyavenard/Work/Mozilla/obj-ff-dbg/dist/include -I/Users/jyavenard/Work/Mozilla/obj-ff-dbg/dist/include/nspr -I/Users/jyavenard/Work/Mozilla/obj-ff-dbg/dist/include/nss -fPIC -include /Users/jyavenard/Work/Mozilla/obj-ff-dbg/mozilla-config.h -DMOZILLA_CLIENT -Qunused-arguments -Qunused-arguments -Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wunreachable-code-return -Wclass-varargs -Wloop-analysis -Wstring-conversion -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wformat -Wformat-security -Wno-gnu-zero-variadic-macro-arguments -fno-strict-aliasing -fno-math-errno -pthread -pipe -g -fno-omit-frame-pointer /Users/jyavenard/Work/Mozilla/mozilla-central/mfbt/lz4.c", 
"file": "/Users/jyavenard/Work/Mozilla/mozilla-central/mfbt/lz4.c"
}, 

could that cause problem?

**Comment by jyavenard** [comment]
hmmmm...

i get thousands of:
cannot open source file "map" (dependency of "MediaPipeline.h")
cannot open source file "cmath" (dependency of "AudioSegment.h")
cannot open source file "queue" (dependency of "AutoTaskQueue.h")

and so forth...

I did add in the path to the c++ standard lib include directory:

```
{
    "configurations": [
        {
            "name": "Mac",
            "compileCommands": "/Users/jyavenard/Work/Mozilla/obj-ff-dbg/compile_commands.json",
            "includePath": [
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/usr/local/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/usr/include",
                "/usr/include/machine",
                "/usr/local/Cellar//llvm/5.0.0/lib/clang/5.0.0/include",
                "/usr/local/Cellar/llvm/5.0.0/include/c++/v1/",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                    "/usr/local/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                    "/usr/include",
                    "/usr/include/machine",
                    "/usr/local/Cellar//llvm/5.0.0/lib/clang/5.0.0/include",
                    "/usr/local/Cellar/llvm/5.0.0/include/c++/v1/",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },

```

**Comment by bobbrow** [comment]
There is a known bug with "command" fields that don't start with the compiler name. #1251 ☹️

**Comment by jyavenard** [comment]
Ok, I'll create a cc script for now that runs /usr/local/bin/icecc /usr/local/opt/llvm/bin/clang instead...

**Comment by bobbrow** [comment]
We recently added a "compilerPath" property to **c_cpp_properties.json** that should work around #1251.

**Comment by bobbrow** [comment]
Closing this older issue.  The `compilerPath` property should address the problem.
