### ISSUE TITLE
Support angle brackets in launch.json arguments

### ISSUE THREAD

**Issue by donfiguerres** [microsoft/vscode-cpptools#1317]
Some of the cmd tools I maintain support angle brackets as symbols for 'greater than' and 'less than' filters. These can be escaped in the cmd using ^ but I can't find a way to use the angle brackets in vscode.

VSCode Version: 1.18.1
cpptools version: 0.14.3
OS Version: Windows Server 2012 R2
Steps to Reproduce:

1. Add an angle bracket argument.

![image](https://user-images.githubusercontent.com/12525903/33693408-b40323d8-db2d-11e7-95ac-1db66e482fc6.png)

2. Check if the the angle bracket is included in the arguments passed to the program.

![image](https://user-images.githubusercontent.com/12525903/33693421-d2d28b1e-db2d-11e7-97d5-9135ad3039c7.png)

**Comment by sean-mcmanus** [comment]
@pieandcakes This isn't something the C++ debugger extension could be causing, right? The VS Code issue got auto-closed by a bot: https://github.com/Microsoft/vscode/issues/39748 .

**Comment by pieandcakes** [comment]
@donfiguerres I tried it out. We convert `<` to `&lt;` and pass it to gdb which gets reconverted to `<` and gdb doesn't like it. 

My fix was for `"YEAR<=1995"` to be quoted and it becomes `"\"YEAR<=1995\""` which works. Can you give that a try and see if that will work for you?

**Comment by pieandcakes** [comment]
oh. I tried it with Linux. let me see if I can figure it out for Windows.

**Comment by pieandcakes** [comment]
@donfiguerres theres a bug here with how we process the arguments. I think the fix would be to allow the `^` escape method but I don't have a fix yet as the code path includes some special casing.

**Comment by donfiguerres** [comment]
Hi @pieandcakes, thanks for confirming that it's a bug. Happy new year by the way 😁

**Comment by WardenGnaw** [comment]
This should be resolved in v1.1.0.
