### ISSUE TITLE
Symbols and scope

### ISSUE THREAD

**Issue by sbrw** [microsoft/vscode-cpptools#1318]
- Ubuntu 17.10
- vscode 1.18.1
- C/C++ 0.14.3

1. Create a file foo.c in the workspace
2. Open foo.c and add the line "static int foo_var;" and save
3. Create a file bar.c in the workspace
4. Start typing "foo" and name completion will suggest the private static variable foo_var in foo.c
![image](https://user-images.githubusercontent.com/33813608/33712800-01e687aa-db49-11e7-9c06-0d82f94d8815.png)

For a big project it is very disturbing to get suggestions on all available variables, even if they are in scope or not. Name completion is not much of help if e.g you are unsure of the name and need to scroll through them.

- Is this the intention?
- Can scope be taken into consideration? Either by removing symbols outside the scope, or placing the ones in scope first and marking them accordingly?
- To me scope would be symbols defined in the file I'm editing, or symbols declared in any included files?

Thanks!

**Comment by bobbrow** [comment]
Thank you for the feedback.  We only have semantic IntelliSense turned on for `.`, `->`, and `::` operators right now.  Quick suggestions (e.g. global autocomplete) is not turned on yet, so you will see all results from all files that we've parsed.  We're tracking the behavior you are asking for with issue #13.
