### ISSUE TITLE
Intellisense doesn't work with ASCII username on windows e.g.: Zalán

### ISSUE THREAD

**Issue by JacksonFurrier** [microsoft/vscode-cpptools#1319]
* Window 10 64 Pro 10.0.16299 build 16299
* VS Code 1.18.1
* CMake, CmakeTools, CmakeTools helper, One Dark Pro, Native Debug, Shader languages support for VS Code. Issue does persist after disabling/deleting them
* Create a windows 10 username with "Kovács Béla" name, try "Go to definition" functionality. Intellisense loops and gets fired off, gives no results.
* Log messages attached.
[vscde_errors.txt](https://github.com/Microsoft/vscode-cpptools/files/1539445/vscde_errors.txt)

**Comment by sean-mcmanus** [comment]
The errors are with the vector-of-bool.cmake-tools extension: https://github.com/vector-of-bool/vscode-cmake-tools/issues . Are you able to repro a problem with that extension disabled?

**Comment by sean-mcmanus** [comment]
I was able to repro the bug with just the cpptools extension. The other extension might have some different issue.

**Comment by sean-mcmanus** [comment]
In my repro, it's failing to create the browse database and entering an infinite loop as it tries to open non-existent files. A workaround should be to set the `databaseFilename` in c_cpp_properties.json to something like `"${workspaceRoot}/.vscode/.browse.vc.db"` (and then doing a Reload Window).

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. Our next update should have the fix (for cpptools, not cmake-tools).

**Comment by JacksonFurrier** [comment]
Excuse me for not responding my timezone is GMT+2. 
Great news, thank you!

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
