### ISSUE TITLE
IntelliSense inside comments

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-cpptools#132]
ms-vscode.cpptools-0.8.1
- have the code below
- add a line or block comment
- 🐛  I don't expect to see `main` or `addition` to show there

```
// my first program in C++

int addition (int a, int b)
{
  int r;
  r=a+b;
  return r;
}

int main ()
{
  int z;
  z = addition (5,3);
}

/*
<ctrl+space> here
*/
```

**Comment by jrieken** [comment]
![screen shot 2016-08-05 at 16 07 08](https://cloud.githubusercontent.com/assets/1794099/17439119/b8d2c68a-5b26-11e6-9476-5566a3c57d1b.png)

**Comment by greazer** [comment]
Yep, we are aware of this problem and working on a solution. Not sure if it'll make the August release, but we're attempting it.

**Comment by PattyDePuh** [comment]
Same for me with another example:
Trying to finish an comment with a dot activates IntelliSense.
`// I'm an example.`
Pushing 'Enter' - with active IntelliSense unnoticed - leaves the first entry from it at the end of the comment.
In this case:
`// I'm an example.__arr`

-> VC Version 1.7.1

**Comment by aamcampbell** [comment]
This is also a problem when typing in string literals. 

I wouldn't mind allowing intellisense in comments and string literals when the user presses CTRL+space or otherwise explicitly invokes intellisense, but it definitely gets in the way if it comes up and "autocorrects" me on <enter> or <tab>while I'm trying to type human-readable text.

**Comment by sean-mcmanus** [comment]
Yes, we expect to have a fix for the autocomplete in strings/comments in our next update.

**Comment by bobbrow** [comment]
This has been fixed.  Please reopen if you continue to see this issue.
