### ISSUE TITLE
C/C++ extension occupys about 30% CPU

### ISSUE THREAD

**Issue by shelfofclub** [microsoft/vscode-cpptools#1322]
OS:Windows 10(1607) OS version 14393.1770
VS Code 1.18.1 stable
C/C++ extension version 0.14.3
When I open a .c or .cpp file, the C/C++extension begins to work and I find that it occupys around 30% CPU in Task Manager. In the past, it worked with no problem, but recently it had this problem. If I don't open a .c or.cpp file when starting VS Code, C/C++ extension will not be started and all things are normal

settings.json:
// The full path of the clang-format executable.
  "C_Cpp.clang_format_path": null,

  // Coding style, currently supports: Visual Studio, LLVM, Google, Chromium, Mozilla, WebKit. Use "file" to load the style from a .clang-format file in the current or parent directory. Use "{key: value, ...}" to set specific parameters, e.g.: "{ BasedOnStyle: LLVM, IndentWidth: 8 }"
  "C_Cpp.clang_format_style": "file",

  // Name of the predefined style used as a fallback in case clang-format is invoked with style "file" but the .clang-format file is not found. Possible values are Visual Studio, LLVM, Google, Chromium, Mozilla, WebKit, none, or use "{key: value, ...}" to set specific parameters, e.g.: "{ BasedOnStyle: LLVM, IndentWidth: 8 }"
  "C_Cpp.clang_format_fallbackStyle": "Visual Studio",

  // If set, overrides the include sorting behavior determined by the SortIncludes parameter.
  "C_Cpp.clang_format_sortIncludes": null,

  // Controls the IntelliSense provider. "Tag Parser" provides "fuzzy" results that are not context-aware. "Default" provides context-aware results and is in preview mode - member list, hover tooltips, and error squiggles are currently implemented. Features not yet implemented in the new default engine will use the tag parser engine instead.
  "C_Cpp.intelliSenseEngine": "Default",

  // Controls whether the IntelliSense engine will automatically switch to the Tag Parser for translation units containing #include errors.
  "C_Cpp.intelliSenseEngineFallback": "Enabled",

  // Controls the auto-completion provider. "Default" uses the active IntelliSense engine. "Disabled" uses the word-based completion provided by Visual Studio Code.
  "C_Cpp.autocomplete": "Default",

  // Controls whether suspected compile errors detected by the IntelliSense engine will be reported back to the editor. Warnings about #includes that could not be located will always be reported to the editor. This setting is ignored by the Tag Parser engine.
  "C_Cpp.errorSquiggles": "Enabled",

  // "Default" enables code formatting. "Disabled" disables code formatting.
  "C_Cpp.formatting": "Default",

  // Maximum character length of the scope/navigation UI in the status bar. The UI may not appear if this value is too large.
  "C_Cpp.navigation.length": 60,

  // The verbosity of logging in the Output Panel. The order of levels from least verbose to most verbose is: None < Error < Warning < Information.
  "C_Cpp.loggingLevel": "Error",

c_cpp_properties.json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/mingw32",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/backward",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include",
                "C:/MinGW/include",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include-fixed"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "__GNUC__=6",
                "__cdecl=__attribute__((__cdecl__))"
            ],
            "browse": {
                "path": [
                    "C:/MinGW/lib/gcc/mingw32/6.3.0/include",
                    "C:/MinGW/lib/gcc/mingw32/6.3.0/include-fixed",
                    "C:/MinGW/include/*"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}

launch.json
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "stopAtEntry": false,
            "targetArchitecture": "x86",
            "cwd": "${fileDirname}", 
            "externalConsole": true,
            "preLaunchTask": "g++",
            "linux": {
               "MIMode": "gdb",
               "miDebuggerPath": "/usr/bin/gdb"
            },
            "osx": {
               "MIMode": "lldb"
            },
            "windows": {
               "MIMode": "gdb",
               "miDebuggerPath": "C:\\MinGw\\bin\\gdb.exe"
            }
         }
    ]
}

log messages present in the Output window:
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode

emmmm......Maybe I don't explain clearly in English, so I show some details in Chinese.
之前我一直使用VS Code编写C语言程序，并且除了IntelliSense只会提示当前文件内的一些变量名外没有其他问题，使用起来很好，但大概11月份自动更新C/C++插件后就发现CPU占用高，卸载VS Code后并删除用户文件夹里的相关插件文件与配置文件后，重新安装VS Code和C/C++插件（没有安装其他插件），刚开始没问题，在我配置launch.json、tasks.json等文件时又开始占用约30%的CPU。

**Comment by bobbrow** [comment]
Based on the log, this looks like it might be #1319 which will be fixed in our update next week.

**Comment by shelfofclub** [comment]
My username is in Chinese.I know this may cause some problems, but I can't change my username now. \~_\~

**Comment by bobbrow** [comment]
You don't have to change your username.  You can change the `"databaseFilename"` in your c_cpp_properties.json to an ASCII path and it should work.

**Comment by shelfofclub** [comment]
Oh, yeah! It works. Thank you!

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.

**Comment by hk2281** [comment]
why the extension of intellisense for vscode, does not highlight possible compilation errors

**Comment by shelfofclub** [comment]
> why the extension of intellisense for vscode, does not highlight possible compilation errors

???

**Comment by sean-mcmanus** [comment]
@hk2281 Could you open a new issue with more repro details? Is your intelliSenseEngine set to "Default" and your errorSquiggles setting set to "Enabled" or "EnabledIfIncludesResolve" (and includes are resolved).
