### ISSUE TITLE
"file not found" after "Format Document"

### ISSUE THREAD

**Issue by tzbo** [microsoft/vscode-cpptools#1325]
I format a file, then report "file not found". It's ok before format the document.

<img width="434" alt="screen shot 2017-12-09 at 08 33 17" src="https://user-images.githubusercontent.com/19189826/33790532-ea65ff24-dcbb-11e7-9030-0245f7a2dee5.png">

**Comment by sean-mcmanus** [comment]
The "file not found" tooltip message is from the C/C++ Clang Command Adapter extension and not the C++ extension (see also #1352 ).
