### ISSUE TITLE
consoleSecefication support

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1327]
The debug console output is awful. 

![screen shot 2017-12-09 at 11 20 20 am](https://user-images.githubusercontent.com/23425023/33797298-55ee6d1e-dcd3-11e7-9e5b-a0b592493303.png)

It would be awesome if there was a setting in the tasks.json for consol

 just like in python 
![screen shot 2017-12-09 at 11 19 52 am](https://user-images.githubusercontent.com/23425023/33797290-4b4dc9fe-dcd3-11e7-9147-1793b5bd2c1d.png)

**Comment by ZZYSonny** [comment]
+1

**Comment by pieandcakes** [comment]
@YusufTaha we have this already on our backlog. #35 #239
