### ISSUE TITLE
Auto-Completion is not response to the correct variables

### ISSUE THREAD

**Issue by michaelllh** [microsoft/vscode-cpptools#1328]
* Operating System and version  : win7 64bits
    * VS Code version : 1.18.1
    * C/C++ extension version : 0.14.3
    * Other extensions: none
    * step-by-step instructions to reproduce the issue:
like if I have a struct:
>typedef struct 
{
    int a;
    int b;
}test_t;

then I define to test_t variable, and use the Auto-Completion to help me complete the code, it give me more option than variables a and b .

**Comment by sean-mcmanus** [comment]
You must be falling back to the tag parser behavior due to missing include paths. You can view the Problems window to see which include paths are missing, possibly use code actions to automatically add the paths, or you can change the `C_Cpp.intelliSenseEngineFallback` to "Disabled". Are you able to get it to work now?

**Comment by michaelllh** [comment]
When I set C_Cpp.intelliSenseEngineFallback to Disabled，it it terrible！My source file fills with error， ALL enum value turn into error. （contains with red underline）

**Comment by sean-mcmanus** [comment]
It sounds like you need to add the paths to the include files that contain the enum definitions to your `includePath` setting. If you add a parent path to the `browse.path` setting, you can have the database automatically return matches via the code action. You could also set `errorSquiggles` to disabled if you can't get the paths resolved. Umm...but you didn't say what the error message in the Problems pane was, so I'm not sure if it's a different issue.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
