### ISSUE TITLE
g++ not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1329]
Hi I have some issue in order to debbug C++ with visual studio code.
I followed this tutorial : https://code.visualstudio.com/docs/languages/cpp

I'm using Visual Studio Code 2017 on windows 10.

Could  you please help me, it has been at least a week and I still didn't find the issue.

Cheers.
![2](https://user-images.githubusercontent.com/34433678/33818242-a8096844-ddf8-11e7-9704-5b436064b5e6.png)
![1](https://user-images.githubusercontent.com/34433678/33818244-ab388aae-ddf8-11e7-8c1b-0df84fb2714b.png)
![3](https://user-images.githubusercontent.com/34433678/33818248-ad692dc4-ddf8-11e7-9cc0-3278ad7cdff8.png)

---
EDIT: [The most upvoted answer is here](https://github.com/microsoft/vscode-cpptools/issues/1329#issuecomment-381384275), though you should really just need to update your PATH environment variable to include C:\MinGW\bin (or whatever the path to your compiler is) and then restart VS Code.

**Comment by sean-mcmanus** [comment]
You need to install g++/gcc somehow, or install a different compiler, such as cl.exe or clang. I just use "sudo apt-get install g++" on Ubuntu, but I haven't installed g++ that on Windows. I assume the mingw docs would explain how to install the gcc compiler. Are you able to install a C++ compiler?

**Comment by ghost** [comment]
I already installed MinGW as a compiler and I have the files gcc.exe and g++.exe.
But I don't know why VS code couldn't find it and gives me this error.

**Comment by sean-mcmanus** [comment]
Is g++ on your PATH? If you type g++ on the command line it should give an output message from it.

**Comment by ghost** [comment]
Yes I think so, is this the right path ?
![1](https://user-images.githubusercontent.com/34433678/33855540-0d354c02-de7a-11e7-9314-95e293263602.png)

**Comment by sean-mcmanus** [comment]
Okay, I've reproed the problem. I'm not sure why VS Code isn't picking the environment path or what path it's using, because it picks up my CMake directory somehow, but not my MinGW directory. I was able to fix this via using the full path to g++ in the `command`. Does that work for you? You could also file a complaint with https://github.com/Microsoft/vscode/issues . There might be some way to get the correct environment path to be used, but I don't know what it is. I don't have this problem on Linux, only on Windows, which is using PowerShell on the terminal.

**Comment by ghost** [comment]
Now I have another issue, it is saying that : 

'g++' is not recognized as an internal or external command,
operable program or batch file.
The terminal process terminated with exit code: 1

**Comment by sean-mcmanus** [comment]
That sounds like the same error, but coming from cmd.exe instead of powershell. Can you use the full path to g++?

**Comment by ghost** [comment]
How can I change that ?

On Dec 11, 2017 3:19 PM, "Sean McManus" <notifications@github.com> wrote:

That sounds like the same error, but coming from cmd.exe instead of
powershell. Can you use the full path to g++?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode-cpptools/issues/1329#issuecomment-350891027>,
or mute the thread

**Comment by sean-mcmanus** [comment]
Change the `command` property to from "g++" to "C:/MinGW/bin/g++".

**Comment by ghost** [comment]
Sorry to bother you with that, but I still didn't find the answer

[image: Images intégrées 1]

**Comment by sean-mcmanus** [comment]
That's fine. Is it working now?

**Comment by ghost** [comment]
No I send you a screenshot,

my terminal is saying that :

> Executing task: C:\MinGW\bin\g++ -g helloworld.cpp <

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

2017-12-11 16:26 GMT-08:00 Sean McManus <notifications@github.com>:

**Comment by sean-mcmanus** [comment]
Yeah, I'm getting the same error you're getting. It's strange that there's no detailed error message, even with the -v flag. I'll ask around to see if anyone know about this.

**Comment by ghost** [comment]
thanks for reopening that.

**Comment by pieandcakes** [comment]
Can either of you confirm the version of G++ you are using? Also, if you run it in the command window, you have to make sure to set the PATH to your MinGW bin folder first. This is a limitation of MinGW because it needs to know where its libraries are that it needs during compilation.

You should be able to run `SET PATH=%PATH%;<path to your mingw bin folder>` and then run your G++ command. Alternatively you can set that path from a command prompt and then launch VS Code from the same command prompt.

**Comment by ghost** [comment]
I'm using the 6.3.0-1 version, the one I got with mingw.

**Comment by sean-mcmanus** [comment]
I'm using 5.3.0. ${env:Path} is showing that F:\MinGW\bin is on the path, but the path isn't recognized if I remove the path from the beginning of gcc. @pieandcakes can you post the command line you're using?

**Comment by pieandcakes** [comment]
@sean-mcmanus  The comment I made is not to fix the issue of finding `gcc` in the path, it is to help `gcc` resolve dependencies it needs during compile time. 

I compile from a command window, not through VS Code `task.json`. I assume if you want to use the `task.json` implementation, to create a `.cmd` file that sets the path and then issues the compile command.

**Comment by pieandcakes** [comment]
Note: This sounds like a toolchain issue with MinGW and not an issue with the extension.

**Comment by ghost** [comment]
I tried to type in the terminal too, and still didn't manage to make it work.

**Comment by pieandcakes** [comment]
@regunHD 
>I tried to type in the terminal too, and still didn't manage to make it work. 

Did you try this in a MinGW command window or a regular command window or VS Code's terminal window? The last two do not have the correct path set so it won't resolve dependencies. One of the other suggestions I've heard is to try MSYS2's version of MinGW.

**Comment by ghost** [comment]
Sorry, I don't really know to do that, I'm actually new in this software.
Since I'm using windows how can I have access to the terminal.

**Comment by pieandcakes** [comment]
@regunHD
> Sorry, I don't really know to do that, I'm actually new in this software.
Since I'm using windows how can I have access to the terminal.

If you are talking about the MinGW terminal, you can see if it is in one of the installed programs on your machine? Otherwise, it would be a normal command prompt but you would need to set the path as above.

**Comment by ghost** [comment]
Ok then. I don't have it installed, and I couldn't find it on my MinGW installer program.

Should I install it with a .exe installer (since I'm using windows 10) ?

**Comment by pieandcakes** [comment]
https://blogs.msdn.microsoft.com/vcblog/2017/07/19/using-mingw-and-cygwin-with-visual-cpp-and-open-folder/ is a blog post that should help you get started on how and where to install MinGW from. I think this article links to MSYS2 which will work also.

**Comment by priyamadhu** [comment]
Close the visual studio and reopen it by right clicking on it and selecting run as administrator. I had similar problem and this worked for me

**Comment by ARHollisSr** [comment]
@priyamadhu  I had to read all the way down here after trying everything above only to find out that your suggestion worked. Thanks mate.

**Comment by liamsain** [comment]
getting 'The terminal process terminated with exit code: 1' .
tasks.json
`{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "echo",
      "type": "shell",
      "command": "C:/raylib/mingw/bin/gcc.exe",
      "args":[
        "-g", "hi.c"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}`

c_cpp_properties.json:

`{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17134.0",
            "compilerPath": "C:/raylib/mingw/bin/gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}`

**Comment by pieandcakes** [comment]
@liamsain Can you look in your output window and see what the error message is? Also, from a regular command prompt can you run your command and see if you get more info?

**Comment by liamsain** [comment]
output window is empty. If I run from the command prompt I get an error window, title 'cc1.exe - System Error', message: 'The code execution cannot proceed because libwinpthread-1.dll was not found. Reinstalling the program may fix this problem'. Guess it's not a vscode-cpptools issue..

**Comment by pieandcakes** [comment]
@liamsain When I've run into that, the problem is that the `MinGW` bin folder wasn't on the path so it couldn't resolve dependencies. I usually add it to the `PATH` environment variable and it fixes the problem.

You are correct though. That error is because of a toolset configuration issue and not a vscode-cpptools issue.

**Comment by indrajitsg** [comment]
@regunHD I was facing the same problem initially. Then I realized that in my system, I had added path to my user's environment variable instead of system's environment variable. As a result even though g++ was recognized in CMD, it was not getting recognized in Powershell. 

So after adding path to MinGW bin folder to System's path, it started working

**Comment by tomdinh** [comment]
@indrajitsg You are right add the MinGW path to system path and restart the command line interface MinGW compiles flawlessly in all cmd, Powershell and VScode integrated terminal.
@pieandcakes @liamsain  Confirmed not a vscode-cpptools issue. On Linux and WSL (xfce) MinGW run smoothly with vscode-cpptools.
@regunHD Alternatively, you can use **Chocolatey** to install MinGW like this tutorial https://www.youtube.com/watch?v=xW6JTqRuQx0&t=

**Comment by sunnyjain** [comment]
@liamsain  I was facing the same issue, with the help of this issue thread.
-> I added the g++ to the path 
-> tried running on my cmd, which worked, but could not get it running on the VS's terminal.
-> then i changed 2 things
`"version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "E:\\MinGW\\bin\\g++.exe",
            "args": ["-g", "main.cpp"],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]`

instead of "command": "g++", i added the respective code 
then i changed terminal to launch in VS code.
you change it from User settings -> Features -> Terminal , there the first option change it to external.
and everything works for me!
thanks!

**Comment by saiksaketh** [comment]
> Close the visual studio and reopen it by right clicking on it and selecting run as administrator. I had similar problem and this worked for me

This actually worked :D

**Comment by ghost** [comment]
run as administrator!!! Thank you!!!

**Comment by HamedMoghadasi** [comment]
> Close the visual studio and reopen it by right clicking on it and selecting run as administrator. I had similar problem and this worked for me

**Thank You** :)

**Comment by shahab1992** [comment]
Thanks for sharing, administrator worked for me too :)

**Comment by ridoy19** [comment]
> Close the visual studio and reopen it by right clicking on it and selecting run as administrator. I had similar problem and this worked for me

Really, Microsoft should put your answer in front line 💯

**Comment by babelf1sh** [comment]
@regunHD What worked for me was adding the file path to the git bash shell (C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Git) to the System Environment Variables in the Control Panel (how to do that [here](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/). Then restart VS Code and it should work. Also, check out [this page](https://code.visualstudio.com/docs/cpp/config-mingw), it helped me sort things out (read it carefully). If you have any other trouble, take a look at [this tutorial](https://www.youtube.com/watch?v=DIw02CaEusY). Hope this helps!

Note: in the docs page I linked, they use the 64bit version of MinGW. It should still work with the 32bit version though.

**Comment by bhavya0598** [comment]
> Close the visual studio and reopen it by right clicking on it and selecting run as administrator. I had similar problem and this worked for me

It worked

**Comment by OldAAAA** [comment]
It worked!Can anyone explain why?I am so crazy about this problem!

**Comment by acjak** [comment]
I got it working by running as administrator, but the actual problem was that the path was only set for my user and not the system, which has been mentioned by others.

I just used [this guide](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) to copy the path for MinGW from my user's Path variable to the system's Path variable.

Once that's done, it works perfectly.

**Comment by gwochy** [comment]
@priyamadhu  Thank you for such a precise answer. Though I would want to know the after math

**Comment by Fenytestver** [comment]
> I got it working by running as administrator, but the actual problem was that the path was only set for my user and not the system, which has been mentioned by others.
> 
> I just used [this guide](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) to copy the path for MinGW from my user's Path variable to the system's Path variable.
> 
> Once that's done, it works perfectly.

Worked perfectly for me too.
**Thanks everyone!**

ps:  One might wonder if going through this hassle is really a necessary component of an IDE installation in the 21st century?

**Comment by pieandcakes** [comment]
@Fenytestver Its a toolset issue. I would expect that if MinGW needs to be on path that they will add it. The other option is to launch MinGW's `bash` window and run VS Code from there which will inherit the lib path.

**Comment by rishikeshshede** [comment]
Solution that worked for me is:
1) open the folder where you have created the file in which you are writing the code.
2) there you'll see a folder **.vscode**, open it and there will be a file named **c_cpp_properties.json**, open that file.
3) now copy the path of your compiler in front of **compilerPath**(change \ to / if needed) and save the file. (eg: C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin)
You are good to go now.
![compilerPath_error](https://user-images.githubusercontent.com/38062804/64758407-25d10280-d552-11e9-8544-499628679b23.PNG)

**Comment by ayushpratap** [comment]
I was facing this issue on windows.
The issue was the path in `User variables for ${USER}` was C:\Mingw\mingw32\bin
and path in `System variables` was C:\MinGW\bin

I resolved it by adding C:\MinGW\bin in `User variables for ${USER}`

**Comment by Muntasir2001** [comment]
> Executing task in folder C project: F:\MinGW\bin\gcc.exe -g 'c:\Users\Muntasir\Desktop\Projects\C project\Project1.c' -o 'c:\Users\Muntasir\Desktop\Projects\C project\Project1.exe' <

/usr/bin/bash: F:MinGWbingcc.exe: command not found
The terminal process terminated with exit code: 127


Can someone help me with this

**Comment by Muntasir2001** [comment]
https://www.youtube.com/watch?v=xj-A3REo2SY

This video shows everything, about how to instal and use MinGW on windows

**Comment by Muntasir2001** [comment]
When I try to build, I get this error. Can someone help me with this..?
> Executing task in folder C project: F:\MinGW\bin\gcc.exe -g 'c:\Users\Muntasir\Desktop\Projects\C project\main.c' -o 'c:\Users\Muntasir\Desktop\Projects\C project\main.exe' <

/usr/bin/bash: F:MinGWbingcc.exe: command not found
The terminal process terminated with exit code: 127

**Comment by pieandcakes** [comment]
@Muntasir2001 You are confusing MinGW and WSL. You can use WSL which is Linux tools running inside WSL, or MinGW which is running on Windows itself. Your error message below is telling me you are trying to run your MinGW path in WSL:

```
/usr/bin/bash: F:MinGWbingcc.exe: command not found
```

I can tell this because it is running the command in `/usr/bin/bash`

**Comment by Muntasir2001** [comment]
> @Muntasir2001 You are confusing MinGW and WSL. You can use WSL which is Linux tools running inside WSL, or MinGW which is running on Windows itself. Your error message below is telling me you are trying to run your MinGW path in WSL:
> 
> ```
> /usr/bin/bash: F:MinGWbingcc.exe: command not found
> ```
> 
> I can tell this because it is running the command in `/usr/bin/bash`

@pieandcakes , Ok I found out the issue. I am using Git terminal as a default terminal for VS code. That's why it was not working with mine. It was able to compile manually though.
Anyway, Thank You

**Comment by bobbrow** [comment]
This issue has been answered and the original post has been updated to locate the answer more quickly.  Closing.

**Comment by bobbrow** [comment]
This issue has been answered and the original post has been updated to locate the answer more quickly.  Closing.

**Comment by HamzaHajeir** [comment]
I have the exact same issue, Tried solutions here and it's not working though. 

I tried : 
- Add MinGW/bin folder to System variables
- Restart VSCode 
- Restart Windows 
- Run VSCode as administrator

g++ is recognized by cmd , Windows PowerShell. But not VSCode's PowerShell Terminal.

Running $env:path dumps the environmental paths, but MinGW/bin isn't one of them.

In the counterpart in Windows PowerShell : It only shows MinGW/bin as an env path.

![image](https://user-images.githubusercontent.com/32960423/72006261-e85a5880-3257-11ea-92ca-98e340e2a486.png)

**Comment by indrajitsg** [comment]
@HamzaHajeir Add it to both system and user variables. I just installed everything and checked that even if it is there in System variables it is not getting reflected in Powershell.

**Comment by indrajitsg** [comment]
@HamzaHajeir Try adding your path to user variables as well. I installed mingw and vscode and made sure the path was in both. VSCode with C/C++ plugin installed is working seamlessly .

**Comment by pieandcakes** [comment]
There is a VSCode [issue](https://github.com/Microsoft/vscode/issues/47816) that might be relevant to what you are running into.

**Comment by HamzaHajeir** [comment]
> @HamzaHajeir Try adding your path to user variables as well. I installed mingw and vscode and made sure the path was in both. VSCode with C/C++ plugin installed is working seamlessly .

That's already added,.

As I'm not fully absorbed the PATH concept, could something be wrong here ?

![image](https://user-images.githubusercontent.com/32960423/72189232-044f2d00-3405-11ea-8337-ef6aa30a7c97.png)

@pieandcakes  Thanks for reference, But mine is a bit different, As it didn't work even after a restart (actually .. it was shut down - power on)

**Comment by pieandcakes** [comment]
Those are all supposed to be inherited by VS Code. You may want to start an issue there about the `$env:path` variable not showing the correct path values and see what they say.

**Comment by HamzaHajeir** [comment]
Thanks, Submitting issue guide got me in trouble : As After I **disabled all extensions**. then only 2 env path variables shown. instead of many variables (before disabling).. thus my extension (PlatformIO) was no longer recognized even after enabling.

The solution to this second issue is : appending its path to system variables.

Now it's recognized and works well.

**Comment by QuanDev2** [comment]
> Solution that worked for me is:
> 
> 1. open the folder where you have created the file in which you are writing the code.
> 2. there you'll see a folder **.vscode**, open it and there will be a file named **c_cpp_properties.json**, open that file.
> 3. now copy the path of your compiler in front of **compilerPath**(change \ to / if needed) and save the file. (eg: C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin)
>    You are good to go now.
>    ![compilerPath_error](https://user-images.githubusercontent.com/38062804/64758407-25d10280-d552-11e9-8544-499628679b23.PNG)

I'm sorry, copy it and paste it to where?

**Comment by Chin-ma** [comment]
> Change the `command` property to from "g++" to "C:/MinGW/bin/g++".

Thanks for the help it helped me a lot

**Comment by asharhasan20** [comment]
g++ is not recognized in build task. 
<img width="558" alt="Capture" src="https://user-images.githubusercontent.com/70622383/92096953-2747aa80-edf5-11ea-856a-f02fc4aa89cd.PNG">

**Comment by HamzaHajeir** [comment]
> g++ is not recognized in build task.
> <img alt="Capture" width="558" src="https://user-images.githubusercontent.com/70622383/92096953-2747aa80-edf5-11ea-856a-f02fc4aa89cd.PNG">

It seems you've missed installing [Git ](https://git-scm.com/downloads)in your system.

**Comment by thameemk** [comment]
> https://www.youtube.com/watch?v=xj-A3REo2SY
> 
> This video shows everything, about how to instal and use MinGW on windows
Its works for me. Thanks
