### ISSUE TITLE
Issue 26 is still happening

### ISSUE THREAD

**Issue by jmlewis1** [microsoft/vscode-cpptools#133]
https://github.com/Microsoft/vscppsamples/issues/26

This is still happening.  And, I have no way of reopening the issue, as requested.

This is simple to reproduce.  Open a folder big enough to take a long time to parse, wait for it to finish parsing.  Close the folder, open it again, and the .db file immediately drops to 4k in size, and starts growing again.

**Comment by jgoshi** [comment]
What OS version, VSCode version, and cpptools version are you currently using?

**Comment by jgoshi** [comment]
Could you try this with the latest versions (VSCode 1.4 and cpptools 0.9.0)? And start from a clean state (meaning no existing database). If it still repros please reopen this issue and attach the database.
