### ISSUE TITLE
please add "Include Autocomplete" Intellisense

### ISSUE THREAD

**Issue by Yensan** [microsoft/vscode-cpptools#1330]
please add "Include Autocomplete" Intellisense, just as the plugin `Include Autocomplete ajshort `:
https://marketplace.visualstudio.com/items?itemName=ajshort.include-autocomplete

I used thinking this is supported by this MS C/C++ pulgin, but when I turn the `Include Autocomplete ajshort ` plugin down, I found it does not. 
I must say I love using VScode to edit C/C++ :laughing:

**Comment by sean-mcmanus** [comment]
Thanks for letting us know what features you want implemented. I want this feature implemented too, but we don't have an ETA yet. It is already being tracked by https://github.com/Microsoft/vscode-cpptools/issues/802 . You can "up vote" that, although having this issue being linked to that one counts as an upvote already.
