### ISSUE TITLE
Go to Definition is not correct! It go to the .h file, not source file

### ISSUE THREAD

**Issue by michaelllh** [microsoft/vscode-cpptools#1332]
* Operating System and version  : win7 64bits
    * VS Code version : 1.18.1
    * C/C++ extension version : 0.14.3
    * Other extensions: none
    * step-by-step instructions to reproduce the issue:

Editing C/C++ file，choose function and goto the definition, it won't go to the right definition, some time it go to .h file，But I really define it  in the project .c file.

**Comment by sean-mcmanus** [comment]
We need more repro details. Go to Definition on a newly added definition only works after you save a file. Also, the feature returns all matching results from the symbol parsing and doesn't yet use the IntelliSense compiler to choose the correct definition. Are you able to get the correct definition to appear in the list of Go to targets? The feature also doesn't work on local variables yet.

**Comment by LeThiHyVong** [comment]
@sean-mcmanus I have exactly same problem. 
It appear that if the definition is in a big cpp (my file is 30000 lines) then Intellisense fails to parse (https://github.com/Microsoft/vscode-cpptools/issues/1197). But the declaration in (short) header is fine and Go to Definition jump to the declaration. 
I have to use C++ Intellisense extension base on GNU tag global instead.

**Comment by JcobCN** [comment]
back to cpptools 0.13.0, it works well.

**Comment by sean-mcmanus** [comment]
@michaelllh Does the lastest update fix your issue? https://github.com/Microsoft/vscode-cpptools/releases/latest .
@JiangCN We fixed some regressions caused by 0.13.1. Let us know if it's working now.

We're still have some issues if your file has UTF-8 characters > 1 byte: https://github.com/Microsoft/vscode-cpptools/issues/1439

**Comment by brianignacio5** [comment]
Using cpptols 0.17.4
Cmake tools 1.0.1

Project : https://files.fm/u/zsnyk2j9
 
Steps to reproduce (In Linux based):
1. Extract folder cmake_test_vscode to any location {dir}.
2. Run `code {dir}/cmake_test_vscode/project`
3.  Run a cmake build using Cmake tools command : **Cmake: Build** 
4. Hover test() in project/main.c and Go to declaration/definition 

We observe that it goes to the test.h file but not to the test.c source.

Going to the actually symbol definition is really important. Could contribute but don't know how to start.

**Comment by sean-mcmanus** [comment]
@brianignacio5 It works if you use
```
            "browse": {
                "path": [
                    "${workspaceFolder}/../dependency"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
```
There are long-standing bugs on these issues (issues exist on GitHub):
1. The browse.path isn't automatically generated from the compile_commands.json
2. The non-workspaceFolder paths are not parsed for source files if limitSymbolsToIncludedHeaders is set to the default value of true.

We might be able to fix issue 2 in June and 1 in July (depending on other priorities).

**Comment by brianignacio5** [comment]
Thanks for your reply @sean-mcmanus !! 

Following up on browse.path functionality, would we be able to obtain the compiled .c source files from the compile_commands.json? Having just the list of directories can present conflicts on mutually exclusive sources ( which are selected upon different settings).

**Comment by sean-mcmanus** [comment]
@brianignacio5 Yeah, I think we should be able to parse only the source files listed in the compile_commands.json. The 2nd issue should be fixed in our next release.

**Comment by bobbrow** [comment]
This issue appears to be a duplicate of another issue: #1715
