### ISSUE TITLE
Invalid error squiggles when not including "/usr/include/x86_64-linux-gnu" in c_cpp_properties.json

### ISSUE THREAD

**Issue by tongko** [microsoft/vscode-cpptools#1333]
Operating System: Ubuntu 17.10
VS Code: Version 1.18.1 (Commit 929bacba01ef658b873545e26034d1a8067445e9)
C/C++ extension: 0.14.3

Steps to reproduce:
1. Open any existing C folder, which uses <stdint.h>
2. Change the C_Cpp.intelliSenseEngine to "Default".
3. Remove the line "/usr/include/x86_64-linux-gnu" from the c_cpp_properties.json.
4. Open the source file using type "uint32_t" (or any of the family).

Expected: when mouse over uint32_t, tool tips "typedef __uint32_t uint32_t" should be showing.
Actual: Error squiggle on the uint32_t. [NOT OK]

In the Problems output window, It shows: identifier "uint32_t" is not defined (line no).

I'm using a cross compiler to compile my code, so I put the include path specified by the command "[cross-compiler] -v -E -x c - < /dev/null into the c_cpp_properties.json under "Browse">"Path" and "includePath", removing those pointing to standard GCC's include fodler, then I got this error, even if the newly added paths contain the right header files (stdint.h, stdint-gcc.h).
Strange enough, pressing F12 or select 'Goto Definition' in the context menu will bring you to exactly the right header files, which in this case, stdint-gcc.h. And this is not impacting the build at all, the program can be compile successfully no problem.

Changing the C_Cpp.intelliSenseEngine to "Tag Parser" will remove this behavior.

**Comment by sean-mcmanus** [comment]
I'm not able to repro any problem, but my stdint/stdint-gcc.h is located at /usr/include/x86_64-linux-gnu/version/include . Does the stdint/stdint-gcc.h you're using require certain defines to be set? If Go to definition is working, that means the correct path is being located recursively from the browse.path setting. Do you get a code action suggesting a path to add?

**Comment by tongko** [comment]
The code action suggestion is 'Disable squiggle'.
Actually I've been seeing similar issues raise by others, and I try to take the advise given your side. Please note that I'm using a cross compiler, i.e. my include path and browse path are not anything under '/usr', instead, it is being place exactly as the output of the "[cross compiler] -v -E -x c - < /dev/null".
and the "defines" are being set to output of "[cross compiler] -dM -D - < /dev/null".
Logically, the extension should have taken this as the location to look for header files, but apparently, it is not, it seems like the path are being hard coded to '/usr/...' (just my assumption).
Also, as mention, without the '/usr/...' include path, placing the cursor at the type 'uint32_t' and then press F12 or Ctrl+F12, it does bring me to the right place where the type are being define, which is the "stdint-gcc.h" in the cross compiler include path.

From above observation I conclude that, if you are using a cross compiler install, say, at ~/opt/gcc-7.2.0/, and you are not using standard library, then you will hit this error.

**Comment by sean-mcmanus** [comment]
If you only see "Disable Squiggle", that means the stdint.h (or the associated header) couldn't be found via your browse.path setting. We're supposed to use the includePath and defines settings in the c_cpp_properties.json, but we also query the compiler for the defaults when initially generating the file. There might be a bug in which defaults are being added when they shouldn't, but I need to investigate a repro. IntelliSense should work with cross compilers, but if you're targeting Windows you'll need to set the intelliSenseMode to msvc-x64. Go to definition uses the browse.path setting instead of the includePath setting.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
