### ISSUE TITLE
#include doesn't follow paths on windows

### ISSUE THREAD

**Issue by dmh2000** [microsoft/vscode-cpptools#134]
using Vscode 1.4 and latest cpptools, i find that if a #include directive has a path, it is not followed and you get the green squiqqles and warning that path is not set.  this occurs when the include path is set in the proproperties file. . this also occurs with system includes such as #include <sys/types.h> when the include path property is set to Visual Studio C include path.

examples 
# include "library/library.h"   // path undefined
# include "library.h"              // ok

only occurs on windows. works ok on linux.

see attached examples
[vscode.zip](https://github.com/Microsoft/vscppsamples/files/404322/vscode.zip)

**Comment by jgoshi** [comment]
What version of the cpptools are you using? Using your sample it works fine for me.

**Comment by dmh2000** [comment]
i'll check on monday, but i had just downloaded VS code from the website https://code.visualstudio.com, installed it and I went to install cpptools and they were already there. so i think it was the most recent version a week ago.

**Comment by jgoshi** [comment]
Even though cpptools was already there, it was probably an older version (since it wouldn't get installed with VSCode). You would need to upgrade it (when you find the cpptools extension there should be a button to upgrade). The latest available version would be 0.8.1

**Comment by TiagoRabello** [comment]
I'm facing the same problem while using VSCode 1.4.0 and cpptools 0.8.1. It seems to be a problem with the handling of `/` on `#include` directives.

If I write `#include "foo/bar.h"`, it won't find the file even if `foo` is visible from any of my include paths and `bar.h` exists. However, the same is not true if I use `\`, as in `#include "foo\bar.h"`.

There also seems to exist a weird cache behavior, as writing `#include "foo\bar.h"` on a file that already have, and is complaining about, an `#include "foo/bar.h"` will both work, fix the previous complaint and allow you to write `#include "foo/bar.h"` without any problems from here on.

**Comment by jgoshi** [comment]
Thank you for the details. This behavior (the '/' vs '\' directory separator) issue has been fixed and will appear in the next release (version 0.9.0)

**Comment by TiagoRabello** [comment]
That's good to hear. Any ETA on next release ?

**Comment by jgoshi** [comment]
We can't guarantee, but we normally strive to release an update once per month.

**Comment by dmh2000** [comment]
I updated cpptools and the issue was fixed. Not the / \ thing just the
search path problem

dave howard
dmh2000@gmail.com
