### ISSUE TITLE
RFE: Switch Header/Source command support for files with *.cc extension.

### ISSUE THREAD

**Issue by photex** [microsoft/vscode-cpptools#1341]
Howdy!

I recently opened a project that used *.cc for c++ files and the Switch Header/Source command had no effect. Upon renaming one of the source files the command worked as expected.

Cheers!

**Comment by sean-mcmanus** [comment]
What is the extension of the header file? "*.cc" is supposed to work. We need more repro details. Does this repro for certain file names or for certain directory structures? What does the bottom right database icon say? Our system needs to have located the target file on disk and added it to our database before it can go to it. Also, if there's a red flame in the bottom right, the IntelliSense thread could be blocking the switching header.

**Comment by photex** [comment]
I've zipped up a setup that reproduces the problem for me.
[blah.zip](https://github.com/Microsoft/vscode-cpptools/files/1553181/blah.zip)

As it is, if you open the folder and open `foo.cc`, pressing Alt+o won't have any effect. Rename it to `foo.cpp` and it'll work as expected.

Hope this helps.

**Comment by sean-mcmanus** [comment]
@photex Thanks a lot for the repro -- I'm hitting the problem now. This is strange. I'll investigate...

**Comment by sean-mcmanus** [comment]
Oh, it's because the header file has the hpp extension and the system is setup to only switch cc files to .hh or .h files. This decision was made before I joined so I'm not sure what the reasoning was. Is there a reason your source is .cc and your header is .hpp? It seems inconsistent.

**Comment by sean-mcmanus** [comment]
We've changed it to switch from to any of .h/.hpp/.hxx/.hh from any of .c/.cpp/.cc/.cxx (not sure yet when the fix will be released). We eventually want to fix it to work on any extensions (I think another issue is tracking that).

**Comment by photex** [comment]
Awesome! Glad I could help. 

I don't know why they were named that way. I think .h was reserved for C interfaces and the header had to be something different. .hpp seems to be the vernacular for c++ interfaces. .cc was kinda left field. :D

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.5.
