### ISSUE TITLE
"Cannot open source file" for system headers in WSL Ubuntu

### ISSUE THREAD

**Issue by aotmr** [microsoft/vscode-cpptools#1347]
OS: Windows 10 Build 16299
VS Code version: 1.18.1
cpptools version: 0.14.4

Following the WSL instructions for configuring the include path didn't work for me, even after adding the WSL config to c_cpp_properties.json:

```
{
    "name": "WSL",
    "intelliSenseMode": "clang-x64",
    "includePath": [
        "${workspaceRoot}",
        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include",
        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu",
        "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include"
    ],
    "defines": [
        "__linux__",
        "__x86_64__"
    ],
    "browse": {
        "path": [
            "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
            "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include",
            "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
            "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu",
            "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/*"
        ],
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": ""
    }
}
```
I verified the presence of the header files, and under Ubuntu Bash, `ls /usr/include` shows a full folder, but in File Explorer, only gawkapi.h and sudo_plugin.h are visible, as well as two other folders. Intellisense has no problems parsing these files, so I know my includePath is correct.

So it seems like certain files are invisible to Windows, but visible to WSL.

**Comment by aotmr** [comment]
My problem was not with cpptools, but with WSL--I had a beta WSL installed alongside Ubuntu WSL. Uninstalling beta WSL resolved my issues completely.

**Comment by sus007** [comment]
@jamestn529 How to know if mine's a beta or not ?

**Comment by sean-mcmanus** [comment]
@sus007 You should make sure you have the latest Win10 OS and/or check your version in Settings->System->About. For non-Beta, your version should be at least 1709, build 16299.

**Comment by sus007** [comment]
### @sean-mcmanus I don't think I am a Beta User ? Am I ? 🤔
![image](https://user-images.githubusercontent.com/7630815/34397649-f6416e76-eb9f-11e7-8197-b6d5c1678e18.png)

**Comment by sean-mcmanus** [comment]
@sus007 No, you're not a beta user (i.e. before the released creator's update earlier this year), but I don't know what changes to WSL the insider preview build has...they could have introduced a bug.

**Comment by sean-mcmanus** [comment]
...but @jamestn529 didn't have the earlier OS either and somehow had an older version installed, not sure how. You might want to check with https://github.com/Microsoft/WSL/issues .
