### ISSUE TITLE
Pretty printing of stl iterators in gdb

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#1349]
I'm using gdb to debug my project which works amazingly well out of the box. I've added pretty printers using an old python script (I'm stuck on Qt 4) which also works for most things.

It shows me the contents of STL containers in the variables window, but it doesn't seem to show the contents of iterators.

For example,

an iterator called 'file' shows the following value in the variables view:
`{sub_path = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 108}, alloc = 0, size = 0, data = 0xf6edaede <QString::shared_null+18>, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 5}, alloc = 0, size = 0, data = 0xf6edaef2 <QString::shared_empty+18>, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0x66800000, static codecForCStrings = 0x0}, alias = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 108}, alloc = 0, size = 0, data = 0xf6edaede <QString::shared_null+18>, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 5}, alloc = 0, size = 0, data = 0xf6edaef2 <QString::shared_empty+18>, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0xff85e010, static codecForCStrings = 0x0}}`

However, if I enter "-exec p source" in the debug console, it shows

`$3 = {first = "/path/to/folder1/subsystem.qrc", second = std::list = {[0] = {sub_path = "icon1.png", alias = ""}}}`

Is there some way to change the pretty printer format so that the variable view can decode it?

**Comment by pieandcakes** [comment]
@Gruntfuggly We enable the 'gdb' pretty printers but do not contribute to them. If you can give me a quick repro of this I can take a look at what we're requesting from `gdb` and see why it would be different. Are you saying that you want to add a custom pretty printer or you have added it but it isn't working?

You can also enable `"logging": { "engineLogging": true }` in your `launch.json` to see what we send `gdb` and what we get back.
