### ISSUE TITLE
debugging config file lacks documentation

### ISSUE THREAD

**Issue by waderyan** [microsoft/vscode-cpptools#135]
This comment was on [HN](https://news.ycombinator.com/item?id=12229015). 

![image](https://cloud.githubusercontent.com/assets/2449568/17452888/e7537e3a-5b28-11e6-85a0-06cc6a7cbf5a.png)

Passing on.

**Comment by pieandcakes** [comment]
@Andrew-MSFT  - Here is another request for more documentation for the debugging options. It looks like they would like more help/guidance for creating the launch.json.

@waderyan - Thanks. We have plans to revamp the documentation located at: https://code.visualstudio.com/docs/languages/cpp

**Comment by AndrewBrianHall** [comment]
Added documentation at https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md
