### ISSUE TITLE
'xxx.h' file not found

### ISSUE THREAD

**Issue by zk5580752** [microsoft/vscode-cpptools#1352]
Hi, I got a problem like this:
![screen](https://user-images.githubusercontent.com/10323590/34042568-47a40da4-e1d8-11e7-8b82-e84db1516a79.png)

The cpp file cannot find its .h header, but the cpp code could be compiled normally without any problem.
The red squiggles not feel good. Please give me some advice. 

Env info:

- Ubuntu 14.04
- VSCode 1.19.0
- C++ extension equiped
- IntelliSense is configured well (the well performed 'includePath')

Thank you!

**Comment by sean-mcmanus** [comment]
The "file not found" tooltip message is from the C/C++ Clang Command Adapter extension and not the C++ extension.

Maybe check out https://github.com/mitaki28/vscode-clang/issues/32 for ways to resolve this.
