### ISSUE TITLE
Weird auto complete behavior with local variable.

### ISSUE THREAD

**Issue by Misairu-G** [microsoft/vscode-cpptools#1354]
**Operating System and version**: Ubuntu 16.04
**VS Code version**: 1.19.0
**VSCode Insiders build**: No
**C/C++ extension version**: 0.14.4

With the extension enabled, I cannot get the variable I want with `"C_Cpp.autocomplete": "Default"`.

`"C_Cpp.autocomplete": "Default"`
![cpptool_default](https://i.imgur.com/cF0mwIK.png)

`"C_Cpp.autocomplete": "Disable"`.
![cpptool_disable](https://i.imgur.com/Xwz6rG9.png)

Behavior in C/C++ Clang command Adapter extension
![clang_extension](https://i.imgur.com/TZsewhd.png)

As you can see on the screen shot, this also have nothing to do with IncludePath. And, no, I didn't configure any option of the cpptools extension.

**Comment by sean-mcmanus** [comment]
We don't support local variable autocompletion yet. It's being tracked by https://github.com/Microsoft/vscode-cpptools/issues/13 .
