### ISSUE TITLE
Multi root problem in "Tag Parser" mode?

### ISSUE THREAD

**Issue by woytowg** [microsoft/vscode-cpptools#1357]
Ubuntu 16.04
VS Code 1.19
C/C++ extention 0.14.4

I'm using  "C_Cpp.intelliSenseEngine": "Tag Parser" because I have a large build and don't want to specify all the possible header includes. 

I have three separate root folders in my workspace, first root folder works fine, the second and third get errors of "Include file not found in browse path" for local header files in the same root folder and Go to Definition doesn't work for the symbols in these local header files.

I have the default browse.path set to "${workspaceRoot}"  in the second and third root folders, the first working root folder has a more complicated setup.

The thing that is weird is if I select the problem #include header in the cpp file and hit Ctrl-F12 (Go to Implementation) it goes to the file correctly, so the information is present in the database

**Comment by sean-mcmanus** [comment]
I don't understand what you mean by "local header files in the same root folder". I'm not able to repro the problem with a simple multi-root workspace (although I tried on Windows, so I'll check out Ubunut later). Can you provide more repro details in regards to the folder structure? Does it repro with the simplest case of a 2 root workspace folders with a single source/header pair? Yeah, the "Include file not found in browse.path" shouldn't appear if the header file can be navigated to via Go to Definition...maybe the missing header warning is being shown incorrectly. Are symbols found from the headers?

**Comment by woytowg** [comment]
By "local" I mean header files in the workspace root folder, as opposed to system headers in /usr/include, etc.

The symbols from the missing headers are in the database, they just not accessible because of the include errors.

If I were to guess, it seems like the second and third root folders are performing lookups in the first root folder database for some reason. Can I turn on some kind of debug to see what happens when a lookup occurs?

I'm not able to give more details, don't have access to my work PC right now.

**Comment by sean-mcmanus** [comment]
Which workspace root folder? Are you referencing files that exist in the current workspace folder or another workspace folder? When you use "${workspaceRoot}" it doesn't actually mean the root of all the workspace folders, but the actual path of the current workspace folder (i.e. it's the same as VS Code's ${workspaceFolder} but we didn't get around to renaming it like VS Code did before they added multi-root support). I have never observed the behavior you describe, I don't remember any other user reporting this, and a simple setup is not able to repro it for me, so it seems like something unusual is required for the repro. You could set the C_Cpp.loggingLevel to Information (or if necessary to a higher number like 6-9, but those cause lots of spam output that slow things down, so you'd want to disable the output during normal usage).

**Comment by sunnyps** [comment]
I can reproduce this with a single folder workspace too:

chromium.workspace in parent directory of chromium "src" repository:
```
{
	"folders": [
		{
			"path": "src"
		}
	],
	"settings": {
	}
}
```
src/.vscode/settings.json:
```
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/data": true,
        "build/linux": true,
        "native_client": true,
        "out*": true,
        "third_party": true
    },
    "C_Cpp.clang_format_style": "Chromium",
    "C_Cpp.intelliSenseEngine": "Tag Parser"
}
```
src/.vscode/c_cpp_properties.json: Default with "{workspaceRoot}" (recursive) in includePath and browse.path.

If I open the workspace, I see include errors and navigation does not work. If I open the folder independently, I don't see include errors and navigation works as expected.

Aside 1: I have a question about how recursive vs non-recursive browse.path works. What happens to an include like "base/stl_util.h" if I put non-recursive "{workspaceRoot}/*" in browse.path? Does the tag parser engine append the include path to browse.path and look for that file? Of course, recursive browse.path works, but I was wondering if that's doing more work than needed.

Aside 2: Can the tag parser search in paths that are excluded through files.exclude, like third_party/skia/include in the above example? Adding that path ("{workspaceRoot}/third_party/skia/include") explicitly in browse.path didn't work. Nor did setting "third_party/skia/include" to false in files.exclude. Do you know of any other way to achieve this?

**Comment by sean-mcmanus** [comment]
I have the same chromium.code-workspace and settings.json and c_cpp_properties.json, but I'm not able to repro any problem. What file are you opening?

With ${workspaceRoot}/*, only the files directly in the ${workspaceRoot} folder would be locatable and parsed on project load. If one of those files has a #include "base/stl_util.h" it will actually ignore the "base" and try to look for a file with the name std_util.h, which it won't find. However, we parse files on open as well, but our database clean up code might remove the symbols later on.

The tag parser won't search in files.exclude paths that are under the workspace root -- it will not exclude files that are not part of the workspace root, but there is a bug on that. The only way to achieve this would be to change your files.exclude.

**Comment by sunnyps** [comment]
The file is "src/cc/resources/resource_provider.cc".

VS Code build:
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:41:01.414Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

> The tag parser won't search in files.exclude paths that are under the workspace root -- it will not exclude files that are not part of the workspace root, but there is a bug on that. The only way to achieve this would be to change your files.exclude.

Can you exclude a path via files.exclude but selectively include subpaths? Like exclude third_party but include third_party/skia/include?

**Comment by sunnyps** [comment]
As I wrote my last comment, the includes started working! Clearly I'm imagining this, or the reindexing takes a while?

**Comment by sean-mcmanus** [comment]
@sunnyps When you open the file, it should be parsed on a separate thread, so it shouldn't take too long. There could be some other bug that caused a delay.

Currently, we only use files.exclude that have values of "true". We could handle the "false" case (applying to anything that matches) and having it not be excluded, but VS Code itself doesn't behave this way -- can you file a bug with VS Code to get them to support "false" in the files.excluded? If you can get them to change their behavior, then we could update ours to match.

**Comment by sunnyps** [comment]
I doubt VS Code maintainers would agree to that. Multi-root workspace is already a solution to that problem.

Is it possible to make the tag parser navigation (and completion?) work across folders in a multi-root workspaces? It would be very useful for projects like chromium where most developers are concerned with the main directory and only a small subset of third_party directories. I can file a feature request for this if you could tell me what information to include.

**Comment by sean-mcmanus** [comment]
Right now every workspace folder has a separate process running for it with a separate c_cpp_properties.json for settings so getting them to communicate with each other might be difficult. Is there a reason you're not able to modify your includePath/browse.path to include paths in the other folder to achieve the same result?

**Comment by sunnyps** [comment]
Those files are in globally excluded files ("files.exclude"). I can put third_party in search.exclude instead (so that Ctrl-P performance is good) but then the tag parser goes through all files in third_party which is a lot of files.

**Comment by sean-mcmanus** [comment]
If you use the recommended default of "limitSymbolsToIncludedHeaders" to true, then the files external to the current workspace folder will only be parsed if they are #included by a workspace file.

**Comment by sean-mcmanus** [comment]
Our latest Insiders release has a new multi-root implementation (which fixes this bug): https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders. Please let us know if you find any multi-root-related bugs or regressions so we can prioritize fixing those for 0.27.0.
