### ISSUE TITLE
Problems with GCC (via Homebrew) and Intellisense

### ISSUE THREAD

**Issue by galletas1712** [microsoft/vscode-cpptools#1358]
I'm on macOS Sierra, version 1.19.0. ms-vscode.cpptools version 0.14.4.

I just installed GCC 6.4.0 over Homebrew, and tried to use its include paths for intellisense instead of the ones from Xcode. However, it seems to be faulty in resolving my includes. Most notably, it fails to recognize scanf, even though it is included in bits/stdc++.h (it includes cstdio).
![screen shot 2560-12-18 at 11 14 35 pm](https://user-images.githubusercontent.com/17022745/34115973-a64fcc8a-e449-11e7-9d44-7898c981afe9.png)

Currently, my c_cpp_properties.json file looks like this for mac:
![screen shot 2560-12-18 at 11 22 17 pm](https://user-images.githubusercontent.com/17022745/34116165-5328d898-e44a-11e7-991a-42d4a7e1fd6e.png)

**Comment by sean-mcmanus** [comment]
Can you give the exact error associated with the scanf squiggle? It could be due to a missing "define". I can investigate more later.

**Comment by galletas1712** [comment]
The squiggle's error says that the identifier "scanf" is not defined. The same happens even if I remove bits/stdc++.h and include cstdio only. Even stdio.h has the same problem.

**Comment by sean-mcmanus** [comment]
I assume you mean `identifier "scanf" is undefined`, right? -- I want to make sure the error is coming from out extension and not another one that would output a different message.

**Comment by galletas1712** [comment]
Yes, the error came from the extension just like that.

**Comment by sean-mcmanus** [comment]
I installed gcc 6.4 Homebrew on Mac and it works for me (scanf is found by IntelliSense). It looks like your include path ordering is incorrect and you're missing some stuff. You should run the command `/usr/local/Cellar/gcc@6/6.4.0/bin/gcc-6 -Wp,-v -E -xc -x c++ /dev/null` and use the include paths it lists, e.g. '/usr/local/Cellar/gcc@6/6.4.0/include/c++/6.4.0 to /usr/include`. Let me know if you're still having problems.

**Comment by galletas1712** [comment]
Everything works fine now. Thanks!
