### ISSUE TITLE
0.14.4 can not debug

### ISSUE THREAD

**Issue by vSzemkel** [microsoft/vscode-cpptools#1359]
The error message is: "Internal package.json error encountered (..)"

Apple LLVM version 9.0.0 (clang-900.0.38)

This is the second Mac with this situation
Extension version 0.14.3 runs well

**Comment by sean-mcmanus** [comment]
We have a fix for that pending (see https://github.com/Microsoft/vscode-cpptools/issues/1344 ). It should be fixed after doing a Reload Window. Does that work for you?

**Comment by vSzemkel** [comment]
Yes, after reloading window debugger works.

**Comment by sean-mcmanus** [comment]
With 0.14.5, you should get warning/reload prompts instead of the strange error message.
