### ISSUE TITLE
the Chinese output problem

### ISSUE THREAD

**Issue by bobo4629** [microsoft/vscode-cpptools#136]
when use the printf() and output the Chinese char 
it will be uncoded 

i think that the VScpp doesn't use the UTF-8 when output.

**Comment by delmyers** [comment]
@bobo4629 
Just for a little more clarification, are you seeing bad characters in your terminal output, or in the debug console?

**Comment by bobo4629** [comment]
in the terminal output

**Comment by sean-mcmanus** [comment]
Can you give more info? Is this when debugging? Where is the printf used?

**Comment by bobbrow** [comment]
If you are continuing to have issues with this, please post some additional information and we can investigate further.  Thanks!

**Comment by light0x00** [comment]
It seems that `DebugConsole` does not understand unicode encoding, It only displays the ASCII encoding correctly.

the code:

```
fprintf(stderr, "test 缺少参数!\n");
```

the output in cppdbg  DebugConsole: 
```
"test\xe7\xbc\xba\xe5\xb0\x91\xe5\x8f\x82\xe6\x95\xb0!\r\n"
```
