### ISSUE TITLE
Language server not setup

### ISSUE THREAD

**Issue by inochisa** [microsoft/vscode-cpptools#1361]
My C/C++ extension is not able to work.If I reinstall the extension, it will not download the dependencies. And if I set up extension command It gives me  `Please wait for the C/C++ extension dependencies to finish downloading and installing.`.   But I don't see the download process in the task window that I saw before.If I install the extension using the vsix. the language server is not opened and I don't see the `Microsoft.VSCode.CPP.Extension.linux` and `Microsoft.VSCode.CPP.IntelliSense.Msvc.linux` in my monitor.I wonder whether it's a problem with the visual-studio-code or the extension.But I see the other extension is well worked.  
My OS is Arch linux x64. and the code version is 1.19.0.

**Comment by sean-mcmanus** [comment]
What does it show in the C/C++ Output window panel? We normally don't show it now unless an error occurs. It should only show that "Please wait" message when it hasn't yet downloaded the dependencies (writing the install.lock file). Actually, the "Please wait" message is supposed to force show the C/C++ output pane. It shows that "Please wait" when you do launch debugging, attach, or opening a launch.json file...oh, we also show that for any C++ command before the install is finished. Have you tried the offline vsix? https://github.com/Microsoft/vscode-cpptools/releases/download/v0.14.5/cpptools-linux.vsix . You might try checking out `/home/user/.vscode/extensions/ms-vscode.cpptools-0.14.5` to see what has installed. If there's a typescript problem, Toggle Developer Tools might show an error.

**Comment by inochisa** [comment]
Offline 0.14.5 vsix is failed.But I try 0.14.4 it's ok. I don't see the install.lock file,where should I seek for?The feedback I get is none.The C/C++ Output window panel also showed nothing.I can compile without exec the debugger.The I got nothing.

**Comment by sean-mcmanus** [comment]
What do you mean by "failed"? Do you get any error message? install.lock goes at `/home/user/.vscode/extensions/ms-vscode.cpptools-0.14.5`. We're not able to repro this and we've tested on 3 different Linux distros (and Mac)...we haven't tested on Arch Linux, but we haven't hit any special issues with that distro in the past...maybe an external extension could be interfering? I don't understand how the C/C++ can show nothing...I've never seen that before. I assume it exists but is blank? Or is the C/C++ option not in the dropdown?

**Comment by inochisa** [comment]
I don't see the install.lock in the dictionary. I mean failed is the server is not open and I can get nothing feedback.

**Comment by sean-mcmanus** [comment]
In our telemetry, I see "a lot" users on Arch Linux successfully using 0.14.5, so I don't think it's an Arch Linux issue.

**Comment by inochisa** [comment]
I see too.Although I reinstall visual-studio-code. the error still existed.

**Comment by inochisa** [comment]
I purge all the file releated to the vscode and reinstall the extension manually, now it's works.But I still to type the reset database command to start the process.

**Comment by sean-mcmanus** [comment]
Okay, that is strange. Might be some VS Code bug or corrupted download/install? What does "I still to type the reset database command to start the process mean"? What "process" are you referring to?

**Comment by inochisa** [comment]
In fact, After I install it,The `Microsoft.VSCode.CPP.Extension.linux`did not appear, So I used the command `Reset databse` to open it.

**Comment by sean-mcmanus** [comment]
Oh, I know -- the Microsoft.VSCode.CPP.Extension.linux process won't start until you open a C++ file or use a C++ command, which is why using Reset Database worked. This is intentional so that we don't do processing in non-C++ workspaces, because the debugger part of our extension requires that the extension activate onDebug (for any language).

**Comment by simon-r** [comment]
I've the same problem on ArchLinux.
The extension seems to start correctly. 
But if I do the right click on a method name and I select "go to declaration" (or another option) it produce the error message: _Please wait for the C/C++ extension dependencies to finish downloading and installing._

If I downgrade to 0.14.4 it's still working.

**Comment by sean-mcmanus** [comment]
@simon-r What does it show in the C/C++ Output panel? Is it still downloading dependencies? It looks like our extension has not installed yet (no install.lock file).

**Comment by simon-r** [comment]
@sean-mcmanus
Nothing, the output panel remains empty.

**Comment by sean-mcmanus** [comment]
@simon-r Hmm...I don't see how that could be happening. Are you using the normal extension via VS Code or the offline vsix at https://github.com/Microsoft/vscode-cpptools/releases ? You might try the offline vsix if the other one isn't working. You could also try to diagnose the issue via the javascript at `~/.vscode/extensions/ms-vscode.cpptools-<version>/our/src/main.js`...i.e. modifying the javascript with output stuff to try to figure out where it's failing. It would be easier to debug after we open source the typescript (not sure when yet). Maybe another extension is interfering.

**Comment by simon-r** [comment]
The problem  is appeared with the vscode code version.
I've fixed by downgrading with the vsix.

Or I try to disable all extensions ... except cpptools

**Comment by sean-mcmanus** [comment]
The VS Code version or the cpptools version was the problem? If you do a Help->Toggle Developer Tools you might be able to see what error is being throw in the javascript with 0.14.5.

**Comment by sean-mcmanus** [comment]
We opened source our typescript code, so if you want, you could clone the git repository and try to debug it yourself: https://github.com/Microsoft/vscode-cpptools . We have info at https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started.md#build-and-debug-the-cpptools-extension , but some of the info might be out of date.

**Comment by simon-r** [comment]
Now is working. 
Without doing anything serious. 
I've disabled and reactivated all extensions, and I've installed vsce.

**Comment by sean-mcmanus** [comment]
Sounds like this is fixed now?
