### ISSUE TITLE
tag parser failed

### ISSUE THREAD

**Issue by suzukajiang** [microsoft/vscode-cpptools#1364]
![image](https://user-images.githubusercontent.com/34700091/34190285-d73aab1c-e57a-11e7-947d-55843b3a53e4.png)

IntelliSense Engine = Tag Parser.
Autocomplete is enabled.
Error squiggles are disabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
Discovering files...
  Indexing: 0 file(s) processed
  Indexing: 1 file(s) removed from database
Done discovering files.
Parsing open files...
Checking for edits and parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Tag parsing failed: D:\RLC\AM_V9.3.0\RLC_AM_RETRANSMIT.C
Done parsing open files.

**Comment by sean-mcmanus** [comment]
Can you identify what code is causing the failure? We don't support GBK encoding, so it's probably related to that.

**Comment by suzukajiang** [comment]
![image](https://user-images.githubusercontent.com/34700091/34234928-3d42ae7e-e629-11e7-8d42-eb3f713907de.png)

![image](https://user-images.githubusercontent.com/34700091/34235033-e2d207a4-e629-11e7-9504-3ed9fbe99420.png)

maybe it's not the reason， the plugin works well in other GBK files. 
I also test utf-8, when I changed the setting to UTF-8, it also failed.

**Comment by sean-mcmanus** [comment]
We need more info in order to fix this. If you could provide an isolated repro that would help. The repro may require certain unsupported characters to exist in the file. I'm currently investigating another parser failure that I'm able to reproduce, so maybe that could be related to this.

**Comment by sean-mcmanus** [comment]
I just found a bug that will cause the tag parser to continually fail for a file even after the cause of the failure is eliminated (https://github.com/Microsoft/vscode-cpptools/issues/1367 ), so isolating the code that causes the tag parse failure would probably require using Reset IntelliSense Database after a tag parse failure.

**Comment by sean-mcmanus** [comment]
I believe this should be fixed in our pending update. We might release an insider's build so people can verify it fixes the issues.

**Comment by sean-mcmanus** [comment]
We have a pre-release with the fix if you want to try it out (https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.14.6-insiders) and let us know if you're still having problems with symbols not being found (you may need to Reset IntelliSense Database or edit the file with symbols to get the database updated).

**Comment by sean-mcmanus** [comment]
Should be fixed now: https://github.com/Microsoft/vscode-cpptools/releases/latest .
