### ISSUE TITLE
Symlink'ed paths in compile_commands.json not taken

### ISSUE THREAD

**Issue by jondo2010** [microsoft/vscode-cpptools#1365]
While getting my C++ project using the Bazel build system working with intellisense in VS-Code, it appears as though symlinks are not being followed correctly.

- Linux
- vs-code 1.19.0
- cpptools 0.14.5

My `compile_commands.json` looks something like this:
```
{
    "directory": "/home/john/.cache/bazel/_bazel_john/b74fab4f1d4785d9b546125b63063446/execroot/werkstatt",
    "command": "/usr/bin/clang++ -std=c++11 -isystem simulation/modules/osi_bridge/include -isystem bazel-out/k8-fastbuild/genfiles/simulation/modules/osi_bridge/include -c simulation/modules/osi_bridge/plugin.cpp bazel-out/k8-fastbuild/bin/simulation/modules/osi_bridge/_objs/osi_bridge.dll/simulation/modules/osi_bridge/plugin.pic.d",
    "file": "simulation/modules/osi_bridge/plugin.cpp"
}
```

My source directory is `/home/john/Devel/werkstatt`. Bazel puts all generated and compiled files into a folder under `~/.cache/bazel` and writes symlinks back into the source directory, so the `directory`, `-isystem` and `file` directives above are all logically valid. **`cpptools` however doesn't like it.**

I was able to work around this limitation by processing the `compile_commands.json`, turning all paths into real, absolute.

**Comment by sean-mcmanus** [comment]
Hmm...so far, I'm not able to repro a problem with symlinks with compile commands. Not sure what is different between my setup and yours.

**Comment by janbernloehr** [comment]
The issue my be `-isystem`. To me it seems that whenever there is an `-isystem` include in the compile commands, cpptools stop working for that file.

**Comment by sean-mcmanus** [comment]
@janbernloehr The code is supposed to handle isystem in general. There might be some special case where it is breaking. Let us know if anyone discovers what that special case is. Otherwise, we'd need to investigate that ourselves.

**Comment by Colengms** [comment]
Hi @jondo2010 .  Do you still have a repro for this?  Symbolic links should be getting resolved.  We can investigate further, if we can get a repro.
