### ISSUE TITLE
Debugging silently has no effect the 1st time it's done if the extension isn't loaded yet

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1366]
1. I used Windows, probably repros on other OS's.
2. Don't open a C++ file, but do Attach debugging (not sure if it repros with Launch).

Bug: The attach dropdown appears, but it never succeeds (silently fails). The Attach causes the extension to load, but it looks like there's some problem handling the debug action until Attach is done a 2nd time. Not sure why we haven't received complaints from users about this yet.

**Comment by WardenGnaw** [comment]
extension.pickNativeProcess and extension.pickRemoteNativeProcess are registering temporary commands during the extension activation. Launch configurations expect actually ```Promise<string>``` to be returned, but instead ```void``` is returned. 

Fix is to register actual AttackPicker.ShowAttachEntries and also have it do the dependency check.

**Comment by sean-mcmanus** [comment]
Fixed https://github.com/Microsoft/vscode-cpptools/releases/latest.
