### ISSUE TITLE
Can we launch the console application in integrated console (Terminal) rather than debug console?

### ISSUE THREAD

**Issue by ZZYSonny** [microsoft/vscode-cpptools#1368]
Since input from debug console is considered variables to watch, we can't input from it. While using a external console helps but we have to switch between VSCode and external console. It will be much more convenient if it is launched in integrated console (Terminal) that we can do the thing in only one window. (Just like moving the external console to the integrated console/terminal)

//Probably launching in integrated console and then attach it using PID?

**Comment by pieandcakes** [comment]
@ZZYSonny No at this time. This is on the backlog already as #35
