### ISSUE TITLE
Intellisense can't locate namespaces STD

### ISSUE THREAD

**Issue by xamiell** [microsoft/vscode-cpptools#1369]
![capture](https://user-images.githubusercontent.com/12973165/34276116-60816a5e-e676-11e7-97ca-c0e3a8fc481d.PNG)

* VS Code version: 1.19.1
* Extension: C/C++ for Visual Studio Code

**Comment by sean-mcmanus** [comment]
We need more info. What is your OS? What is your c_cpp_properties.json includePath? Are you #include'ing string and vector?

**Comment by xamiell** [comment]
Sorry for the lack of information.
More detail of the problem:
* OS: Windows 10 Pro Build: 1709
* c_pp_properties.json (Screenshot below): 

![image](https://user-images.githubusercontent.com/12973165/34284190-9666c6c0-e6a6-11e7-9326-a3390a405b32.png)

* And yes, I have included the headers mentioned.

**Comment by sean-mcmanus** [comment]
Did you see https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md ? Your includePath, defines, and intelliSenseMode settings do not appear to be correct (browse.path could be fixed as well).

**Comment by xamiell** [comment]
Yeah! It works! The aforementioned error no longer occurs. Thanks for your support.
