### ISSUE TITLE
Can't debug

### ISSUE THREAD

**Issue by sczh01** [microsoft/vscode-cpptools#137]
condition:
OS: Win7 professinal 64bit, Chinese version.
WINGW: 6.1
## Below sample code can enter debug UI.
# include <iostream>

int main()
{
    int i = 10;
    while (i >= 0)
        std::cout << i-- << " ";
    return 0;
}
## But can't enter debug UI by below sample code.
# include <iostream>
# include <vector>

using std::cout;
using std::endl;
using std::vector;

int main()
{
    vector<int> ivec{ 1, 2, 3, 4, 5, 6, 7, 8, 9 };

```
for (auto i : ivec) {
    cout << ((i & 0x1) ? i * 2 : i) << " ";
}
cout << endl;

return 0;
```

}

Launch Jason file:

{
   "version": "0.2.0",
   "configurations": [
        {
            "name": "C++ Launch (GDB)",                 // 配置名称，将会在启动配置的下拉菜单中显示
            "type": "cppdbg",                           // 配置类型，这里只能为cppdbg
            "launchOptionType": "Local",  
            "request": "launch",                        // 请求配置类型，可以为launch（启动）或attach（附加）
            "targetArchitecture": "x86",                // 生成目标架构，一般为x86或x64，可以为x86, arm, arm64, mips, x64, amd64, x86_64
            "program": "${file}.exe",                   // 将要进行调试的程序的路径

```
        "miDebuggerPath": "E:\\sw_soft\\mingw\\mingw32\\bin\\gdb.exe",
        "args": ["blackkitty",  "1221", "# #"],     // 程序调试时传递给程序的命令行参数，一般设为空即可
        "stopAtEntry": false,                       // 设为true时程序将暂停在程序入口处，一般设置为false
        "cwd": "${workspaceRoot}",                  // 调试程序时的工作目录，一般为${workspaceRoot}即代码所在目录
        "externalConsole": true,                    // 调试时是否显示控制台窗口，一般设置为true显示控制台
        "preLaunchTask": "E:\\sw_soft\\mingw\\mingw32\\bin\\g++.exe" // 调试会话开始前执行的任务，一般为编译程序，c++为g++, c为gcc
    }
]
```

}

Task jason file:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
   "version": "0.1.0",
    "command": "E:\sw_soft\mingw\mingw32\bin\g++.exe",
    "args": ["-g","${file}","-o","${file}.exe"],    // 编译命令参数
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(._):(\d+):(\d+):\s+(warning|error):\s+(._)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
}

**Comment by sczh01** [comment]
VSC version is 1.4

**Comment by jacdavis** [comment]
What was the error are you getting when if fails? I tried your sample (after fixing a few compilation issues) and was able to debug.

One thing to try, if you’re getting a message like this:
ERROR: During startup program exited with code 0xc0000139.
The program 'c:\temp\customerbug\a.exe' has exited with code 0 (0x00000000).

is to make sure the path to mingw is contained within the path vscode is running in (by setting the PATH environment variable). It appears gdb has a dependency to that folder in the mingw case.

**Comment by delmyers** [comment]
@sczh01, I would like to follow up quickly, as this issue has gone stale. Has your issue been resolved? Are you able to debug?

**Comment by delmyers** [comment]
@sczh01 Since you have not gotten back to us, I'm going to assume that you aren't having any problems anymore. Feel free to re-open the issue if you need more help.
