### ISSUE TITLE
Unable to debug QT application written in C++ code on Windows platform using VSCode? Its not stepping into breakpoints

### ISSUE THREAD

**Issue by 10manjunath** [microsoft/vscode-cpptools#1371]
I'm unable to debug qt application step by step using GDB. I have setup a launch.json with cygwin GDB on windows. I tried the both "launch and attach" methods to debug. When I use the attach mode, it's successfully showing the call stack with some threads in it, but VSCode is still not debugging line-by-line and encountering my breakpoints. The step in/over buttons are disabled.

![image](https://user-images.githubusercontent.com/7700267/34303156-419d07ec-e702-11e7-93da-002c1729cc85.png)

**Comment by sean-mcmanus** [comment]
Did you compile with the -g flag enabled?

**Comment by 10manjunath** [comment]
Yes, I've added "-g" flag to tasks.json file. When I start debugging with this buildstep, it's not encountering any breakpoints. Those buttons are still in disabled state.

**Comment by 10manjunath** [comment]
Used attach method to debug. Its successfully loading all the dll symbols. But it's not encountering breakpoints for step in/out and unable to add variables to watch list.

![image](https://user-images.githubusercontent.com/7700267/34416044-986779a6-ebbf-11e7-8461-72f3527c5a0c.png)

**Comment by pieandcakes** [comment]
@10manjunath Your screenshot shows you are in run mode and not stopped, therefore the stepping buttons are not enabled. Can you enable logging using `"logging": { "engineLogging": true }` and posting those results? 

Can you post the commandline you are using for compiling? With Cygwin, you need to compile with gcc/g++ that is included within cygwin.

**Comment by pieandcakes** [comment]
The line you highlighted shows that it doesn't have symbols for what you are debugging.
