### ISSUE TITLE
identifier "stderr" is undefined

### ISSUE THREAD

**Issue by rusq** [microsoft/vscode-cpptools#1376]
Hi Team,

Running VSCode on Mac OS X 10.11.6, writing a simple file and getting `stderr` red underlined, and  a message `identifier "stderr" is undefined` when hovering over in the following piece of code:

```c
#include <libgen.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <inttypes.h>

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <milliseconds>\n", basename(argv[0]));
        return 1;
    }
}
```

If I press <kbd>F12</kbd> on `stderr` it successfully shows the proper line in `stdio.h`.

Please let me know if there anything else I can provide.

### System report
<hr>

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.22
better-comments|aar|1.1.3
code-runner|for|0.8.6
configure-c-compiling|ivo|0.2.1
restructuredtext|lex|46.0.0
Go|luk|0.6.70
autoconf|mae|0.0.2
python|ms-|0.9.1
cpptools|ms-|0.14.5

**Comment by sean-mcmanus** [comment]
What are you settings in c_cpp_properties.json? It sounds like your includePath setting is not correct. I'm seeing stderr defined in /usr/include/stdio.h, with /usr/include being in my includePath.

**Comment by rusq** [comment]
Hi @sean-mcmanus,
Thanks for your reply.

For an experiment I created a fresh directory and placed the `usleep.c` there, opened this directory with vscode and it resolved `stderr` without problems.

Thanks for pointing out to `c_cpp_properties.json` file - this helped a lot!

My `includePath` was this:
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1",
                "/usr/local/include",
                "/Library/Developer/CommandLineTools/usr/bin/../lib/clang/8.0.0/include",
                "/Library/Developer/CommandLineTools/usr/include",
                "/usr/include",
                "${workspaceRoot}",
                "${workspaceRoot}/dbvlib/",
<…>
                "/usr/include/sys",                        <<<< CULPRIT!
                "${workspaceRoot}/dbvlib/Http",
            ],
< … >
```
After removing `/usr/include/sys` (probably added it with right click at some point), the `stderr` symbol resolved.

I'll close the issue.
