### ISSUE TITLE
Allow to set default includePath and browse.path in settings.json

### ISSUE THREAD

**Issue by rongjiecomputer** [microsoft/vscode-cpptools#1379]
**Problem**:

Currently `includePath` and `browse.path` can only be set in project-specific `.vscode/c_cpp_properties.json` and this leads to a lot of problems:

1. Have to copy the `c_cpp_properties.json` in every project.
1. Single file cannot have `c_cpp_properties.json`, so no intelliSense at all.
1. A git repo cannot share `c_cpp_properties.json` because some users have very different `includePath` and `browse.path` due to non-default header/library installation.

**Feature request**:

Allow to set default `includePath` and `browse.path` in VSCode `settings.json`.

If `includePath` and `browse.path` are set in both `settings.json` and project-specific `c_cpp_properties.json`, `includePath` and `browse.path` in `c_cpp_properties.json` should have higher precedence, just like `-I` and `/I` flags have higher precedence than `-isysroot` flag and `INCLUDE` environment variable.

It might also make sense to have a separate symbol database for `includePath` and `browse.path` from `settings.json` to avoid re-parsing.

**Comment by sean-mcmanus** [comment]
Yes, we were already planning to do this. ETA maybe February (not sure yet). I think we're tracking this via https://github.com/Microsoft/vscode-cpptools/issues/368 .
