### ISSUE TITLE
When I uninstall reinstall studio code Visual, and then again to install the C\C++ extension, each time the.C file to open the error, the following is the wrong tips:

### ISSUE THREAD

**Issue by songwenshuai** [microsoft/vscode-cpptools#138]
The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by greazer** [comment]
I presume this is a dupe report of the "crashing 5 times in the last 3 minutes?"

**Comment by jgoshi** [comment]
Can you try this when the next version (0.9.0) is released? We fixed a crash and it could be this same issue.

**Comment by jgoshi** [comment]
Version 0.9.0 is schedule for release in the next week or so. If this still repros at that time please reopen this issue.
