### ISSUE TITLE
keep installing for hours...

### ISSUE THREAD

**Issue by dundun163** [microsoft/vscode-cpptools#139]
i wonder how much time does it need

**Comment by delmyers** [comment]
@dundun163

This, unfortunately, likely has to do with connectivity problems, and not with the extension itself. There is currently a workitem tracking adding a feature to vs code to give progress indication for downloading extensions. You can see it here:

https://github.com/Microsoft/vscode/issues/9725

In the meantime, please quit VsCode and try again.
