### ISSUE TITLE
Autoformatting not working on second project folder in workspace

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#1391]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.2.3
cpptools|ms-|0.14.5
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1

---

Repro project: [test.zip](https://github.com/Microsoft/vscode-cpptools/files/1595127/test.zip)

Steps to Reproduce:

1. Unzip attached repro test project zip
2. Open test\0 folder with VSCode
3. Add test\1 folder to workspace in the same VSCode instance
4. Mess with the whitespace in test\0\0.h
5. Autoformat 0.h
6. Notice that autoformatting works
7. Repeat steps 4 and 5 with test\1\1.h
8. Notice autoformat does not work

Reproduces without extensions: Yes/No

**Comment by sean-mcmanus** [comment]
What exactly do you mean by "autoformat"? What settings or commands are you using to enable that?

**Comment by azydevelopment** [comment]
Just the one called 'format' "editor.action.format".

![image](https://user-images.githubusercontent.com/29720335/34480833-8b98df06-ef63-11e7-83c0-d80a973513ba.png)

Or if you have format on save on, you can just save.

I just said 'autoformat' colloquially as in something else is formatting it other than my own typing.

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this bug. I've reproed it. I can't believe no one noticed yet that multi-root formatting is busted. We'll fix it (I'm putting it in the February milestone, but we may release a fix earlier).

**Comment by azydevelopment** [comment]
Thanks and np.

**Comment by sean-mcmanus** [comment]
This is quite bizarre -- our engine returns the correctly formatted code to VS Code, but it's somehow not being used -- looks like it could be a VS Code bug, but the scenario works for typescript.

**Comment by sean-mcmanus** [comment]
It appears to be a VS Code bug: https://github.com/Microsoft/vscode/issues/42119 . I'll keep this open to track the issue.

**Comment by azydevelopment** [comment]
This still broken? It prevents me from effectively using the workspace since I need to open up all folders separately in order to format before committing to source control.

**Comment by sean-mcmanus** [comment]
@azydevelopment Yeah, sorry about that. I'm still waiting to hear back from @dbaeumer on what the next step should be. I debugged the VS Code javascript that was mentioned but I didn't see any issues on our end. The multi-root formatting code in question is open source so should be debuggable if anyone wants to investigate themselves -- our closed source code is returning the JSON results shown in our debug protocol output (which appears correctly formatted).

You might want to try using the clang-format extension as a workaround (and setting "C_Cpp.formatting" to "Disabled"). That seemed to work for me.

**Comment by dbaeumer** [comment]
I added comments to https://github.com/Microsoft/vscode-languageserver-node/issues/305. As said I can't reproduce this using our multi root / multi server example so a little debugging help or and example showing the problem is highly appreciated.

**Comment by sean-mcmanus** [comment]
@azydevelopment I tried the latest VS Code Insiders (1.23.0, not 1.22.1) and multi-root formatting is working. If one of your workspace's folder names ends with a subset of another (e.g. "folder" and "folder1"), then you'll hit another bug (https://github.com/Microsoft/vscode-cpptools/issues/1792 ).

**Comment by azydevelopment** [comment]
Thanks a lot guys! I've been pretty excited to use this forever.

Edit: Confirmed working :)
