### ISSUE TITLE
Make custom visualization (.natvis) development user friendly

### ISSUE THREAD

**Issue by sersajur** [microsoft/vscode-cpptools#1394]
I use cpptools under MacOS Sierra, trying to setup custom visualizer (.natvis) for my classes.
And I am wondering if there is:
1) a way to enable autocompletion of .natvis's tags?
2) an approach to update .natvis file and see effect during the single debug session? (Now I have to stop debug session and launch it again in order to see updated effect)

**Comment by pieandcakes** [comment]
@sersajur I'm in the process of adding the schema based on this request: https://github.com/Microsoft/vscode-cpptools/pull/1400

You can find documentation [here](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects) for the Visual Studio implementation. We have a subset of those features but that should be able to help you.

>2.an approach to update .natvis file and see effect during the single debug session? (Now I have to stop debug session and launch it again in order to see updated effect)

If you file an issue over on the [MIEngine](https://github.com/Microsoft/MIEngine/issues) page requesting that, it might be something that can be considered for a future release but isn't something we support today.

**Comment by pieandcakes** [comment]
The schema has been added to this repository under Documentation. Hopefully that helps.
