### ISSUE TITLE
Cannot disable modifications to gitignore file

### ISSUE THREAD

**Issue by AndrewCarterUK** [microsoft/vscode-cpptools#1397]
The following line keeps getting added to my gitignore file:

```
.vscode/c_cpp_properties.json
```

How can I disable this?

I have properly configured gitignore files for all my projects, so my IDE constantly modifying them whenever I open a project is a bit tiresome.

I've had a look at the different configuration options, but nothing jumped out at me.

Thanks very much!

**Comment by sean-mcmanus** [comment]
Our C/C++ extension doesn't modify any .gitignore files. Can you find out who is? The problem doesn't go away when you disable our extension, does it?

**Comment by michelleangela** [comment]
We need more information to further help with this issue. Please verify whether the issue still persists when the C/C++ extension is disabled. If the issue still persists, please re-open the issue and reply with additional information that can help us investigate your issue.
