### ISSUE TITLE
Feature: Optionally filter intellisense errors from problems pane

### ISSUE THREAD

**Issue by lurium** [microsoft/vscode-cpptools#1398]
OS: Windows 10
VSCode 1.19.1 
CPP 0.14.5

The extension often produces several 'problems' through its intellisense engine when viewing a file. However, these are not often useful because the intellisense compiler is not the same compiler used in a C++ project (gcc, clang, etc)

Is there a way to optionally filter intellisense errors from the problems pane in VSCode?

Thank you.

**Comment by bobbrow** [comment]
Does toggling this setting do what you want?

![image](https://user-images.githubusercontent.com/12818240/34494095-9a402a7e-efa3-11e7-9021-04546b5f37d1.png)

**Comment by lurium** [comment]
No, I'd still like to see the squiggles; I just don't want to see these
errors in the Problems window because I'd like that to contain actual
compilation errors only

**Comment by sean-mcmanus** [comment]
Maybe we could send a Diagnostic with no text, but I don't know if VS Code would respond the way we want (squiggles but no Problems). The API implies that the message is required and therefore it might not work without a VS Code change: https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#diagnostic .

**Comment by sbrw** [comment]
I put a request for this to the vscode-team but they closed it. Really annoying to get intellisense problems mixed with the compiler output. Specially if I have several folders (multi-root). I may want to focus on one folder by building it with the compiler and ignore problems in all other folders.

**Comment by sean-mcmanus** [comment]
@sbrw Yeah, I recall other users have complained about errors from different sources getting mixed up all together. Why did VS Code close the issue? Maybe more people just need to complain more. The Diagnostic we return has a "source" (although we don't currently set it), so it seems like users should be able to filter out a source, although that would get rid of our squiggles too probably. VS 2017's Error List has the ability to sort/filter by the source (IntelliSense versus compiler).

**Comment by sbrw** [comment]
Here is my original issue put to the CPP-team:
https://github.com/Microsoft/vscode-cpptools/issues/1286

I was recommended to get in touch with the vscode-team. Here is the link:
https://github.com/Microsoft/vscode/issues/39604

Guess I was a bit unclear in the request, so they suggested me to file yet another request for a problem filter, which I have not...

**Comment by Colengms** [comment]
It looks like this is was addressed by https://github.com/microsoft/vscode/pull/83797 , which added filtering to the problems pane.

**Comment by sean-mcmanus** [comment]
@Colengms No, doesn't work for me. I can't filter out the C/C++ errors, and also our errors are not all labeled with "C/C++" as the source as well.

**Comment by Colengms** [comment]
@sean-mcmanus  The original issue appears to have been addressed.  There is a way to filter problems, by whatever text is contained in them.  If there is additional work that might allow our issues to be _better_ filtered, perhaps you could update the title to reflect what work needs to be done, or open a more specific issue?

**Comment by sean-mcmanus** [comment]
Okay, it sounds like the user could use a filter like "gcc" or whatever "source" they're using in their problemMatcher.
