### ISSUE TITLE
Error output not showing in Debug Console

### ISSUE THREAD

**Issue by charlie-rbchd** [microsoft/vscode-cpptools#140]
I can't seem to be able to see the error output of my programs when debugging inside of Visual Studio Code. I would normally expect the output from `OutputDebugString` to be redirected to the Debug Console.

I'm compiling using Mingw on Windows 10 and I'm debugging with GDB. The Debug Console shows the standard output and GDB's output properly. but the all of the output done using `OutputDebugString` is nowhere to be found. Am I missing something or is this not implemented yet?

Thanks!

**Comment by jacdavis** [comment]
It is not implemented and needs changes to vscode before it can be implemented. We need the ability to also redirect stdin of your app as well. In the meantime, please use the externalConsole:true property to get a new console window for your application.

**Comment by charlie-rbchd** [comment]
Ok, thanks for letting me know, I will be using the externalConsole in the meantime.
