### ISSUE TITLE
there is problem with color. 

### ISSUE THREAD

**Issue by JarmoHu** [microsoft/vscode-cpptools#1402]
I have defined "uchar" "unsigned char", but there is no color.
![image](https://user-images.githubusercontent.com/34189831/34523699-83f8a080-f0d3-11e7-9b8e-1d9545d1c5e5.png)

but "uint" is well.

![image](https://user-images.githubusercontent.com/34189831/34523804-f137a510-f0d3-11e7-81af-bc210db04213.png)

**Comment by bobbrow** [comment]
Hi @hustarbor, #230 is currently tracking colorizer improvements.  I will close this issue as a duplicate.
