### ISSUE TITLE
Build output stucks in terminal

### ISSUE THREAD

**Issue by alekseyt** [microsoft/vscode-cpptools#1406]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.4.0-104-generic (Ubuntu 14.04.5)
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|7.2.0
nightswitch-lite|gha|2.0.3
Go|luk|0.6.70
cpptools|ms-|0.14.5
shader|sle|1.1.2
cmake|twx|0.0.17
code-navigation|vik|0.2.0
vscode-todo-highlight|way|0.5.11
lua-for-vscode|xxx|0.0.23

(1 theme extensions excluded)

---

This is a repost of issue i've originally reported as Microsoft/vscode#41165. I'm not sure where this issue belongs to, but i couldn't reproduce it with C/C++ extension disabled. tl;dr: multithreaded CMake build on ccache hangs embedded terminal output.

Steps to Reproduce:

1. Start build (Run Build Task)
2. Observe terminal output

Result 1: terminal output hangs somewhere during build process (doesn't always reproduce)
Result 2: actual build continues in background ("Building..." appears in status bar, then disappears after some time)

3. Repeat steps 1-2

Result 3: terminal output doesn't change, it stays in "hanged" state from previous build
Result 4: build presumably executes in background, "Building..." appears in status bar, just no output in terminal

When it hangs, it always does that on the same warning on the same file: ``warning: ‘...[skip]...’ defined but not used [-Wunused-function]`` (coming from GCC 4.8.5). To unstuck terminal i have to either restart vscode or click on terminal and press Enter to make build output disappear, then i can restart build and output to terminal correctly appears on the screen.

I don't have build-related extensions installed, cmake extension listed in header is only for syntax highlighting, build runs in shell with ``make -j 4`` or so i think. But after filing issue to Microsoft/vscode i tried to reproduce this issue with all extensions (manually) disabled and i couldn't. If i reenable C/C++ extension (all other extensions remains disabled) when i can reproduce this issue again.

One other thing is that i'm running multithreaded build on ccache and multiple parallel jobs are outputting to terminal very fast, i couldn't hang it with ``make -j 1``.

As i said, i'm not sure where this issue comes from, but it doesn't reproduce with C/C++ extension disabled, so i'm guessing this is somehow "*caused-by-extension".

My tasks.json:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "make -j 4",
            "options": {
                "cwd": "${workspaceRoot}/build"
            },
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

**Comment by pieandcakes** [comment]
AFAIK We don't do anything within the extension to handle `tasks.json` and build commands, so I would start with VS Code itself ( as you have done ) or looking at the toolchain. Both the terminal and processing the `tasks.json` is handled by VSCode.

**Comment by alekseyt** [comment]
I'm closing this issue because it was closed in vscode and i can't reproduce this anymore.
