### ISSUE TITLE
annoying c/cpp auto completion

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-cpptools#141]
_From @netjune on August 8, 2016 2:9_
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

insert the following c code in c file:
`int i;`

On the second 'i' char, there was completion with prefix 'i'. It is OK.
On the last ';' char, there should not be auto completion, BUT there was (with all the symbols as candidates). Then I can't hit ENTER cause it will selection the first completion item.

By the way, how can I set the minimal prefix length to begin the auto completion?

_Copied from original issue: Microsoft/vscode#10282_

**Comment by jrieken** [comment]
_From @aeschli on August 8, 2016 7:20_

@netjune Is this with the c/c++ extension?

**Comment by jrieken** [comment]
_From @netjune on August 9, 2016 1:0_

Yes, it must be. I only installed the following two extensions:
(1) c/c++ (0.8.1)
(2) Toggle Header/Source (0.1.2)

**Comment by greazer** [comment]
Thanks for the report. The aggressiveness of the autocomplete will be fixed in our next release. With regard to minimal prefix length, there is currently no way to set this. After the we fix the aggressive behavior, see if you still feel it's necessary. If so, please feel free to request it again.

**Comment by sridmad** [comment]
The aggressive auto complete should be fixed in 0.9.0 of the extension.
