### ISSUE TITLE
preference to click through intellisense info bubbles

### ISSUE THREAD

**Issue by ad8e** [microsoft/vscode-cpptools#1413]
- VSCode Version: 19.1
- OS Version: Windows 8.1
- C/C++: 0.14.5

On mouseover of code, an intellisense bubble appears, like so:

![bubble](https://user-images.githubusercontent.com/19739817/34638189-a19bea44-f294-11e7-9587-6c2161125a73.png)

These bubbles don't do much when clicked, but they get in my way when I try to click things under them. I would prefer if clicks passed through these bubbles, or if the bubbles disappeared when the mouse leaves the original text (there seems to be special code to persist the bubble when the mouse transfers to it). The info in the bubbles is useful, but the click obstruction is not.

**Comment by sean-mcmanus** [comment]
Please file your issue at https://github.com/Microsoft/vscode/issues ? Our extension has no control over the UI behavior of the tooltip. We just send the info to VS Code. I have also been annoyed by the tooltip blocking a text area I need to type in, but the behavior is shared by all languages in VS Code.
