### ISSUE TITLE
How can i see the value of elements in STL containers or arrays in debug

### ISSUE THREAD

**Issue by philong6297** [microsoft/vscode-cpptools#1414]
For example with `std::vector<std::vector> v(10,vector<int>(5,-1))`. When I run the debug with GDB, i can only see the address of the first and last element. When i expand the `_M_start_` or `_M_finish_`, it still show the address, not the value i need to see. How can i see the value of elements in STL or arrays in debug:
![capture](https://user-images.githubusercontent.com/29605147/34639142-7ef1d332-f30c-11e7-852c-53a4f4c2351e.PNG)

**Comment by Gruntfuggly** [comment]
You need to set up python pretty printers for C++ in the .gdbinit file.

Have a look here:
https://sourceware.org/gdb/wiki/STLSupport

**Comment by pieandcakes** [comment]
@philong6297 Also make sure you have the following block in your `launch.json` to enable pretty printing:
```
"setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
```

**Comment by andyneff** [comment]
For the record, you need **both** of those, and they can both be wrapped in the `setupCommands`

Modern OSes like Fedora and Ubuntu include the svn submodule, and you don't need to download them separately. For example, in Ubuntu 18.04

```
"setupCommands": [
    {
        "description": "Test",
        "text": "python import sys;sys.path.insert(0, '/usr/share/gcc-8/python');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
        "ignoreFailures": false
    },
    {
        "description": "Enable pretty-printing for gdb",
        "text": "-enable-pretty-printing",
        "ignoreFailures": true
    }
]
```

**Comment by nealYangVic** [comment]
not sure why
`{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "(lldb) Launch",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder}/helloworld.out",
        "args": ["-arg1", "-arg2"],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": true,
        "MIMode": "lldb",
        "customLaunchSetupCommands": [
          {
              "description": "Test",
              "text": "python import sys;sys.path.insert(0, '/Users/mingyeyang/gcc/python');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
              "ignoreFailures": false
          },
          {
              "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": true
          }
        ],
        "logging": {
          "trace": true,
          "traceResponse": true,
          "engineLogging": true
        }
      }
    ]
  }`
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (476) STDERR: error: 'logout' is not a valid command.\n"},"seq":44}
1: (476) STDERR: error: 'logout' is not a valid command.
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (477) STDERR: error: Unrecognized command 'logout'.\n"},"seq":46}
1: (477) STDERR: error: Unrecognized command 'logout'.
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.61023.1","VS.Diagnostics.Debugger.HostVersion":"14.0.61023.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.ErrorCode":1005,"VS.Diagnostics.Debugger.Launch.IsError":true}},"seq":48}
--> R (launch-2): {"type":"response","request_seq":2,"success":false,"command":"launch","message":"Unable to start debugging. Specified argument was out of the range of valid values.\nParameter name: options.TargetArchitecture","body":{"error":{"id":1005,"format":"Unable to start debugging. Specified argument was out of the range of valid values.\nParameter name: options.TargetArchitecture"}},"seq":50}

**Comment by AniruddhaHumane** [comment]
How do I do the same for Windows?

**Comment by harrism** [comment]
> For the record, you need **both** of those, and they can both be wrapped in the `setupCommands`
> 
> Modern OSes like Fedora and Ubuntu include the svn submodule, and you don't need to download them separately. For example, in Ubuntu 18.04
> 
> ```
> "setupCommands": [
>     {
>         "description": "Test",
>         "text": "python import sys;sys.path.insert(0, '/usr/share/gcc-8/python');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
>         "ignoreFailures": false
>     },
>     {
>         "description": "Enable pretty-printing for gdb",
>         "text": "-enable-pretty-printing",
>         "ignoreFailures": true
>     }
> ]
> ```

Any idea why @andyneff 's suggestion can't be rolled into vscode-cpptools so that it works out of the box? I've been struggling with debugging STL in vscode for a while now, and this suggestion is going to make it a lot easier.

**Comment by pieandcakes** [comment]
@WardenGnaw can we see if we can get a test matrix with @andyneff's suggestion above and wee where it works and where it doesn't? we would need to at the bare minimum set up Arch, Ubuntu, Centos and WSL1/2

**Comment by yanglr** [comment]
For **Windows**:
If you only see memory address for STL containers when debugging, you probably used x64 Windows.

I found one valid solution, when installing MinGW in x64 Windows, install `i686 (win32)` version (the bottom of this comment gives its official download link) of MinGW instead of `x86_64` version, see below:

![pretty-printing-not-work-with-MinGW GDB-solution](https://user-images.githubusercontent.com/3152813/108173684-6797ac80-7139-11eb-9d03-9eee32578458.png)

**win32 version of MinGW download:**
[i686-posix-dwarf](https://mmbizurl.cn/s/Xtn6Gu8sa)

More details, see:
<https://stackoverflow.com/a/66238128/6075331>

**Comment by bcaddy** [comment]
I'm on Ubuntu 20.04 and none of the suggestions here are having any effect at all. Any suggestions?

**Comment by hansfbaier** [comment]
On Ubuntu 22.04, this seemed to work:
```json
            "setupCommands": [
                {
                    "description": "Test",
                    "text": "python import sys;sys.path.insert(0, '/usr/share/gcc/python');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
                    "ignoreFailures": false
                },
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
```

**Comment by sajedehkebriti** [comment]
> hansfbaier

I'm using this set up in launch.json file. Before copying this command, I was seeing only implementation details of std::set but now it shows me {...} basically no information. I'm attaching the photo of what I'm seeing in debugger. I'm using Ubuntu 22.04.

![Screenshot from 2023-05-20 16-13-04](https://github.com/microsoft/vscode-cpptools/assets/118686973/2548fcce-6a4a-48bb-878c-3b7b7605d319)

**Comment by hansfbaier** [comment]
@sajedehkebriti You need the `libstdc++6` package to be installed

**Comment by sajedehkebriti** [comment]
> @sajedehkebriti You need the `libstdc++6` package to be installed
I have already installed this package.

**Comment by saifeiLee** [comment]
> > > hansfbaier
> > 
> > 
> > I'm using this set up in launch.json file. Before copying this command, I was seeing only implementation details of std::set but now it shows me {...} basically no information. I'm attaching the photo of what I'm seeing in debugger. I'm using Ubuntu 22.04.
> > ![Screenshot from 2023-05-20 16-13-04](https://user-images.githubusercontent.com/118686973/239712706-2548fcce-6a4a-48bb-878c-3b7b7605d319.png)
> 
> the same question in gdb 13.2 use gdb init from [https://github.com/cyrus-and/gdb-dashboard]. did u solve this problem?

Same here.

**Comment by saifeiLee** [comment]
> > > hansfbaier
> > 
> > 
> > I'm using this set up in launch.json file. Before copying this command, I was seeing only implementation details of std::set but now it shows me {...} basically no information. I'm attaching the photo of what I'm seeing in debugger. I'm using Ubuntu 22.04.
> > ![Screenshot from 2023-05-20 16-13-04](https://user-images.githubusercontent.com/118686973/239712706-2548fcce-6a4a-48bb-878c-3b7b7605d319.png)
> 
> the same question in gdb 13.2 use gdb init from [https://github.com/cyrus-and/gdb-dashboard]. did u solve this problem?

You can change your compiler from `clang++` to `g++`. 
Work for me.

**Comment by dvirtz** [comment]
> @WardenGnaw can we see if we can get a test matrix with @andyneff's suggestion above and wee where it works and where it doesn't? we would need to at the bare minimum set up Arch, Ubuntu, Centos and WSL1/2

@pieandcakes any progress on that front?

**Comment by joyWang-77** [comment]
> How do I do the same for Windows?

do you find how to do it for windows

**Comment by delicacyyy** [comment]
Mine on ArchLinux
```json
{
    "description": "Test",
    "text": "python import sys;sys.path.insert(0, '/usr/share/gcc-14.1.1/python/');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
    "ignoreFailures": false
}
```

![Image](https://github.com/user-attachments/assets/f38fb6b5-8cc8-4981-87d6-dbc7e5cedd46)

**Comment by hansfbaier** [comment]
@delicacyyy  Thanks!
