### ISSUE TITLE
Can I change code formatting style?

### ISSUE THREAD

**Issue by DemoCrazer** [microsoft/vscode-cpptools#1416]
If I put following code and press enter in Visual Studio,
`if(a < b){`

code is formatted automatically like this:
```
if (a < b) {
}
```

Blanks are made in front/back of parenthesis. But no blanks are made in VS Code. If I click `Format Document` option, opening brace goes down to next line so that's not what I want.

Is there any way to change auto-formatting style?

**Comment by sean-mcmanus** [comment]
Yeah, we support modifying the formatting behavior via clang-format. You can either add a .clang-format file, or change the style directly, via something like `"C_Cpp.clang_format_style": "{ BasedOnStyle: LLVM}"`. See http://releases.llvm.org/5.0.0/tools/clang/docs/ClangFormatStyleOptions.html . Are you able to get formatting working as you desire?

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
