### ISSUE TITLE
How to pretty print std::string in lldb debuggin on macOS

### ISSUE THREAD

**Issue by gabyx** [microsoft/vscode-cpptools#1417]
System: macOS, with installed `brew install llvm`

and compiling with the following env variables by a cmake configuration

```
export PATH="/usr/local/opt/llvm/bin:$PATH"
export CC="/usr/local/opt/llvm/bin/clang"
export CXX="$CC++"
export LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1/"
```

I used the following clang flags:
```
-g3 -D_GLIBCXX_DEBUG -fno-omit-frame-pointer -fsanitize=leak -fsanitize=address
```

When I start the application with the launch settings:
```
{
            "name": "(lldb) ExecutionGraph-CefApp",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/gui/executionGraphGui/Debug/executionGraphGui.app/Contents/MacOS/ExecutionGraphGui",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb"
}
```
I can really well debug the application but, the variables especially the `std::string`s are not correctly display (strange de/encoding?):
![bildschirmfoto 2018-01-07 um 19 52 50](https://user-images.githubusercontent.com/647437/34652880-93a8b402-f3e4-11e7-976d-f91ef04b5f32.png)

I see that LLDB loaded the following std-libraries which is correct I think:
```
Loaded '/usr/local/opt/llvm/lib/libc++.1.dylib'. Symbols loaded.
Loaded '/usr/local/opt/llvm/lib/clang/5.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib'. Symbols loaded.
```

Is there some remedy for this behavior?
Thanks a lot!

**Comment by pieandcakes** [comment]
@gabyx This is the underlying decoding for lldb for a `std::string`. lldb uses python to try and format the string (which is what is in `requestUrl` in your example) but if you expand it its the underlying data structure that `std::string` uses. This is expected and normal behavior. We are asking `lldb` to format the string and we are not doing anything else to the string that `lldb` gives us. 

What are you expecing to show up?

**Comment by gabyx** [comment]
A correct string like (filePath) "http:/asdasd/asdd/"

**Comment by gabyx** [comment]
it seems that I should build the lldb my self when I use the custom tool chain I think

**Comment by pieandcakes** [comment]
the python files should be in `~/.vscode/extensions/ms-vscode.cpptools-<version>/debugAdapters/lldb/lib/python2.7/site-packages/lldb/formatters/` if you want to see why it isn't handling it correctly.

Does it show non-url strings correctly? I've tried it here with the extension and I see the regular string.

**Comment by gabyx** [comment]
nono, all strings are like this, I think lldb gets a wrong symbol in memory and thats why lldb (not compiled, the one from apple, is the wrong one with the install brew llvm)
thx, cool, I will have a look

I will try to build `brew install llvm --with-toolcain --with-lldb`
which I think should solve the problem?

**Comment by gabyx** [comment]
Ok, I am debugging now with the build lldb from `brew install llvm --with--lldb`
and the Problem still persists... Need to look into the python script

**Comment by gabyx** [comment]
Can it be that the formatters are outdated for the standart library built with llvm 5.0.1?

**Comment by pieandcakes** [comment]
@gabyx if you change that, you need to set the `"miDebuggerPath"` to the `lldb-mi` that you installed. We use the `mi` interface to communicate with lldb. 

> Can it be that the formatters are outdated for the standart library built with llvm 5.0.1? 

that may be the case but since they are scripts, you might be able to update the formatters that you have with the ones you just installed. Let me know if that works and we can update it.

**Comment by gabyx** [comment]
The debugger is found (its in my system path on top), and I can debug the application, however, the output in the console
looks weird, wrong formatted?
```
Warning: Source file '/Users/gabrielnuetzi/Desktop/ExecutionGraph/gui/executionGraphGui/cefapp/FileSchemeHandlerFactory.cpp' is newer than module file '/Users/gabrielnuetzi/Desktop/ExecutionGraph/build/gui/executionGraphGui/Debug/executionGraphGui.app/Contents/MacOS/ExecutionGraphGui'.
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
=thread-selected,id="22"
@"FileSchemeHandlerFactory::Create \"executionGraph/index.html\"\r\n"
```

When I use a simple  main.cpp and debug it:
```bash
#!/bin/bash
cat << EOF > main.cpp
#include <iostream>
#include <string>

int main()
{
    std::string a="hello world";
    std::string b=u8"hello world";
    std::cout << a << std::endl;
}
EOF

clang++ -g -std=c++17 main.cpp -o main
echo -ne "breakpoint set --file main.cpp --line 7\nrun\nfr v a\nfr v b" > runFile
lldb ./main -s runFile
```
**output**:
```bash
(lldb) fr v a
(std::__1::string) a = "hello world"
(lldb) fr v b
(std::__1::string) b = "hello world"
```
I can see the strings, what I am doing wrong...?
In vscode I only see garbage? May be due to compiler flags?

**Comment by gabyx** [comment]
Its solved, it is related to "-fsanitize=address" with clang5.0.1. With clang 7.0 Debugging of std::string works!

**Comment by pieandcakes** [comment]
@gabyx good to know. Is that a compiler flag that was set by default or something you set?

**Comment by gabyx** [comment]
@pieandcakes: No, I set that by a Cmake Configuration: I use the Cmake Tool extension... vector-of-bool (,-))

**Comment by pieandcakes** [comment]
ok Good to know. thank you

**Comment by gabyx** [comment]
From Jim Ingham:

The address sanitizer does quite a number of code transformations, and if any of these transformations moves a variable to a different location, the debug information has to be fixed as well.  There were a bugs in this part of the sanitizer in its original version, many of which have been fixed.  That's likely why 5.0.1 had problems you didn't see in 7.0.  If you see any more bad variable printing in the debugger that only show up with this or other sanitizers on, please file them with llvm.org bug tracker (http://bugs.llvm.org).

Jim

**Comment by ourarash** [comment]
> brew install llvm --with-toolcain --with-lldb

This command doesn't work anymore.

`Error: invalid option: --with-toolcain`

**Comment by gabyx** [comment]
its `--with-toolchain`
