### ISSUE TITLE
"cannot open source file" on Mac GCC 7.2.0

### ISSUE THREAD

**Issue by ZZYSonny** [microsoft/vscode-cpptools#1418]
I've got a similar issue like https://github.com/Microsoft/vscode-cpptools/issues/1358 on VSCode 1.19.1, C++ plugin 0.14.5, GCC@7 from homebrew
I think I've followed everything on that, but I still got such problem. What should I do?
![2018-01-08 9 02 28](https://user-images.githubusercontent.com/28442838/34672190-81375092-f4b8-11e7-9b15-338edf4ae9a0.png)
![2018-01-08 9 02 44](https://user-images.githubusercontent.com/28442838/34672191-82bc7ea6-f4b8-11e7-9273-158516648ec7.png)
![2018-01-08 9 12 05](https://user-images.githubusercontent.com/28442838/34672213-9bf61832-f4b8-11e7-95d4-a144253599aa.png)

**Comment by bobbrow** [comment]
Your "Mac" configuration looks correct, but your first picture shows you are actually attempting to use the "Win32" configuration.  Click on the "Win32" label in the lower right hand corner of the status bar and change it to "Mac" then it should start working.

**Comment by sean-mcmanus** [comment]
I assume you manually changed the config to Win32, right? We should be defaulting to Mac.

**Comment by ZZYSonny** [comment]
Oh, That works! Thank you.
