### ISSUE TITLE
Standard library (cout, cin etc.) not being found/recognised- Linux, g++

### ISSUE THREAD

**Issue by PMcca** [microsoft/vscode-cpptools#1421]
I'm trying to run a simple "Hello World" program, but std :: cout isn't being recognised. 
Here is my current .json config file:
`{

            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "/usr/include/c++/6.3.0",                
                "/usr/include/c++/6",
                "/usr/include/x86_64-linux-gnu/c++/6",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "/usr/include/c++/6.3.0",
                    "/usr/include/c++/6",
                    "/usr/include/x86_64-linux-gnu/c++/6",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }`
This fixed the issue where #include <iostream> and other standard library headers were not being found, but now I'm getting the error "namespace "std" has no member "cout"".

What could I be doing wrong?

**Comment by sean-mcmanus** [comment]
Hmm, it works for me. Can you run "g++ -Wp,-v -E -xc -x c++ /dev/null" and make sure your system paths match? It's also possible some required defines may be missing.

**Comment by PMcca** [comment]
@sean-mcmanus  Sorted- seems a path must not have included. Thanks!
