### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by gitdust** [microsoft/vscode-cpptools#1424]
### Environment data
VS Code version:1.19.1
Window 7 Professional Service Pack 1

### Steps to reproduce
React component use react-redux connect decorator syntax
![_20180109172029](https://user-images.githubusercontent.com/15882116/34713504-75036b54-f561-11e7-9950-85c23f995bab.png)

### Expected behavior
nothing happened

### Actual behavior
keep showing this below:
![_20180109171835](https://user-images.githubusercontent.com/15882116/34713433-307a736a-f561-11e7-84c3-adac1135a1ab.png)
and the error code is:
![_20180109172338](https://user-images.githubusercontent.com/15882116/34713666-e3c09c38-f561-11e7-84d5-3093f7e026c0.png)

**Comment by sean-mcmanus** [comment]
What extension is causing this? cpptools? What is the version?

**Comment by gitdust** [comment]
I do not really have any clue about it.
I have same extensions installed on both Win7 Professional version and Win7 Ultimate version.
Only on Win7 Professional version cause that error.
Maybe it's my OS problem-_-!!!

**Comment by sean-mcmanus** [comment]
Does it repro with our extension disabled? If so, it sounds like a VS Code issue: https://github.com/Microsoft/vscode/issues

**Comment by gitdust** [comment]
Thank you very much,you can close this issue,sorry to borther you.
