### ISSUE TITLE
Feature Request - IntelliSense for Peek/Go to Definition/Declaration

### ISSUE THREAD

**Issue by hbp06236** [microsoft/vscode-cpptools#1427]
As described on the [documentation](https://code.visualstudio.com/docs/languages/cpp#_peek-definition) page VS Code shows several files which contain a definition of the file. However the IntelliSense Engine is able to determine the correct function. Would it be possible to open the recognized file?

![vscodecpp](https://user-images.githubusercontent.com/35260766/34720269-5e007b36-f53e-11e7-902f-3d90ce0b632c.png)

Currently using
* VS Code: Version 1.19.1 (non-Insider)
* C/C++ extension: 0.14.5

**Comment by bobbrow** [comment]
Yes, this is on our backlog. You can reference issue #255 which is another scenario that will be enabled once we get goto definition implemented in the new IntelliSense engine.
