### ISSUE TITLE
Add support for GCC Linker Script files

### ISSUE THREAD

**Issue by tehKaiN** [microsoft/vscode-cpptools#1431]
Currently, if I open linker script (`.ld`) I get no syntax highlighting. Also, those files allow including other linker scripts so having ctrl+click navigation between them would also be helpful.

**Comment by sean-mcmanus** [comment]
That seems like it may be outside the scope of the C/C++ extension and it might be better included as part of another extension. Do you know what other tools implement this .ld support?

**Comment by tehKaiN** [comment]
Currently, there are no vscode extensions supporting .ld syntax highlighting, linting etc. I've found some basic [extension for Atom](https://atom.io/packages/language-linkerscript) but I guess it lacks `INCLUDE` navigation. Also vim supports it, but I would like not to use it. Neither Notepad++ nor NXP's Eclipse distro supports highlighting, so that would be some kind of advantage :)

**Comment by TheNetAdmin** [comment]
I've just published a [LinkerScript](https://github.com/TheNetAdmin/vscode-linkerscript) **vscode extension**, based on `TmLanguage`.

This extension is sufficient for me, and is developed with respect to [GNU Linker Script](https://sourceware.org/binutils/docs/ld/Scripts.html). Could to better with Abstract Syntax Tree or Language Service, but I currently do not have time for that. 

Here is a preview.

![Imgur](https://i.imgur.com/maONwsM.png)

**Comment by bobbrow** [comment]
Closing this feature request as this is out of scope for our extension.  Thanks @TheNetAdmin for publishing an extension that handles this file type!
