### ISSUE TITLE
Ignore suspected compile errors on a per line basis

### ISSUE THREAD

**Issue by chrisckc** [microsoft/vscode-cpptools#1434]
Is there a specially formatted comment than can be placed above a line of code to prevent any suspected C++ compile errors from appearing in the problems panel? Other extensions provide this facility such as the TSLint extension.

I want to keep the errorSquiggles setting enabled, just ignore certain errors that are not actually errors when compiled by the avr compiler. There is code in the avr libs that calls into assembly language and causes issues with the intellisense.
Thanks

**Comment by sean-mcmanus** [comment]
Not currently. It's possible we could add a code action that allows disabling of all error messages of a particular type in a file (saving the disabling to the workspace settings). Using a range/lines or based on comments/pragmas would be more difficult.

**Comment by chrisckc** [comment]
I think it would be worth implementing because vscode is great IDE and people who want to use it for C/C++ would benefit from this.
It seems that others are having similar issues after a quick look through issues list.
VSCode with this extension and the Arduino extension can provide a great alternative to the basic Arduino IDE and will attract the community if this and other issues can be resolved.
(setup of the correct includePath and browse.path lists was quite involved, requiring much digging through the libs)

**Comment by sean-mcmanus** [comment]
I just found a way to cause a chunk of code causing errors to be ignored by our IntelliSense compiler:
`#ifndef __INTELLISENSE__
// code that generates an error squiggle
#endif`

Is that sufficient?
