### ISSUE TITLE
IntelliSense engine is not responding

### ISSUE THREAD

**Issue by menting311** [microsoft/vscode-cpptools#1437]
Extension | Author (truncated) | Version
-- | -- | --
cpptools | ms- | 0.14.5

Steps to Reproduce:

Fresh install of VS code, only cpptools extension installed
Set all needed include paths to clear all squiggles.
Start typing cpp object and hit '.', this is where I expect auto complete suggestions. I do get suggestions when I type one more letter, but it is showing all symbols, not just those that match the type of object I am using.
In the output window of VS code I see this everytime I expect a auto complete suggestions:
Failed to read response from server: 4
IntelliSense engine is not responding. Using the Tag Parser instead.
Failed to send request to server: 17
IntelliSense client has disconnected from the server - D:\REPOSITORY\WMS\SRC\HUB_REQ_TOTALS.CPP

In the log file (vscode.cpp.log.10300.txt) it seems to get cutoff when writing to the file. It starts with....
Log initialized. Verbosity level = 7
handle_compile
handle_change
changes(1) range [0, 0], cursor [4294967295]
handle_quick_info
edge::host - open file: D:\REPOSITORY\WMS\SRC\HUB_REQ_TOTALS.CPP
edge::host - open file: D:\REPOSITORY\WMS\CONTROLLER\HUBSBASED.HPP
edge::host - open file: D:\REPOSITORY\WMS\CONTROLLER\BASE.HPP
edge::host - open file: D:\REPOSITORY\WMS\LIB\DAL\HUBS_FWD.HPP
edge::host - open file: D:\REPOSITORY\WMS_VS_PROJECTS\3RD_PARTY_LIBS\BOOST_1_34_1\BOOST\FUNCTION.HPP
edge::host - open file: D:\REPOSITORY\WMS_VS_PROJECTS\3RD_PARTY_LIBS\BOOST_1_34_1\BOOST\PREPROCESSOR\ITERATE.HPP
.....

Then about 1,000 lines of similar output, then finishes with:
.....
edge::host - open file: D:\REPOSITORY\WMS_VS_PROJECTS\3RD_PARTY_LIBS\BOOST_1_34_1\BOOST\FILESYSTEM\CONVENIENCE.HPP
edge::host - open file: C:\USERS\TMENTING\APPDATA\LOCAL\LXSS\ROOTFS\USR\INCLUDE\C++\5\STACK
edge::host - open file: C:\USERS\TMENTING\APPDATA\LOCAL\LXSS\ROOTFS\USR\INCLUDE\C++\5\BITS\STL_STACK.H
edge::host - open fi

Is there anything else I could provide to figure out what is happening?

**Comment by sean-mcmanus** [comment]
It appears the Microsoft.VSCode.CPP.IntelliSense.Msvc.exe is crashing and falling back to the tag parser. If you can enable local dmps on Windows (https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx) and send us the top few lines of the crashing thread or the dmp that would help. Or a repro.

**Comment by menting311** [comment]
I made the registry changes discussed in that article as you can see in the screen shot. But no logs are showing up. What am I doing wrong?
Is there really no better way to get logs without changing registry??
![reg_ss](https://user-images.githubusercontent.com/1495537/34851492-d945bd8a-f6ef-11e7-87d4-a44c117f7a45.JPG)

**Comment by sean-mcmanus** [comment]
Oops, sorry. I forgot the VS Code does something tricky to suppress local dmps for our processes when they crash.

You would need to attach a debugger before the crash (not sure if enabling just in time debugging works, VS Code might interfere with that too).

We don't have much logging in the IntelliSense process (you appear to have found our hidden logging).

It's probably crashing in our IntelliSense parser code. We're working to get our parser code updated for February which will have some crash fixes.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
