### ISSUE TITLE
Syntax highlighting for template class & user-defined type

### ISSUE THREAD

**Issue by dongzhuoer** [microsoft/vscode-cpptools#1442]
In the current version, `int` is in a special color. I hope user-defined type also be in the same color and template classes (such as `std::vector`) get their own color too.

```cpp
int x{1}

std::vector<int> vec;

class myclass {
}
myclass myclass1;
```

**Comment by bobbrow** [comment]
Thank you for the feedback.  We are tracking colorizer improvements with #230.  Feel free to go upvote that issue.

**Comment by dongzhuoer** [comment]
Thank for the redirect and sorry to create a redundant issue. (I have searched a little, but I didn't find that  issue.)
