### ISSUE TITLE
support folding consecutive comment

### ISSUE THREAD

**Issue by dongzhuoer** [microsoft/vscode-cpptools#1443]
It would be nice if we can fold something like

```cpp
\\ some
\\ very
\\ long
\\ comment
```

**Comment by sean-mcmanus** [comment]
VS Code doesn't have an API to enable this to be implemented by extensions yet: https://github.com/Microsoft/vscode/issues/37682 . You might want to consider filing an issue with VS Code itself https://github.com/Microsoft/vscode/issues .

**Comment by dongzhuoer** [comment]
Thank you anyway!

**Comment by bobbrow** [comment]
There is an API for this now, but we do have another feature tracking code folding.  I'll move this over there.  #407
