### ISSUE TITLE
Set an environment variable.

### ISSUE THREAD

**Issue by mathchew** [microsoft/vscode-cpptools#1445]
I will apologies ahead of time, because I know this is probably right in front of me and I cannot see it or figure this out.

I am taking a class which requires C++, so I would like to run C++ with VS Code.

I followed your instructions and I am stuck on this part:

Set an environment variable CPPTOOLS_DEV=1.
This enables the local developer workflow, copying dependencies from the node_modules folder.

Can someone please explain or point me in the right direction to understand this?

I would like to run this simple hello world code:

#include "stdio.h"
#include "iostream"
using namespace std;

int main() 
{
    cout << "hello world";
    return 0;
}

Any help or guidance would be wonderful.

Matthew

**Comment by bobbrow** [comment]
Did you clone this repository and run the extension from the source code?  Or did you install a pre-built version of the extension (e.g. through the extension Marketplace)?  If you are not building the extension source yourself, you should not see this message.

**Comment by sean-mcmanus** [comment]
The debugger team added that to copyScript.ts . I think you can just ignore it.

**Comment by pieandcakes** [comment]
@mathchew Those instructions are for if you want to build the extension yourself and debug it. 

You probably just want to download the extension from the VS Code extension gallery (or extension widget within VS Code).

**Comment by mathchew** [comment]
Thank you everyone for responding. I am so busy right now I can not keep up. I moved over to Windows OS with VS installed. When I get a chance to try VS Code on the Mac OS again I will keep you posted on my progress. 

bobbrow:

I did clone the repository, but honestly, I clearly do not know what I am doing.

Thank you again for your responses.

**Comment by tehsunnliu** [comment]
Hi all even I'm facing the same problem. I don't understand what "Set an environment variable CPPTOOLS_DEV=1" exactly means. Do I set my system environment variable or in some file I need to make this change? Help will be really appreciated. Thank you.

**Comment by pieandcakes** [comment]
@tehsunnliu That is used when building the extension to tell the extension build that you are developing the extension locally and need to copy dependencies over. 

Environment variables are key/value pairs set in the operating system and can be read by the program. You can search the internet for "How to set Environment variables for <operating system>" and it should tell you how to do it for your particular OS.
