### ISSUE TITLE
Can I use this extension at company?

### ISSUE THREAD

**Issue by massivedynamicLive** [microsoft/vscode-cpptools#1449]
I'm using VS Code, and I want to compile and debugging C++ code at VS Code. Because I can not use  newest VS community at company. 

So I want to know Is there any legal problem using this extension with VS Code at Company?

**Comment by bobbrow** [comment]
There is no legal problem.  You may use VS Code and this extension to write software at your company.  You do not need to pay for a license.

**Comment by massivedynamicLive** [comment]
thank you!!
