### ISSUE TITLE
Using other debuggers?

### ISSUE THREAD

**Issue by MrManhoso** [microsoft/vscode-cpptools#1453]
Hi,

Would it be possible to add support for other debuggers than gdb and lldb? I have some old Borland code (mainly 2006, but also 5) i would love be able to debug i VS Code. I can get it to build using make in a task.

Found this issue #299 which seem to indicate it would only be possible if the debuggers support MI. Is it so? At the moment I don't know if any of the old borland debuggers do, though i read somewhere that the Borland C++ debugger is based on Windows debugger or something like that. But maybe i got that mixed up.  

Best regards
/Erik

**Comment by pieandcakes** [comment]
>Found this issue #299#299, Question about embedded systems debugger. which seem to indicate it would only be possible if the debuggers support MI. Is it so? 

Yes, because our intermediary layer ([MIEngine](https://github.com/microsoft/miengine)) is the layer translating from VSCode's debug protocol to the debugger protocol (MI). 

For the Windows C++ debugger we added support to communicate directly to the VSCode debug protocol in the debugger.

**Comment by MrManhoso** [comment]
Hi, thanks for the answer.

So if it is true that the borland c++ debugger i based off windows debugger then with alot of luck i could get it to debug in VS Code using windows c++ debugger? Fortunately there is also a project for converting the symbol files, map2dbg (borland has their own files). Will try it out as soon as i get some spare time to do it, and report back here if it is of interest. Otherwise my question has been answered, i'm satisfied and thank so much for the help!

best regards
/Erik

**Comment by pieandcakes** [comment]
@MrManhoso If the symbol file format is one we can work with, then it should work with the WIndows Visual C++ debugger. From conversations here, if the converter generates VS7+ style PDBs, it may work partially but the speculation is that the expression evaluator isn't going to be happy. If its older than that, it probably won't work. 

More informations about the pdb format can be found [here](https://github.com/Microsoft/microsoft-pdb)

**Comment by MrManhoso** [comment]
hi, thanks for the information. The dbg format was not accepted, and given the information you just provided probably not so surprising... From what i could gather dbg is no longer (probably since quite long back) supported by VS and the likes.

I'm happy with the answers (though not happy with what it implies for me), and now i know what i have to play with. Thanks!

best regards
/Erik
