### ISSUE TITLE
Go To Definition Opens to Non-Standard Path

### ISSUE THREAD

**Issue by blakebarber** [microsoft/vscode-cpptools#146]
Let's say I startup VS Code to my project directory that has two or more subdirectories that looks like this:

project/
----source/
--------foo.hh
--------foo.cc
----other_stuff/

Now I click on foo.cc in the explorer to open it in my editor.  All is well, I see `foo.cc` open up and the path shown in the "Open Editor" area is `source/foo.cc` .  Now just for fun I hit F4 to bring up the header file and sure enough up pops `foo.hh` and it shows a path of `source/foo.hh`.  So far so good.  Now let's close `foo.hh` and do the same thing only using the `Go To Definition` functionality.  I find a variable in `foo.cc` that is defined in `foo.hh` and I hit F12 to `Go To Definition` and sure enough it pops up.  Only this time the path shown in the "Open Editor" area is `project/source/foo.hh` instead of just `source/foo.hh`.  

Now this starts causing problems.  When I do things such as find in files I now get results for both `project/source/foo.hh` and `source/foo.hh`.  When I hit `ctrl + p` to do a fuzzy find and try to go to `foo.hh` I'm presented with an option to go to `project\source\foo.hh` and if I select this one it fails to open and complains about not being able to find the file.  

Another minor probably unrelated issue that I didn't not above is that when I hit F4 to switch to header, if I happen to be in the Right Editor, the header opens in the Left editor.  It would be better if it swapped from header to source in the same editor.

**Comment by jgoshi** [comment]
Which OS version, VSCode version, and C++ extension version are you using? On my system (Ubuntu 16.04 with the latest VSCode version 1.4 and C++ extention 0.9.0 which will be released in the coming weeks) things work properly.

**Comment by blakebarber** [comment]
I'm using  Ubuntu 14.04, vscode 1.4, and extension 0.8.1. Looking forward
to 0.9.0.

**Comment by jgoshi** [comment]
Do you have a user or workspace settings file? Could you send me that? I wonder if this has to do with different settings on the machines I'm testing on.

**Comment by jgoshi** [comment]
Actually, this is fixed and will appear in the next release of cpptools (version 0.9.0). If you notice it after installing the new version please reopen the bug.
