### ISSUE TITLE
intellisense suggestions/autocomplete for user defined variables/functions is slow/delayed 

### ISSUE THREAD

**Issue by raghavk92** [microsoft/vscode-cpptools#1464]
I am using version 1.19.1 of vscode. I am using the official c/c++ extension from microsoft and i am using wsl on the terminal and configured the path of header files for better intellisense
when i start typing the name of a variable (int,vector or function) defined by me in the current file the autocomplete shows me list of functions from the header files like time.h which i dont even want and the user defined functions autocomplete suggestions come at the very end when i have completed typing the name of the variable/function and this has happened many times.I have but the standard header file which covers all header files (#include <bits/stdc++.h>) but i still want user defined suggestions to come first.

Do i have to turn on some setting or download an extension for getting the suggestions with autocomplete for the variables/functions defined in the current file first or is there any other way to resolve this issue.
I am trying to use the editor for fast/competitive programming . So if suggestions are faster it would be pretty good.

**Comment by sean-mcmanus** [comment]
We don't currently support the smarter IntelliSense autocomplete with global/local variables that are not scoped. We're tracking this with https://github.com/Microsoft/vscode-cpptools/issues/13 .

However, it sounds like you're experiencing an issue with the fact that we only return 1000 completion results when you initially start typing. We were going to investigate increasing that to 10000, but it seems we forgot. Does that sound like it'd fix your issue or did you have some other suggestion for removing unwanted completion results? Putting user-defined suggestions first won't work -- we match alphabetically as you type.

**Comment by raghavk92** [comment]
@sean-mcmanus  i guess you answered my question by saying "We don't currently support the smarter IntelliSense autocomplete with global/local variables that are not scoped. We're tracking this with #13 ." but i am not sure. I want to explain again and  ask that shouldnt autocomplete for local variables(variables defined in a function)  be most important for autocomplete then global variables and then all the other functions from the header file because the local variables/global are most likely to be used when writing code within any function. Shouldnt this be a priority for the editor to make writing code easier. 

In the gif i tried writing two variables (ways and astronaut - a vector which intellisense didnt suggest and but did give for a global variable visited -vector which i defined just below the header files. To me it looks like that local variables are not supported at all in autocomplete but shouldnt that be very important. Instead its showing me gibberish functions and variables from header files whose parts I am not even using. 
![vscode_intellisenselocal](https://user-images.githubusercontent.com/9316689/35167961-4f6368d0-fd7d-11e7-8923-36c4f7299588.gif)
 For functions also if i type a function's first alphabet it should show me the functions first which are in the file then other functions in header files but it shows functions first of header files i am not even using. 

I updated to vscode 1.19.2 where it says it will show smarter suggestions according to the selection i make.but if i type a function three times and select the one that is correct it doesnt get smarter. 

Shouldnt it be like show suggestions first of local variables , then global within the file and then everything all alphabetically but in that order and same goes for functions.

**Comment by sean-mcmanus** [comment]
Yeah, we just don't have the local/global variables available yet because the feature hasn't been added, because it was too slow compared to a scoped completion after a . -> etc. Local variables is https://github.com/Microsoft/vscode-cpptools/issues/255 . The non-IntelliSense completion that is being used is not able to determine which symbols belong to the current translation unit or not, so it will return the first 1000 matching results.

**Comment by raghavk92** [comment]
@sean-mcmanus  please add this feature as soon as possible. I really want to work with node and do cpp programming from vscode .but this really becomes a deal breaker and i have to go back to my previous editor for now for cpp. When would be the ETA for this feature to be added because it would really help me

**Comment by sean-mcmanus** [comment]
We have it scheduled for March, but the schedule could change.

**Comment by mfmayer** [comment]
I want to vote for that, too. It was the first thing I've realized that local variables & function's parameters are not suggested by autocompletion. Would be really helpful to have this. But anyway great work und thanks for the great tools! :-)

**Comment by Srekel** [comment]
This is one of my main gripes with the cpp extension at the moment. At least I think it's the same issue. Sometimes the autocomplete doesn't update with things that are more reasonable when things are filtered out, even though it obviously knows about them in some sense. See the gif:

(climb_direction_x is a local variable in the same function)

![cppautocomplete](https://user-images.githubusercontent.com/1578924/44650363-ac1db380-a9e6-11e8-8ffb-6cf745556d99.gif)

Is it perhaps that it needs to re-request/populate the list as it goes on?

**Comment by bobbrow** [comment]
Can you check the problems window and see if the extension is using the tag parser for IntelliSense?  The extension does suggest local variables but only if all of the `#include` statements successfully resolve (or if you disable the `#include` checking).

In any case, the original issue has already been resolved, so if you are able to resolve the problems in the problems window and continue to get incorrect behavior with autocomplete, I will move this issue to a new one.  Let me know.

**Comment by Srekel** [comment]
Aha. Yes, it seems like it is using the tag parser. So, provided I fix my includes it ought to work? Going to try that, thanks :)

**Comment by bobbrow** [comment]
You can either fix your include path (preferred) or turn off the fallback behavior (click the lightbulb that appears when you highlight the squiggle and choose "force semantic IntelliSense").

**Comment by sean-mcmanus** [comment]
Go to Defintion and autocomplete with local variables should work with 0.19.0. Let us know if you're still having issues with it.
