### ISSUE TITLE
compile_commands additional toolchain include paths

### ISSUE THREAD

**Issue by decimad** [microsoft/vscode-cpptools#1465]
Hey,
it seems the extension ignores manually set include/browse paths once you have a compile_commands.json set up to be used. However in my case this file does not include the built-in toolchain include paths. Adding them to includePaths/browse does not seem to be recognized by the extension in this case.
Is the intentention for me to achieve this differently? Would it be possible to add these settings to the set gathered by parsing the compile_commands.json ?

**Comment by sean-mcmanus** [comment]
I seem to recall it was a design decision, but @bobbrow probably knows more. We try to query the compiler for the builtin includePaths, but there are cases in which that can be incorrect and the builtin defines are not used yet. We could theoretically change it so that the `includePath`/`defines` is appended to the ones obtained from the compile_commands.json. That could break people who rely on the previous behavior, but they should be able to clear out their settings to obtain the previous behavior.

**Comment by aakre** [comment]
What you describe seems to be the intended behavior, but according to the [documentation](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md) you should get a warning if there is no entry for the toolchain include paths:

> compileCommands (optional): If "C_Cpp.intelliSenseEngine" is set to "Default" in your settings file, the includes and defines discovered in this file will be used instead of the values set for includePath and defines. If the compile commands datasbase does not contain an entry for the translation unit that corresponds to the file you opened in the editor, then a warning message will appear and the extension will use the includePath and defines settings instead.

**Comment by sean-mcmanus** [comment]
@aakre Ah, yeah, I talked to Bob today and he mentioned that "fallback" behavior. I think we decided to add some sort of systemIncludePath/systemDefines setting which corresponds to what the built-in values used by your compiler and that would get appended on, and the existing includePath/defines would keep the same behavior and only be used as a fallback (combined with the system ones too). We were already planning to add separate "system" properties to solve some other issues.

**Comment by decimad** [comment]
Hrmm, I'm cross-compiling through cmake (toolchain file), so I'm not very optimistic that the c++ extension will easily be able to determine the compiler automatically to determine the system includes. However it would be equally fine if I just could set the compiler executable manually in this case (if the extension can handle gcc derivates).
The most "conservative" solution imho would be if there was a switch to control wether the manual include paths are taken as system paths in case compile_commands are used.

**Comment by sean-mcmanus** [comment]
@decimad 1. We're adding a setting to your compiler path. 2. We'll also query the compiler for defines. I think that would solve your issue.

**Comment by bobbrow** [comment]
This should be covered by #1293.
