### ISSUE TITLE
In target debugging with locally installed emulator?

### ISSUE THREAD

**Issue by Pillasaar** [microsoft/vscode-cpptools#1467]
Hello,

New to VS Code(just installed in a couple of hours ago!). I also installed the CPPtools extension and the IAR embedded work bench extension. I am able to build my software now.
I use a Renesas Rx631 processor and E2 Lite emulator. Is there anyway I can do in-target debugging using cpptools extension? Or do I need GDB support of the emulator? 

Thanks,
Sudhi

**Comment by pieandcakes** [comment]
@Pillasaar We communicate with gdb using the [mi](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html) interface. You can either have gdb locally and gdbserver in the emulator or use some communication method like `ssh` to communicate with gdb in the emulator. 

I don't know your specific scenario so I can't speak to it but hope that helps.

**Comment by Pillasaar** [comment]
@pieandcakes Thanks for your reply!
I have never worked with gdb before except in the Uni and when I read about gdb server etc. I am a bit confused to be honest. Because all I knew was the GNU debugger that I used in a unix machine ages ago; obviously gdb has moved on a bit by the look of things.
I will explain what I am trying to do - 

I have an IAR embedded work bench project (RX631 processor) that I am trying to get running on VSCode. I am looking to get it to a stage where I can build and perform in-target debugging from VSCode(not sure if this is possible). I use an E2-Lite emulator.

I installed an IAR extension(not an official one) and got the code to build(using IAR compiler) in VSCode.
Here is the link to that extension -  
[https://github.com/politoleo/iar](url)
I have also installed cpptools extension. I have one problem in there that 
**(i)when there are build errors displayed in the output window after building, I can't double click on them and go to the offending line of code.**

I am now trying to get the in-target debugging working. So my question is,
**(ii) Is this possible at all?
(iii) So what do I need here? gdb support for emulator(e2-lite)?
(iv) Does the code need to be compiled using a basic GNU compiler as well to be able to use gbd? My code has a lot of compiler directives for IAR compiler. So, it won't compile in GNU.**

Any help is much appreciated.

Thanks,
Sudhi

**Comment by pieandcakes** [comment]
I've never worked with an emulator so I can't speak to your scenario. The easiest way to answer the question is when you are not using VS Code, how are you debugging this? Is it using `gdb` in the emulator or are you using `gdb` locally to communicate with some other debugger/debug process within the emulator?

That would help me give you a direction to start looking into.

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.
