### ISSUE TITLE
Source code formatted with ÿþ and spaces

### ISSUE THREAD

**Issue by mamellini** [microsoft/vscode-cpptools#1473]
Two of my students who use Visual Studio have submitted C++ source codes that are formatted (not pure text files), such that I cannot compile the codes.  When I open the .cpp file in my IDE, I see a source code file that begins with a byte order mark (ÿþ), then spaces are inserted between each character in the file.  I have never encountered anything like this before. If I open the .cpp files in an ordinary text editor, the content appears normal.

I need to know what causes this so I can tell the students how to adjust their settings to create source codes that I can open and compile.

![fetter_lab0_ide](https://user-images.githubusercontent.com/35608456/35164451-618af948-fd18-11e7-83b5-9179c1859007.jpg)

**Comment by bobbrow** [comment]
They are probably saving their files as UTF-16 and it doesn't look like your editor supports it.  Ask them to try saving the files as UTF-8 instead.  There should be a little down arrow by the save button in Visual Studio that lets you select an encoding.

![image](https://user-images.githubusercontent.com/12818240/35165704-304aae78-fd04-11e7-8a53-f4bc4bb19496.png)

**Comment by mamellini** [comment]
Thank you so much!
