### ISSUE TITLE
[Intellisense] Annoying error message when viewing git diffs.

### ISSUE THREAD

**Issue by vadimcn** [microsoft/vscode-cpptools#1475]
VSCode:  1.19.2
Extension: 0.14.6

I've configured C++ intellisense to use the compile_commands.json file from cmake.

Whenever I view git diffs (using GitLens extension), the C++ extension keeps popping up errors similar to this: `"application-20626910647KP2B8X6OONie.cpp" not found in "${workspaceRoot}/build/compile_commands.json". Using 'includePath' setting in c_cpp_properties.json.`

I think there should be a way to disable this message.  
(And was it necessary in the first place?  Using fallback after failure to parse source file does not generate an error message, so why should this?)

**Comment by sean-mcmanus** [comment]
Okay, we fixed it via not issuing that warning if the missing file isn't under the workspace root.

**Comment by sean-mcmanus** [comment]
We believe this is fixed with the preview .vsix at https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.15.0-insiders (our final release is planned for next week). Let us know if the fix isn't working sufficiently.

**Comment by vadimcn** [comment]
The error message seems to be fixed.  Thanks!

I still see the error squiggles for includes.  Perhaps those should be disabled as well?

**Comment by sean-mcmanus** [comment]
Error squiggles for includes is a different issue (seems like https://github.com/Microsoft/vscode-cpptools/issues/791 , although it could be https://github.com/Microsoft/vscode-cpptools/issues/1520 ). That squiggle is probably intentional, indicating that the includePath or browse.path wasn't sufficient to find the header.

**Comment by vadimcn** [comment]
Isn't the problem that the include path is supposed to be found in compile_commands.json, and for git diff files this doesn't work?

**Comment by sean-mcmanus** [comment]
Yeah, the error squiggle you see is "by design" since users can theoretically fix it via adding the path to the includePath setting.

**Comment by vadimcn** [comment]
I hate to argue this point, because the annoyance of squiggles in minimal... however, the whole point of using compile_commands.json is that one doesn't need to maintain includePath manually (also, when using cmake, the include path may be significantly different for different files in the project).

**Comment by sean-mcmanus** [comment]
So what fix are you proposing we do? Isn't this just for the temporary files generated by "git diff"?

**Comment by vadimcn** [comment]
Same as above - if the file is not under the workspace root, disable error squiggles.  Or, possibly, do that only when compile_commands.json is in use.

Anyhow, I'm gonna stop annoying you about this.  Thanks fixing the error message problem!
