### ISSUE TITLE
snippet can not work in C header file

### ISSUE THREAD

**Issue by cxk99** [microsoft/vscode-cpptools#1476]

**Comment by sean-mcmanus** [comment]
What do you mean? Our cpptools doesn't implement snippets.

**Comment by vasa-chi** [comment]
I can help with this one :)
Basically vscode's snippets are language-specific, and .h files can be detected as C++ instead of C.
So snippets for C would not work in .h files, detected as C++. Manually switch detected language, and everything is fine.

**Comment by cxk99** [comment]
Yes, you are right. Thanks for your help.
I tried, it just work as you said.
By manually switch the language of .h file from C++ to C , my snippet defined in "c.json" works fine.
Thanks for the answer.
