### ISSUE TITLE
Discovering files... can appear stuck if the workspace is too large.

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1481]
If the workspace is super huge and has hundreds of thousands of folders, then our code gets stuck enumerating files with no progress indicator change.

Workaround: Such a large workspace probably should not be used (open the multiple subfolders you actually need instead). VS 2017 fails to handle this as well.

This could be fixed via switching to a breadth first processing of files, but it doesn't appear to be worth the effort until we get enough complaints.

**Comment by shubhamgupta372** [comment]
I am also facing this issue while working on a remote server folder through ssh. The process discovery of files seems to get stuck and IntelliSense doesn't work. I have around 50K files in the project repo. It will be a big relief if you take this issue for fixing.

**Comment by sean-mcmanus** [comment]
@shubhamgupta372 50k files shouldn't be "too large" to process. You might be hitting a different issue. Is cpptools using CPU? Can you attach a debugger to get a call stack to see if it's really enumerating through files in the workspace or not?
