### ISSUE TITLE
Feature Request: Support for clang-rename

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#1483]
Are there any plans for supporting clang-rename?

**Comment by sean-mcmanus** [comment]
We eventually plan to implement rename (https://github.com/Microsoft/vscode-cpptools/issues/296 ). We're not planning to implement support via clang-rename, but if someone wants to contribute that we'd be willing to consider adding it, assuming it isn't too buggy and it works across multiple translation units.

**Comment by Gruntfuggly** [comment]
OK, thanks.

**Comment by bobbrow** [comment]
We have no plans to integrate clang-rename at this time.  We recently implemented rename via #296 and released it with version 0.26.0.  If we get more requests for this feature we can reconsider.
