### ISSUE TITLE
Code formatting causes characters to be added to the file (ie. corruption)

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#1486]
- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.3.4
cpptools|ms-|0.14.6
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1

---

Here's a weird one (which hopefully repros for you). Download this file:

[Untitled-2 - Copy.txt](https://github.com/Microsoft/vscode-cpptools/files/1658563/Untitled-2.-.Copy.txt)

Steps to Reproduce:

1. Rename the above file to have a .cpp extension and try to open it.
2. It says can't open it because of text encoding.
3. The weird thing is that I don't know how it opened the original file on my computer. If I copy the file, VSCode refuses to open it. If I zip it up, then extract and try to open, it refuses still.
4. In any case, the symptoms are as follows. In the file that I have, every time I save (where I've enabled format-on-save), it'll add some text and presumably a malformed character that causes it to happen every time I save.

![capture](https://user-images.githubusercontent.com/29720335/35314614-372c9122-007c-11e8-9c8e-650f31a3d5b5.PNG)

The source text is pasted below copied out of notepad. I have no idea what the bad characters are or how to get rid of them (because I can't see them in notepad):

```
DMAC->CTRL.reg = DMAC_CTRL_SWRST;
PM->APBBMASK.reg |= 0x00000010t :
{

    PM->APBBMASK.reg |= 0x00000010t :
    {
        PM->AHBMASK.reg |= 0x00000020;
        PM->APBBMASK.reg |= 0x00000010t

                            DMAC->CTRL.reg &= ~DMAC_CTRL_DMAENABLE;
        DMAC->CTRL.reg = DMAC_CTRL_SWRST;
        PM->APBBMASK.reg |= 0x00000010t :
        {

            PM->AHBMASK.reg |= 0x00000020;
            PM->APBBMASK.reg |= 0x00000010t

                                DMAC->CTRL.reg &= ~DMAC_CTRL_DMAENABLE;
            DMAC->CTRL.reg = DMAC_CTRL_SWRST;
            PM->APBBMASK.reg |= 0x00000010t :
            {


```

Reproduces without extensions: Yes/No

**Comment by sean-mcmanus** [comment]
I'm not able to get any malformed characters or corruption to occur. What could I be doing wrong/differently? Does it only repro after you format? Or does any edit/save work (and/or edit/save without our extension installed)? There's another bug I've seen in which VS Code will alter the text after any edit/save, apparently due to some encoding peculiarity.

**Comment by bobbrow** [comment]
There appears to be bad characters before the `:` characters in the file.  You can open it with Notepad++ and see.  If you paste the code into VSCode it replaces those characters with spaces which is probably what Sean saw.  Where did you get this code from?  Copied from the Internet?  You can simply delete the characters and then everything will be fine.

**Comment by sean-mcmanus** [comment]
So our extension wasn't causing any corruption?

**Comment by azydevelopment** [comment]
Oh so that's where it was. It doesn't show up in VSCode or Notepad and I've since uninstalled Notepad++ (in favor of VSCode :)).
