### ISSUE TITLE
Context aware goto-definition

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode-cpptools#1487]
Code sample:
```
struct A {
 void foo() {}
};

struct B {
 void foo() {}
};
....
A aa;
aa.foo();
```

If I go to definiton of foo in `aa.foo` it pops up and suggests me both structs, but who cares about struct B, since foo is not virtual.

**Comment by bobbrow** [comment]
Thanks for the feedback.  We are tracking this feature with #255 and I would encourage you to go upvote it.  The current implementation does not use semantic information.

**Comment by sean-mcmanus** [comment]
Go to Definition on aa.foo goes to A::foo with 0.19.0.
