### ISSUE TITLE
Support code coverage tool, eg. gcov

### ISSUE THREAD

**Issue by eliotstock** [microsoft/vscode-cpptools#149]
I'd like to get a view of which lines of my code are executed when I run my tests.

One approach would be to generate the coverage data using an external tool such as gcov, but have VSC understand gcov's .gcov files and shade lines of code to show coverage in the editor.

Another might be to use the integrated debugging features somehow.

**Comment by sridmad** [comment]
Understanding gcov or other code coverage tool generated logs and highlighting the line / column in VSCode should most probably be a stand alone extension. Such an extension can exist side by side with C++ language service and debugging extension

**Comment by bobbrow** [comment]
This is not something that we plan to add to the C++ extension at this time.
