### ISSUE TITLE
Unknown 'PROBLEMS'

### ISSUE THREAD

**Issue by lokeb** [microsoft/vscode-cpptools#1496]
```c++
#include <iostream>
#include <string>

using namespace std;

int main(int argc, char* args[]) {
  string asdf = "my love, I don't love you!";
  cout<<"arg count:"<<argc<<endl;
  cout<<args[0]<<endl;
  cout<<asdf<<endl;
  return 0;
}
```
It is giving me problems that don't make any sense, even though my program compiles, debugs and runs just fine. Also why does it open a new terminal window for debugging, when there is an embedded terminal?

![screen shot 2018-01-27 at 4 55 26 pm](https://user-images.githubusercontent.com/9778706/35471565-6f97e278-0383-11e8-9c00-18d19d8fdf4d.png)

**Comment by sean-mcmanus** [comment]
The error squiggles may not have been updated soon enough -- are you seeing the same problem after closing/reopening the file?

**Comment by lokeb** [comment]
That's true. After reopening it's fixed. But why do I have to reopen? After I update a file, shouldn't the debugger ask to rebuild before running. The debugger uses the old executable, if build is not called.

**Comment by sean-mcmanus** [comment]
We have to queue an update request after an edit, but I think we may have a bug in which the update may not occur or may get lost under certain random conditions (or it could just be delayed by a few seconds). Making an edit and then saving may also force an update and remove the errors. This has nothing to do with the debugger or executable -- it's our IntelliSense process.

**Comment by pieandcakes** [comment]
@lokeb 
>After I update a file, shouldn't the debugger ask to rebuild before running. The debugger uses the old executable, if build is not called.

Unfortunately the VSCode Debug protocol doesn't allow us a way to query the language service to determine of the code we are referencing is different than the executable that is being debugged. If you add a `task.json` and add a `prebuildTask` to your `launch.json`'s configuration, it will build every time before debugging, which would get around this but would build every time.

**Comment by lokeb** [comment]
That works. I added
"preLaunchTask": "build"
to launch.json configurations corresponding to tasks.json task with label
'build'.

Thanks a lot!

**Comment by michelleangela** [comment]
Closing this issue as resolved per last comment.
