### ISSUE TITLE
c_cpp_properties.json file rewritten *every* restart

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-cpptools#1500]
Moved from https://github.com/Microsoft/vscode/issues/42349
From @gdamore

---

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:25:01.248Z)
- OS Version: Darwin x64 17.3.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.23
Go|luk|0.6.73
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.14.6
cmake|twx|0.0.17
cmake-tools|vec|0.10.4
clang-format|xav|1.6.1

---

Steps to Reproduce:

1. Edit the c_cpp_properties.json file (e.g. to add a new includePath for intellisense
2. Confirm the contents updated to disk (after saving), e.g. by "less .vscode/c_cpp_properties.json"
2. Restart
3. The file is now "reverted" to a default, without any of the changes

I suspect maybe one of the cmake related extensions?

Reproduces without extensions: NO

**Comment by bobbrow** [comment]
cmake-tools-helper is the most likely culprit.  It is known to wipe your c_cpp_properties.json file in certain circumstances.

**Comment by gdamore** [comment]
Agreed.  Looking at this a bit more closely, on my platform at least, it isn't actually doing anything helpful since it is just nuking otherwise valid c_cpp_properties.json file (and injecting invalid file contents in its place -- e.g. no version field.)

**Comment by ekegulskiy** [comment]
Observing the same problem when using Studio Code with webkitgtk CMake project. The VS Code version is, running on Ubuntu:

Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:31:21.019Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by sean-mcmanus** [comment]
@ekegulskiy Did you disable the cmake-tools-helper?

**Comment by ekegulskiy** [comment]
@sean-mcmanus yes, disabling the "cmake-tools-helper" extension inside Visual Studio Code does fix the problem, thanks!

**Comment by pyrrho** [comment]
I had the same issue, but without "cmake-tools-helper" installed.
Disabling "Go" resolved the issue for me.
