### ISSUE TITLE
Why isn't std::optional recognized?

### ISSUE THREAD

**Issue by Rakete1111** [microsoft/vscode-cpptools#1502]
`std::optional`, `std::variant` and other facilities from C++17 don't seem to be recognized by the default tag parser engine.

Another issue suggested to change the value in `vim ~/.vscode/extensions/ms-vscode.cpptools-0.14.6/bin/msvc.json` to use the C++17 standard, and I did. But I still get that error. It's a bit annoying. Is there any reason why this happens?

I might add that my compiler can compile this, so it's not a compiler issue.

Here's an image illustrating it:
![std-optional-vscode](https://user-images.githubusercontent.com/8321423/35586811-31f3347e-05fc-11e8-8259-83874c49475e.png)

**Comment by bobbrow** [comment]
Hmm...  This works for me on both Windows and Linux.  What does your include path look like?  If you have an older version of gcc, optional may still be in the "experimental" folder which we do not add to the include path by default.

I'm surprised that there is no squiggle under the `#include <optional>` line though...

**Comment by Rakete1111** [comment]
I'm on Linux so this are my include paths under Linux:

    "includePath": [
        "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1",
        "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1/x86_64-pc-linux-gnu",
        "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../include/c++/7.2.1/backward",
        "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/include",
        "/usr/local/include",
        "/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/include-fixed",
        "/usr/include",
        "${workspaceRoot}"

I'm using gcc 7.2.1 and no, I just checked, it is not under the experimental folder and I looked at the source and there is no mention of optional being in an experimental namespace. For reference, I looked at `/usr/include/c++/7.2.1/optional`.

Thanks @bobbrow

**Comment by sean-mcmanus** [comment]
This is the same issue as https://github.com/Microsoft/vscode-cpptools/issues/1350 .

**Comment by bobbrow** [comment]
Thanks @sean-mcmanus.  I was going to try 7.2, but I hadn't gotten there yet (I have 7.1)

**Comment by bobbrow** [comment]
Tracking this with #1350
