### ISSUE TITLE
Question: How to display memory during a debug session

### ISSUE THREAD

**Issue by LordHog** [microsoft/vscode-cpptools#1503]
I am trying to figure out how to display a region of memory within Visual Studio Code with the CPP-Tools during a debug session.  I can't seem to figure it out.  One way to getting some data is using the following:

(uint8_t*)(address) 

This will display the data as ASCII Hex based upon what I can see.   I ideally, I would like to view the data as hex (perhaps decimal).  I asked this question in the Gitter Microsoft/vscode forum, but no insight so far.  This is the best I can do for now:

![image](https://user-images.githubusercontent.com/970098/35593065-c03dcb74-05c3-11e8-8582-ba84520e24f5.png)

Also, I would like to be able to view the data as hex or decimal, is that possible?

Regards.

**Comment by WardenGnaw** [comment]
VsCode does not have a memory window to use. However, you can execute GDB commands by typing```-exec``` in the Debug Console.

So you can visualize the memory with ```-exec x <address>```.

More information on the examine command can be found [here](https://sourceware.org/gdb/onlinedocs/gdb/Memory.html)

**Comment by LordHog** [comment]
Mr. @WardenGnaw, thanks!  I knew about the "x addr" command, but when I tried to exercise that command it would fail.  I didn't know about the preamble "-exec".  I will need to find the documentation that talks about that command and hopefully others that I don't know about.

**Comment by WardenGnaw** [comment]
Sadly, I don't think we have any documentation on it. All we have is an output in the Debug Console that says ```Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)```.

**Comment by LordHog** [comment]
@WardenGnaw, hopefully this feature might be added one day.  It's a very useful debugging tool.

**Comment by voltflake** [comment]
Very nice-to-have feature. Also want to see it someday in VSCode

**Comment by austriancoder** [comment]
Me too.

**Comment by cxxman** [comment]
+1

**Comment by fadimounir** [comment]
+1

**Comment by IvanPizhenko** [comment]
I's not implemented in VS code, but would be nice to have. VS has memory windows. I came up with same question recently and found following: meanwhile you can run GDB command "x" in the debug console: `-exec x ... `. Command "x" reference, for example, here: https://sourceware.org/gdb/current/onlinedocs/gdb/Memory.html

**Comment by IvanPizhenko** [comment]
+1

**Comment by aktzbn** [comment]
Want to see such window for python debugger.

**Comment by CyrilleBenard** [comment]
Same needs within GO

**Comment by hunyadi-dev** [comment]
I am looking for something similar as well :(

**Comment by amruthsrepo** [comment]
+1

**Comment by twopieman** [comment]
> VsCode does not have a memory window to use. However, you can execute GDB commands by typing`-exec` in the Debug Console.
> 
> So you can visualize the memory with `-exec x <address>`.
> 
> More information on the examine command can be found [here](https://sourceware.org/gdb/onlinedocs/gdb/Memory.html)

the "-exec x <address>" is not as useful as having a memory window. it only gives you like one little portion of the memory. if you want to observe a large chunk of memory for changes its very hard to do so with this command.

**Comment by jonlopezh** [comment]
I found a way to view memory during a debug session using **Cortex-Debug** extension. The following steps must be followed:
1- Start a debug session.
2- Open the command pallet (press F1).
3-Type Cortex-Debug: View memory.
4-Type in memory location (e.g. 0x08000000).
5-Type in memory length (e.g. 128).

**Comment by gunnxx** [comment]
> 
> 
> I found a way to view memory during a debug session using **Cortex-Debug** extension. The following steps must be followed:
> 1- Start a debug session.
> 2- Open the command pallet (press F1).
> 3-Type Cortex-Debug: View memory.
> 4-Type in memory location (e.g. 0x08000000).
> 5-Type in memory length (e.g. 128).

@jonlopezh I already installed Cortex-Debug but I can't find the command in the command pallet.

**Comment by danjiehu** [comment]
View variable memory in HEX, type `-exec x &a` in DEBUG CONSOLE
* `-exec` is to indicate that what comes after is a GDB command
* to track continuous changes, log `-exec x &a` to WATCH - this way we don't have to type in the command manually every time

It would be so useful if we could get the full memory view for C++ in VS code like it's supported in Visual Studio! Unfortunately I'm using Mac so that's not even an option for me :(

**Comment by ShaheemNaqvi** [comment]
Still looking for it in march 2022...!

**Comment by NateAGeek** [comment]
I've created an extension that right now allows you to view a decent buffer of memory hex at an entered address: https://marketplace.visualstudio.com/items?itemName=NateAGeek.memory-viewer

Still very much a work in progress but feel free to tell me if it works 🤙
