### ISSUE TITLE
Ability to do VS Pro Tab Size 8, Indent Size 4?

### ISSUE THREAD

**Issue by bevolz** [microsoft/vscode-cpptools#1507]
Does Visual Studio code have the ability to do the Tools->Options Tab settings of Visual Studio Professional where you can specify that tabs are 8 spaces but the indent size if 4? All our code uses that style and many other editors let you do this, but Visual Studio Code doesn't seem to support this. I've tried  lots of things in Visual Studio Code but not found any combination of settings that work.

Using Visual Studio Code 1.19.3 (and also Visual Studio 2015 (and Professional 2012)).

**Comment by bobbrow** [comment]
I believe that VSCode equates tab size and indent size.  I would encourage you to [create a feature request](https://github.com/Microsoft/vscode/issues/new) in the VSCode repository.

**Comment by bevolz** [comment]
Created issue #42740 (Separate tab size and indent size) - see https://github.com/Microsoft/vscode/issues/42740.
