### ISSUE TITLE
 Unexpected token ]

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-cpptools#151]
_From @vscodeerrors on April 6, 2016 8:21_

Issue Id: <b>f3cc2e1d-6230-6369-eb72-6ce5b5069350</b><br /><br />_Versions_ <br />\- 0.10.14-insider<br />_Stack_ <br />SyntaxError: Unexpected token ]<br />    at Object.parse (native)<br />    at ConfigurationProperties.handleConfigurationChange (C:\Users\a123.vscode-insiders\extensions\ms-vscode.cpptools-0.4.2\out\src\C_Cpp_ConfigurationProperties.js:99:43) <no sourcemaps><br />    at C:\Users\a123.vscode-insiders\extensions\ms-vscode.cpptools-0.4.2\out\src\C_Cpp_ConfigurationProperties.js:61:19 <no sourcemaps><br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />[vs/workbench/node/pluginHostProcess.js#L4:7](https://github.com/microsoft/vscode/blob/17fa1cbb49e3c5edd5868f304a64115fcc7c9c2c/srcvs/workbench/node/pluginHostProcess.js#L4:7)<br />    at e._onFi<br />

_Copied from original issue: Microsoft/vscode#5013_

**Comment by egamma** [comment]
FYI @asthana86

**Comment by egamma** [comment]
_From @willbar on May 3, 2016 16:26_

I'm hitting this issue in 1.1.0-alpha (76625649235f4e9e4fbc9ec466f35061a944758a) and it prevents me opening any *.ts files.

**Comment by sean-mcmanus** [comment]
The versions are too old...re-open if it's reproing with the latest bits.
