### ISSUE TITLE
Error Squiggles showing for valid C++ code using std::bitset::operator[]

### ISSUE THREAD

**Issue by 1g0rb0hm** [microsoft/vscode-cpptools#1510]
* OS: OSX 10.13.2
* VS Code: 1.19.3
* C/C++ extension version: 0.14.6

Error Squiggles are shown for the following sample code (see screen snap further below):

```cpp
#include <bitset>

int main(int argc, char const *argv[]) {
  // see http://en.cppreference.com/w/cpp/utility/bitset/operator_at
  std::bitset<8> foobit(42);
  if (foobit[0]) {
    foobit[1] = false;
  }
  return 0;
}
```

Unless I am missing something the code seems to be correct and should not present any issues, certainly no errors.

![vscode error squiggles](https://user-images.githubusercontent.com/24808322/35685872-3259edca-076b-11e8-8d17-5476b9e7019a.png)

**Comment by bobbrow** [comment]
It appears to be a problem only on Mac.  I'm seeing that `__CHAR_BIT__` is not defined on Mac, but it is on Linux.  I need to go back and figure out why they didn't both get this define.

For now, you can work around this by adding `"__CHAR_BIT__=8"` to the `"defines"` array in **c_cpp_properties.json** or `#define __CHAR_BIT__ 8` in the source file that includes `<bitset>`

**Comment by 1g0rb0hm** [comment]
It seems `__CHAR_BIT__` is pre-defined by Clang. See line 748 in [lib/Frontend/InitPreprocessor.cpp](https://clang.llvm.org/doxygen/InitPreprocessor_8cpp_source.html):

```cpp
// Define type sizing macros based on the target properties.
assert(TI.getCharWidth() == 8 && "Only support 8-bit char so far");
Builder.defineMacro("__CHAR_BIT__", Twine(TI.getCharWidth()));
```

Since it is predefined in the LLVM compiler toolchain and not in some header MS IntelliSense doesn't seem to know about the definition on Mac. Defining it in **c_cpp_properties.json** is a good solution to fix the issue though.

**Comment by bobbrow** [comment]
Yeah, I should have been more clear.  We are not providing IntelliSense by calling directly into clang.  We have our own front end parser that supports a "Clang mode", but doesn't supply all of the defines by default.  The C/C++ extension has to supply them and we're not doing it for Mac.  We did it for Linux already though.

**Comment by 1g0rb0hm** [comment]
Understood. 

Is the plan for IntelliSense on Mac to match LLVM compiler toolchain defaults as on Linux or will the advised solution remain to define such compiler pre-defined macros in **c_cpp_properties.json**?

**Comment by bobbrow** [comment]
@sean-mcmanus is working on this right now.  The **c_cpp_properties.json** solution is just a work around for now.
