### ISSUE TITLE
Getting "cannot open source file obsolete/prototypes.h" with intellisense and compile_commands.json

### ISSUE THREAD

**Issue by nwgh** [microsoft/vscode-cpptools#1511]
I noticed this when I switched over to using `compile_commands.json` instead of a (perpetually out-of-date) explicit list of includes and defines in `c_cpp_properties.json`

STR:
 * Clone `https://hg.mozilla.org/mozilla-central`
 * Get development environment ready (`./mach bootstrap` from the checked-out source, have xcode + command line tools installed)
 * Create a `.mozconfig` in the root of the checkout with the following contents
```
mk_add_options AUTOCLOBBER=1
ac_add_options --enable-warnings-as-errors
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-dbg
ac_add_options --enable-debug
```
 * Build the project (`./mach build` from the root of the checkout)
 * Create a compile_commands.json (`./mach build-backend -b CompileDB`)
 * Set up the project vs code config from https://gist.github.com/nwgh/0e86b72876e03bad3eb398d51d24c528
 * Open VS Code and open an editor for `netwerk/protocol/http/Http2Stream.cpp`

Once the extension does its parsing thing, you'll see the error `cannot open source file "obsolete/protypes.h" (dependency of "HttpLog.h")` in the problems pane. Opening HttpLog.h will move the error to the dependency of a file it includes (and so on, and so on) until you get to `nsprpub/pr/include/prtypes.h` at which point, the error changes to a bunch of `#error` directives getting hit (presumably because, even though I have `XP_DARWIN` and `DARWIN` defined in my `c_cpp_properties.json`, the file `config/external/nspr/prcpucfg.h` that is included by `prtypes.h` doesn't see those defined, and so complains about "Unsupported platform", which bubbles up to cause the errors in `prtypes.h`).

The things is I don't see any file named `obsolete/prorotypes.h` or even a mention of it on my machine, so I'm not sure why that would be in the error message. I also see no output in the Output pane to help with debugging.

OS: Mac OS X 10.13.3 (17D47)
VS Code: 1.20.0-insiders 519088548b09221e9d590d2e10e14ec6d27ac79a
C/C++ extension: 0.14.6
Other extensions (disabling these does not change the behaviour): 
 * AutoTrim 1.0.6
 * Babel ES6/ES7 0.0.4
 * ESLint 1.4.5
 * Git Lens 7.5.10
 * HTML CSS Support 0.2.0
 * Python 0.9.1
 * Rust (rls) 0.3.2
 * Settings Sync 2.8.7
 * Vim 0.10.13

**Comment by djg** [comment]
I've just been investigating the exact same issue on linux.

`obsolete/protypes.h` is located in `${workspaceRoot}/nsprpub/pr/include`

If I run the command that is specified in `compile_commands.json` for a failing CPP file, the file compiles fine, so intellisense isn't using all the defines and includeds from the command specified in `compile_commands.json`.

Is there a way to debug what values intellisense picks up for `includePath` and `defines`?

**Comment by djg** [comment]
@nwgh, If you open `compile_commands.json`, find the command used to compile `netwerk/protocol/http/Http2Stream.cpp`, search the command for `-include /full/path/name.h` (there should be two) and put

```c
#include "/full/path/name1.h"
#include "/full/path/name2.h"
```

At the top of `Http2Stream.cpp` does that fix the intellisense issue where `obsolete/protypes.h` can't be found? If so, the intellisense engine doesn't handle force including of files into compilation using `-include`.

**Comment by sean-mcmanus** [comment]
Yeah, we don't support "forced include" files yet. It's https://github.com/Microsoft/vscode-cpptools/issues/852 . Another potential issue is the default compiler defines aren't being set correctly, which we're working on fixing for the next release.

BTW, I missed the original post for some reason and only noticed it when @djg responded -- if you don't get any response you can try pinging someone.

**Comment by nwgh** [comment]
@djg thanks for pointing out where obsolete/prototypes.h is... could've sworn I did a `find` for it, maybe it just got lost to my eyes in some noise of the output.

Once I added the single forced include for `Http2Session.cpp`, that error went away. (It exposed some other errors that are incorrect, but those could be due to an outdated objdir, or may be actual bugs, I don't know right now.)

@sean-mcmanus since I'm the one that filed #852 to begin with, I suspect this can be closed as a dupe and you can consider this a gentle ping in the hopes that it's coming soon :)
