### ISSUE TITLE
[Suggestion] Dismissing #error directive

### ISSUE THREAD

**Issue by m31317015** [microsoft/vscode-cpptools#1513]
**Reposted from main vscode repository.**

Version 1.20.0-insider
Commit 757ff83f0dece1ecf43d3a92e91fe467de1cc9dc
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

I was playing with Vulkan for some time and uses #error for easy debugging outside VSCode. Then I see every time I open the file it shows lots of "#error directive", so-called "problems". Is there a way to shut it off, or if there's none, may it be implemented in the future?

P.S. I just realized that #error is for C and C++, and I'm here to apologize for my stupidity that allows me to post in the main repository.

[ErrorDirectiveTest.txt](https://github.com/Microsoft/vscode-cpptools/files/1687789/ErrorDirectiveTest.txt)

**Comment by sean-mcmanus** [comment]
This is "by design". Ideally, you should setup your includePath/defines correctly so that the #error compile path is not hit. You could also surround the error code in `#ifndef __INTELLISENSE__ #endif` or set `"C_Cpp.errorSquiggles": "Disabled"`.

**Comment by m31317015** [comment]
Okay thanks, it helps a lot.
