### ISSUE TITLE
Add project's include folder to includePath by default

### ISSUE THREAD

**Issue by faheel** [microsoft/vscode-cpptools#1514]
Most C and C++ projects have an `include` folder that contains the header files for that project. Having this folder in the `includePath` by default would be very useful.

**Comment by faheel** [comment]
If I'm not wrong, this can be done by just adding `"${workspaceRoot}/include"` to `"includePath"` (and `"browse` too"?), right after `"${workspaceRoot}"`, for all 3 configurations in `Extension/src/LanguageServer/configurations.ts`.

**Comment by bobbrow** [comment]
We're going to be working on supporting recursive include paths which should also take care of this case.

**Comment by michelleangela** [comment]
Closing as recursive include paths resolves issue.
