### ISSUE TITLE
"Go To Definition" also opens "Peek Definition" for multiple results

### ISSUE THREAD

**Issue by melak47** [microsoft/vscode-cpptools#1517]
When I use "Go To Definition" on a symbol, and Intellisense finds multiple possible matches,
it goes to the definition of the first one -- but also opens up a "Peek Definition" view of the very same definition, along with a list of the other possible matches. (I assume this is by design.)

Most of the time I'm lucky and the first result is the right one, and my reward is an unnecessary "Peek Definition" view I have to close with another F12 press.
Would it be possible to let us configure whether this should open by default or not?

**Comment by bobbrow** [comment]
I think you'll need to ask the VS Code team if they would consider adding a setting for this.  Our extension doesn't have any way to control it (besides maybe discarding all but the first search result which would result in a different level of frustration 😄)

[Here's a link to open a new issue for VS Code](https://github.com/Microsoft/vscode/issues/new).

**Comment by sean-mcmanus** [comment]
Also, after we implement Go to Definition with IntelliSense, only one definition should be returned (if you're using the IntelliSense engine).

**Comment by chrisjallen** [comment]
@melak47 Hi did you find any resolve to this, could you point me to any ticket made on vs code? Thanks

**Comment by melak47** [comment]
@chrisjallen #255

**Comment by sean-mcmanus** [comment]
@chrisjallen @melak47 The vscode issue tracking this is https://github.com/Microsoft/vscode/issues/31046 so please upvote that.
