### ISSUE TITLE
"Go To Definition" picks wrong definition

### ISSUE THREAD

**Issue by melak47** [microsoft/vscode-cpptools#1518]
I'm not sure if this is a bug, but "Go To Definition" seems to be less accurate in the definition it picks than the hover tooltips.
For example, with the following code:
```cpp
#include <string>

int main() {
    std::string s;
    s.length();
}
```

Hovering over `length` shows `size_t std::string::length() const`, but Go To/Peek Definition picks `std::_Char_Traits::length` (MSVC stdlib), which doesn't match the signature at all. If the hover tooltip can figure out the right definition, why can't "Go To Definition" use that information?

VS Code version 1.19.3, C++ extension version 0.14.6, Windows 10 version 1709 / 16299.192.

**Comment by bobbrow** [comment]
Your analysis is correct.  Go to definition is not using the more accurate IntelliSense information yet.  We have a backlog item open to address this and I encourage you to go upvote it: #255.  Thanks for the feedback!

**Comment by sean-mcmanus** [comment]
Go to Definition std::string:length should work correctly with 0.19.0 (I get the definition in xstring).
