### ISSUE TITLE
Empty .browse.VC.db file  bug

### ISSUE THREAD

**Issue by hacqr** [microsoft/vscode-cpptools#152]
If a file in the sub directory contains Chinese, .browse.VC.db is empty!

for example

/project
/project/test/测试.file

cd /project && code .

**Comment by jgoshi** [comment]
Do you have any cpp files in those directories? We only parse extensions associated with c/c++. If you rename your file to end with cpp do you still have this problem? If so, please re-open this issue and attach a small code sample that repros the issue.
