### ISSUE TITLE
Not getting #include suggestions

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vscode-cpptools#1521]
* Windows 10
    * VScode 1.19
    * Latest
    * C#. Haven't noticed if this has anything to do with it.
  
I tried to debug this on my own and read the documentation but it didn't help. Intellisense works juts fine, but it doesn't suggest any #header files for include statements (even if those header files are in the same folder as the project). Once imported manually, however intellisense starts to work fine with the included header and gives me suggestions from the header. What could the issue be?

Note, that I do have IncludePaths set up.

**Comment by sean-mcmanus** [comment]
We haven't implemented that feature yet. I think we're using https://github.com/Microsoft/vscode-cpptools/issues/13 to track that.

**Comment by bobbrow** [comment]
We're using #802 for #include completion
