### ISSUE TITLE
Autocomplete for function/class method signature

### ISSUE THREAD

**Issue by Trevinlc1997** [microsoft/vscode-cpptools#1522]
Fedora Linux - 27
vscode - 1.19.3
C++ extension - 0.14.6

Extensions:
CMake and Include Autocomplete

When you are about to define your function/class method in your source file it would be nice for an auto complete for the signature.

![peek 2018-02-05 19-37](https://user-images.githubusercontent.com/24485362/35837505-1ff38ce2-0aac-11e8-9bfe-52c91cf04112.gif)

**Comment by sean-mcmanus** [comment]
What editor supports this? VS 2017 doesn't implement this; however, it does have a feature to "create definition" from the declaration, which is even better. ![image](https://user-images.githubusercontent.com/19859882/35837776-dd6f7c82-0a9c-11e8-8bf6-39c01bc3d70f.png).

In your example, you forgot the void return type of the bar method, so a "Create definition" code action would prevent errors like that which wouldn't be fixed via a parameter list completion.

**Comment by Trevinlc1997** [comment]
@sean-mcmanus 

The two editors/ide that I have used, that use this feature is KDevelop and QT Creator.

But interesting I don't seem to have the light bulb for my body less class methods so that's why I must have never seen the functionality. However I still do believe the feature I suggested would be a nice add.

Thank you for your time.

**Comment by sean-mcmanus** [comment]
The lightbulb for Create Definition is only in VS 2017, so we'd have to port that feature over to VS Code.

**Comment by jaynadeau** [comment]
I use this feature in Eclipse CDT as well. It would be a nice to have.

**Comment by codingspirit** [comment]
It's a painful task to copy every method declaration from .h to .cpp . It will be great if this feature can be added.

**Comment by rrodrigues** [comment]
+1

**Comment by futuristek** [comment]
+1 too.

**Comment by bobbrow** [comment]
Please vote by using the ![image](https://user-images.githubusercontent.com/12818240/49176786-79929800-f300-11e8-8612-a593607db469.png) button on the original issue (pick the 👍 icon).  This will help us track the priority of the feature request.

**Comment by sean-mcmanus** [comment]
We're going to use issue https://github.com/Microsoft/vscode-cpptools/issues/664 to track the "Create Definition" feature.
