### ISSUE TITLE
Unable to get rid of green squiggly line

### ISSUE THREAD

**Issue by tkazik** [microsoft/vscode-cpptools#1528]
Minor issue, but I am sure you guys know what I am missing:
Simplistic program, that runs fine, only a green squiggly line below the include is bothering me a bit. Intellisense wants to add the tr1 subfolder and thereafter continues adding folders, that are already included in the c_cpp_properties.json file. Any ideas?

Some screenshots:
![greensquigglyline](https://user-images.githubusercontent.com/15689124/35916338-655aed98-0c0a-11e8-8cab-ed4731c5c62e.png)

![cpp_properties](https://user-images.githubusercontent.com/15689124/35916348-6c3122b8-0c0a-11e8-8e7a-26c043a6fe97.png)

![settings](https://user-images.githubusercontent.com/15689124/35916357-6f51e70c-0c0a-11e8-9461-00147cc3a6ee.png)

![cmd](https://user-images.githubusercontent.com/15689124/35916463-c0cd90ae-0c0a-11e8-84a1-830ee7dd5cd8.png)

Thank you!

**Comment by sean-mcmanus** [comment]
The Add include path suggestions is based on a recursive search of your browse.path setting, but your browse.path appears to be insufficient to contain the correct file. Can you change your browse.path to the roots, such as "C:/MinGW64/mingw64/lib/gcc/x86_64-mingw32/7.2.0/include" and "C:/MinGW64/mingw64/include" (without the * which makes it non-recursive). And you probably will want "${workspaceRoot}" too unless you're folder is extremely big. That should enable the include path suggestion to include the correct path to add. If it prompts for include paths that are already there ignore those paths (I think we have an issue open to avoid duplicate suggestions).

**Comment by tkazik** [comment]
Thank you for the hints!
Unfortunately, the suggestions are still here to include already included paths.
I discovered you opened issue a few days ago: https://github.com/Microsoft/vscode-cpptools/issues/1489
This is kind of similar, but the suggestions don't stop, even after adding the path.

**Comment by sean-mcmanus** [comment]
Which file is still missing? wchar.h? Is the file path of that in the includePath?

We might have some issue with gcc 7.2.0 we need to investigate. A similar report is https://github.com/Microsoft/vscode-cpptools/issues/1520 .

**Comment by tkazik** [comment]
There isn't a file missing. Intellisense just continues to suggest more and more include paths.
If I follow the suggestions, I end up with an include path like this:
![include_path](https://user-images.githubusercontent.com/15689124/36000988-22f1db62-0d25-11e8-8fed-7c3a9aad4efb.png)

**Comment by sean-mcmanus** [comment]
The includePath code action is only supposed to appear if it detects a header file that can't be found. Is there an "#include error detected." message in your problems pane? Which file does it say it cannot open?

**Comment by fexolm** [comment]
That looks really similar to what i was talking about in #1520.

**Comment by tkazik** [comment]
Apparently it is ´stddef.h´.

![stddef](https://user-images.githubusercontent.com/15689124/36078457-d8892d42-0f76-11e8-9b47-0d7c7c4e83f4.png)

**Comment by bobbrow** [comment]
Where did you get your MinGW from?  I have [msys2](http://www.msys2.org/) with GCC 7.2.0 and `<iostream>` resolves ok with the default system include path (no need for tr1).

**Comment by ghost** [comment]
Having the exact same problem. MinGW 4.5.1. All the required `include` paths have been added to `c_cpp_properties.json`. Tried both recursive and non-recursive paths. I can confirm `stddef.h` exists in the path but the green squiggly line appears below the `#include` statement. Message in the Problems pane says

![image](https://user-images.githubusercontent.com/7196815/36386477-dfad82ce-1563-11e8-8b59-3d55de3e1bb2.png)

 OS: Windows 7 64-bit. Latest stable VS Code.

```
$ gcc -v -E -x c++ - < /dev/null
Using built-in specs.
COLLECT_GCC=C:\openlogic\gcc\4.5.1-mingw64-i686\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../libexec/gcc/i686-w64-mingw32/4.5.1/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: /openlogic/gcc/src/gcc/configure --target=i686-w64-mingw32 --host=i686-w64-mingw32 --prefix=/openlogic/gcc/4.5.1-mingw64-i686 --with-sysroot=/openlogic/gcc/4.5.1-mingw64-i686 --enable-targets=all --build=i386-redhat-linux CPPFLAGS=-I/openlogic/gcc/4.5.1-mingw64-i686/include LDFLAGS=-L/openlogic/gcc/4.5.1-mingw64-i686/lib --enable-lto --enable-libstdcxx-debug --enable-languages=c,c++,fortran,objc,obj-c++ --disable-werror --disable-nls --disable-win32-registry --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-lib32 --enable-lib64 --disable-shared
Thread model: win32
gcc version 4.5.1 (GCC)
COLLECT_GCC_OPTIONS='-v' '-E' '-mtune=generic' '-march=pentiumpro'
 c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../libexec/gcc/i686-w64-mingw32/4.5.1/cc1plus.exe -E -quiet -v -iprefix c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../lib/gcc/i686-w64-mingw32/4.5.1/ -isysroot c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../../4.5.1-mingw64-i686 - -mtune=generic -march=pentiumpro
ignoring duplicate directory "c:/openlogic/gcc/4.5.1-mingw64-i686/lib/gcc/../../lib/gcc/i686-w64-mingw32/4.5.1/include/c++"
ignoring duplicate directory "c:/openlogic/gcc/4.5.1-mingw64-i686/lib/gcc/../../lib/gcc/i686-w64-mingw32/4.5.1/include/c++/i686-w64-mingw32"
ignoring duplicate directory "c:/openlogic/gcc/4.5.1-mingw64-i686/lib/gcc/../../lib/gcc/i686-w64-mingw32/4.5.1/include/c++/backward"
ignoring nonexistent directory "c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../../4.5.1-mingw64-i686/openlogic/gcc/4.5.1-mingw64-i686/lib/gcc/i686-w64-mingw32/4.5.1/../../../../include"
ignoring duplicate directory "c:/openlogic/gcc/4.5.1-mingw64-i686/lib/gcc/../../lib/gcc/i686-w64-mingw32/4.5.1/include"
ignoring duplicate directory "c:/openlogic/gcc/4.5.1-mingw64-i686/lib/gcc/../../lib/gcc/i686-w64-mingw32/4.5.1/include-fixed"
ignoring duplicate directory "c:/openlogic/gcc/4.5.1-mingw64-i686/lib/gcc/../../lib/gcc/i686-w64-mingw32/4.5.1/../../../../i686-w64-mingw32/include"
ignoring nonexistent directory "c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../../4.5.1-mingw64-i686/mingw/include"
#include "..." search starts here:
#include <...> search starts here:
 c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../lib/gcc/i686-w64-mingw32/4.5.1/include/c++
 c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../lib/gcc/i686-w64-mingw32/4.5.1/include/c++/i686-w64-mingw32
 c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../lib/gcc/i686-w64-mingw32/4.5.1/include/c++/backward
 c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../lib/gcc/i686-w64-mingw32/4.5.1/include
 c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../lib/gcc/i686-w64-mingw32/4.5.1/include-fixed
 c:\openlogic\gcc\4.5.1-mingw64-i686\bin\../lib/gcc/i686-w64-mingw32/4.5.1/../../../../i686-w64-mingw32/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"
COMPILER_PATH=c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../libexec/gcc/i686-w64-mingw32/4.5.1/;c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../libexec/gcc/;c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../lib/gcc/i686-w64-mingw32/4.5.1/../../../../i686-w64-mingw32/bin/
LIBRARY_PATH=c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../lib/gcc/i686-w64-mingw32/4.5.1/;c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../lib/gcc/;c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../lib/gcc/i686-w64-mingw32/4.5.1/../../../../lib32/;c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../lib/gcc/i686-w64-mingw32/4.5.1/../../../../i686-w64-mingw32/lib/;c:/openlogic/gcc/4.5.1-mingw64-i686/bin/../lib/gcc/i686-w64-mingw32/4.5.1/../../../
COLLECT_GCC_OPTIONS='-v' '-E' '-mtune=generic' '-march=pentiumpro'
```

**Comment by tkazik** [comment]
I got it from here:

https://sourceforge.net/projects/mingw-w64/

Maybe I should also try another one...

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
