### ISSUE TITLE
No snippet completions after '#'

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-cpptools#1531]
### Reproduction
1. Make sure you have snippets with '#' as the first character.
2. Type '#'.
3. You get no completions for snippets.

This is probably because '#' is a trigger character for completions. I think snippets with '#' at the front are quite common so it makes sense to still have snippet completions after '#'.

### Versions
OS: Ubuntu 16.04.3 amd64
VS Code: 1.19.3 (Stable)
C/C++: 0.14.6
Other Extensions: `hars.CppSnippets` 0.0.13

**Comment by sean-mcmanus** [comment]
Our next release should have a fix -- our registration of `#` as a trigger character broke this. A workaround is to type `#` and then hit escape. We can't really support `#` as a trigger character unless all the other completion providers are also triggered, so `#` won't show all the available keywords, but it will show completions/snippets as soon as you type a letter.

**Comment by sean-mcmanus** [comment]
@segevfiner Snippets after # should work now with 0.15.0.
