### ISSUE TITLE
False error

### ISSUE THREAD

**Issue by sylveon** [microsoft/vscode-cpptools#1538]
The following code produces an IntelliSense error in VSCode with all the C++ settings at their defaults:

```cpp
#include <windows.h>
#include <tchar.h>

int main()
{
    TCHAR path[MAX_PATH];
    return _tcslen(path);
}
```

![](https://files.charlesmilette.net/FlawlessBurlywoodPeafowl)

Yet, when built with MSVC/Visual Studio,no error is shown by IntelliSense

![](https://files.charlesmilette.net/HighlevelMountainousConure)

I'm running Windows 10 build 17093, VSCode 1.19.3, addon version 1.13.1.
Visual Studio is at version 15.5.5

(Looks like it's thinking that I'm trying to use std::experimental::filesystem::v1::path instead of the locally declared `path` array)

**Comment by sean-mcmanus** [comment]
Our default "defines" settings has "UNICODE" defined. Removing that fixes the issues (do an Edit Configuration to access the c_cpp_properties.json). Is that acceptable or did you want us to investigate changing the default defines? I'm not sure why we have UNICODE defined by default -- maybe @bobbrow knows.

**Comment by sylveon** [comment]
Visual Studio also has UNICODE defined by default:

![](https://files.charlesmilette.net/NimblePoorIlsamochadegu)

**Comment by sean-mcmanus** [comment]
Adding "_UNICODE" fixes it (VS also defines that by default). It looks like we should add _UNICODE to our defaults too.
