### ISSUE TITLE
[Feature Request] Option to disable comment auto-formatting

### ISSUE THREAD

**Issue by Zooce** [microsoft/vscode-cpptools#1539]
I'd like to request that an option be exposed to disable auto-formatting of comments. When I start a Doxygen comment with `/**`  and hit `Enter` a leading asterisk is automatically added to subsequent lines. However, the code base in which I work, prohibits the use of leading asterisks in Doxygen comments like this:

```
/**
 * This function doesn't do anything, so why are you calling it? 
 * << bad times
 * @param [in] aStartIndex  The start index..duh
 * @param [in] aEndIndex  Not the start index :)
 */
void
MyFunction
    ( int aStartIndex
    , int aEndIndex
    );
```

I've asked about this in the core vscode repo, but I was told that cpptools is responsible. If I'm filing this feature request in yet again the wrong place, please let me know. Thanks!

**Comment by bobbrow** [comment]
Yes, this comes from our extension.  Help me understand your requirements better.  Are you saying that when you press <kbd>Enter</kbd> after the question mark you want the comment to look like this?
```
/**
 * This function doesn't do anything, so why are you calling it? 
   Here is some more information about the function with no '*' to the left.
 * @param [in] aStartIndex  The start index..duh
 * @param [in] aEndIndex  Not the start index :)
 */
void
MyFunction
    ( int aStartIndex
    , int aEndIndex
    );
```

**Comment by Zooce** [comment]
Sorry, I should have clarified. Here's what I want to end up with:

```
/**  << when i hit Enter here, don't automatically put a leading asterisk on the next line
    This function doesn't do anything, so why are you calling it? 

    @param [in] aStartIndex  The start index..duh
    @param [in] aEndIndex  Not the start index :)
*/
void
MyFunction
    ( int aStartIndex
    , int aEndIndex
    );
```

Basically, after I type `/**` and hit Enter, I just want to go to the next line like any other time I hit Enter, and not have any specially formatting happen.

**Comment by bobbrow** [comment]
Thanks for the clarification.  I am thinking about adding a setting that lets you specify which opening characters will initiate a multi-line comment.  Another user asked for support for `/*` and I believe `/*!` is another comment starter that QT users might use.  So I believe the setting would take an array of starter combinations and we would register the matching patterns with VSCode.  If you don't want multi-line comments then you would specify no patterns.

For example:
`C_Cpp.multilineCommentBegin = [ "/*", "/**" ]`
or
`C_Cpp.multilineCommentBegin = []`

**Comment by sean-mcmanus** [comment]
Yeah, I like that idea (the other issue is https://github.com/Microsoft/vscode-cpptools/issues/1100 ).

The options with doxygen are http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html .

**Comment by Zooce** [comment]
@bobbrow, that sounds like a great way to handle this. Quick question, when a multi-line comment is initiated, what determines the automatic leading characters of the subsequent lines? For example, if I had `C_Cpp.multilineCommentBegin = [ "//!" ]`, what would happen when I hit Enter? What I'd like to see is:
```
//! << I hit Enter here
//! << Doxygen is recognized and continues the pattern
```

@sean-mcmanus, good call on mentioning the Doxygen documentation. We use `//!` style quite often, so I wouldn't mind that one auto-formatting.

**Comment by Zooce** [comment]
To expand upon the idea (although, it might be overkill for this) is to do something like this:
```jsonc
"C_Cpp.multilineCommentPatterns": [
    {
        "start": "/**",
        "continue": " *",  << all lines between "start" and "end" get this prefix
        "end": " */"  << if this value is present, add it to the last comment line
    },
    {
        "start": "//!",
        "continue": "//!"
    }  << no "end" pattern
]
```

**Comment by bobbrow** [comment]
A note for anyone considering helping out with this.  The code with the patterns currently lives in [Extension/src/LanguageServer/extension.ts](https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/extension.ts). I am considering moving this logic out into its own file and exporting a method to provide the patterns to VS Code.

**Comment by bobbrow** [comment]
I started playing around with this a bit.  The "end" label seems to be unnecessary for both cases.  And I think the continue label can be defaulted such that either a string or an object can be passed in to the setting's array.  Default continuation for multiline comment would be " * ".  Default continuation for single line comment would be the start pattern.

```
"C_Cpp.multilineCommentPatterns": [
    "/*!",
    { "start": "/**, "continue": " + " },
    "//!",
    "///"
]
```

**Comment by Zooce** [comment]
Can you clarify what you mean by continuation for a single line comment? Also, are you saying passing a string into the setting's array would default to a continuation of itself?

The current behavior upon hitting <kbd>Enter</kbd> the first time, is to insert both the first "continuation" line and the "end" line of the multiline comment, like so:
```
/**  << I hit Enter here
 *   << this is inserted automatically
 */  << and this is inserted at the same time
```
However, I don't see this working as well for a pattern like `//!` because you'd end up with an extra line:
```
//! This function doesn't do anything, so why are you calling it?
//!
//! @param [in] aStartIndex  The start index..duh
//! @param [in] aEndIndex  Not the start index :)
//!  << this last one is kind of awkward...
void
MyFunction
    ( int aStartIndex
    , int aEndIndex
    );
```
Any idea of how this might be handled?

**Comment by bobbrow** [comment]
Correct.  For single-line comments, the default continuation would be itself.  This is what I imagined the default would be based on your example as well as my experience using xml comments in C# which start with '///'.

Are you using another plugin that is adding the ending `*/` for you when you press <kbd>Enter</kbd> after `/**`?  Our extension does not do that.

With single line comments, there is no way for us to know when you are done.  My thought was to emulate Visual Studio and quit if the comment line is empty.  I usually have to delete the final line or use the down arrow key instead of <kbd>Enter</kbd>.

**Comment by Zooce** [comment]
Oh, you're right about inserting the "end" pattern; my apologies. I was thinking of an IDE I've used in the past (maybe Eclipse or something).

I'll just throw this thought out there: if the comment line is empty, and the continuation ends, then I'd have to start a new one manually if all I wanted was an empty comment line for readability (not that big of a deal - just a tad inconvenient):
```
//! This function doesn't do anything, so why are you calling it?
//!
//! @param [in] aStartIndex  The start index..duh    << I'd have to start again manually
//! @param [in] aEndIndex  Not the start index :)
void
MyFunction
    ( int aStartIndex
    , int aEndIndex
    );
```
FWIW, implementing this may be simpler (and a little more convenient in cases like above) to not worry at all about when to stop, rather if the current line containing the cursor begins with a matching pattern, continue it if <kbd>Enter</kbd> is pressed.

**Comment by bobbrow** [comment]
To leave empty comment lines, you should probably be able to do it with the following (note the trailing space at the end of the continuation string)
```
{
  "begin": "//!",
  "continue": "//! "
}
```
I didn't test this in the implementation I just pushed, but I will try it later.

**Comment by Zooce** [comment]
I've been testing this with 0.16.0-insiders and it's been great. Thanks @bobbrow!
