### ISSUE TITLE
jump to definition hangs up on ubuntu

### ISSUE THREAD

**Issue by je-so** [microsoft/vscode-cpptools#1541]
I am using Version 1.20.0, Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:10:15.949Z, Shell 1.7.9, Renderer 58.0.3029.110, Node 7.9.0, x64

Problem description:
I am opening Visual Studio Code. Selecting a symbol and jump to its definition.
The C source is opened in a new editor tab (temporary).
I change the source code file, save it, recompile, and run the project.
Then I undo the change, save it, recompile, and run the project.
After closing the newly opened editor tab and returning to the editor tab
open at program startup I try to select another symbol and jump to its definition.

Most of the time (3 out of 5) this does no more work. The editor just works but
jumping to declaration/definition does not and code completion just shows a 
"loading" popup.

Solution:
Manually shutting down the extension (killall -q Microsoft.VSCode.CPP.IntelliSense.Msvc.linux) without closing Visual Studio Code does solve the issue.
But trying this too often will show another popup saying "does not restart ...server..." and then
only restarting vscode + killing all hanging intellisense and linux extension processes does
resolve the issue again.

**Comment by sean-mcmanus** [comment]
This sounds like a known issue -- you need to wait for the red flame in the bottom right to disappear or the Go to Definition will be blocked by the IntelliSense process. We have various plans to fix this. Setting the intelliSenseEngine to "Tag Parser" should cause it to stop reproing, but the enhanced intelliSense features won't be enabled (e.g. error squiggles, inactive regions, accurate hover/member list completion).

**Comment by je-so** [comment]
This sounds like a known issue -- you need to wait for the red flame in the bottom right to disappear or the Go to Definition will be blocked by the IntelliSense process.

Thanks.

I tried again and waited for the red flame to disappear but waiting for more than 8 minutes did not make it disappear. So I think there is some deadlock between client and server process.

**Comment by sean-mcmanus** [comment]
The IntelliSense process could be stuck in an infinite loop, e.g. https://github.com/Microsoft/vscode-cpptools/issues/1294 . What compiler toolset are you using, e.g. gcc 7.2? Is there any way you can provide a simple repro? Or can you get a call stack of the IntelliSense process? Our insider build fixed some crashes and is using a newer parser, so it's possible it may not repro with that: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.15.0-insiders .

**Comment by je-so** [comment]
I've installed the insiders version. 
Reproducing the bug with the sequence of steps described above does no more work.
So I played around and it seems that the mouse plays a role.

Hovering over a function name and pressing ctrl (ctrl+mouse left jumps to definition) 
brings up the red flame. If I press the left mouse button after the red flame disappeared it works.
But if I press the left mouse button before the red mark disappeared sometimes it jumps to the
file but the red flame is showing up forever or sometimes it just hangs in an infinite loop always 
"loading...".

**Comment by sean-mcmanus** [comment]
Hovering invokes the IntelliSense process (flame), and ctrl+mouse invokes the Go to Definition, which can get blocked by the hovering operation. I don't know a reason why the Go to Definition would cause the red flame to get stuck though (maybe there's a deadlock somewhere). We'll try to investigate and find a repro later.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
