### ISSUE TITLE
Error Squiggles showing for valid C++ code using explicit template instantiation

### ISSUE THREAD

**Issue by 1g0rb0hm** [microsoft/vscode-cpptools#1542]
* OS: OSX 10.13.2
* VS Code: 1.20
* C/C++ extension version: 0.14.6

Error Squiggles are shown for the following sample code (see screen snap further below):

### `Test.h`

```cpp
enum Variant {
 kVariant0,
 kVariant1,
 kVariant2,
};

class Foo {
 public:
  template <enum Variant V, typename T>
  int Bar(T data);
};
```

### `Test.cpp`
```cpp
#include "Test.h"

template <enum Variant V, typename T>
int Foo::Bar(T data) {
  return static_cast<int>(V + data);
}

template int Foo::Bar<kVariant0, int>(int data);
template int Foo::Bar<kVariant1, int>(int data);
template int Foo::Bar<kVariant2, int>(int data);
// --
template int Foo::Bar<kVariant0, char>(char data);
template int Foo::Bar<kVariant1, char>(char data);
template int Foo::Bar<kVariant2, char>(char data);
```

The way the template methods are explicitly instantiated is correct and should not present any errors. I am aware that there are multiple ways of achieving explicit instantiation of templates. However, we are bound to explicitly instantiate specialisations of certain template methods in the compilation unit (`.cpp` files) as in the above simplified example.

<img width="1422" alt="vscode error squiggles - explicit template instantiation" src="https://user-images.githubusercontent.com/24808322/36064537-34f03a62-0e41-11e8-8152-6f8b33618c13.png">

Hopefully there is a way to get rid of this false positive ErrorSquiggle in a future release of this plugin. Thanks in advance for your support!

**Comment by sean-mcmanus** [comment]
I can repro it -- it's strange that it doesn't repro in the latest VS 2017...oh, it's because it only repros in clang-x64 mode.

**Comment by sean-mcmanus** [comment]
It might be related to (or the same as) https://github.com/Microsoft/vscode-cpptools/issues/871 .

**Comment by sean-mcmanus** [comment]
This appears fixed in the latest version (I think the March release got the fix).
