### ISSUE TITLE
"Learn More" button on "Configure includePath for better IntelliSense results." is broken link

### ISSUE THREAD

**Issue by rhencke** [microsoft/vscode-cpptools#1543]
OS: macOS 10.13.3 Beta (17D34a)
VS Code: 1.20.0
C/C++ for Visual Studio Code: 0.14.6

Steps to reproduce:
1) Open a C/C++ project without includePath configured. An 'Info' box pops to the top of the screen: reading 'Configure includePath for better IntelliSense results.' 
2) Click 'Learn More'.
A browser window opens, that directs first to https://go.microsoft.com/fwlink/?linkid=864631, which in turn directs to https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started.md

Actual result: The link is broken, yielding a 404.
Expected result: The link provides documentation on configuring includePath.

(maybe it should point to https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started%20with%20IntelliSense%20configuration.md now?)

**Comment by bobbrow** [comment]
Thanks for letting us know!  The go.microsoft.com link has been updated to point to the right file.
