### ISSUE TITLE
It can't hit BreakPoint when Attaching

### ISSUE THREAD

**Issue by zhangmn799** [microsoft/vscode-cpptools#1544]
**Environment data**
VS Code version:precmd1.20.0
C++ Extension version: 0.15.0
Debugger: cygwin64
OS: Win10 RS2/Ubuntu14.04-x64

**Steps to reproduce**
1.Install vscode.
2.Install c++ extension.
3.Create a folder named test, create a file named main.cpp in test as following:
![code](https://user-images.githubusercontent.com/26423555/36072094-90745c60-0f54-11e8-843f-d10d7ffc5613.PNG)
6.Compara project with command "g++ -g -o main.exe main.cpp" with cygwin64
7.Open vscode, open test folder, configure launch.json as  following:
![capture](https://user-images.githubusercontent.com/26423555/36072037-9f7b3946-0f53-11e8-9805-6e59c137f818.PNG)
8.Set a bp in line cout<<"hello world"<<endl of main.cpp.
9.F5

**Expected behavior**
It will hit bp

**Actual behavior**
It can't hit bp

**Comment by WardenGnaw** [comment]
@zhangmn799 Can you enable ```"logging": { "engineLogging": true }``` in your launch.json and copy what appears in the Debug Console?

**Comment by pieandcakes** [comment]
@WardenGnaw This is a CTI bug. I have an email on it that I will forward to you.

**Comment by qian6** [comment]
You can refer to attachment log.
[log1.txt](https://github.com/Microsoft/vscode-cpptools/files/1719126/log1.txt)

**Comment by WardenGnaw** [comment]
@pieandcakes Looks like an issue specifically with GNU gdb (GDB) (Cygwin 7.12.1-1) 7.12.1

When ```-exec-interrupt``` runs, it returns 
```
1: (340483) ->~"error return /wip/cygport-git/gdb/gdb-7.12.1-1.x86_64/src/gdb-7.12.1/gdb/windows-nat.c:2361 was 87\n"
```

**Comment by pieandcakes** [comment]
@qian6 This sounds like an issue with Cygwin. Can you see if you try an older version (7.11) and see if it reproduces?

**Comment by zhangmn799** [comment]
It can also repro when I install cgwin64-gdb(7.11)

**Comment by zhangmn799** [comment]
@pieandcakes Attach  seems like unsupport Cygwin and Mingw in windows. But it should support gdb in Linux.
this issue also repro in Ubuntu 14.04/Ubuntu 16.04.   Launch.json as following:
![launch](https://user-images.githubusercontent.com/26423555/37136028-cc21c9d4-22da-11e8-9696-5f77e41f6cc6.PNG)
F6(Pause) is invalid.
![f6](https://user-images.githubusercontent.com/26423555/37136900-76e2b8a8-22de-11e8-84d2-c618b16b1f14.PNG)

**Comment by pieandcakes** [comment]
Attach is supported for MinGW/Cygwin, but the problem is because pause requires users to go to the terminal and press `Ctrl + C` to interrupt the app before breakpoints are bound and for pause to work. you can do it before or after. That has been documented before and is by design as its a limitation of the tool set.

**Comment by RobertWZ** [comment]
is the problem  solved?

**Comment by pieandcakes** [comment]
@RobertWZ Which problem are you referring to? If you are talking about the `Ctrl + C` that's an issue between Windows and MinGW/Cygwin not having a good way for us to pause the debuggee through code.
