### ISSUE TITLE
cant use intellisense

### ISSUE THREAD

**Issue by vamsis-adapa** [microsoft/vscode-cpptools#1545]
#include errors detected. Please update your includePath. IntelliSense features for this translation unit (C:\Users\Vamsi Adapa\Desktop\cs lab f111\random.c) will be provided by the Tag Parser.
when I  use update intellisense with location of json file this error occurs "Invalid escape character in string."
on trying to save file this notification appears "Failed to parse "c:\Users\Vamsi Adapa\Desktop\.vscode\c_cpp_properties.json": Unexpected token P in JSON at position 286"
.txt version of json extension file

[New Text Document.txt](https://github.com/Microsoft/vscode-cpptools/files/1714897/New.Text.Document.txt)

**Comment by sean-mcmanus** [comment]
Your usage of `\` in the path needs to changed to`\\` or `/`.

**Comment by vamsis-adapa** [comment]
Now the Error 'C:/Users/Vamsi Adapa/Desktop/.vscode/c_cpp_properties.json" could not be parsed. Using 'includePath' setting in c_cpp_properties.json" is showing.

**Comment by bobbrow** [comment]
I see you pasted a path to **c_cpp_properties.json** into the `"compileCommands"` field.  These two are not compatible.  Compile Commands has a very specific format.  If your build system is not generating this file for you, then you should delete that line.

The rest of your "Win32" config looks incorrect too.  It appears that you renamed the "Mac" configuration, but I recommend that you just delete the "Mac" and "Linux" configs if you are not using them.

**Comment by vamsis-adapa** [comment]
Thanks for the suggestion. I ended up adding my compiler path into the include path and path. It seems to be working now.
