### ISSUE TITLE
C_Cpp.errorSquiggles parameter not working

### ISSUE THREAD

**Issue by palonso** [microsoft/vscode-cpptools#1551]
Hello,
I wanted to report a buggy behaviour just in case someone finds the same problem.
I'm using VS Code Version 1.20.0 with C/C++ version 0.14.6 over Linux 17.10. I've noticed that after a fresh install without modifing any default paramenter the error squiggles were not displaying when opening a folder containing c++ files (Only red squiggles for the missing includes)
The console output at the program start is:
> IntelliSense Engine = Default.
> Autocomplete is enabled.
> Error squiggles are disabled.

Changing the parameter `C_Cpp.errorSquiggles` had no effect. However, following this [issue](https://github.com/Microsoft/vscode-cpptools/issues/1167) I disabled and enabled back `C_Cpp.intelliSenseEngineFallback` which enabled the green squiggles on the includes. Then it was posible to enable the error squiggles through a menu next to the yellow bulb (no matter the value of `C_Cpp.errorSquiggles`)

**Comment by bobbrow** [comment]
Was `C_Cpp.errorSquiggles` set in the Workspace Settings or a settings.json file in your code folder?

![image](https://user-images.githubusercontent.com/12818240/36162049-3a3116da-109a-11e8-89a0-16e0091a8b60.png)

The only thing I can think of is that settings can be overridden on a per folder basis.  So if you were changing the "User Settings" (the global settings), but the folder you opened had a different value for the "Workspace Settings" (the local settings) then your change would have no effect.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
