### ISSUE TITLE
Show numeric value of unsigned char using Intellisense

### ISSUE THREAD

**Issue by jlj-ee** [microsoft/vscode-cpptools#1552]
Is there any way to force VS Code/cpptools to display the numeric (decimal/hex) value of an unsigned char/uint8_t instead of the character literal, when hovering over a variable or constant? So instead of the values shown below:
![uint8_t](https://user-images.githubusercontent.com/11401637/36161623-2298ec06-10b2-11e8-8b91-03d9c4848204.png)
we could see:
`const uint8_t OUTPUT_PINS[5] = {(uint8_t) 9, (uint8_t) 10, (uint8_t) 11, (uint8_t) 12, (uint8_t) 13}`

If there is no way currently to do this, would this be a feature that you would consider adding through a workspace setting?

It is understandable to have the option to display the character literals, since most people do not have the ASCII table memorized. But for that same reason, it is inconvenient to have the display only show character literals for cases when we want to treat `uint8_t` as a numeric byte value, not a character literal, as may often be the case for embedded programming.

**Comment by bobbrow** [comment]
Thank you for the suggestion.  We will put this on the backlog.

**Comment by sean-mcmanus** [comment]
Looks like VS 2017 users are having the same issue: https://stackoverflow.com/questions/46747349/how-can-i-make-vs-intellisense-in-visual-c-make-a-char-value-display-as-a-numb .

**Comment by jlj-ee** [comment]
I can confirm that changing between C and C++ language mode in VS Code 1.20.0/cpptools 0.14.6 affects this behavior for me.

**In C mode**
![uint8_t_c](https://user-images.githubusercontent.com/11401637/36171076-497e975e-10cf-11e8-9c12-8f8a9c671b98.png)

**In C++ mode**
![uint8_t_cpp](https://user-images.githubusercontent.com/11401637/36171079-4af27e48-10cf-11e8-9e70-3fe24d95c20e.png)

**Comment by plopp** [comment]
+1

**Comment by Colengms** [comment]
Open this issue against VS: https://developercommunity.visualstudio.com/content/problem/824877/intellisense-should-show-numeric-values-for-charac.html

**Comment by Colengms** [comment]
It looks like we received a fix for this from VS.  It still repro's in 1.2.2, but appears to be fixed in 1.3.0-insiders4.

**Comment by reporter123** [comment]
I hope this wasn't a switch to just integer display with no option to show the actual character.

**Comment by michelleangela** [comment]
This is now available in the 1.3.0 release version https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0
