### ISSUE TITLE
'Failed to initialize debugger terminal.' when workspaceFolder contains a space

### ISSUE THREAD

**Issue by cheeseandcereal** [microsoft/vscode-cpptools#1554]
Trying to debug a cpp program in Linux Mint with VSCode 1.20.

My launch.json is simply the auto-generated file, no modifications.

Whenever the workspaceFolder contains a space, the debugger terminal will fail to start (likely due to the need of some quotes somewhere).

When moving the entire workspace to a path without any spaces, debugging works fine.

**Comment by pieandcakes** [comment]
@cheeseandcereal Thanks for reporting this. I'll take a look.

**Comment by pieandcakes** [comment]
@cheeseandcereal: @WardenGnaw tried this out with Mint 18.3 and we can't duplicate the original issue (without my fix) with the workspace having a space in it. Can you share more details on what your configuration is?

**Comment by cheeseandcereal** [comment]
After playing around with it some more, it turns out the issue isn't the space in the workspaceFolder as I originally thought. It's actually the existence of a single single quote in the path of the workspaceFolder. For example, having my project in "/home/user/A Program" works fine, but moving this project to the directory "/home/user/A' Program" causes the issue with the debugger.

**Comment by sean-mcmanus** [comment]
This should be fixed in our Insiders build: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders . Let us know if have any issues with that.

**Comment by sean-mcmanus** [comment]
Hmm...I'm seeing "attach" debugging broken on Linux with 0.16.0-insiders (works with 0.15.0), but launch seems to work. UPDATE: It got fixed.

**Comment by WardenGnaw** [comment]
All issues fixed. Closing.
