### ISSUE TITLE
Watch Window: Pressing the del key while editing removes the whole entry

### ISSUE THREAD

**Issue by LordHog** [microsoft/vscode-cpptools#1558]
While editing a watch entry then pressing the del key would remove the entry.  I don't believe this should be the case as it should delete a character and not the whole entry.  After the entry is remove all the other entries remain in a darken state until double click on another entry

![delentry](https://user-images.githubusercontent.com/970098/36184592-9ad9eb8e-10e9-11e8-9b0e-7f29931fa0bb.gif)

**Comment by pieandcakes** [comment]
@LordHog thank you for reporting this. The watch window is not owned by our extension but rather VS Code. Can you file the issue [here](https://github.com/microsoft/vscode) so they can look into it?

**Comment by LordHog** [comment]
@pieandcakes Okay, created on VSC forum (https://github.com/Microsoft/vscode/issues/43780)
