### ISSUE TITLE
VSCode incorrectly reports namespaced base class std::unique_ptr assignment as error

### ISSUE THREAD

**Issue by Anketell** [microsoft/vscode-cpptools#1559]
OS: Ubuntu 16.04 LTS
VSCode ver: 1.20.0
C/C++ Ext ver: 0.14.6

1. Enter the following code into an editor and save.
<pre>
#include &lt;memory&gt;

namespace b
{
    class Base
    {
    };
}

namespace d
{
    class Derived : public b::Base
    {
    };
}

int main( void )
{
    auto p = std::make_unique< d::Derived >();

    std::unique_ptr< b::Base > q = std::move( p );

    return 0;
}
</pre>

VSCode incorrectly reports the error:

<pre>
no suitable user-defined conversion from "std::unique_ptr&lt;d::Derived, std::default_delete&lt;d::Derived&gt;&gt;" to "std::unique_ptr&lt;b::Base, std::default_delete&lt;b::Base&gt;&gt;" exists
</pre>

Whereas without the namespaces VSCode  correctly reports no error. 
<pre>
#include &lt;memory&gt;

class Base
{
};

class Derived : public Base
{
};

int main( void )
{
    auto p = std::make_unique< Derived >();

    std::unique_ptr< Base > q = std::move( p );

    return 0;
}
</pre>

**Comment by sean-mcmanus** [comment]
Repros on Linux/Mac, but not Windows; however, it repros in VS 2017 on Windows. Looks like the same symptom as in https://github.com/Microsoft/vscode-cpptools/issues/1395 but we didn't have a repro. I filed a VS 2017 bug at https://developercommunity.visualstudio.com/content/problem/198343/incorrect-c-intellisense-error-no-suitable-user-de.html (not sure if that's publically accessible bug it's tagged Microsoft internal).

**Comment by Anketell** [comment]
@sean-mcmanus You're right, it's not publicly accessible. 

However, it seems to differ from #1395 in that the following code doesn't report an error:

<pre>
#include &lt;memory&gt;

namespace a
{
    namespace b
    {
        namespace c
        {
            class Base
            {
            };
        }
    }
}

int main( void )
{
    auto p = std::make_unique< a::b::c::Base >();

    std::unique_ptr< a::b::c::Base > q = std::move( p );

    return 0;
}
</pre>

Nor for that mater does:
<pre>
#include &lt;memory&gt;

namespace a
{
    namespace b
    {
        namespace c
        {
            class Base
            {
            };

            class Derived : public Base
            {
            };
        }
    }
}

int main( void )
{
    auto p = std::make_unique< a::b::c::Derived >();

    std::unique_ptr< a::b::c::Base > q = std::move( p );

    return 0;
}
</pre>

**Comment by sean-mcmanus** [comment]
Fixed with 0.18.0.
