### ISSUE TITLE
Getting #include errors (intelliSense) for every Arduino project (even basic examples)

### ISSUE THREAD

**Issue by djanthony93** [microsoft/vscode-cpptools#1561]
Basically I opened the AnalogReadInput built-in Arduino example and it can't recognize any class out of the sketch. For my own sketches I get #include errors (like #include <LiquidCrystal.h>) even if I specify the correct path to my MinGW folder which is "C:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include\\c++".
These are the `arduino.json` and `c_cpp_properties.json` autogenerated by the `Arduino-initialize` command for my sketch

```
{
    "sketch": "LCD_SHIELD.ino",
    "board": "arduino:avr:uno"
}
```

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "path": [
                    "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino"
                ]
            },
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 3
}
```

How to fix? Is there any way to include automatically the whole library folder for any type of project by setting a global setting?

**Comment by sean-mcmanus** [comment]
Did you follow this guide for MinGW? https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md. The includePath is not recursive. You may also need certain defines set. If that doesn't work we could investigate more.

**Comment by djanthony93** [comment]
EDIT: I've followed the guide above setting my c_cpp_properties.json like this:

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino",
                "${workspaceRoot}",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include",
                "C:/MinGW/include",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include-fixed"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "path": [
                    "C:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino",
                    "C:/MinGW/lib/gcc/mingw32/6.3.0/include",
                    "C:/MinGW/lib/gcc/mingw32/6.3.0/include-fixed",
                    "C:/MinGW/include/*"
                ]
            },
            "intelliSenseMode": "clang-x64",
            "defines": [
                "_DEBUG",
                "UNICODE",
                "__GNUC__=6",
                "__cdecl=__attribute__((__cdecl__))"
            ]
        }
    ],
    "version": 3
}
```

Now it gives me:

```
#include errors detected. Please update your includePath. IntelliSense features for this translation unit (.ino path) will be provided by the Tag Parser.
cannot open source file "LiquidCrystal.h"
cannot open source file "dhtnew.h"
```

When I click the yellow bulb over the #include statement it says "edit includePath setting" only

[project folder](https://i.gyazo.com/96cfeb893cd9bb08ef030e7d89674820.png)

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
