### ISSUE TITLE
Go to definition is failing on arduino projects

### ISSUE THREAD

**Issue by benchuk** [microsoft/vscode-cpptools#1562]
Happens on windows more than on mac
Some times it works and than stopps
Also platform io is installed
Latest version on cpptools and vscode
Seems to work better in atom environment

**Comment by bobbrow** [comment]
I'm so sorry we missed your issue.  Something seems to have messed up in our notifications and I only saw this after searching for untagged issues with no response.

Are you still having issues with the extension?  Can you please provide more information (e.g. c_cpp_properties.json, a sample project)?

**Comment by michelleangela** [comment]
We need more information to fully investigate this issue. If you update to the latest version of the extension and your issue persists, please re-open the issue and reply with additional information that can help us investigate your issue.
