### ISSUE TITLE
identifier "strcmp" is undefined

### ISSUE THREAD

**Issue by hgroene** [microsoft/vscode-cpptools#1565]
While typing the following code strcmp is suggested, the function signature is shown, and string.h is identified as the location of the definition. strcmp is then underlined with a red squiggle with the error 'identifier "strcmp" is undefined'. 

This is happening with VSCode 1.20.1 on Ubuntu 16.04 LTS

```
#include <string.h>

int foo(void) {
    char *a, *b;

    if (strcmp(a, b) != 0) {
        return 1;
    }
    return 0;
}
```

**Comment by sean-mcmanus** [comment]
I'm not able to repro a problem. Is your includePath set correctly? What version of cpptools do you have?

**Comment by hgroene** [comment]
Cpptools is 0.14.6.
Include path is below; /usr/include is the very first directory.

I've checked several of the functions that are declared in string.h and they behave the same way. VSCode knows to suggest the function, knows the function signature and that they are declared in string.h. And then it tells me the functions are undefined. The code compiles and runs without any problems

```
            "includePath": [
                "/usr/include",
                "${workspaceRoot}",
                "${workspaceRoot}/build/dist_root/include",
                "${workspaceRoot}/build/dist_root/include/libxml2",
                "${workspaceRoot}/build/dist_root/include/cegui-0",
                "${workspaceRoot}/external/glfw-3.2.1/include",
                "${workspaceRoot}/external/glad/include",
                "${workspaceRoot}/external/glm",
                "${workspaceRoot}/external/OpenGL-Registry/api",
                "/usr/include/x86_64-linux-gnu/c++/5.4.0",
                "/usr/include/c++/5.4.0",
                "/usr/local/include",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include/linux",
                "/usr/include/X11",
                "/usr/lib/gcc/x86_64-linux-gnu/5/include",
                "${workspaceRoot}/build/external/cegui-0.8.7/samples/common/include",
                "${workspaceRoot}/external/cegui-0.8.7/samples_framework/include",
                "${workspaceRoot}/external/cegui-0.8.7/cegui/include",
                "${workspaceRoot}/src"
            ],
```

**Comment by sean-mcmanus** [comment]
Did you fix the issue? If not, you can try calling `/usr/bin/gcc -Wp,-v -E -xc -x c++ /dev/null` or whatever your compiler is and making sure the order of the system include paths match. We plan to improve this for March so you just need to set your compilerPath and the system includes will be handled correctly.

**Comment by hgroene** [comment]
Here's the output of your gcc command. 
```
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/5
 /usr/include/x86_64-linux-gnu/c++/5
 /usr/include/c++/5/backward
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "/dev/null"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "/dev/null"
```

**Comment by sean-mcmanus** [comment]
Can you add ` /usr/include/c++/5
 /usr/include/x86_64-linux-gnu/c++/5
 /usr/include/c++/5/backward
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include` to the bottom of your includePath list? You might need to remove some of the existing system paths too.

**Comment by hgroene** [comment]
I replaced the system paths with the ones the gcc command listed and the issue has gone away.
Thanks for your help.

**Comment by jaa183** [comment]
I have same problem.
the path is correct, and when I click strcpy fun with ctrl, he take me to the string.h
I look at fun decleration in it, it was:
char *_EXFUN(strcpy,(char *__restrict, const char *__restrict));

and macro:
#define _EXFUN(name,proto) name()

I use esp8266 toolchane for arduino 2.5.0
