### ISSUE TITLE
[Feature Request] find references in the c/cop code would be a very nice feature to have

### ISSUE THREAD

**Issue by zanito** [microsoft/vscode-cpptools#1567]
Hi VSCode team

I would like to congratulate the team on a fantastic work that has been done both on VSCode and on the amazing cpptools. I’ve been playing with it in a large code base and so far I think it works great. One feature I do find lacking is the “find references” for symbols in the code. Is this feature planned? is there a rough estimate for when will this feature be made available? I guess this would part of the language server. Clangd actually doesn’t provide find references as well, I guess it’s a tricky feature to implement.

Thank you very much for your great work, you have done a marvellous work! Thank you in advance for any information any of you guys can provide on this matter.

Cheers,
Filipe

**Comment by sean-mcmanus** [comment]
Yes, find all references is our most up-voted feature: https://github.com/Microsoft/vscode-cpptools/issues/15 is the issue tracking this. We plan to implement the feature but we don't have an estimated timeframe.

**Comment by zanito** [comment]
Thank you very much! I tried to search for an issue that already traced this but I failed to find it. Sorry for the entropy :). I will close this issue then

**Comment by sean-mcmanus** [comment]
Find All References is available in 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders , but you'll need to set the C_Cpp.experimentalFeatures setting to "Enabled".
