### ISSUE TITLE
visual studio code showing wrong autocomplete suggestions in c++(SDL)

### ISSUE THREAD

**Issue by LastLightSith** [microsoft/vscode-cpptools#1568]
I am trying to learn SDL in C++ So auto-complete is very essential for me.VS code was working fine with SFML but due to android problems I started learning SDL and now auto-completions for SDL is not working correctly . It always suggest some wrong members ,even If I didn't include any library . I don't have enough experience with VS . I came to VS from neovim only for auto completions which not working properly :(

![screenshot_2018-02-15_19-40-26](https://user-images.githubusercontent.com/29699740/36261816-97680046-128b-11e8-84b8-3ae78ce5f8ec.png)

**Comment by LastLightSith** [comment]
![screenshot_2018-02-15_20-12-59](https://user-images.githubusercontent.com/29699740/36262585-e7ec777a-128d-11e8-90e3-e281ba2e3af8.png)

I had tried restring ,updating and deleting .vscode dir but nothing happened

**Comment by bobbrow** [comment]
See #13.  We are still working on getting the correct IntelliSense results for non-member identifiers.  The items that currently show up in the list for "quick suggestions" come from our extension's tag parser database.  The symbols that show up in this list are controlled by the `"browse.path"` setting in your **c_cpp_properties.json** file and not by any `#include` lines in your source files.  If `SDL_CreateWindow` doesn't show up in this list, then the header that includes it is probably not accessible via the paths in the `"browse.path"` array.

**Comment by bobbrow** [comment]
We just posted an insider release with the finished auto-complete implementation.  If you want to get an early preview, you can install the VSIX that matches your OS and tell us what you think.

https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders
