### ISSUE TITLE
Intellisence file gets reset on restart

### ISSUE THREAD

**Issue by abhisina** [microsoft/vscode-cpptools#1569]
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:31:21.019Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS Linux Ubuntu 16.04 LTS

Issue: The file c_cpp_properties.json gets reset to an empty value file on each restart of VSC.

**Comment by sean-mcmanus** [comment]
I think this is caused by the cmake-tools-helper extension. Please uninstall that one. Let us know if you still have issues. Another previous report: https://github.com/Microsoft/vscode-cpptools/issues/1500
