### ISSUE TITLE
Include file not found

### ISSUE THREAD

**Issue by hexler81** [microsoft/vscode-cpptools#157]
- VSCode Version: 1.4
- C/C++Plugin Version: 0.8.1
- OS Version: Windows 10 64-Bit

Even though I have added the path to c_cpp_properties.json, the include files in that path are not being found.

The correspondig part of my c_pp_properties (which has been generated automatically by clicking the bulb icon on the include statement) looks like this:

> ```
>     {
>         "name": "Win32",
>         "includePath": ["c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include",
>                         "D:/development/example/include"],
>         "browse" : {
>             "limitSymbolsToIncludedHeaders" : true,
>             "databaseFilename" : ""
>         }
>     }
> ```

The include statement that does not work, even though the folders and files are available in the above include path, is for instance:

`#include <JacketSupport/fields.h>`

**Comment by jgoshi** [comment]
This has been fixed and will appear in the next release (version 0.9.0)
