### ISSUE TITLE
Always shows problem "file not found" in and only in the first include heading.

### ISSUE THREAD

**Issue by BladLust** [microsoft/vscode-cpptools#1571]
* Operating System and version: Windows 10 pro build 1709
    * VS Code version : 1.20.1 not Insiders build
    * All the extensions and example code below
 
![2018-02-16_193211](https://user-images.githubusercontent.com/33929696/36305823-3cc10488-1350-11e8-8134-1c37bf6be766.png)

 my c_cpp_properties.json code, and I'm sure I wrote the directory right.
![2018-02-16_193148](https://user-images.githubusercontent.com/33929696/36305878-6e57e476-1350-11e8-8b29-58b89cdc76ed.png)
 The issue is, there will always be an error at my first include, and when I build it and run it there will not be any problem at all. (My example code works perfectly but it always shows an error that says "file not found") I searched in the community and didn't find any issues identical to mine.
More examples:
![2018-02-16_193841](https://user-images.githubusercontent.com/33929696/36306090-323f6ee0-1351-11e8-9b68-ff4f1f24c2e5.png)
![2018-02-16_193926](https://user-images.githubusercontent.com/33929696/36306092-340f4a1a-1351-11e8-9059-864b3d809ea8.png)
I am new to the community so sorry if I made any mistakes.
THANK YOU !

**Comment by bobbrow** [comment]
Which file is not found?  Do you have any other extensions installed?  I believe our extension says "cannot open source file %s".

**Comment by sean-mcmanus** [comment]
The "file not found" tooltip message is from the C/C++ Clang Command Adapter extension and not the C++ extension (see also https://github.com/Microsoft/vscode-cpptools/issues/1352 ).

**Comment by OmSao** [comment]
How I resolved this issue is: As I have already manually installed LLVM in my system and there was "C/C++ Clang adapter" extension in my Visual Code. 
So, I uninstalled the adapater extension and restarted Visual Code.
