### ISSUE TITLE
compileCommands setting does not appear to account for --sysroot/target options

### ISSUE THREAD

**Issue by imerin** [microsoft/vscode-cpptools#1575]
* Ubuntu 16.04
    * VS Code version 1.20.1
    * C/C++ extension version 0.15.0

I'm cross compiling and using the --sysroot option with gcc.  The extension does not seem to account for this when loading the compile_commands.json file.  It correctly includes the header paths specified with the -I option to gcc, but does not include the headers in e.g. sysroot/usr/include.

Removing all entries from both includePath and browse.path did not fix this issue.

Adding the sysroot/usr/include directories to includePath gave me the functionality I was expecting from the compileCommands setting

**Comment by sean-mcmanus** [comment]
We should be able to add support for --sysroot for the next update.

**Comment by sean-mcmanus** [comment]
We haven't added --sysroot parsing to compile_commands.json yet, but as an alternative you might be able to set the compilerPath and add the --sysroot arg , assuming all your files use the same sysroot arg.

**Comment by imerin** [comment]
Thanks, that’s what i ended up doing until this is added to the extension.

**Comment by jimmyharris** [comment]
This also doesn't cover the -isystem flags either. (I needed to add all of those to my compilerPath for the tools to work as expected.

**Comment by sean-mcmanus** [comment]
@jimmyharris We should already handle isystem -- are you experiencing a bug with that? Can you give more details of when isystem isn't working? Something special might be causing it to fail to be parsed.

**Comment by jimmyharris** [comment]
It might be that I am having trouble getting visual studio to parse my commands database. All of the File entries are relative to the build folder where the compile database lives.

**Comment by sean-mcmanus** [comment]
Fixing https://github.com/Microsoft/vscode-cpptools/issues/1755 might fix this too.

**Comment by abmantis** [comment]
I can also confirm that the isystem paths in compile_commands.json do not take into account the --sysroot param.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
