### ISSUE TITLE
Can't launch debugging for C application (Linux)

### ISSUE THREAD

**Issue by R3D9477** [microsoft/vscode-cpptools#1576]
Hi. I tried to launch debugging process, but had exception:

`The C/C++ extension is still installing. See the output window for more information.`
(output window is empty and have not any information!)

Linux Mint 18.3 x64
VSCode 1.20.1
vscode-cpptools 0.15.0
gdb 7.11.1

[c_hello_world_mscpptools.zip](https://github.com/Microsoft/vscode-cpptools/files/1733549/c_hello_world_mscpptools.zip) with lanuch.json and tasks.json

Thanks!

**Comment by bobbrow** [comment]
The Output window has many log channels.  Did you happen to switch it to the "C/C++" channel?

![image](https://user-images.githubusercontent.com/12818240/36437985-66965ee6-161d-11e8-9121-d9cdf5658580.png)

**Comment by R3D9477** [comment]
@bobbrow I'm reinstalled all extensions just now and it solved the problem.
Thank you for participating!
