### ISSUE TITLE
Windows include for MinGW can not include chevrons

### ISSUE THREAD

**Issue by davidjpfeiffer** [microsoft/vscode-cpptools#1578]
Windows 10 version 1709
VS Code version 1.19.1 (not using the Insiders build)
C/C++ extension version 0.15.0
No other VS Code extensions installed

Steps to reproduce the problem:
 - Configure plugin according to [recommended Windows template for MinGW](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md)
 - Write C++ hello world program
 - Get intellisense errors when trying to include a C++ library with chevrons

![with](https://user-images.githubusercontent.com/8846738/36344029-cf64cf02-13d9-11e8-809d-f7b653bad36a.PNG)
![without](https://user-images.githubusercontent.com/8846738/36344030-cf78e1cc-13d9-11e8-8a15-7489eaf7ca93.PNG)

**Comment by sean-mcmanus** [comment]
I don't think `#include "<iostream>"` is valid syntax. Do you mean `#include <iostream>`?

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.

If you update to the latest version of the C/C++ extension and your issue persists, please re-open the issue and reply with additional information that can help us investigate your issue.
