### ISSUE TITLE
std::string_view intellisense missing (CMake, VC++ 2017)

### ISSUE THREAD

**Issue by parkovski** [microsoft/vscode-cpptools#1579]
I'm using cpptools 0.15.0, VSCode 1.20.1, VS2017 15.5.6, Win10 insiders 17074, CMake tools 0.10.4. I am working on a CMake project using the VS2017 generator to build, and setting C++17 mode using these options (I know compile commands doesn't do anything with my current generator):
```cmake
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
```

I have no problem with `std::optional`, and everything compiles fine, but I get intellisense warnings about namespace std not having a member `string_view`. I can add `_HAS_CXX17` to the defines in my `c_cpp_properties.json` and that gets rid of the errors, but I don't think that should be necessary - or is there another way to inform intellisense that I'm using C++17 that I'm not aware of?

**Comment by sean-mcmanus** [comment]
It works for me with the latest VS 2017 15.6 Preview. I think your version of the library might require _HAS_CXX17 defined. You might be passing c++latest to your compiler which might be causing that _HAS_CXX17 to be defined.

**Comment by ajoseps** [comment]
I'm also facing this issue in VSCode 1.21.1 with cpptools 0.15.0. Relevant [StackOverflow](https://stackoverflow.com/questions/49397233/how-to-enable-c17-support-in-vscode-c-extension?noredirect=1#comment85832165_49397233)

**Comment by parkovski** [comment]
I'm using CMake, and the generated project (vcproj) sets `<LanguageStandard>stdcpp17</LanguageStandard>`. Aside from that, I don't see "17" or "latest" anywhere in the project. This is the beginning of my `string_view` header:
```c++
// string_view standard header
// Copyright (c) Microsoft Corporation. All rights reserved.
#pragma once
#ifndef _STRING_VIEW_
#define _STRING_VIEW_
#ifndef RC_INVOKED
#include <xstring>
#include <xstring_insert.h>

#if !_HAS_CXX17
 #error string_view is only available with C++17.
#endif /* _HAS_CXX17 */
```

Based on this, I'm guessing that the compiler sets `_HAS_CXX17` implicitly when the standard is set, but intellisense either doesn't, or doesn't recognize the way CMake is setting C++17 mode, because I don't have to add that option to the compiler's command line to build successfully, I just have to add it to intellisense defines in `c_cpp_properties.json`. I've been keeping up on updates and still have this issue.

Here is my full `c_cpp_properties.json` that enables working intellisense:
```json
{
    "configurations": [
        {
            "name": "null",
            "includePath": [
                "C:\\Users\\parker\\Documents\\GitHub\\o2\\build",
                "C:\\Users\\parker\\Documents\\GitHub\\o2\\include",
                "C:\\Users\\parker\\Documents\\GitHub\\o2\\include\\o2",
                "D:\\dev\\vcpkg\\installed\\x64-windows\\include",
                "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\ATLMFC\\include",
                "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\include",
                "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um",
                "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\ucrt",
                "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\shared",
                "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\um",
                "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\winrt"
            ],
            "defines": ["_HAS_CXX17"],
            "browse": {
                "path": [
                    "C:\\Users\\parker\\Documents\\GitHub\\o2\\build",
                    "C:\\Users\\parker\\Documents\\GitHub\\o2\\include",
                    "C:\\Users\\parker\\Documents\\GitHub\\o2\\include\\o2",
                    "D:\\dev\\vcpkg\\installed\\x64-windows\\include",
                    "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\ATLMFC\\include",
                    "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\include",
                    "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um",
                    "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\ucrt",
                    "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\shared",
                    "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\um",
                    "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\winrt"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 3
}
```

When I remove the `_HAS_CXX17` define, I get intellisense errors on `string_view`, but the project still builds fine.

If this doesn't help, I might be able to help more if you can point me to where intellisense is finding its language standard setting and implicit defines.

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.

If you update to the latest version of the C/C++ extension and your issue persists, please re-open the issue and reply with additional information that can help us investigate your issue.
