### ISSUE TITLE
Incorrect intellisense warning in launch.json for gdb attach

### ISSUE THREAD

**Issue by huili80** [microsoft/vscode-cpptools#1581]
In a launch.json that's configured to launch gdb to attach, intellisense warns that "Property setupCommands is not allowed" even though it actually is allowed and I use it to enable pretty printing.

**Comment by pieandcakes** [comment]
@huili80 can you share a screenshot of this? Usually this indicates either the extension isn't installed correctly or you have a duplicate block or you have `attach` specified instead of `launch`.

**Comment by huili80** [comment]
It's ```attach```. What's strange is, even though intellisense says ```setupCommands``` isn't allowed, i can still use it to enable pretty printing.

**Comment by pieandcakes** [comment]
@huili80 Are you sure it (the pretty printing) is working? I'll take a look at the code and see if it gets passed because i didn't think it did. If it does, i can update the schema in `package.json` to have it back.

**Comment by huili80** [comment]
Yes, pretty printing definitely is enabled by way of setupCommands for attach, just like for launch, as of the latest version of both vscode and cpptools.
		
		

		Sent from iPhone
	




On Tue, Feb 20, 2018 at 3:56 PM -0500, "Pierson Lee" <notifications@github.com> wrote:












@huili80 Are you sure it (the pretty printing) is working? I'll take a look at the code and see if it gets passed because i didn't think it did. If it does, i can update the schema in package.json to have it back.
