### ISSUE TITLE
Preprocessor block folding

### ISSUE THREAD

**Issue by kevinmoran** [microsoft/vscode-cpptools#1584]
```cpp
void foo()
{
    int x = 10;
#if 0
    int y = x;
#else
    int y = x + 1;
#endif
    // etc.
}
```

If I try to collapse foo() in VSCode it will only fold as far as `#if 0` due to the tab alignment. Aligning preprocessor statements to the left regardless of the alignment of the block itself is an extremely common style. It would be lovely if code folding understood that they are inside a function and should be folded with it.

**Comment by sean-mcmanus** [comment]
I don't believe we can implement this yet -- see https://github.com/Microsoft/vscode/issues/3422 .

**Comment by sean-mcmanus** [comment]
We're tracking this with https://github.com/Microsoft/vscode-cpptools/issues/407 .
