### ISSUE TITLE
Need a way to target a specific Windows SDK/Visual Studio version

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1585]
I created a `c_cpp_properties.json` file from the default template to use with MSVC on Windows, and it looks like the system includes must be included in the include path. On my computer these paths are as follows:

```json
"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/include/*",
"C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/um",
"C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/ucrt",
"C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/shared",
"C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/winrt",
```

This makes it impossible to share the `c_cpp_properties.json` to other users who might have different versions of Visual Studio or Windows SDK installed (or if they're installed to a different location), unless they manually edit the file. This is clearly not ideal for open source projects where I might want to include this file in the repository.

Is there something that I'm missing?

**Comment by sean-mcmanus** [comment]
Maybe we should add some special variable like `{latestVCPath}` and `{latestWindowsSDKPath}`? That would also solve the annoying problem that causes the paths to become invalid after a newer version is installed and the old one removed.

**Comment by ghost** [comment]
I think that'd make sense for MSVC, but I think there's also the problem of having to specify the default include path for other compilers? Could the default include paths be queried from the compiler?

**Comment by sean-mcmanus** [comment]
We already query the compiler for the default include path for clang/gcc-based compilers and we're adding a compilerPath setting in case the compiler we guess is incorrect. On Windows we do other stuff to locate the VC and Windows SDKs, but the problem with "forcing" this always is that sometimes the version we choose is not the one desired (i.e. too new).

**Comment by ghost** [comment]
I see. I feel like it might be useful being able to specify version ranges for these (something like `"windowsSDK": "[10.0,11.0)"`), but even just `${latestVCPath}` and `${latestWindowsSDKPath}` would be great.

**Comment by bobbrow** [comment]
Perhaps the work I'm doing for #1338 will help.  Part of this configuration change will remove the requirement to put system headers in c_cpp_properties.json.  There is nothing in there about choosing the Windows SDK right now, but it's something we're thinking about and will improve in the future.

**Comment by ghost** [comment]
Yes, it'd be great if we no longer had to specify the system include paths. Not being able to choose the Windows SDK version is not a deal-breaker for me.

**Comment by bobbrow** [comment]
We will be exposing a setting that will allow you to override the system includes (and therefore the WindowsSDK) to an older one if you really want.  It will be called `"C_Cpp.defaultSystemIncludePath"`

**Comment by bobbrow** [comment]
A preview of this is available in the [insiders build](https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.0-insiders) if you would like to try it out and provide feedback.

**Comment by bobbrow** [comment]
I'm going to use this issue to track a more convenient way to pick a Windows SDK instead.  The only thing that might hinder the original issue of portability is the "compilerPath" property, but the spec in #1338 addresses this by allowing you to specify "${default}" as the compilerPath and then require you to set the `"C_Cpp.default.compilerPath"` setting instead.

**Comment by sean-mcmanus** [comment]
0.17.5 enables targeting a specific Visual Studio version via setting the compilerPath to the cl.exe used, but there's no way to set the Windows SDK used yet.

**Comment by bobbrow** [comment]
We should add a new Windows-only property to `c_cpp_properties.json` like we did for Mac Frameworks.

**Comment by sean-mcmanus** [comment]
windowsSdkVersion has been added to c_cpp_properties.json with 0.17.7.
