### ISSUE TITLE
C/C++: Language identifier identifies C's .h files as C++ syntax highlighting doesn't work as a result

### ISSUE THREAD

**Issue by ebuka-o** [microsoft/vscode-cpptools#1586]
- C/C++ Extension Version: 0.15.0
- VSCode Version: 1.20.1
- OS Version: Windows 10 1709

Other Extensions Downloaded (although C/C++ is the only one I'm using actively):
- C# Version: 1.14.0
- Language Support for Java Version: 0.19.0
- Ocaml Version: 0.643
- Prolog Version: 0.0.4
- Ruby Version: 0.16.0

Note: I noticed this issue right after I updated to VS Code 1.20.1. I posted this issue to Microsoft/vscode, but I was told to post here instead of there.

Steps to Reproduce:

1. Open C .h file with code in between an #ifdef and #endif macro
2. The chunk of code in between the preprocessor will be grayed out (no syntax highlighting), and the
     language mode will now be C++ instead of C.
3. Changing the file.associations settings in User/Workspace settings can fix the incorrect C++ file 
    association, but it does not fix the lack of syntax highlighting.

**Comment by sean-mcmanus** [comment]
The grayed out code is because the code is inactive to our IntelliSense parser. You can add things to the defines or set the intelliSenseMode to "Tag Parser". We're adding a setting to disable colorization in our next version. And we have an issue on VS Code to support opacity so it isn't gray: https://github.com/Microsoft/vscode/issues/43004 .

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.

If you update to the latest version of the C/C++ extension and your issue persists, please re-open the issue and reply with additional information that can help us investigate your issue.
