### ISSUE TITLE
Parse #defines and #includes from Makefile

### ISSUE THREAD

**Issue by veto-gh** [microsoft/vscode-cpptools#1587]
VSCode cpptools is now able to display preprocessor blocks as inactive (see #1466).

To make this feature (and others) work reliable with Makefiles it would be great if the extension could parse preprocessor commands specified in Makefiles, most commonly defines and includes:
```
ifdef FOO
  CFLAGS += -DBAR   # define BAR
  CFLAGS += -I/usr/include/libpng12   # include /usr/include/libpng12
endif
```
(full documentation [here](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#Preprocessor-Options))

In this context it would also be great if compiler options yielded by [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) would get recognized too.
I.e. this is widely used in Makefiles:
```
CFLAGS += $(shell pkg-config --cflags gtk+-3.0)
```

**Comment by idanpa** [comment]
I use [Bear](https://github.com/rizsotto/Bear) to generate the appropriate compile_commands.json from Makefiles.
I use a task which is doing `make clean; bear -a -o .vscode/compile_commands.json make all;` to refresh the database.

**Comment by Prathik-Jain** [comment]
Hi @idanpa , 
Bear seems like an option, do want to tell us how you have set it up, to work with vs code, or do you extract the lines and put them in `c_cpp_properties.json`? 

Thanks :small_airplane:

**Comment by Prathik-Jain** [comment]
Got it, 
`"compileCommands": "${workspaceFolder}/.vscode/compile_commands.json"`
adding this line in the first object of `configurations` array in the `c_cpp_properties.json` file works!

**Comment by bobbrow** [comment]
We have been working on an extension that will extract information from Makefile projects and use that information to configure IntelliSense.  We are at a point where the extension is working with a number of Makefile projects that we've tested (including the linux kernel) and we're ready to start sharing the extension more broadly.  We would certainly love to hear your feedback.

If you would like to participate in an early preview of the extension, please add a 👍 to this comment and I will grant you access to the repository (currently private) where the extension is being developed.  You should then get an invite from GitHub to join the repository where I will post more information/instructions.

EDIT: please reply back here if you have any trouble getting access to the repository.

**Comment by bobbrow** [comment]
Just a note that the 6 of you who have added a 👍 to the previous comment have been granted access to the repo.  Please check your notifications/email if you haven't received it.

**Comment by nschmeller** [comment]
I came to this repo to file this issue--super glad it's already being worked on! 

Could I get access to the preview repo? Thanks!

**Comment by bobbrow** [comment]
@nschmeller, you have been added.  For all those who gave a 👍 to the comment earlier, I have granted you access and it appears that many of you still have an invitation pending.  If you haven't accepted already, please [go here](https://github.com/microsoft/vscode-makefile-tools/invitations).

And just a side note, we do plan to make this repo public very soon, so access will not be gated by invites at that time.

**Comment by KrestenHelstrup** [comment]
> @nschmeller, you have been added. For all those who gave a 👍 to the comment earlier, I have granted you access and it appears that many of you still have an invitation pending. If you haven't accepted already, please [go here](https://github.com/microsoft/vscode-makefile-tools/invitations).
> 
> And just a side note, we do plan to make this repo public very soon, so access will not be gated by invites at that time.

Could you give me access also ?
When do you estimate that the repo will be public ?

**Comment by sean-mcmanus** [comment]
@KrestenHelstrup Bob might be on vacation...might be back Nov 30th.
@andreeis Might know more about an ETA (not sure if she'll get this message though).

**Comment by KrestenHelstrup** [comment]
@nschmeller - Any updates on the release of this and the possibility for me to get beta access ?
Thanks in advance.

**Comment by nschmeller** [comment]
> @nschmeller - Any updates on the release of this and the possibility for me to get beta access ?
> Thanks in advance.

I think it's open to the public! I can access it without signing in [here](https://github.com/microsoft/vscode-makefile-tools).

**Comment by KrestenHelstrup** [comment]
Thanks - sounds great with marketplace soon.

**Comment by Colengms** [comment]
The Makefile extension has been published to the Marketplace.  Closing this issue.  :)
