### ISSUE TITLE
Go To Declaration has stopped working

### ISSUE THREAD

**Issue by varnk** [microsoft/vscode-cpptools#1588]
Just recently the C++ Go To Declaration quit working.  In fact, none of the symbol look-ups are working.  Not sure why.

**Comment by mundodisco8** [comment]
Hey!

Same here. My .vscode folder is empty, and when I try to create a new c_cpp_properties.json I get a 
"command 'C_Cpp.ConfigurationEdit' not found" error. It started to happen yesterday, when I updated to the latest version. As a matter of fact, none of the c/cpp commands work. I tried uninstalling the extension and reinstalling but doesn't help. @varnk, can you check if you have these issues too?

**Comment by varnk** [comment]
I tried to uninstall and re-install too.  It didn't seem to fix the problem.    I get a bunch of messages in the console window that seem to indicate that there are updates that can't be installed, but the marketplace doesn't seem to have any connectivity issues, just the plug-in does.

Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...

**Comment by sean-mcmanus** [comment]
Can you download the offline .vsix that matches your OS at https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.15.0 and do "Install from VSIX..."?

**Comment by varnk** [comment]
Yes, downloading the VSIX and manually installing it seems to work.

**Comment by mundodisco8** [comment]
Same here, VSIX solved the issue. Any idea why the extension broke?

**Comment by sean-mcmanus** [comment]
That's the reason we have the offline .vsix's available. For whatever reason, the online downloading mechanism fails to work sometime for some people. We haven't been able to identify any reason for the failure. It works in general. We're not able to repro any problem. When the online installer fails, we should show a message with a link to the offline .vsix to install.

**Comment by varnk** [comment]
As a suggestion, is there some way that the plug-in symbol-lookups can continue to function after the online download failure occurs?  Right now, when the download fails, the plug-in will no longer be able to jump to symbols until a successful VSIX update is applied.

**Comment by bobbrow** [comment]
The problem is that VSCode deletes the previous version's binaries when it auto-upgrades you so there's no way to revert back at that point.  If this is a recurring problem, you could add `"extensions.autoUpdate": false` to your settings.json.  Unfortunately, our extension doesn't have much control over the update process.

**Comment by bobbrow** [comment]
(but you did get me thinking about whether we could try downloading the matching VSIX for you from GitHub automatically, and maybe extracting the dependencies from there.  That might give us some insight into whether the download failure is caused by our CDN or your proxy settings.  hmm...)

**Comment by varnk** [comment]
I have a feeling that it is a proxy issue.  I don't know much about our IT infrastructure, but if I were to guess, there is probably a firewall rule that allows GitHub through.  That may be the reason why marketplace updates work, but the plug-in symbol update do not.
