### ISSUE TITLE
Intellisense Lightbulb does not appear when green squiggle clicked in C++ file

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-cpptools#159]
Moved from Microsoft/vscode#10695

---

From @DavidA2014 
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:
1. Open a folder with C++ files in it
2. With no c_cpp_properties.json file in .vscode directory ...
3. #include directives will be underlined with green squiggle
4. This link: 

http://code.visualstudio.com/docs/languages/cpp

says:

> To enable code completion and navigation, you will need to generate a c_cpp_properties.json file:
> 
> Hover over any green squiggle in a source file (e.g. a #include statement).
> Click the lightbulb that appears underneath the mouse cursor.
> Click Add include path to settings.

When I click the green squiggle no lightbulb appears.

**Comment by jgoshi** [comment]
Which version of cpptools are you using? When I tried this with VSCode 1.4, cpptools 0.8.1, Windows 10 it worked (when I click the green squiggle (or put the keyboard cursor on that line using the arrow keys) then the lightbulb appears.

**Comment by daldr-ntml** [comment]
Sorry, tried it again and I agree it works. Perhaps I just hovered over the squiggle previously.
Thanks for your reply. Please close this issue.

**Comment by jgoshi** [comment]
Thank you for verifying.

**Comment by sean-mcmanus** [comment]
I may have reproed this bug...but it's seemed random or had some unknown repro requirement. I'll try to investigate if I get another repro, but it seems like it would be a VS Code but and not our extension.
