### ISSUE TITLE
Debugger cannot enter c code

### ISSUE THREAD

**Issue by simon-p-r** [microsoft/vscode-cpptools#1591]
Hi

I am having a problem with debugging a  project with Visual Code cpptools.  The problem is I cannot enter breakpoint within debug mode the files appear as blacked out.  Hopefully the attached picture shows the problem.  I have tried various things and the symbols for the dll according to console are being loaded so unsure why I can't access the code.  Project is x86 is this causing the problem?

![vs-debugger](https://user-images.githubusercontent.com/4668724/36420400-cf4b764c-162c-11e8-857a-a9573732d7ce.png)

My environment info is below

Windows 10 Enterprise
Version 1709
OS Build 16299.248

Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

 C/C++ extension version 0.15.0

Visual Studio 2015 Update 3

**Comment by pieandcakes** [comment]
@simon-p-r When you compiled, did you specify the command flag to include symbols for debugging? for g++ the flag is `-g`. By looking at your screenshot, that seems to be what you are missing.

**Comment by simon-p-r** [comment]
@pieandcakes pieandcakes the compiler was missing the /Zi flag even though I set it to debug builds, I forced a rebuild and it has no worked.   Thanks for your swift response!
