### ISSUE TITLE
[Question] How to disable conditional-compile-based coloring?

### ISSUE THREAD

**Issue by fiigii** [microsoft/vscode-cpptools#1592]
Today, after I updated the latest VS Code, most of the conditional-compiled code path becomes gray.
The cpptools/vscode seems not able to find compile-flags from CMake files. How can I disable the feature?
![image](https://user-images.githubusercontent.com/1263030/36456304-1c9c6dd0-1659-11e8-8fab-8754cc43b37c.png)

**Comment by sean-mcmanus** [comment]
There's one workaround at https://github.com/Microsoft/vscode-cpptools/issues/1466 . You can also set the intelliSenseEngine to "Tag Parser". We're planning to add a setting to disable this in our next release.

**Comment by fiigii** [comment]
@sean-mcmanus Thank you!
