### ISSUE TITLE
C/C++ IntelliSense engine problem

### ISSUE THREAD

**Issue by GriffenJohn** [microsoft/vscode-cpptools#1594]
I'm using vs code to write c code for a week, and found a problem(don't know if this is a bug).
I opened an exist C project folder and fixed the include path problems, none error occurred and the IntelliSense engine worked quite well. But soon I found that in somewhere it just didn't show the function's arguments (/the member list) when I finished typing a function name (/a structural variable). For example, it works well in line 32, but strikes in line 41 in a C file.
I made a gif, but there's something wrong with the uploading, try later

**Comment by GriffenJohn** [comment]
![intellisense](https://user-images.githubusercontent.com/36688398/36467107-37c7f808-1718-11e8-9fd8-3b2f6aec4a7f.gif)

**Comment by bobbrow** [comment]
I am having a hard time seeing what is being typed, but it looks like #13 which I am working on right now.  I'm hoping to have it ready for the March release.

**Comment by GriffenJohn** [comment]
![main c - stm32f7 - visual studio code 2018_2_22 10_32_36 00_00_00-00_00_20](https://user-images.githubusercontent.com/36688398/36517403-de803c6a-17bc-11e8-891e-ca6c9efed337.gif)

this is a clear picture, I don't think it's the same as #13  Code complete is OK, the structural member is matching well, problem is suggestions didn't show up in some lines.

**Comment by sean-mcmanus** [comment]
@bobbrow I think it's an issue with the signature help not working. The IntelliSense process might be crashing? We might need a repro. The high hitting add_expression_to_index crash can occur with signature help invocation. Not sure if the tag parser signature help is supposed to be used in that situation.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
