### ISSUE TITLE
Please add support for intellisence for /clr

### ISSUE THREAD

**Issue by manbearian** [microsoft/vscode-cpptools#1596]
I have a C++ project with code that must be compiled with /clr.

Please add support for intellisence for /clr

**Comment by smartdevoloper** [comment]
digitel convertion stsy in life

**Comment by sean-mcmanus** [comment]
We added C++/CLI support in https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders2 (cpptools-win32.vsix) via setting the compilerPath to "pathToCl.exe /clr". Let us know if you think other flags are important to support. Flags that just modify the compiler defines should work after we add support for that (only implemented for gcc/clang currently), but other flags that change the language behavior require us to explicity convert the flags to values our parser understands (e.g. values in the msvc.json files next to the binaries).

![image](https://user-images.githubusercontent.com/19859882/37853869-c16da4aa-2ea5-11e8-99f2-38dbe48fe54d.png)
