### ISSUE TITLE
Cannot jump to definition of local variable

### ISSUE THREAD

**Issue by cszang** [microsoft/vscode-cpptools#1597]
I am using the latest stable VSCode 1.20.1 on macOS 10.13.3 with a vanilla setup except for having installed cpptools 0.15.0 from the extension manager.

Considering a very basic file

```c++
int example(int number) {
    return number;
}

int main() {
    int myinteger;
    myinteger = example(12);
    return 0;
}
```

I can jump to the definition of `example`, but not to the definition of `myinteger`. I believe this should be possible? Which settings am I possibly missing? Hovering over `myinteger` correctly says `int myinteger`, so somehow Code is aware of the definition anyway...

**Comment by bobbrow** [comment]
This doesn't work yet.  We are in the process of transitioning between two different IntelliSense engines.  Goto definition doesn't work for local variables yet, but hover does.  We are tracking this with #255.

**Comment by sean-mcmanus** [comment]
Go to Definition on the myinteger local variable works with 0.19.0.
