### ISSUE TITLE
Doc Blocks don't remain starred on subsequent lines

### ISSUE THREAD

**Issue by DonoA** [microsoft/vscode-cpptools#1598]
Not fully sure if this is a c/c++ extension bug or not, however documentation blocks no longer continue their star formatting like the used to.
For example, this is what happens now when I go to a new line:
![capture](https://user-images.githubusercontent.com/6405401/36575261-ec3af68c-17fe-11e8-98aa-0d51d0d0a053.PNG)
This is what used to happen:
![capture](https://user-images.githubusercontent.com/6405401/36575284-13bb7ce0-17ff-11e8-93d0-4bcd63d35342.PNG)

If this is not your problem just let me know and I'll move my issue to the main VS code repo.

Edit:
I am running C/C++ 0.15.0 and VS code 1.20.1. I was running C/C++ 0.14.6 when this was working.

**Comment by sean-mcmanus** [comment]
We never implemented continuation via /* -- we do it for /**. Our next release will make it more customizable -- https://github.com/Microsoft/vscode-cpptools/issues/1539 ...so /* would be doable.

**Comment by DonoA** [comment]
I see, however this does not seem to be working either. I start a comment with `/**` and hit enter and nothing follows.

**Comment by bobbrow** [comment]
Just double checking...  does the status bar in the lower right corner say that the file is a C or C++ file?

![image](https://user-images.githubusercontent.com/12818240/36606658-3fb37af8-1879-11e8-97a1-11bccd659541.png)

I don't repro this on 0.15.0 with VS Code 1.20.1.  `/**` followed by <kbd>Enter</kbd> works for me.

**Comment by bobbrow** [comment]
(do you have any other extensions installed that might be interfering?)

**Comment by DonoA** [comment]
I am in C mode and I have disabled all other plugins. When I set the file to C++ (its in C normally) this still does not work. Just to be sure, this should work all the time right? I don't need to be directly above a function for this to work, correct?

**Comment by bobbrow** [comment]
It is regular expression based.  It should work everywhere.  What are your indentation settings?

![comments](https://user-images.githubusercontent.com/12818240/36611097-34e5e4c2-1887-11e8-83c7-1fb29ecf7f15.gif)

**Comment by sean-mcmanus** [comment]
We're not able to repro any issue with 0.15.0. It's possible another extension is interfering. @bobbrow  Any ideas what could cause a failure? Oh, I didn't see Bob's comment :)

**Comment by DonoA** [comment]
The only possible issues as I see it is that I don't have the `msys2` in the corner of my screen and that my node version is `7.9.0`. If you cannot reproduce with those settings I think it is fair to call this un-reproducible.

**Comment by DonoA** [comment]
I did some more research and located the developer console (sorry, should have checked this earlier). The output was the following: https://hastebin.com/exiducivar.tex

**Comment by sean-mcmanus** [comment]
It looks like the node_modules/vsocde-languageclient is not getting installed for some reason. You could try uninstalling/reinstalling the extension or running npm install in the ms-vscode.cpptools-0.15.0 folder. Not sure yet how we can auto-detect/fix this.

**Comment by DonoA** [comment]
I ran npm install from my node command line, restarted vs code and reloaded the plugin and now things are working.  npm installed a __lot__ of dependencies, the only one already installed was `vscode-extension-telemetry@0.0.11`.

Thanks so much for your help!

**Comment by bobbrow** [comment]
Glad it's working for you now.  This is really concerning if we can't trust VS Code to upgrade our extension properly. 😕  I'm considering adding code to check if the old binaries are still around since we've seen cases of that as well.
