### ISSUE TITLE
Integrated terminal for debugging

### ISSUE THREAD

**Issue by Garzet** [microsoft/vscode-cpptools#1600]
Is there a way to use integrated Terminal for debugging/launching code instead of Debug Console?

Currently, I'm using external console window for debugging code in VSCode, but it's not very convenient while debugging on full screen since it goes into background. The problem with the Debug Console is that it does not allow input, so my program is stuck if it requires any input and I don't use the external console.

Or, is there a way to feed intput into Debug Console?

**Comment by pieandcakes** [comment]
@Garzet We don't have integrated Terminal yet (see #371)  and we have plans to do it, just that it hasn't been done yet. There is no current method to enter input in the debug console.
