### ISSUE TITLE
compiled a.exe is not launching 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-cpptools#1601]
_From @SPK-RPI on February 22, 2018 6:48_

### Issue Type
Bug

### Description

my root folder is in onedrive i have compiled a programe in c++ the generated a.exe file was launching in debugger before until now.the programe is running when i run outside vs code but not in it.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|Memory (System)|5.95GB (2.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-phpfmt|kok|1.0.18
vscode-JS-CSS-HTML-formatter|lon|0.2.3
cpptools|ms-|0.15.0

</details>
Reproduces only with extensions

_Copied from original issue: Microsoft/vscode#44178_

**Comment by pieandcakes** [comment]
@spk-rpi can you provide a launch.json configuration? Also when you say it isn't running in VSCode, are you saying you can't debug it or you get an error message that is telling you it fails to launch?

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
