### ISSUE TITLE
No definition/declaration found even though mouseover correctly shows the type

### ISSUE THREAD

**Issue by huili80** [microsoft/vscode-cpptools#1602]
Intellisense clearly knows the type, but when i click on "go to/peek declaration/definition" it tells me no declaration/definition found. I'm certain that intellisense knows the type because it correctly figured out whether a type is a ```class``` or a ```struct``` when mouseover it. But what could cause it not be able to jump to or peek the declaration/definition? All of my ```C_Cpp.*``` configs are the default except error squiggles are disabled.

**Comment by huili80** [comment]
Not only this happens for types, it's the same with enums too. Mouseover even shows the correct numeric value of a enumerator but it can't peek or go to the definition.

**Comment by bobbrow** [comment]
Thank you for your feedback.  We're still working on this.  See #255.

**Comment by sean-mcmanus** [comment]
Go to Definition for class and enum definitions should work with 0.19.0 (including anything else defined in the current translation unit, i.e. the cpp file or its included headers).
