### ISSUE TITLE
can't run code

### ISSUE THREAD

**Issue by BuWH** [microsoft/vscode-cpptools#1606]
**the source code:**

#include <iostream>
using namespace std;

int main(){
    cout<<"hello";
    return 0;
}

**after I "Run Code":**

wenhedeMacBook-Pro:.vscode wenhe$ cd "/Users/wenhe/Documents/我的坚果云/编程/折腾/.vscode/" && g++ test -o  && "/Users/wenhe/Documents/我的坚果云/编程/折腾/.vscode/"
clang: error: argument to '-o' is missing (expected 1 value)

**And then:**
wenhedeMacBook-Pro:.vscode wenhe$ g++ test   && "/Users/wenhe/Documents/我的坚果云/编程/折腾/.vscode/"
ld: warning: ignoring file test, file was built for unsupported file format ( 0x23 0x69 0x6E 0x63 0x6C 0x75 0x64 0x65 0x20 0x3C 0x69 0x6F 0x73 0x74 0x72 0x65 ) which is not the architecture being linked (x86_64): test
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pieandcakes** [comment]
@BuWH you have a few issues with your code and your commands

>#include

You need to include a library, you can't just have #include

>wenhedeMacBook-Pro:.vscode wenhe$ cd "/Users/wenhe/Documents/我的坚果云/编程/折腾/.vscode/" && g++ test -o && "/Users/wenhe/Documents/我的坚果云/编程/折腾/.vscode/"
clang: error: argument to '-o' is missing (expected 1 value)

When compiling with `-o` you need to specify your output target. Clang gives you an error here which looks like you are ignoring. Also, you need to compile with the `-g` flag for symbols.

>wenhedeMacBook-Pro:.vscode wenhe$ g++ test && "/Users/wenhe/Documents/我的坚果云/编程/折腾/.vscode/"

I don't know what you are trying to do here so i don't know what to do wiht your error message.

all these items seem to be related to compilation from a command line and not anything to do with VS Code. Can you explain what you are trying to do?

**Comment by WardenGnaw** [comment]
@BuWH The error ```ld: warning: ignoring file test, file was built for unsupported file format ( 0x23 0x69 0x6E 0x63 0x6C 0x75 0x64 0x65 0x20 0x3C 0x69 0x6F 0x73 0x74 0x72 0x65 ) which is not the architecture being linked (x86_64): test
Undefined symbols for architecture x86_64:
"_main", referenced from:
implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

Comes from clang. You need to specify the extension of the source code file to be .c or .cpp

e.g. test.c or test.cpp

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.
