### ISSUE TITLE
Active preprocessor blocks greyed out

### ISSUE THREAD

**Issue by stmon** [microsoft/vscode-cpptools#1607]
Version 0.15.0: February 15, 2018

When using macro specified below the code that should be active is greyed out. It seems that defined() operator inside macro is not working properly. When defined() is used directly the code is colorized correctly.

```
#define EXAMPLE_ENABLED 1
#define MODULE_ENABLED(module) ((defined(module##_ENABLED) && (module##_ENABLED)) ? 1 : 0)
// #define MODULE_ENABLED(module) (((module##_ENABLED)) ? 1 : 0) /* working */

#if MODULE_ENABLED(EXAMPLE)  /* not working */

// #if (defined(EXAMPLE_ENABLED) && (EXAMPLE_ENABLED))  /* working */

/* greyed out start */

#include "example.h"

int example_is_rnd_number_odd(void) {

    int result;
    result &= 0x01;

    return result;
}

/* greyed out end */

#endif // RDE_MODULE_ENABLED(EXAMPLE)
```

![image](https://user-images.githubusercontent.com/1108331/36646516-cbf3245e-1a78-11e8-93bb-49cd0b61a817.png)

**Comment by sean-mcmanus** [comment]
This scenario works for me. @bobbrow @grdowns Are you guys able to repro this?

**Comment by stmon** [comment]
OK, I changed IntelliSenseEngine to "C_Cpp.intelliSenseEngine": "Tag Parser", and it is working now.

**Comment by stmon** [comment]
When my IntelliSenseEngine is set to "Default" the code is greyed out but
when I change it to "Tag Parser" code is colorized as should be.

**Comment by grdowns** [comment]
I have not been able to repro this on Ubuntu 16.04. @stmon does this bug manifest immediately on re/load of the file, or does it only manifest after performing some edits on the file? If it's the former, does opening the file in a new instance of VSCode still cause the bug to manifest?

**Comment by stmon** [comment]
This bug manifest immediately when opening the file but it must be first saved after editing.
I am running vscode (1.20.1 x64) on windows 10 enterprise. It doesn't matter where I open the file the behavior is the same.

It seems that when using #if directive directly everything works but when it is called through macro the coloring fails.

Line 3. -> OK
Line 4. -> NOT OK

```
1. #define EXAMPLE_ENABLED 1
2. #define MODULE_ENABLED(module) ((defined(module##_ENABLED) && (module##_ENABLED)) ? 1 : 0)
3. #if ((defined(EXAMPLE_ENABLED) && (EXAMPLE_ENABLED)) ? 1 : 0)  /* working */
4. #if MODULE_ENABLED(EXAMPLE)  /* not working */
```

**Comment by stmon** [comment]
@grdowns @sean-mcmanus.... you were probably not able to reproduce the issue because the default intelliSenseMode on Linux is set to "clang-x64"? Correct me if I am wrong.
If I add c_cpp_properties.json file and set "intelliSenseMode" from "msvc-x64" to "clang-x64" everything works as should.
Of course this will not work if I open the file alone in new window.

**Comment by sean-mcmanus** [comment]
@stmon Yeah, you're right. We're able to repro the bug now. Thanks for reporting this.

**Comment by sean-mcmanus** [comment]
Oh, it turns out this is "by design". The Microsoft cl.exe emulated with msvc-x64 mode behaves this way, and it doesn't repro with clang-x64 mode, because the gcc/clang compiler behaves as your code intends. Which compiler are you using? You should make sure the intelliSenseMode matches your compiler.

**Comment by stmon** [comment]
I am using gcc. This should then not be a problem if the source file is open within workspace/folder.
Thanks for your effort.
