### ISSUE TITLE
red squiggle under #include <iostream>

### ISSUE THREAD

**Issue by mattmular** [microsoft/vscode-cpptools#1609]
My code:
`#include <iostream>
using namespace std
int main() {
cout << "Hello World!";
return 0;
}`

c_cpp_properties.json:
```
{
   "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/mingw32",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/backward",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include",
                "C:/MinGW/include",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include-fixed"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/MinGW/lib/gcc/mingw32/6.3.0/include",
                    "C:/MinGW/lib/gcc/mingw32/6.3.0/include-fixed",
                    "C:/MinGW/include/*"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```

I found someones includePath and browser.path settings because I've spent hours trying to get this to work, it removed the red squiggle under "#include <iostream>" but iostream clearly doesn't work. How do I find out what to put in my includePath and browse.path settings?

**Comment by sean-mcmanus** [comment]
intelliSenseMode should be clang-x64. You're also missing some required defines. Have you seen https://github.com/Microsoft/vscode-cpptools/blob/e6d8d1fb28dd38f3a1e39762dad4744c9705bad4/Documentation/LanguageServer/MinGW.md ?

**Comment by L-Sun** [comment]
if you install package _C/C++ Clang Command Adapter_, try add settings in your workspace settings file as flows
```
"clang.cxxflags": [
        "-IC:/MinGW/lib/gcc/mingw32/6.3.0/include/c++
]
```

**Comment by bobbrow** [comment]
The MingGW documentation has been updated.  You can remove system includes/defines from c_cpp_properties.json and just set the "compilerPath" property to the path to your MInGW compiler.

https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md
