### ISSUE TITLE
VS Code becomes unresponsive inside Docker container

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-cpptools#1610]
_From @davefinster on February 26, 2018 5:50_

- VSCode Version: 1.19.3
- OS Version: 4.13.0-32-generic #35-16.04.1-Ubuntu SMP

Steps to Reproduce:

1. Open VS Code to my current project (reasonable C++ project)
2. Right click on a symbol and select "Show Declaration"
VS Code becomes unresponsive with this printed in the console (running --verbose)
```
Server response: <?xml version="1.0" encoding="UTF-8"
[VS Code]: detected unresponsive
```  

Does this issue occur when all extensions are disabled?: Yes - produces [this output](https://gist.github.com/davefinster/dff77d77f739cd58322d267afecfaae2) and crashes immediately upon launch.

To provide some background, this instance of VS Code is running inside a Debian docker container with the following parameters:
```
docker run --net=host --name container -i -t -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --privileged --restart unless-stopped <image-name>
```
I'm not sure how to debug this further and determine why VS Code has become unresponsive.

_Copied from original issue: Microsoft/vscode#44385_

**Comment by weinand** [comment]
_From @kdkeyser on February 26, 2018 8:55_

I run into the same issue. Behaviour seen both with C++ as well as a Haskell project, so likely unrelated to the plugins. Same project/plugins running natively (so not in docker) works fine.

**Comment by sean-mcmanus** [comment]
It repros without the C++ extension, right? Why is this our issue? Where does "Show Declaration" come from? I don't see that. I see "Go to" and "Peek" Definition. Our "Go to Definition" can get blocked by our IntelliSense thread, but it won't cause VS Code itself to be unresponsive.

**Comment by weinand** [comment]
@sean-mcmanus you are right, you can close this and I will reopen the original issue.
