### ISSUE TITLE
Intellisense not working with mapped drive

### ISSUE THREAD

**Issue by rianquinn** [microsoft/vscode-cpptools#1614]
I have a VM with ssh enabled and use SFTP Net Drive 2017 to map the VM's file system to Windows 10 which works great. VSCode can work on the file without issue, but Intellisense doesn't seem to work, stating that it cannot find files. 

- VSCode Version: 1.20.1
- OS Version: Windows 10

Steps to Reproduce:

1. Map VM file system using SFTP Net Drive 
2. Open project, and Intellisense will not work. 

Here is my configuration:
```JSON
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "G:\\working\\hypervisor\\build\\prefixes\\x86_64-vmm-elf\\include",
                "G:\\working\\hypervisor\\build\\prefixes\\x86_64-vmm-elf\\include\\c++\\v1",
                "G:\\working\\hypervisor\\build\\prefixes\\x86_64-userspace-elf\\include",
                "G:\\working\\hypervisor\\build\\prefixes\\x86_64-userspace-elf\\include\\c++\\v1",
                "G:\\working\\hypervisor\\build\\prefixes\\x86_64-test-elf\\include",
                "G:\\working\\hypervisor\\build\\prefixes\\x86_64-test-elf\\include\\c++\\v1",
                "G:\\working\\hypervisor\\bfdriver\\include",
                "G:\\working\\hypervisor\\bfdummy\\include",
                "G:\\working\\hypervisor\\bfelf_loader\\include",
                "G:\\working\\hypervisor\\bfintrinsics\\include",
                "G:\\working\\hypervisor\\bfm\\include",
                "G:\\working\\hypervisor\\bfsdk\\include",
                "G:\\working\\hypervisor\\bfunwind\\include",
                "G:\\working\\hypervisor\\bfvmm\\include",
                "G:\\working\\extended_apis\\include",
                "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/include/*",
                "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/atlmfc/include/*",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/um",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/shared",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/winrt"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "VMM",
                "NATIVE",
                "ENABLE_BUILD_TEST",
                "_HIPPOMOCKS__ENABLE_CFUNC_MOCKING_SUPPORT"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/include/*",
                    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/atlmfc/include/*",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/um",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/ucrt",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/shared",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/winrt"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "C:/.vscode/browse.VC.db"
            }
        }
    ],
    "version": 3
}
```

**Comment by sean-mcmanus** [comment]
Can you give more info on what files intellisense can't find? Are some files found? If you're using a clang/gcc-based compiler you should use the clang-x64 intelliSenseMode. Also, you should remove the Microsoft/Windows paths if you're not using those. You may also want to add the includePath's to the browse.path.

**Comment by rianquinn** [comment]
Sorry for the delay, I wanted to play with this some more and I still cannot figure it out. It cannot find any files from the mapped drive at all. However, if I place some of the files on the C drive, it works fine. I also tried putting the files on my D drive, which is a secondary hard drive that I have, and that worked fine too. But placing those same files on my G drive, which is my mapped drive, fails. I am not using clang as I am using MSVC, and I don't think that matters anyways as it works fine if the files are on C\D. I also tried placing the paths in the browse.path, and that didn't help

**Comment by rianquinn** [comment]
Another interesting issue is that it cannot even find relative includes like:

```
#include "../../../hve/arch/intel_x64/control_register.h"
#include "../../../hve/arch/intel_x64/cpuid.h"
#include "../../../hve/arch/intel_x64/monitor_trap.h"
#include "../../../hve/arch/intel_x64/mov_dr.h"
```

The error I get is: `cannot open source file "xxx"`

**Comment by Colengms** [comment]
Hi @rianquinn .  This issue has been open with 'more info needed' for quite a while.  If you are still seeing an issue, let us know, and we can reopen.

**Comment by ocgltd** [comment]
It seems that clang creates separate processes to compile, and the other processes don't have access to the network mapped drive.

I'm experiencing similar issue (in an unrelated project) and found this topic to be almost identical.  If you find a solutions that would be great.
