### ISSUE TITLE
Every time a file is saved the tag parser scans dependencies

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#1619]
When saving an edited file, we tag parse it again to ensure the database is up to date.  It appears that we are also re-scanning the \#includes unnecessarily.  The timestamps are usually the same so no actual parsing happens, but this is needlessly doing a stat on potentially tons of files each time you save your edits.

**Comment by sean-mcmanus** [comment]
This is intentional -- is this causing any observable performance issue? It should only do a stat 1 time per file...I don't think that should cause a detectable performance impact.

**Comment by bobbrow** [comment]
Oh, right.  A `#include` line could have been added which would require us to reparse dependencies.  I filed this because I was seeing a lot of log messages after each save and I wasn't editing `#includes` at the time.
