### ISSUE TITLE
Go to definition fails to open file

### ISSUE THREAD

**Issue by edumunoz** [microsoft/vscode-cpptools#162]
On OS X 10.10.5 and the newest version of VSCode Insiders (a7190d61e061b969129776cedd13a77b68ec406b), opening files from the language service is failing. It seems like the forward slashes are being escaped but VSCode is not expecting that.

<img width="1006" alt="screen shot 2016-08-23 at 10 56 45 am" src="https://cloud.githubusercontent.com/assets/637952/17903436/4ff0a922-6920-11e6-94e8-c0e451def4a8.png">

This does not occur for other languages such as TypeScript. My suspicion is that maybe VSCode has changed behavior that the language service relied on.

@sridmad

**Comment by jgoshi** [comment]
This has been fixed and will appear in the next cpptools release (version 0.9.0)
