### ISSUE TITLE
Expose the inactive lines color setting so it can be set via color scheme

### ISSUE THREAD

**Issue by skelliam** [microsoft/vscode-cpptools#1620]
It's true that Visual Studio does *not* (I don't think) allow changing this, but Eclipse and others do.  Specifically I would like to have a shaded background for inactive preprocessor blocks, like the first image in issue #510.  (In fact, this image may have come from Eclipse)

So in the color scheme, could we have a scope like "meta.preprocessor.inactive" or something, that would let users adjust the color to their liking?  

Here is an example setting in the color scheme:
![image](https://user-images.githubusercontent.com/830788/36765841-2dd9cfd6-1c01-11e8-8278-0aad72425c51.png)

Thank you!

**Comment by sean-mcmanus** [comment]
0.18.0 should have the fix: C_Cpp.inactiveRegionForegroundColor and C_Cpp.inactiveRegionBackgroundColor settings.
