### ISSUE TITLE
Cpp: Don't disable syntax highlighting when vscode doesn't find the macro definition.

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-cpptools#1623]
_From @zouyxdut on February 24, 2018 11:35_

I have some codes like following:

```
#ifdef A_MACRO
// some codes cannot be highlighted!!
#endif
```
How to enable syntax highlight for such code? I don't want this feature.

_Copied from original issue: Microsoft/vscode#44326_

**Comment by aeschli** [comment]
@zouyxdut What extension do you use for C++? ms-vscode.cpptools?

**Comment by aeschli** [comment]
That's what I see without any extensions enabled:
![image](https://user-images.githubusercontent.com/6461412/36727239-d43bdad0-1bbc-11e8-9dc9-8ca44eeb7529.png)

Please give a more complete example to illustrate the problem.

**Comment by aeschli** [comment]
_From @zouyxdut on February 28, 2018 2:44_

I installed ms-vscode.cpptools, when I disable this, the problem solved.

I guess this feature was introduced recently, since I‘ve never met this before.

**Comment by bobbrow** [comment]
This is covered by #1574.  The setting will be added in the next release.
