### ISSUE TITLE
When using a WSL mingw32/Win10 configuration, __cplusplus is still 199711L

### ISSUE THREAD

**Issue by bpetto35** [microsoft/vscode-cpptools#1625]
OS: Window10 and LSW Ubuntu 17.10
VSCode: 
> Version 1.20.1
> Commit f88bbf9137d24d36d968ea6b2911786bfe103002
> Date 2018-02-13T15:34:36.336Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64
> 

C/C++: 0.15.0

VisualCode is run directly on Windows
From internal terminal, I open a bash.

Mingw32 is
```
i686-w64-mingw32-gcc -v -E -x c++ - < /dev/null
Using built-in specs.
COLLECT_GCC=i686-w64-mingw32-gcc
Target: i686-w64-mingw32
Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir='/usr/lib/x86_64-linux-gnu' --libexecdir='/usr/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++ --enable-lto --with-plugin-ld --enable-threads=posix --program-suffix=-posix --program-prefix=i686-w64-mingw32- --target=i686-w64-mingw32 --with-as=/usr/bin/i686-w64-mingw32-as --with-ld=/usr/bin/i686-w64-mingw32-ld --enable-libatomic
Thread model: posix
gcc version 6.3.0 20170415 (GCC)
COLLECT_GCC_OPTIONS='-v' '-E' '-mtune=generic' '-march=pentiumpro'
 /usr/lib/gcc/i686-w64-mingw32/6.3-posix/cc1plus -E -quiet -v -D_REENTRANT - -mtune=generic -march=pentiumpro
ignoring nonexistent directory "/usr/lib/gcc/i686-w64-mingw32/6.3-posix/../../../../i686-w64-mingw32/sys-include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/i686-w64-mingw32/6.3-posix/include/c++
 /usr/lib/gcc/i686-w64-mingw32/6.3-posix/include/c++/i686-w64-mingw32
 /usr/lib/gcc/i686-w64-mingw32/6.3-posix/include/c++/backward
 /usr/lib/gcc/i686-w64-mingw32/6.3-posix/include
 /usr/lib/gcc/i686-w64-mingw32/6.3-posix/include-fixed
 /usr/lib/gcc/i686-w64-mingw32/6.3-posix/../../../../i686-w64-mingw32/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"
COMPILER_PATH=/usr/lib/gcc/i686-w64-mingw32/6.3-posix/:/usr/lib/gcc/i686-w64-mingw32/6.3-posix/:/usr/lib/gcc/i686-w64-mingw32/:/usr/lib/gcc/i686-w64-mingw32/6.3-posix/:/usr/lib/gcc/i686-w64-mingw32/:/usr/lib/gcc/i686-w64-mingw32/6.3-posix/../../../../i686-w64-mingw32/bin/
LIBRARY_PATH=/usr/lib/gcc/i686-w64-mingw32/6.3-posix/:/usr/lib/gcc/i686-w64-mingw32/6.3-posix/../../../../i686-w64-mingw32/lib/../lib/:/usr/lib/gcc/i686-w64-mingw32/6.3-posix/../../../../i686-w64-mingw32/lib/
COLLECT_GCC_OPTIONS='-v' '-E' '-mtune=generic' '-march=pentiumpro'

```

In the following code
```
#include <mutex>

std::mutex lock

```
VisualCode/C++ intellisense prompt an error 

> namespace "std" has no member "mutex"

In the file c_cpp_properties.json, I have set all path to a local installation of mingw-w64 because VisualCode cannot search path with LSW :/
I have a Visual Studio 2017 community copy installed to develop previous version. As we have jump to jhbuild mingw libs on all our project, I have to link against mingw static libs. To continue to develop under Windows, I make the choice of VisualCode.

I try to define **\_\_GNUC\_\_=5** and **__cplusplus=201103L** to overide define but it does not work.
__cplusplus is still **199711L**

[c_cpp_properties.zip](https://github.com/Microsoft/vscode-cpptools/files/1767792/c_cpp_properties.zip)

Does it exist a way to force __cplusplus or internal define to the one mingw-w64 could use ?

These errors are just disturbing as I know it will compile. Just it is not a great help when seeking for real error as I cannot igonre them.

**Comment by sean-mcmanus** [comment]
Your intelliSenseMode should be clang-x64 if you're using mingw32. See https://github.com/Microsoft/vscode-cpptools/blob/e6d8d1fb28dd38f3a1e39762dad4744c9705bad4/Documentation/LanguageServer/MinGW.md . Does that solve your issue? Our next release will enable your to set a path to the mingw compiler you're using and obtain all the correct defines (and be able to set the cppStandard version).

**Comment by bpetto35** [comment]
It solves the issue of the define of the __cplusplus value. That's fine.

Don't know why now, all my winsock2 functions are undefined, weird. Another issue perhaps, I will dig in it.

Consider this as resolve. Thanks to point me the md file I was looking for.
