### ISSUE TITLE
Documentation: how import existing C++ code into a new project

### ISSUE THREAD

**Issue by polomora** [microsoft/vscode-cpptools#1628]
VS Code: v 1.20.1
C/C++: 0.15.0

I cannot find explained in the documentation how to import an existing C++ codebase into a VSC project / workspace. There are lots of questions about this on SO and elsewhere. Also, the concept of workspace is not clearly explained in the documentation. As fat as I can see, it is simply a way to maintain common user settings.

I want to move to VSC after trying out eclipse and netbeans, where the concept of importing existing code into a project is well established. Is VSC a fully-functional IDE?

Many thanks

**Comment by pieandcakes** [comment]
VS Code is designed as a lightweight code editor which has language services, build tasks and debugging. It is not a full fledged IDE.

Workspaces in VS Code is supposed to allow you to open your codebase’s root folder and allow you to start code editing and provide you a language service experience based on that folder. The language service will parse the folder for information and VS Code will create a .vscode folder in the workspace root to contain your workspace settings and configuration files.

That said, to start a workspace, you just open it in VS Code and no other configuration should be necessary. You can configure additional settings for language services to help parsing, create `tasks.json` for build tasks and a `launch.json` to configure debugging.

If you have specific questions about features please let us know. Hope this helps.

**Comment by polomora** [comment]
Many thanks pieandcakes for the clarification.

**Comment by pieandcakes** [comment]
@polomora If you need additional help, please reopen this issue.
