### ISSUE TITLE
[CYGWIN] Error when debug langage C by gdb. Errror: The program has exited

### ISSUE THREAD

**Issue by giacat-tran0198** [microsoft/vscode-cpptools#1633]
hello everyone,
I have just installe VSC and i try to use cygwin and suyu but it can't debug. It show:
Suyu:
Breakpoint 1, 0x000000000040156d in main ()
[Inferior 1 (process 3572) exited normally]
The program has exited with code 0 (0x00000000).
and
cygwin:
ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". Error creating process /cygdrive/d/C C++/a.exe, (error 193).
The program has exited with code 42 (0x0000002a).
what should i do?﻿ Thank you very much
My test is very easy:

int main()
{
	int a, b, sum;
    scanf("%d%d",&a, &b);
    sum = a+b;
    printf("%d + %d = %d",a, b, sum);
	return 0;
}

**Comment by pieandcakes** [comment]
@ilove3q add `"logging": { "engineLogging": true} ` to your `launch.json` and see what the response for `-exec-run` comes back as.

**Comment by pieandcakes** [comment]
Also what version of Cygwin are you using?

**Comment by giacat-tran0198** [comment]
I use the last version. Thanks for your repond

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
