### ISSUE TITLE
Recent changes greys out the code in C file, when they are under a macro and the macro is defined in a header file /.h file

### ISSUE THREAD

**Issue by tsalinger** [microsoft/vscode-cpptools#1636]
--This issue has been moved from [Microsoft/vscode](https://github.com/Microsoft/vscode/issues/44210)--
Author is @pdp166.
### Issue Type
Bug

### Description

1.  create test.h with below code:
     #define MACRO11
2.  create test.c with below code:
     if defined(MACRO11)
     #include "test.h"
      
      int main()
      {
          //do something
      }
      #endif

3.   Observation:  Code in test.c is greyed out
      Expectation:   Code should not be greyed out

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|19.84GB (11.75GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
chmod|dle|1.0.0
status-bar-tasks|Gua|0.3.0
jlang-clang|l3d|0.0.8
cpptools|ms-|0.15.0
console|vil|0.0.6

</details>
Reproduces only with extensions

**Comment by bobbrow** [comment]
Yes, we gray out the inactive code blocks so you can see what code would be compiled.  If you move `#include "test.h"` above the `#if defined(MACRO11)`, the region will be colored again.  What you have described does not appear to be a bug.

We are also going to expose a setting in the next release that lets you turn off the inactive region colorization.  You can follow #1574.
