### ISSUE TITLE
"Discovering files" icon not responsive to theme

### ISSUE THREAD

**Issue by james-b-yu** [microsoft/vscode-cpptools#1638]
After enjoying the extension for several months now, I have noticed that the "Discovering files" icon in the right-hand side of the status bar does not respond to the theme. This makes it virtually useless in light themes when it becomes virtually invisible.
![image](https://user-images.githubusercontent.com/31538456/36948389-19dde8bc-1fd2-11e8-8337-2917ea205bd1.png)
The icon is indeed there as it is hoverable -- the tooltip is still displayed on mouse-over.
![image](https://user-images.githubusercontent.com/31538456/36948404-3df04d4e-1fd2-11e8-8183-606921a43ba6.png)

The icon is of course fully visible in a dark theme:
![image](https://user-images.githubusercontent.com/31538456/36948411-5630cad2-1fd2-11e8-9986-10f852080f67.png)

This looks very unprofessional but the fix shouldn't be too difficult as VSCode is already aware of which themes are dark and which are light:
![image](https://user-images.githubusercontent.com/31538456/36948424-88dbe7f0-1fd2-11e8-8900-cd04451b0b61.png)

**As an alternative, an actual progress bar or text display which shows the progress and extent of files indexed/to be indexed could be implemented.**

**Comment by bobbrow** [comment]
I didn't realize we were setting a color for this icon.  In any case it looks like VSCode has opened up the statusbar item API to allow for us to link these icons to the [theme colors](https://code.visualstudio.com/docs/getstarted/theme-color-reference).  Should be an easy fix.  Thanks for the report.

**Comment by sean-mcmanus** [comment]
Yeah, we had discussions about this previously -- it was decided to hardcode the colors to the red flame and the white database icon, but I didn't realize a theme had a white status bar. We should probably change this to statusBar.foreground (see https://code.visualstudio.com/docs/getstarted/theme-color-reference ). Not sure if there's any themes with a red status bar we need to handle.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.16.1.
