### ISSUE TITLE
Can't easily see or specify `clang` executable (or C++ version) used for Intellisense

### ISSUE THREAD

**Issue by munael** [microsoft/vscode-cpptools#1639]
I'm suspecting that the intellisense engine doesn't actually make use of any external executable for parsing or linting, but found no literature to confirm this.

If that is not the case, how do we change the command line arguments passed to the executable (for example to tell it to force a specific C++ std)?

**Comment by bobbrow** [comment]
In the March update you will be able to specify your stdver in c_cpp_properties.json.  For now we auto-select c++17 (which is not fully implemented yet, but has many of the features available now).

**Comment by sean-mcmanus** [comment]
Please try out https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders and let us know if there are any issues we should fix before our final release next week.

We improved our ability to guess the clang compiler on Linux OS's if it exists. The compilerPath should show the version we guess, so let us know if you think our guess can be improved or if there's any problems with changing the compilerPath or cppStandard version if you need to do that.
