### ISSUE TITLE
Debug: Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by danie6** [microsoft/vscode-cpptools#1642]
VS Code version:1.19.1
C/C++ extension version:0.14.6
VS version:Microsoft Visual Studio Professional 2017 (15.1)
When I compile MIEngine with vs2017,and copy the following files to  **.vscode\extensions\ms-vscode.cpptools-0.14.6\debugAdapters\bin** folder:
*Microsoft.MICore.dll
*Microsoft.MICore.XmlSerializers.dll
*Microsoft.MIDebugEngine.dll
My reference document:https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/How%20To%20Debug%20MIEngine.md
But debugging a Linux program, an error: Debug adapter process has terminated unexpectedly. What do I need to do to replace MIEngine's library?

**Comment by pieandcakes** [comment]
@danie6 Did you make changes that you need to build MIEngine? What version of Linux are you running this on to debug your Linux program?

**Comment by danie6** [comment]
@pieandcakes Yes,I tried to use my compiled MIEngine library, but it has not been successful.I did not make any changes, just compiled with vs2017.My linux environment is suse 11 sp3,Before replacing MIEngine, the program can be debugged.So I do not know what it needs to rely on? Thanks for your reply.

**Comment by pieandcakes** [comment]
@danie6 I found the problem. there is a bug in the configurations in MIEngine. I'm getting a fix now.

**Comment by pieandcakes** [comment]
I have a PR out for it: https://github.com/Microsoft/MIEngine/pull/696 Once this is in, please rebase on master and rebuild `Desktop.Debug` or `Desktop.Release` and copy the same three files and you should be unblocked.

**Comment by pieandcakes** [comment]
@danie6 This is now checked into MIEngine's `master` branch. If you sync and rebase your changes, it should work. Make sure you are building `Desktop.Release` or `Desktop.Debug` configurations.

Thanks for reporting the issue.

**Comment by danie6** [comment]
@pieandcakes yes，it works now.thank you very much！
