### ISSUE TITLE
The terminal process terminated with exit code: 2

### ISSUE THREAD

**Issue by joe3524** [microsoft/vscode-cpptools#1645]
I got this error message while building a C file using VSCode and gcc, not g++.

```
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `gcc /Users/joe/Documents/(programming)/[ C]/VSCode/example.c -o example  && ./example '
The terminal process terminated with exit code: 2
```

 This was when I tested a simple .c file with VSCode.

```
#include <stdio.h>

int main(int argc, char * argv[]) {
    printf("Hello World!");

    return 0;
}
```

 It's strange that when I build a cpp file with g++, it works. But it doesn't when I specifies 'gcc' in tasks.json file. 

Here is my tasks.json:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "compile and run C",
            "type": "shell",
            "command": "gcc ${file} -o ${fileBasenameNoExtension} && ./${fileBasenameNoExtension}",
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

I'm running macOS 10.13.3, VSCode 1.20.1.

**Comment by WardenGnaw** [comment]
Tasks.json is directly supported by VsCode. I have opened an issue for you at https://github.com/Microsoft/vscode/issues/45239.

A potential fix is to put quotes around the ${file}, the error is due to an in-escaped parenthesis.

**Comment by joe3524** [comment]
Although I left my response on [Microsoft/vscode#45239](https://github.com/Microsoft/vscode/issues/45239), I'd like to say Thank you again here.
