### ISSUE TITLE
Error pop up when trying to go to definition on OS X

### ISSUE THREAD

**Issue by leira** [microsoft/vscode-cpptools#165]
I created c_cpp_properties.json file under .vscode. When I click "Go to Definition", I always got an error pop up like this:

`Error Unable to open '': Invalid file resource (file://%2Fusers%2Fleira%2Fsource...%2Fregistry.h).
`

I replaced some of the path with '...'.

It actually showed the correct path, seems like the indexing worked well, but for some reason it didn't jump to the file. Did I miss some setting?

**Comment by leira** [comment]
Forgot to mention, I'm running vscode Version 1.5.0-insider (1.5.0-insider) c4f365235906cd689e55376e44cc106003ac06b3.

**Comment by jgoshi** [comment]
This is fixed and will appear with the next cpptools release (version 0.9.0).
