### ISSUE TITLE
It can't hit breakpoint in vscode graphic interface when (gdb) launching

### ISSUE THREAD

**Issue by zhangmn799** [microsoft/vscode-cpptools#1656]
**Environment data**
VS Code version:1.21.0
C++ Extension version: 0.16.0-insiders
Debugger: cygwin64
OS: Win10 RS2
Gdb Version: Cygwin 7.11.1-2

**Steps to reproduce**
1.Create a folder named test, create a file named a.cpp in test as following:
![main](https://user-images.githubusercontent.com/26423555/37192565-2e8aa0e8-23a1-11e8-8322-f2a0f1e3198d.PNG)
2.Compiled project with command "g++ -g -o a.exe a.cpp" with cygwin64
3.Open test folder with vscode, configure launch.json as following:
![launch](https://user-images.githubusercontent.com/26423555/37192591-5701af26-23a1-11e8-8457-7c895ac92901.PNG)
3.Set a bp in line 8 of a.cpp.
4.F5
5.Continue(F5)

**Expected behavior**
It will hit bp in line 8.

**Actual behavior**
It can't hit bp in line 8. And debug console window show correctly.
![continue](https://user-images.githubusercontent.com/26423555/37192631-9171d0aa-23a1-11e8-972c-d2613c71c8bd.PNG)
![debugconsole](https://user-images.githubusercontent.com/26423555/37192635-94165204-23a1-11e8-9ed6-276f4a7fdf8f.PNG)

**Comment by bobbrow** [comment]
Thanks for the bug report.  There seems to be another issue with gdb debugging as well #1655.  May be related.

**Comment by WardenGnaw** [comment]
Breakpoints are hit, however the glyph is missing. 

This is due to https://github.com/Microsoft/vscode/issues/45311

**Comment by sean-mcmanus** [comment]
Oh, this is the yellow arrow missing (a VS Code issue I've seen in Insiders) -- it's a different issue from the attach bug.
