### ISSUE TITLE
[Feature Request] SSH Build on Linux

### ISSUE THREAD

**Issue by hdost** [microsoft/vscode-cpptools#1658]
Provide a mechanism to build code on Linux VM/remote Linux machine. From local machine
Similar to how: https://blogs.msdn.microsoft.com/vcblog/2017/02/08/targeting-windows-subsystem-for-linux-from-visual-studio/ works.

**Comment by bobbrow** [comment]
We recommend using the [VSCode Remote SSH extension](https://code.visualstudio.com/docs/remote/ssh) for this now.
