### ISSUE TITLE
Cannot use ConfigurationEdit command

### ISSUE THREAD

**Issue by stevenxiao** [microsoft/vscode-cpptools#166]
while i am typing ConfigurationEdit, it shows me the error "command 'C_Cpp.ConfigurationEdit' not found".
 OS: Debian x86_64
 VS Code Version: 1.4

Is there anything that i missed after install the cpptools?

**Comment by sean-mcmanus** [comment]
Are you still reproing this with the latest bits? We need more repro details.

**Comment by shizhx** [comment]
@sean-mcmanus I got same error just now.
both Ubuntu 16.04 x64 and Windows 7 x64.
VSCode 1.5.2

**Comment by shizhx** [comment]
@sean-mcmanus @stevenxiao 
I was conscious that I had made a mistake:
**MUST** open a **folder** not a file.

**Comment by sean-mcmanus** [comment]
Thanks for the feedback. A future release will give an informational message about needing to open a folder to work with configuration files, and the switch headers command will be made to work.
