### ISSUE TITLE
C++ Debugging broken (lldb error)

### ISSUE THREAD

**Issue by elrasguno** [microsoft/vscode-cpptools#1661]
Issue Type: <b>Bug</b>

Halp! I got the latest version automatically and got this error trying to debug C++: 

```
Starting: "/Users/dan/.vscode/extensions/ms-vscode.cpptools-0.15.0/debugAdapters/lldb/bin/lldb-mi" --interpreter=mi
dyld: Library not loaded: @rpath/liblldb.3.8.0.dylib
  Referenced from: /Users/dan/.vscode/extensions/ms-vscode.cpptools-0.15.0/debugAdapters/lldb/bin/lldb-mi
  Reason: no suitable image found.  Did find:
	/Users/dan/.vscode/extensions/ms-vscode.cpptools-0.15.0/debugAdapters/lldb/bin/../lib/liblldb.3.8.0.dylib: truncated mach-o error: segment __TEXT extends to 44466176 which is past end of file 31375360
"/Users/dan/.vscode/extensions/ms-vscode.cpptools-0.15.0/debugAdapters/lldb/bin/lldb-mi" exited with code 134 (0x86).
```

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_21005319|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
vscode-docker|Pet|0.0.25
unity-debug|Uni|1.3.0
html-css-class-completion|Zig|1.17.1
Doxygen|bbe|1.0.0
doxdocgen|csc|0.3.0
vscode-eslint|dba|1.4.7
vscode-npm-script|eg2|0.3.3
live-html-previewer|hdg|0.3.0
vscode-ue4explore|map|0.2.1
prettify-json|moh|0.0.3
azure-account|ms-|0.3.1
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
mono-debug|ms-|0.15.8
perforce|sle|3.1.0
vim|vsc|0.11.1

</details>
Reproduces only with extensions

**Comment by pieandcakes** [comment]
@elrasguno sounds like an issue where the entire file `liblldb.3.8.0.dylib` wasn't extracted. Can you reinstall the extension? That should force a redownload and extraction.

**Comment by elrasguno** [comment]
Hello! Thanks for the quick response. I did try uninstalling, reloading, and reinstalling the C++ extension, but it was still broken. As it turns out, uninstalling from VS Code did not delete the `.vscode/extensions/ms-vscode.cpptools-0.15.0` directory on my machine. 

After manually deleting the `~/.vscode/extensions/ms-vscode.cpptools-0.15.0` directory, then installing from VS Code, I'm back in business! 

Feel free to close this out, but maybe a new issue to investigate and solve the failed uninstall would be helpful?

**Comment by pieandcakes** [comment]
@elrasguno I think its a problem with the unzipping library and how it unzips the lldb package that we download. Without hardcoded checksums I don't know if we can get around this. 

The uninstall issue is strange and should only be stuck if there is a file open.

I'm glad you are back in business. I will close this issue.

**Comment by Mossop** [comment]
I'm seeing this exact error too :(

**Comment by pieandcakes** [comment]
@Mossop can you try and reinstall the extension? I think VS Code is looking to see if they can add checksums to  verify that the extension has installed correctly although last I saw they hadn't decided on anything yet.

**Comment by Mossop** [comment]
Yeah, uninstalling then manually deleting the folder mentioned above then installing again solved the problem. I hope there can be a fix to solve this, or at least make it easier to resolve though.
