### ISSUE TITLE
New global/local variable completion not respecting variable name hiding

### ISSUE THREAD

**Issue by james-b-yu** [microsoft/vscode-cpptools#1663]
***The new global/local variable completion is awesome!***
...but not when lots of name hiding happens:

Normally, it works normally:
![image](https://user-images.githubusercontent.com/31538456/37244665-7bc011ca-2484-11e8-89ef-2d8bc240bda2.png)

In this next code, there is a simple case of name hiding. It still works well, so one would assume name hiding isn't an issue:
![image](https://user-images.githubusercontent.com/31538456/37244669-8a5ee22e-2484-11e8-95aa-ed20117cf477.png)

However, when adding a further scope, the autocomplete becomes confused and suggests the wrong variable:
![image](https://user-images.githubusercontent.com/31538456/37244699-d950df5e-2484-11e8-8135-70d4423c1e95.png)
As one can see, autocomplete is suggesting ```std::string main::variable``` instead of ```int variable``` within the inner scope. This is a minor problem, as the actual IntelliSense doesn't get confused -- only the global/local autocompletion. Here, the linter correctly states that ```int variable``` is not a structure:
![image](https://user-images.githubusercontent.com/31538456/37244738-4b2f0010-2485-11e8-84c7-063004f4c868.png)

However, a more prominent problem is, that the scope resolution operator (```::```) does not activate global/local variable autocompletion of a variable in the global scope:
![image](https://user-images.githubusercontent.com/31538456/37244839-a791f3ac-2486-11e8-97a7-303f53fdb84c.png)
Here, ```int variable``` declared on line ```3``` should be suggested, but is not.

I am using the ```0.16.0-insiders``` version of the extension along with VSCode ```1.21.0```.

**Comment by sean-mcmanus** [comment]
In regards to the name hiding issue, it looks like VS 2017 has the same, so it might not be easy to fix (I'll file a bug with them).

I think we can get the global :: operator to work (we just overlooked it), but it will only list global variables, and not local variables.

**Comment by bobbrow** [comment]
I have a fix for the global scope operator issue.  I can reproduce the hiding issue as well and am working on a fix for it.

**Comment by bobbrow** [comment]
It appears that I don't have a way to work around the variable shadowing issue yet.  I had thought that I might be able to since there was a +1 overload in the tooltip, but it appears that the inner-most shadowed variable is not being returned to us at all by the IntelliSense engine.  It only gives us type information for the global `int variable` and the `std::string variable` in `main()`.

**Comment by sean-mcmanus** [comment]
This issue got "Won't Fixed" by VS -- https://developercommunity.visualstudio.com/content/problem/212334/c-intellisense-autocomplete-shows-the-wrong-type-f.html . So that means more people need to complain to them :)

**Comment by bobbrow** [comment]
The linked Visual Studio ticket was closed without a fix which means unfortunately we won't be getting a fix for this in VS Code either.
