### ISSUE TITLE
"cannot open source file "c++ header file""

### ISSUE THREAD

**Issue by AndrewDi** [microsoft/vscode-cpptools#1665]
* Operating System : Windows 10 1706
    * VS Code version : 1.21.0
    * C/C++ extension version : 0.15.0
    * MinGW on Windows
    * Gcc 6.3

I configuration vscode with cpptools to write CPP, but hit an issue:
Simple hello world code:
![image](https://user-images.githubusercontent.com/7589147/37248481-4c5bbe18-250e-11e8-8370-a27e608debc5.png)

On problem view:
![image](https://user-images.githubusercontent.com/7589147/37248482-6bf6667e-250e-11e8-98fb-190354dd389a.png)

c_cpp_properties.json:
![image](https://user-images.githubusercontent.com/7589147/37248621-0b6725ba-2512-11e8-9008-632bf6d297c6.png)

gcc -v -E -x c++ -:
`PS F:\Developer\cpp\sample_cpp> gcc -v -E -x c++ -
Using built-in specs.
COLLECT_GCC=G:\MinGW\bin\gcc.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
COLLECT_GCC_OPTIONS='-v' '-E' '-mtune=generic' '-march=i586'
 g:/mingw/bin/../libexec/gcc/mingw32/6.3.0/cc1plus.exe -E -quiet -v -iprefix g:\mingw\bin\../lib/gcc/mingw32/6.3.0/ - -mtune=generic -march=i586
ignoring nonexistent directory "g:\mingw\bin\../lib/gcc/mingw32/6.3.0/../../../../mingw32/include"
ignoring duplicate directory "g:/mingw/lib/gcc/../../lib/gcc/mingw32/6.3.0/include/c++"
ignoring duplicate directory "g:/mingw/lib/gcc/../../lib/gcc/mingw32/6.3.0/include/c++/mingw32"
ignoring duplicate directory "g:/mingw/lib/gcc/../../lib/gcc/mingw32/6.3.0/include/c++/backward"
ignoring duplicate directory "g:/mingw/lib/gcc/../../lib/gcc/mingw32/6.3.0/include"
ignoring nonexistent directory "/mingw/include"
ignoring duplicate directory "g:/mingw/lib/gcc/../../include"
ignoring duplicate directory "g:/mingw/lib/gcc/../../lib/gcc/mingw32/6.3.0/include-fixed"
ignoring nonexistent directory "g:/mingw/lib/gcc/../../lib/gcc/mingw32/6.3.0/../../../../mingw32/include"
ignoring nonexistent directory "/mingw/include"
#include "..." search starts here:
#include <...> search starts here:
 g:\mingw\bin\../lib/gcc/mingw32/6.3.0/include/c++
 g:\mingw\bin\../lib/gcc/mingw32/6.3.0/include/c++/mingw32
 g:\mingw\bin\../lib/gcc/mingw32/6.3.0/include/c++/backward
 g:\mingw\bin\../lib/gcc/mingw32/6.3.0/include
 g:\mingw\bin\../lib/gcc/mingw32/6.3.0/../../../../include
 g:\mingw\bin\../lib/gcc/mingw32/6.3.0/include-fixed
End of search list.`

Actually gcc code can compile and run correct,and Peek Declaration can open correct file.
But whenever I #include c++ header,cpptools will report "cannot find sources 'header file'".
![image](https://user-images.githubusercontent.com/7589147/37248616-f1f9184a-2511-11e8-91b5-2229f02d4af1.png)

BTW:If I include c header file,everything work perfectly.

**Comment by sean-mcmanus** [comment]
Can you try using our 0.16.0-insiders ( https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders ) and setting the compilerPath to the "G:\MinGW\bin\gcc.exe" (new property in c_cpp_properties.json). This is expected to query gcc for the correct system includes and also the defines, the lack of which could be causing the headers to not be found.

**Comment by AndrewDi** [comment]
After upgrade cpptools to 0.16.0-insiders,problem still exists.
![image](https://user-images.githubusercontent.com/7589147/37250844-37c278de-2540-11e8-8a8f-1ffc2afb9a97.png)

**Comment by AndrewDi** [comment]
Alter turn log level to information,plugin give some logs,but seems didn't helpful:

IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Code browsing service initialized
  Folder: F:/DEVELOPER/CPP/SAMPLE_CPP/ will be indexed
  Folder: G:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/ will be indexed
  Folder: G:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/ will be indexed
  Folder: G:/MINGW/INCLUDE/* will be indexed
Discovering files...
  Processing folder (recursive): F:/DEVELOPER/CPP/SAMPLE_CPP/
  Processing folder (recursive): G:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/
  Processing folder (recursive): G:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/
  Processing folder (non-recursive): G:/MINGW/INCLUDE
  Discovering files: 1104 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Checking for syntax errors: file:///f%3A/Developer/cpp/sample_cpp/test.cpp

**Comment by sean-mcmanus** [comment]
Why was this issue closed? Did you figure out how to resolve the issue or do we still have some bug processing minGW 6.3 headers? We have a MinGW faq at https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md .
