### ISSUE TITLE
why disable code highlighting？

### ISSUE THREAD

**Issue by kcloze** [microsoft/vscode-cpptools#1669]
I want to show all code, are there some configs to disable this?
SW_COROUTINE is not defined.
![image](https://user-images.githubusercontent.com/1489176/37293995-d0f07dac-264f-11e8-9afb-ca92075a10f6.png)

**Comment by sean-mcmanus** [comment]
If you want intelliSense to work with the code that is grayed out, you'll need to add SW_COROUTINE to your "defines" setting in c_cpp_properties.json, but if you just want the gray to go away, you can use setting `    "C_Cpp.dimInactiveRegions": false` with our insiders build: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders .
