### ISSUE TITLE
Colorization of large cpp/h files fails after so many lines

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cpptools#167]
_From @rchiodo on August 24, 2016 16:4_
- VSCode Version: 1.4.0
- OS Version: Windows 10 RS1

Steps to Reproduce:
1.  Open file C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h
2.  Colorization stops at about line 612 for me

![image](https://cloud.githubusercontent.com/assets/19672699/17938187/c22b4a92-69d9-11e6-927f-f5b030fc71c7.png)

_Copied from original issue: Microsoft/vscode#10901_

**Comment by rchiodo** [comment]
THis is a vscode issue. Not sure how to reopen issues.
