### ISSUE TITLE
Enable full offline installs

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#1670]
I'm working in an environment where there is not always internet, potentially never internet on systems I would like to use the vscode cpp extension. Is there a way it would be possible to separately download the native dependencies (I don't mind having to download the ones for all architectures) and have a way for the extension to find them to allow a fully offline install with full functionality?

**Comment by sean-mcmanus** [comment]
We have per-OS offline vsix's available at https://github.com/Microsoft/vscode-cpptools/releases .
