### ISSUE TITLE
Some problem with configuration of include headers for standard libraries

### ISSUE THREAD

**Issue by nathanaelg** [microsoft/vscode-cpptools#1672]
I'm using GNU Arm Embedded toolchain https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads and have configured my include path in c_cpp_properties.json to be

```
"C:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/arm-none-eabi/include/c++/7.2.1",
"C:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/arm-none-eabi/include/c++/7.2.1/arm-none-eabi",
"C:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/arm-none-eabi/include/c++/7.2.1/backward",
"C:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/lib/gcc/arm-none-eabi/7.2.1/include",
"C:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/lib/gcc/arm-none-eabi/7.2.1/include-fixed",
"C:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/arm-none-eabi/include"
```

I'm not entirely sure this is the right order but I tried `C:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/bin/arm-none-eabi-gcc.exe -Wp,-v -x c++ - -fsyntax-only` and got
```
#include "..." search starts here:
#include <...> search starts here:
 c:\program files (x86)\gnu tools arm embedded\7 2017-q4-major\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include/c++/7.2.1
 c:\program files (x86)\gnu tools arm embedded\7 2017-q4-major\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include/c++/7.2.1/arm-none-eabi
 c:\program files (x86)\gnu tools arm embedded\7 2017-q4-major\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include/c++/7.2.1/backward
 c:\program files (x86)\gnu tools arm embedded\7 2017-q4-major\bin\../lib/gcc/arm-none-eabi/7.2.1/include
 c:\program files (x86)\gnu tools arm embedded\7 2017-q4-major\bin\../lib/gcc/arm-none-eabi/7.2.1/include-fixed
 c:\program files (x86)\gnu tools arm embedded\7 2017-q4-major\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include
```

If I make `foo.cpp`
```
#include <cstdlib>
#include <ctime>

int main()
{
    srand(time(NULL));
}
```

I am warned that srand has too many arguments in function call, and time has too many arguments in function call.

I also tried the includes in the opposite order but then I get an error that it cannot open source file "stdlib.h" (dependency of "cstdlib")

I'm using Windows 10, VSCode 1.21.0, and am trying the 0.16.0-insiders (though I had the same issue on the mainline version I was using before that).
```
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by sean-mcmanus** [comment]
Is your intelliSenseMode clang-x64? Is your compilerPath property set to "C:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/bin/arm-none-eabi-gcc.exe"?

**Comment by nathanaelg** [comment]
Magical, that fixed it. I had tried setting intelliSenseMode to clang-x64 previously but obviously something in the combination of that and the new define-detection-from-compiler worked. I can still can't "Go to Definition" of those stdlib functions but at least the warnings are gone.

**Comment by sean-mcmanus** [comment]
Go to Definition is used the "browse.path" setting, but that is recursive so it should be easier to get working, unless the file with the definition is hitting a parser failure or has macros whose definition disrupts parsing that need to be added to a cpp.hint file.

**Comment by nathanaelg** [comment]
It's still struggling with stdint.h actually - can't find types like uint32_t, which it marks as \<error-type\>

**Comment by sean-mcmanus** [comment]
I'm also seeing a problem with uint32_t not getting picked up. There's a blog with some info at http://shadetail.com/blog/using-visual-studio-code-for-arm-development-defines/ , but I think 0.16.0-insiders is supposed to make that unnecessary unless a non-default compiler flag is required. Investigating...

**Comment by sean-mcmanus** [comment]
Oh, duh, I didn't #include <stdint.h>. I don't repro a problem after that. Does hovering over `__UINT32_TYPE__` show "unsigined int" or "long unsigned int"? If you could follow the include paths that are being used to check for incorrect defines, that might solve it.

I tested the arm-none-eabi-gcc compilePath and it's working on Linux with uint32_t, not sure if there's a problem on Windows yet.

**Comment by nathanaelg** [comment]
No, I get "identifier "__UINT32_TYPE__" is undefined". It doesn't seem like the compiler path configuration is working - I tried following that article and saving all the defines from gcc into c_cpp_properties.json and the warning about uint32_t went away, although that made size_t break. It's like juggling cats!

**Comment by nathanaelg** [comment]
Actually, I just tried removing all include paths apart from the stdlib ones, and everything worked... so there must be something in those directories which is interfering - it looks like including this directory (although the version of the code I have is a bit different) https://github.com/ARM-software/CMSIS/tree/master/CMSIS/Include causes the problem.

**Comment by nathanaelg** [comment]
I'm still not convinced that `"compilerPath": "C:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/bin/arm-none-eabi-gcc.exe"` is working - if I define 
```
"__GNUC__",
"__INT_MAX__=0x7fffffff",
"__SHRT_MAX__=0x7fff",
"__SCHAR_MAX__=0x7f",
```
(as they are defined in gcc defaults) then it all seems to work.

**Comment by bobbrow** [comment]
If you set `"C_Cpp.loggingLevel": "6"` the extension will spew the compiler defaults to the output window when you open a new c/cpp file.  This should help us see what is going on. (just remember to switch the logging level back to one of the enum values when you're done to avoid slowing down the extension too much)

**Comment by sean-mcmanus** [comment]
Yeah, I'm able to repro the problem -- I'm getting "Failed to query default include paths for F:/Program Files (x86)/GNU Tools ARM Embedded/7 2017-q4-major/bin/arm-none-eabi-gcc.exe". It looks like /dev/null doesn't work on Windows (repros with clang too) -- using "nul" fixes it. Sorry, for not testing this scenario better. It should be fixed in our next release (not sure if we're updating the insiders or just doing a normal release...it feels like we should stay in insiders longer).

**Comment by nathanaelg** [comment]
I think this is fixed now, I'm using the information from compile_commands.json instead of specifying include directories and defines.
