### ISSUE TITLE
Add a setting for adding compiler args to modifying the default defines

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1673]
The compilerPath setting also needs to a generic compilerArgs setting for adding flags that modify the compiler defines used.

See https://github.com/Microsoft/vscode-cpptools/issues/1608 .

**Comment by FreddieChopin** [comment]
This is important for cross-compilers, where you get different compiler defines depending on the machine flags used:

```
$ arm-none-eabi-gcc -dM -E -mcpu=cortex-m0 -mthumb - < /dev/null | grep ARCH
#define __ARM_ARCH_PROFILE 77
#define __ARM_ARCH_ISA_THUMB 1
#define __ARM_ARCH 6
#define __ARM_ARCH_6M__ 1
$ arm-none-eabi-gcc -dM -E -mcpu=cortex-m3 -mthumb - < /dev/null | grep ARCH
#define __ARM_ARCH_7M__ 1
#define __ARM_ARCH_PROFILE 77
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH 7
#define __ARM_ARCH_EXT_IDIV__ 1
$ arm-none-eabi-gcc -dM -E -mcpu=cortex-m4 -mthumb - < /dev/null | grep ARCH
#define __ARM_ARCH_PROFILE 77
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH 7
#define __ARM_ARCH_7EM__ 1
#define __ARM_ARCH_EXT_IDIV__ 1
```

```
$ arm-none-eabi-gcc -dM -E -mcpu=cortex-m4 -mthumb - < /dev/null | grep FP__
#define __SOFTFP__ 1
#define __VFP_FP__ 1
$ arm-none-eabi-gcc -dM -E -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 - < /dev/null | grep FP__
#define __VFP_FP__ 1
```

For me it would be enough if `compilerPath` property would allow to have a path _with_ the flags which are important. Regular user would just have `"compilerPath": "/usr/bin/gcc"` there, while I could set this to `"compilerPath": "/home/freddie/arm-none-eabi-gcc-7.3.0-180127/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16"`. Another option is a separate property just for the flags, but I think `compilerPath` would be enough here (the name is not very good in that case, but well...).

**Comment by sean-mcmanus** [comment]
@FreddieChopin We added the ability to add compiler args to the compilerPath with https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders2 . Let us know if there are any problems we should fix before our official release next week.

**Comment by FreddieChopin** [comment]
How do I use it properly? If I just do:

"compilerPath": "/home/freddie/arm-none-eabi-gcc-7.3.0-180127/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16",

Then in the output tab I see:
```

About to fork
fork complete (parent process, child pid = 21016)
result=arm-none-eabi-g++: error: unrecognized argument in option '-mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16'
arm-none-eabi-g++: note: valid arguments to '-mcpu=' are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a17 cortex-a17.cortex-a7 cortex-a32 cortex-a35 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a72 cortex-a72.cortex-a53 cortex-a73 cortex-a73.cortex-a35 cortex-a73.cortex-a53 cortex-a8 cortex-a9 cortex-m0 cortex-m0.small-multiply cortex-m0plus cortex-m0plus.small-multiply cortex-m1 cortex-m1.small-multiply cortex-m23 cortex-m3...
Waiting for child process to complete
terminating child process: 21016
```

It seems that either I'm using it wrong, or it supports just a single flag, so in fact GCC sees my options as:

`"-mcpu"="cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16"`

I've also tried to quote that myself - `"compilerPath": "/home/freddie/arm-none-eabi-gcc-7.3.0-180127/bin/arm-none-eabi-gcc \"-mcpu=cortex-m4\" \"-mthumb\" \"-mfloat-abi=hard\" \"-mfpu=fpv4-sp-d16\"",`, but then it complains in a different way:

```
About to fork
fork complete (parent process, child pid = 24465)
result=clang-6.0: error: no such file or directory: '"-mcpu=cortex-m4" "-mthumb" "-mfloat-abi=hard" "-mfpu=fpv4-sp-d16"'

Waiting for child process to complete
terminating child process: 24465
```

**Comment by sean-mcmanus** [comment]
Sorry about that -- it's a bug (your first example should work). It should be fixed for our final 0.16.0 release.

**Comment by sean-mcmanus** [comment]
We believe compilerPath multiple args should finally work with 0.16.1 (and we fixed a random deadlock issue that could lead to stuck "Loading...").

**Comment by FreddieChopin** [comment]
Thanks - new version seems to work correctly with my set of flags (;
