### ISSUE TITLE
Allow Modifying Variable with Mouse Hover Preview while Debugging.

### ISSUE THREAD

**Issue by skl131313** [microsoft/vscode-cpptools#168]
Currently when debugging, you can hover over a variable to see its value. It would be more convenient if the value could be modified from this preview window. Rather than having to search through the list of variables.

**Comment by pieandcakes** [comment]
@sprinkle131313 You should be able to add it to `watch` and modify it instead of searching through `variables`

**Comment by Trass3r** [comment]
This refers to the popup in the editor though, just like VS [DataTips](https://docs.microsoft.com/en-us/visualstudio/debugger/view-data-values-in-data-tips-in-the-code-editor#expand-and-edit-information) which offer even more functionality like adding expressions and [pinning](https://docs.microsoft.com/en-us/visualstudio/debugger/view-data-values-in-data-tips-in-the-code-editor#pin-properties-in-datatips). So I guess this could be the "implement DataTips like in VS" tracking ticket.

**Comment by WardenGnaw** [comment]
Closing this as this would be a feature for the VS Code UI to support since we already have debugger protocol to handle it.

Please open an issue at https://github.com/microsoft/vscode/

**Comment by Trass3r** [comment]
> [pinning](https://docs.microsoft.com/en-us/visualstudio/debugger/view-data-values-in-data-tips-in-the-code-editor#pin-properties-in-datatips).

https://github.com/microsoft/vscode/issues/133587
