### ISSUE TITLE
Configuring Intellisense link is broken

### ISSUE THREAD

**Issue by sushanthr** [microsoft/vscode-cpptools#1682]
I am trying to get started on using VSCode and the C/C++ extension. I installed the extension and am presented the release notes page. I clicked on "Configuring Intellisense" which goes nowhere.

https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started.md

![image](https://user-images.githubusercontent.com/15526596/37357249-2387b6de-26a5-11e8-9369-469c2f07aa5e.png)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. It's already been fixed in https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders . The target is https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started%20with%20IntelliSense%20configuration.md .
