### ISSUE TITLE
Intellisense - CamelCase suggestions

### ISSUE THREAD

**Issue by jeffgabhart** [microsoft/vscode-cpptools#169]
It would be nice to have intellisense show suggestions based on the first and capiatlized letters. For example, typing all lowercase 
`sro`
would match
`setReadOnly
`

**Comment by sean-mcmanus** [comment]
This will work in general if no other bugs/issues occur. It's possible if too many symbols match the "sro" then the result might not be returned. We can investigate fixes for this later (maybe increasing the query limit we have or making it user-customizable).
