### ISSUE TITLE
Docs links broken

### ISSUE THREAD

**Issue by lukaszsamson** [microsoft/vscode-cpptools#1690]
v 0.15.0
After installing the extension release notes page is shown with broken links to [Configuring InteliSense](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started.md)

**Comment by sean-mcmanus** [comment]
Thanks for letting us know. It's been fixed in our Insiders release: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders . The link target is https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started%20with%20IntelliSense%20configuration.md .
