### ISSUE TITLE
Debugger cannot print std::complex properly

### ISSUE THREAD

**Issue by niltok** [microsoft/vscode-cpptools#1691]
### Just like this...

I have added `-enable-pretty-printing` to `setupCommends` but it does not work for `std::complex`.

![Screenshot_20180315_220153.png](https://i.loli.net/2018/03/15/5aaa7ce489c7d.png)

**Comment by WardenGnaw** [comment]
@goldimax We enable pretty printing in GDB. We do not provide additional support for that. If you want, you can investigate the python pretty print files. Otherwise, we support the [natvis format](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/natvis/Natvis.md).
