### ISSUE TITLE
Error C/C++ expansion

### ISSUE THREAD

**Issue by haccoco99999** [microsoft/vscode-cpptools#1692]
Error 
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (5038 KB) .................... Failed. Retrying...(5038 KB) .................. Failed. Retrying...(5038 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (796 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (12072 KB) .................... Failed. Retrying...(12072 KB) ................... Failed. Retrying...(12072 KB) .................. Failed. Retrying...Waiting 8 seconds...(12072 KB) ................... Failed. Retrying...Waiting 16 seconds...(12072 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: invalid central directory file header signature: 0x2abb5ec6

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.

**Comment by sean-mcmanus** [comment]
Yeah, did you follow the instructions and install the offline vsix? Some people experience various failures with our online installer, which is why we make the offline, per-OS version available. We've had thoughts about automatically downloading and installing the offline .vsix when this occurs.

**Comment by michelleangela** [comment]
Closing this issue as the last activity on it is more than a year ago.

If you update to the latest version of the C/C++ extension and your issue persists, please re-open the issue and reply with additional information that can help us investigate your issue.
