### ISSUE TITLE
IntelliSense include paths resolution behavior.

### ISSUE THREAD

**Issue by vatosarmat** [microsoft/vscode-cpptools#1697]
Hello. I have trivial C-program with 'include' directives for <stdio.h> and <sys/types.h>. When I try go to definition, IntelliSense shows me 3 locations for stdio.h and 11 for types.h. But those locations are not set in my includePath and browse.path. And I include <sys/types.h>, not just types.h. Does IntelliSense ignore directories in 'include' directive path? Why it searches headers in directories I didn't specify in c_cpp_properties.json?

**Code**
```
#include <stdio.h>
#include <sys/types.h>
int main(int argc, char** argv)
{
    return 0;
}
```
**Go to definition results**
![stdio](https://user-images.githubusercontent.com/35213999/37552891-349e3666-2a09-11e8-91dd-fc86545f9625.png)
![types](https://user-images.githubusercontent.com/35213999/37552892-34d1b54a-2a09-11e8-8840-67a3460a17f8.png)

**c_cpp_properties.json**
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/lib/gcc/x86_64-linux-gnu/7/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/lib/gcc/x86_64-linux-gnu/7/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed",
                    "/usr/include/x86_64-linux-gnu",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```

**Comment by bobbrow** [comment]
The paths provided in your `"browse.path"` setting are searched recursively.  If you want to make any of them non-recursive, add a `/*` at the end.  (e.g. `/usr/include/*`)

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.

If you update to the latest version of the C/C++ extension and your issue persists, please re-open the issue and reply with additional information that can help us investigate your issue.
