### ISSUE TITLE
Debug Console flooded with messages

### ISSUE THREAD

**Issue by zethon** [microsoft/vscode-cpptools#1698]
* OS: OSX 10.12.4
* Visual Studio Code: Version 1.22.0-insider (1.22.0-insider)
* C++ extension ver: Version 0.15.0: February 15, 2018

I have a console program and generally I will run it in Debug Console (ie. `"externalConsole": false,`) however the output is flooded with these messages:

```
Loaded '/System/Library/Frameworks/Security.framework/Versions/A/Security'. Symbols loaded.
Loaded '/usr/lib/libDiagnosticMessagesClient.dylib'. Symbols loaded.
Loaded '/usr/lib/libicucore.A.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcache.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcommonCrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcompiler_rt.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcopyfile.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcorecrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdispatch.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdyld.dylib'. Symbols loaded.
...
```

This goes on for hundreds of lines, which can make finding the actual output of my program difficult to find. 

I realize I could just run in an external console, but Is there any way to suppress this logging?

**Comment by WardenGnaw** [comment]
We have moduleLoad logging enabled as default. You can disable it by adding the following to you launch.json
```
"logging": {
   "moduleLoad": false
}
```

**Comment by Dynamize100** [comment]
Spot on thanks

**Comment by annymosse** [comment]
> We have moduleLoad logging enabled as default. You can disable it by adding the following to you launch.json
> 
> ```
> "logging": {
>    "moduleLoad": false
> }
> ```

it doesn't work and slower than to run it by myself on the terminal 😢
