### ISSUE TITLE
Invalid file resource . c++

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cpptools#170]
_From @leaxoy on August 25, 2016 11:17_
- VSCode Version:1.5.0-insiders
- OS Version:10.12

Steps to Reproduce:
1.  open a c file.
2. press f12 and then meet this error.
   ![vscode-error](http://o8z0dg641.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-08-25%20%E4%B8%8B%E5%8D%887.19.06.png)

_Copied from original issue: Microsoft/vscode#10942_

**Comment by leira** [comment]
Same issue has already been reported as Microsoft/vscppsamples#165, According to @jgoshi, it has been fixed and will be in the next cpptools release (version 0.9.0).

**Comment by jgoshi** [comment]
Yes it should be fixed. If you still see this issue with the upcoming release, please reopen this issue.

**Comment by leira** [comment]
@jgoshi mind if I ask when will it be released?

**Comment by sguillia** [comment]
Hello,

I updated vscode from 1.4.0 to 1.6.0 and now I'm having this issue.

cpptools has released 0.9.2 so I assume this bug has been fixed. I have the latest vscode version so I also assume I have the latest cpptools version (since the `about` section does not show that information).

Now retrograding to 1.4.0. Should I do something ?

**Comment by sean-mcmanus** [comment]
What version does it say for C/C++ in the extensions pane (bottom button on the left)? It should show 0.9.2. Otherwise you need to upgrade it (I don't think it updates extensions when you update VS Code itself). You shouldn't need to downgrade to 1.4.0 of VS Code.

**Comment by sguillia** [comment]
@sean-mcmanus I didn't knew where to look for to update cpptools and it wasn't updated (was below 0.8.1). Now it works fine. Thank you
