### ISSUE TITLE
no instance of overloaded function "swap" matches the argument list -- argument types are: (int, int)

### ISSUE THREAD

**Issue by aigolang** [microsoft/vscode-cpptools#1700]
I got the following error about "swap" method: no instance of overloaded function "swap" matches the argument list -- argument types are: (int, int). 
There ere 2 swap method in this namespace, but I don't understand why only the first one gets the error.
It would be appreciated if any one can help me resolve it!
btw, I get the error after I update the c_cpp_properties.json in VSCode, Win10, MinGW-64 as cmd "gcc -v -E -x c++ -". please refer: https://github.com/Microsoft/vscode-cpptools/issues/757#event-1094666486

what's more, why does the content in <> after #include not show up?

```
#include <iostream> // <iostream
#include <ctime> // <ctime
#include <cassert>  // <cassert
#include <algorithm>  // <algorithm
#include <string>  // <string
#include <utility>  // <utility

using namespace std;

namespace SortTestHelper{
 
   int *generateNearlyOrderedArray(int n, int swapTimes){

        int *arr = new int[n];
        for(int i = 0; i < n; i ++ )
            arr[i] = i;

        srand(time(NULL));
        for(int i = 0; i < swapTimes; i ++){
            int posx = rand()%n;
            int posy = rand()%n;
            swap( arr[posx], arr[posy] ); 
            //no instance of overloaded function "swap" matches the argument list.
        }

        return arr;
    }

    //Selection Sort
    template<typename T>
    void selectionSort( T arr[], int n ){

        for(int i = 0; i < n; i++ ){
            int minIndex = i;
            for (int j=i+1; j<n; j++)
                if(arr[j] < arr[minIndex])
                    minIndex = j;
            swap( arr[i], arr[minIndex] );
            //working good.
        }
    }
}
```

**Comment by bobbrow** [comment]
Can you share your config from c_cpp_properties.json?  I have 4 different MinGW installations on my PC and I am not able to reproduce this problem with any of them.  I suspect it is a configuration issue.

**Comment by sean-mcmanus** [comment]
@lovingjo In regards to `why does the content in <> after #include not show up?`: we haven't implemented completion for #include statements yet. We have nother GitHub issue tracking that https://github.com/Microsoft/vscode-cpptools/issues/802 -- it's in the April milestone currently, but it might get moved back to later.

**Comment by aigolang** [comment]
@bobbrow @sean-mcmanus thank you!! my config from c_cpp_properties.json is following,

       {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}",
                "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include/c++",
                "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include/c++/i686-w64-mingw32",
                "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include/c++/backward",
                "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include",
                "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include-fixed",
                "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/../../../../i686-w64-mingw32/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "__GNUC__=7",
                "__cdecl=__attribute__((__cdecl__))"
            ],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include/c++",
                    "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include/c++/i686-w64-mingw32",
                    "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include/c++/backward",
                    "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include",
                    "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include-fixed",
                    "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/../../../../i686-w64-mingw32/include"
                ],
            "limitSymbolsToIncludedHeaders": true,
            "databaseFilename": ""
            }
        }

I find that it's working good in a win10 PC which has installed VS2017, and the config in "c_cpp_properties.json" is different with above config, but for a PC which doesn't have VS2017, I get the error.

**Comment by sean-mcmanus** [comment]
@lovingjo Oh, that's odd. The existence of VS 2017 should only affects if the paths to the VC appear in the default includePath/browse.path...they aren't used behind the scenes. My guess is that it's due to missing compiler defines (and maybe your machines have slightly different libraries installed?). If you set the compilerPath to your mingw compiler, it might fix the issue, but you'll have to wait till 0.16.0 is released (the insiders version doesn't work on Windows).

**Comment by aigolang** [comment]
@sean-mcmanus I think the issue should be with the config for C++, I have a test on a new win10, install the MinGW-64, VSCode, copy the code in a .cpp file, configure the .json files, and then get the same error.

I find that there is no "swap" red error if I only config the includePath as "${workspaceRoot}", "C:/Program Files (x86)/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/include/c++", at the same time, there are some green warning showing up for #include <...>.

Can you repro the issue on a Win10 without VS2017? 
The following is the config of a Win10 with VS2017, and all good.
        {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/include/*",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/um",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/shared",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/winrt",
                "C:/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/lib/gcc/i686-w64-mingw32/7.2.0/include/c++",
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/include/*",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/um",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/ucrt",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/shared",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/winrt",
                    "C:/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/lib/gcc/i686-w64-mingw32/7.2.0/include/c++",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }

What's more, could you please give me a detail configuration steps after installed MinGW and VSCode, expecially for c_cpp_properties.json like includePath, defines, browser.path? I have tried the document from MSDN, but always get errors or warnings. I refer the URL
"https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md" I still get the same error.

**Comment by fellowseb** [comment]
Had the same issue with a basic MinGW32 setup (no VS2017) and providing the compilerPath option did the trick.

**Comment by aigolang** [comment]
@fellowseb Hi, could you please tell me how do you resolve it?

**Comment by fellowseb** [comment]
@lovingjo Hi. I just followed @sean-mcmanus's advice:
> if you set the compilerPath to your mingw compiler, it might fix the issue, but you'll have to wait till 0.16.0 is released

So I added the following line to my Win32 configuration in the c_cpp_properties.json file:
`"compilerPath": "C:\\MinGW\\bin\\g++.exe"`
I use the insiders version BTW.

**Comment by aigolang** [comment]
@fellowseb Thank you, I add the path as following, but still got the error.
            "name": "Win32",
            "compilerPath": "C:/mingw-w64/i686-7.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/g++.exe",
            "includePath": [ ...

**Comment by aigolang** [comment]
@fellowseb Thank you for your help! It's working!!! It was showing the error after I udpated the c_cpp_properties.json file and saved it. but the error is gone when I restart the VSCode.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
