### ISSUE TITLE
Minor problems with formatting

### ISSUE THREAD

**Issue by tsalinger** [microsoft/vscode-cpptools#1701]
>This issue has been moved from [Microsoft/vscode/](https://github.com/Microsoft/vscode/issues/46107)
Original author is <a href="/medoric">
      <img class="avatar rounded-1" height="44" width="44" alt="@medoric" src="https://avatars1.githubusercontent.com/u/33443169?s=88&amp;v=4">
    </a>@medoric
---

- VSCode Version: 1.20.1
- OS Version: Windows 10 version 1709

VS Code is my primary way of writing C++ programs apart from VS, but the text editing still needs a little improvement.
1. The Alt + Up/Down feature.
I seem to remember that the shortcut could automatically adjust the number of tabs before the lines of code selected to fit wherever they are placed in previous versions (before the icon is changed to blue). But now, the number of tabs will not adjust. Could you please fix that because I use the shortcut frequently and sometimes the problem annoys me.

2. Automatic indentation incorrect with ':'
In class definitions and switch statements, the colon is used. But the indentation is kinda not right. If a line of code ends with ':' (for instance, "private:" or "case xxx:"), the number of indentations of the line of code should be decreased by 1. Take an example:
```cpp
// What it should look like:
switch (foo)
{
case 1:
    // do something
    break;
case 2:
    // ...
    break;
// ....
}

// What it's like in VS Code without manual formatting:
switch (foo)
{
    case 1:
    // do something
    break;
    case 2:
    // ...
    break;
// ....
}
```

That's all. I hope the problems can be solved in future updates. The problems are not huge bugs but solving them make coding all the more convenient. Thanks.

---

>This is a reply from <a href="/medoric">
      <img class="avatar rounded-1" height="44" width="44" alt="@medoric" src="https://avatars1.githubusercontent.com/u/33443169?s=88&amp;v=4">
    </a>@medoric

My problem is similar to [this one](https://github.com/Microsoft/vscode/issues/4039).

---

**Comment by sean-mcmanus** [comment]
@medoric I think this is https://github.com/Microsoft/vscode-cpptools/issues/883 .
