### ISSUE TITLE
(question) why do we need browse and includePath both

### ISSUE THREAD

**Issue by zsynacl** [microsoft/vscode-cpptools#1704]
I was wondering why  should I configure `includePath` to enable auto-completion and meanwhile configure `browse` to enable `Go to definition`.

I configured `includePath` and I can  use auto-completion smoothly, but the function `Go to definition` did not work until I also configured the `browse` attribuite. So there are duplicated configurations of "path"(in both `browse` and  `includePath`).

Can we just keep one piece of `path` settings in `includePath` or `browse` ?

**Comment by bobbrow** [comment]
When we make `includePath` recursive, we can get rid of `browse.path`.

**Comment by tksuoran** [comment]
Go to Definition should also work with compileCommands - it does not seem to.
compileCommands would be superior to both includePath and browse, please make Go to Definition to work with compileCommands.

**Comment by mtripp100** [comment]
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md#what-is-the-difference-between-includepath-and-browsepath-in-c_cpp_propertiesjson explains it well

**Comment by sean-mcmanus** [comment]
@bobbrow The related issue I responded to was https://github.com/Microsoft/vscode-cpptools/issues/1715 . The current design was for users to set the browse.path, even if compileCommands is used...not sure if we should revise that.

**Comment by tksuoran** [comment]
includePath and browse are global, and thus do not work well or at all with large workspaces that contain multiple libraries, each with their own include paths and defines. Meanwhile compileCommands works also for workspaces that contain multiple libraries/projects.

IMHO compileCommands, if present, should be checked first for include paths and defines, and browse would be optional - browse could still be a fallback for files that do not appear in compileCommands, but I would not personally have use for it.

compileCommands also supports -isystem, I do not think it is supported by includePath or browse.

Having said that, IMHO it makes no sense that there same information needs to be entered to both includePath and browse. I am sure you could internally generate includePath from browse. It should not require many lines of code. So why not do it? Current situation where people need to manually copy paste stuff is silly.

**Comment by zsynacl** [comment]
thank @mtripp100 a lot, this FAQ is very usefull.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
