### ISSUE TITLE
Changes to the compile commands file aren't detected if the file watcher limit is hit

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1708]
Doesn't seem worth fixing (most users should probably increase their OS file watcher limit). Reloading the window is a workaround.

**Comment by decimad** [comment]
This sounds interesting, sometimes it felt like as if the compile-commands was not re-evaluated after a configure step, where reloading fixed the problem, although I did not get any error messages. How does one configure this "OS file watcher limit" value system wide on windows, if that is possible at all?

**Comment by sean-mcmanus** [comment]
See https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc for the issue on Linux. I don't think it's possible to hit this limit on Windows. VS Code shows a warning message if you hit the file watcher limit. It generally only happens if you open one or more large workspaces.

**Comment by decimad** [comment]
Thank you for the clarification!

**Comment by bobbrow** [comment]
A new issue #6285 was opened which addresses this.
