### ISSUE TITLE
vscode 1,4 and .8.1 cpp extension browse file build never completes

### ISSUE THREAD

**Issue by davstew** [microsoft/vscode-cpptools#171]
On very large c++ project the browse file never seems to complete building, there are about 15 additional include paths added in config, folder is ~100gb with 275k files.  Expect browse to file to take a long time on this size project, but seems to never complete, file has been around 1.75 gb for 24 hrs.

**Comment by jgoshi** [comment]
What OS are you on? Did the process (Microsoft.VSCode.CPP.Extension.exe for Windows, Microsoft.VSCode.CPP.Extension.Linux for Linux, Microsoft.VSCode.CPP.Extension.darwin for Mac) crash or is it still running? We are addressing issues that cause the process to crash, which can also result in parsing to never finish.

**Comment by jgoshi** [comment]
I fixed a few crashes and they will appear in the next release of cpptools (version 0.9.2). I'm going to close this for now. If you have a chance to try this out with the new version and it still happens please reopen the issue.
