### ISSUE TITLE
Tag Parser can't see "extern C" functions under ident macro

### ISSUE THREAD

**Issue by mtripp100** [microsoft/vscode-cpptools#1717]
* Operating System: Ubuntu 16.04.4, Windows 7
* VS Code version: 1.21.1 mainline
* C/C++ extension version: 0.15.0
* No custom settings for the extension.

I'm working with a codebase of C functions which are all declared in the following pattern so they can be called from both C and C++:

```cpp
#define IDENT(name)
IDENT("add.h")

#ifdef __cplusplus
extern "C" {
#endif

void add_two(int x, int y);

// other functions...

#ifdef __cplusplus
}
#endif
```

With both the `IDENT` and `extern "C"` blocks present, when I include `add.h` in a new file and try to get autocomplete for `add_two`, nothing appears.. However, if I remove either the ident or the extern declaration, `add_two` appears in the autocomplete list as expected.

The semantic parser is able to parse the file correctly as argument hints appear once the complete name of the function is written, but the name itself does not appear as I assume the tag parser is still responsible for this. Forcing `C_Cpp.intelliSenseEngine"` to `"Tag Parser"` doesn't seem to affect it either.

Thanks!

**Comment by sean-mcmanus** [comment]
IntelliSense completion for non-scoped values was added in https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders . Our official release should be soon. I see add_two in the completions with 0.16.0, so I think your issue will be fixed (when using the "Default" IntelliSense engine)...the bug will still exist if the tag parser engine gets used instead. The workaround for the tag parser is to add the macros to a cpp.hint file in your workspace, although I haven't verified this for your sample code (similar to https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/cpp.hint ).

**Comment by mtripp100** [comment]
@sean-mcmanus thanks for the prompt response, I look forward to the release. I tried adding `cpp.hint` as follows in the project root dir:

`#define IDENT`

but it didn't seem to fix the issue. Is this the correct format and location?

**Comment by sean-mcmanus** [comment]
I think `#define IDENT` should be `#define IDENT(x)`, but I don't understand how your IDENT definition is supposed to work, because it's blank. If the definition of IDENT has anything that would change the C++ parsing, such as '{' it would need to be included in the definition in cpp.hint. More info on cpp.hint can be found at https://msdn.microsoft.com/en-us/library/dd997977.aspx .

We should be releasing our 0.16.0 today.

**Comment by mtripp100** [comment]
@sean-mcmanus thanks, I never did get it to work as `IDENT` is actually more complex than specified here, but I can't post the whole definition for compliance reasons. I eventually got everything working with the semantic parser anyway.

Feel free to close this issue - I think the ability to add `cpp.hint` is the real takeaway here. Thanks.
