### ISSUE TITLE
Debugger Option to View Pointer as Array.

### ISSUE THREAD

**Issue by skl131313** [microsoft/vscode-cpptools#172]
For dynamically allocated arrays are simply represented as a pointer, which has no other indicator that it is an array. It would be nice to have a feature to view a pointer as an array as to view more than simply the first element of the array. In the "variables" tab and also when previewing a variable by hovering over it while debugging.

**Comment by pieandcakes** [comment]
@sprinkle131313 with our 0.9.3 release, we updated to enable gdb's pretty-printing in launch.json as a default. This should resolve this issue. Please comment/reopen with more information if it doesn't

**Comment by kevinmoran** [comment]
It would make a HUGE difference if I could type "some_pointer,x" in the watch window to view some_pointer as an array with x elements.

As it stands I have to use LLDB's memory read syntax, which I constantly have to google and sometimes doesn't seem to work. I've actually resorted to printf debugging for large arrays the last few days. Could we please reopen this issue or can I open another to look into something like that being implemented? It's my number 1 gripe with VSCode debugging at the moment (one of my only gripes).

**Comment by pieandcakes** [comment]
@kevinmoran We have updated our version of the shipped LLDB to allow lldb's python pretty printer to work. Your other option is to look at our [Natvis visualizer option](http://aka.ms/natvis#Anchor_8). The commands you are putting in the watch window are sent to the underlying debugger to evaluate.

**Comment by kevinmoran** [comment]
Thanks for getting back to me, have a decent solution now. For anyone who found themselves here Googling this same problem, you can put this in the watch window: 
`*(int(*)[10])some_pointer 
`
to print "some_pointer" as a 10-element array of type int.

Would still argue that having a simpler solution is a basic debugger feature that should be added, this is way too much syntax/thinking/remembering to do something basic. Debuggers should get out of your way, not challenge you when you're trying to think about your actual code.

**Comment by salda** [comment]
I agree with kevinmoran, that retyping the pointer is too complicated by hand and should be done by debugger.

**Comment by pieandcakes** [comment]
@salda We will take it as a feature request but the underlying debugger is lldb or gdb so the change would need to happen in the debugger itself and not the extension.

**Comment by noobling** [comment]
https://github.com/Microsoft/vscode-cpptools/issues/172#issuecomment-277376704
Has this feature been added for pointer to pointers? e.g. char**

**Comment by creikey** [comment]
@noobling Yes, I am having trouble printing pointer to pointers as well

**Comment by giuscri** [comment]
> For anyone who found themselves here Googling this same problem, you can put this in the watch window:
> `*(int(*)[10])some_pointer `
> to print "some_pointer" as a 10-element array of type int.

or, even simpler: `*some_pointer@3`. Bonus point, check out `*argv@argc`!

**Comment by felipeek** [comment]
Will it ever be done?

**Comment by ghost** [comment]
If you do what @giuscri suggests and put a breakpoint in the function that computes the pointer, the watch will stall indefinitely and cannot be deleted (Windows 10)

eg `*tests()@4` will stall if there is a breakpoint in `tests()`, a function which returns a pointer to a list of test results.

reloading the window after this happens seems to fix it.

**Comment by brunohenriquepj** [comment]
> or, even simpler: *some_pointer@3. Bonus point, check out *argv@argc!

If you have the array length in a variable (e.g., length) you can do this: *some_pointer@length

**Comment by teichert** [comment]
Thanks @giuscri!
If anyone else was wanting to use ~~`*s@strlen(s)`~~ to display a c-string without typing in the length, it turns out that the thing to do in gdb is to use: [`$_strlen`](https://sourceware.org/gdb/current/onlinedocs/gdb/Convenience-Funs.html). So if you have a c-string, `s`, you can display the underlying char array by using the following as a watch expression (the + 1 is for showing the terminating null char): `*s@$_strlen(s)+1`

**Comment by tuket** [comment]
> > For anyone who found themselves here Googling this same problem, you can put this in the watch window:
> > `*(int(*)[10])some_pointer `
> > to print "some_pointer" as a 10-element array of type int.
> 
> or, even simpler: `*some_pointer@3`. Bonus point, check out `*argv@argc`!

Looks like this doesn't work anymore?

**Comment by gaming32** [comment]
> > > For anyone who found themselves here Googling this same problem, you can put this in the watch window:
> > > `*(int(*)[10])some_pointer `
> > > to print "some_pointer" as a 10-element array of type int.
> > 
> > 
> > or, even simpler: `*some_pointer@3`. Bonus point, check out `*argv@argc`!
> 
> Looks like this doesn't work anymore?

It works fine for me

**Comment by tripathics** [comment]
> > or, even simpler: *some_pointer@3. Bonus point, check out *argv@argc!
> 
> If you have the array length in a variable (e.g., length) you can do this: *some_pointer@length

Thank you @brunohenriquepj , what would I do without you.. I tried all the suggestions above your answers, none of them worked on my linux machine. But You helped alot.. Will remember this
```
*some_pointer@length
```

BTW I have just started coding with C.

**Comment by JJJohan** [comment]
> > > For anyone who found themselves here Googling this same problem, you can put this in the watch window:
> > > `*(int(*)[10])some_pointer `
> > > to print "some_pointer" as a 10-element array of type int.
> > 
> > 
> > or, even simpler: `*some_pointer@3`. Bonus point, check out `*argv@argc`!
> 
> Looks like this doesn't work anymore?

This has never worked for me either, but that might be because I'm using the cppvsdbg debugger rather than cppdbg. I'd be curious if that's a known limitation or if something else is causing this? I find myself having to revisit this page to remember the pointer order of the longer syntax (i.e. `*(int(*)[10])some_pointer`) that I keep forgetting!

**Comment by tripathics** [comment]
> > > > For anyone who found themselves here Googling this same problem, you can put this in the watch window:
> > > > `*(int(*)[10])some_pointer `
> > > > to print "some_pointer" as a 10-element array of type int.
> > > 
> > > 
> > > or, even simpler: `*some_pointer@3`. Bonus point, check out `*argv@argc`!
> > 
> > Looks like this doesn't work anymore?
> 
> For MSVC (i.e. when using cppvsdbg instead of cppdbg) substitute the @ symbol with a comma, and omit the dereferencing, i.e. i.e. `some_pointer,10`. Only just figured this out myself!

Can I ask what is cppvsdbg? And is it available on Linux?

**Comment by JJJohan** [comment]
> @JJJohan Can I ask what is cppvsdbg? And is it available on Linux?

@tripathics This is referring to the debugger configured in the launch.json file in VS Code. It'll be Windows specific as it's meant for using Visual Studio's toolset as the backend. It's briefly described in the [launch json reference](https://code.visualstudio.com/docs/cpp/launch-json-reference#_type).

**Comment by tripathics** [comment]
> > @JJJohan Can I ask what is cppvsdbg? And is it available on Linux?
> 
> @tripathics This is referring to the debugger configured in the launch.json file in VS Code. It'll be Windows specific as it's meant for using Visual Studio's toolset as the backend. It's briefly described in the [launch json reference](https://code.visualstudio.com/docs/cpp/launch-json-reference#_type).

Btw I am having problem with 2d or 3d array in watch.. idk how to use that pointer syntax for multidimensional arrays in watch.. can you help me?

**Comment by AmirhosseinR** [comment]
For 2d array use this (int pointer_2d[10][15];):
    *(int(*)[10][15])pointer_2d
and so on.

**Comment by batunpc** [comment]
For anyone who having issues still I found this working on my macOS if I put this on my watch window: 
pointerName,[size]
(pay attention having no asterisk at the beginning)

**Comment by z6m8n7ljw** [comment]
> For anyone who having issues still I found this working on my macOS if I put this on my watch window: pointerName,[size] (pay attention having no asterisk at the beginning)

The only way by far that works on my VS for mac !

**Comment by Ch1ldr3n** [comment]
All what you said doesn't work for me :(
![image](https://user-images.githubusercontent.com/34335870/151487002-ccff9684-35c6-4b16-bd6a-d036fc831e24.png)

**Comment by z6m8n7ljw** [comment]
> All what you said doesn't work for me :( ![image](https://user-images.githubusercontent.com/34335870/151487002-ccff9684-35c6-4b16-bd6a-d036fc831e24.png)
In your case, this would be just like this: arr,[5]

**Comment by motla** [comment]
> All what you said doesn't work for me :(
@Ch1ldr3n What debugger are you using? I presume LLDB cause I got the same issue.

**Comment by Ronalyo** [comment]
here's what i've gathered, hope this helps

general forms for expanding arrays (of any dimension, with arbitrary length):
1. ```**...arr@...@len2@len1```: goes from top to bottom, where order of len is reversed
2. ```*(type(*)[len1][len2][...])arr```: goes from bottom to top, order of len is as specified

there's also one for expanding 2 dimensions specifically:
```*arr@len2,len1```: len order reversed, seperate lens with comma
* bottom means element level, top means highest level, see examples for more clarity
---
Examples:
![image](https://user-images.githubusercontent.com/73420425/196333642-7012f816-7549-42b6-9617-6bb9a7b7c70c.png)
1. 1st(_top_) dimension has len = 4, 2nd has 2, 3rd has 3. unspecified dimensions use default len
![image](https://user-images.githubusercontent.com/73420425/196335778-c1f785b9-2a00-486a-b4d4-ac584bd68487.png)
2. highest shown(_not top_) dimension has len = 3, next has 2, next(_bottom_) has 4. unspecified dimensions isn't shown
![image](https://user-images.githubusercontent.com/73420425/196334177-fc6d74cb-ee5e-45ac-9819-dc1eaaa742ff.png)
extra: special 2d expansion is basically method 1. with different syntax
![image](https://user-images.githubusercontent.com/73420425/196334710-8e4a4642-f4ca-4ec7-baac-6944ead17321.png)

**Comment by dsabala** [comment]
What is the reference of `*some_pointer@3` syntax? Where is documentation of such a statements?

**Comment by spking11** [comment]
> What is the reference of `*some_pointer@3` syntax? Where is documentation of such a statements?

[Here](https://sourceware.org/gdb/current/onlinedocs/gdb.html/Arrays.html), and the comma syntax is [here](https://learn.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2022#BKMK_Size_specifiers_for_pointers_as_arrays_in_Visual_Studio_2012/).

**Comment by friendlyman23** [comment]
> > For anyone who found themselves here Googling this same problem, you can put this in the watch window:
> > `*(int(*)[10])some_pointer `
> > to print "some_pointer" as a 10-element array of type int.
> 
> or, even simpler: `*some_pointer@3`. Bonus point, check out `*argv@argc`!

thank you so much for telling me to check this out
