### ISSUE TITLE
Error squiggles appear when declaring function assembly name

### ISSUE THREAD

**Issue by shemarmc** [microsoft/vscode-cpptools#1725]
- Operating System: Windows 10
- VS Code version: 1.21.1 mainline
- C/C++ extension version: 0.15.0
- Clang compiler version: 6.0.0

``` C
#include <stdio.h>

void kernelMain (void *, unsigned int) asm ("kernelMain");
void kernelMain(void* structure, unsigned int number){
    printf("Hello World!");
}

int main(){
    kernelMain(NULL, (unsigned int) NULL);
}
```

On line 3 *kernelMain* is declared and a name is given for it to be read when linking with assembly code. However, Intellisense doesn't recognize the syntax and gives the suggestion to insert a semi-colon after the first closing bracket.
```C
void kernelMain (void *, unsigned int); asm ("kernelMain");
```
This would then make the assembly declaration invalid and cause the compiler to throw an error.
Using the clang compiler have not found an alternative that would allow the function to link properly without the automatic underscore rename.

To reproduce just paste the code into VS Code and save it with as a c file.

So to make myself clear, the bug is that the syntax is not recognized and therefore Intellisense shows squiggles on my code.

**Comment by sean-mcmanus** [comment]
I'm not reproing the bug. Your intelliSenseMode should be set to "clang-x64" in order to compile clang/gcc-based code correctly; otherwise, it uses the Microsoft cl.exe compiler mode (msvc-x64 mode)...maybe the modes should be renamed to avoid this confusion? 0.16.0 enables a compilerPath option too, but we don't yet try to auto-detect/correct potentially incorrect intelliSenseMode values.

**Comment by shemarmc** [comment]
I couldn't find Intellisense mode in the settings but I managed to change it by creating `c_cpp_properties.json` and changing it there.
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "__GNUC__=5"
            ],
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 3
}
```
For anyone else that sees this. I found this on a forum somewhere ad copied it...

**Comment by sean-mcmanus** [comment]
Yeah, you changed the intelliSenseMode correctly (it's not in the settings).
