### ISSUE TITLE
Large workspace (800k+ files)

### ISSUE THREAD

**Issue by tksuoran** [microsoft/vscode-cpptools#1727]
I have a large workspace with over 800000 files in it. I get warning that VSCode is running out of handles, and I also have trouble getting intellisense to work.

I have already configured fs.inotify.max_user_watches=524288. This is still less than number of files in my workspace. I suppose VSCode tries to watch every single file in the workspace? I don't think this is feasibly with the workspace I have.

Is file watching configurable in any way? It should be possible to tell VSCode to exclude/include paths for file watching.

**Comment by tksuoran** [comment]
I found "files.exclude" and "files.watcherExclude".

**Comment by sean-mcmanus** [comment]
Yeah, files.watcherExclude can be used to exclude files from the file watcher, and we look at files.exclude to avoid symbol parsing (but the files won't appear in the explorer or search results.
