### ISSUE TITLE
includePath should handle #include "folder/header.h"

### ISSUE THREAD

**Issue by tksuoran** [microsoft/vscode-cpptools#1728]
Assume I have path/somewhere/include/foo/bar.h. And I have #include "foo/bar.h". It should be enough to have "includePath": "path/somewhere/include" in c_cpp_properties.json. Currently this does not seem to be the case, I need have "includePath": "path/somewhere/include/foo". Note that this is different from recursive include paths.

**Comment by sean-mcmanus** [comment]
What you describe is supposed to work. I'm not able to repro this bug. Can you provide more details? Are you getting a "cannot open source file" error? Is this with a system/library path or a user path? Are you using compile commands? Are you on 0.15.0 or 0.16.0-insiders? Linux or Mac? Can you try with https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders2 ? We fixed some compile commands bugs with that.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having trouble getting system includes to resolve, please remove any system include paths from `includePath` and set the `compilerPath` property in `c_cpp_properties.json` instead.
