### ISSUE TITLE
issue with vtk library recursive include Path!  

### ISSUE THREAD

**Issue by ghodhbane** [microsoft/vscode-cpptools#1729]
Hello 

I added the  vtk path, into  includePath provided in  " .vscode/c_cpp_properties.json " , but C/C++ still can't recognize header file, in my project ?

any idea 

Thank you

**Comment by sean-mcmanus** [comment]
We need more repro details. Is the error "cannot open source file"? The includePath property is not recursive (yet) -- are you adding all the necessary sub-paths? If you set the root vtk path in your browse.path, you can use code actions on the missing include path to automatically add the required subpaths recursively. Also, what is your OS and are you using compile commands? Your full c_cpp_properties.json might help. And what is your C/C++ extension version?

**Comment by ghodhbane** [comment]
Hi

I use : 
Ubuntu 16.04.1 ( 64 bits )
C/C++ ms-vscode.cpptools ( the lastest version)
Yes, " cannot open source file" , even after addign required path

**Comment by ghodhbane** [comment]
please, could you give more details :

>  in your browse.path, you can use code actions on the missing include path to automatically add the required subpaths recursively.

**Comment by sean-mcmanus** [comment]
There's info on setting up your include/browse paths at https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started%20with%20IntelliSense%20configuration.md .

I suspect you need to add the sub-paths to folders with headers instead of just the root.

You have our latest released or insider version (https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders2 )?

**Comment by ghodhbane** [comment]
Hi

Yes, I follow all instruction, "include/browse ", but always the same issues.
Yes, I need to add all sub-paths, but this couldn't be manual since there is so big number of sub-folders.
yes, I installed the latest version. 

always the same issues, many headers files dependencies, located in sub-folders of the same library.

Do you have any others solutions?

**Comment by sean-mcmanus** [comment]
We plan to add support for recursive include paths later. Have you tried setting the browse.path to the root and then using the code actions to add the sub paths multiple times? You could also try generating a compile_commands.json if your build system enables that (such as via cmake).

**Comment by ghodhbane** [comment]
> We plan to add support for recursive include paths later

any date estimation of this update ?
 
>  Have you tried setting the browse.path to the root and then using the code actions to add the sub paths multiple times?
yes, I tried; but a lot of dependencies header files must be added.

it seems, at least for the moment, the only solution is to add manually all subpaths.

**Comment by ghodhbane** [comment]
Hi @sean-mcmanus 

with a simple command line and find/replace on sublime, I can add all sub-folder include path.

> ${librarypath}  tree -f -d -i > file.txt

open this file with Sublime Text
subl file.txt
Ctrl+H
Alt+R
 
Find: /home or the first characters of the path
Replace: "/path_to_root_library" 

next

Find :  \n
Replace : ",\n

After adding all those sub-folder paths, I reloaded VC, all warning message disappeared, but I still can't access to library functions; which mean as before.
the last thing, it seems that the parsing of include sub-folder path takes a long time.

Thanks

**Comment by sean-mcmanus** [comment]
Recursive include paths is expected for April/May.

What do you mean by "can't access library functions"? I assume you're getting errors about library function not being found. It's probably due to missing compiler defines (or includes). The best way to solve this is to make sure your compilerPath is set correctly, with our soon to be released 0.16.0 version or https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders2 .

**Comment by ghodhbane** [comment]
It's ok, after reboot, everything goes well.
I can access all library. 

Looking for the next release :)

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
