### ISSUE TITLE
Wrong Include Path

### ISSUE THREAD

**Issue by Ludonope** [microsoft/vscode-cpptools#173]
Hello,

When I click on the bulb and `Add include path to settings`
it successfully generate `c_cpp_properties.json`,
but the include path for Win32 is a wrong path:
`"includePath": ["c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"]`

On my computer I only have `c:/Program Files (x86)/Microsoft Visual Studio 11.0`, the 14.0 version doesn't exist, and in this 11.0 version, some header files doesn't exists, like `windows.h`.

To fix this, I simply had to put `c:/MinGW/include`, but I don't know if what i got was intended.

Anyway, thanks for your amazing work :)

PS: sorry for mid/bad english

**Comment by jgoshi** [comment]
The includePath is just a hint, we pre-populate it with the expected path for people with that version of Visual Studio. If you don't have that version (or your header files are in a different location) then you can change the includePath as you have done.
