### ISSUE TITLE
Intellisense breaks when followed by struct field compound assignment operators later in same function

### ISSUE THREAD

**Issue by Goz3rr** [microsoft/vscode-cpptools#1730]
Hello, I've run into a strange situation where intellisense suggestions just give up:

- vscode 1.21.1
- vscode-cpptools 0.15.0
- no other extensions enabled

With the following code:
```c
typedef struct
{
    int one;
    int two;
} Foo_TypeDef;

int main(void) {
    ((Foo_TypeDef *) 0x0)-> // Intellisense no longer works properly here
    ((Foo_TypeDef *) 0x0)->two |= 2;
}
```

I get this result:

![image](https://user-images.githubusercontent.com/761433/37840288-f2b2ce52-2ebc-11e8-92b2-4bd11b10b06c.png)

Replacing `((Foo_TypeDef *) 0x0)->two |= 2;` with anything that's not a compound assignment operator (i.e. `((Foo_TypeDef *) 0x0)->two = 2;`), commenting the line out or trying it after this line makes it works fine again:

![image](https://user-images.githubusercontent.com/761433/37840435-5a204d3a-2ebd-11e8-8ff1-d2504bb27881.png)

**Comment by sean-mcmanus** [comment]
Thanks for the bug report. I'm reproing the issue (and in VS 2017 as well). It doesn't repro with C++. It's possible there's some design flaw with the C language that prevents our parser from working, or it could be a bug. I filed a VS 2017 bug at https://developercommunity.visualstudio.com/content/problem/222111/cc-intellisense-autocompletion-fails-in-a-c-file-b.html . If they fix the bug, we can pull in the fix.

**Comment by Goz3rr** [comment]
Cool, thanks for the quick reply

**Comment by sean-mcmanus** [comment]
@Goz3rr Visual Studio "won't fixed" the [bug](https://developercommunity.visualstudio.com/content/problem/222111/cc-intellisense-autocompletion-fails-in-a-c-file-b.html). So that means more people need to upvote the issue.

Update (Feb 2019): This issue got Won't Fixed again.

**Comment by Colengms** [comment]
This issue appears to have been fixed quite a while ago.  Closing.
