### ISSUE TITLE
highlight FIXME and TODO in comment blocks

### ISSUE THREAD

**Issue by davydden** [microsoft/vscode-cpptools#1733]
subj, i.e. 
```
// FIXME: do this ASAP
const unsigned int a = 0;
```
or
```
/**
 * FIXME: don't forget to do that
 */
```

**Comment by sean-mcmanus** [comment]
What do you mean by "highlight"? Can you give an example of another IDE or VS Code language service that implements this "highlighting"?

**Comment by davydden** [comment]
@sean-mcmanus sure, here's what Atom does

![screen shot 2018-03-26 at 13 06 05](https://user-images.githubusercontent.com/8023934/37902966-7b22f5e2-30f6-11e8-8bf0-ce053fc8fc28.png)

**Comment by killerkalamari** [comment]
@davydden In the meantime, consider the "TODO Highlight" extension. It works quite well for me. Here's a sample configuration:

```
    "todohighlight.keywords": [
        "TODO",
        "FIXME"
    ],
```

**Comment by bobbrow** [comment]
We are not currently planning on doing this work.  I see an extension in the Marketplace that appears to do what you want.  Feel free to give it a try.

https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
