### ISSUE TITLE
Fail to install c/c++ extension on Fedora 22

### ISSUE THREAD

**Issue by zzt93** [microsoft/vscode-cpptools#174]
As the following image shows, when I click install button, it show the error and fail to install the extension.
![screenshot from 2016-08-28 18-31-06](https://cloud.githubusercontent.com/assets/5842389/18033125/a6b8b27c-6ce0-11e6-965b-e17b8c38d650.png)

```
uname -a

Linux zzt-pc 4.4.14-200.fc22.x86_64 #1 SMP Fri Jun 24 21:19:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bobbrow** [comment]
Do you still have this problem with the latest version of VSCode & the cpptools extension?

**Comment by bobbrow** [comment]
If you are still having trouble, please let us know.  I'm going to close this issue for now.
