### ISSUE TITLE
The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. #11059

### ISSUE THREAD

**Issue by wuzhijiexia** [microsoft/vscode-cpptools#175]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. Install C/C++ extension
2. Started the extension then the error appear
3. Can't go to definition and declaration

**Comment by jgoshi** [comment]
This should be fixed with the upcoming release of cpptools (version 0.9.0) which will be release in the next week or so. If you still have problems at that time please reopen this bug.
