### ISSUE TITLE
Compiler default includes/defines aren't used with compileCommands if compilerPath isn't set on Windows

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1754]
The bug was found right after we shipped 0.16.0 (it exists in 0.16.0-insiders2 too).

The workaround is to set the compilerPath (it's supposed to try the one in the compile_commands.json command first).

Doesn't repro on Linux/Mac or if cl.exe is used.

**Comment by loaden** [comment]
thx!
