### ISSUE TITLE
Unable to start debugging. UseShellExecute must be false when redirecting I/O.

### ISSUE THREAD

**Issue by paulmadejong** [microsoft/vscode-cpptools#1756]
Today, after switching workspaces, my VSC reported an error "command 'extension.cppdbgAdapterExecutableCommand' not found. when trying to debug my C code that worked fine just before. After reinstalling and following the steps in #1605 I no longer get said message but a new one when debugging: 

> Unable to start debugging. UseShellExecute must be false when redirecting I/O. 

At this point, I can no longer debug my code even after reinstalling the cpptools extension several times. Restarting my system didn't help either. The same extensions and versions running on my CentOS7 VM works fine. It's just my MBP that is no longer working.

I just noticed that this only happens when the MIMode is set to "gdb". With "lldb" it works but I cannot debug my fortran code part of the workspace. Running gdb from command line on the same executable works fine though. Any ideas?

- OS: MacOS High Sierra
- VSC: 1.21.1
- cppTools; 0.16.0
- Extensions: Bash Debug, C/C++/ C/C++ Clang Command Adapter, CMake, CMake Tools, Hg, Modern Fortran, Native Debug, Python

**Comment by pieandcakes** [comment]
@paulmadejong This seems to be an issue that was introduced when @WardenGnaw was fixing the stdout/stderr redirection problem that manifested itself with Invalid json. Unfortunately you might need to rollback to installing the [offline package for OS X](https://github.com/Microsoft/vscode-cpptools/releases/download/v0.15.0/cpptools-osx.vsix) for the previous release until we can ship an update with this fix.

**Comment by Cheng-SG** [comment]
Encounter the same problem! would you please fix this as soon as possibile? Many thanks!

**Comment by coisme** [comment]
+1

**Comment by paulmadejong** [comment]
Reverting to 0.15.0 using the VSIX installer worked for me while waiting for the fix to be released. Thanks!

**Comment by WardenGnaw** [comment]
This is now fixed in 0.16.1

https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.1
