### ISSUE TITLE
Starting client failed (Version 0.16.0)

### ISSUE THREAD

**Issue by bas-zach-freeman** [microsoft/vscode-cpptools#1757]
With the release of Version 0.16.0 I can no longer use this extension.  As soon as I open any c or c+ file the following is printed in the OUTPUT window:

[Error - 10:07:26 AM] Starting client failed
Launching server using command C:\Users\<some-guy>\.vscode\extensions\ms-vscode.cpptools-0.16.0\bin\Microsoft.VSCode.CPP.Extension.exe failed.

    * Operating System and version : Windows 10 Pro
    * VS Code version: 1.21.1
    * C/C++ extension version: Version 0.16.0
    * Other extensions you installed and if the issue persists after disabling them: Unknown
    * step-by-step instructions to reproduce the issue: As soon as I start VSCode this occurs

All was working fine until this upgrade from Version 0.15.0 to Version 0.16.0.  Is there a way to go back to Version 0.15.0? I have set "C_Cpp.loggingLevel": "Information" as suggested but I don't seem to get  any information in the OUTPUT window.  Is there anything else I can try?

**Comment by bobbrow** [comment]
You can go back to 0.15.0 by downloading the [VSIX from the Releases page](https://github.com/Microsoft/vscode-cpptools/releases/download/v0.15.0/cpptools-win32.vsix), but before you install it you will need to set `"extensions.autoUpdate": false` first or else VS Code will immediately update you to 0.16.0 again.

But before you do that, can you check the path you pasted and see if that exe is actually there or not?  You may want to trying uninstalling and reinstalling the extension if it's not.

**Comment by bas-zach-freeman** [comment]
Thank you very much @bobbrow .  That worked.  I am back up and running with Version 0.15.0.  

I tried the path I pasted in the issue this morning and the exe was there in the path shown.  I tried running the exe from the command line and got no errors when I ran it. I also tried uninstalling and reinstalling version 0.16.0 a few times with no luck before I logged this issue. I will check this again on a different machine to see if the issue is isolated to my environment.  Thanks again.

**Comment by bobbrow** [comment]
You can also try installing the VSIX for 0.16.0 from our releases page and see if that works for you.  It is different from the Marketplace version as it comes with all of the dependencies pre-packaged.  It would be good to know if the Marketplace version is encountering an error for some folks.

**Comment by bas-zach-freeman** [comment]
I tried your suggestion of installing the VSIX for 0.16.0 from the releases page and it seems to be working fine unlike the one that came from the Marketplace. Thanks for all your help.

**Comment by sean-mcmanus** [comment]
Oh, this is very weird -- it's the same error I got last night on CentOS7 before I resubmitted the binaries, although it wasn't reproing on Windows so that could just be a coincidence. The offline vsix is built via retrieving the binaries from the same FWlink as the online vsix. Maybe this issue is fixed via https://github.com/Microsoft/vscode-cpptools/pull/1751 .
