### ISSUE TITLE
Language service features don't work when the path starts with "git:" (i.e. staged changes)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1761]
No one has complained about this before...might not matter much because the file is not editable.

**Comment by bobbrow** [comment]
Yeah, IntelliSense only works on the right file because it's passed to the extension with the `file://` protocol

**Comment by sean-mcmanus** [comment]
No, it doesn't work on the right file. This is for staged changes, which don't use the file://. Unstaged changes work on the right.
