### ISSUE TITLE
Automatically adds error message at the beginning of .c file when clicking "Format Document"

### ISSUE THREAD

**Issue by zxy-git** [microsoft/vscode-cpptools#1767]
If I click "Format Document" for a .c file, the formatting process actually completes but an extra line containing error message would be added to the beginning of this file.
`ERROR: ld.so: object '/usr/local/lib/innetgr.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
![screenshot 1180](https://user-images.githubusercontent.com/16920873/38160193-41b9bc2e-3505-11e8-9f44-cab62c76570d.png)
Nothing displayed in the output window even if loggingLevel is "Information".
I have a look at /etc/ld.so.preload and it has only one line of "/usr/local/lib/innetgr.so". Actually there is no such file '/usr/local/lib/innetgr.so'. However, I don't have root access to this system (my school's server) so I can't modify this file. Is it possible to disable this error message?

* OS: Debian 6.0.10
* VSCode: 1.21.1 ia32
* C/C++ extension: 0.16.1

Thanks for your support.

**Comment by sean-mcmanus** [comment]
Ugh -- the process is writing to stderr but not returning an error result -- our code assumes this can't happen and so we redirect stderr to stdout for all child processes, causing the error to get added to the formatted code. What version of clang-format are you running? The one we ship with? Can you try to install another version of clang-format that works with your OS and set the `clang_format_path` as a workaround? See releases.llvm.org/download.html, specifically http://releases.llvm.org/3.3/clang+llvm-3.3-i386-debian6.tar.bz2 , which seems to be the most recent clang distro released for debian 6 (or you could build it from the source or use some sort of apt-get).

I suspect the clang-format binary we ship is not compatible with Debian 6 -- the farthest back we've tested with is with Debian 7-based OS's. It looks like Debian 6 is past it's end of life date: https://wiki.debian.org/DebianReleases . I would recommend upgrading your OS, if possible.

**Comment by zxy-git** [comment]
I try to use the clang-format binary from clang+llvm-3.3-i386-debian6.tar.bz2 but actually this version 3.3 is not compatible with this extension because it does not support arguments "-fallback-style", "-sort-includes", "-assume-filename" and causes an error.
Log:
````
Formatting failed:
/import/glass/3/zxxxxxxx/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/../LLVM/bin/clang-format -style={ BasedOnStyle: LLVM, UseTab: Always, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0 } -fallback-style=LLVM -sort-includes=0 -assume-filename=/tmp_amd/glass/export/glass/3/zxxxxxxx/test1.c
  clang-format: Unknown command line argument '-fallback-style=LLVM'.  Try: '/import/glass/3/zxxxxxxx/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/../LLVM/bin/clang-format -help'
  clang-format: Did you mean '-style=LLVM'?
  clang-format: Unknown command line argument '-sort-includes=0'.  Try: '/import/glass/3/zxxxxxxx/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/../LLVM/bin/clang-format -help'
  clang-format: Did you mean '-style=0'?
  clang-format: Unknown command line argument '-assume-filename=/tmp_amd/glass/export/glass/3/zxxxxxxx/test1.c'.  Try: '/import/glass/3/zxxxxxxx/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/../LLVM/bin/clang-format -help'
  clang-format: Did you mean '-length=/tmp_amd/glass/export/glass/3/zxxxxxxx/test1.c'?
````
I cannot build LLVM 5.0.0 from its source because my cmake version is lower than requirement. So I consider to redirect the stderr of original clang-format to /dev/null. I rename it to "clang-format1" and create a bash script named "clang-format" in the same directory.
````bash
#!/bin/bash
${0}"1" "$@" 2>/dev/null
````
Now the "ld.so" error message won't appear.😀 But it is just a temporary solution. I still wish you fix this redirection issue. Thanks.

**Comment by bobbrow** [comment]
I believe we actually addressed this last year, but we lost track of this issue.  If you continue to have a problem with this, please let us know.
