### ISSUE TITLE
"Go to definition" command show wrong file.

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cpptools#177]
_From @magpier84 on August 28, 2016 11:57_
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.2
- C/C++: 0.8.1

Steps to Reproduce:
1. Select header file of some class in workspace file browser.
2. Go to definition of some its methods.
3. Cpp file is opened but its path isn't relative to root of the workspace. In "Open Editors" section it is displayed as path from root of the drive (cut on left side: "t/subfolder/file.cpp") with hint  "/Users/admin/project/subfolder/file.cpp". The hint of tab shows "/Users/admin/project/subfolder/file.cpp"
4. Breakpoints can not be set if file was opened in above described way.
5. Two instances of the same file can be shown in tabs.

_Copied from original issue: Microsoft/vscode#11064_

**Comment by jgoshi** [comment]
This is fixed in the upcoming release of cpptools (version 0.9.0) and should be available in the next week or so. If this still repros for you at that time please reopen the bug.
