### ISSUE TITLE
Theme: configure enums, static/member vars, etc

### ISSUE THREAD

**Issue by britalmeida** [microsoft/vscode-cpptools#1773]
I did not manage to configure several components of the C and C++ language to my liking.
I tried adding something as follows to the settings:

```
    "editor.tokenColorCustomizations": {
      "textMateRules": [
        {
          "scope": "meta.enum",
          "settings": {
            "fontStyle": "bold",
            "foreground": "#dc3958",
          }
        },
      ]
    },
```

However, this has no visible effect and by using  `Developer: Inspect TM scopes` on the parts I am interested, the only results are `source`or sometimes `meta.block`.

Is it not possible to configure these items? Or maybe I am doing it wrong, but I could not find other documentation.

**Comment by sean-mcmanus** [comment]
The C/C++ extension doesn't implement any of the syntax colorization -- it's implemented as part of VS Code using textmate and atom/language-c. Can you file an issue at https://github.com/Microsoft/vscode/issues ?
