### ISSUE TITLE
Allow specific workspace folders to be referenced via ${workspaceFolder:folderName}

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1774]
From @Jvinniec in https://github.com/Microsoft/vscode-cpptools/issues/1627 :
I'm trying to work in a workspace with multiple folders and according to [this post](https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder) I should be able to specify the paths to the individual folders with something like `${workspaceFolder:FolderName}`. The relevant note is:

> For example, in a multi root workspace with folders Server and Client, a ${workspaceFolder:Client} refers to the path of the Client root.

**Comment by azydevelopment** [comment]
Is this due to get implemented? It would make development so much easier when you have a project that depends on another project but is in a different folder and want the includes to resolve correctly in the cpp properties json file.

**Comment by sean-mcmanus** [comment]
@azydevelopment It's not on our schedule yet, so I'm not sure when we'll get around to adding it...might just be a couple line change, not sure. I think it's possible to implement this in our open source code if anyone wants to contribute a fix :)

**Comment by bobbrow** [comment]
I opened a pull request for this.

**Comment by sean-mcmanus** [comment]
@azydevelopment It's implemented in 0.17.3.

**Comment by azydevelopment** [comment]
Thanks guys that's awesome! I'll let you know if I run into any issues.
