### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/vscode-cpptools#1775]
i build c/c++ with vscode and mingw64 on windows.  when i comiple my program, there are no any warns or errors, however vscode always gives me red error tip, like below:
![image](https://user-images.githubusercontent.com/8075421/38231454-3ab9f708-3745-11e8-82e6-12091a7860cf.png)
my c_cpp_properties.json like below:
![image](https://user-images.githubusercontent.com/8075421/38231503-6bec3340-3745-11e8-9324-39735758d838.png)
I want to why vscode always gives me the red error tip ? Is't the cpptools bug ? How can i fix this ?

**Comment by sean-mcmanus** [comment]
Does adding the compilerPath property and setting it to your mingw compiler fix it? If not, it's a bug, and we'll investigate a repro/fix.

**Comment by DFVSQY** [comment]
i have solved this issue by modify c_cpp_properties.json:
![image](https://user-images.githubusercontent.com/8075421/38238104-70a03222-375b-11e8-95bc-076ffa6e978d.png)
I add "__GNUC__=7" to "defines" node, now it's ok.

**Comment by sean-mcmanus** [comment]
Also, if you set your compilerPath to your gcc compiler, then `__GNUC__=7` should be set automatically, in addition to a bunch of other defines set internally by your compiler, in case you hit any other issues caused by those defines being missing.
