### ISSUE TITLE
Error squiggles don't update after a header file is modified (until an edit or open)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1779]
1. Modify a header file.

Bug: The C++ file that uses the header file doesn't have it's squiggles updated until an edit or (re) open occurs, even though things like hover are updated.

The previous/related issue is https://github.com/Microsoft/vscode-cpptools/issues/1501 .

The bug doesn't repro if the file is active when the header changes (i.e. if the header is modified in one VS Code instance and the source is active in another VS Code instance)...although the update is delayed by 5 seconds or so.

UPDATE: It might not repro in some cases (not sure what causes it to not repro yet).

**Comment by bobbrow** [comment]
There is a known issue where we won't correctly link `header.h` to `source.cpp` after you type `#include <header.h>`.  Is this what you're seeing?  Closing and reopening `source.cpp` works around the issue.  But the IntelliSense clients don't currently check for new `#includes` after edits are made.

**Comment by sean-mcmanus** [comment]
No, that's not the issue I'm seeing. The repro is not with newly added #includes.

**Comment by sean-mcmanus** [comment]
This might be fixed with the fix for https://github.com/Microsoft/vscode-cpptools/issues/3260 ...or the repro is more complicated.

**Comment by sean-mcmanus** [comment]
I repro this bug on Linux and it's fixed now with my changes. @bobbrow @michelleangela Let me know if anyone can repro this after my fix get checked in.

UPDATE: Fixed with 0.22.0-insiders3.
