### ISSUE TITLE
IntelliSense isn't updated in source files when headers change if the header file isn't open in the source file's VS Code instance

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1780]
1. Open a workspace with C/C++ file that includes a header and references code in it, but don't have the header file open.
2. Modify the header file in a different VS Code instance (or external editor).

Bug: The IntelliSense for the source file isn't updated. It is only updated after the externally modified header is opened in the source file's VS Code instance and then the source file is edited or re-opened.

Previous issue is https://github.com/Microsoft/vscode-cpptools/issues/1501 .

**Comment by dasfdlinux** [comment]
Is there an estimate for when this issue might be addressed, or if there are plans to address it in the future? I currently use a program which automatically generates header files which I need to reference, and when they are updated my C++ shows errors that no longer exist (or doesn't show errors that now exist).

**Comment by sean-mcmanus** [comment]
No estimates or plans yet. It's on our big "todo" list. You can upvote this issue.

**Comment by wsnel** [comment]
Running into this issue as well, using protobuf development. I'd like to be able to just force a refresh manually. Perhaps also relevant: I'm experiencing regular out-of-sync situations that seem to only resolve after a vscode restart, when using the remote-development extension.

**Comment by killerkalamari** [comment]
> I'd like to be able to just force a refresh manually.

Go to the vscode keyboard shortcuts settings and search for "Reload Window". Assign it a key combo that works for you.

**Comment by wsnel** [comment]
Thanks @killerkalamari! Reloading the window using the kb-shortcut, indeed forces Intellisense to pick up my background header file changes. It also works 100% when working remotely through the remote-development extension. Great, this solves the whole issue for me.

**Comment by bobbrow** [comment]
@sean-mcmanus I was talking to @Colengms about this today. He said you made a change to update_range that might have addressed this.  Do you know if it did?

**Comment by Flaming-Dorito** [comment]
Any idea if or when a header files auto-refresh option might be implemented?

Reloading the window manually currently is working for me but is a bit of a hassle. plus it takes longer for more and longer files.

**Comment by sean-mcmanus** [comment]
Yeah, that's in progress for 1.2.0.

**Comment by sean-mcmanus** [comment]
I don't repro this with 1.1.3. I see the updates take effect after something causes an idle refresh, such as switching docs. Let me know if someone has repro details.

**Comment by sean-mcmanus** [comment]
Ah, I think the issue is that the switching of docs shouldn't be required.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 ...or at least we fixed the scenario that we encountered -- if you're still seeing issues, your issue has a different root cause and we'd need more repro info (in a separate bug.
