### ISSUE TITLE
Intellisense doesn't show structure members

### ISSUE THREAD

**Issue by atomlin** [microsoft/vscode-cpptools#1781]
Running Extension Version 0.16.1 on Ubuntu
VSCode Version 1.19.3

I run VSCode using directory not workspace.

Intellisense does not seem to restrict itself to the structure I am using.

struct foo {
  int a;
  int b;
} sausage;

if I type sausage.  I get hundreds of suggestions, instead of just a and b.

**Comment by sean-mcmanus** [comment]
I'm not able to repro the problem on Linux with 0.16.1 of our extension. If you're getting too many results, it means it's falling back to the Tag Parser and not the IntelliSense engine. Is your intelliSenseEngine set to "Default"? Do you see any messages in the problems window?

You're doing an Open Folder right?

![image](https://user-images.githubusercontent.com/19859882/38283008-4cdb3dca-3768-11e8-9a32-5980d2014fc1.png)

**Comment by atomlin** [comment]
Ok, thanks for the pointer. In the problem window is 
file: 'file://xxx.h'
severity: 'Info'
message: '#include errors detected. Please update your includePath. IntelliSense features for this translation unit (/xxx.cpp) will be provided by the Tag Parser.'
at: '5,1'
source: ''
code: 'undefined'
I'll see if fixing that works.

**Comment by atomlin** [comment]
I created a workspace file at the root of the main git directory and added my code folder to the workspace. I added the root of the library (which is also a subfolder of the workspace).
I added                 "${workspaceRoot}/libraries/boost_1_65_1/boost",
to the config file. It still complains, I'll experiment some more.

**Comment by sean-mcmanus** [comment]
You can set the intelliSenseEngineFallback to "Disabled" to get completion results even though include files are missing (assuming the definitions don't require the missing include files).

If it's missing system headers, you might want to set your compilerPath.

For project headers, you can generate a compile_commands.json if your build system supports that (such as cmake), or you can add the root of your project to the browse.path and then use the code actions over the missing includes to recursively find/add them (we plan to implement a recursive includePath soon).

**Comment by atomlin** [comment]
Just to circle back. Your help got me going. Opening code at the parent directory resolved the issue. I was then able to use the lightbulb to add the extra directories. Intellisense now works. Cheers Andy
