### ISSUE TITLE
IntelliSense shows unnecessary error squiggles

### ISSUE THREAD

**Issue by Karbonyth** [microsoft/vscode-cpptools#1784]
- Windows 10 v1709
- VSCode Windows v1.21
- Cpptools v0.16.1

VScode was setup to [use Linux headers from the WSL filesystem](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md) (my properties and settings file are the same as in the link, nothing funky added) as well as the WSL bash. When compiling via bash inside VSCode, no errors are shown and the build is successful.

The problem is, IntelliSense marks a bit of code with error squiggles when it's unnecessary, as shown on this picture : 

![code_2018-04-04_09-32-01](https://user-images.githubusercontent.com/4431607/38283877-0fce9ff2-37eb-11e8-90af-2982a2f88dff.png)

Declaration of "_callManager" in the object:
![code_2018-04-04_09-30-24](https://user-images.githubusercontent.com/4431607/38283831-d9c4bb58-37ea-11e8-8c49-35ffbac5efed.png)

When looking at the given error, here is what I have :
`
message: 'no instance of overloaded function "std::map<_Key, _Tp, _Compare, _Alloc>::insert [with _Key=int, _Tp=std::function<InPacket *(InPacket *)>, _Compare=std::less<int>, _Alloc=std::allocator<std::pair<const int, std::function<InPacket *(InPacket *)>>>]" matches the argument list -- argument types are: (std::pair<int, std::_Bind<std::_Mem_fn<InPacket *(InManager::*)(InPacket *package)> (InManager *, std::_Placeholder<1>)>>) -- object type is: std::map<int, std::function<InPacket *(InPacket *)>, std::less<int>, std::allocator<std::pair<const int, std::function<InPacket *(InPacket *)>>>>'
at: '7,17'
source: ''
code: 'undefined'`

I did try to compile with warnings, to be sure I didn't write anything bad that would build but make IntelliSense crazy, but nothing.

**Comment by Karbonyth** [comment]
Additional information:

I forgot to add, using VSCode and Cpptools on Debian (Versions up to date as yesterday, no insider build) doesn't show the errors squiggles.

**Comment by sean-mcmanus** [comment]
It could be due to the fact that compilerPath isn't implemented for WSL yet, so the required compiler defines are missing. I'll check if I can repro this and if it's fixed after adding the WSL compilerPath.

**Comment by Karbonyth** [comment]
I did not know the existence of "compilerPath".  

I installed MinGW with the g++ compiler package, and added the following line to my configuration in the `c_cpp_properties.json` file:

` "compilerPath": "C:/MinGW/bin/g++.exe"`

The error squiggles are no more.

**Comment by sean-mcmanus** [comment]
Yeah, on Linux we have code that will auto-add the compilerPath with a guessed compiler, but we haven't added that code to Windows yet, so the compilerPath is not as discoverable on Windows.
