### ISSUE TITLE
IntelliSense process crash when parsing C variable length arrays (in scan_function_body + 4256)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1785]
Top hitting IntelliSense parsing crash on Mac, probably Linux too (also repros on Windows, but less frequently). Might just be able to add a null check.

With 0.21.0-insiders, the top of the crashing thread call stack looks like:

Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	
0   scan_function_body + 4240
1   function_definition + 4642
2   scan_nonmember_declaration + 16702
3   declaration + 212

On Windows, process_vla_parameters is at the top of the stack due to differences in inlining.

UPDATE: We'll have a fix for December's release, but we're not 100% sure it'll solve the issue.

**Comment by sean-mcmanus** [comment]
We're trying to find a repro in order to fix the root cause, so if anyone has code that uses C with variable length arrays and are hitting this IntelliSense crash then please let us know.

**Comment by hoffmael** [comment]
I have a project hitting this, I logged #2519 against this issue.
