### ISSUE TITLE
Issues with Qt include path for intellisense 

### ISSUE THREAD

**Issue by LordZane** [microsoft/vscode-cpptools#1789]
I have `C:/Qt/5.10.1/msvc2017_64/include` in my include path, and it can't find `#include <QtWidgets>`, which is `C:/Qt/5.10.1/msvc2017_64/include/QtWidgets/QtWidgets` (QtWidgets file in a folder of the same name)

**Comment by bobbrow** [comment]
If this is the case, then you either need to add `C:/Qt/5.10.1/msvc2017_64/include/QtWidgets` to your include path, or use `#include <QtWidgets/QtWidgets>` in your code.

**Comment by LordZane** [comment]
Weird, I swear ive tried that, but it worked. Thanks!
