### ISSUE TITLE
Char array should be shown as string, not as nornal array

### ISSUE THREAD

**Issue by IanChen83** [microsoft/vscode-cpptools#179]
Just moved this issue from [vscode](https://github.com/Microsoft/vscode/issues/11085#issue-173710908)

---
- Cpptools Version: 0.8.1
- VSCode Version: 1.3.1
- OS Version: Linux 4.7.1

As title, character array is shown as a normal array everywhere in debugging mode, which can be annoying when watching on a very long string.

![normal array](http://imgur.com/rTOwqeH.jpg)

Ideally, it should be shown as what gdb would print
![gdb print](http://imgur.com/wapipVk.jpg)

**Comment by pieandcakes** [comment]
@PatrickChen83 We have enabled gdb pretty printers by default in new `launch.json` files in our 0.9.2 release. Please try it and see if this resolves your issue.

**Comment by DanOlivier** [comment]
I'm not sure why this was closed. The pretty printer is on, and yet the variable is displayed as a char array, but the point is that it should be coerced into a string (from char[] to char*). This definitely degrades the user experience. 
Ideally, we would have an example of a custom gdb-python program that overrides the printing for designated structures with embedded char[] members (similar to what is done for libstdc++ types). This plugin would need to be sourced at the start of the debug session.
I would do this myself (and may yet), but it's tricky to nail down the syntax.

**Comment by pieandcakes** [comment]
@DanOlivier This is probably an external feature as we don't control/install gdb. If you want to modify gdb-python and contribute that visualization back to gdb or share it here with people in the documentation section, it would be helpful. 

We also allow users to change visualization through the use of [.natvis](https://msdn.microsoft.com/en-us/library/jj620914.aspx) files.

**Comment by gggin** [comment]
@pieandcakes  is `.natvis` supported for all platform vscode?

**Comment by pieandcakes** [comment]
@gggin yes, we support a limited implementation for `.natvis` for all supported platforms using this extension.

**Comment by zhangjp0405** [comment]
this problem is solved?  I also have this problem. can you say a method?
