### ISSUE TITLE
Edit Configuration isn't available for additional workspace folders until a C/C++ file is opened from that folder

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1791]
No users have complained yet and there's an easy workaround, so it seems low priority.

Other language service operations for the additional workspace folder may also not work (not sure).

I hit this after adding a 2nd workspace folder, not sure if repro if the 2nd folder already exists in the workspace.

**Comment by michelleangela** [comment]
We are currently unable to address this feature request since we are focusing on higher priority features and bugs right now.  We'll tag this for follow up in case it receives more interest from the community, but to keep our issue count manageable, we're closing this issue for now.
