### ISSUE TITLE
Additional Include Folders

### ISSUE THREAD

**Issue by tmakuch** [microsoft/vscode-cpptools#18]
_Additional Include Folders_ would be great for IoT development.

**Comment by sridmad** [comment]
Following should allow you to specify additional include folders

CTRL + P to bring up the command windows. Type the following and hit enter

> C/Cpp: Edit Configurations

It will create a configuration file that allows you to specify additional include folders in the following format

```
includePath:["path1", "path2"]
```

**Comment by eliotstock** [comment]
I can't get this to work. If I use:

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": ["~/dev/nRF5_SDK_11.0.0_89a8197/components/",
                "~/dev/nRF5_SDK_11.0.0_89a8197/components/ble",
                "~/dev/nRF5_SDK_11.0.0_89a8197/external/segger_rtt"]
        },
        {
            "name": "Linux",
            "includePath": ["/usr/include"]
        },
        {
            "name": "Win32",
            "includePath": ["c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"]
        }
    ]
}
```

Then place the cursor in a function name in main.c and hit F12, I'd expect to do to the definition of that function, which is in a file in ~/dev/nRF5_SDK_11.0.0_89a8197/external/segger_rtt. Nothing happens.

Can I expect this to work?

**Comment by spinicist** [comment]
This feature half works for me. However, it seems to fail if my includes have this form:
`# include <directory/header_name>`
I use the Eigen library a lot, and all the includes have `Eigen/` at the front. Includes that have no directory at the front seem to work fine with `includePath`.

**Comment by jgoshi** [comment]
In the next release, version 0.8.0, we will support subdirectories in include paths (ex: #include <directory/header_name>).

As for the other part of this bug, we currently do not support "~" syntax such as "~/dev/nRF5_SDK_11.0.0_89a8197/components/ble". I'm closing this bug but you can track that work in the following issue.
#87

**Comment by spinicist** [comment]
Looking forward to it.

**Comment by guoqingaa** [comment]
Win32, includePath? help me
