### ISSUE TITLE
Precise auto complete using clang.

### ISSUE THREAD

**Issue by be5invis** [microsoft/vscode-cpptools#180]
And move the current behavior to the backup if clang is not installed.

**Comment by agauniyal** [comment]
https://github.com/Valloric/ycmd
Vim frontend to ycmd - http://valloric.github.io/YouCompleteMe/

Here's sample code to get connected to ycmd via javascript - 

``` js
var http = require('http');
var crypto = require('crypto');

var secret = crypto.randomBytes(16);

console.log(secret.toString('base64')); // the secret

var postData = JSON.stringify({});

function generateHmac(data, encoding) {
  return crypto.createHmac('sha256', secret).update(data).digest(encoding);
}

var options = {
  hostname: '127.0.0.1',
  port: 8888,
  path: '/debug_info',
  method: 'GET',
  headers: {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(postData)
  }
};

options.headers['X-Ycm-Hmac'] = generateHmac(Buffer.concat(
  [
    generateHmac(options.method),
    generateHmac(options.path),
    generateHmac(postData)
  ]), 'base64');

var req = http.request(options, (res) => {

  console.log(`STATUS: ${res.statusCode}`);
  console.log(`HEADERS: ${JSON.stringify(res.headers)}`);

  res.setEncoding('utf8');
  res.on('data', (chunk) => {
    console.log(`BODY: ${chunk}`);
  });
});

req.on('error', (e) => {
  console.log(`problem with request: ${e.message}`);
});

req.write(postData);
req.end();
```

**Comment by agauniyal** [comment]
If you change backend to clang or clang based completion systems, you get 
- autocompletion
- advanced linting
- suggestions and code fixits(automatically fix problems with your code)
- code formatting
- automatic header file inclusion
- c++ official code guidelines recommendations

and many other things.

**Comment by lygstate** [comment]
PIng for it.

**Comment by nicber** [comment]
This is a ycmd client that works pretty well:
https://github.com/richard1122/vscode-youcompleteme

**Comment by be5invis** [comment]
Any progress?

**Comment by jankap** [comment]
There are 2 clang solutions:
https://github.com/mitaki28/vscode-clang
https://github.com/kube/vscode-clang-complete

both not very active though... 
A built in (actively maintained) clang solution would be awesome; this enables the possibility to use clang compatible compilers as well, for example the ARM/Keil armclan compiler v6 (ARM Cortex m0-m7 development).

**Comment by bobbrow** [comment]
We will be tracking our improved autocomplete experience with issue #13.  We won't be using clang directly, but our engine has a clang mode that will used on Mac/Linux.
