### ISSUE TITLE
Error code: Code language not supported or defined.

### ISSUE THREAD

**Issue by ismadelgad11** [microsoft/vscode-cpptools#1808]
* C/C++ extension version
hello I'm having some problems running my C++ code on Visual Code in Mac.
Im having trouble setting up c++ on code, i already add the extension of c++ and still having error code.

Here are some screenshots I took.
![screen shot 2018-04-09 at 2 21 43 pm](https://user-images.githubusercontent.com/36654490/38528566-ec9c57d8-3c25-11e8-8d45-098baa122a3f.png)
![screen shot 2018-04-09 at 6 43 00 pm](https://user-images.githubusercontent.com/36654490/38528567-ecad1a5a-3c25-11e8-86b4-436434aa8ded.png)
![screen shot 2018-04-09 at 5 30 12 pm](https://user-images.githubusercontent.com/36654490/38528569-ecbe3cc2-3c25-11e8-89ce-4605bff124f7.png)

**Comment by sean-mcmanus** [comment]
You should save your file with a .cpp extension -- it's currently "Untitled-1". You could also try changing the "Plain Text" in the bottom right to "C++".

**Comment by ismadelgad11** [comment]
silly me, thank you! 👍 👍 👍

**Comment by pieandcakes** [comment]
@ismadelgad11 Closing this issue as it looks resolved. Please reopen/comment if that isn't the case

**Comment by rsap32** [comment]
Make sure that file name is saved with .py extension.
![Capture](https://user-images.githubusercontent.com/57633248/68601530-833ded00-04ca-11ea-8916-040d4b408810.JPG)
