### ISSUE TITLE
C/C++ extension in VirtualBox

### ISSUE THREAD

**Issue by alekseyt** [microsoft/vscode-cpptools#1811]
OS:

* Host OS: Ubuntu 14.04.5
* Guest OS: Linux localhost.localdomain 4.15.15_1 #1 SMP PREEMPT Wed Apr 4 08:48:06 UTC 2018 x86_64 GNU/Linux (Void Linux)
* VirtualBox: 4.3.36_Ubuuntu r105129

vscode:

* Version 1.21.1
* Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
* Date 2018-03-14T14:46:30.761Z
* Shell 1.7.9
* Renderer 58.0.3029.110
* Node 7.9.0
* Architecture x64
* C/C++ extension: 0.16.1

Note: this is steps to repro in virtualbox, i wasn't able to reproduce this on native host OS.

Steps to reproduce:

1. Start vscode
2. Open folder with a project
3. Open file, open another file
4. Close file, open another file, etc, repeat 3-4

Actual result 1: repeating steps 3-4 makes "Updating intellisense" icon (fire) to always appear in status bar (doesn't go away over time)
Actual result 2: intellisense doesn't work when this icon is in status bar
Actual result 3: fallback to "default" (tags?) intellisense doesn't seem to work either

5. Close vscode

Actual result 4: some processes are left in memory after vscode exits:

```
[alex@localhost ~]$ ps ax | grep code
 1619 tty1     Sl     0:21 /home/alex/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.Extension.linux
 1639 tty1     Sl     0:01 /home/alex/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 1619 0
 1719 tty1     Sl     0:00 /home/alex/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 1619 1
 2577 pts/0    S+     0:00 grep code
[alex@localhost ~]$
```

Actual result 5: number of processes spawned by vscode may vary and sometimes they might exhaust all available RAM.

Additional info: i looked into vscode's developer console when this happens but there are no visible errors.

It works fine overall in virtualbox, except this issue with intellisense. It's very convenient for me at least to setup dedicated development environment in virtual machine and it would be great to be able to use vscode in virtual machine too. I can live w/o intellisense, but RAM exhausting issue is hard to deal with.

I suspect this might be somehow related to slow i/o operations, sometimes i need to wait 1-2 seconds before file is saved (reproduces in Vim and other editors too), and sometimes even a system tool can show file-related error like "file doesn't exist" or "operation not permitted", for example when file renaming is taking too long.

Can i somehow help to debug this issue?

**Comment by pieandcakes** [comment]
@alekseyt Can you make sure you have at least 2 processors assigned to your virtual box instance?

**Comment by alekseyt** [comment]
Yeah, i have exactly 2 CPUs assigned:

```
[alex@localhost ~]$ neofetch 
                __.;=====;.__                   alex@localhost.localdomain
            _.=+==++=++=+=+===;.                --------------------------
             -=+++=+===+=+=+++++=_              OS: Void Linux x86_64
        .     -=:``     `--==+=++==.            Host: VirtualBox 1.2
       _vi,    `            --+=++++:           Kernel: 4.15.15_1
      .uvnvi.       _._       -==+==+.          Uptime: 35 mins
     .vvnvnI`    .;==|==;.     :|=||=|.         Packages: 985
+QmQQmpvvnv; _yYsyQQWUUQQQm #QmQ#:QQQWUV$QQmL   Shell: bash 4.4.19
 -QQWQWpvvowZ?.wQQQE==<QWWQ/QWQW.QQWW(: jQWQE   Resolution: 1280x800
  -$QQQQmmU'  jQQQ@+=<QWQQ)mQQQ.mQQQC+;jWQQ@'   DE: Xfce
   -$WQ8YnI:   QWQQwgQQWV`mWQQ.jQWQQgyyWW@!     WM: Xfwm4
     -1vvnvv.     `~+++`        ++|+++          WM Theme: Numix
      +vnvnnv,                 `-|===           Theme: Numix [GTK2], Xfce-4.6 []
       +vnvnvns.           .      :=-           Icons: Faenza-Ambiance [GTK2], ]
        -Invnvvnsi..___..=sv=.     `            Terminal: xfce4-terminal
          +Invnvnvnnnnnnnnvvnn;.                Terminal Font: Monospace 11
            ~|Invnvnvvnvvvnnv}+`                CPU: AMD FX-4300 (2) @ 3.803GHz
               -~|{*l}*|~                       GPU: VirtualBox Graphics Adapter
                                                Memory: 1292MiB / 3949MiB

```

I was fiddling with it trying to find more info, it appears that spawned processes multiply when i restart vscode (not a reload, but hard restart: close vscode, start vscode):

```
[alex@localhost ~]$ ps ax | grep code | wc -l
10
```

Start, repro, close:
```
[alex@localhost ~]$ ps ax | grep code | wc -l
12
```

Start, repro, close:
```
[alex@localhost ~]$ ps ax | grep code | wc -l
16
```

Number of processes seems to grow too when i reload vscode from ctrl+shift+p menu:  Reload Window. This is what i've got after reloading vscode several times:

```
Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
O._onExtensionHostCrashed @ /home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2830
/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2207 Extension host terminated unexpectedly.
e.onDidNotificationChange @ /home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2207
/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2761 [Extension Host] debugger inspector at %cFATAL ERROR: MarkingDeque::EnsureCommitted Allocation failed - process out of memory
 1: node::Abort() [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
 2: 0x7f37faffca57 [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
 3: 0x7f37fad9add7 [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
 4: 0x7f37fad9ad55 [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
 5: 0x7f37fad2ce6b [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
 6: v8::internal::IncrementalMarking::StartMarking() [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
 7: v8::internal::IncrementalMarking::Step(unsigned long, v8::internal::IncrementalMarking::CompletionAction, v8::internal::IncrementalMarking::ForceCompletionAction, v8::internal::StepOrigin) [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
 8: v8::internal::IncrementalMarking::AdvanceIncrementalMarking(double, v8::internal::IncrementalMarking::CompletionAction, v8::internal::IncrementalMarking::ForceCompletionAction, v8::internal::StepOrigin) [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
 9: 0x7f37fa82e046 [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
10: atom::UvTaskRunner::OnTimeout(uv_timer_s*) [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/code]
11: 0x7f37fb167826 [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
12: uv_run [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/libnode.so]
13: atom::NodeMain(int, char**) [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/code]
14: main [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/code]
15: __libc_start_main [/usr/lib/libc.so.6]
16: 0x5c4119 [/home/alex/Downloads/vscode-1.21.1/VSCode-linux-x64/code]
%c
<--- Last few GCs --->

[3430:0x120e17350000]     3738 ms: Mark-sweep 20.7 (31.5) -> 17.0 (37.9) MB, 11.6 / 0.0 ms  (+ 26.8 ms in 32 steps since start of marking, biggest step 2.7 ms, walltime since start of marking 48 ms) finalize incremental marking via task GC in old space re[3430:0x120e17350000]     4745 ms: Scavenge 27.3 (40.4) -> 21.3 (40.4) MB, 5.2 / 0.0 ms  allocation failure 
[3430:0x120e17350000]     7917 ms: Scavenge 30.7 (43.4) -> 25.6 (44.9) MB, 54.8 / 0.0 ms  allocation failure 


<--- JS stacktrace --->
```

I guess it was just killed by kernel when it ran out of RAM. By the end of experiments, after oom kill:

```
[alex@localhost ~]$ ps ax | grep code | wc -l
29
```

This is my User Settings (vscode-global):

```
{
    "telemetry.enableTelemetry": false,
    "update.channel": "none",
    "workbench.startupEditor": "none",
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "editor.minimap.enabled": false,
    "editor.detectIndentation": true,
    "editor.insertSpaces": false,
    "editor.folding": false,
    "editor.renderWhitespace": "none",
    "editor.renderIndentGuides": false,
    "editor.tabSize": 4,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "debug.internalConsoleOptions":"neverOpen",
    "git.confirmSync": false,
    "window.menuBarVisibility": "default",
    "workbench.statusBar.feedback.visible": false,
    "C_Cpp.errorSquiggles": "Disabled",
    "workbench.colorTheme": "One Monokai",
}
```

I don't have c_cpp_properties.json or sophisticated C/C++ setup. I just downloaded vscode from website and installed extensions including C/C++, then i do "Open folder" on a directory with project files and that's it. I don't have build tasks either, all i have is launch.json configured for gdb and project-local settings.json that was auto-generated (i didn't edit it).

My list of extensions:

Extension | Author (truncated) | Version
-- | -- | --
Bookmarks | ale | 0.18.2
cpptools | ms- | 0.16.1
cmake | twx | 0.0.17
vscode-todo-highlight | way | 0.5.12
(1 theme extensions excluded)

**Comment by pieandcakes** [comment]
@bobbrow or @sean-mcmanus might have to see if they can repro and debug it.

**Comment by sean-mcmanus** [comment]
Is changing the "intelliSenseEngine" to "Tag Parser" a sufficient workaround? It could be we don't work on that particular OS or it could be a more general deadlock/race condition.

**Comment by pieandcakes** [comment]
@sean-mcmanus they are running Ubuntu 14.04 in Virtual box (which is like Hyper-V, a virtualization platform).

**Comment by alekseyt** [comment]
>Is changing the "intelliSenseEngine" to "Tag Parser" a sufficient workaround?

This fixed it, no more "Updating intellisense" icon, no more dangling processes. I thought i tried every option to disable intellisense, but apparently i didn't. Thank you very much.

>It could be we don't work on that particular OS or it could be a more general deadlock/race condition.

Yeah, whatever. Please let me know if you need any additional info for debugging this. I'm going to close this because my original issue was fixed with workaround and it now works as expected.

**Comment by alekseyt** [comment]
@pieandcakes sorry, maybe i didn't report this issue clearly, i'm running Void Linux in virtualbox, virtualbox is running on Ubuntu 14.04. Here is VM options i'm using:

![screenshot from 2018-04-10 22 35 46](https://user-images.githubusercontent.com/993454/38579427-9f43141e-3d0f-11e8-8015-5279dac02ee2.png)
![screenshot from 2018-04-10 22 35 52](https://user-images.githubusercontent.com/993454/38579428-a153ec06-3d0f-11e8-98fb-b8676e069d0c.png)

**Comment by pieandcakes** [comment]
@alekseyt Ah. that's good to know. Thanks for the clarification.
