### ISSUE TITLE
 The display is not defined

### ISSUE THREAD

**Issue by tiansin** [microsoft/vscode-cpptools#1814]
System: Win10 1703

![3](https://user-images.githubusercontent.com/4232281/38593024-e847e902-3d71-11e8-96a9-ddcd17f4d5f8.png)
![2](https://user-images.githubusercontent.com/4232281/38592887-38567f54-3d71-11e8-8f00-8a0b4bc4d3b0.png)
![1](https://user-images.githubusercontent.com/4232281/38592890-3be88ab8-3d71-11e8-930d-6bb0b7226ca9.png)

**Comment by bobbrow** [comment]
Can you share the source file for `papapa.cpp`? Do you have a **c_cpp_properties.json** file in the `.vscode` folder that you can share?

**Comment by tiansin** [comment]
I may know what the reason is, which is caused by the encoding of the file. The project was generated using Visual Studio 2017.
![1](https://user-images.githubusercontent.com/4232281/38596976-53c8155c-3d87-11e8-916a-9c5993205b8c.png)
I will change the file encoding to UTF-8,This error disappeared.

**Comment by tiansin** [comment]
It turned out that this is the cause of the error. @bobbrow 

![gif](https://user-images.githubusercontent.com/4232281/38597141-629c3f44-3d88-11e8-833d-d890fb4e3765.gif)

**Comment by bobbrow** [comment]
Something else seems to be interfering.  `va_list` is defined by simply including `<windows.h>`, so I don't understand why you would get a squiggle for it and why adding something else before that `#include` has an effect:

![image](https://user-images.githubusercontent.com/12818240/38598541-99d88c82-3d11-11e8-91e1-b70f241ad919.png)

Do you have any other C++ extensions installed?
Which version of the Windows SDK are you using? 
Can you share your Win32 config in the **c_cpp_properties.json** file?

**Comment by tiansin** [comment]
[config.zip](https://github.com/Microsoft/vscode-cpptools/files/1897451/config.zip)

Inside the compressed package is my configuration data.
This should not be a problem with other extensions. I have tried to open only the cpptools extension but the error is still there.
This problem may be related to the ordering of the types?
Or is it due to macro control?

**Comment by bobbrow** [comment]
If you create a simple file with the following code, do you still see errors?

```
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

int main()
{
    va_list args;
    DWORD dw;
}
```

**Comment by tiansin** [comment]
This code reproduces the problem @bobbrow 

[test.zip](https://github.com/Microsoft/vscode-cpptools/files/1900966/test.zip)

**Comment by bobbrow** [comment]
The files in the project you shared were all UTF-16 LE encoded.  Setting the encoding to UTF-8 fixed the squiggles for that project.  We only support UTF-8 encoded files right now.
