### ISSUE TITLE
IntelliSense doesn't automatically use vcpkg include path

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1817]
I've installed Microsoft's [vcpkg](https://github.com/Microsoft/vcpkg) with user-wide integration, but the IntelliSense in VS Code doesn't seem to be automatically using the vcpkg include path.

From [what I've gathered](https://github.com/Microsoft/vcpkg/blob/9ccad4304edc3ac452b3c295d5ee203c861fcc6f/toolsrc/src/vcpkg/commands.integrate.cpp#L148-L272), vcpkg installs a `vcpkg.system.props` file to `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\ImportBefore\Default`, which is then automatically consumed by MSVC and IntelliSense in Visual Studio (but not by the IntelliSense in VS Code?).

The code compiles fine and the IntelliSense in Visual Studio finds the includes. The IntelliSense in VS Code however, displays green squiggles for any vcpkg includes:

![image](https://user-images.githubusercontent.com/3168386/38617768-82eea666-3da0-11e8-85c2-c0e9ffcf0fe3.png)

I can work around this by adding `"C:/Users/flaradr_ljos/Development/vcpkg/installed/x64-windows/include"` to the include paths in `c_cpp_properties.json`, but this isn't portable (as vcpkg is installed on a different location on different systems). This isn't ideal if I want to commit this file to a repository that is shared with other people.

**Comment by bobbrow** [comment]
**c_cpp_properties.json** supports environment variables if you want a workaround for now.  e.g. `${env:VARIABLE}`

We could make a special variable for the vcpkg root folder that you can use in the future.  e.g. `${vcpkgRoot}`

**Comment by ghost** [comment]
`${vcpkgRoot}` sounds good. I don't think vcpkg currently sets any environment variables. I suppose it would help if vcpkg set an environment variable to its root directory when user-wide integration is performed. I'll see about opening an issue or a PR on the vcpkg repo.

**Comment by ghost** [comment]
Actually, I don't think it's sufficient to only provide a variable to the vcpkg root folder.. The include folder is different depending on the target architecture (and whether we're using static libraries or not). It's not necessarily always "vcpkg/installed/x64-windows/include". This is handled in a `.targets` file that `vcpkg.system.props` references.

Although you may have been referring to the `$(VcpkgRoot)` variable in the `.targets` file? That seems to be set to the target architecture specific folder.

**Comment by bobbrow** [comment]
Yes, there is more work we will need to do under the hood to support this, but in the end an include path will need to be added to **c_cpp_properties.json**, and that's what this variable (or maybe a set of variables) should contain.

**Comment by sean-mcmanus** [comment]
Support for the ${vcpkgRoot} variable has been added with 0.17.7.

**Comment by shelper** [comment]
I am  using latest vscode and this plugin on windows, and still have issue with this vcpkg. i did the `integrate install` and seems vscode still cannot resolve `${vcpkgRoot}` in `c_cpp_properties.json`, i added enviroment variable `vcpkgRoot` and used `{env:vcpkgRoot}`, still could not resolve it. 
The only way the intellisense works is using the full abs_path to vcpkg's include folder...
