### ISSUE TITLE
Setting VS Code debugger to use conda environment

### ISSUE THREAD

**Issue by allthatido** [microsoft/vscode-cpptools#1818]
System Info
      * Windows 10 Home , Version 1709 , OS Build 16299.371
VS Code Info
      * Version 1.22.1
      * Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
      * Shell 1.7.12
      * Renderer 58.0.3029.110
      * Node 7.9.0
      * Architecture x64
Python extension
      * Version 2018.3.1

I have installed miniconda on my machine and created a python environment called 'fcnd'. I have modified the user setting to use anaconda prompt to be used as the integrated terminal while I code.

{
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/K",
        "C:\\ProgramData\\Miniconda3\\Scripts\\activate.bat C:\\ProgramData\\Miniconda3"
    ]
}

The anaconda prompt however defaults to the 'base' environment and I have to issue an 'activate fcnd' command to launch my python programs. Can I modify the user settings so that the default environment is 'fcnd' ?

Also when I try to debug the code with the 'Python: Current File' setting, the python debug console uses the base anaconda environement. How can I make the debugging use the anaconda fcnd environment ?
![capture](https://user-images.githubusercontent.com/10551664/38631206-14777154-3d87-11e8-8327-b23cec424e45.PNG)

**Comment by WardenGnaw** [comment]
This does not look like a C++ issue. Forwarding to https://github.com/Microsoft/vscode-python/issues/1371
