### ISSUE TITLE
Stop forcing /usr/include on the IntelliSense path in clang-x64 mode

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1819]
It also causes a bogus error to appear when warnings are enabled (see https://github.com/Microsoft/vscode-cpptools/issues/1805 ).

Also fixed the bogus "last line of file ends without a newline" warning (when "--no_warnings" is removed from msvc.json).

**Comment by killerkalamari** [comment]
Works great, thank you! (0.17.0-insiders)

**Comment by bobbrow** [comment]
This is fixed in 0.17.0.
