### ISSUE TITLE
The extension crashes during auto-formating 

### ISSUE THREAD

**Issue by TaQk** [microsoft/vscode-cpptools#182]
![image](https://cloud.githubusercontent.com/assets/8940956/18094430/b55b0006-6ed3-11e6-9c76-696f831c7ed7.png)

![image](https://cloud.githubusercontent.com/assets/8940956/18094457/cc322e26-6ed3-11e6-9f2b-951a6f3e8408.png)

![image](https://cloud.githubusercontent.com/assets/8940956/18094482/e59b1436-6ed3-11e6-8605-c1bde97b8445.png)

**Comment by greazer** [comment]
Hi TaQk,

Can I assume you added this specific lpath to clang-format because you need it? I ask because with the latest release 0.9.0, we automatically include a build of clang-format that we have been able to test with. If you remove this setting, does the crash still occur? 

Thanks

**Comment by sean-mcmanus** [comment]
We need more repro info, such as what version of clang-format.exe you're using. I can't repro this. We've only tested with the clang-format 3.8.0 and 3.8.1.

**Comment by TaQk** [comment]
> > `Hi TaQk,
> 
> Can I assume you added this specific lpath to clang-format because you need it? I ask because with the latest release 0.9.0, we automatically include a build of clang-format that we have been able to test with. If you remove this setting, does the crash still occur?
> 
> Thanks`

Dear Sir,
I have removed my local instalation of clang (I have been using this with other VSC extansion called clang-format but it doesn't work anymowe after I have installed the C/Cpp ext). 
Next I have reinstalled the C/Cpp extension and removed all extra settings.

When I use shift+alt+f shortcut or context menu to auto-format code nothing happens. After 5 attemps VSC kills the C/Cpp extension. 

I'm using Windows 7 64bit.

**Comment by sean-mcmanus** [comment]
I'm reproing the bug now -- it seems to only repro on Windows 7. We'll look into getting a fix in a future release.

**Comment by sean-mcmanus** [comment]
I've fixed the bug (for the next release). It was actually a bug in the Win7 implementation of the WriteFile function, which was crashing on certain valid inputs, but I worked around the issue

**Comment by TaQk** [comment]
Hi,
thank you for a good news. I will be waiting for new version. 

Regards

**Comment by sean-mcmanus** [comment]
The fix should be in the upcoming 0.9.1 release.
