### ISSUE TITLE
如何让 VSCODE cpptools 支持 C51 (How to make VSCODE cpptools support C51)

### ISSUE THREAD

**Issue by VSCODE-C51** [microsoft/vscode-cpptools#1821]
1. 中断函数会提示报错
(interrupt function display error)
![image](https://user-images.githubusercontent.com/38309323/38658520-247f59f0-3e58-11e8-9657-a4a77b47d17e.png)

2. IO 定义会报错
(MCU IO define display error)
![image](https://user-images.githubusercontent.com/38309323/38658549-3f6a90e0-3e58-11e8-868d-45ee1f607522.png)

**Comment by bobbrow** [comment]
1. It doesn't look like valid syntax.  Is "interrupt" supposed to be an attribute?  You can edit **c_cpp_properties.json** and add `"interrupt="` and `"INT_VECTOR_T0="` to the `"defines"` array.

2. Can you tell me what `sfr` and `sbit` are?  Those are not types I recognize.

**Comment by VSCODE-C51** [comment]
1. ``` interrupt=``` 加入 "defines" 可以的，但 ``` "INT_VECTOR_T0=" ``` 还是不行。
( interrupt is OK，but  ``` "INT_VECTOR_T0=" ```  not support.)
![image](https://user-images.githubusercontent.com/38309323/38711374-d8177494-3ef7-11e8-838f-1b82ae363a53.png)
![image](https://user-images.githubusercontent.com/38309323/38711388-f339b5ca-3ef7-11e8-8d65-f25fddfa2f5c.png)

2. ```sfr``` 和 ```sbit```  已经在  "defines" 中，所以不显示错误。
(Because it was added before, so no error is displayed.）
![image](https://user-images.githubusercontent.com/38309323/38711374-d8177494-3ef7-11e8-838f-1b82ae363a53.png)

**Comment by VSCODE-C51** [comment]
Thank you for replying me.  @bobbrow 
Sorry, My English is poor, but I will study hard.

**Comment by bobbrow** [comment]
1. I should have noticed sooner.  C51 has some language extensions that our vscode extension does not support.  I found it here: http://www.keil.com/support/man/docs/c51/c51_le_funcdecls.htm

2. Does this compile for you in C51?  It is not valid syntax in C.

**Comment by VSCODE-C51** [comment]
Thank you.

I used Keil compiled C51 Code.

**Comment by bobbrow** [comment]
Unfortunately, we have no plans to support C51 extensions at this time.

**Comment by heartacker** [comment]
FYI, this `keil assistant` will be helpful for c51,
https://marketplace.visualstudio.com/items?itemName=CL.keil-assistant
