### ISSUE TITLE
Long strings are truncated to "..." with cppvsdbg

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1824]
UPDATE (old issue, moved to vscode): I can't copy values from the debugger's hover view (no right click) and instead need to locate/add the value in the Watch window. Is this a limitation with VS Code's UI or what? Typescript debugging seems to have the same limitation, so I'm guessing it's a VS Code issue.

I haven't seen many users complain about this so maybe it's not a common thing to want to do?

UPDATE (this is the new issue): Then I ran into a 2nd issue in which I couldn't even copy the entire string in the Watch window, because it got truncated with "...", so I ended up just debugging with VS 2017 :(

**Comment by pieandcakes** [comment]
@sean-mcmanus I'm pretty sure we don't control copy/paste. The UI elements in VS Code are all provided by VS Code, we just return data to them. This is probably a request you will need to make on their side. 

>UPDATE: Then I ran into a 2nd issue in which I couldn't even copy the entire string in the Watch window, because it got truncated with "...", so I ended up just debugging with VS 2017 :(

Which debugger was this using? if you are using gdb, you can specify an additional parameter to return the entire string. Please see [this](https://github.com/Microsoft/vscode-cpptools/issues/1786#issuecomment-378792199).

**Comment by sean-mcmanus** [comment]
Not gdb -- the cl.exe/Windows debugger cppvsdb. Is there a way to enable the full string to get copied with that?

Sure, I'll see if VS Code has a issue open for adding a right-click menu to the debugger tooltips.

**Comment by pieandcakes** [comment]
@sean-mcmanus that string truncation is something we need to investigate. Please +1 that issue for now.

**Comment by sean-mcmanus** [comment]
I'm not sure what you mean by +1, but I just changed the title (i.e. morphed the bug into the 2nd issue).

**Comment by pieandcakes** [comment]
Go to #1786 and click the + icon in the title bar and choose the thumbs up. This is now a duplicate of that and i'll close this.
