### ISSUE TITLE
#pragma once in main file

### ISSUE THREAD

**Issue by wimalopaan** [microsoft/vscode-cpptools#1825]
Using VSCode 1.22.2 and C/c++-Extension 0.16.1

If I write a simple header file like Abc.h and insert a modern include-guard 

#pragma once

I am getting the very annoying warning:

#pragma once in main file.

**Comment by sean-mcmanus** [comment]
That warning is not from our extension. It must be from another extension that uses clang for warnings, possibly https://github.com/Valloric/YouCompleteMe/issues/216 .
