### ISSUE TITLE
clang.cxxflags has no effect

### ISSUE THREAD

**Issue by wimalopaan** [microsoft/vscode-cpptools#1826]
I try to use the following C++-Flags, but it seems that they don't have any effect:

    "clang.cxxflags": [
        "-Wall -Wextra -Wno-pragma-once-outside-header -std=c++17"
    ],

Also, I can write some bogus text in there, and I don't get any error.

VSCode: 1.22.2
C/C++: 0.16.1

**Comment by bobbrow** [comment]
Our extension doesn't have any setting with that name.  This is likely an issue with another extension you've installed.
