### ISSUE TITLE
identifier "FILE" is undefined

### ISSUE THREAD

**Issue by dnfort** [microsoft/vscode-cpptools#1827]
Issue Type: <b>Bug</b>

#include <stdio.h>
int main( int argc, char **argv)
{
	FILE *fp;
	fp = fopen( "filename", "r");
	fclose( fp);
	return 0;
}

FILE (and fp) are squiggle underlined with hover message:
identifier "FILE" is undefined

There are no compiler errors so it is just a case of annoying red sqiggles.

Extension version: 0.16.1
VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:27:19.487Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz (4 x 2261)|
|Memory (System)|3.68GB (1.18GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
It's not reproing for me. What is your includePath and compilerPath setting? Are you compiling with cl.exe? What Windows SDK do you have installed?

**Comment by bobbrow** [comment]
Can you share your c_cpp_properties.json file?

I suspect you are on a Windows PC without Visual Studio 2015 or 2017 installed, and you just haven't been auto-configured.  We're working on automatic-configurations for MinGW/Cygwin/WSL on Windows, but it's not ready yet, so you need to configure some stuff manually right now.

If my suspicion is correct, run the "C/Cpp: Edit Configurations..." command and set the "compilerPath" property in your c_cpp_properties.json to the path to your mingw compiler.  This should fix up the default includes and defines that will make this work for you.

**Comment by sean-mcmanus** [comment]
I hit this error when my includePath had the Windows SDK paths in it but my compilerPath was set to a gcc-based compiler (removing the Windows paths fixed it).

**Comment by ghost** [comment]
I also have this problem (_FILE is undefined_, _EOF is undefined_, etc.), using MinGW. 
I've set my User _settings.json_: 
 ```
"C_Cpp.default.systemIncludePath": 
   [
      "c:/mingw/lib/gcc/mingw32/5.3.0/include/**",
      "c:/mingw//include/**",
      "c:/mingw/lib/gcc/mingw32/5.3.0/include-fixed/**",
      "c:/mingw/mingw32/include/**"
    ],
```

and in _c_cpp_properties.json_: 
`"compilerPath": "C:\\MinGW\\bin\\mingw32-gcc.exe"`

What am I doing wrong?

**Comment by sean-mcmanus** [comment]
@danijeldomazet Try just setting your compilerPath (in the C_Cpp.default or c_cpp_properties.json). You shouldn't be setting systemIncludePath if you have a compilerPath unless there is problem that is preventing the compiler to be queried for the correct paths and your system include paths shouldn't be using "**", because the ordering in that case is non-deterministic, which is highly likely to not work.

**Comment by ghost** [comment]
Thanks. After I removed the systemIncludePath, it started working OK. Why did I add systemIncludePath at first place? Because it seemed not to work, it wouldn't pick up MinGW system includes. How it got resolved in the meantime - I don't know.
