### ISSUE TITLE
The extension is complaining about finding header files but it actually loads them just fine

### ISSUE THREAD

**Issue by harry-cpp** [microsoft/vscode-cpptools#183]
VS Code is complaining about it being unable to find header files (which are present in "/usr/include" on my system, and that is the default path for the extension to look for them):

![screenshot from 2016-08-30 17-36-57](https://cloud.githubusercontent.com/assets/6773302/18095833/801e6978-6ed8-11e6-9fa8-36d42173c533.png)

But even tho it's complaining about it, the autocomplete works just fine:

![screenshot from 2016-08-30 17-37-46](https://cloud.githubusercontent.com/assets/6773302/18095832/801c421a-6ed8-11e6-924d-4705b0cf6d6a.png)

This happens for both C and C++ projects.

Useful info:
- OS: Arch Linux
- Extension Version: 0.9.0
- VS Code version: 1.4.0

**Comment by jgoshi** [comment]
I'm not able to repro this issue. Did you click on the header and add include path to settings? I'm not sure why the intellisense is showing up though, it isn't for me until I add the include path.

**Comment by harry-cpp** [comment]
The include path is already added and that is why the intellisense is able to work. Header files are located in "/usr/include" on my system.

c_cpp_properties.json looks like:

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": ["/usr/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        },
        {
            "name": "Linux",
            "includePath": ["/usr/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        },
        {
            "name": "Win32",
            "includePath": ["c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        }
    ]
}
```

It has not been modified since "/usr/include" is already set as the default path.

**Comment by jgoshi** [comment]
If you close the file, then reopen does the green line (and the message) go away?

**Comment by harry-cpp** [comment]
> If you close the file, then reopen does the green line (and the message) go away?

No.

**Comment by jgoshi** [comment]
Can you send me the whole folder (I'm assuming this repros for you on a very simple sample right?)

**Comment by harry-cpp** [comment]
The contents of the folder is fully visible in screenshot above... it just has the main.c and main.cpp files (plus the 2 hidden files vs code created).

I can still upload it if you want.

**Comment by jgoshi** [comment]
Yes please. I'm wondering if there are things in your settings files or the browse database that can give me some insight since when I tried this I couldn't repro. Also after you send me those, could you try deleting the .vscode directory then open the root folder again? I wonder if somehow your browse database got messed up.

**Comment by harry-cpp** [comment]
The project: https://drive.google.com/open?id=0BzRP0_lI8PyTdFltZnhMbEZqSmc

> Also after you send me those, could you try deleting the .vscode directory then open the root folder again? I wonder if somehow your browse database got messed up.

Tried it, doesn't work.

**Comment by jgoshi** [comment]
Where is your c_cpp_properties.json file located? It should be in the .vscode directory, but I don't see it there?

**Comment by harry-cpp** [comment]
> Where is your c_cpp_properties.json file located? It should be in the .vscode directory, but I don't see it there?

VS Code settings folder? I am using the default file.

**Comment by harry-cpp** [comment]
Oh wait, creating a c_cpp file in current project removes the green underline.... close it if this was intended to be like this.

**Comment by jgoshi** [comment]
Did you manually place it in the VS Code settings folder? If you clicked on the light bulb when the header wasn't found, it would (should) have created the file in the .vscode folder.

**Comment by harry-cpp** [comment]
> Did you manually place it in the VS Code settings folder? If you clicked on the light bulb when the header wasn't found, it would (should) have created the file in the .vscode folder.

I placed it with the light bulb.

**Comment by ES5017** [comment]
I have the exact same problem but with a red line not green - there is no lightbulb

**Comment by sean-mcmanus** [comment]
@ES5017 We need more repro details. Can you open a new bug?

**Comment by ES5017** [comment]
sure

**Comment by ES5017** [comment]
https://github.com/Microsoft/vscode-cpptools/issues/3216
