### ISSUE TITLE
IF程序段上色的问题

### ISSUE THREAD

**Issue by abcdlzy** [microsoft/vscode-cpptools#1832]
> ms-vscode.cpptools version 0.16.1
> VSCODE version 1.22.2
> all setting are default

代码审计过程中，某些头文件缺少也不打紧，能否给个选项禁用掉对IF段变成灰色的操作？以便于代码审计
Feature request：disable IF program section rendering into gray

![_20180414224813](https://user-images.githubusercontent.com/10682959/38769471-787a116e-4036-11e8-9671-62411a98df5a.png)

**Comment by Leedehai** [comment]
Already reported [here](https://github.com/Microsoft/vscode-cpptools/issues/1707).

**Comment by abcdlzy** [comment]
thx

**Comment by sean-mcmanus** [comment]
@abcdlzy You can set the 'dimInactiveRegions` setting to "false". But in order to get IntelliSense to work on the gray area you would need to set your includePath and defines settings correctly.
