### ISSUE TITLE
Wrong include path error - attempts to check file inside a comment block

### ISSUE THREAD

**Issue by Leedehai** [microsoft/vscode-cpptools#1834]
This is just a comment (line 2) and should not trigger an include path checking.
<img width="680" alt="screen shot 2018-04-14 at 14 31 57" src="https://user-images.githubusercontent.com/18319900/38772634-9e9eab66-3ff0-11e8-8967-f5d79864a381.png">
<img width="686" alt="screen shot 2018-04-14 at 14 31 34" src="https://user-images.githubusercontent.com/18319900/38772635-a214f228-3ff0-11e8-8f93-3b03f72ceda9.png">

**Comment by sean-mcmanus** [comment]
It's "by design" and caused by the fact that html-document.h is included in news-aggregator.cc (the translation unit), which has missing includes. See https://github.com/Microsoft/vscode-cpptools/issues/1651 .
