### ISSUE TITLE
Missing icons in activity bar

### ISSUE THREAD

**Issue by Baozi2** [microsoft/vscode-cpptools#1840]
version 1.22.2
os mac
this is new , the search、git disappear. All extension disabled
![new](https://user-images.githubusercontent.com/5621510/38794669-8a0dc580-4188-11e8-9c8f-d349eed60ad2.png)

**Comment by sean-mcmanus** [comment]
I moved your issue to the VS Code GitHub site: https://github.com/Microsoft/vscode/issues/47942 .
