### ISSUE TITLE
How to cope with non-standard keyword?

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#1849]
I am working with the TI (Texas Instruments) C++ compiler, which supports TI
extension keywords __interrupt, __cregister, and __asm.

I see a squiggle here:

![image](https://user-images.githubusercontent.com/7724321/38937808-fb93cfd0-431b-11e8-9947-7782ce5e2115.png)

which I guess is due to the definition of TSCL not being understood by cpptools:

![image](https://user-images.githubusercontent.com/7724321/38937871-2abe82c8-431c-11e8-95b5-d2ed0175fc82.png)

because it uses the TI keyword __cregister.

Is there anyway I can make cpptools ignore this issue?  (The warnings are a bit irritating).

**Comment by bobbrow** [comment]
If the extension keywords work like attributes and their removal would make the code look like standard c++, then one option is to add the following to the `"defines"` array in **c_cpp_properties.json**:

```
    "defines": [
        "__cregister=",
        "__interrupt=",
        "__asm="
    ]
```

The other option would be to create a support header (e.g. "TI.h") with the same defines as above and use the `"forcedInclude"` property in **c_cpp_properties.json** to have that file included before the first line of all of your source files.  Like this:

**TI.h**
```
#define __cregister
#define __interrupt
#define __asm
```
**c_cpp_properties.json**
```
    "forcedInclude": [ "${workspaceFolder}/path/to/TI.h" ]
```

If TSCL is just an unsigned int, you could also assign it a value via the same mechanism.

**Comment by daldr-ntml** [comment]
Thanks very much for your help. This fixed the problem:

    "defines": [
        "__cregister=",
        "__interrupt=",
        "__asm="
    ]
