### ISSUE TITLE
The extension is complaining about finding missing headers of a #include within a #ifdef.

### ISSUE THREAD

**Issue by be5invis** [microsoft/vscode-cpptools#185]
Like:

``` C++
#ifdef _WIN32
// Windows
#include <Windows.h>
#elif __MACH__
// OSX
#include <unistd.h>
#include <mach/mach_time.h>
#else
#include <unistd.h>
#endif
```

**Comment by jgoshi** [comment]
Are you saying (for example) that if you are on Windows and _WIN32 is defined the extension is still complaining about not finding unistd.h?

**Comment by be5invis** [comment]
@jgoshi No, both unistd.h and mach/mach_time.h
And I cannot find any way to define a variable (like _WIN32).
![image](https://cloud.githubusercontent.com/assets/240091/18140579/bc4872d4-6fe8-11e6-960f-37fdabf883f3.png)

**Comment by jgoshi** [comment]
We currently are unable to detect this situation (understanding the different branches of #ifdef statements based on your environment macro definitions). As we continue to improve our intellisense we can address this issue.

**Comment by bobbrow** [comment]
The new IntelliSense engine can do this properly.  Add `"intelliSenseEngine": "Default"` to your settings.json file and you should no longer see squiggles on the irrelevant headers.  `_WIN32` and `__MACH__` should be defined already on the relevant platforms, but if there are additional defines that you need to define, you can add them to the **"defines"** array in your c_cpp_properties.json file.
