### ISSUE TITLE
ctrl+click always opens files in the same (second) tab

### ISSUE THREAD

**Issue by edogaldo** [microsoft/vscode-cpptools#1855]
Version 0.16.1: March 30, 2018

Suppose "main.c" contains reference to "f1" (defined in "file1.h") and "f2" (defined in "file2.h").
When ctrl+click on "f1" it opens "file1.h" in a second tab.
If then ctrl+click on "f2" it opens "file2.h" in the second tab as well losing reference to "file1.h"
Would have expected "file2.h" to be opened in a new tab so that I can see all 3 files opened..

**Comment by sean-mcmanus** [comment]
This is "by design" VS Code behavior. We just send VS Code the list of definition targets. You can double-click the document title (with italic font) to make the document non-Preview. Or set the workbench.editor.enablePreview setting to false.
