### ISSUE TITLE
VSCode C/C++ Auto-Completion

### ISSUE THREAD

**Issue by metropt** [microsoft/vscode-cpptools#1856]
Auto-Completion doesn't seem to work as expected. Per example when writing an argument I expect to get auto-completion for variables of the same function argument type, per example (QtCreator IDE):

![screenshot from 2018-04-20 10 49 09](https://user-images.githubusercontent.com/764040/39045023-b1c1792e-4489-11e8-9460-58d8d4459199.png)

However on VSCode this is the result:
![screenshot from 2018-04-20 10 53 44](https://user-images.githubusercontent.com/764040/39045096-df0f8bd2-4489-11e8-85c3-aa21604b6a73.png)
![screenshot from 2018-04-20 10 49 55](https://user-images.githubusercontent.com/764040/39045095-deef6f1e-4489-11e8-954e-54a0a9c0afac.png)

**Comment by bobbrow** [comment]
This should work in the latest version of the extension (0.16.1).  Are there any "problems" in the problems window?  Is `"C_Cpp.intelliSenseEngine": "Default"` in your settings?

**Comment by metropt** [comment]
My IntelliSense related settings:
```
 "C_Cpp.autocomplete": "Default",
  "C_Cpp.default.intelliSenseMode": null,
  "C_Cpp.errorSquiggles": "Enabled",
  "C_Cpp.intelliSenseEngine": "Default",
  "C_Cpp.intelliSenseEngineFallback": "Enabled"
```
My plugin version is: 0.17.0

![image](https://user-images.githubusercontent.com/764040/39991503-ab44cb50-5767-11e8-8a7e-3f5d30a875a8.png)

**Comment by sean-mcmanus** [comment]
So autocomplete is working for you now?

**Comment by metropt** [comment]
@sean-mcmanus I don't think so... I have a function with a color(enum) argument and it suggest me a string variable.

**Comment by bobbrow** [comment]
Oh.  We don't do type-checking for parameter hints yet.  I'll mark this as a feature request.

**Comment by sean-mcmanus** [comment]
I didn't even think VS did type-checking for completions as parameters -- seems difficult to do in general because any arbitrary object could have a method that could eventually return an object that is acceptable as a parameter (e.g. printColor(foo1.foo2.fooColor)), but maybe simple types could be filtered out, assuming there's a way to check that no implicit conversion exists between the types.

**Comment by metropt** [comment]
I was wrong thinking that it should do type-check. I take a look on other IDEs and they don't do that.
