### ISSUE TITLE
version0.16.1 cannot work in offline-more information

### ISSUE THREAD

**Issue by zero-sky** [microsoft/vscode-cpptools#1859]
---moro information---
I work in an offline environment.
I use "install from vsix" to install cpptools.
but,
which download from marketplace can not work, include "xxx.h" no lightbulb and waveline suggestion。so I can not use autoComplete, no ./.vscode folder.
which download from github，version 0.16.1. also no lightbulb and waveline 
which download from github, version 0.15.0.  work perfect.

**Comment by WardenGnaw** [comment]
Can you provide more information about which offline installer you are using and what does not work?

**Comment by WardenGnaw** [comment]
Are you using Windows, OSX, or the Linux installer?

**Comment by zero-sky** [comment]
My workplace use window7。
At my home, the environment can connect to internet, using windows10，all work ok.

**Comment by bobbrow** [comment]
You installed this one?  https://github.com/Microsoft/vscode-cpptools/releases/download/v0.16.1/cpptools-win32.vsix

VS Code has been doing weird stuff with upgrades/installs lately.  You may want to check the %userprofile%/.vscode/extensions folder to see if any older versions of the extension are still there (e.g. ms-vscode.cpptools-0.16.1).  Delete any like that (and the .obsolete file if it exists) and then reload VS Code and reinstall the VSIX.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
