### ISSUE TITLE
Attach on Windows should not require the program option in launch.json

### ISSUE THREAD

**Issue by karpinsn** [microsoft/vscode-cpptools#186]
Currently I need to specify the program option in launch.json to attach to a process.

**Comment by delmyers** [comment]
@jacdavis, is this true? Can we get away without adding the program option to the launch.json?

**Comment by jacdavis** [comment]
Yes, it's a bug. I asked Nik to file it while I was showing him how to use the extension. It should be required for all gdb/lldb based scenarios, but is unnecessary in concord.

**Comment by delmyers** [comment]
@pieandcakes, do you have a couple of minutes to look at this? I thought that we had fixed this with this release. Did we forget to fix it on the debugger side?

**Comment by pieandcakes** [comment]
@delmyers We didn't remove the requirement in the package.json. We can have this fixed for the next release.

**Comment by pieandcakes** [comment]
This fix will be in the next release.
