### ISSUE TITLE
Auto-indentation doesn't work when pasting or moving lines

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1860]
I've noticed that VS Code supports automatically indenting code when pasting code or when moving lines around (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd>) via the `editor.autoIndent` setting, but for some reason this doesn't work with C++ files.

I've noticed that this is [disabled by default for C and C++ files](https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/package.json#L1256-L1263), but even enabling the setting doesn't seem to do anything. What would be involved in enabling this behaviour?

**Comment by sean-mcmanus** [comment]
I seem to recall it was disabled due to the annoying/buggy behavior it caused with C++ but there isn't an easy fix using the regular expression mechanism that works in other languages. I think we're tracking this with https://github.com/Microsoft/vscode-cpptools/issues/883 .
