### ISSUE TITLE
Couldn't compile because of "expected a ';' " bug!!

### ISSUE THREAD

**Issue by hoan-cosmos** [microsoft/vscode-cpptools#1861]
Using Ubuntu Budgie 17.10 x64, VS Code 1.22.2, C/C++ extension 0.16.1. Installed only Code Runner (by Jun Han) as second extension and default user/workspace settings.

I created "time" class describing information about hour, minute, second in 3 files: CTimeSpan.h, CTimeSpan.cpp, main.cpp.
(Code obtained from http://home.kenhdaihoc.com/2012/03/xay-dung-lop-time-trong-c.html)

**CTimeSpan.h file:**
```
#include <iostream>
using namespace std;
#pragma once

class time
{
  private:
    int hour;
    int minute;
    int second;
    void incHour();
    void incMinute();

  public:
    void setTime(int, int = 0, int = 0);
    void setHour(int);
    void setMinute(int);
    void setSecond(int);
    void print12h();
    void print24h();
    void incSecond();
};
```
**CTimeSpan.cpp file:**
```
#include "CTimeSpan.h"

void time::incHour()
{
    hour++;
    if (hour == 24)
        hour = 0;
}

void time::incMinute()
{
    minute++;
    if (minute == 60)
    {
        minute = 0;
        incHour();
    }
}

void time::incSecond()
{
    second++;
    if (second == 60)
    {
        second = 0;
        incMinute();
    }
}
void time::setHour(int h)
{
    hour = (h >= 0 && h < 24) ? h : 0;
}

void time::setMinute(int m)
{
    minute = (m >= 0 && m < 60) ? m : 0;
}

void time::setSecond(int s)
{
    second = (s >= 0 && s < 60) ? s : 0;
}

void time::setTime(int h, int m, int s)
{
    setHour(h);
    setMinute(m);
    setSecond(s);
}

void time::print24h()
{
    cout << (hour < 10 ? "0" : "") << hour << ":" << (minute < 10 ? "0" : "") << minute << ":";
    cout << (second < 10 ? "0" : "") << second << endl;
}

void time::print12h()
{
    cout << (hour) << ":" << (minute < 10 ? "0" : "") << minute << ":";
    cout << (second < 10 ? "0" : "") << second << (hour < 12 ? " AM" : "PM") << endl;
}
```
**main.cpp file:**
```
#include "CTimeSpan.h"

int main()
{
  time a;
  a.setTime(23, 59, 58);
  a.print12h();
  a.print24h();
  for (int i = 0; i < 3; i++)
  {
    a.incSecond();
    a.print12h();
    a.print24h();
  }
  return 0;
}
```
Although my code is correct, I couldn't compile it because it gave me error:
![image](https://user-images.githubusercontent.com/29880544/39088941-e23a99f2-45e5-11e8-92c4-57ac01bbc576.png)
![image](https://user-images.githubusercontent.com/29880544/39088957-19fc85da-45e6-11e8-8da3-00aba33ac207.png)
Tried compiling this in other ways (online IDE, Visual Studio,...) but with no error!

**Comment by johnduffynh** [comment]
It is treating time as the c function time.  https://www.tutorialspoint.com/c_standard_library/c_function_time.htm

This extension isn't a compiler, bring compiler issues up to gcc, clang, visual studio.

**Comment by hoan-cosmos** [comment]
@johnduffynh I don't think this issue belongs to compiler or clang, because other IDE with the same gcc/clang worked flawlessly.

**Comment by sean-mcmanus** [comment]
Our extension doesn't handle actual compiling. The issue should repro with our C++ extension disabled. I assume the issue is with whatever task you're using to compile with.

**Comment by hoan-cosmos** [comment]
@sean-mcmanus What do you mean by "with whatever task you're using to compile with"? I compiled it by g++ commands (g++ -o, g++ -c) in VSCode integrated terminal.

**Comment by bobbrow** [comment]
Did you pass in `-std=c++1z` for C++?

**Comment by hoan-cosmos** [comment]
@bobbrow No sir.

**Comment by bobbrow** [comment]
Can you try adding that to your command line?

**Comment by bobbrow** [comment]
Please share your tasks.json file

**Comment by hoan-cosmos** [comment]
@bobbrow 
 1.When I didn't pass in -std=c++1z:
![image](https://user-images.githubusercontent.com/29880544/39379954-17ea61f4-4a87-11e8-9d4e-a917dc549dfb.png)
2.When I passed in -std=c++1z:
![image](https://user-images.githubusercontent.com/29880544/39380082-87fc547a-4a87-11e8-801e-f3c8d580ef06.png)
I only used bash commands on VSCode terminal, I didn't create tasks.json file.

**Comment by Hinara** [comment]
The surprise is that it does compile on others compilers.
Your use of `using namespace std;` make your time class conflict with the std::time class.
That's a normal behavior. Even if my question is why you don't get an error about potential class conflict.
One of my question is why do you include iostream in your .h? You don't use it.
And try to avoid `using namespace std;` even if it is practical, there are a lot of downsides

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.
