### ISSUE TITLE
How do I compile and run my C++ programs

### ISSUE THREAD

**Issue by SousaGoose** [microsoft/vscode-cpptools#1862]
Hello, I'm a freshman in high school and I'm currently taking a class on C++ programming. We have been using the old compiler, Borland. I'm very new to all of this and I was just wondering how to compile and run my programs. Also, can I compile console and/or GUI programs or just one of them? Thank you so much in advance! 
-Cooper

**Comment by sean-mcmanus** [comment]
Have you seen https://code.visualstudio.com/docs/languages/cpp#_building-your-code ? The details depends on your OS, compiler, and build tools. You can compile console or GUI programs, but you have to have the right GUI libraries. You may also want to try Visual Studio 2017 if you're on Windows (which has some GUI editors). I'm not familiar with using Borland compilers.
