### ISSUE TITLE
error when using "goto symbol in file".

### ISSUE THREAD

**Issue by suzukajiang** [microsoft/vscode-cpptools#1868]
there is something wrong when I use "goto symbol in file". It can't find the function in the file, but It find the MACRO called by the function.

list_for_each_entry  is a macro， just like:

#define list_for_each_entry(pos, head, member)				\
	for (pos = list_entry((head)->next, typeof(*pos), member),	\
		     prefetch(pos->member.next);			\
	     &pos->member != (head);					\
	     pos = list_entry(pos->member.next, typeof(*pos), member),	\
		     prefetch(pos->member.next))

![1](https://user-images.githubusercontent.com/34700091/39163610-e6ad2d50-47ad-11e8-8211-a19bae8cac94.PNG)
![2](https://user-images.githubusercontent.com/34700091/39163617-eb97de1e-47ad-11e8-98d2-99570a7d22bf.PNG)

**Comment by sean-mcmanus** [comment]
This is a "by design" limitation of our symbol parser. The macro representing the for each should be added to a cpp.hint file in your workspace root. See https://msdn.microsoft.com/en-us/library/dd997977.aspx .
