### ISSUE TITLE
.browse.VC.db

### ISSUE THREAD

**Issue by mimorisuzuko** [microsoft/vscode-cpptools#187]
I installed vscode-cpptools. So, vscode creates `.vscode/.browse.VC.db`. I understand its file is necessary for this extension. When I opened a Node.js project, however, its file is created. I would like to prevent it. Please, teach me.

**Comment by jgoshi** [comment]
Which version of cpptools are you using? If you update to the latest (version 0.9.0) this is fixed. Also note that if your Node.js project contains any cpp related files the browse database will be created. If after trying those things your problem still exists please reopen this issue.

**Comment by mimorisuzuko** [comment]
Its version is the latest and my project contains cpp files. So the browse database is created, namely cannot prevent it? ok, thank you to your reply.

**Comment by mimorisuzuko** [comment]
In the case of Node.js, any modules is in `node_modules`. So, it is possible that this extension ignores any cpp files in `node_modules`? If so, I can avoid this bug.

**Comment by joeskeen** [comment]
I agree with @mimorisuzuko. I frequently open node.js projects and the plugin always creates the files, even though there is a 0% chance that I will need to use any of the C++ tools in that project as the node_modules are upstream dependencies.  If there were a setting you could set in the settings.json that allowed you to ignore a folder, that would be awesome.

Something like this:

``` json
{
  "C_Cpp.ignore": "node_modules"
}
```

or

``` json
{
  "C_Cpp.ignore": ["node_modules"]
}
```

**Comment by sean-mcmanus** [comment]
0.9.2 won't create the .vscode/browse db, and the next release will do a lazy activation, so our extension won't load at all in node.js scenarios where it's not needed.
