### ISSUE TITLE
Debug using msvc140

### ISSUE THREAD

**Issue by olivierHen** [microsoft/vscode-cpptools#1870]
Hi Folks! 

I would like to know if it is possible to debug a project using the MSVC 2015 (v14) Compiler with this plugin. 

I tried to configure my project (which is build from a CMakeList using compiler MSVC 19.0.24210.0) , but VSCode throws an error "spawn UNKNOWN" and I don't know how to see the stack trace or to find any help on this topic... 

Have you got any tips or solution ? 

I hope that my question is clear and I'm still available to answer to any question. 

Thank you very much!

Olivier.

**Comment by WardenGnaw** [comment]
Can you share your launch.json and the output when you also add the following to your configuration?
```
"logging": {
   "engineLogging": true
}
```

**Comment by olivierHen** [comment]
Ok ! So here is my process :
1 - Launch code.exe from the MSVC 2015 Environment Command Prompt (64bits)
2 - I open my program folder (which just prints "Hello World")
3 - I Make it with my CMake (v3.11.1)
4 - I run it directly from the explorer : it works! 
5 - I create my launch.json ... but unfortunately, I have an UNKNOWN error ... 

Here is my launch.json : 
```
 {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/Debug/VSCodeTesterd.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "logging": {
                "engineLogging": true
            }
        }
    ]
}
```
I can add that my installation is fully offline, I have downloaded & installed all the package manually due to a tricky company proxy that I don't succeed to pass. 
So here is my package configuration : 
- plugin C/C++  (Microsoft) [installed from vsix]
- plugin C# (Microsoft) [installed from vsix]
- plugin CMake (twxs) [installed from vsix]
- .omnisharp [manually downloaded and installed in %userprofile%\.vscode\extensions\ms-vscode.cpptools-0.16.1]
- .debugger [manually downloaded and installed in %userprofile%\.vscode\extensions\ms-vscode.cpptools-0.16.1]

Moreover, the logging entry in the launch.json do not print anything ... as if the debugger crashes before launching something...

Am I missing something or do you want something else?

Thank you very much!

**Comment by WardenGnaw** [comment]
I tried to recreate your scenario and could not get it to break. 

From your information, it seems like the debugger is not launching. Can you see if you can run ```%USER%\.vscode\extension\ms-vscode.cpptools-<version>\debugAdapters\vsdbg\bin\vsdbg.exe```?

If it outputs something, it seems like VSCode is failing somewhere. If that does happen, have you tried reinstalling VSCode and/or the extension.

**Comment by WardenGnaw** [comment]
Closing issue. Please file a new ticket with more information if you are still encountering issues.
