### ISSUE TITLE
This extension couldn't start client cpptools and the server failed to launch server on macOS and Ubuntu 16.04

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode-cpptools#1874]
# Detalhes
* **Operating System and version:**  macOS High Sierra 10.13.4 64bits, Darwin Kernel 17.5.0 and XNU-4570.51.1~1/RELEASE_X86_64 x86_64, and Ubuntu Linux 16.04 64bits.
* VSCode Insiders 1.23.0
* **C/C++ extension version:** 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)
* **Extensions:**

```
DotJoshJohnson.xml
PKief.material-icon-theme
Tyriar.sort-lines
Zignd.html-css-class-completion
abusaidm.html-snippets
alexdima.copy-relative-path
anseki.vscode-color
austin.code-gnu-global
bajdzis.vscode-database
be5invis.vscode-custom-css
bradgashler.htmltagwrap
brapifra.phpserver
brunnerh.file-properties-viewer
castwide.solargraph
cstrap.python-snippets
dbaeumer.vscode-eslint
donjayamanne.jupyter
donjayamanne.python-extension-pack
dustinsanders.an-old-hope-theme-vscode
ecmel.vscode-html-css
eg2.tslint
eiminsasete.apacheconf-snippets
idleberg.emoji-code
felixfbecker.php-debug
felixfbecker.php-intellisense
felixfbecker.php-pack
formulahendry.auto-close-tag
formulahendry.code-runner
formulahendry.vscode-mysql
goessner.mdmath
heberalmeida.php-snippets
hwencc.html-tag-wrapper
jakebathman.mysql-syntax
jakeboone02.cypher-query-language
jakelucas.code-select-until
jerriepelser.copy-markdown-as-html
jithurjacob.nbpreviewer
jmredfern.sort-selection
jock.svg
junstyle.php-cs-fixer
kamikillerto.vscode-colorize
konstantin.wrapSelection
magicstack.MagicPython
mdickin.markdown-shortcuts
mitaki28.vscode-clang
mrmlnc.vscode-apache
mrmlnc.vscode-attrs-sorter
mrmlnc.vscode-duplicate
ms-python.python
ms-vscode.atom-keybindings
ms-vscode.cpptools
ms-vscode.csharp
naumovs.color-highlight
ohansemmanuel.css-grid-snippets
pranaygp.vscode-css-peek
rasmus.al-formatter
rebornix.Ruby
robinbentley.sass-indented
searKing.preview-vscode
sensourceinc.vscode-sql-beautify
yzhang.markdown-all-in-one
```
* With disabled extensions, the issue still insists. 
* Step-by-step instructions to reproduce the issue:
1. I installed C/C++ extensions before.
2. I created a new C++ file
3. I received the alert follwoing:

```
Starting client failed
Launching server using command /Users/gusbemacbe/.vscode-insiders/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.Extension.darwin failed.
```

```
Couldn't start client cpptools 
```
* It is a simple and small code. They are attached here.
[Archive.zip](https://github.com/Microsoft/vscode-cpptools/files/1943954/Archive.zip)

Just test `Análise_Léxico_de_Gustavo.cpp`, `lexicalanalyzer.cpp` and `teste.cpp`.

* `settings.json`:

```json
{
    "atomKeymap.promptV3Features": true,
    "auto-close-tag.SublimeText3Mode": true,
    "colorize.activate_variables_support_beta": true,
    "colorize.languages": [ "css", "html", "php", "svg"],
    "css.validate": false,
    "editor.autoIndent": false,
    "editor.colorDecorators": false,
    "editor.fontFamily": "Everson Mono Bold, Menlo, Monaco, Courier New, Aegean, monospace",
    "editor.fontLigatures": true,
    "editor.fontSize": 12,
    "editor.minimap.enabled": false,
    "editor.minimap.renderCharacters": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.quickSuggestions": 
    {
        "comments": true,
        "other": true,
        "strings": true
    },
    "editor.renderLineHighlight": "none",
    "editor.selectionHighlight": false,
    "editor.smoothScrolling": true,
    "editor.tabCompletion": true,
    "editor.tabSize": 2,
    "emmet.excludeLanguages": [""],
    "emmet.includeLanguages": { "vue-html": "html", "markdown": "html" },
    "emmet.showSuggestionsAsSnippets": true,
    "explorer.autoReveal": false,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "files.autoSave": "onFocusChange",
    "files.exclude": 
    {
        "**/.DS_Store": false
    },
    "git.autofetch": true,
    "git.confirmSync": true,
    "git.enableSmartCommit": true,
    "html-css-class-completion.enableEmmetSupport": true,
    "html.format.indentInnerHtml": true,
    "material-icon-theme.files.associations": 
    {
        "changelog.php": "changelog"
    },
    "material-icon-theme.folders.associations": 
    {
        "fontes": "font",
        "idiomas": "i18n",
        "imagens": "images",
        "javascript": "javascript",
        "language": "i18n",
        "teste": "test",
        "testes": "test"
    },
    "material-icon-theme.folders.color": "#E5CD52",
    "phpserver.browser": "firefox",
    "phpserver.port": 8200,
    "php-cs-fixer.formatHtml": true,
    "search.location": "panel",
    "terminal.integrated.fontFamily": "Everson Mono",
    "terminal.integrated.fontSize": 16,
    "workbench.activityBar.visible": true,
    "workbench.colorCustomizations": 
    {
        "activityBarBadge.background": "#E5CD52",
        "activityBar.border": "#E5CD52",
        "activityBar.foreground": "#A9B8BA",
        "scrollbarSlider.background": "#E5CD52",
        "scrollbarSlider.hoverBackground": "#4FB4D7"
    },
    "workbench.editor.enablePreview": false,
    "workbench.fontAliasing": "antialiased",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.startupEditor": "none",
    "window.zoomLevel": 0.001,
    "workbench.colorTheme": "An Old Hope"
}
```

**Comment by bobbrow** [comment]
Can you verify the binary exists at the path you listed and it has executable permissions?

`/Users/gusbemacbe/.vscode-insiders/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.Extension.darwin`

**Comment by gusbemacbe** [comment]
Finder told it doesn't exist. Only Linux. 

![List](https://user-images.githubusercontent.com/2257024/39223651-9f054dd6-4819-11e8-9be7-69de916ae8e8.png)

**Comment by bobbrow** [comment]
It looks like you might have installed the wrong VSIX file.  If you are downloading from the Releases page, make sure you get the correct VSIX.  For example: https://github.com/Microsoft/vscode-cpptools/releases/download/v0.16.1/cpptools-osx.vsix is the correct one for Mac.

**Comment by gusbemacbe** [comment]
Sorry for my absence. As the VSIX didn't work, I followed the guide of how to compile this repository, using npm, it worked. Can I back up this folder with both macOS and Linux's "VSIXs"? So I will make a clean install of my external HD to install Ubuntu 18.04 and copy this backup.

**Comment by bobbrow** [comment]
Did you try the osx VSIX I linked to?  The folders are pretty much plug and play, so if you copy the ms-vscode.cpptools-0.16.1 folder, you can copy it to any other computer with the same operating system and it will work.

If you are downloading VSIX files from our Releases page, please note that the linux VSIX will not work on Mac, and the Mac VSIX will not work on linux.  If you are downloading from the Extension Gallery (Marketplace), we will download the correct binaries for your operating system.

**Comment by gusbemacbe** [comment]
> Did you try the osx VSIX I linked to?

No, I tried to install VSIX, using `code --install` or `ext install`.

**Comment by bobbrow** [comment]
Did that command install the .linux binaries on your Mac?

**Comment by gusbemacbe** [comment]
Yes, the normal extension from VSCode Insiders installed .linux on macOS, but I have already removed the extension and made a clean install and installed, following the [guide](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Building%20the%20Extension.md) and compiling, then it downloaded .darwin and it worked. The problem is solved.

**Comment by bobbrow** [comment]
I'm trying to figure out if other Mac users might be having the same problem, so please excuse my follow up questions.  I would prefer that you be using the official VSIX from the extension marketplace rather than making you compile and run the extension yourself.

I just ran `code --install-extension ms-vscode.cpptools` on my MacBook and the correct binaries were downloaded.  Is this the exact command you tried?

**Comment by gusbemacbe** [comment]
Yes, but it installed .linux before.

Well, now I backed the folder up, removed the folder, and I have just tested with the same command, now it installed normally .darwin instead and it worked. Strange, before it used to install .linux and to fail to launch server.
