### ISSUE TITLE
cl.exe can't find main.cpp when running from wsl location

### ISSUE THREAD

**Issue by karlbenoit** [microsoft/vscode-cpptools#1876]
I just discovered that windows/wsl interoperability is now possible. That's awesome and I tought, maybe I could use wsl instead of cygwin!

So what I'm trying to achieve is to build a windows app using the MSVC toolchain with cmake. I don't actually want to do crosscompiling - i.e. I don't want to use mingw. I want to use wsl as an alternative to cygwin to compile a windows application.

(I read a little on the matter and I found out that there is currently a limitation that might partly explain the issue described below - https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/)

1. To have the proper environment loaded, launch the MSVC console.
```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.6.6
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>
```
2. From there, call `wsl.exe`.
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>wsl.exe
me@home:/mnt/c/Program Files (x86)/Microsoft Visual Studio/2017/Community$ cd ~/test
me@home:~/test/$ which cl.exe link.exe rc.exe
/mnt/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x86/cl.exe
/mnt/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x86/link.exe
/mnt/c/Program Files (x86)/Windows Kits/10/bin/10.0.16299.0/x64/rc.exe
```

3. Generate the cmake files using the following command from a build directory:
```
mkdir -p build && cd build
cmake -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake ..
```

When I run cmake I get the following error:
```
-- The CXX compiler identification is unknown
-- Check for working CXX compiler: /mnt/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: /mnt/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCXXCompiler.cmake:54 (message):
  The C++ compiler "/mnt/c/Program Files (x86)/Microsoft Visual
  Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe" is
  not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /home/karl/test/build/CMakeFiles/CMakeTmp
...
```
4. This is what happens when I try to compile `main.cpp` without cmake:

```
me@home:~/test$ ls -la
total 1
drwxrwxrwx 0 karl karl 512 Apr 22 10:15 .
drwxr-xr-x 0 karl karl 512 Apr 22 10:16 ..
-rw-rw-rw- 1 karl karl  48 Apr 22 09:28 CMakeLists.txt
-rw-rw-rw- 1 karl karl  47 Apr 22 09:17 main.cpp
-rw-rw-rw- 1 karl karl 532 Apr 22 09:38 toolchain.cmake
me@home:~/test$ cl.exe main.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26131.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
c1xx: fatal error C1083: Cannot open source file: 'main.cpp': No such file or directory
```

Windows Build Number: Microsoft Windows [Version 10.0.16299.371]

[test.tar.gz](https://github.com/Microsoft/vscode-cpptools/files/1945181/test.tar.gz)

This issue was also filed in the WSL github: https://github.com/Microsoft/WSL/issues/3118

**Comment by bobbrow** [comment]
For reference, `notepad.exe main.cpp` doesn't work in this environment either.

From [the documentation](https://docs.microsoft.com/en-us/windows/wsl/interop):
"Modifying files located on VolFs (files not under /mnt/<x>) with a Windows application in WSL is not supported."

I am able to run `cl.exe C:\test\main.cpp` and have it find the file.  I'm no expert on WSL, but based on some quick testing, it seems like you need to use absolute paths to Windows files in order for Windows executables to be able to find them.  And to reiterate the warning in the blog post you linked to, I would not recommend storing files you plan to compile with a Windows compiler under your WSL home directory.

**Comment by bobbrow** [comment]
EDIT: did a little more testing, and it appears you can use relative paths in Windows executables if your pwd in the wsl shell is in the correct folder (under /mnt/ only). (e.g. pwd = /mnt/c/test, then `cl.exe test.cpp` works)

**Comment by karlbenoit** [comment]
This works under `/mnt/d/test` for me as well. 

My mistake was to also use wsl's cmake. When using cmake for windows, the project is compiling.

I'm closing this issue.
