### ISSUE TITLE
compileCommands does not understand MSYS paths.

### ISSUE THREAD

**Issue by Kwizatz** [microsoft/vscode-cpptools#1878]
After configuring vscode to use MSYS2 and setting CMake to export the compile commands json file, I kept getting the "Configure includePath for better IntelliSense results" error but my includePath does include the path where the error was seen.

Looking at the compile commands file, I see that all absolute paths are being given in "MSYS2 style", that is instead of C:/folder/folder/file.cpp you see /c/folder/folder/file.cpp, doing a quick find and replace, the include path error is now gone. Is there a way to configure how to follow MSYS2 or Cygwin paths? (cygwin would likely get the same issue but with /cygdrive/c instead)

How to reproduce:

Configure a CMake project inside the MSYS terminal using -G "MSYS Makefiles" -D CMAKE_EXPORT_COMPILE_COMMANDS=1, build the project so compile_commands.json gets created,
Open the folder in vs code and set compileCommands to the location of the json file.
See the include location errors pop up.

**Comment by Colengms** [comment]
Hi @Kwizatz .  Are you still seeing this issue?  I'm not able to easily repro with the latest versions of packages (mingw_w64, cmake) in MSYS2.  Though, I'm seeing other issues - specifically that MSYS2's CMake is failing to configure the latest version of mingw_w64.  Do you have an example project you can share that I should be able successfully configure with the latest MSYS2 packages installed, using the MSYS2 build of CMake?

As VS Code is not running under MSYS2, it would seem to be expected that alternative path formats used by 3rd party shells would not be supported.  However, I think you'll find that the latest version of MinGW (10.2.0) that is installed with MSYS2 can be configured using the Windows build of CMake, and should generate a `compile_commands.json` that works as expected.

**Comment by Kwizatz** [comment]
Hi @Colengms ,
Last time (back in August) it got so annoying that I wrote these (cmake):

```
function(fix_compile_commands target)
  if(SED_EXECUTABLE)
  add_custom_command(TARGET ${target} POST_BUILD
      COMMAND ${SED_EXECUTABLE} -i 's/\\/\\\(.\\\)\\//\\1:\\//g' ${CMAKE_BINARY_DIR}/compile_commands.json
      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
      COMMENT "Fixing compilation Database."
  )
  endif()
endfunction()
if(SED_EXECUTABLE)
  add_custom_target(fix_compile_commands ALL
      COMMAND ${SED_EXECUTABLE} -i 's/\\/\\\(.\\\)\\//\\1:\\//g' ${CMAKE_BINARY_DIR}/compile_commands.json
      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
      COMMENT "Fixing compilation Database."
  )
endif()
```
Disabling those, yes I still see the wrong paths:
```
{
  "directory": "C:/Code/AeonGUI/mingw64/core",
  "command": "/C/msys64/mingw64/bin/g++.exe -DAeonGUI_EXPORTS -D_USE_MATH_DEFINES -I/C/msys64/mingw64/include/freetype2 -I/C/msys64/mingw64/include/libxml2 -I/C/Code/AeonGUI/include -I/C/Code/AeonGUI/common -I/C/Code/AeonGUI/demos/common -I/C/Code/AeonGUI/core -I/C/msys64/mingw64/include/cairo -I/C/msys64/mingw64/include/pixman-1 -I/C/msys64/mingw64/include/harfbuzz -I/C/msys64/mingw64/include/glib-2.0 -I/C/msys64/mingw64/lib/glib-2.0/include -I/C/msys64/mingw64/include/libpng16  -Wfatal-errors -Wall  -Wfatal-errors -Wall -DDEBUG -g -O0 -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS -DV8_COMPRESS_POINTERS -DV8_31BIT_SMIS_ON_64BIT_ARCH -std=c++2a -Winvalid-pch -x c++-header -include C:/Code/AeonGUI/mingw64/core/CMakeFiles/AeonGUI.dir/cmake_pch.hxx -o CMakeFiles/AeonGUI.dir/cmake_pch.hxx.gch -c /C/Code/AeonGUI/mingw64/core/CMakeFiles/AeonGUI.dir/cmake_pch.hxx.cxx",
  "file": "C:/Code/AeonGUI/mingw64/core/CMakeFiles/AeonGUI.dir/cmake_pch.hxx.cxx"
},
```

And again, I see squiggly lines on local includes.

I don't have a minimal example project, but I am not doing anything particularly weird, I am using the cmake that gets installed with MSYS2 Mingw-w64:

```
$ pacman -Qs cmake
local/mingw-w64-x86_64-cmake 3.18.4-1
    A cross-platform open-source make system (mingw-w64)
```

The only suspect thing might be that I am using the "MSYS Makefiles" generator as shown in the OP.

This is the project I am seeing this on: [AeonGUI](https://github.com/AeonGames/AeonGUI)

**Comment by Kwizatz** [comment]
MSYS2 provides cygpath a cygwin utility to translate paths, maybe you could add some sort of trap or callback for paths and a setting variable for the path to cygpath and run all paths through the utility if set on the settings.json file, do nothing if it doesn't exist?
