### ISSUE TITLE
IncludePath problem on Mac

### ISSUE THREAD

**Issue by gglang** [microsoft/vscode-cpptools#1880]
I am running macOS 10.13.4, and working in Unreal Engine 4.19.1

I get the following error:
"cannot open source file "../include/utility" (dependency of CoreMinimal.h")

I have tried adding all sorts of paths to the includePath and browse.path based on 'utility' files associated with my Unreal project. No success.

**Comment by sean-mcmanus** [comment]
I'm not sure if this is a bug or not, but we'll try to investigate the repro after we're done with 0.17.0.

UPDATE: Sorry...we haven't investigated yet....could be related to https://github.com/Microsoft/vscode-cpptools/issues/1684 .

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
