### ISSUE TITLE
include complete path

### ISSUE THREAD

**Issue by BigfootN** [microsoft/vscode-cpptools#1883]
Hello,

I would like to know if this extension is capable of completing include paths. I prefer to use the `compileCommands` properties. Here is my config (I am under linux):

``` json
{
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}/include",
                "/usr/include/c++/7.3.1",
                "/usr/include/c++/7.3.1/x86_64-pc-linux-gnu",
                "/usr/include/c++/7.3.1/backward",
                "/usr/local/include",
                "/usr/lib/clang/6.0.0/include",
                "/usr/include"
            ],
            "defines": [],
            "compileCommands": "${workspaceFolder}/compile_commands.json",
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}/include",
                    "/usr/include/c++/7.3.1",
                    "/usr/include/c++/7.3.1/x86_64-pc-linux-gnu",
                    "/usr/include/c++/7.3.1/backward",
                    "/usr/local/include",
                    "/usr/lib/clang/6.0.0/include",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
```

If this extension doesn't support that kind of feature, could you please tell me if there is another way of having that ?

Thank you very much in advance.

P.S: Other than that everything seems to be working fine.

**Comment by bobbrow** [comment]
If you use `compileCommands`, the extension ignores `includePath` for the files in the compile_commands.json database.  Are some of the includes still missing for the files you opened?  If so, can you share an entry from the compile_commands.json that illustrates the problem?  It's possible that the include paths are indirectly specified so we don't see them.

**Comment by BigfootN** [comment]
Hello,

Thank you very much for your answer. Here is an entry from my `compile_commands.json`:

```json
{
  "directory": "/home/bigfoot/Documents/ETNA/GPE/local/build/release/lib/Database",
  "command": "/usr/bin/c++  -Ddatabase_EXPORTS -I/home/bigfoot/Documents/ETNA/GPE/local/include  -Wall -Werror -Wextra -g -fPIC   -std=gnu++14 -o CMakeFiles/database.dir/Database.cpp.o -c /home/bigfoot/Documents/ETNA/GPE/local/lib/Database/Database.cpp",
  "file": "/home/bigfoot/Documents/ETNA/GPE/local/lib/Database/Database.cpp"
}
```

Thank you very much in advance.

P.S: I also seemed to notice that the linter doesn't seem to work correctly.  It shows errors, but not warnings. The flags (ex. -Wall -Werror -Wextra) don't seem to be taken into account.

**Comment by bobbrow** [comment]
That's correct, we don't show warnings right now.  We might add a setting to enable them in the future.

We should be able to parse compile_commands.json that looks like your example.  Which include path is missing?  You should also change the `compilerPath` in c_cpp_properties.json to `/usr/bin/c++` to match and you can remove system includes from `includePath`.  (In 0.17.0 (pre-release) you can remove system includes from browse.path as well)

**Comment by BigfootN** [comment]
Sorry for the late response.

I managed to solve the problem. Thank you very much. I used the `browse.path` and `includePath` from the `c_cpp_properties.json`.

Thank you very much for your help.
