### ISSUE TITLE
Can't collapse a C++ class with a single click

### ISSUE THREAD

**Issue by ftrofin** [microsoft/vscode-cpptools#1884]
macOS 10.12.6
Version Studion Code Version 1.22.2
ms-vscode.cpptools 0.16.1

I would like to collapse the declaration of a whole class with a single click but I can't. I have to click the '-'  in the left gutter to collapse every section in the classs: public, protected, private so it's a bit onerous. It would be much nicer to have a '-' sign on the line with the class keyword and collapse the whole class at once.

Thanks!

Florin

**Comment by sean-mcmanus** [comment]
We're tracking this with https://github.com/Microsoft/vscode-cpptools/issues/407 .
