### ISSUE TITLE
How to reduce verbosity of cppvsdbg output

### ISSUE THREAD

**Issue by zomgrolf** [microsoft/vscode-cpptools#1887]
This is happening in VSCode 1.22.2, cpptools version 0.16.1, running on Windows 10 x64 Home, v.1709.

For some reason, whenever I attempt to debug a C++ program, the debugger insists on showing loader snaps in the debug console, even though gflags.exe shows the relevant flag as unchecked (and a cursory glance at the "Image File Execution Options" key in the registry hasn't revealed anything out of ordinary either).

Is there a way to suppress this behaviour? This is way too much information for regular use -- unless I'm trying to diagnose loading failures, just the basic information about loaded DLLs is usually sufficient.

For reference, here's my launch.json file:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/${fileBasenameNoExtension}/Debug/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true
        }
    ]
}
```

**Comment by WardenGnaw** [comment]
You can disable module loads by adding the following to your launch.json:
```
"logging": {
   "moduleLoad": false
}
```

**Comment by zomgrolf** [comment]
Thanks,
As it turned out, it WAS caused by something forcing the system-wide Global Flags to show loader snaps. Clearing the flag and restarting the machine made the problem go away. As I don't think this extension was responsible for this, I consider this issue closed.

Thanks again for looking into this.
