### ISSUE TITLE
lldb type is not recognized with LLDB, CodeLLDB and Native Debug

### ISSUE THREAD

**Issue by jamesray1** [microsoft/vscode-cpptools#1888]
The lldb type is not recognized in launch.json.

OS: Ubuntu 17.10
I installed LLDB, and in VS Code I have these extensions installed and enabled:
- Rust (rls)
- Rusty Code
- Rust by kalitaalexey
- Native Debug
- CodeLLDB
- D Language utility extension pack

The lldb type is not recognized with just Native Debug enabled and installed, with both CodeLLDB and Native Debug and with just CodeLLDB.

What needs to happen to fix this?

Note that the gdb and lldb-mi types do work with Native Debug, but lldbi-mi doesn't support the args field.

![screenshot from 2018-04-27 11-18-07](https://user-images.githubusercontent.com/16969914/39339553-bbf42878-4a0c-11e8-9bdf-f00adbf17e28.png)

**Comment by WardenGnaw** [comment]
Could you provide more information on what you mean by lldb type? 

If it is for configuration type, the vscode-cpptools extension supports ```cppvsdbg``` and ```cppdbg```. ```cppdbg``` supports working with lldb with the ```MIMode``` field set to ```lldb``` in the launch configuration.

We do not own CodeLLDB or Native Debug.
