### ISSUE TITLE
New variable ${userProfile} pointing to the home directory of the current user

### ISSUE THREAD

**Issue by AndiSHFR** [microsoft/vscode-cpptools#1891]
Would it be possible to add a new [variable](https://code.visualstudio.com/docs/editor/variables-reference) `${userProfile}` pointing to the current users home/profile directory?

This would enable relative include paths like:

`${userProfile}/.node-gyp/8.9.1/include/node/*`

## TL;DR

I'm creating a native [Node.js](http://nodejs.org/) addon with vscode. I installed Microsoft [vscode-cpptools](https://github.com/Microsoft/vscode-cpptools) for intellisense.

[node-gyp](https://github.com/nodejs/node-gyp), which is required to build native Node.js addons, is placing header files of Node.js in a directory in the users profile folder.

To make intellisense work with node headers i have to add the directory

`C:/Users/ASC/.node-gyp/8.9.1/include/node/*`

to the __includePath__ variable of the __c_cpp_properties.json__.

As you can see it is an absolute path pointing to _my_ profile folder. 

Example snippet of `./.vscode/c_cpp_properties.json`:
```json
...
     "name": "Win32",
        "includePath": [
            "${workspaceFolder}",
            "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
            "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/*",
            "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/um",
            "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/ucrt",
            "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/shared",
            "C:/Program Files (x86)/Windows Kits/10/Include/10.0.15063.0/winrt",
            "C:/Users/ASC/.node-gyp/8.9.1/include/node/*"
        ],
...
```

It would be much more flexible if a variable like `${userProfile}` would enable this folder to be relative to the current user. So the additional line would look like:

`${userProfile}/.node-gyp/8.9.1/include/node/*`

Then it automatically would work for every user.

This is especially true because the file `c_cpp_propoerties.json` is placed in the `.vscode` directory below the current opened working directory. So this setting is related to the opened folder and not the current user.

__Note__: I already tried to use the environment variable `%USERPROFILE%` like 

`%USERPROFILE%/.node-gyp/8.9.1/include/node/*`

but this did not work.

**Comment by bobbrow** [comment]
Did you try `${userprofile}`?  It should already work.  We support environment variables in **c_cpp_properties.json** with either `${userprofile}, ${env:userprofile}, or ${env.userprofile}` syntax.

Please let us know if it does not work.
