### ISSUE TITLE
Data structure variable viewing

### ISSUE THREAD

**Issue by dahodge** [microsoft/vscode-cpptools#190]
The primary reason I wanted to use this was the ability to hover view variables at a breakpoint, but this doesn't work at all for structures like vectors or maps. Am I doing something wrong, or is this just not implemented? I can only see the first object in a vector if I dig through to find _M_start, and it is cluttered with things like _M_impl, std::_Vector_base, _M_end_of_storage, and other information that just contain addresses and aren't helpful. Is there a way to abstract away all this overhead info? This in no way eliminates the need for cout statements, it is completely unusable to me.

For example in this screenshot, I have 3 ints in my vector, yet I only see the first value along with a bunch of addresses and other stuff.

![vs_code_vars](https://cloud.githubusercontent.com/assets/6467191/18132059/29dcb584-6f63-11e6-9e6e-cce394d69269.PNG)

**Comment by paulmaybee** [comment]
Try turning on python pretty printing. In the debug console window enter "-exec -enable-pretty-printing".

**Comment by dahodge** [comment]
I tried this and it seemed to work (it printed result-class: done) but I am not seeing anything different. I checked the Variables tab, the variable hover, and printing the vector name in the debug console, but they all looked exactly as they do in my screenshot above.

**Comment by paulmaybee** [comment]
What OS and version of gcc are you using?

**Comment by dahodge** [comment]
Windows 7. I am using a MinGW package that contains gcc 6.1.0. I am using g++ for my launch task, not sure if this makes a difference (I'm pretty new to Windows developing).

**Comment by delmyers** [comment]
@dahodge, vscode now works using the visual c++ compiler for Windows. Have you tried using that instead?

**Comment by paulmaybee** [comment]
Looks like python scripting (and therefore pretty-printing) is not enabled in the mingw distributed version of gdb.

**Comment by dahodge** [comment]
@delmyers, 
To do that, do I just change the "command": "C:/MinGW/bin/g++" line in tasks.json to something else (and if so, what) ? I have not found any sort of guide that is remotely helpful in setting up a compiler other than the VS Code Docs page, which doesn't mention visual c++. Does that have something to do with clang? I've tried looking up both but don't really understand very well what they are, or how to use them at all.

**Comment by delmyers** [comment]
@dahodge,
You can install the Microsoft SDKs for creating Windows applications from here:
https://msdn.microsoft.com/en-us/microsoft-sdks-msdn.aspx

I think you can install the Windows 10 SDK even on your Windows 7 machine, you just have to make sure that you have all of your updates. After installing the SDK, you can compile your software using the command line. And, yes, you will have to change the compile command in your tasks.json, and that should do it.

Unfortunately, we depend on the underlying debugger engine (gdb in this case) to give the view of the variables. If "pretty printing" does not work on your version of gdb, that means that it is not implemented correctly there. We have a work item on our backlog to break this dependency, though.

**Comment by jhasse** [comment]
@dahodge Try gdb installed via MSYS2. It works with pretty printing.

> We have a work item on our backlog to break this dependency, though.

This would mean code duplication though, wouldn't it? Is there an issue here for this work item?

**Comment by pieandcakes** [comment]
@jhasse @dahodge In version `0.9.3` and above we have included the `enable-pretty-printing` command by default. If gdb has the necessary pretty-printers installed, it will display those types in a better format. You can also look at creating your own .natvis files as that is also supported using `"visualizerFile"` from within the `launch.json`.
