### ISSUE TITLE
"use of undeclared identifier nullptr" everywhere 'nullptr' is used

### ISSUE THREAD

**Issue by siniarskimar** [microsoft/vscode-cpptools#1900]
Windows 7 SP1
VSCode 1.22.1
vscode-cpptools 0.16.1

**Other extensions:** "C/C++ Clang Command Adapter", "C++ Intellisense"; issue persist after disabling those extensions

**How to reproduce:**

1. Create pointer
2. Assign or check if created pointer is equal to 'nullptr'

**Other information:**

* This issue happens everythime i use keyword 'nullptr'
* Intellisense standard is set to cpp17
* Keyword is being highlighted

**Extension's logs:**
> IntelliSense Engine = Default.
> The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
> Autocomplete is enabled.
> Error squiggles are enabled.
> File exclude: **/.git
> File exclude: **/.svn
> File exclude: **/.hg
> File exclude: **/CVS
> File exclude: **/.DS_Store
> File exclude: **/.vscode
> Search exclude: **/node_modules
> Search exclude: **/bower_components
> Search exclude: **/.vscode
> Code browsing service initialized
>   Folder: D:/DEV/CPP/SDL2TEST/ will be indexed
>   Folder: D:/MSYS64/MINGW64/INCLUDE/ will be indexed
>   Folder: D:/MSYS64/MINGW64/LIB/GCC/X86_64-W64-MINGW32/7.3.0/INCLUDE/ will be indexed
>   Folder: D:/MSYS64/MINGW64/LIB/GCC/X86_64-W64-MINGW32/7.3.0/INCLUDE-FIXED/ will be indexed
>   Folder: D:/MSYS64/MINGW64/X86_64-W64-MINGW32/INCLUDE/ will be indexed
> Discovering files...
>   Processing folder (recursive): D:/DEV/CPP/SDL2TEST/
>   Processing folder (recursive): D:/MSYS64/MINGW64/INCLUDE/
> Checking for syntax errors: file:///d%3A/dev/CPP/SDL2Test/src/Core.cpp
>   Processing folder (recursive): D:/MSYS64/MINGW64/LIB/GCC/X86_64-W64-MINGW32/7.3.0/INCLUDE/
>   Processing folder (recursive): D:/MSYS64/MINGW64/LIB/GCC/X86_64-W64-MINGW32/7.3.0/INCLUDE-FIXED/
>   Processing folder (recursive): D:/MSYS64/MINGW64/X86_64-W64-MINGW32/INCLUDE/
>   Discovering files: 11163 file(s) processed
>   0 file(s) removed from database
> Done discovering files.
> Parsing open files...
> Parsing remaining files...
>   Parsing: 0 files(s) processed
> Done parsing remaining files.
> Done parsing open files.
> Checking for syntax errors: file:///d%3A/dev/CPP/SDL2Test/src/Core.cpp
> Checking for syntax errors: file:///d%3A/dev/CPP/SDL2Test/src/Core.cpp

**Comment by sean-mcmanus** [comment]
The message "use of undeclared identifier" doesn't come from our extension. It must be from another extension or the message must be different. Also, our extension doesn't accept a cppStandard version of "cpp17" -- we use "c++17" instead. Also, it's recommended that you set your compilerPath to your mingw compiler and set the IntelliSenseMode to clang-x64. Usage of the latest 0.17.0-insiders build is also recommended: https://github.com/Microsoft/vscode-cpptools/releases .

**Comment by siniarskimar** [comment]
cppStandard was my misspell it's 'c++17' 
Checked extensions again and yes that issue is coming from other extension,  "C/C++ Clang Command Adapter". It seems like i missed it earlier
