### ISSUE TITLE
C #ifdef sections are not understood by intellisense

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode-cpptools#1901]
* Operating System and version:
Microsoft Windows [Version 10.0.16299.371]

* VS Code version and if you are using the Insiders build
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

* C/C++ extension version:
 0.17.0-insiders

* Other extensions you installed and if the issue persists after disabling them
* step-by-step instructions to reproduce the issue
1. create the project files
2. ctrl+click my_func() from app.c
3. nothing happens (no definition found)
4. additionally, ctrl+click func2, result is as expected, jump to function definition

* A small code sample, zipped up project, or open source repo we can use to verify the bug
[jump_bug.repo.zip](https://github.com/Microsoft/vscode-cpptools/files/1960959/jump_bug.repo.zip) 

* Relevant settings from your settings.json, c_cpp_properties.json, and/or launch.json files
* Any log messages present in the Output window (use "C_Cpp.loggingLevel": "Information" in settings.json)

**Comment by bobbrow** [comment]
The code browsing service doesn't currently handle preprocessor directives at all, so it doesn't see a complete function here and discards it.  This is currently the expected behavior, but we are tracking an issue to improve the symbol indexing. Your issue would be covered by #255.
