### ISSUE TITLE
lldb custom formatters are not working in VS Code

### ISSUE THREAD

**Issue by ftrofin** [microsoft/vscode-cpptools#1902]
OS: macOS Sierra (10.12.6)
Visual Studio Code Version 1.22.2
ms-vscode.cpptools 0.16.1

I'm using VS Code on a large c++ code base as a replacement for Xcode and it's working pretty well. The biggest problems I have are related to debugging (see my comments in #1768). Mainly, my app uses `basic_string<unsigned char>` for UTF8 and `basic_string<uint16_t>` for UTF16 and I can't see the contents of my strings. I had a custom formatter defined in ~/.lldbinit and ~/lldbsummaries.py but it doesn't seem to be picked up by the custom lldb used by the extension (worked in Xcode). Is this a known bug or a local problem with my setup?

Thanks!

F.

**Comment by WardenGnaw** [comment]
I saw your comment in the other thread, but I'll be replying here. 

In your launch.json, does adding the following to the configuration work?
```
"setupCommands": [
   {
      "description": "Load .lldbinit",
      "text": "command source <full-path-to-.lldbinit>"
   }
]
```

I got my simple .lldbinit which registers a new command to be loaded this way.

**Comment by ftrofin** [comment]
Thank you for confirming that! I was able to get my formatters loaded using your instructions. Two interesting notes:
1. You don't need the full path: `~/.lldbinit` worked just fine.
2. To verify that your formatters were loaded correctly by lldb, set a breakpoint and when you stop type this command at the lldb prompt in VS Code Debug Console: `-exec type summary list -w default`. This will list all known formatters.
Thanks Andrew!
