### ISSUE TITLE
"Property processName is not allowed." in launch.json

### ISSUE THREAD

**Issue by hsandt** [microsoft/vscode-cpptools#1904]
I am quickly copying this issue from https://github.com/Microsoft/vscode/issues/48844 so it is formatted according to VS code's own issue rules and not vscode-cpptools. That said, the information provided here should be enough to solve the issue.

---
    VSCode Version: 1.22.2
    OS Version: Windows 10

The `config.json` parser does not recognize the new `processName` parameter, only the `processId` one. Therefore, if you put `processName` but not `processId`, you'll get 2 warnings in the issues list:

    Missing property "processId"
    Property processName is not allowed.

Steps to Reproduce:

    Create a `launch.json` configuration with this:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processName": "my_program.exe"
        }
    ]
}
```

    Open the Issues panel or go to next error (F8) to see the 2 errors mentioned at the beginning.
---

In addition, processName is not yet mentioned in `launch.md`.

**Comment by WardenGnaw** [comment]
@hsandt We do not support ```processName``` in our schema, we have ```program```. 
Where does the parameter ```processName``` come from?
