### ISSUE TITLE
Include error squiggly colors

### ISSUE THREAD

**Issue by stavae** [microsoft/vscode-cpptools#1906]
Hi,

As far as I can tell there is currently no visual difference in the two errors in the attached image (might have to do with the fact that I am colorblind). While there is a difference in the error message that gets reported when hovering over the squiggly lines.

NonExistingFile.h reports: `cannot open source file "NonExistingFile.h"`
While BrokenFile.h reports: `#include errors detected. Please update your includePath. IntelliSense features for this translation unit (<path>\Example.h) will be provided by the Tag Parser.
cannot open source file "NonExistingFile.h" (dependency of "BrokenFile.h")` 

Would it be possible to have these two errors be visually distinct? E.g. have the squigly line under BrokenFile.h be blue or something (or allow them to be customized).

# Example
![image](https://user-images.githubusercontent.com/9059852/39476846-bcbfee82-4d5d-11e8-9f79-ad57f0c2ab3c.png)

```
// Example.h
#pragma once

#include "ExistingFile.h"
#include "NonExistingFile.h"
#include "BrokenFile.h"
```
```
// ExistingFile.h
#pragma once
```
```
// BrokenFile.h
#pragma once

#include "NonExistingFile.h"
```
```
// NonExistingFile.h doesnt exist
```

# Version info
OS: Win7 Enterprise
VSC: 
```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
Installed plugins:
```
C/C++ 0.16.1
Indenticator 0.5.1
msbuild Tools 0.0.8
TODO Highlights 0.5.12
```

**Comment by bobbrow** [comment]
You can change the default colors for the squiggly lines using VS Code's [color customization settings](https://code.visualstudio.com/docs/getstarted/theme-color-reference) (look for `editorWarning.foreground`).  However, we would need to change the classification of the two messages since they are both currently "warnings" right now which means they will still be the same color until we reclassify them.  I think VS Code recently added the "hint" category, so maybe I'll switch it to that.

**Comment by sean-mcmanus** [comment]
@bobbrow All the "cannot open" messages are classified as "Information" when the fallback is enabled. Is this still an issue?

**Comment by bobbrow** [comment]
Yes.  This issue is about distinguishing the "hint" message (update your includePath) with the "information/warning" message (cannot open source file).

**Comment by sean-mcmanus** [comment]
Hint severities aren't being shown -- we may need to update the language server protocol we're dependent on, i.e. not work fixing right now.

**Comment by bobbrow** [comment]
We disabled this fallback scenario, so all squiggles are red now.
