### ISSUE TITLE
Header files not being found by compiler!!!

### ISSUE THREAD

**Issue by adamfilli** [microsoft/vscode-cpptools#1909]
When my header files are directly in the workspace root, everything compiles properly. However, when I move them to a sub folder called "include" and when I add this path to my "c_cpp_properties.json" file, the header files are not being found by the compiler. Not sure why.  Any help would be greatly appreciated:

The following photo shows my configuration, the location of the include files, as well as the error generated. I can provide additional information if necessary. Please remember that everything compiles properly if I simply move the .h files to the workspace root. 

![image](https://user-images.githubusercontent.com/33565735/39486998-e879e44a-4d4b-11e8-90d9-4f16d399e59a.png)

**Comment by sean-mcmanus** [comment]
That error is not from our tool. You need to add the path to the command line passed to your compiler (i.e. via parameters in your task or whatever build system you're using). The paths in c_cpp_properties.json don't get sent to your compiler, just our IntelliSense compiler for error squiggles, etc. running in the Microsoft.VSCode.CPP.IntelliSense.Msvc process.
