### ISSUE TITLE
Random stuck icons -- stuff still works though

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1917]
Not sure of a repro yet and it seems like it should be impossible from the code. Closing/opening files doesn't get rid of the flame. The IntelliSense process all exit and work normally. Let me know if anyone else hits this (make sure no Microsoft.VSCode.CPP.IntelliSense.Msvc processes are running, i.e. no files open, when the red flame is stuck though and that error squiggles, etc. still work when it is running, because otherwise it's a different issue).

![image](https://user-images.githubusercontent.com/19859882/39543316-a8f927b8-4dff-11e8-808a-a38fa67f72b5.png)

**Comment by sean-mcmanus** [comment]
I hit this again with 0.17.0. Microsoft.VsCode.CPP.IntelliSense.Msvc.exe was dangling after the file was closed.

**Comment by sean-mcmanus** [comment]
There's another bug with the database icon getting stuck with "Parsing open files" (it can repro all the time if you don't have ${workspaceFolder} in your browse.path...it might repro more often for smaller workspaces too).

**Comment by sean-mcmanus** [comment]
The stuck database icon got fixed. The stuck red flame might still exist...not sure yet. I'll create a new bug if I see it again.

**Comment by tristan957** [comment]
I have experienced this in past releases. I'll let you know if I run into it this release
