### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by billchenxi** [microsoft/vscode-cpptools#192]
Hi CPP team,
thank you so much for your effort. I have issue with the tools, I already installed everything you guys asked, and I still cannot configure out the right json files. Can you tell me what I need to do to make the debugger run in the Code?

What I did is I just create a .cpp file, then I click the debugger icon, but it keeps asking me to configure the launch.json. I have no idea how to do it. Normally I just g++ the file and then ./ the out file, so what I need to do with the visual studio code? 

The error is: launch: program 'enter program name, for example /Users/bill....

What I need to replace the workspaceRoot? 

my file located here : 

```
Xis-MacBook-Pro:CPP bill$ ls
Hello       Hello.cpp   foo.h
Xis-MacBook-Pro:CPP bill$ pwd
/Users/bill/Documents/Course/pluralsight/CPP

```

Thank you so much, here is the json file.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "enter program name, for example ${workspaceRoot}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "gdb"
            },
            "windows": {
                "MIMode": "gdb"
            }
        },
        {
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "enter program name, for example ${workspaceRoot}/a.out",
            "processId": "${command.pickProcess}",
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb"
            }
        }
    ]
}
```

**Comment by delmyers** [comment]
Hi @billchenxi,

VsCode does not automatically build your project in the way that Visual Studio does. It is designed as a light-weight editor with some debugging features. It isn't a full IDE.

You will have to either compile your code using the command-line, or you can set up a tasks.json to do the compilation step for you. An example is in our documentation: 

http://code.visualstudio.com/docs/languages/cpp

After that, you can set up the "program" component to be the output of your compilation. For example ${workspaceRoot}/a.out

**Comment by heyAyushh** [comment]
I am getting Same error even after correcting what you said..

<img width="1440" alt="screen shot 2017-10-21 at 02 49 06" src="https://user-images.githubusercontent.com/17379963/31842224-a76d9434-b60a-11e7-8aa9-1407859797d5.png">

**Comment by sean-mcmanus** [comment]
@heyAyushh You need to enter the name of the binary that you compiled in the string that has "enter program name".

**Comment by gurjeet8197** [comment]
yo

**Comment by ats1999** [comment]
I have the same issue, but i am using it on windows.
