### ISSUE TITLE
[C++ on windows][vsdbg] Expression keep executing when click the button(+) of 'add expression' in top of watch window.

### ISSUE THREAD

**Issue by ClaireKang** [microsoft/vscode-cpptools#1927]
VSCode Version:1.22.2
OS Version: Window7 X64
Cpptools: \scratch2\scratch\waan\vsdbg-cpptools-test

Steps to Reproduce:
1. Open tests folder in attachments directly.
[ConsoleApplication1.zip](https://github.com/Microsoft/vscode-cpptools/files/1973198/ConsoleApplication1.zip)

2. Update "program" in launch.json as following:
"program": "${workspaceRoot}/Debug/ConsoleApplication1.exe",
3. Set a breakpoint at line of 12 'a++' in ConsoleApplication1.cpp file.
4. Press F5 to start debugging.
5. Add 'a++' into watch window.
![image](https://user-images.githubusercontent.com/20184768/39611465-66e8cfb8-4f8a-11e8-9803-24106a56d1b1.png)
6. Click Add Expression button in the top of watch window.
![image](https://user-images.githubusercontent.com/20184768/39611503-af3279cc-4f8a-11e8-8c56-5c77c319bf8f.png)
7. Observer Watch Window.

Excepted:
The value of 'a++' still is '1'.

Actual:
The value of 'a++' changed to '2' after only click '+'.
![image](https://user-images.githubusercontent.com/20184768/39611565-25bbbf0e-4f8b-11e8-955e-756ad071f3ef.png)

Investigation:
1. If I didn't add expression and click blank space to cancel the operation of 'add expression'. The value of 'a++' changed to '3'.

**Comment by pieandcakes** [comment]
@ClaireKang this isn't a bug. It changes because every time you click `+` you are asking the debugger to reevaluate the variable `a++` which is a self incrementation, causing `a` to change each time. This is normal behavior and by design.
