### ISSUE TITLE
[C++ on windows][GDB] Unable to step out.

### ISSUE THREAD

**Issue by ClaireKang** [microsoft/vscode-cpptools#1929]
VSCode Version:1.22.2
OS Version: Window7 X64
Cpptools: \scratch2\scratch\waan\vsdbg-cpptools-test
GDB: C:\cygwin64\bin\gdb.exe

Steps to Reproduce:
1. Open tests folder in attachments directly.
[test.zip](https://github.com/Microsoft/vscode-cpptools/files/1973446/test.zip)

2. Update "program" and "miDebuggerPath" in launch.json as following:
"program": "${workspaceRoot}/a.exe",
"miDebuggerPath": "C:\cygwin64\bin\gdb.exe",
3. Set a breakpoint at line of 5 'int a=1' in a.cpp file.
4. Press F5 to start debugging.
5. Step Out.  (Shift+F11)

Excepted:
Step out successfully without error message and still hit the breakpoint.

Actual:
Pop up an error message as following:
ERROR: Unexpected GDB output from command "-exec-finish". "finish" not meaningful in the outermost frame.
![image](https://user-images.githubusercontent.com/20184768/39615816-bf01ffa6-4faa-11e8-849e-e3a83c0086c2.png)

Investigation:
This issue didn't reproduce in vsdbg.

**Comment by pieandcakes** [comment]
@ClaireKang This is expected and an external issue. This happens because of cygwin

**Comment by ClaireKang** [comment]
Thanks for your info.
