### ISSUE TITLE
[C++ on windows][mingw] GDB exited unexpected when adding function in watch window

### ISSUE THREAD

**Issue by zhangmn799** [microsoft/vscode-cpptools#1930]
**Environment data**
VS Code version: 1.22.2
C++ Extension version: 0.17.0-master
Debugger: mingwin64
OS: Win7

**Steps to reproduce**
1.Install vscode.
2.Install c++ extension.
3.install Mingwin64
3.Create a folder named test, create a file named main.cpp in test as following:
![image](https://user-images.githubusercontent.com/26423555/39616093-51f0916e-4fac-11e8-8edf-6770d548a64b.png)
4.Compara project with command "g++ -g -o main.exe main.cpp" with mingwin64
5.Open vscode, open test folder, configure launch.json as following:
![image](https://user-images.githubusercontent.com/26423555/39616123-75634506-4fac-11e8-8768-32079593a587.png)
6.Set a bp in line18 of main.cpp.
7.F5
8.Add Sum(1,2) in Watch window.

**Expected behavior**
It can show Sum(1,2):3  correctly.

**Actual behavior**
gdb exited unexpected: 
![image](https://user-images.githubusercontent.com/26423555/39616227-f570ca98-4fac-11e8-9780-e434c7d33585.png)

**Comment by pieandcakes** [comment]
@zhangmn799 Which version of gdb in MinGW are you using?

**Comment by zhangmn799** [comment]
minGW gdb version:8.1

**Comment by pieandcakes** [comment]
This is a MinGW gdb 8.1 issue and not something within our control as the extension.
