### ISSUE TITLE
Variable type of the SDL library are not taken into account.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#1932]
Translated by Google
Hello,

I code with SDL but the SDL library variable types are not taken into account in vs code highlighting.
And also the variables of type struct are not taken into account in the syntax highlighting of vs code.
I also have syntax highlighting issues with uint8_t, uint16_t....

Is there a solution to solve these problems.

Is there a way to color a single variable or variable type especially with Workspace Settings.

Thanks in advance.

Code simple : 

https://www.casimages.com/img.php?i=18050409332616459915698627.jpg

**Comment by bobbrow** [comment]
This is a known issue.  Code colors are provided by regular expressions, which don't take into account user-defined and library-defined types.  We are expecting the VS Code team to give us an API that will allow us to provide our own colors based on the content of the file, but it hasn't happened yet.

We're tracking this with issue #230.

**Comment by ghost** [comment]
Thank you very much for your answer.
