### ISSUE TITLE
[C++ on windows]It has an error message with "Extension have been modified on disk"

### ISSUE THREAD

**Issue by qian6** [microsoft/vscode-cpptools#1935]
## Environment data
•VSCode Version:1.23.0
•OS Version: Window10 X64

## Steps to reproduce
1. Open Vscode
2. Install extension(cpptools-0.17.0-mater.vsix) as below:
![e](https://user-images.githubusercontent.com/20922638/39619535-bf715212-4f77-11e8-9ce4-9921fb241caa.PNG)
3. Reload extension
4. Open a project
[test.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1973742/test.zip)

## Expected  behavior
It has not error message.

## Actual behavior
It has a error message as following:
![m](https://user-images.githubusercontent.com/20922638/39619666-367714be-4f78-11e8-95d2-8ac16d86452a.PNG)

**Comment by bobbrow** [comment]
We have always written to the extension folder.  VS Code decided to add a message for it.  We can file an issue with VS Code, but I'm not sure what else to do about this.  I don't see a setting in VS Code that lets you turn this off.

**Comment by michelleangela** [comment]
Closing as external issue.
