### ISSUE TITLE
Intellisense incorrectly parsing foreach macro in postgresql code

### ISSUE THREAD

**Issue by sdebnath** [microsoft/vscode-cpptools#1939]
**Installation Information**:
* Operating System: Mac OS X 10.13.4
* VS Code version: 1.23.0
* C/C++ extension: 0.16.1
* Other extensions you installed: code outline

**Repro**:

1. Clone git //git.postgresql.org/git/postgresql.git
1. Checkout rel_10_stable branch
1. Create a new workspace at the root of the repository
1. Ensure includePath includes: "${workspaceFolder}/src/include"
1. Go to Symbol in Workspace: "exec_simple_query"

**Results**: 

    "No symbols matching"

**Details**:

The static function "exec_simple_query" is defined in src/backend/tcop/postgres.c, however, due to incorrect parsing of a macro, the symbol is not found by IntelliSense. The issue seems to be the 'foreach' macro used in the PostgreSQL code. In the function above exec_simple_query, pg_plan_queries() uses the foreach macro to iterate querytrees linked list. Based on the code outline macro, the parser seems to break down here and assumes foreach is a function by itself and skips several functions following this line including pg_plan_queries(). Symbol lookup succeeds for pg_plan_query() but not for pg_plan_queries() and exec_simple_query(). pg_plan_queries() lookup takes you to the function prototype in tcopprot.h.

 As you can see in the attached screenshot, the code outline view shows the foreach is repeated a few times (every place where it's used).

The foreach macro is defined in src/include/nodes/pg_list.h as:

    #define foreach(cell, l)	\
	for ((cell) = list_head(l); (cell) != NULL; (cell) = lnext(cell))

    
<img width="1920" alt="screen shot 2018-05-05 at 12 25 27 am" src="https://user-images.githubusercontent.com/59411/39660914-75173796-4ffd-11e8-8d1c-9e8986c1706c.png">

**Comment by sean-mcmanus** [comment]
This is a "by design" limitation of our symbol parser. The macro representing the foreach should be added to a cpp.hint file in your workspace root to fix the issue. See https://msdn.microsoft.com/en-us/library/dd997977.aspx .

**Comment by sean-mcmanus** [comment]
FYI, this is fixed with 1.10.3 (pre-release) -- no cpp.hint is required for this case.
