### ISSUE TITLE
Cannot add include path to settings. 

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-cpptools#194]
_From @Antranilan on August 31, 2016 22:19_
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:
1. Hover over any green squiggle in a source file (e.g. a #include statement).
2. Click the lightbulb that appears underneath the mouse cursor.
3. Click Add include path to settings.

c_cpp_properties.json does not generate/cannot find a directory of the file

_Copied from original issue: Microsoft/vscode#11346_

**Comment by sridmad** [comment]
@Antranilan what is the version of the extension?

**Comment by ghost** [comment]
0.9.0

**Comment by xaverh** [comment]
Does your project folder name have a special character in it? This problem occurred to me when I had a "#" sign in the folder name.

**Comment by bobbrow** [comment]
We fixed the issue with having a special character like '#' in the path.  If you are still having issues, please reopen and let us know.
