### ISSUE TITLE
Failed to create IntelliSense for *.h, but success for *.cpp in 0.17.0

### ISSUE THREAD

**Issue by meritozh** [microsoft/vscode-cpptools#1954]
It can work in 0.17.0, but can work well in 0.16.0.

My *c_cpp_properties.json*:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "compilerPath": "/usr/local/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

> this clang is build from clang svn, version 7.0.0

It cannot works when I focus on header file.

I have set "C_Cpp.loggingLevel": "Information", it report:

```
Failed to create IntelliSense client. Can't create intellisense client for <my source file>.h
...
Unable to add file to database, error = 0x8064000a: /usr/include/<headers>
...
Unable to add file to database, error = 0x8064000a: /usr/local/include/<headers>
...
  Discovering files: 21994 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files
```

But it can work for *.cpp files with:

```
Unable to add file to database, error = 0x8064000a: <my source file>.cpp
```

**Comment by LordHog** [comment]
I am seeing the seem issue in a CentOS v7 machine, but it was all source files.  The generic error was:

```
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
  Folder: /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /users/mrhicks/projects/eagle/repo/ will be indexed
Discovering files...
Unable to add file to database, error = 0x8064000a: "path to file"
```

I also noticed that VSC was creating some file in the parent folder

```
-rw-------  1 mrhicks wheel      301M May 18 18:03 core.28567
-rw-------  1 mrhicks wheel      374M May 18 18:03 core.29820
-rw-------  1 mrhicks wheel      407M May 18 18:03 core.30135
-rw-------  1 mrhicks wheel      295M May 18 18:03 core.30368
```

What is strange, they appear to be ELF files

`/users/mrhicks/tmp/core.30368: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/users/mrhicks/.vscode/extensions/ms-vscode.cpptools-0.17.1/bin/Microsoft.VSCod', real uid: 12835, effective uid: 12835, real gid: 10, effective gid: 10, execfn: '/users/mrhicks/.vscode/extensions/ms-vscode.cpptools-0.17.1/bin/Microsoft.VSCode.CPP.Extension.linux', platform: 'x86_64'`

The IntelliSense would not work even if I closed and restarted VSCode.  I basically had to restart the machine.  Since updating to 0.17.1 I have been noticing instability with the CPPTools.  It would work for a while then stop.  I just enabled the logging, so perhaps I will find something interesting.

**Comment by sean-mcmanus** [comment]
@LordHog By instability do you suspect crashing? There is a known instability compared to 0.17.0 if you're using recursive include paths that we're working on fixing (although the root issues might exist in some non-recursive include path scenarios as well). Our extension doesn't create those ELF files so I don't think it's related to the failures.

0x806400a is a pending_io error from SQLITE (not sure the cause yet, but I don't think it's serious). It's from the symbol parser so it shouldn't affect IntelliSense features.

**Comment by LordHog** [comment]
Mr. @sean-mcmanus,

>0x806400a is a pending_io error from SQLITE (not sure the cause yet, but I don't think it's serious). It's from the symbol parser so it shouldn't affect IntelliSense features.

In this particular case, yes, it does affect IntelliSense given that no file was process thus when trying to navigate the source code a popup would just state the symbol was not found.

>There is a known instability compared to 0.17.0 if you're using recursive include paths that we're working on fixing (although the root issues might exist in some non-recursive include path scenarios as well). 

I am not exactly sure what this mean, but I don't setup the include paths for CPPTools, so perhaps that is it.  By instability, I mean when I first launch VSCode the IntelliSense works though after some time it would go back to the BlueCylon issue that I saw all those months ago.  I have only been working within Linux/CentOS these days, but I can try on Windows to see if it behaves differently.

I will attempt to collect better data for you.


>Our extension doesn't create those ELF files so I don't think it's related to the failures.

Strange, given this was in the C/C++ Output Window shows that the extension was looking for something similar in this case (I have deleted the four files list in the previous post.  Plus, when execution the "file" command against those four files it output the execfn as Microsoft.VSCode.CPP.Extension.linux

C/C++ Output Window
```
Discovering files...
  Processing folder (recursive): /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /users/mrhicks/projects/eagle/repo/
  Discovering files: 10231 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Parsing remaining files...
Done parsing open files.
Unable to determine real path of /users/mrhicks/projects/eagle/repo/core.468. Error = 2
Unable to determine real path of /users/mrhicks/projects/eagle/repo/core.468. Error = 2
```

**Comment by bobbrow** [comment]
Are the `core.*` files core dumps?  Are you able to load them with gdb and get any information out of them?

**Comment by LordHog** [comment]
Mr. @bobbrow,

  This was the output of gdb when loading one of the files

```
[mrhicks@irv-uti-12 tmp]$ gdb core.28567 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
[New LWP 28568]
[New LWP 28567]
[New LWP 28569]
[New LWP 28570]
[New LWP 28572]
[New LWP 28571]
[New LWP 28573]
[New LWP 28574]
[New LWP 28575]
[New LWP 28576]
[New LWP 28577]
[New LWP 28578]
[New LWP 28579]
[New LWP 28580]
[New LWP 28581]
[New LWP 28582]
Core was generated by `/users/mrhicks/.vscode/extensions/ms-vscode.cpptools-0.17.1/bin/Microsoft.VSCod'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000059f217 in ?? ()
"/users/mrhicks/tmp/core.28567" is a core file.
Please specify an executable to debug.
```

I am no gdb expert (or beginner), but if I try to run it I get

(gdb) run
Starting program:  
No executable file specified.

I can certainly send one of the files if you are curious.  They are quite large, so would need a method of sending them.

**Comment by sean-mcmanus** [comment]
If you have no c_cpp_properties.json generated then it default to recursive includes with ${workspaceFolder/**} in the includePath. Our pending fix for the recursive includes crashing is expected to fix a lot of random IntelliSense crashes with the main process.

It sounds like the crashing is causing those core files to be generated by the OS (we don't create them ourselves).

If you edit/save a file does it manage to add the file with that can't be added with 0x806400a? The failure is occurring before we even parse the file. My best guess is that another process is trying to modify the database at the same time. We might need to find a repro.

**Comment by bobbrow** [comment]
To debug a core with gdb, I believe you need to pass in the executable name first:

```
gdb /users/mrhicks/.vscode/extensions/ms-vscode.cpptools-0.17.1/bin/Microsoft.VSCode.CPP.Extension.linux core.28567
```

Then you do

```
(gdb) bt full
```

Which should give you the callstack of the crash.  I think you can also do `thread apply all bt` to get stack traces for all thread, which might also be helpful.

My experience with gdb is also limited.  I'm pulling some of this information from [this question](https://stackoverflow.com/questions/8305866/how-to-analyze-a-programs-core-dump-file-with-gdb)

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.

Update to the latest version of the C/C++ extension and see if issue still persists. Please re-open the issue and reply with additional information that can help us investigate the issue.

**Comment by EmbeddedBacon** [comment]
Over the past six months the vscode-cpptools has been more stable, at least for me.  I don't recall seeing this issue for a number of months now.  Though, I don't pay a great deal of attention to the Output console for C/C++.  Great work by the vscode-cpptools team.
