### ISSUE TITLE
I think it's a bug in this case

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/vscode-cpptools#1956]
Clone [my demo project](https://github.com/DFVSQY/VscodeMsvcDemo) on window10 computer that has installed visual studio 2017, then copy below text to **main.cpp** file:
~~~C++
#include <iostream>
using namespace std;

class Useless {
   private:
    int n;
    char *pc;
    static int ct;
    void ShowObject() const;

   public:
    Useless();
    explicit Useless(int k);
    Useless(int k, char ch);
    Useless(const Useless &f);
    Useless(Useless &&f);
    ~Useless();
    Useless operator+(const Useless &f) const;
    void ShowData() const;
};

int Useless::ct = 0;

Useless::Useless() {
    ++ct;
    n = 0;
    pc = nullptr;
    cout << "default constructor called, number of objects:" << ct << endl;
    ShowObject();
}

Useless::Useless(int k) : n(k) {
    ++ct;
    pc = new char[n];
    cout << "int constructor callled, number of objects:" << ct << endl;
    ShowObject();
}

Useless::Useless(int k, char ch) : n(k) {
    ++ct;
    pc = new char[n];
    for (int i = 0; i < n; i++) pc[i] = ch;
    cout << "int, char constructor called, number of objects:" << ct << endl;
    ShowObject();
}

Useless::Useless(const Useless &f) : n(f.n) {
    ++ct;
    pc = new char[n];
    for (int i = 0; i < n; i++) pc[i] = f.pc[i];
    cout << "copy const called, number of objects:" << ct << endl;
    ShowObject();
}

Useless::Useless(Useless &&f) : n(f.n) {
    ++ct;
    cout << "move constructor callled, number of objects:" << ct << endl;
    pc = f.pc;
    f.pc = nullptr;
    f.n = 0;
    ShowObject();
}

Useless::~Useless() {
    cout << "destructor called, objects left:" << --ct << endl;
    cout << "deleted object\n";
    ShowObject();
    delete[] pc;
}

Useless Useless::operator+(const Useless &f) const {
    cout << "Entering operator+()\n";
    Useless temp = Useless(n + f.n);
    for (int i = 0; i < n; i++) {
        temp.pc[i] = pc[i];
    }
    for (int i = n; i < temp.n; i++) {
        temp.pc[i] = f.pc[i - n];
    }
    cout << "temp object:\n";
    cout << "Leaving operator+()\n";
    return temp;
}

void Useless::ShowObject() const {
    cout << "number of elements:" << n << " Data Address:" << (void *)pc
         << endl;
}

void Useless::ShowData() const {
    if (n == 0)
        cout << "(object empty)";
    else
        for (int i = 0; i < n; i++) cout << pc[i];
    cout << endl;
}

int main() {
    cout << "---------one------------'\n";
    Useless one(10, 'x');
    cout << "---------two------------'\n";
    Useless two = one;
    cout << "--------three-----------'\n";
    Useless three(20, 'o');
    cout << "---------four-----------'\n";
    Useless four(one + three);

    cout << endl;

    cout << "object one: ";
    one.ShowData();
    cout << "object two: ";
    two.ShowData();
    cout << "object three: ";
    three.ShowData();
    cout << "object four: ";
    four.ShowData();

    cout << endl;

    return 0;
}
~~~
Then follow these steps:
1.  **Run Build Task** to compile this demo to produce main.exe.
2.  **Run Test Task** to run the main.exe, however the output is not complete and random, e.g:
![image](https://user-images.githubusercontent.com/8075421/39767593-b69ef63a-5319-11e8-8bbf-ed56e808670f.png)
Note: run the main.exe on powershell is ok:
![image](https://user-images.githubusercontent.com/8075421/39767838-4105759c-531a-11e8-9457-10e9a7419e42.png)

**Comment by bobbrow** [comment]
Can you share your `tasks.json` and `launch.json` so we can see how you configured it?

**Comment by DFVSQY** [comment]
my [launch.json](https://raw.githubusercontent.com/DFVSQY/VscodeMsvcDemo/master/.vscode/launch.json) and [tasks.json](https://raw.githubusercontent.com/DFVSQY/VscodeMsvcDemo/master/.vscode/tasks.json)

**Comment by DFVSQY** [comment]
you can also view [my project demo](https://github.com/DFVSQY/VscodeMsvcDemo)

**Comment by bobbrow** [comment]
I cloned your repo and pasted in the code above to main.cpp, but I don't see any corruption.  I tried both setting a breakpoint (so the console window would persist), and adding `"windows": {"externalConsole": false}` to the launch.json so it would print in the Debug Console, but I still don't see any corruption.

Is there anything else I should know about your project?

**Comment by DFVSQY** [comment]
My win10 platform and vscode are both simplified chinese edition.
This happens 100% on my computer.

**Comment by DFVSQY** [comment]
When i set a breakpoint and set `"externalConsole": false`, then press F5 to debug it also print the result properly.

**Comment by bobbrow** [comment]
Ok, I noticed in your picture that you're running this in the integrated terminal.  When I run your task in the cloned project, it doesn't attempt to print the output to the integrated terminal, but if I run `main.exe` in the integrated terminal I do see that not all of the output is printed in the console (in both English and Chinese versions).

Unfortunately, this is not something our extension has any control over.  This is a bug in VS Code.  You can [open an issue in their repo](https://github.com/Microsoft/vscode/issues/new) and let them know it's a problem with the integrated terminal.
