### ISSUE TITLE
Extension crashes repeatedly

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#1957]
Extracted from #1232 

@daltairwalter, can you please provide some information about your workspace:
* OS
* Extension version
* VSCode version
* Is your project open source/can we clone it?
  * Or do you have a small repro you can zip up and attach to the issue?

On Windows, you can follow [these instructions](https://bugslasher.net/2011/03/26/how-to-debug-a-process-as-soon-as-it-starts-with-windbg-or-visual-studio-2010/) to automatically attach to the extension process `Microsoft.VSCode.CPP.Extension.exe` with WinDbg or Visual Studio. Then save a crash dump when the process crashes.

**Comment by daltairwalter** [comment]
This crash seems strongly linked to Symantec Endpoint Protection.  I will see if I can get the steps to create a crash dump to work, the other information is below.

OS: windows 7 and windows 10
extension: 0.17.0
VSCode version:
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

The project is proprietary.

**Comment by ZanderPete** [comment]
My language server is also crashing (and actually being quarantined) by Symantec Endpoint Protection. So no intellisense works.

**Comment by daltairwalter** [comment]
My attempts to get a dump file using the methods above were unsuccessful.  The current versions of gflags didn't show a gui.  Using an older version of gflags, I was at least able to get windbg to start, but then when I tried to start it in windbg it said no debuggee.

**Comment by bobbrow** [comment]
That's weird.  I've never seen a version of gflags that didn't pop up a GUI.  But I just tried this and it doesn't seem to work for me anymore either.  I'll need to write up some new instructions, I suppose.

**Comment by sean-mcmanus** [comment]
On Windows, you can just right-click in Task Manager and do "Create dump file", which creates it in %tmp%. The symbols aren't available due an issue in our build process, but we could publish the symbols via some other means or they could send us the dmp.

Oh...but you need to use VS Code's cppvsdbg to attach to the process before it crashes first.

**Comment by bobbrow** [comment]
Yes, that's the problem.  We need to attach on launch before it crashes.

**Comment by sean-mcmanus** [comment]
If someone who is able to repro this crash could clone our git repo: https://github.com/Microsoft/vscode-cpptools/tree/release, and do Launch Extension after setting a breakpoint on line 317 of `vscode-cpptools\Extension\src\LanguageServer\client.ts` after languageClient.start(), then you could attach a debugger at that point, which is before we do initialization so I would assume it wouldn't be crashed yet, and then let it crash, which should break into the debugger and you'll be able to create a dmp and then copy the call stack (pdb files for viewing the 0.17.0 call stacks on Windows are available at https://go.microsoft.com/fwlink/?linkid=874019 , Linux and Mac binaries have debug info already).

**Comment by sean-mcmanus** [comment]
Also, has anyone reproed this on Windows 1803? So far I only see repros with 1709.

**Comment by HuangZhs1199** [comment]
It re-appeared on Windows  1803 too.

Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

![default](https://user-images.githubusercontent.com/14327370/51024581-e74f0680-15c4-11e9-8463-54a162ef6f08.PNG)

**Comment by sean-mcmanus** [comment]
@hzs19900515 You provided the Windows and VS Code version, but you didn't provide the version of the C/C++ extension you're using. Using 0.21.0-insiders3 is recommended, because 0.20.1 ships with unsigned binaries (i.e. incorrectly removed by some virus scans) and other crashes that could lead to this failure.

**Comment by HuangZhs1199** [comment]
sorry，in extension  I can only find C/C++ 0.20.1

**Comment by sean-mcmanus** [comment]
Can you set your C_Cpp.updateChannel to "Insiders"?

**Comment by HuangZhs1199** [comment]
I set C_Cpp.updateChannel to "Insiders"，but it did not automatically download 0.21.0-0-Insiders3，I download and install 0.21.0-insiders3 from https://github.com/Microsoft/vscode-cpptools/releases，it work s，Thank you

**Comment by Colengms** [comment]
This issue appears to have been addressed.  Closing.
