### ISSUE TITLE
Use proper discrete progress

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-cpptools#1961]
Saw a progress bar today in the notification area with 5 steps to download additional things. I suggest to change this into a progress with discrete reporting (20% chunks each) to get rid of the "1/5, "2/5" etc. label which is rather ugly.

Refs: https://code.visualstudio.com/updates/v1_22#_show-long-running-operations-as-notifications-with-cancellation-support

**Comment by sean-mcmanus** [comment]
@WardenGnaw Did you want to fix this? The download goes away so fast for me that I barely have noticed it or had time to read what it said.

**Comment by WardenGnaw** [comment]
The 1/5 -> 2/5 files is not a direct translation of 20% progress being completed. The downloaded zip files are different sizes. For users with slower machines, they might see one file download in a minute and then another file in 50 minutes. It is frustrating to see progress bars that are near completion (e.g. 99%) and the last 1% takes a much longer time. 

The reasoning behing the "1/5" indicator shows what is left and there is a label "Downloading" and "Installing" to show the phase.

**Comment by bpasero** [comment]
@WardenGnaw you can still show a label that updates and discrete progress. For the label I would then maybe have a suffix (...3 more downloads to do).

**Comment by elahehrashedi** [comment]
current behaviour:

![current](https://user-images.githubusercontent.com/16143955/91477875-dadbf800-e853-11ea-9aeb-5e26be844adc.gif)

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.0.0
