### ISSUE TITLE
Intellisense Clang-x64 Broken in v0.17.0

### ISSUE THREAD

**Issue by clay07g** [microsoft/vscode-cpptools#1962]
OS: Windows 10
Extension Version: 0.17.0
VSCode Version: 1.23.0

Upgrading this extension breaks nearly all of my Intellisense, but not in any particular pattern. It finds all the header files correctly, but fails to resolve certain types from namespaces.

For example, this is fine:
`#include "nlohmann/json.hpp"`

But then I get a red squiggle under:
`using json = nlohmann::json;`

"nlohmann" is undefined.

Pretty much all of my Intellisense doesn't work. Sometimes it finds some classes and namespaces. Sometimes it fails to find 1 class in a namespace but finds the rest. The errors do not go away after reloading, restarting, or waiting.

If I manually install version 0.16.1, it works properly (until VSCode auto-updates the extension). Also, compilation works properly as before.

My c_cpp_properties.json looks something like:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}/dependencies",
                "${workspaceRoot}/include",
                "${workspaceRoot}/dependencies/nlohmann",
                "C:/mingw64/x86_64-w64-mingw32/include",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/tr1",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/mingw32",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/backward",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/x86_64-w64-mingw32",
                "${workspaceRoot}",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++/ext/pb_ds"
            ],
            "defines": [
                "BUILD_DLL",
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "__GNUC__=6",
                "__cdecl=__attribute__((__cdecl__))",
                "__SIZE_TYPE__=long long unsigned int"
            ],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "C:/mingw64/include/*",
                    "C:/mingw64/x86_64-w64-mingw32/include",
                    "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include",
                    "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/c++",
                    "C:/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include-fixed",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": false,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
We have new docs at https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md . Can you try following that? Your config settings might be causing some problem. Your system defines might be incorrect.

**Comment by clay07g** [comment]
@sean-mcmanus 

Thanks for the quick reply. That works perfectly.

Thank you!

**Comment by sean-mcmanus** [comment]
@bobbrow Is there still a bug here we should investigate? It seems like the new version is regressing people who have the old mingw configs. I'll close this for now...might want to re-visit it if more people hit this.

**Comment by bobbrow** [comment]
@Clay24g when you first upgraded to 0.17.0 did you notice a `"compilerPath"` property added to your **c_cpp_properties.json**?  The only thing I can think of that went wrong is that we picked a different compiler than the one you had already added the paths for and ended up with conflicting system includes.
