### ISSUE TITLE
Extension crashes on Windows when the root drive is in the includePath.

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#1965]
If the includePath contains a path like "C:/" the extension will crash. Not sure if this is what other people are hitting...seems like that would be an unusual includePath.

**Comment by fr43nk** [comment]
OS: Win7
Plugin Version: 0.17.0

I'm not sure if this is related to my problem:

1. My system path pointed to a folder containing a gcc.exe file.
2. Opened my vscode
3. in an external cmd window I started a build process (not using the gcc.exe)
4. after a while when the build is running the extension recursively starts a gcc.exe ending up with more than 20000 of such processes. 
5. had to power off my pc :(

I am not sure if this is by intension?

The folder contains a lot of files and a lot of directories. So I think that is why there are so many recursive processes. But can't that be limited?
