### ISSUE TITLE
Unclear Docs for includePath on WSL LanguageServer Setup Instructions

### ISSUE THREAD

**Issue by loganhuskins** [microsoft/vscode-cpptools#1967]
In the documentation for setting up the Language Server for the plugin using WSL doesn't go into as much detail as novice C/C++ developers like me may need to set up the "includePath" and "path" options. When looking at the docs, I took those paths outlined literally and could not get it set up without digging for where to find the C libs that I needed.

In the next day or two while I have some time I'd like to outline where those come from and go in a little more detail in that portion of the docs if anyone would think it's helpful.

**Comment by sean-mcmanus** [comment]
What C libs did you need? We query the WSL compiler for the default system headers. Did you need to add additional include paths?

Yeah, if you want to submit a pull request to improve the docs that sounds good.

**Comment by loganhuskins** [comment]
Yeah, I just added stdio as an include at the top of my simple Hello World app to get my environment set up and got an error in my editor for it. It ran just fine from Code, I just had issues in the actual editor.

**Comment by sean-mcmanus** [comment]
Do you mean stdio.h? That should be findable via just setting your compilerPath to "/usr/bin/gcc" (and setting the intelliSenseMode to clang-x64). Did that not work? Did you use the docs at https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md ?

**Comment by loganhuskins** [comment]
Hmm, I just created a new project and it's working. Maybe there was a cache or something that had not updated and I was not patient enough? Sorry to bug you if this was user error.

**Comment by sean-mcmanus** [comment]
Hmm...we could have a bug somewhere. Yeah, there's a known bug when switching from a non-WSL to WSL config -- you might have hit that: https://github.com/Microsoft/vscode-cpptools/issues/1958

**Comment by loganhuskins** [comment]
Yep, if I hit a duplicate and was wrong as to what was happening I guess there's no reason for a doc update. Thanks.
