### ISSUE TITLE
includePath in Mac or Win10

### ISSUE THREAD

**Issue by TheLiufp** [microsoft/vscode-cpptools#1969]
Hi

When I code in Vs code, and take CppTools as extension, it appeared that some .h file cannot be opened or found.

The .h header file like "iostream.h" etc. come into error, but"stdio.h"is ok.

I have added the path like "/usr/include","/usr/include/c++/4.2.1/backward",etc. in both browse.path and include.path. 

when coding, the path of "iostream.h" appears, but after typing, the error occurs.

it also occurred in win10.

Many  thanks.

**Comment by TheLiufp** [comment]
For details:

The following code goes well:
/
#include<stdio.h>
#include</usr/include/c++/4.2.1/backward/iostream.h>
/ 
but the following does not work

#include<stdio.h>
#include<iostream.h>

the path "/usr/include/c++/4.2.1/backward" was added to .json file.

**Comment by sean-mcmanus** [comment]
Is there a reason you're not using `#include <iostream>`? I don't have /4.2.1/backward/iostream.h. Are you able to use a newer gcc library with "iostream"?

What is your compilerPath, i.e. mingw, WSL, Cygwin, clang?

**Comment by TheLiufp** [comment]
I have tried in win10 ,using MinGW, and set the path C:\MinGW\bin\ in env..

My #include<stdio.h> came to error, file cannot be found.

the following address show the detail config. for MinGW.
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Archive/MinGW.md

**Comment by sean-mcmanus** [comment]
Oh, the path needs to end in the compiler name, such as gcc.exe or g++.exe. Can you add that? See https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md . intelliSenseMode needs to be "clang-x64" too.

**Comment by TheLiufp** [comment]
Thank you. 

I have added the gcc.exe , an interesting thing is 
the "#include<stdlib.h>" is ok ,but "#include<stdio.h>" still cannot be found. 

my config. as following:

```
"configurations": [
        {
            "name": "MinGW",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\MinGW\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
```

**Comment by sean-mcmanus** [comment]
Do you have WSL on your machine? Looks like I'm hitting a bug in which the WSL compiler is getting used instead of the mingw one -- I need to fix that before I can try to repro it with mingw...

**Comment by TheLiufp** [comment]
I do not have WSL on my machine. but I have both MinGW and clang , Maybe these two have some conflict.

**Comment by sean-mcmanus** [comment]
@TheLiufp Oh -- duh, my mingw was on my F drive instead of C, so it was falling back to WSL instead.

It's working for me and finding stdio.h at `F:\MinGW\include`. I have 5.3 library headers though instead of 4.2.1.

If you set your loggingLevel to the hidden value of "6" do you see errors or suspicious output (in the C/C++ dropdown in the Output tab), such as after "sending compilation args for" where it lists the include paths and defines used.

**Comment by bobbrow** [comment]
Closing older issues.  If you continue to experience this problem, please send us the logging information requested, as well as the output of running the "Log Diagnostics" command.  Thank you!
