### ISSUE TITLE
cpptools not finding correct system include file

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#1971]
Running v.0.17.0-insiders on Windows 10.

My c_cpp_properties.json file contains:

    "includePath": [
        "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/",
        "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/linux",
        "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0",
        "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0/tr1",
        "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0/x86_64-wrs-linux",
        "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/python2.7",
    <snip>
    ],
    "defines": [
        "__x86_64__",
        "__USE_GNU"
    ],
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": "${workspaceRoot}/.vscode/.browse2.vc.db",
        "path": [
            "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include",
            "${workspaceRoot}"
        ]
    },
    "intelliSenseMode": "clang-x64",
    "compilerPath": "",
    "cStandard": "c11",
    "cppStandard": "c++17"

One of my header files contains:

    #include <sys/socket.h>

When I right click 'Go to definition' on that file I see multiple instances of socket.h offered:

![image](https://user-images.githubusercontent.com/7724321/39814278-9c5a250c-538b-11e8-8f7b-ad7b2f472d10.png)

why doesn't cpptools resolve to sys/socket.h rather than offering all socket.h files in usr/include?

**Comment by sean-mcmanus** [comment]
That's an old bug we just haven't gotten around to fixing. Only the "socket.h" is checked and the `<sys>` part is not used to filter out the results. I think there's another issue tracking this, but I'm not sure what number.

**Comment by sean-mcmanus** [comment]
This got fixed 2 months ago in 0.17.4 -- the path part of the #include is used to filter out results. An earlier issue on this was https://github.com/Microsoft/vscode-cpptools/issues/1253 .
