### ISSUE TITLE
Wrong go to definition

### ISSUE THREAD

**Issue by KarolisMil** [microsoft/vscode-cpptools#1976]
Hey. 
I am not sure if I am making some mistake, but seems that Code does not correctly goes to definition. I have added workspace setting for "C_Cpp.default.includePath" and listed all necessary directories fro my project. Then if I navigate to some symbol in the code and do "Go To Definition", it shows few different files that include that definition and none of those files are reachable by" C_Cpp.default.includePath". Also, for example, if symbol of which I am searching for definition happens to be "uint32_t", it shows me few files that exist in my workspace folder, but their paths are not in configuration. And I get "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include" as well and I am not added this. For stdint.h I have added other toolchain specific path which is not in the list of "Go To Definition".

I am using all default settings except "C_Cpp.default.includePath":
```
{
    "C_Cpp.default.includePath" : [
        "C:\\<path_to_fodler>",
        "${workspaceFolder}\\Application\\API",
        <other paths>
    ]
}
```

OS: Windows 7 Pro SP1
C/C++ extension: Version 0.17.0
Code:
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by bobbrow** [comment]
We automatically add system includes to both `includePath` and `browse.path`.  The Visual Studio compiler is set as the default provider of system includes on Windows.

If you are using a different compiler, you can fix this by setting `"C_Cpp.default.compilerPath"` to the compiler you're using (e.g. "c:/mingw/bin/gcc.exe").  Most of these alternate compilers require the "intelliSenseMode" to be set to "clang-x64" as well.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
