### ISSUE TITLE
g++ not responding in integrated terminal

### ISSUE THREAD

**Issue by salbeira** [microsoft/vscode-cpptools#1978]
Using ArchLinux on a Dell XPS 15 9560.

Whenever I try to start the g++ in the integrated terminal the call hangs and outputs nothing. Even just compiling a simple "Hello World" Program using the g++ manually, not called from make, causes the call to hang. CTRL+C still allows cancelling. The integrated terminal says that the normal "bash" is running.

Calling g++ or make from the directory the project I am working on is located in a normal external terminal works fine.

``g++ foo.cpp -o foo`` - hangs
even
``g++ --version`` - hangs

**Comment by WardenGnaw** [comment]
Integrated terminal is a VS Code feature. The extension at the moment does support integrated terminal and it would be during debugging. 

Moved to https://github.com/Microsoft/vscode/issues/49650
