### ISSUE TITLE
auto completion outputs wrong results

### ISSUE THREAD

**Issue by JinnTonic** [microsoft/vscode-cpptools#198]
platform : macOS 10.12 beta, Visual Studio Code 1.4.0, extension C/C++ 0.9.0

1-Type in this code :

```
struct StructA
{
    int a;
    float b;
    char c;
};

struct StructB
{
    StructA myStructA;
};

int main ()
{
    StructB myStructB;
    return 0;
}
```

 2- test auto-complete by typing "myStructB." in the main function.
Every possible symbol gets displayed (only "myStructA" should be displayed) ; semantics is not taken into account.
As a comparison, the extension "C/C++ Clang" does a correct job ; it is also much much quicker to highlight code errors.

**Comment by bootsector** [comment]
+1

**Comment by bobbrow** [comment]
Thank you for your feedback.  Semantic-aware autocomplete is being tracked by issue #13.
