### ISSUE TITLE
There missing a tip for "operator()"

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/vscode-cpptools#1986]
There is no tip for function `operator()`, like below:
![image](https://user-images.githubusercontent.com/8075421/39957217-d662e5fc-5621-11e8-8e91-c0b2db8829c7.png)

**Comment by bobbrow** [comment]
Hmm... I don't see those suggestions if I put this code in a simple file with no `#include`s.  I don't think IntelliSense is offering you suggestions for operators to overload.  I think it's trying to autocomplete overloads that have already been defined elsewhere.  It seems like bug that IntelliSense would offer you those suggestions in this context.  I'm seeing the same behavior in Visual Studio 2017, so I'll file a bug with them.

**Comment by sean-mcmanus** [comment]
@bobbrow Did you file a VS bug? Do you know the bug number?

**Comment by sean-mcmanus** [comment]
This should be fixed in the latest insiders build (i.e. no completion popup for "operator" should appear): https://github.com/Microsoft/vscode-cpptools/releases .
