### ISSUE TITLE
C++ CLI support for assembly references

### ISSUE THREAD

**Issue by fgenolini** [microsoft/vscode-cpptools#1987]
Could you add support for the Microsoft C++ CLI language?

For example, add support for parsing .Net assembly import statements such as:
 
```C++
	using namespace System::Windows::Forms;
```

also could you add support for managed type parsing, such as:

```C++
	public ref class MyForm : public System::Windows::Forms::Form
	{
	};
```

or

```C++
[STAThread]
void Main(array<String^>^ args)
{
}
```

**Comment by bobbrow** [comment]
We do have some support for C++ CLI if you set `"compilerPath": "C:/path/to/cl.exe /clr"` in your **c_cpp_properties.json**

![image](https://user-images.githubusercontent.com/12818240/39959317-b389bb30-55c4-11e8-8829-df0ae89ad312.png)

I didn't see the System::Windows namespace in there though, so I don't think that we've wired up support for assembly references yet.  @sean-mcmanus?

**Comment by fgenolini** [comment]
Thanks for this.

For the moment I will temporarily fix this by adding

```C++
#using "System.Windows.Forms.dll"
```

in all translation units that I need VS Code to recognise

Regards,

**Comment by sean-mcmanus** [comment]
Yeah, I just added support for the basic C++/CLI language features and I didn't try it with System.Windows.Forms.

**Comment by Colengms** [comment]
I don't believe there is a bug here.  The location of the assembly needs to be specified as an include path.  i.e.

```
"includePath": [
    "${workspaceFolder}/**",
    "C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/.NETFramework/v4.8"
],
```

Using the above, `System::Windows::Forms` shows up for me via auto-complete, and does not squiggle if used in `using namespace`.
