### ISSUE TITLE
How do I configure the extension?

### ISSUE THREAD

**Issue by shivam7569** [microsoft/vscode-cpptools#1991]
I have just installed VS Code and its C/C++ extension but it's not showing the green lines under the #include when I am writing a code. I want to include c_cpp_properties.json but I am unable to do so. Please help!

**Comment by bobbrow** [comment]
~If you put the cursor on one of the squiggly lines, you should see a lightbulb appear.  Click on the lightbulb and a menu will appear with some options that will open the c_cpp_properties.json file for you or a suggestion for an include path to add (which will be placed in the c_cpp_properties.json file for you)~

**Comment by bobbrow** [comment]
EDIT: Sorry, I missed the "not" in your description.  Can you check if the "C" or "C++" language is selected in the lower right hand corner of the VS Code Window?  If you are working on a new file (e.g. "Untitled-1" with no extension, VS Code won't recognize that file as C or C++ and won't load our extension to service it.

![image](https://user-images.githubusercontent.com/12818240/40007376-6eedc05a-5751-11e8-9e11-e2d1a3c1c702.png)

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
