### ISSUE TITLE
Freezing when searching for headers

### ISSUE THREAD

**Issue by Trevinlc1997** [microsoft/vscode-cpptools#1995]
Issue Type: <b>Performance Issue</b>

My example will be using the boost headers as this seems to be stressing the autocomplete header feature. If I were to type "#include <boost/" it would freeze for about half a second and continue to do so as I finish typing. 

Extension version: 0.17.0
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.16.8-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 1978)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.66GB (11.57GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   112	  1521	code main
    0	    16	  1523	   zygote
    0	    80	  1565	     shared-process
    4	   241	  1862	     window (main.cpp - Test - Visual Studio Code)
    1	    80	  1895	       extensionHost
    2	   128	  1982	         /home/tcorkery/.vscode/extensions/ms-vscode.cpptools-0.17.0/bin/Microsoft.VSCode.CPP.Extension.linux
    1	   289	  2009	           /home/tcorkery/.vscode/extensions/ms-vscode.cpptools-0.17.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 1982 0
    0	    48	  2180	         electron_node jsonServerMain.js 
    0	    48	  1902	       watcherService
    0	    80	  2804	     shared-process
    1	    96	  1550	   gpu-process
    0	     0	  2823	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (main.cpp - Test - Visual Studio Code)
|    Folder (Test): 2 files
|      File types: json(1) cpp(1)
|      Conf files: settings.json(1);
```

</details>

**Comment by sean-mcmanus** [comment]
Is there a red flame or database icon in the bottom right? `#include` autocompletion will be delayed until those icons are gone.

@bobbrow @grdowns I can't repro any perf problem (using boost 1.62). Are you guys able to?

**Comment by Trevinlc1997** [comment]
The read flame/database icon is absent while these issues occur. Below you will find an attachment of the stuttering that is happening when I search for a header.
![peek 2018-05-14 22-06](https://user-images.githubusercontent.com/24485362/40034641-6d15ccb0-57c3-11e8-8dc8-d4e0b9b4fc9a.gif)

**Comment by sean-mcmanus** [comment]
Oh...the slight 1 second lagginess in your screenshot appears "normal" (I mean the time it takes for the autocomplete popup to appear). We could look into making it faster though. If typing in general is laggy/freezing that would probably be due to CPU usage being too high since VS Code itself deals with the actual text typing.

UPDATE: I do also observe a slight typing lag -- I agree that the typing lag is unexpected -- I suspect it's caused by VS Code blocking text input due to it receiving a large amount of completion data, but it's something worth investigating later.

**Comment by Trevinlc1997** [comment]
@sean-mcmanus Alright good to know its "normal" Also general typing doesn't lag/freeze, just seems to be the autoinclude feature.

**Comment by bobbrow** [comment]
We improved this scenario significantly earlier this year.  Please let us know if you continue to see laggy performance with this feature.
