### ISSUE TITLE
Go To/Symbols/autocompletion + compile_commands.json not working since 1.23

### ISSUE THREAD

**Issue by OrbitalHustler** [microsoft/vscode-cpptools#1997]
I'm using:

- VSCode 1.23.1
- C/C++ extension: 0.17.0

I figure this is a bug since before I updated to 1.23 I was able to use Go To, Ctrl+T to find symbols etc. Now I can't use any IntelliSense or autocompletion.

I have a compile_commands.json that defines lots of commands (40k lines), some with symbolic links.

My c_cpp_properties.json is as follow

{
    "configurations": [
        {
            "name": "Linux",
            "compileCommands": "build_x86_64-sles11-gcc4_Debug/compile_commands.json",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4

My user settings contains the line ""C_Cpp.intelliSenseEngine": "Default".

I didn't change a thing except updating VSCode. I don't really know how to debug this. I think it's the Intellisense that's bugging, I'd appreciate some advice to know where to look.

I know it's at the very least parsing the json because, for exemple, if I remove a specific symbolic link mentionned in the compile_commands.json, some of the #include directives will be underlined in green and tell me the specific file is unfindable. But apart from that, nothing is underlined, as if there was no error in the parsing.

**Comment by bobbrow** [comment]
If you change the user setting to `"C_Cpp.intelliSenseEngine": "Tag Parser"` do goto definition and find symbols start working?

If that still doesn't work, if you [Enable Logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and reload the window you should be able to see exactly which paths we are indexing for code browsing which might help determine why we are not finding your symbols.

**Comment by n3rd4i** [comment]
I can confirm that adding `"C_Cpp.intelliSenseEngine": "Tag Parser"` to user configuration, makes the Intellisense work again!

**Comment by bobbrow** [comment]
Ok, that means that the "Default" IntelliSense was probably deadlocked and blocking the symbols request. We're working on putting out a patch for this soon since the "Default" IntelliSense engine will provide better auto-complete suggestions for you than the "Tag Parser" will.

**Comment by OrbitalHustler** [comment]
It didn't work for me, so I set the logging to full. I discovered that for every file in my project I get the following indexing error:

Unable to add file to database, error = 0x8064000a: /home/path/to/file/file.cpp

Whether the file is a .h, .c, .hpp, .cpp or anything else. 

At the end of all this I get:

Discovering files: 45815 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Parsing remaining files...
  Parsing: 0 files(s) processed

And whenever I open a .cpp file, the same error (0x8064000a) just for this file .

**Comment by OrbitalHustler** [comment]
After rebooting my computer (ubuntu 16.04) I don't have the error, and the indexing seems to work fine. But then after using some "go to", which work, I get a "Shutting down IntelliSense server: /file/path.cpp". Then I can't use "go to" or ctrl+T for about 20 secs, after which it seems to have rebooted, and I can use symbols again.

This cause some heavy lag in everything symbol related when intellisense shuts down and reboots. I'll be using "C_Cpp.intelliSenseEngine": "Tag Parser" in the meantime as it doesn't seem to make intellisense reboot.

**Comment by bobbrow** [comment]
When goto def navigates you to a file that doesn't already have IntelliSense loaded for it, then the new file will be compiled for IntelliSense and that can take a little while to finish.  There is a bug with the extension right now where, if an IntelliSense operation happens (e.g. hover tooltip) while the file is being compiled, all commands are blocked until that finishes.  Fixing that is on my list for the next release.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
