### ISSUE TITLE
Cannot launch debugger, path with Unicode characters

### ISSUE THREAD

**Issue by csasia** [microsoft/vscode-cpptools#1998]
Issue Type: <b>Bug</b>

* VS Code version: 1.23.1 (not using Insiders build)
* C/C++ extension version: 0.17.0
* OS version: Windows_NT x64 6.1.7601

Can't launch the GDB debugger if the file path of the source file contains any special Unicode characters.

This is my launch.json file:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/warmup.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/msys64/mingw64/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```
The error I got:

![captura](https://user-images.githubusercontent.com/18406325/40040881-67b3e19c-57f2-11e8-8ab8-e71b56281e16.JPG)

The problem is with the characters 'ó' and 'á' in "computación" and "imágenes". When I rename the folders, it works fine.

**Comment by pieandcakes** [comment]
@CS9031 Unfortunately this looks like a gdb issue in MinGW. I tried the same thing with logging enabled. We send the correct text but gdb does not like it when it verifies the path:
```
1: (3303) <-1005-environment-cd Z:\\Testing\\computación
1: (3303) ->&"\n"
1: (3303) ->^done
1: (3303) ->(gdb)
1: (3303) ->1005^error,msg="Z:\\\\Testing\\\\computaci\242n: No such file or directory."
```
Notice that we send `-environment-cd Z:\\Testing\\computación` but gdb's error shows `^error,msg="Z:\\\\Testing\\\\computaci\242n: No such file or directory."`

Unfortunately with a bunch of testing, I can't find a workaround for this either.

**Comment by jogo-** [comment]
The usual workaround is to use the short 8.3 path/filename.
The 8.3 filename can be obtained using the Kernel32.dll function [GetShortPathName](http://msdn.microsoft.com/en-us/library/aa364989.aspx).

@CS9031 or @pieandcakes Have you been able to try this workaround ?

**Comment by jogo-** [comment]
@CS9031 or @pieandcakes Have you even try the above workaround ?

**Comment by pieandcakes** [comment]
That fix won't work since we have to be compatible across Linux/Windows/MacOS we can't make a PInvoke call to a Windows library as it doesn't exist on Linux/Mac.

**Comment by jogo-** [comment]
I'm not sure this bug also affects Linux/Mac.

**Comment by pieandcakes** [comment]
@jogo- Yes, this is an issue on Linux also. I tested with Ubuntu 16.04 and 18.04 and can repro the same issue. It seems to be an issue within `gdb`'s MI interfacing.
```
1: (983) <-1011-break-insert -f main.cpp:9
1: (983) ->1011^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x0000000000400575",func="main(int, char const**)",file="computaci\303\263n/main.cpp",fullname="/src/args/computaci\303\263n/main.cpp",line="9",thread-groups=["i1"],times="0",original-location="main.cpp:9"}
```

**Comment by Wulgryn** [comment]
1. Win+R -> intl.cpl
 2. Administrative tab
 3. Click the Change system locale button.
 4. Enable Beta: Use Unicode UTF-8 for worldwide language support
 5. Reboot

It helped me.

**Comment by ajgustmd** [comment]
> 1. Win+R -> intl.cpl
> 2. Administrative tab
> 3. Click the Change system locale button.
> 4. Enable Beta: Use Unicode UTF-8 for worldwide language support
> 5. Reboot
> 
> It helped me.

I spent a lot of time dealing with this issue
and finally found a solution that works.
Thanks!
