### ISSUE TITLE
Debug C/C++ in Windows Container

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-cpptools#2000]
I see it is supported to debug C/C++ in Linux Container: https://github.com/andyneff/hello-world-gdb/
Do this extension also support to debug C/C++ in Windows Container?

**Comment by pieandcakes** [comment]
Are you debugging GNU c++ in the Windows container?

**Comment by formulahendry** [comment]
Yes, GNU c++ in the Windows container

**Comment by pieandcakes** [comment]
I don't see why it can't be done, but you may need to experiment with it.

You would need to use some sort of program to do a pipe connection to the container and call a version of gdb you have inside the container. I think if you are using docker, you can use the `docker` command as the pipe command.

**Comment by pieandcakes** [comment]
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md should be able to get you started with how to call it.

**Comment by AchalaSB** [comment]
Im not getting output.. I just tried C++ hello world..
Im getting debug console
"You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications."

I have installed C/C++ extension. when I tried to debug using GDB it shows path error
please help me to solve this.

**Comment by pieandcakes** [comment]
@AchalaSB Please verify that you are using the right `"type"` in your `launch.json`. You should be using `"cppdbg"` and not `"cppvsdbg"`. `"cppvsdbg"` is for debugging Visual C++ and not GNU C++.


Otherwise, please post additional information for your scenario such as `launch.json` or create a new issue.

**Comment by AchalaSB** [comment]
![screenshot 1](https://user-images.githubusercontent.com/41888986/44084585-bc92c85c-9fd4-11e8-8c34-146e9a3fd721.png)
@pieandcakes  I have used "cppdbg" only.

**Comment by AchalaSB** [comment]
Using C++(windows) 
![screenshot 2](https://user-images.githubusercontent.com/41888986/44085072-1a7695e2-9fd6-11e8-89ac-03151f209e8e.png)

**Comment by pieandcakes** [comment]
@AchalaSB You need to compile your code and put your output of your compiled code in the `program` field.

**Comment by pieandcakes** [comment]
Closing this as a stale issue. Please comment/reopen if theres additional help needed.
