### ISSUE TITLE
Mac OS - std - qualified name is not allowed

### ISSUE THREAD

**Issue by LajosNeto** [microsoft/vscode-cpptools#2001]
Hello all.
I have been facing an issue with VS Code Version 1.23.1 (1.23.1).

I have the following code snippet:

<img width="323" alt="screen shot 2018-05-16 at 00 28 26" src="https://user-images.githubusercontent.com/19560506/40096745-31985454-58a0-11e8-918f-1ab7a5971e04.png">

I keep getting the following error : 

> qualified name is not allowed

This is my current configuration:
<img width="704" alt="screen shot 2018-05-16 at 00 28 37" src="https://user-images.githubusercontent.com/19560506/40096770-54873c28-58a0-11e8-9fe9-c2e5bd405360.png">

I could find some related issues about C++17 support but none of the suggested fixes works.

Any chance that I messed up with the configurations or it is some known issue?
Thanks!

**Comment by sean-mcmanus** [comment]
I get that error when I don't have `#include <memory>` in my file. Are you using that? If you are then it sounds like something is causing the definition of unique_ptr to not be processed correctly. Your settings seems to be correct in general, assuming /usr/bin/clang exists. You could see what includes paths and defines are actually being used by temporarily setting the C_Cpp.loggingLevel to the hidden value of `"6"` and the opening a new file (see https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md ).

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.

If you update to the latest version of the C/C++ extension and your issue persists, please re-open the issue and reply with additional information that can help us investigate your issue.
