### ISSUE TITLE
setupCommands Undefined MIcommand error

### ISSUE THREAD

**Issue by prsullivan** [microsoft/vscode-cpptools#2002]
I am trying to use vscode with cpptools to debug my embedded project, and it mostly works but I would like to reset my target automatically when I launch a debug session. If i try use the "setupCommands" properties to execute these steps automatically I get the following error:

![image](https://user-images.githubusercontent.com/11800076/40124088-bac3d2ee-58f5-11e8-8f52-7e6768d51c9f.png)

What is really weird is that if I set the "ignoreFailures" property for these commands to true, and wait for debugging to start, I can then click the pause button and copy and paste the exact command into the Debug Console and it works just fine. 

Here is my launch configuration:
{
            "name": "cpp-debug",
            "type": "cppdbg",
            "request": "launch",
            "program": "C:\\\\path\\\\to\\\\myprogram.elf",
            "cwd": "${workspaceFolder}/../Debug_1_Main",
            "debugServerPath": "C:\\\\Program Files (x86)\\\\SEGGER\\\\JLink_V630i\\\\JLinkGDBServerCL.exe",
            "debugServerArgs": "-USB -device R7S721001_DualSPI -endian little -if JTAG -speed 4000 -noir -LocalhostOnly -s",
            "launchCompleteCommand": "None",
            "targetArchitecture": "arm",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\\\path\\\\to\\\\arm-none-eabi-gdb.exe",
            "miDebuggerServerAddress": "localhost:2331",
            "stopAtEntry":true,
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing"
                },
                {
                    "text": "-exec monitor halt",
                    "ignoreFailures": true
                },
                {
                    "text": "-exec monitor reset",
                    "ignoreFailures": true
                },
                {
                    "text": "-exec monitor go",
                    "ignoreFailures": true
                }
            ]
        }

The GDB server I am connecting to is provided by the debug probe manufacturer, and handles the USB and JTAG interface.

I am using version 0.17.0 of cpptools and 1.23.1 for vscode.

**Comment by WardenGnaw** [comment]
```-exec``` is used for the Debug Console, since that communicates through MIEngine. For setup commands, you want to use ```-interpreter-exec console "<command>"```

E.g.

```
{
   "text": "-interpreter-exec console \"monitor halt\""
}
```

**Comment by prsullivan** [comment]
After making the change to -interpreter-exec I am now seeing the following error when I try to launch my debugging session.

![image](https://user-images.githubusercontent.com/11800076/40176898-e4408ed6-59aa-11e8-81fb-fb5b3f786aef.png)

If I can use the "monitor" command from the Debug console, I should be able to use it from the setup commands, correct?

**Comment by prsullivan** [comment]
Okay, Some googling led me to try specifying my target in the setup commands using 
```
{
    "text": "-interpreter-exec console \"target remote localhost:2331\"",
    "ignoreFailures": false
}
```
This fixed the monitor command not supported by target issue. Now the the debug launch sequence runs fine.

**Comment by pieandcakes** [comment]
Closing as it is resolved. Please comment/reopen if that isn't the case.
