### ISSUE TITLE
Certain commands stop responding, e.g. formatting

### ISSUE THREAD

**Issue by dyspropos** [microsoft/vscode-cpptools#2007]
Issue Type: <b>Bug</b>

This is a bug that occurs randomly and I am not able to specify a sequence of steps that reproduce this reliably.

After using VSCode a while, Formatting and certain other actions stop responding (e.g. Switch header/source). It seems to coincide with opening a file open which the intellisense parser is having trouble with, but I am not entirely sure. After this begins, Formatting and other intellisense-related features stop working until I close VSCode and kill all extension processes (e.g. the Microsoft.VSCode.CPP.Extension.darwin and Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin processes) and restart VScode.

In any case, it seems related to the intellisense somehow hanging.

Extension version: 0.17.1
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.32GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/soren/luxion/|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by AndreLoddenkemper** [comment]
+1

I am experiencing something similar. When using the "Format document" shortcut, nothing happens. From that point on certain other commands stop responding, such as "Go to symbol in file ...". It just endlessly shows a loading bar, but the symbols never pop up.

edit: Just to be clear, "Go to symbol in file ..." works fine usually, there are no problems with it at all. Just once I try "Format document" it does not work at all anymore.

I gladly provide more information, if that is desired.

Extension version: 0.17.1
Vs Code Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by sean-mcmanus** [comment]
Do you know if this is a recent regression with 0.17.1? When the red flame is showing, it will block formatting and go to definition until the red flame goes away -- we plan to fix this (an issue that has existed for a long time). If it's permanently stuck, then that's a different issue. If you can attach a debugger and provide call stacks that could help...or setting the loggingLevel to "Debug" and providing any logs.

There's a known regression crash when recursive includes are used, but this sounds different.

**Comment by sean-mcmanus** [comment]
I've obtained a repro of the formatting deadlock via the chromium workspace (on Linux). It looks like clang-format is just getting stuck (killing clang-format fixes it...not sure what's causing it to hang...maybe we can just time out).

**Comment by sean-mcmanus** [comment]
We were getting stuck on clang-format for "large" files. We should have a fix available early next week.

The issue with the red flame blocking formatting is a different issue which won't be fixed till later (https://github.com/Microsoft/vscode-cpptools/issues/1928 ).

**Comment by sean-mcmanus** [comment]
We have an insider build you can try that has the fix: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.2-insiders . The official release is planned tomorrow unless we get delayed by finding more bugs.

**Comment by AndreLoddenkemper** [comment]
Thank you very much, Sean! Your updates are very much appreciated. I am sorry that I was not able to respond earlier, but it seems like you guys did not need me to :)
