### ISSUE TITLE
Default include path relative to .code-workspace file

### ISSUE THREAD

**Issue by prsullivan** [microsoft/vscode-cpptools#2009]
Is there to any way to set default include paths relative to the .code-workspace file? I am trying to use the "C_Cpp.default.includePath" propery to set common include paths for all the folders in my multi-root workspace, but some of the folders are at different depths so using "${workspaceFolder}/../../lib1" isn't resolving properly in only some of the folders.

**Comment by sean-mcmanus** [comment]
Can you use something like the following?
```
    "env": {
        "Root": "..."
    },
    "configurations": [
        {

            "includePath": [
                "${env:Root}/dir"
            ],
```

**Comment by prsullivan** [comment]
Is "env" available in for use in the workspace settings? I thought that could only be used in c_cpp_properties.json folder settings.

**Comment by sean-mcmanus** [comment]
Oops, yeah, you're right. Can you use a hardcoded path to the workspace's folder?

**Comment by prsullivan** [comment]
I could, but I would prefer not to.

**Comment by sean-mcmanus** [comment]
We support ${env:var} (uses environment variables) and ${config:var} (uses other settings.json), see https://code.visualstudio.com/docs/editor/variables-reference . I don't know of a VS Code defined variable that references the folder with .code-workspace file...it doesn't seem like we should add our own variable to support referencing that until VS Code adds such a variable.

**Comment by bobbrow** [comment]
VS Code also has a syntax for `${workspaceFolder:<folder_name>}` that we don't support yet.  Once we support it I think that would resolve this issue.  See #1774.  If you think that will work for you, let us know and we'll close this issue as a duplicate.

**Comment by sean-mcmanus** [comment]
@bobbrow I don't think that would be sufficient. A particular workspace folder is different from the workspace "root".

**Comment by prsullivan** [comment]
In my specific situation the ${workspaceFolder:<folder_name>} syntax would work. Basically I am trying set every folder included in my workspace as a default include path. Unless vscode created another environment variable for the multiroot workspace path, I think this is my best option.

**Comment by bobbrow** [comment]
@sean-mcmanus the .code-workspace usually lives in one of the folders. `${workspaceFolder:<folder_name>}` is constant, so it should be a sufficient anchor for a relative path.

**Comment by bobbrow** [comment]
Closing as duplicate of #1774

**Comment by bobbrow** [comment]
I opened a pull request for this.

**Comment by sean-mcmanus** [comment]
@prsullivan 0.17.3 supports ${workspaceFolder:folderName}.

**Comment by prsullivan** [comment]
Thank you!
