### ISSUE TITLE
VSCode C IncludePath not resolved.

### ISSUE THREAD

**Issue by CoconutJJ** [microsoft/vscode-cpptools#2014]
Hi there, I'm having trouble getting the VSCode to resolve my C include path

I've included all the paths to the files I have referenced, but I keep getting the following error message in the problems console:  "could not open source file linux/kernel.h (no directories in search list)"

Here are all my include headers:

```
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <asm/current.h>
#include <asm/ptrace.h>
#include <linux/sched.h>
#include <linux/cred.h>
#include <asm/unistd.h>
#include <linux/spinlock.h>
#include <linux/semaphore.h>
#include <linux/syscalls.h>
```

```
{
    "configurations": [
        {
            "name": "Linux",
            "browse": {
                "path": [
                    "/usr/lib/modules/4.16.9-1-ARCH/build/include/",
                    "/usr/include/",
                    "/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include-fixed",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "/usr/lib/modules/4.16.9-1-ARCH/build/include/",
                "/usr/include/",
                "/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include-fixed",
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}`
```

**Comment by bobbrow** [comment]
It looks like you have `/usr/bin/clang` listed as your compiler (in `compilerPath`), but also have gcc system headers listed.  My guess is that the extension found clang and auto-populated that for you when you actually wanted gcc.

Can you try changing `compilerPath` to the path to your gcc compiler?  You should also be able to remove the system include paths from `includePath` and `browse.path` once you do that.

**Comment by CoconutJJ** [comment]
Hi thanks for the reply
My configurations now look like this:

```
{
    "configurations": [
        {
            "name": "Linux",
            "browse": {
                "path": [
                    "${workspaceFolder}"

                ], 
                "limitSymbolsToIncludedHeaders": false
            },
            "includePath": [
                "${workspaceFolder}/**"

                
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

However I'm still getting the problems listed here: https://imgur.com/a/dRgfwaW

I double checked that these files do actually exist on the system using `find -name "[myfilename]"`
and that their paths were included in the configuration as per the original post

**Comment by sean-mcmanus** [comment]
You're using 0.17.1? Can you set your logging level to "Debug" and see if the include paths we're sending look correct? Are the asm and linux folders under your workspace?

**Comment by sean-mcmanus** [comment]
This could be due to bug https://github.com/Microsoft/vscode-cpptools/issues/2019 . I would avoid using recursive includes until we release an update with the fix or going back to using 0.17.0 ( https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.0 ).

**Comment by sean-mcmanus** [comment]
We have an insider build you can try that may have the fix: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.2-insiders . The official release is planned tomorrow unless we get delayed by finding more bugs.

**Comment by CoconutJJ** [comment]
Sorry for the late reply I've been a bit busy..

I think the Insider Build fixed the issue!! At least its working for me now :)

Both the path resolution and the Go to Definition option for include headers seem to work.

Intellisense Auto Complete seems to work too now.

I'll leave my final configurations here:

```
{
    "configurations": [
        {
            "name": "Linux",
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "/usr/lib/modules/4.16.9-1-ARCH/build/arch/x86/include/",
                    "/usr/lib/modules/4.16.9-1-ARCH/build/include/",
                    "/usr/lib/modules/4.16.9-1-ARCH/build/arch/x86/include/generated/"
                ], 
                "limitSymbolsToIncludedHeaders": false
            },
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/lib/modules/4.16.9-1-ARCH/build/arch/x86/include/",
                "/usr/lib/modules/4.16.9-1-ARCH/build/include/",
                "/usr/lib/modules/4.16.9-1-ARCH/build/arch/x86/include/generated/"

                
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ], 
    "version": 4
} 
```
