### ISSUE TITLE
I have libraries in /opt/ros/lunar, how can I add them in include path for intellisense ?

### ISSUE THREAD

**Issue by SkyRiderMike** [microsoft/vscode-cpptools#2017]
OS: windows subsystem on Linux , Ubuntu.

Windows OS: Windows 10 17134.48

Visual Code Version: 1.23.1

Cpp Extension Version:  0.17.1

I have libraries in /opt/ros/lunar, how can I add them in include path for intellisense ?

**Comment by bobbrow** [comment]
For WSL configs, you are allowed to use linux-style paths in **c_cpp_properties.json**.  Just add `/opt/ros/lunar` to the `includePath` (make sure you also set `intelliSenseMode` to `clang-x64` and `compilerPath` to `/usr/bin/gcc` or whatever compiler you are using)

**Comment by bobbrow** [comment]
See also: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md
