### ISSUE TITLE
@Symbol doesn't map to correct location in source file

### ISSUE THREAD

**Issue by asthana86** [microsoft/vscode-cpptools#202]
**Steps to repro:**
1. Open C/C++ folder in Visual Studio Code
2. Let the indexing complete 
3. Format C/C++ document
4. Bring up command-pallete, and list symbols
5. Not all symbols map or direct to correct file source locations.

**Comment by sean-mcmanus** [comment]
Currently you have to save your changes after an edit (e.g. formatting) or "stuff" doesn't update.

**Comment by sean-mcmanus** [comment]
The saving requirement for symbol updating has been fixed with 0.19.0.
