### ISSUE TITLE
repeated "#include errors detected" but intellisense works and can find the files

### ISSUE THREAD

**Issue by kennyadams** [microsoft/vscode-cpptools#2020]
Everything worked fine but suddenly vs code shows green squiggly lines under include statements and on clicking on the yellow bulb then selecting add "/usr/include....." to path, it gets fixed but again shows the same green line after a few seconds.

```
{
    "configurations": [
        {
            "name": "Linux",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/c++/8.1.0"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
The root cause is most likely a regression caused by https://github.com/Microsoft/vscode-cpptools/issues/2019, which we plan to release a fix for soon.

**Comment by sean-mcmanus** [comment]
We have an insider build you can try that may have the fix: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.2-insiders . The official release is planned tomorrow unless we get delayed by finding more bugs.

**Comment by sean-mcmanus** [comment]
Let us know if you're still having problems with 0.17.3 (we fixed the known issues were able to repro, but there could be others).

**Comment by kennyadams** [comment]
Unfortunately, it's still not fixed. I downgraded to 0.17.1 where its working fine.

**Comment by sean-mcmanus** [comment]
You mean you downgraded to 0.17.0, right? 0.17.2 was only released as an insider build. It's possible symbolic links might be causing problems.

**Comment by sean-mcmanus** [comment]
It tried to repro the issue with symbolic links but it worked...so I don't think we'll be able to fix this until we get enough repro details to figure out the cause. It could be a "by design" issue with recursive includes causing the wrong system header to be used due to a name mismatch. You can set the loggingLevel to "Debug" to see which includePaths we end up using (in the C++ section in the Output pane).

**Comment by sean-mcmanus** [comment]
Ah, I found a repro -- yeah, the required paths are not being added in the case `#include <folder/symlink/file.h>` (path to folder is omitted).

**Comment by sean-mcmanus** [comment]
Oops, false alarm -- my symlink was pointing to an unintended target. I'm not able to repro the bug still.

**Comment by kennyadams** [comment]
This is the error message in 0.17.3
![40464460-03d5a504-5f39-11e8-9294-7c57d60da29a](https://user-images.githubusercontent.com/39486486/40464709-663bbee4-5f3a-11e8-8d5b-bceaa041b138.jpg)

and this one is without the error(same config, same code) in 0.17.1
![image](https://user-images.githubusercontent.com/39486486/40464533-625a886a-5f39-11e8-861f-f50fe1684db2.png)

**Comment by bobbrow** [comment]
Can you set `"C_Cpp.loggingLevel": "Debug"` and then close and reopen the .cpp file?  The extension will log the resolved include path and defines in the Output window (select the "C/C++" filter to see our extension's output).  Then please share the logs or let us know if the include path looks correct.

**Comment by kennyadams** [comment]
Here's the log file 
[output_cpp.txt](https://github.com/Microsoft/vscode-cpptools/files/2033937/output_cpp.txt)

**Comment by bobbrow** [comment]
Well, that's odd. There are no includes listed.  What do you see when you run `/usr/bin/gcc -v -E -x c++ /dev/null`?  Are there any include paths listed?

**Comment by kennyadams** [comment]
Here's the output 
[output.txt](https://github.com/Microsoft/vscode-cpptools/files/2036276/output.txt)

**Comment by sean-mcmanus** [comment]
I just hit the repro with /usr/bin/gcc on Windows/WSL. I'll investigate...

**Comment by sean-mcmanus** [comment]
False alarm. I don't have a repro. I was trying to use optional when it didn't exist.

**Comment by bobbrow** [comment]
Just a shot in the dark... Do all of your code files have this problem?  Or is this a new code file that hasn't been saved since the `#include` lines were added?  It's possible that the reason the include path is empty is because recursive includes tries to optimize the list of includes by removing the ones that aren't necessary.

You can also try removing the `/**` from your `includePath` and see if that fixes the behavior.

**Comment by LinAGKar** [comment]
I'm having similar problems in 0.17.3, and for me removing the line with `/**` fixed it for my includes with <>. However, I have an include with "", which is still not found, even tough the includePath includes the directory it's in, and that directory now is shown in the debug output.

**Comment by bobbrow** [comment]
@LinAGKar, the auto complete for includes is done using a combination of the `browse.path` and `includePath` properties.  If the header is not under any of the folders listed in the `browse.path` then our extension doesn't know about it and can't suggest it.  If it is under one of those paths, then we should suggest it if it lives under one of the `includePath` folders.  If both of these conditions are true for you, then please open a new issue and give us as much detail about the problem as you can.

**Comment by kennyadams** [comment]
Removing the `/**` fixed it for me too. Thanks a lot.
