### ISSUE TITLE
Using Pipe transport  to build task via g++ in WSL

### ISSUE THREAD

**Issue by Agarwal-Nikhil** [microsoft/vscode-cpptools#2021]
How to use Pipe transport  to build task via g++ in WSL?  What is the syntax of the tasks.json with pipe transport? (Reference: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md)

**Comment by pieandcakes** [comment]
@Agarwal-Nikhil tasks.json is supported by VS Code, not by the extension. Please ask on [their issues page](https://github.com/microsoft/vscode). The example reference is for the debugger only.
