### ISSUE TITLE
Problem while compiling with external libraries.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2026]
So I have trouble compiling this code:

    #include <GL/gl.h>
    #include <GL/glu.h>
    #include <GLFW/glfw3.h>
    #include <iostream>

     using namespace std;

        int main( int argc, char * argv[] )
        {
            GLFWwindow* window = glfwCreateWindow(800, 600, "LearnOpenGL", NULL, NULL);
            if (window == NULL)
            {
                std::cout << "Failed to create GLFW window" << std::endl;
                glfwTerminate();
                return -1;
            }
            glfwMakeContextCurrent(window);
        }

It gives me:

    Executing task: g++ -g -lopengl32 -lglu32 -lglfw3 main.cpp <
    C:\Users\damia\AppData\Local\Temp\ccSvn9zL.o: In function `main':
    B:\REPO\c++/main.cpp:11: undefined reference to `glfwCreateWindow'
    B:\REPO\c++/main.cpp:15: undefined reference to `glfwTerminate'
    B:\REPO\c++/main.cpp:18: undefined reference to `glfwMakeContextCurrent'
    collect2.exe: error: ld returned 1 exit status
    The terminal process terminated with exit code: 1

    Terminal will be reused by tasks, press any key to close it.

And here are the 
<b>tasks.json: </b>

    {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "echo",
                "type": "shell",
                "command": "g++",
                "args": [
                    "-g","-lopengl32", "-lglu32","-lglfw3","main.cpp"
                ],
                "group": {
                    "kind": "build",
                    "isDefault": true
                }
            }
        ]
    }
and <b>c_cpp_properties.json:</b>

    {
        "configurations": [
            {
                "name": "Win32",
                "browse": {
                    "path": [
                        "${workspaceFolder}",
                        "B:\\MinGW\\lib",
                        "B:\\MinGW\\lib\\gcc\\mingw32\\6.3.0",
                        "B:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include\\c++"
                    ],
                    "limitSymbolsToIncludedHeaders": true
                },
                "includePath": [
                    "${workspaceFolder}/**",
                    "B:\\MinGW\\include"
                ],
                "defines": [
                    "_DEBUG",
                    "UNICODE",
                    "_UNICODE"
                ],
                "compilerPath": "B:\\MinGW\\bin\\gcc.exe",
                "cStandard": "c11",
                "cppStandard": "c++17",
                "intelliSenseMode": "clang-x64"
            }
        ],
        "version": 4
    }

How to make this work ?

**Comment by Borderliner** [comment]
I don't see glfw library path declared anywhere. Maybe pass `-L/path/to/glfw/lib` as a compiler argument?

**Comment by ghost** [comment]
My glfw library is in B:\\MinGw\\lib directory, which is added to "path" in c_cpp_properties.json

**Comment by pieandcakes** [comment]
@Horsetaur AFAIK the `path` property specified in c_cpp_properties.json is for language service and not compilation. Try specifying it in your `task.json`?

**Comment by ghost** [comment]
How to do so?

**Comment by pieandcakes** [comment]
@Horsetaur Using @Borderliner 's suggestion by adding the compile argument of `-l` and the path to your glfw library.

**Comment by ghost** [comment]
Like that ? 
-l/B:/MinGW/lib
That ^ gives error, and if I do that:
"-L/B:/MinGW/lib"
Then it still produces same error as on the beggining

**Comment by pieandcakes** [comment]
why do you have a `/` between `-L` and `B:`? If that is where it is, you should be able to do `-lB:\\MinGW\\lib\\` but you need to link a library not a folder.

**Comment by ghost** [comment]
The result I'm getting:
      `b:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lB:\MinGW\lib`
      `collect2.exe: error: ld returned 1 exit status`
      `The terminal process terminated with exit code: 1`

**Comment by Borderliner** [comment]
@Horsetaur `-l` and `-L` are different. `-l` specifies the name of the library, `-L` specifies the path to the library. Generally, you specify `-L/path/to/lib` and then `-lmylib`.

**Comment by ghost** [comment]
@Borderliner 
Accordingly to this I've changed inside tasks.json to:
          ```  "args": [
                "-g","-lopengl32", "-lglu32","-LB:\\MinGW\\lib","-lglfw3","main.cpp"
            ],```

And this still gives undefined reference as on the beggining

**Comment by pieandcakes** [comment]
@Horsetaur you may find it faster to figure this out by compiling from a command prompt until you figure it out and then updating your `task.json` accordingly. This seems to be an issue with command syntax and not the extension so I'm marking it as `external`

**Comment by ghost** [comment]
@pieandcakes 
Using code below in command prompt:
`g++ main.cpp -IB/MinGW/lib -lopengl32 -lglu32 -lglfw3 -lgdi32 -o Test.exe`
Gives no errors and builds the file successfuly.

**Comment by pieandcakes** [comment]
Ok. If you take those same args and put them in the same order into your launch.json it should work too.

**Comment by ghost** [comment]
@pieandcakes you're right, it worked, hilararious.
