### ISSUE TITLE
Intellisense doesn't work at all

### ISSUE THREAD

**Issue by trollcop** [microsoft/vscode-cpptools#203]
1/ have folder open in code
2/ folder has lib\stuff\somefiles.h defining struct junk_t { bla bla };
3/ folder root has main.c
4/ int main(void) {
5/     junk_t bar;
6/    bar.| pressing dot shows a million completion options but nothing related to the contents of struct junk until I actually type most of the identifier at which point I might as well just finish typing it.

**Comment by laoshaw** [comment]
same here, no auto complete what-so-ever on ubuntu 16.04, could not even detect the default header files such as stdio.h etc. need wait and try cpptools later.

**Comment by greazer** [comment]
We believe that the most egregious aspects of this should be mostly resolved with the latest release of the extension. There was a time when we were showing both textmate and CPP extension completion items at the same time. This no longer occurs. That being said, there is still planned work to make the CPP completion items more intelligent in the future.
