### ISSUE TITLE
#include "" completion doesn't show files in the current directory if the path isn't in the includePath

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2031]
Without recursive includes, test.cpp and test.h are in the same folder, not in includePath, the `#include ""` won't show test.h in the completion list in test.cpp.

**Comment by momadacoding** [comment]
When the .h file and .cpp file is in the same folder, the .cpp file could not find the .h file. 
Maybe the same as https://github.com/Microsoft/vscode-cpptools/issues/994
I use the code in https://github.com/jjuiddong/Introduction-to-3D-Game-Programming-With-DirectX11 , and add the                 "${workspaceFolder}/Common/**" to the includePath
Anyway to add the current folder to includePath ?

**Comment by sean-mcmanus** [comment]
This bug is just for #include completions. The IntelliSense engine already adds the current folder automatically so any file that uses #include "header.h" should find header.h if it's in the same directory as the source file. Recursive includes is only required if header.h is in a subfolder. It's possible that some required defines are missing. Which header file can't be found? It would be better if you opened a new issue for this.
