### ISSUE TITLE
Downloading 1/3: C/C++ language components (Windows)

### ISSUE THREAD

**Issue by GMHDBJD** [microsoft/vscode-cpptools#2032]
![image](https://user-images.githubusercontent.com/35025882/40402424-21388398-5e7e-11e8-9f61-a182e0acd8a3.png)
whether I install in Extension or Install from VSIX it goes wrong. I lives in China.

**Comment by bobbrow** [comment]
You can download the "offline" installer from our [releases page](https://github.com/Microsoft/vscode-cpptools/releases).  Get the one that matches your operating system then use the "Install from VSIX" command in VS Code.  It will bypass this step that is getting stuck for you.

**Comment by GMHDBJD** [comment]
![image](https://user-images.githubusercontent.com/35025882/40404071-64aa5e58-5e88-11e8-9f24-b21394ddf626.png)
I have tried it,but still failed

**Comment by GMHDBJD** [comment]
![image](https://user-images.githubusercontent.com/35025882/40404193-17506cfa-5e89-11e8-9634-6978e117412f.png)

**Comment by GMHDBJD** [comment]
![image](https://user-images.githubusercontent.com/35025882/40404224-3b6c5978-5e89-11e8-8afe-b6d081695f9e.png)
It appear after I install from VSIX

**Comment by bobbrow** [comment]
Which vsix did you download?  It looks like you are on Windows, so you should download [this one](https://github.com/Microsoft/vscode-cpptools/releases/download/v0.17.3/cpptools-win32.vsix).

If you download this "offline" VSIX and install it, it won't try to download dependencies because they are already packaged in.

**Comment by GMHDBJD** [comment]
![image](https://user-images.githubusercontent.com/35025882/40404930-ed2b9d56-5e8c-11e8-927e-3ca89907e6b8.png)
![image](https://user-images.githubusercontent.com/35025882/40404937-f4e96118-5e8c-11e8-88de-d5b9a0812138.png)
![image](https://user-images.githubusercontent.com/35025882/40404949-05f0a872-5e8d-11e8-9317-281b663e6207.png)
I don't know why it still failed...

**Comment by bobbrow** [comment]
I bet that VS Code still has the old 0.17.3 extension installed and isn't actually installing your VSIX.  They really need to add a warning message or something for this.

Can you delete the `%userprofile%\.vscode\extensions\ms-vscode.cpptools-0.17.3` folder and retry installing the "offline" VSIX.
Also, if you see a `.obsolete` file in `%userprofile%\.vscode\extensions`, open it and check to make sure that there isn't an entry for our extension in there.

**Comment by sean-mcmanus** [comment]
Yeah, after an uninstall, you need to close/reopen VS Code in order for the uninstall to actually work. I opened an issue in VS Code in regards to this, but that last I heard they closed it until they heard more user feedback.

**Comment by gongmeteor** [comment]
on Ubuntu 16.04，　I downloaded the 0.17.5 VSIX and try to install it from local file, the installation seems endless, where can I check install details, or if something goes wrong?

**Comment by sean-mcmanus** [comment]
@gongmeteor 0.17.5 isn't being released until tomorrow. Do you mean 0.17.4 or 0.17.5-insiders? What URL are you using for the .vsix?

**Comment by gongmeteor** [comment]
@sean-mcmanus , it's 0.17.5-insiders, I also tried 0.17.4 which is downloaded from URL https://github.com/Microsoft/vscode-cpptools/releases/download/v0.17.4/cpptools-linux.vsix, seems exactly the same, the installation never finished and no warning or error cue found. I do the same experiment on another computer, still the same.

**Comment by gongmeteor** [comment]
@sean-mcmanus , I install anaconda3 complete before VSCode, I remember something related to VSCode when I install anaconda3, Anaconda Extension Pack and python extension are founded t be already installed right after VSCode installation.

**Comment by gongmeteor** [comment]
I solved the problem following steps:
1, start up VS Code with command: sudo code --user-data-dir /home/XXX/VSCode
2, install cpptools and other extensions needed, then close VS Code
3, restart normally with command: code
thanks!

**Comment by DioTheDev** [comment]
Installing from VSIX on an offline computer still attempts to download the dependencies. 

Using this vsix: https://github.com/Microsoft/vscode-cpptools/releases/download/0.21.0/cpptools-win32.vsix

**Comment by sean-mcmanus** [comment]
@DioTheDev I tried it out, and it didn't try to download dependencies. Why do you think it's trying to download dependencies? If your C_Cpp.updateChannel is set to "Insiders" then we'll attempt to download the latest insiders instead. Is that what you're seeing? We also attempt to download a .json file, but it shouldn't block anything if that fails.

**Comment by DioTheDev** [comment]
![image](https://user-images.githubusercontent.com/48537897/54396777-3d950e80-4708-11e9-8ac3-f0d23f8dc309.png)

I am seeing this after installing from the vsix at the link I posted earlier. Updates have been set to none with "update.mode": "none"

The result:

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'ClangFormat (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Visual Studio Windows Debugger'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: end of central directory record signature not found

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.

**Comment by sean-mcmanus** [comment]
The offline installer should install with an install.lock file, which we check to determine if we need to download the dependencies. Could that file be deleted somehow? Do you see any errors when you use Toggle Developer Tools?

**Comment by ghost** [comment]
![tt](https://user-images.githubusercontent.com/45459546/57092391-8b57eb80-6d35-11e9-91a0-2b07035c87bb.png)
I 
Did i follow the instructions as still having errors? Can you help me ?

**Comment by sean-mcmanus** [comment]
@18020523 Double-click doesn't work -- you need to load it in VS Code via the Install From .vsix command.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.

**Comment by deepakmn** [comment]
My VS Code version is 1.43.2 and during installation of version 0.26.3 of cpptools-win32.vsix, I get the following error:
 
![image](https://user-images.githubusercontent.com/29940558/77662618-1cfdc680-6fa2-11ea-8dd1-7031ff79756e.png)

Attaching the install log:
[cpptools-win32-0_26_3install-log.txt](https://github.com/microsoft/vscode-cpptools/files/4388053/cpptools-win32-0_26_3install-log.txt)

**Comment by sean-mcmanus** [comment]
@deepakmn Double-clicking the vsix will cause Visual Studio to try to try to install it (and fail). You'll need to follow the instructions on the release page:

![image](https://user-images.githubusercontent.com/19859882/77709600-df407400-6f88-11ea-83a8-2bca9a9c3657.png)
