### ISSUE TITLE
Ctrl + Click on include file doesn't disambiguate between files of the same name

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#2033]
Issue Type: <b>Bug</b>

- Unzip [test.zip](https://github.com/Microsoft/vscode-cpptools/files/2030139/test.zip) and open the test folder in VSCode
- Open test.cpp
- Ctrl + Click "header.h" in the #include <folder0/header.h> directive

Actual: Opens a preview tab that shows both folder0/header.h and folder1/header.h
Expected: Opens folder0/header.h as the include directive states

It seems like files are selected only by name and do not take into account the relative path. This is inconvenient when using the multiple workspaces feature where several folders might have a 'debug.h' or something of the likes.

Extension version: 0.17.3
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sean-mcmanus** [comment]
Yeah, this is a known issue that has existed "forever" (see https://github.com/Microsoft/vscode-cpptools/issues/1253 ). Maybe we can finally fix it soon.

**Comment by sean-mcmanus** [comment]
Our next release is expected to have the fix. There was a related bug in that the symbols for the wrong file could end up being parsed (for symbols) due to the path not being taken into account.

**Comment by azydevelopment** [comment]
Thanks. I'll take a look when it's available.

**Comment by sean-mcmanus** [comment]
Fixed with 0.17.4.

**Comment by azydevelopment** [comment]
Confirmed working with the repro case :).

Thanks guys. Much appreciated as always.
