### ISSUE TITLE
Linter does not do well with std::optional

### ISSUE THREAD

**Issue by kghose** [microsoft/vscode-cpptools#2037]
Meta
-----
- macOS HighSierra
- VSCode 1.23.1
- cpptools 0.17.3

Problem
--------
C++ allows us to `return foo` where `foo` is of type `Foo` from a function that returns type `std::optional<Foo>`. The cpptools linter however marks this with red and states that 
`no suitable user defined conversion ... exists`

Thanks!

**Comment by sean-mcmanus** [comment]
I'm able to repro the issue.

**Comment by sean-mcmanus** [comment]
I'm not able to repro this with 0.17.7 or https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.8-insiders . Do you have any more repro details, such as what compilerPath and optional library version you're using?

**Comment by kghose** [comment]
@sean-mcmanus Hi! I forgot to update - looks like this thing has been fixed for a while: I haven't had any issues for about a month now. I'm on 2018-07-11T15:27:07.646Z. Thanks!
