### ISSUE TITLE
When debugging by GDB, it mistook the path of msys bash as the path of Windows CMD.

### ISSUE THREAD

**Issue by napasa** [microsoft/vscode-cpptools#2038]
Hi, Maintainer. I encounter a Folder identification error. 
Under the bash of **C:\\msys64\\usr\\bin\\bash.exe**, my cpp file path is **/home/no6fo/project/learn/cpp/hello.c**, and the path of the file is **C:\msys64\home\no6fo\project\learn\cpp\hello.c** under Windows CMD.  when I debug with cpptools, GDB seems to start from Windows CMD, and report error: Unable 'hello.c': File not found (file:///home/no6fo/project/learn/cpp/hello.c), and if I set up a hello.c file under C:\home\no6fo\project\learn\cpp\, then GDB can work normaly.

Workspace Settings:
```
{
"terminal.integrated.shell.windows": "C:\\msys64\\usr\\bin\\bash.exe",
"terminal.integrated.shellArgs.windows": ["--login", "-i"],
"terminal.integrated.env.windows":
 {
        "MSYSTEM": "MINGW64",
        "CHERE_INVOKING":"1"
  }
}
```

launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(gdb) Launch hello",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/msys64/usr/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

**Comment by pieandcakes** [comment]
@napasa You need to setup `"sourceFileMap"` as I assume you compiling in your MSYS2 command window. The documentation is [here](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md) at the bottom. 

Specifically, it sounds like you need `"sourceFileMap": { "/home/no6fo/project": "C:\msys64\home\no6fo\project" }`.
