### ISSUE TITLE
Updating Intellisense Indefinitely....

### ISSUE THREAD

**Issue by ronitt** [microsoft/vscode-cpptools#2039]
I am having this issue on Windows 10 64-bit. The Microsoft.VSCode.CPP.IntelliSense.Msvc process is at 0% and the flame icon is visible in VSCode reporting that it is updating and seems to be doing so indefinitely. In my settings, both includePath settings are:

- "C_Cpp.default.includePath": null
- "C_Cpp.default.systemIncludePath": null

I am working in a fairly large project, but the process seems to have given up parsing entirely.

**Comment by bobbrow** [comment]
Is the Microsoft.VSCode.CPP.Extension.exe process using any CPU?  Do you have a `c_cpp_properties.json` file or are you using the defaults?  If you are using defaults and have the settings values mentioned above, the extension is using the new recursive includePath feature that we just enabled by default and it may not be performing well on your project.

You can disable it by either:
* Generating a `c_cpp_properties.json` file (with the "Edit Configurations..." command) and then removing the `/**` from the end of the path in the `includePath` property, or
* Setting `"C_Cpp.default.includePath": "${workspaceFolder}"`

though neither of these options will give you the correct `includePath` for your project -- that will need to be done manually as before.

**Comment by ronitt** [comment]
Well that seems to have fixed it! I opened my "c_cpp_properties.json" file and deleted the "/**" from the end and it did the trick. I think the process had too much of a backlog of files to parse, but it seems to be working fairly well now even if all project files are not being parsed. 

For the sake of completeness and to aid in diagnosing this problem for others, to answer your question, the Microsoft.VSCode.CPP.Extension process seemed to be working fine and was using about 15% cpu and seemed to be running normally.

Thank you very much!
