### ISSUE TITLE
Feature Request: Custom user platforms

### ISSUE THREAD

**Issue by newbrain** [microsoft/vscode-cpptools#204]
**Background**
VSCode, with the cpptools and the native debug extensions, is a pleasant environment for embedded development. Unfortunately, no explicit support for platforms outside Mac, Windows and Linux is provided.
To have intellisense-like code assist, one of the predefined platforms has to be (ab)used with embedded specific settings. If more than one embedded target is in use, this is far from an ideal situation.

**Feature Request**
Allow the user to create and customize extra platforms, supporting board specific include paths (in _c_cpp_properties.json_):

``` json
       {
            "name": "MSP432",
            "includePath": [
                "C:/Ti/driverlib",
                "C:/Ti/CMSIS"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        }
```

**Comment by reporter123** [comment]
This would help me as well since my distro does something non-standard with header files.

**Comment by sridmad** [comment]
You should be able to create a config with any name. We have to code to detect the platform that VSCode is running on and select it by default.

To select the config of your choice, 
click on the config name on the status bar (bottom right corner) or Hit F1 (to drop down command windows) and type >C/Cpp: Select a Configuration to list the available configuration. 
Select the required config.

**Comment by newbrain** [comment]
Thanks for your answer!
I appreciate the wonderful work that's being done with Code and this extension.

Yes, I can do that, but the support is only partial.
I have defined a "STM32F7" platform:
- The include paths are actually recognized
- I have a warning stating that this is not an accepted value. This is annoying.
- There's no way (that I found!) to have the build task options linked not (only) to the build environment -"windows", "linux", "osx"- but to the target platform. But probably this is better addressed to VS Code itself, rather than this extension?

See the attached screenshot.
![vscodecustenv1](https://cloud.githubusercontent.com/assets/17814222/18509991/fa1196ca-7a7b-11e6-8842-a846c0f460b0.PNG)

**Comment by sean-mcmanus** [comment]
The warning about unaccepted values is already fixed (for our next release).

What are build task options?

**Comment by newbrain** [comment]
Good to hear! Thanks for the information.

In the task.json file, one has the possibility to define different behaviors  according to the [build host operating system](http://code.visualstudio.com/docs/editor/tasks#_operating-system-specific-properties).

A nice feature would be to have also target specific options sets: it is quite common, for example, that I can write the same code for a ARM M1, M4 or M7 core (with very little conditional compilation) but the build command options and libraries will be differ.
Having the possibility to specify per target options (with the same tag used in c_cpp_properties.json) would help recompile the code by just switching the config (and the same would work for other defined tasks, as debugging and target flashing).

I don't know where the line is drawn between the C/C++ extension and the core Code, so I might be barking up the wrong tree...assuming I have something to bark for!

Once again, thanks for the support.

**Comment by sean-mcmanus** [comment]
All the "Tasks: " commands are controlled by VS Code itself and our extensions doesn't have any way to modify that behavior currently. As a workaround, you could create target specific tasks with different names, e.g. "taskName": "build ARM M1".

**Comment by newbrain** [comment]
Thanks for your answer and your time.
I think Microsoft's teams are doing an excellent work with VS Code, its extensions, and the attitude towards the users.

I will close the item, then, and decide whether to bring it to VS Code.

As for the workaround, that's exactly what I am doing!
So, all in all, it's just a minor annoyance.

**Comment by sean-mcmanus** [comment]
With 0.9.2, extra platforms can be added without giving squiggles and it'll default to the last one if there are >3 platforms. Let us know if there are other problems.
