### ISSUE TITLE
intellisense_client::shutdown stuck in infinite loop in Microsoft.VSCode.CPP.Extension.exe

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2043]
If you notice CPU usage stuck at 100% and intellisense_client::shutdown in on the call stack we have a fix for that.

I'm not sure how common this is because I've never reproed it (a user sent us a dmp). UPDATE: I reproed it later on (unknown steps).

**Comment by bobbrow** [comment]
The workaround is to disable recursive includes for your folder.

You can do this by running the "Edit Configurations..." command and removing the `/**` from the entry in the `includePath`.

**Comment by bobbrow** [comment]
If your workspace folder does not have a **c_cpp_properties.json** in the **.vscode** folder, then you can also work around this issue by adding `"C_Cpp.default.includePath": [ "${workspaceFolder}" ]` to your settings.
