### ISSUE TITLE
(lldb) support for multiline formatters

### ISSUE THREAD

**Issue by weshardee** [microsoft/vscode-cpptools#2045]
lldb supports multiline summaries like so:

```
type summary add --summary-string "test\ntest\ntest" some_type
```

But this breaks the debugging tools in VSCode, notably crashing the entire "Variables" pane. When it encounters the type in question, I see a message like this in the debug console, which isn't very useful:

```
test",type="some_type",thread-id="1",has_more="0"
```

It would be great if the debugging tools failed more gracefully here, and even better if they supported the multiple line summary somehow.

**Comment by pieandcakes** [comment]
@weshardee If you can provide a code sample and some instructions, I'll take a look but I suspect it is because it is changing the format that `lldb-mi` returns the data to us so we can reformat it for the UI and we aren't handing it gracefully.
