### ISSUE TITLE
Warning/error messages don't update their line numbers after formatting

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#205]
Format the code below and the green line renders on the wrong line:

char__ = "'""/_";
# include <stdio.h>
# define m 21
# define o(l, k) for(l=0; l<k; l++)
# define n(k) o(T, k)

There are other cases where the green line renders wrong too. The message doesn't update after any edits, but the line doesn't get re-drawn. Maybe we can clear these warnings after an edit or update it with the correct line numbers.

**Comment by sean-mcmanus** [comment]
Also, things like "Go to definition" also don't update and can go to the wrong location.

**Comment by sridmad** [comment]
Dupe of #202
