### ISSUE TITLE
Scan task with Ninja shows wrong problems directory

### ISSUE THREAD

**Issue by phreppo** [microsoft/vscode-cpptools#2051]
I'm using [Ninja](https://ninja-build.org/) build system to build a C project. I'm using the extension [C/Cpp](https://github.com/Microsoft/vscode-cpptools). When i build the project with the Scan task, the extension shows the warnings in the problems panel, but the paths to the files are wrong: they point to upper directories in the file system tree.

- VSCode Version: 1.23.1
- OS Version: Ubuntu 17.10 x64
- C/Cpp extension version: 0.17.3

Steps to Reproduce:

1. Go to the ${workspaceRoot} directory of a C project. I'm actually workign on [this](https://github.com/parof/CGen/tree/8a51fc3ab0e6678205fae0bdef0145a346b5d5f7)
2. Create the build directory with [Meson](https://mesonbuild.com/): `meson build`
3. Configure the Scan task (as [here](https://github.com/parof/CGen/blob/8a51fc3ab0e6678205fae0bdef0145a346b5d5f7/.vscode/tasks.json))
```
        {
            "label": "Scan",
            "type": "shell",
            "command": "ninja scan-build",
            "group":"build",
            "options": {
                "cwd": "${workspaceRoot}/build"
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared"
            },
            "problemMatcher": {
                "base":"$gcc",
                "fileLocation" : ["relative", "${workspaceRoot}/build"]
            }
        }
```
4. Launch Scan task
5. Look at the output: the warnings should point to files in the ${workspaceRoot} directory, but actually for me they point to some other locations. Example:  

Console output with warnings:
![console3](https://user-images.githubusercontent.com/32315224/40624290-038c1030-62ac-11e8-9a2f-5dd4e9951f54.png)

Problems panel(pointing to the wrong directory, because my project is located in `/home/phreppo/CGen`):
![problems3](https://user-images.githubusercontent.com/32315224/40624285-fe200304-62ab-11e8-8db3-43c17d5c4d97.png)

Dialog window that appears when I click on one warning. In this particular example the file that should be opened is `/home/phreppo/CGen/test/type.c`
![window3](https://user-images.githubusercontent.com/32315224/40624281-f955a748-62ab-11e8-9c78-03f1d4ef50a2.png)

It's curious, because with the task Build the problems points to the right directory, and they have the same `fileLocation` property. Here's the Build task: 
```
        {
            "label": "Build",
            "type": "shell",
            "command": "ninja",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "cwd": "${workspaceRoot}/build"
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared"
            },
            "problemMatcher": {
                "base":"$gcc",
                "fileLocation" : ["relative", "${workspaceRoot}/build"]
            }
        }
```

Does this issue occur when all other extensions are disabled?: Yes

Reopening in Microsoft/cpp-tools from a similar [one](https://github.com/Microsoft/vscode/issues/50503), but now Build task is ok: the problem is the Scan task.

**Comment by bobbrow** [comment]
Looking at your output, `/home/src/type.c` looks like the correct result of combining `/home/phreppo/CGen/build` and `../../../src/type.c`.

It would appear that the `fileLocation` for the Scan task should have been `/home/phreppo/CGen/build/meson-private/tmpsm350_09` in order to resolve the relative path to `/home/phreppo/CGen/src/type.c`.  Am I missing something?

**Comment by phreppo** [comment]
Setting the problem matcher for the Scan task as:
```
            "problemMatcher": {
                "base":"$gcc",
                "fileLocation" : ["relative", "${workspaceRoot}/build/meson-private/tmpsm350_09"]
            }
```
solves the problem, thanks!
