### ISSUE TITLE
Unable to find header files

### ISSUE THREAD

**Issue by karanchawla** [microsoft/vscode-cpptools#2052]
Mac OS Sierra 10.12.16
VS Code 1.23.1
C/C++ 0.16

Config File
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Library/Developer/CommandLineTools/usr/include/c++/v1",
                "/usr/local/include",
                "/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include",
                "/Library/Developer/CommandLineTools/usr/include",
                "/usr/include",
                "/usr/local/Cellar/eigen/3.3.4/include/eigen3/",
                "/usr/local/Cellar/pcl/1.8.1_2/include/pcl-1.8/",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/Library/Developer/CommandLineTools/usr/include/c++/v1",
                    "/usr/local/include",
                    "/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include",
                    "/Library/Developer/CommandLineTools/usr/include",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

IntelliSense is unable to find pcl/Eigen headers even though those exist in the paths mentioned above in the config file. Is this a known bug or potential solutions exist?

**Comment by bobbrow** [comment]
Are you referring to auto-complete for `#include`?  If you want the pcl/eigen headers to show up, you need to add those paths to the `"browse.path"`

**Comment by karanchawla** [comment]
No autocompletion works fine and when I right click on the header it would take me to the definition as well, but it would fail to compile. Compile error being unable to find the header file.

**Comment by bobbrow** [comment]
Our extension doesn't compile files.  Do you have a `tasks.json` that you're using or are you using another extension to provide build services?

**Comment by sclel016** [comment]
Sorry to reopen an old thread. I'm having a similar issue. Intellisense has no problem finding the header file, I can right click on `#include <header.hpp>` and be taken to the header definition. `header.h` is in the base workspace directory (the same as `.vscode` and `main.cpp`).

However, I'm getting an error when I try to build. I get `fatal error: header.hpp: No such file or directory`

My `c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
My `tasks.json`
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build crc",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g",
                "bitset_crc.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        }
    ]
}
```

**Comment by sean-mcmanus** [comment]
If it's in your root workspace, you need to use `#include ""` instead of `#include <>`, because the `<>` version doesn't add the current directory to the include path. Otherwise, you need to modify your task.json to specify the correct include path for g++. c_cpp_properties.json isn't used by g++.exe.

**Comment by ES5017** [comment]
same problem, it didn't work

**Comment by sean-mcmanus** [comment]
@ES5017 I don't know what "same problem" means. What didn't work? Can you open a new issue?

**Comment by ozarchie** [comment]
Here is a picture of it.
Same problem on my mac osx.
It is an arduino project - correctly compiles on Windows Visual Studio Community edition with vmicro.
No such luck on the mac 

![vscode_include](https://user-images.githubusercontent.com/6479143/53615652-a8374c00-3c2a-11e9-9f9d-1855fc097c7a.png)

**Comment by ozarchie** [comment]
Here is the complete verify output.
[EQG2HBX.verify.txt](https://github.com/Microsoft/vscode-cpptools/files/2917872/EQG2HBX.verify.txt)

**Comment by bobbrow** [comment]
@ozarchie our extension doesn't provide any build services right now, so perhaps yours is an issue with the Arduino extension?

**Comment by ozarchie** [comment]
Hi Bob,
Wow .. so an extension can stop a c-construct as old as #include working.
I guess I will just go back to plain vanilla arduino.
Cheers

**Comment by bobbrow** [comment]
@ozarchie, I don't think you understood my comment. The build task and error you are referring to doesn't come from the C/C++ extension. This extension only does IntelliSense right now. We don't compile anything. There is a separate extension for Arduino that you probably installed that is doing your compilation. I'm just saying that you should open an issue on that extension.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.

**Comment by jkotra** [comment]
> If it's in your root workspace, you need to use `#include ""` instead of `#include <>`, because the `<>` version doesn't add the current directory to the include path. Otherwise, you need to modify your task.json to specify the correct include path for g++. c_cpp_properties.json isn't used by g++.exe.

this actually worked!

thanks.
