### ISSUE TITLE
Autoformat gives no apparent option to set the asterisk spacing within a pointer declaration

### ISSUE THREAD

**Issue by BenniG123** [microsoft/vscode-cpptools#2058]
On autoformat, all pointer declarations are spaced as such:
int *a;

I want to configure my settings to style it as:

int* a;

**Comment by sean-mcmanus** [comment]
See http://releases.llvm.org/5.0.0/tools/clang/docs/ClangFormatStyleOptions.html . You can use PointerAlignment and/or DerivePointerAlignment in your .clang-format or _clang_format configuration file located in our project root (or a parent).
