### ISSUE TITLE
[Feature Request] Implement Assembly View/Disassembly View for Debugger

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#206]
Being able to view assembly and step through assembly instructions would be useful. Especially when debug information isn't available for a certain library. Right now it just displays a message saying unknown source, when it goes into one of these functions.  Being able to view values of registers in the GUI some way. Not entirely sure how that would work with VSCode, but being able to the registers all the time and able to modify them such other assembly debuggers.

**Comment by agauniyal** [comment]
@marktrz if you're on Linux, nemiver does it all and is quite a performer. I'm using it as an alternative to vs debugger on linux and so far it performs well. Now only if vscode could implement its features 🎐

**Comment by jacdavis** [comment]
Thanks for the feedback. You can view disassembly in vscode using the -exec disassembly command in the debug console. Registers can be viewed the same way (-exec info registers).

**Comment by Izikiel** [comment]
I have code in C which calls code in ASM and it would be very useful to debug the ASM code within vs code without calling specific gdb commands which only show part of the source.

**Comment by hth313** [comment]
A register display would be very useful in situations like this, having it update as you step around.

**Comment by Izikiel** [comment]
If I'm not mistaken, since it's been a couple of years since I used it, the sublime gdb plugin for sublime text 2 supported asm debugging, showing registers and everything (https://github.com/quarnster/SublimeGDB).  Probably there is a way for it to be done on vs code

**Comment by yh-sb** [comment]
So, could you please add a disassembler viewer in dubug view. It will be so helpful for C/C++ developers.
It should not take long time to implement this.

Below placed examples how this view looks like:

![disassembler_1](https://habrastorage.org/web/92b/9a6/773/92b9a677387b4b009538d745fabb3118.png)

![disassembler_2](https://habrastorage.org/web/a0a/406/2d9/a0a4062d938143949fe7f7029cf6020d.png)

**Comment by kgfly** [comment]
Please add

ASM window
Memory window
Register window

**Comment by doingnz** [comment]
I have just spent days looking for alternatives to VSCode because I would like to have assembler, memory and register windows. Reworking a large open source project based on VSCode/CMmake to a new tool is considerable effort. There are many people asking for a memory view for a long time. Please do consider adding such a window. Memory view can execute the GDB x command after each step / trace as it is so last decade to enter that command repeatedly (or up arrow enter). Ideally the window would also highlight values that have changed.

**Comment by sean-mcmanus** [comment]
@doingnz You could try using Visual Studio 2017 -- they have some remote to Linux ability: https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/ .

**Comment by ci70** [comment]
Please add

ASM window
Memory window
Register window

**Comment by tehKaiN** [comment]
This is probably related to https://github.com/Microsoft/vscode-cpptools/issues/941

**Comment by ci70** [comment]
Has this been implemented yet???

**Comment by nicolo-ribaudo** [comment]
No, but I think that they would happily accept a PR.

**Comment by ci70** [comment]
Oh I am sure they would. PlatformIO has implemented this a long time ago.
What's the hold up?

**Comment by ci70** [comment]
What's the hold up? Nothing about it in new insider build. @sean-mcmanus

**Comment by tehKaiN** [comment]
@optomux 

Not that I think that this feature is not needed, but I guess that's not top priority here. Just wait patiently or do it yourself. You can always copy appropriate code from PlatformIO to this extension and submit a pull request.

**Comment by ci70** [comment]
I wish someone made an extension for it. Would PlatformIO work with this?

**Comment by sean-mcmanus** [comment]
@optomux I don't work on the debugger stuff at all. The other debugger people spend most of their time working on the Visual Studio debugger (a paid product, although there are some free versions with restricted licenses). Implementing an assembler view or other advanced debugging features isn't a priority for the debugger team and not on their schedule to implement.

**Comment by Izikiel** [comment]
@sean-mcmanus Hi!
If you could give a few pointers of example code to have an idea of how vs code interacts with gdb, sends commands, and sets the UI, I would be willing to try to implement this.

**Comment by sean-mcmanus** [comment]
@Izikiel Ask @WardenGnaw (or @pieandcakes when he gets back from vacation in January). I don't know much about how the debugger works since I just work on the language service stuff. I think most of it is open source. Another repo that may be relevant is https://github.com/Microsoft/MIEngine .

**Comment by mirao** [comment]
I tried debugging in VSCode extension [PlatformIO](https://community.platformio.org/t/finally-pio-unified-debugger-comes-to-vscode/4091) on my embedded device. Nice, it's possible to switch fluently between debugging of C source and disassembly view.
It would be great to have such possibility with desktop apps as well.

**Comment by gerekon** [comment]
Please add

ASM window
Memory window
Register window

**Comment by pkeir** [comment]
@jacdavis How does "-exec disassembly" work? While debugging, I type "-exec disassembly" + RETURN in the DEBUG CONSOLE window, but receive only "identifier "exec" is undefined".

**Comment by pieandcakes** [comment]
@pkeir which debug `"type"` are you using? that command works for `gdb`.

**Comment by liar666** [comment]
> Thanks for the feedback. You can view disassembly in vscode using the -exec disassembly command in the debug console. Registers can be viewed the same way (-exec info registers).

```
-exec disassembly
Undefined command: "disassembly".  Try "help".
help
-var-create: unable to create variable object
```

**Comment by mirao** [comment]
@liar666 `-exec disassemble` or `-exec disas` works for me.
I'm running VSCode 1.44.2, ms-vscode.cpptools 0.27.0, gdb 9.1

**Comment by Trass3r** [comment]
> `-exec disassemble` or `-exec disas` works for me.

At least with `set disassembly-flavor intel` 😉

**Comment by Trass3r** [comment]
For the record the feature _is_ in the DAP by now microsoft/debug-adapter-protocol#50, microsoft/debug-adapter-protocol#49
More information is in https://github.com/microsoft/MIEngine/issues/816#issuecomment-661936509.
It is implemented for embedded use-cases in PlatformIO and https://github.com/Marus/cortex-debug.
For desktop applications it would be also useful whenever you don't have source code, see #811.
Edit: It is also implemented in https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#disassembly-view

**Comment by yannickowow** [comment]
+1 for this
I would like to know, in order to do it properly, VS Code needs to provide an UI for Assembly, same as Source View, to provide at the same time SteppingGranularity for the "Next Request", and supports for instructionBreakpoints. 
Or is it a work to provide in DebugAdapter side, like CppTools.

**Comment by Trass3r** [comment]
For general purpose use (arbitrary address ranges) `DisassembleRequest` would need to be implemented in the adapter similar to https://github.com/microsoft/MIEngine/compare/dev/waan/readMemory.
This isn't implemented in vscode though and seems quite useless.

The important use-case is covered by https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Source (vscode [implementation](https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/workbench/contrib/debug/common/debugContentProvider.ts#L104).
If there is no source code available you simply send an assembly document [like this](https://github.com/vadimcn/vscode-lldb/blob/3b83348df4d1087dd5f1d25ff3745b3c3625016f/adapter/src/debug_session.rs#L2145-L2150). They defined a [custom](https://github.com/vadimcn/vscode-lldb/blob/master/syntaxes/disassembly.json) language but I'd rather reuse something like https://marketplace.visualstudio.com/items?itemName=maziac.asm-code-lens.

Then you need to handle stepping, goto, [breakpoints](https://github.com/vadimcn/vscode-lldb/blob/3b83348df4d1087dd5f1d25ff3745b3c3625016f/adapter/src/debug_session.rs#L447-L449) and stacktraces.
See `disassembly` references in https://github.com/vadimcn/vscode-lldb/blob/master/adapter/src/debug_session.rs.

All of this probably goes into MIEngine.

**Comment by KaungZawHtet** [comment]
+1 for this

**Comment by xhliu** [comment]
+1 for this

**Comment by sshsu** [comment]
4 years have passed,  when does these features will be added ?  it is really usefully for c/c++, please pay more attention to ASM window, Memory window, Register window, thanks~

**Comment by Trass3r** [comment]
Well the [DAP](https://microsoft.github.io/debug-adapter-protocol/specification) disassemble request has been [implemented](https://github.com/microsoft/MIEngine/blob/fbbc9938f8a75e3ca5fb7573a331f61ff484676f/src/OpenDebugAD7/AD7DebugSession.cs#L1941) but I think VSCode doesn't use it.

**Comment by bobbrow** [comment]
We are starting the planning for adding this feature to one of our releases this year.  The specific release is not set yet as there is a significant amount of work that needs to go into this.  As we get more clarity on the schedule, we will assign this to the appropriate milestone.

**Comment by nextarg** [comment]
I have a disassembly viewer using DAP in my local environment.
Is there anyone interested in this?

![1](https://user-images.githubusercontent.com/80216624/111069053-91f94180-850e-11eb-836c-df2388180a79.gif)

**Comment by koutheir** [comment]
> I have a disassembly viewer using DAP in my local environment.
> Is there anyone interested in this?

A disassembler view in a debugger is expected to follow the current instruction pointer, not just a listing of disassembled bytes at some address.

**Comment by nextarg** [comment]
That's correct.
I have an experimental function that displays the current instruction pointer value. However, it has not been tested because I have not yet implemented the instruction level steps.

![2](https://user-images.githubusercontent.com/80216624/111202710-88073980-8607-11eb-97e7-72f38d709a18.gif)

**Comment by koutheir** [comment]
While you're there, it would help a lot if the disassembly view can also show the source text in the same view. This usually helps identify which instructions were generated for which source lines.

**Comment by nextarg** [comment]
There are still some limitations, but it is published.

https://github.com/nextarg/disassembly-view/releases/tag/v0.0.1

The workaround is written in the README, but I'm not good at English, so there may be mistakes.

**Comment by Al-aqua** [comment]
it will be cool

**Comment by nextarg** [comment]
I am trying to execute the instruction steps using vscode-cpptools + cppvsdbg, however, I have a wonder about it.
If the address has no source information, are there any limitations?

For example, when I do a stepinto an address with no source information, it seems that a temporary step is being executed.
(ex: call <span>@</span>ILT+X when using incremental link).

Does anyone know anything about this behavior?

Below is a comparison with VS.

### VS
![vs](https://user-images.githubusercontent.com/80216624/115053387-0a8e5c00-9f1a-11eb-8f30-92ca3ce40a84.gif)

```
RIP : 00000001400BDF3D
=>  00000001400BDF3D E8 E1 75 FE FF       call        func (01400A5523h) 
    00000001400BDF42 33 C0                xor         eax,eax 
```

```
RIP : 00000001400A5523
=>  00000001400A5523 E9 38 76 01 00       jmp         func (01400BCB60h)
```

```
RIP : 00000001400BCB60
=>  00000001400BCB60 40 55                push        rbp 
```

### VS Code

![vscode](https://user-images.githubusercontent.com/80216624/115053737-6a850280-9f1a-11eb-8505-a7c5570af71a.gif)

```
RIP : 00000001400BDF3D
=> 0x00000001400BDF3D	E8 E1 75 FE FF	call func (01400A5523h)
   0x00000001400BDF42	33 C0		xor eax,eax
```

```
RIP : 00000001400BDF42
   0x00000001400BDF3D	E8 E1 75 FE FF	call func (01400A5523h)
=> 0x00000001400BDF42	33 C0		xor eax,eax
```

```
RIP : 00000001400BCB60
=> 0x00000001400BCB60	40 55		push rbp
```

**Comment by Trass3r** [comment]
Official support is on the roadmap:
https://github.com/microsoft/vscode/wiki/Roadmap#debug

**Comment by bobbrow** [comment]
For those following along, we are now tracking implementing this support directly in VS Code.  You can subscribe to this issue for updates: https://github.com/microsoft/vscode/issues/124163

**Comment by bobbrow** [comment]
The first iteration of this feature is now available in VS Code Insiders.  Give it a try and let us know what you think.
https://github.com/microsoft/vscode/issues/124163#issuecomment-875938765

**Comment by Trass3r** [comment]
👍🏽

Note that you'll need the step granularity feature from MIEngine `main` which has not been released yet.
The stepping performance will need some improvement, esp. when registers are expanded.
As will the link between original source and disassembly. I usually pull the disassembly view to the right manually to see both and they both update but when you step into another source file you won't see the code anymore.
Eventually a mixed view like in VS and objdump is desirable.

**Comment by Colengms** [comment]
This should be addressed in 1.6.0-insiders.

**Comment by Trass3r** [comment]
Yeah indeed it works with the insider version. Even the performance is a bit better.
Oddly though vscode sends a `disassemble` request even before you open the disassembly view, quite wasteful.

(Also if you prefer Intel syntax use a ~/.gdbinit file with `set disassembly-flavor intel`)

**Comment by ShlomiRex** [comment]
> This should be addressed in 1.6.0-insiders.

Hi, I downloaded insiders 1.6.0 , I'm on mac.
How can I enable or use this feature?
I really like the memory view in Visual Studio Community 2019.
I hoope this feature can reach VS code.

**Comment by Trass3r** [comment]
It's in the editor context menu during debugging.

**Comment by Trass3r** [comment]
> One missing feature is syntax highlighting. There are wonderful extensions for this like ASM Code Lens but since this view is not a normal editor there's no chance of them ever working. (It's also a bit weird in general that you can't select the code.)

https://github.com/microsoft/vscode/issues/131210
https://github.com/microsoft/vscode/issues/129762

**Comment by How-invin** [comment]
it seems that disassembly doesn't work on the gdb which is customized like for mips. ~.~

**Comment by MatAtBread** [comment]
Also no disassembly on esp32-C3 under esf-idf. Memory, code and registers are all visible within gdbgui. I'm running insiders 1.6.4.

Is there something I need to enable or select to see these viewers (no context menu item, unless I'm being really dumb)
