### ISSUE TITLE
Persistent red intellisense fire icon, intellisense stops working, cpp extension takes max CPU

### ISSUE THREAD

**Issue by fultonm** [microsoft/vscode-cpptools#2063]
I have a problem where Intellisense stops working and the C/C++ extension takes max CPU after running a debug session. Sometimes reloading the VSC window works, sometimes I have to exit completely, but I have to do this every time after debugging my project.

    * Operating System and version: Ubuntu Linux 18.04
    * VS Code version and if you are using the Insiders build: Version 1.23.1, not using Insiders
    * C/C++ extension version 0.17.3
    * Other extensions you installed and if the issue persists after disabling them: No other extensions
    * Step-by-step instructions to reproduce the issue. After debugging my C project for the first time after reloading (or loading for the first time) the workspace, the red fire icon stays on, intellisense stops working, and the "Microsoft.VSCode.CPP.Extension.linux (PID 5394)" eats max cpu, even after reloading the VScode window. Only a full shutdown of VScode will turn intellisense back on.
    * A small code sample, zipped up project, or open source repo we can use to verify the bug: Full project here: https://drive.google.com/file/d/16oohl67zUnUWC3lBR3QX-dLw4iOSaLRs/view?usp=sharing 
    * Relevant settings from your settings.json, c_cpp_properties.json, and/or launch.json files: launch.json here: https://pastebin.com/2kamcsN6
    * Any log messages present in the Output window (use "C_Cpp.loggingLevel": "Information" in settings.json) None that I can see
    * Debugger logs (use "logging": { "engineLogging": true } in your launch.json)

**Comment by bobbrow** [comment]
Sounds like a duplicate of #2062 and #2043.  Please follow those issues and let us know if your issue is fixed once those are closed.

**Comment by fultonm** [comment]
@bobbrow I do not have a **c_cpp_properties.json**

**Comment by bobbrow** [comment]
If you don't have a **c_cpp_properties.json** then you are using recursive includes.  If you generate that config file with the "Edit configurations..." command and then delete the `/**` from the entry in there, or if you add `"C_Cpp.default.includePath": [ "${workspaceFolder}" ]` to your settings instead of generating the config file, you will effectively disable it.

**Comment by Zirhi** [comment]
I don't know if you guys fixed this, but I have just begun having this same problem of the "red flame" while using VS Code. 

I have multiple C++ files open and whenever I open the folder containing these files, my Mac becomes slow and I've often found myself restarting my system over and over again. 

I generated the the config file and removed /** but still having the same issues

**Comment by sean-mcmanus** [comment]
@Zirhi Can you open a new issue with more repro details? What process is using CPU? How many processes are there?

**Comment by Zirhi** [comment]
sorry, I have fixed the issue. Found some help in your other article
