### ISSUE TITLE
1. c/c++ plugin , the IntelliSense is always not work. 2. Microsoft.VSCode.CPP.Extension.darwin always use cpu , even when I quit form vscode.

### ISSUE THREAD

**Issue by CharlieCheng2014** [microsoft/vscode-cpptools#2064]
1. c/c++ plugin , the IntelliSense is always not work. 
2. Microsoft.VSCode.CPP.Extension.darwin always use cpu , even when I quit form vscode.

VS Code version: Code 1.23.1 (d0182c3, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 16.7.0

Extension | Author (truncated) | Version
-- | -- | --
vscode-language-pack-zh-hans | MS- | 1.23.5
vscode-docker | Pet | 0.0.27
cpptools | ms- | 0.17.3
cmake | twx | 0.0.17

Item | Value
-- | --
CPUs | Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: enabledrasterization: enabledvideo_decode: enabledvideo_encode: enabledvpx_decode: enabledwebgl: enabledwebgl2: enabled
Load (avg) | 3, 3, 2
Memory (System) | 16.00GB (0.08GB free)
Process Argv | /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Screen Reader | no
VM | 0%

**Comment by bobbrow** [comment]
Hi @CharlieCheng2014, can you take a look at #2043 for a workaround.  We plan to release a fix soon.

**Comment by yunlingz** [comment]
For current version, you can set this in your global `User Settings`, then regenerate `c_cpp_properties.json`.

```
{
    ...
    "C_Cpp.default.includePath": [
        "${workspaceFolder}"
    ],
    ...
}
```

I hope this will help you.

**Comment by bobbrow** [comment]
We released 0.17.4 with a fix for the livelock, so this issue should be resolved now. There are still some performance issues with recursive includes that we are working on, so you might still see some high CPU usage when opening files, but it should eventually catch up. We are going to track performance problems with recursive includes using issue #2068.

**Comment by astnexperiments** [comment]
> For current version, you can set this in your global `User Settings`, then regenerate `c_cpp_properties.json`.
> 
> ```
> {
>     ...
>     "C_Cpp.default.includePath": [
>         "${workspaceFolder}"
>     ],
>     ...
> }
> ```
> I hope this will help you.

I have tried adding this to my settings.json (among other things) but autocomplete still works for only files that are not c/c++. Is there an updated solution for this?

**Comment by webpolis** [comment]
Yep, nothing. I also configured the settings, added all included paths.. . but even a basic `std::` will bring "No Suggestions".

**Comment by michelleangela** [comment]
@webpolis, can you run the command `C/C++: Log Diagnostics` and [enable logging for the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) and then share both logs?
