### ISSUE TITLE
Symbol search fails for a function definition if it uses a certain macro

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#207]
Type #main in the Command Palette with the code below and it will fail to find the symbol main.
# define assign(l, k) l = k;

int main()
{
    int i, t;
    assign(i, ((t & 3) - 3 ? 16 : 37))
    {
    }
}

**Comment by sean-mcmanus** [comment]
Adding a ";" at the end of assign fixes it. It looks like the parser is not correctly applying the macro.

**Comment by jgoshi** [comment]
Visual Studio has the same behavior. Go to definition works (same for VSCode). But go to symbol (VSCode) has the same behavior as Visual Studio Object Browser (which looks at symbols).
