### ISSUE TITLE
In a cpp file asterisk as first non-whitespace character on a line triggers another asterisk on new line

### ISSUE THREAD

**Issue by kghose** [microsoft/vscode-cpptools#2072]
- VSCode Version: 1.23.1 
- cpptools Version: 0.17.4
- OS Version: macOS High Sierra

Steps to Reproduce:

Type the following text in a `.cpp` file
```
a = a
    * b;
```
Then hit enter at the end of the line to begin a new line. You'll get

```
a = a
    * b;
    * 
```

This is not expected behavior in this context. This is perhaps expected when in the middle of a multiline decorated comment but not otherwise.

This does not happen in an unsaved file, a file with no extension, `.txt` extension etc. and does not happen if the cpptools extension is disabled and happens when it is re-enabled.

**Comment by sean-mcmanus** [comment]
Looks like a bug with our comment continuation patterns, i.e. /** is supposed to continue the line with *.

**Comment by bobbrow** [comment]
Can you please share the value you have set for `"C_Cpp.commentContinuationPatterns"`?  I don't see this behavior with the default value.

**Comment by bobbrow** [comment]
Sorry, I misread the repro.  Because the comment continuation stuff is reg-exp based (and not multiline aware), this is actually the expected behavior for the default value.  You will observe the same behavior with JavaScript and TypeScript files.

If you want to disable this behavior, you can set `"C_Cpp.commentContinuationPatterns": []` in your settings file.

**Comment by kghose** [comment]
Hi all,

Thanks for looking at the report. From my (user) perspective I expect the behavior to be context aware. So, If I'm in the middle of a multiline comment (I started with `/*`) I expect this to happen. If I'm not, then I expect this to be disabled.

Thanks!

**Comment by bobbrow** [comment]
I agree with you, but you may need to ask the vs code team for help here since we are unfortunately limited by the reg exp support.

**Comment by bobbrow** [comment]
This is being tracked by https://github.com/microsoft/vscode/issues/50952
