### ISSUE TITLE
Unable to find header files

### ISSUE THREAD

**Issue by z2665** [microsoft/vscode-cpptools#2073]
I want to use vscode to write some cpp program in windows
so I copy the header files form centos to windows and Install the clang 
the c_cpp_properties.json is
```
{
    "configurations": [
        {
            "name": "Win32",
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "D:/linuxdev/gcc/include/c++/7.3.0/x86_64-pc-linux-gnu",
                    "D:/linuxdev/gcc/include/c++/7.3.0/tr1",
                    "D:/linuxdev/gcc/include/c++/7.3.0/tr2",
                    "D:/linuxdev/gcc/include/c++/7.3.0/backward",
                    "D:/linuxdev/gcc/include/c++/7.3.0",
                    "D:/linuxdev/inc/include/linux",
                    "D:/linuxdev/inc/include",
                    "D:/linuxdev/local/include",
                    "D:/linuxdev/x86_64-pc-linux-gnu/7.3.0/include"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}",
                "D:/linuxdev/gcc/include/c++/7.3.0/x86_64-pc-linux-gnu",
                "D:/linuxdev/gcc/include/c++/7.3.0/tr1",
                "D:/linuxdev/gcc/include/c++/7.3.0/tr2",
                "D:/linuxdev/gcc/include/c++/7.3.0/backward",
                "D:/linuxdev/gcc/include/c++/7.3.0",
                "D:/linuxdev/inc/include/linux",
                "D:/linuxdev/inc/include",
                "D:/linuxdev/local/include",
                "D:/linuxdev/x86_64-pc-linux-gnu/7.3.0/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

Then I want to use folly
folly's header file in D:\linuxdev\local\include

but the vscode show can't find the header 
```
{
	"resource": "/g:/clopro/t3/main.cpp",
	"owner": "clang",
	"code": "undefined",
	"severity": 8,
	"message": "'folly/FBString.h' file not found",
	"startLineNumber": 2,
	"startColumn": 9,
	"endLineNumber": 2,
	"endColumn": 27
}
```

**Comment by bobbrow** [comment]
Do you have any other C++ extensions installed?  That doesn't look like our extension's message.  We would have said `cannot open source file "folly/FBString.h"`.

Also, you didn't ask, but to get the best IntelliSense results, I would recommend installing a MinGW compiler and adding `"compilerPath": "C:/path/to/gcc.exe"` to your configuration, then moving your system includes to the `"C_Cpp.default.systemIncludePath"` setting.  This will let you keep your custom system include paths (don't sort the paths, the ordering should match what `gcc -v -E -x c++ /dev/null` displays) and also get you a default set of system defines imported.

**Comment by bobbrow** [comment]
Also, if you do set `"C_Cpp.default.systemIncludePath"`, just do it for the workspaces that need it.  I wouldn't recommend setting it globally unless you also set `"C_Cpp.default.compilerPath"`.

**Comment by z2665** [comment]
@bobbrow  Thanks.  I solve the problem when I uninstall C/C++ Clang Command Adapter .

but The intellisense may not work well. I will try your suggest.  to Install MinGW
