### ISSUE TITLE
Symbol lookup has stopped working

### ISSUE THREAD

**Issue by toh-ableton** [microsoft/vscode-cpptools#2074]
Issue Type: <b>Bug</b>

Symbol lookup has stopped working today. None of "Go to Definition", "Peek Definition", "Go to Symbol in File", "Go to Symbol in Workspace" work. 

I am using the "Default" intelliSenseEngine, loggingLevel set to Debug. I am using "compileCommands" generated by ninja, and have verified that it is correct.

I have removed recursive searching from the include path (the trailing `/**`).

I have restarted VS Code several times, and I have reset the Intellisense Database several times.

When starting VS Code, I'm getting tens of thousands of
```
Unable to add file to database, error = 0x8064000a: ...
```
in the C/C++ log. When I open a file, it seems to be able to parse the file correctly (no swiggles if the file doesn't contain any actual errors, swiggles if I introduce errors for testing, correct pre-processor `#if` branches greyed out etc). Auto-completion and code suggestions work correctly.

The problems tab is empty.

Extension version: 0.17.4
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2191B CPU @ 2.30GHz (36 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (1.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bobbrow** [comment]
symbol lookup/code navigation is currently decoupled from the other IntelliSense features so that would explain why the other features are working fine for you.

I wonder if the reset IntelliSense Database command is failing and not notifying you.  Do you get the same problem if you change the `"browse.databaseFilename"` property to something else? (e.g. `"${workspaceFolder}/.vscode/browse.db"`)  This will guarantee that the database is re-created.

**Comment by toh-ableton** [comment]
Thanks, this workaround seems to have fixed it :)
