### ISSUE TITLE
IntelliSense processes crashes when MSVC headers are used in clang-x64 mode

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2076]
Open a file with
```
#include <iostream>
#include <map>
```
With include path similar to
"C:\\VS\\VC\\Tools\\MSVC\\14.14.26428\\include".
with clang-x64 mode.

It crashes with copy_cached_token on the call stack.

Let us know if anyone is hitting this in a "valid" scenario, since MSVC headers aren't normally supposed to be used in clang-x64 mode.

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.
