### ISSUE TITLE
Red flame icon persists when the extension is not actually doing any IntelliSense work after a c_cpp_properties.json change

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#2077]
Cause unknown as of know.  We are investigating...

**Comment by sean-mcmanus** [comment]
Yeah, please provide a consistent repro if anyone discovers one. I added diagnostic logging, but then I couldn't get it to repro any more.

UPDATE: We think this is fixed with 0.17.5-insiders.

**Comment by sean-mcmanus** [comment]
This isn't fixed -- I just hit this with 0.17.5 (maybe another repro was fixed?). Looks like changing c_cpp_properties.json can randomly cause it.

**Comment by bobbrow** [comment]
The case I saw was when a source file was closed while sqiuggles were being updated

**Comment by sean-mcmanus** [comment]
I reproed this with 0.17.6...but I still don't know how to repeat the repro.

**Comment by sean-mcmanus** [comment]
I'm still reproing this on Linux with 0.17.7-insiders.

**Comment by sean-mcmanus** [comment]
Changing the c_cpp_properties.json while the red flame is showing can repro this 100% (as long as the processing isn't too fast).
