### ISSUE TITLE
class access modifiers incorrectly indented / formatted with editor.formatOnType: true

### ISSUE THREAD

**Issue by BinaryKhaos** [microsoft/vscode-cpptools#2078]
Let's say you have set the "Google" clang format style to get something like this:

```cpp
class Test {
 public:
  int var1;

 private:
  int var2;
};
```
If you enter the code above with ```editor.formatOnType: true```, you will end up with something like this:

```cpp
class Test {
    public:
     int var1;

     protected:
      int var2;

      private:
       int var3;
};
```

With ```editor.formatOnType: false```, you will get something a bit more consistent, but still not what you asked for in the first place (given that no clang-format is invoked, that is as expected):

```cpp
class Test {
    public:
    int var1;

    protected:
    int var2;

    private:
    int var4;
}
```

Versions:
```
VSCode v1.23.1
C/C++ v0.17.4
Vim 0.12.0
```

Customized settings:
```
{
    "editor.fontSize": 16,
    "editor.formatOnType": true,
    "git.enableCommitSigning": true,
    "git.promptToSaveFilesBeforeCommit": true,
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,

    // PLUGIN: vim
    "vim.easymotion": true,
    "vim.enableNeovim": true,
    "vim.neovimPath": "/usr/bin/nvim",

    // PLUGIN: cpp
    "C_Cpp.clang_format_path": "/usr/lib/llvm/6/bin/clang-format",
    "C_Cpp.clang_format_fallbackStyle": "Google",
}
```
It would be nice to have more control over the "as you enter" identation in the first place w/o the need to invoke clang-format. Or properly support formatOnType and really exclusively use clang-format for everything to have a consistent and customizable style. Right now, it seems like, you have to "manually" (as-in: invoke clang-format for a block) reformat a class declaration to get what you want and live with the fact that while you enter it, it looks... well.. messy or formatted in a different style.

**Comment by bobbrow** [comment]
I'm sorry, this slipped through our notification system.  I found it while checking up on untagged issues with no response.

Our implementation of onTypeFormatting is a bit too naive, I'm afraid.  We're tracking this with #1419, which doesn't appear to have many upvotes.  If you can please upvote that issue, it helps us to prioritize which features/bugs are addressed next.
