### ISSUE TITLE
Visual C++ Build Tools cannot be downloaded anymore?

### ISSUE THREAD

**Issue by fschutt** [microsoft/vscode-cpptools#2079]
This is not an issue relating to this repository, but I don't know how to notify anyone of this - the Visual C++ Tools are currently unavailable for download, since Microsofts HubSpot account has expired: 

http://landinghub.visualstudio.com/visual-cpp-build-tools

![grafik](https://user-images.githubusercontent.com/12084016/40878163-2d592d50-668d-11e8-8fac-3fffb089d024.png)

I know that this isn't an issue with the VsCode tools and does not belong here, but I don't know where to report this otherwise, this is the closest I can get. Please forward this to the responsible persons, if possible.

**Comment by bobbrow** [comment]
Are you able to get the tools from here?

https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017

**Comment by fschutt** [comment]
Ah, alright then thanks - it's just that this site is the first result on Google for "Visual C++ Build Tools". I know that it was just a landing page, but couldn't find that link. Thanks.

**Comment by bobbrow** [comment]
Glad to hear that works for you.  Yeah, I made a similar comment to people around here asking if we can fix the SEO somehow.

**Comment by thorade** [comment]
I think the new landingpage is here:
https://visualstudio.microsoft.com/visual-cpp-build-tools/
