### ISSUE TITLE
Support remap of header paths for remote file system

### ISSUE THREAD

**Issue by smhc** [microsoft/vscode-cpptools#2081]
When opening a project on a remote system it isn't currently possible to query the compiler for defines and includes. And even if it could, or if it used compile_commands.json instead, the paths to the includes would be incorrect for the local machine. 

It isn't practical to use a local compiler to obtain the defines as the remote system is a different OS (Linux).

I currently work around this by generating a large header file with all the compiler defines and use the 'forcedInclude' option to set these. I also reference all the system header include paths using includePath to map to the respective local mount path of the headers.

However this is both cumbersome and does not support compile_commands.json, which would allow per-file defines. To support this scenario it would be good to have the following:

1. A setting to use ssh to invoke the compiler to obtain the defines and header paths.
2. A remotePath to localPath map so the compiler_commands.json and compiler headers can be remapped to their respective path on the local machine.

Or is there a better way to achieve intellisense on a remote system?

**Comment by bhack** [comment]
This could be related generally to remote file-system/containers issues:
https://github.com/Microsoft/vscode/issues/35671
https://github.com/Microsoft/vscode/issues/35671

**Comment by bobbrow** [comment]
The recommendation for opening remote projects is to use the [VS Code Remote Development Extensions](https://code.visualstudio.com/docs/remote/remote-overview).  This will allow the C++ extension to query the compiler on those systems.
