### ISSUE TITLE
Code completion list pops up when type a period in the end of comments

### ISSUE THREAD

**Issue by DemoCrazer** [microsoft/vscode-cpptools#2082]
If I type comments in Korean text and put '.' in the end, code completion list pops up.

Steps to Reproduce:

1. Write comments in Korean text
2. Code completion list pops up when type a period(.) in the end of comments

![image](https://user-images.githubusercontent.com/26616056/40889784-9c63d7b6-67a7-11e8-98ac-2714bd2271dc.png)

My English font is _Hack_ and Korean font is fallback font.(_Hack_ doesn't support Korean) The issue doesn't occur when I write comments in English text.

**Comment by sean-mcmanus** [comment]
UTF-8 characters > 1 byte should not cause completion to break now with our latest Insiders release: https://github.com/Microsoft/vscode-cpptools/releases . If you're using VS Code Insiders or have http.proxySupport not set to "off", you might not get the 0.21.0-insiders2 update automatically with C_Cpp.updateChannel set to "Insiders".
