### ISSUE TITLE
Can't identify an enum as a type

### ISSUE THREAD

**Issue by metropt** [microsoft/vscode-cpptools#2086]
As you can see on the following image it can't identify an enum as a type name. Is this the expected behavior on this version of the plugin?

![image](https://user-images.githubusercontent.com/764040/40942079-e038b8d8-6844-11e8-85b9-1213f7ed98b2.png)

**Comment by sean-mcmanus** [comment]
UPDATE: Ignore what I wrote, see Bob's comment :)

It's not expected in general. What is the squiggle in the enum definition? I assume it can't find the values used to define the enum, so that appears to be causing the type to not get defined. Can you get those values to be defined?

**Comment by bobbrow** [comment]
Which of the include files listed in `main.c` includes `nrf_gpiote.h`?  From your screenshot, I can't tell whether `nrf_gpiote.h` is actually included in the translation unit.

This should work, even with the squiggles in the enum value definitions.

![image](https://user-images.githubusercontent.com/12818240/40944372-625133fe-6809-11e8-8364-cd134c98cf93.png)

**Comment by metropt** [comment]
@bobbrow main.c include nrf_drv_gpiote.h and it include nrf_gpiote.h

![image](https://user-images.githubusercontent.com/764040/41193491-8b8febda-6c04-11e8-80ee-71bbe6b6e86c.png)

BTW on the main.c file I can't navigate to included files except the ones from the compiler path or the ones I have opened on the editor.

**Comment by metropt** [comment]
How can I tell intellisense that a variable is defined?
![image](https://user-images.githubusercontent.com/764040/41193640-cabc27cc-6c06-11e8-851f-ceddd9a7b171.png)
I can share the project if it easier.

**Comment by sean-mcmanus** [comment]
You should set the "defines" property in your c_cpp_properties.json. Setting your compilerPath should set your compiler-based defines (excluding cl.exe).

Inability to navigate to the included files usually means your browse.path isn't set correctly (i.e. it should have ${workspaceFolder} and any other root folders where you need file navigation or workspace symbols).

**Comment by bobbrow** [comment]
@metropt, your latest screenshot shows that `__APPLE__` is defined.  The other (inactive) blocks are grayed out.  If you are able to share your project, we can investigate further.

**Comment by metropt** [comment]
@bobbrow __APPLE__ is a system variable but NRF51 isn't one. I'm going to try @sean-mcmanus advice tonight.

Should I use relative paths or it's fine to use absolute paths?

**Comment by bobbrow** [comment]
What I'm implying is that setting `NRF51` won't do anything for this particular header file because you're already going through the `__APPLE__` path, not the `#else` path.  But maybe it matters elsewhere, so it might still be worth a try.

**Comment by metropt** [comment]
@bobbrow you're right, I looked at it as two conditions blocks -.-' There is a way to undefined the `__APPLE__` variable for this project on vscode?

**Comment by bobbrow** [comment]
Unfortunately, not at this time.  Cross-compilation support is on the backlog, but not currently available.

**Comment by metropt** [comment]
So will not be possible to have the project properly configured?

**Comment by bobbrow** [comment]
If you share the project, I can see if there's anything I can do for the time being.  You can also try the `forcedInclude` property in `c_cpp_properties.json` to force include any of those nrf headers that end up missing.

**Comment by metropt** [comment]
https://www.dropbox.com/s/e9yhqq56vqr59yr/vscodecpp.zip?dl=0 the only thing I didn't include was arm gcc embedded.

Thank you

**Comment by bobbrow** [comment]
Thanks.  The `forcedInclude` property seems to do the trick for me.

```
            "forcedInclude": [
                "${workspaceFolder}/../nRF5_SDK_12.3.0_d7731ad/components/device/nrf51.h",
                "${workspaceFolder}/../nRF5_SDK_12.3.0_d7731ad/components/device/nrf51_bitfields.h",
                "${workspaceFolder}/../nRF5_SDK_12.3.0_d7731ad/components/device/nrf51_deprecated.h"
            ]
```

I also saw an invalid path in your `"includePath"` array.  You should remove that or switch to recursive includes `"${workspaceFolder}/../nRF5_SDK_12.3.0_d7731ad/**"`.  We improved the performance of recursive includes in 0.17.5-insiders, with further improvements coming in 0.17.5.

You can also remove the system include paths from `"includePath"` since you have specified the `"compilerPath"` property.  My final c_cpp_properties.json looks like this:

```
{
    "configurations": [
        {
            "name": "Mac",
            "browse": {
                "path": [
                    "${workspaceFolder}/.."
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}/../nRF5_SDK_12.3.0_d7731ad/**",
                "${workspaceFolder}/config"
            ],
            "defines": [],
            "compilerPath": "/usr/local/bin/arm-none-eabi-gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "forcedInclude": [
                "${workspaceFolder}/../nRF5_SDK_12.3.0_d7731ad/components/device/nrf51.h",
                "${workspaceFolder}/../nRF5_SDK_12.3.0_d7731ad/components/device/nrf51_bitfields.h",
                "${workspaceFolder}/../nRF5_SDK_12.3.0_d7731ad/components/device/nrf51_deprecated.h"
            ]
        }
    ],
    "version": 4
}
```

**Comment by bobbrow** [comment]
And for reference, the cross-compiler support issue is #1083.  Please go upvote that issue if you would like to bump up the priority.

**Comment by metropt** [comment]
thank you for your help :) at least now I can navigate through the whole code!

**Comment by sean-mcmanus** [comment]
@metropt __APPLE__ can be undefined now with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0 via changing the intelliSenseMode to something like "linux-gcc-x64", however, it may not solve your scenario, not sure -- we define unix and __unix__ on Linux, but not __unix. We're tracking some "unknown" platform with https://github.com/microsoft/vscode-cpptools/issues/6813 .
