### ISSUE TITLE
compile_commands.json support doesn't understand -iquote

### ISSUE THREAD

**Issue by nelhage** [microsoft/vscode-cpptools#2088]
The `compile_commands.json` support doesn't seem to extract include paths from `-iquote` arguments to the compiler.

You can reproduce by checking out https://github.com/nelhage/vscode_bazel_cxx and opening `foo.cc`; The `foo.h` include won't be found. If you edit `compile_commands.json` to use `-isystem` or `-I` instead, it will work.

(This isn't relevant to the bug since I was able to minimize to the above, but I'm using bazel and https://github.com/grailbio/bazel-compilation-database to generate my `compile_commands`, which is where I'm getting command files containing `-iquote`)

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders
