### ISSUE TITLE
x86 inline ASM: "unknown register name" in clobber list

### ISSUE THREAD

**Issue by whampson** [microsoft/vscode-cpptools#2090]
In an x86 inline assembly block, registers are not recognized when specified in the clobber list. I've tried `edx`, `%edx`, `EDX`, and `%EDX` in addition to other register names and none are recognized.

- OS Version: Windows 10
- VS Code Version: (latest)
- C/C++ Extension Version: (latest)

**Screenshots**
![](https://i.imgur.com/0KaN4GP.png)
![](https://i.imgur.com/namDoMo.png)

**Comment by bobbrow** [comment]
This works on linux/mac.  It looks like support for it was unintentionally removed from the Windows version of the extension.  I have a fix.

**Comment by sean-mcmanus** [comment]
You can try https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.5-insiders for the fix.

**Comment by whampson** [comment]
That seems to have fixed the issue, thanks!
