### ISSUE TITLE
Enabling warnings

### ISSUE THREAD

**Issue by BigfootN** [microsoft/vscode-cpptools#2091]
Hello,

I would like to know if there is a certain way to enable warnings ?

From what I understood, throughout my researches, the flags aren't extracted from `compile_commands.json` . So, am I right or wrong ?

The basic errors are shown without any problems, but how would it be possible to push a bit further (with flags like `-Wall`, `-Werror`, `-Wextra`) ?

Thank you very much in advance.

**Comment by sean-mcmanus** [comment]
You can remove the line containing "--no_warnings", from the bin/msvc.json file (in the directory containing the Microsoft.VSCode.CPP.Extension binary) to enable warnings (it'll get re-added after updates though), and it's an experimental feature, and doesn't directly correspond to warnings given by cl.exe/clang/gcc (it's warnings from the EDG compiler) so the #pragma warning disable code won't suppress the warnings.

**Comment by BigfootN** [comment]
Thank you for your quick response.

So if I understand well, `compile_commands.json` seems a bit useless for the moment ? And the warnings, for the moment, aren't available ? Even if add the flag `-Werror` ?

Thank you very much in advance.

**Comment by bobbrow** [comment]
I wouldn't go so far as to call it useless.  It provides the include path and defines for us which is the majority of the information we need to provide IntelliSense.  We plan to add support for flags on a case-by-case basis as people ask for them.

**Comment by BigfootN** [comment]
> It provides the include path and defines

Okay, thank you for the information. But it doesn't take into account the flags I suppose ?

> We plan to add support for flags on a case-by-case basis

You mean per project I suppose ?

Thank you very much for all your information.

**Comment by bobbrow** [comment]
I mean per flag.  Most flags don't affect IntelliSense.  If there are specific flags that modify the system includes or defines, those can be set in the `"compilerPath"` property and we will use them when we query the compiler for system includes and defines.  See: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md

This is a different case that we will need to support when we enable warnings in IntelliSense.

**Comment by BigfootN** [comment]
>  If there are specific flags that modify the system includes or defines, those can be set in the "compilerPath"

So if I pass for example `-Werror` would it also show the warnings, since they are treated as errors ?

Thank you very much in advance.

**Comment by sean-mcmanus** [comment]
We do not currently parse the -Werror flag -- we've had the idea of parsing that flag and using it to remove the --no_warnings from our msvc.json file (since we expose the warnings as errors in that case), but the warnings provided are not the same warnings as the cl/gcc/clang compiler warnings.

What Bob was saying is that you can pass flags like -stdlib=libc++ in the compilerPath setting to change the system includes/defines used, but -Werror doesn't affect that.

**Comment by BigfootN** [comment]
Thank you very much for all the information.
