### ISSUE TITLE
Link to "Configuring IntelliSense" is broken

### ISSUE THREAD

**Issue by tjamet** [microsoft/vscode-cpptools#2093]
Hi,

Using Code Version 1.13.1 (1.13.1) (379d2efb5539b09112c793d3d9a413017d736f89), I just installed the c/c++ libraries and tried to configure IntelliSense after a message where one of the headers could not be found.

I had a link from the release notes upon how to configure IntelliSense, clicked it and was redirected to https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started.md that is served by GitHub as a 404.

c.f C/C++ release note screenshot for better context.
<img width="1621" alt="screen shot 2018-06-06 at 14 03 36" src="https://user-images.githubusercontent.com/6061440/41037209-e05e3078-6992-11e8-93ce-7a160262a3bb.png">

**Comment by sean-mcmanus** [comment]
Your VS Code is too old. We've already fixed that bug in a version of our extension that requires a newer VS Code. You should upgrade your VS Code to 1.23.1. You're using our extension from October, 8 months ago.
