### ISSUE TITLE
Suggestion: Use an editable "c_cpp_properties_defaults.json" file for setting default properties.

### ISSUE THREAD

**Issue by grumpy-dude** [microsoft/vscode-cpptools#2094]
Instead of creating a "c_cpp_properties.json" file "on-the-fly" from numerous entries in the "settings.json" file, just have an editable "c_cpp_properties_defaults.json" file, which can then be simply copied to the folder/workspace "c_cpp_properties.json" file as needed.  Only a single entry in "settings.json" file indicating the location of the "defaults" file would be needed.  This should provide the following benefits:

- Allow for _multiple_ custom default configurations (e.g. for cross-compiling, supporting additional host operating systems/environments, use of additional/alternative external tools, etc.)
- Allow for per-user/per-workstation configurations (e.g. workstation A uses path A for include files, but workstation B has a different directory structure, user 1 has a license to use an external tool, but user 2 doesn't, etc.)
- Allow a team to use common configurations when the file is placed in a shared location
- _Theoretically_ allow for easier maintenance and expandability, thus providing more time for the hapless extension coders to be assigned additional tasks by their malicious supervisors :wink:

This methodology may provide a solution for issues #2096/#2060.

**Comment by heartacker** [comment]
that will be great, It's been a long time coming.
