### ISSUE TITLE
compile_commands.json based intelliSense is not working with clang-cl

### ISSUE THREAD

**Issue by ziish** [microsoft/vscode-cpptools#2098]
**Describe the bug**
- OS and Version: Windows 7
- VS Code Version: 1.24.0
- C/C++ Extension Version: 0.17.4

I use CMake with ninja and clang-cl to build my project. CMake generates the `compile_commands.json` file for me. 

In my `c_cpp_properties.json` I set:

    "compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "intelliSenseMode": "clang-x64",
    "compilerPath": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"

CMake generates the `compile_commands.json` in the subdirectory `build` with the following content 

	[
		{
			"directory": "C:/projects/project/build",
			"command": "C:\\PROGRA~1\\LLVM\\bin\\clang-cl.exe  /nologo -TP -DNOMINMAX -D_WIN32_WINNT=0x0601 -Isrc\\App -I..\\src\\App -Isrc\\App\\App_autogen\\include /std:c++17 /MDd /Zi /Ob0 /Od /RTC1   /wd4275 /wd4251 /wd4996 /Fosrc\\App\\CMakeFiles\\App.dir\\main.cpp.obj /FdTARGET_COMPILE_PDB -c C:\\projects\\project\\src\\App\\main.cpp",
			"file": "C:/projects/project/src/App/main.cpp"
		}
	]

Now i placed a `foo.h` file beside of `main.cpp` - So it is in the include path. But when I type `#include <f` it is not contained in the suggestions. Tried to figure out what is going wrong for a two day now and have no ideas anymore. The log messages (with `"C_Cpp.loggingLevel": "Debug"`) do not seem to contain anything interesting. It actually does not show any sign of the `compile_commands.json` content. 

I know the description is a bit vague - But if someone with more experience can suggest ways to debug this behaviour I can provide more information.

**Comment by bobbrow** [comment]
Did you try `"intelliSenseMode": "msvc-x64"`?  I believe Clang on Windows attempts to emulate cl.exe and uses the Windows SDK headers, etc.

**Comment by ziish** [comment]
I did - But it did not change the situation. 
Do I need to set the compiler path for msvc-x64 too?

**Comment by bobbrow** [comment]
What is the value of `"browse.path"` in your configuration?  For `#include` suggestions, `"browse.path"` is the data source and `"includePath"` is the filter.

Do you get any suggestions at all?  Our code might not be doing the right thing for clang-cl.exe.

**Comment by ziish** [comment]
`browse.path` is `"${workspaceFolder}"` - Now i am slightly confused. I thought the include directories are completely based on the content of `compile_commands.json`? 

I get suggestions e.g. all standard c++ headers and windows specific headers too. 
Is the language server open source too so i can debug into it? (was not able to locate it)

**Comment by dawaggs** [comment]
I believe I am seeing a similar issue. With the following hello world project setup:

CMakeList.txt:
```
project(std_includes_not_found)
add_executable(std_includes_not_found main.cpp)
```
main.cpp:
```
#include <iostream>
int main() { std::cout << "Hello, world." << std::endl; }
```

And this environment:
- Windows 10
- Version: 1.29.0-insider (user setup)
- C/C++ extension: Version 0.21.0-insiders: November 8, 2018
- CMake Tools extension: Version 1.1.2
- LLVM 6.0.1 for Windows.

If I select the _Visual Studio Professional 2017 - amd64_ kit for CMake Tools, the build works, and <iostream> is found by intellisense.
If I switch to _Clang 6.0.0 for MSVC with Visual Studio Professional 2017 (amd64)_ kit for CMake Tools, the build still works fine but intellisense says, "cannot open source file "iostream".

The Output shows that CppTools is attempting to use my Ubuntu 18.04 WSL installation to configure intellisense, fails, and ends up using the Tag Parser...

> Attempting to get defaults from compiler found on the machine: /usr/bin/clang
> ...
> sending compilation args for D:\BUG-REPORTS\INCLUDE_VARIANT_NOT_FOUND\MAIN.CPP
>   include: C:\USERS\...\APPDATA\LOCAL\PACKAGES\CANONICALGROUPLIMITED.UBUNTU18.04ONWINDOWS_79RHKP1FNDGSC\LOCALSTATE\ROOTFS\USR\INCLUDE\C++\7
>   include: C:\USERS\...\APPDATA\LOCAL\PACKAGES\CANONICALGROUPLIMITED.UBUNTU18.04ONWINDOWS_79RHKP1FNDGSC\LOCALSTATE\ROOTFS\USR\INCLUDE\X86_64-LINUX-GNU\C++\7
> ...
> textDocument/hover
> using Tag Parser for quick info

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
