### ISSUE TITLE
Unable to start debugger because of key "TEMP"

### ISSUE THREAD

**Issue by jhasse** [microsoft/vscode-cpptools#210]
Debugging stoped working for me with 0.9.0 on Windows. I'm getting:

```
Unable to start debugging. Das Element wurde bereits hinzugefügt. Schlüssel im Wörterbuch: "TEMP". Hinzuzufügender Schlüssel: "temp".
```

Sorry for the German, I already have VSCode set to English, but it seems this error message comes from Windows? This is how I would translate it:

```
The element has already been added. Key in dictonary: "TEMP". Key to be added: "temp"
```

This is my launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/build/debug/a.out.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "miDebuggerPath": "C:\\msys64\\mingw64\\bin\\gdb.exe",
                "MIMode": "gdb"
            }
        }
    ]
}
```

**Comment by jacdavis** [comment]
Thanks for reporting this. Unfortunately, I'm not able to repro this on mingw. Can you please enable engine logging and send the last section to us? To do so add this to launch.json: 
"logging": {
                "engineLogging": true
            }

And then check the debug console after it repros.

**Comment by jhasse** [comment]
I've just updated to VSCode 1.5 and now the error is gone. I'll reopen when it comes back :)

**Comment by jhasse** [comment]
VS Code 1.7.2 and C/C++ extension 0.9.3: The error is back.

I've added

```
"logging": {
    "engineLogging": true
}
```

to my launch.json, but no output turned up in the Debug Console.

**Comment by pieandcakes** [comment]
@jhasse This is an issue with running in MSYS and the actual .NET Framework on windows. We use a [Process](https://msdn.microsoft.com/en-us/library/system.diagnostics.process(v=vs.110).aspx) object to spawn the debugger. .NET Framework in windows assumes environment variables are case insensitive and when it creates the process object, it adds them all to a dictionary. In the case of MSYS, it is running a Linux shell which is case insensitive. 

To show your environment variables in MSYS shell, use `printenv` and then to unset the duplicates, use `unset <varname>`.
