### ISSUE TITLE
Case sensitive paths breaks intellisense

### ISSUE THREAD

**Issue by luyui** [microsoft/vscode-cpptools#2106]
Type: LanguageService

This issue is like #1694 but per this [blog](https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/) Windows now supports setting per-directory case sensitive for WSL-Interop.
I have set the workspace case sensitive by command: 
`fsutil file setCaseSensitiveInfo C:\Users\adm\Code\staging\include`
Intellisense seems to still be broken under such paths.
> Unable to retrieve file system information for C:\Users\adm\Code\staging\include. error = -1

- OS and Version: Windows 10 1803 17134.81
- VS Code Version: 1.24.0
- C/C++ Extension Version: 0.17.4
- Other extensions you installed (and if the issue persists after disabling them): None

c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "WSL",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}"
            ],
            "defines": [
            ],
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
This is https://github.com/Microsoft/vscode-cpptools/issues/1994 . There's a suggested workaround in that bug of using a bogus includePath like "/mnt/c/include" to trick us into turning the case-sensitivity on -- does that workaround work for you?

**Comment by luyui** [comment]
@sean-mcmanus sorry missed that issue before posting.
But I tried the mentioned /mnt/c/ trick and it did not work, same error log.
I guess this trick requires the whole path to be case sensitive? I only have part of the include path case enabled.

**Comment by sean-mcmanus** [comment]
I'm able to repro the bug without "/mnt/c/include" in the includePath, but once I add it, the workaround works for me and I get hover/GoToDef working in the case sensitive folder.

My test project has Root/case/test.cpp (case is case-sensitive), and Root/no-case/test.cpp.

Do you know what I'm doing differently?

**Comment by luyui** [comment]
@sean-mcmanus Much thanks for the explain, I didn't understand the workaround correctly, it's working now! I'll close this issue.

**Comment by sarlv** [comment]
Hello. I am using a library where some header files are in uppercase f.e. Fl_Window.H. Unfortunately files with so kind names do not appear in autocomplete. This does not apply to files in lowercase f.e. fl_types.h. Maybe I need to set some params in c_cpp_properties.json for uppercase file names?

**Comment by bobbrow** [comment]
We either do full case-sensitivity, or no case-sensitivity.  It's not separated by upper and lower casings.  If you are having trouble with this, please open a new issue with more details about your problem and we can look into it.  Thanks!
