### ISSUE TITLE
Language Service Crash - No Intellisense RHEL6

### ISSUE THREAD

**Issue by gas6262** [microsoft/vscode-cpptools#2108]
Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
It seems that the cpp tools extension is very difficult to build in RHEL 6 and your provided distribution targets RHEL 7 only.  The langauge server continuously crashes upon start up and Intellisense does not work. We do not have access to internet on our machines - not sure if this is needed or not.

**To Reproduce**
Open vscode in RHEL6  with cpp-tools. After 5 seconds, you will get the error - Language Servicehas crashed 3 times in past 5 minutes. it will not be restarted.

**Expected behavior**
Should not crash and intellisense should work

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
We don't currently support RHEL 6 (too few users, too old), only RHEL 7. It sounds like we may have a dependency on a newer component. Can you run `~/.vscode/extensions/ms-vscode.cpptools-0.17.4/bin/Microsoft.VSCode.CPP.Extension.linux` and see what it outputs? You can also run ldd on that binary to see what the runtime dependencies are.

**Comment by gas6262** [comment]
$  ~/.vscode/extensions/ms-vscode.cpptools-0.17.3/bin/Microsoft.VSCode.CPP.Extension.linux
/home/dgaspard/.vscode/extensions/ms-vscode.cpptools-0.17.3/bin/Microsoft.VSCode.CPP.Extension.linux: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/dgaspard/.vscode/extensions/ms-vscode.cpptools-0.17.3/bin/Microsoft.VSCode.CPP.Extension.linux)
/home/dgaspard/.vscode/extensions/ms-vscode.cpptools-0.17.3/bin/Microsoft.VSCode.CPP.Extension.linux: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/dgaspard/.vscode/extensions/ms-vscode.cpptools-0.17.3/bin/Microsoft.VSCode.CPP.Extension.linux)

$ /lib64/libc.so.6
GNU C Library stable release version 2.12, by Roland McGrath et al.
Copyright (C) 2010 Free Software Foundation, Inc.

Seems the so is a bit dated?

**Comment by gas6262** [comment]
Code folding and syntax highlighting work fine though by the way.

**Comment by sean-mcmanus** [comment]
Yeah, we have a dependency on glibc_2.17 or higher -- via running readelf -a on the binary, it shows it's due to our usage of clock_gettime and the memcpy@glibc_2.14. There are potential solutions to reduce our dependency on those, but I'm not sure if it's a high enough priority for us to fix unless we receive more complaints.

Code folding and syntax highlighting are implemented by VS Code itself via textmate and atom/language-c and not part of the C++ extension binary.

**Comment by Colengms** [comment]
At this time, we do not plan to support RHEL6.  Closing this issue.
