### ISSUE TITLE
CPP tools creates .browse.VC.db and .browse.VC.db-wal

### ISSUE THREAD

**Issue by tonerdo** [microsoft/vscode-cpptools#211]
VSCode Version: 1.4
OS Version: OS X 10.11.5
CPP Tools Version: 0.90

Steps to Reproduce:

Open a new folder in VS Code that doesn't have `.vscode` folder.

Expected Behaviour:
Should leave the folder as is or give notification to setup additional tools e.g. .NET Core debugger

Actual Behaviour:
Creates a `.vscode` folder containing `.browse.VC.db` and `.browse.VC.db-wal` files even when folder contains no C/C++ files.

**Comment by mimorisuzuko** [comment]
I wrote the similar issue at #187 . The answer is as below.

> Which version of cpptools are you using? If you update to the latest (version 0.9.0) this is fixed. Also note that if your Node.js project contains any cpp related files the browse database will be created. If after trying those things your problem still exists please reopen this issue.

**Comment by tonerdo** [comment]
@mimorisuzuko From my comment I'm using the latest. Also these files are created in a Python project and even a .NET Core project.

**Comment by sean-mcmanus** [comment]
I'm not reproing this. I created a new folder with a .cs file and no .vscode folder got created, but it gets created if a .cpp file exists.

**Comment by rkeithhill** [comment]
I'm running 0.9.1 and I'm SEEING THIS AGAIN. I've filed a bug on this before and the issue got fixed and then somehow regressed.  I'm opening a folder for a VSCode extension I'm working on. There are NO .cpp or .h files yet every time I open the folder I get the three files (used to be just two files) @tsolarin lists.

For a repro, clone this project https://github.com/PowerShell/vscode-powershell into a folder and open that folder in VSCode.  That's what I'm doing and the C++ files are getting created.  

I have the following four extensions installed on VSCode 1.5.2 / Windows 10 1607:

```
Ionide.Ionide-fsharp-2.4.2
ms-vscode.cpptools-0.9.1
ms-vscode.csharp-1.4.1
ms-vscode.PowerShell-0.7.2
```

**Comment by sean-mcmanus** [comment]
We haven't been able to repro this yet (seems like you're doing something special), but our next release will create the browse database file in a vscode temp location so this issue should theoretically be fixed.

**Comment by greazer** [comment]
Just as an additional data point, I separately tried to repro based on your information and project and wasn't able to. I've tried opening C++ files while having the VSCode-powershell folder open, as well as closing and reopening VSCode with those C++ file open and I cannot get it to create a browse database. 

As Sean indicated, the upcoming release of the extension will write these files to a location outside the source folder you have open. So while we still shouldn't be creating the browse database for a folder lacking any C++ files, even if we did, they would no longer be cluttering your folder. I assume the latter reason is the main concern you had with the behavior.

**Comment by greazer** [comment]
Didn't mean to close just yet. Waiting to hear if rkeithhill possibly has more details about what repro steps might be missing.

**Comment by rkeithhill** [comment]
I'm not sure what else is different.  Just opening that VSCode-powershell folder is enough to trigger creation of the VC db files.  This is what I see:

![cppextbug](https://cloud.githubusercontent.com/assets/5177512/18695839/bd3bc766-7f71-11e6-8d31-d7ea0e9ba271.gif)

**Comment by vilicvane** [comment]
For me it might be related to package in `node_modules` that contains `.cpp` files.

**Comment by sean-mcmanus** [comment]
It's possible your project may have a "hidden", .c##/.h## files (e.g. part of files.excludes). We've switched to a "lazy" extension loading which should fix any other issues like this.

**Comment by rkeithhill** [comment]
Yup, hidden file:

```
C:\Users\Keith\GitHub\rkeithhill\vscode-powershell\node_modules\node-uuid\benchmark\benchmark-native.c
```

So cloning the vscode-powershell repo wasn't enough.  You'd have to build it to get the node_modules folder populated.

**Comment by sean-mcmanus** [comment]
0.9.2 should cause the browse db to go to the "workspace storage" location, and 0.9.3 will add lazy activation so non-C++ scenarios should no longer be impacted at all.
