### ISSUE TITLE
Understanding debugging ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode-cpptools#2113]
I was reading the documentation and it states; 

> Support for debugging Windows (PDB, Mingw/Cygwin), Linux and OS X applications -- What is meant by this for the C/C++ extension

 What is meant by this ?

**Comment by WardenGnaw** [comment]
The VSCode cpptools extension can debug C/C++ programs created on Windows, Linux and OS X. For Windows, we can specifically debug programs with PDB's or programs created in MinGW or Cygwin.

**Comment by SheepDomination** [comment]
PDB ?
