### ISSUE TITLE
Willl there be refactoring support?

### ISSUE THREAD

**Issue by FlorisColpaert** [microsoft/vscode-cpptools#2115]
Type: LanguageService
Will there be refactoring support in the near future?

**Comment by sean-mcmanus** [comment]
Not in the near future. We're missing multi-translation unit IntelliSense, which is a required component for refactoring to work across translation units.

I think we already have issues tracking this so I'll close this one: https://github.com/Microsoft/vscode-cpptools/issues/296, https://github.com/Microsoft/vscode-cpptools/issues/1162
