### ISSUE TITLE
Feature Request: GDB extended-remote Support

### ISSUE THREAD

**Issue by timedroid** [microsoft/vscode-cpptools#2118]
Type: Debugger

Please add support for connecting to a gdbserver started with the "--multi" argument. Allow users to choose from a list of remote processes to debug.

Ideally this would not even require a local copy of the executable (as GDB could download it from the target if it's not stripped) and be able to attach all child processes as well.

See issue #78 for more context.

**Comment by pieandcakes** [comment]
@timedroid I'll add this as a feature request and see how many requests we get for it. 

This will necessitate changes in [MI Engine](https://github.com/microsoft/miengine).

**Comment by ionutsoare** [comment]
I would also love to see this happening - quite helpful in debugging ARM targets.

**Comment by RohitMoni** [comment]
I'd really like this too: helps with setting up debugging for applications involving multiple docker containers running simultaneous processes.

**Comment by goosenphil** [comment]
I am also interested in this

**Comment by goosenphil** [comment]
For those debugging ARM targets, have a look at the Cortex-debug addon for now.

**Comment by sujiacong** [comment]
I am interested in this

**Comment by pirpyn** [comment]
So am i.

**Comment by Rajveer86** [comment]
Same here, I would love to see this.

**Comment by fbs2016** [comment]
Me too, I am also interested in this function.

**Comment by WardenGnaw** [comment]
Added in https://github.com/microsoft/MIEngine/pull/1260 which shipped in v1.8.2

**Comment by fbs2016** [comment]
Don't see this function in 1.10.7
