### ISSUE TITLE
Memory Window during debug

### ISSUE THREAD

**Issue by iotathome** [microsoft/vscode-cpptools#2120]
Type: Debugger

- OS and Version: Ubuntu 14.04
- VS Code Version: 1.24
- C/C++ Extension Version: 0.17.4

I miss a memory window in the debugging pane to show/edit a block of memory.
See also issue #509, but this was closed without resolving.

**Comment by pieandcakes** [comment]
@iotathome We would need VS Code to provide such a window for us to report the information, which they currently do not and also support from VS Code to report the protocol information. Until that happens, we don't have a way to provide it. That is why #509 is closed.

**Comment by WardenGnaw** [comment]
#509 is still open. Marking this as duplicate.
