### ISSUE TITLE
not support  .c   highlight

### ISSUE THREAD

**Issue by Mycaster** [microsoft/vscode-cpptools#2123]
Issue Type: <b>Bug</b>

.c file.  
it's ok if comment with //, just like this
`//printf("hello,wolrd");`

but highlight will fail with  /****/
`/*printf("hello,wolrd");**/`

Extension version: 0.17.4
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3199)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.68GB (7.41GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe -n|
|Screen Reader|no|
|VM|50%|

</details>

**Comment by bobbrow** [comment]
This works fine for me.  What do you expect to see?

![image](https://user-images.githubusercontent.com/12818240/41303901-712b77d4-6e23-11e8-85e0-5f2abcf8b0b8.png)

**Comment by Mycaster** [comment]
![f7e66dd9-4fb2-40bc-bcd5-e0c4ae493a9c](https://user-images.githubusercontent.com/12558913/41334653-f76cd842-6f18-11e8-8150-877949217a7a.png)

note that space , works fine with one space

**Comment by bobbrow** [comment]
I still don't see the problem.  Can you copy/paste the actual text?  Maybe there's a special character in there that I don't see in the screenshot.

![image](https://user-images.githubusercontent.com/12818240/41359730-f5b5ec34-6edf-11e8-99a6-7d6fd360d08a.png)

**Comment by Mycaster** [comment]
```
int main(int argc, char const *argv[])
{
    /* code */
    return 0;
}
```
this is ok and no need to post a picture



```
int main(int argc, char const *argv[])
{
    /* code **/
    return 0;
}
```

this is not ok , if  there is more than one  continuous `*`  before the last  `/`  ,  it will be shown like this :

![1d7eef24-634e-4c31-ba39-818300d2ad52](https://user-images.githubusercontent.com/12558913/41395385-1a97b14e-6fe0-11e8-870f-cb4a89d2c7a6.png)

it means  comment like this is ok 
```
/**/
/* test */
/* test* */
/* test*** */
/* test
*/
```
but this is not work
```
/***/
/* test **/
/* test
**/
```


file encoding with utf-8, and language mode is c/c++ ( c# is allright )

![172b8b2f-4e68-433a-973c-87382b154f38](https://user-images.githubusercontent.com/12558913/41395621-f6f9e684-6fe0-11e8-9d6b-3db523fa46cc.png)

and no matter whether I disable or enable the c/c++ plugins , it still doesn't work 

![32dbf45b-0cf4-4e25-aa42-831f07db6f8c](https://user-images.githubusercontent.com/12558913/41395777-67fa59a4-6fe1-11e8-920c-7b14494143c4.png)

**Comment by bobbrow** [comment]
I didn't expect this to be an issue related to our extension but was trying to get more details before sending you to the VS Code repository to file an issue.  I still don't see this behavior on my PC, even with the Chinese language pack installed.  My next guess is another extension.  Can you tell us all the extensions you've installed?  It's possible one of them changed the coloring scheme.

**Comment by Mycaster** [comment]
as you mentioned , it's caused  by another extension .... 
I disabled all extensions one by one and found this ..

Dark Pixel 
![image](https://user-images.githubusercontent.com/12558913/41579981-b13ae474-73cb-11e8-9f12-e6b78d0d92f9.png)

highlight will work fine after disabled this extension
well, thanks for your advice

**Comment by bobbrow** [comment]
Thanks for confirming.
