### ISSUE TITLE
c++ intellisense no longer understand typedef'd shared pointer types?

### ISSUE THREAD

**Issue by thecoder138** [microsoft/vscode-cpptools#2128]
I am running vscode for mac: Version 1.24.0 (1.24.0)

After few recent updates my c++ intellisense has stopped giving me suggestion for typedef'd pointer types. 

For example: 
if a certain header file has defined:
typedef std::shared_ptr<my_struct> my_struct_shared_ptr;

If I include this header in some cpp file and try to dereference a my_struct member using -> operator, intellisense spits out:
"expression must have pointer type" 

I had intellisense working for same exact code, without any error squiggle. I tried removing/re-installing/re-starting everything that can restart around me to no success. 

My code compiles and runs just fine.

**Comment by sean-mcmanus** [comment]
What version of the C/C++ extension do you have? What OS are you using? What is your compilerPath setting? What is your intelliSenseMode? Are you using recursive includes (**)? If you set your C_Cpp.loggingLevel to Debug you should be able to see the include paths used in the C/C++ output window. (It's not reproing for me so I need more repro info).

**Comment by thecoder138** [comment]
Sorry for not including relevant info. 

C/C++ extension version: 0x.17.4
Mac OS 10.13.2
compiler path: /usr/bin/clang
IntelliSenseMode: clang-x64
Not using recursive includes.

**Comment by bobbrow** [comment]
I'm still not able to repro the issue.

When you set your loggingLevel to debug and open a file, how does you include path ouptut differ?:

Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/clang'
sending compilation args for /Users/cpptools/test/test3.cpp
  include: /Users/cpptools/test
  include: /Library/Developer/CommandLineTools/usr/include/c++/v1
  include: /usr/local/include
  include: /Library/Developer/CommandLineTools/usr/lib/clang/9.1.0/include
  include: /Library/Developer/CommandLineTools/usr/include
  include: /usr/include
  framework: /System/Library/Frameworks
  framework: /Library/Frameworks
  define: __llvm__=1
...

**Comment by thecoder138** [comment]
Hello,

Sorry initial info I provide was incorrect, the issue is not with std::shared_ptr but with boost::shared_ptr usage as below, please not that intellisense worked perfectly before the recent update. 

Heres how you should be able to reprod the issue, but you'll need a boost library,

file: my_ptr.h
#include <boost/smart_ptr.hpp>
typedef boost::shared_ptr<my_struct> my_struct_shared_ptr;
my_struct_shared_ptr my_ptr;
**my_ptr->a_field = value; // intellisense error: expression must be of pointer type.**
**my_ptr.px->a_field = value; // Works just fine in intellisense.** 

My boost include folder hierarchy is as follows.

boost/smart_ptr.hpp --> includes boost/shared_ptr.hpp 
boost/shared_ptr.hpp ---> this file in turn includes, boost/smart_ptr/shared_ptr.hpp
boost shared pointers is actually defined in boost/smart_ptr/shared_ptr.hpp 

I have all the include paths mentioned correctly in the cpp extension settings file.
