### ISSUE TITLE
Multi-root workspaces and include errors

### ISSUE THREAD

**Issue by PhysicsCodingEnthusiast** [microsoft/vscode-cpptools#2129]
After perusing various documentation and issue threads, I am still quite confused on setting up multi-root workspaces and how to appropriately configure `"C_Cpp.default.includePath"` and `"C_Cpp.default.browse.path"` in the `.code-workspace` settings file in order to remove all `#include` errors (this is on a Windows machine).

I have a folder called AllCodingProjects with subfolders A, B, C, and Shared. I have set up a multi-root workspace that includes folders A and Shared. The `.code-workspace` settings file is located in the AllCodingProjects folder, which I assume is the correct location for that file to be located.

My issue is that the source code files in folder A include files from Shared, but VS Code gives me `#include` errors and tells me to update includePath. I have tried updated both of the above settings as such:

           "C_Cpp.default.includePath": [
			"${workspaceFolder}\\Shared"
		],

		"C_Cpp.default.browse.path": [
			"${workspaceFolder}\\Shared"
		]

to no avail. I have also tried using `${workspaceRoot}`. What am I doing wrong? Thank you!

**Comment by bobbrow** [comment]
Unfortunately, there is no variable that represents the `AllCodingProjects` folder where your .code-workspace file is.  ${workspaceFolder} resolves to `AllCodingProjects/A` for folder `A` and `AllCodingProjects/Shared` for folder `Shared`.

You should be able to address specific folders with the `${workspaceFolder:<folder_name>}` syntax.  (e.g. `${workspaceFolder:Shared}`)

**Comment by PhysicsCodingEnthusiast** [comment]
That worked -- thank you! Just so I know for future reference, is this anywhere in the documentation?

**Comment by sean-mcmanus** [comment]
It's documented at https://code.visualstudio.com/docs/editor/variables-reference . We just re-use the VS Code's variables.

**Comment by PhysicsCodingEnthusiast** [comment]
Ah, that is helpful! I am copying the relevant portion here for future reference:

> ## Variables scoped per workspace folder
> By appending the root folder's name to a variable (separated by a colon), it is possible to reach into sibling root folders of a workspace. Without the root folder name, the variable is scoped to the same folder where it is used.
>
> For example, in a multi root workspace with folders Server and Client, a ${workspaceFolder:Client} refers to the path of the Client root.
