### ISSUE TITLE
No light bulb for green squiggle

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#2132]
- OS and Version: Windows 10
- VS Code Version: 1.24.1
- C/C++ Extension Version: 0.17.5-insiders

Hi, I've just created a new VS Code workspace and I want to configure c/cpp properties for one of the folders in the workspace.  I have created an empty c_cpp_properties.json file in the .vscode folder of the folder I am working on.  Now I need content for that json file. I could either copy from a template (where would I fine one?) or let the CPP extension generate it for me.  I am trying to do the latter but when I view a source file I see green squiggles under my #include statements, but no light bulb:

![image](https://user-images.githubusercontent.com/7724321/41404644-a6c5a0b6-6fbf-11e8-8356-74d45a516c43.png)

So I can't auto-generate the c_cpp_properties.json file.

Is this a bug? How should I proceed?

**Comment by cablefan** [comment]
try press key: Ctrl+Shift+P

**Comment by daldr-ntml** [comment]
That just opens the command palette and allows me to create an empty c_cpp_properties.json file.  I need content 👎

**Comment by sean-mcmanus** [comment]
This is bug https://github.com/Microsoft/vscode-cpptools/issues/2109 . It should be fixed in our next release.

**Comment by daldr-ntml** [comment]
Thanks. It really would be nice to have a means of rolling back to an earlier version.

**Comment by bobbrow** [comment]
All of our releases are available [here](https://github.com/Microsoft/vscode-cpptools/releases), though in this case, I think VS Code changed the behavior of the code actions which exposed this bug in our extension so I'm not sure if rolling back our extension will fix it for you.

**Comment by daldr-ntml** [comment]
Hi Bob, thank you for the link.  Are you planning to release an 'insiders' version with the fix, to get it out quickly?

**Comment by bobbrow** [comment]
We are planning to release 0.17.5 on Monday or Tuesday next week so we hadn't planned to refresh the insiders.

**Comment by daldr-ntml** [comment]
Ok, thanks.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.17.5.

**Comment by daldr-ntml** [comment]
Working nicely now. Thanks.
