### ISSUE TITLE
Red Squiggle with "No operator '<<' matches these operands ..." on compileable and working code

### ISSUE THREAD

**Issue by mjaybaig** [microsoft/vscode-cpptools#2133]
Hello all,

vscode v 1.24.1
c/cpp v 0.17.4
Windows 10 x64

```
#include <iostream>
using namespace std;

int main(){

    string help[] = {"What is", "The meaning"};
    
    cout<<help[0]<<endl;

    return 0;
}
```

This code itself is compiling and working fine. But vscode is having a problem with the cout being used with an array of strings.

![image](https://user-images.githubusercontent.com/16021620/41434503-694baa8e-7035-11e8-9197-94b9dde189bb.png)

It is not showing this behavior with string literals, or even an array of int used with cout.

Just to reassure, the program compiles and runs fine.

**Comment by sean-mcmanus** [comment]
The issue is fixed via adding `#include <string>`. I'm seeing the operator defined there. Are you able to locate where the operator<< (iostream, string) is define? What is your compilerPath/intelliSenseMode? It should match whatever your compiling with.

**Comment by mjaybaig** [comment]
Sean thank you. Yes that fixed it. I don't know what i was thinking using string types without importing the string header. Quite embarrassing.

**Comment by nyck33** [comment]
Actually `#include<string> `did not fix this.

**Comment by sean-mcmanus** [comment]
@nyck33 Can you file a new bug with more repro details?
