### ISSUE TITLE
Synchronize definitions/include paths between c_cpp_properties.json and compile commands.

### ISSUE THREAD

**Issue by hgijeon** [microsoft/vscode-cpptools#2139]
Type: LanguageService
**----- Input information below -----**
There is no way to synchronize definitions in c_cpp_properties.json with makefile/ninja.build/compiler commands. For each cmakelists.txt/makefile, it needs too much time to make c_cpp_properties.json

**Comment by sean-mcmanus** [comment]
You can setup your cmake to export a compile_commands.json file, and when you build it will regenerate and we'll pick up the new includes/defines. https://stackoverflow.com/questions/20059670/how-to-use-cmake-export-compile-commands . Have you tried that yet?

**Comment by hgijeon** [comment]
Oh, I didn't know that... It seems working. Thank you very much for helping!
