### ISSUE TITLE
Lightbulb menu missing

### ISSUE THREAD

**Issue by kghose** [microsoft/vscode-cpptools#2144]
Type: LanguageService

**Describe the bug**
- OS and Version: macOS High Sierra
- VS Code Version: 1.24.1  24f62626b222e9a8313213fb64b10d741a326288
- C/C++ Extension Version: 0.17.4
- Other extensions you installed (and if the issue persists after disabling them): Issue persists after disabling all extensions
- A clear and concise description of what the bug is.

Lightbulb menu missing

**To Reproduce**
1. Create a file with any kind of error
2. Note error squiggle on error
3. Note absence of lightbulb meu

**Expected behavior**
1. Lightbulb menu should appear when cursor hovers over error squiggle

**Comment by sean-mcmanus** [comment]
This is https://github.com/Microsoft/vscode-cpptools/issues/2109 . We plan to release a fix tomorrow.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.17.5.
