### ISSUE TITLE
Specify the implementation file for different target

### ISSUE THREAD

**Issue by ttsshh1990** [microsoft/vscode-cpptools#2148]
In my CPP project it has multiple build targets (like the linux kernel, different targets for different arch).
There are some APIs that shared within those targets but each has their own implementation. When I click 'go to definition' on some functions or variables, it shows a list of files that contains the implementation of them, this is nice. 
But I'd like to go to the one the current target is using directly. There is a config file to specify the IntelliSense includePath for different targets. Can VSCode has a similar file to specify the cpp file for different target? And it could be easy for us to write some script to convert the target's build file to this 'cpp include' file.

**Comment by bobbrow** [comment]
I believe this would be covered by #255.
