### ISSUE TITLE
Failed at stage: getPlatformInfo

### ISSUE THREAD

**Issue by ZCShou** [microsoft/vscode-cpptools#216]
VScode 1.50 insider
Win10

Updating C++ Debugger dependencies...
Failed at stage: getPlatformInfo
Error: Command failed: wmic os get osarchitecture
'wmic' is not recognized as an internal or external command,
operable program or batch file.

Finished
![2016-09-09_085637](https://cloud.githubusercontent.com/assets/8591065/18371982/593cc38c-766b-11e6-9819-0876f6f5b0a7.png)

**Comment by jacdavis** [comment]
Thanks for reporting this. wmic is a utility that should be included in all versions of windows after windows vista. Have you changed your default path setting to remove system32 or anything like that? On my machine, it is located here: C:\Windows\System32\wbem\WMIC.exe

If you execute "where wmic" from a command prompt, is it able to find it?

**Comment by ZCShou** [comment]
@jacdavis 
Thanks for your help .I solved it！！

I need to run VScode as  administrator.

**Comment by jacdavis** [comment]
Weird, afaik, admin shouldn't be required for that.
