### ISSUE TITLE
Unable to start the C/C++ language server.

### ISSUE THREAD

**Issue by pintovillamar** [microsoft/vscode-cpptools#2160]
Type: LanguageService

**Describe the bug**
- OS and Version: Microsoft Windows 10 Home
- VS Code Version: 10.0.17134 Build 17134
- C/C++ Extension Version: C/C++, 0.17.4
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Clang Command Adapter and C++ Intellisense, but none of those worked installing and uninstalling them.

-The problem is basically that when I try to format my file, I can't, and a notification shows up saying "There is no document formatter for 'cpp'-files installed. Also when I launch VS Code with a .cpp file on it, another notification shows up saying "Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Launching server using command c:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.17.4\bin\Microsoft.VSCode.CPP.Extension.exe failed." and "Couldn't start client cpptools: myfile".

**To Reproduce**
1. Go to 'myfile.cpp'.
2. Start coding my file.
3. Trying to make a format with (Alt + Shift + F).
4. Pops out the error.

**Expected behavior**
I just want to the C/C++ plugin to work and make a format of my code, I mean, make it look not messy.

**Screenshots**
![image](https://user-images.githubusercontent.com/30491300/41672943-e8a91948-7480-11e8-8615-36b1be670e1e.png)

**Comment by bobbrow** [comment]
Did you check to see if Microsoft.VSCode.CPP.Extension.exe exists at the path specified in the error and that you can run it by double clicking on it?  (it won't do anything when you run it outside of VS Code, I'm basically just asking you to check permissions on the exe)

**Comment by pintovillamar** [comment]
I have already fix it.

The solution was to deleting the hole folder of the extension (with VS Code closed) **ms-vscode.cpptools-0.17.4** and re-installing from VS Code. 

Thanks @bobbrow anyways.
