### ISSUE TITLE
No lightbulb when clicking on green squiggly for include

### ISSUE THREAD

**Issue by jaynadeau** [microsoft/vscode-cpptools#2163]
Type: LanguageService

- OS and Version:
Windows 10
- VS Code Version:
1.24.1
- C/C++ Extension Version:
0.17.4
- Other extensions you installed (and if the issue persists after disabling them):
Atom One Dark Theme
Partial Diff
SVN
still persists after disabling them
- A clear and concise description of what the bug is.
I am trying to add an include path to fix the green squiggly line under my include statement.
Clicking on it brings up a hover window but no lightbulb.

1. Open a C++ or header file
2. Click on green squiggly line for an include that cannot be found.
3. No lightbuld.

**Expected behavior**
Clicking on green squiggly line under include that cannot be found causes the lightbulb to appear so that the path can be added to the includePath.

**Comment by sean-mcmanus** [comment]
Our next release has this fixed. It's https://github.com/Microsoft/vscode-cpptools/issues/2109 . We might release today or Monday.

**Comment by jaynadeau** [comment]
Great, thank you.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.17.5.
