### ISSUE TITLE
I don`t define __GNUC__  in c_cpp_properties.json but it was definned

### ISSUE THREAD

**Issue by a616781689** [microsoft/vscode-cpptools#2180]
![qq 20180624112510](https://user-images.githubusercontent.com/31605348/41815561-58a9623e-77a1-11e8-90d7-13f9d36d139b.jpg)

**Comment by bobbrow** [comment]
We try to auto-detect your compiler so that IntelliSense will work without any effort on your part.  If we picked the wrong one, you can either add the correct compiler to your `c_cpp_properties.json` file, or to the `C_Cpp.default.compilerPath` VS Code setting.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
