### ISSUE TITLE
inactive region colors should be disabled when Tag Parser fallback is active

### ISSUE THREAD

**Issue by X1aSheng** [microsoft/vscode-cpptools#2181]
Issue Type: <b>Bug</b>

when i use the #if() #elif() #elif() #end , 
the color was wrong. please fix it,you can see it in the pictruce.

Extension version: 0.17.5
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (12.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by X1aSheng** [comment]
![tim 20180624182736](https://user-images.githubusercontent.com/37097029/41818199-4aacf69c-77dc-11e8-9a8a-44f7f8b62415.png)

**Comment by X1aSheng** [comment]
![tim 20180624183650](https://user-images.githubusercontent.com/37097029/41818264-94b25600-77dd-11e8-8d4f-260c1a49b9ac.png)

**Comment by bobbrow** [comment]
When you hover over `ENABLE_LEAK_SENSOR`, `ENABLE_TDS` or any of the other symbols you marked as true, do you get a tooltip that shows they are defined?

If no tooltip appears, can you check and make sure that they are listed in the `"defines"` array in your `c_cpp_properties.json` file?

For example:
```
{
    "configurations": [
        {
            "name": "default",
            "defines": [ "ENABLE_LEAK_SENSOR", "ENABLE_TDS", ... ],
            ...
        }
    ]
}
```

**Comment by X1aSheng** [comment]
![image](https://user-images.githubusercontent.com/37097029/41884211-f8e087f8-7924-11e8-8550-cc50389eb284.png)

**Comment by sean-mcmanus** [comment]
We're not able to repro the problem, so there must be something unusual occurring in your scenario. What happens if you add "#define ENABLE_LEAK_SENSOR" right before the #if (ENABLE_LEAK_SENSOR)? What happens if you use #if (ENABLE_LEAK_SENSOR) in an otherwise empty .c file?

**Comment by X1aSheng** [comment]
sorry .  i can send you the source code pack to you ,it's really an important bug need fix. 
[source20180704.zip](https://github.com/Microsoft/vscode-cpptools/files/2163903/source20180704.zip)

**Comment by attzonko** [comment]
I have this same issue in my code base. I have been trying to reproduce it with simple code and am not having much luck. But I have code which remain inactive even when all the conditions are "true". I will try to find a way to reproduce it with a smaller example. 

As a side note to the original submitter, there is some delay (seconds) before a change of active/inactive happens which seems longer than expected as compared to other intellisense changes.

**Comment by attzonko** [comment]
I played a bit with the source OP provided, and I think in his case the inactive code I found is accurately marked as inactive. Even though the tool-tip pop up shows a value for the define, if you go to where the define is, it itself is inside an inactive code block. You can take a look at what I mean here: https://youtu.be/oj2IUa9oCx8

**Comment by attzonko** [comment]
For my issue I can't seem to figure out why the code is always marked as inactive. For now I am working around it by disabling this feature.

**Comment by bobbrow** [comment]
I think I know what's wrong.  I picked up @1XiaSheng's code and opened the folder.  What happened for me was that a `#include` statement failed to resolve and the IntelliSense engine switched over to the less accurate "fallback" mode (e.g. intelliSenseEngine = Tag Parser).

When we do this, it looks like the inactiveRegions are still being colored, even though they should not be.  The tooltip information displayed is coming from the Tag Parser which does not respect preprocessor conditions.

To reduce the confusion, you should either fix the `includePath` in your `c_cpp_properties.json` so that the `#include` can be found, or you can disable the fallback behavior by doing the following:
* click on the green squiggle under your `#include` statement
* click the lightbulb
* choose "force semantic IntelliSense"

**Comment by sean-mcmanus** [comment]
Inactive regions are now disabled when it falls back to the tag parser (with 0.20.0).
