### ISSUE TITLE
In vscode I could not attach a remote process

### ISSUE THREAD

**Issue by job-gordon** [microsoft/vscode-cpptools#2186]
Type: Debugger
**Describe the bug**
- OS and Version: Win7 business
- VS Code Version: 1.23.1    x64
- C/C++ Extension Version: 0.17.5
- A clear and concise description of what the bug is.
launch.json: 
 { 
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "${workspaceFolder}/src/xxx",
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\linux-gdb.exe",
            "miDebuggerServerAddress": "x.x.x.x:2345",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
use this config, it says "error while processing request 'attach'"

then I use the following LAUNCH config, it's ok, I can debug the remote process when launch it. 
{
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/src/xxx",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\linux-gdb.exe",
            "miDebuggerServerAddress": "127.0.0.1:12340",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }

the "miDebuggerServerAddress"  are accessable.

the arch of remote target is linux-x64, local is win7.

anyone knows how to attach a remote process in vscode? 
In this link, https://code.visualstudio.com/docs/editor/debugging , there is no attach example.

thanks.

**Comment by WardenGnaw** [comment]
For remote debugging, you will want to use the `pipeTransport`. Documentation can be found [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md).

There is a configuration called `Pipe Attach` you can use as a template if you click the `Add Configuration...` in your launch.json.
