### ISSUE TITLE
#ifndef claims to have no #endif to close it

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2193]
I'm on windows 8.1

This isn't the exact code i used, but typing this out claims that #ifndef does not have a #endif to close it
#ifndef FILE_H // "The endif for this directive is missing"
#define FILE_H
#ifdef _WIN32
#pragma once
#endif

**Comment by ghost** [comment]
There is also a red line under #endif stating "the #endif for this directory is missing"

**Comment by sean-mcmanus** [comment]
Yeah, you're missing the 2nd #endif, right?

**Comment by ghost** [comment]
This entire issue would just be my lack of knowledge in programming. I did not know a second #endif was required
