### ISSUE TITLE
Outline doesn't show all items up

### ISSUE THREAD

**Issue by GriffenJohn** [microsoft/vscode-cpptools#2196]
![gif2](https://user-images.githubusercontent.com/36688398/42007464-def7ee78-7ab2-11e8-8aad-f9925e4cee63.gif)
The last two items in outline was out of border when I clicked extension and clicked explorer back.
Change the size of outline window would make them show up again.

**Comment by sean-mcmanus** [comment]
Our extension doesn't populate any outlines -- is this from another extension?

**Comment by GriffenJohn** [comment]
OK, maybe this function is supported by vs code.

**Comment by WardenGnaw** [comment]
This is a preview feature for VSCode. https://code.visualstudio.com/updates/v1_24#_outline-view

You can submit an issue on their [repository](https://github.com/Microsoft/vscode/issues).
