### ISSUE TITLE
Cpp Tools API Repo Private

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#2198]
I was interested in looking at the code for the Cpp Tools API package posted to npm. It gives a github link to a MIT licensed repo, however the repo link does not work, and appears to either be wrong or a private repo. Any timeline on making that repo public?

`https://github.com/Microsoft/vscode-cpptools-api`

**Comment by bobbrow** [comment]
The repo is currently private.  We are working on it.  There is a process we have to go through to publish a new public repo and it's not finished yet.  If you add version 1.2.2 to your package.json npm should download the API for you to look at.

**Comment by bobbrow** [comment]
I also plan to put some more sample code on the landing page too.

**Comment by bobbrow** [comment]
The repo is public now.
