### ISSUE TITLE
Linux Debugging (gdb) - Debug Console should reappear after prelaunch task output

### ISSUE THREAD

**Issue by aaiyer** [microsoft/vscode-cpptools#220]
My launch.json has a preLaunchTask and the output of this task is shown, if it is successful, this output should be hidden and the Debug Console shown. Right now, the output is shown and you have to go and reopen the Debug Console

**Comment by jacdavis** [comment]
This issue was moved to Microsoft/vscode#11900

**Comment by jacdavis** [comment]
Thanks for reporting this. I believe this is an issue with vscode, not with the extension. I've moved the issue over there.
