### ISSUE TITLE
intellisense - overflow for signed int values

### ISSUE THREAD

**Issue by peteer22r** [microsoft/vscode-cpptools#2202]
Issue Type: <b>Bug</b>

In this minimal repro, static_assert fail only in intellisense.
While compyling on any c++ compiler it's ok.
Intellisense reports value for 'actual' as '4294901760' which is obvious overflow for signed int.

```
constexpr signed int make(unsigned int i)
{
      return i << 16u;
}

constexpr signed int expexted = 0xFFFF0000;
constexpr signed int actual = make(0xFFFFFFFF);

static_assert(actual == expexted, "errro");

```
Extension version: 0.17.5
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.17.0-2-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3410)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.72GB (2.91GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bobbrow** [comment]
Looks like the problem has to do with the constexpr function since inlining the bit shift into the assignment of actual makes the static_assert succeed.  `static_assert(4294901760 == expexted)` also works so there's definitely something weird going on in here.  Visual Studio has the same problem, so I'll hand the bug off to them to look at.  Thanks for the concise repro!

**Comment by sean-mcmanus** [comment]
@peteer22r I think Bob reported the bug internally, but I created a public bug on VS at https://developercommunity.visualstudio.com/content/problem/416907/c-intellisense-incorrectly-reports-static-assertio.html -- upvoting that could help get a fix sooner.

**Comment by sean-mcmanus** [comment]
Fixed with Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
