### ISSUE TITLE
Ctrl + click on class name gives me two choices, the class itself, or the constructor

### ISSUE THREAD

**Issue by azydevelopment** [microsoft/vscode-cpptools#2207]
Issue Type: <b>Bug</b>

Repro steps:
* Download [test.zip](https://github.com/Microsoft/vscode-cpptools/files/2148456/test.zip)
* Open folder in VSCode
* Open 1.h
* Ctrl + click CSPIBus
* Notice it gives you two choices, the class definition (which is the desired behaviour), and going to the constructor of that class definition (that's a little weird and I feel like not intended behaviour).
* Open 0.cpp
* Ctrl click "CSPIBus::"
* Notice how it does the same thing. Now that's a bit weird because I'm clearly clicking the class name in the fully qualified name. I don't think it should think I'm trying to go to the constructor

Image example of the one where I click the prefix on the fully qualified constructor.

![image](https://user-images.githubusercontent.com/29720335/42082331-8e628b6e-7b3c-11e8-83c3-4cfcb1af7d9b.png)

Extension version: 0.17.5
VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (1.15GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bobbrow** [comment]
Code navigation doesn't use semantic information right now.  This should be covered by #255.

**Comment by sean-mcmanus** [comment]
Actually, I think there are 2 bugs here.
1. Go to Def on <class>:: should only return "scope" results.
2. Go to Def on a class name without a trailing ( should filter out constructors.
I think these should be pretty easily fixable.

**Comment by sean-mcmanus** [comment]
Yeah, issue 1 was a simple off-by-one bug -- when checking for "::" we find the first ":" but not the 2nd. And the same bug was causing too many results (i.e. functions/types) to appear before a ->. Using ::: incorrectly gives "correct" results. For Issue 2 we can filter out the constructors when it doesn't end with ( or ;.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.17.6.
