### ISSUE TITLE
Not recognize C++11 lambda expression

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-cpptools#221]
VSCode: 1.5.1
OS: Ubuntu 16.04
C/C++ Extension: 0.9.1

I'm writing C++ 11 code and use lambda in my code. The following code is a simple example:

``` cpp
#include <iostream>

int main(int argc, char** argv)
{
    std::cout << "hello, world!" << std::endl;
    const int x = 0;
    const auto f = [&x](int i) { return x + i; };
    std::cout << f(10) << std::endl;
    return 0;
}
```

The code compiles perfectly with `gcc` and `clang` but in VSCode it produces the following warnings and errors:
1. 'auto' type specifier is a C++11 extension [-Wc++11-extension](7, 11)
2. expected expression (7, 20)

Below is a screenshot of this:

![main cpp - cpptest - visual studio code_088](https://cloud.githubusercontent.com/assets/4662568/18409965/2757ae5e-7788-11e6-87db-84ccc24637e0.png)

**Comment by sridmad** [comment]
Do you have a different C++ extension for VSCode installed? VSCode-cpptools does not flag any error or warnings at this time other than for include files it cannot find.

**Comment by renkun-ken** [comment]
It looks like the warnings and errors are produced by `C/C++ Clang`. I'll file an issue there.
