### ISSUE TITLE
Problem in VS code

### ISSUE THREAD

**Issue by Shrey-Viradiya** [microsoft/vscode-cpptools#2215]
Type: LanguageService

**I'm using latest version of VS code but i'm Having some problem like this**

**[Error - 17:53:58] Starting client failed
Launching server using command c:\Users\shrey\.vscode\extensions\ms-vscode.cpptools-0.17.5\bin\Microsoft.VSCode.CPP.Extension.exe failed.**

**Describe the bug**
- OS and Version: Windows 10 home, version 1803
- VS Code Version: 1.24.1
- C/C++ Extension Version: dont know

**Comment by bobbrow** [comment]
Can you check that the file exists and that you have executable rights?  You can also try deleting the `c:\Users\shrey.vscode\extensions\ms-vscode.cpptools-0.17.5` folder and re-installing the extension.

**Comment by Shrey-Viradiya** [comment]
which more info do you need?

**Comment by bobbrow** [comment]
Does `c:\Users\shrey.vscode\extensions\ms-vscode.cpptools-0.17.5\bin\Microsoft.VSCode.CPP.Extension.exe` exist?
Can you double click on it in File Explorer and make it run?

**Comment by Shrey-Viradiya** [comment]
![screenshot 23](https://user-images.githubusercontent.com/40735908/42173292-31a0e774-7e3c-11e8-954b-4b97043a47d8.png)

it shows like this

**Comment by bobbrow** [comment]
(not sure why I missed this update...)

Hmm... it looks like you have access.  Did you install this week's 0.17.6 update and does it still have the same problem?

**Comment by michelleangela** [comment]
We need more information to further investigate this issue.

If you update to the latest version of the extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate your issue.
