### ISSUE TITLE
[Linux] Debugger fails to stop at breakpoint if set on the first line of main()

### ISSUE THREAD

**Issue by tfcollins140** [microsoft/vscode-cpptools#2219]
Type: Debugger
I'm trying to debug C using visual studio code on a Mint VM, code is as follows:

    #include <stdio.h>

    int main(int numargs, char* argvector[])
    {
       printf("test\n");
      return(0);
    }

Compiled with:

    gcc test.c -g -o test

based on the output of ls -l, I can verify that gcc is adding symbols.
When I attempt to debug this program using vs-code using the C/C++ extension, I receive the following error:

    Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
    =cmd-param-changed,param="pagination",value="off"
    Stopped due to shared library event (no libraries added or removed)
    Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.
    Breakpoint 1, main (numargs=1, argvector=0x7fffffffdd18) at test.c:5
    5	  printf("test\n");
    [Inferior 1 (process 8322) exited normally]
    The program '/home/ccsd/test/test' has exited with code 0 (0x00000000).

gcc version: 5.4.0 20160609

vs-c version: 1.24.1

my launch.json file is as follows:

    {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "(gdb) Launch",
                "type": "cppdbg",
                "request": "launch",
                "program": "${workspaceFolder}/grow",
                "processName": "grow",
                "args": [],
                "stopAtEntry": false,
                "cwd": "${workspaceFolder}",
                "environment": [],
                "externalConsole": true,
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                 ]
            }
        ]
    }

uname -a output:

Linux VirtualBox 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

You may note that this issue is potentially similar to the unsolved part of https://github.com/Microsoft/vscode-cpptools/issues/115 .

**Comment by pieandcakes** [comment]
@tfcollins140 Set your breakpoint on the next line (line 6) and it will stop. We automatically set a breakpoint on the first line of the `main()` method so we can setup debugging. The problem is that once we get the debugger setup, we `-exec-continue` which gets us past the first line inside `main()` and unfortunately it causes a step around the printf statement. The workaround is to not set a breakpoint on the first line and instead use `"stopAtEntry": true` if you really wanted to stop at the first line.

**Comment by tfcollins140** [comment]
I had no breakpoint set though? Regardless I still have the same issue in non-test code, even with a break point set on the second line in main.

**Comment by pieandcakes** [comment]
@tfcollins140 I guess i'm not understanding. What error code are you referring to? 

>The program '/home/ccsd/test/test' has exited with code 0 (0x00000000). 

This means that your program exited normally. The window that spawns for your program is tied to the debugger and when debugging ends, that window closes which means you can't see your output.

If you are referring to a different error, please let me know. Everything else in the block you provided is informational from gdb.

**Comment by albe-rosado** [comment]
same here, on ubuntu and solus os, @tfcollins140 are you using the c++ project generator extension?

**Comment by sjt-xfwh** [comment]
i miss the same issue, on linux mint19,when i try to debug , it throuth all break point

**Comment by pieandcakes** [comment]
@sjt-xfwh  did you compile with `-g` ?

**Comment by argelcapela** [comment]
I used the -g flag and here worked very well thanks pieandcakes!
