### ISSUE TITLE
Not all include files found on Ubuntu.

### ISSUE THREAD

**Issue by reporter123** [microsoft/vscode-cpptools#222]
VSCode: 1.5.1
OS: Ubuntu 16.04
C/C++ Extension: 0.9.1

Basically Ubuntu has choosen to use 64bit and 32bit arch specific folders for most header files. I don't know why.
  64bit folder: "/usr/include/x86_64-linux-gnu"
 32bit folder: "/usr/include/i386-linux-gnu"

Theses folders need to be added to "includePath" for include files in these folders to be found by VSCode. clang/gcc give no errors but VSCode complains about missing not finding includes without this change.

**Comment by deepkolos** [comment]
windows7 64bit +1

**Comment by jgoshi** [comment]
In the next release of cpptools (version 0.10.0) we use a default include path of /usr/include which will solve your problem (we will use everything under /usr/include recursively). If you want to be more restrictive you can update your specific include path (as you did).

**Comment by sean-mcmanus** [comment]
Should be fixed in 0.9.2, but there is some other bug that can sometimes cause headers to not be found.
