### ISSUE TITLE
Not consistent C++ code highlighting

### ISSUE THREAD

**Issue by azynheira** [microsoft/vscode-cpptools#223]
VSCode Version: Version 1.5.2 Commit 66f37fd Date 2016-09-12T13:22:54.636Z Shell 0.37.6 Renderer 49.0.2623.75 Node 5.10.0
OS Version: 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:
Have cscode-cpptools installed and check the samples below.

See the slightly different code highlighting for the 2 identical code blocks:
1.
![screenshot from 2016-09-13 09 57 58](https://cloud.githubusercontent.com/assets/346780/18471828/fb00625a-79b3-11e6-926e-47b093ea39e2.png)

2.
![screenshot from 2016-09-13 10 03 00](https://cloud.githubusercontent.com/assets/346780/18471831/fed1cbe4-79b3-11e6-82b9-c41276d5bacc.png)

I already raised this in Visual Code (https://github.com/Microsoft/vscode/issues/11934#event-787363460) but it was reported that this is an issue with an extension and its correct. I have uninstalled vscode-cpptools and the issue was gone. Reinstalled and the issue was back.

Kind Regards,
Pedro

**Comment by sean-mcmanus** [comment]
I'm not able to repro that. Can you provide a small repro?

**Comment by azynheira** [comment]
Try with the attached source code. And I get the snapshot attached. Put the source code in a separate directory.
[example.cpp.txt](https://github.com/Microsoft/vscode-cpptools/files/470835/example.cpp.txt)

![screenshot](https://cloud.githubusercontent.com/assets/346780/18492099/e4ff31ce-7a09-11e6-901b-1bad38b92fa8.png)

Tell me if it works.
Pedro

P.S. -  I think its the 'color' from the 'no reference found' that is spreading to the line below thast is causing this issue.

**Comment by sean-mcmanus** [comment]
Yes it doesn't repro for me with just the C++ extension. What extension is generating the "no references found"? It looks like that other extension may be causing an issue or there's some sort of interaction with ours.

**Comment by azynheira** [comment]
Yes, the problem is with https://marketplace.visualstudio.com/items?itemName=kisstkondoros.typelens extension.  Close this issue mea culpa!

**Comment by sean-mcmanus** [comment]
Ok.
