### ISSUE TITLE
Adopt new DocumentSymbol API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-cpptools#2230]
With the 1.25 release we have finalised the API for the [outline tree](https://code.visualstudio.com/updates/v1_25#_outline-view). A `DocumentSymbolProvider` should now return [document symbols](https://github.com/Microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/vscode.d.ts#L2474) which can represent a hierarchy and that can differentiate between the full range of  a symbol and the selection range, e.g. the name of a function. 

*Note* that we synthesise trees using range-containment when a provider returns `SymbolInformation`-objects and that that isn't perfect. Adopting the new API makes the outline more robust and support features like follow-cursor and diagnostics association. 

Let me know if need more information is needed. Happy Coding!

**Comment by jrieken** [comment]
This depends on https://github.com/Microsoft/language-server-protocol/issues/327

**Comment by bobbrow** [comment]
What are the rules to update the outline view?  I turned it on for a bit and it seemed to be stale as I added new code items to the file.  We currently only update our document symbols list when the file is saved, but the outline didn't update when I saved the file.

EDIT:
Ah, I get it now.  We use the LSP to communicate with VS Code, so we're using the SymbolInformation stuff you mentioned above.  I'm not sure if/when the `vscode-languageclient` module will support this.  Is it on Dirk's backlog to add this?

**Comment by bobbrow** [comment]
Hmm... We use the `vscode-languageclient` npm module to interface with VS Code.  I don't see this new API in the LSP.  Am I missing something?

**Comment by jrieken** [comment]
Yeah, Dirk is on it. I hope the LSP updates soon

**Comment by go2sh** [comment]
Microsoft/language-server-protocol#327 is fixed. This feature would rock the world. Especially for editing large files and classes.

**Comment by micmelesse** [comment]
Where should I start if I wanted to help with this? This feature would be very useful for me.

**Comment by sean-mcmanus** [comment]
@micmelesse It requires changes to our closed source code, so unfortunately you can't help unless you work for Microsoft. We sometimes mark bugs that could be fixed with our open source typescript with "help wanted".

**Comment by lijh8** [comment]
Source Insight* provides two outline views, one for symbols inside file, another for project wide.
It seems it takes you forever to implement the outline / symbol view in your code project.
What is your plan to implement on this?

With this feature, your code project is a source code editor. 
Without it, your code is just another text editor.

* https://www.sourceinsight.com/wp-content/uploads/2016/03/mainappwide1130.png

**Comment by bobbrow** [comment]
We prioritize features based on the number of upvotes.  Please add your +1 to the original post to voice your support for this feature.

**Comment by runelabs** [comment]
@bobbrow this issue is currently [placed at #12](https://github.com/Microsoft/vscode-cpptools/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) in terms of :+1:. Does that mean that it is finally being considered now?

The issues ahead of this one have been around for 2+ years, so I don't understand how the prioritization process actually is supposed to work though... You guys use some weighting and dependencies as well, right? Perhaps milestone-labeling could be helpful for clarifying - so that so it doesn't start to seem like this is just an issue graveyard/gulag.

**Comment by sean-mcmanus** [comment]
@runelabs Being number 12 means there are 11 features with higher priority (along with feedback received from our survey). But this issue might be quick to fix compared to the others so that makes it more likely to get finished sooner. I don't know enough about out schedule to put it on a milestone date yet, but we will add it once we figure out our plan for the next few months.

**Comment by VinayGupta23** [comment]
If fixing this solves #2556 and #2401, then I am up-voting this. I intend to use VS Code as a full-time editor for my C/C++ code base, but lack of this feature makes it really hard to navigate the code :(

**Comment by sean-mcmanus** [comment]
@VinayGupta23 Yeah, those issues should be fixed via this issue.

**Comment by goretkin** [comment]
> @micmelesse It requires changes to our closed source code, so unfortunately you can't help unless you work for Microsoft. We sometimes mark bugs that could be fixed with our open source typescript with "help wanted".

Could you clarify which part is closed source?

**Comment by sean-mcmanus** [comment]
@goretkin The code that is in Microsoft.VSCode.CPP.Extension.* and Microsoft.VSCode.CPP.IntelliSense.Msvc.*.

**Comment by CelticMinstrel** [comment]
It's not entirely clear from the opening post, but this issue is about making the outline hierarchical, right?

**Comment by sean-mcmanus** [comment]
@CelticMinstrel Hierarchical is one aspect, but other issues would be fixed as well via switching to the newer API that returns more info about symbol ranges, such as breadcrumbs.

**Comment by CelticMinstrel** [comment]
Oh yeah, I noticed when the new breadcrumbs showed up that it doesn't tell me which function I'm in.

**Comment by HasanChoton** [comment]
Please support

**Comment by lmlong** [comment]
the outline should not be plain,  it shall be a tree like view  that have the member/methods  unders the class name . Currently I cannot find a specified method through the outline as many similar classes are in one big cpp file

**Comment by bobbrow** [comment]
The fix for this will be in 0.26.0.

**Comment by sean-mcmanus** [comment]
The fix is available in https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders .

**Comment by sean-mcmanus** [comment]
Improved document symbols are available with 0.26.0.

**Comment by psclkhoury** [comment]
@sean-mcmanus I am using 0.26.0 but the `Follow Cursor` option in the outline is not working.

**Comment by awmorgan** [comment]
This 0.26.0 removed Alt+N C/C++ Navigate...

Is there the new way to do what the 0.25.1 Alt+N keyboard shortcut did?

Ctrl+Shift+O is close to previous functionality, but it seems to have dropped the declaration qualifier that was so you can see the difference between declaration and definition in the symbol list.

**Comment by bobbrow** [comment]
@psclkhoury can you open a new issue with more information about your problem?  We've tested out the `Follow Cursor` feature in the Outline view and it is working for us.  There may be something special about your code that we're not handling well.
![image](https://user-images.githubusercontent.com/12818240/67044683-a77ff700-f0e1-11e9-81ae-403eabbd1bfe.png)


@awmorgan, there is a command "Focus Breadcrumbs" that you can use in place of the old Navigate command.  The default key combo is <kbd>CTL</kbd>+<kbd>SHIFT</kbd>+<kbd>.</kbd>, but you can map that to <kbd>ALT</kbd>+<kbd>N</kbd> if you prefer that key combo instead.

**Comment by psclkhoury** [comment]
@bobbrow I realized that it is only not working in some files, I will try to see what is causing it and then open a new issue. Thanks
