### ISSUE TITLE
GDB pretty-printer slow // Natvis alternative?

### ISSUE THREAD

**Issue by sheinzle** [microsoft/vscode-cpptools#2231]
I am having performance issues when debugging my C++ extensions for our Python project (VSCode 1.25.0, Ubuntu 18.04)

In a nutshell, stepping over to the next line takes up to 5 seconds. Doing the same in command line gdb (with pretty printing), stepping over the same lines executes instantaneously.

I am still trying to reproduce the problem with a smaller test-file, however without luck so far. Anybody experienced the same problem?

I noticed that VSCode also supports Natvis. As a workaround, I tried the example from the Microsoft page 
```xml
<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010"> 
<Type Name="std::vector&lt;*&gt;">  
    <DisplayString>{{ size={_Mylast - _Myfirst} }}</DisplayString>  
    <Expand>  
        <Item Name="[size]" >_Mylast - _Myfirst</Item>  
        <Item Name="[capacity]" >_Myend - _Myfirst</Item>  
        <ArrayItems>  
            <Size>_Mylast - _Myfirst</Size>  
            <ValuePointer>_Myfirst</ValuePointer>  
        </ArrayItems>  
    </Expand>  
</Type>  
</AutoVisualizer>
```

The visualizer is included, however it doesn't yield what I am looking for - see image below

![screenshot_2018-07-06_10-50-11](https://user-images.githubusercontent.com/4661954/42369491-6c095ac4-810a-11e8-8078-fab2b9b28051.png)

Sorry to post this question here, but I haven't found any resources on Natvis/VSCode that helped me.

**Comment by pieandcakes** [comment]
@sheinzle It looks like instead of _Mylast and _MyFirst it might be _M_start and _M_finish in your natvis. If you update that does it work?

There's an [article](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/natvis/Natvis.md) in our documentation that might help you get started. It points to the full Natvis documentation.

**Comment by sheinzle** [comment]
@pieandcakes - Thanks for the link to the articles, that's where I got the `std::vector` example from. 

You're right, the Linux implementation of std::vector uses `_M_start`/`_M_finish` (actually `_M_impl._M_start`). 

Here's the complete example, maybe somebody else finds this useful:

```xml
<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010"> 
<Type Name="std::vector&lt;*&gt;">  
    <DisplayString>{{ size={_M_impl._M_finish - _M_impl._M_start} }}</DisplayString>  
    <Expand>  
        <Item Name="[size]" >_M_impl._M_finish - _M_impl._M_start</Item>  
        <ArrayItems>  
            <Size>_M_impl._M_finish - _M_impl._M_start</Size>  
            <ValuePointer>_M_impl._M_start</ValuePointer>  
        </ArrayItems>  
    </Expand>  
</Type>  
</AutoVisualizer>
```

Performance is good with Natvis now. Thanks for the quick help!

**Comment by pieandcakes** [comment]
@sheinzle Thanks! Let me know if you need more help. Closing for now.
