### ISSUE TITLE
Whatever you did, breaks everything ...

### ISSUE THREAD

**Issue by kghose** [microsoft/vscode-cpptools#2233]
(Folks, I know this is not helpful, but I just don't have the time to diagnose the errors when a massive breakage of functionality occurs with a new version of VSCode + cpptools. Here's my best guess ...)

The update at the start of this month broke most things related to the language service (the "error squiggles"). I think what is happening is that the older version relied on `c_cpp_properties.json file` while the newer version relies on `${workspaceFolder}/debug_build/compile_commands.json` (which seems to be weirdly build specific) but this migration broke things inside. 

<img width="463" alt="screen shot 2018-07-06 at 10 38 35 am" src="https://user-images.githubusercontent.com/664644/42384826-0f6b9cce-8109-11e8-87f1-ef3c2c15812b.png">

The primary problem is that when cpptools can't find an include directory, when I add the directory using the widget it gets added to the `c_cpp_properties.json file`, but this has no effect (despite what it claims in the message)

I completely removed my .vscode directory and allowed the extension to remake it. Same issues came back.

- OS and Version: macOS 10.13.5 (17F77)
- VS Code Version: Version 1.25.0 (1.25.0)
- C/C++ Extension Version: 0.17.6
- Other extensions you installed (and if the issue persists after disabling them): I've disabled all extensions but this one.

This makes cpptools unusable for me :(

Thanks!

**Comment by kghose** [comment]
Ok, the way I was able to go back to the original (working) state, was to blow away the "compiler" section. I compile by hand, so I don't need this and I don't know how it got there. 

I don't understand what changed to create this behavior, but it is pretty disruptive.

**Comment by kghose** [comment]
Actually, that just hides the problem: the error squiggles go away but it's clear that cpptools can't do it's language services because it doesn't know where the definitions are coming from.

**Comment by bobbrow** [comment]
We added a feature to auto-detect a compile_commands.json file and use it for you, but a consent dialog is supposed to appear first.  You should be able to dismiss that dialog and not be bothered again.  If you did accidentally allow it, you should be able to remove the `compileCommands` property from `c_cpp_properties.json` to disable the compile_commands.json file.

Let me know if that helps, and especially let me know if you didn't see the consent dialog.

**Comment by kghose** [comment]
Hi @bobbrow thanks for replying.

I've reinstalled vscode and the cpptools extension and I do get the dialog. 

I've removed the `.json` file in the build directory and the entire `.vscode` directory and restarted. 

Things are back to normal now - autocomplete and static checking works. 

I've done this before but without removing the `.json` in the build directory. I suspect that was the critical part. Removing this section from `c_cpp_properties.json` did not help.

It's possible that I clicked "yes" to that dialog at some point, but I don't see how it could break things so badly.

**Comment by bobbrow** [comment]
By accepting that dialog, you are telling the extension that the IntelliSense config for the whole workspace should be available in that `compile_commands.json` file.  There is no way for us to know whether that file is up-to-date or not, but we will revert back to using `c_cpp_properties.json` if the file you've opened isn't serviced by the `compile_commands.json` file (which is what happened when you got the message box in the screenshot above).

**Comment by kghose** [comment]
@bobbrow I suspect that that last part is not working - the fallback to the `c_cpp_properties.json` may be failing. It was only when I deleted `compile_commands.json` did things go back to working. Also, the widget that allows you to add include paths when you click on the error squiggles seems to alter `c_cpp_properties.json` and not `compile_commands.json`

**Comment by bobbrow** [comment]
Yes, the widget intentionally does not alter `compile_commands.json`.  `compile_commands.json` is a file produced by your build system and we have no knowledge about that at this time.

But to address the fallback issue.  Can you tell me step by step what you are doing when this happens?  Are you opening a .cpp file or a .h file?  Do you see the warning message that compile_commands is not being used?  Can you also try running through the issue with `"C_Cpp.loggingLevel"` set to `"Debug"` and take a look at the Output window with the C/C++ filter applied?  The extension will print out which include paths/defines were selected when compiling the source file for IntelliSense.

**Comment by kghose** [comment]
Hi @bobbrow 

1. I'm opening a `.cpp` file when this happens. 
1. I see the dialog that I pasted initially
1. From then on, I can't get rid of the error squiggles because clicking "add to incudePath" alters `c_cpp_properties.json` but does not seem at take effect.
1. This all goes away by deleting `compile_commands.json`
1. Once `compile_commands.json` is deleted, I actually do not see any options to get it back - not that I am eager to.

**Comment by bobbrow** [comment]
But is the `"compileCommands"` property set in your configuration in `c_cpp_properties.json`?

**Comment by kghose** [comment]
Hi @bobbrow  thanks for responding. I got this behavior both when there was a `compileCommands` section and when I deleted it. I'm happy to try and replicate with a fresh minimal project - I would need a pointer on how to get the `compileCommands` section and the `compile_commands.json` - I did not put these in manually and whatever automation triggered their creation, I did not put in motion deliberately. I use cmake and invoke compilation manually.

**Comment by bobbrow** [comment]
So you're saying that the extension is using your `compile_commands.json` file even when you don't have `"compileCommands"` set in your `c_cpp_properties.json`?

And easy way to try this out in a new workspace is to just copy the `compile_commands.json` file into the new workspace and see if the extension starts trying to use that instead of the stuff in `c_cpp_properties.json`.

**Comment by kghose** [comment]
@bobbrow while trying to replicate, I had some interesting experiences and I'll bundle them here before trying to proceed further.

# Path auto magic
VSCode seems to do some auto-magic for include paths without manually adding them and even without a CMakeLists.txt file. I created a simple project

```
.
|____dir2
| |____b.hpp
|____dir1
| |____a.hpp
|____main.cpp
```

`#include "a.hpp"` briefly shows the error squiggle and then disappears. I thought this was a bug, but I found that code sense actually parses the data in `dir1/a.hpp`. Is this expected?

<img width="759" alt="screencapture" src="https://user-images.githubusercontent.com/664644/42465403-dd3b6d4c-8379-11e8-8fc9-241d83eece23.png">

Without the error squiggles I couldn't automatically create the `c_cpp_properties.json` file.

## clang-format working without being enabled

Can an extension work even if it is disabled? I have clang-format (`xaver.clang-format`) installed but disabled - for all workspaces. I have `"editor.formatOnSave": true` and when I hit save the file is auto formatted. In this clean workspace I don't have a `.clang-format` file either. Is cpp-tools now automatically calling `clang-format` by itself - so we no longer need this extension?

Thanks!

**Comment by bobbrow** [comment]
Squiggles may appear briefly when a file is opened and we are indexing the workspace.  The default experience will try to auto-find header files for you, so that you don't have to play around with `c_cpp_properties.json`.  This is normal behavior.  You can still create a `c_cpp_properties.json` file by opening the command pallete: <kbd>CTL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> and selecting "C/Cpp: Edit Configurations..."

Did you change the `"C_Cpp.formatting"` setting?  By default the extension enables formatting via clang-format.  We've actually had this feature for a couple of years.  It is configurable even without a .clang-format file via the `"C_Cpp.clang_format*"` settings

**Comment by kghose** [comment]
@bobbrow 

> By default the extension enables formatting via clang-format.

Very interesting! I guess I did not need that extension after all! - all that extension may have done is set `"editor.formatOnSave": true`. I have `"C_Cpp.formatting": "Default"` (the software default I believe). Naturally, because of my ignorance, no `C_Cpp.clang_format*` settings have been touched. In my actual project I have a `.clang-format` file. 
 
## The main thread
1. Use `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=YES ..` to create the `compile_commands.json`
1. Click on `compile_commands.json` and type yes to the dialog
1. The appropriate line is added to `c_cpp_properties.json`
1. Remove `"command"` and `"file"` from build line in `compile_commands.json`. Note message when switching to `main.cpp`
1. Remove omnibus include path from `c_cpp_properties.json`
1. Note error squiggle comes back
1. Resolved using add to `includePath` as desired.

So I am unable to replicate this and will close it. I'm puzzled by what dogged me for about a week in my actual project. If it pops up again, I'll try a systematic search and reopen.

@bobbrow thank you very much for your time!
