### ISSUE TITLE
Pre-compiled headers and defines

### ISSUE THREAD

**Issue by Yuri6037** [microsoft/vscode-cpptools#2236]
Type: LanguageService
**----- Input information below -----**
**Describe the bug**
- OS and Version: Ubuntu 18.04 (Kernel 4.15.0-23-generic)
- VS Code Version: 1.25.0-insider
- C/C++ Extension Version: 0.17.6
- Other extensions you installed (and if the issue persists after disabling them): None except C/C++ Support
Hello,
I'm trying to use Visual Studio Code for a large project. This project is cross-platform and uses a pre-compiled header.
I used the property "forcedInclude" to specify an absolute path to the required pre-compiled header.

However It seem that IntelliSense is unable to resolve defines (specified through c_cpp_properties.json) in the headers included by the pre-compiled header, resulting in all classes defined to be named "ENGINE_API" which was supposed to be replaced by a compiler attribute.

Also there seem to be another problem in the pre-compiled header : a typedef of a typedef previously defined in the same file is not resolved ("identifier "xxx" is undefined").

Thanks.

**To Reproduce**
For the first problem just create a pre-compiled header that includes other headers with use of defines specified in c_cpp_properties.json
Here is my c_cpp_properties.json (it has been automatically generated by my own tool) : https://pastebin.com/RDNFpYHs
For the second problem create a typedef dependent on another typedef in the same file.

**Expected behavior**
I expected the extension to correctly resolve the dependent typedef type and the pre-compiled header defines.

**Comment by bobbrow** [comment]
Sorry, it appears this issue slipped past us.  I attempted to reproduce your problem on Windows and Linux with version 0.17.7 of the extension and have not been successful.  Perhaps you can provide some additional information.

This is what I used:

**c_cpp_properties.json**
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "ENGINE_API=__attribute__((visibility(\"default\")))"
            ],
            "forcedInclude": [
                "${workspaceFolder}/preinclude.h"
            ],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**preinclude.h**
```
#include "preinclude2.h"
```

**preinclude2.h**
```
typedef int my_int;
typedef my_int my_int2;

class ENGINE_API test
{
};
```

**main.cpp**
```
int main()
{
    my_int2 n = 100;
    test t{};
    return n;
}
```

**Comment by Yuri6037** [comment]
You're missing an "env" key in your c_cpp_properties.json ? Or is the tutorial I followed to auto-generate c_cpp_properties out-dated ?

EDIT : I'm going to try using your c_cpp_properties.json adapted with the additional compilation tools.

EDIT2 : Apparently now it works when using your c_cpp_properties.json, however there's just one "bug", not impacting intelligence but instead the code highlighter. Indeed class names are no longer highlighted in green instead it highlights the macro ENGINE_API in green, when you remove the macro it highlights green...
Anyways thank you very much for your c_cpp_properties.json sample, as it works better than the samples I found in tutorials...

EDIT3 : Just updated to latest VSCode Insiders, everything broken back to the initial issue... With one thing even worse, this time headers are no longer found !!

EDIT4 : I regenerated the c_cpp_properties.json with VSCode and it works now, after adding manually the defines and the path to the Engine includes. The thing that is weird, is why does VSCode bug when I load it on a folder with a .vscode generated by an external tool, and does not bug when I let it generate the base files and I add the missing parts manually ?

**Comment by sean-mcmanus** [comment]
Bob is on vacation, but he could follow up when he gets back next week.

The C++ code highlighter/colorizer is implemented in VS Code via https://github.com/atom/language-c/issues and not our extension.

I'm not sure how the VS Code Insiders could change the C/C++ behavior-- do you mean the 0.17.8-insiders of our extension?

If there is a bug here, I'm not sure what the repro steps are involving the external tool. Maybe our file watcher isn't picking up the changes to c_cpp_properties.json when it's modified by the external tool?

**Comment by bobbrow** [comment]
Hi @Yuri6037,

* "env" is not a required field.  I removed it in my c_cpp_properties.json because it wasn't needed.
* Which external tool is generating your .vscode folder (and your c_cpp_properties.json, I assume)?  We don't support any extensions that write to c_cpp_properties.json, so if you are having issues with that, you should follow up with the extension that is doing it.
* RE: EDIT4: Can you diff the two files (generated by external tool vs. VSCode + manual edits) and see what is different?  That might help you discover the bug in the external tool.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
