### ISSUE TITLE
Add browse.path API for CustomConfigurationProviders

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#2237]
Type: LanguageService
**----- Input information below -----**

Currently there is no API for passing browse.path information from a "CustomConfigurationProvider". The only way to pass it in is to populate the c_cpp_properties.json file. Ideally there should be an API to allow this to be passed in memory.

**Comment by chkp-roic** [comment]
Hi @bobbrow , do you know if and when this feature is planned?
I need this feature for a project and I might implement it myself or search some sort of a workaround to this.

**Comment by bobbrow** [comment]
As we speak, I am working on version 2 of the API which includes this feature.  Expect an update this week with support in cpptools rolling out in September.

**Comment by chkp-roic** [comment]
Thanks for the update!

**Comment by bobbrow** [comment]
support for this has been committed (#2531)

**Comment by sean-mcmanus** [comment]
The v2 API support has shipped with 0.19.0.

**Comment by sherryyshi** [comment]
thanks!
