### ISSUE TITLE
API for cpp.hint for CustomConfigurationProviders

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#2238]
Type: LanguageService
**----- Input information below -----**

Can there be an API or some other way for CustomConfigurationProviders to provide cpp.hint information for expanding macros? Currently the only way to provide this information is to write to the cpp.hint file, which is in the extension install directory, and would cause VSCode to alert the user that their extensions have been modified and ask them to reload.

**Comment by sean-mcmanus** [comment]
Do you want to change the cpp.hint file used or simply add an additional cpp.hint file? The current workaround is to add the cpp.hint file in the user's workspaceFolder root (which appends and doesn't replace the shipped cpp.hint). We could change it to check the .vscode folder as well. We could also add a cppHintPath setting or property: https://github.com/Microsoft/vscode-cpptools/issues/640

**Comment by sherryyshi** [comment]
Editing the current cpp.hint file is not ideal because it would trigger a reload prompt. I think either detecting a cpp.hint file in the .vscode folder or adding a cppHintPath property in c_cpp_properties.json would work for our purposes. Also, what about adding an API in CustomConfigurationProvider? That way all the communication between cpptools and providers would be in one place?

**Comment by busticated** [comment]
being able to manage a custom `cpp.hint` file / instructions via `CustomConfigurationProvider` would be helpful to me as well 👍 

my use-case is similar - i have a handful of macros that intellisense cannot decipher but in my case i manage intellisense configuration on behalf of my users based on their project setup which they can (and do!) change fairly often. the upshot being that trying to handle this via the standard `c_cpp_properties.json` is unwieldy (perhaps VSCode's new "command variables" - [docs](https://code.visualstudio.com/docs/editor/variables-reference#_settings-command-variables-and-input-variables) - could help here?)

**Comment by sean-mcmanus** [comment]
In case anyone doesn't know, "cpp.hint" is only used for "global symbols" saved to our database when our "Tag Parser" is run and not the IntelliSense process for a translation unit, so it can fix failures with Go to Symbol and Go to Definition outside of the current translation unit. The "IntelliSense" engine needs to get the macros via the includePath, forcedInclude, etc..

The tag parser will search up the parents paths of the file it's trying to parse for a cpp.hint...that is the only mechanism currently to supply that (other than editing the "global" hint file in our extension's installation directory). And the doc page is at https://docs.microsoft.com/en-us/cpp/ide/hint-files?view=vs-2017 .

**Comment by busticated** [comment]
@sean-mcmanus i'm probably misunderstanding some nuance but fwiw i got here after finding https://github.com/Microsoft/vscode-cpptools/issues/2876

i'll open a new issue documenting my exact scenario 👍
