### ISSUE TITLE
“Configure your IntelliSense settings to help find missing headers.” should not show if there are CustomConfigurationProvider extensions

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#2240]
Type: LanguageService
**----- Input information below -----**

This message directs users to edit their c_cpp_properties.json file, which might conflict with CustomConfigurationProvider behaviors.

**Comment by sean-mcmanus** [comment]
Sounds like this will be fixed via https://github.com/Microsoft/vscode-cpptools/issues/2350 .

**Comment by bobbrow** [comment]
Yes a combination of #2350 and #2324 (fixed) will address this.

**Comment by sean-mcmanus** [comment]
@bobbrow This is fixed now, right?

**Comment by bobbrow** [comment]
Yes.  The providers will need to update to the v2 API to get the fixed behavior.

**Comment by MSeutin** [comment]
I have a mac and I have this erro on my vscode.  the thing is I am a newbie so I do not understand API, or #2350.  can someone give me simple steps to fix this?
