### ISSUE TITLE
gdb error: Unrecognized format of field "id" in result

### ISSUE THREAD

**Issue by huili80** [microsoft/vscode-cpptools#2244]
Getting something like the following consistently on some code path (but not others):

ERROR: Error while trying to enter break state. Debugging will now stop. Unrecognized format of field "id" in result: result-class: done
threads: [{id=1,target-id=Thread 0x7f1b0fc19740 (LWP 39409),name=...

**Comment by WardenGnaw** [comment]
Can you enable trace logging and copy the output here?

You can do this by adding the following to your launch.json
```
"logging": {
   "trace": true,
   "traceResponse": true
}

**Comment by huili80** [comment]
I synced my workspace to the latest revision this morning and for some reason I can no longer reproduce this error. I'll see if I can roll back my workspace to reproduce it, or encounter it again in the future. If/when it does happen again, I'll enable trace logging and post the output back here.

**Comment by WardenGnaw** [comment]
Sounds good. I'll mark this as needs more info for now.

**Comment by huili80** [comment]
Was able to reproduce the error. Output as follows.

E output: {"category":"stderr","output":"ERROR: Error while trying to enter break state. Debugging will now stop. Unrecognized format of field \"id\" in result: result-class: done\r\nthreads: [{id=1,target-id=Thread 0x7f1f2a213740 (LWP 34914),name=...,frame={level=0,addr=0x00000000009e9b70,func=...,args=[{name=this,value=0x7fff0324a3c0},{name=m,value=... = {...}}],file=...,fullname=...,line=127},state=stopped,core=8}]\r\ncurrent-thread-id: 1\r\n\n","data":null,"type":"output"}
ERROR: Error while trying to enter break state. Debugging will now stop. Unrecognized format of field "id" in result: result-class: done
threads: [{id=1,target-id=Thread 0x7f1f2a213740 (LWP 34914),name=...,frame={level=0,addr=0x00000000009e9b70,func=...,args=[{name=this,value=0x7fff0324a3c0},{name=m,value=... = {...}}],file=...,fullname=...,line=127},state=stopped,core=8}]
current-thread-id: 1
E output: {"category":"console","output":"Debugger has disconnected from the program ''.\n","data":null,"type":"output"}
Debugger has disconnected from the program ''.
E exited: {"exitCode":0,"type":"exited"}
E terminated: {"type":"terminated"}
E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.50719.1","VS.Diagnostics.Debugger.HostVersion":"14.0.50719.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":0},"type":"output"}
C disconnect: {"restart":false}
 R: {"success":true,"message":null,"request_seq":8,"command":"disconnect","body":null,"running":false,"refs":null,"seq":0,"type":"response"}

**Comment by huili80** [comment]
any updates on this?

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
