### ISSUE TITLE
No definition problem

### ISSUE THREAD

**Issue by h2s0109** [microsoft/vscode-cpptools#2245]
Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: window 10
- VS Code Version:1.25
- C/C++ Extension Version:0.17.6
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Provide a code sample including configuration files such as c_cpp_properties.json*
go to definition is not work.
please see below figure.
I attach the code for your investigation.

![image](https://user-images.githubusercontent.com/21095801/42456759-a8b5131e-83d0-11e8-854c-43bfc269c938.png)
[0_Src.zip](https://github.com/Microsoft/vscode-cpptools/files/2176606/0_Src.zip)

Thanks.

**Comment by bobbrow** [comment]
Thanks for the easy repro.  Macros were not being considered as matches when followed by a dot.  I have a fix for this.

**Comment by sean-mcmanus** [comment]
Go to definition on macros followed by . and -> has been fixed with 0.17.7.
