### ISSUE TITLE
Updating C/C++ dependencies...

### ISSUE THREAD

**Issue by hary66** [microsoft/vscode-cpptools#2246]
Type: General
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:
Linux raiselife 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

- VS Code Version:
Version: 1.25.0
Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
Date: 2018-07-05T13:10:37.273Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
- C/C++ Extension Version:

- Other extensions you installed (and if the issue persists after disabling them): 
PLatformio

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'ClangFormat (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Framework Assemblies'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Runtime (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Failed at stage: installPackages
Error: end of central directory record signature not found

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.

How to use the command indicated "Install from VSIX" ?
I've dowloaded cpptools-linux  but don't know what else to do ?

**Comment by bobbrow** [comment]
Press <kbd>CTL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> to open the command list, then type "VSIX" to filter out the other commands

**Comment by cliffburdick** [comment]
@bobbrow is there a way to do this using the remote-ssh plugin? I had opened a ticket here:

https://github.com/Microsoft/vscode-remote-release/issues/89

since I ran into the same issue. I tried installing the VSIX manually using the instructions above, but I don't think this works on remote-ssh since the plugin needs to be installed remotely. I tried it anyways, and got the same error.

**Comment by bobbrow** [comment]
It looks like @sean-mcmanus moved your issue into #3614.  I'm closing this older ticket.

**Comment by XXXXzzzz000** [comment]
i also have this problem.
you can try :
1. install vscode and c++ extension in the remote machine( my remote machine is virtual machine)
2. cp ~/.vscode/extensions/ms-vscode.cpptools-0.24.0 ~/.vscode-server/extensions -raf
now the c++ extension will work in your remote .
so i think this error just a download error.
