### ISSUE TITLE
Tag Parser doesn't recognize symbols defined in Macros

### ISSUE THREAD

**Issue by zeeshan595** [microsoft/vscode-cpptools#225]
I recently started using vs code for c++ programming with vulkan API and came across an issue. When I type "VkInstance instance;" It never auto completes VkInstance but it auto completes vkCreateInstance(..) fine. I have my include path properly defined in c_cpp_properties.json. I also built and ran the application to make sure its working fine. 

someone pointed out
"The Vulkan header wraps the typdefs for all handles (like VkInstance, VkFence, etc.) in a Macro and it looks like VSCode can't handle this."

Link to original post
http://stackoverflow.com/questions/39461080/cannot-auto-complete-c-in-vs-code

**Comment by LYP951018** [comment]
And also HWND!

**Comment by bobbrow** [comment]
We haven't fixed this for the Tag Parser yet, but if you try out the new IntelliSense engine, it works well with both Vulkan and HWND macros.

Add `"C_Cpp.intelliSenseMode": "Default"` to your settings.json to give it a try.

**Comment by bobbrow** [comment]
Sorry, I jumped the gun on this.  We have improved member list autocomplete in the new IntelliSense, but the original issue you described remains.  My apologies.

**Comment by Colengms** [comment]
I believe this has been addressed.  Testing with HWND, I see that it auto-completes.
