### ISSUE TITLE
Clang not installing (i think)

### ISSUE THREAD

**Issue by andreamatt** [microsoft/vscode-cpptools#2253]
Type: General
- OS and Version: Windows 10 x64
- VS Code Version: 1.25.0 x64
- C/C++ Extension Version: 0.17.6
- Other extensions installed: none

Code example:
```cpp
#include <iostream>
                                  using namespace std;
int main(){
return 0;}
```

I expected it to format, but nothing happens.
I checked file diff between my laptop (with this issue) and my pc (without it).
Basically, inside user/.vscode/extensions/ms-vscode.cpptools-0.17.6/LLVM/bin there is no clang-format.exe.
I tried uninstalling, deleting .vscode, roaming/Code and Program files/Microsoft VS Code, and then reinstalling.
I noticed that when I install the extension, the second step (installing clang-format) takes no time compared to my working pc.

I think it might have something to do with an old LLVM installation detected, but I can't find any trace of that.

I haven't touched c_cpp_properties.json and my settings.json only has
```json
{
    "git.ignoreMissingGitWarning": true,
    "C_Cpp.clang_format_path": null
}
```

**Comment by bobbrow** [comment]
Are you able to download clang-format.exe directly? https://go.microsoft.com/fwlink/?LinkID=872610
The link seems to be working for me.  I expected that the installation would fail if any of the downloads failed.

**Comment by andreamatt** [comment]
Yes, download works.
But still, even placing it manually, nothing happens when i format.
Is there a log about formatting somewhere?

**Comment by sean-mcmanus** [comment]
You can set the C_Cpp.loggingLevel to Debug to see formatting logging in the C/C++ pane of the Output window.

**Comment by andreamatt** [comment]
Done. No output at all.
I'm sure vscode it's trying to format though.
If i set clang path to "anything", it gives error, but still no output.

**Comment by bobbrow** [comment]
Did you select the `C/C++` filter in the Output window?  It's kind of hidden in the upper right corner of that panel.

**Comment by andreamatt** [comment]
sorry didn't notice that.
```
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/formatting
Formatting input: #include <iostream>

using namespace std;
int main(){


            return 0;
}
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
```

**Comment by bobbrow** [comment]
Is there a `"Formatting raw output:"` or `"Formatting failed:"` message?

**Comment by andreamatt** [comment]
Do you mean inside the Output?
No, this is what happens if i only open vscode on that file and format once.
```
initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
textDocument/didOpen
cpptools/queryCompilerDefaults
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/documentSymbol
textDocument/codeAction
cpptools/didChangeFolderSettings
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
Code browsing service initialized
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
  Folder: D:/PROGRAMMING/C-C++/ will be indexed
Discovering files...
textDocument/didOpen
  Processing folder (recursive): D:/PROGRAMMING/C-C++/
  Discovering files: 9 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
sending compilation args for D:\PROGRAMMING\C-C++\ALTRO\SUDOKU\TEST.CPP
  define: _DEBUG
  define: UNICODE
  define: _UNICODE
  stdver: --c++17
Checking for syntax errors: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
queue_update_intellisense for files in tu of: D:\PROGRAMMING\C-C++\ALTRO\SUDOKU\TEST.CPP
errorSquiggles count: 2
Tag Parser will be used for IntelliSense operations in: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/formatting
Formatting input: #include <iostream>

using namespace std;
int main(){


            return 0;
}
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
```

**Comment by bobbrow** [comment]
Yeah, I mean inside the output.  One of those messages should be appearing unless the formatting is completely hung.  Do you see any hung `clang-format.exe` processes in TaskManager?

**Comment by andreamatt** [comment]
No, none.
I tried manually removing clang-format.exe.
Now it gives
```
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
Formatting failed:
"c:\Users\andrea\.vscode\extensions\ms-vscode.cpptools-0.17.6/bin/../LLVM/bin/clang-format.exe" -style="{ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0 }" -fallback-style="LLVM" -sort-includes=0 -assume-filename="d:\Programming\C-C++\altro\sudoku\test.cpp"
  Unable to start child process!
```

**Comment by andreamatt** [comment]
Is there any way i can delete everything about vscode and be sure about starting again with a clean system?

**Comment by sean-mcmanus** [comment]
You can uninstall our extension and then restart VS Code. You should double check that the ms-vscode.cpptools-0.17.6 folder is gone afterwards. And then re-install the extension.

It sounds like clang-format.exe is crashing and we get stuck waiting for the results, but we're supposed to time out after 10 seconds and give an error.

**Comment by andreamatt** [comment]
Done as you said. This time clang-format.exe was installed.
Still doesn't format, and the output is exactly the same

**Comment by andreamatt** [comment]
Is it possible that there are issues related to installed cygwin/mingw/LLVM somewhere else on the disk?

**Comment by sean-mcmanus** [comment]
This is really strange, I don't see yet how this is possible.

Other Cygwin/mingw/LLVM shouldn't affect this if the clang_format_path is set to the default of null -- you could try setting the path to your own LLVM clang-format.exe binary that you know works. You might want to make sure the clang-format.exe you're using runs from the command line...even though we still should be showing better errors if it doesn't.

How does the extension behave immediately after formatting? Is everything stuck (i.e. does a 2nd format give output or does goto definition or hover work)?

**Comment by andreamatt** [comment]
I had tried installing LLVM by myself and setting its path, but it didn't fix the issue. The behaviour was the same.
If i try multiple formattings, they all give the same output
```
initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
textDocument/didOpen
cpptools/queryCompilerDefaults
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/didChangeFolderSettings
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
Code browsing service initialized
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
  Folder: D:/PROGRAMMING/C-C++/ will be indexed
textDocument/didOpen
textDocument/documentSymbol
Discovering files...
  Processing folder (recursive): D:/PROGRAMMING/C-C++/
  Discovering files: 9 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
textDocument/codeAction
sending compilation args for D:\PROGRAMMING\C-C++\ALTRO\SUDOKU\TEST.CPP
  define: _DEBUG
  define: UNICODE
  define: _UNICODE
  stdver: --c++17
Checking for syntax errors: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
queue_update_intellisense for files in tu of: D:\PROGRAMMING\C-C++\ALTRO\SUDOKU\TEST.CPP
errorSquiggles count: 2
Tag Parser will be used for IntelliSense operations in: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
textDocument/codeAction
textDocument/formatting
Formatting input: #include <iostream>

using namespace std;
int main(){


            return 0;
}
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/formatting
Formatting input: #include <iostream>

using namespace std;
int main(){


            return 0;
}
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
textDocument/formatting
Formatting input: #include <iostream>

using namespace std;
int main(){


            return 0;
}
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
textDocument/formatting
Formatting input: #include <iostream>

using namespace std;
int main(){


            return 0;
}
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
textDocument/formatting
Formatting input: #include <iostream>

using namespace std;
int main(){


            return 0;
}
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
textDocument/formatting
Formatting input: #include <iostream>

using namespace std;
int main(){


            return 0;
}
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/formatting
Formatting input: #include <iostream>

using namespace std;
int main(){


            return 0;
}
Formatting document: file:///d%3A/Programming/C-C%2B%2B/altro/sudoku/test.cpp

```

**Comment by andreamatt** [comment]
I don't think clang-format.exe goes on timeout. It doesn't appear at all in task manager when i format.
Not even for an instant

**Comment by andreamatt** [comment]
I think i found the issue. I am missing some vc redist requirements. If i start clang-format.exe from the bin folder, it gives a missing msvcp140.dll error. I'll try installing some redist right now

**Comment by andreamatt** [comment]
Done. Was missing vcredist 2015. Sorry for all the trouble.
Now it all works just fine.

**Comment by andreamatt** [comment]
@sean-mcmanus @bobbrow 
I don't see vcredist in any of vscode's requirements.
Maybe it's only a clang requirement, and if so, you should probably include it inside your extension

**Comment by sean-mcmanus** [comment]
Hmm...yeah, looks like it's a requirement of clang-format.exe. LLVM itself ships with this in the bin folder, so it looks like we should do the same...there could be other dependencies too. Thanks for informing us of this issue.
