### ISSUE TITLE
"int &" type incorrectly reported instead of "int" for deduced auto variable

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2256]
#include <utility>
#include <iostream>
using namespace std;

int main()
{
	pair<int, int> p { 1, 2 };
	auto[a, b] = p; // hover over a shows “int &a” instead of “int a”
	a = 10;
	cout << p.first << a << endl;
	return 0;
}

The bug repros with VS 2017 too. I'll link to the VS-side bug if/when it gets created.

The previous issue was https://github.com/Microsoft/vscode-cpptools/issues/2101 .

**Comment by sean-mcmanus** [comment]
Appears to be  VS bug https://developercommunity.visualstudio.com/content/problem/229224/intellisense-displays-wrong-type-for-structed-bind.html -- upvote that if anyone wants a fix.

**Comment by rpjohnst** [comment]
This is not a bug; the standard specifies this behavior in paragraph [dcl.struct.bind]/3.
