### ISSUE TITLE
Library files not installed in a system directory are not parsed properly

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2259]
Type: LanguageService

My project is using Conan to install dependencies. The only important detail to note is that conan installs library files in a directory within the user's home directory. VSCode detects that these headers exist but fails to parse them correctly, showing syntax errors for valid use of library functions. If the same library is installed globally then this extension displays no errors.

To demonstrate, here are the details of a sample project using the [range-v3](https://github.com/ericniebler/range-v3) library.

Contents of `c_cpp_properties.json`:
```
{
    "configurations": [
        {
            "name": "Linux",
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

Contents of `compile_commands.json`:
```
[
{
  "directory": "/home/ajp/demo/build",
  "command": "/usr/bin/c++   -I/home/ajp/.conan/data/range-v3/0.3.6/ericniebler/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include       -std=gnu++14 -o CMakeFiles/demo.dir/demo.cc.o -c /home/ajp/demo/demo.cc",
  "file": "/home/ajp/demo/demo.cc"
}
]
```

Contents of `demo.cc`:
```
#include <range/v3/view/split.hpp>

int main() {
    auto splitter = ranges::view::split(' ');
}
```
VSCode complains that `namespace "ranges::v3::view" has no member "split"`, which is incorrect. The program compiles without errors.
![syntax_error](https://user-images.githubusercontent.com/13278815/42633046-3a8c5efe-85ad-11e8-9870-55316a507eaa.png)

The absence of an `includePath` entry in `c_cpp_properties.json` was intended, under the assumption that `compile_commands.json` would provide the requisite include path information. Manually adding entries to `includePath` did not help however.

Furthermore, when writing a header file in an `#include` statement, VSCode fails to provide an autocomplete suggestion for range-v3 headers. Again, when the library is installed in a system directory this issue disappears.

I am using VSCode version 1.25.0 on Ubuntu 18.04.

**Comment by bobbrow** [comment]
It seems to be a problem with our `clang-x64` intelliSenseMode.  This works on Windows with `msvc-x64` mode.

*Notes for us: To repro, you just need to clone `range-v3` and paste in the code above using `clang-x64` intelliSenseMode*

**Comment by sean-mcmanus** [comment]
@bobbrow I'm not able to repro this with 0.17.7 on Linux with clang-x64 mode. Maybe the range-v3 library changed?

**Comment by bobbrow** [comment]
0.17.7 pulled in a bunch of fixes from VS.  Perhaps one of those took care of this issue.

**Comment by sean-mcmanus** [comment]
Oh, I think you're right -- I must have checked the dates wrong and thought 0.17.7 was being used. So we'll close this for now, but let us know if there's still a way to get it to repro.
