### ISSUE TITLE
CMake include directories

### ISSUE THREAD

**Issue by damienpontifex** [microsoft/vscode-cpptools#226]
Is it possible to integrate/hook into CMake and CMakeLists.txt files to enable the `includePath` property of the json configuration to be populated with cmake `include_directories` function paths?

Currently I setup third party includes in my CMake configuration and it would be great if there was a way to get this automatically similar to the CMake generator for IDEs do. I have no idea how this would work, but something along the lines of `cmake -G VSCode src`

**Comment by agauniyal** [comment]
Don't tie down to a build system please! Use `compile_commands.json` file(generated by almost all build systems) or either a plugin should do this.

**Comment by reporter123** [comment]
I would have considered writing a separate plug-in to do this if that was needed. However I would be inclined for simplicity to use the compile_commands.json file. Even if coding support was still needed. json files are well support by the existing code base. Which makes them easier to parse then "CMakeLists.txt" as much of the code needed is already written. Is compile_commands.json supported by this plugin? I don't have a personal need for this at the moment.

**Comment by damienpontifex** [comment]
Thanks for the help. I wasn't aware of the `compile_commands.json` tooling file process, so I will look into it.

**Comment by tanis2000** [comment]
@damienpontifex  I see that this issue has been closed, does that mean that support for `compile_commands.json` has been added? How do you use it?

**Comment by agauniyal** [comment]
@tanis2000 there are alternate plugins for autocompletion, the best being - https://github.com/richard1122/vscode-youcompleteme. It supports reading from `compile_commands.json` but there are two irritating bugs atm, one from vscode and another is partially reproducible. There is no support(yet?) for `compile_commands.json` parsing with vscode-cpptools plugin.

**Comment by hanzheteng** [comment]
Hello I encountered the same issue today - IntelliSense couldn't find 3rdparty include directory and I had to manually add them to the include path. It would be great if this can be done automatically (by looking into `include_directories` in CMakeLists.txt). 

What is the current status of this feature request? Any recommendation to the plugin if available? I don't quite understand how to proceed with the `compile_commands.json` approach.

**Comment by sean-mcmanus** [comment]
@hanzheteng If you're using CMake, it's recommended to install the CMake Tools extensions and setting "configurationProvider": "ms-vscode.cmake-tools" , and running CMake: Configure (and maybe other commands).

However, include paths in compile_commands.json is supposed to work too, so if you could file a new issue and provide more info we could investigate more.

**Comment by hanzheteng** [comment]
@sean-mcmanus  Thank you. CMake Tools works well after I config and build the project.  

I don't really understand how compile_commands.json works, so probably just skip it for now. Thanks.
