### ISSUE TITLE
Goto definition doesn't lead to right class

### ISSUE THREAD

**Issue by fr43nk** [microsoft/vscode-cpptools#2265]
In my program I have the following class structure:

```
MyBaseClass
{
  virtual void execute() = 0;
};

MyWorkClass1 : public MyBaseClass
{
  void execute();
};
MyWorkClass2 : public MyBaseClass
{
  void execute();
};
```
in a main file I instantiate the two working classes.
```
main
{
  MyWorkClass1 mw1();
  MyWorkClass2 mw2();

  mw1.execute();
  mw2.execute();
}
```
Now when I Ctrl-click on the ```mw1.execute``` method I get a list with all the classes where ```execute``` is implemented. But I think it should lead directly to the class.

- OS and Version: Windows 7
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.6

**Comment by bobbrow** [comment]
Thanks for the feedback.  The current implementation is not aware of the context.  We are tracking this with #255.  Please go and upvote that issue.

**Comment by sean-mcmanus** [comment]
With 0.19.0, this is fixed if the execute method is actually defined in the class itself (i.e. with a {} body) and it works if Go to Declaration is used. However, if the definition is in another cpp file, that work is being tracked by https://github.com/Microsoft/vscode-cpptools/issues/2536 .
