### ISSUE TITLE
Support for passing custom parameters to clang-format 

### ISSUE THREAD

**Issue by jdwieber** [microsoft/vscode-cpptools#2269]
Please add a C_Cpp.clang_format_options to enable passing custom parameters to the clang-format executable. For instance:

```
{
    "C_Cpp.clang_format_options" : ["--assume-filename="${workspaceFolder}/../../.clang-format"],
}
```

or something taken from the env

```
{
    "C_Cpp.clang_format_options" : ["--assume-filename="${env:CL_FMT}"],
}
```

**Comment by sean-mcmanus** [comment]
Your usage of --assume-filename is incorrect -- it doesn't take a .clang-format file as input (clang-format docs are incorrect). The .clang-format file is obtained by being the current directory or any parent directory. Do you have another reason to pass args?

**Comment by jdwieber** [comment]
Ah, yes, you're correct. We use a script to beautify all our C++ repos that pipes output through clang-format as part of the process. --assume-filename won't work like this. Sigh, yes, that is my primary reason for opening this request.

**Comment by Colengms** [comment]
Hi @jdwieber .  Am I reading your last reply correctly to mean that the primary reason for opening this request "won't work like this"?  I'm going to go ahead and close the issue.  If I misread your comment and this is still needed, please add a comment and we can re-open the issue.
