### ISSUE TITLE
Which licence pertains to the source files

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#2274]
In all the source files for the extension, the license header says to look in the project root for license information. Is the project root considered the root of the repo, or the root of the extension folder. The root of the repo is MIT, whereas the root of the extension is a custom Microsoft license with much more restrictions. Which ones applies to the source files for the extension?

Mainly I was interested in extending the logger class for one of my own extensions, but want to make sure I'm following the license properly.

**Comment by sean-mcmanus** [comment]
The MIT license at the root applies to all the stuff under the root (i.e. the GitHub open source typescript code). The license under the extension folder isn't intended to be applied to the contents under the Extension folder on GitHub; instead, it's what gets packaged in the .vsix that gets shipped to end users (i.e. the non-open source binaries and compiled javascript) -- this is the same end user license that existed before we open sourced the typescript part.

**Comment by ThadHouse** [comment]
Ok, one more question. The license in the vsix is very confusing. It doesn't seem to say anything one way or another, but can I include it in a zip I'm distributing for a competition, as long as the license is still there and it is only getting used with VS Code? I don't see the usual redistribution clause in there, so I'm not exactly sure.

**Comment by sean-mcmanus** [comment]
What exactly are you including in a zip and redistributing? I believe the intent of the license was to make sure non-open source binaries weren't being re-used outside of VS Code. For complicated legal questions I can I get you in contact with our lawyer -- I just need to know what email to use (I couldn't find your email on GitHub).

**Comment by ThadHouse** [comment]
I just wanted to include the vsix downloaded from the releases page, directly for use in VS Code. I work with the libraries for a high school robotics competition of about 3000 teams, where we need to be able to support teams at areas without internet access. Our plan is to have an offline installer where users can just download a single zip from us and know that they have everything needed to run their robots. They would be fully used with VS Code, we just wanted to make the experience easier for our teams. We have infrastructure set up to download the full VS Code (since that has the same redistribution restriction), but it would be nice to have that be the only thing, and not have to grab an extension as well. And if lawyers could help us make that redistributable just by us that would make us even happier.

If you want to discuss more offline, my email is 

thadhouse1   at   gmail

**Comment by sean-mcmanus** [comment]
Yeah, you can distribute the offline vsix's at https://github.com/Microsoft/vscode-cpptools/releases -- the intent is for those to be used in offline scenarios, i.e. distribution on a CD or whatever.

**Comment by ThadHouse** [comment]
Ah ok. Thanks for clarifying that helps us a lot.
