### ISSUE TITLE
IntelliSense for 32 bit pointers

### ISSUE THREAD

**Issue by d07RiV** [microsoft/vscode-cpptools#2275]
Type: LanguageService

Is there any way to use intellisense with 32-bit pointers? According to docs, `intelliSenseMode` can be `msvc-x64` or `clang-x64`, and both of these show `sizeof(void*)` as 8, which is not appropriate for my project.

**Comment by bobbrow** [comment]
Not currently.  It is on our backlog to support additional IntelliSense modes.

**Comment by sean-mcmanus** [comment]
Should be fixed with the "-x86" modes in 0.25.-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders
