### ISSUE TITLE
intellisense not working under Linux with  ros

### ISSUE THREAD

**Issue by Sagexs** [microsoft/vscode-cpptools#2277]
I am using Ubuntu 16.04, visual code 1.25 with ajshort.ros and ms-vscode.cpptools extension

if I create an object of a class, the list of attributes and methods are completely confused. I get suggestions for methods of completely different classes see here 
![lgg4n](https://user-images.githubusercontent.com/8236340/42747174-8ea5ec40-88db-11e8-8ea9-7f9cdabfd053.png)

**Comment by bobbrow** [comment]
Are there any problems listed in your problems window?  By default, our extension will use a less accurate form of IntelliSense if we are unable to resolve `#include` lines in your source files.

**Comment by Sagexs** [comment]
you were completely right. In a minimal example (with only one ROS packet) the error does not occur. 

Some headers of third party libraries could not be found in my project.  
After adding all paths it works fine. 

Thank you very much for your help and sorry that I didn't realize this myself!! This makes my daily work much easier.
