### ISSUE TITLE
includePath doesn't work

### ISSUE THREAD

**Issue by Carter-1024** [microsoft/vscode-cpptools#2278]
Type: LanguageService
**Describe the bug**
- OS and Version:
Ubuntu 14.04
- VS Code Version:
1.25.1
- C/C++ Extension Version:
Version 0.17.6: July 2, 2018
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

When I include file like <linux/***>, it can't be loaded in even I have added it to c_cpp_properties.json of workspace. 

**To Reproduce**

Add linux kernel folder to workspace, can not open file show. include format just like <linux/**> or <media/**>

**Comment by bobbrow** [comment]
Please share your `c_cpp_properties.json` file.

**Comment by sean-mcmanus** [comment]
Adding `<parentPath>/linux` to the c_cpp_properties.json isn't correct (`<linux>` won't be found) -- you should add `<parentPath>` or `<parentPath>/**` (if you need subpaths to also be added).

**Comment by Carter-1024** [comment]
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}",
                "/home/xx/xx/xx/kernel/msm-4.9/**",
                .....other git folder
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

in cpp source file, I add just like #include <linux/kthread.h>.
kthread.h located at /home/xx/xx/xx/kernel/msm-4.9/include/linux/, but file can't be open show in vs code.

I have tried two path
                "/home/xx/xx/xx/kernel/msm-4.9/**",
or
                "/home/xx/xx/xx/kernel/msm-4.9/include/**",

can't work

**Comment by sean-mcmanus** [comment]
Can you try doing a "Reset IntelliSense Database" command (in case the database has some invalid data used for recursive incluedes)?

When you set the C_Cpp.loggingLevel to debug and view the C/C++ section in the Output window, and then Reload Window, and open a .cpp file, you can view the "sending compilation args for" which shows which include paths we're actually using -- are we missing the msm-4.9/include/linux include paths? (this usually matters for recursive includes or system includes, which we generate)

Using the msm-4.9/include should work -- is it missing a dependency of the linux/kthread.h? (it should say in the error message what file can't be found).

Is this project open source somewhere?

**Comment by Carter-1024** [comment]
Sorry, that may be my mistake.
It works after I moved c_cpp_properties.json to the git folder not the workspace folder.
thank you for your help.
