### ISSUE TITLE
Question: how to build dynamic library on MacOS

### ISSUE THREAD

**Issue by ShuminY** [microsoft/vscode-cpptools#2279]
How could I use VS Code to build dynamic library file (on MacOS)? I have the cpp files and would like to build them into a dynamic library file (e.g. libxxx.so, or libxxx.dylib on MacOS). Thanks!

**Comment by sean-mcmanus** [comment]
Are you able to build a dynamic library from the command line? You need to first figure out how to build from the command line and then you can use that command line in VS Code via a build task: https://code.visualstudio.com/Docs/editor/tasks .

**Comment by ShuminY** [comment]
thank you.
