### ISSUE TITLE
clang-format do not use c_cpp_properties.jason settings for formatting

### ISSUE THREAD

**Issue by Aukstkalnis** [microsoft/vscode-cpptools#228]
OS: windows 7 x86
clang-format version: 3.9 (3.8 did not worked for me)

I configure clang format like this in c_cpp_properties.json settings:
    "clang_format": {
        "style": "file",
        "fallback-style": "LLVM",
        "sort-includes": false,
        "TabWidth": 4,
        "UseTab": "ForIndentation",
        "SpacesBeforeTrailingComments": 1,
        "AlignAfterOpenBracket": "Align",
        "AlignConsecutiveAssignments": true,
        "AlignConsecutiveDeclarations": true,
        "AlignEscapedNewlinesLeft": true,
        "AlignOperands": false,
        "AlignTrailingComments": true
    }
I press alt+shift+f and I get standard formatation. There is no .clang-format file.

**Comment by sean-mcmanus** [comment]
c_cpp_properties.json doesn't accept any clang_format settings. See the "C_Cpp.clang_format_" user/workspace settings.
