### ISSUE TITLE
Failed to 'continue' nginx debug through gdb attach in vscode while terminal gdb is fine

### ISSUE THREAD

**Issue by hcnhcn012** [microsoft/vscode-cpptools#2283]
Type: Debugger
gdb       (attach)

**Describe the bug**
- OS and Version: Arch Linux with `kernel 4.17.5-1-ARCH`
- VS Code Version: `1.25.1`
- C/C++ Extension Version: `0.17.6`
- Other extensions you installed (and if the issue persists after disabling them): `C++ intellisence`

**Problem description**
When I debug a `nginx` module, it runs find in terminal gdb but it seems not going well on vs code when I  attach the `nginx worker process`. No errors occur when attaching the process, but I can't continue when I get a error `ERROR: Command aborted. See the output window for additional details.`. Here are the corresponding part of my configuration launch.json and some log screenshots. Thanks for helping me to handle it.

**The debugger says `PAUSED ON EXCEPTION` when in function `epool_wait()`, but actually this function is blocked waiting for events, which is normal.**

**launch.json**
![q3](https://user-images.githubusercontent.com/19546977/42815475-0cd3bb3c-89fa-11e8-98a6-5edfc716a7f2.png)

**log main**
![q11](https://user-images.githubusercontent.com/19546977/42815480-0ed3132e-89fa-11e8-9ea2-c80ccafe0020.png)

**log window**
![q22](https://user-images.githubusercontent.com/19546977/42815559-42fb0b8e-89fa-11e8-8213-845dd22560f2.png)

**log extension hosts**
![q33](https://user-images.githubusercontent.com/19546977/42815537-35d8e76e-89fa-11e8-889e-757df5bdd9aa.png)

**Debug Console**
![q44](https://user-images.githubusercontent.com/19546977/42815540-372deb6e-89fa-11e8-8fa9-525a28d95e45.png)

**Comment by pieandcakes** [comment]
@hcnhcn012 Please enable `"logging": { "engineLogging": true" }"` and rerun with trying to continue and send the log.

**Comment by hcnhcn012** [comment]
@pieandcakes [engineLog.txt](https://github.com/Microsoft/vscode-cpptools/files/2204208/engineLog.txt)
Here it is :)

**Comment by pieandcakes** [comment]
Your log shows me:
```
1: (4722) <-1009-break-insert -f ngx_http_multipost_module.c:378
1: (4726) ->1009^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0000000000000166",func="ngx_http_multipost_handler",file="/home/chain/Project/postGraduateProject/180710_nginx_sercure_module/Source/nginx-1.14.0/modules/multipost//ngx_http_multipost_module.c",fullname="/home/chain/Project/postGraduateProject/180710_nginx_sercure_module/Source/nginx-1.14.0/modules/multipost/ngx_http_multipost_module.c",line="378",thread-groups=["i1"],times="0",original-location="ngx_http_multipost_module.c:378"}
``` 
which tells me that gdb thinks your breakpoint is bound to an address of `0x0000000000000166` but then when we try and start running after attach, we get:

```
1: (4832) <--exec-continue
1: (4833) ->^running
1: (4833) ->*running,thread-id="all"
1: (4833) ->&"Warning:\n"
1: (4833) ->&"Cannot insert breakpoint 1.\n"
1: (4833) ->&"Cannot access memory at address 0x166\n"
1: (4833) ->&"\n"
1: (4833) ->^error,msg="Command aborted."
```

This is the message we are showing you because for some reason gdb is telling us the breakpoint is invalid, even though it was the one that set it up. I think this must result in an exception from within gdb, which is why it shows "paused on exception".  This seems to be an issue in gdb. Can you downgrade/upgrade to a different version and see if it is still having the problem?

**Comment by hcnhcn012** [comment]
@pieandcakes Thanks ! :)

**Comment by pieandcakes** [comment]
@hcnhcn012 Can you share the fix you used so others who run into the same problem know what you did?


Thanks!

**Comment by gabeluci** [comment]
I'm facing this too (while debugging VLC 3.0.9, but oddly it doesn't happen with VLC 4.0.0). A workaround is described [here](https://stackoverflow.com/a/44369359/1202807), which is to use the GDB command `delete`, to delete the offending breakpoint.

So in VS Code, after you start debugging and it halts, you do this by typing:

    -exec delete 1

in the debug console. Then continue execution.

The downside of course is that you have to do this every time you start debugging.
