### ISSUE TITLE
[gdb] [windows] unknown target exception 0x4000001f at 0x40163e

### ISSUE THREAD

**Issue by phypy** [microsoft/vscode-cpptools#2285]
Type: Debugger
**Input information below**
Hi, i start an easy test program(C lauguage), then i start debug by F5,then i get an exception at debug console :
gdb: unknown target exception 0x4000001f at 0x40163e
Thread 1 received signal ?, Unknown signal.
0x0009df88 in ?? ().

other info:
GNU:x86_64-8.1.0-release-posix-seh-rt_v6-rev0,
debugger:gdb.

VS Code version: Code 1.25.1 (1dfc5e5, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

System Info
Item	Value
CPUs	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
rasterization: disabled_software
video_decode: enabled
video_encode: enabled
vpx_decode: enabled
webgl: enabled
webgl2: enabled
Memory (System)	7.90GB (2.00GB free)
Process Argv	D:\Programs\Microsoft VS Code\Code.exe
Screen Reader	no
VM	67%
Extensions (2)
Extension	Author (truncated)	Version
vscode-language-pack-zh-hans	MS-	1.25.3
cpptools

**Comment by pieandcakes** [comment]
Which flavor of gdb 8.1 are you using are you using? There is an issue with 64bit gdb 8.1 of MinGW that crashes and unfortunately the only fix I've heard is to either use 32bit gdb 8.1 or to roll back to a previous version.

**Comment by phypy** [comment]
ok, I used 64bit MinGW. what a surprise ...

**Comment by pieandcakes** [comment]
To be fair, this worked before, but the update to gdb 8.1 broke a lot of things. If you feel like it, please report it so that they can fix it for a future release

**Comment by phypy** [comment]
ok,thank you, hope you have a good launch.

**Comment by Ruslvn001** [comment]
HI, Did you solve that problem?)
