### ISSUE TITLE
Weirdly Displaying Enum Definitions

### ISSUE THREAD

**Issue by abrachet** [microsoft/vscode-cpptools#2286]
Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: MacOSx 
- VS Code Version: 1.25
- C/C++ Extension Version: 0.17.6

Hovering over enum's will sometimes show the incorrect enumerator. 

**To Reproduce**
enum Test {
    TEST1 = 1,
    TEST2,
    TEST3,
    TEST4
};

If you take this enum for example, if you hover over TEST1, it will correctly identify it as Test::TEST1 = 1. Weirdly, however, if you hover specifically over the 1, it will show the definition of Test::TEST4. Nowhere else on TEST1 does this happen, only on its given value.

**Expected behavior**
Presumably, it would be expected to continue to say Test::TEST1 = 1.

**Comment by sean-mcmanus** [comment]
This issue repros with VS 2017 too (unlikely to get fixed by them, due to the large number of more severe bugs on their plate).

**Comment by sean-mcmanus** [comment]
This was fixed in July with version 0.17.7.
