### ISSUE TITLE
Add a setting to turn off config provider notifications

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#2292]
Type: LanguageService
**----- Input information below -----**

Can we have a setting to disable the "<config provider> cannot provide configurations for <file>. <default config> will be used instead" messages? They are creating a lot of noise, and popping up in scenarios where they shouldn't be (e.g. when ProvideConfigurations times out, but the configurations are returned eventually).

**Comment by sean-mcmanus** [comment]
`C_Cpp.configurationWarnings` was added in 0.17.7.
