### ISSUE TITLE
Support #IFDEF

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#23]
Similar to how `#IF` is currently supported, it would be great if also `#IFDEF` worked.

Here's an animation to clarify.

![ifdef_animation](https://cloud.githubusercontent.com/assets/1297882/14687549/7f0017a0-073e-11e6-83fa-5e76a42084f0.gif)

**Comment by sridmad** [comment]
At this point syntax colorization as well as greying of preprocessor sections is handled by TextMate  bundle (https://github.com/atom/language-c). The bundle is dealing with #if 0 explicitly for colorization.

**Comment by bobbrow** [comment]
I'm going to merge this issue with #230 for improving colorization in the editor

**Comment by sean-mcmanus** [comment]
@csholmq Fixed with 0.15.0, but the intelliSenseEngine needs to be "Default".

**Comment by csholmq** [comment]
Seems to work great!
