### ISSUE TITLE
oddness with colorization of inactive preprocessor blocks

### ISSUE THREAD

**Issue by sstaub** [microsoft/vscode-cpptools#2304]
macOS Mojave 10.14 Beta (18A336e)
VS Code 1.25.1
C/C++ 0.17.7
Arduino 0.2.18
used board Fubarino Mini with PIC32MX micro controller

The wrong preprocessor block is marked as inactive.

#if defined(__PIC32MX__)
  #define TYP 2 // this part is marked as inactive, but it is wrong 
#else
  #define TYP 0 // this part is marked active, but it is also wrong
#endif

see screenshot
<img width="1244" alt="screenshot" src="https://user-images.githubusercontent.com/6450325/43033467-3b4ac252-8ccb-11e8-9e1f-e9fedfd44360.png">

**Comment by sstaub** [comment]
Maybe this only a problem with the Arduino framework, cpp-tools doesn't find the micro controller specific macros.

**Comment by sean-mcmanus** [comment]
Can you add the `__PIC32MX__` to the defines section of c_cpp_properties.json?

**Comment by sstaub** [comment]
It works, I can make an issue to platformIO to add a processor macro in c_cpp_properties.json when there is no other solution.

**Comment by bobbrow** [comment]
Thanks for confirming.  Our extension doesn't have any specific knowledge of Arduino, so it definitely would be best if platformIO could auto-configure IntelliSense for your specific board.
