### ISSUE TITLE
Can't edit includePath

### ISSUE THREAD

**Issue by magicalKhachapuri** [microsoft/vscode-cpptools#2309]
Type: General
I'm new to VS CODE, I'm trying to use it for cpp. I know i have to edit includePath but i can't because when i write a little code i don't get a green squiggly under #include statement, also a light bulb doesn't show up. What can I do ?

- OS and Version: Windows 10 Pro, 10.0.17134 Build 17134
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them): CSS Peek, HTML CSS Support, PHP Debug. Issue still persists after disabling them.

**Comment by bobbrow** [comment]
Did you solve your problem?  It might help to post your solution in case anyone else searches through the issues.
