### ISSUE TITLE
wrong tm scope for '>>' in vector<vector<>>

### ISSUE THREAD

**Issue by need47** [microsoft/vscode-cpptools#2310]
This is valid in c++ 11. But it has the wrong scope of `keyword.operator.bitwise.shift.c`, which causes issue for color theme such as One Dark Pro (note the mismatched color).

![2](https://user-images.githubusercontent.com/1194165/43080295-6f1ce838-8e5d-11e8-9094-6c5812d83475.JPG)

**Comment by bobbrow** [comment]
This is a bug for the TM grammar, though I'm not sure they'll be able to fix it due to the limitations of regular expressions.  Can you file an issue there instead? https://github.com/atom/language-c/issues/new.

**Comment by need47** [comment]
https://github.com/atom/language-c/issues/282
