### ISSUE TITLE
Very slow/locking up  parsing folders

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#2311]
Under Ubuntu 16.04, Vscode 1.25.1, cpptools 1.17.7.

Output channel:
```
IntelliSense Engine = Tag Parser.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/gen
File exclude: **/Entries
File exclude: **/Makefile*
File exclude: **/moc_*
File exclude: **/bin
File exclude: **/.obj
File exclude: **/.moc
File exclude: **/libs
File exclude: **/GPATH
File exclude: **/GRTAGS
File exclude: **/GTAGS
File exclude: **/ivencs-sdk*
File exclude: **/tmm/asl0632
File exclude: /home/nscott/workspace/tmb/daemons/tmm/include/dataModel/*
File exclude: /usr/include/x86_64-linux-gnu/bits/mathinline.h
File exclude: **/qrc_*
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.mak
Search exclude: **/*.min.js
Search exclude: **/catch.hpp
Search exclude: **/.vscode
Search exclude: **/.vscode
Code browsing service initialized
  Folder: /usr/local/include/ will be indexed
  Folder: /usr/lib/llvm-3.8/lib/clang/3.8.0/include/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /home/nscott/workspace/asldev/aslcore/ will be indexed
  Folder: /home/nscott/workspace/qt4/qt4/include/ will be indexed
Discovering files...
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /usr/lib/llvm-3.8/lib/clang/3.8.0/include/
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /home/nscott/workspace/asldev/aslcore/
  Processing folder (recursive): /home/nscott/workspace/qt4/qt4/include/
  Discovering files: 47053 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Parsing remaining files...
Done parsing open files.
IntelliSense Engine = Tag Parser.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
IntelliSense Engine = Tag Parser.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
IntelliSense Engine = Tag Parser.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
```

This is starting to drive me insane. Before 1.17.5 the extension worked perfectly. Now whenever I open a workspace that hasn't been parsed before, it takes something like 10 minutes with frequent lock ups.

Each workspace shares the same include files - does it reindex every workspace?

I've tried setting the workspaceParsingPriority to "low"  but that didn't help.

Any ideas what to try?

**Comment by bobbrow** [comment]
Are you using a VM?

We have always reindexed every workspace as we don't share databases between folders, so I don't think that is the problem.  My guess is still the recursive includes since that will be on by default when you open a new folder that doesn't have `c_cpp_properties.json`.  You can test this theory by changing `"C_Cpp.default.includePath": [ "${workspaceFolder}" ]` and then opening a new folder that doesn't have a `c_cpp_properties.json` in it.

If that's not it then we might have to try profiling.

**Comment by sean-mcmanus** [comment]
@bobbrow They're using the Tag Parser though -- the intention is for the recursive includes "changes" should only kick in when the "Default" engine is used.

@Gruntfuggly Can you check your OS's resource manager and see what resource is being used heavily by our processes? How many cores is your machine? The low workspaceParsingPriority is supposed to keep the background parsing thread near 25% CPU.

Having lots of files.exclude is known to use more CPU and slow things down (particularly with the exclusion policy set to checkFilesAndFolders), but I wouldn't expect anything major like you're describing.

**Comment by Gruntfuggly** [comment]
I am using a VM, confrigured to use 4 cores. I've set the parsing priority to medium at the moment and the CPU usage doesn't seem to go above 50% (according to top).

**Comment by sean-mcmanus** [comment]
When it's at 50% do you still experience the lock ups? Also, it can go above 50% when you open a file, because the processing related to the file isn't considered background processing.

**Comment by Gruntfuggly** [comment]
The lock ups don't seem to be related to CPU usage. The file parsing count (hovering over the database symbol on the activity bar) doesn't seem to increase very quickly, almost like it is getting stuck on particular files.

**Comment by Colengms** [comment]
This issue hasn't had any activity for quite a while.  There have been many changes since this was reported.  If you are still experiencing the issue, please reopen this or a new issue.
