### ISSUE TITLE
Add 32-bit IntelliSense modes

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#2312]
Additional modes that need to be added:
`gcc-x86`
`msvc-x86`
`clang-x86`

**Comment by sean-mcmanus** [comment]
I moved the gcc-x64 issue to https://github.com/Microsoft/vscode-cpptools/issues/2317 .

**Comment by sean-mcmanus** [comment]
Seems like the same issue as https://github.com/Microsoft/vscode-cpptools/issues/2275 .

**Comment by cdunford** [comment]
👍
