### ISSUE TITLE
Make 'Go to Definition' work for head file that includes multi-level paths

### ISSUE THREAD

**Issue by need47** [microsoft/vscode-cpptools#2313]
Note that my includePaths were set up correctly.

#include <a.hpp>         // working here if I press F12, i.e. opened a.hpp in a separate tab
#include <a/b.hpp>     // not working, no matter where I put the cursor

My general question is that how do I go to a header file?

**Comment by sean-mcmanus** [comment]
It should work in general. Can you provide more repro details to help us figure out what could be causing the failure, such as your c_cpp_properties.json settings? If you set your C_Cpp.loggingLevel to "Debug" you normally should see "tag parsing file: ...\a\b.hpp".

![image](https://user-images.githubusercontent.com/19859882/43102271-7ff3e234-8e7f-11e8-9f79-01ebd1e7dc8f.png)

**Comment by need47** [comment]
You're correct. I have a very large repository, and some were failed to resolve. That could be cause. I just started with a simple test case, it's working properly.
