### ISSUE TITLE
C++ intellisense report an error which is not an error

### ISSUE THREAD

**Issue by xomlizsm** [microsoft/vscode-cpptools#2314]
Type: LanguageService
**----- Input information below -----**

The c++17 standard described definition like this
auto k{123};
that k is an int type after c++17
and in c++11/14 that the k is initializer_list type.
And the intellisense shows me that k is initializer_list type and when I use k be an int type, it will tips me an error which makes everywhere red.. but I can still pass the compile .

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: osx 10.14
- VS Code Version:latest stable for now
- C/C++ Extension Version:latest 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Provide a code sample including configuration files such as c_cpp_properties.json*

**Expected behavior**

**Screenshots**

**Additional context**
*Call Stacks: For bugs like crashes, deadlocks, infinite loops, etc. that we are not able to repro and for which the call stack may be useful, please attach a debugger and/or create a dmp and provide the call stacks. Starting with 0.17.3, Windows binaries have symbols available in VS Code by setting your "symbolSearchPath" to "http://msdl.microsoft.com/download/symbols".*
Add any other context about the problem here including log messages in your Output window ("C_Cpp.loggingLevel": "Debug" in settings.json).

**Comment by sean-mcmanus** [comment]
This appears to be the same issue as https://github.com/Microsoft/vscode-cpptools/issues/2299 -- there's a temporary work around in the bug -- we're working on a fix.

**Comment by sean-mcmanus** [comment]
I'm seeing this fixed with our Insiders build https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.8-insiders .

**Comment by Colengms** [comment]
This appears to be addressed.
