### ISSUE TITLE
LLDB: Breakpoint modification / creation done via -exec isn't reflected in the UI

### ISSUE THREAD

**Issue by dkorbar** [microsoft/vscode-cpptools#2318]
Type: Debugger

**Describe the bug**
- OS and Version: macOS 10.13.3
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them): XML Formatter, TSLint, SQL Server (yes it still reproes after disabling other extensions
- When I add or modify breakpoints directly through lldb via "-exec" it isn't reflected in the UI

**To Reproduce**
- Debug a cpp project and break into the debugger
- use lldb to set a breakpoint, e.g.: `-exec br set -b MyMethod`
- use `-exec br list` to confirm that the breakpoint has been set
- look at BREAKPOINTS section in VSCode

Expected: See breakpoint created via `-exec` here
Actual: Breakpoint set via `-exec` isn't visible

**Comment by pieandcakes** [comment]
@dkorbar This is expected. VS Code only allows you to set breakpoints through the UI.

**Comment by dkorbar** [comment]
@pieandcakes but it does allow me to do so. "-exec br set" is setting up a breakpoint that I hit. It's just not showing up in the UI.
Not allowing to set breakpoints through LLDB isn't great considering that the VS Code UI is already missing some crucial breakpoint options like actions on breakpoints or watchpoints.

**Comment by pieandcakes** [comment]
@dkorbar We piped commands through the REPL window (which is what you are using) to enable the developer to access commands that don't exist in the UI. This isn't a normal feature of VS Code, but we had to allow it as there is information that C++ developers need that VS Code doesn't have UI for. The intention was not to allow setting/changing of state, which is what you are doing. We don't block or filter any commands after the `-exec` is specified. 

Unfortunately, the problem that is blocking the UI from showing it isn't with the extension but with the VS Code debug protocol having no way for us to notify that we have new breakpoints. It is a request/response protocol where VS Code issues requests to us and we process and return responses we receive from `lldb/gdb`. This isn't something we can change/fix. You should still note that the breakpoints get hit, its just not showing in the UI. 

You can find the protocol [here](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts) as well as their implementation using a `node` debug adapter.

**Comment by dkorbar** [comment]
@pieandcakes should this be an issue on VS Code itself then?

**Comment by pieandcakes** [comment]
The protocol repo link will allow you to make suggestions on how to change/improve the protocol. 

To be clear, the `-exec` backdoor to run commands directly against the debugger is NOT part of the protocol, but a workaround we put in place so the chances of them making a change there will be low.
