### ISSUE TITLE
Includes of xpm files not recognized

### ISSUE THREAD

**Issue by jhasse** [microsoft/vscode-cpptools#232]
``` cpp
#include "image.xpm"
```

results in `Include file not found in include directory` even though the file is there.

**Comment by sean-mcmanus** [comment]
I can't repro this bug. Can you give more repro details?

**Comment by sridmad** [comment]
@jgoshi ,  We should look into not filtering files by known C++ file extension when limitSymbolsToIncludedHeaders == true

**Comment by sean-mcmanus** [comment]
Yes, you are correct that we should look for symbols in non-standard headers names, but it doesn't appear to be related to this bug repro.

**Comment by jgoshi** [comment]
We currently do look for symbols in any file that is explicitly included like this (regardless of extension).

**Comment by jgoshi** [comment]
I am also unable to repro. Can you provide a small repro sample by attaching everything in the root folder?

**Comment by jhasse** [comment]
[xpm-bug.zip](https://github.com/Microsoft/vscode-cpptools/files/495542/xpm-bug.zip)

Okay the bug is actually hard to reproduce. I've created these two files and the bug appeared. But when I restarted VSCode it didn't anymore. So I don't really know what causes it :(

**Comment by jgoshi** [comment]
I tried with the files you attached and am unable to repro (I didn't need to restart). I'm going to close this for now. If this keeps happening for you or you find a more consistent repro please reopen the issue.

**Comment by sean-mcmanus** [comment]
I have observed a bug in which our header finding suddenly fails to work when the root folder has "too much" stuff in it, so it's possible he's hitting that. If he has a repro with an extensions like .h then it's probably that issue and not related to the extension.
