### ISSUE TITLE
Windows: system includes and defines not discovered when using MSVC 14

### ISSUE THREAD

**Issue by septag** [microsoft/vscode-cpptools#2321]
vscode: 1.25.1
cpp vscode: 0.17.7
using visual studio 14 2015 - update 3

code builds fine, event "go to definition" works for standard headers, but it's always showing header's not found for standard headers like:

```
#include <stdarg.h>  // "cannot open source file ..."
#include <stdint.h>   // "cannot open source file ..."
#include <malloc.h>  // "cannot open source file ..."
...
```

c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Win32",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}/include",
                "${workspaceFolder}/include/compat/msvc",
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/ClangC2/include"
            ],
            "defines": [
                "_DEBUG"
            ],
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "msvc-x64",
            "configurationProvider": "vector-of-bool.cmake-tools",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/ClangC2/bin/amd64"
        }
    ],
    "version": 4
}
```

**Comment by bobbrow** [comment]
Just a note: the `compilerPath` should also include the executable name (in case CMake Tools is unable to provide a config for a given file).  But it seems the real problem is that the extension doesn't work with clangc2.

**Comment by septag** [comment]
Doesn't matter what compiler I use.
Here's the build with msvc's CL:

```
{
    "configurations": [
        {
            "name": "Win32",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}/include",
                "${workspaceFolder}/include/compat/msvc"
            ],
            "defines": [
                "_DEBUG", "_WIN32"
            ],
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "msvc-x64",
            "configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}
```

**Comment by septag** [comment]
It is the same with CL too 
I've changed my build project and c_cpp_properties to cl.exe:

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "_MBCS"
            ],
            "windowsSdkVersion": "10.0.14393.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```

It seems that it is corrupted for one of my projects only, even adding defines to _c_cpp_properties_ isn't detect and does not highlight anything in the code!

Is there some cache file or something referenced to the project, so I can clean it up ?

**Comment by bobbrow** [comment]
You can try the "Reload Window" command to refresh the extension.  If that fixes it, then we may have a bug here.

**Comment by septag** [comment]
Tried it, even reinstalled, but as I said, it has only happened to one of my projects which is weird.
Prior to this problem, I had installed/uninstalled some extensions like cmake-tools-helper and settings-sync, maybe that caused some problems ..

Is there any file or files that keep the intellisense cache, so I can delete them ?

**Comment by bobbrow** [comment]
This isn't a cache issue.  The squiggles are powered by a component that doesn't save state across sessions.  This looks like a configuration issue.  Can you add `"C_Cpp.loggingLevel": "Debug"` to your settings.json and reload the window?  The extension should print out the configurations it's using.

Do the `c_cpp_properties.json` files for both projects look identical?  Both projects are being opened on the same PC, right?

**Comment by sean-mcmanus** [comment]
You could try the Reset IntelliSense Database command (in case there's a bug that incorrectly marked the headers as non-existent in the database).
