### ISSUE TITLE
Can't navigate to headers outside folder opened in vscode.

### ISSUE THREAD

**Issue by omicronns** [microsoft/vscode-cpptools#2326]
Type: LanguageService

I can't navigate to headers that are included from outside folder opened in vscode.

- OS and Version: `Linux 4.17.6-1-ARCH`
- VS Code Version: `1.25.1`
- C/C++ Extension Version: `0.17.7`
- Clang Version: `6.0.1`

**To Reproduce**

Clone https://github.com/omicronns/vscode-cpptools-test. Build cmake project in `lib` folder with `cmake . -Bbuild && cmake --build build`. Open `lib` folder in vscode. Now one can navigate to `#include <inc_in.hxx>` but can't navigate to `#include <inc_out.hxx>`.

**Expected behavior**

Navigate to `#include <inc_out.hxx>` works.

**Comment by bobbrow** [comment]
I took a look at your `c_cpp_properties.json` and I don't see anything in there that would tell us you have dependencies outside the workspace folder (or inside, for that matter).  You need to add your dependencies to the `includePath` variable.  For example:

```
    "includePath": [
        "$[workspaceFolder}/**",
        "${workspaceFolder}/../inc_out"
    ],
````

**Comment by omicronns** [comment]
What about include directories from `compile_commands.json`?

**Comment by sean-mcmanus** [comment]
Include directories from compile_commands.json are not added to the browse.path, so those paths need to be added to the browse.path -- we have another task to fix that.
