### ISSUE TITLE
No support for C++17 nested namespace syntax

### ISSUE THREAD

**Issue by tiniuclx** [microsoft/vscode-cpptools#2327]
Type: LanguageService

**Describe the bug**
- OS and Version: Windows 7
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them): n/a
- A clear and concise description of what the bug is.

The C++17 nested namespace syntax (e.g. `namespace my_lib::internal {....} ` as opposed to `namespace my_lib { namespace internal {...}}` ) causes errors throughout the project.

**To Reproduce**
Create a source file with the following code:
``` cpp
#include <iostream>

namespace a::b {
    void Hello(void){
        std::cout<<"hello";
    }
}

int main()
{
    a::b::Hello();
    return 0;
}
```
`a`, within the namespace declaration, is underlined in red, with the error `qualified name is not allowed`. `a` within `a::b::Hello();` is underlined in red with the error message `name followed by '::' must be a class or namespace name`.

**Expected behavior**
VS Code gives no errors, since this is legal C++. Declarations within the namespace can be accessed from other places in the project, and work with autocomplete.

**Comment by bobbrow** [comment]
Can you share your `c_cpp_properties.json`?  Your example works fine for me in both msvc and clang mode.

![image](https://user-images.githubusercontent.com/12818240/43210793-e154a2fa-8fe4-11e8-8ce7-94274136b643.png)

**Comment by sean-mcmanus** [comment]
Yeah, make sure your cppStandard is the default of "c++17".

**Comment by tiniuclx** [comment]
Changing `cppStandard` within `c_cpp_properties.json` to `c++17` fixes the issue. Thanks for the heads up!
