### ISSUE TITLE
Updating C++ Debugger dependencies... Failed at stage: getPlatformInfo Error: Command failed: wmic os get osarchitecture 'wmic' �����ڲ����ⲿ���Ҳ���ǿ����еĳ��� ���������ļ���

### ISSUE THREAD

**Issue by lutianqi** [microsoft/vscode-cpptools#233]
version 1.4.0
windows 7
After I enable the c/c++ extensions, then the following message appears. I don't know why.

Updating C++ Debugger dependencies...
Failed at stage: getPlatformInfo
Error: Command failed: wmic os get osarchitecture
'wmic' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by jacdavis** [comment]
We've gotten a few other reports of this.  I suspect some people have their machines locked down so that wmic isn't working. Can you please launch vscode elevated and try again?

**Comment by sean-mcmanus** [comment]
Also, if that workaround doesn't work, we have a fix for a future release.

**Comment by sean-mcmanus** [comment]
This fix didn't make 0.9.2 but it should be in the next one.
