### ISSUE TITLE
intillisense wont display drop down box for splashkit

### ISSUE THREAD

**Issue by bowlofgravy** [microsoft/vscode-cpptools#2330]
Issue Type: <b>Bug</b>
Hi' everyone!
Don't know what has cause the issue but intillisense isn't showing a drop down box for splashkit. an error also appears on the # for #include stating invalid macro definition:_GNU_C = 4 (1, 1). Hope someone can help as I'm new to programming C++ and the drop down helps a lot. I have checked all settings form the C/C++ website and they are all good. I'm using the latest VS code and C/C++ ms-vscode.cpptools

Extension version: 0.17.7
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details>

**Comment by bowlofgravy** [comment]
G'day All.
The issue has been fixed. I'm not quite sure what the issue was as i re-installed everything with still no success. Woke up this morning and checked VSC and it was working.

**Comment by bobbrow** [comment]
I haven't used splash kit before, but I'm glad you were able to make it work.
