### ISSUE TITLE
Don't have header errors offer to create c_cpp_properties.json when using the config API

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#2334]
I have a set of users using my plugin with the new config API, and many of them keep getting confused because they'll mistype a header name, and the vs code will offer to  add header paths. However this adds to a new c_cpp_properties.json, and then because the API is used any new locations wouldn't work anyway. I feel like using compile commands would have the same issue.

**Comment by bobbrow** [comment]
Yes, compile commands would have the same issue.  We can fix this.

**Comment by sean-mcmanus** [comment]
Fixed with 0.18.0.
