### ISSUE TITLE
Unable to open "File" resource is not available.

### ISSUE THREAD

**Issue by chaopeng** [microsoft/vscode-cpptools#2338]
Type: Debugger

**Describe the bug**
- OS and Version: Linux (Debian 4.9)
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7
- issue persists after disabling them

When I use vscode to debug chromium with gdb on Linux. Set a break point, start debug, pause on break point. it shows "Unable to open $FileName resource is not available." But I am currently openning the file.

launch.json:
```
    {
      "name": "Chromium",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/out/Default/chrome",
      "args": ["--single-process", "--user-data-dir=$HOME/.debug-user-data", "--enable-features=OverlayScrollbar", "--enable-prefer-compositing-to-lcd-text", "ht.chaopeng.me"],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    },
```
logs:
```
Breakpoint 2, UpdateScrollAndScrollTranslation () at ../../third_party/blink/renderer/core/paint/paint_property_tree_builder.cc:1246
Loaded '{chromium_path}/src/out/Default/./libembedder.so'. Symbols loaded.
...tons of Symbols loaded
```

It used to work on the last month's version. It maybe something change on vscode or on Chromium.

Please let me know if you need more information

**Comment by pieandcakes** [comment]
Can you include a log to show which file it is trying to hit? based on your information it looks like we might be sending a relative path back to VS Code and it doesn't know where the file is?

If you don't want to post it here, feel free to email it to me and I'll take a look. I suspect either Chromium changed their build system on how paths are stored in symbols or VS Code has a bug in opening files. We haven't changed anything around this area of code in the debugging extension.

**Comment by chaopeng** [comment]
I fix it by totally recompile chromium. It is issue from our side. Thank you.

**Comment by chaopeng** [comment]
I found what is change on Chromium.
Chromium recently set `strip_absolute_paths_from_debug_symbols` default to true on args.

strip_absolute_paths_from_debug_symbols seems to set the absolute file path to symbol.

If anyone have same issue, the work around will be:

```
gn args out/Default
strip_absolute_paths_from_debug_symbols=false
rebuild
```

@pieandcakes is it possible vscode fix this? I think vscode maybe assuming the symbols using relative path.

**Comment by pieandcakes** [comment]
@chaopeng If you include a log we can see what the non-working condition is doing and possibly come up with a fix. We take the path that is given to us by the debugger (`gdb` in this case) and pass it back to VS Code to open. If VS Code can't find it, then it will give the error you have. 

If the question is if VS Code will fix this, you can propose it to them on their [issues](https://github.com/microsoft/vscode/issues) page. It seems the correct fix is the workaround that you are proposing in the above comment.

**Comment by chaopeng** [comment]
@pieandcakes sorry for the dumb question. Where can I get the log you need. I don't see logs in `OUTPUT` or `DEBUG CONSOLE`, I check the source in this repo but don't know which line I should add log to.

**Comment by pieandcakes** [comment]
Logging instructions can be found [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging). Specifically we are looking for `engineLogging`

**Comment by chaopeng** [comment]
Thank you @pieandcakes. I check the log. Chromium actually set the path relative to the executable file now. Change cwd fix it.
