### ISSUE TITLE
VSCode “'fileName' file not found"

### ISSUE THREAD

**Issue by salda** [microsoft/vscode-cpptools#234]
VSCode Version: 1.5.2
OS Version: 7

Steps to Reproduce:
1. Set up VSCode, C/C++ package, g++, Clang and GDB hopefully correctly.
2. Include some file.

See http://stackoverflow.com/questions/39512079/vscode-filename-not-found. 
See https://github.com/Microsoft/vscode/issues/12151. 
![image](https://cloud.githubusercontent.com/assets/3855627/18590734/3d077624-7c30-11e6-9ed3-352ee6b91284.png)

**Comment by sean-mcmanus** [comment]
Did you set the includePath to your system headers in c_cpp_properties.json?

**Comment by salda** [comment]
Yes, 
![image](https://cloud.githubusercontent.com/assets/3855627/18591203/fb2f6034-7c31-11e6-8c7e-5d15622b2caf.png)
and it behaved differently before setting it, it was also needed to set the limitSymbolsToIncludedHeaders to false, because of the fact, that iostream and others don't have headers.

**Comment by sean-mcmanus** [comment]
As far as I can tell, we do not show the "'fileName' file not found" error message with a red squiggle. Instead, we show a green squiggle with the text "Include file not found in include directory". Are you using a different extension? Also, can you get any other include path or header file to work this way? If there is a parse error in the c_cpp_properties.json, then our code may fail.

**Comment by salda** [comment]
The green squiggle was shown before, but I fixed it, the red one is another story. I installed and enabled following extensions: C++ Intellisense, Shell, Terminal, C/C++ Snippets, C/C++ Clang, C/C++, Native Debug and Clang-Format. It is shown for any included file used as first one in the including file. I guess there isn't any parse error in c_cpp_properties.json. 
![image](https://cloud.githubusercontent.com/assets/3855627/18596474/8e907e96-7c49-11e6-94d6-fbb0287497a8.png)

**Comment by sean-mcmanus** [comment]
Via manually installing/uninstalling the various extensions you mentioned, I discovered that the C/C++ Clang extension is the cause of that error. Please visit their support site at https://github.com/mitaki28/vscode-clang/issues .

As far as I have seen, installing/uninstalling is safe to do with VS Code extensions, and whenever an extension is updated, it does an uninstall/install. The extensions settings should be saved at places like a .vscode folder that persist after an uninstall.

**Comment by salda** [comment]
Ok, thanks a lot!

**Comment by Lak4CYUT** [comment]
> Yes,
> ![image](https://cloud.githubusercontent.com/assets/3855627/18591203/fb2f6034-7c31-11e6-8c7e-5d15622b2caf.png)
> and it behaved differently before setting it, it was also needed to set the limitSymbolsToIncludedHeaders to false, because of the fact, that iostream and others don't have headers.

God, you solved my big problem!! Thanks.
