### ISSUE TITLE
I want to develop c++ applications using the open-CV framework and i have an error and i don't know what else to do.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2341]
Type: General
**Input information below**

**Describe the bug**
- OS and Version: Windows 10 x64
- VS Code Version: 1.25.1 x64
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I want to run the most simple C++ CODE using opencv with vscode
I have searched everywhere, I have not found anything. 100% I am the first who is trying to use the most popular computer vision library on VScode. and I fail on to compile.

This is the StackOverflow question I have made. *0 Answers*
https://stackoverflow.com/questions/51571894/fatal-error-opencv2-opencv-hpp-no-such-file-or-directory

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

### I want to run one openCV example in this case, this file `main.cpp`
```c++
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;


int main(int argc, char** argv )
{

  Mat img;
  img = imread("22.png");

  namedWindow("Display Image", WINDOW_AUTOSIZE );
  imshow("Display Image", img);

  waitKey(0);

  return 0;
}
```

### And i get this error

```terminal
Executing task:  g++ ./src/main.cpp -I C:/openCV/opencv/sources/include -L C:/openCV/opencv/build/x64/vc15/lib <

In file included from ./src/main.cpp:2:0:
C:/openCV/opencv/sources/include/opencv2/opencv.hpp:48:38: fatal error: opencv2/opencv_modules.hpp: No such file or directory
 #include "opencv2/opencv_modules.hpp"
                                      ^
compilation terminated.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

I am 99% sure the vscode or the compiler can't find the libs or the .libs files
## How to include this files. ?
![112](https://user-images.githubusercontent.com/20750445/43408924-2e7156ba-942b-11e8-8c11-7b3d0236c59d.PNG)

### My c_cpp_preoperties.json have this code inside

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/src",

                "C:/openCV/opencv/build/include",
                "C:/openCV/opencv/build/x64/vc15/lib",
                "C:/openCV/opencv/build/x64/vc15/bin",
                "C:/openCV/opencv/build/x64/vc15/lib/opencv_world341.lib"
            ],
            "browse": {
                "path": [
                    
            ],
                "limitSymbolsToIncludedHeaders": true
            },
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17134.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64",
            "C_Cpp.intelliSenseEngine": "Tag Parser"
        }
    ],
    "version": 4
}
```

**Screenshots**
![120_li](https://user-images.githubusercontent.com/20750445/43408410-f314abf4-9429-11e8-911e-5f9bc4ddaa8d.jpg)

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by bobbrow** [comment]
It's not complaining about libs.  It's complaining about headers.  The compiler doesn't know where to find `opencv2/opencv_modules.hpp`.  Does `opencv2` exist in `C:/openCV/opencv/sources/include`?

**Comment by ghost** [comment]
Yes sir @bobbrow  the file exist inside `C:\openCV\opencv\sources\include\opencv2`
![121](https://user-images.githubusercontent.com/20750445/43410544-dfb5220e-942f-11e8-938a-847a71b6dc67.PNG)

**Comment by ghost** [comment]
and inside the vscode if i press `ctrl + click` I navigated to the opencv.hpp file

**Comment by bobbrow** [comment]
Ah.  But you are missing most of the library.  This is what I have (note the presence of opencv_modules.hpp):

![image](https://user-images.githubusercontent.com/12818240/43411053-e5d1e2c8-93dd-11e8-9b19-8180b4d4a051.png)

**Comment by ghost** [comment]
How you generated all these files?

**Comment by bobbrow** [comment]
I used [vcpkg](https://github.com/Microsoft/vcpkg) to download them.  It's a very nice package manager tool (though I might be biased because the owners of the tool have offices around the corner from me 😉)

**Comment by ghost** [comment]
@bobbrow I installed successfully  the vcpkg and now in my vscode the intelisense not work, can't find any opencv methods modules or libs 
second where the opencv have installed?
I know the cvpkg say this:

#### step 1: `git clone https://github.com/Microsoft/vcpkg.git`
I installed inside my `C` directory

#### step 2: `PS> .\bootstrap-vcpkg.bat`
All ok

#### step 3: `PS> .\vcpkg integrate install`
All ok

#### step 4: `vcpkg install opencv`
After 1 hour of installetion and i dont know where the opencv have installed? i am comfuded any information in the internet say dont care where the opencv have installed and I say ok.

in my vscode the main.cpp look like this now:

```c++
#include <iostream>
#include <opencv2/opencv.hpp>
// #include "C:/vcpkg/packages/opencv_x86-windows/include/opencv2/opencv.hpp"


int main()
{
	cv::namedWindow("raw", cv::WINDOW_AUTOSIZE);
	cv::namedWindow("gray", cv::WINDOW_AUTOSIZE);
	cv::namedWindow("canny", cv::WINDOW_AUTOSIZE);

	cv::VideoCapture cap;
	cap.open(0);

	if (!cap.isOpened())
	{
		std::cerr << "Couldn't open capture." << std::endl;
		return -1;
	}
	
	cv::UMat bgr_frame, gray, canny;

	for (;;) 
	{
		cap >> bgr_frame;
		if (bgr_frame.empty()) break;

		cv::imshow("raw", bgr_frame);

		cv::cvtColor(bgr_frame, gray, cv::COLOR_BGR2GRAY);
		cv::imshow("gray", gray);

		cv::Canny(gray, canny, 10, 100, 3, true);
		cv::imshow("canny", canny);

		char c = cv::waitKey(10);
		if (c == 27) break;
	}

	cap.release();
	return 0;
}

```


i get this error 
```console
compilation terminated.
PS C:\Users\giorg\Documents\Development\Tests\node-addons-test\src> g++ main.cpp
main.cpp:2:30: fatal error: opencv2/opencv.hpp: No such file or directory
 #include <opencv2/opencv.hpp>
                              ^
compilation terminated.
```


then I say ok lets find where that headers have installed and I find a folder inside this directory
`C:/vcpkg/packages/opencv_x86-windows/include`


then I changed the c_cpp_properties.json to look like this:

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/src",
                "C:/vcpkg/packages/opencv_x86-windows/include" 
            ],
            "browse": {
                "path": [
                    
            ],
                "limitSymbolsToIncludedHeaders": true
            },
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17134.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64",
            "C_Cpp.intelliSenseEngine": "Tag Parser"
        }
    ],
    "version": 4
}
```


what I have changed is this
```json
"includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/src",
                "C:/vcpkg/packages/opencv_x86-windows/include" // <===== I added this in order the intelisense to work but is not working
            ],
```


any idea what I am missing ?
I have Windows 10 x 64

**Comment by bobbrow** [comment]
You will want to use `C:/vcpkg/installed/x86-windows/include` instead.

**Comment by ghost** [comment]
@bobbrow Sry but I need your help friend one more time
I have tried this command to compile my code and I get this message what should I do?

### code /src/main.cpp
```c++

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <iostream>

using namespace cv;
using namespace std;

int main() {

	Mat image;
	image = imread("./22.png", IMREAD_COLOR); // Read the file

	namedWindow("Display window", WINDOW_AUTOSIZE); // Create a window for display.

	if (!image.data) // Check for invalid input
	{
		cout << "Could not open or find the image" << std::endl;
	} else {		// Image is good!

		imshow("Display window", image); // Show our image inside it.
	}

	waitKey(0);
	return 0;
}
```

c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/src",
                "C:/vcpkg/installed/x86-windows/include",
                "C:/vcpkg/installed/x86-windows/lib"

            ],
            "browse": {
                "path": [
                    
            ],
                "limitSymbolsToIncludedHeaders": true
            },
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17134.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64",
            "C_Cpp.intelliSenseEngine": "Tag Parser"
        }
    ],
    "version": 4
}
```


### .vscode.tasks.json
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "",
            "args": [
                "g++", 
                "-I", "C:\\vcpkg\\installed\\x86-windows\\include",
                "-L", "C:\\vcpkg\\installed\\x86-windows\\lib",
                "./src/main.cpp",
                "-opencv_core341",
                "-opencv_highgui341",
                "-o app"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```


### App structure

![editor](https://user-images.githubusercontent.com/20750445/43486605-f023cf76-951c-11e8-99c4-9c4ba95d2c0c.PNG)

### Terminal Error after i pressed CTRL + SHIFT + b

```terminal
> Executing task:  g++ -I C:\vcpkg\installed\x86-windows\include -L C:\vcpkg\installed\x86-windows\lib ./src/main.cpp -opencv_core341 -opencv_highgui341 '-o app' <

C:\Users\giorg\AppData\Local\Temp\ccNFIHQq.o:main.cpp:(.text+0x51): undefined reference to `cv::imread(cv::String const&, int)'
C:\Users\giorg\AppData\Local\Temp\ccNFIHQq.o:main.cpp:(.text+0xa2): undefined reference to `cv::namedWindow(cv::String const&, int)'
C:\Users\giorg\AppData\Local\Temp\ccNFIHQq.o:main.cpp:(.text+0x119): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
C:\Users\giorg\AppData\Local\Temp\ccNFIHQq.o:main.cpp:(.text+0x139): undefined reference to `cv::waitKey(int)'
C:\Users\giorg\AppData\Local\Temp\ccNFIHQq.o:main.cpp:(.text$_ZN2cv6StringC1EPKc[__ZN2cv6StringC1EPKc]+0x42): undefined reference to `cv::String::allocate(unsigned int)'
C:\Users\giorg\AppData\Local\Temp\ccNFIHQq.o:main.cpp:(.text$_ZN2cv6StringD1Ev[__ZN2cv6StringD1Ev]+0xf): undefined reference to `cv::String::deallocate()'
C:\Users\giorg\AppData\Local\Temp\ccNFIHQq.o:main.cpp:(.text$_ZN2cv3MatD1Ev[__ZN2cv3MatD1Ev]+0x2d): undefined reference to `cv::fastFree(void*)'
C:\Users\giorg\AppData\Local\Temp\ccNFIHQq.o:main.cpp:(.text$_ZN2cv3Mat7releaseEv[__ZN2cv3Mat7releaseEv]+0x40): undefined reference to `cv::Mat::deallocate()'
C:\Users\giorg\AppData\Local\Temp\ccNFIHQq.o:main.cpp:(.text$_ZN2cv3MataSEOS0_[__ZN2cv3MataSEOS0_]+0xb4): undefined reference to `cv::fastFree(void*)'
collect2.exe: error: ld returned 1 exit status
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

this is my dirs for include
### C:\vcpkg\installed\x86-windows\include

![100_opencv_includes](https://user-images.githubusercontent.com/20750445/43486275-18986166-951c-11e8-943f-3b01e628f2f5.PNG)

### C:\vcpkg\installed\x86-windows\include\opencv2
![100_opencv_includes_opencv2](https://user-images.githubusercontent.com/20750445/43486337-4294ddaa-951c-11e8-8716-4996189c31b5.PNG)


### C:\vcpkg\installed\x86-windows\lib
![100_opencv_lib](https://user-images.githubusercontent.com/20750445/43486417-7a440320-951c-11e8-9182-1c499a5d0045.PNG)

**Comment by bobbrow** [comment]
Sorry, I think I gave you bad advice for your configuration.  vcpkg is giving you libraries built with cl.exe, not a mingw toolchain.  You may want to download a version of opencv that works with your toolchain, or you may need to build it yourself.

In any case, once you have compatible libraries, you'll need to update your task to link the libraries with the "-lopencv_core" (lower-case `L`) option.

**Comment by ghost** [comment]
Thank you. can I ask you if I can use another compiler than minGW, for example, the compiler that visual studio 2017 use? 
### Can I use MSVS compiler on vscode?

**Comment by bobbrow** [comment]
Yes you can, though we haven't released any guidance on how to build with cl.exe using tasks.json yet (though we are working on that right now).  If you are familiar with CMake, you can pick up the CMake Tools extension and use that to build your folder until we publish some build templates and guidance.

**Comment by bobbrow** [comment]
Also, vcpkg does potentially support building libraries with a different toolchain (it uses CMake to do this), but it's not fully documented and I haven't had a chance to try it out.

**Comment by ghost** [comment]
@bobbrow Thank you, I gonna wait for that. 

I think vcpkg is a great choice and is installed the opencv very easy not to much steps just this commad
`vcpkg install opencv:x64-windows`

And one more thing is I found that MinGW is outdated last update was from 2014 I am not sure if this 100% true but I thing that is bad for developing c++

Have a nice day bob

**Comment by zipzit** [comment]
> And one more thing is I found that MinGW is outdated last update was from 2014 I am not sure if this 100% true but I thing that is bad for developing c++

[Mingw-w64](http://www.mingw-w64.org/doku.php) is an advancement of the original mingw.org project, created to support the GCC compiler on Windows systems. It has forked it in 2007 in order to provide support for 64 bits and new APIs. It has since then gained widespread use and distribution.

**Comment by Jx0520** [comment]
hi,I met the same problem as you. How did you solve it?

**Comment by Utku-Savas** [comment]
Hi, I have the same problem. I compiled opencv from scratch instead installing a pre-build version.
VsCode Version: 1.42.1
Cmake Version: 3.17.0
Mingw-w64 Version: 8.1.0

c_cpp_properties

     
    {
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/Users/arcanine/Downloads/opencv-4.2.0/build/install/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
    }

Error is : fatal error: opencv2/opencv.hpp: No such file or directory #include <opencv2/opencv.hpp>

My path environment has "C:\Users\arcanine\Downloads\opencv-4.2.0\build\install\bin" path

This is the contents of opencv directory
![opencv](https://user-images.githubusercontent.com/23260717/75703629-de3d5f00-5cc8-11ea-9ee8-dca6f19f5009.PNG)

If any other information needed to solve this problem, please inform me.

**Comment by zipzit** [comment]
@Utku-Savas   I know it's sorta dated, but I did once create a pretty detailed [compile OpenCV from scratch blog entry.](https://dogfeatherdesign.com/opencv-3-0-microsoft-visual-studio-2015-cmake-and-c/)  The visual GUI CMake tool was pretty useful.  Perhaps that would help?

On the other hand I know there have been changes to windows and C++ lately with the Visual C++ 2008 64bit command prompt (which asks you what compiler you want to run...)  Not sure how that works with CMake in GUI format.

**Comment by Jx0520** [comment]
Hi，I have successfully solved it by adding the path correctly. First，you need to make sure you have successfully compiled opencv with MinGW。Then you can find the directory：opencv 、opencv2&nbsp; under the compilation&nbsp;&nbsp;directory&nbsp;you created as shown below.

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;


Finally, add the correct opencv file path in your&nbsp;tasks.json、launch.json、c_cpp_properties.json，and you can successfully debug your program with F5。
Mine is as follows：



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Utku-Savas"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 凌晨2:02
收件人:&nbsp;"microsoft/vscode-cpptools"<vscode-cpptools@noreply.github.com&gt;;
抄送:&nbsp;"J"<229406504@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode-cpptools] I want to develop c++ applications using the open-CV framework and i have an error and i don't know what else to do. (#2341)




Hi, I have the same problem. I compiled opencv from scratch instead installing a pre-build version.
 VsCode Version: 1.42.1
 Cmake Version: 3.17.0
 Mingw-w64 Version: 8.1.0
 
c_cpp_properties
 { "configurations": [     {         "name": "Win32",         "includePath": [             "${workspaceFolder}/**",             "C:/Users/arcanine/Downloads/opencv-4.2.0/build/install/include"         ],         "defines": [             "_DEBUG",             "UNICODE",             "_UNICODE"         ],         "compilerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",         "cStandard": "c11",         "cppStandard": "c++17",         "intelliSenseMode": "clang-x64"     } ], "version": 4 }  
Error is : fatal error: opencv2/opencv.hpp: No such file or directory #include <opencv2/opencv.hpp&gt;
 
My path environment has "C:\Users\arcanine\Downloads\opencv-4.2.0\build\install\bin" path
 
This is the contents of opencv directory
 
 
If any other information needed to solve this problem, please inform me.

**Comment by Jx0520** [comment]
@Utku-Savas Hi，I have successfully solved it by adding the path correctly.  First, you need to make sure you have successfully compiled opencv with MinGW and  GUI CMake tool .  Then you can find the required file path：
`D:\opencv\build\x64\MinGW\install\include`
 `D:\opencv\build\x64\MinGW\install\include\opencv`
 `D:\opencv\build\x64\MinGW\install\include\opencv2`

Finally, add the correct opencv file path in your tasks.json、launch.json、c_cpp_properties.json, and you can successfully debug your program with F5.

c_cpp_properties.json：
```
{
    "configurations": [
      {
        "name": "win32",
        "includePath": ["${workspaceFolder}/**",
            "D:/mingw-w64/bin/c++",
            "D:/opencv/build/x64/MinGW/install/include",
            "D:/opencv/build/x64/MinGW/install/opencv",
            "D:/opencv/build/x64/MinGW/install/opencv2",
            "D:/opencv/build/x64/MinGW/install/x64/mingw/lib"],
        "defines": ["_DEBUG", "UNICODE", "_UNICODE"],
        "compilerPath": "D:\\mingw-w64\\bin\\gcc.exe",
        "cStandard": "c11",
        "cppStandard": "c++17",
        "intelliSenseMode": "clang-x64"
      }
    ],
    "version": 4
  }

```
tasks.json:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "g++.exe build active file",
      "command": "D:\\mingw-w64\\bin\\g++.exe",
      "args": ["-g", 
        "${file}",
        "-o", "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "-I", "D:/opencv/build/x64/MinGW/install/include",
        "-I", "D:/opencv/build/x64/MinGW/install/include/opencv",
        "-I", "D:/opencv/build/x64/MinGW/install/include/opencv2",
        "-L", "D:/opencv/build/x64/MinGW/install/x64/mingw/lib",
        "-lopencv_core345",
        "-lopencv_imgproc345",
        "-lopencv_imgcodecs345",
        "-lopencv_video345",
        "-lopencv_ml345",
        "-lopencv_highgui345",
        "-lopencv_objdetect345",
        "-lopencv_flann345",
        "-lopencv_imgcodecs345",
        "-lopencv_photo345",
        "-lopencv_videoio345"],
      "options": {
        "cwd": "D:\\mingw-w64\\bin"
      },
      "problemMatcher": ["$gcc"],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "g++.exe build and debug active file",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}\\${fileBasenameNoExtension}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": true,
      "MIMode": "gdb",
      "miDebuggerPath": "D:\\mingw-w64\\bin\\gdb.exe",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": false
        }
      ],
      "preLaunchTask": "g++.exe build active file"
    }
  ]
}

```

**Comment by Utku-Savas** [comment]
@Jx0520 Hi, I tried your solution, but this time another error occured.
![opencv2](https://user-images.githubusercontent.com/23260717/75857902-257e3980-5e08-11ea-8b4a-0a04b24196db.PNG)
c_cpp_properties.json

    {
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/c++",
                "C:/opencv-4.2.0/build/install/include",
                "C:/opencv-4.2.0/build/install/include/opencv2",
                "C:/opencv-4.2.0/build/install/x64/mingw/lib"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
    }

task.json

    {
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "g++.exe build active file",
            "command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "-I", "C:/opencv-4.2.0/build/install/include",
                "-I", "C:/opencv-4.2.0/build/install/include/opencv2",
                "-L", "C:/opencv-4.2.0/build/install/x64/mingw/lib",
                "-lopencv_core345",
                "-lopencv_imgproc345",
                "-lopencv_imgcodecs345",
                "-lopencv_video345",
                "-lopencv_ml345",
                "-lopencv_highgui345",
                "-lopencv_objdetect345",
                "-lopencv_flann345",
                "-lopencv_imgcodecs345",
                "-lopencv_photo345",
                "-lopencv_videoio345"
            ],
            "options": {
                "cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
    }

launch.json

    {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++.exe build active file"
        }
    ]
    }
