### ISSUE TITLE
C_Cpp.clang_format_path won't accept environment variable

### ISSUE THREAD

**Issue by benlindsay** [microsoft/vscode-cpptools#2344]
Type: LanguageService

**Describe the bug**
- OS and Version: Mac OSX 10.12.6
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7
- A clear and concise description of what the bug is.

I have my clang-format in a custom path, specifically $HOME/.local/bin/clang-format. I have this on two different computers, both of which I use to edit some code via sshfs. I want to be able to specify something like this in my user settings:

```
{
    "C_Cpp.clang_format_path": "${env:HOME}/.local/bin/clang-format",
}
```

so that I get the same formatting functionality on both computers. Formatting works fine if I put in the absolute path with no variables, but all my attempts to use a variable have disabled the formatting functionality. I've tried `"${env:HOME}/.local/bin/clang-format"`,  `"${env.HOME}/.local/bin/clang-format"`, `"~/.local/bin/clang-format"`, and `"$HOME/.local/bin/clang-format"`, all with no success. After any of these attempts if I replace the path with the absolute path it immediately works again.

Is there a way to use a variable here, or some other way to fix my problem?

Thanks in advance!

**Comment by bobbrow** [comment]
There is no workaround right now (besides maybe editing the extension JavaScript yourself), but this is easy enough to fix.  We should have it for the next update.

**Comment by sean-mcmanus** [comment]
The fix I added will pick up the env in the clang_format_path when the extension starts, but any changes to the clang_format_path that has an env won't be picked up until a Reload Window is done...which seems okay to me (it'll fall back to the previous clang_format_path before the settings change).

**Comment by benlindsay** [comment]
@sean-mcmanus Awesome, thanks so much! This will be a great feature to have :)

**Comment by smhc** [comment]
Would this also fix the ability to use '${workspaceFolder}' in compilerPath?

I would like to use a 'dummy/proxy' compiler to return the include/defines to enable me to work cross-platform and need access to workspaceFolder in the path.

**Comment by sean-mcmanus** [comment]
@smhc Yes -- ${workspaceFolder} should work as well with our next release.

**Comment by sean-mcmanus** [comment]
0.18.0 should have the fix (it doesn't need a Reload Window either, as mentioned previously).

**Comment by benlindsay** [comment]
@sean-mcmanus works great! Thanks!
