### ISSUE TITLE
Intellisense stops working after new clone of OS repo to same location

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode-cpptools#2346]
Type: LanguageService
Data integrity issue when user deletes .vscode folder

- OS and Version: Windows, rs5, 177113
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7

When the user deletes the .vscode folder, the state being stored by the C/C++ extension in VSCode's memento storage is now out of sync wit the data that was in the "c_cpp_properties.json".

**To Reproduce**
Open a folder deep in the Windows OS repository. Select a C/C++ file. When prompted, allow the "WAVE for VSCode" IntelliSense provider to provide Intellisense information.

Close all VSCode instances.

Remove the .vscode folder, which is a common scenario for Windows OS developers as they often delete and re-clone their GIT repositories to the same location.

Re-open VSCode to the same folder.

**Expected behavior**
Expected a prompt that "WAVE for VSCode" would like to provide intellisense since the provider configuration in c_Cpp_properties.json no longer exists. 

**Additional context**
The prompt does not occur because the memento storage for the C/C++ plugin has saved away a value indicating to not prompt for this folder, and as a result, the user is not prompted to use the "WAVE for VSCode" Intellisense provider and the standard one is used instead.

**Comment by JohnColleran** [comment]
I hit something similar.  Resetting the properties fixed the problem.  I have no idea though why the properties setting disappeared.

**Comment by sean-mcmanus** [comment]
Fixed in our latest Insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders.
