### ISSUE TITLE
Auto-Complete issue when the C++ source code contains std::pair

### ISSUE THREAD

**Issue by Jim00000** [microsoft/vscode-cpptools#2347]
Issue Type: <b>Bug</b>

# Issues
Auto Complete works abnormally when my source code contains std::pair

# Screenshot
![Imgur](https://i.imgur.com/Y9YT5PI.gif)

Extension version: 0.17.7
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 1865)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.61GB (3.75GB free)|
|Process Argv|/usr/share/code/code ..|
|Screen Reader|no|
|VM|0%|

</details>

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-astyle|chi|0.8.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
xml|Dot|2.3.1
gitlens|eam|8.5.4
vscode-language-pack-zh-hant|MS-|1.25.5
python|ms-|2018.7.1
cpptools|ms-|0.17.7
java|red|0.29.0
vscode-icons|rob|7.25.0
llvm|RRe|0.0.2
cmake|twx|0.0.17
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0

</details>

**Comment by bobbrow** [comment]
Do you have `"C_Cpp.intelliSenseEngine": "Tag Parser"` in your settings?  This looks like the less accurate tag parser IntelliSense.

**Comment by Jim00000** [comment]
I use default settings.
It works after changing to Tag Parser.
Thanks.

**Comment by bobbrow** [comment]
That was the opposite of what I expected to hear.  Tag Parser is what should be giving you these "too many results".  `"C_Cpp.intelliSenseEngine": "Default"` is what should provide you with better results.  Tag Parser doesn't give you suggestions for local variables and it also doesn't use type information to provide the correct list of member functions.

What exactly is going wrong when you use the "Default" setting?  Apparently I misinterpreted the problem in your GIF.
