### ISSUE TITLE
C / C++ Language Server Protocol

### ISSUE THREAD

**Issue by SE2Dev** [microsoft/vscode-cpptools#235]
Are there any plans to release the C++ implementation of the language server protocol that is used in this extension?

**Comment by sean-mcmanus** [comment]
Not currently. We're using proprietary code shared with VS that can't be open sourced. Removing that dependency would be non-trivial.

**Comment by SE2Dev** [comment]
Ah yes, I was afraid that might be the case. Thanks anyway though.

**Comment by SE2Dev** [comment]
Recently I've rekindled my interest in the LSP and figured it would probably be best to clarify the original question, especially since the terminology surrounding the LSP seems to have stabilized somewhat. I'm more curious in what the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/implementors/sdks/) page calls SDKs, and was looking for one that was implemented in C or C++. After doing some digging, it seems that the majority of the logic I was looking for is present in Microsoft.VSCode.CPP.Extension.exe; Does the above statement still hold true for this?

**Comment by sean-mcmanus** [comment]
From what I understand we don't implement the LSP or the SDKs -- we use the Node.JS one. Instead, we provide a Language Server implementation, which is implemented in C++ in the binary you mentioned. The server gets LSP messages from VS Code and our own typescript/Node.JS extension code. See https://microsoft.github.io/language-server-protocol/implementors/servers/ . Maybe https://github.com/cquery-project/cquery has something you're looking for.

**Comment by hulucc** [comment]
Cquery only support project can be built with clang. We need a lsp server which supporting msvc.

**Comment by sean-mcmanus** [comment]
@hulucc Our C/C++ extension provides an LSP server that supports msvc -- is that not sufficient for some reason?

**Comment by hulucc** [comment]
@sean-mcmanus, yes but the LSP server has a lot of private method like "cpptools/queryCompilerDefaults", so it only works with vscode right now. Can be used as a "generic" LSP server or having public document about these private method would be great.
