### ISSUE TITLE
Add a "isReady" method to CppToolsApi

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#2350]
Type: LanguageService
**----- Input information below -----**
We don't register our CustomConfigurationProvider with cpptools until it's ready so that we don't get called before our initialization is complete. It would be great to have an "isReady" API so that we can register as soon as we activate, and set "isReady" when we are ready to provide configurations.

**Comment by bobbrow** [comment]
`notifyReady` method is added to v2 API.  Support in cpptools will be in the next release.

**Comment by sherryyshi** [comment]
Thanks!
