### ISSUE TITLE
Trying to debug, and or install a bluetooth driver for win 10 insiders build 

### ISSUE THREAD

**Issue by JumpingWizard** [microsoft/vscode-cpptools#2356]
Type: General
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by pieandcakes** [comment]
@JumpingWizard Please provide more information and details including a sample application, specific build numbers and what you are seeing when you install the bluetooth drivers.

**Comment by pieandcakes** [comment]
Closing until more information is provided.
