### ISSUE TITLE
workspace/symbol search broken when no cpp files in workspace

### ISSUE THREAD

**Issue by sunverwerth** [microsoft/vscode-cpptools#236]
Referencing  https://github.com/Microsoft/vscode/issues/12188

Version: cpptools 0.9.1

With cpptools installed, if I bring up the workspace/symbol search in a project without any c/cpp files, the search will stop working after I enter 3 characters.
The problem is only resolved after restarting the editor.

If I add a single cpp file to a php project, for example, this bug does not occur.

My guess is that the workspace/symbol search is stuck in a loop in this case, blocking the search feature.

![workspacesymbol](https://cloud.githubusercontent.com/assets/2094371/18608280/5767a344-7ce5-11e6-9474-88c015a0a74e.gif)

**Comment by sean-mcmanus** [comment]
Our engine is crashing. It's the same bug as https://github.com/Microsoft/vscode-cpptools/issues/238 .

**Comment by sean-mcmanus** [comment]
This has been fixed. It'll be in a future release.

**Comment by sean-mcmanus** [comment]
It didn't make 0.9.2, but it'll be in the next release.
