### ISSUE TITLE
No External window when debugging C++ with lldb, it's seem hang

### ISSUE THREAD

**Issue by YingLaiLin** [microsoft/vscode-cpptools#2362]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: OSX 10.12.6  
- VS Code Version: version 1.25.1
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
`launch.json` as follow:
{
  
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build application",
            "logging": {
                "engineLogging": true
            }
        },        
        
    ]
}

1. Go to 'Debug'
2. Click on 'Start Debugging'

**Additional context**
1. After clicking "start debugging", nothing happens. However, what I  expected is a external window appear that can accept some input.
2. Compilation seems ok for I run object file  in command line with "./" + "filename".

**Comment by pieandcakes** [comment]
@YingLaiLin It should start a Terminal window. Can you check and make sure it did not spawn behind the VS Code window? I can't duplicate this with your configuration. Are you sure the build task completes too? You can check this in your output window.

**Comment by YingLaiLin** [comment]
Sorry for later response. I did test the output file and run it in command line successfully. Besides, gdb run good. So I don't how to fix it. 
Another question is that the "output" tab output "cancelled", but I don't know why.
Here is part of log information, help it works for you.
 (2248) <-1012-interpreter-exec console "process handle --pass true --stop false --notify false SIGHUP"
1: (2248) ->NAME         PASS   STOP   NOTIFY
1: (2248) ->===========  =====  =====  ======
1: (2248) ->SIGHUP       true   false  false
1: (2248) ->1012^done
1: (2248) ->(gdb)
1: (2249) 1012: elapsed time 1
1: (2250) <-1013-break-delete 1
1: (2250) ->1013^done
1: (2250) ->(gdb)
1: (2251) 1013: elapsed time 0
1: (2253) <--exec-continue

**Comment by YingLaiLin** [comment]
I find how this happens and it has nothing to do with VSCode, Sorry. 
The window is open in terminal while I use Iterm2, thus it can't  be prompted.
Thank you for your help!
