### ISSUE TITLE
Exclude or change priority of header files

### ISSUE THREAD

**Issue by hugolundin** [microsoft/vscode-cpptools#2364]
Type: LanguageService
**----- Input information below -----**

- OS and Version: MacOS Sierra 10.13.6 (17G2208)
- VS Code Version: Version 1.25.1 (1.25.1)
- C/C++ Extension Version: 0.17.7: July 19, 2018

I have two files called `time.h` - one in /usr/local/ and one in an external directory. I would like the intellisense to use definitions in the external file, which it isn't. 

Is it possible to prioritise or exclude a header file from the includePath?

**Comment by sean-mcmanus** [comment]
For "IntelliSense" (i.e. squiggles/hover) you can prioritize by moving the external path earlier, but it needs to be a non-recursive directory (not ending in **, or the priority will be lowered). Does that solve your issue?

**Comment by hugolundin** [comment]
It unfortunately does not. I have not even added `/usr/local` to my `includePath` but the log still says 

`  Folder: /usr/local/include/ will be indexed`

**Comment by sean-mcmanus** [comment]
The "will be indexed" is for our symbol engine (go to def, go to symbol) and not "IntelliSense"-based features. If you want to exclude /usr/local/include you're should be able to add it to the files.exclude list -- but we have bug https://github.com/Microsoft/vscode-cpptools/issues/1066 which is preventing this.

**Comment by hugolundin** [comment]
I guess that solves my issue then. Thank you very much for a quick response @sean-mcmanus! 😊
