### ISSUE TITLE
Included all Cpp Standard Library but Got errors "identifier undefined"

### ISSUE THREAD

**Issue by quank123wip** [microsoft/vscode-cpptools#2366]
Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:Windows 10-64bits
- VS Code Version:1.25.1
- C/C++ Extension Version:0.17.8-Insiders&0.17.7
- Other extensions you installed (and if the issue persists after disabling them):Nothing
- A clear and concise description of what the bug is.
I installed full TDM-GCC,and I included stdc++.h(it included all C&C++Standard Library)
but I still got an error in VSCode(Of course I can compile it).

**Screenshots**
![image](https://user-images.githubusercontent.com/31064092/43778821-427abdea-9a89-11e8-8636-cefb43001156.png)
Please Ignore Chinese:)

**Comment by quank123wip** [comment]
My c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/backward",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include",
                "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/tr1",
                "C:/mingw64/x86_64-w64-mingw32/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "__GNUC__=6",
                "__cdecl=__attribute__((__cdecl__))"
            ],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++",
                    "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32",
                    "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/backward",
                    "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include",
                    "C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/tr1",
                    "C:/mingw64/x86_64-w64-mingw32/include"
                ]
            },
            "limitSymbolsToIncludedHeaders": true,
            "databaseFilename": "",
            "compilerPath": "C:/mingw64/bin/g++.exe",
            "cStandard": "c11",
            "cppStandard": "c++11"
        }
    ],
    "version": 4
}
```

**Comment by quank123wip** [comment]
After that,I had writeen another code,I was using pbds library,when the intellisense stop loading,I didn't get new error(still "scanf" is not undefined,but my compiler gived me some error:(

**Comment by quank123wip** [comment]
I think it looks like it doesn't identfiy header files in header files:(

**Comment by sean-mcmanus** [comment]
0.17.7 and previous releases has a crashing bug with gcc 8.1 headers. You should use https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.8-insiders as a workaround, and set the intelliSenseMode to gcc-x64. Does that fix your issue? You also should remove the `__GNUC__` and `__cdecl__` from your defines, because the correct versions should be picked up from g++.exe (unless that is failing to work).

If you set your C_Cpp.loggingLevel to "Debug" you can view the C/C++ Output window for "sending compilation args for..." to see the include paths and defines that end up getting used...and any errors.

**Comment by quank123wip** [comment]
Fixed:)
