### ISSUE TITLE
Inaccurate tagline and license

### ISSUE THREAD

**Issue by artagnon** [microsoft/vscode-cpptools#237]
Neither "C++ sample applications used in blog posts and demos", nor MIT license applies to this repository.

**Comment by sean-mcmanus** [comment]
He's referring to the text shown at https://github.com/Microsoft/vscode-cpptools/ .

**Comment by delmyers** [comment]
@artagnon, This repository was originally created for the stated purpose of having code for blog posts and demos, which were to be released by the MIT license. We don't have any samples yet available, though. Sorry for the confusion. I will talk to the person responsible for the sample code about this.
