### ISSUE TITLE
First line of code inside main() treated as a breakpoint, cannot remove

### ISSUE THREAD

**Issue by arminAnderson** [microsoft/vscode-cpptools#2371]
Type: Debugger

- OS and Version: Win 10 1803
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them): None
- First line underneath main() (first line of actual code, not whitespace) is treated as a break point but does not actually stop the program. Cannot remove with "remove all breakpoints" command.

1. Make simple c++ program like in the image
2. Use the debugger

![capture](https://user-images.githubusercontent.com/11141835/43814725-c353147a-9a80-11e8-9e9b-495dff8cc607.PNG)

**Comment by pieandcakes** [comment]
@arminAnderson That's our entrypoint breakpoint. we need to stop there to setup debugging. for you to stop there, you can enable `"stopAtEntry": true` in your `launch.json`. It is removed once it is hit by our debugAdapter and the debugging environment has been setup.

**Comment by arminAnderson** [comment]
@pieandcakes That makes sense, thank you for the quick reply/explanation
