### ISSUE TITLE
go to definition not working

### ISSUE THREAD

**Issue by JingGuo218** [microsoft/vscode-cpptools#2373]
**Describe the bug**
- OS and Version: Windows 64 bit
- VS Code Version:1.25.1
- C/C++ Extension Version:017.7
- Other extensions you installed (and if the issue persists after disabling them):
  => project manager, Bookmarks
- A clear and concise description of what the bug is.
  =>
Following is a simple c code. And the "Go to definition" on the test_func in main() will cause "No definition found".
I think it is caused by using the MACRO #if in the test_func. But I don't know why. An additional information: the MACRO TEST_DEF can be referenced correctly by "Go to definition".

#define TEST_DEF(_a, _b) \\
    for (_a = 0; \\
         _a != _b; \\
         _a ++)\\

void test_func(void){
    int a;
    int b=10;
    int c=0;

    TEST_DEF(a, b) {
        c++;
    } 
}

void main(){
    
    test_func();
}

Note: The configuration file is using default setting

**Expected behavior**
=> "Go to definition" on test_func in main will reference the declaration of test_func

**Comment by JingGuo218** [comment]
#define TEST_DEF(_a, _b) \
    for (_a = 0; \
         _a != _b; \
         _a ++
=> the MACR shoud be

**Comment by JingGuo218** [comment]
...
#define TEST_DEF(_a, _b) \
    for (_a = 0; \
         _a != _b; \
         _a ++
...

**Comment by JingGuo218** [comment]
OMG, I have seen some other closed issues like this issue. It seems current tool cannot support parsing MACRO right?. May I know the latest plan for parsing the MACRO?  Many thanks!

**Comment by sean-mcmanus** [comment]
You should be able to fix this via adding "#define TEST_DEF(_a, _b)" to a cpp.hint file in your workspaceFolder. This will no longer be required for Go to Definition after we implement it via the "IntelliSense" engine: https://github.com/Microsoft/vscode-cpptools/issues/255 .

![image](https://user-images.githubusercontent.com/19859882/43858891-1087e7e2-9b04-11e8-86a4-b0995da36cad.png)

**Comment by JingGuo218** [comment]
Many thanks for your quick reply. I am afraid that I have to use SourceInsight now instead of Vscode. Because the project is too huge, there are too many MACROs. I am greatly looking forward to "IntelliSense" you mentioned. It is the final piece of the puzzle that I can finally get rid of SourceInsight!! Thanks.

**Comment by sean-mcmanus** [comment]
@JingGuo218 Go to definition on functions defined using the macro TEST_DEF works with 0.19.0 -- it doesn't require adding a cpp.hint in the scenario described, but it would if the definition is not in the current translation unit. "test_func" also won't appear in the Outline view or Go to Symbol results though, which still use the symbol database for results.

**Comment by sean-mcmanus** [comment]
FYI, this is fixed with 1.10.3 (pre-release) -- no cpp.hint is required for this case.
