### ISSUE TITLE
Warning: Debuggee TargetArchitecture not detected, assuming x86_64. =cmd-param-changed,param="pagination",value="off" [New Thread 6656.0x1dcc] [New Thread 6656.0x1dbc] [New Thread 6656.0x1d60] [New Thread 6656.0x1d64]

### ISSUE THREAD

**Issue by Margie03** [microsoft/vscode-cpptools#2376]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by pieandcakes** [comment]
@Margie03 Please provide more information

**Comment by 7UM1N** [comment]
![image](https://user-images.githubusercontent.com/56424190/66625080-c3a30600-ebc0-11e9-83ab-07ef175c8de2.png)

**Comment by astinaam** [comment]
Setting "targetArchitecture": "x86_64" in launch.json doesn't work?

**Comment by sebastienmascha** [comment]
I confirm @astinaam comment. It work by adding targetArchitecture to launch.json
```
/* launch.json */
{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "x86_64",
            "program": "${workspaceRoot}/enigme",
            "preLaunchTask": "build",
            "internalConsoleOptions": "openOnSessionStart",
            "logging": {
                "moduleLoad": true,
                "programOutput": true,
                "trace": false
            },
            "showDisplayString": false,
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true, // set true to enable keyboard input
            "osx": {
                "MIMode": "lldb"
            }
        }
    ]
}
```

**Comment by pieandcakes** [comment]
@WardenGnaw

**Comment by fengxiaohu** [comment]
I was wondering if i can  use MakeFile Tools to build and debug c programe in M1 Macbook.
when i try to build ,it can generate excutable files normally,but when i want to debug it,I failed and receive same error message

Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (attach failed ((os/kern) invalid argument))
The program '/Users/xiaohufeng/Documents/HuffmanCode/decode' has exited with code 42 (0x0000002a).

**Comment by maxlv7** [comment]
> I have the same problem, but I'm using cmake M1 Macbook.

**Comment by raghuveer57** [comment]
Facing the same problem. M1 Mac.

**Comment by ZedRover** [comment]
Same problem, I tried using launch.json and CMake to debug. However, I got same error as above.

**Comment by Time-Cheung** [comment]
Install CodeLLDB and set on launch.json like below."type": "lldb". It may solve the problem.

**Comment by maxlv7** [comment]
> Install CodeLLDB and set on launch.json like below."type": "lldb". It may solve the problem. 

using cmake without launch.json can not solve the problem

**Comment by 777ki** [comment]
> Install CodeLLDB and set on launch.json like below."type": "lldb". It may solve the problem.

install the vs Code extension `LLDB` fix that problem on M1 mac

**Comment by shihuade** [comment]
Same problem, and my solution is: add one configuration in launch.json as below, and finally it works.

-             "targetArchitecture": "arm64",

**Comment by BabyMelvin** [comment]
> Setting "targetArchitecture": "x86_64" in launch.json doesn't work?

What if risc-v .  The targetArchitecture suggested values not include it .

`The architecture of the debuggee. This will automatically be detected unless this parameter is set. Allowed values are x86, arm, arm64, mips, x64, amd64, x86_64`

**Comment by coffeebe4code** [comment]
Is there a way to set this in setupCommands? I'm also on riscv

**Comment by coffeebe4code** [comment]
Yes is the answer here. @BabyMelvin 

      "setupCommands": [
        {
          "description": "Sets Riscv",
          "text": "set architecture riscv:rv64",
          "ignoreFailures": false
        }
      ]

Set that or rv32 in your launch json configuration
