### ISSUE TITLE
Intellisense Parser "SQL Lite" Error

### ISSUE THREAD

**Issue by MRobertEvers** [microsoft/vscode-cpptools#2378]
Type: LanguageService
**----- Input information below -----**

**Describe the bug**
- OS and Version: Windows 10 Enterprise Version 10.0 Build 17134
- VS Code Version: 1.25.1
- C/C++ Extension Version: Tested on 17.7 and 17.8-Insider
- Other extensions you installed (and if the issue persists after disabling them): None

General Intellisense does not work. Autocompletion offers no suggestions, Go To Definition says "No definition found", etc. 

**To Reproduce**
__settings.json__
```
    {
        "C_Cpp.intelliSenseEngine": "Tag Parser"
     }
```

__c_cpp_properties.json__
```
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/main"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}/main"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceFolder}/.vscode/database.vc.db"
            },
            "cStandard": "c11",
            "cppStandard": "c++17"
        }

```
**Expected behavior**
I expect to see auto-completion suggest symbols found in the browse.path and "Go To Definition" to navigate to header/c file when applicable.

**Additional context**
I prowled some of the issues and I set VSCode debug to output a log file. I get the following errors at the bottom of the log file.
```
Removed file: C:\USERS\ABUMRE1\DOCUMENTS\GIT_REPOS\MAIN.C
Done discovering files.
Parsing open files...
Parsing remaining files...
[rc=0x80640065] (code_store::a_store::get_file) SQLite Error 1: SQL logic error or missing database: not an error
SQL text: SELECT * FROM files WHERE id = ?1 LIMIT 1
update_file_if_needed: C:\USERS\ABUMRE1\DOCUMENTS\GIT_REPOS\CORE_INTERFACE.C
[rc=0x80640065] (code_store::a_store::get_file) SQLite Error 1: SQL logic error or missing database: not an error
SQL text: SELECT * FROM files WHERE id = ?1 LIMIT 1
[rc=0x80640065] (code_store::a_store::get_file) SQLite Error 1: SQL logic error or missing database: not an error
SQL text: SELECT * FROM files WHERE id = ?1 LIMIT 1
[rc=0x80640065] (code_store::a_store::get_file) SQLite Error 1: SQL logic error or missing database: not an error
SQL text: SELECT * FROM files WHERE id = ?1 LIMIT 1
[rc=0x80640065] (code_store::a_store::get_file) SQLite Error 1: SQL logic error or missing database: not an error
SQL text: SELECT * FROM files WHERE id = ?1 LIMIT 1
```

I rolled back to a previous version __16.1__ which I definitely had working at one point and I am getting these errors now

```
Parsing open files...
Parsing remaining files...
update_file_if_needed: C:\USERS\ABUMRE1\DOCUMENTS\GIT_REPOS\CORE_INTERFACE.H
  File no longer exists.
update_file_if_needed: C:\USERS\ABUMRE1\DOCUMENTS\GIT_REPOS\HTTP_INTERFACE.C
  File no longer exists.
update_file_if_needed: C:\USERS\ABUMRE1\DOCUMENTS\GIT_REPOS\HTTP_INTERFACE.H
  File doesn't exist.
update_file_if_needed: C:\USERS\ABUMRE1\DOCUMENTS\GIT_REPOS\MAIN.C

```

I recently installed and enabled WSL. From my reading of other issues, it looks like this might have something to do with it.

Additionally, I am using a custom toolchain. So I don't want to use a Linux or Windows toolchain. Previously, VSCode had no issue with this.

__Update__
I tested VSCode on another folder which I never opened with WSL and everything worked... 

WSL does impact this in some way. @sean-mcmanus Points out that it is probably case sensitive filepaths.

__Resolution__
VSCode needs to be 'tricked' into WSL mode. See @sean-mcmanus 's answer below.

**Comment by sean-mcmanus** [comment]
It shouldn't be using WSL. Can you set your compilerPath to "cl.exe" (or the path to that?)? If your folder has a case-sensitive file system enabled we don't support that on Windows yet (except in WSL mode). Did you try doing a Reset IntelliSense Database command and making sure no dangling processes exist that could be using the same database?

**Comment by MRobertEvers** [comment]
@sean-mcmanus 
I tested VSCode on another folder which I never opened with WSL and Intellisense worked as I expected.

I did try resetting the database with no success.

How do I enable WSL mode? I am trying with the following instructions
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md

I think my issue is that I want to rapidly switch between accessing that folder in windows AND in WSL. Is there a way to support this?

**Comment by sean-mcmanus** [comment]
I think you can add an includePath with "/" (at the start) to "trick" it to go into WSL mode. Some of the docs might be out-of-date. If you intend to compile the code with WSL, you should set your compiler path to something like "/usr/bin/gcc" and your intelliSenseMode to "clang-x64" (or gcc-x64 with the Insiders) and then set your includePath to something like `"/mnt/c/…"` -- but we have bug https://github.com/Microsoft/vscode-cpptools/issues/2361 which can cause the /mnt symbols to not get parsed -- a fix hasn't been released for yet (it should next week). If you're switching between WSL and non-WSL configs, it's possible we have a bug and you may need to do a Reload Window command to make the switching work correctly.

**Comment by MRobertEvers** [comment]
Truly a master of your trade... It is working now!

```
{
    "configurations": [
        {
            "name": "WSL",
            "includePath": [
                "/mnt/c/Users/abumre1/Documents/Git_Repos/main"
            ],
            "defines": [],
            "intelliSenseMode": "gcc-x64",
            "compilerPath": "/usr/bin/gcc",
            "browse": {
                "path": [
                    "/mnt/c/Users/abumre1/Documents/Git_Repos/main"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```
__Edit__
Changed `gc` to `gcc`

**Comment by sean-mcmanus** [comment]
You might want to change ""/usr/bin/gc" to "gcc" (unless gc is a compiler I'm not familiar with). You can set your C_Cpp.loggingLevel to "Debug" and view the C/C++ output window to make sure the correct compiler is being picked up (i.e. system include/defines are used).
