### ISSUE TITLE
whenever I use a set or an unordered set the intellisense stops working

### ISSUE THREAD

**Issue by ysftaha** [microsoft/vscode-cpptools#2388]
Type: LanguageService

**Describe the bug**
- OS and Version: Manjaro 17.1.11 Hakoila
- Kernel : x86_64 Linux 4.14.57-1-MANJARO
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.17.7
- whenever I write a set or an unordered_set the autocompletion stops working and all Im left with is snippets and keywords

**To Reproduce**
*Im not using a c_cpp_properties.json ... I use code-runner, I just need to run one file, Im competing*
1. initiate a set.

**Comment by sean-mcmanus** [comment]
This is bug https://github.com/Microsoft/vscode-cpptools/issues/2328 -- it was fixed last week with our 0.17.8-insiders release at https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.8-insiders . Well, assuming you're using gcc 8.1 (unordered_set includes type_traits, which is the source of the crash).

**Comment by ysftaha** [comment]
@sean-mcmanus  Looks like it, thanks.
