### ISSUE TITLE
ExternalConsole Option not working on macOS with Xcode newest lldb-mi

### ISSUE THREAD

**Issue by TrungNguyen1909** [microsoft/vscode-cpptools#2389]
Type: Debugger
LLDB

- OS and Version: macOS 10.14
- VS Code Version: 1.25.1
- C/C++ Extension Version:0.17.7
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
launch.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "cwd":"${fileDirname}"
        },
        {
            "name": "C++",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "cwd": "${fileDirname}",
            "MIMode":"lldb",
            "miDebuggerPath": "/usr/local/bin/lldb-mi",
            "externalConsole": true,
            "preLaunchTask": "Build C++17",
            "environment": []

        }
    ]
}`
1. Start debugging

Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
`Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=thread-selected,id="1"
=library-unloaded,id="/Users/trung/Documents/codeforces/Contest 503 Div2/B",target-name="/Users/trung/Documents/codeforces/Contest 503 Div2/B",host-name="/Users/trung/Documents/codeforces/Contest 503 Div2/B"
Loaded '/Users/trung/Documents/codeforces/Contest 503 Div2/B'. Symbols loaded.
Loaded '/usr/lib/dyld'. Symbols loaded.
Loaded '/usr/lib/libc++.1.dylib'. Symbols loaded.
Loaded '/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.ubsan_osx_dynamic.dylib'. Symbols loaded.
Loaded '/usr/lib/libSystem.B.dylib'. Symbols loaded.
Loaded '/usr/lib/libc++abi.dylib'. Symbols loaded.
`
By the way, using Xcode lldb-mi is essential since there is some problems with variables inspect,.. with the packed one.

**Comment by pieandcakes** [comment]
@TrungNguyen1909 You are probably missing a component called `lldb-launcher` that you need for `lldb` to launch the external terminal. This is included in our shipped version of `lldb-mi` but may not be with XCode's. We also made fixes within our version of `lldb-mi` to work properly with VSCode.

**Comment by anyflow** [comment]
> @TrungNguyen1909 You are probably missing a component called `lldb-launcher` that you need for `lldb` to launch the external terminal. This is included in our shipped version of `lldb-mi` but may not be with XCode's. We also made fixes within our version of `lldb-mi` to work properly with VSCode.

As you mentioned, I couldn't find `lldb-launcher` in Xcode's. Anyway, what does 'our version of `lldb-mi`? Can I download it?

**Comment by pieandcakes** [comment]
@anyflow It comes as part of the extension on macOs and is in the ~/.vscode/extensions/ms-vscode.cpptools<version>/debugAdapter/lldb folder

**Comment by anyflow** [comment]
> @anyflow It comes as part of the extension on macOs and is in the ~/.vscode/extensions/ms-vscode.cpptools/debugAdapter/lldb folder

I found it in the directory, But when I designated `lldb-mi` in it as `miDebuggerPath`, vscode debugger doesn't work properly(same effect with no value in `miDebuggerPath`. Because of this, I put `lldb-mi` path of XCode's)

What should I do?

**Comment by pieandcakes** [comment]
>  found it in the directory, But when I designated lldb-mi in it as miDebuggerPath, vscode debugger doesn't work properly(same effect with no value in miDebuggerPath

unfortunately that is the one that works with external console set to true. If you want to use lldb-mi that ships with XCode, I don't know of a workaround to get the external console to work.

**Comment by luxueyan** [comment]
The same problem! It cannot open the terminal!
