### ISSUE TITLE
No any Squiggles

### ISSUE THREAD

**Issue by zhaoyewei** [microsoft/vscode-cpptools#2390]
**Describe the bug**
- OS and Version: win 10
- VS Code Version: 1.25.1
- C/C++ Extension Version:0.17.7

![image](https://user-images.githubusercontent.com/6638644/44002840-0478b352-9e7c-11e8-995d-dd528eaeef99.png)

My settings:

    "C_Cpp.errorSquiggles": "Enabled",
    "C_Cpp.formatting": "Default",
    // "C_Cpp.loggingLevel": "Debug",
    "C_Cpp.loggingLevel": "Information",
    // "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.intelliSenseMode": "clang-x64",
    "C_Cpp.intelliSenseEngineFallback": "Disabled",
    "C_Cpp.autocomplete": "Default",
    // "C_Cpp.intelliSenseEngine": "Tag Parser",
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.clang_format_path": "D:/LLVM/bin/clang-format.exe",
    "C_Cpp.clang_format_style": "{ BasedOnStyle: LLVM, IndentWidth: 4}",

**Additional context**
When i type.Even debug,no message show in "problems".why?

**Comment by zhaotongxue** [comment]
Yesterday time is limited so the message is less.Now i attach some to it.
My Extensions list:
C/C++ for Visual Studio Code Change Log Version 0.17.7: July 19, 2018
Code Runner 0.9.4 (2018-08-03)
Include Autocomplete 0.0.4
Vim v0.16.0 (2018-08-09)
Two themes.

Just this.
The completement can be shown,even though the speed is not fast enough.But there is no any Squiggles what ever i type.What's the error with it?
//my c_cpp_properties.json
```
{
    "version": 4,
    "configurations": [
        {
            "name": "MinGW",
            "intelliSenseMode": "clang-x64",
            "compilerPath": "D:/mingw-w64/mingw64/bin/gcc.exe",
            "includePath": [
                "${workspaceFolder}",
                "${fileFolder}",
                "D:/mingw-w64/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++",
                "D:/mingw-w64/mingw64/x86_64-w64-mingw32/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "__GNUC__=7",
                "__cdecl=__attribute__((__cdecl__))"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ]
}
```

**Comment by zhaoyewei** [comment]
Oh sorry i found that my workspace setting is not the same as user setting and workspace setting  is priority to user setting.Now it works.Still thanks.



Plus,why it's so slow😂
