### ISSUE TITLE
Show variable length array in debugger

### ISSUE THREAD

**Issue by xinyuezheng** [microsoft/vscode-cpptools#2393]
Issue Type: <b>Bug</b>

Platform: linux, gcc, gdb
Showing variables inline and in the local variables window, structures with variable length array show empty value. E.g.:

```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct some_object {
  int thickness;
  char name[];
};

int main(void)
{
  struct some_object *obj = malloc(40);
  obj->thickness = 1;
  strcpy(obj->name, "line");
  printf("%s\n", obj->name);
  return 0;
}
```

Observation: put a breakpoint at printf line. Then obj->name in variables windows shows empty.

Expectation: I expect it to be recognized as a char* and therefore shows the text "line" in this case.

Extension version: 0.17.7
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.13.0-46-generic

**Comment by pieandcakes** [comment]
@xinyuezheng We don't do any processing for the variable. We rely on `gdb`'s pretty printing in `mi` mode to show the value. This may be something that needs a new/updated pretty printer to resolve on `gdb`'s side.

**Comment by mnelissen** [comment]
It works for me, when I enter the following into the debug console in visual studio code:
```
-exec print *obj
$1 = {thickness = 1, name = 0x555555756264 "line"}
```
GDB prints the correct string "line", while in the GUI the obj->name stays empty.

**Comment by mnelissen** [comment]
Ping. Any update on this issue? I'm not 100% sure what the label 'external' means, but in my last comment I tried to point out that I think it's not a problem on GDB's side, but in the parsing by the plugin somehow.
