### ISSUE TITLE
Extern API for changing settings

### ISSUE THREAD

**Issue by chkp-roic** [microsoft/vscode-cpptools#2394]
Hi,
I'm currently writing an extension and since I need to modify the include path and I have no guarantee c_cpp_properties.json exists, I have my extension create it manually and modify the settings, of course this creates potential issues like what will happen when your configuration file will be upgraded...

Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Provide a code sample including configuration files such as c_cpp_properties.json*

**Expected behavior**

**Screenshots**

**Additional context**
*Call Stacks: For bugs like crashes, deadlocks, infinite loops, etc. that we are not able to repro and for which the call stack may be useful, please attach a debugger and/or create a dmp and provide the call stacks. Starting with 0.17.3, Windows binaries have symbols available in VS Code by setting your "symbolSearchPath" to "http://msdl.microsoft.com/download/symbols".*
Add any other context about the problem here including log messages in your Output window ("C_Cpp.loggingLevel": "Debug" in settings.json).

**Comment by sean-mcmanus** [comment]
We do have an API for a custom configuration provider which extensions can use via the npm module called "vscode-cpptools": https://github.com/Microsoft/vscode-cpptools-api . Let us know if you have any questions about how to use that -- @bobbrow is the expert at that.

**Comment by chkp-roic** [comment]
I will check it out, thanks Sean!
