### ISSUE TITLE
Cannot parse the openssl header

### ISSUE THREAD

**Issue by Frank-Shaw-FS** [microsoft/vscode-cpptools#2399]
Issue Type: <b>Bug</b>

I have followed the instructions to set up the developement environement of WSL. It works perfectly for the sqlite3 and other standard POSIX header file, except for openssl, whenever I include the <openssl/rsa.h> or something else, the editor keep telling me cannot open the source file, please update the include path.
The following is my cpp_properties.json
```json
  {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/include/**",
                "${localappdata}/lxss/rootfs/usr/include/c++/5",
                "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                "${localappdata}/lxss/rootfs/usr/include/c++/5/backward",
                "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                "${localappdata}/lxss/rootfs/usr/local/include",
                "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu",
                "${localappdata}/lxss/rootfs/usr/include/**",
                "${localappdata}/lxss/rootfs/usr/local/ssl/include"
            ],
            "defines": [
                "__linux__",
                "__x86_64__"
            ],
            "browse": {
                "path": [
                    "${localappdata}/lxss/rootfs/usr/include/c++/5",
                    "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                    "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                    "${localappdata}/lxss/rootfs/usr/local/include",
                    "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                    "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu",
                    "${localappdata}/lxss/rootfs/usr/include/*",
                    "${localappdata}/lxss/rootfs/usr/local/ssl/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "clang-x64"
        }
```

Extension version: 0.17.7
VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.69GB free)|
|Process Argv|C:\Users\FrankShaw\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
I'm not able to repro the issue. What source file isn't being found and where is it actually located? How did you install the openssl/rsa.h file? I'm using vcpkg. The usage of "/usr/include/**" might cause issues and shouldn't be needed (none of the system paths should be needed if you set the compilerPath instead). You could also use the simpler "/usr/local/ssl/include" path. If you set your C_Cpp.loggingLevel to "Debug" you can check the C/C++ Output window for what include paths are getting used after "sending compilation args for...".

![image](https://user-images.githubusercontent.com/19859882/44093406-551de52c-9f88-11e8-8b5e-1af8927a1a28.png)

**Comment by Frank-Shaw-FS** [comment]
It seems you use the normal Windows environment while I use the WSL. I install the openssl in the WSL environment that under /usr/local/ssl.
My problem is that I try to make the vscode C++ work like under LINUX by using WSL, and the extension cannot get the openssl folder path even I have set the include path that works flawlessly in other header file like splite3.h, unistd.h
![image](https://user-images.githubusercontent.com/5810166/44125594-1900c292-a066-11e8-9a8e-fa3ea9d683a7.png)
![image](https://user-images.githubusercontent.com/5810166/44125613-2a8fd5ac-a066-11e8-9456-e6b0915fb3e7.png)
![image](https://user-images.githubusercontent.com/5810166/44125672-6f99539e-a066-11e8-9bd1-fe68f9d07a48.png)


After I place the openssl header folder under the /mnt/d/include, the green wave line not display anymore, however, when I try to nagivate to PEM_read_RSAPrivateKey function, it still shows no definition found. 

I guess the cause is that the <openssl/pem.h> include a folder path, if I include the header as <pem.h> and change the includepath to /mnt/d/include/openssl, the editor will warn me "cannot open source file "opessn/e_os2.h"(dependency of pem.h)" that I think the editor get the correct path now but fail to get the full include dependency done.

**Comment by sean-mcmanus** [comment]
I'm using the WSL compiler and system headers but with the non-WSL openssl, which I think should still work -- using a compilerPath or includePath starting with "/" turns it into WSL mode....using the Windows path to the WSL headers was supposed to switch it to WSL mode too, but it looks like that is the bug. We should have a fix in the next release, but replacing the "${localappdata}/lxss/rootfs/" part should workaround that issue for now.

The Go to Def failure is https://github.com/Microsoft/vscode-cpptools/issues/2361 .

It's possible there's another bug I'm missing?

What command do I run to install the WSL OpenSSL? The commands I run fails to install it for some reason.

**Comment by bobbrow** [comment]
`sudo apt-get install libssl-dev`

I'm taking a look at this.

**Comment by bobbrow** [comment]
I am unable to repro with the default config on the latest version of WSL (from the [Windows Store](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot%3aoverviewtab)).

```
{
    "configurations": [
        {
            "name": "WSL",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

![image](https://user-images.githubusercontent.com/12818240/44157558-9663d200-a067-11e8-8295-51ea13e9555b.png)

Can you tell us where you got your instructions to set up WSL from?  You are using the "legacy" WSL instance, and in that instance I can't even install openssl with the `apt` command I pasted above so I'm not sure how you got openssl on the filesystem in the first place if you just recently installed WSL.  Are you able to upgrade to the latest Ubuntu from the Windows Store?

There may be another issue here though that @sean-mcmanus pointed out to me, so I'll investigate that too.

**Comment by bobbrow** [comment]
oops, silly me, I forgot to `sudo apt-get update`.  I haven't used that distro in a long time.

**Comment by bobbrow** [comment]
I can confirm that openssl works fine with my config above in the Legacy WSL distro as well.  Can you try it out and let us know if that solves your problem?

**Comment by bobbrow** [comment]
I don't repro with the config pasted in the first post either.  I do see this line though which suggests that you've acquired openssl in some other way: `"${localappdata}/lxss/rootfs/usr/local/ssl/include"`.  If you can please share how you acquired openssl, that would be very helpful.

**Comment by Frank-Shaw-FS** [comment]
I download the official release and build the ssl manually by using make. It install the header folder under the /usr/local/ssl by default. If you use the apt-get to get the libssl-dev, it will place the header under /usr/include.  

After I copy the folder under the /usr/include, it works. Besides, it also works when I copy the folder to /mnt/d/include and set the includePath as "/mnt/d/include". As my previous post https://github.com/Microsoft/vscode-cpptools/issues/2399#issuecomment-413058855 , after copy the folder to /mnt/d/include, the warning disappear, but still can't get the file. But it works after I restart the vscode today.
![image](https://user-images.githubusercontent.com/5810166/44180991-cb3c5b80-a131-11e8-9187-0020a0e5e1cb.png)
![image](https://user-images.githubusercontent.com/5810166/44181631-44897d80-a135-11e8-89f4-6b3e5c9d32c6.png)


Then I use the previous setting, set the includePath as "${localappdata}/lxss/rootfs/usr/local/ssl/include",  it still have the same error.
![image](https://user-images.githubusercontent.com/5810166/44181062-35ed9700-a132-11e8-80d2-6eda888f4b21.png)

**Comment by bobbrow** [comment]
The tooltip in your screenshot is telling me that you have the newer Ubuntu distro from the Windows Store installed.  But your c_cpp_properties.json is referencing the older one.  Which one are you developing on?

What do you see when you run `wslconfig /l`?  I suspect that it shows that "Ubuntu" is your default instead of "Legacy" and that is causing the extension to be "confused" about your configuration.  If you intend to use the Legacy distro, you should set it as the default with `wslconfig /s Legacy`.

Note: When you have the proper distro set with wslconfig, you can use linux-style paths to rootfs in the includePath (e.g. `/usr/local/ssl/include` instead of `${localappdata}/lxss/rootfs/usr/local/ssl/include`)

**Comment by Frank-Shaw-FS** [comment]
![image](https://user-images.githubusercontent.com/5810166/44190395-29c90000-a159-11e8-9ff1-36db5f57aa75.png)
I get this in MS Store after I reinstall the system by using the win 10 fall update iso. 

Thank you,@bobbrow. It works after I change the path to linux-style.

**Comment by bobbrow** [comment]
Good to hear.  And just to close the loop I wanted to check on your c_cpp_properties.json.  This is what I would expect to see (system include paths/defines are added automatically when you set the `compilerPath`)

```
{
    "configurations": [
        {
            "name": "WSL",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/local/ssl/include"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by Frank-Shaw-FS** [comment]
```json
{
            "name": "wsl",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/include/**",
                "/usr/include/c++/5",
                "/usr/include/x86_64-linux-gnu/c++/5",
                "/usr/include/c++/5/backward",
                "/usr/lib/gcc/x86_64-linux-gnu/5/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include",
                "/usr/local/ssl/include"
            ],
            "defines": [
                "__linux__",
                "__x86_64__"
            ],
            "browse": {
                "path": [
                    "/usr/include/c++/5",
                    "/usr/include/x86_64-linux-gnu/c++/5",
                    "/usr/lib/gcc/x86_64-linux-gnu/5/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                    "/usr/include/x86_64-linux-gnu",
                    "/usr/include/*",
                    "/usr/local/ssl/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "clang-x64"
        }
],
 "ver;sion":4
```

**Comment by bobbrow** [comment]
You should remove the system includes from the configuration.  And `browse.path` is optional now.  We will use the setting from `includePath` if they are effectively the same.  I did notice you were missing `${workspaceFolder}` in the browse.path but I assume that was not intentional.

This config should work for you:

```
{
            "name": "wsl",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/local/ssl/include"
            ],
            "defines": [
                "__linux__",
                "__x86_64__"
            ],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "clang-x64"
        }
```
