### ISSUE TITLE
Automatically include c++ std headers in OS X

### ISSUE THREAD

**Issue by jansanz** [microsoft/vscode-cpptools#24]
In OSX I noticed that any std headers were not found by default so I had to add to the include path:

```
/usr/include/c++/4.2.1
```

**Comment by j-stephan** [comment]
Same for Linux.

**Comment by spinicist** [comment]
`/usr/include` doesn't exist on my system (El Capitan 10.11.5), so I had to add `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1`

**Comment by jgoshi** [comment]
In the next release of cpptools (version 0.10.0) we automatically look for headers under /usr/include (recursive search) as the default. If your system is different, you can still manually add the correct paths to your includePath.
