### ISSUE TITLE
Support Xcode framework include path

### ISSUE THREAD

**Issue by leira** [microsoft/vscode-cpptools#240]
Xcode framework's include path is strange, when I say `#include <CoreFoundation/CFString.h>`, it actually means to include file:

```
$(xcodebuild -sdk iphoneos -version Path)/System/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h
```

I tried to put `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks` in configurations.includePath and hope vscode-cpptools support it, but no luck. `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/Headers` doesn't work either.

I guess there is no way to configure it without vscode-cpptools support this kind of search, could you please add support for Xcode framework?

 What's needed is:

When searching header files for `#include <FrameworkX/HeaderY.h>`, also search `FrameworkX.framework/Headers/HeaderY.h` and `FrameworkX.framework/PrivateHeaders/HeaderY.h`.

**Comment by sean-mcmanus** [comment]
@leira You should be able to get this to work via adding the root path of the headers to your includePath. Unfortunately, we actually ignore the "path" in the #include and only use the file name. In other results, we don't filter out results if the path in #include <path/file> doesn't match. If you're not able to get this to work, then it could be some other bug.
