### ISSUE TITLE
Incorrect regex for windowsSdkVersion in c_cpp_properties.json

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2400]
I've configured c_cpp_properties.json with the following

"windowsSdkVersion": "10.0.17134.12"

And the SDK version gets underlined - the regex it's applying seems to assume the last token (12) should be 1 character, the current version has 2.

**Comment by bobbrow** [comment]
The patch number is not reflected in the include path on disk.  The Windows SDK version should still be `10.0.17134.0`.  I just installed 10.0.17134.12 to confirm and it does get installed to `C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0`
