### ISSUE TITLE
Debugger not responding at all

### ISSUE THREAD

**Issue by esmg1** [microsoft/vscode-cpptools#2402]
Type: Debugger

- OS and Version:  Windows 7 Home Premium
- VS Code Version: Windows x64-1.26.0
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them): Debugger for Java by Microsoft, Language Support for Java(TM) by Red Hat, Python by Microsoft

I am trying to use the debugger for testing some code in c++. But nothing happens when I do so. There's no notifications, nor errors appearing on my screen. 
The debugger doesn't seem to work at all. If I click on "Start Debugging" or press F5, nothing happens after I select "C++ (Windows)" or "C++ (GDB/LLDB).
If I try to put something into the console, it says: Please start a debug session to evaluate.
This is only happening with C++, all other extensions work just fine.

**Comment by WardenGnaw** [comment]
Are you debugging a C++ program compiled by mingw or cl.exe?

The selecting "C++ (Windows)" or  "C++ (GDB/LLDB)" will generate a launch.json you will need to configure depending on what kind of C++ project you have.

**Comment by esmg1** [comment]
It's a file I wrote in visual studio code to test it. I thought it'd compile it and then run it. 
Also, it seems that the IntelliSense isn't working for me.
I can't find any .json file related to the files I'm working on.
![problems](https://user-images.githubusercontent.com/41656697/44171156-1ce7d600-a09f-11e8-8af1-e998880da02f.png)

**Comment by pieandcakes** [comment]
@esmg1 Did you compile your code? If so, which compiler did you use? Can you share your `launch.json` configuration?

**Comment by WardenGnaw** [comment]
Closing issue. Please create a new ticket with any additional information requested here if you are still encountering issues.
