### ISSUE TITLE
Unable to start debugging. Launch options string provided by the project system is invalid.

### ISSUE THREAD

**Issue by BDZNH** [microsoft/vscode-cpptools#2405]
**Describe the bug**
- OS and Version: Windows 10 1803. 17134.165
- VS Code Version: 1.26.0
- C/C++ Extension Version: 0.17.7
- Other extensions you installed (and if the issue persists after disabling them): None.
the error look like this 

![image](https://user-images.githubusercontent.com/17548735/44130634-04300a88-a081-11e8-9bdb-3d4940d6bf8a.png)

This is the `launch.json`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb)",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "D:\\CodeBlocks\\MinGW\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

This is the `tasks.json`
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build hello world",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g", "${fileBasenameNoExtension}.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

I have google the error, but I don't get  helpful information.
-----
And there are no the char "0x08", the `launch.json` look like this in the notepad++ with show all characteres.
![image](https://user-images.githubusercontent.com/17548735/44130857-1ca69798-a082-11e8-9630-65821905c1bb.png)

Any one can help?😀

**Comment by pieandcakes** [comment]
Please enable [engineLogging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) and post the output.

**Comment by BDZNH** [comment]
Thanks a lot @pieandcakes . And I find the reason.
Missing a character "\\" in the path of the gdb.exe.

**Comment by pieandcakes** [comment]
Ok. Let me know if you need more help.
