### ISSUE TITLE
"Configure your IntelliSense settings to help find missing headers." not super helpful

### ISSUE THREAD

**Issue by marcoscaceres** [microsoft/vscode-cpptools#2408]
When the error for "Configure your IntelliSense settings to help find missing headers." comes up, it doesn't actually tell you where to go and add/fix the configuration file. This means spending a bunch of time Googling what to actually do. 

Could you please add some instructions as to where to click? Or provide some kind of link that goes straight to the the right settings/place?

**Comment by sean-mcmanus** [comment]
Yeah, I think we could add a button to message box to open the settings, like we do with the code action on the green squiggles with "#include errors detected".

![image](https://user-images.githubusercontent.com/19859882/44209526-9d96e880-a118-11e8-9142-529174f92c3e.png)

**Comment by sean-mcmanus** [comment]
Actually -- we already do show a Learn More button.

![image](https://user-images.githubusercontent.com/19859882/44211083-0a13e680-a11d-11e8-9eaf-3f0c58c94cf6.png)

Which sends users to 
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started%20with%20IntelliSense%20configuration.md

Is this not sufficient for some reason? We could also auto-open the c_cpp_properties.json for the user.

**Comment by marcoscaceres** [comment]
I did eventually click “Learn more”, but it was unclear that learn more was not about the extension. Maybe the button can be renamed?

**Comment by sean-mcmanus** [comment]
VS Code added "Source: C/C++ (Extension)" to the UI, which didn't used to be there, which sort of makes the "Learn More" look like it applies to the extension generally instead of the specific message.

We could change it to "Configuration Help": https://github.com/Microsoft/vscode-cpptools/pull/2410 -- it's possible other people on our team might disagree though (I'll see).

**Comment by marcoscaceres** [comment]
"Configuration Help" sounds great.

**Comment by sean-mcmanus** [comment]
Fixed with 0.18.0.
