### ISSUE TITLE
Update gulp dev dependency

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2413]
Our gulp dev dependency has some vulnerabilities getting reported by npm audit. We should update to a newer version of gulp, but the problem is there are breaking API changes so it might take some work.

Gulp doesn't ship with the extension, so it only affects users who debug our extension.

**Comment by WardenGnaw** [comment]
Whoops. Originally saw Alphas for 4.0. 

I'm assuming this is upgrading Gulp from `3.9.1` to `4.0.0`?

**Comment by bobbrow** [comment]
`lodash`

**Comment by bobbrow** [comment]
![image](https://user-images.githubusercontent.com/12818240/44239123-8e418a80-a16c-11e8-9fac-e31c56538459.png)

**Comment by sean-mcmanus** [comment]
Yeah, going to Gulp 4.0.0 has breaking API changes. I tried to do this, but I abandoned the effort due to issues -- you can run "npm audit fix --force". I'm seeing lodash only have a low pri issue, but minimatch with 4 high issues.
