### ISSUE TITLE
Adding a folder to a workspace for the first time does not show the "<Provider> would like to configure your IntelliSense" message

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#2415]
If I open a workspace that already contains multiple folders, all the folders get IntelliSense. But new folders that I add to a workspace that are opened for the first time don't get the prompt, and therefore don't get IntelliSense configurations from CustomConfigurationProviders.

**Comment by sean-mcmanus** [comment]
Fixed with 0.18.0, although it's possible a C/C++ file in the new workspace folder might need to be opened first -- let us know if that's an issue for you.

**Comment by sherryyshi** [comment]
thanks Sean! I think the current behavior is fine.
