### ISSUE TITLE
Issue with headers

### ISSUE THREAD

**Issue by Mujohaso** [microsoft/vscode-cpptools#2423]
- OS and Version: Win 10
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.0

Hello! I'm quite new to using VS Code and to programming in general. Right now I'm having problems with headers
![a](https://user-images.githubusercontent.com/42471773/44270732-a088fa80-a238-11e8-8c1d-015e2d0d25d3.PNG)
![b](https://user-images.githubusercontent.com/42471773/44270733-a088fa80-a238-11e8-8874-a41a2473459f.PNG)
![c](https://user-images.githubusercontent.com/42471773/44270734-a088fa80-a238-11e8-8d3e-2d7e92c77445.PNG)

Whenever i try to run either of my cpp files it shows an error like this 
![d](https://user-images.githubusercontent.com/42471773/44270751-ada5e980-a238-11e8-8ef9-441489e516eb.PNG)
![e](https://user-images.githubusercontent.com/42471773/44270752-ada5e980-a238-11e8-8cc6-0368e1561169.PNG)

So I was wondering how can I use those void functions from the tutorial2.cpp in tutorial1.cpp? Did i write something wrong? All the files are in the same folder. I'm trying to learn how to play around with headers to not have really lengthy code by splitting it into 2 files and I'm stuck.
Is something maybe wrong with the  c_cpp_properties.json?
![f](https://user-images.githubusercontent.com/42471773/44270892-ffe70a80-a238-11e8-9b5a-ab32d145d819.PNG)

Any help is appreciated :)
Thank you in advance

**Comment by sean-mcmanus** [comment]
The c_cpp_properties.json is only used for configuring our IntelliSense feature and not actual compiling. It looks like you're having a linker error due to not defining a main() entry point or in your 1st case you're not compiling the definitions in tutorial2.cpp but are referencing them in the header. Try compiling all your source files together.

**Comment by Mujohaso** [comment]
Could you please elaborate more? or suggest a fix? I'm still quite lost... Sorry for bothering with such trivial things

**Comment by sean-mcmanus** [comment]
Can you try running something like "g++ -g tutorial/tutorial01.cpp tutorial/tutorial2.cpp -o tutorial1.exe"? Whatever your source files reference has to be built/linked in order to work. See something like: https://stackoverflow.com/questions/3202136/using-g-to-compile-multiple-cpp-and-h-files .

**Comment by Mujohaso** [comment]
Thank you so much!! You have no idea how much this helped me
running that command creates and .exe file and then i can run it and it does exactly what i want perfectly.
Thank you again for you time and help!
