### ISSUE TITLE
_WIN32 automatically defined for clang-x64 in 0.18.0

### ISSUE THREAD

**Issue by BlueHeaven1969** [microsoft/vscode-cpptools#2425]
Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:  Windows 7
- VS Code Version:  1.26.1
- C/C++ Extension Version: 0.18.0

Setting intelliSenseMode to clang-x64 (or the new gcc-x64) has _WIN32 automatically defined.  This was previously only automatically defined in msvc-x64

**To Reproduce**
*Provide a code sample including configuration files such as c_cpp_properties.json*
Using a simple code snippet:
```
#ifdef _WIN32
#error go away!
#endif
```
Previously setting intelliSenseMode to "clang-x64" would not define _WIN32 and the snippet would not show an error.  Since updating to 0.18.0, the error is shown.

**Comment by sean-mcmanus** [comment]
Yeah, I think we may have to ship a 0.18.1 patch for this. https://github.com/Microsoft/vscode-cpptools/issues/2424 is the same issue.

**Comment by sean-mcmanus** [comment]
What compiler are you using? i.e. what is your compilerPath? Is it a mingw, WSL, etc.?

**Comment by sean-mcmanus** [comment]
I assume you're using a Cygwin or related compiler, and not mingw, clang. or a WSL compiler.

**Comment by BlueHeaven1969** [comment]
I'm cross compiling using IAR for ARM.  But I set the compiler path to gcc for ARM:
`"compilerPath": "C:/Users/Rst.Pie/Tools/GnuArm/bin/arm-none-eabi-gcc.exe"`

**Comment by sean-mcmanus** [comment]
Okay, yeah, that's similar to the Cygwin case -- we have a fix for that. The code was adding --ms-extensions like a mingw compiler does by default when it shouldn't have.

**Comment by sean-mcmanus** [comment]
Should be fixed now with 0.18.1.
