### ISSUE TITLE
"C_Cpp.loggingLevel": "None" not working

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-cpptools#2429]
Win10, VSCode 1.26.1, extension 0.18.1
my settings
```json
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.loggingLevel": "None"
```

![image](https://user-images.githubusercontent.com/11925432/44290546-c4d1ef00-a2ab-11e8-8ccd-a3cfc59aa097.png)

I still get annoying problems!

![image](https://user-images.githubusercontent.com/11925432/44290634-2c883a00-a2ac-11e8-853f-e46193d6f36e.png)

How to disable problems?

**Comment by bobbrow** [comment]
`#include` squiggles are the only errors we don't have a setting to disable at the moment.

Is there a reason you don't want to set the correct include path?  IntelliSense won't work very well without it which is why we haven't exposed an option to disable these squiggles.

**Comment by kzhui125** [comment]
I use this extension to read, write, format [mql](https://www.mql5.com/en/docs/basis) code. (by setting files.associations to cpp)

`#include <Object.mqh>` is like `#include <vector>` in C++

I don't need any squiggles.😀

**Comment by bobbrow** [comment]
If you're just doing formatting and nothing else, you might be better off with the standalone clang format extension.  It would be lighter weight than ours.

**Comment by kzhui125** [comment]
@bobbrow  Thanks.
