### ISSUE TITLE
includePath not working (?)

### ISSUE THREAD

**Issue by Fishrock123** [microsoft/vscode-cpptools#2430]
Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: macOS 10.13.6
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): 12
- A clear and concise description of what the bug is.

VS Code doesn't seem to read one of my paths correctly ("bob.h").

I have no idea what I am possibly doing wrong as one of my other header paths works fine (node.js source). 

The only confusing bit is why `${workspaceFolder}/**"` doesn't just pick up this file in the first place, as it is actually within the same workspace.

**To Reproduce**

My includePath
```
"includePath": [
                "${workspaceFolder}/**",
                "/Users/Jeremiah/Documents/node/src",
                "/Users/Jeremiah/Documents/bob-modules/bob-base"
],
```

`<bob.h>` can't be found.
<img width="486" alt="screen shot 2018-08-17 at 6 23 11 pm" src="https://user-images.githubusercontent.com/1093990/44291187-bbfd0100-a24a-11e8-8855-63f951fb11c9.png">

The file is clearly available within that path.
```
ls /Users/Jeremiah/Documents/bob-modules/bob-base
bob.h           license
contributing.md package.json
include_dirs.js readme.md
```

This is my project structure / workspace.
<img width="282" alt="screen shot 2018-08-17 at 6 23 31 pm" src="https://user-images.githubusercontent.com/1093990/44291203-d20ac180-a24a-11e8-8937-dd0a96ad10d2.png">

**Expected behavior**

`<bob.h>` should be found as it is within my included paths.

**Comment by bobbrow** [comment]
What other extensions have you installed?  That message doesn't look like ours.  When our extension fails to find a file we say `cannot open source file "bob.h"`

**Comment by Fishrock123** [comment]
Oh crap... I guess I had `C/C++ Clang Command Adapter` installed from some unknown time. I rarely use VS Code except for C++ on my Mac.

Ok I think this is closed... I'm not really sure, my project is small but it takes forever for changes to reindex or something.

**Comment by bobbrow** [comment]
If you have more details about what is taking longer than expected, let us know and we can investigate.
