### ISSUE TITLE
vscode can't open files from the Problems tab in a cmake project

### ISSUE THREAD

**Issue by tinyredpanda** [microsoft/vscode-cpptools#2431]
Type: LanguageService

**Describe the bug**
- OS and Version: Ubuntu 14.04
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): I disabled all the other extensions and the issue persists.

The Problems tab can't open the files in a cmake project.

**To reproduce**
1. create a folder named `sandbox`,
2. create a `main.cpp` in it and put an intentional error in it to make the gcc give a compiler error,
3. create a `CMakeLists.txt` in `sandbox`,
4. create minimal tasks (one for running cmake and one for running ninja/make),
5. put `"problemMatcher": "$gcc"` in the build task,
5. run cmake & ninja/make then try and open the file in the Problems tab.

The filepath in Problems path is shown as `~/repositories` next to `main.cpp` which is wrong, it should be `~/repositories/sandbox` (or `home/vuser/repositories/sandbox`).

Strangely enough the filepath changes once `CMakeLists.txt` is moved to `sandbox/buildsys`, in this case the filepath is shown correctly (`home/vuser/repositories/sandbox`) in the Problems tab but it still can't be opened.

**Expected behavior**
Be able to open the files correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/39399309/44298400-6cfeac80-a2da-11e8-9157-d724eee6f3c5.png)
`CMakeLists.txt` and `main.cpp` in `sandbox`.
![image](https://user-images.githubusercontent.com/39399309/44298417-a3d4c280-a2da-11e8-9ece-6c706b267e34.png)
`CMakeLists.txt` in `sandbox/buildsys` and `main.cpp` in `sandbox`.

Contents of the project `sandbox`:
**main.cpp** in `sandbox`
```
int main()
{
    abort
    return 0;
}
```
**CMakeLists.txt** in `sandbox`
```
project(hello-cmake)
add_executable(hello-cmake main.cpp)
```
**tasks.json**
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "cmake sandbox",
            "type": "shell",
            "command": "cmake",
            "args": [
                "..",
                "-G",
                "Ninja"
            ],
            "options": {
                "cwd": "${workspaceRoot}/build"
            }
        },
        {
            "label": "build sandbox",
            "type": "shell",
            "command": "ninja",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "cwd": "${workspaceRoot}/build"
            },
            "problemMatcher": "$gcc"
        }
    ]
}
```

**Comment by bobbrow** [comment]
Unfortunately, the problem matcher is expecting an absolute path.  We're tracking this issue with #2266.

**Comment by bobbrow** [comment]
In the meantime, a workaround for this could be to use the [CMake Tools extension](https://marketplace.visualstudio.com/items?itemName=vector-of-bool.cmake-tools) instead of tasks.json.  That's what I use to build my projects (including the cpptools extension).
