### ISSUE TITLE
Linaro GDB remote debugging

### ISSUE THREAD

**Issue by mal10c** [microsoft/vscode-cpptools#2432]
I'm trying to configure Visual Studio Code to remotely debug GDB.  GDB server is running on Linux on a Raspberry Pi and Visual Studio Code is running on Windows.

I should note that I'm running Linaro GDB as a cross-compiler (but I don't think that matters in this case).

From Linux I can start GDB server with:
```bash
gdbserver --attach 10.0.0.1:9999 15717
```

Where 15717 is the PID of my running process I want to debug.

From Windows I can use GDB via Command Line with this:
```
arm-linux-gnueabihf-gdb TheProgram -ex "target extended 10.0.0.2:9999"
```

And that all works.

When I move over from the Command Prompt to Visual Studio Code, I get some problems (and I think it has to do with absolute paths).  I set up my launch.json file with this:
```json
{
   "version": "0.2.0",
   "configurations": [
      {
         "type": "gdb",
         "request": "attach",
         "name": "Attach to gdbserver",
         "executable": "./TheProgram",
         "printCalls": true,
         "target": "10.0.0.2:9999",
         "remote": true,
         "cwd": "${workspaceRoot}/build/RaspberryPi"
      }
   ]
}
```

And make sure the GDB server is running.  Then I start debugging and in the Debug Console I see this:

> 7-break-insert -f "H:\\projects\\TheProgram.cpp:93"
> No source file named H:\projects\TheProgram.cpp.

I think the issue is Visual Studio Code is inserting the absolute path when issuing the break-insert command.  Is there a way to change that so it's using a relative path?

I think it would work if I could find a way to see this instead:
> 7-break-insert -f "TheProgram.cpp:93"

I should also note that in Visual Studio Code, I opened the H:\projects folder and that's what I'm working from.

I'm submitting this as an issue because I think it might be a bug.

**Comment by pieandcakes** [comment]
@mal10c if your `"type"` is `gdb`, this is not the extension you are using. our `"type"` for gdb debugging with this extension is `"cpptools"`. you may want to track down which extension you are using and file the issue there. 

If you want to use our extension, you can explore our [documentation](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md#remote-debugging-or-debugging-with-a-local-debugger-server) regarding remote debugging and give that a shot.

**Comment by snahmad** [comment]
My config is
{
            "type": "gdb",
            "request": "attach",
            "name": "Attach to gdbserver",
            "executable": "../bin/squiddebug/pip",
            "target": "192.168.43.68:1234",
            "remote": true,
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText",
            "gdbpath": "/home/syeda/workspace/work/build/multigw_cpp_1.3.12/host/usr/arm-buildroot-linux-gnueabi/sysroot/bin/arm-buildroot-linux-gnueabi-gdb",
            "additionalSOLibSearchPath": "/home/syeda/workspace/apps-zwave-source/lib/squiddebug"
            "customLaunchSetupCommands": [
                {
                  "description": "Enable pretty-printing for gdb",
                  "text": "file /home/syeda/workspace/apps-zwave-source/bin/squiddebug/pip",
                }
              ]
        }

I am getting this
No symbol table is loaded.  Use the "file" command.

**Comment by pieandcakes** [comment]
@snahmad I left you a comment [here](https://github.com/microsoft/vscode-cpptools/issues/815#issuecomment-524387358). You aren't using this extension. Please contact the owners of the extension you are using.
