### ISSUE TITLE
sizeof(long) does not respect the data model of the target

### ISSUE THREAD

**Issue by easyaspi314** [microsoft/vscode-cpptools#2434]
Type: LanguageService

**Describe the bug**
- OS and Version: Windows 10 Home x64, version 1803, build 17134.228
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): none
- WSL version info:
```
$ uname -a
Linux dont-need-this 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
$ gcc-5 --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
apt dependencies: `sudo apt install build-essential gcc-5`

Summary:
[Info on data models](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models)
Even though the target, WSL, is LP64, with the `__LP64__` macro defined, `long` is still treated as if it is LLP64 on Windows, being 4 bytes instead of 8. `__LLP64__` is not defined.

**To Reproduce**
Use the following c_cpp_properties.json (Note that this is with GCC 5, change the includes to the ones listed by `echo | gcc -E -Wp,-v -`):
```json
{
    "configurations": [
        {
            "name": "WSL",
            "intelliSenseMode": "clang-x64",
            "compilerPath": "/usr/bin/gcc-5 -x c -m64",
            "includePath": [
                "/usr/lib/gcc/x86_64-linux-gnu/5/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include"
            ],
            "defines": [
                "__linux__",
                "__x86_64__"
            ],
            "browse": {
                "path": [
                    "/usr/lib/gcc/x86_64-linux-gnu/5/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                    "/usr/include/x86_64-linux-gnu",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```
Put this in an empty C file called test.c (name doesn't matter as long as it ends in .c):
```c
#if defined (__LLP64__)
#pragma message("This is a LLP64 target.")
_Static_assert(sizeof(long) != sizeof(void *), "this should not happen");
_Static_assert(sizeof(long) == 4, "this should not happen");
_Static_assert(sizeof(void *) == 8, "this should not happen");
#elif defined(__LP64__)
#pragma message("This is a LP64 target.")
_Static_assert(sizeof(long) == sizeof(void *), "this should not happen");
_Static_assert(sizeof(long) == 8, "this should not happen");
_Static_assert(sizeof(void *) == 8, "this should not happen");
#else
#error "unsupported arch"
#endif

unsigned long long i = sizeof(long);
```

The second block, `__LP64__`, is highlighted, but the first two `_Static_assert`s fail (see screenshot).

Hovering over the `sizeof(long)` in the bottom part says `(unsigned long long)4ULL`.

Checking the code with the compiler, the `_Static_assert`s pass:
```
$ gcc-5 -fsyntax-only test.c
test.c:7:9: note: #pragma message: This is a LP64 target.
 #pragma message("This is a LP64 target.")
         ^
```

**Expected behavior**
The second block, `__LP64__` will be highlighted and the three `_Static_assert`s will pass in both the compiler and in the editor. 

Hovering over the `sizeof(long)` will say `(unsigned long long)8ULL` or `(unsigned long)8UL`.

GCC will say "This is a LP64 target.".

**Screenshots**

![vscode lp64 bug](https://user-images.githubusercontent.com/6258309/44303676-0b0f6880-a315-11e8-9f90-4bc6d40935d4.png)

**Comment by easyaspi314** [comment]
Related to #2312

**Comment by bobbrow** [comment]
Thanks for the feedback.  I'm using #1083 to track this issue.  Please go upvote that issue so we can track the demand.

**Comment by michelleangela** [comment]
Closing as duplicate.
