### ISSUE TITLE
It takes a few seconds to start reindex when i add a #include in  .c files...

### ISSUE THREAD

**Issue by suzukajiang** [microsoft/vscode-cpptools#2439]
vscode:  1.26.1
Cpptools: 0.18.1
Windows 7

It takes a few seconds to start reindex when i add a #include in  .c files...

**Comment by bobbrow** [comment]
Are you talking about refreshing the squiggles?  We do that on an idle timer or when the file is saved to avoid doing too much expensive work

**Comment by suzukajiang** [comment]
I have opened autosave in vscode, it would be saved every second. But the refresh did't happened until about ten seconds later，and the autocompletion didn't work until the refresh finished.

**Comment by bobbrow** [comment]
autosave doesn't currently work very well with the extension because it will queue off a lot of tasks to update the squiggles and that will delay autocomplete results the larger your files get.  It's something we need to improve, but I just thought I would let you know for now.

**Comment by suzukajiang** [comment]
I've tried ctrl + s  after I finished typing, but it didn't work.  But the refresh works well when i modified the.c file except add a #include.

**Comment by suzukajiang** [comment]
I have found the reason, there is no "browse.path" in c_cpp_properties.json by default。thank you very much!!!!
