### ISSUE TITLE
lots of clang-format processes

### ISSUE THREAD

**Issue by agauniyal** [microsoft/vscode-cpptools#244]
I checked the output of `htop` command after using vscode for a while and noticed numerous clang-format processes lying around. I'm not sure but somehow this plugin is spawning new clang-format processes and not exiting them properly.

**Comment by pieandcakes** [comment]
@sean-mcmanus Have you noticed this at all?

**Comment by sean-mcmanus** [comment]
I have not noticed that. It'd be great to have more repro details. I assume it's a Linux OS. Is the clang-format version 3.8? I assume 0.9.1 of the extension. I'll see if I can find a way to repro it.

**Comment by agauniyal** [comment]
Yes linux system with `clang-format version 3.8.1 (tags/RELEASE_381/final)` and latest extension.

**Comment by sean-mcmanus** [comment]
I seem to be reproing this, but the clang-format are being closed when VS Code exits. I'll investigate.

**Comment by agauniyal** [comment]
I can confirm that they exit once VSCode is closed, but shouldn't they exit by the time they've done their formatting part?

**Comment by sean-mcmanus** [comment]
Yes, the clang-format process should exit when it's done with its work. It does on Windows.

**Comment by sean-mcmanus** [comment]
It's been fixed for the next release -- we weren't handling Linux "zombie" child processes correctly. The "zombie" processes shouldn't use any system resources other than entries in the process table.
