### ISSUE TITLE
Struct definition inside function not supported

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode-cpptools#2442]
Type: LanguageService

**Description**

The language service fails to parse struct definitions that occur inside function scope.

Please take a look at those screenshots.

Screenshot 1
![vscode-bug-cpp-1](https://user-images.githubusercontent.com/15984272/44468031-9a25c480-a624-11e8-9941-c10ab4ebb2cf.PNG)
Screenshot 2
![vscode-bug-cpp-2](https://user-images.githubusercontent.com/15984272/44468034-9b56f180-a624-11e8-9df4-8d456faf6093.PNG)

**To Reproduce**

- Open these files and change extension to .c
[test.txt](https://github.com/Microsoft/vscode-cpptools/files/2310662/test.txt)
[test2.txt](https://github.com/Microsoft/vscode-cpptools/files/2310661/test2.txt)
- Do as in screenshots

**Expected behavior**

Expected in screenshot 1: `d`, `e` and `f` show up instead of `a`, `b`, `c` which make no sense
Expected in screenshot 2: After pressing F12 (Go to definition), the definition on line 5 should be focused.

**Screenshots**
See above

**Additional context**

VS Code version: Code - Insiders 1.27.0-insider (e0a68266321d1518bc12428b71d80524461a275b, 2018-08-22T05:18:13.273Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.36GB free)|
|Process Argv|C:\Users\GUILLIAMS.S\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
favorites|kdc|1.7.3
cpptools|ms-|0.18.1
vscode-fileutils|sle|2.10.3
vim|vsc|0.16.0

(1 theme extensions excluded)

</details>

**Comment by bobbrow** [comment]
I think the problem is the green squiggle at the top of the file.  It causes us to switch IntelliSense over to our tag parser implementation which does not parse out local variables and types.

![image](https://user-images.githubusercontent.com/12818240/44472008-11863480-a5e2-11e8-8658-022deedd25ad.png)

Can you share your `c_cpp_properties.json` file?  I suspect that either something is misconfigured, or the extension was unable to locate the standard headers on your PC.

The Goto defintion issue is known and we are tracking it with #255.

**Comment by sguillia** [comment]
The file `c_cpp_properties.json` file does not exist.

I indeed ignored the green squiggles because I don't care if standard headers are not found.

It is normal that the extension didn't find them because they are in an unusual directory.

> It causes us to switch IntelliSense over to our tag parser implementation

When removing `#include <stdio.h>`, the autocompletion works and propose `d`, `e` and `f`. 
But how can I force the extension to stay in the "normal" mode?

I don't really want to fix the missing include if it isn't absolutely required since it is an extra effort to me.

**Comment by bobbrow** [comment]
Click on the green squiggle, then click on the lightbulb that appears and select "force semantic IntelliSense"

**Comment by sguillia** [comment]
When removing `#include <stdio.h>`, the autocompletion works as expected.

When forcing semantic IntelliSense (`"C_Cpp.intelliSenseEngineFallback": "Disabled"`), the autocompletion does not work for any of the structures I've declared (`item1` and `item2`).

If I remove the include, then it works again as expected, no matter if semantic IntelliSense was forced.

**Comment by bobbrow** [comment]
Thanks for the info.  I can reproduce your issue.  We'll investigate.

**Comment by sean-mcmanus** [comment]
The Go to Definition on "bar" has been fixed with 0.19.0. I'm not able to repro the completion issue with the fallback even with 0.18.1 -- @bobbrow since you appear to have gotten a repro can you see if it's still a bug? Did you ever investigate this yet?

**Comment by bobbrow** [comment]
My repro involves recursive includes, and an empty `compilerPath` string which results in no include directories being sent to the IntelliSense server.  This causes an error in the server when *any* `#include` is attempted in the file.

For the time being, you should be able to work around this issue by adding any non-recursive path to your `includePath` in `c_cpp_properties.json` (e.g. "${workspaceFolder}")

**Comment by sean-mcmanus** [comment]
The completion issue should be fixed with 0.20.0.
