### ISSUE TITLE
Incorrect error squiggles when using new to create an array of struct pointers

### ISSUE THREAD

**Issue by arminAnderson** [microsoft/vscode-cpptools#2443]
Type: LanguageService

**Describe the bug**
- OS and Version: Win 10, 1803
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): Plastic theme, still persists
- A clear and concise description of what the bug is:

Line of code: 
`SDL_Texture **rTextures = new SDL_Texture *[count];`

Error message: 
> call of an object of a class type without appropriate operator() or conversion functions to pointer-to-function type

For some reason, "new" is underlined in red. This line of code has no error marking in Visual Studio Community 2017, and it compiles fine with MinGW-x64. SDL_Texture is a struct defined in the SDL library, and viewable in the header file as: 
`struct SDL_Texture;`
`typedef struct SDL_Texture SDL_Texture;`

**To Reproduce**
*Provide a code sample including configuration files such as c_cpp_properties.json*
1. Have SDL set up
2. Write code snippet

**Expected behavior**
No underlined "new"

**Comment by bobbrow** [comment]
This reproduces with an even simpler snippet of code (with MinGW or WSL on Windows):

```
int *p = new int[10];
```

It appears to be an inconsistency with the `__SIZE_TYPE__`, but we need to investigate more.  It doesn't repro in clang/gcc mode if `compilerPath` is set to empty string (e.g. disabled), so it appears that the defines returned by the compiler are influencing this behavior.

**Comment by arminAnderson** [comment]
Thank you for the fast reply and adding it to the list! It's this kinda stuff that makes me happy to support vscode

**Comment by sean-mcmanus** [comment]
You should be able to add "-fno-ms-extensions" to the end of your compilerPath to work around this issue, although it might regress other errors (such as https://github.com/Microsoft/vscode-cpptools/issues/2363 ).

UPDATE: Should be fixed with https://github.com/Microsoft/vscode-cpptools/releases/download/0.19.1-insiders/cpptools-win32.vsix .

**Comment by arminAnderson** [comment]
Yeah that seems to do the trick, I'll keep that in there for now. Thanks for the heads up, I appreciate it
