### ISSUE TITLE
Can‘t attach remote linux  process - sh failure

### ISSUE THREAD

**Issue by aengusjiang** [microsoft/vscode-cpptools#2444]
Type: Debugger
**Input information below**

![image](https://user-images.githubusercontent.com/22406984/44521802-f06b3400-a706-11e8-98db-6c2a2bf94329.png)

sh: 1: [: Linux: unexpected operator
sh: 1: [: Linux: unexpected operator
please help me to solve this issue.
thanks.

**Describe the bug**
- OS and Version: Windows 10 1803
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.0: August 17, 2018
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
build the test and run it on ubuntu16.04.
Open the test code and Debug with attach.

Note:  It works well about previous version.
 
Here the demo code.

[test.zip](https://github.com/Microsoft/vscode-cpptools/files/2314144/test.zip)

**Comment by Thanduel** [comment]
I have the same issue.

my versions
- Windows 10 1803 build 17134.228
- vs code version 1.26.1
- C/C++ Extension Version: 0.18.1

I noted that the behaviour is changed by removing the pipeArg -c.  What follows is the ouput in that case.  I'm not really sure what is going on there but it does appear that the sh call has the -c arg even though it has been removed from the pipeArgs.

```
/bin/bash: sh -c 'uname && if [ Linux == Linux ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ Linux == Darwin ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi': No such file or directory
Command failed: "c:\windows\system32\bash.exe"  "sh -c 'uname && if [ $(uname) == "Linux" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) == "Darwin" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi'"
/bin/bash: sh -c 'uname && if [ Linux == Linux ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ Linux == Darwin ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi': No such file or directory
```

Launch.json:

 ```
{
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/mnt/s/Work/repositories/ardupilot/ardupilot/build/sitl/bin/arduplane",
            "processId": "${command:pickRemoteProcess}",
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "c:\\windows\\sysnative\\bash.exe",
                "pipeArgs": ["-c"],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/mnt/s": "s:\\"
            }
        }
```

**Comment by XZiar** [comment]
Same issue here.
output is:

> Linux
> sh: 1: [: Linux: unexpected operator
> sh: 1: [: Linux: unexpected operator

Windows 10 1803 build 17134.228
vs code version 1.26.1
C/C++ Extension Version: 0.18.1

**Comment by czgtest** [comment]
Same issue here when I debug c module solution

**Comment by formulahendry** [comment]
Same issue here using C/C++ Extension Version: **0.18.1**, while it is working using **0.17.7**.

**Comment by pieandcakes** [comment]
This seems to be affecting all instances of remote process picking due to this change #2340

**Comment by pieandcakes** [comment]
@timedroid pointed out what is wrong in #2473 and a fix. 

In the mean time the workaround would be to modify  
`.vscode\extensions\ms-vscode.cpptools-0.17.7\out\src\Debugger\attachToProcess.js` located in your user profile folder (`%userprofile%` for Windows, `~/` for Linux).

Update line 92/93 to say:

```
        const command = `sh -c 'uname && if [ $(uname) = "Linux" ] ; then ${nativeAttach_1.PsProcessParser.psLinuxCommand} ; elif [ $(uname) = "Darwin" ] ; ` +
            `then ${nativeAttach_1.PsProcessParser.psDarwinCommand}; fi'`;

```

The fix will be in the next update.
