### ISSUE TITLE
Add additional SO Lib Search Path to debuger

### ISSUE THREAD

**Issue by edsousa84** [microsoft/vscode-cpptools#2445]
Type: Debugger

- OS and Version: Ubuntu 18.04 64bit and 14.04 32bit
- VS Code Version: 1.26.1 64bit and 125.0 32bit
- C/C++ Extension Version: 0.18.1
- Installed extensions:
> - alefragnani.project-manager
> - anseki.vscode-color
> - austin.code-gnu-global
> - christian-kohler.npm-intellisense
> - codezombiech.gitignore
> - donjayamanne.git-extension-pack
> - donjayamanne.githistory
> - eamodio.gitlens
> - fduman.vscode-nodemcu
> - gayanhewa.local-history
> - ms-python.python
> - ms-vscode.cpptools
> - msjsdiag.debugger-for-chrome
> - narekmal.vscode-run-git-difftool
> - olback.vscode-serial
> - rkostrzewski.monitor-file
> - slevesque.vscode-hexdump
> - trinm1709.dracula-theme-from-intellij
> - vikas.code-navigation
> - ziyasal.vscode-open-in-github

- Description of the bug:
I what to use a external (.so) shared lib on my code that is not located on the standard /usr/lib. The shared lib is on the repository of the project.
The code compiles correctly and I can run the code on a terminal (copying the .so file to the same folder of the program)
Now I am using VScode to develop. And I found out that on the launch.json fiel there is a parameter additionalSOLibSearchPath that passes to the GDB the .so path. But it does not work.

- To Reproduce:
launch.json:
`
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/Build/Debug/Progname",
            "additionalSOLibSearchPath": "${workspaceFolder}/ExternalLibs/include/;${workspaceFolder}/ExternalLibs/static",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
`
I also tried to make the full path and to point directly to the .so files and it did not work.

`"additionalSOLibSearchPath": "${workspaceFolder}/ExternalLibs/static/libwebsockets.so.5.0.0;${workspaceFolder}/ExternalLibs/static/libwebsockets.so",`
And
`"additionalSOLibSearchPath": "/home/username/projects/repos/projectgitfolder/ExternalLibs/static/libwebsockets.so.5.0.0;/home/username/projects/repos/projectgitfolder/ExternalLibs/static/libwebsockets.so",`

I managed to make it work by running the program from the .so folder "cwd": "${workspaceFolder}/ExternalLibs/static", This way I run the program with the .so libs next to the exec file. But I don't think this is the best way to make it work.

- Steps to reproduce the behavior:
1. configure C++ tools as stated on [https://code.visualstudio.com/docs/languages/cpp](https://code.visualstudio.com/docs/languages/cpp) using the launch.json as stated above.
2. Click on the debug and launch the debuger
3. The DEBUG CONSOLE output is:
`=thread-group-added,id="i1"
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
`
And it does not run the debugger
4. When I put the .so on the /usr/lib or I change the cwd parameter:
`=thread-group-added,id="i1"
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".`

**Comment by pieandcakes** [comment]
@priestnot Please enable [engineLogging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) and post the library loads.

**Comment by edsousa84** [comment]
@pieandcakes I have reinstalled vscode and it now works.
I did not understand what happen.

Thank you.
