### ISSUE TITLE
#include errors detected with WSL

### ISSUE THREAD

**Issue by lapcca** [microsoft/vscode-cpptools#2446]
I met the #include errors detected error with my simple hello world and configuration  with WSL 

background:
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
C/C++ plugin:0.18.1

```
"#include errors detected. Please update your includePath. IntelliSense features for this translation unit (C:\\workspace\\test\\helloworld.cpp) will be provided by the Tag Parser.",
cannot open source file \"**asm/errno.h**\" (dependency of \"person.h\")
```

#### it can locate(ctrl+mouse click) that file correctly.

c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "WSL",
            "intelliSenseMode": "clang-x64",
            "compilerPath": "/usr/bin/c++",
            "includePath": [
                "/usr/include/c++/4.8",
                "/usr/include/c++/4.8/x86_64-suse-linux",
                "/usr/include/c++/4.8/backward",
                "/usr/lib64/gcc/x86_64-suse-linux/4.8/include",
                "/usr/local/include",
                "/usr/lib64/gcc/x86_64-suse-linux/4.8/include-fixed",
                "/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/include",
                "/usr/include"
            ],
            "defines": [],
            "browse": {
                "path": [
                    "/usr/include/c++/4.8",
                    "/usr/include/c++/4.8/x86_64-suse-linux",
                    "/usr/include/c++/4.8/backward",
                    "/usr/lib64/gcc/x86_64-suse-linux/4.8/include",
                    "/usr/local/include",
                    "/usr/lib64/gcc/x86_64-suse-linux/4.8/include-fixed",
                    "/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/include",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++11"
        }
    ],
    "version": 4
}

```
![helloworld](https://user-images.githubusercontent.com/5364806/44570618-0df4d800-a7b1-11e8-91df-5e24fce7ddb9.png)
![person](https://user-images.githubusercontent.com/5364806/44570625-13522280-a7b1-11e8-861a-76c9125fdce8.png)

**Comment by bobbrow** [comment]
Thanks for reporting this.  It appears to be the same issue as #2223.  In the `/usr/include` folder I see a symlink from asm -> asm-x86, but the extension is not following the link.  It seems this will block any usage of the std headers on this distro.  I'm surprised no one else has reported this yet.

Until we get a fix for this, you can turn off the tag parser fallback stuff by clicking on the lightbulb that appears when you select the squiggle and choosing "force semantic IntelliSense".

**Comment by lapcca** [comment]
Thanks for your reply.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity and a duplicate.
