### ISSUE TITLE
"Go to Declaration" option does not navigate to the namespace file.

### ISSUE THREAD

**Issue by ilgan** [microsoft/vscode-cpptools#2447]
Type: General
After updating the VS Code and the extensions (both manually, due to network restrictions), the "Go to definition" option disappeared. "Go to declaration" option doesn't work.

- Win 10:
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): ms-python.python

Uninstalled previous version of VS Code, installed a new User recommended version. opened same main folder that contains all teh work files. Cannot navigate from the sub-folder files to the namespace or files where the function was declared.

1. Hover above namespace::Function()
2. Right click on "Go to Declaration"
3. Nothing happens

**Expected behavior**
jump to the namespace where the function was declared.

**Screenshots**
cannot provide

**Additional context**
- the settings file intellisense is enables
- the extensions cannot be autoupdated, network restrictions
- all the updates were done manually (.vsix)
- tried to reinstall and clean the system, reinstalled, but got the same behavior

**Comment by bobbrow** [comment]
Are there any `Microsoft.VSCode.CPP.Extension.exe` processes running?  There is definitely something odd going on if "goto definition" isn't appearing in your context menu.

Is there any additional information you can share with us?  Are you able to simplify this down to a small folder without any proprietary IP that we can download?  This works fine for me on Windows.

You can also try [enabling logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and see if anything suspicious shows up in there.  I would recommend using the "Debug" setting

**Comment by ilgan** [comment]
*Issue is Resolved*

**Steps for the fix:**
1. Download extension file .vsix
2. Manually install the extension.
3. In pop up (bottom right corner) that asks to configure the extension, choose "Edit/Configure".
4. the cC_cpp_properties.json will be created.
5. Save and exit.

**NOTE:** my previous attempts to create c_cpp_properties.json with needed properties failed.

c_cpp_properties.json content:
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ]
        }
    ],
    "version": 4
}

**Comment by ilgan** [comment]
@bobbrow 
1. The logger did not show any information at all, thus I did not include it. Should have mentioned it.
2. The "can't find definition" message doesn't provide any information either.

I think the issue was that somehow c_cpp_properties.json hasn't been created on teh extension installation, as I tried to find it on my drive last week and couldn't.

**Comment by bobbrow** [comment]
So it's working for you now?  Feel free to close the issue if that's the case.  Based on what you've said, it seems that the extension may not have installed successfully which could explain why nothing was working.
