### ISSUE TITLE
some process for cpp extension are not under the child of vs code

### ISSUE THREAD

**Issue by graph** [microsoft/vscode-cpptools#2449]
Type: LanguageService
**----- Input information below -----**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Ubuntu 18
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1

![image](https://user-images.githubusercontent.com/1088059/44629549-0e12e600-a91f-11e8-977d-cff17c2dce93.png)

As you can see those process are not a child of vs code process.

**To Reproduce**

1. just run vs code and open some c++ files

**Expected behavior**
I expect everything related to vs code be a child process of the main vs code process. This may explain why sometimes when I exit vs code there is still some c++ extension code processes running. Which is another bug.

**Comment by bobbrow** [comment]
Those look like MIEngine processes from the debugger.  Changing the bug type...

**Comment by pieandcakes** [comment]
This isn't going to be something we can fix.
