### ISSUE TITLE
Red flame icon never going away, stdbool.h not found

### ISSUE THREAD

**Issue by pl-ca** [microsoft/vscode-cpptools#245]
I am facing some issues with the extension where some header files are not found.

For example, `stdbool.h` is never found, even though I have added its path to the configurations.
![stdbool](https://cloud.githubusercontent.com/assets/9813472/18751736/10a8e342-80ae-11e6-94c6-0252773588c0.png)

I verified where it was on my system:

``` bash
# ls -l /usr/include/c++/5/tr1/stdbool.h 
-rw-r--r-- 1 root root 1219 Aug  8 12:49 /usr/include/c++/5/tr1/stdbool.h
```

And made sure to add it to the configurations:

``` json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include/c++/5/tr1",
```

Furthermore, the red flame icon is never getting resolved in the bottom right, even after multiple days. I'm not sure if it is related or not but I thought I should mention it:
![flame](https://cloud.githubusercontent.com/assets/9813472/18751800/520e4ed0-80ae-11e6-948b-0e9a34dff191.png)

It is able to locate most of my own project header files and most system header files. I'm not sure what is the difference between all of them.

**Comment by pl-ca** [comment]
It seem that it actually ignores the changes I do to `c_cpp_properties.json` file completely. I realised that it is able to find all header files that are in my project folder and subfolders. However, any file that is outside of that base folder will not be found. Except the ones contained in `/usr/include` (I assume because by default the config file include this line already).

I also try to change `"databaseFilename"` config to put the database elsewhere, but it still continues building into `base_folder/.vscode/.browse.VC.db`

**Comment by pl-ca** [comment]
One more update: I could sort of make it work by putting symbolic link in my project base folder to external include directories and then adding those symlink to the the `c_cpp_properties.json` file. I also had to use `"limitSymbolsToIncludedHeaders" : false,`. Now I all my errors and the red flame are gone... but navigating to definition is very slow.

**Comment by bobbrow** [comment]
These issues should be fixed in the latest version of the extension.  Are you still seeing these issues?
