### ISSUE TITLE
Can't disable hover tip, it is annoying

### ISSUE THREAD

**Issue by bingozhu0197** [microsoft/vscode-cpptools#2451]
Type: LanguageService
**----- Input information below -----**
hover tooltips is annoying. It can't be disabled with:
   "editor.parameterHints": false,
    "editor.hover": false,
    "editor.quickSuggestions": false,
    "C_Cpp.intelliSenseEngine": "Tag Parser",
    "C_Cpp.PeekDeclaration": false

**Describe the bug**
- OS and Version: windows 7
- VS Code Version:  1.26.1
- C/C++ Extension Version:  0.18.1: A
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**Comment by bobbrow** [comment]
I believe `"editor.hover.enabled": false` is the setting you are looking for.

**Comment by bingozhu0197** [comment]
You are right. I missed with "editor.hover": false from old suggestions. Really thanks for your help!
