### ISSUE TITLE
Can't compile with "arpa/inet.h"

### ISSUE THREAD

**Issue by sprknd** [microsoft/vscode-cpptools#2457]
**Type: LanguageService**

C/C++

**Describe the bug**
- OS and Version: WIndows 10 Pro 17134.228
- VS Code Version: 1.25.1
- C/C++ Extension Version: 0.18.1
- A clear and concise description of what the bug is.

I have WSL using Ubuntu and followed [this](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md) guide to compile native UNIX codes. But can't compile it.

- In `arpa/inet.h` case, it located at `C:\Users\with4\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\arpa\inet.h`.
- `sys/socket.h` is in `C:\Users\with4\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu\sys\socket.h`. 

They both can locate by 'ctrl + left click' which means that intellisence notice these headers.
But gcc gave errors when compile it.
> fatal error: arpa/inet.h: No such file or directory  #include <arpa/inet.h>

c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "WSL",
            "includePath": [
                "${workspaceFolder}",
                "/usr/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

task.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "gcc",
            "args": [
                "${file}", "-g"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/12877916/44724309-48da7100-ab0d-11e8-8370-d6e91b1f9051.png)

![image](https://user-images.githubusercontent.com/12877916/44722734-f4cd8d80-ab08-11e8-94d9-87bf307d19ab.png)

**Comment by Berrysoft** [comment]
You are running g++ on Windows, but not WSL.

**Comment by sprknd** [comment]
@Berrysoft Thanks for pointing this out. I changed g++ to gcc on WSL but same result

**Comment by sprknd** [comment]
Solved: Conflicted with MinGW gcc.
