### ISSUE TITLE
dimInactiveRegions causes redraw issues

### ISSUE THREAD

**Issue by jovere** [microsoft/vscode-cpptools#2458]
Type: General
If `dimInactiveRegions` is enabled and a dimmed region is shown, redraw issues occur.  Screen flickers in random places and text or sections of screen disappear completely.

- OS and Version: 
`Linux buildPC 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 GNU/Linux`
- VS Code Version:
```
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:34:20.517Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
- C/C++ Extension Version: `0.18.1`

**Expected behavior**
Drawing normally

**Screenshots**
![2018-08-28-094042_1920x1056_scrot](https://user-images.githubusercontent.com/10420943/44731742-7e4d7300-aaa9-11e8-9a60-1629ba954b08.png)
![2018-08-28-094110_1920x1056_scrot](https://user-images.githubusercontent.com/10420943/44731710-7097ed80-aaa9-11e8-94b3-d505dfec3e65.png)

**Comment by bobbrow** [comment]
I've never seen anything like that before.  I think you should open an issue in the [vscode repo](https://github.com/Microsoft/vscode/issues/new/choose).  This extension doesn't have control of any of the rendering/UI code.
