### ISSUE TITLE
IntelliSense does not recognize changed size_t definiton

### ISSUE THREAD

**Issue by RicBent** [microsoft/vscode-cpptools#2460]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux (Manjaro 17.1.12 Hakoila)
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): None
- Description: IntelliSense does not recognize changed size_t definiton.

I am developing bare metal code for an ARM system with the arm-none-eabi compiler and linker and am using following c_cpp_properties: https://gist.github.com/kbumsik/52ce3f41a62f2485c3da1a585674e550#file-c_cpp_properties_my_example-json
It includes proper defines for size_t and has valid include paths to header files which define size_t.
For all "operator new" functions IntelliSense flags them as errors with "first parameter of allocation function must be of 'size_t'".

size_t type: unsigned int
Example of flagged operator new function: void* operator new(size_t size);

**Comment by bobbrow** [comment]
It is likely a size mismatch since the IntelliSense modes we currently support are all 64-bit.  The defines I see in that configuration appear to be 32-bit.

As an aside, I don't think you need to list out all of the includes and defines since the `compilerPath` is being set.  This gist may have been authored before we supported compiler arguments in the `compilerPath` setting.

**Comment by RicBent** [comment]
Yeah, size_t is defined as an unsigned int which is 32-bit on my target platform.
Is there a way to disable that IntelliSense error? It renders VSC pretty much useless for my project when it flags almost every file for these errors.

**Comment by sean-mcmanus** [comment]
We have work in progress that exposes the error codes, which could be added to an ignore list setting, but we don't have an ETA on when the work will be completed -- see https://github.com/Microsoft/vscode-cpptools/issues/2345 .

**Comment by RicBent** [comment]
Thanks.
For now I just tell VSC to include a non-project file that has a different definition for size_t :)

**Comment by zhang456xi** [comment]
But the errors still exists for a GCC item.
![image](https://user-images.githubusercontent.com/24366039/67652483-167e0b00-f980-11e9-8e5b-76a2ae039c7f.png)
namespace std
{
  typedef long unsigned int size_t;
  typedef long int ptrdiff_t;
  typedef decltype(nullptr) nullptr_t;
} 
defined by /usr/include/x86_64-linux-gnu/c++/7/bits/c++config.h

**Comment by sean-mcmanus** [comment]
@zhang456xi I'm not able to repro the issue (your headers might be different)? I see a global size_t defined at `/7/include/stddef.h`. Are you using Go to Def on size_t?

**Comment by zhang456xi** [comment]
![image](https://user-images.githubusercontent.com/24366039/67726183-fe5dc880-fa1f-11e9-8844-08247807641f.png)
Go to Def shows 'size_t' defined in `/usr/lib/gcc/x86_64-linux-gun/7/include/stddef.h` in line 216 'typedef \_\_SIZE_TYPE\_\_ size_t', and '\_\_SIZE_TYPE\_\_' defined in line 213 '#define \_\_SIZE_TYPE\_\_ long unsigned int'.   
Log Diagnostics shows item have included path:  '/usr/lib/gcc/x86_64-linux-gnu/7/include'.  
And the result generated by 'gcc demo.cpp -E' indicate that 'typedef long unsigned int size_t;'
defined in '# 216 "/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h"'  
But IntelliSense can work correctly that reopen folder in WSL.  

- C/C++ Extension Version: 0.26.1
- VS Code Version: 1.39.2
- OS: Windows_NT x64 10.0.18362 and Linux version 4.4.0-18362-Microsoft (WSL)
- gcc version:7.4.0 installed by WSL and 6.3.0 installed by MinGW in windows.

**Comment by sean-mcmanus** [comment]
Okay, I repro it now -- I was hitting the VS Code Insiders bug that was breaking error squiggles: https://github.com/microsoft/vscode-cpptools/issues/4505 .

**Comment by zhang456xi** [comment]
Thanks

**Comment by sean-mcmanus** [comment]
I've filed a VS bug at https://developercommunity.visualstudio.com/content/problem/797098/cc-intellisense-with-gccclang-mode-reports-incorre.html .

The original issue was from a year ago -- not sure if this is the same issue or a recent regression.

**Comment by sean-mcmanus** [comment]
We figured out the cause and a workaround of adding -m32 to the compilerArgs (or to the end of compilerPath) for gcc-x86 mode or adding -m64 for gcc-x64.

The bug with VS is somewhat unrelated because they implement it differently.
