### ISSUE TITLE
There is no way to specify "everything except" in files.exclude settings

### ISSUE THREAD

**Issue by fredijude** [microsoft/vscode-cpptools#2461]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- In the workspace setting, Files.exclude doesn't allow any way of specifying for the requirement of "exclude everything except the files with this".

**Comment by sean-mcmanus** [comment]
This is being tracked by VS Code itself with issue https://github.com/Microsoft/vscode/issues/869 . You could upvote or add comments to that issue.
