### ISSUE TITLE
Debugger broken because of Chinese characters in file name.

### ISSUE THREAD

**Issue by n-p-e** [microsoft/vscode-cpptools#2462]
Type: Debugger

- OS and Version: Windows 10 1803
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions: Clang-Format, Code Runner, and a few themes. Disabled them and the issue persisted

- Bug: When debugging the debugger notice "Can't open file". Chinese characters in the file name become meaningless numbers.
example:
"test 测试.cpp" (original) / “test 262342312324.cpp” (after)

- Full error message:
``` 
无法打开“test 262342312324.cpp”: 找不到文件(file:///c:/Users/me/Documents/C++ Code/test 262342312324.cpp)。
```
- Translation: can't open "test ..... .cpp": file not found (.../test .... .cpp)

**To Reproduce**
Steps to reproduce the behavior: (Related files below)
1. Create a file and name it in Chinese, or any other symbols, and add a breakpoint.
2. Hit F5 to start debugging. 
3. Error message appears.

- launch.json
```
 {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "G++",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
            ],
            "preLaunchTask": "Compile",
            "logging": {
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            }
        }
    ]
}
```
- tasks.json
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Compile",
            "command": "g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}.exe",
                "-std=c++11",
                "-finput-charset=utf-8",
                "-fexec-charset=gbk"
            ],
            "problemMatcher": "$gcc",
        },
    ]
}
```

**Comment by n-p-e** [comment]
I got no idea about which part of the debugger threw this error message. It seems that g++ and gdb are working normally, but VSCode can't control them because the extension got a wrong file name, which has numbers instead of Chinese Characters.

**Comment by pieandcakes** [comment]
@coffee-sgr The problem is in `gdb` when driven in MI mode. It doesn't seem to understand characterization correctly. If you enable [logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging), you can see our communication with gdb and its response. It is responding with the incorrect filenames, which is how we get them. 

This is a duplicate of #602.
