### ISSUE TITLE
Comment ; ctrl+ mouse Cursor pointing Comment display location?

### ISSUE THREAD

**Issue by q962** [microsoft/vscode-cpptools#2463]
**Type: LanguageService**

ming64

**Describe the doubt**
- OS and Version: win10
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them):  vscode-cpptools Exclusive function
- I don't know if `ctrl + cursor points` is used to display comments.
For now, I think it is, Or a small piece of content after the statement or implementation is displayed.
I want to display comments.
😱😱😱

**Comment by q962** [comment]
For the statement, the comment can be displayed normally below, but just now, it has become how many definitions are displayed.

![image](https://user-images.githubusercontent.com/15686075/44795709-f2893300-abdd-11e8-929d-cdc32614d8b0.png)

**Comment by bobbrow** [comment]
We don't display comments yet.  It's on our backlog.  #399

**Comment by q962** [comment]
🆗

**Comment by michelleangela** [comment]
Closing as duplicate.
