### ISSUE TITLE
Add a way to import include paths and flags from conan's ycm file

### ISSUE THREAD

**Issue by blastrock** [microsoft/vscode-cpptools#2464]
**Type: LanguageService**

**Describe the feature**

I use [the conan package manager](https://conan.io/) in my c++ projects. Conan compiles project dependencies and generates cmake scripts to use them in your project.

Conan has another generator which is called "ycm" (referring to vim's plugin YouCompleteMe). This generator generates a json file that looks like:

```json
{
  "includes": [
    "-isystem/home/user/.conan/data/first_package/include",
    "-isystem/home/user/.conan/data/second_package/include"
  ],
  "defines": [
    "-DFIRST_PACKAGE_USE_FOO=1"
  ],
  "flags": []
}
```

This file is usually read by YouCompleteMe to know the compilation flags and be able to invoke clang.

I would like to be able to import these flags from the `c_cpp_properties.json` file, like this for example:

```json
{
    "configurations": [
        {
            "name": "Linux",
            "importConfig": "${workspaceFolder}/build/conan_ycm_flags.json"
        }
    ]
}
```

As you can see though, the format of this conan file is a little different from the usual `c_cpp_properties` as there is that `-isystem` on each line. I see the following options:

- Have vscode-cpptools parse that format
- Try to upstream a patch to conan to not include that "-isystem" part
- Define a vscode-cpptools custom format and convert that json file to the vscode format, or upstream a patch to conan to have it generate that custom format

**Comment by user4223** [comment]
I would really like to have support for this, conan is great step to make real world c++ projects portable and to solve the library dependency hell. Unfortunately, vscode-cpptools are currently unable to resolve the includes properly when conan is used, it would be great when it would do!
