### ISSUE TITLE
Hide same text completion items

### ISSUE THREAD

**Issue by agauniyal** [microsoft/vscode-cpptools#247]
If I've 10 vars named `temp` in 10 different files opened up in vscode, the next time I start typing `te..` it'll show all of them in the dropdown and hide the other relevant ones.

**Comment by bobbrow** [comment]
Are they all global variables?  Variables defined in a function scope should not be added to the database.  Do you have C_Cpp.autocomplete Disabled in your settings file?  That would let VS Code take over and provide the suggestions instead of letting our extension do it.

**Comment by agauniyal** [comment]
> Do you have C_Cpp.autocomplete Disabled in your settings file?

Yes I've done it because right now I'm using separate autocompletion plugin which is context aware so I don't want this plugin to override the autocompletion.

**Comment by bobbrow** [comment]
Removing duplicates from the suggestion list was fixed in version 0.12.0.  We only show each symbol once now, however local variables still do not appear in the list.
