### ISSUE TITLE
Structured bindings in for-loop with map/unordered_map.

### ISSUE THREAD

**Issue by regexus** [microsoft/vscode-cpptools#2472]
Hello guys, 

I have noticed some incompatibilities with the C++17 standard for structured bindings in for-loop with maps and unordered maps.

The following code compiles and runs just fine, but generates IntelliSense errors:

```
void for_loop_with_structured_bindings()
{
    std::unordered_map<int, int> map = {{1, 2}, {3, 4}, {5, 6}};
    for (auto [key, value] : map)
    {
        std::cout << "key : " << key << ", value : " <<  value << std::endl;
    }
}
```

Currently it looks like that:
![screenshot_000052_vs_code_structured_bindings](https://user-images.githubusercontent.com/25210091/44924810-c809b800-ad4c-11e8-879b-5968f809f118.png)

I also tried auto& [key, value] instead of auto [key, value], but the errors remain.

Here are the infos about my OS and VS Code versions:
- OS and Version: Windows 7
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1

P.S. My VS Code settings contain the "C_Cpp.default.cppStandard": "c++17" line.

Best regards, 
AK.

**Comment by bobbrow** [comment]
Can you share your configuration?  I'm not seeing the same error as you.  It works fine for me with `"intelliSenseMode": "msvc-x64"` on Windows 10 + VS 15.9 preview + latest Windows SDK installed:

![image](https://user-images.githubusercontent.com/12818240/44928416-aee11700-ad0c-11e8-9144-74e7fe0ed794.png)

I get a different error when using MinGW/WSL with clang/gcc mode (this looks like a bug):

![image](https://user-images.githubusercontent.com/12818240/44928556-0b443680-ad0d-11e8-8458-bb5bf02dcfe4.png)

**Comment by bobbrow** [comment]
I was able to reproduce the error if I set the cppStandard to c++14.  Do you happen to have a `c_cpp_properties.json` file in your .vscode folder that is overriding your `C_Cpp.default.cppStandard` setting?

![image](https://user-images.githubusercontent.com/12818240/44928975-39764600-ad0e-11e8-8b54-99c94a8e094d.png)

**Comment by regexus** [comment]
Hello Bob, 

thank you for the quick response and you are right! The c_cpp_properties.json was overriding my C_Cpp.default.cppStandard setting to C++11. I have started the project as C++11, switched later to C++17 and simply forgot about the c_cpp_properties.json file. 

It would be probably not bad, if the extension would show a notification that there is a conflict in settings and that c_cpp_properties.json will win. But this issue can be definitely closed. Thank you very much for your help!

Best regards, 
AK
