### ISSUE TITLE
[cppvsdbg] Debug visualizers (natvis) cannot be customized or modified

### ISSUE THREAD

**Issue by jcageman** [microsoft/vscode-cpptools#2476]
Type: Debugger
- OS and Version: Windows 10 1803
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1

I am trying to use a custom .natvis file for my rust project using cpptools.
I have the following added to the launch.json according to the [documentation](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md)

```
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/target/debug/calendar-14bc38fac2db352e.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "visualizerFile": "${workspaceRoot}/calendar.natvis",
            "showDisplayString": true
        }
```
showDisplayString shows as a not allowed property, although it should be supported according to the above documentation. If i look at package.json in my installation it seems that specifically for cppvsdbg the showDisplayString is not supported, which at least conflicts with the documentation. Further testing also seems to indicated it is true by default for cppvsdbg.

I first tried overruling the default rust visualizers for cpptools, but apparently those are now baked into the dbg's rust is providing.
See:
https://github.com/rust-lang/rust/pull/43221/files

Hence, those can't be modified, but i am succeeding modifying non-supplied types in my own .natvis

**Comment by ngugcx** [comment]
Is there any update? showDisplayString(cpptools 0.27.0-insiders3) is still not working with cppvsdbg.

**Comment by ngugcx** [comment]
- Type: Debugger
- OS and Version: Windows 10
- VS Code Version: 1.43.2
- C/C++ Extension Version: 0.27.0-insider4

I am trying to debug a Qt app with the following configuration, but the visualizer just doesn't work with QString. 
- "showDisplayString" is not allowed.
![image](https://user-images.githubusercontent.com/44153489/77488767-1cb1de00-6e71-11ea-9c45-efa085ec1097.png)
- When debugging, QString variables are not shown as readable strings.
![image](https://user-images.githubusercontent.com/44153489/77488880-74e8e000-6e71-11ea-81d2-49ce0db0f292.png)

launch.json
```
        {
            "name": "Debug",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/debug/myapp.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [{"name":"PATH", "value":"D:/Qt-bin/5.6.3-xp-x/bin"}],
            "externalConsole": false,
            "visualizerFile": "D:/appx/qt5.natvis",
            "showDisplayString": true
        },
```
qt5.natvis
```
<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer >

<Type Name="QString">
 <DisplayString>{(char*)d + d->offset,su}</DisplayString>
 </Type>

<Type Name="QtPrivate::RefCount">
 <DisplayString>{atomic}</DisplayString>
 </Type>

<Type Name="QBasicAtomicInteger<int>">
 <DisplayString>{_q_value}</DisplayString>
 </Type>

<Type Name="QTypedArrayData<'''>">
 <DisplayString>{{Count = {size}}}</DisplayString>
 <Expand>
 <Item Name="[size]">size</Item>
 <ArrayItems>
 <Size>size</Size>
 <ValuePointer>(iterator) ((char''')this + offset)</ValuePointer>
 </ArrayItems>
 </Expand>
 </Type>

<Type Name="QByteArray">
 <DisplayString>{*d}</DisplayString>
 </Type>

<!— More Qt5 types… —>

</AutoVisualizer>
```

**Comment by ngugcx** [comment]
Or should I open a new issue for this?
If you need more infos, let me know.

**Comment by tonka3000** [comment]
Hey @ngugcx ,

do you know these natvis file from Qt itself https://code.qt.io/cgit/qt-labs/vstools.git/plain/src/qtvstools/qt5.natvis.xml , just remove `##NAMESPACE##::` from the file after download (if it does not work, just remove `##NAMESPACE##` and let the `::` exist, in older versions of VSCode that worked for me too). This should work.

If you don't want to do all that manually, just use my VSCode extension [Qt tools](https://marketplace.visualstudio.com/items?itemName=tonka3000.qtvsctools) which do all of  that automatically (but only when you use cmake).

Hope that help you.

Greetings  
Tonka

**Comment by ngugcx** [comment]
@tonka3000 , you saved lots of my time. Thank you very much!
I didn't expect it was an error of the natvis file, it was copied from https://wiki.qt.io/IDE_Debug_Helpers.

**Comment by tonka3000** [comment]
@ngugcx , if you create a Qt natvis file, maybe you like to make a PR on https://github.com/tonka3000/vscode-qt-tools/blob/develop/res/qt.natvis.xml and you can use the file as a template for your file as well (it's an MIT license) . Because the Qt Visual Studio tools natvis file is under GPLv3 and my extension is MIT which don't match. So when you like to contribute to my repo, you are absolutely welcome.

**Comment by lygstate** [comment]
Use this one better:
https://github.com/aleksey-nikolaev/natvis-collection/blob/master/qt5.natvis

**Comment by Universal-Invariant** [comment]
I'm having this issue too and can't get natvis to work with rust and cppvsdbg. 

> [@tonka3000](https://github.com/tonka3000) , you saved lots of my time. Thank you very much! I didn't expect it was an error of the natvis file, it was copied from https://wiki.qt.io/IDE_Debug_Helpers.

Are you saying that the showDisplayString variable is irrelevant and the issue is how the natvis file is specified? The link [tonka3000] posted is not valid so I have no idea.

The PDB definitely seems to have the natvis embedded in it but I can't get the debugger to use it. I'm using:

```
<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
  <Type Name="*">
    <DisplayString>*** NATVIS IS WORKING! ***</DisplayString>
  </Type>
</AutoVisualizer>
```

for simplicity but it doesn't work. I've tried messing around with paths and nothing. I don't think even the intrinsic.natvis is being loaded.
