### ISSUE TITLE
Outline view can't find symbols in already opened file on startup or workspace switch

### ISSUE THREAD

**Issue by pewscorner** [microsoft/vscode-cpptools#2477]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): Persists with all other extensions disabled.
- A clear and concise description of what the bug is.
When switching to - or starting VSCode with - a workspace where the file currently displayed in the editor window is a .c/.cpp file, the outline view for that file often fails to show any symbols, and reports: "No symbols found in document". There are no problems when switching to other opened .c/.cpp files in the same workspace, and if the failing file is closed and reopened, it too works fine. It appears that the extension fails to provide outline info for any file that is already loaded in the editor window on VSCode startup or after a workspace switch.

**To Reproduce**

1. Open a folder in VSCode and open a .c/.cpp file from that folder. Check that the outline view shows the file's symbols.
2. Close and restart VSCode (or switch to another folder/workspace and back). The previously opened .c/.cpp file should now be visible again in the editor window.
3. If the error has occurred, the outline view will be empty except for the message: "No symbols found in document ...". If not, repeat step 2 above.

**Expected behavior**

The outline view should always show the file's symbols.

**Screenshots**

Correct behavior:
![good](https://user-images.githubusercontent.com/15351477/44945434-ccd07980-ade9-11e8-9973-72de48b2b6f4.png)

Incorrect behavior:
![bad](https://user-images.githubusercontent.com/15351477/44945447-f38eb000-ade9-11e8-8fc4-d81fa27b35a4.png)

**Additional context**

None.

**Comment by bobbrow** [comment]
I have an idea of what this might be.  VS Code only queries us once and if it does it before the database has been initialized, we return no results.  The behavior was added long before outline view existed. There's no way for us to distinguish between a request for outline view versus a standard document symbol request (which can be discarded in hopes that another one will come in).

**Comment by pewscorner** [comment]
I never see the issue for python and javascript files (and the breadcrumb display works fine in those files too, whereas it often fails in c/cpp files even when the symbols are available).

The ms-python.python extension somehow manages to populate the outline view correctly, even though it takes a long time to gather the symbol info. Before the symbol info is available, the outline view displays the message: "Loading document symbols for ..." - see screenshot. Several seconds later, the symbols appear in the outline view.

![capture](https://user-images.githubusercontent.com/15351477/45253320-9e144f00-b365-11e8-988c-a5b5c869c0ff.PNG)

**Comment by bobbrow** [comment]
Each language extension implements this differently.  If you close and reopen the c file, do you get an Outline on the second try?  If you don't then my hypothesis is incorrect.

**Comment by sean-mcmanus** [comment]
I believe I have I've already fixed this on Friday while investigating https://github.com/Microsoft/vscode-cpptools/issues/2500 . We weren't waiting till accurate results were available before returning document symbol results. However, I'm not able to repro the original issue with 0.18.1 (and VS Cod Insiders), so maybe something else is happening (I assume the browse database isn't ready...I assume the particular machine is slower in initializing the database). When we release the next Insiders we can get confirmation whether this is actually fixed or not.

**Comment by sean-mcmanus** [comment]
This bug isn't fixed -- if a file is open on workspace load it won't have symbols until an edit, close/open, etc. occurs. The problem is that VS Code requires us to send back a document symbol result or it "stop working" and we're not ready to send the symbol info yet.

**Comment by pewscorner** [comment]
@sean-mcmanus and @bobbrow, you seem to be implying that this is a VS Code problem because it doesn't allow the extension enough time to provide the symbols. But, as I wrote earlier, other language extensions don't seem to have this problem, and seem to be able to tell VS Code to wait until the symbols are ready. So this option must somehow already be available in the API, I would think.

**Comment by sean-mcmanus** [comment]
@pewscorner Yeah, it looks like it's a bug with our task queuing system, because when using the "fixed" code for this, the documentSymbol request is randomly blocking the event that is needed to give correct document symbols. Bob is investigating a fix -- not sure if it will make the September release or not.

**Comment by sean-mcmanus** [comment]
Bob's change at https://github.com/Microsoft/vscode-cpptools/pull/2553 fixed the blocking issue, so our next release should have this fix.

**Comment by sean-mcmanus** [comment]
The Outline view not finding symbols for open files after workspace loading has been fixed with 0.19.0.

**Comment by pewscorner** [comment]
Yes, it works for me too. Big thanks!
