### ISSUE TITLE
when editing cpp files with nested #if directives, screen becomes zig zag jig jag

### ISSUE THREAD

**Issue by showching** [microsoft/vscode-cpptools#2481]
**Type: LanguageService**

**Describe the bug**
- OS and Version: CentOS 7.5
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): GBKtoUTF8, Git History, gitignore, Python
- A clear and concise description of what the bug is.
When editing cpp files with nested #if directives, screen becomes zig zag jig jag. 
**To Reproduce**

1. Maximize VS Code window (optional, but helps to reproduce)
2. Use the sample code below
3. Seems the issue does not exist before VS Code 1.26

An example cpp file to reproduce this issue is:

#include <iostream>

int main(int argc, char* argv[])
{
#if VERBOSE
  std::cout << "Whatever"
      << ", ErrorID=" << pRspInfo->ErrorID << ", ErrorMsg=" << pRspInfo->ErrorMsg
      << ", Good=" << pAnGreatObject->Good << ", Description=" << pAnGreatObject->Description 
      << ", Name=" << pAnGreatObject->Name << ", ActionFlag=" << pAnGreatObject->ActionFlag
      << ", ActionDate=" << pAnGreatObject->ActionDate << ", ActionTime=" << pAnGreatObject->ActionTime
      << ", UserID=" << pAnGreatObject->UserID
      << std::endl;
#if CDE
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
#elif EFG
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
#else
  std::cout << "Whatever"
      << ", ErrorID=" << pRspInfo->ErrorID << ", ErrorMsg=" << pRspInfo->ErrorMsg
      << ", Good=" << pAnGreatObject->Good << ", Description=" << pAnGreatObject->Description 
      << ", Name=" << pAnGreatObject->Name << ", ActionFlag=" << pAnGreatObject->ActionFlag
      << ", ActionDate=" << pAnGreatObject->ActionDate << ", ActionTime=" << pAnGreatObject->ActionTime
      << ", UserID=" << pAnGreatObject->UserID
      << std::endl;
#endif
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;

#else
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
  std::cout << "this is a line" << std::endl;
#endif
}

**Expected behavior**

**Screenshots**

![vscode-bug](https://user-images.githubusercontent.com/11239092/45029586-c0fbe600-b07b-11e8-9458-31313eed4471.png)

**Additional context**

**Comment by bobbrow** [comment]
Our extension isn't in control of any of the editor's rendering.  Can you open an issue in the [VSCode repository](https://github.com/Microsoft/vscode/issues/new/choose)?

**Comment by showching** [comment]
But the issue appears when the extension is enabled and disappear when it is disabled. Maybe it's the VSCode issue, but I'm afraid they would say it's an extension issue, because I works without the extension. So, could you please troubleshoot first, and confirm it's a VSCode issue? Thanks!

**Comment by sean-mcmanus** [comment]
That's okay if the issue only repros with our extension -- the repro appears to require our extension's usage of the transparent rendering for inactive text blocks -- there is virtually no way our extension could be the cause of the bug still because we implement none of the rendering -- we just tag the text as being non-opaque, which works in general except for when VS Code has this bug.

**Comment by showching** [comment]
Just reported it to VS Code, hope they will take the issue and resolve it. Thanks!

**Comment by michelleangela** [comment]
Closing this issue as the cause is external.
