### ISSUE TITLE
Intellisense marks up code with errors when the code compiles without error

### ISSUE THREAD

**Issue by rtosman** [microsoft/vscode-cpptools#2482]
**Type: LanguageService**

**Describe the bug**
- OS and Version:  Windows 10
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): N/A
- A clear and concise description of what the bug is.

Intellisense reports a scoping error with a lambda that doesn't actually exist. In fact, msvc fails to compile the code, however, clang and gcc compile the code without error.  Here is a link to a simplified example that causes the error. You will note that it compiles with clang 6.0 and trunk as well as gcc 8.2 and trunk.

Here is the compiler explorer link: https://godbolt.org/z/WSYEeK

**To Reproduce**

{
    "configurations": [
        {
            "name": "Windows",
            "includePath": [
                "${workspaceFolder}/**",
                "c:/SFML-2.5.0/include"
            ],
            "defines": [],
            "compilerPath": "c:/Program Files/bin/clang++",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

**Expected behavior**

I expect there to be no errors reported by intellisense since the source compiles correctly on all compilers except msvc.

**Screenshots**
Reported errors (erroneous):

![image](https://user-images.githubusercontent.com/6283239/45056464-d525f000-b047-11e8-9c2c-bf4912ea941b.png)

**Additional context**
N/A

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. We currently force the "clang-x64" mode to be "msvc-x64" mode (required to parse the Windows headers) leading to https://developercommunity.visualstudio.com/content/problem/327884/c-compiler-fails-to-compile-lambda-that-captures-a.html , but it seems like we need to use some additional flags to differentiate the "clang on Windows" scenario for when clang.exe behavior is different from cl.exe.

**Comment by sean-mcmanus** [comment]
Is your compilerPath supposed to use clang++.exe (with the .exe). It looks like it may be falling back to another default compiler. You can check what compiler is being used via setting the C_Cpp.loggingLevel to "Debug" and viewing the C/C++ output window after opening a new file.

I'm getting a crash when c++17 is used, but I repro the "undefined" issue when c++14 is used.

**Comment by rtosman** [comment]
@sean-mcmanus It seems to be working ok (perhaps it is finding the compiler on the system PATH?)

Here is the output with C_Cpp.loggingLevel set to "Debug"

textDocument/documentSymbol
sending compilation args for {path redacted for privacy}/FRAME.CPP
  include: C:\SFML-2.5.0\INCLUDE
  include: C:\PROGRAM FILES\LLVM\LIB\CLANG\8.0.0\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\VC\TOOLS\MSVC\14.11.25503\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.16299.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.16299.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.16299.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.16299.0\WINRT
  define: __llvm__=1
  define: __clang__=1
  define: __clang_major__=8
  define: __clang_minor__=0
  define: __clang_patchlevel__=0
  define: __clang_version__="8.0.0 (trunk)"
 ---- bajillions of defines output here, redacted for brevity 
 stdver: --ms_c++latest
  intelliSenseMode: msvc  <<<<< THIS IS VERY INTERESTING!!!!
queue_update_intellisense for files in tu of: C:\xxx\xxxxxx\xxxxxx\xxxxx\xxxxx\FRAME.CPP
errorSquiggles count: 6

**Comment by sean-mcmanus** [comment]
If it's not crashing for you, it might be because I'm using newer 15.9 VC++ headers or my clang version is different (6.0).

Yeah, the use of "msvc" mode is intentional; otherwise, the VC++ headers fail to get parsed. It looks like our parser doesn't emulate the "clang on Windows" scenario well (a major amount of work).

The most likely fix will be when cl.exe fixes the bug and then our IntelliSense parser updates (still in msvc mode though).

**Comment by rtosman** [comment]
Yeah, it seems like you probably need a "clang with -fms-compatibility -fms-extensions" mode.

**Comment by sean-mcmanus** [comment]
We use -fms-extensions for MinGW on Windows and that works, but clang + -fms-extensions (haven't tried -fms-compatibility yet) still isn't parsing the VC++ headers -- we might need to dig further into why.

**Comment by rtosman** [comment]
I've never been able to compile windows code without both switches.

**Comment by Colengms** [comment]
I believe the main issue here has been addressed for some time, but 1.6.0 appears to have a regression in which we fail to auto-detect -fms-compatibility properly. That should be fixed also, in the next insiders release.
