### ISSUE TITLE
Intellisense errors are associated with case-insensitive files on Windows

### ISSUE THREAD

**Issue by jeremyong** [microsoft/vscode-cpptools#2483]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 17134.228
- VS Code Version: 1.26.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Errors and warnings reported after a C++ compilation are associated with case-insensitive files such that clicking on them result in a "File not found" error.

**To Reproduce**

1. Compile any project with a compilation error and files with uppercase and lowercase letters
2. Click on the compilation error in the "PROBLEMS" tab
3. See Error

**Expected behavior**
It should navigate you to the file and line where the error exists

**Comment by bobbrow** [comment]
Did you create a case-sensitive folder on Windows?  We don't currently support those unless you are also referencing a WSL compiler in your c_cpp_properties.json configurations.

**Comment by jeremyong** [comment]
No I'm not using that feature at all and I am using the MSVC compiler. Clicking all errors and warnings result in the same "File not found" issue with an all-lowercase path (which is otherwise correct) and I'm forced to navigate manually for each error making the editor somewhat unusable.

**Comment by bobbrow** [comment]
Does the output in the terminal show all lower-case file names?  That would mean that your build system is changing the filenames to lower-case.

What build system and problem matcher are you using?  Can you share the relevant task from your `tasks.json`?  Have you verified that the path is actually correct?  Sometimes build systems will return a relative path from the wrong root folder and VS Code will try to reconstruct an absolute path (based on the problem matcher you choose).

**Comment by michelleangela** [comment]
Closing this issue. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate your issue.
