### ISSUE TITLE
search symbol using the pattern of "Class::Function" is not working

### ISSUE THREAD

**Issue by fredijude** [microsoft/vscode-cpptools#2484]
Type: Symbol Search Across Files
I am working on a c++ code base. i want to search the member function of a specific class using go to a symbol in workspace/file by inputting "#Class::FunctionA". This doesn't work as expected. It's not able to filter and give the result.

OS and Version: Windows 10
VS Code Version: 1.25.1
C/C++ Extension Version: 0.18.1

**Comment by bobbrow** [comment]
Are you seeing multiple symbols for FunctionA attached to other types?  If so, then this is a duplicate of #255 which we are working on right now.

**Comment by sean-mcmanus** [comment]
@bobbrow My Go to Def work shouldn't alter the symbol search behavior. The `#Class::FunctionA` syntax isn't even supported in the VS 2017 "Go to Symbol".

**Comment by fredijude** [comment]
@sean-mcmanus : To my knowledger and verification, In VS 2017 "Go to Symbol" supports search by the symbol in the format of #class::FuncationA.

**Comment by sean-mcmanus** [comment]
Okay -- yeah, I'm not sure why I thought it didn't work in VS.

**Comment by fredijude** [comment]
@sean-mcmanus : Will this be picked up and solved by anyone ASAP ? It would really help our organization to move into vs code itself instead of visual studio ide.

**Comment by sean-mcmanus** [comment]
It's been implemented. It should be in a "future" release, unless it gets cut for some reason.

**Comment by fredijude** [comment]
@sean-mcmanus : Your quick response and initiation are always appreciated. Thanks :)

**Comment by sean-mcmanus** [comment]
Should be fixed with the latest insiders: https://github.com/Microsoft/vscode-cpptools/releases .
