### ISSUE TITLE
Custom launch configuration provider

### ISSUE THREAD

**Issue by chkp-roic** [microsoft/vscode-cpptools#2486]
Type: Debugger
Is there a feature allowing me to add a custom launch configuration provider like the one used for includePath, defines and so on?
Does the debugger looks for symbol in the project browse.path?

This feature would be really useful for me, if it doesn't exist, does it somewhere on the roadmap?

**Comment by pieandcakes** [comment]
@roicpp The debugger does the searching based on what you set `cwd` to. If you want to specify additional paths, you can add `additionalSOLibSearchPath` to your `launch.json` to tell `gdb` or `lldb` where to find the additional symbols, or use `symbolSearchPath` for the Windows C++ debugger.

**Comment by pieandcakes** [comment]
On the first question about the provider, I don't understand what you are looking for. Our code is in this repository under the `Extension` folder if you want to look through it. We welcome contributions by the community.

**Comment by bobbrow** [comment]
@roicpp is looking for integration with a build system extension to provide the symbol paths without requiring additional configuration in `launch.json`.  The language server does this for `c_cpp_properties.json` with our exported API. https://www.npmjs.com/package/vscode-cpptools.

**Comment by chkp-roic** [comment]
True @bobbrow , thanks for the clarification.
@pieandcakes , regarding my first question, I've already checked the source and could not find anything. Basically I want my extension to provide launch configurations on the fly, similar to vscode registerTaskProvider or cpptools CustomConfigurationProvider.

**Comment by pieandcakes** [comment]
If its for `launch.json` it should be the same as the Custom Configuration Provider but you would have to still "choose" it.

**Comment by chkp-roic** [comment]
I don't think I completely understood you. The user should choose the desired "launch task" or launch.json. I want my extension to be responsible for supplying those different launch configuration on the fly without first defining a launch.json file.

**Comment by bobbrow** [comment]
oh, are you the extension author @roicpp?  If you are writing the extension, I thought VSCode exported an interface that would let you do this:

**vscode.d.ts**
```
export interface DebugConfigurationProvider {
...
}
```

Or is this just to aid in creating json entries in launch.json?  @pieandcakes would have more experience with this than I would.

**Comment by pieandcakes** [comment]
Yea, that's the interface you have to provide. We do it [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/Debugger/extension.ts#L32) which calls into our `configurationProvider.ts` code. What that will do is provide additional entries in the drop down for configurations when there is no `launch.json`. 

If you are looking for configurations for the `Add Configuration` button in `launch.json`, that is registered [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/Debugger/extension.ts#L32) as a `CompletionItemProvider`.

**Comment by chkp-roic** [comment]
Thanks for the info guys!
I believe most of my code will be similar to yours(gdb/gdbserver...), except stuff like symbol fetching and 1st transferring gdbserver to the target machine. 
I hoped code duplication could be avoided, but I guess interacting directly with vscode APIs will give me the greatest flexibility.
