### ISSUE TITLE
Can not display cascade

### ISSUE THREAD

**Issue by ZCShou** [microsoft/vscode-cpptools#249]
Using 0.9.2
When i write code in the process, sometimes Can not display cascade.

after I  saved  file , cascade display again!

this issue is not always exsit ！

![2016-09-23_165236](https://cloud.githubusercontent.com/assets/8591065/18780089/829e957c-81ae-11e6-8a6f-56483f4c31b0.png)

**Comment by sean-mcmanus** [comment]
Hovering the mouse to the left of the brace should cause the foldering/outline node to appear. Does the bug happen without our extension or with the previous version? I can't repro the bug. As far as I know, our extension should not affect the folding scenario.

**Comment by ZCShou** [comment]
![2](https://cloud.githubusercontent.com/assets/8591065/18977126/458a5fc2-86ea-11e6-8b2e-3b7110a32050.gif)

**Comment by sean-mcmanus** [comment]
Our C++ extension does not provide the outlining/folding feature. I believe it's a bug in VS Code itself. You appear to be using a pre-release version of VS Code.

**Comment by bobbrow** [comment]
Do you still have this issue with the latest version of VS Code?

**Comment by ZCShou** [comment]
@bobbrow  No.Thanks!
