### ISSUE TITLE
Syntax highlighting is wrong when using double-quote as a char ('"')

### ISSUE THREAD

**Issue by 3v1n0** [microsoft/vscode-cpptools#2490]
Versione: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Data: 2018-08-16T18:34:20.517Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architettura: x64

This is what I'm getting when opening a C file with this code:

```c
case '@':
  c = phase2_getc ();
  if (c != '"')
    {
      phase2_ungetc (c);
      tp->type = last_token_type = token_type_other;
      return;
    }
  template = true;
  /* FALLTHROUGH */
case '"':
  {
    int c2 = phase2_getc ();

    if (c2 == '"')
      {
        int c3 = phase2_getc ();
        if (c3 == '"')
          verbatim = true;
        else
          {
            phase2_ungetc (c3);
            phase2_ungetc (c2);
          }
      }
    else
      phase2_ungetc (c2);
  }
```

Which generates this. I'ts like the ending `'` isn't keept in consideration for terminating the string.

![immagine](https://user-images.githubusercontent.com/345675/45172575-01876b00-b206-11e8-890b-9d44e8b9630c.png)

**Comment by sean-mcmanus** [comment]
Hmm...I don't see any bug. Do you know what you could be doing differently? What version of VS Code are you using? What OS?


![image](https://user-images.githubusercontent.com/19859882/45178608-07138f80-b1cb-11e8-9ac0-8060e96d6440.png)

**Comment by bobbrow** [comment]
It could be a bug with a certain theme. None of the default VS Code themes italicize keywords. @3v1n0 what theme are you using?

**Comment by 3v1n0** [comment]
This is vscode 1.26.1.

It's not theme dependent, but it works properly if you set "Language: C", while it doesn't if you select "Language C/C++".

**Comment by sean-mcmanus** [comment]
Yeah, I tried with C and C++. Is there some additional code beforehand that is required for the repro?

**Comment by 3v1n0** [comment]
Nope, I've noticed that in [this file](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=gettext-tools/src/x-javascript.c;h=2db00abe6cd058de2743f787bd6c801d78791a79;hb=HEAD#l1197)

**Comment by sean-mcmanus** [comment]
That file doesn't have the '@' character in it. Was it updated? Or what line in that file has the incorrect syntax? Our extension doesn't implement the coloring but if we can get repro we can file a bug with atom/language-c.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
