### ISSUE TITLE
Variable expansion does not work for default setttings

### ISSUE THREAD

**Issue by g-arjones** [microsoft/vscode-cpptools#2491]
Type: General
- OS and Version: Ubuntu 16.04
- VS Code Version: 1.27.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): none
- Variables expansion do not work for default settings

1. Open user settings.json
2. Add ""C_Cpp.default.compileCommands": "${workspaceRoot}/build/compile_commands.json"

**Expected behavior**
${workspaceRoot} should be expanded to the absolute path of the folder

**Comment by sean-mcmanus** [comment]
Hmm...it's working for me. It's possible something else is causing your compile_commands.json to not be used. In the error message we send back, we show "${workspaceFolder}" intentionally. If the path doesn't exist, it will be silently ignored (it might be better if we showed some warning message). @bobbrow Are you able to repro any issue?

**Comment by g-arjones** [comment]
Is ${workspaceFolderBasename} supposed to be expanded as well?

**Comment by bobbrow** [comment]
> Is ${workspaceFolderBasename} supposed to be expanded as well?

We don't currently support that particular variable.

**Comment by g-arjones** [comment]
Is there any way to get the path where the .code-workspace file is?

**Comment by bobbrow** [comment]
I don't believe VS Code has a variable for that.  https://code.visualstudio.com/docs/editor/variables-reference

**Comment by g-arjones** [comment]
Any plans to add support for ${workspaceFolderBasename} ? Maybe I can open a pull request for that if you point me in the right direction...

**Comment by bobbrow** [comment]
You could search for usages of `util.resolveVariables` and add `"workspaceFolderBasename": <value>` to the  `additionalEnvironment` passed in.
* For `configurations.ts` you should be able to get that value by extracting it from `this.rootUri`.
* For `client.ts` you should be able to get it from `this.Name`.

**Comment by g-arjones** [comment]
Great! I will give it a try... Thanks.

**Comment by g-arjones** [comment]
Done: #2495
