### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by Evan-Nishi** [microsoft/vscode-cpptools#2496]
I need help trying to set up visual studio code to program c.  I am trying to use coderunner and whenever I try to run my program this message keeps popping up.    "#include errors detected. Please update your includePath. IntelliSense features for this translation unit (C:\\Users\\evank\\Desktop\\C coding lang\\.vscode\\Storage for c\\Test.c) will be provided by the Tag Parser."

I don't know how to edit the Json path and I am very confused.  Any help would be nice.  This is my first time on GitHub btw

**Comment by nebulabox** [comment]
https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md

**Comment by nebulabox** [comment]
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started%20with%20IntelliSense%20configuration.md

**Comment by Evan-Nishi** [comment]
Thank you very much!

**Comment by bobbrow** [comment]
Thanks for jumping in here @nebulabox!

**Comment by Evan-Nishi** [comment]
Wait how do I tell what to input in the json

**Comment by bobbrow** [comment]
It depends on your operating system.  It looks like you are on Windows.  Which compiler are you using to build your code?  If you look in your `.vscode/c_cpp_properties.json` file, the extension may have identified a compiler on your PC already.
