### ISSUE TITLE
Missing mono executable - Ubuntu 16.04 (aarch64)

### ISSUE THREAD

**Issue by jackcoach** [microsoft/vscode-cpptools#2497]
I compiled and launched VsCode Version: 1.28.0
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41

The architecture is aarch64 (Nvidia Jetson TX2).

Then I installed the cpptools extension via VSIX file, but when I launch the debug process I always get the  "Debug adapter process has terminated unexpectedly" error - after which I cannot launch anymore debugs.

The Intellisense feature works.

I should add that, after installing the extension, there is no cpptools-related folder in the ./vscode directory.

How can I solve this?

Thanks in advance.

Update:
when I open a folder in VsCode with the extension installed, the following errors occur:

```
[Error - 2:14:00 PM] Starting client failed
Launching server using command /home/nvidia/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.18.1/bin/Microsoft.VSCode.CPP.Extension.linux failed.
/home/nvidia/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.18.1/debugAdapters/OpenDebugAD7: line 32: mono: command not found
```

Here is launch.json:

```
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/nvidia/Desktop/chamelea_stream/build/src/cpp/chamelea_stream",
            "args": [],
            "stopAtEntry": false,
            "cwd": "/home/nvidia/Desktop/chamelea_stream/build/src/cpp",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": false
                }
            ]
        }
    ]
}
```

```
`[uncaught exception]: Error: read ECONNRESET
onError @ index.js:40
(anonymous) @ index.js:178
emitOne @ events.js:116
emit @ events.js:211
window.onerror @ /home/nvidia/Downloads/vscode-master/vscode/.build/electron/resources/electron.asar/renderer/init.js:142
index.js:43 Error: read ECONNRESET
    at _errnoException (util.js:1024)
    at Pipe.onread (net.js:615)
onError @ index.js:43
(anonymous) @ index.js:178
emitOne @ events.js:116
emit @ events.js:211
window.onerror @ /home/nvidia/Downloads/vscode-master/vscode/.build/electron/resources/electron.asar/renderer/init.js:142
notificationsAlerts.ts:41 Debug adapter process has terminated unexpectedly
NotificationsAlerts.onDidNotificationChange @ notificationsAlerts.ts:41
(anonymous) @ notificationsAlerts.ts:27
Emitter.fire @ event.ts:140
NotificationsModel.notify @ notifications.ts:113
NotificationService.error @ notificationService.ts:52
RawDebugSession.onDebugAdapterExit @ rawDebugSession.ts:531
(anonymous) @ rawDebugSession.ts:160
Emitter.fire @ event.ts:140
(anonymous) @ debugAdapter.ts:305
emitTwo @ events.js:126
emit @ events.js:214
ChildProcess._handle.onexit @ internal/child_process.js:198`
```

**Comment by pieandcakes** [comment]
@jackcoach if you build your own VS Code, your extensions are installed into `~/.vscode-oss-dev` . 

It looks like you are on ARM64. If so, you need to download a separate supported `mono` executable for that architecture as we don't support it out of the box.

**Comment by pieandcakes** [comment]
We use `mono` version `4.2.3.4` but It looks like they don't even have an arm64 package until `4.6.1.3`. You can try downloading it from [here](http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-runtime-sgen_4.6.1.3-0xamarin1_arm64.deb) or using a package manager to download latest. All you need is the `mono` executable which should be labeled `mono-sgen`.

**Comment by jackcoach** [comment]
Hello, I installed the updated mono executable and the debugger runs just fine, thank you very much!

Still, the Intellisense feature fails to start when opening my project's folder, giving me these error messages:

```
[Error - 7:06:13 AM] Starting client failed
Launching server using command /home/nvidia/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.18.1/bin/Microsoft.VSCode.CPP.Extension.linux failed.
```

**Comment by bobbrow** [comment]
If you run `/home/nvidia/.vscode-oss-dev/extensions/ms-vscode.cpptools-0.18.1/bin/Microsoft.VSCode.CPP.Extension.linux` in a terminal window, do you get any errors?

**Comment by jackcoach** [comment]
Hello @bobbrow , there's nothing in there named Microsoft.VsCode.CPP.Extension.linux, the content of the bin folder is the following:

```
msvc.32.intel.json	  msvc.64.intel.clang.json  msvc.64.linux.msvc.json
msvc.64.darwin.json	  msvc.64.intel.json	    msvc.json
msvc.64.darwin.msvc.json  msvc.64.linux.json
```

**Comment by bobbrow** [comment]
It seems that the extension is not installed properly.  Can you try reinstalling it?  If the version from the extension gallery is not working, you can try downloading the full package from our releases page (This is the 64-bit linux package: [cpptools-linux.vsix](https://github.com/Microsoft/vscode-cpptools/releases/download/v0.18.1/cpptools-linux.vsix)) and using the "Install from VSIX" command to do a manual install.

**Comment by jackcoach** [comment]
Hello, previously I had tried to uninstall and reinstall it several times both using the extension manager and the vsix file found on the repo.

Now using the file you gave me I reinstalled the extension, two executable files are present in the bin directory (Extension.linux and Intellisense.Msvc.linux), but still when I open VsCode it gives me the following error:

`Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Error: spawn EACCES`

When I try to run the executables from terminal, the message for both is the following:

`cannot execute binary file: Exec format error`

**Comment by bobbrow** [comment]
Is aarch64 an ARM64 variant?  I naively assumed it was a 64-bit build.  We don't currently ship a binary compatible with ARM or ARM64.

**Comment by jackcoach** [comment]
Yes @bobbrow , the cores are actually Nvidia Denver2 (ARMv8, 64bit) CPUs.

Is there a way for me to crosscompile the project in order to get compatible binaries?

Cheers

**Comment by bobbrow** [comment]
Unfortunately, there is no way for you to do this right now.  We have not opened the source for the language server binaries.  ARM64 is not on our roadmap yet, but we can take it into consideration.

**Comment by jackcoach** [comment]
Yes please take it into consideration, it would be great to have every feature of this extension available for this architecture.

Thank you for your time!

**Comment by bobbrow** [comment]
I created a feature request for this.  Please go upvote #2506 so we can start to get a count of users who would benefit from this.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.0.0
