### ISSUE TITLE
[C++] Single quotes in numeric literals used with user-defined numerals are parsed incorrectly

### ISSUE THREAD

**Issue by Kaznov** [microsoft/vscode-cpptools#2498]
Issue Type: <b>Bug</b>

If .cpp file contains following code:
``` c++
 using namespace std::chrono_literals;
 auto t = 10'000ms;
```

From the second line on, everything after single quote is highlighted as a string literal.

Extension version: 0.18.1
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

**Comment by bobbrow** [comment]
it's the user-defined literal (`ms`) that's tripping up the colorizer.  This is https://github.com/atom/language-c/issues/127

**Comment by sean-mcmanus** [comment]
Fixed in VS Code Insiders.
