### ISSUE TITLE
how to view the printf output or input values for scanf when using Visual Studio Windows  Bebugger?

### ISSUE THREAD

**Issue by aoyulong** [microsoft/vscode-cpptools#250]
OS: win 10 64 bit and the VS code: 1.5.3. 

For now, I can get the imperfect function by setting the "externalConsole": true in the launch.json. Howeveer,  the limitation is that I have to use mouth to switch between the vscode and the command prompt. Is there any other built-in features I ignore to implement this?

**Comment by pieandcakes** [comment]
@aoyulong We plan on integrating the console output into the VSCode debug console in the future. For now, please use `"externalConsole": "true"` in your launch.json and use the external terminal.

**Comment by pieandcakes** [comment]
This issue is being tracked on #35
