### ISSUE TITLE
Visual studio code

### ISSUE THREAD

**Issue by Evan-Nishi** [microsoft/vscode-cpptools#2501]
I keep getting this error when editing my c code in visual studio code.
 'gcc' is not recognized as an internal or external command,
operable program or batch file.
Also I don't know how to edit my include path to allow me to use  the include path.  When I click on the light bulb it takes me to c_cpp_properties.json.   I could really use some help.  Thanks! #545

**Comment by bool3max** [comment]
This is the place for bug reports related to the extension, not a place to ask for help.

I find it absolutely stunning that a person will construct an entire issue report on GitHub before they go and read the instructions for the software they have trouble using. 

Take a look at [this](https://code.visualstudio.com/docs/languages/cpp) article.

**Comment by Evan-Nishi** [comment]
I actually looked at this document because it was linked on the help page of the VS code and installed the C/C++ extension already, but the green line under the #include<stdio.h> did not direct me to add to includepath.     I also did not find anything that helped on the gcc error.  I apologize that I used the "issues" section of GitHub in the wrong way.  Could you please direct me to a website where it is appropriate to ask these kind of questions?

**Comment by bool3max** [comment]
Well for one, you didn't even specify the platform you were on, the `C/C++` compiler which you're using (both of which are crucial for the issue you're having), nor any of the versions (which are all predefined in the issue template for this repository), so even if someone wanted to help you (me right now) they couldn't.

**Comment by Evan-Nishi** [comment]
Oh sorry, I'm on windows 10, I am using code runner extension to run my C and I am using version 0.9.4 for code runner, 0.18.1 for the c extension and I am using 1.27 for the vs code.  By the way can you please recommend me to a website where I can ask theses questions?

**Comment by bobbrow** [comment]
It's ok to ask questions here.  The configuration file documentation is here:  https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md

To edit the configuration, open the Command Palette (<kbd>CTL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd>) and start typing "Edit Configurations" to find the "C/Cpp: Edit Configurations..." command.

The settings you are looking for are probably `compilerPath` and `intelliSenseMode`.  Set `compilerPath` to the absolute path of your gcc compiler and `intelliSenseMode` to `gcc-x64`.  There is additional documentation about configuring MinGW here: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md

**Comment by sean-mcmanus** [comment]
Yeah, the question policy is a little confusing because VS Code itself wants questions asked at StackOverflow (https://stackoverflow.com/questions/tagged/visual-studio-code ), but our C/C++ extension just uses GitHub for questions.

I don't think the error message is coming from our extension. Can you disable the C/C++ extension and see if it still repros? Where are you specifying "gcc" in your settings? Our extension's c_cpp_properties.json is just for configuring IntelliSense and not actually compiling gcc.

**Comment by Evan-Nishi** [comment]
How can I specify my gcc in settings? I was told by my friend that code runner extension will just run code once install it.  I think I need to specify gcc and configure json also but I keep getting confused.   I was also told I need to download a library or something

**Comment by bool3max** [comment]
Learn to compile C from the command line before you use any "code runner" extensions. It will make things easier. Then, read the documentation of the `C/C++` extension which tells you which JSON fields you need to fill to tell it where your compiler executable resides.

**Comment by bobbrow** [comment]
@pErs0nZ if you are having trouble with a code runner extension, unfortunately this is not the place to ask.  This forum is for the Microsoft C/C++ extension.  I may have wrongly assumed that you were having trouble configuring IntelliSense.  We can help you with that here (and that's actually what my instructions above were assuming).

The issues page for the code runner extension appears to be here: https://github.com/formulahendry/vscode-code-runner/issues

**Comment by Evan-Nishi** [comment]
Ok thanks
