### ISSUE TITLE
compile_commands.json doesn't work with WSL

### ISSUE THREAD

**Issue by kayle** [microsoft/vscode-cpptools#2510]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.27
- C/C++ Extension Version: 0.18.1

**To Reproduce**

c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "WSL",
            "intelliSenseMode": "gcc-x64",
            "compilerPath": "/usr/bin/gcc",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compileCommands":"${workspaceFolder}/../BuildOutput/cmake/ninja/compile_commands.json",
            "defines": [],
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

compile_commands.json:
```
{
  "directory": "/mnt/c/repo/BuildOutput/cmake/ninja/test",
  "command": "/usr/bin/g++  -D_CROSS_PLATFORM=1 -isystem /mnt/c/repo/vcpkg/installed/x64-linux/include   -Wall   -std=gnu++1z -o CMakeFiles/test-statops.dir/test_c1.cpp.o -c /mnt/c/repo/DspOps/test/test_c1.cpp",
  "file": "/mnt/c/repo/DspOps/test/test_c1.cpp"
}
```

**Expected behavior**

I expect the WSL paths from compile_commands.json to get translated to the corresponding Windows paths.

**Screenshots**

![image](https://user-images.githubusercontent.com/1664776/45429405-3fa2e580-b671-11e8-9c2a-141a4ab12fb1.png)

**Comment by flamtapgt** [comment]
I have run into the same issue. Is there any update on whether this should be supported?

**Comment by sean-mcmanus** [comment]
No update yet. Maybe we could look at this at the same time we look at the similar WSL compilerPath issue at https://github.com/Microsoft/vscode-cpptools/issues/2978 .

**Comment by sshaw-lutron** [comment]
I've come up against the same problem when using WSL. Since it has only been a short time since the last comment I'm assuming that the status has changed, but hopefully in the next release.

**Comment by flamtapgt** [comment]
Consider using the new [Remote-WSL](https://code.visualstudio.com/docs/remote/wsl) extension (if you can use the Insiders release)

**Comment by sshaw-lutron** [comment]
Thanks, @flamtapgt, this is very interesting. I'll have to take a closer look once I figure out how to test it without breaking my current setup. I am doing embedded development and use a usb based debugger and the Cortex-Debug extension to debug. I'll have to try it out and see if I can still get these extensions working as needed.

**Comment by bobbrow** [comment]
We're not likely to make any more changes to our WSL support now that the Remote-WSL extension is available.  Closing this issue.
