### ISSUE TITLE
"Go to definition"  doesn't work if the declaration contains a preprocessor macro

### ISSUE THREAD

**Issue by gbonacini** [microsoft/vscode-cpptools#2513]
**Type: LanguageService**

**Describe the bug**
- OS and Version: OSx 10.11
- VS Code Version: 1.27.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): vim plugin , python (disabled in that project )
- Concise description of what the bug is:
If in the header file is present a declaration like this : 
void                   checkSshHeader(void)          MYMACRO;
where MYMACRO is a macro that will be expanded by c++ preprocessor, the navidation function "Go to definition" won't work properly, providing, as results the calls to the specified function instead of the declaration. Removing the macro all seems to work fine again.

**To Reproduce**

1. Add in a header file a function like:
void                   checkSshHeader(void)          MYMACRO; 
with a related definition in a cpp file
2. Click on 'Go to definition'
3. See errors: the results are pointers to *calls* tho the specified function instead to its definition, as expected. 

**Expected behavior**

 the result should be the portion of code with the function definition, as expected. 
**Screenshots**

**Additional context**
None.

**Comment by sean-mcmanus** [comment]
This is a "by design" limitation of our parser. You need to put the macro in a cpp.hint file. See https://go.microsoft.com/fwlink/?linkid=865984 .
