### ISSUE TITLE
std::array initialization marked as error

### ISSUE THREAD

**Issue by XobSod** [microsoft/vscode-cpptools#2516]
**Describe the bug**
- OS and Version: Linux Mint 18.1
- VS Code Version: 1.27
- C/C++ Extension Version: 0.18.1

**To Reproduce**
testFile.cpp contains
```
#include <array>
constexpr std::array aaa = {10,2,3,4,5};
int main()
{
    return aaa[0];
}
```
Problem is reported:
`no instance of constructor "array" matches the argument list -- argument types are: (int, int, int, int, int)`

**Expected behavior**
As code is valid, no problems should be reported.

**Additional context**
c_cpp_prpoerties.json:
```
"compilerPath": "/usr/bin/clang++-8",
"cStandard": "c11",
"cppStandard": "c++17",
"intelliSenseMode": "clang-x64",
```

**Comment by Colengms** [comment]
This appears to have been addressed.  The example code no longer reports a problem.
