### ISSUE TITLE
'Format Code' not recognize main include

### ISSUE THREAD

**Issue by darsausalo** [microsoft/vscode-cpptools#252]
When use option 'C_Cpp.clang_format_sortIncludes=true', clang-format not recognize 'main include'.

Source Host.cpp:

```
#include "Console.h"
#include "Shell.h"
#include "Host.h"
#include <iostream>
```

Expected:

```
#include "Host.h"
#include "Console.h"
#include "Shell.h"
#include <iostream>
```

Result:

```
#include "Console.h"
#include "Host.h"
#include "Shell.h"
#include <iostream>
```

first include always should be same as filename of current file, but in current (0.9.2) version of vscode-cpptools clang-format don't recognize it. I assume clang-format receive invalid filename from vscode-cpptools.

**Comment by sean-mcmanus** [comment]
Oh, I see. Yeah, we pass in the text of the file to clang-format instead of the file itself. I'll investigate...

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. The fix will be in the next update.

**Comment by darsausalo** [comment]
Thanks a lot!
