### ISSUE TITLE
please remove the need to type  -exec in debug console to execute a native debugger command

### ISSUE THREAD

**Issue by DanPartelly** [microsoft/vscode-cpptools#2520]
Type: Debugger

Given the fact that the debugger GUI in Visual Studio code is still quite primitive and does not provide anything more than the basics, one still has to use native debugger commands in console quite intensely for non-trivial debugging. (really, even if you would have enough features in  debug UI to rival Visual Studio debug commands would still be necessary IMO)

Having to prefix a native debugger command with -exec is very cumbersome and greatly diminish the speed of ones work.  
More than this, it appears to me that the existence of -exec cannot be motivated in any way. First of all, the debugger command window offers all the context you needs, you are only expected to type debug commands there. 
Second, if -exec is needed for some esoteric reason , just build a new string yourself behind the scenes. Or if this would interfere with debugging in other modes/languages provide a configuration flag
in the  debug settings json and build it only when it is set. Please spare C/C++ users of this pain

**Comment by aremmell** [comment]
+1

**Comment by WardenGnaw** [comment]
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/106

Please continue discussion on that issue.

**Comment by DanPartelly** [comment]
I posted there, but that issue is 2 years old, and prolly nobody gave a damn. Meanwhile, debugging with gdb in Visual Studio Code is and remains a nightmare.

**Comment by AnthonyParkssonos** [comment]
^ amen, drives me completely bonkers that i have to type `-exec` everything i want to do something like `p/t` or `p/x`....there is no reason for this for 99% of users of cpptools

**Comment by ilyaZar** [comment]
Agreed. It annoys me a lot as well. Please remove it.

**Comment by mbUSC** [comment]
Seriously, this is ridiculous. Get rid of it!
