### ISSUE TITLE
[Unable to debug a basic C++ program]

### ISSUE THREAD

**Issue by Parushgit** [microsoft/vscode-cpptools#2522]
Type: Debugger
**Input information below**
I just created one `.cpp` file and now I am trying to debug it. I put the debugger and all it does is `exit with code 0`.

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: MacOSX
- VS Code Version: V 1.24.1
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is. I created a `.cpp` file. I compiled it with command `g++ decodeString.cpp -p decodeString`. I modified the path in `launch.json` file and tried to run `debug.` I receive this 

![image](https://user-images.githubusercontent.com/3814904/45592235-cc7dc580-b935-11e8-8193-29e38858aebe.png)

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

1. Code sample file 
`
#include<iostream>
#include<stdlib.h>
using namespace std;
string result;
string helper_decodeString(int i, string s) {
int num = 0;
string word = "";
for(;i < s.length(); i++) {
    if(s[i] == '[') {
        string output = helper_decodeString(i+1, s); 
        while(num > 0) {
            result += output;
            num--;
        }
    }
    else if(isdigit(s[i])) {
        num = s[i] - '0';
    }
    else if(s[i] == ']') {
        return word;
    }
    else {
        word = word + s[i];
    }
}
return word;
}

string decodeString(string s) {
    return helper_decodeString(0, s);
}

void main() {
    string output;
    output = decodeString("3[a]");
    cout<<"Hello"<<endl;
}
`
2. `launch.json` file
`
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/decodeString",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb"
        }
    ]
}
`
3. See error screenshot above.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by bobbrow** [comment]
Did you try compiling with the `-g` option to produce debug information needed by gdb?

**Comment by WardenGnaw** [comment]
> I compiled it with command g++ decodeString.cpp -p decodeString

You will need to compile with the `-g` flag. Closing for now. Please reopen if you are encountering any more issues.
