### ISSUE TITLE
incorrect clang-format -style formatting

### ISSUE THREAD

**Issue by yagehu** [microsoft/vscode-cpptools#2524]
After I correctly set `C_Cpp.clang_format_path` and format a cpp document, the file doesn't get formatted, and there is no error output. I have verified that error gets printed to output correctly by setting  `C_Cpp.clang_format_path` to some non-existent path. e.g.

```
/not/a/real/path -style={ BasedOnStyle: LLVM } -fallback-style=LLVM -sort-includes=0 -assume-filename=<some cpp file>
  Can't find or run process_name
```

If I run the command `clang-format -style={ BasedOnStyle: LLVM } -fallback-style=LLVM -sort-includes=0 -assume-filename=<some cpp file>` on the command line, clang-format errors out because `-style={ BasedOnStyle: LLVM }` should be `-style='{ BasedOnStyle: LLVM }'`. I suspect this is the reason for the file to not get formatted.

On Linux btw.

**Comment by sean-mcmanus** [comment]
What version of clang-format are you using? We intentionally do no use quotes around the style on Linux, because it doesn't accept that (we use quotes on Windows). This is the way we've always done it, so I'm not sure what is special about your scenario that could be causing this.

**Comment by yagehu** [comment]
```
$ clang-format --version
clang-format version 6.0.1 (tags/RELEASE_601/final)

$ which clang-format
/usr/bin/clang-format
```

I set `C_Cpp.clang_format_path` to `/usr/bin/clang-format`.

Please advise if there's other info I can provide to help locate the problem. Thanks!

**Comment by sean-mcmanus** [comment]
Can you explicitly add a single or double-quote (i.e. using `\"` in settings.json) to the C_Cpp.clang_format_style (or _fallbackStyle) as a workaround? When I do that with the installed clang-format 6.0.0 it fails with "Invalid value for -style". I don't know yet how to detect these different input requirements -- it seems very unlikely that clang-format would break the input requirements like this.

**Comment by yagehu** [comment]
I don't what I did that fixed it. I uninstalled all other C/C++ related extensions. It may be a legacy extension conflict. Thanks for the help anyways!
