### ISSUE TITLE
Use only debugger adapter from extension

### ISSUE THREAD

**Issue by ruabmbua** [microsoft/vscode-cpptools#2525]
Type: General
Hi!

I wonder if it is possible to extract just the debug adapter part of this extension, and build a new extension with it. I am using the cquery-language server as my C++ plugin in vscode, but it does not provide a debugger. Now I am trying to use vscode-cpptools with cquery, but both extensions loaded at the same time results in both not working at all (for example the compiler error stops from being updated etc...)

Another debugger extension does not work for me. I need gdb, and I already tried all other plugins available on the vscode marketplace, which all are not working at all.

**Comment by bobbrow** [comment]
Does disabling the language server not work for you?
```
    "C_Cpp.intelliSenseEngine": "Disabled"
```

**Comment by ruabmbua** [comment]
I will try it as soon as possible. I did not know Disabled was an option.

**Comment by ruabmbua** [comment]
It works, thanks!
