### ISSUE TITLE
How to set the compiler path

### ISSUE THREAD

**Issue by PijushManna** [microsoft/vscode-cpptools#2537]
I don't know how to set the compiler path. Every time i set it in c_cpp_properties.json . Whenever i go to some other folder the error again comes. Need a parmenent solution. and please make a youtube video how to do that . because most of the time you written in description doesn't work.

**Comment by sean-mcmanus** [comment]
You can set C_Cpp.default.compilerPath in settings.json. Are you able to get that to work? c_cpp_properties.json is just for the current workspace folder.
