### ISSUE TITLE
Please provide a way to perform input redirection from a file

### ISSUE THREAD

**Issue by mukulChandYadav** [microsoft/vscode-cpptools#254]
Please provide a way to perform input redirection from a file while debugging a C/C++ application, like ./a.out < testCase.txt.

PS Please mark it as a feature request.

**Comment by Yienschwen** [comment]
@mukul-git You should try revising the `args` item your `.vscode/launch.json`.
For example: 

<pre>
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/a.exe",
            "args": ["&lt;testCase.txt"],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false,
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb"
            }
        }
    ]
}
</pre>

This should work.
No need to mark as feature request, instead I suggest close this issue.

**Comment by pieandcakes** [comment]
@mukul-git Yes, @Yienschwen 's comment should resolve your issue. Please reopen/comment if it does not.

**Comment by mukulChandYadav** [comment]
@Yienschwen Thanks. Actually i tried the same but now i see that I was putting a blank space in between the caret and filename, due to which it was not working. If it's not a bug then please mark it closed.

**Comment by beta-me** [comment]
Even after setting this "args" = [">input.txt"] and "externalConsole" = "true", input is not taken from input.txt. If I set "externalConsole" = "false", then where to see the output

**Comment by spierepf** [comment]
Tried this on Linux, and it does not redirect, instead it continues to expect input from the console.

You can find an example here:

https://github.com/spierepf/Advent-of-Code/tree/master/2015/01%20-%20Not%20Quite%20Lisp
