### ISSUE TITLE
How can I re-enable error squiggles?

### ISSUE THREAD

**Issue by Hopson97** [microsoft/vscode-cpptools#2546]
I accidentally disabled error squiggles, and I have no idea how to re-enable them.

I had an error, and a light bulb appeared. I clicked on it, and then it disabled error checking.

Thanks!

**Comment by Hopson97** [comment]
In the config file, `"C_Cpp.errorSquiggles"` was set to "Disabled"

**Comment by Hopson97** [comment]
Only works when a file is saved now. Used to work "on the fly", how can I get this working? Thanks!

**Comment by sean-mcmanus** [comment]
Normally, the error squiggles will update on a timer. There is a known bug that sometimes requires a save (or waiting 10 seconds).

**Comment by Hopson97** [comment]
I understand, thank you! Seems to be working OK now.

**Comment by watchpoints** [comment]
In the config file, "C_Cpp.errorSquiggles" was set to "Disabled"

> it not work

**Comment by Hopson97** [comment]
@aleafboat  ?

**Comment by nicklesimba** [comment]
Hey I had the same issue, and I changed "Disabled" to "Enabled" and nothing is happening. How do I fix this? Thanks!

**Comment by bobbrow** [comment]
There are some cases where we automatically disable squiggles and we don't have an override setting for that right now.  One such case is if you open a code file without opening a workspace folder.

**Comment by sparshgoyal2014** [comment]
hey!..plz help me i have the same problem ...i tried very much ...i also tried by enabling the options but these don't work for me..

**Comment by sean-mcmanus** [comment]
@sparshgoyal2014 Did you open a workspace or folder?

**Comment by laura-ft** [comment]
you can also go into files->preferences->settings ( or simply do ctrl+, ) and search for squiggles ( they can be found in workspace ) and there it shows its current state, from where you can change it to enabled again

**Comment by shrnv99** [comment]
> hey!..plz help me i have the same problem ...i tried very much ...i also tried by enabling the options but these don't work for me..

You can try to click on Also modified in user/workspace in the error squiggles settings to make them both enabled. I am not sure what both of them individually means but it certainly worked for me.

**Comment by amarphule** [comment]
@laura-ft  I had the same issue with squiggles, your suggestion worked perfectly thanks

**Comment by ghost** [comment]
Follow these steps to re-enable your error squiggles 
1.Open your vs code.
2.By click ctrl+shift +P  through your keyboard. 
3.A tab will appear on screen 
Search c/c++: enable error squiggles in it and click on it.
4.By this you can re enable your error squiggles again.
I hope this can help you.
