### ISSUE TITLE
Support Backslash and forward slash in include statements

### ISSUE THREAD

**Issue by leifcr** [microsoft/vscode-cpptools#2547]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.27.2
- C/C++ Extension Version: Version 0.18.1: August 17, 2018
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.

**To Reproduce**

Create a CPP file and add
```#include <TestLibrary\somefile.h>```

Intellisense doesn't work. Replacing \ with / fixes the issue, and let's intellisens at least open somefile.h

The problem is more complex, as if TestLibrary/somefile.h contains another include (```#include <TestLibrary/otherfile.h>```) which also has \ instead of /, intellisense fails.

Please add support for both \ and / in include statements, as lots of legacy code uses \ instead of / in the include statements.

**Expected behavior**
Intellisense should support both \ and / in include statements.

**Comment by leifcr** [comment]
Related #696

**Comment by sean-mcmanus** [comment]
What compiler are you using and what is your compilerPath? Is there a reason you're using msvc-x64 mode on Linux?

**Comment by leifcr** [comment]
Excellent question! I'm working with legacy windows libraries. The code will be compiled on Windows, but I prefer Linux when developing. I'm using clang config, but I referred to the other bug. Suggestion if possible, is to have intellisense replace slashes while parsing.

**Comment by sean-mcmanus** [comment]
Okay, yeah, I think this has the same root fix as https://github.com/Microsoft/vscode-cpptools/issues/696 .

**Comment by kzhui125** [comment]
@sean-mcmanus hope you support backslash too on mac/linux.
On my mac, I read and write codes which runs on Windows, the source code has backslash in #include.
