### ISSUE TITLE
Unable to open 'isoc99_scanf.c': File not found

### ISSUE THREAD

**Issue by ravirajawasthi** [microsoft/vscode-cpptools#2548]
Type: Debugger
Unable to open 'isoc99_scanf.c': File not found (file:///build/glibc-Cl5G7W/glibc-2.23/stdio-common/isoc99_scanf.c).

**error while debugging file**
- OS and Version: Ubuntu 16.04
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is. 

**As i start debugging and move on to scanf line, error shows**
launch.json 
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/a.out",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            
        }
    ]
}

tasks.json 

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build_debug",
            "type": "shell",
            "command": "cd ${fileDirname} && gcc -g ${fileBasename}",
            "args": [
                ""
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}

code 
#include <stdio.h>
#include <string.h>
int main()
{
    char str[100] = {0};
    //str[100] is for storing the sentence and substr[50][50] is for storing each word.

    scanf("%s", &str);
    char temp[50];
    char small_word[50];
    char large_word[50];
    int small_len = 0;
    int large_len = 0;
    int i = 0;
    int word_len = 0;
    int word_start = 0;
    int word_end = 0;
    char counter;
    counter = str[i];
    for (int i = 0; i < strlen(str); i++){
        counter = str[i];
        if (counter > 64 && counter < 91 || counter > 96 && counter < 123){
            if (word_len == 0){
                word_start = i;
                }
            word_len++;
            }
        else {
            for (int k = word_start, i = 0; k <= word_end; k++){
                temp[i++] = str[k];
            }
            temp[i] = '\0';
            word_end = i - 1;
            if (word_len < small_len ){
                strcpy(small_word, temp);
                small_len = word_len;
            }
            if (word_len > large_len){
                strcpy(large_word, temp);
                large_len = word_len;
            }
            word_start = word_len = word_end = 0;
            
        }
    }
    printf("Largest Word is: %s\nSmallest word is: %s\n", large_word, small_word);
    return 0;
}
1. Start debugging with following settings and you will see the error
![image](https://user-images.githubusercontent.com/27188880/45940175-06fdf700-bff5-11e8-8662-104a8fca76ff.png)

**Comment by WardenGnaw** [comment]
This is by design. When you stop in code that is not owned by you (such as library code in this case, the fopen method), the debugger will return where the library thinks the source should be but since its a glibc library, you probably don't have the source files (which is why it gives the error). You should be able to ignore it and continue debugging.

**Comment by kameshkotwani** [comment]
We can easily get into the function in Windows but not in Linux. With same config, when I debug in Windows I get no error and debugging happens easily. But in linux, after this error, we can no longer continue with debugging. Even after installing glibc-source files, I get this error. Please help. It's very frustrating.

**Comment by WardenGnaw** [comment]
@kameshkotwani  Unless you built glibc-source files and patched the libraries, the debugger will not be able to the sources automatically. 

If you provide [source file mappings](https://code.visualstudio.com/docs/cpp/launch-json-reference#_sourcefilemap) in your launch.json, then the debugger can map the paths to where it thinks glibc exists to your glibc-source is on your machine.

**Comment by kameshkotwani** [comment]
@WardenGnaw I will definitely try that and let you know sir!
