### ISSUE TITLE
Where is the recommended way to put c_cpp_properties.json ?

### ISSUE THREAD

**Issue by certik** [microsoft/vscode-cpptools#2549]
**Type: LanguageService**

I have successfully setup the vscode's C++ extension to work with one of our open source projects and send a PR (https://github.com/symengine/symengine/pull/1427) to add the `c_cpp_properties.json` into the git project itself, so that vscode works out of the box for other developers, not just me.

Is that the recommended approach? Or should the `c_cpp_properties.json` file live somewhere else, and we should have instructions in our README how to download it and setup vscode to work with our open source project?

I tried to find this information in your documentation, but couldn't find any guidance on this. Thanks for any feedback on this.

**Comment by sean-mcmanus** [comment]
If you're able to set the c_cpp_properties.json in a way that works on different computers that would be okay. If that doesn't work, you may need to have additional instructions on how to modify the c_cpp_properties.json and/or set the C_Cpp.default.* values correctly.

**Comment by certik** [comment]
@sean-mcmanus thanks for your feedback. I think that answers my question, so I am going to close it.
