### ISSUE TITLE
[Linux] Cannot launch gnome-terminal when launching as a different user

### ISSUE THREAD

**Issue by sariyn** [microsoft/vscode-cpptools#2550]
Hello,
I want to run vscode/cpp under a different user, e.g. with su -l or sudo -u.
When I do, I have to add this to my launch.json to clear an accessibility bus error.
    "environment": [{"name": "NO_AT_BRIDGE", "value": "1"}],

Afterwards I get stuck at a second error:
term-stdout: # Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Unknown or unsupported transport “disabled” for address “disabled:”

Everything works just fine on my normal login, which I do not wish to use here.

I can install xterm, rename gnome-terminal, and everything works fine with xterm.  But this is less than ideal and would prefer a fix.

Aside from this issue itself but not unrelated, I would like to choose my own terminal for vscode/cpp (e.g. xterm over gnome) and take that chance.  I understand they are not all tested but I used to create a link to konsole as gnome-terminal without any issues when I ran vscode on kde.  A little override option here will go a long way.  Right now I have to choose between my work flow, breaking my gnome-terminal links, or vscode.

Regards,

**Comment by pieandcakes** [comment]
@Sariyn To solve the terminal problem we are trying to get away from calling one specific terminal and switching to using VS Code's terminal implementation. #35 is something that we are working on right now and will be available in a future release.

For your current situation, we don't have an override to force cpp to run a program with a different user level.

**Comment by sariyn** [comment]
Got it, thanks!  Will look forward to the integrated terminal in that case.

**Comment by pieandcakes** [comment]
@Sariyn The integrated terminal feature is available in our 0.20.0 version of the extension. To use the integratedTerminal, set `externalConsole` to false in your `launch.json`.
