### ISSUE TITLE
Too resource intensive. (probably a duplicate, ignore)

### ISSUE THREAD

**Issue by sudosteve** [microsoft/vscode-cpptools#2551]
Type: General
**Input information below**

Uses 60%+ of my 2012 macbook pro cpu and causes the temperature to be 10 degrees higher than it is with the extension uninstalled

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by sean-mcmanus** [comment]
@sk8ersteve You could try setting the C_Cpp.workspaceParsingPriority to "low" (or do Pause Parsing, if the database icon in the bottom right is showing), and/or the intelliSenseEngine to "Tag Parser" or "Disabled". Removing the "**" from your includePath in c_cpp_properties.json may also help (if the red flame is showing too long).
