### ISSUE TITLE
Outline won't highlight corresponding function entry when clicking inside C function body in editor

### ISSUE THREAD

**Issue by lijh8** [microsoft/vscode-cpptools#2556]
Outline won't highlight corresponding function entry when clicking inside C function body in editor, while the status bar at the bottom can show the corresponding function prototype in its C/C++ Navigation.

If vscode can deal with big files and provide both file and project wide outlines (symbol lists) with performance as good as Source Insight, it can replace the later source code editor for lots of people on more operating systems.

- VSCode Version: 1.27.2
- OS Version: macOS 10.14
- Extension: ms-vscode.cpptools
- C/C++ Extension Version: 0.18.1

![screenshot20180925at8 33 28pm](https://user-images.githubusercontent.com/9011764/46016034-4c5e1980-c106-11e8-87d5-bb15989f6f31.png)

**Comment by sean-mcmanus** [comment]
This is being tracked with https://github.com/Microsoft/vscode-cpptools/issues/2230 . The symbols we send back to VS Code don't have a range associated with them yet. They updated their API.
