### ISSUE TITLE
Switching a source files language from C to C++ (or the reverse) switch the Iangauge used by IntelliSense

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2557]
It looks like the language is being cached for a particular file and doesn't update after the language changes. This is most likely a regression from a few updates ago when the code was refactored.

I hit this while investigating https://github.com/Microsoft/vscode-cpptools/issues/2545 .

**Comment by bobbrow** [comment]
@Colengms can you check if this is still an issue?
