### ISSUE TITLE
go to definition does not work in ubuntu 12.04

### ISSUE THREAD

**Issue by FangLiangQiang** [microsoft/vscode-cpptools#256]
in my ubuntu12.04 ,go to definiton does not work,but in my win7 ,it can work .

**Comment by maixuanhan** [comment]
Same here on 14.04. I have lately updated both VS Code and CppTools ext. I don't know which causes the problem. Previous, everything is OK.

**Comment by joewood** [comment]
Seeing this too. On Ubuntu 16.

**Comment by sean-mcmanus** [comment]
We don't currently support Ubuntu 12 (although there are workarounds to get it to work), but I'm not reproing this on supported Linux platforms. Is the file saved as a C++ file? Do any other features like Format Code work? Is Microsoft.VSCode.CPP.Extensions.linux running?

**Comment by joewood** [comment]
File is saved as .cpp file.  Yes the extension is running.

**Comment by sean-mcmanus** [comment]
I'm observing Go to Definition failing in the non-"open folder" scenario on Ubuntu 14, but it starts to work after I open a folder. Is that what you see? Strangely, the open file scenario is working on my other Linux machine.

**Comment by joewood** [comment]
Killing the process -9 and restarting vs code seems to have fixed the issue. Maybe I had a zombie hanging around.

**Comment by yiwuzihui** [comment]
On 32 bit Ubuntu either 12 or 14, 'go to definition' feature doesn't work. It failed to create '.vscode' folder and '.BROWSE.VC.DB’ on my 32 bit Ubuntu virtual machine. But it does work on my friend's 64 bit Ubuntu system.

**Comment by sean-mcmanus** [comment]
Our extension binaries for Linux are 64-bit, so they won't run on 32-bit Linux. The latest version won't create the .BROWSE.VC.DB in the .vscode folder, but it should launch a Microsoft.VSCode.CPP.Extension.linux process.

**Comment by bobbrow** [comment]
Thank you for your feedback.  We are tracking the 32-bit Linux issue with issue #424 and support for older Linux distros (without GLIBC 2.18) with issue #19.

**Comment by sean-mcmanus** [comment]
Should work now with 0.14.4.
