### ISSUE TITLE
Go to Definition on a #include path doesn't use the IntelliSense info

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2564]
It should go to the definition that is actually being used by the current translation unit (i.e. not showing all the files that match the include path).

**Comment by sean-mcmanus** [comment]
It looks like this will be fixed via invoking the new `#include` completion at the end of the `#include`.

**Comment by sean-mcmanus** [comment]
@bobbrow Users are frequently hitting this . It makes them think their project isn't configured correctly when it is. See all the linked issues.

**Comment by bobbrow** [comment]
We should move this into the next release then.

**Comment by ghuser404** [comment]
This works, but may be too slow at times. Sometimes it takes 30 seconds to jump into correct header. Is anything being done about IntelliSense performance?

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
