### ISSUE TITLE
Highlighting matching conditional preprocessor statements #ifdef/#endif

### ISSUE THREAD

**Issue by DABH** [microsoft/vscode-cpptools#2565]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Debian 9
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.18.1
- Other extensions you installed (and if the issue persists after disabling them): Python
- A clear and concise description of what the bug is.

I have two nested #ifdef's in a cpp file.  The highlighting when I click on them to see matching #ifdef's seems wrong (it highlights the wrong pairs).

**Expected behavior**

As you can see in the screen recording, the two #endif's match, when it should be that the #ifndef matches with the first #endif and the #ifdef matches with the second #endif.

**Screenshots**

Here is a screen recording: https://streamable.com/rik4y

**Additional context**

Happy to provide any other useful info!  Thank you!

**Comment by sean-mcmanus** [comment]
Yeah, our reference highlighting code only works on code items and not preprocessor keywords like #ifdef/endif -- we would have to check the current token and find the matching begin/end token.

**Comment by Colengms** [comment]
This should be possible to support by leveraging the results of code folding.  We could cache those results (perhaps just S_BM_IFDEF and possibly S_BM_REGION range types), and document highlight could use that to look up the locations of corresponding start/end positions.

**Comment by sean-mcmanus** [comment]
This is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders2
