### ISSUE TITLE
Intellisense and avr-gcc

### ISSUE THREAD

**Issue by bergeo** [microsoft/vscode-cpptools#2567]
**Type: LanguageService**

- OS and Version: Windows 10
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.18.1

I'm using vscode and the cpptools for software developement for AVR microcontrollers using avr-gcc as a compiler.
Intellisense in vscode works just fine until i introduce a variable which should live in the flash of the microcontroller using the attribute `__flash` as in `const __flash uint8_t font_5x8[2][5]`.
This completely breaks intellisense and yields a lot of errors, see screen-shots below.
before:
![before](https://user-images.githubusercontent.com/8605010/46139865-ee3d4d80-c24f-11e8-821d-0395002d6797.PNG)
after:
![after](https://user-images.githubusercontent.com/8605010/46139909-01501d80-c250-11e8-9278-f970bdbebcf4.PNG)

Any help is highly appreciated.

regards,
Georg

**Comment by bobbrow** [comment]
One way to get IntelliSense to skip over non-standard attributes that it doesn't understand is to add them to the `"defines"` array in your `c_cpp_properties.json` configurations so that they are replaced by whitespace by our parser:

```
   {
        "name": "Win32",
        ...
        "defines": [ "__flash=" ],
        ...
    }
```

**Comment by bergeo** [comment]
Thank's Bob, that fixes the issue for the Moment :-)

Cheers,
Georg
