### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by miniyuan** [microsoft/vscode-cpptools#2568]
Type: Debugger
**Input information below**
Debug adapter process has terminated unexpectedly
**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:windows 2008x64 r2
- VS Code Version:1.26
- C/C++ Extension Version:cpptools 0.18.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
F5 start debugging, failed and notice : 
Debug adapter process has terminated unexpectedly

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "program": "${workspaceRoot}\\src\\main.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": {
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            },
            "windows": {
                "program": "${workspaceRoot}\\src\\main.exe",
                "MIMode": "gdb",
                "miDebuggerPath": "C:\\tools\\i686_w64_mingw32\\bin\\gdb.exe" // Path to gdb on windows
            }
        }
    ]
}
**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by pieandcakes** [comment]
@miniyuan Can you post your output from the `debugConsole`? this should give you why its terminating unexpectedly. Also, which version of MinGW32 are you running?

**Comment by miniyuan** [comment]
MinGW.org GCC-6.3.0-1
GNU gdb (GDB) 7.6.1
the debugConsole is no anything output!

**Comment by miniyuan** [comment]
> @miniyuan Can you post your output from the `debugConsole`? this should give you why its terminating unexpectedly. Also, which version of MinGW32 are you running?
MinGW.org GCC-6.3.0-1
GNU gdb (GDB) 7.6.1
the debugConsole is no anything output!

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
