### ISSUE TITLE
my VSCode can't include "conio.h"

### ISSUE THREAD

**Issue by YousefSaber** [microsoft/vscode-cpptools#2569]
my VSCode can't include conio.h although I've included the include file path 

elementary OS v0.4.1 Loki

VSCode v1.27.2

C/C++ extension v0.18.1

![image](https://user-images.githubusercontent.com/33742499/46163298-19915e00-c28b-11e8-93b3-459411fcd0cc.png)

![image](https://user-images.githubusercontent.com/33742499/46163329-3037b500-c28b-11e8-9de4-570eaf7df090.png)

```
`joseph@joseph-G31M-ES2L:~$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
```
joseph@joseph-G31M-ES2L:~$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`
```

**Comment by bool3max** [comment]
Uhh `conio.h` is not a standard header file. It's a MS-DOS era header file, provided by MS-DOS compilers, yet you're running linux. Are you sure you actually have it on your system?

**Comment by YousefSaber** [comment]
@bool3max I don't know

**Comment by sean-mcmanus** [comment]
@YousefSaber Why are you trying to include conio.h, i.e. what code do you want to use from that? It could be located in another header file. Where does the file exist on your file system?

**Comment by YousefSaber** [comment]
I'll try something else I'll close this thread for now
