### ISSUE TITLE
gdb(msys2) on windows cannot find source

### ISSUE THREAD

**Issue by Yienschwen** [microsoft/vscode-cpptools#257]
VSCode version: 1.5.3
OS: Windows 10 1607
Debugger: gdb, in MSYS 2

Source code is stored in the same location as it was compiled from, `gdb` runs normally, but debugger cannot find my source code. Source viewer outputs 

<pre>
Source \home\Yienschwen\gdbTest\main.cc is not available.
</pre>

The path is actually the same path in MSYS2 environment. So is there a way to map the source code lookup path? Or to specify the path of `cygpath` when using `gdb`?

**Comment by jacdavis** [comment]
Thanks for reporting this. 

The issue is vscode sees the windows view of the file system. AFAIK, msys2 does not work with cygpath, but msys2 isn't one of currently tested platforms, so I'm not entirely sure. We can take this as a feature request to support msys2 on windows. 

In the meantime, manual source mapping is on our backlog, but hasn't yet been shipped. This would allow someone to specify a replacement for a path. In the case above, it would likely replace \home with something relative to the windows view of the file system.

**Comment by jhasse** [comment]
I'm using this extension since a few months with MSYS2 and it works fine. I can't test the current version because of #233, but I will try to reproduce your problem with >0.9.2 soon.

**Comment by jhasse** [comment]
Okay I've got the C++ extension working again under Windows and tested debugging with MSYS2: Everything works fine for me.

Maybe it's your build system which inserts the paths in the wrong format? Have you added `"miDebuggerPath": "C:\\msys64\\mingw64\\bin\\gdb.exe"` to `launch.json`?

**Comment by jacdavis** [comment]
@jhasse, how are you compiling? Is gcc running such that it is seeing windows style paths or virtualized unix style paths? It seems the original poster is getting unix style paths compiled into symbols: "\home\Yienschwen\gdbTest\main.cc". VSCode expects windows paths. On Cygwin, we use cygpath to map from virtualized unix paths to windows paths, but we haven't investigated anything like that for mingw.

**Comment by JoyBinY** [comment]
VSCode version: 1.15.0
OS: Windows 10 1511
Debugger: gdb, in MSYS 2
add path like this in the **launch.json** file
`"sourceFileMap": {
                "/H/Code/Develop_code/server": "H:/Code/Develop_code/server"
            },`
BTW work slowly.. ...

**Comment by Knagis** [comment]
Thanks @JoyBinY - that setting does work, in my case I added a more universal setting:

```
            "sourceFileMap": {
                "/c/": "c:/",
                "/d/": "d:/",
                "/e/": "e:/",
                "/f/": "f:/"
            },
```

**Comment by jhasse** [comment]
> how are you compiling?

With MinGW64 from MSYS2.

**Comment by JoyBinY** [comment]
With GCC from MSYS2
Target : i686-pc-msys

**Comment by jhasse** [comment]
> Target : i686-pc-msys

Does that mean with the MSYS2 shell (and not the MinGW32/64 shell)?

**Comment by JoyBinY** [comment]
yes, here i use the msys-gcc which installed by using command `pacman -S gcc`. 
msys-gcc is difference from msys-gcc which is installed by [mingw-get-setup.exe](https://sourceforge.net/projects/mingw/files/latest/download?source=files) .
Using `gcc -v` can show more information,  and you can find "Target : i686-pc-msys" there

**Comment by jhasse** [comment]
I mean MinGW from MSYS2 which is placed in C:/msys64/mingw64/bin/gcc.exe for example. This will get used if you open the MinGW64 shell shortcut.

**Comment by pieandcakes** [comment]
This is an older issue and hasn't had any updates. Please comment/open a new issue if it is still happening.

**Comment by keuin** [comment]
> Okay I've got the C++ extension working again under Windows and tested debugging with MSYS2: Everything works fine for me.
> 
> Maybe it's your build system which inserts the paths in the wrong format? Have you added `"miDebuggerPath": "C:\\msys64\\mingw64\\bin\\gdb.exe"` to `launch.json`?

I am getting the wrong path if I set `miDebuggerPath` to `gdb`, which is present in my `PATH` environment variable. However, after replacing it with its absolute path (`C:\msys64\mingw64\bin\gdb.exe`), this problem gets fixed. Not sure why this happens, just a reminder for people who have encountered this problem as well.

**Comment by ChrisIdema** [comment]
@keuin 
An absolute path for GDB doesn't work for me. I tried both `"miDebuggerPath": "C:\\msys64\\usr\\bin\\gdb.exe"` and `"miDebuggerPath": "C:/msys64/usr/bin/gdb.exe"`. Both result in distorted paths for files that are debugged.

**Comment by keuin** [comment]
> @keuin An absolute path for GDB doesn't work for me. I tried both `"miDebuggerPath": "C:\\msys64\\usr\\bin\\gdb.exe"` and `"miDebuggerPath": "C:/msys64/usr/bin/gdb.exe"`. Both result in distorted paths for files that are debugged.

Here is my `launch.json` and `tasks.json`:

## launch.json

```json
{
    "configurations": [
        {
            "name": "(gdb) 启动",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/main.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\msys64\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "将反汇编风格设置为 Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        },
        {
            "name": "C/C++: gcc.exe 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\msys64\\usr\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "将反汇编风格设置为 Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: gcc.exe 生成活动文件"
        }
    ],
    "version": "2.0.0"
}
```

## tasks.json

```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc.exe 生成活动文件",
            "command": "C:\\msys64\\usr\\bin\\gcc.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "编译器: C:\\msys64\\usr\\bin\\gcc.exe"
        },
        {
            "type": "cppbuild",
            "label": "C/C++: clang.exe 生成活动文件",
            "command": "C:\\msys64\\usr\\bin\\clang.exe",
            "args": [
                "-fcolor-diagnostics",
                "-fansi-escape-codes",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
            "detail": "调试器生成的任务。"
        }
    ],
    "version": "2.0.0"
}
```


Hope these will help you.

**Comment by ChrisIdema** [comment]
> I found that when using "C:\\msys64\\mingw64\\bin\\gdb.exe", it works without any problem.

My bin folder has no executable. Only DLL files.

**Comment by sean-mcmanus** [comment]
C:\\msys64\\usr\\bin\\gcc.exe" may not be executable on Windows? If C:\msys64\mingw64\bin doesn't have executables, then msys/mingw isn't installed correctly.

**Comment by ChrisIdema** [comment]
@sean-mcmanus 
I've reinstalled mingw64 and gdb for msys2 and this solved the issue.
