### ISSUE TITLE
Extension Problem

### ISSUE THREAD

**Issue by callG** [microsoft/vscode-cpptools#2578]
- Extension Name: cpptools
- Extension Version: 0.19.0
- OS Version: Windows_NT x64 10.0.17744
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 368,
		"activateCallTime": 15,
		"activateResolvedTime": 585,
		"activationEvent": "onLanguage:cpp"
	}
}
```

**Comment by WardenGnaw** [comment]
@callG I could not find anything in the VSCode docs about the `"activationTimes"` object for VSCode's package.json.

Can you provide a link from https://code.visualstudio.com/docs/ about the reason for including the data provided?

**Comment by bobbrow** [comment]
This looks like an issue saying that we're too slow to activate the extension.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
