### ISSUE TITLE
Why VSC shows that my 

### ISSUE THREAD

**Issue by Jaxx4Fun** [microsoft/vscode-cpptools#258]
Updating C/C++ dependencies...
Failed at stage: getPlatformInfo
and the rest is unreadable code. I saw a similar question but I don't think there is a solution for me.
Plz tell my what to do      . T T.
![image](https://cloud.githubusercontent.com/assets/10000619/18872764/b188bfc8-84ee-11e6-85da-36e2d935f302.png)

**Comment by Jaxx4Fun** [comment]
fine, i have already find the solution!
Just put （c:\Windows\System32\wbem）into PATH. 
Thanks for this web:
http://qiita.com/unapuyo/items/fa3d09b459701543a63c

**Comment by sean-mcmanus** [comment]
The next release will skip the non-essential wmic call if it's not found. Maybe we could try other paths when trying to launch wmic?

**Comment by C-F-4** [comment]
Thatnks @Johnny4Fun  it works!
Just added "C:\Windows\System32\wbem" to the path and it went on to successfully install the dependencies.

Although, the weird thing is the extension worked fine on Windows 10 PC where the path didn't had "C:\Windows\System32\wbem" included, but didn't work on my Windows 7 laptop.
