### ISSUE TITLE
Context menu items and its translation

### ISSUE THREAD

**Issue by oktonion** [microsoft/vscode-cpptools#2580]
- Extension Name: cpptools
- Extension Version: 0.19.0
- OS Version: Windows 10
- VSCode version: 1.27.2

I have not found where to contribute translations for this extension, but from the very beginning cpptools had the strings in context menu that are not translated in Russian and it's bugging me:

| Original string      	| Russian translation                    	|
|----------------------	|----------------------------------------	|
| Switch Header/Source 	| Переключить заголовочный/исходный файл 	|
| Navigate...          	| Перейти к...                           	|
| Go to Declaration    	| Перейти к объявлению                   	|
| Peek Declaration     	| Показать объявление                    	|

Furthermore I can not quite understand why there is Peek Declaration option instead of Peek Definition as it is in Visual Studio IDE.

This is what it looks like.

![default](https://user-images.githubusercontent.com/27406278/46261129-f1f2fd80-c4f7-11e8-8a11-0098be3cade1.jpg)

**Comment by WardenGnaw** [comment]
Context menu translations are in the VSCode Repo. 

You may be able to find where to add translations somewhere in https://github.com/Microsoft/vscode/tree/4e4e6f9b44dd9e6a53d1f08565c52b8ea9f61a5e/i18n/rus.

Moved to https://github.com/Microsoft/vscode/issues/59701

**Comment by bobbrow** [comment]
Andrew, these are our menu items, not VS Code's.  We haven't done the translation work yet (one of a few remaining reasons our extension is still in "preview" mode).  #7 will cover this.

**Comment by oktonion** [comment]
@bobbrow I see... so what about 

> Furthermore I can not quite understand why there is Peek Declaration option instead of Peek Definition as it is in Visual Studio IDE.

**Comment by sean-mcmanus** [comment]
@oktonion Go to (Peek) Declaration is a separate C/C++ only feature. It will go to the declaration instead of the definition. For example,

int func();

int func() {}

…
retrun func(); // Go to Declaration will go to the declaration at the top instead of the definition that comes afterwards.

**Comment by bobbrow** [comment]
I can't read Russian, but both options should exist:
![image](https://user-images.githubusercontent.com/12818240/46312158-180cb200-c579-11e8-91fb-6162da490965.png)

**Comment by bobbrow** [comment]
Sorry, I was holding the CTL key while trying to type a newline and my comment was sent prematurely.  I updated the previous with a screenshot showing both options available.

**Comment by oktonion** [comment]
@sean-mcmanus I totally understand the difference between Declaration/Definition. It seems odd that Go to/Peek Definition is translated and same for Declaration is not. I'm just kinda comparing cpptool+VS Code to Visual Studio IDE and its features (this may be wrong but cpptools will not escape that comparison, you know). Now I feel that this is out of topic and I will be patiently waiting for updated translation for one of the most useful extensions for VS Code.

@bobbrow thank you for clear explanations. It's a bit confusing that cpptools has both Definition/Declaration options but this is handy. So as I said - will be waiting for updated translation.

**Comment by bobbrow** [comment]
We are simply aligning with Visual Studio IDE by providing both Definition/Declaration options.

For context, the reason Goto Definition is translated is because VS Code itself provides that string since the feature applies to pretty much all languages.  Goto Declaration is a less common language need, so the string is provided by our extension which has not yet been localized.
