### ISSUE TITLE
Go to definition where defined outside of TU is broken if Intellisense Engine Fallback is disabled

### ISSUE THREAD

**Issue by captainparticles** [microsoft/vscode-cpptools#2583]
As a side effect of https://github.com/Microsoft/vscode-cpptools/issues/2536 where the tag parser is now used for symbol navigation if the symbol is defined outside the current TU, if Intellisense Engine is set to default, and Intellisense Engine Fallback is set to disabled then symbol navigation is broken. 

VS Code will report "No definition found" although manual symbol navigation (ctrl+p) will still work.

**Comment by sean-mcmanus** [comment]
Ah, we're not falling back to the tag parser if IntelliSense isn't able to find the symbol.

**Comment by bobbrow** [comment]
Quick note, we should probably only do this fallback if there are unresolved `#include`s.  The absence of such an error would indicate that we should not do a global symbol search.

**Comment by sean-mcmanus** [comment]
Okay, that sounds good.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/Microsoft/vscode-cpptools/releases/download/0.19.1-insiders/cpptools-win32.vsix .
