### ISSUE TITLE
Empty C_Cpp.default.compilerPath/includePath doesn't work

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2584]
Using

    "C_Cpp.default.compilerPath": "",
    "C_Cpp.default.includePath": []

isn't working as expected. Do any other users care about this bug?

**Comment by rei2hu** [comment]
I'll try to do this.

~~Edit: I'm not sure what's wrong with `"C_Cpp.default.includePath": []`. When I provide it in `.vscode/settings.json`, I see the configuration have an empty array which I assume is correct.~~

**Comment by bobbrow** [comment]
I actually started a branch with a fix for this yesterday. I just didn't have time to test it.
https://github.com/Microsoft/vscode-cpptools/tree/bobbrow/bug2584

**Comment by rei2hu** [comment]
That's good, I already closed my PR.

I tested your branch and it seems to be working so far.
