### ISSUE TITLE
pickRemoteProcess SSH command variable local expansion bug

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2585]
While testing an attach type debugger configuration with SSH as pipeTransport on macOS/VSCode and remote target is Ubuntu Linux I found out that the pickRemoteProcess command will pick and expand the local $(uname) value instead of the remote one so the "if" statement will execute the "Darwin" "ps" command on the remote Linux target which will fail because of unsupported Linux ps command options

    Command failed: "/usr/bin/ssh" "-i" "/Users/xxxx/.ssh/xxx_id_rsa" "xxx@xxxx" "sh -c 'uname && if [ $(uname) = "Linux" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) = "Darwin" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi'"
    error: can not use output modifiers with user-defined output

    Usage:
    ps [options]

    Try 'ps --help <simple|list|output|threads|misc|all>'
    or 'ps --help <s|l|o|t|m|a>'
    for additional help text.

    For more details see ps(1).

You just need to escape any variables inside the SSH command with a backslash `"\"` 
so it's not expanded locally

    "sh -c 'uname && if [ \$(uname) = "Linux" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ \$(uname) = "Darwin" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi'"

- OS and Version: macOS 10.14
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.19.0

**Comment by ghost** [comment]
Also using single quotes for ssh command should prevent local expansion

`"/usr/bin/ssh" "-i" "/Users/xx/.ssh/xxx_id_rsa" "xxx@xxx" 'sh -c "uname && if [ $(uname) = "Linux" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) = "Darwin" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi"'`

Currently I'm only using ssh as "pipeProgram" for attaching so I made the change in attachToProcess.js and it's working fine for me 
but I'm pretty sure the literal $(uname) will break attaching with other types of "pipeProgram"


~/.vscode/extensions/ms-vscode.cpptools-0.19.0/out/src/Debugger/attachToProcess.js

```
const command = `sh -c 'uname && if [ \\$(uname) = "Linux" ] ; then ${nativeAttach_1.PsProcessParser.psLinuxCommand} ; elif [ \\$(uname) = "Darwin" ] ; ` +
            `then ${nativeAttach_1.PsProcessParser.psDarwinCommand}; fi'`;
```

**Comment by ghost** [comment]
I'm sorry but this quoting horror is not over yet
The command is failing with the double single quotes after "fi"

`"/usr/bin/ssh" "-i" "/Users/xx/.ssh/xx_id_rsa" "xx@xx.xx.com" 'sh -c 'uname && if [ $(uname) = "Linux" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) = "Darwin" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi''`

`/bin/sh: -c: line 1: syntax error: unexpected end of file`

I'm still using literal \\$(uname) and double quoted "${command}" in attachToProcess.js to make it work

**Comment by sean-mcmanus** [comment]
Should be fixed with the latest insiders: https://github.com/Microsoft/vscode-cpptools/releases
