### ISSUE TITLE
Please use the latest version of vscode-extension-telemetry dependency

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-cpptools#2587]
This C++ extension uses version 0.0.11 of `vscode-extension-telemtetry`  module.

The latest version of `vscode-extension-telemtetry` module (0.0.22) uses the latest version of `applicationinsights` module (1.0.5) which has the fix to prevent unnecessary patching of the require and other 3rd party modules. 

For more details, please see https://github.com/Microsoft/vscode-extension-telemetry/issues/16

**Comment by ramya-rao-a** [comment]
@sean-mcmanus, @bobbrow I see that a PR was merged to use 0.0.22 version. Unfortunately, we recently learned of an issue where there are multiple powershell processes being spawned and stay stuck on older Windows versions when using version 1.0.5 of `applicationInsights` module.

This [bug](https://github.com/Microsoft/ApplicationInsights-node.js/issues/438) has been fixed in  version 1.0.6 of `applicationInsights` module which is being used by version 0.1.0 of `vscode-extension-telemtetry`

Therefore, please update the version of `vscode-extension-telemetry` dependency to 0.1.0

**Comment by sean-mcmanus** [comment]
Thanks for letting us know. We've only shipped with the changes with our Insider builds so far, so we should be able to fix this for our release version.

**Comment by sean-mcmanus** [comment]
@ramya-rao-a Updating to the new vscode telemetry API is truncating our telemetry to 1000 characters. Our previous limit was 16384 characters. How can we increase the data limit for these particular cases that we need longer data? It looks like the regression started with 1.0.6 of applicationsInsights.

**Comment by sean-mcmanus** [comment]
This looks like bug https://github.com/Microsoft/ApplicationInsights-node.js/issues/444 . What version of vscode-extension-telemetry should we use? We're missing telemetry data which may be important so we'd like to switch to an older version.

**Comment by OsvaldoRosado** [comment]
Adding a note that even after a bugfix you shouldn't have a limit of 16K. The schema defined limit on custom dimension values is 8K, anything beyond this _should_ be dropped by the telemetry ingestion endpoint. You should consider using a telemetry type designed for large data storage, like trace, rather than custom dimensions.

**Comment by ramya-rao-a** [comment]
> You should consider using a telemetry type designed for large data storage, like trace, rather than custom dimensions.

@OsvaldoRosado Can you elaborate on this?

@sean-mcmanus You can use 0.0.22 version of the vscode-extension-telemetry

**Comment by OsvaldoRosado** [comment]
@ramya-rao-a Custom dimensions aren't intended for storing large amounts of data. Very long strings will not be accepted by our backend. The SDK truncates to avoid the backend dropping your telemetry entirely.

If long strings must be stored in telemetry, use `trackTrace` rather than putting the string in a custom dimension. Trace telemetry has a 32K length limit on its message field, rather than the 8K limit on custom dimension properties. https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/MessageData.bond#L13

**Comment by sean-mcmanus** [comment]
@OsvaldoRosado Yeah, 8k is fine for us. I don't think we need to increase it beyond that. We can change our code to self-truncate to 8k instead of 16k.

**Comment by ramya-rao-a** [comment]
>  We've only shipped with the changes with our Insider builds so far, so we should be able to fix this for our release version.

@sean-mcmanus How does one get to use your Insiders build?

**Comment by sean-mcmanus** [comment]
@ramya-rao-a If you use VS Code Insiders you should default to an Insiders C/C++ build, if one exists, or you can set the C_Cpp.updateChannel to "Insiders". You could also install an insider vsix manually from https://github.com/Microsoft/vscode-cpptools/releases . We plan to release a new insiders build later this week.

Let us know when the 1k limit is fixed so we can switch back to the newer API.

**Comment by ramya-rao-a** [comment]
So at present, the Insiders version is using 0.0.22 version of vscode-extension-telemetry? What about the stable version?

**Comment by sean-mcmanus** [comment]
@ramya-rao-a The 0.20.1 release version is using 0.0.22. I don't know what Insider version you're referring to. The previous 0.19.1-insiders3 used the newer version which had the 1k bug. We don't have any "active" insider release published yet.

**Comment by ramya-rao-a** [comment]
Thanks @sean-mcmanus 

With the current released version of the extension, users are seeing the issue mentioned in https://github.com/Microsoft/vscode-cpptools/issues/2587#issuecomment-432479898

There are a couple of options before us
- AppInsights releases a new version with the fix for the 1k bug. I release a new version of vscode-extension-telemetry module which you then use in the new version of the C++ extension
- You use an older version of the vscode-extension-telemetry module which uses an older version of applicationInsights which doesnt have the powershell issue

Either way, we will need a new version of the C++ extension

**Comment by sean-mcmanus** [comment]
@ramya-rao-a We recently added filtering to our telemetry which should reduce the character usage, such that I believe we can switch to the newer version even with the 1k limit and still get the data we require in most cases, so I'll change it back; however, our next 0.21.0-insiders release has major parser changes that we didn't want to ship in a release version until it has been tested more. What timeframe did you want this telemetry change to be pushed to a release version?

**Comment by ramya-rao-a** [comment]
Since users are seeing the issue when using the C++ extension, it is up to you to decide when you want to ship the change.

Do you have a way for users to get an older version of the extension? If yes, then providing a vsix for the users who see this issue can be one way of mitigating this issue until you release the next version

**Comment by sean-mcmanus** [comment]
Yeah, can you tell users who complain about this to use https://github.com/Microsoft/vscode-cpptools/releases/download/0.20.0/cpptools-win32.vsix ? I haven't seen users complaining about this. And we should have 0.21.0-insiders soon as well.

**Comment by sean-mcmanus** [comment]
@ramya-rao-a Actually, on closer inspection, important info is still getting cutoff with 1k characters (i.e. 2k characters might be enough), so we don't want to upgrade the telemetry API yet. Do you have any telemetry on now many Win7 users are hitting this powershell problem?

**Comment by ramya-rao-a** [comment]
We dont have any telemetry. Just the main issue https://github.com/Microsoft/vscode/issues/60585#issuecomment-436766501 where one user has the problem. But I am guessing there should be more.
