### ISSUE TITLE
Change description of this repo

### ISSUE THREAD

**Issue by jhasse** [microsoft/vscode-cpptools#259]
The description on GitHub still says "C++ sample applications used in blog posts and demos". This should be changed to something like "Microsoft C/C++ extension for Visual Studio Code".

**Comment by sean-mcmanus** [comment]
I agree. Same as https://github.com/Microsoft/vscode-cpptools/issues/237 . Not sure what the status is.

**Comment by delmyers** [comment]
Fixed.
