### ISSUE TITLE
No intellisense: Include folders not being read

### ISSUE THREAD

**Issue by izackp** [microsoft/vscode-cpptools#2594]
**Describe the bug**
- OS and Version: Windows 10 Home - 17134.165
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.19

Intellisense does not work as well as any static code analyzing features.

My configuration file looks like this:
```
{
    "configurations": [
        {
            "name": "Win32",
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17134.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}\\src"
                ],
                "limitSymbolsToIncludedHeaders": false,
                "databaseFilename": "${workspaceFolder}/.vscode/vc.db"
            }
        }
    ],
    "version": 4
}
```

Logs:
```initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Error squiggles are enabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
cpptools/queryCompilerDefaults
Attempting to get defaults from compiler found on the machine: 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe'
cpptools/didChangeFolderSettings
Attempting to get defaults from compiler found on the machine: 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe'
Code browsing service initialized
Attempting to get defaults from compiler found on the machine: 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe'
  Unable to retrieve file system information for C:\engine\engine\src. error = -1
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.14.26428/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.14.26428/ATLMFC/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/UM/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/UCRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/SHARED/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/WINRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/CPPWINRT/ will be indexed
Discovering files...
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.14.26428/INCLUDE
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.14.26428/ATLMFC/INCLUDE
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/UM/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/UCRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/SHARED/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/WINRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17134.0/CPPWINRT/
  Discovering files: 4646 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populate include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
```

I have a feeling that it has something to do with the plugin not being able to read any of my specified include directories.
```Unable to retrieve file system information for C:\engine\engine\src. error = -1```

- I've tried several variations in cpp_properties.json
- I've tried changing the compiler to mingw64

If I add a database path then I get a large number of errors in the log:
```Unable to add file to database, error = 0x8064000e: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\VC\TOOLS\MSVC\14.14.26428\INCLUDE\AMMINTRIN.H```

Even with different projects and I end up with the same issue.

**Comment by sean-mcmanus** [comment]
Does "C:\engine\engine\src" exist? We just call _wstat64 and it appears to be failing for that path.

**Comment by izackp** [comment]
![explorer_2018-10-03_06-46-37](https://user-images.githubusercontent.com/2636382/46406020-2b825f00-c6d8-11e8-831d-722d3fd5961e.png)

It does indeed exist. 

I was actually able to finally get it to work by disabling the case sensitivity on the folder
```fsutil.exe file SetCaseSensitiveInfo C:\engine\engine disable```

It looks like this issue might be the same as #2367 but the workaround of adding a '/' directory as an include directory didn't work. I'll try it again and see if that fixes it.

**Comment by izackp** [comment]
- Adding "/" as an include path didn't work
- Changing includePath to "/engine/engine/src" didn't work
- Adding "/" to browse.path just made the plugin start scanning my whole C drive
- Adding "/" to browse.path didn't work
- Changing browse.path to "/engine/engine/src" didn't work

I also tried variations with /c/ and /mnt/c/

Only real solution so far was to disable to case sensitivity on the root folder.

**Comment by bobbrow** [comment]
The linux-style paths (and case-sensitive files) only work when you set the compilerPath to a WSL compiler (e.g. "/usr/bin/g++").  We have an issue open to add a setting to support case-sensitive filesystems in non-WSL scenarios and I would recommend you upvote it so we can keep track of the demand.

#1994
