### ISSUE TITLE
Go to definition issue and issue with autocomplete

### ISSUE THREAD

**Issue by felkar123** [microsoft/vscode-cpptools#260]
Go to definition in a function to a local variable does not work. In longer functions, it is necessarily to have reference to local variables.

Autocomplete should offer a list of variables that are in structure, on the top of list after typing a period "."

There is also a strange coloring in a .h file. If you type a bracket in a definition, then the text that follows will color in to blue. In a syntax like this:
# define definition value(250) // This comment and every thing that follow is colored in blue

**Comment by sean-mcmanus** [comment]
Thanks for reporting this.
1. I'm reproing the "go to definition" issue with local variables. It doesn't appear to be a regression from 0.9.1. We'll investigate.
2. I don't understand what bug you're reporting about the auto-complete, but in general we are working on make the auto-complete on-par with the VS behavior. Can you explain what behavior you're expecting?
3. I'm not able to repro the colorization issue. It's possible other extensions are causing this or the repro needs more text.

**Comment by felkar123** [comment]
1. Thank you, that would be nice
2. It's not a bug, but it's about user experience and it helps to write the code faster. When you type an instance of a structure and then type the period or an arrow "->" for pointers, auto-complete should offer you just the variables that are declared in that structure. 
   Please refer to eclipse CDT extension. It has everything that an extension for C/C++ language needs.
3. I will look if it's a problem of other extensions

**Comment by sean-mcmanus** [comment]
Yes, our team is working on \# 2.

**Comment by sean-mcmanus** [comment]
\# 1 is also currently "by design" (we currently don't parse inside functions), but we're working on implementing the feature.

**Comment by bobbrow** [comment]
\# 1 is being tracked by issue #255 
\# 2 is being tracked by issue #13 
\# 3, I believe, was an issue with the C++ colorization grammar which has since been fixed.  Please let us know if you still see this with the latest version of VS Code and our extension.  I do not see this issue.

I will be closing this issue since I think we're tracking everything that needs to be tracked.  Thanks for your feedback.

**Comment by sean-mcmanus** [comment]
@felkar123 0.19.0 implements Go to Declaration with local variables (and the autocomplete was implemented a while ago).
