### ISSUE TITLE
undefined reference to `std::cout' using

### ISSUE THREAD

**Issue by tcroots78** [microsoft/vscode-cpptools#2605]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 (bootcamp on Mac)
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.19.0
- Other extensions you installed (and if the issue persists after disabling them): WPILib (beta, yes, persists after disable)
- note, Using [FRC Toolchians](http://first.wpi.edu/FRC/roborio/toolchains/ ) for compiler 

I work with my son's robotics team and am new to c++. I'm trying to get a hello world program up and compiled a la [VS Code Setup](https://code.visualstudio.com/docs/languages/cpp). It worked fine in OSX.

When I run the build, I get errors like: HelloWorld.cpp:6: undefined reference to `std::cout'

When I generated c_cpp_properties.json I was initially getting intellisence errors. Tried a bunch and read over [Issue 1041](https://github.com/Microsoft/vscode-cpptools/issues/1041) and ended up changing the compilerPath to point to FRC GCC and Intellisense worked :)

But then I'm getting the build errors. It worked perfect on OSX side, but I think I have clang installed for xcode there in addition to the toolchains. And pretty sure it just used that to compile. 

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath":     "C:\\frc\\bin\\arm-frc-linux-gnueabi-gcc.exe",
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 4
}
```

Note:
I just tried regenerating it and it nothing past the UNICODE spot except `"intelliSenseMode": "msvc-x64"` ...which seems weird. I'm not sure all the steps I did to get to the final product above :(

for information, typically we're using gradle to build the robot code, similar to issue [Issue 2016](https://github.com/Microsoft/vscode-cpptools/issues/2016), not sure if that helps you.

**Comment by sean-mcmanus** [comment]
The C/C++ extension isn't involved with build errors, only the IntelliSense errors. It sounds like you need to configure your build task/tools.

**Comment by tcroots78** [comment]
thanks;. Sorry, still new on so many things...feel like I should have seen that. As soon as I started looking there more found it quick. Need to you g++ instead of gcc
