### ISSUE TITLE
wrong intellisense suggestions

### ISSUE THREAD

**Issue by subratappt** [microsoft/vscode-cpptools#2606]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.27.2
- C/C++ Extension Version: Preview
- Issue: wrong intellisense suggestions.
![vs1](https://user-images.githubusercontent.com/40207448/46491894-a909b480-c829-11e8-8da3-f65bb3e4f39d.png)
![vs2](https://user-images.githubusercontent.com/40207448/46491895-a9a24b00-c829-11e8-8375-8a4f4e4a1fb5.png)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Are you using 0.19.0? What is your compiler path, e.g. a cl.exe or WSL compiler? Does completion work for "trailWF" if it's declared like...

![image](https://user-images.githubusercontent.com/19859882/46495853-5dc0b900-c7cb-11e8-93da-a3f3bbad9d01.png)

**Comment by bobbrow** [comment]
Do you have any other extensions installed?  You typed `tria` and I'm seeing results for both `tria` and `trai` in the list.  Our extension doesn't do any letter swapping like that.

**Comment by subratappt** [comment]
Sorry, this error may be due to the workspace folder.  I did not include the folder. After including the folder (Open Folder ) which contains this file, it is working fine.
