### ISSUE TITLE
Text from the C/C++ extension is not localized

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#261]
Switch VS Code languages and the UI/settings/output messages change, but the extension text doesn't.

How many users care about this?

**Comment by jhasse** [comment]
I don't. I also think that forcing people to use English is a plus.

**Comment by agauniyal** [comment]
There are other tasks far more important than this is atm :)

**Comment by delmyers** [comment]
Is this the same as #7 ?

**Comment by sean-mcmanus** [comment]
I don't think so. By support Chinese, I think they mean our tool should work with a Chinese language codebase, and it should now (previously, our tool didn't support UTF-8 correctly). #7 was filed before VS Code had any translated text. This bug is just about UI strings. So I think #7 can be closed.

**Comment by sean-mcmanus** [comment]
Actually, I guess this can be considered a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/7 .
