### ISSUE TITLE
Variable Length Arrays (C99) error: Expression must have constant value

### ISSUE THREAD

**Issue by LShun** [microsoft/vscode-cpptools#2616]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Home 10.0.17134 Build 17134
- VS Code Version: 1.27.2 (User Setup)
- C/C++ Extension Version: 0.19.0
- Other extensions you installed (and if the issue persists after disabling them): None.
- When a variable length array (C99 supported) is declared, and error: "expression must have a constant value" is raised.

**To Reproduce**

```c
#include <stdio.h>

int main(void)
{
    int i, n;

    printf("How many numbers do you want to reverse? ");
    scanf("%d", &n);

    int a[n];

    printf("Enter &d numbers: ", n);
    for (i = 0; i < n; i++)
    {
        scanf("%d", &a[i]);
    }
    printf("in reverse order: ");
    for (i = n - 1 ; i >= 0 ; i --)
        printf(" %d", a[i]);
    printf("\n");

    return 0;
}
```

**Expected behavior**

Error squiggles appear under n on the line ```int a[n]``` with "expression must have a constant value" is raised

**Screenshots**

![image](https://user-images.githubusercontent.com/9652305/46566525-d56d2000-c952-11e8-933d-7beea66c6d5c.png)

**Additional context**

None.

**Comment by sean-mcmanus** [comment]
I don't think the "cl.exe" compiler supports that -- what compiler are you using? Setting your compilerPath to gcc/clang should "fix" this.

![image](https://user-images.githubusercontent.com/19859882/46626967-d2f2fd80-caed-11e8-9621-fb865ce4f39f.png)

**Comment by michelleangela** [comment]
Closing this issue. Please try the suggested solution. If your issue still persists, please re-open the issue and reply with additional information that can help us investigate your issue.

**Comment by electromaggot** [comment]
Try this to suppress error E0028 in IntelliSense (see [EDG C++ Front-End PDF](http://www.edg.com/docs/edg_cpp.pdf)) :
```
#ifdef __INTELLISENSE__
  #pragma diag_suppress 28
#endif

```

**Comment by sean-mcmanus** [comment]
@electromaggot Oh, that's cool (I didn't know about diag_suppress). We don't currently expose the EDG error codes for the errors, but we might add those later on.

**Comment by INNOVATIVEGAMER** [comment]
> I don't think the "cl.exe" compiler supports that -- what compiler are you using? Setting your compilerPath to gcc/clang should "fix" this.
> 
> ![image](https://user-images.githubusercontent.com/19859882/46626967-d2f2fd80-caed-11e8-9621-fb865ce4f39f.png)

It helped me a lot. Thanks for the explanation. I just need to change the path of compiler to my gcc compiler. I want to just add one thing that we need to change the path where gcc compiler files are present and not only /usr/bin/gcc
