### ISSUE TITLE
Does not syntax highlight for "string" class, very popular in c++ 

### ISSUE THREAD

**Issue by KrupeshDev** [microsoft/vscode-cpptools#2617]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Build 17134
- VS Code Version: 1.27
- C/C++ Extension Version:  0.19.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
I want to see syntax highlighting for "string" class, also get auto-completes for all string class functions.
String class is very popular in c++ programming, it is kind of primitive that vscode cpptools should identify and syntax highlight "string" class.

![issue](https://user-images.githubusercontent.com/42747200/46567696-b96a7e00-c954-11e8-8c16-68daae02832e.png)

**Comment by bobbrow** [comment]
Thanks for the feedback.  Can you please go and upvote #230?  This is a duplicate of that.
