### ISSUE TITLE
[v0.19.0] Not predicting variables, header files, user-defined types, …

### ISSUE THREAD

**Issue by KingOfCeylon** [microsoft/vscode-cpptools#2618]
I did a fresh install of vscode and the cpptools extension (version 0.19.0). The prediction feature is broken. It predicts

![Bad predictions](https://user-images.githubusercontent.com/41140495/46573241-eed99080-c981-11e8-8ba3-dce06002e48b.gif)

As you can see, things like `#include`, `iostream`, `cout` and even variables like `x` are not being predicted.

Debug output [here](https://github.com/Microsoft/vscode-cpptools/files/2453186/cpptools.debug.txt).

Previous versions work fine.

**Comment by bobbrow** [comment]
No repro on Windows.  Need to check linux.  If you can provide any additional configuration info, OS info, etc, that would be helpful.  Debug output is missing messages I would expect to see (e.g. "updating intellisense...", "squiggles count", etc)

**Comment by sean-mcmanus** [comment]
I don't repro it on Linux either. Might be some special repro condition?

**Comment by KingOfCeylon** [comment]
Sorry for the delay. OS is Fedora 28 with kernel 4.18.13 (x64) and VSCode version v1.28 (September 2018).

My `settings.json`:
```json
{
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "window.titleBarStyle": "custom",
    "editor.wordWrap": "on",
    "C_Cpp.default.cppStandard": "c++14",
    "C_Cpp.default.cStandard": "c99",
    "editor.fontFamily": "'monospace'",
    "markdown.preview.fontFamily": "sans-serif",
    "editor.fontLigatures": true,
    "editor.formatOnSave": true,
    "C_Cpp.clang_format_path": "/usr/bin/clang-format",
    "terminal.integrated.rendererType": "dom",
    "workbench.colorTheme": "Monokai",
    "code-runner.runInTerminal": true,
    "python.formatting.autopep8Args": [
        "--aggressive",
        "--aggressive"
    ],
    "files.insertFinalNewline": true
}
```

**Comment by Colengms** [comment]
This issue has been unaddressed in our backlog for a long time.  We suspect it's since been fixed.  If there is still a problem, please re-open and add any new information, or open a new issue.  Thanks!
