### ISSUE TITLE
Browse database doesn't clear when there's a configuration change

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#262]
If includePaths are removed or limitSymbolsToIncludeHeaders change to true, the database isn't being reset, so there's too much stuff in the autocomplete.

Changing the databaseFilename is a workaround (deleting the old db would be good too).

**Comment by thetypingpuppy** [comment]
Where is the database stored?

**Comment by sean-mcmanus** [comment]
On Windows, the default is C:/Users/< user >/AppData/Roaming/Code/User/workspaceStorage/< some GUID >/ms-vscode.cpptools/.BROWSE.VC.DB. You can rename the file via the configuration properties. On Linux...I'd have to check...somewhere similar.

**Comment by Cloudwu1** [comment]
@sean-mcmanus Thank you. I thought it was missing. And now find it.

**Comment by bobbrow** [comment]
This is fixed in 0.13.0
