### ISSUE TITLE
[Feature Request]: Transform "." to "->" if the variable is a pointer.

### ISSUE THREAD

**Issue by eminfedar** [microsoft/vscode-cpptools#2621]
**Type: LanguageService**

**System Info:**
- OS and Version: Pardus 17.3 (or Debian 9)
- VS Code Version: 1.27.2
- C/C++ Extension Version: 0.19.0

**Feature Request:**
If this extension can transform **"." (dot)** to **"->" (arrow)** if the **variable** is a **pointer**, that will be awesome. Because of typing dot "." is much more easier and faster than typing two different characters arrow "->" everytime.

Some IDE's has this feature in their text editors and it works amazing. Please add this feature, I want to use VSCode in developing apps in C++. :+1: 

Thanks!

**Comment by sean-mcmanus** [comment]
This is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/862 . Please upvote that issue.

**Comment by sean-mcmanus** [comment]
Fixed with 0.29.0.
