### ISSUE TITLE
Add 'int' as return type for 'main' snippet

### ISSUE THREAD

**Issue by Iamnvincible** [microsoft/vscode-cpptools#2622]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:1.27.2 (user setup)
- C/C++ Extension Version:Version 0.19.0: September 27, 2018

**To Reproduce**

1. Create a new cpp file
2. Type main and you will see snippet for 'main'
3. Choose the 'main' snippet
4. It will generate a snippet but you can see the method do not contain a return type
5. Though g++ doesn't produce an error for that, clang++ does

![default](https://user-images.githubusercontent.com/5810474/46595091-5c63f900-cb09-11e8-9529-6810a7c7aba3.png)

**Expected behavior**

```
int main(int argc, char const *argv[])
{
    /* code */
    return 0;
}
```

**Suggestion**

Update *Extension/cpp_snippets.json* for `main` snippet and add `int` for that will work better.

**Comment by sean-mcmanus** [comment]
This was intentional to allow users to use "void main" or "int main" -- also, the problem we had with "int main" is that users would type "int m" and it would complete to "int int main". At one point we had snippets imain and vmain.

**Comment by Colengms** [comment]
This appears to have been addressed.  Code snippet for main() now includes int return type.
