### ISSUE TITLE
Why do you have your own navigation system?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-cpptools#2624]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version:
- C/C++ Extension Version: 0.19.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

---

![image](https://user-images.githubusercontent.com/2193314/46627165-7b08c680-caee-11e8-98a3-e83b5f50912d.png)

Click this status bar item gives this:

![image](https://user-images.githubusercontent.com/2193314/46627181-8825b580-caee-11e8-8727-72c7460639f9.png)

But there are already mechanisms in VS Code to surface this information if users want to:

Outline viewlet:

![image](https://user-images.githubusercontent.com/2193314/46627214-9e337600-caee-11e8-8f2f-79b846dd91c1.png)

Find symbol command:

![image](https://user-images.githubusercontent.com/2193314/46627236-a986a180-caee-11e8-8094-df47335e04a4.png)

Breadcrumbs:

![image](https://user-images.githubusercontent.com/2193314/46627257-b99e8100-caee-11e8-96e6-bccd8ceff2a0.png)

/cc @jrieken

**Comment by sean-mcmanus** [comment]
Yeah, we implemented our navigation system before VS Code had any support for the Outline view and bread crumbs. The reason for not removing our navigation is that the Outline and breadcrumbs is currently buggy with our tool and we don't pass back symbol ranges yet. We're tracking that with https://github.com/Microsoft/vscode-cpptools/issues/2230 -- after fixing that we should be able to remove that status bar navigation.

**Comment by vscpp** [comment]
The Cpptools's navigation function is convenient to me for viewing and selecting C function. I think you can keep it.
Outline viewlet: Can't use keyboard to select function
Find symbol command / Breadcrumbs: contain too many useless global variable.

**Comment by Tyriar** [comment]
> Outline viewlet: Can't use keyboard to select function

@vscpp sure you can, you can also filter by typing.

> Find symbol command / Breadcrumbs: contain too many useless global variable.

But it's trivial to filter them, there's a way that this is done across all languages in VS Code and it should remain consistent. That way you set up your preferred keybinding once and it works the same across all languages.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.

**Comment by Tyriar** [comment]
If this is still how the extension works you should reopen this, the C++ extension should use the system that VS Code provides so the experience is consistent across languages and so C++ gets the features we build for it (breadcrumbs, find symbol, outline view).

**Comment by Tyriar** [comment]
I guess this is covered by https://github.com/microsoft/vscode-cpptools/issues/2230 so it's fine 🙂
