### ISSUE TITLE
“Format codes” is unusable

### ISSUE THREAD

**Issue by thunderning** [microsoft/vscode-cpptools#263]
I can't use "format codes" function both in Windows and Linux. You said this extension include clang-format, and I find it. BUT, no matter which path I add to the user setting, it couldn't work. Even I set a wrong path , it still nothing happened when I press "alt+shift+F".I only want an mistake message.
In addition, I can't use other format extension when I use this extension, I hope you can add a setting that allow us to choose the function I want to use.
Please fix this BUG soon.

**Comment by sean-mcmanus** [comment]
You shouldn't need to set a path unless you want to a use different clang-format other than the one we download (3.9). In the future, we may add a clang_format_enabled setting that will allow you to disable our formatting and use another extension's formatting instead.

**Comment by cschengshuo** [comment]
I had same problem
I tried to run clang-format directly
`./clang-format: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`
then solve the problem with
`sudo dnf install libtinfo.so.5`

**Comment by ecanuto** [comment]
Since some Linux distros like Arch Linux doest comes with libtinfo.so, an workaround is to install clang-format using package manager (sometimes it already comes with clang compiler) and then add this like to your settings.json:

```
"C_Cpp.clang_format_path": "/usr/bin/clang-format"
```

It works for me and maybe is better to fix the clang-format bundled with this plugin to compile statically libtinfo (no dependencies).

**Comment by bobbrow** [comment]
A setting to disable our clang formatting was added earlier this year. Let us know if you need anything else.

**Comment by starquake** [comment]
Disabling formatting is not really a solution. Setting the path to clang-format does work.

**Comment by pfeerick** [comment]
You may need to make sure you have the libtinfo5 package installed if you are on ubuntu/debian... I must have removed it whilst updating / pruning packages as part of changing DE... the real fix though would be to remove the need for the dependency...

**Comment by rustyx** [comment]
Install `libtinfo5`:

    $ sudo apt-get install libtinfo5
