### ISSUE TITLE
Code formater unknown key

### ISSUE THREAD

**Issue by fr43nk** [microsoft/vscode-cpptools#2631]
Using the code formater with the configuration setting:
```
BreakInheritanceList: BeforeColon|BeforeComma|AfterColon
```
leads to an error message in the output window: **unknown key 'BreakInheritanceList'**
Is this a new feature of the clang formater and not yet delivered with this extension?

- OS and Version: Windows 7
- VS Code Version: 1.28.0
- C/C++ Extension Version: 0.19.0

**Comment by sean-mcmanus** [comment]
Yeah, that was added to clang-format 7 and we're still on 6. You can manually install clang-format 7 and set the C_Cpp.clang_format_path to it to use it. We've discussed installing clang-format 7 by default, but not sure when it will happen.

**Comment by fr43nk** [comment]
I installed the current LLVM tools and it now works :smile:
