### ISSUE TITLE
A bug cause by cpptools. Warning `rejected promise not handled within 1 second` when running arbitrary extensions.

### ISSUE THREAD

**Issue by andylizf** [microsoft/vscode-cpptools#2632]
_Reopen from **Microsoft/vscode#60081**_

>Issue Type: Bug
>Warning rejected promise not handled within 1 second when running arbitrary extensions. Even the >example "mock-debug", or a empty extension generated by "yo code".
>VS Code version: Code 1.27.2 (f46c4c4, 2018-09-12T16:17:45.060Z)
>OS version: Windows_NT x64 10.0.17134
>System InfoExtensions: none

> Thanks! Based on the callstack in the second screenshot, this warning is from the C++ extension: https://github.com/Microsoft/vscode-cpptools
> 
> Since this is being caused by an extension, please reopen it there

**Comment by sean-mcmanus** [comment]
Yeah, I've seen this in the past, but I'm not sure how to get it to occur again or what problem it causes. Does anyone know how to get it to repro more often or what fails because of it?

**Comment by bobbrow** [comment]
@sean-mcmanus, based on the screenshot in the vscode issue, this looks like the root path issue you already fixed in the insiders build.

**Comment by andylizf** [comment]
The problem still exists in the new version.
![image](https://user-images.githubusercontent.com/28052536/46900566-b0d6f200-ced6-11e8-8b4c-92c713901bc9.png)
<details>
<summary>Log from Toggle Developer Tools</summary>
<a href="https://github.com/Microsoft/vscode-cpptools/files/2475016/-1539399468480.log" alt="Log file">
-1539399468480.log
</a>
</details>

**Comment by sean-mcmanus** [comment]
Our newest version is actually 0.19.1-insiders, which has teh 'fspath' null reference fixed: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders . I'm not convinced it has the rejected promise not handled fix in all scenarios, but it may have fixed it in some. Do you know a way to repro it 100% with 0.19.1-insiders?

**Comment by andylizf** [comment]
It does't appear in 0.19.1 insider. Thanks :+1:
