### ISSUE TITLE
[openocd] Unable to start debugging. No process is associated with this object.

### ISSUE THREAD

**Issue by mjohngreene** [microsoft/vscode-cpptools#2634]
- Windows 10
- VS Code v1.228.0
- C/C++ v0.19.0
- Target - Multitech Mdot (STM32F4x processor) on Multitech Universal Developer Board

This error pops up after the debug routine runs to completion.  A "debug" file is apparently generated withing VSC project although not on the actual desktop (ie, I can not locate "Image: .\BUILD\MTS_MDOT_F411RE\GCC_ARM-DEBUG\VoBoNode.bin").  

debug terminal:
1: (656) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
1: (694) LaunchOptions  ExePath='Z:\VoboNode_vsc_nucleo_f411RE\VoBoNode\BUILD\MTS_MDOT_F411RE\GCC_ARM-DEBUG\VoBoNode.elf'
1: (695) LaunchOptions  WorkingDirectory='Z:\VoboNode_vsc_nucleo_f411RE\VoBoNode'
1: (695) LaunchOptions  ExeArguments=''
1: (695) LaunchOptions MIMode='gdb'
1: (695) LaunchOptions  MIDebuggerPath='C:\Program Files (x86)\GNU Tools ARM Embedded\6 2017-q2-update\bin\arm-none-eabi-gdb.exe'
1: (695) LaunchOptions  WaitDynamicLibLoad='false'
1: (695) LaunchOptions  DebugServer='C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\bin\openocd.exe'
1: (695) LaunchOptions  DebugServerArgs='-s C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\share\openocd\scripts -f board/st_nucleo_f4.cfg -f interface/stlink-v2-1.cfg -c init -c "reset init"'
1: (695) LaunchOptions  ServerStarted='target halted due to debug-request, current mode: Thread'
1: (695) LaunchOptions  FilterStderr='true'
1: (695) LaunchOptions  ServerLaunchTimeout='20000'
1: (695) LaunchOptions>
1: (695) LaunchOptions    <SetupCommands>
1: (695) LaunchOptions        <Command IgnoreFailures='false' Description=''>-environment-cd Z:\VoboNode_vsc_nucleo_f411RE\VoBoNode\MTS_MDOT_F411RE\GCC_ARM\BUILD-DEBUG</Command>
1: (695) LaunchOptions        <Command IgnoreFailures='false' Description='connect to target'>-target-select remote localhost:3333</Command>
1: (695) LaunchOptions        <Command IgnoreFailures='false' Description='load file'>-file-exec-and-symbols VoBoNode</Command>
1: (695) LaunchOptions        <Command IgnoreFailures='false' Description=''>-interpreter-exec console "monitor endian little"</Command>
1: (695) LaunchOptions        <Command IgnoreFailures='false' Description=''>-interpreter-exec console "monitor reset"</Command>
1: (696) LaunchOptions        <Command IgnoreFailures='false' Description=''>-interpreter-exec console "monitor halt"</Command>
1: (696) LaunchOptions        <Command IgnoreFailures='false' Description=''>-interpreter-exec console "monitor arm semihosting enable"</Command>
1: (696) LaunchOptions        <Command IgnoreFailures='false' Description='flash target'>-target-download</Command>
1: (696) LaunchOptions    </SetupCommands>
1: (696) LaunchOptions</LocalLaunchOptions>
1: (859) Starting: "C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\bin\openocd.exe" -s C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\share\openocd\scripts -f board/st_nucleo_f4.cfg -f interface/stlink-v2-1.cfg -c init -c "reset init"
1: (980) "C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\bin\openocd.exe" exited with code 1 (0x1).
1: (998) <-logout

launch.json:
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/BUILD/MTS_MDOT_F411RE/GCC_ARM-DEBUG/${workspaceRootFolderName}.elf",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false,
            "debugServerArgs": "-s C:\\Program Files\\GNU ARM Eclipse\\OpenOCD\\0.10.0-20170609\\share\\openocd\\scripts -f board/st_nucleo_f4.cfg -f interface/stlink-v2-1.cfg -c init -c \"reset init\"",
            "serverLaunchTimeout": 20000,
            "filterStderr": true,
            "filterStdout": false,
            "serverStarted": "target halted due to debug-request, current mode: Thread",
            "preLaunchTask": "mbed",
            "setupCommands": [
                { "text": "-target-select remote localhost:3333", "description": "connect to target", "ignoreFailures": false },
                { "text": "-file-exec-and-symbols ${workspaceRoot}/BUILD/MTS_MDOT_F411RE/GCC_ARM-DEBUG/${workspaceRootFolderName}.elf", "description": "load file", "ignoreFailures": false},
                { "text": "-interpreter-exec console \"monitor endian little\"", "ignoreFailures": false },
                { "text": "-interpreter-exec console \"monitor reset\"", "ignoreFailures": false },
                { "text": "-interpreter-exec console \"monitor halt\"", "ignoreFailures": false },
                { "text": "-interpreter-exec console \"monitor arm semihosting enable\"", "ignoreFailures": false },
                { "text": "-target-download", "description": "flash target", "ignoreFailures": false }
            ],
            "logging": {
                "moduleLoad": true,
                "trace": true,
                "engineLogging": true,
                "programOutput": true,
                "exceptions": true
            },
            "linux": {
                "MIMode": "gdb",
                "MIDebuggerPath": "/usr/bin/arm-none-eabi-gdb",
                "debugServerPath": "openocd"
            },
            "osx": {
                "MIMode": "gdb",
                "MIDebuggerPath": "/usr/local/bin/arm-none-eabi-gdb",
                "debugServerPath": "openocd"
            },
            "windows": {
                "preLaunchTask": "mbed",
                "MIMode": "gdb",
                "MIDebuggerPath": "C:\\Program Files (x86)\\GNU Tools ARM Embedded\\6 2017-q2-update\\bin\\arm-none-eabi-gdb.exe",
                "debugServerPath": "C:\\Program Files\\GNU ARM Eclipse\\OpenOCD\\0.10.0-20170609\\bin\\openocd.exe",
                "setupCommands": [
                    { "text": "-environment-cd ${workspaceRoot}\\MTS_MDOT_F411RE\\GCC_ARM\\BUILD-DEBUG" },
                    { "text": "-target-select remote localhost:3333", "description": "connect to target", "ignoreFailures": false },
                    { "text": "-file-exec-and-symbols ${workspaceRootFolderName}", "description": "load file", "ignoreFailures": false},
                    { "text": "-interpreter-exec console \"monitor endian little\"", "ignoreFailures": false },
                    { "text": "-interpreter-exec console \"monitor reset\"", "ignoreFailures": false },
                    { "text": "-interpreter-exec console \"monitor halt\"", "ignoreFailures": false },
                    { "text": "-interpreter-exec console \"monitor arm semihosting enable\"", "ignoreFailures": false },
                    { "text": "-target-download", "description": "flash target", "ignoreFailures": false }
                ]
            }
        }
    ]
}

tasks.json:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {    
            "label":"mbed",
            "type": "shell",
            "presentation": {"reveal":"always"},
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}/mbed-os"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            },
            "command": "mbed",
            "args": ["compile", "--profile=mbed-os/tools/profiles/debug.json"],
            "windows": {
                "command": "mbed",
            },
        }
    ]
}

**Comment by pieandcakes** [comment]
I don't know enough about openocd, but it looks like that server start is failing:

1: (695) LaunchOptions DebugServer='C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\bin\openocd.exe'
1: (695) LaunchOptions DebugServerArgs='-s C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\share\openocd\scripts -f board/st_nucleo_f4.cfg -f interface/stlink-v2-1.cfg -c init -c "reset init"'
**1: (695) LaunchOptions ServerStarted='target halted due to debug-request, current mode: Thread'**

**Comment by pieandcakes** [comment]
also seeing: 

1: (859) Starting: "C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\bin\openocd.exe" -s C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\share\openocd\scripts -f board/st_nucleo_f4.cfg -f interface/stlink-v2-1.cfg -c init -c "reset init"
1: (980) "C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\bin\openocd.exe" exited with code 1 (0x1).

**Comment by mjohngreene** [comment]
Thanks, @pieandcakes.  I'm pretty sure you are correct that the source of the problem is that the debug server can not start due to problems with DebugServerArgs which execute in line 859 of the second reply you made.  I'm running into problems getting it going through command line so it probably has something to do with my desktop configuration.  I will update if I figure it out.  

In the meantime, do you know the source of the actual error from the final line of the debug output (line 980)?  Where does "exited with code 1 (0x1)" come from?  Is that a  VSC error?  Or does it come from the CPP Tools extension?

**Comment by pieandcakes** [comment]
>In the meantime, do you know the source of the actual error from the final line of the debug output (line 980)? Where does "exited with code 1 (0x1)" come from? Is that a VSC error? Or does it come from the CPP Tools extension?

That's the exit code that openocd.exe returns when it exits.

For the first part, you can try and run from the command line `C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\bin\openocd.exe` with the args `-s C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-20170609\share\openocd\scripts -f board/st_nucleo_f4.cfg -f interface/stlink-v2-1.cfg -c init -c "reset init"`

My guess us that your first argument after the `-s` needs to be quoted because there is a space in it and `openocd` isn't happy with it.

**Comment by mjohngreene** [comment]
Got it working, @pieandcakes.  It appears to be an issue with content from previous builds being present in the location the VS Code build looks for to load for debugging.  Deleting the entire folder and allowing VS Code to repopulate it through a new build resolved the openOCD error.  And now the build works even if I don't delete the contents from previous builds.  Not entirely sure why this worked but it did.  Thanks for your help.

**Comment by pieandcakes** [comment]
Sounds like some strange hiccup. Glad you got it working!
