### ISSUE TITLE
0.19.1-insiders doesn't auto-install on Windows/Mac with C_Cpp.updateChannel set to Insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2636]
We're investigating the a fix for 0.19.1 (sounds like we have a fix pending). It seems to work on 64-bit Linux (not 32-bit).

If you do Toggle Developer Tools you can see errors about failing to launch the Code setup script:

ERR spawn "F:\Program Files\Microsoft VS Code Insiders\bin\code-insiders.cmd" ENOENT: Error: spawn "F:\Program Files\Microsoft VS Code Insiders\bin\code-insiders.cmd" ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
log.ts:169   ERR Failed to launch VS Code script process for installation: Error: Failed to launch VS Code script process for installation

**Comment by sean-mcmanus** [comment]
It looks like there are a lot more failure scenarios. Has anyone actually gotten 0.19.1-insiders to auto-install?

**Comment by hoffmael** [comment]
Hitting same error in the first comment. On 64-bit windows Insiders User install.

**Comment by sean-mcmanus** [comment]
We should have it fixed for 0.19.1-insiders2, although that will require a manual install, so the auto-install might not work till 0.19.1.
