### ISSUE TITLE
C/C++ VSCode version: 1.28.0

### ISSUE THREAD

**Issue by yeColin** [microsoft/vscode-cpptools#2638]
- Extension Name: cpptools
- Extension Version: 0.19.0
- OS Version: Windows_NT x64 6.1.7601
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by sean-mcmanus** [comment]
What's the problem?

**Comment by pieandcakes** [comment]
Please add relevant info on what you need help with and reopen this issue.
