### ISSUE TITLE
[C++ on gdb] Can't modify variables in local windows

### ISSUE THREAD

**Issue by qian6** [microsoft/vscode-cpptools#2645]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows RS4 17134
- VS Code Version: 1.28.0
- C/C++ Extension Version: <internal URL>
- Cygwin: C:\cygwin\bin g++(7.3.0) gdb(8.0.1)

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Create a test floder and create a a.cpp file and add some code as following:
#include <iostream>
using namespace std;

int main()
{
	int i = 1;
	int j = 2;
	return 0;
}
2. Use this command "g++ -g -O0 a.cpp -o a.exe" to compile this project
3. modify "launch.json" file
"program": "${workspaceFolder}/a.exe",
"externalConsole": false,
"miDebuggerPath": "C:\\cygwin\\bin\\gdb.exe",
4. Set a bp at the line of 8 in a.cpp file
5. Click F5
6. Modify I variable as 10

**[Excepted]**
It can modify successfully.

**[Actually]**
It pop up "Could not find varivale"(Picture 2)
[log3.txt](https://github.com/Microsoft/vscode-cpptools/files/2468395/log3.txt)
![picture 2](https://user-images.githubusercontent.com/20922638/46796318-f5e81080-cd7e-11e8-9350-caeac97a186a.PNG)

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by pieandcakes** [comment]
@qian6 I can't duplicate this. Can you tell me where you downloaded Cygwin from?

I have:
g++ (GCC) 7.3.0
GNU gdb (GDB) (Cygwin 8.0.1-1) 8.0.1

**Comment by qian6** [comment]
@pieandcakes Cygwin download path: http://cygwin.com/install.html 
This issue can only reproduce windows 10.

**Comment by pieandcakes** [comment]
@qian6 Can you tell me if you installed 32 or 64bit Cygwin? I still can't duplicate this and I'm running Win 10 with the September 2018 update.

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
