### ISSUE TITLE
[Cygwin] VSCode Terminal window can't input or output when externalConsole set to false

### ISSUE THREAD

**Issue by LynnZhang01** [microsoft/vscode-cpptools#2647]
Type: General
**Input information below**
**Environment data**
Runtime Environment:
OS Name: Windows
OS Version: Windows-10-Enterprise-RS4-VSDrop-09-20-2018
RID: win10-x64
VS Code Version:1.28.0
C++ Extension Version: <internal>
Steps to reproduce:

1.Install and open Cygwin ,then make a folder CPP
2.Create a .cpp file and add some code with  
`int main()
{
    int a=1;
    int b=2;  //set a BP1
    cout<<"please input a number:"<<endl;
    cin>>a;
    
    while(true)
    {
         cout<<"hello"<<endl; //set a BP2
    }
    return 0;
}`
3.Compiler the a.cpp to a.exe with cygwin
4.Open the folder CPP with vscode as admin
5.Set Breakpoints
6.Open.json and set as following:
"externalConsole": false,
"miDebuggerPath": "C:\\cygwin64\\bin\\gdb.exe",
7.F5
8.Wait hit first BP and continue debugging
9.Input a number on Terminal window
Expect behaver:
1.It should output "please input a number:"
2.It can input 

Actual behavior:
Terminal window can't input or output

**Comment by GraceDong** [comment]
This issue can repro on remote scenario.

**Comment by pieandcakes** [comment]
This seems to be an issue with Cygwin. If you set it to false, the output is in DebugConsole and there is no way to input. The issue is that it is not respecting the `tty` redirection of CON when we give it.

**Comment by pieandcakes** [comment]
I'll add a note to the release.

**Comment by pieandcakes** [comment]
@GraceDong 
>This issue can repro on remote scenario. 

There isn't any way we can enable input in the remote scenario as that is a different machine.
