### ISSUE TITLE
Debugger: [SSH][Unstable]"Debug Console" window show an error message "ERROR: Undefined command: "logout"" 

### ISSUE THREAD

**Issue by GraceDong** [microsoft/vscode-cpptools#2651]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Ubuntu 16.04
- VS Code Version: 1.28.0
- C/C++ Extension Version: 0.19.1-master
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Open the attachment app
2. Set the breakpoint in the 23 line of "arguments.cpp", the 48 and 52 line of "Calling.cpp"
3. F5->F5->F5
4. See error in Debug Console window as following:
![image](https://user-images.githubusercontent.com/20184778/46854638-1de57b80-ce34-11e8-8aa0-433bb3af93b2.png)

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
[log.txt](https://github.com/Microsoft/vscode-cpptools/files/2472095/log.txt)
[Breakpoint.zip](https://github.com/Microsoft/vscode-cpptools/files/2472101/Breakpoint.zip)

**Comment by pieandcakes** [comment]
@GraceDong Logout is sent when you use SSH as sometimes it requires the command to terminate the ssh connection. We ignore the output so its ok.
