### ISSUE TITLE
[C++ extension ]Breakpoint can't be hit which set in While(true) loop and App exited

### ISSUE THREAD

**Issue by LynnZhang01** [microsoft/vscode-cpptools#2652]
**Environment data**
Runtime Environment:
OS Name: Windows
OS Version: Windows-10-Enterprise-RS4-VSDrop-09-20-2018
RID: win10-x64
VS Code Version:1.28.0
C++ Extension Version: 
Steps to reproduce:
1.Install and open Cygwin ,then make a folder CPP
2.Create a .cpp file and add some code with
```
int main()
{
int a=1;
int b=2; //set a BP1
cout<<"please input a number:"<<endl;
cin>>a;
while(true)
{
     cout<<"hello"<<endl; //set a BP2
}
return 0;
}

```
3.Compiler the a.cpp to a.exe with cygwin
4.Open the folder CPP with vscode as admin
5.Set Breakpoints
6.Open.json and set as following:
"externalConsole": false,
"miDebuggerPath": "C:\cygwin64\bin\gdb.exe",
7.F5
8.Wait hit first BP and continue debugging
9.Wait hit the second BP and check the DEBUG CONSOLE
Expect behaver:
1.It should hit the second breakpoint.
Actual behavior:
1.DEBUG CONSOLE show already hit the second BP, but Editor window show no one breakpoint hit.
2.a.exe will be exited after a while
![picture7](https://user-images.githubusercontent.com/32084574/46856099-1f18a780-ce38-11e8-8c3c-155cdbec6edb.png)

[log.txt](https://github.com/Microsoft/vscode-cpptools/files/2471891/log.txt)

**Comment by pieandcakes** [comment]
According to your log gdb is stopped.: 

13	         cout<<"hello"<<endl;
1: (76289) ->*stopped,reason="breakpoint-hit",disp="keep",bkptno="4",frame={addr="0x00000001004010d0",func="main",args=[],file="a.cpp",fullname="/cygdrive/c/CPP/a.cpp",line="13"},thread-id="1",stopped-threads="all"

I also tried it locally and I can't reproduce the issue. 

I see you try and pause it a bunch after it is already stopped.  Can you try and include a log with `"traceResponse": true` in the logging block and send that log too when it fails?

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
