### ISSUE TITLE
[C++ extension]The number of Breakpoint should be successive 

### ISSUE THREAD

**Issue by LynnZhang01** [microsoft/vscode-cpptools#2653]
**Environment data**
Runtime Environment:
OS Name: Windows
OS Version: Windows-10-Enterprise-RS4-VSDrop-09-20-2018
RID: win10-x64
VS Code Version:1.28.0
C++ Extension Version:
Steps to reproduce:
1.Install and open Cygwin ,then make a folder CPP
2.Create a .cpp file and add some code with
```
int main()
{
int a=1; //set a BP1
int b=2; //set a BP2
cout<<"please input a number:"<<endl;
cin>>a;
while(true)
{
     cout<<"hello"<<endl; 
}
return 0;
}

```
3.Compiler the a.cpp to main.exe with cygwin
4.Open the folder CPP with vscode as admin
5.Set Breakpoints
6.Open.json and set as following:
"externalConsole": false,
"miDebuggerPath": "C:\cygwin64\bin\gdb.exe",
7.F5
8.Hit first BP and continue 
9.Hit second BP then stop debugging
10.F5
11.Continue two times
12.Click DEBUG CONSOLE
**Expect**
1. Hit breakpoint 2,main () at main.cpp

**Actual**
1. Hit breakpoint 3 ,main () at main.cpp
![picture8](https://user-images.githubusercontent.com/32084574/46856792-014c4200-ce3a-11e8-9c83-37910ba8e3b6.png)

[log2.txt](https://github.com/Microsoft/vscode-cpptools/files/2472250/log2.txt)

**Comment by pieandcakes** [comment]
@LynnZhang01 This is because breakpoint 1 is a breakpoint we set internally so it will be breakpoint # +1  for all breakpoints. This does not affect debugging and should not be an issue.
