### ISSUE TITLE
[C++ Extension]VScode unable to start debugging on win7 

### ISSUE THREAD

**Issue by LynnZhang01** [microsoft/vscode-cpptools#2655]
**Environment data**
Runtime Environment:
OS Name: Windows
OS Version: Windows-7-Enterprise-05-23-2018
RID: win10-x64
VS Code Version:1.28.0
**Steps to reproduce:**
1.Install and open Cygwin ,then make a folder CPP
2.Create a .cpp file and add some code with
3.Compiler the a.cpp to a.exe with cygwin
4.Open the folder CPP with vscode as admin
5.Set Breakpoints
6.Open.json and set as following:
"externalConsole": false,
"miDebuggerPath": "C:\cygwin64\bin\gdb.exe",
7.F5

**Expect**
1.Vscode can launch successfully 
**Actual**
1.ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". During startup program exited with code 0xc0000135.
[log5.txt](https://github.com/Microsoft/vscode-cpptools/files/2472499/log5.txt)

**Comment by pieandcakes** [comment]
this looks to be that the Cygwin library path isn't set. You can fix this with the following block in your `launch.json`:

```
            "environment": [
                {
                    "name": "PATH",
                    "value": "%PATH%;z:\\cygwin64\\bin"
                }
            ],
```

**Comment by yassinedevop** [comment]
This doesn't work for me
