### ISSUE TITLE
[C++ extension]Some issues on Watch window when add expression 'a++'

### ISSUE THREAD

**Issue by LynnZhang01** [microsoft/vscode-cpptools#2658]
Environment data
Runtime Environment:
OS Name: Windows
OS Version: Windows-10-Enterprise-RS4-VSDrop-09-20-2018
RID: win10-x64
VS Code Version:1.28.0
C++ Extension Version: 
Steps to reproduce:
1.Install and open Cygwin ,then make a folder CPP
2.Create a .cpp file and add some code with
```
int main()
{
int a=1;
int b=2; //set a BP1
cout<<"please input a number:"<<endl;
cin>>a;
while(true)
{
     cout<<"hello"<<endl; //set a BP2
}
return 0;
}
```
3.Compiler the a.cpp to a.exe with cygwin
4.Open the folder CPP with vscode as admin
5.Set Breakpoints
6.Open.json and set as following:
"externalConsole": false,
"miDebuggerPath": "C:\cygwin64\bin\gdb.exe",
7.F5 ,wait hit first breakpoint
8.Add expression 'a++' on WATCH 
9.Continue to click "+" 
10.Click Blank space
**Expect**
1.The value of expression 'a++' should 2 
**Actual**
1.The value of expression 'a++' increased with click "+" 

[log7.txt](https://github.com/Microsoft/vscode-cpptools/files/2472641/log7.txt)

**Comment by pieandcakes** [comment]
This is because gdb will evaluate the expression everytime it refreshes so it will do this. It is part of gdb and not controlled by our code.
