### ISSUE TITLE
"Switch header/source" won't switch to an existing file in another group if it's not visible

### ISSUE THREAD

**Issue by akb825** [microsoft/vscode-cpptools#2667]
**Type: LanguageService**

**Describe the bug**
When you use the "switch header/source" feature, and the file it would switch to is open in a separate group (but not visible), it will open a new tab instead of switching to the existing one.

- OS and Version: Arch Linux
- VS Code Version: 1.28.1
- C/C++ Extension Version: 0.19
- Other extensions you installed (and if the issue persists after disabling them): CMake

**To Reproduce**

1. Open a .cpp file.
2. Open the .h file corresponding to the .cpp file in a separate group.
3. Open a separate file in the second group and make sure that's the currently visible file.
4. Go back to the .cpp file and select "Switch header/source"

**Expected behavior**

The existing .h file open in the second group is displayed instead of opening a new tab.

**Screenshots**

![separate tabs](https://user-images.githubusercontent.com/19942638/46922616-6af65880-cfc0-11e8-915f-26175f1b11ca.png)

**Additional context**

It was mentioned [in a separate bug](https://github.com/Microsoft/vscode-cpptools/issues/444) that this is dependent on an additional API for VS code. However, this was closed almost 2 years ago without any indication of when (or if) this will be resolved. Some bug for this issue should remain open as long as it's present.

**Comment by Colengms** [comment]
This is currently blocked on a VS Code issue: https://github.com/microsoft/vscode/issues/110537

I looked for an existing issue against VS Code that was tracking this and could not find one, so created a new one.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 , but you need to change the setting workbench.editor.revealIfOpen to true.
