### ISSUE TITLE
v 0.19.0  Code Formatting (Shift + Alt + F)  doesn't work.

### ISSUE THREAD

**Issue by 8059542577066** [microsoft/vscode-cpptools#2668]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7 Ultimate SP1 64-bit
- VS Code Version: 1.28.1
- C/C++ Extension Version: 0.19.0
- Other extensions you installed (and if the issue persists after disabling them): None
- Code Formatting (Shift + Alt + F) that worked in version 0.18 doesn't work at all. After updating to 0.19, pressing the key combination or <Right Click> and Click Format Document, both don't work.  No Error message shows up. Nothing happens.
- I liked the VS style formatting so i never attempted to alter any parameters myself, and I just used the auto formatting which came with cpptools by default.

**To Reproduce**

1. Install cpptools v 0.19.0 from extensions.
2. Click (Shift + Alt + F) combination to auto format the file.
3. Nothing happens.

**Comment by greennerve** [comment]
Same problem here on linux

Type: LanguageService

Describe the bug

OS and Version: Ubuntu 18.04
VS Code Version: 1.28.1
C/C++ Extension Version: 0.19.0
Other extensions you installed (and if the issue persists after disabling them): Python

To Reproduce

Install cpptools v 0.19.0 from extensions.
Click (Shift + Alt + F, Ctr + Shift + i, Ctr + K then F on selection)  combination to auto format the file.
Nothing happens.

**Comment by 8059542577066** [comment]
I had to roll back to version 0.18.1 in which auto formatting still worked. While testing with the functionality I found a workaround for auto formatting.

I noticed when this extension is installed clang-format 6.0 program was installed with it.
**C:\Users\YOUR_USERNAME\\.vscode\extensions\ms-vscode.cpptools-0.18.1\LLVM\bin\clang-format.exe**
Apparently this clang-format.exe is run when **Shift + Alt + F** keys are pressed from VS Code.

So I tried below testing method to find out the parameters passed to clang-format:
1. In the clang-format directory given above move **clang-format.exe** so some other location
2. Open .c file with VS Code
3. Open Terminal by pressing **Ctrl + Shift + `**
4. When terminal window opens on the bottom, select **OUTPUT** tab, and select **C/C++** from the drop down menu
5. Click anywhere in the code editor and press **Shift + Alt + F** to format
6. Formatting won't work but it produces the error message like this:
![image](https://user-images.githubusercontent.com/20101263/47054572-4ab3dd00-d1fe-11e8-8d44-c0492e77ab40.png)
7. We can modify the command shown in the error message output and use it to format the document ourselves.
8. Try this command: **_clang-format.exe -style="{ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0 }" -fallback-style="LLVM" -sort-includes=0 "Input File.c" > "Output File.c"_**

Although in this method you can't format while working within VS code, but the formatted results are the same. I hope this helped.

**Comment by greennerve** [comment]
Problem seems to be fixed for me after the latest update v0.20.1

**Comment by Colengms** [comment]
Closing this old issue.  We have since upgraded the version of clang-format we bundle with the extension.  If anyone is still seeing a problem, please open a new issue.
