### ISSUE TITLE
dlopen breakpoint not work

### ISSUE THREAD

**Issue by chinesejie** [microsoft/vscode-cpptools#2669]
Type: Debugger
**Input information below**

code sample is here:https://github.com/chinesejie/dlopen_class 
I input a breakpoint on polygon.cpp line 10, when I use launch.json on MacOS to debug remote program on the centos with gcc4.8.3. The  breakpoint not work well. 
polygon.cpp is inside the so library libpolygon.so which is loaded by main.cpp by using dlopen. 
 
**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

none

**Describe the bug**
- OS and Version: MacOS 10.11.6
- VS Code Version: Version 1.29.0-insider (1.29.0-insider)
- C/C++ Extension Version: 0.19.0
- Other extensions you installed (and if the issue persists after disabling them): none
- A clear and concise description of what the bug is.

 More information:
 I try the same code on clion IDE, it works. 
see the pic here:
https://github.com/chinesejie/dlopen_class/blob/master/debug-clion.jpg

**Comment by pieandcakes** [comment]
Can you check the output and see if the libpolygon.so symbol was loaded by gdb? If not, you may need to specify `additionalSOLibSearchPaths` for gdb to know where it is. You can check your output in the Debug Console to see if gdb was able to load the library symbols.

**Comment by chinesejie** [comment]
I add      "additionalSOLibSearchPath": "${workspaceRoot}",    in launch.json;              
libpolygon.so is under ${workspaceRoot}.

But it still can not load the module, the breakpoint of "polygon.cpp line 10"  shows the response info as below.

```
1: (1409) <-1004-gdb-set solib-search-path /home/work/dlopen_class:
1: (1452) ->1004-gdb-set solib-search-path /home/work/dlopen_class:
1: (1452) ->1004^done
1: (1452) ->(gdb)
1: (1452) 1004: elapsed time 43
1: (1452) <-1005-gdb-set stop-on-solib-events 1
1: (1490) ->1005-gdb-set stop-on-solib-events 1
1: (1490) ->1005^done
1: (1490) ->(gdb)
1: (1490) 1005: elapsed time 37
1: (1490) <-1006-environment-cd /home/work/dlopen_class
1: (1535) ->1006-environment-cd /home/work/dlopen_class

....

1: (1895) <-1012-break-insert -f polygon.cpp:10
1: (1932) ->1012-break-insert -f polygon.cpp:10
1: (1932) ->&"\260\367\321\n"
1: (1932) ->1012^done,bkpt={number="3",type="breakpoint",disp="keep",enabled="y",addr="<PENDING>",pending="polygon.cpp:10",times="0",original-location="polygon.cpp:10"}
1: (1932) ->(gdb)
1: (1932) 1012: elapsed time 37
 R: {"success":true,"message":null,"request_seq":4,"command":"setBreakpoints","body":{"breakpoints":[{"id":2,"verified":true,"line":10,"message":null}]},"running":false,"refs":null,"seq":0,"type":"response"}
E breakpoint: {"reason":"changed","breakpoint":{"id":2,"verified":false,"line":10,"message":"Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained."},"type":"breakpoint"}
C setFunctionBreakpoints: {"breakpoints":[]}
 R: {"success":true,"message":null,"request_seq":5,"command":"setFunctionBreakpoints","body":{"breakpoints":[]},"running":false,"refs":null,"seq":0,"type":"response"}
```

**Comment by pieandcakes** [comment]
@chinesejie That seems to be a module load issue. 
> "message":"Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained."

If you go back towards the top of the log, gdb loads the modules. Can you see if it is loading those modules? Also, when compiling the .so, are you specifying the `-g` flag to include symbols?

**Comment by chinesejie** [comment]
Firstly, when compiling the .so, the -g flag is specified to include symbols. 

I try to search for more details in the debug log. 
Add
``` 
"logging": { "trace": true, "traceResponse": true ,"engineLogging": true}, 
```
in launch.json will show more details. 

 The important log is shown as below.
```
1: (2870) <-1016-interpreter-exec console "info sharedlibrary"
1: (2904) ->1016-interpreter-exec console "info sharedlibrary"
1: (2904) ->~"From                To                  Syms Read   Shared Object Library\n"
1: (2904) ->~"                                        No          /opt/compiler/gcc-4.8.2/lib/libdl.so.2\n"
1: (2905) ->~"                                        No          /opt/compiler/gcc-4.8.2/lib/libstdc++.so.6\n"
1: (2905) ->~"                                        No          /opt/compiler/gcc-4.8.2/lib/libm.so.6\n"
1: (2905) ->~"                                        No          /opt/compiler/gcc-4.8.2/lib/libgcc_s.so.1\n"
1: (2905) ->~"                                        No          /opt/compiler/gcc-4.8.2/lib/libc.so.6\n"
1: (2905) ->~"                                        No          /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2\n"
1: (2905) ->1016^done
```
 It seems that /opt/compiler/gcc-4.8.2/lib/libdl.so.2 can not be loaded as symbols.

Why? 

I use /opt/compiler/gcc-4.8.2/bin/g++ to compile the .so. Then I use another gdb(/home/work/.jumbo/bin/gdb) to debug this .so.
```
sample code here:
https://github.com/chinesejie/dlopen_class/blob/master/.vscode/launch.json
```

Resolved !!!
```
                "debuggerPath": "/opt/compiler/gcc-4.8.2/bin/gdb"
```
new debug log:
```

1: (3402) ->1023-interpreter-exec console "info sharedlibrary"
1: (3402) ->~"From                To                  Syms Read   Shared Object Library\n"
1: (3402) ->~"0x00007ffff7ddca80  0x00007ffff7df50a0  Yes         /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2\n"
1: (3402) ->~"0x00007ffff7bd8e80  0x00007ffff7bd99a8  Yes         /opt/compiler/gcc-4.8.2/lib/libdl.so.2\n"
1: (3402) ->~"0x00007ffff792fc30  0x00007ffff79925c6  Yes         /opt/compiler/gcc-4.8.2/lib/libstdc++.so.6\n"
1: (3402) ->~"0x00007ffff75d7800  0x00007ffff7644808  Yes         /opt/compiler/gcc-4.8.2/lib/libm.so.6\n"
1: (3402) ->~"0x00007ffff73bea60  0x00007ffff73ce228  Yes         /opt/compiler/gcc-4.8.2/lib/libgcc_s.so.1\n"
1: (3402) ->~"0x00007ffff702e540  0x00007ffff715abc4  Yes         /opt/compiler/gcc-4.8.2/lib/libc.so.6\n"
1: (3402) ->~"0x00007ffff6e0dcb0  0x00007ffff6e0dfc8  Yes         ./libpolygon.so\n"
1: (3403) ->1023^done
```

**Comment by chinesejie** [comment]
![image](https://user-images.githubusercontent.com/2154341/47128988-1c013980-d2c6-11e8-93c9-69e6e3ace02d.png)
thanks to @pieandcakes

**Comment by pieandcakes** [comment]
So it seems like using the matched gdb that is with your compiler causes it to work. I think our default is to use the gdb in `/usr/bin`.

Thanks for updating the issue with the fix!
