### ISSUE TITLE
No .browse.VS.code being created

### ISSUE THREAD

**Issue by arghasen** [microsoft/vscode-cpptools#267]
The tags file is not being created despite having C_cpp_properties.json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": ["/usr/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        }
    ]
}
OS- Centos7
VSCOde- 1.5.3
CppTools- 0.9.2

The project folder structure is as follows:
A
-B
--include
--src
-C
--include
--src
Some other folders in A have code in languages like python etc.

**Comment by arghasen** [comment]
duplicate of issue #19

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
