### ISSUE TITLE
the result of peek declaration is not the same to go to declaration

### ISSUE THREAD

**Issue by alianZhen** [microsoft/vscode-cpptools#2671]
Go to declaration now is perfect!

But the result of peek declaration is not the same to go to declaration,can make their result the same?

**Comment by sean-mcmanus** [comment]
How do I repro this?

**Comment by michelleangela** [comment]
Closing this issue. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
