### ISSUE TITLE
Interaction with Live Share - High CPU/Memory Usage, Dangling Process

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode-cpptools#2675]
When sharing a simple C++ project using Live Share (repros on both Windows and Mac) - something like a single folder with a single file containing
```
#include <iostream>
using namespace std;

int main() 
{
    cout << "Hello, World!";
    return 0;
}
```
the `Microsoft.VSCode.CPP.Extension` process on the guest machine consumes "a lot" of CPU (10-20%) and a lot of memory (climbs to ~500MB).

On a Mac machine (does not repro on Windows), killing the extension host does not kill the `Microsoft.VSCode.CPP.Extension.Darwin` process, and it even persists after closing VS Code. (note: this only repros in the Live Share scenario).

The odd thing about this issue is that Live Share *should* lessen the burden on the guest machine. Files in a Live Share session have a custom `vsls` scheme that Live Share language services claim exclusive ownership of, so the C++ language services should not be activated. So my suspicion is that this is because of the debugging services offered by the cpp extension. When are those activated? And is there anything about having a remote file provider that would break their assumptions?

**Comment by somebuckaroo** [comment]
Did you resolve this? I believe I'm seeing a similar issue.
