### ISSUE TITLE
[LanguageService] Can you support emacs or vim/nvim?

### ISSUE THREAD

**Issue by paopaol** [microsoft/vscode-cpptools#2679]
**Type: LanguageService**

Microsoft.VSCode.CPP.Extension.exe is very powerfull than cquery, ccls. Is there a way to use this extension under emacs or vim?

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Our extension is only licensed to run in VS Code. VS Code has support for emacs/vim-related extensions.

**Comment by cloudhan** [comment]
@sean-mcmanus Problem is, when you writing code on a server with ssh terminal only, there is simply no way to open VSCode on that machine, even if I strive to. Thus, I also want to use Microsoft version of language server (C/C++ and Python, especially) on emacs.

**Comment by bobbrow** [comment]
We recommend using the [VSCode Remote SSH extension](https://code.visualstudio.com/docs/remote/ssh) for this now.

**Comment by Ericson2314** [comment]
> Our extension is only licensed to run in VS Code. VS Code has support for emacs/vim-related extensions.

https://github.com/microsoft/vscode-cpptools/blob/master/LICENSE.txt looks like MIT? Has it changed since?

**Comment by kmicklas** [comment]
> Our extension is only licensed to run in VS Code. VS Code has support for emacs/vim-related extensions.

In addition to the impossibility of making such a claim when the software is under the MIT license, the second part doesn't make any sense either. Emacs and vim are completely different editors, VS Code in no way "has support" for them and their extensions.

This situation seems to be a blatant disregard for the whole point of LSP in the first place: allowing mixing and matching between all editors and language specific tooling. Is it all a big charade to suck us back into the Microsoft-verse?

**Comment by sean-mcmanus** [comment]
Only our Open Source components are under the MIT license, that is, any of the Open Source code on GitHub. The extension itself that ships in the VS marketplace or via vsix's we build/release, and the closed source binaries are covered by a different license at https://github.com/microsoft/vscode-cpptools/blob/master/Extension/LICENSE.txt, in particular
```
1. INSTALLATION AND USE RIGHTS. You may only use the C/C++ Extension
   for Visual Studio Code with Visual Studio Code, Visual Studio or
   Xamarin Studio software to help you develop and test your
   applications.
```
In particular, our debugger will abort for other editors like vscodium (even though our language service component will still run).

Our cpptools process uses the LSP for some messages, but it highly dependent on messages from our TypeScript component that release on VS Code specific functionality outside of the LSP. You'd have to ask the LSP team about its goals and expectations for tools that respond to LSP messages (i.e. I don't know).
