### ISSUE TITLE
Clang format ignores custom styles

### ISSUE THREAD

**Issue by tapir** [microsoft/vscode-cpptools#268]
I'm on latest VS Code and C/C++ extension on Win7 64-bit.

I have this line on my settings:
`"C_Cpp.clang_format_style": "{ BasedOnStyle: LLVM, ConstructorInitializerIndentWidth: 4, ContinuationIndentWidth: 4, IndentWidth: 4, ObjCBlockIndentWidth: 4, TabWidth: 4 }"`

It's exactly the same as `C_Cpp.clang_format_style": LLVM`. I doesn't recognize the properties.

**Comment by sean-mcmanus** [comment]
I'm reproing the bug. We'll investigate.

**Comment by bobbrow** [comment]
Sounds the same as #536. A fix should be coming out soon.

**Comment by bobbrow** [comment]
This should be fixed in 0.10.4. Thanks for reporting this issue.
