### ISSUE TITLE
Notification: "`#include` errors detected. Please update your includePath. IntelliSense features for this translation unit will be provided by the Tag Parser."  shown when running custom configuration provider...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode-cpptools#2680]
hey there :wave:

i'm seeing an odd message in the "Probelms" tab / area when i run my configuration provider. 

**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.28.1
- C/C++ Extension Version: 0.19.0

The message: 

```
#include errors detected. Please update your includePath. IntelliSense features for this translation unit will be provided by the Tag Parser.
```

is shown when running in a newly created workspace which uses a custom cpp configuration provider. 

**To Reproduce**
1. download, launch vscode, and install the [Particle Workbench developer preview](https://www.particle.io/workbench) (apologies for the hurdles)
2. let the workbench extension install its dependencies (you'll be prompted)
3. once dependencies are installed, open a folder and run the `Particle: Create Project` command (cmd+shift+p)
3. open the `src/<project-name>.ino` file
4. select "View > Problems..." from the main menu

**Expected behavior**
Should not see the `#include errors detected.` message listed in the "problems" view

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
