### ISSUE TITLE
read tensorflow with vscode, autocomplete and intellisense don't work very well.

### ISSUE THREAD

**Issue by wxcstc** [microsoft/vscode-cpptools#2687]
**Type: LanguageService**
autocomplete, intellisense

**Describe the bug**
- OS and Version: win10
- VS Code Version:1.28.1
- C/C++ Extension Version:0.19.0
- Other extensions you installed (and if the issue persists after disabling them):c++ intellisense
- A clear and concise description of what the bug is.
I can’t autocomplete for some class.

**To Reproduce**
1、download tensorflow source code
2、use vscode open tensorlfow
3、open tensorflow/core/kernels/batch_norm_op.cc
4、for class pointer context，it can’t autocomplete its function and variable
5、And sometimes intellisense is invalid，and sometimes is valid.In my environment，open tensorflow/framework/node_def_builder.h，try to jump to the implement of constructor NodeDefBuidler.But it failed.

**Expected behavior**
When I input “context->”, should autocomplete its function or variable.

**Comment by wxcstc** [comment]
Emmm...
In fact，after update the newest vscode and cpptools，it can't jump to definition anymore.
I have no idea about this.

**Comment by wxcstc** [comment]
And there is a strange phenomenon:
when the src code is local, parsing is quick,this phenomenon is not obvious.And after parsing finished, just could not jump.
when the src code is on server, parsing is slow.At the beginning of parsing,  i can jump.
![image](https://user-images.githubusercontent.com/16100055/47074409-ed835000-d22c-11e8-98f7-ec2a4ee3c482.png)
And after parsing finished, it display "no found"
![image](https://user-images.githubusercontent.com/16100055/47075039-3b4c8800-d22e-11e8-944a-40ebe1f49e20.png)
Now, close it and open again.Also at beginning, when my mouse hovers over the icon of db in the low right corner, it display "discovring files: 0", it can jump to definition.Wait for a little seconds, discovring more files, when it was "populating include completion cache", opkernel can not jump.

my setting.json is below:
![image](https://user-images.githubusercontent.com/16100055/47075583-6d121e80-d22f-11e8-90ab-947945ef55ea.png)
![image](https://user-images.githubusercontent.com/16100055/47075603-756a5980-d22f-11e8-8a42-530b8a978c03.png)

and c_cpp_properties.json is below:
![image](https://user-images.githubusercontent.com/16100055/47075647-90d56480-d22f-11e8-9a0b-0b37639ae1a5.png)

**Comment by sean-mcmanus** [comment]
If you have the C++ IntelliSense extension installed it could be interfering with functionality that we provide. You should probably only have 1 enabled.

I don't think we accept "./" style paths for the "C_Cpp.default.browse.databaseFilename".

If you set your Cpp.loggingLevel to "Debug" you can see potential errors in the C/C++ Output window.

We have an Insiders release at https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders2 which may fix some Go to Definition issues.

We can try testing with tensorflow later...

**Comment by wxcstc** [comment]
I updated 0.19.0-insiders2，it still didn't work...

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
