### ISSUE TITLE
C++ language server crash on single file edits.

### ISSUE THREAD

**Issue by ioniall** [microsoft/vscode-cpptools#269]
The C++ language server crashes when editing C++ code.

Steps to reproduce;
1. With 0.9.2 of the cpptools, VSCode 1.5.3, OS X 10.11.6.
2. Open VSCode
3. Paste some C++ code in a new file
4. Change the "language" (bottom right) from "Plain Text" to "C++"
5. Edit the file (I don't save the file)
6. Server crashes

I'll attach the crash dump and error message. Based on the content, it looks like the server crashes because a folder is not open.

Expected behaviour; to not crash.

I would not expect the full capability of the server to be available (it has not place to save the .db), but it should not crash. So basically, if a "folder" is not open (no workspace), the server would not be expected to be able to browse to definitions, but it should not crash. It could arguable still be expected to be able to offer browsing and symbol support for symbols in the current file. But either way, the crash is not expected.

[Crash log and seen shot in Archive.zip](https://github.com/Microsoft/vscode-cpptools/files/500217/Archive.zip)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I'm reproing the bug on Windows too. It seems to only repro when the file is unsaved in a workspace. We should have it fixed in the next release.

**Comment by bobbrow** [comment]
The crash is fixed in the current version of the extension.
