### ISSUE TITLE
Linter provides no warnings for invalid c89 code

### ISSUE THREAD

**Issue by jy-roda** [microsoft/vscode-cpptools#2690]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10 1803 x64
- VS Code Version: 1.28.2
- C/C++ Extension Version: 0.19.0
- The linter doesn't show warnings for some invalid c89 code

**To Reproduce**

Declaring a variable inside a for loop does not show errors, as well as writing line comments (ie // stuff)

**Expected behavior**

This is not valid c89, and throws compilation errors on my compiler.

**Screenshots**

This is my configuration
![image](https://user-images.githubusercontent.com/9161264/47147890-810d5d00-d2cf-11e8-80c4-531acb822d06.png)

A snippet of code that VS code considers perfectly OK
![image](https://user-images.githubusercontent.com/9161264/47148111-1dcffa80-d2d0-11e8-8f3a-8f1ec5d12517.png)

The compiler output
![image](https://user-images.githubusercontent.com/9161264/47148093-127ccf00-d2d0-11e8-9b17-c73c07cd780f.png)

With a block comment instead
![image](https://user-images.githubusercontent.com/9161264/47148146-2fb19d80-d2d0-11e8-916b-a9cf89bbb418.png)

Compiler now bitching about variable declaration inside for (which is totally expected)
![image](https://user-images.githubusercontent.com/9161264/47148219-730c0c00-d2d0-11e8-90f3-b414f02e040c.png)
 
(Sorry for putting only screenshots, but this is production code and i cannot make easily a sample project)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this -- this is supposed to work, but there's a bug...

**Comment by sean-mcmanus** [comment]
gcc/clang always supports // comments (no matter what the C version is set to), so the gcc/clang "mode" is setting this. What compiler are you using that doesn't support "//"?

**Comment by jy-roda** [comment]
My target is a Motorola 68k processor, with a quite old compiler (embedded is fun) that was written before // comments were allowed. I am trying to use VS Code instead of the old IDE (which is more of a text editor than a IDE).
