### ISSUE TITLE
Intellisense using 100% CPU non-stop

### ISSUE THREAD

**Issue by zajo** [microsoft/vscode-cpptools#2698]
Code version 1.28.1, OS Mojave 10.14, running on a recent MacBook Pro.

I'm afraid I can't provide other relevant information. Please provide an option for turning Intellisense off, it's causing my laptop to run hot all the time, draining my battery, spinning the fan.

<img width="660" alt="screenshot" src="https://user-images.githubusercontent.com/609498/47251860-23703200-d3ef-11e8-820c-fcfd239e6ea1.png">

**Comment by bobbrow** [comment]
Can you share a code sample  (if you are working on an open source project) or attach the debugger to it and share the callstacks? It seems you've hit an infinite loop in the IntelliSense server.

**Comment by sean-mcmanus** [comment]
You can also change your intelliSenseEngine setting to "Tag Parser" to prevent that process from starting.

**Comment by zajo** [comment]
The only information I can give you is that after restarting vscode went back to normal, with the same project opened, and exactly the same program, and it hasn't happened since. I doubt this would be helpful, but the project I had opened when it did happen was this: https://github.com/zajo/leaf.

**Comment by zajo** [comment]
Can I please have an option to disable Intellisense, I'm tired of VS code running 40+ threads eating 200% CPU and I don't even care about it. All I need from `vscode-cpptools` is debugging support. As it is I have to disable the whole thing.

**Comment by sean-mcmanus** [comment]
Yes, use the C_Cpp.intelliSenseEngine "Disabled" option.

**Comment by zajo** [comment]
Thank you!
