### ISSUE TITLE
[Feature Request] [gdb] Support Request Completions for debug Console

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-cpptools#2699]
Currently, pressing Ctrl+Space in the input field in the debug console shows "No suggestions". It would be great if available variables would appear there. There should also be an entry for `-exec` to make it more discoverable how to send commands straight to gdb. The latter is useful as the general expectation is that `-exec` is not needed.

**Comment by pieandcakes** [comment]
@letmaik Is this something VS Code supports? If not, it might be best to start an issue on [thier](https://github.com/microsoft/vscode/issues) page first as they would need to support it. The debug console itself is owned by VS Code, not by the extension.

**Comment by letmaik** [comment]
Yes, see https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Completions.

**Comment by WardenGnaw** [comment]
This has been added in v1.8.0
