### ISSUE TITLE
.browse.VC.db including files excluded in the workspace settings.

### ISSUE THREAD

**Issue by jmlewis1** [microsoft/vscode-cpptools#27]
I have explicitly excluded some directories from my workspace in settings.json.

These files do not show up in the explorer, but when I search for symbols I see you're searching the excluded folders.

Looking at the .db file using sqlite3 I can see you have included files that are excluded in my settings.json.

**Comment by sridmad** [comment]
Yes we do not look at the settings currently. We will address it in an update

**Comment by jgoshi** [comment]
This is now fixed and will appear in the next release (version 0.9.0)
