### ISSUE TITLE
Allow other source languages (like Rust) in debugger

### ISSUE THREAD

**Issue by Boddlnagg** [microsoft/vscode-cpptools#270]
I know that this extension is made for C/C++, but since what I'm describing below works in Visual Studio (without an extension), I wonder why it works only _partially_ with the Visual Studio Debugger from inside VS Code. I understand if that is out of scope for this extension, but I'd like it to be considered at least.

When I build an executable with the MSVC-based Rust compiler (which creates a PDB file), I can load it in Visual Studio and and the VS debugger correctly refers to the original Rust source file (even though there's no syntax highlighting), where I can set breakpoints, and most of the stuff just works, including the "Locals" view.
Since VS Code has built in Rust syntax highlighting, I thought that I might try this in VS Code, but it doesn't work as well: I can run the executable in the debugger, and when I break in a console program, it highlights the correct source line and shows a stacktrace. But I can't set breakpoints, no locals are shown, and stepping doesn't work (it jumps out of any Rust code immediately), so it's not really useable.

**Comment by Boddlnagg** [comment]
I just noticed that this is probably a duplicate of #75

**Comment by jacdavis** [comment]
VSCode extensions declare the files they support. If you modify ~/.vscode/extensions/ms-vscode.cpptools-0.9.2/package.json and edit this section to include rust files:
 "debuggers": [
      {
        "type": "cppdbg",
        "label": "C++ (GDB/LLDB)",
        "enableBreakpointsFor": {
          "languageIds": [
            "cpp",
            "c",
            ".h",
            ".cc",
            ".cxx",
            ".hpp",
            ".hh",
            ".hxx"
          ]
        },

Do things work better?

**Comment by jacdavis** [comment]
Sorry, I just realized you're working on windows, not Linux, and are generating pdb symbols. Which debug configuration are you using? C++ Windows or C++ GDB/LLDB? 

Since you mentioned you're using pdb symbols, you would need to use the C++ Windows configuration, and still enable the file extensions you are interested in inside the package.json for the extension (change the section I pointed you to above to the C++ windows portion, rather than gdb/lldb). Note that this isn't really a supported scenario (even in VS) so your milage may vary here.

**Comment by Boddlnagg** [comment]
I am using C++ Windows, no GDB/LLDB involved. Adding`"rust"` to the list of `languageIds` for the `cppvsdbg` debugger type actually allows me to set breakpoints and step through the code, thanks! There are still no variables shown under "Locals", but the local variables _are_ evaluated on mouseover, so this is good enough for me.

Since I don't think that much can be done here to make this scenario more officially supported, from my side this issue can be closed.

**Comment by jacdavis** [comment]
Great, thanks for letting us know. I will go ahead and close the issue.
