### ISSUE TITLE
Windows(Launch) debugger for cpp is giving Unknown Error: 0x800700c1 in vs code

### ISSUE THREAD

**Issue by chandangr** [microsoft/vscode-cpptools#2701]
this is my c_cpp_properties.json
`{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/MinGW/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c99",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}`

this is my launch.cpp
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "C:/WMSCPP_2015/CARD/cbs_2015_RU6/cust/postpacking/auditcarton/server/CARDAuditCartonImpl.cpp",
            "args": [],
            "stopAtEntry": false,
            "cwd": "C:/WMSCPP_2015/CARD/cbs_2015_RU6/",
            "environment": [],
            "externalConsole": true
        }
    ]
}`

**Comment by chandangr** [comment]
launch.json*

**Comment by WardenGnaw** [comment]
```
"program": "C:/WMSCPP_2015/CARD/cbs_2015_RU6/cust/postpacking/auditcarton/server/CARDAuditCartonImpl.cpp",
```
The error is in your launch.json. The expected string in program is a path to your executable. 
That would be the Assembly name or the .exe file in your outputPath for your project.

**Comment by pieandcakes** [comment]
Also, since you are using MinGW includes, you should be using debug `type` of `cppdbg` which will allow you to configure `gdb`. `cppvsdbg` is for Visual C++

**Comment by chandangr** [comment]
> ### here is the path to my cpp files which contains the build files in the libCARDAuditCarton.a-

(https://user-images.githubusercontent.com/27623078/47617123-230c2100-daea-11e8-92f5-35446bce3914.PNG)

> **[Here is my launch.json -](url)**

### {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "C:/WMSCPP_2015/CARD/cbs_2015_RU6/cust/postpacking/auditcarton/server/libCARDAuditCarton.a",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true
        }
    ]
}

Even after these changes, i am getting the same error. Please help me to solve this issue

**Comment by chandangr** [comment]
i have tried changing the version from _0.2.0_ to _2.0.0_ and yet its not working.
