### ISSUE TITLE
includePath errors are hard to understand and fix

### ISSUE THREAD

**Issue by daltairwalter** [microsoft/vscode-cpptools#2702]
I frequently see the message:
#include errors detected. Please update your includePath. IntelliSense features for this translation unit (filename.cxx) will be provided by the Tag Parser.

When I see this and look at the includePath setting, the setting looks good and I am left stuck trying to figure out what went wrong.  Generally my include paths either use the workspace variable or an environment variable that points to our third party so it isn't very straight forward to see where the problem occurs.

Some of the questions I have looking at this error are:
1. What are the full paths of all directories that were searched?
2. Were any of the paths in includePath not found and if so which ones?

C/C++ 0.19.0

Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by sean-mcmanus** [comment]
You can set the C_Cpp.loggingLevel to "Debug" to see what paths end up getting used and any errors (in the C/C++ Output window). Are you able to use that solve your issues?

**Comment by daltairwalter** [comment]
Restarting several times eventually fixed the problem.  I am not sure why, but the environment variable seemed to be cached somewhere and was not being picked up immediately.

I tried making incorrect settings to see if this debug logging would help and it did not seem to be useful because it did not process the environment variables in the log output.  When I restored the settings to be correct, the logging indicated that they were still wrong though intellisense started working again.  If this did work correctly, it would be very helpful for diagnosing this problem, but it would still be a challenge to remember I need to go through all of these steps.  This seems like a very common problem for me, and not something strange or occasional, so I would hope for a more integrated solution.

**Comment by daltairwalter** [comment]
I looked at another file with the restored settings and something went wrong.  I tried restarting again and this time the paths were processed in the debug output window.  Something seems to be wrong in the caching logic that requires several restarts.

**Comment by daltairwalter** [comment]
Another situation I just found is that Intellisesne is missing an include file iconv.h which is needed for some dependency.  When I actually compile the file with -showIncludes, iconv.h does not show up in the list of files that are included.  Presumably, some of my defines are set wrong.  It would be nice if logging could track the include stack to this file and any #ifdef's that were used to get to this point.

**Comment by daltairwalter** [comment]
The following code snippet sometimes fails for me in isolation in a header file.  This is a slightly abbreviated form of the iconv.h problem I am trying to track.

```
#if 0
#    define NOT_DEFINED_DONT_FAIL
#endif
#ifdef NOT_DEFINED_DONT_FAIL
#    include <this_doesnt_exist.h>
#endif
```

**Comment by sean-mcmanus** [comment]
How do I use that header file to repro the issue? I created the header and #included it in some header files, but I'm not seeing any missing include messages.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
