### ISSUE TITLE
Bad scrolling and editing lag/delays in grayed out #ifdef/#endif regions

### ISSUE THREAD

**Issue by floooh** [microsoft/vscode-cpptools#2704]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS 10.14.1 Beta (HW: mid-2014 13" MBP, 2.8 GHz i5, Intel Iris GPU)
- VS Code Version: Version 1.28.2 (1.28.2) (2018-10-17T00:12:02.452Z)
- C/C++ Extension Version: Version 0.19.0: September 27, 2018
- Other extensions you installed (and if the issue persists after disabling them): Vim, Python (both disabled for this issue)
- A clear and concise description of what the bug is:

I'm seeing pretty bad text editing and scrolling lag on the latest macOS when a big part of the editor is occupied by a grayed-out #ifdef/#endif region in big C/C++ headers. The problem disappears (or at least gets a lot better) when executing "C/Cpp: Toggle Inactive Region Colorization".

**To Reproduce**
- clone the following repo with big header-only libs: https://github.com/floooh/sokol
- in VSCode, with the C/Cpp Extension enabled, open the header **sokol_gfx.h**
- scroll anywhere into the big implementation region starting at around line 1500, wait until syntax highlighting gets around to gray-out this region 
- try to scroll up and down with the trackpad or the vertical scrollbar, and note how scrolling is really choppy, and has delays up to half a second
- now execute "Toggle Inactive Region Colorization", and note how the scrolling behavior becomes better (though still quite laggy)
- in some cases I'm also getting bad key input delays, with key-repeat getting stuck for up to a few seconds, but I haven't been able to reproduce this yet with specific steps, it seems to happen fairly randomly, but associated with editing big C/C++ sources with several thousand lines of code.

**Comment by bobbrow** [comment]
The slowness appears to be caused when rendering semi-transparent text.  This is outside of our control (the VS Code team owns rendering), but you can disable opacity for inactive regions and use a gray color to dim it (i.e. the old default) using the following settings:

```
"C_Cpp.inactiveRegionOpacity": 1.0,
"C_Cpp.inactiveRegionForegroundColor": "#c0c0c0",
```

**Comment by sean-mcmanus** [comment]
Is someone going to a file a bug on VS Code?

**Comment by floooh** [comment]
I think it's better if you guys do this (file a bug) because you know VSCode better ;) I'd be interested in following the ticket and give feedback if needed though.

**Comment by sean-mcmanus** [comment]
There is already a similar VS Code issue at https://github.com/Microsoft/vscode/issues/57921 in regards to inactive regions rendering. Can you try the explorer version of VS Code mentioned in https://github.com/Microsoft/vscode/issues/52629 ? You might need to use the "update" to get the latest version (same way VS Code Insiders updates). They're using an updated renderer which has fixed other issues with the inactive regions. If I open a VS Code bug on this, they'll almost certain tell me to try the explorer version first.

**Comment by floooh** [comment]
Wow, yep, the Exploration Version fully fixes the problem, and it also generally feels snappy again when editing such fairly big source files. I guess no further actions are needed except waiting for this to go into the regular version ;)
