### ISSUE TITLE
Use integrated terminal for debugging

### ISSUE THREAD

**Issue by princehektor** [microsoft/vscode-cpptools#2706]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

OS and Version: Ubuntu 16.04, 64bit
VS Code Version: 1.28.1
C/C++ Extension Version: 0.19.0

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. How to use the integrated terminal(instead of gnome-terminal or xterm) for debugging.

**Additional context**
I found a similar issue but this was only for the node debugger.

https://github.com/Microsoft/vscode/issues/16890

**Comment by princehektor** [comment]
@sean-mcmanus : Can you help me out here ?

**Comment by sean-mcmanus** [comment]
Are you using the latest Insiders build at https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders3 ? I think the Integrated Terminal was added in 0.19.1-insiders2.

@pieandcakes @WardenGnaw are the debugger experts.

**Comment by pieandcakes** [comment]
@princehektor Please try using the insiders release. As @sean-mcmanus mentioned, it was recently introduced.

**Comment by pieandcakes** [comment]
Duplicate of #35

**Comment by princehektor** [comment]
@pieandcakes : I installed code insiders. What do i need to change in my launch.json to use the internal terminal for debugging ?

Version: 1.29.0-insider
Commit: d1f5894892e3719846bbd4bd0dd75f117f211ab5
Date: 2018-10-23T05:14:53.945Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by pieandcakes** [comment]
@princehektor Its not code insiders, it is the insiders version of our extension, located in the link Sean posted above. Once you have it installed, it is controlled by `externalConsole` being set to false. 

Note: This works only for local scenarios and only on Windows/ Linux

**Comment by princehektor** [comment]
@pieandcakes  : What do you mean by "local scenarios" ?

**Comment by pieandcakes** [comment]
@princehektor It will only work if you launch the app locally. It does not work for remote (pipeTransport) or attaching to an existing process.

**Comment by pieandcakes** [comment]
This feature is available in our 0.20.0 version of the extension
