### ISSUE TITLE
VS Code cannot find include paths

### ISSUE THREAD

**Issue by malino24** [microsoft/vscode-cpptools#2709]
Something strange happened. Actually nothing happened and BOOM: VS Code cannot find files, especially from the standard library. Gonna link my c_cpp_properties.json, tell me if you need more.

**Comment by malino24** [comment]
![screenshot_5](https://user-images.githubusercontent.com/5430788/47466350-26a15e80-d7f1-11e8-8dc4-f1878d62fe6e.png)

**Comment by sean-mcmanus** [comment]
Can you set C_Cpp.loggingLevel to "Debug" and look for errors in querying gcc.exe for includes paths (in the C/C++ Output window)?

The compilerPath can't be the 0kb gcc.exe. It needs to be a file that is executable on Windows, so you may need to use g++.exe or mingw32-gcc.exe.

**Comment by zondaken** [comment]
Still putting that error.
![screenshot_1](https://user-images.githubusercontent.com/5430788/47466497-bd6e1b00-d7f1-11e8-94ee-5c82b328291a.png)

**Comment by malino24** [comment]
Still putting that error. 
![screenshot_2](https://user-images.githubusercontent.com/5430788/47466516-d5459f00-d7f1-11e8-91e0-8ad5ba0baff2.png)

**Comment by sean-mcmanus** [comment]
@zondaken That is the problems window and not the Output window.

**Comment by malino24** [comment]
When exeuting the task related to this application, it totally escalates and doesn't even find functions I defined in the same file lol Gonna link the new screenshot + screenshot of the task I'm running.
![screenshot_3](https://user-images.githubusercontent.com/5430788/47466608-48e7ac00-d7f2-11e8-918a-472af49047f8.png)
![screenshot_4](https://user-images.githubusercontent.com/5430788/47466609-48e7ac00-d7f2-11e8-866b-3ca2a1d7a021.png)

**Comment by malino24** [comment]
Excuse me, have seen it's again not the Output window. The Output window is empty for me, no matter if I'm executing the task or not.

**Comment by sean-mcmanus** [comment]
The Output window has a C/C++ tab that should show messages from our extension.

The error in the terminal window is with gcc itself and not controlled by our extension, so there's either an error with your code or with the args being passed to gcc.

**Comment by malino24** [comment]
Are you talking about Extensions or Log (Extension Host)?
![screenshot_6](https://user-images.githubusercontent.com/5430788/47466875-b6480c80-d7f3-11e8-8afb-0c7d6928b7ec.png)

**Comment by sean-mcmanus** [comment]
Did you set your C_Cpp.loggingLevel to Debug? The "WSL not detected" part is an incorrect error message and can be ignored. I think you just need to change your compilerPath to point to an executable file, unless you're hitting a different issue.

You should see something like:

![image](https://user-images.githubusercontent.com/19859882/47466986-e0c0a800-d7a8-11e8-8b35-c8b4349241d4.png)

**Comment by malino24** [comment]
As you haven't included any further information, I guess, the logging level should be a node of "configurations" in the "c_cpp_properties.json" file. And as you can see from my attached screenshot my compiler path is pretty valid.
![unbenannt](https://user-images.githubusercontent.com/5430788/47467134-02478100-d7f5-11e8-8dee-2b626411c51b.png)
![unbenannt](https://user-images.githubusercontent.com/5430788/47467144-0a9fbc00-d7f5-11e8-92e7-091932c99413.png)

**Comment by malino24** [comment]
And in one of my previous screenshots you can see that the Output section isn't showing up a C/C++ option like in your screenshot. I don't really know why.

**Comment by malino24** [comment]
And an even stranger thing is that executing my task (after solving a few syntax issues) is now working and compiling through command line works as well. Only IntelliSense is complaining about the include path not being set.
![unbenannt](https://user-images.githubusercontent.com/5430788/47467257-ceb92680-d7f5-11e8-8c46-3ca5fbae9c66.png)

**Comment by sean-mcmanus** [comment]
Use File->Preferences->Settings to get access to the C_Cpp settings -- it's not part of the c_cpp_properties.json. It's part of the settings.json. I attached a screenshot earlier.

Yeah, your gcc.exe seems like it should run, but you should check the log to see if it's failing for some reason and what include paths are being used.

**Comment by bobbrow** [comment]
link: [Enabling logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md)

**Comment by malino24** [comment]
Ok, got it now what you wanted. 
![unbenannt](https://user-images.githubusercontent.com/5430788/47500726-dd3e2700-d863-11e8-9ff0-a72c28192a97.png)

**Comment by bobbrow** [comment]
This is a partial log.  We need to see what happened when testing your compilerPath.  Can you run the `Reload Window` command, make sure main.cpp is focused in the editor and then share the full contents of the Output window?

**Comment by malino24** [comment]
![unbenannt](https://user-images.githubusercontent.com/5430788/47602438-3b434980-d9df-11e8-915e-1dd62d303925.png)

**Comment by malino24** [comment]
I don't wanna confuse you guys but now the stuff is working again xD I'll close this thread as I don't know how to 're-create' the issue. Thanks anyways.
