### ISSUE TITLE
Need a Go to Declaration feature

### ISSUE THREAD

**Issue by ashwin** [microsoft/vscode-cpptools#271]
Visual Studio Code does not have a **Go to declaration** feature. While this may not be needed in many languages, it is important for C++ programmers. Could you add this feature?

**Comment by sean-mcmanus** [comment]
Yes, I believe we can add that. "Go To Definition" already does a "Go To Declaration" when the definition can't be found.

**Comment by Mason-L** [comment]
Visual Studio Code does already have a **Go to declaration** feature. Can you remove it in C/C++ for Visual Studio Code(Version 0.11.0: April 24, 2017)? Or tell me how to disable it in my Context Menu. Bucause there is two options of **Go to declaration**.  My Visual Studio Code Version : 1.11.2.

**Comment by bobbrow** [comment]
This feature has been added in v0.11.0 of the extension.  Thank you for your feedback.
