### ISSUE TITLE
[C# extension] Variable name and value isn't added to the watch window at the same time when adding variable to watch from Locals window

### ISSUE THREAD

**Issue by v-yiwu1** [microsoft/vscode-cpptools#2711]
**Environment data**
OS and Version: Debian9.2.1
VS Code Version: 1.28.2
C# Extension Version:1.17.0-beta6

**Steps to reproduce**
1.Install vscode.
2.Install C# extension.
3.Open the Terminal, run as follow command to create new console project:
   dotnet new console -o hwapp
4.Add some code in the program.cs:
picture1
![picture1](https://user-images.githubusercontent.com/32061365/47478427-df03ec80-d85b-11e8-82b0-e2397dca69ab.png)
5.Compile project with command "dotnet build"
6.Open vscode, open hwapp folder, configure launch.json as following:
![picture2](https://user-images.githubusercontent.com/32061365/47478439-e62afa80-d85b-11e8-9178-8a7606f8a3f6.png)
7.Set a breakpoint in line 19, as picture1
8.F5, wait for hitting the breakpoint.
9.Go to Locals window.
10.choose  a variable, eg: s1, right-click, select "Add to watch"

**Expected**
Variable name and value is added to the watch window at the same time.

**Actual**
Only variable name is added to the watch window. The variable value will not be displayed until you click another location or click "Enter"
![picture3](https://user-images.githubusercontent.com/32061365/47477043-d01a3b80-d855-11e8-8cb4-a010c89d8c54.png)

**Comment by bobbrow** [comment]
I think you meant to create an issue here:  https://github.com/OmniSharp/omnisharp-vscode/issues

This is the C++ extension.
