### ISSUE TITLE
Feature request: allow disabling specific intellisense warning workspace-wide

### ISSUE THREAD

**Issue by dandrestor** [microsoft/vscode-cpptools#2712]
**Type: LanguageService**

Sometimes there is a need to disable a specific intellisense warning for all files. I think this could be done easiest through a workspace-level setting. It would be great if this functionality could be added to the extension.

**Comment by sean-mcmanus** [comment]
This is https://github.com/Microsoft/vscode-cpptools/issues/2345 . It should be pretty quick/easy to implement, but our priorities changed, so it's postponed until later.

**Comment by sean-mcmanus** [comment]
With https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 , we show the IntelliSense error codes, so 
```
#ifdef __INTELLISENSE__
    #pragma diag_suppress 28
#endif
```
could be used as a workaround for suppressing IntelliSense errors (replace 28 with the error code).

You could include that code in a file referenced in the forcedInclude property to have it added to every file in the workspace.
