### ISSUE TITLE
[gdb][qemu]: Unable to create debug configuration without "program".

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode-cpptools#2713]
Type: Debugger

Hello all.
I use vscode to debug programs, launched in QEMU.
As you may know, qemu has built-in gdbserver stub which is available at  localhost:1234 .
I am debugging application, launched in qemu:

My build system generates .gdbinit file at build directory:

```
set architecture i386:x86-64:intel
add-symbol-file /path/to/program1 0xaddr1
add-symbol-file /path/to/program2 0xaddr2
add-symbol-file /path/to/program3 0xaddr3
target remote :1234 
```
So, to start debugging, I just need to launch gdb in build directory without any parameters.
But I cannot do it, because parameter "program" is necessary.
Please make it optional.

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.28.2
- C/C++ Extension Version: 0.19.0

**To Reproduce**
1. Go to debug view
2. Click on  gear icon (open launch.json)
3. Remove "program" property
4. See error message "missing property program" on hover mouse over { symbol

**Comment by pieandcakes** [comment]
@dibalavs Hi, this seems like a very specific case where `program` is not required. Unfortunately for most other users it will be a required parameter. If you can propose a way where we can tell it is in your specific case, we may be able to add a check to ignore the program field without disrupting other users.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity and by design.
