### ISSUE TITLE
[gdb] Unable to specify current working directory for gdb

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode-cpptools#2714]
Type: Debugger

Hello all.
My build system generates .gdbinit file at build directory:

```
set architecture i386:x86-64:intel
add-symbol-file /path/to/program1 0xaddr1
add-symbol-file /path/to/program2 0xaddr2
add-symbol-file /path/to/program3 0xaddr3
target remote :1234 
```
So, to start debugging, I just need to launch gdb in build directory without any parameters.
But I cannot do it, because I cannot specify working directory for gdb.

I found "cwd" propety, but it specify directory for debugged application, not for gdb itself.

Implicitly, directory can be set by using "program" property, But in my case I cannot use it. 
(See separate bug: #2713 )
Please  add explicit way to set CWD for gdb

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.28.2
- C/C++ Extension Version: 0.19.0

**To Reproduce**
1. Go to debug view
2. Click on  gear icon (open launch.json)
3. Remove "program" property
4. Think about, how to set CWD for gdb?

**Comment by pieandcakes** [comment]
You can specify `--cd=<DIR>` in `miDebuggerArgs`. `cwd` path is sent to `gdb` as `-environment-cd`. you can find the code [here](https://github.com/Microsoft/MIEngine/blob/master/src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs#L791).

**Comment by dibalavs** [comment]
Thanks for miDebuggerARgs, but unfortunately gdb does not read DIR/.gdbinit file in case of --cd=DIR is used

**Comment by OlegGalizin** [comment]
-exec source .gdbinit
