### ISSUE TITLE
IntelliSense: Some code gets marked as error despite compiling successfully

### ISSUE THREAD

**Issue by daigennki** [microsoft/vscode-cpptools#2717]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 8.1 (6.3.9600) and Windows 10 (10.0.17134.345). Issue occurs on both, with both machines having identical installations of MinGW and libraries.
- VS Code Version: 1.28.2
- C/C++ Extension Version: 0.19.0
- Other extensions you installed (and if the issue persists after disabling them): Japanese Language Pack, Shader languages support for VS Code. Issue persists after disabling both.
- A clear and concise description of what the bug is.
IntelliSense is giving me red lines beneath some code that uses the `std` namespace, mostly seeming to involve C++11. What is especially confusing is that this code compiles successfully using the same headers in the same include directories, using MinGW's gcc, and these are the only "errors" which IntelliSense detects.

**To Reproduce**
c_cpp_properties.json:
```json
{
    "configurations": [
        {
            "name": "Win32",
            "intelliSenseMode": "gcc-x64",
            "compilerPath": "C:/msys64/mingw32/bin/g++.exe",
            "includePath": [
                "${workspaceFolder}"
            ],
            "defines": [],
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Expected behavior**
The red lines should not be there, since it compiles successfully.

**Screenshots**
Just a few of the many parts of my code where this happens:
![9 _edit](https://user-images.githubusercontent.com/18689525/47504244-d553a680-d8a6-11e8-8427-7752a8536457.png)
![8 _crop](https://user-images.githubusercontent.com/18689525/47504252-d8e72d80-d8a6-11e8-8ff2-9052ce2cb512.png)

**Additional context**

**Comment by daigennki** [comment]
Just noticed something probably important. It seems that the "errors" are gone if I change `C_Cpp.intelliSenseEngine` from `Default` to `Tag Parser`, but with that, it is much less useful. Putting aside the issues I am having, of course.

**Comment by qiaomo** [comment]
I also encountered this problem and it often appears. Hope to fix.

**Comment by mxdh** [comment]
Could you try setting "includePath" and "browse"?
For example:
```
{
	"configurations": [
		{
			"name": "Win32",
			"includePath": [
				"${workspaceFolder}/**",
				"C:/mingw/include/c++/8.2.0",
				"C:/mingw/include/c++/8.2.0/x86_64-w64-mingw32",
				"C:/mingw/include/c++/8.2.0/backward",
				"C:/mingw/lib/gcc/x86_64-w64-mingw32/8.2.0/include",
				"C:/mingw/include",
				"C:/mingw/lib/gcc/x86_64-w64-mingw32/8.2.0/include-fixed",
				"C:/mingw/x86_64-w64-mingw32/include"
			],
			"defines": [
				"_DEBUG",
				"UNICODE",
				"_UNICODE"
			],
			"intelliSenseMode": "gcc-x64",
			"compilerPath": "C:/msys64/mingw64/bin/g++.exe",
			"browse": {
				"path": [ 
				"${workspaceFolder}",
				"C:/mingw/include/c++/8.2.0",
				"C:/mingw/include/c++/8.2.0/x86_64-w64-mingw32",
				"C:/mingw/include/c++/8.2.0/backward",
				"C:/mingw/lib/gcc/x86_64-w64-mingw32/8.2.0/include",
				"C:/mingw/include",
				"C:/mingw/lib/gcc/x86_64-w64-mingw32/8.2.0/include-fixed",
				"C:/mingw/x86_64-w64-mingw32/include"
				],
				"limitSymbolsToIncludedHeaders": true,
				"databaseFilename": ""
			}
		}
	],
	"version": 4
}
```

**Comment by daigennki** [comment]
I appreciate the help, but I think I did that before and it did not fix anything. For some reason though, the issue fixed itself before you commented. Although I am not absolutely sure if this is why, I think my installation may have been weird. I updated MinGW32 using msys64 as well as installed MinGW64 since I was going to move to 64-bit, and I only noticed after that, that the "errors" disappeared. That would explain why I was not able to find other people talking about it on the internet. Also, my C++ configuration right now is just this:
```json
{
    "configurations": [
        {
            "name": "Win64",
            "compilerPath": "C:/msys64/mingw64/bin/g++.exe",
            "includePath": [
                "${workspaceFolder}"
            ]
        }
    ],
    "version": 4
}
```
, relying on default and user settings for what is not there, and it works perfectly fine. For reference, here is my user settings:
```json
{
    "editor.fontFamily": "Migu 1m",
    "explorer.sortOrder": "type",
    "files.encoding": "utf8",
    "git.enableSmartCommit": true,
    "git.autofetch": true,
    "terminal.integrated.fontFamily": "MS Gothic",
    "debug.inlineValues": true,
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.cStandard": "c11"
}
```
I have a feeling the problem disappeared before I even did any of that, but if anybody encounters issues like these again, I suggest trying what I did. Sorry for bothering you people, I will close this now.
