### ISSUE TITLE
on elementary OS ( linux distro) I can't run C++ code in integrated terminal

### ISSUE THREAD

**Issue by YousefSaber** [microsoft/vscode-cpptools#2727]
**Describe the bug**
- OS and Version: elementary OS v5.0
- VS Code Version:1.28.2
- C/C++ Extension Version:0.19.0
- Other extensions you installed (and if the issue persists after disabling them):python extension 
VSCode can't debug c++ code in integrated terminal 

![image](https://user-images.githubusercontent.com/33742499/47543860-82004900-d8e4-11e8-8265-fffd6032f2e9.png)

**Comment by pieandcakes** [comment]
@YousefSaber With 0.19.0, we are using an external terminal app when launching on Linux. The two that are supported are gnomeTerminal or XTerm. If you want to try our new integratedTerminal feature, you can try 0.19.1-insiders2 or [0.19.1-insiders3](https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders3) or wait for 0.20.0 release.

**Comment by YousefSaber** [comment]
@pieandcakes GNOME neither XTerm are supported on elementary OS it looks like that I'll have to wait for v0.20.0

**Comment by YousefSaber** [comment]
@pieandcakes  GNOME neither XTerm are supported on elementary OS it looks like that I'll have to wait for v0.20.0

**Comment by pieandcakes** [comment]
@YousefSaber 0.20.0 is released. Let me know if this solves your issue.
