### ISSUE TITLE
[OS X] Hovering over function name shows Initializing... state with no Code Completion

### ISSUE THREAD

**Issue by dgnn96** [microsoft/vscode-cpptools#2729]
Issue Type: <b>Bug</b>

I installed the official C/C++ plugin. When the function jumps, the mouse is placed on the function name, hold down ctrl, but the function name always shows the status in Initializing..., click No response. And can not do c / c + + code completion.

Extension version: 0.19.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.80GB free)|
|Process Argv|-psn_0_217141|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by pieandcakes** [comment]
Updated title to reflect issue detail

**Comment by sean-mcmanus** [comment]
Are you doing Open Folder? Is there any error in the C/C++ Output window (https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md ).

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
