### ISSUE TITLE
format document not working

### ISSUE THREAD

**Issue by sarthchawla** [microsoft/vscode-cpptools#2730]
Issue Type: <b>Bug</b>
list of events that i did before i faced this problem
1. updated my ubuntu from 18.04 to 18.10
2. updated my vs code too
3.installed another extension thats of sql this extension even changed my vs code font that didnt changed back even after i edited it in the settings,json file too, thus i reinstalled vs code.

Extension version: 0.19.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.18.0-10-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2275)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (2.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
If you [Enable Logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) do you see any error messages?

**Comment by sarthchawla** [comment]
With the latest update my problem got resolved actually. Thank you
