### ISSUE TITLE
clang format corrupting 

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#2731]
Issue Type: <b>Bug</b>

Sometimes (mostly) it happed 😞 

### Before save:
![before](https://user-images.githubusercontent.com/37267028/47614891-5b950600-dabc-11e8-9f52-6f267fac4449.PNG)

### After save (and auto format):
![after](https://user-images.githubusercontent.com/37267028/47614894-6780c800-dabc-11e8-8d48-7c4808df15ac.PNG)

VSCode 1.28.2 + C/C++ Extension 0.19.0 + LLVM 8.0.0-r339319-win64

Settings {
    "python.jediEnabled": false,
    "editor.formatOnSave": true,
    "C_Cpp.clang_format_fallbackStyle": "{BasedOnStyle: Google, ColumnLimit: 120}",
    "C_Cpp.clang_format_sortIncludes": true,
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.cStandard": "c99",
    "C_Cpp.default.intelliSenseMode": "msvc-x64",
    "workbench.colorTheme": "Default Light+",
    "workbench.startupEditor": "newUntitledFile",
}

Extension version: 0.19.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2710QE CPU @ 2.10GHz (8 x 2095)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
Do you have any more info on how to repro this?

**Comment by bobbrow** [comment]
The other case we saw of this had heavy use of the Terminal window or Output window (I forget which) and we suspected there was some corruption in either VS Code's representation of the file or ours (which messed up our edits).  Do you happen to use either of those windows?

We weren't able to get a repro in our instrumented build of the extension.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.

**Comment by Zitrax** [comment]
I am seeing this too which is incredibly annoying when it happens. Sometimes I does not see that the corruption happens further down in the file when editing at the top. But when it happens I can invoke the formatting multiple times and each time garbles the file more and more.

I am on vs code 1.37.1 and using clang-format extension 1.9.0.

Unfortunately I also do not know exactly how to reproduce it.

**Comment by sean-mcmanus** [comment]
@Zitrax We're using https://github.com/microsoft/vscode-cpptools/issues/1073 to track clang-format corruption. However, if you're using the clang-format extension, then the bug should be with that extension and not ours (assuming you set the C_Cpp.formatting to "Disabled").
