### ISSUE TITLE
CPP "strcmp" is undefined error 

### ISSUE THREAD

**Issue by KevYChen** [microsoft/vscode-cpptools#2732]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS Mojave 10.14
- VS Code Version: 1.28.2
- C/C++ Extension Version: 0.19.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
My friend was helping me getting set up with doing shell scripting on vscode and then it stopped working for my cpp in vscode. Didn't have this problem before installed homebrew and other stuff. I think its because my c_cpp_properties.json files have changed.

**To Reproduce**

{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/usr/local/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                    "/usr/local/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17"
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
<img width="1440" alt="screen shot 2018-10-29 at 10 43 21 am" src="https://user-images.githubusercontent.com/42678692/47657503-930cbc80-db67-11e8-904c-b39fa69d953a.png">

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bobbrow** [comment]
Can you try the following configuration instead?

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by KevYChen** [comment]
That seem to do the trick thank you!
