### ISSUE TITLE
Memory "leak" when parsing a large workspace

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2737]
1. Open a large workspace such as chromium with >100k files to parse. The issue occurs the 1st time or after a Reset IntelliSense Database occurs.

Bug: Memory usage of the main process keeps increasing. It's possible we could crash from an out of memory on 32-bit Linux.

UPDATE: Actually, looks like our parser is accumulating memory in various places (i.e. not a simple fix). The workaround is to do a Reload Window if memory usage gets too high.

UPDATE: Should be fixed with 0.21.0-insiders (auto installed if `"C_Cpp.updateChannel": "Insiders"` is set, or manually installed from the [offline vsix](https://github.com/Microsoft/vscode-cpptools/releases/tag/0.21.0-insiders)). Let us know if you find any problems with it.

**Comment by chraac** [comment]
I found similar problem when in 0.20.1, and it create plenty of powershell process.

**Comment by bobbrow** [comment]
The powershell process issue is a bug in the telemetry package we depend on.  See #2822.  A fix is committed to our repo, but you'll want to downgrade to 0.20.0 (and disable automatic updates) until we publish a version with that fix.
