### ISSUE TITLE
No feedback when "Go To Definition" doesn't work

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#274]
I do "Go To Definition" on VK_NULL_HANDLE in UnrealEngine-release\Engine\Source\Runtime\VulkanRHI\Private\VulkanDevice.h .

Bug: It silently fails (in other cases, it takes a long time to give results). It would be nice if gave some feedback as to what happened, e.g. "Couldn't be found", "Local variables aren't supported yet", "Processing...", "Unknown error", etc.

**Comment by bobbrow** [comment]
VS Code renders a balloon message over the symbol when no definition is found now.
