### ISSUE TITLE
GDB debugging broken with VSCode 1.28?

### ISSUE THREAD

**Issue by wpaul-magicleap** [microsoft/vscode-cpptools#2740]
Type: Debugger
Our debugger integration broke when updating VSCode from 1.27.2 to 1.28.  The C/C++ extension is 0.19.0 is both cases, as is our extension.  Something in the core debugger must have changed.  I'm trying to understand if this is specific to our debugger or generically for MIEngine.

**Describe the bug**
- OS and Version: Tested on Windows and OS X
- VS Code Version: 1.28.1/1.28.2
- C/C++ Extension Version: 0.19.0

With 1.27 we can debug just fine.  Once updating to 1.28 the debugger no longer works as expected.  All of the output from GDB is exactly the same.  It shows that it's stopped at the entry point:
Program received signal SIGSTOP, Stopped (signal).
0x0000400001a41b7c in __dl__start () from /path/to/linker64

But with 1.28 the pause button is enabled and the resume button is not.  The call stack view is correct so everything looks like it's correctly stopped except for the debugger controls floating toolbar.  So there's no way to resume the thread.  Actually, you can type 'c' in the debugger console and it will cause the toolbar to refresh.  You can then resume from the toolbar and the process happily executes.  So it looks like some state refresh issues in the latest core debugger.  If that's the case then I'd expect it would impact everyone using MIEngine.

I did some looking at the history and am guessing that this change in the core is perhaps the culprit: https://github.com/Microsoft/vscode/commit/c805df9bd52e15beea01321091aed36e53c218a1

**Comment by pieandcakes** [comment]
@wpaul-magicleap I created an issue with VS Code as this is something they broke and is broken for more than just our extension.

https://github.com/Microsoft/vscode/issues/62085

If you want to commit there, that's probably the right place.

**Comment by wpaul-magicleap** [comment]
Great.  Thanks.
