### ISSUE TITLE
VS Code CPP Extension hogs up the CPU almost constantly in the latest version

### ISSUE THREAD

**Issue by ftrofin** [microsoft/vscode-cpptools#2742]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Mac OS 10.13.6
- VS Code Version: 1.28.2 (7f3ce96)
- C/C++ Extension Version: 0.19.0

I've been very happy with VS Code until recently when it updated to the latest version. It was nimble and fast, it just worked. Now it's slow and it hogs up my computer's CPU (constant CPU utilization 25-50% all the time VS Code is running). The extension that's using the CPU is the CPP extension which I've been using before with no issues.
The processes that show almost constant CPU usage are: "Code Helper" and "Microsoft.VSCode.CPP.Extension.darwin".

**To Reproduce**

Run the specified version of VS Code with the CPP Extension installed. Open a project folder with lots of C++ code. It's expected that upon the initial opening the Intellisense will do a lot of work in background. What's not expected is that it continues to do so after 3-4 days have already passed (for that project). When I look in the Activity Monitor to see which process is causing the high CPU usage I constantly see the CPP extension in the list (sometimes I see Code Helper).

**Expected behavior**

Same behaviour as the previous version (which after the initial indexing was very well behaved). No fans running on the laptop all the time.

**Additional context**

Here is a sample of the CPP extension when chewing up a lot of CPU in the background. Please let me know if I can help you diagnose the problem by providing any additional information.

[Sample of Microsoft.VSCode.CPP.Extension.darwin.txt](https://github.com/Microsoft/vscode-cpptools/files/2532052/Sample.of.Microsoft.VSCode.CPP.Extension.darwin.txt)

Not sure if it's relevant to this problem but I also noticed that the Cmd+P (open file) is very slow, it can take up to a minute to find a file, before it was finding it in seconds.
Search in files is also much slower than before. I frequently abandon searches because they don't complete (no results show up and the search is still running minutes later. If I exit VS Code and open it again, the file search works again, with instantaneous results  - seems that some process/service gets hanged in the background?)

**Comment by sean-mcmanus** [comment]
Do you have 0.19.0 or the just released 0.20.0? What version was good? 0.18.0? This code shouldn't have changed in a while.

The log shows it looking for new files to add to our database.

**Comment by ftrofin** [comment]
Thanks for the quick reply. A few minutes ago I had 0.19.0, I'm sure of it. I restarted VS Code and I see that now it shows 0.20.0 (interesting, no notification or asking the user if they want to update?).
The version that was good was the one from a few months back (before the VS Code September release).
I'm going to keep an eye on the new 0.20.0 to see if I still experience the same CPU churn and update this ticket.

**Comment by ftrofin** [comment]
Periodically I see "Code Helper" process raising to the top of CPU usage and staying there for 5-10 minutes without me doing anything on the computer. I took some samples of the process during that time and they all look very similar. I attached one here in case it helps. This constant churn of the CPU is causing my MBP fan to run almost all the time - not a good user experience.
[Sample of Code Helper-2.txt](https://github.com/Microsoft/vscode-cpptools/files/2532231/Sample.of.Code.Helper-2.txt)

**Comment by sean-mcmanus** [comment]
Our extension has no control (or known impact) on the Code Helper process of VS Code; however, there is a known issue in regards to the transparent rendering which our extension uses, which is fixed on the VS Code Exploration version (which uses a new renderer): see the thread at https://github.com/Microsoft/vscode-cpptools/issues/2704 or https://github.com/Microsoft/vscode/issues/52629 .

If the VS Code Exploration version doesn't fix your issue, I would file a VS Code issue.

**Comment by terris-anylog** [comment]
Same issue. Sometimes goes to 198% (I guess because I have 2 cpus?). What is it doing? I went all the way back to 0.18.1 and it has the same issue.

**Comment by terris-anylog** [comment]
I wonder if this has to do with my Bazel project. Bazel is loading boost source which can be found via smylinks named bazel-\* in the workspace directory. The extension ran for 24 hours and eventually stopped. I'm thinking that's it. Maybe we could get a feature to not process through symlinks.

**Comment by sean-mcmanus** [comment]
@terris-anylog You can add the paths to exclude to files.exclude to prevent the files from being parsed; however, we have a bug that may cause to still be insufficient because the files are still "processed" -- https://github.com/microsoft/vscode-cpptools/issues/3123 .

**Comment by bobbrow** [comment]
If you update to the latest version of the extension and your issue persists, please open a new issue with additional information that can help us investigate your issue.  Indexing code folders does consume a CPU core by default, but you can reduce the CPU usage using the `"C_Cpp.workspaceParsingPriority"` setting.  We also have a number of issues tagged as symlink improvements that could help address these problems in the future.

Thank you!
