### ISSUE TITLE
Goto & Peek Definition Not working correctly

### ISSUE THREAD

**Issue by warwickrudd** [microsoft/vscode-cpptools#2746]
I am currently running version 1.1.3 and the goto and peek definition work for system tables but not for user tables. Selecting goto definition for a system table creates the temp definition file in the local\temp folder. But for a user table this does not work. If I test this on Version 0.31.4 this works correctly.

I have just updated to 1.1.4 and the issue still exists and says No Definition found for the user table that this is being run against.

**Comment by bobbrow** [comment]
Which extension are you reporting a bug for?  This repo only covers the C++ extension and we're on version 0.20.0.

**Comment by warwickrudd** [comment]
Hi Bob,

I am not really sure which extension. This functionality used to work but did not work in my user group session last night, and if this able to be resolved in time for my session on Saturday in Portland forSQLSaturday that would be great.

Thanks

Warwick Rudd
Data Platform MVP (SQL Server), Microsoft Certified Master (MCM) - SQL Server
Principal Consultant
www.sqlmastersconsulting.com.au<http://www.sqlmastersconsulting.com.au>
+61 403 144 302

On 31 Oct 2018, at 12:55 pm, Bob Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


Which extension are you reporting a bug for? This repo only covers the C++ extension and we're on version 0.20.0.

**Comment by bobbrow** [comment]
It sounds like you're doing database stuff.  We will not be able to help you with that.  You'll need to find the correct extension owner, or let us know which extension you're using so we can point you in the right direction.  You can use the `Extensions: Show Enabled Extensions` command to pop open the list.

**Comment by warwickrudd** [comment]
Sorry I was in the wrong guy repository. This should have been for azure Data Studio

Thx

Warwick Rudd
Data Platform MVP (SQL Server), Microsoft Certified Master (MCM) - SQL Server
Principal Consultant
www.sqlmastersconsulting.com.au<http://www.sqlmastersconsulting.com.au>
+61 403 144 302

On 31 Oct 2018, at 1:25 pm, Bob Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


It sounds like you're doing database stuff. We will not be able to help you with that. You'll need to find the correct extension owner, or let us know which extension you're using so we can point you in the right direction. You can use the Extensions: Show Enabled Extensions command to pop open the list.
