### ISSUE TITLE
stdio.h "Include file not found in include directory"

### ISSUE THREAD

**Issue by kevinmoran** [microsoft/vscode-cpptools#275]
I've started having trouble including <stdio.h> in VSCode on Mac without getting this warning. I've added c_cpp_properties.json to my .vscode folder, with the include path "/usr/include" but the issue persists. 

I have no idea why this isn't fixing the warning, here are two folders open side by side; one has the issue, the other doesn't:

<img width="1172" alt="screen shot 2016-10-05 at 10 36 59 am" src="https://cloud.githubusercontent.com/assets/15050023/19097445/243addcc-8ae8-11e6-86bf-40a21444960b.png">

I feel like something has gone really weirdly wrong on my end, doubt it's reproducible.

**Comment by patricksuo** [comment]
http://stackoverflow.com/questions/28362994/where-is-my-stdio-h-in-mac
http://stackoverflow.com/questions/38162836/how-do-i-install-xcode-8-command-line-tools

**Comment by kevinmoran** [comment]
Thanks sillyousu, installing Xcode command line tools and relaunching VScode fixed my problem.

**Comment by mild0wl** [comment]
I have the same problem but in Windows 10. Please help me out soon...

**Comment by bobbrow** [comment]
If you are having trouble configuring IntelliSense, please open a new issue.  In the issue, let us know whether you have mingw or Visual Studio installed or if you are getting the standard headers from some other location.  Thanks!

**Comment by mild0wl** [comment]
Yes, I have opened the new issue.
@bobbrow
