### ISSUE TITLE
Option to re-use debug terminal instance

### ISSUE THREAD

**Issue by rewrking** [microsoft/vscode-cpptools#2756]
Type: Debugger

So this is related to the new option to set "externalConsole": false to use the integrated terminal (which rules of course). At the moment in 0.20.0, every time the debugger is launched, it creates a new terminal instance (1: cppdbg..., 2: cppdbg...) which you then have to close after you're done debugging otherwise you'll find yourself with a handful of leftover ones from each time the debugger was lauched. It would really nice it used a "shared" one like you can do in tasks.json (defined there under presentation > panel > shared). 

Another possibility would be to share the same terminal as the preLaunchTask & use its presentation settings.

That's it! Love this extension. Keep up the great work!

**Comment by pieandcakes** [comment]
@andrew-r-king You will need to propose that to [VS Code](https://github.com/microsoft/vscode/issues) as the implementation of that is on their side now. We make a call to VS Code and they handle all the terminal work.
