### ISSUE TITLE
Could not recognize constructor of non-STL class

### ISSUE THREAD

**Issue by ychen93** [microsoft/vscode-cpptools#2757]
Issue Type: <b>Bug</b>

```
#include <armadillo>
#include <vector>
using namespace std;
using namespace arma;

void foo() {
  vector<double> x1(10), x2(9); // Fine, can color correctly
  cube U(10,10,20), V(10,9,9); // U and V colored differently
  U(0,0,0) = 1;
  x1[0] = 0; // Both cannot correctly find definition when using "Peek Definition"
}
```

Extension version: 0.20.1
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|-psn_0_5149929|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bobbrow** [comment]
Code colorization improvements will be covered by #230.
I don't reproduce your "Peek Definition" issue (I removed the armadillo stuff since I don't have it).

![image](https://user-images.githubusercontent.com/12818240/47862359-30f3c780-ddb2-11e8-8fea-c8cc5255c604.png)

**Comment by ychen93** [comment]
> Code colorization improvements will be covered by #230.
> I don't reproduce your "Peek Definition" issue (I removed the armadillo stuff since I don't have it).
> 
> ![image](https://user-images.githubusercontent.com/12818240/47862359-30f3c780-ddb2-11e8-8fea-c8cc5255c604.png)

I am using Intel C++ Compiler (with Intel Parallel Studio installed), not sure if this matters.

**Comment by bobbrow** [comment]
It might matter.
Can you share your config (`c_cpp_properties.json`)?
Or share some logs?  Follow this guide: [How to enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and then reload the window.

**Comment by ychen93** [comment]
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/opt/intel/compilers_and_libraries_2018/mac/include",
                "/opt/intel/compilers_and_libraries_2018.3.185/mac/mkl/lib",
                "/opt/intel/compilers_and_libraries_2018.3.185/mac/mkl/include",
                "/opt/intel/compilers_and_libraries_2018.3.185/mac/compiler/include",
                "/Users/yuanchen/Documents/1Research/armadillo-9.100.5/include"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
This is really strange -- what does it show if you hover over the x1 variable? If you add the code below to foo does it work?
```
{
int x1;
x1; // Go to def
}
```
i.e. does it look like there's some problem parsing the vector type or is go to def more broken in general for local variables? Does Go to def for the vector work if it's defined as a global variable?

**Comment by ychen93** [comment]
> This is really strange -- what does it show if you hover over the x1 variable? If you add the code below to foo does it work?
> 
> ```
> {
> int x1;
> x1; // Go to def
> }
> ```
> i.e. does it look like there's some problem parsing the vector type or is go to def more broken in general for local variables? Does Go to def for the vector work if it's defined as a global variable?

It seems like a local variable issue. If I define x1 as global, it works fine. (But not for arma::vec x1)
Besides, there is always suggestion to include 2017 version of Intel Parallel Studio for \#include\<vector\>
![screen shot 2018-11-02 at 5 39 33 pm](https://user-images.githubusercontent.com/18510605/47946255-6ee21000-dec6-11e8-814d-131acbfc4062.png)

**Comment by sean-mcmanus** [comment]
Go to Def is not using the IntelliSense-based version because it fails to locate the definition of vector. Can you set your compilerPath to the Intel compiler? Setting the libraries directly in the includePath is error prone because there could be ordering/dependency issues. If you enable logging (https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) you can see what compiler settings and includes/defines we end up using.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
