### ISSUE TITLE
Where to put .gdbinit under Windows 10

### ISSUE THREAD

**Issue by zackgd1024** [microsoft/vscode-cpptools#2758]
Hello everyone

I need to debug some STL Variables.
So I must enable the GDB pretty printer in .gdbinit file by the following code under $HOME path by VSCode's definition.
`python`
`import sys`
`sys.path.insert(0, 'C:/Msys_K/msys64/mingw32/stlprettyprinter/libstdcxx/')`
`from printers import register_libstdcxx_printers`
`register_libstdcxx_printers (None)`
`end`

I have tried some paths like C:\Users\xxx\AppData\Roaming or C:\Users.
However, none of them works.
Does anyone kown VSCode's HOME path under Windows10.

Thanks

**Comment by pieandcakes** [comment]
@zackgd1024 its usually `%userprofile%` which is `c:\users\<username>`

**Comment by zackgd1024** [comment]
I've tried `c:\users\<username>`. Did not work.
However, `source` can work.
![image](https://user-images.githubusercontent.com/9695494/47892377-4c360400-de92-11e8-869f-b36a1b4dc7a4.png)

And STL printing works now.
![image](https://user-images.githubusercontent.com/9695494/47892442-a33bd900-de92-11e8-84fb-8a98a34fa932.png)

Thanks for your help @pieandcakes

**Comment by NewbieToEverything** [comment]
> I've tried `c:\users\<username>`. Did not work. However, `source` can work. ![image](https://user-images.githubusercontent.com/9695494/47892377-4c360400-de92-11e8-869f-b36a1b4dc7a4.png)
> 
> And STL printing works now. ![image](https://user-images.githubusercontent.com/9695494/47892442-a33bd900-de92-11e8-84fb-8a98a34fa932.png)
> 
> Thanks for your help @pieandcakes

life saver solution!
