### ISSUE TITLE
Not correctly detecting errors

### ISSUE THREAD

**Issue by BigfootN** [microsoft/vscode-cpptools#2763]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Archlinux
- VS Code Version: 1.28.2
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them):

  - Gruvbox Themes
  - Material Theme
  - Vim

- A clear and concise description of what the bug is.

Hello,

I noticed that the extension doesn't seem to notice all the errors and warnings in the code. For example, when writing this:

```
char **a;

a = "string";
```

It doesn't return any warning or error. Other than that, it seems to work fine.

I'm using `compile_commands.json` with the `-Wall -Werror -Wextra` flags enabled, and generated from `cmake`.

Thank you very much in advance.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. The issue has already been fixed for our pending 0.21.0-insiders release next week. I assume you're using C++ though (C should not give an error in your case)...well, if you expect a compiler warning in C, then that may be fixed after we add warning support (https://github.com/Microsoft/vscode-cpptools/issues/828 ).

**Comment by BigfootN** [comment]
Thank you very much for your quick response.

I was using C in fact.

Thank you for this great extension.

**Comment by sean-mcmanus** [comment]
Yeah, even with the "hidden" warnings enabled our parser doesn't show a warning for C files, so this will only be fixed for C++ in our next release.

UPDATE:

Should be fixed (for C++, not C) with 0.21.0-insiders (auto installed if `"C_Cpp.updateChannel": "Insiders"` is set, or the [offline vsix](https://github.com/Microsoft/vscode-cpptools/releases/tag/0.21.0-insiders)). Let us know if you find any problems with it.
