### ISSUE TITLE
Add better IntelliSense support for mingw with -fms-extensions set

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2765]
Our current parser understands gcc/clang mode and msvc mode, but when mingw is used with -fms-extensions the are bugs, e.g. type_info isn't in std (https://github.com/Microsoft/vscode-cpptools/issues/2623 ), so we currently default to -fno-ms-extensions, which causes uses of Microsoft extensions to give errors, e.g. https://github.com/Microsoft/vscode-cpptools/issues/2363 , which seems good enough for now unless more people complain.

**Comment by xLobito** [comment]
Greetings. 

https://github.com/Microsoft/vscode-cpptools/issues/2433. This topic covers the issue as well (Either on Linux, or MinGW).

**Comment by bobbrow** [comment]
The referenced bugs appear to be closed. I know we've gone back and forth on -fms-extensions over the years. I don't think this bug is tracking anything actionable at this point. Closing.
