### ISSUE TITLE
the extension keeps updating dependencies, but always failed

### ISSUE THREAD

**Issue by yilinfang** [microsoft/vscode-cpptools#2770]
the internet connection is fine, can i download the offline package or just stop the extension updating dependencies forever.

**Comment by aunsbjerg** [comment]
Being behind a coorporate firewall or proxy can cause the extension to never update.

You can do an offline install by downloading the .vsix file from the release page which is appropriate for your system. In vscode, you can then install the downloaded vsix file by typing in "vsix" in the command pallette (ctrl+p).

You will have to do this everytime cpptools updates though.

**Comment by yilinfang** [comment]
> Being behind a coorporate firewall or proxy can cause the extension to never update.
> 
> You can do an offline install by downloading the .vsix file from the release page which is appropriate for your system. In vscode, you can then install the downloaded vsix file by typing in "vsix" in the command pallette (ctrl+p).
> 
> You will have to do this everytime cpptools updates though.

 I have two pc , the updating process works very well in  win10 but always failed in mac os, maybe the sever provides the macos-cpptools has problem?

**Comment by pieandcakes** [comment]
@yilinfang We upload the packages to the same service. I have verified that macOs works although I don't know why it doesn't in your instance. 

You can download the offline macOs releases from our [release tab](https://github.com/Microsoft/vscode-cpptools/releases).

**Comment by yilinfang** [comment]
@pieandcakes fine, i will do my work with my windows, thanks a lot.

**Comment by dexwerx** [comment]
Is there a reason this extension doesn't use the proxy like the VS Code updates?

**Comment by sean-mcmanus** [comment]
@dexwerx What do you mean by "the proxy"? Our downloading code can be found at https://github.com/Microsoft/vscode-cpptools/blob/c8e30c70b1a294005d525fe3b86c85b89fb33710/Extension/src/packageManager.ts . Are you seeing a bug?
