### ISSUE TITLE
Switching configs and Reset IntelliSense Database can lead to failures when recursive includes are used

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2775]
The recursive includes code that causes files to parse doesn't abort when switching configs or reset intellisense database is done. This can cause problems, such as the correct files not being parsed. Using a Reload Window afterwards seems to fix the issues. Not sure how important this is to fix.

**Comment by bobbrow** [comment]
Closing stale issue with no upvotes.
