### ISSUE TITLE
How can I keep this semicolon here?

### ISSUE THREAD

**Issue by VirFunc** [microsoft/vscode-cpptools#2777]
Issue Type: <b>Bug</b>

I typed a line of code like this.

//This is my code
![image](https://user-images.githubusercontent.com/28671722/48052326-9563bc00-e1e2-11e8-8508-b155d9521514.png)

And I turned this on.
![image](https://user-images.githubusercontent.com/28671722/48052111-09ea2b00-e1e2-11e8-8414-6a9d4d9f5d1b.png)

Then when I typed semicolon behind it.

![image](https://user-images.githubusercontent.com/28671722/48052251-64838700-e1e2-11e8-8bfe-419d86fc7c5d.png)
What? No!
I thought it was going to work like Visual Studio.
I have tried closing other extensions, but it didn't work.
Here are my settings.

![image](https://user-images.githubusercontent.com/28671722/48053020-8251eb80-e1e4-11e8-8f0b-f4fac405d130.png)
I hope it will work well soon, I like vscode!

Extension version: 0.20.1
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (9.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
I would recommend disabling FormatOnType. We haven't implemented Visual Studio's formatting and instead just call clang-format on the line.

**Comment by bobbrow** [comment]
And please go upvote #657 if you would like true Visual Studio formatting.

**Comment by VirFunc** [comment]
@sean-mcmanus OK. Thanks.
@bobbrow I have voted.
Thanks for your replies.
