### ISSUE TITLE
Please configure the cpp_properties file to use gcc compiler instead of MSVC compiler.

### ISSUE THREAD

**Issue by mdmozibur** [microsoft/vscode-cpptools#2779]
I think  a lot of people, if not all of them, use VSCode for c++  to compile files with gcc compilers. But the default include path or compilerPath or browse path aren't set to gcc default folder. It ' ll be a great help if I download this extension and have all the settings working correctly.

It's very annoying to do all the settings manually.

Or please add an option to choose between MSVC and GCC compiler.
Thanks.

**Comment by sean-mcmanus** [comment]
If you don't have cl.exe installed and have WSL'S /usr/bin/gcc (etc.) installed we will choose that default. Are you on Windows? What compilerPath are you setting manually? We have a user-level C_Cpp.default.compilerPath setting you can set once.

**Comment by mdmozibur** [comment]
Yes, I am on windows. I set the compilerPath to MinGW gcc bin folder. And yes, I have Visual Studio installed with VC++ (is that what you mean by cl.exe?). But look, we users normally don't use VSCode for VC++, and also, a lot of extensions' (like Code Runner) default isn't VC++, rather it's GCC. So, my recommendation is to keep this associated with GCC, even if cl.exe is found and GCC is also found. Most convenient will be to let the user choose.

**Comment by bobbrow** [comment]
Our telemetry disagrees with your assertion about compiler preference in VS Code, but we have provided a way for you to change the defaults for all the folders you open.

Set `"C_Cpp.default.compilerPath": "c:\path\to\gcc.exe"` in the User Settings.
