### ISSUE TITLE
Building/debugging using cmd/msvc 14

### ISSUE THREAD

**Issue by rsirefelt** [microsoft/vscode-cpptools#278]
Hi 2 questions: 

1: I've now spent almost 4 hours on trying to build/debug a helloWorld binary
using the cmd terminal and the msvc 14 compiler on windows without any success. 
Does anyone know if this can be done in an easy way? 
The problem I have is that I need to run vcvarsall.bat in cmd before being able to
find the compiler, and this seems hard to do in tasks.json.
(I would rather not add the vcvarsall.bat paths permanently to PATH.) 

2: Are there a forum regarding this extension where the above question is better 
asked then here?

**Comment by delmyers** [comment]
@rsirefelt 

When you installed the compiler tools from Microsoft, did it also install something called the "Developer Command Prompt"? If yes, then I would suggest launching Visual Studio Code from that command prompt. It should set up the path that you need to use the vc tools.

**Comment by rsirefelt** [comment]
@delmyers 

Ahh, this way of doing it did work. 
Thanks!

I was trying to run VS Code from windows desktop but did not manage to set 
the "Developer Command Prompt" as the "terminal.integrated.shell.windows" settings. 
Do you know if this also can be done?
i.e. launch VS Code from windows explorer but still use the "Developer Command Prompt" 
as the default VS Code terminal.

**Comment by delmyers** [comment]
@rsirefelt 
I got this to work, though it isn't fully tested. If you create a new shortcut, and set the "Location" of the shortcut to:

`"C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\Common7\Tools\VsDevCmd.bat" & "C:\Program Files (x86)\Microsoft VS Code\Code.exe"`

And the "start in" field to:

`"C:\Program Files (x86)\Microsoft VS Code"`

It looks as though the shortcut will launch vscode in the context of the developer command prompt. Note, this will leave an additional command window floating around, which might be a little annoying. I know that there are ways to get the command prompt to launch and then close immediately, but I could not get that to work.

Another option would be to create a batch file that simply executed `VsDevCmd.bat` and then launched code, and set that as a shortcut. That should work.

**Comment by rsirefelt** [comment]
Thanks for all the help! 
I ended up using the first solution you suggested.

**Comment by pieandcakes** [comment]
It looks like this is resolved. If it isn't, please reopen and/or comment.

Thanks
