### ISSUE TITLE
support relative paths for forcedInclude

### ISSUE THREAD

**Issue by pagdot** [microsoft/vscode-cpptools#2780]
I'd like forcedInclude to use the specified include paths. At the moment it is necessary to specify the full path.

**Comment by bobbrow** [comment]
What exactly do you mean?  `"forcedInclude": "foo.h"` will use the `"includePath"` to locate foo.h?

**Comment by pagdot** [comment]
I've included headerfiles from included folders, but they don't get included unless I specify them with full path

**Comment by sean-mcmanus** [comment]
This looks like it would be an easy bug for us to fix -- we fixed it 4 months ago for forced includes that are specified in the compile_commands (i.e. if a non-valid path is in forcedInclude, then try appending each includePath to find the first one that is valid).

**Comment by ivankravets** [comment]
PlatformIO users also experience this issue https://github.com/platformio/platformio-core/issues/3379

How is it difficult to fix it? Do we have any workarounds?

/cc @valeros , @sstaub

**Comment by pagdot** [comment]
@ivankravets I just took a (quick) look into it and it may be a problem with the actual (external) languageserver. I don't think it is open source :/ because there are only links to binaries.

**Comment by ivankravets** [comment]
> I don't think it is open source

This extension is open source. Microsoft claims that VSCode is open source.

**Comment by pagdot** [comment]
Yeah, kind of... But it seems to use a closed source language server. In the [package.json Line 1779](https://github.com/microsoft/vscode-cpptools/blob/master/Extension/package.json#L1779) is the download link for binaries containing the languageserver. This repo only seem to contain the client. I haven't seen a reference to the source of the actual languageserver. If you find its source I will take a look into it

**Comment by ivankravets** [comment]
> But it seems to use a closed source language server

This is the main reason why do we have a lot of issues and a slow development process. The community can't contribute and help.

@robotdad what is a reason for keeping this project close sourced?

**Comment by sean-mcmanus** [comment]
- It's easy to fix. See my comment https://github.com/microsoft/vscode-cpptools/issues/2780#issuecomment-582145983 .
- But you're correct that the fix is in our closed source language server.
- The main reason the language server is closed source is because our parser is licensed from another company's closed source parser. There are potential changes in the (not short term) future that could allow us to open source more code.
- One potential workaround is to convert the relative paths to absolute paths yourselves, via the same method we would do (appending the relative path onto each includePath in succession until a valid path is found).

**Comment by ivankravets** [comment]
@sean-mcmanus thanks so much for the quick answer! Yes, I got you. We did a quick fix on our side https://github.com/platformio/platformio-core/commit/fbfbf340c12caf56d8566e24df8c14441d5c9c68 and plan to publish bugfix release of PIO Core 4.2.1 next week.

Could you check this `mbed/.vscode/c_cpp_properties.json`  https://pastebin.com/RfiSbpTZ? 

- Are structure and data goo?
- Do you have any hints/recommendations?
- Is it OK that we have empty `""`` blocks in arrays? It is simpler for us to generate this config.

Thanks!

**Comment by sean-mcmanus** [comment]
@ivankravets The data looks fine to me. The empty `""` in arrays is fine -- we just ignore them. I don't have any hints/recommendations.

**Comment by sean-mcmanus** [comment]
Should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders2 .

**Comment by sean-mcmanus** [comment]
Should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders2 .

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
