### ISSUE TITLE
Upgrade to VS Code's webview API 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-cpptools#2781]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by sean-mcmanus** [comment]
@mjbvz Our extension has removed our dependency on vscode.previewHtml.
