### ISSUE TITLE
Doesn't show structure definition in other C files.

### ISSUE THREAD

**Issue by byteroll** [microsoft/vscode-cpptools#2784]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Microsoft Windows [version 10.0.17763.107] & WSL Ubuntu18.04
- VS Code Version: 1.28.2 (user setup)
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): none

A structure `epoll_event` definited in **epoll.h**, it is be used in other C file. The structure doesn't show anything when I hover over it and it isn't be highlight. I try **Go to Definition**, the pop_up is _**No definition found for epoll_event**_
 
_epoll.h_
```
struct epoll_event
{
    uint32_t events;	/* Epoll events */
    epoll_data_t data;	/* User data variable */
} __EPOLL_PACKED;

```
_myfile.c_
`epoll_event event;`

**To Reproduce**

1. create a C file.
```
#include <sys/epoll.h>
int main(){
    epoll_event event;
    return 0;
}
```
2. right click `epoll_event`, then click **Go to Definition**.

**Expected behavior**

Jump to epoll.h file.

**Screenshots**

![a](https://user-images.githubusercontent.com/15176699/48118315-e4732500-e2a6-11e8-82f1-d94ac705ec79.png)

![b](https://user-images.githubusercontent.com/15176699/48118382-0e2c4c00-e2a7-11e8-8882-05429bd3e4ab.png)

**Comment by byteroll** [comment]
And cpptools will not show the variable list.
![d](https://user-images.githubusercontent.com/15176699/48119664-cf989080-e2aa-11e8-847b-301a04abd5ca.png)

**Comment by bobbrow** [comment]
I don't write anywhere near as much C as C++, but I thought this was the syntax for declaring a struct variable that doesn't have an alias.
```cpp
struct epoll_event event;
```
[reference](https://en.wikipedia.org/wiki/Struct_(C_programming_language))

This works for me in WSL if I use the `struct` keyword in front of the declaration.

![image](https://user-images.githubusercontent.com/12818240/48151540-5f701780-e276-11e8-8856-0ffcf97e5149.png)

**Comment by byteroll** [comment]
> I don't write anywhere near as much C as C++, but I thought this was the syntax for declaring a struct variable that doesn't have an alias.
> 
> ```c++
> struct epoll_event event;
> ```
> 
> [reference](https://en.wikipedia.org/wiki/Struct_(C_programming_language))
> 
> This works for me in WSL if I use the `struct` keyword in front of the declaration.
> 
> ![image](https://user-images.githubusercontent.com/12818240/48151540-5f701780-e276-11e8-8856-0ffcf97e5149.png)

Thank you, you are right. I got them mixed up. This issue could be closed.
