### ISSUE TITLE
compilerPath property doesn't populate with the default chosen for non-cl.exe compilers

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2788]
When /usr/bin/gcc is chosen as the default compiler (such as if that is set by C_Cpp.default.compilerPath), then when an edit configuration is done the compilerPath is not populated with the default chosen. Ideally, it would behave the same as when cl.exe is the default.

**Comment by bobbrow** [comment]
It is not required to set any of the properties in `c_cpp_properties.json`, so I disagree that we should do that.  I would be ok with putting `"compilerPath": "${default}"` when the `C_Cpp.default.compilerPath` setting is set, but if we do it for this setting, a case could be made to do it for all settings and then `c_cpp_properties.json` starts to look like a mess of `${default}`s.

**Comment by bobbrow** [comment]
I'm not sure what this issue is about. I don't see the Compiler Path being pre-populated with anything on Windows with cl.exe. I suspect it is just stale at this point and we won't be making any changes here.
