### ISSUE TITLE
vscode-cpptools can not be used on the last updates

### ISSUE THREAD

**Issue by ZCShou** [microsoft/vscode-cpptools#279]
- VSCode Version: Code - Insiders 1.7.0-insider (cf203e09145586b96497eab230253d686c2b2a2d, 2016-10-11T06:11:07.928Z)

Steps to Reproduce:
1.When VSCdoe opens last floder including some C/C++ file automatically, It will crash.
3.Only display on the last updates

**Comment by edumunoz** [comment]
Hi @ZCShou,

What version of the extension are you using?
What operating system are you using?

When you say "it will crash", do you mean VSCode crashes or some process in the extension? What error message do you see when this happens?

Edit: I tried the latest version for the extension (0.9.2) and VSCode Insiders (1889442ff090ef8170814a98698506300962dbba) and I didn't have any problems.

**Comment by ZCShou** [comment]
VSCode Version: Code - Insiders 1.7.0-insider (cf203e09145586b96497eab230253d686c2b2a2d, 2016-10-11T06:11:07.928Z)
OS：Win10 14393
extension： (0.9.2)
@edumunoz  Maybe this issue is only for me. I create another folder, but this issue also can not display.
Maybe is it related to my SVN? I will have a try again. Thank you for your help.

![4](https://cloud.githubusercontent.com/assets/8591065/19333030/4bb3656c-9124-11e6-942b-ce67b22805ed.gif)

**Comment by edumunoz** [comment]
Thanks for your response! I just tried the latest insiders build on Windows 10 and can't repro this either.

However, it seems like the whole editor becomes unresponsive, can you check the task manager to see if any process (especially `Code - Insiders.exe` or `Microsoft.VSCode.CPP.Extension.exe`) are using high CPU percentage?

Also try the latest insiders build to see if there was an issue with that particular build you tried.

Also, does this occur if you uninstall the C/C++ extension? Does this occur when you open any other type of file?

**Comment by sean-mcmanus** [comment]
Do you have other extensions installed? Does it repro without our extension installed? I have observed similar freezes when using other extensions in which the VS Code UI can freeze with the unresponsive window. From what I can tell, VS Code itself has the potential for freezing issues, because I don't know (yet) how an extension can freeze VS Code on its own (normal high CPU usage in our extension.exe or .ts files doesn't freeze the UI).

**Comment by ZCShou** [comment]
I only used vscode-icon extension and vscode-cpptools extension. I find this issue will not display when I use VScode 1.6 stable. So maybe It's VScode Insiders's problem.But I can not find reason. Someone has repored this issue. thanks!

**Comment by bobbrow** [comment]
It sounds like this issue was resolved.  Please reactivate if there is something else we need to investigate.  Thank you.
