### ISSUE TITLE
It needs many time to updating IntelliSense

### ISSUE THREAD

**Issue by Jackie-Yang** [microsoft/vscode-cpptools#2790]
**Type: LanguageService**

There are too much files to index in my project, so it need many time to update IntelliSense

**To Reproduce**

1.Autocomplete ( Sometimes it takes more time )
![2018-11-08 14 43 20](https://user-images.githubusercontent.com/18381153/48182220-60cc3d80-e365-11e8-8ae0-e0851ca94c7b.gif)

Hope it can show symbols in this file first like this:
![2018-11-08 14 44 15](https://user-images.githubusercontent.com/18381153/48182418-07184300-e366-11e8-93cb-77a6b98d2f18.gif)

2.  "Go to symbol" spends lots of time to load, though it  can show immediately If IntelliSense update finish,  but when I type something, it will update again, so it need many times to show symbol
![2018-11-08 15 00 02](https://user-images.githubusercontent.com/18381153/48182745-527f2100-e367-11e8-8537-0946884b174e.gif)

**Describe the bug**
- OS and Version: Win 10 (CPU: i5-6300HQ RAM:8G)
- VS Code Version:1.28.2
- C/C++ Extension Version:0.20.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**Comment by bobbrow** [comment]
We are actively working on performance issues like this and hope to have some of them available in the next release.

**Comment by Jackie-Yang** [comment]
@bobbrow By the way, our codes is on the server.

**Comment by bobbrow** [comment]
Ok.  Our current work is not specifically targeting that scenario, but you may see some improvement when we release it.

**Comment by Jackie-Yang** [comment]
@bobbrow Thx~ 
And when is the next update release?

**Comment by bobbrow** [comment]
The next release is the second week of December, but it doesn't look like the changes we're working on will be ready in time.

**Comment by sean-mcmanus** [comment]
@Jackie-Yang Is the performance better for you with 0.22.1?

**Comment by Jackie-Yang** [comment]
@sean-mcmanus 
My project is more lightly than before, but cpptools is still unstable, sometimes it still need to update for a long time, and intelliSense and auto format is not work at this time, but it work normally in the last minute. Sometimes I have to delete the database files and reopen my project, it drive me crazy ...

<img width="423" alt="image" src="https://user-images.githubusercontent.com/18381153/56637515-6cef5180-669e-11e9-9afb-dfcaa8508897.png">

**Comment by Colengms** [comment]
There hasn't been activity on this thread for quite a while.  @Jackie-Yang , Are you still seeing an issue?  If so, please reply here and we can reopen this.
