### ISSUE TITLE
BUG: compilerPath is not properly set when compile_commands.json is loaded from a default setting

### ISSUE THREAD

**Issue by g-arjones** [microsoft/vscode-cpptools#2793]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 16.04
- VS Code Version: 1.28.2
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.

If I set the compiler commands database path for each folder in a workspace (in .vscode/c_cpp_properties.json) the compilerPath setting is properly set. If, however, I set it as a default value for the entire workspace (C_Cpp.default.compileCommands in the .code-workspace file), then compilerPath is not set.

**Comment by bobbrow** [comment]
Compiler information for IntelliSense should be in the compile_commands.json file, so compilerPath would be ignored in this case.

...Though now that I think of it, we still haven't done the work to update the browse path based on the contents of compile_commands.json (#1715).  Is that the underlying issue here?

**Comment by g-arjones** [comment]
> so compilerPath would be ignored in this case

Doesn't seem to be the case since setting `compilerPath` manually fixes the missing headers issues.

> Is that the underlying issue here?

That's another issue. Some system paths are not defined explicitly in the build command so there's the possibility that system paths would still be missing when using a different compiler.

I can provide steps to reproduce but the process is a bit involved. Would you be interested?

**Comment by bobbrow** [comment]
Based on your first response, I should be able to craft a quick repro case.  It would also be helpful if you could share the entry from compile_commands.json for the file that is involved with this problem.  You can anonymize paths if you are working on a closed-source project.  Those aren't really what we're after here anyway.

Another thought is that if you open a file that doesn't have an entry in the compile_commands.json (perhaps a header file) and the extension is unable to map it to the compile commands database, the extension will fallback to using the includePath and compilerPath in your `c_cpp_properties.json` to provide IntelliSense for it.

**Comment by g-arjones** [comment]
> It would also be helpful if you could share the entry from compile_commands.json for the file that is involved with this problem

I can do that, sure.

>  the extension will fallback to using the includePath and compilerPath

That would break everything since the only thing I am setting is `compileCommands`, the extension would not find any header at all because `includePath` is empty and the other  (non-system) headers are not in a discoverable place.

**Comment by g-arjones** [comment]
Here you go:

1. Run this in an empty folder: https://gist.github.com/g-arjones/33d7b5db5cdfd9d705cbc0ea6121174c
2. Add `"C_Cpp.default.compileCommands": "${workspaceFolder}/compile_commands.json"` to your global vscode configuration
3. Open the `sample` folder that was created in a fresh vscode instance
4. IntelliSense will complain that it can't find "sys/syslimits.h"
5. Now add `"C_Cpp.default.compilerPath": "<PATH TO YOUR EMPTY PREVIOUSLY EMPTY FOLDER>/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-g++"` to your global vscode confguration
6. IntelliSense is happy again...

If you skip steps 2 AND 5 and just add `"compileCommands": "${workspaceFolder}/compile_commands.json"` locally to c_cpp_properties.json, IntelliSense will find "sys/syslimits.h" even if you don't set `compilerPath`

Hope it helps!

**Comment by g-arjones** [comment]
@bobbrow Please, let me know when/if you were at least able to reproduce. Thanks!

**Comment by bobbrow** [comment]
I'm sorry you had to go into all that detail.  I was able to repro with the simple project I created but I got sidetracked debugging the debugger while looking at this.  But I found the bug here.  This appears to have broken after we started forcing a default value for compilerPath.  Switching the order of the compiler lookup for the compile_commands.json case seems to be doing the right thing for me in my repro project.  I'll run this fix through our tests to see if I'm missing anything before committing it though.

**Comment by bobbrow** [comment]
Thanks for reporting this issue, BTW!

**Comment by g-arjones** [comment]
No problem.. :+1:

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.21.0-insiders (auto installed if `"C_Cpp.updateChannel": "Insiders"` is set, or manually installed from the [offline vsix](https://github.com/Microsoft/vscode-cpptools/releases/tag/0.21.0-insiders)). Let us know if you find any problems with it.

**Comment by g-arjones** [comment]
Fixed in my test case as well. Thank you, guys!
