### ISSUE TITLE
cpp.hint isn't usable for files outside the workspace root

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2797]
It seems like it should be (could be a regression from the cpp.hint caching added a few months ago). Up vote this if it's a problem for you.

**Comment by ghost** [comment]
Even modifying the cpp.hint in the vscode cpptools extensions folder doesn't do anything.

**Comment by sean-mcmanus** [comment]
Hmm...it should. Did you do a Reload Window? Can you provide more repro info?

**Comment by ghost** [comment]
Yes I did a reload, even with a cpp.hint in the workspace it doesn't work. Maybe I'm doing something wrong? It doesn't provide hints for when I type `_NAME_::` and it gives errors as it doesn't know it is a macro.

Edit: I realize now I misread the issue, my cpp.hint just doesn't work at all for any files even in the workspace.

![problem](https://user-images.githubusercontent.com/42397654/50043683-93ddad00-0046-11e9-8daa-5b40ff99281d.png)

**Comment by sean-mcmanus** [comment]
cpp.hint defines are only for our global symbol parser and not for the IntelliSense engine. To get the IntelliSense to pick up the defines you can add them the defines section in c_cpp_properties.json or the C_Cpp.default.defines or set the forcedInclude setting to a file that will be auto-included, which maybe could be the cpp.hint file.

**Comment by bobbrow** [comment]
This doesn't appear to be a high impact issue. Closing for now.
