### ISSUE TITLE
Unable to lookup symbols in platform headers

### ISSUE THREAD

**Issue by badmitrii** [microsoft/vscode-cpptools#2798]
**Type: LanguageService**

- OS and Version: Linux Ubuntu 18.04
- VS Code Version: vscode 1.28.0
- C/C++ Extension Version:  0.20.1
- Other extensions you installed (and if the issue persists after disabling them): CMakeTools, Vim, CodeLLDB

The symbols defined in platform headers (like `sys/inotify.h` on Linux) cannot be looked up using the global symbol search. But it works just fine if we open the header file. 

**To Reproduce**
1. Use the following `c_cpp_properties.json`:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}
```
2. Type any symbol name defined in platform header e.g. as follows: 
`#inotify_init`

**Expected behavior**
Looking up symbols globally that are defined in platform headers as well.

**Screenshots**
1. Unable to find `inotify_init`:
![screenshot from 2018-11-09 09-12-19](https://user-images.githubusercontent.com/6568143/48246432-80fd0a80-e400-11e8-847d-d1ab573dc6e7.png)

2. Lookup works ok:
![screenshot from 2018-11-09 09-14-54](https://user-images.githubusercontent.com/6568143/48246473-9d994280-e400-11e8-8181-a3f53cb6165a.png)

**Comment by bobbrow** [comment]
The default setting for workspace symbols is to just show the ones in your workspace folder.  If you want to see external symbols, try changing this setting:

![image](https://user-images.githubusercontent.com/12818240/48278765-4f397300-e403-11e8-84ea-283c9e581d46.png)

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity and by design.
