### ISSUE TITLE
spawn .../corerun ENOENT when trying to debug C++ on Mac

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-cpptools#28]
_From @DanB91 on April 22, 2016 2:25_
- VSCode Version: 1.0.0 (1.0.0)
- OS Version: Mac OS X 10.11.4

Hi, I am trying to debug my program with the following configuration:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (GDB)",
            "type": "cppdbg",
            "request": "launch",
            "launchOptionType": "Local",
            "miDebuggerPath": "/usr/local/bin/gdb",
            "targetArchitecture": "x64",
            "program": "${workspaceRoot}/build/rg",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}/build",
            "environment": []
        }
    ]
}
```

When I try to run this configuration I get the error: `spawn <home>/.vscode/extensions/ms-vscode.cpptools-0.4.2/debugAdapters/corerun ENOENT. Stopping the debug adapter.`

Can't seem to find this issue anywhere else. gdb is signed and works on the command line.

Steps to Reproduce:
1. Try to launch debug configuration

Any help would be greatly appreciated.  Thanks!

_Copied from original issue: Microsoft/vscode#5637_

**Comment by DanB91** [comment]
I just discovered that "corerun" was not in the debugAdapters directory.   I deleted the extension, reinstalled it and now it seems to be working.  Not sure why corerun was missing...  

Feel free to close this issue.

**Comment by delmyers** [comment]
All of these kinds of issues should go away now. The debugger portion of this extension no longer depends on corerun.

**Comment by sushovannits** [comment]
Hi I installed the latest version of VSCode. I am trying to compile and debug a hello world in C++. I keep getting this error along with EPIPE error. Please help. I have MingW installed and from Windows cmd I can compile and debug a program in gdb.
![image](https://cloud.githubusercontent.com/assets/5388540/15499104/07811c82-21c0-11e6-8e8c-bc7d8c0f1062.png)
