### ISSUE TITLE
"${workspaceFolder}/**" isn't auto-added if includePath isn't set but c_cpp_properties.json exists

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2800]
If c_cpp_properties.json exists, then "${workspaceFolder}/**" is automatically used, but otherwise if "includePath" doesn't exist in the config then it's not added, even though the other system includes are added. It confused me...not sure if it's a common problem though, since the default c_cpp_properties.json has the includePath set. I only hit it because I deleted it, because I wanted to "revert to the defaults", but it didn't work as expected.

**Comment by michelleangela** [comment]
We are currently unable to address this feature request since we are focusing on higher priority features and bugs right now.  We'll tag this for follow up in case it receives more interest from the community, but to keep our issue count manageable, we're closing this issue for now.
