### ISSUE TITLE
headers

### ISSUE THREAD

**Issue by shyam1s15** [microsoft/vscode-cpptools#2801]
Issue Type: <b>Feature Request</b>

i am facing many issues related headder files, I dont know how to solve it please help me

Extension version: 0.20.1
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bobbrow** [comment]
Can you be more specific?  Have you read through our documentation?  This one in particular might be of help:  [Frequently asked questions](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md)

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
