### ISSUE TITLE
Go to definition not correct

### ISSUE THREAD

**Issue by nxyd** [microsoft/vscode-cpptools#2802]
- VS Code Version: 1.29.0-insiders
- C/C++ Extension Version: 0.21.0-insiders

I found that when a function contains parameter 'void', then Go to definition on this function is not correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/3884211/48302697-ab52e300-e53a-11e8-8801-c47cc7063449.png)

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this (and sorry for not catching this issue ourselves). It should be fixed in our next insiders release.

**Comment by sean-mcmanus** [comment]
Go To Def with func(void) should be fixed now with our latest Insiders release: https://github.com/Microsoft/vscode-cpptools/releases . If you're using VS Code Insiders or have http.proxySupport not set to "off", you might not get the 0.21.0-insiders2 update automatically with C_Cpp.updateChannel set to "Insiders".
