### ISSUE TITLE
how can i get c/c++ plugin's database path in other vscode extension,is there any api?

### ISSUE THREAD

**Issue by alianZhen** [microsoft/vscode-cpptools#2804]

**Comment by bobbrow** [comment]
There is no API to retrieve the database path.  What would you plan to use it for?

**Comment by alianZhen** [comment]
c/c++'s symbol search is too slowly to use,.So, I want to parse the database to making a symbol list for quickly in-time searching!   And is there any caller or called relation property in it???

**Comment by sean-mcmanus** [comment]
The database is SQLITE. You can open the file in a SQLITE viewer such as DB Browser for SQLite. Implementing your own reader of the database doesn't seem like it would be an easy thing to do.

**Comment by bobbrow** [comment]
We do not intend to export the database's path for other extensions to query.  If you can provide more information about what scenarios are slow for you we can try to address the root cause.  Can we clone your project?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
