### ISSUE TITLE
Global symbol lookup does not work for platform headers until it is used.

### ISSUE THREAD

**Issue by badmitrii** [microsoft/vscode-cpptools#2805]
**Type: LanguageService**
In order to lookup symbols from platform headers we need to use it first (e.g. add `#include` somewhere in the project). Otherwise it does not work.

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.28.0
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): Vim, CodeLLDB
- A clear and concise description of what the bug is.
The global symbol lookup does not look at the platform headers even after adding it to the workspace settings by hand.

**To Reproduce**
Use configuration:
settings.json
```
{
    "files.associations": {
        "stdio.h": "c",
        "cstdio": "c",
        "stdint.h": "c",
        "cstdint": "c",
        "test.h": "c",
        "ioctl.h": "c"
    },
    "C_Cpp.workspaceSymbols": "All"
}
```
c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "configurationProvider": "vector-of-bool.cmake-tools",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

1. Create an empty c/c++ project
2. Click on "the global symbol lookup button" (e.g. Ctrl+P>#)
3. Type `ioctl`
4. See **_no_** `ioctl(int, unsigned long int, ...)` in the symbols.
5. Add some `c` file (e.g. `main.c`) and add `#include <sys/ioctl.h>`
6. Click on "the global symbol lookup button" again
7. Type `ioctl`
8. See the desired declaration being found

**Expected behavior**
I expected to be able to find declarations in platform headers even if they are not used yet.

**Screenshots**
Before adding the `#include <sys/ioctl.h>`
![screenshot from 2018-11-12 09-28-20](https://user-images.githubusercontent.com/6568143/48330754-be5ed380-e65e-11e8-8e60-44a0b86882b1.png)

After adding `#include<sys/ioctl.h>` into some file
![screenshot from 2018-11-12 09-37-09](https://user-images.githubusercontent.com/6568143/48330763-cd458600-e65e-11e8-9843-b7c2e8b69d03.png)

**Comment by bobbrow** [comment]
Please see this documentation: [limitSymbolsToIncludedHeaders](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md#limitsymbolstoincludedheaders)

We disable parsing unincluded header files outside the ${workspaceFolder} by default because it is very expensive and most people do not want/need them.  If you set the configuration setting linked above to `false` you should get the behavior you expect.
