### ISSUE TITLE
IntelliSense engine loads CPU too much when switching branches in git

### ISSUE THREAD

**Issue by fregloin** [microsoft/vscode-cpptools#2806]
**Type: LanguageService**

C/C++ for Visual Studio Code

**Describe the bug**
- OS and Version: Ubuntu 16.04
- VS Code Version: 1.28.2
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): matthewferreira.cppcheck (0.2.2), ms-python.python (2018.10.1), igordvlpr.trimspaces
(Initial release)
- A clear and concise description of what the bug is.
This extension often eats 100% CPU time (1 core on 4 core CPU).
We have quite big project. I think this is because of IntelliSens files scan job.

Is it possible to set some CPU time consumption threshold?

**To Reproduce**
Almost always reproduces after VSCode starting.

**Expected behavior**

No high CPU load

**Comment by bobbrow** [comment]
Try using the `C_Cpp.workspaceParsingPriority` setting.

**Comment by fregloin** [comment]
Thank you very much! It was exact what i needed!

----- Original Message -----

**Comment by fregloin** [comment]
Well, this setting doesn't work :(. Still 100% CPU load

----- Original Message -----

**Comment by bobbrow** [comment]
Which process is using 100% CPU, and for how long and under what circumstances?  There are two processes at work:
1. Microsoft.VSCode.CPP.Extension.exe
2. Microsoft.VSCode.Cpp.IntelliSense.Msvc.exe

**Comment by sean-mcmanus** [comment]
It can be 100% CPU if there is foreground work, such as after opening a file. Are you seeing 100% CPU when you just open a C++ workspace with no files open and then use some command like "C/C++: Navigate..." to activate our extension.

**Comment by fregloin** [comment]
Hello. This process '/home/anton/.vscode/extensions/ms-vscode.cpptools-0.20.1/bin/Microsoft.VSCode.CPP.Extension.linux' eats CPU.
I suppose, i starts eating cpu after git checkout another branch...

----- Original Message -----

**Comment by sean-mcmanus** [comment]
Fixed in our latest Insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders.

**Comment by fregloin** [comment]
Thanks a lot!
