### ISSUE TITLE
"TypeError: Cannot read property 'map' of undefined at asCompletionResult" occurs when a file is editted before the extension fully activates

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2807]
Open a workspace and immediately edit a cpp file. Use Toggle Developer Tools to see the error output:

```
[Extension Host] TypeError: Cannot read property 'map' of undefined
	at asCompletionResult
```

I'm not aware of any "real" bug this causes, but it seems like we're not doing something correct.

**Comment by bobbrow** [comment]
I have a fix for this.

**Comment by sean-mcmanus** [comment]
Cool, thanks. I thought it was some TypeScript issue.

**Comment by haovic** [comment]
I am getting massive amounts of these errors when I view the Developer Tools. My intelliSense and syntax error checking (red squiggles) do not work either, and I think the issues are related. Whenever I type in a C++ file (even after waiting), tons of these errors appear. Here is an image of the issue:

![image](https://user-images.githubusercontent.com/34224185/51345900-37691580-1a6a-11e9-9269-6660a8ad6e4b.png)

I've also tried different combinations of almost all settings regarding intelliSense, as well as reinstalling both the extension as well as VSCode itself. The Insider Edition does not solve this issue either. Here is an example of my c_cpp_properties.json
```js
{
    "configurations": [
        {
            "name": "WSL",
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

I know that I do not have an includePath in this example, but I heard it might be worth trying to take it out. Currently, I have intelliSense fallback disabled. I think it's also worth mentioning that tag parser/fuzzy works to the extent of autocomplete when turned on, but syntax highlighting continues to fail. intelliSense works for Python. Any ideas?

**Comment by sean-mcmanus** [comment]
@haovic Have you tried 0.21.0-insiders4? This TypeError issue should be fixed in that.

**Comment by sean-mcmanus** [comment]
@haovic Oh, nevermind -- I found your response in the other thread.
