### ISSUE TITLE
"environment" not effective when using "pipeTransport"

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-cpptools#2809]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 (host) and Ubuntu 18.04 (remote)
- VS Code Version: 1.29.0
- C/C++ Extension Version: 0.20.1
- A clear and concise description of what the bug is.

I'm trying to debug with gdb by connecting to a remote machine using pipeTransport and at the same time defining that the environment variable `LD_PRELOAD` should be used when launching the program to debug. The environment variable doesn't seem to be set when debugging starts. I enabled engine logging and couldn't see anything mentioning this variable.

**To Reproduce**

```json
        {
            "name": "(gdb)",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/...",
            "args": [],
            "stopAtEntry": false,
            "cwd": "/home/...",
            "logging": {"engineLogging": true},
            "environment": [
                { "name": "LD_PRELOAD", "value": "/home/.../some_library.so" }
            ],
            "externalConsole": true,
            "MIMode": "gdb",
            "pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "C:\\Windows\\System32\\OpenSSH\\ssh.exe",
                "pipeArgs": ["user@host"],
                "debuggerPath": "/usr/bin/gdb"
            },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "sourceFileMap": {
                "/home/...": "${workspaceFolder}"
            }
        },
```

**Comment by a-zh** [comment]
@pieandcakes Is it the active issue? Is any plans for fixing?

**Comment by pieandcakes** [comment]
@a-zh I'm adding @WardenGnaw to take a look as I'm no longer working on this team anymore.

**Comment by a-zh** [comment]
@WardenGnaw Please, help me to fix the problem. I'm using the `pipeTransport:` for launch NetcoreDBG. And I want to have ENV values in "launch" vscode command filled from `launchSetting.json` and propagated to my apps. I expect the next launch command: "env": `{"ASPNETCORE_ENVIRONMENT":"Development","ASPNETCORE_URLS":"http://localhost:5001"}`. But unfortunately, I only see the values from `launch.json` `env:` for .NET MVC projects. All values from launchSetting.json are ignored. 

Simple way to obtain the mvc project:
`dotnet new mvc --no-https --auth None`

**Comment by a-zh** [comment]
@WardenGnaw Do you have any tidings about the issue?
