### ISSUE TITLE
Buggy autocomplete in comments: sometimes uses dictionary words; other times, classes

### ISSUE THREAD

**Issue by artagnon** [microsoft/vscode-cpptools#281]
The images should talk for themselves.

<img width="599" alt="screen shot 2016-10-12 at 8 26 16 pm" src="https://cloud.githubusercontent.com/assets/37226/19332475/53523ede-90ba-11e6-881c-a380a7e7be93.png">
<img width="600" alt="screen shot 2016-10-12 at 8 25 50 pm" src="https://cloud.githubusercontent.com/assets/37226/19332479/5c219e92-90ba-11e6-8157-d4ec5bff449e.png">

**Comment by DevSecTim** [comment]
+1

**Comment by guoqingaa** [comment]
+1

**Comment by bobbrow** [comment]
The extension should no longer be providing autocomplete suggestions inside of comments.  If you force it with CTL+Space, VS Code should provide you with dictionary words parsed from the current file.
