### ISSUE TITLE
Documentation for Cygwin?

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vscode-cpptools#2810]
Hi, I see that there's documentation available for MinGW, but there are no guides for Cygwin. Can someone shed light on this?
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md

**Comment by sean-mcmanus** [comment]
I think it should be the same, but you just set the compilerPath to your Cygwin compiler. Are you hitting config issues still?

**Comment by Astrantia** [comment]
@sean-mcmanus I haven't tried to set compilerPath to Cygwin compiler, but I'll try and report back. Regardless, if that is works as you have suggested, why not indicate that in docs for clarity so that issue like this doesn't pop up in future? If not, why don't we document Cygwin usage too?

**Comment by Astrantia** [comment]
I believe setting the compilerPath to Cygwin compiler worked.

**Comment by sean-mcmanus** [comment]
I believe our Cygwin usage was lower, which is why we only called out MinGW in our docs. I've updated the docs with https://github.com/Microsoft/vscode-cpptools/pull/2813 .

**Comment by Astrantia** [comment]
@sean-mcmanus Why is it g++ for Cygwin and gcc for MinGW?
In fact, I set gcc for Cygwin too.

**Comment by sean-mcmanus** [comment]
It was just an example, the compiler could be clang-5.0.exe, etc. I'll add a line explaining that.
