### ISSUE TITLE
the database config not work

### ISSUE THREAD

**Issue by alianZhen** [microsoft/vscode-cpptools#2815]
I set "C_Cpp.default.browse.databaseFilename":${workspaceFolder}/.vscode/vc.db 

When I open a folder which in chinese path,it not work,.The database will be created on "C:\Users\****\AppData\Roaming\Code\User\workspaceStorage"

**Comment by bobbrow** [comment]
Did you put quotes around `"${workspaceFolder}/.vscode/vc.db"`?

**Comment by alianZhen** [comment]
yes
![image](https://user-images.githubusercontent.com/27906971/48453645-3b20b780-e7ef-11e8-84ac-8be1e26685d9.png)

**Comment by bobbrow** [comment]
Do you have it set as a User setting/Workspace setting/Folder setting?  Do you have it set in `c_cpp_properties.json`?  The order we evaluate this property is:
1. `c_cpp_properties.json`
2. Folder Setting
3. Workspace Setting
4. User Setting

As soon as we find one, we use it, so if it is set in (1), we don't evaluate (2)-(4)

**Comment by alianZhen** [comment]
I find that I set c_cpp_properties.json.When I delete this config in json,it work fine.Thank you~

**Comment by alianZhen** [comment]
And I also want to know how to get the value of ${workspaceFolder}

**Comment by sean-mcmanus** [comment]
@alianZhen Can you right-click the folder and choose Copy Path? For a single root workspace, you can just do that on some file/folder at the root and remove the leaf path.
