### ISSUE TITLE
Containera headers

### ISSUE THREAD

**Issue by bhack** [microsoft/vscode-cpptools#2818]
Partially related to https://github.com/Azure/vscode-kubernetes-tools/issues/403.
I think that for Docker on localhost you can always always mount a portable version of Vsocde in a volume and run the IDE in the container but it will be hard for remote running containers like Kubernetes. Also I don't know if there will any security consequence about mounting the portable ide in containers (some plug-ins like github store tokens or vscode livestream etc..). What do you think?

**Comment by sean-mcmanus** [comment]
This doesn't appear related to our C/C++ extension. Maybe try https://github.com/Microsoft/vscode/issues ?
