### ISSUE TITLE
configurations.includePath doesn't seem to work

### ISSUE THREAD

**Issue by artagnon** [microsoft/vscode-cpptools#282]
I can set `configurations.includePath` to "~/src/llvm/include" or "${workspaceRoot}/include", and there are squiggly lines on everything. Notice that even `std` stuff isn't found! Did you not include an implicit includePath for Mac?

<img width="345" alt="screen shot 2016-10-12 at 8 31 41 pm" src="https://cloud.githubusercontent.com/assets/37226/19332539/070a2fcc-90bb-11e6-938f-39ee3af7b70f.png">

**Comment by sean-mcmanus** [comment]
We don't have any implicit includePaths. There are just the defaults that you see in c_cpp_properties.json. If you're using xcode stuff, this might have a solution https://github.com/Microsoft/vscode-cpptools/issues/275 .

**Comment by artagnon** [comment]
There seems to be a huge lag between me setting the includePath, and the squiggly lines going away, with no indication of progress. And "${workspaceRoot}" definitely seems to be broken.

Please consider making "/usr/include" and "/usr/include/c++" implicit on Linux and Mac. Nobody using cpptools is ever _not_ going to want that. I'd send a PR if the code were open source (as I've done for vscode).

**Comment by agauniyal** [comment]
`/usr/include/c++` is fine but I won't put `/usr/include` because last time I checked, it started showing every possible symbol without context awareness for autocompletion. Think of typing `len` and you're getting repeated suggestions for symbols starting with `a..`.

**Comment by justnonamenoname** [comment]
${workspaceRoot}
why not to add this?

**Comment by bobbrow** [comment]
@artagnon, are you still having issues with this?  This could have been broken back when you reported the issue, but I don't have any issues with the includePath in the latest version.  /user/include is added implicitly to the symbol search path if no c_cpp_properties.json file exists.  When it is created for the first time, we will also add that path to the list.  If you already have a c_cpp_properties.json file in your workspace, you will need to add it manually.

Please reactivate if you are still having issues.
