### ISSUE TITLE
Quotes around Defines are not supported for CustomConfigurationProviders

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#2820]
For example, when passing in "\"FOO\"" as a define, it results in the error `command-line error: invalid macro definition: "FOO"` to show up at the top of the source file.

**Comment by bobbrow** [comment]
Thanks for reporting this.  We have this working for compile_commands.json, but not the other providers.

**Comment by sean-mcmanus** [comment]
Our latest [0.21.0-insiders3](https://github.com/Microsoft/vscode-cpptools/releases) should allow quotes around defines with custom configuration providers.

Setting `C_Cpp.updateChannel` to `"Insiders"` is another way to get the update.

**Comment by sherryyshi** [comment]
Great, thanks!
