### ISSUE TITLE
How to include other folders

### ISSUE THREAD

**Issue by bobwolff68** [microsoft/vscode-cpptools#2826]
Issue Type: <b>Bug</b>

I cannot recompile my old project as it had custom include folders. I found the C_Cpp.default.includePath setting, but it is unclear how to set it and what relative path I'm working with. Without a GUI to pick a folder, this is kinda tricky and it's not clear if the new setting should include the entire setting name of "C_Cpp.default.includePath" or maybe NOT have the ".default" in that name since it is no longer the default.

Extension version: 0.20.1
VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_1675673|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
C_Cpp.default.includePath doesn't affect compiling at all -- just the IntelliSense feature. It takes an absolute path or you can use a variable like '${workspaceFolder}' to create an absolute path.

**Comment by bobwolff68** [comment]
Thanks for your response. After experimenting a bunch, I came to a similar understanding that there are two parts to the include - the visual portion and then actual cross-compilation directives. I've still been unsuccessful at both cross-compilation directives and intellisense. Can someone help?

As a simplified project, I started a new robot sample based on Arcade and then I've added a single #include directive to include a common header of ours hoping to get the include folders to work out in this simpler unit test...

For Intellisense, I've modified the .vscode/settings.json (vsArcade folder settings) file and added:
  "C_Cpp.default.includePath": ["/Users/rwolff/dev/robotics/FRCTeam1967/code/include"]

The full path folder (Mac) above contains a battery of common include headers needed by all of our projects. After adding this and saving the file, I go back to the sample Arcade Robot.cpp file to which I've added one of my team's include files and I save it causing intellisense to check it out. It gives me an error about the include file not being found despite the above. Thoughts on what I'm missing here or to which file this setting should be added if not settings.json?

SECONDLY - Cross-compiler directives for include files. Where should I set these? It seems it must be a gradle setting but I've tried several different ways and have begun to understand that there may be a need to do a 'wpilib refresh gradle C++ properties" to have it re-generate gradle items before doing a 'robot build' but still haven't gotten the right combination of things.

**Comment by sean-mcmanus** [comment]
For using the default settings, see https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Customizing%20Default%20Settings.md . It looks like you're going to probably want to add `${workspaceFolder}` or `${workspaceFolder}/**` as well. You may also need to set your compilerPath in c_cpp_properties.json (https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md) or set the C_Cpp.default.compilerPath.

You should [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and see what includePaths we're sending to our IntelliSense process.

I'm not familiar with gradle so I don't know how to specify include directories with that.

**Comment by Colengms** [comment]
There has not been activity on this issue for quite a while.  If you are still seeing a problem, please re-open with new information or create a new issue.
