### ISSUE TITLE
Downloading package 'Visual Studio Windows Debugger' Failed at stage: downloadPackages Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cpptools#283]
this 
`
// Place your settings in this file to overwrite the default settings

{
    "http.proxyStrictSSL": false
}
`

works for vscode itself, but seems doesn't affect c++ tools extension

**Comment by sean-mcmanus** [comment]
You need to add the "http.proxy": "http[s]://<hostname>:<port>" setting or an HTTP[S]_PROXY environment variable. Uh...but if you're seeing VS Code work, maybe we're doing something wrong? Unlike VS Code, we're always using an HttpsProxyAgent and not an HttpProxyAgent. Is your http.proxy protocol http?

**Comment by amigo421** [comment]
sorry for extremely short and unclear initial description

our network uses proxy indirectly, there is a special hosts on a firewall, which split the traffic on internal and external and add proxy for external one on the go. so for the application , we do not set up the proxy and it works. I believe the problem with cpptools is no in this.
the problem is that our internal certificate is not trusted (I'm not familar with the process well, I only know that currently our certificates , required for the connection, are not trusted by root issuer, when I'm working in CLion, it raise the window with a question - do I trust this certificate or not and remember the decision), In vscode, there is no this ability but I solved the problem - If I'm using the setting : proxyStrictSSL for vscode, this avoids the issue with a certificate, but not for cpptools extension, because seems CppTools doesn't use this setting
does it sound clear for you? if not enough let me know,I'll try to explain with more details

**Comment by sean-mcmanus** [comment]
The proxyStrictSLL setting should require the http.proxy setting or the http[s]_proxy environment variable otherwise I don't see how it would work. Can you check for a http[s]_proxy environment variable? Or enter some valid value for http.proxy? If you open C:\Users<user>.vscode\extensions\ms-vscode.cpptools-0.9.2\out\src\packageManager.js you can see GetHttpsProxyAgent to see how we use the proxyStrictSSL, but the HttpsProxyAgent requires that we supply a proxyURL.

**Comment by amigo421** [comment]
Please do not close the request- I'll can to check at Mon only. I'll write the result here

**Comment by sean-mcmanus** [comment]
Sure. Also, there's also a potential workaround via manually downloading the platform-specific packages you need, adding the install.lock file, and possibly modifying our package.json (if you need OpenDebugAD7 to work), and making the binaries executable if you're on Linux/Mac. See https://github.com/Microsoft/vscode-cpptools/issues/284 .

**Comment by amigo421** [comment]
just checked (from builtin terminal):

> C:\dev\workspace\algolist>set http_proxy  
> Environment variable http_proxy not defined                                                                                                                                                                   
> 
> C:\dev\workspace\algolist>set https_proxy  
> Environment variable https_proxy not defined                                                                                                                                                                  

exact message on the starting:

> Updating C/C++ dependencies...
> 
> Downloading package 'Visual Studio Windows Debugger' Failed at stage: downloadPackages
> Error: unable to get local issuer certificate
> 
> Finished

just for sure - vscode works fine, just installed a couple extensions without issues

unfortunately, i have no experience in TS/JS, , so give me more time to review the code .

# 

update: 
for the testing only - Ive commented out this:
`// "http.proxyStrictSSL": false,`

and got absolutely the same error , but now, for the whole editor, e.g. extension downloading:

> unable to get local issuer certificate

if this can help , feel free to provide me with a version with any extended logging

**Comment by sean-mcmanus** [comment]
Okay, it sounds like the VS Code extension downloading is somehow able to use the proxyStrictSSL without a proxy URI. What version of VS Code are you using? I searched the vscode source and I don't see any spot where it would behave different from our code or where it uses the proxyStrictSSL without having a proxyURI: https://github.com/Microsoft/vscode .

**Comment by amigo421** [comment]
first of all, there is a latest vscode version, auto-update for the editor itself and extensions works with no issues.
I've also checked how my other dev tools work out there. so all ones work with "no proxy" setting. 
and without the error with local issuer. 
so seems my PC requies no proxy. the only issue with a certificates whicxh are really in use in case of external traffic. is there any extended logging console?

**Comment by amigo421** [comment]
is there an ability to download all required manually? 

I don't know how to work with an extensions as a projects, I've tried to open your extension as a folder, 
and faced with a similar issue:
- if httpStrictSSL = true - vscode shows me a error : unable to get local issuer certificate
- if httpStrictSSL = false - no issues on an extension loading

**Comment by pieandcakes** [comment]
There is an issue in the download that it is not respecting `"http.proxyStrictSSL": false` setting. This will be fixed in the next release.

**Comment by pieandcakes** [comment]
This should be fixed in 0.9.3. let me know if you are still running into the issue.
