### ISSUE TITLE
Chinese Characters don't show properly in Integrated Terminal

### ISSUE THREAD

**Issue by ZZYSonny** [microsoft/vscode-cpptools#2831]
Type: Debugger

**Describe the bug**
- OS and Version: Win10 10.0.17763.134
- VS Code Version: 1.29.0
- C/C++ Extension Version: 0.20.1
- Chinese characters don't show properly in integrated terminal when running

**To Reproduce**
*Please include a code sample and `launch.json` configuration.* ->See screenshot
1. Create code with Chinese output and run

![image](https://user-images.githubusercontent.com/28442838/48538888-9a1a2580-e8f0-11e8-9df6-b98a63da4b40.png)

Also is it possible to ignore the long command that appears before every launch as it seems so distracting? And is it possible to clear the terminal before running for another time?

**Comment by Forgoys** [comment]
1. Click "Select encoding" on the bottom-left.
2. Choose "Reopen with encoding".
3. Choose "Simplified Chinese (GBK)"

**Comment by zikonde** [comment]
> 1. Click "Select encoding" on the bottom-left.
> 2. Choose "Reopen with encoding".
> 3. Choose "Simplified Chinese (GBK)"

What happens when I do that is that I can see the code properly in the editor but its still noodles when I run the file
![image](https://github.com/microsoft/vscode-cpptools/assets/103549398/1f7adb5f-cba8-44a8-9931-332eabf92e35)

![image](https://github.com/microsoft/vscode-cpptools/assets/103549398/23860462-3ea7-4bb9-9d6d-68e751948456)

**Comment by Forgoys** [comment]
> > 1. Click "Select encoding" on the bottom-left.
> > 2. Choose "Reopen with encoding".
> > 3. Choose "Simplified Chinese (GBK)"
> 
> What happens when I do that is that I can see the code properly in the editor but its still noodles when I run the file ![image](https://private-user-images.githubusercontent.com/103549398/324357322-1f7adb5f-cba8-44a8-9931-332eabf92e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzY3NDksIm5iZiI6MTcxMzc3NjQ0OSwicGF0aCI6Ii8xMDM1NDkzOTgvMzI0MzU3MzIyLTFmN2FkYjVmLWNiYTgtNDRhOC05OTMxLTMzMmVhYmY5MmUzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwOTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTNjNzE5NjI1ZDRlNGM0MmNlYzQ5YjA2ZDA5ZGI0ZjU3OTBmZGQ2ZjYyOWNkODA3YTEzNjY1NTAyMjc1Yjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7SiatZFAMfT1f_ZmmaoTSFBTxVHmNXQpL0oHdyIIAxs)
> 
> ![image](https://private-user-images.githubusercontent.com/103549398/324357418-23860462-3ea7-4bb9-9d6d-68e751948456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzY3NDksIm5iZiI6MTcxMzc3NjQ0OSwicGF0aCI6Ii8xMDM1NDkzOTgvMzI0MzU3NDE4LTIzODYwNDYyLTNlYTctNGJiOS05ZDZkLTY4ZTc1MTk0ODQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwOTAwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmM3ZjI1NWFjYTY2ODk1OTdmMjkzZjY0ZjYxMzkxODkxOWNjZThlNThhNGNiNGNiZjY1YzlkMGM5ZTA4OGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sSEYp2am_vbsdH3Ez-yOl6ptlvxuT9dEVMK3KmE06V0)

第二步里选“通过编码保存”，然后选GBK试试？

**Comment by zikonde** [comment]
Figured it out. Open the php.ini file related to your PHP version and change default_charset = "UTF-8" to default_charset = "GBK"
