### ISSUE TITLE
systemIncludePath parameterization & effects

### ISSUE THREAD

**Issue by raggi** [microsoft/vscode-cpptools#2837]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS Mojave
- VS Code Version: Version 1.29.1 (1.29.1)
- C/C++ Extension Version: 0.20.1

I am working on Fuchsia (https://fuchsia.googlesource.com/docs/+/master/README.md).

I have a fuchsia checkout at `~/fuchsia`. `${workspaceFolder}` == `~/fuchsia`.

I have the following configuration:

```
{
    "configurations": [
        {
            "name": "Fuchsia",
            "defines": [],
            "browse": {
                "path": [
                    "${workspaceFolder}/zircon",
                    "${workspaceFolder}/garnet",
                    "${workspaceFolder}/peridot",
                    "${workspaceFolder}/topaz",
                    "${workspaceFolder}/third_party"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "compilerPath": "${workspaceFolder}/zircon/prebuilt/downloads/clang/bin/clang++ --sysroot=${workspaceFolder}/out/x64/zircon_toolchain/obj/zircon/public/sysroot/sysroot --target=x86_64-fuchsia",
            "systemIncludePath": [
                "${workspaceFolder}/out/x64/zircon_toolchain/obj/zircon/public/sysroot/sysroot/include"
            ],
            "includePath": [
                "${workspaceFolder}/out/x64/zircon_toolchain/obj/zircon/public/sysroot/sysroot/include"
            ]
        }
    ],
    "version": 4
}
```

I have the following issues:

- the above `includePath` seems to be required, but it should not. That path is a system include path - it's the sysroot. I've had to specify the sysroot three times - this seems incorrect. Without this specification, editing for example `//zircon/system/fdio/include/lib/fdio/spawn.h` presents warnings that it can not find `#include <zircon/compiler.h>`. `out/x64/zircon_toolchain/obj/zircon/public/sysroot/sysroot/include/zircon/compiler.h` exists.
- I would like to be able to define targets for x64 and arm64, and to parameterize the sysroot paths based on the architecture. This does not seem to be possible, based on the documentation I have so far been able to find.

**Expected behavior**

- I should be able to specify a sysroot or a system include path once, and not need to add it to includePaths.
- I should be able to parameterize my paths based on an architecture parameter (x64/arm64 for me (alas these aren't clang triples in the paths)).

**Comment by bobbrow** [comment]
Our system header detection logic has improved in the past few years.  There should no longer be a need to add sysroot paths to "systemIncludePath" or "includePath".  In fact, this is often a source of incorrect squiggles.  If you continue to have issues with this, please let us know.  We're sorry we didn't get to this specific issue sooner.
