### ISSUE TITLE
Problem matcher for warnings

### ISSUE THREAD

**Issue by badmitrii** [microsoft/vscode-cpptools#2839]
**Type: LanguageService**
Warning messages are not being displayed in the "Problems" panel. But errors do. As specified in the [problem matchers section](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher) the extension already has one. Percisely:

> 
Note: The C/C++ extension includes problem matchers for GCC so there is no need to define our own.

So I guessed it was not necessary to write a regex to parse gcc-warnings by ourselves.

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.28.0
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): VSCode Vim.
- A clear and concise description of what the bug is.

GCC prints out warning messages, but they are not displayed in the "Problems" panel.

**To Reproduce**
**_c_cpp_properties.json_**:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```
1. Create a new project.
2. Type any code that makes gcc prints out a warning
3. Go to the "Problems" panel
4. See no warnings being displayed

**Expected behavior**
Show the warning in the "Problems" panel.

**Screenshots**
No warnings issued:

![screenshot from 2018-11-18 14-04-07](https://user-images.githubusercontent.com/6568143/48671589-b65dd280-eb3b-11e8-98f1-8b0fa3ac5c6f.png)

Errors are displayed as expected:

![screenshot from 2018-11-18 14-11-05](https://user-images.githubusercontent.com/6568143/48671605-0c327a80-eb3c-11e8-8dd5-ab8d97bbd6ba.png)

**Comment by sean-mcmanus** [comment]
The problem matcher is in our open source at https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/package.json if anyone wants to investigate/fix this themselves.

**Comment by sean-mcmanus** [comment]
Actually, the problem matcher we provide is only invoked when you use the tasks.json with the problemMatcher field set to "$gcc", and warnings should be supported, so instead of invoking gcc from the terminal you would need to use invoke a task. The error that shows "expected a `;`" is from our IntelliSense engine which doesn't support showing warnings yet (see https://github.com/Microsoft/vscode-cpptools/issues/828 ).

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity and by design.
