### ISSUE TITLE
Updating C/C++ dependencies...  Downloading package Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by sherkwast** [microsoft/vscode-cpptools#284]
Updating C/C++ dependencies...

Downloading package 'Visual Studio Windows Debugger' Failed at stage: downloadPackages
Error: connect ETIMEDOUT xxx.xx.x.xx:xxx

Finished

**Comment by sean-mcmanus** [comment]
Are you connected to the internet? The 1st package is 12 MB.

**Comment by sherkwast** [comment]
Yes, I am connected to the internet.

**Comment by sean-mcmanus** [comment]
Hmm...I'm not reproing it. The URL is https://go.microsoft.com/fwlink/?LinkID=825339 . Are you able to access that?

**Comment by sherkwast** [comment]
Yes.And I download a zip file.

**Comment by sean-mcmanus** [comment]
Okay, we make an https request to that URL to download the zip...so I'm not sure why it would timeout in VS Code. We read the http.proxy and http.proxyStrictSLL settings from VS Code and possibly the HTTP[S]_PROXY environment variable. I don't think we've gotten other reports of this. ENOENT occurs if there's no connection at all, so it looks like your connection is just really slow and is timing out -- how long does it take before the timeout occurs?

**Comment by sherkwast** [comment]
So where should I put the zip file...

**Comment by sean-mcmanus** [comment]
Bypassing the download/install is not really recommended. We do other "install" stuff like modify the package.json. However...if you go to the install location Users\(user)\.vscode\extensions\ms-vscode.cpptools-\<version\> then you can open package.json to see the URLs that have additional downloads you'll need, which are list under the "runtimeDependencies" section. All the downloads go to the that root location. And then to bypass the auto-download you need to add a "install.lock" file there. And if you need to use OpenDebugAD7 debugging (or if you don't want the extension to always run) you can modify the package.json as shown in out/src/main.js rewriteManifest().

**Comment by mazhan465** [comment]
After I do these,I can open VS code normal.But When I click debug,only follows :

---

You may only use the C/C++ Extension for Visual Studio Code with Visual Studio
Code, Visual Studio or Xamarin Studio software to help you develop and test your

## applications.

and debugger seems not  really get into main funtion.

**Comment by Luxios** [comment]
Thanks, I've solved the problem.

**Comment by pieandcakes** [comment]
@Luxios we have released an update that may resolve your download issues. Please reopen if it does not.

**Comment by tallplay** [comment]
**I got same problem:**

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
Failed at stage: downloadPackages
Error: connect ETIMEDOUT 104.115.2xx.1xx:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

Finished

I could download  [https://go.microsoft.com/fwlink/?LinkID=825339 ](url) by borwser.

**Comment by sean-mcmanus** [comment]
@tallplay We're still trying to figure out why this is happening. We switched to an "improved" CDN but the results have not improved. If the link works via the browser, it implies there is some problem in our software layer. Or maybe we need to retry/wait more?

**Comment by sean-mcmanus** [comment]
@tallplay The 825339 fwlink is old. Looks like you're on 0.12.0? Can you try updating to 0.12.1 or 0.12.2 (when we release it).

**Comment by tallplay** [comment]
I've tried 0.12.2. Same problem:

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
Failed at stage: downloadPackages
Error: connect ETIMEDOUT 104.115.227.41:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

Finished

The link in package.json is [https://go.microsoft.com/fwlink/?linkid=853251](url), I could download it too.

Have any manual way to overcome this problem? I'd glad to try. I am looking forward to use the great functions of  this extension.

**Comment by sean-mcmanus** [comment]
The guy who is helping us wants to know what country (and preferably city) you are in because that will help him figure out which node is having connection issues. Can you provide that? It looks like our highest number of ETIMEDOUT are coming from China, mostly Shanghai and Beijing.

As a workaround, you can open the package.json in our extension folder, look at the runtimeDependencies section and change all the fwlinks to the targets of the fwlinks (since the ETIMEDOUT is occurring on the fwlink), such as https://download.visualstudio.microsoft.com/download/pr/11025398/720d3484d8477614d89ff7a92c6fb1ee/Bin_Windows.zip (for the 853251 fwlink), and also https://download.visualstudio.microsoft.com/download/pr/11008322/220fcbe64419383a9fb722a4cdab5a92/LLVM_Windows.zip for 848957 and https://download.visualstudio.microsoft.com/download/pr/11008322/220fcbe64419383a9fb722a4cdab5a92/Microsoft.VisualStudio.VsDbg.zip for 852926.

If bypassing the fwlinks doesn't work, can you give us the error you receive? Then you could try another workaround by download the zip files using your browser, and then unzip them into the extension folder and add a install.lock file to prevent additional downloads. You might hit some issues with this though, because it skips some "install" steps we do.

**Comment by mazhan465** [comment]
I am in WuHan in china .

**Comment by Yensan** [comment]
I am in ShenZhen in China.

**Comment by Yensan** [comment]
Great China is Great as Great Fire Wall...

**Comment by Yensan** [comment]
I have updated  to 1.14.2 
then

_Updating C/C++ dependencies...
Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
Failed at stage: downloadPackages
Error: connect ETIMEDOUT 23.58.152.144:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
Finished_

I have downloaded the file. Can you tell me( and other guys) how to install it by hand? Appreciate it!

**Comment by mazhan465** [comment]
Now I can update normally.I don't know what about happen.Since one month after,it haven't happen.

**Comment by sean-mcmanus** [comment]
@mazhan465 We switched to a new CDN that reportedly works better in China, although our telemetry hasn't shown an improvement yet.
@Yensan You're failing to get results back from the fwlink (located in Massachusetts). Can you try replacing the fwlink with the actual target URL (which I gave above).

**Comment by Yensan** [comment]
@sean-mcmanus I did have replaced the fwlink with the actual target URL (which you gave above), and, there is nothing changed.  Could you tell me  how to install by hand?

**Comment by tallplay** [comment]
I am in Taiwan. I found it was  blocked by my company's proxy. After using my phone's sharing network, everything was normal.

**Comment by Yensan** [comment]
@sean-mcmanus   @tallplay Maybe it was blocked by my company's proxy too. I am in a company forbidden to access internet freely. I figure out a way to install it. Download it, then shut up cpptools' https requirement, use local python django http server to ship it. It worked fine. 
My mac in my home have **not** encounter this problem, it works very well.
Hope VS Code and Cpptools is better and better. It make C language programming easier. Visusal Studio is too vast to make me lost.

**Comment by DatuNinuno** [comment]
@sean-mcmanus hi, i just experienced the same issue at version 1.17.2
tried to check the package.json file but the link isn't in the ones you mentioned before..
the ones here are the ff.

			"description": "C/C++ language components (Linux)",
			"url": "https://go.microsoft.com/fwlink/?linkid=859832",

			"description": "C/C++ language components (OS X)",
			"url": "https://go.microsoft.com/fwlink/?linkid=859833",

			"description": "C/C++ language components (Windows)",
			"url": "https://go.microsoft.com/fwlink/?linkid=859834",

Is there a workaround i can do to install the c++ extension..?

Update: I just found another thread like this, followed what other people suggested and managed to make it work. Basically, just set your proxy to the http.proxy parameter in the settings and it should work fine. Cheers!

**Comment by Yensan** [comment]
I have another way to ship this extension:
1. install / update in normal environment, then zip the extension file
2. download the extension file in https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools , such as ms-vscode.cpptools-0.14.0.vsix 
3. transfer zip file and vsix file in special environment
4. install the extension by vsix file, and unzip the files into folder 
5. enjoy it

**Comment by sean-mcmanus** [comment]
@DatuNinuno You can manually download the new fwlink binaries. Definitely don't try to use the old binaries with the new extension or the results are unpredictable and may crash or do other unintended things.

**Comment by sean-mcmanus** [comment]
@Yensan If you zip the installed/downloaded extension, there shouldn't be any need to also install the .vsix (it would just copy over files that already exist)...or am I mistaken? You may also need to use some program like tar that maintains the executable permissions (or re-run chmod to make the 2 executables runnable on Linux/Mac).
