### ISSUE TITLE
Error processing launch options at field: name

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#2840]
When attempting to debug on windows while setting an environment variable, the error message `Error processing launch options at field: name` pops up. This happens with a basic launch setup, and even happens before it checks for the executable path. If I remove the environment declaration, the issue goes away.

C++ extension 0.20.1

```
    {
      "name": "(Windows) Launch2",
      "type": "cppvsdbg",
      "request": "launch",
      "program": "this doesnt matter",
      "environment": [{
        "ANY_ENV_VAR": "",
      }],
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "externalConsole": true
    },
```

**Comment by pieandcakes** [comment]
@ThadHouse I believe the correct way to do it is 
```
"environment": [
    { 
        "name": "ANY_ENV_VAR", 
        "value": ""
    }
],
```

**Comment by ThadHouse** [comment]
Ah ok, that seems to work. The docs were a bit confusing on that, and both the node and java debuggers use 

```
environment: {
  "key": "value",
  "key2": "value"
}
```

for their environment variables, so I thought they would be similar.

**Comment by pieandcakes** [comment]
@ThadHouse Yea, sorry. Its roll your own json schema so I think we started using this format at the beginning. There have been people asking to switch but it would break back compat.
