### ISSUE TITLE
Fedora 29: debugger never starts

### ISSUE THREAD

**Issue by psukys** [microsoft/vscode-cpptools#2842]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Fedora 29 x64
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them):

Problem persists after disabling all (and leaving C/C++):
    - Ansible
    - autoDocstring
    - CMake
    - CMake Tools
    - Code Runner
    - Cram Test Runner
    - CSS Formatter
    - Docker
    - Dracula Official
    - Git Blame
    - Gradle Language Support
    - Kotlin Language
    - LaTeX
    - LaTeX language support
    - Markdown Table Formatter
    - nginx.conf
    - npm
    - npm Intellisense
    - PHP Debug
    - PHP DocBlocker
    - PHP IntelliSense
    - PlantUML
    - Python
    - SVN
    - WakaTime
    - YAML Support by Red Hat 

- A clear and concise description of what the bug is.
**Debugging does not start**

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
Steps to reproduce the behaviour:
1. Add `test.c` (source below)
2. Compile `test.c` via `gcc test.c`
3. Add `launch.json` to `.vscode` folder (source below)
4. In debugging, press play for `(gdb) launch`
5. Verify the debugger never starts/ends
6. Verify `gdb a.out` functionality works without any hanging
7. Verify no logging output is produced

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
launcher
test.c:
```c
int main() {
    int a = 0;
    return a;
}
```
launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "logging": {
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

**Comment by pieandcakes** [comment]
@psukys with the logging added, is there anything anything in the `debugConsole` ? When you say "debugging never starts" are you saying you get the blue progress indicator and it doesn't stop?

**Comment by pieandcakes** [comment]
Also, can you try setting `externalConsole` to `false` and see if you get the same behavior?

**Comment by LinAGKar** [comment]
I'm having the same problem on OpenSUSE Leap 15 with VSCode 1.29.1 and C/C++ extension 0.20.1. When externalConsole is true, the blue progress indicator never stops, and nothing appears in the debug console, but when externalConsole is false debugging starts normally.

**Comment by psukys** [comment]
@pieandcakes regarding "Debug Console", there's nothing and the input bar contains "Please start a debug session to evaluate expressions", while the debug indicator shows that it's loading and only "Stop" button is active (clickable) in Debug panel.
Also with debugging, I separately (outside VSCode) check for any processes that run my specified executable and couldn't find any.

Setting `externalConsole` to `false` the problem does not occur, debugging seems to function normally.

**Comment by satyajitghana** [comment]
I'm having a similar issue, though setting ``externalConsole`` to ``false`` doesn't solve the issue. The blue progress bar keeps on going, on the debug console it says : please start a debug session. so the session isn't even started. The stop button is clickable in the debug panel. that's about it.

config : 
Ubuntu 16.04 - WSL
VSCode : 1.29.1
cpptools extension : 0.20.1

here's ``launch.json``
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": { "engineLogging": true }
        }
    ]
}
```

**Comment by pieandcakes** [comment]
@satyajitghana If you are using WSL you need to specify more configuration. Please see [this document](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/Windows%20Subsystem%20for%20Linux.md) for configuration instructions.

**Comment by satyajitghana** [comment]
@pieandcakes its WSL though i am using VcXsrv X Server to open VSCode Natively inside WSL, i am not using VSCode on Windows and configuring it to work with WSL.

**Comment by Murzinio** [comment]
Same problem on Arch, setting `externalConsole` to false fixes it.

**Comment by pieandcakes** [comment]
@satyajitghana That isn't something we have tested and I don't have an idea why it isn't working.

Are you installing the extension in WSL also? Can you confirm in your extension's folder you see `mono-linux-86_64` in the debugAdapters folder.

**Comment by pieandcakes** [comment]
@Murzinio So it sounds like the command we're sending to do externalConsole launch is not correct. Thank you for letting me know.

**Comment by satyajitghana** [comment]
@pieandcakes yeah i do have that
```mono.linux-x86_64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=d465c99a4d8e4c34639af8ac31358a0e6d2eeb40, stripped```

BTW again this ^ i am on Native WSL Linux. not on the windows VSCode piping the output, although i did try that too, and i have the same problem, debugger doesn't start, ``"pipeProgram": "c:\\windows\\sysnative\\bash.exe",`` <- is this correct ? i don't seem to have the sysnative folder at all.

Here's the Windows VSCode launch.json
```{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/mnt/d/LambdaCalculus/LambdasCPP/a.out",
            "args": ["-fThreading"],
            "stopAtEntry": false,
            "cwd": "/mnt/d/LambdaCalculus/LambdasCPP",
            "environment": [],
            "externalConsole": false, // changed to false
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "c:\\windows\\sysnative\\bash.exe",
                "pipeArgs": ["-c"],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/mnt/d": "d:\\"
            }
        }
    ]
}```

**Comment by pieandcakes** [comment]
@satyajitghana `sysnative` is a reference to the 64bit system32 folder under Windows. It allows it to be accessed even from a 32bit command. 

If you are setting up `pipeTransport`, that is to allow it to be run from Windows across the bash.exe remoting to WSL. This is currently what we support. 

There is another issue open for your scenario, #2870. Please use that issue for the native WSL scenario.

**Comment by WardenGnaw** [comment]
I could not reproduce debugging not working on Fedora 29: Linux localhost.localdomain 4.18.16-300.fc29.x86_64

I am using VSCode 1.29.1 and C++ extension 0.20.1.

Can you enable logging and provide the info?

**Comment by psukys** [comment]
@WardenGnaw logging was enabled yet *nothing starts* (see discussion above) that would yield output. Only by setting `externalConsole` to `false` debugging would start.
VSCode developer console doesn't yield any logging, that would be related to C++ extension, as well.

**Comment by tommyvct** [comment]
For me it does not really matter whether is false or true, same result.
It can compile, linting works fine, running blue progress bar, but it just don't want to start the debugger at all.
I'm on ubuntu 1810 WSL, native linux VSCode. I will try the same folder on my real ubuntu 1810 to see if the problems still persist.
UPDATE: on my real ubuntu 1810 it worked well.
I will now giving roll back a try.

**Comment by pieandcakes** [comment]
Can All of you check and make sure the external terminal you have specified in VS Code exists on your machine? 

The settings are in the VS Code's Settings area:
```
    "terminal.explorerKind": "external",
    "terminal.external.linuxExec": "x-terminal-emulator"
```

**Comment by pieandcakes** [comment]
Closing this in favor of #2998. Please leave a comment there or here if you need more help

**Comment by LinAGKar** [comment]
terminal.external.linuxExec was set to 1. Setting it to konsole works. I also tried xdg-terminal, but got the same problem.
