### ISSUE TITLE
${workspaceRoot} in compileCommands generates misleading warnings

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#2845]
Adding `${workspaceRoot}/build/compile_commands.json` to the compileCommands generates the error

```
${workspaceFolder}/build/compile_commands.json" could not be found. 'includePath' from c_cpp_properties.json will be used instead.
```

The actual problem is that the file doesn't exist...

**Comment by bobbrow** [comment]
`compile_commands.json` doesn't exist?  Or the source file referenced by `compile_commands.json`?

**Comment by Gruntfuggly** [comment]
The compile_commands.json doesn't exist, but the error says "workspaceFolder" when I was setting it to "workspace*Root*", which was really confusing.

**Comment by bobbrow** [comment]
workspaceRoot == workspaceFolder and VS Code discourages use of workspaceRoot, so we don't preserve the original variable name when we translate back from the absolute path to the variable syntax.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity and by design.
