### ISSUE TITLE
Allow sub configurations

### ISSUE THREAD

**Issue by ci70** [microsoft/vscode-cpptools#2847]
Allow/implement sub configurations in c_cpp_properties.json file. Currently we use this which creates are ridiculously long list. This is without Operating Systems.

```
{
    "configurations": [
        {
            "name": "Release/x64/MSVC",
        },
		{
            "name": "Debug/x64/MSVC",
        },
        {
            "name": "Release/x86/MSVC",
        },
		{
            "name": "Debug/x86/MSVC",
        },	
        {
            "name": "Release/x64/GCC",
        },
		{
            "name": "Debug/x64/GCC",
        },
        {
            "name": "Release/x86/GCC",
        },
		{
            "name": "Debug/x86/GCC",
        },
		
        {
            "name": "Release/x64/Clang",
        },
		{
            "name": "Debug/x64/Clang",
        },
        {
            "name": "Release/x86/Clang",
        },
		{
            "name": "Debug/x86/Clang",
        },
		
        {
            "name": "Release/x64/ICC",
        },
		{
            "name": "Debug/x64/ICC",
        },
        {
            "name": "Release/x86/ICC",
        },
		{
            "name": "Debug/x86/ICC",
        },
    ],
    "version": 3
}
```

**Comment by sean-mcmanus** [comment]
I don't fully understand how sub-configurations would work to simplify your configuration. We could add a "group" to each config, so "Debug" and Release would have group 0 and x64 and x86 would be group 1, etc., and then the status bar would show one item for each group, but you're still left with the problem that each combination of groups may need settings specific to that combination, e.g. 4 different compilerPath settings. Using env variables in the configs might reduce some of the duplication in the configurations themselves: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md .

**Comment by ci70** [comment]
Indeed. That would solve the problem. We'd probably then need groups for launch.json too. 
As the debuggers are different.
