### ISSUE TITLE
ipp::IwException cannot be ignored after first hit.

### ISSUE THREAD

**Issue by graph** [microsoft/vscode-cpptools#2848]
Type: Debugger
**Input information below**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version:
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- C/C++ Extension Version: 0.20.1
- When debugging my app I do "All Exceptions" then an ipp::IwException exception occurs. I disable "all exceptions" and vs code still keeps breaking on that exception.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. enable "All Exceptions"
2. start your app in debug
3. trigger an ipp::IwException
4. disable "All exceptions"
5. trigger ipp::IwException again. It should not break because no breakpoints are set.

Also is there a way to not break on that exception? And is there a way to break on only unhandled exceptions?

**Comment by pieandcakes** [comment]
@graph is this using the `cppdbg` or `cppvsdbg` debugAdapter `type` ?

**Comment by graph** [comment]
I'm using `cppvsdbg` for the `type` parameter.
