### ISSUE TITLE
New icons for completion and symbols (operators, structs/unions, enum values, template arguments, macros)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2849]
Let us know if anyone has any problems with our icon usage.

Operators (previously used the function/method icon): 
![image](https://user-images.githubusercontent.com/19859882/48870265-f8ce1c00-ed94-11e8-9309-be4c58285266.png)
Structs/Unions (previously used the Class icon):
![image](https://user-images.githubusercontent.com/19859882/48870271-fec3fd00-ed94-11e8-8537-183b9f2f968b.png)
Enum values (previously used the Enum icon):
![image](https://user-images.githubusercontent.com/19859882/48870279-0f747300-ed95-11e8-943f-5231d2a132d5.png)
Template arguments (previously used the Enum icon):
![image](https://user-images.githubusercontent.com/19859882/48870375-84e04380-ed95-11e8-807f-e408a2e14d31.png)
Typedefs and using aliases (previously used the Class icon for symbols and the Enum icon for completion). We're using the "interface" icon for typedefs/aliases because VS Code provides no other alternative that is closer to the icon Visual Studio uses (extra (typedef) and (type alias) text should alleviate the confusion):
![image](https://user-images.githubusercontent.com/19859882/48870547-29fb1c00-ed96-11e8-8c0e-451bc2910889.png)
Macros/defines (previously used the Enum icon):
![image](https://user-images.githubusercontent.com/19859882/48870943-99254000-ed97-11e8-94e9-482ed491bfe0.png)
Folders (or symlinks to folders) (previously only files were selectable in `#include` completion):
![image](https://user-images.githubusercontent.com/19859882/48871104-25376780-ed98-11e8-8977-ff829302cb9a.png)
Symbolic links to files (previously used the File icon corresponding to the symlink's type, not the target's type): This is possible, but I removed it because it doesn't seem to be worth it to check if every file is a symlink or not, just to have a different icon. Symlinks that are folders will appear as folders, which is the most important thing.
![image](https://user-images.githubusercontent.com/19859882/48876789-f380c980-edb4-11e8-9022-517ef7d5f971.png).

Unchanged icons: 
Classes/templates:
![image](https://user-images.githubusercontent.com/19859882/48870207-c45a6000-ed94-11e8-9893-190b1d978a0c.png)
Enum types:
![image](https://user-images.githubusercontent.com/19859882/48870213-c8867d80-ed94-11e8-821d-258a195a4f06.png)
Functions/methods/constructors:
![image](https://user-images.githubusercontent.com/19859882/48870220-ccb29b00-ed94-11e8-9b77-b05590042ccc.png)
Member fields/variables:
![image](https://user-images.githubusercontent.com/19859882/48870760-d63d0280-ed96-11e8-91a1-507ecfe593d7.png)
Variables:
![image](https://user-images.githubusercontent.com/19859882/48870775-ef45b380-ed96-11e8-8530-1292f6ba431e.png)
Namespaces:
![image](https://user-images.githubusercontent.com/19859882/48870861-3fbd1100-ed97-11e8-8448-aa6744db0235.png)

**Comment by nxyd** [comment]
Can you distinguish declaration and definition using different icons for function?

**Comment by sean-mcmanus** [comment]
@xiaoyongdong Not currently. Visual Studio supports that icon type (arrow over the purple cube for declarations) -- I've added a feature request for VS Code at https://github.com/Microsoft/vscode/issues/63617 . You could add to that issue if you think of other icons we should add as well.

We might be able to add text like "(declaration)" to the symbol name...or we might have to switch to the new DocumentSymbol API first: https://github.com/Microsoft/vscode-cpptools/issues/2230 .

**Comment by sean-mcmanus** [comment]
@xiaoyongdong Adding (declaration) text to the end of the symbol seems to be a workaround for the icon deficiences: https://github.com/Microsoft/vscode-cpptools/issues/2851 .

**Comment by nxyd** [comment]
@sean-mcmanus Thank you! According to you it maybe the best way currently if extension can't use different icons.

**Comment by rewrking** [comment]
Does the #include completion use the theme's folder icon if it's present?

**Comment by sean-mcmanus** [comment]
@andrew-r-king Yes, the icon image is (will be) based on the theme. E.g.
![image](https://user-images.githubusercontent.com/19859882/49049241-0e778300-f193-11e8-91a3-da366da8eb75.png)

**Comment by sean-mcmanus** [comment]
Updated icons/symbol info is supported now with our latest Insiders release: https://github.com/Microsoft/vscode-cpptools/releases . If you're using VS Code Insiders or have http.proxySupport not set to "off", you might not get the 0.21.0-insiders2 update automatically with C_Cpp.updateChannel set to "Insiders".
