### ISSUE TITLE
Add (declaration), (typedef), (type alias), (union) to symbols

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2851]
I'm not sure why we didn't do this a long time ago. It's a workaround for deficiencies in the VS Code icon support.

![image](https://user-images.githubusercontent.com/19859882/48881580-01d9e000-edcb-11e8-9458-c8a2f94344f3.png)
![image](https://user-images.githubusercontent.com/19859882/48881752-e6230980-edcb-11e8-85d8-8636f17bd90b.png)

**Comment by nxyd** [comment]
Why no (declaration) tag?
![image](https://user-images.githubusercontent.com/3884211/50127058-71e46480-02aa-11e9-808b-6d86ca123be9.png)

**Comment by sean-mcmanus** [comment]
Thanks for reporting that bug -- looks like that got broken at some point (or the implementation only worked in certain cases?). It should be easy to fix.

**Comment by sean-mcmanus** [comment]
Okay, it's fixed now, for our next release (a last minute code clean up broke it and our tests didn't catch it).

We might release the non-Insiders 0.21.0 in a few days.

**Comment by sean-mcmanus** [comment]
@xiaoyongdong Our latest [0.21.0-insiders3](https://github.com/Microsoft/vscode-cpptools/releases) has fixed the `(declaration)` missing from the symbol name.
