### ISSUE TITLE
redundant symbols are added to Outline

### ISSUE THREAD

**Issue by nxyd** [microsoft/vscode-cpptools#2853]
I am using QT.
If i use 'foreach' in a function, then some redundant symbols would be added to Outline.

See below, 'foreach' and 'tmp' were added, but 'test' is missing.
![image](https://user-images.githubusercontent.com/3884211/48884018-807f5d80-ee5d-11e8-854c-f3c7efa75e56.png)

![image](https://user-images.githubusercontent.com/3884211/48884011-74939b80-ee5d-11e8-8ea7-6357b85a2834.png)

**Comment by sean-mcmanus** [comment]
Where is "foreach" defined? It's a macro, right? It needs to be added to a cpp.hint file in order for our symbol parser to be able to not break. See https://msdn.microsoft.com/en-us/library/dd997977.aspx .

**Comment by nxyd** [comment]
yes, it is a macro defined in qt header file.
oh, it looks comlicated.

why don't need to do anything same in VS?

**Comment by sean-mcmanus** [comment]
VS should require the same for it's symbol parser to work.

Using foreach or Q_FOREACH is not recommended -- see http://doc.qt.io/qt-5/qtglobal.html#Q_FOREACH . Using something like `for (const auto &item: list)` is recommended.

**Comment by nxyd** [comment]
Thank you.  It seems to be working after i added a cpp.hint file.
