### ISSUE TITLE
Improve includePath resolution for header files

### ISSUE THREAD

**Issue by g-arjones** [microsoft/vscode-cpptools#2856]
How does the extension match header files names to source file names to infer include paths and compilation definitions? Is it required that source and header files live in the same directory?

**Comment by bobbrow** [comment]
No, they shouldn't need to live in the same directory, but it helps.  If you open the source file before the header, that will ensure that the include paths are correct for the header file.  There is still more work for us to do to improve the experience for headers.

**Comment by g-arjones** [comment]
Could you please point me to the relevant piece of code? I would like to understand how this works... Thanks!

**Comment by bobbrow** [comment]
Unfortunately, that part of the code is in the closed-source binary that we release with the extension.

**Comment by g-arjones** [comment]
@bobbrow I noticed that if header and implementation live in the same directory, vscode-cpptools will resolve the includePaths right away, if they don't, I have to do what you suggested and open the source before opening the header. Is there another workaround? This is a bit annoying and people in my team don't get why sometimes vscode resolves the paths and sometimes it doesn't... Explaining that every time is even more annoying...

I noticed that you added this issue to the "On Deck" milestone, does this mean that there is a fix coming?

**Comment by bobbrow** [comment]
Unfortunately, I don't have another workaround right now.

"On Deck" means it has a higher priority than the average issue.  When selecting issues to address for the next milestone, I look through this list first.

**Comment by g-arjones** [comment]
Ok.. Thanks a lot! :)

**Comment by Colengms** [comment]
>How does the extension match header files names to source file names to infer

Hi @g-arjones .  I've been working on some improvement to how the C/C++ extension decides which source file to use to open a TU for a header file.  We will use the following heuristics:

 - Source files are preferred. If no source file is found that includes the header (directly, or indirectly), the header itself is used.
 - Source files with the same name as the header (without extension) are preferred.
 - Source files in immediate parent directories that are similar to the immediate parent directory of the header, are preferred. For example, "/src/utils/source.cpp" will be preferred for "/inc/utils/header.h" over source files not immediately within a directory named "utils". If there are multiple levels of similar parent directory names, more similarly named directories are preferred over fewer similarly named directories. For example, "/src/a/b/c/source.cpp" will be preferred over "/src/b/c/source.cpp" for "/inc/a/b/c/header.h".  Source files in the same directory as the header are implicitly the best match for this rule.
 - Source files with closer path proximity to the header file are preferred. Paths with the least number of subfolder differences are preferred, followed by paths with the nearest proximity to common parent folder.  For example, for the header "\a\b\file.h", we will prefer headers in the following order: \a\b\file.cpp, \a\file.cpp, \a\b\c\file.cpp, \a\x\file.cpp
 - Source files with custom configurations are preferred over source files without custom configurations.
 - Source files with compile commands are preferred over source files without compile commands.

These rules are applied in the above order.  Only if multiple candidates are found to be equivalent by one rule is the next rule is applied.

We are hoping this will address the majority of the scenarios that have been reported in which TU selection has not been ideal.

**Comment by g-arjones** [comment]
Sounds perfect to me. I can't think of a reasonable layout that wouldn't fit one of these scenarios. 

One question though, how does the extension decide what's a "source file"? I've seen projects that use .cc,.cpp,.c++,.cxx and .c. Can we configure that in the extension?

**Comment by michelleangela** [comment]
Fixed in version 0.26.2-insiders, please try it out and let us know what you think. Vsix is available at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders

**Comment by g-arjones** [comment]
@michelleangela @Colengms Does not work for me, unfortunately. I still have to open the source file first. Does the extension recognize .cc and .hh as sources and headers?

**Comment by Colengms** [comment]
@g-arjones .  Could you provide the output from "Log Diagnostics" after opening the header?  That will show what source file was selected for the header.

Are you using the cmake-tools extension?  If so, you will need at least v1.2.2, as there was an issue that could could the source file path not to be included in the browse path.

**Comment by g-arjones** [comment]
> Could you provide the output from "Log Diagnostics" after opening the header? 

@Colengms Sure:

```
-------- Diagnostics - 11/18/2019, 9:06:02 AM
Version: 0.26.2-insiders
Current Configuration:
{
    "name": "Linux",
    "defines": [],
    "knownCompilers": [
        {
            "path": "/usr/bin/clang",
            "isC": true
        },
        {
            "path": "/usr/bin/clang++",
            "isC": false
        },
        {
            "path": "/usr/bin/clang-5.0",
            "isC": true
        },
        {
            "path": "/usr/bin/clang++-5.0",
            "isC": false
        },
        {
            "path": "/usr/bin/clang-3.8",
            "isC": true
        },
        {
            "path": "/usr/bin/clang++-3.8",
            "isC": false
        },
        {
            "path": "/usr/bin/gcc",
            "isC": true
        },
        {
            "path": "/usr/bin/g++",
            "isC": false
        },
        {
            "path": "/usr/bin/cpp",
            "isC": false
        },
        {
            "path": "/usr/bin/gcc-5",
            "isC": true
        },
        {
            "path": "/usr/bin/g++-5",
            "isC": false
        },
        {
            "path": "/usr/bin/clang",
            "isC": false
        }
    ],
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "includePath": [
        "${workspaceFolder}/include",
        "/opt/ros/kinetic/include",
        "/usr/include/x86_64-linux-gnu/qt5/**"
    ],
    "compileCommands": "<full path omitted>/build/attraction_force_surface_gazebo/compile_commands.json",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${default}",
            "${workspaceFolder}/include",
            "/opt/ros/kinetic/include",
            "/opt/ros//include",
            "/usr/include/x86_64-linux-gnu/qt5/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ <full path omitted>/attraction_force_surface_gazebo/include/attraction_force_surface_gazebo/MagnetFunctionFactory.hh ]:
    <full path omitted>/attraction_force_surface_gazebo/include/attraction_force_surface_gazebo/MagnetFunctionFactory.hh
Translation Unit Configurations:
[ <full path omitted>/attraction_force_surface_gazebo/include/attraction_force_surface_gazebo/MagnetFunctionFactory.hh ]:
    Process ID: 7744
    Memory Usage: 75 MB
    Compiler Path: /usr/bin/clang
    Includes:
        <full path omitted>/attraction_force_surface_gazebo/include
        /opt/ros/kinetic/include
        /usr/include/c++/5
        /usr/include/x86_64-linux-gnu/c++/5
        /usr/include/c++/5/backward
        /usr/local/include
        /usr/lib/llvm-3.8/lib/clang/3.8.0/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=30800
        --header_only_fallback
Total Memory Usage: 75 MB
```

I have a `MagnetFunctionFactory.cc` in `${workspaceFolder}/src/MagnetFunctionFactory.cc` but the extension doesn`t seem to pick that up. I also got this in the extension logs:

```
Can't create IntelliSense client for  <full path omitted>/attraction_force_surface_gazebo/include/attraction_force_surface_gazebo/MagnetFunctionFactory.hh
```

attraction_force_surface_gazebo is the workspace base name

**Comment by sean-mcmanus** [comment]
Your browse.path setting appears to be incorrect, unless you have set the C_Cpp.default.browse.path to be correct. It appears to be missing `${workspaceFolder}` or `${workspaceFolder}/src`, which could cause our code to not be able to associate the header with the source file.

**Comment by g-arjones** [comment]
I have updated browse paths as you suggested by it doesn't seem to have any effect. Updated logs:

```
-------- Diagnostics - 11/19/2019, 9:05:55 AM
Version: 0.26.2-insiders
Current Configuration:
{
    "name": "Linux",
    "defines": [],
    "knownCompilers": [
        {
            "path": "/usr/bin/clang",
            "isC": true
        },
        {
            "path": "/usr/bin/clang++",
            "isC": false
        },
        {
            "path": "/usr/bin/clang-5.0",
            "isC": true
        },
        {
            "path": "/usr/bin/clang++-5.0",
            "isC": false
        },
        {
            "path": "/usr/bin/clang-3.8",
            "isC": true
        },
        {
            "path": "/usr/bin/clang++-3.8",
            "isC": false
        },
        {
            "path": "/usr/bin/gcc",
            "isC": true
        },
        {
            "path": "/usr/bin/g++",
            "isC": false
        },
        {
            "path": "/usr/bin/cpp",
            "isC": false
        },
        {
            "path": "/usr/bin/gcc-5",
            "isC": true
        },
        {
            "path": "/usr/bin/g++-5",
            "isC": false
        },
        {
            "path": "/usr/bin/clang",
            "isC": false
        }
    ],
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "includePath": [
        "${workspaceFolder}/include",
        "/opt/ros/kinetic/include",
        "<omitted>/install/include",
        "/usr/include/x86_64-linux-gnu/qt5/**"
    ],
    "compileCommands": "<omitted>/build/attraction_force_surface_gazebo/compile_commands.json",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${default}",
            "${workspaceFolder}",
            "/opt/ros/kinetic/include",
            "/usr/include/x86_64-linux-gnu/qt5/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ <omitted>/src/attraction_force_surface_gazebo/include/attraction_force_surface_gazebo/MagnetFunctionFactory.hh ]:
    <omitted>/src/attraction_force_surface_gazebo/include/attraction_force_surface_gazebo/MagnetFunctionFactory.hh
Translation Unit Configurations:
[ <omitted>/src/attraction_force_surface_gazebo/include/attraction_force_surface_gazebo/MagnetFunctionFactory.hh ]:
    Process ID: 6986
    Memory Usage: 75 MB
    Compiler Path: /usr/bin/clang
    Includes:
        <omitted>/src/attraction_force_surface_gazebo/include
        /opt/ros/kinetic/include
        <omitted>/install/include
        /usr/include/c++/5
        /usr/include/x86_64-linux-gnu/c++/5
        /usr/include/c++/5/backward
        /usr/local/include
        /usr/lib/llvm-3.8/lib/clang/3.8.0/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=30800
        --header_only_fallback
Total Memory Usage: 75 MB
```

Am I missing something or is intellisense mapping the header to the header itself?

**Comment by g-arjones** [comment]
I have added `${workspaceFolder}/src` to browse path (rather than `${workspaceFolder}`) and it did the trick. But that doesn't feel right, I think source files should be preferred (and that's what the algorithm @Colengms mentioned should be doing, right?)

**Comment by g-arjones** [comment]
Adding `${workspaceFolder}/**` also works but should this really be required?

**Comment by sean-mcmanus** [comment]
`${workspaceFolder}/**` and `${workspaceFolder}` should be equivalent in the browse.path setting -- both are treated as being recursive. Maybe `${workspaceFolder}` didn't work because the source files weren't finished parsing? The browse.path setting specifies the root directory where global symbols are parsed.

**Comment by g-arjones** [comment]
> because the source files weren't finished parsing?

You were right.. Just tried again :+1:

**Comment by g-arjones** [comment]
Thanks for working on this guys ;)
