### ISSUE TITLE
[vscode exploration][build] terminal doesn't show in exploration build when building my app for debug

### ISSUE THREAD

**Issue by graph** [microsoft/vscode-cpptools#2857]
Type: General

- VSCode Version:
Version: 1.30.0-exploration (user setup)
Commit: 6312280271061e6be2909b3ffc677972e1875069
Date: 2018-11-21T06:16:14.348Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
- cpptools version: 0.20.1
- OS Version: windows 10

Steps to Reproduce:

1. setup tasks.json & launch configuration
2.  goto debug tab
3. press play

Does this issue occur when all extensions are disabled?: I haven't tried

Terminal should popup and show log info of my build. But instead nothing happens. It definitly does build and launch my app in debug. And problems are populated normally, but my terminal doesn't show the output. No terminal is added to the terminal list dropdown too. Stable build has no problems and terminal opens just fine automatically.

Sometimes I get the specified task cannot be tracked error.

**Expected behavior**
Terminal to popup and for me to see build output in terminal

**Additional context**
Originally filed here https://github.com/Microsoft/vscode/issues/63596 I feel it's more of a problem in the vscode itself because my build output doesn't show, which is before the debugging phase.

<details>
<summary>launch.json</summary>

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/debug/someexe.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}/build/debug",
            "environment": [],
            "externalConsole": true,
            "preLaunchTask": "build"
        },
        {
            "name": "test",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/test/path/to/test/build/debug/test.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}/test/path/to/test/build/debug/",
            "environment": [],
            "externalConsole": true,
            "preLaunchTask": "build_test"
        },
        {
            "name": "test release",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/test/path/to/test/build/release/test.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}/test/path/to/test/build/release",
            "environment": [],
            "externalConsole": true,
            "preLaunchTask": "build_test_release"
        },
        {
            "name": "Launch release",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/release/someexe.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}/build/release",
            "environment": [],
            "externalConsole": true,
            "preLaunchTask": "build_release"
        }
    ]
}
```
</details>

**Comment by pieandcakes** [comment]
@weinard Our extension doesn't control build output. What sort of investigation would you like us to do? I took a look at Microsoft/vscode#63596 but don't see any hints.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
