### ISSUE TITLE
[VS Code Insiders] type "cppdbg" throw NullReferenceException on launch

### ISSUE THREAD

**Issue by payonel** [microsoft/vscode-cpptools#2858]
Type: Debugger

**Additional context**
PLEASE NOTE This works on VSCode stable release, only crashing on insiders build

Version: 1.30.0-insider
Commit: 0d3a14402d88f0f555ab3250c3ffd4c45a251665
Date: 2018-11-22T06:14:14.378Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-39-generic

Using type "cppdbg" failing to launch cpp program [ basic hello world, basic auto generated launch script ]

In the debugger window it prints:
`Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object`

**To Reproduce**
launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "C++ Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceRoot}/a.out",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceRoot}",
      "environment": [],
      "externalConsole": true,
      "linux": {
          "MIMode": "gdb",
          "setupCommands": [
              {
                  "description": "Enable pretty-printing for gdb",
                  "text": "-enable-pretty-printing",
                  "ignoreFailures": true
              }
          ]
      }
  }
]
}
```

code
`int main() { return 0; }`

**Comment by weinand** [comment]
It would be great if reports of these kind of breaking behaviour in VS Code would reach us as soon as you find them in Insiders. We would have fixed this within one day (for the next Insiders).

**Comment by sean-mcmanus** [comment]
The debugger failure should be fixed now with our latest Insiders release: https://github.com/Microsoft/vscode-cpptools/releases . If you're using VS Code Insiders or have http.proxySupport not set to "off", you might not get the 0.21.0-insiders2 update automatically with C_Cpp.updateChannel set to "Insiders".

**Comment by FelixKimmerle** [comment]
I have the same issue with the Version
1.30.1
dea8705087adb1b5e5ae1d9123278e178656186a
x64

(so it's not an insider build)

Im also using Linux (Ubuntu 18.04)

**Comment by WardenGnaw** [comment]
@FelixKimmerle This is now fixed with the latest cpptools insider's version. 

See: https://github.com/Microsoft/vscode-cpptools/issues/2922
