### ISSUE TITLE
external terminal not closing when program ends (linux)

### ISSUE THREAD

**Issue by payonel** [microsoft/vscode-cpptools#2859]
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

(can't test on vscode insiders and this extension crashes on that version: see #2858 )

`      "externalConsole": true,`
external terminal is not closing on program exit

Same exact issue with webfreak's native debug extension, so this might not be your plugin's fault. I'm making a bug report there and will reference this.

**Comment by payonel** [comment]
related, or perhaps vscode issue, and not the plugin
https://github.com/WebFreak001/code-debug/issues/161

**Comment by payonel** [comment]
might be MIEngine issue: https://github.com/Microsoft/MIEngine/issues/807

**Comment by pieandcakes** [comment]
@payonel If you are using our latest extension version, the terminal is all controlled now by VS Code. You may want to open an [issue](https://github.com/microsoft/vscode/issues) there.
