### ISSUE TITLE
is there a configuration that can make parser start manually

### ISSUE THREAD

**Issue by chongchai** [microsoft/vscode-cpptools#2861]
When I open a large project, the parser will run for a long time. And after I use git to checkout a branch, it also consumes a lot time and makes the CPU in high usage. (This can make my computer to freeze for some time since my computer is not so good).

I want to stop Intellisense parser run automatically and set it to run when I'm ready to start.
I find a command "C_Cpp.PauseParsing", but it is not a configuration. So before I checkout a branch, I execute the "C_Cpp.PauseParsing" but the parser is still running.

Is there a configuration that can make parser start manually?

**Comment by sean-mcmanus** [comment]
You could create a config with
```
"browse": {
"path": []
}
```

However, when you open files, it'll still try to parse the headers for symbols as a non-background task.

Setting workspaceParsingPriority setting to "low" may also solve the issue for you, or we could add an even lower setting of "off".

**Comment by chongchai** [comment]
@sean-mcmanus  Thanks for your reply. 

> You could create a config with
> 
> "browse": {
> "path": []
> }
> However, when you open files, it'll still try to parse the headers for symbols as a non-background task.
I think change this config is not so handy. And can cause two problems:
1. As you said, open files still make parser to run.
2. setting browse.path to empty will make all the 'go to definition' to fail (even this relation is already parsed)

> Setting workspaceParsingPriority setting to "low" may also solve the issue for you

 Setting workspaceParsingPriority setting to "low" seems not take effect, since my cpu still consumes more than 50%.

## My advice is like this.
Maybe you can add a setting (for instance called parseEnabled).
* When setting parseEnabled to false, it will not parse any files, but still can provide 'go to definition' and ‘find symbols’ with the old parse result.
* When setting parseEnabled to true, it will start to parse the project files and sync the parse result to latest.

My scenario is to  checkout branch in a large project. I can accept the parser index db is not accurate for the modified or new file. But make computer to freeze is not so good.

**Comment by bobbrow** [comment]
The problem happens when lots of files change, right?  VS Code and our extension set up file watchers for your folder when you open it.  Can you try using the `files.watcherExclude` setting to exclude your workspace folder and see if that fixes your problem?  You can experiment by adding `"**/*": true` to the list of paths to exclude.

I tried this out on one of my large code folders and it seems to work the way I expect when changing branches.  As you mention, this will mean that our extension will show old parse results, but if you need to refresh the database, you can use the "Reload Window" command to force our extension to rescan the filesystem (using the mechanism that respects the workspaceParsingPriority setting).

**Comment by chongchai** [comment]
@bobbrow I tried your suggestion. It' good for me when checkout branch. 
ps:
Maybe one problem is that I can't control when to start parse new file. In my opinion, I think "Reload Window" command is not a perfect solution and user can't know when the parser is finished.

**Comment by sean-mcmanus** [comment]
@chongchai You can [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) to see when files are being parsed in the output window (and for background parsing of the workspace folders we show an icon in the bottom right).

**Comment by Lennon925** [comment]
@sean-mcmanus @bobbrow 

Hi both,

I have same requirements with chongchai's. And I listed the requirements in issue 3072

Regards,
Lennon

**Comment by bobbrow** [comment]
Thank you for the feature suggestion, but we're reviewing some of our older requests and do not have plans to implement this feature.
