### ISSUE TITLE
Erroneous warning for vector initialization

### ISSUE THREAD

**Issue by davepl** [microsoft/vscode-cpptools#2864]
Initializing a vector as follows warns that non-aggregate types cannot be initiliazed with an initializer list, but of course that's totally valid under the current standard (and it compiles and works):

```
std::vector<SceneElement> Setup2 =
{
    // Effect                          Offset   Count
    SceneElement(_RainbowEffect, g_LEDs, 0 * 144, 8 * 144),
};
```
I have tried C++11 and 14 as the standard in the settings file to no avail.  Other warnings seem correct for my setting.

**Comment by bobbrow** [comment]
I don't repro on Windows or Mac.  Can you provide more information about your configuration?

![image](https://user-images.githubusercontent.com/12818240/49032479-87f67d80-f161-11e8-8e4d-0bb8fd116313.png)

**Comment by davepl** [comment]
Sorry, I’ve now traced this to the C/C++ Clang Command Adapter!  Safe to close the issue.
