### ISSUE TITLE
CMake Project cannot open source file but go to definition works

### ISSUE THREAD

**Issue by kfabian** [microsoft/vscode-cpptools#2865]
**Type: LanguageService**

**Describe the bug**

- OS and Version: Ubuntu 18.04
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): CMake, CMake Tools

I have a CMake C++ project where I get the error "cannot open source file" for includes like `#include <Eigen>`. Despite this error I can click on "go to definition" and the correct header is opened. I wonder where VSC looks for these headers and how this path can be extended.

Thanks

**Comment by bobbrow** [comment]
Have you seen [this documentation](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started%20with%20IntelliSense%20configuration.md)?

**Comment by bobbrow** [comment]
You might also consider installing the CMake Tools extension by vector-of-bool.  It can send our extension the include paths after it analyzes the CMakeLists.txt.

**Comment by kfabian** [comment]
Thanks. I think the error message came from the Clang Command Adapter extension.
