### ISSUE TITLE
Feature request: in debug console, is it possible to just input gdb command directly instead of -exec gdb command?

### ISSUE THREAD

**Issue by kgfly** [microsoft/vscode-cpptools#2866]
Feature request: 

Currently, in debug console, to execute gdb command, I've to type "-exec gdb_command".

is it possible to just type gdb command?  Typing "-exec" seems unnecessary. It's very inconvenient when you need type lots of command.

On the other hand, your competitor, vscode LLDB plugin does not request to type -exec, which is convenient and make sense.

Thanks.

**Comment by WardenGnaw** [comment]
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/106

**Comment by pieandcakes** [comment]
@9527KGG No,  because the debugConsole was designed by VS Code to be for variable and expression evaluation. we had to add parsing to parse for -exec so we know when it is a gdb command and to reroute it to gdb as a command.
