### ISSUE TITLE
Feature request: please add lldb support on Linux.

### ISSUE THREAD

**Issue by kgfly** [microsoft/vscode-cpptools#2867]
This is a feature request.

AFAIK, vscode-cpptools does not support LLDB on Linux. Please add support for it. Since vscode-cpptools supports lldb on MAC. I don't think there would be lots of work.

Thanks.

**Comment by pieandcakes** [comment]
If you download lldb and change `MIMode` to `lldb` and then set `miDebuggerPath` to the `lldb-mi` executable, it should work. Have you tried it?

**Comment by kgfly** [comment]
I've added:
            "MIMode": "lldb",
            "miDebuggerPath": "/usr/bin/lldb",
When starting debug, vscode prompts
![image](https://user-images.githubusercontent.com/12282281/49044163-d61b7900-f181-11e8-8d06-f89868cb3c88.png)

Suggestion?

**Comment by pieandcakes** [comment]
@you need `lldb-mi` as your executable, not `lldb`.

**Comment by kgfly** [comment]
I see. Working now. Thanks for helping~

**Comment by kgfly** [comment]
I think I hit a bug:

Please see the error in the image:

![image](https://user-images.githubusercontent.com/12282281/49047389-2566a700-f18c-11e8-8dcc-1fe0ccf45ada.png)

Any suggestions about the error?

**Comment by pieandcakes** [comment]
That isn't a bug. You are going to have to look up what the corresponding lldb commands are. `info registers` is a `gdb` command.  I would suggest [this](https://lldb.llvm.org/lldb-gdb.html) document. I think you are looking for `-exec register read`.

**Comment by kgfly** [comment]
I see. Thanks.
