### ISSUE TITLE
Icons out of place on autocompletion

### ISSUE THREAD

**Issue by mikaelsouza** [microsoft/vscode-cpptools#2868]
**Type: LanguageService**

**Bug description**

Icons in the autocomplete menu sometimes look out of place when selected. This doesn't seem to happen while using Python so this may be an issue related to the CPP extension.

- OS and Version: macOS 10.14.1
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): None.

**To Reproduce**

1. Create a simple Hello World program as described shown here:
```cpp
#include <iostream>
int main(){
    std::cout << "Hello Github!" << std::endl;
    return 0;
}
```
2. While typing `std::cou` wait for the autocompletion to appear, it should recommend `count` as a completion.
3. Use the keyboard to go down or up throughout the list and, you should notice that some icons are out of place when selected.

**Expected behaviour**

Icons should be centred just like when they are not selected. 

**Screenshots**

<img width="556" alt="screenshot 2018-11-25 at 10 44 21" src="https://user-images.githubusercontent.com/9092284/48980442-42717c00-f09f-11e8-884a-5ca0586f79cf.png">

<img width="525" alt="screenshot 2018-11-25 at 10 44 38" src="https://user-images.githubusercontent.com/9092284/48980447-48fff380-f09f-11e8-8d9e-81c9a97fe31f.png">

<img width="759" alt="screenshot 2018-11-25 at 10 45 24" src="https://user-images.githubusercontent.com/9092284/48980448-4d2c1100-f09f-11e8-9b9a-7d8957917cb3.png">

**Comment by bobbrow** [comment]
Can you report this issue to the VS Code team?  We don't control icon placement.
https://github.com/Microsoft/vscode/issues/new?template=bug_report.md

**Comment by mikaelsouza** [comment]
Sure! As I said before, it didn't happen while using autocomplete for python, so I reported it here.

Thanks for pointing out the correct place to post this issue.
