### ISSUE TITLE
Support for Cilk plus (lcilkrts) annotations

### ISSUE THREAD

**Issue by DavidRomao** [microsoft/vscode-cpptools#2869]
**Type: LanguageService**

When using the lcilkrts (cilk plus) library the annotations are not recognized and it displays a syntax error. I have  the import correct and it seems VS code detects that they are correct, it just doesn't recognize the annotations, like cilk_for, cilk_spawn and cilk_sync. 

Sorry if this has been asked before or it's because I am missing something in

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.29.1
- C/C++ Extension Version: 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

1. Create a *.c file and have gcc installed with version that still includes cilk plus. ( i have 7.3.0 )
2. Include the cilk libraries and try to use cilk_spawn with a function call or a cilk_for instead of a for.
```
#include <cilk/cilk.h>
#include <cilk/cilk_api.h>
```
3. Notice that the cilk annotation and everything until the end of the line has a syntax error.

Here's my c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Expected behavior**

I expected not to have a syntax error.

**Comment by bobbrow** [comment]
We do not natively support custom keywords.  If these are just annotations, you should be able to work around the issue by adding them as empty pre-processor defines and IntelliSense will ignore them:

```
    "defines": [
        "cilk_spawn=",
        "cilk_for=",
        "cilk_sync=",
    ]
```

**Comment by DavidRomao** [comment]
Adding them as you said works fine as a workaround, even with the "cilk_for=for". 
Thanks for the quick response.
