### ISSUE TITLE
A few missing keywords in highlighting

### ISSUE THREAD

**Issue by DevSecTim** [microsoft/vscode-cpptools#287]
'sizeof'
![screenshot from 2016-10-14 10-17-19](https://cloud.githubusercontent.com/assets/2226767/19382283/6cd0dbac-91f7-11e6-9ab9-98e563d1db91.png)

**Comment by DevSecTim** [comment]
'override'
![screenshot from 2016-10-14 10-15-06](https://cloud.githubusercontent.com/assets/2226767/19382224/1dc4e562-91f7-11e6-95c0-7dc13b260b3c.png)

**Comment by sean-mcmanus** [comment]
We use the built-in VS Code atom/language-c as our colorizor.

sizeof is not really a bug -- it's being colorized that way by the theme you're using. Other themes don't repro the issue. See https://github.com/atom/language-c/issues/151 . I guess you could file a bug with the theme?

Also, override is not a keyword. I don't see it colorized like a keyword online, such as http://en.cppreference.com/w/cpp/language/override . If you want the colorization changed, it would probably be an atom bug.

**Comment by DevSecTim** [comment]
Fair enough on both comments, although I am using the default VSCode theme...

**Comment by DevSecTim** [comment]
'static_assert'
![screen shot 2016-11-03 at 10 30 04](https://cloud.githubusercontent.com/assets/2226767/19962635/8b195c4c-a1b0-11e6-9715-48826cf9e854.png)

**Comment by bobbrow** [comment]
We're asking VS Code to fix this: https://github.com/Microsoft/vscode/issues/22419
