### ISSUE TITLE
Cpp Intellisense not indexing variables defined by macro

### ISSUE THREAD

**Issue by jetacpp** [microsoft/vscode-cpptools#2876]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Build 17134
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Steps to Reproduce:

file1.c

```
#define make_var(name)  int name = 0;

// int global = 0;  // this variable can be found
make_var(global); // this variable is not found
```

file2.c
`int global = 1;`

test.c

```
extern int global;
int main()
{
    global = 1;
}
```
When multiple definitions are found, VS Code correctly lists them. However, if they are declared by a macro expansion then they are not found and listed (cannot go to definition, definition not listed). Looks like Intellisense indexing is working off prior to macro processing, correctly it should index after the macro expansion.

**Comment by sean-mcmanus** [comment]
Our symbol parser won't pick up definitions that are defined with macros. The define needs to be added to a cpp.hint file: https://msdn.microsoft.com/en-us/library/dd997977.aspx . Go to Def works after I added the cpp.hint file and Reload Window.

![image](https://user-images.githubusercontent.com/19859882/49186767-5d9bf000-f31a-11e8-974d-f7479e157f7f.png)
