### ISSUE TITLE
Auto-complete is not working

### ISSUE THREAD

**Issue by safield** [microsoft/vscode-cpptools#2877]
I am running vscode 1.29.1  with the c/c++ extension by Microsoft 0.20.1.

I have configured the extensions c_cpp_properties.json correctly, so all my includes are working.

I can jump to definition of any symbols in the project correctly.

Yet the auto-completion is not working.

When I start typing a variable name, it just shows me an ordered list of literally every symbol in the entire project.

In addition, why I have a variable class instance and I type '.', and I expect autocomplete to complete the members of that particular class, again, it just shows me the entire list of all the symbols of the project.

Is something misconfigured, or is this bug/unimplemented behaviour?

thanks.

**Comment by bobbrow** [comment]
Can you [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md), run the "Reload Window" command, and then try again?

Please share any of the logging that looks relevant.

**Comment by safield** [comment]
I don't have an idea of what would be relevant.

But when I type myClassPtr-> , specifically the '>' character, to bring up completion, I get this output...

> Offering completion
textDocument/codeAction

Here is all of the output of me just typing variables in my class.

> errorSquiggles count: 2
> errorSquiggles count: 2
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:6)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:7)
> Offering completion
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:8)
> Offering completion
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:7)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:8)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:7)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:6)
> Offering completion
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:6)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:7)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:8)
> Offering completion
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
>   tag parsing file: [redacted]
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
> sending 34 changes to server
> errorSquiggles count: 2
> errorSquiggles count: 2
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:7)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:6)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:6)
> Offering completion
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:7)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:8)
> Offering completion
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> Database safe to open
>   tag parsing file: [redacted]
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
> sending 12 changes to server
> errorSquiggles count: 2
> errorSquiggles count: 2
> Database safe to open
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/codeAction
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
>   tag parsing file: [redacted]
> sending 4 changes to server
> errorSquiggles count: 2
> errorSquiggles count: 2
> Database safe to open
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
> errorSquiggles count: 2
> errorSquiggles count: 2
> cpptools/activeDocumentChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:6)
> Offering completion
> textDocument/codeAction
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
>   tag parsing file: [redacted]
> sending 1 changes to server
> errorSquiggles count: 2
> errorSquiggles count: 2
> cpptools/textEditorSelectionChange
> cpptools/textEditorSelectionChange
> Database safe to open
> textDocument/documentHighlight
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:6)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:7)
> Offering completion
> errorSquiggles count: 2
> errorSquiggles count: 2
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:8)
> Offering completion
> textDocument/codeAction
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
>   tag parsing file: [redacted]
> sending 4 changes to server
> errorSquiggles count: 2
> errorSquiggles count: 2
> textDocument/codeAction
> Database safe to open
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
> errorSquiggles count: 2
> errorSquiggles count: 2
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:7)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:8)
> Offering completion
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/completion
> auto_complete::handle_completion: file:///c%3A/[redacted] (88:22)
> Offering completion
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> textDocument/didChange
> cpptools/textEditorSelectionChange
> textDocument/codeAction
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
>   tag parsing file: [redacted]
> sending 32 changes to server
> errorSquiggles count: 2
> errorSquiggles count: 2
> Database safe to open
> Checking for syntax errors: file:///c%3A/[redacted]
> queue_update_intellisense for files in tu of: [redacted]
> errorSquiggles count: 2
> errorSquiggles count: 2
>

**Comment by bobbrow** [comment]
It looks like there are 2 squiggles in your file.  Are they `#include` errors? (check the "Problems" window)  In this case, the extension will think you are not configured correctly and will provide more suggestions than you want.

**Comment by safield** [comment]
There actually was an include error. I traced it down, and it turns out stl headers are not being resolved.

All of these lines are squiggly...

```
#include <exception>
#include <assert.h>
#include <vector>
```

**Comment by safield** [comment]
The solution was to define the compilerPath to point to clang.exe.

**Comment by michelleangela** [comment]
Closing this issue as it's resolved according to the last comment.
