### ISSUE TITLE
Stop Debug will kill the program

### ISSUE THREAD

**Issue by Jackie-Yang** [microsoft/vscode-cpptools#2879]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:Win20
- VS Code Version:1.29.1
- C/C++ Extension Version:0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

I use GDB server to attach the debug program, but when I stop Debug, the program will be killed, can I just exit the GDB debug?

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by travishaagen** [comment]
I think the ask here, and what I would like, would be for _stop_ in the debugger to be configurable so that we could send SIGTERM instead of what it does now which is SIGKILL. 

Other plugins do this: https://github.com/Microsoft/vscode-node-debug2/issues/101

**Comment by joelspadin** [comment]
I would also like to be able to change the stop debugging signal. I have a Raspberry Pi application that allocates some resources using https://github.com/joan2937/pigpio and needs to release them when it stops. As things are currently, it leaks those resources every time I run a new debug session, and eventually I have to reboot. If I could get a SIGTERM when stopping debugging, that would fix the problem.
