### ISSUE TITLE
environment variables not recognized in includes path

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/vscode-cpptools#288]
it would be nice to be able to have environment variables in your include path

**Comment by sean-mcmanus** [comment]
We do support environment variables in the includePath via the syntax "${ENVVAR}". However, the tooltip for the includePath should mention that so users like yourself are better able to discover this.

**Comment by stevenbrix** [comment]
oh great, thanks sean! I couldn't find it anywhere in the documentation, so it would be helpful if it could be discovered that way too
