### ISSUE TITLE
[cppvsdbg] Debugging exes that require admin privileges results in the error 0x800702e4

### ISSUE THREAD

**Issue by maciek-codes** [microsoft/vscode-cpptools#2881]
Type: Debugger

- OS: Windows 10
- VS Code Version: 1.29.1
- C/C++ Extension Version:  0.20.1

Some debug targets require to be launched as an administrator. At the moment, the debugger fails to launch and attach to such executables and it prompts the user with an error message:

```
Unknown Error: 0x800702e4
```
There should be an option to launch the debugger as an administrator user (and show the UAC prompt). 
The workaround at the moment is to launch vscode as an administrator, but that's less ideal.

**Comment by pieandcakes** [comment]
@macqm please let us know which debugAdapter type you have specified in your `launch.json`

**Comment by maciek-codes** [comment]
I am using `"type": "cppvsdbg"`

**Comment by victoralvesp** [comment]
I stumbled on the same problem, but the workaround doesn't work for me.
I'm using debugAdapter `"type":"clr"`

**Comment by Ar5ham** [comment]
so this issue has been opened and closed multiple times... there are certainly some work around one can try but this is still an issue. So either VS code needs a directive and would launch the debugger as elevated so you dont have to run VSCode as elevated or when VSCode is launched as elevated then the debugger should too. 
You would also bump into the same issue on WSL with VSCode on the Linux side IIRC.
