### ISSUE TITLE
Refresh processes in process picker

### ISSUE THREAD

**Issue by mbise1993** [microsoft/vscode-cpptools#2885]
Type: Debugger

I've run into a scenario in which I need to launch a process, wait for that process to launch a subprocess, then attach to the subprocess in order to debug it. In an attempt to make this as convenient as possible, I'm using a compound configuration in my `launch.json` file to invoke both the launch config for the first process and the attach config for the subprocess. The first process writes the PID of the subprocess to the terminal, which I planned to use in the process picker to quickly select and attach to the subprocess. However, I've noticed that once the process picker is open, is doesn't update with newly created processes. I propose that the process picker either automatically check for new process at a certain interval or offer a refresh button so the user can refresh the list.

If this is seems like a useful feature, I would be happy to look into implementing it. Or, if you have any other suggestions for how to accomplish what I'm trying to do, that would be even better!

**Describe the bug**
- OS and Version: OSX Mojave (10.14.1)
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
1. Create a launch configuration with `"request": "attach"` and `"processId": "${command:pickProcess}"`
2. Invoke the launch configuration
3. Start a new process
4. Search for the new process in the process picker

**Additional context**

**Comment by pieandcakes** [comment]
@mbise1993 If this is something you want to implement, that would be great. You can also change the processId field to be the actual processId instead of the command. 

The code for it lives [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/Debugger/nativeAttach.ts).

**Comment by mbise1993** [comment]
@pieandcakes After looking into this a bit, my plan was to use the [QuickPick API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#QuickPick) to provide a refresh button for the list. However, it looks like that is only available in vscode API versions >= 1.26. Is there a timeline for when the vscode engine version of the extension will be advanced?

**Comment by WardenGnaw** [comment]
@mbise1993 Feel free to bump up the engine number with your PR. We will review it and see if the upgrade affects anything else.

**Comment by sean-mcmanus** [comment]
Yeah, I'm fine with increasing the VS Code dependency to 1.26.

**Comment by mbise1993** [comment]
I have what I believe to be a working implementation ([here's the diff](https://github.com/Microsoft/vscode-cpptools/compare/master...mbise1993:refresh_process_list)), but I haven't been able to test it with my original use case because I'm getting an error when I try to launch my process. Here's what I'm seeing in the extension output panel in the extension host: 
```
/Users/matt/dev/repos/vscode-cpptools/Extension/debugAdapters/OpenDebugAD7: line 32: mono: command not found
```
I have tested it by temporarily setting the `QuickPick` to stay open when it loses focus, manually launching another process, then refreshing the list. It works correctly in that case, but I'd like to test it in my original use case as well. Are there any steps I can take to resolve that error?

**Comment by pieandcakes** [comment]
You will need to copy the `mono` and `frameworks` folder from a working extension into your development area.
