### ISSUE TITLE
Unable to establish a connection to GDB when "externalConsole": false

### ISSUE THREAD

**Issue by tnqzh123** [microsoft/vscode-cpptools#2889]
Type: Debugger

(I'm sorry for my poor English)

- OS and Version: Windows 10 Pro 1809 18290.100
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.20.1

I want to debug with the built-in terminal on VS Code, so I set `"externalConsole": false` in `launch.json`.
But when I started debugging, it told me "Unable to establish a connection to GDB". I have already installed MinGW-w64.

![snipaste_2018-12-02_18-39-07](https://user-images.githubusercontent.com/16630630/49338852-b04f1200-f662-11e8-8607-2f9aa76bf9ce.png)

This is my `launch.json` file:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C/C++ Debugging with GDB",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "Compile C/C++"
        }
    ]
}
```
and `tasks.json`:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Compile C/C++",
            "command": "g++",
            "args": [
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}.exe",
                "-g",
                "-Wall",
                "-lm",
                "-std=c++17"
            ],
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared"
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": "absolute",
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
    ]
}
```

1. Open a c/cpp file
2. Navigate to Debug panel
3. Click "Start Debugging"
4. Error happened.

This error only happens when `"externalConsole": false` in launch.json. If `"externalConsole": true`, it will be normal.

**Comment by pieandcakes** [comment]
@tnqzh123 is there anything in the debug output like the error message says? Can you enable [engineLogging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) and let me know what the output is?

**Comment by tnqzh123** [comment]
@pieandcakes There are nothing in the debug console, even after I added
```json
"logging": {
    "trace": true,
    "traceResponse": true,
    "engineLogging": true
}
```
into `launch.json`.

Now my `launch.json` is:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C/C++ Debugging with GDB",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "Compile C/C++",
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
            }
        }
    ]
}
```

**Comment by tnqzh123** [comment]
I found it will start debugging normally some times when I set `"externalConsole": false`.
(Only some times!)

**Comment by mihaiconstantin** [comment]
I was setting-up vscode for a colleague (i.e, on Windows 7), using the configuration below. At that time it work, few days later it stopped working with the same message as you indicated. It works perfect on my computer (i.e., Windows 10).

I will investigate this further and write back. If you find anything new, please share below.

**Configuration on which it works:**
- OS and Version: Windows 10 NT x64, Version 1809, Build 17763.253
- VS Code Version: 1.30.2
  - Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
  - Electron: 2.0.12
  - Chrome: 61.0.3163.100
  - Node.js: 8.9.3
  - V8: 6.1.534.41
- C/C++ Extension Version: 0.21.0
- Other extensions you installed:
  - `CMake` -> the issue still persists after uninstalling it 


**Configuration(s) on which it fails:**
- *to be updated*


**`launch.json` configuration:**

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "build & debug",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "build (cmake)",
            "program": "${workspaceFolder}/bin/vscode/program.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\CLI\\gcc-tools\\mingw-w64\\x86_64-8.1.0-posix-sjlj-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": {
                "engineLogging": true
            }
        }
    ]
}
```

**Comment by clnmahone** [comment]
> I found it will start debugging normally some times when I set `"externalConsole": false`.
> (Only some times!)
It seems like the incompatible of windows' **power shell**, today I change the defualt shell to **cmd.exe**, and it works.
@tnqzh123 @mihaiconstantin

**Comment by ghost** [comment]
Thank you! simple but, very powerful solution! @mahonelee

**Comment by nadalaba** [comment]
I had the same issue and I'm using PowerShell as my default terminal too.
I found that sometimes there are multiple terminals open (spawned by the debugger sessions) and if one of these sessions didn't terminate properly (for whatever reason), vscode/extension can't establish a new connection to gdb, and launching a new debugging session will fail.

Solution in this case: Kill the freezed terminal (it should have the name "cppdbg:" or "cppvsdbg:" followed by `<debugged exe>`). If uncertain which one kill 'em all

P.S, Kill terminal is the trash can icon not the x icon.

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.

**Comment by christian-vorhemus** [comment]
I ran into the same problem today after updating Windows 10.

As others mentioned above, one workaround is to use cmd.exe instead of PowerShell as an internal shell by adding `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"` to the .vscode/settings.json file.

Another thing that worked for me was uninstalling and reinstalling the C/C++ extension in VS Code.

**Comment by 0xUrsa** [comment]
Also having this error. Thx @christian-vorhemus for solution.

My sys info:
VSCode: 1.41.1
C/C++ 0.26.3
MinGW-W64-builds-4.3.5
Windows 10: Windows 10 Pro 10.0.18363 / 18363

**Comment by Epikem** [comment]
In my case I found that short wait time in [MIEngine](https://github.com/microsoft/MIEngine) is causing timeout. If powershell terminal loading takes more than 5 seconds, connection timeouts.

**Comment by Infinite-U** [comment]
Today when I am programing in Java with VSC, I set "java.debug.settings.console":  "externalTerminal" in settings.json. But it failed to debug. So I turn it back into "integratedTerminal". According to this, I want to know if C program can also run in the integrated terminal. So I tried just as assignees does, but failed again. Later, however, I adapted @mahonelee 's opinion and succeeded. So, thank you. But I still have no idea why Java can't run in external terminal, and why C run in external terminal better. I'd appreciated it if someone could help me.

**Comment by pieandcakes** [comment]
@Infinite-U this is the page for the C/C++ extension. It sounds like you need to ask the question on the Java extension's page.

**Comment by pieandcakes** [comment]
@Epikem the change for the timeout is in the next release.

**Comment by sean-mcmanus** [comment]
Fixed in our latest Insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders.

**Comment by drNoob13** [comment]
If you prefer using git-bash in windows, you can try to install the latest version (https://git-scm.com/download/win) and vscode. Reload vscode and you can debug with the bash terminal.

**Comment by Priyanshu-21** [comment]
I am using VS Code for running my c++ program for over 1 year. But from 3-4 days when I reloaded the new version of VsCode, I face problem in debugging my C/C++ programs.

Now, I am not able to debug and run a simple hello World program.

Need Help!!!

```
#include <iostream>


using namespace std;

int main()
{
    cout<<"Hello World";
    return 0;
}
```

- But I am unable to know the output in my VS Code terminal.
- Sometimes, It is also showing This Prompt

![image](https://user-images.githubusercontent.com/56169366/113003590-7fc70680-9190-11eb-8903-1f920dfacb05.png)

Here is my launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "D:\\Program Files\\C++\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
            },
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}

```
And, Here is my task.json 
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe build active file",
			"command": "D:\\Program Files\\C++\\mingw64\\bin\\g++.exe",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: \"D:\\Program Files\\C++\\mingw64\\bin\\g++.exe\""
		}
	]
}
```
Please help me to debug my program. 😀 @pieandcakes

**Comment by LazyRaunak** [comment]
It helped me just removing and setting back environment variables.

**Comment by autieblesam** [comment]
So I had this problem and the cause ended up being a little odd.

I'm running Windows 11, MSYS2, and Git Bash.

I found the issue when trying to run gdb.exe directly at C:\msys2\mingw64\bin\gdb.exe.  The output I received was the following:
```sh
# snipped configuration information
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007efe89db8780 (most recent call first):
<no Python frame>
```

It turns out GDB wasn't able to start because of an error in my system's Python configuration caused by PYTHONPATH and PYTHONHOME being set.

I opened up my Windows environment variables and deleted these two from my system variables, then restarted.

I'm observing no issues in my python applications (and in fact am now able to configure my webserver to run Django) and my GDB debugger is now functioning properly.

**Comment by KKqdtjo** [comment]
# I solve this problem in my VS code, but I don't know why.

①turn off all VS code projects

②delete .vscode/launch.json

③delete cache:
``C:\Users\Your_UserName\AppData\Roaming\Code``

④recreate launch.json and configure it like the way you did before 

⑤press F5 and I succeed.

Maybe this can help you.
