### ISSUE TITLE
Go to Declaration doesn't work function in a Qt SIGNAL macro

### ISSUE THREAD

**Issue by monstertango** [microsoft/vscode-cpptools#2890]
It should be go to  declaration the  proper function in my classs instead of SIGNAL itself declaration .

I am using  vscode insider under Ubuntu 16.04.5 with kernel 4.12  & 64bit  Intel cpu.

**Comment by eypsum** [comment]
For example,  
connect(senderObj, SIGNAL(updated()), receiverObj, SLOT(onUpdated()));
move cursor to the signal 'updated' and press 'ctrl+F12'
then the cpp intellisense point to the *qFlagLocation(const char *method); in the qobjectdefs.h
On the other hand, It works good for the slot onUpdated .

**Comment by monstertango** [comment]
I found that it doesn't work too for slot function if  the cursor places at the definition like below
MyClass.h file
class MyClass{
public slots :    // or public Q_SLOTS
void onUpdated()
...
};

MyClass.cpp
void MyClass::onUpdated()   // move the cursor here and press ctrl+F12 then it doesn't go to declaration.
{
}

**Comment by sean-mcmanus** [comment]
What is the "public slots :" code supposed to do? That doesn't appear to be valid C++. Did you type it in wrong?

**Comment by monstertango** [comment]
the slots is just  #define with blank  so it's absolutely valid C++.

#define slots       // <- it's just empty

that is built in Qt, which is just used by Qt's MOC.
so you can see  it is valid  C++ syntax.

**Comment by sean-mcmanus** [comment]
Our symbol parser doesn't evaluate macros, so it needs to be added to a cpp.hint file: https://docs.microsoft.com/en-us/cpp/ide/hint-files?view=vs-2017 . We could add the breaking defines to our default cpp.hint files if we can identify the defines that need to be added. We currently only have have 3 QT defines handled.

**Comment by monstertango** [comment]
Okay, I understand that. Where are I place hint file with Visual studio code? In my project? 
Can I add those defines in the c_cpp_properties.json ?

I hope to be surpport built in for those of these preprocessor macros on popular SDKs like MFC, QT,GTK .
Actually Vscode-cpptool requires a lot of memory as 1GB ~ 2GB .

**Comment by sean-mcmanus** [comment]
You can add the cpp.hint in your `${workspaceFolder}` root...it doesn't work if the code is external to that. We haven't exposed adding cpp.hint defines in another way yet.

Which process is using a lot of memory? The IntelliSense processes uses a lot of memory -- we're working on fixing that. The main process shouldn't use a lot of memory.

**Comment by eypsum** [comment]
I will try it. Thanks.

Here, My VSCode's CPP IntelliSense memory status is 
![vscode-cpp--huge-memory2](https://user-images.githubusercontent.com/20113770/49582694-32a84080-f999-11e8-9467-2cbd3ed5c963.png)

**Comment by sean-mcmanus** [comment]
@eypsum Yeah that memory usage is "normal" currently, but we're working on a change that should reduce the memory usage by around 75% (e.g. 70 MB instead of 280 MB).

**Comment by eypsum** [comment]
It works pretty good with cpp.hint file. I am using VS Code Insiders.
my cpp.hint is
#define signals public
#define Q_SIGNALS public
#define slots
#define Q_SLOTS

I place only a single cpp.hint in ${workspaceFolder}.
the ${workspaceFolder} is root of  my project.
Thanks.

**Comment by HaoQChen** [comment]
> It works pretty good with cpp.hint file. I am using VS Code Insiders.
> my cpp.hint is
> #define signals public
> #define Q_SIGNALS public
> #define slots
> #define Q_SLOTS
> 
> I place only a single cpp.hint in ${workspaceFolder}.
> the ${workspaceFolder} is root of my project.
> Thanks.

It does not work for me. My Qt version is 5.10.

**Comment by bobbrow** [comment]
The original poster's issue was resolved.  If anyone is still having an issue with this, please open a new issue and we'll take a look.
