### ISSUE TITLE
CTRL+left click go to a definition then can not continue to the next definition(C++)

### ISSUE THREAD

**Issue by tonywyt12** [microsoft/vscode-cpptools#2892]
Type: Language Service

Dear MS,
After CTRL + Left click goto a definition, it switch to a source file name with all uppercase, then i can not goto the next difinition while i am in the uppercase name file. Actually the real source file is not named with all uppercase, i am not sure where the all uppercase file comes from and how could i continue to goto the next difinition with CTRL + Left click.

- OS and Version: Windows 10
- VS Code Version:1.29.1
- C/C++ Extension Version: 0.20.1

**To Reproduce**
1. ctrl + left click goto a definition(swith to the source file where the var defined, but the file name is all uppercase which the real file name is not)
2. ctrl + left click in the jumped file to goto the next definition of new var
3. can not goto the definition

**Additional context**
Have filed a issue to VSCODE: https://github.com/Microsoft/vscode/issues/64285

**Comment by sean-mcmanus** [comment]
Do you know what you are doing special to get a file with all uppercase? We internally uppercase the filenames in certain cases when they're stored in our database without case-sensitive file system enabled. Does the workspace folders you're using have the Windows case-sensitive file system enabled (https://github.com/Microsoft/vscode-cpptools/issues/1994)?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
