### ISSUE TITLE
Unable to debug a moderate project

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vscode-cpptools#2893]
Type: Debugger
```json
{
  "windows": {
      "MIMode": "gdb",
      "setupCommands": [
        { "text": "-enable-pretty-printing", "description": "enable pretty printing", "ignoreFailures": true },
        { "text": "handle SIGPIPE nostop noprint pass", "description": "ignore SIGPIPE", "ignoreFailures": true }
      ]
    },
"configurations": [
  {
      "name": "(gdb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/a.exe",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "miDebuggerPath": "C:\\cygwin64\\bin\\gdb.exe",
      "setupCommands": [
          {
              "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": true
          }
      ]
  }
]
}

```

**Describe the bug**
- OS and Version: Windows 10 1809
- VS Code Version: 1.29
- C/C++ Extension Version: Latest
- Other extensions you installed (and if the issue persists after disabling them): Persists without other extensions
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Compile with g++ main.exe
2. Start debugging
3. Debugging is dysfunctional stuck at this log
 - Meaning that debugger doesn't respect any breakpoints
 - Debugger can't run through the file
 - Nothing is happening
```
Breakpoint 1, 0x0000000100401096 in main ()
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
Single stepping until exit from function main,
which has no line number information.
```

 

I have attached the project that I couldn't debug.

[cppgdp - Copy.zip](https://github.com/Microsoft/vscode-cpptools/files/2646132/cppgdp.-.Copy.zip)

**Comment by WardenGnaw** [comment]
Are you compiling with `-g`? Can you also enable logging in your launch.json? https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging

**Comment by Astrantia** [comment]
@WardenGnaw Sorry for the rushed issue that indeed was the problem so this issue can be closed.
I ran into another problem now however. I tried debugging the same project in Visual Studio earlier and I never saw npos or _M_dataplus in the variables:
![image](https://user-images.githubusercontent.com/32885386/49475642-bfaa9880-f7e5-11e8-9246-00eb468ea697.png)


Is this how it's supposed to look? `value` is a string. Does this mean the variables in my debugger aren't pretty-printed?

**Comment by WardenGnaw** [comment]
For Cygwin, make sure you have gdb-python installed for the pretty printer to work.

**Comment by Astrantia** [comment]
@WardenGnaw Thanks again. Is there a guide on how to make the pretty printer work with Cygwin? I'm in Cygwin setup and I can't find gdb-python in it.
By gdb-python do you mean python installed from Cygwin setup? If so, does that have to take precedence over my normal python setup in Path?

**Comment by Astrantia** [comment]
@WardenGnaw I've installed gcc-debuginfo and it seems to have fixed it on Windows. 
Now I was trying to debug on Linux where I have gdb 8.2 and it is acting weird. I compiled .out with g++ -g and when I'm in the debugger variables are being shown with values that have never been assigned yet. I can't reproduce the problem on Windows. With the project that I have attached in the issue, I set breakpoint 
```cpp

int main(){
  HashMap<int, string, 10, MyKeyHash> hmap;
```
on Hashmap and I'm seeing value: '@' and result: 247. 
They haven't been declared/defined yet so how/why am I seeing them? It's fine on Windows. I couldn't find anything related to this in docs.
![image](https://user-images.githubusercontent.com/32885386/49483098-ef669a00-f7ff-11e8-9946-17bd2010409c.png)

**Comment by Astrantia** [comment]
@sean-mcmanus Do you know why gdb debugging with vscode is different in Linux? One difference that comes to mind is that Cygwin gdb is 8.0.1 while it is 8.2 on Linux, but I don't know if that's the reason
The behavior I observe on Windows is:
```
value: ""
result: 
```
on Linux:
```
value: "@"
result: 247
```
