### ISSUE TITLE
Intellisense will stop working when use std::bind incorrectly.

### ISSUE THREAD

**Issue by Frank-Shaw-FS** [microsoft/vscode-cpptools#2898]
Issue Type: <b>Bug</b>

Auto complement and error detect not work until I reload the windows, but it will soon stop working.
```
typedef std::function<void(const std::string, const std::string)> ReceiveCallBack;

class Parser  {
public:
  void Parse(const std::string & str, ReceiveCallBack cb) {
    cb(str, str);
  }
};

class UseParser {
public:
  void TP(const std::string s, const std::string b) {
    std::cout << "the s is " << s << " the b is " << b << std::endl;
  }

  void TestP() {
    Parser p;
    p.Parse("Hello", std::bind(&UseParser::TP, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3)); 
  }
};
```

The above code pass one unnecessary argument and it will trigger the bug in my PC.

Extension version: 0.20.1
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
I'm not able to repro any problem. I need to know more about what your configuration is, such as your compilerPath and what #includes you are using in the file. And what edits exactly do I need to make?

I added the code below to the top of the file. And I tried passing more arguments, but I didn't get a crash.
```
#include <functional>
#include <string>
#include <iostream>

using namespace std;
```

**Comment by Frank-Shaw-FS** [comment]
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder/include/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "msvc-x64"
        },
        {
            "name": "wsl",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/include/**",
                "/usr/local/ssl/include"
            ],
            "defines": [
                "__linux__",
                "__x86_64__"
            ],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
The above is my configuration, nothing special, and I cannot reproduce this bug now. 
![image](https://user-images.githubusercontent.com/5810166/49620489-18537e80-f9fc-11e8-8abb-7b37ea9a112c.png)
This is the error from the debug console.

**Comment by sean-mcmanus** [comment]
Yeah, we're aware of those typescript error log -- I don't think it causes any "real" bug. It should happen when edits occur "too soon".

Having `"${workspaceFolder}/include/**"` is unnecessary because `"${workspaceFolder}/**` should handle that already. Changing one of those to a non-recursive include might be what you want instead, if your goal is to disambiguate files with the same name in each folder. Also, you shouldn't need the "__linux__" defines because they should be coming from the compilerPath.

**Comment by Frank-Shaw-FS** [comment]
Well, I may come across a weired bug, it  cann't reproduce now and I do nothing for it, all works well today when I come to office.
I will try to provide more decent information next time, well, maybe no more, since I never get this bug in the past few months.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity and it does not repro according to the last comment.
