### ISSUE TITLE
Ignore Function Attributes for RTOS in Embedded C 

### ISSUE THREAD

**Issue by Zillaaa** [microsoft/vscode-cpptools#2899]
Type: General
**Input information below**

When using c/c++ within Embedded C Project, we got many Errors, when using Funtion Attributes.

void EMR_Command (void) _task_ TNR_EMRCMD _priority_ PRI_EMRCMD
{
    /*CODE*/
}
_task_ and the others are Attributes extensions for the Compiler and the RTOS Extension for the compiler. 

Syntax:
[PreAttribute1]...[PreAttribute.n] <TypOfReturn> "FunctionName" ( [<TpyOfParameter> "Name",...]) [Attribute 1] ...[Attribute.n]

**Describe the bug**
- OS and Version: Windows 7 
- VS Code Version: 1.28.2
- C/C++ Extension Version:.20.1
- A clear and concise description of what the bug is.
No Error Message like:  "expected a '{'

**Expected behavior**
Perhaps an a new Extension-Property called : Ignore?

 "configurations": [
        {
             ... 
             "ignore": [
              PreAttribute1,
              PreAttributen,
              ....
             ],
             ....
         },
         ......
]

**Comment by bobbrow** [comment]
If the attributes are simply strings, you can use the `"defines"` array to trick our parser into ignoring them:

```
    "defines": [
        "PreAttribute1=",
        "PreAttributen="
    ]
```

**Comment by sean-mcmanus** [comment]
Also, for global symbols to be parsed, you may need to add #define lines to a cpp.hint file as well (https://docs.microsoft.com/en-us/cpp/ide/hint-files?view=vs-2017).

**Comment by Zillaaa** [comment]
@bobbrow 
Your Idea works only a half. Now the first attribute is okay, but now the second has the same error!

void EMR_Command (void) _task_ **TNR_EMRCMD** priority PRI_EMRCMD

_task_ has been ignored successfully. 
Now NTR_EMRCMD has the fault: expected a '{'

@sean-mcmanus 
I will try your sollution soon.

**Comment by sean-mcmanus** [comment]
The solution I mentioned won't get rid of the "expected a '{'" message. Did you add all the attributes to the defines?

**Comment by bobbrow** [comment]
You also need to add the non-standard keywords to the `defines` array:

```
    "defines": [
        "task=",
        "TNR_EMRCMD=",
        "priority=",
        "PRI_EMRCMD="
    ]
```

Note, that this can get dangerous if you have any variables named `priority` or `task`, but if these are keywords for your extension, I would hope that the compiler wouldn't allow for that.

**Comment by Zillaaa** [comment]
My actual Source Code Line with Problem: 
`void EMR_Command (void) _task_ TNR_EMRCMD _priority_ PRI_EMRCMD`
My actual Defines:
`"defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "VS_CODE_IDE",
                "_task_=",
                "TNR_EMRCMD=",
                "_priority_=",
                "PRI_EMRCMD="
            ],`

My acutal Error Messages: 

`{
	"resource": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": null,
	"severity": 8,
	"message": "function \"EMR_Command\" may not be initialized",
	"startLineNumber": 24,
	"startColumn": 32,
	"endLineNumber": 24,
	"endColumn": 32
}`

and 
`{
	"resource": "xxxxxxxxxxxxxxxxxxxxxxx",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": null,
	"severity": 8,
	"message": "expected an expression",
	"startLineNumber": 24,
	"startColumn": 43,
	"endLineNumber": 24,
	"endColumn": 43
}`

and many times:
`{
	"resource": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": null,
	"severity": 8,
	"message": "expected a ';'",
	"startLineNumber": 51,
	"startColumn": 10,
	"endLineNumber": 51,
	"endColumn": 11
}`

**Comment by bobbrow** [comment]
I don't repro.  Is there anything else different in your configuration?  (Note: I also tried gcc-x64 `intelliSenseMode`)

![image](https://user-images.githubusercontent.com/12818240/49750625-4afdb100-fc60-11e8-9ba7-652728861b9d.png)

**Comment by Zillaaa** [comment]
myConfiguration is:
`"configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/Keil/C166/INC"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "VS_CODE_IDE",
                "_task_=",
                "TNR_EMRCMD=",
                "_priority_=",
                "PRI_EMRCMD="
            ],
            "intelliSenseMode": "msvc-x64",
            "cStandard": "c99"
        }
    ],
    "version": 4`
@bobbrow  Can you please insert some code in the function?

Here a beet example of my source code:
`
#include "globals.h"
#include "signames.h"
#include "tp.h"

void EMR_Command (void) _task_ TNR_EMRCMD _priority_ PRI_EMRCMD
{
	static ubyte c_status;
	static t_rtx_exit r_status;
	....
}
`

**Comment by bobbrow** [comment]
I have squiggles for stuff that doesn't exist, but not anything else:

![image](https://user-images.githubusercontent.com/12818240/49840502-8388b200-fd68-11e8-9693-b4a675190618.png)

**Comment by Zillaaa** [comment]
![grafik](https://user-images.githubusercontent.com/26488030/49873346-eab36e80-fe1b-11e8-903c-9850208b467e.png)

Strange....
Perhaps there is something in the Header Files?
I have many headers....

**Comment by Zillaaa** [comment]
Found....
![grafik](https://user-images.githubusercontent.com/26488030/49873471-3e25bc80-fe1c-11e8-8407-e7a4926250a3.png)

Yes, now i solve all the Problems. Thank you!
