### ISSUE TITLE
Show All symbols command is very slow

### ISSUE THREAD

**Issue by rajesh-gali** [microsoft/vscode-cpptools#29]
Searching for a symbol in very large C Project using Show All symbols command(Ctrl+t) is very very slow. Find In Files option is quicker than the show symbols command. 

System: Windows 7 and .browse.VC.db file size approximately 1.1GB .

**Comment by jgoshi** [comment]
Could you try this again with the latest release (VSCode 1.4, cpptools 0.8.1)? Has the situation improved for you?

**Comment by jgoshi** [comment]
We fixed the document symbol search so that is fast now (will appear with cpptools version 0.10.0). The workspace search (show all symbols) that you mentioned is also faster now with the latest version. If this is still a problem with the latest version please reopen this issue.
