### ISSUE TITLE
Feature request for an option to disable "Press any key" request at the end of the debuggee

### ISSUE THREAD

**Issue by xHasKx** [microsoft/vscode-cpptools#2906]
Type: Debugger

Feature request: a configuration option to disable a confirmation request "Press any key to continue..." at the end of the debuggee program.

In my setup, every debugging session is starting separate console, which I have to close manually after debugging end. That's an addition action disturbing when I'm in the deep debugging.

**Describe the bug**
- OS and Version: Manjaro Linux
- VS Code Version: Version: 1.29.1, Architecture: x64
- C/C++ Extension Version: 0.20.1: October 31, 2018

**Comment by killerkalamari** [comment]
Possible duplicate of: https://github.com/Microsoft/vscode/issues/63813

**Comment by xHasKx** [comment]
> Possible duplicate of: [Microsoft/vscode#63813](https://github.com/Microsoft/vscode/issues/63813)

Exactly.
Provided temporary solution is working, tkanks @killerkalamari
