### ISSUE TITLE
C++17 class template argument deduction not working correctly 

### ISSUE THREAD

**Issue by aryan-gupta** [microsoft/vscode-cpptools#2907]
Type: LanguageService

- OS and Version: Arch Linux with Gnome 3
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.20.1

I am having an issue where vscode is telling me I have an compile error when it compiles correctly with gcc and clang. Here is an c++ example that triggers the issue:

```c++
struct A {};

template<typename T>
struct B : public A {
	B(int p1, T p2) {  }
};

int main()
{
	A* test1 = new B{ 5, 5.0 }; // < Error

	double dtest = 5.0;
	A* test2 = new B{ 5, dtest }; // < Error

	B<double>* test3 = new B{ 5, 5.0 }; // < Error

	A* test4 = new B<double>{ 5, 5.0 }; // < Works Correctly
}
```

Intellisense is saying there is an error: `too many initializer values`. However the code compiles correctly with gcc 8.2 and clang 7. 

![screenshot from 2018-12-08 22-14-01](https://user-images.githubusercontent.com/12296130/49693051-4093c800-fb37-11e8-9d00-433514724fb8.png)

My `c_cpp_properties.json` is as follows:

```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

Does not resolve issue when using `clang-x64`.

**Comment by aryan-gupta** [comment]
A better code sample that reproduces the same error

```c++
template<typename T>
struct B {
	B(int p1, T p2) {  }
};

int main()
{
	B<int>* test1 = new B{ 5, 5 }; // < Error

	int dtest = 5.0;
	auto test2 = new B{ 5, dtest }; // < Error

	auto test3 = new B{ 5, 5 }; // < Error

	B<int>* test4 = new B<int>{ 5, 5 }; // < Works Correctly
}
```

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. The bug repros with VS 2017 as well. I've filed bug https://developercommunity.visualstudio.com/content/problem/404157/c17-intellisense-class-template-argument-deduction.html . Once that bug is fixed we should get the fix as well.

**Comment by sean-mcmanus** [comment]
Our latest [0.21.0-insiders3](https://github.com/Microsoft/vscode-cpptools/releases) has fixed the incorrect errors when template argument deduction is used.

Setting `C_Cpp.updateChannel` to `"Insiders"` is another way to get the update.
