### ISSUE TITLE
In mac, I can run the C code normally, but VSC shows program does not exist when debugging

### ISSUE THREAD

**Issue by lbfatcat** [microsoft/vscode-cpptools#2909]
Type: Debugger

**Under my mac, I wrote a simple one-line printing C program.**
`#include<stdio.h>

int main()
{
    printf("hello.\n");
    return 0;
}`

**Describe the bug**
- OS and Version: macOS Mojave
- VS Code Version:1.29.1
- C/C++ Extension Version: 0.20.1

**I can run the program but when I do debug, it just shows the *.out file does not exist!**
**Hope you guys can help me out, I am new to VSC, and find it really handy.**
![qq20181210-190615 2x](https://user-images.githubusercontent.com/39958847/49728795-b1a9bb80-fcae-11e8-8e8f-a73edb0e3507.jpg)

![qq20181210-190213 2x](https://user-images.githubusercontent.com/39958847/49728602-2e886580-fcae-11e8-9c95-f1793186fa10.jpg)

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

** the  tasks.json **
![tasks](https://user-images.githubusercontent.com/39958847/49728940-08af9080-fcaf-11e8-88ae-6c0f122b90dc.jpg)

** the launch.json **
![launch](https://user-images.githubusercontent.com/39958847/49728958-1107cb80-fcaf-11e8-9543-a68ff2f4c40c.jpg)

**Comment by bobbrow** [comment]
In `launch.json` you don't need those `args`, but you do need `"MIMode": "lldb"`.

I wasn't able to reproduce your error on my MacBook.  Can you verify that clang is actually creating `hello.out` at the location shown in the error message?  You may also want to check the Terminal window to see if there were any errors during compilation.

**Comment by lbfatcat** [comment]
> In `launch.json` you don't need those `args`, but you do need `"MIMode": "lldb"`.
> 
> I wasn't able to reproduce your error on my MacBook. Can you verify that clang is actually creating `hello.out` at the location shown in the error message? You may also want to check the Terminal window to see if there were any errors during compilation.

 **Thanks for you reply @bobbrow . I tried as you suggested, but things don't work out.** 
_first, I modify the launch.json as follows:_
![newlaunch](https://user-images.githubusercontent.com/39958847/49775440-30e0d300-fd33-11e8-9365-630c38da770e.jpg)

_second, i can successfully compile with gcc and run the program:_
![gcc_and_run](https://user-images.githubusercontent.com/39958847/49775450-3807e100-fd33-11e8-9857-e9de64242084.jpg)

***BUT, WHEN DEBUG WITH GDB, THINGS WENT WRONG***
***Is it possible that some authentication thing keep me from using gdb on my MAC ?***
![gdb_problem](https://user-images.githubusercontent.com/39958847/49775466-435b0c80-fd33-11e8-9c23-b932e47901e5.jpg)

**Comment by WardenGnaw** [comment]
The executable for GDB you want to run is `hello.out` not `hello`.

Can you also run `ls && echo $PWD`

**Comment by lbfatcat** [comment]
thanks @WardenGnaw I tried hello.out to be told ***executable format unrecognized.....***

***but after I re-installed XCode, then gcc and gdb with homebrew. things get back on track!***

perhaps the strange problem is caused by dependencies between xcode and the gnu tools.
