### ISSUE TITLE
outlining doesn't work for non-standard file extension

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-cpptools#291]
_From @amigo421 on October 17, 2016 18:11_
- VSCode Version: 1.6.1
- OS Version: Win10

Steps to Reproduce:
1.  have a files (c++ syntax but non-standard extension, c++ scripting for specific system)
2. user settings contains (probably incorrect??)

`
"files.associations" : {  "*.aaa" : "cpp"  }
`

outlining (Ctrl+Shift+O) doesn't work ("no symbols.." message), 
in case of I rename the file with usual extension: .cpp, all works okay then

_Copied from original issue: Microsoft/vscode#13899_

**Comment by roblourens** [comment]
I verified that this works as expected for TS, but not CPP. Could this extension be filtering based on file extension?

**Comment by sean-mcmanus** [comment]
Yes, the C/C++ extensions filters based on file extension. I don't really understand the bug you're reporting.

**Comment by roblourens** [comment]
Users can use the `"files.associations"` setting to register another file extension as belonging to language X. With the setting above, file.aaa will be colored as cpp, but ctrl+shift+O won't work.

**Comment by delmyers** [comment]
@roblourens, it does filter based on extensions. That is the standard way that vscode works with extensions today. You can hack the debugger to work with custom file extensions by locating the file `home/.vscode/extensions/ms-vscode.cpptools-<ver>\package.json` and updating the sections that look like this:

```
 "languageIds": [
            "cpp",
            "c",
            ".h",
            ".cc",
            ".cxx",
            ".hpp",
            ".hh",
            ".hxx"
          ]
```

to add the extension you are interested in. Unfortunately, you have to do this each time you update the extension.

@sean-mcmanus, this isn't a bug. It's a feature request or a question. Is there a way to hack the language service to recognize custom file extensions? It seems that the content of the files is c/c++ code, but the file extensions that are used are non-standard.

**Comment by sean-mcmanus** [comment]
Ah, yes, I seem to recall the "no symbols" is a known bug. Our browse engine is not correctly taking the file.associations into account and just uses a hardcoded list. The bug also repros if you manually do Change Language Mode for a file. Ctrl+Shift+O is Go To Symbols in file, not outlining/folding.

**Comment by delmyers** [comment]
@sean-mcmanus is there already a bug logged somewhere for this?

**Comment by sean-mcmanus** [comment]
I don't remember the bug number and a search didn't find it. I just remember the bug was mentioned in a previous forum discussion. Using this thread to track the bug seems fine to me.

**Comment by bobbrow** [comment]
This should be fixed in the latest version of the extension.  Please reopen if you are still having issues.

**Comment by amigo421** [comment]
This works for me, thanks!
