### ISSUE TITLE
Can not include stdafx.h -> atlbase.h

### ISSUE THREAD

**Issue by safield** [microsoft/vscode-cpptools#2910]
Windows 10
VSCode: 1.29.1
 C/C++ Extension Version: 0.20.1

No other extensions installed.

Background: the vscode-cpptools plugin is not correctly resolving default compiler defines in my cross-platform code base (separate issue).

Although, I am compiling targeting android arm, using clang, the intellisense is still trying to resolve windows headers wrapped in ifdefs.

My work around is to just include all the directories of the default include folder for msvc.

Enter my new issue....

I have foo.cpp which exists outside my workspace root, but is included in my "includePath".

In foo.cpp, the following line exists...

`#include "stdafx.h"`

with the following error...

"cannot open source file "atlbase.h" (dependency of "stdafx.h")"

If I open stdafx.h, I get the following line....

`#include <atlbase.h>`

with the error...

> cannot open source file "atlbase.h"

I have included both of the directories that these header files exist in, and the problem persists.

These two lines have been added to my "includePath" in c_cpp_properties.json

```
                "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\atlmfc\\include"
                ,"C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\atlmfc\\src\\mfc"
```

**Comment by sean-mcmanus** [comment]
We haven't tested with MSVC 11.0, only 14.0/15.0/16.0. Are those paths being used when you enable logging? The atlbase.h exists under atlmfc//include?

**Comment by safield** [comment]
atlbase.h exists under atlmfc/include. That is the only place it exists under the VC directory.

The paths listed are being logged by the plugin...

>   Processing folder (recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO 11.0/VC/ATLMFC/INCLUDE/
>   Processing folder (recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO 11.0/VC/ATLMFC/SRC/MFC/

**Comment by sean-mcmanus** [comment]
Those logs aren't from the IntelliSense process (they're for the symbol parser). If you set your loggingLevel to Debug and then open a C/C++ file you should see the includes/defines in the logs.

**Comment by safield** [comment]
When I open foo.cpp, the only things logged are...

> textDocument/codeAction
> cpptools/pauseParsing

When I open a file within the workspace root, a bunch of includes are listed, including the pertinent ones...

>   include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 11.0\VC\ATLMFC\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 11.0\VC\ATLMFC\SRC\MFC

**Comment by sean-mcmanus** [comment]
I assume that's when opening the file with the `#include <atlbase.h>`. I'm not sure what could cause include to not be found. Can you provide a self-contained repro project?

**Comment by safield** [comment]
Here is a minimal project that fails to include atlbase.h on my system
[IncludeTest.zip](https://github.com/Microsoft/vscode-cpptools/files/2665352/IncludeTest.zip)

**Comment by sean-mcmanus** [comment]
It doesn't repro for me with VS 2017, but I'll see if I can get VS 2012 and/or the Android tools.

**Comment by safield** [comment]
Turns out this is not an accurate repro case. There is just a new error causing the squiggles this time around. 

`cannot open source file "errno.h" (dependency of "atlbase.h")`

**Comment by sean-mcmanus** [comment]
For me that is found in `C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.17134.0\\ucrt`, but with VS 2012 it might be at a different location. Are you able to install a newer VS? VS 2017 is able to side-by-side install on any drive, unlike older VS versions.

**Comment by safield** [comment]
Here is a more accurate minimal repro example.

Observe the include in the file "someheader.h".
[IncludeTest.zip](https://github.com/Microsoft/vscode-cpptools/files/2668448/IncludeTest.zip)

**Comment by safield** [comment]
I have just installed VS2017. 

VS2012:

-the error for #include <atlbase.h>, in "someheader.h" said that it cannot find atlbase.h.
-the path that contains "atlbase.h" was added to the includePath...
    

> C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\atlmfc\\include

I then installed VS2017, and changed nothing for my cpptools configuration, and left VS2012 installed...

VS2017:
-the error for #include <atlbase.h>, in "someheader.h" said "cannot open source file "errno.h" (dependency of "atlbase.h")".
-it can now find and jump to definition of "atlbase.h", in the VS2017 install folder. I did NOT include this folder in my include path....

the folder that contains errno.h is added to the includePath....
    

> C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\include

Just the act of installing VS2017, changed the behaviour of the cpptools plugin.

**Comment by sean-mcmanus** [comment]
Yeah, we automatically detect the VS 2017 include path and add it if msvc-x64 mode is being used. The missing errno.h is from a missing Windows Kits. Adding the path to the errno.h should fix the issue, although if you're using a multi-root workspace you may need to update the settings for the other folder as well, unless you set the "C_Cpp.default.includePath" instead so it applies to multiple folders.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
