### ISSUE TITLE
IntelliSense support for coroutines using Clang

### ISSUE THREAD

**Issue by bartdesmet** [microsoft/vscode-cpptools#2915]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04.1 LTS
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.20.1
- Can't find a way to configure IntelliSense to support `co_await` and `co_return` with Clang.

**To Reproduce**
Given the following code:
```cpp
task<int> f(const task<int> & t) {
    int x = co_await t;
    co_return x + 1;
}
```
We get `identifier not found` errors for `co_await` and `co_return`. I've tried to configure `c_cpp_properties.json` in a variety of ways, but nothing seems to work:
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": ["COROUTINES"],
            "compilerPath": "/usr/bin/clang++-6.0 -fcoroutines-ts",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
Is there any way to configure VS Code to use Clang with `-fcoroutines-ts` supplied to fuel IntelliSense? I've tried other extensions for Clang, but haven't found a configuration that works end-to-end.

**Comment by sean-mcmanus** [comment]
Okay, we might be able to turn this on in a future update. If you edit msvc.json at ~/.vscode/extensions/ms-vscode.cpptools-0.20.1/bin by changing "cpfe" to
```
      "cpfe",
      "--set_flag",
      "coroutines",
```
Does that work for you or are there additional issues? I don't know how to get the "task" class to be usable.

**Comment by bartdesmet** [comment]
I did edit `msvc.json` as described and reloaded VS Code, but the error remains the same. The `task<T>` type I have does support `co_await` and `co_return` just fine (command-line build using clang is passing). The error remains that IntelliSense considers both keywords to be undeclared identifiers.

**Comment by sean-mcmanus** [comment]
Where does Go to Definition take you with task<int>? I don't know how to get that class to be recognized. Do you have a #include line? What is the error message for the co_await? Does it say "this co_aware expression requires a suitable "await_ready"? If it's not recognizing the co_await keyword, it sounds like it's not picking up the modifications to msvc.json.

**Comment by bartdesmet** [comment]
`task` is my own type. It has everything needed to work properly with coroutines, including the three `await_*` methods, a promise type, etc. The code compiles fine using clang++-6.0 at the command line. Only VS Code remains unenlightened about the language feature.

How does IntelliSense get powered? For compilation to support coroutines, I need `/await` for MSVC cl.exe and `-fcoroutine-ts` for clang. I assume the compiler front-end uses for IntelliSense needs similar flags.

**Comment by sean-mcmanus** [comment]
We don't currently look at /await or -fcoroutine-ts in the compilerPath args, but we could later on. --set_flag coroutine in the msvc.json is "supposed" to enable this, so I'm not sure why it's not working for you. It's working for me on Linux with gcc8 and clang 3.9.

**Comment by sean-mcmanus** [comment]
If you're getting the "identifier "co_await" is undefined" then you must be modifying the incorrect msvc.json file. There are 4 potential locations for the file, e.g. VS Code non-insiders/insiders and our 0.20.1 and 0.21.0-insiders, so maybe you modified the wrong one?

**Comment by oxycoder** [comment]
msvc.json look like below:
~/.vscode/extensions/ms-vscode.cpptools-0.24.0/bin/msvc.json
```
  {
    "defaults": [
      "cpfe", 
      "--set_flag",
      "coroutines",
      "--wchar_t_keyword",
      "--no_warnings",
      "--rtti",
      "--edge",
      "--exceptions",
      "--error_limit",
      "25000",
      "-D_EDG_COMPILER",
      "-D_USE_DECLSPECS_FOR_SAL=1"
    ],
    "source_file_format": "-f %s",
    "expressions": [
      {
        "match": "^/I(.*)",
        "replace": "-I\n$1"
      },
      {
        "match": "^/D(.*)",
        "replace": "-D$1"
      },
      {
        "match": "^/AI(.*)",
        "replace": "--using_directory\n$1"
      },
      {
        "match": "^/dE--header_only_fallback",
        "replace": "--header_only_fallback"
      }
    ]
  }

```

but intellisense still show error with co_wait, ... 

VS code 1.38 (not insider)

**Comment by bobbrow** [comment]
With C++20 IntelliSense mode, there should no longer be squiggles for `co_await` and `co_return`.
