### ISSUE TITLE
Mac Frameworks issue with GStreamer

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#2917]
_Originally posted by @lummish in https://github.com/Microsoft/vscode-cpptools/issues/770#issuecomment-446024904_

@sean-mcmanus I'm having a similar issue with a different library (gstreamer). You can find my c_cpp_properties.json below:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}",
                "/usr/local/cuda",
                "/usr/local/include",
                "/Library/Frameworks/GStreamer.framework/Headers",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
            ],
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "/usr/local/cuda",
                    "/usr/local/include",
                    "/Library/Frameworks/GStreamer.framework/Headers",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include",
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks",
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include",
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "defines": [],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks",
                "/System/Library/Frameworks/ApplicationServices.framework/Frameworks",
                "/System/Library/Frameworks/CoreServices.framework/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}
```
I've included all the paths that appear in the output of `clang -Wp,-v -E -xc -x c++ /dev/null`, shown below. Note: I have already verified that `clang` is symlinked to /usr/bin/clang

```
clang -cc1 version 10.0.0 (clang-1000.11.45.5) default target x86_64-apple-darwin18.2.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 373 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2
```
I saw in the [GStreamer documentation](https://gstreamer.freedesktop.org/documentation/installing/on-mac-osx.html) that this particular library requires that certain steps be taken to prepare your development environment: 

```
XCode: Add the headers path to Search Paths → Header Search Paths
GCC: Using the compiler option -I/Library/Frameworks/GStreamer.framework/Headers
```

However you'll notice that I've included /Library/Frameworks/GStreamer.framework/Headers in my include path. I'm pretty much at a loss as to how to fix the issue from this point. I've tried adding the framework headers directory to the `macFrameworkPath` variable however I have not had any success. Any ideas?

**Comment by bobbrow** [comment]
I see that you are using the CMake Tools extension to provide the `includePath` (see `"configurationProvider": "vector-of-bool.cmake-tools"), so the values you set here won't be used unless the CMake Tools extension fails to provide the configuration for your source files.

Though I'm still surprised this isn't working since you don't need to do anything special to get IntelliSense to work for this framework because it was installed to the `/Library/Frameworks` folder.  I installed this framework and was able to get IntelliSense working.

**NOTE:** I had to set up the `Headers` symlink manually for some reason after installing version 1.14.4, maybe that's it?  Do you have a symlink called "Headers" in the `/Library/Frameworks/GStreamer.framework` folder?

![image](https://user-images.githubusercontent.com/12818240/49887815-29343380-fdf2-11e8-808c-322ed349865a.png)

BTW, you should be able to simplify your configuration to this:
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}",
                "/usr/local/cuda",
                "/usr/local/include"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}

**Comment by lummish** [comment]
@bobbrow I do actually have the Headers symlink working. I simplified my configuration as you recommended and after restarting VSCode it looks like fuzzy Intellisense is making smart suggestions for the gstreamer library include path:

![screen shot 2018-12-12 at 10 19 59 am](https://user-images.githubusercontent.com/8981664/49889884-8383c300-fdf7-11e8-94d9-c958f0974dc9.png)

So I suppose an explicit include path is required, but at least Intellisense is finding it!

**Comment by bobbrow** [comment]
Oh.  That's odd.  It seems that GStreamer isn't following standard Framework conventions.  Now I understand why the docs say to add a `-I` to consume the headers.  Normally you would do something like:
```
#include <GStreamer/gst/gst.h>
```

**Comment by anselmobattisti** [comment]
In my case i needed to install de devel version

https://gstreamer.freedesktop.org/data/pkg/windows/1.16.0/

that came with headers in folder C:\gstreamer\1.0\x86\include\gstreamer-1.0

After thar i add the path in my configuration 

    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\/gstreamer\/1.0\/x86\/include\/gstreamer-1.0"
            ],
