### ISSUE TITLE
Can't attach remote linux program on windows again

### ISSUE THREAD

**Issue by aengusjiang** [microsoft/vscode-cpptools#2920]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows 10 1809
- VS Code Version:1.29 , 1.30
- C/C++ Extension Version:0.20.1
- remote Os: Ubuntu 16.04

Issue:
[test.zip](https://github.com/Microsoft/vscode-cpptools/files/2674302/test.zip)

Attach a linux remote c++ program, it show the error log below.
![image](https://user-images.githubusercontent.com/22406984/49911607-f9546100-fec1-11e8-889b-d6cade187cdc.png)

**Comment by aengusjiang** [comment]
Any progress about this issue?

**Comment by aengusjiang** [comment]
When I go back to version 0.19.1, it works.

**Comment by aengusjiang** [comment]
The C/C++ Extension Version:0.21 still have this issue.

**Comment by WardenGnaw** [comment]
Sorry for the delay, this will be fixed in the next release. 

Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/3150
