### ISSUE TITLE
miDebuggerPath invalid

### ISSUE THREAD

**Issue by theOne-Phil** [microsoft/vscode-cpptools#2925]
I am unable to find out, why miDebuggerPath is invalid.

#### Setup:
OS: Windows 10
I am coding in C
C/C++ Extension by Microsoft is installed
MinGW installed

#### Issue:
![image](https://user-images.githubusercontent.com/45015159/49958055-fbdaa900-ff09-11e8-9ccc-a6754dbe6e97.png)

#### my launch.json
![image](https://user-images.githubusercontent.com/45015159/49958322-b8346f00-ff0a-11e8-86d5-b138243ace48.png)

#### location of gdb.exe
![image](https://user-images.githubusercontent.com/45015159/49958358-e4e88680-ff0a-11e8-82bc-1a6579b47bcf.png)

So with all these working together I have no clue why it is unable to find the gdb.exe
Any help appreciated! 
Thanks ~Phil

**Comment by WardenGnaw** [comment]
Can you get the [engine logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) and paste it here?

**Comment by theOne-Phil** [comment]
1: (85) LaunchOptions WorkingDirectory='C:\QS_SurfacePro\FHS\SWE' 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (85) LaunchOptions ExeArguments=''\r\n"},"seq":8,"type":"event"} 
1: (85) LaunchOptions ExeArguments='' 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (85) LaunchOptions MIMode='gdb'\r\n"},"seq":10,"type":"event"} 
1: (85) LaunchOptions MIMode='gdb' 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (85) LaunchOptions MIDebuggerPath='‪‪‪C:\\MinGW\\bin\\gdb.exe'\r\n"},"seq":12,"type":"event"} 
1: (85) LaunchOptions MIDebuggerPath='‪‪‪C:\MinGW\bin\gdb.exe' 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (85) LaunchOptions WaitDynamicLibLoad='false'\r\n"},"seq":14,"type":"event"} 
1: (85) LaunchOptions WaitDynamicLibLoad='false' 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (86) LaunchOptions ExternalConsole='true'\r\n"},"seq":16,"type":"event"} 
1: (86) LaunchOptions ExternalConsole='true' 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (86) LaunchOptions>\r\n"},"seq":18,"type":"event"} 
1: (86) LaunchOptions> 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (86) LaunchOptions <SetupCommands>\r\n"},"seq":20,"type":"event"} 
1: (86) LaunchOptions <SetupCommands> 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (86) LaunchOptions <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>\r\n"},"seq":22,"type":"event"} 
1: (86) LaunchOptions <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command> 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (87) LaunchOptions </SetupCommands>\r\n"},"seq":24,"type":"event"} 
1: (87) LaunchOptions </SetupCommands> 
--> E (output): {"event":"output","body":{"category":"console","output":"1: (87) LaunchOptions</LocalLaunchOptions>\r\n"},"seq":26,"type":"event"} 
1: (87) LaunchOptions</LocalLaunchOptions> 
--> E (output): {"event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.51030.1","VS.Diagnostics.Debugger.HostVersion":"14.0.51030.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.ErrorCode":1005,"VS.Diagnostics.Debugger.Launch.IsError":true}},"seq":28,"type":"event"} 
--> R (launch-2): {"request_seq":2,"success":false,"command":"launch","message":"Unable to start debugging. The value of miDebuggerPath is invalid","body":{"error":{"id":1005,"format":"Unable to start debugging. The value of miDebuggerPath is invalid"}},"seq":30,"type":"response"}

**Comment by WardenGnaw** [comment]
I'm quite stumped, too. The error message `The value of miDebuggerPath is invalid` only appears if that file does not exist. 

Can you try running `C:\MinGW\bin\gdb.exe --interpreter=mi` in a command prompt and see if that works?

**Comment by theOne-Phil** [comment]
![image](https://user-images.githubusercontent.com/45015159/50212180-ae7f9100-037a-11e9-9c05-03a778af62d1.png)

**Comment by theOne-Phil** [comment]
I have tried to setup Visual Code with MinGW the same way on my computer, and got the same results.
The walktrhorugh is:

- install MinGW
  - mingw32-base-bin
  - mingw32-gcc-g++-bin
  - adding mingw to PATH
- install Visual Code
- setup tasks in Visual Code (gcc -g FILE -o FILE.exe)
  - "command": "gcc",
  - "args": ["-g", "${file}", "-o", "${workspaceRoot}\\${fileBasename}.exe"]
- install ms-vscode.cpptools
- setup launch
  - path to gdb.exe
  - add "compile task" as pretask

**Comment by WardenGnaw** [comment]
Sadly I still can't repro the issue with your provided steps. Can you copy the launch.json file you were using here?

**Comment by theOne-Phil** [comment]
launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}\\${fileBasename}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "‪C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "Build",
        }
    ]
}
```

**Comment by theOne-Phil** [comment]
task.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "type": "shell",
            "command": "gcc",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${workspaceRoot}\\${fileBasename}.exe"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
        },
        {
            "label": "RunCFile",
            "type": "shell",
            "command": ".\\${fileBasename}.exe",
            "group": {
                "kind": "test",
                "isDefault": true
            }
        }
    ]
}
````

**Comment by theOne-Phil** [comment]
Maybe dump MinGW for something else?

**Comment by WardenGnaw** [comment]
I just copied your launch.json, and I also got the same failure.

There is no visible difference between the two strings so I wrote a simple program to see whats going on. 

![image](https://user-images.githubusercontent.com/3953714/50262563-c7159880-03c6-11e9-85f9-0c7c33816739.png)

Your string printed out character by character is:
```
"miDebuggerPath": "?C:\\MinGW\\bin\\gdb.exe",
34 109 105 68 101 98 117 103 103 101 114 80 97 116 104 34 58 32 34 8234 67 58 92 92 77 105 110 71 87 92 92 98 105 110 92 92 103 100 98 46 101 120 101 34 44
```

When the expected is:
```
"miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
34 109 105 68 101 98 117 103 103 101 114 80 97 116 104 34 58 32 34 67 58 92 92 77 105 110 71 87 92 92 98 105 110 92 92 103 100 98 46 101 120 101 34 44
```

Theres a weird 8234 character in your string, which printing it rendered it as '?'.

Try replacing this string below with your current one:
"miDebuggerPath": "C:\\\\MinGW\\\\bin\\\\gdb.exe"

**Comment by theOne-Phil** [comment]
I copied your string, and get a Syntax-Error:
![image](https://user-images.githubusercontent.com/45015159/50263092-7c227200-0414-11e9-8c51-920294e0e4eb.png)

But after adding '\\' it works!! :D i am so happy right now!
![image](https://user-images.githubusercontent.com/45015159/50263142-a7a55c80-0414-11e9-8090-8208e31bbf38.png)

THANK YOU! ❤️ 
I will look into this char element, since I edited the launch.json manually on PC and on my Surface...

**Comment by reservoirinvest** [comment]
> I just copied your launch.json, and I also got the same failure.
> 
> There is no visible difference between the two strings so I wrote a simple program to see whats going on.
> 
> ![image](https://user-images.githubusercontent.com/3953714/50262563-c7159880-03c6-11e9-85f9-0c7c33816739.png)
> 
> Your string printed out character by character is:
> 
> ```
> "miDebuggerPath": "?C:\\MinGW\\bin\\gdb.exe",
> 34 109 105 68 101 98 117 103 103 101 114 80 97 116 104 34 58 32 34 8234 67 58 92 92 77 105 110 71 87 92 92 98 105 110 92 92 103 100 98 46 101 120 101 34 44
> ```
> 
> When the expected is:
> 
> ```
> "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
> 34 109 105 68 101 98 117 103 103 101 114 80 97 116 104 34 58 32 34 67 58 92 92 77 105 110 71 87 92 92 98 105 110 92 92 103 100 98 46 101 120 101 34 44
> ```
> 
> Theres a weird 8234 character in your string, which printing it rendered it as '?'.
> 
> Try replacing this string below with your current one:
> "miDebuggerPath": "C:\MinGW\bin\gdb.exe"

I had the exact same problem and was struggling. It really is wierd. 

Looks like manually editing file in JSON in vs code introduces extra invisible characters. This would be a question to developers?

**Comment by lvZic** [comment]
thank god!
 in my opinion, it may be somthiing about ANSI coding

**Comment by gtsompanoglou** [comment]
"miDebuggerPath":"C:\\TDM-GCC-64\\bin\\gdb.exe" 

This saved my day (: . If you are reading this you should definately try it.

**Comment by dvogureckiy99** [comment]
@gtsompanoglou [gtsompanoglou](https://github.com/gtsompanoglou) 
Where is situated TDM-GCC-64\bin\gdb.exe execpt you example ?

**Comment by nested-slk** [comment]
![image](https://user-images.githubusercontent.com/61833299/181706609-8253e8a5-7a8e-4d8c-ac66-a336bdf7389c.png)
Check the End of line setting

**Comment by TTFH** [comment]
If you're using **Makefile Tools**, edit the `settings.json` (NOT `launch.json`) and make sure the paths starts with a lowercase 'c'.

```{
	"makefile.launchConfigurations": [
		{
			"cwd": "path to folder with exe",
			"binaryPath": "path to exe",
			"binaryArgs": [],
			"MIMode": "gdb",
			"miDebuggerPath": "c:\\msys64\\usr\\bin\\gdb.exe"
		}
	]
}```

**Comment by KhaledT5** [comment]
The solution that worked for me was that either you delete this line "C:\\MinGW\\bin\\gdb.exe",
except gdb and the quotations, or the problem might be that minGW is downloaded within another folder in C drive. I don't know how it happened with me but i found that minGW was inside a folder named mingw.

**Comment by ludanik** [comment]
> If you're using **Makefile Tools**, edit the `settings.json` (NOT `launch.json`) and make sure the paths starts with a lowercase 'c'.
> 
> ```
> 	"makefile.launchConfigurations": [
> 		{
> 			"cwd": "path to folder with exe",
> 			"binaryPath": "path to exe",
> 			"binaryArgs": [],
> 			"MIMode": "gdb",
> 			"miDebuggerPath": "c:\\msys64\\usr\\bin\\gdb.exe"
> 		}
> 	]
> }
> ```

You saved me! Thank you!
