### ISSUE TITLE
Debugger Not Working Properly on Linux

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vscode-cpptools#2928]
Type: Debugger
**Input information below**
Debugger runs ahead the current breakpoint and displays values not yet initialized.

**Describe the bug**
```cpp
#include "HashMap.h"
#include <assert.h>
#include <iostream>
#include <string>

using namespace std;

struct MyKeyHash {
  unsigned long operator()(const int &k) const { return k % 10; }
};

int main(){
  HashMap<int, string, 10, MyKeyHash> hmap;
  hmap.put(1, "1");
  hmap.put(2, "2");
  hmap.put(3, "3");

  string value;
  bool result = hmap.get(2, value);
  cout << value;

  result = hmap.get(3, value);
  cout << value;

  hmap.remove(3);
  result = hmap.get(3, value);
  return 0;
}
```
If I set a breakpoint on HashMap<int, string, 10, MyKeyHash> hmap; I can see `result and value` with some values that I should not be seeing. (I'm not seeing it on Windows at least):
![image](https://user-images.githubusercontent.com/32885386/49993418-952ead00-ff54-11e8-8e5e-3250ef07e3e6.png)
This picture is still at line 
```cpp
int main(){
  HashMap<int, string, 10, MyKeyHash> hmap;
```

- OS and Version: Linux 
- VS Code Version: 1.29
- C/C++ Extension Version: Latest
- Other extensions you installed (and if the issue persists after disabling them): Persists after disabling
- A clear and concise description of what the bug is.
GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
gcc version 8.2.1 20180831 (GCC) 

Im compiling with `-g` on both Linux and Windows 
**Additional context**
Using cygwin on windows and vscode, the debugger works as expected. I don't know why I'm observing this behavior on linux.

Here's the project 

[cppgdp - Copy.zip](https://github.com/Microsoft/vscode-cpptools/files/2646132/cppgdp.-.Copy.zip)

**Comment by Astrantia** [comment]
@WardenGnaw @pieandcakes am I not providing enough details for this to be answered ?

**Comment by WardenGnaw** [comment]
The variables are declared and when we stop at the breakpoint, those variables (`value` and `result`) have not been set to any value yet. The value it will contain is whatever is currently at the variable's memory address. 

https://stackoverflow.com/questions/30172416/uninitialized-variable-behaviour-in-c
