### ISSUE TITLE
IntelliSense and WSL not working

### ISSUE THREAD

**Issue by Gliptal** [microsoft/vscode-cpptools#2934]
**Type: LanguageService**

- Windows 10 Pro 1809 (17763.194)
- VS Code 1.30.0
- C/C++ Extension 0.20.1
- IntelliSense not working with WSL.

**To Reproduce**
1. Install Windows 10 Pro
2. Install VS Code
3. Install WSL
4. Note IntelliSense is not using WSL include paths

**Expected behavior**
As per [the docs](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md), this should allow IntelliSense to pick up wsl and its appropriate include paths:

```
{
    "configurations": [
        {
            "name": "WSL",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}"
            ],
            "defines": [
                "DEBUG_LEVEL=DEBUG_INFO"
            ],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4    
}
```

**Additional context**
Result of `wslconfig.exe /l`:
```
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
Ubuntu
```

Specifying the full Windows Path to WSL includes returns this error in the console:
```
Unable to retrieve file system information for C:/Users/MattiaAffabris/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/**. error = -1
Unable to retrieve file system information for C:/Users/MattiaAffabris/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/7/**. error = -1
```
I'm migrating the project from my personal PC to my office PC, with the only macro difference I can think of being the former is on WIndows 10 Home 1803. The configuration works fine on my home PC with the full Windows paths specified in the configuration file _and_ with only the `compilerPath` specified.

**Comment by sean-mcmanus** [comment]
The `"**"` at the end of the includePath should not be there. We never add a "*" to paths so I don't see how this is possible, and I don't know how to repro that issue and everything seems identical to me with your setup. Could you enable [debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and see if there are any other messages before hand? You could try removing the path with the "**". Does the error lead to an actual bug? It's possible the code is just checking for potentially valid paths. You could try our Insider build to see if it's fixed there: https://github.com/Microsoft/vscode-cpptools/releases .

**Comment by Gliptal** [comment]
The `"**"` at the end of the file path is for recursion, and is documented in the official example in the link I provided. Also, [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md#includepath). 

I have a hunch this might be an issue with the way WSL was installed in my system, But I won't be able to check until tomorrow.

**Comment by sean-mcmanus** [comment]
The `"**"` should not be used with system paths, because recursive incluedes are non-deterministically ordered. For the workspaceFolder it is normally fine. I don't know how the "**" is appearing at the end of "/usr/include/c++". Yeah, it could be something unusual with your system, because we haven't see any reports like this before.

**Comment by Gliptal** [comment]
I'll report back tomorrow, thanks in the meantime.

**Comment by Gliptal** [comment]
Indeed, on my system WSL installed both an `Ubuntu` and an `Ubuntu-18.04`, with the latter set as `default`. Turns out the `Ubuntu-18.04` entry was a dummy of sorts, and I only actually had `Ubuntu` on the system: after setting that as `default` and unregistering the dummy `Ubuntu-18.04` (with `wslconfig.exe`) the extension started working again.

**Comment by bobbrow** [comment]
It sounds like this issue is resolved. Closing it.
