### ISSUE TITLE
Blank lines in doc comments are not preserved

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#2937]
With 0.21.0-insiders2:

// Doc one.
// 
// Doc two.
int var;

The empty new line is not preserved for doc comments in hover/signatureHelp/completion. Not sure how important this is. We intentionally remove normal newlines without a blank line because VS Code has its own line wrapping, but this case should still work.

**Comment by JalonWong** [comment]
All comments are in one line.

![image](https://user-images.githubusercontent.com/5309088/52024708-c0894d80-253c-11e9-8e9f-8a4da44abe23.png)


I think this is better.
![image](https://user-images.githubusercontent.com/5309088/52025047-f418a780-253d-11e9-8810-eda59ff4ae95.png)

**Comment by sean-mcmanus** [comment]
Yeah, we're not yet sure how to fix this, because VS Code doesn't give us an API to check/suppress the newlines that they add themselves, which prevents us from doing accurate line wrapping.

One idea is that we can add the newlines when the end of the previous line or the start of the current line ends in a punctuation, which would fix the 1 word on a line problem:
```
this is a long comment............one
two
three ..... more long comment then
four
five … etc.
```

**Comment by arminAnderson** [comment]
Having that new line character, at least when you have this: 

`//A`             
`// `   
`//B`             

would be really helpful. Forcing everything into one long wrapping line makes the doc hover look bad in almost every situation. I'm not sure how hard it is to make `// ` cause a new line in the hover tooltip, plus the other situations a newline should be in, but the intention of anyone who just does `//` followed by a space only is really obvious and imo should be prioritized first

**Comment by sean-mcmanus** [comment]
0.23.0-insiders has enabled newlines in doc comments.
