### ISSUE TITLE
Cannot find header files defined in compile_command that is not in the project directory

### ISSUE THREAD

**Issue by dmitrii1971** [microsoft/vscode-cpptools#2940]
Header files that are not in the project directory cannot be opened. 

I think this is a must have case since, e.g. `jni.h` used in Java for native methods is in the directory `$JAVA_HOME/include` and it's not possible to navigate to it by placing "Go to definition".

- VSCode Version: 1.28.0
- OS Version: Linux Ubuntu 18.04
- VSCode-cpptools Version: 0.20.1

Steps to Reproduce:

1. Create a new vscode project in some directory
2. Create a header file in another directory that is not a parent of the project directory.
3. Generate compile_command.json to have the header file at **2.** included
4. Write a source file in the project including the header file defined at **2.**
5. Try to navigate to the file by pressing "Go to definition" on the header file
6. See the message "No definition found for xxx.h"

c_cpp_properties:
```
{
    "configurations": [
        {
            "name": "Linux",
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "compileCommands": "${workspaceFolder}/compile_commands.json",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

Screenshot:
![screenshot from 2018-12-18 09-20-18](https://user-images.githubusercontent.com/45256052/50136225-25982500-02a8-11e9-94fa-ffe6643b3803.png)
![screenshot from 2018-12-18 09-23-56](https://user-images.githubusercontent.com/45256052/50136227-2761e880-02a8-11e9-8b00-4f184a2264ed.png)
![screenshot from 2018-12-18 09-26-39](https://user-images.githubusercontent.com/45256052/50136229-292bac00-02a8-11e9-908f-5e82bdbed78e.png)
![screenshot from 2018-12-18 09-39-43](https://user-images.githubusercontent.com/45256052/50136511-1fef0f00-02a9-11e9-9176-c2f07cd7da48.png)

**Comment by sean-mcmanus** [comment]
You need to add the external folders to your c_cpp_properties.json `"browse": { "path": "..." }` setting or C_Cpp.default.browse.path (see https://github.com/Microsoft/vscode-cpptools/issues/1163 ). It's "by design" currently, but we've been wanting to auto-create that setting from the compile_commands.json for a while.

**Comment by bobbrow** [comment]
Please upvote issue #1163.  It helps us track priorities for extension work.  I will be closing this duplicate.
