### ISSUE TITLE
Autocomplete does not display variables declared in the for loop In C file

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#2946]
**Type: LanguageService**
```c
int main(void) {
    for (int test = 0; test < 10; test++) {
        tes // Autocomplete does not list 'test'. 
    }
}
```

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. I've filed a bug with VS at https://developercommunity.visualstudio.com/content/problem/413562/cc-intellisense-autocomplete-does-not-display-vari.html , so you could upvote that issue if you want.

UPDATE: Their response was "We are currently prioritizing problems that are impacting a broad set of our customers,", so I'd recommend everything hitting this to click the "upvote" button at the "developercommunity" website in the link above.

**Comment by teodorrd27** [comment]
Any updates on this? It's been a couple of years.

**Comment by sean-mcmanus** [comment]
No update -- only 3 votes at https://developercommunity.visualstudio.com/content/problem/413562/cc-intellisense-autocomplete-does-not-display-vari.html

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 .
