### ISSUE TITLE
variable mangling not work in c_cpp_properties.jason

### ISSUE THREAD

**Issue by ihakh** [microsoft/vscode-cpptools#2948]
this statement is not working
what should I do?
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "${SOME_ENVIRONMENT_VARIABLE%%/lib*}/include"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
I want to add the include folder from lib folder location

**Comment by YassinMahmoudEl-Zouhery** [comment]
why whats the problem

**Comment by sean-mcmanus** [comment]
What is the "%%/lib*" syntax supposed to mean? I don't think we support that.

**Comment by ihakh** [comment]
please read this:
https://www.linuxjournal.com/article/8919
a environment variable may contain multiple value or a long address.
I want to create a config file which would work on every device by reading a installation path from environment variable.
this works on Makefile but it seems it's not working on VSCODE config file
I am a newbie in VSCODE is there a way to achieve my goal?

**Comment by sean-mcmanus** [comment]
We don't support those makefile operators currently, but you could use "${SOME_ENVIRONMENT_VARIABLE}/../include" instead.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity.
