### ISSUE TITLE
Intellisense not resolving library name

### ISSUE THREAD

**Issue by chrisjsewell** [microsoft/vscode-cpptools#2951]
**Type: LanguageService**

**Describe the bug**
- OS and Version: OSX 10.10.5
- VS Code Version: 1.30.0
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.

I want to inspect the code in this repo: https://github.com/idaholab/moose
Creating a workspace with the default `c_cpp_properties.json` mostly works, however the following include fails (`cannot open source file "libmesh/utility.h"`):

```c
#include "libmesh/utility.h"
```

The `libmesh` library is located within the repo (`${workspaceFolder}/libmesh`) and, if I remove the library name prefix, it is found by Intellisense, i.e.

```c
#include "utility.h"
```

Is there a simple way to alter the `c_cpp_properties.json`  so that these includes are resolved?

My current `c_cpp_properties.json`  is:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
My guess is that the libmesh files are being added to the "never found" list. Does doing a "Reset IntelliSense Database" or opening the files fix the issue?

How do I get the libmesh library?

Another issue I noticed is that the ".C" files are incorrectly being treated as "C" instead of C++ files, due VS Code's files.association not being case sensitive, which is a known issue: https://github.com/Microsoft/vscode-cpptools/issues/2558 , https://github.com/Microsoft/vscode/issues/59369

**Comment by chrisjsewell** [comment]
Sorry for the late reply, but no, resetting or opening the files does not fix the issue.

A fixed version of the libmesh library is located internally in the main [repository](https://github.com/idaholab/moose) (if you click on the link hopefully you will see what I mean)

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
