### ISSUE TITLE
relative includePath woes

### ISSUE THREAD

**Issue by dfarley1** [microsoft/vscode-cpptools#2954]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 (latest stable)
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): none enabled
- A clear and concise description of what the bug is.

Intellisense cannot resolve project headers included in includePath when multiple modules have the same name.

**To Reproduce**

Here's my project hierarchy:
```
mgmt (${workspaceFolder})
    common
      inc
        common_header.h
      src
        common_source.cpp
    module1
      inc
        module_header.h
      src
        module_source.cpp
    module2
      inc
        module_header.h
      src
        module_source.cpp
    module3
      ...
    moduleN
      ...
```

I have several separate modules where the class and file names in them are the same ( I know, I know...).  These modules compile separately and do not reference each other, but they all reference the "common" code.

I'm getting a ton of "cannot open source file 'module_header.h'" errors and I can't figure out how to format my includePath to pick everything up correctly.  Blindly using "${workspaceFolder}\\**" doesn't work; IntelliSense thinks every moduleN's source file includes module1's header file since that's the first one found.

How do I format includePath to only pick up headers relative to the current file (../inc/module_header.h)  and the common headers (can be absolute).  I've tried the following c_cpp_properties.json with no success:
```
{
    "configurations": [
        {
            "name": "Win32",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${fileDirname}/../inc/",
                "${fileDirname}\\..\\inc\\",
                "${workspaceFolder}/mgmt/app-sw/embed/common/service/inc/",
                "${workspaceFolder}\\mgmt\\app-sw\\embed\\common\\service\\inc\\"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "__SIZE_TYPE__=unsigned int"
            ],
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

Side question: Do I use `/` or `\\` for paths on Windows?

**Comment by sean-mcmanus** [comment]
Are you using cmake to build? If so, you should be able to use compile_commands.json to set the per-source file include paths.

You can use / or \\ for paths on Windows.

If you're using gcc, you'll probably want to set the compilerPath for the system includes/defines (and not set `__SIZE_TYPE__` yourself, because you're probably missing other defines).

You can create a multi-root workspace, i.e. each module folder can be a root folder with it's own includePath in c_cpp_properties.json. Does that work for you?

We had another earlier request for some sort of relative includePath mechanism.

We might be able to improve the recursive include code to use the "closest" path (not sure if that would cause a performance issue though).

**Comment by dfarley1** [comment]
I'm using g++ to compile, but it's on a remote Linux server that doesn't support X11 yet.  I'm using VSCode and ftp-sync on my Windows machine so I can edit in VSCode at least (the rest of my team seems content with vim).
That's the reason for my defined __SIZE_TYPE__ as well, I've installed g++ on my local WSL so I at least get the stdlib headers but for some reason Intellisense claims its ambiguous.

I'm not sure what a multi-root workspace entails, but I don't have to worry about compilers so I suppose why not?  I'd like to keep everything in one "view" if possible since I'm often working across modules at the same time.

**Comment by sean-mcmanus** [comment]
For multi-root, just open one of the module folders, and then do File->Add Folder to Workspace -- it looks like you can select all the other modules/folders at once to add. For multi-root we run a different language server process for every root folder though and they don't communicate with each other, so you might encounter some "issues".

You'll probably want to set the workspace's C_Cpp.default.includePath to some shared value like "${workspaceFolder}/inc", although the default "${workspaceFolder}/**" might also work.

**Comment by dfarley1** [comment]
That doesn't seem to have worked.  I added `mgmt/module4/` to the workspace, but I'm still getting complaints that `mgmt/module4/inc/` headers can't be found.  

I copied the same c_cpp_properties.json file to `mgmt/module4/.vscode/` except I changed the includePath to:
```
{
    "configurations": [
        {
            "name": "Win32",
            "compilerPath": "/usr/bin/g++",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}/inc/",
                "${workspaceFolder}/**",
                "${workspaceFolder}/../common/inc/"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

I ran an "echo ${workspaceFolder}" task from the source file in module4 and it looks OK there.  Even with `/**` it's not picking up `mgmt/module4/inc/`, it picks up the common header just fine though.
I restarted VSCode and reset both folders' IntelliSense databases as well.  Is there any way to turn on some debugging for this?

**Comment by sean-mcmanus** [comment]
You can [enable Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) to see what paths get used. The "sending compilation args" ones are for IntelliSense.

What are your workspace folders? module4, module1, and common? What does your #include loook like and what file is it in? Are you trying to access the inc folder in the same workspace as the source or a different one?

**Comment by dfarley1** [comment]
I have the top level `mgmt` and `module4` as workspace folders, just to test.  Within module4 I have the following tree and my c_cpp_properties.json is above.  
```
mgmt/module4
    inc
        module4.h
        interface.h
    src
        module4.cpp
        interface.cpp
```

So from `module4/interface.cpp`,  `${workspaceFolder} == ".../mgmt/module4"`.  Thus the first line in includePath should be `.../mgmt/module4/inc/`, right?

Here are my includes.  Setting up the include paths for actual compilation is done within a Makefile for each daemon.
```
mgmt/module4/interface.cpp:

#include "interface.h"
#include "module4.h"
```
```
mgmt/module4/module4.cpp:

#include "module4.h"
```

**Comment by dfarley1** [comment]
Just reset the IntelliSense database with logging set to Debug, It looks pretty minimal, but doesn't seem to be processing the common folder either?
```
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/codeAction
cpptools/resetDatabase
cpptools/resetDatabaseReady
Database safe to open
Code browsing service initialized
Discovering files...
  Processing folder (recursive): C:/Users/danielf/Ubuntu/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include/
  Processing folder (recursive): C:/Users/danielf/Ubuntu/rootfs/usr/local/include/
  Processing folder (recursive): C:/Users/danielf/Ubuntu/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/
  Processing folder (recursive): C:/Users/danielf/Ubuntu/rootfs/usr/include/
  Processing folder (recursive): C:/Users/danielf/Desktop/mgmt/app-sw/embed/module4/
  Discovering files: 2044 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populate include completion cache.
Parsing remaining files...
  tag parsing file: C:\Users\danielf\Desktop\mgmt\module4\src\main.cpp
  tag parsing file: C:\Users\danielf\Desktop\mgmt\module4\inc\interface.h
  tag parsing file: C:\Users\danielf\Desktop\mgmt\module4\inc\module4.h
  tag parsing file: C:\Users\danielf\Desktop\mgmt\module4\src\interface.cpp
  tag parsing file: C:\Users\danielf\Desktop\mgmt\module4\src\module4.cpp
  Parsing: 5 files(s) processed
Done parsing remaining files.
Database safe to open
cpptools/textEditorSelectionChange
textDocument/codeAction
```

**Comment by sean-mcmanus** [comment]
Yeah, you shouldn't have the top level mgmt. as a folder -- it is expected that the folders will not be children of each other...otherwise there might be problems. If you have mgmt as a root folder, it's possible we could incorrectly associate the module4/src files with the mgmt folder instead of the module4 folder.

For module4/src/interface.cpp, the includePath should have be "${workspaceFolder}/inc" to get module4/inc.

Those logs are for the global symbol parser. We don't parse files outside of the workspace in that case unless a file from the common folder is #included.

Is your loggingLevel set to Debug? Opening a file should show the IntelliSense "includes" used.

**Comment by dfarley1** [comment]
loggingLevel is set to Debug.
Oh, I forgot to mention that there is `#include "common_header.h"` in interface.cpp and module4.cpp.  So the outside files should be getting parsed?  Why aren't they showing up?

There's a bunch of other files parallel to the mgmt folder that I need access to, at least visually.  Can I somehow keep a "global" view of the whole project in Explorer even if the workspaces I care about are inside it?  If not, maybe the multi-root approach doesn't work in my case.

**Comment by sean-mcmanus** [comment]
The "tag parsing" applies to the browse.path, so you need to add "${workspaceFolder}/.." probably if you want global symbols to be parsed across workspace folders.

You could try adding the mgmt folder as a root folder, but then adding the subfolders to the files.exclude setting like "**/module4".

**Comment by dfarley1** [comment]
I tried going back to just one top-level workspace and using `${fileDirname}../inc/` to get the module heads only, but it looks like it can't be resolved and reverts to tag parsing my entire `${workspaceFolder}`.

```
cpptools/didChangeFolderSettings
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/g++'
Failed to spawn process. Error: 2 (The system cannot find the file specified.)
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/g++'
Failed to spawn process. Error: 2 (The system cannot find the file specified.)



  Unable to retrieve file system information for ${fileDirname}/../inc/. error = -1



  Folder: C:/Users/danielf/Ubuntu/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include/ will be indexed
  Folder: C:/Users/danielf/Ubuntu/rootfs/usr/local/include/ will be indexed
  Folder: C:/Users/danielf/Ubuntu/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/ will be indexed
  Folder: C:/Users/danielf/Ubuntu/rootfs/usr/include/ will be indexed
  Folder: C:/Users/danielf/Desktop/cnos/confd-6.5.6/libconfd/include will be indexed
  Folder: C:/Users/danielf/Desktop/cnos/cnsources/cpu/ will be indexed
textDocument/didOpen
Discovering files...
  Processing folder (recursive): C:/Users/danielf/Ubuntu/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include/
  Processing folder (recursive): C:/Users/danielf/Ubuntu/rootfs/usr/local/include/
  Processing folder (recursive): C:/Users/danielf/Ubuntu/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/
  Processing folder (recursive): C:/Users/danielf/Ubuntu/rootfs/usr/include/
  Processing folder (recursive): C:/Users/danielf/Desktop/cnos/confd-6.5.6/libconfd/include
  Processing folder (recursive): C:/Users/danielf/Desktop/cnos/cnsources/cpu/



Unable to resolve include path: ${fileDirname}/../inc/



  tag parsing file: C:\Users\danielf\Desktop\cnos\cnsources\cpu\mgmt\app-sw\embed\module4\src\interface.cpp
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\stdlib.h
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\c++\5\map
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\c++\5\set
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\c++\5\cstring
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\c++\5\thread
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\regex.h
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\x86_64-linux-gnu\sys\socket.h
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\x86_64-linux-gnu\sys\ioctl.h
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\netinet\in.h
  tag parsing file: C:\Users\danielf\Ubuntu\rootfs\usr\include\arpa\inet.h
  ...
```

Here's the output of a `echo ${fileDirname}` task from `mgmt/module4/interface.cpp`:
```
Executing task in folder cpu: echo c:\Users\danielf\Desktop\cnos\cnsources\cpu\mgmt\app-sw\embed\module4\src <

c:UsersdanielfDesktopcnoscnsourcescpumgmtapp-swembedmodule4src

Terminal will be reused by tasks, press any key to close it.
```

**Comment by sean-mcmanus** [comment]
We don't support ${fileDirname} yet.

**Comment by dfarley1** [comment]
Aww bummer. I might look into using cmake and generating a file for compileCommand then.  That should theoretically keep track of any special cases in one of the modules as well.

Thanks so much for the help!
