### ISSUE TITLE
externalConsole did not work while debugging with Xcode's lldb-mi

### ISSUE THREAD

**Issue by RRRaymond** [microsoft/vscode-cpptools#2955]
Type: Debugger

**Describe the bug**
- OS and Version: MacOS mojave 10.14.2
- VS Code Version: 1.21.1
- C/C++ Extension Version: 0.16.1

In my vscode, I could not see the content of vectors or maps while using the lldb-mi of the cpptools.
So I  using Xcode's lldb-mi instead and the I can see the content of vectors and maps.
But now, I can't debug with terminal even I set externalConsole to true. I can only using the integrated 
debugconsole of vscode, which could not get user's input.
Is there any solution or work around?
**Thanks!**

**Comment by MrCapone** [comment]
Same problem. On Linux debug works with built-in VSCode terminal which is good. But on macOS it is not.

**Comment by WardenGnaw** [comment]
The version of lldb-mi that we ship has changes that are not in master/lldb. These changes prevent the debug adapter from intermittent hanging the debugger (lldb).

We are still investigating on upgrading our version of lldb that we ship to the latest to have the visualizers working.
