### ISSUE TITLE
Language Service Crash with Nonstandard WSL Default

### ISSUE THREAD

**Issue by brianleu** [microsoft/vscode-cpptools#2956]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Pro Build 17134
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): None
- Language server crashes when opening a C project folder (5x 'Connection to server got closed. Server will not be restarted.' messages). I tried debugging and setting a breakpoint on the line after the 'languageClient.start();' line, but the process seems to crash before it hits the breakpoint.

**To Reproduce**

1. Open VS Code
2. Open Folder with multiple C files
3. 'The language server crashed 5 times in the last 3 minutes. It will not be restarted.'

**Expected behavior**

Language Server doesn't crash

**Screenshots**

**Additional context**

Not sure if any of this is relevant, but I added a distribution to WSL shortly before things stopped working. I also recently uninstalled VS2017 Community, but can't recall if VSCode C/C++ intellisense was still working after doing this...

**Comment by sean-mcmanus** [comment]
Yeah, it's possible the WSL and/or VS install change may have broken things, since we attempt to query WSL and the VS for compiler info.

You could try running WSL config to list and change the default WSL distribution used.

You might also try deleting the .BROWSE.VC.db file, which might be under `"C:\Users\<user>\AppData\Roaming\Code\User\workspaceStorage"`.

We fixed some crashes with 0.21.0-insiders2 as well: https://github.com/Microsoft/vscode-cpptools/releases , which you can get via setting the C_Cpp.updateChannel to "Insiders".

**Comment by brianleu** [comment]
Yeah, looks like it was setting Arch [(from here)](https://github.com/yuk7/ArchWSL) as WSL default that broke it... reverting to Debian as default (but leaving Arch installed/registered) and intellisense is fine again!

**Comment by sean-mcmanus** [comment]
Okay, thanks for the info. We should look into what is causing the crash with Arch (the same root crash could be reproducing in other scenarios as well).

**Comment by brianleu** [comment]
Sounds good! You can also close this as far as I'm concerned... supporting distros obtained outside official channels doesn't necessarily seem like something you're obligated to provide. I'm okay keeping Debian as WSL default and invoking other distros manually!

**Comment by kckemper** [comment]
I have the problem if I install g++ in my debian distro.

**Comment by brianleu** [comment]
With g++ installed in both Debian and Arch things are fine for me (assuming Debian is set to WSL Default)

**Comment by bobbrow** [comment]
We are no longer investing in changes to the extension to support WSL natively on Windows.  We recommend using the Remote - WSL extension to connect to your WSL environment and using the linux version of our extension there.
