### ISSUE TITLE
c/c++ plugin intellisence not working if includePath is set to recursive mode **

### ISSUE THREAD

**Issue by kkonevets** [microsoft/vscode-cpptools#2960]
Issue Type: <b>Bug</b>

if you set includePath to "${workspaceRoot}/**" go to definition stops working, but if you leave without ** it works, by default ** is used

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:05:00.654Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (3.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.9
python|ms-|2018.12.1
cpptools|ms-|0.20.1
cmake-tools|vec|1.1.3

</details>

**Comment by sean-mcmanus** [comment]
Can you provide a more specific repro? "${workspaceRoot}/**" is the default and works in normal cases. We have a more recent Insiders version with some fixes at https://github.com/Microsoft/vscode-cpptools/releases (or via changing the C_Cpp.updateChannel to "Insiders"). It's possible if your workspace is too large it could be stuck parsing. What exactly do you mean by "stops working". Does Go to Def stop working on local variables or global variables defined in other files?

**Comment by sean-mcmanus** [comment]
I assume this issue only happens when the workspace is "too large", right? It could be caused by parsing files (if you [enable Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and see parsing messages, or the #include completion cache code we're working on improving performance for (https://github.com/Microsoft/vscode-cpptools/issues/2836).

**Comment by kkonevets** [comment]
Correct, I am working with Tensorflow repo and it is big (just clone it from github and try). The weird thing is that when I just open vscode  I see "red fire" label in bottom right corner and while it is on "go to definition" works but just after it disappears it stops.
By "stops working" I mean that when I press F12 it does not focus on the definition of a variable or function.
I tried go to definition only on functions defined in other files inside Tensorflow, I could manually find the link by hand.
So I tried to remove ** and it started to work. I don't know maybe ** option has a better precision, but now it doesn't work

Insider version - no difference, same stuff

**Comment by sean-mcmanus** [comment]
Okay, thanks, we'll check out the repro project.

**Comment by sean-mcmanus** [comment]
It looks like I'm missing a bunch of .pb.h files which causes IntelliSense to fail. Do I need to compile to get those?

Also, what file are you opening?

When you [enable debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) do you see any errors and do the recursively compulted "includes: " listed appear correctly. This project appears to all reference includes based on the root, so removing the "**" might be a better approach.

**Comment by kkonevets** [comment]
from here [https://www.tensorflow.org/install/source](url)
first you should run `./configure` with default options (just press Enter everywhere), 
second run `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
` this will download external files you mentioned and then it will start to compile, press Ctrl-C to stop (it will compile lots of time, maybe 40 minutes, so you don't need it).  

I open cpp files, need some time to answer the rest of your questions

**Comment by kkonevets** [comment]
I forgot to mention, you can install bazel this way on mac [https://docs.bazel.build/versions/master/install-os-x.html](url)

or using homebrew:
brew tap bazelbuild/tap
brew tap-pin bazelbuild/tap
brew install bazelbuild/tap/bazel

**Comment by kkonevets** [comment]
[cpp_logs_debug.txt](https://github.com/Microsoft/vscode-cpptools/files/2715980/cpp_logs_debug.txt)

here are the logs you asked
pay attention to file:///Users/guyos/Documents/tensorflow/tensorflow/core/framework/collective.cc, 206:58 line, when "red fire" disappears "goto definition" does not work anymore on this function `MutableCollectiveRegistry()`
but if "fire is on" it will work

**Comment by sean-mcmanus** [comment]
Okay, I did the configuration, but I'm still missing files like tensorflow/core/framework/device_attributes.pb.h.

The IntelliSense parser is failing (which is the No IL available log), possibly due to the eigen3 folder issue (https://github.com/Microsoft/vscode-cpptools/issues/2976).

Then the Go to Definition code isn't gracefully falling back to the "Tag Parser" results -- a workaround for this is to change the C_Cpp.intelliSenseEngine setting for the workspace to "Tag Parser", i.e. Go to Definition succeeds after that, but you lose the IntelliSense enhanced features, so a better workaround is to add "**/tensorflow/eigen3" to your files.exclude setting. When the red flame is showing, it's detecting IntelliSense isn't ready and fall back to the Tag Parser results.

**Comment by kkonevets** [comment]
to get .pb.h files you should run `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package `

**Comment by sean-mcmanus** [comment]
Yeah, I ran that bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package command -- it's currently compiling...I assumed I didn't need to wait for it to compile?

**Comment by kkonevets** [comment]
as I said earlier - you should not, press Ctrl-C

**Comment by sean-mcmanus** [comment]
Yeah, I tried aborting the compile, but no pb.h file is generated. I don't see any error messages in the logs. It looks like our IntelliSense process is not crashing. Does the files.exclude workaround enable IntelliSense to work for you or is the eigen3 folder actually needed?

**Comment by sean-mcmanus** [comment]
This is what I get. Maybe one of the warnings is a problem?

![image](https://user-images.githubusercontent.com/19859882/50532504-fca93880-0ace-11e9-8653-40f67643be72.png)

**Comment by kkonevets** [comment]
I am sorry for misleading, you should compile to the end for .pb.h to appear. 
Those are auto-generated while bazel build known as protocolbuffer include files

**Comment by sean-mcmanus** [comment]
Ah, okay, thanks, I'll report back Monday to see what I get...

UPDATE: The build failed...investigating...

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
