### ISSUE TITLE
Red squiggle despite correct file paths

### ISSUE THREAD

**Issue by dominik-dev** [microsoft/vscode-cpptools#2961]
**Type: LanguageService**

**Describe the bug**
Red squiggle under header files, only the first one, no matter which order. 

- OS and Version: Windows 10 Home
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Clang Commander Adapter, C++ IntelliSense, Code Runner (Jun Han). Tried uninstalling deleting folders and reinstalling everything; always same result as issue.
- A clear and concise description of what the bug is.
Red squiggle under header file.

My "c_cpp_properties.json" file: 
`
{
    "configurations": [
        {
            "name": "Win32",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/mingw32",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/backward",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include",
                "C:/MinGW/include",
                "C:/MinGW/lib/gcc/mingw32/6.3.0/include-fixed"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "__GNUC__=6",
                "__cdecl=__attribute__((__cdecl__))"
            ],
            "browse": {
                "path": [
                    "C:/MinGW/lib/gcc/mingw32/6.3.0/include",
                    "C:/MinGW/lib/gcc/mingw32/6.3.0/include-fixed",
                    "C:/MinGW/include/*"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "compilerPath": "C:\\Program Files\\LLVM\\bin\\clang.exe",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
`

**Screenshots**
![image](https://user-images.githubusercontent.com/15054875/50378910-7c995380-0634-11e9-9c79-82ca16ae7c0d.png)
![image](https://user-images.githubusercontent.com/15054875/50378959-4d371680-0635-11e9-8469-54e3332891f6.png)

**Additional context**
Using `"C_Cpp.intelliSenseEngine": "Default"`

**Comment by sean-mcmanus** [comment]
You shouldn't put system include paths in your includePath setting. You should set the compilerPath correctly and let that bring in the system include paths. Your compilerPath is not set to a mingw compiler. It is probably able to find the string file but not able to find a dependency (the error message in the problem window should show more details). You can [enable Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) to see what includePaths are actually getting used.

**Comment by michelleangela** [comment]
Closing this issue. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
