### ISSUE TITLE
C after adding arguments to launch.json breakpoints dont work

### ISSUE THREAD

**Issue by jgrazew** [microsoft/vscode-cpptools#2962]
I am running VS Code in Ubuntu on a C program. 
After I add arguments to the args property in launch.json then launch the debugger, the program runs but it just skips past the break points. 

this is the code I am running to reproduce:

//teeCommand.c
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>

#include <unistd.h>
#include <fcntl.h>

#define BUF_SIZE 1024
#define handle_error(msg) do { perror(msg); exit(EXIT_FAILURE); } while (0)

int main(int argc, char *argv[])
{
    int fileLength;
    int inputFd, outputFd;
    char* buffer;
    ssize_t numRead;
    char buf[BUF_SIZE];

    if(argc < 5){
        printf("not enough arguments given");
    }

    inputFd = open(argv[1], O_RDWR | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH);
    if(inputFd == -1){
        handle_error("opening input file");
    }

    outputFd = open(argv[4], O_RDWR | O_CREAT, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH);
    if(outputFd == -1){
        handle_error("opening file output file");
    }

    while((numRead = read(inputFd, buf, BUF_SIZE)) > 0){
        if(write(outputFd, buf, numRead) != numRead){
            handle_error("could not write the whole buffer");
        }
    }
    if(numRead == -1){
        exit(1);
    }

    if(close(inputFd) == -1){
        exit(1);
    }
    if(close(outputFd) == -1){
        exit(1);
    }

    exit(EXIT_SUCCESS);
}

//launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/teeCommand",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

//task.json

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "gcc -O0 -g teeCommand.c -o teeCommand",
            "group":{
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

**Comment by WardenGnaw** [comment]
Where are you setting your breakpoints? 

Can you also [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) and copy the output here?

**Comment by jgrazew** [comment]
i was setting my break points on the first bracket below the main function, where inputFd and outputFD are being assigned values with in the main function function

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
