### ISSUE TITLE
Provider API does not affect files visible and opened when VS Code is first opened, or providers changed.

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#2966]
I have an extension providing configurations through the API, and some of my users are noticing an odd issue, that I can verify through enabling debugging logging. When they first open VS Code, and they have cpp files open, or they open cpp files before the provider has started, the files are opened with the default intellisense configuration for the platform, rather then the provided API. This makes sense, because there is no known provider by this point, however when `notifyready` is called in the API, I would expect the file to change to be parsed with the new provided configurations. However, this does not seem to be the case, and intellisense continues to be provided by the platform default. 

Another oddity is my extension can change the provider on the fly to target different platforms. This worked in previous versions of the cpp extension, but it does not seem to be working now in 0.20.1. I'm calling `cppToolsApi.didChangeCustomConfiguration()`, but this does not seem to be changing any provided configurations.

```
sending compilation args for C:\USERS\THADH\DOCUMENTS\BETATESTING\LOCKTESTCPP\SRC\MAIN\CPP\ROBOT.CPP
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\VC\TOOLS\MSVC\14.16.27023\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\VC\TOOLS\MSVC\14.16.27023\ATLMFC\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\WINRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\CPPWINRT
  include: C:\USERS\THADH\DOCUMENTS\BETATESTING\LOCKTESTCPP\BUILD\TMP\EXPANDEDARCHIVES\WPILIBC-CPP-2019.1.1-BETA-3-HEADERS.ZIP_793ECB2CEC6159753014E78C54431A22
  include: C:\USERS\THADH\DOCUMENTS\BETATESTING\LOCKTESTCPP\BUILD\TMP\EXPANDEDARCHIVES\CAMERASERVER-CPP-2019.1.1-BETA-3-HEADERS.ZIP_8E6098F7E4E3B331E0504D2D66CEBD71
  include: C:\USERS\THADH\DOCUMENTS\BETATESTING\LOCKTESTCPP\BUILD\TMP\EXPANDEDARCHIVES\WPIUTIL-CPP-2019.1.1-BETA-3-HEADERS.ZIP_09B38849DBDFA883C4BE908731924BE2
  include: C:\USERS\THADH\DOCUMENTS\BETATESTING\LOCKTESTCPP\BUILD\TMP\EXPANDEDARCHIVES\CSCORE-CPP-2019.1.1-BETA-3-HEADERS.ZIP_0324C2EA7062F8412624EBA46D406EED
  include: C:\USERS\THADH\DOCUMENTS\BETATESTING\LOCKTESTCPP\BUILD\TMP\EXPANDEDARCHIVES\HAL-CPP-2019.1.1-BETA-3-HEADERS.ZIP_82510C6B0F5E8246FE22C38CB7751914
  include: C:\USERS\THADH\DOCUMENTS\BETATESTING\LOCKTESTCPP\BUILD\TMP\EXPANDEDARCHIVES\NTCORE-CPP-2019.1.1-BETA-3-HEADERS.ZIP_DE8BB156E7C972A7498927AC56D827F7
  define: _DEBUG
  define: UNICODE
  define: _UNICODE
  stdver: --ms_c++latest
  intelliSenseMode: msvc
  Processing folder (recursive): C:/USERS/THADH/DOCUMENTS/BETATESTING/LOCKTESTCPP/BUILD/TMP/EXPANDEDARCHIVES/NETCOMM-2019.9.3-HEADERS.ZIP_17EACC74380083365BC16ACA05F210AF/
  Processing folder (recursive): C:/USERS/THADH/DOCUMENTS/BETATESTING/LOCKTESTCPP/SRC/MAIN/INCLUDE/
  Processing folder (recursive): C:/USERS/THADH/DOCUMENTS/BETATESTING/LOCKTESTCPP/BUILD/TMP/EXPANDEDARCHIVES/WPILIBC-CPP-2019.1.1-BETA-4-SOURCES.ZIP_269031B0B926A36D566DEFADAF3B5034/
Checking for syntax errors: file:///c%3A/Users/thadh/Documents/BetaTesting/LockTestCpp/src/main/cpp/Robot.cpp
queue_update_intellisense for files in tu of: C:\USERS\THADH\DOCUMENTS\BETATESTING\LOCKTESTCPP\SRC\MAIN\CPP\ROBOT.CPP
  Processing folder (recursive): C:/USERS/THADH/DOCUMENTS/BETATESTING/LOCKTESTCPP/BUILD/TMP/EXPANDEDARCHIVES/HAL-CPP-2019.1.1-BETA-4-SOURCES.ZIP_7A52AC201F0B0FE63F9122CCB78ACCFE/
  Processing folder (recursive): C:/USERS/THADH/DOCUMENTS/BETATESTING/LOCKTESTCPP/BUILD/TMP/EXPANDEDARCHIVES/WPIUTIL-CPP-2019.1.1-BETA-4-SOURCES.ZIP_27F7D7FA68257A63301BAC2AFC842AB9/
  Processing folder (recursive): C:/USERS/THADH/DOCUMENTS/BETATESTING/LOCKTESTCPP/BUILD/TMP/EXPANDEDARCHIVES/NTCORE-CPP-2019.1.1-BETA-4-SOURCES.ZIP_AC9FC944D72A25AA34CD72DB9B9D4F46/
  Processing folder (recursive): C:/USERS/THADH/DOCUMENTS/BETATESTING/LOCKTESTCPP/BUILD/TMP/EXPANDEDARCHIVES/CSCORE-CPP-2019.1.1-BETA-4-SOURCES.ZIP_BCB4A09A184D1AF4F52B363440153677/
  Processing folder (recursive): C:/USERS/THADH/DOCUMENTS/BETATESTING/LOCKTESTCPP/BUILD/TMP/EXPANDEDARCHIVES/CAMERASERVER-CPP-2019.1.1-BETA-4-SOURCES.ZIP_5F7E9586978010D82528C8F2DAA3F911/
  Processing folder (recursive): C:/USERS/THADH/DOCUMENTS/BETATESTING/LOCKTESTCPP/BUILD/TMP/EXPANDEDARCHIVES/OPENCV-CPP-3.4.4-4-SOURCES.ZIP_77141D62B3E263395A4B585628A50D3D/
  Discovering files: 5686 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populate include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
$/cancelRequest
textDocument/documentSymbol
textDocument/codeAction
errorSquiggles count: 3
textDocument/codeAction
textDocument/hover
Database safe to open
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
Custom configurations received:
```

**Comment by bobbrow** [comment]
Hi @ThadHouse, we noticed this too and there should be a fix in the latest insiders build for this.  Could you try it out and confirm it works for you?

**Comment by ThadHouse** [comment]
I tested and insiders fixed the first part of the issue (setting up proper configurations during initialization), but did not fix the second part of the issue (changing configurations after initial loading). Any time I change configurations, the logger shows `Custom configurations received:` but does not actually change anything.

**Comment by bobbrow** [comment]
Ok.  I'll see if I can get a repro for the second issue.

**Comment by ThadHouse** [comment]
Doing some more debugging for the second issue, when I close and reopen a file, I get the full `custom configuration received`, however that does not cause the `sending compilation args` message to happen. It seems that sending compilation args only happens after the language server for that specific file has been shut down and restarts, and not when `didChangeCustomConfiguration` is called.

**Comment by ThadHouse** [comment]
I still notice the first issue occasionally even on insiders. Its not always, but it does happen sometimes.

**Comment by go2sh** [comment]
I have the same problem. I create a CMake based extension and if the CMake configuration is updated, the internal model is updated and so the configurations. But it is not used. Both the browse configuration and the per-file configuration.

**Comment by Colengms** [comment]
Hi @ThadHouse .  Are you still seeing this issue with recent versions of the extension?  I'm not currently easily able to repro an issue with already-open files getting configured, or providers changing on the fly.  Can you confirm whether this is still an issue for you?

**Comment by ThadHouse** [comment]
I'll check again this weekend.
