### ISSUE TITLE
#error directive: "Never include <bits/syslog.h> directly; use <sys/syslog.h> instead."

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#2967]
**Type: LanguageService**
- OS and Version: Archlinux

**Step to reproduce**
1. creat c file.
```c
#include <syslog.h>

int main(void) {
    syslog(LOG_ERR, "test"); // Go to Definition at syslog 
}
```
2.  Go to Definition at syslog.
> Go to **Definition** should jump to the same place as Go to **Declaration** because I don't think syslog is defined in header file.
3.  #error directive: \"Never include <bits/syslog.h> directly; use <sys/syslog.h> instead.\".

**Comment by sean-mcmanus** [comment]
Do you believe the error is that Go to Definition is going to the wrong file or that when the bits/syslog.h file is opened we should be choosing a better set of files to compile with such that the #error doesn't appear? The Go to Definition code doesn't really have any way to determine that the definition is not correct, and the bits/syslog.h file won't be part of a TU unless the fortify defines are set, so I don't see a way of fixing that either.

**Comment by lh123** [comment]
Finding the correct definition needs to be done during the linking. 

It seems that it cannot be fixed unless Intellsence can also work in the link period.
