### ISSUE TITLE
Intellisense does not update changes outside of the current folder

### ISSUE THREAD

**Issue by zhiayang** [microsoft/vscode-cpptools#2968]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10, 1803 / 17134 -- in WSL!
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1

The Intellisense engine does not detect changes to files outside of the current workspace (or folder). Changes to functions and types are not reflected, and new definitions are not updated (I'm unable to Go To Definition/Declaration).

The current setup I have is a multi-root workspace, with a couple of folders; each folder has its own `.vscode` folder, with its own `c_cpp_properties.json` file. The physical layout is as such:

```
root/
  |- foo/
  |  |- .vscode/
  |
  |- bar/
  |  |- .vscode/
  |
  |- .vscode/
```

For instance, assume that `foo` depends on `bar`, and I have setup `includePath` and `browse.path` appropriately in the configuration file. If I change some declarations in the headers of `bar`, they are not seen in the source files of `foo` -- resulting in errors, or sometimes lack thereof.

I have set `"limitSymbolsToIncludedHeaders": false` in the configuration as well. Opening the changed file in VSCode (in an attempt to get intellisense to 'refresh') does nothing -- only a full restart of VSCode (or, I suspect, just the extension itself) gets me the new definitions. Strangely, resetting the intellisense database (for both `foo` and `bar`) also does nothing.

**To Reproduce**
1. Recreate the folder structure above, and create some header files in either subdirectory
2. Make some changes to the headers

**Expected behaviour**
Intellisense should detect the changes, and provide definitions/dropdowns.

PS:
How does VSCode determine whether the compiler (in `compilerPath`) is a WSL compiler or not? Is it path-based, or does it look at the executable itself? I ask because this is my `compilerPath: "${workspaceFolder}/build/toolchain/bin/x86-64-elf-g++"`, and I get this error in the output: `Failed to query default include paths and defines for d:\Projects\nx/build/toolchain/bin/x86_64-elf-g++. WSL not detected`

In WSL land I'm accessing the workspace folder through `/mnt/d/Projects/`, and that's where the compiler lives as well. I can't set `compilerPath` to be `/mnt/d/...`, because as expected that folder is actually empty.

PPS:
If there is a better way to organise my project, do let me know, because this current setup (c++ issues aside) is a little unwieldy. I do need separate C++ configs for each subfolder though.

**Comment by sean-mcmanus** [comment]
With WSL, you're supposed to access the compiler via a WSL path, such as "/usr/bin/gcc". I've never tried a WSl compilerPath that wasn't under "/usr/bin" or something similar...are you saying we're buggy with that? When we encounter a compilerPath that won't run on Windows we try again under WSL, so you should set the compilerPath to whatever you run under WSL.

We still need to investigate the update issue. You might just need to set the browse.path to include all the folders that you want to react to changes or we could have a bug.

**Comment by zhiayang** [comment]
Hello, happy holidays.

For the updating issue, I have tried setting browse.path to include the entire root directory (in the example above, that would be `root` -- I just used `${workspaceFolder:root}`), but the issue persists.


With regards to the WSL compiler discovery, this is the output that I get on log level "Information":

```
Failed to query default include paths and defines for d:\Projects\nx/build/toolchain/bin/x86_64-orionx-g++. WSL not detected
Code browsing service initialized
Failed to query default include paths and defines for d:\Projects\nx/build/toolchain/bin/x86_64-orionx-g++. WSL not detected
  Folder: D:/Programs/archlinux/rootfs/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include/ will be indexed
  Folder: D:/Programs/archlinux/rootfs/usr/local/include/ will be indexed
  Folder: D:/Programs/archlinux/rootfs/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed/ will be indexed
  Folder: D:/Programs/archlinux/rootfs/usr/include/ will be indexed
  Folder: D:/Projects/nx/efx/ will be indexed
  Folder: D:/Projects/nx/libs/libkrt/ will be indexed
  Folder: D:/Projects/nx/libs/zircon-efi/ will be indexed
```

The compiler is referred to from a Windows path, but it's actually a WSL compiler. The reason I can't refer to it using a Unix path (eg. `/home/foo/g++`) is that the toolchain lives in the shared WSL folder (in my case `/mnt/d/...`), which will be empty when viewed from Windows.

I could move the compiler outside of the shared folder, but since it's the toolchain for the project ideally I'd like to keep it in the project tree.

From the output, it looks like it fails to detect what kind of compiler it is, then falls back to default gcc...? `D:/Programs/archlinux` is my WSL installation. My toolchain should not be looking at those system folders for includes.

**Comment by sean-mcmanus** [comment]
What do you mean by "root"? The "${workspaceFolder:root}" syntax only would be used to reference another root folder named "root". If one of your workspace folders is the "root" then that is a known unsupported scenario that is highly buggy. Our current multi-root support is for when all the root folders are separate and not children of another.

Why can't you use the /mnt/d/... as the compilerPath? Do we fail? We invoke that path inside of WSL, so it should succeed, so I don't know what you mean by it being "empty when viewed from Windows".

**Comment by zhiayang** [comment]
Hm, I was not aware that that was an unsupported scenario; this is my current structure:
```
root/
  |- .vscode/
  |
  |- foo/
  |  |- .vscode/
  |
  |- bar/
  |  |- .vscode/
```

In my case, the `c_cpp_properties.json` files in `foo` and `bar` have `browse.path` entries that refer to `root/`. I can move the source code that lives in `root` into a separate folder (say `qux`) that lives under `root` as well. If `root` does not have a `c_cpp_properties.json` file, then will it work as expected? While there's no code directly in the root directory, there's still some stuff there that I'd like to be included as part of the workspace.


As for the compiler issue, I get this:
```
Compiler include path not found: D:\Programs\archlinux\rootfs\/mnt/d/Projects/nx/build/toolchain/lib/gcc/x86_64-orionx/8.2.0/../../../../x86_64-orionx/include/c++/8.2.0
Compiler include path not found: D:\Programs\archlinux\rootfs\/mnt/d/Projects/nx/build/toolchain/lib/gcc/x86_64-orionx/8.2.0/../../../../x86_64-orionx/include/c++/8.2.0/x86_64-orionx
Compiler include path not found: D:\Programs\archlinux\rootfs\/mnt/d/Projects/nx/build/toolchain/lib/gcc/x86_64-orionx/8.2.0/../../../../x86_64-orionx/include/c++/8.2.0/backward
Compiler include path not found: D:\Programs\archlinux\rootfs\/mnt/d/Projects/nx/build/toolchain/lib/gcc/x86_64-orionx/8.2.0/include
Compiler include path not found: D:\Programs\archlinux\rootfs\/mnt/d/Projects/nx/build/toolchain/lib/gcc/x86_64-orionx/8.2.0/include-fixed
Compiler include path not found: D:\Programs\archlinux\rootfs\/mnt/d/Projects/nx/build/toolchain/lib/gcc/x86_64-orionx/8.2.0/../../../../x86_64-orionx/include
Compiler include path not found: D:\Programs\archlinux\rootfs\/mnt/d/Projects/nx/build/sysroot/usr/include
```

The paths mentioned definitely exist on disk; for example the last entry exists as `D:/Projects/nx/build/sysroot/usr/include`. Could it be a path resolution issue?

EDIT: as for what I meant when I said "empty as viewed from Windows", I was referring to the fact that, when accessing the folder under Window, the folder is expectedly empty. But since you mention that the extension uses the WSL subsystem to access the folder, then that's not the case.


EDIT 2: I've deleted the extension configuration in the `root/` folder, but the issue still persists. Or do I actually have to remove the root folder entirely from my workspace, and solely use the subfolders?

**Comment by sean-mcmanus** [comment]
If your workspace folders are foo, bar, and root, then you should remove root. You can still reference the root via "${workspaceFolder}/.." (e.g. for the browse.path).

When we query the compiler under WSL, we assume the paths we get back are relative to the WSL root folder (e.g. /usr/include), so if your compiler is returning a /mnt path that won't work unless we added code to handle that. I haven't heard of any other users trying to invoke a compiler under /mnt and I havent' seen any docs about that so I'm not even sure if that's a valid scenario yet. Is the compiler runnable on Windows? Can you move the compiler under the WSL root folder?

**Comment by zhiayang** [comment]
Removing the root folder from my list of folders (leaving just `bar` and `foo`) (and restarting VSCode) did not appear to fix the updating problem :/

Can subfolders (in a single-root workspace) provide their own `.vscode` directories? Or more specifically, does the C++ extension handle this case? Or does it only fetch configuration info from the top-level folder in each root of a workspace? If I can make it work, I am more than willing to use a single-root workspace for this project.


About the compiler -- it's definitely an ELF executable, so not runnable under Windows. If I set the path to somewhere inside the WSL hierarchy but outside of `/mnt`, then the detection appears to succeed:
```
Compiler include path not found: D:\Programs\archlinux\rootfs\/mnt/d/Projects/nx/build/sysroot/usr/include
  Folder: D:/Programs/archlinux/rootfs/home/zhiayang/code/nx-build/toolchain/lib/gcc/x86_64-orionx/8.2.0/include/ will be indexed
  Folder: D:/Programs/archlinux/rootfs/home/zhiayang/code/nx-build/toolchain/lib/gcc/x86_64-orionx/8.2.0/include-fixed/ will be indexed
  Folder: D:/Programs/archlinux/rootfs/home/zhiayang/code/nx-build/toolchain/x86_64-orionx/include/ will be indexed
```

However the first line is still an error, because the compiler is configured to look there for includes.

**Comment by sean-mcmanus** [comment]
No, plain "folders" with a .vscode/c_cpp_properties.json will not be picked up, only the root one in each "workspace folder" (i.e. you do Open Folder for bar and then Add Folder to Workspace for foo).

Using just the single "root" folder with bar/foo children is normally supposed to work, unless the folders need to be configured in some incompatible way.

**Comment by zhiayang** [comment]
Each subproject does need slightly different include paths, mainly because there are identically named headers with subtly different contents, so I don't think I can add all the includes for each sub-project into the main list at the root-level.

Regardless, the update issue doesn't seem to be affected by this.

**Comment by sean-mcmanus** [comment]
Okay, I don't think I understand how exactly to repro the updating issue -- what file exactly is being modified and what file is the update not getting recognized in? Updates in files belong to the current TU get updated by our IntelliSense process (i.e. error squiggles, hover). Updates outside of the TU get saved to our database (i.e. Outline symbols, and Go to Def might use these results). Are you able to upload a repro simple project for me? That might be easier to for me to repro the problem.

**Comment by zhiayang** [comment]
I've created a repo: https://github.com/zhiayang/vscode-repro

Clone it so it looks like this:
```
vscode-repro/
  |- subproj-one/
  |
  |- subproj-two/
```
Use VSCode to add the `subproj-one` and `subproj-two` folders to the workspace.

Changes in `two.h` are not reflected in `main.cpp` until the window is reloaded (or vscode is restarted). For instance, adding a new function in the namespace does not appear in the dropdown after `foo::`.

**Comment by sean-mcmanus** [comment]
Okay -- I see the problem. The didChange events are getting sent to the subproj-two folder's process and not the subproj-one process. @bobbrow Is it quick/easy for you to change the TypeScript multi-root code to send the didOpen/didChange/etc. events too all the clients or is this too low pri? The current behavior seems pretty broken (usage of multi-root is relatively low, so we haven't prioritized fixing issues like this previously).

Another potential way to support per-folder include paths using 1 workspace folder would be to use cmake to generate a compile_commands.json, which supports per-folder/file includePaths.

**Comment by zhiayang** [comment]
Thanks for looking into this.

I tried the `compile_commands.json` thing, but I think the issue of finding the compiler in `/mnt` is still an issue, except this time I don't get any intellisense at all -- but that's a separate issue I guess.

(as an aside, I can't get compiledb which i'm using for my Make projects to play nice with recursive make, so the `file` key in the JSON is wrong (or it's not absolute to the project root), which is kind of a pain to manually fix)

**Comment by zhiayang** [comment]
Hello, are there any updates on this? I just got hit with this issue after forgetting about its existence, which is kinda lame cos it's been almost 7 months.

Is this something that can be fixed by an extension (sending events to other workspaces?), or is it something that has to be fixed in vscode itself?

**Comment by sean-mcmanus** [comment]
No updates yet. It should be fixable via changes to our open source TypeScript. I can move it to On Deck I think.

**Comment by zhiayang** [comment]
yay, that's great to hear!

**Comment by bobbrow** [comment]
@sean-mcmanus I'm tagging this as relevant to the multi-root work you're doing. It should be addressed by that.

**Comment by sean-mcmanus** [comment]
Our latest Insiders release has a new multi-root implementation (which fixes this bug): https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders. Please let us know if you find any multi-root-related bugs or regressions so we can prioritize fixing those for 0.27.0.

**Comment by zhiayang** [comment]
As mentioned in #3183 this has indeed been fixed in the insiders2 release which i'm currently running. thanks again!
