### ISSUE TITLE
The language server crashed. Can't use fsutil.

### ISSUE THREAD

**Issue by VitalyVint** [microsoft/vscode-cpptools#2969]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Microsoft Windows 7 SP 1
- VS Code Version: 1.30.1
- C/C++ Extension Version: 20.1
- Other extensions you installed (and if the issue persists after disabling them):

**To Reproduce**

1. start VS code without administrative privileges
2. open any project with cpp files
3. navigate to *.cpp file
4. "The language server crashed 5 times in the last 3 minutes. It will not be restarted".

**Additional context**

Using ProcessMonitor i found that Microsoft.VSCode.CPP.Extension.exe trying to start `fsutil` command. Without administrative privileges that command failed, witch will fail extenshion with return code -1073740777.

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this -- the call to fsutil.exe is to detect if the Windows OS supports case-sensitive file paths (https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/). On Win10, this doesn't require admin privileges. Since case-sensitive file paths are not possible on Win7, we should be able to fix this issue via not making that call on Win7.

**Comment by sean-mcmanus** [comment]
I got a fix for our next release via avoiding launching fsutil on Win7, but I'm not able to repro any crash on Win7 with a non-admin account and our code isn't supposed to crash when the child process fails to launch, so I'm not able to verify the fix.

**Comment by sean-mcmanus** [comment]
Are you on a 32-bit OS? I'm seeing the create process for fsutil.exe working successfully on Win7 with a non-admin account. Well, I don't see any reason why it would fail on a 32-bit OS versus a 64-bit OS, since all the processes involved are 32-bit in all cases.

Is calling fsutil the last event that occurs before the crash? I'm not sure what OS setting is required to get the failure to occur on Win7.

**Comment by VitalyVint** [comment]
64-bits os, fsutil successfully started and printed "i need administratirve privileges".
I tried to collect dumps using Vusial Studio debugger of image execution options - nothing.
Error reporting to collect dumps - still nothing. Debug logs ends in different places (looks like it not flushed). So i guess problem with fsutil - it only one that go wrong amd i could find.
Thank you for fix.

**Comment by VitalyVint** [comment]
I found workaround: just change console code page to 437 (english) before launch VSCode and it will work well, my usual language is 866 (russian). Windows system utilities has localized messages and stdint/stdout is just ansii strings:-(.

**Comment by sean-mcmanus** [comment]
Hmm...I changed my OS's code page to 866 and I wasn't able to repro any crash, i.e. fsutil outputs Russian text and chcp from a new cmd gives 866 (so there might be some other requirement?), but if this code page issue only is a problem with Win7 then our pending fix should still work.

**Comment by VitalyVint** [comment]
maybe you have no Russian language pack installed? i tried 860 - brazil and fsutil still print english.

**Comment by sean-mcmanus** [comment]
Yeah, I have the Russian language pack for the OS and VS Code, i.e. everything is in Russian. I'm seeing the fsutil command fail due to the nonadmin, but I don't see any crash.

![image](https://user-images.githubusercontent.com/19859882/50498236-d95d8b00-09f3-11e9-8d27-e42d04919d2c.png)

**Comment by VitalyVint** [comment]
That my turn to say "hmm"....

Finally i can get stack trace,
```
00 0327eeb4 011c44a4 Microsoft_VSCode_CPP_Extension!terminate
01 0327ef1c 011c4885 Microsoft_VSCode_CPP_Extension!FindHandler<__FrameHandler3>+0x38d
02 0327ef50 011bed04 Microsoft_VSCode_CPP_Extension!__InternalCxxFrameHandler<__FrameHandler3>+0xf7
03 0327ef8c 7758b6ad Microsoft_VSCode_CPP_Extension!__CxxFrameHandler3+0x26
04 0327efb0 7758b67f ntdll!ExecuteHandler2+0x26
05 0327efd4 7758b620 ntdll!ExecuteHandler+0x24
06 0327f060 77540163 ntdll!RtlDispatchException+0x127
07 0327f060 7568c42d ntdll!KiUserExceptionDispatcher+0xf
08 0327f400 011be794 KERNELBASE!RaiseException+0x58
09 0327f444 00d757cd Microsoft_VSCode_CPP_Extension!_CxxThrowException+0x66
0a 0327f488 00d68b93 Microsoft_VSCode_CPP_Extension!vscode::vscode_client_message::convert_raw_contents+0x8d
0b 0327f8d8 00d6b60c Microsoft_VSCode_CPP_Extension!vscode::vscode_client_message::vscode_client_message+0x14d
0c 0327f994 00d73aca Microsoft_VSCode_CPP_Extension!<lambda_1da3d9583f4f21df7da3f84e9944c16d>::operator()+0x86
0d 0327f9b4 00d71efd Microsoft_VSCode_CPP_Extension!std::_LaunchPad<std::unique_ptr<std::tuple<std::function<void __cdecl+0x38
0e 0327f9bc 00d2eec4 Microsoft_VSCode_CPP_Extension!std::_LaunchPad<std::unique_ptr<std::tuple<std::function<void __cdecl+0x6
0f 0327f9c4 011ece59 Microsoft_VSCode_CPP_Extension!std::_Pad::_Call_func+0xa
10 0327fa00 757e337a Microsoft_VSCode_CPP_Extension!thread_start<unsigned int +0x58
11 0327fa0c 775692e2 kernel32!BaseThreadInitThunk+0xe
12 0327fa4c 775692b5 ntdll!__RtlUserThreadStart+0x70
13 0327fa64 00000000 ntdll!_RtlUserThreadStart+0x1b
```
I manually start Microsoft.VSCode.CPP.Extension.exe and wrote two messages into console.

**Comment by sean-mcmanus** [comment]
Yeah, it looks like we throw that exception if we receive an invalid Language Server Protocol message (i.e. from VS Code) -- why do you suspect that is the same crash you are experiencing without manually starting the process?

**Comment by VitalyVint** [comment]
oh, sorry, i check again - it my mistake. I think i check it with changed locale, but not. sorry.

**Comment by sean-mcmanus** [comment]
0.21.0 should fix this via avoiding the call to fsutil.exe on Windows 7. Let us know if you're still hitting this problem.
