### ISSUE TITLE
VSCode is using a lot of the CPU on this Mac with the CPP extension

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-cpptools#297]
_From @brennanMKE on October 18, 2016 19:41_
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Kasik96.swift-0.0.2, Orta.vscode-ios-common-files-1.0.2, TimonVS.ReactSnippetsStandard-1.0.3, TwentyChung.jsx-0.0.1, alechp.react-toolbox-snippets-0.12.0, cdsama.shell-snippets-0.1.2, dbaeumer.vscode-eslint-1.0.8, donjayamanne.githistory-0.1.0, dzannotti.vscode-babel-coloring-0.0.4, eg2.tslint-0.5.39, flowtype.flow-for-vscode-0.3.3, gllwy.theme-dusk-0.0.7, groksrc.ruby-0.0.6, kube.ClangComplete-0.0.4, mitaki28.vscode-clang-0.2.1, ms-vscode.cpptools-0.9.2, ornithologist.ios-snippets-0.0.15, rebornix.Ruby-0.9.0, redhat.java-0.0.5, robertohuertasm.vscode-icons-3.0.5, rtorr.vscode-flow-276.3.0, vsmobile.vscode-react-native-0.2.0, waderyan.babelrc-1.0.0, xabikos.ReactSnippets-1.2.0

It appears to be related to `Microsoft.VSCode.CPP.Extension.darwin` and `parentalcontrolsd`. When I run VSCode the CPU is used heavily and the fan makes a lot of noise. This is happening just recently when I started using VSCode with C code. Specifically I am viewing code for the `pjsim` project on GitHub. Perhaps loading up that project on a Mac (El Capitan) with VSCode will be a way to reproduce the problem.

Steps to Reproduce:
1. Clone `pjsim` project from GitHub https://github.com/chakrit/pjsip
2. Open that folder with VSCode
3. Install the recommended plugins for C/C++
4. Restart VSCode
5. Wait for the CPP plugins to wreak havoc on all that is good and holy

It appears to not cause any trouble without the recommended CPP plugins. The Microsoft CPP and Clang plugins for C/C++ have been downloaded a lot and have high ratings so I expected them to be alright.

One potentially important detail is that I am running a beta release of Xcode (8.1 beta 3) and have that path selected with `Xcode-select`. If that is somehow the cause for this trouble it would be best to resolve it before the final 8.1 release is out.

_Copied from original issue: Microsoft/vscode#13958_

**Comment by sean-mcmanus** [comment]
Microsoft.VSCode.CPP.Extension.darwin is expected to use 100% CPU on 1 core. Is that the behavior you're seeing? How is that a problem for you?

**Comment by brennanMKE** [comment]
It is a problem because VSCode is in the background while I am working in another app. I expect it should not be doing anything while I am not actively using the app. In the very least it should have a much lower priority so that it is not using the CPU heavily.

**Comment by sean-mcmanus** [comment]
How many CPU cores do you have? Are you saying our extensions process is competing with another process for the same CPU core? We expect our users to have multi-core machines that have enough processing power to do the necessary processing. I suppose we could add a setting to turn off features that require this processing. If your machine makes a loud fan noise when a process uses a lot of CPU on one core, I would recommend getting a better computer. I have not used a machine with a loud fan noise in a long time. I have not noticed any problem on our Macs yet.

**Comment by brennanMKE** [comment]
This MacBook has a 3.1 GHz dual Core i7 processor.

https://support.apple.com/kb/SP715?locale=en_US&viewlocale=en_US

**Comment by sean-mcmanus** [comment]
Yeah, that seems like a good machine. My laptop has similar specs. The Intel processor seems to use some turbo boost that has a louder fan when CPU usage gets too high, but that is normal. Your machine should have 4 logical cores, and our process should only be using 1 of those logical cores, so you should be able to use your other apps without problem. If the noise is a bother to you, you may want to consider wearing headphones. You can also kill the process. We are busy with other higher priority issues currently, but we can investigate your particular repro later to see if there's something unusual going on.

**Comment by brennanMKE** [comment]
Today I do not have the `pjsip` project opened so it is not busy today. I still have the recommended CPP plugins installed. It seems having Android/Java and JavaScript projects do not cause any excessive processing.

For your test case is appears that `pjsip` is a good way to reproduce the issue.

**Comment by sridmad** [comment]
@brennanMKE , Thanks for the repro.

When a open a folder with C++ files is opened with VSCode-cpptools extension installed following we do the following
- Parse _all_ C / C++ files recursively under the folder to populate the browse database.
- Once all files under the folder are processed, headers referenced in the source files are located in the set of  directories specified by includePath settings (defaults to /usr/include).

As @sean-mcmanus indicated we use a single thread to do this work but sometime it can take a while to complete. The time spent is directly dependent on the number of C/C++ files under the folder and number of headers referenced by these sources. In the past I have tried opening large projects with the extension installed and it has taken a while for really large projects with thousands of files.

I will take a look at the project to see if there is anything special about this project that is causing the parser to hit some bottleneck.

**Comment by brennanMKE** [comment]
It could be something unique. It seemed like it would stop for a while and start again. Perhaps you can identify a unique detail in that project which causes this problem to happen.

**Comment by dengxf2008-zz** [comment]
I also have this issue on multiple versions of vscode. and the cpu is high even the vscode is exited. but the extension does not exit. bellow is the data from monitor:

Sampling process 15273 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling Microsoft.VSCode.CPP.Extension.darwin (pid 15273) every 1 millisecond
Process:         Microsoft.VSCode.CPP.Extension.darwin [15273]
Path:            /Users/dengxf/.vscode/extensions/ms-vscode.cpptools-0.9.2/bin/Microsoft.VSCode.CPP.Extension.darwin
Load Address:    0x10d1ad000
Identifier:      Microsoft.VSCode.CPP.Extension.darwin
Version:         0
Code Type:       X86-64
Parent Process:  ??? [1]

Date/Time:       2016-11-12 22:39:08.600 +0800
Launch Time:     2016-11-12 20:54:03.677 +0800
OS Version:      Mac OS X 10.12.2 (16C41b)
Report Version:  7

## Analysis Tool:   /usr/bin/sample

Call graph:
    2666 Thread_1640211   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2666 start  (in libdyld.dylib) + 1  [0x7fffaee5e255]
    +   2666 main  (in Microsoft.VSCode.CPP.Extension.darwin) + 102  [0x10d1aedf6]
    +     2666 vscode::handler_base<message_handler>::main_loop()  (in Microsoft.VSCode.CPP.Extension.darwin) + 757  [0x10d1af135]
    +       2666 std::__1::thread::join()  (in libc++.1.dylib) + 23  [0x7fffada3e4b7]
    +         2666 pthread_join  (in libsystem_pthread.dylib) + 425  [0x7fffaf077855]
    +           2666 __semwait_signal  (in libsystem_kernel.dylib) + 10  [0x7fffaef8cfda]
    2666 Thread_1640214
      2666 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fffaf0751fd]
        2666 _pthread_start  (in libsystem_pthread.dylib) + 286  [0x7fffaf0759f7]
          2666 _pthread_body  (in libsystem_pthread.dylib) + 180  [0x7fffaf075aab]
            2666 void\* std::__1::__thread_proxystd::__1::tuple<vscode::handler_base<message_handler::main_loop()::'lambda1'()> >(void_)  (in Microsoft.VSCode.CPP.Extension.darwin) + 96  [0x10d1dae50]
              2666 vscode::handler_base<message_handler>::main_loop()::'lambda1'()::operator()() const  (in Microsoft.VSCode.CPP.Extension.darwin) + 75  [0x10d1daedb]
                2666 vscode::handler_base<message_handler>::parse_message(vscode::vscode_client_message&&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 60  [0x10d1daf9c]
                  2666 vscode::handler_base<message_handler>::dispatch(vscode::vscode_client_message&&, vscode::vscode_server_message&, bool)  (in Microsoft.VSCode.CPP.Extension.darwin) + 8529  [0x10d1b2ae1]
                    2666 message_handler::C_Cpp_didChangeFolderSettings(vscode::C_Cpp_ConfigurationParams)  (in Microsoft.VSCode.CPP.Extension.darwin) + 612  [0x10d1b9914]
                      2666 message_handler::parse_folder()  (in Microsoft.VSCode.CPP.Extension.darwin) + 285  [0x10d1caa2d]
                        2666 browse_engine::parse_referenced_headers_only()  (in Microsoft.VSCode.CPP.Extension.darwin) + 263  [0x10d1f4577]
                          2666 parser::start(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >_, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >_)  (in Microsoft.VSCode.CPP.Extension.darwin) + 521  [0x10d1fc6f9]
                            2666 parser::add_file(char const_, stat const_, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >_, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >_)  (in Microsoft.VSCode.CPP.Extension.darwin) + 778  [0x10d1fcc4a]
                              2666 parser::update_file_if_needed(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, stat const_, bool)  (in Microsoft.VSCode.CPP.Extension.darwin) + 1487  [0x10d1fd49f]
                                2666 tag_parse(int, char const**, char const_, edge::parse_lang, a_scout_parser_interface_)  (in Microsoft.VSCode.CPP.Extension.darwin) + 65  [0x10d6133f1]
                                  2666 tag_parse(int, char const**, char const_, edge::parse_lang, edge::snapshot_session const_, a_scout_parser_interface_)  (in Microsoft.VSCode.CPP.Extension.darwin) + 670  [0x10d6132de]
                                    2666 perform_antlr_parse(int, char const__, a_scout_parser_interface&, edge::parse_lang)  (in Microsoft.VSCode.CPP.Extension.darwin) + 174  [0x10d612f8e]
                                      2666 edg_main  (in Microsoft.VSCode.CPP.Extension.darwin) + 162  [0x10d32a072]
                                        2666 process_translation_unit  (in Microsoft.VSCode.CPP.Extension.darwin) + 807  [0x10d5ba707]
                                          2666 run_scout_parser  (in Microsoft.VSCode.CPP.Extension.darwin) + 41  [0x10d611699]
                                            2666 scout_parser_base<scout_parser_cpp, scout_parser_cpp_generated, scout_parser_cpp_generatedTokenTypes>::translation_unit()  (in Microsoft.VSCode.CPP.Extension.darwin) + 280  [0x10d611918]
                                              2666 scout_parser_cpp_generated::declarations()  (in Microsoft.VSCode.CPP.Extension.darwin) + 359  [0x10d62f667]
                                                2666 scout_parser_cpp_generated::declaration(a_type_specification&, antlr::TokenRefCountantlr::Token, a_declaration_info const&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 677  [0x10d62fe15]
                                                  2666 scout_parser_cpp_generated::general_declaration_with_error_recovery(a_type_specification&, antlr::TokenRefCountantlr::Token, a_declaration_info const&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 273  [0x10d630a31]
                                                    2666 scout_parser_cpp_generated::general_declaration(a_type_specification&, antlr::TokenRefCountantlr::Token, a_declaration_info const&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 570  [0x10d631eaa]
                                                      2666 scout_parser_cpp_generated::property_or_event_or_simple_declaration(a_type_specification&, antlr::TokenRefCountantlr::Token, a_declaration_info const&)  (in Microsoft.VSCode.CPP.Extension.darwin) + 505  [0x10d633df9]
                                                        2666 scout_parser_cpp_generated::property_or_event_definition(a_type_specification&, antlr::TokenRefCountantlr::Token)  (in Microsoft.VSCode.CPP.Extension.darwin) + 132  [0x10d636844]
                                                          2666 scout_parser_cpp_generated::property_definition(a_type_specification&, antlr::TokenRefCountantlr::Token)  (in Microsoft.VSCode.CPP.Extension.darwin) + 495  [0x10d638c5f]
                                                            1848 std::__1::__wrap_iter<a_declaration_marker const_> get_expression_list_details<scout_parser_cpp>(std::__1::vectorantlr::TokenRefCount<antlr::Token, std::__1::allocatorantlr::TokenRefCount<antlr::Token > > const&, std::__1::__wrap_iter<a_declaration_marker const*>, std::__1::__wrap_iter<a_declaration_marker const*>, a_text_formatting_kind, a_scouted_expression_list**, a_text_buffer_pool_)  (in Microsoft.VSCode.CPP.Extension.darwin) + 557  [0x10d67ec4d]
                                                            ! 1379 edge_host_log_assert(char const_, int)  (in Microsoft.VSCode.CPP.Extension.darwin) + 35,6,...  [0x10d62d703,0x10d62d6e6,...]
                                                            ! 312 edge_host_log_assert(char const_, int)  (in Microsoft.VSCode.CPP.Extension.darwin) + 18  [0x10d62d6f2]
                                                            ! : 312 edge::get_host()  (in Microsoft.VSCode.CPP.Extension.darwin) + 0,4,...  [0x10d5dc440,0x10d5dc444,...]
                                                            ! 157 std::__1::__function::__func<message_handler::init_cmake_parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)::'lambda'(std::__1::shared_ptr<cmake_daemon_comm>), std::__1::allocator<message_handler::init_cmake_parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)::'lambda'(std::__1::shared_ptr<cmake_daemon_comm>)>, void (std::__1::shared_ptr<cmake_daemon_comm>)>::destroy()  (in Microsoft.VSCode.CPP.Extension.darwin) + 1,4,...  [0x10d1bf7b1,0x10d1bf7b4,...]
                                                            817 std::__1::__wrap_iter<a_declaration_marker const_> get_expression_list_details<scout_parser_cpp>(std::__1::vectorantlr::TokenRefCount<antlr::Token, std::__1::allocatorantlr::TokenRefCount<antlr::Token > > const&, std::__1::__wrap_iter<a_declaration_marker const*>, std::__1::__wrap_iter<a_declaration_marker const*>, a_text_formatting_kind, a_scouted_expression_list**, a_text_buffer_pool_)  (in Microsoft.VSCode.CPP.Extension.darwin) + 540,1399,...  [0x10d67ec3c,0x10d67ef97,...]
                                                            1 edge_host_log_assert(char const_, int)  (in Microsoft.VSCode.CPP.Extension.darwin) + 48  [0x10d62d710]

Total number in stack (recursive counted multiple, when >=5):

Sort by top of stack, same collapsed (when >= 5):
        __semwait_signal  (in libsystem_kernel.dylib)        2666
        edge_host_log_assert(char const_, int)  (in Microsoft.VSCode.CPP.Extension.darwin)        1380
        std::__1::__wrap_iter<a_declaration_marker const_> get_expression_list_details<scout_parser_cpp>(std::__1::vectorantlr::TokenRefCount<antlr::Token, std::__1::allocatorantlr::TokenRefCount<antlr::Token > > const&, std::__1::__wrap_iter<a_declaration_marker const*>, std::__1::__wrap_iter<a_declaration_marker const*>, a_text_formatting_kind, a_scouted_expression_list*_, a_text_buffer_pool_)  (in Microsoft.VSCode.CPP.Extension.darwin)        817
        edge::get_host()  (in Microsoft.VSCode.CPP.Extension.darwin)        312
        std::__1::__function::__func<message_handler::init_cmake_parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)::'lambda'(std::__1::shared_ptr<cmake_daemon_comm>), std::__1::allocator<message_handler::init_cmake_parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)::'lambda'(std::__1::shared_ptr<cmake_daemon_comm>)>, void (std::__1::shared_ptr<cmake_daemon_comm>)>::destroy()  (in Microsoft.VSCode.CPP.Extension.darwin)        157

Binary Images:
       0x10d1ad000 -        0x10d721fff +Microsoft.VSCode.CPP.Extension.darwin (0) <B92C812D-9B9E-3512-B3FC-8FF2E151805C> /Users/dengxf/.vscode/extensions/ms-vscode.cpptools-0.9.2/bin/Microsoft.VSCode.CPP.Extension.darwin
       0x113bad000 -        0x113bea267  dyld (0.0 - ???) <87D3A32A-2F19-3DEA-BADD-709929339826> /usr/lib/dyld
    0x7fffad8bc000 -     0x7fffad8bdff3  libSystem.B.dylib (1238) <8FD3EEE6-8D61-39E4-A199-93D3C7037876> /usr/lib/libSystem.B.dylib
    0x7fffad9d5000 -     0x7fffad9d5ff3  libauto.dylib (187) <5BBF6A00-CC76-389D-84E7-CA88EDADE683> /usr/lib/libauto.dylib
    0x7fffad9f6000 -     0x7fffada4cff7  libc++.1.dylib (307.4) <BEE86868-F831-384C-919E-2B286ACFE87C> /usr/lib/libc++.1.dylib
    0x7fffada4d000 -     0x7fffada77fff  libc++abi.dylib (307.2) <1CEF8ABB-7E6D-3C2F-8E0A-E7884478DD23> /usr/lib/libc++abi.dylib
    0x7fffae566000 -     0x7fffae936d97  libobjc.A.dylib (706) <F9AFE665-A3A2-3285-9495-19803A565861> /usr/lib/libobjc.A.dylib
    0x7fffaed80000 -     0x7fffaed84ff7  libcache.dylib (79) <0C8092D3-600F-3ADD-A036-F225B6CDCA43> /usr/lib/system/libcache.dylib
    0x7fffaed85000 -     0x7fffaed90ff7  libcommonCrypto.dylib (60092.30.2) <B77F3EA7-47A2-32AF-A235-1A98B2622477> /usr/lib/system/libcommonCrypto.dylib
    0x7fffaed91000 -     0x7fffaed98fff  libcompiler_rt.dylib (62) <E992E8D9-037C-3454-A366-A25E4D31D6BB> /usr/lib/system/libcompiler_rt.dylib
    0x7fffaed99000 -     0x7fffaeda1fff  libcopyfile.dylib (138) <64E285D9-5485-333B-AEE7-8B0C8FB9275F> /usr/lib/system/libcopyfile.dylib
    0x7fffaeda2000 -     0x7fffaee25fdf  libcorecrypto.dylib (442.30.18) <6825AADB-EC94-3149-9CD4-EEB78CF93723> /usr/lib/system/libcorecrypto.dylib
    0x7fffaee26000 -     0x7fffaee58fff  libdispatch.dylib (703.30.5) <7FA9C970-4B28-33E6-883F-70BC065A7485> /usr/lib/system/libdispatch.dylib
    0x7fffaee59000 -     0x7fffaee5eff3  libdyld.dylib (421.2) <C2EDACC7-67D7-3F7F-AC7E-2C04A2904D97> /usr/lib/system/libdyld.dylib
    0x7fffaee5f000 -     0x7fffaee5fffb  libkeymgr.dylib (28) <1A318923-1200-3B06-B432-5007D82F195D> /usr/lib/system/libkeymgr.dylib
    0x7fffaee6d000 -     0x7fffaee6dfff  liblaunch.dylib (972.30.7) <15FACC21-079A-3BDF-9AFB-4253EFDEB587> /usr/lib/system/liblaunch.dylib
    0x7fffaee6e000 -     0x7fffaee73fff  libmacho.dylib (894) <A2F38EC1-C37C-3B93-B0E4-36B07C177F8C> /usr/lib/system/libmacho.dylib
    0x7fffaee74000 -     0x7fffaee76ff3  libquarantine.dylib (85) <C1D7749F-5F5F-3BB9-BEFC-1F0B9DA941FD> /usr/lib/system/libquarantine.dylib
    0x7fffaee77000 -     0x7fffaee78ffb  libremovefile.dylib (45) <CD42974E-BE0B-39FC-9BFC-8A7540A04DC6> /usr/lib/system/libremovefile.dylib
    0x7fffaee79000 -     0x7fffaee91ff7  libsystem_asl.dylib (349.30.2) <8C6D74A4-55B9-33DC-933E-6A03D9D6D840> /usr/lib/system/libsystem_asl.dylib
    0x7fffaee92000 -     0x7fffaee92ff7  libsystem_blocks.dylib (67) <B8C3701D-5A91-3D35-999D-2DC8D5393525> /usr/lib/system/libsystem_blocks.dylib
    0x7fffaee93000 -     0x7fffaef20fef  libsystem_c.dylib (1158.30.7) <56208CAE-0FEA-3C93-8EDE-0CDE1F956E38> /usr/lib/system/libsystem_c.dylib
    0x7fffaef21000 -     0x7fffaef24ffb  libsystem_configuration.dylib (888.30.2) <4FE3983C-E4ED-3939-A578-03AD29C99788> /usr/lib/system/libsystem_configuration.dylib
    0x7fffaef25000 -     0x7fffaef28fff  libsystem_coreservices.dylib (41.4) <5DBCA81E-28F6-33D6-A8F0-650E9F0F29DB> /usr/lib/system/libsystem_coreservices.dylib
    0x7fffaef29000 -     0x7fffaef41ffb  libsystem_coretls.dylib (121.30.2) <B68F4FD7-9EBA-3FE6-BE75-3E5622772B39> /usr/lib/system/libsystem_coretls.dylib
    0x7fffaef42000 -     0x7fffaef48fff  libsystem_dnssd.dylib (765.30.11) <C284D7C7-8BAF-39E0-8613-FA8C0C81B24F> /usr/lib/system/libsystem_dnssd.dylib
    0x7fffaef49000 -     0x7fffaef72ff7  libsystem_info.dylib (503.30.1) <9ED9121C-F111-3FAD-BC2F-C95DEE1C9362> /usr/lib/system/libsystem_info.dylib
    0x7fffaef73000 -     0x7fffaef95ff7  libsystem_kernel.dylib (3789.30.87) <3013EFC3-FD8D-3ADC-9400-8349D3B2EE2B> /usr/lib/system/libsystem_kernel.dylib
    0x7fffaef96000 -     0x7fffaefddfe7  libsystem_m.dylib (3121.4) <266DB92B-A86F-3691-80FB-1B26AD73CFF3> /usr/lib/system/libsystem_m.dylib
    0x7fffaefde000 -     0x7fffaeffcff7  libsystem_malloc.dylib (116.30.3) <D7A704E0-D645-3D97-B611-B9B327B77AE5> /usr/lib/system/libsystem_malloc.dylib
    0x7fffaeffd000 -     0x7fffaf054ffb  libsystem_network.dylib (856.30.16) <4AE368E9-605D-379D-B04C-2AC7455B8250> /usr/lib/system/libsystem_network.dylib
    0x7fffaf055000 -     0x7fffaf05eff3  libsystem_networkextension.dylib (563.30.14) <2C2C860A-AE29-3609-8E9B-DDA205191081> /usr/lib/system/libsystem_networkextension.dylib
    0x7fffaf05f000 -     0x7fffaf068ff3  libsystem_notify.dylib (165.20.1) <7C9E8EDE-A65F-3138-AEC0-DB7A84CA96CD> /usr/lib/system/libsystem_notify.dylib
    0x7fffaf069000 -     0x7fffaf071fe7  libsystem_platform.dylib (126.1.2) <3CA06D4E-C00A-36DE-AA65-3A390097D1F6> /usr/lib/system/libsystem_platform.dylib
    0x7fffaf072000 -     0x7fffaf07cff7  libsystem_pthread.dylib (218.30.1) <C869ED7C-BE29-3532-8E69-3A8DA1447EDC> /usr/lib/system/libsystem_pthread.dylib
    0x7fffaf07d000 -     0x7fffaf080ff7  libsystem_sandbox.dylib (592.30.14) <2326A0AB-C987-3C3D-BF36-28DD5EE95D6F> /usr/lib/system/libsystem_sandbox.dylib
    0x7fffaf081000 -     0x7fffaf082fff  libsystem_secinit.dylib (24) <5C1F1E47-0F7D-3E25-8DEB-D9DB1F902281> /usr/lib/system/libsystem_secinit.dylib
    0x7fffaf083000 -     0x7fffaf08afff  libsystem_symptoms.dylib (532.30.5) <AA39E3D5-1577-3023-862E-4487292E3619> /usr/lib/system/libsystem_symptoms.dylib
    0x7fffaf08b000 -     0x7fffaf0abff7  libsystem_trace.dylib (518.30.7) <985DB80E-6D01-382C-B6FE-BEED5096EB67> /usr/lib/system/libsystem_trace.dylib
    0x7fffaf0ac000 -     0x7fffaf0b1ffb  libunwind.dylib (35.3) <9F7C2AD8-A9A7-3DE4-828D-B0F0F166AAA0> /usr/lib/system/libunwind.dylib
    0x7fffaf0b2000 -     0x7fffaf0dbff7  libxpc.dylib (972.30.7) <65E41BB6-EBD5-3D93-B0BE-B190CEE4DD93> /usr/lib/system/libxpc.dylib
Sample analysis of process 15273 written to file /dev/stdout

**Comment by bobbrow** [comment]
I don't repro this issue on the pjsip repo anymore.  Please reactivate the issue if you are still seeing excessive CPU usage.

**Comment by ivancuric** [comment]
Still happens, even when no workspaces are open.

**Comment by brennanMKE** [comment]
Thanks @bobbrow!
