### ISSUE TITLE
Cannot run extension C/C++: "Starting client failed"

### ISSUE THREAD

**Issue by yanghanlin** [microsoft/vscode-cpptools#2970]
Issue Type: <b>Bug</b>

The extension C/C++ cannot be run **after upgrading to version 0.21.0-insiders2**.

The last version (0.21.0) runs well.

Way to reproduce:
1. Upgrade the extension C/C++ to version 0.21.0-insiders2 (which may be performed automatically by VSCode - Insiders);
2. Reload the window when VSCode informs you of that the extension has been upgraded and requires you to do so.
3. VSCode will pop up two messages, which read:

> Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Error: spawn UNKNOWN

and

> Couldn't start client cpptools: Codes

while in the output window there appears the information of the error:

> [Error - 下午4:51:09] Starting client failed
> Error: spawn UNKNOWN
> 	at ChildProcess.spawn (internal/child_process.js:357:11)
> 	at Object.spawn (child_process.js:540:9)
> 	at createMessageTransports._getServerWorkingDir.then.serverWorkingDir (<My Personal Folder>\.vscode-insiders\extensions\ms-vscode.cpptools-0.21.0-insiders2\node_modules\vscode-languageclient\lib\main.js:353:40)

Extension version: 0.21.0-insiders2
VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:20:35.852Z)
OS version: Windows_NT x64 10.0.18305

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (1.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
We have lots of users successfully using the 0.21.0-insiders2, so it sounds like some unexpected error has occurred. Can you uninstall 0.21.0-insiders2, restart VS Code, and then either manually install the vsix at https://github.com/Microsoft/vscode-cpptools/releases/download/0.21.0-insiders2/cpptools-win32.vsix (the Install from vsix command) or install 0.20.1 and wait for the auto-update to 0.21.0-insiders (although it sounds like the auto-update is always failing for you?). Maybe the download was incomplete?

**Comment by yanghanlin** [comment]
Thanks for your suggestion, but unfortunately the problem is still not solved.

The auto-update in my VSCode - Insiders is not failing. The version previously installed is 0.20.1 and works pretty well.

I tried uninstalling cpptools and re-installing it from the marketplace, which was version 0.21.0 and worked well. The extension later automatically updated to 0.21.0-insiders2 and then the error appeared again.

I also tried downloading the vsix file from the URL given by you and installed cpptools manually, which 
was version 0.21.0-insiders2 (instead of 0.21.0). The same error occured.

This time in the output window there appears another piece of information:
> [Error - AM 10:50:21] Starting client failed
> Launching server using command c:\Users\\(My Username)\\.vscode-insiders\extensions\ms-vscode.cpptools-0.21.0-insiders2\bin\Microsoft.VSCode.CPP.Extension.exe failed.

Then I found the executable file in the command it failed to execute **does not exist in the folder at all**.

**Comment by sean-mcmanus** [comment]
The Microsoft.VSCode.CPP.Extension.exe file is bundled inside the .vsix (you can see it via renaming the .vsix to a .zip and opening it in Windows Explorer). The auto and manual methods use the same .vsix. VS Code does some caching of extensions so you may need to restart VS Code after doing an uninstall in order for the uninstall to actually work. I have never heard of the Microsoft.VSCode.CPP.Extension.exe process being missing during installation of an insiders vsix before...maybe your virus scan is incorrectly quarantining the file for some reason?

I assume our previous 0.21.0-insiders has the same issue: https://github.com/Microsoft/vscode-cpptools/releases/download/0.21.0-insiders/cpptools-win32.vsix? Are you able to manually install the release offline vsix at https://github.com/Microsoft/vscode-cpptools/releases/download/0.20.1/cpptools-win32.vsix ?

**Comment by yanghanlin** [comment]
Thank you very much for your suggestion. 😀
I have found what has caused the error.
My McAfee LiveSafe has recognized the executable file as a suspected virus and deleted it from my computer.
When it is turned off, the error disappears.

I'm also curious about why this version of cpptools will cause McAfee to suspect that it is a virus.
I think the error may occur to other McAfee users who are also using this extension as well.
(The suspected threat name that McAfee recognized: `JTI/Suspect.196612!c7641b5e0f5f`)

**Comment by sean-mcmanus** [comment]
Yeah, the binaries should not contain any virus signatures or virus-like behavior, etc.. We had a report like this a year ago or so with the McAfee virus scan as well, but I'm not sure if we contacted McAfee or not. It's possible their is something wrong with our Microsoft digital signature we use to build the binaries, which should be the same for insiders and non-insiders, but maybe something with the insiders is triggering the McAfee scan for another reason?

**Comment by sean-mcmanus** [comment]
Okay, thanks for providing the virus signature -- we'll try to figure out what is going on.

**Comment by sean-mcmanus** [comment]
Are you able to tell the McAfee LiveSafe to do a more thorough scan to check if the file actually contains a virus or not? Does the McAfee scan report false positives in other cases for you? Can you report the false positive to McAfee and see what they say?

**Comment by yanghanlin** [comment]
Okay. I'll perform a customized virus scan on this single file.
But I also noticed there's another executable file, named Microsoft.VSCode.CPP.IntelliSense.Msvc.exe, that is not identified as a threat.

**Comment by sean-mcmanus** [comment]
Okay, that is good to know. The other process is our IntelliSense process which is launched from the Microsoft.VSCode.CPP.Extension.exe process after a file is opened -- but if the main process is prevented from executing then maybe the LiveSafe scan isn't run...or maybe it just doesn't match that virus signature for some other reason.

**Comment by yanghanlin** [comment]
I'm sorry that the customized scan cannot provide any other useful information (or I don't know how to get the information).
I uploaded this file to VirusTotal, in which 5 engines including McAfee detected it as a threat.
( https://www.virustotal.com/#/file/494c25e5c737f95fff8f0357d14b5678205ce29e437cac9158858086df858974/detection )

**Comment by yanghanlin** [comment]
I performed another customized virus scan on the file Microsoft.VSCode.CPP.IntelliSense.Msvc.exe with McAfee. This time the file is not detected as a threat.

**Comment by sean-mcmanus** [comment]
Our latest [0.21.0-insiders3](https://github.com/Microsoft/vscode-cpptools/releases) adds the Microsoft digital signature to the binaries, so it should not be incorrectly flagged by your virus scan any more. We had the signature back in 0.13.0 (September 2017), but it got accidentally removed during cleanup of our build processes.

**Comment by yanghanlin** [comment]
Thanks for your effort devoted in investigating this issue. 😀
