### ISSUE TITLE
Language server failed 5 times

### ISSUE THREAD

**Issue by OlegZv** [microsoft/vscode-cpptools#2972]
Issue Type: <b>Language Service</b>

Intelisense doesn't works from time to time. Last time I reinstalled windows to get this working but now I'm getting the same issue, and I seems to be not dependent on the project im using. 
also tried using different version of cpptools 0.17.6 and 0.20.0

```
	[Error - 5:47:25 PM] Connection to server got closed. Server will not be restarted.
[Error - 5:47:25 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\messageWriter.js:57:27)
	at Socket.<anonymous> (C:\Users\user\.vscode\extensions\ms-vscode.cpptools-0.20.1\node_modules\vscode-jsonrpc\lib\messageWriter.js:79:63)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:554:12)
```

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
debug|web|0.22.0

</details>

**Comment by OlegZv** [comment]
Downgrading to 0.17.0 helps..

**Comment by sean-mcmanus** [comment]
0.17.0 is from May 7th, 2018, i.e. not recommended. Are you able to attach a debugger to the crashing Microsoft.VSCode.CPP.Extension.exe process to get a call stack? Does it crash before you open any files? Is there any scenario where you can get it not to crash?

**Comment by OlegZv** [comment]
@sean-mcmanus I'm not sure if I correctly understood how to attached a debugger to the ....CPP.extension.exe, here is what I get when i do debug with VS2017:
`Unhandled exception at 0x012BD0D3 in Microsoft.VSCode.CPP.Extension.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.`

Call stack doesn't look like anything helpful
![image](https://user-images.githubusercontent.com/19969581/50484327-eb243b80-09bd-11e9-8a0b-073eab3aa8a9.png)

Please let me know if that was helpful or I need to perform any other steps to debug. Thanks

The scenario is next - Open VSCode, open any .c or .h file - see crash.
It doesn't crash if I don't open any files.

**Comment by sean-mcmanus** [comment]
Yeah, it looks like you've attached correctly -- you just need to obtain the symbols from the Microsoft symbol server. This could be the bug described at https://github.com/Microsoft/vscode-cpptools/issues/2969 related to our calling fsutil with a different code page.

Using VS, Debug->Options->Symbols.
![image](https://user-images.githubusercontent.com/19859882/50493737-4a8d4600-09d4-11e9-95ca-ea5382072324.png)

Using VS Code, launch.json
![image](https://user-images.githubusercontent.com/19859882/50493835-c6878e00-09d4-11e9-9f03-58eb87ca8f50.png)

**Comment by OlegZv** [comment]
Thanks for the detailed answer. Now VS was able to load almost all the symbols,except for:
```
'Microsoft.VSCode.CPP.Extension.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sysfer.dll'. Cannot find or open the PDB file.
'Microsoft.VSCode.CPP.Extension.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ctiuser.dll'. Cannot find or open the PDB file.
```
I did also config for VS Code, but that doesn't seem to change anything.. Debugging still gives me:
`Unhandled exception at 0x005AD0D3 in Microsoft.VSCode.CPP.Extension.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.`

**Comment by sean-mcmanus** [comment]
Are you able to see a call stack for the crash once the symbols are loaded in VS?

We have fixed one crash that could be causing this for our next release, but without a call stack I'm not sure if this is the same crash or not.

**Comment by elcojacobs** [comment]
I am trying to use cquery with vscode but cquery seems to die continuously with a jsonrpc error `(   0.758s) [stdin        ]            lsp.cc:205   | Bad or missing jsonrpc version`. I assume because the language server is not responding as expected.
This is on ubuntu 18 (KDE Neon 5.14).

If I could help you find the cause of the crashes, I would gladly do so. But I don't know where to start.

My relevant settings in vscode:

```
  "C_Cpp.autocomplete": "Disabled",
  "C_Cpp.formatting": "Disabled",
  "C_Cpp.errorSquiggles": "Disabled",
  "C_Cpp.intelliSenseEngine": "Disabled",
  "cquery.highlighting.enabled.types": true,
  "cquery.highlighting.enabled.freeStandingFunctions": true,
  "cquery.highlighting.enabled.memberFunctions": true,
  "cquery.highlighting.enabled.freeStandingVariables": true,
  "cquery.highlighting.enabled.memberVariables": true,
  "cquery.highlighting.enabled.namespaces": true,
  "cquery.highlighting.enabled.macros": true,
  "cquery.highlighting.enabled.enums": true,
  "cquery.highlighting.enabled.typeAliases": true,
  "cquery.highlighting.enabled.enumConstants": true,
  "cquery.highlighting.enabled.staticMemberFunctions": true,
  "cquery.highlighting.enabled.parameters": true,
  "cquery.highlighting.enabled.templateParameters": true,
  "cquery.highlighting.enabled.staticMemberVariables": true,
  "cquery.highlighting.enabled.globalVariables": true,
  "cquery.cacheDirectory": "${workspaceFolder}/.vscode/cquery_cached_index/",
  "cquery.launch.command": "/home/elco/opt/cquery/build/release/bin/cquery",
``` 

Latest version of vscode-cpptools (0.21.0) and cquery compiled from latest source.

**Comment by Colengms** [comment]
Closing this crasher issue due to inactivity for the last 10 months.  If you're still seeing this issue, please let us know.

**Comment by elcojacobs** [comment]
I switched to ccls instead of cquery and have not had any issues recently. :)
