### ISSUE TITLE
Disable /Library/Developer/CommandLine Tools for Peek/Goto

### ISSUE THREAD

**Issue by Pusnow** [microsoft/vscode-cpptools#2979]
Hi,
I'm currently developing a linux system program in macOS.
I've copied all linux headers to my local computer and set `includePath` to the directory.
However, whenever I use Peek/Goto, there are Mac related headers.
Is there any way to disable them?

My `c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "~/Headers/**"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64",
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 4
}
```

<img width="804" alt="2018-12-29 6 36 08" src="https://user-images.githubusercontent.com/6031017/50536516-9e488c80-0b98-11e9-9173-b842cb66f2c5.png">

**Comment by sean-mcmanus** [comment]
I think this is a duplicate of https://github.com/Microsoft/vscode-cpptools/issues/2564 . Our implementation of Go to Def for #include just needs to be improved. A possible workaround would be to add the folders you don't care about to the files.exclude setting.

**Comment by bobbrow** [comment]
The Mac system headers are included because `"compilerPath"` is not being set in `c_cpp_properties.json`.

I would recommend you set the `"compilerPath"` property to the compiler you're using and remove `"~/Headers/**"` from your `"includePath"`.  This will ensure the the system include path is configured correctly.

**Comment by Pusnow** [comment]
Setting the `"compilerPath"` to `""` solves this issue.
Thanks.
