### ISSUE TITLE
 IntelliSense-based Go to Definition failed

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#2981]
**Type: LanguageService**

**To Reproduce**

1. create `apue.h` ( All files are in the top directory)
```c
typedef int ssize_t;
typedef unsigned int size_t;

int test(int fd, ssize_t (*callback)(int, const void *, size_t));
int test2(int fd, int (*callback)(int, const void *, int));
```
2. create `apue.c`
```c
#include "apue.h"

int test(int fd, ssize_t (*callback)(int, const void *, size_t)) {

}

int test2(int fd, int (*callback)(int, const void *, int)) {

}
```
3. create `main.c`
```c
#include "apue.h"

ssize_t callback(int a, const void *b, size_t c) {
    return 0;
}

int callback2(int a, const void *b, int c) {
    return 0;
}

int main(void) {
    test(1, callback); // Go to Definition failed. (Only jumped to the Declaration)
    test2(1, callback2); // Go to Definition works fine.
}
```

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. A fix should be released in our next (Insiders?) release, we'll try for Wednesday, but it could get delayed.

**Comment by sean-mcmanus** [comment]
Our latest [0.21.0-insiders3](https://github.com/Microsoft/vscode-cpptools/releases) has fixed IntelliSense-based Go to Definition with function pointer parameters.

Setting `C_Cpp.updateChannel` to `"Insiders"` is another way to get the update.
