### ISSUE TITLE
Remote debugging - Debug server not started

### ISSUE THREAD

**Issue by HorstBaerbel** [microsoft/vscode-cpptools#2982]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 18.04.01
- VS Code Version: 1.30.01
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them):
Everything disabled, except:
CMake
CMake Tools
Visual Studio keymap
- A clear and concise description of what the bug is.
When starting "remote" debugging on a local machine it does not work from VS Code, but the same commands work from the command line. The launch.json launches an emulator that includes a GDB server. Then GDB attaches to that. Issuing:

> mgba-qt -2 -g ${workspaceFolder}/build/target.gba

(opens GBD server on localhost:2345) and then:

> $DEVKITARM/bin/arm-none-eabi-gdb

then in GDB:

> file ${workspaceFolder}/build/target.elf
> target remote localhost:2345
> continue

the executable runs as expected (workspaceFolder is manually replaced by the correct path). I've tried fiddling around with the launch.json for a couple of hours now, read several related issues here etc., but just can't get it to work from VS Code. The emulator starts and waits for a connection, but nothing connects. Other debug configurations that just start the emulator and run the executable work fine. I do compile with "-g" and the environment variables used are properly set.
Please note that the "program" setting is not necessary in this context, but can not be omitted. There is a feature request open for that afaik. 

**To Reproduce**
Hit F5 to start debugging.

**Additional context**
launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
         {
            "name": "Debug target in mgba",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "build Debug",
            "program": "${workspaceFolder}/build/target.elf",
            "debugServerPath": "/usr/bin/mgba-qt",
            "debugServerArgs": "-2 -g ${workspaceFolder}/build/target.gba",
            //"miDebuggerServerAddress": "localhost:2345",
            "cwd": "${workspaceRoot}/build",
            //"stopAtEntry": false,
            "MIMode": "gdb",
            "miDebuggerPath": "${env:DEVKITARM}/bin/arm-none-eabi-gdb",
            "setupCommands": [
                //{"text": "set print pretty", "ignoreFailures": true},
                {"text": "file ${workspaceFolder}/build/target.elf", "ignoreFailures": true}, 
                {"text": "target remote localhost:2345", "ignoreFailures": true}, 
                //{"text": "monitor reset init", "ignoreFailures": true}
                //{"text": "continue", "ignoreFailures": true}
            ]
            //"externalConsole": false
            //, "showDisplayString": true
            , "logging": {
                "traceResponse": true,
                "moduleLoad": true,
                "trace": true,
                "engineLogging": true,
                "programOutput": true,
                "exceptions": true
            },
         } ]
}
```
Debug console output:

> --> E (output): {"event":"output","body":{"category":"console","output":"1: (143) LaunchOptions>\n"},"seq":20,"type":"event"}
> 1: (143) LaunchOptions>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (143) LaunchOptions    <SetupCommands>\n"},"seq":22,"type":"event"}
> 1: (143) LaunchOptions    <SetupCommands>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (143) LaunchOptions        <Command IgnoreFailures='true' Description=''>file /home/mememe/Programmieren/GameBoy/target/build/target.elf</Command>\n"},"seq":24,"type":"event"}
> 1: (143) LaunchOptions        <Command IgnoreFailures='true' Description=''>file /home/mememe/Programmieren/GameBoy/target/build/target.elf</Command>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (143) LaunchOptions        <Command IgnoreFailures='true' Description=''>target remote localhost:2345</Command>\n"},"seq":26,"type":"event"}
> 1: (143) LaunchOptions        <Command IgnoreFailures='true' Description=''>target remote localhost:2345</Command>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (144) LaunchOptions    </SetupCommands>\n"},"seq":28,"type":"event"}
> 1: (144) LaunchOptions    </SetupCommands>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (144) LaunchOptions</LocalLaunchOptions>\n"},"seq":30,"type":"event"}
> 1: (144) LaunchOptions</LocalLaunchOptions>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (268) Starting: \"/usr/bin/mgba-qt\" -2 -g /home/mememe/Programmieren/GameBoy/target/build/target.gba\n"},"seq":32,"type":"event"}
> 1: (268) Starting: "/usr/bin/mgba-qt" -2 -g /home/mememe/Programmieren/GameBoy/target/build/target.gba
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (10289) <-logout\n"},"seq":34,"type":"event"}
> 1: (10289) <-logout
> --> E (output): {"event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.51030.1","VS.Diagnostics.Debugger.HostVersion":"14.0.51030.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.ErrorCode":1005,"VS.Diagnostics.Debugger.Launch.IsError":true}},"seq":36,"type":"event"}
> --> R (launch-2): {"request_seq":2,"success":false,"command":"launch","message":"Unable to start debugging. Debug server process failed to initialize.","body":{"error":{"id":1005,"format":"Unable to start debugging. Debug server process failed to initialize."}},"seq":38,"type":"response"}

**Comment by HorstBaerbel** [comment]
I upgraded to VSCode 1.33.1 in the meantime.
This does "work" with a imo half-baked workaround. I opened an issue for mgba [here](url) and @paeolo replied with a comment. The workaround is to install the "Native debug" extension and set up your launch.json:
```
{
    "name": "Debug gbatv in mgba",
    "type": "gdb",
    "gdbpath": "${env:DEVKITARM}/bin/arm-none-eabi-gdb",
    "request": "attach",
    "executable": "${workspaceFolder}/build/foo.elf",
    "target": "localhost:2345",
    "remote": true,
    "cwd": "${workspaceRoot}/build",
    "valuesFormatting": "parseText",
    "preLaunchTask": "run Debug",
    "postDebugTask": "kill Debug"
}
```
and tasks.json:
```
{
    "label": "build Debug",
    "type": "shell",
    "command": "cmake --build ${workspaceRoot}/build --config Debug --target foo.gba -- -j 4",
    "options": {
        "cwd": "${workspaceRoot}"
    },
    "group": {
        "kind": "build",
        "isDefault": true
    }
},
{
    "label": "run Debug",
    "dependsOn": [
        "build Debug"
    ],
    "type": "shell",
    "command": "mgba-qt",
    "args": [
        "-2",
        "-g",
        "${workspaceFolder}/build/foo.elf"
    ],
    "presentation": {
        "echo": false,
        "reveal": "never",
        "clear": false,
        "showReuseMessage": false
    },
    "isBackground": true,
    "problemMatcher": [
        {
            "pattern": [
                {
                    "regexp": ".",
                    "file": 1,
                    "location": 2,
                    "message": 3
                }
            ],
            "background": {
                "activeOnStart": true,
                "beginsPattern": ".",
                "endsPattern": ".",
            }
        }
    ]
},
{
    "label": "kill Debug",
    "type": "process",
    "command": [
        "${command:workbench.action.tasks.terminate}",
        "${command:workbench.action.acceptSelectedQuickOpenItem}"
    ]
}
```
There are some caveats. You have to press enter to kill the "run Debug" task after finishing debugging (the "acceptSelectedQuickOpenItem" does not work btw) and it only works a couple of times until something gets stuck and subsequent attempts to start debugging fail consistently. They fail to the extent that only logging out / in or even rebooting solves the problem. One time VSCode blocked my whole machine (mouse was working, key input not) and I had to CTRL+ALT+F3 to go another console and pkill code... :/

**Comment by tichun** [comment]
I have got this problem, too, and only under Linux:

- when running task manually, the debugger can just connect to it, no problems.

- if some task is set as "preLaunchTask" then the debugger won't even start, as it waits for task to exit even though task is set as "isBackground", and adding "problemMatcher" doesn't help - when problem is matched, the "preLaunchTask" instantly exits, even though it "isBackground".
