### ISSUE TITLE
Completely crashes every time I try to add nodejs/src to includePath

### ISSUE THREAD

**Issue by magnus-trent** [microsoft/vscode-cpptools#2987]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them):
- Developing nodejs addons, I tried to add the nodejs/src directory to access the node.h and other header files and was met with crashes nonstop. I tried "C:/NodeJS/src/**" which didn't work. So I tried "C://NodeJS//src//**" and it crashed. 

**Expected behavior**
Directory and header files are loaded.

**Comment by sean-mcmanus** [comment]
What crashes? What error do you see? Where is this path being used? Is this a bug with VS Code or the C/C++ extension?

Using "//" should never be a valid path. Maybe you meant `"\\"`? Our extension should normally accept "/" (or `\\`) in paths. It's possible we have a problem with "//" since that is unexpected input.

**Comment by magnus-trent** [comment]
I got it to work thankfully. However, I used the wrong slash and that's what crashed it. Specifically, using "//" will cause the server to restart 5 times and Ultimately fail. Forcing you to restart VS Code entirely. So although it was my mistake, I do recommend trying to find out why "//' causes such a crash.

**Comment by sean-mcmanus** [comment]
Where did you add the path with "//"? I found/fixed a crash when "//" is used with "//**" in includePath. Is that the same one you hit?

**Comment by sean-mcmanus** [comment]
Our latest [0.21.0-insiders3](https://github.com/Microsoft/vscode-cpptools/releases) has fixed the crash when "//" is used.

Setting `C_Cpp.updateChannel` to `"Insiders"` is another way to get the update.

**Comment by magnus-trent** [comment]
Sorry for such a late response. Yes that's what seemed to crash it pretty hard.
