### ISSUE TITLE
Bad coloring of block comments that are preceded by an asterisk

### ISSUE THREAD

**Issue by dan1994** [microsoft/vscode-cpptools#2988]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 17134
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1
- When putting a block comment right after an asterisk (when example when using a pointer), there's a red syntax coloring for the rest of the line. This appears to be caused because the `*/*` is captured as end of block comment instead of asterisk followed by start of block comment.

**To Reproduce**
Write in an open cpp file:
`void */*comment*/ var;`

**Expected behavior**
The comment should be identified and colored correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/6225230/50578582-ab5fb880-0df0-11e9-913c-307bc7720799.png)

**Comment by sean-mcmanus** [comment]
Our extension doesn't actually provide the colorization. It is implemented in VS Code itself via using the atom/language-c module. I've created a bug at https://github.com/atom/language-c/issues/315 .

**Comment by sean-mcmanus** [comment]
This appear to be fixed with the latest VS Code. Let us know if you're still seeing it.

**Comment by sean-mcmanus** [comment]
Oh, the fix hasn't been ported to Insiders yet -- you can install the Better C++ Syntax extension for that fix. I'll close this after the fix gets moved.

**Comment by Colengms** [comment]
This looks to be fixed in VS Code.

**Comment by dan1994** [comment]
Sorry for the late reply, but this issue seems to still be relevant. This is the info of my current setup:
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

This is what I see:
![image](https://user-images.githubusercontent.com/6225230/61595255-7e90b880-abfd-11e9-80b2-b6f867767e2a.png)

**Comment by matter123** [comment]
@dan1994 This is because with VS Code 1.36.1 The C syntax was rolled back to an earlier version of the upstream textmate grammar. Installing the previously mentioned [Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) extension should fix the issue.

![Screenshot from 2019-07-21 22-43-14](https://user-images.githubusercontent.com/714007/61608845-1b0c8800-ac09-11e9-9931-6953566a6a35.png)

**Comment by dan1994** [comment]
This seems to solve the problem. Thank you!
I do want to ask out of curiosity: Is it not desired that the coloring will work correctly without relying on other plugins?

**Comment by matter123** [comment]
Better C++ Syntax is the same grammar that VS Code uses for C and C++ syntax highlighting. The extensions is just the latest version of the grammar.

**Comment by dan1994** [comment]
To my understanding the syntax coloring Iv'e seen comes from either the cpptools extension or VS code itself. Why then, are there two different coloring schemes? Why is the coloring in Better C++ Syntax not integrated into VS Code/cpptools? Or, from a different perspective, why do I get syntax coloring w/o installing the Better C++ Syntax if that's the extension that should be responsible for it.

Sorry if my questions are out of place, I truly just seek to understand.

**Comment by matter123** [comment]
VS Code bundles an older version of Better C++ Syntax, see https://github.com/microsoft/vscode/blob/1.36.1/extensions/cpp/cgmanifest.json#L8. The version bundled has the above bug.

The C/C++ extensions adds its own enhanced colorization on top of the syntax highlighting provided.

**Comment by dan1994** [comment]
Thanks for the clarification 👍
