### ISSUE TITLE
I think this plugin open a large number of powershell processes and take up memory until it runs out.

### ISSUE THREAD

**Issue by zhangchievil** [microsoft/vscode-cpptools#2989]
When I use this plugin with my vscode, it will open a large number of powershell processes, oh and a lot conhost.exe there.
I have tried so many times, disabled all the other plugins, that i'm sure it's this plugin which use all my idle memory after a few hours later.
My system is windows 7, and the newest vscode. the plugin version is 0.20.1.
I think there is some thing wrong with the plugin or my settings?

**Comment by sean-mcmanus** [comment]
It was fixed for https://github.com/Microsoft/vscode-cpptools/issues/2822 . You can get the fix by changing your C_Cpp.updateChannel to "Insiders" to get our Insider build or you can manually download/install the vsix.
