### ISSUE TITLE
Question about embedded systems debugger.

### ISSUE THREAD

**Issue by Aukstkalnis** [microsoft/vscode-cpptools#299]
I want to be able to debug embedded systems with VSCode debugger. My code is written in C. I have debugger tools ulink and st-link v2. They have command line interface for code debugging. I am using Keil uvision 4 compiler. My question is: How to attach these tools to vscode debugger? Do I need some sync between obj and code?  Can you provide my with info on how to do that?
Thank you.

**Comment by delmyers** [comment]
@Aukstkalnis, this debugger uses gdb or lldb as its underlying debugger via the mi protocol. If your embedded systems can talk over the mi protocol, then this should be possible. @paulmaybee has had some success with iot devices. Maybe he can help out.

**Comment by robotdad** [comment]
@Aukstkalnis were you ever successful here? Here is [a launch.json I've used with an mbed board that uses stlink](https://gist.github.com/robotdad/28c60c77e8b39eeee73c65dc8234df69). You need to start openocd or whatever your debug bridge is that presents the gdbserver before launching.

**Comment by Aukstkalnis** [comment]
Well, I was searching the web and found something called PlatformIO. It has IDE like environment for VS Code and debugger is included via Native Debugger extension. So I think I have found the answer for this question. Case can be losed :)
