### ISSUE TITLE
Impossible to disable auto-completion of brackets and double-quotes pairs

### ISSUE THREAD

**Issue by amorulartei** [microsoft/vscode-cpptools#2990]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux Mint 19 Cinnamon
- VS Code Version: 1.29.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): Python, (it persists)
- A clear and concise description of what the bug is.
This is more of a feature request. I would like to have the ability to turn off auto-completion of brackets and double quotes pair upon typing { and ". This is interfering a lot with my typing and I am unable to get used to it after using Visual Studio Code for 2 months. If you can point me to the right place where this is being done in the extension code, so that I can disable it there, that would also work for me.

**To Reproduce**

1. Go to any cpp or c file, and press { or ". Result: } or another " is inserted automatically after the first.

**Expected behavior**
No extra characters should be inserted.

**Comment by sean-mcmanus** [comment]
Is changing the editor.autoClosingBrackets and editor.autoClosingQuotes settings an acceptable solution for you?

**Comment by amorulartei** [comment]
Yes, it is the solution I was looking for. Thank you!
Is there a list somewhere, with all the supported settings?

**Comment by sean-mcmanus** [comment]
You can do File->Preferences->Settings and search or click the Open Settings (JSON) button in the top right to see a list in JSON.

**Comment by amorulartei** [comment]
Thank you, I can see it now! Much appreciated!
