### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by adumont** [microsoft/vscode-cpptools#2991]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.20.1`
- OS Version: `Linux x64 4.4.0-140-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/adumont/ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/2722274/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
What process is using high CPU? Does this occur when open a smaller workspace folder? Does it occur before you open a file? A certain amount of high CPU usage is normal. The logs you provided are for VS Code itself using high CPU and are not helpful to us. If you attach and break into a debugger to the process that is using high CPU and provide a call stack then that would let us know what is going on.

**Comment by adumont** [comment]
Hi Sean, I opened the issue using the "Report Issue" button on the "C/C++" line of the VScode page "Running Extensions" which showed me that this extension was having a performance issue. I don't know if it's very relevant issue. For me it's not a deal breaker. I understand VSCode flags the extension at startup if it takes more than some threshold ms to start.
How can I see what process it is? (is it not "vscode" process?)
I'll try on a small workspace, as this one had multiple projects (6-7 I think).

BTW: I don't think I am even using the C/C++ extension at all in any of this (none are C/C++ projects IIRC), if there is it is probably a very small Arduino project (with very few C/C++ small files).
I guess this extension was installed probably as a dependency of the Arduino extension, as I don't recall installing it on purpose.

**Comment by sean-mcmanus** [comment]
The "Include my currently running processes" option in the Report Issue dialog box has some of the info we would need:

![image](https://user-images.githubusercontent.com/19859882/50657594-c72ba180-0f4b-11e9-9611-1994fe568fea.png)

i.e. the process that is using the CPU. You could also use whatever task/process viewer you have on Linux.

Our extension won't be activated unless a .vscode/c_cpp_properties.json file exists, or a C/C++ file is opened, so those are the only expected cases where CPU usage would be high from our extension. If you see a database icon or red flame in the bottom right corner then our extension has been activated.

**Comment by adumont** [comment]
Right after staring VScode, with a Workspace of 8 small projects, none of
them being C/C++, and none of them containing the
.vscode/c_cpp_properties.json, oddly enough, if I open the Running
Extentions window, I can again see the C/C++" as as Unresponsive.

In my case, maybe because I'm on Linux, when I click on the Report Issue
button, I get no dialog, and I cannot Include my current running processes,
it just opens a browser, opens a new issue on your repo, and fill in some
information (which is what I did yesterday, which created this issue).

**Comment by adumont** [comment]
I've noticed that I also have the Arduino extension loaded, while I have no
Arduino project in this workspace, so I have disabled the Arduino extension
in this workspace, reloaded vscode, and: no more Arduino, nor C/C++
extension loaded this time!

So I guess the C/C++ extension is called/triggered by the Arduino
extension. The Arduino extension itself shouldn't load (but maybe it's
poorly designed and will always load?).

**Comment by sean-mcmanus** [comment]
The Arduino extension appears to have a bug in that the "activationEvents" in the package.json contains a `"*"`, which doesn't make sense given the other entries in the list, which essentially would be ignored. The "*" is causing the extension to always be activated, even for non-Arduino or C/C++ projects. Our extension has better activation events, but it looks like we're being activated due to the dependency.

Fortunately, we implement a secondary activation for our language service process, so the CPU using Microsoft.VSCode.CPP.Extension.exe process shouldn't be launched until a "real" activation occurs, via opening a C/C++ or invoking some C/C++ command.

I'm not able to repro the "Unresponsive" issue on Linux. Do you have any other ideas what could be triggering this? How do you know that the "Unresponsive" means there is a CPU usage issue?  Also, can you open your "System Monitor" or similar utility to see what process is using the CPU?

![image](https://user-images.githubusercontent.com/19859882/50661656-a289f680-0f58-11e9-9d43-2bc58d79fd8d.png)

**Comment by adumont** [comment]
After re-enabling the Arduino extension on the workspace, and restarting
vscode, the cpp extension isn't Unresponsive anymore (at least I have tried
several time and it doesn't happen anymore.

What I don't understand is, in the Output window, when I select "Log
(Extension host)", it shows:

[2019-01-04 00:24:55.842] [exthost] [info] extension host started
[2019-01-04 00:24:55.932] [exthost] [info]
ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":
true,"activationEvent":"*"}
[2019-01-04 00:24:55.932] [exthost] [info]
ExtensionService#loadCommonJSModule
/usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2019-01-04 00:24:55.944] [exthost] [info]
ExtensionService#_doActivateExtension vscode.emmet {"startup":true,
"activationEvent":"*"}
[2019-01-04 00:24:55.944] [exthost] [info]
ExtensionService#loadCommonJSModule
/usr/share/code/resources/app/extensions/emmet/dist/extension
[2019-01-04 00:24:56.002] [exthost] [info]
ExtensionService#_doActivateExtension vscode.git {"startup":true,
"activationEvent":"*"}
[2019-01-04 00:24:56.002] [exthost] [info]
ExtensionService#loadCommonJSModule
/usr/share/code/resources/app/extensions/git/dist/main
[2019-01-04 00:24:56.264] [exthost] [info]
ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,
"activationEvent":"*"}
[2019-01-04 00:24:56.265] [exthost] [info]
ExtensionService#loadCommonJSModule
/usr/share/code/resources/app/extensions/merge-conflict/dist/extension
[2019-01-04 00:24:56.281] [exthost] [info]
ExtensionService#_doActivateExtension eamodio.gitlens {"startup":true,
"activationEvent":"*"}
[2019-01-04 00:24:56.281] [exthost] [info]
ExtensionService#loadCommonJSModule
/home/adumont/.vscode/extensions/eamodio.gitlens-9.3.0/dist/extension
[2019-01-04 00:24:56.595] [exthost] [info]
ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":true,
"activationEvent":"*"}
[2019-01-04 00:24:56.595] [exthost] [info]
ExtensionService#loadCommonJSModule /home/adumont/.vscode/extensions/ms-
vscode.cpptools-0.20.1/out/src/main
[2019-01-04 00:24:57.364] [exthost] [info]
ExtensionService#_doActivateExtension yzhang.markdown-all-in-one {"startup":
true,"activationEvent":"workspaceContains:README.md"}
[2019-01-04 00:24:57.364] [exthost] [info]
ExtensionService#loadCommonJSModule /home/adumont/.vscode/extensions/yzhang.
markdown-all-in-one-1.8.0/out/src/extension
[2019-01-04 00:24:57.699] [exthost] [info]
ExtensionService#_doActivateExtension vsciot-vscode.vscode-arduino {
"startup":true,"activationEvent":"*"}
[2019-01-04 00:24:57.699] [exthost] [info]
ExtensionService#loadCommonJSModule /home/adumont/.vscode/extensions/vsciot-
vscode.vscode-arduino-0.2.24/out/src/extension
[2019-01-04 00:24:59.289] [exthost] [info] eager extensions activated

Am I interpreting incorrectly when I read that ms-vscode.cpptools was
activated at 00:24:56.595 which happens _before_ vscode-arduino being
activated (at 00:24:57.699, so about 1 sec later).

Also, the cpptools extensions line also says: with "activationEvent":"*",
(like the vscode-arduino).

To answer your question about what lead me to diagnose "high cpu load", I
simply didn't. As I told you, the issue was created like that when I
pressed the "Report Issue" button. All the text of the first post was
already filled in by vscode "Report Issue" button. :( Sorry for all the
trouble. I guess we can close the issue.

**Comment by bobbrow** [comment]
cpptools ships with `"activationEvent": "*"` to force downloading of our dependencies immediately on installation.  It then changes the activation events to a narrower scope for subsequent launches.

**Comment by bobbrow** [comment]
This issue was addressed by moving to webpack for our TypeScript sources.
