### ISSUE TITLE
unable to debug with gdb

### ISSUE THREAD

**Issue by JWleo** [microsoft/vscode-cpptools#2993]
system:fedora 28.0
vscode:1.30
![screenshot from 2019-01-03 17-56-41](https://user-images.githubusercontent.com/32316654/50631962-4c7d7900-0f81-11e9-8203-9bdd3efebde9.png)

![screenshot from 2019-01-03 18-01-33](https://user-images.githubusercontent.com/32316654/50632066-a8480200-0f81-11e9-99a7-7c3b78e1fd5c.png)

problem:
![screenshot from 2019-01-03 17-57-44](https://user-images.githubusercontent.com/32316654/50631975-530bf080-0f81-11e9-8334-acc6ba3ab5ad.png)

**Comment by WardenGnaw** [comment]
Please update the cpptools extension to the [latest insiders](https://github.com/Microsoft/vscode-cpptools/releases/tag/0.21.0-insiders2) and let me know if you are still experiencing this issue.

**Comment by JWleo** [comment]
@WardenGnaw It works!
But each time i start to debug, the number of gnome-terminal adds one.
so strange!
