### ISSUE TITLE
"too many errors for the IntelliSense engine to function properly" when working on Qt project

### ISSUE THREAD

**Issue by ianbrault** [microsoft/vscode-cpptools#2999]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Mojave 10.14
- VS Code Version: Version 1.30.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I am adding Qt to a project and when adding includes for Qt headers I get the error message "There are too many errors for the IntelliSense engine to function properly, some of which may not be visible in the editor." Removing the includes removes the error message.

I have tried setting my "includePath" to no luck. I found [issue 2252](https://github.com/Microsoft/vscode-cpptools/issues/2252) which seems like a similar issue but I am getting a different error message.

**To Reproduce**

*The most actionable issue reports include a code sample including configuration files such as c_cpp_properties.json*

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/Users/ianbrault/Qt/5.12.0/clang_64/include"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "configurationProvider": "vector-of-bool.cmake-tools",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Expected behavior**

The program builds correctly so I would expect no errors to be present and IntelliSense to function correctly.

**Screenshots**

<img width="533" alt="screen shot 2019-01-03 at 3 42 47 pm" src="https://user-images.githubusercontent.com/18159197/50667519-8002d800-0f6e-11e9-940f-489460499192.png">

**Additional context**

**Comment by sean-mcmanus** [comment]
Our error limit is 25000, so this is unusual to be hit.

If you [enable Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and look at the output that occurs after you open a new C/C++ file, you can check whether the compiler, includes, and defines appear as expected or not.

It's strange that you have an include path, compilerCommands, and configurationProvider set because those all mutually exclusive sources of configuraiton, although include path will be used as a fallback if a source file isn't listed in the compile commands.

**Comment by ianbrault** [comment]
My apologies, the issue was coming from having the `configurationProvider` set. Removing that setting removed the issue.

**Comment by sean-mcmanus** [comment]
That's fine -- we have plans to improve the configuration experience so things like this are easier to figure out.
