### ISSUE TITLE
"Go to Symbol in Workspace" stops working in non-C/C++ files when this extension is installed

### ISSUE THREAD

**Issue by smarter** [microsoft/vscode-cpptools#300]
I'm running Ubuntu 16.10, and here is the behavior I observe after installing and enabling this extension:
- open any non-C/C++ file (say, a typescript file)
- do `Ctrl+T`
- Start typing
- As long as you type one or two characters, everything is fine
- As soon as you type at least three characters, vscode displays a small bouncing progress bar and stops displaying any result
- Once this has happened, any new `Ctrl+T` query, even if it's only one or two characters long, will display the bouncing progress bar and no result.
- This behaviour stops if vscode is restarted of if vscode-cpptools is uninstalled

A very simple way to workaround this problem would be to change the `activationEvents` of this extension which is currently set to `*` and thus always active.

**Comment by greazer** [comment]
Hi smarter. Yep, this is a known issue that we plan on addressing in an upcoming release -- very likely the next one.
