### ISSUE TITLE
code about "go to declaration"

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3000]
Recently I have been learning the open-source code about cpptools. But I didn't find any code about function 'go to declaration'. There are no any records about local variables in the cpptools database, either. So I wonder where this function is implemented and it's open-source?

**Comment by sean-mcmanus** [comment]
The implementation is mostly in the closed-source code that builds the Microsoft.VSCode.CPP.Extension.exe -- the code is closed source because it is dependent on code shared with VS in order to build (VS is a mostly non-open source, paid product, unlike VS Code) as well as the licensed EDG parser (https://www.edg.com/).

**Comment by Lennon925** [comment]
> The implementation is mostly in the closed-source code that builds the Microsoft.VSCode.CPP.Extension.exe -- the code is closed source because it is dependent on code shared with VS in order to build (VS is a mostly non-open source, paid product, unlike VS Code) as well as the licensed EDG parser (https://www.edg.com/).

Thanks for your reply.

**Comment by Lennon925** [comment]
> The implementation is mostly in the closed-source code that builds the Microsoft.VSCode.CPP.Extension.exe -- the code is closed source because it is dependent on code shared with VS in order to build (VS is a mostly non-open source, paid product, unlike VS Code) as well as the licensed EDG parser (https://www.edg.com/).

Hi sean-mcmanus,
If as you said, it's also impossible to fix issues about 'go to declaration' for other developers. What we can do is to find issues to submit them to you and wait for fixing, right?
In addition, is it possible to control cpptools when to update the symbols database in cpptools extension or vscode codes?

best regards,
Lennon

**Comment by Lennon925** [comment]
@sean-mcmanus

**Comment by Lennon925** [comment]
@sean-mcmanus @delmyers @martinwoodward @Jaxkr 

any update?

**Comment by sean-mcmanus** [comment]
Yeah, file bugs and feature requests to us and/or upvote existing issues. Bugs that are really quick/easy to fix we can usually get into the next Insider release, but more time consuming bugs could get stuck on our backlog for a while if we don't view them as having a high enough priority.

We don't have a feature that controls when the symbol database is updated, other than "pause parsing" command. You could file a feature request for that.
