### ISSUE TITLE
compiled a.exe won't execute

### ISSUE THREAD

**Issue by matgus72** [microsoft/vscode-cpptools#3003]
Hi,

I created a simple HelloWorld project. Compiled it with VS code with the GCC compiler, and the a.exe file was generated. But when I try to run it, it seems like it cannot be opened.

What could be the issue?

Thanks,
/MatGus72

---

PS C:\VSC_projects\HelloWorld> .\a.exe
Program 'a.exe' failed to run: Åtkomst nekadAt line:1 char:1
+ .\a.exe
+ ~~~~~~~.
At line:1 char:1
+ .\a.exe
+ ~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by pieandcakes** [comment]
@matgus72 This does not seem like an extension issue.

**Comment by pieandcakes** [comment]
@matgus72 if you provide the code it might be easier to diagnose.
