### ISSUE TITLE
C syntax highlighting issue

### ISSUE THREAD

**Issue by ru-ace** [microsoft/vscode-cpptools#3006]
Issue Type: <b>Bug</b>

Pure C code.
`cfg` is struct.
second `cfg.t_low_fan` not highlighted properly
```C
cfg.t_low_fan ? (cfg.t_low_fan == 1 ? "low" : "high") : "off";
```
Screenshot:
![image](https://user-images.githubusercontent.com/10783157/50734978-6228b380-11b8-11e9-9e3e-3ad381b6e8bc.png)

Extension version: 0.20.1
VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.9.128-0409128-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2699)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (10.28GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
Our extension doesn't actually implement any C/C++ colorization; instead, VS Code itself relies on the colorization of atom/language-c: I filed a bug at https://github.com/atom/language-c/issues/316 .

**Comment by sean-mcmanus** [comment]
It looks like VS Code needs to upgrade to using tree sitter: https://github.com/Microsoft/vscode/issues/50140 .

**Comment by denis-reichelt** [comment]
I have another similar problem with the syntax highlighting:
![image](https://user-images.githubusercontent.com/13780880/50824938-1ac93100-1338-11e9-8a0d-c93d4821ea18.png)
It is not detected, that after the escaped \" quotation there is no end of quotation.

**Comment by sean-mcmanus** [comment]
@denis-reichelt I'm not able to reproduce your syntax issue. Can you provide more info on what could be different about what you're using? What color theme are you using? What OS? It would be better to file a new bug.

![image](https://user-images.githubusercontent.com/19859882/50855458-ba88be00-133c-11e9-9ebd-015ec2672ae2.png)

**Comment by jeff-hykin** [comment]
I moved this issue to `jeff-hykin/cpp-textmate-grammar` 
@ru-ace we'll keep you updated on the bug [here](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/108)
@sean-mcmanus You can probably close this issue on `vscode-cpptools`
