### ISSUE TITLE
Formatting failed!

### ISSUE THREAD

**Issue by boy-good** [microsoft/vscode-cpptools#3007]
![image](https://user-images.githubusercontent.com/39320533/50750320-42a88e00-127f-11e9-8145-b7a0d1bfa9eb.png)

![image](https://user-images.githubusercontent.com/39320533/50750354-6cfa4b80-127f-11e9-8a73-f61c5c87591b.png)

i think should ignore the head .hpp

**Comment by sean-mcmanus** [comment]
What does the C/C++ Output window say? What is the error message or number?

**Comment by boy-good** [comment]
> C / C ++输出窗口说什么？什么是错误消息或号码？

like picture two，because cannot open the head file for hpp make Formatting failed.

**Comment by sean-mcmanus** [comment]
The picture 2 is not the Output window it is the Problems window. The "cannot open source file" message are due to not being able to find the files via the includePath and is unrelated to the formatting failure.

**Comment by boy-good** [comment]
![image](https://user-images.githubusercontent.com/39320533/50804277-375d6d00-1328-11e9-81d4-8f6817af4be9.png)

only the problems window has info. @sean-mcmanus

**Comment by sean-mcmanus** [comment]
The error info should be at 
![image](https://user-images.githubusercontent.com/19859882/50804366-72b55880-12a2-11e9-8bfa-8f62b1350d87.png)

You may need to change your loggingLevel setting: (see https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md ).

**Comment by boy-good** [comment]
![image](https://user-images.githubusercontent.com/39320533/50804385-a3d86c00-1328-11e9-9315-7054fb82f550.png)

ok i find the error log like this

**Comment by sean-mcmanus** [comment]
It's the clang-format.exe. Does that file exist? Are you able to run it via the command line?

**Comment by sean-mcmanus** [comment]
I suspect the UTF-8 characters > 1 byte in the path is causing the command line to fail.

**Comment by boy-good** [comment]
![image](https://user-images.githubusercontent.com/39320533/50804769-6e348280-132a-11e9-9c27-01f7537ba0f6.png)
![image](https://user-images.githubusercontent.com/39320533/50804782-7a204480-132a-11e9-8a32-7e38fc399c03.png)

i install clang-format again but warning me this. dont you know how to setting? thanks very much

**Comment by sean-mcmanus** [comment]
Our extension provides a different implementation of clang-format and we auto-install the clang-format 6.0 binary so you don't need to install that other clang-format extension unless it has a feature that our support doesn't provide. You can download the clang-format binary yourself at http://releases.llvm.org/download.html#7.0.1 . If you want to use the clang-format extension instead, you should set the C_Cpp.formatting setting to Disabled (otherwise, both extensions will be registered as providing formatting, so I'm not sure which will actually get used).

**Comment by boy-good** [comment]
> I suspect the UTF-8 characters > 1 byte in the path is causing the command line to fail.

right. the utf-8 causing clang-format.exe formatting failed.

**Comment by boy-good** [comment]
thank you very much.

**Comment by sean-mcmanus** [comment]
I tried using UTF-8 characters > 1 byte in the path and zh-cn locale, but for some reason I'm not able to reproduce the bug. Are you able to workaround the failure somehow?

**Comment by boy-good** [comment]
I change my filename to workaround the failure. Now my filename without UTF-8 and it can be formatted.

**Comment by x7890** [comment]
This probblem has been bothering me for a long time. I have found that the cpp file can not be formatted if the name of one of its parent folders ends with "Chinese character+digit", like "中文123". If not, the cpp file can be formatted. The name of the cpp file has no influence.
Not long ago I found a solution: I insert an underline "_" between the Chinese character and the digit of the name of the folders to separate them, writing "中文_123", and the cpp file can be formatted. Using "-" or space doesn't work. Using English letters works, but there must be no spaces after Chinese characters.

**Comment by Lotherxuan** [comment]
> I suspect the UTF-8 characters > 1 byte in the path is causing the command line to fail.

Really want to say thx to you! This really works out for my problem. Well I have to say the problems that Chinese characters in a path cause really bother me, which enforces me (a Chinese windows user) to master English well...(or I have to thank microsoft for my progress in English? lol)

**Comment by sean-mcmanus** [comment]
@Lotherxuan We've recently started work on improving our "world readiness", with support for translated strings and non-English compilers coming soon.

But I'm still not able to repro this bug. Does anyone know what other special requirement is needed other than having Chinese characters in the the folder name? @Jasdriel Are you able to repro this?

**Comment by Jasdriel** [comment]
@sean-mcmanus I tried to but no luck, I even can do the formating: 
![image](https://user-images.githubusercontent.com/51973231/65634677-9d138700-df93-11e9-967e-c6311ddcb8fe.png)

**Comment by sean-mcmanus** [comment]
I believe this got fixed with in December with 0.26.2 from https://github.com/microsoft/vscode-cpptools/issues/1560 . Let us know if we should re-activate this.
