### ISSUE TITLE
format

### ISSUE THREAD

**Issue by kingloser** [microsoft/vscode-cpptools#3009]
**Type: LanguageService**

Path to format the formatting code must be in English, in Chinese and other languages would have been an error!! Request to repair!

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
We would like to fix this, but we're having problems reproducing the issue (see https://github.com/Microsoft/vscode-cpptools/issues/3007 for another report of this). We need more details, such as the OS and an example path that fails, and what version of clang-format is being used. And what other language extensions and settings need to be used or changed with the OS.

**Comment by kingloser** [comment]
Path for example：E:\stm32视频资料\A盘\4，程序源码\4，UCOS扩展例程\例10-2 UCOSIII使用信号量访问共享资源区\USER
then format will shou fail 
the os is windows 10 clang-format is 0.2.1

**Comment by sean-mcmanus** [comment]
As shown in this screenshot, formatting is still working for me. Do you know what else could be different? What is clang-format 0.2.1? I don't see that version at http://releases.llvm.org/download.html .

![image](https://user-images.githubusercontent.com/19859882/50923616-4add0680-1402-11e9-8780-ee329e37f251.png)

**Comment by kingloser** [comment]
yes ,I am find that if I build a small protect ,it will be ok ,but when i start a stm32 project it will be fail.
![image](https://user-images.githubusercontent.com/35766235/51365826-3d6bfe80-1b1d-11e9-985a-d41551b48444.png)
the 0.2.1 is the version of c/c++ ( the vscode's cpptools   ) ,which include the format .

![image](https://user-images.githubusercontent.com/35766235/51365901-a2275900-1b1d-11e9-8391-a7c517196116.png)
I is interest that when i change the file's name ,it will be success format .
the progect is as fllow
 I am so sorry that reply you too late .

 
[例11-2 UCOSIII任务内建消息队列.zip](https://github.com/Microsoft/vscode-cpptools/files/2771631/11-2.UCOSIII.zip)

**Comment by sean-mcmanus** [comment]
Tried your repro project, but I'm still not reproing the bug, even with the the Chinese language pack enabled.

![image](https://user-images.githubusercontent.com/19859882/51573716-564b1b80-1e5f-11e9-8ec5-3f1156c591af.png)

**Comment by sean-mcmanus** [comment]
I believe this got fixed with in December with 0.26.2 from #1560 . Let us know if we should re-activate this.
