### ISSUE TITLE
cpptools do not find definition of local variables

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-cpptools#301]
_From @jeybrahms on October 19, 2016 23:56_
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-43-generic
- Extensions: donjayamanne.python-0.4.2, ms-vscode.cpptools-0.9.2

Steps to Reproduce:
1. Create a bug.cpp file and put this code inside
   void f() {
   int nodeffound = 1;
   
   int b = nodeffound + 1;
   }
2. right-click on the second reference to 'nodeffound' and choose PeekDefinition. No definition will be displayed.

_Copied from original issue: Microsoft/vscode#14029_

**Comment by greazer** [comment]
Hi roblourens. Our extension currently does not parse the code within functions. Therefore, any functionality that would require that, such as this, will not work as desired. This is a common request and we do expect to address it in future release.

**Comment by roblourens** [comment]
Thanks, and just to be clear, the several bugs I've filed this week are just being moved from the vscode repo, not originating from me.
