### ISSUE TITLE
Comparison with eclipse-cdt/cdt-gdb-adapter ?

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode-cpptools#3010]
Type: Debugger

I've posted the dual question to https://github.com/eclipse-cdt/cdt-gdb-adapter/issues/56 .
I'd like to get some inputs from both projects to sort out how they compare and -to be clear- which one I'm more likely to favor if we're in need of a GDB debug adapter in some of our products.

Basically, have you compared the debug adapter from VSCode-C++ extension with the incubating one from Eclipse CDT?
On https://github.com/eclipse-cdt/cdt-gdb-adapter/issues/56 , it seems like missing registers and memory view are justification for a new debug adapter. What do you think? Is it actually missing? Would it be something that could be easily implemented in VSCode-C++ debug adapter?
Are there some synergies with https://platformio.org/platformio-ide which may grow the feature set of VSCode-C++ debug adapter?

**Comment by mickaelistria** [comment]
The vscode C++ debug adapter is actually not free software as licence on marketplace says «INSTALLATION AND USE RIGHTS. You may only use the C/C++ Extension for Visual Studio Code with Visual Studio Code, Visual Studio or Xamarin Studio software to help you develop and test your applications.», or is it only for a component in particular? (We want to use gdb,not vsdbg)
Can you please update the marletplace licence to get rid of this clause or change repo license as well as saying it's MIT isn't really compatible with this restrictive clause?

**Comment by WardenGnaw** [comment]
We have not used eclipse-cdt or platformio.

However for the memory view, we have an issue on the gdb adapter on creating a memory window: https://github.com/Microsoft/MIEngine/issues/816 

The [marketplace license](https://marketplace.visualstudio.com/items/ms-vscode.cpptools/license) is for the published extension. The cpptools source code is MIT License and if you are interested in the gdb adapter we have it also under the MIT license here: https://github.com/Microsoft/MIEngine
