### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by shamrock1996** [microsoft/vscode-cpptools#3011]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.20.1`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/2737764/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

**Comment by sean-mcmanus** [comment]
This bug report is not actionable due to lack of info. See https://github.com/Microsoft/vscode-cpptools/issues/2991 . Maybe we should try to get VS Code to improve their performance bug report template?

**Comment by bobbrow** [comment]
Consolidating performance reports from VS Code.  Tracking with #2991.
