### ISSUE TITLE
Intellisense on nested Macros does not work correctly (ex: GoToDef on SP_MEM, SP_COM, etc fails)

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/vscode-cpptools#3013]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows Build 17763.195
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

These macros are actually built up from other macros, and those macros are nested to other macros, etc.

The file https://microsoft.visualstudio.com/OS/_git/os?path=%2Fonecore%2Fds%2Fsecurity%2Flicensing%2Fclip%2Fcommon%2Fcorelib%2Fspshdefs.h&version=GBofficial%2Frsmaster builds them up.

//
// SP_MEM<T> / DP_MEM<T> - MEM smart pointer (allocated with MemoryAlloc)
//

SP_BEGIN(MEM)
    MemoryFree(p);
SP_END()

Where SP_BEGIN is defined in this file:
https://microsoft.visualstudio.com/OS/_git/os?path=%2Fonecore%2Fds%2Fsecurity%2Flicensing%2Fclip%2Fcommon%2Fcorelib%2Fsmartptr.h&version=GBofficial%2Frsmaster

And that is then comprised of other macros and so on.

#define SP_BEGIN(TAG) \
    SP_BEGIN_CLASS(TAG) \
    CP_BEGIN_DESTROY(T) \

#define SP_END() \
    CP_END_DESTROY() \
    CP_END_CLASS() \

**To Reproduce**
Repro steps;
Open folder: <OS>\src\onecore\ds\security\licensing
Navigate to: <OS>\src\onecore\ds\security\licensing\clip\service\clipsapi.cpp

<wait for NMAKE parsing to complete and also for cpptools tag parsing to complete>

Try GoToDef on SP_MEM<BYTE>. It doesn't work. GoToDef on BYTE works. What's special about SP_MEM?

(What is special is that is nested macros upon nested macros that builds a class)

Also, confirmed that these files are being tag parsed:
`tag parsing file:
E:\REPOS\OSNEW\PUBLIC\AMD64CHK\INTERNAL\ONECOREDS\INC\SPP\COMMON\CORELIB\SMARTPTR.H
  tag parsing file: E:\REPOS\OSNEW\PUBLIC\AMD64CHK\INTERNAL\ONECOREDS\INC\SPP\COMMON\CORELIB\SPSHDEFS.H`

**Expected behavior**
GoToDef works on the SP_MEM macro

**Screenshots**

**Additional context**
none

**Comment by sean-mcmanus** [comment]
Is this IntelliSense-based Go to Definition? (i.e. is IntelliSense enabled and is the header with the definition part of the includePath with any necessary defines set?). IntelliSense-based Go to Definition is expected to work in this case, but Tag Parser based Go to Definition will probably fail to parse the symbol if it requires macro evaluation unless the breaking macros are added to a cpp.hint file.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
