### ISSUE TITLE
MinGW unrecognised

### ISSUE THREAD

**Issue by Polda18** [microsoft/vscode-cpptools#3016]
I tried setting `c_cpp_properties.json` for MinGW gcc_x64, based on readme doc, but it still can't recognise the include paths for MinGW.

VS Code version: 1.30.1 (Windows 10 Home, 64bit)
MinGW version: 2013072200 (32bit, no update available)

`#include <stdio.h>` etc. do not work, IntelliSense can't open them. `#include <stdbool.h>` is just fine.

If this is not bug but wrong setup, then how do I set it up properly?

This is `c_cpp_properties.json` file contents:
```json
{
    "configurations": [{
        "name": "MinGW",
        "intelliSenseMode": "gcc-x64",
        "compilerPath": "C:/mingw64/bin/gcc.exe",
        "browse": {
            "path": [
                "${workspaceFolder}"
            ],
            "limitSymbolsToIncludedHeaders": true
        },
        "includePath": [
            "${workspaceFolder}"
        ],
        "defines": [
            "_DEBUG",
            "UNICODE",
            "_UNICODE"
        ],
        "cStandard": "c11",
        "cppStandard": "c++17"
    }],
    "version": 4
}
```

Strange thing is, that even MinGW is 32bit (as reported by MinGW Installation Manager), the `C:\MinGW64\bin\gcc.exe` does exist, alongside with other compilers and of course corresponding header files, that it should automatically locate.

**Comment by sean-mcmanus** [comment]
Is C:\MinGW64\bin\gcc.exe executable on Windows via the command line? We try to execute that and query it for the default include path and defines. Specifically, can you try:

```
cd /d C:\MinGW64\bin
gcc.exe -Wp,-v -E -xc -dD -x c++ nul
echo %errorlevel%
```

It's possible your "nul" service is disabled, see https://github.com/Microsoft/vscode-cpptools/issues/2863 .

Can you [enable Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and see what compiler it is choosing or if there appears to be other problems?

**Comment by Polda18** [comment]
Sorry, my bad. Looks like I made a mistake and remembered a wrong path. It is `C:\MinGW`, not `C:\MinGW64` like I believed. However, doesn't it expect 64bit binaries? Because I have 32bit installed. And it seems I can't define gcc-x86 to be used.

EDIT: Yea, it's okay now. The issue was the path. I don't know why I assumed it was in `MinGW64` folder. Perhaps because MinGW bash mislead me? I don't know.
