### ISSUE TITLE
Sign Language Service executable with Microsoft certificate

### ISSUE THREAD

**Issue by sclel016** [microsoft/vscode-cpptools#3018]
Type: General

I'm in a locked down environment where only whitelisted applications are allowed to run. VS Code is my editor of choice, thankfully it's signed by Microsoft which allows it to run without issue. However, the cpp tools extension is not signed by Microsoft. It would really help if I could use cpptools, however the executable needs to be signed by Microsoft.

**Describe the bug**
- OS and Version: Windows 7
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.20.1
- cpptools is not signed by Microsoft

**To Reproduce**
- Open .cpp file in vscode with Carbon Black installed with whitelist enabled
- cpptools is blocked due to no signature

**Expected behavior**
Have executable signed by Microsoft (like vscode).

**Comment by WardenGnaw** [comment]
@sean-mcmanus Did you fix this recently?

**Comment by sean-mcmanus** [comment]
We already fixed this in our insiders build (see https://github.com/Microsoft/vscode-cpptools/issues/1103 ). Set your C_Cpp.updateChannel to "Insiders" to get the signed version.

We plan to ship 0.21.0 that will also be signed in a few days or so (or next week if we get delayed).

**Comment by sclel016** [comment]
Thanks for the quick response! Keep up the great work!
