### ISSUE TITLE
Unable to start debugging. GDB failed with message "Not in executable format: File format not recognized."

### ISSUE THREAD

**Issue by caprice24** [microsoft/vscode-cpptools#3019]
I'm unable to run Windows VS Code with the MingGW gdb debugger. Getting this Error:
"Unable to start debugging. Program path 'C:\VisualStudioCode\Chap01\main.exe is missing or invalid"
"GDB failed with the message: "C:\VisualStudioCode\Chap01\main.exe": not in executable format: File format not recognized."

I'm able to run the gdb debugger from MingGW 64 bit (Version 7.3.0)  just fine from the command line, but it acts up when invoked from within VS Code using the Debug (gdb) Launch menu command.

Here is my c_cpp_properties.json:
{
    "configurations": [
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE"
    ],
    "compilerPath": "C:/MinGW64/mingw32/bin/gcc.exe",
    "intelliSenseMode": "clang-x64",
    "browse": {
        "path": [
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": ""
    }
}
],
"version": 4
}

Here is my launch.json:
{
    "version": "0.2.0",
    "configurations": [
      
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/main.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/MinGW64/mingw32/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build hello world"
        }
        

        
    ]
}

Here is my tasks.json

{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build hello world",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g", "main.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

main.cpp:
#include <iostream>

int main() {
    int x = 10;
    int y = 20;
    
    std::cout << "hello world" << std::endl;
    system("pause");
}

I looked at other forums that said it might be an issue between running 32 bit version of g++ vs 64 bit gdb, but I don't think that is the issue since it runs fine from the command line.

Extensions were all disabled when I tried to debug the issue, the error still happened.
Here is the list of extensions I have:

![capture2](https://user-images.githubusercontent.com/26287865/50878059-a7e8a600-1389-11e9-9ff1-2168c6f3e570.JPG)
Additional extensions not shown above:
+ Ruby extension
+ SQL Server
+YML

![capture](https://user-images.githubusercontent.com/26287865/50877901-ddd95a80-1388-11e9-9265-a97e63429c4f.JPG)

**Comment by WardenGnaw** [comment]
From launch.json, you specified the miDebuggerPath to be `C:/MinGW64/mingw32/bin/gdb.exe` which is the 32 bit MinGW.

In tasks.json, you have the command as `g++`. Can you specify the full path the compiler instead? E.g. `C:/MinGW64/mingw32/bin/g++.exe`

**Comment by caprice24** [comment]
I changed the tasks.json to read like this:
   "command": "C:/MinGW64/mingw32/bin/g++.exe",

But it made no difference.

As for the launch.json, unfortunately, there doesn't seem to be a 64 bit version of gdb in the default minGW distribution that I downloaded from https://osdn.net/projects/mingw/releases . Note that on this web page they state "All of MinGW's software will execute on the 64bit Windows platform".

 Is there a better minGW or other C++ compiler that you can recommend?

**Comment by caprice24** [comment]
Accidentally closed issue, see comment above to respond.

**Comment by WardenGnaw** [comment]
Did you build main.exe? The tasks.json does not have `-o` specificing the output name, by default, it will produce `a.exe`.

**Comment by caprice24** [comment]
That works! Thanks!

**Comment by sushi057** [comment]
> Did you build main.exe? The tasks.json does not have `-o` specificing the output name, by default, it will produce `a.exe`.

Can you please clarify more on how to do that? I have been trying to resolve this issue for so long.
