### ISSUE TITLE
has error OS x 10.11.6

### ISSUE THREAD

**Issue by yejun556688** [microsoft/vscode-cpptools#302]
Updating C/C++ dependencies...

Downloading package 'Mono Framework Assemblies' Failed at stage: downloadPackages
Error: connect ECONNREFUSED 111.13.109.41:443

Finished

**Comment by delmyers** [comment]
@yejun556688, this particular extension needs to download dependencies for individual platforms. Can you try restarting vscode and trying again? If that doesn't work, try uninstalling and reinstalling the extension.

**Comment by pieandcakes** [comment]
@yejun556688 If this is still an issue, can you try the steps @delmyers mentioned above and if it doesn't resolve it, please reopen this issue.

Thanks
