### ISSUE TITLE
Unable to compile standard library C++ code in Linux

### ISSUE THREAD

**Issue by caprice24** [microsoft/vscode-cpptools#3020]
My problem is that I'm running Visual Studio Code on Redhat Linux, and I'm not able to get the g++ compiler to work, because it can't find the std libraries. I know that the gdb debugger is working, because when I run the g++ from the command line, it builds the executable properly and gdb then works. Intellisense is also not picking up the "std" part of the code in the IDE.

OS and Version: RedHat Centos 6 64 bit
VS Code Version: 1.20.1
C/C++ Extension Version:  0.16.1

My Code:
#include <iostream>
#include <stdio.h>
int main() {
    int x = 10;
    int y = 20;

    int z = 30 ;
    std::cout << "hello world" << std::endl;
   std::cout << std::endl << "Press any key to continue...";
   getchar();
   getchar();
}

my c_cpp_properties.json

    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
         

            "logging": {
                "engineLogging": true
            },
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                     "${workspaceFolder}"
                ]
            },
            "compilerPath": "/usr/bin/g++"
        }
    ],
    "version": 3
}

my launch.json
{
 
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(gdb) Launch Internal Window",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/helloworld",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build hello world"
        },
        {
            "name": "(gdb) Launch External Window",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/helloworld",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build hello world"
        }
    ]
}

my tasks.json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build hello world",
            "type": "shell",
            "command": "/usr/bin/g++",
            "args": [
                "-g", "helloworld.cpp",
                "-o", "helloworld"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
            
        }
    ]
}

**Comment by sean-mcmanus** [comment]
You should try removing the system path from your includePath and instead rely on the compiler querying for "/usr/bin/g++" for the include path. However, your VS Code and C/C++ versions are too old so you might be hitting some bug we fixed a long time ago. Can you update them? Everything is working for me with 0.21.0-insiders3 and VS Code 1.30.1. I'm not aware of any other user reports from CentOS 6 (all have been with CentOS 7), so I don't know if there is some issue with that.

Also, your intelliSenseMode should not be "msvc-x64" -- that is for the cl.exe compiler.  I don't remember if we fall back to the correct clang/gcc-x64 mode on the old version you're using.

**Comment by caprice24** [comment]
Thanks, your suggestion solved my problem, eg the VS Code and C++ Extension versions were stale!

Regards,
Nick
