### ISSUE TITLE
Prevent Intellisense and Syntax Checking for Compiler Header Files

### ISSUE THREAD

**Issue by yekanchi** [microsoft/vscode-cpptools#3021]
**Type: LanguageService**

It would be Great if there was an option to opt out the compiler header files problems from being shown in the problem section(shown in below Screenshot). the image below shows the part i want it to be removed, those are the files related to MinGW and i d'nt want them to be checked for error. because they are out of our Scope.

**Adding a Feature to opt out specific folders from being checked for intellisense and errors will solve the issue**

**Describe the bug**
- OS and Version: Windows
- VS Code Version: 1.30.2
- C/C++ Extension Version:   0.21.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

1.  Download MinGW Build from [nuwen.net](https://nuwen.net/)
2. Start a New Cpp Project and in your c_cpp-Properties.json Include MinGW include Folders.
3. Add some header files like: "basic_string.h", <iomanip>, or any other header witch may have errors

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/25511175/50965100-412ccf00-14e6-11e9-85d9-38963a9b9a86.png)
i want the errors show in red area to be removed because they are out of my code and they are comipler header files.

**Additional context**

**Comment by bobbrow** [comment]
I am no longer seeing this issue with the latest version of the extension.
