### ISSUE TITLE
Highlight 2nd namespace when nested

### ISSUE THREAD

**Issue by pgbarletta** [microsoft/vscode-cpptools#3023]
**Type: LanguageService**
Super minor, and annoying, feature request.

- OS and Version: Neon KDE 5.14.4 (kernel 4.18)
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1

**Screenshots**

![multiline](https://user-images.githubusercontent.com/5693483/51004199-70f4ca80-1518-11e9-8114-c638ddcd3d5d.png)
![nested](https://user-images.githubusercontent.com/5693483/51004205-73efbb00-1518-11e9-8a93-f0926c3bddd8.png)

**Additional context**
My *c_cpp_properties.json*:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/home/pbarletta/labo/ANA/include",
                "/usr/local/fmt-5.2.1/include",
                "${workspaceFolder}/include",
                "/usr/lib",
                "/usr/local/lib",
                "/usr/lib/x86_64-linux-gnu",
                "/usr/include/x86_64-linux-gnu"
            ],
            "defines": [],
            "compilerPath": "/usr/local/clang+llvm_7.0.0/bin/clang++",
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++17",
            "configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
Our extension doesn't implement colorization. It looks like it will be fixed once VS Code switches to the atom/language-c tree sitter implementation: https://github.com/Microsoft/vscode/issues/50140 .

![image](https://user-images.githubusercontent.com/19859882/51011228-9976c780-150c-11e9-8c27-ea73fc3e0635.png)

**Comment by pgbarletta** [comment]
Oh, cool, thanks for the info.

**Comment by sean-mcmanus** [comment]
This has been fixed with the latest VS Code -- all the namespaces are non-highlighted.

**Comment by sean-mcmanus** [comment]
Actually, the fix is in VS Code Insiders (not VS Code, unless you install the Better C++ Syntax extension).
