### ISSUE TITLE
[Windows] Interactive Pipe Program that will prompt for a password

### ISSUE THREAD

**Issue by grant-rez** [microsoft/vscode-cpptools#3025]
Type: Debugger
CPP GDB Pipe Transport Attach

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows
- VS Code Version: 1.30.2
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them): N/A
- A clear and concise description of what the bug is:
While using Pipe Transport, I am not asked for my password or for further authentification (My university uses DUO Security  2fa.)

**To Reproduce**

launch.json:
```
{
     {
            "name": "(gdb) Pipe Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "./hello_world",
            "args": [],
            "stopAtEntry": false,
            "cwd": "EECS482/test",
            "environment": [],
            "externalConsole": false,
            "pipeTransport": {
                "debuggerPath": "/usr/bin/gdb",
                "pipeProgram": "C:\\Windows\\System32\\OpenSSH\\ssh.exe",
                "pipeArgs": ["username@host"], // This is the correct server name in my own file
                "pipeCwd": "",
                
            },
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
}
```

**Additional context**
My university also does not support using ssh keys to login.

**Comment by pieandcakes** [comment]
This is a known limitation and we don't have a good solution for it. All the communication is sent over plaintext protocol messages and we don't have a way to prompt the user for this information. 

`plink.exe` supports specifying your password using the `-pw` flag but I'm not familiar with the security protocols that your university uses and how 2FA works in your specific instance. If you have to then enter in a code then that solution won't work for you either.

**Comment by pieandcakes** [comment]
The other option is to write an ssh client that creates a modal dialog asking for your password but thats beyond the scope of this extension.

**Comment by grant-rez** [comment]
Thanks for the reply and help. Basically, after putting in my password, the authorization asks for a number to specify which authorization to use, then I need it to wait so that I can approve the login on my phone. I tried several different options with plink, but that wasn't possible either. I'll have to look into some other options I guess.

**Comment by pieandcakes** [comment]
If you find a better option, let me know. I'm going to close this issue for now.
