### ISSUE TITLE
tag parser is used for local variable

### ISSUE THREAD

**Issue by outofmemo** [microsoft/vscode-cpptools#3030]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux ubuntu 3.13.0-79-generic #123-Ubuntu
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): alefragnani.project-manager
- A clear and concise description of what the bug is.
Whatever the symbol is selected, tag parser will be used for `Go to Definition`.

**To Reproduce**

1. Select local variable
2. Click on 'Go to Definition'
3. See error

**Expected behavior**

Show context-aware results.
**Screenshots**

![image](https://user-images.githubusercontent.com/19758229/51084522-31232280-1766-11e9-8bdd-d91a562f021f.png)
*`j` is a local variable*
**Additional context**

**setting**
```
"C_Cpp.default.cStandard": "c99",
"C_Cpp.default.intelliSenseMode": "gcc-x64",
"C_Cpp.loggingLevel": "Debug"
```
**log**
```
textDocument/definition
textDocument_definition() - file:///xxxx/wclient.c, 312:46
  tag parsing file: /workdisk/xxxx/rtl8712_hal.h
  tag parsing file: /workdisk/xxxx/hw/map_pcu_reg.h
textDocument/documentHighlight
cpptools/textEditorSelectionChange
$/cancelRequest
textDocument/definition
textDocument_definition() - file:///xxxx/wclient.c, 312:46
textDocument/codeAction
textDocument/hover
using Tag Parser for quick info
$/cancelRequest
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/codeAction
cpptools/textEditorSelectionChange
textDocument/didOpen
Checking for syntax errors: file:///xxxx/linux/device-mapper.h
terminating child process: 14793
textDocument/codeAction
textDocument/codeAction
  tag parsing file: /workdisk/xxxx/mach/magician.h
sending compilation args for /workdisk/xxxx/device-mapper.h
  include: /usr/include/c++/4.8
  
```

**Comment by bobbrow** [comment]
Sorry for the late reply, this seems to have slipped through our notifications.

Can you share more information about your configuration?  From the logs you've shared it doesn't look like you are setting `compilerPath` in your `c_cpp_properties.json`  This could be causing the extension to use the tag parser for goto definition instead of using the semantic IntelliSense engine.  Tag parser doesn't do IntelliSense for local variables.

**Comment by sean-mcmanus** [comment]
From the screenshot, it looks like error squiggles are showing, so (assuming those aren't from another extension) it wouldn't be using the tag parser unless there is a severe parser error that causes the local variable to no longer been interpreted as a local (i.e. I repro that behavior when I remove the { from the start of the function body).

**Comment by outofmemo** [comment]
Yes, you are right. The engine switches to the tag parser because of #include errors. So I will disable `Intelli Sense Engine Fallback`.
