### ISSUE TITLE
VSCode window flickers and fails to render properly when viewing code with inactive regions

### ISSUE THREAD

**Issue by sgcowell** [microsoft/vscode-cpptools#3032]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04.1 LTS
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them):

I've disabled all other extensions except for cpptools - the issue only repros with cpptools enabled.   I've tried previous versions of cpptools as well - this issue started reproing in 0.17.5, and repros in all versions since then, including the latest insiders build.  I suspect the change that introduced this was the inactive regions coloring changes (#1907).

- A clear and concise description of what the bug is.

When viewing C++ source files with inactive regions in #ifdef blocks, vscode does not render correctly.  Parts of the window will blank out randomly depending on where you move your cursor.  The issue will go away if you scroll to a part of the file that does not have such inactive regions, or switch to another open file without such inactive regions.   The issue is most likely to repro with large inactive regions that cover the majority of the visible area.

Attached zip has a video showing the flickering and a file that repros the issue for me.

[cpptools_flickering_issue.zip](https://github.com/Microsoft/vscode-cpptools/files/2753660/cpptools_flickering_issue.zip)

**To Reproduce**

1. Open Triangle.frag.h from the attached zip.
2. Make sure your window size is large enough to view the entire area in the #if block, as well as some of the code below.
3. Flickering occurs when moving the cursor around.

**Expected behavior**

It should render the inactive region correctly without causing flickering in vscode

**Screenshots**

Note the rectangular blanked out regions on the tab list and on the left pane.

![screenshot from 2019-01-13 15-03-33](https://user-images.githubusercontent.com/24662068/51091812-88180000-1744-11e9-9658-719fa7b5f38c.png)

**Comment by sgcowell** [comment]
Dug further, looks like a dupe of #2704.   This issue has been around for months, what's the ETA on the fix on the vscode side going into a production build?

**Comment by sean-mcmanus** [comment]
@sgcowell The fix should be in VS Code Insiders. Not sure when they're pushing that to the non-Insiders (usually it's monthly).
