### ISSUE TITLE
Option to configure IntelliSense suggestion wrapping for big function signatures

### ISSUE THREAD

**Issue by KaeLL** [microsoft/vscode-cpptools#3034]
Please don't wrap this
![Please don't wrap this](https://user-images.githubusercontent.com/4423144/51115235-ce299e00-17ee-11e9-855b-b629a12f89a2.png)

**Comment by bobbrow** [comment]
Language extensions currently don't have any way to request the tooltip width.  The VS Code API would need to be modified for us to be able to control this.

**Comment by sean-mcmanus** [comment]
VS Code is tracking this with https://github.com/Microsoft/vscode/issues/56525 .

**Comment by bobbrow** [comment]
Tooltips are resizable now.
