### ISSUE TITLE
My vscode can't find the definition globally? 

### ISSUE THREAD

**Issue by kevinuav** [microsoft/vscode-cpptools#3035]
Hi,all!
I use vscode to edit a git code with OSX.It works very well before.But these days it can't "go to definition"suddenly.And it can't find the definition of the functions globally.
Besides,the issue comes with tons of problems, such as"identifier XXX is undefined","variable XXX is not a type name".Curiously,the code can be compiled successfully!

Meanwhile,it responds with
"XXX.cpp not found in "${workspaceFolder}/build/XXX_default/compile_commands.json". 'includePath' from c_cpp_properties.json will be used for this file instead."

If the compile_commands.json have something to do with the issue?

To fix the issue,I have tried many methods.However,It still doesn't work even after that I completely remove and reinstall all of the vscode and all of the git's code.what is the problem about the vscode?And how could I fix it? Thank you?

**Comment by HigHwindEx** [comment]
I have had a similar problem with Windows, but it seemed that adding `"/**"` to some include paths solved my problem. I don't know why...

**Comment by bobbrow** [comment]
Hi there,

I was looking through old issues and found this one.  I'm so sorry this issue didn't get any attention when you opened it.  Are you still having trouble with your `compile_commands.json` files?  If you could provide some additional information we can help you debug this (e.g. run the "Log Diagnostics" command to check how the source file was configured and see if that matches your compile_commands entries).

Thank you, and again I'm sorry we didn't respond earlier!

**Comment by Colengms** [comment]
@kevinuav Are you still seeing this issue?  Since we haven't heard back, I'm going to close this issue.  If it is still a problem, please re-open.
