### ISSUE TITLE
C++ source files interpreted as C

### ISSUE THREAD

**Issue by sameersuterwala** [microsoft/vscode-cpptools#3036]
**Type: LanguageService**

**Describe the bug**
- OS and Version: RHEL 7
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.20.1 and 0.21.0-insider3
- No other extensions

My organization uses .C (upper case) for C++ source files, and cpp-tools attempts to parse the file as C.  Renaming files to a .cpp extension resolves the issue, however, this is not possible with our coding conventions.

I have also tried the following settings, to no avail
In workspace settings:
`{
    "files.associations": {
        "*.C": "cpp",
        "*.c": "c",
        "*.H": "cpp",
        "*.h": "cpp",
       ...
`
adding "-x c++" to compilerPath in c_cpp_properties.json

**Comment by bobbrow** [comment]
Thank you for reporting this.  This is a duplicate of #2558 and is something we may need to work around since VSCode doesn't support case-sensitive file associations.

**Comment by sameersuterwala** [comment]
I read #2558 and thought maybe my problem was I had "*.c": "c" in my files.associations property.  I have removed that and still have the same issue.

also, despite having the following files.associations:
`    "files.associations": {
        "*.C": "cpp",
        "*.H": "cpp",
        "vector": "cpp",
        "cstdlib": "cpp",
        "stdexcept": "cpp",
        "string": "cpp",
        "memory": "cpp",
        "iosfwd": "cpp",
        "functional": "cpp",
        "ios": "cpp",
        "exception": "cpp",
        "fstream": "cpp",
        "ostream": "cpp",
        "cstdint": "cpp"
    }
`
```namespace std``` is unrecognized in ```cstdint``` (and others)

**Comment by sameersuterwala** [comment]
also, it appears the application of the parser is not consistent.  in the file with my main (which has a .C extension), C++ keywords are interpreted properly, however, when jumping to an included header (with .H), the interpreter goes to C

**Comment by sameersuterwala** [comment]
I seemed to have found another factor

Files with a .C extension resolve as C++ when in my workspace's root directory, however, not within sub-directories

**Comment by sean-mcmanus** [comment]
Are you using a multi-root workspace? Are the files.association settings being applied to only certain workspace folders?

**Comment by sameersuterwala** [comment]
I don't believe I am using a multi-root workspace

here is an obfuscated view of my organization's code layout:
```
+--proj/  <--This is my workspace root and is my git root
   |
   +--README.md
   |
   +--proj/  <--I have tried this as my workspace root, no difference
       |
       +--subproj1/
       |   |
       |   +--main1.C <--always correctly interpreted
       |   |
       |   +--Class1.C <--never correctly interpreted.  renaming to Class1.cpp causes proper interpreting
       |   |
       |   +--Class1.H
       | 
       +--UtilClass1.C <--occasionally correctly interpreted (possibly doesn't work when arriving at file via browsing definitions)
       |
       +--UtilClass1.H
```

the convention for including headers is `#inlcude <proj/UtilCLass1.H>`

**Comment by sameersuterwala** [comment]
also, to be specific, the first parser failure is usually along the lines of interpreting `namespace` or `using` as a symbol.

**Comment by sean-mcmanus** [comment]
I'm not able to repro a problem. I noticed the icons are incorrect for the header files, but the status bar shows C++ for the language.

![image](https://user-images.githubusercontent.com/19859882/51275392-b1c06980-1986-11e9-8f8d-9f7879243552.png)

**Comment by sameersuterwala** [comment]
I believe I'm seeing a correlation to how I navigate to the file.  Jumping by class definition seems to be more likely to expose the issue, whereas opening the file from the Explorer makes it less likely.

`switch header/source` on files with the issue doesn't seem to work, either

I will try to reproduce with a sample I can share. (I do see the same issue with the icon/status bar, but I haven't given it too much significance)

**Comment by sean-mcmanus** [comment]
I filed a new bug for the switch header/source: https://github.com/Microsoft/vscode-cpptools/issues/3048 .

Our Go to Definition code will add headers to files.associations whenever it detects a C or C++ file is using that header from a #include (which enables C++ highlighting when navigating to `#include <string>` etc.). It's possible there's a bug with this in certain scenarios. Let us know if you figure out a repro.

**Comment by sameersuterwala** [comment]
I haven't been able to reproduce the issue with a smaller application, but I do have a couple more observations:
1) Context seems to matter:
 * The same file might not parse correctly depending on if the corresponding C/H is not open, but recover after the counterpart is opened
 * Opening the file via the solution explorer makes it more likely to parse correctly, versus jumping via class/method definition or `#include`
2) Jump to definition/declaration does not work properly.  Even if both the header and source file do parse properly, jumping does not from a function declaration to the definition or vice-versa.

I have upgraded cpptools to 0.21.0

**Comment by michelleangela** [comment]
Closing as duplicate.
