### ISSUE TITLE
C++/CX projects are not supported 

### ISSUE THREAD

**Issue by saqadri** [microsoft/vscode-cpptools#3039]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 (but shouldn't be version specific)
- VS Code Version: 1.30.1 (but shouldn't be version specific)
- C/C++ Extension Version: 0.20.1 (but shouldn't be version specific)
- Other extensions you installed (and if the issue persists after disabling them): N/A
- A clear and concise description of what the bug is:

In cl.exe, C++/CX is enabled using the /ZW flag. There is at present no facility to enable this from IntelliSense perspective in the cpptools extension.

There are some approaches to this:
- allow a --cppcx flag on the compilerPath, similar to /clr (see https://github.com/Microsoft/vscode-cpptools/issues/1987).
- allow a generic compilerFlags field to specify arbitrary compiler flags, one of which could be /ZW, which then gets translated to the relevant EDG setting.

**To Reproduce**
Set up a C++/CX project

**Expected behavior**
C++/CX constructs are supported

**Comment by sean-mcmanus** [comment]
Do you need support for the /AI command line for adding directories to search for files when using `#using`? I'm not sure how important that is to add.

UPDATE: We'll just enable /AI on the compilerPath for now...we might support it via includePath later on.

**Comment by sherryyshi** [comment]
Hi @sean-mcmanus ,
Bob mentioned that you will be enabling this through the `compilerArgs` param. FYI to enable C++/CX we specify the following compiler args:
`ZW`,  `/ZW:nostdlib`, `/FU<platform.winmd>`, `/FU<Windows.winmd>`, `/AI<metadataDirectory>`

Currently the `.winmd` files are passed into the `forcedInclude` param - let me know if we should change that.

Also, let me know if you want me to test out your implementation as I'm currently looking into enabling this scenario.

Thanks,
Sherry

**Comment by sean-mcmanus** [comment]
@sherryyshi Yeah, thanks for the info. We process the /ZW and /AI, but not the /ZW:nostdlib and /FU flags, i.e. we automatically use the platform.winmd and windows.winmd -- did you need those set in a special way that is different from their default locations. I can send you a .vsix with the change when I get it finalized/tested.

**Comment by sean-mcmanus** [comment]
We added support for `/ZW`, `/ZW:nostdlib`, `/FI`, `/FU`, and `/AI` compiler arguments. See https://docs.microsoft.com/en-us/cpp/cppcx/compiler-and-linker-options-c-cx?view=vs-2019 . compilerPath needs to be set for "cl.exe" except in the special case where a custom configuration provider is used, in which case compilerPath can be "", but the path to vccorlib.h needs to be in the includePath (in addition to be specified with the /FI flag or forcedInclude setting).

**Comment by sean-mcmanus** [comment]
C++/CX is available with 0.26.0.
