### ISSUE TITLE
Add custom preprocessor definitions?

### ISSUE THREAD

**Issue by LYP951018** [microsoft/vscode-cpptools#304]
What about allowing users to config custom preprocessor definitions in the JSON file like command line [/D](https://msdn.microsoft.com/en-us/library/hhzbb5c8.aspx) in MSVC?

**Comment by delmyers** [comment]
@LYP951018, what is the scenario that you are trying to support here? Do you expect IntelliSense to work differently based on preprocessor definitions?

**Comment by LYP951018** [comment]
@delmyers Yes.

**Comment by hoffmael** [comment]
Adding a vote to this one. Compiler and Arch specific preprocessor definitions have to be manually provided to intelliSense as they are not defined in a source file.

**Comment by sean-mcmanus** [comment]
We're working on adding this for our next feature release.

**Comment by bobbrow** [comment]
This is available in the current release: 0.11.0.  If you opt-in to the new IntelliSense engine via `"intellisenseEngine": "Default"` you can set **"defines"** in your c_cpp_properties.json file and we will respect them for the features that the new IntelliSense engine supports (currently, tooltips and error squiggles).

**Comment by fordp2002** [comment]
Having to duplicate #defines separately from your build system does not make a lot of sense. Some ways to get them out of your project/makefile would make more sense.

**Comment by worthy7** [comment]
![image](https://user-images.githubusercontent.com/4762399/94630737-91bf0e00-0301-11eb-98a4-0965e4296412.png)


Am I doing something wrong here? It doesn't seem to be working. Intellisense still puts red lines under the custom preprocessor definitions.

**Comment by Colengms** [comment]
Hi @worthy7 .  Adding a value to the list of 'defines' is equivalent to using them in #define statements.  i.e.:
```
#define UNICODE
```
... for use as a macro or in preprocessor expressions, such as:
```
#ifdef UNICODE
#endif
```
It looks like you're trying to create your own preprocessor commands/keywords, not macro definitions.  I don't believe that's supported by the language.

**Comment by worthy7** [comment]
Ah, so I misunderstood the use. So what are my options to try and get it to be a bit smarter? (This is using MQL5, a MetaTraders own trading code which is some kind of modified c++, but their editor is crap)
Thanks for the help!

**Comment by sean-mcmanus** [comment]
@worthy7 You could try using (potentially in a forcedInclude file).
```
#ifdef __INTELLISENSE__
    #pragma diag_suppress 11
#endif
```

**Comment by bobbrow** [comment]
If you want to hide non-standard keywords, the syntax would be:
```
"defines": [
  "input="
]
```
If you forget the `=`, the define will be assigned a value of `1` instead of an empty string.
