### ISSUE TITLE
Configuration problems with px4 code

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3040]
Hi,all!
I use vscode to edit the px4's code with OSX.It works very well before.But these days it can't "go to definition"suddenly.And it can't find the definition of the functions.
Besides,the issue comes with tons of problems, such as"identifier XXX is undefined","variable XXX is not a type name".Curiously,the code can be compiled successfully!

Meanwhile,it responds with
"FixedwingPositionControl.cpp not found in "${workspaceFolder}/build/px4io-v2_default/compile_commands.json". 'includePath' from c_cpp_properties.json will be used for this file instead."

If the compile_commands.json have something to do with the issue?

To fix the issue,I have tried tons of methods.However,It still doesn't work even after that I completely remove and reinstall all of the vscode and all of the px4's code.what is the problem about the vscode?And how could I fix it? Thank you?

To fix the issue,I have tried tons of methods.However,It still doesn't work even after that I completely remove and reinstall all of the vscode and all of the git's code.what is the problem about the vscode?And how could I fix it? Thank you?

_Originally posted by @kevinuav in https://github.com/Microsoft/vscode-cpptools/issues/1777#issuecomment-454008998_

**Comment by sean-mcmanus** [comment]
Is your compile_commands.json correctly generated? Does it contain information for the FixedwingPositionControl.cpp? If you can provide your c_cpp_properties.json and/or any C_Cpp.default settings you're using that would help.

For "identifier is undefined" issues do you have the correct includePaths that define the variables?

For Go to Definition, do the definitions exist in other translation units? Does the path with the definition exist in the browse.path or includePath setting? We don't auto-populate the browse.path from the compile_commands.json yet.

It's also recommended to set your C_Cpp.updateChannel to get the 0.21.0-insiders3 build, which has a lot of fixes.

[Enabling debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) is a good way to try to figure out why configuration problems are occurring.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
