### ISSUE TITLE
Migrate Travis-CI to Azure Pipelines

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode-cpptools#3041]
From https://developer.github.com/changes/2018-04-25-github-services-deprecation/
> January 31, 2019: GitHub stops delivering installed services' events on GitHub.com.
This will cause Travis-CI to stop working for PRs.

From https://docs.travis-ci.com/legal/terms-of-service/
> An Account may only be used by one single person. The Customer is entitled to create separate Accounts for his employees.

This means that we can't use the Travis-CI for the cpptools extension. We should move to Azure Pipelines, so we also get Windows and OSX coverage, too.

See https://code.visualstudio.com/api/working-with-extensions/continuous-integration

**Comment by sean-mcmanus** [comment]
Is this finished now?
