### ISSUE TITLE
PowerShell process 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-cpptools#3043]
_From @MT00x on January 14, 2019 16:12_

- VSCode Version: 1.30.2
- OS Version: Windows 7 64 BIT

A lot of PowerShell Process created and do not exit when doing symbol searching. 
Related to issue #60414 the problem is still present.

Language: C/C++ - JS
Extensions:  
ms-vscode.cpptools
mitaki28.vscode-clang
hars.cppsnippets
austin.code-gnu-global
streetsidesoftware.code-spell-checker
plorefice.devicetree
ms-ceintl.vscode-language-pack-it
ms-python.python
fantasytyx.tortoise-svn

[vscode-status.txt](https://github.com/Microsoft/vscode/files/2755972/vscode-status.txt)

![vscode](https://user-images.githubusercontent.com/10209506/51124927-c0d8d780-181f-11e9-9360-76bc0084d27e.jpg)

_Copied from original issue: Microsoft/vscode#66494_

**Comment by sean-mcmanus** [comment]
@MT00x This has been fixed already with our Insiders build, via setting C_Cpp.updateChannel to "Insiders" we plan to release the non-Insiders update within the next few days. See https://github.com/Microsoft/vscode-cpptools/issues/2822 .
