### ISSUE TITLE
why debug the F11 etc is disable?

### ISSUE THREAD

**Issue by qiudaozhang** [microsoft/vscode-cpptools#3044]
1. i want to debug the c program , config the  the tasks.json 
`{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build C",
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            }, 
            "command": "gcc -g main.c -std=c11 -Werror -Wall -lm"
        }
    ]
}`
2.  the lauch.json config is 
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}`

3 when i enter F5 
F10 and F11 are disabled . can you tell me how to do it ?
i use the vscode lastest version.

**Comment by pieandcakes** [comment]
@qiudaozhang You have to be stopped at a breakpoint for F10 and F11 to work. Please either set `stopAtEntry` to `true` or set a breakpoint and then stepping will be allowed.
