### ISSUE TITLE
Signature help fails on semicolon

### ISSUE THREAD

**Issue by gost-serb** [microsoft/vscode-cpptools#3045]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Version 1709
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): Remains after disabling all of them
- A clear and concise description of what the bug is.

Function signature help stop showing after entering typing semicolon or closing parenthesis in one of `char*` arguments.

**To Reproduce**

Sample code file:
```
#include <stdio.h>

int main()
{
    fopen("put semicolon here", "r");
    return 0;
}
```

**Expected behavior**

Signature help continue showing after typing some of these symbols.

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
It looks like this repro's with Tag Parser, but not with IntelliSense.
