### ISSUE TITLE
The extension can‘t solve C/C++ autocompletion 

### ISSUE THREAD

**Issue by heator** [microsoft/vscode-cpptools#3051]
The extension can‘t solve C/C++ autocompletion. It's so upset to me for I am going to improve my C skills.Auto-Completion doesn't seem to work as expected. 

It(vscode) says _**"cannot open source file "xxx.h""**_,but when I press **"ctrl"** and click it( **_#include (for instance)<stdio.h>_**), it can jump to the _**stdio.h**_ source file. 
### _why it can't sense(sense means _giving me right auto-completion_) the source files while it can jump to them?_   

Below is my Cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "E://cygwin64//lib//gcc//x86_64-pc-cygwin//7.4.0",
                "E://cygwin64//lib//gcc//x86_64-pc-cygwin//7.4.0//include",
                "E://cygwin64//lib/gcc//x86_64-pc-cygwin//7.4.0//finclude",
                "E:/cygwin64/lib/gcc/x86_64-pc-cygwin/7.4.0",
                "E:/cygwin64/lib/gcc/x86_64-pc-cygwin/7.4.0/include",
                "E:/cygwin64/lib/gcc/x86_64-pc-cygwin/7.4.0/finclude"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "browse": {
                "path": [
                    "E://cygwin64//lib//gcc//x86_64-pc-cygwin//7.4.0",
                    "E://cygwin64//lib//gcc//x86_64-pc-cygwin//7.4.0//include",
                    "E://cygwin64//lib/gcc//x86_64-pc-cygwin//7.4.0//finclude"
                ]
            },
            "compilerPath": "E://cygwin64//bin//gcc.exe",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

Then below is my setting.json:
```
    "C_Cpp.default.cppStandard": "c++11",
    "C_Cpp.default.cStandard": "c11",
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.default.includePath": [
        "E:\\cygwin64\\lib\\gcc\\x86_64-pc-cygwin\\7.4.0",
        "E:\\cygwin64\\lib\\gcc\\x86_64-pc-cygwin\\7.4.0\\include",
        "E:\\cygwin64\\lib\\gcc\\x86_64-w64-mingw32\\7.4.0\\include"
    ],
    "C_Cpp.default.browse.path": [
        "E:\\cygwin64\\lib\\gcc\\x86_64-pc-cygwin\\7.4.0",
        "E:\\cygwin64\\lib\\gcc\\x86_64-pc-cygwin\\7.4.0\\include",
        "E:\\cygwin64\\lib\\gcc\\x86_64-w64-mingw32\\7.4.0\\include"
    ],
```

Enviro Configuration

    OS: Windows 10 Education 64-bit
    VS Code Version: 1.30.2
    version of cygwin's gcc is 7.4.0

Plug-ins I used:

    C/C++
    C-intellisense

Is there anyone can help me? thx.

**Comment by heator** [comment]
Is there anyone to help me?

**Comment by bobbrow** [comment]
You should not add system include paths to the `includePath` variable.  GCC compilers are very picky about the ordering of the include paths because the system headers use `#include_next`.  Setting the `compilerPath` should be sufficient.

Can you try the following configuration instead?
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "E:/cygwin64/bin/gcc.exe",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

You should also remove system include paths from `C_Cpp.default.includePath` and `C_Cpp.default.browse.path`

**Comment by heator** [comment]
I did nothing but vscode restored the C/C++ autocompletion. I wish it won't happen again. 
### **All in all, vs code is a perfect tool(I like it and it makes me love coding more) even than those IDEs like pycharm ,clion and others** 
@bobbrow

**Comment by Robominister** [comment]
I am having an issue today, since upgrading cygwin and the gcc installation on my machine - intellisense for any standard library has completely broken. It was working fine previously.

**System:** Windows 7 64
**VSCode:** 1.30.2
**C/C++ extension:** 0.21.0

My cpp_properties.json is basically exactly as @bobbrow describes:
`{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/cygwin64/bin/gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}`

And I can verify, that adding the paths to the header files in the "includePath" field doesn'thelp (some standard library imports are resolved, but not others)
