### ISSUE TITLE
outline hangs with each edit

### ISSUE THREAD

**Issue by lfg6000** [microsoft/vscode-cpptools#3054]
**Type: LanguageService**
- VSCode Version: 1.30.2
- OS Version: win 10
- C/C++ ms-vscode.cpptools Preview 0.20.2
- extension: Platformio ide 1.6.0

Steps to Reproduce:

1. Open a .cpp file
2. in outline view click on a method and notice the editor goes to the method in the .cpp file
3. make an edit in the .cpp
4. in outline click on a method and notice the editor does NOT go to the method in the .cpp file 
5. notice the blue progress indicator in the outline view title bar is going around
6. the outline view is unusable while blue progress indicator is active.

It would be good to be able to use the outline view while making lots of edits. At the moment the outline view is not helpful when doing lots of edits.

**Comment by bobbrow** [comment]
Yes, the Outline view needs more work done on it.  Our extension doesn't support it very well right now.  We are tracking this with #2230.  Can you please go upvote that issue?

**Comment by sean-mcmanus** [comment]
@bobbrow This should be unrelated to the document symbol api, which just enables us to supply ranges to symbols, unless perhaps if returning those ranges causes VS Code to send us less symbol requests (which I doubt). After an edit, VS Code sends us a new documentSymbol request so we probably need to optimize that better.

**Comment by bobbrow** [comment]
I don't repro this with the latest version of the extension. If it is not fixed for you, please let us know.
