### ISSUE TITLE
Feature req: Ability to generate definitions/declarations

### ISSUE THREAD

**Issue by yannickbt64** [microsoft/vscode-cpptools#3056]
Hi,

We use here VSCode for application internals and QT creator for UI related stuff.
One feature I love about QT Creator is the ability to generate declarations/definitions.

Let me explain.
Let's say for example I'm inside "source.cpp", then I can rightclick on myClass::FunctionDefinition and I can click on "Add definition inside source.h", which will add the function prototype inside the myClass class if not present.

If I am inside "source.h", I can do the inverse: generate inside "source.cpp" the definition of the function prototype I want. An image showing it:
![](https://i.stack.imgur.com/shk3N.png)

This also applies to variables.

Needless to say it improves a lot productivity when you have multiple definitions/declarations to write (for example when you start a new header/source pair).
I'd love to have this feature available inside VSCode. In my opinion, it's a certainly something I miss.

**Comment by sean-mcmanus** [comment]
Thanks for the feedback. We eventually plan to add this -- it's already being tracked by https://github.com/Microsoft/vscode-cpptools/issues/664 .
