### ISSUE TITLE
environment variable settings lost on remote debug

### ISSUE THREAD

**Issue by erik2047** [microsoft/vscode-cpptools#3057]
Type: Debugger

Summary: The environment variables I set in launch.json don't get passed to GDB when I try to do remote debugging through gdbserver.

- OS and Version: Ubuntu 18.04
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.20.1
- Other extensions you installed (and if the issue persists after disabling them): no other extensions are loaded
- A clear and concise description of what the bug is.

I have two nearly identical configurations.  One has the "miDebuggerServerAddress" value set and the other does not.  Only for the latter configuration do the environment variables set in the configuration get passed to the debugger.  I can check this outcome using a wrapper around GDB that dumps the environment variables.

**To Reproduce**
// Here is the sample configuration.  The alternate versions can be created by 
// either commenting or uncommenting the line with "miDebuggerServerAddress"
        {
            "name": "(gdb) Extra Config",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/test",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "miDebuggerPath": "/home/erik/bin/Egdb",
            //"miDebuggerServerAddress": "localhost:8010"
            "environment": [ 
                {"name": "foo", "value": "Barbarbar"},
                {"name": "CROW", "value": "joe"},
                {"name": "Blow", "value": "YUP!"}
            ],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },

Running test with miDeguggerServerAddress line commented produces this in the Debug Console:

hello from Egdb
Egdb TERM=xterm-256color
Egdb foo=Barbarbar
Egdb CROW=joe
Egdb Blow=YUP!
=thread-group-added,id="i1"
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git

Running test with the miDeguggerServerAddress line uncommented produces this in the console:
hello from Egdb
Egdb TERM=xterm-256color
Egdb foo=
Egdb CROW=
Egdb Blow=

The second example requires starting gdbserver, of course.  Note that the TERM variable is set in the SHELL where VS Code is started.

This is Egdb (the GDB wrapper):
#!/bin/bash
echo "hello from Egdb"
echo "Egdb TERM=$TERM"
echo "Egdb foo=$foo"
echo "Egdb CROW=$CROW"
echo "Egdb Blow=$Blow"
exec /usr/bin/gdb $*

The test program is basically a "hello world!" program.

**Comment by pieandcakes** [comment]
@erik2047 Thats by design. In the instance where you are debugging `gdb` to `gdbserver`, the entire program setup on the `gdbserver` side needs to be completed by you prior to starting debugging. This is explained in the documentation for `gdbserver`.

If you want to set it up through our `launch.json` i would suggest you look at using `ssh` through our `pipeTransport` settings instead.

**Comment by erik2047** [comment]
I assumed it was by design and wanted to make sure.  Thanks

**Comment by pieandcakes** [comment]
I don't think we can tell the schema to say if you specify one property that this other property should error so unfortunately we don't have a good mechanism to tell the user which properties won't be handled.
