### ISSUE TITLE
Unable to start debugging

### ISSUE THREAD

**Issue by MaryRit** [microsoft/vscode-cpptools#3058]
Type: Debugger

This problem occures every time I attempt to debug. I've tried re-launching the application or restarting the machine, didn't work. Tried to look it up everywhere, didn't work. Please help!

1) The launch.json file:

   {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/lalala.cpp",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb"
        }
    ]
}   

2)Tasks.json file:
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "g++ -g lalala.cpp -o lalala",
            "group":{
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher":"$gcc"
        }
    ]
}

3)The running program:

#include <iostream>
using namespace std;

int main()
{
    cout << "Hello *redacted*" << endl;
    cout << "Put your numbers here: " << endl;
    int x, y;
    cin >> x >> y;
    cout << x << " + " << y << " = " << x + y << endl;
    cout << x << " - " << y << " = " << x - y << endl;

    return 0;
}

4)The problem:
Unable to start debugging. Program path '/Users/illa/Desktop/🖥MyProjects/🏈C++)/lalala.cpp' is missing or invalid.

LLDB failed with message: Command 'file-exec-and-symbols'. Target binary '/Users/illa/Desktop/🖥MyProjects/🏈C++)/lalala.cpp' is invalid. error: '/Users/illa/Desktop/🖥MyProjects/🏈C++)/lalala.cpp' doesn't contain any 'host' platform architectures: x86_64h, x86_64, i386

This may occur if the process's executable was changed after the process was started, such as when installing an update. Try re-launching the application or restarting the machine.

**Describe the bug**
- OS Mojave 10.14
- VS Code Version: 1.30.2
- C/C++ Extension Version: C/C++ for Visual Studio Code
- Other extensions you installed (and if the issue persists after disabling them): I had the Code Runner installed but now it's uninstalled.

[pieandcakes] Edited to remove inappropriate language.

**Comment by pieandcakes** [comment]
@MaryRit your problem is that your `program` target is the cpp file. You need to specify in the `program` field your executable, which looks like from your task is `lalala`.

The error message `Unable to start debugging. Program path '/Users/illa/Desktop/🖥MyProjects/🏈C++)/lalala.cpp' is missing or invalid.` tells us this.
