### ISSUE TITLE
Ability to run dependency update via terminal

### ISSUE THREAD

**Issue by stefan-schweiger** [microsoft/vscode-cpptools#306]
As far as I have noticed there doesn't seem to be the ability to start the dependency update process via a terminal command. Which makes it really cumbersome to deploy the extension automatically on a large multiuser system.
Maybe any advice how do do this or plans to integrate such a "feature"?

**Comment by delmyers** [comment]
@stefan-schweiger, can you describe to us your ideal scenario? How would you like this to work?

**Comment by stefan-schweiger** [comment]
@delmyers since I don't know if the dependency update process is started by VS Code or the extension I'm not sure how feasible my idea is. But ideally something like `code --updateDependencyies`. Or at least a script inside the extension folder of your extension which is called `updateDependencies.sh` or whatever, really anything that can be done with just terminal commands is fine for me.

Also an out of the box way of installing extensions global would be nice, since now we have to do this for one user and then move the extension folder into the global extension folder. But this is more on the VSC side of things then on yours.

**Comment by bobbrow** [comment]
I'm not sure if this is still an issue for you, but I just linked to an issue I created for VS Code related to this.  [VS Code also has a setting](https://code.visualstudio.com/docs/editor/extension-gallery#_auto-update-extensions) to automatically update extensions (if that is an option)

**Comment by michelleangela** [comment]
Closing this issue as the last response is more than a year old.
