### ISSUE TITLE
goto/peak definition does not work for some 'noexcept' functions

### ISSUE THREAD

**Issue by CuriousRubick** [microsoft/vscode-cpptools#3060]
**Type: LanguageService**

**Describe the bug**
- OS and Version: win10, latest
- VS Code Version: latest, stable and insiders
- C/C++ Extension Version: latest, stable and insiders
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

Create a new project with a single header and src file. Create the following class in the header:

struct Test
{
    void Test();
    void TestNoexcept() noexcept;
    void TestNoexcept(int i) noexcept;
};

Add the following to the source

void Test::Test()
{
}

void Test::TestNoexcept() noexcept
{
}

void Test::TestNoexcept(int i) noexcept
{
}

Goto/peek definition does not work for the middle TestNoexcept function. Instead, it goes to the last function with the int parameter. If the last function's declaration and definition are commented out, then goto doesn't find any definition.

**Comment by sean-mcmanus** [comment]
Yeah, Bob discovered this bug last Thursday, but I was out sick so it won't make 0.21.0, but we'll try to fix it for our next Insider release in a few days.

**Comment by sean-mcmanus** [comment]
Go to Def with noexcept methods is fixed with 0.22.0-insiders. You can get it via setting the C_Cpp.updateChannel setting to "Insiders", or downloading it manually from https://github.com/Microsoft/vscode-cpptools/releases .
