### ISSUE TITLE
Don't see the output (printf on stdout) of C program

### ISSUE THREAD

**Issue by jmsfez** [microsoft/vscode-cpptools#3062]
Type: Debugger

Hi, I **don't see the output (printf on stdout) of C program**, whether I run the program in debug mode (Debug | Start Debugging) or not (Debug | Start Without Debugging).

My configuration is:
— **macOS Mojave Version 10.14.2**
— VS Code Version **1.30.2**
— C/C++ Extension Version **0.20.1**
— **c_cpp_properties.json**
![image](https://user-images.githubusercontent.com/28300202/51529198-8fbc6080-1e38-11e9-9f29-7aba002fe9dd.png)
— **tasks.json**
![image](https://user-images.githubusercontent.com/28300202/51529301-b37fa680-1e38-11e9-9ee3-0d0b629a857d.png)
— **launch.json**
![image](https://user-images.githubusercontent.com/28300202/51529360-cd20ee00-1e38-11e9-8b3b-26a0f29d660c.png)
— **hello.c**
![image](https://user-images.githubusercontent.com/28300202/51529397-e2961800-1e38-11e9-9ecd-e88cddb61d13.png)

**I perform the following operations:**
1) I select **Terminal | Run Build Tasks...**
    > It works perfectly, i.e., the hello.o file is generated 
![image](https://user-images.githubusercontent.com/28300202/51529608-57695200-1e39-11e9-865e-3693554ee3e1.png)
2) I select **Debug | Start Debugging** but **without any Breakpoint**
    > It seems to succeed since the DEBUG CONSOLE specified
        **The program '/Users/jsfez/dev/ora/hello' has exited with code 0 (0x00000000).**
    > But there is no output of "Hello\nFoo Bar\n" neither in the DEBUG CONSOLE, nor in the OUTPUT.
    > Here is the DEBUG CONSOLE
![image](https://user-images.githubusercontent.com/28300202/51529925-1160be00-1e3a-11e9-821b-011f7228ad55.png)
    > Here is the OUTPUT
![image](https://user-images.githubusercontent.com/28300202/51529990-3bb27b80-1e3a-11e9-97f7-e529dfbe7ce0.png)

**I try to perform the following operations:**
1) I move to **hello.c:line6** and select **Debug | Toggle Breakpoint** to add a breakpoint
![image](https://user-images.githubusercontent.com/28300202/51530546-7c5ec480-1e3b-11e9-9905-264c0aee34a6.png)
2) I select **Debug | Start Debugging**
![image](https://user-images.githubusercontent.com/28300202/51531035-a2389900-1e3c-11e9-95eb-163c816c75d8.png)
    > The program stop correctly and show me that the variable **i = 0**.
    > But there is no output of "Hello\n" neither in the DEBUG CONSOLE, nor in the OUTPUT.
![image](https://user-images.githubusercontent.com/28300202/51531141-edeb4280-1e3c-11e9-959a-987b5ceccbee.png)
3) I select **Step Over**
![image](https://user-images.githubusercontent.com/28300202/51531174-15420f80-1e3d-11e9-9cdc-4475568ec8f0.png)
    > The program stop correctly and show me that the variable **i = 1**.
    > But there is still no output of "Hello\n" neither in the DEBUG CONSOLE, nor in the OUTPUT.

I'm completely new to Visual Source Code (I'm used to develop with vi).
So, any detailed help would be greatly appreciated 😉

**Comment by pieandcakes** [comment]
@jmsfez When debugging on macOS, you will see a separate `Terminal` window pop up with your output. This is due to a limitation within `lldb-mi` that doesn't allow us to redirect debuggee output.

**Comment by jmsfez** [comment]
Thanks for your answer @pieandcakes.
I did not notice the opening of a Terminal window.
Is there an alternative solution to `lldb` that is better integrated, avoiding the use of an external Terminal window?

**Comment by pieandcakes** [comment]
@jmsfez Not with our extension at this time.
