### ISSUE TITLE
Intellisense marks unnamed struct/union members as errors, but gcc does not

### ISSUE THREAD

**Issue by nurbles** [microsoft/vscode-cpptools#3063]
**Type: LanguageService**
I am not sure if I am asking for a feature or reporting a bug. I believe it is about something that intellisense is doing wrong, but since it could have been intentionally left out (because a developer didn't know gcc supported this feature, perhaps) I may be asking for a new feature. Or, most likely, I just cannot discover the correct combination of settings to get intellisense to work as I need.

I am using (I update EVERY day before starting to use vscode):
```
Ubuntu 18.04.1.LTS
VSCode Version: 1.31.0-insider
Commit: e9bb33f
Date: 2019-01-21T06:16:03.813Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-43-generic
C/C++ Intellisense extension version: 0.21.0-insiders4
```
**The issue I am reporting (or feature I am requesting)**
I started using the **-fms-extensions** switch on the gcc command line to allow unnamed struct/union members, but intellisense is flagging all references to those members as errors. (I'm building on an embedded box, so vscode doesn't get any compiler output [which has zero errors or warnings[).

I had learned to like vscode/intellisense's ability to let me know about errors BEFORE I sent the source to the embedded box to be built, but now my code shows too many errors that actually are NOT errors for me to find all the REAL mistakes I make! Hopefully intellisense can stop flagging these valid statements as errors, at least when told to allow them (but how is that done?)

I am using this for c_cpp_properties.json ((updated to a corrected c_cpp_properties.json file):
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/lib/gcc/x86_64-linux-gnu/7/include",
                "/usr/local/include",
                "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include"
                           ],
            "defines": [ "RM23S", "VerNum=0x00010000" ],
            "compilerPath": "/usr/bin/gcc -fms-extension",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```
If I have this source file:
```
typedef struct UnnamedTest_s
{
   int   a;
   union Unnamed_u
   {
      unsigned char Byte;
      unsigned short Word;
      unsigned long Dword;
   };
   int   b;
   unsigned char  uc;
   unsigned short us;
   unsigned long  ul;
} UnnamedTest;

int main( int argc, char **argv )
{
   UnnamedTest test;
   
   test.uc = test.Byte;
   test.us = test.Word;
   test.ul = test.Dword;
   return 0;
}
```
The **Byte**, **Word**, and **Dword** members have the red squiggly underline that indicates and error.  However, the **-fms-extensions** switch means those **are not** errors.

**Expected behavior**
I do not expect intellisense to mark valid code as an error.

**Reference**
The gcc documentation says that unnamed fields are allowed by C11 and supported by gcc:
[gcc Unnamed Fields](https://gcc.gnu.org/onlinedocs/gcc/Unnamed-Fields.html#Unnamed-Fields)

**Comment by nurbles** [comment]
Is this project still alive?  No comment or even acknowledgement of the message in over a week makes me think not.  Is there a different, newer and still maintained Intellisense extension?  If so, please let me know what it is called so I can switch to using it instead of this broken, um, somewhat less than complete one.  Thanks!

**Comment by bobbrow** [comment]
Sorry, we have a lot of issues coming through and sometimes one is accidentally missed.  Thank you for bringing this to our attention.  We'll update this issue with a response today.

**Comment by sean-mcmanus** [comment]
We don't support the -fms-extensions flag at all for gcc/Linux. We support it with MinGW, but even with that case the bug described here still repros and it repros with VS too, so it looks like our parser doesn't support this scenario yet. I'll look into filing a bug with VS (the developer community site is buggy and not currently showing the bug I reported).

**Comment by sean-mcmanus** [comment]
I filed a bug with VS 2017 at https://developercommunity.visualstudio.com/content/problem/439947/c-language-intellisense-marks-unnamed-structunion.html . Once that is fixed we can enable -fms-extensions with gcc/clang on Linux. But my bug got logged as internal instead of external, so it doesn't look like people can view it until they move it out of the Internal section.

@nurbles Yeah, sorry for the delayed response.

**Comment by nurbles** [comment]
FWIW, the anonymous struct/union stuff is also part of C11 and should also be working when C11 is selected as the cStandard.  At least, that is how I understand the cStandard setting for intellisense to be intended.

**Comment by sean-mcmanus** [comment]
I don't know whether it's in the standard or not, but if you enter that code into https://godbolt.org/ it doesn't compile with gcc or clang without the -fms-extensions, and our parser tries to mimic those compiler behaviors and not the standards (i.e. if the compilers don't follow it).

**Comment by sean-mcmanus** [comment]
There's a public issue at https://developercommunity.visualstudio.com/content/problem/440407/c-intellisense-marks-unnamed-structunion-members-a.html -- so upvoting that would help get a fix.

**Comment by nurbles** [comment]
Again, FWIW, removing the tag from the union in my example (Unnamed_u) allows the example to compile fine at https://goodbolt.org using the latest GCC with only the -std=c11 option enabled.  The -fms-extensions option allows union/struct with tags to also be used anonymously.

Also, thanks for listening!  These extra comments aren't additional complaints, just my attempt to make sure whoever ends up designing and working on this issue is aware of the facts.  I'm headed over to upvode the public issue right after I post this.

But... I can no longer resist mentioning that I got a chuckle from Microsoft's Intellisense not supporting GCC's switch that enables Microsoft extensions to the language.  :-D

**Comment by sean-mcmanus** [comment]
So it sounds like removing the tag from the union solves your IntelliSense issue as well? It appears to do that for me. But having the tag and other -fms-extensions (such as designated initializers in C) would be preferred?

**Comment by nurbles** [comment]
I checked and it does appear that removing the tags works.  That is a bit of a problem for me, since the headers I'm working with that contain all these things are created for and shared with several VS2017 projects that build Windows 10 software.  I'm working on the linux side of a communication channel and need to use the same data structures.  I can hopefully get the tags removed from the primary copies of the files so that I don't lose my local changes (tag removals) should the primary be updated.

And yes, I don't think I could ever be convinced that Microsoft's syntax analysis tool is complete without supporting Microsoft's language extensions.  <smile>  Thanks again for your continued attention and interest in this issue!

[Edit]  Also, my linux target is an embedded system with an older gcc compiler (4.6.3) that pre-dates the -std=c11 option, but supports the -fms-extensions option.  I'm OK with using the c11 option in VSCode which running in Ubuntu 18.04 with gcc 7.3.0.  AFAIK, the only ms/c11 extension I need is the anoymous struct members and it appears that the -fms-extensions option supports the c11-type anonymous struct members.

**Comment by sean-mcmanus** [comment]
-fms-extensions should be usable with the latest Insiders: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.22.2-insiders .

However, there are other known bugs related to how we deal with that flag, so you might hit those.
