### ISSUE TITLE
Tag database can get corrupted. We need an automatic way to resolve this.

### ISSUE THREAD

**Issue by arijun** [microsoft/vscode-cpptools#3064]
**Type: LanguageService**

- OS and Version: Debian 8.10
- VS Code Version: - C/C++ Extension Version: 1.30.2 - 0.20.1
- Other extensions: Gitlens, vscode-icons

Using ctrl-shift-o to bring up the go to symbol menu, I immediately get the response "No symbols found". This is in all files in my project (in other projects it works).

After enabling logging, I see a whole lot of "Unable to add file to database", including the file I'm trying to find a symbol in.

I've included the relevant part of my c_cpp_properties.json
```
        {
            "name": "Simple",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}",
                "${workspaceFolder}/path/to/include",
                "${workspaceFolder}/path/to/other/include"
            ],
            "defines": ["mydefine"],
            "compilerPath": "/usr/bin/clang++-3.5",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "forcedInclude": [
                "path/to/forced/include.h"
            ],
            "browse": { 
                "path": [
                    "${workspaceFolder}/**",
                    "${workspaceFolder}",
                    "${workspaceFolder}/path/to/include",
                    "${workspaceFolder}/path/to/other/include"
                    ],
                "limitSymbolsToIncludedHeaders": true
            }

        },
```

Let me know if I can provide more information.

**Comment by sean-mcmanus** [comment]
Yeah, there's some problem adding the file to the database, which will cause the symbols to not get parsed/added. What is the error number? Is there a dangling Microsoft.VSCode.CPP.Extension process that has a file lock on the database file?

**Comment by austenc** [comment]
Also encountering this all of a sudden. Is there a docs page that explains how to debug the internal language service? Happy to provide more info, just not sure how yet!

**Comment by sean-mcmanus** [comment]
@austenc The language server process is closed source. You could attach a debugger to the process and see call stacks or open the database files in a SQLite editor, but I don't think that would be enough to find a cause/fix. If you can provide a simple repro project, that might help the most.

**Comment by lucascoxBAF** [comment]
Ran into this problem yesterday running latest on Ubuntu. Turns out there was a dangling process that had a lock. After killing all of the extension process and restarting the problem went away.

**Comment by ashish5679** [comment]
I also got the same issue on one of my remote ssh workspace.
debug - it happens only for one particular root-folder where workspace and all codebase is present. If I simply rename root folder the issue disappears.
so somehow global database gets corrupted for one particular name of root folder.

**Comment by sean-mcmanus** [comment]
@ashish5679 You may have a dangling cpptools process that has a lock on the database. Killing all the cpptools processes (or restarting your machine) may fix the issue.

**Comment by bobbrow** [comment]
Linking to #5316

**Comment by Colengms** [comment]
We think this issue is either already addressed by related fixes, or tracked by https://github.com/microsoft/vscode-cpptools/issues/5316 .  Closing this one.
