### ISSUE TITLE
cpptools auto-install windows debuger fail

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-cpptools#307]
_From @mazhan465 on October 26, 2016 4:27_

Downloading package 'Visual Studio Windows Debugger' (12073 KB) .................... Done!
Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
Error: write EPROTO 0:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:y:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:769:

_Copied from original issue: Microsoft/vscode#14503_

**Comment by weinand** [comment]
In the future please file extensions specific issues against the corresponding extension itself and not against VS Code.

**Comment by pieandcakes** [comment]
@mazhan465 Can you attempt to close and reopen VSCode and see if it will retry the download?

**Comment by pieandcakes** [comment]
@mazhan465 is this related to issues #316 and #309 that you opened?

**Comment by pieandcakes** [comment]
Since I haven't heard back, I'm closing this issue. If its still an issue, please update and reopen.
