### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yspef** [microsoft/vscode-cpptools#3073]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.20.1`
- OS Version: `Linux x64 4.9.0-8-amd64`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/facundo/ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
No performance info is attached. We need more info.

**Comment by bobbrow** [comment]
Consolidating performance reports from VS Code.  Tracking with #2991.
