### ISSUE TITLE
c_cpp_properties.json compilerPath failes when path contains spaces

### ISSUE THREAD

**Issue by Wetmelon** [microsoft/vscode-cpptools#3077]
**Type: LanguageService**

**Describe the bug**
- OS and Version:  **Windows 10**
- VS Code Version: **1.30.2**
- C/C++ Extension Version: **0.21.0**
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

"compilerPath:" in c_cpp_properties.json no longer supports paths with spaces.  It was working fine for the last few months, then with 0.21.0 it fails.  For example, my compiler is located at:

`C:/Program Files (x86)/GNU Tools ARM Embedded/7 2018-q2-update

`"compilerPath": "C:/Program Files (x86)/GNU Tools ARM Embedded/7 2018-q2-update/bin/arm-none-eabi-g++.exe -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -specs=nosys.specs -specs=nano.specs -u _printf_float -u _scanf_float"`

In the C/C++ Firmware output window, I get the error `Failed to query default include paths and defines for C:/Program. WSL not detected`

This causes missing includes e.g. `#include <stdlib.h>` shows up as an error  with `Cannot open source file "stdlib.h"`

![image](https://user-images.githubusercontent.com/3612694/51645006-4820fc00-1f40-11e9-973e-87f97cba364d.png)

**Comment by sean-mcmanus** [comment]
You need to change it to:
`"compilerPath": "\"C:/Program Files (x86)/GNU Tools ARM Embedded/7 2018-q2-update/bin/arm-none-eabi-g++.exe\" -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -specs=nosys.specs -specs=nano.specs -u _printf_float -u _scanf_float"`. As in, the path with spaces requires `\"` around it.

Does that fix the issue for you?

This requirement didn't change with 0.21.0.

I don't know what "C/C++ Firmware output window" means. Our output window is just C/C++.

**Comment by Wetmelon** [comment]
Ok, I see the issue there.  Yes, that escaped path works.  The reason I only saw it crop up with 0.21.0 was because I am using a Windows environment variable called "ARM_GCC_ROOT" which contains the unescaped path `C:\Program Files (x86)\GNU Tools ARM Embedded\7 2018-q2-update`.  And then I have:

`"compilerPath": "${ARM_GCC_ROOT}/bin/arm-none-eabi-g++.exe -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -specs=nosys.specs -specs=nano.specs -u _printf_float -u _scanf_float",`

Did the variable substitution go from being escaped to unescaped with 0.21.0?

----

Oh, hehe.  My output dropdown shows "C/C++: Firmware"... I guess because I'm in the Firmware folder in my project.  Oops 😀

----

EDIT:  Escaping the variable seems to fix it.  `compilerPath: "\"${ARM_GCC_ROOT}/bin/arm-none-eabi-g++.exe\"`

**Comment by sean-mcmanus** [comment]
The code for environment variable replacement is in our open source TypeScript at https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/common.ts (resolveVariables function). That code has not changed from 0.20.1 to 0.21.0. We have never added quotes to environment variable expansion.

**Comment by Wetmelon** [comment]
Strange.  Anyway, sounds like it works by design and I'm dumb so thanks 😁
