### ISSUE TITLE
c_cpp_properties.json compilerPath doesn't seem to look at Windows PATH environment variable

### ISSUE THREAD

**Issue by Wetmelon** [microsoft/vscode-cpptools#3078]
**Type: LanguageService**

**Describe the bug**
- OS and Version:  **Windows 10**
- VS Code Version:  **1.30.2**
- C/C++ Extension Version: **0.21.0**
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Using just the .exe name of a compiler in `compilerPath` in c_cpp_properties.json causes it to fail.  This has been happening since `compilerPath` was introduced.  E.g. `compilerPath: "g++"`

![image](https://user-images.githubusercontent.com/3612694/51645335-d21d9480-1f41-11e9-85c9-bff328638c4a.png)

Error in C/C++ Firmware Output window: `Failed to query default include paths and defines for g++. WSL not detected`

When I simply type `g++ --version` into a VSCode Powershell terminal, it works fine, so I have my PATH setup properly:

![image](https://user-images.githubusercontent.com/3612694/51645311-b914e380-1f41-11e9-999d-437d119b3d80.png)

-------

A more realistic example:
`"compilerPath": "arm-none-eabi-g++ -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -specs=nosys.specs -specs=nano.specs -u _printf_float -u _scanf_float",`

![image](https://user-images.githubusercontent.com/3612694/51645376-f11c2680-1f41-11e9-9c84-68cebf6db983.png)

`Failed to query default include paths and defines for arm-none-eabi-g++. WSL not detected`

![image](https://user-images.githubusercontent.com/3612694/51645380-fb3e2500-1f41-11e9-9eb5-2c002da084bb.png)

In Terminal:  `arm-none-eabi-g++ --version`: 

![image](https://user-images.githubusercontent.com/3612694/51645404-16109980-1f42-11e9-868f-9733923dc52c.png)

**Comment by sean-mcmanus** [comment]
This is currently "by design", but given that we're looking to improve the configuration experience for our next release, this would be one way to help with that.

**Comment by tdjastrzebski** [comment]
It seems adding env variable support will not break anything but in some cases will help a lot.
Example: on my computer I have 2 versions of Visual Studio and 20 (twenty) versions of cl.exe compiler. Managing this with single PATH variable is impractical. I have to use distinct environment variables to store paths to x86, x64, ARM current version to avoid hardcoding.
Also, current behavior is inconsistent with other config files (tasks, launch etc.).

**Comment by bobbrow** [comment]
We implemented this feature with PR #5965.  It currently available in our 0.30.0-insiders3 which you can install by changing the C_Cpp.updateChannel setting to "Insiders".
