### ISSUE TITLE
Array with variable for dimension producing error, compiles correctly

### ISSUE THREAD

**Issue by NeilBaner** [microsoft/vscode-cpptools#3079]
Issue Type: <b>Bug</b>

In C, creating a variable-length array produces an error in VSCode, but not in the compiler (gcc) and program works as expected. 

1. Declare and assign an int variable (e.g. int dim = 7;)

2. Declare an array with dimension as that int (e.g. int array[dim];)

3. An error "Expression must have a constant value" is produced

4. Compiling the code (with gcc) does not produce an error and the program works correctly. 

Extension version: 0.21.0
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sean-mcmanus** [comment]
This works for me. You need to set your compilerPath to a gcc/non-cl.exe compiler and set your intelliSenseMode to "gcc-x64". Does that fix it?

**Comment by NeilBaner** [comment]
Thanks for the tip. It works as expected now. Please forgive my ignorance,
I am only beginning to learn proper programming. Should I delete this issue
or something, then?

**Comment by sean-mcmanus** [comment]
That's okay. We're planning to do work to help new user properly configure things and diagnose failures.
