### ISSUE TITLE
Visualizer files (.natvis) support does not seem to work on linux

### ISSUE THREAD

**Issue by filipsky** [microsoft/vscode-cpptools#308]
Hi,
first I'd like to thank you for this extermely useful extension.

The thing I'm not able to configure is the .natvis file support (in the launch.json file)
It does not matter what I write there, the debugger output is always the same.
One more thing: is it possible to add more .natvis files?

Thanks, Honza

**Comment by jacdavis** [comment]
There was a bug that natvis wasn't being honored by the gdb/lldb configuration. This has been fixed but the fix hasn't yet been released. When this ships, it will be possible to add natvis files via the launch.json.

**Comment by filipsky** [comment]
Thanks for your quick reply.
Looking forward to the next update then!

Best, Honza

**Comment by pieandcakes** [comment]
The fix for this should be in 0.9.3. Please update the extension and let me know if this resolves your issue. Thanks

**Comment by filipsky** [comment]
Hi,
thanks for the fix.
The natvis support now sort of works, but I have two problems on MacOS
- natvis visualization does not work on tooltips - it says "Explicit refresh required for visualized expressions"
- when I try to expand the [Visualized expression] in the watch window, the LLDB crashes with this eror:
ERROR: LLDB exited unexpectedly with exit code 139 (0x8B). Debugging will now abort.

also when i write -exec version to the debugger console, it prints lldb-350.99.0, but I have lldb-360.1.65 installed on my system, maybe the newer lldb can fix it

Should I file new issues?

Thanks, Honza

**Comment by pieandcakes** [comment]
@filipsky Can you share what you are trying to visualize? We provide and support a version of lldb that will work with our extension because it has specific fixes in place to work. Visualization with natvis is done by our middle layer and not by lldb so I'd be interested to see why it is crashing.

**Comment by filipsky** [comment]
@pieandcakes the LLDB crashes on visualizing std::strings and QT QStrings, I did not try anything more complex. Is there some option to generate a log for you to analyze? Do you want me to send you my natvis file?

**Comment by pieandcakes** [comment]
@filipsky if you can send me your natvis file and a small repro code file I can try and repro it to see what is wrong. We snapped to a specific version of lldb because we have fixes that we needed to add to support our scenario. This is why the version that `-exec version` returns doesn't match what is on your machine.
