### ISSUE TITLE
Installing C/C++ package updates fails when multiple windows are open.

### ISSUE THREAD

**Issue by dudamoos** [microsoft/vscode-cpptools#3084]
Issue Type: <b>Bug</b>

Have VSCode launch with multiple windows (configuring it to re-open all windows and then exiting and re-launching VSCode while multiple windows are open should do the trick). When The C/C++ extension tries to update it's dependencies, it will fail. Usually the downloading works just fine, but when trying to install the updated packages, the multiple extension host processes (one per window by the looks of it) will trip over each other when trying to replace the same file at the same time. Sometimes, 1 extension host process may succeed in fully completing the installation, but often none of them do.

**Additional context**
Output pane text from window 1:
```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (5622 KB)  Done!
Downloading package 'ClangFormat (Windows)' (1054 KB)  Done!
Downloading package 'Visual Studio Windows Debugger' (12386 KB)  Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: EPERM: operation not permitted, open 'c:\Users\qz409d\.vscode\extensions\ms-vscode.cpptools-0.21.0\bin\Microsoft.VSCode.CPP.Extension.exe.tmp'

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
```

Output pane text from window 2:
```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (5622 KB)  Done!
Downloading package 'ClangFormat (Windows)' (1054 KB)  Done!
Downloading package 'Visual Studio Windows Debugger' (12386 KB)  Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: ENOENT: no such file or directory, rename 'c:\Users\qz409d\.vscode\extensions\ms-vscode.cpptools-0.21.0\bin\Microsoft.VSCode.CPP.Extension.exe.tmp' -> 'c:\Users\qz409d\.vscode\extensions\ms-vscode.cpptools-0.21.0\bin\Microsoft.VSCode.CPP.Extension.exe'

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
```

Extension version: 0.21.0
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Colengms** [comment]
This should get addressed by: https://github.com/microsoft/vscode/issues/23251

**Comment by bobbrow** [comment]
https://github.com/microsoft/vscode/issues/23251 is complete and we no longer download extra binaries after installation. Any remaining issues around installation would be VS Code bugs at this point.
