### ISSUE TITLE
autoplace semicolon (after class, struct, enum definitions)

### ISSUE THREAD

**Issue by oktonion** [microsoft/vscode-cpptools#3087]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10, latest Ubuntu etc...
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them): none

So the suggestion is to auto place semicolon after **class**, **struct**, **enum** and **union** definition. Since we have already autocompletion for the brackets, when `struct A {|` completes to `struct A{ | }` why not to put a semicolon after brackets to complete **class**, **struct** etc. definition like `struct A{ | };`. It really bugs me to put semicolon every time at the end of definition.

**To Reproduce**
1. Type `struct A {|`
2. Auto complete will do its job: `struct A{ | }`
3. Observe error squiggles - missing semicolon after **struct** definition!
4. Put semicolon by hand

**Expected behavior**
Autocomplete with semicolon at the end of **class**, **struct**, **enum** and **union** definition.

**Comment by sean-mcmanus** [comment]
We have struct/class/etc. snippets that do this. Have you tried that or is the snippet behavior not desirable? VS Code itself auto-completes the }, but there is no way for us to change that behavior and add a ";" at the end.

**Comment by sean-mcmanus** [comment]
I've filed a feature request with Visual Studio Code at https://github.com/Microsoft/vscode/issues/67090 (you could upvote that).

**Comment by oktonion** [comment]
Oh, thank you. It is confusing sometimes to distinguish the job of extension and the editor itself.

**Comment by xgdgsc** [comment]
Is it possible to auto add semicolon after `break`?

**Comment by sean-mcmanus** [comment]
@xgdgsc You mean as part of the keyword completion? I think that's the only place it could be added. i.e.
![image](https://user-images.githubusercontent.com/19859882/155601471-feb30a4e-48c0-496d-b233-067cc2aa603c.png)

I've filed an issue at https://github.com/microsoft/vscode-cpptools/issues/8932 .

**Comment by imtangsheng** [comment]
I solved the problem here
https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by sean-mcmanus** [comment]
The VS Code team closed it due to not enough upvotes: https://github.com/microsoft/vscode/issues/67090

**Comment by ModyxOstora** [comment]
I tried to solve this problem by making an extension called C++ Class/Struct Auto Semicolon & Bracket, I published it in vs code so give it a try🙂
