### ISSUE TITLE
Reprompt for the configuration provider if c_cpp_properties.json is deleted

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3088]
Suggested in https://github.com/Microsoft/vscode-cpptools/issues/2843#issuecomment-457136598 .

Maybe we can add other code to detect/prompt users for a missing configurationProvider setting as well.

Didn't make 0.23.0-insiders.

**Comment by bobbrow** [comment]
This was addressed along with #2346 in 0.27.0.

**Comment by sean-mcmanus** [comment]
@bobbrow Can you clarify? That issue seems unrelated. I don't recall seeing a fix for this. I had PR with the fix, but then I never got finished with my testing of it.

**Comment by sean-mcmanus** [comment]
Ok, I see the fix now.
