### ISSUE TITLE
cquery seems to die continuously

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3090]
I am trying to use cquery with vscode but cquery seems to die continuously with a jsonrpc error `(   0.758s) [stdin        ]            lsp.cc:205   | Bad or missing jsonrpc version`. I assume because the language server is not responding as expected.
This is on ubuntu 18 (KDE Neon 5.14).

If I could help you find the cause of the crashes, I would gladly do so. But I don't know where to start.

My relevant settings in vscode:

```
  "C_Cpp.autocomplete": "Disabled",
  "C_Cpp.formatting": "Disabled",
  "C_Cpp.errorSquiggles": "Disabled",
  "C_Cpp.intelliSenseEngine": "Disabled",
  "cquery.highlighting.enabled.types": true,
  "cquery.highlighting.enabled.freeStandingFunctions": true,
  "cquery.highlighting.enabled.memberFunctions": true,
  "cquery.highlighting.enabled.freeStandingVariables": true,
  "cquery.highlighting.enabled.memberVariables": true,
  "cquery.highlighting.enabled.namespaces": true,
  "cquery.highlighting.enabled.macros": true,
  "cquery.highlighting.enabled.enums": true,
  "cquery.highlighting.enabled.typeAliases": true,
  "cquery.highlighting.enabled.enumConstants": true,
  "cquery.highlighting.enabled.staticMemberFunctions": true,
  "cquery.highlighting.enabled.parameters": true,
  "cquery.highlighting.enabled.templateParameters": true,
  "cquery.highlighting.enabled.staticMemberVariables": true,
  "cquery.highlighting.enabled.globalVariables": true,
  "cquery.cacheDirectory": "${workspaceFolder}/.vscode/cquery_cached_index/",
  "cquery.launch.command": "/home/elco/opt/cquery/build/release/bin/cquery",
``` 

Latest version of vscode-cpptools (0.21.0) and cquery compiled from latest source.

_Originally posted by @elcojacobs in https://github.com/Microsoft/vscode-cpptools/issues/2972#issuecomment-457265611_

**Comment by sean-mcmanus** [comment]
@elcojacobs Can you file an issue with the CQuery extension at https://github.com/cquery-project/vscode-cquery/issues or are you saying there is some bug with how our C/C++ extensions interacts with CQuery? Is this is a regression from 0.21.0?

**Comment by elcojacobs** [comment]
A downgrade to 0.20.1 seems to make it work without problems.

I don't know whether the bug is in cpptools or cquery, but changing the cpptools version makes a difference.

As soon as I upgrade to 0.21.0, I get errors like these:
```
[Error - 1:19:46 PM] Request textDocument/documentSymbol failed.
  Message: Unable to find file /home/elco/repos/firmware/app/brewblox/test/BrewBloxTestBox.h
```

``` 
elco@elco-workstation:~/repos/firmware$ ls -ahl /home/elco/repos/firmware/app/brewblox/test/BrewBloxTestBox.h
-rw-r--r-- 1 elco elco 3,6K jan 28 13:19 /home/elco/repos/firmware/app/brewblox/test/BrewBloxTestBox.h
```

The file exists though and 0.20.1 has no problems finding it.
It seems like the Intellisense fallback code for includes broke something. Let me know if there is another test I can do.

**Comment by elcojacobs** [comment]
With further testing, I don't think it is directly related to 0.21.0. Maybe it is a strange timing issue instead.

**Comment by Yilin-Yang** [comment]
I encountered what seemed like the same issue, also on Ubuntu 18.04, though I was using [coc.nvim](https://github.com/neoclide/coc.nvim) and neovim instead of VSCode.

The solution I found was to `sudo apt install libjsonrpccpp-dev`; after making that change, cquery worked as expected.

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
