### ISSUE TITLE
Commenting code inside peek dec/def with Monokai = blurred function name

### ISSUE THREAD

**Issue by KaeLL** [microsoft/vscode-cpptools#3091]
Since Peek doesn't work without the extension, I guess this belongs here, but Idk.

- VSCode Version: 1.30.2
- OS Version: Any

Steps to Reproduce:
1. Peek declaration or definition of a function with Monokai color theme;
2. Select code the includes the function name;
3. Ctrl + / to comment the line;
4. Voila.
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them): None
**Screenshots**
![Before commenting](https://user-images.githubusercontent.com/4423144/51717964-1edc9a80-202a-11e9-9ef1-e6ff0fb59246.png)
![After commenting](https://user-images.githubusercontent.com/4423144/51717979-2c922000-202a-11e9-9504-d7a95e44720a.png)

**Comment by sean-mcmanus** [comment]
Can you open a VS Code bug? Our extension doesn't implement the Monokai theming. It might be covered by bug https://github.com/Microsoft/vscode/issues/64013 .
