### ISSUE TITLE
Extension tries to auto-update despite being told not to

### ISSUE THREAD

**Issue by Anmol-Singh-Jaggi** [microsoft/vscode-cpptools#3093]
Type: General

- OS and Version: Windows 10 Enterprise 1709 16299.846 
- VS Code Version: 1.28.1
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.

Extension tries to update itself when VS Code is opened, despite extension auto-updates turned off in the preferences:
"extensions.autoCheckUpdates": false
"extensions.autoUpdate": false

**To Reproduce**
1. Disable auto-update extension in preferences.
2. Restart VS Code.
3. The extension still tries to update.

**Expected behavior**
Extension should not check for updates.

**Additional context**
Output log:

 Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'ClangFormat (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Visual Studio Windows Debugger'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: end of central directory record signature not found

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.

**Comment by bobbrow** [comment]
When you install the extension for the first time, we need to download additional OS-specific binaries in order to make the extension work.  If you install the "offline" VSIX package we upload to https://github.com/Microsoft/vscode-cpptools/releases, do you continue to have this problem?

You can try installing an older version (e.g. https://github.com/Microsoft/vscode-cpptools/releases/download/0.20.1/cpptools-win32.vsix) and see if VS Code is still trying to auto-update you to 0.21.0.

**Comment by Anmol-Singh-Jaggi** [comment]
I just removed the HTTP_PROXY environment variable, and it stopped bothering me.
But I have been using this extension for quite some time, this was not the first time install.
I have now updated both the extension as well as VSCode to the latest versions.
Thanks for the response though.
If you need any more clarifications, let me know.
