### ISSUE TITLE
Go to Symbol in File performance

### ISSUE THREAD

**Issue by alekseyt** [microsoft/vscode-cpptools#3094]
**Type: LanguageService**

**Describe the bug**
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763
C/C++ Extension Version: 0.21.0

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.21.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

**To Reproduce**

1. Open a set of cpp/h files
2. Wait for "database" icon disappear (files parsed)
3. Choose any open file and verify that symbols list is actually present: Go to Symbol in File

Actual result 1: symbols are in the list as expected

4. Open another cpp/h file
5. Before "database" icon disappears (still parsing), Go to Symbol in File, type nonexisting symbol, e.g. "assdgsadsa"
6. Wait for bluebar/database icon to disappear

Actual result 2: symbols list (in quick open menu) is empty (as intended)

7. Esc
8. Switch to another _open_ file
9. Go to Symbol in File

Actual result 3: parsing process starts again
Actual result 4: even though complete symbols list for that file is visible in Explorer's outline section (in sidebar)

I'm using tags parser, here's my options related to C++ extension:

```
    "C_Cpp.dimInactiveRegions": false,
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseEngine": "Tag Parser",
```

Maybe tags parser is part of the reason why it's slow, default intellisense engine doesn't work in my situation. I would like to still open this issue because in majority of cases it's faster to use vscode embedded search rather than "Go to Symbol in File".

I don't know what the expected result would be here, i guess it would be beneficial to prioritize parsing of currently open file or avoid reparsing of already parsed files, or fallback to symbols in Explorer's outline, whatever makes "Go to Symbol in File" faster than embedded search in file i guess.

My complete `settings.json`:

```json
{
    "telemetry.enableTelemetry": false,
    "update.channel": "none",
    "extensions.ignoreRecommendations": true,
    "workbench.startupEditor": "none",
    "workbench.statusBar.feedback.visible": false,
    "workbench.editor.enablePreview": false,
    "workbench.settings.editor": "json",
    "editor.minimap.enabled": false,
    "editor.insertSpaces": false,
    "editor.detectIndentation": true,
    "editor.renderIndentGuides": false,
    "editor.renderWhitespace": "none",
    "editor.folding": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "search.useIgnoreFiles": false,
    "git.confirmSync": false,
    "git.inputValidation": "off",
    "C_Cpp.dimInactiveRegions": false,
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseEngine": "Tag Parser",
    "debug.internalConsoleOptions": "neverOpen",
    "debug.toolBarLocation": "docked",
    "debug.openDebug": "openOnDebugBreak",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "todohighlight.keywords": [
        "TODO",
        "FIXME",
        "XXX",
    ],
    "workbench.colorTheme": "One Monokai",
}
```

**Comment by sean-mcmanus** [comment]
I'm not able to repro the problem.

What do you mean by "parsing process starts again"? How do you know parsing is occurring? Go to Symbol in File doesn't invoke any parsing. However, it can be blocked if parsing is occurring to ensure that the Outline view has updated symbols. Do you know what action is occurring to cause additional parsing? If parsing is actually occurring you should see a "tag parsing" message when [debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) is enabled.

**Comment by alekseyt** [comment]
I assume that parsing is reoccuring because i see bluebar running in both explorer's outline and "quick open menu" when this happens, also "database icon" appears in status bar with tooltip text "Parsing open files".

![image](https://user-images.githubusercontent.com/993454/51776506-2f604400-2102-11e9-82ff-30a05977287a.png)

I might have misinformed you about steps to reproduce, i think steps 7-8 should read

7. Esc
8. Close currently open file (Ctrl-W, this automatically switches editor to another open file)

I also noticed that explorer's outline might show symbols from previously open file so this part might also be irrelevant to the issue. I might have missed some steps too, sorry, maybe build running in background could help to manifest this issue or large files (~5000 lines or so).

It looks like symbols might not be always loaded for all open files and opening/closing files triggers symbols update in some situations maybe.

I was able to reproduce this on Linux with vscode 1.29.1 and cpptools 0.19.0 too. However on Linux it's of much smaller magnitude, not tens of seconds but 1-5 seconds for bluebar to finish running and display symbols (maybe smaller project).

Actually i don't think it's necessarily related to tags parser, on Linux i usually use default intellisense engine and i don't see difference in performance when i switch to tags parser.

Alternative steps to reproduce:

0. (Wait for initial parsing to finish)
1. Open a set of files (e.g. five)
2. Ctrl-W, Ctrl-W (close two last files)
3. Ctrl-Shift-T, Ctrl-Shift-T (reopen two last files)
4. Wait for bluebar and database icon to disappear
5. Ctrl-W, Ctrl-W (close two last files again)
6. (no pause/wait) Go to Symbol in File

Actual result: bluebar and database icon appear, symbols are not displayed until they disappear

Reproduces reliably here. I tried with cpptools 0.19.0 and 0.21.0.

This is what i see in "Output" with `"C_Cpp.loggingLevel": "Debug"` when i repeat steps 4-9 or alternative steps (didn't spot difference between two): 

<details>

```
textDocument/documentSymbol
textDocument/didOpen
textDocument/didClose
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/didClose
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/documentSymbol
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentSymbol
textDocument/didOpen
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/documentSymbol
textDocument/didOpen
textDocument/didClose
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/didClose
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/documentSymbol
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentSymbol
textDocument/didOpen
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/documentSymbol
textDocument/didOpen
textDocument/didClose
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/didClose
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/documentSymbol
```

</details>

I don't see "tag parsing" message here, only when i restart vscode. But bluebar and database icon appear.

I'll try to enable debug logging on Window too to see if there is a difference.

**Comment by alekseyt** [comment]
I've checked this on Windows and debug output is identical to output on Linux. Running build on all cores definitely increases parsing time or "parsing time" because i don't see tag parser messages in debug output. It just takes a long time to display symbols after i close some files in editor when CPU is busy.

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
