### ISSUE TITLE
Switch Header/Source performance

### ISSUE THREAD

**Issue by alekseyt** [microsoft/vscode-cpptools#3095]
**Type: LanguageService**

**Describe the bug**
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763
C/C++ Extension Version: 0.21.0

**To Reproduce**

1. Open cpp file
2. Switch Header/Source

Actual result 1: nothing happens (seemingly)
Actual result 2: header file opens after 30-60 seconds when i've already opened that file using "quick open" menu and then switched to yet another file

Additional info: sometimes it takes a long time to switch even if header is already open in another tab. I suspect project parsing may be somehow involved, "database" icon appears after a (long) attempt to switch to header. Rather big codebase.

Additional info: also sometimes it's switching to incorrect file, e.g. `a.cpp` is open, "Switch Source/Header", it switches to first tab open in editor or to previously open header (not `a.h`). If i switch back to `a.cpp` and do "Switch Source/Header" again then it switches correctly.

C++ extension settings:

```
    "C_Cpp.dimInactiveRegions": false,
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseEngine": "Tag Parser",
```

**Comment by sean-mcmanus** [comment]
It sounds like something is blocking the main thread (i.e. I assume Go to Definition would also be delayed). The switch header/source operation itself isn't expected to take a long time. I'm not able to repro the bug though (with the large chromium repo). Can you attach a debugger to the Microsoft.VSCode.CPP.Extension.exe process and get the interesting call stacks that appear to be blocked doing some work after invoking the switch header/source? Or the [logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) might show some info.

**Comment by alekseyt** [comment]
Regarding 
> also  sometimes it's switching to incorrect file

It's my bad, i messed up keybindings and hotkey for Switch Header/Source was bound to other actions too.

**Comment by alekseyt** [comment]
Regarding performance issue: i think i found conditions under which issue reliably reproduces. Sorry for the strange steps to reproduce:

1. Reboot Windows

While Windows is getting everything up and disk i/o is at 100%

2. Launch vscode
3. Start a long search in files (e.g. "abc")

While search is still running (disk i/o is at 100%)

4. Pick and open any cpp file in search
5. Switch Header/Source
6. (immediately) Ctrl-W (close picked file)
7. (optionally) Repeat steps 4-6

Actual result 1: picked cpp file(s) is closed

8. Wait

Actual result 2: corresponding h files start to open up in editor

It was able to open 5 or so headers that way, they just started appearing in editor one by one after some time.

Step 1 can probably be skipped if just searching in files does 100% disk i/o, but following search in files might not do the same disk i/o again. I don't know how to simulate high disk i/o on Windows with embedded tools.

I do understand that apparently some task/action is submitted to some sort of a queue for processing on each Switch Header/Source, i do not consider this behavior as a bug. But i do think there might be some performance issue because i was able to open and close several other files before actions/tasks were actually processed.

I'm guessing that Switch Header/Source might be in some way I/O-bound, maybe it needs to access filesystem or something. But, again, opening/closing another files is accessing filesystem too, so i assume filesystem itself isn't _blocked_ at that moment, it just takes a long time to find corresponding header.

My filesystem is NTFS, HDD is SATA3 7200 RPM something something. It's not SSD, but it's not super slow (neither super fast), it's a decent, relatively new HDD.

Debug output with `"C_Cpp.loggingLevel": "Debug"` didn't show anything that caught my eye, stuff like this:

```
cpptools/textEditorSelectionChange
textDocument/codeAction
$/cancelRequest
cpptools/didSwitchHeaderSource
textDocument/didClose
$/cancelRequest
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/didOpen
textDocument/codeAction
$/cancelRequest
cpptools/textEditorSelectionChange
textDocument/codeAction
$/cancelRequest
cpptools/textEditorSelectionChange
textDocument/codeAction
$/cancelRequest
cpptools/didSwitchHeaderSource
textDocument/didClose
```

**Comment by Colengms** [comment]
Hi @alekseyt .  There hasn't been activity on this issue for quite a while.  Could you confirm whether or not this issue is still repro'ing for you with a recent version of the extension?  Thanks.

**Comment by alekseyt** [comment]
Hi. Sorry, i can't confirm this because i'm not using that setup (on Windows) anymore, i never saw this on Linux + i'm stuck on cpptools 0.19 because of another issue that is still not resolved, so i can't help with it any further. If anyone want to close this issue - please feel free to do so, it is pretty much not reproducible for me anyway.
