### ISSUE TITLE
support per build type/directory settings

### ISSUE THREAD

**Issue by hferreiro** [microsoft/vscode-cpptools#3096]
When building Chromium, there can be multiple build directories for different platforms in the same machine, for example chromeos, linux and android on a linux box. The extension lacks a way to select a different compile_commands.json per build type. This is needed because the different platforms may compile different source files.

**Comment by hferreiro** [comment]
I just noticed that there can be more than one configuration and those can be selected at runtime. Is there a way to setup the default configuration in the .code-workspace file so that I can just load a different workspace file sharing the same source dirs?

**Comment by sean-mcmanus** [comment]
Yeah, the current config is saved per-workspace, so you can just create 2 workspaces and set them to use different configs and then switch workspaces...is that what you're asking? The workspace default is saved into the VS Code's special storage area though, so it's not something that can be checked into source control.
