### ISSUE TITLE
C++ parsing erroring on opencv

### ISSUE THREAD

**Issue by python152** [microsoft/vscode-cpptools#3099]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS Mojave
- VS Code Version: Nov 2018 release
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

opencv 4.0.1 installed by homebrew, initially all three hpp files shows squiggles, after adding the path, both highgui.hpp and imgproc.hpp are gone, but dnn.hpp is still there, as it shows. The output is `opencv2/dnn.hpp file not found`. However, the file is there, and I can `go to definition` to load it. Is there something else I missed?

![image](https://user-images.githubusercontent.com/17506882/51781783-99b9ba00-20eb-11e9-92e0-23d1f3e55dac.png)

**Comment by sean-mcmanus** [comment]
I suspect a dependency of dnn.hpp is not being found. What does the error say?

**Comment by python152** [comment]
file not found is the only error.
![image](https://user-images.githubusercontent.com/17506882/51781858-d9cd6c80-20ec-11e9-827f-4866e6ba56d4.png)

**Comment by sean-mcmanus** [comment]
That error message is not from out extension. It might be from the C/C++ Clang Command Adapter extension. We might add a [cpp] provider to our error message to help avoid this confusion, but that other extension should add some [vscode-clang] source ID as well (not sure if they want to).

**Comment by python152** [comment]
You are right!  I do have that extension enabled, and the problem went away when clang adapter disabled, even though I have no idea why clang extension does what it does, the ball is on their court. thanks.
