### ISSUE TITLE
Repetitive problem message when pointing to problem line

### ISSUE THREAD

**Issue by Aukstkalnis** [microsoft/vscode-cpptools#31]
VSCode Version: 1.0.0
OS Version: windows 7

Steps to Reproduce:
1. In one header create warning message
2. Include this header into multiple files
3. Compile and go, to problem Mach in this header
4. Problem message shows a list repetitive messages

It is strange to see list of problem messages that are the same.

**Comment by sridmad** [comment]
Duplicate issue #41.
