### ISSUE TITLE
change "." to "->" automatically

### ISSUE THREAD

**Issue by nxyd** [microsoft/vscode-cpptools#3105]
When i type a variable that is a pointer, then i type ".", and is it possible to change to "->" automatically?

**Comment by starkblitz** [comment]
I would definitely want this feature!

**Comment by sean-mcmanus** [comment]
Duplicate of https://github.com/Microsoft/vscode-cpptools/issues/862 . Please upvote that issue.

**Comment by sean-mcmanus** [comment]
Fixed with 0.29.0.
