### ISSUE TITLE
"go to definition" function doesn't work on vs code for c/c++

### ISSUE THREAD

**Issue by apeforest** [microsoft/vscode-cpptools#3106]
**Type: LanguageService**

"go to definition" function doesn't work (properly) on vs code for c/c++

**Describe the bug**
- OS and Version: MacOS 10.13.6
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
When right click GOTO defintion in any function in my C++ project, it would stop working in a few seconds (literally). It first worked. And then I repeat the same process again, it says "No definition found". I have rolledback to 0.20.0 to see if this is some bug introduced in 0.21.0. So far 0.20.0 works well.
**To Reproduce**

1. Go to any large C++ project
2. Click on function and Goto definition

**Expected behavior**

**Comment by sean-mcmanus** [comment]
If you check the C/C++ Output window is there are disconnect message from a crash?

Does this repro for certain kinds of definitions?

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
