### ISSUE TITLE
I still can't seem to run the debugger on my Mac

### ISSUE THREAD

**Issue by carlosd097** [microsoft/vscode-cpptools#311]
![screen shot 2016-10-26 at 7 51 25 pm](https://cloud.githubusercontent.com/assets/23089420/19751352/bcfff55a-9bb5-11e6-81a6-79297c784e73.png)

I've tried multiple ways suggested by peers.

![screen shot 2016-10-26 at 7 54 51 pm](https://cloud.githubusercontent.com/assets/23089420/19751906/26227756-9bb6-11e6-811a-6866f4e65a43.png)

**Comment by ecanuto** [comment]
"Program" must be your final executable program and I suggest you try something without space, try "hot-plate".

Also, you must remember to compile your program with "-g" flag to include debug symbols, for final versions you can suppress "-g" to make smaller executable.

So, to compile with debug symbols, try something like:

```
clang++ -g -o hot-plate hotPlate.cpp
```

Here it works just fine.

**Comment by jacdavis** [comment]
ecanuto is correct, the program must point to the target of compilation, not a source file. 

We recently posted to the VC blog about how to compile on the various platforms. This might help:
https://blogs.msdn.microsoft.com/vcblog/2016/10/24/building-your-c-application-with-visual-studio-code/

**Comment by pieandcakes** [comment]
@carlosd097 Have you been able to get the debugging working? Do you need additional help?

**Comment by pieandcakes** [comment]
If this is still an issue, please provide updated information and reopen.
