### ISSUE TITLE
symbol behind “goto“ can't go to definition correctly.

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3111]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

codes as blow:

void strtoull(bool isTure, int x)
{
    if (x > 36)
        goto destination;    //location1, "go to definition" for destination will go to location1. 
    if (isTure)
    {
        x++;
        goto destination;               //location2,  "go to definition" for destination will go to location1. 
    }
destination:
    x--;
}

but it's right if you place destination region to some place before "goto" like this:

void strtoull(bool isTure, int x)
{
    unsigned long long ret = 0;
destination:
    x--;
    if (x > 36)
        goto destination;
    if (isTure)
    {
        x++;
        goto destination;
    }
}

**Comment by sean-mcmanus** [comment]
I repro the problem. Visual Studio doesn't have this bug, so we must be doing something incorrectly.

**Comment by Lennon925** [comment]
> I repro the problem. Visual Studio doesn't have this bug, so we must be doing something incorrectly.

Will this issue be fixed on next cpptools version ?

**Comment by sean-mcmanus** [comment]
It is not currently planned to be fixed in the next version. We don't have an ETA on a fix yet.

**Comment by Lennon925** [comment]
> It is not currently planned to be fixed in the next version. We don't have an ETA on a fix yet.

Hi, this issue will be planned to be fixed in April？

**Comment by sean-mcmanus** [comment]
There are a couple other Go to Def bugs you reported that I was hoping to investigate next week, so I could add this to that list. But it's possible other issues might get higher priority, such as dealing with the complaints around the ipch folder.

**Comment by Lennon925** [comment]
> There are a couple other Go to Def bugs you reported that I was hoping to investigate next week, so I could add this to that list. But it's possible other issues might get higher priority, such as dealing with the complaints around the ipch folder.

OK，thanks so much.

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders (available by setting "C_Cpp.updateChannel" to "Insiders").

**Comment by Lennon925** [comment]
> Fixed with 0.24.0-insiders (available by setting "C_Cpp.updateChannel" to "Insiders").

I tested on version 0.24 and it's OK.
