### ISSUE TITLE
"go to definition" error when there is a macro reference before function name

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3115]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**#define __init __section**
void __init test(int nid)
{
	int mm = 0 ;
	mm ++;          //it's ok to go to definition.
}

**#define __init __section()**
void __init test(int nid)
{
	int mm = 0 ;
	mm ++;          //variable mm can't go to definition in both .c file and .cpp file.
}

**#define __init __section(x)**  
void __init test(int nid)
{
	int mm = 0 ;
	mm ++;          //variable mm can't go to definition in .c file but can in .cpp file.
}

**Comment by sean-mcmanus** [comment]
How is "void __section() test(int nid)" valid code? What compiler/flags are you using? I don't see this working with .cpp files either. I get an error squiggle.

**Comment by Lennon925** [comment]
> How is "void __section() test(int nid)" valid code? What compiler/flags are you using? I don't see this working with .cpp files either. I get an error squiggle.

it's not valid. But I think local variables in functions should go to definition correctly.

**Comment by Lennon925** [comment]
my sample code is from Linux source code. I removed the header including part and used my macro to make logic to understand easily. VsCode can't parse the macro with brackets and parameters for some reasons and this results in errors which local variables can't go to defintion.

**Comment by sean-mcmanus** [comment]
I reported a bug (feature request) at https://developercommunity.visualstudio.com/content/problem/441352/cc-intellisense-fails-to-work-in-a-function-body-a.html , so upvoting that issue would help get a fix.

**Comment by sean-mcmanus** [comment]
This issue is unlikely to get fixed unless the linked VS issue gets more votes. There are also implementation reasons why it may not be possible to fix.
