### ISSUE TITLE
const reference return type is marked as an error by intellisense

### ISSUE THREAD

**Issue by fabiopolimeni** [microsoft/vscode-cpptools#3119]
**Type: LanguageService**
C

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.31
- C/C++ Extension Version: 0.21
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

The character '&' is highlighted in red if part of a declaration/definition of the return type of a function.

**To Reproduce**
```
typedef struct {
    size_t      count;
    size_t      capacity;
    ubyte_t*    data;
} ng_buffer_t;

const ng_buffer_t& ng_buffer_get_buffer();
```

Both configurations produce the same error.

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/tests/greatest"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17763.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        },{
            "name": "Clang",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/tests/greatest"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17763.0",
            "compilerPath": "clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }

    ],
    "version": 4
}
```

**Expected behaviour**
The given code is valid and it shouldn't produce any error

**Screenshots**
![Screenshot](https://i.ibb.co/rGzKXG6/c11-error.png)

**Comment by sean-mcmanus** [comment]
I'm not reproing a problem. Can you copy/paste the text of the error?

**Comment by fabiopolimeni** [comment]
Unfortunately, the only text I have is the one you can see in the screenshot 

> expected an identifier

If you can't repro on your side I will try to disable some other extensions, they may are conflicting with the parsing.

**Comment by sean-mcmanus** [comment]
That error is from our extension. It's caused by your file (I assume ".C") from being interpreted as a C instead of a C++ file (C doesn't allow references with &). Can you workaround the issue via adding `"*.C": "cpp"` to your files.associations setting? We have an issue tracking improving this scenario at https://github.com/Microsoft/vscode-cpptools/issues/2558 .

**Comment by fabiopolimeni** [comment]
Great @sean-mcmanus, the issue is fixed as far as I need.
