### ISSUE TITLE
[C++] single quotes in numeric literals are parsed incorrectly

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-cpptools#312]
_From @jplatte on October 27, 2016 12:42_
- VSCode Version: 1.6.1
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

Open a `.cpp` file with a literal with a single quote in it:

``` c++
constexpr int a = 100'000;

int main() {}
```

Expected result: The main function should be highlighted as normal.
Actual result: Everything after the single quote is formatted as if it was in a string literal.

See [integer literal](http://en.cppreference.com/w/cpp/language/integer_literal) (and [floating point literal](http://en.cppreference.com/w/cpp/language/floating_literal)) on cppreference for the details about numeric literals in C++.

_Copied from original issue: Microsoft/vscode#14595_

**Comment by bobbrow** [comment]
We fixed this in the atom/language-c grammar and are waiting for VS Code to pick it up.
see: https://github.com/atom/language-c/issues/154
also: #460
