### ISSUE TITLE
Support tracepoint actions (Linux)

### ISSUE THREAD

**Issue by aparks5** [microsoft/vscode-cpptools#3120]
it's pretty simple, vscode 1.30.2

launch gdb, try:

-exec trace source.cxx:line
-exec actions 

(no response)

works fine when i launch gdb from the terminal

**Comment by pieandcakes** [comment]
We don't currently support tracepoints.

@aparks5 what are you expecting to happen? I tried your scenarion and I get a response of *not available* back from gdb.

**Comment by aparks5** [comment]
I was expecting to be able to do anything in the Debug Console that I could do in gdb. Even if it gets written out to the file system and is not reflected in the Debug window.

**Comment by WardenGnaw** [comment]
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/2591
