### ISSUE TITLE
Code formatter: Curly braces not in same column

### ISSUE THREAD

**Issue by EmbersArc** [microsoft/vscode-cpptools#3125]
**Type: LanguageService**

- OS and Version: Ubuntu 16.04, Linux x64 4.4.0-141-generic
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.21.0
- Issue persists after disabling all other extensions

----

- A clear and concise description of what the bug is.

The default c/c++ formatter turns an initializer list from this

```
std::vector<...> vec =
{
    {1, 30},
    {21, 20}
};
```

into this

```
std::vector<...> vec =
{
    {1, 30},
    {21, 20}};
```

Putting the last curly brace not below the first is inconvenient:

- It doesn't look good and is harder to read.
- It is inconsistent with the behavior in functions, loops, etc., where matching braces are placed in the same column.
- Some codechecks like Vera insist on the braces being in the same column, effectively making the otherwise great formatter unusable.

----

**To Reproduce**
1. Create a .cpp file with an initializer list as in the example above.
2. Format the file with the default VSCode C++ formatter.

**Expected behavior**
The last closing brace is in the same column as the corresponding opening brace.

**Comment by sean-mcmanus** [comment]
It can be configured via using the Cpp11BracedListStyle: false (see https://clang.llvm.org/docs/ClangFormatStyleOptions.html ). Example C_Cpp.clang_format_style setting is
`{ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, Cpp11BracedListStyle: false }`. Does that work for you? I'm not sure if we want to set that to false by default though. It seems like even with that setting set to the default of "true" your example should get better results, but that seems like a bug that the clang-format team would need to fix.

**Comment by EmbersArc** [comment]
Ah, I see. Now the brace is in the right place, but there are additional spaces:
```
std::vector<...> vec =
{
    { 1, 30 },
    { 21, 20 }
};
```
Not really better either. I wasn't aware that clang-format is always used for this. Might report there.
Thanks for your help.
