### ISSUE TITLE
[question] Option to disable completion committing for methods after (

### ISSUE THREAD

**Issue by kroton** [microsoft/vscode-cpptools#3127]
Is there any option to disable completion committing for methods after ( #1184 ?

It seems to me that the feature related to #1184 works well for method calls, but is not fit for variable definitions or method calls using macros.
For example, I have typed `std::vector<string> grid`, then I typed `(`, and finally I got `std::vector<string> __libcpp_thread_get_current_id()`.
Another case, I have typed
```cpp:
#define pb push_back
std::vector<int> v;
v.pb
``` 
then I typed `(`, and finally I got `v.pop_back()`.

I prefer previous behavior about completion committing after (, so I want an option to disable the feature.
Thanks.

**Comment by sean-mcmanus** [comment]
The main scenario this break is when typing function declaration/definitions. I think we'll need to remove the commit characters.

There is not currently an option to disable it. One problem is that VS Code auto-selects completions (unlike VS), so if any commit characters are used they will be committed unintentionally whenever the list pops up. The other problem is that we shouldn't be offering suggestions when the current token is the identifier in a declaration or definition...we have some checks when a built-in type is on the left (e.g. int i( won't auto-complete) but not the more general case. Until those problems are fixed, I don't think we can safely add commit characters.

**Comment by bobbrow** [comment]
@kroton have you tried `"editor.acceptSuggestionOnCommitCharacter": false`?  Does that solve your problem?  It seems to work for me.

**Comment by sean-mcmanus** [comment]
@bobbrow Yeah, that is a workaround, but I still think we should remove it. And to not affect other languages
```
    "[cpp]": {
        "editor.acceptSuggestionOnCommitCharacter": false
    },
    "[c]": {
        "editor.acceptSuggestionOnCommitCharacter": false
    }
```

**Comment by kroton** [comment]
@sean-mcmanus @bobbrow 
Thank you for the advice both. The workaround works for me too.

**Comment by sean-mcmanus** [comment]
Our next Insider release will remove the ( commitCharacter, and replace it with the "(|)" snippet, which is a "better" experience anyway. We're keeping the < commitCharacter for struct/classes, since that scenario doesn't appear to cause a conflict.

UPDATE: (|) snippets is blocked by signature help not working: https://github.com/Microsoft/vscode/issues/67901 .

UPDATE2: We fixed the (|) snippets, but 0.22.0-insiders will just remove the ( commitCharacter, because we want to add a setting for what parentheses are completed for methods.

**Comment by sean-mcmanus** [comment]
We've removed the commit characters with 0.22.0-insiders. You can get it via setting the C_Cpp.updateChannel setting to "Insiders", or downloading it manually from https://github.com/Microsoft/vscode-cpptools/releases .

**Comment by kroton** [comment]
@sean-mcmanus 
I've tried 0.22.0-insiders, and I'm very satisfied with the behavior. Thanks a lot.
