### ISSUE TITLE
arguments suggestions underline wrong

### ISSUE THREAD

**Issue by tkj666** [microsoft/vscode-cpptools#3129]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 x64
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

![image](https://user-images.githubusercontent.com/28040169/52175061-e3379280-27d8-11e9-962d-ee9a5b0cca07.png)

As you can see, the underline should be on the first argument but now on the last and doesn't cover it completely.

**Comment by sean-mcmanus** [comment]
This has been fixed in our Insider build with https://github.com/Microsoft/vscode-cpptools/issues/2952 ...not sure when we'll release it yet.

**Comment by sean-mcmanus** [comment]
The signature help bug has been fixed with 0.22.0-insiders. You can get it via setting the C_Cpp.updateChannel setting to "Insiders", or downloading it manually from https://github.com/Microsoft/vscode-cpptools/releases .
