### ISSUE TITLE
step over work unexpectedly.

### ISSUE THREAD

**Issue by wa8n** [microsoft/vscode-cpptools#3130]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows_NT ia32 10.0.17134
- VS Code Version: 1.30.2
- C/C++ Extension Version:0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "preLaunchTask": "build",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "logging": { "engineLogging": true, "trace": true, "traceResponse": true },
            "miDebuggerPath": "D:/Program Files/TDM-GCC-64/bin/gdb64.exe", 
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }]
}
```
2. tasks.json
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            "windows": {
                "command": "g++",
                "args": [
                    "-ggdb",
                    "\"${file}\"",
                    "--std=c++11",
                    "-o",
                    "\"${fileDirname}\\${fileBasenameNoExtension}.exe\""
                ]
            }
        }
    ]
}
```
3. gcc version
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=D:/Program\ Files/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)
```
4. when I click "step over" button into a for loop or step into a function then click "step over" button,  the cursor of current line dispeared and the program stucked.

5. 
![i7cr9-izlw4](https://user-images.githubusercontent.com/5162138/52254501-084b1300-2949-11e9-8950-44262760dac1.gif)
![u1yr1-1cf93](https://user-images.githubusercontent.com/5162138/52254506-0aad6d00-2949-11e9-8105-241993b25d8f.gif)

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by pieandcakes** [comment]
Which tools package did you install to get your gcc/gdb and what version of gdb are you using? 

Also, attaching an engineLog to your issue will help. I can't repro this with my 8.1 gdb on MinGW.

**Comment by wa8n** [comment]
I used TDM-GCC-64, and the version of gdb is  7.9.1.
[debugconsole.txt](https://github.com/Microsoft/vscode-cpptools/files/2849642/debugconsole.txt)
my test code:
```
#include <iostream>

using namespace std;

int main(){

    int a = 0;
    for(int i=0;i<5;i++){
        cout<<i<<endl;
    }
    return 0;
}
```

**Comment by pieandcakes** [comment]
The logging setting i'm looking for is: `"logging": { "engineLogging": true }`

I think you provided a trace log.

**Comment by pieandcakes** [comment]
According to the log you are stopped after completing a Step request. Which version of the TDM tool set are you using?

**Comment by pieandcakes** [comment]
Ok. I tried it with 5.9.1_3 of TDM. The step over is stopping, but on this line:
```
1: (12687) ->*stopped,reason="end-stepping-range",frame={addr="0x000000000046c8a0",func="std::ostream::operator<<(std::ostream& (*)(std::ostream&))",args=[]},thread-id="1",stopped-threads="all"
```

we then ask for a list of frames:
```
1: (51170) <-1062-stack-list-frames 0 1000
1: (51170) ->&"\n"
1: (51171) ->^done
1: (51172) ->(gdb)
1: (51180) ->1062^done,stack=[frame={level="0",addr="0x000000000046c8a0",func="std::ostream::operator<<(std::ostream& (*)(std::ostream&))"}]
```

But the only frame available is the `operator<<` frame which is not in your code. There is no frame available that is within your code which is why there is no execution pointer. If you set a line on `cout<<` and continue, you will see that breakpoint get hit and it will be within your code again.

This seems to be a problem with your TDM tool set and not a bug within the extension.
