### ISSUE TITLE
The debugger sometimes show no response when I debug a c program with getchar() in the head of 'while' loop.

### ISSUE THREAD

**Issue by bigface008** [microsoft/vscode-cpptools#3131]
Type: Debugger
The debugger sometimes show no response when I debug a c program(listed below) with getchar() in the head of 'while' loop. (Please forgive my poor English......

**Describe the bug**
- OS and Version: wsl(ubuntu16.04) on windows10(17134.523):
- VS Code: 1.30.2
- C/C++ Extension Version: 0.21.0

**To Reproduce**
1. Set break points at line 7 and line 11. Start the debugger.
2. The debugger stops at the entry. When you press the 'step over' button, it works well and goes to line 7.
3. Press the 'step over' button again, it goes to line 8, press again, and the debugger shows something weird.
- The variable list in the debugger panel diappear.
- Some buttons for debugging on top of the interface get grey. (Please forgive my poor English.) You will get no response if you clink them.
![default](https://user-images.githubusercontent.com/27338884/52208942-4f8bc200-28bd-11e9-96c8-ff5867505236.png)
- I wait 10s(longer) yet nothing happens.

I tried 10 times and the debugger works properly only once.

I compiler the file(simple.c) with the command `gcc -g simple.c`. The debugger works properly when I don't use the getchar() function in the 'whlie' loop. Besides, I've disabled other plugins and the problem presists.
```c
#include <stdio.h>

int main(int argc, char const *argv[])
{
    int c;
    int temp = 0;
    temp++;
    while ((c = getchar()) != EOF)
    {
        temp++;
        printf("c\n");
    }
    return 0;
}
```
```json
{ 
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Bash on Windows Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/mnt/e/workspace/c-family/learn/a.out(You may need to modify this option)",
            "args": [" < input.log(just for input)"],
            "stopAtEntry": true,
            "miDebuggerArgs": "",
            "cwd": "/mnt/e/workspace/c-family/learn/(You may need to modify this option)",
            "environment": [],
            "externalConsole": false,
            "sourceFileMap": {
                "/mnt/e/": "E:\\(You may need to modify this option)"
            },
            "pipeTransport": {
                "debuggerPath": "/usr/bin/gdb",
                "pipeProgram": "${env:windir}\\system32\\bash.exe",
                "pipeArgs": [
                    "-c"
                ],
                "pipeCwd": ""
            },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": { "engineLogging": true, "trace": true, "traceResponse": true }
        },
    ]
}
```
The content of input file is listed below. (I don't think it is meaningful......)
```
kausdhclkandslkgvbqiwruhgpaisdgbasdhpoahfvadsivhasdfga
alksdbvasugviaugsfvkabfs;vbalkfbvafv
alksubvaiourhgpqowarhgb
```
Pictures of log are listed below.
When the debugger show no response, the logs end with:
![default](https://user-images.githubusercontent.com/27338884/52209803-025d1f80-28c0-11e9-87ed-12924f753826.png)

**Comment by escaner** [comment]
In my case, this (which looks weird, BTW unless you have a file named like that with parenthesis and all):
            "args": [" < input.log(just for input)"],
is being passed as an argument to the program, it is not interpreted by any shell and therefore stdin is not connected to any external file. Check the values for argc (2) and argv[1] (" < input.log(just for input)").

When you do a step over getchar(), it reads stdin and blocks because there is nothing yet to read. Write something in the terminal window and press enter: the debugger will advance to the next line inside the loop.

**Comment by bigface008** [comment]
> In my case, this (which looks weird, BTW unless you have a file named like that with parenthesis and all):
> "args": [" < input.log(just for input)"],
> is being passed as an argument to the program, it is not interpreted by any shell and therefore stdin is not connected to any external file. Check the values for argc (2) and argv[1] (" < input.log(just for input)").
> 
> When you do a step over getchar(), it reads stdin and blocks because there is nothing yet to read. Write something in the terminal window and press enter: the debugger will advance to the next line inside the loop.

~~So if I want to connect stdin to the external file 'input.log', what value should the "args" option be? Is it like~~
```json
"args":["<","input.log"]
```
~~? (Since I have something wrong with my debugger of vscode-cpptools now, I can't test it myself.)~~

It works in the right way. Thank you!
