### ISSUE TITLE
Debugger Spam

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vscode-cpptools#3132]
Everytime I start debugger integrated terminal automatically opens up with these messages:
```
& 'c:\Users\Alex\.vscode\extensions\ms-vscode.cpptools-0.21.0\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-zmopjqyq.3c4' '--stdout=Microsoft-MIEngine-Out-bpc4b00u.x2z' '--stderr=Microsoft-MIEngine-Error-gcjterlb.5js' '--pid=Microsoft-MIEngine-Pid-34nqayos.zr2' '--dbgExe=C:/cygwin64/bin/gdb.exe' '--interpreter=mi'
```
How to suppress them? It's becoming very annoying

**Comment by Astrantia** [comment]
@WardenGnaw

**Comment by Astrantia** [comment]
@sean-mcmanus is there a configuration that I didn't see? I set all logs to false.

**Comment by sean-mcmanus** [comment]
I don't know (I don't use the debugger integrated terminal). @pieandcakes Do you know?

**Comment by pieandcakes** [comment]
@Astrantia that is the way VS Code's Run In terminal works. We send a command to VS Code to run in the terminal and that is what you are seeing.

**Comment by GloomySoul** [comment]
> I don't know (I don't use the debugger integrated terminal). @pieandcakes Do you know?

Whats the alternative to using the debugger integrated terminal?
