### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Udopia** [microsoft/vscode-cpptools#3133]
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/2832111/ms-vscode.cpptools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.21.0`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/markus/ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by nbrachet** [comment]
`cpptools` is making Code unusable:

- Extension Name: cpptools
- Extension Version: 0.21.0
- OS Version: Darwin 18.2.0
- VSCode Version: 1.31.0


[CPU-20190207T230320.465Z.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/2843002/CPU-20190207T230320.465Z.cpuprofile.txt)

**Comment by nbrachet** [comment]
Additional comment: it looks like `cpptools` isn't honoring `files.exclude` (or I don't understand `files.exclude`.)
`dtruss` shows `cpptools` scanning files that should have been filtered out:
```
access("/Users/nick/Projects/ForgeCEP/bazel-ForgeCEP/external/mysql_connector_cpp_1/var/tmp/_bazel_nick/11ce90006b6ab352ac4280416cf43075/external/mysql_connector_cpp_1/Users/nick/.npm/_cacache/content-v2/sha512/dd/80\0", 0x4, 0x0)		 = 0 0
```
when `**/bazel-*` is in `files.exclude`.

**Comment by sean-mcmanus** [comment]
Are you able to tell what sort of access is occurring and when the access occurs? The files.exclude problems may be https://github.com/Microsoft/vscode-cpptools/issues/3123 , if it is just checking for a list of files in directories, but if it's actually opening files (possibly parsing it), then it's possible there is a bug somewhere, but I'm not able to repro it with a simple "**/bazel-*" entry in files.exclude with a "bazel-forge" directory. I hit a case when #include completion is invoked (https://github.com/Microsoft/vscode-cpptools/issues/3195), but in that case it only touches files in the exluded folder one level at a time as "/" is used, so I don't think you're hitting that.

We could investigate further ourselves via proc mon later on too.

**Comment by nbrachet** [comment]
Here's what looks like a typical sequence for a file:
```
access("/Users/nick/Projects/ForgeCEP//bazel-ForgeCEP/external/mysql_connector_cpp_1/var/tmp/_bazel_nick/11ce90006b6ab352ac4280416cf43075/external/mysql_connector_cpp_1/System/Library/CoreServices/SystemVersion.bundle/fi.lproj\0", 0x4, 0x0)		 = 0 0
open_nocancel("/Users/nick/Projects/ForgeCEP//bazel-ForgeCEP/external/mysql_connector_cpp_1/var/tmp/_bazel_nick/11ce90006b6ab352ac4280416cf43075/external/mysql_connector_cpp_1/System/Library/CoreServices/SystemVersion.bundle/fi.lproj\0", 0x1100004, 0x1)		 = 12 0
getattrlistbulk(0xC, 0x70000E87AEF8, 0x7FC4D9196800)		 = 1 0
getattrlistbulk(0xC, 0x70000E87AEF8, 0x7FC4D9196800)		 = 0 0
close_nocancel(0xC)		 = 0 0
```

So yes it is opening the files.

It is worth noting that bazel (we use [bazel](https://bazel.build/) as our build system) creates many symlinks. Could it be that the `files.exclude` list is checked against the symlink and not matching whereas the realpath would match? Or something like that?

```
$ ls -dl /Users/nick/Projects/ForgeCEP/bazel-ForgeCEP
lrwxr-xr-x  1 nick  staff    79B Feb 20 16:15 /Users/nick/Projects/ForgeCEP/bazel-ForgeCEP@ -> /private/var/tmp/_bazel_nick/11ce90006b6ab352ac4280416cf43075/execroot/__main__
$ ls -dl /Users/nick/Projects/ForgeCEP/bazel-ForgeCEP/external/mysql_connector_cpp_1/System
lrwxr-xr-x  1 nick  wheel    99B Feb 20 16:15 /Users/nick/Projects/ForgeCEP/bazel-ForgeCEP/external/mysql_connector_cpp_1/System@ -> /private/var/tmp/_bazel_nick/11ce90006b6ab352ac4280416cf43075/external/mysql_connector_cpp_1/System
```

I did try to be very broad in my `files.exclude` to account for that though:
```
  "files.exclude": {
    "**/_bazel_nick": true,
    "**/bazel-*": true
  },
```

**Comment by sean-mcmanus** [comment]
Files.exclude is supposed to apply to the symbolic link name and not the target of the link (both for VS Code and our extension), so the "**/bazel-*" should work.

No where in our code do we open/parse a file of type ".lproj" unless you have added it in your files.associations as a C/C++ file or you have #included a ".lproj" file, which seems unlikely. It appears that the "open_nocancel" is just used to check the file attributes to determine if it's a file or directory, etc. As in, it appears to be https://github.com/Microsoft/vscode-cpptools/issues/3123 , which does cause high CPU usage when there are lots of folders under the excluded folder.

We use the "ntfw" Linux system call to get the list of folders/files and then later apply files.exclude before we actually process the files, i.e. we should be doing the files.exclude check earlier -- this code has existed for the past 3 years but the effect got worse when we added the recursive includes feature a few months ago -- removing the "**" from your includePaths may fix the more severe CPU problems.

**Comment by nbrachet** [comment]
You are correct: I don't #include a ".lproj" file.
It does appear my issue is indeed #3123.

I'll try removing the "**" from my includePaths...

**Comment by bobbrow** [comment]
The original issue looks like it would have been fixed by our webpack work last year.  The second issue is tracked by #3123.
