### ISSUE TITLE
AutoComplete set to Disabled doesn't work

### ISSUE THREAD

**Issue by Nazeehe** [microsoft/vscode-cpptools#3134]
Hey all,

Running VS Code:

Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

Extension: Version 0.21.0 January 23, 2019

When I upgraded to this version a few days ago, I lost my ability to have autocomplete be the default VSCode word based one. I went to the extension Settings and flipped the AutoComplete setting to Disabled, reloaded. When I try to invoke autocomplete now, it provides "no suggestions". 

To be 100% sure that it's not some other settings I have or extension, I installed a fresh copy of VSCode on another machine and only installed the C++ extension. Same thing. 

What am I missing? I had to turn off the extension as I depend on word based AutoComplete (the code base I am working on has never given me a successful intellisense experience so I gave up on it). 

Thanks!

**Comment by sean-mcmanus** [comment]
Our extension does this by default:
```
      "[cpp]": {
        "editor.wordBasedSuggestions": false
      },
      "[c]": {
        "editor.wordBasedSuggestions": false
      }
```

You can override those settings as a user setting, either globally or per-language. Is that sufficient? In order to change that default based on the auto-complete setting we would need to re-write the package.json.

**Comment by Nazeehe** [comment]
So here's what I put in my user settings:

{
    "C_Cpp.autocomplete": "Disabled",
    "editor.wordBasedSuggestions": true
}

that's it. 

Assuming that's enough, it still doesn't work. I can't get any word based suggestions to show up.

**Comment by Nazeehe** [comment]
Ok! Figured it out. I had to copy both and set them to true. 

Thanks all! Closing issue.

**Comment by sean-mcmanus** [comment]
Yeah, it turns out the settings need to be overwritten for the c/cpp languages, because the per-language settings take precendence.

**Comment by magiblot** [comment]
Sorry for reviving this.
I just wanted to point out that the current behaviour doesn't match what the Settings page promises:

![Screenshot_20190710_233713](https://user-images.githubusercontent.com/20713561/61006988-01975080-a36c-11e9-919d-e7c1376cf157.png)

From my experience, word-based suggestions require being explicitly enabled through the language-specific settings @sean-mcmanus pointed out before (thanks!), something the Settings page doesn't say a word about.

I don't really mind what the default behaviour is, but I find it reasonable to demand that (1) information in the Settings page matches the actual behaviour, and (2) enough information is provided to prevent users from having to find this GitHub issue to get word-based suggestions working.

Thank you very much.
