### ISSUE TITLE
${config.XXX} not work in c_cpp_properties.json

### ISSUE THREAD

**Issue by JuHo1117** [microsoft/vscode-cpptools#314]
in `settings.json`
set `"HOME_MINGW": "x:/mingw32"`

in `tasks.json`
set `"command": "${config.HOME_MINGW}/bin/make.exe"`
"ctrl+b" Works for me

in `launch.json`
set `"MIDebuggerPath": "${config.HOME_MINGW}/bin/gdb.exe"`
“F5” works for me

in `c_cpp_properties.json`
set `"includePath": ["${config.HOME_MINGW}/include"]`
not work!!!

**Comment by sean-mcmanus** [comment]
We support ${env.VAR} and ${env:VAR}. Is that good enough?

**Comment by sean-mcmanus** [comment]
@JuHo1117 Fixed with 0.15.0.
