### ISSUE TITLE
Preprocessor defines #warning (and custom #warn) are not supported

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode-cpptools#3142]
**Type: LanguageService**

https://github.com/Microsoft/vscode-cpptools

**Describe the bug**
The preprocessor directives `#warning` and `#warn` are not suppored in Language Service.

- OS and Version:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18329 N/A Build 18329
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO 39CN16WW       , 7/29/2010
```
- VS Code Version:
```
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18329
```
- C/C++ Extension Version:
```
Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.21.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
```
- Other extensions you installed (and if the issue persists after disabling them): N/A

**To Reproduce**

1. Example:
``` C
#include <stdio.h>

#define A
#define B

#if defined(C)
// stuff here 1
#elif defined(D)
// stuff here 2
#  define some_define__ some/path/file.h

#else
#  warn can't some situation here
#endif

void main(){
	return 0;
}
```
2. See error: `The Language Service does not work in this case`
2.1: error #1: `unrecognized preprocessing directive`
2.2: error #2: The code highlight is wrong. (not even GitHub understands this.)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
What is "#warn"? What compiler supports that? Where is that defined in the C/C++ language?

#warning is expected to work if we ever ship warning support -- it was implemented, but post-poned because we wanted to add the ability to suppress unwanted warnings first: https://github.com/Microsoft/vscode-cpptools/issues/828

UPDATE: And our extension doesn't implement any syntax colorization yet, so "#warn" would need to be added the VS Code's implementation (i.e. atom/language-c).

**Comment by n3rd4i** [comment]
Some embedded compilers support this `#warn` which is `#warning` preprocessor directive.
Example [doc](http://www.tij.co.jp/jp/lit/ug/sprui04b/sprui04b.pdf) page. 45

Maybe it could be a good Idea to allow users to customize this so the Language Service understand such syntax.

**Comment by n3rd4i** [comment]
not sure if there is update on this, will close because its stalled
