### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dmslabsbr** [microsoft/vscode-cpptools#3143]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.21.0`
- OS Version: `Darwin x64 17.7.0`
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/2843231/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/dms/ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bobbrow** [comment]
Thank you for your issue report.  This looks to be the same issue reported in #2991.
