### ISSUE TITLE
Building up stack in debugger really slow

### ISSUE THREAD

**Issue by dirkseidel** [microsoft/vscode-cpptools#3144]
After hitting a breakpoint it takes a really long time for the local variables to be displayed. The whole time the plugin is busy with building up the stack trace. In my case there are approximately 260 threads displayed and it can be seen that the plugin works on the threads one after the other. Stepping through the code takes roughly 50 seconds for the variables to show up for every single step, which is practically unusable.
In addition, almost all threads in the stack view are expanded and so it is very hard to find the thread where the breakpoint is hit and I cannot find any way to collapse the view.
This behaviour appeared after the recent update of VS Code to version 1.31.0. Cpptools should be up to date with version 1.21.0.

**Comment by dirkseidel** [comment]
I just reverted to 1.30.2 and deactivated updates. Like this everything works fine again.

**Comment by pieandcakes** [comment]
@dirkseidel Do you mind getting me some logs for your instance before and after? If so I can send specific instructions on how to generate a log to disk.

**Comment by dirkseidel** [comment]
@pieandcakes Please let me know how to generate the logs to disk.

**Comment by pieandcakes** [comment]
* In your `VS Code extension folder` find the following file: `.vscode\extensions\ms-vscode.cpptools-0.21.0\out\src\Debugger\extension.js`.
* Scroll down to `function registerAdapterExecutableCommands()` and replace this block:
```
                return {
                    command: command
                };
```
with this block, specifying the logfile location to replace `<log file location>`
```
                return {
                    command: command,
                    args: ['--engineLogging=<log file location>' ]
                };
            }
```
* Restart debugging

If you can do this for the working and non-working case and send it to me in an email, I can diff the files and see what is different. My email address is in my profile.

**Comment by pieandcakes** [comment]
Thanks @dirkseidel  for the logs. After looking at them, it looks like with 250+ threads, in VS Code 1.31, we are receiving a StackTrace request for each thread when stopping, which is why it is taking much longer.

I've opened https://github.com/Microsoft/vscode/issues/68648 on their page for them to look into it.

**Comment by BaronZemo** [comment]
Looks like #2901 is probably related.

**Comment by dirkseidel** [comment]
Works again with 1.32.1, thanks!
