### ISSUE TITLE
[question] Is code open?

### ISSUE THREAD

**Issue by mkwork** [microsoft/vscode-cpptools#315]
Is code open or are there plans to make it so?
If it's open, where can I get it?
If it's not and/or not planned, that's should be documented in README.md in project's root.

**Comment by delmyers** [comment]
Portions of the code are open, and portions are not. This extension mostly connects several different technologies together to create an edit and debug experience. The technologies that are used depend on the platform that your are on. The major technologies used are:
Microsoft MiEngine (open: http://github.com/microsoft/MiEngine)
lldb-mi (open: http://lldb.llvm.org/)
clang-format (open: http://clang.llvm.org)
Microsoft C++ language service (closed)
Microsoft Visual Studio Debugger for Windows (closed)

Mono is also used on Linux and Mac to execute some .NET code. 

All of this information is in various third party notices and licences that come with the extension. Thanks for the suggestion about the README.md.

**Comment by mkwork** [comment]
Thank you.
