### ISSUE TITLE
launch: program '/home/pi/testc/a.out' does not exist

### ISSUE THREAD

**Issue by xujintao** [microsoft/vscode-cpptools#3156]
os: ubuntu18.04
vscode: 1.31.0
c/c++ extention: 0.21.0

When i press F5 in vscode, it tips launch: program '/home/pi/testc/a.out' does not exist.
I can g++ -g main.c and gdb a.out in terminal.

my main.c:
```c
#include <stdio.h>

int main(){
    printf("hello\n");
    return 0;
}
```

launch.json:
```js
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

tasks.json:
```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g",
                "${workspaceFolder}/main.c"
            ]
        }
    ]
}
```

**Comment by pieandcakes** [comment]
Can you confirm that your a.out is actually in the folder `/home/pi/testc/` ? We do a file check to make sure that the file `a.out` is actually there and that seems to be failing.

Also, if you want to use your task as part of the `launch` you need to add a `preLaunchTask` inside your `launch.json` with the `label` name as the `task` name.

**Comment by xujintao** [comment]
@pieandcakes 
After ctrl + shift + B, vscode popup this:
![image](https://user-images.githubusercontent.com/5418373/52782079-20c5d680-3089-11e9-8781-070686ec3514.png)
then this:
![image](https://user-images.githubusercontent.com/5418373/52782130-47840d00-3089-11e9-8451-ccfe7b9476ff.png)
tasks.json add group field automaticlly, then a.out comes out, and also F5 works.
so, ctrl + shift + B is build task, and F5 is debug in vscode.
![image](https://user-images.githubusercontent.com/5418373/52782226-84500400-3089-11e9-9aaa-a4de1c944161.png)
![image](https://user-images.githubusercontent.com/5418373/52782321-b95c5680-3089-11e9-9c50-a5377343c8c8.png)

I thought it could be like vs in which F5 is build + debug.

anyway, thanks.

**Comment by pieandcakes** [comment]
@xujintao if you want build to be part of debug, my comment here will fix your problem:
>Also, if you want to use your task as part of the `launch` you need to add a `preLaunchTask` inside your `launch.json` with the `label` name as the `task` name.
