### ISSUE TITLE
didChangeCustomConfiguration doesn't update the IntelliSense server in some cases

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#3158]
There is a race condition in the config provider stuff where an IntelliSense server may not be updated with the config provider's request. The scenario is this:

1. user opens a file in the editor.
2. user closes the file before the config provider sends the configuration
3. config provider sends the configuration
4. user reopens the file

What happens is that the IntelliSense server stays alive for a brief period after the file is closed. If the custom configuration comes in during that time, the IntelliSense server will not be refreshed with the new configuration because it checks whether the file is open instead of whether the server is still active.  If the user then reopens the file before the server expires, we will reattach to the existing server and the new configuration will not be applied.

**Comment by Colengms** [comment]
This should be addressed in >= 0.26.3-insiders, as this was changed to discard the outdated TU before checking if the file is open.  (If open, we also trigger an update, which causes a new TU to be created).
