### ISSUE TITLE
Unknown Error: 0x800700c1  when Debug

### ISSUE THREAD

**Issue by mazhan465** [microsoft/vscode-cpptools#316]
When I debug a .c file.It is follows:
![qq 20161029165653](https://cloud.githubusercontent.com/assets/20238053/19828466/e24d75d6-9df8-11e6-824c-e7655d19e1f6.png)

**Comment by pieandcakes** [comment]
@mazhan465 Can you share with me how this was compiled and your launch.json file contents?

**Comment by pieandcakes** [comment]
@mazhan465 if you use the Visual C++ debugger on windows, the executable needs to be compiled with Visual C/C++. If you are debugging a gcc/g++ compiled app you need to choose gdb as the debugging option when initially setting up the launch.json file. You can delete the launch.json file and hit the gear button and choose the C++ (GDB\LLDB) option.

**Comment by mazhan465** [comment]
Thanks.I have solve this problem for debuging with GDB.I think the error is that I haven't compiled with vcbuildtools.

**Comment by Haneesh07** [comment]
try creating a folder in the same environment of python or cpp and add your code file into it. then open the vs code, it worked for me. I was getting this error while coding in tensorflow python.
![image](https://user-images.githubusercontent.com/30610865/30507575-7959dca6-9ada-11e7-8d75-cdfe5e427ca9.png)

**Comment by sean-mcmanus** [comment]
@haneeshh Is this with debugging C++? Your screenshot doesn't show any error.

**Comment by Haneesh07** [comment]
Its just I wanted to share how I solved this error. @sean-mcmanus ,there are no errors in the screenshot yes.

**Comment by sean-mcmanus** [comment]
@haneeshh Yeah, I misunderstood. I thought you were reporting a bug :)

**Comment by Haneesh07** [comment]
@sean-mcmanus  no worries :)

**Comment by AchalaSB** [comment]
![capture](https://user-images.githubusercontent.com/41888986/43571531-d2ec2f36-965a-11e8-9e65-b9787018bc18.JPG)

Hi,
Im unable get output using windows. I have installed C++ extension and minGW 64.

I tried using c++(GDB/LLDB) also but it didn't work for me. It shows miDebugerpath error but the path was proper.

**Comment by BXDM** [comment]
I use python also have this problem!

**Comment by durga-koppisetti** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/74443703/99189669-4fa23c80-2788-11eb-8d2a-73051da43c17.png)

**Comment by durga-koppisetti** [comment]
can anyone help me to run my first program in c

**Comment by sean-mcmanus** [comment]
@durga-koppisetti We have some docs at https://code.visualstudio.com/docs/cpp/config-mingw . "helloworld" isn't a valid file -- it seems to be helloworld.exe....there might be other issues too.
