### ISSUE TITLE
command 'C_Cpp.GoToDeclaration' not found

### ISSUE THREAD

**Issue by rivergold** [microsoft/vscode-cpptools#3160]
Type: General

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.30.2
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
    When I use `ctrl` + `F12` to go to a declaration, occur error command 'C_Cpp.GoToDeclaration' not found

I have tried other lower C/C++ Extension Version, it can run correctly. Is there something wrong in version 0.21.0?

**Comment by sean-mcmanus** [comment]
Our process is probably failing to start. I assume other C_Cpp commands also fail? We haven't gotten other reports of 0.21.0 failing yet. Your machine might be lacking some runtime shared library our Microsoft.VSCode.CPP.Extension.linux process requires. Are you sure you have 0.21.0 and not 0.22.0-insiders? Does 0.22.0-insiders fail too? When you do Help->Toggle Developer Tools does it show any errors in the console? Can you launch ~/.vscode/extesnsions/ms-vscode-cpptools-0.21.0/bin/Microsoft.VSCode.CPP.Extension.linux ?

Are you missing any of these shared libraries?
```ldd Microsoft.VSCode.CPP.Extension.linux
	linux-vdso.so.1 =>  (0x00007ffee7b73000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2ca3136000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2ca2f18000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2ca2b4f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2ca294b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2ca2743000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2ca252b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2ca343c000)
```

**Comment by rivergold** [comment]
There are some reasons caused the program failed to start. After I uninstall the extension, restart the computer and reinstall the extension, it can work……

**Comment by sean-mcmanus** [comment]
Restarting your computer shouldn't be required, but re-installing the extension and/or restarting VS Code may have fixed it. If this is specific to Go to Declaration, then using the built-in Go to Declaration might fix this: https://github.com/Microsoft/vscode-cpptools/issues/2959 .

**Comment by sean-mcmanus** [comment]
I found a repro -- it occurs if a command is executed before our extension has fully initialized. The code is supposed to register the command but then delay it until we're ready to handle. It looks like something regressed that (maybe the command localization change?).

UPDATE: It's been fixed for our next release (at least the repro I was hitting) -- the root bug has existed "forever", but changes that have made our activation slower may have caused it to repro more often.
