### ISSUE TITLE
(Mac OS Mojave) Debugging C: ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". Command 'exec-run'. Invalid process during debug session. EXIT CODE 42

### ISSUE THREAD

**Issue by bklxxjjz** [microsoft/vscode-cpptools#3161]
Type: Debugger
**Debugging C: ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". Command 'exec-run'. Invalid process during debug session. EXIT CODE 42**

**Describe the bug**
- OS and Version: OS Mojave 10.14.3
- VS Code Version: 1.22.2
- C/C++ Extension Version: 0.17.4
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

When I try to debug C with the extension installed, I am getting this error initializing the debugger. The launch.json is set as follows:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/./shell.o",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb"
        }
    ]
}
The shell.o executable is compiled with -g flag and can be debugged with gdb/lldb. I used to be able to debug a few months ago but now I am having this issue. I have reviewed similar issues but cannot find a working solution.

**Comment by WardenGnaw** [comment]
Can you [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) and share it here?

**Comment by Dantee296** [comment]
@WardenGnaw i am facing same issue , any update here

**Comment by WardenGnaw** [comment]
@Dantee296 Can you [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) and share it here? This will help with the investigation.

**Comment by Dantee296** [comment]
@WardenGnaw 

> 

1: (149) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
1: (161) LaunchOptions  ExePath='/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy-iproxy.o'
1: (161) LaunchOptions  WorkingDirectory='/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd'
1: (161) LaunchOptions  ExeArguments=''
1: (161) LaunchOptions  MIMode='lldb'
1: (161) LaunchOptions  MIDebuggerPath='/Users/dantee296/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/lldb/bin/lldb-mi'
1: (161) LaunchOptions  WaitDynamicLibLoad='false'
1: (161) LaunchOptions>
1: (162) LaunchOptions    <LaunchCompleteCommand>exec-run</LaunchCompleteCommand>
1: (162) LaunchOptions</LocalLaunchOptions>
1: (267) Starting: "/Users/dantee296/.vscode/extensions/ms-vscode.cpptools-0.21.0/debugAdapters/lldb/bin/lldb-mi" --interpreter=mi
1: (291) DebuggerPid=46913
1: (442) ->(gdb)
1: (456) <-1001-gdb-set auto-solib-add on
1: (457) ->1001^done
1: (457) ->(gdb)
1: (459) 1001: elapsed time 3
1: (460) <-1002-gdb-set solib-search-path "/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools:"
1: (460) ->1002^done
1: (460) 1002: elapsed time 0
1: (460) <-1003-environment-cd /Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd
1: (460) ->(gdb)
1: (461) ->1003^done,path="/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd"
1: (463) ->(gdb)
1: (465) 1003: elapsed time 4
1: (465) <-1004-file-exec-and-symbols /Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy-iproxy.o
1: (468) STDERR: Traceback (most recent call last):
1: (469) STDERR:   File "<input>", line 1, in <module>
1: (469) STDERR:   File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
1: (469) STDERR:     import weakref
1: (470) STDERR:   File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
1: (470) STDERR:     from _weakref import (
1: (470) STDERR: ImportError: cannot import name _remove_dead_weakref
1: (518) ->1004^done
1: (518) ->(gdb)
1: (518) 1004: elapsed time 53
1: (518) ->=library-loaded,id="/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy-iproxy.o",target-name="/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy-iproxy.o",host-name="/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy-iproxy.o",symbols-loaded="0",loaded_addr="-",size="7024"
1: (520) <-1005-interpreter-exec console "platform status"
1: (521) ->  Platform: host
1: (522) ->    Triple: x86_64h-apple-macosx
1: (522) ->OS Version: 10.14.3 (18D109)
1: (523) ->    Kernel: Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
1: (523) ->  Hostname: 127.0.0.1
1: (523) ->WorkingDir: /Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd
1: (523) ->1005^done
1: (524) ->(gdb)
1: (525) 1005: elapsed time 4
1: (526) <-1006-break-insert -f on main
1: (527) ->1006^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0000000000000011",func="main",file="iproxy.c",fullname="/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy.c",line="254",pending=["main"],times="0",original-location="main"}
1: (527) ->(gdb)
1: (528) ->=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0000000000000011",func="main",file="iproxy.c",fullname="/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy.c",line="254",pending=["main"],times="0",original-location="main"}
1: (528) ->(gdb)
1: (529) 1006: elapsed time 3
1: (577) <-1007-break-insert -f on iproxy.c:252
1: (578) ->1007^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x0000000000000011",func="main",file="iproxy.c",fullname="/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy.c",line="254",pending=["iproxy.c:252"],times="0",original-location="iproxy.c:252"}
1: (578) ->(gdb)
1: (578) 1007: elapsed time 1
1: (579) ->=breakpoint-modified,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x0000000000000011",func="main",file="iproxy.c",fullname="/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy.c",line="254",pending=["iproxy.c:252"],times="0",original-location="iproxy.c:252"}
1: (579) ->(gdb)
1: (601) <-1008-break-insert -f on libusbmuxd.c:951
1: (601) ->1008^done,bkpt={number="3",type="breakpoint",disp="keep",enabled="y",addr="0xffffffffffffffff",func="??",file="??",fullname="??/??",line="0",pending=["libusbmuxd.c:951"],times="0",original-location="libusbmuxd.c:951"}
1: (601) 1008: elapsed time 0
1: (601) ->(gdb)
1: (602) ->=breakpoint-modified,bkpt={number="3",type="breakpoint",disp="keep",enabled="y",addr="0xffffffffffffffff",func="??",file="??",fullname="??/??",line="0",pending=["libusbmuxd.c:951"],times="0",original-location="libusbmuxd.c:951"}
1: (602) ->(gdb)
1: (605) <-1009-break-insert -f on reenumerate.c:76
1: (605) ->1009^done,bkpt={number="4",type="breakpoint",disp="keep",enabled="y",addr="0xffffffffffffffff",func="??",file="??",fullname="??/??",line="0",pending=["reenumerate.c:76"],times="0",original-location="reenumerate.c:76"}
1: (605) 1009: elapsed time 0
1: (605) ->(gdb)
1: (609) ->=breakpoint-modified,bkpt={number="4",type="breakpoint",disp="keep",enabled="y",addr="0xffffffffffffffff",func="??",file="??",fullname="??/??",line="0",pending=["reenumerate.c:76"],times="0",original-location="reenumerate.c:76"}
1: (609) ->(gdb)
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
1: (648) <-1010-exec-run
1: (649) ->1010^error,msg="Command 'exec-run'. Invalid process during debug session"
1: (649) ->(gdb)
1: (649) 1010: elapsed time 1
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". Command 'exec-run'. Invalid process during debug session
1: (661) <--gdb-exit
1: (662) ->^exit
1: (662) ->=thread-group-exited,id="i1"
1: (662) ->(gdb)
1: (662) ->
1: (662) ->
1: (663) <-logout
The program '/Users/dantee296/Desktop/Working/GitProject/Library-iPhone/libusbmuxd/tools/iproxy-iproxy.o' has exited with code 42 (0x0000002a).

>

**Comment by Dantee296** [comment]
**Task.json**

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "make",
            "args": [],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        }
    ]
}

**Launch.json**

{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/tools/iproxy-iproxy.o",
            "internalConsoleOptions": "openOnSessionStart",
            "logging": {
                "moduleLoad": false,
                "programOutput": true,
                "trace": false,
                "engineLogging" : true
            },
            "showDisplayString": false,
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false, // set true to enable keyboard input
            "launchCompleteCommand": "exec-run",
            "osx": {
                "MIMode": "lldb"
            }
        }
    ]
}

**Comment by Dantee296** [comment]
@WardenGnaw any update

**Comment by WardenGnaw** [comment]
Do you see a prompt when start debugging?

macOS requires authorization when running the debugger with Developer Tools. It should say something like
```Developer Tools Access is trying to take control of another process. Enter your password to allow this.```

If you do not have authorization then lldb will fail to `-exec-run`.

**Comment by Dantee296** [comment]
i think i allowed it . any way to get it back ?

**Comment by WardenGnaw** [comment]
If you restart your machine, you should be able to get the prompt back.

**Comment by slashrsm** [comment]
I am facing the same problem. After following the [official debugging docs](https://code.visualstudio.com/docs/cpp/config-clang-mac) I have:

### launch.json

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(lldb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/helloworld.out",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": true,
      "MIMode": "lldb",
      "logging": {
        "trace": true,
        "traceResponse": true,
        "engineLogging": true
      }
    }
  ]
}
```

### tasks.json

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Build with Clang",
      "type": "shell",
      "command": "clang++",
      "args": [
        "-std=c++17",
        "-stdlib=libc++",
        "helloworld.cpp",
        "-o",
        "helloworld.out",
        "--debug"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

### c_cpp_properties.json

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks",
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "${default}"
        }
    ],
    "version": 4
}
```

I did see the access prompt when I launched it and I did approve it. Nonetheless, I am still seeing the same error in the logs:

```
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (130) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'\n"},"seq":2}
1: (130) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (141) LaunchOptions  ExePath='/Users/slashrsm/Workspace/helloworld/helloworld.out'\n"},"seq":4}
1: (141) LaunchOptions  ExePath='/Users/slashrsm/Workspace/helloworld/helloworld.out'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (141) LaunchOptions  WorkingDirectory='/Users/slashrsm/Workspace/helloworld'\n"},"seq":6}
1: (141) LaunchOptions  WorkingDirectory='/Users/slashrsm/Workspace/helloworld'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (141) LaunchOptions  ExeArguments=''\n"},"seq":8}
1: (141) LaunchOptions  ExeArguments=''
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (141) LaunchOptions  MIMode='lldb'\n"},"seq":10}
1: (141) LaunchOptions  MIMode='lldb'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (142) LaunchOptions  MIDebuggerPath='/Users/slashrsm/.vscode/extensions/ms-vscode.cpptools-0.26.2-insiders/debugAdapters/lldb/bin/lldb-mi'\n"},"seq":12}
1: (142) LaunchOptions  MIDebuggerPath='/Users/slashrsm/.vscode/extensions/ms-vscode.cpptools-0.26.2-insiders/debugAdapters/lldb/bin/lldb-mi'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (142) LaunchOptions  WaitDynamicLibLoad='false'\n"},"seq":14}
1: (142) LaunchOptions  WaitDynamicLibLoad='false'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (142) LaunchOptions  ExternalConsole='true'\n"},"seq":16}
1: (142) LaunchOptions  ExternalConsole='true'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (142) LaunchOptions>\n"},"seq":18}
1: (142) LaunchOptions>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (142) LaunchOptions</LocalLaunchOptions>\n"},"seq":20}
1: (142) LaunchOptions</LocalLaunchOptions>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (228) Starting: \"/Users/slashrsm/.vscode/extensions/ms-vscode.cpptools-0.26.2-insiders/debugAdapters/lldb/bin/lldb-mi\" --interpreter=mi\n"},"seq":22}
1: (228) Starting: "/Users/slashrsm/.vscode/extensions/ms-vscode.cpptools-0.26.2-insiders/debugAdapters/lldb/bin/lldb-mi" --interpreter=mi
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (249) DebuggerPid=1906\n"},"seq":24}
1: (249) DebuggerPid=1906
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (416) ->(gdb)\n"},"seq":26}
1: (416) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (431) <-1001-gdb-set auto-solib-add on\n"},"seq":28}
1: (431) <-1001-gdb-set auto-solib-add on
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (432) ->1001^done\n"},"seq":30}
1: (432) ->1001^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (432) ->(gdb)\n"},"seq":32}
1: (432) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (434) 1001: elapsed time 3\n"},"seq":34}
1: (434) 1001: elapsed time 3
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (435) <-1002-gdb-set solib-search-path \"/Users/slashrsm/Workspace/helloworld:\"\n"},"seq":36}
1: (435) <-1002-gdb-set solib-search-path "/Users/slashrsm/Workspace/helloworld:"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (435) ->1002^done\n"},"seq":38}
1: (435) ->1002^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (435) 1002: elapsed time 0\n"},"seq":40}
1: (435) 1002: elapsed time 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (435) <-1003-environment-cd /Users/slashrsm/Workspace/helloworld\n"},"seq":42}
1: (435) <-1003-environment-cd /Users/slashrsm/Workspace/helloworld
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (436) ->(gdb)\n"},"seq":44}
1: (436) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (436) ->1003^done,path=\"/Users/slashrsm/Workspace/helloworld\"\n"},"seq":46}
1: (436) ->1003^done,path="/Users/slashrsm/Workspace/helloworld"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (436) ->(gdb)\n"},"seq":48}
1: (436) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (440) 1003: elapsed time 4\n"},"seq":50}
1: (440) 1003: elapsed time 4
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (440) <-1004-gdb-set new-console on\n"},"seq":52}
1: (440) <-1004-gdb-set new-console on
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (440) ->1004^done\n"},"seq":54}
1: (440) ->1004^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (440) 1004: elapsed time 0\n"},"seq":56}
1: (440) 1004: elapsed time 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (441) ->(gdb)\n"},"seq":58}
1: (441) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (441) <-1005-file-exec-and-symbols /Users/slashrsm/Workspace/helloworld/helloworld.out\n"},"seq":60}
1: (441) <-1005-file-exec-and-symbols /Users/slashrsm/Workspace/helloworld/helloworld.out
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (715) ->1005^done\n"},"seq":62}
1: (715) ->1005^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (715) ->(gdb)\n"},"seq":64}
1: (715) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (715) 1005: elapsed time 274\n"},"seq":66}
1: (715) 1005: elapsed time 274
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (715) ->=library-loaded,id=\"/Users/slashrsm/Workspace/helloworld/helloworld.out\",target-name=\"/Users/slashrsm/Workspace/helloworld/helloworld.out\",host-name=\"/Users/slashrsm/Workspace/helloworld/helloworld.out\",symbols-loaded=\"1\",symbols-path=\"/System/Volumes/Data/Users/slashrsm/Workspace/helloworld/helloworld.out.dSYM/Contents/Resources/DWARF/helloworld.out\",loaded_addr=\"-\",size=\"12288\"\n"},"seq":68}
1: (715) ->=library-loaded,id="/Users/slashrsm/Workspace/helloworld/helloworld.out",target-name="/Users/slashrsm/Workspace/helloworld/helloworld.out",host-name="/Users/slashrsm/Workspace/helloworld/helloworld.out",symbols-loaded="1",symbols-path="/System/Volumes/Data/Users/slashrsm/Workspace/helloworld/helloworld.out.dSYM/Contents/Resources/DWARF/helloworld.out",loaded_addr="-",size="12288"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (717) <-1006-interpreter-exec console \"platform status\"\n"},"seq":70}
1: (717) <-1006-interpreter-exec console "platform status"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (718) ->  Platform: host\n"},"seq":72}
1: (718) ->  Platform: host
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (718) ->    Triple: x86_64h-apple-macosx\n"},"seq":74}
1: (718) ->    Triple: x86_64h-apple-macosx
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (718) ->OS Version: 10.15.1 (19B88)\n"},"seq":76}
1: (718) ->OS Version: 10.15.1 (19B88)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (718) ->    Kernel: Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64\n"},"seq":78}
1: (718) ->    Kernel: Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (718) ->  Hostname: 127.0.0.1\n"},"seq":80}
1: (718) ->  Hostname: 127.0.0.1
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (718) ->WorkingDir: /Users/slashrsm/Workspace/helloworld\n"},"seq":82}
1: (718) ->WorkingDir: /Users/slashrsm/Workspace/helloworld
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (719) ->1006^done\n"},"seq":84}
1: (719) ->1006^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (719) ->(gdb)\n"},"seq":86}
1: (719) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (720) 1006: elapsed time 3\n"},"seq":88}
1: (720) 1006: elapsed time 3
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (721) <-1007-break-insert -f on main\n"},"seq":90}
1: (721) <-1007-break-insert -f on main
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (724) ->1007^done,bkpt={number=\"1\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x00000001000007b7\",func=\"main\",file=\"helloworld.cpp\",fullname=\"/Users/slashrsm/Workspace/helloworld/helloworld.cpp\",line=\"10\",pending=[\"main\"],times=\"0\",original-location=\"main\"}\n"},"seq":92}
1: (724) ->1007^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x00000001000007b7",func="main",file="helloworld.cpp",fullname="/Users/slashrsm/Workspace/helloworld/helloworld.cpp",line="10",pending=["main"],times="0",original-location="main"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (724) ->(gdb)\n"},"seq":94}
1: (724) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (724) ->=breakpoint-modified,bkpt={number=\"1\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x00000001000007b7\",func=\"main\",file=\"helloworld.cpp\",fullname=\"/Users/slashrsm/Workspace/helloworld/helloworld.cpp\",line=\"10\",pending=[\"main\"],times=\"0\",original-location=\"main\"}\n"},"seq":96}
1: (724) ->=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x00000001000007b7",func="main",file="helloworld.cpp",fullname="/Users/slashrsm/Workspace/helloworld/helloworld.cpp",line="10",pending=["main"],times="0",original-location="main"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (724) ->(gdb)\n"},"seq":98}
1: (724) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (726) 1007: elapsed time 4\n"},"seq":100}
1: (726) 1007: elapsed time 4
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (733) Send Event AD7EngineCreateEvent\n"},"seq":102}
1: (733) Send Event AD7EngineCreateEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (736) Send Event AD7ProgramCreateEvent\n"},"seq":104}
1: (736) Send Event AD7ProgramCreateEvent
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.61023.1","VS.Diagnostics.Debugger.HostVersion":"14.0.61023.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.Duration":655,"VS.Diagnostics.Debugger.Launch.IsCoreDump":false,"VS.Diagnostics.Debugger.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.SourceFileMappings":0,"VS.Diagnostics.Debugger.MIMode":null}},"seq":106}
--> R (launch-2): {"type":"response","request_seq":2,"success":true,"command":"launch","body":{},"seq":108}
--> E (initialized): {"type":"event","event":"initialized","body":{},"seq":110}
<--   C (setFunctionBreakpoints-3): {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":3}
--> R (setFunctionBreakpoints-3): {"type":"response","request_seq":3,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]},"seq":113}
<--   C (setExceptionBreakpoints-4): {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":4}
--> R (setExceptionBreakpoints-4): {"type":"response","request_seq":4,"success":true,"command":"setExceptionBreakpoints","body":{},"seq":116}
<--   C (configurationDone-5): {"command":"configurationDone","type":"request","seq":5}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (770) Send Event AD7LoadCompleteEvent\n"},"seq":120}
1: (770) Send Event AD7LoadCompleteEvent
--> R (configurationDone-5): {"type":"response","request_seq":5,"success":true,"command":"configurationDone","body":{},"seq":119}
<--   C (threads-6): {"command":"threads","type":"request","seq":6}
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"Warning: Debuggee TargetArchitecture not detected, assuming x86_64.\n"},"seq":124}
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (774) <-1008-exec-run\n"},"seq":127}
1: (774) <-1008-exec-run
--> R (threads-6): {"type":"response","request_seq":6,"success":true,"command":"threads","body":{"threads":[]},"seq":126}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1294) ->1008^error,msg=\"Command 'exec-run'. Invalid process during debug session\"\n"},"seq":130}
1: (1294) ->1008^error,msg="Command 'exec-run'. Invalid process during debug session"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1295) ->(gdb)\n"},"seq":132}
1: (1295) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1295) 1008: elapsed time 520\n"},"seq":134}
1: (1295) 1008: elapsed time 520
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1301) Send Event AD7MessageEvent\n"},"seq":136}
1: (1301) Send Event AD7MessageEvent
--> E (output): {"type":"event","event":"output","body":{"category":"stderr","output":"ERROR: Unable to start debugging. Unexpected LLDB output from command \"-exec-run\". Command 'exec-run'. Invalid process during debug session\n"},"seq":138}
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". Command 'exec-run'. Invalid process during debug session
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1306) <--gdb-exit\n"},"seq":140}
1: (1306) <--gdb-exit
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1306) ->^exit\n"},"seq":142}
1: (1306) ->^exit
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1306) ->=thread-group-exited,id=\"i1\"\n"},"seq":144}
1: (1306) ->=thread-group-exited,id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1306) ->(gdb)\n"},"seq":146}
1: (1306) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1306) ->\n"},"seq":148}
1: (1306) ->
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1307) ->\n"},"seq":150}
1: (1307) ->
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1308) <-logout\n"},"seq":152}
1: (1308) <-logout
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1314) Send Event AD7ProgramDestroyEvent\n"},"seq":154}
1: (1314) Send Event AD7ProgramDestroyEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"The program '/Users/slashrsm/Workspace/helloworld/helloworld.out' has exited with code 42 (0x0000002a).\r\n\n"},"seq":156}
The program '/Users/slashrsm/Workspace/helloworld/helloworld.out' has exited with code 42 (0x0000002a).
--> E (exited): {"type":"event","event":"exited","body":{"exitCode":42},"seq":158}
--> E (terminated): {"type":"event","event":"terminated","body":{},"seq":160}
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.61023.1","VS.Diagnostics.Debugger.HostVersion":"14.0.61023.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":0}},"seq":162}
<--   C (disconnect-7): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":7}
--> R (disconnect-7): {"type":"response","request_seq":7,"success":true,"command":"disconnect","body":{},"seq":165}

```

It is worth noting that debugging works when running it manually from the command line. As I execute the program I see the access prompt and upon approving it everything proceeds as normal. 

**OS Version:** macOS Catalina 10.15.1
**Visual Studio Code:** 
```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```
**C++ extension:** 0.26.2-insider
**clang:** 
```
➜  helloworld clang++ --version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
**lldb:**
```
➜  helloworld lldb --version
lldb-1100.0.28.19
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
```

Is there any other helpful information that I could provide? Any suggestions what to investigate next? How exactly does the extension run the debugger? Could I try to run it with the same arguments manually and see what happens in that case?

**Comment by chuckb** [comment]
I had the same issue...I upgraded lldb to version 9 on osx 10.14.6, and problem went away.
