### ISSUE TITLE
Comment of a templated method does not get parsed if above template

### ISSUE THREAD

**Issue by tomasiser** [microsoft/vscode-cpptools#3162]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.31.0
- C/C++ Extension Version: 0.21.0

**To Reproduce**
Compare the standard Doxygen way of commenting templated methods:
```cpp
/// This is a nice function
template <typename T>
void hello(const T&);
```
and this non-standard way:
```cpp
template <typename T>
/// This is a nice function
void hello(const T&);
```

In the first (correct) case, the documentation comment does not get shown when the method is hovered.

**Expected behavior:**

The documentation comment gets parsed correctly and shows when hovered in the first situation the same way as in the second.

**Screenshots**

![image](https://user-images.githubusercontent.com/10374559/52717148-b5a0d500-2fa0-11e9-91cf-705c751f88f9.png)

![image](https://user-images.githubusercontent.com/10374559/52717125-a457c880-2fa0-11e9-806b-a5720b920122.png)

**Comment by sean-mcmanus** [comment]
The template doc comment bug is fixed with 0.23.0-insiders.
