### ISSUE TITLE
Intelli Sense Engine Fallback shouldn't be default

### ISSUE THREAD

**Issue by kevenv** [microsoft/vscode-cpptools#3165]
**Type: LanguageService**

**Describe the bug**
- C/C++ Extension Version: 0.21.0
- I thought intellisense was broken since I tried to check the members functions of some object by typing '.' but it just threw me all the symbols anywhere in my project, which is not what I expected. It took me forever to realize that the intellisense engine fallbacks to TagParser (so not context aware) by default when it cannot find _a single include_. It seems to me that it might be a bit much and could produce false positives of users thinking their intellisense is broken.

![image](https://user-images.githubusercontent.com/3892244/52735965-b0d72380-2f96-11e9-86eb-8fda3387a265.png)

**Comment by bobbrow** [comment]
Yes, we are planning to change the default for this value alongside some upcoming configuration improvements.  Thanks for opening an issue to track it.

**Comment by sean-mcmanus** [comment]
The default intelliSenseEngineFallback is Disabled with 0.23.0.
