### ISSUE TITLE
can't auto complete 

### ISSUE THREAD

**Issue by rgw5267** [microsoft/vscode-cpptools#3169]
版本: 1.31.1 (system setup)
提交: 1b8e8302e405050205e69b59abb3559592bb9e60
日期: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

I have configured c_cpp_properties.json.

**Screenshots**
- If it is modified from the middle, it will not auto complete.

![image](https://user-images.githubusercontent.com/1254990/52760939-5f896b80-304c-11e9-84b1-18071d0807dc.png)

![image](https://user-images.githubusercontent.com/1254990/52760848-08839680-304c-11e9-8423-570b99005724.png)

- The structure behind the operator cannot auto complete.

![image](https://user-images.githubusercontent.com/1254990/52760368-3ec01680-304a-11e9-8c8d-75016469557b.png)

**Comment by sean-mcmanus** [comment]
Can you try using Ctrl+Space to invoke completion (i.e. that is the intended workaround)? The current behavior appears to be "by design" (with the "can auto complete" at the end behavior being some unintentional deviation from how Visual Studio behaves)...although maybe we could change it to complete in the start/middle cases (I'm not sure why VS doesn't).

**Comment by sean-mcmanus** [comment]
It turns out this is a Visual Studio controlled issue -- in the start/middle cases our extension is not sent any completion message, but in the end case our extension gets a completion message. I'ved filed a VS Code bug at https://github.com/Microsoft/vscode/issues/68672 .

**Comment by sean-mcmanus** [comment]
@rgw5267 The VS Code team says "Yes, quick suggestions are designed to work at the end of words only". Feel free to add your thoughts to that VS Code issue as well if you think they should fix it.

**Comment by rgw5267** [comment]
Thank you, you have clearly explained what I want to say.

**Comment by rgw5267** [comment]
> @rgw5267 The VS Code team says "Yes, quick suggestions are designed to work at the end of words only". Feel free to add your thoughts to that VS Code issue as well if you think they should fix it.

Thank you, you have clearly explained what I want to say.

**Comment by rgw5267** [comment]
@sean-mcmanus Hi,  all cases that can‘t auto completed in Windows are normal in Linux.

Linux
> 版本: 1.33.1
> 提交: 51b0b28134d51361cf996d2f0a1c698247aeabd8
> 日期: 2019-04-12T08:59:47.459Z
> Electron: 4.1.1
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.30-electron.0
> OS: Linux x64 4.19.34-1-MANJARO

Windows
> 版本: 1.33.1 (system setup)
> 提交: 51b0b28134d51361cf996d2f0a1c698247aeabd8
> 日期: 2019-04-11T08:27:14.102Z
> Electron: 3.1.6
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

**Comment by xgdgsc** [comment]
I also hope it would auto completion in the middle. But considering how vscode repo likes to lock issues , I don' t know what to do.

**Comment by sean-mcmanus** [comment]
@xgdgsc You could create a new "feature request" in the vscode repo...or we could do that later.

**Comment by Colengms** [comment]
@sean-mcmanus The issue opened against VS Code was closed.  https://github.com/microsoft/vscode/issues/68672  Is there more follow-up to do, or should this issue be closed?

**Comment by sean-mcmanus** [comment]
@Colengms Can you file a feature request on VS Code? i.e. convert the issue I posted to a feature request?

**Comment by bobbrow** [comment]
It doesn't work in the middle of the word unless you press CTL+Space to force it. But we wouldn't own this behavior. VS Code would and they closed the issue we opened.
