### ISSUE TITLE
Support for Platform pre-processor defeintions

### ISSUE THREAD

**Issue by NZSmartie** [microsoft/vscode-cpptools#317]
Hi guys. 
Can support for definitions (VC: `\D`, gcc: `-D`, etc...) in `c_cpp_properties.json` be added. This would simplify browsing MACROs or functions that are declared in files which are wrapped inside `#ifdef`, `#ifndef`, `#else` blocks.

**Comment by bobbrow** [comment]
This is in the current version of the extension.  See duplicate issue #304 for more details.
