### ISSUE TITLE
can't hint local variable 

### ISSUE THREAD

**Issue by sakizhu** [microsoft/vscode-cpptools#3170]
why can't not hint local variable correctl?
![image](https://user-images.githubusercontent.com/9567827/52772090-a1c5a380-3072-11e9-8140-7164bf20a8aa.png)

**Comment by bobbrow** [comment]
The extension is probably not configured correctly.  Do you see any problems in the PROBLEMS window that say that the extension was unable to resolve one of your `#include` lines?

**Comment by sean-mcmanus** [comment]
To be more specific -- if we fall back to the "Tag Parser" then local variables won't be discoverable. Changing the intelliSenseEngineFallback setting to "Disabled" is another workaround.

**Comment by sakizhu** [comment]
> To be more specific -- if we fall back to the "Tag Parser" then local variables won't be discoverable. Changing the intelliSenseEngineFallback setting to "Disabled" is another workaround.

thank you very much, I have set the intelliSenseEngineFallback setting to "Disabled" , it works! but, why some hint are not exactly? some Member Variable like std::string can't be hinted correctly
![image](https://user-images.githubusercontent.com/9567827/52831526-eb180080-310f-11e9-84bf-70721855fd97.png)

**Comment by sean-mcmanus** [comment]
There are squiggles on "string", I assume because the definition can't be found -- it looks like your compilerPath isn't set correctly, so the "string" header is not able to be found. Can you set your compilerPath (in c_cpp_properties.json or the C_Cpp.default.compilerPath setting)?

Or maybe you need to use "std::string"?

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
