### ISSUE TITLE
Last indent level converted to spaces (.clang-format set to `UseTab: Always`)

### ISSUE THREAD

**Issue by daravi** [microsoft/vscode-cpptools#3172]
**Type: LanguageService**

I am using "C_Cpp.Clang_format_style": "file" to specify my custom formatting. Here is my `.clang-format` file content:
```
BasedOnStyle: LLVM
UseTab: Always
IndentWidth: 4
```

However, when formatting, vs-code converts the last indentation level to spaces. For example if I have 4 indentation levels the fourth one is converted to spaces. I have set detectIndentation and insertSpaces to false.

**Describe the bug**
- OS and Version: MacOS 10.13.6
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21.0
- Description of what the bug is: Last indent level is converted to spaces on formatting (.clang-format file defines `UseTab: Always`)

**To Reproduce**

1- Set "C_Cpp.Clang_format_style" to "file" 
2- Create a .clang-format file in project root:
```
BasedOnStyle: LLVM
UseTab: Always
IndentWidth: 4
```
3- Attempt to format a file

**Expected behavior**
All indentation levels must be tabs.

**Additional context**
Please note that when I select Tab Size > Convert Indentation to Tabs all levels are converted to tabs as expected. But after reformatting the file the last level is turned back to spaces.

**Resources**
https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by daravi** [comment]
I think this might be a convenience feature of vscode and not an actual case of space-indentation.

**Comment by Tronic** [comment]
Could you elaborate on how is this a convenience feature? I have VSCode and clang-format both set to use tabs, and yet every time I paste, the last level of surrounding code gets indented by spaces.

It would be *convenient* if clang-format followed VSCode indent setting without even requiring separate 
indentation settings there.

**Comment by sean-mcmanus** [comment]
@Tronic I'm not able to repro this issue, although I used
```
BasedOnStyle: LLVM
UseTab: Always
IndentWidth: 4
TabWidth: 4
```

If someone can provide a specific code example that might help.

**Comment by Tronic** [comment]
@sean-mcmanus Missing TabWidth seemed to be causing this. It would make sense for UseTab, IndentWidth and TabWidth all to follow the indentation choice made in VS Code, but at least manually configuring avoids the paste misformat issue. Thanks!

**Comment by sean-mcmanus** [comment]
@Tronic When the default "Visual Studio" style is used, we do inherit the VS Code tab/indent-related settings, but when a .clang-format file is used, we don't do anything to change that, because clang-format itself reads the .clang-format directly. Theoretically we could read/parse/modify the .clang-format ourselves and stop sending "file" to clang-format.

This issue https://github.com/microsoft/vscode-cpptools/issues/657 is related (although it morphed into a different issue).

**Comment by daravi** [comment]
> Could you elaborate on how is this a convenience feature?

@Tronic Sorry I missed your question. I don't remember tbh since this was a while back. But I think at least at that time I had come to the conclusion that the editor was showing the last indent level as spaces but it was only for ease of navigation and not actual tab characters.
I might be remembering incorrectly or have been wrong about what vscode was doing, but it seems that your issue is resolved so cheers!
