### ISSUE TITLE
Enable IntelliSense error messages to be modified

### ISSUE THREAD

**Issue by zhouhangzooo** [microsoft/vscode-cpptools#3179]
Hello, I want to modify the smart prompt, such as the original prompt identifier "XXX" is undefined this paragraph, I would like to modify this paragraph, how do I do?

**Comment by bobbrow** [comment]
Sorry, I don't understand what you're asking for.  Can you include a code snippet or screenshot with an example of what you mean?

**Comment by sean-mcmanus** [comment]
@bobbrow "identifier XXX is undefined" is an IntelliSense error message, so it sounds like they want to modify that, possibly to localize the text or maybe to disable the error?

**Comment by zhouhangzooo** [comment]
> Sorry, I don't understand what you're asking for.  Can you include a code snippet or screenshot with an example of what you mean?

Yes, we want to modify this "identifier XXX is undefined" intellisense error message, because we may not understand this prompt on our side, so we want to make this prompt a little more detailed, so we ask you whether there is a way to modify this prompt.

**Comment by sean-mcmanus** [comment]
There is not currently a way to modify this text. We do eventually plan to have the message localized for different languages, but I don't know if that implementation will allow user-modifications. If we started exposing error codes (based on change https://github.com/Microsoft/vscode-cpptools/issues/2345 ), then we could also expose a setting that could enable different messages to be used for the error codes, but such a feature is not currently a high priority for us to implement. Can you elaborate on what "a little more detailed" means? Is there some more info would could add to the message ourselves?

**Comment by zhouhangzooo** [comment]
About this "a little more detailed" it says that we can edit the text of this prompt, and not let you write it, and of course you can translate the text messages to different languages, and I suggest that you publish the methods for converting the language so that some of the users' needs can be met. Also is you the error message not accurate enough (as shown in figure, the error is less a semicolon, in the red wavy lines "printf", this should prompt behind "int n") and we will demand was to the tooltip text edit (custom text, the last photo tip "identifier" aa "is undefined"), because some users don't understand the tooltip text is what meaning, we want the tooltip text explain more details. For example, change "identifier "aa" is undefined" to "identifier "aa" is undefined, you need to create this custom function".
![1550629869 1](https://user-images.githubusercontent.com/37395573/53062381-9b647b00-34fb-11e9-8b4f-cb9b260196e4.jpg)
![image](https://user-images.githubusercontent.com/37395573/53062434-bfc05780-34fb-11e9-9c83-c1c54f1fcdf5.png)
![image](https://user-images.githubusercontent.com/37395573/53062617-555be700-34fc-11e9-87ed-f91cc7d06dd9.png)

**Comment by sean-mcmanus** [comment]
The "identifier is undefined" code occurs in our parser even when the identifier is not part of a function call expression, so if you modified the text to add the "you need to create this custom function" then it would apply even for "return undefined_var", which would be incorrect. It is unlikely that we would modify our parser to have a different error code if `()` is after the undefined identifier.
