### ISSUE TITLE
Extension builds symbols very slowly and delays autoComplete

### ISSUE THREAD

**Issue by dtasev** [microsoft/vscode-cpptools#318]
Hello, I've been having issues with this extension, up to the point where I had to uninstall it because it would make the auto complete that VSCode provides unusable.

- Regardless of whether `C_Cpp.autocomplete` is set to `Default` or `Disabled` the auto complete is stuck on `Loading...` most of the time, I imagine that is because the extension is building symbols?
- The extension seems to lose the built symbols for a file (after 30secs of building) on each editor change

I'll provide any info additional info you want if I can.
Some info about the project: 
- It's large (10k+ files)
- It's mostly on cpp and python, but there's a wide variety of file types
- I've added loads of file extensions to be ignored (not sure if this affects which files are processed)

**Comment by dtasev** [comment]
Actually this is something that also happens while using the Python extension (on the same project). VSCode is building symbols and the auto complete stops working. To me it sounds like there could be a deeper issue with VSCode and it's not the extension's fault.

In this case:
- The cpp extension is uninstalled so it is not the cause
- Only the Python extension in installed and is busy building symbols

@pieandcakes Should this be closed in this case? I'm going to go ahead and open an issue on the official VSCode repo

**Comment by pieandcakes** [comment]
@DimitarTasev If you open an issue in the VSCode repo, you can link and close this issue. If it happens that we need to investigate again, you should be able to reopen it. 

Thanks
-Pierson

**Comment by dtasev** [comment]
Issue in VSCode repo: https://github.com/Microsoft/vscode/issues/14848, closing this until we have some answer in it
