### ISSUE TITLE
This extension cannot find the right include path.

### ISSUE THREAD

**Issue by wxutopia** [microsoft/vscode-cpptools#3186]
**Type: LanguageService**

**Describe the bug**
- OS and Version:Manjaro 18.0.2 Illyria
- VS Code Version:1.30
- C/C++ Extension Version:0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
When I include stdio.h file in a c++ program, the extension hints: cannot open source file "stdarg.h" (dependency of "stdio.h").There are four directories where I can find stdio.h file: /usr/include/bits, /usr/include/bsd, /usr/include/c++/8.2.1/tr1, /usr/include.The last one is the file I need, but the extension always include other directory's stdio file.The gcc version in my computer is 8.2.1.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
This scenario is supposed to work. Have you set your compilerPath to the gcc you're using (and removed any compiler-provided system headers from your includePath)?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
