### ISSUE TITLE
"includePath" just don't work

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3187]
**Describe the bug**
- OS and Version: Win 10
- VS Code Version: latest
- C/C++ Extension Version: latest
- Other extensions you installed (and if the issue persists after disabling them): none
- A clear and concise description of what the bug is.

**To Reproduce**
1. Download DirectX SDK: https://www.microsoft.com/en-us/download/details.aspx?id=6812
2. Add it to include paths
3. Try to include `d3d9.h` or `d3dx9.h`
4. Build project with g++
5. See error

**Expected behavior**
Successful build

**Description:**
c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Win32",
            "compilerPath": "D:/Soft/MinGW/bin/g++.exe",
            "includePath": [
                "D:/Soft/Microsoft DirectX SDK (June 2010)/Include",
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "browse": {
                "path": [
                    "D:/Soft/Microsoft DirectX SDK (June 2010)/Include",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

Works:
my.h
```c++
#include <D:\Soft\Microsoft DirectX SDK (June 2010)\Include\d3d9.h>
#include <D:\Soft\Microsoft DirectX SDK (June 2010)\Include\d3dx9.h>

#pragma comment(lib, "d3d9.lib")
#pragma comment(lib, "d3dx9.lib")
```

Does't work:
```c++
#include <d3d9.h>
#include <d3dx9.h>

#pragma comment(lib, "d3d9.lib")
#pragma comment(lib, "d3dx9.lib")
```

Error:
![image](https://user-images.githubusercontent.com/5371279/52913123-0d01b680-32bb-11e9-9317-d866e63d2884.png)

**Comment by sean-mcmanus** [comment]
Our extension does not currently provide any build features (the errors are from your compiler and not our C/C++ extension). The c_cpp_properties.json is to configure IntelliSense and is not used during the compilation with gcc.

I do not believe D3D9 is compilable with gcc -- it requires a Microsoft cl.exe compiler, i.e. obtained from a Visual Studio or Visual C++ Build Tools download.

How exactly are you doing "build project with g++"? Do you have a task.json for building?

**Comment by sean-mcmanus** [comment]
Can you try adding something like `"-I D:\\Soft\Microsoft DirectX SDK (June 2010)\\Include"` to your tasks.json command?

**Comment by ghost** [comment]
> Our extension does not currently provide any build features (the errors are from your compiler and not our C/C++ extension). The c_cpp_properties.json is to configure IntelliSense and is not used during the compilation with gcc.

I'm not mean that it's your extension need to build the code itself. g++ do all the work. Please read last part of the original topic carefully: I explictly described that everything works with absolute paths.

> I do not believe D3D9 is compilable with gcc -- it requires a Microsoft cl.exe compiler, i.e. obtained from a Visual Studio or Visual C++ Build Tools download.
> How exactly are you doing "build project with g++"? Do you have a task.json for building?

Actually, documentation is on Microsoft official site: https://code.visualstudio.com/docs/languages/cpp
I simply installed g++, added it to system PATHS and wverything works like a charm for me.

task:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g",
                "src/hardware/main.cpp",
                "-o",
                "dist/app"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        },
        {
            "label": "run",
            "type": "shell",
            "command": "dist\\app",
            "args": [],
            "problemMatcher": []
        }
    ]
}
```

The problem only in this extension, which is don't respect it own `includePath` parameter.

**Comment by sean-mcmanus** [comment]
What is the error you see with our extension? The includePath is used by our IntelliSense process to locate the correct file from `#include` statements to provide error squiggles and other features.

**Comment by ghost** [comment]
@sean-mcmanus Now I understand. Semms like I need to configure g++'s include paths separately.

**Comment by bobbrow** [comment]
This issue appears to have been resolved (add the `-I` paths to your tasks.json). Please reopen if there is any remaining issue.
