### ISSUE TITLE
Debugging problems with miDebuggerPath

### ISSUE THREAD

**Issue by MMROmbo** [microsoft/vscode-cpptools#3188]
Type: Debugger
I'm actually having problems with debugger

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows 10 Home
- VS Code Version: 1.31.1 User Setup
- C/C++ Extension Version: 0.21.0

- The main problem I think is in the launch.json file, I was trying to figure out why the debug wasn't working and i ended up like this:

    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "C:\\Users\\Gabriel\\.vscode\\extensions\\ms-vscode.cpptools-0.21.0\\bin\\Microsoft.VSCode.CPP.Extension.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Users\\Gabriel\\.vscode\\extensions\\ms-vscode.cpptools-0.21.0\\debugAdapters\\bin\\WindowsDebugLauncher.exe",
            "logging": 
                { 
                    "engineLogging": true,
                     "trace": true,
                     "traceResponse": true 
                },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

this is my launch.json file. 
The error message says:"Unable to start debugging. Unable to establish a connection to GDB the following message was written to stderr: 
One or more required values are missing.
See Output Window for more details.

I actually don't know what to do.

**Comment by WardenGnaw** [comment]
WindowsDebugLauncher is used the VSCode integrated terminal. 

miDebuggerPath should be the path to gdb. Usually its /usr/bin/gdb on Linux or gdb.exe if you install MinGW or Cygwin.
