### ISSUE TITLE
No definitions found on C code

### ISSUE THREAD

**Issue by izzygold** [microsoft/vscode-cpptools#3190]
**Type: LanguageService**

**Describe the bug**
- OS and Version: 
windows 10
Version	10.0.17763 Build 17763

- VS Code Version:
1.3.1 user setup
- C/C++ Extension Version:
0.21.0

- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I added my workspace to visual code, from a virtual driver that was mounted using winSshFs.
This code (on a different machine) works well with visual code. 

I get "no definitions found" no matter on what I click, functions, variables, anything.

**To Reproduce**
Use any code what-so-ever and press F12.

{
    "configurations": [
        {
            "name": "Win32",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}/utils"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c89",
            "intelliSenseMode": "clang-x64"  
        }
    ],
    "version": 4
}

**Expected behavior**
VS should show definitons

**Comment by sean-mcmanus** [comment]
This appears to be issue https://github.com/Microsoft/vscode-cpptools/issues/1046 , i.e. it's not a supported scenario yet. Can you upvote that issue?

**Comment by izzygold** [comment]
Using these configurations solved the issue:

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}",
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
            ],
            "windowsSdkVersion": "01.1.11111.1",
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
Okay, that is good to hear. The compilerPath is probably the most important, because we use it to set the compiler defines and includes.
