### ISSUE TITLE
The debugger hangs after reaching "cout"

### ISSUE THREAD

**Issue by WEGFan** [microsoft/vscode-cpptools#3193]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 1709 (16299.192)
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them): None

**To Reproduce**
Code sample
```cpp
#include <iostream>
#include <cstdio>
using namespace std;

int main()
{
    cout << 123 << endl;
    printf("456");
    return 0;
}
```
launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "logging": {
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            },
            "miDebuggerPath": "D:\\Program Files\\Dev-Cpp\\MinGW64\\bin\\gdb.exe",
            "preLaunchTask": "build",
            "setupCommands": [{
                "description": "Enable pretty-printing for gdb",
                "text": "-enable-pretty-printing",
                "ignoreFailures": true
            }]
        }
    ]
}
```
1. Add breakpoint on `cout << 123 << endl;`
2. Start debugging
3. Click `Step Over`, outputs `123` correctly.
4. Click `Step Over` again, the background of the line becomes green.
5. Click `Step Over` again, the debugger hangs and doesn't execute the next line (which supposed to output `456`)

**Additional context**
Debug console log: https://www.pastery.net/hhvhww/

**Comment by WardenGnaw** [comment]
I believe this is an issue with MinGW GNU gdb (GDB) 7.8.1. 

If possible can you see if this repros on GDB 7.6.1?

**Comment by WEGFan** [comment]
In gdb 7.6.1 there is no issue, thanks!
But I'm using 7.8.1 before and the problem didn't occur.
