### ISSUE TITLE
#include completion doesn't respect the files.exclude setting

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3195]
It will show excluded folders in the results, and then when "/" is used it will recurse one level and show the children. It repros with recursive and non-recursive includes, but with recursive includes it follows the non-recursive code path (i.e. recursion only happens when "/" is typed).

I'm not sure how important this is to fix, i.e. no users have complained yet. Up vote this if it's important to you.

**Comment by ThadHouse** [comment]
I've noticed that with API provided headers that sometimes the project root folder is included as well, not just the headers included via the provider. Not sure if this is related or not. It's kind of random if it does or not.

**Comment by bobbrow** [comment]
Closing stale issue with few upvotes.
