### ISSUE TITLE
indent 5 spaces rather than 4

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-cpptools#3198]
macOS, VSCode 1.31.1, C/C++ extension 0.21.0

settings:
```json
"C_Cpp.clang_format_style": "{ BasedOnStyle: Chromium, IndentWidth: 4, ColumnLimit: 0 }"
```

steps to reproduce:
1. open main.c
2. put cursor after `int main() {`
3. enter
4. you can find there is 5 spaces, 4 is expected.

[main.c.zip](https://github.com/Microsoft/vscode-cpptools/files/2888013/main.c.zip)

**Comment by sean-mcmanus** [comment]
This is caused by the VS Code editor.detectIndentation setting -- change that to false to fix this.

**Comment by kzhui125** [comment]
@sean-mcmanus thanks, it works.
