### ISSUE TITLE
Support additional extensions in "Switch Header/Source"

### ISSUE THREAD

**Issue by mak-ableton** [microsoft/vscode-cpptools#3199]
**Type: LanguageService**

It would be great if the "Switch Header/Source" command could support additional (ideally user-configurable) extensions, such as `.ipp` and `.mm`.

**Comment by sean-mcmanus** [comment]
Yeah, this has been on our TODO list for the past 2 years. We could probably look at files.associations for the header files to use (not sure if we would need another setting to differentiate which are headers versus source extensions). Our extension already treats ".mm" as a C++ file in other cases, but not for the switch header/source...we could also update our hardcoded list to include these other extensions.
