### ISSUE TITLE
Ctrl + left click(Mouse) is not working.

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-cpptools#320]
_From @mong87suk on September 22, 2016 17:9_

- VSCode Version: 1.5.0
- OS Version: Raspbian GNU/Linux 8.0 (jessie)

Steps to Reproduce:
I worte follwoing codes in _test.c_ file 

```
1  #include <stdio.h>
2
3  int test(void) {
4
5    }
6
7    int main (void) {
8     printf("Hello\n");
9     test();
10   int a = 3;
11   return 0;
}
```

I did  _Ctrl + left click(Mouse)_  at the 9 line  but the cursor hasn't been moved to the 3 line.
I didn't know why it wasn't moved.
Could you fix this issue?

Thank you.

_Copied from original issue: Microsoft/vscode#12464_

**Comment by chrmarti** [comment]
- Do you have the C/C++ extension installed?
- Does 'test' change its color and get an underline when you ctrl + hover?

**Comment by chrmarti** [comment]
_From @mong87suk on September 23, 2016 2:26_

Hi @chrmarti 
Thank you for your support.
- Do you have the C/C++ extension installed?
  Yes, I have. I have installed it.  the version is 0.9.1
- Does 'test' change its color and get an underline when you ctrl + hover?
  No, the color was not changed when I did _ctrl + hover_

Thanks

**Comment by chrmarti** [comment]
@mong87suk What does the Output panel show in the C/C++ channel?

**Comment by chrmarti** [comment]
_From @mong87suk on September 24, 2016 13:9_

Hello @chrmarti 
Thank you for your support.
I didn't know exactly what I have to show you.
Could you explain more detail?
I posted the picture which is captured on vs code.

![screen](https://cloud.githubusercontent.com/assets/6234666/18808678/8d005d16-82a3-11e6-9625-45975ac602d8.png)

Thank you

**Comment by chrmarti** [comment]
You can open the Output panel through the menu View > Output. There used to be a C/C++ channel in its top-right channel switcher, though it doesn't show for me currently, it might have been removed, could you check in your set up?

Another thing to try is to run Go to Definition from the context menu on line 9. Does that position the cursor on line 3?

**Comment by chrmarti** [comment]
_From @mong87suk on September 27, 2016 0:45_

Hello @chrmarti 
Thank you for your support.
I checked the _Output_ panel.  it is as follows.
![2016-09-27-091354_1225x715_scrot](https://cloud.githubusercontent.com/assets/6234666/18856146/60877ea8-8493-11e6-8a64-5fbfb01a2c21.png)

When I selected _C/Cpp Languase Server_ on _OUTPUT_,  The error happended.the error message is as follows.
**Connection to server is erroring. Shutting down server**
I don't know why this error happens. 
Dose this error cause that cursor is not moved?
Could you explain it?

I checked the _Default Keyboard Shortcuts_ to find _Go to Definition_ key.
it's _F12_  so I tried _F12 key_ : _'Go to Definition'_  on line 9 but cursor has not been moved to line 3.

![2016-09-27-091443_1225x715_scrot](https://cloud.githubusercontent.com/assets/6234666/18856367/11bddb1c-8495-11e6-8c23-88ff27087498.png)

Thank you

**Comment by chrmarti** [comment]
Seems to be a problem with the extension.

@waderyan could you move this issue over to Microsoft/vscode-cpptools (or let me know how to do that myself)?

**Comment by sean-mcmanus** [comment]
We don't support 32-bit Linux OS's or Linux OS's that don't have glibc 2.18 or newer.

**Comment by bobbrow** [comment]
We're tracking 32-bit Linux support with issue #424
