### ISSUE TITLE
When debug it comes out Unable to open 'iofflush.c'

### ISSUE THREAD

**Issue by Eileen0** [microsoft/vscode-cpptools#3201]
I am working on the Ubuntu 14.04, VS Code 1.30.2 . When I am debugging the code, it comes out the problem that 

Unable to open 'iofflush.c': File not found (file:///build/eglibc-oGUzwX/eglibc-2.19/libio/iofflush.c).

when I click on the create file button, it shows that 

Permission denied writing to file (file:///build/eglibc-oGUzwX/eglibc-2.19/libio/iofflush.c)

Even if I raised the authority as a root user, the debugger cannot be invoked.

The following is the screenshots
![image](https://user-images.githubusercontent.com/45990858/53220226-87657880-36b7-11e9-92ff-5579397941b3.png)
![image](https://user-images.githubusercontent.com/45990858/53220236-91877700-36b7-11e9-9b01-552ba464a5cd.png)
However, it seems that if I delete all the related flush statements，this problem cannot happen. But I need these statements, so can anyone help me out of this?
The launch.json is shown as follows:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bin/xxx",
            "args": [./bin/xxx 3 54321],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "preLaunchTask": "build",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

**Comment by WardenGnaw** [comment]
This is the same issue as https://github.com/Microsoft/vscode-cpptools/issues/2762.

It is trying to open a library source that does not exist in your path.
