### ISSUE TITLE
How do you programmatically control plug-in enable and disable

### ISSUE THREAD

**Issue by zhouhangzooo** [microsoft/vscode-cpptools#3202]
How do you programmatically control plug-in enable and disable？

**Comment by sean-mcmanus** [comment]
What do you mean exactly? What programming API are you intending to use and what feature are you trying to disable/enable? We have an intelliSenseEngine "Disabled" setting which will disable the language server.

**Comment by bobbrow** [comment]
In the terminal you can run `code --disable-extension <extension-id>` to disable extensions and `code --install-extension <extension-id>` to install extensions.

A full list of CLI commands can be found by running `code --help`
