### ISSUE TITLE
Unable to start the C/C++ language server on Raspberry Pi 3 b+ running Raspbian Stretch.

### ISSUE THREAD

**Issue by tanvit8250** [Microsoft/vscode-cpptools#3203]
On Raspberry Pi 3 b+ running  Raspbian Stretch i am getting this message.

Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at /home/pi/.vscode/extensions/ms-vscode.cpptools-0.21.0/bin/Microsoft.VSCode.CPP.Extension.linux

**Comment by sean-mcmanus** [comment]
Our binary is compiled for x86 and x64 targets and not arm targets. We're tracking this with https://github.com/Microsoft/vscode-cpptools/issues/429 . Can you upvote that issue?
