### ISSUE TITLE
[windows insiders]the extension always notify me to update to new version 0.22.0

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode-cpptools#3206]
the notification is:

> The C/C++ Extension has been updated to version 0.22.0-insiders. Please reload the window for the changes to take effect.

so I **reload again and again**.But it still show up the notification!

**Comment by sean-mcmanus** [comment]
What version of VS Code do you have? This might be a bug if your version of VS Code is too old.

**Comment by JoeyRxy** [comment]
the newest except the insider version.
now I solve the problem by disabling the extension's notification.
but I now have a secondary problem:the gdb debugger doesn't work on win10
after I configure those .JSON files while it works on Linux(Ubuntu).
when I click the dubug button,I can see the output from task.json in the
terminalm.but then the whole thing just stop.


Sean McManus <notifications@github.com> 于 2019年2月26日周二 上午3:38写道：

**Comment by aparks5** [comment]
happening to me on insiders 1.31.1

"The C/C++ Extension has been updated to version 0.22.0-insiders2. Please reload the window for the changes to take effect."

^ never goes away 

version:

Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.4.0-142-generic

**Comment by bobbrow** [comment]
I'm seeing this too.  It seems that VSCode is not uninstalling the previous version, and it keeps loading the older version of the extension.  Removing the older version of the extension manually fixed the problem for me.  We'll investigate why this is suddenly broken.

**Comment by sean-mcmanus** [comment]
1. We weren't waiting for the install to finish before showing the reload prompt.
2. We weren't checking the exit code before showing the reload prompt.
3. We weren't logging any error if the install failed (we just sent telemetry).

**Comment by JoeyRxy** [comment]
OK,thank you all!
unfortunately I have reset my computer for other reason so that the problem disappear

**Comment by sean-mcmanus** [comment]
We made fixes for this with 0.22.0-insiders3 that should prevent the incorrect extra reload/installation prompts.
