### ISSUE TITLE
No intellisense with CMake (Clang project)

### ISSUE THREAD

**Issue by SoftwareApe** [microsoft/vscode-cpptools#3209]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
I'm trying to build a tool with libTooling in clang. If you follow the guide you add your project under \<LLVM-PROJECT\>/clang-tools-extra/\<MYPROJECT\>

No intellisense, go to header, etc. works.

Sometimes going to the header throws an error like:
Couldn't find "\<LLVM-PROJECT\>/clang/include/clang/Frontend/FrontendActions.h"

I tried adding the relative or even absolute include paths in the workspace settings or in c_cpp_properties.json. It still doesn't find the files that are there. Thinking there are some additional folders in between I never gave to it.

My assumption is it finds CMake's compile_commands.json and gets some wrong info out of it and ignores manual include paths. The compile_commands.json is not in the project workspace.

It would be nice if we could disable any kind of automatic search for the configuration (e.g. compile_commands.json), because Intellisense works perfectly on projects without any other configuration information if I use the top workspace folder.

**To Reproduce**
Probably fails on other CMake projects as well, but you can build Clang and use the libTooling example (that's exactly my code right now).
https://clang.llvm.org/docs/LibASTMatchersTutorial.html

**Expected behavior**
No intellisense.

**Additional context**
C/C++ doesn't print anything to output window. So apparently it thinks it's working.

**Comment by sean-mcmanus** [comment]
The message "Couldn't find ..." doesn't come from our extension. Are you using some other extensions that could interfere? What is your c_cpp_properties.json "compileCommands" property set to? If you [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) you can see more info about what include paths are being used.

**Comment by bobbrow** [comment]
Closing stale issue marked "more info needed".  If you are still having issue with the extension, please reopen and provide the information requested.  Thank you!
