### ISSUE TITLE
Substitute macros in miDebuggerPath 

### ISSUE THREAD

**Issue by ilg-ul** [microsoft/vscode-cpptools#3210]
Type: Debugger
This is an enhancement proposal.

- OS and Version: macOS 10.13.6
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them): none

---
For various reasons, I currently have gdb installed in a custom location, in my home folder.

If I try to define:

```
      "osx": {
        "miDebuggerPath": "${HOME}/opt/homebrew/xbb/bin/gdb"
      }
 ```

... the debug session fails with 'Unable to start debugging. The value of miDebuggerPath is invalid'.

If I rewrite the definition to an absolute path: 

```
      "osx": {
        "miDebuggerPath": "/Users/ilg/opt/homebrew/xbb/bin/gdb"
      }
```

... the debugger starts. 

Could you consider expanding macros in the `miDebuggerPath` property? And possibly in all other paths properties?

Thank you, Liviu

**Comment by WardenGnaw** [comment]
We do not expand variable references in the launch.json. VS Code does the variable replacement before passing it to the extension. 

I believe you want to use ```$(env:HOME}``` from https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables

**Comment by ilg-ul** [comment]
Hi Andrew, 

Thank you for your feedback, I checked and indeed, when using the correct syntax, the substitution is performed.
