### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by germinolegrand** [microsoft/vscode-cpptools#3213]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.21.0`
- OS Version: `Linux x64 4.9.0-8-amd64`
- VSCode version: `1.31.1`

[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/2899824/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by WardenGnaw** [comment]
From the .cpuprofile, it is taking a long time to load a module. VS Code's solution is https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#code-loading

**Comment by sean-mcmanus** [comment]
@WardenGnaw So we should be using WebPack? Do we know how severe of an issue this is, i.e. how much of a benefit would be gained?

**Comment by WardenGnaw** [comment]
@sean-mcmanus We would have to do profiling on WebPacked code vs non-WebPacked code and see what the improvement is.

**Comment by germinolegrand** [comment]
Same notification while loading the same code folder (which is quite huge, tens of thousands of files, that might be of importance ?).

[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/2911569/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

**Comment by WardenGnaw** [comment]
Time is still mostly spent doing module loads. Profiler is saying it is taking 2500 ms.

**Comment by philkuz** [comment]
I noticed in the messages that @sean-mcmanus is leaving on duplicate issues, there's apparently a fix to this issue in the upcoming release. Is there a branch where this is currently located? 

Thanks!

**Comment by WardenGnaw** [comment]
@philkuz The branch would be https://github.com/Microsoft/vscode-cpptools/pull/3411

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.23.0-insiders2: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.23.0-insiders2

**Comment by larshb** [comment]
Version 1.40.2

![image](https://user-images.githubusercontent.com/8710787/70141907-524f7300-1698-11ea-9012-98d5e3e1b047.png)

**Comment by sean-mcmanus** [comment]
@larshb "high CPU load" is a general symptom with many possible causes -- can you open a new issue with more repro info? Are you able to look at the logs or call stacks to determine what processing is occurring?
