### ISSUE TITLE
File not found for headers in cpp files

### ISSUE THREAD

**Issue by ES5017** [microsoft/vscode-cpptools#3216]
Even though I can peek definition of the header files in cpp files, it underlines them in red and gives the error 'file not found'. If I change it from, say, include "test.hpp" to include "../../include/dir/test.hpp" it will work. The c_cpp_properties is the default "${workspaceFolder}/**"

- OS and Version: MacOS Mojave
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21.0

<img width="351" alt="screenshot 2019-02-26 at 00 24 09" src="https://user-images.githubusercontent.com/44258515/53378288-2363de00-395d-11e9-8b7b-9b7b0394722d.png">

**Comment by sean-mcmanus** [comment]
That message is not from our extension. Can you disable the other extension you have installed that is causing the problem?

**Comment by ES5017** [comment]
OK, I disabled the C/C++ Clang Command Adapter by Yasuaki MITANI and the red line error went away, now I'm getting a green underline error saying include errors detected, please update your include path with the lighbulb. Is there any way I don't have to do this, as there will be many sub folders in the include folder.

**Comment by sean-mcmanus** [comment]
If your includePath has `"**"` at the end it should try to automatically include the necessary paths. If you [enable debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) then you should be able to see the include paths we end up using when a C/C++ file is opened.

If the include files are system files then you may need to set your compilerPath.

**Comment by ES5017** [comment]
It seems to be include the system files. Wha should the compilerPath be set to?

**Comment by sean-mcmanus** [comment]
Something like "/usr/bin/clang". It depends on what you're using to compile. Usually, we should prepopulate the field if we detect a compiler on your machine.

**Comment by ES5017** [comment]
it already is usr/bin/clang. maybe i was looking for the wrong this with the including the system files..

**Comment by sean-mcmanus** [comment]
So what system file is it not able to find still?

**Comment by ES5017** [comment]
Sorry, I think I misunderstood. It only shows the error for hpp files I have written in the workspace.

**Comment by sean-mcmanus** [comment]
Can you check your debug logs and see if the folder that contains the hpp file is getting set?

It should show
```
sending compilation args for
  include: …
```

**Comment by ES5017** [comment]
Yes, just checked. One of the includes in the list has the path to the hpp just fine

**Comment by ES5017** [comment]
But the problem still happens...

**Comment by sean-mcmanus** [comment]
Can you give more detail or provide a sample repro project?

**Comment by ES5017** [comment]
I can give all the detail requested. A sample project would simply be a blank hpp file trying to be included in a blank cpp file, but the two are in different directories.

**Comment by sean-mcmanus** [comment]
That works for me. Do you see the folder with the header being used in the debug output? It should be auto-added if you're using "${workspaceFolder}/**". If you use "${workspaceFolder}/subDir" does that work? (where subdir has the header that you're including. I assume everything is under the 1 workspace folder, and there are not multiple workspace folder, right?

**Comment by ES5017** [comment]
yes, "${workspaceFolder}/subDir" works, as added when i click the lightbulb. however I don't want to do it manually every time. I have one workspace, but it should be working for multiple folders. In the debug output, I see the folder with the header being used, in fact twice. That's what is so weird, it still gives the error, and doesn't seem to be auto added.

**Comment by sean-mcmanus** [comment]
By "multiple folders" do you mean multiple "workspace folders" or are these ordinary folders that exist on your file system? It sounds like the recursive includes "**" is not working for you. One thing to try is doing a "Reset IntelliSense Database" command in case those directories got added to our "non-existent" list somehow.

**Comment by McDic** [comment]
Hello @sean-mcmanus, can you help me in this [question?](https://github.com/microsoft/vscode-cpptools/issues/2250#issuecomment-518729094) Thanks in advance.

**Comment by bobbrow** [comment]
This issue hasn't had any traffic in a long time.  If you are still experiencing problems, can you please open a new issue with steps we can follow to reproduce the problem.  Thank you!
