### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3217]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.21.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/atreyasinha/ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by WardenGnaw** [comment]
File is not attached.

**Comment by bobbrow** [comment]
Consolidating performance reports from VS Code.  Tracking with #2991.
