### ISSUE TITLE
Visual Studio Code wont work 

### ISSUE THREAD

**Issue by Jman2275** [microsoft/vscode-cpptools#3223]
- OS and Version: not sure
- VS Code Version: not sure
C/C++ Extension Version: 0.21.0
- Other extensions: code runner by jun han
- A clear and concise description of what the bug is.
I am trying to run a simple code and every time i ru any code i get [Done] exited with code=-4058 in 0.003 seconds or something along the lines

**Comment by sean-mcmanus** [comment]
That message is from the Code Runner extension and not our C/C++ extension. Please file an issue at https://github.com/formulahendry/vscode-code-runner/issues .
