### ISSUE TITLE
msvc-x64 intellisense shouldn't try to use definitions from GCC

### ISSUE THREAD

**Issue by 0xabu** [microsoft/vscode-cpptools#3224]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows build 18342.19h1_release
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them): none
- A clear and concise description of what the bug is.

I had a simple C++ project configured for "msvc-x64" IntelliSense that didn't accept builtin types such as __int64.

I finally tracked this down to an intersection of the following:
 * If a project's `c_cpp_properties.json` doesn't specify any `compilerPath` setting, then the default is used.
   * I do not have `C_Cpp.default.compilerPath` configured in my VS Code preferences.
   * I don't have any Windows compilers installed in the usual places.
   * I do have WSL installed. Consequently, per [the builtin WSL support](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md), the extension seems to have been defaulting to `/usr/bin/gcc`.
 * Having a `compilerPath` of `/usr/bin/gcc` but an `intelliSenseMode` of `msvc-x64` leads to unhappiness.

After discovering [this document](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Customizing%20Default%20Settings.md#system-include-pathdefines-resolution-strategies), I fixed the problem by explicitly setting `compilerPath` to the empty string in `c_cpp_properties.json`. Setting `C_Cpp.default.compilerPath` to the empty string also seems to work for all projects that don't define their own `compilerPath` (and for my use-case is a much safer default).

My suggestion is therefore: when auto-detecting a compiler, you should keep track of the compiler's "flavour" (e.g. gcc, clang, msvc), and prevent the wrong compiler being used by default for a different IntelliSense mode. Alternatively, detect the flavour of compiler, and don't permit the user to specify a different IntelliSense mode at all -- why do they need to be two different settings?

**Comment by sean-mcmanus** [comment]
We originally just had an intelliSenseMode setting and then we added the compilerPath setting in order to get the correct compiler includePath and defines. We're planning to add warning squiggles to our c_cpp_properties.json file when the compilerPath and intelliSenseMode are set inconsistently.

**Comment by 0xabu** [comment]
Sounds good, although I would think you could detect the appropriate intelliSenseMode from running the compiler. If so, why not make it an error to specify intelliSenseMode with a non-empty compilerPath?

**Comment by sean-mcmanus** [comment]
Our current behavior is inconsistent in that some cases the intelliSenseMode overrides the compilerPath, such as if the intelliSenseMode is clang and the compilerPath is "cl.exe, but when the compilerPath is a non-cl.exe compiler the intelliSenseMode of msvc will be ignored. There is internal debate as to whether the compilerPath should override the intelliSenseMode setting or vice versa. I think the warning squiggle would in effect make it an "error" to have inconsistent settings, but it won't "break" people who are relying on the current behavior.

**Comment by sean-mcmanus** [comment]
The original repro appears fixed with 0.23.0 (I'm see it use cl.exe).
