### ISSUE TITLE
Cannot attach docker container for debugging

### ISSUE THREAD

**Issue by adashen** [microsoft/vscode-cpptools#3227]
Type: Debugger

- OS and Version: windows
- VS Code Version: 1.30.0
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
   {
      "name": "C++ Attach in hello_gdb container",
      "type": "cppdbg",
      "request": "attach",
      "program": "/hello.out",
      "processId": "${command:pickRemoteProcess}",
      "pipeTransport": {
          "pipeCwd": "${workspaceRoot}",
          "pipeProgram": "docker",
          "pipeArgs": [
              "exec", 
              "-i", 
              "hello_gdb",
              "sh",
              "-c"
          ],
          "debuggerPath": "/usr/bin/gdb"
      },

1. Build a simple docker container image for cpp project. Start the container.
2. Start the debugger to attach to the process. 
3. See error
Command failed: "docker" "exec" "-i" "hello_gdb" "sh" "-c" 'sh -c 'uname && if [ $(uname) = "Linux" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) = "Darwin" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi''
$(uname) was unexpected at this time.

**Additional context**
It seems the process picker script has some problem. I tried to use the remote process picker from csharp extension (use cshap debugger attach configuration), it could list the process. And I think the problem is instead of using "sh -c" to run the script, it should be "sh -s" instead.

**Comment by pieandcakes** [comment]
Can you provide which container type you are using or a `dockerfile` where we can attempt your scenario?

**Comment by WardenGnaw** [comment]
@pieandcakes The error is the quoting issue I fixed in https://github.com/Microsoft/vscode-cpptools/pull/3181. We have not done a release yet with the fix.

**Comment by WardenGnaw** [comment]
This is fixed in our [0.22.0-insiders2](https://github.com/Microsoft/vscode-cpptools/releases/tag/0.22.0-insiders2).

**Comment by adashen** [comment]
The issue has not been fixed and could be reproduced in windows 10

**Comment by adashen** [comment]
new issue created at https://github.com/Microsoft/vscode-cpptools/issues/3389
