### ISSUE TITLE
IntelliSense behaving incorrectly when files reopened with different casing

### ISSUE THREAD

**Issue by dwilliamson** [microsoft/vscode-cpptools#3229]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Microsoft Windows 10 Pro 10.0.17134 Build 17134
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.22.0 Insiders
- Other extensions you installed (and if the issue persists after disabling them):
  * Go 0.9.2
  * Output Colorizer 0.1.2
  * Perforce for VS Code 3.1.0
  * Terraform 1.3.7
  * **DISABLING these extensions has no effect**

**Description**
After a short term iterating on C++ code (maybe, 10 minutes) VSCode no longer highlights any errors. Any errors highlighted previously stay in perpetuity.

The output window for C/C++ shows that it's still responding to text inputs, e.g:

```
textDocument/hover
sending 2 changes to server
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/hover
sending 41 changes to server
cpptools/textEditorSelectionChange
textDocument/hover
$/setTraceNotification
$/setTraceNotification
$/setTraceNotification
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/didSave
  tag parsing file: FILE.CPP
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didSave
  tag parsing file: FILE.CPP
Database safe to open
```

Reloading the window restores functioning intellisense.

**To Reproduce**
Iterate on C++ code for any sufficiently large project.

**Expected behavior**
Intellisense should respond to any errors introduced in code.

**Screenshots**
![image](https://user-images.githubusercontent.com/1532903/53639843-5094e280-3c22-11e9-8290-eed9c601b400.png)

Above: Old error from variable that didn't exist before remains. Intellisense not responding the the garbage `lslsl` added, even after saving the file.

**Additional context**
`C_Cpp.loggingLevel` is set to `Debug`.

**Comment by dwilliamson** [comment]
Addendum: intellisense seems to be "sticky" right now, as in; if I fix an error the squiggly highlights don't disappear for an indeterminate amount of time.

**Comment by dwilliamson** [comment]
One thing I *have* noticed... sometimes my `Problems` window picks up odd errors in other TUs and for some reason gives them their lower-case path. Pressing F8 opens this lower-case version while the correct-case version is still open also (VSCode bug for this open for many years now). Anyway, it seems to take down the server. Log here:


```
cpptools/textEditorSelectionChange
sending 1 changes to server
textDocument/didSave
  tag parsing file: C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT\GAME\PARTPROCESSOR.CPP
Checking for syntax errors: file:///c%3A/dev/Celtoys/Star/src/CppClient/Game/PartProcessor.cpp
queue_update_intellisense for files in tu of: C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT\GAME\PARTPROCESSOR.CPP
Checking for syntax errors: file:///c%3A/dev/celtoys/star/src/cppclient/game/partprocessor.cpp
queue_update_intellisense for files in tu of: C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT\GAME\PARTPROCESSOR.CPP
textDocument/didChange
sending 1 changes to server
errorSquiggles count: 2
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 2
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 0
Checking for syntax errors: file:///c%3A/dev/celtoys/star/src/cppclient/game/partprocessor.cpp
queue_update_intellisense for files in tu of: C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT\GAME\PARTPROCESSOR.CPP
  tag parsing file: C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT\GAME\PARTPROCESSOR.CPP
errorSquiggles count: 2
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 0
Database safe to open
Checking for syntax errors: file:///c%3A/dev/celtoys/star/src/cppclient/game/partprocessor.cpp
queue_update_intellisense for files in tu of: C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT\GAME\PARTPROCESSOR.CPP
textDocument/hover
errorSquiggles count: 2
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 0
textDocument/documentHighlight
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/didClose
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/hover
sending 3 changes to server
sending 14 changes to server
textDocument/documentHighlight
cpptools/textEditorSelectionChange
textDocument/codeAction
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/hover
IntelliSense client not available, using Tag Parser for go to definition.
Shutting down IntelliSense server: C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT\GAME\PARTPROCESSOR.CPP
sending compilation args for C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT\GAME\PARTPROCESSOR.CPP
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\VC\TOOLS\MSVC\14.15.26726\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.16299.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.16299.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.16299.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.16299.0\WINRT
  include: C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT
  include: C:\DEV\CELTOYS\STAR\EXTERN\CLREFLECT\RELEASE\INC
  define: _DEBUG
  define: UNICODE
  define: _UNICODE
  define: CLCPP_SIZE_TYPE=size_t
  define: CLCPP_SIZE_TYPE_HEX_FORMAT="lX"
  stdver: --ms_c++latest
  intelliSenseMode: msvc
Closing the communication channel.
textDocument/documentHighlight
cpptools/textEditorSelectionChange
$/cancelRequest
textDocument/codeAction
cpptools/textEditorSelectionChange
textDocument/codeAction
cpptools/textEditorSelectionChange
textDocument/documentHighlight
cpptools/textEditorSelectionChange
textDocument/codeAction
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didSave
  tag parsing file: C:\DEV\CELTOYS\STAR\SRC\CPPCLIENT\GAME\PARTPROCESSOR.CPP
textDocument/codeAction
cpptools/textEditorSelectionChange
textDocument/codeAction
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight
sending 2 changes to server
cpptools/textEditorSelectionChange
textDocument/codeAction
Database safe to open
```

**Comment by bobbrow** [comment]
Thank you for the detailed report.  I think you're on to something with the casing.  I see a potential for the language server to mess this up.  We'll investigate more.

**Comment by dwilliamson** [comment]
With VSCode 1.32.3 and vscode-cpptools 0.22.1 this still seems to be an issue. It's not as bad as before but it's generating a steady stream of crash dumps in my `.vscode\ipch` directory.

**Comment by dwilliamson** [comment]
In terms of case sensitivity I did notice from the thread [here](https://github.com/Microsoft/vscode/issues/12448) that using `/FC` on `cl` emits lower-case filenames and this was causing my Problems window and build output to flood with alternate-case filenames.

As I control my own build system I've changed it to scan for filenames in the output and replace with the correct path. I will report back if the crashing still occurs with correct casing.

**Comment by dwilliamson** [comment]
That doesn't seem to have helped: it's still crashing every few minutes. However, intellisense is always responding now even after crashes, so that's a good thing.

I no longer think this issue is representative of the latest 
behaviour. I've added an animation below to demonstrate...

![problems](https://user-images.githubusercontent.com/1532903/55168898-a00bf700-516b-11e9-992b-df9b45c406e1.gif)

This may not even be a cpptools issue.

**Comment by bobbrow** [comment]
Those are not crashes. That's the IntelliSense cache which speeds up the IntelliSense engine.

We haven't released a mitigation for the original bug in this issue yet.

Are the squiggles in your gif coming from the build? I believe they remain until you attempt to build again. Our extension doesn't control this.

**Comment by dwilliamson** [comment]
Good to know I'm misdiagnosing crashes: looking at my logs there is now only one instance of server shutdown, whereas it was happening every few minutes with previous builds. I incorrectly mapped this behaviour to the creation of these new files.

The squigglies are coming from the build but the behaviour is what I'd expect it to be in other files, which is: they disappear as I update and fix the text.

I'll grep VSCode issues to see if I can find anything live.

**Comment by sean-mcmanus** [comment]
0.24.0-insiders shows a warning if files with different casing are opened (with IntelliSense disabled in the 2nd file), available by setting "C_Cpp.updateChannel" to "Insiders").
