### ISSUE TITLE
Quick open doesn't really work

### ISSUE THREAD

**Issue by fr43nk** [microsoft/vscode-cpptools#3230]
**Type: LanguageService**

- OS and Version: Win7
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.22.0-insiders

I have a large code base located on a network drive (smb connection)
My workspace file has some folders set up like follows:
```
{
	"folders": [
		{
			"path": "y:\\base\\path1"
		},
		{
			"path": "y:\\base\\path2"
		},
		{
			"path": "y:\\base\\path3"
		},
		{
			"path": "y:\\base\\path4"
		}
	],
```

The problem is: If I hit Ctrl+P (quick open) and type in a file name, the dialog doesn't find anything.
Only after opening this file I can use the shortcut.
My expectation was, that some kind of tree walker iterates through the folders and builds a list of existing files.
Am I wrong?

**Comment by bobbrow** [comment]
Our extension doesn't provide this service.  This belongs to the VS Code team.  I'll move it to their repository.
