### ISSUE TITLE
Creating configuration for dump file debugging requries "program" and "cwd"

### ISSUE THREAD

**Issue by mmoderau** [microsoft/vscode-cpptools#3232]
Type: Debugger

- OS and Version: Windows 10 Enterprise 1073 (build 15063.1631)
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21.0

**To Reproduce**
When creating a launch configuration for opening a dump file (using `"dumpPath"` ), I need to also provide `"program"` and `"cwd"` attributes, because the `"launch"` configuration type requires it.

It is not clear, what values should these parameters have in case of dump debugging.

In my case setting `"program"` to *"dummy"* and `"cwd"` to *""* works.

Dump debugging should not require usage of dummy attribute values.

**Comment by WardenGnaw** [comment]
We have a backlog on this to clean up the launch.json scenario, will also include this as part of removing unnecessary values in the launch.json for certain scenarios.
