### ISSUE TITLE
the code Im making doesnt exist?

### ISSUE THREAD

**Issue by LeonelL1** [microsoft/vscode-cpptools#3233]
Im in vs code and Im trying to make a basic snake game but when i try to run it, it says the file im working on doesn't exist as a whole. it says "clang: error: no such file or directory: 'games'". If games is the name of the file, then what is going on?

**Comment by sean-mcmanus** [comment]
This doesn't appear to be a bug with our C/C++ extension. It sounds like your clang build tasks isn't able to find "games".
