### ISSUE TITLE
How to configure VS Code on Windows to run 'make' in bash integrated terminal?

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#324]
I am running VS Code 1.6 on Windows and have configured the integrated terminal to be bash:

`"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",`

I want to build my C++ project using 'make' running in WSL. So I defined a task:

```
{
    "version": "0.1.0",
    "command": "make",
    "isShellCommand": true,
    "args": [""],
    "showOutput": "always"
}
```

How can I configure that task to run in WSL?

How can I set the directory in which make should run? (not the root directory of the folder opened in Code, but a subfolder of it).

**Comment by pieandcakes** [comment]
@DavidA2014  Tasks are part of VSCode and I don't know enough to configure the task to run in WSL. That might be something you can ask on the [VSCode ](https://github.com/Microsoft/VSCode/Issues) page.

To set the directory in the task, you can add:
`"options": {
        "cwd": "/path/where/you/want/to/be"
    }`

**Comment by daldr-ntml** [comment]
Thanks for your answer.
