### ISSUE TITLE
Question - How do I prevent compile_commands.json from overwriting the default include paths?

### ISSUE THREAD

**Issue by Guy1524** [microsoft/vscode-cpptools#3248]
Type: Question

- OS and Version: Arch Linux
- VS Code Version: 1.31.0
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them): Gitlens, it does

Hello, I am trying to use intellisense from this plugin with the wine codebase.  I have generated compile_commands.json using [Bear](https://github.com/rizsotto/Bear), and added the path in my configuration.  The problem is, compile_commands.json only specifies the *extra* include paths, not the default ones such as /usr/include.  Because of this, headers from outside wine source aren't found, and the extension reverts to the tag parser.

Debug output from extension: https://paste.ubuntu.com/p/WgbMgMTKVH/

c_cpp_properties.json: https://paste.ubuntu.com/p/wW2QjMPtQ8/

Example compile command from compile_commands.json, since the whole thing is 4.7 MB : https://paste.ubuntu.com/p/xmbqfPFXjN/

**Comment by bobbrow** [comment]
It seems the compiler listed in the compile commands file does not include the full path.  Setting `compilerPath` to `/usr/bin/gcc` in your c_cpp_properties.json file would likely fix it.

**Comment by Guy1524** [comment]
Yes, that fixed it, thanks!
