### ISSUE TITLE
Python source file names capitalization not recognized by ptvsd 

### ISSUE THREAD

**Issue by jmagosta** [microsoft/vscode-cpptools#3250]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:
Windows 10 enterprise 1809
- VS Code Version: 
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
- C/C++ Extension Version:  NA
- Other extensions you installed (and if the issue persists after disabling them):
C# 1.1.7.1
Python 2019.2.5433
SQL Server 1.4.0
Vim 1.1.0

- A clear and concise description of what the bug is.
Error is similar to Issue #1113
Py files with "camel case" names run properly without debugging, but will not stop at breakpoints when run in the debugger.  Error is
"pydev debugger: warning: trying to add breakpoint to file that does not exist: c:\users\joagosta\repo\cloud\rewrite\debugfailfile.py (will have no effect)"

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
Code sample:
debugFailFile.py
import os, sys
print("hello")

Launch file is the default:
"Python: Current File (Integrated Terminal)", configuration"

Set breakpoint then run debugger from the Debug menu (F5)
**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment]
This is the C/C++ VS Code extension. If our extension is not enabled, it would not be our issue. 

If you believe this is a VS Code issue, please post it at https://github.com/Microsoft/vscode/issues
If it is a Python extension issue, please post at https://github.com/Microsoft/vscode-python/issues
