### ISSUE TITLE
0.22.0-insiders2: Debugging doesn't work for Windows 32-bit apps

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3258]
1. 0.22.0-insiders or earlier works. 64-bit Windows apps works.
2. I tested debugging with 0.22.0-insiders2 earlier and it worked so there may be something else that may cause it not to repro, but it's possible we only tested with 64-bit apps.

**Comment by dwilliamson** [comment]
Can verify my breakpoints are no longer hitting on 32-bit apps. It worked on 0.22.0-insiders.

**Comment by sean-mcmanus** [comment]
32-bit Windows debugging is fixed with 0.22.0-insiders3.

**Comment by dwilliamson** [comment]
Works for me! Single-stepping also many times faster again (I updated to 1.32.0). Thanks.
