### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by SupinePandora43** [microsoft/vscode-cpptools#3265]
**Type: LanguageService**

How work with C++ Gradle projects?

**Comment by sean-mcmanus** [comment]
I don't know. We don't currently have any special handling for "Gradle".

**Comment by sean-mcmanus** [comment]
There is a Gradle extensions for VS Code, but I don't know how well it works....but that might not be C++ Gradle (looks like some other Gradle language).

**Comment by SupinePandora43** [comment]
Gradle language support - extension for support *.gradle files, such as build.gradle, settings.gradle.

**Comment by bobbrow** [comment]
We aren't planning on adding support for Gradle builds directly in the extension
