### ISSUE TITLE
question regarding tooltip

### ISSUE THREAD

**Issue by kelvinwop** [microsoft/vscode-cpptools#3266]
How do I add a newline in the tooltip comment thing? I tried all the tricks up my sleeve:

![image](https://user-images.githubusercontent.com/30770221/54061816-2a45e880-41c8-11e9-8f52-690527189101.png)

But it said no.

![image](https://user-images.githubusercontent.com/30770221/54061821-32058d00-41c8-11e9-8938-1f9b907f388f.png)

Great job by the way, the extension is getting better by the day!

**Comment by sean-mcmanus** [comment]
We haven't implemented that yet. We're tracking it with https://github.com/Microsoft/vscode-cpptools/issues/2937 .

**Comment by sean-mcmanus** [comment]
0.23.0-insiders has enabled newlines in doc comments.
