### ISSUE TITLE
Intellisense for Linux specific header files on macOS

### ISSUE THREAD

**Issue by joshniec** [microsoft/vscode-cpptools#3269]
**Type: LanguageService**
I'm developing applications for Linux on a macOS laptop and I'd like to include intellisense for Linux specific header files, such as `sys/epoll.h`. I've tried searching high and low on the internet for an answer but haven't been able to find a solution. Obviously I could simple just ignore the warnings given to me in the problems area, but I'd like to see if I can provide intellisense for the Linux header files instead. Is there a way I can provide this information to VSCode on macOS for intellisense?

**Describe the bug** (not really a bug)
- OS and Version: 
macOS 10.14.3
- VS Code Version: 
1.32.1
- C/C++ Extension Version: 
0.21.0
- Other extensions you installed (and if the issue persists after disabling them): 
Quite a few others.. including CMake Tools. But I have tried a fresh install with ONLY the c++ extension enabled. 
- A clear and concise description of what the bug is:
(see above)

**To Reproduce**
1. Be on a mac Laptop
2. Create a new file (cpp)
3. Try to include a header file that is specific to Linux (not available on mac) such as `sys/epoll.h`

Thank you

**Comment by sean-mcmanus** [comment]
Can you set your compilerPath setting to a compiler that is able to compile the sys/epoll.h file?

If that doesn't work, then it sounds like you're hitting https://github.com/Microsoft/vscode-cpptools/issues/1083 , i.e. on Mac our IntelliSense process is using a hard-coded define for __APPLE__, so if any of the system headers does something based on that define, your IntelliSense will be incorrect.

**Comment by joshniec** [comment]
Hi Sean,

Thanks for taking the time to response here.

After reviewing that issue you linked I'm inclined to believe that is the problem I am hitting.  I tried modifying the `compilerPath` setting but still had the same issue. 

I will subscribe to notifications in #1083 and follow the progress there.

Thanks again for the help.
