### ISSUE TITLE
hard to troubleshoot launch failure

### ISSUE THREAD

**Issue by hth313** [microsoft/vscode-cpptools#327]
I can launch gdb, but when I try with another debugger that mimics gdb, it just fails with the following output in the console:

```
E output: {"category":"stderr","output":"\r\n\n","data":null,"type":"output"}
E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/MIEngine/DebuggerAborted","data":{"VS.Diagnostics.Debugger.MIEngine.DebuggerName":"GDB","VS.Diagnostics.Debugger.MIEngine.LastSentCommandName":""},"type":"output"}

 R: {"success":false,"message":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information.","request_seq":2,"command":"launch","body":{"error":{"id":1104,"format":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information.","variables":null}},"running":false,"refs":null,"seq":0,"type":"response"}
C disconnect: {"restart":false}
 R: {"success":true,"message":null,"request_seq":3,"command":"disconnect","body":null,"running":false,"refs":null,"seq":0,"type":"response"}
```

I have successfully used this debugger in Eclipse and Emacs/MI as a replacement for gdb.

The xterm console blinks briefly, then just the above error, which does not tell me much except that it did not work.

Is it possible to see the command line it cooked up?

Does it need some particular output from the debugger to be happy?

**Comment by pieandcakes** [comment]
@hth313 We do additional setup for gdb to map pipes for stdin and stdout so we can read MI. I know for our extension we had to do work also to get lldb to work that was different than what we needed for gdb. 

[MIEngine ](https://github.com/Microsoft/MIEngine) is an open source project that you can download and build and debug if you want to see what is going on with the debugger that you are attempting to use.

**Comment by hth313** [comment]
@pieandcakes  Thanks, I was able to pinpoint the problem by looking at the MIEngine source.

I closed the issue, but you want you to ponder over that it may help to display the actual command line used when it fails to launch, it would have helped in this case.

Anyway, I can launch it now.

**Comment by pieandcakes** [comment]
@hth313 Our error support needs some work to help us quickly tell what is wrong. One step that we made recently was adding logging, but I assume in this instance it would not have helped. 

Glad to see you were able to get it working.
