### ISSUE TITLE
C: function like macro expansion false errors

### ISSUE THREAD

**Issue by KarthikJay** [microsoft/vscode-cpptools#3272]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux Kernel 4.19.24-1 (Manjaro 18.0.3)
- VS Code Version: 1.32.1
- C/C++ Extension Version: 0.22.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): N/A

When vscode's intellisense expands function like macro's it tends to chop off the closing brace and/or semi-colon.
This then gets reported as problem by intellisense and is given red error squiggles.

**To Reproduce**

1. Open a C project w/ function like macro's
2. Use a function like macro
3. Hover over red squiggle to see error and incorrect parse.

**Expected behavior**

Parsing of the popup should be the complete statement.
This should in turn be used by intellisense to determine if there is an error with the statement.

**Screenshots**

Example 1: (Chopped off semi-colon)
![vscode_macro_error_semicolon](https://user-images.githubusercontent.com/14841510/54077043-f4f0d780-4267-11e9-82a1-661ed6c5c84c.png)

Example 2: (Chopped off close parenthesis):
![vscode_macro_error_parens](https://user-images.githubusercontent.com/14841510/54077037-e0acda80-4267-11e9-9247-f4dc009d601f.png)

**Additional context**

The above examples are taken from a linux loadable module and using the following C_cpp_properties.json:
```json
{
    "configurations": [
        {
            "name"       : "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/lib/modules/4.19.24-1-MANJARO/build/include",
                "/usr/lib/modules/4.19.24-1-MANJARO/build/arch/x86/include/asm",
                "/usr/lib/modules/4.19.24-1-MANJARO/build/arch/x86/include",
                "/usr/lib/modules/4.19.24-1-MANJARO/build/arch/x86/include/generated",
                "/usr/lib/modules/4.19.24-1-MANJARO/build/include/uapi"
            ],
            "defines": []
        }
    ],
    "version": 4
}
```

As an aside, is there a way to embed shell commands into the .json file that can be used to evaluate the resultant string
Ex:
```json
"/usr/lib/modules/4.19.24-1-MANJARO/build/include/uapi"
```
Into something like this:
```json
"/usr/lib/modules/$(shell uname -r)/build/include/uapi"
```

**Comment by bobbrow** [comment]
To debug this, we'd need to see the definitions of the `#define`s you are using.  Can you share those?  These look like macros expanding to macros.

For your second question, the paths you reference look like system include paths.  Are you using gcc or clang to compile?  If you are then you should be able to set `compilerPath` instead of manually adding system paths to your `includePath` and you'll get better results (and won't need to embed a shell command either).

**Comment by KarthikJay** [comment]
Sure thing, most of it are macro's found in the Linux kernel but here's an expansion of 1:
Ex:
```C
pr_warn("Bypassed DMI check, the driver may not support your device.\n");
```
relevant #defines:
```C
#define KERN_SOH "\001"
#define KERN_WARNING	KERN_SOH "4"	/* warning conditions */
#define pr_fmt(fmt) KBUILD_MODNAME ": " fmt
#define pr_warning(fmt, ...) \
	printk(KERN_WARNING pr_fmt(fmt), ##__VA_ARGS__)
```

Also, thanks for the tip about the compilerPath, that was the trick I needed.

Edit:
You can disregard example 1, as those are indeed just macro's being expanded all the way through. The issue still persists for example 2 though that do eventually get expanded out into an inline printk function call.

**Comment by bobbrow** [comment]
I'm suspicious of the variadic macro, but I only have a Windows laptop to play around with right now and it doesn't repro on WSL for me.  I'll try again in the office tomorrow.

**Comment by bobbrow** [comment]
I only repro the problem on Windows/Linux when `KBUILD_MODNAME` is undefined (there was no definition provided in your last post).  Can you confirm if that macro is defined somewhere?

**Comment by KarthikJay** [comment]
Yea, after adding in the define to the c_cpp_properties.json file the errors went away.

Sorry about that, I should have read the [documentation](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Customizing%20Default%20Settings.md) better.
After adding in all my compileCommands (or just the defines for now) all the warnings did go away correctly.

I did speak too hastily on my side note though, and can confirm that those paths are not actually system includes by default. Since you can load multiple versions of kernels, the shell command (uname -r) output is necessary. I'm still unable to see a way to embed the output of that shell command within the json file though.

**Comment by bobbrow** [comment]
Thank you for confirming.

To your other point, there is no way to execute a shell command in our properties file.  The best we have right now is support for environment variables.  You can also create a custom environment that inherits the shell environment by using the `"env"` property in `c_cpp_properties.json`:

```json
{
    "env": {
        "kernel_release": "4.19.24-1-MANJARO"
    },
    "configurations": [
        {
            "name"       : "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/lib/modules/${env:kernel_release}/build/include",
                "/usr/lib/modules/${env:kernel_release}/build/arch/x86/include/asm",
                "/usr/lib/modules/${env:kernel_release}/build/arch/x86/include",
                "/usr/lib/modules/${env:kernel_release}/build/arch/x86/include/generated",
                "/usr/lib/modules/${env:kernel_release}/build/include/uapi"
            ],
            "defines": []
        }
    ],
    "version": 4
}
```

**Comment by bobbrow** [comment]
Sorry, I made a mistake in the JSON file. It is updated now.

**Comment by KarthikJay** [comment]
Thanks,

That does the trick for now!

**Comment by n-peugnet** [comment]
Hi, I have the same problem but I didn't understand exactly how you fixed the `pr_info` marco expansion problem. I am compiling against the sources of linux and here is my `c_cpp_properties.json`:
```json
{
    "configurations": [
        {
            "defines": [
                "__GNUC__",
                "__KERNEL__"
            ],
            "name": "Linux",
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu89",
            "includePath": [
                "/home/nicolas/Source/c/linux/include",
                "/home/nicolas/Source/c/linux/arch/x86/include",
                "/home/nicolas/Source/c/linux/arch/x86/include/asm",
                "/home/nicolas/Source/c/linux/arch/x86/include/generated",
                "/home/nicolas/Source/c/linux/include/uapi"
            ]
        }
    ],
    "version": 4
}
```
What should I change to get rid of this error ?

edit: ok sorry I understood afterwards. I just needed to add `"KBUILD_MODNAME=\"modname\""` to my `"defines"`.
