### ISSUE TITLE
Breakpoints disabled by default.

### ISSUE THREAD

**Issue by sarahkittyy** [microsoft/vscode-cpptools#3274]
Type: Debugger
This may be a simple configuration issue but in C++ source files, hitting F9 or clicking to set a breakpoint sets one, but it's automatically disabled.

**Describe the bug**
- OS and Version:
```
~ $ uname -r
5.0.0-arch1-1-ARCH
```
- VS Code Version:
```
~ $ code-insiders --version
1.33.0-insider
9b849d9de7168eb4f685823bf9b9e27a0a8dae74
x64
```
- C/C++ Extension Version: 0.22.0-insiders2

- Issue persists after disabling all other extensions.

Video of the bug:
https://drive.google.com/open?id=12KHqvu2UL4adltyK6YK1W5TQO8BbtoZn

**To Reproduce**
Any C++ file will work.
Just place a breakpoint down, and it will automatically be disabled.

**Additional context**
- No launch.json.
- Settings are irrelevant (removing all settings and reverting them to default does nothing.)

**Comment by WardenGnaw** [comment]
The file in the video that you provided has is not a valid C++ source file, the breakpoints will fail to bind because it could not match that breakpoint in the source file with a given line of instruction in the binary.

**Comment by dcrystalj** [comment]
i have same issue.. it was not always like this. In the left panel where breakpoints are list I have to manually check it to enable it. If I enable it manually it is working normal. I believe this is not problem with c++ source file if manualy ticking is debugging without problem.

![image](https://user-images.githubusercontent.com/1460727/57021465-983ce800-6c2c-11e9-8001-4fe36b8235ee.png)

this should be enabled by default when clicking as shown on video.

**Comment by sarahkittyy** [comment]
I haven't experienced this in a while and behavior seems ok so i'm just gonna close this ig
