### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Lorenz65** [microsoft/vscode-cpptools#3277]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.21.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\loren\ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by WardenGnaw** [comment]
Missing attached file and merging with https://github.com/Microsoft/vscode-cpptools/issues/2991
