### ISSUE TITLE
Question about forbidding language service or debugger function

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3284]
Hi,
Currently my .net framework version is 4.5, I don't want to upgrade it to 4.6 but I want to use new features about language service.  Are there some configurations which can forbid debug function or language service? And if there are, from which version they are added.
By the way, I wonder from which version need to upgrade .net framework to 4.6 if I want to use both language service and debugger.

**Comment by Lennon925** [comment]
In addition, Could I install two different versions independently? I wanna to forbid debugger on one version and forbid language service on another version.

**Comment by Lennon925** [comment]
@sean-mcmanus

**Comment by bobbrow** [comment]
The only way to install two different versions of the extension is to have two different versions of VS Code (e.g. stable and Insiders).

You can then disable the language server on one of them by using the `"C_Cpp.intelliSenseEngine": "Disabled"` setting.  There is no way to actively disable the debugger, but you could just refrain from creating and using a `launch.json` file.
