### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gloriaOli** [microsoft/vscode-cpptools#3287]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.21.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Carmen\ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by gloriaOli** [comment]
soy nueva me aparece este error y no se como arreglarlo

**Comment by bobbrow** [comment]
Thank you for your issue report.  We are tracking this with #3213.
