### ISSUE TITLE
Why is there a task type `shell` contributed?

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-cpptools#3289]
Type: General
Task type `shell` is reserved by VS Code and is a built in type. Having it contributed in the package.json of an extension causes json validation warnings for folks in tasks.json. Why is it being contributed in the cpptools extension? Contribution location: https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/package.json#L46

I noticed this because @noppej was getting a json validation warning that only occurs when the cpptools extension is installed. Related VS Code issue that found this: https://github.com/Microsoft/vscode/issues/68006#

**Comment by bobbrow** [comment]
I think this was added by mistake earlier.  I am opening a PR to remove it.

**Comment by alexr00** [comment]
Thank you!
