### ISSUE TITLE
Unable to launch debugger when default shell is fish

### ISSUE THREAD

**Issue by BusyJay** [microsoft/vscode-cpptools#329]
`$?` is invalid in fish shell, when try to debug a program with default shell set to fish, it will failed to be launched.

> arch -arch x86_64 '/Users/name/.vscode/extensions/ms-vscode.cpptools-0.9.2/debugAdapters/lldb/bin/lldb-launcher' --unix-socket=/tmp/87bOkG --arch=x86_64 --working-dir '/Users/name/Documents/workspace' --disable-aslr --  '/Users/name/Documents/workspace/program' ; echo Process exited with status $? ; exit
$? is not the exit status. In fish, please use $status.

**Comment by BusyJay** [comment]
Just find out this issue is duplicated with #239.

**Comment by leomikezee** [comment]
Same problem.
