### ISSUE TITLE
Functions using certain macros are not listed in Document and Workspace Symbols

### ISSUE THREAD

**Issue by harikrishnan94** [microsoft/vscode-cpptools#3290]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Mojave (10.14.3 (18D109))
- VS Code Version: 1.32.2
- C/C++ Extension Version: 0.22.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): Issue persists after disabling all other extensions.
- Certain functions are not listed in Document and Workspace Symbols, even though they are suggested in auto-complete, Source Hovers and GoTo Definition works for them correctly.

**To Reproduce**
1. Download [postgres repo](https://github.com/postgres/postgres.git)
2. Add `${workspaceFolder}/src/include` to includePath
3. Open `postgres.c` file and search for `exec_simple_query` in document/workspace symbols and it will not be listed.

**Additional context**
- From my investigation all functions using `foreach` macro (defined in pg_list.h) are not being listed in workspace or document symbols.
- And all uses of `foreach` macro are listed as definition/declaration in document/workspace symbols.

**Comment by sean-mcmanus** [comment]
This is "by design". The syntax breaking macros need to be added to a cpp.hint file in your workspace folder, see https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2017 , i.e. add something like
```
#define foreach (cell, l)
```

**Comment by sean-mcmanus** [comment]
FYI, this is fixed with 1.10.3 (pre-release) -- no cpp.hint is required for this case.
