### ISSUE TITLE
__cdecl and 5 other keywords aren't recognized by IntelliSense with clang without -fms-extensions

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3296]
With clang mode without -fms-extensions, "__cdecl" should be a valid pre-defined identifier.

Currently, it causes incorrect squiggles.

There could be additional keywords handled incorrectly in a similar manner.

A more comprehensive test is:

int __cdecl func() { return 0; }
int __fastcall func2() { return 0; } // C (>=3.2), or C++​ (>=3)
int __stdcall func3() { return 0; }​
int __thiscall func4() { return 0; }​
int __vectorcall func5() { return 0; } // >=3.6​
int * func10() { return __nullptr; } // C++​ (>= 3)
int main()​
{​
    return 0;​
}

UPDATE: I reported a VS bug internally.

**Comment by Colengms** [comment]
The symptoms here appears to specific to clang-x86 on Linux and Mac.  These keywords are not accepted by clang when building for x64 on Linux and Mac (compilation fails).  On Windows, these are all supported properly for both clang and clang-cl and both x86 and x64, as a result of cpptools always providing `-ms_extensions` to the IntelliSense process.

@sean-mcmanus Do you have a link to the feedback against VS for this?

**Comment by sean-mcmanus** [comment]
I'm not sure...I'll check...

**Comment by sean-mcmanus** [comment]
@Colengms It's 830252 -- looks like it's reported as an EDG bug in 2019, but not fixed yet.

**Comment by bobbrow** [comment]
This seems to be fixed in the latest version of the extension.
