### ISSUE TITLE
Question on Readme Info:  Data/Telemetry

### ISSUE THREAD

**Issue by CBtiger** [microsoft/vscode-cpptools#3299]
You write in the ReadMe:

> Data/Telemetry
> This project collects usage data and sends it to Microsoft to help improve our products and services. Read our privacy statement to learn more.

Does this mean your Extensions does its own Telemetry apart from the Telemetry of the main program VS Code? If so, can you please make that clear. If no, why are you mention that here (because it would have be mentioned at all externsions). I admit that this information is a bit confusing. Hopefully you could rephrase it a bit.

**Comment by bobbrow** [comment]
Yes, the extension collects feature usage information in addition to what VS Code collects.  Would you like for us to add that additional description?

**Comment by sean-mcmanus** [comment]
We use the vscode-extension-telemetry API -- see https://github.com/Microsoft/vscode-extension-telemetry . In particular, setting the telemetry.enableTelemetry option to false will also affect our extension telemetry too, so it's not a "separate" telemetry mechanism in that respect.

**Comment by CBtiger** [comment]
> We use the vscode-extension-telemetry API -- see https://github.com/Microsoft/vscode-extension-telemetry . In particular, setting the telemetry.enableTelemetry option to false will also affect our extension telemetry too, so it's not a "separate" telemetry mechanism in that respect.

@bobbrow , @sean-mcmanus thank you both for your replies.

 Yes, I would think its an important information. Both bits: a)You collect information apart from the main program and at least as informative. b) its controlled with thte same settings switch than the telemetry of the main program.

**Comment by crazyBaboon** [comment]
@CBtiger  

+1

**Comment by bobbrow** [comment]
The documentation was updated
