### ISSUE TITLE
can't work on win7

### ISSUE THREAD

**Issue by chena1982** [microsoft/vscode-cpptools#33]
i install the c/cpp extersion by copy the .vscode/extersions/ms-vscode.cpptools-0.5.0 folder to a pc which can't connect to internet.
this pc use win 7, after install, ctrl+shift+o show "we have no symbol information". and cannot find "go defintion" on right button menu, and the staut bar show text "undefinedwin32".

**Comment by csholmq** [comment]
Sounds like a duplicate of https://github.com/Microsoft/vscppsamples/issues/9

**Comment by sridmad** [comment]
Duplicate of #9

**Comment by chena1982** [comment]
yes, it works now, thanks.
