### ISSUE TITLE
"C_Cpp.clang_format_style" is not overwriting "editor.detectIndentation" setting.

### ISSUE THREAD

**Issue by kasraghu** [microsoft/vscode-cpptools#330]
When the following two options are used in settings, the indentation is not correct.
``` cpp
"editor.detectIndentation": true,
"C_Cpp.clang_format_style": "Visual Studio"
```

For example:
Instead of
``` cpp
if (IsGood)
    SomeThing= 0;
else
    SomeThing= 1;`
```
we get
``` cpp
if (IsGood)
SomeThing= 0;
else
SomeThing= 1;`
```

**Comment by greazer** [comment]
Hmmm... I tried, but am not reproducing the problem. I created a cpp file that had the code you suggest above (first in a function, but then outside of a function completely on its own). I set the settings as you suggest. Right clicking and choosing Format Document, results in the properly indented snippet. Am I missing something?

**Comment by kasraghu** [comment]
Here I am attaching the file to reproduce the problem. One thing I have observed is, if I try to use 'save as' option inside visual studio code, the indentation corrects itself in the new file. Copy/Paste or Renaming the file in windows explorer doesn't change anything.

Try introducing a tab at lines 21/23/30/33. When you do Ctrl+S, the lines revert back.

P.S: Change the file extension from .txt to .cpp
[TestIndent.txt](https://github.com/Microsoft/vscode-cpptools/files/574779/TestIndent.txt)

**Comment by bobbrow** [comment]
I tried your file and used the settings you mentioned and I do not see any problems with the formatting.  I also tried switching between tabs and spaces for indentation and they both work as expected.  Please let us know if you are still having issues with formatting.

Thanks!
