### ISSUE TITLE
Hight light of scanf format "%[]"

### ISSUE THREAD

**Issue by Tnze** [microsoft/vscode-cpptools#3301]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Mac OS Mojave
- VS Code Version: 1.32
- C/C++ Extension Version: 0.21.0

The highlighter incorrectly displays red for `%[]` format string.

**Screenshots**

![it should not be red](https://i.loli.net/2019/03/15/5c8ba659c7e26.png)

**Comment by sean-mcmanus** [comment]
This is fixed in the latest VS Code Insiders.
