### ISSUE TITLE
Linaro GDB remote connect

### ISSUE THREAD

**Issue by sswwpplyy** [microsoft/vscode-cpptools#3304]
Type: Debugger

- OS and Version: Ubuntu-16.04
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21.0
- Other extensions you installed (and if the issue persists after disabling them):

I'm trying to connect to gdbserver which run on an ARM device, but there are some errors.

I have printed the engine log:
```bash
1: (1031) <-1017-stack-list-frames 0 1000
1: (1035) ->1017^error,msg="Cannot access memory at address 0x34"
1: (1035) ->(gdb)
1: (1036) 1017: elapsed time 4
1: (1039) Stack walk failed on thread: 27901
ERROR: Unable to start debugging. Failed to find thread 1 for break event
1: (1045) <--gdb-exit
1: (1045) ->^exit
```

The log showed that 'frame list' caused gdb exit.

The 'cannot access memory at address 0x34' error message will also occur if I connect to the gdbserver in terminal, but will not cause the gdb exit.
Is it possible to disable the 'stack-list-frames'?

here is my launch.json
```bash
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "miDebuggerPath": "/opt/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin/arm-linux-gnueabihf-gdb",
            "program": "${workspaceFolder}/build/bin/c8_base",
            // "miDebuggerServerAddress": "192.168.0.105:2345",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "logging": {
                "engineLogging": true
            },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
            ],
            "launchCompleteCommand": "None",
        }
    ]
}
```

**Comment by pieandcakes** [comment]
@sswwpplyy Unfortunately not. `-stack-list-frames` is the first step in getting the call stack to be displayed. 

From feedback I've heard before, this sounds like an issue where your gdb and gdbserver architecture don't match. Please check that.

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
