### ISSUE TITLE
Ctrl + left click on an included header isn't resolved to configurations/includePath

### ISSUE THREAD

**Issue by kripod** [microsoft/vscode-cpptools#331]
`.vscode/c_cpp_properties.json`:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": ["/usr/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        },
        {
            "name": "Linux",
            "includePath": ["/usr/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        },
        {
            "name": "Win32",
            "includePath": ["C:/MinGW/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        }
    ]
}
```

`src/main.c`:

```c
#include <stdbool.h>
#include "size.h"
#include <SDL2/SDL.h>

int main(int argc, char* args[]) {
    // ...
    return 0;
}
```

Although `stdbool.h` and `size.h` can be opened by ctrl + left click, trying to open `SDL2/SDL.h` results in the following error message:

> Unable to open 'SDL.H': File not found (c:\DEVELOPMENT\PROJECTS\PROJECT\DEPENDS\SDL\INCLUDE\SDL.H).

The syntax highlighter doesn't mark `#include <SDL2/SDL.h>` with a green underline, so it seems to find the header correctly, based on the include path.

**Comment by mycraftmw** [comment]
The same problem.

**Comment by bobbrow** [comment]
@kripod, does SDL.h exist at the location you shared?  My guess is that you may have moved the library somewhere else after the extension had already indexed it and the database wasn't updated to reflect the file move.  You can try changing the "databaseFilename" in your c_cpp_properties.json file to create a new database and see if that fixes your issue.

**Comment by kripod** [comment]
@bobbrow Thank you for the tip! I'm not entirely sure whether SDL2/SDL.h existed before creating c_cpp_properties.json.

**Comment by bobbrow** [comment]
I forgot to mention, we added some documentation with a [sample c_cpp_properties.json file for MinGW projects](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md).

Please let us know if you continue to have issues.
