### ISSUE TITLE
Problem interacting with custom FoldingRangeProvider

### ISSUE THREAD

**Issue by maptz** [microsoft/vscode-cpptools#3315]
- OS and Version: Windows 10 Pro
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.21

The C/C++ language extension for VS code appears to have an issue with other vscode extensions that implement `FoldingRangeProvider`. When the new extension registers `FoldingRangeProvider` normal C-folding for functions, loops, structs, etc. is not longer available / not longer shown. 

To reproduce this error, install my custom extension available on the marketplace  as `maptz.regionfolder`, or clone the repo from github [here](https://github.com/maptz/maptz.vscode.extensions.customfolding), and place the following code into a new .c file:

```
   // #region  My region
   void main(void)
   {
       int foo = 1;
       if (foo)
       {
           foo = 0;
       }
       return foo;
   }
   // #endregion
```

My extension allows you to collapse custom sections of code based on custom comments by implementing a `FoldingRangeProvider`, and recognises the `//#region` tags above. With both C/C++ and maptz.regionfolding installed, the default C-folding no longer works.

This was originally logged on my repo [here](https://github.com/maptz/maptz.vscode.extensions.customfolding/issues/5), but appears to be a bug with the C/C++ language service.

**Comment by bobbrow** [comment]
Our extension doesn't do any custom folding at this time.  We have an issue open to enable it. #407

**Comment by maptz** [comment]
I see what's happening now then. When you implement a `FoldingRangeProvider` which my extension does, the default (indentation-based) folding behaviour is overriden. This is a vs code issue, so I'll close this issue now.
