### ISSUE TITLE
Launch options string provided by the project system is invalid. (hexadecimal value 0x08 is an invalid character; line 6 position 54)

### ISSUE THREAD

**Issue by WOOSAL** [microsoft/vscode-cpptools#3319]
Hello guys! I was trying to debug my C++ code via VS Code and my compiler is mingw, however, I can not launch it.... This is how my **launch.json** looks like : 

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.exe",
            "args": [ ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [ ],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Users\\Vusal\\Desktop\\HARHAR\\mingw\bin\\gdb.exe",
            "preLaunchTask": "echo",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

**Comment by WardenGnaw** [comment]
0x08 is a backspace character. Somewhere in your launch.json is a non-visable character that VS Code is not happy about. Can you delete your launch.json, press F5, and select the GDB configuration to get a new launch.json?

**Comment by WOOSAL** [comment]
I can try now, I will inform you now. Thanks for starting your support

**Comment by WOOSAL** [comment]
> 0x08 is a backspace character. Somewhere in your launch.json is a non-visable character that VS Code is not happy about. Can you delete your launch.json, press F5, and select the GDB configuration to get a new launch.json?

dude i try to start all again but do not get that green highlight and lamp in order to get the new launch.json file. How I can get it?

**Comment by WOOSAL** [comment]
> 0x08 is a backspace character. Somewhere in your launch.json is a non-visable character that VS Code is not happy about. Can you delete your launch.json, press F5, and select the GDB configuration to get a new launch.json?

forget about all, i am going to spend that fixing time Atom learning C++. thanks for the help tho :D

**Comment by bolner** [comment]
I have the same issue after copied the launch.json sample from the tutorial page:
- https://code.visualstudio.com/docs/cpp/config-mingw

I opened the file with a hex editor, and it has no 0x08 byte in it at all.

**Comment by bolner** [comment]
Found the issue: It's non issue. Related to escaping in JSON.
After replacing the compiler path, all backslashes were double except before a "b", which generated a 0x08 internally:

- "miDebuggerPath": "C:\\\\mingw-w64\\\\mingw64\\bin\\\\gdb.exe",

But there might still be a bug, because it complained about "line 6", and the problem was at line 15.
