### ISSUE TITLE
Remote c++ debugging

### ISSUE THREAD

**Issue by lxl30** [microsoft/vscode-cpptools#332]
I am looking for a little help in debugging my app using vscode. My app is in a Parallels Desktop virtual machine running Ubuntu 14.04, and I am running vscode on my Mac, running MacOS 10.12. I am using ssh to connect to Ubuntu, and my home directory in Mac is shared with the VM. 

Unfortunately, I could not find any couldn't find any cross-gcc which can do the debugging using gdbserver. So I tried to make vscode do an ssh before executing gdb. 

To ensure, the absolute paths of the source files in both the system are same, I created a (symbolic)link of my mac home folder in the VM, at the location /Users/mac_user.

In my Mac, I created a wrapper bash script (say `rungdb.sh`)

 ```
#!/usr/bin/env bash
ssh VM_user@VM_address "
cd  /Users/mac_user/project_path  > /dev/null
g++ -g file.cpp > /dev/null
gdb --interpreter=mi a.out "
```
and configured my `launch.json` to run this bash script. 

```
{  "version": "0.2.0",
    "configurations": [{
        "request": "launch",
        "cwd": "${workspaceRoot}",
        "name": "C++ Launch",
        "type": "cppdbg",
        "program": "${workspaceRoot}/a.out",
        "linux": {
                "MIMode": "gdb",
                "miDebuggerPath": "/Users/mac_user/project_path/rungdb.sh",
        },
        "osx": {
                "MIMode": "gdb",
                "miDebuggerPath": "/Users/mac_user/project_path/rungdb.sh",
        },
        "windows": {
                "MIMode": "gdb"
        }]
}
```
With this configuration, vscode was able to debug and step through the program showing the variable values, call stack, and the breakpoints are also working..  but somehow it is not displaying the source file. It is showing the error "Source file.cpp not available." Any fix to this or any alternative approach will be much appreciated. Thanks!

**Comment by pieandcakes** [comment]
@lxl30 Alternative source mapping feature isn't available right now but it is something that we are working on. What you can do for now is make sure the code is in the same exact folder structure on your Mac that it is in Ubuntu and then it should find it. 

You can also download VSCode with our extension directly on Ubuntu and use it there too, bypassing the remote scenario.

**Comment by pieandcakes** [comment]
Source File Mapping will be available in the next update.

**Comment by pieandcakes** [comment]
Source File mapping has been released. Let me know if this resolves your issue.
