### ISSUE TITLE
Using the `Build and Debug Active File` command causes an "undefined task type" warning to get logged.

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3322]
With 0.22.0.

It doesn't seem to cause any other issue. Not sure why we never noticed this earlier.

**Comment by sean-mcmanus** [comment]
Uh...I don't know how to fix this. Looks like some VS Code issue. Looks like validTypes[task.definition.type] === true fails, in extHostTask.ts, leading to the console.warn call.

**Comment by ghost** [comment]
I'm also getting this error now in output console after running a simple shell type build task

I get no errors if I disable cpptools extension

``` 
There are task errors. See the output for details.

Error: e is not iterable
Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined
Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined
Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined
Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

```
{
    "label": "Debug-Build",
    "type": "shell",
    "command": "${workspaceFolder}/build.bash",
    "args": [
        "-d"
    ],
    "group": {
	"kind": "build",
        "isDefault": true
    },
    "problemMatcher": []
},
```

- OS and Version: macOS 10.14.3
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1

**Comment by sean-mcmanus** [comment]
This was a VS Code bug. Should be fixed in the next Insiders.
