### ISSUE TITLE
macFrameworkPath isn't working?

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3323]
Unfortunately this feature seems to not work on my side,

![](https://i.imgur.com/z20k54L.png)

As you can see i tried different things, put the root folder or frameworks/headers directories directly.
The result is always the same.

If i switch "fuzzy" mode on & off the result is the same (well in fuzzy mode it's underlined in green with a message telling to update includePath). Did I miss something ?

OSX 10.14.3
VSCode 1.32.3
CPP Tools 0.21.0

_Originally posted by @jbltx in https://github.com/Microsoft/vscode-cpptools/issues/970#issuecomment-474642622_

**Comment by jbltx** [comment]
As I said in https://github.com/Microsoft/vscode-cpptools/issues/970#issuecomment-474657703, it seems there's a difference between writing manually the `Headers` path in the configuration file, and clicking the suggestion given by the tool in any `#include`. Only the suggestion clear the errors.
To more, I think the suggestion shouldn't be the real `Headers` path, but a Framework one. 
![](https://camo.githubusercontent.com/bed2fc68e18bde08f8b70d8145425be46a5b39a1/68747470733a2f2f692e696d6775722e636f6d2f4434434c66646e2e706e67)
I can take a look at the code this evening if there's no assignee yet.

**Comment by sean-mcmanus** [comment]
The code action is implemented in the addToIncludePathCommand method in our open source (https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/configurations.ts), but it basically just writes to the c_cpp_properties.json, so I don't know why the behavior would be different.

**Comment by julee** [comment]
Any news? It's Troublesome

**Comment by sean-mcmanus** [comment]
@julee What issue are you hitting? I don't think we found a repro for this issue. Can you provide more repro info?

**Comment by julee** [comment]
> @julee What issue are you hitting? I don't think we found a repro for this issue. Can you provide more repro info?

Project:
[vs_sample.zip](https://github.com/microsoft/vscode-cpptools/files/4384658/vs_sample.zip)

you may edit the  .vscode/setting.json , change Qt5_DIR to the correct path:
```
{
    "cmake.configureArgs": [
        "-DQt5_DIR=/Users/julee/Qt5.10.1/5.10.1/clang_64/lib/cmake/Qt5"
    ],
    "C_Cpp.default.configurationProvider": "vector-of-bool.cmake-tools"
}
```

After cmake: configure the project, Qt head files cannot find by vscode, though all include path are detected.

![image](https://user-images.githubusercontent.com/1493342/77602903-a7660c00-6f49-11ea-8424-9c4d744df883.png)

C/C++ Log Diagnostics output:

```
-------- Diagnostics - 3/26/2020, 10:02:58 AM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "knownCompilers": [
        {
            "path": "/usr/bin/clang",
            "isC": true
        },
        {
            "path": "/usr/bin/clang++",
            "isC": false
        },
        {
            "path": "/usr/bin/gcc",
            "isC": true
        },
        {
            "path": "/usr/bin/g++",
            "isC": false
        },
        {
            "path": "/usr/bin/cpp",
            "isC": false
        },
        {
            "path": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang",
            "isC": true
        },
        {
            "path": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++",
            "isC": false
        },
        {
            "path": "/usr/bin/clang",
            "isC": false
        }
    ],
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": [],
    "configurationProvider": "vector-of-bool.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Volumes/SSD/code/issue_test/vs_sample/main.cc ]:
    /Volumes/SSD/code/issue_test/vs_sample/main.cc
Translation Unit Configurations:
[ /Volumes/SSD/code/issue_test/vs_sample/main.cc ]:
    Process ID: 73493
    Memory Usage: 7 MB
    Compiler Path: /usr/bin/clang++
    Includes:
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Versions/5/Headers
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Versions/5/Headers
        /Users/julee/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Defines:
        QT_CORE_LIB
        QT_GUI_LIB
        QT_WIDGETS_LIB
    Standard Version: c++11
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 7 MB

-------- Diagnostics - 3/26/2020, 10:06:58 AM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "knownCompilers": [
        {
            "path": "/usr/bin/clang",
            "isC": true
        },
        {
            "path": "/usr/bin/clang++",
            "isC": false
        },
        {
            "path": "/usr/bin/gcc",
            "isC": true
        },
        {
            "path": "/usr/bin/g++",
            "isC": false
        },
        {
            "path": "/usr/bin/cpp",
            "isC": false
        },
        {
            "path": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang",
            "isC": true
        },
        {
            "path": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++",
            "isC": false
        },
        {
            "path": "/usr/bin/clang",
            "isC": false
        }
    ],
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": [],
    "configurationProvider": "vector-of-bool.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Volumes/SSD/code/issue_test/vs_sample/main.cc ]:
    /Volumes/SSD/code/issue_test/vs_sample/main.cc
Translation Unit Configurations:
[ /Volumes/SSD/code/issue_test/vs_sample/main.cc ]:
    Process ID: 73587
    Memory Usage: 7 MB
    Compiler Path: /usr/bin/clang++
    Includes:
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Versions/5/Headers
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework
        /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Versions/5/Headers
        /Users/julee/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Defines:
        QT_CORE_LIB
        QT_GUI_LIB
        QT_WIDGETS_LIB
    Standard Version: c++11
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 7 MB
```

**Comment by julee** [comment]
@sean-mcmanus Any news for this issue?

**Comment by sean-mcmanus** [comment]
I'm not sure if anyone investigated this yet. What is the exact error message, i.e. which header is missing? QtGui/QGuiApplication or a dependency of that ? Where is the file located? At one of the paths in the "Includes" in your logs?

**Comment by julee** [comment]
> I'm not sure if anyone investigated this yet. What is the exact error message, i.e. which header is missing? QtGui/QGuiApplication or a dependency of that ? Where is the file located? At one of the paths in the "Includes" in your logs?

QtGui/QGuiApplication not found. it's locate at: /Users/julee/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Versions/5/Headers

**Comment by julee** [comment]
@sean-mcmanus  You can try that demo project with macOS, just edit the  .vscode/setting.json ,set Qt5_DIR  to correct path, you can find the bug

**Comment by bobbrow** [comment]
I think the problem is that `/Users/julee/Qt5.10.1/5.10.1/clang_64/lib` is not being added as a framework path.  This looks like a bug with CMake Tools.

**Comment by bobbrow** [comment]
You could write it as `#include <QGuiApplication>` to make IntelliSense work, but I don't know if that will compile for you.

**Comment by julee** [comment]
> You could write it as `#include <QGuiApplication>` to make IntelliSense work, but I don't know if that will compile for you.

use `#include <QGuiApplication>` Wont' work, it says:
can't open "QtGui/qtguiglobal.h" (dependency of "QGuiApplication").

**Comment by julee** [comment]
> I think the problem is that `/Users/julee/Qt5.10.1/5.10.1/clang_64/lib` is not being added as a framework path. This looks like a bug with CMake Tools.

Yes, you are right! It's a bug with CMake Tools. 
I try remove `"configurationProvider": "vector-of-bool.cmake-tools"`, and add: `"compileCommands": "${workspaceFolder}/build/compile_commands.json" `
It works now!

Thanks you!

**Comment by bobbrow** [comment]
> use `#include <QGuiApplication>` Wont' work, it says:
> can't open "QtGui/qtguiglobal.h" (dependency of "QGuiApplication").

Ah yes, that's a problem if the dependencies are all using the framework syntax.  🤦‍♂️ Thanks for opening the bug for CMake Tools.

**Comment by julee** [comment]
> > use `#include <QGuiApplication>` Wont' work, it says:
> > can't open "QtGui/qtguiglobal.h" (dependency of "QGuiApplication").
> 
> Ah yes, that's a problem if the dependencies are all using the framework syntax. 🤦‍♂️ Thanks for opening the bug for CMake Tools.

Open a issue:
[CMake Tool Issue: Require Pass -iframework Options to C/C++ Extension](https://github.com/microsoft/vscode-cmake-tools/issues/1178)
