### ISSUE TITLE
Can't attach remote linux c++ program

### ISSUE THREAD

**Issue by aengusjiang** [microsoft/vscode-cpptools#3325]
When use the remote attach way, it start failed and show me:
bash: sh -c uname && if [ $(uname) = "Linux" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) = "Darwin" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi: command not found
Command failed: "ssh" "smite@192.168.1.78" 'sh -c "uname && if [ $(uname) = \"Linux\" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) = \"Darwin\" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi"'
bash: sh -c uname && if [ $(uname) = "Linux" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) = "Darwin" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi: command not found

**Comment by aengusjiang** [comment]
The vs code version 1.32.3
the cpptool: 0.22,

The vsersion 0.19 is ok, but 0.20, 0.21, and the newest version it still can't work.
But the issue log said that issue have fixed.

https://github.com/Microsoft/vscode-cpptools/issues/2998

**Comment by aengusjiang** [comment]
The local OS is Window10, and the remote os is Centos7.5

**Comment by aengusjiang** [comment]
[test.zip](https://github.com/Microsoft/vscode-cpptools/files/2986762/test.zip)
the sample.

**Comment by WardenGnaw** [comment]
Since I'm still seeing single quotes, I believe this does not have the latest fix. https://github.com/Microsoft/vscode-cpptools/pull/3181 

Have you tested with 0.22.0?

**Comment by aengusjiang** [comment]
Hi, WardenGnaw.
I am sure I test it with 0.22.0.
It is OK about launch a remote program in my environment, it it can't not work with remote attach.
It show me the result above. "bash: sh -c uname && if [ $(uname) = "Linux" ] ; then ps axww -o ..."
I really don't what wrong about that.
I always use this function to debug before, but it has problem since 0.20.0 version.

It's pleasure to help you solve this problem and you could tell me how to help you. such as get some logs or others.
You also can run the sample.

**Comment by aengusjiang** [comment]
I have try it On os：Ubuntu 18.04.1 LTS， it can work.
![image](https://user-images.githubusercontent.com/22406984/54773415-7c652000-4c44-11e9-997b-823cb28e29a3.png)

**Comment by WardenGnaw** [comment]
Can you run 
```
sh -c "uname && if [ $(uname) = \"Linux\" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) = \"Darwin\" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi"
```
on the centOS machine?

**Comment by WardenGnaw** [comment]
Could you also share your launch.json or provide the pipeProgram you are using?

**Comment by aengusjiang** [comment]
I can run that command, seet that:
![image](https://user-images.githubusercontent.com/22406984/54796943-48fab380-4c8d-11e9-94cf-e19593d4d16c.png)

**Comment by aengusjiang** [comment]
The pipeProgram is ssh.exe. There is a ssh.exe after installed Git for windows.
![image](https://user-images.githubusercontent.com/22406984/54797106-cc1c0980-4c8d-11e9-8d89-a31df8ba8b02.png)
and the git version is 
![image](https://user-images.githubusercontent.com/22406984/54797134-e6ee7e00-4c8d-11e9-9437-4f1d1e70fb93.png)

**Comment by aengusjiang** [comment]
the launch file:
![image](https://user-images.githubusercontent.com/22406984/54797453-1ea9f580-4c8f-11e9-9208-72cb50f41e91.png)
this file is contain in the test.zip
and I was add the ssh to the path environment.

**Comment by aengusjiang** [comment]
I also use the public key to authorized ssh

**Comment by aengusjiang** [comment]
I seem to find the problem.
When I set the pipe program with the absolute path, for the attach way is OK.

But the launch way is also use the ssh(not the absolute path ), and it is OK, but for the attach is failed.
I think this is exist some issue, I hope that can help you.
