### ISSUE TITLE
Using the `Build and Debug Active File` command will empty the original tasks.json

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode-cpptools#3327]
Issue Type: <b>Bug</b>

1. Use the `Build and Debug Active File` command.
2. The original tasks.json was replaced.

Is it a feature or a bug?

If it is a feature,could you add a setting to control it?

Extension version: 0.22.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (2.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
Sorry about that -- we have a fix at https://github.com/Microsoft/vscode-cpptools/pull/3328, which we plan to release later today.

NOTE: Single-line comments will still be removed from the tasks.json when the command is used. We might fix that for 0.23.0.

**Comment by sean-mcmanus** [comment]
Fixed with 0.22.1.
