### ISSUE TITLE
Configuration problem with MinGW and gcc 8.2

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3329]
Not sure if it is related, but I have a similar problem where includes, cout, etc work, but "system" (etc. for system("pause");) is underlined red. Any Help appreciated!

My c_cpp_properties.json:

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}",
                "C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++",
                "C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++/mingw32",
                "C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++/tr1"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "compilerPath": "C:/MinGW/bin/gcc.exe",
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 4
}
```

_Originally posted by @ChiIIBiII in https://github.com/Microsoft/vscode-cpptools/issues/2381#issuecomment-474745290_

**Comment by bobbrow** [comment]
Sorry we missed this issue!  If you are still having problems with the latest version of the extension, please let us know.  We have made numerous improvements in how configuration for system headers work, so we suspect that your issue may have already been fixed.
