### ISSUE TITLE
IntelliSense doesn't work with c++ header files

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode-cpptools#3330]
Issue Type: <b>Bug</b>

When I view a c++ header filr(files without extensions),
e.g. algorithm,cstdio,
IntelliSense will shut down at once.
```
Shutting down IntelliSense server: C:\COMPILER\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\ALGORITHM
```
So I can't go to declaration or peek declaration.

I tried setting cache size to 0,but it doesn't work.

Extension version: 0.22.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
Do you know if this a regression compared to 0.21.0 (i.e. via the Install Another Version option).

I'm not seeing the issue with MinGW64 gcc 7.3.

**Comment by mxdh** [comment]
@sean-mcmanus 0.21.0 works properly.
I use MinGW-w64 gcc 8.1.0.

**Comment by mxdh** [comment]
@sean-mcmanus 
my c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Win32-C++",
            "compilerPath": "C:/Compiler/MinGW64/bin/g++.exe",
            "intelliSenseMode": "gcc-x64",
            "cppStandard": "c++98"
        },
        {
            "name": "Win32-C",
            "compilerPath": "C:/Compiler/MinGW64/bin/gcc.exe",
            "intelliSenseMode": "gcc-x64",
            "cStandard": "c99"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
I'm not able to repro this bug with `mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/g++.exe`. Where did you get your version of MinGW? Does it repro just by using code
```
#include <algorithm>
int main()
{
return 0;
}
```

If your machine doesn't have enough memory, is it possible we are just closing the older IntelliSense instance when switching to the header? We start doing that after 1.5 GB of memory is used.

**Comment by mxdh** [comment]
@sean-mcmanus Sorry, I didn't express it clearly.
My English is not good.
When I open a C++ header file,I can't go to declaration or peek declaration.
For example,"algorithm" includes "bits/stl_algobase.h",when I view "algorithm",I can't peek or go to "bits/stl_algobase.h".

**Comment by sean-mcmanus** [comment]
It sounds like querying of the g++ compiler is not working correctly. Can you [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and see if the path of the "bits" folder is being used? I'm not able to repro the bug using the version of mingw-w64 I have installed.

**Comment by mxdh** [comment]
@sean-mcmanus 
I'm sorry to bother you.
After two reboots,it works.
This is probably caused by insufficient memory.My machine has 8GB memory.
This may be related to a memory leak,but it shouldn't be a new issue.
