### ISSUE TITLE
Open the externalConsole inside the VSCode Terminal Tab in OSX

### ISSUE THREAD

**Issue by Mon-ius** [microsoft/vscode-cpptools#3338]
Every time I debug C/C++ code, the VSCode always open a terminal outside terminal when I have a full screen vscode open. I knew there is a way just set `"externalConsole": false, ` in `launch.json`. But I would like to enable the input. There is a **TERMIAL** tab near the **DEBUG CONSOLE**, why not just open terminal inside it to enable interaction.

`OS`:  `macOS Mojave 10.14.3 (18D109)`

### settings.json
```
{
    "workbench.colorTheme": "Material Theme Ocean",
    "workbench.iconTheme": "eq-material-theme-icons-ocean",
    "workbench.startupEditor": "newUntitledFile",
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "editor.fontFamily": "hack",
    // Controls the line height. Use 0 to compute the lineHeight from the fontSize.
    "editor.lineHeight": 24,
    // Enables font ligatures
    "editor.fontLigatures": true,
    // Controls if file decorations should use badges.
    "explorer.decorations.badges": false,
    "terminal.external.osxExec": "iTerm.app",
    "terminal.explorerKind": "external",
    "terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.integrated.fontFamily": "Hack Nerd Font",
    "window.zoomLevel": 1,
    "explorer.confirmDelete": false,
    "git.enableSmartCommit": true,
    "latex-workshop.message.update.show": false,
}
```

###  tasks.json
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "build",
      "command": "clang++",
      "args": [
        "-o",
        "hello", // executable
        "hello.cpp", // main file
        "-g",
        "-v"
      ],
      "type": "shell",
      "presentation": {
        "echo": true,
        "reveal": "always",
        "panel": "new"
      },
      "problemMatcher": {
        "owner": "cpp",
        "fileLocation": [
          "relative",
          "${workspaceRoot}"
        ],
        "pattern": {
          "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "message": 5
        }
      }
    }
  ]
}
```

### launch.json
/* launch.json */
```
{
    "version": "2.0.0",
    "configurations": [

        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/hello",
            "preLaunchTask": "build",
            "internalConsoleOptions": "openOnSessionStart",
            "logging": {
                "moduleLoad": false,
                "programOutput": true,
                "trace": false
            },
            "showDisplayString": false,
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true, 
            "osx": {
                "MIMode": "lldb"
            }
        }
    ]
}
```

### My example code(hello.cpp)
```

/* hello.cpp */
#include <iostream>
using namespace std;
int main()
{
    cout << "Please enter your name: ";
    string name;

    cin >> name;
    cout << "Hello, " << name;
    cout << "\n";
    return 0;
}
```

**Comment by WardenGnaw** [comment]
Integrated terminal support is not available for MacOS at this time. lldb does not have the capabilities for it yet.

**Comment by Mon-ius** [comment]
If this feature has already been in roadmap in recent version? Will you plan to support it?

**Comment by Yang-Xijie** [comment]
It seems that your method doesn't work for me. I have the same requirement as you do. On Windows just changing "externalConsole": false then you could input in the integrated shell below.

**Comment by Yang-Xijie** [comment]
After checking the official document, I found the reason.
link here -- https://code.visualstudio.com/docs/cpp/launch-json-reference
<img width="951" alt="image" src="https://user-images.githubusercontent.com/57952362/94843091-cd1b2300-044e-11eb-96e5-9834955cf455.png">
What a pity! Hope that this function will be added in the soon future.

**Comment by FavonianKong** [comment]
> After checking the official document, I found the reason.
> link here -- https://code.visualstudio.com/docs/cpp/launch-json-reference
> <img alt="image" width="951" src="https://user-images.githubusercontent.com/57952362/94843091-cd1b2300-044e-11eb-96e5-9834955cf455.png">
> What a pity! Hope that this function will be added in the soon future.

when I set the `externalConsole` to true，pressing F5 will not start the debugger, and the debugger is always displayed as loading.
