### ISSUE TITLE
Intellisense refreshing locks window

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#3340]
Platform: Ubuntu, VSCode version: 1.32.3, Cpp tools version: 0.22.0

Intellisense seems to be being updated when I am typing. Sometimes it locks the window for several seconds.

If I revert to version 0.21 it is much less agressive - the timeout for refreshing when I stop typing is more like 2 seconds. With the current version it starts when I am still typing.

Is there a setting for controlling the delay? I couldn't see one...

**Comment by sean-mcmanus** [comment]
Yes, we changed our IntelliSense updating behavior to match Visual Studio's behavior more.

"Locks the window" sounds like our IntelliSense process might be using too much memory or CPU for your scenario. Can you provide any more details on your hardware (number of cores and RAM)...or can you check which resources are being used too much...or how large the .ipch file is for the source file that is causing a problem?

There is not currently a setting to control this.

**Comment by Gruntfuggly** [comment]
I'm using a virtual machine, but it uses 8 cores (I think - It's my work machine and I'm now at home for the weekend).

It happens with all source files, regardless of size - and none of them are particularly large. Where do I find the .ipch files?

I've had to go back to 0.21 - the current version is unusable.

**Comment by sean-mcmanus** [comment]
The ipch folder is in the .vscode folder.

We've received reports of memory usage problems.

It could be some issue with VMs and our usage of mmap calls -- one potential workaround would be to set the intelliSenseCacheSize to 0 in case that is making it slow. We'll try to find some repro scenario.

UPDATE: I tested with LLVM (https://github.com/llvm-mirror/llvm) in LLParser.cpp on an Ubuntu VM, and I'm not seeing performance issue. Also, the IntelliSense "reparse" should only occur "onIdle" -- if you set the C_Cpp.loggingLevel to "Debug" you should see "idle loop: reparsing the active document" after you finish typing. Other typing will send changes to the IntelliSense to handling changes for things like completion. If you see any "disconnected" or "failed" messages that could be leading to the performance issues, i.e. if the IntelliSense process is continuously restarting for some reason, or for example if you see the memory usage go over 1.5 GB.

**Comment by Gruntfuggly** [comment]
OK - I'll check the ipch folder and try setting intelliSenseCacheSize on Monday. Thanks.

**Comment by Gruntfuggly** [comment]
Without changing anything, I see this while I was still typing:
```
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
Database safe to open
Checking for syntax errors: file:///....
queue_update_intellisense for files in tu of: ...
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
sending 8 changes to server
errorSquiggles count: 5
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/codeAction: 86
textDocument/documentSymbol: 87
```
and immediately after I stop (seriously a fraction of a second)
```
idle loop: reparsing the active document
Checking for syntax errors: file:///...
queue_update_intellisense for files in tu of: ...
sending 3 changes to server
errorSquiggles count: 0
textDocument/codeAction: 88
```

No disconnect or failed at the moment. I'll keep an eye on it.

**Comment by Gruntfuggly** [comment]
Still no "disconnect" or "failed" entries in the log, however it just locked up for about 30 seconds. When it started responding again, I saw the following in the log:
```
textDocument/documentHighlight: 1731
cpptools/textEditorSelectionChange
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/textEditorSelectionChange
cpptools/fileDeleted
cpptools/fileCreated
textDocument/codeAction: 1732
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
Database safe to open
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileDeleted
Database safe to open
```

Does that look OK? 

Unfortunately there are no time stamps so it's not possible to see how long these things are taking.

**Comment by bobbrow** [comment]
Did you checkout a new branch in git (or your favorite source control provider)?  I see slowness in the extension when switching between two branches that have a lot of differences.  If this is what you are experiencing, we have an issue open for this: #2806.

These messages are just letting us know that files are changing in the workspace.  We respond to them by tag parsing the files and adding or removing them from our database.  I profiled our handling of this the other day, but the slowness didn't seem to be in the language server binary, so I was going to investigate the file watchers next.

I have been discussing with the team putting timestamps in the messages, and we'll likely do so for the next release since we'll be spending more time on editor performance in this iteration.

**Comment by Gruntfuggly** [comment]
No, I hadn't changed the repository in any significant way. 

I don't think I was adding/deleting files either. You can see there was one point where I changed the code, so I'm pretty sure all those create/deletes were happening during the lock up.

**Comment by bobbrow** [comment]
It can also happen during `git pull` or maybe if your build output folder is inside the workspace folder.  We might just need to log the file URI for you to figure out what it is.  Do you see these messages every time the lock up happens?

**Comment by Gruntfuggly** [comment]
Sorry - I missed this reply. My build output folder *is* in the workspace, however, the lock up occurs during editing.

I've been using version 0.21.0 of the extension for the past two weeks without any issues. I'll update again and see what happens.

**Comment by sean-mcmanus** [comment]
Do the problems ever happen if you don't do any new builds before editing?

It looks like we're clearing some include caches and updating squiggles on every file deletion, because the deleted file might be a header, but that change was made a year ago (particulary if the build files are extensionless)...maybe the effect just became worse.

We can investigate the "build folder in workspace" scenario for performance later. I don't think 0.22.2-insiders solves this.

**Comment by Gruntfuggly** [comment]
I'm still stuck on version 0.21.0. If I use anything later I get frequent lock ups - even to the extent of vscode telling me the window has stopped responding, sometimes just when starting vscode.

Is there any way that whatever changed in 0.22.0 could be made configurable?

**Comment by sean-mcmanus** [comment]
We're still thinking about what to do. Right now the IntelliSense update is not "chunkable"/cancelable so fixing that might fix your issue. I think we've only had a couple users report a symptom like this so we're not sure what the cause is. Are you able to run some system wide profiler on your machine to identify what process or call stack or resource is causing your OS to freeze? I don't think anyone on our team has been able to repro this symptom (on Linux or other OS's).

**Comment by Gruntfuggly** [comment]
One thing I've noticed is that windows which are not even active seem to be updating the intellisense database. I tend to have 3 or 4 vscode windows open at the same time. Maybe this is causing the issues?

**Comment by sean-mcmanus** [comment]
What do you mean by "windows"? Do you mean you have multiple VS Code instances open? Do they all point to the same workspace folder? What do you mean by "IntelliSense database" -- do you mean the browse database (i.e. from "tag parsing file") or the in-process IntelliSense updating?

**Comment by Gruntfuggly** [comment]
Multiple instances of vscode pointing at different workspace folders, but sharing libraries. They are modules in an overall project.

To be honest, it's hard to tell what database - it's the red flame icon which says "Updating Intellisense..." when I hover over it. Also the white 'database' icon seems to be shown at the same time quite often.

**Comment by sean-mcmanus** [comment]
If you have 4+ VS Code windows open and you make an edit to a header file shared all the projects, then that will cause all 4+ processes to try to update after typing, even if the Windows are not active...it's not a scenario we have optimized for yet. Are you able to determine if that this is the cause of the OS freezes?

**Comment by Gruntfuggly** [comment]
The problem definitely gets worse with more windows open.

**Comment by bobbrow** [comment]
We recently addressed some performance problems related to receiving multiple fileCreated/fileDeleted messsages in a short period of time.  If you continue to experience this problem with the latest version of the extension, please let us know.
