### ISSUE TITLE
version setting cause version control issues

### ISSUE THREAD

**Issue by jasonbeach** [microsoft/vscode-cpptools#3344]
The "version" property in the `c_cpp_properties.json` file gets automatically and persistently updated by the extension (if the extension knows what it should be, why is it even a setting?)  This causes problems with version control when working with others who may not have installed the most update version of vscode.  

If `"version": 3` is committed to the repository and someone who has the latest version (for which it needs to be `"version": 4`) it is a little painful to work with git.  If you don't want to commit that change, the only way to do operations such as `git pull --rebase` is to close vscode so you can stash the `c_cpp_properties.json` file and then do the pull.  If you stash the file with vscode still open the setting just gets re-updated.  

It seems like this setting is more of a global setting that shouldn't be in individual .vscode folders.

- OS and Version: Linux Ubuntu 16.04
- VS Code Version: 1.31.1 is combination with others
- C/C++ Extension Version: 0.22.0 

**Expected behavior**
This seems like a superfluous thing to force users to commit to version control and particularly if different users are using different versions causing multiple superfluous commits.

**Comment by sean-mcmanus** [comment]
The version is required in order for us to process the c_cpp_properties.json correctly after a breaking change is introduced that would cause incorrect behavior in the latest extension version if the c_cpp_properties.json was created with an older version. Simply removing the version wouldn't fix the problems that could occur as a result. Our extension knows what version it's using, but it doesn't know what version the c_cpp_properties.json was created using without checking the version. c_cpp_properties.json wasn't designed to checked into source control, but if you commit c_cpp_properties.json to a repo, then it's expected that everyone will be able to use that version.

We don't increase the version very often, so the current version 4 should work with VS Code 1.22.0 and our extension version 0.17.1 (May 2018).

**Comment by bobbrow** [comment]
We understand that this can cause issues when the file is committed to source control, so we try very hard not to update it unless we absolutely have to.  We do not plan to change the way this works right now.
