### ISSUE TITLE
выдает ошибку при сборке

### ISSUE THREAD

**Issue by 0k8i8a0** [microsoft/vscode-cpptools#3352]
Issue Type: <b>Bug</b>

#include errors detected. Please update your includePath. IntelliSense features for this translation unit (C:\Users\nadin\Documents\My_Dz\g++ basic_program.cpp) will be provided by the Tag Parser.
????????????????

Extension version: 0.22.1
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-5300 APU with Radeon(tm) HD Graphics     (2 x 3391)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.19GB (3.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
Some `#include` can't be found. You might need to set your includePath and/or compilerPath settings, see https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md . Are you able to set those to get it working?

**Comment by Colengms** [comment]
There have been no updates on this issue for several months.  The initial reporter has not responded beyond the initial post.  Closing.  If there is still an issue here, please let us know - we can re-open it.
