### ISSUE TITLE
source is not available

### ISSUE THREAD

**Issue by yujqiao** [microsoft/vscode-cpptools#336]
Version : 1.71
OS: Windows10
When I were debugging with gdb(MinGW64), I got lines like this:
There was two tabs and the first one had correct code on it but the second one read "source x.cpp is not available."
![qq 20161106200119](https://cloud.githubusercontent.com/assets/20105061/20037526/cda7d360-a45b-11e6-8111-6e74eab48c0c.png)

**Comment by pieandcakes** [comment]
@Rapiz1 What that means is that the source file is not in the same location on disk as when the executable is compiled. Was this binary compiled and then moved?

**Comment by pieandcakes** [comment]
@Rapiz1 if you enable `"logging": {
                "engineLogging": true
            }` you can see where it is expecting the file versus where you have the file loaded.

**Comment by yujqiao** [comment]
@pieandcakes I think it was caused by the path with Chinese character. I renamed the folder in English then everything works fine. It's a bug.

**Comment by pieandcakes** [comment]
@Rapiz1 I tried with GDB and if you provide a filename or path that contains Chinese characters, it looks like it does not respect that. This is probably an issue in GDB and would need to be fixed on that side.
