### ISSUE TITLE
How to remove wave lines under header files

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3361]
Currently we can set C_Cpp: Error Squiggles this property to enabled to remove wave line about compile errors but it can't remove wave lines under wrong header files.  Are there some ways to remove them？

Regards,
Lennon

**Comment by sean-mcmanus** [comment]
There is not a setting for this yet (other than intelliSenseEngine "Disabled"). I remember a previous request for this but I'm unable to locate it.

**Comment by sean-mcmanus** [comment]
Fixed with 0.23.0-insiders -- the "Disabled" errorSquiggles option will remove all the squiggles.

**Comment by Lennon925** [comment]
> Fixed with 0.23.0-insiders -- the "Disabled" errorSquiggles option will remove all the squiggles.

Thanks so much
