### ISSUE TITLE
'go to defintion' error when allowing fuzzy intelliSense

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3362]
**Type: LanguageService**

**Describe the bug**
- VS Code Version: 1.3.1
- C/C++ Extension Version: 0.21

**To Reproduce**

When file can't find header file, I click the lightbulb and select 'allow fuzzy intelliSense' and then local variables can't go to definition.

#include "tddest.h"
#include <stdio.h>

void testLocalVariable(int count)
{
  int ii = count;  //can't go to definition.
}

**Comment by sean-mcmanus** [comment]
Local variable Go to Definition only works with the non-fuzzy "Default" IntelliSense engine, not the "Tag Parser" one.

If you can't find headers, you could set the intelliSenseEngineFallback to "Disabled" instead of doing the "allow fuzzy IntelliSense".
