### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jgm1997** [microsoft/vscode-cpptools#3363]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.21.0`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/djgowlin/ms-vscode.cpptools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by WardenGnaw** [comment]
Missing attachment and merging with https://github.com/Microsoft/vscode-cpptools/issues/3213
