### ISSUE TITLE
Go to definition not working on one machine (works fine on another)

### ISSUE THREAD

**Issue by fiveohhh** [microsoft/vscode-cpptools#3364]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 build 17763
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.
Go to definition is not finding any definitions that are in my current workspace.   Iooking at the logs it looks like the extension knows to look in the folder, for files, but I see no mention of any of the files in my workspace being parsed.

Here is my `c_cpp_properties.json`
~~~
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "C:/gitRepos/my-code/**",
                "${workspaceFolder}/../nRF5_SDK_15.0.0_a53641a/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "NRF_MODULE_ENABLE_ALL"
            ],
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
~~~
And here is what I see in the logs after a database reset:
~~~
cpptools/resetDatabase
cpptools/resetDatabaseReady
Database safe to open
Code browsing service initialized
Populate include completion cache.
Discovering files...
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.16.27023/INCLUDE
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.16.27023/ATLMFC/INCLUDE
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UM/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UCRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/SHARED/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/WINRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/CPPWINRT/
  Processing folder (recursive): C:/GITREPOS/MY-CODE/
  Processing folder (recursive): C:/GITREPOS/NRF5_SDK_15.0.0_A53641A/
  Discovering files: 17488 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
~~~
The rest of the log is full of entries that say `tag parsing file: C:\GITREPOS\NRF....`
but there are no entries related to the the any of the files in `MY-CODE`, or any of the Visual Studio paths.

**To Reproduce**
Thist works as expected on another computer

**Expected behavior**
I would expect the tool to parse files it finds in `C:/GITREPOS/MY-CODE/`.  It correctly does this on another machine that has the exact same codebase

**Additional context**
The only errors I see in the cpp tools logs look like this: `Tag parsing encountered a error, but it may not matter. Let us know if symbols in the file can't be found: `.  Other wise the log ends with:
~~~
  Parsing: 1861 files(s) processed
Done parsing remaining files.
Database safe to open
~~~

When trying to go to definition on symbols in the nrf folder, things work as expected.

**Comment by bobbrow** [comment]
Which folder is your `${workspaceRoot}`?  Are you opening the same folder on both machines?

**Comment by fiveohhh** [comment]
`${workspaceRoot}` = ` C:/gitRepos/my-code/` on both machines.  I had `${workspaceRoot}` in `c_cpp_properties.json` originally.  I tried swapping it out with the full path to see if it fixed it.

**Comment by sean-mcmanus** [comment]
Do you have any files.exclude settings set? We check those for exclusions before parsing files.

**Comment by fiveohhh** [comment]
Not that I know of.  Where would that be set?  It's not in `settings.json` or `c_cpp_properties.json`.

**Comment by sean-mcmanus** [comment]
In settings.json. Setting the loggingLevel to the hidden value of `"7"` may help diagnose things further.

Does your workspace folder have .cpp files? We only parse source files initially, and then parser header files only if they are #included by source files.

You could try adding the following to your c_cpp_properties.json (if you want to force the headers to be parsed):

```
"browse": {
"limitSymbolsToIncludedHeaders": false
}
```

**Comment by fiveohhh** [comment]
I set the debugging to `7` and now I see this output.

> update_file_if_needed: C:\GITREPOS\MY-CODE\SOME_DIR\MY_SOURCE.C
  File no longer exists.

But that file does indeed exist.  I can copy/paste the same path into explorer and the file opens up.

**Comment by fiveohhh** [comment]
I think I got this figured out.  It's related to #1994.  When I manually set the case insensitivity to false for all the folders my source was in, things started working.  

The original repository (that wasn't working) was cloned from within wsl.  The computer I was trying to duplicate the situation on was synced to that directory using synctrazor.  Synctrazor must not copy that attribute over and therefor used a default of case insensitive.

**Comment by sean-mcmanus** [comment]
@fiveohhh Yeah, good catch.

**Comment by bobbrow** [comment]
In case you haven't already, don't forget to switch the loggingLevel to one of the regular values.  `"7"` can log a lot of stuff and slow down the extension.

**Comment by fiveohhh** [comment]
I did forget to undo that, thanks!
