### ISSUE TITLE
cannot include the header files even with path added.

### ISSUE THREAD

**Issue by geyan3566** [microsoft/vscode-cpptools#3366]
Type: General
**Input information below**

**Describe the bug**
- OS and Version: macOS Mojave 10.14.3
- VS Code Version: Version 1.32.3 (1.32.3)
- C/C++ Extension Version: 0.22.1

**To Reproduce**

IncludePath setting issue: 
Even though I added the path to the header files, the error is still there.
There first pic shows the error, second is my configure file. 

<img width="586" alt="Screen Shot 2019-03-26 at 18 42 49" src="https://user-images.githubusercontent.com/33760486/55038420-2c48dd80-4ff7-11e9-9c91-d1272f627014.png">

<img width="549" alt="Screen Shot 2019-03-26 at 18 43 01" src="https://user-images.githubusercontent.com/33760486/55038427-31a62800-4ff7-11e9-9440-834d644914ae.png">

**Comment by sean-mcmanus** [comment]
What does the error squiggle say? Which header can't be found?

**Comment by geyan3566** [comment]
Thanks for you reply.
Detail of the error message is:
"cannot open source file "_config.hpp" (dependency of "fem.hpp")".
config.hpp is another header file locates on `mfem/config`, `fem.hpp` locates in `mfem/fem`.
The header file that cannot be find is "fem.hpp" which is in the same folder of the source file I opened.(This is shown in figure 1.)
Figure 2 is the c_cpp_properties.json file.

Thanks for your help.
Ge

**Comment by geyan3566** [comment]
Sorry I omitted another error message. All error messages:
```
#include errors detected. Please update your includePath. IntelliSense features for this translation unit (/Users/geyan/Downloads/mfem/fem/intrules.cpp) will be provided by the Tag Parser.
"cannot open source file "_config.hpp" (dependency of "fem.hpp")".
```

**Comment by bobbrow** [comment]
It can't find `_config.hpp`. I think you need to add `${workspaceFolder}/config` to your include path.

**Comment by geyan3566** [comment]
> It can't find `_config.hpp`. I think you need to add `${workspaceFolder}/config` to your include path.

It's not because of `${workspaceFolder}/config`, even though I added it. `_config.hpp` looks like a temporary file of `config.fpp`.

**Comment by sean-mcmanus** [comment]
Did you intend to use "${workspaceFolder}/**"? The two asterisks is required for recursive includes. The one asterisk will get you a non-recursive browse.path (folders under ${workspaceFolder} won't be parsed for global symbols).

**Comment by geyan3566** [comment]
Yes I changed it to double stars, but the error message is still there.

**Comment by sean-mcmanus** [comment]
What is the path to _config.hpp? I don't understand what you mean by "looks like a temporary file of config.fpp".

**Comment by geyan3566** [comment]
The working folder is `mfem` and `config.hpp` locates in `mfem/cofig`, in which there is no `_config.hpp`. 
My friend got the same source code from here `https://github.com/mfem/mfem.git`, but when he open `mfem` as working directory, there is a `_config.hpp` automatically generated in `config` folder.

**Comment by sean-mcmanus** [comment]
Our extension does not generate any _config.hpp file -- it must be some external build process or tool. Or am I misunderstanding?

If you don't need that file, you could change intelliSenseEngineFallback to disabled to have IntelliSense work without the header, although any type info provided by that missing file might causes errors.

**Comment by geyan3566** [comment]
Sorry for the confusion and late reply. 
It turns out `_config.hpp` will be automatically generated after compile.

Thanks a lot.
