### ISSUE TITLE
C_Cpp.intelliSenseCachePath doesn't resolve tilde or env for home directory

### ISSUE THREAD

**Issue by rewrking** [microsoft/vscode-cpptools#3367]
**Type: LanguageService**

**Describe the bug**
- OS and Version: All (tested on Win/Mac)
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.
"C_Cpp.intelliSenseCachePath" setting does not respect the tilde ~ as the home directory path, nor does it take ${env:HOME}, ${env.HOME}, ${HOME}... ${env:HOME} I think is the correct syntax, but wanted to cover my bases.

**To Reproduce**
1. Open a terminal (use git-bash on windows), go to ~/.vscode and type "mkdir cpptools-cache", or create the folder through explorer/finder
1. Go into settings.json, add "C_Cpp.intelliSenseCachePath" : "~/.vscode/cpptools-cache" 
or "C_Cpp.intelliSenseCachePath" : "${env:HOME}/.vscode/cpptools-cache"
3. Reload the window with a project open
4. Delete the ipch folder currently in the project directory
5. Open some cpp files
6. Notice the ipch folder generates in the project directory's .vscode folder again.

**Expected behavior**
The extension should resolve the home directory and place its ipch stuff there instead of the project directory's .vscode folder. Instead, it does nothing, and cache files continue to be created in the project's .vscode folder.

**Additional context**
This is a pretty annoying. Personally, I'd prefer that the extension didn't clutter up my project folders with cache files and instead default to some other folder I don't know of or care about (Roaming for instance), instead of having to configure yet another setting to get them out of the project directory.

**Comment by sean-mcmanus** [comment]
Environment variables in the intelliSenseCachePath should expand with the latest Insiders: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.22.2-insiders .

**Comment by rewrking** [comment]
Works great. Thanks!
