### ISSUE TITLE
Can I configure tasks.json,launch.json for certain language?

### ISSUE THREAD

**Issue by yujqiao** [microsoft/vscode-cpptools#337]
I usually work on single files, which are not in a folder. So when I create a new file, I will have to write the launch.json and tasks.json again. Is there any way to configure task. Is there any way to solve this?

**Comment by pieandcakes** [comment]
@Rapiz1 That would probably be a question for [VSCode](https://github.com/microsoft/vscode/issues) as they control where launch.json and task.json are laid out and used.
