### ISSUE TITLE
Intellisense only giving suggestions once per line of code

### ISSUE THREAD

**Issue by griffin895** [microsoft/vscode-cpptools#3372]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10.0.17763 
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them): None

Problem: Intellisense is not giving any suggestions for struct contents after having already used it once in a line of code.

**To Reproduce**

1. Copy:
```c
struct numOne {
    int val_one;
};

struct numTwo{
    int val_two;
};

int main(int argc, char** argv)
{
    struct numOne one;
    struct numTwo two;

    one.val_one = 1;
    two.val_two = 2;

    int result = ...

    return 0;
}
```

2. Try setting `int result = one.val_one + two.val_two;`

**Expected behavior**

Expected intellisense to give suggestions when typing both 'one' and 'two' however, suggestions only appear for 'one'.
**Screenshots**
Working properly for 'one':

![1](https://user-images.githubusercontent.com/29279944/55127980-ef0c4a80-50df-11e9-8639-f960d08a5d5d.jpg)

Identifies struct numTwo two:
![2](https://user-images.githubusercontent.com/29279944/55127996-077c6500-50e0-11e9-9f4e-73876add7cee.jpg)

Fails to offer any suggestions (cursor hidden at end of val for next two SS):
![3](https://user-images.githubusercontent.com/29279944/55128016-18c57180-50e0-11e9-9d8d-c48039d0d770.jpg)

ctrl+space results in no suggestions as well:
![4](https://user-images.githubusercontent.com/29279944/55128019-21b64300-50e0-11e9-8133-64182a08dd5f.jpg)

**Additional context**

**Comment by sean-mcmanus** [comment]
This is bug https://developercommunity.visualstudio.com/content/problem/407956/cc-intellisense-no-member-list-appears-after-typin.html . Please upvote that issue so they can prioritize fixing it (you should be able to login via your GitHub account, you may have to click some links to see that option).

It only repros with .c files.

The previous VS Code C++ issue is https://github.com/Microsoft/vscode-cpptools/issues/2184.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 .
