### ISSUE TITLE
IntelliSense will search the history? i don't want it

### ISSUE THREAD

**Issue by mtllyb** [microsoft/vscode-cpptools#3374]
**Type: LanguageService**

**Describe the bug**
- OS and Version: ubutnu16.04
- VS Code Version: 1.32.3
- C/C++ Extension Version:0.22.1
- bug: 
Because i usually make a copy for backup, after i make a copy of the ${workspaceFolder}, and then i opened the original folder, i will find two defines, which  makes me so upset~

**Screenshots**

![two_defines](https://user-images.githubusercontent.com/18020534/55146570-ccca0980-517f-11e9-8b3b-72bd41873360.png)

**Comment by sean-mcmanus** [comment]
We need more info. Where is the copy made in relation to the `${workspaceFolder}`? How is the copy made? I can't tell from your screenshot what the 2 paths are.

We have a database that can be reset using the Reset IntelliSense Database command.

**Comment by mtllyb** [comment]
* Thank you for response. The copy is made in the parent directory of ${workspaceFolder}. And I just use the copy cmd(of course i delete the .vscode folder in the copy).
* For example, my ${workspaceFolder} is [small_exe_auto_drop], first i make a copy(small_exe_auto_drop_copy) in the pwd and delete the .vscode folder in the copy, then  i opened the the ori folder(small_exe_auto_drop), and the IntelliSense searcedh the declaration in the copy(small_exe_auto_drop_copy). BUT i just want the IntelliSense search the declaration in the ori folder.
* Will the relationship picture below help?
![11](https://user-images.githubusercontent.com/18020534/55271063-1c284b00-52e2-11e9-81d9-c2336a20ee70.png)

**Comment by sean-mcmanus** [comment]
I'm not able to repro the bug. It seems like a parent of your ${workspaceFolder} is being added to your includePath or browse.path. Can you [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and see if a parent folder is being used, i.e. "Processing folder (recursive):" logs?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
