### ISSUE TITLE
C language switch syntax wrong format with Format Document tool

### ISSUE THREAD

**Issue by rikonaka** [microsoft/vscode-cpptools#3376]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux x64 4.15.0-46-generic
- VS Code Version: 1.32.3
- C/C++ Extension Version: gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
- Other extensions you installed (and if the issue persists after disabling them): too many
- A clear and concise description of what the bug is.

This is the switch syntax for vscode autocompletion (normally, when we write C, it is also the right format).

![image](https://user-images.githubusercontent.com/13602602/54874447-85154c00-4e26-11e9-95d6-72ea3f471f71.png)

But when I use the Format Document tool, the format of the entire statement becomes like this.
![image](https://user-images.githubusercontent.com/13602602/54874456-ae35dc80-4e26-11e9-92ae-5e39041c58dc.png)

This does not seem to be normative.

**To Reproduce**

1. Go to a C file.
2. Click on right. 
3. Use the `Format Document` tool provided by the right button.
4. See error.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
We just call into clang-format which has configurable options described at https://releases.llvm.org/6.0.0/tools/clang/docs/ClangFormatStyleOptions.html .

You can change that switch indentation via changing your C_Cpp.clang_format_style to something like:
```
{ BasedOnStyle: LLVM, UseTab: "Never", IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: true, ColumnLimit: 0 }
```

i.e. the "IndentCaseLables" controls that.

**Comment by sean-mcmanus** [comment]
Is this a request to change our snippet to match the default formatting? ....I answered this myself as "yes".

**Comment by sean-mcmanus** [comment]
It looks like our we should change our snippet to not indent the case labels, to match the default formatting and VS.

It's possible our other default snippets have similar formatting inconsistencies.

UPDATE: Our snippets had several other formatting "bugs" and I fixed our default formatting to not indent class access modifiers.

**Comment by rikonaka** [comment]
Thanks for responding.

**Comment by sean-mcmanus** [comment]
The formatting and snippet issue has been fixed with the latest Insiders: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.22.2-insiders .
