### ISSUE TITLE
it goes to declaration instead of definition

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3378]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

1. I add two folders to a new workspace, one folder is "cpps" and another one is "headers"
2. In "apps" folder there is a cpp file called "cpp_test.cpp" and in "headers" folder there are two files, "header_test.h" and "header_test.cpp".
3. code as following:

**cpp_test.cpp(in cpps folder)**
#include "../headers/headers_test.h"
int cpps_test()
{
   ClassA *obj = new ClassA();
   obj->test();        **//"go to definition" on function "test" will go to declaration instead of def.**
}

**headers_test.h(in headers folder)**
class ClassA {
public:
    ClassA(){}
    int test(); 
};

**"headers_test.cpp(in headers folder)**
#include "test.h"
ClassA::test(){
   int mm = 0;
}

This is a bug? Are there some ways to resolve this issue?

**Comment by Lennon925** [comment]
Then I removed "headers" folder from my workspaces. "go to definition" on function "Test" is right. But after I close and reopen vscode, it didn't work again.

**Comment by Lennon925** [comment]
> Then I removed "headers" folder from my workspaces. "go to definition" on function "Test" is right. But after I close and reopen vscode, it didn't work again.

I tried operators above for some times and it seems that it's not stabled. Sometimes it went to declarations and sometimes it went to declarations.

**Comment by sean-mcmanus** [comment]
Should be fixed 0.23.1.

**Comment by aneox** [comment]
I am working in VSCode Version: 1.49.3 and have this bug, macOS 10.15.4

When I click "Go to definition", sometimes it went to declarations and sometimes it went to the definition.
No error or warning messages.

c_cpp_properties.json

```
{
  "configurations": [
    {
      "name": "vscode_stm32_c_cpp_properties",
      "compilerPath": "/Users/AneoX/compilers/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-gcc",
      "includePath": [
        "${workspaceRoot}/Inc/",
        "${workspaceRoot}/Drivers/cmsis/",
        "${workspaceRoot}/Drivers/STM32F0xx_StdPeriph_Driver/inc/"
        // "${workspaceRoot}/**"
      ],
      "browse": {
        "path": ["${workspaceFolder}"],
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": "${workspaceFolder}/.vscode/browse.vc.db"
      },
      "cStandard": "c11",
      "cppStandard": "c++17",
      "intelliSenseMode": "gcc-arm",
      "configurationProvider": "ms-vscode.cmake-tools",
      "defines": ["USE_STDPERIPH_DRIVER", "STM32F042"]
    }
  ],
  "version": 4
}
```

**Comment by aneox** [comment]
@sean-mcmanus please reopen
