### ISSUE TITLE
headers are not picked up by IntelliSense

### ISSUE THREAD

**Issue by davydden** [microsoft/vscode-cpptools#3379]
**Type: LanguageService**

I have the following settings:
```
        {
            "name": "Mac",
            "compileCommands": "${workspaceRoot}/_build/compile_commands.json",
            "includePath": [
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                 "<external-lib>/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                 "<external-lib>/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17"
        },
```

that is, I point to `cmake`-generated compile commands and external include directories both in 
however `IntelliSense` complains about missing headers both in `browse/Path` and in `includePath` sections, but still `IntelliSense` can't find the source file. 

```
cannot open source file "blabla.h"
```

I am quite certain I don't have a typo in the path.

Looking at debug output I see
```
  Processing folder (recursive): <external-lib>/include
```
so it should be processing headers, AFACT.

**Describe the bug**
- OS and Version: 10.14.4
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1

**To Reproduce**

I am not quite sure how to reproduce this as I actually have other projects which use the same external lib and IntelliSense does the job right. As far as I can tell, `c_cpp_properties.json` are almost identical for those case. 

**Expected behavior**

IntelliSense should pick up external headers.

p.s. as mentioned [here](https://github.com/Microsoft/vscode-cpptools/issues/2940#issuecomment-448340906), I think ideally everything should be picked up from `compile_commands.json`.

**Comment by bobbrow** [comment]
Yes, IntelliSense should pick up external headers.  They should all be defined in `compile_commands.json`.  Unfortunately, we didn't get to this issue earlier.  If you are still having issues with the latest version of the extension, please share the compile commands entries that are not working for you and we can reopen an investigation.  Thank you!
