### ISSUE TITLE
Editing impossible due to lag in response on editing...

### ISSUE THREAD

**Issue by jkhoogland** [microsoft/vscode-cpptools#3380]
**Type: LanguageService**
C++

**Describe the bug**
- OS and Version: OSX 10.12.6
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1
- Since upgrading to the latest version of the C++ extension, there is a noticable lag in editing c++ files. This looks like a bug to me, it makes the use of the editor effectively impossible as every time you type a character, the extension starts doing some work and you are waiting to get control back for a second or more....

**To Reproduce**
Editing c++ files

**Comment by bobbrow** [comment]
Our caching change was incompatible with Sierra and had to be disabled.  This appears to have had some unintended consequences on older versions of macOS. Are you able to upgrade to High Sierra or Mojave?  Another option is to revert the extension back to 0.21.0 while we investigate.

What would you say is the approximate size** of the files you are editing?

** (When we say "size" we  mean the size of the .c/.cpp you are editing plus the included headers and their dependencies. We don't expect you to count lines or the number of the dependencies, so a qualitative assessment is sufficient. e.g: "source files have lots of includes/dependencies" or "source files have few dependencies")

**Comment by sean-mcmanus** [comment]
The change in squiggling behavior is unrelated to the caching change so it's not an "unintended consequence" of that, although we would expect the caching to help.

The "size" of the translation unit could be estimated via the memory usage of the Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin process.

I'm thinking we should add some setting to make the squiggle updating occur less often for cases where it is taking too long (or maybe we wouldn't need a setting if we can detect the update slowness ourselves)

**Comment by jkhoogland** [comment]
Thank you for the quick response!
I will have a look at updating to a new OSX.
In the meantime I will revert back to the previous version.

**Comment by Colengms** [comment]
@jkhoogland I suspect this has since been addressed.  If you are still seeing an issue, please re-open.
