### ISSUE TITLE
Support configuration file to disable/enable services

### ISSUE THREAD

**Issue by manhnt9** [microsoft/vscode-cpptools#3384]
Extension uses a large amount of system resources. I think it's better to let user disable features that they don't want.

**Comment by sean-mcmanus** [comment]
You can. Setting C_Cpp.intelliSenseCacheSize to 0 can reduce the disk space usage and setting C_Cpp.intelliSenseEngine to "Disabled" can disable the CPU usage. Is there some other disabling you wanted?

**Comment by manhnt9** [comment]
Thanks @sean-mcmanus.
My VSCode uses a lot of RAM, I think the extension is involved, like storing IntelliSense for project. Is there any setting that can help me with this?

**Comment by sean-mcmanus** [comment]
Which process is using RAM? I assume Microsoft.VSCode.CPP.IntelliSense.Msvc, right? The setting to disable the process from running is C_Cpp.intelliSenseEngine "Tag Parser", but it gives an inferior experience.

**Comment by manhnt9** [comment]
I'll try and see if it improves the situation. Thank you!
