### ISSUE TITLE
formatter doesn't work by default on Linux Mint 19.1

### ISSUE THREAD

**Issue by mattearly** [microsoft/vscode-cpptools#3388]
formatter doesn't work by default on Linux Mint 19.1 MATE. It is a flatpak version offered in Software Manager.

I went and got the official version of vscode from [code.visualstudio.com](https://code.visualstudio.com/download) deb64 and the formatter works fine on there.

**Comment by sean-mcmanus** [comment]
I don't understand. What is a flatpack version? I don't understand how installing VS Code fixed the issue. Do you mean the clang-format we install doesn't run? Usually this is caused by missing shared library dependencies that we expect.

**Comment by eszlari** [comment]
@mattearly You should open this issue under https://github.com/flathub/com.visualstudio.code/issues !

**Comment by eszlari** [comment]
This is fixed now: https://github.com/flathub/com.visualstudio.code/commit/7246c67e16ee2b4245ed3418fb33ea6c8d72fd1f

**Comment by mattearly** [comment]
@sean-mcmanus I'm not 100% sure what the flatpak means other than it is a packaged version in the Software Manager in some Linux Distros. https://flatpak.org/

closing as it appears resolved
