### ISSUE TITLE
Cannot attach docker container for debugging on Windows 10

### ISSUE THREAD

**Issue by adashen** [microsoft/vscode-cpptools#3389]
Type: Debugger

![image](https://user-images.githubusercontent.com/1872137/55305183-c8ecfe80-5481-11e9-90d5-8883717dc41c.png)

**Describe the bug**
- OS and Version: Windows 10 
- VS Code Version: 1.32.1
- C/C++ Extension Version: 0.22.1

**To Reproduce**
1. Clone repo https://github.com/andyneff/hello-world-gdb/
2. Add COPY ./* /src/ into the Docker file ( https://github.com/andyneff/hello-world-gdb/blob/master/Dockerfile) to avoid volume mounting
3. Build the docker image
4. Run the docker image with: 
docker run -it --rm --privileged --name hello_gdb <the image built in step 3>
5. Select "C++ Attach in hello_gdb container" debug configuration and debug.
6. Error shows up.

**Additional context**
Need reproduce the issue on Windows 10. It seems to be double quote issue of windows console when running the the process script.

**Comment by MaxKhlupnov** [comment]
Can duplicate this issue when building C++ module for Azure Iot Edge
-c: 1: -c: Syntax error: Unterminated quoted string
Command failed: "docker" "exec" "-i" "SampleModule" "sh" "-c" 'sh -c "uname && if [ $(uname) = \"Linux\" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) = \"Darwin\" ] ; then ps axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi"'
-c: 1: -c: Syntax error: Unterminated quoted string

**Comment by pieandcakes** [comment]
The example has it quoted correctly too. No idea what is missing.

**Comment by adashen** [comment]
Any update of this issue? It really block the user on windows for linux docker container

**Comment by pieandcakes** [comment]
This should be resolved as I've tested it with 0.25.0 and it works with @adashen's example after i add `procps` to be installed in the Dockerfile.

**Comment by pieandcakes** [comment]
It was fixed with https://github.com/microsoft/vscode-cpptools/commit/b763aa57d368e009300f4492e90684c0c25e4a52#diff-63bdf79ee71cadec1ca8f47ee4c87c0c .
