### ISSUE TITLE
Insiders 1.8.0: Updating C/C++ dependencies...  Failed at stage: downloadPackages

### ISSUE THREAD

**Issue by jonowells** [microsoft/vscode-cpptools#339]
Getting this warning when I start up VS Code with this package installed.

```
Updating C/C++ dependencies...

Failed at stage: downloadPackages
Error: Package manifest does not exist

Finished
```

**Comment by pieandcakes** [comment]
@jonowells Does the machine you have this running on have internet access? Its trying to download its dependencies which happens the first time the extension is activated.

**Comment by jonowells** [comment]
I definitely have an internet connection. I just tested it and I still have that message.

Could the packages could be in a corrupt state?

**Comment by pieandcakes** [comment]
@jonowells I just reinstalled the extension and I haven't seen that error. Would it be possible for you to remove the extension folder from ~/.vscode/extensions and reinstall it and see if it will download again? Can you tell me which OS you are running this on?

**Comment by jonowells** [comment]
10.12.2 public beta. Deleting the package from the extensions folder didn't fix it.

**Comment by jonowells** [comment]
I also tried running npm manually. I get this:

```
...
npm WARN cpptools@0.9.2 No repository field.
```

**Comment by pieandcakes** [comment]
@jonowells The dependencies are not obtained through npm. They are downloaded through an `https-proxy-agent` and the code is found in `~/.vscode/extensions/<extension-folder>/out/src/packageManager.js`. The URLs it is trying to download are in the `package.json` file at the bottom.

Can you see if you can access `https://go.microsoft.com/fwlink/?LinkID=817244` on that machine? That's one of the items it is attempting to download.

**Comment by jonowells** [comment]
I see. That link downloads as it should.

**Comment by pieandcakes** [comment]
@jonowells Can you tell me which version of VSCode you are running?

**Comment by jonowells** [comment]
So I tried downloading the stable VSCode build instead of insiders. A completely clean install except for some preferences leftover. The plugin installs fine and everything works as it should. I noticed that one of the packages that are installed is mono develop. I also have the C# and some unity plugins installed on my insiders build. maybe there is a conflict?

**Comment by jonowells** [comment]
1.8.0-insiders

**Comment by pieandcakes** [comment]
@jonowells Looking at the block of code where it is failing, it is expecting to be able to get our extension from vscode.extensions.getExtension. It might be an issue in Insiders. I'll give that a shot later today and let you know. 

We also download mono but that is downloaded inside the extension path and we use it to launch our debugger extension. There should not be a conflict since we use the version we lay down and it should only be used by our extension and not affect any other instance of mono.

**Comment by jonowells** [comment]
I see. Thanks for taking a look. If I have more info I'll post it here.

**Comment by pieandcakes** [comment]
@jonowells Looks like an issue with VSCode insiders version. I downloaded the latest Insiders on my Windows machine and tried to install the extension and I'm getting the same error. I'll see if I can file an issue with them.

**Comment by pieandcakes** [comment]
@jonowells Looks like its an issue that they have fixed: https://github.com/Microsoft/vscode/issues/14763

**Comment by jonowells** [comment]
Awesome!
