### ISSUE TITLE
how to block one file("go to definition")

### ISSUE THREAD

**Issue by bowenee** [microsoft/vscode-cpptools#3391]
when click "go to definition", vs code shows a popup(two options for choice), two files(c source file) have one same function name, how to exclude one of them?

![](https://user-images.githubusercontent.com/5562854/55327574-f0ad8800-54bc-11e9-8d38-0d91a2b28009.png)

**Comment by sean-mcmanus** [comment]
Can you add the folder you want to exclude to files.exclude?

**Comment by bowenee** [comment]
where is “files.exclude”？

**Comment by bowenee** [comment]
Hi Sean,
I have exclude this file already, 
but "go to definition" still show that popup(two option)：
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/5562854/55370643-b203e600-552d-11e9-81bb-0bbbf2342e7f.png">

**Comment by sean-mcmanus** [comment]
By default we don't accept files.exclude filters that operate on files, only folders, so you should remove the "/*" from your setting or change the C_Cpp.exclusionPolicy to "checkFilesAndFolders" (not recommended for performanc reasons).

**Comment by bowenee** [comment]
still have this popup:
![image](https://user-images.githubusercontent.com/5562854/55382115-6bc37c80-5557-11e9-8273-7cb2928b3850.png)

**Comment by sean-mcmanus** [comment]
Hmm, that is strange -- it works for me. Did you do a Reset IntelliSense Database? It may not have processed the files.exclude change yet. Otherwise, can you [enable logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and see where the excluded folder is being referenced?

**Comment by bowenee** [comment]
How to reset intelliSense database?

**Comment by sean-mcmanus** [comment]
There's a command "Reset IntelliSense Database".

**Comment by bowenee** [comment]
where is it ? I cannot find that command.

**Comment by sean-mcmanus** [comment]
See the screenshot (after doing View->Command Palette).

![image](https://user-images.githubusercontent.com/19859882/55768051-1cd28700-5a30-11e9-848c-63b3abaf691a.png)

**Comment by bowenee** [comment]
Got it. This issue has been solved.
Thanks for your help, Sean.
