### ISSUE TITLE
Detecting Block Comments for functions

### ISSUE THREAD

**Issue by tabedzki** [microsoft/vscode-cpptools#3392]
In a recent update, C/C++ tools enable comments that were immediately before a variable or function to be displayed if you hovered over a non-declaration instance of the variable or function (could hover over `foo()` and see what the comments before `foo()` was). Example:

```
// A useful comment goes here
void foo(int bar){
// Work here
}
```

I think it would be useful if the extension could determine block comments that are done in the following way and parse out the extra `//` characters like in: 

```
////////////////////////////////////////////////////
// Add segments to each processors density fields //
////////////////////////////////////////////////////
void foo(int bar){
// Work here
}
```
Currently it removes the first two of each line and that is it. 

Also, can it be made possible to see if there is a comment block two lines above a function definition? I am currently working with inherited code that followings a format like this:

```
////////////////////////////////////////////////////
// Add segments to each processors density fields //
////////////////////////////////////////////////////

void foo(int bar){
// Work here
}
```

Since it is not immediately before the function, the extension does not see the command block and when you hover over, does not inform you what the function does.

Thank you in advance.

Edit: Another situation that might be useful to consider:

``` 
/* ---------------------------
  Comment here
  ----------------------------*/

void foo(int bar){
// Work here
}
```

**Comment by sean-mcmanus** [comment]
Sounds good to me. Not sure yet when we'll get around to improving the doc commenting (maybe May?).

**Comment by bobbrow** [comment]
Just for context, the reason we didn't look past an empty line is because it could potentially be a section comment which doesn't apply to the current function, but rather the next N functions.

**Comment by tabedzki** [comment]
Ahhh ok. Would it be possible to make that a toggle set to false by
default? I could still see reading a block for general discription useful
even if it isn't for the specific function.

**Comment by bobbrow** [comment]
Sure, we can reevaluate our decision here.  Just note that Visual Studio behaves the same way and we model most of our behavior on Visual Studio so we'll want to achieve consensus across the two products.

**Comment by sean-mcmanus** [comment]
Yeah, VS correctly removes the `//` from around the comment, and preserves new lines, (unlike us), but uses blank newlines to disassociate the comment, as Bob mentioned.
