### ISSUE TITLE
Add forceCaseSensitivity to c_cpp_properties.json and C_Cpp.default.*

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3394]
I would like to override the default and be able to force it one way or another.  If possible, by individual folder, but for now, a global setting would work for me.

Something like this would work:
~~~
"forceCaseSensitivitySettings": "CaseSensitive"

or 

"caseSensitiveSetting: [
     "some/path/": "CaseSensitive",
     "some/other/path/": "NotCaseSensitive"
  ] 
~~~

_Originally posted by @fiveohhh in https://github.com/Microsoft/vscode-cpptools/issues/1994#issuecomment-478607690_

UPDATE: But maybe it's better to use "fsutil.exe file queryCaseSensitiveInfo <folder>" to detect it, but I'm worried about the performance hit...maybe we can just call that on the root folder, and if it's true then call it for all the subfolders (or assume the subfolders are also case sensitive?). Let us know if anyone knows a C++ Win32 API for checking this (I couldn't find any).

**Comment by bobbrow** [comment]
We store filenames in a canonicalized format. Doing a stat on those file paths (which have their casing changed by us) should allow us to detect whether we are in a case-sensitive folder or not.  Ideally we would be able to detect this without adding any new settings.

**Comment by sean-mcmanus** [comment]
Yeah, that sounds like it should work.

**Comment by fiveohhh** [comment]
Is there another issue to track that feature?

**Comment by sean-mcmanus** [comment]
@fiveohhh Yeah, the original issue: https://github.com/Microsoft/vscode-cpptools/issues/1994 .
