### ISSUE TITLE
malloc undefined with IntelliSense

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3396]
![1 jpg](https://user-images.githubusercontent.com/46044770/55371750-e7123780-5531-11e9-8bbd-ff4ae728b488.png)

I just enable logging for the extension by adding `"C_cpp.loggingLevel": "Information",` to `settings.json`
```
{
    "files.associations": {
        "*.tcc": "cpp",
        "cctype": "cpp",
        "clocale": "cpp",
        "cstdint": "cpp",
        "cstdio": "cpp",
        "cstdlib": "cpp",
        "cwchar": "cpp",
        "cwctype": "cpp",
        "codegnuglobal.executable": "D:\\GNU\\bin\\global.exe",
        "codegnuglobal.encoding": "cp936",
        "C_cpp.loggingLevel": "Information",
        "exception": "cpp",
        "initializer_list": "cpp",
        "iosfwd": "cpp",
        "iostream": "cpp",
        "istream": "cpp",
        "limits": "cpp",
        "new": "cpp",
        "ostream": "cpp",
        "stdexcept": "cpp",
        "streambuf": "cpp",
        "system_error": "cpp",
        "type_traits": "cpp",
        "typeinfo": "cpp",
        "algorithm": "cpp",
        "random": "cpp",
        "array": "cpp",
        "atomic": "cpp",
        "bitset": "cpp",
        "cfenv": "cpp",
        "chrono": "cpp",
        "cinttypes": "cpp",
        "cmath": "cpp",
        "codecvt": "cpp",
        "condition_variable": "cpp",
        "csetjmp": "cpp",
        "csignal": "cpp",
        "cstdarg": "cpp",
        "cstddef": "cpp",
        "cstring": "cpp",
        "ctime": "cpp",
        "cuchar": "cpp",
        "deque": "cpp",
        "forward_list": "cpp",
        "list": "cpp",
        "unordered_map": "cpp",
        "unordered_set": "cpp",
        "vector": "cpp",
        "rope": "cpp",
        "slist": "cpp",
        "fstream": "cpp",
        "functional": "cpp",
        "future": "cpp",
        "iomanip": "cpp",
        "memory": "cpp",
        "mutex": "cpp",
        "numeric": "cpp",
        "ratio": "cpp",
        "scoped_allocator": "cpp",
        "shared_mutex": "cpp",
        "sstream": "cpp",
        "thread": "cpp",
        "complex": "cpp",
        "tuple": "cpp",
        "utility": "cpp",
        "typeindex": "cpp",
        "valarray": "cpp"
    },
    "C_Cpp.errorSquiggles": "Enabled",
    "C_Cpp.intelliSenseEngineFallback": "Disabled",
}
```
but as the screen shot shows, there is not "C/C++" option in the log filter...
actually I have changed the c_cpp user settings `C_cpp: Intelli Sense Engine` from `default` to `Tag Parser`. that is because in the situation of `default` , functions in stdlib.h such as malloc() will be regard as an undefined symbol by the intellisense:
![1 jpg](https://user-images.githubusercontent.com/46044770/55373810-f183ff80-5538-11e9-8bf7-31c242e3b79d.png)

 
but this time intellisense works on other functions on whom didn't work before like strlen().
oh, it seems that there is some wrong with my options...
could you help me?

_Originally posted by @clover1967 in https://github.com/Microsoft/vscode-cpptools/issues/3390#issuecomment-478821784_

**Comment by sean-mcmanus** [comment]
@clover1967 -- what are you c_cpp_properties.json settings? You probably need to set your compilerPath correctly to get the system include paths set (where malloc is defined).

**Comment by Colengms** [comment]
@clover1967 Are you still seeing this issue?  I'm going to close this, since we haven't heard back from you.  If you are still seeing an issue, please re-open.
