### ISSUE TITLE
Go to Definition not working for C designated initializers

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3397]
@sean-mcmanus this problem still exists even if I removed C++ IntelliSense。I also tried on Ubuntu 18.04, F12 doesn't wrok on put_prev_task_fair(), enqueue_task_fair(), dequeue_task_fair(), .... But they actually have definition in the workspace.
![image](https://user-images.githubusercontent.com/38934793/55380147-de315e00-5551-11e9-841a-f13a4bbcd311.png)
![image](https://user-images.githubusercontent.com/38934793/55380153-eab5b680-5551-11e9-8406-8766637e5ea7.png)
![image](https://user-images.githubusercontent.com/38934793/55380166-f43f1e80-5551-11e9-8832-26ce3c382a5d.png)

_Originally posted by @Noctis-AKM in https://github.com/Microsoft/vscode-cpptools/issues/1657#issuecomment-478864063_

**Comment by sean-mcmanus** [comment]
What do you see when you hover over 0 in that file? Nothing or "(int)0"?

What is the type of something that the Go to Definition fails for? Does the Go to Def succeed on something with a simpler type? Does it succeed outside of a designated initializer?

Does the Go to Definition succeed if you change the C_Cpp.intelliSenseEngine to "Tag Parser"?

When I tried the repro, I got the definition, but it was falling back to the Tag Parser results even when the definition was in the same TU, so in your case the definition might be failing to be "tag parsed".

**Comment by Noctis-AKM** [comment]
for enqueue_task_fair() & dequeue_task_fair(), if I disable  "Intelli Sense Engine Fallback", F12 works。
![image](https://user-images.githubusercontent.com/38934793/55459570-7c8cf480-5622-11e9-9860-482d9272b8eb.png)

But it still doesn't work on put_prev_task_fair()
![image](https://user-images.githubusercontent.com/38934793/55459601-8ca4d400-5622-11e9-918b-7e5a71060afb.png)

Nothing changes if I choose  "C_Cpp: Intelli Sense Engine", all the 3 functions could not get definition.
![image](https://user-images.githubusercontent.com/38934793/55459867-21a7cd00-5623-11e9-9f21-06bc83d68fa1.png)
![image](https://user-images.githubusercontent.com/38934793/55459882-2bc9cb80-5623-11e9-86eb-4f0770882839.png)
![image](https://user-images.githubusercontent.com/38934793/55459896-33897000-5623-11e9-8fd4-6317fe7dc570.png)

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
