### ISSUE TITLE
Need VS 2015 x86 redistributable in order to work on Windows

### ISSUE THREAD

**Issue by savioret** [microsoft/vscode-cpptools#34]
If you are a Windows user (Win7 in my case), and don't have Microsoft Visual Studio Redistributable 2015 x86 installed on your system the extension does not work at all.
But the bug itself is the lack of information about it. Some people is complaining that the extension does not find any symbols and seems that this may be the cause.

If you manually try to run
`~\.vscode\extensions\ms-vscode.cpptools-0.4.2\bin\Microsoft.VSCode.CPP.Extension.exe`
You'll get a dialog with the error of "MSVCP140.dll" not found.

It would be great to get info about this error when the extension is being loaded from vscode, otherwise you are not aware that something went wrong.

Thanks !

**Comment by csholmq** [comment]
Sounds like a duplicate of https://github.com/Microsoft/vscppsamples/issues/9

**Comment by savioret** [comment]
Sure it is.
