### ISSUE TITLE
Issue with Visual Studio Code when i want to run C code 

### ISSUE THREAD

**Issue by FilipLaurentiu** [microsoft/vscode-cpptools#340]
"Updating C/C++ dependencies...
Failed at stage: getPlatformInfo
Error: Command failed: wmic os get osarchitecture
'wmic' is not recognized as an internal or external command,
operable program or batch file.

Finished"

this is what it say in the console.
![capture](https://cloud.githubusercontent.com/assets/20188480/20074092/7abd1070-a537-11e6-9777-e3cb035937b4.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20188480/20074093/7ad79c4c-a537-11e6-8104-61b0a558af77.PNG)

**Comment by pieandcakes** [comment]
@FilipLaurentiu  Which version of windows are you running this on? We're attempting to get the version of windows you are running on in order to download the correct dependencies by using `wmic`.

**Comment by FilipLaurentiu** [comment]
i use windows 10 pro 64 bit

**Comment by pieandcakes** [comment]
@FilipLaurentiu  Can you open a regular Command prompt and run `wmic os get osarchitecture` and let me know if it returns anything?

**Comment by FilipLaurentiu** [comment]
![capture](https://cloud.githubusercontent.com/assets/20188480/20075372/91edca78-a53c-11e6-933b-74418d217863.PNG)

**Comment by pieandcakes** [comment]
@FilipLaurentiu We have a fix to remove our requirement for `wmic` in our next release. 

In the meantime, if you want, you can add a `.catch((error) => { return "64-bit"; });` to the return statement in your `c:\users\<username>\.vscode\extensions\<extension_name>\out\src\platform.js` script at the end of the GetWindowsArchitecture method. It should be around line 43.

**Comment by FilipLaurentiu** [comment]
![capture](https://cloud.githubusercontent.com/assets/20188480/20076091/b6560d78-a53f-11e6-9c4d-5d449e1c9d93.PNG)

Like this ?

**Comment by FilipLaurentiu** [comment]
1 problem solve 👍  another problem appear 👎

**Comment by FilipLaurentiu** [comment]
![capture](https://cloud.githubusercontent.com/assets/20188480/20076320/a65b6ade-a540-11e6-954e-57ccc75a77d8.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20188480/20076321/a680bbcc-a540-11e6-9b01-4d554ca87552.PNG)

**Comment by FilipLaurentiu** [comment]
now when i want to run the code, this appear. Sorry if i am a a pain in the ass.

**Comment by pieandcakes** [comment]
@FilipLaurentiu  So the line in your launch.json where it says `"program":` you need to enter the location for your compiled executable. 

If you need to compile your executable, you'll need to configure a task through the `Task Runner`.

**Comment by FilipLaurentiu** [comment]
![capture](https://cloud.githubusercontent.com/assets/20188480/20078666/3ae49bb8-a54a-11e6-9fc5-3a5d340d1f0f.PNG)

i give up..

**Comment by pieandcakes** [comment]
You need to use `\\` instead of `/` symbols. plus, the program you are debugging is not gdb.exe, its your program. You do need to create another tag in there called `"miDebuggerPath": "c:\\mingw\\bin\\gdb.exe"` and specify in the `"program":` the result of your compilation of your c++ app (a.exe, or whatever you specify).

**Comment by FilipLaurentiu** [comment]
where is my compiled file? i don't know the location. i set up "miDebuggerPath": "c:\mingw\bin\gdb.exe" and work, but i don't specify in the "program" the right location. How to find this location ?

And thank you for you time and help !

**Comment by pieandcakes** [comment]
@FilipLaurentiu You need to manually compile your code either from the terminal command line or by adding a `task.json` from within VSCode. Its probably going to be easier for you to compile from the command line to get started. You will need to make sure your MinGW bin folder is in your path and you can go to the folder where your source code is located and use `g++ -g <your code files> -o <your executable name>`.

If you want to explore the `task.json` option, you can read about it from their docs located [here](https://code.visualstudio.com/Docs/editor/tasks).

**Comment by delmyers** [comment]
@FilipLaurentiu, since there has been no follow-up in a week on this issue, I'm going to assume that @pieandcakes helped you to solve your problems. I'm going to close this issue now.
