### ISSUE TITLE
Debugger Hangs

### ISSUE THREAD

**Issue by kprakasam** [microsoft/vscode-cpptools#3401]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: MacOS 10.14.4
- VS Code Version: 1.32.3 (1.32.3)
- C/C++ Extension Version:Name:  0.22.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.

Using Apple's lldb-mi cause cause debugger to hang after hitting break point.  lidb-mi bundled with VSCode and Xcode are same version. I switched to Xcode lldb-mi since it displayed the variables, containers size, etc. correctly

LLDB Machine Interface Driver (MI) All rights reserved
Version: 1.0.0.9
Version: GNU gdb (GDB) 7.4 
(This is a MI stub on top of LLDB and not GDB)
All rights reserved.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Test",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/bazel-bin/${input:testcase}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [
        {
          "name": "TEST_RUNDIR",
          "value": "${workspaceFolder}"
        },
        {
          "name": "TEST_SRCDIR",
          "value": "${workspaceFolder}"
        },
        {
          "name": "TEST_WORKSPACE",
          "value": "${workspaceFolder}"
        },
        {
          "name": "ENVOY_IP_TEST_VERSIONS",
          "value": "v4only"
        }
      ],
      "externalConsole": false,
      "MIMode": "lldb",
      "miDebuggerPath": "/Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi"
    }
}

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment]
There are a couple of changes in our clone of LLDB to fix hanging issues that has not been ported back to LLDB/master. We are still working on updating to the latest lldb.

**Comment by kprakasam** [comment]
I understand that it's better to use the lldb-mi bundled with vscode but can you guys do something to fix the way the container and object are displayed by the vscode's lldb-mi so there is no reason to use Apple's lldb-mi.
