### ISSUE TITLE
Option to turn off warnings for non-existent paths in c_cpp_properties.json?

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#3403]
For our scenario, lots of paths may be currently non-existent, but will be generated by a build. Also, since we are a customConfigurationProvider, having these warnings is unactionable and distracting for users. Is it possible to add a setting to disable these warnings?

This issue can potentially be mitigated if we use cpptools-api V2 to provide browse path configs, but we're currently blocked on https://github.com/Microsoft/vscode-cpptools-api/issues/7.

Also, we had discussed with @bobbrow the possibility of adding this setting to cpptools-api V3.

**Comment by sean-mcmanus** [comment]
I have a fix at https://github.com/Microsoft/vscode-cpptools/pull/3405 . Let us know if you see a problem with that.

**Comment by YassinMahmoudEl-Zouhery** [comment]
Hi

**Comment by YassinMahmoudEl-Zouhery** [comment]
what is the issue here

**Comment by sherryyshi** [comment]
Thanks @sean-mcmanus !

**Comment by HenokAddis** [comment]
Let us know when this makes it into code-insiders!

**Comment by sean-mcmanus** [comment]
@HenokAddis Sure, I'll respond to this thread when the fix is availabe -- we plan to release the fix in 0.22.2-insiders tomorrow, unless we find some last minute bug that delays it.

**Comment by sean-mcmanus** [comment]
The fix should be in Insiders now, via the enableConfigurationSquiggles field in c_cpp_properties.json or the C_Cpp.default.enableConfigurationSquiggles setting: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.22.2-insiders
