### ISSUE TITLE
Switch to using the installExtension command for offline/insider vsix installing

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3408]
They added it to 1.33.0.

vscode.commands.executeCommand('workbench.extensions.installExtension', vscode.Uri.file('path-to-vsix'));

The problem with the current method is that it has to locate the .exe, which may fail for various reasons (such as the .exe name not matching what we expect).

**Comment by tara-raj** [comment]
Fixed in Insiders 0.23.0
