### ISSUE TITLE
Red squiggles remain even on valid code

### ISSUE THREAD

**Issue by dwilliamson** [microsoft/vscode-cpptools#3418]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10.0.17134.590
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them): Bracket Pair Colorizer, Output Colorizer - **Issue persists after disabling them**

After rearranging the order of fields in a class and having intellisense respond with correct errors during removal, red squiggles remain after code is fixed and a successful build is performed:

![image](https://user-images.githubusercontent.com/1532903/55628388-7e80c000-57a8-11e9-9704-f9542c2c7cb3.png)

The issues are still present in the Problems window:

![image](https://user-images.githubusercontent.com/1532903/55628430-922c2680-57a8-11e9-9d65-78af36d51744.png)

Switching to the header file that declares the class it appears to be parsing a different version of the code than the one that was fixed:

![image](https://user-images.githubusercontent.com/1532903/55628494-c4d61f00-57a8-11e9-902a-5e52c2dd4385.png)

Attempted fixes:
* Completing further successful builds does not make them go away.
* Resaving the header file to force a rebuild does not make them go away.
* Cutting and repasting the `octree_build_thread` field makes them go away.

**Comment by dwilliamson** [comment]
Please see https://github.com/Microsoft/vscode/issues/71799, which has just been closed.

I'm at a loss how to report all these as they all seem to be interlinked and each repo is pointing to a fault in each other.

**Comment by sean-mcmanus** [comment]
Do you have any more repro details? Does this happen with a simple project? Is the IntelliSense process crashing? Does doing a reload window fix the issue?

**Comment by dwilliamson** [comment]
Some more information:

* This is a **big** refactor of a single type, causing a few hundred errors to show in the Problems view.
* The server is not crashing but it has crashed in the past.
* I have this error in my output: `Tag parsing encountered a error, but it may not matter. Let us know if symbols in the file can't be found` - it's parsing a Bash Script and failing, here.

Reloading fixes it temporarily but the problem comes back immediately after I build. When I fix a single 
compile error, it looks like this:

![image](https://user-images.githubusercontent.com/1532903/55871893-9464fb00-5b83-11e9-8e15-b195b09680f8.png)

Note both lines have been fixed here but the hover is reporting an error from an older version of the file only on the top line.

**Comment by sean-mcmanus** [comment]
Thanks for the additional info.

That "syntax error" message is not from out extension -- it appears to be from either another extension or your compiler. The 1st screenshot above was from our extension though. One way to tell is that our extension doesn't currently show any error codes like (C2051).

That tag parser error sounds okay, particularly for a bash file -- it shouldn't affect error squiggles at all, which is parsed differently.

**Comment by dwilliamson** [comment]
I have distilled this issue down to a VSCode-only problem by testing with clangd.

**Comment by rollsch** [comment]
This is a problem in VS2019 as well. Are the code analysis engines linked?

https://developercommunity.visualstudio.com/content/problem/817870/intellisense-lag-and-huge-number-of-false-red-squi.html

**Comment by sean-mcmanus** [comment]
@rolandh We share some code with VS, but the IntelliSense lag and stuck squiggles is a general symptom that could have a number of causes that could be different for VS Code.

Do you have a specific repro we could try?

**Comment by rollsch** [comment]
If you can do a screenshare I can show you our solution. It is a huge project that is full of proprietary information though so I cannot share it. Not sure if there is anyway to get you guys to look at that? These problems typically only occur in large solutions.

**Comment by host452b** [comment]
SAME ISSUE FOR THIS!!!

**Comment by host452b** [comment]
> Please see [microsoft/vscode#71799](https://github.com/microsoft/vscode/issues/71799), which has just been closed.
> 
> I'm at a loss how to report all these as they all seem to be interlinked and each repo is pointing to a fault in each other.

how do you fix for this problem, bro ?
