### ISSUE TITLE
VS Code Highlighting keywords incorrectly after update

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#3420]
This issue is actually, caused by the VS Code 1.33 update, but I'm posting it here as it might get greater visability by someone who knows C++ rather. Since updating to 1.33, code highlighting for C++ specifically has gotten much work. The biggest one is I have a typedef `COMM_Bool`, and the Bool part actually gets highlighted differently then the COMM_ part. In addition, some local variables are randomly now blue rather then white, but not all. It's very distracting. I've attached pics of these issues, older version on top, newer version on bottom.

Old

![BoolOld](https://user-images.githubusercontent.com/7727148/55640821-4023da80-5781-11e9-8eb7-72afcecbfbb2.PNG)
![BlueOldWakeup](https://user-images.githubusercontent.com/7727148/55640829-43b76180-5781-11e9-93bf-60d087103e7a.PNG)

New

![CppBool](https://user-images.githubusercontent.com/7727148/55640862-503bba00-5781-11e9-8dc6-3d1f75296c34.PNG)
![BlueNewWakeup](https://user-images.githubusercontent.com/7727148/55640867-529e1400-5781-11e9-8a26-f495d242330a.PNG)

I can move this issue to VS Code if you would like, but I think it will get lost there.

**Comment by sean-mcmanus** [comment]
VS Code switched to using the colorization parser from https://github.com/jeff-hykin/cpp-textmate-grammar/issues . Can you file a bug with that extension? Or I could file the bug for you. Fixes to that extension will get picked up by VS Code over time (not sure how often).

**Comment by ThadHouse** [comment]
I'll try and post an issue there, and I'm going to put an issue on vscode as well. The new parser is horrible, and it should be reverted. After playing with is for a day, I've probably found 10 more things that are very bad and make the experience much worse.

**Comment by ThadHouse** [comment]
https://github.com/jeff-hykin/cpp-textmate-grammar/issues/58
https://github.com/jeff-hykin/cpp-textmate-grammar/issues/59
https://github.com/jeff-hykin/cpp-textmate-grammar/issues/60

I created issues for the 3 major things I found, and will create more when I find them.

**Comment by ThadHouse** [comment]
I was able to use the extension from that repo to override the built in vscode default, and a newer version already had 2 of the 3 things fixed.
