### ISSUE TITLE
Intellisense quircks and general suggestions:

### ISSUE THREAD

**Issue by septag** [microsoft/vscode-cpptools#3427]
vscode: 1.33.0
cpp: 0.22.1
windows 10

First off, the new version builds lots of these ipch files everytime I open vscode, is this normal ? because it doesn't delete them and it consumes disk space pretty fast.

Also, it really bothers us when working with large files:  
the intellisense becomes dead-slow when you are writing code, because the extension seems to be rebuilding the database on every modification (the fire icon keep appearing) and it may take about 10..15 seconds to build it for some files. so essentially we have no intellisense when writing code!
I don't know what happens under the hood, but one suggestion would be to keep the current database and use it while the new one is being built.

EDIT: I have noticed that when we start vscode and start typing into a large file, intellisense update process (fire icon) is much faster. Working in vscode for some time, slows it down considerably.

Thank you!

**Comment by sean-mcmanus** [comment]
We have a FAQ in the works at https://github.com/Microsoft/vscode-cpptools/pull/3424/files .

Do you see the memory usage go up when it gets slower?

We've gotten other similar performance reports, but we're not sure how to get repro yet.

**Comment by septag** [comment]
thanks for the docs

so far, in one instance that it got slow, I had 850mb of allocated memory for vscode (at the beggining when project was opened, it was 450mb).

The procmon shows vscode_cpp_intellisense.exe (something similar) keep opening and closing, and taking roughly the same time as the fire icon in the bottom.

**Comment by sean-mcmanus** [comment]
That memory usage seems normal/expected -- does it seems like the 850 MB of memory usage is too much and is causing the slowness? What action causes the intellisense process to open/close? If that is occurring during edits, then it means that the process is crashing and restarting, but after 5 or so crashes it's supposed to stop launching new processes. Or if it's just using CPU and idling then that sounds normal.

**Comment by septag** [comment]
> That memory usage seems normal/expected -- does it seems like the 850 MB of memory usage is too much and is causing the slowness?

No, I don't think it's unexpected for an electron app. I was just reporting the memory usage that you asked for.

Btw, about the close/open. sorry, with a little more inspection, I was mistaking. The process just takes too much time. 
yes it takes just more time with the same source file.
here's what proc-explorer shows (in this instance vscode takes about 1gb of memory) :

![image](https://user-images.githubusercontent.com/5081921/56082288-5b9b7f00-5e2c-11e9-87b8-4ed656001ee3.png)

Also in Process DLL view for the selected cpp.intellisense.msvc.exe, there are lots of `edgXXX.tmp` and `sourcefile.pch` modules.

I will be watching it more closely and keep you updated if I find something interesting, but If there are any inspections or hints that I could do to pin-point the slowdown, please let me know..

**Comment by sean-mcmanus** [comment]
Approximately how many lines are in the "large files" that are slow? We have a know issue with files with over 100k lines, but I'm not seeing the issue you describe with 10k line files.

If you enable debug logging (https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) what is the last message you see when it gets stuck processing IntelliSense?

**Comment by septag** [comment]
> but I'm not seeing the issue you describe with 10k line files.

they are generally less than 10kloc.
For example, today I was working on a 1300 lines file for couple of hours, which is not large at all. at the end of the day, it got so slow that the intellisense wasn't usable, after vscode restart, it's as fast as before
this is the modules view of the `Intellisense.msvc.exe`:

![image](https://user-images.githubusercontent.com/5081921/56461390-696e7880-63c7-11e9-9dc5-de53b1453977.png)

There is a large list of .tmp files under this instance...
EDIT: I forgot to elevate logging level, and check it. Unfortunately I have to work on a file for some time for the issue to show itself, so I'll keep you posted if I got something interesting.

**Comment by septag** [comment]
Here's another example:
I opened a 1800 line file _(math.h)_. But it stays on 'fire' icon for about 30 seconds and even then, the symbols are not loaded for _math.h_

Here's the debug log:
![image](https://user-images.githubusercontent.com/5081921/56668065-2876ac80-66c4-11e9-8078-3b31028958ad.png)

(I don't know why when I opened math.h, it queued multiple other files for intellisense which some of them are not even opened in my editor)

**Comment by septag** [comment]
I may have found the cause of the problem. (by checking the logs)
it was dead slow, until I disabled error squiggles. now it seems that intellisense became fast again!

EDIT: Unfortunately no, it got super slow after some time again. 
I have disabled error squiggles:
```
"C_Cpp.errorSquiggles": "Disabled"
```

And there are no red lines in my code anymore but the log shows something else:
```
errorSquiggles count: 2
errorSquiggles count: 0
errorSquiggles count: 0
errorSquiggles count: 0
```

**Comment by septag** [comment]
Sorry but the extension is becoming very unusable for me and is really hurting my productivity, so I'll be switching to msvc again for a while. 
But I will be checking the bugs from time to time and happy to help if you wanted more info on something.
Hope this software will become robust and usable soon

**Comment by andreeis** [comment]
Does IntelliSense still get progressively slower with the last insiders? We made a fix that may have addressed this issue but we don't know for sure since we weren't able to create a good repro for this scenario.

**Comment by septag** [comment]
I've just installed the insiders version and working with a project to see if it happens.
will get back to you..

**Comment by septag** [comment]
Update: It's been a while that I'm working with my code base and still no slowdowns with version 0.24.1. vscode insider: 1.37.0

**Comment by bobbrow** [comment]
Thank you for the update.  Are there any remaining unresolved issues for you, or is it ok to close this issue now?

**Comment by septag** [comment]
It's currently fixed I guess, I'll close it until I encounter the slowdowns again.
Thanks
