### ISSUE TITLE
Macos: cannot open source files

### ISSUE THREAD

**Issue by sab24** [microsoft/vscode-cpptools#3429]
**Type: LanguageService**

**Describe the bug**

- OS and Version: macos 10.4.4
- VS Code Version: 1.33.0
- C/C++ Extension Version: 0.22.1

**To Reproduce**
create a project with a cpp file including iostream

<img width="371" alt="Screenshot 2019-04-07 at 14 02 07" src="https://user-images.githubusercontent.com/3050374/55683225-c9800c00-593d-11e9-84c8-e4c123d0ebad.png">

Gives
<img width="536" alt="Screenshot 2019-04-07 at 13 49 21" src="https://user-images.githubusercontent.com/3050374/55683086-fd5a3200-593b-11e9-8f4c-51d373a6ce94.png">

**Expected behavior**
No errors, as it compiles fine.
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/local/Cellar/llvm/8.0.0/include/c++/v1"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/local/opt/llvm/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
Can your remove the "v1" directory from your includePath? You should be relying on the compilerPath to set that. If that doesn't work, you may need to supply some additional args in the compilerPath (to match what you use to build), such as "-stdlib=libc++" or a "-sysroot=".

Or can you can check the Debug logging output to see if the correct includePaths are being used: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md .

**Comment by sab24** [comment]
Reinstalled the toolchain files with:
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

Seemed to solve the problems for me this time.

**Comment by sab24** [comment]
I guess it has something to do with removing /usr/include starting in Mojave
