### ISSUE TITLE
hitting tab or space doesn't work after TrimTrailingWhitespace

### ISSUE THREAD

**Issue by csalv5** [microsoft/vscode-cpptools#343]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-47-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-great-icons|emmanuelbeziat|1.1.22|
|CppSnippets|hars|0.0.5|
|language-haskell|justusadam|1.2.2|
|cpptools|ms-vscode|0.9.2|
|mytheme|me|0.0.1|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.0.6|
|vscode-icons|robertohuertasm|4.0.1|
|selectline-statusbar|tomoki1207|0.0.1|
|join-lines|wmaurer|0.1.5|

Steps to reproduce:
1. Move cursor  to newline
2. Save file
3. Hit Tab or Space

It causes saving the file. This only happens with c/c++ files and when "files.trimTrailingWhitespace" setting is set to true.

![vscode](https://cloud.githubusercontent.com/assets/6254054/20184502/2bd7255c-a769-11e6-90ff-866ea666a97e.gif)

**Comment by sean-mcmanus** [comment]
It seems like another extension is causing the file to be saved on edit, because I can't repro it with just our cpptools extension. Can you disable our cpptools extension (or disable others) to see if this still repros and narrow down which extension is causing the problem?

**Comment by csalv5** [comment]
The problem still persist after disabling all the above extensions (with only cpp ext enabled); with cpp ext disabled everything is ok, anyhow, i noticed that having cpp extension enabled, the only way to fix this issue is to set "C_Cpp.clang_format_formatOnSave" setting to false.

**Comment by sean-mcmanus** [comment]
Yeah, looks like a formatOnSave bug -- it seems to only repro on Linux/Mac (not Windows). We'll put it on our list of bugs to fix for a future release. We wrote the feature before VS Code had platform support for formatOnSave, so re-implementing the feature to use the platform support would probably fix this (and other issues, like SaveAll not formatting all saved files). Setting either of the formatOnSave or files.trimTrailingWhitespace settings to false also works around the bug.

**Comment by sean-mcmanus** [comment]
I'm no longer able to repro this. Let us know if this is still a problem.
