### ISSUE TITLE
Question: Intelli Sense between msvc-x64 and clang-x64

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3431]
Currently there are some different behavior in msvc-x64 and clang-x64 mode. Sometimes some code errors show in msvc-x64 mode and don't in clang-x64. Sometimes show in clang-x64 and don't in msvc-64.

I wonder currently which one is more reliable and accurate ? In windows, msvc-64 is more reliable and accurate than clang-64? I must use msvc-64 instead of clang-64?

**Comment by sean-mcmanus** [comment]
msvc-x64 attempts to mimic the cl.exe compiler. clang/gcc-x64 attempt to mimic the non-Windows clang/gcc complers that don't require Windows SDK headers or extensions to build. If you're using clang on Windows with Windows headers, you may need to use the msvc-x64 mode instead, but there are known issues where that mode isn't properly emulating the clang-cl.exe compiler. You can also use the "-fms-extensions" argument with clang/gcc, but there are known bugs with that as well (0.22.2-insiders will enable that on Linux/Mac, it's currently Windows only).

You should set the compilerPath as well to get the correct system includes defined set if you're using a non-cl.exe compiler.
