### ISSUE TITLE
CppProperties.json for vs code

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode-cpptools#3436]
Hey,

I was using open folder with visual studio and I had a CppProperties.json file for each subfolder in the repository to enable intellisense.

I recently switched to vs code because visual studio was becoming too slow to be usable.

I am wondering if there is something similar to the CppProperties.json for vs code.

I know of c_cpp_properties.json but if I understand correctly, there can only be one such file for the whole workspace that applies to all the subfolders.

Having only one file for the whole workspace is a bit limiting and hard to maintain since I have a script that updates the CppProperties.json everytime I build a project/subfolder. Not to mention that sometimes I need different defines and compiler flags for each subfolder.

Thanks

**Comment by sean-mcmanus** [comment]
Yeah, our c_cpp_properties.json is similar to the CppProperties.json, but ours only works at the root and doesn't support subfolders currently. Subfolders with configuration options are currently handled via either generating/using a compile_commands.json or using another extension that is a custom configuration provider for your build system, such as the CMake Tools extension and setting our configurationProvider setting.

We could use this issue to track the possibility of supporting c_cpp_properties.json in subfolders.

Another option might be to use multiple roots (one root per folder with a c_cpp_properties.json), but we have some known bugs in that scenario, such as formatting being buggy, and there could be performance issues, or issues with working across the folders.

**Comment by psclkhoury** [comment]
@sean-mcmanus It would be nice if you support CppProperties.json or something similar because for a big project the c_cpp_properties.json and the global settings is not very efficient. compile_commands.json might be the solution but they are not straightforward to generate if CMake is not used. We are still using makefile to build and some vcxprojs.
