### ISSUE TITLE
Add hability to include/exclude the files to parse

### ISSUE THREAD

**Issue by svillar** [microsoft/vscode-cpptools#3438]
VS code currently offers the possibility of excluding/ignoring files/dirs from being shown on the UI or from search results. However all the files found in a project are unconditionally parsed. That might be a problem in large projects, like Chromium or WebKit for example.

In those code bases there are a huge amount of files/directories that should not be parsed from the Web engine developer POV like most third party libraries or even large portions of the engine which are barely inspected and/or touched by the engine developer.

The parsing happens relatively fast even for those projects (order of seconds not minutes), however it'd be nice to have the possibility to restrict it to a selected group of directories. That initial parsing would be faster but also the intellisense engine would work much more faster and would provide much better results.

Does it make sense?

**Comment by sean-mcmanus** [comment]
We currently just use files.exclude to avoid global symbol parsing. Is using that okay?

But by default we only check folder excludes -- you can change the C_Cpp.exclusionPolicy setting to enable file-based exclusion, although that isn't recommended because of the potential performance impact.

**Comment by svillar** [comment]
> We currently just use files.exclude to avoid global symbol parsing. Is using that okay?

Ah that's awesome, didn't know it was used also for the parsing engine. The last time I checked I observed that all the files were found anyway although perhaps the filtered out ones were not inspected.
 
> But by default we only check folder excludes -- you can change the C_Cpp.exclusionPolicy setting to enable file-based exclusion, although that isn't recommended because of the potential performance impact.

Yeah I have enabled it only for folders. I have one question though, is it possible to have multiple intersecting patterns? Because the last time I checked it was not possible

For example, let's say that I want to exclude all the subfolders in a folder but one, is that possible?

**Comment by sean-mcmanus** [comment]
Yeah, I don't know how to not exclude certain subfolders. The docs mention `!` but I couldn't get it to work. Your best bet might be to try https://stackoverflow.com/questions/tagged/visual-studio-code , or file a feature request with VS Code.

**Comment by svillar** [comment]
It's been actually reported in several ocasions, like https://github.com/Microsoft/vscode/issues/869. Anyway out of the scope of the C++ extension.

We can safely close this. Thanks for the quick replies!
