### ISSUE TITLE
Return QuickFix code actions for missing includes

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3439]
We currently just return a Command instead of a CodeAction with a CodeActionKind.

However, we shouldn't do this until we can disable the "Add to includePath" code action for system includes and potentially replace it with a "Set compilerPath to" option.

**Comment by bobbrow** [comment]
Is there anything left to do here?  We updated the CodeActions a while back, but it's unclear if we need to do anything else for this issue.

**Comment by bobbrow** [comment]
I think #3422 covers the second half of this.

**Comment by sean-mcmanus** [comment]
> Is there anything left to do here?  We updated the CodeActions a while back, but it's unclear if we need to do anything else for this issue.

Yeah, we don't set the CodeAction "kind".
