### ISSUE TITLE
Code snippet not working properly

### ISSUE THREAD

**Issue by learning** [microsoft/vscode-cpptools#3442]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS 10.14.4 (18E226)
- VS Code Version: 1.33.0 (1.33.0)
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them):
  - Better TOML 0.3.2
  - Dart 2.25.0
  - Flutter 2.25.0
  - Rust (rls) 0.6.1
  - Vim 1.4.0
- A clear and concise description of what the bug is.
  When using the `class` code snippet, I can't change the name properly

**To Reproduce**

1. Type `class` and hit `<enter>`
2. Hit `<backspace>` and enter a new name

**Expected behavior**

Change the name, constructor and destructor to the same.

**Screenshots**

![Untitled-1](https://user-images.githubusercontent.com/354626/55868807-c8f2aa00-5bb7-11e9-80a2-2c0303fc51fa.gif)

**Additional context**

N/A

**Comment by sean-mcmanus** [comment]
The bug isn't reproing for me, although I'm using 0.22.2-insiders. I believe it's probably a VS Code bug that only repros with certain settings and is unrelated to our snippets -- we don't control the snippet UI behavior, just the text that is used. Can you open a bug on VS Code? https://github.com/Microsoft/vscode/issues

**Comment by learning** [comment]
@sean-mcmanus Oh, I found that was a bug related to [Vim](https://github.com/VSCodeVim/Vim) plugin.

https://github.com/VSCodeVim/Vim/issues/3518
