### ISSUE TITLE
how to compile in visual code studio 2019 for mac using C++

### ISSUE THREAD

**Issue by Myke24** [microsoft/vscode-cpptools#3445]

**Comment by sean-mcmanus** [comment]
Visual Studio Code for Mac doesn't support C++ as far as I'm aware of. Our team only works on the Visual Studio Code extension, which runs on Mac. We have a Build and Debug Active File command that works on a single file -- you can modify the tasks.json it creates to compile more files.

**Comment by bobbrow** [comment]
This feature request is being tracked on Developer Community.  Please go upvote it here: https://developercommunity.visualstudio.com/content/idea/356171/support-projects-with-c-c14-c17-language-with-inte.html
