### ISSUE TITLE
Visual Studio Code C/C++ Extension is incorrectly labeling several errors

### ISSUE THREAD

**Issue by bavalpey** [microsoft/vscode-cpptools#3446]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.17134
- VS Code Version: 1.32.3
- C/C++ Extension Version: 0.22.2-insiders
- Visual Studio Code C/C++ Extension is incorrectly marking basic, valid code with syntax errors

**To Reproduce**

1. Create a new .cpp file
2. Attempt to use std::min() or std::max(), or any of the identifiers such as "and", "or", or "not"
3. Observe incorrect error marking by the extension
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17763.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```
**Expected behavior**

I expect that vscode will not incorrectly label the min() function and max() function with red squiggles.  I also expect that the alternative identifiers 'and', 'or' and 'not' (as well as the others) to not be incorrectly highlighted.
**Screenshots**
![image](https://user-images.githubusercontent.com/36710691/55918026-32be8400-5bb7-11e9-8801-5b5f02d8a068.png)

![image](https://user-images.githubusercontent.com/36710691/55918075-5f729b80-5bb7-11e9-8b15-782da1a01bf0.png)

**Comment by sean-mcmanus** [comment]
Are you #including the header that defines min?
```
#include <algorithm>
int main()
{
return std::min(0, 1);
}
```
works for me.

The "not" issue is caused by our lack of support for cl.exe with /permissive-. Are you compiling with /permissive-?

**Comment by sean-mcmanus** [comment]
A temporary work around to fix the issue is to edit the file `"C:\Users\<user>\.vscode[-insiders]\extensions\ms-vscode.cpptools-0.22.2-insiders\bin\msvc.64.intel.json"` .
and replace
```
      "--microsoft_bugs",
```
with
```
      "--microsoft_bugs",
      "--no_ms_permissive",
```
and then edit/save...but that will get overwritten by updates to the extension.

UPDATE: In our next release, the `/permissive-` flag can be passed to cl.exe in the compilerPath setting to enable this.

**Comment by bavalpey** [comment]
While the workaround suggested may have worked, I fixed this by changing my configuration.json to use MinGW as the compiler instead. The problem now is that I want this configuration enabled by default.

MinGW fixes both issues, while adding #include<algorithm> only fixed the issue for min and max (using MinGW, #include<algorithm> is not needed for min / max)

To fix this, my new c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "MinGW",
            "intelliSenseMode": "gcc-x64",
            "compilerPath": "C:/MinGW/bin/g++.exe",
            "includePath": [
                "${workspaceFolder}"
            ],
            "defines": [],
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
Yeah, your compilerPath setting should match whatever you're using to compile.

You can set your C_Cpp.default.compilerPath and C_Cpp.default.intelliSenseMode settings to have that used by default when opening new projects.
