### ISSUE TITLE
IntelliSense doesn't suggest existing variable names

### ISSUE THREAD

**Issue by V0rt-x** [microsoft/vscode-cpptools#3447]
The extension doesn't suggest and autocomplete any of existing variable names. It also can't find the declarations for them. It shows the definitions of functions well though. 
The problem has appeared recently, it had used to work properly for some time. I think it started, when I installed the Anaconda. Looked through the settings and c_cpp_properties.json and couldn't find what the matter is.
![issue1](https://user-images.githubusercontent.com/20661694/55921564-0b42d800-5c06-11e9-9141-3d4ce76e4663.png)
![issue2](https://user-images.githubusercontent.com/20661694/55921583-10a02280-5c06-11e9-9930-6da702912a76.png)

**Comment by sean-mcmanus** [comment]
This will occur if it's falling back to the Tag Parser and not using the "IntelliSense" engine. Are you missing any include headers? Can you provide more of your C_Cpp and c_cpp_properties.json settings?

**Comment by V0rt-x** [comment]
Oh, thanks a lot. I've just changed the IntelliSense engine to default...
