### ISSUE TITLE
problem with c_cpp_properties.json

### ISSUE THREAD

**Issue by mamo5298** [microsoft/vscode-cpptools#3449]
Type: General

**Describe the bug**
- OS and Version: windows 10 1803
- VS Code Version: 133.0
- C/C++ Extension Version: from 0.22.0
- just as i open vs code a message appears says that there is error when parsing c_cpp_properties.json because of double backslash ended path string, and then intellisense will not work any more, when i edit the json file to avoid the error, the extension will automatically update the file after compiling the project and the problem comes back.
i am currently working on extension version 0.21.0 where everything is fine but i have to reinstall this version everytime i start vs code because the extension will update automatically to the latest version.

**To Reproduce**
1. install c/c++ v0.22.0 or later
2. use c_cpp_properties.json file with \\\\ ended include or browse path entry, example:
"C:\\\\Users\\\\mm\\\\Desktop\\\\Sampler32\\\\trunk\\\\common\\\\",
3. compile or simply open the project which has this file

**Expected behavior**
with the version v0.21.0 the json file works as it is, and everything is fine

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/49508578/55934773-faa85700-5c31-11e9-8043-e08fbef9a87d.PNG)

**Additional context**
i am developing an embedded systems project, therefore i am using IAR Embedded extension for compiling, and cortex-debug extension for debugging as well as SVN extension for code syncing.

**Comment by sean-mcmanus** [comment]
Sorry about that. We have a fix for our next release: https://github.com/Microsoft/vscode-cpptools/pull/3453 .

**Comment by sean-mcmanus** [comment]
The parse error should be fixed with 0.23.0-insiders.
