### ISSUE TITLE
Go to definition and intellisense error about typedef function pointer

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3450]
**Type: LanguageService**

**Describe the bug**
- C/C++ Extension Version: 0.21

in .h file, define macro like this:
![捕获22](https://user-images.githubusercontent.com/39362073/55956590-e34f8500-5c96-11e9-866a-de4d8459bdb1.PNG)

in .cpp file, code like this:
![捕获](https://user-images.githubusercontent.com/39362073/55956541-c9ae3d80-5c96-11e9-8ff0-edd18c7356ae.PNG)

**Comment by sean-mcmanus** [comment]
We need more repro info, i.e. I'm not reproing the bug. The bug would repro if the header file is not being found for some reason. Does it say the header is found? What is your compilerPath? I assume C language, not C++, right?

**Comment by Lennon925** [comment]
> We need more repro info, i.e. I'm not reproing the bug. The bug would repro if the header file is not being found for some reason. Does it say the header is found? What is your compilerPath? I assume C language, not C++, right?

it said that the header is not found in both c and c++ language. I didn't set the compilerPath for it.  My header file and cpp file are in the same folder, I still need to set the compiler path?

**Comment by sean-mcmanus** [comment]
It sounds like it may be finding the wrong header file, for example, if recursive includes is used and you have multiple different folders that have header files with the same name. Something is causing the VOS_INT32 type to not be found. If you enable logging, you could double check that the includePath being used is correct: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md . Another possibility is that the `#defines` are not correctly set for that file, causing the definition to be skipped over.

You may not need to set the compiler if we're choosing the correct one behind the scenes. The error doesn't seem related to the compilerPath.

Can you verify that you don't repro the bug with a simple project? And/or can you provide a repro project?

**Comment by Lennon925** [comment]
> We need more repro info, i.e. I'm not reproing the bug. The bug would repro if the header file is not being found for some reason. Does it say the header is found? What is your compilerPath? I assume C language, not C++, right?

header file:
![1](https://user-images.githubusercontent.com/39362073/56006448-6a3c4600-5d07-11e9-8230-2ab586516a03.PNG)

cpp file:
![2](https://user-images.githubusercontent.com/39362073/56006451-6dcfcd00-5d07-11e9-914b-0e1446c9879a.PNG)

in cpp file, don't include the header to simulate scenario which can't find header file

**Comment by Lennon925** [comment]
> > We need more repro info, i.e. I'm not reproing the bug. The bug would repro if the header file is not being found for some reason. Does it say the header is found? What is your compilerPath? I assume C language, not C++, right?
> 
> header file:
> ![1](https://user-images.githubusercontent.com/39362073/56006448-6a3c4600-5d07-11e9-8230-2ab586516a03.PNG)
> 
> cpp file:
> ![2](https://user-images.githubusercontent.com/39362073/56006451-6dcfcd00-5d07-11e9-914b-0e1446c9879a.PNG)
> 
> in cpp file, don't include the header to simulate scenario which can't find header file

in clang-x64 mode, even though you include the right header, 'go to definition' still goes wrong position.

**Comment by sean-mcmanus** [comment]
I'm confused. Why is the #include for the header commented out? That needs to exist or it won't be able to find the definition.

Also, Go to Def is implemented without looking at the proper IntelliSense includePath so it may send you to the wrong file (we have another work item tracking that).

**Comment by Lennon925** [comment]
> I'm confused. Why is the #include for the header commented out? That needs to exist or it won't be able to find the definition.
> 
> Also, Go to Def is implemented without looking at the proper IntelliSense includePath so it may send you to the wrong file (we have another work item tracking that).

in clang-x64 mode, even though you include the right header, 'go to definition' still goes wrong position.

**Comment by Lennon925** [comment]
> I'm confused. Why is the #include for the header commented out? That needs to exist or it won't be able to find the definition.
> 
> Also, Go to Def is implemented without looking at the proper IntelliSense includePath so it may send you to the wrong file (we have another work item tracking that).

you can repo this bug by like this:

Test(folder)
       |__.vscode(folder)
       .....|__c_cpp_properties.json
       |__student.h
       |__test.cpp

c_cpp_properties.json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "intelliSenseMode": "clang-x64",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}

student.h 
typedef unsigned long VOS_INT_TEST_32;

test.cpp
![333](https://user-images.githubusercontent.com/39362073/56009856-e0df4080-5d13-11e9-8725-fe0786619ec8.PNG)

In clangd-x64 mode, if I add "#include \<vector\>" this line,"go to definition" on VOS_INT_TEST_32 goes wrong position.

**Comment by sean-mcmanus** [comment]
Yeah, I'm not reproing the bug. vector is a system header so it may be important what your compilerPath is set to and what location vector is getting chosen from.

![image](https://user-images.githubusercontent.com/19859882/56056374-dec7b280-5d10-11e9-9e40-1889c3aa5d6a.png)


It's also possible your ipch folder may have corrupted data so deleting that folder might help, and/or setting the intelliSenseCacheSize to 0.

Can you check the logging I mentioned before, for the includePaths and defines used? The info that is important is output after you open test.cpp for the 1st time. Also, if that folder has case sensitive folders enabled that might cause this issue.

Do you still have 0.21.0 installed? You could try 0.22.1 or 0.22.2-insiders.

**Comment by Lennon925** [comment]
On version 0.21, there is no ipch folder and intellisenseCacheSize this parameter to set. I tried on the version 0.22.2-insiders, and the behavior is still same with version 0.21. 

Log as follows:
Shutting down IntelliSense server: D:\TEST\TEST1\TEST.CPP
Closing the communication channel.
cpptools/queryTranslationUnitSource: 22
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/didOpen
textDocument/documentSymbol: 23
sending compilation args for D:\TEST\TEST1\TEST.CPP
  include: D:\PROGRAM FILES\LLVM\LIB\CLANG\8.0.0\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\BUILDTOOLS\VC\TOOLS\MSVC\14.16.27023\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\WINRT
  define: __llvm__=1
  define: __clang__=1
  define: __clang_major__=8
  define: __clang_minor__=0
  define: __clang_patchlevel__=0
  define: __clang_version__="8.0.0 (tags/RELEASE_800/final)"
  define: __ATOMIC_RELAXED=0
  define: __ATOMIC_CONSUME=1
  define: __ATOMIC_ACQUIRE=2
  define: __ATOMIC_RELEASE=3
  define: __ATOMIC_ACQ_REL=4
  define: __ATOMIC_SEQ_CST=5
  define: __OPENCL_MEMORY_SCOPE_WORK_ITEM=0
  define: __OPENCL_MEMORY_SCOPE_WORK_GROUP=1
  define: __OPENCL_MEMORY_SCOPE_DEVICE=2
  define: __OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES=3
  define: __OPENCL_MEMORY_SCOPE_SUB_GROUP=4
  define: __PRAGMA_REDEFINE_EXTNAME=1
  define: __VERSION__="4.2.1 Compatible Clang 8.0.0 (tags/RELEASE_800/final)"
  define: __OBJC_BOOL_IS_BOOL=0
  define: __cpp_rtti=199711L
  define: __cpp_exceptions=199711L
  define: __cpp_unicode_characters=200704L
  define: __cpp_raw_strings=200710L
  define: __cpp_unicode_literals=200710L
  define: __cpp_user_defined_literals=200809L
  define: __cpp_lambdas=200907L
  define: __cpp_constexpr=201603L
  define: __cpp_range_based_for=201603L
  define: __cpp_static_assert=201411L
  define: __cpp_decltype=200707L
  define: __cpp_attributes=200809L
  define: __cpp_rvalue_references=200610L
  define: __cpp_variadic_templates=200704L
  define: __cpp_initializer_lists=200806L
  define: __cpp_delegating_constructors=200604L
  define: __cpp_nsdmi=200809L
  define: __cpp_inheriting_constructors=201511L
  define: __cpp_ref_qualifiers=200710L
  define: __cpp_alias_templates=200704L
  define: __cpp_threadsafe_static_init=200806L
  define: __cpp_binary_literals=201304L
  define: __cpp_digit_separators=201309L
  define: __cpp_init_captures=201304L
  define: __cpp_generic_lambdas=201304L
  define: __cpp_decltype_auto=201304L
  define: __cpp_return_type_deduction=201304L
  define: __cpp_aggregate_nsdmi=201304L
  define: __cpp_variable_templates=201304L
  define: __cpp_hex_float=201603L
  define: __cpp_inline_variables=201606L
  define: __cpp_noexcept_function_type=201510L
  define: __cpp_capture_star_this=201603L
  define: __cpp_if_constexpr=201606L
  define: __cpp_deduction_guides=201703L
  define: __cpp_template_auto=201606L
  define: __cpp_namespace_attributes=201411L
  define: __cpp_enumerator_attributes=201411L
  define: __cpp_nested_namespace_definitions=201411L
  define: __cpp_variadic_using=201611L
  define: __cpp_aggregate_bases=201603L
  define: __cpp_structured_bindings=201606L
  define: __cpp_nontype_template_args=201411L
  define: __cpp_fold_expressions=201603L
  define: __cpp_guaranteed_copy_elision=201606L
  define: __cpp_nontype_template_parameter_auto=201606L
  define: __cpp_aligned_new=201606L
  define: __cpp_impl_destroying_delete=201806L
  define: __CONSTANT_CFSTRINGS__=1
  define: __DEPRECATED=1
  define: _WCHAR_T_DEFINED=1
  define: _NATIVE_WCHAR_T_DEFINED=1
  define: __ORDER_LITTLE_ENDIAN__=1234
  define: __ORDER_BIG_ENDIAN__=4321
  define: __ORDER_PDP_ENDIAN__=3412
  define: __BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __LITTLE_ENDIAN__=1
  define: __CHAR_BIT__=8
  define: __SCHAR_MAX__=127
  define: __SHRT_MAX__=32767
  define: __INT_MAX__=2147483647
  define: __LONG_MAX__=2147483647L
  define: __LONG_LONG_MAX__=9223372036854775807LL
  define: __WCHAR_MAX__=65535
  define: __WINT_MAX__=65535
  define: __INTMAX_MAX__=9223372036854775807LL
  define: __SIZE_MAX__=18446744073709551615ULL
  define: __UINTMAX_MAX__=18446744073709551615ULL
  define: __PTRDIFF_MAX__=9223372036854775807LL
  define: __INTPTR_MAX__=9223372036854775807LL
  define: __UINTPTR_MAX__=18446744073709551615ULL
  define: __SIZEOF_DOUBLE__=8
  define: __SIZEOF_FLOAT__=4
  define: __SIZEOF_INT__=4
  define: __SIZEOF_LONG__=4
  define: __SIZEOF_LONG_DOUBLE__=8
  define: __SIZEOF_LONG_LONG__=8
  define: __SIZEOF_POINTER__=8
  define: __SIZEOF_SHORT__=2
  define: __SIZEOF_PTRDIFF_T__=8
  define: __SIZEOF_SIZE_T__=8
  define: __SIZEOF_WCHAR_T__=2
  define: __SIZEOF_WINT_T__=2
  define: __SIZEOF_INT128__=16
  define: __INTMAX_TYPE__=long long int
  define: __INTMAX_FMTd__="lld"
  define: __INTMAX_FMTi__="lli"
  define: __INTMAX_C_SUFFIX__=LL
  define: __UINTMAX_TYPE__=long long unsigned int
  define: __UINTMAX_FMTo__="llo"
  define: __UINTMAX_FMTu__="llu"
  define: __UINTMAX_FMTx__="llx"
  define: __UINTMAX_FMTX__="llX"
  define: __UINTMAX_C_SUFFIX__=ULL
  define: __INTMAX_WIDTH__=64
  define: __PTRDIFF_TYPE__=long long int
  define: __PTRDIFF_FMTd__="lld"
  define: __PTRDIFF_FMTi__="lli"
  define: __PTRDIFF_WIDTH__=64
  define: __INTPTR_TYPE__=long long int
  define: __INTPTR_FMTd__="lld"
  define: __INTPTR_FMTi__="lli"
  define: __INTPTR_WIDTH__=64
  define: __SIZE_TYPE__=long long unsigned int
  define: __SIZE_FMTo__="llo"
  define: __SIZE_FMTu__="llu"
  define: __SIZE_FMTx__="llx"
  define: __SIZE_FMTX__="llX"
  define: __SIZE_WIDTH__=64
  define: __WCHAR_TYPE__=unsigned short
  define: __WCHAR_WIDTH__=16
  define: __WINT_TYPE__=unsigned short
  define: __WINT_WIDTH__=16
  define: __SIG_ATOMIC_WIDTH__=32
  define: __SIG_ATOMIC_MAX__=2147483647
  define: __CHAR16_TYPE__=unsigned short
  define: __CHAR32_TYPE__=unsigned int
  define: __UINTMAX_WIDTH__=64
  define: __UINTPTR_TYPE__=long long unsigned int
  define: __UINTPTR_FMTo__="llo"
  define: __UINTPTR_FMTu__="llu"
  define: __UINTPTR_FMTx__="llx"
  define: __UINTPTR_FMTX__="llX"
  define: __UINTPTR_WIDTH__=64
  define: __FLT16_DENORM_MIN__=5.9604644775390625e-8F16
  define: __FLT16_HAS_DENORM__=1
  define: __FLT16_DIG__=3
  define: __FLT16_DECIMAL_DIG__=5
  define: __FLT16_EPSILON__=9.765625e-4F16
  define: __FLT16_HAS_INFINITY__=1
  define: __FLT16_HAS_QUIET_NAN__=1
  define: __FLT16_MANT_DIG__=11
  define: __FLT16_MAX_10_EXP__=4
  define: __FLT16_MAX_EXP__=15
  define: __FLT16_MAX__=6.5504e+4F16
  define: __FLT16_MIN_10_EXP__=(-13)
  define: __FLT16_MIN_EXP__=(-14)
  define: __FLT16_MIN__=6.103515625e-5F16
  define: __FLT_DENORM_MIN__=1.40129846e-45F
  define: __FLT_HAS_DENORM__=1
  define: __FLT_DIG__=6
  define: __FLT_DECIMAL_DIG__=9
  define: __FLT_EPSILON__=1.19209290e-7F
  define: __FLT_HAS_INFINITY__=1
  define: __FLT_HAS_QUIET_NAN__=1
  define: __FLT_MANT_DIG__=24
  define: __FLT_MAX_10_EXP__=38
  define: __FLT_MAX_EXP__=128
  define: __FLT_MAX__=3.40282347e+38F
  define: __FLT_MIN_10_EXP__=(-37)
  define: __FLT_MIN_EXP__=(-125)
  define: __FLT_MIN__=1.17549435e-38F
  define: __DBL_DENORM_MIN__=4.9406564584124654e-324
  define: __DBL_HAS_DENORM__=1
  define: __DBL_DIG__=15
  define: __DBL_DECIMAL_DIG__=17
  define: __DBL_EPSILON__=2.2204460492503131e-16
  define: __DBL_HAS_INFINITY__=1
  define: __DBL_HAS_QUIET_NAN__=1
  define: __DBL_MANT_DIG__=53
  define: __DBL_MAX_10_EXP__=308
  define: __DBL_MAX_EXP__=1024
  define: __DBL_MAX__=1.7976931348623157e+308
  define: __DBL_MIN_10_EXP__=(-307)
  define: __DBL_MIN_EXP__=(-1021)
  define: __DBL_MIN__=2.2250738585072014e-308
  define: __LDBL_DENORM_MIN__=4.9406564584124654e-324L
  define: __LDBL_HAS_DENORM__=1
  define: __LDBL_DIG__=15
  define: __LDBL_DECIMAL_DIG__=17
  define: __LDBL_EPSILON__=2.2204460492503131e-16L
  define: __LDBL_HAS_INFINITY__=1
  define: __LDBL_HAS_QUIET_NAN__=1
  define: __LDBL_MANT_DIG__=53
  define: __LDBL_MAX_10_EXP__=308
  define: __LDBL_MAX_EXP__=1024
  define: __LDBL_MAX__=1.7976931348623157e+308L
  define: __LDBL_MIN_10_EXP__=(-307)
  define: __LDBL_MIN_EXP__=(-1021)
  define: __LDBL_MIN__=2.2250738585072014e-308L
  define: __POINTER_WIDTH__=64
  define: __BIGGEST_ALIGNMENT__=16
  define: __WCHAR_UNSIGNED__=1
  define: __WINT_UNSIGNED__=1
  define: __INT8_TYPE__=signed char
  define: __INT8_FMTd__="hhd"
  define: __INT8_FMTi__="hhi"
  define: __INT8_C_SUFFIX__=
  define: __INT16_TYPE__=short
  define: __INT16_FMTd__="hd"
  define: __INT16_FMTi__="hi"
  define: __INT16_C_SUFFIX__=
  define: __INT32_TYPE__=int
  define: __INT32_FMTd__="d"
  define: __INT32_FMTi__="i"
  define: __INT32_C_SUFFIX__=
  define: __INT64_TYPE__=long long int
  define: __INT64_FMTd__="lld"
  define: __INT64_FMTi__="lli"
  define: __INT64_C_SUFFIX__=LL
  define: __UINT8_TYPE__=unsigned char
  define: __UINT8_FMTo__="hho"
  define: __UINT8_FMTu__="hhu"
  define: __UINT8_FMTx__="hhx"
  define: __UINT8_FMTX__="hhX"
  define: __UINT8_C_SUFFIX__=
  define: __UINT8_MAX__=255
  define: __INT8_MAX__=127
  define: __UINT16_TYPE__=unsigned short
  define: __UINT16_FMTo__="ho"
  define: __UINT16_FMTu__="hu"
  define: __UINT16_FMTx__="hx"
  define: __UINT16_FMTX__="hX"
  define: __UINT16_C_SUFFIX__=
  define: __UINT16_MAX__=65535
  define: __INT16_MAX__=32767
  define: __UINT32_TYPE__=unsigned int
  define: __UINT32_FMTo__="o"
  define: __UINT32_FMTu__="u"
  define: __UINT32_FMTx__="x"
  define: __UINT32_FMTX__="X"
  define: __UINT32_C_SUFFIX__=U
  define: __UINT32_MAX__=4294967295U
  define: __INT32_MAX__=2147483647
  define: __UINT64_TYPE__=long long unsigned int
  define: __UINT64_FMTo__="llo"
  define: __UINT64_FMTu__="llu"
  define: __UINT64_FMTx__="llx"
  define: __UINT64_FMTX__="llX"
  define: __UINT64_C_SUFFIX__=ULL
  define: __UINT64_MAX__=18446744073709551615ULL
  define: __INT64_MAX__=9223372036854775807LL
  define: __INT_LEAST8_TYPE__=signed char
  define: __INT_LEAST8_MAX__=127
  define: __INT_LEAST8_FMTd__="hhd"
  define: __INT_LEAST8_FMTi__="hhi"
  define: __UINT_LEAST8_TYPE__=unsigned char
  define: __UINT_LEAST8_MAX__=255
  define: __UINT_LEAST8_FMTo__="hho"
  define: __UINT_LEAST8_FMTu__="hhu"
  define: __UINT_LEAST8_FMTx__="hhx"
  define: __UINT_LEAST8_FMTX__="hhX"
  define: __INT_LEAST16_TYPE__=short
  define: __INT_LEAST16_MAX__=32767
  define: __INT_LEAST16_FMTd__="hd"
  define: __INT_LEAST16_FMTi__="hi"
  define: __UINT_LEAST16_TYPE__=unsigned short
  define: __UINT_LEAST16_MAX__=65535
  define: __UINT_LEAST16_FMTo__="ho"
  define: __UINT_LEAST16_FMTu__="hu"
  define: __UINT_LEAST16_FMTx__="hx"
  define: __UINT_LEAST16_FMTX__="hX"
  define: __INT_LEAST32_TYPE__=int
  define: __INT_LEAST32_MAX__=2147483647
  define: __INT_LEAST32_FMTd__="d"
  define: __INT_LEAST32_FMTi__="i"
  define: __UINT_LEAST32_TYPE__=unsigned int
  define: __UINT_LEAST32_MAX__=4294967295U
  define: __UINT_LEAST32_FMTo__="o"
  define: __UINT_LEAST32_FMTu__="u"
  define: __UINT_LEAST32_FMTx__="x"
  define: __UINT_LEAST32_FMTX__="X"
  define: __INT_LEAST64_TYPE__=long long int
  define: __INT_LEAST64_MAX__=9223372036854775807LL
  define: __INT_LEAST64_FMTd__="lld"
  define: __INT_LEAST64_FMTi__="lli"
  define: __UINT_LEAST64_TYPE__=long long unsigned int
  define: __UINT_LEAST64_MAX__=18446744073709551615ULL
  define: __UINT_LEAST64_FMTo__="llo"
  define: __UINT_LEAST64_FMTu__="llu"
  define: __UINT_LEAST64_FMTx__="llx"
  define: __UINT_LEAST64_FMTX__="llX"
  define: __INT_FAST8_TYPE__=signed char
  define: __INT_FAST8_MAX__=127
  define: __INT_FAST8_FMTd__="hhd"
  define: __INT_FAST8_FMTi__="hhi"
  define: __UINT_FAST8_TYPE__=unsigned char
  define: __UINT_FAST8_MAX__=255
  define: __UINT_FAST8_FMTo__="hho"
  define: __UINT_FAST8_FMTu__="hhu"
  define: __UINT_FAST8_FMTx__="hhx"
  define: __UINT_FAST8_FMTX__="hhX"
  define: __INT_FAST16_TYPE__=short
  define: __INT_FAST16_MAX__=32767
  define: __INT_FAST16_FMTd__="hd"
  define: __INT_FAST16_FMTi__="hi"
  define: __UINT_FAST16_TYPE__=unsigned short
  define: __UINT_FAST16_MAX__=65535
  define: __UINT_FAST16_FMTo__="ho"
  define: __UINT_FAST16_FMTu__="hu"
  define: __UINT_FAST16_FMTx__="hx"
  define: __UINT_FAST16_FMTX__="hX"
  define: __INT_FAST32_TYPE__=int
  define: __INT_FAST32_MAX__=2147483647
  define: __INT_FAST32_FMTd__="d"
  define: __INT_FAST32_FMTi__="i"
  define: __UINT_FAST32_TYPE__=unsigned int
  define: __UINT_FAST32_MAX__=4294967295U
  define: __UINT_FAST32_FMTo__="o"
  define: __UINT_FAST32_FMTu__="u"
  define: __UINT_FAST32_FMTx__="x"
  define: __UINT_FAST32_FMTX__="X"
  define: __INT_FAST64_TYPE__=long long int
  define: __INT_FAST64_MAX__=9223372036854775807LL
  define: __INT_FAST64_FMTd__="lld"
  define: __INT_FAST64_FMTi__="lli"
  define: __UINT_FAST64_TYPE__=long long unsigned int
  define: __UINT_FAST64_MAX__=18446744073709551615ULL
  define: __UINT_FAST64_FMTo__="llo"
  define: __UINT_FAST64_FMTu__="llu"
  define: __UINT_FAST64_FMTx__="llx"
  define: __UINT_FAST64_FMTX__="llX"
  define: __USER_LABEL_PREFIX__=
  define: __FINITE_MATH_ONLY__=0
  define: __CLANG_ATOMIC_BOOL_LOCK_FREE=2
  define: __CLANG_ATOMIC_CHAR_LOCK_FREE=2
  define: __CLANG_ATOMIC_CHAR16_T_LOCK_FREE=2
  define: __CLANG_ATOMIC_CHAR32_T_LOCK_FREE=2
  define: __CLANG_ATOMIC_WCHAR_T_LOCK_FREE=2
  define: __CLANG_ATOMIC_SHORT_LOCK_FREE=2
  define: __CLANG_ATOMIC_INT_LOCK_FREE=2
  define: __CLANG_ATOMIC_LONG_LOCK_FREE=2
  define: __CLANG_ATOMIC_LLONG_LOCK_FREE=2
  define: __CLANG_ATOMIC_POINTER_LOCK_FREE=2
  define: __NO_INLINE__=1
  define: __PIC__=2
  define: __pic__=2
  define: __FLT_EVAL_METHOD__=0
  define: __FLT_RADIX__=2
  define: __DECIMAL_DIG__=__LDBL_DECIMAL_DIG__
  define: __code_model_small_=1
  define: __amd64__=1
  define: __amd64=1
  define: __x86_64=1
  define: __x86_64__=1
  define: __k8=1
  define: __k8__=1
  define: __tune_k8__=1
  define: __REGISTER_PREFIX__=
  define: __NO_MATH_INLINES=1
  define: __FXSR__=1
  define: __SSE2__=1
  define: __SSE2_MATH__=1
  define: __SSE__=1
  define: __SSE_MATH__=1
  define: __MMX__=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1
  define: _WIN32=1
  define: _WIN64=1
  define: _CPPRTTI=1
  define: _CPPUNWIND=1
  define: __BOOL_DEFINED=1
  define: _MSC_VER=1916
  define: _MSC_FULL_VER=191627024
  define: _MSC_BUILD=1
  define: _HAS_CHAR16_T_LANGUAGE_SUPPORT=1
  define: _MSVC_LANG=201703L
  define: _MSC_EXTENSIONS=1
  define: _RVALUE_REFERENCES_V2_SUPPORTED=1
  define: _RVALUE_REFERENCES_SUPPORTED=1
  define: _NATIVE_NULLPTR_SUPPORTED=1
  define: _INTEGRAL_MAX_BITS=64
  define: _M_X64=100
  define: _M_AMD64=100
  define: __STDC_HOSTED__=1
  define: __cplusplus=201703L
  define: __STDCPP_DEFAULT_NEW_ALIGNMENT__=16ULL
  define: __STDC_UTF_16__=1
  define: __STDC_UTF_32__=1
  stdver: --ms_c++latest
  intelliSenseMode: msvc
Checking for syntax errors: file:///d%3A/test/test1/test.cpp
queue_update_intellisense for files in tu of: D:\TEST\TEST1\TEST.CPP
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/test/test1/test.cpp
queue_update_intellisense for files in tu of: D:\TEST\TEST1\TEST.CPP
textDocument/codeAction: 24
errorSquiggles count: 1
errorSquiggles count: 1
textDocument/codeAction: 25
textDocument/codeAction: 26
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/test/test1/test.cpp
queue_update_intellisense for files in tu of: D:\TEST\TEST1\TEST.CPP
errorSquiggles count: 1
textDocument/codeAction: 27

**Comment by Lennon925** [comment]
In addition, I hope cpptools team can fix "go to definition" bugs as soon as possible. I have raised some bugs since January but no one has been fixed by now.

**Comment by Lennon925** [comment]
> Yeah, I'm not reproing the bug. vector is a system header so it may be important what your compilerPath is set to and what location vector is getting chosen from.
> 
> ![image](https://user-images.githubusercontent.com/19859882/56056374-dec7b280-5d10-11e9-9e40-1889c3aa5d6a.png)
> 
> It's also possible your ipch folder may have corrupted data so deleting that folder might help, and/or setting the intelliSenseCacheSize to 0.
> 
> Can you check the logging I mentioned before, for the includePaths and defines used? The info that is important is output after you open test.cpp for the 1st time. Also, if that folder has case sensitive folders enabled that might cause this issue.
> 
> Do you still have 0.21.0 installed? You could try 0.22.1 or 0.22.2-insiders.

Any update about this?
In addition, if you comment out "typedef unsigned long VOS_INT_TEST_32" this line, "go to defintion" on symbol "VOS_INT_TEST_32" will go to "typedef VOS_INT_Test_32 (*Test22)(int m ,int n);" instead of "No definition"

**Comment by Lennon925** [comment]
@sean-mcmanus ，could you repro this issue?

**Comment by sean-mcmanus** [comment]
@Lennon925 Not sure yet -- we've been busy preparing our 0.23.0-insiders release. We'll try to check after we ship that.

**Comment by sean-mcmanus** [comment]
@Lennon925 I repro the bug now after updating to clang-8 -- it looks like the clang-8 header for vector is somehow causing the #include afterwards to be skipped (reversing the order of the includes causes it to stop reproing). I don't repro this with WSL-clang-6.0 or cl.exe.

**Comment by sean-mcmanus** [comment]
It looks like we need to use clang-x64 mode with -fms-extensions instead of using "msvc-x64" mode. However, in addition to that fix there might be some more bugs, i.e. I'm seeing _Pragma not getting recognized in that mode so there might be more fixes required...

**Comment by Lennon925** [comment]
Any update about this?

**Comment by sean-mcmanus** [comment]
No update. The work hasn't been scheduled yet.

**Comment by suifeng115** [comment]
> No update. The work hasn't been scheduled yet.
hi， I find the same problem in my project.

**Comment by Colengms** [comment]
Hi @Lennon925 Are you still seeing this issue?  I'm not able to repro.  We have since changed how IntelliSense is configured for clang/clang-cl, which likely addressed this issue.  I will close assuming this is fixed, but let us know if you still see a problem.
