### ISSUE TITLE
when debug cpp, variable value read from ifstream is wrong

### ISSUE THREAD

**Issue by shaozi** [microsoft/vscode-cpptools#3451]
Issue Type: <b>Bug</b>

If a variable is read from an ifstream, its values does not update in debug VARIABLES window.
sample code:

```cpp
#include <fstream>
#include <iostream>

using namespace std;

int main()
{
  long long l;
  ifstream input;
  input.open("data.txt");
  input >> l;
  cout << l << endl;
  return 0;
}
```

When run lldb, variable `l` does not update to the read value.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|-psn_0_180268|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx|Twe|0.0.1
Angular2|UVB|0.4.1
angular1-code-snippets|ale|0.0.3
vscode-intelephense-client|bme|1.0.13
systemd-unit-file|coo|1.0.3
vscode-markdownlint|Dav|0.26.0
vscode-eslint|dba|1.8.2
python|don|0.7.0
xml|Dot|2.4.0
auto-close-tag|for|0.5.6
vscode-emacs|hir|0.1.1
rails-snippets|Hri|1.0.8
mysql-syntax|jak|1.3.1
Angular2|joh|7.0.1
graphql-for-vscode|kum|1.13.0
eml|lei|0.3.2
restructuredtext|lex|106.0.0
vue|liu|0.1.5
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
mssql|ms-|1.5.0
python|ms-|2019.3.6558
cpptools|ms-|0.22.2-insiders
Go|ms-|0.9.2
vsliveshare|ms-|1.0.45
debugger-for-chrome|msj|4.11.3
ReactSnippetsWithoutSemicolons|not|1.3.1
vetur|oct|0.18.1
vscode-docker|Pet|0.6.1
diff|raf|0.0.1
tcl|ras|0.1.0
ruby|reb|0.22.3
sass-indented|rob|1.5.1
partial-diff|ryu|1.4.0
language-stylus|sys|1.11.0
ReactSnippets|xab|2.3.0
licenser|ymo|1.3.1
markdown-pdf|yza|1.2.0

</details>

**Comment by brealisty** [comment]
same problem,  debug not work, but the complied file work well.

**Comment by brealisty** [comment]
I did some tests, maybe this problem is due to file path. when use absolute path, it will be ok.

> Issue Type: Bug
> 
> If a variable is read from an ifstream, its values does not update in debug VARIABLES window.
> sample code:
> 
> ```c++
> #include <fstream>
> #include <iostream>
> 
> using namespace std;
> 
> int main()
> {
>   long long l;
>   ifstream input;
>   input.open("data.txt");
>   input >> l;
>   cout << l << endl;
>   return 0;
> }
> ```
> 
> When run lldb, variable `l` does not update to the read value.
> 
> VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
> OS version: Darwin x64 18.5.0
> 
> System Info
> Extensions (38)

**Comment by BigSamu** [comment]
Hi, 

I am having the same problem. Someone was able to resolve it?

**Comment by brealisty** [comment]
> Hi,
> 
> I am having the same problem. Someone was able to resolve it?

If I remember correctly, it's launch.json's problem. One of setting should be:
"configurations":[
     {
         ...
         "program":"${fileDirname}/${fileBasenameNoExtension}.out",
         ...
}
]

**Comment by BigSamu** [comment]
Hey,

I have something similar redirecting indicating the debugger the working directory. In my case this is the configuration I have in the JSON file:

`"version": "0.2.0",
    "configurations": [
        {
            "name": "g++-10 - Compilar y depurar el archivo activo",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/Exams/Doublets/exec",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: g++-10 build active file"
        }
    ]`

**Comment by brealisty** [comment]
this is mine. show me your code, let me take a test.
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            // "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}

**Comment by brealisty** [comment]
I have change my launch.json file:
the "fileDirname" to "workspaceFolder", then the debug get some errors.
if your enter file(like main.out) do not in the root path(workspace path), "workspaceFolder" will not work well.

**Comment by BigSamu** [comment]
Hi brestly,

Thanks for the reply. In my case, the debugger does not put me any problems if I don't use ifstream objects. It is something related to VSCode and debugging when your code is receiving some input data throw a ifstream. Here is the code I am working: https://github.com/MSc-CS-Imperial-College-Code-Practice/Doublets if you want to get a try with the Debugger.

Thanks for the help!

Samuel

**Comment by brealisty** [comment]
![test](https://user-images.githubusercontent.com/12651762/103370102-e6dc0d00-4b06-11eb-9ed8-ffdcb91d29fa.png)

？

**Comment by BigSamu** [comment]
Ouuu you were able to load the dictionary. Could you share me the configuration of your launch.json. I think some parameter I am setting incorrectly.

Thanks!

**Comment by BigSamu** [comment]
Hey brealisty,

Just found the problem. I had to use in "cwd": "${fileDirname}" and not "cwd": "${workspaceFolder}". That make sense, because my file words.txt is located in "${fileDirname}" and not "${workspaceFolder}", so the debugger was unable to load the files! Thanks a lot for your help!

Regards,

Samuel
