### ISSUE TITLE
Language server crashed 5 times in 3 minutes.

### ISSUE THREAD

**Issue by jojoclt** [microsoft/vscode-cpptools#3457]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.18362
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.2-insiders
- Other extensions you installed (and if the issue persists after disabling them): IORun
- A clear and concise description of what the bug is.

I Just Install VSCode with clean install and install cpptools. Without doing anything, when I open cpp files. It shows an error

**Screenshots**

![Screenshot (66)](https://user-images.githubusercontent.com/4539395/56011848-d15ff780-5d13-11e9-87f4-4b7c9af930f9.png)
![Screenshot (67)](https://user-images.githubusercontent.com/4539395/56011866-e9377b80-5d13-11e9-805e-0c4ebdce692e.png)

**Comment by sean-mcmanus** [comment]
Can you attach the C/C++ debugger to the Microsoft.VSCode.CPP.Extension.exe process before it crashes and then open a file to cause the crash and get a call stack? The launch.json settings for attaching are below (ignore the "name"):
![image](https://user-images.githubusercontent.com/19859882/50493835-c6878e00-09d4-11e9-9f03-58eb87ca8f50.png)
"symbolSearchPath": "http://msdl.microsoft.com/download/symbols"

I assume this is a 0.22.2-insiders regression, right?

**Comment by jojoclt** [comment]
I already tried attach to the Microsoft.VSCode.CPP.Extension.exe. But it is no where to be found. This problem is happening to me in the non-insiders as well.
`
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "(Windows) attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "symbolSearchPath": "http://msdl.microsoft.com/download/symbols",
            "logging": {
                "engineLogging" : true
            }
        }
        
    ]
`
I checked at running extension when I first running the program "C/C++" is nowhere to be found.
![image](https://user-images.githubusercontent.com/4539395/56074370-46e2cb00-5ddb-11e9-882b-9f1c4e5aa3f6.png)

**Comment by sean-mcmanus** [comment]
If you don't have a `/.vscode/c_cpp_properties.json` then you have to first run a C/C++ command in order to make the extension process start (without opening a .cpp file).

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
