### ISSUE TITLE
The data type\identifier is both defined and undefined;

### ISSUE THREAD

**Issue by NikolaiTour** [microsoft/vscode-cpptools#3458]
**Type: LanguageService**

Setting focus on the data type\identifier in code, IntelliSense shows the message if the data type\identifier is both defined (and, if "#define", how it expands) and undefined. The screenshot attached; 
At the same time some "#include" directives doesn't take an effect; 

Changing c_cpp_properties.json and settings.json hasn't taken an effect; 

![Annotation 2019-04-12 123617](https://user-images.githubusercontent.com/37363368/56014854-1cccd280-5d21-11e9-96e9-7db0218f90d6.png)

**Describe the bug**
- OS and Version: Windows 10 Pro 1809;
- VS Code Version: 1.33.1 (system setup);
- C/C++ Extension Version: 0.22.1;
- Other extensions you installed (and if the issue persists after disabling them): 
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
The "undefined" is from our IntelliSense parser. The "NULL" being defined is from a different "Tag Parsing" mode, which is being shown there because IntelliSense for the hover isn't currently available for some reason. If you [enable debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and then hover you may see some info that explains why the hover is failing to get the IntelliSense results.

Your includePath and/or compilerPath maybe incorrect and unable to find stddef.h.

The expected result is:
![image](https://user-images.githubusercontent.com/19859882/56058511-69f77700-5d16-11e9-8d4d-1c622bc1eb74.png)

**Comment by mikegormack** [comment]
I have the same issue:

![image](https://user-images.githubusercontent.com/46801399/57197569-0979f380-6fbd-11e9-892a-cdc9b40e6647.png)

Hovering does not give a reason for the failure to get intellisense result. This is all the output returns for the hover:

> textDocument/hover: 120

The source file for the define is in the includePath

**Comment by sean-mcmanus** [comment]
@slademcthornbody Can you locate the definition of "NVM_BL_IMAGE_TYPE_FLAG"? What does hovering over the definition show? Something is causing IntelliSense parsing to not find the definition, possibly a missing define (or a parsing error/bug).

**Comment by mikegormack** [comment]
This is what the hover shows:

![image](https://user-images.githubusercontent.com/46801399/57260254-e7fd3280-70b6-11e9-811e-2238a6dda082.png)

Debug output shows textDocument/hover: as above

**Comment by sean-mcmanus** [comment]
@slademcthornbody If you have 0.23.0-insiders2 can you run the C/C++: Log Diagnostics command with the file that defines the macro to see if there's any unexpected output? Are these errors only occurring with certain uses of the macro? What happens if you have a new file with just
```
#include <MacroHeader.h>
int func() { return NVM_BL_IMAGE_TYPE_FLAG; }
```

**Comment by mikegormack** [comment]
Hi Sean.

Looks like I was on the default release - have upgraded to 0.23.0 insiders 2 and the problem has gone. I was previously on an insiders release and recalled this problem was present so perhaps it was insiders 1

**Comment by mikegormack** [comment]
Please disregard the above - was not related to the cpp version. The file with the issue had its header included twice, which is no problem for the compiler (given ifndef in the header) but must have confused intellisense. Something i changed just before I upgraded.

**Comment by sean-mcmanus** [comment]
@slademcthornbody Yes, I remember a bug a year or so ago where a duplicate header would cause IntelliSense to think the macros were undefined, but I can't locate that bug and it's not reproing for me. Any ideas how to get this to repro?

**Comment by mikegormack** [comment]
@sean-mcmanus I found that I can reproduce when there are other defines between the duplicates but when the duplicate defines are next to each other there is no issue. 

This repros the issue:

#include "app_timer.h"
#include "hal_flash.h"
#include "hal_encrypt.h"
#include "Clock.h"
#include "NVM_Parameters.h"
#include "hal_flash.h"

This doesn't:

#include "app_timer.h"
#include "hal_flash.h"
#include "hal_flash.h"
#include "hal_encrypt.h"
#include "Clock.h"
#include "NVM_Parameters.h"

**Comment by mikegormack** [comment]
@sean-mcmanus  do you need further info for this issue? Thanks

**Comment by sean-mcmanus** [comment]
Yeah, I'm still not able to repro this issue. @michelleangela @Colengms Are any of you guys able to repro this? I was able to repro this a few months ago.

**Comment by mikegormack** [comment]
My project is embedded and has a large number of files. Unfortunately its commercial so its not easy to share the project. Anything I can do to help debug?

**Comment by sean-mcmanus** [comment]
Are you able to create a simple dummy folder with a single .cpp/.h to repro this? I tried, but wasn't able to repro it so maybe the repro requirements are more complex.

**Comment by bobbrow** [comment]
Does `hal_flash.h` have an include guard?  Or is it changing preprocessor defines based on the contents of `hal_encrypt.h`, `Clock.h`, `NVM_Parameters.h`?

**Comment by mikegormack** [comment]
Yes it does. I found that the problem was due to two files with the same name within an SDK (for different SDK configurations) being in the include path. Due to the complexity of the project and the dependencies it is hard to determine what exactly it was tripping up on. Either way if it was possible to display a more sensible error message this would be helpful. Cheers

**Comment by bobbrow** [comment]
Sorry, does your "yes" apply to the include guard question or the changing preprocessor defines question?

And are you saying that you solved the problem by fixing your includePath?

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
