### ISSUE TITLE
Intellisense fails with multiple VS Code instances active

### ISSUE THREAD

**Issue by noxabellus** [microsoft/vscode-cpptools#3459]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: Latest
- C/C++ Extension Version: Latest
- Other extensions you installed (and if the issue persists after disabling them): Nothing pertaining to C/C++, and it does persist.
- When I have more than one instance of VS Code open, the language server crashes after a few files have been opened

**To Reproduce**
1. Open two separate c/c++ projects in different instances of VS Code
2. Open one or more files in each instance
4. Intellisense features such as error detection, auto completion, and comment documentation display, stop working

**Comment by sean-mcmanus** [comment]
Are you opening the same the workspace folder/files in 2 VS Code instances? It's possible our IntelliSense cache is causing an issue in this case if 2 instances try to use to use it at the same time. You might want to try setting the intelliSenseCacheSize to 0 to see if that fixes it.

**Comment by noxabellus** [comment]
> Are you opening the same the workspace folder/files in 2 VS Code instances?

This happens when opening different workspaces

**Comment by sean-mcmanus** [comment]
Can you enable debug logging and see if there are any errors shown? https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md

Is your databaseFilename setting for the 2 different projects point to the same file?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
