### ISSUE TITLE
"C_Cpp.clang_format_formatOnSave" doesn't work

### ISSUE THREAD

**Issue by liushuikong** [microsoft/vscode-cpptools#346]
"C_Cpp.clang_format_formatOnSave": true

**Comment by liushuikong** [comment]
The system is Ubuntu 16.04. The version of vscode is 1.7.1

**Comment by ThadHouse** [comment]
I noticed this on Windows 10 as well. I believe it is somehing wrong with the `"C_Cpp.clang_format_fallbackStyle"`  setting, as removing that seemed to solve the issue. I also added `"editor.formatOnSave": true,`, but I don't remember if that was explicitly needed to fix the issue or not.

**Comment by sean-mcmanus** [comment]
Yeah, it looks like C_Cpp.clang_format_formatOnSave doesn't work anymore after VS Code added the editor.formatOnSave option. The editor.formatOnSave option should be used.

**Comment by bobbrow** [comment]
We have removed this setting.  Please use VSCode's `editor.formatOnSave` setting instead.
