### ISSUE TITLE
peek definition find both headers

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3461]
- OS and Version: Windows 10
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.1

I have Visual Studio Build Tools installed in the default location and Mingw64 installed at C:\mingw64, and build-essential installed in WSL. And I want to use mingw64.
I just need to config c_cpp_properties like this before：

``` json
{
    "configurations": [
        {
            "name": "MinGW",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compilerPath": "C:/mingw64/bin/gcc.exe",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```
but now after I set like this, the peek definition will still find Visual C++ headers. 
![cpptools-bug](https://user-images.githubusercontent.com/43626829/56071512-ac29c280-5dc1-11e9-88ba-7cbe0e53f939.PNG)

![cpptools-bug](https://user-images.githubusercontent.com/43626829/56071683-67525b80-5dc2-11e9-9c29-f6c455d08f7e.PNG)

And if I change back to the default settings(delete the c_cpp_properties.json file and use the default Windows setting) now, it will also find both headers in mingw64 folder and VS folder, seems to remember something. Before I set the the compilerPath to mingw64 gcc, it seems to only find the VC++ headers(I'm not very sure about this).

When set "intelliSenseMode" to "gcc-x64", and not specify the compilerPath(use default cl.exe, I think?), it'll only find headers in the WSL.

Did I do somthing wrong? Or need more config? I want to see the proper mingw64 headers only.

**Comment by sean-mcmanus** [comment]
Can you try doing a Reset IntelliSense Database command? It may not have updated the database.

If that doesn't work you'll want to [enable debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md)

And see why it is picking up the MSVC paths incorrectly.

**Comment by ghost** [comment]
> 
> Can you try doing a Reset IntelliSense Database command? It may not have updated the database.
> 


Reset IntelliSense Database is useful. And I find a way to reproduce:

just set "compilerPath": "C:/mingw64/bin/gcc.exe",
            "intelliSenseMode": "msvc-x64"(or do not set it because it's default)

now Peek Definition will find both headers even after you change back to the proper combination.

**Comment by sean-mcmanus** [comment]
It sounds like there's a bug with the database not being correct if an invalid compilerPath and intelliSenseMode is used.

**Comment by bobbrow** [comment]
We believe we fixed the issue that caused you to need to reset the DB.

We can't guarantee the behavior if the project is configured incorrectly.  We show errors in the configuration UI/JSON for this case now to help reduce the confusion around configuration.
