### ISSUE TITLE
how to watch memory in debug window

### ISSUE THREAD

**Issue by xspeed1989** [Microsoft/vscode-cpptools#3462]
Type: Debugger
  can type any command to view mem in debug window

**Comment by pieandcakes** [comment]
if you use the debugConsole, `-exec info registers` will display memory registers.

**Comment by xspeed1989** [comment]
on windows vc toolchain 
how can i do this/

**Comment by xspeed1989** [comment]
> if you use the debugConsole, `-exec info registers` will display memory registers.
how can i do this/

**Comment by pieandcakes** [comment]
@xspeed1989 You can't do this with the current VC toolchain as the VIsual C++ debugger  does not support commandline queries. There would need to be implemented a way for VS Code Debug Protocol to support memory registers.
