### ISSUE TITLE
C/C++ doc comments preview doesn't react to newlines

### ISSUE THREAD

**Issue by std282** [microsoft/vscode-cpptools#3464]
Issue Type: <b>Bug</b>

## Brief description

When I look at documentation comments with IntelliSense, they do not have any newlines. It makes doc comments greatly less readable, since every paragraph of comment ends being merged into one big chunk of text.

## Steps to reproduce

To observe this behaviour, do the following:
1. Create function or something else that can be documented.
2. Make doc comment for it, using either ``//`` or ``/** ... */`` style.
3. Hover the mouse cursor over the function (or whatever you created) name.
4. Look at popped-up text.

## Example

What I write:

```
/**
 * The first line of doc comment.
 * 
 * The second line of doc comment.
 */
```

What I get:

> The first line of doc comment. The second line of doc comment.

Extension version: 0.22.2-insiders
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
We're tracking this issue with https://github.com/Microsoft/vscode-cpptools/issues/2937. It's something we want to fix, but we're not sure when yet.

**Comment by sean-mcmanus** [comment]
0.23.0-insiders has enabled newlines in doc comments.
