### ISSUE TITLE
#include completion should sort files starting with underscores last

### ISSUE THREAD

**Issue by philong6297** [microsoft/vscode-cpptools#3465]
- OS and Version: Windows 10 Enterprise LTSC Redstone 5
- VS Code Version:  1.33.1
- C/C++ Extension Version:  0.22.1
- Other extensions you installed (and if the issue persists after disabling them):
  - CMake Extension: 0.0.17
  - CMake Tools Extension: 1.1.3
  - MinGW kit : x86-64 8.1.0
  - CMake: 3.14.1

I want to make the intellisense only provide suggestion for only STL header files (iostream, type_traits, ...), not show any other files in the compiler kit. Let me use some screenshots to explain my desire: 
- I didn't include ``type_traits``, but still have suggestion for this. What i want is it will only show suggestion depend on the include: 
![image](https://user-images.githubusercontent.com/29605147/56097718-68020380-5f22-11e9-8c9d-c9fcec62cc0a.png)
- The ``GL`` folder and the other files start with ``__...`` is implement files MinGW, i dont want to browse for these files in ``#include``.  What i want is whenever i use ``#include`` it will only show STL headers and files in my folder root: 
![image](https://user-images.githubusercontent.com/29605147/56097768-e9f22c80-5f22-11e9-8c0c-fbeee229daae.png)
- My MinGW STL library is in ``C:/Program Files/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++``, so i include it in both ``includePath`` and ``browse.path`` in configuration: 
![image](https://user-images.githubusercontent.com/29605147/56097798-4d7c5a00-5f23-11e9-8c15-7aac5f51be84.png)
- In workspace settings file, i exclude entire mingw folder, i expected it will exclude "the other files" that i described above but it didn't work:
![image](https://user-images.githubusercontent.com/29605147/56097905-6f2a1100-5f24-11e9-96c4-f00da1904abb.png)

**Comment by sean-mcmanus** [comment]
"**/mingw64/**" is a file-based exclusion. Can you change it to a folder-based exclusion of "**/mingw64" or change the C_Cpp.exclusionPolicy setting?

**Comment by philong6297** [comment]
I tried both way as you said but it didn't work

**Comment by bobbrow** [comment]
Coming back to this issue:
1. `type_traits` is included by `iostream` and we don't have a way to selectively exclude symbols from included headers.
2. auto-complete usually sorts symbols starting with `_` to the end of the list.  It looks like we aren't doing this for headers.  (bug)
3. You shouldn't need to add system include paths to `includePath` and `browse.path` in your configuration.  We query the compiler in `compilerPath` to fill these in automatically.
4. The exclude glob patterns don't apply outside of the ${workspaceFolder}.  I don't think there's a way to achieve this.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
