### ISSUE TITLE
IntelliSense failed to autocomplete or click-jump to workspace headers, but extern headers work well

### ISSUE THREAD

**Issue by rj-leichen** [microsoft/vscode-cpptools#3467]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1809
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.2-insiders
- Other extensions you installed (and if the issue persists after disabling them): Go, LuaCoderAssist, robotframework. Not working even disabling them all except C/C++.
- A clear and concise description of what the bug is:

I have added `"${workspaceFolder}/**"` under `includePath` sector of `c_cpp_properties.json`, together with external include paths. The headers in external paths work well, click-jumping and completion etc, but the headers within` ${workspaceFolder}` cannot be click-jumped nor auto-completed.

There used to be error messages that header cannot be found when I used `MINGW` as `compilerPath`. After I changed `compilerPath` to `clang`, there were no error messages but still no click-jumping or completion. ~~However, all symbols defined within headers under workspace path are resolvable, and click-jumping works fine on symbols.~~ Edit: I find only after I have manually opened the headers would the symbols be parsed. Any headers not opened manually still remain inert.

I have gone through similar issues but non work for me.

**To Reproduce**
c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "D:/Documents/header/org_wlan",
                "D:/Documents/header/linux"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Expected behavior**

Headers under workspacepath can be parsed.

**Screenshots**

**Additional context**

**Comment by bobbrow** [comment]
There could have been an issue with case-sensitive files and WSL here.  We recommend using the Remote-WSL extension released by the VS Code team for all WSL development.  If you continue to have problems, we can reopen the issue and investigate further.
