### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by weiguoquan422** [microsoft/vscode-cpptools#3468]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.1`
- OS Version: `Linux x64 4.9.0-8-amd64`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/wei/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by WardenGnaw** [comment]
Missing attachment and merging with https://github.com/Microsoft/vscode-cpptools/issues/3213
