### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by emnik** [microsoft/vscode-cpptools#3469]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.2-insiders`
- OS Version: `Linux x64 5.0.7-200.fc29.x86_64`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/manos/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-cpptools/files/3079210/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

**Comment by WardenGnaw** [comment]
Missing attachment and merging with https://github.com/Microsoft/vscode-cpptools/issues/3213
