### ISSUE TITLE
intelliSence does not search the path for special case path

### ISSUE THREAD

**Issue by winggan** [microsoft/vscode-cpptools#3471]
**Type: LanguageService**

**Describe the bug**
- OS:  Microsoft Windows 10.0.17134.0
- C/C++ Ext: 0.22.1
- Description:
   - IntelliSence cannot search and open headers in custom 'includePath' if the path contains character '-' (the minus notation)

**Comment by sean-mcmanus** [comment]
I'm not able to repro the bug -- can you provide more info? I may not be understand what you mean for the repro. What exactly is your includePath? My includePath used `${workspaceFolder}/test-path`.

![image](https://user-images.githubusercontent.com/19859882/56330693-0f0eb700-613e-11e9-9610-ed4c5caf1dfb.png)

**Comment by winggan** [comment]
Sorry, I have edited the issue

I found that '-' is not the case, and I am now confused about what is going on.

The special path I found not working is 'r:/Archieve/caffe-dep/include/'

Captical is not the case because 'r:/Tmp/caffe-dep/include/' work properly. So 'Archieve' maybe a magic word？

**Comment by sean-mcmanus** [comment]
Do the folders that fail to work have case sensitivity enabled? We don't support that yet (we have another issue tracking that).

**Comment by winggan** [comment]
"case sensitivity enabled" means a setting in vscode or in this extension？
There is only directory named "Archieve" in R:, without directory or file named "archieve" at the same time. 
And also windows filesystem is not case sensitive.

**Comment by sean-mcmanus** [comment]
Windows 10 enabled the ability to set folders to be case sensitive, using the fsutil.exe.

**Comment by winggan** [comment]
Thank you!
I gonna close this issue for now as it cannot be reproduce by you
