### ISSUE TITLE
Cannot correctly identify constants

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode-cpptools#3472]
Issue Type: <b>Bug</b>

Sorry,My English is not good.
c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Win32",
            "compilerPath": "C:/Compiler/MinGW64/bin/g++.exe",
            "intelliSenseMode": "gcc-x64",
            "cppStandard": "c++98"
        }
    ],
    "version": 4
}
```
code.cpp
```cpp
#include <cmath>

const int N = 200000, M = sqrt(N);
bool a[M + 1];
```
Intellisense shows
```
expression must have a constant value -- the value of variable \"M\" (declared at line 3) cannot be used as a constant",
```
But gcc successfully compiled it.
Is this undefined behavior?

Extension version: 0.22.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
I filed a VS bug at https://developercommunity.visualstudio.com/content/problem/543980/cc-intellisense-expression-must-have-a-constant-va.html -- you can login with your GitHub account to upvote that. The global variable case only works with gcc and not clang, so it's possible that case might not get fixed with the clang compilab le case.

**Comment by sean-mcmanus** [comment]
This was fixed for the local case where the variable length array is in a non-global scope -- is that sufficient? The global case in your repro doesn't compile with clang (only gcc). I could file a new VS bug for the global case if you want.

**Comment by mxdh** [comment]
@sean-mcmanus Thank you, this is sufficient.
