### ISSUE TITLE
[Feature] An option to move the activity bar to the top

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3473]
Currently you have the activity bar on the left side, would an option to have it at the top be good?

For example VS for mac has a menu bar like so:

<img src="https://i.imgur.com/42laKxz.png">

Vscode top menu bar would look similar (better than this screenshot)

<img src="https://i.imgur.com/DmzpG6N.png">

**Comment by WardenGnaw** [comment]
The cpptools extension does not have control over the activity bar. Please file this issue to the [VS Code GitHub Repo](https://github.com/Microsoft/vscode/issues).
