### ISSUE TITLE
IntelliSense can't find my system headers

### ISSUE THREAD

**Issue by ridiculousfish** [microsoft/vscode-cpptools#3474]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Mojave 10.14.4
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them): n/a
- A clear and concise description of what the bug is:

VSCode is complaining about not being able to find lots of system headers. I'll focus on `unistd.h`:

<img width="850" alt="Screen Shot 2019-04-15 at 10 15 44 PM" src="https://user-images.githubusercontent.com/920838/56183639-25950100-5fcc-11e9-8dc7-3430756f7e02.png">

[Here is my c_cpp_properties.json](https://gist.github.com/ridiculousfish/7d96240574da1e050d3a8ed67a4078f4).

Note this specifies an `includePath`. The file `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h` is a normal file and is what I expect to be found by IntelliSense for `unistd.h`.

The `compile_commands.json` is CMake generated, [here it is](https://gist.github.com/ridiculousfish/ab15151ae2c11bc4b2dca2aba6b236d3).

The build succeeds in this directory, it is only IntelliSense which cannot find the headers.

**Comment by sean-mcmanus** [comment]
I think you need to set your compilerPath to something like `/usr/bin/c++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk`. We're tracking auto-processing that flag with https://github.com/Microsoft/vscode-cpptools/issues/1575 .

Are you able to get that to work?

**Comment by ridiculousfish** [comment]
Yes I think it's working, it's stopped complaining about headers and command-click has reasonable looking suggestions. Thanks for the quick help!!
