### ISSUE TITLE
Question：Parameter about intelliSenseCacheSize  and intelliSenseCachePath 

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3475]
I noticed that cpptools added setting parameter 'intelliSenseCacheSize ' and 'intelliSenseCachePath ' from version 0.22.  I read the release document and it wrote like this "Add AutoPCH support to reduce IntelliSense parsing time".  It will be helpful to raise the speed of going to definition?

**Comment by sean-mcmanus** [comment]
No, it probably will not make Go to Definition faster, unless the Go to Definition happens to be blocked by IntelliSense parsing. It's designed to reduce the time spent on IntelliSense parsing "on open" and "after edits", i.e. a subset of the time the red flame is showing. The speedup is equivalent to the time that would have been spent parsing the headers.

And some users have reported it slowed their OS down -- we still need to investigate that (i.e. find a repro).

**Comment by Lennon925** [comment]
> No, it probably will not make Go to Definition faster, unless the Go to Definition happens to be blocked by IntelliSense parsing. It's designed to reduce the time spent on IntelliSense parsing "on open" and "after edits", i.e. a subset of the time the red flame is showing. The speedup is equivalent to the time that would have been spent parsing the headers.
> 
> And some users have reported it slowed their OS down -- we still need to investigate that (i.e. find a repro).

Thanks for your reply
