### ISSUE TITLE
only the first 1000 children of one variable are shown

### ISSUE THREAD

**Issue by juancarlossanchez** [microsoft/vscode-cpptools#3477]
Type: Debugger

I have a std::list with 64000 elements, but on VARIABLES tab only the first 1000 elements are shown, is there any way to change this value?

**set print elements** doens't help

**Comment by sean-mcmanus** [comment]
A year ago it only showed 500 elements. @WardenGnaw Did it get increased to 1000? Can it be configured?

**Comment by WardenGnaw** [comment]
The 1000 is by design, https://github.com/Microsoft/MIEngine/blob/ab694ea25feaa52e33abb5e400831a07baec223b/src/MICore/CommandFactories/MICommandFactory.cs#L357
