### ISSUE TITLE
Question : Any advise about raising the speed of "go to definition”

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3480]
Currently I have a folder which have about 50000 files and 6-7 subfolders generations. Sometimes it will cost long time to go to definition. Any advise to raise the speed to go to definition?

The speed is related to the amount of subfolders generations ? If I just choose some folder to add a new workspace, it will be helpful to raise the speed of "go to definition"?

**Comment by sean-mcmanus** [comment]
Is the Go to Def using IntelliSense to check the types? i.e. if you use Go to Def on a commonly named entity like "length" does it only go to the definition for the correct types?

One known issue is with large files: https://github.com/Microsoft/vscode-cpptools/issues/3126 , if the slowness occurs when the target file is large.

We do a database query for files and then run IntelliSense to check the types....so it depends on which part is slow. What process is using CPU when it's slow? Are you able to attach a debugger and see the call stacks? Repro projects that exhibit slow Go to Definition have been hard for us to locate so let us know if you know of any.

**Comment by Lennon925** [comment]
> Is the Go to Def using IntelliSense to check the types? i.e. if you use Go to Def on a commonly named entity like "length" does it only go to the definition for the correct types?
> 
> One known issue is with large files: #3126 , if the slowness occurs when the target file is large.
> 
> We do a database query for files and then run IntelliSense to check the types....so it depends on which part is slow. What process is using CPU when it's slow? Are you able to attach a debugger and see the call stacks? Repro projects that exhibit slow Go to Definition have been hard for us to locate so let us know if you know of any.

How to check Go to Def is using IntelliSense to check the types?  it only go to the definition for the correct types on the following code.

void Test23(){
  Student *student = new Student();
  student->length = 0; // it's ok
}

It is hard to locate because it is slow sometimes

**Comment by yaweiw** [comment]
@sean-mcmanus  we also noticed the code nagvigation performance e.g. F12 has something to do with the size of .BROWSE.VC.DB. For instance if we partition the single monolith .BROWSE.VC.DB into multiple ones (each ~600MB) by using multi-root workspace we gain much better performance. I think it relates to how sqllite querys db. Is cpptools language server's server side code open sourced somewhere? Can't find it here though.

**Comment by sean-mcmanus** [comment]
One way is to do Go to Definition on a local variable, which only works with IntelliSense. If the database querying is slow, then the Go to Definition will be slow even when the intelliSenseMode is set to "Tag Parser".

Also, if you could attach a debugger to the process that is using CPU and get a call stack, that would help. If you're on Windows, the symbols can be obtained via setting "symbolSearchPath" to "https://msdl.microsoft.com/download/symbols".

**Comment by sean-mcmanus** [comment]
@yaweiw Yes, we do a SQL query of the .browse.vc.db for global symbols across a workspace. The cpptools language server side code is not open sourced, although SQLITE is open source. How large is the single monolith database? I haven't noticed any issues with SQLITE query performance in the past. Do you know if this performance issue is a regression from some point?

Using files.exclude to remove folders might help.

**Comment by sean-mcmanus** [comment]
I got Go to Def to be slow using chromium with a 1.4 GB database (after removing a file that crashed our extension), but it was slow sometimes because it was getting blocked by an in flight IntelliSense operation (red flame). If you check your log and/or attach a debugger you should be able to see what operation is blocking the Go to Def.

**Comment by yaweiw** [comment]
@sean-mcmanus, I wasn't aware of performance metrics for the past. the recent repo i got is around 40 million lines of code with db size some 1.6 GB. Even with this one, F12 on certain functions/symbols works better than others, when those symbols are in the same directory. as i understand, tag parser is the one that generates browse db, would it be possible to partition the db so that it doesn't grow through the roof? Or was it possible to do some tweaks on query side? If you look at SourcceInsight, they've done great on the same repo.

**Comment by yaweiw** [comment]
@sean-mcmanus I'd happy to take a memory dump or attach a debugger to take a look what's blocking. which process is it? *.CPP.Extension?

**Comment by sean-mcmanus** [comment]
It's Microsoft.VSCode.CPP.Extension.exe.

You're saying it's faster if the database is split into smaller pieces? That would suggest that database querying might be the cause. I'm not sure why I wasn't reproing the issue on chromium -- I did see database query slowness in Debug mode, but it was fast in Release.

Splitting the database into smaller pieces won't really work.

**Comment by yaweiw** [comment]
I'll take a dump and get back with what i find. thanks Sean.
