### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tarbear123** [microsoft/vscode-cpptools#3482]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
-Game Development with Visual Studio
- Live Share
- Microsoft Visual Studio Test Platform

- A clear and concise description of what the bug is.
i can't seem to find the path to put in the "includePath", can you plz post where to go in file explorer?
**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/38800609/56322067-46bd3500-6125-11e9-933b-5558a602dc0b.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
You should remove the "/usr/include" and "/usr/local/include" and instead set your compilerPath setting.

Does your build system generate a compile_commands.json? You only need to set that if you're using something like CMake that generates that.

**Comment by tarbear123** [comment]
[do i just go into the path, fint the "include" library and add the path to the code?
![image](https://user-images.githubusercontent.com/38800609/56385731-34063700-61dd-11e9-9536-3ac0db5c8545.png)
](url)

![image](https://user-images.githubusercontent.com/38800609/56385856-7b8cc300-61dd-11e9-9ce3-d31b9c8198e5.png)

**Comment by sean-mcmanus** [comment]
This is a bug caused by the PlatformIO extension. I think they fixed it though. What version of the PlatformIO extension do you have? You can also change the C_Cpp.default.enableConfigurationSquiggles to false -- if you have 0.22.2-insiders (i.e. set the C_Cpp.updateChannel to "Insiders").

**Comment by tarbear123** [comment]
i don't have the platformio extension

**Comment by sean-mcmanus** [comment]
Then what are the ".platformio" paths? PlatformIO had a bug where they were creating a c_cpp_properties.json without a version, causing a problem with corrupted documents to occur with VS Code. Why is version missing from the c_cpp_properties.json? We check for that and add it if it doesn't exist, so another tool must be creating that.

**Comment by tarbear123** [comment]
well i do have a platform folder from when i used the app

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
