### ISSUE TITLE
Disable debug heap by default with cppvsdbg

### ISSUE THREAD

**Issue by Djoulihen** [microsoft/vscode-cpptools#3484]
I investigated some performance issues when debugging with vscode using cppvsdbg on code that did a lot of allocations. I was confused by the fact that using Visual Studio 2017 to debug the same executable did not show the same slow-down.

After finding this issue  #1121 I confirmed that the culprit was the debug heap used by vsdbg.exe. As for the difference with Visual Studio itself, it seems that the debug heap is deactivated by default since VS 2015 (as explained here: https://devblogs.microsoft.com/cppblog/c-debugging-improvements-in-visual-studio-14/) because its value is limited.

So I would suggest that the vscode-cpptools extension also deactivate the debug heap by default when using cppvsdbg. That would make the behavior consistent with VS itself and avoid some hard-to-track performance issues when debugging.

----------------------------------------------------------------------------------------------------
For reference here is the result of my experiments.

I made the following test program:
```
#include <chrono>
#include <iostream>
#include <string>
#include <vector>

int main()
{
	size_t const NB_VECTORS = 3000;
	size_t const VECTOR_SIZE = 200;

	std::cout << "Test program started" << std::endl;

	std::chrono::steady_clock::time_point start = std::chrono::steady_clock::now();
	std::string testString("This is my test string");

	for (size_t i = 0; i < NB_VECTORS; ++i)
	{
		std::vector<std::string> myVec;

		for (size_t j = 0; j < VECTOR_SIZE; ++j)
		{
			myVec.push_back(testString);
		}
	}

	std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
	std::chrono::milliseconds elapsedSec = std::chrono::duration_cast<std::chrono::milliseconds>(end-start);
	std::cout << "Finished after " << elapsedSec.count() << std::endl;

	return 0;
}
```

Compilation was done using `cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\test_program.dir\main.cpp.obj /FdCMakeFiles\test_program.dir\ /FS -c C:\dev\tests\cppvsdbg_test\main.cpp`

Running with the debugger in VS 2017 takes 2332ms. It takes 19808ms with vscode and cppvsdbg.

Setting `"environment": [{"name":"_NO_DEBUG_HEAP", "value": "1"}]` in launch.json solves the issue.

**Comment by sean-mcmanus** [comment]
Fixed with 0.23.0-insiders.
