### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Googlei** [microsoft/vscode-cpptools#3485]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\wilhe\ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
See https://github.com/Microsoft/vscode-cpptools/issues/3213
