### ISSUE TITLE
no environment file support for MSVC debug configuration

### ISSUE THREAD

**Issue by kejxu** [microsoft/vscode-cpptools#3490]
Type: Debugger

for a common launch configuration:
```json
{
    "name": "(msvc) Launch",
    "type": "cppvsdbg",
    "request": "launch",
    "program": "${workspaceFolder}/out.exe",
    "args": [],
    "stopAtEntry": true,
    "cwd": "${workspaceFolder}",
    "environment": [],
    "externalConsole": false
}
```

is there any plan to add support for environment variable definitions file (similar concept in [python debugger](https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file)) aside from the current `environment` key-value list?

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.23.0-insiders2: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.23.0-insiders2

**Comment by kejxu** [comment]
Thanks for updating on this @pieandcakes! We are currently staffing at //build, and will be testing this fix out afterwards. Would you want us to close this issue once we verify the fix?

**Comment by pieandcakes** [comment]
@kejxu We will close once we ship the official release. I closed it prematurely.

**Comment by sean-mcmanus** [comment]
@kejxu 0.23.0 shipped yesterday with the fix. If there's an issue still we could re-open this.
