### ISSUE TITLE
designator may not specify a non-POD subobject

### ISSUE THREAD

**Issue by xor2k** [microsoft/vscode-cpptools#3491]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.4
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.2-insiders
- Other extensions you installed (and if the issue persists after disabling them): all but cpptools disabled, issue persists
- A clear and concise description of what the bug is: as far as I can judge IntelliSense (just like gcc, see below) has issues with non-POD subobjects.

**To Reproduce**

1. Open a terminal, create a new folder, change directory there, "code ." (new empty workspace)
2. Create a file test.cpp
3. Insert the following content
```#include<vector>

struct bar {
    std::vector<int> x;
    int y;
};

int main(int argc, char** argv) {
    struct bar bar = {
        .y = 5
    };
    return 1;
}
```
4. See error `designator may not specify a non-POD subobject [10, 10]`
5. Install clang-7 `apt-get install clang-7` in terminal and try `clang++-7 test.cpp -o test`, which successfully creates the `test` binary
6. For comparison, `g++ test.cpp -o test` yields
```test.cpp: In function ‘int main(int, char**)’:
test.cpp:11:5: sorry, unimplemented: non-trivial designated initializers not supported
     };
     ^
```
7. Create .vscode/c_cpp_properties.json with the following content
```{
    "configurations": [
        {
            "name": "Linux",
            "defines": [],
            "compilerPath": "/usr/bin/clang-7",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
8. vscode still reports `designator may not specify a non-POD subobject [10, 10]`

**Expected behavior**
Either IntelliSense by itsself or configuring `"intelliSenseMode": "clang-x64"` should make IntelliSense capable of handling non-POD subobjects and not report an error.

**Screenshots**

Should not be necessary.

**Additional context**

Renaming support in vscode-cpptools should have a higher priority, I just stumbled upon the here described issue as well.

**Comment by sean-mcmanus** [comment]
That's a C++20 feature (and clang-specific extension, also implemented in gcc-8) that our IntelliSense compiler hasn't gotten support for yet (even though the latest cl.exe supports it with /std:c++latest).

A different team works on IntelliSense parser stuff so fixing bugs like this doesn't impact "renaming" work.

I've filed a bug at https://developercommunity.visualstudio.com/content/problem/540560/c-intellisense-doesnt-support-designated-initializ.html . You can use your GitHub login to upvote that if you want.

**Comment by xor2k** [comment]
Thank you! I've tried to upvote with my GitHub account, but it did not work out. Is there an upvote-on-visualstudio.com-with one's GitHub account tutorial somewhere?

And another question: the IntelliSense used in vscode (and vscode-cpptools), is it open source? I only know the name IntelliSense from Visual Studio, which is a closed source product.

**Comment by sean-mcmanus** [comment]
Did it not allow you to sign in? You have to click some "Sign in Options" link to see the GitHub login option.

The IntelliSense parsing is closed source for both. Just the TypeScript part is open source.

**Comment by sean-mcmanus** [comment]
Screenshots:
![image](https://user-images.githubusercontent.com/19859882/56775517-325be680-677c-11e9-9700-c9235d5512ee.png)
![image](https://user-images.githubusercontent.com/19859882/56775526-469fe380-677c-11e9-8fcc-165f2f9b9181.png)

**Comment by xor2k** [comment]
I just tried: there is no sign-in options button. Is that feature available in Europe?

![Screenshot from 2019-05-01 17-03-23](https://user-images.githubusercontent.com/3997849/57024109-12bd3600-6c34-11e9-80bb-fcbadac13532.png)

![Screenshot from 2019-05-01 16-59-37](https://user-images.githubusercontent.com/3997849/57023621-d2a98380-6c32-11e9-9dac-231a66080cd7.png)

**Comment by sean-mcmanus** [comment]
Oh -- it looks like that only works if you have your Microsoft account linked to your GitHub account, i.e. it seems to require an actual Microsoft account (i.e outlook email, etc.).

**Comment by xor2k** [comment]
For some reason it now worked, I‘ve just upvoted https://developercommunity.visualstudio.com/content/problem/540560/c-intellisense-doesnt-support-designated-initializ.html

**Comment by xor2k** [comment]
Hey there, what is the state of this issue? Seems to be fixed in Visual Studio:

https://developercommunity.visualstudio.com/content/problem/540560/c-intellisense-doesnt-support-designated-initializ.html

**Comment by sean-mcmanus** [comment]
This is fixed with 0.26.0 -- you need to set the cppStandard to "c++20" though. Let us know if it's not working for you.

**Comment by sean-mcmanus** [comment]
Oh -- I'm seeing it work for gcc and cl.exe, but not clang. Is that what you're seeing? There might be some additional issue for clang.

**Comment by sean-mcmanus** [comment]
The code specifically disables C++20 designated initializer support for clang, because it hasn't been implemented yet -- see https://clang.llvm.org/cxx_status.html .

i.e. we (VS) added support for the C++20 feature and not the c99 extension behavior of gcc and clang prior to C++20.

Are you okay with waiting till clang implements C++20 designated initializers and using that or did you want a new VS bug opened to support for the clang extension pre-C++20 behavior.

**Comment by Colengms** [comment]
The original tracking issue did not completely address the issue.  Opening another issue against VS: https://developercommunity.visualstudio.com/content/problem/1230928/class-type-not-suitable-for-us-with-designators-gc.html

**Comment by sean-mcmanus** [comment]
This is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders (we initially forgot the fix made it in), i.e. designated initializers no longer give squiggles for C++14 or later with clang >= 6 and gcc >= 8 (gcc with C++20 already worked).
