### ISSUE TITLE
Enable bash.exe color schemes during Debug

### ISSUE THREAD

**Issue by aenima1891** [microsoft/vscode-cpptools#3492]
I'm using msys bash.exe as integrated terminal in VSCODE.

![immagine](https://user-images.githubusercontent.com/1100887/56412653-302def80-6285-11e9-9c42-974b1b07f6a3.png)

I'm using color codes in my printf (e.g. "\033[30", "\033[31"), but during the debug, the ccpdbg Terminal is not able to recognize these color schemes, despite the use of bash.exe terminal.

![immagine](https://user-images.githubusercontent.com/1100887/56412774-8ef36900-6285-11e9-88ed-d530869909a1.png)

In red, the text not recognized with the color scheme

**Comment by WardenGnaw** [comment]
This will need to be investigated because the debugger and debug adapter should be forwarding on the color codes to the integrated terminal and the integrated terminal should be consuming the color codes.
