### ISSUE TITLE
Question: Intellisence disregard codes in inactive region?

### ISSUE THREAD

**Issue by OnionSalt** [microsoft/vscode-cpptools#3493]
For example

```
#if DEBUGBUILD
struct debugDataStruct
{
    ...
}
...
#endif
```

I use cl -DDEBUGBUILD=1 to activate that region when I build 

When I trying to use debugDataStruct, the intellisence always says it is undefined.

Is there a way to make intellisence look the codes in inactive region?

**Comment by mxdh** [comment]
Add `-DDEBUGBUILD=1` to `compilerPath` in `c_cpp_properties.json`.
Like `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\Hostx64\x64\cl.exe -DDEBUGBUILD=1`.

**Comment by OnionSalt** [comment]
Thank you !
It worked

Just add it to the "defines" section
