### ISSUE TITLE
Formatting failed

### ISSUE THREAD

**Issue by WangWeiqi1228** [microsoft/vscode-cpptools#3494]
Issue Type: <b>Bug</b>

Formatting failed:
"c:\Users\Omen2018\.vscode\extensions\ms-vscode.cpptools-0.22.1/bin/../LLVM/bin/clang-format.exe" -style="{ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 2, TabWidth: 2, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0 }" -fallback-style="LLVM" -sort-includes=0 -assume-filename="c:\Users\Omen2018\Desktop\ADC—独立模式-单通道-中断\Libraries\STM32F4xx_StdPeriph_Driver\src\stm32f4xx_crc.c"
  Unable to start child process!

Extension version: 0.22.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (9.50GB free)|
|Process Argv|C:\Users\Omen2018\Desktop\ADC—独立模式-单通道-中断|
|Screen Reader|no|
|VM|67%|

</details>
们已经将其写入剪贴板，请粘贴。

**Comment by sean-mcmanus** [comment]
Removing the quotes around the `{ BasedOnStyle…}` should fix it. See https://github.com/Microsoft/vscode-cpptools/issues/3419 . Our next release will have the quotes removed from the documentation text.
