### ISSUE TITLE
Auto-completion / type deduction doesn't work with template

### ISSUE THREAD

**Issue by cynecx** [microsoft/vscode-cpptools#3501]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS 10.14.3
- VS Code Version: 1.34.0-insiders/750680d2f7ae563529501f8ec419d83ccf8ec325
- C/C++ Extension Version: 0.22.2-insiders
- Other extensions you installed (and if the issue persists after disabling them): none
- Autocompletion doesn't work and type inference also doesn't work at the specified location.
 
**To Reproduce**

Code:
```cpp
#include <memory>
#include <atomic>

template <typename Descr>
struct Bar {
    std::atomic<bool> running;

    template <uint32_t num>
    uint32_t getnum() {
        this->running.<|>store(1); // auto completion doesn't work here
        return num;
    }
};

template <typename Descr>
struct Foo {
    std::shared_ptr<Bar<Descr>> mem;

    void test() {
        auto val = mem-><|>template getnum<8>(); // auto completion doesn't work here
        // type of val is `auto`
        auto val2 = mem-><|>getsth(); // auto completion also doesn't work here
    }
};
```

`<|>` is the cursor

**Expected behavior**
Auto-completion and type deduction should work for `val` and `val2`.

**Screenshots**
None needed.

**Additional context**
None.

**Comment by sean-mcmanus** [comment]
I've filed a Visual Studio bug at https://developercommunity.visualstudio.com/content/problem/542773/c-intellisense-completion-fails-to-work-with-windo.html , with slightly modified details. You can login with your GitHub account to upvote that if you want.

Also, it appears that after we implement setting of template args then this issue would have a workaround.
