### ISSUE TITLE
Intellisense only works in *.cpp files but not *.h files

### ISSUE THREAD

**Issue by ziish** [microsoft/vscode-cpptools#3503]
**Type: LanguageService**

**Description**
- OS and Version: Ubuntu 18.04.2
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.1

Behavior is exactly the same as described in issue [2744](https://github.com/Microsoft/vscode-cpptools/issues/2744). 

Also using `vector-of-bool.cmake-tools` extension with its configuration provider but for testing I also disabled it and set the compile_commands.json manually with the same effect. 

**Comment**
I was not able to see anything suspicious in the log windows. If more information is needed I would appreciate a hint how I can collect some useful diagnostics.

**Comment by bobbrow** [comment]
This sounds like #1715, but I'm pretty sure CMake Tools implemented the feature we added for providing the code browsing information to work around it.

If you [Enable Logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and search the logs for "Custom browse configuration received" do you see anything?

**Comment by ziish** [comment]
@bobbrow 
The debug output shows up in the log. What is interesting though is that the paths to the third party libraries are not marked as link (not underlined/clickable). Not sure if this is related. The paths look like this:
```
"/home/daniel/.conan/data/fmt/5.3.0/bincrafters/stable/package/0e4b37fed2418692fca237108ab0fad3283043c2/include",
"/home/daniel/.conan/data/eigen/3.3.7/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/eigen3",
"/home/daniel/.conan/data/boost/1.69.0/conan/stable/package/cabba3b08559858fc9c32b2017ab7a3cb8781a5e/include",
"/home/daniel/.conan/data/zlib/1.2.11/conan/stable/package/35437353b857392790f3121d268b1db3fb9a09b0/include",
"/home/daniel/.conan/data/bzip2/1.0.6/conan/stable/package/35437353b857392790f3121d268b1db3fb9a09b0/include",
"/home/daniel/.conan/data/Catch2/2.7.1/catchorg/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include",
```

**Comment by bobbrow** [comment]
We think this has been fixed in the latest versions of the two extensions.  If not, please let us know and we can investigate further.
