### ISSUE TITLE
Debug configuration could be made more dynamic [sourceFileMap]

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode-cpptools#3504]
Type: Debugger
**Input information below**

**Describe the bug**
- OS and Version: `Microsoft Windows [Version 10.0.18875.1000]`
- VS Code Version:
```
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18875
```
- C/C++ Extension Version:
```
Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.22.2-insiders
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
```
- Other extensions you installed (and if the issue persists after disabling them): N/A
- A clear and concise description of what the bug is:

`Debug configuration` could be configured to be slightly more dynamic:
```json
"sourceFileMap": {"/mnt/c": "${env:systemdrive}/"}
```

**To Reproduce**
1. Open `.vscode/launch.json`
1. While in `C++ Launch`/`(gdb) Bash on Windows Launch`/ configuration scroll down to `sourceFileMap`
1. replace existing `sourceFileMap` with improved more dynamic one:
	```json
	"sourceFileMap": {
		"/mnt/c": "${env:systemdrive}/"
	}
	```
1. Unfortunately the `/mnt/c` could not be optimized further because using `$(wslpath $SYSTEMDRIVE/)` does not seem to work

**Comment by WardenGnaw** [comment]
The variables used in `launch.json` is resolved by VS Code. We take whatever VS Code gives to [`resolveConfigurationProvider`](https://github.com/Microsoft/vscode-cpptools/blob/79609045756ff7944a557067a4992c7f30391f1d/Extension/src/Debugger/configurationProvider.ts#L180) in the `config` parameter and send them along to the debug adapter. The list of variables they support is listed [here](https://code.visualstudio.com/docs/editor/variables-reference), I do not know how far they replace the `${...}` variables. It may be a question to ask on their [issues page](https://github.com/Microsoft/vscode/issues).
