### ISSUE TITLE
GDB with cmdline options like quiet (-q) is possible (not clear from documentation)

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode-cpptools#3505]
Type: Debugger
**Input information below**

**Describe the bug**
- OS and Version: `Microsoft Windows [Version 10.0.18875.1000]`
- VS Code Version:
```
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18875
```
- C/C++ Extension Version:
```
Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.22.2-insiders
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
```
- Other extensions you installed (and if the issue persists after disabling them): N/A
- A clear and concise description of what the bug is:

`Debug configuration` could be configured to make GDB quieter or any other command line parameters.

**To Reproduce**
1. Open `.vscode/launch.json`
1. While in `"C++ Launch"`/`"(gdb) Bash on Windows Launch"` configuration scroll down to `debuggerPath`
1. Replace existing `debuggerPath` quiet version:
	```json
	"debuggerPath": "/usr/bin/gdb -q"
	```

**Comment by WardenGnaw** [comment]
You will want to use [`miDebuggerArgs`](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md#midebuggerargs
). `miDebuggerPath` is just the path to gdb, it does not take the arguments.

**Comment by n3rd4i** [comment]
The answer is incorrect because I forgot to say the most important information and that is that I am using **WSL**.

**Comment by WardenGnaw** [comment]
You can add arguments after `debuggerPath` seperated by spaces but there may be some issues with it so I would not add this to the official documentation for adding args to the `debuggerPath`. 

We should added a `debuggerArgs` variable within pipe transport similar to how `miDebuggerPath` and miDebuggerArgs`.

@n3rd4i Thank you for pointing this out.

**Comment by n3rd4i** [comment]
probably deprecated, will close this
