### ISSUE TITLE
Uncurruct format options.

### ISSUE THREAD

**Issue by sxyugao** [microsoft/vscode-cpptools#3506]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Pro 1809
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.1

Multi code format options like pic below

![](https://i.loli.net/2019/04/22/5cbdb014809c4.png)

**Comment by sean-mcmanus** [comment]
Yes, I've seen this bug as well. It occurs in the multi-root scenario.

**Comment by sean-mcmanus** [comment]
We're tracking this bug via https://github.com/Microsoft/vscode-cpptools/issues/3285 .
