### ISSUE TITLE
How can I use block notation? For example, dispatch_async(queue, ^{})

### ISSUE THREAD

**Issue by MichaelZengLZ** [microsoft/vscode-cpptools#3508]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: macOS Mojave (10.14.4)
- VS Code Version: 1.33.1 
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
I want to use `dispatch_async` function in the VSCode. But the editor seems don't know the block notation. Do you know how could I make it work? 

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Here is my hello_world.cpp
```c++
#include <dispatch/dispatch.h>
#include<pthread.h>
#include <iostream>

using namespace std;

int main() {
    dispatch_queue_t printingQueue = dispatch_queue_create("elevatorBank.printingQueue", NULL);
    dispatch_async(printingQueue, ^{
      cout << "Hello World";
    });
    return 0;
}
```

Here is my launch.json
```JSON
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "clang++ build and debug active file",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "lldb",
      "preLaunchTask": "clang++ build active file"
    }
  ]
}
```

Here is my user space configuration:
```
// Place your settings in this file to overwrite the default settings
{
    "editor.insertSpaces": true,
    "editor.tabSize": 2,
    "editor.formatOnType": true,
    "files.trimTrailingWhitespace": true,
    "terminal.external.osxExec": "iTerm.app",
    "workbench.iconTheme": "eq-material-theme-icons-palenight",
    "window.zoomLevel": 0,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "workbench.colorTheme": "Material Theme Palenight High Contrast",
    "clang.executable": "clang",
    "clang.completion.enable": true,
    "clang.cxxflags": [
        "-std=c++11",
        "-I/your/CPP/include/path1",
        "-I/your/CPP/include/path2"
    ],
    "clang.cflags": [
        "-std=c99",
        "-Ic:/your/C/include/path1",
        "-Ic:/your/C/include/path2"
    ],
}
```

**Comment by bobbrow** [comment]
That looks like Objective-C syntax, and unfortunately our extension doesn't support it at this time.  We do have a feature request open for it (#2533), but it doesn't have many upvotes.
