### ISSUE TITLE
Viewing derived class variables with a base class pointer during debugging

### ISSUE THREAD

**Issue by dhiraj113** [microsoft/vscode-cpptools#351]
Is it possible to view the member variables of a derived class during debugging by hovering the cursor over a base class pointer that points to an object of the derived class.

Currently, the cpptools addon in vscode only shows the base class variables when I hover the cursor over the base class pointer pointing to a derived class object.

**Comment by delmyers** [comment]
Have you tried casting to the type that you are interested in the watch window? We get the type info from the debug engine itself. Are you running on Mac, Linux, or Windows?
