### ISSUE TITLE
Cpptools can't recognize function declaration and function after adding soter annotation macro.

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3510]
Ctrl + Shift + O can't find function declaration and function after adding soter annotation macro.

code as below:

#define AN_NONNULL(...)
void  Eat() AN_NONNULL();

![捕获](https://user-images.githubusercontent.com/39362073/56567756-293a1080-65e8-11e9-9e88-c68f1097419d.PNG)
![捕ddd获](https://user-images.githubusercontent.com/39362073/56568017-aebdc080-65e8-11e9-862a-215e3ba13e07.PNG)

**Comment by sean-mcmanus** [comment]
This is "by design". The macro that require evaluation in order to parse the code correctly need to be added to a cpp.hint file in your workspace. See https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2019 . Let us know if that doesn't work.
