### ISSUE TITLE
Please support network workspace intellisense and debugging

### ISSUE THREAD

**Issue by cuiyongji** [microsoft/vscode-cpptools#3511]
# I like to securely access and remotely debug my code from anywhere, without downloading the code. Avoid forgetting to submit code.I can make vscode a remote web access, but I don't like it, becuse the web client is very fragile.

**Comment by WardenGnaw** [comment]
The editing files remotely will have to depend on https://github.com/Microsoft/vscode/issues/29194.

You can setup a remote launch/attach scenario using [`pipeTransport`](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md#pipe-transport). If you can mount a share to point to the files, you can use [`sourceFileMap`](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md#sourcefilemap) to debug with sources.
