### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kushalchordiya216** [microsoft/vscode-cpptools#3514]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.22.2-insiders`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/kushal/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
See bug https://github.com/Microsoft/vscode-cpptools/issues/3213 and the in-progress fix: https://github.com/Microsoft/vscode-cpptools/pull/3411 .
