### ISSUE TITLE
Problem with C file errors when using CMake Tools

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3518]
I have this same problem, and I am using cmake tools.  I would prefer to *keep* using cmake tools, because it offers me much better support for multiple cross compilation options (cmake toolchains) and better integration with CMake itself.  But it is somewhat annoying that I see warnings that only pertain to C++.  (C99 structure initialization, and also assignment of void * to typed pointers.) 

I have other workspaces which do not use cmake, and they are fine.

I am using VSC on Windows, with Visual Studio 2019, and also with a local copy of gcc set up for cross compilation.

_Originally posted by @gdamore in https://github.com/Microsoft/vscode-cpptools/issues/2545#issuecomment-484979983_

**Comment by gdamore** [comment]
My frustration with this has been growing in the weeks since I originally posted the above.  I'm not sure how I can help provide information, but this is probably the single biggest "detractor" to an ideal user experience for me.  CMake Tools has, in many other ways, made my life so much better.  But this one interop issue is a big gotcha.

If there's anything I can provide to help expedite resolution, please let me know.

**Comment by sean-mcmanus** [comment]
Can you run the C/C++: Log Diagnostics command?

Did you set your compilerPath to the gcc and set any args to it?

Are you using gcc extensions? You might need to set some define like "_GNU_SOURCE" to configure it because we use strict -std=c11 instead of -std=gnu11.

**Comment by sean-mcmanus** [comment]
Oh, this is with CMake Tools...I don't think compilerPath should matter, and the defines should be provided by the CMake Tools.

**Comment by sean-mcmanus** [comment]
We need to know if IntelliSense is incorrectly thinking the file is C++ instead of C and what std version is being used. Also, please copy/paste the error message.

**Comment by gdamore** [comment]
```
-------- Diagnostics - 5/9/2019, 6:46:38 AM
Version: 0.23.0
Translation Unit Mappings:
[C:\Users\garre\Work\nng\src\supplemental\websocket\websocket.c]:
    C:\USERS\GARRE\WORK\NNG\SRC\SUPPLEMENTAL\WEBSOCKET\WEBSOCKET.C
[C:\Users\garre\Work\nng\src\protocol\pubsub0\pub.c]:
    C:\USERS\GARRE\WORK\NNG\SRC\PROTOCOL\PUBSUB0\PUB.C
Translation Unit Configurations:
[C:\Users\garre\Work\nng\src\supplemental\websocket\websocket.c]:
    Process ID: 25616
    Memory Usage: 69 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
    Includes:
        C:\USERS\GARRE\WORK\NNG\INCLUDE
        C:\USERS\GARRE\WORK\NNG\SRC
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.20.27508\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.20.27508\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++latest
    IntelliSense Mode: msvc-x64
[C:\Users\garre\Work\nng\src\protocol\pubsub0\pub.c]:
    Process ID: 5672
    Memory Usage: 65 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
    Includes:
        C:\USERS\GARRE\WORK\NNG\INCLUDE
        C:\USERS\GARRE\WORK\NNG\SRC
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.20.27508\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.20.27508\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++latest
    IntelliSense Mode: msvc-x64
Total Memory Usage: 134 MB
```

**Comment by gdamore** [comment]
SO somehow "Stanard version" is ms_c++latest ?

Error messages are of the form (from red squiggles) like a value of "void *" cannot be used to initialize (some other pointer type) - which is true for C++ but not for C

**Comment by gdamore** [comment]
Note also that the language mode (on the bottom status bar) is C not C++.

**Comment by gdamore** [comment]
I also have the following user preferences:
```
        "editor.tabSize": 8,
        "editor.detectIndentation": false,
        "git.autofetch": true,
        "editor.rulers": [
                80
        ],
        "files.associations": {
                "*.c": "c",
                "*.h": "c",
        },
        "[c]": {
                "editor.defaultFormatter": "xaver.clang-format"
        },
        "editor.formatOnSave": true,
        "[cpp]": {
                "editor.defaultFormatter": "xaver.clang-format"
        },
        "C_Cpp.default.cStandard": "c99",
        "C_Cpp.default.intelliSenseMode": "clang-x64",
        "C_Cpp.default.cppStandard": "c++11",
}
```

**Comment by gdamore** [comment]
I'm also not using any GNU extensions in my code -- I generally prefer to avoid non-standard constructs.  (There are some non-standard *symbols* -- I'm not restricting myself to "strict ANSI" conformance where non-ANSI symbols are not permitted in the namespace, but I'm not seeing errors resulting from that.)

**Comment by sean-mcmanus** [comment]
Yeah, something is causing your compilerPath to incorrectly be cl.exe instead of your gcc and your intelliSenseMode to be msvc-x64 instead of clang-x64, and the language to be C++ instead of C. Is your CMake Tools extension configured correctly? If you're using a custom config provider like CMake Tools, then we're probably getting the language standard incorrect from them. If you could provide a repro we could debug it, or you could try debugging our extension in https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/client.ts ... just set the C_Cpp.loggingLevel to Debug and check the "Custom configurations received: " output ...or we could investigate more.

**Comment by septag** [comment]
check everywhere in your settings for "C_Cpp.configurationProvider" assigned to cmake-tools and remove them.
Then clear the cache and restart the vscode. I also switched to compile_commands.json for resolving compile flags for each file.
Thats how it solved for me

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
