### ISSUE TITLE
"#ifndef" code snippet is wrong

### ISSUE THREAD

**Issue by hangxingliu** [microsoft/vscode-cpptools#352]
I used code snippet `#ifndef` but I got a snippet like down:

``` cpp
#ifdef 1

#endif //!1
``` 
It look like a wrong snippet mixed ifdef preprocess and ifndef preprocess.

- VSCode version: `1.7.1`
- System: `Windows10 10.0.14393` and `Windows7 6.1.7601`
- Extension version: `0.9.2`

**Comment by bobbrow** [comment]
Our extension doesn't provide snippet support right now.  We have auto-complete suggestions for #ifndef and #ifdef in the latest versions of our extension, so if you are still seeing this problem, this sounds like it is a bug in another extension that you have installed.
