### ISSUE TITLE
Discussion: New UI Editor for Configuring IntelliSense

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#3522]
We’ve received a lot of feedback on the configuration experience of the C/C++ extension for Visual Studio Code. Users have consistently pointed out the difficulty of configuring IntelliSense, especially setting things up in the `c_cpp_properties.json` file. To address this pain point, we created a UI editor (screenshots below) to configure basic IntelliSense settings that are defined in the underlying `c_cpp_properties.json` file.

The UI editor is available in the [0.23.0-insiders]( https://github.com/Microsoft/vscode-cpptools/releases/tag/0.23.0-insiders) version.

### Purpose of the UI editor
- Make IntelliSense configuration easier to understand.
- Provide a simple and clear interface that displays basic settings to configure at minimum for IntelliSense to work for a workspace.
- Provide an alternative to editing JSON files to configure IntelliSense.

### Entry points to IntelliSense configurations
**Commands**
A new command `C/C++: Edit configurations (UI)` is available to open the UI Editor. The `c_cpp_proproerties.json` file can be opened with the command `C/C++: Edit configurations (JSON)` which replaced the old command `C/C++: Edit configurations…`.

**Default editor** 
Aside from the specific commands to either open the UI editor or JSON file, there are other entry points (such as links to quick fix IntelliSense errors) to configure IntelliSense. The default whether to open the IntelliSense UI editor or JSON file is based on the VS Code `workbench.settings.editor` setting. If `workbench.settings.editor` is set to “ui”, then the UI editor will open by default, and if it is set to "json", then JSON file will open by default.

### Future features for the UI editor

- Input validation. The `c_cpp_properties.json` shows error squiggles for invalid paths.
- Edit multiple configurations. Currently, modifications done on the UI editor will only apply to the active configuration. To edit other configurations on the UI editor, change the active configuration.

### Let us know what you think
We would love to hear your feedback on the new UI editor. Please let us know what you think! Give your feedback directly on this thread.

### Screenshots 

Light theme
![light](https://user-images.githubusercontent.com/38734287/56633065-7ed6e300-6611-11e9-9ab8-479ab6ff17fc.png)

Dark theme
![dark](https://user-images.githubusercontent.com/38734287/56633070-87c7b480-6611-11e9-97c5-0c1dceb6040d.png)

High contrast theme
![high-contrast](https://user-images.githubusercontent.com/38734287/56633071-8a2a0e80-6611-11e9-985c-a20ea78ced0b.png)

**Comment by Lennon925** [comment]
![捕获](https://user-images.githubusercontent.com/39362073/56638677-61515a00-66a1-11e9-96b1-e241b881aefa.PNG)
It seems that there is a bug about compiler path. Every time I change IntelliSense mode, the path will add some "\\" to it.

**Comment by michelleangela** [comment]
@Lennon925 Thanks for reporting the issue. There is a bug in the code that handles escape characters `\` in paths, where it replaces `\ `with `\\`. It looks like the code is unintentionally adding more `\\` when it re-reads the c_cpp_properties.json file to update the UI editor. As a note, this issue does not repro if a path uses `/` forward slashes.

Update: created separate issue to track this [#3526](https://github.com/Microsoft/vscode-cpptools/issues/3526)
