### ISSUE TITLE
Autocompletion does not work for defined local variables

### ISSUE THREAD

**Issue by shelper** [microsoft/vscode-cpptools#3525]
Issue Type: <b>Bug</b>

The auto completion works fine for lots of things but not a newly defined local variable.

Just like the image shows below, i defined a local variable and it does not get autocompletion but saying not suggestion. 
![image](https://user-images.githubusercontent.com/546163/56672762-fbef7000-6684-11e9-82cc-2efbaa6fafbd.png)

Extension version: 0.22.1
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (24 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|124.58GB (11.46GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

**Comment by sean-mcmanus** [comment]
This will occur when include files can't be found and your intelliSenseEngineFallback setting is "Enabled" or your intelliSenseEngine is "Tag Parser" instead of "Default". Are you able to change your settings to fix this?

**Comment by shelper** [comment]
I tried all combinations of intellisenseEngine and intellisenseEngineFallback, none if them sovles the problem...

my original setting is intellisenseEngine: Default, intellisenseEngineFallback:enabled

**Comment by shelper** [comment]
I tested again, and i think for the same settings, same extensions, version 1.25 works fine with auto-completion in c++ mode but 1.33 just is not working....

**Comment by shelper** [comment]
i believe this is an issue of the c++ extension. i downgraded to 0.20.1 and everything works.
version >0.20.1 all fails on ubuntu 

on mac all versions are fine

**Comment by sean-mcmanus** [comment]
It sounds like the IntelliSense process might be crashing. Can you try [enabling debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and look for any failure messages and/or installing 0.23.0-insiders (via C_Cpp.updateChannel "Insiders") and run the "C/C++: Log Diagnostics command?

**Comment by shelper** [comment]
well, with 0.23.0-insider2, it seems to be working fine....

**Comment by sean-mcmanus** [comment]
Let us know if you have any issues with 0.23.0.
