### ISSUE TITLE
Extra escape characters are added to paths with back slash when UI editor is updated.

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#3526]
**Type: LanguageService**

![image](https://user-images.githubusercontent.com/38734287/56675071-1d922c80-6670-11e9-8fa9-62b9fe40cded.png)

Whenever the configuration UI editor gets updated, it re-reads the c_cpp_properties.json file, which replaces back slashes in paths, but ends up adding more black slashes as the UI editor gets updated again.

**Comment by sean-mcmanus** [comment]
@Lennon925 The backlash issue should be fixed with 0.23.0-insiders2: https://github.com/Microsoft/vscode-cpptools/releases/tag/0.23.0-insiders2
