### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by marcoamolinaro** [microsoft/vscode-cpptools#3528]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.23.0-insiders`
- OS Version: `Linux x64 4.15.0-32-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/mmolinaro/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by WardenGnaw** [comment]
Missing attachment, merging with https://github.com/Microsoft/vscode-cpptools/issues/3213
