### ISSUE TITLE
Using vscode debugging c + +

### ISSUE THREAD

**Issue by Kractal** [microsoft/vscode-cpptools#353]
I want to use vscode and cpptools to debug C++, I have already installed MinGW in my C disk, I write a helloworld program and when i want to start debug, an error occurred, it is:
    Unable to start debugging. Program path 'd:\1\test.cpp' is missing or invalid.
Anyone know how to solve this problem? Please tell me,thanks a lot.

**Comment by delmyers** [comment]
Hi @NightWitchLilith 

C++ is not an interpreted language. You need to compile your code before you can execute it. After it is compiled, you have to tell the debugger to launch the compiled output.

Please see these blogs, and docs for more info:

[Building Your C++ Applications With Visual Studio Code](https://blogs.msdn.microsoft.com/vcblog/2016/10/24/building-your-c-application-with-visual-studio-code/)
[Configuring Your launch.json for C/C++ Debugging](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md)

**Comment by Kractal** [comment]
Thank you very much for your help!
