### ISSUE TITLE
Include errors are not reflected in status bar. 

### ISSUE THREAD

**Issue by prideout** [microsoft/vscode-cpptools#3531]
The status bar icon does not indicate if intellisense is in its "dumb" fallback mode. I often see a green squiggly in the copyright comment in a header file with a highly generic error tooltip like:

```
#include errors detected. Please update your includePath. IntelliSense features for this translation unit (/path/to/main.cpp) will be provided by the Tag Parser.
```

When intellisense is in this bad state, the status bar icon still indicates that everything is fine, which seems strange.

As an aside, it is not obvious that users should open the Problems view and/or `c_cpp_properties.json` to diagnose these kinds of issues -- perhaps the status bar icon should make it easy to jump to those two places.

**Comment by sean-mcmanus** [comment]
0.23.0-insiders changes the default to intelliSenseEngineFallback to "Disabled" so we expect less users to be hitting this error state, but it would still be useful to show some status indicator.

**Comment by bobbrow** [comment]
We don't revert to Tag Parser for IntelliSense anymore when `#include` doesn't resolve.  The default mode just hides red squiggles for errors.  This behavior can be changed with the `C_Cpp.errorSquiggles` setting.  VS Code will show if there are problems in the file in the Explorer panel.  I think we can close this issue.
