### ISSUE TITLE
Don't show release notes if the extension has never been installed before

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-cpptools#3533]
In order to prevent a bunch of extensions from spamming users about their updates when first installed I suggest the C++ extension doesn't show release notes on first launch, instead show [something like this](https://github.com/Dart-Code/Dart-Code/issues/1633#issuecomment-484952365)

**Comment by sean-mcmanus** [comment]
Fixed with 0.23.0 -- we didn't change it to show a "Do you want to see the Release Notes" prompt...we could open a new issue for that if any users complain.
