### ISSUE TITLE
Bring Template IntelliSense to Visual Studio Code

### ISSUE THREAD

**Issue by chibidev** [microsoft/vscode-cpptools#3535]
As a library author who writes heavily templated code I'd want to use Template IntelliSense (introduced in Visual Studio) to avoid dumb mistakes and provide better context during implementation. Even small typos or calling the wrong function can take up your time in templated functions (errors messages not always help in this case).

Especially since Concepts are coming up in C++20, having additional toolset around it could make C++ developers life much easier.

**Comment by sean-mcmanus** [comment]
Thanks for the feedback. We're currently tracking this with https://github.com/Microsoft/vscode-cpptools/issues/1946 (so you could upvote that), but we don't have it on our near term schedule yet. It doesn't look like VS Code has a sufficient UI interface to allow us to place a code action that is equivalent to what VS shows, but maybe we could do some creative hack that just runs a command to set one template parameter at a time or something.
