### ISSUE TITLE
Add ReadMe to ipch folder to try to prevent git checkins

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3537]
VSCode's default for the cache path works fine for me.  The only issue was not knowing what stuff was in there, and whether to commit it to source control.  (I have since added ".vscode/ipch" to my .gitignore file, and deleted files that were committed before I knew what they were.  That works for me.)

How about creating a ReadMe file inside .vscode/ipch to explain what's being stored there, that it's OK not to commit it to source control, and what settings you can change to modify the location and size of the cache?

_Originally posted by @mday64 in https://github.com/Microsoft/vscode-cpptools/issues/3347#issuecomment-486876234_

We've gotten multiple reports of users checking in the large binary files into git by mistake.

**Comment by Lennon925** [comment]
I think you can set ipch default storage path to where cpptools database is storaged.  .vscode folder isn't a good location to storage by fault.

**Comment by sean-mcmanus** [comment]
The workspaceStorage location is problematic because it's forced on the C/OS drive (and hard for users to locate) and there isn't a way to change the workspaceStorage location yet -- I think VS Code is tracking this with https://github.com/microsoft/vscode/issues/3884 .

**Comment by bobbrow** [comment]
The default ipch location has changed, so we don't think this is necessary anymore (i.e. users won't be able to commit the files to git because they are outside the repository).
