### ISSUE TITLE
Go to definition

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3539]
**Type: LanguageService**

**Describe the bug**
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.21

Sometimes I opened a file and use "go to definition" on variables and it showed 'no definition' or there are many results. But when I changed this file and saved it, "go to definition" found the correct result(only one)

This scenario just occurs occasionally and I can't repro it all the time.

**Comment by sean-mcmanus** [comment]
Yes, this sounds like a known issue in that when a file is first opened and IntelliSense is not ready (red flame appears) then it will fall back to the non-IntelliSense-based Go to Def, which will fail for local variables (no definition) or give many results (same name, but wrong type) -- https://github.com/Microsoft/vscode-cpptools/issues/2735 . It's possible https://github.com/Microsoft/vscode-cpptools/issues/2977 might also be occurring.
