### ISSUE TITLE
error squiggle at the end of file:  nclude is not a template expected an expression

### ISSUE THREAD

**Issue by tkj666** [microsoft/vscode-cpptools#3540]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1809
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

error squiggle at the end of file:

nclude is not a template
expected an expression

**To Reproduce**

type any code started with #include like
```cpp
#include <bits/stdc++.h>
using namespace std;

int main()
{
    cout << "hello world" << endl;
}
```
and **sometimes** the error comes up and it will disappear after reopen the file

**Expected behavior**

no error should occur
**Screenshots**

![image](https://user-images.githubusercontent.com/28040169/56796880-11f85e80-6846-11e9-9c44-ce6e7d9cda98.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
We're not able to repro this. Do you have any more repro info? Is this with WSL?

It looks like our internal document somehow has bad data and is trying to process
```
nclude <
```
instead of
```
#include <bits/stdc++.h>
````

We located and fixed one off-by-one error in our document/intelliSense interface that could theoretically lead to something like this, but we can't tell if that fixed your issue.

**Comment by tkj666** [comment]
not with WSL.
It just happens with no certain conditions.
It seems to be more likely to happen on low performance computers(pentium G3220 4G) than on higher performance computers(i5-4590 12G).
thank you for your quick fix and hope it works.

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
