### ISSUE TITLE
c++ How to run unchanged files without building them again

### ISSUE THREAD

**Issue by Jihad92** [microsoft/vscode-cpptools#3542]
Type: Debugger

Hello, I've managed to configure vs code to build and run c++ files and it worked fine, but it builds the files every time I hit F5 even if the files were unchanged.
What I want is to run the unchanged files without rebuild them.
I know it builds every time because the "preLaunchTask" is set "build" in "launch.json",  but I want something like:

if _**cpp_file is unchanged**_ then
      **_omit_** the "preLaunchTask" ( don't rebuild the project - just run the previous .exe )
else
      _**rebuild and run**_

**launch.json:**
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(gdb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/a.exe",
      "cwd": "${workspaceRoot}",
      "externalConsole": true,
      "MIMode": "gdb",
      "miDebuggerPath": "C:/mingw64/bin/gdb.exe",
      "preLaunchTask": "build",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}
```

**tasks.json:**
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "build",
      "type": "shell",
      "command": "g++",
      "args": ["-std=c++11", "starter.cpp"],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

**Comment by znakeeye** [comment]
Um... This was closed? So what is the solution then?!
