### ISSUE TITLE
[Feature Request] Ability to disable statusbar items

### ISSUE THREAD

**Issue by diabolicle** [microsoft/vscode-cpptools#3546]
I find the statusbar items distressing and would like a way to disable them. Whenever I start typing the database/flame icon repeatedly flashes and having to deal with the redundant C/C++ navigation item when there is now breadcrumbs, an outline view, and a symbol picker is not optimal.

**Comment by sean-mcmanus** [comment]
The code for showing the status bar icons is at https://github.com/Microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/ui.ts if anyone wants to make a pull request for a disable setting. I don't know when we'll have time to add that.

We plan to eventually get rid of the navigation bar, but the bread cumbs/outline view doesn't fully work with out our tool yet, so we need to fix https://github.com/Microsoft/vscode-cpptools/issues/2230 first.

**Comment by diabolicle** [comment]
VSCode recently added the ability to hide statusbar items so I'm going to close this issue.
