### ISSUE TITLE
#include errors detected on Win 10 1809 with wsl

### ISSUE THREAD

**Issue by FantasqueX** [microsoft/vscode-cpptools#3550]
Issue Type: <b>Bug</b>

**To Reproduce**
#include errors detected. Please update your includePath. IntelliSense features for this translation unit (D:\rlt\Documents\develop\new\hhh.cpp) will be provided by the Tag Parser.
cannot open source file "iostream"

**Screen shot**
![捕获](https://user-images.githubusercontent.com/46747123/56861497-e4412000-69d3-11e9-99d8-0f1f948df4ab.JPG)

**Here is my c_cpp_properties.json**
```
{
    "configurations": [
        {
            "name": "WSL",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "/usr/bin/g++",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}

```
I'm sure gcc is intalled on Ubuntu.
![捕获1](https://user-images.githubusercontent.com/46747123/56861539-53b70f80-69d4-11e9-9c87-fb3992611079.JPG)

Extension version: 0.22.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (2.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>

**Comment by bobbrow** [comment]
Your screenshot shows you invoking `gcc`, but your configuration is pointing at `g++`.  Can you double check that `g++` is also installed?

**Comment by FantasqueX** [comment]
![捕获3](https://user-images.githubusercontent.com/46747123/57116733-ae13ef80-6d89-11e9-8891-df81eb9de1de.JPG)
g++ is also installed.

**Comment by bobbrow** [comment]
We recommend using the Remote - WSL extension in the VS Code Marketplace for doing WSL work.  Please let us know if you continue to have problems with your WSL folders when you use that extension.
