### ISSUE TITLE
includePath is not working correctly (picking up stdint.h from MinGW path)

### ISSUE THREAD

**Issue by taitcw** [microsoft/vscode-cpptools#3551]
"${workspaceFolder}/**" is working well, picking up all the necessary source and header files.
I include standard library headers in my project:
#include <stdbool.h>
#include <stdint.h>
#include <stddeh.h>
etc

intellisense complains about not being able to find these files (compiled fine because I used -I to include "C:/Program Files (x86)/IAR Systems/Embedded Workbench 6.0/arm/inc/c". So I added this path to includePath, thinking it will solve the referencing issue.

I have added all the necessary defines under "defines" so that all data types are correctly sized.

But intellisense still have problem finding the std**.h.  It complains about not being able to find Crc16_t, which I define typedef uint16_t Crc16_t; in one header file.  So if I manually open the file one by one, the red squiggle will disappear because everything is there.  But then the error squiggle will come back once those files are closed.

So at the end, I found a temporary solution, I copied the entire folder (C:/Program Files (x86)/IAR Systems/Embedded Workbench 6.0/arm/inc/c) into my workspace so that "${workspaceFolder}/**" will contain all those std**.h.  That works!

Why is intellisense picking up stdint.h fro MinGW or other Visual Studio path?  What is the proper way to exclude those from intellisense i.e. I want to setup my workspace to pick up those standard library headers from my compiler only.

Many thanks.

**Comment by bobbrow** [comment]
I forget, is the IAR compiler derived from GCC?  If it is, you can set "compilerPath" in your `c_cpp_properties.json` to tell the extension where your compiler is, and it will attempt to query the system include path from it.

**Comment by bobbrow** [comment]
And to answer your other question, if you don't set "compilerPath" explicitly, the extension will try to find one so that the system headers are available for you.

If setting the path to your IAR compiler doesn't work for you, you should set it to an empty string `""` and the extension will not attempt to locate an alternate compiler on your computer.

**Comment by taitcw** [comment]
Hi bob, I don't think IAR is derived from GCC, but I could be wrong.

I added the location to IAR compiler inc to here:
            "includePath": [
                "C:/Program Files (x86)/IAR Systems/Embedded Workbench 6.0/arm/inc/c",
                "${workspaceFolder}/**"
            ],
            "compilerPath": ""

Then I get error from intellisense, for now knowing "volatile" keyword...

Any idea?

**Comment by sean-mcmanus** [comment]
What exactly is the error message involving the "volatile" keyword?

If you set the C_Cpp.updateChannel to "Insiders" and use the C/C++: Log Diagnostics command you can see what includePath/defines/etc. we use for IntelliSense.

**Comment by taitcw** [comment]
Hi Sean,
I have switched to Insiders channel. But I am not familiar with log diagnostics command. Can you tell me get diagnostics information out?

**Comment by sean-mcmanus** [comment]
You can get it in the View->Command Palette (you can type "log diagnostics" to search for the command):
![image](https://user-images.githubusercontent.com/19859882/57113727-c557cc00-6cfa-11e9-8f8d-aedfff8ad033.png)

The output should appear in the Output panel.

The insider update might not kick in immediately (or could fail) if you don't see that command available (restarting VS Code can sometimes trigger the update faster).

**Comment by taitcw** [comment]
I finally got some time to focus on figuring out the issues. I have learnt
a few things about Intellisense.

iccarm.exe is the compiler that we are using, and it is not derived from
GCC.  Adding that to compilerPath doesn't work as the same if I put a
gcc.exe there.  So I explicitly set it to "" as suggested.

I have to manually define all those required compiler provided defines such
as:

"__INT8_T_TYPE__=char",
"__UINT8_T_TYPE__=unsigned char",
"__INT16_T_TYPE__=short",
"__UINT16_T_TYPE__=unsigned short",
"__INT32_T_TYPE__=int",
"__UINT32_T_TYPE__=unsigned int",
"__INT_LEAST8_T_TYPE__=__INT8_T_TYPE__",
"__UINT_LEAST8_T_TYPE__=__UINT8_T_TYPE__",
"__INT_LEAST16_T_TYPE__=__INT16_T_TYPE__",
"__UINT_LEAST16_T_TYPE__=__UINT16_T_TYPE__",
"__INT_LEAST32_T_TYPE__=__INT32_T_TYPE__",
"__UINT_LEAST32_T_TYPE__=__UINT32_T_TYPE__",
"__INT_FAST8_T_TYPE__=__INT8_T_TYPE__",
"__UINT_FAST8_T_TYPE__=__UINT8_T_TYPE__",
"__INT_FAST16_T_TYPE__=__INT16_T_TYPE__",
"__UINT_FAST16_T_TYPE__=__UINT16_T_TYPE__",
"__INT_FAST32_T_TYPE__=__INT32_T_TYPE__",
"__UINT_FAST32_T_TYPE__=__UINT32_T_TYPE__",
"__INTMAX_T_TYPE__=long long",
"__UINTMAX_T_TYPE__=unsigned long long",
"__INTPTR_T_TYPE__=long",
"__UINTPTR_T_TYPE__=unsigned long",
"__INT8_T_MAX__=127",
"__INT8_T_MIN__=-128",
"__UINT8_T_MAX__=0xFF",
"__INT16_T_MAX__=32767",
"__INT16_T_MIN__=-32768",
"__UINT16_T_MAX__=0xFFFF",
"__INT32_T_MAX__=2147483647",
"__INT32_T_MIN__=-2147483648",
"__UINT32_T_MAX__=0xFFFFFFFFu",
"__INT_LEAST8_T_MAX__=__INT8_T_MAX__",
"__INT_LEAST8_T_MIN__=__INT8_T_MIN__",
"__UINT_LEAST8_T_MAX__=__UINT8_T_MAX__",
"__INT_LEAST16_T_MAX__=__INT16_T_MAX__",
"__INT_LEAST16_T_MIN__=__INT16_T_MIN__",
"__UINT_LEAST16_T_MAX__=__UINT16_T_MAX__",
"__INT_LEAST32_T_MAX__=__INT32_T_MAX__",
"__INT_LEAST32_T_MIN__=__INT32_T_MIN__",
"__UINT_LEAST32_T_MAX__=__UINT32_T_MAX__",
"__INT_FAST8_T_MAX__=__INT8_T_MAX__",
"__INT_FAST8_T_MIN__=__INT8_T_MIN__",
"__UINT_FAST8_T_MAX__=__UINT8_T_MAX__",
"__INT_FAST16_T_MAX__=__INT16_T_MAX__",
"__INT_FAST16_T_MIN__=__INT16_T_MIN__",
"__UINT_FAST16_T_MAX__=__UINT16_T_MAX__",
"__INT_FAST32_T_MAX__=__INT32_T_MAX__",
"__INT_FAST32_T_MIN__=__INT32_T_MIN__",
"__UINT_FAST32_T_MAX__=__UINT32_T_MAX__",
"__INTMAX_T_MAX__=9223372036854775807LL",
"__INTMAX_T_MIN__=-9223372036854775808LL",
"__UINTMAX_T_MAX__=0xFFFFFFFFFFFFFFFFuLL",
"__SIZE_T_MAX__=__UINT32_T_MAX__",
"__PTRDIFF_T_MAX__=__INT32_T_MAX__",
"__PTRDIFF_T_MIN__=__INT32_T_MIN__",
"__INTPTR_T_MAX__=__INT32_T_MAX__",
"__INTPTR_T_MIN__=__INT32_T_MIN__",
"__UINTPTR_T_MAX__=__UINT32_T_MAX__",
"__SIGNED_CHAR_MIN__=127",
"__SIGNED_CHAR_MAX__=-128",
"__INT8_C_SUFFIX__=",
"__UINT8_C_SUFFIX__=",
"__INT16_C_SUFFIX__=",
"__UINT16_C_SUFFIX__=",
"__INT32_C_SUFFIX__=",
"__UINT32_C_SUFFIX__=",
"__INTMAX_C_SUFFIX__=",
"__UINTMAX_C_SUFFIX__=",
"__ICCARM__=1",
"__IAR_SYSTEMS_ICC__=8",
"__TID__=0xCF60",
"__FLOAT_SIZE__=4",
"__DOUBLE_SIZE__=8",
"__LONG_DOUBLE_SIZE__=8",
"__INT_SIZE__=4",
"__LITTLE_ENDIAN__",
"__C99_BOOL__",
"__ARM_PROFILE_M__",
"__VER__=6020003",
"__STDC_VERSION__=199901L",
"__WCHAR_T_TYPE__=__UINT16_T_TYPE__",
"__PTRDIFF_T_TYPE__=__INT32_T_TYPE__",
"__SIZE_T_TYPE__=__UINT32_T_TYPE__",
"__SIGNED_LONG_MAX__=__INT32_T_MAX__",
"__UNSIGNED_LONG_MAX__=__UINT32_T_MAX__",
"__WCHAR_T_MAX__=0xFFFF",
"__intrinsic=",
"__nounwind=",
"__noreturn=",
"__ramfunc=",

But intellisense still failed to generated PCH for modules.  I narrowed
down to this header file <intrinsics.h>.

It has some compiler specific calls that I found them very hard to define
in c_cpp_properties.json

#define __cpid unsigned __constrange(0,15)
#define __cpreg unsigned __constrange(0,15)
#define __cpopc unsigned __constrange(0,8)

/* Co-processor access */
__intrinsic void __MCR( __cpid coproc, __cpopc opcode_1, __ul src,
__cpreg CRn, __cpreg CRm, __cpopc opcode_2 );


Any idea how I can define __constrange so that I can keep intellisense
happy?


Many thanks.

**Comment by sean-mcmanus** [comment]
Can you try "__constrange(x, y)="?

**Comment by taitcw** [comment]
Hi Sean,

Sorry for the late reply.  I have added what you suggested and there are no
more error squiggles in <intrinsics.h> for now.  But PCH still unable to be
generated, I will investigate further (got a feeling is another <libxxx.h>
that got some error squiggles?).

One thing very important to me is that, is there a way to exclude
directories from intellisense?  My source code folder structure contains a
folder that is basically another repo (Bootloader), which I want to
exclude.  I can add the folder to this list:

[image: image.png]

But that does not stop intellisense going through that folder.

Is there a way to exclude a folder for intellisense?


Thanks,
David

**Comment by sean-mcmanus** [comment]
You can use the files.exclude setting, but that will also hide the files from VS Code itself (to only hide it from our extension we would need a new setting).

**Comment by taitcw** [comment]
I have spent more time trying to figure out which defines are still
missing.  I got a feeling I am very close now.

I created a new little module for debugging this:

![image](https://user-images.githubusercontent.com/8909482/61913239-961ac900-af90-11e9-9f27-2152638df8a7.png)

The error message does not tell me much.  From my experience, it is
probably caused by a broken definition in one of the headers.

Is there a way to track down which header is causing the problem?

**Comment by sean-mcmanus** [comment]
I don't see any screenshot or other details. We don't yet provide a good way to track down missing defines, other than manually opening the included files to find the 1st file that gives squiggles due to incorrect defines (be aware that Go to Def on `#include` is buggy and may return the wrong result because it doesn't use the IntelliSense include path to locate the file).

**Comment by taitcw** [comment]
The error squiggle shown in that screenshot is misleading.  I know it is from <stdint.h> and I have been trying to narrow down to which exact line, but when I open the corresponding stdint.h, there is no squiggles (because I have added all the necessary defines already).

**Comment by sean-mcmanus** [comment]
Okay, I see your screenshot now with the error. Another user reported the error at https://github.com/microsoft/vscode-cpptools/issues/3910 . Maybe adding a #pragma once at the start of the header file might fix it? I think you can just ignore the error message.

**Comment by taitcw** [comment]
I have read #3910, the problem sounds very similar to what I am encountering.  Unfortunately, I can't just ignore this error because in my actual module, when it complains about PCH, there are 50 errors to follow i.e. my custom datatype is not defined etc (which they are all properly defined in my header file).

P.S. How can I get the debug output like what #3910 reporter did?

**Comment by taitcw** [comment]
YAHOO~ I was about to give up but I have found the problem!

It is this line in my compiler's <stdint.h>
__DATA_PTR_MEMORY_LIST1__()

I need to add:
"__DATA_PTR_MEMORY_LIST1__()=",

I felt I have learnt quite a bit from this exercise, as I never really looked into what my compiler provides (those __DATATYPE__ etc).

Thank you Sean!  This issue can be closed.

I am using IAR for ARM (Cortex-M3) if anyone is interested.
