### ISSUE TITLE
Request for Information regarding pre-compiled binary dependencies

### ISSUE THREAD

**Issue by WallyZambotti** [microsoft/vscode-cpptools#3553]
vscode/cpptools contains two pre-compile binaries depending on machine architecture.

These binaries are:

Microsoft.VSCode.CPP.Extension.{architecture}
Microsoft.VSCode.CPP.Intellisense.Msvc.{architecture}

Is there any intention to release these binaries for the Aarch64 (Arm64) architecture?

**Comment by sean-mcmanus** [comment]
We're tracking that with https://github.com/Microsoft/vscode-cpptools/issues/429 (you could upvote that). It's not on our near-term plans.

**Comment by WallyZambotti** [comment]
Sean McManus

 

Thank you for taking the time to respond.

 

I understand.

 

Much appreciated.

 

Walter Zambotti
