### ISSUE TITLE
Typedef inside #ifdef potentially breaking Outline

### ISSUE THREAD

**Issue by sdebnath** [microsoft/vscode-cpptools#3554]
**Type: LanguageService**
 

**Describe the bug**
- OS and Version: MacOS X 10.14.4
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.1
- Other extensions you installed (and if the issue persists after disabling them): Go, GitLens, Vim, Python
- A clear and concise description of what the bug is.

When browsing postgresql code, the outline for heapam.c seems to be broken. It skips about ~2400 lines of functions and definitions and the entry it does show for that span is a typedef struct XidHorizonPrefetchState.

I am guessing the typedef is the source of the issue, but not at all confident in that assumption.

**To Reproduce**

1. Clone https://github.com/postgres/postgres/ repository
2. Open that directory in Visual Studio Code.
3. Wait for indexing to complete (I typically open up a few .c files and browse around
4. After indexing is complete, open (Cmd+P) heapam.c
5. In Explorer, ensure outline pane is open
6. The first entry in the outline is XidHorizonPrefetchState (line 177), followed by compute_infobits (line ~2401)

**Expected behavior**

I expect to see all the functions and macros from line 0 to line 2401.

**Screenshots**

<img width="1920" alt="Screen Shot 2019-04-28 at 11 05 47 PM" src="https://user-images.githubusercontent.com/59411/56878723-57658900-6a0a-11e9-8b3e-e83cb3eb6407.png">

**Additional context**

**Comment by sean-mcmanus** [comment]
Thanks for reporting this.

A macro that requires evaluation in order to parse the code correctly may need to be added to a cpp.hint file in your workspace. See https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2019 .

We can double-check ourselves later.

**Comment by sdebnath** [comment]
Hi Sean - thank you for the information on the cpp hints. I am going to close this issue as it turns out my sort order was set to type and not by position!
