### ISSUE TITLE
Microsoft.VSCode.CPP.Extension.exe CPU usage 12%

### ISSUE THREAD

**Issue by shangsh** [microsoft/vscode-cpptools#3555]
my os is Windows 10
ms-vscode.cpptools Version: 0.23.0-insiders

Why is the cpu usage so high????
![image](https://user-images.githubusercontent.com/13687222/56885227-8299b800-6a9e-11e9-94f0-160fb1c46e2e.png)

**Comment by sean-mcmanus** [comment]
It depends on what it is doing. Do you have a database icon or red flame in the bottom right? You could try [enable Debug logging](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) to see if it shows more info.

**Comment by bobbrow** [comment]
We need more information to fully investigate this issue. If you update to the latest version of the extension and your issue persists, please reply with additional information that can help us investigate your issue.
