### ISSUE TITLE
Excluded folders are scanned

### ISSUE THREAD

**Issue by xchrdw** [microsoft/vscode-cpptools#356]
I have a huge project where I usually only need a few folders. I have configured "files.exclude" to hide all irrelevant folders. Sadly the cpptools still try to analyse the code from hidden folders for hours and code navigation (goto to symbols, include files, ...) doesn't work at all. Would it be possible to have cpptools use "files.exclude" or a custom setting for this purpose? 

If I only open a subfolder everything works fine. Even a "files.exclude": { "*/": true } doesn't prevent cpptools from analysing everything.

I'm using vscode 1.7.1 with cpptools 0.9.2 as the only extension.

**Comment by sean-mcmanus** [comment]
files.exclude should work now. If there are additional buggy scenarios let us know.
