### ISSUE TITLE
Debian 9 Arm64 C++ Configure Task error

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3560]
**Type: LanguageService**
Terminal - Configure Task

**Describe the bug**
- OS and Version: Debian 9 Stretch Arm64
- VS Code Version:
Version: 1.32.0 (user setup)
Commit: aeaef41d51201e555735f5e8d2f38a9d0ddb9026
Date: 2019-02-20T06:32:49.577Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux arm64 4.4.154.c83-00028-gaeed0d91c4a7

- C/C++ Extension Version: ??  current
- Other extensions you installed (and if the issue persists after disabling them): only c# and C++ language related
- A clear and concise description of what the bug is.

**To Reproduce**

This is an attempt to set up a build task for phantomjs on ARM64
Create a task from template (e.g. echo)
From the "Terminal" menu select "Configure Task" and select Echo

when attempting to modify the task echo, the following message is displayed

Unable to open '.vscode\tasks.json': File not found 
 file:///media/nvme/phantomjs/.vscode\tasks.json)

NOTICE!  The backslash in the path is OS dependent ... should be a forward slash for Unix
.vscode **\\** tasks.json  should be .vscode **/** tasks.json

**Expected behavior**
The tasks.json file should be opened

**Screenshots**

**Additional context**

**Comment by WardenGnaw** [comment]
The `Configure Task` selection is part of VS Code. Please submit this issue to https://github.com/Microsoft/vscode/issues
