### ISSUE TITLE
C++ Autocompletion memory leak

### ISSUE THREAD

**Issue by 6502** [microsoft/vscode-cpptools#3565]
**Type: LanguageService**

Big memory leak on autocomplete

- OS and Version: Arch Linux (updated on 30/4/2019)

- VS Code Version: 1.33.1 (Arch package)

- C/C++ Extension Version: 0.22.1

- Other extensions you installed (and if the issue persists after disabling them):
MS C/C++ extension was the only one installed when I bumped into the problem. After that I installed C/C++ Clang Command Adapter to keep having auto completion.

- A clear and concise description of what the bug is:
VS code just leaks memory in big quantities. I found the problem after the computer freezed  because of RAM exhaustion. Killing VS code freed more than 9Gb.

**To Reproduce**
I found the problem is present even with a simple helloword program when autocompleting an `std::vector` instance:

```
#include <vector>
#include <stdio.h>

int main(int argc, const char *argv[]) {
    std::vector<int> v;
    v.    // <- Typing and backspacing the dot here keeps leaking big amounts of memory
    return 0;
}
```

**Screenshots**

Here you can see a screen capture of me reproducing the problem.

https://youtu.be/v8dzIyABI6U

**Comment by sean-mcmanus** [comment]
I repro the problem with the Microsoft.VSCode.CPP.IntelliSense.Msvc.linux process. I got it to repro on Windows too using gcc-8 with WSL.

It started regressing with 0.21.0-insiders2 -- due to code that queries for doc comments; however the root cause is from IntelliSense-based Go to Def code, i.e. memory leaks on Go to Def and Hover as well. The memory leak when switching docs might also share the root cause...

**Comment by sean-mcmanus** [comment]
This appears to be "by design" and the memory is freed as soon as an edit is made outside of a fuction and the cursor moves to a new line (i.e. VS has the same behavior). Can you verify that the memory usage goes back to normal after doing that?

Did you hit the 9 GB of memory usage while doing lots of edits exclusively to a single method?

Umm...but we could still add code to free up the memory after "too much is used".

**Comment by 6502** [comment]
Sorry for the late reply.

Yes, moving in the global scope and typing in a new `int` variable declaration frees the memory; it's also very possible that when I stumbled in the problem I've had been coding for the whole morning in a method (i was tweaking the code, switching to the terminal to compile and run, then switching back to code for some more tweak and so on).

I must say that I fail to see why it's considered ok to temporary leak huge amounts of memory until you move to another method.

Incidentally I also noticed that in an older version this "bug" was not present (sorry I cannot remember the version I had on the laptop I took to the conference but seeing the problem wasn't present I updated before thinking to taking note - stupid, i know - and after the update the bug was present and I saw the "move around and define a dummy new variable" solution was indeed working).

**Comment by LeonSpors** [comment]
> 
> 
> This appears to be "by design" and the memory is freed as soon as an edit is made outside of a fuction and the cursor moves to a new line (i.e. VS has the same behavior). Can you verify that the memory usage goes back to normal after doing that?
> 
> Did you hit the 9 GB of memory usage while doing lots of edits exclusively to a single method?
> 
> Umm...but we could still add code to free up the memory after "too much is used".

**OS and Version:** Ubuntu 19.04

**VS Code Version:** 1.33.1 

**C/C++ Extension Version:** 0.23.0-insiders2

I do hit the maximum usage I can get (7.7GB) . Just by the given function. A "too much is used"-function would be helpful.

**Comment by 6502** [comment]
Tried again MS intellisense for C++ recently but this "design" makes it unusable for me.

Probably is ok for people writing a plethora of tiny functions that do trivial things but dealing with my code now I get gigabytes of leaks per minute just moving around the cursor (I've a problem remembering names thus my code tend to be quite a bit more intricate and nested than what most feel comfortable with -- for example I use a lot of lambda as local functions with short context-dependent names).

Just out of curiosity... why is it considered useful to limitless accumulate gigabytes and gigabytes of data when moving a cursor inside a function without asking for completion? Where is this data being stored? In a map using random numbers as key?

**Comment by sean-mcmanus** [comment]
@6502 We're tracking a fix for this at https://github.com/microsoft/vscode-cpptools/issues/4119 . I may have mentioned this already, but our implementation is borrowed from VS (on Windows) which uses a 32-bit process, so it auto-cleans itself in your scenario via crashing from an out of memory and then just restarting so users don't notice any problem (unlike on Linux/Mac where memory just keeps increasing).

**Comment by 6502** [comment]
Ah ok, sorry for the sarcasm... I misunderstood the "by design" comment. I'ts not by design at all but it's a genuine bug. I can understand that it's not considered critical because probably 99% of the users are using the 32-bit crashing version and do not notice any problem (2 Gb of memory use is considered normal and perfectly acceptable today).

**Comment by sean-mcmanus** [comment]
@6502 It's important to our Linux users who have code bases that repro the issue. The 32-bit version only runs on Windows. I was trying to explain why the issue exists.
