### ISSUE TITLE
Cannot set breakpoints in C++ code and "step out" fails

### ISSUE THREAD

**Issue by a-shahba** [microsoft/vscode-cpptools#3566]
Type: Debugger

I have a simple C++ code that I am trying to run via the debugger. I know this code has a memory leak; but that is not the point here. I have problem with basic debugging operations.

- OS and Version: Windows 10, 64-bit
- VS Code Version: 1.33.1
- C/C++ Extension Version:  0.23.0-insiders
- Other extensions you installed (and if the issue persists after disabling them): I installed CMake Tools, CMake Tools Helper and CMake. The problem persists even after disabling these extensions. 
- A clear and concise description of what the bug is.
(a) I cannot set breakpoint on lines 16 and 17 of **cppPrimer5thEdition**
(b) From **cppPrimer5thEdition**, I cannot step into **exercise_13_4** function
(c) I can *step in* **sumTwoInts**. Once I am inside, the debugger exits when I hit *step out*

**To Reproduce**
I am attaching the full code with all the relevant json files.
1. Give the path to the C and C++ compiler on line 45 and 46 of the **build.sh** script. Provide the path to gdb in **launch.json** file.  I am using the gcc provided in MinGW
2. Run "d-build" task to compile the code in debug mode. The executable will be installed under **working_directory/executable/debug**
3. Start the code in debugger and you should be able to see the issues I described above

**Additional context**
Here is the log information in the Debug console

[debugConsole.txt](https://github.com/Microsoft/vscode-cpptools/files/3131603/debugConsole.txt)

**Comment by a-shahba** [comment]
Here is the code

[DebuggerFailing.zip](https://github.com/Microsoft/vscode-cpptools/files/3131617/DebuggerFailing.zip)

**Comment by pieandcakes** [comment]
@a-shahba I tried to follow your instructions but my version of MinGW64 does not contain `make` which your example needs. Can you tell me where you are getting your version of MinGW and also which version of CMake you are using.

**Comment by a-shahba** [comment]
I got MinGW (version MinGW-W64-builds-4.3.5) from SourceForge. This version does not have **make** in its bin directory so I followed the instructions at 

https://www.eclipse.org/4diac/documentation/html/installation/minGW.html

to add it. By the way, I am using CMake 3.12.3
