### ISSUE TITLE
C/C++ .i header files taken as plain text

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-cpptools#3567]
In C language, there's usually header files that end in `.h`, but these can be pre-processed by compilers such as `gcc` to produce a `.i` file which serves the same purpose, but has already underwent macro text substitutions, and can also be included with `#include "file.i"`.

These are currently not recognized as C header files in vscode with the C/C++ extension.

(moved from https://github.com/Microsoft/vscode/issues/73089)

**Comment by sean-mcmanus** [comment]
Is adding `"*.i": "c"` to your files.associations setting sufficient?

**Comment by david-cortes** [comment]
> Is adding `"*.i": "c"` to your files.associations setting sufficient?

That works, but I think it should be part of the default as `.i` (AFAIK) are not used in any other language, and are rather standard in C.

**Comment by sean-mcmanus** [comment]
@david-cortes VS Code itself controls the out-of-box files.associations (i.e. the text colorization to use), not our C/C++ extension. However, there are features in our extension that uses those specific files.associations, so we could use this issue to track those other changes.

Also, ".ii", ".cp", ".c++", ".hp", ".h++", ".tcc" should be added treated as "C++" files according to the gcc docs at https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/Overall-Options.html .

**Comment by sean-mcmanus** [comment]
We have a fix pending for our internal handling of various extensions, but VS Code itself is treating "*.i" as "cpp" instead of "c" now.
