### ISSUE TITLE
Downloading package 'Visual Studio Windows Debugger' Failed at stage: downloadPackages Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by garoyeri** [microsoft/vscode-cpptools#357]
When trying to run the plugin from behind a corporate SSL proxy, I get the following message:

```
Updating C/C++ dependencies...

Downloading package 'Visual Studio Windows Debugger' Failed at stage: downloadPackages
Error: self signed certificate in certificate chain

Finished
```

This issue was resolved for the C# plugin in this issue: https://github.com/OmniSharp/omnisharp-vscode/issues/957

**Comment by gregg-miskelly** [comment]
Here is the PR: https://github.com/OmniSharp/omnisharp-vscode/pull/958

**Comment by pieandcakes** [comment]
@garoyeri I don't have a corporate SSL proxy so I don't have a way to test this, but in our extension's package manager code, I see the following block, which should respect the http.proxyStrictSSL settings already. Does setting that value work for you?


```
        let strictProxy = vscode.workspace.getConfiguration().get("http.proxyStrictSSL", true);
        let proxyOptions = {
            host: proxyUrl.hostname,
            port: parseInt(proxyUrl.port, 10),
            auth: proxyUrl.auth,
            rejectUnauthorized: strictProxy
        };

        return new HttpsProxyAgent(proxyOptions);

```

**Comment by garoyeri** [comment]
I've set only the http.proxyStrictSSL flag, but not the proxy URL or the proxy Port.  It works for the Extension manager and they fixed it with the OmniSharp plugin as well.

**Comment by garoyeri** [comment]
Here's the related issue: https://github.com/OmniSharp/omnisharp-vscode/issues/579

**Comment by pieandcakes** [comment]
@garoyeri I made a change that will be available in the next release.

**Comment by garoyeri** [comment]
I tested with 0.9.3 and it works as expected.  The additional tools were automatically downloaded and installed.  My company proxy interrupted the 3rd download (Debugger), but restarting Visual Studio Code allowed it to redownload properly and install.

**Comment by pieandcakes** [comment]
Thanks. I'll consider this issue resolved.
