### ISSUE TITLE
VS ArduinoIDE 1.9 Compiler problem.

### ISSUE THREAD

**Issue by wogoos** [microsoft/vscode-cpptools#3575]
Dear reader I work with MS VS to program ATmega ESP and STM32103C micro controllers. I work with the Arduino IDE 1.9. extension and have installed the standard STM32F environment.

My problem relates to the STM32103C. Compiling and uploading works fine for software without Include files or the standard builtin libraries lib files.  I have seen however that as soon I use more complex libraries as the U8GLIB to control a HS1103 OLED the compiler/Linker generate a list of errors as indicated blow, the list is longer. VS complains that it can't open files like "inttypes.h" or stdlib.h ........ . I checked for the existence of these files and they do not exists in the STM32 environment some have similar but new names.  I have added a search path link for the builtin libraries to the "VC++ Directory" part of the project properties but without success.
Does any one recognize my problem and know what I can do about it.
Thanks  Oscar

![image](https://user-images.githubusercontent.com/11338044/57038374-66715480-6c1f-11e9-9295-f9cd96917ab1.png)

**Comment by sean-mcmanus** [comment]
That screenshot looks like Visual Studio. Can you try https://developercommunity.visualstudio.com/ or the Arduino IDE extension page?
