### ISSUE TITLE
support remote language server

### ISSUE THREAD

**Issue by msandy** [microsoft/vscode-cpptools#3577]
I have a project on my debian workstation that works fine with local language servers. When I am working remotely, I use sshfs to mount the workspace on my local machine so I can load it in vscode and do local editing, but I use ssh for everything else - git commands, builds, debugging, etc.  I can run the language server on my local vscode instance, however this triggers sshfs to on-demand download a significant portion of the workspace files locally.  Instead, it would be great if cpptools could be pointed at a remote server for its language service queries.

**Comment by bobbrow** [comment]
Thank you for the feature suggestion, but we're reviewing some of our older requests and do not have plans to implement this feature.
