### ISSUE TITLE
Need ability to move .browse.VC.db

### ISSUE THREAD

**Issue by zhackwyatt** [microsoft/vscode-cpptools#358]
- VSCode Version:1.7
- OS Version: Windows 7
- CPP Tools Version: 0.9.2

Our code is located in ClearCase.  ClearCase has never been known for speed.  The problem is the symbols database is stored in the top-level folder in ClearCase which is essentially a slow network drive.

I think this causes problems because sometimes IntelliSense works and sometimes it doesn't.

I'd like the ability to have the .vscode folder on my local drive, even though my code is in ClearCase.

Thanks

**Comment by bobbrow** [comment]
The database should be in your %appdata% folder by default now.  If not, you can set a specific path by editing the c_cpp_properties.json file (use the "C/Cpp: Edit Configurations" command if you don't have this file yet).

Please reopen if this doesn't work for you.
