### ISSUE TITLE
c++11 is not set in the build cmd even if I set cppstandard to c++11 in settings.json

### ISSUE THREAD

**Issue by code-crow** [microsoft/vscode-cpptools#3587]
Issue Type: <b>Bug</b>

Trying to run 
```
 #include <iostream>
 #include <vector>
 #include <string>

 using namespace std;

 int main()
 {

     vector<string> msg {"Hello", "C++", "World", "from", "VS Code!", "and the C++ extension!"};

     for (const string& word : msg)
     {
         cout << word << " ";
     }
     cout << endl;
 }
```
example code from https://code.visualstudio.com/docs/cpp/config-wsl

Uses C++98 std by default even if set the standard to c++11 inthe settings of the c/C++ extensions

Extension version: 0.22.1
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.23GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+default/home/amit/projects/vscodecpp --remote=wsl+default|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.88GB (10.23GB free)|
|VM|0%|
</details>

**Comment by bobbrow** [comment]
Hi @code-crow, the `cppStandard` set in the `settings.json` or `c_cpp_properties.json` are only consumed by IntelliSense and do not automatically get applied to your compiler command line.

You will need to update the `"args"` in `tasks.json` to include the C++ standard version you would like to compile against.  For example, add `"-std=c++11"` to the `"args"` list.

**Comment by code-crow** [comment]
Thanks @bobbrow I already did what you mentioned. I was wondering if there was a global setting to default the compiler to use c++11.

**Comment by bobbrow** [comment]
For building code, no there isn't a default.  For IntelliSense, there is a global setting `"C_Cpp.default.cppStandard"`
