### ISSUE TITLE
ignore warnning on some functions

### ISSUE THREAD

**Issue by david85fr** [microsoft/vscode-cpptools#3588]
**Type: LanguageService**

vscode show this function as
```
#define max(a,b) \
       ({ __typeof__ (a) _a = (a); \
          __typeof__ (b) _b = (b); \
          _a > _b ? _a : _b; })

resMax = max( a , b );
```
vscode show warning, as expected an expression.
Can i disable warning on some define() ?

- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.22.1

**Comment by bobbrow** [comment]
Thank you for your issue report.  Which compiler and flags are you using to compile this?  We may consider repurposing this issue to track support for the syntax that you have shared.

We have a feature request open to disable certain errors.  #2345

**Comment by HoriKyouko** [comment]
I'm getting a similar issue when creating my own max function the intellisense is saying there is an error with the declaration of my max function (seen below are the function and error):

int max(int num1, int num2){
    return (num1 > num2) ? num1 : num2;
}

should "expected an identifier" then says:
"#define max(a,b) (((a) > (b)) ? (a) : (b))
Expands to:
(((int num1) > (int num2)) ? (int num1) : (int num2))"

Screenshot of VSCode showing above error on function and the problems it's detecting:
![Screenshot (2)](https://user-images.githubusercontent.com/26206463/60837311-dc50e980-a195-11e9-8b8d-77f0c4ea12c7.png)
The semicolon error occurs right after the "int max(int num1, int num2)" saying that it should be right after the ')' 

When I compile with "gcc -Wall -Werror..." no warnings/errors pop up in the terminal and when I run my executable everything runs fine:
![Screenshot (3)](https://user-images.githubusercontent.com/26206463/60837553-6e58f200-a196-11e9-9f3f-48c3f96e46bc.png)

**Comment by sean-mcmanus** [comment]
@HoriKyouko It seems to be picking up a max macro from some other location. Did you set your compilerPath to your gcc compiler? It might be picking up a VC++ header instead.

**Comment by bobbrow** [comment]
The code in the original example looks to be invalid syntax.  I couldn't find a compiler on godbolt.org that successfully compiles it.

**Comment by bobbrow** [comment]
And the original request to ignore errors for specific functions may be covered by #2395
