### ISSUE TITLE
Collapsing a function doesn't hide preproccessor directives

### ISSUE THREAD

**Issue by snake-4** [microsoft/vscode-cpptools#3589]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 x64 17134.753
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.23.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.
When clicking on collapse icon on left of function definition, the code gets hidden until a preprocessor directive inside the function and is annoying with functions that have lots of preprocessor directives.
**To Reproduce**

1. Open a C++ or C file
2. Make a function that contains any preprocessor directive
3. Click on '-' to collapse that function

**Expected behavior**

Preprocessor directives should be hidden too.
**Screenshots**

![capture1](https://user-images.githubusercontent.com/18491360/57240483-3c60cd80-7037-11e9-9798-b44088be426a.PNG)
![capture2](https://user-images.githubusercontent.com/18491360/57240484-3c60cd80-7037-11e9-8f99-2a16c7ab6099.PNG)

**Additional context**

**Comment by bobbrow** [comment]
Thank you for your feedback.  We are tracking this issue via https://github.com/Microsoft/vscode-cpptools/issues/407.
