### ISSUE TITLE
Feature request: custom language server middleware

### ISSUE THREAD

**Issue by felixhao28** [microsoft/vscode-cpptools#3598]
Since version 0.23.0, vscode-cpptools is offered as a bundled file (dist\main.js) instead of separate files for each module. This makes wiring internal modules on-the-fly impossible. I am working on a plugin for vscode-cpptools to filter and sort the completion items in the completion list based on an AI-powered web service, which is practically what [Microsoft IntelliCode](https://github.com/microsoftDocs/intellicode) does.

Before version 0.23.0, I could do something like this:

```ts
const mscpp = vscode.extensions.getExtension("ms-vscode.cpptools");
assert(mscpp.isActive);
const _m = require("module");
const lsext = _m._cache[path.join(mscpp.extensionPath, "out", "src", "LanguageServer", "extension.js")];
const client = lsext.exports.getClients().ActiveClient.languageClient;
const oldProvideCompletionItems = client.clientOptions.middleware.provideCompletionItem;
client.clientOptions.middleware.provideCompletionItem = function(...) {
  const list = await oldProvideCompletionItems(...);
  // sort and filter the list
  return list;
}
```

Now all I got is a CppTools API object, which does not cover the functionality I need. I suggest we export a `getClientCollection` function in CppTools API, which calls `getClients` function in `LanguageServer\extension.ts`, so extensions can have a better control.

**Comment by bobbrow** [comment]
Thank you for your feedback.

We plan to add support for IntelliCode in a future release, so we do not plan to provide a mechanism to alter the completion results at this time.  Doing so would not allow us to ensure the integrity of the results when IntelliCode is enabled.

**Comment by felixhao28** [comment]
I see. I will have to inject the code on our side then. Thanks.
