### ISSUE TITLE
C_Cpp.clang_format_style: IndentWidth is invaild

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-cpptools#360]
_From @yayuntian on November 22, 2016 8:43_

- VSCode Version:1.7.1
- OS Version:windows 10 1607

Steps to Reproduce:

1. install c/c++ plugins
2. edit settings.json

`
{
    "C_Cpp.clang_format_style": "{BasedOnStyle: Google, IndentWidth: 4}"
}`

but c/c++ code indentwidth always display 2

_Copied from original issue: Microsoft/vscode#15866_

**Comment by drewcassidy** [comment]
I am having the same issue on macOS 10.12.1, vscode 1.8.0

**Comment by dongshimou** [comment]
windows 10 ,vscode 1.11.0

same issue.

last,i found the problem.i install `C/C++` and `Clang-Format`.
when i uninstall `Clang-Format`,the indent width was display 4.

**Comment by bobbrow** [comment]
This appears to be fixed in the latest version of the extension.  If you continue to see this problem, please reopen the issue.
