### ISSUE TITLE
Include paths from Provider API not passed on when new file is created

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#3603]
When creating a new file, the intellisense engine does not get sent the header directories for the file. Looking at the debug log, my compiler configuration from my API is sent correctly, however the extra include paths are not. This seems to be reproducible with every header file I create. If I close the file, wait long enough for the server to shutdown, and reopen it starts working again.

- OS and Version: Windows 10 1809
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.23.0
- Other extensions you installed (and if the issue persists after disabling them):

**Comment by bobbrow** [comment]
Can you share the debug logs?  Feel free to redact any sensitive information (e.g. specific folder paths) first.

**Comment by ThadHouse** [comment]
I'll try to reproduce this again later this week. The debug logs iirc showed the defaults being sent to the server rather then the API provided directories, but I'll double check.

**Comment by bobbrow** [comment]
We didn't have enough information to investigate this. If you continue to see a problem here, please send us some repro steps to follow so we can investigate.  Thank you!
