### ISSUE TITLE
Can't intellisense dprintf in stdio.h

### ISSUE THREAD

**Issue by Lobshunter86** [microsoft/vscode-cpptools#3608]
**Type: LanguageService**

**Describe the bug**
- OS and Version: ***Ubuntu 18.04 LTS***
- VS Code Version: ***1.33.1***
- C/C++ Extension Version: ***0.23.0***
- after `#include <stdio.h>`, vscode still can't intellisense function dprintf(), but other functions in the same header file, like fprintf(), works pretty well. I am sure dprinf() is in the header file, and I have tried `#include "absolute path"`, didn't work either.

**To Reproduce**

1. Create an empty *.c file
2. #include <stdio.h>
3. It won't intellisense dprinf() and vdprintf()
4. Says man page: ***The dprintf() and vdprintf() functions were originally GNU extensions that were later standardized in POSIX.1-2008.*** Any influence?

**Screenshots**

![image](https://user-images.githubusercontent.com/32472986/57351954-56fd8880-7196-11e9-9cf3-f83b776dd36f.png)

**Comment by michelleangela** [comment]
This is because the extension does not currently support any `-std=gnuNN` that would include the correct define to the IntelliSense compiler. 

A workaround is to add `_GNU_SOURCE` to your defines in `c_cpp_properties.json` file.
