### ISSUE TITLE
Download fails with remote-ssh plugin?

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3614]
@bobbrow is there a way to do this using the remote-ssh plugin? I had opened a ticket here:

https://github.com/Microsoft/vscode-remote-release/issues/89

since I ran into the same issue. I tried installing the VSIX manually using the instructions above, but I don't think this works on remote-ssh since the plugin needs to be installed remotely. I tried it anyways, and got the same error.

_Originally posted by @cliffburdick in https://github.com/microsoft/vscode-cpptools/issues/2246#issuecomment-490126424_

**Comment by sean-mcmanus** [comment]
@cliffburdick We haven't investigated the remote-ssh extension scenario yet.

**Comment by sean-mcmanus** [comment]
It sounds like the extension is not able to download the platform dependent binaries, i.e. something in the Linux environment is preventing the download.

**Comment by cliffburdick** [comment]
@sean-mcmanus I was able to work around it by disabling auto-updates and installing the insider's VSIX. I don't know what I'm missing by doing that, but that seems to work.

**Comment by pieandcakes** [comment]
@sean-mcmanus Are there proxy settings we need to change in the remote scenario? Is there a way to do it?

**Comment by pieandcakes** [comment]
also: https://github.com/microsoft/vscode-remote-release/issues/231

**Comment by sean-mcmanus** [comment]
@cliffburdick The 0.23.0-insiders2 vsix should be nearly identical to the 0.23.0 offline vsix.

@pieandcakes I don't know. I haven't investigated the remote-ssh plugin at all. We've had a bunch of users report the updating dependencies download failures due to improper http proxy settings compared to what VS Code itself uses, but I haven't been able to figure out a solution -- see the thread at https://github.com/microsoft/vscode-cpptools/issues/3335.

**Comment by bobbrow** [comment]
@sean-mcmanus, are we still having problems with this?

**Comment by sean-mcmanus** [comment]
@bobbrow I don't know. I assume so, since I never investigated it. I mark stuff as "investigate" when I want other people to investigate because I'm too busy.

**Comment by bobbrow** [comment]
I am not seeing any issues downloading the extension binaries with the latest version of the Remote SSH extension.
