### ISSUE TITLE
command C_Cpp.ConfigurationEditJSON not found

### ISSUE THREAD

**Issue by akshsin** [microsoft/vscode-cpptools#3615]
Issue Type: <b>Bug</b>

I am trying to use VS code on my windows machine for c++ development (with WSL).

Following the steps outlined in - https://code.visualstudio.com/docs/cpp/config-wsl

While trying to create the configuration json, using Ctrl+Shift+P, "Edit Configurations":

1. I don't see "Edit Configurations"

2. Do see "Edit Configurations (JSON)" though which I believe should work similarly, but getting this error "command 'C_Cpp.ConfigurationEditJSON' not found".

Extension version: 0.23.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.49GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ReonLion** [comment]
Hello, i have the same problem, did you figure it out?

**Comment by erezak** [comment]
The same happens with the UI configuration command.

**Comment by ReonLion** [comment]
You should have a .cpp file first.

**Comment by bobbrow** [comment]
Thank you for reporting this issue.  We are investigating the root cause.

**Comment by ahmedkrmn** [comment]
A similar error message is also shown for all other extension commands!
I'm running the same VS Code and extension versions as OP.

**Comment by bobbrow** [comment]
Yes, they are all affected.  You can work around this issue by creating and opening a C/C++ file in your new folder before running the command.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.23.1.

**Comment by abdoulayegk** [comment]
I have this problem on visual studio can anyone help me?
"{
	"resource": "/c:/Users/T440s/Desktop/C/test1.c",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 8,
	"message": "#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\\Users\\T440s\\Desktop\\C\\test1.c).",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 18
}"

**Comment by sean-mcmanus** [comment]
@Abdoulaye20 I don't understand what your problem is. Can you give more info, preferably in a new issue?
