### ISSUE TITLE
Disable IntelliSense caching by default?

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3616]
Any reason why the discussion is not about having the "C_Cpp.intelliSenseCacheSize": 0 as default, and then the user can decide whether he wants to use the Intellisense and how? VScode is supposed to be a text editor that can have expanded functionality, not an almost-IDE that can be turned into a text-editor by changing the settings back to zero after checking the issue in github and finding what exactly is that ipch folder that the extension creates automatically by simply having a file opened.

_Originally posted by @JavierReyes945 in https://github.com/microsoft/vscode-cpptools/issues/3347#issuecomment-490253111_

**Comment by sean-mcmanus** [comment]
@JavierReyes945 We're continuing to listen to feedback and gather data etc. on this. The thinking is that we want the "default" experience to be an improved performance experience to match what VS does. We were already creating a database file in the workspace storage location that could be many GB in size for large workspaces (but it doesn't default to the .vscode folder).

Another request we've heard is to change the default intelliSenseCachePath to a shared location instead of each workspace's .vscode folder.

**Comment by ThadHouse** [comment]
I think a shared path with an LRU algorithm to delete older files would be the right way to go. I originally didn't care that much, but I've been opening a bunch of small projects for debugging little things lately, and my disk space is skyrocketing because of all the separate files. I think with a shared path, most people would be OK with having a 5GB default limit, its just that per project that is WAY too high, as 20 projects could fill 100GB, and some people might open that many files per day.

**Comment by JavierReyes945** [comment]
With all due respect: If the creation of that folder that can easily go up to several GB, it should not be the default behaviour. No other extension in VSCode works like that (specially without notifying the user about it, or at least making sure that the user understands what implies and allowing to disable the setting during installation). Keep in mind that editing a Cpp file is not only done on larger projects. Someone in a small setup might want to edit a file for an embedded project, and having such a large disk usage in a TEXT EDITOR makes no sense.

**Comment by sean-mcmanus** [comment]
Our current plan is to switch to a shared path like `<AppData>/.cpptools` so the default is a 5 GB limit (not sure when that work will ship though, unless someone wants to submit a pull request themselves). The main argument against turning it off by default is that we're worried about too many users getting reduced performance if the default is off...we're still discussing this internally though...

**Comment by JavierReyes945** [comment]
> The main argument against turning it off by default is that we're worried about too many users getting reduced performance if the default is off...we're still discussing this internally though...

The counter argument would be the massive impact that the feature adds on a system, specially if no information is given at installing time, or even a big note in the README. Keep in mind, as said before, that VSCode product is considered a **text editor** with extensible capabilities (user chooses if/when to enable them). Such default behavior is acceptable for an IDE-like product (where disk space saving is not a main concern, as large projects are the norm). I happen to use VScode in environments where the quota of user space is rather limited, and therefore was worried about this behavior. But even assuming the use case of a beginner, that starts learning and uses the code editor, installs the extension as it is also a Microsoft product, and by creating/opening a simple source file, its workspace (or any other folder you choose) will be bloated without any notice. If not possible to turn it off by default, at least make a notice during install, to let the user know the consequences of the InteliSense cache, which are not trivial in the era of large HDD/small SSD migration.

**Comment by tomatac** [comment]
What about changing the default maximum cash to a reasonable amount: 100 MB and inform the user if more space is needed? What about purging some of the old cashed data?

**Comment by sean-mcmanus** [comment]
@tomatac We switched the default IntelliSense cache location to be shared amongst workspaces. 100 MB is too small for the cache to be effective (one TU might be 100 MB). We already replace the old cache data with new cache data after the limit is hit.

**Comment by tomatac** [comment]
That makes sense. What about 1 GB? I believe that the default is 5 GB and there is no way to know what cash file is associated with what project. Is there an easy way to clear the cash?

**Comment by sean-mcmanus** [comment]
@tomatac 5 GB is also the default used by VS and we haven't gotten enough user feedback to lower that default to 1 GB. Setting the intelliSenseCacheSize to 0 should clear the cache. If your intelliSenseCachePath is set to the default, then the files could be created from multiple projects, but if you search for files with .ipch extensions you can see the file names of the original files.

**Comment by bobbrow** [comment]
Thank you for your feedback!  We do not plan to change the default value for this setting.  If we see more feedback/upvotes from the community, we can come back to this and reassess.
