### ISSUE TITLE
Could you add a path setting to storage cpptools database and intelli sense cache

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3619]
Currently there are so many settings in cpptools extension. I suggest to add a path setting to storage cpptools database and intelli sense cache. Currently I can't configure cpptools database to another folder which is not in workspace because when I open another folder with vscode, the db will be replaced. So I want  a folder path like intelli sense cache path to storage database. it's better if there is only one folder path to storage all of these.

**Comment by Lennon925** [comment]
Also, I think it's strange to configure database filename instead of storagepath. It's not convenient. Currently I must set this setting to workspace folder and ignore it in gitignore to prevent to submit it to source by mistakes.

**Comment by bobbrow** [comment]
Thank you for the feedback.  We are currently tracking this with issue #1404.  Could you please go and upvote that issue?  It helps us to track the priority of the feature request.

**Comment by sean-mcmanus** [comment]
@Lennon925 It sounds like your issue could be solved via setting `"C_Cpp.default.browse.databaseFileName": "F:/storageLocation/${workspaceFolderBasename}/database.db"` and `"C_Cpp.intelliSenseCachePath"` to either the same thing or shared location (minus the filename).

Well...assuming you don't have multiple workspaces folders with the same "basename".
