### ISSUE TITLE
Ctrl  + mouse over symbol feature

### ISSUE THREAD

**Issue by dfroze** [microsoft/vscode-cpptools#362]
Hy there,
When **mouse over** symbol and **Ctrl** button is **pressed**, a preview box is displayed regarding the symbol. I am saying preview box cause I don't know it's name and no, i am not talking about peek feature.

The preview box only displays the declaration line. Is there a way to display more line in the 'preview box', such as declaration and 5 more line of code?

As well, is there a way to display it without holding the Ctrl button? For example to display the info after having the mouse over the symbol for  0.5s ?

**Comment by dfroze** [comment]
P.S: how can I join and help with vscode-cpptools? I would have wanted to help with vscode , but I see there are a lot o people there and can hardly help.

**Comment by ronglums** [comment]
Hi dfroze,

Thanks for the feedback! To view the full definition of a symbol, it's highly recommended to use the GoToDefinition or Peek Definition feature. Please let us know if they're not meeting your needs. The mouse hover + Ctrl functionality is for a quick preview of the function name (mouse hover over the symbol works too), and currently we don't have plans to expand it to include the function body. That being said, I'd like to understand your requirements a little bit better for future considerations: would you like to see the **Definition** or **Declaration** of the symbol in the Preview window?

Thanks for offering to help with the extension. The extension is not open-sourced at the moment. Sharing your feedback and suggestions would be a great way of helping us and we really appreciate that.

Best regards,
Rong Lu
Program Manager, Visual Studio

**Comment by sean-mcmanus** [comment]
@dfroze If you want to help with vscode-cpptools, you can help fix bugs with the C++ syntax highlighting, which is open source at https://github.com/atom/language-c . When bugs fixes are made there, VS Code can integrate in the changes (in the Insider build first) and then all C/C++ users can benefit.

**Comment by bobbrow** [comment]
This is not something we plan to implement for the extension.
As far as the suggestion to display it after hovering for 0.5s, you would need to open a feature request for VS Code since it's not something we can control in the extension.
