### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lan99mu** [microsoft/vscode-cpptools#3620]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.23.0-insiders2`
- OS Version: `Linux x64 4.15.0-29deepin-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/lisanmu/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bobbrow** [comment]
Please attach the requested file `/home/lisanmu/ms-vscode.cpptools-unresponsive.cpuprofile.txt` so we can investigate.  This should have been fixed in 0.23.0 with #3213.
