### ISSUE TITLE
envFile option for cppdbg

### ISSUE THREAD

**Issue by SolalVall** [microsoft/vscode-cpptools#3624]
Type: Debugger

Hi,

it would be great to add the "envFile" option to the launch.json file for the cppdbg debugger.

Like you did for cppvsdbg debugger: #3490 

Thanks in advance

**Comment by pieandcakes** [comment]
@WardenGnaw

**Comment by WardenGnaw** [comment]
https://github.com/microsoft/vscode-cpptools/pull/3723
