### ISSUE TITLE
Unable to read property length of 'undefined'

### ISSUE THREAD

**Issue by Stalker2106** [microsoft/vscode-cpptools#3625]
Issue Type: <b>Bug</b>

When I create a debugging configuration for GDB/LLDB on macOS El Capitan (10.11.6), a message shows that vscode is unable to create the configuration file 'launch.json' inside the '.vscode' folder (Unable to read property length of 'undefined')

Extension version: 0.23.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|Model|Mac Mini Late 2009|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8700  @ 2.53GHz (2 x 2530)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|4.00GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
Is this https://github.com/microsoft/vscode-cpptools/issues/3583 ? Do you have the intelliSenseEngine set to Disabled?

**Comment by Stalker2106** [comment]
Not exactly the same bug.
You can achieve the creation of 'launch.json' through the dropdown list, but if you select gdb/lldb via the 'gear' icon, the error occurs.
When launch.json exists, you cannot reproduce error.

IntelliSenseEngine is set to Default.

Regards

**Comment by sean-mcmanus** [comment]
Okay, it sounds like a different issue -- are you able to use Toggle Developer Tools to provide a call stack or the property that is undefined? I'm trying to get a repro, but it's not reproing for me on Mac (I get a Select a Configuration prompt with g++-6 and 5 other compilers and "Default Configuration").

**Comment by sean-mcmanus** [comment]
I've reproed the bug -- it occurs if it's used before our language service activates. I believe https://github.com/microsoft/vscode-cpptools/issues/3615 is the same issue, but I'll double check if that fixes this as well.

**Comment by Stalker2106** [comment]
As always, when pointed out, cannot reproduce anymore ! Ahh...
Quitted vscode, removed .vscode folder, started vscode,
And it (weirdly) reinstalled dependencies (5 of them, including lldb).
It looks like it is fine now. I guess when LLDB is 'dirty'-installed, the error shows.
Will try to uninstall and reinstall addon to reproduce.

Edit: Good find! I hope you're on track with this!

**Comment by sean-mcmanus** [comment]
If you have a .c/.cpp file open or a c_cpp_properties.json, then the bug shouldn't repro.

The bug only repros on Mac (which is strange).

**Comment by sean-mcmanus** [comment]
What version of "node" do you have installed on your machine?

I appear to have stopped reproing the bug after upgrading from node 6 to node 12 (my other machines had node 8 and didn't repro the issue).

**Comment by Stalker2106** [comment]
I haven't installed any version myself, so either the XCode CLI tools have installed one, or vscode deploys one. I don't have the machine around to give you that information, but will sure do later on.

**Comment by sean-mcmanus** [comment]
Yeah, installing "node" shouldn't be required unless you do TypeScript/JavaScript development, but maybe VS Code itself has some strange bug/dependency on the system's node version or one of our dependencies is buggy with node 6 -- our development version of the extension requires it. @michelleangela @Colengms Are any of you able to repro this bug still?
