### ISSUE TITLE
Incorrect squiggle after code update

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-cpptools#3626]
Issue Type: <b>Bug</b>

The information pop-up has already noticed the code update, but squiggle keeps showing error
![image](https://user-images.githubusercontent.com/8154646/57497131-f6428d00-7308-11e9-93d7-b4f3e8ab90e5.png)

Extension version: 0.23.0
VS Code version: Code - Insiders 1.34.0-insider (473af338e1bd9ad4d9853933da1cd9d5d9e07dc9, 2019-05-01T00:22:05.899Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-957.10.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-957.10.1.el7.x86_64
Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a22484b444556313232227d' timed out.

**Comment by sean-mcmanus** [comment]
The hover result is coming from a different system than the "undefined" message. Are you missing an includePath or define that is required? Can you go to the definition of the narrowTicks and see if hover on that works?

Can you run the C/C++: Log Diagnostics command?

**Comment by Victsz** [comment]
The variable declare is several lines above this line so include path might not be an issue, also ctrl+left click can jump to the define statement. Actually the squiggle will disappear after minutes. It takes the "undefined message system" much longer time to notice the code update compared to the "hover result system".

**Comment by sean-mcmanus** [comment]
Yeah, the error squiggle requires IntelliSense to parse the entire translation unit, so if it takes a long time, the error squiggles for invalid temporary code might appear until the parsing (red flame) is finished. We have some work planned to potentially speed up the updating of the error squiggles.

**Comment by bobbrow** [comment]
This should have been addressed with #7759. If you are still experiencing issues with this, please let us know.
