### ISSUE TITLE
outline is not correct

### ISSUE THREAD

**Issue by alianZhen** [microsoft/vscode-cpptools#3634]
C/Cpp version：0.23.0

I define a macro scan_list
when I don't use it ,the symbol in outline is correct.
![image](https://user-images.githubusercontent.com/27906971/57591334-66e4e600-7563-11e9-9d93-d1c7be6cd64f.png)
But when I use macro in my function,the symbol in outline seems wrong.
![image](https://user-images.githubusercontent.com/27906971/57591384-a27fb000-7563-11e9-97fe-71dad61bca63.png)

**Comment by sean-mcmanus** [comment]
This is "by design". The macro that require evaluation in order to parse the code correctly need to be added to a cpp.hint file in your workspace. See https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2019 . Let us know if that doesn't work.

**Comment by sean-mcmanus** [comment]
FYI, this is fixed with 1.10.3 (pre-release) -- no cpp.hint is required for this case.
