### ISSUE TITLE
No support for Apple/Clang block syntax for C

### ISSUE THREAD

**Issue by boborbt** [microsoft/vscode-cpptools#3636]
**Type: LanguageService**

The extension does not seem to support Apple/Clang block syntax for C.

**Describe the bug**
- OS and Version: Mac Os 10.14.4
- VS Code Version: 1.33.1 (1.33.1)
- C/C++ Extension Version: 0.23.0

There is no support for apple/clang block syntax. 
Major problems:
- __block decoration are marked as errors (error message is '''identifier "__block" is undefined''')
- the '''^{}''' notation for introducing a block is marked as erroneous (error message is: "expected expression").

**To Reproduce**

Create a new folder with the following C file:

```C
#include <stdio.h>

typedef const char* (^Callback)();

static void hello_world_wb(Callback callback) {
    printf("Hello %s!\n", callback());
}


int main(int argc, char const *argv[])
{   
    __block const char* world = NULL;

    hello_world_wb(^{
        world = "world";
        return world;
    });
    return 0;
}
```

The extension should be marking the ^ and the __block symbols as mentioned above.

**Expected behavior**

The extension should treat the block syntax as correct.

**Comment by sean-mcmanus** [comment]
Our parser doesn't currently support the -fblocks extension. I filed a bug (feature request) for VS at https://developercommunity.visualstudio.com/content/problem/566828/cc-intellisense-doesnt-support-fblocks-in-windows.html . If you have a Microsoft account you can login to upvote that.

**Comment by minkir014** [comment]
C/C++ clang extension provide that.

**Comment by boborbt** [comment]
Hi minkir014, thanks for the hint. 

I did not find exactly the package you mentioned, but its closest match: "C/C++ Clang Command Line Adapter" indeed solves the
