### ISSUE TITLE
intelliSenseMode clang-x64 in incompatible with compilerPath

### ISSUE THREAD

**Issue by Kri-Ol** [microsoft/vscode-cpptools#3637]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1809 x64
- VS Code Version: 1.33.1
- C/C++ Extension Version: 0.23 insides
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
Have Intellisense mode set to "clang-x64", and "compilerPath": "C:/Program Files/LLVM/bin/clang-cl.exe", which is LLVM 8.0. Compiler works fine, but there is warning message which is not right, I believe
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Kri-Ol** [comment]
"windowsSdkVersion": "10.0.17763.0",
            "compilerPath": "C:/Program Files/LLVM/bin/clang-cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",

Clang-cl from LLVM v8.0 is main compiler used alongside with Visual C++ 2019 Pro

**Comment by minkir014** [comment]
Remove `compiler path` setting intellisense works great without it.

**Comment by michelleangela** [comment]
Hi @Kri-Ol, the usage of compiler `clang-cl.exe` with IntelliSense mode `clang-x64` should not show an incompatibility error message. You can use `clang-x64` with `clang-cl.exe` and just ignore the error. I'll change the logic that validates the compatibility; the fix will be available in a future release.

**Comment by minkir014** [comment]
I say if he removed that setting that will work. It works for me greatly.

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders (available by setting "C_Cpp.updateChannel" to "Insiders").
