### ISSUE TITLE
Downloading package 'C/C++ language components (Windows)'  Failed.

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3640]
win10 64bit ms-vscode.cpptools-0.23.0 
Can you help me with this error?I'm online,it didn't work even though i uninstalled version 0.23.0 and then installed version 0.22.1.
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'ClangFormat (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Visual Studio Windows Debugger'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: end of central directory record signature not found

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.

_Originally posted by @Gan-Jason in https://github.com/microsoft/vscode-cpptools/issues/694#issuecomment-491528616_

**Comment by sean-mcmanus** [comment]
@Gan-Jason Your http-proxy settings might be misconfigured. You could try downloading/installing the offline vsix (or setting the C_Cpp.updateChannel to "Insiders).

**Comment by Gan-Jason** [comment]
> @Gan-Jason Your http-proxy settings might be misconfigured. You could try downloading/installing the offline vsix (or setting the C_Cpp.updateChannel to "Insiders).

thanks,i make it after installing the offline vsix.lol

**Comment by EndOfTheGlory** [comment]
Hey,I am installing this online and it still give me such an error.Should I perhaps dobwload for offline enviroment?I don't even know why this problem occured in the first place.

**Comment by sean-mcmanus** [comment]
@EndOfTheGlory It could be some proxy issue from our OS-specific download -- after VS Code allows OS-specific vsix's this issue should get fixed. Yeah, the workaround is to use the Install from VSIX command with the "offline" vsix on our releases page.

**Comment by philipzhong222** [comment]
Hi, I get the same error:
Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: end of central directory record signature not found

After I download offline cpptools-osx.vix, it shows timeout error:
PS C:\> code --install-extension cpptools-osx.vix
Installing extensions...
connect ETIMEDOUT 13.107.6.175:443
Failed Installing Extensions: cpptools-osx.vix
PS C:\> code --install-extension cpptools-osx.vix
Installing extensions...
connect ETIMEDOUT 13.107.6.175:443
Failed Installing Extensions: cpptools-osx.vix

Can you please take a look? Thanks.

**Comment by philipzhong222** [comment]
Never mind, I download cpptools-win32.vsix and install it successfully. I install in Windows 10.
What OS should be used for cpptools-osx.vix?

**Comment by michelleangela** [comment]
@philipzhong222 

cpptools-linux.vsix - for 64-bit Linux
cpptools-linux32.vsix - for 32-bit Linux
cpptools-osx.vsix - for macOS
cpptools-win32.vsix - for 64-bit & 32-bit Windows

**Comment by General-Delta1** [comment]
Hello!!!! here is what i am seeing i don't know why ;
Downloading package 'C/C++ language components (Windows)' (6758 KB)  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds...(6758 KB)  Done!
Downloading package 'ClangFormat (Windows)' (794 KB)  Done!
Downloading package 'Visual Studio Windows Debugger' (13813 KB)  Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: invalid central directory file header signature: 0x7117c6a4

**Comment by sean-mcmanus** [comment]
@Genal-Delta1 You've hit some unknown download/install issue.  Can you try again or download/install the offline vsix at https://github.com/microsoft/vscode-cpptools/releases/download/0.28.0/cpptools-win32.vsix (run the "Install from VSIX" command in VS Code).
