### ISSUE TITLE
 Intelli Sense Cache Path Bug

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3642]
- C/C++ Extension Version: 0.23.1

I set  "Intelli Sense Cache Path" to "D:/storageLocation/${workspaceFolderBasename}/".
If I have three folders which have the same name 'cpptools-demo‘ and have different storage path，it goes wrong.

Open first folder, it created cpptools-demo folder in D:/storageLocation
Open second folder, it create untitled folder in D:/storageLocation
Open third folder, it didn't create folder in D:/storageLocation any more.

In addition, is there a way to set the cache path to where cpptools browse.db is storaged, ,"AppData\Roaming\Code\User\workspaceStorage"?

**Comment by sean-mcmanus** [comment]
Yeah, I'm seeing the ${workspaceFolderBasename} incorrectly being resolved to "untitled".

Also, I'm seeing bogus temporary paths getting created while the setting is changed in the UI editor. I filed a bug at https://github.com/microsoft/vscode-cpptools/issues/3644 .

There isn't a way currently to set the location to the "workspaceStorage" location. Is there an issue on this already?

**Comment by sean-mcmanus** [comment]
I have a fix at https://github.com/microsoft/vscode-cpptools/pull/3643 . I'm not able to repro the bugs after that.

**Comment by Lennon925** [comment]
> Yeah, I'm seeing the ${workspaceFolderBasename} incorrectly being resolved to "untitled".
> 
> Also, I'm seeing bogus temporary paths getting created while the setting is changed in the UI editor. I filed a bug at #3644 .
> 
> There isn't a way currently to set the location to the "workspaceStorage" location. Is there an issue on this already?

I tried to set ${workspaceFolderBasename} to cpptools database storage path, there is only one cpptool-demo folder when I opened many folders which have the same name but have different storage path.

If I use ${workspaceFolderBasename}, folders which have the same name but have different storage path will be regarded as a same folder, right?

**Comment by sean-mcmanus** [comment]
Yeah, using ${workspaceFolderBasename} just uses the name and not the storage path -- the storage path creates a hash for the workspace. However, I think we could create our own ${workspaceStorage} variable that resolves to the storage path and add that to the AdditionalEnvironment in the exact same we do do for the ${workspaceFolderBasename}, which would allow users to use that location for the intelliSenseCachePath.

**Comment by sean-mcmanus** [comment]
@Lennon925 I've also added a ${workspaceStorage} variable (which resolves to the full path of the storage location), so you could use that.

**Comment by Lennon925** [comment]
> @Lennon925 I've also added a ${workspaceStorage} variable (which resolves to the full path of the storage location), so you could use that.

Thanks very much!

**Comment by Lennon925** [comment]
> @Lennon925 I've also added a ${workspaceStorage} variable (which resolves to the full path of the storage location), so you could use that.

you added a  ${workspaceStorage} variable for cpptools database, too?

**Comment by sean-mcmanus** [comment]
Yes, at https://github.com/microsoft/vscode-cpptools/pull/3643 -- it hasn't been checked in yet, but it should soon.

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders (available by setting "C_Cpp.updateChannel" to "Insiders").
