### ISSUE TITLE
Request to search for all references

### ISSUE THREAD

**Issue by prashanjitghosh** [microsoft/vscode-cpptools#3645]
Issue Type: <b>Feature Request</b>

I use the VS code for C++ and C projects. I have also installed this extension. can you please tell if there is "Search for all refrences"  feature if not can you implement this?

Extension version: 0.23.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Lennon925** [comment]
I need this, too.

**Comment by noxabellus** [comment]
I agree this would be great to have

**Comment by michelleangela** [comment]
The implementation for this feature is in progress and is being tracked by #15

**Comment by sean-mcmanus** [comment]
Find All References is available in 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders , but you'll need to set the C_Cpp.experimentalFeatures setting to "Enabled".
