### ISSUE TITLE
Enable unlimited string size for gdb

### ISSUE THREAD

**Issue by rynz** [microsoft/vscode-cpptools#3646]
Type: Debugger
**Input information below**
Perhaps it is a good idea to change the default configuration for Windows and Linux to enable unlimited string size for gdb.

**Comment by pieandcakes** [comment]
@rynz what is the reason to permanently turn this on? This does not seem like a good default setting to include for all users especially if they end up with really long strings. It looks like the default is 200. Is that too short?

**Comment by rynz** [comment]
@pieandcakes to my knowledge Visual Studio does not impose a limit. For my personal use case, I needed to be able to copy byte arrays as hex from the debugger, and as I could not do it by inspecting the arrays (eg: watching `buf,x` it still only copies one value when you select many and also has a limit) I, therefore, converted them to strings where the default limit of 200 was not enough.

The reason why I suggest this change is because it only affects the default configuration template and is a good chance to expose developers to the configuration detail, whether they choose to keep it or not is up to them.

**Comment by pieandcakes** [comment]
I think it would be good to document the ability to change it and how to configure it but I don't believe that setting it to unlimited is the right thing to do. @WardenGnaw mentioned adding a separate configuration document for additional `gdb` commands and linking it in the [launch.md](https://github.com/microsoft/vscode-cpptools/blob/master/launch.md) file under setupCommands and I believe that is the right way to go.
