### ISSUE TITLE
Debugger Doesn't step into function

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode-cpptools#3648]
When I launch the debugger it works but it can't step into functions like that:

![Screenshot (32)](https://user-images.githubusercontent.com/42807112/57702763-0a66f100-765f-11e9-962e-2b84debadf03.png)

When I make a step it goes like this

![Screenshot (33)](https://user-images.githubusercontent.com/42807112/57702800-1c489400-765f-11e9-9524-d314c642cdca.png)

**Comment by pieandcakes** [comment]
@minkir014 Please enable [engineLogging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) and provide a log.

**Comment by minkir014** [comment]
This is my `launch.json` I changed it as I understood that article

![Screenshot (34)](https://user-images.githubusercontent.com/42807112/57727567-233cca00-7692-11e9-8ce8-7df384a8cd24.png)


and this is what is shown in the debug console


![Screenshot (35)](https://user-images.githubusercontent.com/42807112/57727630-47001000-7692-11e9-9832-7e64fa3fa5a0.png)


and when I step nothing changes in the debug console.

**Comment by minkir014** [comment]
I understood what you mean ant this is `launch.json`

![Screenshot (36)](https://user-images.githubusercontent.com/42807112/57727945-fdfc8b80-7692-11e9-8033-2140fe7a2346.png)



and this is the output in the debug console before the step

`1: (315) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
1: (340) LaunchOptions  ExePath='C:\Users\MINKIR\Desktop\Calculator\gii\CPP\a.exe'
1: (340) LaunchOptions  WorkingDirectory='C:\Users\MINKIR\Desktop\Calculator\gii\CPP'
1: (341) LaunchOptions  ExeArguments=''
1: (342) LaunchOptions  MIMode='gdb'
1: (342) LaunchOptions  MIDebuggerPath='E:\MIN\bin\gdb.exe'
1: (343) LaunchOptions  WaitDynamicLibLoad='false'
1: (343) LaunchOptions  ExternalConsole='true'
1: (344) LaunchOptions>
1: (347) LaunchOptions    <SetupCommands>
1: (348) LaunchOptions        <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>
1: (348) LaunchOptions    </SetupCommands>
1: (349) LaunchOptions</LocalLaunchOptions>
1: (511) Starting: "E:\MIN\bin\gdb.exe" --interpreter=mi
1: (523) DebuggerPid=2908
1: (756) ->=thread-group-added,id="i1"
1: (764) ->~"GNU gdb (GDB) 7.6.1\n"
1: (765) ->~"Copyright (C) 2013 Free Software Foundation, Inc.\n"
1: (769) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
1: (770) ->~"This GDB was configured as \"mingw32\".\nFor bug reporting instructions, please see:\n"
1: (770) ->~"<http://www.gnu.org/software/gdb/bugs/>.\n"
1: (779) ->(gdb)
1: (798) <-1001-gdb-set target-async on
1: (821) ->1001^done
1: (822) ->(gdb)
1: (827) 1001: elapsed time 31
1: (859) ->&"\n"
1: (966) <-1002-enable-pretty-printing
1: (970) ->^done
1: (970) ->(gdb)
1: (1006) ->1002^done
1: (1043) 1002: elapsed time 77
1: (1044) <-1003-interpreter-exec console "set pagination off"
1: (1044) ->(gdb)
1: (1050) ->&"\n"
1: (1055) ->^done
1: (1057) ->(gdb)
1: (1062) ->=cmd-param-changed,param="pagination",value="off"
1: (1070) ->1003^done
1: (1070) ->(gdb)
1: (1071) ->&"\n"
1: (1072) ->^done
1: (1073) ->(gdb)
1: (1074) 1003: elapsed time 30
1: (1075) <-1004-gdb-set auto-solib-add on
1: (1082) ->1004^done
1: (1084) ->(gdb)
1: (1086) 1004: elapsed time 11
1: (1088) <-1005-gdb-set solib-search-path C:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP;
1: (1156) ->&"\n"
1: (1190) ->^done
1: (1194) ->(gdb)
1: (1228) ->1005^done
1: (1231) ->(gdb)
1: (1248) 1005: elapsed time 160
1: (1272) <-1006-environment-cd C:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP
1: (1273) ->&"\n"
1: (1278) ->^done
1: (1279) ->(gdb)
1: (1304) ->1006^done
1: (1308) ->(gdb)
1: (1315) 1006: elapsed time 43
1: (1315) <-1007-gdb-set new-console on
1: (1316) ->&"\n"
1: (1326) ->^done
1: (1327) ->(gdb)
1: (1346) ->1007^done
1: (1367) ->(gdb)
1: (1373) 1007: elapsed time 58
1: (1390) <-1008-interpreter-exec console "show configuration"
1: (1393) ->&"\n"
1: (1393) ->^done
1: (1394) ->(gdb)
1: (1411) ->&"Undefined show command: \"configuration\".  Try \"help show\".\n"
1: (1413) ->1008^error,msg="Undefined show command: \"configuration\".  Try \"help show\"."
1: (1452) ->(gdb)
1: (1468) 1008: elapsed time 78
1: (1497) <-1009-file-exec-and-symbols C:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\a.exe
1: (1528) ->&"\n"
1: (1532) ->^done
1: (1533) ->(gdb)
1: (1542) ->1009^done
1: (1545) ->(gdb)
1: (1550) 1009: elapsed time 53
1: (1551) <-1010-interpreter-exec console "show architecture"
1: (1552) ->&"\n"
1: (1555) ->^done
1: (1574) ->(gdb)
1: (1581) ->~"The target architecture is set automatically (currently i386)\n"
1: (1613) ->1010^done
1: (1613) ->(gdb)
1: (1614) ->&"\n"
1: (1614) ->^done
1: (1615) ->(gdb)
1: (1643) 1010: elapsed time 92
1: (1646) <-1011-break-insert -f main
1: (1698) ->1011^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0040143b",func="main()",file="str.cpp",fullname="c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp",line="11",thread-groups=["i1"],times="0",original-location="main"}
1: (1698) ->(gdb)
1: (1715) 1011: elapsed time 69
1: (1748) Send Event AD7EngineCreateEvent
1: (1765) Send Event AD7ProgramCreateEvent
1: (1823) ->&"\n"
1: (1830) ->^done
1: (1833) ->(gdb)
1: (2365) <-1012-break-insert -f str.cpp:11
1: (2369) ->1012^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x0040143b",func="main()",file="str.cpp",fullname="c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp",line="11",thread-groups=["i1"],times="0",original-location="str.cpp:11"}
1: (2371) ->(gdb)
1: (2382) 1012: elapsed time 17
1: (2435) ->&"\n"
1: (2600) ->^done
1: (2600) ->(gdb)
1: (2655) Send Event AD7BreakpointErrorEvent
1: (2674) <-1013-symbol-list-lines c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp
1: (2687) ->1013^done,lines=[{pc="0x00401410",line="6"},{pc="0x00401416",line="7"},{pc="0x0040142a",line="8"},{pc="0x0040142d",line="10"},{pc="0x00401436",line="10"},{pc="0x0040143b",line="11"},{pc="0x00401440",line="12"},{pc="0x0040144c",line="13"},{pc="0x00401453",line="0"},{pc="0x00401465",line="13"},{pc="0x0040146b",line="13"},{pc="0x0040147a",line="0"},{pc="0x00401490",line="13"},{pc="0x00401493",line="13"},{pc="0x00401499",line="13"},{pc="0x004014af",line="0"}]
1: (2688) ->(gdb)
1: (2690) 1013: elapsed time 16
1: (2739) ->&"\n"
1: (2780) Send Event AD7BreakpointBoundEvent
1: (2810) ->^done
1: (2811) ->(gdb)
1: (4238) Send Event AD7LoadCompleteEvent
=thread-group-added,id="i1"
GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
1: (4255) <-1014-exec-run
1: (4265) ->=thread-group-started,id="i1",pid="4380"
1: (4498) ->=thread-created,id="1",group-id="i1"
1: (4523) <-1015-thread-info 1
1: (4543) ->~"[New Thread 4380.0x16cc]\n"
1: (4545) ->1014^running
1: (4545) ->*running,thread-id="all"
1: (4545) ->(gdb)
1: (4546) ->=library-loaded,id="C:\\Windows\\system32\\kernel32.dll",target-name="C:\\Windows\\system32\\kernel32.dll",host-name="C:\\Windows\\system32\\kernel32.dll",symbols-loaded="0",thread-group="i1"
1: (4546) ->=library-loaded,id="C:\\Windows\\system32\\KernelBase.dll",target-name="C:\\Windows\\system32\\KernelBase.dll",host-name="C:\\Windows\\system32\\KernelBase.dll",symbols-loaded="0",thread-group="i1"
1: (4547) ->=library-loaded,id="C:\\Windows\\system32\\msvcrt.dll",target-name="C:\\Windows\\system32\\msvcrt.dll",host-name="C:\\Windows\\system32\\msvcrt.dll",symbols-loaded="0",thread-group="i1"
1: (4547) ->=library-loaded,id="E:\\MIN\\bin\\libgcc_s_dw2-1.dll",target-name="E:\\MIN\\bin\\libgcc_s_dw2-1.dll",host-name="E:\\MIN\\bin\\libgcc_s_dw2-1.dll",symbols-loaded="0",thread-group="i1"
1: (4548) ->=library-loaded,id="E:\\MIN\\bin\\libstdc++-6.dll",target-name="E:\\MIN\\bin\\libstdc++-6.dll",host-name="E:\\MIN\\bin\\libstdc++-6.dll",symbols-loaded="0",thread-group="i1"
[New Thread 4380.0x16cc]
1: (4572) 1014: elapsed time 317
1: (4773) ->=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0040143b",func="main()",file="str.cpp",fullname="c:\\\\Users\\\\MINKIR\\\\Desktop\\\\Calculator\\\\gii\\\\CPP\\\\str.cpp",line="11",thread-groups=["i1"],times="1",original-location="main"}
1: (4818) ->=breakpoint-modified,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x0040143b",func="main()",file="str.cpp",fullname="c:\\\\Users\\\\MINKIR\\\\Desktop\\\\Calculator\\\\gii\\\\CPP\\\\str.cpp",line="11",thread-groups=["i1"],times="1",original-location="str.cpp:11"}
1: (4826) ->*stopped,reason="breakpoint-hit",disp="keep",bkptno="1",frame={addr="0x0040143b",func="main",args=[],file="str.cpp",fullname="c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp",line="11"},thread-id="1",stopped-threads="all"
1: (4826) ->(gdb)
1: (4827) ->&"\n"
1: (4827) ->^done
1: (4828) ->(gdb)
1: (4829) <-1016-symbol-list-lines c:\\\\Users\\\\MINKIR\\\\Desktop\\\\Calculator\\\\gii\\\\CPP\\\\str.cpp
1: (4847) ->1015^done,threads=[{id="1",target-id="Thread 4380.0x16cc",frame={level="0",addr="0x0040143b",func="main",args=[],file="str.cpp",fullname="c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp",line="11"},state="stopped"}]
1: (4847) ->(gdb)
1: (4854) ->&"\n"
1: (4854) ->^done
1: (4855) ->(gdb)
1: (4857) ->1016^done,lines=[{pc="0x00401410",line="6"},{pc="0x00401416",line="7"},{pc="0x0040142a",line="8"},{pc="0x0040142d",line="10"},{pc="0x00401436",line="10"},{pc="0x0040143b",line="11"},{pc="0x00401440",line="12"},{pc="0x0040144c",line="13"},{pc="0x00401453",line="0"},{pc="0x00401465",line="13"},{pc="0x0040146b",line="13"},{pc="0x0040147a",line="0"},{pc="0x00401490",line="13"},{pc="0x00401493",line="13"},{pc="0x00401499",line="13"},{pc="0x004014af",line="0"}]
1: (4857) ->(gdb)
1: (4863) ->&"\n"
1: (4864) ->^done
1: (4865) ->(gdb)
1: (4904) <-1017-thread-info
1: (4913) 1015: elapsed time 390
1: (4914) ->1017^done,threads=[{id="1",target-id="Thread 4380.0x16cc",frame={level="0",addr="0x0040143b",func="main",args=[],file="str.cpp",fullname="c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp",line="11"},state="stopped"}],current-thread-id="1"
1: (4915) ->(gdb)
1: (4922) Send Event AD7ProcessInfoUpdatedEvent
1: (4924) Send Event AD7ThreadCreateEvent
1: (4927) ->&"\n"
1: (4941) 1016: elapsed time 112
1: (4945) 1017: elapsed time 41
1: (4950) ->^done
1: (4950) ->(gdb)
1: (4993) <-1018-stack-list-frames 0 1000
1: (4999) ->1018^done,stack=[frame={level="0",addr="0x0040143b",func="main",file="str.cpp",fullname="c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp",line="11"}]
1: (5000) ->(gdb)
1: (5006) 1018: elapsed time 12
1: (5024) ->&"\n"
1: (5037) ->^done
1: (5038) ->(gdb)
1: (5079) <-1019-interpreter-exec console "info sharedlibrary"
1: (5099) ->~"From        To          Syms Read   Shared Object Library\n"
1: (5127) ->~"0x77a31000  0x77b28320  Yes         C:\\Windows\\system32\\kernel32.dll\n"
1: (5132) ->~"0x75611000  0x756e1a80  Yes         C:\\Windows\\system32\\KernelBase.dll\n"
1: (5133) ->~"0x77971000  0x77a2d818  Yes         C:\\Windows\\system32\\msvcrt.dll\n"
1: (5134) ->~"0x6eb41000  0x6eb637fc  Yes         E:\\MIN\\bin\\libgcc_s_dw2-1.dll\n"
1: (5134) ->~"0x6fe41000  0x6ffb8a68  Yes         E:\\MIN\\bin\\libstdc++-6.dll\n"
1: (5135) ->1019^done
1: (5136) ->(gdb)
1: (5144) 1019: elapsed time 65
1: (5145) ->&"\n"
1: (5146) ->^done
1: (5147) ->(gdb)
1: (5154) Send Event AD7ModuleLoadEvent
Loaded 'C:\Windows\system32\kernel32.dll'. Symbols loaded.
1: (5158) Send Event AD7ModuleLoadEvent
Loaded 'C:\Windows\system32\KernelBase.dll'. Symbols loaded.
1: (5160) Send Event AD7ModuleLoadEvent
Loaded 'C:\Windows\system32\msvcrt.dll'. Symbols loaded.
1: (5161) Send Event AD7ModuleLoadEvent
Loaded 'E:\MIN\bin\libgcc_s_dw2-1.dll'. Symbols loaded.
1: (5164) Send Event AD7ModuleLoadEvent
Loaded 'E:\MIN\bin\libstdc++-6.dll'. Symbols loaded.
1: (5178) <-1020-break-delete 1
1: (5182) ->1020^done
1: (5183) ->(gdb)
1: (5183) 1020: elapsed time 5
1: (5187) Send Event AD7BreakpointEvent
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
1: (5197) ->&"\n"
1: (5200) ->^done
1: (5201) ->(gdb)
1: (5461) <-1021-stack-list-arguments 0 0 0
1: (5466) ->1021^done,stack-args=[frame={level="0",args=[]}]
1: (5467) ->(gdb)
1: (5467) 1021: elapsed time 6
1: (5471) ->&"\n"
1: (5487) ->^done
1: (5490) ->(gdb)
1: (5997) <-1022-stack-list-variables 0
1: (6007) ->1022^done,variables=[]
1: (6007) ->(gdb)
1: (6008) 1022: elapsed time 11
1: (6011) ->&"\n"
1: (6014) ->^done
1: (6014) ->(gdb)
`

and this is after the step


`1: (16045) <-1023-exec-next
1: (16060) ->1023^running
1: (16061) ->*running,thread-id="1"
1: (16061) ->(gdb)
1: (16063) 1023: elapsed time 18
1: (16072) ->*stopped,reason="end-stepping-range",frame={addr="0x00401440",func="main",args=[],file="str.cpp",fullname="c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp",line="12"},thread-id="1",stopped-threads="all"
1: (16075) <-1024-stack-list-frames 0 1000
1: (16078) ->(gdb)
1: (16080) ->&"\n"
1: (16081) ->^done
1: (16081) ->(gdb)
1: (16097) ->1024^done,stack=[frame={level="0",addr="0x00401440",func="main",file="str.cpp",fullname="c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp",line="12"}]
1: (16098) ->(gdb)
1: (16099) 1024: elapsed time 24
1: (16101) Send Event AD7StepCompleteEvent
1: (16125) ->&"\n"
1: (16127) ->^done
1: (16130) ->(gdb)
1: (16178) <-1025-stack-list-arguments 0 0 0
1: (16184) ->1025^done,stack-args=[frame={level="0",args=[]}]
1: (16185) ->(gdb)
1: (16185) 1025: elapsed time 7
1: (16193) ->&"\n"
1: (16194) ->^done
1: (16198) ->(gdb)
1: (16755) <-1026-stack-list-variables 0
1: (16764) ->1026^done,variables=[]
1: (16764) ->(gdb)
1: (16765) 1026: elapsed time 10
1: (16767) ->&"\n"
1: (16768) ->^done
1: (16771) ->(gdb)
`

I cleared the debug console before showing you the log after stepping as it adds these lines only after the first ones.

**Comment by minkir014** [comment]
What's the news?

**Comment by pieandcakes** [comment]
@minkir014 This seems like a `gdb` bug. According to the [documentation](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Program-Execution.html#GDB_002fMI-Program-Execution), we should be calling `-exec-next` to get to the next line which is what we do.

```
<-1023-exec-next 
1: (16060) ->1023^running 
1: (16061) ->*running,thread-id="1" 
1: (16061) ->(gdb) 
1: (16063) 1023: elapsed time 18 
1: (16072) ->*stopped,reason="end-stepping-range",frame={addr="0x00401440",func="main",args=[],file="str.cpp",fullname="c:\\Users\\MINKIR\\Desktop\\Calculator\\gii\\CPP\\str.cpp",line="12"},thread-id="1",stopped-threads="all"
```

The log shows that the next time `gdb` stops, its on line 12, which is what you are saying is wrong. From this, I can say we are doing the correct behavior but the version of `gdb` you are using is not behaving correctly.

**Comment by minkir014** [comment]
I am using gcc 8.2.0 with its gdb.

**Comment by pieandcakes** [comment]
According to your log you are using `gdb` version `7.6.1` YOu will probably want to file a bug with whichever toolset you got your `gdb` from.

**Comment by WardenGnaw** [comment]
Closing due to being an external issue with GDB 7.6.1.
