### ISSUE TITLE
Better Formatting for Allmanstyle

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-cpptools#365]
_From @equinoxr on November 22, 2016 15:33_

Im programming in the Allmanstyle.
if i press { i would be really faster if a new line would happen, then a tab in the new line and then a } -- but the cursor should stay in the middle of the braces (after the tab). Would be also cool to select text, and if i press { it gets formatted in the Allmanstyle... how could this be achieved??

greetz equinox

_Copied from original issue: Microsoft/vscode#15893_

**Comment by jrieken** [comment]
@equinoxr The brackets rules are language dependent so we first need to know for what language you want that

**Comment by jrieken** [comment]
_From @equinoxr on November 23, 2016 9:44_

oh sry ok im programming in C++! 

https://de.wikipedia.org/wiki/Einr%C3%BCckungsstil#Allman_.2F_BSD_.2F_.E2.80.9EEast_Coast.E2.80.9C

Here is a example how code looks when i code ;)

greetz & thx

equinoxr

**Comment by bobbrow** [comment]
VS Code should provide the functionality you describe if you set `"editor.autoClosingBrackets": true` in your settings.json file.  You should also be able to format selected regions of text by using the CTL+K, CTL+F key sequence (you can also create different keybindings if you don't like the default one).

**Comment by sean-mcmanus** [comment]
@bobbrow VS Code doesn't provide the functionality via `editor.autoClosingBrackets`. It just adds the end bracket but without the newline and tab. I think we'd have to implement it as part of our formatOnType.

**Comment by bobbrow** [comment]
It adds the newline and tab and moves the closing brace down an additional line when you press ENTER after typing the opening curly brace.  This is similar to the behavior I've seen in intelliJ and Android Studio.
