### ISSUE TITLE
Garbage value for a specific program on vscode just in my system

### ISSUE THREAD

**Issue by el3mentry** [microsoft/vscode-cpptools#3650]
-   OS and Version:Win10 1809
-   VS Code Version: March 2019 (version 1.33)
-   C/C++ Extension Version:0.23.1
-   GCC Compiler Version: 8.1.0

**So, I am getting a garbage value on one of the outputs when I run a program,**

## TO REPRODUCE

Here is the code: 
[**https://textuploader.com/1dkda**](https://textuploader.com/1dkda)
*[To find the perfect numbers within a entered range and print the numbers and the sum of the numbers.]*

Compiler finds and prints the perfect numbers but gives a garbage value for the 'SumTotal' output. 

This code works fine in online compilers or someone else's system but isn't working in mine.

What I have tried:
Reinstalling VS Code from scratch.
Removing Console Host WIndow files from Task Manager

**Here is the output terminal:**
(https://ibb.co/ZdbZt9H)

**_tasks.json_**
```
{
"version": "2.0.0",
"tasks": [
{
   "label": "compile C File",
   "type": "shell",
   "command": "gcc",
   "args": [
   "-g",
   "${file}",
   "-o",
   "${workspaceRoot}\\${fileBasename}.exe"
          ],
   "group": {
   "kind": "build",
   "isDefault": true
            }
},

  {
    "label": "Run C File",
    "type": "shell",
    "command": ".\\${fileBasename}.exe",
    "group": {
    "kind": "test",
    "isDefault": true
  }
},


  {
  "type": "shell",
  "label": "gcc.exe build active file",
  "command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",
  "args": [
  "-g",
  "${file}",
  "-o",
  "${fileDirname}\\${fileBasenameNoExtension}.exe"
         ],
  "options": {
  "cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
             }
  }
]
}
```

**Comment by WardenGnaw** [comment]
This is neither a language service or debugger issue. It will reproduce if you run it without VS Code. 

I would recommend debugging through your code to find out why `SumTotal` may be the value, you think it is.
