### ISSUE TITLE
Undeclared variables are not highlighted/underlined

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3653]
Issue Type: <b>Bug</b>

{
 //int a = 2;
 a = 5;
}

Expected: Any visual representation that a is undeclared.

Extension version: 0.23.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

**Comment by michelleangela** [comment]
Hi @nimodia, I was not able to reproduce the issue.

My repro steps were:

1. Open folder
2. Create cpp file
3. Add the repro code

To help determine whether this could be a configuration issue on IntelliSense settings or a bug on IntelliSense itself, could you send the following:

- Repro steps of how you opened or created the file. Did you open/create the file without opening a folder first?

- Copy of `c_cpp_properties.json` file. This file contains configuration settings for IntelliSense. Or any `C_Cpp.default.*` in your `settings.json` file. These are the default configuration settings for intelliSense if you do not have `c_cpp_properties.json` configured.

- The output from running the command `C/C++: Log Diagnostics`. Note that the Log Diagnostics command will get logs from the current active source file. So ensure that the source file with the issue is open before running the command.

**Comment by ghost** [comment]
I observed that issue is NOT reproducible when working with new files in new folder. However, with my project files, I see this issue. So this seems to be some configuration issue.
However, I could NOT share the c_cpp_properties.json due to some constraints.

It would be helpful if you could let me know the configurations that might cause this problem.

Thanks,
Mangesh Nimodia

**Comment by michelleangela** [comment]
Are there unresolved #includes on your project files, that is IntelliSense can't find included header files? If there are, then error squiggles will be disabled for the file with unresolved #includes.

By default, error squiggles are not shown if the setting `C_Cpp.errorSquiggles` is set to `EnabledIfIncludesResolve` and `C_Cpp.intelliSenseEngineFallback` is `Enabled`. Set `C_Cpp.errorSquiggles` to `Enabled` and `C_Cpp.intelliSenseEngineFallback` to `Disabled` to show error squiggles even if #include paths are not resolved. 

Here is an example where a source file has an unresolved #include and `C_Cpp.errorSquiggles` is set to `EnabledIfIncludesResolve` and error squiggles are not shown.

![image](https://user-images.githubusercontent.com/38734287/57884332-3a3c0300-77dd-11e9-9c95-40062ed02566.png)

You can also ensure IntelliSense can resolve the path to included headers by specifying the paths under the property `includePath` in `c_cpp_properties.json`. For more information about the configuring `includePath` go to https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md

**Comment by ghost** [comment]
Thanks for the reply. Yes some of my files have unresolved #includes. 
However, error squiggles are not shown even for the files that do not have any unresolved #includes.

I tried the modifying the settings you mentioned but still error squiggles are not shown. 

See below a screenshot of how it appears:
![VSIntellisenseError](https://user-images.githubusercontent.com/29398545/57904369-138ad480-7890-11e9-93d2-c4aacba7992a.png)

**Comment by michelleangela** [comment]
Can you enable debug logging by setting `C_Cpp.loggingLevel` to `Debug` and then select `C/C++` from the output window:
![image](https://user-images.githubusercontent.com/38734287/57959280-f407a200-78b7-11e9-9e0d-86494fea2b4f.png)

Can you compare the output of debug logging and the output of the command `C/C++: Log Diagnostics` for when the error squiggles work on a new folder and when it doesn't work on your project folder? If there are any errors or failures from the logs, can you share those?

Also, do you have IntelliSense cache enabled? If so, can you try disabling it by setting `C_Cpp.intelliSenseCacheSize` to 0 and see if that fixes the issue?

Can you share your values of these settings:
`C_Cpp.intelliSenseEngine`
`C_Cpp.errorSquiggles`
`C_Cpp.intelliSenseEngineFallback`

And are you setting these settings per User or Workspace?
![image](https://user-images.githubusercontent.com/38734287/57959576-557c4080-78b9-11e9-8763-478baec703cb.png)

**Comment by michelleangela** [comment]
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.
