### ISSUE TITLE
Debugger hangs on break if dbgsym packages are installed, SourceRequest

### ISSUE THREAD

**Issue by rpavlik** [microsoft/vscode-cpptools#3662]
Issue Type: <b>Bug</b>

I'm on Debian Testing/Buster. The project I was working on when hitting this bug was [SolveSpace](https://github.com/solvespace/solvespace) - will attach the launch config (I had it set to break on a glib warning, which one occurs when you go to exit the app). But I don't expect those specifics to matter too much.

Initially, I had function names for a number of stack frames, but they were greyed out (just like, e.g. raise.c from the c library is) and couldn't click them. I wanted to look a bit closer so I went to add the debug symbols - apparently they're in a separate apt repo now - so I added `deb http://debug.mirrors.debian.org/debian-debug/ testing-debug main` to my sources and installed `libgtk-3-0-dbgsym libglib2.0-0-dbgsym libglibmm-2.4-1v5-dbgsym` and tried the debug again.

Now, most of the greyed-out ones are no longer greyed (presumably because of the dbgsym packages). However, the debugger hangs (can't continue, view other stack frames, etc - can only hit "stop" and that doesn't actually close the app) as soon as it breaks in a place that is related to those symbol packages. It appears to be trying to load something and failing (it shows an error "Stopping due to fatal error: NotImplementedException: No handler implemented for request type 'SourceRequest'" in the debug console), but can't even view the stack frames I know I have source for.

Can't debug with extensions disabled, which is why I'm filing this here.

Here's the launch config I used for my SolveSpace build, it automatically triggers breakpoints on some warning messages in glib, which are getting triggered on exit.
[launch.zip](https://github.com/microsoft/vscode-cpptools/files/3192157/launch.zip)

This is what it looks  when misbehaving after installing the symbols:
![image](https://user-images.githubusercontent.com/61129/57939426-f950f680-788f-11e9-9e37-e0604fc060ee.png)

Note that most stack frames aren't greyed out, the "NotImplementedException" in the debug console, and the attempt to open a source file (from the libraries I installed dbgsym for) causing an activity-bar to keep scrolling.

Clicking stack frames does nothing but switch to another file it can't show me. The "Load more stack frames" button does nothing, as do attempting to expand the other threads' call tacks.

Here are two screen casts: one showing what happens when the dbgsym packages are installed (at the end, I show how the stop button didn't actually stop the debugged application), the other showing it working more correctly after I uninstalled them.
[debugger-screencasts.zip](https://github.com/microsoft/vscode-cpptools/files/3192186/debugger-screencasts.zip)

and here's the launch.json for this exact reproduction, though I suspect any library that is system-installed and has the ability to break on some condition might cause the same thing.
[launch.zip](https://github.com/microsoft/vscode-cpptools/files/3192193/launch.zip)

Extension version: 0.23.1
VS Code version: Code - Insiders 1.34.0-insider (daf71423252a707b8e396e8afa8102b717f8213b, 2019-05-07T05:14:45.885Z)
OS version: Linux x64 4.19.0-4-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 3684)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.62GB (0.57GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pieandcakes** [comment]
@rpavlik Thank you for reporting this. Does this happen quite consistently for you? if so, can you do me a favor and get me a `traceResponse` log for when it happens? To do that, you would want to add `"logging": {"traceResponse": true}` to your `launch.json` and restart debugging.

AFAIK we don't support SourceRequest (which is what the exception is) but I can't understand why VS Code is sending us the request in the first place. 

If you don't want to post it here but you are comfortable emailing it to me, my email address is in my profile.

**Comment by rpavlik** [comment]
Well, I'd never had it happen before but I never had those packages installed before. I kept them installed just long enough to record the data.

I re-installed those packages, added the traceResponse config to launch, and it was perfectly reproducible. I got this: (didn't see anything too sensitive - this is all open source code, and I just used solvespace master as of right now.)

[traceresponse.txt](https://github.com/microsoft/vscode-cpptools/files/3208996/traceresponse.txt)

**Comment by pieandcakes** [comment]
Thanks. That helps a lot. I'll see if we can make a fix to avoid stopping debugging.

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders (available by setting "C_Cpp.updateChannel" to "Insiders").

**Comment by Spongman** [comment]
where can i get this 0.24.0? i have this in my settings.json:

````json
{
    "C_Cpp.updateChannel": "Insiders"
}
```

but it doesn't offer me that version.

the debugger is completely broken for me with this bug.

**Comment by pieandcakes** [comment]
I get this exception when trying to click on a frame in the callstack while debugging an attached process.


> Stopping due to fatal error: NotImplementedException: No handler implemented for request type 'SourceRequest'!


> GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git

ms-vscode.cpptools v 0.23.1

````
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-24-generic
````

_Originally posted by @Spongman in https://github.com/microsoft/vscode-cpptools/issues/2922#issuecomment-505598489_

**Comment by pieandcakes** [comment]
@Spongman You can download the insiders from our [release page](https://github.com/microsoft/vscode-cpptools/releases)

**Comment by Spongman** [comment]
> @Spongman You can download the insiders from our [release page](https://github.com/microsoft/vscode-cpptools/releases)

maybe it's worth removing the incorrect/misleading comments above?

**Comment by pieandcakes** [comment]
@sean-mcmanus Why is @Spongman not able to update through the insiders channel?

**Comment by sean-mcmanus** [comment]
@pieandcakes I'm not sure. Some users have issues (most don't) -- we probably should add better error messages.

This should be fixed with 0.24.0.

**Comment by rpavlik** [comment]
Confirmed fixed, btw - looks like a small typo (message is "'SourceRequest' not supported.." with two periods) but definitely better than hanging :) thank you!

**Comment by pieandcakes** [comment]
@rpavlik Thanks for the info. I think that message comes from VS Code. I'll let them know.
