### ISSUE TITLE
Commenting out a symbol then trying to navigate to the function leads to "No definition found for... function_name"

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode-cpptools#3663]
Issue Type: <b>Bug</b>

I noticed when commeting out a function/variable (i.e., symbol) leads to "No definition found for... function_name".  Is that by design?  I would still like to search for a symbol even if it commented out

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.14393

**Comment by sean-mcmanus** [comment]
That is "by design". We do not parse definitions of symbols inside of comments.

One alternative if to surround the code in
```
#if 0
int goto_def_works_now;
#endif
```
...which will allow the Go to Def to work still.

**Comment by EmbeddedBacon** [comment]
Ah, that is an unfortunate user annoyance.  The #if/#endif is nice if I am blocking out a section of code, but if I have comments which reference the function/symbol, I much rather that the tools allow me to navigate to that symbol other than me having to revert to find in files.  Perhaps you might consider adding a flag to allow a user be able to find that symbol, even if in a comments section.

**Comment by sean-mcmanus** [comment]
Oh -- the "Find All References" in VS has an option to find "references" in comments, so we can use this issue to track that. Version 1 of "Find All References" won't have this ability though. And it's unlikely that Go to Def would.

Also, the VS has a fancy UI that allows users to decide if they want references/renames in comments to appear, so we'd have to figure out some design to accomplish that given VS Code's limited UI/APIs.

UPDATE: Rename and Find All References has the option available in VS. Also, for inactive regions and strings.

**Comment by EmbeddedBacon** [comment]
Thank you, @sean-mcmanus .  I think having this feature would be very very helpful.

**Comment by bobbrow** [comment]
This should work with Find All References now.
