### ISSUE TITLE
[Feature request] View only the breakpoints in the current file in the debugger tab

### ISSUE THREAD

**Issue by GaurangTandon** [microsoft/vscode-cpptools#3665]
Type: Debugger

- OS and Version: Ubuntu 18.04.2
- VS Code Version: 1.34.0
- C/C++ Extension Version: 0.23.1

**Launch.json**

        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }

**Feature request:**

When I open a folder (Ctrl K, Ctrl O), put some breakpoints in one file, then switch to another file and put breakpoints there, the breakpoints of both the files are visible in the Breakpoints tab of the Debugger.

I wish to have a toggle switch in settings due to which it would display only the breakpoints of the currently active file. Is it possible? Thanks!

**Comment by WardenGnaw** [comment]
The vscode cpptools extension does not control the UI for the breakpoints window, that would be the VS Code. Please file an issue on their [issues page](https://github.com/Microsoft/vscode/issues).
