### ISSUE TITLE
Should update the repo description

### ISSUE THREAD

**Issue by easyaspi314** [microsoft/vscode-cpptools#3667]
Currently, the repo's description is "Official repository for filing issues against and getting support for the Microsoft C/C++ extension for VS Code"

Unless I am mistaken, that is the old description from when this was a stub. 

Now that the C++ extension is open source and the repo is more than just for filing issues, we should just change it to "Official repository for the Microsoft C/C++ extension for VS Code"

**Comment by sean-mcmanus** [comment]
Sounds good to me -- I've updated the description. It already said "This is the official repository for the Microsoft C/C++ extension for VS Code" in the ReadMe.md.

Also, only the TypeScript/client side of the extension is open source (the server/C++ side is not).
