### ISSUE TITLE
C++ syntax highlighting error

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode-cpptools#3668]
Issue Type: <b>Bug</b>

https://github.com/microsoft/vscode/issues/73858

![捕获1](https://user-images.githubusercontent.com/20399194/57990600-cb132700-7ada-11e9-9f02-0011a5afce66.PNG)

![捕获2](https://user-images.githubusercontent.com/20399194/57990604-cfd7db00-7ada-11e9-9235-0bad425e813b.PNG)

```
#include <cstdio>

int main()
{
	char **sss = new char *[3];
	for (int i = 0; i < 3; ++i)
		sss[i] = new char[2];
	return 0;
}
```

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @mxdh ,

Could you clarify the issue here with the C++ extension?  Currently, colorization is coming only from vscode, so would not be the extension.  If you are referring to the squiggle on the new operator in your example, that would be coming from the extension, but looks to be correctly indicating a type incompatibility.

 - Colen

**Comment by matter123** [comment]
@mxdh This was fixed upstream at jeff-hykin/cpp-textmate-grammar in version 1.8.9, see jeff-hykin/cpp-textmate-grammar#128

The fix should make it to vscode the next time the grammars are updated. If you need the fix now, It has already been updated in insiders, or you can install marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax&ssr=false

**Comment by mxdh** [comment]
I mean C++ syntax coloring error.
Thank you very much.
