### ISSUE TITLE
Add /usr/local/include to c_cpp_properties.json's default list of include paths

### ISSUE THREAD

**Issue by waldyrious** [microsoft/vscode-cpptools#367]
Currently the "includePath" key in `c_cpp_properties.json` only contains the "/usr/include" path. IMO it would be a good default to also add "/usr/local/include" to it.

**Comment by bobbrow** [comment]
In the more recent versions of the extension, /usr/local/include is added to the includePath when a new c_cpp_properties.json file is created.  Thank you for the suggestion.
