### ISSUE TITLE
IntelliSense squiggles don't update after a header is renamed

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3670]
After a header is renamed that is used in a source, the IntelliSense squiggles don't update to reflect the change. In some cases, the even editing/save the file doesn't pick up the changes from the rename, i.e. the file in the `#include <>` no longer exists, but IntelliSense doesn't complain about it -- it seems like it's using some cached version of the non-existent file.

I hit this while doing the repro of https://github.com/microsoft/vscode-cpptools/issues/3378 and renaming headers_test.h.

So this might be 2 bugs:
1. The rename should auto-trigger an update squiggles without having to edit/save (i.e. non-existent file becomes existent).
2. The rename should clear the IntelliSense process cache of the file if the file doesn't exist any more.

**Comment by bobbrow** [comment]
We'll be looking at this as part of the code folding work.  Note this will address files located within the workspace. We don't get notifications for files outside the workspace.

**Comment by Colengms** [comment]
I've addressed the issue of the intelliSense process not being notified of files changed outside of the editor. (VS Codes informs us of a rename as a delete and a create, provided it's in the workspace).  It looks like we also need to trigger squiggle updates.

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
