### ISSUE TITLE
CTRL+SHIFT+B no longer gives the option to set up a build task when a cpp file is open

### ISSUE THREAD

**Issue by dunhor** [microsoft/vscode-cpptools#3674]
**Type: LanguageService**
When I do the key combo 'CTRL+SHIFT+B' on a new directory (not configured for any build task), it would previously prompt me to set up a new task. This was wonderful since I likely wanted to invoke cmake/ninja/etc. It is now, however, only presenting me the option to invoke cl.exe on the active file. While I can still go in and manually set up a new build task, it was very convenient to do everything the old way. This could also be an editor change unrelated to the extension, but it's still annoying nonetheless. FWIW if the active file is not a C++ file, then it presents me with the old experience, so I suppose at least I still have that

**Describe the bug**
- OS and Version: Windows Insiders (but hit this on 1803 machine at home)
- VS Code Version: 1.35.0-insider
- C/C++ Extension Version: 0.23.1

**Comment by sean-mcmanus** [comment]
Yeah, we recently changed it to add those default build tasks -- maybe we can add the "default" that was previously shown to the list as well, so the previous behavior is still obtainable.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders ,
