### ISSUE TITLE
"C_Cpp.clang_format_fallbackStyle": "Visual Studio" is a poor default

### ISSUE THREAD

**Issue by mbward** [microsoft/vscode-cpptools#3676]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux
- VS Code Version: 1.32.3
- C/C++ Extension Version: 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

1. Install both `vscode-cpptools` and `xaver.clang-format` extensions
2. Set the setting `"clang-format.style": "{BasedOnStyle: google}"`
3. Open a .cc file
4. Save

**Expected behavior**
It doesn't change the file formatting.

**Actual behavior**
The file changes formats twice. Usually if I save again, my intended format wins somehow.

Sometimes my strings over 80-columns get reformatted, not sure if it's due to this or something else.

**Additional context**
Presumably this only happens if you don't have a `.clang-format` file anywhere in the file tree. Having one is infeasible for me.

IMO it should only reformat things when explicitly configured to do so. Most users won't want the `Visual Studio` style.

**Comment by mbward** [comment]
The template guided me to set Type: LanguageService, but I'm not sure if that's correct. Please feel free to reassign as needed.

**Comment by sean-mcmanus** [comment]
The xaver.clang-format is another extensions. This sounds like a bug with that extension? Let us know if you repro the issue with that other one disabled.

**Comment by sean-mcmanus** [comment]
You can disable our extension's formatting via the C_Cpp.formatting setting.

**Comment by mbward** [comment]
Yes, but again, none of this should happen *by default*. I asked `xaver.clang-format` to reformat my code. I never asked the C/C++ extension to reformat my code.

**Comment by sean-mcmanus** [comment]
Did you use the "Format Document With..." command and then select the default formatting to be the other extension?

**Comment by mbward** [comment]
The only similar menu item I have is "Format Document" (Ctrl+Shift+I), but I don't explicitly use it.

I did enable `"editor.formatOnSave": true` long ago.

**Comment by sean-mcmanus** [comment]
They added the ability to configure the default formatter in 1.33 of VS Code: https://code.visualstudio.com/updates/v1_33#_default-formatter-selection .
