### ISSUE TITLE
The function not define or declare before using shall given an error.

### ISSUE THREAD

**Issue by JasonLeeCn** [microsoft/vscode-cpptools#3678]
Issue Type: <b>Feature Request</b>

eg.:

void funA()
{
}

void main(void)
{
    funA();
    funB(); //The funB is not exit in the project. But hear is no error given.
}

The C shall take it as "int funB()". But it will case link error.  And is can not run correct if the function is not exit ( not declare or define) also. So, please given an error for this case.

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Colengms** [comment]
This looks like the same issue as: https://github.com/microsoft/vscode-cpptools/issues/828 

Which compiler is your compilerPath set to?

CL issues a warning.  We currently show squiggles only for errors.  An issue tracking squiggles for warnings is: https://github.com/microsoft/vscode-cpptools/pull/2379

In gcc, you can enable a warning using -Wmissing-prototypes.  Or, make it an error using -Werror=missing-prototypes.  There are lots of command line arguments that can be passed to gcc to vary its behavior, and we do not handle all of them.

**Comment by JasonLeeCn** [comment]
I not set compilerPath. It stay default setting for "clang-x64". The macro not define it will show as error squiggles, but the function not define will take as int_void function and no error squiggles.
