### ISSUE TITLE
Show thread name and additional info

### ISSUE THREAD

**Issue by UR3IQO** [microsoft/vscode-cpptools#3684]
Type: Debugger
Feature request.

I use gdb to remote debug baremetal application running RTOS. VSCode shows threads correctly, but it does not show any additional information gdb provides.
Here is the output of the ```info thread``` command:
```
(gdb) i th
  Id   Target Id                                             Frame
* 1    Thread 10576 (Name: IDLE C0, State(0x80): Running C0) 0x000003f4 in entryIdle () at main.c:88
  2    Thread 10652 (Name: IDLE C1, State(0x80): Running C1) entryIdle2 () at main.c:93
  3    Thread 10728 (Name: No Name, State(0x82): WT All Ev)  0x00000438 in entryTaskA () at main.c:112
  4    Thread 10804 (Name: No Name, State(0x82): WT All Ev)  entryTaskB () at main.c:179
(gdb)
```
And here is VSCode window:
![Снимок экрана (1446)](https://user-images.githubusercontent.com/25171239/58313846-2b75d180-7e17-11e9-9cf6-117d0b28cd51.png)

**Comment by pieandcakes** [comment]
@sov1178 The [VS Code DebugAdapter Protocol (DAP)](https://github.com/microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L149) doesn't support this. 

They have a proposal that you can upvote [here](https://github.com/microsoft/vscode-debugadapter-node/issues/149)

**Comment by pieandcakes** [comment]
Until the DAP supports it there isn't anything we can do to display a name.

**Comment by Spongman** [comment]
i don't even see the thread Ids, just the process name, repeated 20 times.
