### ISSUE TITLE
Some time all typedef enum give re-declared error when delete --no warnings in file msvc.json

### ISSUE THREAD

**Issue by JasonLeeCn** [microsoft/vscode-cpptools#3685]
Issue Type: <b>Bug</b>

When delete "--no_warnings" line in file "msvc.json".
In some complex project (code files forlder) all typedef enum type given an error as follow:
"typedef name has already been declared (with similar type)"  in all hearder files. But some projects no this problem.  I checked the typedef enum, it just define one times.

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.66GB (4.10GB free)|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
It repros with .c files (possibly other projects are using C++).

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders (available by setting "C_Cpp.updateChannel" to "Insiders").
