### ISSUE TITLE
Add always show error squiggles count in explorer window files name right side.

### ISSUE THREAD

**Issue by JasonLeeCn** [microsoft/vscode-cpptools#3686]
Issue Type: <b>Feature Request</b>

Now, the error squiggles count show in file name of explorer need click the file one time. Request for a option to automatic show all files error sguiggles count. It will better and more benefit for fix errors.

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

**Comment by bobbrow** [comment]
We are currently unable to address this feature request since we are focusing on higher priority features and bugs right now.  We'll tag this for follow up in case it receives more interest from the community, but to keep our issue count manageable, we're closing this issue for now.
