### ISSUE TITLE
Can't indent Cpp files

### ISSUE THREAD

**Issue by kalpaj12** [microsoft/vscode-cpptools#3689]
**Type: LanguageService**

- OS and Version: Ubuntu 19.04
- VS Code Version: 1.34.0
- C/C++ Extension Version: 0.23.1

I'm not able to Format / Indent my C++ files.

**Steps to Reproduce**
Using `ctrl + shift + i` gives the following output:

`Formatting failed:
/home/kalpaj_ag/.vscode/extensions/ms-vscode.cpptools-0.23.1/bin/../LLVM/bin/clang-format -style=file -fallback-style=google -assume-filename=/home/kalpaj_ag/Desktop/CP/test.cpp
  /home/kalpaj_ag/.vscode/extensions/ms-vscode.cpptools-0.23.1/bin/../LLVM/bin/clang-format: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`

**Expected behavior**
To indent my files. They are soo out of place :)

**Screenshots**
![Screenshot from 2019-05-24 22-54-47](https://user-images.githubusercontent.com/41864755/58345866-04e78300-7e77-11e9-8f41-25cd70b36d71.png)

**Comment by bobbrow** [comment]
This sounds familiar.  Can you take a look at #3174 and see if that helps you?

**Comment by kalpaj12** [comment]
Thanks @bobbrow! I **guess** the issue is due to minimal installation of ubuntu during its set up. I have no issues on my desktop [selected full ubuntu installation] where as for my laptop [ selected minimal installation ], I seem to have a missing package. I guess this extension could first check if clang-format and other essential packages are installed or not, and if not, then proceed with a warning to install these required packages or do the same in the background.

**Comment by kalpaj12** [comment]
For now, I'll try #3174 and let you know if this works! Thanks though! Good day.

**Comment by kalpaj12** [comment]
[This](https://github.com/microsoft/vscode-cpptools/issues/3174#issuecomment-463944461) works!

**Comment by taringi** [comment]
yip, that fix works. We really need extension to check if dependencies are met

**Comment by michelleangela** [comment]
Closing as duplicate.
