### ISSUE TITLE
Symbols in files with alternate extensions

### ISSUE THREAD

**Issue by codejnki** [microsoft/vscode-cpptools#369]
I recently started using Visual Studio Code to edit Arduino sketches.  I've got an extension installed that will apply code syntax highlighting for the .ino extension and VS Code interprets these files as C++ files.

When I press <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>O</kbd> to look up symbols when the file has an extension of .ino no symbols are found.
![ardunioexample](https://cloud.githubusercontent.com/assets/700104/20603566/1e04d812-b230-11e6-943b-5aaccc80d65d.png)

If I change the file extension to either C or CPP symbol location works as expected.
![cexample](https://cloud.githubusercontent.com/assets/700104/20603628/66fda1e8-b230-11e6-91a5-70f68f8e48b3.png)

Any ideas on what might need to be changed so that symbols will work while the extension is .ino?

**Comment by pieandcakes** [comment]
@sridmad Would there be a way for @codejnki to add a file extension for the language service? I know how to do it for the debugger but that isn't what he is looking for.

**Comment by bobbrow** [comment]
This should be fixed in the latest version of the extension.  Please let us know if it is not.
