### ISSUE TITLE
Runn task.json with make command

### ISSUE THREAD

**Issue by BrunoXL** [microsoft/vscode-cpptools#3691]
I'm trying to configure `tasks.json` to run a `make` commad.

Tasks. json is as follows:
![image](https://user-images.githubusercontent.com/11648780/58354982-5d079080-7e49-11e9-94bb-4198666bc294.png)

On execute <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd> it gives me error:

> make: *** No targets specified and no makefile found. Stop.
> The terminal process terminated with exit code: 2

However, when I run from command line `make -j4` everything goes perfect.
It is not related to configure my project or any dependencies, once I can run from command line.
What could be wrong??

**Comment by bobbrow** [comment]
Can you try setting "options.cwd" to the location where your makefile resides (e.g. ${workspaceFolder}, perhaps)?  I think it's trying to run make in the `/usr/bin` folder.

**Comment by BrunoXL** [comment]
Ok @bobbrow that worked, but I didn't caught why set `options.cwd`?

**Comment by bobbrow** [comment]
I'm not sure I understand.  You may not need to set it at all if it defaults to ${workspaceFolder}.  Was that added automatically to your tasks.json?

**Comment by BrunoXL** [comment]
I do not remember set it anytime. It was added automatically for sure.

**Comment by bobbrow** [comment]
How did you generate the tasks.json?  Or, which template did you pick?

**Comment by BrunoXL** [comment]
I hit <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>P</kbd> and pick `Tasks: Configure Taks`.

**Comment by bobbrow** [comment]
And after that, which template did you pick?

**Comment by BrunoXL** [comment]
I do not remember which template was, but it was a default one.
