### ISSUE TITLE
2 squiggle updates get sent on file open

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3693]
It would be better to only send 1. They both appear to take about the same amount of time.

**Comment by bobbrow** [comment]
Is this still an issue?

**Comment by sean-mcmanus** [comment]
Yes, it still repros.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.19.2
