### ISSUE TITLE
IntelliSense Missing some symbol 

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/vscode-cpptools#3695]
Version:0.23.1
OS:Linux

1、__FUNCTION__ Macro  can not auto completion
2、
TcpServer.h
```
#ifndef TCPSERVER_H
#define TCPSERVER_H
#include <boost/asio.hpp>
class TcpServer
{
    public:
        TcpServer();
        virtual ~TcpServer();
};
#endif
```

TcpServer.cpp
```
#include "TcpServer.h"
```

when i type tcpserver in cpp, the auto completion missing TcpServer class

**Comment by michelleangela** [comment]
@xspeed1989 , I could not reproduce the issue. My repro steps are detailed below. Did your repro steps involve other or different steps? Do you have a c_cpp_properties.json file configured, if so can you provide a copy?


**Repro steps:**

1. Created new workspace folder.
2. Created TcpServer.h without `#include <boost/asio.hpp>` as I only wanted to test autocomplete for the class.

```
#ifndef TCPSERVER_H 
#define TCPSERVER_H 
class TcpServer 
{
    public: 
    TcpServer(); 
    virtual ~TcpServer(); 
}; 
#endif
```

3. Created TcpServer.cpp with the following and typed `tcp` for auto completion
```
#include "TcpServer.h"
```

Result:
![image](https://user-images.githubusercontent.com/38734287/58501371-1d86c000-8139-11e9-9053-83e110f12404.png)

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
