### ISSUE TITLE
Mismarked problems

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode-cpptools#3696]
Issue Type: <b>Bug</b>

MinGW-w64 8.1.0

1. 
<img width="960" alt="2019-05-26 (3)" src="https://user-images.githubusercontent.com/20399194/58380396-18dad400-7fa0-11e9-83a9-92f14f4a2490.png">

2.
<img width="960" alt="2019-05-26 (4)" src="https://user-images.githubusercontent.com/20399194/58380402-22643c00-7fa0-11e9-906e-89f860e00615.png">

<img width="960" alt="2019-05-26 (5)" src="https://user-images.githubusercontent.com/20399194/58380404-26905980-7fa0-11e9-8979-e2e7186a24d4.png">

3.
<img width="960" alt="2019-05-26 (6)" src="https://user-images.githubusercontent.com/20399194/58380647-1332bd80-7fa3-11e9-9ab6-e94a69ab1807.png">

4.
<img width="960" alt="2019-05-26 (7)" src="https://user-images.githubusercontent.com/20399194/58380648-18900800-7fa3-11e9-81af-68e3b459ef72.png">

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
@mxdh , can you clarify what is mismarked in the screenshots? Also, can you copy and paste the contents of your `c_cpp_properties.json`?

**Comment by mxdh** [comment]
As we all know, the header file in MinGW can be compiled correctly, but C/C++ marks many errors in it.

Such as bits/stl_vector.h

Who is wrong?

```
{
    "configurations": [
        {
            "name": "Win32",
            "compilerPath": "C:/Compiler/MinGW64/bin/g++.exe",
            "intelliSenseMode": "gcc-x64",
            "cppStandard": "c++98"
        }
    ],
    "version": 4
}
```

**Comment by mxdh** [comment]
@michelleangela As we all know, the header files in MinGW can be compiled correctly, but C/C++ marks many errors in it.

Such as bits/stl_vector.h

Who is wrong?

```
{
    "configurations": [
        {
            "name": "Win32",
            "compilerPath": "C:/Compiler/MinGW64/bin/g++.exe",
            "intelliSenseMode": "gcc-x64",
            "cppStandard": "c++98"
        }
    ],
    "version": 4
}
```

**Comment by michelleangela** [comment]
Your c_cpp_properties.json looks correct. The MingGW system include paths should have been obtained for the IntelliSense because the `compilerPath` is set.

Can you run the command `C/C++: Log Diagnostics` while one of the header files with the IntelliSense errors is opened and copy and paste the output? Do the errors only show up on system header files?

**Comment by mxdh** [comment]
Sorry to bother you.
This problem has now disappeared, maybe the C/C++ extension crashed at the time.
