### ISSUE TITLE
Closing nested parenthesis

### ISSUE THREAD

**Issue by adrwor** [microsoft/vscode-cpptools#3699]
Issue Type: <b>Bug</b>

The following describes the steps and issue:

1. Open parenthesis, closing parenthesis automatically: "()"
2. insert something between these parenthesis: "(something)"
3. add an opening parenthesis inside: "((something)"
4. now when typing ")" after "something" but before the closing parenthesis, it won't show, the cursor just shifts to the right: "((something)"

Maybe this isn't a bug, but it is bugging me :-)

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
This sounds like a feature request for VS Code and not specific just to C++ extension. Please re-file issue at https://github.com/microsoft/vscode/issues
