### ISSUE TITLE
Add support of preprocessor definitions to c_cpp_properties.json

### ISSUE THREAD

**Issue by nikitozz** [microsoft/vscode-cpptools#37]
The extension should allow adding custom preprocessor definitions to _c_cpp_properties.json_. This would allow achieving the same results as with C++ **_/D_** compiler flag (https://msdn.microsoft.com/en-us/library/hhzbb5c8.aspx).

**Comment by sridmad** [comment]
The defines are not required for the browsing experience. Other features like full intellisense will require information about defines and we will add a mechanism when we add a features that requires it.
