### ISSUE TITLE
Linting seems to have issues with typedefs and structs

### ISSUE THREAD

**Issue by dirthsj** [microsoft/vscode-cpptools#3700]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Manjaro Stable, patch [2019-05-26](https://forum.manjaro.org/t/stable-update-2019-05-26-kernels-xfce-4-14-pre1-virtualbox-libreoffice/88908)
- VS Code Version: Code - OSS v 1.34.0-2 (installed via Manjaro repo)
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them): cpplint, GitLens (no)
- A clear and concise description of what the bug is.

The extension produces a large quantity of nonsensical error messages when a datastructure is declared as follows:

```
typedef struct Example {
    struct Example* next;
    struct Example* previous;
} Example;
```

The error messages will be things like:
`a value of type "Example *" cannot be assigned to an entity of type "Example *"`
(reassigning a pointer)
`operand types are incompatible ("Example *" and "Example *")`
(comparing two pointers to see if they are the same)
`a value of type "Example *" cannot be used to initialize an entity of type "Example *"`
(when creating a local pointer to an existing object)
`return value type does not match the function type`
(returning an `Example *` from a function which is correctly returning `Example *`

**To Reproduce**

1. Write any C++ class with a struct declared in this way
2. Use the struct in any of the above ways
3. Observe loads of error messages

**Expected behavior**

I expect the same behavior as if the struct were declared like this:

```
typedef struct Ex {
    struct Ex* next;
    struct Ex* previous;
} Example;
```

...which solves all of the parsing issues.

**Screenshots**

N/A
**Additional context**

N/A

**Comment by sean-mcmanus** [comment]
I'm not able to repro this. Can you give more info, such as a specific usage of Example? If you could run the C/C++: Log Diagnostics command and provide some info there it might help as well.

**Comment by dirthsj** [comment]
Well dang, I'm trying to reproduce this so hard with the files I originally discovered it on and it just won't do it anymore.

It was definitely doing this though.

The file I had this on was essentially two linked lists with identical items but in different orders, so all the standard linked list operations apply.

```
head = newExample
```
```
ExampleClass::Example*  ExampleClass::RemoveHead() {
   Example* temp = head;
   ...
   return temp;
}
```
etc.

I'll keep trying to find a solid reproduction case.

Here's the Log Diagnostics:
```
-------- Diagnostics - 5/28/2019, 10:34:28 PM
Version: 0.23.1
Translation Unit Mappings:
[/home/steven/CSM/software/SensorModule/MedianFilter.cpp]:
    /home/steven/CSM/software/SensorModule/MedianFilter.cpp
    /home/steven/CSM/software/SensorModule/MedianFilter.hpp
Translation Unit Configurations:
[/home/steven/CSM/software/SensorModule/MedianFilter.cpp]:
    Process ID: 7032
    Memory Usage: 83 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/8.3.0
        /usr/include/c++/8.3.0/x86_64-pc-linux-gnu
        /usr/include/c++/8.3.0/backward
        /usr/local/include
        /usr/lib/clang/8.0.0/include
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=80000
Total Memory Usage: 83 MB
```

If you would like to view the files I originally had this issue on, I can put that up here too, but it does rely on a pretty large list of files for dependencies which I would not be posting.  The actual value it gets from them is minimal and I could post that.

Potentially relevant is one member of the struct is a union between int16, uint16, float, and byte[4].

**Comment by camilojm27** [comment]
![image](https://user-images.githubusercontent.com/14319090/59544784-e0f9e900-8eda-11e9-8a14-aa9909a93c60.png)
I have the same issue, the linting does not work after the last update

**Comment by sean-mcmanus** [comment]
@camilojm27 Where in your screenshot do you expect a squiggle?

Can you provide more repro info?

You may also want to try 0.24.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.24.0-insiders

**Comment by camilojm27** [comment]
![image](https://user-images.githubusercontent.com/14319090/59544916-8bbed700-8edc-11e9-96c9-712187b63c22.png)

@sean-mcmanus i have the insiders one and this is what the code should look like

**Comment by sean-mcmanus** [comment]
The Insiders build added it's own IntelliSense-based semantic colorization. It sounds like you're experiencing a bug with that? You can disable it by changing C_Cpp.enhancedColorization. If you can give more details about what Color Theme you are using we could investigate a repro.

**Comment by bobbrow** [comment]
I repro with the Tomorrow Night Blue theme built in to VS Code.  It looks like we broke some themes.  This should move to a new issue though.

**Comment by bobbrow** [comment]
I created #3779 and #3780

**Comment by sean-mcmanus** [comment]
@camilojm27 The selection bug is fixed with 0.24.0-insiders2. Set the "C_Cpp.updateChannel" setting to "Insiders" to auto-install it.

**Comment by camilojm27** [comment]
@sean-mcmanus Thanks for everything, work perfectly, i love vscode team <3

**Comment by Zylann** [comment]
I'm having similar issues with structs declared within a class, same errors `a value of type "Example *" cannot be assigned to an entity of type "Example *"`, I searched for the error message on Github but only that issue came up as relevant.

Had stuff like:
![image](https://user-images.githubusercontent.com/1311555/63047019-73167180-becb-11e9-8662-60ad97b5f319.png)

However I closed VSCode and reopened the same file later, they didn't appear again.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
