### ISSUE TITLE
Error Highlighting

### ISSUE THREAD

**Issue by MB1151** [microsoft/vscode-cpptools#3701]
Issue Type: <b>Bug</b>

The errors in my C++ code are not getting highlighted(underlined) with red lines although i installed the C/C++ extension.  I didn't check with other languages.

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.58GB free)|
|Process Argv|Sample.cpp|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Do you have missing include files? What is your intelliSenseEngine, intelliSenseEngineFallback, and errorSquiggles settings? -- those settings could cause squiggles to not appear.

**Comment by enricoboschi** [comment]
I don't know if it helps, but I had the same issue on Manjaro x64 18.0.4 and fixed it simply opening the folder containing the file with VSCode.

**Comment by sean-mcmanus** [comment]
@enricoboschi Yeah, that's good advice. We intentionally disable error squiggles in the Open File scenario.

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
