### ISSUE TITLE
Cannot open source file "CppUnitTest.h"

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode-cpptools#3702]
Hi,

I'm working on a simple project where all the include files are in the workspace folder. I did not define a c_cpp_properties.json file because everything is working correctly except for 1 (system?) include file: 'CppUnitTest.h' which is available in:
`"C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Auxiliary/VS/UnitTest/include"` .

In this article it is specified that it is not necessary to add system include paths https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md#includepath

My question is: why is `"C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Auxiliary/VS/UnitTest/include"` not considered a system path?
I would rather not have to define the c_cpp_properties.json file for each small project and in all of them I use the CppUnitTest.h header.

Thanks

**Comment by sean-mcmanus** [comment]
That path is not considered a system include path because our code doesn't auto-add those include paths in the Auxiliary directory. You should be able to work around this via setting the C_Cpp.defaults.systemIncludePath (or C_Cpp.defaults.includePath) to those defaults you want. Is that workaround sufficient?

**Comment by bobbrow** [comment]
Don't use `C_Cpp.default.systemIncludePath` unless you intend to override the entire system include path.

Use
```
"C_Cpp.defaults.includePath": [
    "${workspaceFolder}/**",
    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Auxiliary/VS/UnitTest/include"
]
```

**Comment by psclkhoury** [comment]
okay thanks! That should work perfectly!
