### ISSUE TITLE
char8_t literals not correctly highlighted

### ISSUE THREAD

**Issue by cjdb** [microsoft/vscode-cpptools#3703]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.34
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

C++17 introduced a new character literal type, `u8'x'`. At present, this messes with the syntax highlighting, as shown in the attached screenshot. Note that this doesn't seem to be a problem for UTF-8 string literals.

**To Reproduce**
See screenshot.

**Expected behavior**
Should look similar to
```cpp
return static_cast<int>('1' + '1' - '\\' + '1');
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8622748/58435702-acec8e80-80b9-11e9-8895-a0f5b2496540.png)

**Additional context**
* See [C++17 literals][literals].

[literals]: https://timsong-cpp.github.io/cppwp/n4659/lex.ccon

**Comment by sean-mcmanus** [comment]
Our extension doesn't implement the colorization currently (it's implemented via VS Code itself using the textmate grammar linked below), but in our development branch that does implement colorization it has your example fixed. You could also file a bug with the extension https://github.com/jeff-hykin/cpp-textmate-grammar/issues and download install that extension after it fixes the issue.

**Comment by jeff-hykin** [comment]
@cjdb Fixed! just install `Better Syntax` v1.11.3

**Comment by cjdb** [comment]
@sean-mcmanus I previously [filed an issue][issue] with vscode for a different colourisation problem, and they deemed it an extension problem (despite the issue being replicated without any extensions enabled), and was directed here by @tyriar. I'd appreciate direction on where to submit future bug reports, or help understanding why the initial issue should have been directed here, and this issue elsewhere.

@jeff-hykin Thanks! Everything looks great now 👍 

[issue]: https://github.com/microsoft/vscode/issues/40847

**Comment by jeff-hykin** [comment]
This issue was "an extension problem" since the Better Syntax extension is the upstream source for the VS Code built-in C++ syntax. It's just an extension so that the latest changes can get pushed out and tested without waiting for a full VS Code release.

If it's a code-color issue with C, C++, Objective-C or Objective-C++, post it on jeff-hykin/cpp-textmate-grammar. It is almost always a syntax issue or a theme issue.

**Comment by cjdb** [comment]
> If it's a code-color issue with C, C++, Objective-C or Objective-C++, post it on jeff-hykin/cpp-textmate-grammar. It is almost always a syntax issue or a theme issue.

Thanks for clarifying! I think the issue can be closed now.
