### ISSUE TITLE
Static construction of a non-copyable object shows errors

### ISSUE THREAD

**Issue by pparuzel** [microsoft/vscode-cpptools#3704]
**Type: LanguageService**

**Describe the bug**
- OS and Version: **MacOS 10.14.5**
- VS Code Version: **1.34.0**
- C/C++ Extension Version: **0.23.1**
- Other extensions installed (and if the issue persists after disabling them): **N/A**

Although, the "cppStandard" is set to "c++17" an error is inconsistently shown when defining a **static** object by auto + explicit constructor.

**To Reproduce**
1. Set "cppStandard" to "c++17" in `c_cpp_properties.json`
2. Create a simple singleton or a default-constructible, non-copyable class
3. Try instantiating an object of this class using auto + explicit constructor

Example:
```cpp
class Widget {
    Widget() = default;
public:
    Widget(const Widget&) = delete;
    // ...
    Widget& instance() {
        // All three mean/do the same and compile
        static auto w1 = Widget();  // shows error squiggles
        static Widget w2{};  // doesn't
        static Widget w3 = {};  // doesn't
        // ... also ...
        auto w4 = Widget();  // doesn't show squiggles either
    }
    // ...
};
```

**Expected behavior**

No error should be displayed since C++17 handles such cases with unmaterialized prvalues thus avoiding copy constructor on the temporary (copy elision). The error should be displayed only below C++17 standard.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I have filed a bug on Visual Studio 2019 at https://developercommunity.visualstudio.com/content/problem/588115/c-intellisense-shows-invalid-errors-with-static-co.html . If you have a Microsoft account, you can login to upvote that issue.

**Comment by sean-mcmanus** [comment]
They said it's a duplicate of https://developercommunity.visualstudio.com/content/problem/495584/c17-copy-elision-not-respected-by-intellisense.html -- if that gets fixed I'll double check that this issue is fixed as well.

**Comment by pparuzel** [comment]
Awesome, thank you!

**Comment by Colengms** [comment]
The tracked issue has been fixed, and I'm no longer able to repro this in recent builds of the C/C++ Extension.  Closing as fixed.
