### ISSUE TITLE
Linux GCC reference issue

### ISSUE THREAD

**Issue by w136111526** [microsoft/vscode-cpptools#3705]
Hello, my development environment is Linux gcc. I have written a flyeg C++ test program. I want to compile it through task.json. There is an unresolvable symbol. How do I reference the. so file it depends on? My parameters are set to:
task.json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "g++",
            "args": [
                "src/*.cpp",
                "-o",
                "${workspaceFolder}/ffmpeg_test.out",
                "-g",
                "-std=c++11"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
}

**Comment by WardenGnaw** [comment]
Questions like this is part of the compiler toolset, not part of the cpptools extension.

From https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html, you will need to link the library that you are using.

```
-llibrary
-l library
Search the library named library when linking. (The second alternative with the library as a separate argument is only for POSIX compliance and is not recommended.) 
The -l option is passed directly to the linker by GCC. Refer to your linker documentation for exact details. The general description below applies to the GNU linker. 
The linker searches a standard list of directories for the library. The directories searched include several standard system directories plus any that you specify with -L. 
Static libraries are archives of object files, and have file names like liblibrary.a. Some targets also support shared libraries, which typically have names like liblibrary.so. If both static and shared libraries are found, the linker gives preference to linking with the shared library unless the -static option is used. 
It makes a difference where in the command you write this option; the linker searches and processes libraries and object files in the order they are specified. Thus, ‘foo.o -lz bar.o’ searches library ‘z’ after file foo.o but before bar.o. If bar.o refers to functions in ‘z’, those functions may not be loaded. 
```

**Comment by w136111526** [comment]
That is to say, when I write task.json's args argument, I can write it like this, for example: 
"args":
[
"SRC / *. Cpp ",
"-O",
"${workspace Folder} / FFmpeg _ test. out",
"-I",
"usr/local/include/avffmpeg",
"-l",
"avffmepg.so, dlib.so",
"-g",
"-STD = C + + 11"],
 is this correct? And if I want to make it like makefile, how do I write a macro definition?

**Comment by sean-mcmanus** [comment]
It's correct if the compiler doesn't give errors. I think you can set macros using -D. I don't know what you mean by "make it like makefile".

**Comment by w136111526** [comment]
@sean-mcmanus  
Hello, I 've added the command to the linked SDL dynamic library using the task.json file build C++ project.
Still reporting errors / usr/bin / LD: cannot find-l / USR / local/lib / libSDL2. so
My code is as follows,How can I change it?:
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "g++",
            "args": [
                "src/*.cpp",
                "-o",
                "${workspaceFolder}/ffmpeg_test.out",
                "-L",
                "/usr/local/lib/",
                "-l",
                "libSDL2.so",
                "-g",
                "-std=c++11"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

**Comment by sean-mcmanus** [comment]
Does that file exist at /usr/local/lib/libSDL2.so?

**Comment by w136111526** [comment]
@sean-mcmanus Thank you. I 've solved the problem. The parameters are misspelled.
