### ISSUE TITLE
[enum class|struct] symbol has trouble being detected

### ISSUE THREAD

**Issue by Clovel** [microsoft/vscode-cpptools#3706]
**Type: LanguageService**

When creating an `enum class`, the symbol is not recognized correctly, but the code compiles and runs fine. 

**Describe the bug**
- OS and Version: Win10 + WSL Ubuntu 18.04.02 LTS
- VS Code Version: 1.34.0
- C/C++ Extension: 0.23.1

**To Reproduce**

1. Create a Enum.hpp with a `enum class Direction` declaration with `NONE`, `RIGHT` & `LEFT` entries inside a namespace of your choice (`namespace tools` for example). 
2. Create code in the same namespace that uses this enum as a variable : `Direction lDirection =  Direction::NONE;`
3. Wait for IntelliSense to parse the source code. 

**Expected behavior**

The symbol should be correctly recognized, but in my case, error squiggles appear saying : 
> identifier "Direction" is undefined

**Comment by Colengms** [comment]
Hi @Clovel,

I'm not able to repro this.  In a new folder, I created tmp.h, and tmp.cpp.  In tmp.h I have:
```
namespace tools
{
    enum class Direction 
    {
        NONE, RIGHT, LEFT
    };
}
```

In tmp.cpp, I have:
```
namespace tools
{
    Direction lDirection = Direction::NONE;
}
```

... No squiggles are shown.  Do you see anything different in my example from your repro?

**Comment by Clovel** [comment]
Hi. 

The few differences I can think of : 
* Very large project, maybe Intellisense is having issues with that. 
* The squiggles appear in a `.cpp` file that implements a class that is in the same namespace as the Enum. The variable is declared in a member function of said class. 

Thanks for the help. 
Clovel

**Comment by Colengms** [comment]
Hi @Clovel,

So far, I'm not able to repro the issue.  I suspect there are other factors.  Could you perhaps create a standalone repo that demonstrates the issue, that we could pull to investigate?  That would take out a lot of the guesswork.

Thanks,
Colen

**Comment by Clovel** [comment]
Ok, I don't really have the time right here, but I will try to make you a simple example as soon as possible. Will report here. 

Clovel

**Comment by Colengms** [comment]
Hi @Clovel .  Since there hasn't been activity on this issue in 3 month, I'm going to close it.  Feel free to open another if you can isolate a repro.
