### ISSUE TITLE
High CPU due to parse_file

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3709]
Hiya,

<img width="882" alt="Screenshot 2019-05-24 at 16 08 29" src="https://user-images.githubusercontent.com/4742697/58360601-8cfd6680-7e3e-11e9-9a57-4238c181b12f.png">

Once again seeing high cpu usage recently, must have been the May update. 70% -> 30% battery in about 20 minutes!

Sample of process attached.
[sample-process.txt](https://github.com/microsoft/vscode-cpptools/files/3218833/sample-process.txt)

_Originally posted by @jamesadevine in https://github.com/microsoft/vscode-cpptools/issues/1816#issuecomment-495811437_

**Comment by sean-mcmanus** [comment]
@jamesadevine Hmm...that is the 1st report we've seen of any sort of performance regression like this with our latest update, which doesn't really change any of that code in the sample-process.txt. It looks as if your database might have gotten invalided for some reason and it's re-parsing files. One thing to double check is that your database isn't getting clobbered via having multiple different projects pointing to the same file or opening the same folder in different VS Code instances -- in your screenshot I see 3 extension processes -- are you using 3 workspace folders?

If you wait for the data base parsing to finish and then re-open the workspace is everything back to normal? If you set your C_Cpp.loggingLevel to Debug you can check if we output a database invalidation message for some reason.

I think we need more repro info.

**Comment by jamesadevine** [comment]
Hi @sean-mcmanus,

Yes I almost definitely had more than one VS code instance pointing to the same folder tree. As a user (with no understanding of the implementation) I wouldn't expect multiple processes to invalidate the database. I work on https://github.com/Microsoft/pxt/ and my workflow is usually:

1 x workspace containing all the files with folders containing CPP files.
1 x workspace containing project files with folders containing CPP files.
1 x workspace containing just the CPP files.

It looks a little like this:

```
Root (workspace)
    typscript files
    projects (workspace)
        more typescript
        CPP source files (workspace)
            libraries
                CPP...
            project files
```

**Comment by sean-mcmanus** [comment]
What is your databaseFilename setting? The default/unchanged? If you're using 3 different workspace folders in the graph shown it should be creating 3 different browse.vc.db files for each workspace in your workspaceStorage location. If you don't need the C/C++ symbols in some workspaces you can add the C/C++ folders to your files.exclude setting for that particular workspace to avoid parsing the C/C++ files.

**Comment by jamesadevine** [comment]
My databaseFilename setting is either not specified or set to ${default}! :smile:

**Comment by sean-mcmanus** [comment]
In your scenario, we have a bug in which multiple workspace folders that have the same leaf name get mapped to the same database file -- are you hitting that scenario? I have a fix for that at https://github.com/microsoft/vscode-cpptools/pull/3715 .

i.e. can you examine your `${AppData}/Roaming/Code/User/workspaceStorage/<GUID>/ms-vscode.cpptools` folder to see what buggy behavior is occurring with the .browse.vc.db file under those locations?

Without more info, I can't tell if you're experiencing a bug or not.

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
