### ISSUE TITLE
integrate DebuggerTerminal?

### ISSUE THREAD

**Issue by rorywalsh** [microsoft/vscode-cpptools#371]
Right now all my logging messages appear in the external DebuggerTerminal window that launches when I start debugging. Is there any way to either redirect this to the integrated debug console, or simply integrate the DebuggerTerminal into VSCode?

**Comment by cppcrusader** [comment]
Yes please add this feature. I came across the console property but it apparently isn't supported in the cpptools. I really need the console output of my program to feed into an integrated console for multiple reasons. One being a cleaner workspace and ease of use. The biggest need for it is to be able to review the output if the program crashes unexpectedly. The DebuggerTerminal closes when the program does so I lose all my logs.

**Comment by loganintech** [comment]
Any update on this feature? I too would appreciate it.

**Comment by alanlivio** [comment]
Any update on this feature?

**Comment by PhoenixStarEclipse** [comment]
Any update on this feature? The default xterm is too weak.

**Comment by Aeonos** [comment]
Same issue here. I need the output of the program, but the terminal closes after the program exits.

**Comment by WardenGnaw** [comment]
https://github.com/Microsoft/MIEngine/pull/757 implements Integrated Terminal
