### ISSUE TITLE
include file not found dilemma

### ISSUE THREAD

**Issue by francescoandreussi** [microsoft/vscode-cpptools#3710]
Hi, I extensively read about similar issues before opening this one, but I tried almost everything and I am still at square one.
I paste down here my VSCode window with my includes (not highlighted), the error in the terminal tab and my IncludePath option.

Thank you in advance.

![fnfClangVSCode1](https://user-images.githubusercontent.com/18213477/58570328-15fa1080-8238-11e9-8673-0ee9514fcd17.png)
![fnfClangVSCode2](https://user-images.githubusercontent.com/18213477/58570354-21e5d280-8238-11e9-8808-b6f1723107ed.png)

**Comment by sean-mcmanus** [comment]
The error you are getting is from your compiler and not our C/C++ extension. Your compiler or build system doesn't read the includePath from c_cpp_properties.json. You need to add the include paths to your command line somehow, e.g. -I "path".
