### ISSUE TITLE
compile_commands.json -idirafter flags in Clang are not detected as include files

### ISSUE THREAD

**Issue by gbbosak** [microsoft/vscode-cpptools#3713]
**Type: LanguageService**

Including a path with -idirafter in a compile_commands.json results in the parser not detecting it as an include path. More information on -idirafter can be found here: https://clang.llvm.org/docs/genindex.html

Additional flags that do the same thing are: --include-directory-after <arg>, --include-directory-after=<arg>

These flags are supported in both Clang and GCC.

**Describe the bug**
- OS and Version: Linux (Debian)
- VS Code Version:1.34.0
- C/C++ Extension Version: 0.23.1

**Comment by gbbosak** [comment]
Any updates on this?

**Comment by sean-mcmanus** [comment]
We're currently working on higher priority features. We don't have this fix scheduled yet.

**Comment by gbbosak** [comment]
Thanks for the update!

**Comment by vardhan** [comment]
> We're currently working on higher priority features. We don't have this fix scheduled yet.

I'm happy work on a patch if someone can point me where to look.

**Comment by sean-mcmanus** [comment]
@vardhan It's in our closed source code, but we might be able to fix it.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders

**Comment by gbbosak** [comment]
Fix verified! Thanks!
