### ISSUE TITLE
C/C++.log for writing: Operation timed out

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode-cpptools#3717]
Type: General

When running `npm test` there are strange errors caused by the C/C++ extension.

**Describe the bug**
- OS and Version: macOS 10.14.5 (18F132)
- VS Code Version: 1.34.0
- C/C++ Extension Version: 0.23.1

**To Reproduce**
1. Run `yo code` with default options
2. Run `npm test`

**Expected behavior**
The C/C++ extension not to log anything. After the test output the following appears:
`Error: Failed opening file [path]/output_logging_20190531T195912/5-C/C++.log for writing: Operation timed out`.

Disabling the extension does not prevent the error, the extension must be uninstalled.

**Comment by sean-mcmanus** [comment]
This is bug https://github.com/microsoft/vscode/issues/73441 -- fixed with the latest VS Code Insiders.

**Comment by sean-mcmanus** [comment]
But that error shouldn't repro if the C/C++ extension is disabled (it seems like the disabling might not be working for you?).

**Comment by dnicolson** [comment]
It looked unique as the filename and error message is different.

**Comment by sean-mcmanus** [comment]
The log in https://github.com/microsoft/vscode/issues/73441 has "Diagnostics" at the end because it's from the C/C++: Log Diagnostics command, but the same root issue occurs for the normal C/C++ output window (log).

**Comment by sean-mcmanus** [comment]
The other error message differences might be due to the OS being used (my error is from Windows).

Let us (or the VS Code team) know if the bug still repros with Insiders...it could be another spot in VS Code hitting the same issue with parsing "C/C++" incorrectly.
