### ISSUE TITLE
Notice: terminal.integrated.shell.* can be null in the upcoming v1.35

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-cpptools#3718]
See https://github.com/microsoft/vscode-python/issues/5743 and https://github.com/microsoft/vscode/issues/74233, you may also be affected by this. If you detect the shell based on the `terminal.integrated.shell.*` setting you can no longer do this unless the user has specified a shell.

**Comment by sean-mcmanus** [comment]
I don't see that setting in our code.

@WardenGnaw @pieandcakes Are you guys checking this setting somewhere else or can I close this issue?

**Comment by pieandcakes** [comment]
We don't use it specifically as we tell VS Code to run stuff in the terminal through the DA's `RunInTerminal` command. @Tyriar are you suggesting that we need to check that value now or do i need to ask VS Code for clarification?

**Comment by Tyriar** [comment]
Only if you were reading that setting and using the value, assuming it would always be `string` do you need to do anything (as it is now a `string | null`).

**Comment by pieandcakes** [comment]
@Tyriar Thanks for clarifying it. We currently don't do anything with that value so I'll close this. Thank you for the heads up regarding the change.

**Comment by Gongyihang** [comment]
"code-runner.executorMap": {
        "c": "cd $dir && clang '$fileName' -o '$fileNameWithoutExt.exe' -Wall -g -Og -static-libgcc --target=x86_64-w64-mingw -std=c11 && & '$dir$fileNameWithoutExt'",
        "cpp": "cd $dir && clang++ '$fileName' -o '$fileNameWithoutExt.exe' -Wall -g -Og -static-libgcc --target=x86_64-w64-mingw -std=c++17 && & '$dir$fileNameWithoutExt'"
},

and after I use ‘;’ to replace '&&'，It reported another mistake.

    "code-runner.executorMap": {
        "c": "cd $dir ; clang '$fileName' -o '$fileNameWithoutExt.exe' -Wall -g -Og -static-libgcc --target=x86_64-w64-mingw -std=c11 ; & '$dir$fileNameWithoutExt'",
        "cpp": "cd $dir ; clang++ '$fileName' -o '$fileNameWithoutExt.exe' -Wall -g -Og -static-libgcc --target=x86_64-w64-mingw -std=c++17 ; & '$dir$fileNameWithoutExt'"
},

&:""d:\vsc\\.vscode\\"hello" item cannot be recognized as  cmdlet, function, script file or runnable program. Please check the spelling of the name. If the path is included, make sure the path is correct and try again.
Location line: 1 character: 128

**Comment by pieandcakes** [comment]
@Gongyihang I don't know what you posted and why that is here in this post? you need to provide more information. Your comment has nothing to do with this issue.
