### ISSUE TITLE
OverflowError: in method 'SBInstructionList_GetInstructionAtIndex'

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-cpptools#372]
_From @PerMildner on November 24, 2016 10:24_

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|
|vscode-lldb|vadimcn|0.3.1|
|debug|webfreak|0.12.3|

---

Steps to Reproduce:

1. On OS X, launched a C program using "type":"lldb", tried to step or some such (just getting started with vscode). Suddenly debugee hung and vscode "Continue" button does nothing. Debug Console showed the following error message:

[11:13:32 debugsession] Internal debugger error:
Traceback (most recent call last):
  File "./adapter/debugsession.py", line 695, in handle_message
    result = handler(args)
  File "./adapter/debugsession.py", line 407, in DEBUG_stackTrace
    dasm = disassembly.Disassembly(pc_sbaddr, self.target)
  File "./adapter/disassembly.py", line 62, in __init__
    last_instr = self.instructions[len(self.instructions)-1]
  File "/Applications/Xcode_8_1.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 5267, in __getitem__
    return self.GetInstructionAtIndex(key)
  File "/Applications/Xcode_8_1.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 5236, in GetInstructionAtIndex
    return _lldb.SBInstructionList_GetInstructionAtIndex(self, *args)
OverflowError: in method 'SBInstructionList_GetInstructionAtIndex', argument 2 of type 'uint32_t'

_Copied from original issue: Microsoft/vscode#16012_

**Comment by pieandcakes** [comment]
@PerMildner Are you using the lldb version that is shipped with our CPPTools extension or did you replace it with the version from XCode?  This looks like its using XCode's version of lldb which we don't support. 

We ship a customized version of lldb that works with our extension and contains specific bugfixes.

**Comment by PerMildner** [comment]
Note that I used did not use the "cppdbg" debugger type. I used "lldb" from vadimcn.vscode-lldb and it does not come with its own customized lldb binary.

(The reason I did not use cppdbg was that it had many other problems that makes it next to useless on OS X with our code)

**Comment by pieandcakes** [comment]
@PerMildner We build ours with `LLDB_DISABLE_PYTHON=1`. If you can point me to a way to get the copy you are using I can give it a shot.

**Comment by PerMildner** [comment]
@pieandcakes I am not sure I understand what you mean by "the copy you are using". I use Xcode 8.1 and VSCode et al. as described above. I have not built any part of the tool chain myself.

I think I will go back to attempting to use cppdbg, and try to get its various problems fixed instead.

**Comment by pieandcakes** [comment]
@PerMildner When you say you specified `type: lldb`, does that mean you are using WebFreak's Native Debug? If so, this is the support page for the Cpptools extension using cppdbg.

**Comment by PerMildner** [comment]
@pieandcakes As I wrote above, the problem was not with cppdbg. It was @jrieken that moved the issue to here from Microsoft/vscode#16012.

**Comment by pieandcakes** [comment]
@PerMildner I understand now, thanks. I can't move the issue to WebFreak's issues page, but if you would like to open one there, they may be able to help you. 

I'm going to close this for now. If you need help with cppdbg please let us know.

**Comment by PerMildner** [comment]
@pieandcakes Actually I could not find a way to report problems with vscode extensions, that is why I reported it to Microsoft/vscode. How would I find the issues page for a particular extension, like the vadimcn.vscode-lldb extension?

**Comment by pieandcakes** [comment]
@PerMildner For ours, its listed in the readme.MD that is in the extension's folder. On the Native Debug extension, it looks like WebFreak posted a comment with the URL. For the lldb extension, [this ](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) is their extension page in the VSCode Extension Gallery. It looks like they have an issues page on the right hand column. 

HTH

**Comment by PerMildner** [comment]
@pieandcakes Thanks. I only looked at each installed extensions description within vscode and there I did not see anything about bug reporting (it turns out there _are_ links hiding within the description text, just not among the "important links" at the top of the descriptions). Thanks for the help.
