### ISSUE TITLE
Still can't open (find) <sys\time.h>

### ISSUE THREAD

**Issue by hsmyers** [microsoft/vscode-cpptools#3720]
Issue Type: <b>Bug</b>

Add:
#include <sys\time.h>
to source file. The c_cpp_properties.json file has this in the Win32 include path:
        "includePath": [
            "${workspaceFolder}/**",
            "c:/msys64/usr/include/**",
            "c:/mingw64/x86_64-w64-mingw32/include/**"
        ],
Both of the last two entries should satisfy the search as they both have subdirectories of 'sys' with time.h files within.

The file compiles as expected without problem indicating that gcc can find the file even if the C/CPP extension can't.

My expectations are No error message. The extension should parse the indicated include path(s). This is clearly a version of vscode-cpptools #1107 which was said to be fixed. It does not seem so.

Extension version: 0.23.1
VS Code version: Code - Insiders 1.35.0-insider (0284236851a94b116f468345f6e98688a737015d, 2019-05-31T21:32:42.295Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8320 Eight-Core Processor            (8 x 3512)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (19.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bobbrow** [comment]
It looks like you are trying to set system include paths manually.  This is not recommended for GCC-family compilers because you will be missing some paths and defines.

Try setting something like `"compilerPath": "c:/mingw64/x86_64-w64-mingw32/bin/gcc.exe"` instead.  (i'm guessing your compiler path, yours may be slightly different)

**Comment by hsmyers** [comment]
Sorry, no change. Still says:
{
"resource": "/c:/Users/hsmyers/Documents/LilyPond/mug/timestamp.c",
"owner": "clang",
"severity": 8,
"message": "'sys\\time.h' file not found",
"startLineNumber": 10,
"startColumn": 10,
"endLineNumber": 10,
"endColumn": 22
}
with c_cpp_properties set to:
{
"configurations": [{
"name": "Win32",
"includePath": [
"${workspaceFolder}/**",
"c:/msys64/usr/include/**"
],
"defines": [
"_DEBUG",
"UNICODE",
"_UNICODE"
],
"windowsSdkVersion": "10.0.14393.0",
"compilerPath": "c:/msys64/usr/bin/gcc.exe",
"cStandard": "c11",
"cppStandard": "c++17",
"intelliSenseMode": "gcc-x64"
}],
"version": 4
}

**Comment by bobbrow** [comment]
Did you try removing `"c:/msys64/usr/include/**"` from the `"includePath"`?

If that still doesn't work, can you run the "C/C++: Log Diagnostics" command (in the command palette) and share the output with us?

**Comment by hsmyers** [comment]
If I remove " c:/msys64/usr/include/**" from the "includePath I get
multiple 'cannot open source file…' errors.

I'll run the diagnostic log next and get back to you.

**Comment by hsmyers** [comment]
From C/C++ Log Diagnostics:

-------- Diagnostics - 6/3/2019, 12:13:55 PM
Version: 0.23.1
Translation Unit Mappings:
[C:\Users\hsmyers\Documents\LilyPond\mug\timestamp.c]:
C:\USERS\HSMYERS\DOCUMENTS\LILYPOND\MUG\TIMESTAMP.C
Translation Unit Configurations:
[C:\Users\hsmyers\Documents\LilyPond\mug\timestamp.c]:
Process ID: 16364
Memory Usage: 15 MB
Compiler Path: c:/msys64/usr/bin/gcc.exe
Includes:
C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\7.4.0\INCLUDE
C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\7.4.0\INCLUDE-FIXED
C:\MSYS64\USR\INCLUDE\W32API
C:\MSYS64\USR\INCLUDE
Defines:
_DEBUG
UNICODE
_UNICODE
Standard Version: c11
IntelliSense Mode: gcc-x64
Other Flags:
--gcc
--gnu_version=70400
Total Memory Usage: 15 MB

**Comment by sean-mcmanus** [comment]
I've reproed the issue -- our attempt to query the compiler is failing with "Compiler include path not found: c:\\msys2\\usr\\bin\/lib/gcc/x86_64-pc-msys/7.3.0/include", etc. If you [enable debug logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) you could double check that you see a similar error.

Recursive includes should never be used for system includes, because there is a particular ordering required.

Can you try using:
```
C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\7.4.0\INCLUDE
C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\7.4.0\INCLUDE-FIXED
C:\MSYS64\USR\INCLUDE
C:\MSYS64\USR\INCLUDE\W32API
```
as a workaround?

I assume you're using C and not C++, right?

**Comment by sean-mcmanus** [comment]
The compiler at `c:/msys64/usr/bin/gcc.exe` appears to be intended to be run from within a Linux-type environment that expects Linux style paths -- do you have an alternative compiler under msys64 such as `C:\\msys64\\mingw64\\bin\\gcc.exe` that returns Windows paths?

Otherwise, it looks like we'd need to add code to get correct root when we receive the "/lib/..." path -- we have code that does this for Cygwin, but it looks like it doesn't work for MSYS64.

**Comment by hsmyers** [comment]
Yes, for small utilities I use C (or Perl). I've found that either style
seems to work in the .json file, both forward slashes, and traditional
backward slashes. I'll switch and see if it makes a difference. The msys2
compiler install is designed for windows. If I were using windows linux I'd
use gcc 8.x…

With suggested changes, the only difference in the log is the revised path
for the compiler.

**Comment by sean-mcmanus** [comment]
Does C:/msys64/usr/include/sys/time.h exist for you?

Another possible cause of the failure is if your paths have the Windows case-sensitive file paths enabled.

**Comment by hsmyers** [comment]
Yes, the directory 'sys' exists within the directory 'include' with time.h
present.

Regards case sensitivity for paths, I would have had to enable that on a
per-directory basis and there is no reason I would have done that. I find
it ironic that 'nix requires this yet still cannot handle spaces in the
path cleanly.

**Comment by sean-mcmanus** [comment]
...unless your mys64 installer enabled case-sensitive file paths on those directories (my msys2 installer didn't do this). You could double check by running `fsutil.exe file queryCaseSensitiveInfo C:\msys64\usr\include`.

**Comment by hsmyers** [comment]
I get:

C:\>fsutil.exe file queryCaseSensitiveInfo C:\msys64\usr\include
Case sensitive attribute on directory C:\msys64\usr\include is disabled.

**Comment by bobbrow** [comment]
Can you tell us which distro of MinGW this is?  I installed msys64 a while back, but my compiler actually lives in `C:\msys64\mingw64\bin\gcc.exe`, not `C:\msys64\usr\bin\gcc.exe`.  Unfortunately, I do not reproduce your issue when I use this compiler.  If you [enable debug logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md), and restart VS Code, do you see any errors in the Output Window related to your compiler?

If you run `gcc.exe -v -E -x c -`, what include path is printed by your compiler?

**Comment by hsmyers** [comment]
I get:
C:\>gcc -v -E -x c
gcc: warning: ‘-x c’ after last input file has no effect
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-7.4.0/configure
--build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib
--enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static
--enable-version-specific-runtime-libs --with-arch=x86-64
--with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2
--enable-languages=c,c++,fortran,lto --enable-graphite
--enable-threads=posix --enable-libatomic --enable-libcilkrts
--enable-libgomp --enable-libitm --enable-libquadmath
--enable-libquadmath-support --disable-libssp --disable-win32-registry
--disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check
--enable-checking=release --without-libiconv-prefix
--without-libintl-prefix --with-system-zlib --enable-linker-build-id
--with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 7.4.0 (GCC)

All I have in c:\msys64\mingw64\bin are files from pacman installs. In so
as I know my installation of msys2 is the current one.

**Comment by bobbrow** [comment]
The `-` at the end of the command is important.  The compiler won't print out the paths without it.  Can you rerun the command with the `-` at the end?

**Comment by hsmyers** [comment]
C:\>gcc -v -E -x c -
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-7.4.0/configure
--build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib
--enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static
--enable-version-specific-runtime-libs --with-arch=x86-64
--with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2
--enable-languages=c,c++,fortran,lto --enable-graphite
--enable-threads=posix --enable-libatomic --enable-libcilkrts
--enable-libgomp --enable-libitm --enable-libquadmath
--enable-libquadmath-support --disable-libssp --disable-win32-registry
--disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check
--enable-checking=release --without-libiconv-prefix
--without-libintl-prefix --with-system-zlib --enable-linker-build-id
--with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 7.4.0 (GCC)
COLLECT_GCC_OPTIONS='-v' '-E' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-pc-msys/7.4.0/cc1.exe -E -quiet -v -Dunix -idirafter
/usr/lib/../lib/../include/w32api -idirafter
/usr/lib/gcc/x86_64-pc-msys/7.4.0/../../../../x86_64-pc-msys/lib/../lib/../../include/w32api
- -mtune=generic -march=x86-64
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory
"/usr/lib/gcc/x86_64-pc-msys/7.4.0/../../../../x86_64-pc-msys/include"
ignoring duplicate directory
"/usr/lib/gcc/x86_64-pc-msys/7.4.0/../../../../x86_64-pc-msys/lib/../lib/../../include/w32api"
ignoring nonexistent directory "c"
#include "..." search starts here:
#include <...> search starts here:
 \win-builds\lib64
 /usr/lib/gcc/x86_64-pc-msys/7.4.0/include
 /usr/lib/gcc/x86_64-pc-msys/7.4.0/include-fixed
 /usr/include
 /usr/lib/../lib/../include/w32api
End of search list.

**Comment by hsmyers** [comment]
Before I forget (again) I don't use vscode to compile, I do that from the
command line.

**Comment by bobbrow** [comment]
Ok, this confirms what @sean-mcmanus was saying about the linux-style paths.

>Before I forget (again) I don't use vscode to compile, I do that from the
command line.

That's ok.  We just use the compiler to query the system include paths and default \#defines.

**Comment by MickeyElZouhery** [comment]
What is your issue here

**Comment by MickeyElZouhery** [comment]
and what is your project

**Comment by hsmyers** [comment]
The issue is the appearance of an error message in problems window
(sys\time.h file not found) that by all rights should not be there since
the file is located in the path as given.

The 'project' is a short 'C' compilation which includes <sys\time.h>.

**Comment by YassinMahmoudEl-Zouhery** [comment]
What is your issue in the project

**Comment by Colengms** [comment]
Hi @hsmyers .  Are you still seeing this issue?  Recent versions of MinGW appear to return Windows style paths.  I'm not able to easily repro an issue finding sys/time.h using recent versions of the C/C++ Extension and MinGW.

**Comment by hsmyers** [comment]
It has been so long that I no longer remember the details. I also have
moved on to other toolchains—vscode with wsl2, where everything works as
expected… You may as well close the issue!

--hsm
