### ISSUE TITLE
Cannot open output file

### ISSUE THREAD

**Issue by SolarTorch** [microsoft/vscode-cpptools#3722]
Type: Debugger

Get error message 
> /usr/bin/ld Cannot open output file

- OS and Version: Windows 10 1903
- VS Code Version: 1.34.0
- C/C++ Extension Version: 0.23.1
- I followed the instruction [Get Started with C++ and WSL](https://code.visualstudio.com/docs/cpp/config-wsl) and modify launch.json as below:

`

    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}.out",
            "args": ["-fThreading"],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}/",
            "environment": [],
            "externalConsole": true,
            "windows": {
                "MIMode": "gdb",
                "miDebuggerPath": "/usr/bin/gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "c:\\windows\\sysnative\\bash.exe",
                "pipeArgs": ["-c"],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/mnt/c": "${env:systemdrive}/",
                "/usr": "C:\\Users\\Helan\\AppData\\Local\\Packages\\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\\LocalState\\rootfs\\usr\\"
            }
        }
    ]
`

I used the sample Hello World Code from the link but cannot get the development environment set up properly.

BTW, the instruction is outdated somehow.

**Comment by pieandcakes** [comment]
`/usr/bin/ld` is the linker. You are getting a compiler error. Please include what your compile command/`task.json` file contains.

**Comment by SolarTorch** [comment]
> `/usr/bin/ld` is the linker. You are getting a compiler error. Please include what your compile command/`task.json` file contains.

`

    "version": "2.0.0",
    "tasks": [
        {
            "label": "make",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g",
                "-o",
                "${workspaceFolder}/${fileBasenameNoExtension}.out",
                "helloworld.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]

`

**Comment by pieandcakes** [comment]
If you commandline compile, do you get the .out file?

**Comment by SolarTorch** [comment]
> 
> 
> If you commandline compile, do you get the .out file?

No. There is no .out file.

**Comment by pieandcakes** [comment]
You tried to run `g++ -g -o <workspaceFolder>/helloworld.out helloworld.cpp` (replacing workspaceFolder with your folder) and it doesn't work?  That sounds like the issue is outside the extension since it doesn't work from the command line.

**Comment by SolarTorch** [comment]
But it does work to if I compile directly with `g++ -g -o helloworld.out helloworld.cpp `

**Comment by SolarTorch** [comment]
> 
> 
> You tried to run `g++ -g -o <workspaceFolder>/helloworld.out helloworld.cpp` (replacing workspaceFolder with your folder) and it doesn't work? That sounds like the issue is outside the extension since it doesn't work from the command line.

I see what the problem is. `<workspaceFolder>` gives the folder location under Windows, but the compiler needs the location under WSL.
