### ISSUE TITLE
Add way to restart language server for a specific file

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#3727]
https://github.com/microsoft/vscode-cpptools/issues/3603 and https://github.com/microsoft/vscode-cpptools/issues/2966 are still open, and I still randomly see at least 2966, which seems like a race condition somewhere. Closing the file, waiting for the language server for that file to close, and reopening always solves both issues, so it would be nice if there was a way to manually reset the language server on a file. That way the delay wouldn't be needed, and could just be immediately restarted.

**Comment by sean-mcmanus** [comment]
By language server I assume you mean the Microsoft.VSCode.CPP.IntelliSense.Msvc.exe process -- you could trying do some a "kill Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" command.

It sounds like fixing the root bugs might be a better solution. I think they're caused by our didOpen event getting delayed for the custom config provider, but then we receive other messages that aren't delayed.

**Comment by ThadHouse** [comment]
I don't want to kill the whole process, I notice in the debug logs that after about 20 seconds it receives a message saying `shutting down language server for file *`. So I don't know if its just 1 process with multiple files, or 1 process per file, but a way to restart just the server parsing for that file.

Another option would be a button to reforce sending the API data to get intellisense.

I do agree fixing the root bugs would be the best fix, but I know that doing that might take a while.

**Comment by sean-mcmanus** [comment]
We never output "shutting down language server for file" -- do you mean `Shutting down IntelliSense server: <file>`? That shutdown terminates the IntelliSense process for the translation unit and not the main extension process. It's one process per translation unit.

**Comment by bobbrow** [comment]
This would be a relatively easy thing to add.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2 (C/C++: Restart IntelliSense for Active File command).
