### ISSUE TITLE
Debugging stops at code file not on machine/Performance tools Feature request

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3728]
Issue Type: <b>Bug</b>

Multi threaded program.
Hit pause or break.
`Unable to open 'cthread.c': Unable to read file (Error: File not found (d:\agent\_work\4\s\src\vctools\crt\crtw32\stdcpp\thr\cthread.c)).`

I do not have a D:\ drive. it seems that the extension is referencing a static file path that was used during development, please fix!

Also consider adding Ram / CPU Usage graph, similar to Visual Studio.

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.88GB free)|
|Process Argv|C:\Users\Maher\source\repos\XPBuddyCPP|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pieandcakes** [comment]
@ninja-1337 you are stopped in library code. Move to a portion of the call stack where your code exists and then you will see your source code.  

For the RAM/CPU performance tools monitoring, we will take it into consideration but as theres no protocol for it in VS Code, it won't be something we will get to until VS Code supports it.
