### ISSUE TITLE
[Mac] Debug Console prints a carriage (\n) return and a newline (\n) for every printf

### ISSUE THREAD

**Issue by prime31** [microsoft/vscode-cpptools#3729]
Issue Type: <b>Bug</b>

printf produces a lot of extra noise in the Debug Console. Rather than just printing the data you pass to it a lot of extract chars get placed in the output making it hard to read.

Run the following program and open the Debug Console to view the log output.

```c
int main(void) {
    printf("0\n");
    printf("1\n");
    printf("2\n");
}
```

Expected output:
```
0
1
2
```

Actual output:
```
@"0\r\n"
@"1\r\n"
@"2\r\n"
```

Extension version: 0.23.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pieandcakes** [comment]
@prime31 That is from `lldb-mi`. If you want to see your output without that, change the setting `"externalConsole": true`.

**Comment by prime31** [comment]
That’s odd. Is there anyway to workaround having to spawn an external console? Having to pop up a separate console every run kills the nice workflow Code provides. Should I open a bug with lldb directly or is this expected behavior?

**Comment by pieandcakes** [comment]
VS Codes integrated terminal as a console is blocked because lldb-mi currently has no support to redirected `tty` in its codebase.
