### ISSUE TITLE
Multi line macros break code highlighting in file

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode-cpptools#373]
When using multi-line macros, code highlighting in the rest of the file is broken below the macro. Instead of base text being white, its blue. Attached is a file that showcases this issue on every system I have tested with, which includes 2 windows 10 systems, and a ubuntu system. VSCode 1.7.2 and C++ extension 0.9.2

![macros](https://cloud.githubusercontent.com/assets/7727148/20645256/16a6e19e-b40d-11e6-8d7a-3ace0b79db0e.PNG)
![nomacros](https://cloud.githubusercontent.com/assets/7727148/20645257/1a9a7acc-b40d-11e6-87b6-74a01db3b53b.PNG)

[AnalogGyroJNI.zip](https://github.com/Microsoft/vscode-cpptools/files/614547/AnalogGyroJNI.zip)

**Comment by djg** [comment]
This is a bug in the TextMate C language parsing rules. Every editor that uses TextMate as a basis for C/C++ syntax highlighting has this bug.

**Comment by sean-mcmanus** [comment]
Yeah, you're right. You can track the issue at https://github.com/atom/language-c/issues . It seems like lots of users have complained about it. Not sure why it's taking so long to fix.
