### ISSUE TITLE
Incorporate CMake Tools extension

### ISSUE THREAD

**Issue by hudsonmiranda291** [microsoft/vscode-cpptools#3730]
The CMake Tools extension (https://github.com/vector-of-bool/vscode-cmake-tools) for VSCode with 727k installs is currently looking for a primary maintainer (https://github.com/vector-of-bool/vscode-cmake-tools/issues/691). I think it would make sense to incorporate it on cpptools to improve CMake support.

**Comment by bobbrow** [comment]
Thank you for reaching out.

We have been in contact with @vector-of-bool in regards to this.  I was meaning to reply to that issue so that the community would be aware, but had not done so yet.  I will do it now.
