### ISSUE TITLE
problem matcher for IAR toolchain

### ISSUE THREAD

**Issue by rohitkotak** [microsoft/vscode-cpptools#3735]
- OS and Version: windows 10
- VS Code Version: 1.34.0
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them): NA
- A clear and concise description of what the bug is: When ctrl-select on the compilation error/warning message on the terminal, it should navigate the window to that line of the file which causes the error/warning. But it is always navigates to the first line of the file. We are not able to navigate to the correct line of the error. We are using IAR toolchain (IAR version: 8.30.1.17148). 

**To Reproduce**
1. Install IAR workbench version 8.30.1.17148
2. Compile code which contains compilation error using installed IAR's toolchain
3. ctrl-select on the error message on terminal

**Expected behavior**
Ctrl-select on the error message on terminal should navigate to the line which cause the error.

logs:
1. error message in my case: 
"D:\Work\Code\myproject\Main.c",58  Error[Pe140]:
          too many arguments in function call
2. Ctrl-select on this navigates to 1st line of Main.c file. It should navigate to 58th line of Main.c file.

**Comment by sean-mcmanus** [comment]
You would need to create a problem matcher that matches the errors output by your tool. We just ship a $gcc problem matcher. It probably belongs in a separate IAR extension and not the C++ extension.

**Comment by rohitkotak** [comment]
Below is my custom problem matcher:
```
    "problemMatcher": {
        "fileLocation": "absolute",
        "pattern": [
            {
                "regexp": "^.*$"
            },
            {
                "regexp": "^.*$"
            },
            {
                "regexp": "^(.*),(\\d+)\\s+(Warning|Error).*:\\s*$",
                "file": 1,
                "line": 2,
                "severity": 3
            },
            {
                "regexp": "\\s*^(.*)\\s*$",
                "message": 1
            }
        ]
    },
```

I have attached compilation log with error.
[IAR_build_log.txt](https://github.com/microsoft/vscode-cpptools/files/3265330/IAR_build_log.txt)

Please have a look and let me know if I missed anything.

**Comment by sean-mcmanus** [comment]
In your tasks.json, can you try adding the problem matcher?
```
    "problemMatcher": {
        "base": "$gcc",
        "source": "IAR",
        "fileLocation": "absolute",
        "pattern": [
            {
                "regexp": "^.*$"
            },
            {
                "regexp": "^.*$"
            },
            {
                "regexp": "^(.*),(\\d+)\\s+(Warning|Error).*:\\s*$",
                "file": 1,
                "line": 2,
                "severity": 3
            },
            {
                "regexp": "\\s*^(.*)\\s*$",
                "message": 1
            }
        ]
    },
```

@bobbrow Is this something we would be willing to accept a pull request for to add our built-in problem matchers? I don't know how many other users would benefit from this.

**Comment by bobbrow** [comment]
Based on the [documentation](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher) it doesn't seem like you need the first two regexp's.  Can you try removing them and see if it still works for you?  If so, we can add this to our `package.json`.

**Comment by rohitkotak** [comment]
There is no impact whatever I change into the problemMatcher. When I ctrl+click on error message on TERMINAL, it navigates me to the first line of that file only.

Also, I verified on link [https://regex101.com/] that this regexp is correct to parse the correct line number.

**Comment by bobbrow** [comment]
Can you try this one instead?  `.*` can give unpredictable results so I try to use `[^]` instead when possible.

```
            "problemMatcher": {
                "fileLocation": "absolute",
                "pattern": [
                    {
                        "regexp": "^\"?([^\",]*)\"?,(\\d+)\\s+(Warning|Error)\\[([^\\]]*)\\]:\\s*$",
                        "file": 1,
                        "line": 2,
                        "severity": 3,
                        "code": 4
                    },
                    {
                        "regexp": "^\\s*(.*)$",
                        "message": 1
                    }
                ]
            },
```
