### ISSUE TITLE
doesn't shows problem for cpp files

### ISSUE THREAD

**Issue by raiadi2008** [microsoft/vscode-cpptools#3736]
Issue Type: <b>Bug</b>

The code editor doesn't reports any problem in the PROBLEMS section even if my code is wrong or i am using some undifined variable, how ever it does shows error for non-matching brackets and comma but not for the wrong code as used to do before, this problem probably arose after installing Python extension, but i am not very sure about it.

Extension version: 0.23.1
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
@raiadi1999, can you verify if the issue also reproduces when the Python extension is disabled? Did you change any default settings for the C++ extension? Are there any file exclusion settings set by Python or VS Code in `settings.json` for the workspace scope or user scope?

**Comment by raiadi2008** [comment]
> @raiadi1999, can you verify if the issue also reproduces when the Python extension is disabled? Did you change any default settings for the C++ extension? Are there any file exclusion settings set by Python or VS Code in `settings.json` for the workspace scope or user scope?

uninstalling every single extension and then reinstalling intllisense and c/cpp extension worked fine for me. However just disabling the python extension does no fruitful help to me. but after doing the steps i mentioned above it started working fine even after installing python extension. Thanks for the help
