### ISSUE TITLE
Restrict intellisense to files listed

### ISSUE THREAD

**Issue by sg-** [microsoft/vscode-cpptools#374]
Moved from https://github.com/Microsoft/vscode-tips-and-tricks/issues/24

I'd like to reduce the noise intellisense is giving by creating a white list of files that it should index. Is this possible? I'd thought the below snippet would kill all indexing but it seems to still search the root project directory and all subdirectories with have a lot of nonsense for my particular project.

c_cpp_properties.json
```
{ 
    "configurations": [
        {
            "name": "Mac",
            "includePath": ["${workspaceRoot}/main.cpp"]
        }                
    ]
}
```
Any tips? Much appreciated!

**Comment by janjongboom** [comment]
+1

**Comment by sean-mcmanus** [comment]
Yeah, we're currently planning to remove the implicit ${workspaceRoot} from the includePath in our next release.

**Comment by sg-** [comment]
@sean-mcmanus When is your next release?

**Comment by sean-mcmanus** [comment]
I removed the ${workspaceRoot} for 0.10.0, but other people on our team wanted to add it back...so maybe in a future release we'll add some setting to allow people to remove it. If you really want it out, you can modify the javascript code that adds the ${workspaceRoot} in ms-vscode.cpptools-0.10.0/out/src/LanguageServer/C_Cpp_ConfigurationProperties.js line 208/211. Without the workspace root, it won't parse your source code files in the workspace until you open the files (i.e. workspace symbol searching might miss things). It'd be better if we added some "source files" settings for scenarios where the root contains only a subset of folders with source files that the user wants parsed. And we're planning another bug fix release in February.

**Comment by sg-** [comment]
Is there a way to override the behavior in the meanwhile?

**Comment by bobbrow** [comment]
A new setting was added in 0.10.2 that will allow you to disable automatic recursive parsing of the `${workspaceRoot}` folder.

**Comment by sunnyps** [comment]
Can you confirm if ${workspaceRoot} is still considered as a _non-recursive_ include path? My limited testing tells me that's the case. Specifically when opening Chromium's src directory, it looks like the include paths, most of which are relative to src, work.

**Comment by sean-mcmanus** [comment]
It is recursive, so you don't need to add additional include paths that are subdirectories...you can if you want, but it would just increase the processing done (ideally we would skip doing extra work if a path has already been searched, but we don't currently).
