### ISSUE TITLE
String visualizer for text variables

### ISSUE THREAD

**Issue by Trevinlc1997** [microsoft/vscode-cpptools#3742]
The same feature that visual studio has, as shown in this link https://docs.microsoft.com/en-us/visualstudio/debugger/string-visualizer-dialog-box?view=vs-2019

But it may not be a high demand feature. I personally want it to check formatting, etc.

**Comment by michelleangela** [comment]
This feature is not specific to C/C++ language and can benefit other languages. It may be better suited for VS Code to implement. Please file this feature request at VS Code's repro at https://github.com/microsoft/vscode/issues.

**Comment by Trevinlc1997** [comment]
Alright thanks. I honestly can't tell which I should post to.

**Comment by michelleangela** [comment]
@Trevinlc1997 , you're welcome.

Usually, any features or concerns specific or implemented by the Microsoft C/C++ extension should be posted on the [vscode-cpptools repo](https://github.com/microsoft/vscode-cpptools). For any general features or concerns not specific to any extensions or expected to ship as an in-box feature with VS Code client, should be posted on the [vscode repo](https://github.com/microsoft/vscode).
