### ISSUE TITLE
launch gdb error on wsl

### ISSUE THREAD

**Issue by henaiguo** [microsoft/vscode-cpptools#3746]
I'm a newer in vscode&wsl, and I get error when starting with this tutorial
[https://code.visualstudio.com/docs/cpp/config-wsl](https://code.visualstudio.com/docs/cpp/config-wsl)

The error is:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/14122312/59205641-dfc47580-8bd5-11e9-907b-07674c7989d8.png">

My config files are:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/14122312/59205742-11d5d780-8bd6-11e9-83a7-b24c514c8a8d.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/14122312/59205773-2023f380-8bd6-11e9-992f-f9243f2d7763.png">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/14122312/59205796-3467f080-8bd6-11e9-8a91-b6e003ad5833.png">

My wsl:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/14122312/59205855-53ff1900-8bd6-11e9-974e-43350d176046.png">

The tasks.json runs well, and generates helloworld.out, but gdb can't find it. I don't know why

**Comment by WardenGnaw** [comment]
@HelloLucio That documentation is only for running and debugging your application remotely on WSL. To make it work with what you currently have, you will need to add `pipeTransport` to your `launch.json`. 

If you wish to edit, compile, and debug under WSL, you should use [VS Code Remote - WSL](https://code.visualstudio.com/docs/remote/wsl).

**Comment by henaiguo** [comment]
@WardenGnaw It works, thanks!
