### ISSUE TITLE
Problem configuring MSVC compiler - red squiggles

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#3749]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1803
- VS Code Version: 1.35.0
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them): CMake Integration

I have created a new project to build a single .cpp file using CMake and the Visual Studio 2017 compiler.  Build succeeds using CMake but vscode-cpptools is showing red squiggles under an include path and under a valid line of code:

![image](https://user-images.githubusercontent.com/7724321/59284627-750e4b00-8c64-11e9-8ecc-8d2dd3d525c0.png)

Here is my c_cpp_properties.json:

    {
    "configurations": [
        {
            "name": "Release",
            "includePath": [

            ],
            "defines": [
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceFolder}/.vscode/.browse2.vc.db",
                "path": [
                ]
            },
            "intelliSenseMode": "msvc-x64",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
    }

What am I doing wrong?

**Comment by daldr-ntml** [comment]
Perhaps I have misunderstood. Do the red squiggles indicate errors reported by the CMake generator?

**Comment by sean-mcmanus** [comment]
Please provide the text of the error squiggles so we can determine the source (in the Problems window).

**Comment by daldr-ntml** [comment]
The errors are:

`#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\SVNProj\<snip>\trunk\Software\Prototypes\CPlaneTest\CPlaneTest.cpp).`

`cannot open source file "windows.h" (dependency of "C:\SVNProj\<snip>\trunk\Software\Prototypes\CPlaneTest\CPlaneTest.cpp")`

I thought it wasn't necessary to specify system include paths for MSVC projects?

**Comment by bobbrow** [comment]
@DavidA2014, can you add the "windowsSdkVersion" property to your configuration?  It seems to be missing.

For example:
```
            "windowsSdkVersion": "10.0.17763.0",
```

**Comment by daldr-ntml** [comment]
@bobbrow, thanks for your reply. I have added that line but it makes no difference.

    {
        "configurations": [
            {
                "name": "Release",
                "includePath": [
    
                ],
                "defines": [
                ],
                "browse": {
                    "limitSymbolsToIncludedHeaders": true,
                    "databaseFilename": "${workspaceFolder}/.vscode/.browse2.vc.db",
                    "path": [
                    ]
                },
                "intelliSenseMode": "msvc-x64",
                "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
                "cStandard": "c11",
                "cppStandard": "c++14",
                "windowsSdkVersion": "10.0.17763.0"
            }
        ],
        "version": 4
    }

The C/C++ extension debug output is:

    Custom configuration provider 'CMake Integration' registered
    Custom configurations received:
    Custom configurations received:
      uri: file:///c%3A/SVNProj/Athena/trunk/Software/Prototypes/CPlaneTest/CPlaneTest.cpp
      config: {
      "includePath": [],
      "defines": [
        "UNICODE",
        "_CONSOLE",
        "_UNICODE"
      ],
      "intelliSenseMode": "msvc-x64",
      "standard": "c++17"
    }
    Custom browse configuration received: {
      "browsePath": [],
      "standard": "c++98"
    }

The problem window output is:

    #include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\SVNProj\Athena\trunk\Software\Prototypes\CPlaneTest\CPlaneTest.cpp).
    cannot open source file "windows.h" (dependency of "C:\SVNProj\Athena\trunk\Software\Prototypes\CPlaneTest\CPlaneTest.cpp")

This file does exist:
"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\Windows.h"

Do you have any other ideas please?

**Comment by bobbrow** [comment]
Oh, hang on, you're using CMake Tools to provide the configuration.  Do you have `C_Cpp.default.configurationProvider` set to `vector-of-bool.cmake-tools`?  It's not in your configuration, so I wasn't expecting that.  When another extension provides the configurations, `c_cpp_properties.json` is not used.

Did you select a compiler "Kit" in CMake Tools?  It appears that it is not providing correct configurations to our extension.  Usually it sends the `compilerPath`.

**Comment by daldr-ntml** [comment]
@bobbrow Sorry, I should have told you that I'm using CMake, but I didn't realise there was a dependency on your extension. I'm actually using the 'CMake Integration' extension (if you think I could make a better choice please tell me).  The settings.json file of my root folder contains:

    {
        "C_Cpp.intelliSenseEngine": "Default",
        "C_Cpp.default.configurationProvider": "go2sh.cmake-integration"
    }

I really struggle with all the settings and different settings files. I'll have another look at the extension's documentation.

**Comment by bobbrow** [comment]
Oops.  I read your log wrong.  I'm not very familiar with the "CMake Integration" extension.  This appears to be an issue with that extension.  I would recommend you [open an issue in their repo](https://github.com/go2sh/cmake-integration-vscode/issues).

**Comment by bobbrow** [comment]
And as far as a recommendation goes, we use the "CMake Tools" extension by `vector-of-bool` and are pretty satisfied with it.

**Comment by daldr-ntml** [comment]
@bobbrow Thanks very much for your help.
