### ISSUE TITLE
Doesn't work on CentOS 7

### ISSUE THREAD

**Issue by kbadz** [microsoft/vscode-cpptools#375]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 3.10.0-327.22.2.el7.x86_64
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|cpptools|ms-vscode|0.9.2|

---

Cpptools plugin doesn't work on CentOS 7. It seems it doesn't recognize any cpp/hpp files at all..
I had no such issue on other OSes.

**Comment by pieandcakes** [comment]
This is a duplicate of #19 . It seems to be an issue with glibc version that the language service is compiled against is newer than the default one in CentOS7

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
