### ISSUE TITLE
Extension downloading

### ISSUE THREAD

**Issue by npatel99** [microsoft/vscode-cpptools#3750]
Issue Type: <b>Bug</b>

I install vscode version 1.35.0 in my ubuntu OS and also install extension. But when I am trying to open my c/c++ code in VScode then in terminal some packages are trying to download automatically and it is showing "Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying....."
please tell me what to do..? 

Extension version: 0.23.1
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:13:26.790Z)
OS version: Linux x64 4.15.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|7.69GB (0.70GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by WardenGnaw** [comment]
You may want to grab the cpptools-linux.vsix [offline installer](https://github.com/microsoft/vscode-cpptools/releases) for the vscode-cpptools extension. You will want to go to the debug tab and use the `install from vsix...` selection from the dropdown.
