### ISSUE TITLE
$gcc problem matching not working with WSL

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3751]
Just got bitten by this issue after I switched from developing on the virtual machine to VSCode on Windows + WSL...

The workaround with "problemMatcher" and "fileLocation: relative" didn't help and I cannot play with the makefiles.

Hope there's gonna be some ultimate solution delivered in the future since this is really annoying :/

![image](https://user-images.githubusercontent.com/22395284/59013447-41818a00-883a-11e9-9f10-2b00c4f6c640.png)

_Originally posted by @mgr-inz-rafal in https://github.com/microsoft/vscode-cpptools/issues/2266#issuecomment-499376063_

**Comment by sean-mcmanus** [comment]
@mgr-inz-rafal -- the issue you originally posted to seemed unrelated. The problem matcher is open source if anyone wants to contribute a fix. You can also overwrite most of the fields in your task.json.

**Comment by mgr-inz-rafal** [comment]
OK, thanks for creating the separate issue. Earlier today I fiddled a little bit with different regex patterns set manually in `tasks.json` but with no luck.

**Comment by Colengms** [comment]
This isn't repro'ing for me.  It appears to have been fixed by: https://github.com/microsoft/vscode-cpptools/pull/3916
