### ISSUE TITLE
[Windows] Problem re-attaching to a running process with GDB

### ISSUE THREAD

**Issue by Friday32** [microsoft/vscode-cpptools#3753]
Type: Debugger
- GDB 7.6.1
- OS and Version: Windows 10
- VS Code Version: 1.35.0
- C/C++ Extension Version: 0.23.1

I'm working on an extension that adds company specific functionality for C/C++ code.  It uses cpptools to attach to a running process .  

My testing scenario.
1. Launch VSCode and open my extension project.
2. Run a debug session for the project that launches another instance of VSCode.
3. Run some other program that I will attach to.
4. Within the second instance of VSCode, I run the following launch configuration.

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "${command:extension.getProgramPath}",
            "processId": "${command:extension.selectProgramProcess}",
            "MIMode": "gdb",
            "logging": {
                "moduleLoad": true,
                "trace": true,
                "programOutput":true,
                "engineLogging":true,
                "exceptions":true
             },
            "miDebuggerPath": "${command:extension.getgdbPath}",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
 
I am able to attach to the running process with no issues, set breakpoints, etc.  Pressing the disconnect icon in the debug toolbar appears to close the session.

The problem occurs if I try to reconnect to the same running process by running the launch configuration again.  I'll get an error message stating something along the lines "GDB failed with message:Can't attach to process."

I can reattach to the running process if I close and reopen the instance of VSCode that ran the launch configuration.   

Attached is a copy of the debug console. ( with some edits ).

[cpptools_debug_log.txt](https://github.com/microsoft/vscode-cpptools/files/3278371/cpptools_debug_log.txt)

**Comment by pieandcakes** [comment]
Which distribution (mingw/cygwin/msys2) are you using? 

This is a known problem that we haven't been able to solve. At the bottom of the disconnect request you'll notice we send `-exec-interrupt` and there isn't anything else. this is because async break into the `gdb` process on Windows currently requires user interaction. We time it out and the UI looks like it disconnects, but you can verify that your `gdb.exe` is probably still running. If you end that process in Task manager, it will attach again.

**Comment by Friday32** [comment]
The package I am using, repository version 2013072300, comes from running mingw-get downloaded www.mingw.org .

It sounds like using a another distribution that has a newer version of gdb won't help, since it's a known problem without a resolution.

I'm wondering if it's possible to hook into the detach method of the debug taskbar and extend the functionality to kill gdb. It's not ideal but is better than making a user restart VSCode or manually shutting down the process.  I can add additional options to the toolbar but having multiple detach methods would be confusing.
