### ISSUE TITLE
C_Cpp.clang_format_sortIncludes dosn't work

### ISSUE THREAD

**Issue by ArcherLew** [microsoft/vscode-cpptools#3755]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows7x64
- VS Code Version: 1.35.0
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them):
  C/C++ Clang Command Adapter, Code Runner, Noctis
- A clear and concise description of what the bug is.
I set "C_Cpp.clang_format_sortIncludes" to false ,but when i press alt+shift+f in my opengl program, my includes will be resorted . 
My Original includes :
`
#include <glad/glad.h>
#include <GLFW/glfw3.h>
`
After format by press alt+shift+f :
`
#include <GLFW/glfw3.h>
#include <glad/glad.h>
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bobbrow** [comment]
Capital 'F' comes before lower-case 'a'.  This could be a clang-format issue.  The sorting may be case-sensitive.  What happens if you use lower-case letters for `GLFW`?

**Comment by ArcherLew** [comment]
> Capital 'F' comes before lower-case 'a'. This could be a clang-format issue. The sorting may be case-sensitive. What happens if you use lower-case letters for `GLFW`?

That works ! when i use "glfw/glfw3.h", resorting do not happen again ! Thanks a lot !
