### ISSUE TITLE
Some issues for an optimal workflow

### ISSUE THREAD

**Issue by equinoxr** [microsoft/vscode-cpptools#376]
Hey guys, I allready love to code with VSCode thanks for the good work.

But here are some issues: 
Clang plugin is not working for me ( see https://github.com/mitaki28/vscode-clang/issues/36 ) - so its really no working out of the box... when you think of diagnostics. So do you plan to integrate diagnostics in cpptools? like clang diagnostic tools? 

Autocomplete is not working good. I need context based autocompletion, not any autocompletion. Are you working on this? 

Debugging works great (The debuggeR) good job!

greetz equinox

**Comment by bobbrow** [comment]
Thank you for your feedback.
We have no plans to include clang diagnostic tools in our extension at this time.
context-based auto-completion is being tracked by issue #13.
