### ISSUE TITLE
Change the default databaseFilename to "~/.vscode-cpptools/<workspaceStorage-GUID>" instead of ${workspaceStorage}

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3762]
I hope you can combine intelliSenseCachePath and cpptools database storage path to be one path which name may be “cpptoolsStoragePath”. And then you can add subfolders for intelliSenseCache and db storage path. If so, we just need to set this path 'cpptoolsStoragePath'.
It's strange to set database filename instead of database storage path.

Such as:
If I don't set cpptoolsStoragePath,it's like this:
![1](https://user-images.githubusercontent.com/39362073/58242036-b35ccc80-7d80-11e9-9ae8-49cb9f8814ac.PNG)
If I set cpptoolsStoragePath to "D:\VsCodeCpptoolsStoragePath"
![2](https://user-images.githubusercontent.com/39362073/58242063-be176180-7d80-11e9-9a34-bfd4097b2bb9.PNG)

_Originally posted by @Lennon925 in https://github.com/microsoft/vscode-cpptools/issues/3664#issuecomment-495111172_

**Comment by bobbrow** [comment]
The default location for ipch is shared between workspaces now, so we do not plan to make any changes to the default for databaseFilename.
