### ISSUE TITLE
Switch to header file opens file in a different editor.

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-cpptools#3764]
VSCode Version: VSCode insider 1.36.0-insider
Local OS Version: Windows 10 1803
Remote OS Version: WSL ubuntu 16.04
Remote Extension/Connection Type: WSL
Steps to Reproduce:

From https://github.com/microsoft/vscode-remote-release/issues/666#event-2408627629

Prepare a C project, e.g. example, with lib.c and lib.h. And put it in a windows folder. Make sure it can be accessed through /mnt/c/somePaths/example in WSL.
Open this project with vscode/WSL remote.
Open a file through the Explorer, e.g. lib.c. The editor will show its path is lib.c
Use Alt+O to switch to the header file. The editor will open lib.h as the WSL's mount path, like _/mnt/c/somePaths/example/lib.h`
Use the Explorer to open lib.h, and it will open in another editor, with the path lib.h.
It causes a lot of troubles like I wrote some code in one editor, but it cannot be visible in another editor. And one editor saves the file, and another editor cannot save the file due to conflicts.

Does this issue occur when you try this locally?: No. The file has only one path, the windows path.
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
I tried to reproduce, but wasn't able. Switch to header file is contributed by the cpp extension. Maybe there's something special in that code. Moving to the cpp extension.

@sean-mcmanus If you can point me to the code then I can see if there's something problematic there.

**Comment by sean-mcmanus** [comment]
We have pending "fix" for a similar issue caused when 2 files with different casings get opened by VS Code on Windows: https://github.com/microsoft/vscode-cpptools/issues/3229 . However, our fix is just to give users a warning and disable IntelliSense. We really want VS Code to stop opening 2 different editors for the same file -- this can also occurs on Linux with symlinks too (there's an existing VS Code bug).

The code that triggers the file opening for switchHeaderSource is "onSwitchHeaderSource" at https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/extension.ts . The code that generates the path string is in our closed source language server. I'll send the info via email.

**Comment by aeschli** [comment]
Different casing would explain it. When comparing remote URIs we do this always case insensitive. That's of course not really correct.
Can you query the real file name of the header file before opening it?

**Comment by sean-mcmanus** [comment]
Our language server process does attempt to get the "real name" of the header file. I'm not able to repro the user's issue. A repro project might help.

**Comment by aeschli** [comment]
@wanghc78 added in https://github.com/microsoft/vscode-remote-release/issues/666#issuecomment-502562212:

Here is a screenshot for a C project (jerryscript https://github.com/jerryscript-project/jerryscript). You can see the same file is opened from two paths
- _jerry-core/include/jerryscript.h_
- _/mnt/d/workspace/IoT/jerry-core/include/jerryscript.h_

![jerry](https://user-images.githubusercontent.com/3319260/59584413-ca968d80-9092-11e9-83db-1574f0e34bdd.jpg)

Besides using Alt+O to flip the header, you can also use Ctrl+mouse click to track a file to open. For example, you can first open _jerry-main/main-unix-snapshot.c_, and click the `#include "jerryscript.h"` to open it with the absolute path. 

After that, you can use Ctrl+P to search the file, and it will be shown in two paths.
![jerry2](https://user-images.githubusercontent.com/3319260/59584762-be5f0000-9093-11e9-909a-f13e909ff19e.jpg)

I guess it is related to CPP extension. When I try this in a Node.JS project, and follow `require()` to open another js file, only the relative path in the project will be used, not the absolute path.

And if I use code in non-WSL mode, it works without any problem. For the same jerryscript project, it  only opens a file with the project's relative path.

**Comment by sean-mcmanus** [comment]
@wanghc78 What source file are you opening? Your database could have corrupt data. Could you try doing a Reset IntelliSense Database command?

In WSL "mode", I opened that jerryscript-master folder and created a jerryscript.c file next to the jerryscript.h file and did SwitchHeaderSource but it went to the 1 correct file (without the /mnt shown in the breadcrumb). I was using VS Code Insiders.

**Comment by wanghc78** [comment]
I used Ctrl+Shift+P, and then "C/C++: Reset IntelliSense Database".  The problem is still there.

I opened _jerry-main/main-unix-snapshot.c_, and Ctrl+click the `#include "jerryscript.h"` line to open _jerryscript.h_. 

But I found another information to help you repeat the bug. The project's absolute path inside WSL is _/mnt/d/workspace/IoT/jerryscript_. But I also created a symbolic link at my home directory,  _ winspace -> /mnt/d/workspace/_. for me to quick access the project.

If I go through _~/winspace/IoT/jerryscript_, and open code-insider in WSL mode, the problem will happen. But if I go through the absolute path _/mnt/d/workspace/IoT/jerryscript_, and open code-insider in WSL, there is no such a problem.

**Comment by sean-mcmanus** [comment]
Okay, yeah that symlink is the cause. It could be https://github.com/microsoft/vscode-cpptools/issues/3288 or https://github.com/microsoft/vscode-cpptools/issues/2140.

**Comment by wanghc78** [comment]
Thank you for figuring it out. It's similar to #3288, symbolic resolution caused two different paths.
- The VSCode Explorer uses the path following the symbolic link
- The cpp extension header/source flip or link through symbols follow the absolute path without symbolic link.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
