### ISSUE TITLE
IntelliSense sometimes enters an invalid state after making edits, closing the file without saving, then reopening it

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3768]
Use some code in a saved C++ file, then make some edits, close the file without saving changes, and then reopen the file.

Bug: IntelliSense sometimes enters an invalid state, as if it's operating on the doc with the unsaved edits. This can cause the colorization to appear incorrect (or other stuff based on IntelliSense, such as hover, reference highlighting, go to def, etc.).

**Comment by Colengms** [comment]
I'm not able to repro this issue anymore.  It may have been addressed as part of my edge_host/edge_filebuf changes to fully handle snapshot sessions (which were needed for code folding).  IntelliSense  should now see the file restored to its saved contents.  Closing.
