### ISSUE TITLE
Go to definition doesn't work

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-cpptools#377]
_From @nikamveena on November 30, 2016 7:26_

- VSCode Version: 1.7.2
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open existing c# .net project using a solution
2. Add cpptools extension.
3. Go to definition will appear on right clicking but it doesn't work.

_Copied from original issue: Microsoft/vscode#16251_

**Comment by pieandcakes** [comment]
@nikamveena can you confirm that you are opening a c# .NET project? If so, you should be installing the Omnisharp extension and not the cpptools extension. This extension is for C++. 

That extension is located at https://github.com/OmniSharp/omnisharp-vscode and is also in the gallery.

**Comment by chrmarti** [comment]
My bad, moved it to the wrong repo. @nikamveena Could you open a new issue for Omnisharp? Thanks.
