### ISSUE TITLE
Debugging with gdbserver64 on android: Unable to start debugging. The target process has exited.

### ISSUE THREAD

**Issue by dcharkes** [microsoft/vscode-cpptools#3772]
Type: Debugger

I cannot use VSCode to debug with gdbserver on an android phone, even though using gdb on commandline works.
gdbserver exits as soon as VSCode connects, which in turn makes the debugger report that the target process has already exited.

**System**
- OS and Version: Linux Debian 4.19.37-2rodete1 
- VS Code Version: 1.31.1
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them): yes, disabling all other plugins yields same result.

**To Reproduce**
I start gdbserver on an Android phone with:

```
adb forward tcp:5039 tcp:5039;adb shell "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/data/local/tmp/testing/test;cd /data/local/tmp/testing;gdbserver64 --once :5039 ./dart --deterministic --optimization-counter-threshold=500 --enable-testing-pragmas --ignore-unrecognized-flags --packages=/usr/local/google/home/dacoharkes/dart-sdk/sdk/.packages /data/local/tmp/testing/test/out.dill"
```

Which prints

```
Process ./dart created; pid = 5780
Listening on port 5039
```

When attach with gdb manually (outside VSCode) it works:

```
~/flt/engine/src/third_party/android_tools/ndk/prebuilt/linux-x86_64/bin/gdb
...
(gdb) set sysroot .
(gdb) target remote :5039 // or target extended-remote :5039
Remote debugging using :5039
warning: Unable to find dynamic linker breakpoint function.
GDB will be unable to debug shared library initializers
and track explicitly loaded dynamic code.
0x0000007fb7ed36bc in ?? ()
(gdb) c
Continuing.
...
```

However, when I try to attach from VSCode the debug process exits immediately.

```
Process ./dart created; pid = 5878
Listening on port 5039
Remote debugging from host 127.0.0.1
Killing process(es): 5878
```

Giving a popup in VSCode with the following:

```
Unable to start debugging. The target process has exited.
```

launch.json:

```json
        {
            "name": "arm64",
            "type": "cppdbg",
            "request": "launch",
            "miDebuggerPath": "${workspaceFolder}/../../flt/engine/src/third_party/android_tools/ndk/prebuilt/linux-x86_64/bin/gdb",
            "miDebuggerServerAddress": ":5039",
            "program": "${workspaceFolder}/out/DebugAndroidARM64/dart",
            "cwd": "${workspaceFolder}/out/DebugAndroidARM64",
            "environment": [],
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Setup to resolve symbols",
                        "text": "set sysroot .",
                        "ignoreFailures": false
                    }
                ]
            },
            "engineLogging": true,
            "trace": true,
            "traceResponse": true 
        }
```

**Additional context**
No output in `output` or `debug console`.

**Comment by pieandcakes** [comment]
@dcharkes Can you enable the logging block? I see that you added the three properties to your launch.json but they need to be in a `"logging": {}` object.

```
"logging": {
            "engineLogging": true,
            "trace": true,
            "traceResponse": true 
}
```

**Comment by dcharkes** [comment]
@pieandcakes here is the output of logging: https://gist.github.com/dcharkes/c8791385ca1cd56649359a998ab00f24

**Comment by pieandcakes** [comment]
In the log I see the following two lines:

```
1: (486) ->&"/usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugAndroidARM64/.gdbinit:2: Error in sourced command file:\n"
1: (486) ->&"/data/local/tmp/testing/dart: No such file or directory.\n"
```
Do either of those errors mean anything to you? I don't know what is in the `.gdbinit` file or why its looking for the other file and if failing to find it is stopping debugging. 

We also see:
```
The program '/usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugAndroidARM64/dart' has exited with code 0 (0x00000000).
```
which seems to be what the error is telling us, that the target process has exited. I don't know if that is expected either.

**Comment by dcharkes** [comment]
Ah good spotting! I put the two commands in there that I used in the command line.

```
set sysroot .
target remote :5039
```

Without the `.gdbinit` it works like a charm! :+1: Thanks!
