### ISSUE TITLE
Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by isidord** [microsoft/vscode-cpptools#3773]
**Type: LanguageService**

**Describe the bug**

The extension doesn't work. 
I have the error message:

"Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined"

- OS and Version: win 10
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.23.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
I just installed VS Code and the c++ extension. It's my first use of VS Code.
Disabled/Reload/Re-Enable the extension is enough to see the error message.

Crtl-12 does nothing too.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/51825983/59512501-24dbf680-8eb9-11e9-9faf-366f476a84b4.png)

**Comment by sean-mcmanus** [comment]
Can you check the Toggle Developer Tool output to see if there's a call stack? We're not able to repro that -- do you know what could be special about your repro?

**Comment by Colengms** [comment]
@isidord Are you still seeing this issue?  Closing this, as we haven't heard back.  If you are still seeing an issue, please re-open.

**Comment by Lennon925** [comment]
@sean-mcmanus one of my workmate has the same issue with this. The latest extension verison and vscode. I don't know where is wrong.
