### ISSUE TITLE
Flag machine specific configurations like paths as machine scoped

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cpptools#3774]
I am developer from VS Code and we introduced Machine Scope for configurations in [1.34](https://code.visualstudio.com/updates/v1_34#_machinespecific-settings) which will help in [remote set ups](https://code.visualstudio.com/docs/remote/remote-overview).

I would like to encourage extension authors to adopt to machine scope if you have any settings that you think they are scoped to machine like `C_Cpp.clang_format_path` 

For example, If you have settings that allow users to customize an executable path that exists on the machine in which extension is running, then you can tag such settings as `machine` scoped. This will let VS Code to read this setting from the location where the extension is running.

- When extension is running locally, VS Code reads this setting **only** from User settings on the same machine.
- When extension is running remotely, VS Code reads this setting **only** from Remote settings on the remote machine.

If the extension is running remotely in a [remote set up](https://code.visualstudio.com/docs/remote/remote-overview), then this will help the extension not to read paths configured in local machine user settings and bail as the paths not exist in the remote machine.

Note that machine scoped settings are overridable only in user or remote settings.

**Comment by sean-mcmanus** [comment]
@sandy081 I have a pull request at https://github.com/microsoft/vscode-cpptools/pull/3810, but I don't understand how to test it or observe a change, because for both resource and machine scopes. And the only documentation I could find is at https://code.visualstudio.com/updates/v1_34#_machinespecific-settings .

**Comment by sean-mcmanus** [comment]
@sandy081 Oh -- I see that the settings with "machine" scope cause the setting to not appear under the Workspace and Folder UI. Are there other differences?

**Comment by sandy081** [comment]
As mentioned machine scope setting has two characteristics

1. It cannot be overridable at workspace/folder level
2. In remote set up, value defined in user settings is ignored.

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0.
