### ISSUE TITLE
0.24.0-insiders - Syntax colorization showing incorrect background color for highlighted lines

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#3780]
**Type: LanguageService**

Some themes highlight the selected line with a color that doesn't match the unselected lines' background color.  In these cases the new syntax highlighting doesn't honor the theme.  This affects multiple themes.

It gets more visible when you select things:
![image](https://user-images.githubusercontent.com/12818240/59547339-40172800-8ef2-11e9-9a3a-81e9de085389.png)

To disable the new syntax highlighting, set `"C_Cpp.enhancedColorization": "Disabled"` and you will get the old behavior again.

Themes with known issues:
* Abyss
* Monokai
* Monokai Dimmed
* One Monokai
* Red
* Quiet Light
* Solarized Dark
* Solarized Light
* Tomorrow Night Blue

**Comment by heimskr** [comment]
I'm having this issue too for the same set of themes. It also affects my usual theme, unfortunately. I have a lot of other themes installed too (too many, really—still trying to find the perfect theme) and I went through them to check which ones are affected. I first started experiencing the issue within the past few hours or so. Before then, everything worked fine.

Affected:
- Abyss
- Clymate Pop Neon
- Flatland Monokai
- Kimbie Dark
- Material Theme (default, Darker, Darker High Contrast, High Contrast, Ocean, Ocean High Contrast, Palenight, Palenight High Contrast)
- Monokai
- Monokai Dark Soda
- Monokai Dimmed
- Monokai++
- One Monokai
- Palenight (Italic, Operator, Theme)
- Quango Classic
- Red
- Reed Alert
- sandstorm - classic
- Solarized (Dark, Light)
- Spirited Away (my usual theme :-/)
- Tomorrow Night Blue


Not affected:
- Atom One Dark
- Clymate, Clymate Monochrome, Clymate Vintage
- Cyberpunk+
- Dark (Visual Studio)
- Dark Wiwa
- Dark+ (default dark)
- Electron
- Hackz, Hackz Darker
- Henna
- Radical
- sandstorm - darker
- Sidious
- skGRTT
- Spotify
- High Contrast

Thanks for the workaround!

**Comment by Colengms** [comment]
Please up-vote the following issue: https://github.com/microsoft/vscode/issues/75642

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders2. Set the "C_Cpp.updateChannel" setting to "Insiders" to auto-install it.
