### ISSUE TITLE
0.24.0-insiders - Noticeable latency with enhanced colorization

### ISSUE THREAD

**Issue by notAlaanor** [microsoft/vscode-cpptools#3781]
**Type: LanguageService**

With Enhanced Colorization enabled there is a noticeable amount of latency when typing and simply moving around the document.

Disabling Enhanced Colorization immediately fixes this issue.

Note: Is this a flaw of using the Decorations API?

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders2. Set the "C_Cpp.updateChannel" setting to "Insiders" to auto-install it.

Let us know if you're still seeing lag issues. After scrolling > 150 lines, it's expected there might be a slight lag in the semantic colors being updated.

**Comment by notAlaanor** [comment]
The performance has improved tremendously (scrolling through a 600+ line file).

Thanks for the work on this extension.
