### ISSUE TITLE
shows problem for __gcd(num1, num2)

### ISSUE THREAD

**Issue by raiadi2008** [microsoft/vscode-cpptools#3783]
Issue Type: <b>Bug</b>

the __gcd(num1, num2) shows error in problem section how ever its a part of algorithm standard header which i have explicitly mentioned in the program but still it shows error however compilation gives no problem at all

Extension version: 0.23.1
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.18GB free)|
|Process Argv|C:\Users\aditya\Desktop\practice\gcd.cpp|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by raiadi2008** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/49565745/59554949-cd2cb080-8fc8-11e9-91ea-df08d9e80557.png)
this is one of the sample

**Comment by sean-mcmanus** [comment]
What implementation of algorithm are you using? What language standard? I'm seeing std::gcd being part of the numeric header with C++ 17. I don't see __gcd in algorithm. If you do a C/C++: Log Diagnostics command you can see what includePath and compiler is being used. You might be using the wrong library that doesn't have __gcd defined. Also, it would help to provide the text of the "problem" so we can verify it's from our extension or not.

**Comment by raiadi2008** [comment]
Intelli sense Mode : msvc-x64,
adding the numeric header does no help.
changed the c++ standard to c++17.
issue still exist

**Comment by raiadi2008** [comment]
> What implementation of algorithm are you using? What language standard? I'm seeing std::gcd being part of the numeric header with C++ 17. I don't see __gcd in algorithm. If you do a C/C++: Log Diagnostics command you can see what includePath and compiler is being used. You might be using the wrong library that doesn't have __gcd defined. Also, it would help to provide the text of the "problem" so we can verify it's from our extension or not.

i don't understand the statement "what implementation of algorithm are you using?" probably cuz i am just a 2nd year student at my college.

**Comment by sean-mcmanus** [comment]
It sounds like you're using the MSVC implementation. Do you know what version? I don't believe __gcd is implemented by the MSVC headers. If you're intending to compile with gcc/clang headers instead, you should set your compilerPath to your compiler you're using (and change the intelliSenseMode).

**Comment by raiadi2008** [comment]
thank you, changing the intellisense mode to clang or gcc completely resolves my problem
