### ISSUE TITLE
Broken highlight selection

### ISSUE THREAD

**Issue by pLago123** [microsoft/vscode-cpptools#3784]
Issue Type: <b>Bug</b>

version 0.24 cannot display highlighter when selecting text for this extension. I have to rollback to the previous 0.23.1

Extension version: 0.23.1
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by shalva97** [comment]
same problem here, default themes are ok but all others are broken
![image](https://user-images.githubusercontent.com/22417494/59556405-1bdf4800-8fd3-11e9-871f-f86a96b9c0e9.png)

**Comment by hmarcuzzo** [comment]
Same problem here!

**Comment by bobbrow** [comment]
Thanks for reporting this issue. We are tracking it with #3780.
