### ISSUE TITLE
Issue with externalConsole when Debugging via SSH

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode-cpptools#3788]
- Type: Debugger
- OS and Version: macOS 10.14.4
- VS Code Version: 1.36.0-insider (f291714906cdcb02830b8cfe2485a3c23415b5fe)
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them): Remote - SSH

If I connect to a Linux system from Mac using the `Remote - SSH` extension, and then I try to debug a C++ program using this extension it works fine if I have `externalConsole: false` in `launch.json`. If it is true it just displays a progress bar forever and never does anything (nothing is printed in the Debug Console log either).

`launch.json`:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Test",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/../build/test",
      "args": ["some", "args"],
      "stopAtEntry": false,
      "cwd": "${workspaceRoot}/../build",
      "environment": [
        {
          "name": "LD_LIBRARY_PATH",
          "value": "${workspaceRoot}/../build"
        }
      ],
      "externalConsole": false,   // Doesn't work if this is true (the default).
      "MIMode": "gdb",
      "setupCommands": [
          {
              "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": true
          }
      ]
    }
  ]
}
```

**Comment by WardenGnaw** [comment]
Issue can be due to runInTerminal with remote-ssh. Reported an issue at https://github.com/microsoft/vscode-remote-release/issues/723
