### ISSUE TITLE
Debugger: show integer types in multiple ways: hex, dec, ascii, binary

### ISSUE THREAD

**Issue by jpap** [microsoft/vscode-cpptools#379]
It looks like variables in the debugger are based on their type -- but when using `uint8_t` they show up as `char`, when what I really want to see is the decimal value.

It would be nice to show all alternate forms of a variable -- hex, dec, ascii, binary -- or have a way to switch between types in the UI.

The only (tedious) way to do this now is to use the debug console and typecast to `(int)` for example.

**Comment by pieandcakes** [comment]
@jpap This is the same as #319 . You can specify common variables in the Watch window. You can find format specifiers and you can find the format specifiers [here](https://sourceware.org/gdb/onlinedocs/gdb/Output-Formats.html#Output-Formats).

For example for `double dbl` I added `dbl,h` to the Watch window and it displayed the value of `dbl` in hex.

**Comment by rpavlik** [comment]
FWIW, this does not appear to work with memory addresses in hex (such as debugging on an MCU) - no permutation of h or x, a delimiter like , or /, and the address, would display any value.
