### ISSUE TITLE
Highlighting screwed up

### ISSUE THREAD

**Issue by jpan127** [microsoft/vscode-cpptools#3790]
Issue Type: <b>Bug</b>

The most recent update caused many themes to invert the highlighting of text.  If I highlight a block of text, many of the tokens are not highlighted, but the spacing is.  I have tried a few themes and they are broken now.

Extension version: 0.24.0-insiders
VS Code version: Code - Insiders 1.36.0-insider (15b7c86d86319b187a5ef255c170184a8519c5af, 2019-06-14T10:33:50.651Z)
OS version: Linux x64 4.15.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz (32 x 971)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|45.89GB (6.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
This is a dupe of: https://github.com/microsoft/vscode-cpptools/issues/3780

To disable the new syntax highlighting, set "C_Cpp.enhancedColorization": "Disabled" and you will get the old behavior again.

The underlying VS Code issue is here: https://github.com/microsoft/vscode/issues/75642

**Comment by jpan127** [comment]
Thank you, will close.

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders2. Set the "C_Cpp.updateChannel" setting to "Insiders" to auto-install it.
