### ISSUE TITLE
C++ for mac won't download or show in visual studio 

### ISSUE THREAD

**Issue by jsss333** [microsoft/vscode-cpptools#3794]
Downloaded it on Visual studio code but its not showing up when i launch VS? I have even tried parallels and visual box, nothing is working

**Comment by michelleangela** [comment]
@jsss333 , are you referring to [Visual Studio for Mac](https://visualstudio.microsoft.com/vs/mac/)? Visual Studio for Mac does not support C++. You can upvote the feature request at https://developercommunity.visualstudio.com/content/idea/356171/support-projects-with-c-c14-c17-language-with-inte.html

**Comment by bobbrow** [comment]
We need more information to fully investigate this issue. If you update to the latest version of the extension and your issue persists, please reply with additional information that can help us investigate your issue.
