### ISSUE TITLE
Format on save creates gibberish

### ISSUE THREAD

**Issue by Shachlan** [microsoft/vscode-cpptools#3796]
macOS 10.14.15
VSCode 1.35.1 (also seen on previous versions)
C/C++ version: 0.23.1 (also seen on previous versions)
Other extensions - 
alesiong.clang-tidy-linter
austin.code-gnu-global
CADENAS.vscode-glsllint
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
eamodio.gitlens
eg2.vscode-npm-script
esbenp.prettier-vscode
firsttris.vscode-jest-runner
formulahendry.docker-explorer
ms-vscode.cpptools
msjsdiag.debugger-for-chrome
oderwat.indent-rainbow
PeterJausovec.vscode-docker
psioniq.psi-header
sburg.vscode-javascript-booster
sdras.night-owl
slevesque.shader
smulyono.reveal
VisualStudioExptTeam.vscodeintellicode

Happens also when other cpp extensions are disabled.

VScode auto-formats on save using clang-format, and adds garbage to the code file - random characters and words. This happens repeatedly - saving the file multiple times in a row without doing anything in-between still adds garbage on every save.
demonstration video - https://youtu.be/zxPHINAk9Tw

This is an occasional issue, so I don't know how to repro it. removing the ipch folder doesn't help. There are no special logs in the Output window.

**Comment by sean-mcmanus** [comment]
Formatting works "in general", but it sounds like you're hitting an "unsupported scenario". Are you using a multi-root workspace? Does the Format Document command have the same effect? I would recommend setting the C_Cpp.formatting to Disabled and trying another C++ formatting extension to see if they have the same problem or not.

**Comment by Shachlan** [comment]
I'm using a regular workspace, and I'll try to repro manually.
Do you have a suggestion for an alternative formatting extension?

**Comment by sean-mcmanus** [comment]
I think the other known problem can occur if you open a symlinked folder.

The only other formatting extension I'm familiar with is the "clang-format" extension.

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
