### ISSUE TITLE
[windows] [Visual C++] Unable to open 'exe_common.ini' error when stepping over

### ISSUE THREAD

**Issue by YangJiao1996** [microsoft/vscode-cpptools#3797]
Type: Debugger
**Input information below**

**Describe the bug**
- OS and Version: Windows 10.0.17763
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.24.0-insiders
- Other extensions you installed (and if the issue persists after disabling them): 

| Extention | Version | If disabling works
|--------------------------|-----------------| -------|
| Anaconda Extension Pack | 1.0.1 | No
| Bracket Pair Colorizer 2 | 0.0.28 | No
| C/C++ | 0.24.0-insiders | N/A
| C++ Intellisense | 0.2.2 | No
| Clang-Format | 1.9.0 | No

- A clear and concise description of what the bug is.
The error occurs when stepping over the line after "return 0" (which is actually a curly bracket) in the main function. 
Error information is: 
```
Unable to open 'exe_common.inl': Unable to read file (Error: File not found 
(d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl)).
```
The program does not exit until I hit the Step Over button for 3 times, while the error messages keep popping out.
**To Reproduce**
**Code Sample**:
```
#include <iostream>

int main(){
    int a = 0;
    for(int idx = 0; idx < 10; idx++){
        a++;
        std::cout << a << std::endl;
    }
    std::cout << "Hello world!" << std::endl;
    return 0;
}
```
The `launch.json`, `tasks.json` and even `c_cpp_properties.json` files are basicly the same as the [tutorial](https://code.visualstudio.com/docs/cpp/config-msvc).
1. Create the `tasks.json` and `launch.json` as in the [link](https://code.visualstudio.com/docs/cpp/config-msvc)
2. Hit `Ctrl+Shift+B` to compile
3. Hit `F5` to debug
4. Keep hitting `F10`

**Additional context**
- The error message is quite interesting since I do not even have a `D:\` disk on my computer
- According to [this link](), this could be an issue with Visual Studio where the `exe_common_inl`, file is missing, but I could locate the file under `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\crt\src\vcruntime`.
- My Visual Studio version is 15.9.13, I reinstalled Visual Studio, but it doesn't work.
- Other error messages were printed in the debug console:
```
Loaded 'C:\Windows\SysWOW64\kernel.appcore.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\sechost.dll'. Cannot find or open the PDB file.
```
But all the `dll` files above could be located in my `C:\Windows\SysWOW64\` directory.

**Comment by pieandcakes** [comment]
@YangJiao1996 This error is because the top frame in the callstack is in the VC runtime and you don't have the necessary files to debug it. You can ignore this error and select a line in the callstack where your code exists.

**Comment by pieandcakes** [comment]
The other errors are because you don't have the symbol files (`.pdb`) for them and is also expected.

Your link points to this issue.

**Comment by YangJiao1996** [comment]
@pieandcakes Got it. Thank you!

**Comment by valdersea** [comment]
If you want to load those symbols , you can add
`"symbolsearchpath"="https://msdl.microsoft.com/download/symbols"`
to launch.json. Then vscode will download those symbols wanted when debugging automaticly.

**Comment by tyeth** [comment]
> "symbolsearchpath"="https://msdl.microsoft.com/download/symbols"

"symbolsearchpath": "https://msdl.microsoft.com/download/symbols",

and I stuck it above my configurations section.

**Comment by delicacyyy** [comment]
> If you want to load those symbols , you can add `"symbolsearchpath"="https://msdl.microsoft.com/download/symbols"` to launch.json. Then vscode will download those symbols wanted when debugging automaticly.

![image](https://github.com/microsoft/vscode-cpptools/assets/11476249/af9df1f3-1fa5-4379-b700-f043ff210566)

Regrettably, the contraption continues to malfunction despite my adherence to your instructions.

**Comment by ilev4ik** [comment]
Faced the same issue. @valdersea's solution (on Nov 19, 2020 ) didn't fixed the problem
