### ISSUE TITLE
"-imacros"  in compile_commands.json-parsing ignored

### ISSUE THREAD

**Issue by bjda** [microsoft/vscode-cpptools#3798]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1803 17134.706
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.24.0-insiders
- Other extensions you installed (and if the issue persists after disabling them): None

The extension does not seem to care about defines included in compilation through the -imacros flag in compile_commands.json. The specific context is using the Zephyr CMake build system.

**To Reproduce**

* Use a compile_commands.json with the "-imacros some_header.h" flag
* Observe error squiggles on sympols defined in the file. The file is not mentioned in cpptools' debug output.

**Expected behavior**
Macros loaded correctly from included header, similar to "forcedInclude"s behaviour.

**Comment by sean-mcmanus** [comment]
See https://github.com/microsoft/vscode-cpptools/issues/2417.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders
