### ISSUE TITLE
Do not collapse local variable struct view when executing on debug console

### ISSUE THREAD

**Issue by jpap** [microsoft/vscode-cpptools#380]
If I have expanded a `struct` variable when sitting on a breakpoint, then execute a command in the debug console, that expansion is collapsed.  That's really frustrating, especially when the manual expansion is rather deep into a complex `struct`. 

Please keep the variables hierarchical UI state fixed while refreshing it following a debug console execution step.

**Comment by pieandcakes** [comment]
@jpap I think that's a "feature" of VSCode as I don't see a way to override this experience. You may want to file an issue in their repository at https://github.com/Microsoft/vscode/issues. I did notice that if you add the same `struct` to the Watch window that it respects the expansion and keeps it expanded when you step. 

HTH
