### ISSUE TITLE
提示c/c++已经更新到0.24.0版本，reload后没有生效

### ISSUE THREAD

**Issue by lujfsd** [microsoft/vscode-cpptools#3800]
Issue Type: <b>Bug</b>

在WSL中，系统提示"The C/C++ Extension has been updated to version 0.24.0-insiders. Please reload the window for the changes to take effect.",点击reload后，没有生效。会一直提示
![1560993752(1)](https://user-images.githubusercontent.com/3353399/59811539-f6d53700-933c-11e9-9a0b-ab0b7e6ff2c0.jpg)

Extension version: 0.23.1
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.85GB (1.98GB free)|
|VM|67%|
</details>

**Comment by sean-mcmanus** [comment]
What is your question? You can set the C_Cpp.updateChannel to "Default" to switch back to 0.23.1.

**Comment by lujfsd** [comment]
new version 0.24.0 is not effect after reload.

**Comment by sean-mcmanus** [comment]
Do you mean the pop up keeps re-appearing? If you can check the extensions folder to see if the 0.23.1 and/or 0.24.0-insiders folder are still there that would help.

**Comment by lujfsd** [comment]
yes. it's re-appear.my extensions folder as below:
![1560997003(1)](https://user-images.githubusercontent.com/3353399/59813546-84685500-9344-11e9-9062-c139e0ab5516.jpg)
just 0.23.1

**Comment by sean-mcmanus** [comment]
Okay, it looks like the download/install is failing for some unexpected reason and we don't handle the error well. Until we're able to figure out a fix, your best option is to change the updateChannel setting. The code that is causing this failure is open source if you feel like debugging it yourself with our release branch, but you'd have to change the "testingInsidersVsixInstall" variable to "true" in githubAPI.ts.

**Comment by lujfsd** [comment]
OK，Thanks

**Comment by sean-mcmanus** [comment]
This issue should be fixed starting with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3 .
