### ISSUE TITLE
Watching for file changes outside the workspace folder

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode-cpptools#3802]
Intellisense does not detect changes to header files that are not in the workspace folder. I have to reload vscode for it to work.

Most of our header files are generated when building and are placed outside the workspace folder. When a function signature changes or a new member is added in a header file, intellisense will not update unless vscode is reloaded.

The path of the include files is in the includePath and browse.path of my c_cpp_properties.json.

**Comment by sean-mcmanus** [comment]
0.24.0-insiders added a Rescan Workspace command, which is a manual workaround.

I think the fix would involve add fs.watch calls for browse.path/includePath outside of the workspace (preferably avoiding dups).

A related issue is https://github.com/microsoft/vscode-cpptools/issues/4211 -- we don't handle "change" events even for files in the workspace.
