### ISSUE TITLE
Weird text appears when format on save is used

### ISSUE THREAD

**Issue by TheGreatRambler** [microsoft/vscode-cpptools#3809]
cpp file
```
{
	"configurations": [{
		"name": "Win32",
		"includePath": [
			"${workspaceFolder}/include/**",
			"${workspaceFolder}/**"
		],
		"defines": [
			"_DEBUG",
			"UNICODE",
			"_UNICODE"
		],
		"compilerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",
		"cStandard": "c11",
		"cppStandard": "c++11",
		"intelliSenseMode": "gcc-x64"
	}],
	"version": 4
}
```

ajshort.include-autocomplete   
ban.spellright                 
brunnerh.file-properties-viewer
CoenraadS.bracket-pair-colorize
dbaeumer.vscode-eslint         
formulahendry.code-runner      
Gruntfuggly.todo-tree          
HookyQR.beautify               
ms-python.python               
ms-vscode.cpptools             
msjsdiag.debugger-for-chrome   
PhilHindle.errorlens           
redhat.java                    
shakram02.bash-beautify        
shinnn.stylelint               
sleistner.vscode-fileutils     
twxs.cmake                     
vscode-icons-team.vscode-icons 
xaver.clang-format             
yzhang.markdown-all-in-one     
ziyasal.vscode-open-in-github  

I had clang format and removed it to see if anything could be fixed, but nothing helped.

I have a multi root workspace (a root folder and the other root is a child folder) if that helps.

My issue is similar to this person's issue. #3796 

Here is a screenshot:

![search](https://user-images.githubusercontent.com/31906920/59879642-2d30a780-9379-11e9-833d-333c1c31da91.gif)

**Comment by TheGreatRambler** [comment]
Here is my clang format file

```
---
BasedOnStyle: WebKit
AllowShortBlocksOnASingleLine: 'false'
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: 'false'
AllowShortLoopsOnASingleLine: 'false'
BreakBeforeBraces: Attach
ColumnLimit: '500'
ConstructorInitializerAllOnOneLineOrOnePerLine: 'true'
IndentWrappedFunctionNames: 'true'
MaxEmptyLinesToKeep: '2'
NamespaceIndentation: All
PointerAlignment: Left
SpaceBeforeParens: Never
SpaceInEmptyParentheses: 'false'
SpacesInAngles: 'false'
Standard: Cpp11
TabWidth: '4'
UseTab: Always
IndentCaseLabels: 'true'
SpaceAfterCStyleCast: 'true'
SpaceBeforeParens: ControlStatements
...
```

**Comment by sean-mcmanus** [comment]
I think this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/1073 (and others?) .

**Comment by TheGreatRambler** [comment]
I do, in fact, have a multi-root workspace organized that way. WOW! Reducing the roots of my workspace to 1 have actually fixed many errors! Previously, my intellisense wouldn't update and I would have errors stick around for no apparent reason, but that is now fixed. MY header detection works now! I think I will submit a pull request to add a warning against multi-root workspaces on the readme. Thank you!
