### ISSUE TITLE
Include file not found under Win32 and MinGW

### ISSUE THREAD

**Issue by wuqiling97** [microsoft/vscode-cpptools#381]
When using vscode version 1.7.2 and cpptool 0.9.2 with the following include headers:

```c++
#include <iostream>
#include <chrono>
#include <stdio.h>
#include <cstdlib>
```

and settings in "c_cpp_properties.json":

```json
        {
            "name": "Win32",
            "includePath": ["c:/MinGW/lib/gcc/mingw32/5.3.0/include", "C:/MinGW/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        }
```

I still got green squiggles under those headers. However, these c++ code worked fine in another directory without "c_cpp_properties.json", and vscode will take me to "Microsoft Visual Studio 14.0\VC\include" when I ctrl+click on these headers.

Could someone figure it out?

**Comment by BillDenton** [comment]
I have the same problem with #include <streambuf>. I'm using MSVS2005 with "c_cpp_properties.json" with "includePath": ["c:/Program Files (x86)/Microsoft Visual Studio 8/VC/include"],. It shows "include file not found in directory". I presume this is related to these files not having an extension (see https://github.com/Microsoft/vscode-cpptools/issues/406)

**Comment by wuqiling97** [comment]
@BillDenton 
<stdio.h> has an extension but still gets green squiggles. Maybe it has nothing to do with extension

**Comment by BillDenton** [comment]
<stdio.h> works for me. I've got appropriate include path for my compiler in "c_cpp_properties.json". Have you got the include path?

**Comment by sean-mcmanus** [comment]
Which #include file repros the bug? Like "#include \<string\>"?

**Comment by wuqiling97** [comment]
When I work in certain directories, all the headers will reproduce this bug. 
![1](https://cloud.githubusercontent.com/assets/19304928/21576165/7a21917e-cf60-11e6-9214-4878f913b96b.png)

But in other directories, headers like \<climits\>, \<vector\>, \<algorithm\> will have green squiggles.
![2](https://cloud.githubusercontent.com/assets/19304928/21576169/aaab57ee-cf60-11e6-8a6e-7dca47a585d0.png)

Yet some directories don't have this bug.
![3](https://cloud.githubusercontent.com/assets/19304928/21576173/c548cd70-cf60-11e6-9aeb-41cbe85a6d4a.png)

**Comment by sean-mcmanus** [comment]
Is the Win32 configuration not red all these times? Is there something special about the directories that repro the bug? We'll do more testing with MinGW later to try to repro the issue.

**Comment by wbogocki** [comment]
I get the same bug. It occurs with include paths for both MinGW and VC++. I don't see any red about the Win32 configuration. The directories are the usual ones:

MinGW:
- C:/MinGW/lib/gcc/mingw32/5.3.0/include/c++
- C:/MinGW/include

VC++:
- C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include

**Comment by sean-mcmanus** [comment]
Is anyone still having problems with headers not being found? 0.10.3 has bug fixes related to this.

**Comment by wbogocki** [comment]
I can confirm that it's fixed for me. I'm unsure if it's because of the patch or something else but it randomly started working last month. Anyhow, thanks! :)

**Comment by wuqiling97** [comment]
Thanks! The version 0.10.2 has fixed this bug.
