### ISSUE TITLE
extension escalation error

### ISSUE THREAD

**Issue by chenlhuawei** [microsoft/vscode-cpptools#3811]
[Error - 上午8:39:13] Connection to server got closed. Server will not be restarted.
[Error - 上午8:39:14] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\chenl\.vscode\extensions\ms-vscode.cpptools-0.24.0-insiders\dist\main.js:2556:22)

**Comment by sean-mcmanus** [comment]
This should be fixed in our next Insiders, either Friday or Monday: https://github.com/microsoft/vscode-cpptools/issues/3792 .

Until we have a fix, you can change C_Cpp.updateChannel to "Default" to use the non-Insiders build.

**Comment by chenlhuawei** [comment]
thanks,i will try it

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders2. Set the "C_Cpp.updateChannel" setting to "Insiders" to auto-install it.
