### ISSUE TITLE
UI feature request: show status of parsing/indexing

### ISSUE THREAD

**Issue by koenlek** [microsoft/vscode-cpptools#3813]
**Type: LanguageService**

**Issue**
Currently, it's hard to tell what the status of workspace parsing/indexing is. 
When opening a very large workspace, this can take many minutes or even hours. However, apart from seeing a busy process in a process manager like htop, I found no way to see if indexing is ongoing. Moreover, originally I wasn't even aware that parsing was ongoing, I just figured out that probably manual configuration was needed to get IntelliSense working for my workspace.

I noticed that among myself and colleagues, this caused quite some confusion. Opening a workspace in VS Code and seeing that IntelliSense doesn't work, made me embark on a long quest for finding the right configuration (through `c_cpp_properties.json` and `settings.json`). At some point, that kinda worked and I thought it was thanks to my hard work. Until I found out that another colleague had a perfectly working setup without adding any custom configuration. 

**Proposed Solution**
How about a spinning progress icon in the bottom bar while parsing is ongoing? If you hover over it, it shows "IntelliSense Parsing ongoing", if you click on it, you can choose "Pause Parsing", "Resume Parsing", "Show Parsing Commands" or "Rescan Workspace" (as of v0.24). 

If you want to add "Rescan Workspace" behind the icon, it probably makes sense to always have it their (spinning while parsing, maybe just a checkmark or green dot when finished). 

**Describe the bug**
- OS and Version: Ubuntu 18.04 x64
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.23.1

**Comment by koenlek** [comment]
Ok. Just spotted the "updating intellisense" icon in the bottom right corner... Not sure how I couldn't have seen that before...

**Comment by DeltaRazero** [comment]
I would've liked if it could be disabled though, it gets fairly annoying since moves the other icons on the status bar left of it every time it is updating

**Comment by sean-mcmanus** [comment]
We're adding a 3rd progress UI for Find All References (might not have any icon though) -- it might be a good idea to create 1 progress icon that incorporates all 3 status.

The database icon is for "tag parsing" and the red flame is for IntelliSense updating. Both could use some improvement.

VS Code Insiders allows removing all the C/C++ status bar info in the right-click options, but not on a per-item basis.

**Comment by bobbrow** [comment]
We're tracking the possibility of consolidating the icons with #4117
