### ISSUE TITLE
Can the latest VSCode support the debug for multi-process in c++?

### ISSUE THREAD

**Issue by JWleo** [microsoft/vscode-cpptools#3817]
@WardenGnaw 
if yes. How to do it?
Please give a hint.
Thank you!

**Comment by WardenGnaw** [comment]
Are you debugging multiple processes or are you wanting to debug child processes?

**Comment by JWleo** [comment]
### the code just like this:

```c++
#include "mpi.h"
#include <iostream>
using namespace std;
int main(int argc, char *argv[]) {
	int rank, size;
	MPI_Init(&argc, &argv);
	MPI_Comm_rank(MPI_COMM_WORLD, &rank); 
	MPI_Comm_size(MPI_COMM_WORLD, &size);   
	if(0 == rank) {
                // do case A
	} else if(1 == rank) {
		// do case B
	}
	//... do others
	MPI_Finalize();
	return 0;
} 
```

### when debugging this one,i need to know the change of data in each processes with running. Data in each processes don't share same memory.

###  If i did't describe it clearly, And you can check [**other cases**](https://stackoverflow.com/questions/329259/how-do-i-debug-an-mpi-program) to understand.

**Comment by WardenGnaw** [comment]
We currently do not have this feature yet. The request is at https://github.com/microsoft/vscode-cpptools/issues/1723

**Comment by JWleo** [comment]
Thank you for answering.
