### ISSUE TITLE
Why does 'Go to definition' show the 'Peek definition' popup?

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#382]
Running VS Code 1.7.2 on Windows 10 with C++ extension 0.9.2.

When I invoke 'Peek definition' on a symbol the definition appears in a popup. That is good.

When I invoke 'Go to definition' on a symbol, the editor opens a new tab with the file containing the definition - that is good.  But the definition also appears in a popup, which I think is unnecessary and even obstructive. Do you agree?

**Comment by csholmq** [comment]
Even when it's just only one match?

**Comment by daldr-ntml** [comment]
Thanks for your reply. You're right, often the reason is that there are multiple matches from competing projects. 

However, I found one case where there is only one match but the C++ extension reports 3 matches. Two of the matches were shown in upper case on the right-hand side and, when expanded, show no definition (the number beside is 0). These look like old definitions that no longer exist. Am I right? How can I refresh the symbol database?

**Comment by sean-mcmanus** [comment]
Change the databaseFilename setting after Edit Configuration to refresh the symbol database (or manually locate and delete it). I have also noticed the browse engine database doesn't delete things it should when include paths are changed.

**Comment by daldr-ntml** [comment]
> Change the databaseFilename setting after Edit Configuration to refresh the symbol database

Sorry I don't understand this.  Is this a setting in c_cpp_properties.json?

**Comment by sean-mcmanus** [comment]
Yes.

**Comment by daldr-ntml** [comment]
Where can I find the json schema that shows the available properties?

My c_cpp_properties.json doesn't have an entry for the database, it seems to be stored in my user profile. Is that what you would expect?

**Comment by sean-mcmanus** [comment]
The schema should be at the install location (e.g. /home/user/.vscode/extensions/ms-vscode.cpptools-0.9.2) in c_cpp_properties.schema.json.

Maybe you have an old c_cpp_properties.json? I have entries like
{
            "name": "Linux",
            "includePath": ["/usr/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : "/home/user/Desktop/Project/.vscode/.browse2.vc.db"
            }
},

I don't understand what you mean by the database entry being in your user profile.

**Comment by daldr-ntml** [comment]
Well I am stuck on 0.9.2, I haven't seen a new release since September (I am not using the Insider's build).

**Comment by sean-mcmanus** [comment]
Yes, we're working on an update, but 0.9.2 should still have the databaseFilename.

**Comment by daldr-ntml** [comment]
I deleted my json file and regenerated it. Now I see the databaseFilename property.  All seems to be working ok now. Thanks for your help and for bearing with me.

Perhaps the documentation page could be updated to described all the supported json properties?

**Comment by daldr-ntml** [comment]
Problem solved.
