### ISSUE TITLE
How to highlight erros in visual studo code editor for c++ language?

### ISSUE THREAD

**Issue by shravankgit** [microsoft/vscode-cpptools#3820]
Issue Type: <b>Bug</b>

Could you please answer the following question, I wrote everything in that question.

How to highlight erros in visual studo code editor for c++ language?

https://stackoverflow.com/questions/56730323/how-to-highlight-erros-in-visual-studo-code-editor-for-c-language

I tried everything like downgrading `vscode` and `C/C++ IntelliSense` version etc, but not achieved.

please help me.

Extension version: 0.23.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 3310)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.55GB (8.85GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sean-mcmanus** [comment]
You should disable the "C/C++ IntelliSense" extension and set intelliSenseEngineFallback to "Disabled". Does that fix it?

**Comment by bobbrow** [comment]
We need more information to fully investigate this issue. If you update to the latest version of the extension and your issue persists, please reply with additional information that can help us investigate your issue.
