### ISSUE TITLE
c_cpp_properties.json

### ISSUE THREAD

**Issue by wedizeru** [microsoft/vscode-cpptools#3822]
I’m trying to set up my VS code so i can start coding CPP. I was using a youtube video as a guide to help me set this thing up but when i got to the part that talks about the c_cpp_properties.json i got confused because the person’s and mine outlook didn’t match and i try to use other source include the VS code website but that didn’t help as well. I will attach what mine looks like so you help me. I would appreciate if you could also attach an image that shows how to fix the issue.

![cpp](https://user-images.githubusercontent.com/52183278/60060621-5a959200-96a6-11e9-9c84-bc7cc7a08ba5.PNG)

**Comment by sean-mcmanus** [comment]
I don't understand. What issue needs to be fixed? What setting do you need help setting?

**Comment by wedizeru** [comment]
i just want to set up VS code for CPP.

**Comment by wedizeru** [comment]
im not sure what extension to add or what other steps to take so i used a youtube video as a reference to help me set it up.

**Comment by sean-mcmanus** [comment]
What compiler are you using to build? Or which compiler do you want to use, e.g. cl, clang, or gcc?

**Comment by wedizeru** [comment]
Gcc

**Comment by sean-mcmanus** [comment]
If you're using Mingw/gcc, see https://code.visualstudio.com/docs/cpp/config-mingw . The page has links to help for cl.exe and WSL compilers as well.

**Comment by sean-mcmanus** [comment]
Our extension is the "C/C++" extension.

**Comment by wedizeru** [comment]
i followed the steps you shared from the website but im having a trouble with my launch.json. it says that "matches multiple schemas when only one must validate". I don't understand what this mean 

![Capture](https://user-images.githubusercontent.com/52183278/60132421-4dcd7880-9750-11e9-8a20-107898198f80.PNG)

**Comment by sean-mcmanus** [comment]
That is strange. I don't get that error. It could be caused by another extension you have installed? @pieandcakes @WardenGnaw Have you seen this error before?

**Comment by pieandcakes** [comment]
No I haven't, If you can provide the list of extension you have installed, that would help.

**Comment by wedizeru** [comment]
i've only installed c/c++ extension

**Comment by pieandcakes** [comment]
Can you check your `c:\\users\\<username>\\.vscode\\extensions` folder and tell me what you see in there?
