### ISSUE TITLE
Warning: Path is not a file: AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\bin\gcc, despite IntelliSense working

### ISSUE THREAD

**Issue by fefrei** [microsoft/vscode-cpptools#3825]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1903
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them): None

I'm getting this warning when trying to set `"compilerPath": "/usr/bin/gcc"`:

    Path is not a file: "C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\bin\gcc".

The warning is actually incorrect: This file exists, and IntelliSense works fine. If I remove `"compilerPath": "/usr/bin/gcc"` from my configuration, IntelliSense no longer works, and I get build errors, so the configuration is used despite this warning.

**To Reproduce**

I'm pretty sure these steps don't suffice, but here's what I did:

1. Install Ubuntu through WSL.
1. Create this `c_cpp_properties.json`:
    ```
    {
        "configurations": [
            {
                "name": "tool",
                "defines": [],
                "compilerPath": "/usr/bin/gcc",
                "cStandard": "c11",
                "cppStandard": "c++17",
                "intelliSenseMode": "gcc-x64"
            }
        ],
        "version": 4
    }
    ```

That's it.

**Screenshots**

![image](https://user-images.githubusercontent.com/3078885/60080921-14394500-9731-11e9-86ba-25d360fe28cd.png)

**Comment by sean-mcmanus** [comment]
I don't repro this problem, with Ubuntu or Ubuntu 18.04. The only way I was able to repro it was when I did not have gcc installed. Can you run the C/C++: Log Diagnostics command to see what gcc path it is using when you use the "/usr/bin/gcc"?

**Comment by fefrei** [comment]
This is the output (with a configuration that also has some `includePath` entries, previously omitted because the problem happened without them):

```
-------- Diagnostics - 2019-6-25 23:10:13
Version: 0.23.1
Translation Unit Mappings:
[C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\ForwardVerifier.cpp]:
    C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\ForwardVerifier.cpp
    C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\Chunk.h
    C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\ForwardVerifier.h
    C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7\stdexcept
[C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\PendulumVerifier.cpp]:
    C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\PendulumVerifier.cpp
    C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\Chunk.h
    C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\ForwardVerifier.h
    C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7\stdexcept
    C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\PendulumVerifier.h
Translation Unit Configurations:
[C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\ForwardVerifier.cpp]:
    Process ID: 2376
    Memory Usage: 82 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        C:\Users\felix\git\hypro\src
        C:\Users\felix\git\hypro\src\hypro
        C:\Users\felix\git\hypro\build\resources\src\glpk_download\include
        C:\Users\felix\git\carl\src
        C:\Users\felix\git\carl\build\resources\include
        C:\Users\felix\git\carl\build\resources\src\CoCoALib-EP\include
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu\c++\7
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7\backward
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\local\include
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include-fixed
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70400
[C:\Users\felix\git\draisine-hypro\tool\src\lib\verifier\PendulumVerifier.cpp]:
    Process ID: 8528
    Memory Usage: 40 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        C:\Users\felix\git\hypro\src
        C:\Users\felix\git\hypro\src\hypro
        C:\Users\felix\git\hypro\build\resources\src\glpk_download\include
        C:\Users\felix\git\carl\src
        C:\Users\felix\git\carl\build\resources\include
        C:\Users\felix\git\carl\build\resources\src\CoCoALib-EP\include
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu\c++\7
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7\backward
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\local\include
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include-fixed
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu
        C:\Users\felix\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70400
Total Memory Usage: 122 MB
```

**Comment by sean-mcmanus** [comment]
That output looks correct. Hmm, not sure why the config squiggle would appear, but you could get the incorrect squiggle to go away via `"enableConfigurationSquiggles": false` in the root (or the matching C_Cpp.default.enableConfigurationSquiggles setting).

@michelleangela @Colengms Any ideas how this incorrect squiggle could occur or are you able to repro it?

**Comment by fefrei** [comment]
While I don't know the internals, I find it really suspicious that I configure `/usr/bin/gcc`, and the debug output lists `/usr/bin/gcc`, but the squiggle complains about the Windows version of that path.

**Comment by sean-mcmanus** [comment]
The code that implements this squiggle is in our open source TypeScript, so theoretically you could debug it to see why it's failing for you if you use the "release" branch. The code runs on Windows so we need to convert the path to the Windows path, which appears to work successfully, so I don't know why it would fail to be found.

**Comment by fefrei** [comment]
Hm, OK. Another thought: While the file does exist, it's a 0-byte file, because it's a symbolic link on the Linux side. Maybe this is tripping something up?

**Comment by sean-mcmanus** [comment]
That should still work. It's a symbolic link to gcc-7 for me as well. The only case it would fail is if there was a symbolic link in the WSL version of the path that we would need to translate on the WSL side in order to get the correct Windows path. Your OS matches mine as well, so I don't know what is different that could be causing the failure.

**Comment by sean-mcmanus** [comment]
Oh, wait, it shouldn't be 0 bytes -- are you sure it's really 0 bytes? Size on Disk can be 0 bytes, but it should contain text when opened in notepad (i.e. Size not 0).

**Comment by fefrei** [comment]
It appears to have 0 bytes:

![image](https://user-images.githubusercontent.com/3078885/60135972-45eaf400-97a3-11e9-8a9a-5279a8f2024e.png)

And – suspiciously – Notepad cannot touch it:

![image](https://user-images.githubusercontent.com/3078885/60136006-5d29e180-97a3-11e9-923c-069fd17529c1.png)

However, the files look fine with WSL goggles on:

![image](https://user-images.githubusercontent.com/3078885/60136085-8ea2ad00-97a3-11e9-824b-04e6077de3ad.png)

**Comment by sean-mcmanus** [comment]
It might be because you upgraded to the "WslFs file system format"...I'm checking that out now...

**Comment by sean-mcmanus** [comment]
I reproed it -- the WslFs file system format is the cause.

**Comment by bobbrow** [comment]
Can you try using the Remote-WSL extension?  We're not likely to make any changes to our WSL support now that that extension exists.

**Comment by fefrei** [comment]
I’m using that right now, currently without issues. Thanks!
