### ISSUE TITLE
Can't find system headers

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3826]
C_Cpp_Properties.json as follow:

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${default}"
            ],
            "defines": [
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "databaseFilename": "${workspaceFolder}/.vscode/BROWSE.VC.DB"
            },
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe",

            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}

![捕获](https://user-images.githubusercontent.com/39362073/60081823-259c4480-9765-11e9-8e27-ea6c357480ad.PNG)

**Comment by michelleangela** [comment]
Hi @Lennon925 , I cannot reproduce this. Do you have any cpptools settings configured?

My repro steps were:

1. Open VS Code and create new folder for new workspace
2. Use the C_Cpp_Properties.json you provided
3. Create header file in folder
4. Try to add `#include <vector>`
Result: IntelliSense was able to find vector

I used this cl.exe from Visual Studio 2015.
![image](https://user-images.githubusercontent.com/38734287/60124109-c70fa000-973d-11e9-91bd-6813a8b05935.png)

**Comment by michelleangela** [comment]
@Lennon925 , my repro actually uses a different compiler path even though I specify in C_Cpp_Properties.json to use Visual Studio 2015.

I ran the `C/C++: Log Diagnostics` command and saw the extension is actually using the compiler path and include path from Visual Studio 2019. So it looks like the extension uses whatever cl.exe it finds on the machine.

Do you have other cl.exe installed by any chance? Can you also run and share output of `C/C++: Log Diagnostics` command?

**Comment by michelleangela** [comment]
Closing this issue do to long inactivity. Please re-open for further investigation and with any updated information.
