### ISSUE TITLE
Problem: C/C++ Debugger never works

### ISSUE THREAD

**Issue by Phycanva** [microsoft/vscode-cpptools#3827]
Type: Debugger
My debugger(gdb) doesn't work with C/C++ tools.
After configuring correctly(I think), I pressed the debug button. My program is complied and into an executable file. but debugger never starts.

Details:
1. When external terminal is false, integretad terminal just shows blue words and is stuck there, I can't input anything. When external terminal is ture. Nothing happened after closing the previous terminal. 
2. About the bar of debugger, there are only three buttons available: pause, restart and stop.
3. Below the menu bar, on the left there is a short blue line moving from one side to another(seem to be loading all the time).
4. No error imformation is given.

![question](https://user-images.githubusercontent.com/46981710/60103460-36af7a80-9792-11e9-94fc-dc759034fe14.png)

- OS and Version: Windows 10 1903
- VS Code Version: 1.35.1 (system setup)
- C/C++ Extension Version: 0.24.0-insiders
- Other extensions you installed (and if the issue persists after disabling them):
Chinese (Simplified) Language Pack for Visual Studio Code
Code Runner

More Details:

c_cpp_properties.json

>  {
>     "configurations": [
>         {
>             "name": "Win32",
>             "includePath": [
>                 "${workspaceFolder}/**",
>                 "C:\\MinGW\\include\\*",
>                 "C:\\MinGW\\include\\ddk\\*",
>                 "C:\\MinGW\\include\\gdiplus\\*",
>                 "C:\\MinGW\\include\\GL\\*",
>                 "C:\\MinGW\\include\\parts\\*",
>                 "C:\\MinGW\\include\\sys\\*"
>             ],
>             "defines": [
>                 "_DEBUG",
>                 "UNICODE",
>                 "_UNICODE"
>             ],
>             "windowsSdkVersion": "10.0.17763.0",
>             "compilerPath": "C:/MinGW/bin/g++.exe",
>             "cStandard": "c11",
>             "cppStandard": "c++17"
>         }
>     ],    
>     "version": 4
> }

tasks.json

> {
>     "tasks":[
>          {
>             "label": "Build(C)(Debug)",
>             "type": "shell",
>             "command": "g++",
>             "args": ["-g","${file}","-o","${fileBasenameNoExtension}"],    // 编译命令参数
>             "problemMatcher": {
>                 "owner": "cpp",
>                 "fileLocation": ["relative", "${workspaceRoot}"],
>                 "pattern": {
>                     "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
>                     "file": 1,
>                     "line": 2,
>                     "column": 3,
>                     "severity": 4,
>                     "message": 5
>                 }
>             },
>         }
>         
>     ],
>        "version": "2.0.0"
> }   

launch.json

> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "(gdb) Launch",
>             "type": "cppdbg",
>             "request": "launch",
>             "program": "${workspaceFolder}/${fileBasenameNoExtension}.exe",
>             "args": [],
>             "stopAtEntry": false,
>             "cwd": "${workspaceFolder}",
>             "environment": [],
>             "externalConsole": false,
>             "MIMode": "gdb",
>             "miDebuggerPath": "C:/MinGW/bin/gdb.exe",
>             "setupCommands": [
>                 {
>                     "description": "Enable pretty-printing for gdb",
>                     "text": "-enable-pretty-printing",
>                     "ignoreFailures": false
>                 }
>             ],
>             "preLaunchTask": "Build(C)(Debug)"
>         },
>     ]
> }

Additonally, Since yesterday I have tried many ways I find on the Internet but don't work at all. GDB is OK, I installed it recently and can use it in cmd and PowerShell.

Is there any problem in my json files? (Paths have been checked)
Please point out if I were wrong.
Excuse me for my limited English ability, thank you sincerely.

**Comment by WardenGnaw** [comment]
Can you share the output when you enable [logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging)?

**Comment by Phycanva** [comment]
Thank you, I will try and response about 2 hours later.

**Comment by Phycanva** [comment]
Hi! 
What I enabled:
trace, traceResponse, engineLogging.
Here are the results:

> --> E (output): {"event":"output","body":{"category":"console","output":"1: (80) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'\r\n"},"seq":2,"type":"event"}
> 1: (80) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (90) LaunchOptions  ExePath='D:\\Projects\\2019XJTUACM\\test.exe'\r\n"},"seq":4,"type":"event"}
> 1: (90) LaunchOptions  ExePath='D:\Projects\2019XJTUACM\test.exe'
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (90) LaunchOptions  WorkingDirectory='D:\\Projects\\2019XJTUACM'\r\n"},"seq":6,"type":"event"}
> 1: (90) LaunchOptions  WorkingDirectory='D:\Projects\2019XJTUACM'
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (90) LaunchOptions  ExeArguments='2&gt;CON 1&gt;CON &lt;CON'\r\n"},"seq":8,"type":"event"}
> 1: (90) LaunchOptions  ExeArguments='2&gt;CON 1&gt;CON &lt;CON'
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (90) LaunchOptions  MIMode='gdb'\r\n"},"seq":10,"type":"event"}
> 1: (90) LaunchOptions  MIMode='gdb'
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (91) LaunchOptions  MIDebuggerPath='C:/MinGW/bin/gdb.exe'\r\n"},"seq":12,"type":"event"}
> 1: (91) LaunchOptions  MIDebuggerPath='C:/MinGW/bin/gdb.exe'
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (91) LaunchOptions  WaitDynamicLibLoad='false'\r\n"},"seq":14,"type":"event"}
> 1: (91) LaunchOptions  WaitDynamicLibLoad='false'
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (91) LaunchOptions>\r\n"},"seq":16,"type":"event"}
> 1: (91) LaunchOptions>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (91) LaunchOptions    <SetupCommands>\r\n"},"seq":18,"type":"event"}
> 1: (91) LaunchOptions    <SetupCommands>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (92) LaunchOptions        <Command IgnoreFailures='false' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>\r\n"},"seq":20,"type":"event"}
> 1: (92) LaunchOptions        <Command IgnoreFailures='false' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (92) LaunchOptions    </SetupCommands>\r\n"},"seq":22,"type":"event"}
> 1: (92) LaunchOptions    </SetupCommands>
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (92) LaunchOptions</LocalLaunchOptions>\r\n"},"seq":24,"type":"event"}
> 1: (92) LaunchOptions</LocalLaunchOptions>
> --> C (runInTerminal-26): {"command":"runInTerminal","arguments":{"kind":"integrated","title":"cppdbg: test.exe","cwd":"","args":["c:\\Users\\92975\\.vscode\\extensions\\ms-vscode.cpptools-0.24.0-insiders2\\debugAdapters\\bin\\WindowsDebugLauncher.exe","--stdin=Microsoft-MIEngine-In-5vav3yc4.3gd","--stdout=Microsoft-MIEngine-Out-lxujwwny.0s1","--stderr=Microsoft-MIEngine-Error-yats221p.051","--pid=Microsoft-MIEngine-Pid-ldx0r5dh.5z4","--dbgExe=C:/MinGW/bin/gdb.exe","--interpreter=mi"],"env":{}},"seq":26,"type":"request"}
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (180) Wait for connection completion.\r\n"},"seq":28,"type":"event"}
> 1: (180) Wait for connection completion.
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1165) ->=thread-group-added,id=\"i1\"\r\n"},"seq":30,"type":"event"}
> 1: (1165) ->=thread-group-added,id="i1"
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1166) ->~\"GNU gdb (GDB) 7.6.1\\n\"\r\n"},"seq":32,"type":"event"}
> 1: (1166) ->~"GNU gdb (GDB) 7.6.1\n"
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1166) ->~\"Copyright (C) 2013 Free Software Foundation, Inc.\\n\"\r\n"},"seq":34,"type":"event"}
> 1: (1166) ->~"Copyright (C) 2013 Free Software Foundation, Inc.\n"
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1167) ->~\"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\\nThis is free software: you are free to change and redistribute it.\\nThere is NO WARRANTY, to the extent permitted by law.  Type \\\"show copying\\\"\\nand \\\"show warranty\\\" for details.\\n\"\r\n"},"seq":36,"type":"event"}
> 1: (1167) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1167) ->~\"This GDB was configured as \\\"mingw32\\\".\\nFor bug reporting instructions, please see:\\n\"\r\n"},"seq":38,"type":"event"}
> 1: (1167) ->~"This GDB was configured as \"mingw32\".\nFor bug reporting instructions, please see:\n"
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1167) ->~\"<http://www.gnu.org/software/gdb/bugs/>.\\n\"\r\n"},"seq":40,"type":"event"}
> 1: (1167) ->~"<http://www.gnu.org/software/gdb/bugs/>.\n"
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1167) ->(gdb)\r\n"},"seq":42,"type":"event"}
> 1: (1167) ->(gdb)
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1172) <-1001-gdb-set target-async on\r\n"},"seq":44,"type":"event"}
> 1: (1172) <-1001-gdb-set target-async on
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1173) ->&\"\\357\\273\\2771001-gdb-set target-async on\\n\"\r\n"},"seq":46,"type":"event"}
> 1: (1173) ->&"\357\273\2771001-gdb-set target-async on\n"
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1173) ->&\"Undefined command: \\\"\\\".  Try \\\"help\\\".\\n\"\r\n"},"seq":48,"type":"event"}
> 1: (1173) ->&"Undefined command: \"\".  Try \"help\".\n"
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1173) ->^error,msg=\"Undefined command: \\\"\\\".  Try \\\"help\\\".\"\r\n"},"seq":50,"type":"event"}
> 1: (1173) ->^error,msg="Undefined command: \"\".  Try \"help\"."
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1173) ->(gdb)\r\n"},"seq":52,"type":"event"}
> 1: (1173) ->(gdb)
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1174) ->&\"\\n\"\r\n"},"seq":54,"type":"event"}
> 1: (1174) ->&"\n"
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1174) ->^done\r\n"},"seq":56,"type":"event"}
> 1: (1174) ->^done
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1174) ->(gdb)\r\n"},"seq":58,"type":"event"}
> 1: (1174) ->(gdb)
> --> E (output): {"event":"output","body":{"category":"console","output":"1: (1178) Send Event AD7MessageEvent\r\n"},"seq":60,"type":"event"}
> 1: (1178) Send Event AD7MessageEvent

Have a good day!

**Comment by Phycanva** [comment]
> Can you share the output when you enable [logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging)?

Looking forward to your reply.

**Comment by APTX-4869-MDZZ** [comment]
Looking forward to your solution : )

**Comment by ghost** [comment]
I have the same problem. :(
Looking forward to your solution : )
