### ISSUE TITLE
Insiders updateChannel doesn't work with WSL remote

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3833]
The local version uses 0.24.0-insiders2, but my WSL remote incorrectly defaults to "Default" and then doesn't switch after changing it to Insiders. I thought we tested this earlier and it was working for the WSL remote scenario.

**Comment by sean-mcmanus** [comment]
It gives the error C/C++: Install vsix -- Failed to find VS Code script in the developer console.

**Comment by sean-mcmanus** [comment]
Manually downloading/installing the vsix in the WSL remote is a workaround.

**Comment by visstro** [comment]
Could you describe how to fix it manually?

**Comment by visstro** [comment]
Ok, there is actually no remote stuff magic here.
According to: https://code.visualstudio.com/api/advanced-topics/remote-extensions#installing-a-development-version-of-your-extension
1. Download manually from releases to your local: https://github.com/microsoft/vscode-cpptools/releases
2. In extensions tab choose "Install from VSIX".

Seems like it will keep auto updating even after manual install. Hope this is one-time action. :)

**Comment by LongLiveCHIEF** [comment]
I'm having problems also, but I think it's because I'm on WSL2.  I'll try to leave more info when I can. Right now though, it can't detect compiler path when I use `/usr/bin/gcc` or `/usr/bin/g++`, and I suspect it has to do with the way the WSL pipe works with WSL2.

**Comment by sean-mcmanus** [comment]
@LongLiveCHIEF If WSL2 is the new file system (where the /usr/bin/g++ is not detected as a file on Windows), then that's a known issue -- a potential workaround is to use the Remote - WSL extension to connect.

**Comment by Colengms** [comment]
I'm not repro'ing this.  I'm seeing insiders build installed in my remote WSL connection.  This seems to have been addressed.  Closing as fixed.

**Comment by Colengms** [comment]
This was fixed by #4767
