### ISSUE TITLE
0.24.0-insiders2 crashes in certain cases (mostly after edits and documentHighlight)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3834]
We're not sure what the cause is yet. It may also crash on hover, completion, or squiggles update (less likely).

UPDATE: Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.24.0-insiders3 ..

**Comment by Colengms** [comment]
This looks to be fixed in 0.24.0-insiders3
