### ISSUE TITLE
Feature Request: Container debugging launch profile

### ISSUE THREAD

**Issue by kagonzalez** [microsoft/vscode-cpptools#3835]
Type: Debugger
A debugging profile that allows users to debug from a container using the pipeTransport options

**Describe the bug**
- OS and Version: Antergos Linux kernel: 4.19.50-1-lts
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.23.1
- Other extensions you installed (and if the issue persists after disabling them): N/A because its not really an issue
- A clear and concise description of what the bug is.
I would like a debugging profile that can attach to a container running gdbserver 
**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
Below is a sample launch profile. I would try to submit a pull request but I know very little java/type script, and the code is very confusing.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/src/main",
            "args": [],
            "stopAtEntry": false,
            "cwd": "/",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set sysroot to the root of the target filesystem",
                    "text": "set sysroot /",
                    "ignoreFailures": true
                }
            ],
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "docker",
                "pipeArgs": [
                    "exec", 
                    "-i", 
                    "CONTAINER NAME", 
                    "sh",
                    "-c"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                    "/home/src":"${workspaceRoot}/src"
            },
        }
    ]
}
```

**Comment by WardenGnaw** [comment]
We have documentation on how to setup docker [here](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md#docker-example). 

We will consider making this a configuration available to select if there is a higher ask for it.

**Comment by pieandcakes** [comment]
We can start with documentation if that would be helpful.

**Comment by WardenGnaw** [comment]
We reccomend setting up `VS Code Remote - Containers` instead of using pipeTransport to build and debug your C++ apps in Docker.
