### ISSUE TITLE
6/25 update mess up mtk definition in vscode

### ISSUE THREAD

**Issue by coroner4817** [microsoft/vscode-cpptools#3837]
**Type: LanguageService**

I am using a custom css (https://github.com/robb0wen/synthwave-vscode) for the vscode theme and yesterday's update seems mess up the mtk definition within vscode for c++ (https://github.com/microsoft/vscode/search?q=mtk&unscoped_q=mtk)

The color of the theme for c++ looks wrong today and if I disable this c/c++ extension, it back to normal.

**Comment by sean-mcmanus** [comment]
It sounds like you're using 0.24.0-insiders2 with enhancedColorization set to "Enabled". Setting that to "Disabled" should also work around the issue. We added semantic colorization using decorators.

However, we should figure out if it's some bug with how we are assigning scopes or if the theme should be changed.

**Comment by coroner4817** [comment]
Thanks disable it works for me.

**Comment by Colengms** [comment]
Hi @coroner4817 .  I've installed the SynthWave '84 theme and Custom CSS and JS Loader extension.  When enhancedColorization is enabled, I see a number of elements with new colors, due to being newly recognized by this feature.  (Such as local variables, global variables, functions where called, types where instantiated).  These colors seem to be aligned with similar elements in TypeScript files when using the same theme.  Could the differences you are seeing be intentional?  As some of these tokens are new, existing themes likely do not account for them specifically, and we would be falling back to the next best scope to select their color.

If you don't believe the differences are intentional, could you post an example of what you are seeing that looks incorrect?

**Comment by coroner4817** [comment]
@Colengms  This is what I see on Ubuntu 16.04. You might haven't enable the glow on the SynthWave '84 theme. You need to reload the vscode window: 
https://github.com/robb0wen/synthwave-vscode#to-enable-the-glow
https://github.com/be5invis/vscode-custom-css#getting-started

Before 0.24.0-insiders2, the theme always looks like the second one.

**enhancedColorization enabled c++ code:**
![Screenshot from 2019-06-26 16-47-46](https://user-images.githubusercontent.com/8528457/60213990-9cebda00-9832-11e9-8b55-094b1507ea14.png)

**enhancedColorization disabled c++ code:**
![Screenshot from 2019-06-26 16-48-20](https://user-images.githubusercontent.com/8528457/60214034-b8ef7b80-9832-11e9-86dc-a36be249d06f.png)

**Other code like Python**
![Screenshot from 2019-06-26 16-49-57](https://user-images.githubusercontent.com/8528457/60214142-eccaa100-9832-11e9-85ea-235686a738ca.png)

**Comment by Colengms** [comment]
@coroner4817 , I believe if you compare against a TypeScript file, you will see C++ files have similar colors for variables and types, whereas you are not actually getting the proper colors for variables (i.e. arr and pivot) in Python files, likely for the same reason as they were missing from C++ files.

Tokens colored by enhancedColorization are likely missing the 'glow'.  We are using TextEditorDecorations to colorize them.  The CSS loader extension is likely not associating the glow with them.  That would be the case for anything that uses TextEditorDecorations.  (Such as git diff's).

**Comment by coroner4817** [comment]
@Colengms TypeScript for me also looks similar to the second one.  

Anyway if the first screenshot should be the correct one which pick up all the proper colors then I guess I just disable enhancedColorization. It's too colorful for me.

You can close this one if it's a non-issue.

**Comment by Colengms** [comment]
@coroner4817 This looks like a side-effect of the custom CSS and our use of TextEditorDecorations.  The CSS is applied to certain CSS classes, but when TextEditorDecorations are applied they involve dynamically created CSS classes which take precedence. Unfortunately, I don't think we can address this from our side, at least not easily.  There are plans to add a better mechanism to VS Code to facilitate semantic colorization.  Once we switch to that approach, this may be addressed.

**Comment by coroner4817** [comment]
Thanks for explanation.
