### ISSUE TITLE
Ctrl+Shift+P :  Command 'C_Cpp.ConfigurationEdit' not found.

### ISSUE THREAD

**Issue by gigaimage** [microsoft/vscode-cpptools#384]
Config: Win10/VSCode 1.7.2/CC++ 0.9.2

Followed Documentation page. 
> Note: You can also generate or edit a c_cpp_properties.json file with the C/Cpp: Edit Configurations command from the Command Palette (Ctrl+Shift+P).

But VSCode errors out " Command 'C_Cpp.ConfigurationEdit' not found. 

This was when I was trying to resolve a constant error message when I start VSCode: see screenshot.

![image](https://cloud.githubusercontent.com/assets/1184087/20870115/e924db92-ba36-11e6-8ccc-f4fa5eee190f.png)

For the C/C++ dependencies error, tried elevated mode, tried with admin account just in case my regular account has lock-down issue mentioned in #233.  Confirmed that System32/wbem (as per  #216) is in path which has wmic.exe

settings.json:
'
{  
 

    // The full path of the clang-format executable.
    "C_Cpp.clang_format_path": "C:\\Program Files\\LLVM\\bin\\clang-format.exe",

    // Enable clang-format on save.
    "C_Cpp.clang_format_formatOnSave": true
}
'

**Comment by gigaimage** [comment]
BTW : This is on Win10 and other config : see screen capture: 
![image](https://cloud.githubusercontent.com/assets/1184087/20870173/3bb10128-ba38-11e6-906c-c2f9b2099257.png)

**Comment by pieandcakes** [comment]
@gigaimage we have a fix for the `wmic` issue in the next release. I don't know if that is preventing this from working. Someone from the C++ language team will need to chime in.

**Comment by sean-mcmanus** [comment]
Yeah, sounds like the fixed wmic issue.

**Comment by gigaimage** [comment]
Upgraded to 0.9.3. I confirm that issue has been fixed.
Thanks.
