### ISSUE TITLE
how deal with `class` keyword in c program?

### ISSUE THREAD

**Issue by dancon** [microsoft/vscode-cpptools#3841]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS 10.14.5
- VS Code Version: 1.35.1
- C/C++ Extension Version: typedef struct class Class;
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

![image](https://user-images.githubusercontent.com/6836599/60244871-f1a05b00-98ed-11e9-93a7-d9b54e87e927.png)

I just working with a third party lib in c, and there are too much docs to read to fix this problem for me (a newer for c/c++). Maybe it's an insignificant issue for you, but hard to me.

Is there a way to disable the next-line check? or something else like that ~

**To Reproduce**

As the code in the screenshot above.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
It is interpreting the code as C++ instead of C. What is the file type? Can you make sure the files.association settings haven't added the file type as C++?

**Comment by Colengms** [comment]
The error due to use of `class` in a C language file appears to be by-design.  The reporting user has not responded since the initial posting.  Closing.  If there is still an issue here, please let us know.
