### ISSUE TITLE
Unable to start the C/C++ language server (remote SSH on raspbian)

### ISSUE THREAD

**Issue by Souldat** [microsoft/vscode-cpptools#3842]
Unable to start the C/C++ language server (remote SSH on raspbian)

Raspbian - Stretch 
vscode insiders 1.36.0
CPP Tools version: 0.24.0-insiders2 (and some previous versions tested as well)
Other extensions installed: Python
Remote SSH (nightly)

Issue:
I'm using the new remote SSH features for remote debugging / running on a raspberry pi 3b+. The python side of my application seems to be working well with the python debugging extension installed. However im having issues getting the C++ debugging / intellisense (cpptools) working.

After installing the C/C++ extension (which installs on the remote system) and reloading vscode, I get the following error:

Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Launching server using command /home/pi/.vscode-server-insiders/extensions/ms-vscode.cpptools-0.24.0-insiders2/bin/Microsoft.VSCode.CPP.Extension.linux failed.

I've tried manually uninstalling and reinstalling both the cpptools-linux and cpptools-linux64 versions via visx (in case the auto install was selecting the wrong version of cpp-tools) as well with no luck. (I'm not exactly sure which version of the linux cpptools I should be using for a raspbian linux os)  I've tried some previous versions as well all with the same results.

Here's the output from developer tools in VSCode:

[-1561645211142.log](https://github.com/microsoft/vscode-cpptools/files/3335201/-1561645211142.log)

**Comment by sean-mcmanus** [comment]
Our binaries don't run on ARM currently. See https://github.com/microsoft/vscode-cpptools/issues/429 and https://github.com/microsoft/vscode-cpptools/issues/2506 to upvote those.

**Comment by Souldat** [comment]
Thanks Sean, I was under the impression that support had been added based on some previous readings elsewhere since some of the original posts regarding this issue but good to know its still currently not supported.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.0.0

**Comment by Souldat** [comment]
Your a legend. <3
