### ISSUE TITLE
Syntax highlighting broken with enum keyword in function argument

### ISSUE THREAD

**Issue by tomocafe** [microsoft/vscode-cpptools#3845]
Issue Type: <b>Bug</b>

1. Open a new editor, then add the following C++ code:

```cpp
enum SampleEnum {
    FOO = 0,
    BAR = 1
};

void func(enum SampleEnum arg) {
    std::vector<std::stringstream> streams;
    streams.push_back(std::stringstream());
    streams.back() << "hello";
    if (arg & FOO) {
        streams.back() << "foo";
        // syntax is busted until the next } character, see line below:
    }
    streams.push_back(std::stringstream());
    if (arg & BAR) {
        streams.back() << "bar";
    }
    streams.back() << "world";
}
```

2. Set the syntax to C++
3. Observe (almost) no syntax highlighting between the beginning of function `func` and the first `}` character in the function

![vscode_cpp_enum_arg_bug](https://user-images.githubusercontent.com/20233563/60300418-c3b61900-98e3-11e9-9b3e-21dce010645e.PNG)

## Expected result:

Delete the keyword `enum` in the function argument and observe the correct syntax highlighting within the function scope.

![vscode_cpp_enum_arg_expected](https://user-images.githubusercontent.com/20233563/60300468-eba57c80-98e3-11e9-88ea-e40ce6e0dee4.PNG)

Extension version: 0.23.1
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 3.10.0-957.5.1.el7.x86_64

**Comment by Colengms** [comment]
Hi @tomocafe .  This looks like an issue with vscode's C++ TextMate grammar.  There is a "Better Syntax" extension that handles this properly.  My understanding is that we'd like to ingest the TextMate grammar from this extension into vscode at some point.  @jeff-hykin is the author and may be able to comment.

**Comment by jeff-hykin** [comment]
This is an issue with an earlier version of the C++ Syntax. Thankfully it has been fixed upstream, but it will take a bit for it to get pulled into the regular VS Code. @tomocafe If you want the fix right now download the [Better Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) extension and the latest syntax will automatically be applied.

**Comment by tomocafe** [comment]
Better Syntax indeed solves this issue. Thanks!

Not sure if I should close this issue or leave it open to track until it's pulled into mainline. I'll leave this to the maintainer's discretion.
