### ISSUE TITLE
Code navigation stops working if one symbol couldn't be resolved

### ISSUE THREAD

**Issue by pralhadsapre** [microsoft/vscode-cpptools#3846]
**Type: LanguageService**

- OS and Version: Mac OS 10.14.3
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.23.1

This is something I noticed when using VS Code with a codebase with almost 20K+ files. There are tons of symbols here with cases where a symbol is found in multiple places due to header file generation.

When I reset the Intellisense DB and start navigating to definitions of symbols, everything works fine. Up until the point that the extension gets confused and the progress bar keeps on going and the symbol is ultimately not found with no file being opened. From this point onwards, code navigation just completely gives up and even the symbols which were properly being navigated to stop working.

If I reopen the workspace the old navigations start working again. That leads me to believe that the internal state after a failed navigation ends up in an inconsistent state. It's super time consuming to keep regenerating the Intellisense DB every time such an event happens.

Is there a shortcut to restore the state to the previous state after a failed code navigation which I am missing?

I am also interested in making the extension look for definition in a file with a different extension than the standard ones. In this case its ".ifc". I tried to add the following snippet to the settings.json file under
```
~/Library/Application Support/Code/User

"languages": [
        {
            "id": "c",
            "extensions": [".ifc", ".h", ".c"]
        },
        {
            "id": "cpp",
            "extensions": [".ifc", ".hpp", ".cxx"]
        }
    ]
```
but code navigation seems to be completely ignoring these files.

Any suggestions about these two issues?

**Comment by sean-mcmanus** [comment]
What do you mean by "navigating to definitions of symbols"? Are you using Go to Def/Decl or Go to Symbol? Do you know what operation causes it to enter a broken state?

Under normal conditions, a reload window should not cause a reparsing of the symbol database, just a rescan for any potentially changed files. Are you saying a Restart IntelliSense Database is required to fix the issue, which does an actual reparse, i.e. the database is corrupt?

If your intelliSenseEngine is set to "Default", then Go to Def is also controlled by the IntelliSense process results, so if that is failing for some reason, then it could fail to find a definition. You could change it to "Tag Parser" to "by pass" the IntelliSense part.

Can you provide any sample project that demonstrates this "failed navigation"? Are you navigating to a symbol that doesn't exist or should exist? Do you see errors when you [enable debug logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md)?

You should add `"*.ifc": "cpp"` to your files.associations setting.

**Comment by pralhadsapre** [comment]
Hi Sean,

Thanks for your reply.

To clear out the ambiguity when I mentioned "navigating to definitions of symbols" I only meant "Go to definition" since I was CMD + Left Clicking on the symbols.

Using the IntelliSenseEngine set to "Default" I do need to Reset the IntelliSense Database which triggers a reparse. However I should say that I tried navigating in the problematic files after changing the IntelliSenseEngine to "Tag Parser" and things are behaving much better than before. Especially for the fact that the "Go to definition" is landing correctly in the source .c file instead of the generated .h header files. 

The change to "Tag Parser" just as well might be sufficient for now. I will keep you posted here if I encounter something.

I have enabled the debug logging too and will be on the lookout for any logs of interest when the "Go to Definition" breaks and stops working.

Also thanks for the tip on files.association setting. However I still notice that Definitions in a .ifc are not being navigated to properly. Any thoughts here? There are parallel definitions in generated .h files which the extension prefers to show. I would imagine that the ordering of the files in the directory scan could play a role in this.

**Comment by sean-mcmanus** [comment]
The "Tag Parser" mode is not ideal and doesn't do full parsing and type checking or squiggles, etc., but it sounds like the additional type checking that the IntelliSense is doing has a bug that is excluding results that it should not, if the bug always repros when the red flame disappears then there's a bug with how we handle the IntelliSense type checking, but if the bug happens after editing, the internal state could be corrupted.

I wasn't able to repro a bug with Go to Def with .ifc in the files.associations. Are you able to give more repro details? It's possible our parser is failing to parse the particular definitions (our symbol parser doesn't evaluate macros, so those need to be added to a cpp.hint file, usually just in cases where the macro needs to be evaluated into order to correctly parse function definitions).

**Comment by pralhadsapre** [comment]
I double checked for the .ifc file Go to Def issue. Sorry for the confusion but that file is indeed parsed correctly and shows up as one of the possible definitions.

For the IntelliSense issue, after the point that the code navigation was broken, I didn't see the red flame or the database icon. So I am positive that the parsing was completed. I know that doesn't help you a lot to narrow down the problem. I will try to reproduce it and paste the logs over here to help you pinpoint it.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
