### ISSUE TITLE
GDB stepping isn't working right on Ubuntu

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-cpptools#385]
_From @lovettchris on December 3, 2016 7:10_

- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04

**Steps to Reproduce:**
1. install C++ extension from Microsoft and the Native Debug extension by "webfreak".
2.  setup remote debugging via GDB server of a C++ app compilied by g++ with -ggdb. 
3.  create launch.json file with "type":"gdb", "request":"attach", "remote":"true", with target set to the port that GDB server is listening on.
4. set a breakpoint that you will hit
5. hit the break point and press F10 or click "step over" button on the debug toolbar.

**Expected**: move to next line of code.

**Actual**: every step operation reports and error:
"Source ../sysdeps/unix/sysv/linux/x86_64/cancellation.S is not available."

Clicking step one more time works, but this intermediate error on every step makes debugging rather painful.  I also found step out sometimes doesn't work.

_Copied from original issue: Microsoft/vscode#16429_

**Comment by pieandcakes** [comment]
@lovettchris Are you using the Native Debug extension or the Microsoft C++ extension when you run into this debugging issue? It sounds like you are using Native Debug.

**Comment by lovettchris** [comment]
Both.  I didn't realize the Microsoft C++ extension could also do GDB debugging :-) So I removed the other one, now it is working fine.  Thanks.

**Comment by pieandcakes** [comment]
No problem! If you have further questions, please let us know.
