### ISSUE TITLE
Squiggles are disabled for this translation unit

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3852]
**Describe the bug**
- C/C++ Extension Version: 0.24.2-insider

Currently I set compile_commands.json and includePath in my c_cpp_properties.json, but some errors occur like this: "#include errors detected. Consider updating your compile_commands.json or includePath. Squiggles are disabled for this translation unit".

I wonder when this error will occur ? Any solution to solve this? Any ways to remove squiggles errors only about #include?

**Comment by sean-mcmanus** [comment]
The text "squiggles are disabled" is incorrect is the errorSquiggles setting is "Enabled" (it's correct if the setting is "EnabledIfIncludesResolve".

The error occurs when a `#include` header can't be found. You could try using the C/C++: Log Diagnostics command to see if the paths are setup correctly.

There is no way to remove that particular error, unless all errors are removed via the errorSquiggles "Disabled" setting.

**Comment by Lennon925** [comment]
> The text "squiggles are disabled" is incorrect is the errorSquiggles setting is "Enabled" (it's correct if the setting is "EnabledIfIncludesResolve".
> 
> The error occurs when a `#include` header can't be found. You could try using the C/C++: Log Diagnostics command to see if the paths are setup correctly.
> 
> There is no way to remove that particular error, unless all errors are removed via the errorSquiggles "Disabled" setting.

Hi Sean,

I set the errorSquiggles to 'Enabled' and the error still occur. And there is no errors in output window after I use 'Log Diagnostics'.

![1](https://user-images.githubusercontent.com/39362073/60377562-e1ea5900-9a4a-11e9-824f-1765435e4c0c.PNG)

And output as follow:

`-------- Diagnostics - 2019/6/29 上午8:43:44
Version: 0.24.0-insiders3
Translation Unit Mappings:
[D:\Lennon\xxxx\xxxx.c]:
    D:\LENNON\xxxx\xxxx.C
Translation Unit Configurations:
[D:\Lennon\xxxx\xxxx.c]:
    Process ID: 8504
    Memory Usage: 366 MB
    Includes:
        ....(FilePath)
    Standard Version: c11
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 366 MB

`

**Comment by sean-mcmanus** [comment]
Yeah, the IntelliSense process can't locate stddef.h. How are you setting your system includes? Did you set a compilerPath? Setting that explicitly might fix the issue.

**Comment by sean-mcmanus** [comment]
If you're using compile_commands.json, it looks like it might have some problem getting the compilerPath from there.

**Comment by sean-mcmanus** [comment]
We have a bunch of known bugs with compile_commands.json that we want to fix.

**Comment by Lennon925** [comment]
> Yeah, the IntelliSense process can't locate stddef.h. How are you setting your system includes? Did you set a compilerPath? Setting that explicitly might fix the issue.

I put  system include file path into compile_commands.json, it's solved.

**Comment by Lennon925** [comment]
I set compilerPath to "D:\\Lennon\\MinGW\\bin\\gcc.exe", but it still can't find system header file "features.h" which is in "D:\Lennon\MinGW\lib\gcc\mingw32\5.3.0\include\c++\parallel" folders.

**Comment by Lennon925** [comment]
> We have a bunch of known bugs with compile_commands.json that we want to fix.

I set compilerPath to "D:\Lennon\MinGW\bin\gcc.exe", but it still can't find system header file "features.h" which is in "D:\Lennon\MinGW\lib\gcc\mingw32\5.3.0\include\c++\parallel" folders.

**Comment by sean-mcmanus** [comment]
1. You should use g++.exe for C++ (if you really want C with gcc.exe, then make sure it's non-0 byte file that is executable on Windows, i.e. you might need to use mingw32-gcc.exe instead).
2. When you do C/C++: Log Diagnostics, you should see the "D:\Lennon\MinGW\lib\gcc\mingw32\5.3.0\include\c++\" (in caps).

Are you able to get it working now?

**Comment by Lennon925** [comment]
> 1. You should use g++.exe for C++ (if you really want C with gcc.exe, then make sure it's non-0 byte file that is executable on Windows, i.e. you might need to use mingw32-gcc.exe instead).
> 2. When you do C/C++: Log Diagnostics, you should see the "D:\Lennon\MinGW\lib\gcc\mingw32\5.3.0\include\c++" (in caps).
> 
> Are you able to get it working now?

I used g++.exe and did C/C++: Log Diagnostics and saw:
![捕获](https://user-images.githubusercontent.com/39362073/60475895-127cfd80-9cac-11e9-982e-d3a6fbff6825.PNG)

There is no this path : "D:\Lennon\MinGW\lib\gcc\mingw32\5.3.0\include\c++" and error still errors.

**Comment by sean-mcmanus** [comment]
Those are the C/gcc paths and the C++ paths are supposed to appear beforehand -- it looks like it's interpreting the file as "C" and not "C++". What "Standard Version" is reported from the Log Diagnostics?

**Comment by Lennon925** [comment]
> Those are the C/gcc paths and the C++ paths are supposed to appear beforehand -- it looks like it's interpreting the file as "C" and not "C++". What "Standard Version" is reported from the Log Diagnostics?

my file is a c file which name is xxx.c and ’Standard Version‘ is 'C11'

**Comment by sean-mcmanus** [comment]
What happens when you run `D:\Lennon\MinGW\bin\g++.exe -Wp,-v -E -xc -dD -x c++ nul`? It's supposed to show the C++ include paths in the "search starts here" output. My guess is it's outputting some path format that we're not converting correctly to a usable path that exists.

**Comment by Lennon925** [comment]
> D:\Lennon\MinGW\bin\g++.exe -Wp,-v -E -xc -dD -x c++ nul

As below:

![捕获](https://user-images.githubusercontent.com/39362073/60478803-49581100-9cb6-11e9-8fd8-c8320073b43c.PNG)

**Comment by sean-mcmanus** [comment]
Yeah, that's the correct output -- I don't know why we are not picking those up. @bobbrow Any ideas on how to get more diagnostics?

**Comment by bobbrow** [comment]
I might be missing something, but it sounds like this is a .c file so @Lennon925 is getting the correct include path for C.  Why do you want to include "features.h" from the C++ path?  Is it valid to be including that file?

**Comment by Lennon925** [comment]
> I might be missing something, but it sounds like this is a .c file so @Lennon925 is getting the correct include path for C. Why do you want to include "features.h" from the C++ path? Is it valid to be including that file?

Output window give this error:cannot open source file "features.h". I don't know why to include this header. My code files don't include 'features.h'

**Comment by sean-mcmanus** [comment]
It sounds like parallel/features.h should not be being used. Are you able to track down which file is attempting to use that?

From the error message, you are using compile_commands.json, so the output from C/C++: Log Diagnostics might be incorrect (looking at [debug logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) might be more correct). So it's possible something in the compile_commands.json is trigger the particular file to execute as C++ instead of C (even though the Log Diagnostics says it's C).

**Comment by Lennon925** [comment]
> It sounds like parallel/features.h should not be being used. Are you able to track down which file is attempting to use that?
> 
> From the error message, you are using compile_commands.json, so the output from C/C++: Log Diagnostics might be incorrect (looking at [debug logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) might be more correct). So it's possible something in the compile_commands.json is trigger the particular file to execute as C++ instead of C (even though the Log Diagnostics says it's C).

I searched my code and didn't find any code like this: '#include <features.h>'. And I removed compile_commands.json, the behavior is the same with previous.

and debug info as follow:
textDocument/codeAction: 195
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/Lennon/16.0_Mirror/app/src/rr/uem/ca/UemCaApi.c
errorSquiggles count: 39
sending compilation args for D:\LENNON\16.0_MIRROR\APP\SRC\RR\UEM\CA\UEMCAAPI.C
  include: D:\LENNON\MINGW\LIB\GCC\MINGW32\5.3.0\INCLUDE
  include: D:\LENNON\MINGW\INCLUDE
  include: D:\LENNON\MINGW\LIB\GCC\MINGW32\5.3.0\INCLUDE-FIXED
  include: D:\LENNON\MINGW\MINGW32\INCLUDE
             .....
             include some my code folder
             .....

  define: __STDC__=1
  define: __STDC_VERSION__=201112L
  define: __STDC_UTF_16__=1
  define: __STDC_UTF_32__=1
  define: __STDC_HOSTED__=1
  define: __GNUC__=5
  define: __GNUC_MINOR__=3
  define: __GNUC_PATCHLEVEL__=0
  define: __VERSION__="5.3.0"
  define: __ATOMIC_RELAXED=0
  define: __ATOMIC_SEQ_CST=5
  define: __ATOMIC_ACQUIRE=2
  define: __ATOMIC_RELEASE=3
  define: __ATOMIC_ACQ_REL=4
  define: __ATOMIC_CONSUME=1
  define: __FINITE_MATH_ONLY__=0
  define: __SIZEOF_INT__=4
  define: __SIZEOF_LONG__=4
  define: __SIZEOF_LONG_LONG__=8
  define: __SIZEOF_SHORT__=2
  define: __SIZEOF_FLOAT__=4
  define: __SIZEOF_DOUBLE__=8
  define: __SIZEOF_LONG_DOUBLE__=12
  define: __SIZEOF_SIZE_T__=4
  define: __CHAR_BIT__=8
  define: __BIGGEST_ALIGNMENT__=16
  define: __ORDER_LITTLE_ENDIAN__=1234
  define: __ORDER_BIG_ENDIAN__=4321
  define: __ORDER_PDP_ENDIAN__=3412
  define: __BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __FLOAT_WORD_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __SIZEOF_POINTER__=4
  define: __SIZE_TYPE__=unsigned int
  define: __PTRDIFF_TYPE__=int
  define: __WCHAR_TYPE__=short unsigned int
  define: __WINT_TYPE__=short unsigned int
  define: __INTMAX_TYPE__=long long int
  define: __UINTMAX_TYPE__=long long unsigned int
  define: __CHAR16_TYPE__=short unsigned int
  define: __CHAR32_TYPE__=unsigned int
  define: __SIG_ATOMIC_TYPE__=int
  define: __INT8_TYPE__=signed char
  define: __INT16_TYPE__=short int
  define: __INT32_TYPE__=int
  define: __INT64_TYPE__=long long int
  define: __UINT8_TYPE__=unsigned char
  define: __UINT16_TYPE__=short unsigned int
  define: __UINT32_TYPE__=unsigned int
  define: __UINT64_TYPE__=long long unsigned int
  define: __INT_LEAST8_TYPE__=signed char
  define: __INT_LEAST16_TYPE__=short int
  define: __INT_LEAST32_TYPE__=int
  define: __INT_LEAST64_TYPE__=long long int
  define: __UINT_LEAST8_TYPE__=unsigned char
  define: __UINT_LEAST16_TYPE__=short unsigned int
  define: __UINT_LEAST32_TYPE__=unsigned int
  define: __UINT_LEAST64_TYPE__=long long unsigned int
  define: __INT_FAST8_TYPE__=signed char
  define: __INT_FAST16_TYPE__=short int
  define: __INT_FAST32_TYPE__=int
  define: __INT_FAST64_TYPE__=long long int
  define: __UINT_FAST8_TYPE__=unsigned char
  define: __UINT_FAST16_TYPE__=short unsigned int
  define: __UINT_FAST32_TYPE__=unsigned int
  define: __UINT_FAST64_TYPE__=long long unsigned int
  define: __INTPTR_TYPE__=int
  define: __UINTPTR_TYPE__=unsigned int
  define: __has_include(STR)=__has_include__(STR)
  define: __has_include_next(STR)=__has_include_next__(STR)
  define: __GXX_ABI_VERSION=1009
  define: __SCHAR_MAX__=0x7f
  define: __SHRT_MAX__=0x7fff
  define: __INT_MAX__=0x7fffffff
  define: __LONG_MAX__=0x7fffffffL
  define: __LONG_LONG_MAX__=0x7fffffffffffffffLL
  define: __WCHAR_MAX__=0xffff
  define: __WCHAR_MIN__=0
  define: __WINT_MAX__=0xffff
  define: __WINT_MIN__=0
  define: __PTRDIFF_MAX__=0x7fffffff
  define: __SIZE_MAX__=0xffffffffU
  define: __INTMAX_MAX__=0x7fffffffffffffffLL
  define: __INTMAX_C(c)=c ## LL
  define: __UINTMAX_MAX__=0xffffffffffffffffULL
  define: __UINTMAX_C(c)=c ## ULL
  define: __SIG_ATOMIC_MAX__=0x7fffffff
  define: __SIG_ATOMIC_MIN__=(-__SIG_ATOMIC_MAX__ - 1)
  define: __INT8_MAX__=0x7f
  define: __INT16_MAX__=0x7fff
  define: __INT32_MAX__=0x7fffffff
  define: __INT64_MAX__=0x7fffffffffffffffLL
  define: __UINT8_MAX__=0xff
  define: __UINT16_MAX__=0xffff
  define: __UINT32_MAX__=0xffffffffU
  define: __UINT64_MAX__=0xffffffffffffffffULL
  define: __INT_LEAST8_MAX__=0x7f
  define: __INT8_C(c)=c
  define: __INT_LEAST16_MAX__=0x7fff
  define: __INT16_C(c)=c
  define: __INT_LEAST32_MAX__=0x7fffffff
  define: __INT32_C(c)=c
  define: __INT_LEAST64_MAX__=0x7fffffffffffffffLL
  define: __INT64_C(c)=c ## LL
  define: __UINT_LEAST8_MAX__=0xff
  define: __UINT8_C(c)=c
  define: __UINT_LEAST16_MAX__=0xffff
  define: __UINT16_C(c)=c
  define: __UINT_LEAST32_MAX__=0xffffffffU
  define: __UINT32_C(c)=c ## U
  define: __UINT_LEAST64_MAX__=0xffffffffffffffffULL
  define: __UINT64_C(c)=c ## ULL
  define: __INT_FAST8_MAX__=0x7f
  define: __INT_FAST16_MAX__=0x7fff
  define: __INT_FAST32_MAX__=0x7fffffff
  define: __INT_FAST64_MAX__=0x7fffffffffffffffLL
  define: __UINT_FAST8_MAX__=0xff
  define: __UINT_FAST16_MAX__=0xffff
  define: __UINT_FAST32_MAX__=0xffffffffU
  define: __UINT_FAST64_MAX__=0xffffffffffffffffULL
  define: __INTPTR_MAX__=0x7fffffff
  define: __UINTPTR_MAX__=0xffffffffU
  define: __GCC_IEC_559=2
  define: __GCC_IEC_559_COMPLEX=2
  define: __FLT_EVAL_METHOD__=2
  define: __DEC_EVAL_METHOD__=2
  define: __FLT_RADIX__=2
  define: __FLT_MANT_DIG__=24
  define: __FLT_DIG__=6
  define: __FLT_MIN_EXP__=(-125)
  define: __FLT_MIN_10_EXP__=(-37)
  define: __FLT_MAX_EXP__=128
  define: __FLT_MAX_10_EXP__=38
  define: __FLT_DECIMAL_DIG__=9
  define: __FLT_MAX__=3.40282346638528859812e+38F
  define: __FLT_MIN__=1.17549435082228750797e-38F
  define: __FLT_EPSILON__=1.19209289550781250000e-7F
  define: __FLT_DENORM_MIN__=1.40129846432481707092e-45F
  define: __FLT_HAS_DENORM__=1
  define: __FLT_HAS_INFINITY__=1
  define: __FLT_HAS_QUIET_NAN__=1
  define: __DBL_MANT_DIG__=53
  define: __DBL_DIG__=15
  define: __DBL_MIN_EXP__=(-1021)
  define: __DBL_MIN_10_EXP__=(-307)
  define: __DBL_MAX_EXP__=1024
  define: __DBL_MAX_10_EXP__=308
  define: __DBL_DECIMAL_DIG__=17
  define: __DBL_MAX__=((double)1.79769313486231570815e+308L)
  define: __DBL_MIN__=((double)2.22507385850720138309e-308L)
  define: __DBL_EPSILON__=((double)2.22044604925031308085e-16L)
  define: __DBL_DENORM_MIN__=((double)4.94065645841246544177e-324L)
  define: __DBL_HAS_DENORM__=1
  define: __DBL_HAS_INFINITY__=1
  define: __DBL_HAS_QUIET_NAN__=1
  define: __LDBL_MANT_DIG__=64
  define: __LDBL_DIG__=18
  define: __LDBL_MIN_EXP__=(-16381)
  define: __LDBL_MIN_10_EXP__=(-4931)
  define: __LDBL_MAX_EXP__=16384
  define: __LDBL_MAX_10_EXP__=4932
  define: __DECIMAL_DIG__=21
  define: __LDBL_MAX__=1.18973149535723176502e+4932L
  define: __LDBL_MIN__=3.36210314311209350626e-4932L
  define: __LDBL_EPSILON__=1.08420217248550443401e-19L
  define: __LDBL_DENORM_MIN__=3.64519953188247460253e-4951L
  define: __LDBL_HAS_DENORM__=1
  define: __LDBL_HAS_INFINITY__=1
  define: __LDBL_HAS_QUIET_NAN__=1
  define: __DEC32_MANT_DIG__=7
  define: __DEC32_MIN_EXP__=(-94)
  define: __DEC32_MAX_EXP__=97
  define: __DEC32_MIN__=1E-95DF
  define: __DEC32_MAX__=9.999999E96DF
  define: __DEC32_EPSILON__=1E-6DF
  define: __DEC32_SUBNORMAL_MIN__=0.000001E-95DF
  define: __DEC64_MANT_DIG__=16
  define: __DEC64_MIN_EXP__=(-382)
  define: __DEC64_MAX_EXP__=385
  define: __DEC64_MIN__=1E-383DD
  define: __DEC64_MAX__=9.999999999999999E384DD
  define: __DEC64_EPSILON__=1E-15DD
  define: __DEC64_SUBNORMAL_MIN__=0.000000000000001E-383DD
  define: __DEC128_MANT_DIG__=34
  define: __DEC128_MIN_EXP__=(-6142)
  define: __DEC128_MAX_EXP__=6145
  define: __DEC128_MIN__=1E-6143DL
  define: __DEC128_MAX__=9.999999999999999999999999999999999E6144DL
  define: __DEC128_EPSILON__=1E-33DL
  define: __DEC128_SUBNORMAL_MIN__=0.000000000000000000000000000000001E-6143DL
  define: __REGISTER_PREFIX__=
  define: __USER_LABEL_PREFIX__=_
  define: __GNUC_STDC_INLINE__=1
  define: __NO_INLINE__=1
  define: __STRICT_ANSI__=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1
  define: __GCC_ATOMIC_BOOL_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR16_T_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR32_T_LOCK_FREE=2
  define: __GCC_ATOMIC_WCHAR_T_LOCK_FREE=2
  define: __GCC_ATOMIC_SHORT_LOCK_FREE=2
  define: __GCC_ATOMIC_INT_LOCK_FREE=2
  define: __GCC_ATOMIC_LONG_LOCK_FREE=2
  define: __GCC_ATOMIC_LLONG_LOCK_FREE=2
  define: __GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1
  define: __GCC_ATOMIC_POINTER_LOCK_FREE=2
  define: __GCC_HAVE_DWARF2_CFI_ASM=1
  define: __PRAGMA_REDEFINE_EXTNAME=1
  define: __SIZEOF_WCHAR_T__=2
  define: __SIZEOF_WINT_T__=2
  define: __SIZEOF_PTRDIFF_T__=4
  define: __i386=1
  define: __i386__=1
  define: __SIZEOF_FLOAT80__=12
  define: __SIZEOF_FLOAT128__=16
  define: __ATOMIC_HLE_ACQUIRE=65536
  define: __ATOMIC_HLE_RELEASE=131072
  define: __i586=1
  define: __i586__=1
  define: __pentium=1
  define: __pentium__=1
  define: __code_model_32__=1
  define: _X86_=1
  define: __stdcall=__attribute__((__stdcall__))
  define: __fastcall=__attribute__((__fastcall__))
  define: __thiscall=__attribute__((__thiscall__))
  define: __cdecl=__attribute__((__cdecl__))
  define: __GXX_MERGED_TYPEINFO_NAMES=0
  define: __GXX_TYPEINFO_EQUALITY_INLINE=0
  define: __MSVCRT__=1
  define: __MINGW32__=1
  define: _WIN32=1
  define: __WIN32=1
  define: __WIN32__=1
  define: __WINNT=1
  define: __WINNT__=1
  define: _INTEGRAL_MAX_BITS=64
  define: __declspec(x)=__attribute__((x))
  define: __DECIMAL_BID_FORMAT__=1
  define: _REENTRANT=1
  other: --gcc
  other: --gnu_version=50300
  stdver: c11
  intelliSenseMode: gcc
queue_update_intellisense for files in tu of: D:\LENNON\16.0_MIRROR\APP\SRC\RR\UEM\CA\UEMCAAPI.C
textDocument/codeAction: 196
errorSquiggles count: 39
Update IntelliSense time (sec): 11.584
textDocument/codeAction: 197

**Comment by Lennon925** [comment]
In addition, If my code folder includes .c file and .cpp file, I should use gcc.exe or g++.exe for compilerPath?

**Comment by sean-mcmanus** [comment]
Does the error message for the missing include have a "dependency of"? Usually you can keep opening the headers to see where the source of the missing include is. I would guess some incorrect system header is going down a C++ code path instead of a C code path.

Either gcc.exe or g++.exe should work as long as the files exist and are callable -- we pass in the -x c or c++ flag depending on the file.
