### ISSUE TITLE
c_cpp_properties.json is not viable for use on teams - compilerPath needs to be more flexible

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode-cpptools#3854]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1903
- VS Code Version: 1.35.1
- C/C++ Extension Version:  0.23.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

We normally commit files like this for the workspace.  So that when team members grab the repo it will just work for them.  There are myriad problems trying to do this but one obvious one is the `compilerPath` property e.g.:
```
"compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
```
I have Enterprise but most of the rest of my team has Professional.  And even if we were all on Professional, folks are at different update levels for MSVC.  Could the compilerPath setting be modified to search for cl.exe - preferably the latest cl.exe?  Perhaps like so:
```
"compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/**/bin/Hostx64/x64/cl.exe",
```
Or maybe it could accept multiple paths:
```
"compilerPaths": [ 
  "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
  "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe"
]
```

**To Reproduce**

To try to create a c_cpp_properties.json file that gets committed to the workspace that multiple people on a team can use.  Those folks should have different editions of Visual Studio installed.

**Expected behavior**

I should be able to specify a compiler path that works across editions of Visual Studio and preferably across individual versions of the MSVC compiler.  Note: in the wildcard search case, the extension should find the **latest** version.

**Comment by sean-mcmanus** [comment]
Our code already auto-detects the user's latest installed cl.exe location if doesn't exist, so you shouldn't need to check in the compilerPath setting, i.e. can you just remove it, or are you adding arguments to the end of the path? We plan to add a separate compilerArgs setting later.

**Comment by rkeithhill** [comment]
No, not adding any cl args.  Good to know that it can be removed.  Although I don't recall adding it in the first place but it's been a while.

**Comment by sean-mcmanus** [comment]
Yeah, we auto-add the auto-detected compilerPath when it's first created, but if it doesn't exist, it will still try to auto-detect a compilerPath behind the scenes.

**Comment by Colengms** [comment]
I believe this has been addressed, since we do auto-detect the user's latest installed cl.exe location.  We have also since added the separate compilerArgs settings.  Closing this issue.  If there is still an issue, please let us know.
