### ISSUE TITLE
format down

### ISSUE THREAD

**Issue by lujfsd** [microsoft/vscode-cpptools#3859]
i got some troubles about format，
before format:
![image](https://user-images.githubusercontent.com/3353399/60375956-64205080-9a3e-11e9-9616-ff32e0c33ed7.png)
after format:
![image](https://user-images.githubusercontent.com/3353399/60375969-769a8a00-9a3e-11e9-9929-b3dac58cd0d4.png)
details below：
issues:[#76292](https://github.com/microsoft/vscode/issues/76292#issue-462015898)
someone can give me a hand
Thanks

**Comment by sean-mcmanus** [comment]
We need more repro info. Are you using multi-root? Are you using UTF-8 files? Does it repro without making other edits beforehand? Does it repro with a simple file?

**Comment by lujfsd** [comment]
![image](https://user-images.githubusercontent.com/3353399/60475248-017ebd00-9ca9-11e9-9b5f-26f1c277fe1c.png)
just main.cpp file,and encodeing with UTF-8.
Reproduce as below:
include multi file,
keep coding,coding....., the c_cpp parse is always running.... and then save file.this issue is coming.
you can try it.

**Comment by bobbrow** [comment]
I believe this issue should be fixed in version 0.25.1 of the extension.  Can you try again and let us know?

Thank you!

**Comment by lujfsd** [comment]
@bobbrow ok,I test 5 min,and this issue is not appear
