### ISSUE TITLE
Switch to using $XDG_CACHE_HOME on Linux

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3860]
Please consider using $XDG_CACHE_HOME and fall back to ~/.cache on Linux following the XDG Base directory specification: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

There's a comprehensive proposal on how files should be organized in each platform for vscode here: https://github.com/microsoft/vscode/issues/3884.

_Originally posted by @hferreiro in https://github.com/microsoft/vscode-cpptools/issues/3664#issuecomment-502411706_

**Comment by sean-mcmanus** [comment]
Also see https://github.com/microsoft/vscode-cpptools/issues/3347#issuecomment-506658208

**Comment by sean-mcmanus** [comment]
Same as https://github.com/microsoft/vscode-cpptools/issues/3860, I'll close this as a duplicate of that.

**Comment by michelleangela** [comment]
Same as #3979
