### ISSUE TITLE
cant run debugging for c programs...

### ISSUE THREAD

**Issue by venkata-ram** [microsoft/vscode-cpptools#3861]
There is no problem on debugging untill yesterday...
 But from today morning when i start debugging active file it shows "Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information."

--> E (output): {"event":"output","body":{"category":"console","output":"1: (216) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'\r\n"},"seq":2,"type":"event"}
1: (216) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions  ExePath='c:\\Users\\Venkat\\Documents\\Learn C\\nested_recrsion.exe'\r\n"},"seq":4,"type":"event"}
1: (229) LaunchOptions  ExePath='c:\Users\Venkat\Documents\Learn C\nested_recrsion.exe'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions  WorkingDirectory='C:\\Users\\Venkat\\Documents\\Learn C'\r\n"},"seq":6,"type":"event"}
1: (229) LaunchOptions  WorkingDirectory='C:\Users\Venkat\Documents\Learn C'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions  ExeArguments='2&gt;CON 1&gt;CON &lt;CON'\r\n"},"seq":8,"type":"event"}
1: (229) LaunchOptions  ExeArguments='2&gt;CON 1&gt;CON &lt;CON'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions  MIMode='gdb'\r\n"},"seq":10,"type":"event"}
1: (229) LaunchOptions  MIMode='gdb'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions  MIDebuggerPath='C:\\mingw\\mingw32\\bin\\gdb.exe'\r\n"},"seq":12,"type":"event"}
1: (229) LaunchOptions  MIDebuggerPath='C:\mingw\mingw32\bin\gdb.exe'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions  WaitDynamicLibLoad='false'\r\n"},"seq":14,"type":"event"}
1: (229) LaunchOptions  WaitDynamicLibLoad='false'
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions>\r\n"},"seq":16,"type":"event"}
1: (229) LaunchOptions>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions    <SetupCommands>\r\n"},"seq":18,"type":"event"}
1: (229) LaunchOptions    <SetupCommands>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions        <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>\r\n"},"seq":20,"type":"event"}
1: (229) LaunchOptions        <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions    </SetupCommands>\r\n"},"seq":22,"type":"event"}
1: (229) LaunchOptions    </SetupCommands>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (229) LaunchOptions</LocalLaunchOptions>\r\n"},"seq":24,"type":"event"}
1: (229) LaunchOptions</LocalLaunchOptions>
--> C (runInTerminal-26): {"command":"runInTerminal","arguments":{"kind":"integrated","title":"cppdbg: nested_recrsion.exe","cwd":"","args":["c:\\Users\\Venkat\\.vscode\\extensions\\ms-vscode.cpptools-0.23.1\\debugAdapters\\bin\\WindowsDebugLauncher.exe","--stdin=Microsoft-MIEngine-In-sxfkqyrn.az0","--stdout=Microsoft-MIEngine-Out-zufpnmf1.zbb","--stderr=Microsoft-MIEngine-Error-2tzhppaa.52x","--pid=Microsoft-MIEngine-Pid-5kxslrif.v1w","--dbgExe=C:\\mingw\\mingw32\\bin\\gdb.exe","--interpreter=mi"],"env":{}},"seq":26,"type":"request"}
--> E (output): {"event":"output","body":{"category":"console","output":"1: (354) Wait for connection completion.\r\n"},"seq":28,"type":"event"}
1: (354) Wait for connection completion.
--> E (output): {"event":"output","body":{"category":"stderr","output":"\r\n\r\n"},"seq":30,"type":"event"}

--> E (output): {"event":"output","body":{"category":"console","output":"1: (5370) Send Event AD7MessageEvent\r\n"},"seq":32,"type":"event"}
1: (5370) Send Event AD7MessageEvent
--> E (output): {"event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/MIEngine/DebuggerAborted","data":{"VS.Diagnostics.Debugger.MIEngine.DebuggerName":"GDB","VS.Diagnostics.Debugger.MIEngine.LastSentCommandName":""}},"seq":34,"type":"event"}
--> E (output): {"event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"16.1.10504.1","VS.Diagnostics.Debugger.HostVersion":"16.1.10504.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.ErrorCode":1005,"VS.Diagnostics.Debugger.Launch.IsError":true}},"seq":36,"type":"event"}
--> R (launch-2): {"request_seq":2,"success":false,"command":"launch","message":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information.","body":{"error":{"id":1005,"format":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information."}},"seq":38,"type":"response"}

**Comment by pieandcakes** [comment]
@venkata-ram Your error tells you whats wrong:
`--> R (launch-2): {"request_seq":2,"success":false,"command":"launch","message":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information.","body":{"error":{"id":1005,"format":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information."}},"seq":38,"type":"response"}`

according to your log we are looking for `gdb` here: `C:\mingw\mingw32\bin\gdb.exe`. Please make sure you have that executable.

**Comment by venkata-ram** [comment]
thank you for response.yes gdb is present in the path C:\mingw\mingw32\bin\gdb.exe and now it is fine thank you.
