### ISSUE TITLE
doesn't pick up changes in compile_commands.json at runtime.

### ISSUE THREAD

**Issue by mdzahidh** [microsoft/vscode-cpptools#3864]
Extension Version: 0.24.0-insiders3
Vscode version: 1.36.0-insider
OS: Linux, Fedora

We have a script that changes the compile_commands.json while vscode/cpptool is running, but unfortunately the cpptools doesn't seem to pick up the changes until we restart vscode (rescan workspace doesn't seem to handle this case). Are there ways to trigger this ? It would be really nice if cpptools picked up the changes automatically, especially when you are on a remote session (restarting vscode means reconnecting to the server and etc).

**Comment by sean-mcmanus** [comment]
Yeah, we have code that handles the change to the compile commands and updates the IntelliSense args, but somehow it's not working so we need to debug it further.

**Comment by Lennon925** [comment]
> Extension Version: 0.24.0-insiders3
> Vscode version: 1.36.0-insider
> OS: Linux, Fedora
> 
> We have a script that changes the compile_commands.json while vscode/cpptool is running, but unfortunately the cpptools doesn't seem to pick up the changes until we restart vscode (rescan workspace doesn't seem to handle this case). Are there ways to trigger this ? It would be really nice if cpptools picked up the changes automatically, especially when you are on a remote session (restarting vscode means reconnecting to the server and etc).

Hi, I am intersted in your mechanism how to change to compile_command.json when vscode/cpptools is running. Could you share it with me? Thanks a lot.

**Comment by sean-mcmanus** [comment]
@Lennon925 Who are you asking? Usually, your build system will regenerate the compile_commands.json (e.g. CMake). This issue was fixed already via https://github.com/microsoft/vscode-cpptools/pull/3938 and a language server change.

**Comment by Lennon925** [comment]
> @Lennon925 Who are you asking? Usually, your build system will regenerate the compile_commands.json (e.g. CMake). This issue was fixed already via #3938 and a language server change.

OK，Thanks for your reply!

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders .
