### ISSUE TITLE
Namespace Alias

### ISSUE THREAD

**Issue by suluvai** [microsoft/vscode-cpptools#387]
Trouble in resolving symbols after its namespace is aliased to a shortened version.

**Comment by cmazakas** [comment]
I wanted to bring some life back into this bug report. VSCode seems capable of using auto-complete as I type `boost::spirit::qi::phrase_parse` _but_ it has no idea if I re-alias and instead  use `namespace qi = boost::spirit::qi`

**Comment by bobbrow** [comment]
@LeonineKing1199, this works with the new IntelliSense engine.  Have you tried adding `"C_Cpp.intelliSenseEngine": "Default"` to your settings.json?

![alias](https://user-images.githubusercontent.com/12818240/27937083-8b8ee6a4-6269-11e7-85f5-2cbd78b03ed1.png)

**Comment by wolfie2x** [comment]
I had the same problem, and can confirm that setting the engine to "Default" solves it.
@bobbrow do you have any links/blogs that gives more details on the new engine? is it different to the clangd based solution? if yes, doesn't it make sense to converge on to the clangd direction?

**Comment by sean-mcmanus** [comment]
Go to Definition doesn't work on "ns::member" when using "namespace n = another::ns;". It's expected to be fixed when Go to Defintion is implemented with the IntelliSense engine. We might have another bug on this but I couldn't find it.
