### ISSUE TITLE
The flame still occurs when I switch file or open file in vscode

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3870]
Hi, I comment out these code as following in main.js which is located in cpptools installed folder, but the flame still occurs on the status bar when I open a file. How to stop symbols parsing when switching or opening a file?

`activeDocumentChanged(document) {
        this.notifyWhenReady(() => {
            //this.languageClient.sendNotification(ActiveDocumentChangeNotification, this.languageClient.code2ProtocolConverter.asTextDocumentIdentifier(document));
        });
    }`

` takeOwnership(document) {
        let params = {
            textDocument: {
                uri: document.uri.toString(),
                languageId: document.languageId,
                version: document.version,
                text: document.getText()
            }
        };
        //this.notifyWhenReady(() => this.languageClient.sendNotification(DidOpenNotification, params));
        this.trackedDocuments.add(document);
    }`

**Comment by sean-mcmanus** [comment]
Trying to disable active document change message will probably break other stuff.

The update on switching or opening files isn't expected to take more than a few seconds. Can you explain why the red flame appearing is a problem? We could potentially add some setting to configure this, but we haven't received enough complaints and neither has VS which has the same behavior.
