### ISSUE TITLE
Bad coloring of block comments in templates

### ISSUE THREAD

**Issue by hgruniaux** [microsoft/vscode-cpptools#3871]
Issue Type: <b>Bug</b>

### To reproduce
Type this in a C++ soure file (e.g. main.cpp):
```cpp
using type = another_type</* */>;
```

### Expected
The C-style block comment should be correctly highlighted.

### Actual
The comment is not correctly highlighted, instead `/* */` is considered as multiple C++ operators by the syntax highlighter.

### Screenshot
![image](https://user-images.githubusercontent.com/42495291/60593663-8a7a1f00-9da3-11e9-8ed0-4e5bc3cbb407.png)

### Other
Node, in GitHub, the code is correctly highlighted.

Also, set `C_Cpp.enhancedColorization` to `enabled` or `disabled` change nothing.

Extension version: 0.24.0-insiders3
VS Code version: Code - Insiders 1.36.0-insider (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T08:11:06.542Z)
OS version: Linux x64 5.0.0-20-generic snap

**Comment by Colengms** [comment]
Hi @HubertGruniaux .  This looks like an issue with the Text Mate grammar in VS Code insiders.  I'm not able to repro with a non-insiders build of VS Code, though it does repro if I enable the "Better C++ Syntax" extension.  ( @jeff-hykin has been contributing grammar to VS Code, which is also available in that extension).

**Comment by jeff-hykin** [comment]
This was an issue, and it was fixed just now.
@HubertGruniaux 
if you want the changes immediately, install the Better C++ Syntax extension
if you're okay with waiting a few days, you can use the VS Code Insider's release
if you're okay with waiting awhile, the changes will eventually be pulled into VS Code stable
