### ISSUE TITLE
Insider update channel not working with vscode-remote

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode-cpptools#3874]
Hello,

  VSCode recently updated to 1.36 and the Remote-SSH extension was recently updated as I was waiting for this action item to be addressed, [Handle Proxy Issues on Remote](https://github.com/microsoft/vscode-remote-release/issues/231)

  I am able to install extension on the remote session which the main extension is this one, vscode-cpptools.  This extension was installed/updated to 0.23.1.  Now, I keep getting the notification of "The C/C++ Extension has been updated to version 0.24.0-insiders3.  Please reload the window for the changes to take effect"

  After I press the "Reload" button and VSCode restarts the same message reappears after a few minutes.  I had reloaded and restarted the remote session a number of times, but I still keep getting this notification.  I am not sure this is problem with this extension or the remote extension.

  For now, I changed the configuration option C_Cpp:Update Channdel to "default" instead of "Insiders", though I would like to use the Insiders channel.

Mark

**Comment by sean-mcmanus** [comment]
This appears to be the same issue as https://github.com/microsoft/vscode-cpptools/issues/3800 . There must be some unknown failure during the installation and we don't log enough info.

0.24.0 is the latest now, but you'll probably hit the same issue again with 0.25.0-insiders.

**Comment by EmbeddedBacon** [comment]
@sean-mcmanus After seeing your post, I started a remote editing session to see if v0.24.0 would be seen and then install it.  I did install it, but as the dependencies were downloaded/installed the following was seen on the Output Window:

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)' (8683 KB)  Done!
Downloading package 'ClangFormat (Linux / x86_64)' (812 KB)  Done!
Downloading package 'Mono Framework Assemblies' (5368 KB)  Failed. Retrying...(5368 KB)  Done!
Downloading package 'Mono Runtime (Linux / x86_64)' (1862 KB)  Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Installing package 'ClangFormat (Linux / x86_64)'
Installing package 'Mono Framework Assemblies'
Failed at stage: installPackages
Error: invalid central directory file header signature: 0xbc94316e

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
```

Edit:  Okay, after shutting down VSC and re-launching the remote session it seems the installation completed okay:

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)' (8683 KB)  Done!
Downloading package 'ClangFormat (Linux / x86_64)' (812 KB)  Done!
Downloading package 'Mono Framework Assemblies' (5368 KB)  Done!
Downloading package 'Mono Runtime (Linux / x86_64)' (1862 KB)  Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Warning: File '/users/mrhicks/.vscode-server/extensions/ms-vscode.cpptools-0.24.0/bin/Microsoft.VSCode.CPP.Extension.linux' already exists and was not updated.
Warning: File '/users/mrhicks/.vscode-server/extensions/ms-vscode.cpptools-0.24.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux' already exists and was not updated.
Installing package 'ClangFormat (Linux / x86_64)'
Warning: File '/users/mrhicks/.vscode-server/extensions/ms-vscode.cpptools-0.24.0/LLVM/bin/clang-format' already exists and was not updated.
Installing package 'Mono Framework Assemblies'
Installing package 'Mono Runtime (Linux / x86_64)'

Finished installing dependencies
```

**Comment by christianparpart** [comment]
I am getting the exact same message:

```
The C/C++ Extension has been updated to version 0.25.0-insiders. Please reload the window for the changes to take effect.
```

For version 0.25.0-insiders though. I cannot get rid of it, no matter how often I click reload, and no matter how often I do a clean shutdown + restart of VSC.

I just updated VSCode and then to cpptools 0.25.0-insiders. One note to make is, that I am using remote-wsl extension to develop.

What logs could I provide you for a more detailed analysis?

**Comment by hoopoepg** [comment]
hi all
got same issue - after update to 0.25-insiders it ask to reload window to apply changes. I'm using SSH Remote plugin to Linux host.

to suppress this I updated config file:
```
<AppData>\Roaming\Code\User\settings.json
```
added string:
```
    "C_Cpp.updateChannel": "Default"
```

**Comment by bobbrow** [comment]
We knew the update didn't work in the remote sessions yet (#3833), but if it's constantly nagging you about it, we should prioritize addressing this sooner.

Opting out of the Insiders channel as mentioned by @hoopoepg or ignoring the popup are the only workarounds right now.

**Comment by christianparpart** [comment]
Thanks for taking care, @bobbrow

**Comment by sean-mcmanus** [comment]
This appears to be caused by VS Code bug https://github.com/microsoft/vscode-cpptools/issues/3874 (Command `workbench.extensions.installExtension` doesn't work on Remote Host). Not sure yet if we should try to workaround that bug or wait till they fix it?

**Comment by stevenguh** [comment]
I think you meant https://github.com/microsoft/vscode/issues/78719 filed in vs code?

**Comment by sean-mcmanus** [comment]
@stevenguh Yeah, thanks for providing the correct link :)

**Comment by stevenguh** [comment]
FYI, there is a workaround provided in the https://github.com/microsoft/vscode-remote-release/issues/1144 (which is the same issue in my last comment)

**Comment by sean-mcmanus** [comment]
You mean the workaround of unzipping the .vsix ourselves to the extensions folder? Yeah, that might work (if necessary), but I think we're just going to wait for VS Code to fix their issue.

**Comment by stevenguh** [comment]
Yes. I tried the workaround, and it works with vs code remote ssh for me. I think it make sense to wait for VS Code to fix their bug. At least there is a workaround for people eager to try.

**Comment by EmbeddedBacon** [comment]
When to update this extension for today while running VS Code 1.39.1 and now see it on the host machine, Windows 10

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (5692 KB)  Failed. Retrying...(5692 KB)  Done!
Downloading package 'ClangFormat (Windows)' (1054 KB)  Done!
Downloading package 'Visual Studio Windows Debugger' (13316 KB)  Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: invalid central directory file header signature: 0x31d1fbe6

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.

**Comment by sean-mcmanus** [comment]
@bobbrow @michelleangela @Colengms VS Code fixed their issue but we're still failing to install remotely (I tried WSL) with error "Failed to find VS Code script".

**Comment by sean-mcmanus** [comment]
The Insider channel should work with vscode-remote with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3 (after we have our next Insiders available).

**Comment by robertcinciuc** [comment]
@hoopoepg Your solution worked for me! Thank you!
