### ISSUE TITLE
Support for `/std:c++latest`, `c++2a`, etc.

### ISSUE THREAD

**Issue by zhiayang** [microsoft/vscode-cpptools#3879]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10, 1903
- VS Code Version: 1.36.0
- C/C++ Extension Version: 0.24.0

**To Reproduce**
1. Change the value of `cppStandard` in `c_cpp_properties.json` to something like `c++latest` or `c++2a`.
2. Plugin complains that it is not one of the accepted values, which must be one of `c++98, c++03, etc. etc.`

It would be very useful to add support for the latest language features if they are available. I'm not sure how the intellisense engine works on Windows, but for Linux/OSX where (presumably) it's done by calling the compiler binary, being able to pass `-std=c++2a` through the configuration would be nice, instead of having to manually set that as the argument (and by extension providing a `compilerPath`).

Not sure how it works on Windows (if the extension calls the installed MSVC or it's a totally separate thing), but it would be nice if some C++20 features were supported as well, especially since I can set `/std:c++latest` on MSVC and have great things like designated initialisers when using VS 2019.

**Comment by bobbrow** [comment]
We are planning to add this for the next release.  Currently, our `c++17` value should actually be `c++latest` right now though.  But do note however, the MSVC compiler and the IntelliSense engine are not synchronized to the exact same set of features.

**Comment by sean-mcmanus** [comment]
C++20 is being tracked by https://github.com/microsoft/vscode-cpptools/issues/3448 , so I think this issue is a duplicate.

There shouldn't be a need to expose compiler-specific "c++latest" or "c++2a".

We're using c++latest with msvc mode, but the compiler version hasn't been updated to the latest VS 2019 cl.exe yet, so lots of the C++20 features are not working.

**Comment by bobbrow** [comment]
Thanks @sean-mcmanus, I was thinking we had an issue for this already, but was clearly searching with the wrong keywords. 😄

**Comment by zhiayang** [comment]
Ah, my bad, that didn't turn up when I was searching. Thanks for clearing that up!

**Comment by sean-mcmanus** [comment]
We added some support for C++20 with 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders . But additional C++20 features will be added in the next release.
