### ISSUE TITLE
Microsoft.VSCode.CPP.Extension.linux Segmentation fault on Redhat when using Remote extension (get_working_set_size)

### ISSUE THREAD

**Issue by MyFreeGit** [microsoft/vscode-cpptools#3880]
I use VSC 1.36 with remote development extension with SSH to Red Hat linux server. All source code and building tools are located in Red Hat linux server. The C/C++ extension version is 0.24 which is installed and running on linux. The VSC client is running on windows laptop.
The C/C++ extension has crashed a few times. I use the gdb to check the coredump, I've found:
Core was generated by `/home/worker/.vscode-server/extensions/ms-vscode.cpptools-0.24.0/bin/Microsoft.V'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000062eb2e in intellisense_client::get_working_set_size() ()
[Current thread is 1 (Thread 0x7f6bd57fa700 (LWP 12402))]
(gdb) bt
#0  0x000000000062eb2e in intellisense_client::get_working_set_size() ()
#1  0x0000000000658682 in intellisense_client_mapping::update_for_max_size() ()
#2  0x000000000064882b in create_async_work(char const*, std::string const&, char const*, int, unsigned long, std::shared_ptr<browse_engine>, std::shared_ptr<compilation_args_provider>, std::function<void (std::vector<std::shared_ptr<intellisense_client>, std::allocator<std::shared_ptr<intellisense_client> > >)>, std::function<void (std::string const&)>) ()
#3  0x00000000006520d0 in std::_Function_handler<void (), intellisense_client_factory::create_async(char const*, char const*, char const*, int, std::shared_ptr<browse_engine>, std::shared_ptr<compilation_args_provider>, std::function<void (std::vector<std::shared_ptr<intellisense_client>, std::allocator<std::shared_ptr<intellisense_client> > >)>, std::function<void (std::string const&)>)::$_2>::_M_invoke(std::_Any_data const&) ()
#4  0x00000000006f3a72 in std::_Function_handler<void (), msvc::thread_pool::enqueue(std::function<void ()>, std::future<void>*)::$_2>::_M_invoke(std::_Any_data const&) ()
#5  0x00000000006f2704 in msvc::thread_pool::do_work(unsigned long) ()
#6  0x0000000000cadbdf in execute_native_thread_routine ()
#7  0x00007f6c38b53dd5 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f6c3887cead in clone () from /lib64/libc.so.6
(gdb) l
1       ../../../libgcc/libgcc2.c: No such file or directory.
(gdb) 
The project that I have working is very big, about 100Mb source code.

**Comment by sean-mcmanus** [comment]
This is our 2nd highest hitting main process crash, but the number of users affected seems low.

**Comment by bobbrow** [comment]
We believe this issue has been fixed.  Please update to the latest version of the extension and if you continue to see the problem, let us know.  Thank you!
