### ISSUE TITLE
#if <define> == <value> not being recognised and greyed out correctly

### ISSUE THREAD

**Issue by WattsC-90** [microsoft/vscode-cpptools#3881]
**Type: LanguageService**

The VSCode editor appears to be misunderstanding or not interpreting #if statements correctly in the code I am viewing. 

The scenario:

my C file looks like this: 
```
#define MYDEFINE 3

#if MYDEFINE == 2
    //highlights
#elif MYDEFINE == 1
    //greyed out
#elif MYDEFINE == 3
    //greyed out
#else
    //greyed out
#endif
```

**Describe the bug**
- OS and Version: Win 10, 1809 - 17763.557
- VS Code Version: 1.35.1
- C/C++ Extension Version: 0.24.0 (i think)
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
![image](https://user-images.githubusercontent.com/10712792/60707074-c37cd580-9f02-11e9-92a4-0df81a3a59ce.png)
The image shows the exact issue. nothing else is in this file.

**Expected behavior**
The area should grey out appropriately

**Additional context**
None

**Comment by zhiayang** [comment]
This is not a bug with the compiler or the extension, this is a part of the C preprocessor. Going through the steps:

1. You have defined `MYVAR` to be `hello`, so doing the replacement:
```c
// #define MYVAR hello

#if hello == goodbye
	tst = "a";
#elif hello == hello
	tst = "b";
#endif
```

2. Neither `goodbye` nor `hello` are defined. When the preprocessor encounters undefined symbols, it substitutes 0:

```c
// #define MYVAR hello
#if 0 == 0
	tst = "a";
#elif 0 == 0
	tst = "b";
#endif
```

3. Only the first true branch is evaluated. `0 == 0` is `true`, so the first branch is valid, and is *not* greyed out, while the second branch is greyed out.

EDIT: for what it's worth, your original example can't be reproduced (0.24.0 also):
![Capture](https://user-images.githubusercontent.com/500236/60710899-3d827e00-9f46-11e9-873e-956a3cdce25c.PNG)

**Comment by WattsC-90** [comment]
@zhiayang Thank you, it makes sense, and then also makes sense why the original example works, as the numbers are already defined. I am not particularly adept with C, as you can tell.  Sorry to have wasted your time.
