### ISSUE TITLE
fails to install with latest version

### ISSUE THREAD

**Issue by dennykhoerniawan** [microsoft/vscode-cpptools#3884]
Hi,

After 0.24.0 update, I keep getting
//////////////////////////////////////////////////////////////////
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)' (8683 KB)  Done!
Downloading package 'ClangFormat (Linux / x86_64)' (812 KB)  Done!
Downloading package 'Mono Framework Assemblies' (5368 KB)  Done!
Downloading package 'Mono Runtime (Linux / x86_64)' (1862 KB)  Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Failed at stage: installPackages
Error: Unknown system error -122: Unknown system error -122, close

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
//////////////////////////////////////////////////////////////////

Tried installing it manually but still not working. Sometimes I get similar error, sometimes VSCode is just loading it without success. VSCode version 1.35

I use OSX but my code lives on a linux VM on a remote host that I access using remote-ssh

**Comment by michelleangela** [comment]
Hi @dennykhoerniawan,

Is it correct that you are trying to install on your Linux machine? Could you provide the system information of the machine you're trying to install it to?

Did installation work on your previous upgrades or manual installation of the extension? If so, did you do anything differently before?

**Comment by dennykhoerniawan** [comment]
@michelleangela, just edited the original post, im using my mac, accessing code on a linux server using remote-ssh extension, red hat rel7 to be exact.

I use the extensions tool to install it previously, and it was working fine. when I open extensions in VSCode it shows 2 sections, "Local - installed" and "ssh: <host-name>: installed".  Other C/C++ Intellisense tools I have tried before automatically goes to that section, that is why I assume everything is good. Just realized after this error that it is the linux version that is being used automatically.

Only started seeing this issue when I reloaded VSCode and it automatically installs the latest version. Tried installing it manually, even the previous version, but nothing happens. There is a blue bar near the top of extensions tab that keeps moving as if it is trying to do something but never finishes.

**Comment by michelleangela** [comment]
I searched for the error code "122" from "Unknown system error -122", this [post on error-122](https://github.com/npm/npm/issues/16604) says it's an error on disk quota exceeded. Can you try to do a manual install or upgrade of some large npm packages and see if you get the same error?

**Comment by dennykhoerniawan** [comment]
@michelleangela, seems like youre right, i tried deleting the older version that was still there to make space and reinstall the extension and it works.

And I just found out that I am only allowed to have 1GB in my home directory. So to solve my issues in long term, I need to understand what those files are, and how to remove them out of my home directory. Do you know how to configure the path for it to be somewhere else? And is the file going to keep growing?

~$ du -mh -d 1 ~/.vscode-server/data/User/workspaceStorage/2772fc37b7af4d976c74f0ba6f290ecd/
788M	/users/dkhoerni/.vscode-server/data/User/workspaceStorage/2772fc37b7af4d976c74f0ba6f290ecd/ms-vscode.cpptools
788M	/users/dkhoerni/.vscode-server/data/User/workspaceStorage/2772fc37b7af4d976c74f0ba6f290ecd/

**Comment by michelleangela** [comment]
The VS Code workspaceStorage is always on the home drive. However, you can change the path where the C/C++ extension stores the Tag Parser's browse symbol database to be elsewhere other than under the default workspaceStorage location. To change the default path, set `C_Cpp.default.browse.databaseFilename` to your desired location. The database will increase with the size of its associated workspace.

Other files you can move or not have the C/C++ extension generate are the cached ipch files IntelliSense creates to improve #include header processing. You can change the default location of the cache path by setting `C_Cpp.intelliSenseCachePath`. You can stop the creation of the ipch files by disabling IntelliSense caching by setting `C_Cpp.intelliSenseCacheSize` to 0.
