### ISSUE TITLE
range-based loop pretty printing

### ISSUE THREAD

**Issue by infalmo** [microsoft/vscode-cpptools#3887]
When using range-based loop, some unwanted info is shown in the variables. Only the value of the variable should be shown in my opinion.
![Screenshot from 2019-07-06 20-38-51](https://user-images.githubusercontent.com/45997896/60757914-641be400-a02e-11e9-9515-469134654be5.png)

**Comment by pieandcakes** [comment]
@infixint943 We don't control what is printed during pretty-printing. All of that comes from the Python pretty printers installed with `gdb`.

**Comment by infalmo** [comment]
Any idea on how to manually correct this?
