### ISSUE TITLE
No way to disable C style comment automatic closing tags

### ISSUE THREAD

**Issue by hpg-mheck** [microsoft/vscode-cpptools#3891]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
Any
- VS Code Version:
Current as of 07JUL2019
- C/C++ Extension Version:
Current as of 07JUL2019
- Other extensions you installed (and if the issue persists after disabling them):
Persists with cpptools only
- A clear and concise description of what the bug is.
When I type forward slash asterisk ("/*"), a space, another asterisk, and another forward slash is immediately included.  This should never occur even if failing to do so results in famine and torture.  Since it causes cancer, rioting, and occasional harsh language, I would like to shut it off, but after thorough searching, I can find no option to do so.  I do NOT necessarily wish to break alphanumeric symbol completion when typing actual code outside of a comment block.

**To Reproduce**

1. Start Visual Studio Code with cpptools installed.
2. Create a new source or header file.
3. Type ['forward slash', 'asterisk']; that is, "/*"
4. Observe that the actual inserted character sequence is "/* */".
5. Riot.

**Expected behavior**

The expected behavior is that, with an appropriate configuration option set, the sequence of events should be:
1. Start Visual Studio Code with cpptools installed.
2. Create a new source or header file.
3. Type ['forward slash', 'asterisk']; that is, "/*"
4. Observe that the actual inserted character sequence is "/*", ONLY.
5. Enjoy a deep sense of inner peace, knowing that your tools haven't gotten in your way and embarrassed themselves again.

**Screenshots**

+----------+
|    /* */    |
+----------+
(shot on iPhone)

**Comment by sean-mcmanus** [comment]
I have also hit this issue and been "annoyed" by the result when I want `/*comment*/`. However, it's caused by VS Code itself and not our extension. Can you file your issue at https://github.com/microsoft/vscode/issues ?

**Comment by michelleangela** [comment]
Please up vote the duplicate issue on VS Code: https://github.com/microsoft/vscode/issues/54793.
