### ISSUE TITLE
Question: Ipch file can be zipped to shrink storage space?

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3893]
Currently ipch file is very large and occupies large storage space. These files can be zipped to shrink storage space? And what is storaged in these ipch files?

**Comment by michelleangela** [comment]
The ipch files serve as precompiled headers for the IntelliSense engine; the files have precompiled headers information on #include files in a source file. These cached ipch files can reduce the parsing time of #include files in a source file to speedup IntelliSense processing time. The IntelliSense engine reads and uses an ipch file anytime it is processing a source file, and it looks for ipch files specifically. If the ipch files were to be zipped, IntelliSense would not be find them and create a new one. The files can be zipped, but they will need to be extracted again prior to IntelliSense startup and usage for the source file that the ipch is associated with.

IntelliSense caching or generation of the ipch files can be disabled by setting `C_Cpp.intelliSenseCacheSize` to 0.

For more information about precompiled headers created by IntelliSense engine and how they are used, here is a blog post [explaining their usage in Visual Studio](https://devblogs.microsoft.com/cppblog/precompiled-header-files-in-visual-studio-2010/). Here is the blog post about [IntelliSense cache added to the VS Code Microsoft C/C++ extension](https://devblogs.microsoft.com/cppblog/visual-studio-code-c-c-extension-march-2019-update/).
