### ISSUE TITLE
Cplex configration on Linux (c++ compliler and linker options)

### ISSUE THREAD

**Issue by Jesmine0902** [microsoft/vscode-cpptools#3895]
Type: General
**Input information below**
I want to use Cplex in my c++ program. However, the configuration is confusing. In the tutorial, I need to finish two configurations: compiler and linker options. The details are shown as bellow.
[https://www.ibm.com/support/knowledgecenter/SSSA5P_12.8.0/ilog.odms.cplex.help/CPLEX/GettingStarted/topics/set_up/GNU_Linux.html](url)

Compiler options
Tell your compiler where to find the include directory for both CPLEX C++ API and Concert C++ API, substituting the correct path of your installation and the correct version number, like this:
> -I/path/to/cplex/cplexXX/includeCopy
> -I/path/to/cplex/concertYY/includeCopy

Give your compiler a preprocessor directive by means of the option -D, like this:
> -DIL_STD

Linker options

Tell your linker where to search for both the CPLEX and Concert libraries, like this, substituting the correct path of your installation and the correct version numbers:

> -L/path/to/cplex/cplexXX/lib/archi/tectureCopy

> -L/path/to/cplex/concertYY/lib/archi/tectureCopy

Specify the libraries to your linker, like this:

> -lilocplex -lconcertCopy

Here is the correct order of the builds of the libraries:

> -lilocplex -lconcert -lcplex -lm -lpthread

**Describe the bug**
- OS and Version: Ubuntu 18
- VS Code Version: 1.35
- C/C++ Extension Version: 7.4.0 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I only included the path in the c_cpp_properties.json. For the following steps, I don't know how to set the configuration. 

So far, the error is "ilolpex1.cpp:22:10: fatal error: ilcplex/ilocplex.h: No such file or directory
 #include <ilcplex/ilocplex.h>"

**To Reproduce**
*Please include code sample and `task.json` files.*
code sample is 
`#include <ilcplex/ilocplex.h> 
ILOSTLBEGIN

static void
   usage (const char *progname),
   populatebyrow     (IloModel model, IloNumVarArray var, IloRangeArray con),
   populatebycolumn  (IloModel model, IloNumVarArray var, IloRangeArray con),
   populatebynonzero (IloModel model, IloNumVarArray var, IloRangeArray con);

int
main (int argc, char **argv)
{
   IloEnv   env;
   try {
      IloModel model(env);

      if (( argc != 2 )                         ||
          ( argv[1][0] != '-' )                 ||
          ( strchr ("rcn", argv[1][1]) == NULL )   ) {
         usage (argv[0]);
         throw(-1);
      }

      IloNumVarArray var(env);
      IloRangeArray con(env);

      switch (argv[1][1]) {
         case 'r':
            populatebyrow (model, var, con);
            break;
         case 'c':
            populatebycolumn (model, var, con);
            break;
         case 'n':
            populatebynonzero (model, var, con);
            break;
      }

      IloCplex cplex(model);
      cplex.exportModel("lpex1.lp");

      // Optimize the problem and obtain solution.
      if ( !cplex.solve() ) {
         env.error() << "Failed to optimize LP" << endl;
         throw(-1);
      }

      IloNumArray vals(env);
      env.out() << "Solution status = " << cplex.getStatus() << endl;
      env.out() << "Solution value  = " << cplex.getObjValue() << endl;
      cplex.getValues(vals, var);
      env.out() << "Values        = " << vals << endl;
      cplex.getSlacks(vals, con);
      env.out() << "Slacks        = " << vals << endl;
      cplex.getDuals(vals, con);
      env.out() << "Duals         = " << vals << endl;
      cplex.getReducedCosts(vals, var);
      env.out() << "Reduced Costs = " << vals << endl;
   }
   catch (IloException& e) {
      cerr << "Concert exception caught: " << e << endl;
   }
   catch (...) {
      cerr << "Unknown exception caught" << endl;
   }

   env.end();

   return 0;
}  // END main

static void usage (const char *progname)
{
   cerr << "Usage: " << progname << " -X" << endl;
   cerr << "   where X is one of the following options:" << endl;
   cerr << "      r          generate problem by row" << endl;
   cerr << "      c          generate problem by column" << endl;
   cerr << "      n          generate problem by nonzero" << endl;
   cerr << " Exiting..." << endl;
} // END usage

// To populate by row, we first create the variables, and then use them to
// create the range constraints and objective.

static void
populatebyrow (IloModel model, IloNumVarArray x, IloRangeArray c)
{
   IloEnv env = model.getEnv();

   x.add(IloNumVar(env, 0.0, 40.0));
   x.add(IloNumVar(env));
   x.add(IloNumVar(env));

   model.add(IloMaximize(env, x[0] + 2 * x[1] + 3 * x[2]));

   c.add( - x[0] +     x[1] + x[2] <= 20);
   c.add(   x[0] - 3 * x[1] + x[2] <= 30);

   x[0].setName("x1");
   x[1].setName("x2");
   x[2].setName("x3");

   c[0].setName("c1");
   c[1].setName("c2");
   model.add(c);

}  // END populatebyrow

// To populate by column, we first create the range constraints and the
// objective, and then create the variables and add them to the ranges and
// objective using column expressions.

static void
populatebycolumn (IloModel model, IloNumVarArray x, IloRangeArray c)
{
   IloEnv env = model.getEnv();

   IloObjective obj = IloMaximize(env);
   c.add(IloRange(env, -IloInfinity, 20.0, "c1"));
   c.add(IloRange(env, -IloInfinity, 30.0, "c2"));

   x.add(IloNumVar(obj(1.0) + c[0](-1.0) + c[1]( 1.0), 0.0, 40.0));
   x.add(IloNumVar(obj(2.0) + c[0]( 1.0) + c[1](-3.0)));
   x.add(IloNumVar(obj(3.0) + c[0]( 1.0) + c[1]( 1.0)));

   x[0].setName("x1");
   x[1].setName("x2");
   x[2].setName("x3");

   model.add(obj);
   model.add(c);

}  // END populatebycolumn

// To populate by nonzero, we first create the rows, then create the
// columns, and then change the nonzeros of the matrix 1 at a time.

static void
populatebynonzero (IloModel model, IloNumVarArray x, IloRangeArray c)
{
   IloEnv env = model.getEnv();

   IloObjective obj = IloMaximize(env);
   c.add(IloRange(env, -IloInfinity, 20.0));
   c.add(IloRange(env, -IloInfinity, 30.0));

   x.add(IloNumVar(env, 0.0, 40.0));
   x.add(IloNumVar(env));
   x.add(IloNumVar(env));

   obj.setLinearCoef(x[0], 1.0);
   obj.setLinearCoef(x[1], 2.0);
   obj.setLinearCoef(x[2], 3.0);

   c[0].setLinearCoef(x[0], -1.0);
   c[0].setLinearCoef(x[1],  1.0);
   c[0].setLinearCoef(x[2],  1.0);
   c[1].setLinearCoef(x[0],  1.0);
   c[1].setLinearCoef(x[1], -3.0);
   c[1].setLinearCoef(x[2],  1.0);

   c[0].setName("c1");
   c[1].setName("c2");

   x[0].setName("x1");
   x[1].setName("x2");
   x[2].setName("x3");

   model.add(obj);
   model.add(c);
}  // END populatebynonzero
`
task.json
`
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "g++",
            "args": [
                "ilolpex1.cpp",
                "-o",
                "cplex_test"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
}
`

**Expected behavior**
I have worked on this problem for several days but still, have no idea. Could you please tell me the detailed steps of how to set the configuration? Thank you very much!

**Comment by sean-mcmanus** [comment]
This doesn't appear to be a question on how to configure our C/C++ extension. You should try to get your code and Cplex to compile on the command line first (or using the build task). Maybe the Cplex developers can help?

The c_cpp_properties.json does not get used by your compiler to build. It is only used for configuring our IntelliSense parser.

**Comment by bobbrow** [comment]
> Compiler options
>Tell your compiler where to find the include directory for both CPLEX C++ API and Concert C++ API, substituting the correct path of your installation and the correct version number, like this:
>> -I/path/to/cplex/cplexXX/includeCopy
>> -I/path/to/cplex/concertYY/includeCopy

> Give your compiler a preprocessor directive by means of the option -D, like this:
>> -DIL_STD

> Linker options

> Tell your linker where to search for both the CPLEX and Concert libraries, like this, substituting the correct path of your installation and the correct version numbers:

>> -L/path/to/cplex/cplexXX/lib/archi/tectureCopy

>> -L/path/to/cplex/concertYY/lib/archi/tectureCopy

>Specify the libraries to your linker, like this:

>> -lilocplex -lconcertCopy

>Here is the correct order of the builds of the libraries:

>> -lilocplex -lconcert -lcplex -lm -lpthread

Can you try adding those switches to your `tasks.json`?  Anything you would specify on the command line can be added to the build task.  For example:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "g++",
            "args": [
                "ilolpex1.cpp",
                "-I/path/to/cplex/cplexXX/includeCopy",
                "-I/path/to/cplex/concertYY/includeCopy",
                "-DIL_STD",
                "-o",
                "cplex_test"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
}
```
