### ISSUE TITLE
{}__7 appears many times in the Outline panel with new files

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3897]
Hello everybody, I am having an "opposite" broblem. When i create new .cpp or .h file, the outline panel display many line with content "{}__7". Is this another bug?
![image](https://user-images.githubusercontent.com/47727306/60762195-d3242780-a084-11e9-96a0-794536fc4758.png)
My system infomation:

- OS: Ubuntu 18.04.2 LTS (Linux kernel 4.18.0-25-generic)
- VS Code version 1.36
- Extension: ms-vscode.cpptools 1.24

_Originally posted by @LongChampion in https://github.com/microsoft/vscode-cpptools/issues/3877#issuecomment-508961246_

**Comment by sean-mcmanus** [comment]
@LongChampion That is a strange bug. I haven't been able to repro it yet though. It's possible it could be fixed in our next update, but I'm not sure. Is this a regression from 0.23.1 (or one of the 0.24.0-insiders releases)?

@Colengms @michelleangela Are you able to repro it?

**Comment by michelleangela** [comment]
I cannot repro this either. Were there specific steps done when creating the folder and new .cpp or .h files?

**Comment by LongChampion** [comment]
@sean-mcmanus 
This is a video show how to repos this issue.
[https://drive.google.com/open?id=12E4GPqlI8mLO72xhNZtsDpK6Z4zy8LiC](https://drive.google.com/open?id=12E4GPqlI8mLO72xhNZtsDpK6Z4zy8LiC)
My settings.json
![image](https://user-images.githubusercontent.com/47727306/60871120-551a7900-a25c-11e9-9a9c-4d40cdbdbeb9.png)
I am using ms-vscode.cpptools 0.24.0 (NOT insider build)

**Comment by michelleangela** [comment]
@LongChampion , thank you for the repro video (very helpful!). I was able to repro this as well now. The data showing up in the outline pane view seems to be stale data.

**Comment by sean-mcmanus** [comment]
This isn't a regression from 0.23.1. It won't be fixed in 0.24.1. Not 100% sure yet when it will be fixed.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.25.0.
