### ISSUE TITLE
Microsoft.VSCode.cpp.extension.exe does not exit on deactivate causing uninstall to fail on windows

### ISSUE THREAD

**Issue by jacdavis** [microsoft/vscode-cpptools#39]
1) Install the extension and open a cpp file to start intellisense. 
2) Uninstall the extension
3) Check the .vscode folder or look at the running processes

EXPECTED: extension is removed
ACTUAL: Microsoft.VSCode.CPP.Extension.exe is left behind because it is running.

**Comment by delmyers** [comment]
@sridmad

**Comment by sridmad** [comment]
These issues should be resolved with 0.7.0 of the extension. Please reopen the issue if you continue to see the behavior.
