### ISSUE TITLE
Comment block always auto-adds end symbol

### ISSUE THREAD

**Issue by rewrking** [microsoft/vscode-cpptools#3904]
Type: General
This started happening in one of the recent extension updates.
Let's say you want to comment out some c++ code that's already written somewhere (an extremely common use-case). Typing "/*" now auto-adds "*/" directly after it. This is super annoying because you have to backspace out the last 2 characters.

**Describe the bug**
- OS and Version: all
- VS Code Version: 1.36.0
- C/C++ Extension Version: 0.24.0
- Other extensions you installed (and if the issue persists after disabling them):
       Disabled others & confirmed it's this extension
- A clear and concise description of what the bug is.

**To Reproduce**
1. Write any c++ code inside of a .cpp/h/hpp etc file.
2. Type "/*" at the begging of of a line that has already been written
3. Notice "*/" gets automatically added afterwards, but before the code, so nothing actually gets commented out

Simple example, where "|" denotes the cursor position:
```
/*| */void mySoonToBeCommentedFunction() {}
```

**Expected behavior**
"/*" shouldn't auto-add the end symbol of the comment block by default, should be setting controlled, and should be able to recognize when it's been entered at the start of a line.

**Comment by michelleangela** [comment]
Duplicate of #3891.

This is caused by VS Code and not the extension. Please file the issue at https://github.com/microsoft/vscode/issues.

**Comment by rewrking** [comment]
I'm seeing more and more issues passing the buck off to the vscode team. Don't you folks communicate with them at all?

...Also this literally only happens with C++ code. How could this not be extension related?

**Comment by michelleangela** [comment]
It's not extension related because the issue reproduces with the extension disabled.

VS Code issues that impact our extension are reported to the VS Code team like any other VS Code issue would be reported. On some occasion and depending on the severity of the issue, we will also communicate with them offline to raise the priority of the issue, but we will still open a GitHub issue on their repro as it is how they keep track of issues on their end.

**Comment by michelleangela** [comment]
@andrew-r-king , just an FYI, I found the duplicate issue on VS Code https://github.com/microsoft/vscode/issues/54793. Please up vote it to increase its priority.

**Comment by rewrking** [comment]
Thanks. Found a workaround too:
https://github.com/microsoft/vscode/issues/77008#issuecomment-509765216
