### ISSUE TITLE
Using clang-cl.exe as a compilerPath doesn't work with clang-x64 intelliSenseMode

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3906]
It ends up falling back to another compiler, such as WSL.

clang-cl.exe should be treated like clang-x64 mode with -fms-extensions -- and possibly other config changes that we may not be handling currently. I believe originally, we expected clang-cl.exe to run with msvc-x64 mode (i.e. treated exactly like cl.exe, with no system include/define querying).

Originally reported at https://github.com/microsoft/vscode-cpptools/issues/3898 .

**Comment by Colengms** [comment]
Note: clang-cl appears to accept cl command line args, so needs to be treated as cl in regards to command line args, but treated as clang otherwise.

**Comment by sean-mcmanus** [comment]
It looks like special args can be used, such as `clang-cl.exe -TP -v -E -Xclang -dM nul`

**Comment by Colengms** [comment]
I believe this should be addressed, as of 0.26.3-insiders, as previously we were not probing clang-cl correctly.
