### ISSUE TITLE
Extension randomly takes up to 90% of my CPU usage, often times when not in use.

### ISSUE THREAD

**Issue by bettyleung** [microsoft/vscode-cpptools#3909]
Issue Type: <b>Bug</b>

No paticular action causes this to occur. It happens randomly when VScode is open on my computer. 

Extension version: 0.24.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 2|
|Memory (System)|16.00GB (2.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Are you opening a workspace with C++ files? What process is using CPU? You could also [enable debug logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) to get more info about what is going on. Setting C_Cpp.workspaceParsingPriority to "low" may also help, or using the Pause Parsing command.

**Comment by bettyleung** [comment]
Are you opening a workspace with C++ files? 
Yes.

What process is using CPU? 
"Microsoft.VSCode.CPP.Extension" and "Code Helper"

Ok I will try turning on logging and setting C_Cpp.workspaceParsingPriority to "low" .
