### ISSUE TITLE
F12 key aslo opens the peek definition view

### ISSUE THREAD

**Issue by suluvai** [microsoft/vscode-cpptools#391]

**Comment by sean-mcmanus** [comment]
Yeah, I'm seeing this bug. Did VS Code regress us?

**Comment by bobbrow** [comment]
Are you still having this issue?  If the symbol is defined in multiple locations, the peek definition view opens up to help disambiguate.

**Comment by sean-mcmanus** [comment]
Yeah, this is by design. I'm closing it. It doesn't repro if there's only 1 definition found.
