### ISSUE TITLE
[macOs] Build and Debug Active file fails with PreLaunch task  'Build' terminated with exit code 1.

### ISSUE THREAD

**Issue by NasserAlhouti** [microsoft/vscode-cpptools#3911]
I'm having issues trying to get Clang ++ debugger to work I've followed the instructions on the website https://code.visualstudio.com/docs/languages/cpp I got the intellisense, I compiled my C++ using g++ followed by -g and the file path as shown
nasser$ g++ -g /Users/nasseralhouti/algo/twoSumNumber.cpp
this created an a.out file under my .vscode directory 
I set the debugger to c++ build and debug active 
but when I run the debugger it outputs PreLaunch task  'Build' terminated with exit code 1.
so I'm assuming it's something in my tasks.json file which is 
![Screen Shot 2019-07-10 at 8 26 20 PM](https://user-images.githubusercontent.com/30329703/61020017-11ee0200-a351-11e9-9bf6-5724dd3b2691.jpg)

since this was preconfigured I'm not really sure how it works 
since the intelisense is working I'm assuming my /Users/nasseralhouti/algo/.vscode/c_cpp_properties.json 
works fine 
so does it have to do with my tasks.json  not finding the xcode path debugger ?
looking at the lauch.json I'm not really sure what's it used for 
![Screen Shot 2019-07-10 at 8 19 57 PM](https://user-images.githubusercontent.com/30329703/61019918-b9b70000-a350-11e9-9690-36d60160fdd6.jpg)

I would like the problem to be resolved but more importantly understand how my json files are configured so that I could figure out how to fix future configurations problems like debugging in dart or angular.

**Comment by pieandcakes** [comment]
@NasserAlhouti You chose `Build and Debug Active File` and the `task.json` does the `Build` portion of that task. If you want to skip the build, you can remote the `preLaunchTask` and it won't try and run the `task.json` task anymore.

If you want help with your `task.json`, can you share the output window text from the failure? It should show the command being run and then the output.

**Comment by NasserAlhouti** [comment]
Yeah sure so this is the error I get 
![Screen Shot 2019-07-11 at 10 36 29 PM](https://user-images.githubusercontent.com/30329703/61104863-ab3e1680-a42c-11e9-9a57-0086663e7c06.jpg)
and when I click on show errors this is what pops up on my terminal 
![Screen Shot 2019-07-11 at 10 37 47 PM](https://user-images.githubusercontent.com/30329703/61104890-c7da4e80-a42c-11e9-9d99-3e10dbb28d92.jpg)

**Comment by NasserAlhouti** [comment]
I think I figured it out I followed the instructions on this page 
https://code.visualstudio.com/docs/cpp/config-clang-mac
and found that you could configure your tasks.json and lauch.json to be the same but change your ouput files and cpp file I wasn't aware that the tasks.json file was acctually building the executable while you ran it  which was causing me a lot of confusion since before I even touch those two files I had everything built using the integrated command line prompt 
I also had to change my .bash_profile script because it requires you  to enter in a password if you use database server but that was interfering with the vscode debugger so I just commented it out and added my arguments from my regular terminal not the integrated one and everything worked like a charm xD
I really appreciate your help : )
