### ISSUE TITLE
new input verification of configurations.includePath fails to verify multiple paths in single env variable

### ISSUE THREAD

**Issue by mistersandman** [microsoft/vscode-cpptools#3912]
The example `c_cpp_properties.json` provided [here](https://github.com/microsoft/vscode-cpptools/blob/53107bc57ca9c0e772a8d73746e1caf4612568db/Documentation/LanguageServer/c_cpp_properties.json.md) reports the problem `Cannot find "<workspaceFolder>;<workspaceFolder>\include".`

The issue is that the path array `configurations.includePath` contains the env variable `${myDefaultIncludePath}` which again is a path array that gets flattened into a semi-colon separated path list. However, the input validation for `configurations.includePath` wrongly expects a single path per entry, as can be seen here: https://github.com/microsoft/vscode-cpptools/blob/53107bc57ca9c0e772a8d73746e1caf4612568db/Extension/src/LanguageServer/configurations.ts#L1012-L1014

The issue only concerns validation, since the actual processing of `cofigurations.includePaths` https://github.com/microsoft/vscode-cpptools/blob/53107bc57ca9c0e772a8d73746e1caf4612568db/Extension/src/LanguageServer/configurations.ts#L540 handles path arrays in env variables correctly by using `resolveAndSplit` inside `updateConfiguration` https://github.com/microsoft/vscode-cpptools/blob/53107bc57ca9c0e772a8d73746e1caf4612568db/Extension/src/LanguageServer/configurations.ts#L513-L529

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.25.0.

**Comment by mistersandman** [comment]
I can confirm the fix in 0.25.0. Thanks!
