### ISSUE TITLE
Incorrect Error Squiggles on Various User- and Library-Defined Symbols

### ISSUE THREAD

**Issue by kenny1983** [microsoft/vscode-cpptools#3915]
**Type: LanguageService**
 
**Describe the bug**
 
* OS and Version: Windows 10 x64 1903
* VS Code Version: 1.36.1 (user setup)
* C/C++ Extension Version: 0.24.0
* Other extensions you installed (and if the issue persists after disabling them): C# and NuGet Package Manager (yes)
* A clear and concise description of what the bug is:

This issue is similar to #3910, except that I get the error squiggles for some library-defined symbols as well.

I'm building an old-school MFC app and as such am not surprised that I'm having this issue, especially considering that just setting up the workspace took me the better part of an entire day (including the download and install of the MSVC Build Tools).

I've followed all suggestions in [this documentation page](https://code.visualstudio.com/docs/cpp/config-msvc) for setting up VS Code to work with the MSVC Build Tools, except that I have an MSBuild command in my build task since that seemed simpler than writing a mile-long CL command.

That may not actually be the case since, as I said above, figuring out how to use MSBuild in a tasks.json configuration took me forever. But in any case, I digress...the point is that I finally have everything building and launching properly, but now I have supposed errors all over my code!

As described in the aforementioned #3910, I can F12 to the correct definition of any of these marked-as-erroneous symbols and in **that** file, everything is fine! But unlike that issue, the incorrect markings **never go away**! To make matters even more confusing, the code suggestion/completion features of IntelliSense **do** work for some, **but not all**, of the incorrectly-marked symbols.

I've tried uninstalling and reinstalling the extension but that doesn't seem to help, and I don't even have the faintest idea of what to try next. So any help would be very much appreciated! Here's my workspace config files in case they may provide some clues:

c_cpp_properties.json:
```
{
    "configurations": [{
        "name": "Win32",
        "defines": [
            "_DEBUG",
            "UNICODE",
            "_UNICODE"
        ],
        "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x86/cl.exe",
        "windowsSdkVersion": "10.0.18362.0",
        "cStandard": "c11",
        "cppStandard": "c++17"
    }],
    "version": 4
}
```
tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [{
        "label": "Build",
        "type": "shell",
        "command": "${workspaceFolder}\\build.bat",
        "args": [ "amd64_x86" ],
        "group": {
            "kind": "build",
            "isDefault": true
        },
        "presentation": {
            "clear": true,
            "reveal": "never"
        }
    }]
}
```
The `build.bat` file referenced as the command to run is a 322-line batch file that I hacked together from VS' `vcvarsall.bat`. It basically just sets up the environment needed for MSBuild to work, but yeah...322 lines just to do something as **seemingly** simple as that! I won't include it here since I doubt it has anything to do with the problem and because it's so long, but just LMK if you'd like to see it anyway ;-)

launch.json:
```
{
    "version": "0.2.0",
    "configurations": [{
        "name": "Host User",
        "type": "cppvsdbg",
        "request": "launch",
        "preLaunchTask": "Build",
        "program": "${workspaceFolder}\\Debug\\Messenger.exe",
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}"
    }, {
        "name": "Extra User",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "${workspaceFolder}\\Debug\\Messenger.exe",
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}"
    }]
}
```
MTIA for any light shed on this confusing and frustrating problem! And BTW, kudos for all the great work otherwise; when not building something as complex as this your extension works flawlessly and is an absolute must-have IMO! :D

**Comment by kenny1983** [comment]
UPDATE: Just realised after all this time that I never had includePath set in c_cpp_properties.json! I feel so ridiculously foolish and ashamed...although I guess that's what 36 hours of no sleep will do to you! :P

Now after getting a good night's rest I have set that parameter properly, which has greatly reduced but still not fixed all of the incorrect error markings. In particular, I'm being told that `identifier "IDP_SOCKETS_INIT_FAILED" is undefined` even though I have the correct definition in `afxsock.h`, which is correctly included through `stdafx.h`.

**Comment by sean-mcmanus** [comment]
The IntelliSense compiler is somehow not finding the definition. You can try to isolate the potential cause and/or use logging to help. There is a known bug that in certain cases, macros will become undefined if duplicate `#includes` are used. One thing to be careful of is that Go to Def on the header file might not go to the same file that IntelliSense is using. So I would guess either the wrong header files are being used or there are defines not being set that are required for the identifier to be defined.

**Comment by kenny1983** [comment]
> There is a known bug that in certain cases, macros will become undefined if duplicate `#includes` are used.

Do you mean doing something like this?
```
// foo.h
#pragma once

class Foo {
    // Definition of class
    ...
}

// foo.cpp
#include "Foo.h"

// other code
...

// bar.cpp
#include "Foo.h"
```
I have `stdafx.h` included in every source file (of course) so that may be the issue...?

> You can try to isolate the potential cause and/or use logging to help.

What exactly do you mean by "isolate the potential cause"? Comment stuff out until there's no errors, then slowly add stuff back in to see what causes the problem? And how do I enable/view the IntelliSense compiler logs?

MTIA Sean, and keep up the great work! :D

P.S. You also mentioned including the wrong headers, so could you please confirm that the correct path for the 2019 build tools is `C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/atlmfc/include`? Also, you tagged this issue with more info needed, so if you could tell me exactly what else you need in order to help you help me, I would be more than happy to oblige! Thanks again :-)

**Comment by sean-mcmanus** [comment]
I mean like
```
#include "Foo.h"
...
#incluee "Foo.h"
```
Your example seems okay. stdafx.h should be okay.

Yeah, commenting stuff out or using smaller files and C/C++ Log Diagnostics and [debug logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md).

The atlmfc/include is one path, but there should also be a higher level include as well -- we should be automatically finding these paths.

It could also be a corrupt ipch file (setting intelliSenseCacheSize to 0 temporarily might fix it).

**Comment by kenny1983** [comment]
> I mean like
> 
> ```
> #include "Foo.h"
> ...
> #include "Foo.h"
> ```
Well that's just silly! I would go back to Programming 101 classes if I found myself doing anything like that! :P

stdafx.h does include **every** header in the project (all 8 of them) because when I started this project, I was a much younger, lazier and obviously-less-experienced developer. I thought "Hey cool I can just include everything in this PCH thingy, and no more #include statements! Yay!". I just noticed this after you got me thinking about extra includes and seriously wanted to deck myself LOL. Now I have 257 errors to resolve by taking them out of the PCH and putting them where they belong...what fun! Especially when IntelliSense isn't working! :P

Anyway thanks for the suggestions; I'll let you know how they go!

**Comment by kenny1983** [comment]
OK so after taking my project headers (not STL or external library headers) out of stdafx.h and fixing the ensuing mess, I now have everything building correctly again. And guess what? That seems to have been the cause of this issue!

The only things I see in the "Problems" window now are 4 instances of...no, now they're gone too haha! I literally **just** saw 4 errors related to missing STL headers being reported, but after switching to Chrome to write this and switching back, they're now gone too :D:D

Do you still want to see my logs in case this error pops up again in the future for someone else? They probably won't show anything useful anyway, since the problems are now all gone.

**Comment by kenny1983** [comment]
Scatch that last comment; it seems to have started happening again, although not as frequently. Here's a debug trace log:
```
textDocument/codeAction: 1747
Request canceled: 1744
textDocument/documentSymbol: 1748
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/Dev/Hobby_Programming/C%2B%2B/MFC/Messenger/Messenger.cpp
queue_update_intellisense for files in tu of: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
sending 1 changes to server
cpptools/textEditorSelectionChange
errorSquiggles count: 30
errorSquiggles count: 0
Update IntelliSense time (sec): 0.69
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/Dev/Hobby_Programming/C%2B%2B/MFC/Messenger/Messenger.cpp
queue_update_intellisense for files in tu of: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
errorSquiggles count: 1
errorSquiggles count: 0
Update IntelliSense time (sec): 0.316
  tag parsing file: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
Database safe to open
textDocument/didSave
  tag parsing file: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/Dev/Hobby_Programming/C%2B%2B/MFC/Messenger/Messenger.cpp
queue_update_intellisense for files in tu of: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
errorSquiggles count: 1
errorSquiggles count: 0
Update IntelliSense time (sec): 0.365
Database safe to open
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileDeleted
cpptools/fileDeleted
Database safe to open
textDocument/didChange
cpptools/textEditorSelectionChange
Checking for syntax errors: file:///d%3A/Dev/Hobby_Programming/C%2B%2B/MFC/Messenger/Messenger.cpp
queue_update_intellisense for files in tu of: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
textDocument/codeAction: 1750
textDocument/didChange
cpptools/textEditorSelectionChange
sending 19 changes to server
errorSquiggles count: 2
errorSquiggles count: 0
Update IntelliSense time (sec): 0.356
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/codeAction: 1751
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/codeAction: 1752
textDocument/didChange
cpptools/textEditorSelectionChange
Checking for syntax errors: file:///d%3A/Dev/Hobby_Programming/C%2B%2B/MFC/Messenger/Messenger.cpp
queue_update_intellisense for files in tu of: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
textDocument/codeAction: 1753
textDocument/didChange
cpptools/textEditorSelectionChange
sending 27 changes to server
errorSquiggles count: 0
errorSquiggles count: 0
Update IntelliSense time (sec): 0.285
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/codeAction: 1754
textDocument/documentSymbol: 1755
Checking for syntax errors: file:///d%3A/Dev/Hobby_Programming/C%2B%2B/MFC/Messenger/Messenger.cpp
queue_update_intellisense for files in tu of: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
sending 1 changes to server
errorSquiggles count: 1
errorSquiggles count: 0
Update IntelliSense time (sec): 0.301
textDocument/codeAction: 1756
  tag parsing file: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/codeAction: 1757
Request canceled: 1755
textDocument/documentSymbol: 1758
Checking for syntax errors: file:///d%3A/Dev/Hobby_Programming/C%2B%2B/MFC/Messenger/Messenger.cpp
queue_update_intellisense for files in tu of: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
sending 1 changes to server
errorSquiggles count: 0
errorSquiggles count: 0
Update IntelliSense time (sec): 0.282
textDocument/codeAction: 1759
  tag parsing file: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
Database safe to open
textDocument/hover: 1760
cpptools/textEditorSelectionChange
textDocument/codeAction: 1761
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1762
cpptools/textEditorSelectionChange
textDocument/codeAction: 1763
textDocument/documentHighlight: 1764
Request canceled: 1764
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1765
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1766
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1767
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1768
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1769
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1770
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1771
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1772
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1773
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1774
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1775
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1776
Request canceled: 1776
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1777
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1778
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1779
Request canceled: 1779
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1780
Request canceled: 1780
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1781
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/Dev/Hobby_Programming/C%2B%2B/MFC/Messenger/Messenger.cpp
queue_update_intellisense for files in tu of: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
textDocument/codeAction: 1782
errorSquiggles count: 29
errorSquiggles count: 0
Update IntelliSense time (sec): 0.315
textDocument/codeAction: 1783
textDocument/documentHighlight: 1784
cpptools/textEditorSelectionChange
textDocument/codeAction: 1785
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1786
cpptools/textEditorSelectionChange
textDocument/codeAction: 1787
textDocument/documentHighlight: 1788
cpptools/textEditorSelectionChange
textDocument/codeAction: 1789
textDocument/documentHighlight: 1790
cpptools/textEditorSelectionChange
textDocument/codeAction: 1791
textDocument/documentHighlight: 1792
cpptools/textEditorSelectionChange
textDocument/codeAction: 1793
textDocument/documentHighlight: 1794
cpptools/textEditorSelectionChange
textDocument/codeAction: 1795
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 1796
cpptools/textEditorSelectionChange
textDocument/codeAction: 1797
textDocument/codeAction: 1798
textDocument/hover: 1799
Request canceled: 1799
textDocument/hover: 1800
textDocument/hover: 1801
textDocument/hover: 1802
textDocument/codeAction: 1803
cpptools/textEditorSelectionChange
textDocument/codeAction: 1804
textDocument/hover: 1805
Request canceled: 1805
textDocument/hover: 1806
Request canceled: 1806
textDocument/hover: 1807
Request canceled: 1807
textDocument/hover: 1808
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/Dev/Hobby_Programming/C%2B%2B/MFC/Messenger/Messenger.cpp
queue_update_intellisense for files in tu of: D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
textDocument/codeAction: 1809
errorSquiggles count: 0
errorSquiggles count: 0
Update IntelliSense time (sec): 0.31
textDocument/codeAction: 1810
```
And the log diagnostics report:
```
-------- Diagnostics - 13/07/2019, 6:50:24 am
Version: 0.24.0
Current Configuration:
{
    "name": "Win32",
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x86/cl.exe",
    "includePath": [
        "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/atlmfc/include"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "browse": {
        "path": [
            "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/atlmfc/include",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[D:\Dev\Hobby_Programming\C++\MFC\Messenger\Messenger.cpp]:
    D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
    D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.H
    D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\STDAFX.H
[D:\Dev\Hobby_Programming\C++\MFC\Messenger\MessageServer.cpp]:
    D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSAGESERVER.CPP
    D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\STDAFX.H
[D:\Dev\Hobby_Programming\C++\MFC\Messenger\MessageServerApp.h]:
    D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSAGESERVER.H
Translation Unit Configurations:
[D:\Dev\Hobby_Programming\C++\MFC\Messenger\Messenger.cpp]:
    Process ID: 3916
    Memory Usage: 92 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x86/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\BUILDTOOLS\VC\TOOLS\MSVC\14.21.27702\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\BUILDTOOLS\VC\TOOLS\MSVC\14.21.27702\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++latest
    IntelliSense Mode: msvc-x64
[D:\Dev\Hobby_Programming\C++\MFC\Messenger\MessageServer.cpp]:
    Process ID: 8000
    Memory Usage: 136 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x86/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\BUILDTOOLS\VC\TOOLS\MSVC\14.21.27702\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\BUILDTOOLS\VC\TOOLS\MSVC\14.21.27702\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++latest
    IntelliSense Mode: msvc-x64
[D:\Dev\Hobby_Programming\C++\MFC\Messenger\MessageServerApp.h]:
    Process ID: 12840
    Memory Usage: 10 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x86/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\BUILDTOOLS\VC\TOOLS\MSVC\14.21.27702\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\BUILDTOOLS\VC\TOOLS\MSVC\14.21.27702\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++latest
    IntelliSense Mode: msvc-x64
    Other Flags:
        --header_only_fallback
Total Memory Usage: 238 MB

-------- Diagnostics - 13/07/2019, 8:28:32 am
Version: 0.24.0
Current Configuration:
{
    "name": "Win32",
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x86/cl.exe",
    "includePath": [
        "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/atlmfc/include"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "browse": {
        "path": [
            "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/atlmfc/include",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[D:\Dev\Hobby_Programming\C++\MFC\Messenger\Messenger.cpp]:
    D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.CPP
    D:\DEV\HOBBY_PROGRAMMING\C++\MFC\MESSENGER\MESSENGER.H
Translation Unit Configurations:
[D:\Dev\Hobby_Programming\C++\MFC\Messenger\Messenger.cpp]:
    Process ID: 7496
    Memory Usage: 235 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x86/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\BUILDTOOLS\VC\TOOLS\MSVC\14.21.27702\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\BUILDTOOLS\VC\TOOLS\MSVC\14.21.27702\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++latest
    IntelliSense Mode: msvc-x64
Total Memory Usage: 235 MB
```

**Comment by sean-mcmanus** [comment]
What file has errors squiggles? (looks like Messenger.cpp from the logs). What is the error message? Are you saying there are temporary invalid error squiggles? After editing? Do they go away after switching files or doing a save?

**Comment by kenny1983** [comment]
> What file has errors squiggles? (looks like Messenger.cpp from the logs).

Yeah that log was taken from Messenger.cpp, but it happens intermittently on all files.

> What is the error message?

It varies widely, but the most prevalent are incorrect "undefined identifier" errors and "name followed by '::' must be a class or namespace name", which then results in a cascade of others. So the IntelliSense engine seems to think that the class declaration in the header is missing or invalid, but only until I make a change, close the file or switch to another.


> Are you saying there are temporary invalid error squiggles? After editing? Do they go away after switching files or doing a save?

Yes. Sometimes changing a file causes it; sometimes it fixes it. Same with switching files. It seems as though if I hover over a definition or declaration that's erroneously marked, it **usually** (but not always) goes away. And when I have no more error squiggles after a bunch of changes, attempting to build will suddenly cause 20 - 30 squiggles in Messenger.cpp (the main app class), even though the build succeeds.

I also just noticed that clicking on a reported issie in the "Problems" window will invariably make it disappear.

I'll do some more in-depth testing across various files and send you another debug log. Thanks again for your continued help with this mate :D

**Comment by kenny1983** [comment]
BTW the extension works flawlessly in a pure WinAPI project, so I think this has a lot/maybe everything to do with MFC. And as I said before, fixing the PCH (which the pure WinAPI project doesn't have) improved things drastically. However, I just tried disabling the IS PCH cache and it seems to have made things worse again!

**Comment by bobbrow** [comment]
Does this issue still happen with the latest version of the extension? Are you able to share any code that causes this issue to reproduce?
