### ISSUE TITLE
The extension downloads binary blobs without asking

### ISSUE THREAD

**Issue by marmistrz** [microsoft/vscode-cpptools#3919]
Type: General

**Describe the bug**
- OS and Version: Arch Linux, latest
- VS Code Version: code 1.36.0-1 from the repos
- C/C++ Extension Version: 0.24.0
- Other extensions you installed: N/A
- A clear and concise description of what the bug is.

**To Reproduce**

1. Install the extension
2. Open any C/C++ file (this may not actually be needed)

**Expected behavior**
If the Mono, clang-format, etc. binaries are missing from the system (e.g. cannot be found in `PATH`), the extension should ask the user if they want to have them downloaded.

**Actual behavior**
If the Mono, clang-format, etc. binaries are missing from the system (e.g. cannot be found in `PATH`), the extension downloads them without asking.

**Additional context**
I definitely don't want the extension to fetch any blobs from the Internet without asking.

**Comment by pieandcakes** [comment]
@marmistrz We need those specific items to use the extension on the platform and we use this method to avoid downloading bits for all platforms for extension users. We need VS Code and the extension gallery to allow us to create/download platform specific packages to avoid doing this.

If you don't want them to be downloaded separately on demand, you can download our offline installers on our [releases](https://github.com/microsoft/vscode-cpptools/releases) page and that will have all the parts already included.

**Comment by marmistrz** [comment]
@pieandcakes, I don't understand, why can't the extension ask before downloading? That's what the official Rust extension does, for example.

The bad part is not that it downloads something, but that it doesn't ask the user for permission.

**Comment by sean-mcmanus** [comment]
@marmistrz When you installed the C++ extension, VS Code itself downloads a vsix with the contents -- the only difference is that a per-OS vsix hasn't been implemented yet (it is planned to be in the couple months, so this won't be an issue after that), but until then it requires us to do a 2nd download of the OS-specific bits which weren't in the vsix that was originally downloaded. So the permission to download the remaining components of our extension is implicitly given when the extension is installed. I don't think we want to unnecessarily prompt users before doing the download.

**Comment by pieandcakes** [comment]
@marmistrz The downloads are a necessary requirement that will be downloaded every time else the extension will not run. As @sean-mcmanus mentioned you would always get a prompt and we want to shift away from having to download additional dependencies and will do so when VS Code implements a way to avoid it. For now, if you want to avoid us automatically downloading files, you can download the offline package.

**Comment by michelleangela** [comment]
@marmistrz , the offline packages are available here per release version: https://github.com/microsoft/vscode-cpptools/releases

**Comment by marmistrz** [comment]
I disagree. I can and I should install clang-format (and possibly the Mono runtime) through my package manager (from the repositories)

**Comment by pieandcakes** [comment]
@marmistrz I can't speak to `clang-format` but for debugging we are using a specific version of `mono` due to dependencies in our code.

**Comment by sean-mcmanus** [comment]
The reason we download clang-format is so the formatting feature works if the user doesn't have it installed (although there are certain Linux versions where it will fail to run still due to missing shared library dependencies). You can set the clang_format_path to be the version installed from your package manager. We have another feature request open for making it use the clang-format on the path by default instead of our installed one (which is the older 6.0 still). The clang-format extension doesn't download any clang-format binary.

**Comment by marmistrz** [comment]
Thanks for the detailed and swift replies, sounds fair enough! :)
