### ISSUE TITLE
pretty-printing not working with MinGW GDB

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode-cpptools#3921]
Same problem! Vectors doesn't show its elements.
I'm currently using this task file:

>     "version": "2.0.0",
>     "tasks": [
>         {
>             "label": "echo",
>             "type": "shell",
>             "command": "g++",
>             "args": [
>                 "-g", "${relativeFile}", "-o", "example"
>             ],
>             "group": {
>                 "kind": "build",
>                 "isDefault": true
>             }
>         }
>     ]
> }

and this launch file:

> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "(gdb) Launch",
>             "type": "cppdbg",
>             "request": "launch",
>             "program": "${workspaceFolder}/example.exe",
>             "args": [],
>             "stopAtEntry": false,
>             "cwd": "${workspaceFolder}",
>             "environment": [],
>             "externalConsole": true,
>             "MIMode": "gdb",
>             "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
>             "preLaunchTask": "echo",
>             "setupCommands": [
>                 {
>                     "description": "Enable pretty-printing for gdb",
>                     "text": "-enable-pretty-printing",
>                     "ignoreFailures": true
>                 }
>             ]
>         }
>     ]
> }

Has anybody found any solution for MinGW (windows 10)? Enabling pretty printing didn't help.
Thanks!

_Originally posted by @tomas-silveira in https://github.com/microsoft/vscode-cpptools/issues/1768#issuecomment-507073918_

**Comment by pieandcakes** [comment]
Same problem here: no string values in debugger/variables window.
OS: Windows 10, VS Code 1.36, g++ 8.2.0, gdb 7.6.1
I got just MinGW from https://osdn.net/projects/mingw/
Should I try another distro with more recent versions, switch to a different OS or abandon any hope for now?

_Originally posted by @tdjastrzebski in https://github.com/microsoft/vscode-cpptools/issues/1768#issuecomment-510677351_

**Comment by pieandcakes** [comment]
@tdjastrzebski Do you see a difference in how it is visualized if you remove the pretty-printer line in your `launch.json` ?

To add to that, it looks like MinGW ships a separate `gdb` that has Python enabled as Python is what does the pretty-printing. You may need to point your `miDebuggerPath` to that. Online searches tells me it should be in the same folder as `gdb` but called something like `gdb-python27.exe`.

_Originally posted by @pieandcakes in https://github.com/microsoft/vscode-cpptools/issues/1768#issuecomment-510680506_

**Comment by pieandcakes** [comment]
@pieandcakes Thank you for your help. There is no apparent difference after removing **pretty-printer**.
This particular MinGW distribution I installed does not contain any other gdb*, besides gdbserver.exe.
The other two distributions I found:
https://sourceforge.net/projects/mingw-w64/
https://mingw-w64.org/doku.php/download
do not install at all or are very difficult to configure - at best.
Please advise.

![vs code gdb 1](https://user-images.githubusercontent.com/7325277/61108980-06e7be80-a484-11e9-8a09-95a071d6ffd4.png)

_Originally posted by @tdjastrzebski in https://github.com/microsoft/vscode-cpptools/issues/1768#issuecomment-510774779_

**Comment by tdjastrzebski** [comment]
@pieandcakes Note I did not try the latest MinGW version.
g++ was ver 8.2.0, gdb 7.6.1

**Comment by pieandcakes** [comment]
@tdjastrzebski Would you be able to run `info pretty-printer` in your version of `gdb` and see if any pretty printers exist for the type you want? That command should show all the pretty printers in that version of `gdb`. I suspect that it is missing files.

**Comment by eacheveryhour** [comment]
> 
> 
> @tdjastrzebski Would you be able to run `info pretty-printer` in your version of `gdb` and see if any pretty printers exist for the type you want? That command should show all the pretty printers in that version of `gdb`. I suspect that it is missing files.

@pieandcakes 
Mingw has 3 gdbinit files. Like shown:
![image](https://user-images.githubusercontent.com/10809110/69851180-a7177600-12b3-11ea-850b-ca7575f46214.png)

Two of them is missing `register_libstdcxx_printers (None)` line.
Add a register line to all of them, and thats it.
Now for `gdb info pretty-printing`:
![image](https://user-images.githubusercontent.com/10809110/69851348-0ecdc100-12b4-11ea-8065-8182684d4a1c.png)

**Comment by yanglr** [comment]
Firstly, you probably used x64 Windows.

I found one valid solution, when installing MinGW in x64 Windows, install `i686 (win32)` version of MinGW instead of `x86_64` version, see below:

![pretty-printing-not-work-with-MinGW GDB-solution](https://user-images.githubusercontent.com/3152813/108173684-6797ac80-7139-11eb-9d03-9eee32578458.png)
