### ISSUE TITLE
Target app (UE4 project editor) won't launch with LLDB debugger (Linux)

### ISSUE THREAD

**Issue by danich93** [microsoft/vscode-cpptools#3924]
Type: Debugger

- OS and Version: Linux (Manjaro)
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.0
- Other extensions you installed: Mono debug, Python, C#.
- A clear and concise description of what the bug is.

When trying to debug an UE4 editor project with a launch command with lldb debugger, the app technically starts (it hangs in processes), but the window never actually shows up. Debugger seems to succesfully start and load symbols too, but the process stops at shader compilation step (which is really supposed to be happening when the editor is already loaded).
In fact, shaders are already compiled, and should not be recompiled again. I'm also able to launch and debug the very same project with gdb just fine.

launch.json task:

```
{
	"name": "TestProjectEditor (Debug)",
	"request": "launch",
	"preLaunchTask": "TestProjectEditor Linux Debug Build",
	"program": "/home/danich/Documents/UnrealEngine/Engine/Binaries/Linux/UE4Editor-Linux-Debug",
	"args": [ 
		"/home/danich/Documents/UnrealEngine/Games/TestProject/TestProject.uproject" 
	],
	"cwd": "/home/danich/Documents/UnrealEngine",
	"MIMode": "lldb",
	"type": "cppdbg"
},
```

1. Download and compile UE4 from source
2. Create any template c++ project
3. Launch the debugger with lldb config
4. See the process being stuck on shader compilation

Console log:
[lldb.log](https://github.com/microsoft/vscode-cpptools/files/3388338/lldb.log)

**Comment by pieandcakes** [comment]
Is your issue compilation or debugging? 

If its compilation you'll need to seek out someone who knows your project.

If its debugging, can you enable [engineLogging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging) and let me know what comes back?  We ship a version of `lldb-mi` for macOs and if you are using it on Linux, you need to specify `miDebuggerPath` to your version of `lldb-mi`.

**Comment by danich93** [comment]
hi @pieandcakes ,
yes indeed, the problem is with debugger (or, should I say, with launching with debugger attached), compilation step goes fine.
I've done what you requested and here's a new log file for you.
[debug.log](https://github.com/microsoft/vscode-cpptools/files/3393707/debug.log)

**Comment by pieandcakes** [comment]
@Ohmu93 According to the log, the application is running under the debugger. I see where we send `-exec-run` and then when we stop on `main()` we send `-exec-continue` and after that i don't see any stopping event. 

Can you describe more what you are expecting to happen?

**Comment by danich93** [comment]
@pieandcakes Yes, I do see that the process (both debugger and application) are listed in the task manager, and are active. What I don't see is the application window (in my case that would be UE4 editor window). It works fine with gdb, but once I switch to lldb it just never shows up. (So basically my problem is that the app window never appears on the screen). If you have any idea what I could try that would be great, cause im really at a loss here :/

**Comment by pieandcakes** [comment]
@Ohmu93  me too. I don't know what would be causing that. you may try and ask on one of the mailing lists at lldb.llvm.org and see if someone who works on lldb can help you.

**Comment by danich93** [comment]
@pieandcakes Thank you for your time. I'll see if I can ask them or find a problem myself.

**Comment by pieandcakes** [comment]
Thanks. I'll close this for now then as it looks like an `lldb` problem. Feel free to reopen with new information when you have it.
