### ISSUE TITLE
[Question] Which language server do you use? Ccls or Clangd?

### ISSUE THREAD

**Issue by ianyepan** [microsoft/vscode-cpptools#3925]
As titled.

**Comment by sean-mcmanus** [comment]
The C/C++ extension implements its own language server in the Microsoft.VSCode.CPP.Extension process.

**Comment by ianyepan** [comment]
Thanks for the reply.

**Comment by cstrahan** [comment]
@sean-mcmanus May I ask, where is the source located?

Edit: for the native binary, that is.

**Comment by sean-mcmanus** [comment]
@cstrahan It's not available to people external to Microsoft (i.e. closed source). Only our TypeScript component is open source.
