### ISSUE TITLE
the autocomplete is Incomplete

### ISSUE THREAD

**Issue by lujfsd** [microsoft/vscode-cpptools#3926]
Issue Type: <b>Bug</b>
it's just has two method in vscode
![image](https://user-images.githubusercontent.com/3353399/61191828-7ad2d280-a6e1-11e9-8882-ceaa641e6f44.png)
but in the qt creator ,it's full method
![image](https://user-images.githubusercontent.com/3353399/61191862-bc637d80-a6e1-11e9-9c1a-29c9327677b5.png)

and it's slowly.look at [issue#3907](https://github.com/microsoft/vscode-cpptools/issues/3907#issue-466082627)

Extension version: 0.24.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by SchwarzeMagier** [comment]
I have the same problem. when I use `std::unique_ptr`, the autocomplete is incomplete, but I use `std::shared_ptr` is ok.
![1](https://user-images.githubusercontent.com/13066061/62032192-a7c3d100-b21b-11e9-8ca0-73774c5ce37d.png)
![2](https://user-images.githubusercontent.com/13066061/62032392-215bbf00-b21c-11e9-9bec-a511c91c426c.png)

**Comment by sean-mcmanus** [comment]
I believe this is a duplicate of the fixed bug https://github.com/microsoft/vscode-cpptools/issues/3930 . The fix should be in our next Insider release.

**Comment by sean-mcmanus** [comment]
The fix should be in 0.25.0-insiders2: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders2 .
