### ISSUE TITLE
${fileBasename} 变量包含了扩展名

### ISSUE THREAD

**Issue by yycalm** [microsoft/vscode-cpptools#393]
launch.json中，${fileBasename} 变量包含了扩展名

"program":"${workspaceRoot}/${fileBasename}.exe",  展开后是"program":"d:/test/filename.cpp.exe",

我想要的是"program":"d:/test/filename.exe".

**Comment by pieandcakes** [comment]
@yycalm the replacement texts for ${workspaceRoot} and ${fileBasename} come from VS Code. Please file this issue under https://github.com/microsoft/vscode/issues.
