### ISSUE TITLE
No method hints provided when using smart pointers

### ISSUE THREAD

**Issue by yaroslavsadin** [microsoft/vscode-cpptools#3930]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7 64-bit
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.0: July 3, 2019
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
See screenshots

**Description**
When using smart pointers (unique_ptr) and type -> opeartor, the engine doesn't give hints on the class methods except for destructor. The same happens when I try to get the regular pointer with .get() method and apply -> to it. Only when I create explicit pointer variable it does show methods list. Is this a bug related to smart pointers?
Thanks.

**Screenshots**
![image](https://user-images.githubusercontent.com/6427691/61240659-6d056780-a74a-11e9-9d7c-e28397aa98a4.png)
![image](https://user-images.githubusercontent.com/6427691/61240719-89a19f80-a74a-11e9-86a6-770cc892d2ca.png)

**Comment by sean-mcmanus** [comment]
A workaround is to type ->, hit Esc to cancel the popup, then use Ctrl+Space to invoke "manual completion" which bypasses our "is it accessible" checking.

I've filed a bug at https://developercommunity.visualstudio.com/content/problem/645202/c-intellisense-completion-is-hiding-accessible-met.html . If you have a Microsoft account you can upvote that.

**Comment by sean-mcmanus** [comment]
The fix should be in 0.25.0-insiders2: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders2 .

**Comment by luohancfd** [comment]
![violentmonkey](https://user-images.githubusercontent.com/6806720/85642822-82745880-b660-11ea-98da-7001b1805a98.gif)

I'm still experiencing the issue. `error` is defined as `Error *&error;` and `all` is a method. I'm using vscode for remote WSL

Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.28.3
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
