### ISSUE TITLE
Cannot turn off block comment autocompletion

### ISSUE THREAD

**Issue by davidgiven** [microsoft/vscode-cpptools#3935]
**Type: LanguageService**

**Describe the bug**
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.0-5-amd64
C/C++ extension version: 0.24.0

I cannot find any way to turn off block comment autocompletion. I've searched the settings multiple times, asked questions on SO, etc.

- if there isn't a way to turn it off, there should be --- I find it incredibly jarring and it makes typing comments difficult.
- if there is a way to turn it off, it's not discoverable enough.

**To Reproduce**

Type `/*` into a text editor. You'll get `/* | */` (where the | represents the position of the cursor.) I want a way to make it not do this, so I just get `/* |` (i.e. it just entered what I typed).

**Comment by sean-mcmanus** [comment]
This is a VS Code bug, fixed on the latest VS Code Insiders release. See https://github.com/microsoft/vscode/issues/77008 .

**Comment by davidgiven** [comment]
Wow, that was a quick fix! Thanks!
