### ISSUE TITLE
"December update" link broken

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#394]
> Version 0.9.3: December 8, 2016
> [December update](https://aka.ms/cppvscodedec) for C/C++ extension

The link is broken. When visiting the blog, I can't seem to find any new blog post since Nov 16. Forgotten to publish?

**Comment by sean-mcmanus** [comment]
I think it should be posted later today. [Edit: I was wrong. It wasn't. I don't have an ETA yet.]

**Comment by csholmq** [comment]
I see. Just eager to see what's been keeping the update for over two months. Documentation is lacking on configuration, but I guess that's also coming along.

**Comment by sean-mcmanus** [comment]
I suspect we're not publicly disclosing the reason for the update delay in the blog. The debugger part was updated, but the language service executable actually has not been updated, although an update for that is expected within a month.

**Comment by csholmq** [comment]
Too bad. This project could use some more transparency.

Looking forward to remote attach and better autocomplete! :)

**Comment by delmyers** [comment]
@sean-mcmanus, @csholmq 
There isn't really any secret to why the language service didn't update this time around. There were just some late bugs that were found in the language service that we didn't want to release. There were some significant changes to the debugger, though, so we decided to release the debugger without the changes to the language service.

**Comment by sean-mcmanus** [comment]
Yeah, we found regressions that we're fixing so we delayed updating the language service. However, I think he wants to know why the last update was September 22. Previously, we had an update schedule that was a lot shorter. There is a reason (on the language service side), but I'm not sure if I'm allowed to be more transparent :)

**Comment by delmyers** [comment]
@sean-mcmanus, it isn't a big deal. We just had bugs to work through and not enough time to work on them. Finally, we decided to release the debugger and not the language service. Hopefully we will be able to pick things up on the language service side and release an update there too.

**Comment by csholmq** [comment]
Appreciating all of your work. I hope you reach a stage when you can open source this extension as well. Hopefully accelerates the bug squashing and allows for more on features.

**Comment by PerMildner** [comment]
The link "December update" points at https://aka.ms/cppvscodedec which takes me to https://www.microsoft.com/sv-se/. That is, for me the link is completely broken and does not bring me to an out-of-date blog or anything like that.

**Comment by csholmq** [comment]
@PerMildner The blog I'm referring to is https://blogs.msdn.microsoft.com/vcblog/.
That is where the "August update" points to. Ultimately, when the post has been published, there is where you would find it.

**Comment by pieandcakes** [comment]
@PerMildner @csholmq we will get the blog posted soon. The person in charge of writing the blog is currently out of the office and has been trying to work when he has time. The new blog explains the two debugger features mentioned in the readme.MD file -- `sourceFileMap` and having gdb's pretty-printing defaulted in newly created `launch.json` file.

**Comment by csholmq** [comment]
Link now works!
