### ISSUE TITLE
go wrong definition locations in remote development mode

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#3947]
Cpptools Version：0.24.0
VsCode Version：1.36.1

I tried vscode remote development mode today and installed cpptools 0.24.0. And found these issues:

- "go to definition" can't go to right definition locations

- Colorazation seem to be broken for unknown reasons.

**Comment by sean-mcmanus** [comment]
I think colorization is tracked by https://github.com/microsoft/vscode-cpptools/issues/3942 .

We haven't heard about Go to Definition not working yet, so it sounds like we may need to investigate.

**Comment by Lennon925** [comment]
> I think colorization is tracked by #3942 .
> 
> We haven't heard about Go to Definition not working yet, so it sounds like we may need to investigate.

Maybe this is related with file encoding

**Comment by sean-mcmanus** [comment]
Are you suggesting the Go To Def issue may not be related to "remote development".

**Comment by Lennon925** [comment]
> Are you suggesting the Go To Def issue may not be related to "remote development".

Yes, I remembered that I was using a GB2312 code file to test.

**Comment by ranjithpp** [comment]
as per the comments in https://github.com/microsoft/vscode-remote-release/issues/320, it is said that need to install extention in SSH box ,any citation about how to install it ?

**Comment by sean-mcmanus** [comment]
@ranjithpp In the Extensions view the Local section will show "Install in" buttons for extensions that aren't installed remotely.

**Comment by ranjithpp** [comment]
Thanks, i managed to install and it is working fine

**Comment by bobbrow** [comment]
It appears that the issues in this bug report are tracked by other issues.
