### ISSUE TITLE
Strange Outline returned for files outside the workspace that are in the `files.exclude` list

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3949]
This issue is different from https://github.com/microsoft/vscode-cpptools/issues/3877 and reproes with 0.23.1 too (and the pending 0.24.1). It only repros if the file hasn't been tag parsed yet, i.e. after a Reset IntelliSense Database or when a new folder is opened or some other file that isn't in the browse.path is opened.

The code is supposed to wait till the file is parsed.

**Comment by bobbrow** [comment]
This could be a regression in 0.27.0-insiders3.  Incorrect stuff is reported in the outline view for files outside the workspace folder (single root):

![image](https://user-images.githubusercontent.com/12818240/77118234-f9aaa880-69f0-11ea-9d14-f9e2420baf22.png)

**Comment by sean-mcmanus** [comment]
I'm not able to repro that -- any idea what the repro requirements are? The symptoms are the same as https://github.com/microsoft/vscode-cpptools/issues/5142 , caused by files.exclude usage.

**Comment by sean-mcmanus** [comment]
Are you referring to the original bug? The original bug was never fixed so it's not a 0.27.0-insiders3 regression. Are you seeing a regression?

I saw a temporary Outline issue, but as soon as the file got tag parsed the Outline correctly populated.

**Comment by bobbrow** [comment]
You have to open a file that is outside the `${workspaceFolder}`

**Comment by sean-mcmanus** [comment]
@bobbrow None of us were able to repro that on our computers. Michelle reproed it with 0.26.3, but said the latest fixed it.

**Comment by sean-mcmanus** [comment]
@bobbrow It sounds like the issue you were hitting is the same as https://github.com/microsoft/vscode-cpptools/issues/5190 -- let me know if you still have a repro with 0.27.0-insiders5.

The original issue I reported may no longer repro as well (not sure).

**Comment by bobbrow** [comment]
It turns out that I had a `files.exclude` setting that was causing the file outside the workspace not to be tag parsed.  The strange thing is that I was getting bogus symbols for that file instead of no symbols.
