### ISSUE TITLE
No way to regenerate broken launch.json

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#396]
Hi guys,
I ran into an issue where I updated my version of cpptools and some aspects of my launch.json file were now deprecated in the latest version (it complained about the syntax when I tried to run), so debug no longer worked. 
The problem is, there's no way for me to ask it to generate a new launch.json that is compliant with the latest version - uninstalling and reinstalling the extension didn't seem to do the trick. I can't find an example of a functional launch.json to modify for use. Maybe if you can tell me where this file is stored, I can delete it and try to get the extension to recreate it? It would be nice if there was a way to reset this file to a correct default.
Thanks.

**Comment by sean-mcmanus** [comment]
The launch.json should be in your .vscode folder of the workspace root. You can generate a new one with the Configure or Fix launch.json button in the Debug pane (if you have one already it opens the launch.json instead).

**Comment by pieandcakes** [comment]
@saltbot If you delete the `launch.json` that is in your workspace inside the `.vscode` folder and go through the `Debug` window's `Configure` gear button, it will create a brand new one and you will need to reenter the settings you had in there before.

**Comment by pieandcakes** [comment]
@saltbot Please reopen/comment on this issue if my above steps don't work for you.

**Comment by bwilv** [comment]
I am having problems setting up my launch.json file. I don't know how to resolve the Pylint syntax error, I have tried to delete and relaunced a new launch.json...but I can not seem to remedy this error. Thank you. 
![Capture](https://user-images.githubusercontent.com/34752775/57872635-19be7980-77da-11e9-903b-9a84254ca196.JPG)

**Comment by pieandcakes** [comment]
@bwilv This is the `C/C++` extension's github. I think the Python one is somewhere different. 

To regenerate your `launch.json` you need to delete the file from the `.vscode` folder in your workspace root and go through creating debug configurations again.
