### ISSUE TITLE
Incorrect syntax highlighting for u8 strings

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#3961]
Copied from https://github.com/microsoft/vscode-cmake-tools/issues/555

The following code does not highlight properly.  Seems to be caused by the `u8` strings.
```
#include <map>

namespace Engine
{
	class UTF32 //char character, unicode value
	{
	private:
		std::map<uint8_t, unsigned long> CharCodeMap =
		{
			{u8' ', 0x20},
			{u8'!', 0x21},
			{u8'#', 0x23},
		};
	};
}
```

![image](https://user-images.githubusercontent.com/12818240/61667195-35d51000-ac8e-11e9-99b8-f026811b2d43.png)

**Comment by sean-mcmanus** [comment]
This is already fixed with VS Code Insiders or the Better C++ Syntax extension.
