### ISSUE TITLE
VS Code does not consistently normalize paths

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode-cpptools#3964]
Issue Type: <b>Bug</b>

Sorry, my English is bad.

I am an informatics contestant, so I mainly use a single file instead of a project during practice. There are many separate CPP files in my workspace, they may have some symbols. When I open any file with Cmd+click on any symbol, C/C++ outputs a warning similar to #3786.

I think C/C++ should add an option to control the search for symbols from a single file or the entire workspace.

Also, are there any temporary solutions?

Extension version: 0.24.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
We need more specific details and repro steps, because we aren't able to repro any issue that you are describing and we haven't gotten other reports like this so far.

Are you doing Open Folder or Open File? (i.e. does it say "No Folder Opened" in the Explorer?

What other settings have you changed? What does it say when you use the C/C++: Log Diagnostics command?

Are you able to provide a simple sample project that repros the issue?

What is the problem with "search for symbols"?

**Comment by RBNico** [comment]
Same issue here ..

I am working in a folder containing a lot subfolders and much more source code files. Once I use CMD + Click I get faced by:

> This file (...) is already opened in the editor but with a different casing. IntelliSense features will be disabled on this copy of the file.

Best regards
Nico

**Comment by mxdh** [comment]
I think I found the cause of the problem.

This is an example:
[sample.zip](https://github.com/microsoft/vscode-cpptools/files/3425100/sample.zip)

1. Unzip the package on windows and open `code.code-workspace` with vscode.

2. Open any CPP file (such as `A+B Problem\sample.cpp`) in the vscode explorer.

3. CMD+ click main function

C/C++ will output a warning similar to #3786.

I found that after changing `"path": "Code"` in `code.code-workspace` to `"path": "code"` (consistent with the case of the `code` folder), the problem disappeared.

Windows file system is not case sensitive.

So, is this an expected behavior or a bug?

Thank you.

**Comment by RBNico** [comment]
Hi @mxdh can you explain where to find this setting? I searched for it in "Settings" but couldn't find it.

**Comment by mxdh** [comment]
@RBNico In your `.code-workspace` file. You can open it with another editor.

**Comment by RBNico** [comment]
Mh cannot find such file ¯\＿(ツ)＿/¯

**Comment by mxdh** [comment]
@RBNico This method does not apply if you are not using a workspace.

**Comment by RBNico** [comment]
I only have such entry in my `workspace.json` where I have the following:

```
{
	"folders": [
		{
			"path": "..."
		}
	],
```

But changing my path (`...`) to lowercase doesn't change anything. Error still appears.

**Comment by mxdh** [comment]
@RBNico 
Sorry, my English is bad.
Open the `settings`, select the `workspace`, and click the braces button in the upper right corner to open the workspace configuration file. Change the `path` to the same name as the folder you want to open (same case).

**Comment by RBNico** [comment]
Unfortunately this is not working for me.

**Comment by sean-mcmanus** [comment]
@mxdh Yeah, you identified the cause. I'm not sure if it's something we can fix or not, so using your workaround of renaming it to the correct case is the recommended action currently. VS Code is tracking the root of path normalization at https://github.com/microsoft/vscode/issues/12448 , i.e. VS Code shouldn't be opening the same file with 2 different casings.

@RBNico Your repro might be different. Are you able to provide more repro details? Do you have the Windows case sensitive file system enabled?

**Comment by RBNico** [comment]
@sean-mcmanus My workspace is currently a network (samba) folder shared by Ubuntu running in a virtual box. At least I didn't enabled any case sensitive file system.

**Comment by sean-mcmanus** [comment]
@RBNico I've moved your issue to a new bug https://github.com/microsoft/vscode-cpptools/issues/3980 .

**Comment by Zylann** [comment]
Just got the same as #3786 after opening files from Ctrl+Clicking on compile errors in the output terminal:
```
This file (c:\projects\godot\engine\godot_fork\modules\voxel\terrain\voxel_lod_terrain.cpp) is already opened in the editor but with a different casing. IntelliSense features will be disabled on this copy of the file.
```

The file was already opened, but opened a second time instead:
![image](https://user-images.githubusercontent.com/1311555/63969953-e824a200-ca9a-11e9-99ae-b8727f178bcc.png)

And here is what I clicked. The build system I use (SCons+MSVC) made the whole path come out as lower case in the terminal (notice the `c:/` drive letter instead of `C:/`), which maybe is why VSCode is confused:
![image](https://user-images.githubusercontent.com/1311555/63970003-0094bc80-ca9b-11e9-95b9-90193fff6d0e.png)

Not sure how to solve that. I thought VSCode could reconcile the path on Windows since case doesn't matter here?

**Comment by sean-mcmanus** [comment]
@Zylann Yeah, it's a problem with VS Code and the lack of any sort of file normalization, particuarly from links generated from external tools: see https://github.com/microsoft/vscode/issues/12448 . The warning message we output is "by design".
