### ISSUE TITLE
0.24.1 can't start

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode-cpptools#3965]
**Type: LanguageService**

**Describe the bug**
- OS and Version: linux debian 8.10
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
I updated to 0.24.1 and started getting this error:
> Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at /homes/baruchb/.vscode/extensions/ms-vscode.cpptools-0.24.1/bin/Microsoft.VSCode.CPP.Extension.linux

And of course (as the error says) I now have no intellisense.

**To Reproduce**

**Comment by BMBurstein** [comment]
Going back to 0.24.0 fixes this, but I can't get it to stay at that version (vscode keeps auto-updating it back to 0.24.1)

**Comment by sean-mcmanus** [comment]
Are you using 32-bit Linux?

You can stay on 0.24.0 by changing extensions.autoUpdate to "false" and C_Cpp.updateChannel to "Default".

**Comment by BMBurstein** [comment]
@sean-mcmanus No, it is 64-bit. Thanks for the tip on preventing updates

**Comment by sean-mcmanus** [comment]
We have tested the install on 64-bit Linux and we haven't gotten any other reports of missing binaries, so maybe you could try an uninstall, restart VS Code, and then reinstall? Or you could try deleting the install.lock file to re-install the binaries or manually install the vsix at https://github.com/microsoft/vscode-cpptools/releases/tag/0.24.1 .

**Comment by BMBurstein** [comment]
I have tried the uninstall-restart-install already. I will try the install.lock thing. Where is this file?

**Comment by sean-mcmanus** [comment]
~/.vscode/extensions/ms-vscode.cpptools-0.24.1/install.lock

If there's some failure, it might be shown in the C/C++ output window or the "Toggle Developer Console"

**Comment by BMBurstein** [comment]
Deleting the .lock file solved it. Thank you
