### ISSUE TITLE
How to exclude a path from the include search path?

### ISSUE THREAD

**Issue by smwikipedia** [microsoft/vscode-cpptools#3966]
**Type: LanguageService**

**Describe the bug**
- OS and Version:  Ubuntu 18.04
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I configure includePath has below: 

![image](https://user-images.githubusercontent.com/999318/61710709-cb52cb80-ad84-11e9-9b06-853388e2f07c.png)

But when I try to open a header file with F12, it gives me two candidates:

![image](https://user-images.githubusercontent.com/999318/61710585-85960300-ad84-11e9-9470-3fd1057c4207.png)

The second one `subsys/testsuite/ztest/include/syscalls` folder is not in my includePath.  Why is it still scanned? How can I exclude it?

**Comment by sean-mcmanus** [comment]
You can use C/C++: Reset IntelliSense Database to try to fix any stale files. You can also use the C/C++: Log Diagnostics to see what other system include paths might be coming from the compiler. You can also try adding the paths you don't want to the files.exclude setting. Does that solve your issue?

**Comment by smwikipedia** [comment]
Unfortunately, it doesn't solve the issue.

My `c_cpp_properties.json` file contains below content:

```
  "includePath": [
      "/home/xxx/zephyr/zephyrproject/zephyr/kernel/include",
      "/home/xxx/zephyr/zephyrproject/zephyr/arch/posix/include",
      "/home/xxx/zephyr/zephyrproject/zephyr/include",
      "/home/xxx/zephyr/zephyrproject/zephyr/include/drivers",
      "/home/xxx/zephyr/zephyrproject/zephyr.build/hello_world_native/zephyr/include/generated",
      "/home/xxx/zephyr/zephyrproject/zephyr/soc/posix/inf_clock",
      "/home/xxx/zephyr/zephyrproject/zephyr/boards/posix/native_posix"
  ],

```
I tried the C/C++: Log Diagnostics, below are the outputs:

```
    Includes:
        /home/xxx/zephyr/zephyrproject/zephyr/kernel/include
        /home/xxx/zephyr/zephyrproject/zephyr/arch/posix/include
        /home/xxx/zephyr/zephyrproject/zephyr/include **<======= Here this path is output once.**
        /home/xxx/zephyr/zephyrproject/zephyr/include/drivers
        /home/xxx/zephyr/zephyrproject/zephyr.build/hello_world_native/zephyr/include/generated
        /home/xxx/zephyr/zephyrproject/zephyr/soc/posix/inf_clock
        /home/xxx/zephyr/zephyrproject/zephyr/boards/posix/native_posix
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /home/xxx/zephyr/zephyrproject/zephyr/include **<======= Here this path is ouput again??**
```
My code contains below line:

`#include <syscall.h>`

When I press `F12` over the `<syscall.h>`, VS Code gives me 5 candidates:
![image](https://user-images.githubusercontent.com/999318/61781493-031a4b80-ae37-11e9-9542-3d52b8a1e985.png)


We can see all these candidates are coming from the `/home/xxx/zephyr/zephyrproject/zephyr/include` and its sub dirs.

How can I prevent this **recursion search** to make the include path more specific?

And if i use the `files.exclude` setting, that folder will not show in my workspace. That's not what I want. I just want to narrow down the include search paths.

**Comment by smwikipedia** [comment]
@sean-mcmanus Could you help me out?

**Comment by sean-mcmanus** [comment]
Go to Def on `#include` lines is buggy and doesn't use the includePath to locate the "correct" file. It instead uses the tag parser which by default behaves recursively using the includePath, see https://github.com/microsoft/vscode-cpptools/issues/2564 .

You can work around this by copying over your includePath settings into browse.path and then adding "/*" to the end of the path to make the path become non-recursive. You may need to do a Reset IntelliSense Database afterwards if it doesn't clean up the old files automatically.

**Comment by michelleangela** [comment]
Closing as duplicate.
