### ISSUE TITLE
Format.exe will fail to start child process when cpp file in Multi-level folders.

### ISSUE THREAD

**Issue by Fomalhauthmj** [microsoft/vscode-cpptools#3967]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 (10.0.18362.239)

- VS Code Version:
version: 1.36.1 (system setup)
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

- C/C++ Extension Version:
id: ms-vscode.cpptools
version: 0.24.1

- A clear and concise description of what the bug is.
When my cpp file in Multi-level folders, clang-format.exe will fail to start child process.
About Details you can compare below two screenshots.

**To Reproduce**
1. create a file in current folder and another fail in sub folder then try to use format function

**Screenshots**

![TIM图片20190723235120](https://user-images.githubusercontent.com/40078998/61726776-cd2c8700-ada4-11e9-9b6a-4d93b7dddaf9.png)
![TIM图片20190723235232](https://user-images.githubusercontent.com/40078998/61726906-fd742580-ada4-11e9-9237-abc7cc8a1d68.png)

**Comment by sean-mcmanus** [comment]
This is strange. I'm not able to repro it. @Colengms @michelleangela @Jasdriel Is anyone else able to repro this?

**Comment by Jasdriel** [comment]
I can't repro either, I actually even tried with more subfolders but is working ok

**Comment by michelleangela** [comment]
It might be the same as this issue https://github.com/microsoft/vscode-cpptools/issues/3007#issuecomment-485062945

**Comment by Fomalhauthmj** [comment]
Update: I solve this problem by the method in #3007 comment.
> This probblem has been bothering me for a long time. I have found that the cpp file can not be formatted if the name of one of its parent folders ends with "Chinese character+digit", like "中文123". If not, the cpp file can be formatted. The name of the cpp file has no influence.
> Not long ago I found a solution: I insert an underline "_" between the Chinese character and the digit of the name of the folders to separate them, writing "中文_123", and the cpp file can be formatted. Using "-" or space doesn't work. Using English letters works, but there must be no spaces after Chinese characters.
