### ISSUE TITLE
[macOs] c/c++ debug console output problems

### ISSUE THREAD

**Issue by bu2zhouzhu** [microsoft/vscode-cpptools#3968]
- OS and Version: mac OS 10.14.5
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1

I have several problems:
1. Why `cout` and `printf` have `@` symbol in the `DEBUG CONSOLE` ?
2. Why `DEBUG CONSOLE` print `\r\n` ?
3. Why after press `F5`, `TERMINAL` window opend by default, I have to click `DEBUG CONSOLE` **every time** to see program output? It's **too** inconvenient.

Following is my test code and `DEBUG CONSOLE` output:

Test2.c
```c
#include <stdio.h>

int main() {
    printf("Hello c\n");
    printf("Hello c 2\n");
    return 0;
}
```

```
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=thread-selected,id="1"
@"Hello\r\n"
@"Hello2\r\n"
The program '/somepath/.vscode/Test2' has exited with code 0 (0x00000000).
```

Test.cpp
```
#include <iostream>

int main() {
    std::cout << "Hello cpp";
    return 0;
}
```

```
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=thread-selected,id="1"
@"Hello cpp"
The program '/somepath/.vscode/Test' has exited with code 0 (0x00000000).
```

**Comment by pieandcakes** [comment]
>Why cout and printf have @ symbol in the DEBUG CONSOLE ? 

Because you are not using `externalConsole`, `lldb` shows program output within its output stream and it appends an `@` symbol in front.

>Why DEBUG CONSOLE print \r\n ?

Because that is what `lldb` does. We don't control that, we are passing on what the debugger is showing.

>Why after press F5, TERMINAL window opend by default, I have to click DEBUG CONSOLE every time to see program output? It's too inconvenient.

Are you talking about `Terminal` that is within VS Code? If so, that is a [VS Code](https://github.com/microsoft/vscode/issues)  issue that might stem from how it launches the debugger.

**Comment by JohnHoustonQG** [comment]
Any further insight on this? Something is seemingly turning each line for the console into an escaped NSString. I'm using Linux VSCode ssh-remote into a Mac and I to am seeing everything sent to stdout or stderr appear this way in the debug console.
