### ISSUE TITLE
Recursive include path doesn't work with #include_next.

### ISSUE THREAD

**Issue by CFornari** [microsoft/vscode-cpptools#3969]
In the `c_cpp_properties.json` I have this includePath:
```
"includePath": [
                "${ESP_HOME}/xtensa-lx106-elf/xtensa-lx106-elf/include/**",
                "${SMING_HOME}/**",
                "${workspaceRoot}/**"
            ],
```
I have the following error: `cannot open source file "driver/uart.h" (dependency of "global_core.h")`

This header should be added by the `"${SMING_HOME}/**"`. To confirm this I run:
```
cd $SMING_HOME
find . -name "uart.h"
```
Output
```
./Arch/Host/Components/driver/include/driver/uart.h
./Arch/Esp8266/Components/driver/include/driver/uart.h
```
I made it work once whit a lot of include paths, but unfortunately I made the mistake of deleting the .json file without saving the paths. Previously the intellisense reported no errors and when pressing F12 offer the alternative to which header I wanted to go.

- OS and Version: Ubuntu 18.04.2 -- Linux x64 5.1.0-050100-generic
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
The issue persist after disable all other extensions

**Comment by Colengms** [comment]
Hi @Oshio09 .  Are you also using a configurationProvider?  If so, the include paths it provides will be used instead.

**Comment by bobbrow** [comment]
Also, try running the `C/C++: Log Diagnostics` command which will tell you which include paths were used when creating the IntelliSense engine.

**Comment by CFornari** [comment]
@Colengms That's not the case. Here is the current code:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${ESP_HOME}/xtensa-lx106-elf/xtensa-lx106-elf/include/**",
                "${SMING_HOME}/**",
                "${workspaceRoot}/**"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "databaseFilename": "${workspaceRoot}/.vscode/browse.vc.db"
            },
            "intelliSenseMode": "clang-x64",
            "compilerPath": "${ESP_HOME}/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by CFornari** [comment]
@bobbrow thanks for pointing out this command.
The output does not include the path to that folder, actually, just a few sub-directories are included. Could this be a bug?

**Comment by bobbrow** [comment]
Maybe?  A potential cause could be that VS Code hasn't inherited the environment variables and doesn't know about `SMING_HOME`.  If you [enable logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) and run the `Developer: Reload Window` command, do you see any log messages that indicate an invalid path being used?

For example:
```
Unable to retrieve file system information for ${SMING_HOME}/**. error = -1
```

**Comment by CFornari** [comment]
@bobbrow I don't think that would be the case because it can find some paths. Here are the includes reported by the command  `C/C++: Log Diagnostics`:

```
Includes:
        /home/user/sdks/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/include/c++/4.8.5
        /home/user/sdks/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/include/c++/4.8.5/xtensa-lx106-elf
        /home/user/sdks/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/include/c++/4.8.5/backward
        /home/user/sdks/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/include
        /home/user/sdks/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/include-fixed
        /home/user/sdks/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/include
        /home/user/sdks/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include
        /home/user/Codes/esp8266/include
        /home/user/sdks/Sming/Sming/Core
        /home/user/sdks/Sming/Sming/System/include
        /home/user/sdks/Sming/Sming/Wiring
        /home/user/sdks/Sming/Sming
        /home/user/sdks/Sming/Sming/Arch/Esp8266/Core
        /home/user/sdks/Sming/Sming/Arch/Host/Components
        /home/user/sdks/Sming/Sming/Arch/Host/System/include
        /home/user/sdks/Sming/Sming/Components/spiffs
        /home/user/sdks/Sming/Sming/Arch/Host/Components/driver/include
        /home/user/sdks/Sming/Sming/Arch/Host/Components/esp_hal/include
        /home/user/sdks/Sming/Sming/Arch/Host/Components/esp_wifi/include
        /home/user/sdks/Sming/Sming/Components
        /home/user/sdks/Sming/Sming/Arch/Esp8266/Components/rboot/rboot/appcode
        /home/user/sdks/Sming/Sming/Components/spiffs/spiffs/src
        /home/user/sdks/Sming/Sming/Arch/Esp8266/Components/esp8266/include
        /home/user/sdks/Sming/Sming/Arch/Host/Components/heap/include
        /home/user/sdks/Sming/Sming/Arch/Esp8266/Components/rboot/rboot
        /home/user/sdks/Sming/Sming/Arch/Esp8266/Components/rboot/appcode

```
EDIT:
Forgot to mention: 
`${SMING_HOME} = /home/user/sdks/Sming/Sming`

**Comment by bobbrow** [comment]
It sounds like this is the path you want:
```
/home/user/sdks/Sming/Sming/Arch/Host/Components/driver/include
```
And I see it in the Includes: list.  You're saying that you still have a squiggle complaining about `driver/uart.h` even with that path in the includes list?

**Comment by CFornari** [comment]
The path is very similar but is actually:
`/home/user/sdks/Sming/Sming/Arch/Host/Components/driver/include/driver/uart.h`
Note that after `inlcude` there is an additional `driver/uart.h`, and this last folder is the one not been catch.

**Comment by bobbrow** [comment]
To clarify, I was referring to the include path, not the full path to the include.  When you concatenate the string from the error (`driver/uart.h`) to the include path being tested it should create the full path to the included file, which is what you posted.

This is definitely odd.  Is there any way you can share your project with us (or a simple subset)?  We can go and clone the https://github.com/SmingHub/Sming project ourselves so you wouldn't need to include that, but it would be nice to have a copy of `global_core.h` or something similar that reproduces the error so we can see what is going on.

**Comment by CFornari** [comment]
@bobbrow you are right sorry for that.
The `global_core.h` is mainly for macro definitions the only inlcude inside is `#include <SmingCore.h>`
I will adjust the code and upload for you to give a look, just give a few minutes.

**Comment by CFornari** [comment]
@bobbrow Here is the link to my code: https://github.com/Oshio09/myproject
I copied the base skeleton of the project from a guy who gives some instructions on how to integrate Sming and VS Code , so I copied his README.md file to give you some kind of context.

**Comment by bobbrow** [comment]
The problem is caused by an `#include_next` in uart.h.  This is a deficiency with the recursive includes feature.

In the meantime you can work around this issue by including paths to both `driver/include` folders in your `includePath` (note: the order of the non-recursive paths matters)

```
            "includePath": [
                "${ESP_HOME}/xtensa-lx106-elf/xtensa-lx106-elf/include/**",
                "${SMING_HOME}/**",
                "${SMING_HOME}/Arch/Host/Components/driver/include",
                "${SMING_HOME}/Arch/Esp8266/Components/driver/include",
                "${workspaceRoot}/**"
            ],
```

**Comment by CFornari** [comment]
Thanks this works!

**Comment by Colengms** [comment]
The behavior is by design, but we added some additional logging to provide guidance when this happens.  We think this scenario has been addressed.  If you're still seeing an issue, please let us know.
