### ISSUE TITLE
How to quickly import android source code like IntelliJ IDEA.

### ISSUE THREAD

**Issue by zhaohaixin** [microsoft/vscode-cpptools#397]
How to import AOSP source code, and can achieve function tracking. Whether through the source code idegen.jar import, or can be compiled through the completion of the AOSP link file to function tracking query.

**Comment by pieandcakes** [comment]
@zhaohaixin This extension does not work with `Java` files, which AOSP contains. Therefore, we would not be able to import a large portion of the AOSP source code base.
