### ISSUE TITLE
Use gdb to attach to a running process and debug it

### ISSUE THREAD

**Issue by ranqiyu** [microsoft/vscode-cpptools#3975]
This situation is very common, for example, when fork a child process, but it is separate. Use gdb to attach and vscode to debug. Is this feature now supported?I don't seem to see it.

**Comment by pieandcakes** [comment]
@ranqiyu You can attach using the `type: "attach"` in your `launch.json`.

 If you want to follow a child process fork for launch, you need to send `gdb` the command: `gdb set follow-fork-mode child`. This can be configured as one of the `setupCommands` in your `launch.json` file.

**Comment by ranqiyu** [comment]
> @ranqiyu You can attach using the `type: "attach"` in your `launch.json`.
> 
> If you want to follow a child process fork for launch, you need to send `gdb` the command: `gdb set follow-fork-mode child`. This can be configured as one of the `setupCommands` in your `launch.json` file.

Great. This solved my problem, but with the `"request": "attach"` instead of `type: "attach"`.
But when using `gdb set follow-fork-mode child` in `launch.json` file, you mean like this, 
```
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true,
                    "set follow-fork-mode":"child"
                }
            ],
```
But it doesn't work for me.what's wrong？

**Comment by pieandcakes** [comment]
@ranqiyu Sorry, you are correct and it should be `"request"` and not `"type"`.

```           
"setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true,
                    "set follow-fork-mode":"child"
                }
            ],
```

Notice that the `"text"` field is the actual command we send to `gdb` and that it is an array of objects.

You would want something like:
```
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "text": "gdb set follow-fork-mode child",
                    "ignoreFailures": false
                }
            ],
```
