### ISSUE TITLE
Incorrect error squiggle on creating _Atomic type of struct/union

### ISSUE THREAD

**Issue by harikrishnan94** [microsoft/vscode-cpptools#3976]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS 10.14.5 (Xcode 10.3)
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
- Other extensions you installed : Reproduces with all other extensions disabled
- Error squiggle on defining _Atomic struct variable, which compiles fine on gcc/clang

**To Reproduce**
``` C
#include <stdatomic.h>

struct IntStruct {
  long a;
};

typedef _Atomic(struct IntStruct) AtomicIntStruct;
```
c_cpp_properties.json: 
``` json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "${vcpkgRoot}/x64-osx/include"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
- Error squiggle under `AtomicIntStruct`

**Expected behavior**
No error squiggles

**Screenshots**
<img width="1440" alt="Screenshot 2019-07-25 at 2 53 03 PM" src="https://user-images.githubusercontent.com/6957719/61862742-ff94cc00-aeeb-11e9-81dd-ec671dd0a7e4.png">

**Additional context**: C++ std::atomic doesn't give error squiggles

**Comment by sean-mcmanus** [comment]
Our IntelliSense compiler doesn't currently support _Atomic with clang, only gcc (I assume your gcc on mac is actually a symlink to clang). I've filed a bug on VS at https://developercommunity.visualstudio.com/content/problem/662081/c-intellisense-shows-atomic-class-types-are-disabl.html that you could upvote if you have a Microsoft account.

**Comment by harikrishnan94** [comment]
Thanks @sean-mcmanus , Error squiggles are gone after changing `compilerPath` to 'real gcc'.
