### ISSUE TITLE
Don't automatically change carriage return.

### ISSUE THREAD

**Issue by leowinchester** [microsoft/vscode-cpptools#3977]
**Type: LanguageService**

Sometimes we don't want vs code automatically change the carriage return, otherwise when submit code, we get more than what we wanted, visual studio community have a choice you can make when file with different type of carriage return inside(unix, windows), but seems vs code make the choice for you. 

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
This is the repro for the C/C++ extension. The functionality you are describing is implemented by VS Code -- please file your issue at https://github.com/microsoft/vscode/issues unless this issue only repros with the C/C++ extension enabled.
