### ISSUE TITLE
Use XDG_CACHE_HOME on Linux systems for the default cache path

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode-cpptools#3979]
Type: General
There is no sense in polluting the home directory with yet another folder. The Freedesktop spec has included support for a default cache dir denoted by $XDG_CACHE_HOME typically residing in ~/.cache.

**Expected behavior**
Not pollute the home directory.

**Additional context**
This is in regard to the latest release announcement.

https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

**Comment by bobbrow** [comment]
Until we make this change, please note that you can override our defaults by setting the `C_Cpp.intelliSenseCachePath` **User** setting to "${XDG_CACHE_HOME}/vscode-cpptools" (or similar)

![image](https://user-images.githubusercontent.com/12818240/61903508-868c7900-aed9-11e9-96b0-3b9871cce5a6.png)

**Comment by CameronNemo** [comment]
https://github.com/microsoft/vscode/issues/3884#issuecomment-460359959

**Comment by tristan957** [comment]
@CameronNemo thank you. I have made sure to upvote the issue and I hope everyone who cares about this issue also upvotes that one. It is quite amazing we have to fight to have the VSCode team (proper) follow a *standard* that has been in place for far longer than the editor. The issue is currently on the second page, which means slowly but surely we might get it implemented at some point.

**Comment by michelleangela** [comment]
Default cache path updated for Mac and Linux in version 0.26.2-insiders, available at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders.

**Comment by soloturn** [comment]
@michelleangela is the default respected or it would need a variable set? because - there is none set usually.

- https://wiki.archlinux.org/index.php/XDG_Base_Directory
- https://wiki.archlinux.org/index.php/XDG_user_directories

**Comment by michelleangela** [comment]
@soloturn, on Linux the C/C++ extension queries XDG_CACHE_HOME and uses whatever value XDG_CACHE_HOME returns, so it should respect the default value unless it has been changed by the user. Also, if querying XDG_CACHE_HOME  is not successful on the Linux machine then the extension will fallback to the path `~/.cache`.
