### ISSUE TITLE
Change Log: December update does not work.

### ISSUE THREAD

**Issue by Aukstkalnis** [microsoft/vscode-cpptools#398]
I want to see what was done, but the link just redirects me to https://www.microsoft.com/lt-lt/
Can you fix it?

**Comment by sean-mcmanus** [comment]
The ReadMe.md for version 0.9.3 describes most of the changes. The language service executable wasn't updated at all yet. We're working on bug fixes. I don't have an ETA yet on when the blog will be posted.

**Comment by pieandcakes** [comment]
@Aukstkalnis We are working on getting it posted. As mentioned in #394, the blog will explain how to use the `sourceFileMap` feature and explain that `pretty-printing` is enabled in new `launch.json` files for GDB users.
