### ISSUE TITLE
"Already opened" message with network (samba) folder shared by Ubuntu

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3980]
@sean-mcmanus My workspace is currently a network (samba) folder shared by Ubuntu running in a virtual box. At least I didn't enabled any case sensitive file system.

_Originally posted by @RBNico in https://github.com/microsoft/vscode-cpptools/issues/3964#issuecomment-514889189_

**Comment by sean-mcmanus** [comment]
From @RBNico

Same issue here ..
I am working in a folder containing a lot subfolders and much more source code files. Once I use CMD + Click I get faced by:
This file (...) is already opened in the editor but with a different casing. IntelliSense features will be disabled on this copy of the file.
Best regards
Nico

**Comment by Colengms** [comment]
I've encountered this as well when accessing a Mac-hosted SMB share from a PC.

**Comment by ebuescher** [comment]
I am also experiencing this issue when running vs code on windows with a mapped network drive from a linux box.

**Comment by HEMINSAN** [comment]
Yeh, me too.

**Comment by Colengms** [comment]
Same issue as https://github.com/microsoft/vscode-cpptools/issues/2528

**Comment by michelleangela** [comment]
Fixed in version 0.26.2-insiders, available at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders.
