### ISSUE TITLE
Go to def bug

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3981]
two functions are defined in the same file and are called in another file, go to definition works for one function, while does not work as expected for the other function. Maybe sometimes, it can work.

```
{
    "configurations": [
        {
            "name": "IAR",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/../Config/exec/arm/inc/c",
                "${workspaceFolder}/../Config/exec/arm/inc/cpp"
            ],
            "defines": [
                "CPU_S32K146",
                "__ICCARM__",
                "__IAR_SYSTEMS_ICC__"
            ],
            "compilerPath": "",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

![cpptools_go_to_definition](https://user-images.githubusercontent.com/15389150/61869088-65de1680-af0d-11e9-8860-41b441721212.gif)

_Originally posted by @mkitby in https://github.com/microsoft/vscode-cpptools/issues/2450#issuecomment-514998283_

**Comment by sean-mcmanus** [comment]
When you open the file with the definition that Go to Def fails to locate, do you see the function in the Outline pane or C/C++: Navigate... list?

It looks like the symbol might not be getting parsed, possibly due to a macro interfering with it.

**Comment by mkitby** [comment]
I can see both functuions in the C/C++: Navigate list and symbol in file list
![cpptools_n](https://user-images.githubusercontent.com/15389150/61917542-3a484400-af80-11e9-813d-c3c134e37c5f.gif)

**Comment by sean-mcmanus** [comment]
It seems like the IntelliSense-based Go to Def type checking may be failing for the definition, but it succeeds for the 2 other results. Do the signatures in the declaration and definition match? If you change the input signatures to be void, does the Go to Def succeed? Unfortunately we haven't added better logging for failures in this code yet so it's hard to tell why it's failing without debugging it.

All the squiggles in your file might also be causing some failure.

**Comment by mkitby** [comment]
The declaration and definition match. The go to def works if I change the function argument to be void. OK, I found another extension C++ Intellisense, this works for me.

**Comment by theunwisewolf** [comment]
Any update on this issue?

**Comment by sean-mcmanus** [comment]
@askamn We were never given enough repro info. It sounded like our code was not processing the function arguments correctly...the screenshots showed lots of error squiggles (seemingly due to missing includes), so that could be the cause. Let us know if you have more repro details on a case were Go to Def fails.

**Comment by theunwisewolf** [comment]
@sean-mcmanus It stops working randomly. What happened was I was working on my project (which uses this extension + the vector-of-bool.cmake one), everything was working fine. Suddenly I noticed that I could no longer Cmd + Click to go to definitions or open header files. Doing a right-click on any function or a header file and then on "Go to definition" gave me the error "No definition found" (Forgot exact wording :P). But I could see the Function declaration and parameter list if I simply hover over the function call.

After a while, I shutdown my mac and when I opened it back, everything in VS Code was working fine once again. 

This happens every now and then. I tried using both include Paths in the C++ extensions and specifying compile_commands.json but I noticed that it happens with both of them. 

Also Rescan Intellisense and Clearing the intellisense cache doesn't help.

And sorry, I do not know the exact steps to repro this bug.

**Comment by ghost** [comment]
Any update on this issue? I have encountered the same problem.

**Comment by sean-mcmanus** [comment]
@abitofmaya The issue where Go to Def returns multiple results is a symptom that can have many different causes/fixes. We need more specific repro details to be able to diagnose/fix the particular issue you are hitting.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
