### ISSUE TITLE
go to definition incorrect

### ISSUE THREAD

**Issue by alianZhen** [microsoft/vscode-cpptools#3983]
when my project has multiple encoded files,such as utf-8,gb2312 and so on.
Go to definition always incorrect when I first do it.
But when I edit the target file,go to definition seems working fine.

c/c++ version: 0.24.1

**Comment by sean-mcmanus** [comment]
We haven't added support for non-UTF8 files yet.

This issue is a duplicate of a really old issue.

**Comment by suifeng115** [comment]
> We haven't added support for non-UTF8 files yet.

Hi, our team have the sample problem.
Can other coding formats be supported?

**Comment by Lennon925** [comment]
I think this is related with bugs I raised previously. If this issue can be fixed, I think it's a big step forward.

**Comment by bobbrow** [comment]
Duplicate issue is #414

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 . Let us know if you see any remaining bugs with non-UTF-8 encodings.
