### ISSUE TITLE
VS Build tools isn't appearing in the compilerPath dropdown

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#3989]
I already try all solutions but C++ Extension cannot detect installed VS Build tools
![image](https://user-images.githubusercontent.com/9786086/61932560-ea807180-afad-11e9-9c42-76b35cc2299c.png)
But CMake Tools does it.
![image](https://user-images.githubusercontent.com/9786086/61932642-14d22f00-afae-11e9-896e-30f1d31051f5.png)

Any ideas?

_Originally posted by @Gargony in https://github.com/microsoft/vscode-cpptools/issues/1839#issuecomment-515335513_

**Comment by bobbrow** [comment]
This should be fixed in the latest version of the extension. Your other option is to set CMake Tools as the configuration provider (use the `C/C++: Change Configuration Provider...` command) and then you don't need to set a compiler path at all.

**Comment by Gargony** [comment]
@bobbrow yes, now is ok, thx.
