### ISSUE TITLE
Cannot compile: Arduino not including my own libraries  - paths?

### ISSUE THREAD

**Issue by ImolaS3** [microsoft/vscode-cpptools#3991]
Hopefully someone can help - I have spent 2 weeks trying to fix this and exhausted pages of google results :(

I use a Mac mostly these days and wanted a nice "proper" IDE for Mac and Arduino (the Arduino "IDE" isn't an IDE and is, in my opinion, like a dreadful trip back to 1990, Z80 dev under DOS 3 :( - something i long to forget :) )

VSCODE seemed to fit the bill.

I have it working fine if I place my custom headers in the actual project folder and use"" to point to them, but when placed in another folder using <>, it always fails.

I have added the path to the  c_cpp_properties.json and played with "Default" and "Tag Parser" intellisense.

The Colours header in this example is located in "/Users/antonysutton/Arduino_H/" and called Colours.h  (I have also tried ""/Users/antonysutton/Arduino_H/**" 

When I try to compile, the error is "TonyTouchScreen:7:66: error: Colours.h: No such file or directory"

Headers in code:
#include <Adafruit_GFX.h>
#include <MCUFRIEND_kbv.h>
#include "TouchScreen_kbv.h"         
#include <Colours.h>    

Using the following syntax compiles fine, so it si not looking in the includepath unless explicitly stated :

#include <Adafruit_GFX.h>
#include <MCUFRIEND_kbv.h>
#include "TouchScreen_kbv.h"         
#include </Users/antonysutton/Arduino_H/Colours.h>  

c_cpp_properties.json

{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Applications/Arduino.app/Contents/Java/tools/**",
                "/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/**",
                "/Users/antonysutton/Arduino_H/**",
                "${workspaceFolder}/**"

            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse":{
                "path":[
                    "/Applications/Arduino.app/Contents/Java/tools/**",
                    "/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/**",
                    "/Users/antonysutton/Arduino_H/**",
                    "${workspaceFolder}/**"
                ]
            },
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
           
            "forcedInclude": [
                "/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h"
            ]
        }
    ],
    "version": 4
}

Settings.json
    "C_Cpp.intelliSenseEngine": "Tag Parser",

**Comment by ImolaS3** [comment]
I am pretty sure the3 compilation is not even looking at c_cpp_properties.json as whatever i do to it, the error remains the same, none added, none taken away even if i delete the .json file it still has exactly the same error

Someone please help :(

**Comment by michelleangela** [comment]
@ImolaS3 , how are you trying to compile, are you using a [task.json](https://code.visualstudio.com/docs/cpp/config-clang-mac#_create-a-build-task) or another method? The information in `c_cpp_properties.json` is only used for configuring IntelliSense and not building.

**Comment by ImolaS3** [comment]
Hi 
I tis an Arduino compilation and I really have no idea if it uses a task.json.

There isn't one in the .vscode drop down in the project, only the arduino.json and a propeeties.json

If the path for include locations for libraries is not in the properties.json file, then do you know where one should place them for the arduino?

Finding this ide very confusing due to its complexity and felxibility

many thanks

**Comment by michelleangela** [comment]
@ImolaS3 ,  I'm guessing that the `arduino.json` created and used is by this Arduino extension https://github.com/Microsoft/vscode-arduino? And the IDE you're referring to is https://www.arduino.cc/en/main/software#download ? 

If you haven't already, I suggest to go to https://github.com/Microsoft/vscode-arduino for information and question on Arduino complication, they may be able to help with your question. The Arduino IDE also has a forum https://forum.arduino.cc/ where you can ask questions or look for related issues.
