### ISSUE TITLE
Directories created on Linux side don't show up in VSC under Windows

### ISSUE THREAD

**Issue by DeanRoddey** [microsoft/vscode-cpptools#3993]
So I have a large C++ development environment repository ( https://github.com/DeanRoddey/CIDLib) which is highly portable and I'm working on the Linux platform driver for it. I presume I created a sub-directory on the Linux side. When I git pull those changes down to the Windows side, the Linux created sub-directory doesn't show up in VSC's explorer.

I've checked the permissions of the directory and contained files and they are identical to the Win32 files. My local Windows account shows up as the owner of both. The directory is there from Window's point of view. If I try to get VSC to create a new sub-directory with that name it complains that the directory is already there. So it's not like it can't see it. But for some reason the explorer won't show it.

If I do a find in folder from the parent (build tool folder) for something that should be found in one of those Linux platform files, they are not found by the search.

Any ideas why that would be?

**Comment by pieandcakes** [comment]
@DeanRoddey Did you mean to open this on the `VS Code` [issues page](https://github.com/microsoft/vscode/issues)? This issues page is for the C++ Extension and I don't know why files would not show up in the explorer.

Another area might be to try the [vscode-remote-release](https://github.com/Microsoft/vscode-remote-release) repository if you are using VS Code Remote or VS Code-WSL extensions.

**Comment by DeanRoddey** [comment]
Oops... too many details, too few brain cells.
