### ISSUE TITLE
A suggestion to make the 'move explorer to currently open file' useful

### ISSUE THREAD

**Issue by DeanRoddey** [microsoft/vscode-cpptools#3994]
The thing where VSC moves the explorer to the currently open file is one of those things that is 50% really useful and 50% so utterly annoying I can't use it. Way , way too many times it screws me, so I've turned it off.

But, what would be useful for those us who can't deal with that behavior, would be to allow something like a double click on the open file's tab, to move the explorer to that file. That would be enormously useful.

**Comment by pieandcakes** [comment]
@DeanRoddey I think you want the [VS Code](https://github.com/microsoft/vscode/issues) repository.
