### ISSUE TITLE
Error compiling code. Can't find the right function

### ISSUE THREAD

**Issue by leewwe** [microsoft/vscode-cpptools#3997]
Type: Debugger
*When I want to "#include" something, it didn't work.
I have added the right include path and files, but the program don't use it when compile the source code.*

platform : Linux

**Additional context**
```
//tasks.json
{
    "tasks": [
        {
            "type": "shell",
            "label": "g++ build active file",
            "command": "/usr/bin/gcc",
            "args": [
                "-g",
                "${file}",
                "${workspaceFolder}/csapp.c",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}",
                "-lpthread"
            ],
            "options": {
                "cwd": "/usr/bin"
            }
        }
    ],
    "version": "2.0.0"
}
```

**Comment by pieandcakes** [comment]
@leewwe are you having a problem compiling or debugging? What is your error message?

**Comment by leewwe** [comment]
when I want to include my own '*.h' file, the VScode will tell me that it can't find the right function, which has been in the previous '*.h' file and corresponding '*.c' file.

**Comment by pieandcakes** [comment]
Can you provide a concrete example so we can debug the scenario? I think it would help to know where your `.h` file is and your `#include` definitions in your `.c` file. 

 This sounds like code editing or compiling though, not debugging.  I changed the title to point it to compiling.

**Comment by leewwe** [comment]
hi, first, thank you.I think I have solved this problem. This problem appears in the C/C++ mixed compiling. I wrongly use it. Again, thanks.
