### ISSUE TITLE
Incorrect header file resolution when there are headers with same name

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#3999]
**Type: LanguageService**

 I have a project like this:
--root/
----project1/
------include/
------src/
----project2/
------include/
------src/

And there are some header files with same name at different location.
Sometimes cpp-tools could not find the correct header file (I mean the nearest one)  and show me error squiggles.

**Describe the bug**
- OS and Version: Win 10 Pro
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
This sounds "by design". I assume you're using recursive includes. If you want a different include path to take precedence over another you can add that path before "${workspaceFolder}/**". You can use C/C++: Log Diagnostics to see what includePaths are being used for IntelliSense. If you use something like CMake Tools or compile_commands.json then you can set per-file include paths.

**Comment by DougHaigh** [comment]
Our build process layers include paths such that a private copy of an include file is searched before a fix branch which is searched before a product branch. For example, I have a file myInclude.h that lives in project1/h, our builds would have the following include files added to the compile command in the following order:

- ${workspace}/project1/h
- /master/<version>-fix/project1/h
- /master/<version>/project1/h

This allows us to have compiles search our workspace before searching the production-released-fixes path before searching the production code path for a header file.

Right now VSCode's IntelliSense appears to pick the first occurance of a path which may leave out all the other header files that would be in the fix branch or the production branch resulting in missing identifier errors.

Is there any way to make this sort of build process work for IntelliSense or are you saying that this cannot work in the VSCode C/C++ extension?

**Comment by sean-mcmanus** [comment]
@DougHaigh The original issue was with recursive includes. compile_commands.json should work. What type of configuration setup are you using?

**Comment by DougHaigh** [comment]
I am not familiar with compile_commands.json and I am not sure my build process does anything with them. Where do I find out about its contents and VSCode's C/C++ extension's use of it?

**Comment by DougHaigh** [comment]
I found the doc [here](https://clang.llvm.org/docs/JSONCompilationDatabase.html) and was able to setup the file for my project. It now appears to get all of the include files but seems to have problems with types that are defined in multiple locations. For example, one include file (stdint.h in the WinSDK include files) typedefs 'int64_t' as '_longlong' and another internal file typedefs 'int64_t' as 'signed long'. Both resolve to the same value on 64bit systems, but IntelliSense tells me that int64_t is undefined.

**Comment by sean-mcmanus** [comment]
@DougHaigh What system paths are shown when you do C/C++: Log Diagnostics? I'm not able to repro int64_t being undefined. It would normally be defined in the stdint.h in the Windows SDK. Does Go to Def on int64_t open any file?

**Comment by bobbrow** [comment]
@DougHaigh, can you open a new issue for your case and provide a small repro project that would help us investigate?  The original issue in this ticket is "by design" and we will be closing this issue.

Thank you!
