### ISSUE TITLE
Parameter Hints Doesn't Work Sometimes

### ISSUE THREAD

**Issue by Jackie-Yang** [microsoft/vscode-cpptools#400]
For example:
<img width="320" alt="2016-12-12 9 28 12" src="https://cloud.githubusercontent.com/assets/18381153/21085457/6117e13c-c04d-11e6-909e-869abbdc02cc.png">
I included "stdio.h"(already set the includePath), and type the function "printf", but Parameter Hints doesn't work.

**Comment by sean-mcmanus** [comment]
We don't implement Parameter Hints yet, but the autocomplete is expected to work. Unfortunately, it seems to be somewhat buggy currently. If you type printf( and then delete the ( you should get the basic signature to appear that lists the input parameters with types.

**Comment by bobbrow** [comment]
This should be fixed in the current version of the extension: 0.10.1.  Please reopen if you are still having issues with the parameter hints.  Thank you!
