### ISSUE TITLE
Problem using clang-cl.exe and CMake Tools

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4000]
@sean-mcmanus Thanks for quick reply.
But my problem is a more deep. )))
Our cmake uses clang 7.0.0 cl.exe (clang-cl.exe) and I set option:
_"configurationProvider": "vector-of-bool.cmake-tools"._
All works correct and build fine. But intellicense works wrong because "cmake--tools" provide options uncompataible with cpptools, "compilerPath": "C:/Program Files (x86)/LLVM/msbuild-bin/cl.exe". So cpptools cannot find standart  *.h(s) (std) (e.g. &lt;vector&gt;, &lt;list&gt;,...).
Manual setting "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe" 
and/or
"includePath":[
"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/include" 
]
not helps because (I suppose) _"configurationProvider": "vector-of-bool.cmake-tools"._ override my changes.
Currently I use without _"configurationProvider": "vector-of-bool.cmake-tools"_, with manual settings

Btw: you are make a cool extension, thank you )))

_Originally posted by @Gargony in https://github.com/microsoft/vscode-cpptools/issues/1839#issuecomment-515837455_

**Comment by Colengms** [comment]
I believe this issue is addressed, starting with 0.26.3-insiders.  Before that version, our clang-cl detection was not working properly.  We would mistake the compiler filename for 'cl.exe', and configure incorrectly.
