### ISSUE TITLE
VS Code doesn't recognize Vcpkg include path

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#4002]
The only dependency is the SFML library, that Vcpkg has inside the include folder. It does not recognize the include path (includePath) when I try to built the program, it gives the error C1083 for "SFML/System.hpp", but if I peek the definition of SFML/System.hpp inside the editor, it recognizes the path and everything.
The project is organized like this:

SFML Study1 [workspace root]
----.vscode [the folder]
--------c_cpp_properties.json
--------launch.json
--------tasks.json
----Entities [a folder]
----GUI Architecture [a folder]
----Identifiers [a folder]
----Others [a folder]
----Processing architecture [a folder]
----Resources [a folder]
----Scenery architecture [a folder]
----State architecture [a folder]
----Data_tables.cpp
----Data_tables.h

Inside the folders "[a folder]" there are only .cpp and .h files, except in "Resources", there are images and one .ttf font file in there.

The "Others" folder is where I have the main.cpp file which has the main function and a pch.cpp and pch.h file (I was making the project in Visual Studio, but I want to try VS Code). In VS Code the pch.h is not a precompiled header anymore, but it has #include directives inside that will work anyway. The "SFML/System.hpp" file is inside pch.h

In the main.cpp file I include the pch.h file, the #include directive for SFML/System.hpp is inmediately after the #include directives for the C++ Standard Library headers, so, it means that VS Code is able to find them, but not able to find the Vcpkg ones (because the error is when "SFML/System.hpp" is reached). I told this just in case...

> c_cpp_properties.json content:

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${vcpkgRoot}/x64-windows/include/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17763.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```

> tasks.json content:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "type": "shell",
            "command": "cl.exe",
            "args": [
                "/EHsc",
                "/Zi",
                "/Fe:",
                "Shoot them up.exe",
                "${workspaceRoot}/Others/main.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal":"always"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}
```

> launch.json content:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(MSVC) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/Shoot them up.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false
        }
    ]
}
```

The include paths are correct.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz (2 x 2167)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.90GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.24.1

</details>

**Comment by sean-mcmanus** [comment]
What error are you getting? Is this a build failure or an IntelliSense failure?

**Comment by Zeleska** [comment]
Terminal output when I run the build task:

> Executing task: cl.exe /EHsc /Zi /Fe: 'Shoot them up.exe' 'C:\Users\Zeleska\source\repos\SFML Study1/Others/main.cpp' <

Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
C:\Users\JULIO ENRIQUE SELVA\source\repos\SFML Study1\Others\pch.h(19): fatal error C1083: Cannot open include file: 'SFML/System.hpp': No 
such file or directory
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

**Comment by ghost** [comment]
@sean-mcmanus 
Terminal output when I execute the build task:

Executing task: cl.exe /EHsc /Zi /Fe: 'Shoot them up.exe' 'C:\Users\Zeleska\source\repos\SFML Study1/Others/main.cpp' <

Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x86 [also, how do I call x64?]
Copyright (C) Microsoft Corporation. All rights reserved.

main.cpp
C:\Users\Zeleska\source\repos\SFML Study1\Others\pch.h(19): fatal error C1083: Cannot open include file: 'SFML/System.hpp': No such file or directory

The terminal process terminated with exit code: 1
Terminal will be reused by tasks, press any key to close it.

**Comment by sean-mcmanus** [comment]
c_cpp_properties.json includePath is just for configuring IntelliSense and not for building. You need to add the path to the vcpkg include path to your build task's command line arguments (/I).

@grdowns Maybe the vcpkg team could write up some doc page on how to build vcpkg stuff with VS Code?

**Comment by ghost** [comment]
@sean-mcmanus how the task.json file should look like?

For example, where should I add "/I ${vcpkgRoot}/x64-windows/include/" in args (the complete task.json is above):

```
"args": [
                "/EHsc",
                "/Zi",
                "/Fe:",
                "Shoot them up.exe",
                "${workspaceRoot}/Others/main.cpp"
            ],
```

**Comment by sean-mcmanus** [comment]
You might need "/I" and the path on separate lines like with "/Fe:" (not sure). I don't think the ${vcpkgRoot} variable is expanded in tasks.json, so you'll probably need to use the resolved path.

**Comment by Zeleska** [comment]
I tried various variations, for example:
"/I C:/Users/Zeleska/source/repos/vcpkg/installed/x64-windows/include/**"
"/IC:/Users/Zeleska/source/repos/vcpkg/installed/x64-windows/include/**"
"/I: C:/Users/Zeleska/source/repos/vcpkg/installed/x64-windows/include/**"
"/I:C:/Users/Zeleska/source/repos/vcpkg/installed/x64-windows/include/**"

"/I",
"C:/Users/Zeleska/source/repos/vcpkg/installed/x64-windows/include/**"

"/I:",
"C:/Users/Zeleska/source/repos/vcpkg/installed/x64-windows/include/**"

etc. I tried without the ** at the end too, also with / being - in /I as in -I

If I put the path after the "/I" the compiler gives a lot of warnings, all being "Command line warning D9024", for example:
cl : Command line warning D9024 : unrecognized source file type 'C:/Users/Zeleska/source/repos/vcpkg/installed/x64-windows/include/libpng16', object file assumed

cl : Command line warning D9024 : unrecognized source file type 'C:/Users/Zeleska/source/repos/vcpkg/installed/x64-windows/include/png.h', object file assumed

and at the end as always: C:\Users\Zeleska\source\repos\SFML Study1\Others\pch.h(19): fatal error C1083: Cannot open include file: 'SFML/System.hpp': No such file or directory

If I try with "/I" and the path being in the same line I only get C:\Users\Zeleska\source\repos\SFML Study1\Others\pch.h(19): fatal error C1083: Cannot open include file: 'SFML/System.hpp': No such file or directory

I will attach a .zip file that contains the project (952kb). Just in case you want to try to build from your computer.
[SFML Study1.zip](https://github.com/microsoft/vscode-cpptools/files/3459257/SFML.Study1.zip)

**Comment by ghost** [comment]
@sean-mcmanus 
Ok, ok, I did it, it was like this:
```
"args": [
    "/EHsc",
    "/Zi",
    "/Fe:",
    "Shoot them up.exe",
    "${workspaceFolder}/Others/main.cpp",
    "/I",
    "C:/Users/Zeleska/source/repos/vcpkg/installed/x64-windows/include/",
    "/I",
    "${workspaceFolder}/Processing architecture",
    "/I",
    "${workspaceFolder}/Entities",
    "/I",
    "${workspaceFolder}/GUI Architecture",
    "/I",
    "${workspaceFolder}/Identifiers",
    "/I",
    "${workspaceFolder}/Others",
    "/I",
    "${workspaceFolder}/Resources",
    "/I",
    "${workspaceFolder}/Scenery architecture",
    "/I",
    "${workspaceFolder}/State architecture",
    "/I",
    "${workspaceFolder}/",
],
```
I wasn't repeating the "/I" before other inclusion.
Is there a more efficient way to do this? It seems I have to do the same for each .cpp file, is there a more efficient way to do that too?

**Comment by vicroms** [comment]
@Zeleska instead of feeding commands directly to the compiler, you may want to take a look at [CMake](https://cmake.org/cmake-tutorial/) or any other build system, e.g.: MSBuild, Meson, etc.

MSBuild or CMake are recommended if you want to take advantage of [vcpkg's build-system integration](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

**Comment by ghost** [comment]
@vicroms thank you for the advice.
