### ISSUE TITLE
Build Task doesnt work when Live Share is disabled

### ISSUE THREAD

**Issue by infalmo** [microsoft/vscode-cpptools#4007]
My keybinding `ctrl+shift+b`(to build a task) doesn't run when live share is disabled or uninstalled. However, it continues working when Live Share is enabled. Is this an intended feature, or merely a bug?

**Comment by pieandcakes** [comment]
@infixint943 This seems to be an issue with [VS Code](https://github.com/microsoft/vscode/issues). Please file an issue on their repo.
