### ISSUE TITLE
Intellisense gives error "qualified name is not allowed"

### ISSUE THREAD

**Issue by drjefffrazier** [microsoft/vscode-cpptools#4009]
**Type: LanguageService**

Intellisense gives incorrect error message, then when I try to play around a bit to isolate the problem, Intellisense stops working entirely until I restart VS Code and re-open the files (several times usually).

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version:
Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
- C/C++ Extension Version:
Version 0.24.1: July 22, 2019
- Other extensions you installed (and if the issue persists after disabling them):
None
- A clear and concise description of what the bug is.
Intellisense gives incorrect error message, then when I try to play around a bit to isolate the problem, Intellisense stops working entirely until I restart VS Code and re-open the files (several times usually).

**To Reproduce**
I can continually do the following in a loop:

1) start with this code snippet in a cpp file:
```
#include <memory>

class Tree
{
    struct Node
    {
        std::shared_ptr<Node> d_left;
        std::shared_ptr<Node> d_right;
    };
};
```

2) Intellisense will show squiggles beneath both instances of `std::shared_ptr`, with an error that says "qualified name is not allowed." I can get the squiggles to go away by removing the `std::`, but this fails to compile for obvious reasons. I can make intellisense -and- the compiler happy by adding `using namespace std;`, but this should not be neccessary.

3) At this point I try to mess around a bit with the code to isolate the issue more, by commenting out the snippet above and just including `<vector>` and trying to declare a vector. Every time I do this, within a few seconds, Intellisense stops working altogether on the unit, and no amount of blatant syntax errors can bring it back.

4) Opening and closing VSCode several times, and opening and closing various cpp files in the workspace will eventually bring Intellisense back, at which point I will be back to the errors from state 1).

**Expected behavior**

Expected for Intellisense to have no issues with the snippet above, and also for it to stay active as I edit the file.

**Comment by drjefffrazier** [comment]
Here is the contents of my c_cpp_properties.json file.

Also, this behavior has just begun in the last few days.

```
{
    "configurations": [
        {
            "name": "Win32",
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17134.0",
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64",
            "includePath": [
                "${default}",
                "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.14.26428/include",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.17134.0/ucrt",
                "${workspaceFolder}"
            ]
        }
    ],
    "version": 4
}
```

**Comment by drjefffrazier** [comment]
One other data point, it seems to only give the error on declarations nested within a type. For the following snippet, it gave squiggles only on the first three `std::shared_ptr`s. However, Intellisense shut off again immediately after I found this.

```
#include <memory>
#include <vector>

class Tree
{
public:
    struct Node
    {
        std::shared_ptr<Node> d_left;
        std::shared_ptr<Node> d_right;
    };

    std::shared_ptr<Node> d_root;
};

std::shared_ptr<Tree::Node> other;
```

**Comment by drjefffrazier** [comment]
Sorry, the previous comment was not quite correct.

In the previous snippet, the three declarations nested in the Tree type all get squiggles with `qualified name is not allowed`.

However, the final line, outside the class, still gives a squiggle with a different error: `namespace "std" has no member "shared_ptr"`.

Thanks.

**Comment by bobbrow** [comment]
The problem is with the configuration.  You have selected your WSL g++ compiler as the compiler to emulate, but you have also supplied MSVC include paths which is confusing IntelliSense.  It's trying to emulate GCC mode, but with MSVC headers (which are incompatible).

We recommend you never add system include paths to the `includePath` variable.  We will auto-populate system include paths for you by using the values supplied in the `compilerPath`, `intelliSenseMode` and/or `windowsSdkVersion` properties.

So the solution to this problem is to either:
* remove the the Visual Studio and WindowsSDK paths from `includePath`
or
* change `compilerPath` to point to `cl.exe` from your BuildTools and change `intelliSenseMode` to `msvc-x64`

**Comment by drjefffrazier** [comment]
Thanks very much. I'm not sure exactly how these lines came to be added, but removing them fixes the issue.
