### ISSUE TITLE
"limitSymbolsToIncludedHeaders" Not Work 

### ISSUE THREAD

**Issue by Jackie-Yang** [microsoft/vscode-cpptools#401]
When I set "limitSymbolsToIncludedHeaders" to "true" in the c_cpp_properties.json, it still show all symbols of the files under the specified include paths
<img width="613" alt="2016-12-12 9 40 28" src="https://cloud.githubusercontent.com/assets/18381153/21085655/644b72d6-c04f-11e6-8d90-5fb17e4ff478.png">
<img width="484" alt="2016-12-12 9 46 36" src="https://cloud.githubusercontent.com/assets/18381153/21085704/e7c238b6-c04f-11e6-81f4-3e507a58a698.png">

**Comment by sean-mcmanus** [comment]
The limitSymbolsToIncludeHeaders appears to be working for me. It is recursive, so I suspect that the big list of items is recursively reachable from stdio.h. You should notice that other files in /usr/include/poll.h are not processed unless you explicitly added it. On my Mac, pthread_attr_t is included from /user/include/sys/_pthread and not /Applications/..., so I'm not sure why that is different in your screenshot. If you still think this is buggy, we could investigate more later. Preferably you could provide more specific repro steps for the buggy behavior.

**Comment by bobbrow** [comment]
Please reopen if you are still experiencing an issue with the limitSymbolsToIncludedHeaders setting.  We are not seeing any problems on our side.  (You may need to delete your old browse database if it has already been populated with symbols you don't want)

Thanks!
