### ISSUE TITLE
CPPTOOLS

### ISSUE THREAD

**Issue by busterbeam** [microsoft/vscode-cpptools#4010]
Issue Type: <b>Feature Request</b>

Their inststructions are garbage here ask them to change it to recomending a compier not some middlewere/BLOATWERE.  More like be-ware this is a bad extenstion, maybe a bad text editor if you just want to do c++, can people get brains.

Extension version: 0.24.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by pieandcakes** [comment]
@busterbeam If you have specific feedback/issues please add them. These comments don't help contribute to the community.
