### ISSUE TITLE
Integrating VSCode debugger with the xtensa-lx106-elf-gdb

### ISSUE THREAD

**Issue by CFornari** [microsoft/vscode-cpptools#4011]
Type: Debugger

I'm programming a microcontroller and my attempts to integrate its debugger to the VSCode isn't going well, the debugger is working when running from the terminal, the process is this: 

1. Flash the code to the MCU;
2. Run the GDB (communicates through serial port);

Here is the terminal command for item 2:
`/home/user/sdks/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gdb -x /home/user/sdks/Sming/Sming/Arch/Esp8266/Components/gdbstub/gdbcmds -b 460800 -ex "target remote /dev/ttyUSB0"`

Here is my attempt to reproduce this in the `launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "xtensa-lx106-elf-g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/out/Esp8266/debug/build/app_0.out",
            "logging": { "engineLogging": true },
            "args": [
                "-x /home/user/sdks/Sming/Sming/Arch/Esp8266/Components/gdbstub/gdbcmds",
                "-b 460800",
                "-ex \"target remote /dev/ttyUSB0\""
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "miDebuggerPath": "/home/user/sdks/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gdb"
        }
    ]
}

```

I receive the error:

**ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". Don't know how to run.  Try "help target".**

You can see that this `gdb` doesn't take any `program` as input, but when I leave the field empty I receive error instructing to give a file.

I think issue #2778 has some similarities, but couldn't solve the problem with information in that issue. I found other issues, but no useful information in there.

I would like to receive some guidance to implement the item 2 command in the json.

**System information**
-OS and Version: Ubuntu 18.04.2 -- Linux x64 5.1.0-050100-generic
-VS Code Version: 1.36.1
-C/C++ Extension Version: 0.24.1
-The issue persist after disable all other extensions.

**Comment by pieandcakes** [comment]
@Oshio09 If you do a [search in our issues](https://github.com/microsoft/vscode-cpptools/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Adebugger+XTENSA+) for XTENSA we have other users that you can ask about it. 

Unfortunately I have no experience with XTENSA and no device here to figure it out right now. This is something we are hoping the community can contribute in the way of documentation/help.

**Comment by pieandcakes** [comment]
It looks like someone updated #1447 with a [configuration](https://github.com/microsoft/vscode-cpptools/issues/1447#issuecomment-517906636) to debug Arduino with `Xtensa` that might be helpful.
