### ISSUE TITLE
Sometimes colorization is broken and "go to definition" don't give tip "No definition found for xxxx"

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#4012]
Sometimes colorization is broken for unknown reasons.  Sometime function/variable color is wrong.  I think code colorization need to be tested more.

**Comment by Lennon925** [comment]
In addition, when there is no definitions results of "go to definition", some of them don't give tip "No definition found for xxxx ", no  any response.

**Comment by michelleangela** [comment]
@Lennon925 , thanks for your feedback.

> In addition, when there is no definitions results of "go to definition", some of them don't give tip "No definition found for xxxx ", no any response.

Please create another thread for this "go to definition" issue. This is so we can track each issue separately without one getting lost.

As for the colorization issue, it would be helpful if you can find and provide specific steps that reproduces the issue with function and variable colors to give us information to investigate with.

**Comment by sean-mcmanus** [comment]
Are you using the linux code base? No response at all to Go to Def might mean the main thread is stuck. That would also cause colorization to be stale -- I've seen stale colors after the IntelliSense process crashes. Our next release may have better crash recovery of the IntelliSense process.

**Comment by Lennon925** [comment]
> Are you using the linux code base? No response at all to Go to Def might mean the main thread is stuck. That would also cause colorization to be stale -- I've seen stale colors after the IntelliSense process crashes. Our next release may have better crash recovery of the IntelliSense process.

About "No response", I mean that when you press F12 to go to definition, Neither go to symbol's definition, nor show "no definition found for xxxx". The cursor still stay the origin position. vscode is not stuck.

**Comment by sean-mcmanus** [comment]
Our extension operates outside of the VS Code process so the UI shouldn't be stuck, but I believe not showing "no definition" means that our extension process is stuck -- are you saying other extension operations still work?

**Comment by Colengms** [comment]
Hi @Lennon925 .  Both Go To Definition and semantic colorization rely on IntelliSense.  For complex code, IntelliSense may take a long time to refresh.  If it never refreshes, perhaps your code is exposing an IntelliSense parsing bug causing the IntelliSense process to crash.  You might check if you see the Microsoft.VSCode.CPP.IntelliSense.Msvc.exe process die while waiting for IntelliSense to update.  If that is the issue, some code that repro's the issue would help us pinpoint the issue and address it.

**Comment by Lennon925** [comment]
> Our extension operates outside of the VS Code process so the UI shouldn't be stuck, but I believe not showing "no definition" means that our extension process is stuck -- are you saying other extension operations still work?

Yes，other extension operations still work.

**Comment by Lennon925** [comment]
> Hi @Lennon925 . Both Go To Definition and semantic colorization rely on IntelliSense. For complex code, IntelliSense may take a long time to refresh. If it never refreshes, perhaps your code is exposing an IntelliSense parsing bug causing the IntelliSense process to crash. You might check if you see the Microsoft.VSCode.CPP.IntelliSense.Msvc.exe process die while waiting for IntelliSense to update. If that is the issue, some code that repro's the issue would help us pinpoint the issue and address it.

I agree with you. Because I can't give the code that repro's the issue, I didn't paste them here. it occured in my complex code, but in simple code, it didn't occur. 
I transcibed a gif picture for you, maybe it's helpful for you although it can't help you find the reason     right now.

![demo](https://user-images.githubusercontent.com/39362073/62405349-eddbb480-b5ce-11e9-8a20-a4ef7252f917.gif)

In gif, actually mytest() function don't exist in my code. But there is no error squiggle for it. It's strange.

**Comment by sean-mcmanus** [comment]
It's treating myTest() as a declaration of "int myTest()" so go to Def is going to itself. This is "by design" behavior with C code, which explains why there are no error squiggles.

**Comment by Lennon925** [comment]
> Hi @Lennon925 . Both Go To Definition and semantic colorization rely on IntelliSense. For complex code, IntelliSense may take a long time to refresh. If it never refreshes, perhaps your code is exposing an IntelliSense parsing bug causing the IntelliSense process to crash. You might check if you see the Microsoft.VSCode.CPP.IntelliSense.Msvc.exe process die while waiting for IntelliSense to update. If that is the issue, some code that repro's the issue would help us pinpoint the issue and address it.

Now I can repro this issue every time even though in simple code. You can follow my steps as following:

1. Create a new Folder "Test".
2. New a test.c file.
3. Fill test.c with following codes:
```
void test(){
    int mm = 0;
    mm++;
    mytest();
}
```
If you change test.c to test.cpp, its behaviour is right. Are there some differences between .c and .cpp?

**Comment by sean-mcmanus** [comment]
Did you see my response https://github.com/microsoft/vscode-cpptools/issues/4012#issuecomment-517883536 ?

**Comment by Lennon925** [comment]
> Did you see my response [#4012 (comment)](https://github.com/microsoft/vscode-cpptools/issues/4012#issuecomment-517883536) ?

But I think it's a function reference instead of a declaration. If you change mytest() to mytest(9,0), its behaviour is same.
If there are some functions which have no params, how to recognize it's a function which has no definition or a function declaration?

**Comment by sean-mcmanus** [comment]
If you use
```
int main()
{
foo(1, 0);
}
````
in a .c file, gcc will give a warning about an implicit declaration of function foo being used. (We don't currently show a warning unless the hidden warning feature is enabled).

See https://github.com/microsoft/vscode-cpptools/issues/828 for the issue tracking it and the details on a potential workaround.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
