### ISSUE TITLE
some file can't find while debug on remote-wsl

### ISSUE THREAD

**Issue by void-mian** [microsoft/vscode-cpptools#4013]
Type: Debugger

**Describe the bug**
- OS and Version: windows_NT x64 10.0.3497.128
- VS Code Version:1.36.1
- C/C++ Extension Version:0.24.1
- Other extensions you installed (and if the issue persists after disabling them):
1. when I debug using remote-wsl and run through a line with a function called memset these is an error shown,but when I debug the same cpp file while opened my windows folder it just walk through this line.(I use F11 which shold means step into)
2. ps: this error message occurred before while I using my windows file before,but it has been fixed
3. the error message: 无法打开“memset-vec-unaligned-erms.S”: Unable to read file (Error: File not found (vscode-remote://wsl+ubuntu-18.04/build/glibc-OTsEL5/glibc-2.27/sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S))。

**To Reproduce**
+ launch.json and tasks.json I just use the default one("g++ build and debug active file" and "g++ build active file").
+ launch.json:
```json
"version": "0.2.0",
    "configurations": [
        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
```
+ tasks.json:
```json
"version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "/usr/bin"
            },
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
```
**Steps to reproduce the behavior:**
1. Open code under wsl terminal(or just switch to wsl-remote in windows application)
2. Open a folder
3. Make a breakpoint on the line write with a memset function
4. Start Debug(use F5)
5. Step into(F11)
6. See error

**Comment by pieandcakes** [comment]
That is the source code from the library and the line that `gdb` returns. You can ignore the error and continue debugging or choose the line that you want to see in the Stack window.

**Comment by void-mian** [comment]
But when I try to ignore it (I press F11 to "step over",not switch to F10),and the error message comes continuously and about 5 times I press F11,the debugger just closed.(though these is nothing error occurred if I press F10 to ignore it.)

**Comment by pieandcakes** [comment]
Step Over only steps over the current line in that same file which is why you continue to get that error. 

If you have the source for that method, you can set up `sourceFileMap` in your `launch.json` to point to that file in WSL. 

If you are also using `gdb` on Windows, it should give you the same error. If you are using the `Microsoft Visual C++` debugger, it might be skipping over this because in `Microsoft Visual C++` there is a feature known as `Just My Code` that allows the debugger to know when it is not code you have written.
