### ISSUE TITLE
[cppvsdbg] sourceFileMap doesn't work when symbol paths are relative

### ISSUE THREAD

**Issue by CloudyMcFox** [microsoft/vscode-cpptools#4017]
Issue Type: <b>Bug</b>

Even after I set sourceFileMap, VS Code still fails to find source file (sourceFileMap  doesn't seem to take effect). I get:

Unable to open 'cupperscan.cpp': Unable to read file (Error: File not found (c:\Users\<USER>\AppData\Local\Programs\Microsoft VS Code\...)

My tasks.json has:

            "sourceFileMap": {
                "c:\\Users\\<USER>\\AppData\\Local\\Programs\\Microsoft VS Code": "C:\\Source\\Engine\\src"
            },

Extension version: 0.24.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pieandcakes** [comment]
@CloudyMcFox you mention in your issue you are putting it in your `tasks.json`. If you are using it during debugging, it needs to be in your `launch.json` .

If it still doesn't work after you move it, can you provide an [engine log](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging)?

**Comment by CloudyMcFox** [comment]
I am sorry that was a typo. I meant to say launch.json:

![image](https://user-images.githubusercontent.com/18708122/62659308-d9295480-b91f-11e9-9d71-c01b63a9f56b.png)

**Comment by CloudyMcFox** [comment]
Engine log:
[enginelog.log](https://github.com/microsoft/vscode-cpptools/files/3479077/enginelog.log)

**Comment by pieandcakes** [comment]
@CloudyMcFox can you try and end the left side with `\\` and make sure your right hand side is `g:\\Source\\Engine\\src\\` ?

**Comment by CloudyMcFox** [comment]
Thanks for the response @pieandcakes. Tried this with no success. I even made sure the path was cased exactly. Attaching screenshots:
![1](https://user-images.githubusercontent.com/18708122/63544182-68feff00-c4d9-11e9-8584-b60dabba6241.png)

![2](https://user-images.githubusercontent.com/18708122/63544190-6bf9ef80-c4d9-11e9-899d-a48eee11089d.png)


![3](https://user-images.githubusercontent.com/18708122/63544212-7b793880-c4d9-11e9-812f-2c80d9f71597.png)

**Comment by pieandcakes** [comment]
I was able to investigate @CloudyMcFox 's scenario and his symbols are not full paths. It looks like when we try and resolve the partial path, it is appending the running directory for VS Code.

One of the troubleshooting steps for users running into this would be to run `[cvdump.exe](https://github.com/microsoft/microsoft-pdb/blob/master/cvdump/cvdump.exe) -l <exe or dll> > output.txt` and then look in output.txt for the file line info from your symbol file. When doing this you can see where the path starts and create a source file map.

## Example

Source lin in symbol: `bar\baz.cpp`
Example mapping:

```
"sourceFileMap": {
    "bar": "c:\\foo\\bar"
}
```

You can also use `${workspaceFolder}` in the value portion of the mapping (Doesn't work in the key though).
