### ISSUE TITLE
I cannot watch elements of array.

### ISSUE THREAD

**Issue by renkarsu** [microsoft/vscode-cpptools#4021]
Type: Debugger
**Describe the bug**
- OS and Version: windows10, latest
- VS Code Version: latest
- C/C++ Extension Version: latest
- Other extensions you installed (and if the issue persists after disabling them): none
- A clear and concise description of what the bug is.
I cannot watch elements of arrays in C++, but I can watch variable.

I know debugging result have to be same condition like under picture.
![image](https://user-images.githubusercontent.com/42439654/62462135-8fc2f300-b7c1-11e9-84fc-b842d5273637.png)

However, my vscode shows
![image](https://user-images.githubusercontent.com/42439654/62462399-48893200-b7c2-11e9-8d3a-d1e67db8aab4.png)

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
Here is my launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [
                "<",
                "input.txt",
                ">",
                "output.txt"
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\msys64\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++.exe build active file"
        }
    ]
}

thank you

**Comment by pieandcakes** [comment]
Your issue is with variable visualization which is a feature of `gdb` called `pretty printing`.

According to [this](https://sourceware.org/gdb/onlinedocs/gdb/Pretty_002dPrinter-Commands.html) document, you can run `info pretty-printer` in your instance of `gdb` to see if you have the right pretty-printers installed for the types you want to visualize.

**Comment by renkarsu** [comment]
I can never thank you enough! Thank you! Thank you!

I am not good at English, so I may confuse you.
**To those who are troubled by the same thing**, I check `gdbinit` in `C:\msys64\mingw64\etc`.
Then, it has been changed as follows.
```
python
import sys
sys.path.insert(0, sys.path[0] + '/../../gcc-8.3.0/python')
from libstdcxx.v6.printers import register_libstdcxx_printers
register_libstdcxx_printers (None) # I added this line
end
```
This worked fine.

Probably, you are Msys2 user.
