### ISSUE TITLE
Unable to start debugging

### ISSUE THREAD

**Issue by DukeLaze** [microsoft/vscode-cpptools#4022]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows 10 pro v. 1803 (OS Build 17134.706)
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
   Using mingw, g++ and gdb
- Other extensions you installed (and if the issue persists after disabling them):
    Code Runner 0.9.12
    Easy C++ Projects
    Issues persists after disabling.
- A clear and concise description of what the bug is.
   Upon trying to debug (Green arrow "Run" or F5) VSCode spits out a "Cannot find debug 
   adapter for tpye 'cppdbg'
   In addition, if I create a new c++ "project" and choose to add a new debug configuration, the    
   cpptools extension crashes ('Extension host terminated unexpectedly')
**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

>{   
>   "version": "0.2.0",  
>   "configurations": [  
>       {
>           "name": "(gdb) Launch",
>           "type": "cppdbg",
>           "request": "launch",
>           "program": "${workspaceFolder}/issue.exe",
>           "args": [],
>           "stopAtEntry": true,
>           "cwd": "${workspaceFolder}",
>           "environment": [],
>           "externalConsole": false,
>           "MIMode": "gdb",
>           "miDebuggerPath": "C:\\\MinGW\\\mingw64\\\bin\\\gdb.exe",
>           "setupCommands": [
>               {
>                   "description": "Enable pretty-printing for gdb",
>                   "text": "-enable-pretty-printing",
>                   "ignoreFailures": true
>               }
>           ]
>       }
>   ]
>}

* Issue.cpp
>#include <iostream>
>
>int main() {
>    int x;
>
>    std::cin >> x;
>
>    std::cout << "You entered: " << x << std::endl;
> }

1. Open a new workspace/folder
2. Create the required files (launch.json and issue.cpp)
3. Compile issue.cpp (g++ -o issue.exe issue.cpp)
4. Try to launch debugging in any of the ways possible
5. Error.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

Have tried reinstalling cpptools.
Have tried running gdb manually (it works)

Please ask for additional information if required.
(also, very sorry for formatting issues)

**Comment by pieandcakes** [comment]
Can you confirm that your `miDebuggerPath` path has the `\` escaped like `C:\\folder\\to\\gdb` ?

**Comment by DukeLaze** [comment]
@pieandcakes Yes, it is escaped properly, sorry for not noticing in the paste.

**Comment by pieandcakes** [comment]
@DukeLaze I haven't been able to repro but I also noticed that you aren't compiling with `-g` flag to enable debug symbols. That shouldn't be causing the problem but you'll run into an error later. 

When you reinstalled cpptools, did you verify that the `c:\\users\\<your_username>\\.vscode\extensions` folder did not have the `cpptools` extension folder in it before you reinstalled? Try uninstalling the extension, deleting the folder (it should start with `ms-vscode.cpptools`) and then restart VS Code and reinstall. When you reinstall it, you'll have to restart VS Code one more time.

**Comment by DukeLaze** [comment]
@pieandcakes The folder(s) for cpptools were indeed there after uninstalling.
Alas, uninstalling -> Deleting the folders -> Restarting vscode and reinstalling the extension didn't help.
I'm getting "Extension host terminated unexpectedly" whenever I try to start debugging now (also compiled with the `-g` flag this time). Trying to restart the extension just leads to the error repeating.

**Comment by pieandcakes** [comment]
@DukeLaze I would suggest this process if it is still not working:
* Uninstall the extension
* delete the folders
* Restart VS Code and install the extension
* Go to the output window and look at the `C/C++` output (in the drop down) and see if there are log messages about it downloading components. Make sure that it is done downloading.
* Restart VS Code one more time and try and start debugging. 

the message of `Extension host terminated unexpectedly` usually means that VS Code is throwing an error when starting up our extension which could be missing dependencies that we download after you install the extension.

**Comment by WardenGnaw** [comment]
Closing due to not enough info. Please update to the latest extension version and open a new issue if this problem is occuring.
