### ISSUE TITLE
A mistake in the program path does not produce an obvious error message

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode-cpptools#4024]
Type: Debugger

I just spent several hours trying to understand why I was getting a `NullPointerException` in the debug console when trying to start the debugger. After a lot of looking, I found that I had written `${workspaceDirectory}/executable` instead of `${workspaceFolder}/executable` in my `launch.json`. This mistake should be made more obvious to the user.

If it matters, I am doing this over a remote SSH connection, as detailed below.

- Version: 1.37.0-insider (user setup)
- Commit: 4a03f7e7eff2560d2e53c029321870514d19a2aa
- Date: 2019-08-05T09:34:10.366Z
- Local OS: Windows_NT x64 6.3.9600 (Windows 8)
- Remote OS Version: CentOS Linux Release 7.4.1708
- Remote Extension/Connection Type: SSH

**Comment by pieandcakes** [comment]
@kylrth This will be fixed in the next release

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.25.0.
