### ISSUE TITLE
Disable Automatic Comment Block

### ISSUE THREAD

**Issue by keaton-freude** [microsoft/vscode-cpptools#4025]
**Type: LanguageService**
I can't figure out if there is a setting for this, so apologies if it is documented somewhere.
When I write `/*` in a `.cpp` file, I automatically get a matching `*/` inserted. This is driving me crazy when I just want to comment out a block of code.

How can I disable this? As far as I can tell, this happened in a recentish version of the extension because I do not remember this behavior in the past.

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is.

**To Reproduce**

1. Open a `.cpp` file.
2. In the editor, outside of any existing comment blocks, type `/*` note that a matching `*/` is automatically inserted.

**Expected behavior**
I expected a setting to be present.

Apologies if this information is present somewhere, I glanced through the docs and searched for it. Couldn't find a way to disable it, only customize it.

Thanks for the awesome extension!

**Comment by bobbrow** [comment]
This is https://github.com/microsoft/vscode/issues/77008.  Sorry for the inconvenience!  A fix should be coming out soon.
