### ISSUE TITLE
Ctrl+Mouse click is still slower than using F12 to go to definition

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#4026]
Cpptools version : 0.24.1

Ctrl+Mouse click is still slower than using F12 to go to definition

**Comment by sean-mcmanus** [comment]
This is most likely because hover computation is delaying the Go to Def. Maybe there's some way to detect this and skip hover.

I assume if you hover, wait for the results, and then ctrl+click is the speed will be the same (I could double check this later).

**Comment by sean-mcmanus** [comment]
Actually, the Ctrl+Click also sometimes triggers a didOpen, IntelliSense update, didClose, which can also cause slowness (you can see the messages via loggingLevel "Debug").

This is a known VS Code API issue that we don't currently have a way to prevent...unless we happen to think of something creative workaround.

**Comment by Lennon925** [comment]
> Actually, the Ctrl+Click also sometimes triggers a didOpen, IntelliSense update, didClose, which can also cause slowness (you can see the messages via loggingLevel "Debug").
> 
> This is a known VS Code API issue that we don't currently have a way to prevent...unless we happen to think of something creative workaround.

You are right. VS Code API is very slow. Currently the speed is not the same with F12 even though hover finished. I think this is related with VS Code API because I encountered some similar issue in our own extensions.

Are there any ways to forbid the hover in code ?  If so, the speed should be the same with F12.

**Comment by sean-mcmanus** [comment]
To avoid hover when doing ctrl+click, you can quickly click the identifier before you see the hover tooltip appear, then use the cltr+click -- if you still see slowness, then it's because it's doing the additional didOpen and/or a 2nd definition when the Ctrl key is pressed -- this seems like a VS Code bug because it shouldn't do the didOpen/definition until the cursor moves and a hover is sent.

There's a thread related to this at https://github.com/microsoft/vscode/issues/78453 -- we may be able to do some additional checks to skip the definition/didOpen processing when Ctrl is used.

**Comment by Lennon925** [comment]
> To avoid hover when doing ctrl+click, you can quickly click the identifier before you see the hover tooltip appear, then use the cltr+click -- if you still see slowness, then it's because it's doing the additional didOpen and/or a 2nd definition when the Ctrl key is pressed -- this seems like a VS Code bug because it shouldn't do the didOpen/definition until the cursor moves and a hover is sent.
> 
> There's a thread related to this at [microsoft/vscode#78453](https://github.com/microsoft/vscode/issues/78453) -- we may be able to do some additional checks to skip the definition/didOpen processing when Ctrl is used.

OK, Thanks for your reply.

**Comment by Colengms** [comment]
I believe this will be addressed in the next release, fixed by https://github.com/microsoft/vscode-cpptools/pull/4593 (and https://github.com/microsoft/vscode-cpptools/pull/4621).  We will avoid processing didOpen for intelliSense operations that do not involve displaying the contents.
