### ISSUE TITLE
Auto completion fails after snippets choosed.

### ISSUE THREAD

**Issue by foreverlms** [microsoft/vscode-cpptools#4029]
**Type: LanguageService**

OS: Ubuntu 14.04
vscode: 
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.4.0-142-generic
C/C++: Version 0.24.1

It's really annoying! For example, I have a segment of code like below.
![image](https://user-images.githubusercontent.com/20502148/62630459-8f615e00-b961-11e9-9b52-4c185fbca3a9.png)

When I type 'whi', the intellisense will automatically suggest `while` loop, ok, it's fine. But when I choose the first snippet, the automatical completion of function `guess` fails in the parenthesis. There is nothing popped. But when I type the `while ` loop myself, it works well in the parenthesis and gives the right suggestion of function `guess`. What's wrong? I have tried a lot, it appears 100%.

Hopefully expect your suggestions and solutions. Thanks! My mother-tongue isn't English and I have googled by myself, but I can't have the solution found.

**Comment by michelleangela** [comment]
@foreverlms , could you explain what you mean by "when I choose the first snippet"? Do you mean choosing the first snippet from the auto-completion suggestion like the following:

![image](https://user-images.githubusercontent.com/38734287/62655430-ccecc980-b916-11e9-97da-f0005c005d58.png)

After I choose the suggestion "guess", it inserts `guess` in the `while()`, and it becomes `while(guess)`.

**Comment by bobbrow** [comment]
This is actually an intentional VS Code behavior.  According to this: https://github.com/microsoft/vscode/issues/45716, you can opt out of the behavior with the `"editor.suggest.snippetsPreventQuickSuggestions": false` setting.

You can also manually invoke auto-complete by pressing CTL+Space.

**Comment by foreverlms** [comment]
@bobbrow Thanks!
