### ISSUE TITLE
-imsvc flag ignore in compile_commands.json 

### ISSUE THREAD

**Issue by Gargony** [microsoft/vscode-cpptools#4032]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them):

Looks like IntelliSence ignores [-imsvc](https://clang.llvm.org/docs/UsersManual.html#id9) flag, when parse compile_commands.json

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
The fix should be in 0.25.0-insiders2: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders2 .
