### ISSUE TITLE
[win][mingw]Unable to start debugging

### ISSUE THREAD

**Issue by aaronweldy** [microsoft/vscode-cpptools#4033]
Type: Debugger
**Input information below**

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version: Windows 10 
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is: I cannot get gdb to attach to my c++ code. If I leave the externalConsole as true, it says that --exec-run fails, with error 193. If I set it to false, I get that my code cannot connect to gdb. 

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
launch.json:
![launch](https://user-images.githubusercontent.com/41965433/62689088-b3be4880-b9fc-11e9-975a-ddd173d78d6e.JPG)
error log w/externalConsole: 
![ext1](https://user-images.githubusercontent.com/41965433/62689157-dc464280-b9fc-11e9-97d6-0dd5b35f8554.JPG)
![ext2](https://user-images.githubusercontent.com/41965433/62689161-dd776f80-b9fc-11e9-9c32-8c11e4d5292b.JPG)
error log w/o externalConsole: 
![naext](https://user-images.githubusercontent.com/41965433/62689216-f7b14d80-b9fc-11e9-9459-a47754772bad.JPG)

**Comment by pieandcakes** [comment]
@aaronweldy you need to make sure that the mingw bin path is in your $PATH. During run time, your executable needs to load libs from it and if it can't find it, it will fail with that error.

**Comment by aaronweldy** [comment]
Yes -- I have added the path of MinGW to my Windows environment variable, and I also added the "includePath" to c_cpp_properties.json as shown below: 
![mingw](https://user-images.githubusercontent.com/41965433/62777734-ea6d8f00-bae0-11e9-9fa3-291d6715be54.JPG)

I'm still getting the same error output.

**Comment by bobbrow** [comment]
`includePath` is not used by the debugger. It's for IntelliSense only.  But while I'm commenting, I'll recommend you remove the system include paths from your `includePath`.  The extension gets these from the `compilerPath` property.  It's more accurate that way.

**Comment by pieandcakes** [comment]
@aaronweldy So when `gdb` starts the process it is unable to and is showing error 193. A quick internet search shows that 193 means it might be a bad executable format. Can you try and run your `a.out` from the command line to see if it works?

>If I set it to false, I get that my code cannot connect to gdb.

I suspect that it is connected to not being able to start the executable.

**Comment by aaronweldy** [comment]
I saw that too when I googled it, but running ./a.out works fine on the command line: 
![out](https://user-images.githubusercontent.com/41965433/62821352-0edf6f00-bba6-11e9-8808-fd7803975748.JPG)

Something weird I noticed -- when I run the "gdb" command on the command line, it runs a version different from the MinGW that I have installed: 
![gdb](https://user-images.githubusercontent.com/41965433/62821368-2dde0100-bba6-11e9-86ef-6eddd81d4bf2.JPG)

Also, not sure if this matters, but there's a "command not found" error on the command line when I run the debugger: 
![output](https://user-images.githubusercontent.com/41965433/62821437-6af6c300-bba7-11e9-958d-f0f73d07ac8e.JPG)

**Comment by pieandcakes** [comment]
@aaronweldy Are you trying to use MinGW or WSL? When you run the command in your terminal, it is running it in WSL which is using the WSL command line and environment. Those binaries are not compatible with MinGW as they are compiled as if on Linux and not able to run in a regular Windows environment. 

If you go to Start -> Run and run `cmd.exe` and then try and run your `a.out` will it run? I suspect it will not, and thats why it is not working.

**Comment by pieandcakes** [comment]
If you want to use WSL (Windows Subsystem for Linux) you can. It would require you to install VS Code's Remote WSL extension and then our extension will run natively as if you were on Linux and that will work.
