### ISSUE TITLE
Intellisense is not working for c++ libraries 

### ISSUE THREAD

**Issue by subhmm** [microsoft/vscode-cpptools#4034]
**Type: LanguageService**  C++

Unable to detect the c++ libraries

![Screenshot (6)](https://user-images.githubusercontent.com/45540171/62709130-6947c680-ba12-11e9-99c3-9149cc266944.png)

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
We need more info. You're probably not configured correctly. What does it say when you use the C/C++: Log Diagnostics command?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
