### ISSUE TITLE
Copying value from long std::string variable in "Locals" ends with "..."

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode-cpptools#4035]
Type: Debugger

Values copied from a long string's value the debug console don't copy entirely, but look like:

```
"some super long string!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"...
```

**To Reproduce**

1. Debug some code with a very long string variable.
2. Set a breakpoint so the variable appears in the debug console under "Locals".
3. Right click the variable and select "Copy Value"

Maybe this is just a gdb thing though.

**Comment by pieandcakes** [comment]
Yes, it is. https://github.com/microsoft/vscode-cpptools/issues/3646 talks about it and the work around.
