### ISSUE TITLE
Add a setting for the max threads to use for Find All References

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4036]
1. Do Find All References (Rename would have the same issue after it's released).

Bug: It uses all the available cores (minus 1), which is the same as VS's default, but VS also has a setting to set the max cores. E.g. C_Cpp.maxReferencesThreads (between 2-31).

Upvote this issue if you think this is important to add.

**Comment by Lennon925** [comment]
Currently it's slow to find all references if there are many code files in your project.

**Comment by sean-mcmanus** [comment]
FYI, adding this setting wouldn't make Find All References faster -- it would just enable users to use less cores, making Find All References slower (not sure why a user would want that...maybe if the 100% CPU usage causes their machine to freeze up?). And there are certain points in the operation that will use less cores.

**Comment by sean-mcmanus** [comment]
Actually, if a user's machine doesn't have enough memory compared to cores, it could cause memory thrashing, so limiting it to fewer threads could increase performance in those cases.

**Comment by heartacker** [comment]
@sean-mcmanus Should I change the default value to boost my cpptools speed?

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/143987970-1e50a0b7-5c30-4fe7-a232-542b02199b65.png)
ALSO,  `Max Cached Process` is set to 0 by default. not null. Is there something we should concern

**Comment by bobbrow** [comment]
It looks like a bug in the translation.  It should be 0.  I saw something similar for the German translation when I checked a while back, but missed this one.

**Comment by bobbrow** [comment]
Sorry, I got it backwards. `null` is the default value when the setting is not set.  Setting it to 0 will pick our lowest acceptable value for the setting (which I think is 2).  Use the gear icon to clear the value if it's showing 0.  Are you saying that it will always show 0 there?

**Comment by heartacker** [comment]
no， it can be changed, and the default is 0, not null

**Comment by bobbrow** [comment]
Ah hah, I was looking at the wrong one.  This is for the **References** Max Cached Processes.

**Comment by bobbrow** [comment]
Yes, it's a bug.  We'll fix it.

**Comment by sean-mcmanus** [comment]
Sorry for the confusion -- the 0 default is currently "by design". We could potentially change the default to null if we discover that it's a better default, but we don't know yet if that is the case or not, i.e. due to the increased memory usage and the fact that the lexer/search results are also not cached (which in some cases may be the bottleneck in Find All References performance).

**Comment by sean-mcmanus** [comment]
Also, to clarify, this particular issue most closely corresponds to the `C_Cpp.references.maxConcurrentThreads` setting (and https://github.com/microsoft/vscode-cpptools/issues/4038 is tracking the `C_Cpp.references.maxCachedProcesses` setting).
