### ISSUE TITLE
Add a setting to enable caching of Find All References clients for non-opened files

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4038]
Currently, IntelliSense clients are only kept around for opened files. In VS, they are also kept around from the clients created from Find All References, based on a setting and in some cases memory usage.

The current workaround is to open any files if you want Find All References to be faster for those files....but if memory goes over 1 GB we'll start to close clients, so we may want to improve that as well.

**Comment by Lennon925** [comment]
Hi Sean，0.25.insider can be realeased on time this week?

**Comment by Lennon925** [comment]
Currently it's slow to find all references if there are many code files in your project. It will be better if it can find references faster.

**Comment by sean-mcmanus** [comment]
To be more specific, doing this change would only decrease the time it takes in the "confirming" phase when the same file has to be confirmed that was already confirmed in a previous Find All References operation. But if you did 2 Find All References that had to confirm references in 16 different files, then there would be no speed up. The speed up would be equivalent to the speed up a user would gain via manually opening the files with references before doing a Find All References (assuming the clients aren't close due to memory usage).

**Comment by sean-mcmanus** [comment]
This available in https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders 
 via the `C_Cpp.references.maxCachedProcesses` setting (it currently default to 0, i.e. opt-in).
