### ISSUE TITLE
"Click to preview" is disabled for "Peek References"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4040]
Find All References allows previewing of the current results via clicking the search icon, but Peek References has this disabled because when we re-issue the Peek Reference and the cursor hasn't moved then the Peek Reference dialog box disappears. It's possible there might be a way to add some workaround? Let me know if anyone thinks they know how to fix this in the open source TypeScript -- the VS Code team is telling us they don't want us to implement "click to preview" and want to implement "streaming", but there's no ETA for that. See https://github.com/microsoft/vscode/issues/77617 and https://github.com/microsoft/vscode/issues/20010 .

UPDATE: The preview can be shown in the Output window as a "Confirmed Reference" -- related work needs to be done for Rename anyway.

There was also a minor bug where it would say "Confirmation in progress" if the peek window was closed instead of "Confirmation canceled".

**Comment by bobbrow** [comment]
Not seeing a lot of feedback on this. Closing...
