### ISSUE TITLE
Add a command to filter out references by "type"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4042]
Currently all "types" of references are show in the "C/C++: References" output. It would be nice to have a command to filter out unwanted "types" -- however, from my experience, it seems like all the "types" are potentially useful to see...so let us know if you really don't be able to filter stuff out (or if anyone wants to implement this themselves in our open source TypeScript).

Also, we could potentially have a setting that move the types that are not "confirmed references" into the References Results -- but since there's no way to tell what the "types" are that seems like it would be too confusing.

**Comment by bobbrow** [comment]
I think this was addressed with the UI work.
