### ISSUE TITLE
Peek References could incorrectly trigger Find All References and vice versa

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4045]
Let us know if anyone hits an issue where Peek References is incorrectly doing a Find All References or vice versa -- it would repro 100% in certain (unusual) conditions. VS Code doesn't tell us if a Peek versus Find is used so use an imperfect heuristic to try to guess which command is used. It's possible we could fix this via handling the onDidExecuteCommand added to 1.37 of VS Code.

**Comment by bobbrow** [comment]
Not seeing a lot of feedback on this.  Closing...
