### ISSUE TITLE
Log file word wrapping is disabled by default

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4047]
This is because we want the "C/C++ References" output to not have word wrapping and VS Code doesn't have better APIs for configuring this. See https://github.com/microsoft/vscode/issues/78245 .

The workaround is to overwrite the default setting, e.g.
```
      "[Log]": {
        "editor.wordWrap": "on"
      }
```

**Comment by bobbrow** [comment]
Since we moved to the UI for references, do we need to keep this setting anymore?  I know peek references still sends extra info to the output window, but maybe this doesn't matter anymore.

**Comment by sean-mcmanus** [comment]
The wrapping disabling gives better results for our C/C++ logging too. We haven't gotten any user complaints that the non-wrapping is unwanted, i.e. we could close this issue.
