### ISSUE TITLE
Unused non-workspace header files get parsed if their name matches a used header

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4048]
Our parsing code isn't capable of identifying the correct file to parse (i.e. it doesn't have the IntelliSense includePath available) -- this can cause the browse database to be unnecessarily large and parse header files outside of the workspace that it doesn't really need to.

Previously were incorrect skipping parsing of headers until the files were open and/or parsing the wrong files -- we needed to make this change in order to give accurate Find All References results in headers.

**Comment by bobbrow** [comment]
Not a lot of feedback on this.  Closing...
