### ISSUE TITLE
References may not be confirmed in headers if they are inactive in the TU that is used for confirming

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4049]
Not sure how important this is to deal with since it doesn't seem like it would be a commonly hit scenario and we use various heuristics for choosing the ideal TU...fixing this would negatively impact performance...maybe we could add a setting to enable this if enough people want it.

**Comment by bobbrow** [comment]
Not a lot of feedback on this.  Closing...
