### ISSUE TITLE
debug C++ file, exe not found, windows

### ISSUE THREAD

**Issue by Mugiwara303** [microsoft/vscode-cpptools#405]
i have created a main.cpp file with a simple hello world message, but i can't compile it or debug it! it said main.exe not found, i know there is no main.exe file on the project folder i tried main.cpp but it's not working too, please help me i have tried everything but still no luck, thank you

tasks.json
`{
    "version": "0.1.0",
    "command": "g++",
    "isShellCommand": true,
    // compiles and links with debugger information
    "args": ["-g", "-o", "main.exe", "main.cpp"],
    // without debugger information
    //"args": ["-o", "hello.exe", "hello.cpp"],
    "showOutput": "always"
}`

launch.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (Windows)",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/main.exe",
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\CodeBlocks\\MinGW\\bin\\gdb.exe",
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "externalConsole": false,
            "visualizerFile": "${workspaceRoot}/my.natvis"
        },
        {
            "name": "C++ Attach (Windows)",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command.pickProcess}" 
        }
    ]
}`

**Comment by pieandcakes** [comment]
@Mugiwara303 for the command in your tasks.json, can you specify the fill path to your g++ executable? I'm wondering if it isn't able to find it. 

Can you also look at the `debug console` window and see if the compiler output is showing?

**Comment by Mugiwara303** [comment]
@pieandcakes  i have changed this but no luck "command": "C:\\CodeBlocks\\MinGW\\bin\\g++.exe",
in my folder project there is only main.cpp file, there is no main.exe and when debugging it fail because there is no main.exe, look at the images, thank you :)
![11](https://cloud.githubusercontent.com/assets/24526558/21117190/91876398-c0b0-11e6-94e2-c163a5655923.jpg)
![22](https://cloud.githubusercontent.com/assets/24526558/21117191/919c09e2-c0b0-11e6-8ec1-ad0f060b5c97.jpg)

**Comment by pieandcakes** [comment]
@Mugiwara303 Can you manually compile it with the parameters from a command prompt?

**Comment by Mugiwara303** [comment]
@pieandcakes i am sorry i don't know how to do it, i am a beginner with programming, and i am currently using code blocks, and i can't compile on VSCode

**Comment by pieandcakes** [comment]
Open a Windows command prompt to the folder where your source code is. Then using the path to your G++, type `g++ -g main.cpp -o main.exe`

**Comment by Mugiwara303** [comment]
@pieandcakes i don't know if i did it right but it gives me an error libintl-8.dll is missing 
![2016-12-12_213533](https://cloud.githubusercontent.com/assets/24526558/21117833/41a99afa-c0b3-11e6-88db-191396e801bc.jpg)

**Comment by pieandcakes** [comment]
@Mugiwara303 You may want to search the internet or see if you can get help with CodeBlocks. Looks like there is a problem with your installation?

**Comment by Mugiwara303** [comment]
@pieandcakes code blocks is running fine and is compiling without errors, and also is not installed on program files to avoid problems

**Comment by pieandcakes** [comment]
@Mugiwara303 The MinGW G++ compilation is giving you an error which is telling me that there is an issue with the MinGW installation on your machine. Command line compilation tools are not part of this extension. I can give you help with the debugger, but the error you screenshotted is showing me that you can't run the `g++` command without an error.

**Comment by Mugiwara303** [comment]
@pieandcakes ok thank you for your time :) i will look for a fix to my problem, as long as my VSCode configuration is correct i have to fix mingw problem

**Comment by pieandcakes** [comment]
@Mugiwara303 Just to give you some context, our extension provides language services which helps when you are writing code and the debugger, which is debugging. The compile `task.json` file is part of VS Code and its just a tool to call a command line executable to compile your code. For my day-to-day tasks, I usually end up leaving a Windows command line window open to compile from. 

It looks like for this error you are missing some libraries. It might be easier for you to download MinGW on its own and make sure you install gcc and gdb for both x86 and x64 to get you started.

**Comment by Mugiwara303** [comment]
@pieandcakes i have fixed the problem by adding the missing dlls to system32! and now i can create exe from the cmd, so i deleted the exe and tried from VScode but it still give me the same error, main.exe not found

**Comment by pieandcakes** [comment]
where is the exe you created from the cmd? is it in the location you specified in `program`  in your `launch.json` ?

**Comment by Mugiwara303** [comment]
yes near main.cpp "program": "${workspaceRoot}/main.exe",

**Comment by pieandcakes** [comment]
@Mugiwara303 and what error do you see now?

**Comment by Mugiwara303** [comment]
just like before, main.exe not found, but when i create the main.exe with cmd and then debug from vscode it works and it gives me hello world on the debug console

**Comment by pieandcakes** [comment]
Ok. So your problem is with the `task.json` compiling your code? If so, you may want to seek help with VS Code's `task.json` file. You can read more [here](https://code.visualstudio.com/Docs/editor/tasks) or reach the VS Code issue page [here](https://github.com/Microsoft/vscode/issues).

**Comment by Mugiwara303** [comment]
yes VSCode cannot compile and build the exe from cpp file, i will try on the links you provide me, thank you for your time and help

**Comment by Mugiwara303** [comment]
@pieandcakes i have tried ctrl+shift+p then tasks:run task then i selected C:\\CodeBlocks\\MinGW\\bin\\g++.exe hit enter and it worked! but it takes a lot of time to do all this instead of clicking the debug button, i found the shortcut ctrl+shift+b

**Comment by pieandcakes** [comment]
@Mugiwara303 Look at making the task a build task and adding it to the `launch.json`. It should be part of the first article. Then it will run that task every time you start debugging

**Comment by Mugiwara303** [comment]
@pieandcakes can you guide me where to look to do this, it confuses me

**Comment by pieandcakes** [comment]
If you follow the section `command and tasks[]` you can name your task in the `task.json` and you can add `"isBuildCommand": true,` OR you can specify a `preLaunchTask` in your `launch.json` where you can put the name of the task you created and it will be called before it launches.

**Comment by pieandcakes** [comment]
@Mugiwara303 If you need more help with tasks, I would suggest asking over in the VS Code issues page.

**Comment by Mugiwara303** [comment]
@pieandcakes i have added `"preLaunchTask": "C:\\CodeBlocks\\MinGW\\bin\\g++.exe"` and it works, so this problem is fixed, thank you

**Comment by RohitAthithya** [comment]
I had a similar issue, taking a close look at the command it was executing, it called the gcc instead of g++.
I just had to provide the proper path and it did the job.
