### ISSUE TITLE
Links in "C/C++: References" do not render in some cases (non-workspace files, files with spaces, etc.)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4050]
The root issue is caused by VS Code -- upvote or add complaints to https://github.com/microsoft/vscode/issues/34026 .

We could also show the data in some better UI tree view -- we're waiting for VS to provide something better...not sure yet if we'll need to do the work ourselves. See https://github.com/microsoft/vscode/issues/74237 .

**Comment by bobbrow** [comment]
Not a lot of feedback on this. Closing...
