### ISSUE TITLE
"Cancel" for Find All References can take "too long" when it's in the "Processing source" state

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4052]
The reason "Cancel" gets "stuck" is that it is doing the normal "IntelliSense operation" code without a separate "cancel" thread that can kill the IntelliSense process (which is what enables faster canceling when it's in the "confirming" state). It should be fixable...not sure if it's worth the effort though.

**Comment by bobbrow** [comment]
Not seeing a lot of feedback on this.  Closing...

**Comment by sean-mcmanus** [comment]
I'm seeing this happen when confirming references too (repros with call hierarchy too).
