### ISSUE TITLE
clang-format broken unless you stick to a single file

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#4054]
Before the change described in #3937, clang-format worked (mostly) flawlessly for me with format-on-save and manual formatting.

Now however, even after making the regressive settings changes required by the #3937 change, my clang-format works only so long as I stick to editing one file. As soon as I change to a second file it won't work again until I restart the application (even if I return to the original file). So long as I stick to the original file it works fine (whether invoked manually or with format-on-save). Thereafter, nothing.

Nothing appears in the Output window.

I get developer console errors that look like this:
```
console.ts:137 [Extension Host]% Object
t.log @ console.ts:137
```

- OS and Version: Ubuntu Linux 18.04
- VS Code Version: 1.37.0
- C/C++ Extension Version: 0.24.1

**Comment by sean-mcmanus** [comment]
I'm not reproing the bug (with 0.25.0-insiders). Do you see any errors when you change the C_Cpp.loggingLevel to Debug?

What is the "regressive settings changes" you are referring to?

**Comment by ghost** [comment]
The "regressive settings changes" I'm referring to are those necessitated by changing the `clang_format_path` to machine scoped (meaning I can't set it in my `.code-workspace` file, where it belongs for my project and am forced to set it in my user settings and manually edit that every time I change to a project that needs a different `clang-format` version). I made the connection here only because these are two changes to clang-format that, for me at least, appeared simultaneously.

I've tried changing the logging level, which gives no further output.

It may be relevant that I'm working with a very large multi-root-directory workspace.

Sometimes (though this is the exception, not the rule) I repeatedly get `WARN Aborted format on save after 750ms` in the developer console. But once it has stopped working entirely, there are no new console messages at all either. This suggests to me there might be something stateful in the invocation of clang-format which can find itself in an invalid state altogether until restart.

**Comment by ghost** [comment]
Having upgraded to 0.25.0-insiders, the developer console errors I posted originally now look like this: 
```
/snap/code/12/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host]% Object
t.log @ /snap/code/12/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242
```

**Comment by sean-mcmanus** [comment]
The developer console errors are not useful. Could you check the C/C++ error logs? See https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md .

**Comment by ghost** [comment]
Well now I'm getting 
```
Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at /home/john-mark/.vscode/extensions/ms-vscode.cpptools-0.25.0-insiders2/bin/Microsoft.VSCode.CPP.Extension.linux
```
which means I can't even enable the C/Cpp tools error logs.

VScode version 1.37.1

**Comment by sean-mcmanus** [comment]
@johnmarkwayve Look like there was a problem installing the binary. Can you try doing a clean install of the extension? The .vsix has the binary in it so either it was deleted or there was some failure during the download/install process. You could also try changing the C_Cpp.updateChannel to "Default" to get the non-Insiders version.

**Comment by MikeWeller** [comment]
Sounds similar to https://github.com/Microsoft/vscode-cpptools/issues/3145 though there could be multiple issues at play.

**Comment by bobbrow** [comment]
Closing this issue as we do not have enough information to make further progress on it.  We reverted the scoping for the clang format path which should address the machine scoping issue.  Please retry your scenario with the latest version of the extension and let us know if you continue to have issues.

Thanks!
