### ISSUE TITLE
The terminal shell path "platformio" does not exist

### ISSUE THREAD

**Issue by skypuppy** [microsoft/vscode-cpptools#4055]
Type: General
VSC with platformio was working, sort of, until I let VSC update itself.  Now, I get the "platformio" does not exist error, making the entire effort useless.  Exhaustive web search does not yield any solution.  Help, please.

**Please review existing issues and our documentation at https://github.com/Microsoft/vscode-cpptools/tree/master/Documentation prior to filing an issue.**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by pieandcakes** [comment]
@skypuppy Please report this either at `platformio`'s repository or [VS Code's](https://github.com/microsoft/vscode/issues). This is the C++ extension's repository and not `platformio`
