### ISSUE TITLE
heap corruption since 0.23

### ISSUE THREAD

**Issue by qian2501** [microsoft/vscode-cpptools#4064]
OS and Version: Window7 Pro
VS Code Version: 1.37
C/C++ Extension Version: 0.23-0.24.1

Recently after I updated the extension, I keep getting a crash says “Critical error at c0000374”, which is a heap corruption. But it never happens when using 0.21, with same code version, nor debugging same program with vs2012.
The first time I run into this situation was when I updated from 0.21 to 0.23.
I wonder if there is some improvement on debugging or something goes wrong.

**Comment by pieandcakes** [comment]
@qian2501 Can you explain what you are doing when you get that Critical error and what process/executable is giving that error? 

Does 0.24.0 have the same error? Can you provide a code sample that reproduces this?

**Comment by qian2501** [comment]
Well, here is where things gets awkward, I don’t have permission to the codes triggers this error.
So I think maybe it is possible to compare between this two versions and check what exactly changed. If we do have more exceptions  covered then I can report a problem in theirs code(we have a really low efficiency workflow, isn’t it).

**Comment by pieandcakes** [comment]
@qian2501 If this is debugging, the only change is to correct child process debugging: https://github.com/microsoft/MIEngine/commit/f04de41a05877bc177e8959f8ebcfcdd82aae9cf which does not look like it affects anything to cause it to give a heap corruption.

**Comment by Colengms** [comment]
Hi @qian2501 .  Are you still seeing this issue?

Is heap corruption occurring in the extension process, or is it occurring in the process you are debugging?

**Comment by qian2501** [comment]
Sorry, I should have closed this issue, we couldn't find anything useful yet, but we don't observe this issue on other main branches, so I think this is supposed to be our fault.
