### ISSUE TITLE
New IntelliSense coloring occasionally treating operators as functions

### ISSUE THREAD

**Issue by arminAnderson** [microsoft/vscode-cpptools#4071]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10, Version	10.0.18362 Build 18362
- VS Code Version: 1.37.0
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them): NA

- IntelliSense colors operators when using "entity.name.function" or "entity.name.function.template"

**To Reproduce**

1. Add "entity.name.function" or "entity.name.function.template" to the color theme json
2. Type std::cout << "hello" << std::endl;
3. Bitwise operators, and 'endl' are now the same color as functions

**Expected behavior**

They would not be covered under the function color coding.
Overridden operators also will now stay color changed as well, which should be up to the user.
Sometimes other operators are color changed but so far only the bitwise shifting operators change every time, and brackets depending on the situation (usually when using arrays)

**Screenshots**

Before:
![image](https://user-images.githubusercontent.com/11141835/62914624-e2625900-bd45-11e9-9a73-278318b11053.png)

After:
![image](https://user-images.githubusercontent.com/11141835/62914641-fa39dd00-bd45-11e9-903f-75b1d7535d7f.png)

These bracket operators also always change:
![image](https://user-images.githubusercontent.com/11141835/62914963-813b8500-bd47-11e9-902b-05d1eabd1b92.png)

**Comment by Colengms** [comment]
Hi @arminAnderson .  It's currently by-design that overloaded operators fall back to the color for functions if more specific colors are not assigned to their scopes.  You can independently color the overloaded operators using the following scopes:

|Token|Scope|
|---|---|
|Operator Overload Function | entity.name.function.operator| 
|Operator Overload Member | entity.name.function.operator.member|

If we were to change this behavior, it would require changing the scope name (which cascades, i.e. from entity.name.function.operator to entity.name.function if no color is associated with entity.name.function.operator).  We'd like to avoid making changes to scope names for semantic tokens if not absolutely necessary, as it breaks themes that have started using them.

Note that the Inspect TM Scopes command will reflect the syntactic color applied by VS Code (TextMate), and does not reflect the color applied on top of that by semantic colorization in the C/C++ extension.

**Comment by arminAnderson** [comment]
Hi @Colengms. I was aware of those tokens, but for some reason I was having trouble getting them to 'prioritize' them over the function coloring. I was under the impression that the theme is prioritized top to bottom, but it might be the way my theme json is set up so I'll take a look.

**Comment by arminAnderson** [comment]
It appears that TextMate rules prioritize from top to bottom, but that does not appear to be the case for the semantic colorization. Not sure if there is some internal hierarchy for those

**Comment by Colengms** [comment]
Hi @arminAnderson .  You can elaborate on what you mean by prioritizing from top to bottom?  My understanding is that TM styles should be applied based on scopes, in a cascading manner similar to CSS.  Style for entity.name.function.operation are applied atop of entity.name.function, which is applied atop of entity.name, etc..

**Comment by arminAnderson** [comment]
Hey @Colengms, I meant that the textmate rules seem to always be considered second when the semantic colorization is enabled. 

For example:
* ScopeA is supposed to colored blue (Intellisense scope)
* ScopeA.B is supposed to be colored green (TM scope)

There doesn't seem to be anything I can do about getting the semantic colorization to not be prioritized. In this case, even though ScopeA.B is defined specifically, and atop ScopeA, it'll still be blue. 

I have every scope that semantic colorization covers (at least from the docs), but there's been a couple times where I'd prefer to use the TM scopes instead of the intellisense ones. Not sure if that's by design to ignore the TM scopes entirely or if that's unintentional

**Comment by Colengms** [comment]
Hi @arminAnderson .  Unfortunately, this is currently by-design.  TextMate colorization is effectively the first pass, and C/C++ semantic colorization is applied on top of that.  Neither pass is aware of the results of the other.  We are working with the core VS Code team on a more comprehensive API for semantic colorization.  Our current implementation of semantic colorization in the C/C++ Extension is a best-effort with the currently available APIs (applying text decorations in the editor, and scanning themes and settings directly).
