### ISSUE TITLE
VSCode cannot find file for "compileCommands"

### ISSUE THREAD

**Issue by goldrus** [microsoft/vscode-cpptools#4072]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I'm using Remote SSH to edit and run code on a server with Ubuntu xenial. I've tried to set compileComands field in c_cpp_propertis.json, but it always says ```Cannot find "/home/akhruslan/arcadia/compile_commands.json".```
I'm sure that the file exists and contains a valid json
Reloading VSCode doesn't help the problem.

```c_cpp_properties.json``` looks like this:
```(json)
{
    "configurations": [
        {
            "name": "Linux",
            "compileCommands": "${workspaceFolder}/compile_commands.json",
            "includePath": [
                "/usr/include/x86_64-linux-gnu",
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang++",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "browse": {
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
```

**Expected behavior**
Extension can find the file and autocomplete works fine

**Comment by sean-mcmanus** [comment]
Is this with version 0.24.1 or 0.25.0-insiders?

The "Cannot find" message is from our call to fs.existsSync -- maybe that's getting executed on the local host instead of the remote? Can you tell if the compile_commands.json is being used, such as via C/C++: Log Diagnostics? From your comment about autocomplete not working it sounds like it's not being used.
