### ISSUE TITLE
Uses too much RAM

### ISSUE THREAD

**Issue by shawnl** [microsoft/vscode-cpptools#4076]
My source code is only 13MB https://github.com/ziglang/zig , and yet Intellisense easily uses 3GB+ to analyze it. There should be an upper bound of RAM usage relative to the size of the code base and the size of the applicable headers in /usr/include.

CPUs | Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 x 2216)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: disabled_softwareskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: unavailable_offviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 2, 3, 2
Memory (System) | 3.70GB (1.33GB free)
Process Argv | --unity-launch
Screen Reader | no
VM | 0%

CPU %	Mem MB	   PID	Process
    1	    53	  3547	code main
    0	     4	  3550	   zygote
    0	   197	  3615	     window (ir.cpp - Visual Studio Code)
    0	    83	  3728	       extensionHost
    0	    61	  3805	         clangd
    0	    30	  3775	     shared-process
    0	     0	 17217	       /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 17218	         /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    2	    83	 17195	     window (Notificador de problemas)
    0	    45	  3591	   gpu-process

**Comment by sean-mcmanus** [comment]
13 MB is very large for a source file (I guess that is for all the source code?). The IntelliSense process has to store data for the entire translation unit, which could include lots of header files. 3 GB is not the normal size though, unless you have a really large TU or there is a bug.

**Comment by shawnl** [comment]
While I agree there is a bug, I don't feel this report really helps at all, I just got frustrated :(

**Comment by bobbrow** [comment]
Are you referring to the total size of your repo, or just a single source file?
Which language service binary is using 3GB?  `Microsoft.VSCode.CPP.Extension.linux` or `Microsoft.VSCode.CPP.IntelliSense.Msvc.linux`?

**Comment by YiweiJiang2015** [comment]
Consider using jedi extension as the intellisense engine instead of the default one. This will make big difference.
![Capture](https://user-images.githubusercontent.com/36023486/64616001-e385b500-d3db-11e9-82c2-bec32b0a9b8f.JPG)

**Comment by YiweiJiang2015** [comment]
Consider using another Intellisense engine.

**Comment by bobbrow** [comment]
We'll be addressing this with #4119
