### ISSUE TITLE
Find All References doesn't find references to function overrides in derived classes

### ISSUE THREAD

**Issue by rajabala** [microsoft/vscode-cpptools#4078]
If I use 'FindAllReferences' on the (pure) virtual Sync below, I don't get references to the usage in the derived classes. Make it virtual (i.e., not pure) doesn't help either.
It's really helpful to _find all references to overrides of a base class method_, and I'm not sure if FindAllReferences is the tool for this or not. If this is possible in vscode today, I'd love to know how!

```
#include <iostream>
#include <memory>
using namespace std;

class Task {
public:
    virtual void Sync() = 0;
};
class FooTask : public Task {
    void Sync() override {
        cout << "Foo:Sync" << endl;
    }
};
class BarTask : public Task {
    void Sync() override {
        cout << "Bar:Sync" << endl;
    }
};

int main()
{
    typedef std::shared_ptr<class Task> TaskSharedPtr;

    TaskSharedPtr tasks[2] = {make_shared<FooTask>(), make_shared<BarTask>()};
    tasks[0]->Sync();
    tasks[1]->Sync();

    return 0;
}

```

![image](https://user-images.githubusercontent.com/530244/62976618-dcb25500-bdd1-11e9-9438-acf002de480f.png)

- OS and Version: RHEL 3.10.0-957.21.3.el7.x86_64
- VS Code Version: 1.34.0
- C/C++ Extension Version: 0.25.0-insiders

**Comment by sean-mcmanus** [comment]
The references are shown as "Not a Reference" in the C/C++: References output. The reason is that the type of Task::Sync is considered different from FooTask::Sync and BarTask::Sync. We might be able to change the "Not a Reference" to something like more informative like "Override Reference" (and "Overload Reference" for the overload case which is also treated the same way currently).

VS behaves the same way if Sync is given a definition, and if there's no definition it oddly isn't showing the "Sync() = 0" as a reference. In the VS Case, the UI has a column for showing and grouping references based on the derived class.

![image](https://user-images.githubusercontent.com/19859882/62980081-649c5d00-bdda-11e9-8094-20c7697a6fba.png)

**Comment by rajabala** [comment]
Thanks @sean-mcmanus! I gather that there isn't currently a way to get to all the derived references of a symbol, correct? Should I file another issue for that, or would this be repurposed for it?

**Comment by sean-mcmanus** [comment]
Well, it finds the derived references, but it's just marking them as "Not a Reference". You don't need to create a new issue.

There's also an issue on "Go to Implementation" to find al the derived class of a base type: https://github.com/microsoft/vscode-cpptools/issues/3941 .

**Comment by rajabala** [comment]
Ah, gotcha. Thanks!

**Comment by lumonix** [comment]
It would be super helpful if “Find all references” could be configured so it also displays the derived versions. 

Our code base is very large and complex and we often have function names such as “Sync” that are used by many different classes that are not all the same “Sync” derived from the same base-class Sync. 

Having them all listed as “Not a reference” is not so helpful as you still have to visit each line in the code manually. 

If they can be configured to be uniquely identifiable in either the output window or even better show in the results it would be incredibly helpful to navigate our code base.  

Thanks for the find all references implementation @sean-mcmanus. Its a super promising feature!

**Comment by sean-mcmanus** [comment]
The root issue is that we're not running the Find All References using all the possible definitions (only the 1st), so the same bug could possibly happen in other cases where there could be multiple definitions for a particular identifier. So this is definitely something we want to fix, but VS Code's UI doesn't expose the concept of multiple definitions for references (even though it does expose that for Go to Def, which is inconsisent), so we might need to implement our own tree view container (or just group all the definitions together).

UPDATE: FYI, VS has the same bug whenever the base class has a definition. Our extension is just missing the results when the source of the find all references is missing a definition. I'm investigating if there's a way to fix this in the short term.

UPDATE: It's fixed (pending release)...still working on further test stuff.

**Comment by lumonix** [comment]
Thanks for the update Sean.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders . Let us know if it's not working for you.

**Comment by rajabala** [comment]
Thanks! Just checked and it does work. However, rename symbol doesn't. I'll file another ticket for that :)

**Comment by sean-mcmanus** [comment]
@rajabala Rename Symbol should give the same results as Find All References (the backend implementation is shared). I'm not able to repro this bug with Rename. Did you file a bug or do you have more repro info?

**Comment by iiropeltokangas** [comment]
I would also find it very helpful to find all base class references when using "Find All References" on a derived class' function, i.e.  the OP's example, when using the feature on BarTask::Sync, I would like to see all references to Task::Sync as well.

**Comment by sean-mcmanus** [comment]
@iiropeltokangas That's how it should behave with 0.26.0-insiders2. Let us know if you're not seeing that.
