### ISSUE TITLE
Move C/C++ References to a Tree Views in the References view container

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4079]
i.e. https://code.visualstudio.com/api/extension-guides/tree-view#tree-view -- the docs don't say it works with the References view container, but it does.

```
  "contributes": {
    "views": {
      "references-view": [
        {
          "id": "commentReferences",
          "name": "Comment References"
        },
        ...
      ]
    },
   ...
```

Also need to register and implement the tree data provider, e.g. `vscode.window.registerTreeDataProvider('commentReferences', new CommentReferencesProvider());`.

**Comment by michelleangela** [comment]
VS Code Reference view container
https://github.com/microsoft/vscode-references-view
