### ISSUE TITLE
Go to definition/Peek definition does not work on non standard file extensions.

### ISSUE THREAD

**Issue by Seg0r** [microsoft/vscode-cpptools#408]
Mentioned functionality does not work when function definition is stored in file with non standard extensions. Here is simple sample:
https://github.com/Seg0r/vscode-cpp_bug_sample
Using "Got to definition" option opens header file instead of lib.sqc.
Configuration of file association:
`"files.associations": {
        "*.sqc": "c"
},`
does not help. 
As mentioned in [#97](https://github.com/Microsoft/vscode-cpptools/issues/97) problem should be solved with 0.10.0 release, however only versions 0.9.1, 0.9.2, 0.9.3 were released since then. Any chance to fix this problem in next version?

**Comment by sean-mcmanus** [comment]
Yes, I'm able to repro the bug. Go To Definition doesn't work for files with non-standard file types, even after they're changed to be C++ files. We'll look into fixing this later. Thanks for reporting this.

**Comment by sean-mcmanus** [comment]
Can you try 0.10.3? It should be fixed now.
