### ISSUE TITLE
[WSL] Unable to start debugging (C/C++)

### ISSUE THREAD

**Issue by cruzeflute** [microsoft/vscode-cpptools#4082]
- VSCode Version: 1.37

- OS Version: Windows 10 - 1803 with WSL

- Extensions (Up-to-date): Remote - WSL, C/C++, C++ Intellisense, CMake. 

Start any project, add some easy code, and compile (tasks:Run Build Task).
Begin debugging with the launch.json from https://code.visualstudio.com/docs/cpp/config-wsl.
There will then be a pop-up like the one below:
![vscodeerror](https://user-images.githubusercontent.com/4276563/63012111-3b53fd80-bebc-11e9-8d85-916cf612f2ed.png)
Below is my jsons:
![vscodeerror1](https://user-images.githubusercontent.com/4276563/63012192-65a5bb00-bebc-11e9-8fb9-fe68484e7193.png)
![vscodeerror2](https://user-images.githubusercontent.com/4276563/63012194-663e5180-bebc-11e9-9d85-320022ca6ff5.png)
![vscodeerror3](https://user-images.githubusercontent.com/4276563/63012196-663e5180-bebc-11e9-9ade-00ab25d13875.png)
![vscodeerror4](https://user-images.githubusercontent.com/4276563/63012197-66d6e800-bebc-11e9-99d4-463829b8070b.png)

Is there something wrong?

**Comment by pieandcakes** [comment]
@cruzeflute Do you have C:\Windows\System32\Bash.exe ? Also, you probably need to replace `System32` with `Sysnative` because the debug adapter runs as a 32bit process, it needs the special folder name to resolve to the 64bit folder.

**Comment by colonyevan** [comment]
I have an identical launch.json as the above (with the sysnative change), have double-checked that I have bash in my System32 file and am having this problem.

**Comment by cruzeflute** [comment]
> @cruzeflute Do you have C:\Windows\System32\Bash.exe ? Also, you probably need to replace `System32` with `Sysnative` because the debug adapter runs as a 32bit process, it needs the special folder name to resolve to the 64bit folder.

I try again.All step follow https://code.visualstudio.com/docs/cpp/config-wsl
And the error still exist:
![vscodeerror5](https://user-images.githubusercontent.com/4276563/63071492-101bed80-bf52-11e9-926e-8e30a5f894a3.png)

![vscodeerror6](https://user-images.githubusercontent.com/4276563/63071787-43ab4780-bf53-11e9-99f4-eafd5376cc9e.png)

**Comment by pieandcakes** [comment]
So i noticed you are using the VS Code `Remote-WSL` extension. If you are, then you don't need the `pipeTransport` blob. The remote extension runs all of the commands natively in bash already. 

The `pipeTransport` blob is only needed if you don't have the `Remote-WSL` extension installed/active.

**Comment by pieandcakes** [comment]
@colonyevan Can you verify if you are also using the `Remote-WSL` extension from VS Code? If so, see the comment [above](https://github.com/microsoft/vscode-cpptools/issues/4082#issuecomment-521709092)

**Comment by cruzeflute** [comment]
> So i noticed you are using the VS Code `Remote-WSL` extension. If you are, then you don't need the `pipeTransport` blob. The remote extension runs all of the commands natively in bash already.
> 
> The `pipeTransport` blob is only needed if you don't have the `Remote-WSL` extension installed/active.

I delete the pipeTransport, it doesn't work.
I try to delete all json,create them by default.Now it works.
Thank you for your help.
