### ISSUE TITLE
Default argument issue

### ISSUE THREAD

**Issue by rei-vilo** [microsoft/vscode-cpptools#4084]
**Type: LanguageService**

Calling a function with a default argument and not providing that specific argument raises an error.

**Describe the bug**
- OS and Version: macOS 10.14.6
- VS Code Version: 1.37.0
- C/C++ Extension Version: 0.25.0-insiders
- All other extensions have been disabled.

**To Reproduce**
1. Define a function with a default argument
2. Call that function without providing that specific argument

**Expected behavior**

No error message should be displayed as the default argument is already defined.

**Screenshots**

<img width="1295" alt="Capture  2019-08-13 à 18 11 13" src="https://user-images.githubusercontent.com/951776/63025860-5f0e4800-beaa-11e9-9692-1ac9779a329d.png">

**Additional context**

Thank you.

**Comment by Colengms** [comment]
Hi @rei-vilo .  I assume your .ino file is being treated as a C++ file.

I'm not able to repro this with a simple case, such as:
```
#include <cinttypes>
using namespace std;

void foo(uint8_t a, uint8_t b, uint16_t c, bool z = false)
{
}

void bar()
{
	foo(1, 2, 3);
}
```

Does the above code repro for you?  If not, there would seem to be more going on here.  Can you distill your repo to something you can send us?

**Comment by rei-vilo** [comment]
Thank you for your answer. `ino` files are associated as `cpp` files.

```
    "files.associations": {
        "*.ino": "cpp"
    },
```

Indeed, both the examples provided and shown below work fine. 

```
int b = 0;

void test(int var = 1)
{
    b += a;
}

void loop()
{
    test();
    delay(1000);
}
```

Is there a way to force re-indexing the functions for Intellisense and Intellicode?

**Comment by sean-mcmanus** [comment]
Can you do a Reload Window?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
