### ISSUE TITLE
Super slow include path parsing

### ISSUE THREAD

**Issue by markypizz** [microsoft/vscode-cpptools#4087]
Hi guys. I know this is going to be super vague but it's an issue I've been dealing with with this extension for as long as I've used it. I work in a very large codebase, 1500-2000+ files with very varying include paths. Some of them are from the root directory, some up to 7 or so folders down. For the sake of keeping our codebase private, I'll give an example of my issue.

The main folder I work in, let's call proj_root/A requires many dependencies from proj_root/B. The include paths for these are relative to proj_root:

#include <B/stuff/file.H>

So I need to use proj_root as one of my includePaths, in addition to 15-20 others I have there which work fine. As soon as I add "${workspaceFolder}/../" (A up to proj_root), the extension slows to an absolute snails pace and can sometimes take 5+ hours to index what previously took about 15 seconds, though most of the time I'm not convinced it's doing anything at all, and I believe it crashes the majority of the time. (though no output/feedback to vscode whatsoever) It's worth noting that 80% of the code of our repository is in proj_root/A. I already have include paths set for proj_root/A/** and a few others and I am seeing no issues. proj_root/B has significantly fewer files. So I don't think this is a case of too many files to parse, right? I do not have the proj_root include as recursive.

Now within proj_root itself there's .git/ a few shell scripts, and some other dirs C, D, which trickle down to obj and executable files, and some XML parsers, etc. None of these files are directly in proj_root.

I don't know enough about how to get some more meaningful logs for you guys... Can anyone lend a hand and either point me in the right direction or tell me how to get some logs? With debug output on in the extension, I get no output. 

Here's some info VSCode brought along:

- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `0.25.0-insiders`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.37.0`

{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 23,
		"activateCallTime": 2,
		"activateResolvedTime": 13,
		"activationEvent": "workspaceContains:/.vscode/c_cpp_properties.json"
	},
	"runtimeErrors": []
}
```

Thank you all for your amazing work writing this great extension!!

**Comment by sean-mcmanus** [comment]
Can you enable debug logging and check the logs to see what processing is being done? https://code.visualstudio.com/docs/cpp/enable-logging-cpp .

With 0.25.0-insiders we had to do more parsing of include files in order to get correct Find All References results for headers.

If you see files in folders being parsed that should not be, you should add those folders to files.exclude -- the glob pattern should match folders and not files and you should try to minimize the number of glob patterns (due to performance).

**Comment by markypizz** [comment]
Sure. Forgot to include that info. I should mention that I've been seeing this issue long before 0.25.0-insiders. This is what occurs when I add the path, and then enable the plugin. I have changed the paths for the privacy of our repo:

```initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
Autocomplete is enabled.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/proj_root/output/**
Search exclude: **/proj_root/sub_module_repo/**
Search exclude: **/proj_root/system/**
Search exclude: **/proj_root/tools/**
Search exclude: **/.vscode
cpptools/queryCompilerDefaults: 1
Attempting to get defaults from compiler found on the machine: '/usr/local/bin/gcc-8'
terminating child process: 75567
Attempting to get defaults from compiler found on the machine: '/usr/local/bin/gcc-8'
terminating child process: 75569
cpptools/didChangeFolderSettings
Attempting to get defaults from compiler in "compilerPath" property: '/usr/local/bin/g++-8'
terminating child process: 75571
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: '/usr/local/bin/g++-8'
terminating child process: 75573|

```


And that's it. Without the path included, it gets through the whole process as normal. I know there should be all the files and folders being parsed after this, but it doesn't seem to ever get there. I can't find any evidence of the plugin being responsive from this point forward.

**Comment by sean-mcmanus** [comment]
I suspect you are hitting https://github.com/microsoft/vscode-cpptools/issues/3123 . You could verify this by attaching a debugger and checking the non-idle call stacks for something like "enumerate_files". Our code tries to iterate over all the files under the includePath/browse.path roots, even those files are not ever used in any way, and all progress will stop until that is finished. The only known workaround currently is to avoid adding paths with too many files under them.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
