### ISSUE TITLE
IntelliSense not working with __VA_OPT__

### ISSUE THREAD

**Issue by Bemteb** [microsoft/vscode-cpptools#4088]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux Mint 18.2
- VS Code Version: 1.37.0
- C/C++ Extension Version: 0.25.0
- Other extensions you installed (and if the issue persists after disabling them): austin.code-gnu-global; disabling it doesn't change anything
- A clear and concise description of what the bug is.

I get an error message when using `__VA_OPT__` in my program, as IntelliSense expects a closing bracket at the wrong place.
The exact error message is "expected a ')'".
Below are a minimal example of the problem and also my c_cpp_properties.json file.

```
#include <experimental/source_location>
#include <string>

template<typename... Args>
void make_error(const std::experimental::fundamentals_v2::source_location& location, std::string message, Args... args)
{
    // does some stuff to make a fancy error message, including location of the error

};

#define ERROR(msg, ...) make_error(std::experimental::fundamentals_v2::source_location::current(), msg __VA_OPT__(,) __VA_ARGS__)

int main()
{
    ERROR("This is an error without any arguments.");

    int i = 3;
    double j = 3.5;
    ERROR("This is an error telling us that i = % and j = %.",i,j);
}
```

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++20",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

If I replace `__VA_OPT__(,)` by just a `,` the problem no longer occurs. But in this case, the first of the two error messages is wrong of course, both in vs code and when compiling, as it then misses arguments.

**Comment by sean-mcmanus** [comment]
The only released compiler I can find that compiles that is gcc 8.1. `__VA_OPT__` is a new C++20 feature -- our next update of our parser is expected to support this. Our current C++20 support is a small subset.

0.25.0 doesn't have the fix for this -- the fix is available in an internal branch, but we don't feel it's ready to ship yet, because VS isn't shipping it until some issue with the cl.exe library headers is fixed first.

**Comment by plinnie** [comment]
GCC 9.2 also support this as part of the GNU C language. I'm using IntelliSense 0.28.1 and it does not seem to accept it.

I'm using VSCode 1.45.1 on Windows 10 with the remote SSH connection, working remotely on a CentOS 8.1 Linux system. 

`c_cpp_properties.json`:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/src/common",
                "${workspaceFolder}/src/std",
                "${workspaceFolder}/src/platform",
                "${workspaceFolder}/src/ministack",
                "${workspaceFolder}/src/app",
                "${workspaceFolder}/build/generated",
                "${workspaceFolder}/cfg",
                "${workspaceFolder}/../shared"
            ],
            "defines": [
                "CLBV2", "WHITERABBIT", "NET_SU_IP_FIX", "PV_META", "__VSCODE__"
            ],
            "compilerPath": "/home/vincent/local/lm32-elf-gcc-9.2.0/bin/lm32-elf-gcc",
            "cStandard": "c18",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
The cppStandard needs to be c++20. This issue appears fixed.
