### ISSUE TITLE
Please support semantic highlighting for Doxygen comments

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-cpptools#4089]
**Type: LanguageService**

By convention, Doxygen comments use [special comment signature](http://www.doxygen.nl/manual/docblocks.html) to indicate Doxygen comment blocks. IDE's like Qt Creator support these and both colorizes Doxygen comments in different color and provides additional syntax colorization for values in the comment:

![cpptools-doxygen](https://user-images.githubusercontent.com/37181601/63093190-1fa03400-bf5c-11e9-8b90-ec674af2e216.PNG)

This makes it very easy to distinguish normal comments from documentation, and is very easy to spot when you've accidentally created the wrong comment type. It would be good if VSCode supported that as well (generating these from function signature automatically would also be a bonus!).

This is similar to #658, but at issue here is not _display_ of comments, but rather _syntax highlighting and colorization_ for C/C++ Doxygen comments.

**Comment by HunterZ** [comment]
Note that a triple-slash `///` before each line is also commonly used to signal Doxygen comments.

**Comment by matter123** [comment]
@anatolyburakov @HunterZ I'm working on Doxygen comment syntax highlighting from the textmate grammar (non-semantic) side. Are you looking for something more comprehensive than the picture in the linked PR. https://github.com/jeff-hykin/cpp-textmate-grammar/pull/354#issuecomment-522101518. Supports both `/**` and `///` style documentation comments.

**Comment by anatolyburakov** [comment]
@matter123 yes it looks great. as long as it's possible to have it as a different color than normal comments, and have even rudimentary syntax highlighting within comments, i'll be quite happy!

**Comment by matter123** [comment]
@anatolyburakov @HunterZ with version v1.14.0 of the "Better C++ Syntax" extension, syntax highlighting for Doxygen commands inside documentation comments. 

@anatolyburakov You can distinguish documentation comments from normal comments, as documentation comments have the scope `comment.block.documentation.cpp`. Using the vscode setting "editor.tokenColorCustomizations" you can apply a separate color to those comments

Example: (settings.json)
```jsonc
{
//...
"editor.tokenColorCustomizations": {
  "textmateRules": [
    {
      "name": "doxygen",
      "scope": [ "source.cpp comment.block.documentation" ],
      "settings": {
        "foreground": "#BBBBBB",
      }
    }
  ]
},
//...
}
```
![Screenshot from 2019-08-26 22-58-15](https://user-images.githubusercontent.com/714007/63744722-0ac57980-c855-11e9-9a6e-74c0221d3f6a.png)

**Comment by sean-mcmanus** [comment]
Thanks. Sounds like we can close this issue.

**Comment by gb-esat** [comment]
Would it be possible to support variable highlighting for @param[in,out]? Thanks!

http://www.doxygen.nl/manual/commands.html#cmdparam 

![Untitled](https://user-images.githubusercontent.com/56022622/69000279-d207de80-0931-11ea-9a4e-1ed872717849.png)

**Comment by matter123** [comment]
@gb-esat Created https://github.com/jeff-hykin/cpp-textmate-grammar/issues/418 for that
