### ISSUE TITLE
Code formatter duplicates contents on save when in extension development host

### ISSUE THREAD

**Issue by matter123** [microsoft/vscode-cpptools#4091]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Mac OS 10.14.15
- VS Code Version: 1.38.0-insider (ba69d8dcccaebbfaa94906503728eb7c3e45b9c1)
- C/C++ Extension Version: 0.25.0-insiders
- Other extensions you installed (and if the issue persists after disabling them): Issue persists after disabling all other extensions
- A clear and concise description of what the bug is.

When saving a new file when in extenstion development host window, the code formatter duplicates the file.

**To Reproduce**

1. Open an extension development host window
2. Create a new file
3. Set language to C++
4. Copy the following contents
```
void
foo()
;
```
5. Save
6. Observe that the file contains
```
void foo();
void foo();
```

**Expected behavior**

File contains just `void foo();`
**Screenshots**

Before Save | After Save
------------|-----------
<img width="86" alt="Screen Shot 2019-08-15 at 11 43 52" src="https://user-images.githubusercontent.com/714007/63118101-098d7600-bf52-11e9-8b20-a8d29e1164a1.png"> | <img width="110" alt="Screen Shot 2019-08-15 at 11 43 59" src="https://user-images.githubusercontent.com/714007/63118116-10b48400-bf52-11e9-9d40-d71b49789141.png">

**Comment by sean-mcmanus** [comment]
Strange -- VS Code is sending us a didOpen and then sending us a didChange, which causes the file contents to get duplicated. I'll try filing a VS Code bug and see what they say.

https://github.com/microsoft/vscode/issues/79252

It's not really a formatting bug, but an internal documentation corruption that the formatting makes visible.

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.25.0.

**Comment by sean-mcmanus** [comment]
It wasn't actually fixed -- 0.25.1 should have the fix (when it's released).

**Comment by sean-mcmanus** [comment]
Should be fixed with 0.25.1 now.
