### ISSUE TITLE
IntelliSense error a value of type "Example *" cannot be assigned to an entity of type "Example *"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4092]
I'm having similar issues with structs declared within a class, same errors `a value of type "Example *" cannot be assigned to an entity of type "Example *"`, I searched for the error message on Github but only that issue came up as relevant.

Had stuff like:
![image](https://user-images.githubusercontent.com/1311555/63047019-73167180-becb-11e9-8662-60ad97b5f319.png)

However I closed VSCode and reopened the same file later, they didn't appear again.

_Originally posted by @Zylann in https://github.com/microsoft/vscode-cpptools/issues/3700#issuecomment-521369123_

**Comment by sean-mcmanus** [comment]
@Zylann I'm not able to repro this (with 0.25.0-insiders). Are you able to get a repro with some sample code?
 Can you provide more info about how your code is configured/compiled, such as from C/C++: Log diagnostics?

**Comment by bobbrow** [comment]
might be another manifestation of #3883

**Comment by Zylann** [comment]
I still have this problem from time to time. When it happens I close/reopen VSCode and the error goes away, then it comes back after some time of editing, about 5 to 10 minutes. Every time, it involves a struct defined within a class.

![image](https://user-images.githubusercontent.com/1311555/63884687-90206980-c9ce-11e9-87d9-54a691b95dc0.png)

I didn't change the struct while editing, though.

My project is a Godot Engine module. I usually have VSCode open at the root of the Godot repo, and the class I'm working on is at `modules/voxel/terrain/myclass.cpp`, next  to its header.
Here is what my config looks like:
```
        {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/*",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/um",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/shared",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/winrt",
                "${workspaceRoot}",
                "${workspaceRoot}/editor",
                "${workspaceRoot}/core",
                "${workspaceRoot}/core/math",
                "${workspaceRoot}/core/bind",
                "${workspaceRoot}/core/helper",
                "${workspaceRoot}/core/io",
                "${workspaceRoot}/core/os",
                "${workspaceRoot}/drivers",
                "${workspaceRoot}/platform/windows",
                "${workspaceRoot}/modules",
                "${workspaceRoot}/modules/gdnative/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "WINDOWS_ENABLED",
                "DEBUG_ENABLED",
                "TOOLS_ENABLED"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/*",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/um",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/ucrt",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/shared",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/winrt",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
```
Settings:
```
{
    "files.exclude": {
        "**/*.64.obj": true,
        "**/*.tools.obj": true,
        "**/*.o": true,
        "**/*.pyc": true
    },
    "files.associations": {
        "vector": "cpp"
    }
}
```

**Comment by Colengms** [comment]
The error message itself looks like an instance of: https://developercommunity.visualstudio.com/content/problem/714374/intellisense-error-unable-to-assign-type-to-own-ty.html

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
