### ISSUE TITLE
Stale Intellisense squiggles (reopening)

### ISSUE THREAD

**Issue by ncoghlan** [microsoft/vscode-cpptools#4094]
**Type: LanguageService**
Reopening #920 as requested on that issue, since I'm still seeing the problem with stale Intellisense squiggles reported there.

**Describe the bug**
- OS and Version: Windows 10 on host, Debian 9 in WSL
- VS Code Version: 1.36.1
- C/C++ Extension Version: 0.24.1 (on both host and inside WSL)
- Other extensions you installed (and if the issue persists after disabling them): Annotator, Ansible, Git History, Python, Snippets and Syntax Highlight for Gherkin (Cucumber), x509 parser (I haven't tried seeing what happens with them disabled, since this only happens sometimes, so failing to reproduce it wouldn't tell me much)

Inside a header file, Intellisense is reporting a call signature of "unique_ptr, bool, bool, double" for a function call that has the structure "method(ptr, boolValue, doubleValue)".

The method being called was edited in this session to add the new boolean optional parameter, and appears in the header file *after* the method that calls it.

**To Reproduce**
Not clear - as with #920, the plugin just sometimes gets into a state where it isn't correctly reparsing a file after it is changed.

**Expected behavior**
Editing and saving the header file triggers a full reparse of the file (or else there would be a way to explicitly force full reparsing).

**Additional context**

I'm not that bothered by the diff tracking getting confused sometimes - speed improvements are good, but caching is hard to get right.

I *am* bothered by the fact that there isn't a clear way to tell the plugin "Forget everything you think you know about this file, and reparse it from scratch" short of restarting VSCode (or disabling the plugin, reloading the UI, re-enabling the plugin, and then reloading the UI again).

**Comment by sean-mcmanus** [comment]
This might be the same as bug https://github.com/microsoft/vscode-cpptools/issues/3883 ?

You could also try 0.25.0-insiders2 (https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders2) -- that fixed some bugs with IntelliSense getting into a bad state after edits are made if there are lambda in a method.

We added a "Rescan Workspace" command that will restart the IntelliSense clients.

**Comment by ncoghlan** [comment]
The same root cause would definitely be plausible. The fact that disk IO in WSL is so astonishingly slow may also be giving the language server grief (I don't have anywhere near the same level of problems on my Linux laptop with local SSD access as I do running on the Windows machine through the WSL connection).

As a baseline, I triggered "Rescan Workspace" right after starting up, and it took 16 seconds. Next time I see this, I'll try that and see if it fixes the parsing problem, or if it looks like something has actually gone wrong with the client/language server comms.

**Comment by ncoghlan** [comment]
OK, I got it into a bad state again by editing a subclass implementation file to refer to a base class constructor that didn't exist yet, and a member variable that was still marked as private. After updating the base class header file, the squiggles remained in the subclass implementation file, and modifying and resaving it didn't remove them.

Running "Rescan Workspace" brought up the "Updating Intellisense" icon in the status bar, and it's been there for several minutes now.

Updated VSCode version info:

Version: 1.45.0 (system setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

C/C++ Intellisense plugin: 0.28.0

**Comment by ncoghlan** [comment]
Given enough time, it did eventually complete the "Rescan Workspace" operation (I was away from the computer for around an hour, and it had resynced by the time I got back)

**Comment by sean-mcmanus** [comment]
I'm not able to repro the issue by trying the steps indicated. Can you check your C/C++ logging for a "Failed to read" message that would indicate the IntelliSense process crash? (i.e. https://github.com/microsoft/vscode-cpptools/issues/5486 ).

Is the issue random? Are you able to find repro steps that repro the issue reliably or find what factors contribute to it occurring more frequently? What I see is that the squiggles in the source file get fixed after I make edits to the header and then switch back to the source file. But I was using a TU that was quick to update. If you're just editing classes without changing what `#include` are used then you shouldn't need to do Rescan Workspace or even save the files, simply changing the active document to the file with the old squiggle should update it.

**Comment by bobbrow** [comment]
We need more information to fully investigate this issue. If you update to the latest version of the extension and your issue persists, please reply with additional information that can help us investigate your issue.
