### ISSUE TITLE
lldb-mi high CPU usage

### ISSUE THREAD

**Issue by cyuste** [microsoft/vscode-cpptools#4097]
Hello,
I am using lastest VS code release:
Version: 1.37.0
Commit: 036a6b1
Date: 2019-08-08T01:22:37.660Z

in a Macbook Mojave 10.14.6 with C/C++ preview extension.
I understand that, well, it is a preview and some things will still need some polishment but when I have a C++ project opened in VS battery duration is drastically reduced. The OS points to VS as the main user of the battery and if you open the activity monitor you will see that lldb-mi process is always with a 90-100% cpu consumption, even if VS is in background

![image](https://user-images.githubusercontent.com/11320538/63156269-9d277b00-c014-11e9-8b15-b28fe1dd462d.png)

So, I hope that this issue will be addressed soon. Thanks for your great work!

**Comment by atteneder** [comment]
Same here.

I try to debug a CMake C++ project. 
Lauching works, seems like all symbols get loaded.
It stops properly on first breakpoint.
Buth then I cannot inspect variables nor step through code. Stopping debugging takes 1-2 seconds but seems to work.

The `lldb-mi` process keeps on spinning at 100% CPU and if not detected/killed manually, brings down the whole system after some minutes.

Id: ms-vscode.cpptools
Version: 0.27.0

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Catalina 10.15.4
Xcode 11.4.1

**Comment by atteneder** [comment]
This extension works as expected:

https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb

**Comment by H-G-Hristov** [comment]
@pieandcakes I experience this issue on MacOS BigSur incl. debugging stopped suddenly working yesterday. I cannot even execute unit tests with the UI Test Explorer extension now.

**Comment by DominicFrei** [comment]
I do find myself in the same situation as @H-G-Hristov regularly. MacOS Big Sur, Visual Studio Code and I see multiple `lldb-mi` processes at 100% until I kill them manually.

**Comment by GCUGreyArea** [comment]
I'm having the same problem right now. 
![Screenshot 2022-02-20 at 08 25 35](https://user-images.githubusercontent.com/9020084/154834643-9d1d187a-e939-45a7-bc4d-4aa1a4d2e48b.png)

**Comment by g101418** [comment]
I also encountered the same problem

**Comment by xtremesky** [comment]
Got the same problem, any solution? the lldb-mi processes do not stop even if I quit vscode.

**Comment by RekiDunois** [comment]
Got the same problem, any solution? the lldb-mi processes do not stop even if I quit vscode.

**Comment by z16166** [comment]
Currently I have a  project which can 100% reproduces this cpu utilization bug at a function breakpoint.

How to analyze this bug? Use a debugger to attach to "lldb-mi" or "debugserver" process to analyze it?

**Comment by whlsxl** [comment]
Same here.

**Comment by z16166** [comment]
> When I uninstalled the plugin `C/C++ Intellisense `, it worked.

quite weird. lldb-mi is the debugger process, but has relation with intellisense? Let me try it also.

**Comment by git-flyer** [comment]
On December 2, 2024, this problem still exists. WTF?

**Comment by pieandcakes** [comment]
I'm no longer on the team that maintains this. If its still an issue, my suggestion would be to open a new issue, add a comment that points to this issue and let the team triage it going forward. This issue has been closed for a number of years already.
