### ISSUE TITLE
Click the search icon to preview results - which search icon?

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode-cpptools#4098]
Minor issue using 0.25.0-insiders2: I tried the new "Find All References..." function, and it starts "confirming" files (weird verb by the way - surely "processing" or "parsing" makes more sense?). Anyway I get this message:

> Find All References: 171/176 files confirmed. Click the search icon to preview results.

I have no idea which "search icon" it is referring to. I tried a few and none of them showed me any preview results.

**Comment by michelleangela** [comment]
The "search icon" to preview results is on the right side of the status bar. 

![image](https://user-images.githubusercontent.com/38734287/63185168-1f607100-c00e-11e9-869b-9bcaab9afcf2.png)

The preview results get displayed on the "REFERENCES:RESULTS" panel.

You can click on the "search icon" again to refresh the preview results. Once the search is complete, the results panel should auto update with the final results.

**Comment by sean-mcmanus** [comment]
Where do you see the verb "confirming"?

The VS Code UI APIs don't allow us to add buttons for commands to the progress UI -- if they fix that we could add a "Preview Results" button. We also can't show an image of the icon in the progress UI unless we use the Unicode search icon, which looks odd.

Is there a reason you didn't notice the search icon in the task bar?

**Comment by Timmmm** [comment]
Ah! I didn't look in the status bar.. I guess because I was expecting the button to preview the results to be near where the results are.

Anyway I guess you could just change it to "Click the search icon in the status bar to preview results." Dunno about "task bar". Maybe that's what it's called but I bet most users don't know that.

It isn't literalled "confirming" but "confirmed",  as in "171/176 files confirmed".

**Comment by tokyophil** [comment]
I had the same problem. I tried the search icon on the left, which i usually use for searching. I did not expect another search icon to click and did not notice the one in the status bar.
Also, i clicked the settings icon, because i thought that maybe the settings icon in the message is representing the icon i should click... (see screenshot)
![Searchicon](https://user-images.githubusercontent.com/19667554/63261785-97d06780-c284-11e9-9ce3-947c937c67d7.JPG)

maybe a message like "Click the search icon in the status bar to preview results" would help others too.

**Comment by michelleangela** [comment]
Would it be helpful if the search icon is a different color so that it is more noticeable? Like the "flame" icon for IntelliSense parsing is red?

**Comment by tokyophil** [comment]
> Would it be helpful if the search icon is a different color so that it is more noticeable? Like the "flame" icon for IntelliSense parsing is red?

Not really, since i never really payed attention to the icons in the status bar and i still would think the search icon would refer to the search button on the left. I think the way it's implemented now in #4106 is the best one with the given circumstances.

**Comment by sean-mcmanus** [comment]
The updated text is shipped with 0.25.0.
