### ISSUE TITLE
Repetitive problem message when pointing to problem line

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-cpptools#41]
_From @alexxx537 on April 26, 2016 7:11_
- VSCode Version: 1.0.0
- OS Version: windows 7

Steps to Reproduce:
1. In one header create warning message
2. Include this header into multiple files
3. Compile and go, to problem Mach in this header
4. Problem message shows a list repetitive messages

It is strange to see list of problem messages that are the same.

_Copied from original issue: Microsoft/vscode#5792_

**Comment by dbaeumer** [comment]
_From @bpasero on April 26, 2016 11:9_

@alexxx537 what language is this?

**Comment by dbaeumer** [comment]
_From @alexxx537 on April 26, 2016 12:41_

It is C language. I am using C/C++ extension.

**Comment by delmyers** [comment]
@sridmad Sridhar, can you look at this?

**Comment by jgoshi** [comment]
In the repro steps, could you clarify the following?
1. What warning did you create (what does the header look like)?
3. Compile and go, to problem Mach in this header. Could you provide a screenshot? Are you building from the command line then opening up the header file in vscode?

**Comment by Aukstkalnis** [comment]
When compiled and jumped to problem, the same message list problem is gone. I think it was fixed after update :) However, there is another problem that is related to this case.
This is how it looks:
![problem](https://cloud.githubusercontent.com/assets/9738294/15418722/de45beb2-1e69-11e6-8c44-630afde2c4ef.png)
But it is strange, that when I jump on both of them, one error disappears. 
I created error message in enumerator by removing one comma.
I am using tasks functionality to launch external bat file that do the job.

**Comment by jgoshi** [comment]
Are you able to repro with the attached project? I'm not sure if I'm following your repro steps properly or the project is not set up properly but when I run it I don't get the duplicate error issue. Do you have a small sample where this repros? Or are you unable to create a repro you can share?

[ConsoleApplication1.zip](https://github.com/Microsoft/vscppsamples/files/275572/ConsoleApplication1.zip)

**Comment by Aukstkalnis** [comment]
This is how I compile my task project and what error messages I get:

![consoleapplication1 7z](https://cloud.githubusercontent.com/assets/9738294/15464032/99f66748-20d5-11e6-845e-1db61f11149a.jpg)

Download picture and change extention from jpg to zip. I did this because I couldn't upload zip file.

**Comment by sridmad** [comment]
I suspect this is not related to the C++ extension.  #The extension does not intercept task invocations nor does it process the resulting output.

**Comment by sridmad** [comment]
Left comment in original issue indicating that this is VSCode issue and closing this
