### ISSUE TITLE
Cannot turn off flame icon

### ISSUE THREAD

**Issue by sd3412** [microsoft/vscode-cpptools#4101]
Whenever I press a key the flame icon has to appear.

This is very annoying. There is no way to limit this behaviour eg. to only the time when the file is being saved.

**Comment by sean-mcmanus** [comment]
The flame icon means that IntelliSense parsing is occurring so IntelliSense-results will be delayed or not be available.

A setting could be added to hide/show it. You can right-click the status bar to hide all the C/C++ icons, but that API doesn't allow finer grained control over the visible icons.

**Comment by sd3412** [comment]
In version 1.33.1 on MacOS Mojave, right clicking the status bar in any place does not have any effect; except for right-clicking the portion that shows the current scope, but this simply shows the one-element context menu with the option to "Manage Extension", and clicking on this just sends me to the extension "main page" (?) where I cannot really manage it.

Anyhow, short of overriding "IsUpdatingIntelliSense()" and building myself, which will probably only cause more headache, development in C++ is excluded for me for now.

**Comment by sean-mcmanus** [comment]
Yeah, they added the right-click status bar filter ability in the past couple months or so to VS Code.

Modifications to the TypeScript are usually safe as long as you use the release branch and your binaries match the release binaries (i.e. 0.24.1). Using the master branch requires using binaries that are compatible (e.g. from the latest insider release if it's available).

You could also change the intelliSenseEngine to "Tag Parser" -- with degraded functionality.
