### ISSUE TITLE
Preprocessor scopes are wrong

### ISSUE THREAD

**Issue by elicn** [microsoft/vscode-cpptools#4104]
Issue Type: <b>Bug</b>

Preprocessor conditions are not well parsed, causing mismatches between corresponding `#ifdef` / `#else` / `#endif` directives. As a result, collapsing an `#ifdef` scope collapses the wrong scope. Observed mostly in nested `#ifdef`'s / `#else`'s.

Extension version: 0.25.0-insiders2
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by azenapow** [comment]
![postprocess_error](https://user-images.githubusercontent.com/16533954/63240817-390eec00-c28c-11e9-8090-25e27edc725a.png)

I have neither.
Extension version: 0.25.0-insiders2

**Comment by matter123** [comment]
@azenapow That is a bug with the TextMate grammar for C++ (endif should not terminate the comment). Could you file an issue at https://github.com/jeff-hykin/cpp-textmate-grammar with that picture and a text version.

Edit: submitted.

**Comment by sean-mcmanus** [comment]
We're tracking the code folding issue with https://github.com/microsoft/vscode-cpptools/issues/407 .

**Comment by azenapow** [comment]
@matter123 Thanks your kindly.
