### ISSUE TITLE
gdb stop at entry

### ISSUE THREAD

**Issue by alexzshl** [microsoft/vscode-cpptools#4108]
Issue Type: <b>Bug</b>

Extension version: 0.24.1
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

in launch.json,the setup bellow

`"stopAtEntry": true,`

This setup has different performance on different debuggers

If I use gdb.exe, it will stop at entry when I launch a cpp file with F5(launch without debug)
How ever,if I use MSVC,it will not stop

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.53GB free)|
|Process Argv|F:\Source\Python\Projects\_test|
|Screen Reader|no|
|VM|40%|
</details>

**Comment by pieandcakes** [comment]
@alexzshl Correct. `stopAtEntry` only works when debugging and with `gdb.exe`, we currently don't support `launch without debug` so it defaults to debugging.
