### ISSUE TITLE
nullptr deemed "undeclared identifier"

### ISSUE THREAD

**Issue by lbartnik** [microsoft/vscode-cpptools#411]
I'm not sure how to tell IntelliSense in Visual Studio Code that my C++ is >= 11 and `nullptr` is a valid keyword. Is that supported?

**Comment by sean-mcmanus** [comment]
nullptr should be keyword highlighted for C++ files. It is not for C files. The language being used is shown in the bottom right. VS Code itself controls the keyword highlighting.

**Comment by bobbrow** [comment]
I see nullptr is highlighted as a keyword in VS Code 1.10.2.  Please let us know if you are still having an issue with this.

**Comment by hstefan** [comment]
I believe I'm having this same issue on version 1.10.2, with the file type being correctly set to C++. Is there any configuration I need to do to get Code to know which standard I'm using?

**Comment by sean-mcmanus** [comment]
What exactly is the issue you are having? There is no configuration you need to do if the language says C++in the bottom right.

**Comment by hstefan** [comment]
I'm gettiing a red squiggle below usages of the nullptr keyword, and as minor issue I also don't get any syntax highlighting for it. I'm attaching a screenshot to illustrate what exactly I'm getting.

![image](https://cloud.githubusercontent.com/assets/341397/24339881/e2f17090-1284-11e7-93cd-f792f79e8a9c.png)

**Comment by sean-mcmanus** [comment]
The squiggle appears to be coming from another extension, and not our cpptools extension. Can you disable our extension and report the bug to the extension that is causing the bug? Also, the theme may be mapping the nullptr keyword color to white, so if you let me know what theme you're using I could double check what the result should be with your theme.

**Comment by frzifus** [comment]
Any update?

**Comment by sean-mcmanus** [comment]
@Frzifus Update in regards to what? This issue is closed. What bug are you seeing exactly? Could you open a new issue?
