### ISSUE TITLE
Open Folder -> Choose new configuration gives an error

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode-cpptools#4118]
Type: Debugger

In 0.25.0-Insiders2, open a folder but do not open any files.
Go to Debug pane and choose Gear -> C++ (Windows)

Expected:
Windows Configuration in a newly created launch.json

Actual: 
Error message: Unable to create 'launch.json' file inside the '.vscode' folder (Cannot read property 'length' of undefined).

```
notificationsAlerts.ts:38 Error: Unable to create 'launch.json' file inside the '.vscode' folder (Cannot read property 'length' of undefined).
    at fileService.readFile.then.then.e (debugConfigurationManager.ts:581)
    at process._tickCallback (internal/process/next_tick.js:68)
```

If I open a .cpp file it works fine. 

This calls into configurationprovider.ts:provideDebugConfigurations and ends up in QuickPickConfigurationProvider.

**Comment by pieandcakes** [comment]
@sean-mcmanus I think this is your area.

**Comment by sean-mcmanus** [comment]
That repros with 0.24.1 too, right? Or is this a regression you think we should fix for 0.25.0?

**Comment by pieandcakes** [comment]
It repros both. I don't know how to fix it as it only repros live and not when i F5 the extension. Might be a check  to `configs` to see if it is null first would be necessary but i don't know if that is the `.length` it complains about.

**Comment by Colengms** [comment]
I'm not able to repro this.  Since this should be a pretty simply scenario to repro, I assume this has been addressed.
