### ISSUE TITLE
Reset memory usage of IntelliSense server when reaches certain size

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#4119]
**Type: LanguageService**

**Issue:**
When editing a source file, memory usage of IntelliSense server for the source file's translation unit will continually grow and end up consuming too much memory

**To Reproduce:**

1. Make a lot of edits/hovers/selection in a class function
2. Memory usage of IntelliSense server grows
3. Make more edits/hovers/selection in a class function
4. Memory usage of IntelliSense server continues to grow

Note: on Windows, the IntelliSense server will just crash when it reaches a certain limit, but on Linux and macOS usage will just keep growing.

**Desired behabior:**
- Reset memory usage when it reaches certain size

**Workarounds:**

Make edit in global scope:
1. Make an edit outside the class scope, such as adding a global variable `int x;`
2. Memory usage should reset back to base size

Force shut down of IntelliSense server by one of following:

- Running command `C/C++: Rescan Worksace`
- Manually killing an IntelliSense server process (Microsoft.VSCode.CPP.IntelliSense.Msvc.*)

**Comment by trampster** [comment]
Had this happen three times so far today, I'm on ubuntu and it happens very quickly and completely locks up the machine such that the only way to recover is to power cycle.

Last time it happened I had system monitor running which caught it using 11 gigs of memory (I only have 16 total) This happened after about 10 minutes of using vs code with a large cpp codebase.

**Comment by FreddieChopin** [comment]
I think I'm having the same issue. Started appearing when editing a large unit-test (~2000 loc) with a lot of test framework macros (I'm using Catch2 + trompeloeil). The memory usage of cpptools binary keeps growing and growing until it reaches a threshold when OS starts swapping things around. As I have no swap enabled (the PC has 16 GB of RAM), this swapping really does nothing, just makes the system completely unresponsive for a few minutes. During that time `kswapd0` process takes nearly 100% of CPU.

See this printscreen of htop, sorted by memory:

![Screenshot from 2019-09-08 16-19-30](https://user-images.githubusercontent.com/1139038/64489563-1e111580-d255-11e9-8dc8-d9ca500f2148.png)

Here's a screenshot from GNOME's system monitor after I close vscode:

![Screenshot from 2019-09-08 16-25-06](https://user-images.githubusercontent.com/1139038/64489572-40a32e80-d255-11e9-81a9-69235c127acb.png)

Before closing vscode the total usage of RAM was 12.1 GB, 77.4%, after closing - 4.3 GB, 27.5%.

Possibly related to #4076 and probably others.

**Comment by sean-mcmanus** [comment]
https://github.com/microsoft/vscode-cpptools/issues/3565 is the same issue -- not sure if we want to close that as a duplicate or not.

**Comment by michelleangela** [comment]
Fixed in version 0.26.2-insiders, available at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders.

**Comment by frz-dev** [comment]
I installed the 0.26.2-insiders version and doesn't seem to work.
On my machine, 'Microsoft.VSCode.CPP.IntelliSense.Msvc.linux'  reaches 3.5 GB.
