### ISSUE TITLE
Debug adapter process has terminated unexpectedly. C++ debugger wont start.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#412]
I have a problem with the C/Cpp tools' debugger not starting, i have followed the instructions on the VS code site and the C/Cpp tools site but nothing works. I can build the file just fine but the debugger cant find it. I tried adding logging to the debugger but it never gets that far to log anything.

Here is my task.json 

    "version": "0.1.0",
    "command": "g++",
    "isShellCommand": true,
    "args": ["-g", "main.cpp"],
    "showOutput": "always"

and launch.json

    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        }
    ]

Here is the error im getting and proof it builds
http://imgur.com/a/Qc7Mg

My system is 

Intel i7 6850K Broadwell
Asus X99 Deluxe ii Motherboard
16GB DDR4 ram
Asus GTX 960 Graphics
Arch Linux OS with KDE plasma 5 desktop

Here is the packages intalled on my system
http://pastebin.com/KAzuCybS

**Comment by pieandcakes** [comment]
@bmr1 Do you have gnome-terminal installed? If not, do you have XTerm installed? We need one of the terminals to allow it to work. Also can you confirm the path for `gdb` on your machine?

**Comment by ghost** [comment]
Yes i have both terminals, they are listed in the pastebin link.

**Comment by pieandcakes** [comment]
@bmr1 if you change `"externalConsole": false` in the `launch.json` does the debugger launch?

**Comment by ghost** [comment]
@pieandcakes yes, changing "externalConsole" to false did solve the issue and the debugger started.

**Comment by maroquio** [comment]
I have the same problem, but setting externalConsole: false did not solve the problem... :(

**Comment by pieandcakes** [comment]
@maroquio please file a new issue with OS version, VS code version and extension version and which terminal applications you have installed.

**Comment by maroquio** [comment]
After fighting for more than 4 hours, I've removed VSCode and extensions and all remaining files and installed it all again. Now it's working. Thanks.

**Comment by pieandcakes** [comment]
@maroquio Thanks for letting me know. Interesting that it got stuck in that mode.
