### ISSUE TITLE
Change C_Cpp.clang_format_path to be scope machine-overridable

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4121]
See https://github.com/microsoft/vscode/issues/73985 .

It would require increasing our vscode dependency to 1.38 (August 2019 release).

**Comment by sean-mcmanus** [comment]
@elahehrashedi See https://github.com/microsoft/vscode-cpptools/pull/3810/files . The change should be similar, but with a "machine-overridable" value (https://github.com/microsoft/vscode/issues/73985#issuecomment-522013185)

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
