### ISSUE TITLE
Enhancement: Auto Create Function Definition

### ISSUE THREAD

**Issue by karan-k-deepr** [microsoft/vscode-cpptools#4123]
It will be awesome if this tool automatically creates `Function Definition` either in the same file or in `CPP` file like `Visual Studio 2017`. 
Because of that, I need to copy and paste function for its declaration which consumes a lot of unnecessary time. 😭

**Comment by bobbrow** [comment]
Thank you for your feedback.  Please go add your 👍 to #664 where we are currently tracking this feature request.
