### ISSUE TITLE
outline not showed in a tree-like view under remote-development

### ISSUE THREAD

**Issue by cnjsdfcy** [microsoft/vscode-cpptools#4124]
- VSCode Version:
```
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```
- OS Version: 
`local Windows 1803, remote Linux server: Ubuntu 18.04.3 LTS`

Steps to Reproduce:

1. install vscode in Windows, and install Remote-Development extension
2. add Ubuntu IP as a connection, and open it
3. open a CPP file in Ubuntu, then install  C/C++ extension on Ubuntu
4. outline showed but not in a tree-like view.
![image](https://user-images.githubusercontent.com/5670527/63514825-13981180-c51c-11e9-901f-d028619f4002.png)

Does this issue occur when all extensions are disabled?: No

**Comment by bobbrow** [comment]
We just started work on this feature for 0.26.0.  We are tracking with #2230.  Thank you!
