### ISSUE TITLE
files.exclude processing doesn't work with "\\"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4127]
@sean-mcmanus 

Unfortunately, the issue is not **fully** fixed.

If use path separator `/`, the issue seems fixed.
![image](https://user-images.githubusercontent.com/999318/63489813-b2554b80-c4e5-11e9-8423-cb349e30d908.png)

If use path separator `\\`, the issue remains.

![image](https://user-images.githubusercontent.com/999318/63489219-1bd45a80-c4e4-11e9-9845-8dc0f2ea8a96.png)

![image](https://user-images.githubusercontent.com/999318/63489253-2ee72a80-c4e4-11e9-8f57-1e6f906ee34d.png)

_Originally posted by @smwikipedia in https://github.com/microsoft/vscode-cpptools/issues/4095#issuecomment-523761316_

**Comment by smwikipedia** [comment]
Thanks for creating issue. Looking forward to the next release.

**Comment by sean-mcmanus** [comment]
Fixed with 0.25.1.

**Comment by smwikipedia** [comment]
It works! Thanks!
