### ISSUE TITLE
GCC errors are reordered

### ISSUE THREAD

**Issue by evarsanyi** [microsoft/vscode-cpptools#4128]
**Type: LanguageService**

Using Linux (Fedora 25) or OSX (Mojave) and any GCC (example 6.3.1) with VS Code 1.38.0-insider and 0.25.0 of the C++ plugin alone when I run a build using the supplied tasks it parses the GCC output and creates 'problems' for each error in the output.

The issue is that the problems are in no useful order, specifically they are not in the order the compiler issued them. GCC (and other C++ compilers) generate loads of error messages downstream of an actual error, sometimes these are useful and indicate different errors, but most of the time these are 'collateral damage' from the first error. The build cycle is usually: analyze the first error and fix it, compile again, repeat.

By randomizing (or sorting by filename) the plugin makes it impossible to find the actual error and instead shows dozens of 'junk' errors that are not fixable.

To reproduce attempt to compile and program with a simple error in it, for example leave the semicolon off a typedef statement where the type is used later in the program. Or create a class with an error in its definition. There will be dozens of "problems" listed but only the first one that came out of the compiler is useful, the rest are just noise. There is no way to tell or sort the "problems" screen by the order the problems came out of GCC so you cannot use VSCode to find/fix compile issues in a C++ program.

As another side issue in this same area: the compiler generates several lines of context around errors, especially when compiling template code, and these are critical to finding the actual problem. These are frequently turned into the own "problems" in VSCODE and then sorted away from the problem they are actually trying to describe and made into their own problem.

The expected behavior is that the "problems" are in the order the compiler issued them, so you can click on the first one and fix, then attempt the second one (which if its a distinct error youc an fix), etc. Once you get to one that is 'junk' you can just recompile and find the new 'first' error. I also expect the lines of context before/after an error message can be found without clicking through hundreds of unrelated problems and there's some way I can tell the 'fake' problems are related to each other.

Other IDE like editors get this right, for example with pure 'vim' the errors window is the actual text that came from the compiler and their matcher lets you click through the problems in the order the compiler generated them AND see the actual error output in their version of the problems window -- not some abstracted away notion of the problems that the editor thinks might be useful.

**Comment by sean-mcmanus** [comment]
This is VS Code bug https://github.com/microsoft/vscode/issues/62942 .

However, our extension could theoretically wrap the gcc command in our own command and bypass the ProblemMatcher mechanism.

**Comment by evarsanyi** [comment]
Thanks for the pointer. I opened this as suggested in the response to my review. This other one is indeed the issue I'm having.

There is one 'additional' related problem in this ticket which is that frequently with GCC (esp in template code) when it reports errors the problem matcher either makes each part of one actual problem into multiple problem entries, or it just ignores them and hides them (they aren't in the problem pane). This data is freqently crucial to figuring out what's wrong (the whole 'instantiated from here' stack).

[from review response]
"
Our extension mostly provides language service and debugger functionality, with a small number of build related features such as a gcc "problem matcher" and a "Build and Debug Active File" command. Providing enhanced gcc build support would require us (or another extension provider) to add our own build commands that wrap gcc and its output instead of going through VS Code's task.json system. You could file a feature request at https://github.com/microsoft/vscode-cpptools/issues . "

**Comment by sean-mcmanus** [comment]
Do you have any more repro details on the problem matcher bug with multiple entries with templates -- it's possible that could be fixed via a change to our problem matcher regular expression at https://github.com/microsoft/vscode-cpptools/blob/release/Extension/package.json#L56
