### ISSUE TITLE
Cannot set "C_Cpp.clang_format_path": "C:\\Program Files\\LLVM\bin\\clang-format.exe": breaks the format feature completely.

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode-cpptools#4132]
**Type: LanguageService**

**Describe the bug**
When setting "C_Cpp.clang_format_path": "C:\\Program Files\\LLVM\bin\\clang-format.exe" in settings.json (either user or workspace), the Format command fails to work, apparently because of error generated by the wrong clang-format binary because the .clang-format option specification is highly unstable and changes drastically between clang releases.

- OS and Version:
Windows 10

- VS Code Version:
1.37.1

- C/C++ Extension Version:
0.25.0

- Other extensions you installed (and if the issue persists after disabling them):

ms-vscode.cpptools
twxs.cmake
vector-of-bool.cmake-tools

- A clear and concise description of what the bug is.
Cannot set "C_Cpp.clang_format_path" to "C:\\Program Files\\LLVM\bin\\clang-format.exe" even though the file is present, and works fine when called form the command line. The built-in clang is stuck on version 6.0.0 which takes some options and rejects others, and vice versa.

When setting my own path to clang, I get an error message telling me to check the output window, which seems to indicate the wrong binary is being called sometimes.

**To Reproduce**
1. Go to settings.json
2. Add "C_Cpp.clang_format_path": "C:\\Program Files\\LLVM\bin\\clang-format.exe"
or "c:/program files/llvm/bin/clang-format.exe" 
3. Right click "Format Document"
4.  Output from wrong clang-format binary.

**Expected behavior**
1. Formatting should work when clicked on using whatever binary is specified by C_Cpp.clang_format_path.

**Comment by danielmrussell** [comment]
Okay, after I made that change to forward slashes, it didn't work immediately, but at some point it started working. I must have done something to refresh something. I dunno. Very confused now haha. I have the exact same .clang-format file but it's working.

Sigh. Gotta love undefined behavior from complex systems. Sorry I couldn't track this more closely. I hope someone here has a clue.

**Comment by sean-mcmanus** [comment]
Did you use a single backslash?

**Comment by danielmrussell** [comment]
I'm getting TRULY bizarre and inconsistent behavior. I have restarted code many times, but just did so again and THIS time when i restarted it and tried clang format, I FINALLY got error messages in the output window a *single time* but it is not reproducible.

However, it seems that the major source of headaches comes from this line in my .clang-format file IndentPPDirectives: BeforeHash which *was* working at some point is now failing.

When I do this at the command line

>clang-format -style=file system.h

I get:

YAML:9:21: error: unknown enumerated scalar
IndentPPDirectives: BeforeHash
                    ^~~~~~~~~~

But AfterHash works okay.

I suspect that somehow vs code is getting confused between the multiple installs of clang (one with Visual Studio, one with cpptools on the super old version of 6.0.0, and one actually installed by me using choco install. Even though I have set the setting in cpptools, it feels like its inconsistently grabbing other ones. I'm not sure and am grasping at straws in frusration.

My installed clang-format is 8.0.1 and should work. BeforeHash is officially in the clang-format documentation as well and I had that working at least once, so I'm thoroughly confounded by all of this.

**Comment by danielmrussell** [comment]
Forward slashes work, / and double backslashes work \\.

I can't explain the bizarre behavior of VS Code and this extension in terms of inconsistent results, but I can say that something is wrong with the BeforeHash option of IndentPPDirectives in .clang-format. Contrary to official clang documentation, this option breaks the program, while the other options work fine. I will submit a bug report to them.

**Comment by danielmrussell** [comment]
Forward slashes work, / and double backslashes work \\.

I can't explain the bizarre behavior of VS Code and this extension in terms of inconsistent results, but I can say that something is wrong with the BeforeHash option of IndentPPDirectives in .clang-format. Contrary to official clang documentation, this option breaks the program, while the other options work fine. I will submit a bug report to them.
