### ISSUE TITLE
Include path from c_cpp_properties.json not passed to clang compiler

### ISSUE THREAD

**Issue by robinbudd** [microsoft/vscode-cpptools#4134]
**Type: LanguageService**

**Steps to Reproduce:** 
1. Configure VSC to use clang++ compiler on MacOS 
2. Include a header file from a directory other than the project, and not one of the standard c++ paths
3. Add the path to the directory to "includePath" in c_cpp_properties.json 
4. Confirm that VS Code knows how to find the include file by  right-clicking the "include " statement and selecting "peek". It shows the include file contents. 
5. Now try to build the file. Get "<filename.h> not found". 

Looking  at the clang++ command line that vscode uses to compile the file, there  is no include path passed in: 
clang++ -std=c++17 -stdlib=libc++ ParseCC.cpp -o ParseCC.out --debug 
Shouldn't the include path be passed to the compiler? 
This works (from the command line):
clang++ -std=c++17 -stdlib=libc++ -I/Users/robinbudd/dev/Library/tinyxml2 ParseCC.cpp -o ParseCC.out --debug

--

**Comment by sean-mcmanus** [comment]
The c_cpp_properties.json is not used for building -- the includePath is just used for IntelliSense. You need to add the -I to whatever build system command you are using. Does that fix it for you?

**Comment by robinbudd** [comment]
Hi Sean, appreciate the quick response. Apparently the compiler arguments go in "tasks.json", which frankly is rather counter-intuitive but OK. It works now. Thanks for the help!

**Comment by michelleangela** [comment]
Closing as resolved.
