### ISSUE TITLE
Variables used in a macro inside a template function don't get coloured

### ISSUE THREAD

**Issue by Zylann** [microsoft/vscode-cpptools#4136]
Windows 10 64 bits
VSCode version: 1.37.1 (user setup)

With the following file:
```cpp
#define CRASH_COND(cond)

template <typename T>
void foo() {
        bool truth = false;
        CRASH_COND(truth == false);
}

void foo2() {
        bool truth = false;
        CRASH_COND(truth == false);
}
```

Variables used inside the `CRASH_COND` macro don't get coloured and don't get highlighted when clicked, but they are if the function is not template.

![image](https://user-images.githubusercontent.com/1311555/63630573-15450080-c614-11e9-8031-576f95ab4ab5.png)

**Comment by sean-mcmanus** [comment]
The bug is inherited from VS. I've filed a bug at https://developercommunity.visualstudio.com/content/problem/711228/variables-used-in-a-macro-inside-a-template-functi.html . You can upvote that if you have a Microsoft account.

**Comment by bobbrow** [comment]
The Visual Studio issue linked to this issue was closed without a fix. Unfortunately, that means it will not be fixed in VS Code either.
