### ISSUE TITLE
NullReferenceException on windows msys2 arm-none-eabi-gdb openocd

### ISSUE THREAD

**Issue by h7ga40** [microsoft/vscode-cpptools#4137]
Type: Debugger

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.18362 (Japanese)
- VS Code Version: 1.37.1 (system setup)
- C/C++ Extension Version: 0.25.0
- Other extensions: nothing (all uninstalled)
- msys2: https://www.msys2.org/
- arm-none-eabi-gcc: https://developer.arm.com/tools-and-software/open-source-software/developertools/gnu-toolchain/gnu-rm/downloads/6-2017-q2-update
- OpenOCD: https://github.com/gnu-mcu-eclipse/openocd/releases/tag/v0.10.0-12-20190422

**To Reproduce**

'launch.json' is following.
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/Debug/${workspaceFolderBasename}.elf",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "debugServerArgs": "-f interface/cmsis-dap.cfg -f target/renesas_rza1h_swd.cfg",
            "filterStderr": true,
            "filterStdout": false,
            "serverStarted": "",
            "targetArchitecture": "ARM",
            "MIMode": "gdb",
            "preLaunchTask": "",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": false
                },
                {
                    "text": "-target-select remote localhost:3333",
                    "ignoreFailures": false
                },
                {
                    "text": "-environment-cd ${workspaceFolder}/Debug",
                    "description": "set cwd",
                    "ignoreFailures": false
                },
                {
                    "text": "symbol-file ${workspaceFolderBasename}.elf",
                    "description": "load file",
                    "ignoreFailures": false
                }
            ],
            "logging": {
                "moduleLoad": true,
                "trace": true,
                "engineLogging": true,
                "programOutput": true,
                "exceptions": true
            },
            "miDebuggerPath": "C:\\Program Files (x86)\\GNU Tools ARM Embedded\\6 2017-q2-update\\bin\\arm-none-eabi-gdb.exe",
            "debugServerPath": "C:\\Program Files\\GNU MCU Eclipse\\OpenOCD\\0.10.0-12-20190422-2015\\bin\\openocd.exe",
        }
    ]
}
```

1. Open C/C++ folder
2. build with arm-none-eabi-gcc, it output 'app.elf' to 'Debug' folder.
3. Type 'F5'
4. output error in Debug console
```
Stopping due to fatal error: NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
```
This was not an issue in earlier versions of cpptools (<=0.24.1)
and
The issue is *not* fixed by adding the "description" field the element inside "customLaunchSetupCommands".

**Comment by atrantan** [comment]
@h7ga40 Got the same issue since version 0.25.0

**Comment by pieandcakes** [comment]
@h7ga40 The problem is this line is missing a `description` and there was a bug I inadvertently introduced which is requiring that `description` not be null:

```
                {
                    "text": "-target-select remote localhost:3333",
                    "ignoreFailures": false
                },
```

I have a fix and it will be in `0.25.1` which we will release this week but in the mean time, you can avoid this by making sure you have a `description` set.

This is a duplicate of #4125 issue.

**Comment by h7ga40** [comment]
After adding "description", it's fixed. Thank you.

**Comment by pieandcakes** [comment]
@h7ga40 Thanks. I'll mark it as a duplicate and closed. It should be fixed again in our next release.
