### ISSUE TITLE
Feature request: write `->` arrow when using `.` on a pointer type

### ISSUE THREAD

**Issue by Zylann** [microsoft/vscode-cpptools#4138]
VSCode 1.37.1

I'm coming from QtCreator and one of the features I miss is the auto-arrow converter when you type `.` after a pointer type.
For example, if you have a `Object *obj` and you write `obj.`, it auto-replaces the dot with an arrow as `obj->` as you type, and you can continue as normal.
This feature saves the hassle of a cumbersome keystroke with just having to type `.` instead of `-` with right hand and `Shift`+`>` with the other hand.

**Comment by michelleangela** [comment]
Duplicate of #862 . Please upvote that issue.

**Comment by sean-mcmanus** [comment]
The fix is available with 0.29.0.
