### ISSUE TITLE
Unable to open some of the files that appear in compilation errors

### ISSUE THREAD

**Issue by Zylann** [microsoft/vscode-cpptools#4139]
VSCode 1.37.1
Windows 10 64 bits

When I compile my project and there are errors, some of them don't show up in the explorer tree.
If I click on one, it very briefly opens and immediately closes, saying it is unable to open.
If I open the file and click on the error again, it actually closes it too, saying it can't open.

![image](https://user-images.githubusercontent.com/1311555/63643836-f442e500-c6d1-11e9-81e5-354a8423fa0f.png)
```
Unable to open 'voxel_terrain.cpp': Unable to read file (Error: File not found (\modules\voxel\terrain\voxel_terrain.cpp)).
```

I tried compiling again but this time all of them are unable to open.
The path indicated in the error is also relative to the folder I have open in VSCode.
It doesn't seem to be consistently happening but it's often, not sure how to repro 100%.

**Comment by sean-mcmanus** [comment]
The Problem is generated from a problemMatcher regular expression in our extension's package.json: `^(.*):(\\d+):(\\d+):\\s+(?:fatal\\s+)?(warning|error):\\s+(.*)$`. So either your compiler is generating paths that randomly break that regular expression or VS Code's handling of that regular expression has a bug with it. What is the general format of the source path when the error occurs? What is the custom problemMatcher you're using (i.e. in your task.json...often you'll need to override the fileLocation property).

**Comment by Zylann** [comment]
This is the kind of log that I get in the `Terminal`:
```
[ 44%] Compiling ==> modules\voxel\terrain\voxel_lod_terrain.cpp
voxel_lod_terrain.cpp
[ 44%] Compiling ==> modules\voxel\terrain\voxel_mesh_updater.cpp
[ 44%] voxel_mesh_updater.cpp
[ 44%] Compiling ==> modules\voxel\terrain\voxel_terrain.cpp
voxel_terrain.cpp
modules\voxel\terrain\voxel_lod_terrain.cpp(388): error C2039: 'enter_world': is not a member of 'VoxelBlock'
c:\projects\godot\engine\godot_fork\modules\voxel\terrain\voxel_block.h(11): note: see declaration of 'VoxelBlock'
scons: *** [modules\voxel\terrain\voxel_lod_terrain.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
The terminal process terminated with exit code: 1
```

I can Ctrl+Click that path and it works, but the `Problems` tab doesn't work.
The problem matcher I use is `"$msCompile"`.

**Comment by Zylann** [comment]
I tried again introducing an error to verify:
![image](https://user-images.githubusercontent.com/1311555/104845706-bc43cf80-58ce-11eb-9462-6d04269fec13.png)

In the Problems tab, the error appears twice. If I click the first one it picks up the `%` part generated by SCons and fails to open that.

Clicking on the second occurrence works.

If I close the file where the error occurs, the working occurrence of the error disappears from the Problems tab, but the non-working occurrence remains.

Seems like the problem became a bit different, because in my first post there wasn't anything wrong in the path, apart maybe the fact it was full lower-case (while in reality some folders are uppercase).

**Comment by sean-mcmanus** [comment]
That would be a bug with VS Code's $mscompile problem matcher. Can you file an issue at https://github.com/microsoft/vscode/issues ?
