### ISSUE TITLE
Cannot attach cannot attach to process after lastest commit!

### ISSUE THREAD

**Issue by lxffff1990** [microsoft/vscode-cpptools#4146]
[https://github.com/microsoft/vscode/issues/79849](https://github.com/microsoft/vscode/issues/79849)

**Comment by sean-mcmanus** [comment]
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4133 . We plan to release a fix soon. You can use "Install Another Version..." to revert to 0.24.1 as a workaround (with extensions.autoUpdate set to false and C_Cpp.updateChannel set to "Default").
