### ISSUE TITLE
can not find the browse.VC.db file

### ISSUE THREAD

**Issue by zhangbo1882** [microsoft/vscode-cpptools#415]
From the official document (http://code.visualstudio.com/docs/languages/cpp), I got the message that is
"With the C/C++ extension installed, this database(browse.VC.db) is generated whenever a folder containing C++ source code files is loaded into VS Code". But in my root folder, there is no such database file. I can see the c_cpp_properties.json but not browser.VC.db. My vs code is 1.8 and cpptools is 0.9.3
![image](https://cloud.githubusercontent.com/assets/2562441/21309318/d4445ba6-c618-11e6-929f-5017f793a387.png)

**Comment by zhangbo1882** [comment]
I have found the cause by
![image](https://cloud.githubusercontent.com/assets/2562441/21309767/8067eece-c61a-11e6-8d72-6cc8806c84ae.png)

**Comment by zhangbo1882** [comment]
@sean-mcmanus , if we do not have a static symbol database (.BROWSE.VC.DB), each time we launch vs code, it will recreate the symbol database dynamically. If the project is very big, it will cost a lot of time. I do not think it is a good design.

**Comment by sean-mcmanus** [comment]
The .browse.vc.db should not be recreated every time. It should be at either the default location or set via the databaseFilename property.

**Comment by zhangbo1882** [comment]
@sean-mcmanus , so are there still .browse.vc.db file in disk？

**Comment by sean-mcmanus** [comment]
Yes, there should be. Either set the databaseFilename path or check the default location like /home/<user>/.config/Code/User/workspaceStorage or C:\Users\<user>\AppData\Roaming\Code\User\workspaceStorage .

**Comment by sunzhec2702** [comment]
Hi Sean,

I met the same issues.
My situation is that I have to install the vs/cpptools offline. After downloaded and installed the extension, the database file didn't show up. And I cannot navigate the code neither.
Also I saw a message when I opened vs.
"Update c/c++ dependencies...
Downloading package 'c/c++ language components(linux)' "

My questions are 
1. Is the update necessary for the navigation?
2. Is there a way I can create the database manually?

Thanks a lot.

**Comment by pieandcakes** [comment]
@sunzhec2702 If you need to install it offline, you will need to run the extension first on a machine online and copy the extension out of the `~/.vscode/extensions` folder as we do not download the dependencies until the extension is first run. Once that is done, it will be ok for you to move it to the offline machine. 

The database is created through the language service code when you open the project so if you follow my instructions above, that should allow the database to be created.

**Comment by zgoda** [comment]
I found that by installing this extension I created symbol databases in all my workspaces in `$HOME/.config/Code/User/workspaceStorage`. Closed VSC, manually removed all these files and they did not get recreated. Indeed, strange behaviour.

**Comment by sean-mcmanus** [comment]
@zgoda The .browse.vc.db files should get recreated when you re-open the folder, but if you change the databaseFilename then they'll get created at that location instead. Do things like Go To Definition work for you?

**Comment by zgoda** [comment]
@sean-mcmanus none of features provided by the plugin and related to symbols work (go to definition, arguments list in tooltip, docstrings, etc.). If I hover over symbol I get only "loading...", the "red flame" stays forever, includes are not resolved.

**Comment by zgoda** [comment]
I changed database location so now relevant bits of plugin configuration:

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/home/jazg/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/include",
                "/home/jazg/Sming/Sming",
                "/home/jazg/Sming/Sming/system/include"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "/home/jazg/work/sming_playground/.vscode/browse.vc.db"
            }
        }
    ]
}
```

After couple of VSC restart and database delete cycles symbol collection process finally finished and symbol-related features started working.

**Comment by sean-mcmanus** [comment]
Yeah, it sounds like something was preventing the browse database from being created, most likely a lingering or crashing Microsoft.VSCode.Cpp.Extension.linux process. We do not have a good repro yet, but are working to improve the reliability.
