### ISSUE TITLE
Intellisense stops working after declaring a class inside another one

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#4154]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.37.1
- C/C++ Extension Version: 0.25.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
When I declare a class inside another one, i.e.
    ```cpp
    class a {
    public:
        class b {
        };
    };
    ```
    IntelliSense stops working for some reason.

**Comment by michelleangela** [comment]
I'm not able to reproduce the issue. I tried to reproduce by using your sample code in a *.cpp and *.h files.

Does the entire IntelliSense server stop working or is there a particular feature of IntelliSense that doesn't work?

Can you [enable logging for the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) and send the logs?

Also, did you change any settings in `c_cpp_properties.json`? If so, can you send a copy of those too?

**Comment by michelleangela** [comment]
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.
