### ISSUE TITLE
Cannot open source file iostream 

### ISSUE THREAD

**Issue by krisbyington** [microsoft/vscode-cpptools#4155]
Type: General
I installed two extensions, the microsoft c/c++ estension and the code runner extension as for a compiler. 
I copied in a simple program to test the compiler and I have two error messages returned when I tried to compile the code.

The first is 
 Failed to parse "\.vscode\c_cpp_properties.json": ENOENT: no such file or directory, open'\.vscode\c_cpp_properties.json'

The second is 
cannot open source file "iostream"

I have unistalled and reinstalled all extensions from VScode and I am still getting the same issue. here is a screenshot of my code, installed extensions and the error messages. 

![image](https://user-images.githubusercontent.com/43834863/63884662-74e03a80-c98b-11e9-87c5-7c0ace6251dc.png)

I am running the 0.25.0 version that was released 6 days ago. 

I read that this issue had been fixed in the new update but I am still getting the same errors.

**Comment by sean-mcmanus** [comment]
What are the repro steps to get "Failed to parse ".vscode\c_cpp_properties.json": ENOENT: no such file or directory, "? We fixed a bug with the same symptom previously, but your repro steps are probably different.

Can you do a C/C++: Log Diagnostics command to see what your includePaths are? You should probably set your compilerPath setting to your compiler to automatically get the correct system includes.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
