### ISSUE TITLE
fatal error: opencv2/opencv.hpp: No such file or directory

### ISSUE THREAD

**Issue by bitquality** [microsoft/vscode-cpptools#4157]
I am trying to use openCV library in my VSCode . I could compile a hello world cpp program but doesn't work when i include any header from opencv.

fatal error: opencv2/opencv.hpp: No such file or directory

my c_cpp_properties.json

`{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\opencv\\build\\include",
                "C:/opencv/build/include",
                "C:\\opencv\\build\\x64\\vc15\\bin",
                "C:\\opencv\\build\\x64\\vc15\\lib",
                "C:\\opencv\\sources\\modules\\core\\include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "cppStandard": "c++20",
            "cStandard": "c89"
        }
    ],
    "version": 4
}`

tasks.json:

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "myC++",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g",
                "HelloWorld.cpp",
                "-o",
                "HelloWorld"
            ],
            "group": "build",
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
}`

HelloWorld.cpp:

```
#include <iostream>
#include <fstream>
#include <windows.h>

int main()
{
    // Output the hello world text
    std::cout << "Hello world!" << std::endl;
    return 0;
}
```
The above program works.

If i try to include #include <opencv2/opencv.hpp> header and build it , it throws error fatal error: opencv2/opencv.hpp: No such file or directory.

I am using MinGW

**Comment by sean-mcmanus** [comment]
You need to add the -I include paths to your tasks.json. The paths in c_cpp_properties.json includePath are not used for compiling (just IntelliSense features).

**Comment by bitquality** [comment]
Thanks for the quick reply. Can you give me one sample or line with -I 
I have updated it to below. Is that valid ? 

`            {
                
                "version": "2.0.0",

                "tasks": [
                    {
                        "label": "myC++",
                        "type": "shell",
                        "command": "g++",
                        "args": [
                            "-I",
                            "C:\\opencv\\build\\include",
                            "HelloWorld.cpp",
                            "-o",
                            "HelloWorld"
                        ],
                        "group": "build",
                        "problemMatcher": [
                            "$gcc"
                        ]
                    }
                ]
            }`

The above approach now gives me another error:

```
C:\opencv\build\include/opencv2/core/utility.hpp:701:14: error: 'recursive_mutex' in namespace 'std' does not name a type
 typedef std::recursive_mutex Mutex;

```

**Comment by sean-mcmanus** [comment]
That is the error you get when you use gcc 5.5 instead of 6.1 or later. Can you upgrade your compiler?

**Comment by bitquality** [comment]
Not sure how i can upgrade the gcc to > 6.1. I had MingW setup in my system and it was teh latest i feel.

This is the directory of mingw: C:\MinGW\lib\gcc\mingw32\6.3.0

**Comment by sean-mcmanus** [comment]
Instead of using command "g++" you should specify the path to your MinGW compiler. It might be picking and older/different one (on your path). If you use a --version command line arg in your task you can check the version of your compiler.
