### ISSUE TITLE
Parsing doctest.h 1.2.9 very slow

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cpptools#4158]
Issue Type: <b>Bug</b>

1. Create a C/C++ project with cmake.
2. open doctest.h
3. it's would stuck for a long time(TOO LONG), and then doctest.h are parsed out. There is no infinite loop, cause finllay it's out, but really slow

Extension version: 0.25.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.80GB (14.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details>

**Comment by sean-mcmanus** [comment]
What does "Create a C/C++ project with cmake" mean?

If you do a Reload Window is it slow the 2nd time?

Is the red flame or database icon showing?

**Comment by lygstate** [comment]
@sean-mcmanus  It's still slow each time I open doctest.h,  after Reload Window still slow

**Comment by sean-mcmanus** [comment]
What is doctest.h?

**Comment by matter123** [comment]
@sean-mcmanus This might be https://github.com/microsoft/vscode/issues/78769

**Comment by sean-mcmanus** [comment]
@matter123 Thanks -- yeah, that's it. I reproed the bug as soon as I disabled the Better C++ Syntax extension. Freezes for around 45 seconds for me.

**Comment by lygstate** [comment]
Yeap, Better C++ Syntax extension solve the issue

**Comment by bobbrow** [comment]
This should be fixed in the latest version of VS Code.  They import the syntax from the Better C++ Syntax extension from time to time.
