### ISSUE TITLE
Auto-complete is adding !-- every time I put a point "." inside Summary comment

### ISSUE THREAD

**Issue by igormcoelho** [microsoft/vscode-cpptools#4163]
**Type: LanguageService**

**Describe the bug**
- OS and Version: linux 
- VS Code Version: 1.35.0
- C/C++ Extension Version: 0.25.0
- Other extensions you installed (and if the issue persists after disabling them): C# extension may also affect this...
- A clear and concise description of what the bug is.

I'm trying to hit a double point ".." inside a "</summary>" comment for parameters of a function... but every time I hit double "..", it gives me ".!--", so I have to manually close a suggestion box every time I click a point ".", which is terrible for programming. It only happens inside comments, and looks like it's related to some html parser perhaps, as !-- is common there I guess. 

**To Reproduce**
1. Open editor and create a comment like this:
// < Summary>
//  
// < /Summary>
2. Inside this parameter summary, try to put a double point "..", and it will give you ".!--"

**Expected behavior**

After hitting two points ".", I expected to have on screen "..", not ".!--"

**Screenshots**

![image](https://user-images.githubusercontent.com/290989/63907654-dc12f300-ca4e-11e9-863e-11f7d218382e.png)

**Additional context**

Please help, it's so annoying... I don't know how to disable or debug this.

**Comment by sean-mcmanus** [comment]
What programming language is the file using? I don't think our extension is doing this. You could try changing the wordBasedSuggestions VS Code setting.

**Comment by Colengms** [comment]
Hi @igormcoelho .  It looks like this issue is regarding the C# Extension for VS Code, not the C++ Extension for VS Code.  Is that correct?  If so, I'd suggest opening the issue here: https://github.com/OmniSharp/omnisharp-vscode/issues
