### ISSUE TITLE
Different windowsSDK directories

### ISSUE THREAD

**Issue by swq123459** [microsoft/vscode-cpptools#4164]
**Type: LanguageService**

**Describe the bug**
- OS and Version: win10 `1903` x64
- VS Code Version: `1.37.1`
- C/C++ Extension Version: `0.25.0`
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
My computer has windowsSDK (v10 in vs2019), and platformSDK (vs2005); I want to use the vs2005 build environment, I use vsvars32.bat to set the environment variables and enter through the console (just like https://code.visualstudio .com/docs/cpp/config-msvc that is going to be done), it is reasonable to enter the "compilerPath" in the configuration, it should be `VS05_path\VC\bin.cl.exe`, but his configuration is still `C: /Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe`
Also, the version number is also wrong 10.0.17134.0, I hope not the development environment of this version, but vs05

**Expected behavior**

**Screenshots**

**Additional context**

goto definition of printf, go to the `C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h` but not goto the correct path `VS05_path\vc\include\stdio.h`.why?
In the old version of vs, choose not to install the c drive, windowsSDK will not put the c drive `C:\Program Files (x86)\Windows Kits\`, will this be the cause?
I have installed multiple versions of windowsSDK on my computer. I have no problem with Visual Studio development, but the multi-version SDK has problems running in vsCode.

**Comment by swq123459** [comment]
in c_cpp_properities.json i set `"windowsSdkVersion": "8.1.51636.0"`(win8.1 SDK) false, It seems to only support versions above 10.

**Comment by michelleangela** [comment]
If you're using Windows SDK 8.1.*, the property `windowsSdkVersion` expects `8.1`. Can you try setting it to `8.1` and run the command `C/C++: Log Diagnostics` to see which include paths are used?

**Comment by swq123459** [comment]
- Thank you very much for your guidance. I configured `windowsSdkVersion=8.1` according to your practice and met the format requirements. I am very happy to see that the c/c++ plugin starts downloading some content of the corresponding version, then I ran `C/C++: Log Diagnostics`, printed the following content：
```
-------- Diagnostics - 2019/8/30 上午10:46:01
Version: 0.25.1
Current Configuration:
{
    "name": "Win32",
    "defines": [
        "_DEBUG"
    ],
    "windowsSdkVersion": "8.1",
    "compilerPath": "F:/Program Files (x86)/VS13/VC/bin/cl.exe",
    "cStandard": "c11",
    "cppStandard": "c++11",
    "intelliSenseMode": "msvc-x86",
    "compilerArgs": [],
    "browse": {
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ F:\Program Files (x86)\VS13\VC\EmptyProjSWQ\Proj\ProjectName\ProjectName\main.cpp ]:
    F:\PROGRAM FILES (X86)\VS13\VC\EMPTYPROJSWQ\PROJ\PROJECTNAME\PROJECTNAME\MAIN.CPP
Translation Unit Configurations:
[ F:\Program Files (x86)\VS13\VC\EmptyProjSWQ\Proj\ProjectName\ProjectName\main.cpp ]:
    Process ID: 5780
    Memory Usage: 118 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.22.27905\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.22.27905\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\8.1\INCLUDE\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\8.1\INCLUDE\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\8.1\INCLUDE\WINRT
    Defines:
        _DEBUG
    Standard Version: c++11
    IntelliSense Mode: msvc-x86
Total Memory Usage: 118 MB
```
My c_cpp_properties.json is
```json
{
    "configurations": [
        {
            "name": "Win32",
            "defines": [
                "_DEBUG"
            ],
            "windowsSdkVersion": "8.1",
            "compilerPath": "F:/Program Files (x86)/VS13/VC/bin/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "msvc-x86"
        }
    ],
    "version": 4
}
```
- I configured `compilerPath`, but unfortunately, it doesn't seem to use my configuration, but instead uses the default configuration, this location is not my target cl.exe
- As you can see, the path to windowsSDK is correct. But for the current version of the `windows runtime` and the MFC path include directory is wrong, detected the content of my vs19 version, why is this?
- And I found out that my `include<isotream>` and `#include <windows.h>` error:
![image](https://user-images.githubusercontent.com/35790719/63989927-b8b27b80-cb14-11e9-89b3-7025b2e643c0.png)
- Upon following the prompt, I will add the correct `includePath` to my configuration.
```json
	  "includePath": [
                 "F:/Program Files (x86)/VS13/VC/include",
                "F:/Program Files (x86)/VS13/VC/atlmfc/include"
             ]
```
- Then I found that the previous error was gone, but when I run`F12 ` from  `iostream`, I found that it actually suggested that I have 2 possible files, one is the correct path I just configured, and the other is the path of vs19. I think, since the correct path is configured, how can the previous path be deleted?
- Thanks again to Mr. Michelleangela

**Comment by michelleangela** [comment]
The use of setting the `compilerPath` property is to find system includes and defines associated with that compiler path. However, the extension only checks paths for Visual Studio 2015 and later versions for Windows.

If you would like to use specific include paths and do not want the extension to add include paths based on the `compilerPath` setting, do the following:
- set `compilerPath` to `""`
- if `compilerPath` is `""`, then there is no need to set `windowsSdkVersion`, because `windowsSdkVersion` will not be considered if `compilerPath` is specifically set to `""`.
- list all the include paths, including the ones for the SDK, under `includePath` property.

Example:

```
{
    "configurations": [
        {
            "name": "Win32",
            "defines": [
                "_DEBUG"
            ],
            "includePath": [
                "F:/Program Files (x86)/VS13/VC/include",
                "F:/Program Files (x86)/VS13/VC/atlmfc/include",
                "C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/UM",
                "C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/SHARED",
                "C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/WINRT"
             ]
            "compilerPath": "",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "msvc-x86"
        }
    ],
    "version": 4
}
```

Will this work for your workspace? Also just to clarify, the `c_cpp_properties.json` settings only applies to configuring the IntelliSense server and not for building a project.

**Comment by swq123459** [comment]
- Thank you for your guidance and comments.
- According to your instructions, it is now working properly.
- However, I still hope that these contents can be explained in the document, or that some conceptual things are clearly explained to avoid confusion.
- best wishes and thanks a lots Mr. Matias
