### ISSUE TITLE
The same macro definition could not be correctly identified

### ISSUE THREAD

**Issue by LiShunGang** [microsoft/vscode-cpptools#4165]
Type: Debugger

Member properties and member functions cannot be identified

**Describe the bug**
- OS and Version: win10 ssh centos
- VS Code Version: 1.37.1
- C/C++ Extension Version: 0.25.0

A/InternodeSyncer.h:
```
#ifndef INTERNODESYNCER_H_
#define INTERNODESYNCER_H_
class InternodeSyncer
{...}
#endif /* INTERNODESYNCER_H_ */
```

B/InternodeSyncer.h:
```
#ifndef INTERNODESYNCER_H_
#define INTERNODESYNCER_H_
class InternodeSyncer
{...}
#endif /* INTERNODESYNCER_H_ */
```

Then, member properties and member functions in "B/InternodeSyncer.cpp" could not be correctly identified

**Comment by sean-mcmanus** [comment]
Can you give more repro details? I'm not able to observe any bug, and I don't understand what bug you're seeing. Is your source file including the header file?

**Comment by LiShunGang** [comment]
B/InternodeSyncer.cpp:
![image](https://user-images.githubusercontent.com/36393104/64249848-404e1f00-cf47-11e9-9ea9-940ee1df6696.png)

If I del macro definition in B/InternodeSyncer.h, member properties and member functions will be correctly identified.
If I don't do that, then B/InternodeSyncer.cpp links to A/InternodeSyncer.h.

**Comment by sean-mcmanus** [comment]
Are you using "${workspaceFolder}/**" in your includePath? That could cause the wrong include path to be used. Can you run C/C++: Log Diagnostics with the .cpp file active and see if the results look correct?

**Comment by sean-mcmanus** [comment]
Actually, if you're using `#include ""` then it should be using the B header and not recursive includes.

I think we need more repro details still.

**Comment by LiShunGang** [comment]
Yeah, I'm using "${workspaceFolder}/**" in my includePath.
I got this:
1/a.h
```
#ifndef A_H
#define A_H

#include <common/Bar.h>

class Foo : public Bar
{
    public:
        Foo(int a);
        int a_;
};

#endif
```
2/a.h
```
#ifndef A_H
#define A_H

#include <common/Bar.h>
#include <iostream>

class Foo : public Bar
{
    public:
        Foo(int a, int b);
        int a_;
        int b_;
};

#endif
```
2/a.cpp
```
#include <a.h> // This is included by some other Header
#include "a.h"

Foo::Foo(int a, int b) : Bar("common"), a_(a), b_(b) {}
```
Then 2/a.cpp will use 1/a.h.
![image](https://user-images.githubusercontent.com/36393104/64399344-adbe9480-d09a-11e9-94dc-359c67c214ee.png)


How to avoid that?

**Comment by sean-mcmanus** [comment]
The first `#include <a.h>` is causing the 1 folder to be used due to recursive includes (which is "by design"). The workaround in this case would be to add "${workspaceFolder}/1" to the includePath before "${workspaceFolder}/**" -- in more complicated scenarios where folders can't be added to break "ties" then you could remove the recursive include or add directories to the files.exclude.

The 2nd "a.h" causes the 2 version to be used, because in that case the local directory is given priority in the path.

**Comment by LiShunGang** [comment]
```
"includePath": [
   "${fileDirname}",
   "${workspaceFolder}/**",
],
```
I changed the ```includePath``` but still can't affect the result of the first ```#include <a.h>```.
Is there some way to affect it?

**Comment by sean-mcmanus** [comment]
We don't support the variable ${fileDirname}.
