### ISSUE TITLE
Configuration notification should not show when there is a custom configuration provider.

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools#4168]
When a custom configuration is provided and set as the active/default provider, the user should not be prompted to configure their IntelliSense - they expect the configuration provider to do that.

**Comment by sean-mcmanus** [comment]
What's the prompt? Is this for the compile_commands.json prompt or something else?

i.e. how do I repro the bug? I believe I've seen the compile_commands.json prompt appear when it shouldn't because I was using a custom config provider, but I'm not sure how to repro it now.

**Comment by sean-mcmanus** [comment]
I got a repro of the compile_command.json prompt with a custom config provider, but it seems like it's occurring when the custom config provider is stuck. We could just check if the setting is set and skip the custom config prompt in that case.

**Comment by sherryyshi** [comment]
I was talking specifically about "Configure your IntelliSense settings to help find missing headers."

I actually have not seen the compile_command.json prompt with our extension, but in any case that also seems like something that we don't want our users to set.

**Comment by sean-mcmanus** [comment]
Ah, okay -- that message appears if the intelliSenseEngineFallback is enabled -- the default is "Disabled".

Oh, no, it also repros if errorSquiggles is the default value.

**Comment by sherryyshi** [comment]
Thanks Sean!

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders . Let us know if it's not working for you.
