### ISSUE TITLE
C project, .inc include file cannot find

### ISSUE THREAD

**Issue by Skilence** [microsoft/vscode-cpptools#418]
C project, .inc include file cannot find.
I have set the settings: "files.associations": {"*.inc": "c"}
The .h file is OK, but the .inc file cannot find..

**Comment by sean-mcmanus** [comment]
Assuming I understand you correctly, it is a known bug that Go To Definition doesn't work with unusual file extensions: https://github.com/Microsoft/vscode-cpptools/issues/408 .

**Comment by bobbrow** [comment]
This should be fixed in the latest version of the extension. 0.10.3
