### ISSUE TITLE
documentSymbol parse error

### ISSUE THREAD

**Issue by zb-007** [microsoft/vscode-cpptools#4181]
hi, here i met a problom:

I used a macro in the function, but it seems to be treated as a definition of another function.

![截图3](https://user-images.githubusercontent.com/54835759/64152992-68168780-ce60-11e9-970e-85abe29941d9.PNG)

This problem causes other symbols in the source file to not be parsed correctly, and the outline is not displayed correctly.

![截图4](https://user-images.githubusercontent.com/54835759/64162063-41ad1800-ce71-11e9-98be-c6f020621e88.PNG)

**Comment by sean-mcmanus** [comment]
This is "by design". The macro that require evaluation in order to parse the code correctly need to be added to a cpp.hint file in your workspace. See https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2019 . Let us know if that doesn't work.
