### ISSUE TITLE
Incorrect include file error indicator

### ISSUE THREAD

**Issue by mikepelley** [microsoft/vscode-cpptools#4185]
I have configured my include paths in c_cpp_properties.json and it has been working well. Just recently I'm getting the following error indicator for an undefined macro:

![image](https://user-images.githubusercontent.com/48527/64209864-acf5ea80-ce6f-11e9-836e-eaf2afaa3458.png)

In the hover box I can see that vscode found the macro definition and knows the value (64), but then proceeds to say that the name is undefined. If it found the definition I would think it shouldn't report it as undefined, but perhaps I'm missing something.

This error persists after restarting vscode and running "C/C++: Reset IntelliSense Database".

**Comment by sean-mcmanus** [comment]
The error squiggle is from the IntelliSense parser and the hover info is from the tag parser...I believe that would happen if the IntelliSense process was crashing or somehow not available during the hover. Can you [enable logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) and look for errors?

**Comment by mikepelley** [comment]
I'm afraid I did not see any errors. I cleared the output window and then opened the target file (common.h) and here are the logs:

```
textDocument/didOpen
Checking for syntax errors: file:///n/mpelley/infra/lib/libsmg/src/common.h
queue_update_intellisense for files in tu of: /n/mpelley/infra/lib/libsmg/src/block.c
textDocument/codeAction: 70
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentSymbol: 71
errorSquiggles count: 0
errorSquiggles count: 1
terminating child process: 2527
Update IntelliSense time (sec): 0.315
textDocument/hover: 72
textDocument/codeAction: 73
idle loop: reparsing the active document
Checking for syntax errors: file:///n/mpelley/infra/lib/libsmg/src/common.h
queue_update_intellisense for files in tu of: /n/mpelley/infra/lib/libsmg/src/block.c
errorSquiggles count: 0
errorSquiggles count: 1
Update IntelliSense time (sec): 0.29
textDocument/codeAction: 74
```

**Comment by sean-mcmanus** [comment]
Okay, looks like no crashing is occurring and it also doesn't appear to be falling back to the tag parser results for hover. Looks like something is causing the symbol to get undefined when checking for error squiggles...are you able to simplify the code any further to get a repro we can try?

**Comment by mikepelley** [comment]
It's a large codebase from work, but I will give it a shot this weekend.

**Comment by mikepelley** [comment]
I'm afraid I was not able to reproduce with a smaller example (the problem would not appear in the smaller sandbox I created). I'm not sure how to proceed; perhaps this should be closed as unreproducible.

**Comment by Victsz** [comment]
I have a similar issue.
```
FILE(GLOB PROJECT_SRCS      
    "${PROJECT_SOURCE_DIR}/src/*.cc"
    "${PROJECT_SOURCE_DIR}/src/Olympia/*.cc"
    "${PROJECT_SOURCE_DIR}/src/Olympia/*.hpp"
    "${PROJECT_SOURCE_DIR}/src/Helper/*.hpp"
)
```
![image](https://user-images.githubusercontent.com/8154646/68556050-9c638100-046b-11ea-985c-4c771674ce42.png)



The absolute path for the files "\ExtendSpace\Victor\Git..." is not correct. I think it is about symbolic link
I open the project under "/home/victor/Workspace/Git " and Workspace -> /ExtendSpace/Victor/
Some how the path is mixed up.

I tried CMAKE reconfigure and  Reset intelliesense database but no luck.

**Comment by bobbrow** [comment]
This looks like the same issue as #4576.  Closing this in favor of that one since it has more repro information in it.
