### ISSUE TITLE
Auto-complete does not take effect

### ISSUE THREAD

**Issue by suzukajiang** [microsoft/vscode-cpptools#4188]
vscode : 1.36.1
cpptools : 0.25.1
win7

cpptools/activeDocumentChange
Unable to resolve include path: D:/tools/mingw32/lib/gcc/i686-w64-mingw32/8.2.1/include
cpptools/textEditorSelectionChange
textDocument/documentHighlight: 142
cpptools/textEditorSelectionChange
textDocument/codeAction: 143
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/workspace/iNet_1881_CP_H/protocol/L2/u-task/rlc/um/rlc_um_segment.c
queue_update_intellisense for files in tu of: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM\RLC_UM_SEGMENT.C
errorSquiggles count: 2
Update IntelliSense time (sec): 0.29
cpptools/textEditorSelectionChange
textDocument/codeAction: 144
textDocument/didChange
cpptools/textEditorSelectionChange
Checking for syntax errors: file:///d%3A/workspace/iNet_1881_CP_H/protocol/L2/u-task/rlc/um/rlc_um_segment.c
queue_update_intellisense for files in tu of: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM\RLC_UM_SEGMENT.C
textDocument/documentSymbol: 145
sending 1 changes to server
errorSquiggles count: 2
Update IntelliSense time (sec): 0.295
textDocument/didSave
  tag parsing file: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM\RLC_UM_SEGMENT.C
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/completion: 147
auto_complete::handle_completion: file:///d%3A/workspace/iNet_1881_CP_H/protocol/L2/u-task/rlc/um/rlc_um_segment.c (775:6)
Offering completion
sending 1 changes to server
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/completion: 148
auto_complete::handle_completion: file:///d%3A/workspace/iNet_1881_CP_H/protocol/L2/u-task/rlc/um/rlc_um_segment.c (775:8)
Offering completion
sending 2 changes to server
textDocument/codeAction: 149
textDocument/didChange
cpptools/textEditorSelectionChange
completionItem/resolve: 150
sending 1 changes to server
textDocument/codeAction: 151
Request canceled: 145
textDocument/documentSymbol: 152
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/workspace/iNet_1881_CP_H/protocol/L2/u-task/rlc/um/rlc_um_segment.c
queue_update_intellisense for files in tu of: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM\RLC_UM_SEGMENT.C
textDocument/didSave
  tag parsing file: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM\RLC_UM_SEGMENT.C
textDocument/didChange
cpptools/textEditorSelectionChange
completionItem/resolve: 154
sending 1 changes to server
Failed to read response from server: 6
IntelliSense engine is not responding. Using the Tag Parser instead.
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/didSave
sending 1 changes to server
Update IntelliSense time (sec): 0.25
textDocument/didChange
cpptools/textEditorSelectionChange
  tag parsing file: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM\RLC_UM_SEGMENT.C
textDocument/codeAction: 156
textDocument/didChange
cpptools/textEditorSelectionChange
textDocument/completion: 157
Resetting IntelliSense server: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM\RLC_UM_SEGMENT.C
Closing the communication channel.
sending compilation args for D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM\RLC_UM_SEGMENT.C
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\PUB\INCLUDE
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\PUB\INCLUDE\MAPI
  include: D:\WORKSPACE\INET_1881_CP_H\PUB\INC
  include: D:\WORKSPACE\INET_1881_CP_H\COMMON\OSA\INC
  include: D:\WORKSPACE\INET_1881_CP_H\PUB\INC\MOS\LARENA\INCLUDE\PE\KERNEL
  include: D:\WORKSPACE\INET_1881_CP_H\PUB\INC\MOS\LARENA\INCLUDE\PA\DEVMAN
  include: D:\WORKSPACE\INET_1881_CP_H\PUB\INC\MOS\LARENA\INCLUDE\PSE\SERVICES
  include: D:\WORKSPACE\INET_1881_CP_H\PUB\INC\MOS\LARENA\INCLUDE\PE\SMARTCARD
  include: D:\WORKSPACE\INET_1881_CP_H\PUB\INC\MOS\LARENA\INCLUDE\PE\TELEPHONY
  include: D:\WORKSPACE\INET_1881_CP_H\PUB\INC\MOS\DRIVERS_TURNKEY\INC
  include: D:\WORKSPACE\INET_1881_CP_H\LMS\DRIVERS_TURNKEY\INC
  include: D:\WORKSPACE\INET_1881_CP_H\LMS\DRIVERS_TURNKEY\CAL\LC1860\INC
  include: D:\WORKSPACE\INET_1881_CP_H\COMMON\EL1A\INC
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\COMMON
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\COMMON
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\UTIL
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\UTIL\MIDDLEWARE\INC
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\TRANS
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\TRANS\FRAGMENT
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\PDCP
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\AM
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\TM
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM
  include: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\MAC
  include: D:\TOOLS\MINGW32\I686-W64-MINGW32\INCLUDE
  include: D:\TOOLS\MINGW32\INCLUDE
  define: __STDC__=1
  define: __STDC_VERSION__=199901L
  define: __STDC_HOSTED__=1
  define: __GNUC__=7
  define: __GNUC_MINOR__=4
  define: __GNUC_PATCHLEVEL__=0
  define: __VERSION__="7.4.0"
  define: __ATOMIC_RELAXED=0
  define: __ATOMIC_SEQ_CST=5
  define: __ATOMIC_ACQUIRE=2
  define: __ATOMIC_RELEASE=3
  define: __ATOMIC_ACQ_REL=4
  define: __ATOMIC_CONSUME=1
  define: __FINITE_MATH_ONLY__=0
  define: __SIZEOF_INT__=4
  define: __SIZEOF_LONG__=4
  define: __SIZEOF_LONG_LONG__=8
  define: __SIZEOF_SHORT__=2
  define: __SIZEOF_FLOAT__=4
  define: __SIZEOF_DOUBLE__=8
  define: __SIZEOF_LONG_DOUBLE__=12
  define: __SIZEOF_SIZE_T__=4
  define: __CHAR_BIT__=8
  define: __BIGGEST_ALIGNMENT__=16
  define: __ORDER_LITTLE_ENDIAN__=1234
  define: __ORDER_BIG_ENDIAN__=4321
  define: __ORDER_PDP_ENDIAN__=3412
  define: __BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __FLOAT_WORD_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __SIZEOF_POINTER__=4
  define: __SIZE_TYPE__=unsigned int
  define: __PTRDIFF_TYPE__=int
  define: __WCHAR_TYPE__=short unsigned int
  define: __WINT_TYPE__=short unsigned int
  define: __INTMAX_TYPE__=long long int
  define: __UINTMAX_TYPE__=long long unsigned int
  define: __CHAR16_TYPE__=short unsigned int
  define: __CHAR32_TYPE__=unsigned int
  define: __SIG_ATOMIC_TYPE__=int
  define: __INT8_TYPE__=signed char
  define: __INT16_TYPE__=short int
  define: __INT32_TYPE__=int
  define: __INT64_TYPE__=long long int
  define: __UINT8_TYPE__=unsigned char
  define: __UINT16_TYPE__=short unsigned int
  define: __UINT32_TYPE__=unsigned int
  define: __UINT64_TYPE__=long long unsigned int
  define: __INT_LEAST8_TYPE__=signed char
  define: __INT_LEAST16_TYPE__=short int
  define: __INT_LEAST32_TYPE__=int
  define: __INT_LEAST64_TYPE__=long long int
  define: __UINT_LEAST8_TYPE__=unsigned char
  define: __UINT_LEAST16_TYPE__=short unsigned int
  define: __UINT_LEAST32_TYPE__=unsigned int
  define: __UINT_LEAST64_TYPE__=long long unsigned int
  define: __INT_FAST8_TYPE__=signed char
  define: __INT_FAST16_TYPE__=short int
  define: __INT_FAST32_TYPE__=int
  define: __INT_FAST64_TYPE__=long long int
  define: __UINT_FAST8_TYPE__=unsigned char
  define: __UINT_FAST16_TYPE__=short unsigned int
  define: __UINT_FAST32_TYPE__=unsigned int
  define: __UINT_FAST64_TYPE__=long long unsigned int
  define: __INTPTR_TYPE__=int
  define: __UINTPTR_TYPE__=unsigned int
  define: __has_include(STR)=__has_include__(STR)
  define: __has_include_next(STR)=__has_include_next__(STR)
  define: __GXX_ABI_VERSION=1011
  define: __SCHAR_MAX__=0x7f
  define: __SHRT_MAX__=0x7fff
  define: __INT_MAX__=0x7fffffff
  define: __LONG_MAX__=0x7fffffffL
  define: __LONG_LONG_MAX__=0x7fffffffffffffffLL
  define: __WCHAR_MAX__=0xffff
  define: __WCHAR_MIN__=0
  define: __WINT_MAX__=0xffff
  define: __WINT_MIN__=0
  define: __PTRDIFF_MAX__=0x7fffffff
  define: __SIZE_MAX__=0xffffffffU
  define: __SCHAR_WIDTH__=8
  define: __SHRT_WIDTH__=16
  define: __INT_WIDTH__=32
  define: __LONG_WIDTH__=32
  define: __LONG_LONG_WIDTH__=64
  define: __WCHAR_WIDTH__=16
  define: __WINT_WIDTH__=16
  define: __PTRDIFF_WIDTH__=32
  define: __SIZE_WIDTH__=32
  define: __INTMAX_MAX__=0x7fffffffffffffffLL
  define: __INTMAX_C(c)=c ## LL
  define: __UINTMAX_MAX__=0xffffffffffffffffULL
  define: __UINTMAX_C(c)=c ## ULL
  define: __INTMAX_WIDTH__=64
  define: __SIG_ATOMIC_MAX__=0x7fffffff
  define: __SIG_ATOMIC_MIN__=(-__SIG_ATOMIC_MAX__ - 1)
  define: __SIG_ATOMIC_WIDTH__=32
  define: __INT8_MAX__=0x7f
  define: __INT16_MAX__=0x7fff
  define: __INT32_MAX__=0x7fffffff
  define: __INT64_MAX__=0x7fffffffffffffffLL
  define: __UINT8_MAX__=0xff
  define: __UINT16_MAX__=0xffff
  define: __UINT32_MAX__=0xffffffffU
  define: __UINT64_MAX__=0xffffffffffffffffULL
  define: __INT_LEAST8_MAX__=0x7f
  define: __INT8_C(c)=c
  define: __INT_LEAST8_WIDTH__=8
  define: __INT_LEAST16_MAX__=0x7fff
  define: __INT16_C(c)=c
  define: __INT_LEAST16_WIDTH__=16
  define: __INT_LEAST32_MAX__=0x7fffffff
  define: __INT32_C(c)=c
  define: __INT_LEAST32_WIDTH__=32
  define: __INT_LEAST64_MAX__=0x7fffffffffffffffLL
  define: __INT64_C(c)=c ## LL
  define: __INT_LEAST64_WIDTH__=64
  define: __UINT_LEAST8_MAX__=0xff
  define: __UINT8_C(c)=c
  define: __UINT_LEAST16_MAX__=0xffff
  define: __UINT16_C(c)=c
  define: __UINT_LEAST32_MAX__=0xffffffffU
  define: __UINT32_C(c)=c ## U
  define: __UINT_LEAST64_MAX__=0xffffffffffffffffULL
  define: __UINT64_C(c)=c ## ULL
  define: __INT_FAST8_MAX__=0x7f
  define: __INT_FAST8_WIDTH__=8
  define: __INT_FAST16_MAX__=0x7fff
  define: __INT_FAST16_WIDTH__=16
  define: __INT_FAST32_MAX__=0x7fffffff
  define: __INT_FAST32_WIDTH__=32
  define: __INT_FAST64_MAX__=0x7fffffffffffffffLL
  define: __INT_FAST64_WIDTH__=64
  define: __UINT_FAST8_MAX__=0xff
  define: __UINT_FAST16_MAX__=0xffff
  define: __UINT_FAST32_MAX__=0xffffffffU
  define: __UINT_FAST64_MAX__=0xffffffffffffffffULL
  define: __INTPTR_MAX__=0x7fffffff
  define: __INTPTR_WIDTH__=32
  define: __UINTPTR_MAX__=0xffffffffU
  define: __GCC_IEC_559=2
  define: __GCC_IEC_559_COMPLEX=2
  define: __FLT_EVAL_METHOD__=2
  define: __FLT_EVAL_METHOD_TS_18661_3__=2
  define: __DEC_EVAL_METHOD__=2
  define: __FLT_RADIX__=2
  define: __FLT_MANT_DIG__=24
  define: __FLT_DIG__=6
  define: __FLT_MIN_EXP__=(-125)
  define: __FLT_MIN_10_EXP__=(-37)
  define: __FLT_MAX_EXP__=128
  define: __FLT_MAX_10_EXP__=38
  define: __FLT_DECIMAL_DIG__=9
  define: __FLT_MAX__=3.40282346638528859811704183484516925e+38F
  define: __FLT_MIN__=1.17549435082228750796873653722224568e-38F
  define: __FLT_EPSILON__=1.19209289550781250000000000000000000e-7F
  define: __FLT_DENORM_MIN__=1.40129846432481707092372958328991613e-45F
  define: __FLT_HAS_DENORM__=1
  define: __FLT_HAS_INFINITY__=1
  define: __FLT_HAS_QUIET_NAN__=1
  define: __DBL_MANT_DIG__=53
  define: __DBL_DIG__=15
  define: __DBL_MIN_EXP__=(-1021)
  define: __DBL_MIN_10_EXP__=(-307)
  define: __DBL_MAX_EXP__=1024
  define: __DBL_MAX_10_EXP__=308
  define: __DBL_DECIMAL_DIG__=17
  define: __DBL_MAX__=((double)1.79769313486231570814527423731704357e+308L)
  define: __DBL_MIN__=((double)2.22507385850720138309023271733240406e-308L)
  define: __DBL_EPSILON__=((double)2.22044604925031308084726333618164062e-16L)
  define: __DBL_DENORM_MIN__=((double)4.94065645841246544176568792868221372e-324L)
  define: __DBL_HAS_DENORM__=1
  define: __DBL_HAS_INFINITY__=1
  define: __DBL_HAS_QUIET_NAN__=1
  define: __LDBL_MANT_DIG__=64
  define: __LDBL_DIG__=18
  define: __LDBL_MIN_EXP__=(-16381)
  define: __LDBL_MIN_10_EXP__=(-4931)
  define: __LDBL_MAX_EXP__=16384
  define: __LDBL_MAX_10_EXP__=4932
  define: __DECIMAL_DIG__=21
  define: __LDBL_DECIMAL_DIG__=21
  define: __LDBL_MAX__=1.18973149535723176502126385303097021e+4932L
  define: __LDBL_MIN__=3.36210314311209350626267781732175260e-4932L
  define: __LDBL_EPSILON__=1.08420217248550443400745280086994171e-19L
  define: __LDBL_DENORM_MIN__=3.64519953188247460252840593361941982e-4951L
  define: __LDBL_HAS_DENORM__=1
  define: __LDBL_HAS_INFINITY__=1
  define: __LDBL_HAS_QUIET_NAN__=1
  define: __FLT32_MANT_DIG__=24
  define: __FLT32_DIG__=6
  define: __FLT32_MIN_EXP__=(-125)
  define: __FLT32_MIN_10_EXP__=(-37)
  define: __FLT32_MAX_EXP__=128
  define: __FLT32_MAX_10_EXP__=38
  define: __FLT32_DECIMAL_DIG__=9
  define: __FLT32_MAX__=3.40282346638528859811704183484516925e+38F32
  define: __FLT32_MIN__=1.17549435082228750796873653722224568e-38F32
  define: __FLT32_EPSILON__=1.19209289550781250000000000000000000e-7F32
  define: __FLT32_DENORM_MIN__=1.40129846432481707092372958328991613e-45F32
  define: __FLT32_HAS_DENORM__=1
  define: __FLT32_HAS_INFINITY__=1
  define: __FLT32_HAS_QUIET_NAN__=1
  define: __FLT64_MANT_DIG__=53
  define: __FLT64_DIG__=15
  define: __FLT64_MIN_EXP__=(-1021)
  define: __FLT64_MIN_10_EXP__=(-307)
  define: __FLT64_MAX_EXP__=1024
  define: __FLT64_MAX_10_EXP__=308
  define: __FLT64_DECIMAL_DIG__=17
  define: __FLT64_MAX__=1.79769313486231570814527423731704357e+308F64
  define: __FLT64_MIN__=2.22507385850720138309023271733240406e-308F64
  define: __FLT64_EPSILON__=2.22044604925031308084726333618164062e-16F64
  define: __FLT64_DENORM_MIN__=4.94065645841246544176568792868221372e-324F64
  define: __FLT64_HAS_DENORM__=1
  define: __FLT64_HAS_INFINITY__=1
  define: __FLT64_HAS_QUIET_NAN__=1
  define: __FLT128_MANT_DIG__=113
  define: __FLT128_DIG__=33
  define: __FLT128_MIN_EXP__=(-16381)
  define: __FLT128_MIN_10_EXP__=(-4931)
  define: __FLT128_MAX_EXP__=16384
  define: __FLT128_MAX_10_EXP__=4932
  define: __FLT128_DECIMAL_DIG__=36
  define: __FLT128_MAX__=1.18973149535723176508575932662800702e+4932F128
  define: __FLT128_MIN__=3.36210314311209350626267781732175260e-4932F128
  define: __FLT128_EPSILON__=1.92592994438723585305597794258492732e-34F128
  define: __FLT128_DENORM_MIN__=6.47517511943802511092443895822764655e-4966F128
  define: __FLT128_HAS_DENORM__=1
  define: __FLT128_HAS_INFINITY__=1
  define: __FLT128_HAS_QUIET_NAN__=1
  define: __FLT32X_MANT_DIG__=53
  define: __FLT32X_DIG__=15
  define: __FLT32X_MIN_EXP__=(-1021)
  define: __FLT32X_MIN_10_EXP__=(-307)
  define: __FLT32X_MAX_EXP__=1024
  define: __FLT32X_MAX_10_EXP__=308
  define: __FLT32X_DECIMAL_DIG__=17
  define: __FLT32X_MAX__=1.79769313486231570814527423731704357e+308F32x
  define: __FLT32X_MIN__=2.22507385850720138309023271733240406e-308F32x
  define: __FLT32X_EPSILON__=2.22044604925031308084726333618164062e-16F32x
  define: __FLT32X_DENORM_MIN__=4.94065645841246544176568792868221372e-324F32x
  define: __FLT32X_HAS_DENORM__=1
  define: __FLT32X_HAS_INFINITY__=1
  define: __FLT32X_HAS_QUIET_NAN__=1
  define: __FLT64X_MANT_DIG__=64
  define: __FLT64X_DIG__=18
  define: __FLT64X_MIN_EXP__=(-16381)
  define: __FLT64X_MIN_10_EXP__=(-4931)
  define: __FLT64X_MAX_EXP__=16384
  define: __FLT64X_MAX_10_EXP__=4932
  define: __FLT64X_DECIMAL_DIG__=21
  define: __FLT64X_MAX__=1.18973149535723176502126385303097021e+4932F64x
  define: __FLT64X_MIN__=3.36210314311209350626267781732175260e-4932F64x
  define: __FLT64X_EPSILON__=1.08420217248550443400745280086994171e-19F64x
  define: __FLT64X_DENORM_MIN__=3.64519953188247460252840593361941982e-4951F64x
  define: __FLT64X_HAS_DENORM__=1
  define: __FLT64X_HAS_INFINITY__=1
  define: __FLT64X_HAS_QUIET_NAN__=1
  define: __DEC32_MANT_DIG__=7
  define: __DEC32_MIN_EXP__=(-94)
  define: __DEC32_MAX_EXP__=97
  define: __DEC32_MIN__=1E-95DF
  define: __DEC32_MAX__=9.999999E96DF
  define: __DEC32_EPSILON__=1E-6DF
  define: __DEC32_SUBNORMAL_MIN__=0.000001E-95DF
  define: __DEC64_MANT_DIG__=16
  define: __DEC64_MIN_EXP__=(-382)
  define: __DEC64_MAX_EXP__=385
  define: __DEC64_MIN__=1E-383DD
  define: __DEC64_MAX__=9.999999999999999E384DD
  define: __DEC64_EPSILON__=1E-15DD
  define: __DEC64_SUBNORMAL_MIN__=0.000000000000001E-383DD
  define: __DEC128_MANT_DIG__=34
  define: __DEC128_MIN_EXP__=(-6142)
  define: __DEC128_MAX_EXP__=6145
  define: __DEC128_MIN__=1E-6143DL
  define: __DEC128_MAX__=9.999999999999999999999999999999999E6144DL
  define: __DEC128_EPSILON__=1E-33DL
  define: __DEC128_SUBNORMAL_MIN__=0.000000000000000000000000000000001E-6143DL
  define: __REGISTER_PREFIX__=
  define: __USER_LABEL_PREFIX__=_
  define: __GNUC_STDC_INLINE__=1
  define: __NO_INLINE__=1
  define: __STRICT_ANSI__=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1
  define: __GCC_ATOMIC_BOOL_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR16_T_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR32_T_LOCK_FREE=2
  define: __GCC_ATOMIC_WCHAR_T_LOCK_FREE=2
  define: __GCC_ATOMIC_SHORT_LOCK_FREE=2
  define: __GCC_ATOMIC_INT_LOCK_FREE=2
  define: __GCC_ATOMIC_LONG_LOCK_FREE=2
  define: __GCC_ATOMIC_LLONG_LOCK_FREE=2
  define: __GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1
  define: __GCC_ATOMIC_POINTER_LOCK_FREE=2
  define: __GCC_HAVE_DWARF2_CFI_ASM=1
  define: __PRAGMA_REDEFINE_EXTNAME=1
  define: __SIZEOF_WCHAR_T__=2
  define: __SIZEOF_WINT_T__=2
  define: __SIZEOF_PTRDIFF_T__=4
  define: __i386=1
  define: __i386__=1
  define: __SIZEOF_FLOAT80__=12
  define: __SIZEOF_FLOAT128__=16
  define: __ATOMIC_HLE_ACQUIRE=65536
  define: __ATOMIC_HLE_RELEASE=131072
  define: __GCC_ASM_FLAG_OUTPUTS__=1
  define: __i686=1
  define: __i686__=1
  define: __pentiumpro=1
  define: __pentiumpro__=1
  define: __code_model_32__=1
  define: __SEG_FS=1
  define: __SEG_GS=1
  define: _X86_=1
  define: __stdcall=__attribute__((__stdcall__))
  define: __fastcall=__attribute__((__fastcall__))
  define: __thiscall=__attribute__((__thiscall__))
  define: __cdecl=__attribute__((__cdecl__))
  define: __GXX_MERGED_TYPEINFO_NAMES=0
  define: __GXX_TYPEINFO_EQUALITY_INLINE=0
  define: __MSVCRT__=1
  define: __MINGW32__=1
  define: _WIN32=1
  define: __WIN32=1
  define: __WIN32__=1
  define: __WINNT=1
  define: __WINNT__=1
  define: _INTEGRAL_MAX_BITS=64
  define: __declspec(x)=__attribute__((x))
  define: __DECIMAL_BID_FORMAT__=1
  define: _REENTRANT=1
  define: DIAG_EXTLINK_TTCHANNEL_MODE_SWITCH
  define: DIAG_SUPPORT_SWITCH
  define: FEA_BUFFER_LEAK_2_SWITCH
  define: FEA_LTE_SWITCH
  define: FEA_N_FREQUENCY_SWITCH
  define: FEA_RLP_SWITCH
  define: FEA_SLEEP_CTRL_SWITCH
  define: FEA_TEST_MOBILE_SWITCH
  define: FEA_TT_LOG_SPOOL_SWITCH
  define: LITTLEENDIAN_SWITCH
  define: OS_FEA_FILE_SYSTEM_SWITCH
  define: PF_FEA_DUALMODE_SWITCH
  define: PF_FEA_TURNKEY_V3
  define: TEMP_DISABLE_RF_DMAD_SWITCH
  define: TEMP_FTUE_CR4055_SWITCH
  define: THREADX_SWITCH
  define: DEBUG_SWITCH
  other: --gcc
  other: --gnu_version=70400
  stdver: c99
  intelliSenseMode: gcc-x64
auto_complete::handle_completion: file:///d%3A/workspace/iNet_1881_CP_H/protocol/L2/u-task/rlc/um/rlc_um_segment.c (775:13)
Offering completion
sending 2 changes to server
Failed to read response from server: 8
textDocument/codeAction: 158
textDocument/didSave
  tag parsing file: D:\WORKSPACE\INET_1881_CP_H\PROTOCOL\L2\U-TASK\RLC\UM\RLC_UM_SEGMENT.C
Request canceled: 152
textDocument/documentSymbol: 160
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/workspace/iNet_1881_CP_H/protocol/L2/u-task/rlc/um/rlc_um_segment.c
Update IntelliSense time (sec): 0
textDocument/hover: 161
IntelliSense client not available, using Tag Parser for quick info.
using Tag Parser for quick info
Database safe to open

**Comment by sean-mcmanus** [comment]
The Microsoft.VSCode.CPP.IntelliSense.Msvc.exe process is crashing when processing rlc_um_segment.c . Are you able to provide an isolated repro for the crash? Are you able to tell if the crash is caused by gcc 8.2 headers or something in your own code? Are you able to attach a debugger before it crashes and get a call stack? You need to set `"symbolSearchPath": "https://msdl.microsoft.com/download/symbols",` in your launch.json to get symbols. If it crashes too fast, you can remove the code contents, attach, and the paste the code to get it to crash.

**Comment by sean-mcmanus** [comment]
Also, I see you're getting "Unable to resolve include path: D:/tools/mingw32/lib/gcc/i686-w64-mingw32/8.2.1/include" and it's parsing the code using gcc 7.4. Double check that your compilerPath is set to the correct mingw compiler and that you're not manually adding system includes to the includePath.

**Comment by suzukajiang** [comment]
@sean-mcmanus You are right, I had set the wrong "C_Cpp.default.systemIncludePath". But when I remove "C_Cpp.default.systemIncludePath", It crashed again. 
My code is in a offline pc, I can't connet to internet. So "symbolSearchPath": "https://msdl.microsoft.com/download/symbols" is unuseful.


Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\mscoree.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\imm32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\msctf.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\vmwsci.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\psapi.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\SysWOW64\api-ms-win-core-synch-l1-2-0.dll'. Cannot find or open the PDB file.
The thread 8088 has exited with code 0 (0x0).
Exception thrown at 0x7684C54F in Microsoft.VSCode.CPP.IntelliSense.Msvc.exe: Microsoft C++ exception: a_cfe_exception at memory location 0x02EEFD4B.
The thread 9812 has exited with code 0 (0x0).
Error - Invalid args, too  big block
Error - Invalid args, too  big block
Error - Invalid args, too  big block
Error - Invalid args, too  big block
Error - Invalid args, too  big block
Exception thrown at 0x0055C204 in Microsoft.VSCode.CPP.IntelliSense.Msvc.exe: 0xC0000005: Access violation reading location 0x0000004A.

**Comment by suzukajiang** [comment]
The code can be compiled successfully, and it can auto complete when I use vscode-clangd.

**Comment by sean-mcmanus** [comment]
We need a call stack and/or a repro in order to investigate a fix. It looks like our parser is crashing.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
