### ISSUE TITLE
Unable to start debugging. Program path 'd:\vscode\c.c' is missing or invalid.

### ISSUE THREAD

**Issue by karpulix** [microsoft/vscode-cpptools#419]
(windows 10)
file d:\vscode\c.c exist in D:\vscode\, it's simple "hello world", I can not understand why there is an error.

launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "miDebuggerPath":"c:/MinGW/bin/gdb.exe",
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/c.c",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
           "miDebuggerPath":"c:/MinGW/bin/gdb.exe",
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "${workspaceRoot}/c.c",
            "processId": "${command.pickProcess}",
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        }
    ]
}

**Comment by sean-mcmanus** [comment]
"Program" is a supposed to be an executable file, not a source file (.c).

**Comment by karpulix** [comment]
Thank! Tell me please, this plugin is able to compile or it only analyzes previously compiled file?

**Comment by sean-mcmanus** [comment]
The C++ extensions provides a C++ debugger and language services (Go to Definition, autocomplete, symbol search, formatting, etc.). We don't provide compile or build services, but you can setup VS code to use a build task, see http://stackoverflow.com/questions/30269449/how-do-i-set-up-vscode-to-compile-c-code , or just build via the command line.

**Comment by pieandcakes** [comment]
@karpulix Do you need additional assistance or is it working for you?

**Comment by pieandcakes** [comment]
Closing this issue. If you still need help please comment/reopen. Thanks
