### ISSUE TITLE
__has_include marked as error

### ISSUE THREAD

**Issue by luni64** [microsoft/vscode-cpptools#4193]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.38.0
- C/C++ Extension Version: 0.25.1
- Compiler: GCC

In the snippet below intellisense marks ```__has_include``` as error but it compiles without problems
```c++
#if __has_include("somefile.h")
#include "somefile.h"  // has constexpr int someVal=1 in it. 
#else
constexpr int someVal = 0;
#endif
```
![image](https://user-images.githubusercontent.com/12611497/64313973-9d7cbb80-cfad-11e9-884d-10732fb0ca1b.png)

**Expected behavior**
Should not be marked as an error

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. The fix should be available in our next Insider release (not sure when yet...might be a couple weeks unless we get more demand to release an Insiders sooner).

**Comment by luni64** [comment]
Thanks a lot

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders . Let us know if it's not working for you.

**Comment by luni64** [comment]
Works for me, thanks a lot
