### ISSUE TITLE
C++20: Support "concepts" syntax

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cpptools#4195]
Support the "concepts" syntax, which is not yet supported.

**Comment by michelleangela** [comment]
The extension's C++ standard features are inherited from Visual Studio. Please upvote this feedback ticket https://developercommunity.visualstudio.com/idea/549930/add-standard-concepts-libary-support.html on Visual Studio to support C++ 20 concepts library.

**Comment by sean-mcmanus** [comment]
Michelle -- that issue is for the cl.exe compiler...there might be another issue tracking IntelliSense, but we usually keep the issues open on our side until we get the fix from VS.

**Comment by tloka** [comment]
Any news on this?

**Comment by sean-mcmanus** [comment]
C++ IntelliSense concepts support is still being worked on. I found a related VS bug at https://developercommunity.visualstudio.com/content/problem/745318/-cpp-lib-concepts-isnt-defined-in-vs-2019-1630-rel.html .

**Comment by elijaharita** [comment]
Concepts Intellisense support is now available with Visual Studio 16.6 Preview 2

**Comment by sean-mcmanus** [comment]
@elijahseedarita Yes, we plan to integrate those changes for our 1.0 release (our soon-to-be-released 0.27.0 won't have those changes yet). Also, it sounded like the support for concepts was not 100% yet.

**Comment by elijaharita** [comment]
@sean-mcmanus Thanks for all your work! =)

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders2 in regards to IntelliSense parsing, but support for the global symbol (tag) parser (i.e. outline view, workspace symbol search, find all references, etc.) hasn't been checked in yet (it should be available in 0.29.0-insiders)...not sure if we need another issue to track that or if we should just keep this issue open until then.

**Comment by sean-mcmanus** [comment]
Actually, it looks like concepts support is still not 100% finished in Intellisense. We'll track the remaining work in https://github.com/microsoft/vscode-cpptools/issues/5444 .

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0

**Comment by OleksandrKvl** [comment]
Not sure whether it's related to this particular issue, I have 1.45.1 VSC and 0.28.1 C++ extension and _concept/requires_ keywords are not highlighted even though VSC clearly knows(they're suggested) that they're C++ keywords.
