### ISSUE TITLE
IntelliSense: no syntax highlight for comments between member initializer list and constructor body

### ISSUE THREAD

**Issue by profnandaa** [microsoft/vscode-cpptools#4197]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10, v1903
- VS Code Version: 1.38.0-insider
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

1. Write a sample C++ code with comments after the initializer list before the constructor body, like in the screenshot below.

2. Check if the comments are syntax-highlighted

**Expected behavior**

The comment is highlighted in green (or the chosen color). Same as in the example below, as done by the Github syntax highlighter.
```cpp
class Vector {
private:
    double* elem;           // elem points to an array of sz doubles
    int sz;
public:
    Vector(int s) :elem{new double[s]}, sz{s}       // constructor: acquires resources
    {
        for (int i = 0; i != s; ++i) elem[i] = 0;   // initialize elements
    }

    ~Vector() { delete[] elem; }                    // destructor: release resources

    double& operator[](int i);
    int size() const;
};

```
**Screenshots**

![_comment_highlighting_bug](https://user-images.githubusercontent.com/261265/64348733-608ce500-cffe-11e9-822e-f5c5d87e9101.jpg)

**Comment by Colengms** [comment]
Hi @profnandaa.  This looks like an issue with syntactic colorization.  The C/C++ extension adds semantic colorization over syntactic colorization, but the later is provided by VS Code.  Specifically, it's provided by TextMate grammar contributed to VS Code by @jeff-hykin.  His repo is here: https://github.com/jeff-hykin/cpp-textmate-grammar  I'd suggest opening the issue there.

**Comment by profnandaa** [comment]
Thanks for the heads-up, [done](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/386) 👍
