### ISSUE TITLE
Issues/questions around the flame icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-cpptools#4198]
It's not 100% clear to me what it is exactly but I'm assume it's indexing/analyzing the current file or something. But anywhere there are a few issues I see with it:

1 - It appears to pop up briefly for every single file that is opened, it appears on the very right of the status bar so it shifts all the items to the left and then back again.

![flame](https://user-images.githubusercontent.com/2193314/64380007-fb78c580-cfe4-11e9-804b-06faba284e30.gif)

Some possible solutions:

- Do not show it straight away but instead only when it's taking longer than expected to analyze (say after 1 or 2 seconds).
- Move it to the very left.

2 - It's red, this is an accessibility issue as contrast is not guaranteed and even on the default theme it's very hard to read.

Some possible solutions:

- Make it the default color
- Request the vscode team to support a special status bar item state that indicates some error or requires attention state that makes the color themable (this is not my area so I'm not sure how feasible this is).

Related: https://github.com/microsoft/vscode/issues/76909

**Comment by bobbrow** [comment]
Funny, I was just talking with @sean-mcmanus about moving the icons over to the left.  I also agree that it pops up too aggressively now.  That was an artifact of a change we did a few months ago that we should revisit.

I feel that \*all\* the icons are harder to see now that they are outlines instead of fills, but that's just my opinion.  (I'm very upset with the recent icon changes, if you can't tell 😉).  We'll consider reverting it back to the status bar default theme color.

**Comment by sean-mcmanus** [comment]
Does this look okay? I tried put the icons most likely to be clicked on the right (i.e. search icon) and the more temporary icons on the left (i.e. flame icon).
![image](https://user-images.githubusercontent.com/19859882/64394048-24ab4d00-d009-11e9-96ad-03ebeffa9e9d.png)

https://github.com/microsoft/vscode-cpptools/pull/4200

We also have issue https://github.com/microsoft/vscode-cpptools/issues/4117 that is tracking collapsing the 3 icons into a single icon that changes between 3 different states.

**Comment by sean-mcmanus** [comment]
FYI, after this change, the icons may not be visible if there's not enough status bar room.

Should it be on the left of the GitLens status bar entry? Putting it on the right of that would reduce the potential of the icon disappearing.

**Comment by sean-mcmanus** [comment]
Or on Insiders:
![image](https://user-images.githubusercontent.com/19859882/64397022-96d55f00-d014-11e9-9b64-31195e89f0cd.png)

I agree with Bob that all the status bar icons look worse...did the VS Code team get any user feedback for the change?

**Comment by sean-mcmanus** [comment]
It looks sort of odd for the icons to appear/disappear with every line change, due to the GitLens extension icon item that changes every line.

**Comment by sean-mcmanus** [comment]
I moved it to the right of the GitLens line changed by info -- it looks a lot better when the line changes (you can't really see the difference in a screenshot).

**Comment by Tyriar** [comment]
Sounds good, you want to minimize the amount of visual noise so to the right of gitlens seems best

**Comment by sean-mcmanus** [comment]
Fixed with 0.26.0.
