### ISSUE TITLE
Find All References child results have incorrect lines if the file is changed after "searching" is done

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4199]
I did Find All References and expanded the file to see the children (refs), but it shows bogus lines that didn't have the reference -- it looked like all the line positions were off by a fixed amount (i.e. the reference was a few lines away at the same column). I don't have a repro yet -- I did the Find All References a second time and it didn't repro. It's possible the database was somehow incorrect after switching branches.

**Comment by sean-mcmanus** [comment]
I reproed it after adding lines of text in the middle of a find all references operation, but my original repro may have been a different bug because the file wasn't opened at all -- actually, it's possible I switched branches in the middle of a Find All References after the file was lexed ("searched").

**Comment by bobbrow** [comment]
It seems that no one is running into this behavior or that they understand the experience.  We won't fix this unless more people vote for it.
