### ISSUE TITLE
vscode-ext: Toggle header/source

### ISSUE THREAD

**Issue by bbenoist** [microsoft/vscode-cpptools#42]
Hi,

It would be nice if the vscode C++ extension had a `Toggle header/source` feature.

![Example](https://raw.githubusercontent.com/bbenoist/vscode-togglehs/master/images/example.gif)

Actually, I've already implemented such a feature [bbenoist/vscode-togglehs](https://github.com/bbenoist/vscode-togglehs) but it would be better if it was directly available from the official extension IMO.

Extension has 939 installs, which means the feature actually has some audience.

**Comment by sridmad** [comment]
We have this on out plate to add to the extension.

**Comment by jhasse** [comment]
I'm using a [different extension](https://marketplace.visualstudio.com/items?itemName=ryzngard.vscode-header-source) which uses `Alt+O` as the shortcut. I think it's a better one then F4, as I don't have to move my hands up ;) This is also Sublime Text's default shortcut :)

**Comment by sridmad** [comment]
Latest update (0.7.0) has source / header toggle. F4 is the short cut. We will think about adding Alt+O as an alternate shortcut.

**Comment by mohsinhasan** [comment]
+1 for Alt+O. Is this something I can configure from a file?

**Comment by sridmad** [comment]
https://code.visualstudio.com/docs/customization/keybindings - see Customizing Shortcuts section

I have added Alt+O as an alternate binding for Switching between header and source. It should appear in 0.8.0 of the extension

**Comment by mohsinhasan** [comment]
Sweet! Much appreciated.

-M
