### ISSUE TITLE
Functions with the same name

### ISSUE THREAD

**Issue by ClarkZhaoHF** [microsoft/vscode-cpptools#4201]
**Describe the bug**
- OS and Version: Windows 7
- VS Code Version: any
- C/C++ Extension Version: 0.24.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**As the workspace has many functions with the same name, the symbol list for functions without a path indicator can not give me a clear choice which is the function I am looking for.**

**Expected behavior**
**The symbol list for function can display its FULL absolute path.**

**Comment by sean-mcmanus** [comment]
I don't understand what you mean by "symbol list". Can you provide more info, such as a screenshot?

I see a path indicator with Go to Symbol in Workspace, although it's a relative path.
![image](https://user-images.githubusercontent.com/19859882/64451450-199ffd80-d099-11e9-8a30-4674eded4598.png)

**Comment by bobbrow** [comment]
We don't plan to show the absolute path in the symbol search results.
