### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of {0}/{1} files confirmed.{2} {0}/{1} files searched.{2}

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4202]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
{0}/{1} files confirmed.{2}
{0}/{1} files searched.{2}

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
We translated this string by assuming the PHs as numeric values. Please check and confirm.

**Comment by Colengms** [comment]
For these strings, the first 2 variables are numbers, and the later is a either a help string (localized separately) or blank.  i.e. 

2/10 files confirmed. To preview results, click the search icon in the status bar.)
5/10 files searched.

**Comment by PDostalek** [comment]
perfect, thanks
