### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "package.c_cpp.command.logDiagnostics.title"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4203]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Log Diagnostics

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
We are not sure whether "Log" is used as a verb or a noun.
Could you clarify this?
Thank you.

**Comment by Colengms** [comment]
Log is a verb in this case.  This command outputs/logs diagnostic information.

**Comment by PDostalek** [comment]
ok, thanks
