### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/ui/settings.html.limit.symbols"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4204]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Browse: limit symbols to included headers

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Please clarify if "limit" here is a verb or a noun. Thanks.

**Comment by Colengms** [comment]
In this string, "limit" is a verb.
