### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/packageManager.failed.web.error"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4205]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
failed (error code '{0}')

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Is this a full string or will it be concatenated? Thanks.

**Comment by Colengms** [comment]
This is a full string, no concatenated.

**Comment by PDostalek** [comment]
ok, thanks
