### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of  0; "dist/src/LanguageServer/nativeStrings.compiler_from_compile_commands"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4207]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Attempting to get defaults from compiler in compile_commands.json file: '{0}'

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Please define the placeholder

**Comment by Colengms** [comment]
In this string, the placeholder will be a path to the compiler we're trying to get defaults from.
