### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/LanguageServer/nativeStrings.compiler_from_compiler_path"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4208]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Attempting to get defaults from compiler in "compilerPath" property: '{0}'

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Please will be the placeholder

**Comment by Colengms** [comment]
In this string, the placeholder will be a path to the compiler we're trying to get defaults from.
