### ISSUE TITLE
Auto-completion is broken

### ISSUE THREAD

**Issue by hia3** [microsoft/vscode-cpptools#421]
Currently auto-completion gives a lot of irrelevant suggestions:

![image](https://cloud.githubusercontent.com/assets/4704208/21468667/ec6cf740-ca2f-11e6-92a8-05c2519cba14.png)

This is how it should work:

![image](https://cloud.githubusercontent.com/assets/4704208/21468669/f15b8528-ca2f-11e6-8117-fdb95921dd4a.png)

**Comment by invokr** [comment]
I have the same problem (Tested on OS X and Linux). Can someone confirm this works on Windows?

**Comment by sean-mcmanus** [comment]
It doesn't work better on Windows. The current behavior is "by design" until the IntelliSense feature is complete.

**Comment by esmirnov** [comment]
@sean-mcmanus do you have estimation for the IntelliSense feature? Is there some workaround to show local (in same file) symbols on top of the list?

**Comment by sean-mcmanus** [comment]
Full IntelliSense is being worked on, but we don't have a release date yet. Variables that are non-local to a function should appear for autocomplete. The "workaround" would be to make whatever variable that is local to a function non-local, i.e. global or file-local scope.

**Comment by bobbrow** [comment]
We are tracking auto-completion with issue #13
