### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/LanguageServer/nativeStrings.include_path_suggestions_discovered"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4210]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
{0} include path suggestion(s) discovered.

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
What will {0} be?

**Comment by Colengms** [comment]
In this string, the placeholder variable will be a number (of suggested include paths).

**Comment by PDostalek** [comment]
thanks
