### ISSUE TITLE
Intellisense DB not updated after a git pull

### ISSUE THREAD

**Issue by RichardFurness** [microsoft/vscode-cpptools#4211]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 remote SSH to Linux
- VS Code Version: latest insiders
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

If I update the code on the remote server e.g. doing a git pull or checking out a new branch, the C intellisense DB isn't updated so e.g. find-all-references won't find new references due to the update.

**To Reproduce**

1. In VSCode, have open the file defining something (say, a function).
2. On the server, pull in changes that introduce a new referenc to the function in another file (not already open in VSCode), using e.g. git pull / checkout new branch.
2. In VSCode, perform find-all-references from the function definition.

**Expected behavior**
The new reference should be found. Instead, it will only be found after I either:
- Open the file with the new reference, OR
- Reset intellisense DB

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Oh, we've had this root problem for a long time -- we ignore file watcher "changed" events.

Doing a Rescan Workspace command is the recommended workaround until we're able to fix this.

A related issue is https://github.com/microsoft/vscode-cpptools/issues/3802 (no file watchers at all outside of the workspace).

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders . Let us know if it's not working for you.
