### ISSUE TITLE
Go to Symbol in Workspace shows duplicate symbols after switching from a WSL to non-WSL config

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4212]
Looks like the database is keeping around duplicate files with different cases, causing Go to Symbol in Workspace to show duplicate results -- it's possible other features could be negatively impacted in other less obvious ways (such as performance).

**Comment by bobbrow** [comment]
I think the problem is caused by a bug in the case-sensitive path handling we do for WSL.  The database is supposed to be cleared when switching out of a case-sensitive configuration.

**Comment by bobbrow** [comment]
We're not really investing much energy into our WSL implementation anymore.  We recommend using VS Code's Remote-WSL extension isntead.
