### ISSUE TITLE
Debugger add configuration not showing C++

### ISSUE THREAD

**Issue by emanspeaks** [microsoft/vscode-cpptools#4217]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 (1809)
- VS Code Version: 1.38.0
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them):

Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 2.0.5
vscode-sqlite | ale | 0.8.0
vscode-django | bat | 0.19.0
vscode-devtools-for-chrome | cod | 0.0.5
vscode-markdownlint | Dav | 0.30.2
python-extension-pack | don | 1.6.0
gitlens | eam | 9.9.3
fortran-ls | han | 0.6.0
text-transformer | jac | 0.0.2
linter-gfortran | krv | 2.1.1
restructuredtext | lex | 114.0.0
MagicPython | mag | 1.1.0
dotenv | mik | 1.0.1
anaconda-extension-pack | ms- | 1.0.1
python | ms- | 2019.9.34911
remote-wsl | ms- | 0.39.5
cpptools | ms- | 0.25.1
powershell | ms- | 2019.5.0
vscode-typescript-tslint-plugin | ms- | 1.2.2
vsliveshare | ms- | 1.0.766
debugger-for-chrome | msj | 4.11.7
vscode-yaml | red | 0.5.2
gitconfig | sid | 2.0.1
vscode-djaneiro | the | 1.4.2
cmake | twx | 0.0.17
vscodeintellicode | Vis | 1.1.9
vscode-icons | vsc | 9.3.0
jinja | who | 0.0.8

- A clear and concise description of what the bug is.

After opening C++ file in a new workspace, trying to add new launch.json file does not provide options related to C++ environment in the first palette dropdown.  If I click another option for another language to create the file and click the Add Configuration button, they do appear in that IntelliSense window.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Create new workspace
2. Add *.cpp file (simple helloworld.cpp will suffice)
```
#include <stdio.h>

int main()
{
  printf("hello, world");
}

```
3. Open palette and chose "Debug: open launch.json"
4. No C++ options appear

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
On the Explorer panel, `main()` appears in the Outline panel, which seems to imply the extension has indeed been activated.  Successive attempts at adding a configuration do not cause it to eventually appear; it just never appears at all, so not exactly a recurrence of #1287.

**Comment by pieandcakes** [comment]
@WardenGnaw Can you investigate?

**Comment by WardenGnaw** [comment]
Something seems to have changed in VS Code 1.38.0.

Created an issue at https://github.com/microsoft/vscode/issues/80601

**Comment by WardenGnaw** [comment]
Closing as external issue.

The VS Code team says they are investigating the issue. 

You should still be able to get configuration snippets with `Ctrl + Space` or using the `Add Configuration..` button.

**Comment by emanspeaks** [comment]
Thanks!  Tracking the other issue.
