### ISSUE TITLE
some C++17 structured binding declaration breaks syntax highlighting

### ISSUE THREAD

**Issue by Blaok** [microsoft/vscode-cpptools#4219]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 18362
- VS Code Version: 1.38.0
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them): None (and yes)
- A clear and concise description of what the bug is.

With C++17 structured binding declaration, syntax highlighting can be broken in the rest of the scope:

![image](https://user-images.githubusercontent.com/4057569/64562333-a2b96d80-d301-11e9-87b7-59d15d390e58.png)

Note that the `&` after `auto` is significant. Without it highlighting is just fine.

![image](https://user-images.githubusercontent.com/4057569/64562364-b533a700-d301-11e9-9aa9-d4f1f64c6afd.png)

**To Reproduce**

1. Download vscode
2. Install this extension
3. Create a file called `foo.cpp`
4. Copy and paste the following code

```C++
int main() {
  auto& [a, b, c] = some_tuple;
  // starting from here highlighting is broken
  int some_int = 0;
}
// highlighting works again
auto& [a, b, c] = some_tuple;
// broken again
int some_int_global = 0;
void new_scope() {
  // opening a new scope makes highlighting work again
  int some_int = 0;
}
```

**Expected behavior**

Syntax highlighting works in all scopes.

**Screenshots**

Already pasted :)

**Additional context**

The settings in `c_cpp_properties.json` don't seem to change this behavior. The above code doesn't compile but complete, working code also has the same problem.

**Comment by matter123** [comment]
@Blaok this issue is because vscode uses an old version of the upstream textmate grammar (syntactical highlighting). Installing the latest version (https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax&ssr=false) should fix the issue.

Related issue https://github.com/jeff-hykin/cpp-textmate-grammar/issues/224

**Comment by Blaok** [comment]
@matter123 Indeed, thanks! I assume this will be automatically fixed when vscode updates its grammar from the upstream so I'm closing this issue.
