### ISSUE TITLE
The C++ extension should not activate on startup

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-cpptools#422]
The C++ extension activates on startup, e.g.,
```json
	"activationEvents": [
		"*"
	]
```
A language extension must only activate when a language specific artifact or command is executed.

**Comment by sean-mcmanus** [comment]
@egamma: Actually, the "*" is "by design" -- we re-write our package.json's activationEvents after the initial one-time download/install step has completed:
manifestObject.activationEvents = [
                "onLanguage:cpp",
                "onLanguage:c",
                "onCommand:extension.pickNativeProcess",
                "onCommand:C_Cpp.ConfigurationEdit",
                "onCommand:C_Cpp.ConfigurationSelect",
                "onCommand:C_Cpp.SwitchHeaderSource",
                "onCommand:C_Cpp.UnloadLanguageServer",
                "workspaceContains:.vscode/c_cpp_properties.json",
                "onDebug:cppdbg",
                "onDebug:cppvsdbg"
            ];
