### ISSUE TITLE
Find reference wongly state "Not a reference"

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-cpptools#4223]
**Type: LanguageService**

**Describe the bug**
A function, "HardToTrade2", is referenced but "Find all reference" label it as [Not a reference]
Meanwhile, the find all in files can locate it correctly.
**Screenshots**

![image](https://user-images.githubusercontent.com/8154646/64579635-2765c380-d3b6-11e9-81e4-2da1425dca3f.png)
 Extension version: 0.25.1
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-957.10.1.el7.x86_64

**Comment by sean-mcmanus** [comment]
I'm not able to repro this bug. Are you able to provide more details? The code I used was
```
class ContractFactorClass
{
public:
    bool HardToTrade2(const bool isBid, const int priceTk, const int hedgeBufferTk) const {
        return false;
    }

    void func()
    {
        ContractFactorClass ContractFactor;
        bool isBid = false;
        int priceTk = 0;
        ContractFactor.HardToTrade2(isBid, priceTk, 2); // Find All Refs works here.
    }
};
```
Is your scenario doing something more complicated that could cause our type checking to fail? Does Go to Def on "HardToTrade2" give multiple definitions or is there class inheritance involved? We're working on fixing a known bug with methods in base class not matching to references in subclass methods.

**Comment by Victsz** [comment]
Sorry it might be a correct behavior, I found the caller is a template class of ContractFactor,  it is like
```
<template class T>
class Contract{
T factor;
void func(){
 factor.HardToTrade2()
}
}
 
Contract<ContractFactor> c;
c.func()
```
--------------------------------------------
I know most IDE cannot find this kind of reference, so sorry for the inconvenience.

**Comment by sean-mcmanus** [comment]
By default, VS gives the same result, but after you use the UI to set T=ContractFactor, then it confirms the references.

We're tracking adding support for template intellisense with https://github.com/microsoft/vscode-cpptools/issues/1946 .
