### ISSUE TITLE
namespace "std" has no member "cout"

### ISSUE THREAD

**Issue by Schokocrossi** [microsoft/vscode-cpptools#4228]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.38.0
- C/C++ Extension Version: 0.25.1
- I am trying to setup clang in Visual Studio Code on Windows 10. If I write a simple HelloWorld program, IntelliSense tells me that `namespace "std" has no member "cout"` even though I included `<iostream>` and chose `"clang-x64"` as intelliSenseMode. According to similar issues on this page this should have been fixed with the versions I am using.

**To Reproduce**
Main:
![main](https://user-images.githubusercontent.com/9406913/64696112-e8ab3880-d49d-11e9-85dd-b03415d2d27f.PNG)

c_cpp_properties:
![prop](https://user-images.githubusercontent.com/9406913/64696118-ea74fc00-d49d-11e9-84c5-c630ab2b6db0.PNG)

I am not sure if I have to include something in this file, because the auto-instantiation for c_cpp_properties does not do that either.

I am grateful for any help!

**Comment by sean-mcmanus** [comment]
We're tracking our lack of support for clang-cl.exe with clang-x64 mode with https://github.com/microsoft/vscode-cpptools/issues/3906 .

In the mean time, you can try setting the compilerPath to "" and manually specifying the includePath to be whatever clang-cl.exe outputs when you use ""C:/Program Files/LLVM/bin/clang-cl.exe" -TP -v -E -Xclang -dM nul"

for example

```
                 "C:\\Program Files\\LLVM\\lib\\clang\\8.0.0\\include",
                    "C:\\VS-2019\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\include",
                    "C:\\VS-2019\\VC\\Tools\\MSVC\\14.16.27023\\include",
                    "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um",
                    "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\ucrt",
                    "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\shared",
                    "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\um",
                    "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\winrt",
                    "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\cppwinrt"
```

But it looks like the intelliSenseMode needs to be set to "msvc-x64" until we're able to fix it to use the correct clang mode flags.

Using the defines that clang-cl.exe outputs may not be necessary.

**Comment by Schokocrossi** [comment]
Thank you for your answer! Sadly, specifying the include path did not work for me so i'll use "msvc-64" and keep an eye on #3906 (closing this issue then)
