### ISSUE TITLE
browse.VC.db file is not created.

### ISSUE THREAD

**Issue by sunzhec2702** [microsoft/vscode-cpptools#423]
Hi,

My situation is that I have to install the vs/cpptools offline. After downloaded and installed the extension successfully, the database file didn't show up. And I cannot navigate the code neither.
My vs code is 1.8 and cpptools is 0.9.3.

Also I saw a message when I opened vs.
"
Update c/c++ dependencies...
Downloading package 'c/c++ language components(linux) Fail at stage: downloadPackages' 
"
It failed as I didn't have access to Internet.

My questions are
1. Is the update necessary for the navigation?If yes, is it possible for me to download and install it offline?
2. Is there a way I can create the database manually?

Thanks a lot.

**Comment by sean-mcmanus** [comment]
The update is necessary. It downloads OS-specific components. Offline downloading/installing isn't officially supported, but you may be able to work around this via downloading/installing the extension and updates on a computer with internet access and then copying over the updated files/folders (e.g. on Windows: install.lock, package.json, bin/Microsoft.VSCode.CPP.Extension.exe, LLVM, debugAdapters/vsdbg).

**Comment by sunzhec2702** [comment]
Hi Sean,

Thanks for the reply. My OS is ubuntu :(
I've copied the whole folder under /usr/shared/code from a Internet access computer(VS/CppTools works well) to my offline computer. 
But it didn't work neither. VS still try to down&update c/c++ dependencies.


BTW, I've already offline installed the cpptools extension successfully. 

Is there still a way to WAR this issue in Ubuntu?

Thanks a lot.

**Comment by sean-mcmanus** [comment]
The workaround should work on Ubuntu too. You need to copy the extension files, which should be in a location like ~/.vscode/extensions/ms-vscode-cpptools-0.9.3. It sounds like you are copying the vs code binaries and not the extension binaries. The existence of the install.lock file will prevent the download.

**Comment by sunzhec2702** [comment]
Hi Sean,

Thanks! I thought it was updating the component of vs code itself since the extension was installed successfully already. 
Now I copied the folder ~/.vscode/extensions/* as you told me. Everything goes well! 
Thanks a lot!
