### ISSUE TITLE
Ctrl + mouse click on a function opens its definition, but with its filepath in uppercase. 

### ISSUE THREAD

**Issue by frenetorp** [microsoft/vscode-cpptools#4232]
Press "File" -> "Open Folder..". 
Open a network folder (Network File System), for example: 
`\\files.example.com\home\emma\git\example_project`
The example_project is written in C, with a header-file (example.h) and a c-file (example.c). 
Open the header-file and press "ctrl + left click" on a function in order to bring up its defenition located in the c-file. 
The c-file will now open in the vscode editor, but its filepath will be in uppercase. 
Opening the c-file from the "EXPLORER" will open another copy of it, but with a lowercase filepath instead (the correct casing). 
Right-clicking and pressing "Reveal in Explorer" on both of these c-files will open the exact same file. 
Also, having opened both of these c-files confuses the Source Control, causing the same project to show up twice under the "SOURCE CONTROL PROVIDERS" tab. 

I'm not sure if this issue is caused by opening an NFS folder, but that's the only common factor I could find. This doesn't happen for local folders.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I repro the bug.

**Comment by bobbrow** [comment]
We think we might have fixed this.  Can you try again with the latest version of the extension?  If it's not fixed, we can reopen the issue.
