### ISSUE TITLE
[cppvsdbg] requireExactSource option is not recognized by launch.json

### ISSUE THREAD

**Issue by guusw** [microsoft/vscode-cpptools#4233]
Type: Debugger

Sometimes when debugging my application (UE4 project) the symbols seem to not match the source files. Although I would still like to debug my application.

The debug  console suggests that I can disable this source file matching in my launch.json by adding `"requireExactSource":false`, however the settings' json linting tells me this option is not allowed.

Extension version: 0.25.1
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362

**Comment by pieandcakes** [comment]
@guusw We will take a look. thanks
