### ISSUE TITLE
Linux 32-bit support

### ISSUE THREAD

**Issue by alex-che** [microsoft/vscode-cpptools#424]
Currently several extension binaries are 64-bit only, and do not work on Linux 32-bit. Is it possible to add support for Linux 32-bit?

**Comment by je-so** [comment]
Same problem here. Symbol information is not generated on 32-bit systems. Any plan to fix it?

**Comment by sean-mcmanus** [comment]
We haven't decided yet whether to add support for 32-bit systems. The number of users on 32-bit Linux systems is a very small percentage; however, it still seems to be the 2nd most common "blocker", followed by the glibc 2.18 or newer requirement.

**Comment by randombenj** [comment]
Same problem, 32 bit support would be nice.

**Comment by sean-mcmanus** [comment]
Why are people running 32-bit Linux instead of 64-bit Linux? What is the barrier to switching?

**Comment by randombenj** [comment]
We develop c++ in a lxc container, with some real time c++ application framework which we can only use as a 32 bit library.

**Comment by alex-che** [comment]
@sean-mcmanus, I develop for several target platforms. Some of my build environment is Windows and some is Linux. So I use Windows as my host OS, running Linux in a virtual machine when needed. To minimize memory and storage load when running the virtual machine, I opted to go 32-bit Linux. It worked without any cons so far.

**Comment by yuyoyuppe** [comment]
+1

**Comment by randombenj** [comment]
Any plans whether this will be fixed at all?

**Comment by sean-mcmanus** [comment]
Not yet.

**Comment by wintersf** [comment]
+1 for 32bit support. 
We are building an embedded application that has older tools only available on 32-bit and a large effort to update full toolchain.

**Comment by agendek78** [comment]
+1 for 32bit. Many users are running linux in virtual machines and don't want to waste resources for 64bit linux installation.

**Comment by randombenj** [comment]
Are there some pain points in releasing the extension as 32 bit?

**Comment by sean-mcmanus** [comment]
@randombenj The main pain point is our code doesn't compile/link without errors for a 32-bit Linux target. And our telemetry showed the 32-bit Linux usage was between 3-4% so it wasn't a high priority issue to solve.

**Comment by wjd19900102** [comment]
By now ,some developers about the embedded system, need the 32 bit on the Linux. We need support the 32bit.

**Comment by sean-mcmanus** [comment]
@wjd19900102 I believe embedded systems developed can be done on 64-bit Linux too, even if the target embedded system is 32-bit. We still plan to add 32-bit support, but we're not sure when.

**Comment by bobbrow** [comment]
This has been addressed with version 0.14.4
