### ISSUE TITLE
[other extension] lldb custom formatters are not working in VS Code

### ISSUE THREAD

**Issue by mbargiel** [microsoft/vscode-cpptools#4240]
Type: Debugger

OS: macOS Mojave (10.14.6)
Visual Studio Code Version 1.38.1
ms-vscode.cpptools 0.25.1
Also present: vadimcn.vscode-lldb 1.3.0

We have custom LLDB formatters defined `~/.lldbinit`. They are picked up fine by `lldb` in the shell or Xcode, but not by VS Code.

I found issue https://github.com/microsoft/vscode-cpptools/issues/1902 which is from 2018, which listed configuring `"setupCommands"` in `launch.json` as a workaround. That doesn't work for me, however if I run the command `"command source ~/.lldbinit" manually in the Debug Console after starting the debugger, then it works.

Expected: The `~/.lldbinit` should automatically be picked up (as described in https://lldb.llvm.org/use/tutorial.html) without requiring a workaround. Barring that, I would at least expect the workaround to work... (Since people reported it as working in issues #1902 above, this may actually be a regression.)

**Comment by pieandcakes** [comment]
can you post your launch.json with you using the `setupCommands` and an `engineLog`?

**Comment by mbargiel** [comment]
Hi @pieandcakes,

I initially had this in my launch config:
```
		{
			"name": "C++ Launch Editor (LLDB)",
			"type": "lldb",
			"expressions": "native",
			"request": "launch",
			"osx": {
				"program": "${workspaceRoot}/build/MacEditor/MyApp.app/Contents/MacOS/MyApp"
			},
			"stopOnEntry": false,
			"cwd": "${workspaceRoot}"
		},
```
The custom formatters do get imported and loaded if I run `command source ~/.lldbinit` in the Debug console.

With "setupCommands":
```
		{
			"name": "C++ Launch Editor (LLDB)",
			"type": "lldb",
			"expressions": "native",
			"request": "launch",
			"osx": {
				"program": "${workspaceRoot}/build/MacEditor/MyApp.app/Contents/MacOS/MyApp"
			},
			"stopOnEntry": false,
			"cwd": "${workspaceRoot}",
			"setupCommands": ["command source ~/.lldbinit"]
		},
```
(I also tried with an absolute path. No go.)

**Comment by mbargiel** [comment]
I have no idea what or where a `engineLog` is though.

Also, I just noticed that VSCode autocomplete just offered to use `"initCommands"` rather than `"setupCommands"` and that actually worked (i.e. replace "setupCommands" with "initCommands" in the second snippet above).

**Comment by mbargiel** [comment]
Soooo, I have a workaround now, but I guess this is one of those things that should **Just Work™️**, considering the LLDB documentation mentions that's precisely the way to execute custom LLDB commands, and this is respected by other IDEs. (In fact I'm pretty certain that used to work with VS Code as well, but I couldn't say when it stopped working... Perhaps I'm just misremembering.)

In any case, thank you for looking into it and seeing if this is indeed a regression.

**Comment by pieandcakes** [comment]
@mbargiel I see the confusion. You are actually not using our extension. The `"type":` field tells me that you are using a different extension. Our `type` field for this extension is `cppdbg`. You may want to identify which extension you are using and post to their github repo.

Like you posted above you have another `lldb` extension installed and i suspect you are using their extension for debugging.

**Comment by mbargiel** [comment]
Aaaaah, it would certainly help if I directed this to the right people. Thanks! And sorry for the confusion. I'll close this for now.

**Comment by pieandcakes** [comment]
We also provide debugging support but the configuration is different. Let me know if you need any other help.
