### ISSUE TITLE
System can't find headers despite setting all the settings.

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode-cpptools#4241]
Issue Type: <b>Bug</b>

Frustratingly, no matter what I do, I keep getting these header errors popping back up.

I set includePath, browsePath, etc etc. to C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/include/** because for some odd reason, when using clang-cl, VSCode Intellisense dies. Setting this worked for a while, then stopped working again.

There are apparently millions of interacting settings regarding this and it's very very confusing. Documentation and text in-program only adds to the confusion. For example, the blurb for Include Path when opening C/C++ Configurations GUI says "If on Windows with Visual Studio installed, or if a compiler is specified in the compilerPath setting, it is not necessary to list the system include paths in this list." But that doesn't seem to be the case when it's set to clang ""C:/Program Files/LLVM/bin/clang.exe". Nor does setting compiler_commands.json work.

Extension version: 0.25.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (25.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
We still have work to do to improve the "clang-cl.exe" scenario. Can you try setting your intelliSenseMode to msvc-x64 and removing other system includes, except maybye the clang include path? Using `"**"` with system include paths is not recommended because `"**"` is order independent, which can break system include paths that require a specific ordering.

See https://github.com/microsoft/vscode-cpptools/issues/4228 and https://github.com/microsoft/vscode-cpptools/issues/3906 .

**Comment by danielmrussell** [comment]
Honestly, I tried that and everything I could think of. The error is
random. It sometimes disappears for a little bit (squiggles go away) but
comes back quickly if you look at it wrong.

This is with cl.exe clang.exe, etc. This is with removing all includes
listed in the configuration editor, with them in there, etc. Nothing seems
to reliably fix this. :(

I didn't understand your comment: Using "" with system include paths...

Do you mean blank strings? I don't know where the blank string is which is
the problem The error message mentions a blank string but not where it's
from so I don't know what setting is blank that shouldn't be.

I set includePath, as well as unsetting it. Doesn't matter. Error remains.

**Comment by danielmrussell** [comment]
After some more testing, it seems that building the project when Clang kit
is selected in CMake Tools induces the squiggles. So if I open Code, they
might not be there at first, but if switch to Clang kit, and then hit Cmake
Tools build button, they appear.

I attached screenshots to show what is happening.

**Comment by danielmrussell** [comment]
Here is my current c_cpp_properties.json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/Program Files/LLVM/include/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "",
            "cStandard": "c11",
            "cppStandard": "c++20",
            "intelliSenseMode": "msvc-x64",
            "configurationProvider": "vector-of-bool.cmake-tools",
            "compileCommands": "",
            "browse": {
                "path": [],
                "limitSymbolsToIncludedHeaders": true
            },
            "compilerArgs": []
        }
    ],
    "version": 4
}

**Comment by danielmrussell** [comment]
Okay. Setting configurationProvider to blank worked.

I hope that doesn't screw everything else up.

**Comment by sean-mcmanus** [comment]
Yeah, you only would want to set that configurationProvider if you have the CMake Tools extension property configured. The configuration provider will cause the other settings in the c_cpp_properties.json to be ignored and use the settings the configuration provider provides.

**Comment by Colengms** [comment]
I believe this should be addressed, as of 0.26.3-insiders, as previously we were not probing clang-cl correctly.

**Comment by Colengms** [comment]
Hi @danielmrussell .  Since your config refers to CMake Tools as the configuration provider, that would override all other fields of that config with data returned from CMake Tools.  I believe we've addressed the scenario of using clang and CMake Tools on Windows (which selects clang-cl.exe).  Note that when switching configurations in CMake Tools you will need to run `CMake: Configure` in order for that info to be delivered to the C/C++ extension.  (On launch, it can configure automatically if using `cmake.configureOnOpen`).

Closing the issue.  If your issue is not addressed, please let us know.
