### ISSUE TITLE
Poorly coded error message leaves user stumped as to what to fix... effects header visibility to the extension.

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode-cpptools#4242]
Issue Type: <b>Bug</b>

See screenshot in link.
https://ibb.co/cT4VXvV

I don't know how to reproduce this because I don't know how the error got generated, what is generating it or where to fix it. What setting is the source of this? Wish I knew!

Extension version: 0.25.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (25.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
It looks like you don't have a workspace folder open and you're it's trying to use compile_commands.json, maybe because you have C_Cpp.default.compileCommands set? Are you able to figure out the repro conditions?

**Comment by danielmrussell** [comment]
I have been unable to pinpoint minimum conditions, because I unset those
things and still get the same error under all conditions I have tried.
Obviously I am confused and don't understand the overall system. I find
there to be so many moving parts and overlap in settings that it's mind
boggling sometimes. I am trying to sort it out and will attempt to pin this
down further.

But regardless, I'm much more interested in submitting the error message as
a bug report, as error messages that fail to direct you to where to look
are basically useless imo.

**Comment by danielmrussell** [comment]
Sorry, I should add I do have a workspace folder open and a .vscode folder
in it and c_cpp_properties.json.

**Comment by sean-mcmanus** [comment]
The string `""` is supposed to be a path to your compile_commands.json. Do you know how you're using compile_commands.json?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
