### ISSUE TITLE
Extermely slow intellisense 

### ISSUE THREAD

**Issue by ciraci** [microsoft/vscode-cpptools#4244]
Issue Type: <b>Bug</b>

Editing a C file, change the type of a variable lets call it Key from one struct to another struct. This causes an error in some other line of the function. To fix the problem, I type . after Key in that line. Intellisense pops up, I select the struct attribute I want to add, lets call it InternalKey. Now VsCode is unresponsive for a long time (vscode cpu usage shoots upto %16). And then changes the code to Key.InternalKey.

Extension version: 0.25.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.15.0-62-generic

**Comment by sean-mcmanus** [comment]
I'm not able to repro it. Do you have any `#include` in your code? Can you do a C/C++: Log Diagnostics with that active and see what settings are being used? What process is using the CPU? Can you attach a debugger to that process to what the call stack is? Can you [enable debug logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) to see what messages occur after the unresponsiveness?

I used

```
typedef struct A
{
    int i;
} A;

typedef struct B
{
    int InternalKey;
} B;

int main()
{
    B Key;
    Key.InternalKey;
}
```

Originally with "A Key; Key.i;".

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
