### ISSUE TITLE
F12 go to def sometimes not working for class member function

### ISSUE THREAD

**Issue by coroner4817** [microsoft/vscode-cpptools#4247]
Version info:
Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.25.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:51:09.716Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic

It sometimes works sometimes not. I see this issue in a no compiled error project.

I don't know how IntelliSense works. But I guess it's base on the current code base and doesn't necessary need to have the code compiled. So I provided this minimal repro for you to test.
F12 on the both `fun` doesn't lead me to the right line. 

```
int main()
{
  fun(2, 2);
}

bool Test::foo(float f) {
  // just a comment
  fun(a, b);
}

void Test::fun(int a, int b) {}
```
BTW another fun part is if you remove the `// just a comment` it will works again

**Comment by sean-mcmanus** [comment]
I don't repro the problem. Go to Def on the fun() calls go to Test::fun(). It gives me squiggles for the missing classes. Our Go to Def code ends up falling back to our Tag Parser due to the IntelliSense compilation errors.

**Comment by sean-mcmanus** [comment]
Okay, I repro it now -- it repros on Linux, but not Windows.

Actually, it repros on Windows in certain cases and it repros with VS.

**Comment by sean-mcmanus** [comment]
The fact that the behavior changes without the comment or not is odd, but it seems like the behavior is somewhat undefined because the code doesn't compile. I've filed a VS bug at https://developercommunity.visualstudio.com/content/problem/734280/go-to-def-doesnt-work-in-certain-strange-condition.html , but I'd suspect they may not decide to fix it.

**Comment by coroner4817** [comment]
But I do see this issue in a compiled project. I just provide a minimal repro case here.
I also see the issue with this Intellisense extension: https://marketplace.visualstudio.com/items?itemName=austin.code-gnu-global

I start to struggle with this go to def since recent vscode update. Before that it always works fine.

**Comment by sean-mcmanus** [comment]
Are you able to give more sample code that repros the issue with code that compiles?

**Comment by coroner4817** [comment]
@sean-mcmanus Sorry I tried but I cannot repro with simple compiled code

But one thing is that in my compiled project, there is a comment right on previous line of the function call. If I remove it will work. So it's the comment that mess up.

**Comment by bobbrow** [comment]
The Visual Studio ticket linked to this issue was closed without a fix. Unfortunately, this means that a fix will not make it into VS Code either.
