### ISSUE TITLE
/usr/include always included

### ISSUE THREAD

**Issue by PatrikMoberg** [microsoft/vscode-cpptools#425]
"/usr/include" is included in include path even when path explicit set to a different custom path. Host is Linux.

Version used: 0.9.3

**Comment by sean-mcmanus** [comment]
I believe the problem is that we don't currently remove "stuff" from the browse engine database after paths like "/usr/include" are removed. A workaround should be to delete the .browse.vc.db or change the databaseFilename property in c_cpp_properties.json.

**Comment by PatrikMoberg** [comment]
Deleting the .db did the trick as a work around, thanks!
