### ISSUE TITLE
value of miDebuggerPath is invalid

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/vscode-cpptools#4250]
Type: Debugger

I have the following line in launch.json ...

"miDebuggerPath": "C:\\MinGW64\\bin\\gdb",

When i press F5 I get 'unable to start debugging. The value of miDebuggerPath is invalid.

I don't see any way to add an image to show you that this is the correct path. But this is a copy of the Explorer path ...

C:\MinGW64\bin

**Comment by PhantomGamers** [comment]
Try using double backslashes

`"C:\\MinGW64\\bin\\gdb.exe"`

**Comment by Gavin-Williams** [comment]
Yes, that's it thank you. And i see I can use forward slash, so that's preferable for me.

**Comment by mollychen12** [comment]
I encountered the same error,and when I change as using double backslashed,it does't work ,confused~
