### ISSUE TITLE
Type not found when global variable has the same name as its type

### ISSUE THREAD

**Issue by q009** [microsoft/vscode-cpptools#4251]
**Type: LanguageService**

Suppose we have a type called 'foo'.
If we try to define a global variable, of both type and name 'foo', IntelliSense will assume the type token refers to the variable itself, not type name. As a result, it will complain that 'foo' does not name a type.

The issue does not appear to happen when the definition exists within a block (i.e. a function).

Screenshot of the problem: https://i.imgur.com/HtHwizM.png
If we name the variable different than the type: https://i.imgur.com/o3dW6ok.png
When in a function: https://i.imgur.com/M08KY5j.png

- OS and Version: Windows 10, version 1803
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.25.1

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug with VS at https://developercommunity.visualstudio.com/content/problem/737747/cc-intellisense-error-type-not-found-when-a-global.html .

**Comment by bobbrow** [comment]
This issue was closed as "lower priority" in Visual Studio so unfortunately we won't be seeing a fix for it in VS Code either.
