### ISSUE TITLE
Warn against implicit type casts from int to bool or long double to long long

### ISSUE THREAD

**Issue by GaurangTandon** [microsoft/vscode-cpptools#4252]
I believe the following code snippets should produce at least a warning squiggle (wasted quite a lot of time today on them):

1. `long long a = 5.1;`
2. `bool a = 2;`

Both of which are clearly wrong and result in loss of information.

More concretely, I wish if VS Code CPP Tools would be able to flag such expressions as warnings. How to enable this feature, if it is already present? If not present already, can it be added? Clion has this feature and it is quite useful.

**Comment by sean-mcmanus** [comment]
You may be able to configure your compiler to give the warnings when you build.

**Comment by GaurangTandon** [comment]
@sean-mcmanus I am sorry but I do not know how to do that. Could you please explain how to?

**Comment by sean-mcmanus** [comment]
What compiler are you using?

**Comment by GaurangTandon** [comment]
I am using `gcc 7.4.0`.

**Comment by sean-mcmanus** [comment]
You can try using -Wconversion -- see https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html .

warning: conversion to 'long long int' alters 'double' constant value [-Wfloat-conversion]
warning: conversion to 'int' from 'long long int' may alter its value [-Wconversion]

We're tracking warning support with IntelliSense at https://github.com/microsoft/vscode-cpptools/issues/828 .
