### ISSUE TITLE
vscode unable to debug

### ISSUE THREAD

**Issue by Daisy-Shi** [microsoft/vscode-cpptools#4255]
Type: Debugger
<Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
Stopped due to shared library event (no libraries added or removed)
Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.>

I tried to debug a series of code files in vscode, but it output the result directly.

**Comment by pieandcakes** [comment]
Please post your `launch.json` and which platform you are on and any additional information. This is not enough information to act on. Per the message above, it looks like its stopping on a shared library load event. 

You can try and change your `solib` event setting to not stop for `gdb`. A quick search online gives me this [document](https://visualgdb.com/gdbreference/commands/set_stop-on-solib-events) that explains what is happening.
