### ISSUE TITLE
Git: Clone

### ISSUE THREAD

**Issue by 10CIrwin1** [microsoft/vscode-cpptools#4256]
Issue Type: <b>Bug</b>

I am trying to use Git:Clone and I am receiving the message "Cannot be found"

Extension version: 0.25.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.82GB (1.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
The command [Git:Clone](https://code.visualstudio.com/Docs/editor/versioncontrol#_cloning-a-repository) is a feature by VS Code and not the C/C++ extension. Please file the bug at https://github.com/microsoft/vscode/issues.
