### ISSUE TITLE
cpp.hint does not seem to have any effect

### ISSUE THREAD

**Issue by niklas-ourmachinery** [microsoft/vscode-cpptools#4257]
**Type: LanguageService**

**Describe the bug**

- Windows.
- VS Code 1.38.1
- C/C++ 0.25.1

An undefined macro in a function definition causes Intellisense errors. Even if I add the macro to `cpp.hint`, I still get the error. It doesn't seem like `cpp.hint` is parsed at all.

**To Reproduce**

1. Open VS Code in an empty folder.
2. Create a file `blorg.c` with the text `int main() KORV { int x = 3; }`.
3. Create a file `cpp.hint` with the text `#define KORV`.
4. Type some character into `blorg.c` and save, try `Reset Intellisense Database`, etc.
5. Notice that the error persists.

See screenshot:

![image](https://user-images.githubusercontent.com/26548514/64997330-42907180-d895-11e9-9d15-720d706aa39d.png)

**Comment by sean-mcmanus** [comment]
cpp.hint is not for IntelliSense -- it's for the "tag parser" or global symbols. For IntelliSense, you want to add the defines to the "defines" section of c_cpp_properties.json (or an equivalent location).

You still may want to keep the cpp.hint if the macro breaks the tag parser (i.e. symbols in the Outline view).

**Comment by niklas-ourmachinery** [comment]
Got it! Thank you!
