### ISSUE TITLE
Goto Definition do not work appropriately

### ISSUE THREAD

**Issue by liuyuxun** [microsoft/vscode-cpptools#426]
# when i use the ‘goto definition’ 
![image](https://cloud.githubusercontent.com/assets/3021095/21561076/b5f9736a-cea2-11e6-8ac9-497e3bdb29db.png)
# I get this window
![image](https://cloud.githubusercontent.com/assets/3021095/21561106/26b2048c-cea3-11e6-998b-06a0f4894f9b.png)
## this is just a simple sample，i think the nearest definition is the appropriate one

**Comment by sean-mcmanus** [comment]
It appears like you are using Go to Definition on a local variable and are getting other global variables instead. We don't currently support Go to Definition on local variables.

**Comment by liuyuxun** [comment]
yes this is the issue.
but ,is there any plan to support this?
vscode is the lightly and best appliation that i've have ever used to review codes on mac
the other ides are either too heavy or too slow for big projects ,for example the uboot and linux kernel projects in embed development 

Thanks for your attention

**Comment by sean-mcmanus** [comment]
We do plan to support this (as part of the "full IntelliSense"), but we don't have any announced schedule for it yet.

**Comment by liuyuxun** [comment]
update to the newest version,it seems still do support the local variables IntelliSense?
such as 'Go to Declaration', 'auto complete struct member', am i right?

**Comment by bobbrow** [comment]
version 0.11.1 does not yet support goto definition for local variables.  Auto complete for struct members is still using the old tag parser implementation which not semantic-aware.

**Comment by liuyuxun** [comment]
@bobbrow appreciate for your work，is there a schedule for this feature?

**Comment by bobbrow** [comment]
We haven't released any schedules for these features yet.
