### ISSUE TITLE
Peek/Go To Definition finds same definitions multiple times

### ISSUE THREAD

**Issue by Holo-Viktor** [microsoft/vscode-cpptools#4261]
> https://github.com/microsoft/vscode/issues/80854#issue-493233317

Issue Type: Bug

I have a multi-root project with one of the root folder being a subfolder of the other (main) root folder. (because there is no way to focus or pin folders right now)
I'm not sure if this is causing the problem but Go To Definition always shows the multiple peek view because it finds the same definitions twice.

VS Code version: Code 1.38.1 (b37e54c, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

![screenshot](https://user-images.githubusercontent.com/43336921/64944839-896b7080-d86f-11e9-9a65-864116998179.png)

**Comment by sean-mcmanus** [comment]
Yeah, multi-root where one folder is a subfolder of another has many known problems. We plan to re-write our multi-root support "correctly" in the next few months.

**Comment by sean-mcmanus** [comment]
Our latest Insiders release has a new multi-root implementation (which fixes this bug): https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders. Please let us know if you find any multi-root-related bugs or regressions so we can prioritize fixing those for 0.27.0.
