### ISSUE TITLE
Code formatter doesn't see what macro expands to

### ISSUE THREAD

**Issue by moojek** [microsoft/vscode-cpptools#4263]
The title might be confusing but the problem is very simple. For example if I have a macro function `#define FE(i, a, b) for (size_t i = a; i < b; i++)` and I've set my code formatter to format 'for' loops like:
```
for (size_t i=a; i < b; i++) {
    /* code */
}
```
when I use my macro it gets formatted to:
```
FE (i, a, b)
{
/* code */
}
```
Bracket goes to the next line when it isn't supposed to

**Comment by sean-mcmanus** [comment]
This is "by design" with clang-format. Can you set ForEachMacros: [ 'FE' ]? If that doesn't work, what is the exact settings you're using to control line breaking?

**Comment by moojek** [comment]
> Can you set ForEachMacros: [ 'FE' ]?

What do you mean?

**Comment by moojek** [comment]
Okay, that worked, thanks for help :)
