### ISSUE TITLE
MAP_ANO

### ISSUE THREAD

**Issue by mahsoommoosa42** [microsoft/vscode-cpptools#4267]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I'm closing this, since there doesn't appear to be any valid info...looks like the issue got reported at https://github.com/microsoft/vscode-cpptools/issues/4268 .
