### ISSUE TITLE
MAP_ANONYMOUS undefined

### ISSUE THREAD

**Issue by mahsoommoosa42** [microsoft/vscode-cpptools#4268]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Pop! OS 19.04
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.25.1
- A clear and concise description of what the bug is.
When I use define in linux header files MAP_ANONYMOUS. it is reported as undefined but, it compiles with GCC. 

**To Reproduce**

**Expected behavior**
Consider this function
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <sys/wait.h>
#include <sys/mman.h>

void* create_shared_memory(size_t size){
    int protection = PROT_READ | PROT_WRITE;

    int visibility = MAP_SHARED | MAP_ANONYMOUS;

    return mmap(NULL, size, protection, visibility, -1, 0);
}
```
![image](https://user-images.githubusercontent.com/21087309/65152306-537fe500-da45-11e9-9a36-e9e7639ff4a5.png)

**Comment by sean-mcmanus** [comment]
I have it defined at /usr/include/x86_64-linux-gnu/bits/mman-linux.h, but its usage is dependent on a bunch of system defines that you might be missing. Can you do a C/C++: Log Diagnostics command and/or open the file where MAP_ANONYMOUS is defined and look which defines are missing? Providing your gcc version may also help.

**Comment by mahsoommoosa42** [comment]
Yeah my bad. I had missed a define. Thanks anyway.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by stewartmcgown** [comment]
@mahsoommoosa42 would you care to share the define that you were missing? I can right-click MAP_ANONYMOUS and it brings me to the definition, but vscode still shows it as undefined!

![image](https://user-images.githubusercontent.com/1136276/65377275-eb7a0a80-dca1-11e9-8629-321325eacb60.png)

Is it due to Vscode not having __USE_MISC defined when searching for headers?

**Comment by mahsoommoosa42** [comment]
It was GNU_SOURCE

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
