### ISSUE TITLE
Use Docker with cross target GDB with cpptools debugger

### ISSUE THREAD

**Issue by antmerlino** [microsoft/vscode-cpptools#427]
Hi,

Here is what I am hoping to do.. I can't tell if this is something I'd be able to do now, or is a feature I'd like in the future. (I'm hoping I can do it now).

Basically, I am hoping to eliminate the need to have a cross target gdb installation on my host machine.  Instead I'd like to have preconfigured docker containers for different targets that have entire toolchains inside, including gdb.  Then, instead of having vscode get MI data from gdb on the host which is connected to gdbserver on the target, I can have vscode somehow get MI data directly from gdb running in the docker container.  

Is this possible?

I noticed that I could probably do it using https://github.com/WebFreak001/code-debug by ssh'ing to the gdb instance in the docker container, but there debugging adapter seems far less developed than this one.  

Thank you,
Anthony

**Comment by antmerlino** [comment]
@jacdavis I noticed in another issue you mentioned something about transport pipes or something for doing something similar to this.  Do you have any ideas or is this in the works?

**Comment by pieandcakes** [comment]
@antmerlino This is something new that we can look into but it isn't something that works today.

**Comment by pieandcakes** [comment]
@antmerlino we have released version `0.10.0` with the added feature of `pipeTransport`.  Please take a look at the documentation [here](../wiki/PipeTransport). This sounds like the feature you are referencing above. If this doesn't solve your problem please comment and reopen.

Thanks
