### ISSUE TITLE
Enter key does not jump to the definition when "Go to definition" has multiple results

### ISSUE THREAD

**Issue by yutotsukishima** [microsoft/vscode-cpptools#4273]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Pro 1809 x64 2019-03B
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them): disabled all
- A clear and concise description of what the bug is.
When there are multiple results with "Go to definition" search, "Press Enter Key" does not jump to the definition of the selected result with "White highlight font ( the default selected result)".
"Press Enter Key" will jump to the definition if the font color of the selected result is gray.

**To Reproduce**

1. set "C_Cpp: Intelli Scese Engine" to "Tag Parser" so there will be multiple results with "Go to definition"
2. Press F12 on variables/functions which have multiple definitions
3. Press Enter
4. nothing happens

**Expected behavior**
Should jump to the selected result after pressing "Enter"

**Screenshots**

**Additional context**

C_Cpp log:
initialized
workspace/didChangeConfiguration
IntelliSense Engine = Tag Parser.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Autocomplete is enabled.
Enhanced Colorization is enabled.
Error squiggles are disabled.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/CVS
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: *.patch
Search exclude: **/*.bin
Search exclude: **/*.log
Search exclude: **/*.o
Search exclude: **/*.obj
Search exclude: **/*.html
Search exclude: **/*.patch
Search exclude: **/*.svn-base
Search exclude: **/.vscode
Attempting to get defaults from compiler found on the machine: 'C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe'
cpptools/queryCompilerDefaults: 1
Attempting to get defaults from compiler found on the machine: 'C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe'
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
textDocument/didOpen
textDocument/didOpen
textDocument/didOpen
cpptools/didChangeFolderSettings
Attempting to get defaults from compiler in "compilerPath" property: '<-deleted log->clang++.exe'
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: '<-deleted log->clang++.exe'
  Unable to retrieve file system information for <-deleted log-> error = -1
  Unable to retrieve file system information for <-deleted log-> error = -1
  Folder: C:/PROGRAM FILES (X86)/SCE/ORBIS SDKS/6.500/TARGET/INCLUDE/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/SCE/ORBIS SDKS/6.500/TARGET/INCLUDE_COMMON/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO 14.0/VC/INCLUDE/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO 14.0/VC/ATLMFC/INCLUDE/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/UM/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/SHARED/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/WINRT/ will be indexed
  <-deleted log->
Populate include completion cache.
textDocument/didOpen
Discovering files...
textDocument/didOpen
textDocument/didOpen
textDocument/documentSymbol: 2
textDocument/codeAction: 4
textDocument/codeAction: 5
idle loop: reparsing the active document
  Processing folder (recursive): C:/PROGRAM FILES (X86)/SCE/ORBIS SDKS/6.500/TARGET/INCLUDE/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/SCE/ORBIS SDKS/6.500/TARGET/INCLUDE_COMMON/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO 14.0/VC/INCLUDE/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO 14.0/VC/ATLMFC/INCLUDE/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/UM/
textDocument/documentSymbol: 3
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/SHARED/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/8.1/INCLUDE/WINRT/
  <-deleted log->
textDocument/hover: 6
using Tag Parser for quick info
textDocument/hover: 7
using Tag Parser for quick info
  Discovering files: 243848 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
textDocument/hover: 8
using Tag Parser for quick info
textDocument/documentHighlight: 9
cpptools/textEditorSelectionChange
textDocument/codeAction: 10
textDocument/hover: 11
using Tag Parser for quick info
textDocument/definition: 12
textDocument/codeAction: 13
textDocument/codeAction: 14

**Comment by sean-mcmanus** [comment]
I don't understand the issue -- using the Enter key is working for me -- it goes to the definition of the selected item. Can you add a screenshot that shows the problem?

**Comment by yutotsukishima** [comment]
It was working a few days ago before VSCode 1.38.1 updates? I will try to go back to the previous version later.
The Enter key does not work in this situation.
![go_to_definition](https://user-images.githubusercontent.com/41064866/65211905-385fb480-dadb-11e9-8d8e-4d455b89f8e1.jpg)

The Enter key works if I select the gray colored item.
![go_to_definition2](https://user-images.githubusercontent.com/41064866/65212074-c9369000-dadb-11e9-92b5-63780f963235.jpg)

**Comment by yutotsukishima** [comment]
I installed the previous version of VSCode 1.37.1(user setup) and the Enter key is working.

I tried to disable all the setting in settings.json and keybindings in keybindings.json with 1.38.1 but still not working.

**Comment by sean-mcmanus** [comment]
We have no control over the UI -- can you report this bug to VS Code at https://github.com/microsoft/vscode/issues? Or I could move this bug over there myself if you want.

Our extensions just sends back an array of locations for results.

I think I repro the bug now -- Enter isn't working for the definition that is currently visible (i.e. first selected).

**Comment by Anoop-Goudar** [comment]
Any updates on this ? Goto definition is not working in VScode 1.38.1

**Comment by sean-mcmanus** [comment]
It's a VS Code bug: https://github.com/microsoft/vscode/issues/81200

**Comment by Colengms** [comment]
The tracked issue has been fixed.  Closing this one.  The behavior appears to have changed since this issue was created.  If you're still seeing a similar problem, I'd suggest opening an issue in the VS Code repo: https://github.com/microsoft/vscode

The C/C++ Extension provides results for this operation, but UI navigation is handled by VS Code.
