### ISSUE TITLE
Problems with the global 'c_cpp_properties.json' file on Linux

### ISSUE THREAD

**Issue by ranolfi** [microsoft/vscode-cpptools#4274]
Type: General

- OS and Version: **Arch Linux**
- VS Code Version: **Code-OSS 1.37.1**
- C/C++ Extension Version: **0.25.1**

On a newly-installed VS Code setup with the C/C++ extension, I was having problems with all my C++ files because the extension could not find the stdlib headers. I tried clicking the lightbulb option to edit the `IncludePath` setting, but the message "_Open a folder first to edit configurations_" appears. As I wanted to the setting to apply to _all_ projects and files (as, IMO, it should by default), I created the file under `~/.vscode-oss/c_cpp_properties.json` (which was _not_ automatically created by the extension):
```
{
    "configurations": [
        {
            "name": "Linux",
            "compilerPath": "/usr/bin/gcc"
        }
    ],
    "version": 4
}
```

But it did not have any effect.

Even though I don't have the Microsoft brand of VS Code, just the open source edition, I still tried creating the dir `~/.vscode` and putting the file there. Then, whenever I save it, a message appears in VS Code:

> Failed to parse "/.vscode/c_cpp_properties.json": ENOENT: no such file or directory, open '/.vscode/c_cpp_properties.json'

Notice how it is trying to open something from the root dir (`/.vscode/`).

Then, I tried:
`$ sudo ln -sf ~/.vscode /.vscode`

and, sure enough, it worked. The extension could now find `<iostream>` and the other standard headers.

Things are odd:

1. Why is the file under `~/.vscode-oss` not recognized? (I don't have the branded VS Code edition installed)
2. Why wasn't it created automatically?
3. Why is it giving an error when the file under `~/.vscode` is saved, and why is it trying to open the file via `/.vscode`?

I'd also like to take the opportunity to ask, whether in my case it would be advantageous to just set `"C_Cpp.default.compilerPath"` in VS Code's _settings.json_ instead.

Thanks

**Comment by sean-mcmanus** [comment]
Yeah, setting C_Cpp.default.compilerPath would be good. The C_Cpp.default.* settings is how we support the "global c_cpp_properties.json" concept -- otherwise, it needs to be in the ${workspaceFolder}/.vscode folders (not ~/.vscode-oss or ~/.vscode). "/.vscode" probably means it thinks the ${workspaceFolder} is blank.

You should use the C/C++: Edit configuration command to create and edit c_cpp_properties.json settings, either via the UI or the JSON editor, but you need to have a workspace folder open -- our support for the "open file" scenario could be improved.

**Comment by ranolfi** [comment]
A lot of files I just want to inspect C++ source files without creating a workspace for them... that's my use case in this issue report. But it's all good, by setting `C_Cpp.default.compilerPath` I got rid of the error squiggles under the standard library header `#include`s.
