### ISSUE TITLE
Adding support for reading out file content into c_cpp_properties.json

### ISSUE THREAD

**Issue by DeadRabbits307** [microsoft/vscode-cpptools#4275]
Like U-Boot many SW projects create a toplevel` .config` file before running `make all` to build the binary. In such a `.config` file, defines/configurations are listed which are used in source codes for `#ifdef`s which cause the intelisense to colorize inactive regions.

Therefore, it would be useful to be able to fill the `"defines"` under `"configurations"` in the `c_cpp_properties.json `with the content of files like:

`"defines": ["${workspaceFolder}/.config"],`

...for example required [here](https://stackoverflow.com/questions/46415076/how-can-i-define-macros-for-the-c-intellisense-engine) as well

**Comment by sean-mcmanus** [comment]
What is the format of the .config file? `var=val` , `"var=val"`, or `#define var val`? If it's valid C/C++ you could potentially add it to forcedInclude setting.

We're also working on a "make" configuration provider that might also be able to read the .config (if that's what "make" is setup to process when building).

**Comment by DeadRabbits307** [comment]
The .config file has following format: 
`CONFIG_DISPLAY_BOARDINFO=y`
`# CONFIG_DISPLAY_BOARDINFO_LATE is not set`

Because this file is used to generate an autoconf.h containing C-style defines, I can use the forcedInclude setting.

For information: [This](https://stackoverflow.com/questions/32991627/ide-with-kconfig-support) helped me and as you can see, for the KDevelop IDE there seems to be something available called [kdev-kernel](https://github.com/Gnurou/kdev-kernel). Maybe this helps you as well:)
