### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of nativeStrings.child_exec_failed

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4276]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Child exec failed {0}

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
What does the placeholder {0} stand for? Name of the child process? Shouldn't it be before the word 'failed' then?

**Comment by Colengms** [comment]
In this case, the placeholder is an error code.

**Comment by Colengms** [comment]
@PDostalek Tagging you as FYI that this issue is still open.
