### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of lowercased strings

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4285]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Since this string starts with a lower case letter, will it be preceded (and/or followed) by anything? If yes, please provide the complete string.

This also applies to the following ResIDs:
0; "dist/src/Debugger/configurationProvider.path.to.pipe.program"
0; "dist/src/Debugger/configurations.enter.program.name"
0; "dist/src/LanguageServer/client.a.compile.commands.file"
0; "dist/src/LanguageServer/extension.client.not.found"
0; "dist/src/LanguageServer/nativeStrings.giving_up"
0; "dist/src/LanguageServer/nativeStrings.not_exited_yet"
0; "dist/src/LanguageServer/nativeStrings.sending_compilation_args"
0; "dist/src/LanguageServer/nativeStrings.sending_count_changes_to_server"
0; "dist/src/LanguageServer/nativeStrings.still_alive_killing"
0; "dist/src/LanguageServer/nativeStrings.tag_parser_quick_info"
0; "dist/src/LanguageServer/ui.click.to.preview"
0; "dist/src/packageManager.failed.web.error"
0; "package.c_cpp.debuggers.pipeTransport.default.pipeProgram"

File Name:
Src\vscode-extensions\cpptools.xlf

**Comment by Colengms** [comment]
0; "dist/src/Debugger/configurationProvider.path.to.pipe.program" - This string is a text field placeholder.  It's initial text intended to be replaced by the user.

0; "dist/src/Debugger/configurations.enter.program.name" - This string is also a text field placeholder.  It's initial text intended to be replaced by the user.

0; "dist/src/LanguageServer/client.a.compile.commands.file" - This string (or a path) may be used as the placeholder string {0} in auto-configure.intellisense.folder or auto-configure.intellisense.this.folder

0; "dist/src/LanguageServer/extension.client.not.found" - This is a logged error message

0; "dist/src/LanguageServer/nativeStrings.giving_up" - This is a logged error message

0; "dist/src/LanguageServer/nativeStrings.not_exited_yet" - This is a logged error message.

0; "dist/src/LanguageServer/nativeStrings.sending_compilation_args" - This is a logged message

0; "dist/src/LanguageServer/nativeStrings.sending_count_changes_to_server" - This is a logged message

0; "dist/src/LanguageServer/nativeStrings.still_alive_killing" - This is a logged error message

0; "dist/src/LanguageServer/nativeStrings.tag_parser_quick_info" - This is a logged message

0; "dist/src/LanguageServer/ui.click.to.preview" - This is a tooltip (displayed within parenthesis, i.e. "(click to preview results)".

0; "dist/src/packageManager.failed.web.error" - This is a logged error message

0; "package.c_cpp.debuggers.pipeTransport.default.pipeProgram" - This is text field placeholder text


I have an issue open against vscode-nls-dev [here](https://github.com/microsoft/vscode-nls-dev/issues/21) to enable us to add these types of hints to the XLF we export, which would make this process easier.

**Comment by PDostalek** [comment]
Excellent, thanks for creating issue regarding loc hints. Closing this bug for now.
