### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/LanguageServer/nativeStrings.offering_completion"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4286]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Offering completion

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Does this mean that an offering is being completed or that a completion is being offered?

**Comment by Colengms** [comment]
In this case, completion is a noun.  A 'completion' is being offered.

**Comment by PDostalek** [comment]
THanks
