### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/packageManager.error.from"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4287]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Error from {0}

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
What will the placeholde be replaced with?

This also applies to this ResID:
0; "dist/ui/settings.html.intellisense.configurations.description3"

**Comment by Colengms** [comment]
In the case of "Error from {0}", the placeholder will be a filename.

settings.html.intellisense.configurations.description3 should no longest exist.  settings.html.intellisense.configurations.description (without the 3) contains a placeholder that will be replaced with a (link to a) filename.

**Comment by PDostalek** [comment]
Many thanks
