### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "package.c_cpp.configuration.autocomplete.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4288]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Controls the auto-completion provider. "Default" uses the active IntelliSense engine. "Disabled" uses the word-based completion provided by Visual Studio Code.

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Are the options in this string translatable or should they remain in English?

This also applies to these ResIDs:
0; "package.c_cpp.configuration.formatting.description"
0; "package.c_cpp.configuration.intelliSenseEngine.description"

**Comment by Colengms** [comment]
"Default", "Disabled", and "Tag Parser" should remain in English.  "fuzzy" is not an option name, and could be localized.

**Comment by PDostalek** [comment]
Thanks
