### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "package.c_cpp.configuration.workspaceParsingPriority.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4289]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Controls whether parsing of the non-active workspace files uses sleeps to avoid using 100% CPU. The values highest/high/medium/low correspond to approximately 100/75/50/25% CPU usage.

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Are the values in this string translatable?

**Comment by Colengms** [comment]
The numbers in this string (25%/50%/75%/100%) can be localized if there is a preferred alternative concept in another language.  "highest", "high", "medium", and "low" are settings values, and should remain in English.

**Comment by PDostalek** [comment]
Perfect, thx.
