### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/Debugger/configurationProvider.replacing.sourcepath"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4290]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Replacing {0} '{1}' with '{2}'.

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
In order to determine gender, please clarify what variable {0} will be replaced with. Thanks.

**Comment by Colengms** [comment]
In this case, {0} is essentially referring to a variable, {1} is it's original value, and {2} is a replacement value.

**Comment by PDostalek** [comment]
Thank you for clarification
