### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/Debugger/ParsedEnvironmentFile.ignoring.lines.in.envfile"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4291]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Ignoring non-parseable lines in {0} {1}: 

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
In order to determine gender, please clarify what the placeholder {0} will be replaced with. Thanks.

**Comment by Colengms** [comment]
In this case, {0} refers to a type of file, and {1} refers to the file specifically.  i.e. Ignoring non-parseable lines in envFile TestEnvFileName

**Comment by PDostalek** [comment]
Thanks!
