### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "package.c_cpp.debuggers.miDebuggerArgs.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4292]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Arguments for the mi debugger (such as gdb) to use. When unspecified.

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Please confirm if something is missing after " When unspecified." or if the sentence should be "Arguments for the mi debugger (such as gdb) to use when unspecified."

**Comment by Colengms** [comment]
This is a description for a settings field.

However, the "When unspecified." doesn't make sense.  It looks incomplete.  @pieandcakes This is the original string.  Does this string need to be corrected?

**Comment by pieandcakes** [comment]
I created a pull request to clear it up. This looks like a copy/paste issue when the string was created.

**Comment by PDostalek** [comment]
Thanks for correction
