### ISSUE TITLE
Add support for parsing the non-recursive "*" in compilerPath output for .bat files

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4296]
See https://github.com/microsoft/vscode-cpptools/issues/4269 . Setting a .bat file that uses "*" for non-recursive includes doesn't work.

**Comment by bobbrow** [comment]
This is to support a workaround.  I think the idea to add a systemDefines setting is a better way to approach this issue.

**Comment by Colengms** [comment]
We are tracking multiple possible solutions for handling unsupported compilers.  Closing this, as we likely not need it.
