### ISSUE TITLE
[C] Incorrect error: array size parameter

### ISSUE THREAD

**Issue by venuur** [microsoft/vscode-cpptools#4300]
Issue Type: <b>Bug</b>

1. Enter the following into a new file `bug.c`.

```
int main(int argc, char *argv[argc + 1]) {
    return 0;
}
```

2. Actual outcome: argc in the second parameter of main is highlighted in red underscore.as if it were an error.

3. Expected outcome: no error should be highlighted as the code is correct.

Extension version: 0.25.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (9.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Jasdriel** [comment]
Hi @venuur, this is not a valid declaration in C++, when a 2D array is passed, the value of the second dimension, argc +1 in your case, must be known at compile time but the operation you are using will be know till run time.

**Comment by venuur** [comment]
I apologize. I was not clear. This is a C program, where such an expression is valid. Does this extension support C as well?

**Comment by Jasdriel** [comment]
Got it, I reasearch I little and found out that that feature was in the c99 standard and that still exist for gcc compilers, so you can change the IntelliSense mode you would be using, I think by default is set to msvc-x64 that doesn't support all c99 standard features

**Comment by sean-mcmanus** [comment]
Did the suggestion work of changing your intelliSenseMode work (and/or setting your compilerPath)? Let us know if this is still an issue.
