### ISSUE TITLE
Auto format incorrectly formats text

### ISSUE THREAD

**Issue by comiluv** [microsoft/vscode-cpptools#4301]
**Type: LanguageService**

**Describe the bug**
- OS and Version: windows 10
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them): none
- A clear and concise description of what the bug is.
C auto formatter formats `while (getchar() != '\n');` to become
```C
while (getchar() != '\n')
    ;
```

**To Reproduce**

1. Select Language Mode C
2. Type `while (getchar() != '\n');`
3. Open command pallet
4. Format Document

**Expected behavior**

`while (getchar() != '\n');` stays same

**Screenshots**

**Additional context**

**Comment by michelleangela** [comment]
This seems to be by design, as it's expecting `;` to be some statement which would not be inline with `while(...)`.

**For example:**

Start with
```
while (getchar() != '\n') someStatement();
```

then format document, which results in:
```
while (getchar() != '\n')
    someStatement();
```
