### ISSUE TITLE
Automatic inserting comment symbols in new line

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-cpptools#4303]
I'm writing C++ code via Rcpp. Comments starting with `//'` are converted to documentation by `roxygen` tools. It would be very convinient to have `//'` inserted in the beginning of a new line if the previous line is also a comment like this.

```cpp
//' Fast shift
//' @param x an atomic vector or a list of atomic vectors
//' @param n an integer vector of shift offsets.
//'   `0` indicates no shifting.
//'   Positive integers indicate lagging.
//'   Negative integers indicate leading.
//' @export
//' @examples
//' fshift(rnorm(10), 2)
//' fshift(rnorm(10), 1:10)
//' fshift(rnorm(10), -1)
// [[Rcpp::export]]
SEXP fshift(const SEXP &x, const IntegerVector &n) {
  // some code here
}
```

I notice that auto-inserting `/** **/` notation is already supported (can be used by doxygen) but is it possible to generalize the feature so that `//'` or `///` can be auto-inserted too? For example, if there's an option that a line starting with `//['/]` will be auto-inserted the same prefix, it would be nice.

**Comment by michelleangela** [comment]
You can try defining a pattern for the setting `C_Cpp.commentContinuationPatterns`.

Example:
```
    "C_Cpp.commentContinuationPatterns": [
        "//'"
    ]
```

In order for the next line to auto insert a `//'` you must type either a space or some character after the preceding or first `//'`

**Comment by renkun-ken** [comment]
Thanks! This is exactly what I'm asking for.
