### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/LanguageServer/nativeStrings.define_label"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4305]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
define: {0}

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Is "define" localizable here? Thanks.

**Comment by Colengms** [comment]
In this case, the placeholder refers to a "#define" or C/C++ preprocessor definition.  This string is used in log output, in which a list of #define's are logged.  Whether or not it _should_ be localized, or kept as the English string (directly referring to the C++ keyword 'define').  I'm not certain.  For now, I suggest we localize it, as we have done so for most languages already.

**Comment by PDostalek** [comment]
Thanks
