### ISSUE TITLE
Jump to macro definition failed when expanding macros with length around 2400.

### ISSUE THREAD

**Issue by smwikipedia** [microsoft/vscode-cpptools#4306]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
Windows 10 Version 1709

- VS Code Version:
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299

- C/C++ Extension Version:
0.25.1

- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
Open this repo in VS Code:
https://github.com/smwikipedia/macroExpansion

There are 2 files in that repo:

- `a.h`: defines a bunch of macros
- `a.c`: use the macros defined in `a.h`

In `a.c` file, line 7 to line 33 are some macros. See below:
![image](https://user-images.githubusercontent.com/999318/65416801-3d01d100-de2b-11e9-9c4b-b9d86b389c75.png)

Jump to definition for `ztest_test_suite` on line 7 in `a.c`. It will jump to `struct unit_test` in `a.h` at line 1. **This is incorrect.** See below:

![image](https://user-images.githubusercontent.com/999318/65416306-23ac5500-de2a-11e9-8a2d-8cc4cec55216.png)

So this issue seems to be related to the length of the macro expansion result. So I tried **deleting single arbitrary line** from `a.c` between line 8 and line 32.
Repeat jump to definition for `ztest_test_suite` on line 7 in `a.c` again. It will jump to `#define ztest_test_suite(suite, ...)` at line 31 in `a.h`. **This is the correct result.** See below:

![image](https://user-images.githubusercontent.com/999318/65416464-784fd000-de2a-11e9-8d79-73a7898bba48.png)

The final macro expansion length is about 2400. It doesn't exceed the **20000** token length limitation. However, even if I changed to `"editor.maxTokenizationLineLength": 50000` in the `settings.json`. The issue still remains.

![image](https://user-images.githubusercontent.com/999318/65416713-0deb5f80-de2b-11e9-8ab0-4c489144a6e5.png)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. The bug also repros in VS, so I've filed a bug at https://developercommunity.visualstudio.com/content/problem/752497/cc-intellisense-based-go-to-definition-fails-for-m.html . You could upvote that if you have a Microsoft account.

**Comment by smwikipedia** [comment]
Thanks. So Visual Studio and Visual Studio Code share some implementations?

**Comment by smwikipedia** [comment]
I have upvoted that VS bug report. I see this issue was removed from the 0.26.1 milestone. Kind of disappointing. Could you reveal if it will be covered in any future milestones? Thanks. @sean-mcmanus

**Comment by smwikipedia** [comment]
I have upvoted that VS bug report.

**Comment by sean-mcmanus** [comment]
Yeah, our low level parsing and IntelliSense code is shared. We plan to share more later.

It was removed from 0.26.1 because we don't know when the fix will get in -- it depends on when the VC++ team decides to fix. I was able to fix it for your specific repro via changing a hard-coded array size, but I don't think that is the correct fix.

**Comment by Colengms** [comment]
@sean-mcmanus Did this make it into 1.2.1 ?

**Comment by sean-mcmanus** [comment]
No. It's for 1.3.0-insiders.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders .

**Comment by smwikipedia** [comment]
Glad it is claimed to be fixed.

**Comment by michelleangela** [comment]
Fix is released in the 1.3.0 release version https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0
