### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/ui/settings.html.limit.symbols" #4204 

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4307]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Defines

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Is "Defines" localizable here? Thanks.

**Comment by Colengms** [comment]
Same answer as: https://github.com/microsoft/vscode-cpptools/issues/4305
It's not 100% clear to me.  How do people refer to C/C++ "defines" and "includes" in other languages?  Existing documentation for Visual Studio might provide us with a precedence for that decision.
