### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/LanguageServer/nativeStrings.other_label"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4308]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
other: {0}

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Please explain "other" here. Thanks.

**Comment by Colengms** [comment]
The placeholder here refers to a command line argument passed to the compiler.  We have various categories or compiler command line arguments.  (Such as defines, and includes).  "other" is used for misc comment line arguments that do not fall into other categories.

**Comment by Colengms** [comment]
@PDostalek Tagging you as FYI that this issue is still open.

**Comment by PDostalek** [comment]
Closing, thx
