### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/LanguageServer/nativeStrings.discovery_files_processed"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4309]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Discovering files: {0} file(s) processed

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
What will {0} be?
Assuming numbered placeholder

**Comment by Colengms** [comment]
Yes, the placeholder will be a number here.

**Comment by Colengms** [comment]
@PDostalek Tagging you as FYI that this issue is still open.

**Comment by PDostalek** [comment]
Closing, thx
