### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/packageManager.downloading.progress.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4310]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Downloading {0}: {1}

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
What will {0} and {1} be?

**Comment by Colengms** [comment]
In this case, {0} will contain progress.  i.e. (50%).  And, {1} will contain a description of a package being downloaded.

**Comment by Colengms** [comment]
@PDostalek Tagging you as FYI that this issue is still open.

**Comment by PDostalek** [comment]
perfect, closing
