### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/LanguageServer/nativeStrings.include_label"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4311]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
include: {0}

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Is "include" localizable in this string? Thanks.

**Comment by Colengms** [comment]
Similar to: https://github.com/microsoft/vscode-cpptools/issues/4305
It's not 100% clear to me.  How do people refer to C/C++ "defines" and "includes" in other languages?  Existing documentation for Visual Studio might provide us with a precedence for that decision.

**Comment by Colengms** [comment]
@PDostalek Tagging you as FYI that this issue is still open.
