### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of  0; "dist/src/LanguageServer/nativeStrings.tag_parsing_file"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4312]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
tag parsing file: {0}

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
What will {0} be?

**Comment by Colengms** [comment]
In this case, the placeholder will be a full path to a file.

**Comment by PDostalek** [comment]
Perfect, thanks
