### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/ui/settings.html.compiler.path.description1"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4313]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The full path to the compiler you use to build your project, e.g. {0}, to enable more accurate IntelliSense.

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
What will {0} be?

**Comment by Colengms** [comment]
The placeholder will be a path to a compiler executable.  Specifically, in this case, the placeholder is an example and will always be: <code>/usr/bin/gcc</code>

When processing HTML, we turn any sub-nodes into placeholders so raw HTML does not appear in strings we hand off for loc.

**Comment by PDostalek** [comment]
Thanks for clarifying
