### ISSUE TITLE
Never-ending scrolling indicator in File Explorer

### ISSUE THREAD

**Issue by smwikipedia** [microsoft/vscode-cpptools#4318]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
Windows 10 Version 1709

- VS Code Version:
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299

- C/C++ Extension Version:
0.25.1

- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I opened a relatively large code base in Visual Studio. There are mainly C files.
I see below blue progress bar scrolling forever in the VS Code Explorer window. Anyone knows what's going on in the background?

**Screenshots**

![image](https://user-images.githubusercontent.com/999318/65486003-e7cec980-ded5-11e9-8090-b8e3c0644b7b.png)

**Comment by sean-mcmanus** [comment]
Does the bug repro without our C/C++ extension? If so, can you file your bug at https://github.com/microsoft/vscode/issues

**Comment by smwikipedia** [comment]
This issue happens from time to time but I have no steady way to reproduce it yet.
I will come back if more info is available.

**Comment by bobbrow** [comment]
At this time we don't have enough information to investigate this issue.  If you are able to provide some repro steps for us, we can reopen this issue and investigate further.  Thank you!
