### ISSUE TITLE
Support trailing comma in c_cpp_properties.json arrays

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode-cpptools#4319]
It's a small thing but is it possible to support a trailing comma at the end of a json array in c_cpp_properties?
My c_cpp_properties is generated by a script and then sorted so it would be easier if we can have trailing commas.

Thanks!

```json
{
  "configurations": [
    {
      "includePath": [
        "${myDefaultIncludePath}", 
        "/another/path",
      ],
      "defines": [
        "FOO", 
        "BAR=100",
      ],
    }
  ],
  "version": 4
}
```

**Comment by michelleangela** [comment]
I think in order to support and parse trialing commas, [JSON5 ](https://json5.org/) is required.

**Comment by bobbrow** [comment]
This will be covered by #2755
