### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "dist/src/LanguageServer/nativeStrings.giving_up"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4326]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
giving up

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
We are not sure how this "giving up" is going to be used throughout the context. Would you mind giving us a little more information? Thanks.

**Comment by sean-mcmanus** [comment]
Giving up is used in the context of "The code has been trying for 16 seconds, now it's reporting that it's "giving up" instead of continuing to wait."

**Comment by PDostalek** [comment]
Thanks for clatification
