### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of  0; "dist/src/LanguageServer/nativeStrings.files_removed_from_database"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4327]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
{0} file(s) removed from database

File Name:
Src\vscode-extensions\cpptools.xlf

Query:
Please clarify placeholder. Is it this just volume or something different ?

**Comment by sean-mcmanus** [comment]
Place holder is a number, like "10 files(s) removed from database".

Note: The English string should probably use "the database" to be more grammatically accurate.

**Comment by PDostalek** [comment]
Thank you
