### ISSUE TITLE
How to setup the c_cpp_properties.json to create a local database and look it up for symbol references.

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-cpptools#433]
_From @rahulagr on January 5, 2017 19:45_

- VSCode Version: 1.8.1
- OS Version: Mac OS X 10.12.2

My code lives on a NFS mounted partition (linux server). I am launching Microsoft Code on my Mac, and using NFS mount to access the files.

The file search and symbol reference is very slow currently. I want to create a local database, and use that database to do symbol reference and file search. Please let me know if it is possible, and if so, what exactly needs to be configured and where. I tried to search for c_cpp_properties.json documentation, but didn't find anything relevant.

Steps to Reproduce:
1. 
2. 

_Copied from original issue: Microsoft/vscode#18189_

**Comment by chrmarti** [comment]
There is currently no cache for the file lookup/search, we will investigate adding one as part of #15382. Moving to the cpptools in case there is a cpp specific solution/answer to the symbol cache.

**Comment by sean-mcmanus** [comment]
You can change the databaseFilename property in c_cpp_properties.json -- I assume a local location will be faster. The documentation is in the tooltips in the json file. Does that speed symbol search up?

**Comment by bobbrow** [comment]
Please reopen if Sean's answer didn't resolve your issue for you.  Thanks!
