### ISSUE TITLE
Add a search or file filter to the References/Rename UI

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4338]
Because when I care about references in the current file, it's hard to locate that file when there 200 other files in the UI. The ability to search was possible with the Output window.

**Comment by bobbrow** [comment]
We can't do this in the references UI.  We'd need the VS Code Team to support this too.  Can you open a feature request for them to consider it?

**Comment by sean-mcmanus** [comment]
This is possible via adding a search/filter button, which triggers a command dropdown in the command palette area -- this is what the TODO extension does with their "Filter tree (Press 'Enter' to confirm or 'Escape to cancel), which changes to "Clear filter" after a filter is added.
