### ISSUE TITLE
#ifdef XXX #else  #endif gray code Bug

### ISSUE THREAD

**Issue by iamlk** [microsoft/vscode-cpptools#4346]
Type: Debugger

**Describe the bug**
- OS and Version: MacOS 10.14.6
- VS Code Version:1.38.1
- C/C++ Extension Version:0.25.1

- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. #define something in header files
2. writing #ifdef xxx #else xxx #endif
3. //#define 
![image](https://user-images.githubusercontent.com/5254604/65745984-16e07780-e130-11e9-8218-b8ce7d4d596e.png)
**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment]
I'm not able to repro the bug. Is the bug that half the defines are grayed out strangely? Is there some special requirement?

**Comment by iamlk** [comment]
Restart ccptools and VScode,it's get back to normal.
Thanks~
