### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "./src/LanguageServer/references.comment.reference.upper"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4347]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
COMMENT REFERENCE

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Does this mean "a reference to a comment"?
Or maybe it means "to make a comment for a reference" or "to place the reference within a comment"?
Please clarify.

**Comment by Colengms** [comment]
This string is part of our "find all references" feature.  A "comment reference" is a type of reference.  It refers to a source code 'comment' (text that does not contain source code instructions, rather a programmers comments/documenation), which contains a reference being searched for.

**Comment by PDostalek** [comment]
Many thanks !
