### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "package.c_cpp.debuggers.symbolLoadInfo.loadAll.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4348]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
If true, symbols for all libs will be loaded, otherwise no solib symbols will be loaded. Default value is true.

File Name:
Src\vscode-extensions\vscode-cpptools.xlf

Query:
what is a solib?

**Comment by Colengms** [comment]
@pieandcakes or @WardenGnaw , can you comment?

**Comment by pieandcakes** [comment]
`solib` is the gnu term for shared library

**Comment by PDostalek** [comment]
Thanks
