### ISSUE TITLE
 [loc][Query][vscode-cpptools] Localizability of 0; "package.c_cpp.debuggers.symbolLoadInfo.exceptionList.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4349]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
List of filenames (wildcards allowed) separated by semicolons ';'. Modifies behavior of LoadAll. If LoadAll is true then don't load symbols for libs that match any name in the list. Otherwise only load symbols for libs that match. Example: "foo.so;bar.so"

File Name:
Src\vscode-extensions\vscode-cpptools.xlf

Query:
Do these sentences mean the following?
The list of filenames (wildcards allowed) separated by semicolons ';'.modifies behavior of LoadAll.
Also does "lib" mean library?

**Comment by Colengms** [comment]
@pieandcakes or @WardenGnaw , can you comment?

**Comment by pieandcakes** [comment]
yes, that is correct. `lib` = `library`
