### ISSUE TITLE
No features of the language service working in VSCode

### ISSUE THREAD

**Issue by xoxota99** [microsoft/vscode-cpptools#4352]
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Open a .cpp or .h file
2. Attempt to Cmd-click any normally clickable thing (Class name, variable name, include file, etc). Observe infinite spinner (knight-rider light across top of editor tabs).
3. Attempt to auto-complete (Cmd-Space). Same thing.
4. Save the file. Even though autoformat on save is enabled, observe no formatting occurs.
5. formatting colors are also "messed up" (comments are half-green, half-yellow, other effects)

Does this issue occur when all extensions are disabled?: Yes. All C++ editor features will randomly stop working. A restart is required (and sometimes even that doesn't work) to restore this functionality.

**Comment by sean-mcmanus** [comment]
Does this repro with or without the C/C++ extension?

**Comment by sean-mcmanus** [comment]
If you're seeing the Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin process repeatedly crash/disappear after hoving, then it's likely a duplicate of bug https://github.com/microsoft/vscode-cpptools/issues/4302 .

**Comment by sean-mcmanus** [comment]
However, the "infinite spinner" and format failure seems to imply the main process is not available and not just the IntelliSense process. Do you see any error messages in the C/C++ log or via Toggle Developer Console?

**Comment by xoxota99** [comment]
> Does this repro with or without the C/C++ extension?

With the C++ Extension. 

> If you're seeing the Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin process repeatedly crash/disappear after hoving, then it's likely a duplicate of bug #4302 .

I will check that next time this happens.



> However, the "infinite spinner" and format failure seems to imply the main process is not available and not just the IntelliSense process. Do you see any error messages in the C/C++ log or via Toggle Developer Console?

I don't know where those are. Can you tell me how to find them?

**Comment by sean-mcmanus** [comment]
The C/C++ error log should be in the VS Code Output pane (if an error was written too it), see https://code.visualstudio.com/docs/cpp/enable-logging-cpp
. The Toggle Developer Console is available in the Help menu.

**Comment by bobbrow** [comment]
At this time we don't have enough information to investigate this issue. If you are able to provide some additional information for us, we can reopen this issue and investigate further. Thank you!
