### ISSUE TITLE
Repeating working dir on opened problems, can't find the file to go to line 

### ISSUE THREAD

**Issue by NULL0B** [microsoft/vscode-cpptools#4355]
Im working on /root/Desktop/Project/file.c  in latest vscode stable and i have warnings on my code:
Example:
Under Problems Tab on vscode:
file.c
 |----"warning ... gcc[5,30] "

So when i touch the warning to go there vscode thows an error msg "Unable to open file.c. Unable to read /root/Desktop/Project/root/Desktop/Project/file.c"
it seems that is repeating the working folder in the find path.

**Comment by sean-mcmanus** [comment]
This should be fixed by https://github.com/microsoft/vscode-cpptools/pull/3916. As a workaround, you should be able to change the problemMatcher for your build task to use a different fileLocation, such as "autoDetect" or "absolute".

**Comment by bobbrow** [comment]
This is fixed in recent versions of the extension.
