### ISSUE TITLE
Can't debug c++ program

### ISSUE THREAD

**Issue by BigZG** [microsoft/vscode-cpptools#4358]
Issue Type: <b>Bug</b>

I think i had configurate the c++ extension correctly,but i still can't lauch c++ program debug.This make me angry,and i does't show any message to tell me what 's wrong,it just let me keep waitting.

Extension version: 0.25.1
VS Code version: Code - Insiders 1.39.0-insider (601e3e0762ac93e03cfef8336be8223bf32754e1, 2019-09-30T07:41:01.671Z)
OS version: Windows_NT x64 10.0.18990

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (12.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by WardenGnaw** [comment]
To help us further investigate this issue, can you share your `launch.json`?

**Comment by BigZG** [comment]
> To help us further investigate this issue, can you share your launch.json?

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/school_experiment/Test4/a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "c++(gcc)"
        }
    ]
}

Here is my launch.json.

**Comment by WardenGnaw** [comment]
I'm not seeing any issues with your `launch.json` either. Could you also provide your `tasks.json` and [enable logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_logging-for-mi-debuggers) and see what output you get?

**Comment by BigZG** [comment]
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "c++(gcc)",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g",
                "${workspaceFolder}/school_experiment/Test4/Ex_Student_1.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

Here is my tasks.json.And i had try to enabble logging,but i didn't get any output,
