### ISSUE TITLE
Function inside function marks error

### ISSUE THREAD

**Issue by IgPugliese** [microsoft/vscode-cpptools#4360]
Issue Type: <b>Bug</b>

int a(){
bool b(){ <- here marks error
return false;
}
return 0;
}

Extension version: 0.25.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.0.0-29-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
How are you getting that to compile? What compiler and settings are you using?

**Comment by IgPugliese** [comment]
here is all the info i think you need:
`code -v
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64`

https://imgur.com/a/KuulOoh

**Comment by sean-mcmanus** [comment]
Our parser doesn't currently handle the GCC nested functions extension. We're tracking this with https://github.com/microsoft/vscode-cpptools/issues/1035 .
