### ISSUE TITLE
vscode-cpptools's code colorization breaks with c++17

### ISSUE THREAD

**Issue by GoToCoding** [microsoft/vscode-cpptools#4362]
### vscode-cpptools's code colorization breaks after writing some lines with c++17 code

- OS and Version: OS: Darwin x64 18.6.0
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.25.1
- Other extensions you installed: [remote ssh](https://code.visualstudio.com/docs/remote/ssh) only.

VSCode can't color lines with code like next:
```
std::pair<int, int> somePair{1, 2};
const auto& [x, y] = somePair;
int z = 3;
for (int i = 0; i < n; i++) {
    // ...
}
```
![image](https://user-images.githubusercontent.com/16542586/65974508-b9249600-e475-11e9-90c9-42fb57368b05.png)

If you delete line with `const auto& [x, y] = somePair;`, other code get color:

(look to 3rd and 4th lines)
![image](https://user-images.githubusercontent.com/16542586/65974659-fa1caa80-e475-11e9-9e1f-4ab94405cedc.png)

To reproduce you can just create cpp file and paste code given above and set `cppStandard` to `c++17`

**Comment by Colengms** [comment]
Hi @GoToCoding 

The C/C++ extension provides semantic colorization, but syntactic colorization is coming from VS Code and the TextMate grammar is uses.  The TextMate grammar for C and C++ in VS Code is contributed by Jeff Hykin.  You can get his latest grammar, which may not have made it into VS Code yet, try his 'Better C++ Syntax' extension.  His repo is here: https://github.com/jeff-hykin/cpp-textmate-grammar

I'm able to repro, but not able to with the latest Better C++ Syntax extension.  I believe that would imply the issue has already been addressed and it's just a matter of VS Code picking up his latest.

**Comment by GoToCoding** [comment]
Hi @Colengms

[Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) plugin really helps, thank you!
