### ISSUE TITLE
Fit and Finish issues for v.1.0

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#4364]
- [x] Rename language server binaries (and update build pipelines + resource.in on Windows)
  * cpptools.exe (win32)
  * cpptools (linux/mac)
  * cpptools-srv.exe (win32)
  * cpptools-srv (linux/mac)
- [x] Update the "FileDescription" of the language service binary (for Windows)
- [x] Rename settings with non-conforming names (e.g. clang_format)
  - Consider rename of `C_Cpp` -> `cpptools`
- [x] Remove unneeded node_modules from vsix since they are webpacked.

**Comment by kjemeyer** [comment]
Hi Bob,

I am using Fedora 30 and it looks like this change is causing issues for me.

"Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at /home/kmeyer/.vscode/extensions/ms-vscode.cpptools-0.27.0/bin/cpptools"

When I go to that directory there is no cpptools file.
![image](https://user-images.githubusercontent.com/25483994/78070924-9878c280-736a-11ea-86cc-420610c4363a.png)

Is it possible that linux missed the update?

The extension version is .27 and the vscode version is 1.43.2. In case there was a stale config, I deleted my .vscode directory, .config/Code directory and reinstalled the vscode binary.

Let me know what you think.

Thanks,

Best.

Kevin

**Comment by sean-mcmanus** [comment]
@kjemeyer Is your OS 32-bit or 64-bit? You used the normal online install path and not the manually installed vsix, right?

**Comment by kjemeyer** [comment]
My OS is 64 bit. I was able to resolve the issue by installing using vsix and giving cpptools and cpptools-srv executable permissions

**Comment by kjemeyer** [comment]
(chmod +x)

**Comment by sean-mcmanus** [comment]
@kjemeyer It's possible you encountered some random networking issue that caused a failure with our online download. Using the vsix should be a workaround, but it should not normally require changing executable permissions since our vsix is supposed to do that already (if not, that would be another bug). Normally, the online vsix should give
```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)' (9321 KB)  Done!
Downloading package 'ClangFormat (Linux / x86_64)' (894 KB)  Done!
Downloading package 'Mono Framework Assemblies' (5368 KB)  Done!
Downloading package 'Mono Runtime (Linux / x86_64)' (1862 KB)  Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Installing package 'ClangFormat (Linux / x86_64)'
Installing package 'Mono Framework Assemblies'
Installing package 'Mono Runtime (Linux / x86_64)'

Finished installing dependencies
```
from using the download from https://go.microsoft.com/fwlink/?linkid=2125055 .

**Comment by kjemeyer** [comment]
Appreciate the quick response :) I will let you know if I encounter issues when I upgrade the extension next. Btw vscode is great!
