### ISSUE TITLE
Feature Request: Group Results of Find All References

### ISSUE THREAD

**Issue by borbmizzet** [microsoft/vscode-cpptools#4366]
**Type: LanguageService**

Please add options in the Find All References View to group results of Find All References by:

- File, Type
- File, Type, Member
- File, Type.Member
- Namespace
- Namespace, File, Type
- Namespace, File, Type, Member
- Namespace, File, Type.Member
- Directory Structure

Note: Members could be global (such as in C), in which case the Type would be ignored.  Global members could be namespaceless (such as in C), in which case the namespace would be listed as "global namespace".

I use this functionality in Resharper C++ extensively, which is currently the main thing preventing me from making the switch to VS Code.

**Comment by sean-mcmanus** [comment]
We have an improved UI at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0-insiders . But it may not have all the grouping options you want yet.

**Comment by borbmizzet** [comment]
As far as I can tell, 0.26 only has Group-By-File.  Only slightly more useful than a standard grep/find-all.  Is the Find All References functionality context-aware at all internally?

**Comment by sean-mcmanus** [comment]
The context-awareness (or type checking) is shown for "confirmed results" which are reported in the top section. If you don't have any results there then the IntelliSense type checking could be failing somehow. The "other results" can group by file or by "reference type".
