### ISSUE TITLE
Rename during Find All References doesn't show the "canceled" references results.

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4369]
1. Find All References.
2. Rename before the Find All References is finished.

Bug: The Find All References results are not updated with the "canceled" (preview) state.

May not be high enough priority to fix?

**Comment by Colengms** [comment]
@sean-mcmanus Is this issue still valid?  I see the same behavior with regards to the FAR results when I issue a Rename while it's in progress, as I see when just cancelling the FAR request.

**Comment by sean-mcmanus** [comment]
Yeah, I'm not reproing it now.
