### ISSUE TITLE
Usage of "struct foo* f;" in C incorrectly generates a declaration for "foo"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4383]
Use
```
typedef struct foo
{
	struct foo* f;
} foo;
```

The Outline view incorrectly shows "foo::foo" being a declaration.

This bug has existed in VS for a long time, so it's probably too low priority for them to fix.

https://developercommunity.visualstudio.com/content/problem/759968/usage-of-struct-foo-f-in-c-incorrectly-generates-a.html

**Comment by ljhm** [comment]
clangd doesn't have this issue, why you still can't fix this?

llvm-vs-code-extensions.vscode-clangd
![llvm-vs-code-extensions vscode-clangd](https://user-images.githubusercontent.com/9011764/180245872-166340d1-94e4-4b57-a966-b525f28295c8.png)

ms-vscode.cpptools
![ms-vscode cpptools](https://user-images.githubusercontent.com/9011764/180246028-719927ff-2f83-448b-a126-4bb4942321ec.png)

**Comment by sean-mcmanus** [comment]
@ljhm We're considering adding a setting to enabling tag parsing in C mode, which would fix this: https://github.com/microsoft/vscode-cpptools/issues/9570

**Comment by bobbrow** [comment]
The issue reported to Visual Studio was closed as "lower priority." Unfortunately, this means that a fix is not likely coming to VS Code either.
