### ISSUE TITLE
IntelliSense is different between header file and source file

### ISSUE THREAD

**Issue by zhang456xi** [microsoft/vscode-cpptools#4387]
**Type: C/C++**

**Describe the bug**
- OS and Version: Windows 10 Version 1903
- VS Code Version:1.38.1
- C/C++ Extension Version:0.25.1
- Other extensions you installed (and if the issue persists after disabling them): Remote-WSL
- A clear and concise description of what the bug is.
The macro \_WIN32 is different between header file and source file when open folder in Windows

**Screenshots**
![image](https://user-images.githubusercontent.com/24366039/66222549-00c05180-e704-11e9-8709-44f042800b33.png)

The Toolchain is gcc, but the macro \_WIN32 is different in *.c file, *.cpp file and *.h file 
`{
    "configurations": [
        {
            "name": "Demo",
            "includePath": [
                "${workspaceFolder}/"
            ],
            "compilerPath": "/usr/bin/gcc",
            "intelliSenseMode": "gcc-x86"
        }
    ],
    "version": 4
}`

**Comment by sean-mcmanus** [comment]
Can you run C/C++: Log Diagnostics commands with each file active to compare the output and look for a problem? 0.25.1 had a bug with gcc-x86 not being used, so you should see "gcc-x64" mode used...it looks like it's somehow not able to find a C++ compiler and falling back to cl.exe mode. Are you sure you have a g++ installed? Can you change your "compilerPath" to "/usr/bin/g++"? It looks like your ".c" file is working.

**Comment by zhang456xi** [comment]
thank you! there is no g++ install on WSL but install on Windows by MinGW.
