### ISSUE TITLE
More configurable builds for C/C++

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cpptools#439]
From @Rn86. Ref: https://github.com/Microsoft/vscode/issues/18227

Feature Request

Using cpptool you can define configurations. Those configurations can only be used just for include paths and symbols databases. It would be nice to use those configurations in build to specify compilation flags (e.g. debug/release build). I would like to be able to change those configurations and build accordingly to specified configuration. In other words i want to be able to add compilation arguments for specific configuration only. Now its only possible to change your build by modifying tasks.json file, which is not a big deal but still.

**Comment by pieandcakes** [comment]
@Rn86 you can add multiple tasks and call them from `launch.json` and then duplicate your debugging configurations and specify one for Release or Debug. Build is a feature provided by VS Code itself through `task.json`.
