### ISSUE TITLE
C/C++ IntelliSense incorrect error when referencing a variable in an anonymous namespace

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4391]
Use the code below in a C++ file:
```
namespace {
    int i;  // defines ::(unique)::i
}
void f() {
    i++;  // increments ::(unique)::i
}
 
namespace A {
    namespace {
        int i; // A::(unique)::i
        int j; // A::(unique)::j
    }
    void g() { i++; } // A::unique::i++
}
 
using namespace A; // introduces all names from A into global namespace
void h() {
    A::i++; // ok, increments ::A::(unique)::i
    j++;    // ok, increments ::A::(unique)::j
}
```
Bug: There’s a “i” is ambiguous IntelliSense error when the code compiles.
The code is from https://en.cppreference.com/w/cpp/language/namespace 

I reported a bug with VS at https://developercommunity.visualstudio.com/content/problem/761600/cc-intellisense-incorrect-error-when-referencing-a.html .

**Comment by bobbrow** [comment]
The issue reported to Visual Studio was closed as "lower priority." Unfortunately, this means that a fix is not likely to make it to VS Code either.
