### ISSUE TITLE
[MinGW] "break main" fails to create a breakpoint in specific scenarios, preventing execution

### ISSUE THREAD

**Issue by gabeluci** [microsoft/vscode-cpptools#4392]
Type: Debugger

- OS and Version: Windows 10.0.17763
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.25.1

This is not technically VS Code's problem, but hear me out.

When starting to debug, VS Code issues the `break main` command to GDB to set a breakpoint at the `main()` function before it runs (even when `stopAtEntry` is `false`).

In some rare cases, execution stops with:

>Command aborted. See the output window for additional details.

But the output window says nothing. And you simply cannot continue. Any attempt to continue just gives the same message and stops. Only after enabling `engineLogging`, can you see the real problem:

```
1: (620) <-1012-break-insert -f main
1: (630) ->1012^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0000000140008450",func="main",file="../crt/crt0_c.c",fullname="/build/mingw-w64/mingw-w64-crt/build/../crt/crt0_c.c",line="17",thread-groups=["i1"],times="0",original-location="main"}

...

1: (1228) ->&"Warning:\n"
1: (1228) ->&"Cannot insert breakpoint 1.\n"
1: (1228) ->&"Cannot access memory at address 0x140008450\n"
1: (1228) ->&"\n"
1: (1228) ->1016^error,msg="Command aborted."
```

For whatever reason I don't understand, the memory location that GDB determined where `main()` is, isn't accessible.

**To Reproduce**

This can be reproduced in GDB in the terminal. It happens when debugging VLC 3.0.9, for example. You can grab a debug version of the nightlies [here](https://nightlies.videolan.org/build/win64/last-3/) and run `gdb vlc.exe`:

```
(gdb) break main
Breakpoint 1 at 0x140008450: file ../crt/crt0_c.c, line 17.
(gdb) run
Starting program: C:\vlc\vlc-3.0\win64\vlc-3.0.9\vlc.exe
[New Thread 18168.0x1230]
[New Thread 18168.0x4858]
[New Thread 18168.0x234]
[New Thread 18168.0x1588]
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x140008450

Command aborted.
(gdb) continue
Continuing.
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x140008450

Command aborted.
(gdb) continue
Continuing.
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x140008450

Command aborted.
(gdb)
```

You see that any attempt to `continue` just repeats the failure and stops, unless you delete the breakpoint before continuing.

**Proposed solution 1**

VS Code could work around this by using `starti` instead of `break main` / `run`, since that works just fine:

```
(gdb) starti
Starting program: C:\vlc\vlc-3.0\win64\vlc-3.0.9\vlc.exe
[New Thread 22196.0x5384]
[New Thread 22196.0x1e94]
[New Thread 22196.0xe6c]
[New Thread 22196.0x1960]

Thread 1 stopped.
0x00007ffbffb22dbd in ntdll!LdrInitShimEngineDynamic () from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) continue
```

It breaks after execution starts, and you can continue normally.

I know that `starti` isn't exactly equivalent to `break main` / `run`. The [documentation](https://sourceware.org/gdb/current/onlinedocs/gdb/Starting.html) says:

>The ‘starti’ command does the equivalent of setting a temporary breakpoint at the first instruction of a program’s execution and then invoking the ‘run’ command. For programs containing an elaboration phase, the starti command will stop execution at the start of the elaboration phase.

So it depends on why VS Code automatically uses `break main`. Does it _really_ need to break in `main()`? Or does it just need to break any time after execution starts?

The `starti` command was introduced in GDB 8.1, so it may be wise to confirm it's available before attempting to use it.

**Proposed solution 2**

If it doesn't _really_ need to break after execution starts when `stopAtEntry` is `false`, maybe it could just.... not do that?

**Proposed solution 3**

VS Code could detect the bad breakpoint (by seeing "Cannot insert breakpoint 1") and automatically remove it, so at least you can continue execution.

**Additional Info**

This problem has appeared in a couple other issues that I could find, although they may not be exactly equivalent  to what I describe since those seem to be user-defined breakpoints:
https://github.com/Microsoft/vscode-cpptools/issues/2283
https://github.com/microsoft/vscode-cpptools/issues/4339

But even in those cases, I'm curious to know if it works with setting the breakpoint after execution starts with `starti`.

An answer on StackOverflow that attempts to answer why this happens: https://stackoverflow.com/a/32233750/1202807

**Current workarounds**

1. Define `customLaunchSetupCommands`, which stops VS Code from using `break main`, but I have to define the `target exec` command and the architecture myself:

    "customLaunchSetupCommands": [
        { "text": "target exec {same as whatever you put in 'program'}", "description": "target exec", "ignoreFailures": false },
    ],
    "targetArchitecture": "x64"

2. When execution stops at the error, use `-exec delete 1` in the debug console to delete the automatically-created breakpoint, then continue.

**Comment by pieandcakes** [comment]
@gabeluci Thank you for doing the research. It looks like there isn't a `gdb/mi` [command](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Program-Execution.html#GDB_002fMI-Program-Execution) for `starti` although there is one for `start`. 

We use the breakpoint at `main` to set up the debugging session. If the user specifies `stopAtEntry` to be `true` then we don't automatically continue. 

From one of the comments on the stackoverflow link you provided, it looks like it is specific to MinGW?

**Comment by gabeluci** [comment]
Debugging with MinGW, yes. In my case (using VLC 3 as an example) the binaries were built on Linux (cross-compiled for Windows). I haven't actually tried building with MinGW.

**Comment by galinart** [comment]
@pieandcakes the issue is still relevant VS Code 1.44.2 and MSYS2 GNU gdb (GDB) 8.2.1.

**"stopAtEntry": false doesn't help.**

**Comment by pieandcakes** [comment]
@WardenGnaw

**Comment by idevices-mvicuna** [comment]
This happens when attaching to gdbserver as well. If the app being debugged is waiting at spot where the initial breakpoint setting and variable window update raise exceptions you can't continue. Manually using gdb to attach to the remote will work fine.

Tested with:
Ubuntu 18.04
VSCode 1.38.1
ms-vscode.cpptools 0.27.1

**Comment by cswrd** [comment]
The same error messages may appear if you run incompatible versions of gdb and gdbserver. In our case we accidentally used the wrong gdb. It was configured at built time for the wrong target, resulting in violating:

> _--target=target_ Configure GDB for cross-debugging programs running on the specified target. Without this option, GDB is configured to debug programs that run on the same machine (host) as GDB itself.
