### ISSUE TITLE
false error accessing member of element of array of anonymous struct inside a struct

### ISSUE THREAD

**Issue by TinBryn** [microsoft/vscode-cpptools#4393]
Issue Type: <b>Bug (corner case)</b>

I have a struct of the form similar to this
`
struct foo {
    struct {
        int bar;
    } bars[24];
};
`

I'm accessing a `bar` with `f.bars[i].bar;` but it shows the error "expression must have pointer-to-object type". But the code compiles fine regardless.

As it is an anonymous inner struct I don't see a way to break this expression up, and I don't have access to change the struct.

Extension version: 0.26.0-insiders2
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.15.0-65-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 2111)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 0|
|Memory (System)|3.64GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
I'm not able to repro that error. Can you give more info on your configuration, such as from C/C++: Log Diagnostics?

**Comment by TinBryn** [comment]
Strange, I've tried restarting vscode a few times to see if that fixed it, but suddenly it actually fixed it.

If it comes back it's from my repo https://github.com/TinBryn/CITS2002-SIFS-2019 in library/mkdir.c
and the header library/sifs-internal.h

I'm actively working on this, but the problem expression is `dirblock.entries[i].blockID`

**Comment by sean-mcmanus** [comment]
It could be an issue with a stale ipch (IntelliSense cache file) that went away after the incorrect cache file got updated.

**Comment by TinBryn** [comment]
Sounds plausible, what would have triggered the cache to update? The issue went away when I closed an reopened the workspace, but not when I closed and reopened vscode.

**Comment by sean-mcmanus** [comment]
The cache would update after an edit to the header file. Closing and reopening the workspace should be identical to closing/reopening vscode. Let us know if you figure out a way to repro this in the future.
