### ISSUE TITLE
Status bar C/C++ extension field no longer shows function name

### ISSUE THREAD

**Issue by iazzam** [microsoft/vscode-cpptools#4395]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04.3 LTS
- VS Code Version: 1.38.1
- C/C++ Extension Version: 0.26.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): Astyle, Go, vscode-proto3. Issue persists after disabling all other extensions.
- A clear and concise description of what the bug is.
The status bar used to show the name of the function that the cursor is currently in. With the update from version 0.25.1 to 0.26, the function name is no longer being displayed.

**To Reproduce**

1. Open any development folder
2. Open a C++ file with any function
3. Place the cursor inside the implementation of a function
4. The status bar does not show the name of the function

**Expected behavior**

The status bar shows the name of the function as it used to do in version 0.25.1

**Screenshots**

**Additional context**

**Comment by bobbrow** [comment]
This is actually expected.  We removed our custom UI and are now using the common "breadcrumbs" UI provided by VS Code which is at the top of the file just under the tab name.

![image](https://user-images.githubusercontent.com/12818240/66335847-b5b76180-e8f0-11e9-855c-2c925c9e4e4f.png)

The following settings control its appearance:

![image](https://user-images.githubusercontent.com/12818240/66335926-e13a4c00-e8f0-11e9-9fbc-1aa84373b1fc.png)
