### ISSUE TITLE
No compiler in config UI with VS build tools

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4396]
> What do you mean by vscode-cpptools "cannot detect" your compiler? What error are you seeing? What does "C/C++: Log Diagnostics" show?

I mean this:
vscode-cpptools UI:
![image](https://user-images.githubusercontent.com/9786086/66281336-1345b100-e8e5-11e9-8fb3-24dc917e318d.png)

CMake Tools:
![image](https://user-images.githubusercontent.com/9786086/66281345-1e98dc80-e8e5-11e9-9a6d-b230a680b7e6.png)

_Originally posted by @Gargony in https://github.com/microsoft/vscode-cpptools/issues/3270#issuecomment-538818848_

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
