### ISSUE TITLE
Using network and disk

### ISSUE THREAD

**Issue by sean93park** [microsoft/vscode-cpptools#44]
VSCode.Cpp.Extension.exe (v 0.5.0) is keep using network about 9Mbps steady number (in task manager), maybe I'm using samba mounted disk from my Linux box for my project.
- For testing, left it with no source file opened. 
- After uninstalling this extension, my HDD is now quiet.

**Comment by sridmad** [comment]
We will use #11 to track issues related to networking, #6 for loading the extension on startup
