### ISSUE TITLE
The configuration of the c/c++ in Debian8, when I was in debug, when there is no input, the debuge console can correct output results, when the input function, in debug console, only one line of output, the output is not complete. I would like to ask, when the output, how to call their own system terminal.

### ISSUE THREAD

**Issue by Roobt1** [microsoft/vscode-cpptools#441]
//tasks.json
{
    "version": "0.1.0",
    "command": "gcc",
    "externalConsole": true,
    "args": ["-g", "${file}", "-o", "${file}.o"],
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
}
//launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "gdb",
            "request": "launch",
            "target": "${file}.o",
            "cwd": "${workspaceRoot}",
            
            "preLaunchTask": "gcc"
           
        }
    ]
}

**Comment by pieandcakes** [comment]
@Roobt1 Based on your `launch.json` you are not using this extension. Please read the Readme.MD that is part of your extension and file an issue on their page.
