### ISSUE TITLE
Signature popup not opening without arguments

### ISSUE THREAD

**Issue by xahon** [microsoft/vscode-cpptools#4413]
**Type: LanguageService**

Signature popup won't open if you just opened a parenthesis.
```
std::deque<sCar*> someQueue(/* ctrl+shift + space here - nothing happens */);
std::deque<sCar*> someQueue("", /* ctrl+shift + space here - a popup opened */);
```
Note: the second line has invalid parameter type `string`, deque doesn't have any like that

**Describe the bug**
- OS and Version: Ubuntu 18.04.3
- VS Code Version: 
Version: 1.39.0-insider
Commit: c8252b63f547674d2faf361d4181bb76b0b5f81a
Date: 2019-10-04T09:24:45.417Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-27-generic

- C/C++ Extension Version: 0.26.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): I've disabled all other extensions

**To Reproduce**
```
std::deque<sCar*> collidables(/* trigger popup here */);
std::deque<sCar*> collidables("", /* and here */);
```

**Expected behavior**
Popup opened in both examples

~~I'm not really sure if it is c++ extensions issue and not vscode's~~
No such issue for javascript

**Comment by bobbrow** [comment]
Some background on this particular issue can be found here: https://en.wikipedia.org/wiki/Most_vexing_parse

It is recommended to use `{}` for passing parameters to the constructor.  The extension should do the right thing when you use `{}` instead of `()`
