### ISSUE TITLE
can't find headers files C++ during compilation

### ISSUE THREAD

**Issue by BastG57** [microsoft/vscode-cpptools#4417]
Hi,
I swear i've spend A DAY searching for it, but I cant find a solution (even in past issues) so i'm now searching for help
To be clearer here is what the concerned file tree looks like :
  ```
>ProjectTP
   > Sensor 
        - Sensor.cpp
        - Sensor.h
   > Server
        - Server.cpp
        - Server.h
```
I want to compile Server.cpp (where my main function is), which includes Sensor.h, but I keep getting the same error message at the compilation (Using code runner and g++, windows 10 x64)

> " Server.cpp:2:10: fatal error: Sensor.h: No such file or directory
>  #include "Sensor.h"
> compilation terminated. "

Ive tried all sort of configuration from Intellisense IncludePath settings, the c_cpp_settings.json..... 
Feel free to ask me whatever you need from my configuration to help you help me :)
Thanks to all

(Here is my c_cpp_settins.json if it can help)
```
`{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/Sensor"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "D:/MinGW/bin/g++.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "${default}"
        }
     ],
    "version": 4
}
`
```

**Comment by michelleangela** [comment]
The C/C++ extension does not compile code but provides IntelliSense or code editing features.

How are you trying to build? Are you using `tasks.json`, via command line, or some other method?

If you're using a task in `tasks.json` to build your code, such as this [build task example](https://code.visualstudio.com/docs/cpp/config-mingw#_create-a-build-task), does it specify the required source and header files to compile?

**Comment by michelleangela** [comment]
I missed the part that you're using "code runner" for compilation. I would try posting your build issue at  [code runner issues page](https://github.com/formulahendry/vscode-code-runner/issues) and provide them with any "code runner" related configurations.

**Comment by BastG57** [comment]
> 
> 
> I missed the part that you're using "code runner" for compilation. I would try posting your build issue at [code runner issues page](https://github.com/formulahendry/vscode-code-runner/issues) and provide them with any "code runner" related configurations.

Thanks for suggestion, i've just tried to uninstall code runner, and compile directly with g++ from terminal, but I get the exact same error : (

**Comment by michelleangela** [comment]
Are you passing the the absolute path to the header file (Sensor.h) to the compiler arguments? Can you share the command line and arguments you're using?

**Comment by BastG57** [comment]
I tried somthing like that 
D:/MinGW/bin/g++.exe -g c:\~FilePath\Server.cpp -o c:\~FileDestination\Server.exe
So I didnt mention Sensor.h, but I dont understand why I should! (Already included in Server.cpp needed library?)
That dosnt seems logical, I have like 10 different classes (with Inheritances) in the program,  so that means I should write them all?? And what happens when you have thousands of lines of code......

**Comment by michelleangela** [comment]
When the header files you include in a source file (*.cpp) are not in the same folder as the source file that `#include` them, then the compiler will need to know the path to the included header files that are located in a different folder.

You specify include paths to the g++ compiler by using the `-I` include compiler option. For example:
```
D:/MinGW/bin/g++.exe -g c:~FilePath\Server.cpp -I/SomeFolder/ProjectTP/Sensor -o c:~FileDestination\Server.exe 
```
You can also try to add the full path of the header file in a source file (`#include "/fullPath/someHeader.h"`), but that usually is not preferred.

**Comment by BastG57** [comment]
It worked with -I ! Thank you I didnt know that ^^
