### ISSUE TITLE
miDebuggerPath should search PATH

### ISSUE THREAD

**Issue by janjongboom** [microsoft/vscode-cpptools#442]
We use the GNU ARM cross-compiler to build and debug embedded applications. These tools are normally somewhere in the `PATH` of the user, but the actual location will differ depending on the Linux distribution / package manager used. I figured we could do something like:

```json
"osx": {
    "MIDebuggerPath": "arm-none-eabi-gdb"
}
```

But this fails with 'Unable to start debugging. The value of miDebuggerPath is invalid'.

I think that if `MIDebuggerPath` and `debugServerPath` are not absolute, PATH should be searched for these binaries, similar to how PATH is searched when these paths are left empty.

/cc @sg-

**Comment by janjongboom** [comment]
I guess this would work (against microsoft/IMEngine) (and similar patch needed for debugServerPath) but I can't get Visual Studio to work to build IMEngine:

```diff
diff --git a/src/MICore/LaunchOptions.cs b/src/MICore/LaunchOptions.cs
index 6ecbb28..74790f5 100644
--- a/src/MICore/LaunchOptions.cs
+++ b/src/MICore/LaunchOptions.cs
@@ -274,6 +274,17 @@ namespace MICore
                 }
             }

+            // If no path, but just a binary name is provided, search the user's $PATH for the binary
+            if (!File.Exists(miDebuggerPath) && miDebuggerPath.IndexOfAny(Path.GetInvalidFileNameChars() == 0))
+            {
+                miDebuggerPath = LocalLaunchOptions.ResolveFromPath(miDebuggerPath);
+
+                if (String.IsNullOrEmpty(miDebuggerPath))
+                {
+                    throw new InvalidLaunchOptionsException(MICoreResources.Error_NoMiDebuggerPath);
+                }
+            }
+
             var options = new LocalLaunchOptions(
                 RequireAttribute(miDebuggerPath, "MIDebuggerPath"),
                 source.MIDebuggerServerAddress,
```

**Comment by sg-** [comment]
@pieandcakes Any update on a planned release version for this?

**Comment by pieandcakes** [comment]
@sg- I am taking a look at it this week. If testing goes well and it is approved, it should be our next release sometime this month.

**Comment by pieandcakes** [comment]
@janjongboom I've submitted your proposed fix. We can't do the same for debugServerPath because the problem is that its the machinename and port that its expecting to connect to so its not searchable.

**Comment by pieandcakes** [comment]
@janjongboom this change is in our `0.10.2` release.

**Comment by janjongboom** [comment]
\o/

**Comment by Jojendersie** [comment]
The documentation on https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md is not consistent with the implementation of this feature.
It says "When unspecified, it will search the operating system's PATH...", which it doesn't. Not specifying the miDebuggerPath causes the error "Unable to start debugging. Launch options string provided by the project system is invalid. Unable to determine path to debugger. Please specify the "MIDebuggerPath" option."

FixA: The documentation should read "When only a filename is specified, it will search..."
FixB: Change the implementation to search for gdb on PATH if miDebuggerPath is not specified.

**Comment by pieandcakes** [comment]
@janjongboom It was supposed to be FixA. Thanks for reporting it. I'll look to get it updated.
