### ISSUE TITLE
Extension does not work with non-ASCII path

### ISSUE THREAD

**Issue by Byongsoo** [microsoft/vscode-cpptools#4420]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Pro
- VS Code Version: 1.39.1
- C/C++ Extension Version: Version 0.26.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them):
![image](https://user-images.githubusercontent.com/56447120/66665350-53ac8280-ec89-11e9-8d72-b70b5022f506.png)
- A clear and concise description of what the bug is.

It is very simple code.
**But I can not see the functions of the string class.**

![image](https://user-images.githubusercontent.com/56447120/66665397-6a52d980-ec89-11e9-9f40-5a6c07391a3e.png)

**To Reproduce**

1. Make a folder
2. Make new file.
3. write simple code. (see below)

#include <iostream>
#include <string>

int main(void)
{
    std::string A;
    A.
}

**Expected behavior**

When wirte "A." in the upper code, I want to see the functions and vriables of the std::string class. 

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Can you disable the "C++ IntelliSense" extension? That might be interfering with our "C/C++" extension.

**Comment by Byongsoo** [comment]
Hi sean-mcmanus,
I have uninstalled the "C++ IntelliSense" and re-started the VS code.
But result is same.

![image](https://user-images.githubusercontent.com/56447120/66716596-6dc19e80-ee0a-11e9-8606-d1839850d14c.png)

![image](https://user-images.githubusercontent.com/56447120/66716599-75814300-ee0a-11e9-9ac7-c2d148716c9a.png)

Heare is my "c_cpp_properties.json" file.

{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17763.0",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}

**Comment by michelleangela** [comment]
Can you run the command `C/C++: Log Diagnostics` to verify the actual values from c_cpp_properties.json that are given to the language server?

**Comment by Byongsoo** [comment]
Here is resutl of command "C/C++: Log Diagnostics".


-------- Diagnostics - 2019. 10. 15. 오전 6:13:17
Version: 0.26.0-insiders3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.17763.0",
    "knownCompilers": [
        {
            "path": "C:\\MinGW\\bin\\gcc.exe",
            "isC": true
        },
        {
            "path": "C:\\MinGW\\bin\\g++.exe",
            "isC": false
        }
    ],
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.

![image](https://user-images.githubusercontent.com/56447120/66783715-7a7de980-ef13-11e9-83da-84700e0bcae6.png)

**Comment by michelleangela** [comment]
The values of the c_cpp_properties.json look okay, but the message "No active translation units" indicates that there are no IntelliSense language server working. Do you have the setting `C_Cpp.intelliSenseEngine` configured to something other than "Default"? Do you have the setting `C_Cpp.intelliSenseEngineFallback` to `Disabled`?

Another logging you can check is [language server log](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server), where it will show if a language server may be crashing or if it tries to fall back to tag parser.

**Comment by Byongsoo** [comment]
The C_CPP:IntellisenseEngineFallback has alread set to disable(Default)

![image](https://user-images.githubusercontent.com/56447120/66832478-f8360980-ef94-11e9-9a90-33d6b27be939.png)

I did not set any configuration related with C_Cpp.intelliSenseEngine.

When I check the language server log, I can find below error.
Do you know any solution to solve below error message?

C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\WDEXPRESS\VC\TOOLS\MSVC\14.16.27023\INCLUDE\CODEANALYSIS\SOURCEANNOTATIONS.H
Can not make process. Error : 267(���͸� �̸��� �ùٸ��� �ʽ��ϴ�.)
Can not make IntelliSense process.

**Comment by Byongsoo** [comment]
### Root Cause
I find the root cause!!!
I have got a hint from https://github.com/Microsoft/vscode-cpptools/issues/1560.

There is non-ASCII characters(Korean) in the user path.
This is root cause.
My case : "C:\Users\공"

VS code basic folders were made in the user path by default.
%LocalAppData%\Programs\Microsoft VS Code
%UserProfile%\.vscode
%AppData%\Code
%AppData%\Visual Studio Code

So if the extentions of VS code does not support non-ASCII characters, it can make the error.

### Solution
So I have changed the user folder name.(refer below URL).
https://www.youtube.com/watch?v=w5N2aaiToiQ
You can get the URL at the google.(Keyword is "windows 10 change user folder name")

Finally, I have check the intellisense was working well on my labtop.
![image](https://user-images.githubusercontent.com/56447120/66845229-a304f280-efaa-11e9-80d5-d574f3a9e676.png)

### Question
But I have a question.
Do you(C/C++ extention) have a plan to support the non-ASCII path?

Thank you.

**Comment by bobbrow** [comment]
Yes, we do plan to support this.  I thought we had already taken care of it, but it appears we lost track of the issue.  @Colengms or @michelleangela, can one of you work on a fix for this?

**Comment by michelleangela** [comment]
Duplicated this to #1560 and will close this issue.

**Comment by michelleangela** [comment]
@Byongsoo , I'm trying to reproduce the error 267, which means "The directory name is invalid", by using the Korean character 공 for a user name, but I could not reproduce it. The Windows OS language and VS Code were also set to Korean. Are there any other language settings you have configured on your laptop?

**Comment by Byongsoo** [comment]
@michelleangela, could you delete all below folders and re-insatall VS code?
%LocalAppData%\Programs\Microsoft VS Code
%UserProfile%.vscode
%AppData%\Code
%AppData%\Visual Studio Code

As far as I komw, there is no more language settings on my laptop.

**Comment by michelleangela** [comment]
@Byongsoo, thanks. Deleting and re-installing the VS Code files didn't repro the issue. However there was one more language settings that I changed which did caused the issue. You have to [change the Code Page](https://knowledgebase.progress.com/articles/Article/4677) to Korean

**Comment by Byongsoo** [comment]
@Michelleangela, It`s good(?) news. :)
I hope you fix this issue and release new version.
Thank you for supporting.

**Comment by michelleangela** [comment]
@Byongsoo, we're working on a fix and is targeted to be in 0.26.1 or next release.

**Comment by michelleangela** [comment]
Fixed in version 0.26.2-insiders, available at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders.
