### ISSUE TITLE
chs i18n improvement

### ISSUE THREAD

**Issue by zhangyafeikimi** [microsoft/vscode-cpptools#4422]
https://github.com/microsoft/vscode-cpptools/blob/master/Extension/i18n/chs/package.i18n.json
clang format被翻译成“clang 格式”, 建议保持英文不变.

".clang 格式文件", 应该是 ".clang_format 或者 _clang-format 文件", 这个参考这里:
https://clang.llvm.org/docs/ClangFormatStyleOptions.html
同时也参考英文的翻译:
https://github.com/microsoft/vscode-cpptools/blob/master/Extension/package.nls.json

**Comment by michelleangela** [comment]
Filed an internal issue for localization team to consider this improvement and update the string.

**Comment by michelleangela** [comment]
Issue resolved in pull request https://github.com/microsoft/vscode-cpptools/pull/4457

**Comment by michelleangela** [comment]
Change set included in 0.26.1

**Comment by leaon4** [comment]
@zhangyafeikimi 请教一下，如果关闭这个功能？其实这个功能有时反而没用。比如报错提示，英文提示反而对学习者更有帮助，搜索起来也更方便

**Comment by zhangyafeikimi** [comment]
@leaon4 你的问题是什么?

**Comment by leaon4** [comment]
@zhangyafeikimi 不好意思，“如何”打成了“如果”。是想请教一下如何关闭翻译功能，还是想看英文的报错提示信息。不知道如何配置

**Comment by zhangyafeikimi** [comment]
把语言插件停用就变成英文了
