### ISSUE TITLE
Any way to remove menu "Find All References"？

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#4425]
Hi Sean,
Currently I want to remove menu "Find All References" and register my own menu so that I can call cpptool "Find All References" to implement my own feature. Any way to remove this menu in cpptools code?

**Comment by Colengms** [comment]
Hi @Lennon925 .  We are not modifying the menu directly.  I believe Find All References appears in the context menu as a result of there being an Extension for that file type that either has registered a ReferenceProvider or has indicated that it supports the operation via the Language Server Protocol.  I'm not aware of a good way for you to patch this feature in one Extension using another Extension, without modifying the original extension (or without there being a VS Code feature to facilitate it).

**Comment by sean-mcmanus** [comment]
Yeah, our extension would need to add a setting to disable registering as a "Find All References" provider.

**Comment by Lennon925** [comment]
> Yeah, our extension would need to add a setting to disable registering as a "Find All References" provider.

Hi Sean, if you disable registering as a "Find All References", we will not be able to get results by vscode command "vscode.executeReferenceProvider". Unless you provide your own context menu and command. If so, we can call cpptools command to get references results and meanwhile you can remove "Find All References" this context-menu.

**Comment by sean-mcmanus** [comment]
VS Code itself is adding the "Find All References" command to the menu whenever an extension registers as a references provider. Did you have a suggestion of what change we could make? It sounds like it would require VS Code changes. Is this a problem with 0.25.1 and 0.26.0-insiders3?

**Comment by Lennon925** [comment]
> VS Code itself is adding the "Find All References" command to the menu whenever an extension registers as a references provider. Did you have a suggestion of what change we could make? It sounds like it would require VS Code changes. Is this a problem with 0.25.1 and 0.26.0-insiders3?

It's not very important and let it go.
