### ISSUE TITLE
Go To definition jumps to the wrong definition when using a lambda as an argument in a function

### ISSUE THREAD

**Issue by theFlyingCat04** [microsoft/vscode-cpptools#4426]
Hi there!

**Describe the bug**
- OS and Version: Linux Mint 19 (as well as inside a Cent OS docker image)
- VS Code Version: 1.30.1
- C/C++ Extension Version: ms-vscode.cpptools@0.26.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): doesn't matter, bug is also reproducible with all other extensions disabled
- Description: When you use a lambda function as an argument of another function and want to go to the definition of a parameter inside of the lambda, then you land on the definition of a std::function constructor instead.

**To Reproduce**
Example:
```c++
#include <string>
#include <functional>
#include <iostream>
#include <unordered_map>

class X {
public:
	void printMe () { std::cout << "printed X" << std::endl; }
};

class Registry {
public:
	void registerCallback(std::string name, std::function<void(X x)> func) {
		reg.emplace(name, func);
	}
private:
	std::unordered_map<std::string, std::function<void(X x)>> reg;
};

int main(int argc, char const *argv[]) {
	Registry r;
	r.registerCallback("test", [](X x){ x.printMe(); } );
	auto f = [](X x){ x.printMe(); };
	return 0;
}
```
When Pressing <kbd>F12</kbd> (for go to definition) while the cursor is on the call of the `printMe` method, then everything is allright and you land on the definition of this method. But when pressing  <kbd>F12</kbd> while the cursor is on the `X` inside the argument list (in the `r.registerCallback` line), then you'll land on the definition of the std::function constructor instead. If you'll press <kbd>F12</kbd> while the cursor is on the `X` on the `auto f = ` line, then you'll land on the definition of `class X` as expected.
Same behavior with the "peek definition" functionality.

**Expected behavior**
I expect to land on the definition of the function parameter when using the action "go to definition" every time.

**Screenshots**
Here are two screenshots showing the behavior described above. The first shows the wrong definition, the second one the correct one (both with the "peek definition" code action).
![vscode-cpp-bug-1](https://user-images.githubusercontent.com/32870282/66738718-6680ac00-ee6f-11e9-888a-23782bd48460.png)
![vscode-cpp-bug-2](https://user-images.githubusercontent.com/32870282/66738724-6aacc980-ee6f-11e9-9cf8-a73a00c8d17f.png)

Thanks in advance.
the flying cat

**Comment by Colengms** [comment]
Hi @theFlyingCat04 .  I was able to repro this issue in VS.  (VS and VS Code share some common code for IntelliSense).  I opened an issue against VS here: https://developercommunity.visualstudio.com/content/problem/776567/go-to-definition-goes-to-stdfunction-constructor-i.html

**Comment by theFlyingCat04** [comment]
Thanks @Colengms for the quick response. Let's see what the VS Team is able to do there.

**Comment by Colengms** [comment]
It looks like that issue was duped to: https://developercommunity.visualstudio.com/content/problem/661818/wrong-go-to-definition-location.html

I'd suggest up-voting it, as vote count is often used to set priorities.

**Comment by Colengms** [comment]
The tracked issue is fixed, and I'm no longer able to repro this issue in a recent build of the C/C++ Extension.  Closing as fixed.
