### ISSUE TITLE
Highlight issue with "constexpr static"

### ISSUE THREAD

**Issue by rianquinn** [microsoft/vscode-cpptools#4428]
**Type: LanguageService**
Highlighting

**Describe the bug**
- OS and Version: Any OS
- VS Code Version: 1.40.0
- C/C++ Extension Version: 0.25.1
- Other extensions you installed (and if the issue persists after disabling them): shows up with other extensions disabled
- A clear and concise description of what the bug is: The "constexpr" in "constexpr static" is not highlighted correctly. 

**To Reproduce**
1. Add the following code to a ".h" file
```cpp
struct A
{
    constexpr static void foo() {}
};
```
2. You should see the issue (funny how GitHub seems to get it right). 

**Expected behavior**
"constexpr" should be the same color as "static"

**Screenshots**
![image](https://user-images.githubusercontent.com/5932003/66763585-acea0100-ee97-11e9-948a-ff3e4e3c6991.png)

**Comment by Colengms** [comment]
Hi @rianquinn .  Syntactic colorization is provided by VS Code using TextMate grammar.  The C/C++ extension adds semantic colorization as a layer over VS Code's syntactic colorization.  An easy way to rule out semantic colorization is to set `C_Cpp.enhancedColorization` to `Disabled` and see if the issue still repros.  This issue does, so appears to be with syntactic colorization.

VS Code's TextMate grammar is provided by @jeff-hykin.  His repo is here: https://github.com/jeff-hykin/cpp-textmate-grammar  I'd suggest opening this issue there.

**Comment by rianquinn** [comment]
I think this is a general issue with highlighting as this seems to happen regardless of the keywords and more about the total number of decorators a function might have. For example:

![image](https://user-images.githubusercontent.com/5932003/66770348-ed9d4680-eea6-11e9-9035-a342f0c6f607.png)

![image](https://user-images.githubusercontent.com/5932003/66770395-0dcd0580-eea7-11e9-85de-acf75daddaed.png)

**Comment by rianquinn** [comment]
https://github.com/jeff-hykin/cpp-textmate-grammar/issues/398

**Comment by jeff-hykin** [comment]
Thanks @Colengms, I can confirm this is a C++ grammar issue and not a cpptools issue.

**Comment by rianquinn** [comment]
This appears to be fixed
