### ISSUE TITLE
Dim Inactive region not working

### ISSUE THREAD

**Issue by RogFedex** [microsoft/vscode-cpptools#4431]
Issue Type: <b>Bug</b>

Would expect the inactive regions are dimmed correctly based on definitions included in file that are forcedinclude 

Extension version: 0.26.0-insiders3
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (8.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @RogFedex .  In a simple example, inactive regions appear to be working as expected.

![image](https://user-images.githubusercontent.com/49173979/66773010-e0666480-ee72-11e9-8ce3-4ba0b0b0df16.png)

Can you provide an example?  Perhaps incorrect inactive regions are the symptom, and there is a configuration issue preventing the expected defines?

**Comment by RogFedex** [comment]
Hi,

It was working fine for me too but lately I’m seeing some issues after adding configurations forcedInclude in c_cpp_properties.json file with the location of header file where the definitions are included.. The definitions exit in multiple location across workspace and I would like to use the definition from specific header file and that is what I have added in forcedInclude. When I search for definition (f12) it jumps to this header file. However if the definition is 0 the code is not dimmed. The else part is not dimmed either.

Thanks
Prasad

**Comment by Colengms** [comment]
If there is a #else and code on neither side is dimmed, that would seem to point to IntelliSense failing to parse the file.  Is it possible that one or more of the forcedInclude's is not being found?  Or, are there any squiggles prior to the code expected to be dimmed that might refer to a earlier issue (include not found?) preventing the rest of the file from being processed?

Can you distill the repro down to a minimal example that you can share?

**Comment by RogFedex** [comment]
I remember disabling squiggles recently.. Will it be a reason for it ? How do we reenable it ? All forcedIncluded header files are valid and exist in the workspace. Yes #else and #if code are not dimmed

**Comment by Colengms** [comment]
Inactive region dimming is dependent on 2 settings.  IntelliSense needs to be enabled (`C_Cpp.intelliSenseEngine` set to `"Default"`).  And, `C_Cpp.dimInactiveRegions` needs to be set to `true`.  As far as I know, these 2 settings should be sufficient.

IntelliSense identifies inactive regions.  So, if there is something preventing intelliSense (such as headers not found, or code it's failing to parse due to a bug), that could result in failing to identify the regions as inactive.  You might check the C/C++ output channel for error processing IntelliSense for the file.  You might also try using the "Log Diagnostics" command to view the includes and defines that were used by IntelliSense to parse the file.

**Comment by RogFedex** [comment]
Ok, Thanks for the details. In my setup IntelliSense and dimInactiveRegions
are enabled. I added valid and existing files in forcedInlcude
in C_Cpp_properties.json and observed the issue of no dimming of either #if
and #else statements (for sometimes it was working good and failed later).
I tried moving all the forcedInclude connfigurations to settings.json
file (C_Cpp.forcedInclude) and it seems working fine but not confident how
long will it be working. I could feel some inconsistency in forcedInclude
concept of working with respect to dimming of inactive regions.

Thanks

**Comment by RogFedex** [comment]
Just want to let you know that adding forcedinclude in settings.json (
C_Cpp.forcedInclude) is not working consistently. forcedInclude is not
effective at all but i don't see 'no dimming óf inactive code' issue.
I add the forcedInclude in C_Cpp_properties.json then forcedInclude is
effective but i observe the 'no dimming óf inactive code' issue. Hope this
information helps.

**Comment by Colengms** [comment]
Hi @RogFedex .  The setting "C_Cpp.forcedInclude" should work only in c_cpp_properties.json.  In settings.json, the setting to set a default for all projects would be "C_Cpp.default.forcedInclude".

Would you be able to isolate a stand-alone example of a region not becoming inactive when expected, that you can share with us?

**Comment by RogFedex** [comment]
Thanks. correcting it to  C_Cpp.default.forcedInclude has helped to get
forcedInclude working. Atleast now the dimming of the inactive code is also
working.
If there is no difference in the logic of having forcecInclude in
settings.json and c_cpp_properties.json file then i will come across the
same problem again.. I will keep you updated on that.
Its not possible to share the project workspace though.

**Comment by kenwu-wu** [comment]
Not sure if I should post this here, or create another issue, but DIM inactive region doesn't seem to be working when accessing the file via REMOTE-SSH.

**Comment by Steelskin** [comment]
I have figured out a potential cause to this issue:
-Have a project directory at `/mnt/sthg/code`
-Have a symlink at `$HOME/src/code` pointing to `/mnt/sthg/code`
-Open `$HOME/src/code` in VS Code

Files opened as `$HOME/src/code/path/to/file` in this workspace do not have proper syntax highlighting, including inactive regions. However, files opened as `/mnt/sthg/code/path/to/file` have proper syntax highlighting.
As a workaround, opening the `/mnt/sthg/code` directory in VS Code works. I do not know if this is the same issue that you are experiencing, @RogFedex since you are on Windows.

**Comment by RogFedex** [comment]
Hi, The inactive region issue seems to have got resolved in the latest
version of vscode. Now the highlighting seems correct. I remember when i
was interacting with you i had multiple folders added in the workspace and
i m not sure if the workspace folder and the root folder are different then
we may run in to the issue. Right now i tried adding two folders in the
workspace and so far the inactive regions are getting Dim correctly. I will
update you if i come across the issue again.

Thanks
Prasad
