### ISSUE TITLE
Symbols from included file are not recognized although F12 works

### ISSUE THREAD

**Issue by ivancho-ifa** [microsoft/vscode-cpptools#4434]
Issue Type: <b>Bug</b>

1. Open a C++ project folder in VS Code.
When parsing is finished this error is noticed:
![Inkedvs-code-intellisence-problem_LI](https://user-images.githubusercontent.com/13264246/67005390-29285280-f0eb-11e9-9371-5620f36d6a7f.jpg)

The funny thing is that when I press `F12` for any element declared in the `sslUtils.h` file if works. But it is marked as not existing in the **Problems** pane and underlined in the editor.

The `c_cpp_properties.json` is the following:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```
The `settings.json` is:
```
{
    "C_Cpp.clang_format_path": "D:\\dev\\clang-format\\clang-format.exe",
    "C_Cpp.errorSquiggles": "Enabled",
    "C_Cpp.experimentalFeatures": "Enabled",
    "C_Cpp.loggingLevel": "Debug",
    "C_Cpp.updateChannel": "Insiders",
}
```

Extension version: 0.25.1
VS Code version: Code - Insiders 1.40.0-insider (3f6ed25939b8ef157a7a41e0dc43b517898d4005, 2019-10-15T05:26:38.861Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.0-693.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sof2-dbc401|
|OS|Linux x64 3.10.0-693.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (80 x 2100)|
|Memory (System)|376.17GB (1.06GB free)|
|VM|0%|
</details>

**Comment by ivancho-ifa** [comment]
Also noticed with `std::chrono_literals` under the same configuration:
![InkedInkedvs-code-intellisence-problem-chrono_literals_LI](https://user-images.githubusercontent.com/13264246/67005513-6db3ee00-f0eb-11e9-84d8-f6135023bbaa.jpg)

**Comment by Colengms** [comment]
Hi @ivancho-ifa .  Would you be able to isolate this into a stand-alone example that you could share with us, so we could investigate directly?

**Comment by pieandcakes** [comment]
@Colengms Tagging as Language Service. Please add additional tags/assignments as needed.

**Comment by sean-mcmanus** [comment]
For the 1st issue, it looks like recursive includes is using the path to the other file with the same name. You may be able to fix it via adding `"${workspaceFolder}/bora/apps/trusted-host-services/common/include"` before `"${workspaceFolder}/**"`. Go to Def on the `#include` doesn't use the correct IntelliSense path (we have another issue tracking that).

For the issue with chrono_literals, you may want do add some folders to files.exclude or replace `"${workspaceFolder}/**"` with more entries for specific sub folders you actually want to use (looks like your workspace has multiple chrono_literals implementations). Actually, the error message means IntelliSense can't find chrono_literals, so you should check the output of C/C++: Log Diagnostics to see what system paths are getting used.

**Comment by pelrun** [comment]
I've been hitting something similar. It only seems to happen on large codebases with recursive includes, and reordering the includes can sometimes (temporarily) resolve it. Is there a size limit on the intellisense db or some other reason parsing may be silently terminated before fully traversing the include tree?

**Comment by pelrun** [comment]
One more thing that seems to cause this: The Problem window has a long-standing issue where dangling entries raised by extensions stick around even though the extension has forgotten about them. They then permanently generate squiggles even though there is no longer an underlying reason to. At the moment the only way to clear them is the Reload Window command.

**Comment by sean-mcmanus** [comment]
@pelrun We have a max folder depth of 20, but no size limit.

Do you know how to repro the stuck error squiggles?

**Comment by pelrun** [comment]
Unfortunately not; it's never happened reliably, but if I can find a sensible repro case I'll document it. What I'll do in the meantime is determine whether my symptoms are purely due to leaked problem window entries (and intellisense is working fine), or if there's a mix of both that issue and a persistent intellisense one.

**Comment by ivancho-ifa** [comment]
The solution suggested by @sean-mcmanus worked for me. Feel free to close the issue. Thanks!

**Comment by sean-mcmanus** [comment]
Okay, I'm closing this -- if anyone has more repro details of another bug, that can go in a new issue.
