### ISSUE TITLE
Return type listed along with function name in Outline view

### ISSUE THREAD

**Issue by lijh8** [microsoft/vscode-cpptools#4440]
![66886647-ab8d1580-f00a-11e9-90b9-2aa93ff0ea5d](https://user-images.githubusercontent.com/9011764/66889721-1001a200-f016-11e9-802c-41abe638419f.png)

- C/C++ Extension Version: 
Id: ms-vscode.cpptools
Version: 0.26.0

**Comment by sean-mcmanus** [comment]
This appears to be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4383 .

**Comment by bobbrow** [comment]
Closing duplicate issue.
