### ISSUE TITLE
clang-format IndentPPDirectives: BeforeHash

### ISSUE THREAD

**Issue by luni64** [microsoft/vscode-cpptools#4441]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.0

Using IndentPPDirectives: BeforeHash generates an error: 
`YAML:21:21: error: unknown enumerated scalar
  IndentPPDirectives: BeforeHash`
The same works using the clang-format extension and disabling formatting in c/c++

**Expected behavior**
Should support IndentPPDirectives: BeforeHash

**Comment by sean-mcmanus** [comment]
The version of clang-format we bundle doesn't support that. We're tracking upgrading to 9.0 at https://github.com/microsoft/vscode-cpptools/issues/2887. You could set the C_Cpp.clang_format_path to a newer version of clang as a workaround.
