### ISSUE TITLE
Extension doesn't use editor's language settings for tooltips

### ISSUE THREAD

**Issue by tehKaiN** [microsoft/vscode-cpptools#4442]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10 1809 x64 PL
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.0
- Other extensions you installed (and if the issue persists after disabling them): irrelevant, I think.
- A clear and concise description of what the bug is: it uses my OS language for tooltips instead of one selected in vscode settings

**To Reproduce**
1. Use non-english Windows version
2. Set vscode language to English
3. Go to c_cpp_properties.json and hover on any setting name, alternatively hover on any error in opened C/C++ file
4. Note that tooltip text is non-english
5. Go to tasks.json or launch.json or any other vscode config file
6. Note that tooltips are in english

**Expected behavior**
Extension's tooltips should be in English, they are not.

**Screenshots**
c_cpp_properties.json:
![obraz](https://user-images.githubusercontent.com/16180344/66896698-a70a3200-eff5-11e9-8363-14deaffd1aa8.png)

launch.json:
![obraz](https://user-images.githubusercontent.com/16180344/66896760-c99c4b00-eff5-11e9-84e5-e1febfa9e77f.png)

**Additional context**

**Comment by michelleangela** [comment]
The c_cpp_properties.json config file is implemented by the C/C++ extension, whereas the launch.json and tasks.json files are implemented by VS Code. Please report the issue at VS Code repository: https://github.com/microsoft/vscode/issues

**Comment by tehKaiN** [comment]
I'm afraid you have misread my issue. The problem is that c_cpp_properties.json **is using non-english locale when should not**. Also, screenshots are only from .json file, the same problem is apparent with error descriptions in tooltips.

![obraz](https://user-images.githubusercontent.com/16180344/66937706-3e947280-f040-11e9-817a-aa9052ff48ee.png)

Note that I've marked strings in Polish fron C/C++ Extension and sample English text in rest of GUI.

**Comment by michelleangela** [comment]
@tehKaiN, you're right, I'm sorry for misreading your issue.

Can you try to change the display language on VS Code by running the command [configure display language](https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language) and see if that fixes the issue?

**Comment by tehKaiN** [comment]
Whoa, it worked! I guess it's some kind of cache problem. Many thanks for that fix!
