### ISSUE TITLE
enhancedColorization makes smooth scrolling lag

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode-cpptools#4446]
Type: General

**Describe the bug**
- OS and Version: kubuntu 19.04
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

With enabled C_Cpp.enhancedColorization evene relatively small cpp files (150 lines) tend to lag on scrolling. I have 1080 GTX, core i7 4770.

**Comment by Colengms** [comment]
I'm not seeing a discernable difference between the lag with or without enhancedColorization enabled, with significantly larger files.  Could there be something else going on in your case?

We only apply text decorations to (just beyond) the immediately visible region of the file.  So, the size of the file actually should not matter.  The process of parsing the document and applying the text decorations, happens on a thread other than the main UI thread.  Even without enhancedColorization, VS Code applies quite a bit of color to source files.  I suspect that any further performance improvements to this area would need to come from VS Code itself, in the form of a more efficient way to store style settings for semantic colorization.

**Comment by Yanpas** [comment]
Here is a profile from vscode dev tools. Maybe it's vscode's issue.

[Profile-20191017T150945.json.txt.gz](https://github.com/microsoft/vscode-cpptools/files/3739150/Profile-20191017T150945.json.txt.gz)

**Comment by bobbrow** [comment]
Will be addressed with #4992
