### ISSUE TITLE
Function comments in GBK appear garbled when hovering over this function

### ISSUE THREAD

**Issue by huangyxi** [microsoft/vscode-cpptools#4447]
Type: General

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.18362
- VS Code Version: 1.39.2 (user setup)
- C/C++ Extension Version: 0.26.0
- Other extensions you installed (and if the issue persists after disabling them): No
- A clear and concise description of what the bug is:
The comment text (GBK encoding) where the mouse hovering on the function is garbled.

**To Reproduce**
- `main.c`:
```c
// the encoding of this file is arbitrary
#include "a.h"
void main(void) {
	testFun();
}
```
- `a.h`:
```c
// this file should save with encoding GBK or other encodings but not UTF-8
// this file should be closed in vs code tab
// example Chinese comments below
// 用其他编码的注释 (Chinese comments)
void testFun(void) {
	return;
}
```
- `launch.json` is not need to be created

1. set `"files.autoGuessEncoding": true` in `settings.json`
2. create files above in one folder, **`a.h` should be save with encoding GBK** or other encodings but **not UTF-8**, the encoding of `main.c` is arbitrary, `launch.json` is not need to be created
3. open `main.c` in  vs code, but **`a.h` should be closed**
4. hover over `testFun`
5. the Chinese comments appear garbled (`�����������ע�� (Chinese comments)`) in the pop-up frame
6. Chinese comments appear right when:
a. `Peek definition` of `testFun`
b. open `a.h` in vs code
c. definition and the code when call the function in one file

Apologize for my poor English.

**Comment by sean-mcmanus** [comment]
We're tracking non-UTF-8 support with https://github.com/microsoft/vscode-cpptools/issues/414.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 . Let us know if you see any remaining bugs with non-UTF-8 encodings.
