### ISSUE TITLE
Add support for Windows Resource files

### ISSUE THREAD

**Issue by ffes** [microsoft/vscode-cpptools#445]
At the moment with I open a .rc (Windows Resource) file, it is just plain text. No syntax highlighting.

Not sure if this project is the right place, but since .rc files are mostly used by C/C++ projects, I would expect it to be included in this project, especially since this is a Microsoft project.

**Comment by sean-mcmanus** [comment]
The current C++ syntax highlighting is provided by VS Code through atom/language-c. We could theoretically add support for .rc files, but we're not planning to yet. Visual Studio supports .rc file highlighting.

**Comment by bobbrow** [comment]
You should be able to add `"files.associations": { "*.rc": "cpp" }` to your workspace settings.json to associate that file extension with the cpp language (goto: File->Preferences->Settings).

**Comment by sean-mcmanus** [comment]
But it would interpret the .rc file as C++ file, so I'm not sure if the result will be good enough.

**Comment by bobbrow** [comment]
We are currently unable to address this feature request since we are focusing on higher priority features and bugs right now.  We'll tag this for follow up in case it receives more interest from the community, but to keep our bug counts manageable, we're closing this issue for now.
