### ISSUE TITLE
How to change the feedback language of Intellisense

### ISSUE THREAD

**Issue by harokyang** [microsoft/vscode-cpptools#4450]
I use a Chinese language OS, but set the build enviornment to English for project requirement(env variable VSLANG=1033)

Before the latest vscode update, everything works fine
But after the update, Cpp-tools intellisense now give Chinese language feedback

Now I have mixed language feedback in PROBLEMS tab, CN from the intellisense, EN from the compiling result

How can I force intellisense to use the same language setting with vscode GUI? (At least the intellisense in visual studio community follow the regional language setting)

**Comment by Neonit** [comment]
Same problem here with German. IntelliSense suddenly changed the language of my error messages to (assumingly) system language without my consent. I don't want that.

**Comment by michelleangela** [comment]
What display language is your VS Code set to? If it's not English, can you try [changing the language display on VS Code](https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language) to English and see if that changes the IntelliSense feedback language?

**Comment by Colengms** [comment]
The C/C++ Extension uses [vscode-nls](https://github.com/microsoft/vscode-nls).  We should be displaying in the same language as VS Code menus, etc., based on the setting of the 'Configure Display Language' command.  Are you seeing the C/C++ Extension use a language other than what VS Code is set to?

There is an issue that might result in language settings being out of sync; if you remove a language pack for the currently selected language.  https://github.com/microsoft/vscode/issues/82791

If you are asking for all or only certain features of the C/C++ Extension (i.e. IntelliSense) to use a language other than VS Code's current display language, we could consider that.

**Comment by harokyang** [comment]
> What display language is your VS Code set to? If it's not English, can you try [changing the language display on VS Code](https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language) to English and see if that changes the IntelliSense feedback language?

Well that works for me
By changing Display Language to en fix the issue

The question is I did not install any other language for vscode, the en is the default one
But now explicitly select the only option in the language list did fix it

Can I suppose that even a fresh installed vscode displayed as English, the actual display language value is not en?

**Comment by bobbrow** [comment]
This is a VS Code issue tracked by microsoft/vscode#82791
