### ISSUE TITLE
format a macro function with a Chinese annotation, the slash alignment fails.

### ISSUE THREAD

**Issue by Atom2004** [microsoft/vscode-cpptools#4451]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1903
- VS Code Version: 1.39.2 x64
- C/C++ Extension Version: 0.26.0: October 15, 2019
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
  Write an MACRO function in an *.c file or *.h file like the screenshot below, with some Chinese annotation. And auto format that code. The slash behind each alignment fails.
  The *.c file is GBK encoded.

**To Reproduce**

**Expected behavior**

**Screenshots**

![Annotation 2019-10-17 143039](https://user-images.githubusercontent.com/22042246/66983716-cbe0d100-f0eb-11e9-9a00-835b10efe99a.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
Does the issue repro with UTF-8? We're tracking GBK support with https://github.com/microsoft/vscode-cpptools/issues/414 .

**Comment by Colengms** [comment]
Hi @Atom2004  I believe this issue has since been addressed.  I'm not able to repro.  If you are still seeing an issue with this, please let us know and we can reopen it.  If you can still repro, please include sample text we can repro with.  Thanks!

**Comment by sean-mcmanus** [comment]
@Colengms Do you mean it will be fixed with 0.30.0-insiders4 or it doesn't repro with 0.29.0 too?

**Comment by sean-mcmanus** [comment]
Either way, it should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 . Let us know if you see any remaining bugs with non-UTF-8 encodings.
