### ISSUE TITLE
Linux Can't Downloading components

### ISSUE THREAD

**Issue by shudingbo** [microsoft/vscode-cpptools#4453]
Type: General

Can't Downloading components:

notify like this:
 **c/c++ Extension: Downloading 1/4: C/C++ language componsnts(Linux x86_64)**

**Describe the bug**
- OS and Version: centos 7/8
- VS Code Version: 1.39.1
- C/C++ Extension Version: 0.25.*,  0.26 AND another 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by hajlyx** [comment]
Same problem.
Stucked in "Downloading 1/4: C/C++ language componsnts" process.

- OS and Version: Ubuntu 18.04

- VS Code Version: 1.39.2

- C/C++ Extension Version: 0.26

**Comment by bobbrow** [comment]
We're hoping to eliminate this step in the near future when the Marketplace adds support for OS-specific extension packages.

In the meantime, you can download the OS-specific packages directly from our [releases page](https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.0) and use the `Install from VSIX...` command to install it.

**Comment by jkmartindale** [comment]
For some reason I'm getting the same issue even after installing from the VSIX file in my remote

**Comment by jkmartindale** [comment]
I've found that even when installing the VSIX on my remote, I get the downloading messages that run for a while before failing:

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'ClangFormat (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Framework Assemblies'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Mono Runtime (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Failed at stage: installPackages
Error: end of central directory record signature not found

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/Microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
```

**Comment by bobbrow** [comment]
@jkmartindale which VSIX did you download?  This is the one you want: https://github.com/microsoft/vscode-cpptools/releases/download/0.26.1/cpptools-linux.vsix.  It should be about 19.6 MB in size.

The standalone VSIX's on our Release page don't attempt to download anything.

**Comment by xuebinsu** [comment]
Same problem as @jkmartindale . The version I downloaded is exactly cpptools-linux.vsix and it is installed on a remote server.

**Comment by xni** [comment]
I have had the same issue and even installation from vsix didn't help. What helped:
1) uninstall the extension
2) remove ~/.vscode-server/extensions/ms-vscode.cpptools*
3) install from .vsix

**Comment by bhanupatial** [comment]
I guess you are behind a proxy and because of SSL certificates; you are facing this issue. 

"http.proxyStrictSSL": false in setting will surely help.

**Comment by ymh199478** [comment]
I also encountered the same problem, but when I close my agent(vpn) it works fine.

**Comment by yaohong772** [comment]
@ymh199478 how to close agent？

**Comment by ymh199478** [comment]
@yaohong772 I just mean I closed my vpn program, when the global vpn is turned on, it will cause an abnormal installation.

**Comment by Colengms** [comment]
This should get addressed by: microsoft/vscode#23251

**Comment by XingLiu0923** [comment]
@ymh199478 works for me too, thanks

**Comment by bobbrow** [comment]
This will no longer be a problem when #8152 is completed in version 1.8.0.
