### ISSUE TITLE
Follow Cursor in outline view (and Breadcrumbs) not working with nested namespaces

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode-cpptools#4456]
In 0.26.0, follow cursor does not work with nested namespaces

This will not work
```c++
namespace test1::test2 {

void Test1()
{
  int i = 0;
  return;
}

void Test2()
{
  int i = 0;
  return;
}

void Test3()
{
  int i = 0;
  return;
}

}
```
But this will work

```c++
namespace test1 {
namespace test2 {

void Test1()
{
  int i = 0;
  return;
}

void Test2()
{
  int i = 0;
  return;
}

void Test3()
{
  int i = 0;
  return;
}

}
}
```

I also saw that follow cursor was not working in some stl headers on windows, but I don't know what is causing that.
Example: 
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.20.27508\include\vector`
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.20.27508\include\utility`

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
