### ISSUE TITLE
Remote debug breakpoints not unset in J-Link GDB server

### ISSUE THREAD

**Issue by jefffhaynes** [microsoft/vscode-cpptools#446]
Steps to Reproduce:

1. Going to be tricky...I'm using [J-Link](https://www.segger.com/jlink-gdb-server.html) to debug a microcontroller (awesome that this is possible, btw).
2. Set miDebuggerServerAddress to localhost:2331
3. Start J-Link GDB Server (probably not possible without a target device).
4. Set breakpoint anywhere in code - GDB Server UI logs breakpoint
5. Unset breakpoint - GDB Server logs nothing.
6. This is problematic as J-Link alerts to multiple breakpoints in the same place if you set and unset the same breakpoint multiple times.

The documentation for the J-Link server is [here](https://www.segger.com/admin/uploads/productDocs/UM08001_JLink.pdf) and it seems to indicate that "clrbr" is the command to clear a breakpoint.  I realize there's a pretty good chance this issue is on the J-Link side but it's hard to tell.

**Comment by pieandcakes** [comment]
@jefffhaynes - if you enable `"logging": { "engineLogging": true }` in the `launch.json`, you should be able to see the MI commands we send/receive to gdb. this may help you figure out what J-Link is doing.

**Comment by jefffhaynes** [comment]
Thanks, I'll give that a try. 

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Tue, Jan 17, 2017 at 5:51 PM -0500, "Pierson Lee" <notifications@github.com> wrote:












@jefffhaynes - if you enable "logging": { "engineLogging": true } in the launch.json, you should be able to see the MI commands we send/receive to gdb. this may help you figure out what J-Link is doing.

**Comment by robotdad** [comment]
@jefffhaynes did you get any further with the JLink here?

**Comment by jefffhaynes** [comment]
No, unfortunately. I turned on logging but I wasn’t able to figure out the issue. It is still a problem and it’s just something we live with.  In general the vs code/jlink experience is quite wonky and unstable.

**Comment by tehKaiN** [comment]
Hi there,

I was struggling with hooking up my NXP LPC4370 with GDB, openocd didn't work for me, so I've switched to SEGGER JLink GDB Server and programmed my LPC-Link2 to JLink firmware. Then, I've finally come up with launch.json config as below (windows, on linux should be very similar):

``` js
{
	// Based on: https://touchgfx.zendesk.com/hc/en-us/articles/205337311-Debugging-SEGGER-J-Link-GDB-Server
	"name": "(gdb) LPC Test board",
	"type": "cppdbg",
	"request": "launch",
	"program": "path/to/elf.or.axf.file",
	"args": [],
	"stopAtEntry": false,
	"cwd": "${workspaceFolder}",
	"environment": [],
	"externalConsole": false,
	"MIMode": "gdb",
	"miDebuggerPath": "arm-none-eabi-gdb.exe",
	"debugServerPath": "path/to/JLink_V622f/JLinkGDBServerCL.exe",
	"targetArchitecture": "arm",
	// Proper command line args may be obtained from JLinkGDBServer.exe
	"debugServerArgs": "-select USB -device LPC4370_M4 -if JTAG -speed auto -noir",
	"setupCommands": [
		{
			"text": "-target-select remote localhost:2331",
			"description": "connect to JLink GDB Server",
			"ignoreFailures": false
		},
		{
			"text": "-file-exec-and-symbols path\\\\to\\\\elf.or.axf.file", // must have 4 backslashes in place of one single backslash
			"description": "Load symbols",
			"ignoreFailures": false
		},
		{
			"text": "-enable-pretty-printing",
			"description": "Enable pretty-printing for gdb",
			"ignoreFailures": false
		},
		{
			"text": "-interpreter-exec console \"monitor reset\"",
			"description": "Reset CPU",
			"ignoreFailures": false
		},
		{
			"text": "-interpreter-exec console \"monitor halt\"",
			"description": "Halt CPU",
			"ignoreFailures": false
		},
		{
			"text": "-interpreter-exec console \"monitor endian little\"",
			"description": "Enforce little endian",
			"ignoreFailures": false
		},
		{
			"text": "-interpreter-exec console \"monitor speed auto\"",
			"description": "Auto-configure link speed",
			"ignoreFailures": false
		},
		{
			"text": "-interpreter-exec console \"monitor flash device LPC4370_M4\"",
			"description": "Set device to be debugged - same as in debugServerArgs",
			"ignoreFailures": false
		},
		{
			"text": "-interpreter-exec console \"load\"",
			"description": "Flash target",
			"ignoreFailures": false
		},
	],
	"logging": {
		// Debug stuff - enable some for details
		// "moduleLoad": true,
		// "trace": true,
		// "engineLogging": true, // GDB Server & GDB responses - most important
		// "programOutput": true,
		// "exceptions": true,
		// "traceResponse": true // JSON stuff
	},
	// Listen to JLink GDB Server output to know when to launch GDB
	"filterStderr": true,
	"filterStdout": true,
	"serverStarted": "Connected\\ to\\ target"
}
```

And it works! Be sure to change LPC4370_M4 to your uc - get proper name from JLinkGDBServer.exe

**Comment by lmapii** [comment]
same problem here - debugging using openocd as gdb server works quite ok-ish though slow, J-LINK is just giving me issues w/ breakpoints and even launching. prob. also due to some differences in the API of gdb / J-LINK.

**Comment by pieandcakes** [comment]
@lmapii If you would be able to provide logging (above), we might be able to find out where the problem is.

**Comment by WardenGnaw** [comment]
Closing with not enough information. 

If this issue is still occuring, please open a new issue with the requested information.
