### ISSUE TITLE
Outline does not list function-local structs or classes

### ISSUE THREAD

**Issue by CelticMinstrel** [microsoft/vscode-cpptools#4461]
**Type: LanguageService**

- OS and Version: Win10
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.0

A `union`, `struct`, or `class` nested in a function body is not shown in the outline.

**To Reproduce**

Create a document with the following code and activate the Outline View.

```
int main(int argc, char* argv[]) {
	struct mystruct {
		int i_am_a_teapot;
		void brew_tea();
	};
	return 1;
}
```

**Expected behavior**

I would expect `mystruct` to be nested under `main` in the outline (with `brew_tea` nested under `mystruct`), but instead, only `main` itself is shown.

**Comment by sean-mcmanus** [comment]
Yeah, I noticed TypeScript does this -- however, our document symbol parsing code only runs at the global scope, so we don't have the local variables or local classes available, unless we somehow did an additional query from the IntelliSense process.

**Comment by CelticMinstrel** [comment]
I could see reason not to show local variables, as that might clutter the outline; but at the very least, local classes with member functions should be shown in my opinion.

**Comment by sean-mcmanus** [comment]
I have filed a VS bug https://developercommunity.visualstudio.com/content/problem/784673/cc-local-function-scopes-are-not-shown-in-the-navi.html . So if they fix that, then maybe we could get their fix or do something similar.
