### ISSUE TITLE
The CPP extension keeps running at 40% CPU even if I leave vscode minimized for 12 hours

### ISSUE THREAD

**Issue by lattice0** [microsoft/vscode-cpptools#4465]
**Describe the bug**
- OS and Version: Debian 9
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is:

Even if I let vscode minimized (that is, I do no work on it), the extension keeps running at 25% or even 40% CPU usage, even if I go to sleep. There's no reason to do that since I'm not chaning any files, vscode is just minimized.

Also, the extension constantly crashes with these errors:

`[Error - 11:36:58 PM] Connection to server got closed. Server will not be restarted.`

and also I cannot use it at all, because it constantly loses track of the include files and mark them as not found and then seconds later mark as found, and also points errors on many line codes and then seconds later doesn't count them as errors.

**Comment by sean-mcmanus** [comment]
If you want to find out what is causing the CPU usage, you could enable debug logging (https://code.visualstudio.com/docs/cpp/enable-logging-cpp) and/or attach a debugger and view the call stacks. My guess is that you may have a symlink that points to some large directory, such as your root drive (see https://github.com/microsoft/vscode-cpptools/issues/3123). You could change the browse.path setting to include less folders (or use "*" to make the paths non-recursive).

We are not aware of any high hitting crashes in general, but your particular code base, OS, or compiler library might be causing our extension to crash. If you could attach a debugger to the Microsoft.VSCode.CPP.Extension.linux process before the crash and provide a call stack (or any sample code or repro details) that could help us fix the crash.

We have not heard about the "constantly loses track of the includes files and marks them as not found" issue from other users, but my guess is that it could happen if the IntelliSense process were crashing repeatedly.

Temporary errors that go away later can occur after a later parsing fixes the issues, but I'm not sure that is what you're seeing.

**Comment by blooop** [comment]
I noticed that this extension was running even after I had closed VS code 10 minutes ago. 

While writing this comment I opened a closed VS code a number of times and a new 100% usage process was spawned each time I opened and (properly) closed vs code. 

```
Tasks: 393 total,   1 running, 286 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.3 us,  0.6 sy,  0.0 ni, 94.5 id,  0.2 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem : 13177643+total, 12371283+free,  2886596 used,  5177000 buff/cache
KiB Swap: 15622140 total, 15622140 free,        0 used. 12722529+avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                    
11718 blooop   20   0 1447664  45240   8896 S 100.0  0.0   0:38.52 Microsoft.VSCod                                                                                                                                                                                            
19448 blooop   20   0 2010508 183904  12632 S 100.0  0.1  76:24.10 Microsoft.VSCod                                                                                                                                                                                            
10424 blooop   20   0 1734396  75748  12228 S  94.1  0.1   2:09.19 Microsoft.VSCod                                                                                                                                                                                            
10878 blooop   20   0 1660664  66320   9356 S  94.1  0.1   1:17.78 Microsoft.VSCod                                                                                                                                                                                            
29615 blooop   20   0  508448  60192  26800 S  41.2  0.0   4:05.90 xfce4-taskmanag  
```

**Comment by sean-mcmanus** [comment]
@blooop Are you hitting https://github.com/microsoft/vscode-cpptools/issues/4470 ? The main process is supposed to be killed when VS is closed, but something may be preventing that on your machine.

**Comment by blooop** [comment]
I have classes similar to  "foo_interface" but not a namespace with "interface" by itself.  I noticed the problem when I ran the capt'n proto interface generator that produces header files and .cpp files based on the .capnp definition files.    A quick look at the autogenerated files do not seem to use interface as part of the namespace either but there might be files in capt'n proto library that do that that don't come up in my search.

**Comment by sean-mcmanus** [comment]
@blooop "foo_interface" should be okay. Does your issue still repro with 0.26.2-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders .

If it's still not fixed, are you able to attach a debugger to the process using CPU and get a call stack?

**Comment by andyp1per** [comment]
hi @sean-mcmanus you keep saying "check the logging" I have checked the logging and there is no output and yet cpptools is running at 40%
![image](https://user-images.githubusercontent.com/2893260/86287512-338a6e00-bbe0-11ea-8b34-8f82de81df36.png)
![image](https://user-images.githubusercontent.com/2893260/86287542-40a75d00-bbe0-11ea-8929-b21374218a2e.png)
This is a BUG

I keep killing the process and it keeps restarting - this is a VIRUS as far as I am concerned
VSC is so awesome apart from this one really, really bad problem - it pretty much makes the C++ plugin unusable

**Comment by sean-mcmanus** [comment]
@andyp1per cpptools intentionally restarts after it crashes or is killed. If you set the C_Cpp.loggingLevel to "Debug" there should be logging in the "C/C++" output pane. From your screenshot, it looks like workspace parsing is occurring. You could set compilerPath to "" and browse.path to [] to disable that completely (with diminished results).
