### ISSUE TITLE
Template class cannot be displayed as a tree view in the outline

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode-cpptools#4466]
Issue Type: <b>Bug</b>

**Type: LanguageService**

**To Reproduce**
```cpp
template <typename T>
struct Sample {
    int value;
};
```

**Screenshots**
<img width="960" alt="批注 2019-10-20 230534" src="https://user-images.githubusercontent.com/20399194/67161705-90663100-f38f-11e9-8799-bf4c1f38d704.png">

**Expected behavior**
<img width="960" alt="批注 2019-10-20 230753" src="https://user-images.githubusercontent.com/20399194/67161713-9d832000-f38f-11e9-91a5-388a79a9aa31.png">

Extension version: 0.26.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by michelleangela** [comment]
For comparison, this is the behavior on Visual Studio

![image](https://user-images.githubusercontent.com/38734287/67227942-1cf30c80-f3ed-11e9-8461-fc47ce0d6a98.png)

**Comment by sean-mcmanus** [comment]
The Outline bug should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3-insiders .
