### ISSUE TITLE
Any plan to support code disasm and CPU register window for debugging?

### ISSUE THREAD

**Issue by zhangyafeikimi** [microsoft/vscode-cpptools#4467]
Any plan to support code disasm and CPU register window for debugging?

**Comment by pieandcakes** [comment]
We have feature requests outstanding feature requests for them. please upvote the corresponding item. You can add `label:debugger` and `label:"Feature Request"` to your search terms to find them.

As this is an open source project, we welcome contributions from the community if people want to see a feature we haven't implemented yet.

**Comment by pieandcakes** [comment]
#206 for Disassembly
#509 for memory view

**Comment by zhangyafeikimi** [comment]
So, my question is if there is a plan for these feature?

**Comment by sean-mcmanus** [comment]
@WardenGnaw @pieandcakes It's not on any current schedule, right?

**Comment by pieandcakes** [comment]
@zhangyafeikimi We haven't done any planning of features beyond the next release and these are not features that will be in the next release.
