### ISSUE TITLE
Add cache to task inputs of the promptString type

### ISSUE THREAD

**Issue by yeggles** [microsoft/vscode-cpptools#4472]
It would be useful for task inputs to offer the ability to cache the last used input.  

A possible solution could be for the "promptString" GUI to have the appearance of the "pickString" GUI, but also offering a textbox where new values could be typed.  If the user just presses enter than it will use the last value.  If no value has ever been input then it would use the suggested default.

**Comment by sean-mcmanus** [comment]
Is this a request for VS Code (https://github.com/microsoft/vscode/issues) or was there a particular C/C++ task input you wanted our extension to cache input for?
