### ISSUE TITLE
Add documentation for ${command:cpptools.activeConfigname}

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#4473]
@bobbrow It works fine. 

Where can I find the documentation related to this feature? Pages [Customizing default settings](https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp) and [c_cpp_properties.json reference](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference) for the **C++ extension**, and page [Integrate with External Tools via Tasks](https://code.visualstudio.com/docs/editor/tasks#vscode) for **Tasks**, do not mention `cpptools.activeConfigName`.

Thank you!

_Originally posted by @rei-vilo in https://github.com/microsoft/vscode-cpptools/issues/742#issuecomment-544171285_

**Comment by bobbrow** [comment]
This was an oversight.  I created an issue to improve the documentation.

**Comment by bobbrow** [comment]
We can add a section for supported variables here:

https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference#:~:text=cppStandard%20The%20version%20of%20the%20C%2B%2B%20language%20standard,can%20provide%20IntelliSense%20configuration%20information%20for%20source%20files.

**Comment by michelleangela** [comment]
Note: the variable `${command:cpptools.activeConfigname}` can be used in tasks.json and launch.json
