### ISSUE TITLE
can you add a configuration to disable rename feature?

### ISSUE THREAD

**Issue by chongchai** [microsoft/vscode-cpptools#4476]
I may use other extension with rename feature. If these extension are installed together, the rename feature will be conflicted. 
So can you provider a configuration to control the rename feature?

**Comment by sean-mcmanus** [comment]
We register our rename provider at https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/client.ts and our settings are at https://github.com/microsoft/vscode-cpptools/blob/release/Extension/package.json if anyone wants to contribute a pull request for this (or other "disable" settings).
