### ISSUE TITLE
Outline/breadcrumbs takes > 30 seconds

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4479]
By the way, I just noticed that the command focusAndSelect is not quite the same as Navigate. The advantage of Navigate is: At least on my machine focusAndSelect needs quite some time until all information is read so that I can jump to a certain location in the file (currently it takes > 30 seconds), whereas Navigate was available nearly instantly. I'm not sure how this was implemented, but I really miss this feature :-(
btw,  also the feature "Go to Symbol in File" is really slow on my machine, most likely it uses the same data than focusAndSelect.

Shall I open a different bug for this, since actually the "error" is indeed by design, but the user experience problem most likely is not?

PS: I'm using a rather powerful machine for VS Code: My machine has 48 Xeon cores (Skylake) and 384 GB RAM.

_Originally posted by @hensz in https://github.com/microsoft/vscode-cpptools/issues/4469#issuecomment-544838951_

**Comment by sean-mcmanus** [comment]
@hensz Can you provide more info on what is taking 30 seconds? What do you see during this time? Is this the time for the Outline/breadcrumbs to populate? We haven't seen this type of slowness before. Does your file have a lot of lines or symbols or something else unusual?

The Outline/breadcrumb view added ranges and nesting structure which takes longer to compute.

**Comment by bobbrow** [comment]
With a machine as powerful as yours, this is definitely not expected.  focusAndSelect is pretty snappy on my more modest 8 core machine.  "Go to symbol in file" has known performance problems, but I don't believe it is the data source for focusAndSelect.  I expect focusAndSelect to be using the data already present in the Outline view as the data source.

Have you taken a performance trace of VS Code before? If you open the developer tools (`Help` -> `Toggle Developer Tools`) and navigate to the `Performance` tab, you can take a performance trace and share it with us.

**Comment by hensz** [comment]
My experience is like this:
I open a cpp file. Then the breadcrumb bar displays the path, split up into its pieces. If I run the command focusAndSelect now I can select one of the files in the current folder. When I wait a couple of seconds (the ~30 seconds I initially wrote) the breadcrumb bar changes into path plus '...'. Now I can run the command and actually navigate to other parts of the file, e.g. methods. (when I tried to reproduce this just now, it took almost 2 minutes...)

Perhaps this is related: Currently I also don't have IntelliSense, but strangely I also don't see any errors indicating a problem with indexing or my compilecommands file. Also the outline works fine. How can I diagnose this?

Thanks,
Torsten

**Comment by hensz** [comment]
Hi @sean-mcmanus!

>  Does your file have a lot of lines or symbols or something else unusual?
> The Outline/breadcrumb view added ranges and nesting structure which takes longer to compute.

The files are not that large. However, the entire code base is rather large. But since it worked fine before with Navigate (and also other IntelliSense features) I doubt that the size is an issue here.

btw, today I noticed something: Most of the time I'm working with Remote Development. Now when I open a file with the Go to File command I see lots of files twice: One with a relative path and one with an absolute path. For some files when I open the ones with relative path the breadcrumb bar is instantly displaying the "..." symbol and I can navigate using focusAndSelect. When I open the one with absolute path this doesn't work, and the Outline view displays some kind of progress indicator.

I have no clue where these files with absolute path come from, but I think that some kind of navigation mechanism use absolute paths and others use relative ones (e.g. goto compile error location, switch header - source).

However this is not the solution for the problem, since for other files it doesn't matter which one I open.

And this issue is not limited to the breadcrumb, but also the outline is not updating very fast most of the time.

**Comment by hensz** [comment]
> With a machine as powerful as yours, this is definitely not expected. focusAndSelect is pretty snappy on my more modest 8 core machine. "Go to symbol in file" has known performance problems, but I don't believe it is the data source for focusAndSelect. I expect focusAndSelect to be using the data already present in the Outline view as the data source.
> 
> Have you taken a performance trace of VS Code before? If you open the developer tools (`Help` -> `Toggle Developer Tools`) and navigate to the `Performance` tab, you can take a performance trace and share it with us.

I just recorded the performance trace while I opened a file that previously worked fast with focusAndSelect as stated in the previous command. Now it takes much longer again. I recorded about 30 seconds, and the breadcrumb showed no "..." symbol - in fact, even now, several minutes later VS Code is still displaying the progress indicator in the outline.

**Comment by hensz** [comment]
[Profile-20191025T213855.zip](https://github.com/microsoft/vscode-cpptools/files/3773537/Profile-20191025T213855.zip)

**Comment by sean-mcmanus** [comment]
It looks like the database is being built still, which might cause database access to be slower. What does it show when you hover over the database icon in the status bar? Also, does it show "tag parsing" messages when you enable debug logging (https://code.visualstudio.com/docs/cpp/enable-logging-cpp)? Using the "Pause Parsing" command might help. If your database or workspace is too large (lots of GB) that can impact performance for operations that do database operations. Our recent change to the Outline/breadcrumbs to support nested symbols adds more database operations.

**Comment by hensz** [comment]
Hi!
Sorry for the delay, I was on vacation.
The database icon hover says "parsing files" until the symbols are loaded. After that the icon disappears.

The log output first shows (rather fast) this here:

Checking for syntax errors: file:///...workspace...
Queueing IntelliSense update for files in translation unit of: /...workspace...
idle loop: reparsing the active document
Checking for syntax errors: file:///...workspace...
Queueing IntelliSense update for files in translation unit of: /...workspace...
Error squiggle count: 3
Error squiggles will be disabled in: file:///...workspace...
Error squiggle count: 3
Update IntelliSense time (sec): 5.97

During the long time that updating symbols (or the outline, or whatever) needs, nothing is printed to the output window, and also after this parsing is finished the output stays the same.

btw, yes, my workspace is indeed rather large. My source folder is about 22 GB, my compile_commands.json is about 93 MB.

**Comment by sean-mcmanus** [comment]
@hensz What `%` of files is showing as being parsed? Does parsing ever get past 100%? Does clicking the icon and choosing Pause Parsing make the outline faster?

Our extension may not currently be capable of handling a 22 GB source directory. https://github.com/microsoft/vscode-cpptools/issues/3123 is a related issue.

**Comment by hensz** [comment]
How can I see the percentage values? The hover only shows "parsing files", and also the outline doesn't display a percentage value. Today it parsed really fast, it only took about 10 seconds :-( .

The thing is, after parsing is done, everything seems to work as expected. So I assume that it gets to 100%. And I think that Pause Parsing doesn't change anything.

**Comment by sean-mcmanus** [comment]
It normally will show a "Parsing files: cur / max (%)" in the progress hover unless it gets into an unexpected state where it's > 100% (at which point it may be stuck don't some additional final processing that we haven't accounted for).

**Comment by hensz** [comment]
Just to explain things a bit better. This is how the footer of my VS Code looks like when I open a cpp file. I see two icons, a flame icon and a can (database?) icon:
![Footer](https://user-images.githubusercontent.com/1984979/69144797-73c33300-0acc-11ea-94f5-dd2cbf4e3a62.jpg)

The tooltip of the flame reads "Updating Intellisense....". This one disappears after about 4 seconds.
![Flame](https://user-images.githubusercontent.com/1984979/69144794-73c33300-0acc-11ea-931e-7d1b33c5016a.jpg)

The tooltip of the database icon reads "Parsing open files...". This one stays like that for the reported 30-40 seconds.
![Parsing](https://user-images.githubusercontent.com/1984979/69144798-73c33300-0acc-11ea-966e-5e70ea2f6fca.jpg)

I just reproduced this with a cpp file with 16 lines, which includes a header of also 16 lines. This one however includes some larger headers, however nothing spectacular. And for this file, "Parsing open files..." was displayed for way more than 40 seconds. And during this test, no other files were open - so the tooltip is misleading.

**Comment by sean-mcmanus** [comment]
If you check the "C/C++" debug log and you see "tag parsing" messages, then it would mean the parsing of open files is parsing include dependencies (possibly wrong ones that have the same name, but a different path). Otherwise, the status message could be incorrect.

**Comment by hensz** [comment]
Sorry, I don't understand your comment. In the debug log I don't see any "tag parsing" messages, and all paths that are listed are correct.

Perhaps there's something wrong with my workspace configuration. As I said, I sometimes see certain files twice, with both relative and absolute path.

**Comment by sean-mcmanus** [comment]
Yeah, if you don't see "tag parsing" then the "Parsing" status message is incorrect.

**Comment by hensz** [comment]
But what shall I do about this now? Something is wrong, but I don't know what, and how to fix this.

**Comment by sean-mcmanus** [comment]
So the bug is that the outline/breadcrumb performance is too slow compared to the previous Navigate when using a large workspace/database, right? We could investigate improving the performance -- we added code that handled a hierarchy of symbols so it's possible it's doing more database accesses or something.

**Comment by hensz** [comment]
I'm not entirely sure if the root cause is really "only" a performance issue due to the size of the workspace. Since some time I also have issues with IntelliSense in general, so perhaps there's something else broken on my system that impacts the performance. But how can I found out what this is?

**Comment by sean-mcmanus** [comment]
If you're using recursive includes "**" in the includePath, then the database/workspace size will impact the performance of IntelliSense (flame icon) -- if you see CPU usage in the Microsoft.VSCode.CPP.Extension process then it could be stuck on a database operation, while CPU usage in Microsoft.VSCode.CPP.IntelliSense.Msvc would mean IntelliSense parsing of the current TU (independent of workspace/database size). You could attach a debugger or enable an OS profiler to get call stacks to further diagnose performance issues.

**Comment by hensz** [comment]
Just to give an update, the mentioned issue #4720 seems to be solved now, but this one is still active. I just tried out, opening one rather small file (yes, 1500 lines is not always considered as small, but in our case it is ;-), and since ~1 minute the outline and breadcrumb wasn't loaded. Now, after more than 1 minute it was and works as expected.

Yes, even though the file is not that large, it has huge dependencies. This surely increases the time needed to parse.

What started the whole thing for me was the removal of a feature, Navigate, see the first post of this issue. This feature was really fast, while not in all cases accurate. But a feature that's not that accurate but usable is much better than an unusable (because slow) feature that's a bit more accurate.

**Comment by TorstenIhben** [comment]
Somehow this issue got lost. However at least the 30 seconds waiting time is at least reduced to a couple of seconds. Let's close this for now.

**Comment by hensz** [comment]
Hi!
Lots of time has passed since this issue was filed. We changed the language server in the meantime, and now the 30 seconds delay has reduced to a couple of seconds. This is acceptable, even though I still miss the good old times with the removed function Navigate. From my perspective we can close this issue.

**Comment by sean-mcmanus** [comment]
@hensz Sure, but FYI, we are in the process of investigating/fixing other performance issues.
