### ISSUE TITLE
Using statement won't get autocomplete if on the last line

### ISSUE THREAD

**Issue by escape0707** [microsoft/vscode-cpptools#4483]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.18362 & Linux x64 5.3.7-arch1-1-ARCH
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.0

When coding on a new `.cpp` file in a empty workspace withour `.vscode` folder and settings, the using statement won't always get appropriate autocomplete when it's on the last line. (...Maybe? Anyway append a space to that line don't work, too.) If it's not on the last line, everything seems to be just fine.

**Screenshots**

![C++](https://user-images.githubusercontent.com/11014745/67387783-2a192280-f5ca-11e9-87a8-739ff751acec.gif)

**Comment by escape0707** [comment]
Any progress on this issue?

**Comment by sean-mcmanus** [comment]
No progress...it's probably a quick fix, but it's not ranked as a high priority issue and we're pretty busy with other tasks currently (e.g. re-writing multi-root support).

**Comment by Colengms** [comment]
This appears to have since been addressed.  I can no longer repro.  Let us know if you still see this issue.
