### ISSUE TITLE
Windows 10 VS code debugger for C++ not stopping for anything

### ISSUE THREAD

**Issue by Kalivix** [microsoft/vscode-cpptools#4488]
Type: Debugger

**Describe the bug**
Windows 10 Version	10.0.18362 Build 18362
 
 VS Code Version: 1.93.2
- C/C++ Extension Version: 0.26.0:
- Other extensions you installed: Non
- When running the debugger is doesn't matter what breakpoints I put in it and no information ever appears in the debug side panels.

**To Reproduce**
I downloaded MinGW64 and placed it in the C drive, changed the PATH to C:\MinGW64\bin (though one for AppData\Local\WindowsApp; is still present). Then I opened the folder with what I'm working on (so the launch.json and task.json are in the .vscode folder) and pressed F5 which brings up the C++ (GDB/LLDB) or C++ (Windows) environment selection option. There are then 2 option, g++.exe build and debug active file and g++.exe build and debug active file when selecting the GDB option (which seems to be what everything I've found online suggests is the correct one).

This then creates the tasks.json and launch.json in the vscode folder, and the configuration changes from non to g++.exe build and debug active file. However when I click start debugging it just run through it to the end without stopping no matter how many breakpoints I `add.`

Below I have included the contents of the launch.json and task.json files that are created and what shows up in the debug console, nothing at all appears in the debug panel on the left when doing this even if I add tons of breakpoints throughout.

```
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
[New Thread 7272.0x267c]
[Inferior 1 (process 7272) exited normally]
The program '**** has exited with code 0 (0x00000000).


launch.json:

`    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++.exe build active file"
        }
    ]
}`

tasks.json:

`{
    "tasks": [
        {
            "type": "shell",
            "label": "cpp.exe build active file",
            "command": "C:\\MinGW64\\bin\\cpp.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\MinGW64\\bin"
            }
        },
        {
            "type": "shell",
            "label": "g++.exe build active file",
            "command": "C:\\MinGW64\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\MinGW64\\bin"
            }
        }
    ],
    "version": "2.0.0"
}`

**Comment by pieandcakes** [comment]
can you tell me where you set the breakpoint and an engine log?

**Comment by reservoirinvest** [comment]
I am having a similar issue as @Kalivix.

Followed steps outlined in [Get Started with C++..](https://code.visualstudio.com/docs/cpp/config-mingw)
>c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\mingw-w64\\mingw64\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

>tasks.json file
```
{
    "version": "2.0.0",
    "tasks": [
      {
        "label": "build hello world",
        "type": "shell",
        "command": "g++",
        "args": ["-g", "-o", "helloworld", "helloworld.cpp"],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]
  }
```
> launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/helloworld.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/mingw-w64/mingw64/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

> terminal output
```
PS C:\DEV> & 'c:\Users\User\.vscode\extensions\ms-vscode.cpptools-0.26.0\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-xmd5f2xe.wvs' '--stdout=Microsoft-MIEngine-Out-0k5yhtzz.lrs' '--stderr=Microsoft-MIEngine-Error-sgc5juia.xx4' '--pid=Microsoft-MIEngine-Pid-umx2u20s.gzg' '--dbgExe=C:/mingw-w64/mingw64/bin/gdb.exe' '--interpreter=mi'
```

The debugger keeps looping without any errors, but does not give any `VARIABLE` output.

Tried in two Windows 10 machines. Also tried changing compiler to [MingGW](https://nuwen.net/mingw.html). Have the same issue.

**Comment by pieandcakes** [comment]
@Kalivix  What version of the MinGW toolset are you using? Do you know how you got the one in WindowsApp ? can you remove that from your path and try again?

@reservoirinvest can either of you check and see what is in your `Debug Console` window? Any errors from `gdb` will be displayed there.

I suspect it isn't able to actually run the program because `mingw`'s `/bin` folder isn't in your Windows `PATH` which means that the program can't load the libs it needs.

**Comment by reservoirinvest** [comment]
> 
> 
> @Kalivix What version of the MinGW toolset are you using? Do you know how you got the one in WindowsApp ? can you remove that from your path and try again?
> 
> @reservoirinvest can either of you check and see what is in your `Debug Console` window? Any errors from `gdb` will be displayed there.
> 
> I suspect it isn't able to actually run the program because `mingw`'s `/bin` folder isn't in your Windows `PATH` which means that the program can't load the libs it needs.

Found that it was happening because of extra unseen characters - Refer: https://github.com/Microsoft/vscode-cpptools/issues/2925#issuecomment-448853709
