### ISSUE TITLE
Is there a way to pass input to std::cin during debugging / in debug console?

### ISSUE THREAD

**Issue by loganintech** [microsoft/vscode-cpptools#449]
I have mac / windows if that helps at all.

**Comment by pieandcakes** [comment]
@JewsOfHazard if you enable `"externalConsole":true` in the `launch.json` then you will get a pop up console window that you can type in. 

We have plans to integrate the debugConsole that is within VSCode.

**Comment by pieandcakes** [comment]
@JewsOfHazard Did enabling the `"externalConsole"` work for you?

**Comment by loganintech** [comment]
Yes sorry I didn't get back to you. That did open the external console and I was able to input text.

However, is there a way to change syntax on that command that runs in the external console? The shell I use has a slightly different command for the status code ($status instead of $?)
It's ultimately not a big deal but might be interesting to consider.

**Comment by pieandcakes** [comment]
@JewsOfHazard There is work to use the VSCode integrated console which may allow you to make changes but this work hasn't been done yet. Issue #35 is tracking that

**Comment by fanjc320** [comment]
have a problem:Property externalConsole is not allowed

**Comment by pieandcakes** [comment]
@fanjc320 if you need more help, we need your `launch.json` to see what is going on.

**Comment by zeyugao** [comment]
@pieandcakes I can't enable ```"externalConsole":true``` when using vscode-cmake-tools with Visual Studio as kits. The extension controls the ```launch.json``` when debuging.

The extension generates the config for cpptools as below

```
function createMSVCDebugConfiguration(target) {
    return {
        type: 'cppvsdbg',
        name: `Debug ${target.name}`,
        request: 'launch',
        cwd: '${workspaceRoot}',
        args: [],
        program: target.path
    };
}
```

As for the ```cppdbg```, the cpptools use the integrated terminal to debug. I can use it to input the stuff. But the ```cppvsdbg``` not.

**Comment by pieandcakes** [comment]
@zeyugao please file an issue with the cmake extension to allow you to set `"externalConsole": true`. This is currently the only way with `cppvsdbg` to allow you to process stdin with your debuggee.

**Comment by fawwaz** [comment]
Hi @pieandcakes , I set `externalConsole: true` but it seems that it only launch a normal terminal without running my program. Is there any step that I miss ? 
Here is my launch.json 
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [

    {
      "name": "clang++ - Build and debug active file",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": true,
      "MIMode": "lldb",
      "preLaunchTask": "clang++ build active file",
    }
  ]
}
```

**Comment by fawwaz** [comment]
Here is my screen recording , it open a terminal but then it doesn't run my code. Even if i execute my code manually in that terminal, the debugger doesn't capture my input. 

![image](https://user-images.githubusercontent.com/1295143/81784983-e6671580-9527-11ea-82ed-de2aeb663f5a.png)

**Comment by pieandcakes** [comment]
@fawwaz the screen recording is just a screenshot. Please file a new issue and fill out the template. I don't know what OS you are on or any other details so I don't have enough information to go off of.

**Comment by srikuppa** [comment]
- Inspite of having "externalConsole": true, I am unable to debug the code.

- Exact similar issue as above, and 
- I see Warning  - ** 'Debuggee TargetArchitecture not detected, assuming x86_64."**

**Comment by slampants** [comment]
I'm having the same issue as @srikuppa and others. I get an external terminal window to open, but the code never starts running in VS Code to bring me to the point that it's ready for my input. I was able to kill the "assuming x86_64" warning by specifying it explicitly in launch.json, but the program still won't actually run. I'm on macOS Catalina 10.15.7, running VS Code Version: 1.52.1

**Comment by qiulang** [comment]
I also got the external terminal open, but it did NOT read my input, nor does it output anything. If I kill the terminal, the debugger stops as well. 

It really looks like a bug to me. Any way to fix it? 

```
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0
```

**Comment by OliverHeilmann** [comment]
I would just like to add to this thread as the proposed fix **DOES** work for me. below is some key info from my setup.... I am on an Apple Silicon Macbook Pro and using the Clang compiler.

**Software and hardware** below:
```sh 
Software:
    System Software Overview:
      System Version: macOS 12.5 (21G72)
      Kernel Version: Darwin 21.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: -------
      User Name: -------
      Secure Virtual Memory: -------
      System Integrity Protection: -------
      Time since boot: -------

Hardware:
    Hardware Overview:
      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,4
      Chip: Apple M1 Max
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 64 GB
      System Firmware Version: -------
      OS Loader Version: -------
      Serial Number (system): -------
      Hardware UUID: -------
      Provisioning UDID: -------
      Activation Lock Status: -------
```

**launch.json** file below:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
        "name": "C/C++: clang++ build and debug active file",
        "type": "cppdbg",
        "request": "launch",
        "program": "${fileDirname}/${fileBasenameNoExtension}",
        "args": [],
        "stopAtEntry": true,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": true, // true for user inputs, false for vscode debugger (no user inputs)
        "MIMode": "lldb",
        "preLaunchTask": "C/C++: clang++ build active file"
      }
    ]
  }
```

When I click on the debugger, a new terminal window opens and prompts me for my name (as per the code setup). One thing I noted was that the debugger would automatically pause on the first line ```string firstname;```. Simply clicking "continue" on the debugger would then move the debugger to the user input section of the code.
<img width="1223" alt="Screenshot 2022-10-15 at 11 36 30" src="https://user-images.githubusercontent.com/49697817/195982084-17a90f1d-1c5e-48bf-8833-c609d6e3975c.png">

<img width="569" alt="Screenshot 2022-10-15 at 11 36 49" src="https://user-images.githubusercontent.com/49697817/195982087-1446ea98-d457-4cb3-a160-97897e10fc6a.png">

<img width="569" alt="Screenshot 2022-10-15 at 11 38 07" src="https://user-images.githubusercontent.com/49697817/195982072-5e42dfae-8543-4598-ae24-2a519f29b412.png">
