### ISSUE TITLE
Error message saying "unused parameter" for "int main(int argc, char* argv[])" 

### ISSUE THREAD

**Issue by tayloryoeuth** [microsoft/vscode-cpptools#4491]
Type: Debugger

Hello I currently have the C/C++ plug in and I am getting an error message that prevents me from running my code. It states I have unused parameters "argc" and "argv" for my "int main(int argc, char* argv[])" . I am currently running VS Code on a Macbook as well. 
<img width="761" alt="Screen Shot 2019-10-25 at 10 05 26 AM" src="https://user-images.githubusercontent.com/57007054/67577696-fe538500-f70e-11e9-8ea9-2358fe44e02a.png">

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by Colengms** [comment]
Hi @tbycodes .  The C/C++ Extension for VS Code provides language services such as IntelliSense.  It does not provide compile and build support.  Is there another extension you are using that is providing the "C/C++ Compile Run" output in your snapshot?

The output you referred to appear to be compiler warnings, not errors.  I would expect warnings would not prevent you from successfully compiling and running.

**Comment by sean-mcmanus** [comment]
Yeah, you can also try adding -Wno-unused-parameter to your build command line.
