### ISSUE TITLE
gdb does not show multiple threads always

### ISSUE THREAD

**Issue by kiransj2** [microsoft/vscode-cpptools#450]
When debugging C application with multilpe threads VS code does not show all the threads. It shows only the current threads where the breakpoint is hit. While running cmd "-exec info threads shows all the threads while on the callstack window only 1 thread is shown. 

VS code version: 1.8.1
C++ extension version: 0.9.3

Please see the attached image and sample source code that was used.
[1.zip](https://github.com/Microsoft/vscode-cpptools/files/706455/1.zip)

![gdb](https://cloud.githubusercontent.com/assets/12323112/21960912/17d2a64a-db20-11e6-80e0-2b1efe3f2583.jpg)

**Comment by randombenj** [comment]
I had the same issue when analyzing a core dump.

**Comment by pieandcakes** [comment]
@kiransj2 What OS are you running this on?

**Comment by kiransj2** [comment]
Ubuntu

**Comment by pieandcakes** [comment]
@randombenj core dump threads should be fixed in `0.10.2`

**Comment by pieandcakes** [comment]
@kiransj2 this issue should be fixed in `0.10.2`
