### ISSUE TITLE
Cannot find definition

### ISSUE THREAD

**Issue by Stormwaker** [microsoft/vscode-cpptools#4501]
OS and Version: macOS 10.15
VS Code Version: 1.39.2
C/C++ Extension Version: 0.2.2

After choosing "Go to Definition" I'm met with "No definition found", even though definition for that struct is in the same file and IDE like CLion doesn't have an issue with finding that definition.

**Comment by michelleangela** [comment]
@Stormwaker , the current latest version of C/C++ extension by Microsoft is 0.26.0. You specified **version 0.2.2**, did you mean 0.26.0 or are referring to a different extension?

If you're using the C/C++ extension by Microsoft, can you run the command `C/C++: Log Diagnostics` and share the log?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
