### ISSUE TITLE
Task not found

### ISSUE THREAD

**Issue by jclydepng** [microsoft/vscode-cpptools#4502]
Type: Debugger

I followed all the instructions properly but when I started to debug, it keeps on saying "Could not find the task 'C:/mingw/bin/g++.exe'"

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by pieandcakes** [comment]
@jclydepng Based on the information you provided, it sounds like you have a `preLaunchTask` in your `launch.json` pointed to `C:/mingw/bin/g++.exe` but you don't have a corresponding task named that in your `tasks.json`.
