### ISSUE TITLE
Rename UI fails to rename symbols after the document cursor moves in VS Code 1.40.0-insiders

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#4504]
This is related to:
https://github.com/Microsoft/vscode/issues/82146
https://github.com/microsoft/vscode/issues/83459

In VS Code 1.40.0-insiders, Rename operations that require disambiguation (display rename UI due to unconfirmed references found) will likely fail to apply. We are working with the VS Code to identify the proper solution.

**Comment by sean-mcmanus** [comment]
It only repros after the document cursor moves (although clicking the leaf reference in the tree view will trigger the cursor change as well).

**Comment by michelleangela** [comment]
Fixed in version 0.26.2-insiders, available at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders.
