### ISSUE TITLE
No error squiggles appear with VS Code Insiders if "(" or ")" is in the path

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4505]
Root cause is a VS Code Insider change...not sure if we need to fix this ourselves yet.

**Comment by Colengms** [comment]
@sean-mcmanus , Is the issue that VS Code now encodes all URI's in a new way?  If so, we should encode the same way when converting from path to URI.  Or, is the issue that VS Code is giving us inconsistent encodings for URIs?  The later would seem to be a VS Code bug.

**Comment by sean-mcmanus** [comment]
From what I saw, the Insiders version encodes URIs differently from the non-Insiders (not 100% if there are inconsistent cases)...but our extension would need to behave correctly for both cases somehow.

**Comment by sean-mcmanus** [comment]
Latest VS Code Insiders has it fixed.
