### ISSUE TITLE
The clang-format version currentlly not support key words 'AlignConsecutiveMacros'

### ISSUE THREAD

**Issue by neoyong** [microsoft/vscode-cpptools#4507]
My file '_clang-format' include a keyword 'AlignConsecutiveMacros' . When I use the 'Alt+shift+f' to format my c/c++ source file , the output window gives me a error info:
"c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.26.1/bin/../LLVM/bin/clang-format.exe" -style="file" -fallback-style="LLVM" -assume-filename="f:\****\ext_button.h"
YAML:14:25: error: unknown key 'AlignConsecutiveMacros'
  AlignConsecutiveMacros: true
                          ^~~~
  Error reading f:\****\_clang-format: invalid argument

Currentlly resulotion
Download the new version of clang-format.exe from the url "https://llvm.org/builds/" & replace the old one where the path includes.

**Comment by michelleangela** [comment]
Duplicating to issue that's tracking to update clang-format https://github.com/microsoft/vscode-cpptools/issues/2887
