### ISSUE TITLE
Header autocomplete and header/source switch for "*.cu" "*.cuh" files

### ISSUE THREAD

**Issue by vakokako** [microsoft/vscode-cpptools#4509]
Hi, I'm developing in Cuda right now and just adding `*.cu` and `*.cuh` to `files.associations` in settings works for syntax parsing. 
However, when I try to autocomplete `#include <Header.cuh>`, it doesn't show files with `.cuh`/`.cu` extensions. 
Also switching between `.cuh`/`.cu` as header/source doesn't work.

Is there any setting that can control this?

**Comment by sean-mcmanus** [comment]
Unfortunately, the types are currently hardcoded. We might need to add some setting to indicate which files are headers versus source files in addition to just files.associations. The switch header source is being tracking with https://github.com/microsoft/vscode-cpptools/issues/3199 , but we can use this issue to track the completion.

It might just be easier to add those types to our hardcoded list.
