### ISSUE TITLE
IntelliSense could not find dependency from current header

### ISSUE THREAD

**Issue by darksectordds** [microsoft/vscode-cpptools#4515]
Hello. For a long time I can not get rid of issue such as 

> couldn't find source file "bits/c++config.h" (dependency of "vector")

Exactly the same problem exists when include the `algorithm` file.

![dependency of vector not found](https://user-images.githubusercontent.com/11490033/67861996-5be23a00-fb32-11e9-9e73-2f727717f4ba.png)

The full path to algorithm and vector are in

> c:\MinGW\lib\gcc\mingw32\8.2.0\include\c++\algorithm
> c:\MinGW\lib\gcc\mingw32\8.2.0\include\c++\vector

And dependence is contained in

> c:\MinGW\lib\gcc\mingw32\8.2.0\include\c++\mingw32\bits\c++config.h

### Visual Studio Code
```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
```

### c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\MinGW\\include",
                "C:\\MinGW\\lib\\gcc\\mingw32\\8.2.0\\include",
                "C:\\MinGW\\lib\\gcc\\mingw32\\8.2.0\\include\\c++\\mingw32\\bits",
                "C:\\MinGW\\lib\\gcc\\mingw32\\8.2.0\\include\\c++",
                "D:\\PSP\\pspsdk\\psp\\include",
                "D:\\PSP\\pspsdk\\psp\\sdk\\include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:\\MinGW\\include",
                    "C:\\MinGW\\lib\\gcc\\mingw32\\8.2.0\\include",
                    "C:\\MinGW\\lib\\gcc\\mingw32\\8.2.0\\include\\c++\\mingw32\\bits",
                    "C:\\MinGW\\lib\\gcc\\mingw32\\8.2.0\\include\\c++",
                    "D:\\PSP\\pspsdk\\psp\\include",
                    "D:\\PSP\\pspsdk\\psp\\sdk\\include"
                ]
            }
        }
    ],
    "version": 4
}
```

### Extensions
```
Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.26.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
```
### MinGW version
![gcc version](https://user-images.githubusercontent.com/11490033/67861967-5127a500-fb32-11e9-9df2-40e708536f1c.png)

### MinGW files
[listfiles.txt](https://github.com/microsoft/vscode-cpptools/files/3789105/listfiles.txt)

**Comment by michelleangela** [comment]
In c_cpp_properties.json, can you try changing the `compilerPath` setting to the path of _g++.exe_ and set `intelliSenseMode` to `gcc-x64`? The language server uses the compiler path to infer the path to the C++ standard library header files. Though since the path to the header files are listed in `includePath`, the language server should have also picked them up. @sean-mcmanus is that correct?

**Comment by darksectordds** [comment]
Thanks. It's helped me.

**Comment by michelleangela** [comment]
Closing as resolved.
