### ISSUE TITLE
A strange syntax problem

### ISSUE THREAD

**Issue by jizhanwang** [microsoft/vscode-cpptools#4516]
![error](https://user-images.githubusercontent.com/45527532/67882178-c91abd00-fb7c-11e9-9a83-7f128c74ca43.png)

**Comment by Colengms** [comment]
Hi @SeeYouBesideSky .  Assuming this is a C file (not cpp), I believe you are seeing correct behavior.  Dynamic initialization is not allowed in C.  Using cl.exe, you should get: error C2099: initializer is not a constant.

Let us know if there is additional information to consider.

**Comment by jizhanwang** [comment]
> 嗨@SeeYouBesideSky。假设这是一个C文件（不是cpp），我相信您看到的是正确的行为。在C中不允许动态初始化。使用cl.exe，您应该得到：错误C2099：初始化程序不是常量。
> 
> 让我们知道是否还有其他信息需要考虑。

Thank you, I got it. But when I run it in my IDE , no error occured. So, can I change some setting to block this warning?

**Comment by Colengms** [comment]
Hi @SeeYouBesideSky .  Which compiler are you using?  gcc, clang, cl?  Is the IntelliSenseMode configured to match the compiler?  If the compiler accepts it, and IntelliSense is configured to match that compiler, this would seem to be an IntelliSense bug.

**Comment by jizhanwang** [comment]
> 嗨@SeeYouBesideSky。您正在使用哪个编译器？gcc 、,、 cl？IntelliSenseMode是否配置为与编译器匹配？如果编译器接受它，并且将IntelliSense配置为与该编译器匹配，则这似乎是IntelliSense错误。

I‘m using KEIL5, I just write code in VScode and then run them in Keil, I have not set anything, so the IntelliSenseMode is MSVC-64, I checked on the internet, Keil has it's own compiler, (°_°!)  .So this syntax is only abled in Keil. but I still have to say "Thank you so much!!!"

**Comment by Colengms** [comment]
Great.  Since we understand what is happening here, I will close the issue.  If there is anything additional, let us know.  :)
