### ISSUE TITLE
When clicking on erros in problem view, duplicate files are opened with "." as directory.

### ISSUE THREAD

**Issue by martincohen** [microsoft/vscode-cpptools#452]
I'm using MSVC 2015. When I click on errors in problem view, I get the file opened as a duplicate with path "." (for example `lib.h` opens again as `lib.h .`) This later causes errors with saving files (as Code detects that the file is "newer" on the disk).

VS Code version 1.8.1, freshly installed `cpptools` today.

**Comment by sean-mcmanus** [comment]
This doesn't seem like an issue with our C++ extension. I assume it repros without our extension enabled? Can you file a bug with https://github.com/Microsoft/vscode ?

**Comment by martincohen** [comment]
Yah, I'm opening an issue there. Sorry for the confusion. Closing now.
