### ISSUE TITLE
"Go to Definition" does NOT work after upgrading to Version 1.39.2

### ISSUE THREAD

**Issue by zengletian1491** [microsoft/vscode-cpptools#4521]
When I do the  “Go to Definition" operation, "no definition for  .. " appears on the screen! I do not find a solution. Could you please give me a hand? Thanks very much!

**Comment by zengletian1491** [comment]
I solved it today.
Solution：
1、reinstall the VSCODE
2、type "C/C++" in the left upper corner of the VSCODE, as shown in the following:
![2019-11-01_202001](https://user-images.githubusercontent.com/53558305/68024421-09954a80-fce5-11e9-82d3-e04bf2beb3f8.png)
3、select "C/C++ 0.26.1" and install it.
Well done!

**Comment by michelleangela** [comment]
Closing as resolved.
