### ISSUE TITLE
The intelligent prompt shall give some information when use #if, #elif.

### ISSUE THREAD

**Issue by JasonLeeCn** [microsoft/vscode-cpptools#4522]
Issue Type: <b>Feature Request</b>

Some time we need check the macro value for pre-process using #if, #elif. But now the extension is not give any intelligent prompt.

Extension version: 0.26.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sean-mcmanus** [comment]
What do you mean by "intelligent prompt"? We show hover info. Do you mean autocomplete?

**Comment by bobbrow** [comment]
We need more information to fully investigate this issue. If you update to the latest version of the extension and your issue persists, please reply with additional information that can help us investigate your issue. Thank you!
