### ISSUE TITLE
VSC 1.39.2 with C++ extension 0.26.1 formatter corrupting code

### ISSUE THREAD

**Issue by SanjayVyas** [microsoft/vscode-cpptools#4524]
**Type: LanguageService**

When using formatter in C++ file, it corrupts the code, by inserting bits an pieces of existing code into various location. The issue does not start immediately after opening VSC, but after a while.

Following is one such example

Code before formatting
```
while (node)
{
     while (node)
     {
           stack.push(node);
            node = node->left;
     }     
}
```
Code after formatting
```
while (node)
        {
            while (node)
                stack.push(node);
            **sh(node->value);**
            node = node->left;
        }
```
It is becoming impossible to use vscode as the corruption happens in random places and not near the cursor. Sometimes random bits and pieces are inserted at the end, sometimes at the top of the file. This munges the code so much that I have to undo multiple times, sometimes losing code. I have to then inspect the entire file and rewrite the code all over again. Sheer pain!

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Are you using a multi-root workspace? We have a similar issue at https://github.com/microsoft/vscode-cpptools/issues/1073 .

**Comment by SanjayVyas** [comment]
Looks like formatting issue maybe happening due to recent vim extension. I have installed an earlier version 1.11.0 to see if formatting still corrupts.

**Comment by SanjayVyas** [comment]
I suspected the formatter and then vim, but I now suspect its another extension called pisoniq headers. pisoniq has a feature of updating the header on save, and it may be causing the corruption. Will observe for a while more to confirm.

**Comment by SanjayVyas** [comment]
Now I am running ONLY C++ extension and no other extension, yet face the default formatter corruption

**Comment by SanjayVyas** [comment]
The problem definitely seems to be with C++ extension and default formatter. VS code is now unusable to write C++ code as I scared I will lose the code when it gets formatted. It doesn't start immediately, but happens after editing for a while. Once it happens, the code is munged and unrecoverable. I have to manually recall what I had written and fix line by line.

**Comment by michelleangela** [comment]
Do you have any format settings configured? Such as `editor.defaultFormatter` or `C_Cpp.clang_format_path`, `C_Cpp.formatting`?

**Comment by sean-mcmanus** [comment]
Is this a multi-root workspace?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
