### ISSUE TITLE
Could not find the task 'C:/MIngw/bin/g++.exe'.

### ISSUE THREAD

**Issue by torresdale** [microsoft/vscode-cpptools#4527]
Type: Debugger
I am having the error message whenever I try to run a program. 

Everything has been properly installed and the variable path properly configured. 
![Error](https://user-images.githubusercontent.com/57095414/68078078-71918100-fe0a-11e9-8a2a-7bb63364da21.PNG)

**Describe the bug**
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by sean-mcmanus** [comment]
What is your launch.json?

**Comment by torresdale** [comment]
[cid:39df236e-ce8d-490a-a6a7-63f56c11c3d8][cid:9d88befe-ecec-4f0e-b647-656fd796e9a4]
________________________________

**Comment by bobbrow** [comment]
It looks like something didn't copy over correctly when you sent it via email.

**Comment by torresdale** [comment]
Those were 2 screenshots actually. So I need to send it in just one screenshot?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bobbrow** [comment]
I think you need to do images via the website. This is what got posted instead of the screenshots:

[cid:39df236e-ce8d-490a-a6a7-63f56c11c3d8][cid:9d88befe-ecec-4f0e-b647-656fd796e9a4]

**Comment by torresdale** [comment]
________________________________

**Comment by torresdale** [comment]
![001](https://user-images.githubusercontent.com/57095414/68368731-a0458980-0173-11ea-86af-848db254718f.PNG)
![002](https://user-images.githubusercontent.com/57095414/68368735-a0de2000-0173-11ea-8bad-f2b554957e27.PNG)
![003](https://user-images.githubusercontent.com/57095414/68368736-a0de2000-0173-11ea-9e4f-786715320e48.PNG)

**Comment by sean-mcmanus** [comment]
I don't think preLaunchTask accepts an executable -- the executable should be wrapped in a task in a tasks.json file.

**Comment by bobbrow** [comment]
That is correct.  preLaunchTask needs to be the "name" of another task (presumably one that has g++.exe as the "command").

**Comment by torresdale** [comment]
It was already that way when I had it installed.
Sorry Im really new to this. Do I delete or or change something ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by blacksky9727** [comment]
i have same problem as torresdale. and i'm also new to this.

**Comment by michaelafruiz** [comment]
I have same issue as well.

**Comment by sean-mcmanus** [comment]
You need to create a build task in tasks.json. See https://code.visualstudio.com/docs/cpp/config-mingw#_create-a-build-task . I don't know how your preLaunchTask got populated with the g++.exe path.

**Comment by blacksky9727** [comment]
Thank you for this information. I'll try this if it works for me.

**Comment by blacksky9727** [comment]
Is it the same MinGw? It says MinGw-64w. My school said that i should use
MinGW.

**Comment by sean-mcmanus** [comment]
You could change the paths described in the docs to use MinGW instead of MinGW-w64...if your school said to use "MinGW" they could mean either "MinGW" or "MinGW-w64": https://stackoverflow.com/questions/25582110/what-is-the-difference-between-mingw-mingw-w64-and-mingw-builds .

**Comment by keipei25** [comment]
hi,
did anyone already solve this issue? we have the same problem and i have been dealing with this for almost 2 months. and still couldn't find the answer. not sure why my school provides invalid codes for beginners like me.

**Comment by blacksky9727** [comment]
Yeah. Same
I really don't know how to fix it. I don't know anything about it. And the
professor of the subject didn't answer my questions and emails. How am i to
know any of this? I'll definitely have a fail grade in this class.

**Comment by blacksky9727** [comment]
Someone gave me a help about it but not sure of it. Because it says MinGW
-w64 not MinGW . The school said use MinGW.

**Comment by torresdale** [comment]
Still cant fix it 😥

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by blacksky9727** [comment]
If i can't still fix it. I might need a real IT to fix it. I don't know any
IT so that might be difficult. But i need to find a way to fix it or else i
might fail. Just let me know if you fix it too. If i can't fix it, i can't
do the machine problem that i need to do.😥😭

**Comment by michaelafruiz** [comment]
Hey guys,

See the link For the same issue

https://github.com/jmadoremos/amaoed-cpp-template/commit/710912524e78959c9e20a1922ff1894e5b872541

Please create a ticket/post a student concern on our online portal and ask for the updated project/source folder. I’m just not sure guys if I can provide you here the project/source folder due to data privacy of our school. Our professor will definitely
 provide you the latest one. Just make sure to attach the error you are receiving in VS Code  so she can assist you ASAP. 

<img width="487" alt="711CCCEE-FB27-4B28-AB22-668CD69CFD64" src="https://user-images.githubusercontent.com/56989201/69011171-a4a74900-09a2-11ea-8382-31523e50f1a7.png">

**Comment by blacksky9727** [comment]
She isn't responding to any of my emails though. Some of the professors l
responds if you directly email them. And what kind of ticket/post a concern
should i do? They are too many and i can't find the right one. Like
academic concerns,content dev etc.

**Comment by michaelafruiz** [comment]
Academic concerns then lesson/module/presentation topic inquiry

**Comment by torresdale** [comment]
I posted the concern 3 times already but did not get any response as well.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by blacksky9727** [comment]
I got a response just now. She gave me a new project folder.

**Comment by keipei25** [comment]
I got an email from her and followed what it says. But I couldn't extract the file to my project folder because it is rar format.

Please check the email below and try if it works.


![image](https://user-images.githubusercontent.com/55885307/69065567-560db380-0a63-11ea-9fd9-d00c16714a17.png)


kindly visit this link (https://drive.google.com/file/d/1pQ0IbG-YUHIBS3ic78VH81_DGxJSrzHH/view?usp=sharing)

**Comment by blacksky9727** [comment]
I tried it also. But when i tried it on my phone. It extract the folder.
But i don't know how to put it on computer.

**Comment by keipei25** [comment]
I used winzip to extract the rar file from the link. and put it in my project folder but there is still an error to the updated code of the hello world.

![image](https://user-images.githubusercontent.com/55885307/69145070-24065b00-0b10-11ea-9e05-bdca166a562d.png)

bagsak kung bagsak lol

**Comment by blacksky9727** [comment]
Hahaha kaya nga panu na yun

**Comment by torresdale** [comment]
Not getting any luck with the instructor. Still no response even from my oine buddy

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by michaelafruiz** [comment]
I think you opened the wrong file. It should be like these in your launch.json

<img width="1028" alt="02052944-B4D8-4C10-B33E-9777EB30BC45" src="https://user-images.githubusercontent.com/56989201/69147562-3af77e00-0b0d-11ea-9a57-0a2579f62ad7.png">
<img width="936" alt="0338475D-035D-4B52-8D61-4BE1E533F428" src="https://user-images.githubusercontent.com/56989201/69147563-3b901480-0b0d-11ea-941a-5228fd85ec7d.png">
<img width="964" alt="3CB8C671-7614-46A1-B6A0-B9BFDA5B4D3D" src="https://user-images.githubusercontent.com/56989201/69147564-3c28ab00-0b0d-11ea-89a3-3d269d929ccb.png">

**Comment by blacksky9727** [comment]
Micheal Angelo,
Have you fix it?

**Comment by michaelafruiz** [comment]
Yes I haved fixed it already.
These are the steps that I did:

1. Extract the file in the project folder you are going to use in VS Code.

2. Open the VS Code app.

3. In the file tab of VS Code, click Open Folder then locate the file that you have extracted which is the Project Folder.

4. Start debugging.

If the debugging didn’t work, you have to restart your pc/laptop. And do the steps number 2 to 4.

**Comment by blacksky9727** [comment]
Micheal angelo,
How did you extract the folders?

**Comment by michaelafruiz** [comment]
I used the WinZip app to extract the file.

**Comment by torresdale** [comment]
Turns out the problem is from the materials provided by the instructor. 
Thanks for all your help

**Comment by torresdale** [comment]
- [ ]

**Comment by blacksky9727** [comment]
Yeah. Buti na lang nag response din yung prof.

**Comment by mariearianemae** [comment]
Glad I came across this thread. Thank you, classmates! :)

**Comment by keipei25** [comment]
hello guys~ are you able to run the hello world program now?

I tried to copy the code of launch.json that is shown above but i failed again. bagsak n tlg haha

**Comment by keipei25** [comment]
kung sino man may mabuting puso. iiscreenrecord nyo nmn panu i run c hello world, from settting up the environment hggng debugging ^^ maybe i missed something, or my device is not really compatible with this. i don't know. pretty please~

**Comment by blacksky9727** [comment]
Oo. Hingiin mo kay prof yung bagong code.

**Comment by keipei25** [comment]
could you send it to me sa email? hnd kz sya responsive

**Comment by keipei25** [comment]
https://drive.google.com/file/d/1pQ0IbG-YUHIBS3ic78VH81_DGxJSrzHH/view

i was advised to download the rar file from this

hnd ba to un?

**Comment by blacksky9727** [comment]
Oo. Yan yun. E extract mo yung file. Download mo sya then open mo yung file
using a WinRar or WinZip ata.. Winrar ginamit ko para ma extract yun.

**Comment by blacksky9727** [comment]
Naging responsive naman yung prof. Yun nga lang matagal. Mga nakaraang
araw, responsive sya.

**Comment by keipei25** [comment]
ni dl q to and extract sa winzip app. still not working. try ko ult tomorrow. bale etong subject na lng aq d makapagproceed dhl dto. since nakapagfinal na aq s 3 subjects. eto na hinaharap q. hayy hirap pg d actual na tinuturo. hehe

**Comment by keipei25** [comment]
<img width="489" alt="캡처" src="https://user-images.githubusercontent.com/55885307/70149087-c286e480-16ea-11ea-9dd5-a65147f35340.PNG">
 eto lng bale problema q

**Comment by blacksky9727** [comment]
Actually, ito na rin yung last subject ko. Katatapos ko lang nung isa. Same
prof din. Pero di ko pa rin matapos kasi walang kuryente dito. Badtrip yung
bagyo eh. 2 lesson na lang tapos na then final exam. Tapos ko na rin kasi
yung 3 machine problem.

**Comment by blacksky9727** [comment]
Ganyan din yun akin. Sa code ata yung may problema. Kaso minsan hindi sya
nag de debug. Like yung sakin, dapat C++ Launch nakasulat para madebug yung
code kaso C+ lang nakalagay. Kaya puro Hello World lang ang lumalabas.
Kahit iba naman yung codes na nakalagay. Yun yung naging problem ko sa last
machine problem. Naka install din naman kasi yung C/C++ extension.

**Comment by keipei25** [comment]
pre pwd mo ba send sa email ko ung project folder mo. try q i run sa akin. ok lng b? pra malaman ko ung prob sa code. hnd tlg aq magaling sa ganto. sorry

**Comment by blacksky9727** [comment]
Same lang din naman tayo. Bagohan din naman. Wala talaga akong alam sa mga
ganto eh. Pwede ko naman e send sayo. Ang problema lang is nasa laptop ko
pa yung file. Walang kuryente dito sa lugar namin dahil sa bagyong tisoy.
Tsaka mukhang matatagalan pa bago magkakuryente dito. Dahil maraming poste
ng kuryente ang natumaba at naputol. Tsaka sira rin yung battery ng laptop
ko. Di sya gumagana kung hindi nakasaksak yung charger.

**Comment by KurtAshing** [comment]
> https://drive.google.com/file/d/1pQ0IbG-YUHIBS3ic78VH81_DGxJSrzHH/view
> 
> i was advised to download the rar file from this
> 
> hnd ba to un?

this one works to me. Thanks

**Comment by ryanmngyty** [comment]
Just make sure na yung previous folders na we selected sa VS Code will be replaced by the new ones provided on this file. https://drive.google.com/file/d/1pQ0IbG-YUHIBS3ic78VH81_DGxJSrzHH/view

**Comment by JunHilot1990** [comment]
> I got an email from her and followed what it says. But I couldn't extract the file to my project folder because it is rar format.
> 
> Please check the email below and try if it works.
> 
> ![image](https://user-images.githubusercontent.com/55885307/69065567-560db380-0a63-11ea-9fd9-d00c16714a17.png)
> 
> kindly visit this link (https://drive.google.com/file/d/1pQ0IbG-YUHIBS3ic78VH81_DGxJSrzHH/view?usp=sharing)

Thanks men

**Comment by JohnpaulVerzosa** [comment]
> hi,
> did anyone already solve this issue? we have the same problem and i have been dealing with this for almost 2 months. and still couldn't find the answer. not sure why my school provides invalid codes for beginners like me.

we're the same
