### ISSUE TITLE
Unable to compile .cpp codes

### ISSUE THREAD

**Issue by shasha101** [microsoft/vscode-cpptools#4528]
Type: Debugger

**Describe the bug**
- C/C++ Debugger for VS Code

I've followed all the steps shown in "Get Started with C++ and Microsoft C++ compiler (MSVC)" yet I keep receiving below error message in **OUTPUT** when I try to run code:
>> [Running] cd "c:\Windows\System32\projects\coding\.vscode\" && g++ coding.cpp -o coding && "c:\Windows\System32\projects\coding\.vscode\"coding
'g++' is not recognized as an internal or external command,
operable program or batch file.

**and the following error message in TERMINAL:**
Executing task: cl.exe /EHsc /Zi /Fe: coding.exe coding.cpp

Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

coding.cpp
c1xx: fatal error C1083: Cannot open source file: 'coding.cpp': No such file or directory
The terminal process terminated with exit code: 1

It's funny that error mentions g++ when im actually trying to run with msvc.

**Notes:** 
1. I changed the variable helloworld to "coding" but I dont see how this could be an issue.
2. I added the **cl.exe** directory in PATH for both system and user environments:
>> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64
**Result: No impact**

**===To Reproduce===**
**Codes to be run, saved as coding.cpp**
#include <iostream>
#include <vector>
#include <string>

using namespace std;

int main()
{

    vector<string> msg {"Hello", "C++", "World", "from", "VS Code!"};

    for (const string& word : msg)
    {
        cout << word << " ";
    }
    cout << endl;
}
**===Below is `launch.json` configuration.===**
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "(msvc) Launch",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "${workspaceFolder}/coding.exe",
        "args": [],
        "stopAtEntry": true,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false
      }
    ]
  }

**===Below is `c_cpp_properties.json` configuration.===**
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
**settings.json**
just twp corly brackets shown below:
>>{
>>}
is this normal???

I've been trying to setup VS Code for 2 days now...Need to start on my coding project real soon. Anyy help is really appreciated. Thanks in advance.

**Comment by sean-mcmanus** [comment]
What is your task.json that you're using to compile? The "Executing task" log appears to be missing the workspaceFolder paths for the .exe and .cpp files.

Empty settings.json is okay.
