### ISSUE TITLE
[loc][Query][vscode-cpptools] Localizability of verbosity level

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4535]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The verbosity of logging in the Output Panel. The order of levels from least verbose to most verbose is: None < Error < Warning < Information < Debug.

File Name:
Src\vscode-extensions\vscode-cpptools.xlf

Query:
Translator thinks that 'None < Error < Warning < Information < Debug' should be kept in English as they are the values of verbosity level. Would you please check if this is correct?

**Comment by Colengms** [comment]
That is correct.  These are potential values for the setting.

**Comment by PDostalek** [comment]
Thanks
