### ISSUE TITLE
Symbols missing after update to 0.26.0 on Windows 7

### ISSUE THREAD

**Issue by geusr** [microsoft/vscode-cpptools#4536]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them): gitlens, powershell

After upgrading to 0.26, the outline view is empty and the breadcrumbs only available up to file level.

**To Reproduce**

1. Update to cpptools 0.26.1 and reload window
2. Select any C file
3. Change something and save it
4. Symbols disappear from outline view and breadcrumbs (but no error message)
5. Downgrade to cpptools 0.25.1 and reload window
6. Select any C file
7. Change something and save it
8. Symbols reappear

**Expected behavior**

Symbols should be available also in 0.26

**Comment by bobbrow** [comment]
Could be related to #4470?  Can you share an example code file that reproduces the issue?

**Comment by sean-mcmanus** [comment]
I'm not able to repro it (we need a repro to investigate further).

I don't think it's related to https://github.com/microsoft/vscode-cpptools/issues/4470 .

It's possible it's some problem related to the C++/CX change.

**Comment by geusr** [comment]
Hi again

I have this problem for all my source folders, even when they contain only a single C file. I have attached a zipped source folder as an example.

[exec_test.zip](https://github.com/microsoft/vscode-cpptools/files/3818653/exec_test.zip)

0.26.0 and 0.26.1 both have the same issue.

Also I have tried to reinstall vscode, which didn't help.

My extension folder looks like this

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          16.02.2018    16:51                adammaras.overtype-0.2.0
d----          07.11.2019    09:06                eamodio.gitlens-10.1.2
d----          30.08.2019    09:08                fcrespo82.markdown-table-formatter-1.4.3
d----          07.09.2018    14:59                helixquar.asciidecorator-0.2.0
d----          10.10.2019    09:16                marvhen.reflow-markdown-2.1.0
d----          24.10.2019    15:53                ms-python.python-2019.10.44104
d----          07.11.2019    09:21                ms-vscode.cpptools-0.26.1
d----          04.11.2019    17:28                ms-vscode.powershell-2019.11.0
d----          27.05.2019    16:37                slysherz.comment-box-2.0.0
d----          15.08.2019    18:17                troelsdamgaard.reflow-paragraph-1.3.0
d----          13.02.2018    09:39                twxs.cmake-0.0.17

0.26.1:
![0 26 1](https://user-images.githubusercontent.com/57392540/68374084-71fc8580-0144-11ea-9445-1528533d4a96.PNG)

0.25.1:
![0 25 1](https://user-images.githubusercontent.com/57392540/68374097-7c1e8400-0144-11ea-88a8-7748b2ee23c7.PNG)

Thanks and best regards,
Roman

**Comment by michelleangela** [comment]
Was able to reproduce on Windows 7 only. 

Version 0.26.0 adopted the DocumentSymbol API https://github.com/microsoft/vscode-cpptools/issues/2230, so it could be related to that change.

Verified that outline view works for TypeScript to rule out issue being specific to VS Code client.

**Comment by michelleangela** [comment]
@geusr , can you try the following workaround?

Copy the files `msvcp140.dll` and `vcruntime140.dll` that are in folder:
`C:\Users\%username%\.vscode\extensions\ms-vscode.cpptools-0.26.1\LLVM\bin`

to folder:
`C:\Users\%username%\.vscode\extensions\ms-vscode.cpptools-0.26.1\bin`

Note that for this workaround, these files need to exist in both folders.

**Comment by geusr** [comment]
@michelleangela Your proposed workaround fixed my problem!

Thanks a lot!
- Roman

**Comment by michelleangela** [comment]
Fixed in version 0.26.2-insiders, available at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders.
