### ISSUE TITLE
Crash after formatting selection

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4539]
Any solutions to this yet?
I have a similar issue: VSCode on Ubuntu 19.1, with C/C++ 0.26.1 extension installed. When I try to format a selected part of my code, I receive the error:

    [Error - 6:16:27 p.m.] Connection to server got closed. Server will not be restarted.
    [Error - 6:16:27 p.m.] Request textDocument/rangeFormatting failed.

_Originally posted by @kei2e in https://github.com/microsoft/vscode-cpptools/issues/1975#issuecomment-550067235_

**Comment by sean-mcmanus** [comment]
@kei2e Our language server process is crashing. Can you attach a debugger to the Microsoft.VSCode.CPP.Extension.linux and provide a callstack or give more repro details? Are you using a multi-root workspace?

**Comment by kei2e** [comment]
@sean-mcmanus sorry, I am very new to this. Can you plz give me some instructions on how to attach a debugger to Microsoft.VSCode.CPP.Extension.linux?

No, I am not using a multi-root workspace.

**Comment by sean-mcmanus** [comment]
There are some docs at https://code.visualstudio.com/docs/cpp/cpp-debug.

You basically just need to create a launch.json file with a "(gdb) attach" config and set the program to the full path of the Microsoft.VSCode.CPP.Extension.linux binary (e.g. `/home/user/.vscode/extensions/ms-vscode.cpptools-0.26.1/bin/Microsoft.VSCode.CPP.Extension.linux`). Then click the Start Debugging button and repro the crash. Let me know if you want more info.

**Comment by sean-mcmanus** [comment]
Also, we have no known crashes involving formatting, so anything special about your environment or format settings you could think of could help (might be related to Ubuntu 19).

**Comment by sean-mcmanus** [comment]
Also, if you could set the C_Cpp.clang_format_path to another clang-format such as from http://releases.llvm.org/download.html , it's possible that could fix/workaround the issue.

**Comment by sean-mcmanus** [comment]
Looks like other users have hit this at https://github.com/microsoft/vscode-cpptools/issues/3559 .

**Comment by kei2e** [comment]
@sean-mcmanus thanks for the instructions and help!
I am working on it to provide you with more info .. in the meantime, I tried the formatter on a separate test.cpp file and got the following:

```
Formatting failed:
/home/keyvan/.vscode/extensions/ms-vscode.cpptools-0.26.1/bin/../LLVM/bin/clang-format -style={ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 2, TabWidth: 2, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -2 } -fallback-style=LLVM -sort-includes=0 -offset=364 -length=77 -assume-filename=/home/keyvan/test.cpp
/home/keyvan/.vscode/extensions/ms-vscode.cpptools-0.26.1/bin/../LLVM/bin/clang-format: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
  
```

**Comment by kei2e** [comment]
Okay .. it was fixed by installing clang-format,
`sudo apt install clang-format`
and adding
`{
  "C_Cpp.clang_format_path": "/usr/bin/clang-format"
}`
to `settings.json`, as suggested by **penguingovernor** at [#3174](https://github.com/microsoft/vscode-cpptools/issues/3174). Now the formatter appears to be working fine in both workspaces.

I still do not know what exactly is going on. But let me know if I can be of any help figuring that out.

**Comment by sean-mcmanus** [comment]
Our Insiders release should fix this clang-format issue: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders
