### ISSUE TITLE
freezing the ui for N seconds.

### ISSUE THREAD

**Issue by janwilmans** [microsoft/vscode-cpptools#4540]
The whole vscode ui freezed for ~30 seconds.

Type: General

![image](https://user-images.githubusercontent.com/5933444/68297631-c138ac80-0097-11ea-84f1-aa0b89b0c399.png)

**Describe the bug**

Version: 1.39.2
Commit: 6ab5985
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.0-6-amd64

Steps to Reproduce:

it happened while compiling a single file within a c++ cmake project

**Comment by michelleangela** [comment]
This could be a VS Code client issue and not an issue with the C/C++ extension. The extension does not have compiling capabilities. 

Does the issue reproduce if the extension is also disabled? Were you doing other operations while it was compiling (such as scrolling through a file, hovering over a symbol)?
