### ISSUE TITLE
Use the markdownDescription property for settings

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#4544]
settings descriptions in `package.json` that reference enum values should use the `markdownDescription` property instead of `description`.

**Comment by Colengms** [comment]
This is potentially problematic, as our settings descriptions get localized.  We could see problems if the localization team does not use markdown in translations, or uses characters that inadvertently trigger markdown formatting.

**Comment by Colengms** [comment]
I have this issue open against nls-dev, which doesn't appear to have gotten any attention.  We could look at contributing this to nls-dev.  https://github.com/microsoft/vscode-nls-dev/issues/21

**Comment by Colengms** [comment]
Although the vscode-nls-dev issue I mentioned has been closed, it did not address the lack of a way to specify a 'hint' to localizers for strings defined in `package.nls.json`.

**Comment by Colengms** [comment]
I created a PR to enable support for this, in vscode-nls-dev: https://github.com/microsoft/vscode-nls-dev/pull/33

**Comment by sean-mcmanus** [comment]
We should also change all the settings reference to be like `#editor.tabSize#` so that they're linked.

**Comment by Colengms** [comment]
Note that this is currently blocked until the next release of VS Code (>1.57.x), due to depending on this change: https://github.com/microsoft/vscode/pull/126462

**Comment by sean-mcmanus** [comment]
@Colengms 1.57.0 is already released....so it's not blocked?

**Comment by Colengms** [comment]
1.57.0 was released on June 10.  The fix was submitted on June 21.  I assume that means we need to wait until 1.58 is released.

**Comment by sean-mcmanus** [comment]
Okay, looks like they plan to release 1.58.0 any day now (https://github.com/microsoft/vscode/issues/127394)...but I'm not sure if that's too early to have a 1.58.0 pre-requisite for 1.6.0.

**Comment by sean-mcmanus** [comment]
Fixed in my clang-tidy branch...I might port it team/vcls/vscode later.
