### ISSUE TITLE
"Cannot determine executable for debug adapter {...}" error message

### ISSUE THREAD

**Issue by tomasz-rozanski** [microsoft/vscode-cpptools#455]
After upgrading to VSCode v1.9-insider (01-19-2017), when trying to debug Windows executable, I'm getting the following error message:

> Cannot determine executable for debug adapter 'C:/Users/Tomek/.vscode-insiders/extensions/ms-vscode.cpptools-0.9.3/debugAdapters/vsdbg/bin/clrdbg.exe'.

My launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "C++ Launch (Windows)",
      "type": "cppvsdbg",
      "request": "launch",
      "program": "${workspaceRoot}/${fileBasenameNoExtension}.exe",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceRoot}",
      "environment": [],
      "externalConsole": false
    },
    {
      "name": "C++ Attach (Windows)",
      "type": "cppvsdbg",
      "request": "attach",
      "processId": "${command.pickProcess}"
    }
  ]
}
```

**Comment by pieandcakes** [comment]
@Rosto75 If you don't use ${fileBasenameNoExtension} does it work?

**Comment by tomasz-rozanski** [comment]
I tried many configurations (${fileBasename}, ${file} and literal 
executable name) but with no luck. The same exact config still works in 
VSC 1.8, though.

------ Original Message ------

**Comment by pieandcakes** [comment]
@Rosto75 It sounds like they may have made changes in the Insiders program that broke how they are sending the file name. I'll try and hookup a repro.

**Comment by pieandcakes** [comment]
@Rosto75 it looks like its a VSCode issue. [Microsoft/vscode#19386](https://github.com/Microsoft/vscode/issues/19386) has been filed for it.
