### ISSUE TITLE
vscode-cpptools is not running on CentOS 7

### ISSUE THREAD

**Issue by sergio-nsk** [microsoft/vscode-cpptools#456]
Error: /Microsoft.VSCode.CPP.Extension.linux: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./Microsoft.VSCode.CPP.Extension.linux)
Please compile and link vscode-cpptools with the older GLIBC 2.17.

**Comment by pieandcakes** [comment]
@sergio-nsk same as #19 . There is a workaround in that Issues page if you would like it to work.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
