### ISSUE TITLE
haven't auto indent whenever press enter。

### ISSUE THREAD

**Issue by lfjbb** [microsoft/vscode-cpptools#4563]
![捕获](https://user-images.githubusercontent.com/35714131/68454930-15c55e80-0235-11ea-9dbb-fe99575c9c20.PNG)
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

![捕获1](https://user-images.githubusercontent.com/35714131/68452625-0ee71d80-022e-11ea-8466-107aa227e368.PNG)
![捕获](https://user-images.githubusercontent.com/35714131/68452661-27efce80-022e-11ea-9b7c-ac43f4d51e7d.PNG)

![捕获](https://user-images.githubusercontent.com/35714131/68454951-237ae400-0235-11ea-8feb-89b3ff3557de.PNG)

**Comment by michelleangela** [comment]
Can you provide an example of when auto indent does not occur when pressing enter? Is it pressing enter after a statement or within function arguments?

Is your auto indent related to https://github.com/microsoft/vscode-cpptools/issues/1993 or https://github.com/microsoft/vscode-cpptools/issues/883?

**Comment by lfjbb** [comment]
> Can you provide an example of when auto indent does not occur when pressing enter? Is it pressing enter after a statement or within function arguments?
> 
> Is your auto indent related to #1993 or #883?

actually , it's does work everywhere and everytime

**Comment by michelleangela** [comment]
Closing as resolved.

**Comment by lfjbb** [comment]
> Closing as resolved.

is there something wrong with my vscode or don't have this function yet？

**Comment by michelleangela** [comment]
Hi @lfjbb 

I closed the issue as resolved because of the comment:
> actually , it's does work everywhere and everytime


From the screenshots you provided, the circled blue line means an edit was done to that line. 
![image](https://user-images.githubusercontent.com/38734287/68456081-bb36ee80-01b1-11ea-9bdc-19ab19983416.png)

Sorry if I misunderstood the issue you are reporting. Is the issue about the editor is not doing an auto indent or is the issue about the editor doing an auto indent when it should not?

**Comment by lfjbb** [comment]
> everywhere
there is a typing error
actually , it's doesn't work everywhere and everytime, the editor is not doing an auto indent。

**Comment by lfjbb** [comment]
> Hi @lfjbb
> 
> I closed the issue as resolved because of the comment:
> 
> > actually , it's does work everywhere and everytime
> 
> From the screenshots you provided, the circled blue line means an edit was done to that line.
> ![image](https://user-images.githubusercontent.com/38734287/68456081-bb36ee80-01b1-11ea-9bdc-19ab19983416.png)
> 
> Sorry if I misunderstood the issue you are reporting. Is the issue about the editor is not doing an auto indent or is the issue about the editor doing an auto indent when it should not?

sorry, there is a typing error
actually , it's doesn't work everywhere and everytime, the editor is not doing an auto indent。
if the editor doing an auto indent. the screenshots should be like this one:
![捕获](https://user-images.githubusercontent.com/35714131/68457105-71deb180-023a-11ea-832e-55f678363715.PNG)
![捕获](https://user-images.githubusercontent.com/35714131/68457154-89b63580-023a-11ea-966e-d96c9f64e864.PNG)

**Comment by lfjbb** [comment]
this problem may cause by a conflict with vsc-python-indent extension. I uninstall that extension. then the "enter" key doesn't work. with the help from microsoft/vscode I sloved the "enter" key problem and uninstall  vsc-python-indent extension then everything is fine.  but I can't reproduce this problem now.
thanks!!
