### ISSUE TITLE
Enhanced colorization and intellisense not working on Linux

### ISSUE THREAD

**Issue by SPAstef** [microsoft/vscode-cpptools#4569]
**Type: LanguageService**
**Describe the bug**
- OS and Version: Clear Linux 31520
- VS Code Version: code-insiders-1.40.0-1573062522, tried also VS Code stable 1.39
- C/C++ Extension Version: 0.26.1, tried also 0.26 and 0.25
- Other extensions you installed (and if the issue persists after disabling them): Customize UI, Java Extension Pack, Italian language pack, markdown lint, Material Icon Theme, Material Theme, shell-format, Visual Studio IntelliCode. It does persist even on a clean installation of stable VS Code, with just cpptools.
- A clear and concise description of what the bug is. Enhanced colorization doesen't work. With the exact same extensions, on Windows I get colored types, darkened not-defined code regions, etc. Also function hidden by a "#ifdef" condition, when exposed don't appear in the suggestion snippet, and when writing them down "by hand" their prototype is shown as "int foo(void)". I tried the vscode-ccls extension and it does work, so it's definetly an extension problem.

**To Reproduce**
1. Go to a C/C++ source/header file
2. Scroll down to any piece of code
3. See error

**Additional context**
VS Code was installed via RPM. When launched the first time it used a weird monospaced font throughout the UI, so I had to install the Customize UI extension. Another problem I had was with the formatter, which I had to manually redirect to the correct clang-format binary in my /usr/bin directory. So this is probably the same problem: the extension ships with some integrated language server binary that for some reason doesen't work... I don't know if this is Clear Linux or VS Code's fault...

**Comment by Colengms** [comment]
Hi @SPAstef .  I don't believe this is something that is impacting most users, so we could use some additional information about what's happening on your system.  Could you try enabling debug logging using the setting: `"C_Cpp.loggingLevel": "Debug"`?  That may output some clues to the C/C++ output channel.  Also, if you run `C/C++: Log Diagnostics` after opening a source file, that might provide some insights into the state of IntelliSense for that file.

**Comment by SPAstef** [comment]
```initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
Autocomplete is enabled.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: /usr/include/bits
File exclude: /usr/include/linux
File exclude: /usr/include/sys
File exclude: /usr/include/asm
File exclude: /usr/include/asm-generic
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Attempting to get defaults from compiler found on the machine: '/usr/bin/clang'
terminating child process: 2711
cpptools/queryCompilerDefaults: 1
Attempting to get defaults from compiler found on the machine: '/usr/bin/clang'
terminating child process: 2716
cpptools/didChangeFolderSettings
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/gcc'
terminating child process: 2719
Code browsing service initialized
Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/gcc'
terminating child process: 2721
  Folder: /usr/lib64/gcc/x86_64-generic-linux/9/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /usr/lib64/gcc/x86_64-generic-linux/9/include-fixed/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/ will be indexed
Populate include completion cache.
Discovering files...
  Processing folder (recursive): /usr/lib64/gcc/x86_64-generic-linux/9/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /usr/lib64/gcc/x86_64-generic-linux/9/include-fixed/
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/
  Discovering files: 5751 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
textDocument/didOpen
Checking for syntax errors: file:///run/media/stefano/Windows%2010/Users/stefa/Documenti/universita/tirocinio/ba_horn/include/ord.h
cpptools/getCodeActions: 2
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: 3
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/getCodeActions: 4
sending compilation args for /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/src/ord.c
  include: /usr/lib64/gcc/x86_64-generic-linux/9/include
  include: /usr/local/include
  include: /usr/lib64/gcc/x86_64-generic-linux/9/include-fixed
  include: /usr/include
  include: /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/include
  define: __STDC__=1
  define: __STDC_VERSION__=201112L
  define: __STDC_UTF_16__=1
  define: __STDC_UTF_32__=1
  define: __STDC_HOSTED__=1
  define: __GNUC__=9
  define: __GNUC_MINOR__=2
  define: __GNUC_PATCHLEVEL__=1
  define: __VERSION__="9.2.1 20191106 gcc-9-branch@277869"
  define: __ATOMIC_RELAXED=0
  define: __ATOMIC_SEQ_CST=5
  define: __ATOMIC_ACQUIRE=2
  define: __ATOMIC_RELEASE=3
  define: __ATOMIC_ACQ_REL=4
  define: __ATOMIC_CONSUME=1
  define: __pic__=2
  define: __PIC__=2
  define: __pie__=2
  define: __PIE__=2
  define: __OPTIMIZE__=1
  define: __FINITE_MATH_ONLY__=0
  define: _LP64=1
  define: __LP64__=1
  define: __SIZEOF_INT__=4
  define: __SIZEOF_LONG__=8
  define: __SIZEOF_LONG_LONG__=8
  define: __SIZEOF_SHORT__=2
  define: __SIZEOF_FLOAT__=4
  define: __SIZEOF_DOUBLE__=8
  define: __SIZEOF_LONG_DOUBLE__=16
  define: __SIZEOF_SIZE_T__=8
  define: __CHAR_BIT__=8
  define: __BIGGEST_ALIGNMENT__=16
  define: __ORDER_LITTLE_ENDIAN__=1234
  define: __ORDER_BIG_ENDIAN__=4321
  define: __ORDER_PDP_ENDIAN__=3412
  define: __BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __FLOAT_WORD_ORDER__=__ORDER_LITTLE_ENDIAN__
  define: __SIZEOF_POINTER__=8
  define: __SIZE_TYPE__=long unsigned int
  define: __PTRDIFF_TYPE__=long int
  define: __WCHAR_TYPE__=int
  define: __WINT_TYPE__=unsigned int
  define: __INTMAX_TYPE__=long int
  define: __UINTMAX_TYPE__=long unsigned int
  define: __CHAR16_TYPE__=short unsigned int
  define: __CHAR32_TYPE__=unsigned int
  define: __SIG_ATOMIC_TYPE__=int
  define: __INT8_TYPE__=signed char
  define: __INT16_TYPE__=short int
  define: __INT32_TYPE__=int
  define: __INT64_TYPE__=long int
  define: __UINT8_TYPE__=unsigned char
  define: __UINT16_TYPE__=short unsigned int
  define: __UINT32_TYPE__=unsigned int
  define: __UINT64_TYPE__=long unsigned int
  define: __INT_LEAST8_TYPE__=signed char
  define: __INT_LEAST16_TYPE__=short int
  define: __INT_LEAST32_TYPE__=int
  define: __INT_LEAST64_TYPE__=long int
  define: __UINT_LEAST8_TYPE__=unsigned char
  define: __UINT_LEAST16_TYPE__=short unsigned int
  define: __UINT_LEAST32_TYPE__=unsigned int
  define: __UINT_LEAST64_TYPE__=long unsigned int
  define: __INT_FAST8_TYPE__=signed char
  define: __INT_FAST16_TYPE__=long int
  define: __INT_FAST32_TYPE__=long int
  define: __INT_FAST64_TYPE__=long int
  define: __UINT_FAST8_TYPE__=unsigned char
  define: __UINT_FAST16_TYPE__=long unsigned int
  define: __UINT_FAST32_TYPE__=long unsigned int
  define: __UINT_FAST64_TYPE__=long unsigned int
  define: __INTPTR_TYPE__=long int
  define: __UINTPTR_TYPE__=long unsigned int
  define: __GXX_ABI_VERSION=1013
  define: __SCHAR_MAX__=0x7f
  define: __SHRT_MAX__=0x7fff
  define: __INT_MAX__=0x7fffffff
  define: __LONG_MAX__=0x7fffffffffffffffL
  define: __LONG_LONG_MAX__=0x7fffffffffffffffLL
  define: __WCHAR_MAX__=0x7fffffff
  define: __WCHAR_MIN__=(-__WCHAR_MAX__ - 1)
  define: __WINT_MAX__=0xffffffffU
  define: __WINT_MIN__=0U
  define: __PTRDIFF_MAX__=0x7fffffffffffffffL
  define: __SIZE_MAX__=0xffffffffffffffffUL
  define: __SCHAR_WIDTH__=8
  define: __SHRT_WIDTH__=16
  define: __INT_WIDTH__=32
  define: __LONG_WIDTH__=64
  define: __LONG_LONG_WIDTH__=64
  define: __WCHAR_WIDTH__=32
  define: __WINT_WIDTH__=32
  define: __PTRDIFF_WIDTH__=64
  define: __SIZE_WIDTH__=64
  define: __INTMAX_MAX__=0x7fffffffffffffffL
  define: __INTMAX_C(c)=c ## L
  define: __UINTMAX_MAX__=0xffffffffffffffffUL
  define: __UINTMAX_C(c)=c ## UL
  define: __INTMAX_WIDTH__=64
  define: __SIG_ATOMIC_MAX__=0x7fffffff
  define: __SIG_ATOMIC_MIN__=(-__SIG_ATOMIC_MAX__ - 1)
  define: __SIG_ATOMIC_WIDTH__=32
  define: __INT8_MAX__=0x7f
  define: __INT16_MAX__=0x7fff
  define: __INT32_MAX__=0x7fffffff
  define: __INT64_MAX__=0x7fffffffffffffffL
  define: __UINT8_MAX__=0xff
  define: __UINT16_MAX__=0xffff
  define: __UINT32_MAX__=0xffffffffU
  define: __UINT64_MAX__=0xffffffffffffffffUL
  define: __INT_LEAST8_MAX__=0x7f
  define: __INT8_C(c)=c
  define: __INT_LEAST8_WIDTH__=8
  define: __INT_LEAST16_MAX__=0x7fff
  define: __INT16_C(c)=c
  define: __INT_LEAST16_WIDTH__=16
  define: __INT_LEAST32_MAX__=0x7fffffff
  define: __INT32_C(c)=c
  define: __INT_LEAST32_WIDTH__=32
  define: __INT_LEAST64_MAX__=0x7fffffffffffffffL
  define: __INT64_C(c)=c ## L
  define: __INT_LEAST64_WIDTH__=64
  define: __UINT_LEAST8_MAX__=0xff
  define: __UINT8_C(c)=c
  define: __UINT_LEAST16_MAX__=0xffff
  define: __UINT16_C(c)=c
  define: __UINT_LEAST32_MAX__=0xffffffffU
  define: __UINT32_C(c)=c ## U
  define: __UINT_LEAST64_MAX__=0xffffffffffffffffUL
  define: __UINT64_C(c)=c ## UL
  define: __INT_FAST8_MAX__=0x7f
  define: __INT_FAST8_WIDTH__=8
  define: __INT_FAST16_MAX__=0x7fffffffffffffffL
  define: __INT_FAST16_WIDTH__=64
  define: __INT_FAST32_MAX__=0x7fffffffffffffffL
  define: __INT_FAST32_WIDTH__=64
  define: __INT_FAST64_MAX__=0x7fffffffffffffffL
  define: __INT_FAST64_WIDTH__=64
  define: __UINT_FAST8_MAX__=0xff
  define: __UINT_FAST16_MAX__=0xffffffffffffffffUL
  define: __UINT_FAST32_MAX__=0xffffffffffffffffUL
  define: __UINT_FAST64_MAX__=0xffffffffffffffffUL
  define: __INTPTR_MAX__=0x7fffffffffffffffL
  define: __INTPTR_WIDTH__=64
  define: __UINTPTR_MAX__=0xffffffffffffffffUL
  define: __GCC_IEC_559=2
  define: __GCC_IEC_559_COMPLEX=2
  define: __FLT_EVAL_METHOD__=0
  define: __FLT_EVAL_METHOD_TS_18661_3__=0
  define: __DEC_EVAL_METHOD__=2
  define: __FLT_RADIX__=2
  define: __FLT_MANT_DIG__=24
  define: __FLT_DIG__=6
  define: __FLT_MIN_EXP__=(-125)
  define: __FLT_MIN_10_EXP__=(-37)
  define: __FLT_MAX_EXP__=128
  define: __FLT_MAX_10_EXP__=38
  define: __FLT_DECIMAL_DIG__=9
  define: __FLT_MAX__=3.40282346638528859811704183484516925e+38F
  define: __FLT_MIN__=1.17549435082228750796873653722224568e-38F
  define: __FLT_EPSILON__=1.19209289550781250000000000000000000e-7F
  define: __FLT_DENORM_MIN__=1.40129846432481707092372958328991613e-45F
  define: __FLT_HAS_DENORM__=1
  define: __FLT_HAS_INFINITY__=1
  define: __FLT_HAS_QUIET_NAN__=1
  define: __DBL_MANT_DIG__=53
  define: __DBL_DIG__=15
  define: __DBL_MIN_EXP__=(-1021)
  define: __DBL_MIN_10_EXP__=(-307)
  define: __DBL_MAX_EXP__=1024
  define: __DBL_MAX_10_EXP__=308
  define: __DBL_DECIMAL_DIG__=17
  define: __DBL_MAX__=((double)1.79769313486231570814527423731704357e+308L)
  define: __DBL_MIN__=((double)2.22507385850720138309023271733240406e-308L)
  define: __DBL_EPSILON__=((double)2.22044604925031308084726333618164062e-16L)
  define: __DBL_DENORM_MIN__=((double)4.94065645841246544176568792868221372e-324L)
  define: __DBL_HAS_DENORM__=1
  define: __DBL_HAS_INFINITY__=1
  define: __DBL_HAS_QUIET_NAN__=1
  define: __LDBL_MANT_DIG__=64
  define: __LDBL_DIG__=18
  define: __LDBL_MIN_EXP__=(-16381)
  define: __LDBL_MIN_10_EXP__=(-4931)
  define: __LDBL_MAX_EXP__=16384
  define: __LDBL_MAX_10_EXP__=4932
  define: __DECIMAL_DIG__=21
  define: __LDBL_DECIMAL_DIG__=21
  define: __LDBL_MAX__=1.18973149535723176502126385303097021e+4932L
  define: __LDBL_MIN__=3.36210314311209350626267781732175260e-4932L
  define: __LDBL_EPSILON__=1.08420217248550443400745280086994171e-19L
  define: __LDBL_DENORM_MIN__=3.64519953188247460252840593361941982e-4951L
  define: __LDBL_HAS_DENORM__=1
  define: __LDBL_HAS_INFINITY__=1
  define: __LDBL_HAS_QUIET_NAN__=1
  define: __FLT32_MANT_DIG__=24
  define: __FLT32_DIG__=6
  define: __FLT32_MIN_EXP__=(-125)
  define: __FLT32_MIN_10_EXP__=(-37)
  define: __FLT32_MAX_EXP__=128
  define: __FLT32_MAX_10_EXP__=38
  define: __FLT32_DECIMAL_DIG__=9
  define: __FLT32_MAX__=3.40282346638528859811704183484516925e+38F32
  define: __FLT32_MIN__=1.17549435082228750796873653722224568e-38F32
  define: __FLT32_EPSILON__=1.19209289550781250000000000000000000e-7F32
  define: __FLT32_DENORM_MIN__=1.40129846432481707092372958328991613e-45F32
  define: __FLT32_HAS_DENORM__=1
  define: __FLT32_HAS_INFINITY__=1
  define: __FLT32_HAS_QUIET_NAN__=1
  define: __FLT64_MANT_DIG__=53
  define: __FLT64_DIG__=15
  define: __FLT64_MIN_EXP__=(-1021)
  define: __FLT64_MIN_10_EXP__=(-307)
  define: __FLT64_MAX_EXP__=1024
  define: __FLT64_MAX_10_EXP__=308
  define: __FLT64_DECIMAL_DIG__=17
  define: __FLT64_MAX__=1.79769313486231570814527423731704357e+308F64
  define: __FLT64_MIN__=2.22507385850720138309023271733240406e-308F64
  define: __FLT64_EPSILON__=2.22044604925031308084726333618164062e-16F64
  define: __FLT64_DENORM_MIN__=4.94065645841246544176568792868221372e-324F64
  define: __FLT64_HAS_DENORM__=1
  define: __FLT64_HAS_INFINITY__=1
  define: __FLT64_HAS_QUIET_NAN__=1
  define: __FLT128_MANT_DIG__=113
  define: __FLT128_DIG__=33
  define: __FLT128_MIN_EXP__=(-16381)
  define: __FLT128_MIN_10_EXP__=(-4931)
  define: __FLT128_MAX_EXP__=16384
  define: __FLT128_MAX_10_EXP__=4932
  define: __FLT128_DECIMAL_DIG__=36
  define: __FLT128_MAX__=1.18973149535723176508575932662800702e+4932F128
  define: __FLT128_MIN__=3.36210314311209350626267781732175260e-4932F128
  define: __FLT128_EPSILON__=1.92592994438723585305597794258492732e-34F128
  define: __FLT128_DENORM_MIN__=6.47517511943802511092443895822764655e-4966F128
  define: __FLT128_HAS_DENORM__=1
  define: __FLT128_HAS_INFINITY__=1
  define: __FLT128_HAS_QUIET_NAN__=1
  define: __FLT32X_MANT_DIG__=53
  define: __FLT32X_DIG__=15
  define: __FLT32X_MIN_EXP__=(-1021)
  define: __FLT32X_MIN_10_EXP__=(-307)
  define: __FLT32X_MAX_EXP__=1024
  define: __FLT32X_MAX_10_EXP__=308
  define: __FLT32X_DECIMAL_DIG__=17
  define: __FLT32X_MAX__=1.79769313486231570814527423731704357e+308F32x
  define: __FLT32X_MIN__=2.22507385850720138309023271733240406e-308F32x
  define: __FLT32X_EPSILON__=2.22044604925031308084726333618164062e-16F32x
  define: __FLT32X_DENORM_MIN__=4.94065645841246544176568792868221372e-324F32x
  define: __FLT32X_HAS_DENORM__=1
  define: __FLT32X_HAS_INFINITY__=1
  define: __FLT32X_HAS_QUIET_NAN__=1
  define: __FLT64X_MANT_DIG__=64
  define: __FLT64X_DIG__=18
  define: __FLT64X_MIN_EXP__=(-16381)
  define: __FLT64X_MIN_10_EXP__=(-4931)
  define: __FLT64X_MAX_EXP__=16384
  define: __FLT64X_MAX_10_EXP__=4932
  define: __FLT64X_DECIMAL_DIG__=21
  define: __FLT64X_MAX__=1.18973149535723176502126385303097021e+4932F64x
  define: __FLT64X_MIN__=3.36210314311209350626267781732175260e-4932F64x
  define: __FLT64X_EPSILON__=1.08420217248550443400745280086994171e-19F64x
  define: __FLT64X_DENORM_MIN__=3.64519953188247460252840593361941982e-4951F64x
  define: __FLT64X_HAS_DENORM__=1
  define: __FLT64X_HAS_INFINITY__=1
  define: __FLT64X_HAS_QUIET_NAN__=1
  define: __DEC32_MANT_DIG__=7
  define: __DEC32_MIN_EXP__=(-94)
  define: __DEC32_MAX_EXP__=97
  define: __DEC32_MIN__=1E-95DF
  define: __DEC32_MAX__=9.999999E96DF
  define: __DEC32_EPSILON__=1E-6DF
  define: __DEC32_SUBNORMAL_MIN__=0.000001E-95DF
  define: __DEC64_MANT_DIG__=16
  define: __DEC64_MIN_EXP__=(-382)
  define: __DEC64_MAX_EXP__=385
  define: __DEC64_MIN__=1E-383DD
  define: __DEC64_MAX__=9.999999999999999E384DD
  define: __DEC64_EPSILON__=1E-15DD
  define: __DEC64_SUBNORMAL_MIN__=0.000000000000001E-383DD
  define: __DEC128_MANT_DIG__=34
  define: __DEC128_MIN_EXP__=(-6142)
  define: __DEC128_MAX_EXP__=6145
  define: __DEC128_MIN__=1E-6143DL
  define: __DEC128_MAX__=9.999999999999999999999999999999999E6144DL
  define: __DEC128_EPSILON__=1E-33DL
  define: __DEC128_SUBNORMAL_MIN__=0.000000000000000000000000000000001E-6143DL
  define: __REGISTER_PREFIX__=
  define: __USER_LABEL_PREFIX__=
  define: __GNUC_STDC_INLINE__=1
  define: __STRICT_ANSI__=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1
  define: __GCC_HAVE_SYNC_COMPARE_AND_SWAP_16=1
  define: __GCC_ATOMIC_BOOL_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR16_T_LOCK_FREE=2
  define: __GCC_ATOMIC_CHAR32_T_LOCK_FREE=2
  define: __GCC_ATOMIC_WCHAR_T_LOCK_FREE=2
  define: __GCC_ATOMIC_SHORT_LOCK_FREE=2
  define: __GCC_ATOMIC_INT_LOCK_FREE=2
  define: __GCC_ATOMIC_LONG_LOCK_FREE=2
  define: __GCC_ATOMIC_LLONG_LOCK_FREE=2
  define: __GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1
  define: __GCC_ATOMIC_POINTER_LOCK_FREE=2
  define: __HAVE_SPECULATION_SAFE_VALUE=1
  define: __GCC_HAVE_DWARF2_CFI_ASM=1
  define: __PRAGMA_REDEFINE_EXTNAME=1
  define: __SIZEOF_INT128__=16
  define: __SIZEOF_WCHAR_T__=4
  define: __SIZEOF_WINT_T__=4
  define: __SIZEOF_PTRDIFF_T__=8
  define: __amd64=1
  define: __amd64__=1
  define: __x86_64=1
  define: __x86_64__=1
  define: __SIZEOF_FLOAT80__=16
  define: __SIZEOF_FLOAT128__=16
  define: __ATOMIC_HLE_ACQUIRE=65536
  define: __ATOMIC_HLE_RELEASE=131072
  define: __GCC_ASM_FLAG_OUTPUTS__=1
  define: __corei7=1
  define: __corei7__=1
  define: __nehalem=1
  define: __nehalem__=1
  define: __tune_core_avx2__=1
  define: __tune_haswell__=1
  define: __code_model_small__=1
  define: __MMX__=1
  define: __SSE__=1
  define: __SSE2__=1
  define: __SSE3__=1
  define: __SSSE3__=1
  define: __SSE4_1__=1
  define: __SSE4_2__=1
  define: __PCLMUL__=1
  define: __POPCNT__=1
  define: __FXSR__=1
  define: __SSE_MATH__=1
  define: __SSE2_MATH__=1
  define: __SEG_FS=1
  define: __SEG_GS=1
  define: __gnu_linux__=1
  define: __linux=1
  define: __linux__=1
  define: __unix=1
  define: __unix__=1
  define: __ELF__=1
  define: __DECIMAL_BID_FORMAT__=1
  define: _STDC_PREDEF_H=1
  define: __STDC_IEC_559__=1
  define: __STDC_IEC_559_COMPLEX__=1
  define: __STDC_ISO_10646__=201706L
  other: --gcc
  other: --gnu_version=90201
  stdver: c11
  intelliSenseMode: gcc-x64
Queueing IntelliSense update for files in translation unit of: /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/src/ord.c
Error squiggle count: 0
Update IntelliSense time (sec): 0.885
idle loop: reparsing the active document
Checking for syntax errors: file:///run/media/stefano/Windows%2010/Users/stefa/Documenti/universita/tirocinio/ba_horn/include/ord.h
Queueing IntelliSense update for files in translation unit of: /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/src/ord.c
Error squiggle count: 0
Update IntelliSense time (sec): 0.263
textDocument/didOpen
Checking for syntax errors: file:///run/media/stefano/Windows%2010/Users/stefa/Documenti/universita/tirocinio/ba_horn/src/ord.c
Queueing IntelliSense update for files in translation unit of: /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/src/ord.c
cpptools/getCodeActions: 5
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: 6
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/getCodeActions: 7
Error squiggle count: 0
Error squiggle count: 0
Update IntelliSense time (sec): 0.295
idle loop: reparsing the active document
Checking for syntax errors: file:///run/media/stefano/Windows%2010/Users/stefa/Documenti/universita/tirocinio/ba_horn/src/ord.c
Queueing IntelliSense update for files in translation unit of: /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/src/ord.c
Error squiggle count: 0
Error squiggle count: 0
Update IntelliSense time (sec): 0.268

**Comment by SPAstef** [comment]
-------- Diagnostics - 7/11/2019, 21:37:20
Version: 0.26.1
Current Configuration:
{
    "name": "Linux",
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "compilerArgs": [],
    "cStandard": "c11",
    "cppStandard": "c++20",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/src/ord.c ]:
    /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/include/ord.h
    /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/src/ord.c
Translation Unit Configurations:
[ /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/src/ord.c ]:
    Process ID: 2765
    Memory Usage: 15 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib64/gcc/x86_64-generic-linux/9/include
        /usr/local/include
        /usr/lib64/gcc/x86_64-generic-linux/9/include-fixed
        /usr/include
        /run/media/stefano/Windows 10/Users/stefa/Documents/universita/tirocinio/ba_horn/include
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=90201
Total Memory Usage: 15 MB

**Comment by Colengms** [comment]
It looks like the extension is getting initialized, successfully creating a TU for the file (ord.c), and successfully processing IntelliSense.

Could you provide a screen snapshot?  Perhaps the issue has something to do with the font and UI issues you mentioned.

**Comment by SPAstef** [comment]
@Colengms you mean a screenshot? I am away from the PC now, but there's nothing interesting to see. Normal syntax highlighting works fine, and "normal" function snippets are ok. Only problem is that highlighting is not semantic and "special" function aren't suggested even after setting the right "#define". Now, this last problem might be related to the fact that the function search is (I guess) probably done alphabetically, so e.g. /usr/include/bits/stdio.h is preferred over /usr/include/stdio.h (fun fact, first line in that header says "never include this header"). I've been somewhat able to partially work around this by using the files.exclude setting, but I'm not 100% sure whether the function-not-found bug is related to colorization or header search, even if when right clicking <stdio.h> the correct one pops out.

**Comment by SPAstef** [comment]
Sorry if I'm making a bit of a mess here with this bug report, I know it started as a color issue and it starts getting a bit convoluted. So let's just stick to the colors now. I'm almost sure both problems are related to the language server executable but I'm not the expert here so it's just a feeling.

**Comment by Colengms** [comment]
Semantic colorization, inactive regions, and squiggles, are all applied by the same IntelliSense pass.  Your logs show that this IntelliSense pass is successful.  There would seem to be some information about your repro that we're missing that might explain what is happening.

If you specify an inactive block with an else, is one side dimmed?

```
#if 0
// Is this dimmed?
#else
// Is this dimmed?   Or, are neither dimmed?
#endif
```

If one side is dimmed, that would seem to point to a configuration issue, and your code may be compiling with different defines than expected.  If neither side is dimmed, that would seem to point to semantic colorization not being applied.  Since the IntelliSense pass was successful, I'm not sure why they would not show.

Are you running this on Linux directly, or using VS Code's Remoting feature?  Enhanced colorization does not currently work via remoting, as we don't have access to the current Theme's files to look up colors.

Otherwise, I'm a bit suspicious of the UI issues you described after installing VS Code.

If you add something invalid, is a squiggle shown?  Depending on whether squiggles are shown when expected, that might provide a clue about what's happening.

Screenshots of what you're seeing may be helpful, as we may be able to identify what's going on based on details that might not be obvious.  For instance, depending on whether Tag Parser or IntelliSense is used to provide auto-complete, slightly different UI is shown.

**Comment by SPAstef** [comment]
VS Code is installed, executed and displayed all on the same OS, it's not on WSL/VM/container. Installed via RPM, on installation I had to specify --nodeps, otherwise some errors kicked in, but that's the normal way to install RPM on Clear Linux, otherwise none would install. I did not try `#if 0`, I did try, actually I have:
`#define MACRO`
`#ifndef MACRO`
`...`
`#endif`

But the portion is not dimmed. I don't remember the squiggles now but I'm pretty sure (90%) they did show up as I was typing a partial function. Tomorrow I'll get you the screenshots, thanks for your help! 😄

**Comment by SPAstef** [comment]
Ok I have an update to make:
1) Colorization works correctly and nicely if the code resides in an absolute path (e.g. /home/username/project).
2) Semantic colorization stops working if I access the project through a soft link (e.g. /home/username/project is a link to /run/media/windows_drive/project)
3) Wrong header inclusion is wrong either way (/usr/include/bits instead of /usr/include), this means some functions don't get suggested.

Here are a couple screenshots of the same thing: first image is when accessing by direct location, second one when accessing by soft link.
![Schermata del 2019-11-08 10-43-57](https://user-images.githubusercontent.com/9153046/68466507-d555e880-0214-11ea-9da7-3b59bd2743cc.png)

**Comment by Colengms** [comment]
Hi @SPAstef .  I was able to repro an issue with symbolic links, with a minimal example - just a source file, and a soft link to another local directory.  I created https://github.com/microsoft/vscode-cpptools/issues/4573 to track that issue.

Wrong header inclusion would seem to be a separate issue.  Can you provide a simplified example I might use to repro locally?

**Comment by SPAstef** [comment]
Well, I have a stdio.h header in the /usr/include/bits directory, and one in the /usr/include.
You can just try making an "Hello, world!" C program with stdio to check that... Also try this:
```C
#include <stdio.h>
int main(void)
{
    int fd = fileno(stdin);

    return 0;
}
```

and check if the fileno function is available (you might have to add a `#define SOME_POSIX_MACRO` according to your system, check `man fileno`.

**Comment by SPAstef** [comment]
Also, about the soft link problem: When I start the debugger, and I allready have the file opened via the soft link, the debugger opens it up again in the absolute path. It's like if they are somehow seen as two different folders, even if when I make a change in one "version", obivously the other one gets immediatly updated too. I think I might have had some issues with breakpoints actually, but now they seem to be ok.

**Comment by Colengms** [comment]
@SPAstef , Your system include paths look correct.  They've are retrieved from the compiler, and appear to be in the correct order.  As long as I define "_POSIX_C_SOURCE" (Ubuntu 18.04, gcc 7.4), I see the proper prototype and doc comment when hovering over fileno.  (I've also tried with gcc-9)

Are you certain you are using the right #define to enable fileno?  :)  Can you confirm against other functions expected in stdio.h, that don't require a define to enable?  Are there more indications that wrong headers are being used that we might look into?

**Comment by SPAstef** [comment]
@Colengms the define to use in my system is _USE_POSIX. This is what happens when peeking the definition of a "normal" function. fileno() just points back to the same file where it's being used.
![Schermata del 2019-11-11 14-45-54](https://user-images.githubusercontent.com/9153046/68591892-055def80-0492-11ea-9f09-eae1a56d15e5.png)

**Comment by Colengms** [comment]
@SPAstef, I do not doubt that the function is not being defined as expected.

Incorrect headers or incorrect defines are generally configuration issues.  The reason I asked about other headers that are not being included as expected, was to rule out the possibility that this specific header is actually being included properly but parsed differently than expected due to additional needed defines, etc..  And that additional evidence might provide some additional clues as to what might be misconfigured.

**Comment by SPAstef** [comment]
Just tried again with a new from-scratch source file, and the function (along usleep() and nanosleep(), using different macros) where actually correctly found. Most likely it's an inclusion order error on my side, I have several sources and headers, have to double-check the inclusion tree. Sorry for the bother :P

**Comment by Colengms** [comment]
No bother.  :)   Glad to help.  Since we have https://github.com/microsoft/vscode-cpptools/issues/4573 tracking the symbolic link issue, and the remaining issues in this thread are resolved(?), I'll close this one.  Feel free to re-open if there is something we missed.
