### ISSUE TITLE
Undefined identifiers using Lua 5.3

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4576]
I also see the problem originally reported, embedding Lua 5.3 into my programs written in C++.  All macros defined in the Lua headers have red squigglies and the hover tooltips say they're both defined and undefined:

![image](https://user-images.githubusercontent.com/41497796/68494269-fca3ba00-0202-11ea-8f75-23e64e30a0f6.png)

The problem doesn't happen in Visual Studio, only VSCode, even though same project structure, include paths, and both built from same CMake files.

If more information is needed, I'd gladly construct a MCVE or answer any questions the devs have.  The problem is one of only a few things that I've seen wrong with the vscode-cpptools for a long time, so it would be awesome if it could be fixed.

_Originally posted by @rhymu8354 in https://github.com/microsoft/vscode-cpptools/issues/1485#issuecomment-551898257_

**Comment by sean-mcmanus** [comment]
@rhymu8354 Can you use the C/C++: Log Diagnostics command with that source file active? Do you see any incorrect includes or defines in the output? Our IntelliSense engine is not seeing lua_newtable definition (the hover info is coming from a different system).

What is a "MCVE"?

**Comment by rhymu8354** [comment]
```
-------- Diagnostics - 11/9/2019, 9:25:25 AM
Version: 0.26.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.17763.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compileCommands": "${workspaceFolder}/build-vscode/compile_commands.json",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ E:\Projects\MoonUnit\src\Runner.cpp ]:
    E:\PROJECTS\MOONUNIT\SRC\RUNNER.CPP
Translation Unit Configurations:
[ E:\Projects\MoonUnit\src\Runner.cpp ]:
    Process ID: 20268
    Memory Usage: 58 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
    Includes:
        E:\PROJECTS\MOONUNIT\JSON\INCLUDE
        E:\PROJECTS\MOONUNIT\BASE64\INCLUDE
        E:\PROJECTS\MOONUNIT\SYSTEMABSTRACTIONS\INCLUDE
        E:\PROJECTS\MOONUNIT\UTF8\INCLUDE
        E:\PROJECTS\MOONUNIT\LUA\SRC
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\VC\TOOLS\MSVC\14.16.27023\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\VC\TOOLS\MSVC\14.16.27023\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: msvc-x64
Total Memory Usage: 58 MB
```

I don't think any of the includes or defines are wrong.  `Runner.cpp` should be finding `lua.h` and other Lua includes inside of `E:\PROJECTS\MOONUNIT\LUA\SRC` which is in the include path.

Source for `Runner.cpp` is here in github:  https://github.com/rhymu8354/MoonUnit/blob/master/src/Runner.cpp
I also have the Lua source here:  https://github.com/rhymu8354/Lua

A MCVE is [Minimum Complete Verifiable Example](https://stackoverflow.com/help/minimal-reproducible-example)

Also, version info:
```
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Extensions:
vscode-cpptools: 0.26.1
CMake Tools: 1.2.1

CMake is version 3.12.1
```

**Comment by Colengms** [comment]
Hi @rhymu8354 .  Sorry for the delay.  Are you still seeing this issue?  If so, could you provide the configuration from your `c_cpp_properties.json` ?  If you are able to provide a MCVE we could investigate, that would be ideal.

Though, it's odd that you are seeing an indication that lua_newtable is undefined, when we clearly know it's defined as we provided the value it expands to.  Is it possible you have multiple extensions enabled that are attempting to provide language services for the same file?  It looks like VS Code will now also display which extension that message came from.

**Comment by Colengms** [comment]
I think this may be related to https://github.com/microsoft/vscode-cpptools/issues/5182 , which is a case of squiggles on macros that are indeed defined, and results in the macro being both successfully resolved and 'undefined' on hover.  I've been having trouble coming up with a Windows repro for https://github.com/microsoft/vscode-cpptools/issues/5182.  @rhymu8354 , if you have a Windows MCVE, it might help us escalate the issue to VS (IntelliSense is shared with VS)

**Comment by rhymu8354** [comment]
Hi @Colengms , I don't have a `c_cpp_properties.json` file.  It might be because I'm using CMake to provide IntelliSense configuration (through `"C_Cpp.default.configurationProvider": "vector-of-bool.cmake-tools"` in `settings.json`)?

[Edit: Isn't the equivalent of `c_cpp_properties.json` to be found in the [log above](https://github.com/microsoft/vscode-cpptools/issues/4576#issuecomment-552120257) ?]

**Comment by rhymu8354** [comment]
With the latest version of cpptools, it does look like the extension the message came from is displayed:
![image](https://user-images.githubusercontent.com/41497796/93628715-df4f8880-f99b-11ea-964d-6f45b4993ec4.png)

**Comment by rhymu8354** [comment]
I've been so far unable to reduce a project with this issue down to an MCVE.  It doesn't appear in small projects like [this one](https://github.com/rhymu8354/LuaCppTutorial), only larger ones.  I'll continue looking for whatever triggers it to start happening.

**Comment by sean-mcmanus** [comment]
@rhymu8354 Is this still an issue?
