### ISSUE TITLE
clang-format invalid sometimes

### ISSUE THREAD

**Issue by KingaChou** [microsoft/vscode-cpptools#4577]
Issue Type: <b>Bug</b>

The clang-format is normal at the outset. I set the configuration that format on save the file.
But suddenly it is invalid and I have no idea. Even if I use the shortcut key.
I can see the progress of  ms-vscode.cpptools-0.26.1 is running.
After I reopen the workspace, the clang-format is normal again.

Extension version: 0.26.1
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by KingaChou** [comment]
![image](https://user-images.githubusercontent.com/4949336/68529621-8060c200-033b-11ea-80ca-85f7f95083a2.png)
![image](https://user-images.githubusercontent.com/4949336/68529943-bfdcdd80-033e-11ea-8d33-457e551b0cad.png)

**Comment by sean-mcmanus** [comment]
What do you mean by "it is invalid"? What symptom or error is occurring with formatting? Are you using a multi-root workspace?

**Comment by KingaChou** [comment]
Thank you for your reply.
Just like what the picture 2 show, when I save the 'test.cpp', it doesn't do the clang-format, which the space and tab is still exist.
After I close the workspace and reopen it, I save the 'test.cpp' again, it can do clang-format is normally.
The problem and ouput dialog of the terminal also show nothing wrong.
I guess if something file not ok affect it, such as wrong grammar.

The picture 1 is my folder setting file.
The picture 2 is the clang-format doesn't work.
The picture 3 is the clang-format works ok after I close and reopen my workspace.

![image](https://user-images.githubusercontent.com/4949336/68727458-72db5e80-05ff-11ea-80c2-a822f1a95050.png)
![image](https://user-images.githubusercontent.com/4949336/68727117-7cb09200-05fe-11ea-818d-5a9583ec160b.png)
![image](https://user-images.githubusercontent.com/4949336/68727841-80ddaf00-0600-11ea-889d-937e4a67f8df.png)

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please download the latest version of the extension and see if issue has been resolved. If issue persists, please re-open for further investigation and with any updated information.
