### ISSUE TITLE
Parameter hints does not support macros

### ISSUE THREAD

**Issue by moojek** [microsoft/vscode-cpptools#4578]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Manjaro Linux, kernel: 5.0.1-MANJARO
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them): Bracket Pair Colorizer, Discord Presence, HTML Preview, LaTeX Workshop, Material Icon Theme, Noctis, Power Mode, Todo Tree, vscode-pdf
- A clear and concise description of what the bug is: if you have defined macros that fills two parameters, parameter hint still highlights parameter already filled by macro

**To Reproduce**

1. Define a macro that defines two things such as #define RANGE(c) (c).begin(), (c).end()
2. Use it in a function that beside those two arguments needs third one such as std::find
3. Open parameter hints

**Expected behavior**

I would expect that parameter hints would recognize that macro fills two parameters and highlights the third parameter.

**Screenshots**
![image](https://user-images.githubusercontent.com/42188458/68536721-a6945b00-0357-11ea-821b-db05ff643bde.png)
here RANGE(graph) already fills first two parameters(__first and __last) so the last (__pred) should be highlighted (with bold).

**Additional context**

**Comment by sean-mcmanus** [comment]
The bug repros in VS so I've reported it at https://developercommunity.visualstudio.com/content/problem/815657/cc-intellisense-parameter-hints-highlights-the-wro.html .

**Comment by moojek** [comment]
Thank you

**Comment by bobbrow** [comment]
The issue reported to Visual Studio was closed as "lower priority." Unfortunately, this means that a fix is not likely to make it to VS Code either.
