### ISSUE TITLE
New F4 keybinding conflict with vscode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-cpptools#458]
Hi, just a heads up that vscode 1.9 will have F4 bound to navigate search results by default, and the C++ extension binds it to 'Switch Header/Source'. We picked F4 because it's what people expect coming from Sublime.

Since the extension binding would override that for all files, maybe you might consider changing that binding - it looks like you already have alt+O as an alternate.

Also adding a note to the release notes for this. Reference issue - https://github.com/Microsoft/vscode/issues/18679

**Comment by sean-mcmanus** [comment]
Sure, we can change that.

**Comment by sean-mcmanus** [comment]
We've made the change. It should be in our next release (0.10.1, February).

**Comment by roblourens** [comment]
Thanks!
