### ISSUE TITLE
Debugger dosn't show variables from std::map when that variable type has configured in natvis

### ISSUE THREAD

**Issue by ykuchin** [microsoft/vscode-cpptools#4580]
VSCode Version:
1.40.0
86405ea
x64

OS Version:
Linux portable 5.0.0-32-generic #3418.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
GNU gdb (Ubuntu 8.2-0ubuntu118.04) 8.2

Steps to Reproduce:

1. build and run attached project
2. stop at nb.cpp:30
3. look at variable 'm' and 'v' in 'locals'
You can see natvis-configured variables in vector, but you can't see variables in map.

Also you can enable debug pretty printing from gdb in launch.json, by adding '-x ${workspaceFolder}/nb.gdb' to miDebuggerArgs. Pretty printers from gdb always shows variables from vector and map.
[natvis_bug.zip](https://github.com/microsoft/vscode-cpptools/files/3828042/natvis_bug.zip)

**Comment by rokups** [comment]
Can confirm. No amount of fiddling with config helped when trying to enable natvis.

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-15T22:58:14.270Z
Electron: 6.1.1
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.12-arch1-1

**Comment by ykuchin** [comment]
I have found workaround: all works fine if using pointer to class as template parameter.

**Comment by ykuchin** [comment]
Here is patch for https://sourceware.org/gdb/wiki/STLSupport to enable natvis for non-ptr values 
[patch_map_and_vector.txt](https://github.com/microsoft/vscode-cpptools/files/4496737/patch_map_and_vector.txt)
