### ISSUE TITLE
Add support for 'ms-vscode.cmake-tools' configurationProvider id

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4586]
@Victsz We didn't change the configurationProvider to `ms-vscode.cmake-tools` yet because we need to make a change to cpptools to support it first.  We plan to support both ids during this transition.  If you change it back to `vector-of-bool.cmake-tools` it should work again.

_Originally posted by @bobbrow in https://github.com/microsoft/vscode-cpptools/issues/3731#issuecomment-552554283_

**Comment by michelleangela** [comment]
Support added in version 0.26.2-insiders, available at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders.
