### ISSUE TITLE
Allow formatting the current line / statement

### ISSUE THREAD

**Issue by r4nt** [microsoft/vscode-cpptools#459]
Not sure if this should better be a VS Code bug, let me know what to do.
clang-format works specifically well when formatting code as-you-go. To some degree, the format-as-you-type already does that, but not enough (for example, it won't format when I enter an opening brace, so I'll still need to manually format my function declarations).
Thus, it would be great if ctrl-k ctrl-f worked without an active selection, formatting at the cursor.

**Comment by sean-mcmanus** [comment]
We do format the current line when you enable onType formatting, but we're limited to when the line ends in ";". We may be able to add more onType formatting for { later. If you want a Format Line option added to the right-click menu, then VS Code would need to add that. Shift+Up Ctrl+K Ctrl+F may be a workaround for now (i.e. select the previous line and format selection).

**Comment by r4nt** [comment]
shift-up does slightly too much; shift-left ctrl-k ctrl-f works pretty much the same as I want for now :)

**Comment by r4nt** [comment]
Any reason for the wontfix?

**Comment by bobbrow** [comment]
We don't think we'll get to this any time soon given the number of higher priority backlog items and issues we have open and the small size of our team.  This feature request didn't have any +1's so we're just trying to be realistic and transparent with you that there is a very good chance we'll never get to it.

**Comment by sean-mcmanus** [comment]
I'm not 100% sure what exactly the feature request is. You can try asking vscode to implement it.
