### ISSUE TITLE
Attach not working

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode-cpptools#4592]
Type: Debugger
- OS and Version: Windows 10 (remote debugging on Ubuntu 18)
- VS Code Version: 1.40.0
- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them): I have other extensions installed, but can't disable them all because some are needed for Remote Development
- Attach (to debug) was working, but now does not work

I'm relatively new to MS Code.  I'm using a Windows 10 machine to do Remote Development on a Ubuntu machine.  I successfully setup and debugged by attaching to my running app, using Ubuntu 16 several months ago.  When I tried about a month later (MS Code had probably updated in the meantime), the debugger did not Attach (i.e., using the same config that had previously worked, as far as I know).  Since then, I have updated the Ubuntu machine to Ubuntu 18, but using the same configuration, it still does not Attach.

When it was successful, I clicked the green Play arrow on the Deubg pane, next to my configured Debug name, I picked the running process from the running process list, and saw text (debug command?) appear in my Terminal window, and eventually saw a debug toolbar (with Step, Step Into, etc., buttons).  Now, I click the green Play button, I see the running process list, select the process I want to debug (the same one that used to work), but I don't see anything happen after that -- no text appears in the Terminal window, not Notifications appear in the Code Notifications section, etc.

Here is my launch.json (I've added "engineLogging", "trace", "traceResponse", and "externalConsole" to try to debug the issue -- all of which show yellow squiggles in the editor -- but it was also not working without these):
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Gpudb Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/opt/gpudb/core/bin/gpudb_cluster_cuda",
            "MIMode": "gdb",
            "engineLogging": true,
            "trace": "true",
            "traceResponse": "true",
            "externalConsole": "true",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "processId":"${command:pickProcess}"
        }
    ]
}

I'm not sure where to look for the trace output, but I did see (only) this line appear in my Output window, under "Log (Windows)":
[2019-11-12 14:00:19.749] [renderer1] [error] timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/Andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798:1003)
    at file:///C:/Users/Andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798:434
    at async t.RawDebugSession.shutdown (file:///C:/Users/Andy/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2796:536)

Everything else about MS Code seems to be working fine for this Remote Development environment (including Editing, Terminal and GIT).  Also, if I use the Ubuntu machine directly, I am able to debug the (same) process by attaching with the QtCreator debugger (which is what I did before Code, and was hoping to get away from).

Please let me know what other info I can provide, etc., and thank you in advance for any help.

**Comment by andyj513** [comment]
I've disabled all Extensions except "Remote - SSH", "Remote Development" and (on the remote machine) "C/C++".  Also, it looks like VS Code updated to 1.40.1.  Remote Debugging (with Attach) still does not work, but now has slightly different behavior.  Now, after I select the process to attach to, the debugging toolbar does appear.  But there is a moving/scrolling line under the Debug header which seems to keep going for over 10 minutes (which I didn't notice before).  But my breakpoints do not seem to be hit, and clicking the Pause button on the Debugging toolbar does not seem to have an effect (and I never see text appear in the Terminal Window, but I'm not sure if that is necessary).  The following appeared in the Output: Log (Window):

[2019-11-14 10:52:55.338] [renderer1] [error] xterm: Xt error: Can't open display: : Error: xterm: Xt error: Can't open display: 
	at ChildProcess.<anonymous> (/home/gpudb/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:424:258)
	at ChildProcess.emit (events.js:200:13)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[2019-11-14 10:54:53.042] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)

**Comment by pieandcakes** [comment]
@andyj513 It looks like you are using VS Code's `Remote-SSH` extension in conjunction with our extension. Please add the [logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_logging-for-mi-debuggers) block to your `launch.json` and try again. The logging output will display in your `debugConsole` and will help us isolate what is happening.

**Comment by pieandcakes** [comment]
Also, which version did you have that this was working on?

**Comment by andyj513** [comment]
Unfortunately, I don't know the answer to your question, but I think it is moot, as I think I found the issue.

Summary: I had added "externalConsole": "true" to my launch.json at some point (because I wanted to avoid the debugging taking over my console).  I saw to do this on https://code.visualstudio.com/docs/cpp/launch-json-reference.  But it looks like having this line is causing my problem, and when I comment it out, things work as expected (I've tried it both way a few times now).

FWIW, when I try to debug with the logging entries (which I did to try to get you more info), I don't see any output in DEBUG CONSOLE (thank you @pieandcakes for the link, which helped me figure out that I had the logging statements at the wrong level, and when I fixed that, noticed that the only line getting yellow squiggles was this line -- which I had mentioned above).

So, I'm happy.  But it looks like A) The documentation should be updated, and B) There is a bug that when this invalid entry (I didn't try others) is in the launch.json that nothing is launched, and no error is displayed or notified to help the user figure out what is wrong.

Thank you for your help.

**Comment by pieandcakes** [comment]
@andyj513 Thank you for your reply. For the external console = true, can you check your VS Code settings to see what you have the terminal settings set to? It looks like it has a problem with your default setting for that. If it is set correctly, let me know as that is a VS Code bug. [This](https://github.com/microsoft/vscode-cpptools/issues/2998#issuecomment-459214989) comment should help you find the setting. If launching the external console was failing, I can see how it would mess up the entire debug session.
