### ISSUE TITLE
CTest Status Bar Formatting

### ISSUE THREAD

**Issue by dstodev** [microsoft/vscode-cpptools#4594]
Type: General

Formatting of the text for CTest in the status bar appears malformed.

**Describe the bug**
- OS and Version: Windows 10 -- Version 10.0.19013 Build 19013
- VS Code Version: 1.40.0
- C/C++ Extension Version: 0.26.2-insiders
- Other extensions you installed (and if the issue persists after disabling them): Issue persists when _only_ cmake-tools is enabled (including disabling the C/C++ extension)
- A clear and concise description of what the bug is.
With CTest enabled, the button on the status bar has apparently malformed text.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. Enable CTest via `include(CTest)`
2. Build simple program
3. Notice CTest button in the status bar appears malformed

**Expected behavior**
CTest button has text like "X tests passing"

**Screenshots**
![image](https://user-images.githubusercontent.com/31356674/68732793-89df6980-0589-11ea-9419-1255865c32b8.png)

**Additional context**
Very simple repository that demonstrates this bug is here: https://github.com/dstodev/cmake-tools-ctest-bug

**Comment by michelleangela** [comment]
@dstodev, this seems like an issue with the cmake-tools extension and not the C/C++ extension if the issue still persists when C/C++ extension is disabled. Please report the issue at the [cmake-tools repository](github.com/microsoft/vscode-cmake-tools/issues).

**Comment by dstodev** [comment]
Oops, my mistake--I thought that's where I posted this issue, but I read the repo names too quickly and saw microsoft/vscode-cpptools as microsoft/vscode-cmake-tools. I'll post this issue there instead.
