### ISSUE TITLE
Remote development

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#4596]
- VS Code Version: 1.40
- Remote Development: 0.17.0

maybe this question is not related with cpptools extension. But I think you maybe encounter it and know how to solve it.

Currently I use remote development to develop extension which can run on linux. My extension source code is on the linux machine and on windows I use remote development to open source code and start to debug. But extension always can't be actived on debug mode.

I wonder how you solve this remote development issue? I think you maybe encounter this issue when you develop cpptools linux version.

Thanks a lot and look forward to your reply.

**Comment by sean-mcmanus** [comment]
Yeah, we have hit the same issue and haven't found a solution. My workaround was to install a "debug" vsix on the remote machine that had more logging.

I found the issue you posted at https://github.com/microsoft/vscode-remote-release/issues/1830 .
