### ISSUE TITLE
Go to Definition opens a different copy of a file.

### ISSUE THREAD

**Issue by dvirsky** [microsoft/vscode-cpptools#46]
This happens on Linux with version 0.5.0 and vscode 1.0 and 1.1.0.

If I have a C file open, and it contains a function, and I click "go to definition" of that function, no matter from what open file (even from the same file) - this will cause the C file containing the function to be re-opened and appear twice in the active files list. The second file appears with the file's absolute path next to it. 
This is confusing and causes clutter. I'm not sure if it's a bug in the extension or of vscode itself.

Attached - example of how it looks. 
![screenshot from 2016-05-12 18-49-33](https://cloud.githubusercontent.com/assets/503226/15235720/82cdf91c-18c6-11e6-825b-cf7504d36735.png)

**Comment by dbaeumer** [comment]
@sridmad how does the file URI look like you are returning in this case. This should work and there should be no need for you to do anything special besides returning a propery file url. Something like file:///home/.... What wonders me is that the file path at the end is ///home which indicates that either we do something wrong in the language client or vscode extension host API or the provided file URI is incorrect.

I quickly tested this under Windows and it works. Need to setup Linux first to try there as well.

**Comment by sridmad** [comment]
Let me take a look at the experience on Windows and also the paths we return

**Comment by dvirsky** [comment]
If you want me to help with debugging on Linux, let me know. BTW I've verified that it happens to other people as well.

**Comment by dbaeumer** [comment]
@sridmad just to clarify: I tried a test bed under Windows, not the C++ extension.

**Comment by dvirsky** [comment]
FWIW it still happens on VSCode 1.2.0

**Comment by jgoshi** [comment]
Does this still happen with the latest stuff (VSCode 1.4, cpptools 0.8.1)?

**Comment by jgoshi** [comment]
I was able to repro this and the fix will appear in the next release of cpptools (version 0.9.0).

**Comment by dvirsky** [comment]
Any ETA on 0.9.0? Besides this bug, the auto-completion suggestions are totally screwed up on the latest version. Is it at least possible to revert to 0.7?

**Comment by jgoshi** [comment]
Version 0.9.0 should be available within the next week or so. We did some work on auto-completion but there's still many improvements we are currently working on for future releases.

**Comment by dvirsky** [comment]
Cool. Right now it seems like the auto-complete defaults to all known symbols in a lot of trivial cases. I tried all configuration options to no avail. 
Is there any way to downgrade to 0.7? it worked much much better in that sense.

**Comment by jgoshi** [comment]
Sorry I'm not aware of any way to downgrade.

**Comment by dvirsky** [comment]
@jgoshi oh well. Is there a way to cause the extension not to do completions at all? there's another extension that uses clang and does decent completion, but lacks all the other great features yours has. I wish I could use both.

**Comment by dvirsky** [comment]
maybe it's worth adding a configuration option to disable this.
