### ISSUE TITLE
C++ syntax highlighting issue

### ISSUE THREAD

**Issue by DanielJamesCollier** [microsoft/vscode-cpptools#460]
VSCode version: 1.8.1
CPP Tools: 0.9.3

Digit separators don't work ? like the following 
```
int test =  20'000;
int test2 = 20;
```

All code after the digit separator gets highlighted wrong. see screenshot.

![syntax highliting issue with vs code](https://cloud.githubusercontent.com/assets/6226245/22291861/6405d19e-e300-11e6-8fe2-d732eec9b0b7.png)

**Comment by DanielJamesCollier** [comment]
![syntax highliting issue with vs code](https://cloud.githubusercontent.com/assets/6226245/22291858/58b96ad0-e300-11e6-918c-375a20e90a9b.png)

**Comment by sean-mcmanus** [comment]
The bug repros without the C++ extension installed. See https://github.com/atom/language-c/issues/154 .

**Comment by DanielJamesCollier** [comment]
![syntax highliting issue with vs code](https://cloud.githubusercontent.com/assets/6226245/22292309/70d0d4ee-e302-11e6-9a93-3b524f90b857.png)

It is installed ?

**Comment by sean-mcmanus** [comment]
The bug repros with and without the C++ extension installed. It is not a bug in the C++ extension. We don't implement C++ syntax highlighting. VS Code implements it via the atom (i.e. textmate) component.

**Comment by DanielJamesCollier** [comment]
@sean-mcmanus sorry, thanks for the info.

**Comment by sean-mcmanus** [comment]
I posted a comment on the atom/language-c bug (reported back in August) asking for a status update. I don't know why it's taking so long for a fix to get released.
