### ISSUE TITLE
Inconsistent Language with VSCode

### ISSUE THREAD

**Issue by E-train-Liu** [microsoft/vscode-cpptools#4600]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Family
    - Original Default Language: zh-CN
    - Display Language set to: en-US 
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them): No
- A clear and concise description of what the bug is.

    The Snippet Suggestions given by C/C++ extension are mixed with Chinese and English. While my VSCode is actually displaying English. No Chinese Extension have been installed. 

    I know this maybe caused by my Windows 10, which is a Family Edition and originally use Chinese as displaying language. 

**Expected behavior**

It maybe better to let the language consistent with VSCode by default, and  then enable the displaying language to be configured. 

**Screenshots**

![image](https://user-images.githubusercontent.com/38714576/68783527-0aa67000-0633-11ea-878b-ac1e942b4220.png)

**Comment by Colengms** [comment]
Hi @E-train-Liu .  Is all text associated with the C/C++ Extension in Chinese?  Could you check the C/C++ output channel?  And, perhaps check the strings used in the Find All References or Rename UI ?

Could you try the following and let us know if it works around the issue? :
 - Install a language pack
 - Switch the language
 - Switch the language back to English

**Comment by E-train-Liu** [comment]
> 
> 
> Hi @E-train-Liu . Is all text associated with the C/C++ Extension in Chinese? Could you check the C/C++ output channel? And, perhaps check the strings used in the Find All References or Rename UI ?
> 
> Could you try the following and let us know if it works around the issue? :
> 
> * Install a language pack
> 
> * Switch the language
> 
> * Switch the language back to English

1. Yes, it seems all text in C/C++ extension have such problem. And I recently found that the popup info generated by C/C++ extension is also in Chinese. See the screenshot below. I am sorry I am too busy recently to test those thing. I'll try my best to give the testing result soon .


    ![image](https://user-images.githubusercontent.com/38714576/68905888-90611300-073a-11ea-99cf-036ec501175a.png)

2. I have installed then uninstalled the language pack. The problem still exist.

**Comment by Colengms** [comment]
Hi @E-train-Liu .  The last image you posted contains a string provided by a library we are using for localization, [vscode-nls](https://github.com/microsoft/vscode-nls).  Since the C/C++ Extension is not attempting to determine the proper language in that case, I believe this is an issue with VS Code and the vscode-nls library.  I've opened an issue here: https://github.com/microsoft/vscode/issues/84883

**Comment by E-train-Liu** [comment]
I recently found that the problem may really caused by my Windows 10.

My initial windows edition installed is "Windows 10 Family Chinese Edition" (Not equivalent to Window 10 Family whose displaying language was set to zh-CN, the "Chinese Edition" not let the user to choose displaying language except zh-CN). My organization update my Windows to "Windows 10 Family". Then, I change the displaying language to en-US. 

But the updating is not very successful and seems broke something. So I recently found that the actual Windows "Displaying Language" is still zh-CN, but the "Default Language" goes to en-US (I am very sorry that I gave the wrong information in previous comments due to my careless). 

![image](https://user-images.githubusercontent.com/38714576/68998165-8d833100-08a6-11ea-8302-74f65d2abd7c.png)

And you can see that many Apps also have inconsistent language now.

![image](https://user-images.githubusercontent.com/38714576/68997949-f4ebb180-08a3-11ea-9f5b-9490cfd077ef.png)

Sorry again to give incorrect information in comments before. So the `localize()` in vscode-nls should works fine ([microsoft/vscode/issues/84883](https://github.com/microsoft/vscode/issues/84883)). 

But I will really appreciate it if users are allowed to choose the displaying languages in setting. The reason is that my colleagues come from multiple counties. They may use different languages in their own OS, but all use English in VSCode to share the error info easily.

**Comment by wdscxsj** [comment]
@Colengms I think the reported issue is not related to installed language packs. As a Chinese programmer, it's common practice to set English as the default input language, simply to avoid toggling the Chinese IME on and off. That's the "Default Language" reported by E-train-Liu, and it's not the same as the display (UI) language of Windows. The top half of his 3rd screenshot shows the Windows display language is Chinese (中文（中华人民共和国）), and the bottom half shows the default input language is English (United States).

To decide its display language, VSCode checks `"locale"` in `argv.json` before using the operating system's UI language (https://code.visualstudio.com/docs/getstarted/locales). On my laptop (Windows 10 Simplified Chinese), `"locale": "en"` sets all UI elements to English except for the C/C++ Extension. For instance, C/C++ Configurations are all Chinese. I suspect the C/C++ Extension fails to obey the `"locale"` value when setting its display language.

**Comment by Colengms** [comment]
Hi @wdscxsj .  Thanks for the additional information.  Our extension currently leverages only the NLS libraries to set the language.  ( https://github.com/microsoft/vscode-nls https://github.com/microsoft/vscode-nls-dev ).  I believe you will see the same differences of languages for other extensions that use these libraries provided by VS Code, and rely on it to detect the current language.  We should not need to check argv.json, or do any other detecting of the current language ourselves.  It may be that ours is the only one you currently have installed.  The internal detection in the NLS libraries appears to be flawed if a language pack has not (yet) been specifically selected and there is a difference between the original OS language and current OS language (https://github.com/microsoft/vscode/issues/84883 , which is still an issue, but appears to have been closed due to inactivity.).  Could you try also selecting a language pack, and let us know if that causes our extension to start using the same language as VS Code?

**Comment by wdscxsj** [comment]
@Colengms Hi, I think you are right. With the French language pack installed and selected, my VSCode UI is still in English and C/C++ Edit Configurations still in Chinese. The `"locale": "fr"` option in `argv.json` is somehow loaded too late, as [pointed out](https://github.com/Microsoft/vscode/issues/4170) by Tyriar. A manual execution of `code --locale=fr .` kills all these issues.

I'm not quite sure about the part of  "difference between the original OS language and current OS language". Did you mean @E-train-Liu changed his Windows display language? I believe he didn't; it's only a change of the preferred input language (using Chinese IME or not).

**Comment by Colengms** [comment]
Hi @E-train-Liu @wdscxsj .  Are you still seeing incorrect localized strings?

The C/C++ Extension uses [the `vscode-nls-dev` library](https://github.com/microsoft/vscode-nls-dev), provided by VS Code.  It determines/detects the current language and decides which set of localized strings to use.  If you are seeing the wrong language strings, that would seem to be a bug in that library or VS Code itself.  If you are still seeing this issue, I'd like to confirm whether it also occurs with other extensions that use `vscode-nls-dev`.  If so, we should ensure there is an issue for your scenario in the VS Code repo.

**Comment by wdscxsj** [comment]
Hi @Colengms, I think this issue is fixed now. Thanks!
