### ISSUE TITLE
Outline view can't refresh with adding "**/.*" in File.exclude

### ISSUE THREAD

**Issue by nemo-rui-chen** [microsoft/vscode-cpptools#4602]
Issue Type: <b>Bug</b>

Outline view will refresh itself if I change the files like exchange the position of any two functions.
However, when I add a item "**/.*" in "File.exclude " setting and exchange functions in the same way, it can't refresh.  After I remove the item and restart vscode, It can work again.

Extension version: 0.26.1
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (22.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Looks like a bug with our exclusion parsing code.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0
