### ISSUE TITLE
IntelliSense: no support for GCC alignment attrubite

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-cpptools#4603]
Issue Type: <b>Bug</b>

The following code compiles fine:
```
#define BUILD_BUG_ON(condition) ((void)sizeof(char[1 - 2 * !!(condition)]))
#define ALIGNED __attribute__((__aligned__(16)));

struct unaligned {
    int i;
};

struct aligned {
    int i;
} ALIGNED;

int main(int argc, char **argv) {
  BUILD_BUG_ON(sizeof(unaligned) != 4ULL);
  BUILD_BUG_ON(sizeof(aligned) != 16ULL);
  return 0;
}
```
but produces an IntelliSense error because it does not take the `__attribute__((__aligned__(16)))` into account.

Extension version: 0.26.1
VS Code version: Code - Insiders 1.41.0-insider (c408a2c02d78982b1f83819c587c02bb59af9f93, 2019-11-13T06:25:23.355Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-70-generic
Fetching remote diagnostics for 'ssh-remote+7b22686f73744e616d65223a22434c58227d' timed out.
Remote OS version: Linux x64 4.15.0-70-generic

**Comment by michelleangela** [comment]
Thank you for reporting this issue. 

The C/C++ extension uses the same IntelliSense engine as C++ IntelliSense on Visual Studio and this issue was reproducible on Visual Studio. I filed the bug at https://developercommunity.visualstudio.com/content/problem/820990/intellisense-no-support-for-gcc-alignment-attrubit.html

**Comment by michelleangela** [comment]
The feedback ticket on Visual Studio for this issue has been closed as it was evaluated as low priority. To increase its priority and re-open the issue on Visual Studio, please upvote the feedback ticket https://developercommunity.visualstudio.com/content/problem/820990/intellisense-no-support-for-gcc-alignment-attrubit.html

**Comment by anatolyburakov** [comment]
I can't vote for reactivation for that ticket for some reason - it won't let me submit feedback.

**Comment by michelleangela** [comment]
@anatolyburakov 
Thanks for letting us know about not being able to vote on the closed feedback ticket. We found that there's a [request to allow voting on closed Visual Studio feedback tickets](https://developercommunity.visualstudio.com/t/Dev-Community--gt;-Allow-up-vote-on-clo/536898?space=8&q=vote).

In the meantime, we'll track the votes here and ask the Visual Studio ticket to be re-considered if the votes increase. If you'd like, you can also re-file an issue against Visual Studio as well and provide a reason for the severity of the issue.

**Comment by bobbrow** [comment]
It appears that this issue is fixed in the latest version of the extension.
