### ISSUE TITLE
Can't create IntelliSense client for  <filename> 

### ISSUE THREAD

**Issue by mdzahidh** [microsoft/vscode-cpptools#4605]
Hi I am seeing these errors/warning a lot, pretty much for every file in my project lately.

There are two issues:
1.
```
Can't create IntelliSense client for  <filename> 
[Warning] Some references may be missing, because workspace parsing was incomplete when Find All References was started.
```

2. Sometimes when I CTRL+Click, the Find all references pops up and fails. Why is it popping up Find all Ref ?

The filename has no special character or anything. This happens in both my Linux box and Windows box. 

What might be happening ?

**Comment by michelleangela** [comment]
Which version of the extension does the issue occur on? Can you share the following 2 logs:

1. Log from running the command `C/C++: Log diagnostics` 
2. [Logs for the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server).

**Comment by sean-mcmanus** [comment]
In regards to issue 2: VS Code Insiders is invoking Find All References when Ctrl+Click (or go to def) is invoked on the definition itself. There's a thread at https://github.com/microsoft/vscode/issues/73081 .

**Comment by mdzahidh** [comment]
ah, falling back to Peek References may work for other language but for the C/C++ it gives a pretty horrible experience as it out of nowhere locks up all intellisense ! :(

**Comment by RigoLigoRLC** [comment]
https://pasteboard.co/IH4Ekzg.png
I'm having the same problem with the latest version of C++ Tools plugin 0.26.2-insiders. The elements.hpp file was working fine last night and it suddenly died today. Deleting the entire plugin folder and reinstalling it don't work out.

@michelleangela here are my logs, if you'd like to see

C/C++ Log Diagnostics output:
https://pastebin.com/mTyrW9pu
C/C++ Debug of language server output after a window reload:
https://pastebin.com/xrWJ7Rnw

The problematic project is on my github page; the problematic file has no read/write permission issues on my computer.

VSCode: 1.40.1
Plugin: 0.26.2-insiders
System: Ubuntu 18.04LTS

**Comment by nunojsa** [comment]
I'm also always seeing the `Can't create IntelliSense client for  <filename> `. What is the meaning of this message? I also realized that after including the header `signal.h`, a lot of symbols of that header do not appear on the autocomplete. Is it related with the message?

**Comment by nunojsa** [comment]
Ok. For the signal things, defining `_GNU_SOURCE` apparently fixes my auto completion. Not sure why we need since things like `sigaction()` do not need to explicitly define GNU_SOURCE (using gnu11/99 as standard is enough). It seems to be related with #2782

**Comment by bobbrow** [comment]
This should be fixed in the latest version of the extension. Please let us know if you continue to have problems with this.  Thank you!
