### ISSUE TITLE
Specifying miDebuggerPath in launch.json file for a container debug

### ISSUE THREAD

**Issue by Prj1508** [microsoft/vscode-cpptools#4607]
Type: Debugger

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by Prj1508** [comment]
OS and Version: Ubuntu 16.04
VS Code Version: /C++ Extension Version:0.26.1
Other extensions you installed (and if the issue persists after disabling them):
A clear and concise description of what the bug is.

I am trying to debug C++ code in a container and in launch.json file, I have specified debugger path as 
"miDebuggerPath": "/usr/bin/gdb", 

but VS code complains 
"Unable to start debugging. The value of miDebuggerPath is invalid" 
I have gdb in root/usr/bin directory. 
These work when I debug in local 
Is there a different setting I need to do for container based debugging? 
snapshot is below
![image](https://user-images.githubusercontent.com/48227055/68908608-d659af00-0719-11ea-96d4-e2529663efc3.png)

**Comment by pieandcakes** [comment]
@Prj1508 Are you attempting to debug in the container? If so, can you paste your entire launch.json? 

In the picture it looks like you are setting up a local debugging scenario and not one running in a Docker container. It is looking on your local machine for `/usr/bin/gdb`.

If you are attempting to do remote debugging in the container, you will need to have a `pipeTransport` block and specify the correct executable and parameters to launch the debugger in the container.

An example of that would be [here](https://code.visualstudio.com/docs/cpp/pipe-transport#_docker-example).

**Comment by snevs** [comment]
I have the same issue, but only when I select 
`clang++ - Build and debug active file`
However
`g++ - Build and debug active file`
works

**Comment by WardenGnaw** [comment]
Not enough info provided. Closing issue for now. 

If you are still experiencing problems, please file a new issue with the additional information requested.
