### ISSUE TITLE
High CPU usage after switching GIT branch 

### ISSUE THREAD

**Issue by nico87** [microsoft/vscode-cpptools#4609]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.40.1
- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them): native debug and SSH FS. The issue persists after removing them

When I switch branch using the system terminal outside VS Code, the cpp extension spikes the CPU at 100% and does not stop for the time being.

**To Reproduce**

1. Open a c++ git repository in VS Code
2. Wait for the cpp extension to end its work
3. Switch to another git branch
4. Checkout top for high cpu usage

**Expected behavior**
The cpu usage should lower to normal levels after few second/minutes

**Comment by sean-mcmanus** [comment]
Looks like we already have an issue on this at https://github.com/microsoft/vscode-cpptools/issues/2806 .
