### ISSUE TITLE
Arrow in initializer list breaks syntax highlighting

### ISSUE THREAD

**Issue by NOhs** [microsoft/vscode-cpptools#461]
I don't know if this is the right place to post this, but when using the `->` operator in an initializer list in vscode C++, the syntax highlighting gets mixed up.
![cpp_broken_syntax_highlighting](https://cloud.githubusercontent.com/assets/20553080/22301078/f1faf4b0-e329-11e6-93da-6c16b2f5c09f.PNG)

As you can see in the image above, the `c2`, the `6` and the `0.0f` are not highlighted.
![cpp_broken_syntax_highlighting_2](https://cloud.githubusercontent.com/assets/20553080/22301145/3d626f96-e32a-11e6-901b-45fa9e467cc7.PNG)
![cpp_broken_syntax_highlighting_3](https://cloud.githubusercontent.com/assets/20553080/22301147/3faedf0a-e32a-11e6-93f9-09757a6b81db.PNG)

**Comment by sean-mcmanus** [comment]
It's a bug with Atom/language-c (the C++ extension doesn't implement its own syntax highlighting). Can you report it at https://github.com/atom/language-c/issues ?

**Comment by NOhs** [comment]
Ok, I will report it there.
