### ISSUE TITLE
How to get the lldb Interactive Interpreter?

### ISSUE THREAD

**Issue by CodeLife2012** [microsoft/vscode-cpptools#4611]
Can't find any place to input lldb command(bt, thread, expr...).  Try to run it in debug console.

![image](https://user-images.githubusercontent.com/4277861/68945588-b1357100-07eb-11ea-8760-858ccc45b4e9.png)

My launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(lldb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/helloworld.out",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": true,
      "MIMode": "lldb"
    }
  ]
}

```

**Comment by pieandcakes** [comment]
@CodeLife2012 The DebugConsole was designed for you to do variable and expression evaluation. In order to pass a command to the debugger, you need to preface each command with `-exec`. When we see `-exec` we don't do anything except to pass the following string to `lldb-mi`.
