### ISSUE TITLE
Feature request: open a header file, ask why it is (or isn't) indexed.

### ISSUE THREAD

**Issue by prideout** [microsoft/vscode-cpptools#4613]
I would love to find out why Intellisense is (or isn't) parsing a particular file, so that I can figure out how to fix my exclusion / inclusion lists.  Imagine if I could open a header file and do "C/C++: View IntelliSense information for current file", which would show me if the current file is being indexed, and if so, the list of rules that led to it being indexed.

**Comment by prideout** [comment]
Some more context:

This is probably due to some global configuration on my machine but I can't figure out why `CPP.Extension` has recently been consuming 100% CPU on my machine, even for small projects with minimal content in their `c_cpp_properties.json`. Here's one of my typical config files:

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "extras",
                "src"
            ],
            "defines": [
                "TVECTOR_STDIO",
                "PAR_STREAMLINES_IMPLEMENTATION"
            ]
        }
    ],
    "version": 4
}
```

I enabled Debug logging and noticed some redundancy in the global locations that are being indexed:

```
Folder: /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/include/ will be indexed
Folder: /usr/local/include/ will be indexed
Folder: /usr/local/Cellar/gcc/8.2.0/include/ will be indexed
Folder: /usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/include-fixed/ will be indexed
Folder: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Network.framework/Versions/A/Headers/ will be indexed
[...plus more Frameworks that I don't use...]
```

I usually use clang so I would like it if homebrew-installed gcc weren't indexed.  I tried adding `**/gcc` to `files.exclude` but I still see the above output after resetting my database.  I also tried adding setting `compilerPath` to: `usr/bin/clang`, but the gcc things are still being indexed.

I also see this:

```
 tag parsing file: /usr/local/Cellar/boost/1.67.0_1/include/boost/compatibility/cpp_c_headers/cstdio
```

I tried adding `**/Cellar` to `files.exclude` but it still gets parsed.

**Comment by bobbrow** [comment]
`files.exclude` only works for files within your `${workspaceFolder}` so you wouldn't be able to exclude these external files that way.  We should only be adding paths for headers that your compiler is using and clang has the ability to choose gcc headers.

What do you see when you run `/usr/bin/clang -v -E -x c++ - /dev/null` in your terminal?  It should print out a list of system include paths and those are supposed to be the ones that the extension uses to populate the index.
