### ISSUE TITLE
Intellisense (and most features of this extension) Not Working

### ISSUE THREAD

**Issue by ashanhol** [microsoft/vscode-cpptools#4614]
Fact: **My code is able to build correctly using non vscode command line and goma build tools. I have copied my c_cpp_properties.json against someone who's C/C++ extension works correctly on this code base and they are identical.** 
Expect: Features of this extension expected to work correctly. 
Actual: 
- "Go to definition" frequently sits and spins without producing result. Inconsistently able to work sometimes.
- Inconsistent red underline over everything.
- No autocomplete
- Includes not able to find every file (sometimes it will say it can't find an include, but then "go to definition" will work???). 

Reality: It's clear almost no part of this extension works correctly on my machine decreasing my productivity. 

Red underline, error: "not a class or struct name"
![image](https://user-images.githubusercontent.com/9140651/68965537-e3fe4b80-0790-11ea-8aa3-1540d80e8e23.png)

Try to go to definition, vscode can tell it's a class or struct name. 🤷‍♀️
![image](https://user-images.githubusercontent.com/9140651/68965586-fbd5cf80-0790-11ea-8559-344288dabd7c.png)

Red underlines disappear, completely only to come back and underline everything after. Not working correctly at all. 
![image](https://user-images.githubusercontent.com/9140651/68965623-15771700-0791-11ea-9dcc-4c33312016f5.png)

**Comment by sean-mcmanus** [comment]
Can you use the C/C++: Log Diagnostics command to see what includes and defines we're using and if they're incorrect? By default we use recursive includes, which doesn't give 100% correct result in all workspaces (e.g. if the non-deterministic includePath ordering causes the wrong file to get used).

I tried a version of chromium and wasn't able to repro the bug.

Go to Def on `#include` lines doesn't use the IntelliSense includePath for lookups (there's another issue tracking that).

Can you provide more detailed repro steps?

**Comment by xgdgsc** [comment]
I also began to see this intellisense not working properly since maybe a day or two. Might after vscode update?

here' s my ` C/C++: Log Diagnostics command` output. I tried reinstalling C++ extension. This is stable version, not insider version.

```
-------- Diagnostics - 11/16/2019, 3:52:53 PM
Version: 0.26.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/include/**",
        "/n1/env/include/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc-9",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compileCommands": "${workspaceFolder}/build-Debug/compile_commands.json",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${workspaceFolder}/include/**",
            "/n1/env/include/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.
```

**Comment by xgdgsc** [comment]
Just tried insider build and also not showing auto complete correctly.

**Comment by xgdgsc** [comment]
It started working well for me after reinstalling stable release after trying insider.

**Comment by xgdgsc** [comment]
I was wrong, completion of type works but not class methods

**Comment by ghost** [comment]
I seem to be having a similar issue on my system.  I am working on a C++ project and the extension does not seem to be handling C++ syntax properly, as people have mentioned above in this issue.  I have been manually reverting the C++ extension back to version 0.24.1, as that seems to be the most recent extension version where the problem does not occur.

I ran the `C/C++: Log Diagnostics` command on both versions of the extension, and I've noticed that the `Standard Version` is different for the same translation unit.  I have redacted some project-specific information (includes, source file names) from the output, as it may be confidential and I don't feel comfortable sharing it.

```
-------- Diagnostics - 11/18/2019, 12:40:23 PM
Version: 0.26.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/src/include",
        "${workspaceFolder}/src",
        "/usr/include/x86_64-linux-gnu/c++/7",
        "/usr/include/c++/7"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c11",
    "cppStandard": "c++11",
    "intelliSenseMode": "${default}",
    "compilerArgs": []
}
Translation Unit Mappings:
[ <REDACTED>.C ]:
    <REDACTED>.H
Translation Unit Configurations:
[ <REDACTED>.C ]:
    Process ID: 834
    Memory Usage: 29 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        <REDACTED - workspace include path>
        <REDACTED - workspace include path>
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        <REDACTED - translation unit-specific include path>
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=70400
Total Memory Usage: 29 MB
```

The output for version 0.24.1 is almost identical, but the `Standard Version` is c++11 instead of c11.  Is it possible that the 0.26.1 version of the extension is treating the C++ source files as C source files instead?  I thought that might explain why it seems C++ specific syntax is not being handled properly.  Our naming conventions for our C++ source and header files are somewhat abnormal (.C/.H), but it doesn't seem like this was a problem in earlier versions of the extension.  I have the language mode set to C++ for these filename extensions, and I've verified that the language mode setting for this specific translation unit is C++ (not sure if that makes a difference)

**Comment by xgdgsc** [comment]
Deleting the extension folder `~/.vscode/extensions/ms-vscode.cpptools-0.26.1/` and reinstalling seems to fix it for me

**Comment by xgdgsc** [comment]
It stopped working again for me :sweat:

**Comment by sean-mcmanus** [comment]
@xgdgsc Your diagnostic log file shows no IntelliSense process is active. Are you able to enable debug logging (https://code.visualstudio.com/docs/cpp/enable-logging-cpp) and see what error message is shown when it tries to create the IntelliSense process? Also, if you could only specify only a configurationProvider or compileCommands, that would help narrow down the problem.

**Comment by xgdgsc** [comment]
Thanks. It shows log like:
```
Custom configuration provider 'CMake Tools' registered
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
cpptools/fileCreated
cpptools/fileCreated
cpptools/getCodeActions: 186
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: 187
cpptools/getDocumentSymbols
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///home/sgao/Documents/sim/src/bar_exec.cpp
Queueing IntelliSense update for files in translation unit of: /home/sgao/Documents/sim/src/bar_exec.cpp
cpptools/getCodeActions: 188
cpptools/textEditorSelectionChange
cpptools/getCodeActions: 189
Error squiggle count: 1
Update IntelliSense time (sec): 0.65
cpptools/getCodeActions: 190
Database safe to open
cpptools/fileDeleted
cpptools/fileDeleted
Database safe to open
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///home/sgao/Documents/sim/src/bar_exec.cpp
Queueing IntelliSense update for files in translation unit of: /home/sgao/Documents/sim/src/bar_exec.cpp
Error squiggle count: 1
Update IntelliSense time (sec): 0.68
cpptools/getCodeActions: 191

cpptools/fileCreated
cpptools/fileDeleted
cpptools/getDocumentSymbols: 212
cpptools/getDocumentSymbols
cpptools/fileCreated
cpptools/fileDeleted
Database safe to open
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/fileCreated
cpptools/fileDeleted
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///home/sgao/Documents/sim/src/bar_exec.cpp
Queueing IntelliSense update for files in translation unit of: /home/sgao/Documents/sim/src/bar_exec.cpp
Error squiggle count: 1
Update IntelliSense time (sec): 0.6
```

**Comment by sean-mcmanus** [comment]
Is there stuff before that log? I don't see the output when it tries to create the TU initially.

**Comment by xgdgsc** [comment]
I found it works after opening the folder of "MyProject" directly. I was using a workspace file on the parent directory MyProject.code-workspace.

**Comment by xgdgsc** [comment]
It stopped again. log at https://gist.github.com/xgdgsc/1667c7bbe5b260feda9be5e84e418201

**Comment by sean-mcmanus** [comment]
I'm OOF till Friday.

@Colengms Can you investigate this -- I'm seeing the forced include file sim_core_CXX_prefix.hxx causing the compiler to generate a fatal error, causing defines to be missing when it queries /usr/bin/g++-9. I think maybe we should not pass forced includes arguments to the compiler when we query it for compiler defaults.

@xgdgsc Are you able to somehow get that "fatal error" showing the log to be fixed. Or maybe remove the `"-include", "....hxx"` and pass it via the forcedInclude setting....although that appears to be coming from the CMake Tools extension (so it could be a bug with that extension).

**Comment by xgdgsc** [comment]
Thanks for the tip. The file reported as fatal error exists.  I disabled cotire in CMakeLists and it works.

**Comment by bobbrow** [comment]
We're tracking #4655 as the fix for this.

**Comment by sean-mcmanus** [comment]
@xgdgsc With https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders2 the failure caused by "-include" being used should be fixed. Let us know if you hit any other issues.

**Comment by grigorig** [comment]
This started to appear recently for me. There is nothing obvious in the diagnostics log at all. I'm using version 0.29 of the extension. Is this a regression?

**Comment by sean-mcmanus** [comment]
> This started to appear recently for me. There is nothing obvious in the diagnostics log at all. I'm using version 0.29 of the extension. Is this a regression?

@grigorig Could you file a new issue with more repro details? We're not aware of a regression like this.
