### ISSUE TITLE
Find All References and Rename not leveraging existing TUs

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#4617]
I have a header-only library.  There is 1 source file that includes all of the headers.  The source file is correctly selected to create the translation unit, when any of the headers are opened.

However, if I use Find All References, or Rename, a bunch of additional IntelliSense processes are spawned.  Since every header should already be in the single existing TU, it should not be necessary to spawn additional IntelliSense processes.  Reusing the existing TU would provide much better performance.

**Comment by sean-mcmanus** [comment]
This issue only repros when the source file doesn't contain any of the references but the headers do.
