### ISSUE TITLE
c_cpp_properties.json giving warning.

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#462]
Just installed 0.10.0 and it seems as if everything stopped working. No database is produced, so I'm not sure if the language server is actually doing anything active.

`Problems loading reference 'file:///c%3A/Users/sholmq/.vscode-insiders/extensions/ms-vscode.cpptools-0.10.0/boolean': Unable to load schema from 'c:\Users\sholmq\.vscode-insiders\extensions\ms-vscode.cpptools-0.10.0\boolean'`

Here's my edited part:

```
{
    "name": "Win32",
    "includePath": ["Sw/A_XMC/out/obj"],
    "browse" : {
        "limitSymbolsToIncludedHeaders" : true,
        "databaseFilename" : ""
    }
}
```

**Comment by sean-mcmanus** [comment]
That is a warning. I see that too when opening c_cpp_properties.json, but everything still works. Maybe the two are unrelated. How do you know no database is being produced?

**Comment by sean-mcmanus** [comment]
The warning is a bug with our c_cpp_properties.schema.json. If you remove lines 62-64 from that file the warning will go away. It should be fixed in our next update. However, I'm still not aware of any other negative side effects of this warning.

**Comment by csholmq** [comment]
@sean-mcmanus You are completely correct. They were unrelated. My issue was that the database file is now stored elsewhere than project root by default.

Your suggestion did the trick. Thanks!
