### ISSUE TITLE
[Internal testing] Only one message "The terminal process terminated with exit code:1" show on terminal window after building project

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode-cpptools#4623]
According to the tutorial: https://code.visualstudio.com/docs/cpp/config-msvc 
Configure the c_cpp_properties.json, launch.json and tasks.json and create helloword.cpp.
After building the project, only one message "The terminal process terminated with exit code: 1" show on the terminal window

![image](https://user-images.githubusercontent.com/29274719/69029071-e4a41580-0a0e-11ea-9e5d-72d1b8638be0.png)

VSCode version: 1.40.1
C/C++ extension version: 0.26.1

**Comment by bobbrow** [comment]
Which folder is helloworld.cpp in?  If it's in the `.vscode` folder, then that's why you're getting this error.  Can you share the folder structure?

**Comment by Wanye1062271859** [comment]
Hi bobbrow,
My folder structure show as below, wish this can help you to resolve this problem.
![image](https://user-images.githubusercontent.com/29274719/69112470-428e3700-0abb-11ea-80a9-ecc976bd7dcd.png)

**Comment by michelleangela** [comment]
From which command prompt did you create the project folder and open VS Code from? Was it the **Developer Command Prompt for Visual Studio**? In order for the source code to build, [VS Code should be started from a Developer Command Prompt for VS](https://code.visualstudio.com/docs/cpp/config-msvc#_start-vs-code-from-the-developer-command-prompt).

Also, I suggest to create the project folder under a different folder, such as user documents and not under the Windows System32 which requires admin privileges for any file changes.

**Comment by Wanye1062271859** [comment]
Hi Michelleangela,
Thanks for your reply! This issue has been resolved, this problem is because the settings.json file, I once set the "terminal.integrated.shell.windows": "C:/Windows/System32/wsl.exe" in settings.json file in other workspace, the new created workspace use the setting.json file by default.  This issue are resolved after deleting the setting from setting.json file.

**Comment by michelleangela** [comment]
Closing as resolved.
