### ISSUE TITLE
Error list path error

### ISSUE THREAD

**Issue by HuJK** [microsoft/vscode-cpptools#4628]
Type: Debugger

**Describe the bug**
- OS and Version: Debian 10
- VS Code Version: 1.40.1
- C/C++ Extension Version: 0.26.2-insiders
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/15907444/69041230-1d051d00-0a2a-11ea-9d25-f353c21e6838.png)

I can't goto the problem line by one click, It seems there have some problem to parse the output from g++
![image](https://user-images.githubusercontent.com/15907444/69041561-aae10800-0a2a-11ea-8276-cdad52bd6bda.png)

**To Reproduce**
1. follow this: https://github.com/HuJK-TestRepo/testvscode/tree/master

**Additional context**
launch.json and tasks.json should exist in the link.

**Comment by Colengms** [comment]
This looks like an issue with the built in gcc problem matcher, and potentially a duplicate of https://github.com/microsoft/vscode-cpptools/issues/2266 .

If I understand correctly, a potential workaround for your repro override the base gcc problem match and switch it to using absolute paths.

```
            "problemMatcher": {
                "base": "$gcc",
                "fileLocation": ["absolute"]
            },
```

**Comment by HuJK** [comment]
This workaround works, thank you.

Is this a bug of VScode? Or just I misconfigured?

**Comment by sean-mcmanus** [comment]
@HuJK We have a fix pending at https://github.com/microsoft/vscode-cpptools/pull/3916, but it would require us taking a dependency on a newer version of the VS Code, so we've postpone that change till later.
