### ISSUE TITLE
[Internal testing] The all of the text about "Reference" are not localized

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode-cpptools#4629]
1. Install VSCode and install the C/C++ Extension from View->Extension
2. Install the CHS language pack from View->Extension
3. Restart VSCode to switch the display language to CHS
4. Open a cpp file and tying some code
5. Right click on a variable and click "Find All References" to open the reference window
![image](https://user-images.githubusercontent.com/29274719/69046146-42e2ef80-0a33-11ea-95ab-fc86f6a546de.png)

6. Put the cursor on the icon "Reference" on the main menu
![image](https://user-images.githubusercontent.com/29274719/69045550-05ca2d80-0a32-11ea-821e-941b69beaef0.png)

7. View the reference window
![image](https://user-images.githubusercontent.com/29274719/69046182-58f0b000-0a33-11ea-8163-b59838b418ea.png)

VSCode version: 1.40.1
Affected language: All non English
C/C++ extension version: 0.26.2

**Comment by Colengms** [comment]
This UI is part of VS Code, not added by the cpptools Extension.  I've opened https://github.com/microsoft/vscode/issues/85055 against VS Code.

**Comment by Colengms** [comment]
Closing this, as it's not specific to the C/C++ Extension, and it's being tracked in the vs code repo.
