### ISSUE TITLE
[insiders] IntelliSense crash when memory usage gets too large

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#4630]
We're seeing crashes in our telemetry related to a new memory management algorithm in IntelliSense

**Comment by sean-mcmanus** [comment]
This might be "okay" because the IntelliSense process should restart after the crash after the next IntelliSense request, which would explain why no users are complaining about it (i.e. same behavior as on Windows with VS). Better to avoid crashing still though.
