### ISSUE TITLE
[insiders] IntelliSense process failing

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4631]
https://pasteboard.co/IH4Ekzg.png
I'm having the same problem with the latest version of C++ Tools plugin 0.26.2-insiders. The elements.hpp file was working fine last night and it suddenly died today. Deleting the entire plugin folder and reinstalling it don't work out.

@michelleangela here are my logs, if you'd like to see

C/C++ Log Diagnostics output:
https://pastebin.com/mTyrW9pu
C/C++ Debug of language server output after a window reload:
https://pastebin.com/xrWJ7Rnw

The problematic project is on my github page; the problematic file has no read/write permission issues on my computer.

VSCode: 1.40.1
Plugin: 0.26.2-insiders
System: Ubuntu 18.04LTS

_Originally posted by @RigoLigoRLC in https://github.com/microsoft/vscode-cpptools/issues/4605#issuecomment-554723043_

**Comment by sean-mcmanus** [comment]
@RigoLigoRLC What is the problematic project on your GitHub page?

What is the symptom of the problem you're seeing?

**Comment by RigoLigoRLC** [comment]
> @RigoLigoRLC What is the problematic project on your GitHub page?
> 
> What is the symptom of the problem you're seeing?

It's on the picture maybe you didn't see; it's LC2KiCad on my GitHub homepage which is the only C++ Project I own.
Symptoms: simply cannot make IntelliSense work on the elements.hpp. Everything else is in my original post.
It sometimes works and shows the error squiggles, but after you fixing the error it dies again.

Other files still can read that file. If I change the class definitions in the elements.hpp, the plugin will report error for having no matching definitons in elements.cpp. I don't exactly know what's going on.

**Comment by sean-mcmanus** [comment]
The screenshot shows that a crash occurred ("failed to read response"). Are you able to attach a debugger before the process crashes to get a call stack? I'm not reproing the crash using the project on Linux.

Insiders has an issue that can cause the "Can't create IntelliSense client" message to appear for open documents when the extension initializes. Is that what you're seeing or do you still get the error when you open new files that are not active on startup?

Also, there are 3 modes of configuring, (1) with configurationProvider set, (2) with compileCommands set, or with none of those set (just using c_cpp_properties.json) -- which setups cause the problems for you?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
