### ISSUE TITLE
Remove knownCompilers from "Current Configuration" after C/C++: Log Diagnostics

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4637]
...it shouldn't be there...

**Comment by bobbrow** [comment]
I think we need to remove this from the config and put it in a separate variable as soon as the message comes back from the language server.  It should never be a part of `c_cpp_properties.json` (as I have seen it appear in some issues).  We should probably clean up and configs we see that have it.

**Comment by bobbrow** [comment]
Related to #4931. Was fixed in 0.27.0.
