### ISSUE TITLE
Trigger database rebuild

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#464]
After looking at https://github.com/Microsoft/vscode-cpptools/issues/415#issuecomment-268133937 I found the new location for the database file. But this leads me to two questions:

1. What triggers a rebuild of the database? According to https://github.com/Microsoft/vscode-cpptools/issues/262, it's not triggered by changes in `c_cpp_properties.json`. This is also the case for adding entries to `files.exclude` where I have to manually delete the database to have it take effect.
2. How do I trigger a rebuild manually (besides deleting the database that is)? The only command I found was `Unload Language Server` which doesn't seem to do much.

**Comment by sean-mcmanus** [comment]
The database doesn't rebuild, other than via manually deleting or renaming it. It's a known problem we would like to fix. I've also never seen "Unload Language Server" have any effect.

**Comment by csholmq** [comment]
It appears that modifying or deleting the `c_cpp_properties.json` triggers a rebuild. At least for me. Is this by design?

**Comment by sean-mcmanus** [comment]
It just re-does what it usually does when the workspace is first opened (searches for new files to add to the database, potentially parsing them), but it doesn't remove stuff from the database yet. Also, ideally it would only trigger a rebuild when a setting that requires a rebuild changes, i.e. changing the intelliSenseMode shouldn't trigger a rebuild. Was there a reason you did not want a "rebuild"?

**Comment by csholmq** [comment]
Oh, I see. Because removing an include path did break stuff.

**Comment by csholmq** [comment]
As per your question, I was positively surprised. Sorry if it sounded as if it was something negative.

**Comment by bobbrow** [comment]
We just released 0.12.3 which added a new command to reset the database.
