### ISSUE TITLE
Extension doesn't run if not owned by user

### ISSUE THREAD

**Issue by dx-coding** [microsoft/vscode-cpptools#4643]
Type: General

**Describe the bug**
- OS and Version: Redhat Linux 7.5
- VS Code Version: 1.40.0
- C/C++ Extension Version: 0.26.1
- Other extensions you installed: 
  - python 2019.10.44104
  - xml 0.9.1
  - yaml 0.5.3
The issue persists after disabling them.
- Description:
  - I'm attempting to install code and the extensions listed above in an automated manner on new VMs. The idea is that a developer can spin up a new VM and have code and the extensions already installed on the VM (thus they never install an extension). I went by the docs for [Portable Mode](https://code.visualstudio.com/docs/editor/portable) to create the `/usr/share/code/data/` area. Code and the extensions get installed via ansible on boot and the group and file permissions are updated after installing (so the files are `root:swdev`).  Code launches fine and all of the extensions work except this one, `cpptools`.  There is no completion, syntax highlighting, and etc... for c++ and c files.

**To Reproduce**
Steps to reproduce the behavior (assuming cpptools is not yet installed):
  ```bash
  sudo /usr/bin/code --extensions-dir /usr/share/code/data/extensions --install-extension cpptools-0.26.1-linux.vsix
  sudo chgrp swdev -R /usr/share/code/data/extensions
  sudo chmod -R u+rwx,g+rwx,o+rX /usr/share/code/data/extensions
  /usr/bin/code 
  ```

**Expected behavior**
Code launches and the cpptools extension loads; providing completion, syntax highlighting, and etc... for c++ and c files.

**Additional context**
- I've created a launch.json with the following:
  ```json
  {
     "logging": {
        "trace": true,
        "traceResponse": true,
        "engineLogging": true
     }
  }
  ```
  In order to get the following log messages from the output window:
  > The installation of the C/C++ extension failed. Please see the output window for more information

- Reinstalling the the extension as the user via `/usr/bin/code --extensions-dir /usr/share/code/data/extensions --install-extension cpptools-0.26.1-linux.vsix` resolves the issue of the extension not working as desired.  So this works for us as a workaround for the time being.
- The user can also run `sudo chown -R $USER /usr/share/code/data/extensions/ms-vscode.cpptools-0.26.1` to resolve the issue.
- Running a diff between the `root:swdev` and the `$USER:swdev` folder `ms-vscode.cpptools-0.26.1` shows the only diff to be:
  - `ms-vscode.cpptools-0.26.1/package.json` 
    - The `activationEvents` in the `root` owned only lists `"*"`
    - The `activationEvents` in the `$USER` owned lists `"onLanguage:cpp",` ....and a few more.

**Comment by Colengms** [comment]
Hi @dx-coding .  Forgive my limited knowledge of *nix permissions.  Aren't files read-only to users other than the owner, by default?  The C/C++ Extension attempts to rewrite package.json when it's first activated.  It's likely that VS Code or other extensions would encounter similar issues when/if attempting to write to an existing file.

Perhaps you could address this by making all files writable for all users, or associating all files with a group that all users are in?

**Comment by dx-coding** [comment]
It depending on how the umask is set, but typically it is locked to the owner for read/write.

By running `sudo chgrp swdev -R /usr/share/code/data/extensions` after the install, it sets the group of all directories and files to `swdev` . Then, running `sudo chmod -R u+rwX,g+rwX,o+rX /usr/share/code/data/extensions` sets the file permissions to be read/writable by anyone in the group.

So, the files are read/writable by anyone in the group `swdev` and all directories are open (the `X` in `g+rwX` sets directories to be read/write/executable).

**Comment by dx-coding** [comment]
Setting the files to `rwx` still resulted in a failure.  I'm hoping to try looking through the source files to see if it's checking for ownership instead of if the file is writable.

**Comment by Colengms** [comment]
The code is cross platform, so I don't believe we're checking ownership.  However, since we are rewriting package.json, I assume the new copy is written with new permissions based on the user the process is running as at the time.

I will try the repro.

**Comment by Colengms** [comment]
Hi @dx-coding .  When I try to use the latest .gz (as the doc indicates the zip archive must be used on Linux for Portable Mode), I get the following error for any command line that attempts to launch `code` via sudo:

```
[3814:1121/152951.725467:FATAL:atom_main_delegate.cc(223)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

Are you not seeing the same issue?

**Comment by dx-coding** [comment]
No, but that's because I'm not running `code` via `sudo`.

We only run it via `/usr/bin/code`

**Comment by sean-mcmanus** [comment]
When I do Help->Toggle Developer Tools and view the Console tab, I see the error "Activating extension 'ms-vscode.cpptools' failed: vscode.window.showErrorMessage is not iterable (cannot read property Symbol(Symbol.iterator)).

@dx-coding Is that what you get or am I hitting a different issue?

**Comment by sean-mcmanus** [comment]
I think your chmod command needs to use a lower-case X or it won't add the correct permissions. Our extension ships binaries at data/extensions/ms-vscode.cpptools-0.26.1/bin/Microsoft.VSCode.CPP.Extension.linux and Microsoft.VSCode.CPP.IntelliSense.Msvc.linux that we run chmod 755 on during the installation, but if those files are restricted to root access then the chmod will fail.

Can you double-check if the permissions of the executables are correct?

I think the showErrorMessage error is just a symptom of the chmod failure (i.e. a separate bug).

**Comment by dx-coding** [comment]
I will double-check on Monday about the permissions.

**Comment by dx-coding** [comment]
@sean-mcmanus Even with all directories and files set to have group read/write/execute the extension still fails with the same message:
> The installation of the C/C++ extension failed. Please see the output window for more information

Also, I do see the same error message in the Developer Tools console you mentioned previously
> Activating extension 'ms-vscode.cpptools' failed: vscode.window.showErrorMessage is not iterable (cannot read property Symbol(Symbol.iterator))

**Comment by dx-coding** [comment]
I think I've tracked down the issue in [common.ts](https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/common.ts#L635)

`allowExecution` checks for file existence and if the file exists (and not win32), it always tries to change the file permission:
```js
if (process.platform !== 'win32') {
    checkFileExists(file).then((exists: boolean) => {
        if (exists) {
            fs.chmod(file, '755', (err: NodeJS.ErrnoException) => {
                if (err) {
                    reject(err);
                    return;
                }
                resolve();
            });
        } else {
```

I'd suggest adding a check to see if it needs to be done; something like:
```js
if (process.platform !== 'win32') {
    checkFileExists(file).then((exists: boolean) => {
        if (exists) {
            fs.access(file,  fs.constants.X_OK, (error: NodeJS.ErrnoException) => {
                if (error) {
                    fs.chmod(file, '755', (err: NodeJS.ErrnoException) => {
                        if (err) {
                            reject(err);
                            return;
                        }
                    });
                }
                resolve();
            });
        } else {
```
