### ISSUE TITLE
Can't stop terminal after entering into infinite loop

### ISSUE THREAD

**Issue by Rajat-S-Patel** [microsoft/vscode-cpptools#4646]
Issue Type: <b>Bug</b>

start an infinite loop and the try to kill the terminal. It will not respond.

Extension version: 0.26.2-insiders
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @Rajat-S-Patel .  Is this issue specific to the C/C++ Extension, or is it a general VS Code issue?  (The GitHub repo for VS Code is [here](https://github.com/microsoft/vscode)).

If specific to the C/C++ Extension, could you provide a bit more information?  How are you causing an infinite loop?

**Comment by Rajat-S-Patel** [comment]
This is a general VS code issue. Any infinite loop can't be terminated. Sometimes I can kill terminal but after that VS code do not respond and I have to close it forcefully.
A simple infinite for loop can be use to generate a similar problem

**Comment by michelleangela** [comment]
Hi @Rajat-S-Patel, it sounds like this issue is with the VS Code terminal and not specific to the C/C++ extension. Please file this issue at the [VS Code repository](https://github.com/microsoft/vscode/issues).
