### ISSUE TITLE
Multi definition problem

### ISSUE THREAD

**Issue by h2s0109** [microsoft/vscode-cpptools#4647]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.17134
- VS Code Version:1.40.1 (user setup)
- C/C++ Extension Version: 0.26.2
there is message on my value: identifier "Adc_ValueGroupType" is undefined
![image](https://user-images.githubusercontent.com/21095801/69328934-7d4ac780-0c93-11ea-96df-ea817b529da2.png)

**To Reproduce**

 I declare the type at  "Adc.h"
![image](https://user-images.githubusercontent.com/21095801/69329131-d581c980-0c93-11ea-9f63-f3d3b838610d.png)
But there are two Adc.h files 
Platform_Types.h is also same.
second Adc.h is not unintended file in the below figure.
Maybe it looks automatically include by a tool
![image](https://user-images.githubusercontent.com/21095801/69329219-03ffa480-0c94-11ea-9de6-555979cd45f7.png)
I would like to remove the auto-include file.
How can I remove the auto-include file?
I found the temporary solution like this #include "tricore\inc\Adc.h".
I would like to find the more right solution

**Comment by michelleangela** [comment]
Have you tried setting the includes and browse path in the [c_cpp_properties.json](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference)?

**Comment by h2s0109** [comment]
The below code is my JSON.
Can you guide what should I include?

I haven`t inserted below paths by myself.
I can`t understand why those paths is included.
**C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\adc.h
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\qcc\windows\platform_types.h**
My compiler doesn`t belong to gcc and msvc.
I just use the tool editing and code. analysis
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "_TASKING_C_TRICORE_"
            ],
            "compilerPath": "C:/Program Files (x86)/TASKING/TriCore v6.2r2/ctc/bin/ctc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by h2s0109** [comment]
I found a related issue [#2601](https://github.com/microsoft/vscode-cpptools/issues/2601)
so I have modified the below points
  **"compilerPath": "",**

1. undefined problem solved but still, it shows an unwanted path
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\adc.h

2. when I set **"compilerPath": "C:/Program Files (x86)/TASKING/TriCore v6.2r2/ctc/bin/ctc.exe",**
there is a undefined message. Is it the right operation?

![image](https://user-images.githubusercontent.com/21095801/69438652-c03a9700-0d88-11ea-99be-72f6f2b6fbf0.png)

**Comment by michelleangela** [comment]
If the `compilerPath` is set, IntelliSense will try to query its related system include paths. But if it is not set, then IntelliSense will use the include paths defined under `includePath`. It looks like the desired header file is under the `${workspaceFolder}` path which is already set to recursively include folders for `includePath`, so IntelliSense should only include the header files from that path. It could be adding the include from Windows kit because some other configuration setting is not getting set correctly.

The correct way, though, is to set `compilerPath` to `""` (that is let the IntelliSense know to not query a compiler for system includes). And specific the desired include paths under `includePath`. 

Can you share a log from running `C/C++: Log Diagnostics` with the following configuration? I added  setting `limitSymbolsToIncludedHeaders` to true even though the default is true.
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/tricore/inc"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "_TASKING_C_TRICORE_"
            ],
            "compilerPath": "",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "browse": {
                "limitSymbolsToIncludedHeaders": true
            }
        }
    ],
    "version": 4
}

**Comment by michelleangela** [comment]
Can you also run the command `C/C++: Reset IntelliSense Database` after changing the configuration?

**Comment by h2s0109** [comment]
After `C/C++: Reset IntelliSense Database' problem solved. Thanks for your help
