### ISSUE TITLE
Remote-SSH: Syntax Highlighting/Coloring Problems

### ISSUE THREAD

**Issue by DeadRabbits307** [microsoft/vscode-cpptools#4652]
**Describe the bug**
- OS and Version: remote OS: manjaro (Linux 4.19.80), local OS: Windows 7
- VS Code Version: remote OS: 1.39.2, local OS: 1.40.1
- C/C++ Extension Version: 0.26.1
- remote-SSH: 0.47.2

**To Reproduce**
Syntax Highlighting/Coloring is not working using the remote-SSH extension. 

directly using VS Code on the remote-OS:
![remote-os](https://user-images.githubusercontent.com/33861896/69413875-f2f57880-0d11-11ea-92a5-26b575acfd81.PNG)

local-OS using remote-SSH:
![local-os](https://user-images.githubusercontent.com/33861896/69413926-056fb200-0d12-11ea-98ce-25b679553d3c.PNG)

Could this maybe be related with [3942](https://github.com/microsoft/vscode-cpptools/issues/3942)?

**Comment by sean-mcmanus** [comment]
Yes, it's the same issue as https://github.com/microsoft/vscode-cpptools/issues/3942 .
