### ISSUE TITLE
Remove "-include" arguments when querying gcc/clang

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4655]
Originally reported in the thread https://github.com/microsoft/vscode-cpptools/issues/4614 .

Using -include can cause the querying to fail.

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
