### ISSUE TITLE
No console output while debugging a C++ library on Linux

### ISSUE THREAD

**Issue by chandangreddy** [microsoft/vscode-cpptools#466]
Hi, 
Is there an option that I need to set to see the stderr and stdout in the debug console?
By default, I am not seeing any output in the debug console.

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|lualinter|dcr30|1.0.3|
|python|donjayamanne|0.5.0|
|cpptools|ms-vscode|0.10.0|
|ravi-debug|ravilang|0.0.22|
|vim|vscodevim|0.5.2|

Thanks

**Comment by pieandcakes** [comment]
@chandangreddy it should be in the external console if you enable `"externalConsole": true` in your `launch.json`

**Comment by chandangreddy** [comment]
I had set "externalConsole" to false, I do not see any output. I tried with the "externalConsole": true, I see an external terminal but no output at all. Right now I am redirecting the output to log file, which is correctly populated.

**Comment by pieandcakes** [comment]
@chandangreddy So you aren't seeing stdout in either the external console or the DebugConsole? 

I can't seem to repro this on Ubuntu 16.04. Can you provide a code snippet and possibly which specific Linux distro you are running on?

**Comment by anyflow** [comment]
Same issues here.

It works on Mac, but does not on linux(14.04)

Changing externalConsole values doesn't make any difference.

Here goes my launch.json.

`{
  "version": "0.2.0",
  "configurations": [

    {
      "name": "C++",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceRoot}/cpp/bin/${fileBasenameNoExtension}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceRoot}",
      "environment": [],
      "externalConsole": false,
      "logging": {
        "programOutput": true
      },
      "linux": {
        "MIMode": "gdb"
      },
      "osx": {
        "MIMode": "lldb"
      },
      "windows": {
        "MIMode": "gdb"
      }
    },`

**Comment by pieandcakes** [comment]
Can either of you post a code snippet? I can't seem to duplicate this with `printf` or `cout`.

**Comment by arthurspa** [comment]
Same problem here.

I'm running Ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

```

VS Code version:
```
Version 1.14.1
Commit 2648980a697a4c8fb5777dcfb2ab110cec8a2f58
Date 2017-07-13T19:12:01.887Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

My launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [
                {
                    "name": "IS_DEBUG",
                    "value": true
                }
            ],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "Build C++"
        }
    ]
}
```

**I can't see any output in console that is opened when debugging.**

**Comment by arthurspa** [comment]
It seems that the output is buffered until it finds a newline character.

For example, If I test the following code:
```
#include <iostream>

using namespace std;

int main()
{
	cout << 5 ;
	cout << " Teste 1";
	printf("%s", " test 3");

	return 0;
}
```
the output is blank.

However, If I add a `cout << endl;` after line `printf("%s", " test 3");`, the output will be:
```
5 Teste 1 test 3

```

**Comment by codeJRV** [comment]
Is there any workarounds to this?

**Comment by pieandcakes** [comment]
@codeJRV As @arthurspa metions above, it looks like adding a newline will print it.
