### ISSUE TITLE
can't stop at the breakpoint (sorry to reopen)

### ISSUE THREAD

**Issue by wangbo223** [microsoft/vscode-cpptools#4660]
Type: Debugger

**Describe the bug**
- OS and Version: macOS Catalina 10.15.1
- VS Code Version: 1.30.1
- C/C++ Extension Version: 0.26.2-insiders3
- Other extensions you installed (and if the issue persists after disabling them): Python 2019.10
- A clear and concise description of what the bug is.

Learning C++ extension on VSCode by following this website: https://code.visualstudio.com/docs/cpp/config-clang-mac

However, couldn't get the breakpoint hit (none of the break points) in the debugger.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

Under working directory: there are 
.vscode/c_cpp_properties.json
.vscode/launch.json
.vscode/tasks..json
test.cpp

test.cpp:
`#include <iostream>

using namespace std;

int main()
{
    cout << "Hello World!" << endl;  // break point here
    return 0;
}`

c_cpp_properties:
`{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "${default}"
        }
    ],
    "version": 4
}`

launch.json:
`{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "(lldb) Launch",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder}/test",
        "args": [],
        "stopAtEntry": true,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false,
        "MIMode": "lldb",
        "logging": {
          "trace": true,
          "traceResponse": true,
          "engineLogging": true
        }
      }
    ]
  }`

tasks.json:
`{
    "version": "2.0.0",
    "tasks": [
      {
        "label": "Build with Clang",
        "type": "shell",
        "command": "clang++",
        "args": [ 
          "-std=c++17",
          "-stdlib=libc++",
          "test.cpp",
          "-o",
          "test",
          "--debug"
         ],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]
  }`

1. Press Cmd + Shift + B to build the binary ./test
2. Press F5 to invoke the debugger

Terminal Output is:
`Terminal will be reused by tasks, press any key to close it.

> Executing task: clang++ -std=c++17 -stdlib=libc++ test.cpp -o test --debug <`

Debug Console Output is:
`--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (88) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'\n"},"seq":2}
1: (88) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (96) LaunchOptions  ExePath='/Users/bwang/dev/c/test'\n"},"seq":4}
1: (96) LaunchOptions  ExePath='/Users/bwang/dev/c/test'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (96) LaunchOptions  WorkingDirectory='/Users/bwang/dev/c'\n"},"seq":6}
1: (96) LaunchOptions  WorkingDirectory='/Users/bwang/dev/c'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (96) LaunchOptions  ExeArguments=''\n"},"seq":8}
1: (96) LaunchOptions  ExeArguments=''
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (96) LaunchOptions  MIMode='lldb'\n"},"seq":10}
1: (96) LaunchOptions  MIMode='lldb'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (96) LaunchOptions  MIDebuggerPath='/Users/bwang/.vscode/extensions/ms-vscode.cpptools-0.26.2-insiders3/debugAdapters/lldb/bin/lldb-mi'\n"},"seq":12}
1: (96) LaunchOptions  MIDebuggerPath='/Users/bwang/.vscode/extensions/ms-vscode.cpptools-0.26.2-insiders3/debugAdapters/lldb/bin/lldb-mi'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (96) LaunchOptions  WaitDynamicLibLoad='false'\n"},"seq":14}
1: (96) LaunchOptions  WaitDynamicLibLoad='false'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (96) LaunchOptions>\n"},"seq":16}
1: (96) LaunchOptions>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (97) LaunchOptions</LocalLaunchOptions>\n"},"seq":18}
1: (97) LaunchOptions</LocalLaunchOptions>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (172) Starting: \"/Users/bwang/.vscode/extensions/ms-vscode.cpptools-0.26.2-insiders3/debugAdapters/lldb/bin/lldb-mi\" --interpreter=mi\n"},"seq":20}
1: (172) Starting: "/Users/bwang/.vscode/extensions/ms-vscode.cpptools-0.26.2-insiders3/debugAdapters/lldb/bin/lldb-mi" --interpreter=mi
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (183) DebuggerPid=21168\n"},"seq":22}
1: (183) DebuggerPid=21168
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (275) ->(gdb)\n"},"seq":24}
1: (275) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (284) <-1001-gdb-set auto-solib-add on\n"},"seq":26}
1: (284) <-1001-gdb-set auto-solib-add on
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (284) ->1001^done\n"},"seq":28}
1: (284) ->1001^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (284) ->(gdb)\n"},"seq":30}
1: (284) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (285) 1001: elapsed time 2\n"},"seq":32}
1: (285) 1001: elapsed time 2
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (286) <-1002-gdb-set solib-search-path \"/Users/bwang/dev/c:\"\n"},"seq":34}
1: (286) <-1002-gdb-set solib-search-path "/Users/bwang/dev/c:"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (286) ->1002^done\n"},"seq":36}
1: (286) ->1002^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (286) 1002: elapsed time 0\n"},"seq":38}
1: (286) 1002: elapsed time 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (286) <-1003-environment-cd /Users/bwang/dev/c\n"},"seq":40}
1: (286) <-1003-environment-cd /Users/bwang/dev/c
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (286) ->(gdb)\n"},"seq":42}
1: (286) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (286) ->1003^done,path=\"/Users/bwang/dev/c\"\n"},"seq":44}
1: (286) ->1003^done,path="/Users/bwang/dev/c"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (287) ->(gdb)\n"},"seq":46}
1: (287) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (288) 1003: elapsed time 1\n"},"seq":48}
1: (288) 1003: elapsed time 1
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (288) <-1004-file-exec-and-symbols /Users/bwang/dev/c/test\n"},"seq":50}
1: (288) <-1004-file-exec-and-symbols /Users/bwang/dev/c/test
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (357) ->1004^done\n"},"seq":52}
1: (357) ->1004^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (357) ->(gdb)\n"},"seq":54}
1: (357) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (357) 1004: elapsed time 68\n"},"seq":56}
1: (357) 1004: elapsed time 68
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (358) ->=library-loaded,id=\"/Users/bwang/dev/c/test\",target-name=\"/Users/bwang/dev/c/test\",host-name=\"/Users/bwang/dev/c/test\",symbols-loaded=\"1\",symbols-path=\"/System/Volumes/Data/Users/bwang/dev/c/test.dSYM/Contents/Resources/DWARF/test\",loaded_addr=\"-\",size=\"8192\"\n"},"seq":58}
1: (358) ->=library-loaded,id="/Users/bwang/dev/c/test",target-name="/Users/bwang/dev/c/test",host-name="/Users/bwang/dev/c/test",symbols-loaded="1",symbols-path="/System/Volumes/Data/Users/bwang/dev/c/test.dSYM/Contents/Resources/DWARF/test",loaded_addr="-",size="8192"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (358) <-1005-interpreter-exec console \"platform status\"\n"},"seq":60}
1: (358) <-1005-interpreter-exec console "platform status"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (358) ->  Platform: host\n"},"seq":62}
1: (358) ->  Platform: host
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (358) ->    Triple: x86_64h-apple-macosx\n"},"seq":64}
1: (358) ->    Triple: x86_64h-apple-macosx
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (359) ->OS Version: 10.15.1 (19B88)\n"},"seq":66}
1: (359) ->OS Version: 10.15.1 (19B88)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (359) ->    Kernel: Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64\n"},"seq":68}
1: (359) ->    Kernel: Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (359) ->  Hostname: 127.0.0.1\n"},"seq":70}
1: (359) ->  Hostname: 127.0.0.1
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (359) ->WorkingDir: /Users/bwang/dev/c\n"},"seq":72}
1: (359) ->WorkingDir: /Users/bwang/dev/c
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (359) ->1005^done\n"},"seq":74}
1: (359) ->1005^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (359) ->(gdb)\n"},"seq":76}
1: (359) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (360) 1005: elapsed time 1\n"},"seq":78}
1: (360) 1005: elapsed time 1
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (361) <-1006-break-insert -f on main\n"},"seq":80}
1: (361) <-1006-break-insert -f on main
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (362) ->1006^done,bkpt={number=\"1\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x00000001000011c6\",func=\"main\",file=\"test.cpp\",fullname=\"/Users/bwang/dev/c/test.cpp\",line=\"7\",pending=[\"main\"],times=\"0\",original-location=\"main\"}\n"},"seq":82}
1: (362) ->1006^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x00000001000011c6",func="main",file="test.cpp",fullname="/Users/bwang/dev/c/test.cpp",line="7",pending=["main"],times="0",original-location="main"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (362) ->(gdb)\n"},"seq":84}
1: (362) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (362) ->=breakpoint-modified,bkpt={number=\"1\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x00000001000011c6\",func=\"main\",file=\"test.cpp\",fullname=\"/Users/bwang/dev/c/test.cpp\",line=\"7\",pending=[\"main\"],times=\"0\",original-location=\"main\"}\n"},"seq":86}
1: (362) ->=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x00000001000011c6",func="main",file="test.cpp",fullname="/Users/bwang/dev/c/test.cpp",line="7",pending=["main"],times="0",original-location="main"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (362) ->(gdb)\n"},"seq":88}
1: (362) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (363) 1006: elapsed time 2\n"},"seq":90}
1: (363) 1006: elapsed time 2
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (367) Send Event AD7EngineCreateEvent\n"},"seq":92}
1: (367) Send Event AD7EngineCreateEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (369) Send Event AD7ProgramCreateEvent\n"},"seq":94}
1: (369) Send Event AD7ProgramCreateEvent
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.61023.1","VS.Diagnostics.Debugger.HostVersion":"14.0.61023.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.Duration":314,"VS.Diagnostics.Debugger.Launch.IsCoreDump":false,"VS.Diagnostics.Debugger.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.SourceFileMappings":0,"VS.Diagnostics.Debugger.MIMode":null}},"seq":96}
--> R (launch-2): {"type":"response","request_seq":2,"success":true,"command":"launch","body":{},"seq":98}
--> E (initialized): {"type":"event","event":"initialized","body":{},"seq":100}
<--   C (setBreakpoints-3): {"command":"setBreakpoints","arguments":{"source":{"name":"test.cpp","path":"/Users/bwang/dev/c/test.cpp"},"lines":[7],"breakpoints":[{"line":7}],"sourceModified":false},"type":"request","seq":3}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (415) <-1007-break-insert -f on test.cpp:7\n"},"seq":103}
1: (415) <-1007-break-insert -f on test.cpp:7
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (415) ->1007^done,bkpt={number=\"2\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x00000001000011c6\",func=\"main\",file=\"test.cpp\",fullname=\"/Users/bwang/dev/c/test.cpp\",line=\"7\",pending=[\"test.cpp:7\"],times=\"0\",original-location=\"test.cpp:7\"}\n"},"seq":105}
1: (415) ->1007^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x00000001000011c6",func="main",file="test.cpp",fullname="/Users/bwang/dev/c/test.cpp",line="7",pending=["test.cpp:7"],times="0",original-location="test.cpp:7"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (415) ->(gdb)\n"},"seq":107}
1: (415) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (415) ->=breakpoint-modified,bkpt={number=\"2\",type=\"breakpoint\",disp=\"keep\",enabled=\"y\",addr=\"0x00000001000011c6\",func=\"main\",file=\"test.cpp\",fullname=\"/Users/bwang/dev/c/test.cpp\",line=\"7\",pending=[\"test.cpp:7\"],times=\"0\",original-location=\"test.cpp:7\"}\n"},"seq":109}
1: (415) ->=breakpoint-modified,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x00000001000011c6",func="main",file="test.cpp",fullname="/Users/bwang/dev/c/test.cpp",line="7",pending=["test.cpp:7"],times="0",original-location="test.cpp:7"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (415) ->(gdb)\n"},"seq":111}
1: (415) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (415) 1007: elapsed time 0\n"},"seq":113}
1: (415) 1007: elapsed time 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (420) Send Event AD7BreakpointBoundEvent\n"},"seq":115}
1: (420) Send Event AD7BreakpointBoundEvent
--> R (setBreakpoints-3): {"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"id":1,"verified":true,"line":7}]},"seq":117}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":true,"line":7}},"seq":119}
<--   C (setFunctionBreakpoints-4): {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":4}
--> R (setFunctionBreakpoints-4): {"type":"response","request_seq":4,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]},"seq":122}
<--   C (setExceptionBreakpoints-5): {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":5}
--> R (setExceptionBreakpoints-5): {"type":"response","request_seq":5,"success":true,"command":"setExceptionBreakpoints","body":{},"seq":125}
<--   C (configurationDone-6): {"command":"configurationDone","type":"request","seq":6}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (442) Send Event AD7LoadCompleteEvent\n"},"seq":129}
1: (442) Send Event AD7LoadCompleteEvent
--> R (configurationDone-6): {"type":"response","request_seq":6,"success":true,"command":"configurationDone","body":{},"seq":128}
<--   C (threads-7): {"command":"threads","type":"request","seq":7}
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"Warning: Debuggee TargetArchitecture not detected, assuming x86_64.\n"},"seq":133}
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (444) <-1008-exec-run\n"},"seq":136}
1: (444) <-1008-exec-run
--> R (threads-7): {"type":"response","request_seq":7,"success":true,"command":"threads","body":{"threads":[]},"seq":135}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (743) ->1008^running\n"},"seq":139}
1: (743) ->1008^running
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (743) ->=thread-group-started,id=\"i1\",pid=\"21169\"\n"},"seq":141}
1: (743) ->=thread-group-started,id="i1",pid="21169"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (743) 1008: elapsed time 298\n"},"seq":143}
1: (743) 1008: elapsed time 298
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (743) ->(gdb)\n"},"seq":145}
1: (743) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (744) ->=thread-created,id=\"1\",group-id=\"i1\"\n"},"seq":147}
1: (744) ->=thread-created,id="1",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (744) ->=thread-selected,id=\"1\"\n"},"seq":149}
1: (744) ->=thread-selected,id="1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (744) ->(gdb)\n"},"seq":151}
1: (744) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (744) ->*running,thread-id=\"all\"\n"},"seq":153}
1: (744) ->*running,thread-id="all"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (744) ->(gdb)\n"},"seq":155}
1: (744) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (745) ->@\"Hello World!\\r\\n\"\n"},"seq":157}
1: (745) ->@"Hello World!\r\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (745) ->(gdb)\n"},"seq":159}
1: (745) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (745) ->=thread-exited,id=\"1\",group-id=\"i1\"\n"},"seq":161}
1: (745) ->=thread-exited,id="1",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (745) ->=thread-group-exited,id=\"i1\",exit-code=\"0\"\n"},"seq":163}
1: (745) ->=thread-group-exited,id="i1",exit-code="0"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (745) ->*stopped,reason=\"exited-normally\"\n"},"seq":165}
1: (745) ->*stopped,reason="exited-normally"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (745) ->(gdb)\n"},"seq":167}
1: (745) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (746) <-1009-thread-info 1\n"},"seq":169}
1: (746) <-1009-thread-info 1
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"=thread-selected,id=\"1\"\n"},"seq":171}
=thread-selected,id="1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (747) ->1009^done,threads=[{id=\"1\",target-id=\"Thread 1\",frame={level=\"0\",addr=\"0xffffffffffffffff\",func=\"??\",args=[],file=\"??\",fullname=\"??\",line=\"0\"},state=\"running\"}]\n"},"seq":173}
1: (747) ->1009^done,threads=[{id="1",target-id="Thread 1",frame={level="0",addr="0xffffffffffffffff",func="??",args=[],file="??",fullname="??",line="0"},state="running"}]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (747) ->(gdb)\n"},"seq":175}
1: (747) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"@\"Hello World!\\r\\n\"\n"},"seq":177}
@"Hello World!\r\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (750) 1009: elapsed time 3\n"},"seq":179}
1: (750) 1009: elapsed time 3
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (751) Send Event AD7ProcessInfoUpdatedEvent\n"},"seq":181}
1: (751) Send Event AD7ProcessInfoUpdatedEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (751) Send Event AD7ThreadCreateEvent\n"},"seq":183}
1: (751) Send Event AD7ThreadCreateEvent
--> E (thread): {"type":"event","event":"thread","body":{"reason":"started","threadId":1},"seq":185}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (755) <--gdb-exit\n"},"seq":187}
1: (755) <--gdb-exit
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (755) ->^exit\n"},"seq":189}
1: (755) ->^exit
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (755) ->=thread-group-exited,id=\"i1\"\n"},"seq":191}
1: (755) ->=thread-group-exited,id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (755) ->(gdb)\n"},"seq":193}
1: (755) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (756) ->\n"},"seq":195}
1: (756) ->
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (756) ->\n"},"seq":197}
1: (756) ->
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (757) <-logout\n"},"seq":199}
1: (757) <-logout
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (760) Send Event AD7ProgramDestroyEvent\n"},"seq":201}
1: (760) Send Event AD7ProgramDestroyEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"The program '/Users/bwang/dev/c/test' has exited with code 0 (0x00000000).\r\n\n"},"seq":203}
The program '/Users/bwang/dev/c/test' has exited with code 0 (0x00000000).

--> E (exited): {"type":"event","event":"exited","body":{"exitCode":0},"seq":205}
--> E (terminated): {"type":"event","event":"terminated","body":{},"seq":207}
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.61023.1","VS.Diagnostics.Debugger.HostVersion":"14.0.61023.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":0}},"seq":209}
<--   C (disconnect-8): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":8}
--> R (disconnect-8): {"type":"response","request_seq":8,"success":true,"command":"disconnect","body":{},"seq":212}
`

Not sure which step is wrong from https://code.visualstudio.com/docs/cpp/config-clang-mac, however my break point is not hit by all means.

I've also tried "-g" flag in the tasks -> args, but still no luck

Please help

Thank you

**Comment by mmlogin** [comment]
The same with
* OS and Version: macOS Catalina 10.15.1
* VS Code Version: **1.40.2**
* C/C++ Extension Version: 0.26.2-insiders3

**Comment by pieandcakes** [comment]
This is already tracked in #3829.
