### ISSUE TITLE
Conflict local Header files with Windows kit's header file

### ISSUE THREAD

**Issue by madoodia** [microsoft/vscode-cpptools#4665]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.40.1
- C/C++ Extension Version: 0.26.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I have a header file beside my main.cpp named **rend.h**
this **rend.h** is a header file in windows 10 kit named **REND.h**
when I include mine, vscode can not detect that I mean the local and show me both as **multiple files** (I know case sensitivity does not work in windows)
and show **Squiggles** underneeth its content like functions or clases.
and **F12** doesn't direct me to my local file.

I include the header file with **""** and it should know about my local and should search first in my local then in global directories
`#include "rend.h"`

this is my config in **c_cpp_properties.json**:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}/**",
                ]
            },
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe",
            "cppStandard": "c++11",
            "intelliSenseMode": "${default}",
            "cStandard": "c11"
        }
    ],
    "version": 4
}
```
what should I do to just have my own header files when i include them with `""`?
Appreciated!

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue. I'm seeing "rend.h" and "REND.h" in the completion list and no squiggles.

Can you run the C/C++: Log Diagnostics command and verify the includePath is as expected?

When you do "Go to Def" on the header, you should see both files appear in the results (local and Windows SDK files).

**Comment by madoodia** [comment]
Thanks (actually I wanted to ask my question, not as VSCode Issue)
But Squiggles is on elements of the header files like classes or functions that you use in main.cpp

**Log Diagnostics** is a nice feature, I was looking for it, Thanks

btw this is the log for order:
```
C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
D:\REND\SRC
```
and don't know why  my local is at the end of the list!?
I think if I can put my local on top it can detect my `rend.h` instead `REND.h` of `C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM` (maybe I'm wrong)

- yes as I said I see multiple file

need more help
thanks again

**Comment by sean-mcmanus** [comment]
Our IntelliSense engine automatically adds the "current directory" to the top (not shown in the logging) when the `#include ""` is used, i.e. so you wouldn't even need "D:\REND\SRC" in your includePath if files at that location reference each other.

The Go to Def on the "#include" doesn't use IntelliSense path info, so it's expected to show multiple file results and doesn't actually open the file that is actually used by IntelliSense (there's another open issue on that).

With the Log Diagnostics command -- what do you see rend.h or REND.h being used in the TU -- the red squiggles could be caused by the wrong file being included.

**Comment by madoodia** [comment]
Exactly this is why I wonder that `""` should first look at my local, It is not `<>`

so what should I do?

**Comment by sean-mcmanus** [comment]
I'm not able to repro the problem you're describing, but it seems like there could be a problem with our recursive includes feature. If you change the `${workspaceFolder}/**` to `${workspaceFolder}` then you should see the `${workspaceFolder}` appear before the system includePaths.

**Comment by sean-mcmanus** [comment]
Also, you may want to try https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.2-insiders3 (which what we plan to ship next week). Other users have reported it fixed some similar issues.

**Comment by madoodia** [comment]
> If you change the ${workspaceFolder}/** to ${workspaceFolder} then you should see the ${workspaceFolder} appear before the system includePaths.

yes it went on top, but GoToDef still shows me multiple files. my local rend.h should be detected automatically , I don't understand.
I think this is a bug in VSCode, I hope it solve in the next release

thanks though

**Comment by sean-mcmanus** [comment]
The Go to Def issue is https://github.com/microsoft/vscode-cpptools/issues/2564 .

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
