### ISSUE TITLE
configuring defines doesnt work with makefile projects

### ISSUE THREAD

**Issue by Aetherbase** [microsoft/vscode-cpptools#4669]
**Type: LanguageService**

**Description**
- OS and Version: Windows 10 Build 19103
- VS Code Version: 1.40.1
- C/C++ Extension Version:0.26.1
- Using defines in configurations doesnt work. Even after reloading workspace, vscode,etc. This creates include errors and many definitions/declaration functions from the extension doesnt work. even if make is successful.

**To Reproduce**

1. Create a simple makefile project
2. pass arguments to define macros on the makefile
3.add the defined macros in "defines"
4.reload the vscode and the workspace.
5.Open the source code.
6. See the error.

**Expected behavior**
After defines is successful, there should be no include error and all definations must work properly.

**Comment by Colengms** [comment]
Hi @Aetherbase .  The C/C++ Extension does not currently have direct support for makefiles.  In step #3, are you referring to adding your defines to c_cpp_properties.json ?  Can you provide the contents of your c_cpp_properties.json?  To fully configure the extension, you will also need to specify compilerPath and includePath in c_cpp_properties.json.

**Comment by Aetherbase** [comment]
>  In step #3, are you referring to adding your defines to c_cpp_properties.json ? 

Hi @Colengms . Yes, I am referring to adding defines to c_cpp_properties.json.
>  Can you provide the contents of your c_cpp_properties.json?

Yes. and also I have specified  compilerPath and includePath in c_cpp_properties.json as seen below.
***
{
    "configurations": [
        {
            "name": "mingw32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "CONF_LANGUAGE = c"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:\\MinGW\\mingw32\\mingw32\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x86"
        }
    ],
    "version": 4
}`
***
Even after reloading my project, the macro is shown as undefined and all dependent header files dont work.The project compiles and runs properly regardless.

**Comment by Aetherbase** [comment]
I need to define the macro `CONF_LANGUAGE =c` using defines, but it is not working. It works during compilation because i have passed it as an argument using makefile.

**Comment by sean-mcmanus** [comment]
The spaces around the "=" are not valid. Not sure if that is "by design" or something we should fix. Does it work for you after removing the spaces around the "="?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
