### ISSUE TITLE
[Internal] The content under setting "C_Cpp:Intelli Sense Cache Path" is not localized 

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode-cpptools#4672]
Repro steps:
1. Open VSCode
2. Install Chinese (Simplified) Language Pack from View->extension, and configure display language to zh-cn (De, Ja and Fr are OK)
3. Press "Ctrl+," to open the setting UI page
4. Switch to the Extension->C/C++ node
5. Scroll to the bottom of the page
6. Check the content under setting "C_Cpp:Intelli Sense Cache Path"
![image](https://user-images.githubusercontent.com/29274719/69792717-17fe5580-1202-11ea-9b09-6952280b30c9.png)

**Comment by Colengms** [comment]
This has been addressed by the follow 2 PRs: https://github.com/microsoft/vscode-cpptools/pull/4641 , https://github.com/microsoft/vscode-cpptools/pull/4634

Note that whenever we change an English string the loc process results in that English string being set for all languages until the Loc team (re)localizes the string.  The turn-around time is usually 1 week.
