### ISSUE TITLE
[Internal] Build error log is not localized

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode-cpptools#4673]
1. Opening VSCode. according to the toturial " https://code.visualstudio.com/docs/cpp/config-msvc " to create helloworld project 
2. Install Chinese (Simplified) Language Pack from View->extension, and configure display language to zh-cn
3. Open helloworld.cpp and add a wrong code line in main function, like "int test=" 
4. Build the project

**Expected:**
The build log was localized

**Actual:**
The build log are not localized
![image](https://user-images.githubusercontent.com/29274719/69796930-dbcef300-1209-11ea-8fc9-4a689e8888e1.png)

**Comment by Colengms** [comment]
The C/C++ Extension provides language services and debug support, but does not provide a build system or a compiler.  The error messages in the screenshot are coming from cl.exe, which part of Visual Studio, also installed on the system.  Changing the language of errors output by cl.exe would be specific to Visual Studio.  (I believe this can be changed by setting the VSLANG environment variable).
