### ISSUE TITLE
format doesn't work on wsl

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#4674]
Issue Type: <b>Bug</b>

I used to use Alt+Shift+F to format some c++ code on Windows  Subsystem for Linux(wsl). The format feature worked fine when using on Ubuntu 18.04.
Today I upgrade it to Ubuntu19.10, but  it didn't work any more, with a message "no cpp formatting tool installed"(similar to this). Then I try debian 10.2 now. And it still don't work. Here is the erro output:
Formatting failed:
/home/x/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/bin/../LLVM/bin/clang-format -style={ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4 } -fallback-style=LLVM -sort-includes=0 -assume-filename=/home/x/OSExp/processManange.cpp
/home/x/.vscode-server/extensions/ms-vscode.cpptools-0.26.1/bin/../LLVM/bin/clang-format: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
  

Extension version: 0.26.1
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (10.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|Memory (System)|15.81GB (10.88GB free)|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
We're tracking this issue with https://github.com/microsoft/vscode-cpptools/issues/3174 , which has some workarounds described.
