### ISSUE TITLE
[Linux] Can't get the IntelliSense, autocomplete etc. to work

### ISSUE THREAD

**Issue by IdoiaReina** [microsoft/vscode-cpptools#4675]
Hello everyone, 

- OS and Version: Ubuntu 18.04.3 LTS
- VS Code Version: 1.40.2
- C/C++ Extension Version: 0.26.1
- No other extension is installed

Step to reproduce :
- Install VsCode
- Create a new folder, a new file .cpp, write a simple main

No intelliSense is showing.
the C/C++ extensions command (such as C/C++ : Log Diagnostics) are not doing anything / opening anything.

Can someone help me ? Thanks !

**Comment by Colengms** [comment]
Hi @IdoiaReina .  Could you try adding the following to your settings `"C_Cpp.loggingLevel": "Debug",`.  (Use `Preferences: Open Settings (JSON)` to open settings).

That should output diagnostic information to the C/C++ channel.  Could you include that info here?

**Comment by IdoiaReina** [comment]
Thank you for your answer !
Here is the log : 

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)' (8599 KB)  Done!
Downloading package 'ClangFormat (Linux / x86_64)' (812 KB)  Done!
Downloading package 'Mono Framework Assemblies' (5368 KB)  Done!
Downloading package 'Mono Runtime (Linux / x86_64)' (1862 KB)  Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Installing package 'ClangFormat (Linux / x86_64)'
Installing package 'Mono Framework Assemblies'
Installing package 'Mono Runtime (Linux / x86_64)'

Finished installing dependencies

initialized
workspace/didChangeConfiguration
IntelliSense Engine = Default.
Autocomplete is enabled.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/.vscode
Attempting to get defaults from compiler found on the machine: '/home/idoia/bin/cpp'
```

**Comment by Colengms** [comment]
It looks like there is an issue trying to probe the compile at /home/idoia/bin/cpp .  (I assume there is not more information output after a long delay?)

What type of compiler is at /home/idoia/bin/cpp ?  If that is not actually a compiler, perhaps this path was added to c_cpp_properties.json and is incorrect?

**Comment by IdoiaReina** [comment]
Ooh thank you for pointing that out !
"cpp" was just a little script that has nothing to do with any of this. I renamed it and now the extension works. Thank you ! :)
