### ISSUE TITLE
inno_update.exe

### ISSUE THREAD

**Issue by Ildomar** [microsoft/vscode-cpptools#4676]
Issue Type: <b>Bug</b>

Após atualização fica aparecendo uma mensagem com código (0xc000007b).
Não sei com resolver.

Extension version: 0.26.1
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G (4 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (5.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
What did you update? Does your update issue occur when you uninstall our C/C++ extension, i.e. is this a VS Code issue?

**Comment by bobbrow** [comment]
Nao conhecemos o `inno_update.exe`.  Nao achemos que isso vem da nossa extencao.   (I apologize for my bad Portuguese in advance 😄)
