### ISSUE TITLE
[Internal] The default keyboard shortcut for "Focus Breadcrumbs" is wrong (Ctrl+Shift+<)

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode-cpptools#4678]
1. Install VSCode in a Linux machine 
2. Use VSCode to open a folder containing a cpp file with some code 
3. Press F1 or Ctrl+ Shift+ P to open the Command Palette
4. Search "Focus Breadcrumbs"

**Expected:**
The keyboard should be Ctrl+ Shift+.
![image](https://user-images.githubusercontent.com/29274719/69851887-c4e9d880-12bd-11ea-9a2a-efc16a142f66.png)

**Actual:**
The keyboard is Ctrl+ Shift+ < and the keyboard doesn't work
![image](https://user-images.githubusercontent.com/29274719/69851708-4a20bd80-12bd-11ea-8721-d7e95e9ba05c.png)

**Comment by Colengms** [comment]
Hi @Wanye1062271859 .  `Ctrl + Shift + .` is working for me.

Are you using a non-US keyboard?  Perhaps there Is an issue with VS Code not displaying the correct character mapping when shifted characters are not where expected?  (On my keyboard, "." and ">" are the same key).

The "Focus Breadcrumbs" command, and the display of shortcuts in the palette menu, are not specific to the C/C++ Extension.  You may want to follow up with an issue against [VS Code](https://github.com/microsoft/vscode).

**Comment by Wanye1062271859** [comment]
Hi Colengms,
You seem to have misunderstood my question,

1. The "." and ">" are also the same key in my keyboard. 
2. This shortcut show as "Ctrl+Shift+**<**" but not "Ctrl+Shift+**>**"  on the Linux machine. 
3. The shortcut display normally and can work properly on windows and mac machine.  

So this may just be a display issue on Linux machine.

**Comment by Colengms** [comment]
I opened an issue for this against VS Code, here: https://github.com/microsoft/vscode/issues/86133

**Comment by Wanye1062271859** [comment]
This issue doesn't reproduce in latest release version 1.41.1 now.
