### ISSUE TITLE
[Internal] An unexpected blue border show on the checkbox of "Browse: limit symbols to Include headers" in C/C++: Edit Configuration(UI) page

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode-cpptools#4679]
1. Install VSCode in Mac machine
2. Open VSCode, Install C/C++ extension 
3. Open Command Palette by pressing keyboard Ctrl+ Shift+ P
4. Search and open "C/C++:Edit Configurations(UI)"
5. Scroll to the bottom of the page
6. Expand the node "Advanced Settings"
7. Scroll to the item "Browse: limit symbols to Include headers"

**Expected:**
The checkbox on the content of the item show as below
![image](https://user-images.githubusercontent.com/29274719/69852616-b3a1cb80-12bf-11ea-92d9-92e0929c6c47.png)

**Actual:**
An unexpected blue border show on the checkbox
![image](https://user-images.githubusercontent.com/29274719/69852843-42aee380-12c0-11ea-81a9-589477db7ffa.png)

**Notes:**
The blue border only appears on mac machine, it is normal on Windows and Linux machine

**Comment by michelleangela** [comment]
The blue border indicates that the input object is the currently selected one when it is selected via tabbing.

On Windows, the selection is an orange border
![image](https://user-images.githubusercontent.com/38734287/69988964-83dd0880-14f7-11ea-9865-ec6c4e95d343.png)
