### ISSUE TITLE
 rename variable shows references in /tmp that was from previous show git history diff 

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-cpptools#4680]
**Type: LanguageService**
 

**Describe the bug**
- OS and Version: 
- VS Code Version:
```

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-70-generic
```
- C/C++ Extension Version: 0.26.1
 

**To Reproduce**
 
1. Go to git log and view some cpp file history diff from previous commit, then some previous versions of cpp file would be generated inside /tmp/
2. try to rename a variable in your workspace using F2
 

**Expected behavior**
Only variables inside your current workspace is shown in the rename dialog.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/1189869/69858262-97585b80-12cc-11ea-818a-077c594b7c60.png)

**Comment by sean-mcmanus** [comment]
Any open C/C++ files get added to our database ("by design"), but when you do a Reload Window, it should remove those "/tmp" files. You could add the "/tmp" directory to your files.exclude setting that should fix the issue. Is there a better solution you think we should implement?

**Comment by sean-mcmanus** [comment]
Maybe we could check the C_Cpp.workspaceSymbols setting for the "Just My Code" value and make Find All Refs (Rename) check that to filter out non-workspace files (or add some new setting for that).

**Comment by sean-mcmanus** [comment]
https://github.com/microsoft/vscode-cpptools/issues/4102 also sounds like it would cover this issue with the "workspace files" scope.
