### ISSUE TITLE
vscode cpptool not working on windows 1909

### ISSUE THREAD

**Issue by luckzylp** [microsoft/vscode-cpptools#4681]
I have been using the excellent software vscode. Since upgrading Windows 10 to version 1909, the issue of vscode cpptools-win32 opening the native code keeps prompting   No symbols found in document "xxxx.c"  . Try to disable all plugins and enable again, not work yet. Reinstalling vscode and cpptools-win32 does not fix the problem. I also tried to install windows system(1909), and then installed vscode and cpptools-win32, this problem still exists. cpptool version:0.26.1 is also have this issue. In particular, this is a must-have problem on my computer.
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

System information:
CPUs	Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
metal: disabled_off
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: enabled
skia_renderer: disabled_off
surface_control: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off
webgl: enabled
webgl2: enabled
Load (avg)	undefined
Memory (System)	7.95GB (5.04GB free)
Process Argv	
Screen Reader	no
VM	0%

My enable extensions:
Extension | Author (truncated) | Version
-- | -- | --
c-cpp-makefile-project | adr | 1.1.0
include-autocomplete | ajs | 0.0.4
c-cpp-project-generator | dan | 1.2.0
CppSnippets | har | 0.0.14
vscode-gnu-global | jay | 0.3.2
ccpp-extension-pack | Leo | 0.3.0
vscode-language-pack-zh-hans | MS- | 1.40.2
remote-containers | ms- | 0.83.1
remote-ssh | ms- | 0.47.2
remote-ssh-edit | ms- | 0.47.2
remote-wsl | ms- | 0.40.3
vscode-remote-extensionpack | ms- | 0.17.0
cpptools | ms- | 0.26.2-insiders3
c-cpp-definition-generator | rei | 0.0.2
vscode-icons | vsc | 9.6.0

**Comment by luckzylp** [comment]
Now I reinstalled win10 1903, vscode + cpptool still doesn't work. I really don't know where to deal with the problem. Can you help?
vscode version: 1.40.2
cpptool version: 0.26.1

**Comment by Colengms** [comment]
Hi @jay-zhou-yan .  Could you add a screenshot of the error?  I'm not able to find where in our code we output "No symbols found in document".  Are you sure this isn't coming from a different extension?

**Comment by luckzylp** [comment]
Thanks for your reply.After repeated attempts, using the insider version works fine on my work computer. It should be vscode 1.40.2 not working on my computer. Currently working environment: win10 (1903) + vscode insider (1.41.0) + cpptool (0.26.2-insiders3). I don't want to continue tangling this issue for the time being, and if there are still issues with subsequent stable versions, I will continue to investigate. Close it now.
