### ISSUE TITLE
C_Cpp clangformatter breaks with order of directories in workspace

### ISSUE THREAD

**Issue by phkeese** [microsoft/vscode-cpptools#4682]
Type: General

**Describe the bug**
- OS and Version: Windows 10 Home, WSL Ubuntu 18.04
- VS Code Version: 1.40.2 (User setup)
- C/C++ Extension Version: 0.26.1
- Other extensions: Gitlens
I have a workspace "C" with two folders, "caiman" and "pt1". I have VS Code configured to format on save and paste in the user settings. Both folders are git repositories.
When working on files in "caiman" alone, formatting works as expected. After formatting a file in "pt1", formatting no longer works on files in "caiman". After closing and reopening the workspace, formatting works again on files in "caiman" but will break again after formatting files in "pt1".
This also works in the reverse, when "caiman" is below "pt1".

**To Reproduce**
I have no taksks set up.
1. Create a workspace with two folder in it
2. Format a file in the lower folder of your workspace
3. Formatting in the higher folder no longer works

**Expected behavior**
I expected the formatter to work in both folders simultaniously.

**Comment by sean-mcmanus** [comment]
I'm in the middle of re-implementing our multi-root support, which should fix this...ETA isn't known yet, hopefully January.

**Comment by sean-mcmanus** [comment]
Our latest Insiders release has a new multi-root implementation (which fixes this bug): https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders. Please let us know if you find any multi-root-related bugs or regressions so we can prioritize fixing those for 0.27.0.
