### ISSUE TITLE
How to clear compiler error and use extension error squiggles 

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#4684]
vscode version: 1.40.2 on windows 10
extension: C/C++ IntelliSense, debugging, and code browsing. Version: 0.26.1

Assuming there're some code 
`int main()
{
  int a
  return 0;
}
`
And the c++ extension will notify me there's an error that is excepted an semicolon like the picture.

![Annotation 2019-11-30 010910](https://user-images.githubusercontent.com/41794415/69883269-5719cd00-130e-11ea-9bda-071d2b9066f2.png)

But when I compiled the code the error squiggles seems change to compiler's.

![Annotation 2019-11-30 005922](https://user-images.githubusercontent.com/41794415/69883055-677d7800-130d-11ea-975a-4a2a1d588c03.png)

How can I use the extension but not the compiler's

**Comment by Colengms** [comment]
Hi EizabethZeta .  What you are seeing is the result of a 'problem matcher'.  VS Code has one built in for MSVC (cl.exe).  The cpptools extension provides one for gcc.

How are you triggering the build in VS Code?  If you are using the CMake-tools extension, it looks like issueing `CMake: Clean` will clear compiler-generated problems.

It looks like there is an issue open against VS Code [here](https://github.com/microsoft/vscode/issues/66982) tracking the need for a way to clear stale problems from the list.
