### ISSUE TITLE
Debugging Error:Unable to open 'raise.c'

### ISSUE THREAD

**Issue by hamidddds** [microsoft/vscode-cpptools#4686]
- OS and Version: Ubuntu 18.4
- VS Code Version: Vscode 1.4
- C/C++ Extension Version:0.26

Hello, I have read all the articles about "raise.c" and none of them solved my problem, I just wrote a simple OpenCV code which captures webcam's frames. each time I run my code it frequently shows an error. the error message is:

> Unable to open 'raise.c': Unable to read file (Error: File not found (/build/glibc-OTsEL5/glibc-2.27/sysdeps/unix/sysv/linux/raise.c)).
 launch.json is:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```

and tasks.json is:

```
{
    "tasks": [
        {
            "type": "shell",
            "label": "g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}",
                "`pkg-config",
                 "--libs",
                  "--cflags", 
                  "opencv4`"

            ],
            "options": {
                "cwd": "/usr/bin"
            }
        }
    ],
    "version": "2.0.0"
}
```

So How can I solve this problem? is there any way to solve it. I am a beginner programmer .any ideas are welcome. thanks.

**Comment by eman291** [comment]
> OS and Version: Ubuntu 18.4
> VS Code Version: Vscode 1.4
> C/C++ Extension Version:0.26
> 
> Hello, I have read all the articles about "raise.c" and none of them solved my problem, I just wrote a simple OpenCV code which captures webcam's frames. each time I run my code it frequently shows an error. the error message is:
> 
> Unable to open 'raise.c': Unable to read file (Error: File not found (/build/glibc-OTsEL5/glibc-2.27/sysdeps/unix/sysv/linux/raise.c)).
> launch.json is:
> 
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "g++ build and debug active file",
>             "type": "cppdbg",
>             "request": "launch",
>             "program": "${fileDirname}/${fileBasenameNoExtension}",
>             "args": [],
>             "stopAtEntry": false,
>             "cwd": "${workspaceFolder}",
>             "environment": [],
>             "externalConsole": false,
>             "MIMode": "gdb",
>             "setupCommands": [
>                 {
>                     "description": "Enable pretty-printing for gdb",
>                     "text": "-enable-pretty-printing",
>                     "ignoreFailures": true
>                 }
>             ],
>             "preLaunchTask": "g++ build active file",
>             "miDebuggerPath": "/usr/bin/gdb"
>         }
>     ]
> }
> 
> and tasks.json is:
> {
>     "tasks": [
>         {
>             "type": "shell",
>             "label": "g++ build active file",
>             "command": "/usr/bin/g++",
>             "args": [
>                 "-g",
>                 "${file}",
>                 "-o",
>                 "${fileDirname}/${fileBasenameNoExtension}",
>                 "`pkg-config",
>                  "--libs",
>                   "--cflags", 
>                   "opencv4`"
> 
>             ],
>             "options": {
>                 "cwd": "/usr/bin"
>             }
>         }
>     ],
>     "version": "2.0.0"
> }
> 
> So How can I solve this problem? is there any way to solve it. I am a beginner programmer .any ideas are welcome. thanks.

**Comment by pieandcakes** [comment]
The debugger is stopping inside a library function that exists in the file `raise.c`. This is not your code so it gives you the error because it can't find the file. You can ignore that and change the stack frame you want to look at in the `Stacks` debug pane.

**Comment by krys-g** [comment]
I understand that the behaviour "makes sense", and yes, this is "by design". However, this is a **serious** usability issue. Every time I hit an assertion, I need to:
 - close the useless "raise.c" window, containing the error message.
 - navigate to the call stack
 - and select the right call stack frame

It should be clear that, when debugging an issue, the person debugging is interested in the assertion itself, not the internal implementation of the assertion mechanism.

And to be fair, gdb behaves exactly the same, though in that, it can be worked around by having the muscle memory to type e.g. `f 4` immediately to get to the interesting place.

I do not see a clean way to solve this usability -- perhaps an option to go by default to the first stack frame that maps to a file for which source is available?

**Comment by cumtchw** [comment]
this error is because you exec program run in error, when you modify the bug of you program ,then the mistake will correct.

**Comment by pktiuk** [comment]
> I do not see a clean way to solve this usability issue -- perhaps an option to go by default to the first stack frame that maps to a file for which source is available?

@krys-g  
I think it would be a great solution (I am also annoyed by this problem), but I think it should be reported rather as a new feature, not as a bug solution.
