### ISSUE TITLE
Can't disable CLangFormat

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode-cpptools#469]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|read-only-indicator|alefragnani|0.6.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|vscode-astyle|chiehyu|0.6.0|
|python|donjayamanne|0.5.6|
|EditorConfig|EditorConfig|0.3.4|
|copy-relative-path|enochc|0.1.1|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.1.2|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.3.10|
|cpptools|ms-vscode|0.10.0|
|copy-file-name|nemesv|1.0.0|
|vscode-clearcase|OpenNingia|1.4.2|
|vscode-icons|robertohuertasm|7.1.2|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.14.8|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.1.4|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

Steps to Reproduce:

1. Put "C_Cpp.formatting": "false", in File, Preferences, User Settings/
2. Select some text and use context menu to format selection. It still is formatted.

I'm trying Astyle (via https://marketplace.visualstudio.com/items?itemName=chiehyu.vscode-astyle) so need to disable CLangFormat. So far I don't seem to be disable it.

**Comment by sean-mcmanus** [comment]
The setting currently needs to be "disabled" not "false" (and a restart is required), although we intend to change it to a boolean format.enable so that it's consistent with the other VS Code settings and people don't get confused by this again.

**Comment by sean-mcmanus** [comment]
Let me know if you're still not able to get our formatting to be disabled (i.e. if we have some bug I'm not able to repro).

**Comment by BillDenton** [comment]
OK. Working now. Thanks. Would be better if a restart wasn't required - like other options.

**Comment by sean-mcmanus** [comment]
Requiring a restart was the quick/easy default implementation (many other VS Code "enable" settings also require a restart). Getting it to work without a restart would take more work/investigation.
