### ISSUE TITLE
[Feature Request] Config the env that start the language server.

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode-cpptools#4691]
Type: General

On my local environment, language server crash because I set the `LD_LIBRARY_PATH` env variable. To start the language server, I have to set `LD_LIBRARY_PATH` to be empty, but it may cause other problems. And now we can not set language server process env because to code here: https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/client.ts#L866

Could we have a  config that can set the LanguageServerOption env variables? It will help me a lot and if you accept this feature, I'd love to send a pull request to do this.

**Comment by sean-mcmanus** [comment]
A PR sounds fine to me, but I'm waiting to here from others on our team still. Were you thinking about adding a setting to package.json? What "scope" would the setting be? "machine" scope?

**Comment by bobbrow** [comment]
I believe we are tracking this request with #4759
