### ISSUE TITLE
Configuration detection wrong

### ISSUE THREAD

**Issue by tschoonj** [microsoft/vscode-cpptools#4693]
**Type: LanguageService**

**Describe the bug**
- OS and Version: RHEL 7.7
- VS Code Version: 1.40.2
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
  - autoconf 0.1.0
  - Docker 0.9.0
  - Modern Fortran 2.1.1
  - OpenCL 0.6.1
  - Singularity 0.4.0
  - Vim 1.11.3
  Disabling these plugins does not fix the issue
- A clear and concise description of what the bug is.
  Even though running on RHEL 7, it would appear that my system is identified as Mac, and the wrong configuration ends up being used.

**To Reproduce**
I have the following c_cpp_properties.json file:

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/local/opt/glib/include/glib-2.0",
                "/usr/local/opt/glib/lib/glib-2.0/include/",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2",
                "/usr/local/include/xraylib",
                "/usr/local/opt/libsoup/include/libsoup-2.4",
                "/usr/local/opt/gtk+3/include/gtk-3.0",
                "/usr/local/opt/pango/include/pango-1.0",
                "/usr/local/opt/harfbuzz/include/harfbuzz",
                "/usr/local/opt/cairo/include/cairo/",
                "/usr/local/opt/gdk-pixbuf/include/gdk-pixbuf-2.0",
                "/usr/local/opt/atk/include/atk-1.0/",
                "/usr/local/opt/gtkmm-plplot/include/gtkmm-plplot-2.0",
                "/usr/local/opt/gtkmm-plplot/lib/gtkmm-plplot-2.0/include/",
                "/usr/local/opt/gtkmm3/include/gtkmm-3.0",
                "/usr/local/opt/gtkmm3/lib/gtkmm-3.0/include",
                "/usr/local/opt/gtkmm3/lib/gdkmm-3.0/include",
                "/usr/local/opt/pangomm/include/pangomm-1.4",
                "/usr/local/opt/pangomm/lib/pangomm-1.4/include",
                "/usr/local/opt/glibmm/include/glibmm-2.4",
                "/usr/local/opt/glibmm/lib/glibmm-2.4/include",
                "/usr/local/opt/json-glib/include/json-glib-1.0",
                "/usr/local/opt/hdf5/include"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/local/opt/llvm/bin/clang",
            "cppStandard": "c++11"
        },
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/glib-2.0",
                "/usr/lib64/glib-2.0/include",
                "/usr/include/libxml2",
                "/dls_sw/apps/xraylib/3.99.0-gcc8/7/include/xraylib",
                "/usr/include/libsoup-2.4",
                "/dls_sw/apps/hdf5/1.10.3/include",
                "/usr/include/gtk-3.0/",
                "/dls_sw/apps/gtkmm-plplot/2.3/7/include",
                "/usr/include/pango-1.0",
                "/dls_sw/apps/gtkmm-plplot/2.3/7/lib/gtkmm-plplot-2.0/include/",
                "/usr/lib64/gtkmm-3.0/include/",
                "/usr/include/cairo",
                "/usr/lib64/gdkmm-3.0/include/",
                "/usr/include/json-glib-1.0/",
                "/usr/include/gdk-pixbuf-2.0",
                "/usr/lib64/pangomm-1.4/include/",
                "/usr/include/atk-1.0",
                "/usr/lib64/glibmm-2.4/include/",
                "/dls_sw/apps/cuda/9.2/include"
            ],
            "defines": [],
            "compilerPath": "/dls_sw/apps/gcc/8.3.0/7/bin/gcc",
            "cStandard": "c99",
            "cppStandard": "c++11",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Expected behavior**
That the system would be properly recognized as Linux and the corresponding configuration used. I cannot seem to find a way either to force it to use Linux either...

**Screenshots**

**Additional context**

Thanks for looking into this.

**Comment by Colengms** [comment]
Hi @tschoonj .  The C/C++ Extension does not auto-detect the appropriate configuration to use.  You need to select a configuration either by clicking on the configuration at the bottom of the VS Code window (while a C/C++ file is in focus), or using the `C/C++: Select a Configuration...` command.

**Comment by tschoonj** [comment]
Thank you for the hint: this works indeed.

I am surprised that there is no auto-detection going on, since the [documentation](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference#_configuration-properties) appears to say otherwise:

> name A friendly name that identifies a configuration. Linux, Mac, and Win32 are special identifiers for configurations that will be autoselected on those platforms. The status bar in VS Code will show you which configuration is active. You can also click on the label in the status bar to change the active configuration.

**Comment by Colengms** [comment]
Hi @tschoonj .  I stand corrected.  I did not know this feature existed.  :)  We'll take a look.

**Comment by sean-mcmanus** [comment]
I seem to recall (from a long time ago) the auto-config detection doesn't work if there are less than 3 configs, so adding a 3rd "windows" config that is unused might fix it.

**Comment by bobbrow** [comment]
The 3 config thing was from a while ago, I just tried this and didn't reproduce the incorrect config selection.  But we only auto-config the first time you open a folder or if you make changes to the config that remove the currently selected config.  Otherwise we will continue to use the previously selected config.

If you are still having a problem with this, let us know.  I will close the issue for now.
