### ISSUE TITLE
Formatter reorders includes resulting in broken code

### ISSUE THREAD

**Issue by acestronautical** [microsoft/vscode-cpptools#4697]
Formatter reorders includes alphabetically which is a non-stylistic change. This broke my code several times before I realized it was happening.

**Comment by sean-mcmanus** [comment]
This is controlled by the C_Cpp.clang_format_sortIncludes property -- did you change that? Or do you have a clang-format file that sets the SortIncludes parameter? What is your "clang_format_style" setting? The "Visual Studio" style sets the "-sort-includes=0". What version of clang-format are you using? The one we ship?

**Comment by bobbrow** [comment]
Unfortunately, we don't have enough information to investigate this issue.  If you can provide more information about your problem, we can take a look.  We will close this issue for now.  Thank you!
