### ISSUE TITLE
Problemmatcher not work over ssh

### ISSUE THREAD

**Issue by tooyangtoonaive** [microsoft/vscode-cpptools#4699]
Type: General
problemmatcher not work

**Describe the bug**
- OS and Version:win7 x64
- VS Code Version:1.40.2
- C/C++ Extension Version:0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Run task to build, problemmatcher not work when build error
**To Reproduce**
*Please include code sample and `task.json` files.*

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "zcsshbuild",
			"type": "shell",
			"command": "d:\\putty\\plink.exe -pw passwd user@server \"cd workspace && ./zcmake.sh\"",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher" : {
				"fileLocation" : ["relative", "${workspaceFolder}"],
				"pattern" : {
					//"regexp": "^.*$",   // nothing hanppen too
					"regexp" : "\/home\/workspace\/testproject\/([^:]*):(\\d+):(\\d+): (E|e)rror:(.*)"
					"file" : 1,
					"line" : 2,
				}
			}
		}
	]
}
```

1.ctrl+shift+b to build
2. Terminal show message: 
`/home/workspace/testproject/src/test.c:423:26: error: 'a' undeclared (first use in this function)`
3. It's **nothing happen** when double click message above. Terminal show message above not highlight

**Expected behavior**
It will nagivate to the codeline that compile error

**Comment by tooyangtoonaive** [comment]
plink.exe is a tool that can connect to ssh server and do something in batch. It include in putty software

**Comment by Colengms** [comment]
Hi @tooyangtoonaive .  This doesn't appear to be specific to the C/C++ Extension.  I'd suggest opening this against VS Code [here](https://github.com/microsoft/vscode/issues).
