### ISSUE TITLE
No Go to Definition/Peek Definition

### ISSUE THREAD

**Issue by vsccarl** [microsoft/vscode-cpptools#47]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Open a C++ file.
2. Right click to bring up context menu

![cppnopeekgoto](https://cloud.githubusercontent.com/assets/12900364/15261889/cab82eda-1913-11e6-9a8c-369b152ffb52.PNG)

**Comment by matthewgao** [comment]
Hopes this can be fixed ASAP

**Comment by delmyers** [comment]
@sridmad can you revisit? Was this fixed with the last update?

**Comment by matthewgao** [comment]
@delmyers yes, have tried in latest version, works perfect in windows.

**Comment by sridmad** [comment]
This should be fixed in recent updates.
