### ISSUE TITLE
[CMake] Not possible to debug since  update 0.26.2

### ISSUE THREAD

**Issue by LuisAyuso** [microsoft/vscode-cpptools#4703]
### Brief Issue Summary

The Extension Debug button in the bottom bar prompts error, normal debug tab on the left prompts same error:

ConvertToDto unexpected type

Extension Target selection works as usual.

### Expected:

1. Open CMake Project
2. Select Target to debug (bottom bar)
3. Click Debug
4. Debugger session starts

### Apparent Behavior:

1. Open CMake Project
2. Select Target to debug (bottom bar)
3. Click Debug
4. Bang! ConvertToDto unexpected type

### CMake Tools Log

```
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build xxxxxxxxxxxxxxxxx --config Debug --target xxxxxxxxxxxx -- -j 16
[build] [1/6  16% :: 0.004] xxxxxxxxxxxxxxxxxxx
[build] [2/4  50% :: 0.009] xxxxxxxxxxxxxxxxxxx
[rollbar] Unhandled exception: Unhandled Promise rejection: Update code model for cpptools TypeError: Cannot read property 'getApi' of undefined {}
[build] Build finished with exit code 0
[proc] Executing command: /usr/bin/gdb-7 --version
[proc] Executing command: gdb --version
```

### Platform and Versions

- **Operating System**:  Ubuntu 18.04
- **CMake Version**: 3.16
- **VSCode Version**: 1.40.2
- **CMake Tools Extension Version**: 1.2.3
- **C++  Extension Version**: 0.26.2
- **Compiler/Toolchain**: gcc 7.4

**Comment by sean-mcmanus** [comment]
Can you provide the log from Help->Toggle Developer Tools->Console?

Is this a recent regression within the past couple days, i.e. does using the "Install Another Version..." for 1.2.2 of CMake Tools fix the issue? From the previous issue https://github.com/microsoft/vscode-cmake-tools/issues/954 it sounds like you believe it's not a CMake Tools bug.

**Comment by sean-mcmanus** [comment]
I found a similar issue at https://github.com/cdr/code-server/issues/516 , which has some possible workarounds. Does changing your debugger type to "cppdbg" or uninstall/restart/install of the C/C++ extension fix the issue?

**Comment by pieandcakes** [comment]
@sean-mcmanus Is this a cmake extension issue? Can we move it to the correct repo? The error that `getApi` doesn't return a known value makes it sound like the `Cmake` extension is not calling a valid api anymore.

**Comment by sean-mcmanus** [comment]
I don't think it's a CMake Tools issue (that's where it was originally posted at). The getApi error message might be a CMake issue (during build), but the "ConvertToDto unexpected type" when debugging seems different.

**Comment by pieandcakes** [comment]
I don't know where that error comes from and it doesn't look like its this extension that does it. I know cmake-tools tries to make debugging calls and isn't very transparent about it.

**Comment by LuisAyuso** [comment]
I can confirm that the bug is present in C/C++ extension version 0.26.2.
- reverting to version 0.26.1 gets everything to work, any other extension and vscode itself are updated to the latest version
- Debug button in the bottom bar does not exist when this Extension is not installed.

I will come back with the developer's log

**Comment by sean-mcmanus** [comment]
@pieandcakes There weren't any debugger changes with 0.26.2, right?

**Comment by pieandcakes** [comment]
AFAIK there are no direct debugger changes. This looks like an API call to the extension code which @WardenGnaw and I didn't change either.

**Comment by LuisAyuso** [comment]
I was attempting to collect the developer log today, and therefore I updated the C++ extension again (0.26.2). Now I am unable to reproduce the issue. This is very embarrassing as a few days ago I reinstalled all the extensions several times and the bug was there. Could be this be related to an update of the system libraries (chrome related?)?, the only thing I can think that is different is that the host machine was restarted after updates. 

Thanks for your time and hard work. This extension is great and I think that it is awesome that Microsoft acknowledged it by taking ownership.

**Comment by gojimmypi** [comment]
@pieandcakes  fwiw - I saw this same problem compiling the [nanoFramework](https://github.com/nanoframework/nf-interpreter):

```
[kit] Successfully loaded 1 kits from c:\nf\.vscode\cmake-kits.json
[variant] Loaded new set of variants
[kit] Successfully loaded 1 kits from c:\nf\.vscode\cmake-kits.json
[rollbar] Unhandled exception: Unhandled Promise rejection: Update code model for cpptools TypeError: Cannot read property 'getApi' of undefined {}
[rollbar] Unhandled exception: Unhandled Promise rejection: Update code model for cpptools TypeError: Cannot read property 'getApi' of undefined {}
[rollbar] Unhandled exception: Unhandled Promise rejection: Update code model for cpptools TypeError: Cannot read property 'getApi' of undefined {}
```

 on 0.26.3. Reverting to  0.26.1 resolved it for me as noted by @LuisAyuso, [above](https://github.com/microsoft/vscode-cpptools/issues/4703#issuecomment-563155650).

Curiously, when re-installing the latest version (0.26.3) the problem was no longer present. 

This was a first-time install of the C/C++ extension for me. I wonder if some critical setting occurs in  0.26.1 that does not in 0.26.3 and is otherwise kept after the upgrade?

See also https://github.com/microsoft/vscode-cmake-tools/issues/608 which is similar, but I think different.
