### ISSUE TITLE
Find All References/Rename could use query_translation_unit_source on headers

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#4708]
This is related to https://github.com/microsoft/vscode-cpptools/issues/4617 .

For header files, FAR/Rename could use query_translation_unit_source on each header, and create TU's with the source file instead.  If multiple headers resolve to the same source file, they could be coalesced into the same TU.

This would also address issues with custom configurations, as some providers may not provide configurations for headers, resulting in unconfigured header-only TUs.

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
