### ISSUE TITLE
Version 0.10.0 "Go-to-definition" is not excluding symbols found in files.exclude

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#471]
I am running 0.10.0 with the Insiders release of Code.  The release notes state:

"Go-to-definition now excludes symbols found in files.exclude file"

but I'm finding that Go-to-definition is ignoring files.exclude:

![image](https://cloud.githubusercontent.com/assets/7724321/22560297/fda69042-e96b-11e6-830b-e0b886a8f0f2.png)

![image](https://cloud.githubusercontent.com/assets/7724321/22560346/22a504aa-e96c-11e6-88b9-ac731f9a35e3.png)

Do I need to re-index the database?  If so, how?

**Comment by daldr-ntml** [comment]
On second thoughts, it is expanding the correct (non-excluded) definition.  Should it be offering the excluded ones as well?

**Comment by sean-mcmanus** [comment]
We have a bug with the excluded files not being removed from the database when the setting is changed. It has been fixed (and we're planning to release a bug fix update ASAP), but in the meantime a workaround is to delete the .browse.vc.db after adding an exclude.

**Comment by daldr-ntml** [comment]
Thank you. That fixed it.

**Comment by daldr-ntml** [comment]
Sorry, I think I should not have closed this.

**Comment by sean-mcmanus** [comment]
Yeah, the bug still exists in 0.10.0 :)

**Comment by csholmq** [comment]
Works in 0.10.1 👍
