### ISSUE TITLE
Find all references/rename does not work across folders in multi-root workspace

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#4711]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Debian 9
- VS Code Version: 1.40
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is:

I have a project with the following structure:
Project
|
|----Module 1
|
|----Module 2
|
|----Module N

My workspace only opens Module 1 and Module 2 because I work in a monorepo and opening the whole project is too much. When I try doing find all references on a symbol in Module 1, Intellisense only shows the references in Module 1 and not in Module 2 (references to the same symbol do exist in Module 2, however). 

I assume this is related to https://github.com/microsoft/vscode-cpptools/issues/2821#issuecomment-438742688

**To Reproduce**
1. Use LLVM repo
2. Create a workspace with 'clang' and 'clang-tools-extra' folders open
3. Configure Intellisense using compile_commands.json
4. Try doing find all references on a symbol in clang-tools-extra (such as ASTContext). Notice that only references in the clang-tools-extra folder are shown.

**Expected behavior**
References in both the clang-tools-extra and clang folders would be shown

**Comment by sean-mcmanus** [comment]
Our multi-root support is being re-implemented (one language server process and database shared across all folders instead of one per folder), so this should be fixed as a result of that.

**Comment by sean-mcmanus** [comment]
Our latest Insiders release has a new multi-root implementation (which fixes this bug): https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders. Please let us know if you find any multi-root-related bugs or regressions so we can prioritize fixing those for 0.27.0.

**Comment by ghost** [comment]
This seems to be working very well now.

Thanks, Sean!
