### ISSUE TITLE
Red squiggles not shown if file location contains umlauts

### ISSUE THREAD

**Issue by michaellass** [microsoft/vscode-cpptools#4712]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS 10.15.1 (Catalina)
- VS Code Version: 1.40.2
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them): Python, Rust (rls) (both disabled without any change)
- A clear and concise description of what the bug is:

If the project path contains an umlaut like `ü`, no red squiggles are shown in the editor, even if problems are detected and shown in the Problems tab.

**To Reproduce**

1. Create a project directory with a name that contains an umlaut (e.g., ~/tüst)
2. Open in vscode and create an erronous C file, e.g.:
```
int main() {
  @;
}
```
3. Wait until the problem is detected and listed in the Problems tab
4. Observe: No squiggly line below the @
5. Close vscode and rename project directory, e.g. from tüst to test
6. Open file in vscode again and wait until problem is detected and listed in the Problems tab
7. Observe: Squiggly line below the @

One additional thing:
If you click on the error listed in the Problems tab, the file is opened using an abolute path. In this new file tab, the squiggles are shown as expected, even if the path contains an umlaut.

**Expected behavior**

The squiggles should work regardless of the file location.

**Screenshots**

With umlaut, no squiggles:
![With umlaut, no squiggles](https://user-images.githubusercontent.com/11042539/70330315-a051ab80-183d-11ea-87e2-34da344e93bb.png)

With umlaut, opened with aboslut path, squiggles working:
![With umlaut, opened with absolut path](https://user-images.githubusercontent.com/11042539/70330431-d858ee80-183d-11ea-9261-251342a6e87b.png)

No umlaut, squiggles working:
![No umlaut, squiggles working](https://user-images.githubusercontent.com/11042539/70330457-e870ce00-183d-11ea-83f8-d81b783363fc.png)

**Additional context**

I tried to reproduce the problem with the Python extension but could not, so I assume it is an issue specific to vscode-cpptools.

**Comment by sean-mcmanus** [comment]
Strange -- the bug only repros on Mac and not Windows or Linux. The logging shows:

* Original file (no squiggles) from VS Code: Umlaut encoded as `%C3%BC` (correct).
* Path from the squiggle (from us?): Umlaut encoded as `u%CC%88` (incorrect).

**Comment by Colengms** [comment]
I've tracked this down to a potential issue in VS Code.  It appears to be changing the encoding from use of a combining character to the combined equivalent, and does not recognize the original as the same path.  If VS Code keeps this behavior, we will at least need sufficient information about what modifications may be made to the encoding, to ensure we make the same modifications when receiving a path from the file system directly.

**Comment by sean-mcmanus** [comment]
Fixed in our latest Insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders.
