### ISSUE TITLE
Debugger not starting my process

### ISSUE THREAD

**Issue by JoffreyAlto** [microsoft/vscode-cpptools#4713]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 familial edition
- VS Code Version: 1.40.2
- C/C++ Extension Version: 0.26.2
- Other extensions you installed :
C/C++ GNU Global
C++ Intellisense
Include Autocomplete
SQL Server (mssql)
TabNine
Visual Studio Intellicode

Description of my issue :
Hello there,

Since today my debugging doesn't work anymore. I'm working on a C89 project, I've been using VS Code for a few months and real time debugging used to work pretty correctly. My launch.json seems to be configured well, and I didn't change anything in it. During the morning, I've tried to install new random extensions to improve the autocomplete feature.

Since I did so, the whole debugging feature litterally stopped working. I tried to disable them all, but still, I can't do anything. I've set up 2 different configurations (launch/attach), and both don't work anymore. The launch one just doesn't launch anything, I can't find any error message log file or anything. The attach one won't attach either.

**To Reproduce**
`"configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "C:/cc50/_joffr/STD51alto.EXE",
            "args": [],
            "stopAtEntry": true,
            "cwd": "C:/cc50/C",
            "environment": [],
            "externalConsole": false,
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
            }
        },
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
            }
        }]`
1. Use F5 or click on the button to start the "launch" configuration
2. Nothing happens

**Additional context**
I enabled "logging" feature in launch.json.
I'm not able to post any sample of my code due to privacy issues, sorry about it. Anyway it's not about the code, the debugger just doesn't start anymore.
My debug console and output box don't print anything. I have no clue how to find where my issue comes from.

**Comment by pieandcakes** [comment]
Can you verify that the folder `%userprofile%\.vscode\extensions\ms-vscode.cpptools-0.26.2\debugAdapters\vsdbg` exists and has a `bin` folder inside? If not, can you uninstall/reinstall the extension?

We haven't done any updating to the `cppvsdbg` scenario in the last update to cause it not to work.

**Comment by JoffreyAlto** [comment]
Thanks a lot for your answer. I solved my issue. Actually, I already tried to uninstall the extension and re-install it, but it didn't change anything. On the other hand, I had no idea that the binary files of the debugger were in a separated folder, which is debugAdapters\vsdbg.

So what I've done after seeing your message is simply to uninstall the extension, then I dropped manually the whole folder ms-vscode.cpptools-0.26.2 (first, I thought uninstalling from VS Code interface would at least drop binary files). Then I re-installed it, and I guess downloading the whole extension from the beginning helped, maybe this was a case of corrupted file or whatever.

Anyway thanks for your advice, it helped ! Sorry for disturbing, I guess I could've fixed it by myself :)

**Comment by noodlecollie** [comment]
I'm having the same problem, and the above process didn't fix it. I am running VSCodium, I don't know if that makes any difference.

The `debugAdapters\vsdbg\bin` folder does exist for me, and I can see (and manually run) the VS debugger executable within that folder. However, I still get the issue mentioned above where the debugger never actually seems to launch for more than half a second within the VS Code environment, before quitting silently.

The only thing the debug console displays is:

```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

Nothing else is printed in any other console.

**Comment by pieandcakes** [comment]
@x6herbius The Visual C++ debugger won't work with VSCodium. As the item in your debug console says, it only works with Visual Studio or Visual Studio Code, which VSCodium is not. 

[Here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#proprietary-debugging-tools) is the note on VSCodium's github page.

**Comment by noodlecollie** [comment]
Ah, whoops, I thought that was just a standard license banner. I'll switch back to normal VS Code.
