### ISSUE TITLE
template parameter type-parameter-key may not be colored correctly

### ISSUE THREAD

**Issue by UnsaidAverage** [microsoft/vscode-cpptools#4715]
<img width="155" alt="批注 2019-12-07 152358" src="https://user-images.githubusercontent.com/47773825/70370719-a612c400-1905-11ea-948f-ca385fb22422.png">
Issue Type: <b>Bug</b>

```
template <
    typename T,
    class Compare = ::std::less<T>,
    class Allocator = ::std::allocator<T>
> class MySet {
/// ...details
};
// typename is colored, however, class is NOT colored
```
Extension version: 0.26.2
VS Code version: Code - Insiders 1.41.0-insider (87c2e0be5d7359ce110c4c9ec9f6df71be996f8a, 2019-12-06T21:36:11.793Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2130 @ 3.20GHz (2 x 3203)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.45GB (20.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @UnsaidAverage .  Although the C/C++ Extension provides semantic colorization, keyword colorization is syntactic/lexical and handled by VS Code via TextMate grammer.  @jeff-hykin contributes TextMate grammer for C/C++ in VS Code.  That repo is here: https://github.com/jeff-hykin/cpp-textmate-grammar   Would you like to open this issue there?

**Comment by jeff-hykin** [comment]
Yup we are actually already tracking the issue [here ](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/246)
The template area needs a rewrite

**Comment by Colengms** [comment]
Closing this issue, as we don't generally track issues with TextMate grammar in this repo.
