### ISSUE TITLE
ver 0.26.2 cannot list class members by IntelliSense on macOS mojave 10.14.6

### ISSUE THREAD

**Issue by hayhan** [microsoft/vscode-cpptools#4716]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS mojave 10.14.6
- VS Code Version: 1.40.2
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

Following the official instructions at link below can reproduce the issue.
https://code.visualstudio.com/docs/cpp/config-clang-mac#_explore-intellisense

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by michelleangela** [comment]
@hayhan, I can't reproduce the issue of class members not listed by IntelliSense. 

To get more information about the issue, can you enable [logging of the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) and share the logs?

**Comment by hayhan** [comment]
@michelleangela, I attached the log. Pls check.

[macos_issue4716.log](https://github.com/microsoft/vscode-cpptools/files/3945183/macos_issue4716.log)

**Comment by hayhan** [comment]
@michelleangela, some extra logs. B.T.W, it is OK to goto definition and OK to build the code.

-------------------------
textDocument/hover: 33
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
using Tag Parser for quick info
textDocument/hover: 34
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
using Tag Parser for quick info
textDocument/hover: 35
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
using Tag Parser for quick info
textDocument/hover: 36
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
using Tag Parser for quick info
textDocument/hover: 37
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
using Tag Parser for quick info

**Comment by hayhan** [comment]
From the log, I just realized the SDK is 10.15 on my Mojave machine. I am not sure if this combination introduces this issue.

**Comment by hayhan** [comment]
I upgraded my macOS to 10.15.2 and re-installed the 10.15 SDK. The IntelliSense works well now. So probably Mojave (10.14.6) + 10.15 SDK makes the IntelliSense down.

Pls feel free to close this case or investigate it further.

**Comment by michelleangela** [comment]
>So probably Mojave (10.14.6) + 10.15 SDK makes the IntelliSense down.

Perhaps that combination caused an issue with IntelliSense trying to resolve the includes.
