### ISSUE TITLE
Intellisense: no error emitted about inaccessible base class member in inline friend function of derived class.

### ISSUE THREAD

**Issue by escape0707** [microsoft/vscode-cpptools#4717]
**Type: LanguageService**

No error emitted about inaccessible base class member in inline friend function of derived class.

**Describe the bug**
- OS and Version: Linux x64 5.4.2-arch1-1
- VS Code Version: 1.40.2
- C/C++ Extension Version: 0.26.2

**To Reproduce**

1. Create and compile a `.cpp` file which contains the following codes:
```cpp
class Base {
 protected:
  int prot_mem;
};

class Sneaky : public Base {
  inline friend void clobber(Sneaky &s) { s.j = s.prot_mem = 0; }
  inline friend void clobber(Base &b) { b.prot_mem = 0; }
  int j;
};
```

**Expected behavior**

Identify b.`prot_mem` as error just as if the error appears in a out-of-class friend function definition:

```
int Base::prot_mem
protected member "Base::prot_mem" (declared at line 3) is not accessible through a "Base" pointer or object
```

**Screenshots**

- Expected:

![image](https://user-images.githubusercontent.com/11014745/70384627-96a28200-19bc-11ea-8c25-94892562d78a.png)

- Got:

![image](https://user-images.githubusercontent.com/11014745/70384546-eaac6700-19ba-11ea-85f9-0c9e7575ddef.png)

**Comment by Colengms** [comment]
Hi @escape0707 .  This also repro's in Visual Studio.  (The C/C++ Extension shares common code for IntelliSense with VS).  I've opened an issue against VS [here](https://developercommunity.visualstudio.com/content/problem/849776/intellisense-does-not-squiggle-error-for-inaccessi.html).

**Comment by sean-mcmanus** [comment]
Fixed in our latest Insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders.

**Comment by escape0707** [comment]
> 
> 
> Fixed in our latest Insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders.

Thanks for your hardwork on this. But I'm sorry that I can't test it in C++ project for now. Feel free to close this issue if it's confirmed fixed XD!
