### ISSUE TITLE
Lint error when init a struct in this way, how to eliminate it?

### ISSUE THREAD

**Issue by fwhezfwhez** [microsoft/vscode-cpptools#4719]
It will report before-compile error when I init a c struct in this way:

```c
#include <stdio.h>

int main()
{
    struct Person
    {
        char name[10];
        int age;
    };
    struct Person tom = {
        .name = "ft",
        .age = -10,
    };
    printf(tom.name);

   // Here it will report error
    struct Person tom2 = {
        name : "ft",
        age : -10
    };
    printf(tom2.name);

    return 0;
}
```

**Comment by fwhezfwhez** [comment]
1

**Comment by Colengms** [comment]
Hi @fwhezfwhez .  In your first example, it looks like you are using 'designated initialization', which is a new feature in C++20.

In your second example, you are using a ":" to assign the value.  I'm not familiar with this syntax.  I do not see it in http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0329r4.pdf .  Is that syntax valid?

**Comment by fwhezfwhez** [comment]
@Colengms 

```bash
> gcc --version
gcc (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 4.9.1
```
`struct.c`

```c
#include <stdio.h>

int main()
{
    struct Person
    {
        char name[10];
        int age;
    };

    struct Person tom2 = {
        name : "ft",
        age : -10,
    };
    printf(tom2.name);

    return 0;
}
```
```bash
> gcc struct.c -o struct.exe && struct
ft
```

**Comment by Colengms** [comment]
Aha.  It's a gcc extension.

Try adding the following to your configuration:

```
"intelliSenseMode": "gcc-x64"
```

(Or gcc-x86, if 32-bit).  With the intelliSenseMode set to a gcc mode, I do not see a squiggle for that syntax.

**Comment by fwhezfwhez** [comment]
ok,3q~~I'll not use second style.
