### ISSUE TITLE
Ctrl+Shift+O cannot show long function name

### ISSUE THREAD

**Issue by guolisen** [microsoft/vscode-cpptools#4722]
sometimes in C++, the function name has a long namespace, so the Ctrl+Shift+O cannot show the whole function name, because the dialog is too short and doesn't have scroll bar.
I have created a issue on vscode project, but the vscode experts said that this is a extension problem,
https://github.com/microsoft/vscode/issues/85793

![](https://user-images.githubusercontent.com/1932457/69841109-eedcd400-1298-11ea-9b34-72cfe291e08f.png)

**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I made a comment in the original issue. This is currently "by design", but it's possible we could change the design. Or maybe VS Code could add a horizontal scroll bar?

**Comment by sean-mcmanus** [comment]
The VS Code team suggests we move the "base::" part to the details section that appears on the right and create some dummy "base" symbol that just points to the 1st reference if there's no symbol definition in the file.

**Comment by guolisen** [comment]
actually, I think add the scroll bar is better, because 'func base1 base2....' also has problem.

setValue ObjjjjjjjjjjjjjjjjjjjjjectNamespace::ObjjjjjjjjjjjjjjjjjjjjjectNamespace::type1
setValue ObjjjjjjjjjjjjjjjjjjjjjectNamespace::ObjjjjjjjjjjjjjjjjjjjjjectNamespace::type2
.....

the 'type1‘ will be covered by dialog......

**Comment by bobbrow** [comment]
This issue was addressed. We don't show the fully qualified name anymore.
```cpp
namespace A1234567890
{
  namespace B1234567890
  {
    namespace C1234567890
    {
      namespace D1234567890
      {
        void innerFunc(){}
      }
      void innerFunc(){}
    }
    void innerFunc(){}
  }
}
```
![image](https://github.com/user-attachments/assets/099cb1f4-b8a9-4e77-952a-9c4619c14113)
