### ISSUE TITLE
cpptools causes some characters to render incorrect colors in cpp files.

### ISSUE THREAD

**Issue by fisheva** [microsoft/vscode-cpptools#4723]
Here is the example code.
```c++
#include <iostream>
#include <ctime>
using namespace std;
int main( )
{
   time_t now = time(0);
   char* dt = ctime(&now);
   cout << "Local date and time：" << dt << endl;
   tm *gmtm = gmtime(&now);
   dt = asctime(gmtm);
   cout << "UTC date and time："<< dt << endl;
}
```

When I disabled cpptools, the code rendering like this:
![image](https://user-images.githubusercontent.com/17448419/70501426-00579300-1b59-11ea-8a7a-9282d9b42713.png)

While when I enabled cpptools, the code rendering like this:
![image](https://user-images.githubusercontent.com/17448419/70501509-31d05e80-1b59-11ea-9e21-420411c2d87b.png)

See, these characters' scope values were not changed, but they are rendering an incorrect color.
Hope this bug can be fixed soon. Thanks a lot!

**Comment by sean-mcmanus** [comment]
This seems "by design". Our extension adds semantic colorization on top of the existing lexical colors. You can disable this via the C_Cpp.enhancedColorization setting. See https://code.visualstudio.com/docs/cpp/colorization-cpp .

@Colengms might have more to add.

**Comment by Colengms** [comment]
Note that because semantic colorization is implemented using `TextEditorDecorations`, they are not reflected in the `Developer: Inspect TM scopes` UI.

**Comment by fisheva** [comment]
Wow, it worked. Thank u so much!
![image](https://user-images.githubusercontent.com/17448419/70693737-05ebdf00-1cf9-11ea-8ec2-1049fd1f12a1.png)
