### ISSUE TITLE
Move internal -std when compiler quering to the front to allow overwriting it

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4726]
It would be really nice if the generated `-std` argument was prepended instead of appended to the user-provided arguments. I have a codebase that requires `__GNUC__` to be set and `__STRICT_ANSI__` to be unset in order for the correct typedefs to exist. Because this extension forces `gcc` to report its definitions for an ANSI standard, I am unable to get that combination of definitions (and there also doesn't seem to be any way for me to manually undef `__STRICT_ANSI__`).

The only workaround I've found is to pass bogus arguments to the compiler so that it errors out and doesn't report any definitions at all. Then, I can set the ones I need manually.

_Originally posted by @tchebb in https://github.com/microsoft/vscode-cpptools/issues/2782#issuecomment-563944172_

**Comment by JamesDwyer364** [comment]
{%%ini.sysmond;)

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
