### ISSUE TITLE
Colorization can't run correctly when useing remote-ssh mode

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#4729]
codes can't be colorized when using remote-ssh mode but "go to definition" is correct.

**Comment by Colengms** [comment]
Hi @Lennon925 .  We're currently tracking this issue with https://github.com/microsoft/vscode-cpptools/issues/3942 .  This is a limitation of the way semantic colorization is implemented, which involves parsing the current theme.  Unfortunately, the theme is not accessible remotely.  VS Code is in the process of providing some new APIs that we'll be able to use to improve this feature, including working via remote.  Those issues are: https://github.com/microsoft/vscode/issues/32813 and https://github.com/microsoft/vscode/issues/77133

**Comment by Lennon925** [comment]
> Hi @Lennon925 . We're currently tracking this issue with #3942 . This is a limitation of the way semantic colorization is implemented, which involves parsing the current theme. Unfortunately, the theme is not accessible remotely. VS Code is in the process of providing some new APIs that we'll be able to use to improve this feature, including working via remote. Those issues are: [microsoft/vscode#32813](https://github.com/microsoft/vscode/issues/32813) and [microsoft/vscode#77133](https://github.com/microsoft/vscode/issues/77133)

Thanks for your reply.
