### ISSUE TITLE
${vcpkgRoot} variable is not expanded in tasks.json

### ISSUE THREAD

**Issue by david-antiteum** [microsoft/vscode-cpptools#4730]
${vcpkgRoot} variable is expanded in c_cpp_properties.json (for example in includePath) but not in  tasks.json.

I need this expansion to write a cmake task command. Something like this:

```
{
	"label": "cmake",
	"type": "shell",
	"command": "cmake",
	"args": [
		"${workspaceFolder}",
		"-B",
		"${workspaceFolder}/build",
		"-DCMAKE_TOOLCHAIN_FILE=${vcpkgRoot}/scripts/buildsystems/vcpkg.cmake"
	],
	"group": "build",
	"problemMatcher": []
}
```

Thanks

**Comment by michelleangela** [comment]
Parsing of tasks.json is done by VS Code and understands the variable substitutions documented [here](https://code.visualstudio.com/docs/editor/variables-reference).

I think `${vcpkgRoot}` is unique to the C/C++ extension. @sean-mcmanus , can `${vcpkgRoot}` be referenced in tasks.json?

**Comment by sean-mcmanus** [comment]
vcpkgRoot is only understood by our extension. We have util.getVcpkgRoot() method at https://github.com/microsoft/vscode-cpptools/issues/4418#issuecomment-564445774 . There's an issue on VS Code to enable extensions to custom variables at https://github.com/microsoft/vscode/issues/46471
