### ISSUE TITLE
Concerns regarding curly braces slamming to the left in C++ language

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode-cpptools#4732]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 x64-bit
- VS Code Version: Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z

- C/C++ Extension Version: v0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
I disabled Beautify, and it still happens.

- A clear and concise description of what the bug is.

I disabled beautify and even with disabling that extension, my curly braces keeps slamming to the left.
In the pictures I provide will show what I am expecting the behavior to do in C++
and another picture that shows the curly braces slamming to the all the way to the left.
This does not happen in another language, only happens in C++ language & I dont know why.

**Expected behavior**

> _This is the slamming curly braces that I hate:_

![Not proper way of C++ linting](https://user-images.githubusercontent.com/18384135/70656288-cdc89b80-1c27-11ea-8ffc-abd33f7bf54f.png)

**Screenshots**

> _This is what I would like to happen:_

![proper way of formatting C++](https://user-images.githubusercontent.com/18384135/70656316-d9b45d80-1c27-11ea-9c8a-3566ca444cc3.png)

Is it possible to get what I want, or is C++ oddly like this ??
I'm new to C++ language so dont know how it is suppose to behave in regards to curly braces left slamming.
anyways thanks.

**Comment by michelleangela** [comment]
The C/C++ extension uses clang-format to format code. Style of code formatting can be configured, which is documented at https://code.visualstudio.com/docs/cpp/cpp-ide#_code-formatting

**Comment by RobFosterNYC** [comment]
But does it disable formatting on all other languages too ?
or just for C++ ? - I just want it to remember the way I want it to format, so its readable easily.
To understand what I am talking about, take a look at the Class Car on both pictures provided.
And how they are indented and how all the curly braces are not slammed to the left.

**Comment by michelleangela** [comment]
The specific formatting settings at  https://code.visualstudio.com/docs/cpp/cpp-ide#_code-formatting is only for the C/C++ extension. So disabling it will not affect other languages.

**Comment by RobFosterNYC** [comment]
thank you for letting me know, i will keep reading the linked tutorial

**Comment by Colengms** [comment]
This issue was labeled as a 'question' and appears to have been answered.  If there is something more here, please let us know.  :)
