### ISSUE TITLE
Mingw64 headers breaks intellisense under linux

### ISSUE THREAD

**Issue by ttc0419** [microsoft/vscode-cpptools#4735]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Arch Linux
- VS Code Version: 1.40.2-1
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them): Python

Intellisense cannot detect definitions in headers after windows.h  

**To Reproduce**

1. copy the code in the screenshot
2. type my
3. See error

**Expected behavior**
my_t shows up in the autocompelete list

**Edit**
After a bit of testing, it seems most of headers from mingw64 can break the intellisense.  Some functinons were not shown in the autocompletion list (e.g. CreateThread) using default intellisense engine.  Tag Parser worked fine.

**Screenshots**
![Screenshot from 2019-12-12 17-12-30](https://user-images.githubusercontent.com/26517146/70699814-ae537080-1d04-11ea-9644-05f6a0b6b6e3.png)
![Screenshot from 2019-12-12 17-12-07](https://user-images.githubusercontent.com/26517146/70699820-b0b5ca80-1d04-11ea-8ada-0ee8f4966d2d.png)

**Comment by sean-mcmanus** [comment]
I'm only familiar with using MinGW on Windows. How are you using it on Linux? Usually Linux uses gcc or clang based compilers.

Can you open the headers and see what errors are occurring? The windows.h file is probably causing our parser to break.

**Comment by ttc0419** [comment]
Yes, I'm using it with gcc on linux. 

settings.json
```json
{
    "window.titleBarStyle": "custom",
    "window.zoomLevel": 0,
    "editor.fontFamily": "'Consolas'",
    "files.autoSave": "afterDelay",

    "C_Cpp.default.compilerPath": "/usr/bin/gcc",
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.cStandard": "c11", 
    "C_Cpp.default.includePath": [
        "/usr/include/**",
        "/usr/x86_64-w64-mingw32/include/**"
    ],
    "C_Cpp.intelliSenseEngineFallback": "Enabled",
}
```

windows.h:
```c
/**
 * This file has no copyright assigned and is placed in the Public Domain.
 * This file is part of the mingw-w64 runtime package.
 * No warranty is given; refer to the file DISCLAIMER.PD within this package.
 */
#ifndef _WINDOWS_
#define _WINDOWS_

#include <_mingw.h>
#include <sdkddkver.h>

/* Some kludge for Obj-C.
   For Obj-C the 'interface' is a keyword, but interface is used
   in midl-code too.  To resolve this conflict for at least the
   main windows API header, we define it here temporary.  */
#ifdef __OBJC__
#pragma push_macro("interface")
#undef interface
#define interface struct
#endif

#ifndef _INC_WINDOWS
#define _INC_WINDOWS

#if defined(RC_INVOKED) && !defined(NOWINRES)

#include <winresrc.h>
#else

#ifdef RC_INVOKED
#define NOATOM
#define NOGDI
#define NOGDICAPMASKS
#define NOMETAFILE
#define NOMINMAX
#define NOMSG
#define NOOPENFILE
#define NORASTEROPS
#define NOSCROLL
#define NOSOUND
#define NOSYSMETRICS
#define NOTEXTMETRIC
#define NOWH
#define NOCOMM
#define NOKANJI
#define NOCRYPT
#define NOMCX
#endif

#if defined(__x86_64) && \
  !(defined(_X86_) || defined(__i386__) || defined(_IA64_))
#if !defined(_AMD64_)
#define _AMD64_
#endif
#endif /* _AMD64_ */

#if defined(__ia64__) && \
  !(defined(_X86_) || defined(__x86_64) || defined(_AMD64_))
#if !defined(_IA64_)
#define _IA64_
#endif
#endif /* _IA64_ */

#ifndef RC_INVOKED
#include <excpt.h>
#include <stdarg.h>
#endif

#include <windef.h>
#include <winbase.h>
#include <wingdi.h>
#include <winuser.h>
#include <winnls.h>
#include <wincon.h>
#include <winver.h>
#include <winreg.h>
#include <winnetwk.h>
#include <virtdisk.h>

#ifndef WIN32_LEAN_AND_MEAN
#include <cderr.h>
#include <dde.h>
#include <ddeml.h>
#include <dlgs.h>
#include <lzexpand.h>
#include <mmsystem.h>
#include <nb30.h>
#include <rpc.h>
#include <shellapi.h>
#include <winperf.h>
#if defined(__USE_W32_SOCKETS) || !defined(__CYGWIN__)
#include <winsock.h>
#endif
#ifndef NOCRYPT
#include <wincrypt.h>
#include <winefs.h>
#include <winscard.h>
#endif

#ifndef NOUSER
#ifndef NOGDI
#include <winspool.h>
#ifdef INC_OLE1
#include <ole.h>
#else
#include <ole2.h>
#endif
#include <commdlg.h>
#endif
#endif
#endif

#ifndef __CYGWIN__
#include <stralign.h>
#endif

#ifdef INC_OLE2
#include <ole2.h>
#endif

#ifndef NOSERVICE
#include <winsvc.h>
#endif

#ifndef NOMCX
#include <mcx.h>
#endif

#ifndef NOIME
#include <imm.h>
#endif

#endif
#endif

/* Restore old value of interface for Obj-C.  See above.  */
#ifdef __OBJC__
#pragma pop_macro("interface")
#endif

#endif
```

**Comment by sean-mcmanus** [comment]
Hmm...cross compiling for Windows on Linux is not something we have tested, so it's possible there are bugs. What errors do you see when you open the <windows.h> header?

You're usage of "/include/**" in your includePath is likely to give incorrect results, because "**" generates the paths in a non-deterministic order, but the Linux include paths require a particular order or you're likely to get incorrect results and missing headers. Can you remove those system includes and instead set your compilerPath to the mingw compiler? I think /usr/bin/gcc is not the mingw compiler, right? Enabling debug logging (https://code.visualstudio.com/docs/cpp/enable-logging-cpp) may help diagnose some configuration issues.

**Comment by ttc0419** [comment]
After some tesing,

- No errors in windows.h or any of mingw header files.
- Change of include path does not have any impacts.
- Change compiler path to mingw compiler seems fix the issue, but why?

**Comment by sean-mcmanus** [comment]
Yeah, your compilerPath needs to be compatible with the headers you're using, because we query the compilerPath for system defines and includes.

**Comment by MonaTheMonad** [comment]
What does IntelliSense actually do to determine the appropriate header paths, knowing the compiler path? If I only have a standalone sysroot (i.e. just headers and libraries, no binaries like `gcc` or `ld`), could I spoof the binary to get it to automatically detect the appropriate header paths?

**Comment by sean-mcmanus** [comment]
Yeah, we query the compilerPath for system includes and defines. If you set compilerpath to be `""` then you could try to supply your own system includes and headers to mimic what gcc would return. Another approach is to pass a .sh file to compilerPath that outputs results that mimics what gcc would return.
