### ISSUE TITLE
Configuration UI shows error for cl.exe with a different version when it shouldn't

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4739]
The JSON configuration doesn't squiggle when the cl.exe path is different so the behavior is inconsistent. The reason not to show the error is that the version in the path can change, but we should still be able to find the correct version, so there's no reason to show an error.

But maybe this doesn't matter to external users that don't update their cl.exe often? I'm not sure how frequently the public Preview version changes. I'm on the "dogfood" so the version changes a lot.

**Comment by bobbrow** [comment]
Yeah, the extension works when you don't update it, but it's still an invalid path.  I don't think we should bother fixing this.  At some point we may be able to get variables like MSC_VER from cl and at that point the path will matter.
