### ISSUE TITLE
Light bulb always asking to add include path, when it's already set

### ISSUE THREAD

**Issue by hmenzagh** [microsoft/vscode-cpptools#474]
VSCode Version: Latest, 1.9.0
OS Version: OSX 10.12
Extention Version : 0.10.0

Hi, I just noticed (maybe it's recent) that every time I type a new line in a .c file on vscode (or even when I clic on a function name), there is the yellow lightbulb that appears and that asks me to add an include path to the settings. But possible includes specified .. I can't get rid of it and it's driving me crazy.

Here is my c_cpp_properties.json :

```

{
    "configurations": [
        {
            "name": "Mac",
            "includePath": ["/usr/include", 
            "/Users/XXX/XXX/XXX/includes",
             "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : false,
                "databaseFilename" : ""
            }
        },
        {
            "name": "Linux",
            "includePath": ["/usr/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        },
        {
            "name": "Win32",
            "includePath": ["c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        }
    ]
}
```

**Comment by sean-mcmanus** [comment]
Yes, it's caused by different code action behavior in VS Code 1.9. We have made a fix (in the C++ extension) and are working to release it ASAP. See https://github.com/Microsoft/vscode-cpptools/issues/472 .
