### ISSUE TITLE
[Feature Request] Improve Debug: Attach to Running Process

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode-cpptools#4740]
Type: Debugger

I frequently debug a (specific) running process using VS Code on Windows, remote debugging an already running C++ process on Linux. I have a few related suggestions (and/or bugs) for launch.json, and the documentation of it:

1) In launch.json, I have "processId":"${command:pickProcess}", which works. However, I also have the "program" setting specified (which the documentation says is "required" -- see #3), but the list of running processes that are displayed is never filtered to only show that "program". So, this is my first suggestion: If a "program" is specified, filter the list to only that program (there may still be more than one). This could be done by starting the running program selection with the "program" text in the search box (related to #2). Or, it could be done without the search box by simply limiting the list to those processes which match.  If the latter, perhaps skip displaying the list of just one item and/or have an option to do so.

2) In the running program selection box, I am frequently typing the same thing (actually, different than my "program", because I am searching for a command-line parameter). It would be nice if I could specify some default text search string in launch.json (that could override "program" if you also do #1). I would still want to be able to edit the text, but this text could appear as the default/initial text in the search box.

3) The documentation on https://code.visualstudio.com/docs/cpp/launch-json-reference says that "program" is "required". However, it does not appear to actually be required (at least in my scenario it seems to be ignored).

4) The documentation on https://code.visualstudio.com/docs/cpp/launch-json-reference lists "externalConsole" option. However, A) The editor shows a yellow squiggly for it, and B) See microsoft/vscode-cpptools#4592 where I found out that my debugger never actually attaches when that setting is present (after selecting the process to attach to). Please update the documentation and also make the debugger still work if an invalid entry is present in launch.json (or at least report it in the notifications).

(I originally posted this at https://github.com/microsoft/vscode/issues/86946, but they said to post it here).

**Comment by pieandcakes** [comment]
> The documentation on https://code.visualstudio.com/docs/cpp/launch-json-reference says that "program" is "required". However, it does not appear to actually be required (at least in my scenario it seems to be ignored).

It is required because that is what we tell `gdb` to load for symbols.

**Comment by pieandcakes** [comment]
For 1, we will need to parse the `config` and get the filename of `program` and filter [here](https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/Debugger/nativeAttach.ts#L155)

**Comment by pieandcakes** [comment]
For 4: https://github.com/microsoft/vscode-docs/pull/3352. I commented about the invalid entry as i suspect VS Code is not doing the right thing.

**Comment by mattfysh** [comment]
I'd love these features too, I'm wondering if there is a way around by using custom launch commands in launch.json. Can you set processId to `0` and then on launch, run a custom script that selects the process id for you?
