### ISSUE TITLE
Add logging info for fileCreation/Deletion/Changed

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4741]
Requested at https://github.com/microsoft/vscode-cpptools/issues/4418#issuecomment-564445774

**Comment by bobbrow** [comment]
I believe this was already done.

**Comment by BillDenton** [comment]
I'm using the insider's channel (0.26.3). When is this likely to appear? Thanks.

**Comment by sean-mcmanus** [comment]
@BillDenton 0.26.3 is not the Insiders channel. 0.27.0-insiders3 is the current insiders vsix: https://github.com/microsoft/vscode-cpptools/releases . Be aware there are a couple "known issues" we're working on fixing soon for our next Insiders (i.e. wrong settings in multi-root, and opening a file without a folder).

**Comment by BillDenton** [comment]
@sean-mcmanus That's strange as I've got it set to insiders update:
![image](https://user-images.githubusercontent.com/17859340/76890911-12478100-6880-11ea-992c-8755035fb036.png)
![image](https://user-images.githubusercontent.com/17859340/76890944-1d021600-6880-11ea-9970-0574d59d789f.png)
Is there something else I need to do?

**Comment by sean-mcmanus** [comment]
Check your extensions.autoUpdate setting. If that is false, we won't auto-install the latest Insiders, i.e. you could change autoUpdate to "true", get the latest insiders, and then switch it to false to avoid future insider updates until the setting is changed. If that doesn't work, there could be some error/problem connecting to the server (GitHub) (Toggle Developer Tools console might show an error), in which case the workaround is manually download the vsix matching your OS and running the "Install from vsix..." command.

**Comment by BillDenton** [comment]
@sean-mcmanus Thanks, it has installed the new version. Whilst building I can see:
cpptools/fileCreated: file:///<folder root>/.git/lfs/tmp/065377983
I thought everything in the .git folder would be excluded.
I can also see some files specific to our setup which I should be able to exclude. I've got a directory "a/b" in the "Files: Exclude", but cpptools is stilll seeing files in it. This directory is where our build system stores a lot of temporary files.

**Comment by sean-mcmanus** [comment]
@BillDenton I've moved that issue to https://github.com/microsoft/vscode-cpptools/issues/5141 .

**Comment by BillDenton** [comment]
Would changing "Files: Watcher Exclude" help? I've only got:
"files.watcherExclude": {
  "**/.git/objects/**": true,
  "**/.git/subtree-cache/**": true,
  "**/node_modules/*/**": true
}
which I think are the defaults. I don't need "node_modules"

**Comment by sean-mcmanus** [comment]
It appears that doesn't work. We use the vscode.workspace.createFileSystemWatcher API, and it doesn't appear to obey files.watcherExclude and we don't have any code that explicitly processes that setting. Might be a VS Code bug or "by design", not sure.
