### ISSUE TITLE
Language server/intellisense diagnostic info is out of date and inconsistent

### ISSUE THREAD

**Issue by peterschussheim** [microsoft/vscode-cpptools#4743]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS 10.14.6

- VS Code Version:

Version: 1.42.0-insider
Commit: cbeff45f80213db0ddda2183170281ed97ed3b12
Date: 2019-12-13T07:05:12.353Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

- C/C++ Extension Version: 0.26.2

- A clear and concise description of what the bug is.

Diagnostic information from extension fails to update when making changes to files. 

**Expected behavior**

I expected this extension to have **realtime** intellisense/diagnostics (ie: as I type and correct errors, the errors should go away).

**Comment by RobFosterNYC** [comment]
Im having the same problem.
Its like a 30 to 60 second delay before intellisense kicks in when I am trying to fix something.
I dont know if its right or wrong, I would have to sit there for 30 to 60 seconds for intellisense to figure out I made a change.
**Expected Behavior:**
I should be able to type and in real time intellisense is suppose to kick in and do its thing as I type.

**Comment by sean-mcmanus** [comment]
Can someone give more repro info? Does this only happen with certain large TUs? I'm not reproing this issue in my test files. Do you see the red flame during the delayed time? Does it repro only when making certain edits? Are the edits global or local to a function? Does saving have any effect? Are the Microsoft.VSCode.CPP processes using CPU before edits are made? Are edits being made to a header or source file?

It sounds like @peterschussheim is hitting an issue with permanently stuck squiggles, and not just delayed results. It's possible a crash is occurring if squiggles are stuck (I don't remember if we clear squiggles on an IntelliSense process crash...we did at one point, but VS doesn't).

**Comment by peterschussheim** [comment]
# cpp-tools intellisense issues

Hi @sean-mcmanus, thanks for your reply! I've included some information that
should help you understand my issues.

### Example repo

[Example cpp project using cmake and catch2 for testing.](https://github.com/peterschussheim/mre-cpp/)

## Reproduction

### Case 1:

1. Clone the repo above and build and execute tests. Project should build and
   all tests should pass.
2. Edit line 3 of `src/Fibonacci.cpp`, as shown below, re-build and you should
   receive a linker error as a result of the change we just made:
   
![editor_not_detecting_errors](https://user-images.githubusercontent.com/3654683/71016396-174f3580-20c3-11ea-9dfa-ad4d849e0710.jpg)


So, my question is, **why is the editor not showing any error/diagnostic
information about this change**?

### Case 2:

1. Edit line 4 of `src/Fibonacci.hpp`, changing "Fibonacci" to "Fibonacci1".
   ![Code - Insiders013](https://user-images.githubusercontent.com/3654683/71016425-20d89d80-20c3-11ea-9d54-d909af86c94a.jpg)
2. `tests/FibonacciTest.cpp` displays the **correct** diagnostic info:
   ![Code - Insiders014](https://user-images.githubusercontent.com/3654683/71016426-20d89d80-20c3-11ea-929e-78a980690539.jpg)

However, when we switch to `Fibonacci.cpp`, incorrect information is displayed:
![Code - Insiders015](https://user-images.githubusercontent.com/3654683/71016427-21713400-20c3-11ea-814a-236d27d5bb2c.jpg)
![Code - Insiders016](https://user-images.githubusercontent.com/3654683/71016428-21713400-20c3-11ea-9689-03426094653f.jpg)

## Related questions and comments

- what is the purpose of this setting? When would I use it, why would I NOT use
  it, what benefit does using `compile_commands.json` for intellisense?:
![when_is_this_useful](https://user-images.githubusercontent.com/3654683/71016429-21713400-20c3-11ea-9909-a4d7c8e7d30f.jpg)

- is there a real time status indicator for the status bar to update the user
  what the extension is doing in the background? If not, this would be a
  valuable feature.

- notify user when language server crashes or automatically restart it.

**Comment by sean-mcmanus** [comment]
I'll check out your repro project...

If you're using CMake, then the CMake Tools configurationProvider is the recommended way to get configured accurately. compileCommands.json is the 2nd option if you can generate that -- it allows every file to have different (the correct) include paths, defines etc. We're also working on a Makefile extension. But if your project is simple enough to use just c_cpp_properties.json (includePath, etc.), then that is fine. Maybe instead of showing the compile_commands.josn prompt we should prompt for installing the CMake Tools extension (if it's already installed we do show a prompt to set configurationProvider).

We show the flame and database icons in the status bar. It could be improved though. We also have a loggingLevel that can be increased to "Debug" which shows more info.

We have code to auto-restart the IntelliSense process and language server when it crashes, but if it crashes too much it'll be disabled. We also log an error message, but we could do a better job of informing users (or having some setting to enable this for users who are interested in reporting crash bugs), since it's easy to crash and users not be aware (sort of intentional).

**Comment by peterschussheim** [comment]
Hi Sean,

Thanks for the info. I've had some time to play around with configuration and
setup CMake Tools (which is quite good).

I have some feedback:

It would be a good idea to prompt the user to install CMake Tools ext if
CPP-tools detects CMake config files. Furthermore, there could be many more
"hints" aimed at helping new users understand how `c_cpp_properties.json`
relates to core VSCode components. I had to read and re-read the docs and a few
github issues to get something working.

The flame and database icons should be a single icon which shows the progress of
the background task, rather than having to hover over an icon that usually
disappears immediately. Additionally, this status icon should remain visible
always.

Of the crashed IntelliSense process and language server crashes, this is likely
what is causing my "stale" diagnostic info. I've noticed that while writing
code, the language server info works OK for a while but once I make a typo or
other error, the syntax highlighting, IntelliSense, and diagnostics break.

It would be very useful if there were some comparison and/or table comparing
core c++ features that are in-progress/implemented to what is available in VS
2019 and even better, clarify that goals of this project.

**Comment by sean-mcmanus** [comment]
Oh, looks like I missed some of your previous comments:

* Case 1: IntelliSense doesn't report linker errors. The same behavior occurs with VS. It's a known missing feature.
* Case 2: Isn't reproing for me (using 0.26.3-insiders2 and the CMake Tools extension). Are you still hitting this bug?

We're tracking the unnecessary compile_commands.json prompt with https://github.com/microsoft/vscode-cpptools/issues/3972 .

We currently show CMake Tools as a recommended extension when CMakeLists.txt is opening (via the VS Code mechanism, which doesn't currently support a "project contains CMakeLists.txt" option).

We have issue that discusses potential icon rework at https://github.com/microsoft/vscode-cpptools/issues/4117 .

We show "Connection to server got closed. Server will not be restarted" if the main process crashes, and something like "Failed to send request to server" when the IntelliSense process crashes. Are you seeing any of those messages in your logs?

We don't currently have a feature comparison table available (I've filed an issue at https://github.com/microsoft/vscode-cpptools/issues/4792 ), but we have "Works in VS" tag we use: https://github.com/microsoft/vscode-cpptools/issues?utf8=%E2%9C%93&q=is:open+is:issue+label:%22Works+in+VS%22 . The goal of the project is to become closer to VS in feature parity. We have some progress tracking at https://github.com/microsoft/vscode-cpptools/projects/4 and at the various milestones https://github.com/microsoft/vscode-cpptools/milestones .

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
