### ISSUE TITLE
Auto generate starting code when starting or opening a new .cpp file

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode-cpptools#4744]
It gets a bit tedious and annoying having to keep typing the same thing over and over,
every time I open a new .cpp file.  To be forced to type:

```
#include <iostream>
using namespace std;

int main(){
    return 0;
}
```

Is there any way that microsoft can create a switch within both VS-Code & Visual Studio
preferences, where one can switch on auto generate this code.?
Or is there a extension I don't know about that does this already ?
Its a bit frustrating having to type this over and over and over again.  :/

**Comment by sean-mcmanus** [comment]
VS Code supports adding user-defined snippets, but our extension doesn't yet support easily integrating those into our own snippets -- we're tracking that with https://github.com/microsoft/vscode-cpptools/issues/3556 . That might be sufficient for you if you don't mind typing some text to invoke the snippet completion, but we could use this issue to track the "new file template" feature.
