### ISSUE TITLE
GDB hardware breakpoints support

### ISSUE THREAD

**Issue by changbindu** [microsoft/vscode-cpptools#4745]
Hi~
Dear vscode developers, could you considier to add hardware breakpoints support for gdb? hardware breakpoint is very usefull for kernel debugging since soft breakpoints sometimes is not working which requres modifying memory. For example, when debugging linux kernel using qemu debugger, 'hbreak' should be used instead of 'break', otherwise we may crash the kernel.

**Comment by WardenGnaw** [comment]
Thank you for your feedback. This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/1410 

Can you please react to the issue to upvote the Feature Request.

**Comment by changbindu** [comment]
hello, Idont think this is a duplicate of #1410.   #1410 is about data watchpoint breakpoints, while this one is for instruction hardware breakponit.

**Comment by changbindu** [comment]
For gdb, hardware bp command is hbreak, soft breakpoint is break.

**Comment by WardenGnaw** [comment]
@changbindu Thank you for the clarification. This will be dependent on VSCode providing a way through the UI to set hardware breakpoints.

**Comment by cdacamar** [comment]
:+1: to this feature.  It is one missing from VSCode which is the top reason keeping me from using VSCode full time.

**Comment by mhlau233** [comment]
check this
https://bugzilla.redhat.com/show_bug.cgi?id=839263

**Comment by gabriserra** [comment]
Hi guys, I think I've found a (ugly) workaround. If you are using a launch configuration with the MI interpreter, you can create a hardware breakpoint with `setupCommands`

```
"setupCommands": [
                ... // your commands
                {
                    "description": "Hardware breakpoint at start",
                    "text": "-break-insert -h -f start", // specify your entry point label, mine was 'start'
                    "ignoreFailures": true
                }
            ],
 ```
 
 You have also to add a breakpoint from the GUI because VS Code continues on breakpoint it can't recognize.

**Comment by ysun46** [comment]
@changbindu Recently, I setup the environment to debug linux kernel with Qemu and vscode.
It seems the vscode probably support hbreak. I'm not pretty sure, but the breakpoints indeed work well even run qemu with -enable-kvm. Correct me is my misunderstanding.
watching this issue.

**Comment by gabriserra** [comment]
@ysun46 I tested by myself and it seems like after the first HW breakpoint, the other breakpoints work. It's the first step :)

However, enabling `engineLogging: true` you can see VS Code places SW breakpoints when you hit the "red dot" button adjacent to the line number.

I.e.

```
1: (182992) <-1030-break-insert -f entry.S:69
1: (182993) ->1030^done,bkpt={number="9",type="breakpoint",disp="keep",enabled="y",addr="0x000000000000709b",file="os/src/arch/x86_64/entry.S",fullname=".../os/src/arch/x86_64/entry.S",line="69",thread-groups=["i1"],times="0",original-location="entry.S:69"}
1: (182993) ->(gdb)
```

As you can see it executes `break-insert -f entry.S:69` but it misses the `-h` option needed to insert the hardware one. It's all about giving the possibility to choose the kind of breakpoint you want to place.

**Comment by ysun46** [comment]
@gabriserra Thanks for your info. I see, the red dot is sw breakpoint.
But I'm a little confused now, since those are sw breakpoints, why do they work?  Considering about breakpoints in GDB. I tried debug kernel with GDB+QEMU, the software breakpoints would not work there, but only hbreak does at least when I enabled kvm.
Beside, any chance could I place hbreak in vscode ?

**Comment by changbindu** [comment]
> @gabriserra Thanks for your info. I see, the red dot is sw breakpoint. But I'm a little confused now, since those are sw breakpoints, why do they work? Considering about breakpoints in GDB. I tried debug kernel with GDB+QEMU, the software breakpoints would not work there, but only hbreak does at least when I enabled kvm. Beside, any chance could I place hbreak in vscode ?

As QEMU, the gdbstub implementation is different for tcg and kvm. When running with tcg, software bp and hardware bp are actually the same thing, both work well. 
When running with kvm mode, they are different. The hardware bp uses the hardware debug features in  CPU while software bp does not. Sometimes the software bp can not work well.

**Comment by ysun46** [comment]
> > @gabriserra Thanks for your info. I see, the red dot is sw breakpoint. But I'm a little confused now, since those are sw breakpoints, why do they work? Considering about breakpoints in GDB. I tried debug kernel with GDB+QEMU, the software breakpoints would not work there, but only hbreak does at least when I enabled kvm. Beside, any chance could I place hbreak in vscode ?
> 
> As QEMU, the gdbstub implementation is different for tcg and kvm. When running with tcg, software bp and hardware bp are actually the same thing, both work well. When running with kvm mode, they are different. The hardware bp uses the hardware debug features in CPU while software bp does not. Sometimes the software bp can not work well.

I know tcg and kvm are different, kvm requires hbreak. But my question is why does SW bp work in VSCode even when I running QEMU with option '-enable-kvm' .   My qemu command line `qemu-system-x86_64 -enable-kvm -m 2048 -smp 1 -cpu max -s -S -kernel ./bzImage -hda ./ubuntu20.10_mini.img -vga none -nodefaults -nographic -append \"root=/dev/sda3 nokaslr console=ttyS0\" -serial mon:stdio`.

**Comment by changbindu** [comment]
> I know tcg and kvm are different, kvm requires hbreak. But my question is why does SW bp work in VSCode even when I running QEMU with option '-enable-kvm' . My qemu command line `qemu-system-x86_64 -enable-kvm -m 2048 -smp 1 -cpu max -s -S -kernel ./bzImage -hda ./ubuntu20.10_mini.img -vga none -nodefaults -nographic -append \"root=/dev/sda3 nokaslr console=ttyS0\" -serial mon:stdio`.

It depends on when the sw bp is applied to guest, and when the debugged code loads. Qemu modify guest memory to insert a soft bp, but if your code load after that or the memory is changed by guest again, then the soft bp won't work. So hw bp is the best choice here.

**Comment by gabriserra** [comment]
> @gabriserra Thanks for your info. I see, the red dot is sw breakpoint. But I'm a little confused now, since those are sw breakpoints, why do they work? Considering about breakpoints in GDB. I tried debug kernel with GDB+QEMU, the software breakpoints would not work there, but only hbreak does at least when I enabled kvm. Beside, any chance could I place hbreak in vscode ?

I cannot say why precisely. In my specific case, breakpoint software worked quite well but only if being placed after the binary was loaded into QEMU. So I had to "do the trick" placing the first breakpoint (at the start) as hardware one and using the software ones. However, each time I loaded the binary, I had to delete and place again each software breakpoint. Now, as you were mention, after the first hardware one, the software ones work without deleting/adding again. But I cannot say why.

**Comment by ysun46** [comment]
> > @gabriserra Thanks for your info. I see, the red dot is sw breakpoint. But I'm a little confused now, since those are sw breakpoints, why do they work? Considering about breakpoints in GDB. I tried debug kernel with GDB+QEMU, the software breakpoints would not work there, but only hbreak does at least when I enabled kvm. Beside, any chance could I place hbreak in vscode ?
> 
> @ysun46 I cannot say why precisely. In my specific case, sw bps worked quite well but only if being placed after the binary was loaded into QEMU. So I had to "do the trick" placing the first breakpoint (at the start) as hardware one and using the software ones. However, each time I loaded the binary, I had to delete and place again each software breakpoint. Now, as you were mention, after the first hardware one, the software ones work without deleting/adding again. But I cannot say why.

@gabriserra I see. Anyway the vscode is working well with your trick "Hardware breakpoint at start". It pretty good we only need this workaround to debug kernel with vscode, IMO. 😄 
@gabriserra  and @changbindu 's explanations do make sense!   Thank you all.

**Comment by WardenGnaw** [comment]
With https://github.com/microsoft/vscode-cpptools/pull/7449, you have an option in your `launch.json` to set all breakpoints as hardware breakpoints.
```
"hardwareBreakpoints": {
   "require": true,
   "limit": 4
}
```

@aleun

**Comment by ysun46** [comment]
> With #7449, you have an option in your `launch.json` to set all breakpoints as hardware breakpoints.
> 
> ```
> "hardwareBreakpoints": {
>    "require": true,
>    "limit": 4
> }
> ```
> 
> @aleun
@aleun  Thanks your info.
Can I get that change just by updating my VScode insider? And just curious why there is a "limit" needed? What's the max value of that "limit"?

Thanks
   --Sun, Yi

**Comment by aleun** [comment]
> Can I get that change just by updating my VScode insider?

This feature has been available since version 1.4.0 of this extension, so as long as your version is at or above that, you should be able to use it.

> And just curious why there is a "limit" needed? What's the max value of that "limit"?

This was added to support environments in which there is a restricted number of hardware breakpoints, as commonly seen when debugging embedded devices. If you have no need for this, you can omit the "limit" key, and then the number of breakpoints will be unrestricted.

**Comment by sean-mcmanus** [comment]
@WardenGnaw Can this issue be closed? It's assigned the 1.4 milestone.

**Comment by WardenGnaw** [comment]
yes

**Comment by mao-china** [comment]
> With #7449, you have an option in your `launch.json` to set all breakpoints as hardware breakpoints.
> 
> ```
> "hardwareBreakpoints": {
>    "require": true,
>    "limit": 4
> }
> ```
> 
> @aleun

when i add hardwareBreakpoints option in my launch.json, it shows : property hardwareBreakpoints is not allowed.
can you give me some suggestions?
thank you!

vscode version:v1.67.2
cpptools version:v1.9.8
my launch.json is:

    "version": "0.2.0",
    "configurations": [
        {
            "name": "Cortex Debug",
            "cwd": "${workspaceRoot}",
            "executable": "./build/stm32f401.elf",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            "configFiles": [
                "./.openocd/stm32f401.cfg"
                ],
            "runToEntryPoint": "Reset_Handler",
            "hardwareBreakpoints": {
                "require": true,
                "limit": 6
            }
        }
@WardenGnaw

**Comment by QuocTrung76** [comment]
Can I simultaneously enable hardware breakpoint and software breakpoint?
