### ISSUE TITLE
symbols parsing error after using 'CMake:Configure' of CMake tools

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#4747]
- VS Code Version: 1.41.0
- C/C++ Extension Version: 0.26.2
- CMake Tools Version: 1.2.3

I have a large project which is based on CMake. So I use CMake Tools and Cpptools extension. When I run "CMake:Configure" of CMake Tools, this extension generated compile-commands.json and I set "C_Cpp.default.configurationProvider" to "vector-of-bool.cmake-tools"(Only set this configuration, no others).  They worked very well for me. "go to definition" and colorazation of cpptools are correct.

But when I run "CMake:Configure" of CMake tools again, some symbols can't be got parsed by cpptools. these symbols' "Go to definition" and Colorization have wrong behavior. Many wavy lines occurs under these symbols, these wavy lines show error information like "xxxx is undefined" and so on. Acturally these codes are right. If I reload VSCode windows(press F1 and run "reload window"), they will get right again. This is a bug?

**Comment by Lennon925** [comment]
If I add this configuration："C_Cpp.default.compileCommands": "${workspaceFolder}/build/compile_commands.json",  the same errors will always show even though you reload vscode window. ${workspaceFolder}/build is CMake tools extension's cmake.buildDirectory.

![234567](https://user-images.githubusercontent.com/39362073/70875976-d687eb80-1ff2-11ea-99fe-b01fe50b872e.PNG)

So I guess when run "CMake:Configure" of CMake tools again, the behavior that cpptools can't parse symbols correctly is related with this configure "C_Cpp.default.compileCommands"? During this period of running "CMake:Configure", cpptools adds  "C_Cpp.default.compileCommands": "${workspaceFolder}/build/compile_commands.json" to configurations implicitly  and use new conf to parse symbols ?

**Comment by sean-mcmanus** [comment]
If you're using CMake and CMake Tools as the configurationProvider, then it's not recommended to have compileCommands set. Does this bug repro when the compileCommands is not set?

Our pending 0.26.3-insiders fixed some custom configuration bugs.

**Comment by Lennon925** [comment]
> If you're using CMake and CMake Tools as the configurationProvider, then it's not recommended to have compileCommands set. Does this bug repro when the compileCommands is not set?
> 
> Our pending 0.26.3-insiders fixed some custom configuration bugs.

This bug still repros when the compileCommands is not set.(As descriptions on first floor.)

**Comment by sean-mcmanus** [comment]
And it repros with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3-insiders ? If so I can try the repro tomorrow.

@andreeis Have you seen any issues like this reported on the CMake Tools extension?

**Comment by Lennon925** [comment]
> And it repros with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3-insiders ? If so I can try the repro tomorrow.
> 
> @andreeis Have you seen any issues like this reported on the CMake Tools extension?

let me try~

**Comment by Lennon925** [comment]
> And it repros with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3-insiders ? If so I can try the repro tomorrow.
> 
> @andreeis Have you seen any issues like this reported on the CMake Tools extension?

This bug still repros on 0.26.3-insiders. CMake Tools seems to call some api of cpptools, so maybe this results from CMake Tools.

**Comment by sean-mcmanus** [comment]
I don't seem to repro the bug. Can you look at the C/C++ debug logs in the Output window and look for any errors or buggy behavior, such as any reparsing or database clearing going on that shouldn't? Do you see the database size change after the 2nd configure?

Under normal conditions, the 2nd configure should cause the CMake Tools extension to send us new config info (shown in the logs) and the IntelliSense clients will restart, but not database changes should occur. If the configuration info we get is incorrect or not received then it would be a CMake Tools bug.

**Comment by Lennon925** [comment]
@sean-mcmanus ，

Yes, after the new config info received, wavy lines occurs. where is the configure that cpptools used after reloading window from?

**Comment by sean-mcmanus** [comment]
Ok, wavy lines is from IntelliSense being misconfigured and not the database (I think I misread the original post). Can you look at the logs or compare the output of C/C++: Log Diagnostics to see what changed before and after the squiggles appear?

**Comment by sean-mcmanus** [comment]
I'm not sure what you mean by "where is the configure that cpptools used after reloading window from".

**Comment by sean-mcmanus** [comment]
We need to know if the new config from CMake Tools is incorrect or if something else is going wrong.

**Comment by Lennon925** [comment]
I found 

> Ok, wavy lines is from IntelliSense being misconfigured and not the database (I think I misread the original post). Can you look at the logs or compare the output of C/C++: Log Diagnostics to see what changed before and after the squiggles appear?

1. Custom configurations received(includePath, intelliSenseMode, compilerPath and compilerArgs)
1. Custom browse configuration received:(BrowsePath)
1. cpptools/didChangeCustomConfiguration
1. cpptools/didChangeCustomBrowseConfiguration
1. sending compilation args for xxxxx.c
1. Shutting down IntelliSense server:
1. ueueing IntelliSense update for files in translation unit of xxxxx.c
1. cpptools/cpptools_finishUpdateSquiggles
Aborting tag parse at root
Error squiggle count: 50
Populate include completion cache.
Error squiggle count: 50
Discovering files...
Update IntelliSense time (sec): 14.01
cpptools/cpptools_finishUpdateSquiggles
cpptools/resumeParsing
Done discovering files.
Parsing open files...
Parsing remaining files...
Done parsing open files.

And then wavy lines occurs.

**Comment by Lennon925** [comment]
> I'm not sure what you mean by "where is the configure that cpptools used after reloading window from".

After window reloaded, no wavy lines occurs. At this time, where does configuration intellisense used come from?(at this time, I don't use CMake:Configure command so CMake tools doesn't provide new configuration for intellisense).

If cpptools doesn't reveive configuration from CMaketools, it's possible to fix this issue?

**Comment by sean-mcmanus** [comment]
It sounds like your CMake.configureOnOpen setting is false? I normally have that set to true, so after a reload window it will get the same results as when I run CMake:Configure manually.

It looks like the wavy lines are being caused by CMake Tools not configuring something properly.

Without configuring, the c_cpp_properties.json or C_Cpp.default.* includePath/etc. would be used (or compile_command.json if that is set).

**Comment by Lennon925** [comment]
> It sounds like your CMake.configureOnOpen setting is false? I normally have that set to true, so after a reload window it will get the same results as when I run CMake:Configure manually.
> 
> It looks like the wavy lines are being caused by CMake Tools not configuring something properly.
> 
> Without configuring, the c_cpp_properties.json or C_Cpp.default.* includePath/etc. would be used (or compile_command.json if that is set).

Yes, I set  CMake.configureOnOpen to false. I didn't use the c_cpp_properties.json or C_Cpp.default.* includePath/etc. I just used "C_Cpp.default.configurationProvider" : "vector-of-bool.cmake-tools". when window reloaded, it's OK

**Comment by sean-mcmanus** [comment]
But after the reload and things are working, what configuration info is being used? It sounded like you were saying the configurationProvider info wasn't being used and it was falling back to some defaults we choose.

**Comment by Lennon925** [comment]
> But after the reload and things are working, what configuration info is being used? It sounded like you were saying the configurationProvider info wasn't being used and it was falling back to some defaults we choose.

I don't know what configuration info cpptools is using after the reload. My configuation is as follow:

1. CMake.configureOnOpen: false
1. C_Cpp.default.configurationProvider : vector-of-bool.cmake-tools 
1. a Compile-Commands.json CMake generated (but I didn't set C_Cpp.default.compileCommands)

NO other configurations(no c_cpp_properties.json and so on )

**Comment by sean-mcmanus** [comment]
It sounds like it's falling back to "defaults" for everything (i.e. includePath being "${workspaceFolder}/**" and compilerPath being whatever we can auto-detect). The loggingLevel and C/C++: Log Diagnostic should show what is being used.

**Comment by Lennon925** [comment]
> It sounds like it's falling back to "defaults" for everything (i.e. includePath being "${workspaceFolder}/**" and compilerPath being whatever we can auto-detect). The loggingLevel and C/C++: Log Diagnostic should show what is being used.

Hi Sean, I solved this issue and it's not a bug. I run wrong CMakelist.txt before.
