### ISSUE TITLE
command 'C_Cpp.ConfigurationEditJSON' not found

### ISSUE THREAD

**Issue by thecoder138** [microsoft/vscode-cpptools#4749]
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by sean-mcmanus** [comment]
Can you give more repro info?

**Comment by thecoder138** [comment]
So this is very recent (unfortunately I dont have a timeline)  issue, I have my c++ repository. I use the popular C++ extension for intellisense. When I open command palette and try to configure c++ extension settings, I get above error.

**Comment by sean-mcmanus** [comment]
Can you try uninstalling/reinstalling the C/C++ extension? Maybe restarting VS Code in between or making sure the extension directory is deleted in case VS Code keeps it around.

**Comment by thecoder138** [comment]
Restart black magic worked! Thanks!
