### ISSUE TITLE
Non-recursive includes from workspaceRoot

### ISSUE THREAD

**Issue by johnmellor** [microsoft/vscode-cpptools#475]
Currently `${workspaceRoot}` is [implicitly included](https://github.com/Microsoft/vscode-cpptools/issues/72#issuecomment-226257014) in the includePath, and is _recursively_ searched for header files.

This causes problems in projects which have files with the same name in different paths. For example:

```
base/string16.h
ui/string16.h
third_party/somelibrary/base/string16.h
```

Now when a file does `#include "base/string16.h"`, VS Code finds _all three_ of the string16.h headers, and the indexer gets confused about which one to use (it seems to default to `ui/string16.h` since that has the shortest path?). There are two problems here:

1. It's presumably a bug that the indexer matches `ui/string16.h` when you `#include "base/string16.h"`?

2. Finding both `base/string16.h` and `third_party/somelibrary/base/string16.h` is a more fundamental issue though. It may be possible to heuristically address this by preferring exact matches that don't require recursion, or preferring shorter paths. But for a robust solution there probably needs to be a way to disable the implicit recursive search of `${workspaceRoot}` for includes. I tried adding an explicit includePath of `"${workspaceRoot}/*"` since the tooltip suggests specifying '*' to indicate non-recursive search, but that didn't seem to make any difference (presumably because includePath is in addition to the implicit workspace search, and/or because `${workspaceRoot}` [expansion wasn't yet supported](https://github.com/Microsoft/vscode-cpptools/issues/366#issuecomment-263388605)?).

VS Code version: 1.10.0-insider
cpptools version: 0.10.0
OS: Ubuntu 14.04

**Comment by sean-mcmanus** [comment]
The Go to Definition just looks at the strings16.h and ignores the "base/" part. We may be able to fix this in a future release.

We may add a setting to remove the workspaceRoot, but as a workaround for now, ${workspaceRoot} could be manually removed by modifying the javascript (this will cause # symbol search to not find stuff in non-opened source files, but opened source files will still have symbols parsed). See https://github.com/Microsoft/vscode-cpptools/issues/374 for the details or let me know if you hit any problems.

**Comment by bobbrow** [comment]
A new setting was added in 0.10.2 that allows you to disable the automatic recursive parsing of the `${workspaceRoot}`.  Let us know if that resolves your issue.

**Comment by janjongboom** [comment]
That patch does not solve the problem described in this issue (it helps a bit though).

Let's say I have a directory structure like this:

```
mbed-os
    - mbed.h
    - folder1
        - rtos.h
    - folder2
        - unrelated-file.h
```

I create my ``c_cpp_properties.json`` like this:

```
        {
            "includePath": [
                "${workspaceRoot}/mbed-os",
                "${workspaceRoot}/mbed-os/folder1"
            ],
            "name": "Mac",
            "browse": {
                "databaseFilename": "",
                "limitSymbolsToIncludedHeaders": false
            }
        }
```

However, the includePaths are searched through recursively and thus `folder2` is still added to intellisense.

We need a setting to not search through includePaths recursively.

Related: #374.

/cc @sg-

**Comment by bobbrow** [comment]
You need to add a * to the end of the path if you don't want it to be recursive.

```
    "includePath": [
        "${workspaceRoot}/mbed-os/*",
        "${workspaceRoot}/mbed-os/folder1/*"
    ],
```

**Comment by janjongboom** [comment]
@bobbrow Great!
