### ISSUE TITLE
Not able to interact with IDE - While following a course. Am I doing something wrong?

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode-cpptools#4751]
Im new to C++ and i'm having a small little problem.
When running the code for C++ by pressing the |> play button in vs-code to execute the code,
I am not able to interact with the console.  strangely it only results into the output.
.How do I fix this.
im running MingW64.  

I was trying to press #1 in the running code.
.
![problem interacting with code game](https://user-images.githubusercontent.com/18384135/70957124-1971af80-2043-11ea-8a96-8232bdb6f39a.png)

**Comment by sean-mcmanus** [comment]
Have you seen https://code.visualstudio.com/docs/cpp/config-mingw ? That explains how to setup building and debugging with mingw.

How are you launching the debugger?

What does your task.json and launch.json look like?

You want to get the program to output stuff in the Terminal pane (or an external console) and not in the Output window (which is read only).

**Comment by RobFosterNYC** [comment]
If I could get it to output in the 'Terminal' 
that would be awesome, so I don't have to deal with external consoles at all.

A1: - by pressing the |> play button in vs-code on the upper right hand side of the IDE
and sometimes by right clicking and selecting 'Run Code'.

A2: - I dont have any task.json or launch.json in my folder.
I just create a .cpp file write some code as I am learning through video course,
then either press |> play button on the upper right side of the IDE and also sometimes right cliking and choosing 'Run Code'...
Sorry, I am new to C++, please bare with my very little knowledge of C++,
as I continue to learn it and hopefully master it one day :)

This is my c_pp_properties.json
```
{
    "configurations": [{
        "name": "Win64",
        "includePath": [
            "${workspaceFolder}/**"
        ],
        "defines": [
            "_DEBUG",
            "UNICODE",
            "_UNICODE"
        ],
        "windowsSdkVersion": "10.0.18362.0",
        "compilerPath": "C:/Mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/g++.exe",
        "intelliSenseMode": "gcc-x64",
        "cppStandard": "c++17",
        "cStandard": "c11"

    }],
    "version": 4
}
```

> **UPDATE: - I just created the task.json and task.json**

. TASK:
```
{
    "version": "2.0.0",
    "tasks": [{
        "label": "build hello world",
        "type": "shell",
        "command": "g++",
        "args": ["-g", "-o", "helloworld", "helloworld.cpp"],
        "group": {
            "kind": "build",
            "isDefault": true
        }
    }]
}
```
LAUNCH:
```
{
    "version": "0.2.0",
    "configurations": [{
        "name": "(gdb) Launch",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder}/helloworld.exe",
        "args": [],
        "stopAtEntry": true,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false,
        "MIMode": "gdb",
        "miDebuggerPath": "C:\\mingw-w64\\x86_64-8.1.0-win32-seh-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
        "setupCommands": [{
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
        }]
    }]
}
```

Thank you for being very patient with me and understanding im new.
Its very much appreciated :D

My current folder layout list.  I threw out many .cpp files as I only used them to practice code.
So just cleaned up a bit.
.
![My Insiders Folder layout](https://user-images.githubusercontent.com/18384135/70966204-729c0c00-2060-11ea-9dd3-3b4520b81771.png)

> Even with the settings files created, still doesnt work.
> Still having the problem

**Comment by sean-mcmanus** [comment]
Your task.json command is just g++ and no options.cwd is set so I'm not sure if it's invoking the correct compiler -- you might want to make those explicit.

What error or behavior are you getting? I wasn't able to debug with the externalConsole set to false, but changing it to true made it work. @pieandcakes @WardenGnaw Is this a known issue?

**Comment by sean-mcmanus** [comment]
Looks like the debugger integrated terminal issue is https://github.com/microsoft/vscode-cpptools/issues/2998 .

**Comment by sean-mcmanus** [comment]
Actually, the bug is https://github.com/microsoft/vscode-cpptools/issues/3140 .

**Comment by RobFosterNYC** [comment]
This is starting to get annoying, because its preventing me from following a course.
I am really trying to fix this problem.
When I press - CNTRL + SHFT + B  this is the output I get. - (trying to follow a learning course)

![Starting to seriously piss me off](https://user-images.githubusercontent.com/18384135/71053466-7ab98180-211c-11ea-9d66-774c45b82bb1.png)

If I also right click anywhere in the code and Select RUN CODE (or) I press the PLAY button on 
the top right of the VS-Code IDE to run the code, it wont render the code.

![Running Code Problems 3](https://user-images.githubusercontent.com/18384135/71053742-72157b00-211d-11ea-808c-b3c9c61e3b66.png)




And also when it does decide to run the code I cant type anything to interact with the rendered code,
because it defaults to the output of the terminal and not in the terminal itself..

This is getting very frustrating when I am trying to learn & follow courses,
but VS-Code is preventing me from doing so. - I need to interact with the code/terminal

**Comment by RobFosterNYC** [comment]
Code works when doing a debug,  but not when pressing the Play Button on top left of IDE or 
right clicking anywhere in the code and choosing 'Run Code'  ??
Grrr.
.
![Works in Debug 1](https://user-images.githubusercontent.com/18384135/71055801-f5869a80-2124-11ea-9dfe-2b963800df53.png)

.

![Works in Debug 2](https://user-images.githubusercontent.com/18384135/71055808-fa4b4e80-2124-11ea-9ec1-349f23cd7921.png)

.


And the picture immediately below is the result when trying to run the code the normal way,
by either pressing the play button in the IDE or right clicking and selecting 'Run Code'
I can not interact with the terminal and it shows the output only in the Output section of the terminal.
Very frustrating.
.
![Wont Run Code in Normal RUN](https://user-images.githubusercontent.com/18384135/71056042-d76d6a00-2125-11ea-9d52-0ce390e69036.png)

**Comment by pieandcakes** [comment]
@RobFosterNYC Like @sean-mcmanus mentioned, there is an issue that is blocking it from working when `externalConsole` is set to `false`. If you change it to `true` in your `launch.json` you should see a command window open separately that you can interact with that will help you work around the problem until we find a fix for it.

**Comment by pieandcakes** [comment]
Duplicate #3140

**Comment by RobFosterNYC** [comment]
@pieandcakes  
Even with the externalConsole set to **true** in my launch.json
nothing works,  no console comes up.  Still can not interact with console when executing code.
Also as I mentioned above, it works when I debug, but not when the code is executed normally.

**Comment by pieandcakes** [comment]
>>> Also as I mentioned above, it works when I debug, but not when the code is executed normally.

I don't understand what you mean by `executed normally` then. Hitting the `Play` button is debugging. If you go to the `Terminal` tab and type your executable, that should run it without debugging. Is that what you mean by `executed normally` ?

**Comment by RobFosterNYC** [comment]
@pieandcakes @sean-mcmanus
Ok,  i have pictures with step by step explanations - 
So please read the **red text** in the pictures to understand.

This first picture pressing play on upper right side of IDE does not work and does not want to
allow user to interact with code. and sends code to the output only, not to terminal.
.
![Z1 - Does not work this way](https://user-images.githubusercontent.com/18384135/71131552-fd951780-21c2-11ea-858f-b151d9be4123.png)


.
This picture I right click and select in the menu - Build and Debug.
The IDE properly executes the code and performs the debug mode. (by my understanding)
Sorry still learning this stuff..................................................  anyways....
This is the out debug information after right clicking and selecting "Build And Debug".
.
![Z1 - Buidl   Compile Works 1](https://user-images.githubusercontent.com/18384135/71131617-303f1000-21c3-11ea-80af-fb68b989a2d9.png)

.
.
This it the same view but viewing it within the Terminal TAB.
It shows the code properly executing and the user CAN interact with the code and play the game.
that is properly executed from the main code built.
.
![Z2 - rendered code and interaction](https://user-images.githubusercontent.com/18384135/71131712-7a27f600-21c3-11ea-8d43-2170d005208d.png)


I hope this better explains what I am trying to convey.
.Hope it gets fixed soon :)
thanks
.
