### ISSUE TITLE
IntelliSense stopped working when I type 'p'

### ISSUE THREAD

**Issue by jovinhz** [microsoft/vscode-cpptools#4754]
C++ intellisense stopped working every time when i type 'p'

Type: LanguageService
Describe the bug
OS and Version: Windows 10 x64
VS Code Version: 1.41.0
 C/C++ Extension Version: 0.26.3-insider

![1](https://user-images.githubusercontent.com/58977095/70992467-5a79ca80-20fc-11ea-93b6-1e0cccf7ac42.png)
![2](https://user-images.githubusercontent.com/58977095/70992499-69f91380-20fc-11ea-9cf2-b56ed782eb38.png)

the intellisense above should be :
![3](https://user-images.githubusercontent.com/58977095/70992510-72514e80-20fc-11ea-80af-664d10b40393.png)

The intellisense fixed when i restart vscode, but when i type 'p' again the instellisense stop working again

**Comment by yaroslavsadin** [comment]
I have similar symptoms but not related to typing 'p'. It works for the first time when I type something, then I select and delete what I've typed and after that I see the same as on screenshots.
Seems to be a bug in 0.26.3

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. I'm able to repro it with WSL/gcc-7. This is https://github.com/microsoft/vscode-cpptools/issues/4752 -- we were looking for a repro. There's a crash in the IntelliSense process caused by a change in how types are resolved/displayed.

We should have a fix "soon"...

**Comment by sean-mcmanus** [comment]
We won't have a fix until Wed/Thursday so I've unpublished 0.26.3-insiders until we can publish a fixed version.

**Comment by jovinhz** [comment]
> 
> 
> We won't have a fix until Wed/Thursday so I've unpublished 0.26.3-insiders until we can publish a fixed version.

Okay, Sir.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3-insiders2 .
