### ISSUE TITLE
Why there is no method for - is_closed  in the methods list.?

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode-cpptools#4757]
Here is an example
When implementing a - is_open() method to verify that a file has been opened, there is a method for that.
but, then when doing the same verification for a closed file method,
there is no method in the method list that has - is_closed() or is_close()
Here is an example code that spits out to console that a file has been opened by confirming it at the console when the execution happens.
Now I want to do the same thing, but for closing the file.
When I checked the methods list, it only has - is_open()  but it does not have  - is_closed()  or is_close() method.

```
#include <iostream>
#include <fstream>
#include <vector>

int main(){

    std::ofstream file ("Hello.txt", std::ios::app);

// ?   This makes sure the file has been opened and informs you that it has.
    if(file.is_open()){
        std::cout << "Document successfully opened" << std::endl;
    }

    std::vector<std::string> names;
    names.push_back("John");
    names.push_back("Steve");
    names.push_back("Anna");
    names.push_back("Mary");

    for(std::string name : names){
        file << name << std::endl;
    }


    file.close();
        if(file.is_closed(){
        std::cout << "Document successfully closed" << std::endl;
    }
    return 0;

}
```

**Comment by sean-mcmanus** [comment]
That is just the way the API was designed. You're expected to call !file.is_open() to test for "closed".

**Comment by RobFosterNYC** [comment]
Thank you, -- Though I would have preferred to type  :  anyways thanks for answering :)

```
file.close();
        if(file.is_closed(){
        std::cout << "Document successfully closed" << std::endl;
    }
```

**Comment by Colengms** [comment]
This issue was labeled as a 'question' and appears to have been answered. If there is something more here, please let us know. :)
