### ISSUE TITLE
How to fix include errors for gstreamer tutorials

### ISSUE THREAD

**Issue by hyattbaker** [microsoft/vscode-cpptools#4758]
Type: Debugger

**Describe the bug**
- OS and Version:UBUNTU 18.04
- VS Code Version:1.41
- C/C++ Extension Version:.26.3-insiders
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is: 
There are are include and path issues when compiling gstreamer tutorial files that run fine in system terminal.
 
![image](https://user-images.githubusercontent.com/1910123/71051024-ded84780-2114-11ea-907b-31c676a79a6e.png)

I can compile from the VSC terminal  using: 
![image](https://user-images.githubusercontent.com/1910123/71051159-5a39f900-2115-11ea-8889-3e0175065424.png)

tasks.json
![image](https://user-images.githubusercontent.com/1910123/71051290-d3d1e700-2115-11ea-8e2f-2b79adc16ff8.png)

**To Reproduce**
Install all the gstreamer files and test via linux terminal. 
The tutorial I"m trying to compile:

```
#include <gst/gst.h>

int
main (int argc, char *argv[])
{
  GstElement *pipeline;
  GstBus *bus;
  GstMessage *msg;

  /* Initialize GStreamer */
  gst_init (&argc, &argv);

  /* Build the pipeline */
  pipeline =
      gst_parse_launch
      ("playbin uri=https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm",
      NULL);

  /* Start playing */
  gst_element_set_state (pipeline, GST_STATE_PLAYING);

  /* Wait until error or EOS */
  bus = gst_element_get_bus (pipeline);
  msg =
      gst_bus_timed_pop_filtered (bus, GST_CLOCK_TIME_NONE,
      GST_MESSAGE_ERROR | GST_MESSAGE_EOS);

  /* Free resources */
  if (msg != NULL)
    gst_message_unref (msg);
  gst_object_unref (bus);
  gst_element_set_state (pipeline, GST_STATE_NULL);
  gst_object_unref (pipeline);
  return 0;
}

```
![image](https://user-images.githubusercontent.com/1910123/71051656-fdd7d900-2116-11ea-8155-35a4c1d26852.png)

**Comment by sean-mcmanus** [comment]
We don't read task.json (it's only for compiling).

The errors you are seeing are IntelliSense errors and not compiler errors. It sounds like you need to do an Edit Configuration command to set your includePath and/or compilerPath correctly, i.e. add the path to gst.

**Comment by hyattbaker** [comment]
I have the include path and it is still the same issue. I also added the compiler arguments there to with no success.  

![image](https://user-images.githubusercontent.com/1910123/71054168-f4526f00-211e-11ea-8c2c-23f21c3f4c11.png)

It looks like maybe I've created an issue in the wrong place.  Sorry about that. I wont waste anymore of your time.  


Thx,

Hyatt

**Comment by sean-mcmanus** [comment]
Okay, if you think it's not our bug, I'll close this issue, but it seems like the /usr/include/gstreamer-1.0/ would find the gst/gst.h if it exists there. Maybe if you set C_Cpp.loggingLevel to "Debug" or ran the C/C++: Log Diagnostics command it would give more info on why it's not working.
