### ISSUE TITLE
questionable "cwd" value in default build task

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-cpptools#4761]
Type: General

**Describe the bug**
- OS and Version: macOS 10.14.6
- VS Code Version: Insiders
- C/C++ Extension Version: 0.26.3

The default task.json contains a questionable value for the Current Working Directory (cwd):
```js
            "options": {
                "cwd": "/usr/bin"
            }
```
It doesn't make much sense that the "build task" for C/C++ runs in `/usr/bin` because any output produced by gcc should not live there and typically results in access errors because `/usr/bin` is not writable for most users.

If a user uses the default build task as a starting point for modification of the file, she will always run into problems unless the bogus "/usr/bin" is changed. 

 
**To Reproduce**
- create folder "test"
- open "test" in VS Code
- create (empty) "hello.c"
- open "hello.c"
- press "F1"
- type "task"
- select the "Configure Default Build Task" action
- select "C/C++: gcc build active"

Observe:
generated task.json has the `"cwd": "/usr/bin"`.

**Comment by sean-mcmanus** [comment]
I think it may have been done because Cygwin compilers don't run by default unless the cygwin64\bin folder is either added to the path or it's the cwd...but that seems like a lower priority scenario that we can let user's fix themselves.

After we change this, we should update the docs at https://code.visualstudio.com/docs/cpp/config-wsl too.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.2, although we have a follow up issue at https://github.com/microsoft/vscode-cpptools/issues/5604 for when the cwd does actually need to be the compiler's directory.
