### ISSUE TITLE
Can't disable intellisense

### ISSUE THREAD

**Issue by nickolai-voyage** [microsoft/vscode-cpptools#4763]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

https://imgur.com/a/KoRbS0C

For one thing, intellisense doesn't work, it can't even find a variable defined on the previous line in a 5 line file. Unfortunately, going into the settings and disabling it doesn't fall back to "simple" autocomplete.  This is really frustrating, as it should be really simple to find a word defined in the same file.

**To Reproduce**
See the imgur link above

**Expected behavior**
Either intellisense should display some level of competence, or it should fall back to something that can.

**Screenshots**
See imgur link above

**Additional comments**
I like the C++ extension for the "Goto definition feature", but it really sucks to have to trade working autocomplete in exchange for that feature. There must be a way to actually disable this extension's autocomplete "feature"?

**Comment by sean-mcmanus** [comment]
Does setting "C_Cpp.autocomplete" to "Disabled" work for you?

**Comment by nickolai-voyage** [comment]
No, none of the settings bring up MY_DEFINED_VALUE in the autocomplete.

I ultimately found a workaround by disabling the autocomplete, keeping intellisense enabled (since apparently goto definition doesn't work without it) and using the All Autocomplete extension to provide autocomplete results.

**Comment by sean-mcmanus** [comment]
Our extension overwrites the default "editor.wordBasedSuggestions" to "false", so that's probably what is preventing the default VS Code completion. We have an issue tracking this at https://github.com/microsoft/vscode-cpptools/issues/3920 .

**Comment by nickolai-voyage** [comment]
Is there a workaround? My settings page is showing that value to be true, but I still can't get autocomplete working (without All Autocomplete) in the example shown.

**Comment by sean-mcmanus** [comment]
Try using
"[cpp]": {
"editor.wordBasedSuggestions": true
},
"[c]": {
"editor.wordBasedSuggestions": true
}

**Comment by nickolai-voyage** [comment]
That appears to work, thanks. Any idea as to why intellisense can't figure out what to suggest? Seems like a pretty straightforward test case.

**Comment by sean-mcmanus** [comment]
Oh, yeah, I just viewed your screenshot -- that should work. It looks like you don't have intelliSenseEngine set to "Default"? Is it set to "Tag Parser" or "Disabled"? Or if it fell back to the "tag parser" if `#include` were not found and the intelliSenseEngineFallback was enabled.

It would also repro if an IntelliSense crash occurred. 0.26.3-insiders had a major IntelliSense crash if you happened to have had that (we're about to release 0.26.3-insiders2 with a fix).

**Comment by sean-mcmanus** [comment]
Actually, your screenshot shows a squiggle so it looks like the intelliSenseEngine is "Default"...it could be crashing during/before completion.
