### ISSUE TITLE
[Help] How to change "Peek" submenu to main menu

### ISSUE THREAD

**Issue by vscpp** [microsoft/vscode-cpptools#4769]
- OS and Version: Win10 1909
- VS Code Version: 1.41.0
- C/C++ Extension Version: 0.26.2

Current "Peek" moved to a submenu, I am wonder if there is method change it back to main menu? Because it's very not convenience for coding.
I searched by google but I didn't find a solution. Please help.

![image](https://user-images.githubusercontent.com/26138585/71143301-059d9780-2255-11ea-9f5f-920051de9720.png)

**Comment by sean-mcmanus** [comment]
I also do not see a way to configure the UI (our extension doesn't control this UI). Can you file a feature request at https://github.com/microsoft/vscode/issues ?

**Comment by vscpp** [comment]
Thank @sean-mcmanus , I filed a feature request at vscode issue.
https://github.com/microsoft/vscode/issues/87628
