### ISSUE TITLE
Code formating will break the text content if there is any multibyte character in it

### ISSUE THREAD

**Issue by owent** [microsoft/vscode-cpptools#477]
This problem has been solved in [Clang-Format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) long time ago.
Related commit is https://github.com/xaverh/vscode-clang-format-provider/commit/86e773b4acce9e14b8610d2576c11fb56de43433

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. The bug has been fixed and will be in our next update (hopefully, out tomorrow, but it could be delayed if we find other issues).

**Comment by owent** [comment]
Fixed in 0.10.1
