### ISSUE TITLE
Digraphs are not properly formatted

### ISSUE THREAD

**Issue by mikaelmello** [microsoft/vscode-cpptools#4771]
**Type: LanguageService**

Digraphs such as `<%` and `%>` are not properly formatted.

**Describe the bug**
- OS and Version: Manjaro 18.1.4 Juhraya
- VS Code Version: 1.40.2
- C/C++ Extension Version: 0.26.3-insiders
- Other extensions you installed (and if the issue persists after disabling them): None applicable
- A clear and concise description of what the bug is.

Digraphs are not properly formatted.

**To Reproduce**

![image](https://user-images.githubusercontent.com/17488630/71147500-c39a3480-2207-11ea-8610-b0616ef47482.png)
![image](https://user-images.githubusercontent.com/17488630/71147509-cac14280-2207-11ea-9381-21236034921f.png)
![image](https://user-images.githubusercontent.com/17488630/71147517-ce54c980-2207-11ea-8cc0-ffd6a1284660.png)
![image](https://user-images.githubusercontent.com/17488630/71147525-d4e34100-2207-11ea-8615-2cbc8338685c.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/17488630/71147542-dca2e580-2207-11ea-970c-1e6b642560aa.png)

**Additional context**

https://en.wikipedia.org/wiki/Digraphs_and_trigraphs#C

**Comment by sean-mcmanus** [comment]
Our extension relies on clang-format for formatting -- I don't see an option for enabling trigraph support. I believe you would need to file a bug or feature request at https://bugs.llvm.org/ .

**Comment by mikaelmello** [comment]
Thanks, I'll check there!
