### ISSUE TITLE
"Find All References" get results repeated twice.

### ISSUE THREAD

**Issue by duanyongli** [microsoft/vscode-cpptools#4774]
**Type: LanguageService**

**Describe the bug**
- OS and Version:ubuntu 18.04
- VS Code Version:1.41.1
- C/C++ Extension Version:cpptools Version 0.26.3-insiders2, vscode-clangd
- when cpp-tools and vscode-clangd are enabled simultaneously, "Find All References" get results repeated twice.

**Expected behavior**

**Screenshots**

**Additional context**

I think my problem is the same as [pyright #201](https://github.com/microsoft/pyright/issues/201).

**Comment by sean-mcmanus** [comment]
You can set C_Cpp.intelliSenseEngine to "Disabled" to prevent our extension from registering as a references provider. Is that sufficient for you?

**Comment by duanyongli** [comment]
> You can set C_Cpp.intelliSenseEngine to "Disabled" to prevent our extension from registering as a references provider. Is that sufficient for you?

Thanks. My problem is solved.
