### ISSUE TITLE
IntelliSense, autocomplete not working for cpp17 on mac

### ISSUE THREAD

**Issue by vrbilgi** [microsoft/vscode-cpptools#4775]
Hello,
**Type: LanguageService**
**OS and Version: MAC 10.12.6**
**VS Code Version: 1.41**

I am using VS Code on MAC. I have noticed three issues.
**1:  vector<string> msg {"Hello", "C++", "World", "from", "VS Code!"}**
  Which is write code but, shown as error.

no instance of constructor "std::vector<_Tp, _Alloc>::vector [with _Tp=std::string, _Alloc=std::allocator<std::string>]" matches the argument list -- argument types are: (const char [6], const char [4], const char [6], const char [5], const char [9])
 
**2:   cout<<msg.capacity()<<endl;
         cout<<msg.capacity<<endl**
       in c++ capacity is a function under vector. So first line has no isssues.
       Whereas second line error. This is not highlighted in the editor. I get the error only at build time 

**3: vector<string> msg {"Hello", "C++", "World", "from", "VS Code!"}
 msg.shrink_to_fit()**
shrink_to_fit() is part of vector. But its not shown in autocomplete. When I write its highlighted as error. Build is working fine.

![VisualCodeInt](https://user-images.githubusercontent.com/11361828/71235709-f38a2a80-2322-11ea-9703-f25e4dcd130e.png)

**c_cpp_properites.json**
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include/c++/4.2.1",
                "/usr/local/include",
                "/usr/include",
                "${workspaceRoot}",
                "/usr/local/Cellar/gcc/8.2.0/include/c++/8.2.0/tr1"
            ],
            "defines": [],
            "_intelliSenseMode": "clang-x64",
            "intelliSenseMode": "${default}",
            "browse": {
                "path": [
                    "/usr/include/c++/4.2.1",
                    "/usr/local/include",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/local/bin/gcc-8",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
You need to remove the `/usr` paths from your includePath. Instead, you should set your compilerPath to the correct value (you have it set...is that not sufficient)? Does that fix your issue?

If not, can you run C/C++: Log Diagnostics with the source file active and check if the includePath it reports is correct?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
