### ISSUE TITLE
Formatting function didn't work improperly in multi-root workspace.

### ISSUE THREAD

**Issue by lclancey** [microsoft/vscode-cpptools#4777]
***\*Type: LanguageService\****

***\*Describe the bug\****

\- OS and Version: Win10 1903

\- VS Code Version: 1.41.1(user setup)

\- C/C++ Extension Version: 0.26.2 and 0.26.3-insiders2 

\- When trying to format c/cpp files in multi-root workspace, formatting function didn't work improperly, it provides more than one formatter with the same name "ms-vscode.cpptools".

***\*To Reproduce\****

\1.  Make sure "editor.defaultFormatter" is not set in global or file-associate setting.

\2. Create multi-root workspace, with more than one directories. Each directories have c and/or h files in it.

My test workspace is like this:

```
├── dirA
│   └── fileA.c
├── dirB
│   └── fileB.c
├── dirC
    └── fileC.c
```

\3. Try to format files in these directories.

​	\3.1 First open fileA.c, press shift+alt+F, the formatting function seems work fine, mostly,.

​	\3.2 Then again open and try to format fileB.c.

\4. Then VS Code shows an alarm note :*There are multiple formatters for 'C++' files. Select a default formatter to continue.*, if press **Configure** button, it shows two formatter which have the same name "ms-vscode.cpptools".

\5. If not selected one of those selections (means not set *editor.defaultFormatter*), and open and try to format fileC.c, the alarm shows again, this time three formatter are available (also have the same name) .

***\*Screenshots\****

**

***\*Additional context\****

My guess: when working in multi-root workspace, the extension register itself as c/cpp formatter provider too many times (one directory one time), while VS Code has no mechanism to prevent same-name-provider, caused this problem.

I tried to set  *C_Cpp.formatting* to *Disabled*,  and using Clang-format extension instead. Didn't work for me,  because it has different format result from c/cpp extension.

I am not good in English, so if anything above not clear, or this issue has been submit/discussed somewhere,  please let me know.

**Comment by sean-mcmanus** [comment]
This is a known issue: https://github.com/microsoft/vscode-cpptools/issues/3285 . 

We're in the middle of re-writing our multi-root implementation which should fix this issue.
