### ISSUE TITLE
Attempt to download OS binaries if they're missing

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4778]
@sean-mcmanus, @bobbrow 
The last insider build 0.26.3-insiders2 just "installed" was missing "Microsoft.VSCode.CPP.Extension.exe". And this was on my private computer without corporate firewall.

Switched from the insider channel to the default channel and back to insider. Now it installed everything (I forgot about the re-install command). Strange.

Unfortunately I cannot reproduce the missing file error.

Why don't you guys implement an integrity check in case of an error (not only during install)? E.g. you know which files to expect in the folders. If something is missing you can retry downloading it or at least print a message where to download the missing files manually?

Btw. the link https://download.visualstudio.microsoft.com/ shows internal server error at the moment, I do not know if this may be related.

_Originally posted by @crashdown0815 in https://github.com/microsoft/vscode-cpptools/issues/3610#issuecomment-567375899_

**Comment by sean-mcmanus** [comment]
@crashdown0815 The 0.26.3-insiders2 vsix has the binaries inside of it, see the "offline vsix's" posted at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3-insiders2 . We just call the VS Code's installExtension method. I do not know what could cause the file to be missing.

Currently we just check the install.lock file for determining if dependencies need to be downloaded, but we have talked about potentially adding more integrity checks.

**Comment by bobbrow** [comment]
We're working on this feature in 0.30.0
