### ISSUE TITLE
Typo in 0.10.0 Change History: 2016 instead of 2017

### ISSUE THREAD

**Issue by rfjakob** [microsoft/vscode-cpptools#478]
Should read January 24, **2017**

Screenshot from https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools :

![2016](https://cloud.githubusercontent.com/assets/286847/22641646/e12fdd30-ec57-11e6-99a4-c8d0471d7c5f.png)

**Comment by sean-mcmanus** [comment]
Thanks for noticing :)

**Comment by pieandcakes** [comment]
This is resolved. Closing
