### ISSUE TITLE
IntelliSense does not parse project completely

### ISSUE THREAD

**Issue by ltWolfik** [microsoft/vscode-cpptools#4784]
I have `C` project about 600K lines of code. I've noticed that IntelliSense learned the project only partially. For example,  I do "Go to definition" for some function - and IntelliSense can 't find a definition. But I know, that definition exists in `N.c`. So, I opened the file, and after "Go to definition" works correctly for that function. 

Right now C/C++ extension consumes about 500 MB RAM.

600K - does not seem too lot.
Is it possible some way for IntelliSense to work right for the whole project?

VSCode Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:32:17.711Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.12.14-lp151.28.36-default

C/C++ Extension Version: 0.26.2

**Comment by sean-mcmanus** [comment]
Can you set your C_Cpp.loggingLevel to "Debug" and check the C/C++ section for "tag parsing file: N.c"? Does that message only appear after the file is opened? Does Find All References give the same results (missing references)? Does the Outline view show the definition when you open the file?

Is this a multi-root workspace? Are the files with different folders external to the workspace?

Also, is the database icon appearing in the bottom right and does it show a parsing is in progress? If it's in progress still, you just need to wait till it finishes.

**Comment by ltWolfik** [comment]
Yes, section "tag parsing file: N.c" was appeared after the file had opened.
Yes, Find All References give the same results (references are missing before the file opening).
Yes, Outline shows the definition after the file opening.
No, it is not a multi-root workspace.
No, now I do not see the database icon.

**Comment by Lennon925** [comment]
@sean-mcmanus，I have similar issue with @ltWolfik. Today I found that “Find Refs” gave partial results and other results was given until file was opened. Cpptools Version: 0.26.3-insiders2. And I used CMakeTools to provide configure for cpptools. But today I use this function again, it's right.

**Comment by Lennon925** [comment]
> Can you set your C_Cpp.loggingLevel to "Debug" and check the C/C++ section for "tag parsing file: N.c"? Does that message only appear after the file is opened? Does Find All References give the same results (missing references)? Does the Outline view show the definition when you open the file?
> 
> Is this a multi-root workspace? Are the files with different folders external to the workspace?
> 
> Also, is the database icon appearing in the bottom right and does it show a parsing is in progress? If it's in progress still, you just need to wait till it finishes.

And I used CMakeTools to provide configure for cpptools.

**Comment by sean-mcmanus** [comment]
Okay, it looks an issue with our workspace file search/parsing -- this code isn't expected to have changed recently. Are you using compileCommands or configurationProvider?

The logging message "Processing folder (recursive)" shows what folders we search for parsing -- is the skipped file a child of one of those folders? Could a files.exclude setting be excluding the folder from parsing? When you do a Reset IntelliSense database, can you tell how many or whar "kind" of files are missing after it logs "Parsing: # files(s) processed"?

Do you know of a repro project? I haven't been able to observe this issue yet.

**Comment by ltWolfik** [comment]
No, I don't have compileCommands or configurationProvider.
I checked `files.exclude` - It's ok.
Problem with [FRRouting](https://github.com/FRRouting/frr) project.
I just have done "Reset IntelliSense Database", and noticed from debug output:
"Discovering files: 5391 file(s) processed", but "Parsing: 1420 files(s) processed".
It has parsed fully only ./lib subdir, from another subdirs only several _opened_ files.

**Comment by sean-mcmanus** [comment]
Setting compilerPath to "" to disable system header parsing, I get "Parsing: 1519 files(s) processed", and 1499 files on Linux (not sure why there's a difference). Is the 1420 number with a compilerPath set? What is that number when compilerPath is "" so I can get an estimate of the number of skipped files? Even with 1420 it does seem like it's not parsing some files. The only settings that I know that can affect this are files.exclude (parses less) and files.associations (parses more), and limitSymbolsToIncludedFiles (but that setting appears to have no effect on that project because all the headers are included, exlcuding system headers). Can you provide a specific file folder that is missing so I could double check if that is getting parsed for me? I'm seeing around 977 .c files and 476 .h files.

Does your local copy have any additions/changes, like symlinks or build output?

**Comment by ltWolfik** [comment]
Seems, I've found the problem reason. In `c_cpp_properties.json` I did change the following (seems, because of some file names overlapping):
```json
"includePath": [
    "${workspaceFolder}/**"
],
```
to
```json
"includePath": [
    "${workspaceFolder}/*",
    "${workspaceFolder}/lib/*"
],
```
I thought this only specifies where to search for `*.h` files when processing `*.c` files (like `gcc -I`). But actually it stopped parsing all `*.c` files except lib subdir.

I changed `includePath` back, and now it parses the project completely.

**Comment by sean-mcmanus** [comment]
Yeah, using the `"*"` syntax would cause the .c files to not be parsed when it's copied over to the browse.path setting (using "*" essentially mean "non-recursive browse.path"). An alternative change would be to set your browse.path explicitly (bypassing the copy from includePath behavior). If your goal is to resolve name overlapping with `"${workspaceFolder}/**"`, putting `"${workspaceFolder}/lib"` first would give that high precedence (although from what I remember all non-recursive includes are given precedence over recursive ones).
