### ISSUE TITLE
C/C++ IntelliSense "expression must have a pointer type" is incorrectly shown on a pointer type (wrong location)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4785]
Use
```
class c2
{
public:
	int i;
};

class c1
{
public:
	c2 func() { return c2(); }
};

void main(void)
{
	std::shared_ptr<c1> ptr = std::make_shared<c1>();
	ptr->func()->i;
}
```

Bug: "expression must have a pointer type" is shown on the "ptr", which is the wrong location and confusing. It should be shown after the func() call, which is the expression that doesn't have the pointer type, which is where the cl.exe compiler errors at.

Reported at https://developercommunity.visualstudio.com/content/problem/866095/cc-intellisense-expression-must-have-a-pointer-typ.html .

**Comment by bobbrow** [comment]
The issue still repros, but the Developer Community issue is no longer there and would have been closed as "lower priority" by now anyway. Unfortunately, that means that this will not likely be fixed in VS Code either.
