### ISSUE TITLE
Signature Help: cannot correctly underline template argument

### ISSUE THREAD

**Issue by saoaix** [microsoft/vscode-cpptools#4786]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 2004
- VS Code Version: 1.41.0
- C/C++ Extension Version: 0.26.3-insiders2
- Other extensions you installed (and if the issue persists after disabling them): python 
- A clear and concise description of what the bug is.
If the first template argument is a pair, intellisense seems to skip the next argument.

**To Reproduce**

1. open a new file
2. populate with
```cpp
#include <queue>
#include <utility>

using namespace std;

int main()
{
    return 0;
}
```
3. before line "return 0", start a new line with "priority_queue<pair<int, int>"
4. IntelliSense says I'm going to input _Sequence
5. append ", "
6. IntelliSense says I'm going to input _compare, however I'm going to input _Sequence.

**Expected behavior**

IntelliSense should probably underline _Sequence for me.
**Screenshots**

![image](https://user-images.githubusercontent.com/58806594/71399407-7f22f480-265e-11ea-930d-6a6d646b3981.png)

**Additional context**

I tried:
testing in windows with Mingw gcc 8.2.0
testing in WSL with gcc 9.2.1
both observes the issue.

**Comment by sean-mcmanus** [comment]
Yeah, the comma in `pair<>` is getting parsed as belonging to the `priority_queue<>`.

**Comment by sean-mcmanus** [comment]
The fix is available in https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders3
