### ISSUE TITLE
Linting has problem with struct __attribute__

### ISSUE THREAD

**Issue by 45gfg9** [microsoft/vscode-cpptools#4787]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7
- VS Code Version: 1.14.1
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them): C++ Intellisense
- A clear and concise description of what the bug is.

I found an issue #3700 which is also on linting about typedefs and structs.

**To Reproduce**

```cpp
typedef struct a {
    // ...
} b;

typedef struct __attribute__ ((packed)) x {
    // ...
} y;

int main() {}
```

**Expected behavior**

Code above is able to compile but error message `expected a ';'` appears

Update: This does not happen on macOS 10.14.6

**Screenshots**

![image](https://user-images.githubusercontent.com/37043529/71405350-265c5780-2670-11ea-889e-2884a16a9e6f.png)

**Comment by sean-mcmanus** [comment]
The code doesn't compile under msvc-x64 mode. If you do "C/C++: Log Diagnostics" it shows the IntelliSense Mode as "msvc-x64", right? Can you change your compilerPath to use a gcc or non-Windows-based clang compiler, such as mingw or a WSL compiler?

The user at https://github.com/microsoft/vscode-cpptools/issues/3387 hit the same issue with a clang/gcc compiler, but we weren't able to repro the issue.

**Comment by 45gfg9** [comment]
Long wait, sorry.

![image](https://user-images.githubusercontent.com/37043529/71615119-93309e00-2bea-11ea-8d41-16a6fb3829ed.png)

Yeah, IntelliSense Mode is at `msvc-x64`
After changing `compilerPath` to `MinGW\bin`, problem is gone

though IntelliSense Mode is still `msvc-x64`

![image](https://user-images.githubusercontent.com/37043529/71615265-6335ca80-2beb-11ea-9808-6bb6e8286296.png)

**Comment by sean-mcmanus** [comment]
`compilerPath` actually should be the full path with the filename, such as `C:\\MinGW\\bin\\gcc.exe`.

The problem is gone because of "No active translation units", i.e. IntelliSense isn't being used (or you did C/C++: Log Diagnostics without a C++ file active).

**Comment by 45gfg9** [comment]
oh sorry
![image](https://user-images.githubusercontent.com/37043529/71657210-dff6af00-2d79-11ea-8697-f967042795a8.png)

So i guess this is it, right?

**Comment by sean-mcmanus** [comment]
Yeah, that looks right.
