### ISSUE TITLE
Show variable type and size of stl container when debugging

### ISSUE THREAD

**Issue by duanyongli** [microsoft/vscode-cpptools#4788]
Type: Debugger

**Describe the bug**
- OS and Version:Ubuntu 18.04
- VS Code Version: 1.41
- C/C++ Extension Version:0.26.3
- **Show variable type and size of stl container when debugging.**

**Additional context**
I hope to add support for this feature.

**Comment by pieandcakes** [comment]
This should be enabled via `gdb`'s `pretty-printing`. Are you planning on adding support in another way?
