### ISSUE TITLE
in the single step mode,gdb always crash at the "}" of the main funtion

### ISSUE THREAD

**Issue by sunqi1993** [microsoft/vscode-cpptools#479]
In the MinGW(version 4.8.1), i use gdb.exe(version7.6) to debug at the breakpoint:
When the single step cursor goes to the right bracket of the main function and  i press F11 ，it always cause a problem like that:
![image](https://cloud.githubusercontent.com/assets/12682690/22693515/95d9503c-ed7e-11e6-8539-ff1c7a31f11e.png)
It's a small bug,thing goes well except this situation.

otherwise gdb(version 7.9) in the TMD-GCC don't get well support in the ext,when i press F5 to debug ,
it just crash down, i can't debug the  program.
![image](https://cloud.githubusercontent.com/assets/12682690/22693833/e00c96e0-ed7f-11e6-9d8e-3fc8ce66add1.png)

**Comment by pieandcakes** [comment]
@sunqi1993 Can you enable logging in your launch.json by adding 
```
"logging:" { "trace": true, "traceResponse": true, "engineLogging": true } 
```
and repro and send me the contents of the logging? I suspect for the first option that we are passing a path to VSCode that it isn't able to find the code file for. 

The second issue, is that gdb 7.9 on MinGW? Can you provide more information for that one so I can investigate? 
Thanks

**Comment by sunqi1993** [comment]
@pieandcakes 
Thanks for your reply, actually i want to upload a log-file.but sadlly the log infoformation has hunders of lines and i can't use "ctrl+a ctrl+c"  to select and copy the debug console window, so i copy the key information in the debug console
```
C stepIn: {"threadId":1}
E output: {"category":"stdout","output":"Single stepping until exit from function __do_global_ctors,\nwhich has no line number information.\n","data":null,"type":"output"}
Single stepping until exit from function __do_global_ctors,
which has no line number information.
 R: {"success":true,"message":null,"request_seq":35,"command":"stepIn","body":null,"running":false,"refs":null,"seq":0,"type":"response"}
E output: {"category":"stdout","output":"[New Thread 8804.0x438]\n","data":null,"type":"output"}
[New Thread 8804.0x438]
E thread: {"reason":"started","threadId":5,"type":"thread"}
E stopped: {"threadId":1,"reason":"step","source":null,"line":0,"column":0,"text":null,"allThreadsStopped":true,"type":"stopped"}
C threads: null
 R: {"success":true,"message":null,"request_seq":36,"command":"threads","body":{"threads":[{"id":4,"name":"Thread #4"},{"id":3,"name":"Thread #3"},{"id":2,"name":"Thread #2"},{"id":1,"name":"Thread #1"},{"id":5,"name":"Thread #5"}]},"running":false,"refs":null,"seq":0,"type":"response"}
C threads: null
 R: {"success":true,"message":null,"request_seq":37,"command":"threads","body":{"threads":[{"id":4,"name":"Thread #4"},{"id":3,"name":"Thread #3"},{"id":2,"name":"Thread #2"},{"id":1,"name":"Thread #1"},{"id":5,"name":"Thread #5"}]},"running":false,"refs":null,"seq":0,"type":"response"}
C stackTrace: {"threadId":1,"startFrame":0,"levels":20}
 R: {"success":true,"message":null,"request_seq":38,"command":"stackTrace","body":{"stackFrames":[{"id":1000,"source":null,"line":0,"column":0,"name":"_fu0___set_invalid_parameter_handler"},{"id":1001,"source":null,"line":0,"column":0,"name":"[Unknown/Just-In-Time compiled code]"},{"id":1002,"source":null,"line":0,"column":0,"name":"kernel32.dll!KERNEL32!BaseThreadInitThunk"},{"id":1003,"source":null,"line":0,"column":0,"name":"[Unknown/Just-In-Time compiled code]"}],"totalFrames":4},"running":false,"refs":null,"seq":0,"type":"response"}
C scopes: {"frameId":1000}
 R: {"success":true,"message":null,"request_seq":39,"command":"scopes","body":{"scopes":[]},"running":false,"refs":null,"seq":0,"type":"response"}

```
For the second issue, MinGW doesn't have a new release and contain a unfixed bug for a long time,so  i use TMD-GCC as an alternative to see wether  i can use it to debug in vscode(its gdb version is 7.9)

**Comment by pieandcakes** [comment]
@sunqi1993 I think I need more of the log as I need the information returned about the stopping event from gdb. Can you enable `"logging": { "engineLogging": true }` and look for something that starts with `stopped` ?

We require `MI` command mode from gdb and for the second one, if you do the same logging as above and send it in I can see what we send and what your version of gdb is sending back.

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
