### ISSUE TITLE
If it is possible to add FreeBSD support for the debugger?

### ISSUE THREAD

**Issue by everything411** [microsoft/vscode-cpptools#4790]
VS Code has been ported to FreeBSD now, and can be installed from the offcial freebsd ports collections. 

So, if it is possible to add freebsd support?

thanks a lot

**Comment by sean-mcmanus** [comment]
Where are you seeing VS Code ported to FreeBSD? Is it some old version of VS Code?

**Comment by everything411** [comment]
> 
> 
> Where are you seeing VS Code ported to FreeBSD? Is it some old version of VS Code?

It's an up to date version of vscode

vscode in the ports tree https://www.freshports.org/editors/vscode/

the github repo https://github.com/tagattie/FreeBSD-VSCode

**Comment by sean-mcmanus** [comment]
It looks like we don't get any telemetry from that vscode port so our the FreeBSD usage appears to be 0. Releasing for ARM platforms is higher priority for us.

**Comment by netbsduser** [comment]
I presume the telemetry doesn't apply because the FreeBSD port is built from the OSS codebase. 

@everything411 The cpptools run on FreeBSD with minimal adjustment; just ensure you have the 64-bit Linux binary compatibility module loaded. There are a very few places in the codebase which explicitly check for Linux, and adding support for FreeBSD is as simple as adding the appropriate checks for FreeBSD in those places. Just setting it to use the same stuff as Linux seems to work fine. I will try to make a pull request for this at some point, or in the meantime let me know if you would like a writeup on how I did it.

**Comment by sean-mcmanus** [comment]
@JX7P You got FreeBSD to work via just changing our open source TypeScript? We haven't tested our closed source language server binary on FreeBSD and our IntelliSense parser appears to have some BSD-specific tweaks to deal with things like system header differences, so you might experience some IntelliSense bugs related to that unless we build a specific BSD binary. Also, the debugger components might not work on the OSS-built VS Code version and/or BSD.

**Comment by netbsduser** [comment]
@sean-mcmanus That's right, FreeBSD has a fairly good Linux binary compatibility layer and it seems to run the closed binaries for Linux fine. I haven't tested it exhaustively but with the IntelliSense I haven't observed any issues yet. The debugger doesn't appear to work at all - I will look into that and see if I missed something.

**Comment by sean-mcmanus** [comment]
The debugger issue could be https://github.com/microsoft/vscode-cpptools/issues/4713 .

**Comment by woodsb02** [comment]
This line in the code appears outdated :)

https://github.com/microsoft/vscode-cpptools/blob/v0.18.1/Extension/src/common.ts#L524
```
    if (platformInfo.platform !== 'win32' && platformInfo.platform !== 'linux' && platformInfo.platform !== 'darwin') {
        // this should never happen because VSCode doesn't run on FreeBSD
        // or SunOS (the other platforms supported by node)
```

**Comment by sean-mcmanus** [comment]
@woodsb02 I don't think the official release of VS Code supports FreeBSD and the debugger only runs on the official release of VS Code. See https://github.com/microsoft/vscode-cpptools/issues/4713 .

**Comment by Mohsents** [comment]
> I presume the telemetry doesn't apply because the FreeBSD port is built from the OSS codebase.
> 
> @everything411 The cpptools run on FreeBSD with minimal adjustment; just ensure you have the 64-bit Linux binary compatibility module loaded. There are a very few places in the codebase which explicitly check for Linux, and adding support for FreeBSD is as simple as adding the appropriate checks for FreeBSD in those places. Just setting it to use the same stuff as Linux seems to work fine. I will try to make a pull request for this at some point, or in the meantime let me know if you would like a writeup on how I did it.

It's doesn't seem that by enabling linux on FreeBSD all things works correctly. In my case although it is enabled but it doesn't work.
