### ISSUE TITLE
failed brackets matching

### ISSUE THREAD

**Issue by uccmorph** [microsoft/vscode-cpptools#4795]
Issue Type: <b>Bug</b>

The following code has incorrect brackets matching
void test_func()
{
#ifdef NN
	while (1) 
	{ //<-
#else
	while (0)
	{
#endif
	}
} //<-

Extension version: 0.26.2
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by sean-mcmanus** [comment]
This is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/3681 .

Our extension doesn't currently implement brace matching. The behavior is coming from VS Code's handling, which doesn't understand that one of the `{` is in an inactive region and should be skipped.
