### ISSUE TITLE
Why my VS code could not better support C ++ 11 and above standards?

### ISSUE THREAD

**Issue by nolongerwait** [microsoft/vscode-cpptools#4796]
This is the first time that I use VS code to code C++, and I have finished  the configuration of C++.
But when I am coding, I still received the errors and warnings that could not use C++11 or list initialization like following image:
![image](https://user-images.githubusercontent.com/22978131/71562965-11bcfc80-2a80-11ea-823a-b72e48106e69.png)

And thess are my configuration files of C++:

<details>
<summary>c_cpp_properties.json</summary>

```
{
    "configurations": [
        {
            "name": "macOS",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
</details>

<details>
<summary>launch.json</summary>

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch(LLDB)",
            "type": "lldb",
            "request": "launch",
            "program": "${workspaceFolder}/source.out",
            "args": [],
            "stopOnEntry": true,
            "cwd": "${workspaceFolder}"
        }
    ]
}
```
</details>

<details>
<summary>tasks.json</summary>

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build with Clang",
            "type": "shell",
            "command": "clang++",
            "args": [
                "-std=c++17",
                "-stdlib=libc++",
                "source.cpp",
                "-o",
                "source.out",
                "--debug"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
</details>

And I also have configured C/C++ Extension:
![image](https://user-images.githubusercontent.com/22978131/71563040-4f6e5500-2a81-11ea-8ae5-cb646b509440.png)

**Comment by nolongerwait** [comment]
I am sorry that the markdown could  not support code label well.

**Comment by sean-mcmanus** [comment]
Those errors are not from our extension. They're either from another extension you have installed (you could disable them) or your compiler (you could verify the correct compiler is being used...your tasks.json just calls clang++ without a full path, so it could be an older clang++ that doesn't support C++17).

**Comment by nolongerwait** [comment]
> Those errors are not from our extension. They're either from another extension you have installed (you could disable them) or your compiler (you could verify the correct compiler is being used...your tasks.json just calls clang++ without a full path, so it could be an older clang++ that doesn't support C++17).

Thanks for your reply, I would like to know how to determine which extension provides these errors. Because my VS Code just install Java extension, and the C ++ extension with CodeLLDB.

What's more,  I could provide you new information: I could successfully compile and run, but when I am coding, it always gives me these errors and warnings.

**Comment by nolongerwait** [comment]
> Those errors are not from our extension. They're either from another extension you have installed (you could disable them) or your compiler (you could verify the correct compiler is being used...your tasks.json just calls clang++ without a full path, so it could be an older clang++ that doesn't support C++17).

With your suggestion, I found the reason of this problem, an extension called "C / C ++ Clang Command Adapter".

Now I could close this issue. Thanks very much again.
