### ISSUE TITLE
Sluggish when editing a very large C file after some time

### ISSUE THREAD

**Issue by sveinse** [microsoft/vscode-cpptools#4799]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version:  Code 1.41.1
- C/C++ Extension Version: ms-vscode.cpptools-0.26.3-insiders2
- All other extensions except One Dark Pro is disabled. One Dark Pro does not affect the issue.

I have problems with occasional lockup when using the C/C++ extension on a large c file with local edits in a git repo (this file https://github.com/sveinse/portaudio/blob/master/src/hostapi/wasapi/pa_win_wasapi.c). This file is large, so I sit with the same file in three parallel windows simultaneously. After some time working on the file vscode suddenly becomes extremely sluggish (but not completely dead). When sluggish, running `code --status` shows that the "window" process is consuming 13-14% CPU. A restart of vscode is required to remedy the issue. The occurrence for this is about once every 30 mins-1hrs, not too often but often enough to be a major annoyance when working.

I'm not even sure if the issue is indeed caused by the C/C++ extension to begin with, so pardon me if this is due to the main VS Code rendering engine. However, If I don't enable the C/C++ extension the issue does not occur. But then again the highlighting/styling is much simpler. I do notice that scrolling the file is a lot faster. For this large file, I cannot work without the IntelliSense, so I have to have it enabled.

I tried setting `"C_Cpp.loggingLevel": "Debug"` to see if the logs would give any clues, but no useful output was given before or after the lockup.

I understand this is too little information for others to work on, yet this is very annoying that it cannot be left unchecked. What can I do to provide debug and logs that will provide the additional information that can be used to shed some light to the issue, please?

[c_cpp_properties.json.txt](https://github.com/microsoft/vscode-cpptools/files/4011629/c_cpp_properties.json.txt)

**Comment by sean-mcmanus** [comment]
Our extension doesn't consider 6k lines to be "large" in terms of what it is able to handle (and we routinely work with files that size and haven't noticed this yet). I'm also seeing our IntelliSense process only using 133 MB (small). By "parallel" windows, do you mean split panes or 3 VS Code instances?

This seems like more likely to be a VS Code issue. You don't see our Microsoft.VSCode.Cpp. processes using lots of CPU when the sluggishness occurs, right? Our TypeScript that runs in the code extension host process might be causing this though -- is the "extensionHost" process the one using CPU? I'm not aware of any feature in our extension's TypeScript that could cause sluggishness after 30 minutes of usage though. Are you able to determine what sort of actions cause the sluggishness, such as edits or scrolling or if changing certain settings cause it to no repro, such as the intelliSenseEngine "Disabled" setting?

Your includePath is unusual. You're using recursive includes "**" on folders that don't have any child folders. You might want to consider using the CMake Tools extension for configuring IntelliSense, although the project seems simple enough to configure without it.

**Comment by sean-mcmanus** [comment]
You might want to try setting C_Cpp.enhancedColorization to "Disabled" -- I don't know why that would cause it, but it could be exposing some bug with VS Code itself, because we send them more decorators, which VS Code is known to not render scalably (we had to remove lexical decorators because of this, but our existing semantic decorators shouldn't be "too large" for your repro file...unless after 30 minutes of usage it accumulates "garbage" some how).

**Comment by sean-mcmanus** [comment]
Also, does the 13-14% CPU usage ever end, even when there is no UI interaction? If it ends, what UI interaction causes it to re-appear?

**Comment by sean-mcmanus** [comment]
If you can do Help->Toggle Developer Tools->Performance to record a log during this sluggish repro, it could help pinpoint the cause (the VS Code team would probably ask for that log as well).

**Comment by sean-mcmanus** [comment]
Does this repro with non-Insiders VS Code as well?

EDIT: Oops, you're using non-Insiders VS Code (just Insiders of our extension). I assume our non-Insiders would also repro the issue.

**Comment by sean-mcmanus** [comment]
Also, do you see any processes with unusually high memory usage?

**Comment by sean-mcmanus** [comment]
You might try using the Better C++ Syntax extension -- it has the most update-to-date version of the lexical colorizer -- the one that ships with VS Code is an older version of that extension which may have a bug that causes the lexical colorizer to enter an infinite loop (there have been multiple such instances of that in the past)...although this seems unlikely, since our C/C++ extension shouldn't trigger different behavior with lexical processing.

**Comment by sveinse** [comment]
Thanks @sean-mcmanus 

- I use multiple split panes of the same file in one VS Code instance
- It usually hangs after scrolling or intellisense navigation (F12)
- When it happens it is the "window" process which consumes CPU, not the extension host or its children
- The strange include path is fixed, but it does not change the overall behavior. Thus I believe it is unrelated
- I was able to profile the sluggishness. [Profile-20200111T151909.zip](https://github.com/microsoft/vscode-cpptools/files/4049407/Profile-20200111T151909.zip) - it is related to scrolling, and it shows that it spends 98% cpu-time in `_deltaDecorationsImpl`. I have no knowlegde of this, but it could seem like this is indeed a render issue.

```
cpptools: 0.26.3-insiders3
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by sean-mcmanus** [comment]
I think VS Code is tracking improving this at https://github.com/microsoft/vscode/issues/77140 . Until then, you could try changing C_Cpp.enhancedColorization to "Disabled" -- does that fix it?

**Comment by bobbrow** [comment]
Our latest insiders build changes the way we do the semantic tokens.  I suspect if you are still having this issue with 0.28.3, then 0.29.0 will address it.
