### ISSUE TITLE
Whitesmith Formatting not Supported

### ISSUE THREAD

**Issue by LostLaplace** [microsoft/vscode-cpptools#4801]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10, version 1709
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them): Vim (persists)
- A clear and concise description of what the bug is.

Whitesmith formatting is not supported by the language server. 

**To Reproduce**
1. Start new code block, for example an if block
2. Hit enter, VS Code doesn't indent
3. Open new brackets
4. VS Code indents cursor instead of lining it up with brackets

![screen_capture](https://user-images.githubusercontent.com/4967659/71627098-429f4d80-2bb6-11ea-817b-bc4c5dc68ef5.gif)

**Expected behavior**
Cursor should indent prior to placing brackets and should not indent within the brackets.

**Comment by sean-mcmanus** [comment]
This is a known issue we are tracking with https://github.com/microsoft/vscode-cpptools/issues/883 .
