### ISSUE TITLE
Intelisense without  existed header file (arpa/inet.h)

### ISSUE THREAD

**Issue by Phelexand** [microsoft/vscode-cpptools#4804]
When  I write unix-socket  using a windows computer, an error occurs that "cannot open source file "arpa/inet.h" "。There are two ideas. 
A new menu "ignore this header file" is needed for this workspace or global。
A new extensions that support offline headers's tags for unix-headers, windows sdk's, or other third part library.
The first one is a feature for your team, and the next is an other extension, what I want to make. Otherwise, your help is necessary.
Thank you very much.

**Comment by Phelexand** [comment]
I don't  like to install Windows SDK or lots of third part library when writing. Try one...Try another....and finnally I got the library what I want really. 
After coded, I move to a independent host to compiler and link.

**Comment by sean-mcmanus** [comment]
Without the header, IntelliSense isn't able to properly the compile the code in that header file.

"arpa/inet.h" is available on Windows 10 via using WSL (Ubuntu app) and the Remote-WSL extension.

**Comment by Phelexand** [comment]
> Without the header, IntelliSense isn't able to properly the compile the code in that header file.
> 
> "arpa/inet.h" is available on Windows 10 via using WSL (Ubuntu app) and the Remote-WSL extension.
 
I don't need to compile in all my machines. I just want use the feature which jumps into define or refrence when coding, otherwise, I'll compile at the compiler machine.
