### ISSUE TITLE
fatal error C1083: Cannot open include file: 'iostream': No such file or directory

### ISSUE THREAD

**Issue by birken25** [microsoft/vscode-cpptools#4805]
Type: General
Hello, I downloaded and installed VS Code fresh. Then followed the tutorial at https://code.visualstudio.com/docs/cpp/config-msvc. 

Issue: I cannot build the out-of-the-box hello world application. I am getting this error: "helloworld.cpp(1): fatal error C1083: Cannot open include file: 'iostream': No such file or directory"

Additional: IntelliSense does find the file. I get an error only when I try to build. I have not yet built anything with VS Code. I do have VS 2019 installed on my C drive. I have VS Code installed on my D drive. The VS C++ Build Tools have been installed on the C drive. I have copied over the MSVC folder to the D drive. I have tried including both the C and D drive folders in every property I can think to do it (plus the System Path variable), but still it will not build. If I change "#include \<iostream\>" to "#include <D:\code\MSVC\14.24.28314\include\iostream>" then the build does indeed get past the error, but it has issues with cascading includes.

I really have no idea if this is an issue with VS Code, my environment, or my brain. Could be all of the above. If anyone has thoughts I'd love to hear them. 

![image](https://user-images.githubusercontent.com/8355634/71683483-e4a66d80-2d4f-11ea-8c1c-693e641faa14.png)

![image](https://user-images.githubusercontent.com/8355634/71684078-a3af5880-2d51-11ea-9124-914da18cd1dc.png)

![image](https://user-images.githubusercontent.com/8355634/71684803-b7f45500-2d53-11ea-8d56-ec26403c9fbe.png)

**Comment by sean-mcmanus** [comment]
VS Code needs to be launched from the Visual Studio developer command prompt in order to get the environment variables setup (https://code.visualstudio.com/docs/cpp/config-msvc#_start-vs-code-from-the-developer-command-prompt ). Does doing that fix it?

**Comment by birken25** [comment]
This does not fix it unfortunately. This is how I have been starting VS Code.

Another item to note is that prior to getting this error, VS Code gave me an error that it couldn't find the compiler cl.exe, even though I had the full path in my settings files in VS Code. I fixed this by adding another Path environment variable for the MSVC path containing the cl.exe file (the same C:/Program Files/... path that I have above in my settings).

**Comment by sean-mcmanus** [comment]
The issue has to do with your tasks.json and the environment VS Code is running in, i.e. changing c_cpp_properties.json, settings.json, or launch.json shouldn't affect the compiler result.

When you do Help->Toggle Developer Tools->Console and enter "process.env" do you see the INCLUDE path with the "correct" data? My guess is that your process.env is incorrect. Ideally, you could fix your environment somehow...otherwise, you might try manually adding all the /I "args" or maybe manually setting the environment (not sure exactly what changes would need to be done though).

**Comment by birken25** [comment]
You are correct I think. I'm not sure what the "correct" data is supposed to be, but it's just a bunch of "Windows Kits" paths. When I added the INCLUDE env variable with the path containing the standard library the build was able to get past this issue (https://docs.microsoft.com/en-us/cpp/build/reference/cl-environment-variables?view=vs-2019). There is another issue with the build, but apparently my environment is just messed up, so I suppose this is not a direct issue with VS Code. Having some way of understanding this via the interface might be a good idea. It could be that having other versions of VS installed have disrupted this in some way. Thanks for helping here
