### ISSUE TITLE
No C/C++ IntelliSense squiggle (or hover info) for object.memberFunc = 0

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4806]
Use C/C++ code

```
struct foo
{
	int func(){}
};

int main()
{
	foo f;
	f.func = 0;
}
```

It doesn't show an error on "f.func = 0" when it should.

Bug #2: Hover over "func" also show no info.

https://developercommunity.visualstudio.com/content/problem/872469/no-cc-intellisense-squiggle-for-objectmemberfunc-0.html

**Comment by Colengms** [comment]
This looks to be fixed, since 0.28.0.  Closing as fixed.
