### ISSUE TITLE
No C/C++ IntelliSense error squiggle for "must return a value", e.g. "int * func() {}"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4807]
Use C/C++ code:

```
int * func(){}

int main()
{
	int i = *func();
}
```

There's no squiggle on the func definition about the lack of a return. Ideally there would be.

https://developercommunity.visualstudio.com/content/problem/872470/no-cc-intellisense-error-squiggle-for-must-return.html

**Comment by bobbrow** [comment]
This still repros, but the Developer Community link is invalid and would have been closed as "lower priority" by now anyway. Unfortunately, that means we won't likely see a fix in VS Code either.
