### ISSUE TITLE
No C/C++ IntelliSense squiggle for uses of undefined variables after the 1st usage

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4808]
Use C/C++ code:

```

void func()
{
	undefined;
	undefined;
}

```

Bug: The 2nd undefined doesn't have a squiggle. Hover gives no info. It would be better if it did.

2 squiggles get shown for certain cases like

```
void func(int i)
{
	if (i > 0)
	{
		return undefined;
	}
	return undefined;
}

```

https://developercommunity.visualstudio.com/content/problem/872555/no-cc-intellisense-squiggle-for-uses-of-undefined.html

**Comment by Colengms** [comment]
@sean-mcmanus Are you sure this isn't by-design?  I've noticed this before and had assumed it was intentional to avoid generating a potential flood of redundant errors/squiggles.  The error is only reported once per function, on first unique use.

**Comment by sean-mcmanus** [comment]
Yeah, it does seem "by desig".
