### ISSUE TITLE
The "Show Fixes" is nothing but "Add include path to setting"

### ISSUE THREAD

**Issue by sleepymole** [microsoft/vscode-cpptools#481]
![screenshot1](https://cloud.githubusercontent.com/assets/17199941/22731073/59fb49f2-ee24-11e6-8bb1-49b8ba8406ed.png)
I have included path to "c_cpp_properties.json". However, the "show fixes" is always there whenever I am coding.
![screenshot2](https://cloud.githubusercontent.com/assets/17199941/22731469/be649460-ee25-11e6-9eb4-643153e0c5bb.png)

**Comment by sean-mcmanus** [comment]
The bug was introduced in our extension by a change to the VS Code 1.9 update. A fix will be released soon.

**Comment by bobbrow** [comment]
Tracked by #472
