### ISSUE TITLE
 Garbled preview of function definition

### ISSUE THREAD

**Issue by zjh3029** [microsoft/vscode-cpptools#4810]
Issue Type: <b>Bug</b>

 When using this plug-in for function preview, there will always be garbled characters in the Simplified Chinese comment, but the Chinese display is normal after clicking into the function definition;
![image](https://user-images.githubusercontent.com/25833121/71712650-177c5e80-2e41-11ea-9d57-ae79932fda96.png)

Extension version: 0.26.3-insiders2
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by sean-mcmanus** [comment]
Your file encoding is not UTF-8, right? It's GBK? I believe this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/414 (lack of support for encodings other than UTF-8). We'll double-check this issue is also fixed after we fix that.

**Comment by zjh3029** [comment]
yes, It's GBK.   thanks

**Comment by sean-mcmanus** [comment]
Should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 . Let us know if you see any remaining bugs with non-UTF-8 encodings.
