### ISSUE TITLE
Add setting (and/or auto-heuristic) to limit the maximum number of IntelliSense processes to spawn

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#4811]
Based on a user comment in https://github.com/microsoft/vscode-cpptools/issues/3220 for 12 IntelliSense processes using >600 MB each (or more?) on a machine with 8 GB RAM.

Right now, our heuristic uses core count and not total available memory.

https://github.com/microsoft/vscode-cpptools/issues/4036 is tracking the Find All References case.

https://github.com/microsoft/vscode-cpptools/issues/4038 (Find All References) caching could be added more easily if this were fixed.

**Comment by joaquin-herrero** [comment]
Not sure if it is 100% related with the limit of spawn processes but here I have a machine with 12 cores and 12GB of RAM running Debian 9 and VSCode 1.43. 

I have 23 processes of cpptools eating all my RAM so I need to reboot the machine again and again. 

Te two things I can do are:
Set Intelli Sense Engine to tag parser seems to stop cpptools processes to eat all the memory.
Set the memory system limits to avoid the system hang up, but this makes me unable to use cpp features on VSCode.

**Comment by sean-mcmanus** [comment]
@joaquin-herrero What version of our C/C++ extension are you using? I assume 0.27.0-insiders3? Are you using multi-root? Are you using multiple VS Code instances? Do you mean 23 cpptools processes or 23 cpptools-srv processes (or the old-named Microsoft.VSCode.Cpp proceses). Only 1 cpptools process is expected per VS Code instance. Having 23 cpptools-srv processes open is not expected unless you have 12 C++ files open and then run a Find All References operation. If you close VS Code do the processes go away (i.e. are there any dangling processes)? If you close files you aren't using, the cpptools-srv processes should go away (there's a few second delay).

Setting the IntelliSenseEngine to "Tag Parser" disables a lot of our functionality so it's not recommended.

Setting the CPU affinity that controls which cores a process can run on might also be a workaround, depending on your OS's support for that.

**Comment by terriblefire** [comment]
Happens for me too. Makes my macOS system unusable when opening a large project (e.g. Mame) in VSCode.

**Comment by sean-mcmanus** [comment]
@terriblefire This issue is only about the number of IntelliSense processes to spawn, and currently only 1 process spawns per file open up to around the core count -- do you have lots of files open? If you're seeing an issue with only 1 file open, then you're seeing a different issue (you may be seeing multiple threads from the same process).

**Comment by bruno-kakele** [comment]
Happens to me too. I tried using vscode with the C++ plugins and it spawns 4 processes on my old laptop, which has 8GB RAM only. The cpptool-srv eats up all the memory and eventually I have to restart the computer.

**Comment by sean-mcmanus** [comment]
This is available in https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders. The maximum number of IntelliSense processes can be configured with the `C_Cpp.intelliSense.maxCachedProcesses` setting, and the number of processes will automatically decrease when the free memory becomes < 256 MB and it can be configured to use less memory via the maxMemory settings (memory usage from code analysis is not handled yet).
