### ISSUE TITLE
Is there current configuration inside public API?

### ISSUE THREAD

**Issue by 13n1n** [microsoft/vscode-cpptools#4813]
I can't manage how to check under my extension current configuration chosen by the user.
![image](https://user-images.githubusercontent.com/1568959/71781072-82619d00-2fdb-11ea-82a0-abb25e9067c2.png)
I investigated that inside extension this is resolving by [`C_Cpp.ConfigurationSelect`](https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/commands.ts#L25) command which binds on [`onSelectConfiguration`](https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/extension.ts#L878). How my extension can gather such information? I can extend API by myself but this won't a solution in the future. Maybe it could be done with a better method, am I right?

**Comment by michelleangela** [comment]
You can get current configuration name with the command `${command:cpptools.activeConfigName}`

Or invoke in Typescript:
```
vscode.commands.executeCommand('cpptools.activeConfigName')
```

Is this what you're looking to do?

**Comment by 13n1n** [comment]
Seems to be exactly the one. Thanks!

пн, 6 янв. 2020 г., 21:54 Michelle Matias <notifications@github.com>:
