### ISSUE TITLE
gcc/g++ inline asm syntax produces an "expected a ')'" warning

### ISSUE THREAD

**Issue by paul-reilly** [microsoft/vscode-cpptools#4814]
Issue Type: <b>Bug</b>

```cpp
auto getChar() 
  -> uint8_t
{
    uint8_t res = 0;
    uint8_t var = 65;
    asm(R"(
        mov al, %[var]
        mov %[res], al
    )"
    : [res] "+g" (res)  // <- warning produced at this ':'
    : [var] "g" (var)  
    : "eax" );

    return res;
}
```

Extension version: 0.26.2
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.94GB (2.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
The code doesn't compile with cl.exe/msvc mode (which is what it appears to be using). If you intend the code to compile with gcc/clang, can you change your compilerPath/intelliSenseMode? You can run the VS Code command "C/C++: Log Diagnostics" see what compiler settings are being used for the current file.

**Comment by paul-reilly** [comment]
Good point, thanks. Changing the `C_Cpp.default.compilerPath` to gcc works.

Really sorry about exposing you to that brain fart!

<makes slow retreat in reverse, bowing continuously as he departs>
