### ISSUE TITLE
[loc][Query][vscode-cpptools] Localizability of 0; "./src/LanguageServer/references.c.cpp.peek.references"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4815]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
C/C++ Peek References

String ID:
0; "./src/LanguageServer/references.c.cpp.peek.references"

File Name:
Src\vscode-extensions\vscode-cpptools.xlf

Query:
Could you please provide more information on "peek references"? Is it connected with "Peek References" (0; "./src/LanguageServer/references.peek.references")? Thank you.

**Comment by Colengms** [comment]
"Peek References" is the name of the feature.  That name is displayed in multiple places (usually using "references.peek.references").  For, "c.cpp.peek.references", the prefix "C/C++" was added in order to group multiple features in a list and group/sort them together with other "C/C++" feature.

**Comment by PDostalek** [comment]
Thanks !
