### ISSUE TITLE
[loc][Query][vscode-cpptools] Localizability of 0; "./src/nativeStrings.not_exited_yet"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4816]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
not exited yet. Will sleep for {0} milliseconds and try again.

String ID:
0; "./src/nativeStrings.not_exited_yet"

File Name:
Src\vscode-extensions\vscode-cpptools.xlf

Query:
Should we keep lowercase at the beginning? What does appear before this?

**Comment by Colengms** [comment]
In context, the text is referring to a process that it is trying to terminate.  A better English version of this string would be: "The process has not yet exited.  Will sleep for {0} miliseconds and try again."

**Comment by PDostalek** [comment]
@Colengms thx for reply, but which string is concatenated with? Cannot find the remaining part of that " The process has.."

**Comment by Colengms** [comment]
There is no other string to concatenate with.  You have the complete string.  It is not a complete sentence.  We will update it to be the string I mentioned; "The process has not yet exited. Will sleep for {0} miliseconds and try again."

**Comment by PDostalek** [comment]
Many thanks
