### ISSUE TITLE
[Python] Library source not syncing with gdb in SSH session

### ISSUE THREAD

**Issue by jordankubica** [microsoft/vscode-cpptools#4817]
Type: Debugger

**Describe the bug**
- Windows 10 workstation and Centos 7 remote host VM
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.2
- When I run a debug configuration in an SSH session, gdb runs the program but I cannot set breakpoints: "Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained"
- I can get the debugger to pause with raise(SIGTRAP) but it does not link back to the source file, and in fact all stack frames show "Unknown Source".
- When I start the same debug configuration locally in the VM it works as expected except that X11 performance is poor so this is not viable.

**To Reproduce**
[launch.json.txt](https://github.com/microsoft/vscode-cpptools/files/4027075/launch.json.txt)
1. Open some C++ shared library source code in a VSCode SSH session
2. Add raise(SIGTRAP) and/or breakpoints around the library entry point
3. Build the library from command line
4. Configure debugger to run a Python script which calls into the library
5. Run Python in the debugger
6. Notice that breakpoints are missed and all stack frames show "Unknown Source".
7. Close the VSCode remote session and go open the project locally.
8. Run the same debug configuration and notice that everything works properly.

**Additional context**
I have installed VSCode on a Windows PC and CentOS VM, and set up remote development from the PC to the VM. I'm trying to use cppdbg on a shared library which is built by CMake in a terminal and called from a Python program. I have tried various permutations of source code maps but this has no effect.

**Comment by pieandcakes** [comment]
@jordankubica I think you need to tell gdb to follow the child fork. Python will spawn the native process but gdb won't follow it. 

in your `launch.json`, add a `setupCommands` block with the command `set follow-fork-mode child`. 

Reference [here](https://sourceware.org/gdb/onlinedocs/gdb/Forks.html). 

The reason why it will say `Unknown Source` is probably that it didn't load symbols. Can you check the `engineLog` and see that the symbols for your library are loaded?

**Comment by jordankubica** [comment]
Hi, thanks for the suggestions. I tried `set follow-fork-mode child` but this caused the debugging session to exit while the program was still running, so I think "parent" is the correct setting here.
In the debug console I can see that symbols are being loaded for the target library from the same path as when I run the debugger locally as expected. I still think this has something to do with the SSH tunneling, since this source code desync is the only visible difference between running the same debug configuration locally or remotely.

**Comment by pieandcakes** [comment]
>I still think this has something to do with the SSH tunneling, since this source code desync is the only visible difference between running the same debug configuration locally or remotely.

Between locally/remotely are you sing the exact same `gdb`? If you look at the log, when it binds the breakpoint, what is the `breakpoint-created` or `breakpoint-modified` message? does it point to the memory address that the library is loaded in? There also should be a request for `symbol-list-line` that might tell you if we're looking in the right spot. 

If you want to create a sample that allows me to Build/Debug it, I can try and debug it from my side. Otherwise, if you send me the log privately, I can look at it and see if I can narrow down what is failing.
