### ISSUE TITLE
debug breakpoint opens second copy of the file (real path) when project folder path has a symlink part

### ISSUE THREAD

**Issue by payonel** [microsoft/vscode-cpptools#4818]
Type: Debugger

* note, this bug has already been reported to the remote extension github, because this issue ONLY happens when i open a remote folder with the vscode remote extension: https://github.com/microsoft/vscode-remote-release/issues/2057 - they wanted me to report this to you instead.

**Describe the bug**
Version: 1.42.0-insider
Commit: 9349e9a2fdbd1d92824ce99af4a50b6785351b11
Date: 2020-01-06T10:32:25.858Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.1.0-050100-generic

- C/C++ Extension Version:
ms-vscode.cpptools Version 0.26.3-insiders2: December 18, 2019

- Other extensions you installed (and if the issue persists after disabling them):
Name: Remote - SSH (Nightly)
Id: ms-vscode-remote.remote-ssh-nightly
Version: 2019.12.44160

**To Reproduce**
1. open a remote folder (ms-vscode-remote)
2. open a source file from the browser
3. build and debug to breakpoint

vscode opens a 2nd file, from an absolute path instead of using the relative file for the project folder.

**Additional context**
debuging a project folder locally does not reproduce this, only using remote.

**Comment by pieandcakes** [comment]
>vscode opens a 2nd file, from an absolute path instead of using the relative file for the project folder.

can you give me a concrete example of the relative file path vs the absolute file path? you should be able to get both when you hover over the tab. I'm not understanding the problem.

**Comment by payonel** [comment]
sure! thanks for reading my bug report :)

spoiler, turns out this bug repros when home is symlinked to /data/home

and now that i go to test this to get exact data you are asking for, i realize this one bit more complicated than i first thought. also, I was wrong about "relative path" -- you'll see in my explanation. 

assume we are using remote-ssh plugin to open `/home/user/code` on a remote machine `remote-host`

1. open vscode `code-insiders`
2. open `/home/user/code/` on `remote-host` via remote-ssh plugin
3. open, via vscode folder browser (ctrl+b), main.cpp. the files path on file tab for vscode is /home/user/code/main.cpp
4. set a break point in main.cpp
5. launch main.cpp in debug

expected:
break point is hit in the main.cpp you have open

actual: (when it repro'd...which it isn't doing)
a 2nd file tab is open, the tab label says /data/home/user/code/main.cpp -- the existing tab that is open for /home/user/code/main.cpp is not used for the file path

yep, it's because home is really `/home -> /data/home` (i think centos 6 is to blame for this unusual layout)

**Comment by pieandcakes** [comment]
If that is the problem, It probably isn't something we can fix cheaply. VS Code won't do any string processing on the filepath we return and we're probably getting the "correct" one for `/data/home` from the symbol file (you can confirm this by looking in the engineLog) and sending it to VS Code. Unfortunately VS Code doesn't reconcile that those files are the same and we as the debug adapter don't know which files you have open.

You can try and add a `sourceFileMap` to map `/data/home` to `/home` and then it should replace `/data/home` with `/home` which will fix it in your case.

**Comment by pieandcakes** [comment]
Also, really strange this doesn't manifest locally.

**Comment by payonel** [comment]
now that i understand the root cause, i can work around the problem by opening /data/home/user/code instead, then the paths should match

with regards to no local repro, that isn't AS true as I first thought -- my local system doesn't use a /home -> /data/home link, so it's not the same test. I suspect vscode running directly on the remote machine would repro this (i dont have X on the remote to test this currently, will test later)

**Comment by payonel** [comment]
ok this has nothing to do with centos, nor the home dir, just if part of the path is a symlink, then the break point will open the "real" path

**Comment by pieandcakes** [comment]
Correct. this isn't a problem we can solve as we don't know what the editor has open. It would be up to [VS Code](https://github.com/microsoft/vscode/issues) to solve it.

**Comment by Lassebq** [comment]
Is [this](https://github.com/microsoft/vscode/issues/130082) the relevant issue that is expected to fix this behavior?

**Comment by sean-mcmanus** [comment]
@Lassebq I think so.
