### ISSUE TITLE
include paths are broken

### ISSUE THREAD

**Issue by sollapse** [microsoft/vscode-cpptools#482]
It seems that include paths are not being resolved when setting them in the c_cpp_properties.json object. I'm running VS Code on Ubuntu 16.04. 

![image](https://cloud.githubusercontent.com/assets/14261598/22797203/1179e70c-eec3-11e6-9101-9f49714dcce3.png)

**Comment by sean-mcmanus** [comment]
Does re-starting VS Code fix this? 0.10.0 may have had some bugs with updating the includePath. We're releasing a 0.10.1 update soon (today?) that might fix this.

**Comment by sollapse** [comment]
Restarting VS Code does not solve the issue. Along with deleting the json config and recreating the file with an app restart.

**Comment by sean-mcmanus** [comment]
Hmm...then I'm not able to repro what you are seeing. I believe your .browse.vc.db is corrupted. You should delete it or change the databaseFilename in c_cpp_properties.json (it should be a full path). The symptom you are a seeing occurs when we fail to locate the filename in the .browse.vc.db. There may have been some problem recursing through your workspace, which occurs before the includePath is searched.

**Comment by sollapse** [comment]
This file does not seem to have been created. How would I generate it?

**Comment by sean-mcmanus** [comment]
It should auto-generate when you open a workspace. There have been some bugs where it can fail to be created, but if you specify the full path in the databaseFilename, that should work, e.g. /home/user/newProject.db . It's at /home/user/.config/Code/user/workspaceStorage/guid/ms-vscode.cpptools/.browse.vc.db by default.

**Comment by bobbrow** [comment]
Please reopen if you are still having a problem with this on the latest version of the extension.
