### ISSUE TITLE
Intellisense stopped working on Manjaro Linux

### ISSUE THREAD

**Issue by tbhaxor** [microsoft/vscode-cpptools#4822]
**Type: LanguageService**

**Describe the bug**
+ Version: 1.41.1
+ Commit: 26076a4de974ead31f97692a0d32f90d735645c0
+ Date: 2019-12-20T11:11:01.597Z
+ Electron: 6.1.7
+ Chrome: 76.0.3809.146
+ Node.js: 12.4.0
+ V8: 7.6.303.31-electron.0
+ OS: Linux x64 5.4.6-2-MANJARO
+ Other extensions you installed (and if the issue persists after disabling them): Issue persists even if this extension is installed
+ A clear and concise description of what the bug is
```
I am not able to format my C++ Code
```

**To Reproduce**

1. Create any file `test.cpp`
2. Try to format it
3. The error notification will come with the message
```
/home/terabyte/.vscode-oss/extensions/ms-vscode.cpptools-0.26.3-insiders2/bin/../LLVM/bin/clang-format -style={ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 2, TabWidth: 2, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -2 } -fallback-style=LLVM -sort-includes=0 -assume-filename=/home/terabyte/test.cpp
/home/terabyte/.vscode-oss/extensions/ms-vscode.cpptools-0.26.3-insiders2/bin/../LLVM/bin/clang-format: error while loading shared libraries: libtinfo.so.5: wrong ELF class: ELFCLASS32
```

**Expected behavior**

It should format the code with `clang-format`

**Screenshots**

All the information are provided

**Additional context**

All the information are provided

**Comment by sean-mcmanus** [comment]
This is a known bug we're tracking with https://github.com/microsoft/vscode-cpptools/issues/3174 and https://github.com/microsoft/vscode-cpptools/issues/4539 .
