### ISSUE TITLE
Add custom config entries to Log Diagnostics

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#4826]
**Type: LanguageService**

The Log Diagnostics command prints out the current config, but doesn't list the "special" configurations like `compile_commands.json` and custom configs.  We should be able to print out the entries for the active translation units as well as the "custom browse path" (if set).

**Comment by sean-mcmanus** [comment]
@bobbrow I don't understand what this issue is about exactly -- what info should be added? Just the custom config browse path? What is there to print about the compile commands that isn't already printed?

**Comment by bobbrow** [comment]
For translation units (e.g. Foo.cpp), we'd want to print out the verbatim compile commands entry for it (or the custom config we received for it).  This allows us to check whether data was lost or misinterpreted before creating the TU for it.

For browse path, this should be relatively easy in the config provider scenario.  For compile commands, you'd build on the work @elahehrashedi just did.

**Comment by bobbrow** [comment]
The work for custom configurations is done. A new issue will be created for compile_commands.json logging
