### ISSUE TITLE
std::getline gives error

### ISSUE THREAD

**Issue by naklow12** [microsoft/vscode-cpptools#4828]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows
- VS Code Version: 1.40.1
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them): Code Runner

std::getline has a problem, for example:
        `std::getline(input, line, ':');`
When I compile it it's working well, but IntelliSense is not working.

**Comment by michelleangela** [comment]
@naklow12, I couldn't reproduce IntellliSense issue for `std::getline`.

Can you provide a repro sample that produces the issue and a `c_cpp_properties.json` if you have one configured for IntelliSense?

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
