### ISSUE TITLE
Implement a solution to deal with extension installation/download failures

### ISSUE THREAD

**Issue by rolandma** [microsoft/vscode-cpptools#4829]
I can't get the intellie server to start after upgraded to the 0.26.3-insiders3 because I missed Microsoft.VSCode.CPP.Extension.exe in bin folder. So I have to copy one from the 0.26.2/bin folder, then it'll work fine.

**Comment by Colengms** [comment]
Hi @rolandma .  We've been receiving feedback that the install process sometimes does not complete successfully.  This may have something to do with terminating VS Code while it is in the process of installing (or, in this case, while we're downloading some needed binaries such as Microsoft.VSCode.CPP.Extension.exe, on first run).  I'd suggest uninstalling cpptools, deleting it's extension directory, and installing again.  You may run into issues if not using a matching version of that binary.

**Comment by bobbrow** [comment]
We'll use this issue to track implementing a solution for dealing with download failures.

**Comment by rolandma** [comment]
As of now, this failure is still happening. There's a setting in the extension 

> C_Cpp: Update Channel
> Set to "Insiders" to automatically download and install the latest Insiders builds of the extension, which include upcoming features and bug fixes. 

which automatically tries to load the latest preview, and cause this problem repeatedly. So before a fix is available, I suggest to disable the "insider" level, switch it back to default.
