### ISSUE TITLE
Peek definition is not working for the code that is in samba server

### ISSUE THREAD

**Issue by veda87** [microsoft/vscode-cpptools#483]
Recently, I installed VS code on my Windows machine and added C/C++ extension to enable peek definition. 

My code (which is in multiple folders) is currently on my Linux (samba server) and I mounted the server as a network drive. I was able to open the code using the VS code. But unable to do peek definition or declaration.

Note: if my code resides on my Windows local drive, everything works fine.

**Comment by sean-mcmanus** [comment]
I'm not able to repro any problem with 0.10.1 and VS Code 1.9.1/1.10.0 with a Linux samba 4.3.11-Unbuntu server and Win10 host. Peek definition is working for files in the workspace root and files in the includePath. Your host machine will need to have access to the files with the definition in it and they have to be set to the correct includePath for your configuration (in c_cpp_properties.json). Can you provide more repro info?

**Comment by veda87** [comment]
Here is the test I'm using

I have a root folder TestVScode which has sub-folders folder-1 & folder-2  which has the codes. 

My configuration is

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/usr/include",
                "/usr/local/include"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "Z:/TestVScode/*"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                "Z:/TestVScode/*"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ]
}
```

When I tried to go to declaration using `F12`, I'm getting the following error

`Unable to open 'BOXTEST.HPP': File not found (z:\TESTVSCODE\FOLDER-1\SRC\BOXTEST.HPP).`

Even if I tried to create a new file, I'm getting

`A system error occured (ENOENT: no such file or directory, mkdir 'z:\TESTVSCODE\FOLDER-1')`

So, on my Windows machine, what will be my configuration. Is it Win32 or Linux? Can you provide me an example

**Comment by bobbrow** [comment]
It looks like you have a * in your include path for Z:/TestVSCode.  The * means to only add the current folder to the include path.  Remove the * and it should recursively add all sub directories as well.

**Comment by bobbrow** [comment]
What is the actual casing of the file path?  This could also be a case-sensitivity issue for Linux.

**Comment by sean-mcmanus** [comment]
If your host is a Windows machine, the default config will be Win32, so that would be the easier config to use, but you want to make sure your includePath is correct for the Linux files you want. I'm still not able to get a repro, but when you create a file, we should not be causing a system error, so it sounds like there is some other problem with either VS Code or Samba. The casing is strange (looks like a canonicalized Windows path, which wouldn't match the Linux casing).

**Comment by veda87** [comment]
On my Linux server. The directory structure is $HOME/TestVScode/Folder-1
I mounted my HOME on Z drive. 

If I access those files in Windows Explorer, It is "Computer > Veda (... Linux address...)(Z:) > TestVSCode > Folder-1

Question: I don't know why the casing changes? Any reason for it?

**Comment by sean-mcmanus** [comment]
I don't know where the changed casing is coming from (we have code that changes the casing on Windows but that doesn't appear to be causing the problem). If you're not able to create a folder then it sounds like a VS Code bug and would repro without our extension. Can you file a bug with them? I assume you can create a folder without using VS Code. It's possible another VS Code extension could be causing the problem.

**Comment by bobbrow** [comment]
If you are continuing to have issues with this, please let us know.  Thanks!

**Comment by Windeal** [comment]
I still have the same problem. 
My host is windows 10， My code is on a Linux machine (samba server). And I use samba to access the code.
I mounted the server as a network drive 
windealli(\\10.125.229.10\dev-suse-kqq131)--->Z:
My code folder is Z:\AIBuilding\vrelay.
My vscode-cpp configure:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "Z:/AIBuilding/vrelay/**",
                "${workspaceFolder}/**"
                
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\TDM-GCC-64\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

It is OK to create file on the folder. 
It is OK if my code is on my windows machine, 

vscode 1.28.2
ms-vscode.cpptools  0.19.0

**Comment by Windeal** [comment]
@bobbrow  Is there anyone concern this issue？ Could you reproduce this issue？ Or need more information？

**Comment by bobbrow** [comment]
I've been tagging network drive-related issues so I can keep track of how prevalent this is.  Since we're a small team with limited resources to fix bugs, we have to prioritize issues based on how many people are affected.  I'll reopen this issue so that we don't lose track of it.

**Comment by Windeal** [comment]
> I've been tagging network drive-related issues so I can keep track of how prevalent this is. Since we're a small team with limited resources to fix bugs, we have to prioritize issues based on how many people are affected. I'll reopen this issue so that we don't lose track of it.

Ok， thanks

**Comment by Windeal** [comment]
Tips： 
I think the reason for this problem is probably that file path in Unix is case sensitive but is not in windows.

**Comment by vince-zeng** [comment]
I met the same issue (Win10  + Ubuntu Samba). And I have to  do the network driver map on Win10 to fix it.

**Comment by alexz4321** [comment]
Yes. Same issue. Version 1.39.2.
BUT peek definition will work after you open source code file once.

**Comment by hobbes78** [comment]
This issue is also happening to me. I'm accessing from Windows a Samba share served from a Solaris machine.
- SunOS CMF-SOLARIS 5.10 Generic_141445-09 i86pc i386 i86pc
- Microsoft Windows [Version 10.0.18362.476]
- Visual Studio Code 1.41.1

**Comment by bobbrow** [comment]
We did make some fixes for UNC paths recently that may help, but without a repro, we are unfortunately unable to fix this issue.  If anyone is still experiencing this problem, please open a new issue with steps that will help us reproduce the problem.

Thank you!
