### ISSUE TITLE
Intellisense issue with initialization of nested enum

### ISSUE THREAD

**Issue by marzojr** [microsoft/vscode-cpptools#4831]
**Type: LanguageService**

**Description**
- OS and Version: Windows 10, Ubuntu 19.10, probably others
- VS Code Version: 1.41.1 (probably earlier versions too)
- C/C++ Extension Version: 0.26.3-insiders3 (probably earlier versions too)
- Issue happens even with all other extensions disabled

**To Reproduce**
1. Create a c++ file with the following code:

```c++
    const struct Action {
    	enum {
    	    value1 = 0,
    	    value2
    	} type;
    } ActionList[] = {
    	{ Action::value1 }
    };
```
2. Save the file
3. Intellisense will display the following message:
    > a value of type "enum Action1::&lt;unnamed&gt;" cannot be used to initialize an entity of type "enum Action1::&lt;unnamed&gt;"

**Expected behavior**
The code is valid, and there should not be a message. For this simple case, there is little issue; but in the actual case, there are 83 instances of this error.

**Additional context**
If the enum is given a name, the issue persists:

```c++
    const struct Action {
    	enum Values {
    	    value1 = 0,
    	    value2
    	};
    	Values type;
    } ActionList[] = {
    	{ Action::value1 }
    };
```
gives the following message:
> a value of type "Action::Values" cannot be used to initialize an entity of type "Action::Values"

Splitting the structure declaration and the variable initialization works, as does declaring the enum out of the struct.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. It repros with VS too, so I've filed a bug at https://developercommunity.visualstudio.com/content/problem/883249/cc-intellisense-error-with-initialization-of-neste.html .

**Comment by bobbrow** [comment]
The issue reported to Visual Studio was closed as "lower priority." Unfortunately, this means we won't likely get a fix for VS Code either.
