### ISSUE TITLE
Microsoft.VSCode.CPP.IntelliSense.Msvc.exe crash on hover over nested struct name in C file

### ISSUE THREAD

**Issue by JFXTK** [microsoft/vscode-cpptools#4832]
OS and Version: Win7
VS Code Version: 1.41.1
C/C++ Extension Version: 0.26.3-insiders3
When edit one of my project,  Microsoft.VSCode.CPP.IntelliSense.Msvc.exe crashes frequently, after every time reload window,  Microsoft.VSCode.CPP.IntelliSense.Msvc.exe will crash in about tow minute when edit c file.
-----------------------------------------------------
I attach Microsoft.VSCode.CPP.IntelliSense.Msvc.exe with gdb,  gdb report Microsoft.VSCode.CPP.IntelliSense.Msvc.exe got SIGSEGV.
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) attach 8804
Attaching to process 8804
[New Thread 8804.0xc74]
[New Thread 8804.0x80c]
[New Thread 8804.0x22c0]
[New Thread 8804.0x102c]
[New Thread 8804.0x116c]
[New Thread 8804.0x1cdc]
[New Thread 8804.0x1e08]
[New Thread 8804.0x1d44]
[New Thread 8804.0x1c18]
[New Thread 8804.0xf20]
[New Thread 8804.0x21f4]
[New Thread 8804.0x2050]
Reading symbols from c:\Users\jfx\.vscode\extensions\ms-vscode.cpptools-0.26.3-insiders3\bin\Microsoft.VSCode.CPP.Intell
iSense.Msvc.exe...(no debugging symbols found)...done.
(gdb) c
Continuing.
[Thread 8804.0x2050 exited with code 0]
[Thread 8804.0x21f4 exited with code 0]
[New Thread 8804.0x2244]
warning: Error -
warning: Invalid args, too  big block
warning:
warning: Error -
warning: Invalid args, too  big block
warning:

Thread 13 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 8804.0x2244]
0x0061f7c1 in ?? ()
(gdb)
-----------------------------------------------------------------
log of c/c++ as
[log_cpptool.txt](https://github.com/microsoft/vscode-cpptools/files/4049415/log_cpptool.txt)

-----------------------------------------------------------------
test file:
[gui_frame_dc.txt](https://github.com/microsoft/vscode-cpptools/files/4049489/gui_frame_dc.txt)
rename this txt file to gui_frame_dc.c, open with vscode, put cursor to line 24, Microsoft.VSCode.CPP.IntelliSense.Msvc.exe crashed every time

**Comment by Colengms** [comment]
Hi @JFXTK .  Thanks for reporting this to us.  I'm able to repro with the file you provided.  We will investigate.

**Comment by Colengms** [comment]
It looks like this issue also repro's in Visual Studio.  (We share common code for IntelliSense with Visual Studio).  I've opened a bug against VS here: https://developercommunity.visualstudio.com/content/problem/883246/vcpkgsrvexe-crash-on-hover-over-nested-struct-name.html

**Comment by bobbrow** [comment]
This appears to be fixed in the latest version of the extension.
