### ISSUE TITLE
[MinGW] Build/debug active file says there is no compiler

### ISSUE THREAD

**Issue by Azenor1er** [microsoft/vscode-cpptools#4834]
Type: General

**Describe the bug**
- OS and Version: W10 Pro, ver 1903
- VS Code Version: 1.41.1
- C/C++ Extension Version: 1696 ? I guess ?
- Other extensions you installed (and if the issue persists after disabling them): Noone
- A clear and concise description of what the bug is.
I just install VS Code on my new computer to continue my prog. I download the extension C++ Build And Debug Active File (as it's wrote on https://code.visualstudio.com/docs/cpp/config-mingw#_prerequisites ), but it say there is no compiler.
I have the MinGW which is on my computer.
When I try to use compilor, it's like the screenshot. No compilor for C++ I guess :(

**Expected behavior**
Try to uninstall and reinstall VS Code, on different versions. Tried to download lots of extensions of C++ (that's what I'm looking to prog)

**Screenshots**
![image](https://user-images.githubusercontent.com/59807600/72226499-1b6f5580-3592-11ea-9151-8d937068c073.png)

**Additional context**
Add any other context about the problem here including log messages from the Output window.
-

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. We have a fix at https://github.com/microsoft/vscode-cpptools/pull/4844 / (mistaken `||` instead of `&&`). A workaround is to set your compilerPath (in c_cpp_properties.json) to anything non-empty, such as "a" (or a valid path). If that workaround doesn't work, then you could be hitting a different bug.

**Comment by sean-mcmanus** [comment]
Should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3-insiders4
