### ISSUE TITLE
Breadcrumbs or outline can't show properly a symbol which contains a macro

### ISSUE THREAD

**Issue by monstertango** [microsoft/vscode-cpptools#4835]
**Describe the bug**
VSCode Version: Code Insiders
Version: 1.42.0-insider
Commit: 7e64866
Date: 2020-01-09T06:44:40.132Z
Electron: 6.1.6`//example.cpp
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-66-generic

C/C++ Extension Version: ms-vscode.cpptools-0.26.3-insiders3
- Other extensions you installed (and if the issue persists after disabling them):
Git Blame - Wade Anderson
Git History - Don Jayamanne
Head-File-Guard - bjr 
Path Intellisense - Christian Kohler
Python - Microsoft 
QML - Baptist BENOIST
QML Snippets - Baptist BENOIST 
Qt for Python - Sean Wu 
Rust (rls) - rust-lang 
VSCode Sequence Diagrams - Aleksandar Toplek 
Material Icon Theme - Philipp Kief 
Material Theme Icons - Mattia Astorino
Bracket Pair Colorizer - CoenraadS
Code alignment - Chris McGrath

- A clear and concise description of what the bug is.
Steps to Reproduce:
case 1 :
Breadcrumbs or outline and even Find symbol in a file  can't show properly a symbol which contains a macro.
Also,  they has same issue in c++ 11 'foreach' statement .

![image](https://user-images.githubusercontent.com/38209036/72232206-efd88380-3602-11ea-9ad7-e41521705bb4.png)

![image](https://user-images.githubusercontent.com/38209036/72232215-ff57cc80-3602-11ea-901e-1b0e71c5b5ea.png)

for me, the code is c++ . below is simple example.
### `//example.cpp
#define MACRO_1( s ) \
    if ( s == "" )

class Query
{
	Query( int d=0);
	virtual ~Query();
	void query(const char* sql);
	void find(int id);
	void exec();
	void next();
	int  error() const;
	int  lastErr;
};

Query::Query(int d)
{
}

Query::~Query()
{
}

void Query::query(const char* sql)
{

}
void Query::find(int id)
{

}
void Query::exec()
{
	if ( true ) {
        MACRO_1( t1 ) {
			for (;;) {
			}
		}
	}
	else {
        MACRO_1( t2 ) {
		}
	}
}

bool Query::next()
{
	return true;
}

int Query::error() const
{
	return lastErr;
}`

**Comment by sean-mcmanus** [comment]
This is "by design". Macros that require evaluation in order for correct parsing require a cpp.hint file in the project with contents like `#define MACRO_1( s )`. Adding that and doing a C/C++: Reset IntelliSense Database and then Reload Window should fix it.

**Comment by sean-mcmanus** [comment]
FYI, this is fixed with 1.10.3 (pre-release) -- no cpp.hint is required for this case.
