### ISSUE TITLE
Stay * activated, but trigger *real* activation when C/C++ file is loaded

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-cpptools#4851]
From C++/VS Code sync meeting:

Delay *real* activation of C++ extension. Want to avoid notification that contents of extension have changed and the user needs to reload

Possible Solutions:
- Potentially have one extension that is language activated and one for tools that is always * activated that downloads platform specific bits and fetches latest, because extension should be ready to go

**Comment by sean-mcmanus** [comment]
I think VS Code's platform specific marketplace should eliminate the need to use "*" activation...not sure what their timeframe is on that yet though.

**Comment by pieandcakes** [comment]
We currently download platform specific files for both language service and debugger after * activation. If we choose to delay the activation, the user may be in a state where they assumed they were ready to go but then we need to download additional files. This becomes an issue if the user is then out of an area where they have internet connection. 

As @sean-mcmanus says, once there is support for the platform specific market place this should all go away.

**Comment by sean-mcmanus** [comment]
@pieandcakes I believe the user was requesting we always keep "*" as the activation event (not overwriting it), but then delaying "real activation" for anything that is "problematic" (unwanted, resource using), which is what our language server side does already.

**Comment by bobbrow** [comment]
@sean-mcmanus, yes, that is what we discussed in the VS Code sync meeting.  This is a request to investigate whether we can stay `*` activated so that we don't need to rewrite the package.json file.
