### ISSUE TITLE
Move documentation to Wiki.

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#486]
Currently, there is some documentation in the extension itself (clang settings, keyboard shortcuts), some documentation in launch.md (debugger example) in the repo and some documentation in the wiki (pipe transport functionality).

My suggestion would be to move the documentation to the wiki where it can be easily structured.

**Comment by pieandcakes** [comment]
@csholmq Yes, that is a task I have assigned to myself to try and add documentation to the Wiki. I'm up for some community help though so if anyone else wants to help, that would be great. I don't think we're planning on moving away from the blog model for release information.

**Comment by csholmq** [comment]
@pieandcakes I think the Wiki is restricted though. I can't seem to find any edit button :)

**Comment by pieandcakes** [comment]
@csholmq What if there is a directory within the code that has documentation instead of in the wiki? Would that work? Then we can take contributions from the community.

**Comment by bobbrow** [comment]
You should be able to clone the wiki, make edits, and send a pull request, no?

**Comment by csholmq** [comment]
@pieandcakes That would work! Similar to launch.md then?
@bobbrow Don't think that's how it works. But I could be wrong.

**Comment by pieandcakes** [comment]
@bobbrow I pushed a branch to the wiki but I can't figure out how to create a PR. 
@csholmq That should be fine. I can then probably port it over to the wiki.

**Comment by bobbrow** [comment]
I just tried editing my clone and submitted directly to master.  That worked for me.  That seems analogous to what would happen if you edited directly via the website.

**Comment by pieandcakes** [comment]
@bobbrow I added you as an admin, so that's probably why you can do it. I don't think the general public can do that.

**Comment by bobbrow** [comment]
I just found a setting that restricts editing the wiki to users with push access and toggled it off.  @csholmq, can you see if the Edit button is available to you now?

**Comment by pieandcakes** [comment]
I don't know if I want to open up the wiki to anyone to update without a Pull Request. I think we can do it one of two ways.
1) We can clone the vscode-cpptools.wiki into a branch in the main repo and manage changes there, sort of like http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github
2) We can keep our documentation in the main repo and not use the wiki.

Which one sounds better @csholmq @bobbrow

**Comment by csholmq** [comment]
@bobbrow No button, no.
@pieandcakes I vote for the second one. More apparent than the wiki perhaps.

**Comment by bobbrow** [comment]
Yeah, @pieandcakes toggled it back off, so I wouldn't expect it to work anymore.  In the absence of that option, I vote for number 2 as well.

**Comment by pieandcakes** [comment]
@bobbrow @csholmq The documentation folder is in the main repo. Hopefully as we create content, the README.md will be update with some basic navigation.
