### ISSUE TITLE
Error navigation from terminal to files in root folder

### ISSUE THREAD

**Issue by Fakamakato** [microsoft/vscode-cpptools#4861]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10 x64 1909
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Navigation to an error/warning doesn't work for files in the root, but works for files in subfolders.
**To Reproduce**

1. Write some code
2. Build
3. Watch terminal

**Expected behavior**

I want to be able to navigate to error\warning from all files. 
**Screenshots**

project structure
![structure](https://user-images.githubusercontent.com/41305618/72594240-0a1ea400-3918-11ea-8a45-3318a2949253.png)
works fine
![works](https://user-images.githubusercontent.com/41305618/72594241-0ab73a80-3918-11ea-9060-46665e1a9a9b.png)
doesn't work fine
![not](https://user-images.githubusercontent.com/41305618/72594242-0ab73a80-3918-11ea-98bd-4a964d77eaaf.png)

**Additional context**

{
    "configurations": [
        {
            "name": "vscode_stm32_c_cpp_properties_Windows",
            "compilerPath": "D:/Soft/6 2017-q2-update/bin/arm-none-eabi-gcc",
            "includePath": [
                "${workspaceRoot}/cmsis",
                "${workspaceRoot}/cmsis/inc",
                "${workspaceRoot}/cmsis_boot",
                "${workspaceRoot}/inc",
                "${workspaceRoot}/service/inc",
                "${workspaceRoot}/stm_lib/inc",
                "${workspaceRoot}/usb/inc",
                "${workspaceRoot}/usart/",
                "${workspaceRoot}/fatFS/",
                "${workspaceRoot}/"

            ],
            "defines": [
                "STM32F103xE",
                "STM32F10x",
                "USE_STDPERIPH_DRIVER",
                "STM32F10X_HD"
            ],
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
What is your problemMatcher set to you in your tasks.json? It sounds like it might be a VS Code issue.

This thread might be related: https://github.com/microsoft/vscode-cpptools/issues/2266

**Comment by Fakamakato** [comment]
> What is your problemMatcher set to you in your tasks.json? It sounds like it might be a VS Code issue.
> 
> This thread might be related: #2266

I tried different options with problemMatcher, it did not help. Might be because i use Makefiile?

**Comment by sean-mcmanus** [comment]
But you're using the $gcc problemMatcher, right?

The default should be the same as
```
    "problemMatcher": {
        "base": "$gcc",
        "fileLocation": ["relative", "${workspaceRoot}"]
    }
```

**Comment by Fakamakato** [comment]
> But you're using the $gcc problemMatcher, right?
> 
> The default should be the same as
> 
> ```
>     "problemMatcher": {
>         "base": "$gcc",
>         "fileLocation": ["relative", "${workspaceRoot}"]
>     }
> ```

Yes, that's right. I can put all source files into subfolders, than will be some kind of a solution.
