### ISSUE TITLE
'C_Cpp.ConfigurationEditJSON'  not found using remote ssh

### ISSUE THREAD

**Issue by elsucht** [microsoft/vscode-cpptools#4862]
Using vscode with cpptools under Win10 and remote ssh to a Ubuntu based Jetson Nano machine.
Getting error messages :
> command 'C_Cpp.ConfigurationEditJSON'  not found
> command 'C_Cpp.ConfigurationEditUI' not found

Tried 0.26.1 with same issue. Reinstalling and/or restarting did not help.

- OS and Version: Win10 10.0.18362
- VS Code Version:  1.41.1
- C/C++ Extension Version: 0.26.2
- Remote SSH (on Host), Cmake, Cmake Tools, Python(on Remote)

in addition there is a porblem:
> Unable to load schema from 'cpptools-schema:/c_cpp_properties.schema.json': Request vscode/content failed with message: cannot open cpptools-schema:/c_cpp_properties.schema.json. Detail: resource is not available.

**Comment by Colengms** [comment]
Hi @elsucht .  I'm not able to repro this (with remoting into standard desktop Ubuntu).  Is there anything output to the C/C++ channel in the output window?

**Comment by elsucht** [comment]
There is no C/C++ channel available in the output window. Looks like the installation does not go through normally. Every command I execute is not found...

> command 'C_Cpp.LogDiagnostics' not found

the remote server logs 
> [2020-01-20 09:18:42.729] [remoteagent] [info] Installing extension: ms-vscode.cpptools
[2020-01-20 09:18:44.048] [remoteagent] [info] Downloaded extension: ms-vscode.cpptools /tmp/4a4167ee-519d-40f6-8ae4-01b44c946111
[2020-01-20 09:18:44.110] [remoteagent] [info] Removed the extension from uninstalled list: ms-vscode.cpptools
[2020-01-20 09:18:44.127] [remoteagent] [info] Extensions installed successfully: ms-vscode.cpptools

**Comment by elsucht** [comment]
Tried the insiders version of vscode, remote ssh and cpptools and same issues exists.
At startup of vscode the message "Architecture arm64 is not supported. " appears. Could it be related to the issue?

**Comment by sean-mcmanus** [comment]
Our extension doesn't run on arm64 yet. We're tracking arm64 support at https://github.com/microsoft/vscode-cpptools/issues/2506 .

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.0.0
