### ISSUE TITLE
Cannot start server when running in remote SSH environment.

### ISSUE THREAD

**Issue by thatnerdjack** [microsoft/vscode-cpptools#4863]
### Describe the issue

- OS and Version: MacOS 10.15.2
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
Locally: Remote - SSH, Remote - SSH: Editing Configuration Files
Remote: just this plugin
- A clear and concise description of what the bug is:
When I reload or start the window, I immediately get an error in the output stating this:
```
[Error - 4:03:55 PM] Connection to server got closed. Server will not be restarted.
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```

Unsure of what error is or could be.

### To reproduce
Open a remote directory, ensure the plugin is installed, and see the error.

**Comment by sean-mcmanus** [comment]
Your host OS is Mac and your target OS is what? It looks like our extension process is crashing on the remote machine.

**Comment by thatnerdjack** [comment]
Sorry! That would be Ubuntu 18.04.3 LTS

**Comment by sean-mcmanus** [comment]
Does it crash even with a simple hello world project?

Are you able to get a call stack for the crash somehow? Such as via attaching a debugger before it crashes or configuring your OS to log the crash? The process is Microsoft.VSCode.CPP.Extension.linux on the remote machine.

We have a newer release at https://github.com/microsoft/vscode-cpptools/releases/tag/0.26.3-insiders4 , but I don't expect that to fix your issue.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
