### ISSUE TITLE
compile_commands.json could not be parsed for the one generated by Chromium

### ISSUE THREAD

**Issue by domenic** [microsoft/vscode-cpptools#4864]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 v1909
- VS Code Version: 1.41.1 (user setup)
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them): EditorConfig, ESLint, Glitch, Python, Remote - WSL, Rewrap, vscode-icons. I have not tried disabling them but can if you think that would possibly help.
- A clear and concise description of what the bug is: generating the `compile_commands.json` for the Chromium repository, and configuring `c_cpp_properties.json` to point to it, immediately tells me that the file could not be parsed.

**To Reproduce**

1. Check out Chromium according to [the instructions](https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md). Building it once is probably a good idea; at least do `gn gen out/Default`. My gn args are:

```
is_component_build = true
enable_nacl = false
is_debug = true
```

Note: I have Visual Studio 2019 installed but I don't believe I am configuring the Chromium build to use it in any way.

2. Generate `compile_commands.json` using `gn gen out/Default --export-compile-commands`. The resulting file is 254 MiB. I have uploaded it [here](https://1drv.ms/u/s!AnHv9ZPMBMTtkoZ0mbisW67maru1LA?e=WHV2lq).

3. Create the following `.vscode/c_cpp_properties.json` file:

```
{
  "configurations": [
    {
      "name": "Win32",
      "windowsSdkVersion": "10.0.18362.0",
      "compilerPath": "${workspaceFolder}/third_party/llvm-build/Release+Asserts/bin/clang-cl.exe",
      "compileCommands": "${workspaceFolder}/out/Default/compile_commands.json",
      "cStandard": "c11",
      "cppStandard": "c++17",
      "intelliSenseMode": "clang-x64"
    }
  ],
  "version": 4
}
```

4. Upon saving the file, I immediately get a toast in the lower right corner informing me that `"C:/src/chromium/src/out/Default/compile_commands.json" could not be parsed. 'includePath' from c_cpp_properties.json will be used instead.`

**Expected behavior**

A `compile_commands.json` created by clang should be able to be parsed by VS Code, I think. At least, VS Code should tell me where the parsing error occured; for example if it's just too big, then that would be good information.

**Comment by sean-mcmanus** [comment]
It doesn't appear to valid JSON, according to our parser and according to what I see, which is
```
"command": "..."..."...""
```
Looks like the string quotes aren't escaped? Your tool that outputs JSON has a bug? Or do you believe our parser has a bug?

**Comment by domenic** [comment]
Wow, thank you for the second set of eyes (especially so quickly). The problem is clearly on our side, so I will close this.

https://bugs.chromium.org/p/gn/issues/detail?id=140 for anyone else's reference.
