### ISSUE TITLE
Cannot Launch the C++ executable in Multi-Root Workspace?

### ISSUE THREAD

**Issue by hwhsuguest** [microsoft/vscode-cpptools#4865]
I want to use Multi-Root structure to edit and compile Multiple Project.
(Just like having multiple projects in a solution in Visual Studio)

However, I met some problems.

Whether I chose “g++(C-Project)” or “g++(…code-workspace)”, both of them can generate an executable.

After compiling, I used Launch to run the executable. Both “Launch(C-Project)” and “Launch(code-workspace)” failed.

I checked my “launch.json, tasks.json, and .code-workspace”, but found nothing.
Do I miss something? Or VSCode can't support “Launch in Multi-Root Workspace”?

![operate](https://user-images.githubusercontent.com/59817015/72681292-0e57e680-3afd-11ea-8743-4b0630a1f617.gif)

This is my “code-workspace”
![code-worksapce](https://user-images.githubusercontent.com/59817015/72681309-39dad100-3afd-11ea-8357-5eb5122c5412.png)

This is my “launch.json” in “C-Project/.vscode”
![launch](https://user-images.githubusercontent.com/59817015/72681328-6262cb00-3afd-11ea-8292-217651f103e5.png)

This is my “tasks.json” in “C-Project/.vscode”
![tasks](https://user-images.githubusercontent.com/59817015/72681333-6a226f80-3afd-11ea-990f-a35e8f264ea1.png)

This is my whole files.
[VSC-CPP-MINGW_MR.zip](https://github.com/microsoft/vscode-cpptools/files/4082684/VSC-CPP-MINGW_MR.zip)

**Comment by hwhsuguest** [comment]
When I launch the exe, it shows the message:

Unable to start debugging. Program path ‘D:\HW_VSC\VSC-SPP-MINGW_MR\C-Project\test1.exe’ is missing or invalid.
GDB failed with message: “D:\HW_VSC\VSC-SPP-MINGW_MR\C-Project\test1.exe”: not in executable format: File format not recognized.
This may occur if the process’s executable was changed after the process was started, such as when installing an update. Try re-launching the application or restarting the machine.

![message](https://user-images.githubusercontent.com/59817015/72699933-4571da80-3b85-11ea-9c8c-c587e0178738.png)

**Comment by pieandcakes** [comment]
@houwayhsu It looks like you are using a different gdb.exe than the one that matches your compiler. I noticed that your compiler comes from a `c:\\mingw-64` folder but your debugger is  in `c:\\mingw\\`. 

I wonder if you are compiling 64bit but you are debugging 32bit.

**Comment by hwhsuguest** [comment]
@pieandcakes What do you mean? I checked my code again and again. I didn't find that I'm using compiler from "c:\\mingw-64".

**Comment by pieandcakes** [comment]
If you watch your first slide show, in the output window, it calls the compiler from that folder. @sean-mcmanus might be able to tell you how to change that.

**Comment by sean-mcmanus** [comment]
Can you just specify the full path to the correct g++ compiler? It looks like the wrong one is getting picked up on the path or something. I don't see how this is multi-root related.
