### ISSUE TITLE
False positive case of intelli-sense: 'this declaration has no storage class or type specifier'

### ISSUE THREAD

**Issue by windless0530** [microsoft/vscode-cpptools#4867]
**Type: LanguageService**

Usually the error 'this declaration has no storage class or type specifier' means some statement written outside functions. But here the intelli-sense of C/C++ extension reports it somewhere else, where there is no error when I compile it.

**Describe the bug**
- OS and Version: 10.15.2
- VS Code Version: 1.39.2
- C/C++ Extension Version: 0.26.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
1. See the picture below
False positive error squiggle:
![image](https://user-images.githubusercontent.com/4645959/72694386-c7570900-3b6f-11ea-96c1-ff4d552cf4fc.png)
Details information of the squiggle:
![image](https://user-images.githubusercontent.com/4645959/72694379-bdcda100-3b6f-11ea-9d19-1ee8038e6230.png)
Where the related class is declared, in 'ks/common_reco/model_retrieve/term_retriever.h'
![image](https://user-images.githubusercontent.com/4645959/72694440-f1103000-3b6f-11ea-93f6-fe7db447fc73.png)

**Expected behavior**
No error squiggles.

**Comment by Colengms** [comment]
Hi @windless0530 .  Thanks for reporting this.  Can you reduce this to segment of code we can use to reproduce the issue, and share that with us?  Thanks.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
