### ISSUE TITLE
possibility to set cpptools.activeConfigName from a different extension

### ISSUE THREAD

**Issue by aliaksei-siarhei** [microsoft/vscode-cpptools#4870]
Type: General

I'm trying to make an extension for VS Code and possibility to control activeConfigName would be highly useful.

So far I only found how to bring "Select configuration" dropdown on the screen:
`vscode.commands.executeCommand('C_Cpp.ConfigurationSelect')`

Is there any hack/possibility to select configuration without user interaction?

**Comment by sean-mcmanus** [comment]
The ConfigurationSelect command doesn't take an argument, so we'd need to add a command that takes an argument for the configuration to select (cpptools.activeConfigName is read only). I don't know of a workaround.

**Comment by aliaksei-siarhei** [comment]
@sean-mcmanus , thanks for the info!
I've submitted a PR to add `cpptools.setActiveConfigName` command. Please take a look at #4893

**Comment by sean-mcmanus** [comment]
cpptools.setActiveConfigName is available in our Insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders

**Comment by aliaksei-siarhei** [comment]
awesome! Works great)
Thanks for the help, will close the issue now.
