### ISSUE TITLE
Outline view does not show methods in nested structs/classes

### ISSUE THREAD

**Issue by allanleal** [microsoft/vscode-cpptools#4871]
Issue Type: <b>Bug</b>

Consider the following C++ class declaration using the pimpl idiom:

**Constant.hpp**

~~~c++
#pragma once

#include <memory>

class Constant
{
public:
    Constant();

    Constant(int val);

    int value();

    int square();

    int cube();

private:
    struct Impl;

    std::unique_ptr<Impl> pimpl;
};
~~~

and here its definition:

**Constant.cpp**

~~~c++
#include "Constant.hpp"

struct Constant::Impl
{
    int val;

    Impl(int val)
    : val(val)
    {}

    int square()
    {
        return val*val;
    }

    int cube()
    {
        return val*val*val;
    }
};

Constant::Constant()
: pimpl(new Impl(0))
{
}

Constant::Constant(int val)
: pimpl(new Impl(val))
{
}

int Constant::value()
{
    pimpl->val;
}

int Constant::square()
{
    pimpl->square();
}

int Constant::cube()
{
    pimpl->cube();
}
~~~

The Outline View for the file `Constant.cpp` does now show the methods/variables inside the nested structure `Constant::Impl`.

![image](https://user-images.githubusercontent.com/5825588/72781041-a00c4480-3c20-11ea-8822-0ab6a3aa9550.png)

Extension version: 0.26.3-insiders4
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-37-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2900)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (0.14GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @allanleal .  Thanks for reporting this.  It looks like the use of a scope in the struct declaration is not being handled properly.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0
