### ISSUE TITLE
How do I filter the header file search path?

### ISSUE THREAD

**Issue by huanghantao** [microsoft/vscode-cpptools#4872]
Now, I have an include folder in my workspace that holds my header files. When I compile the code, I need to install the workspace header under /usr/include. This will cause the vscode search to find two defined places. Here is my configuration:

```json
{
    "configurations": [{
        "name": "PHP",
        "includePath": [
            "${workspaceFolder}/**",
            "/usr/include/**",
        ],
}
```

I don't want to search for /usr/include/myproject.

**Comment by sean-mcmanus** [comment]
I don't fully understand. Can you remove the "**" from "/usr/include/" to stop it from being recursive includes? You could also try adding folders to files.exclude.

**Comment by huanghantao** [comment]
for example, it is file tree of my workspace:

```shell
tree swoole-src -L 1
swoole-src
|-- CMakeLists.txt
|-- CREDITS
|-- LICENSE
|-- Makefile
|-- config.m4
|-- include
|-- swoole_websocket_server.cc
```

I will install the `swoole-src/include` directory to `/usr/include/php/ext/swoole/include/`.

When I click on the header file jump, will show the two places, one is in my workspace, one is in `/usr/include/php/ext/swoole/include/`.

Here are the screenshots:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/22836925/72858999-69f0c280-3cfd-11ea-9ef3-8ef01364a2f3.png">

I just want to jump to the header file in the workspace(That's the first one in the screenshot).

**Comment by sean-mcmanus** [comment]
Yes, can you remove "/usr/include/**"? That should normally be pulled in via setting your compilerPath. Or you can you just use "/usr/include"? You may need to use the C/C++: Reset IntelliSense Database command after doing the change.

**Comment by huanghantao** [comment]
@sean-mcmanus I can't remove `"/usr/include/**"`, because there are other headers in there that I have to use.

**Comment by sean-mcmanus** [comment]
Can you replace it by "/usr/include/" or `"/usr/include/<otherPaths>"`? Otherwise, can you add `"/usr/include/php/ext/swoole/include"` to your files.exclude setting?

**Comment by huanghantao** [comment]
thanks, `files.exclude` is effective. But here comes another problem. There are two source files under the same folder, one can find the header file correctly, the other cannot.

It's screenshots:

<img width="283" alt="image" src="https://user-images.githubusercontent.com/22836925/72860611-4419ec80-3d02-11ea-817b-7102454235e5.png">

<img width="927" alt="image" src="https://user-images.githubusercontent.com/22836925/72860724-ab37a100-3d02-11ea-91fc-905d08722e43.png">

<img width="715" alt="image" src="https://user-images.githubusercontent.com/22836925/72860669-79263f00-3d02-11ea-90fc-ea97f28a9a5a.png">

**Comment by sean-mcmanus** [comment]
That is odd. Can you run the C/C++: Log Diagnostics command with both files active and compare the output of the "Includes" section? The recursive includes feature (i.e. "**") could cause different include paths to be used if the same "server.h" exists at different locations (since the ordering not deterministic) -- adding `"${workspaceFolder}/swoole-src/include"` as the first value in includePath could fix that.

**Comment by huanghantao** [comment]
I reopened the vscode and the problem was solved. thanks!
