### ISSUE TITLE
feature request: recursive expansion of macros

### ISSUE THREAD

**Issue by lattice0** [microsoft/vscode-cpptools#4875]
When a macro expands to another macro, this plugin won't expand it further, so I end up having to search for the other macros.

**Comment by sean-mcmanus** [comment]
Can you provide a specific example? We do some expansion, but there might be cases that aren't expanded or some bug may be occurring. This is what I'm seeing:

![image](https://user-images.githubusercontent.com/19859882/72851800-7de6e680-3c61-11ea-8809-c40ba14bbd7f.png)

**Comment by lattice0** [comment]
@sean-mcmanus this example: https://github.com/ambrop72/aipstack/blob/master/src/aipstack/ip/IpStack.h#L136

I'm trying to read this code but there like 5 to 10 macro calls hidden in this one macro call. The macro expansion never worked for me recursively, it always showed another other macro for me, so I guessed it didn't have this feature.

**Comment by sean-mcmanus** [comment]
What are you seeing exactly? I'm seeing...

![image](https://user-images.githubusercontent.com/19859882/72852960-031fca80-3c65-11ea-8e3f-82ead2af5f95.png)

You're getting different results? What OS are you on? Have you changed any settings?

**Comment by lattice0** [comment]
@sean-mcmanus I get 

`AIPSTACK_AS_MAP(AIPSTACK_USE_TYPE, AIPSTACK_AS_MAP_DELIMITER_NONE, Arg, (Params, ProtocolServicesList))`

which are bunch of other macros.

I'm on debian9.

Just to be sure I opened a completely new debian9 VM, installed VSCode and then this CPP extension, did no configuraions. Opened the AipStack repo and it still expanded to macros, not to your output.

**Comment by sean-mcmanus** [comment]
Okay, I remember now -- this is a duplicate, see https://github.com/microsoft/vscode-cpptools/issues/3579#issuecomment-489224943 .

**Comment by sean-mcmanus** [comment]
A fix is available with 1.14.1 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.1
