### ISSUE TITLE
debug output and xterm on Linux?

### ISSUE THREAD

**Issue by rorywalsh** [microsoft/vscode-cpptools#488]
It seem the only way to see any program debug info output is through the floating xterm window that launches with the debug session. Setting  "externalConsole": false, doesn't seem to make a difference. Is this something that will looked into in the future?

**Comment by pieandcakes** [comment]
@rorywalsh on Linux we currently need the window to be able to support displaying the output of the debuggee and gdb. we have an issue in our backlog to look at integrating the debugger terminal within VS Code #35.

**Comment by rorywalsh** [comment]
Thanks.
