### ISSUE TITLE
No stdout from remote target when debugging over WSL

### ISSUE THREAD

**Issue by Fuzzy67** [microsoft/vscode-cpptools#4887]
Type: Debugger
gdb

*No program output from stdout visible*
- OS and Version: W10/1809 with WSL Debian/Gnu
- VS Code Version:1.41.1
- C/C++ Extension Version: 0.26.3
- Remote Dvelopment Extension Version: 0.19.0

We debug a small extern linux target via the WSL1 installed on an W10 desktop PC using the Remote Development extension. So the WSL runs only in background.  Everything works well. Except I can't see any programm output on any terminal in vscode. Is there any setting missing. Here is our launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "IPEmotionRT-Debug",
            "preLaunchTask": "PrepareRTDebug",
            "type": "cppdbg",
            "request": "launch",
            "MIMode": "gdb",
            "miDebuggerPath": "/home/fabrice/embeddedLinux/Develop/x86_build/host/usr/bin/x86_64-buildroot-linux-gnu-gdb",
            "miDebuggerArgs": "set print pretty on set print object on set print static-members on set print vtbl on set print demangle on set demangle-style gnu-v3set auto-load safe-path / -ix ${workspaceFolder}/build/Debug/.gdbinit",
            "program": "${workspaceFolder}/build/Debug/IPEmotionRT",
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "externalConsole": false,
            "logging": {
                "trace": true,
                "engineLogging": true
            },
            "targetArchitecture": "x86_64",
            "setupCommands": [
                {
                    "description": "Debugging program",
                    "text": "file ${workspaceFolder}/build/Debug/IPEmotionRT",
                    "ignoreFailures": true
                },
                {
                    "description": "Enable pretty printing",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Stop at main",
                    "text": "break main()",
                    "ignoreFailures": true
                },
                {
                    "description": "Connect to remote debugger",
                    "text": "target remote | sshpass -p root ssh -T -oStrictHostKeyChecking=no root@192.168.236.1 gdbserver - /usr/bin/IPEmotionRT",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

Maybe the tasks.json is from interest too 

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "PrepareRTDebug",
            "detail": "Kill a unnecessary processes on target device (IPEmotionRT, IPEwatch) and restart the ipectrld process",
            "type": "shell",
            "command": "sshpass -p root rsync ./.scripts/prepare.sh root@192.168.236.1:/media/MEA/prepDebug.sh && sshpass -p root ssh root@192.168.236.1 '/media/MEA/prepDebug.sh'",
            "dependsOn" :["DisableWatchdog"]
        },
        {
            "label": "DisableWatchdog",
            "detail": "Disable the watchdog on target device using i2ctools ic2get/i2cset called in script file \"disableWatchdog.sh\"",
            "type": "shell",
            "command": "sshpass -p root rsync ./.scripts/disableWatchdog.sh root@192.168.236.1:/media/MEA/disableWatchdog.sh && sshpass -p root ssh root@192.168.236.1 '/media/MEA/disableWatchdog.sh'",
            "problemMatcher": [
                "$eslint-compact"
            ]
        },
        {
            "label": "EnableWatchdog",
            "detail": "Enable the watchdog on target device using i2ctools ic2get/i2cset called in script file \"enableWatchdog.sh\"",
            "type": "shell",
            "command": "sshpass -p root rsync ./.scripts/enableWatchdog.sh root@192.168.236.1:/media/MEA/enableWatchdog.sh && sshpass -p root ssh root@192.168.236.1 '/media/MEA/enableWatchdog.sh'",
            "problemMatcher": [
                "$eslint-compact"
            ]
        }
    ]
}

The called script on the target just kills some running processes. That shouldn't have an impact

**Comment by pieandcakes** [comment]
If you enable `engineLogging`, does `gdb` report that output? that would be the only way we would be getting your program's output in a remote scenario.

**Comment by Fuzzy67** [comment]
> If you enable `engineLogging`, does `gdb` report that output? that would be the only way we would be getting your program's output in a remote scenario.

As you can see in our launch.json, engineLoggin is already enabled. And i see nothing in gdb log.
If this is not possible in the moment. Are there any plans to support it in the feature ?

**Comment by pieandcakes** [comment]
@Fuzzy67 I don't see an engine log in your original issue text. I don't know how we would report it since our communication is with `gdb` and you are saying `gdb` doesn't show any of the output.

**Comment by Fuzzy67** [comment]
> @Fuzzy67 I don't see an engine log in your original issue text. I don't know how we would report it since our communication is with `gdb` and you are saying `gdb` doesn't show any of the output.

In my original post of the launch.json you can find this :

"logging": {
"trace": true,
"engineLogging": true
},

Isn't this what you mean ? Anyway ! My statement that I don't see anything related only to the output of the program to be debugged. Not on the gdb itself.

No idea what is different today. But today i can see the output of the programm. However, they are difficult to discover because so many issues come from the gdb itself. It is possible to separate these two outputs in some way ?

**Comment by pieandcakes** [comment]
The terminal output should be in the Terminal tab under `cppdbg: <program name>` where `<program name>` is the name of your program. 

I tested with a basic printf/scanf app and it shows up. 

When you enable enginelogging, the communication between our debugadapter and the debugger will show up in the `Debug Console` and that was what I was looking for. If `externalConsole` is set to false, your output will show up in `Terminal` and if it is `true` you should see it in a pop up window.

**Comment by lakehu** [comment]
Mannul start gdbserver on the target Linux tty could get it done. Otherwise, the debugged process's stdout is inside gdb<-> gdbserver tcp communication for this case.
