### ISSUE TITLE
Incorrect integration with clang-format 

### ISSUE THREAD

**Issue by yuyoyuppe** [microsoft/vscode-cpptools#489]
clang-format accepts `-assume-filename=` argument which, quoting the man, does the following:

> When reading from stdin, clang-format assumes this filename to look for a style config file (with
> -style=file) and to determine the language.

`vscode-cpptools` indeed uses its stdin, while supplying these arguments:
`-style=file -fallback-style=LLVM -sort-includes=0 -assume-filename=/tmp/test.cpp`

Note that the value of `-assume-filename` is incorrect: we get a path to the source file instead of a style config. Could you please fix that as well as add a setting to specify overriding path to the style config? Something like `"C_Cpp.clang_format_style_config_path"`.

Thanks.

**Comment by yuyoyuppe** [comment]
As a workaround on Linux, you can replace clang-format at `~/.vscode-insiders/extensions/ms-vscode.cpptools-0.10.1/LLVM/bin/clang-format` with a perl script:
```perl
#!/usr/bin/perl
$style_file = ...
print `clang-format -style=file -assume-filename=$style_file`;
```

**Comment by sean-mcmanus** [comment]
The clang-format docs are not worded correctly. -assume-filename is supposed to take the name of the file being formatted (when the text of the file is passed to clang-format from stdin). Using it enables header sorting to work correctly with file.h on top of file.c. When style=file, the style document for the current directory is .clang-format or _clang-format. You can see another example usage at https://github.com/LiquidHelium/atom-clang-format/issues/34 .

**Comment by yuyoyuppe** [comment]
Oh, my bad, I've actually had .clang-format file over two dirs up and tested this workaround by moving it even further up the tree. clang-format will actually scan [up until the drive root path](https://github.com/llvm-mirror/clang/blob/release_39/lib/Format/Format.cpp#L1728), which is quite unexpected, but nevertheless stated in the same docs:

>  -style=<string>           - Coding style, currently supports:
>                                LLVM, Google, Chromium, Mozilla, WebKit.
>                              Use -style=file to load style configuration from
>                              .clang-format file located in one of the parent
>                              directories of the source file (or current
>                              directory for stdin).

Perhaps it would be better to implement some `-style-config-path` in clang-format which would override such behavior.

Thanks.
