### ISSUE TITLE
Alternative way for providing debug configuration snippets

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cpptools#4891]
Type: Debugger

Because of the implementation (src/debugger/extension.ts, line 129 - 136), the intellisense for the snippets will be shown
1) For all launch.json, at all locations
2) Under multi-root mode, not at all for workspace configuration file (.code-workspace).

**Comment by pieandcakes** [comment]
@WardenGnaw It is [this](https://github.com/microsoft/vscode-cpptools/blob/2b1054bf41a401da10ddc37d3b95168cf178c5d9/Extension/src/Debugger/extension.ts#L129) line. Do you know why we need the actual launch.json file?

**Comment by WardenGnaw** [comment]
```
registerCompletionItemProvider(selector: DocumentSelector, provider: CompletionItemProvider, ...triggerCharacters: string[]): Disposable
```
We need to provide a document selector when we register the completion item provider for launch.json. This hooks into the `Add Configurations...` button displayed.

**Comment by xisui-MSFT** [comment]
There are two parts for providing a debug config https://vscode.readthedocs.io/en/latest/extensions/example-debuggers/, one is provideDebugConfigurations which provide the initial settings (or specifying initialConfigurations in package.json), and the other is to specify configurationSnippets, which provides the autocomplete stuff. Instead of the "standard" second part, you used a way to just insert to anywhere in the document as long as it's a launch.json file and intellisense pops up. So I doubt the problem you mentioned is the same.

While it's unfortunate that cpptools can't really use the package.json ways since there are some os dependent items, it looks like function provideCompletionItems does pass in a position argument. Can you change the function to check if it's triggered at a proper position?

For multi-root workspace file, it remains to be tested. But adding a document select for .code-workspace file would probably work?
