### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Angel215i** [microsoft/vscode-cpptools#4897]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `0.26.3`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by sean-mcmanus** [comment]
What is this about?

**Comment by Angel215i** [comment]
I just purchased an SKR1.4 Turbo mother board for my CR10Mini 3D printer
and am having issues with VSCode. When i try to compile i get the following
(Tasks not found)
It worked before but now for some reason i cannot stop the tasks not found
i cannot clean it or anything i uninstalled vscode reinstalled it, deleted
out the marlin folder redownloaded it tried again. Watched videos about
performing tasks but it doesn't help with what I'm trying to do with
updating the 3D Printer Firmware

**Comment by Angel215i** [comment]
I have no idea what to do please take control to help resolve this.  I apologize for my illiteracy

**Comment by bobbrow** [comment]
> :warning: We have written the needed data into your clipboard. Please paste! :warning: 

We will close this issue and you should open a new one with VS Code the same way you did as before, except this time, please also paste (<kbd>CTL</kbd>+<kbd>V</kbd>) the logs that are copied to your clipboard.

**Comment by Angel215i** [comment]
I don't even know how i did that before im not coding literate and have no
experience except from what was set up for me before.
