### ISSUE TITLE
c++03 mode bug with std::pair

### ISSUE THREAD

**Issue by oktonion** [microsoft/vscode-cpptools#4899]
**Type: LanguageService**

**Describe the bug**
- Windows 10
- VS Code Version : 1.41.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): none

**In c++03 mode** intellisense is going nuts about `std::pair` default constructor:

**To Reproduce**

1. Install c++ extension
2. Create .cpp file with `std::pair` in it
3. Set c++ extension to c++03 mode

**Expected behavior**
There should be no error message. `std::pair` default constructor in c++03 is totally ok.

**Screenshots**
![c++bug](https://user-images.githubusercontent.com/27406278/73126883-54afb880-3fc9-11ea-9f88-0f6f72ec25d0.jpg)

**Comment by sean-mcmanus** [comment]
What compiler and header libraries are you using to compile? It appears that you're using cl.exe with a pair header that will only compile with /std:c++14 or greater. Using the C/C++: Log Diagnostics command can show you more info on the headers that are being picked up.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
