### ISSUE TITLE
[0.10.0] Cpptools extension is consuming too much disk IO.

### ISSUE THREAD

**Issue by sunzhec2702** [microsoft/vscode-cpptools#490]
Hi,

I am using vs code in Ubuntu in a virtual machine. Recently I upgraded the cpptools extension to 0.10.0. 
This version is consuming too much I/O from command iotop. And of course, the vs code hang and I have to kill the extension.

After go back to 0.9.3, this issue disappears.

**Comment by pieandcakes** [comment]
@sunzhec2702 Can you try 0.10.1? The language team made some fixes that might resolve your issue.

**Comment by sunzhec2702** [comment]
@pieandcakes I've tried 0.10.1 and I cannot repro this issue :) 
Close this issue.
