### ISSUE TITLE
Failure when inspecting data of a variable during debug for a variable next to asterisk 

### ISSUE THREAD

**Issue by allanleal** [microsoft/vscode-cpptools#4900]
Issue Type: <b>Bug</b>

Issue Type: <b>Bug</b>

The following screencast shows the problem. I have to insert at least one space between `*` and vector `y` to be able to inspect its data while hovering it.

![Peek 2020-01-27 13-04](https://user-images.githubusercontent.com/5825588/73182272-0c9fab80-4119-11ea-8e3b-a31d1c30223b.gif)

Extension version: 0.26.3
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-36-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (20 x 1199)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|62.83GB (4.11GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

Extension version: 0.26.3
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-26-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (20 x 1200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 0|
|Memory (System)|62.74GB (48.48GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pieandcakes** [comment]
@allanleal Can you enable [engineLogging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_logging-for-mi-debuggers) and paste what it is sending `gdb`? In this case is `*` an arithmetic operation or for a pointer?

**Comment by allanleal** [comment]
@pieandcakes `*` is the multiplication operator in this case.

Here is what I get when hovering `x` in `A*x`:

~~~
1: (51428) ->(gdb)
1: (51428) 3572: elapsed time 1
1: (52233) <-3573-var-create - * "A*x"
1: (52262) ->3573^error,msg="No symbol \"operator*\" in current context."
~~~

The desired behavior would be:

~~~
1: (52262) ->(gdb)
1: (52263) 3573: elapsed time 29
1: (137847) <-3574-var-create - * "x"
1: (137849) ->3574^done,name="var1147",numchild="0",value="{...}",type="Eigen::Ref<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::InnerStride<1> >",thread-id="1",dynamic="1",has_more="1"
~~~

which is what I get if I go there in the code and enter a space between `*` and `x` as in `A* x`.

**Comment by pieandcakes** [comment]
@allanleal Unfortunately I think the hovered expression is provided by VS Code. Let me investigate and, if need be, I'll file an issue with them.
