### ISSUE TITLE
Undefined identifiers in librairies

### ISSUE THREAD

**Issue by flobsh** [microsoft/vscode-cpptools#4908]
- OS: Linux 5.4.13-3 Manjaro 18.1.5
- VS Code (OSS): 1.41.1
- C/C++ Extension: 0.26.3

Hi,

I have an issue using VS Code with the C/C++ extension. Some identifiers are not recognized by Intellisense, although my includePath in ```c_cpp_properties.json``` seems fine.

For instance here I am trying to display the current time with ```time()``` from the ```ctime``` library. VS Code tells me that the time identifier is undefined:

```
#include <iostream>
#include <ctime>

using namespace std;

int main()
{
    cout << time(nullptr) << endl; //--> "time" identifier is undefined
}
```

Here is my c_cpp_properties.json file:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/linux",
                "/usr/include/c++/9.2.0/tr1"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

There is a ```ctime``` file at``` /usr/include/c++/9.2.0/tr1/``` as well as at ```/usr/include/c++/9.2.0/``` but changing the includePath to the latter doesn't change anything.

Thanks for your help,

FB.

**Comment by sean-mcmanus** [comment]
Can you remove the 2 "/usr/include" paths from the includePath and then run the C/C++: Log Diagnostics command to see what system includes are getting used from /usr/bin/gcc?

**Comment by flobsh** [comment]
Sure, here is the output of the C/C++: Log Diagnostics command when I remove the two include paths:
```
-------- Diagnostics - 29/01/2020 à 21:07:32
Version: 0.26.3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/florianb/Public/Test/main.cpp ]:
    /home/florianb/Public/Test/main.cpp
Translation Unit Configurations:
[ /home/florianb/Public/Test/main.cpp ]:
    Process ID: 1593
    Memory Usage: 69 MB
    Includes:
        /usr/include/c++/9.2.0
        /usr/include/c++/9.2.0/x86_64-pc-linux-gnu
        /usr/local/include
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=80100
Total Memory Usage: 69 MB
```

In the ```main.cpp``` file it now shows an error message asking me to include both of the include paths that were previously here.

**Comment by flobsh** [comment]
The error messages are:
```#include errors detected. Please update your includePath. Error squiggles are disabled for this translation unit"``` ;
```Can't open source file "stddef.h" (dependancy of "iostream")```

(Sorry if the messages are inaccurate, I translated them from french)

**Comment by sean-mcmanus** [comment]
Your logging is missing the "Compiler Path: " info after "Memory Usage", which implies that /usr/bin/gcc was failed to be queried for system includes/defines. I'm not sure how the "/usr/include/c++/9.2.0" got on your includePath (which is missing lots of other normal gcc system paths) -- and the --gnu_version appears to be our default 80100 fallback. You might see more compiler querying (and fallback) failure messages in your logging if you set C_Cpp.loggingLevel to "Debug" and view the C/C++ output panel.

I believe you should have stddef.h at `/usr/lib/gcc/x86_64-linux-gnu/?/include` where ? is some version.

Do you have gcc and g++ installed? You may need to installed a newer version like g++-8 and gcc-8.

Do you see more paths when you run `/usr/bin/gcc -Wp,-v -E -x c++ /dev/null` ?

**Comment by flobsh** [comment]
Thanks for your feedback.

I set the C_Cpp.loggingLevel to "Debug" but I got the same output as before.

I indeed have stddef.h at ```/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include```.

I have gcc and g++ installed, both at version 9.2.0 (I checked with the commands ```gcc --version``` and ```g++ --version```).

Here is the output of ```/usr/bin/gcc -Wp,-v -E -x c++ /dev/null```:
```
ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0
 /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/x86_64-pc-linux-gnu
 /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../include/c++/9.2.0/backward
 /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include
 /usr/local/include
 /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed
 /usr/include
End of search list.
# 1 "/dev/null"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "/dev/null"
```

There are indeed a few more include paths...

**Comment by sean-mcmanus** [comment]
The output from setting C_Cpp.loggingLevel to "Debug" should not be "the same" because it goes to the "C/C++" pane and not the "C/C++: Diagnostics" pane. You should see some message like `Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/gcc'`.

Could your gcc be outputting non-English output when we query it? We fail to parse the output in that case.

The "more include paths" are correct and in the correct order...so you could manually specify those and set the compilerPath to "", but you'll probably hit other errors due to the system defines not being set correctly (obtained via the additional -dD flag).

**Comment by flobsh** [comment]
Alright yes I didn't know it was displayed on a different pane. I have the message ```Attempting to get defaults from compiler in "compilerPath" property: '/usr/bin/gcc'``` and then it says that it failed to retrieve the include paths and the system defines.

Yes my output is in french so the issue surely comes from there. I assume I can change my ```LANG``` environment variable to change this behaviour, but I'd like to keep the output of my commands in french.

However I assume I can copy the include paths in the C/C++ extension paramters as well as the system defines in the default defines of the extension ?

**Comment by sean-mcmanus** [comment]
Yeah, we tried to fix this bug (see the previous thread at https://github.com/microsoft/vscode-cpptools/issues/4542) by setting LC_ALL to "C" before launching gcc, but the fix didn't work. We've been able to get non-ENU languages to be set in the OS, but we haven't been able to get gcc to output the non-English strings (i.e. the lack of a repro makes it hard to verify if our fixes work).

Yeah, you should be able to set the system includes/defines manually.

**Comment by ijash** [comment]
i think i have similar issue

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
