### ISSUE TITLE
Unable to launcher debugger

### ISSUE THREAD

**Issue by h135558** [microsoft/vscode-cpptools#4914]
Hi

When I try to launch gdb via f5 I get this error:

![error](https://user-images.githubusercontent.com/25818006/73451266-87f69c80-4367-11ea-823e-0e6fe22d6793.png)

The program compiles and works just fine, but debugging is not working.

launch.json
![launch](https://user-images.githubusercontent.com/25818006/73451906-f38d3980-4368-11ea-9bbe-db28eb6ab5e7.png)

tasks.json
![tasks](https://user-images.githubusercontent.com/25818006/73451994-3d761f80-4369-11ea-9b66-f019a244b06c.png)

c_cpp_properties.json
![c_cpp_properties](https://user-images.githubusercontent.com/25818006/73452116-7c0bda00-4369-11ea-9b82-8aa2c386bf86.png)

settings.json
![settings](https://user-images.githubusercontent.com/25818006/73452194-abbae200-4369-11ea-8618-d77bc6feda8e.png)

output log
![output](https://user-images.githubusercontent.com/25818006/73452390-1a983b00-436a-11ea-8381-b0e3b9d6ff44.png)

terminal
![terminal](https://user-images.githubusercontent.com/25818006/73452466-41ef0800-436a-11ea-8501-4334ccb3c803.png)

It looks like the command issued in the terminal fails, but I cannot figure out why.

bash: c:UsersAdministrator.vscodeextensionsms-vscode.cpptools-0.26.3debugAdaptersbinWindowsDebugLauncher.exe: command not found

**Comment by pieandcakes** [comment]
which version of VS Code are you using? Its strange that its stripping the path separators in the command. I can't duplicate this with the latest VS Code release and extension.

**Comment by h135558** [comment]
Hello again, sorry for the delay with answering.

I'm using VS Code version 1.41.1 and the C/C++ 0.26.3 plugin by Microsoft.

Debugging worked just fine for me up until recently. I wonder if maybe an update broke something.

**Comment by h135558** [comment]
I got it working again by removing anything I could find related to VS Code in my AppData folder.

**Comment by pieandcakes** [comment]
Sounds like one of the downloads was corrupted. Thanks for letting us know.
