### ISSUE TITLE
Launch debug session from terminal: "code-gdb --args ./mytool --foo"

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode-cpptools#4916]
Type: Debugger

I often have the scenario that I have a terminal open where I'm running and testing a program that I'm developing. Wouldn't it be awesome if I could start a VS Code debug session directly from the terminal simply by prefixing my command with something like `code-gdb`?

The time it takes me to setup a real debug config in VS Code is insane, and often it's very specific to a certain command line -- I wouldn't commit that to source control. Starting debugging from the terminal eliminates this friction and would be a big productivity boost for me.

**Comment by pieandcakes** [comment]
@letmaik that would need to be provided by VS Code to provide an option to launch VS Code and start the debugger. Can you file an issue on [their](https://github.com/microsoft/vscode/issues) Github?
