### ISSUE TITLE
Can we have a setting field to turn off "search include paths"

### ISSUE THREAD

**Issue by chaopeng** [microsoft/vscode-cpptools#492]
Can we have a setting field to turn off "search include paths"? 

Currently I am working on chromium code base with vscode and vscode-cpptools. It works great even on laptop. But on laptop "search include paths" consuming too much battery and it is useless on chromium code base.

**Comment by bobbrow** [comment]
We will add this soon.  This is covered by #374.  If you need an immediate fix, you can work around the issue by manually editing this extension file:

```
Windows: %userprofile%\.vscode\extensions\ms-vscode.cpptools-0.10.1\out\src\LanguageServer\C_Cpp_ConfigurationProperties.js
Linux/Mac: ~/.vscode/extensions/ms-vscode.cpptools-0.10.1/out/src/LanguageServer/C_Cpp_ConfigurationProperties.js
```

lines 157 and 160 insert ${workspaceRoot} into the include path array before sending it over to the language server extension.  Remove these lines and it should solve your problem until we get a proper setting added to the extension.

**Comment by chaopeng** [comment]
In 0.10.2, `"C_Cpp.addWorkspaceRootToIncludePath": false` works for me. Thank you.

**Comment by bobbrow** [comment]
great to hear!
