### ISSUE TITLE
IntelliSense does not detect type of member in class nested in template class

### ISSUE THREAD

**Issue by zwuis** [microsoft/vscode-cpptools#4920]
I'm sorry for my poor English.

Type these codes:
```cpp
template<typename T>
class a_class {
    struct a_struct {
        int num;
    } *p;
    public a_class() {
        p = new a_struct;
        ++(p->num);
    }
};
```
Then move mouse to `num` in line 8.
It will show `<unknown> a_class<T>::a_struct::num`.

Extension version: 0.26.3
VS Code version: Code - Insiders 1.42.0-insider (705f01577dd37d6f17eaa683ab89b0c392fa1a7c, 2020-02-03T14:03:06.282Z)
OS version: Windows_NT ia32 10.0.18363

**Comment by Colengms** [comment]
Hi @zwuis .  Thanks for reporting this.  I was able to repro this in Visual Studio.  (The C/C++ Extension for VS Code shares common code with Visual Studio, for IntelliSense).

I've opened the following bug against Visual Studio: https://developercommunity.visualstudio.com/content/problem/906115/intellisense-does-not-detect-type-of-member-in-cla.html

**Comment by sean-mcmanus** [comment]
VS is treating this as "by design" and relying on the "template IntelliSense" feature which is being tracked by https://github.com/microsoft/vscode-cpptools/issues/1946 .
