### ISSUE TITLE
Can't debug on win10  (LLDB) 

### ISSUE THREAD

**Issue by oridong** [microsoft/vscode-cpptools#4922]
Type: Debugger

**Describe the bug**
- OS and Version: win10pro  1709   internal 16299.15
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
LLVM 9.0.0-win64   
MingW 8.1.0 release

when I press F5, it starts but not start the application ,and always keep that.
I can not pause it and only stop it on the debug bar.
but on vscode TERMINAL panel , type "lldb main.exe" I can run it as using GDB.

The TERMINAL  Console output:

PS D:\00_ws\CMake-MinGWFile-GCC> & 'c:\Users\d\.vscode\extensions\ms-vscode.cpptools-0.26.3\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-fuzl4dtv.0q2' '--stdout=Microsoft-MIEngine-Out-1wjhtezp.r5f' '--stderr=Microsoft-MIEngine-Error-npxdjlkt.ddh' '--pid=Microsoft-MIEngine-Pid-u5mz34py.cxf' '--dbgExe=D:/Include/LLVM/bin/lldb.exe' '--interpreter=mi'                 <force to stop>
PS D:\00_ws\CMake-MinGWFile-GCC>

Debug Console output:

--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (107) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'\r\n"},"seq":2}
1: (107) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (118) LaunchOptions  ExePath='d:\\00_ws\\CMake-MinGWFile-GCC\\main.exe'\r\n"},"seq":4}
1: (118) LaunchOptions  ExePath='d:\00_ws\CMake-MinGWFile-GCC\main.exe'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (118) LaunchOptions  WorkingDirectory='D:\\00_ws\\CMake-MinGWFile-GCC'\r\n"},"seq":6}
1: (118) LaunchOptions  WorkingDirectory='D:\00_ws\CMake-MinGWFile-GCC'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (118) LaunchOptions  ExeArguments='2&gt;CON 1&gt;CON &lt;CON'\r\n"},"seq":8}
1: (118) LaunchOptions  ExeArguments='2&gt;CON 1&gt;CON &lt;CON'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (118) LaunchOptions  MIMode='lldb'\r\n"},"seq":10}
1: (118) LaunchOptions  MIMode='lldb'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (119) LaunchOptions  MIDebuggerPath='D:/Include/LLVM/bin/lldb.exe'\r\n"},"seq":12}
1: (119) LaunchOptions  MIDebuggerPath='D:/Include/LLVM/bin/lldb.exe'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (119) LaunchOptions  WaitDynamicLibLoad='false'\r\n"},"seq":14}
1: (119) LaunchOptions  WaitDynamicLibLoad='false'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (119) LaunchOptions>\r\n"},"seq":16}
1: (119) LaunchOptions>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (119) LaunchOptions    <SetupCommands>\r\n"},"seq":18}
1: (119) LaunchOptions    <SetupCommands>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (119) LaunchOptions        <Command IgnoreFailures='true' Description='for gdb allign print'>-enable-pretty-printing</Command>\r\n"},"seq":20}
1: (119) LaunchOptions        <Command IgnoreFailures='true' Description='for gdb allign print'>-enable-pretty-printing</Command>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (119) LaunchOptions    </SetupCommands>\r\n"},"seq":22}
1: (119) LaunchOptions    </SetupCommands>
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (119) LaunchOptions</LocalLaunchOptions>\r\n"},"seq":24}
1: (119) LaunchOptions</LocalLaunchOptions>
--> C (runInTerminal-26): {"type":"request","command":"runInTerminal","arguments":{"kind":"integrated","title":"cppdbg: main.exe","cwd":"","args":["c:\\Users\\d\\.vscode\\extensions\\ms-vscode.cpptools-0.26.3\\debugAdapters\\bin\\WindowsDebugLauncher.exe","--stdin=Microsoft-MIEngine-In-fuzl4dtv.0q2","--stdout=Microsoft-MIEngine-Out-1wjhtezp.r5f","--stderr=Microsoft-MIEngine-Error-npxdjlkt.ddh","--pid=Microsoft-MIEngine-Pid-u5mz34py.cxf","--dbgExe=D:/Include/LLVM/bin/lldb.exe","--interpreter=mi"],"env":{}},"seq":26}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (178) Wait for connection completion.\r\n"},"seq":28}
1: (178) Wait for connection completion.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
launch.json
{
   //https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++", 
            "type": "cppdbg", 
            "request": "launch",  
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,// true
            "cwd": "${workspaceFolder}", // ${workspaceFolder} ${fileDirname}
            "environment": [],// 
            "externalConsole": false,//false true 
            "MIMode": "lldb", //   gdb   lldb 
            "miDebuggerPath":  "D:/Include/LLVM/bin/lldb.exe" , 
            "setupCommands": [
                {
                    "description": "for gdb allign print",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "compile c++ by clang++" ,
            "logging": { "engineLogging": true, "trace": true, "traceResponse": true }
        }
    ]
}
task.json
{
    "version": "2.0.0",
    "tasks": [
      {
        "label": "compile c++ by clang++",
        "type": "shell",
        "command": "clang++.exe",
        "args": [
            "${file}",
            "-o", 
            "${fileDirname}/${fileBasenameNoExtension}.exe",
            "-g", 
            "-Wall",
            "-static-libgcc", 
            "--target=x86_64-w64-mingw", 
            "-std=c++17", 
        ], 
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]
}
    

Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment]
The protocol used for the Debug Adapter with GDB/LLDB is MI which is the machine interface. It is trying to run `D:/Include/LLVM/bin/lldb.exe --interpreter=mi` but lldb does not have the machine interface built into it, it requires `lldb-mi`. 

You will need to have `miDebuggerPath` point to `lldb-mi.exe`

**Comment by WardenGnaw** [comment]
Inactive issue. Please create another issue if you have any other questions.
