### ISSUE TITLE
no TM scope for variables

### ISSUE THREAD

**Issue by geromueller** [microsoft/vscode-cpptools#4924]
Version 0.26.3

There are no TM scopes for variables. Neither local, global or class members.

**Comment by Colengms** [comment]
Hi @geromueller .  VS Code provides syntactic/lexical colorization based on TextMate grammar.  The TextMate grammar for C/C++ is contributed to VS Code by @Jeff-hykin .  That repo is [here](https://github.com/jeff-hykin/cpp-textmate-grammar).

The C/C++ Extension provides semantic colorization as a layer on top of the VS Code's TM-based syntactic colorization.  The scopes used to color semantic tokens are documented [here](https://code.visualstudio.com/docs/cpp/colorization-cpp).  This includes colorization for local and global variables, and class members, where used.  Whereas TextMate colorization only applies where they are declared, where they can be detected syntactically.  Although semantic tokens are mapped to TextMate scopes for the purpose of colorizing, you will not see information for them if using the `Developer: Inspect TM Scopes' command.

Does this address your issue?  Or, are you seeing a problem with enhancedColorization?

**Comment by jeff-hykin** [comment]
Here's the issue you're looking for @geromueller https://github.com/jeff-hykin/cpp-textmate-grammar/issues/81

**Comment by geromueller** [comment]
Thank you @Colengms and @jeff-hykin  for the quick answers!
