### ISSUE TITLE
sourceFileMap sometimes doesn't work in containers

### ISSUE THREAD

**Issue by jiajudu** [microsoft/vscode-cpptools#4925]
Type: Debugger

**Describe the bug**
- OS and Version: MacOS 10.15.3, attatch to container Ubuntu 19.10
- VS Code Version: 1.14.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is: sourceFileMap doesn't work for libstdc++ codes but work for glibc codes.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Start a ubuntu:19.10 container
```
docker run --rm -it ubuntu:19.10 bash
```
2. Attacth to the container, and open `/root`.
3. Install cpptools and some dependencies
```
apt update
apt install gcc g++ gdb glibc-source libstdc++6-9-dbg gcc-9-source
cd /usr/src/gcc-9
tar xvf  gcc-9.2.0.tar.xz
cd /usr/src/glibc
tar xvf glibc-2.30.tar.xz
```
4. Add souce file and configs
a.cpp
```
#include <memory>
using namespace std;
class A: enable_shared_from_this<A> {
public:
    A() {
        shared_ptr<A> p = shared_from_this();
    }
};
int main() {
    A a;
    return 0;
}
```
launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb",
            "sourceFileMap": {
                "/build/glibc-4WA41p": "/usr/src/glibc",
                "/build/gcc-9-NSfpi_/gcc-9-9.2.1/src": "/usr/src/gcc-9/gcc-9.2.0"
            }
        }
    ]
}
```
tasks.json
```
{
    "tasks": [
        {
            "type": "shell",
            "label": "g++ build active file",
            "command": "g++ a.cpp -g -o a",
        }
    ],
    "version": "2.0.0"
}
```
5. Hit F5 and the program will throw an exception. In the call stack, the 1-2 frames starts with `libc.so.6` and the 3-6 frames starts with `libstdc++.so.6`. I can open the source file by clicking 1-2 frames, but get errors when clicking 3-6 frames:
```
Unable to open 'vterminate.cc': Unable to read file (Error: File not found (vscode-remote://attached-container+7b22636f6e7461696e65724e616d65223a22626c69737366756c5f7468617270227d/build/gcc-9-NSfpi_/gcc-9-9.2.1/src/libstdc++-v3/libsupc++/vterminate.cc)).
```

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by mschuckmann** [comment]
I'm seeing the same basic problem when attempting to do remote debugging (of an embedded device)  when running VSCode attached to a docker container.

**Comment by NapalmCodes** [comment]
Same situation here with a C# application unable to find code files to debug against.  VSCode just throws this:

```Unable to open 'WeatherForecastController.cs': Unable to read file 'vscode-remote://wsl+ubuntu/app/Controllers/WeatherForecastController.cs' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu/app/Controllers/WeatherForecastController.cs').```

The app directory is inside my container but not my code folders.  Changing sourceFileMap values in either the key or value in launch.json make no difference.

**Comment by jiajudu** [comment]
is there any plan to fix this?

**Comment by sean-mcmanus** [comment]
@jiajudu Not currently, but we could re-open this.

**Comment by davidwin** [comment]
I also see that `sourceFileMap` is ignored in Remote SSH setups, and probably has been for a while. Is this known to work in general so there is a problem with out configurations, or is it an unsupported scenario? I want to map from one remote path to another remote, but being able to map remote to local would sometimes be handy.

I have tried prefixing the paths with `vscode-remote://ssh-remote+...`, but that doesn't seem to work either. I have also tried with `MIMode` being both `gdb` and `llvm` with the same result. Current plugin version 1.2.2 running on Windows connected to a Linux target.

**Comment by nsgundy** [comment]
Also just stumbled into this:
```
Unable to open 'gtest.h': Unable to read file 'vscode-remote://attached-container+7b22636f6e7461696e65724e616d65223a222f7369746172615f646576656e76227d/root/sdk/gmock-1.7.0/gtest/include/gtest/gtest.h' (NoPermissions (FileSystemError): Error: EACCES: permission denied, stat '/root/sdk/gmock-1.7.0/gtest/include/gtest/gtest.h').
```

With
```json
    "sourceFileMap": {
      "/root/sdk/gmock-1.7.0/gtest/include/gtest/": "/usr/local/include/gtest/"
    },
```
