### ISSUE TITLE
Run command starts Text Editor Settings

### ISSUE THREAD

**Issue by Baky9912** [microsoft/vscode-cpptools#4927]
Windows 10, recently started using VSC. I use mingw compiler and everything works fine if I compile and run with f6 and set flags with f7 but if I press run (or f5/ctrl f5) I get asked do I want c++(gdb/llldb), c++(windows), node.js or more. After I select either of the c++ options it opens a new window with Settings. It is probably a mistake on my end. I want to debug a c++ programme.

**Comment by sean-mcmanus** [comment]
What do you mean it opens a "new window with Settings"? Do you mean a launch.json? There are some docs at https://code.visualstudio.com/docs/cpp/config-mingw for the json files for building/debugging.

**Comment by Baky9912** [comment]
https://prnt.sc/qybpcx
https://prnt.sc/qybpw6
I use another extension to compile and run c++, I disabled it and I still have the same problem.
Pressing f5 prompts the first picture and clicking on any of the C++ options opens the second picture.

**Comment by Baky9912** [comment]
I used to have only 1 file open. I opened at file and now I have problems configuring launch,json for win10. I will write here if I get it working.

**Comment by michelleangela** [comment]
Closing this issue because it has not had recent activity.
