### ISSUE TITLE
Fail to Update C/C++ Dependencies and Debugger won't start

### ISSUE THREAD

**Issue by incredibleXM** [microsoft/vscode-cpptools#493]
Here is the problem
![image](https://cloud.githubusercontent.com/assets/19206969/23005612/1e7d0eb4-f438-11e6-9868-310d3e523cbd.png)
![image](https://cloud.githubusercontent.com/assets/19206969/23005628/2ff38bf0-f438-11e6-96c1-92bfd9f698c4.png)
When I press F5 to Debug(while Compiler can be used correctly)
![image](https://cloud.githubusercontent.com/assets/19206969/23005701/88f86e78-f438-11e6-912d-c13fa2a978f1.png)

And this is my launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (GDB)",                 
            "request": "launch",                        
            "type": "cppdbg",
            "targetArchitecture": "x86",               
            "customLaunchSetupCommands": [
                { "text": "target-run", "description": "run target", "ignoreFailures": false }
            ],
            "launchCompleteCommand": "exec-run",
            "program": "${file}.exe",                  
            "MIMode": "gdb",
            "miDebuggerPath":"C:\\MinGW\\bin\\gdb.exe", 
            "miDebuggerServerAddress": "localhost:80",
            "args": [],    
            "stopAtEntry": false,                       
            "cwd": "${workspaceRoot}",                 
            "externalConsole": true,                   
            "preLaunchTask": "g++"　　                  
        }
    ]
}
```

**Comment by sean-mcmanus** [comment]
The extension needs to download additional OS-specific components or the debugger won't work. You will need access to the internet and correct http proxy settings. Are you able to download https://go.microsoft.com/fwlink/?linkid=841505 ?

**Comment by pieandcakes** [comment]
@incredibleXM If you restart VSCode, it should try again. It needs to download dependencies that our extension needs before you can start debugging.

**Comment by incredibleXM** [comment]
Problem solved. Something went wrong with ISP. Thanks anyway.
