### ISSUE TITLE
Focus not restored properly after hovering over a symbol

### ISSUE THREAD

**Issue by GoaLitiuM** [microsoft/vscode-cpptools#4930]
**Type: LanguageService**

When debugging and having the debugger on break, hovering over any symbol changes the cursor focus to text editor instead of back to the UI element which was previously focused on. This issue manifests when I use the document search while the debugger is paused and the focus suddenly changes back to editor without touching any keys other than enter in order to jump to the next search result.

**To Reproduce**
1. Start debugging the application.
2. Hit Pause in debugger.
3. Open up the document search box (CTRL-F) and type something in the field.
3. Move the mouse cursor over any symbol (function, variable etc.) in the editor which prompts the inspector/info box.
4. Move the cursor away to dismiss the info box.
5. Observe the focus changing back to the previous cursor location in text editor instead of back to the search box.

**Expected behavior**
The focus should be restored back to the previously active element instead of the text editor.

- OS and Version: Windows 10
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.3

**Comment by Colengms** [comment]
@pieandcakes  Would this be a debugger issue, or a VS Code issue?  I assume this is a VS Code issue.

**Comment by pieandcakes** [comment]
UI issues should go to VS Code. The debugger gets the underlying call, but doesn't control how the info box/text editor behave.

**Comment by GoaLitiuM** [comment]
Ah, my mistake. Refiled it here: https://github.com/microsoft/vscode/issues/90167
