### ISSUE TITLE
When defining a macro definition, auto-completion does not work

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#4933]
Type: Debugger

Autocomplete is available in the margins, but does not work when defining macro definitions.
After writing a macro definition, can automatically find the source of a defined target.
![{D}7PYK51%1MUMHNU7ATYCF](https://user-images.githubusercontent.com/49903949/74011335-8ad63a80-49c2-11ea-84e8-4b0b1b7bdcf2.png)
![JEQEXFW517F 09SOW34P156](https://user-images.githubusercontent.com/49903949/74011394-afcaad80-49c2-11ea-8819-bfbd03ec133e.png)

**Comment by sean-mcmanus** [comment]
The same behavior exists in VS. I filed a VS issue at https://developercommunity.visualstudio.com/content/problem/911391/cc-intellisense-autocomplete-isnt-available-in-mac.html .
