### ISSUE TITLE
add an option to enable more exceptions with cppvsdbg

### ISSUE THREAD

**Issue by robUx4** [microsoft/vscode-cpptools#4935]
Type: Debugger
cppvsdbg

- OS and Version: Win64 1909
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.3
- A clear and concise description of what the bug is.

I am debugging a program that sometimes launches some `_com_error` exceptions. In MSVC I can trigger the debugger to break on those exceptions (off by default). I would like to be able to catch those (turn on the debugger feature) from VSCode as well.

**Comment by pieandcakes** [comment]
You can add them in the exception pane. Is your suggestion to provide those (disabled) by default or is it not stopping when you add those exceptions?
