### ISSUE TITLE
VSC C++ gdb integration with WSL not working

### ISSUE THREAD

**Issue by OtmarZ** [microsoft/vscode-cpptools#4936]
Debuging with VSCode on Windows 10 with WLS integration (Windows Linux Subsystem) with Ubuntu 18.04.4 LTS not working.

**Describe the bug**
- OS and Version: Win10 17134.1246
- VS Code Version: 1.42.0 user setup
- C/C++ Extension Version:  0.26.3
- Other extensions you installed (and if the issue persists after disabling them):  cmake 0.0.17, cmaketools 1.2.3

VSCode 1.41.1 debugging a simple C++ prog on Win with WSL Ubunu in Dec 2019 works.
Now after update VSCode and the C/C++ extension the WSL gdb debug will not launch!

VSCOde -> Help -> Toggel Develope Tools show

 ERR timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/.../AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2892:728)
    at file:///C:/Users/.../AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2892:159
    at async t.RawDebugSession.shutdown (file:///C:/Users/.../AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2890:248)

My simple setup:

C file "source.c" on WSL Ubuntu in own directory with content:

int main() {
  int i = 3;
  return i;
}

Compile task.json in .vscode folder (was working with VSC 1.41.1)
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "compile_g++",
      "command": "/usr/bin/g++",
      "args": [
        "-g",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}"
      ],
      "options": {
        "cwd": "/usr/bin"
      },
      "problemMatcher": [
        "$gcc"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}

(previous VSC 1.41.1 working) launch.json in .vscode folder:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/source",            
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
        }
    ]
}

Execute  "(dbg) Launch" with "Debug" terminate after 1 sec and nothing happens.

br,
OtmarZ

**Comment by sean-mcmanus** [comment]
It's working for me -- are you using the Remote - WSL extension to remote into the Linux/WSL system from Windows? You might want to change "cwd" to be "${workspaceFolder}" instead of "/usr/bin" as well.

**Comment by OtmarZ** [comment]
Hi Sean!

Thx for your help!

Yes, I use the Remote WSL extension into Linux WSL system of WinX.

I changed now the "cwd" setup of the "task.json" to your suggested ${worksplaceFolder} and the timeout problem disappeared. 
1st "but": I am wondering why the setup in the task.json prevents to start the debugger. I used the setup from launch.json to start the DBG and the tasks from task.json to compile it.

2nd "but": After your suggested change,  I can start the debugger via key "F5" (in source code window) : As a result I see the small debugger tool window (with restart, step into ...) but no arrow points to any code line of my source file. And I see a blue running line below "RUN AND DEBUG" which indicates to me that the debugger should be started but the "step over/into .." icons are disabled. "pause, restart and stop" icons are enabled.

I can stop the debugger and restart it again, but no more. 

br,
OtmarZ

**Comment by sean-mcmanus** [comment]
@pieandcakes @WardenGnaw Do you guys have any idea what is going wrong?

**Comment by pieandcakes** [comment]
> After your suggested change, I can start the debugger via key "F5" (in source code window) : As a result I see the small debugger tool window (with restart, step into ...) but no arrow points to any code line of my source file.  And I see a blue running line below "RUN AND DEBUG" which indicates to me that the debugger should be started but the "step over/into .." icons are disabled. "pause, restart and stop" icons are enabled.

It sounds like the debugger is trying to start debugging. Can you enable [engineLogging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_logging-for-mi-debuggers) and let me know what it outputs in the debugConsole?

**Comment by OtmarZ** [comment]
Hi pieandcakes,
you have a nice nick :-)!

I added next lines to my gdb config in launch.json:

"logging": {
                "trace": false,
                "traceResponse": false,
                "engineLogging": true
            }

And the output in the debug console is that one:

1 : (201) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
1: (217) LaunchOptions  ExePath='/mnt/c/UserData/_tmp/code/source'
1: (217) LaunchOptions  WorkingDirectory='/mnt/c/UserData/_tmp/code'
1: (217) LaunchOptions  ExeArguments=''
1: (218) LaunchOptions  MIMode='gdb'
1: (218) LaunchOptions  MIDebuggerPath=''
1: (218) LaunchOptions  WaitDynamicLibLoad='false'
1: (218) LaunchOptions  ExternalConsole='true'
1: (218) LaunchOptions>
1: (219) LaunchOptions</LocalLaunchOptions>
1: (476) DbgCmd:echo $$ > /tmp/Microsoft-MIEngine-Pid-457ffyo2.ls1 ; cd "/mnt/c/UserData/_tmp/code" ; DbgTerm=`tty` ; set -o monitor ; trap 'rm "/tmp/Microsoft-MIEngine-In-05jjn29w.pom" "/tmp/Microsoft-MIEngine-Out-5xrcbfap.8x2" "/tmp/Microsoft-MIEngine-Pid-457ffyo2.ls1" "/tmp/Microsoft-MIEngine-Cmd-k1v96vph.5pr"' EXIT ; "/usr/bin/gdb" --interpreter=mi --tty=$DbgTerm < "/tmp/Microsoft-MIEngine-In-05jjn29w.pom" > "/tmp/Microsoft-MIEngine-Out-5xrcbfap.8x2" & clear; pid=$! ; echo $pid > "/tmp/Microsoft-MIEngine-Pid-457ffyo2.ls1" ; wait $pid; 
1: (497) Wait for connection completion.

br,
Otmar

**Comment by pieandcakes** [comment]
@OtmarZ your app is called `source` ? 

It looks like it is waiting for gdb to launch and it isn't happening. If you run `ps aux | grep gdb` do you see it running?

**Comment by OtmarZ** [comment]
Hi pieandcakes!

Yes the name of my compiled app is "source" (file with C code is "source.c" - name is not a perfect choice, just for this demo)

I typed in the VSCode "Terminal " your cmd's "ps aux | grep gdb" and the only result is the grep call itself - it seems that no gdb is running.

Do I need to start the gdb/gdb-server manual? I thought that VSCode starts the gdb local and remote in the WSL Ubuntu environment.

br,
Otmar

**Comment by pieandcakes** [comment]
when you are pressing `F5` to start debugging, it should start `gdb`. its after that has started, I'd like you try the `ps` command to see if `gdb` actually started too or if it hasn't started. The question here is whether there is an issue within VSCode's WSL remote extension or with the command we're sending.

**Comment by OtmarZ** [comment]
Hi!

To void any influence of other things, I removed and installed Ubuntu App (18.04 LTS) on WLS system again + gdb 8 + C++ extension - not more. I kept above files. Now VSCode is wating for .. (see Debug Console Output):
1: (185) LaunchOptions</LocalLaunchOptions>
1: (307) DbgCmd:echo $$ > /tmp/Microsoft-MIEngine-Pid-aa88igpn.9xl ; cd "/mnt/c/UserData/_tmp/code" ; DbgTerm=`tty` ; set -o monitor ; trap 'rm "/tmp/Microsoft-MIEngine-In-2wt5ayc6.t3e" "/tmp/Microsoft-MIEngine-Out-v7e0epzk.20n" "/tmp/Microsoft-MIEngine-Pid-aa88igpn.9xl" "/tmp/Microsoft-MIEngine-Cmd-chqz8xro.ayq"' EXIT ; "/usr/bin/gdb" --interpreter=mi --tty=$DbgTerm < "/tmp/Microsoft-MIEngine-In-2wt5ayc6.t3e" > "/tmp/Microsoft-MIEngine-Out-v7e0epzk.20n" & clear; pid=$! ; echo $pid > "/tmp/Microsoft-MIEngine-Pid-aa88igpn.9xl" ; wait $pid; 
1: (327) Wait for connection completion.

Then I typed "ps -aux in the VSCode terminal:

ps  -aux 
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   8304   132 ?        Ss   11:01   0:00 /init ro
root         3  0.0  0.0   8304    92 tty1     Ss   11:01   0:00 /init ro
z...     4  0.0  0.0  17300  4040 tty1     S    11:01   0:00 -bash
root      1474  0.0  0.0   8304    96 tty2     Ss   11:05   0:00 /init ro
z...  1475  0.0  0.0  16928  3604 tty2     S    11:05   0:00 -bash
root      4245  0.0  0.0   8308    96 tty3     Ss   11:10   0:00 /init ro
z...  4246  0.0  0.0  10660   648 tty3     S    11:10   0:00 sh -c "$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" c47d83b293181d9be64f27ff093689e8e7aed054 stable .vscode-server 0  
z...  4247  0.0  0.0  10660   700 tty3     S    11:10   0:00 sh /mnt/c/Users/z.../.vscode/extensions/ms-vscode-remote.remote-wsl-0.42.3/scripts/wslServer.sh c47d83b293181d9be64f27ff093689e8e7aed054 stable .vscode-ser
z...  4252  0.0  0.0  10660   680 tty3     S    11:10   0:00 sh /home/z.../.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/server.sh  --port=0 --fileWatcherPolling=0
z...  4254  0.6  0.2 951756 36852 tty3     Sl   11:10   0:02 /home/z.../.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node /home/z.../.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/
z...  4283  0.0  0.1 725036 19928 tty3     Sl   11:10   0:00 /home/z.../.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node /home/z.../.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/
z...  4295  0.8  0.5 1120228 84280 tty3    Rl   11:10   0:03 /home/z.../.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node /home/z.../.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/
z...  4316  1.6  0.1 935928 20392 tty3     Sl   11:10   0:06 /home/z.../.vscode-server/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.Extension.linux
z...  4343  0.0  0.0 4667352 7676 tty3     Sl   11:10   0:00 /home/z.../.vscode-server/extensions/ms-vscode.cpptools-0.26.3/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 4316 0
z...  4357  0.0  0.0  15276  1680 tty3     S    11:10   0:00 bash /home/z.../.vscode-server/extensions/ms-vscode.cpptools-0.26.3/debugAdapters/OpenDebugAD7
z...  4363  0.3  0.2 748364 36268 tty3     Sl   11:10   0:01 /home/z.../.vscode-server/extensions/ms-vscode.cpptools-0.26.3/debugAdapters/mono.linux-x86_64 --config /home/z.../.vscode-server/extensions/ms-vscode.
z...  4376  0.0  0.0  16696  3284 pts/0    Ss   11:12   0:00 /bin/bash
z...  4391  0.6  0.1 561696 18272 tty3     Sl   11:16   0:00 /home/z.../.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node /home/z.../.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/exte
z...  4403  0.0  0.0  17652  2052 pts/0    R    11:16   0:00 ps -aux
z...:/mnt/c/UserData/_tmp/code$ 

It seems no gdb is running.
Maybe this helps for further checks.

br,
Otmar

**Comment by pieandcakes** [comment]
If you change `"externalConsole": false` does it work? It looks like per the DeveloperTools window they are expecting `xterm` (or whatever you have configured as the `Terminal -> External: Linux Exec` in `File` -> `Preferences` -> `Settings`) to be on the machine and it isn't. I keep getting:
```
 ERR can't find terminal application 'xterm': Error: can't find terminal application 'xterm'
```

I'm going to open an issue on their page.

**Comment by pieandcakes** [comment]
I filed Microsoft/vscode-remote-release#2453 for it.
