### ISSUE TITLE
Hide reserved identifiers in autocomplete list when _ has not been typed

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#4939]
IntelliSense will provide suggestions that include anything and everything in system headers, a lot of which the user is unlikely to use.

![image](https://user-images.githubusercontent.com/49173979/74074250-1ef3d200-49c2-11ea-8f1b-1cb3c78343cb.png)

It may be possible to remove some of these identifiers, such as identifiers reserved for internal use by standard headers.

>the identifiers with a double underscore anywhere are reserved; 
>the identifiers that begin with an underscore followed by an uppercase letter are reserved; 
>the identifiers that begin with an underscore are reserved in the global namespace. 
*(from: https://en.cppreference.com/w/cpp/language/identifiers )*

Though, the last one might need to be kept, as there are various commonly used functions that match that pattern.  i.e. MS implementation of POSIX functions such as `_open`, `_read`, etc.

**Comment by sean-mcmanus** [comment]
There is an existing issue that is related: https://github.com/microsoft/vscode-cpptools/issues/1798

**Comment by Colengms** [comment]
When using tag parser, and completing a member function/variable, would it be possible to filter the results to only member functions/variables?  Seems like the tag parser should have that info.

**Comment by sean-mcmanus** [comment]
@Colengms We do that already -- we just don't have the type available for the class used. Are you seeing a case where global variables are showing in the completion list when using a member access?

**Comment by Colengms** [comment]
@sean-mcmanus I meant members of the current class.  Showing members from all classes isn't particularly useful.  :/  But, it makes sense that we would need semantic parsing to identify the class used.

![image](https://user-images.githubusercontent.com/49173979/129427965-bd2f91ed-ecb4-4037-9f63-154ca68f405b.png)

**Comment by bobbrow** [comment]
Instead of adding settings around this the current thinking is that we just remove the symbols starting with `_` from the suggestion list if the user does not start the symbol they are currently typing with a `_`.  This will prevent the fuzzy matching from matching reserved symbols.

**Comment by sean-mcmanus** [comment]
@bobbrow I'm not opposed to do that, but I believe that it won't actually improve the experience significantly, because under normal circumstances, users who type any letter will not have `__` variables sorted near the top, regardless of if they're filtered or not. I believe it would be better if we:
1. Identified an exact repro case.
2. The exact improvements that will result after the fix.

So far I haven't seen this. I believe in the vast majority of cases where users are complaining about `__` results is when a bug is occurring that is causing local variables (or other valid user variables) to not be shown, such as bug https://github.com/microsoft/vscode-cpptools/issues/8610 or whenever it falls back to the tag parser behavior.

**Comment by michelleangela** [comment]
**Final behavior:**

Reserved identifiers with characters that match typed characters in the same order, but not contiguously are initially filtered from the auto-completion list. 

**Example:**
Typed characters are "**ab**", then identifiers that contain characters "**ab**" in the same order  but not in contiguously such as in the pattern `<any-or-no-character>`**a**`<any-or-no-character>`**b**`<any-or-no-character>` will be filtered from the auto-completion list.

**Bypassing the filter:**
 Typing an underscore `_` as the initial character will bypass this filter, or doing a `ctrl` + `space` in the same location will invoke to show all auto-complete suggestions.
