### ISSUE TITLE
c++11

### ISSUE THREAD

**Issue by CDitzel** [microsoft/vscode-cpptools#494]
I cant seem to get the c++11 standard to work inside VS Code.

e.g. syntax like

double a{5};

should work right?

what am I doing wrong?

**Comment by sean-mcmanus** [comment]
It works for me. What specific feature are you trying to use and what are the results? The C++ extension doesn't provide a compiler or build tools.

**Comment by CDitzel** [comment]
thank you for your reply

I am using standard gcc/g++ 4.9 

code snippet is 

> #include iostream
using namespace std;
int main(){
    std::cout << "hi" << std::endl;
double a{5};
}

also it does not compile with a task defined like:

> {
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "g++",
    "isShellCommand": true,
    "args": ["-o", "-std=c++11", "test", "test.cpp"],
    "showOutput": "always",
    "echoCommand": true
}

**Comment by sean-mcmanus** [comment]
Your args are in the incorrect order. Use "args": ["-o", "test", "-std=c++11", "test.cpp"]. It was treating the -std arg as in the parameter for the -o arg.

**Comment by edlgg** [comment]
Where and how can I define the task to make c++11 work? Im using Ubuntu, I dont know if it would be different.

**Comment by sean-mcmanus** [comment]
@edlgg Did you figure it out? I'm not sure exactly what you're asking for help with. Have you created your task.json yet? What compiler do you want to use? It would be better if you created a new issue instead of adding a comment to a closed issue.

**Comment by ngmgit** [comment]
i can confirm i have the same issue.
![screenshot_20171021_224550](https://user-images.githubusercontent.com/10939602/31854097-c6ea99ae-b6b1-11e7-9f83-c083d9dcd333.png)

**Comment by ngmgit** [comment]
I can confirm i have this issue too.
![screenshot_20171021_224550](https://user-images.githubusercontent.com/10939602/31854169-c66e9e0c-b6b2-11e7-86d9-8c62e9ae7ea8.png)
