### ISSUE TITLE
arm64 is not supported

### ISSUE THREAD

**Issue by peter197321** [microsoft/vscode-cpptools#4940]
I am connecting to my device via VSCode I'm getting notification "Architecture arm64 is not supported"

![image](https://user-images.githubusercontent.com/46971586/74087070-58dbdb80-4a89-11ea-943b-353bba4626d4.png)

Any reason why?

**Comment by cfriedt** [comment]
^^ Same same.
![Screenshot 2020-02-10 at 1 19 02 PM](https://user-images.githubusercontent.com/983494/74177989-cb26fa00-4c08-11ea-8b7d-adb16071bdf7.png)

**Comment by Colengms** [comment]
Hi @peter197321 .  We're currently tracking this with: https://github.com/microsoft/vscode-cpptools/issues/429

**Comment by Colengms** [comment]
Closing as duplicate.
