### ISSUE TITLE
strict null checks in TypeScript

### ISSUE THREAD

**Issue by Veetaha** [microsoft/vscode-cpptools#4941]
While studying your source code to finish with https://github.com/rust-analyzer/rust-analyzer/pull/3053 I've stumbled with these lines of code.
https://github.com/microsoft/vscode-cpptools/blob/3fa056f4d57cb43f4ece6e3e6996af38aa208538/Extension/src/githubAPI.ts#L38-L43
From my perspective, it is apparent that if the release doesn't contain the needed `.vsix` file (which is a developer mistake that should never happen) you will get `TypeError: Cannot read property 'browser_download_url' of undefined`, instead of `undefined` written to `downloadUrl`. Thus, that true branch of the `if` statement is unreachable now.
<details>

<summary>
Proof
</summary>

![image](https://user-images.githubusercontent.com/36276403/74088842-50909a00-4aa3-11ea-984f-c295e98ee12b.png)

</details>

In order to avoid such mistakes I strongly recommend you to set `"strictNullChecks": true` in `tsconfig.json`. The migration process for it is pretty straightforward, you just slap non-null assertions (i.e. postfix `!` operator) everywhere the compiler sees a bug and later fix these places.

**Comment by Colengms** [comment]
Hi @Veetaha .  Thanks for the bug report and the suggestion to enable strictNullChecks.  We will take a look.

**Comment by sean-mcmanus** [comment]
@Colengms FYI, I looked into the structNullChecks several months ago, and it required a lot of changes. VS Code switched to using that last year.

Also, don't make these changes until I get my newMultiRoot2 branch checked in.

**Comment by Veetaha** [comment]
One cannot underestimate the power of strictNullChecks. This is an elegant solution to so-called 1-billion-dollar mistake.

In order to switch to strict-null-checks you can give me up to an hour or two and I will put postfix `!` operators everywhere where the nullability is unsound according to TypeScript compiler. This way you just silence the errors and get strict-null checks from day 1. This means that new code will already use them. After that it is just a matter of time and incremental updates to figure out which types are indeed nullable and which are not to add `null | T` types and remove all unsound postfix `!` operators (i.e. non-null assertions)
