### ISSUE TITLE
Intellisense squiggles on commented lines

### ISSUE THREAD

**Issue by pauljurczak** [microsoft/vscode-cpptools#4943]
I'm using Ubuntu 18.04, VS Code 1.41.1, C/C++ for Visual Studio Code 0.26.3. In some cases, I'm getting Intellisense squiggles on commented lines:

![intellisense1](https://user-images.githubusercontent.com/4933032/74094362-29cf6500-4a9d-11ea-8da1-022cf4b949cd.png)

Can you add a conditional to squiggle display code, which prevents this from happening?

**Comment by Colengms** [comment]
Hi @pauljurczak .  Is it possible an intelliSense pass had not yet completed yet after commenting out the line?  The colorization for the comment is applied by VS Code based on a syntactical parsing of the file.  Squiggles are semantic, based on a first pass compilation of the file, which may happen more slowly.

Did you perhaps have compilation errors present in the Problems output tab, from your last attempt to compile?  I believe those will linger (potentially not aligning with your code as you make edits).  This is a behavior of VS Code for 'problems matchers', I believe, not the C/C++ Extension.

**Comment by pauljurczak** [comment]
Hi @Colengms, indeed this is a lingering squiggle from a line of code , which had errors and was removed.
