### ISSUE TITLE
I need help finding out what the issue with my c_cpp_properties.json file is, lots of context in post

### ISSUE THREAD

**Issue by dunaden001** [microsoft/vscode-cpptools#4944]
**Type: LanguageService**

Please forgive any formatting issues: first Github issue submission.

**Describe the bug**
VSCode Details
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.13.0-43-generic (Mint 18.3)

C/C++ Extension Version: 0.26.3

Other extensions installed:
* Cortex-Debug
* Default Dark+ Contrast
* Material Icon Theme
All errors persist with all above extensions disabled

Description of Bug:

I just tried swapping over to VsCode as an IDE and I'm trying to get intellisense to work with the C/C++ extension.  Originally I tried it with some nRF52 projects and after a day or two gave up and decided to try on something I could understand a bit better.

So now I'm trying to get a simple example esp32 Arduino project to not have any "problems".  Unfortunately I'm consistently getting "#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit" problems occur (and often also "cannot open source file "XXX.h" (dependency of "YYY.h")" problems).  This example project I'm using is being compiled using a clone of this repo (https://github.com/espressif/arduino-esp32) and I am compiling it using a modified version of this makefile (https://github.com/plerup/makeEspArduino/blob/master/makeEspArduino.mk - I can provide my modified version if needed).  The main information to take from this is that the project is being compiled with a bin from that directory.  Every project I'm testing with compiles without any errors.

So my first step was to locate all the files that needed to be included for the project.  I actually started with auto-generating the c_cpp_properties.json file from the makefile, directly using the directories used in the '-Idir' flags of the compilation.  But I've also now started testing with recursive searches to higher directories for simplicity.  So my includePath was as below (please note that these are definitely containing all libraries used by my project [but not necessarily the compiler command] because they are the only directories searched for includes in my makefile too).

	"/home/mike/Arduino/libraries/**",
	"/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/**",
	"/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/**",
	"/home/mike/softwarePackageStorage/arduino_ESP/esp32/cores/esp32/**",
	"/home/mike/softwarePackageStorage/arduino_ESP/esp32/variants/m5stack_core_esp32/**",
	"/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/build_files/test_m5stack-core-esp32/**"

NOTE: in this example I have cloned the repo from https://github.com/espressif/arduino-esp32 to '/home/mike/softwarePackageStorage/arduino_ESP/esp32' and my example test project is in '/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting'.

The next part I learned about was making sure to include all of the files included by your compiler itself and the latest advice seemed to be to achieve this by setting your compilerPath.  So given my makefile is compiling with a binary from within the esp32 repo, I put that command there as shown below:

	"compilerPath": "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++"

This still resulted in the same errors, so then I went to include any definitions that my makefile was putting into the compilation command in case that was making a difference.  So I set up my makefile to automatically set these in the c_cpp_properties.json file along with the includePaths and compilerPath.  This resulted in my defines section looking as below:

	"defines" : [
		"-DESP_PLATFORM",
		"-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"",
		"-DHAVE_CONFIG_H",
		"-DGCC_NOT_5_2_0=0",
		"-DWITH_POSIX",
		"-DF_CPU=240000000L",
		"-DARDUINO=10605",
		"-DARDUINO_M5Stack_Core_ESP32",
		"-DARDUINO_ARCH_ESP32",
		"-DARDUINO_BOARD=\"M5Stack_Core_ESP32\"",
		"-DARDUINO_VARIANT=\"m5stack_core_esp32\"",
		"-DESP32",
		"-DCORE_DEBUG_LEVEL=0"
		],

This still resulted in the same errors, so after a couple days of banging my head against the wall and searching github issues, I saw bobbrow on several github issues repeatedly recommending to run:
	g++ -Wp,-v -E -xc -x c++ /dev/null
Then "The "includePath" in your c_cpp_properties.json file should match that".  If I'm understanding this correctly, this was accounted for with the compilerPath setting but I tried this anyway.

So from my understanding:
According to https://linux.die.net/man/1/g++ (because the man page is annoying to traverse):
-Wp,option passes all options after the ',' directly onto the pre-processor
-v Print (on standard error output) the commands executed to run the stages of compilation. Also print the version number of the compiler driver program and of the preprocessor and the compiler proper.
-E Stop after the preprocessing stage; do not run the compiler proper. The output is in the form of preprocessed source code, which is sent to the standard output.
-xc Specify explicitly the language for the following input files as c
-x c++ Specify explicitly the language for the following input files as c++
/dev/null I'm guessing means just supply no actual files so no actual compilation occurs past the bare minimum.

So I'm presuming this should be printing out the steps in the process of compiling a null project which would mean printing include files as it finds them to bring in (because of -v) to compile c and c++ files.  Then it stops after pre-processing and doesn't go further.

For me, because I'm using the compiler in the esp32 build repo mentioned above, I've been running this command to try and achieve the same as above:

	/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ -Wp,-v -E -xc -x c++ /dev/null

and I get the following output:

	ignoring duplicate directory "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/../../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/include/c++/5.2.0"
	ignoring duplicate directory "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/../../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf"
	ignoring duplicate directory "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/../../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/include/c++/5.2.0/backward"
	ignoring duplicate directory "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/../../lib/gcc/xtensa-esp32-elf/5.2.0/include"
	ignoring nonexistent directory "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../xtensa-esp32-elf/sysroot/builds/idf/crosstool-NG/builds/xtensa-esp32-elf/xtensa-esp32-elf/sysroot/include"
	ignoring duplicate directory "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/../../lib/gcc/xtensa-esp32-elf/5.2.0/include-fixed"
	ignoring duplicate directory "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/../../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/include"
	#include "..." search starts here:
	#include <...> search starts here:
	/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/include/c++/5.2.0
	/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf
	/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/include/c++/5.2.0/backward
	/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/include
	/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/include-fixed
	/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/include
	/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/../xtensa-esp32-elf/sysroot/usr/include
	End of search list.
	# 1 "/dev/null"
	# 1 "<built-in>"
	# 1 "<command-line>"
	# 1 "/dev/null"

Note that I also did the same with "xtensa-esp32-elf-gcc" in the same directory and got the same results.

Because all of the file names I see are definitely in this directory, I just include it with a recursive search using **
	/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/**

But also of note: I have tested including each individual directory both as listed with the relative jumps and as a realpath.

Next, to make sure I was covering all bases, I also ran the command using standard g++ in case that gets called by the esp32 compiler or something that I don't understant.  This yields the following output:

	ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/5"
	ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
	ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/include"
	#include "..." search starts here:
	#include <...> search starts here:
	/usr/include/c++/5
	/usr/include/x86_64-linux-gnu/c++/5
	/usr/include/c++/5/backward
	/usr/lib/gcc/x86_64-linux-gnu/5/include
	/usr/local/include
	/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
	/usr/include/x86_64-linux-gnu
	/usr/include
	End of search list.
	# 1 "/dev/null"
	# 1 "<built-in>"
	# 1 "<command-line>"
	# 1 "/usr/include/stdc-predef.h" 1 3 4
	# 1 "<command-line>" 2
	# 1 "/dev/null"

So from this, I also tried including these directories:

	"/usr/include/c++/5",
	"/usr/include/x86_64-linux-gnu/c++/5",
	"/usr/include/c++/5/backward",
	"/usr/lib/gcc/x86_64-linux-gnu/5/include",
	"/usr/local/include",
	"/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
	"/usr/include/x86_64-linux-gnu",
	"/usr/include"

From all of these attempts, I consistently always had at least "#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit" problems and usually also "cannot open source file "XXX.h" (dependency of "YYY.h")" problems occur.  So after more headbashing and reading github issues, I wanted to verify that the correct directories were actually being included by vscode/the extension with the diagnostics logging.

So first, my current c_cpp_properties.json file is as below:

	{
	"version": 4,
	"env": {},
	"configurations": [
		{
			"defines": [
				"ESP_PLATFORM",
				"MBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"",
				"HAVE_CONFIG_H",
				"GCC_NOT_5_2_0=0",
				"WITH_POSIX",
				"F_CPU=240000000L",
				"ARDUINO=10605",
				"ARDUINO_M5Stack_Core_ESP32",
				"ARDUINO_ARCH_ESP32",
				"ARDUINO_BOARD=\"M5Stack_Core_ESP32\"",
				"ARDUINO_VARIANT=\"m5stack_core_esp32\"",
				"ESP32",
				"CORE_DEBUG_LEVEL=0"
			],
			"cStandard": "c11",
			"browse": {
				"limitSymbolsToIncludedHeaders": false
			},
			"includePath": [
				"/home/mike/Arduino/libraries/**",
				"/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/**",
				"/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/**",
				"/home/mike/softwarePackageStorage/arduino_ESP/esp32/cores/esp32/**",
				"/home/mike/softwarePackageStorage/arduino_ESP/esp32/variants/m5stack_core_esp32/**",
				"/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/build_files/test_m5stack-core-esp32/**",
				"/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/**"
			],
			"intelliSenseMode": "gcc-x64",
			"cppStandard": "c++17",
			"compilerPath": "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++",
			"name": "test"
		}
	]
	}

(Note that I only set limitSymbolsToIncludedHeaders to false after I noticed in the Log Diagnostics that it was defaulting to true and I wanted to make sure that wasn't causing issues either.)

I then opened the C/C++ log Diagnostics panel through the command input and saw the output below.  Note that the the directories that are included in the 'Includes' are correctly identifying the locations of the source files that are directly and indirectly linked into my project.

	-------- Diagnostics - 09/02/2020, 3:46:27 pm
	Version: 0.26.3
	Current Configuration:
	{
		"defines": [
			"ESP_PLATFORM",
			"MBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"",
			"HAVE_CONFIG_H",
			"GCC_NOT_5_2_0=0",
			"WITH_POSIX",
			"F_CPU=240000000L",
			"ARDUINO=10605",
			"ARDUINO_M5Stack_Core_ESP32",
			"ARDUINO_ARCH_ESP32",
			"ARDUINO_BOARD=\"M5Stack_Core_ESP32\"",
			"ARDUINO_VARIANT=\"m5stack_core_esp32\"",
			"ESP32",
			"CORE_DEBUG_LEVEL=0"
		],
		"cStandard": "c11",
		"browse": {
			"limitSymbolsToIncludedHeaders": false,
			"path": [
				"/home/mike/Arduino/libraries/**",
				"/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/**",
				"/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/**",
				"/home/mike/softwarePackageStorage/arduino_ESP/esp32/cores/esp32/**",
				"/home/mike/softwarePackageStorage/arduino_ESP/esp32/variants/m5stack_core_esp32/**",
				"/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/build_files/test_m5stack-core-esp32/**",
				"/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/**",
				"${workspaceFolder}"
			]
		},
		"includePath": [
			"/home/mike/Arduino/libraries/**",
			"/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/**",
			"/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/**",
			"/home/mike/softwarePackageStorage/arduino_ESP/esp32/cores/esp32/**",
			"/home/mike/softwarePackageStorage/arduino_ESP/esp32/variants/m5stack_core_esp32/**",
			"/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/build_files/test_m5stack-core-esp32/**",
			"/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/**"
		],
		"intelliSenseMode": "gcc-x64",
		"cppStandard": "c++17",
		"compilerPath": "/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++",
		"name": "test",
		"compilerArgs": []
	}
	Translation Unit Mappings:
	[ /home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/test.ino ]:
		/home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/test.ino
	Translation Unit Configurations:
	[ /home/mike/Documents/HAX/lockerGui/checkoutDeviceFirmware/intellisenseTesting/test.ino ]:
		Process ID: 22224
		Memory Usage: 177 MB
		Compiler Path: /home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++
		Includes:
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/xtensa-esp32-elf
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/backward
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/lib/gcc/xtensa-esp32-elf/5.2.0/include
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/lib/gcc/xtensa-esp32-elf/5.2.0/include-fixed
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/xtensa-esp32-elf/include
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/xtensa-esp32-elf/sysroot/usr/include
			/home/mike/Arduino/libraries/M5ez/src
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/WiFi/src
			/home/mike/Arduino/libraries/M5Stack/src
			/home/mike/Arduino/libraries/ezTime/src
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/cores/esp32
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/Wire/src
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/SPI/src
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/FS/src
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/SD/src
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/variants/m5stack_core_esp32
			/home/mike/softwarePackageStorage/arduino_ESP/esp32/libraries/SPIFFS/src
		Defines:
			ESP_PLATFORM
			MBEDTLS_CONFIG_FILE="mbedtls/esp_config.h"
			HAVE_CONFIG_H
			GCC_NOT_5_2_0=0
			WITH_POSIX
			F_CPU=240000000L
			ARDUINO=10605
			ARDUINO_M5Stack_Core_ESP32
			ARDUINO_ARCH_ESP32
			ARDUINO_BOARD="M5Stack_Core_ESP32"
			ARDUINO_VARIANT="m5stack_core_esp32"
			ESP32
			CORE_DEBUG_LEVEL=0
		Standard Version: c++17
		IntelliSense Mode: gcc-x64
		Other Flags:
			--g++
			--gnu_version=50200
			--header_only_fallback
	Total Memory Usage: 177 MB

So I'm now at a loss as to what I do next. I still have the same "problems", click-through references still take me to the correct files though. The only thing I can think to do is to also set the compilerArgs in case that has any significant effect but I've already set the -I and -D flags with the includePath and defines so I don't really see what difference it could make.

Any advice that takes into account the information I've provided here would be great.

**To Reproduce**

It might be a bit frustrating to setup the full system to reproduce exactly, if someone can walk me through an example that I can setup to see if the issue persists there I can do so to try and generate a minimum system that repros the issue.

Projects I'm using in my example:
* https://github.com/espressif/arduino-esp32 (compiler and core tools)
* https://github.com/plerup/makeEspArduino (makefile - I'm using a modified version, can be provided if necessary)
* https://github.com/ropg/M5ez (library I'm using - example I'm using for this is the 'Hello World' example in the example subdirectory of this repo)
* https://github.com/m5stack/M5Stack (dependency of the above library)

**Expected behavior**

![Screenshot_20200209_162310](https://user-images.githubusercontent.com/1224148/74099117-2ac6cc00-4b5b-11ea-80fc-b7248b956bf4.png)
![Screenshot_20200209_162256](https://user-images.githubusercontent.com/1224148/74099120-3914e800-4b5b-11ea-8b7f-0397661200c5.png)

**Additional context**

**Comment by Colengms** [comment]
Hi @MichaelAReed .  Based on the output of the Log Diagnostics command, your configuration looks valid and looks like making it into the intelliSense configuration for the file.  In your screenshot, I see there is an error trying to locate: "esp_err.h".  Can you confirm the location of that file?  Perhaps it's in a path that's not included.

Possibly unrelated, but consider using "gcc-x86" (32-bit) as the intelliSense mode instead of "gcc-x64", to ensure 32-bit pointer sizes are used for intelliSense.

**Comment by dunaden001** [comment]
@Colengms You were very correct.  Turns out "esp_err.h" was in
"/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/someDirectory"
and I was only including
"/home/mike/softwarePackageStorage/arduino_ESP/esp32/tools/xtensa-esp32-elf/**"
so I just pulled out the "xtensa-esp32-elf" subdirectory and everything is shiny.

No idea how I made it this far and I managed to miss that, thank you very much for sifting through my info-dump to help!
