### ISSUE TITLE
[loc][Query][vscode_extension] Localizability of string: 0; "package.c_cpp.configuration.clang_format_path.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#4948]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The full path of the clang-format executable. If not specified, and clang-format is available in the environment path, that is used. If not found in the environment path, a copy of clang-format bundled with the extension will be used.

String ID:
0; "package.c_cpp.configuration.clang_format_path.description"

File Name:
Src\vscode-extensions\vscode-cpptools.xlf

Query:
"that is used" - what is used?
"If not found in the environment path" - what is not found?

**Comment by Colengms** [comment]
>that is used

clang-format is a utility that formats source code.  It is used when the user selects one of the format commands (format document, format selection).

>If not found in the environment path

This is referring to clang-format.  We search for it already installed on the system, and available (it's path is present in the PATH environment variable).  If not found, we fall back to using our own copy of the executable.

**Comment by PDostalek** [comment]
Thanks for clarifying
