### ISSUE TITLE
IntelliSense doesn't use includes pathes from the compiler given in compile_commands.json

### ISSUE THREAD

**Issue by GertGrossmann** [microsoft/vscode-cpptools#4949]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Remote-SSH Win -> Linux
- VS Code Version: 1.42.0
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them):
CMake Tools 1.3.0, issue persists after deactivation
- A clear and concise description of what the bug is.

'CMake Tools' generated a 'compile_commands.json' and this reflects in the C/C++ configuration ("C_Cpp.default.compileCommands": "${workspaceRoot}/build/compile_commands.json").
I get squiggles under '#includes' because the path is not known.

IntelliSense reads the correct entry but doesn't use the specified compiler (plus default include pathes for this compiler) for the entry in compile_comands.json

**To Reproduce**

${workspaceFolder}=/my/project
create myFile.cpp with '#includes' which only has /my/path/to/gcc in its installation.
create a compile.commands.json in ${workspaceFolder}/build:
`[
{
"directory": "/my/project/src",
"command" : "/my/path/to/gcc -DBLAH -o myfile.cpp.o -c myfile.cpp"
}
]`
settings.json and enter 
"C_Cpp.loggingLevel": "Debug"
"C_Cpp.default.compileCommands": "${workspaceRoot}/build/compile_commands.json"

2. Click on '....' Open myfile.cpp
Look at the output for C/C++ extension

**Expected behavior**

My compile_command.json entry contains a compiler which isn't in the path (/my/path/to/gcc). I would expect IntelliSense would add include pathes from `/my/path/to/gcc -print-search-dirs`. Instead pathes from `/usr/bin/gcc -print-search-dir` has been added. So IntelliSense fails because it doesn't get the correct include pathes.

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
If you're using the CMake Tools extension, then you should be setting the configurationProvider setting instead of the compileCommands setting.

Do you have a compilerPath property set to /usr/bin/gcc? If so, that will overwrite the compiler path in the compile_commands.json.

Can you set C_Cpp.loggingLevel to "Debug" and view the output of the C/C++ pane to see what error is shown when it tries to query /my/path/to/gcc?

**Comment by GertGrossmann** [comment]
Indeed there was a default config for 'compilerPath' coming from ${workspaceFolder}/.vscode/c_cpp_properties.json - I assume 'CMake Tools' had created this config. After removing this file everthing went fine. Thanks for the hint.
But I see a problem there. This c_cpp_properties.json hasn't come up in the dialog '@ext:ms-vscode.cpptools'. I only see tabs for 'User' (settings,json), for 'Remote [SSH: ...]' (settings.json) and for 'Workspace' (settinngs.json). c_cpp_properties.json is under the radar of the configuration dialog.
