### ISSUE TITLE
tasks.json for compiling source file

### ISSUE THREAD

**Issue by CDitzel** [microsoft/vscode-cpptools#495]
I am trying to compile a small program "test.cpp" 

#include < iostream >
using namespace std;

int main(){
    std::cout << "hi" << std::endl;

double a = 5;

}

via the definition of a task, that looks like this:

{
    "version": "0.1.0",
    "command": "g++",
    "isShellCommand": true,
    "args": ["-o", "-std=c++11", "test", "test.cpp"],
    "showOutput": "always",
    "echoCommand": true
}

however, I always get the folllowing output, what am I missing here?

`running` command$ g++ -o -std=c++11 test test.cpp
test: In function `_start':
(.text+0x0): multiple definition of `_start'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o:(.text+0x0): first defined here
test: In function `_fini':
(.fini+0x0): multiple definition of `_fini'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crti.o:(.fini+0x0): first defined here
test:(.rodata+0x0): multiple definition of `_IO_stdin_used'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o:(.rodata.cst4+0x0): first defined here
test: In function `data_start':
(.data+0x0): multiple definition of `__data_start'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o:(.data+0x0): first defined here
test: In function `data_start':
(.data+0x8): multiple definition of `__dso_handle'
/usr/lib/gcc/x86_64-linux-gnu/4.9/crtbegin.o:(.data+0x0): first defined here
test: In function `_init':
(.init+0x0): multiple definition of `_init'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crti.o:(.init+0x0): first defined here
/tmp/ccFLku6Q.o: In function `main':
test.cpp:(.text+0x0): multiple definition of `main'
test:(.text+0xf6): first defined here
/usr/lib/gcc/x86_64-linux-gnu/4.9/crtend.o:(.tm_clone_table+0x0): multiple definition of `__TMC_END__'
test:(.data+0x10): first defined here
/usr/bin/ld: error in test(.eh_frame); no .eh_frame_hdr table will be created.
collect2: error: ld returned 1 exit `status`

**Comment by sean-mcmanus** [comment]
Your args are in the incorrect order. Use "args": ["-o", "test", "-std=c++11", "test.cpp"]. It was treating the -std arg as in the parameter for the -o arg.

**Comment by CDitzel** [comment]
thanks a lot. And can I also run make and cmake commands in the task.json?

**Comment by sean-mcmanus** [comment]
Yes.

**Comment by CDitzel** [comment]
if I may ask one more question. 

if I need to cd first into a build directory within my project directory before calling make etc.

how can I facilitate this in a task.json?

**Comment by sean-mcmanus** [comment]
I'll answer your question in the newer post you made.
