### ISSUE TITLE
Linking error not shown in the Problems panel

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode-cpptools#4957]
The linking errors are not shown in the Problems panel.
Using cl.exe and makefiles to build.

**Comment by psclkhoury** [comment]
@sean-mcmanus could you provide some hints of what should be done to try and give it a go myself?

**Comment by sean-mcmanus** [comment]
You could try to add a problem matcher or modify the existing one: That's what we do for gcc: https://github.com/microsoft/vscode-cpptools/blob/master/Extension/package.json#L76 .

If using the problemMatcher json isn't powerful enough, you could write a wrapper for gcc and/or it's linker that outputs its own diagnostics/problems (potentially also dealing with https://github.com/microsoft/vscode-cpptools/issues/4128 ). Info at https://code.visualstudio.com/api/references/vscode-api#Diagnostic and https://code.visualstudio.com/api/references/contribution-points#contributes.taskDefinitions might be useful.

There's also a new VS Code problem matcher API being discussed: https://github.com/microsoft/vscode/issues/59337 .

**Comment by psclkhoury** [comment]
I realized that I am using the `msCompile` problem matcher which comes from vscode and not the `gcc` one that comes from the `c/c++ extension`.

I solved my problem by writing a custom problem matcher for linking errors and combining it with the `msCompile` one.

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "cl.exe build active file",
      "command": "cl.exe",
      "args": [
        "/Zi",
        "/EHsc",
        "/Fe:",
        "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "${file}"
      ],
      "problemMatcher": [
        "$msCompile",
        {
          "fileLocation": "autoDetect",
          "pattern": {
            "regexp": "^([^\\s].*)\\s*:\\s+(?:fatal\\s+)?(error|warning)\\s+(LNK\\d+)\\s*:\\s*(.*)\\[(.*)\\]$",
            "kind": "file",
            "severity": 2,
            "code": 3,
            "message": 4,
            "file": 5
          }
        }
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

I will close this issue.
