### ISSUE TITLE
How to include additional path for auto-completion and suggestions?

### ISSUE THREAD

**Issue by CDitzel** [microsoft/vscode-cpptools#496]
I am still having trouble wrapping my head around some of the features.

VS Code, when opened in a directory, is parsing all the existing files and upon completion, the red flame vanishes and auto completion is enabled. Is that understanding correct?

No, whats the difference between auto-completion, suggestions that turn up while typing and Intelli Sense?

Also, my project depends on includes and libs in different folders, what do I need to do to enable suggestions for those files as well? just put them in the include path in the c_pp_properties.json?

And why is this c_pp_properties.json local to every directory rather than a global file setting?

thanks in advance

**Comment by sean-mcmanus** [comment]
Currently, the files aren't fully parsed and only non-local variables are added to the database. So autocomplete and other features will usually generate "too many" results, sometimes invalid in the context, or local vars will be missing. Our team refers to "IntelliSense" as the IntelliSense engine used by Visual Studio C++ (versus the currently "browse engine"), but VS Code refers to it more generally as a set of features.

Add the include paths to your includePath setting in the c_cpp_properties.json. That config file is per-workspace...we're considering enabling a global version like the normal settings in the future. We don't handle libs specially.

**Comment by CDitzel** [comment]
All right. Thank you.

And will there a full-fetched auto-complete (comparable to the one in Studio) in VS Code in the near future?

**Comment by sean-mcmanus** [comment]
Yes, we are working on it.
