### ISSUE TITLE
Use VS Code's CodeAction type instead of Command

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-cpptools#4961]
Hi, I work on VS Code's code actions. Our telemetry shows that your extension is returning `Command` types from at least one `CodeActionProvider`. A few years ago, we introduced a [`CodeAction` type](https://code.visualstudio.com/api/references/vscode-api#CodeAction) that brings a number of benefits over `Command`, including allowing workspace edits to be returned directly and letting extensions tag the type of their code actions (such as `Refactor` or `QuickFix`)

To make sure your extension behaves as expected with VS Code's new features, please migrate all of your code action providers to return `CodeActions` instead of `Commands`

 Let me know if you have any questions about this

**Comment by sean-mcmanus** [comment]
Thanks for letting us know.

**Comment by sean-mcmanus** [comment]
Fixed with 0.27.0.
