### ISSUE TITLE
launch.json should pass arguments verbatim (Unexpected parsing args of format `{,}`)

### ISSUE THREAD

**Issue by samloescher** [microsoft/vscode-cpptools#4962]
Type: General

Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:23.649Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.17-1-MANJARO

- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): Issue persists after disabling them.

When providing arguments in the format `{x,y}` they are expanded into two distinct arguments `x` and `y`. This is unexpected, there also appears no way to stop this parsing occurring, and I've not found what causes this from the docs. As shown you can avoid this behaviour by adding a space character after the comma (`{x, y}`) however it should be possible to provide arguments verbatim. Perhaps a flag to disable any parsing of `args`?

**To Reproduce**

Create task in launch.json with `{x,y}`

```
        {
            "name": "vscode {} parsing",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/saml/workspace/vscode-braces/build/parseargs",
            "args": ["{1,2}", "\"{3,4}\"", "{5, 6}", "(7,8)"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
``` 
example cpp parser
```
#include <iostream>

int main(int argc, char **argv) {
    for (auto i = 0; i < argc; i++) {
        std::cout << argv[i] << std::endl;
    }
}
```

Expected:
/home/saml/workspace/vscode-braces/build/parseargs
{1,2}
"{3,4}"
{5, 6}
(7,8)

Actual:
/home/saml/workspace/vscode-braces/build/parseargs
1
2
"3"
"4"
{5, 6}
(7,8)

I originally created this ticket against VSCode (https://github.com/microsoft/vscode/issues/90362) before getting forwarded here

**Comment by michelleangela** [comment]
The C/C++ extension does not parse arguments from the launch.json file. This issue is on the VS Code client side which parses the data from launch.json. 

For reference, it was verified that this issue does not reproduce on Windows. On Linux, the issue does not also reproduce when executing the program directly from the terminal (that is not using launch.json):

`$./main.out "{1,2}" "\"{3,4}\"" "{5, 6}" "(7,8)"`

output:
```
./main.out
{1,2}
"{3,4}"
{5, 6}
(7,8)
```

Please re-open the issue on VS Code for further investigation on launch.json for Linux.

**Comment by samloescher** [comment]
Hey @michelleangela, I can't reproduce the issue with a different language target (here's the example in python https://github.com/microsoft/vscode/issues/90362#issuecomment-586016465), and the VSCode team are pretty sure it's the C++ plugin and they don't do any parsing of `args`. Is there any possibility there is parsing happening in the plugin? Unfortunately this bug presumably is right near the interface of the plugin and VSCode so not sure what to suggest without keep getting bounced between the two repos.

Given it works on Windows and not on Linux is a good hint though, potentially we are using explicitly platform specific code or a third party library has platform specific behaviour (in parsing :scream:)

**Comment by samloescher** [comment]
It looks like it's because behaviour in linux in bash, e.g.

```
$ python3 hello.py {1,2}
['1', '2']
$ python3 hello.py "{1,2}"
['{1,2}']
```

I'm having some trouble printing out the exact command which is launch to inspect the string escaping, I've read through https://code.visualstudio.com/docs/cpp/launch-json-reference but can't seem to find it anywhere obvious of just printing it out, and when keeping the console open after launching it looks like it executed something along the lines of 

`[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/home/saml/tmp/Microsoft-MIEngine-In-1vs5532w.oyk" 1>"/home/saml/tmp/Microsoft-MIEngine-Out-5rkjryql.5ve"`

Is there anyway to inspect the original command it launched with?

**Comment by michelleangela** [comment]
@pieandcakes or @WardenGnaw , is there a way to get the original command from launch.json that is used to launch a program? On Linux, the args that are passed to a program are not parsed correctly which results in incorrect input.

**Comment by pieandcakes** [comment]
If you enable engineLogging, it should show the command we send to `gdb` including the debuggee and its arguments.

**Comment by samloescher** [comment]
I'm not entirely sure to where `enableLogging` flag is meant to be set, so I've modified my launch.json to look like the following:

```
        {
            "name": "args {,} parsing",
            "type": "cppdbg",
            "request": "launch",
            "program": "/bin/echo",
            "args": ["{1,2}", "\\\"{3,4}\\\"", "{5, 6}", "(7,8)"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "logging": {
                "engineLogging": true,
                "programOutput": true,
                "exceptions": true,
                "moduleLoad": true,
                "trace": true,
                "traceResponse": true
            },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
```
And in the debug console I'm seeing:
```
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (229) LaunchOptions  ExePath='/bin/echo'\n"},"seq":4}
1: (229) LaunchOptions  ExePath='/bin/echo'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (229) LaunchOptions  WorkingDirectory='/home/saml/workspace/workbench'\n"},"seq":6}
1: (229) LaunchOptions  WorkingDirectory='/home/saml/workspace/workbench'
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (230) LaunchOptions  ExeArguments='{1,2} \\\"{3,4}\\\" \"{5, 6}\" \"(7,8)\"'\n"},"seq":8}
1: (230) LaunchOptions  ExeArguments='{1,2} \"{3,4}\" "{5, 6}" "(7,8)"'
```

Which if paste out for reference looks to be concatenated to :
`\bin\echo {1,2} \"{3,4}\" "{5, 6}" "(7,8)"` -> `1 2 "3" "4" {5, 6} (7,8)`

Here's some things I've tried so far and their corresponding debug console and terminal output:
| args from launch.json | Debug console output | Terminal output |
| ------------- | ------------- | ------------- |
| `"{1,2}"`  | `ExeArguments='{1,2}'`  | `1 2`|
| `"\"{1,2}\""`  | `ExeArguments='\\\"{1,2}\\\"'` | `"1" "2"` |
| `"\\\"{1,2}\\\""` | `ExeArguments='\\\"{1,2}\\\"'` | `"1" "2"` |
| `"\\\\\"{1,2}\\\\\""` | `ExeArguments='\\\\\"{1,2}\\\\\"'` | `\{1,2}\` |
| `"\\\"\"{1,2}\\\"\""` | `ExeArguments='\\\"\\\"{1,2}\\\"\\\"'` | `""1"" ""2""` |
| ? | ? | `"{1,2}"` |

So I guess the problem is now how is the escaping managed such that I can set my args to produce an actual argument of `"{1,2}"`

**Comment by pieandcakes** [comment]
Thanks for investigating. my assumption is you would want something like `"\"\{1,2\}\""` but I'll see if I can figure out the correct order and also how it can be more predictable. It looks like its non deterministic at this point.

**Comment by samloescher** [comment]
I found the following which worked in case others encounter this:
args from launch.json | Debug console output | Terminal output
-- | -- | --
`"\"\\{1,2\\}\""` | `ExeArguments='\\\"\\{1,2\\}\\\"'` | `"{1,2}"`

I guess the way to work around this is described simply, escape `"` once, escape `{` twice.
