### ISSUE TITLE
Add a minimum-required version check before using system installed clang-format

### ISSUE THREAD

**Issue by anjiawei1991** [microsoft/vscode-cpptools#4963]
my clang-format's version is 3.4.2 and has no option of -fallback-style.  but the latest cpptools extension use it.  and I can hardly upgrade clang-format based on my enviroment.

**Comment by Colengms** [comment]
Hi @anjiawei1991 .  Let's use this issue to track adding a minimum version check before trying to use the installed version of clang-format.  In the meanwhile, try  setting `clang_format_path` to the clang-format binary bundled with the extension:

`"C_Cpp.clang_format_path": "<path_to_the_CppTools_extension>\\LLVM\\bin\\clang-format.exe"`

**Comment by sean-mcmanus** [comment]
Setting the hardcoded "<path_to_the_cpptools>" will break after a new version of the extension gets installed. Should we add a setting or variable that enables using the extension's clang-format or do we think a "minimum version" setting is sufficient?

**Comment by sean-mcmanus** [comment]
Fixed in our latest Insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders
