### ISSUE TITLE
Can't use classes in separate files

### ISSUE THREAD

**Issue by lor1x** [microsoft/vscode-cpptools#4965]
Hi,

I recently started coding C++ in Visual Studio Code and trying to create a class in separate files (the class prototype and the cpp file where I would code the class).

Trying to do these I keep stumbling upon issues. One of them being this when I run the main function:
```
    Undefined symbols for architecture x86_64:
    "Test::Test()", referenced from:
        _main in main-da9e6e.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    The terminal process terminated with exit code: 1
```

This is the class prototype I saved with the name Test.h
```
#ifndef Test_h
#define Test_h

class Test {
   public:
    Test();
    void prt() {
    }
};

#endif
```

This is the Test.cpp
```
#include "Test.h"
#include <iostream>
using namespace std;

Test::Test() {}

void Test::prt() {
    cout << "Test" << endl;
}
```

I will get highlighted the function line code where it says: redefinition of 'prt'

This is the c_cpp_properties.json file:
```
{
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}",
                "${workspaceFolder}/**"
            ],
            "defines": [
                "VERSION = 1"
            ],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}",
                    "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
                ],
                "limitSymbolsToIncludedHeaders": false,
                "databaseFilename": ""
            },
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "forcedInclude": [],
            "compilerPath": "/usr/bin/clang++",
            "compilerArgs": [],
            "cStandard": "c11",
            "cppStandard": "c++20",
            "configurationProvider": "ms-vscode.cmake-tools"
        },
```

This is the launch.json:
```
{
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/hello",
            "preLaunchTask": "build",
            "internalConsoleOptions": "openOnSessionStart",
            "logging": {
                "moduleLoad": false,
                "programOutput": true,
                "trace": false
            },
            "showDisplayString": false,
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "osx": {
                "MIMode": "lldb"
            }
        },
    ]
}
```
If I haven't included something please let me know.

**Comment by Colengms** [comment]
> redefinition of 'prt'

Hi @lor1x .  It looks like you are defining prt() both inline within the class, as well as outside of the class.  Here it's defined inline:

```
class Test {
   public:
    Test();
    void prt() {   // <-- Inline
    }
};
```

If you want to define prt() outside of the class, you will want to specify only a prototype within class (omit the curly braces and their contents).  i.e. :

```
class Test {
   public:
    Test();
    void prt();
};
```

The error message you posted;

```
    Undefined symbols for architecture x86_64:
    "Test::Test()", referenced from:
```

appears to be outdated.(?)  It looks like you have defined Test::Test().

**Comment by lor1x** [comment]
Hi @Colengms!

Thank you for your reply!

I have tried not defining the function inline and this is the error it has thrown me before and again now that I tried it again:
Undefined symbols for architecture x86_64:
  "Test::prt()", referenced from:
      _main in main-f74463.o
  "Test::Test()", referenced from:
      _main in main-f74463.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have tried looking up for such errors but have not been able to troubleshoot it on my end. I even tried it on Windows and the same issue.

Edit: 
A few other little suggestions I get from VS Code:

<a href="https://ibb.co/VHrv9J9"><img src="https://i.ibb.co/vsgJqVq/Screen-Shot-2020-02-13-at-21-21-01.png" alt="Screen-Shot-2020-02-13-at-21-21-01" border="0"></a>
<a href="https://ibb.co/YRX3R4h"><img src="https://i.ibb.co/Gx90xfR/Screen-Shot-2020-02-13-at-21-21-10.png" alt="Screen-Shot-2020-02-13-at-21-21-10" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/wSVWqSM/Screen-Shot-2020-02-13-at-21-21-23.png" alt="Screen-Shot-2020-02-13-at-21-21-23" border="0"></a> 

I have set C11 and C++20 as standards though.

**Comment by Colengms** [comment]
Hi @lor1x  .  How are you building your project?  The C/C++ Extension does not provide build services (other than Build and Debug Active file, but it looks like you have multiple files).

Is it possible that Test.cpp is not included in your build?

**Comment by lor1x** [comment]
I used the C/C++ extension and Run Code extension, both giving me the same error to build this test program. I have them (Test.h prototype class, Test.cpp where I insert the working code of the class and main.cpp where I create the object to access that function of that class in those files).

I have included the launch.json and c_cpp_properties.json configs on my first post @Colengms.

Thank you for you help!

**Comment by Colengms** [comment]
To clarify, the C/C++ Extension does not build.  It provides language services, such as IntelliSense.  For the compile error you are seeing (unresolved symbols), you may need to follow up with the extension(?) providing build services.  (Run Code extension?).  The issue looks like Test.cpp is not being linked by your build, hence the symbols defined within it are not resolved.

Regarding the squiggles in your last response; Do you have another extension installed that might be adding those?  The specific error messages you are seeing do not appear to match anything our extension generates.

**Comment by lor1x** [comment]
Got it! Thank you for clarifying!
Take care!
