### ISSUE TITLE
Struct dot initializer not recognized by intellisense autocomplete

### ISSUE THREAD

**Issue by serjche** [microsoft/vscode-cpptools#4966]
**Type: LanguageService**

Hi, I'm not sure if this bug has been reported before.

I've noticed that the autocomplete engine is not finding the references for struct initialization with the "dot notation". 
I believe this notation is only supported from C99 and beyond (please correct if I'm wrong).

Thanks for your attention.

**Bug description**
- OS and Version: Windows 7 Professional.
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.26.3

Given a struct like this:
```C
typedef struct sample_tag
{
    uint8_t field1;
    uint8_t field2;
    uint16_t field3;
} sample_struct_t;
```
When trying to initialize an assigned variable of the given struct type, using the dot notation like:
```C
sample_struct_t s = 
{
    .field1 = 1,
    .field2 = 255,
    .field3 = 65000
};
```
The autocomplete function is not finding the references after writing the dot each time.
Otherwise, the fields are found just fine when assigning them individually, such as:

```C
s.field1 = 1;
```

**To Reproduce**

1. Define a struct type.
2. Declare a variable on such structure using the dot initializer.
3. Press ctrl+space (depending on shortcuts) to kickstart the autocomplete function.
4. No references found.

**Expected behavior**
The field references should be found.

**Screenshots**

![image](https://user-images.githubusercontent.com/43921252/74463872-1d118f00-4e58-11ea-8c4f-96d639c4b8d1.png)

**Additional context**
I have only tested on C, not C++, so I'm not quite sure if the same issue happens there.

**Comment by Colengms** [comment]
Hi @serjche .  Thanks for reporting this.  I was able to repro this issue with Visual Studio as well.  (The C/C++ Extension for VS Code shares common code for IntelliSense with Visual Studio).  I've opened a bug against VS here: https://developercommunity.visualstudio.com/content/problem/917598/struct-dot-initializer-does-not-trigger-auto-compl.html

**Comment by serjche** [comment]
Hi @Colengc, thanks for the quick response :).

**Comment by Colengms** [comment]
Taking this out of tracking, as the VS issue has been fixed, but the issue still repro's with the C/C++ Extension v1.1.0-insiders.

**Comment by sean-mcmanus** [comment]
I'm seeing this as fixed.

**Comment by sean-mcmanus** [comment]
It's not fixed at file scope, see https://github.com/microsoft/vscode-cpptools/issues/6316
