### ISSUE TITLE
Intellisense auto-complete is very slow for larger files

### ISSUE THREAD

**Issue by t0ni0** [microsoft/vscode-cpptools#4967]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Enterprise
- VS Code Version: 1.42.0
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is: After files are done parsing and Intellisense has updated (both flame and database icons have disappeared), auto-completion is very slow and takes upwards of 10 seconds to resolve even variables defined in scope.

**To Reproduce**

After waiting for parsing and Intellisense update, simply start typing a variable or a type and hit <kbd>ctrl</kbd>+<kbd>space</kbd>. The pop-up will display "Loading..." for a very long time and the language server process will be taking up maximum cpu for that time. Once it is done, the code completion suggestions *may* be very snappy for the few following statements, but almost never when inserting a new line. Given for example:
``` cpp
int numberA, numberB, numberC;
numberA = numberB + numberC;
```
Writing the second line will take a long time to suggest completion for `numberA` but may or may not take a long time for `numberB` or `numberC`. Please see gif below, and appologies for the length of it.

**Expected behavior**

I expect suggestions to come quicker especially since the caching process seems to have been completed. In this state, the auto-completion is unusable.

**Screenshots**

![cpptools-issue](https://user-images.githubusercontent.com/6692437/74473407-8a7de980-4e71-11ea-8a5e-c84623c044c5.gif)

**Additional context**

- Settings are default settings, although I have also tried setting include paths manually and removing the compiler path (msvc) with no difference. Also tried changing intellisense mode, but I do not really want the tag parser.
- This example I would say has a medium amount of includes, the size of the page file at %LocalAppData%\Microsoft\vscode-cpptools\ is 60MB. For a file that results in a 15-20MB page file, this problem is not observed, suggestions are much quicker and usually take at most 2 seconds.
- Go to definition and hovering over variables works consistently.
- My issue sounds a lot like #1914 but I'm unsure if that one was resolved.

**Comment by sean-mcmanus** [comment]
Which process is using the CPU? Microsoft.VSCode.CPP.Extension or Microsoft.VSCode.CPP.IntelliSense.Msvc?

Can you run C/C++: Log Diagnostics with that file open? What memory usage is reported and how many include paths?

Does changing the includePath setting to not use "**" (recursive includes) make it faster, e.g. if you just use the explicit list of include paths shown from the Log Diagnostics command? Sounds like you may have tried that already?

**Comment by sean-mcmanus** [comment]
Also, how many lines is the file?

Also, what is your intelliSenseCacheSize setting? (sounds like the default of 5 GB)

**Comment by t0ni0** [comment]
Hello Sean, thanks for the quick response.

> Which process is using the CPU? Microsoft.VSCode.CPP.Extension or Microsoft.VSCode.CPP.IntelliSense.Msvc?

Microsoft.VSCode.CPP.IntelliSense.Msvc which revs up to about 20% CPU for the duration of the "Loading..."

> Can you run C/C++: Log Diagnostics with that file open? What memory usage is reported and how many include paths?

Under translation unit configuration, it says 52MB, and I have 16 include paths of which 7 are Microsoft. The rest are part of my workspaceFolder. My whole project is approximately 20k lines.

> Does changing the includePath setting to not use "**" (recursive includes) make it faster, e.g. if you just use the explicit list of include paths shown from the Log Diagnostics command? Sounds like you may have tried that already?

I just tried that and removing everything from the include directories with "**" and pasting the output from Log Diagnostics has helped reduce the time from ~15sec to ~10sec for this file. So definitely an improvement but still quite slow.

> Also, how many lines is the file?

This file is 408 lines at the moment, which is pretty small, but I feel like the lag is mostly related to the amount of includes.

> Also, what is your intelliSenseCacheSize setting? (sounds like the default of 5 GB)

Yes I have it at the default value and the only overrides I have in my user settings.json are:
```json
"C_Cpp.loggingLevel": "Debug"
"C_Cpp.updateChannel": "Insiders"
```

Other thoughts: I cannot say exactly when this issue started occuring but it is not new. I have just recently tried to work on this project with VS Code but I remember a few months ago and it was there. 2 years back I remember not having an issue at all with the same code base.

Does file access speed play a big role in this after Intellisense is done updating? Come to think of it, in that time span, a corporate real-time monitoring antivirus and DLP were updated/installed on my system. Do you think it could have that big of an impact on this?

**Comment by sean-mcmanus** [comment]
Okay, thanks for the info. Your scenario is expected to be fast for IntelliSense processing, so it looks like you may be hitting some unexpected performance bug. It's possible the virus monitoring could affect the performance.

Can you attach a debugger to the IntelliSense process to get a call stack when it's using the high CPU during autocompletion? Windows binaries have symbols available in VS Code by setting your "symbolSearchPath" to "https://msdl.microsoft.com/download/symbols".

Do you know if this repros with other more simpler workspaces?

Can you set C_Cpp.loggingLevel to "Debug" and then look at the logs in the "C/C++" output pane when you start typing for completion? When you do that, approximately how many times does it show "offering completion" and "auto_complete::handle_completion" and "sending X changes to server" and "queuing IntelliSense update" and "tag parsing" -- if you see those messages more than 1-2 times after typing "numberB" then that could be causing the problems. Or if you see it get stuck for a long time after outputting a certain message, then that message could be related to the cause.

Also, if "Update IntelliSense time" shows a large number, that could be the issue.

**Comment by t0ni0** [comment]
Thanks for the suggestions. When I have some more time soon I'll try the debugger and try to isolate the issue as best as I can. For now, looking at the debug logs, the hang up is always right after this sequence:
```
auto_complete::handle_completion: file:///.../MyFile.cpp (xxx:x)
Offering completion
sending X changes to server
```
And the changes do seem to queue up, so for example when I type "num" all at once, it first sends 1 change to the server, presumably for "n", then idles for a few seconds, then I see "Request canceled",  sends 2 changes for "um" and then after enough time the suggestions appear. Intellisense update time is also pretty constant at about 0.26 seconds.

While attached to the Intellisense process, the only output I get is an exception that gets thrown right after I hit <kbd>;</kbd> at the end of a statement. On the extension side I get:
```
idle loop: reparsing the active document
Checking for syntax errors: file:///.../MyFile.cpp
Queueing IntelliSense update for files in translation unit of: D:\...\MYFILE.CPP
cpptools/cpptools_finishUpdateSquiggles
```
At the same time the language server outputs:
```
Exception thrown at 0x752319B2 in Microsoft.VSCode.CPP.IntelliSense.Msvc.exe: Microsoft C++ exception: a_cfe_exception at memory location 0x00E9FD33.
The thread 25468 has exited with code 0 (0x0).
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
WER/CrashAPI:2658: ERROR Invalid args, too  big block
```
And the reported Intellisense update time is approximately 10s. This does not happen on a smaller file ~50 lines in the same project, although Intellisense for it is still slow. I will try to investigate check the call stack next.

**Comment by t0ni0** [comment]
Just tried with other similar sized repos and cannot reproduce this slowness. I will take some time to try to narrow down the cause on this particular repo.

**Comment by sean-mcmanus** [comment]
It looks like the IntelliSense updating is really slow for your TU, possibly due to usage of certain template libraries that take a long time for us to parse. Another user reported a similar issue at https://github.com/microsoft/vscode-cpptools/issues/3907 (looks like we never followed up on investigating that repro or the profiler logs). This parsing code is shared by VS, so it's likely they have the same performance issue, unless our handling of edits is less ideal.

The exception and CrashAPI logging is normal and not a bug.

The call stack will likely show parsing code is being done.

**Comment by t0ni0** [comment]
Thanks for taking the time to investigate this with me. I have determined that the cause of my problem was indeed DLP and Anti-Virus software causing the Intellisense server process to slow down to snail pace. The DLP software actually spawns a monitoring thread for every working thread as I could see in the call stack. I think the only solution for me is to request an exemption for the extension.
