### ISSUE TITLE
Unable to read file when click problems 

### ISSUE THREAD

**Issue by zmt0516** [microsoft/vscode-cpptools#4975]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Go to 'Problems'
2. Click on 'Warning line'
3. See error
![2020-02-17](https://user-images.githubusercontent.com/4460150/74645973-ecc33c80-5146-11ea-8fde-3f13b97aac41.png)

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by zmt0516** [comment]
I use mingw-64 as C++ compiler on Win10.

The compilation process and results are fine.

However, I can not locate the error or warning by click the line of problems console.

**Comment by Colengms** [comment]
Hi @zmt0516 .  I see that the path is incorrect - it looks like the entire path is repeated except for the filename.  However, I'm not able to easily repro.

In the images you posted, it looks like you had clicked on a problem entry reported by the gcc problem matcher (as it says gcc at the end of the line).  Does this repro only on problems reported gcc, or does it also repro on the lines that indicate "C/C++" ?

The problem matcher for gcc is rather simple.  It basically just capture output from gcc.

```
    "problemMatchers": [
      {
        "name": "gcc",
        "source": "gcc",
        "owner": "cpptools",
        "fileLocation": [
          "relative",
          "${workspaceFolder}"
        ],
        "pattern": {
          "regexp": "^(.*):(\\d+):(\\d+):\\s+(?:fatal\\s+)?(warning|error):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "message": 5
        }
      }
    ],
```

Could you check if the output from gcc contains the correct or incorrect path?

**Comment by tlwetteronline** [comment]
Hi @Colengms, 

I think I have the same problem, so perhaps I can answer your last question. In the embedded terminal (bash with Ubuntu in my case), I get the correct path, and can navigate to the code via Alt+Click. But in the problems tab, the workspace path seems to be prepended, e. g.:

Terminal:
g++-8 -Wall [...] -c /home/nowcastglobal/prozess/nowcastweather/src/io/fileConfiguration.cpp -o /home/nowcastglobal/prozess/nowcastweather/debug/obj/home/nowcastglobal/prozess/nowcastweather/src/io/fileConfiguration.o
/home/nowcastglobal/prozess/nowcastweather/src/io/fileConfiguration.cpp:30:11: error: found ‘:’ in nested-name-specifier, expected ‘::’
 const util:TString TFileConfiguration::mEmptyString{};

Problems tab:
fileConfiguration.cpp home/nowcastglobal/prozess/nowcastweather/src/io
found ‘:’ in nested-name-specifier, expected ‘::’ gcc [30, 11]

I also have errors in the problems tab, which are reported by intellisense. In these cases only the relative path src/io is shown and clicking succeeds.

Is it possible that the problem matcher should be changed to recognize the fileLocation as absolute path and if you think so where can I do this?

**Comment by zmt0516** [comment]
Thank you very much @Colengms .
You gave me ideas for solving this question.
I added this in tasks.json and everything is OK now.
`
"problemMatcher":  {
                "base": "$gcc",
                "fileLocation": [
                    "absolute"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "message": 4
                }
            },
`

**Comment by ak-karimzai** [comment]
@zmt0516  can u show me your tasks.json file i try to do something like that but no result

**Comment by ak-karimzai** [comment]
```
{
	
	"version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "C/C++: gcc.exe build active file",
            "command": "C:\\msys64\\mingw64\\bin\\gcc.exe",
            "args": [
                "-g",
                "-Wall",
                "-Werror",
                "-pedantic",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
			"problemMatcher": { "base": "$gcc",
				"fileLocation": [ "absolute" ],
				"pattern": { "regexp": "^(.*):(\\d+):(\\d+):\\s+(.*)$",
					"file": 1,
					"line": 2,
					"column": 3,
					"message": 4
					} 
				},
            "group": {
                "kind": "build",
                "isDefault": true
			}
        }
    ]
}
```
