### ISSUE TITLE
C++ Intellisense does not apply code conformance

### ISSUE THREAD

**Issue by TheMarkie** [microsoft/vscode-cpptools#4980]
I've recently migrated my C++ project from VS to VS Code. While I find that VS Code already handles highlighting and compiling pretty well, Intellisense is kinda lacking and broken.

For example: My codebase is old and require these options:
- `/Zc:wchar_t-`
- `/Zc:forScope-`
- `/Zc:inline`
- `/Zc:implicitNoexcept-`

Compiling using MSBuild or CL is completely fine, only highlighting and error reporting is problematic. I've tried the `compilerArgs` setting in `c_cpp_properties.json` but it doesn't seem to be designed for this. I've tried putting in a shortcut (that runs cl.exe with the proper parameters) but that doesn't work either.

Any idea?

**Comment by sean-mcmanus** [comment]
We haven't added support for those cl.exe compiler args/flags.

**Comment by TheMarkie** [comment]
Thank you for the quick reply.

The goal should be to allow the Intellisense to work almost 1 to 1 to how the code is compiled, no? I'm not sure how the Intellisense works exactly but if fundamentally it just parses the output from cl.exe then we cacn have an "experimental" option that allows all kinds of args in compilerArgs or the use of a command file.

Maybe since MSBuild is available for C++ now, allowing it (which kinda automates cl args) would be the more elegant solution.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders
