### ISSUE TITLE
[LLDB]The console windows is not closed after debugging stopped

### ISSUE THREAD

**Issue by caslan** [microsoft/vscode-cpptools#499]
Sample code attached.

 

Configuration:

 

VSCode(Stable) + cpptools(0.8.0)

 

Steps to repro:

1) Compile the sample code: clang++ -g a.cpp b.cpp c.cpp -lpthread

2) Open the sample code folder in vsocde.

3) Set a BP at line 40 in c.cpp

4) Set debug type to Launch, then F5 break.

5) stop debugging

 

Expected:

The console window will be closed also after debugging stopped.

 

Actual:

The console windows is not closed after debugging stopped.
[test.zip](https://github.com/Microsoft/vscode-cpptools/files/784832/test.zip)

**Comment by pieandcakes** [comment]
This is a configuration in Terminal and isn't controlled by the extension.
