### ISSUE TITLE
Switch to using new VS Code WorkspaceEditMetadata API for Rename

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#4990]
VS Code has added a new API for previewing refactor operations.  https://github.com/microsoft/vscode/issues/77728

 Creating this issue to track switching to using it instead of our own Rename UI.

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
