### ISSUE TITLE
Remap directory names inside include directive

### ISSUE THREAD

**Issue by mikepelley** [microsoft/vscode-cpptools#4991]
**Type: LanguageService**

Our build system copies source files and includes into certain directories and then does the build. A consequence of this is that some .c files have includes like this:

`#include <subdir/myapp.h>`

In this case, "subdir" only exists in the build tree after a build has been implemented. In the source tree there is an include directory that contains myapp.h directly.

Is it possible for intellisense and the tag parser to find these includes in the source tree when the subdir is not present? I imagine a "remap directory name" option or something in the settings. Currently I just point to the build include directory, but if I edit the header file and the source file simultaneously (e.g. to change a prototype) I don't see errors properly until I build.

Thanks.

**Comment by bobbrow** [comment]
Are you able to use symlinks to achieve your goal?

**Comment by mikepelley** [comment]
Yes, symlinks do work but this is a large codebase so I would have to create many symlinks for the various components. For now I just stay aware that the header file lags and added the build path to the include vars, so they get updated when I do a build.
