### ISSUE TITLE
Intellisense not work if not install visual studio with C/C++ compiler

### ISSUE THREAD

**Issue by hellyzh** [microsoft/vscode-cpptools#4994]
Intellisense not work as below, but if I installed visual studio with C/C++ compiler, it can work well.
The "compilerPath" I used is g++.exe, not visual studio. So visual studio should not give impact to intellisense. Please check  diagnostic logs.

![image](https://user-images.githubusercontent.com/49181894/75002090-4789ca80-549e-11ea-8cfc-1e617bd46fcb.png)

[diagnostics_notwork_not_installed visualstudio.txt](https://github.com/microsoft/vscode-cpptools/files/4234161/diagnostics_notwork_not_installed.visualstudio.txt)
[diagnostics_work_installed visualstudio.txt](https://github.com/microsoft/vscode-cpptools/files/4234162/diagnostics_work_installed.visualstudio.txt)

**Comment by Colengms** [comment]
Hi @hellyzh .  Both of the logs you posted appear to be configured identically, other than being from different folders/projects.  Could there have been another change to your system other than installing VS?  Or, could there have been a common dependency that installing VS may have altered?  Are there files still present under C:\USERS\HELLY\APPDATA\LOCAL\ARDUINO15\PACKAGES\AZ3166\HARDWARE\STM32F4\1.6.5\ ?
There are paths missing from your repro case that would have been found and included in the IntelliSense configuration if include paths were successfully resolved.  It looks like nothing under that path was successfully detected.

There is a squiggle on the line immediately prior to the one you hovered over in the image you posted.  Could you provide the error message on that prior line?  It should point to the header that is not found (which may be deeply nested).  Perhaps what was not found was "mbed.h" ?  Is that still where you would expect it to be?

**Comment by hellyzh** [comment]
1. Confirmed files are present under C:\USERS\HELLY\APPDATA\LOCAL\ARDUINO15\PACKAGES\AZ3166\HARDWARE\STM32F4\1.6.5\
2. The prior line shows not found "mbed.h". But mbed.h is under the folder. And nothing changed, after installed Visual studio C/C++ compiler, intellisense will work, I tested on two servers.

Please check screenshots:
A. not install visual studio:
![image](https://user-images.githubusercontent.com/49181894/75087101-4aa4b980-5577-11ea-81a6-ab38bb56a776.png)
B. installed visual studio:
![image](https://user-images.githubusercontent.com/49181894/75087110-5b552f80-5577-11ea-9d02-4f7a2f7ba856.png)

**Comment by Colengms** [comment]
Hi @hellyzh .  Are your logs from different machines, or the same machine?  They are 9 minutes apart, use different paths (START2 and START3), and the repro is the second one (9 minutes later).  Am I correct to interpret that as:
 * VS was initially installed
 * There was no repro with the first project (START2)
 * VS was uninstalled
 * The second project (START3) repro'ed.

Can you repro with START2, or only with START3?  If you could provide logs with and without the repro, using the same project/path, that would help us rule out potential differences between these 2 projects.

Can you enable logging using the following, and provide the output of the C/C++ channel, with and without the repro?
`"C_Cpp.loggingLevel": "Debug"`

**Comment by hellyzh** [comment]
I used same machine, same project. Intellisense works after installed VS and reset intellisense database.
1. before installing VS:
[diagnostics_beforeVS.log.txt](https://github.com/microsoft/vscode-cpptools/files/4247693/diagnostics_beforeVS.log.txt)
[c_c++_beforeVS.log.txt](https://github.com/microsoft/vscode-cpptools/files/4247694/c_c%2B%2B_beforeVS.log.txt)
![image](https://user-images.githubusercontent.com/49181894/75207779-ae67f600-57b4-11ea-9280-56c2c8fe2c07.png)

2. after installed VS:
[c_c++_afterVS_beforeresetintellisensedatabase.log.txt](https://github.com/microsoft/vscode-cpptools/files/4247695/c_c%2B%2B_afterVS_beforeresetintellisensedatabase.log.txt)
[c_c++_afterVS_resetintellisensedatabase.log.txt](https://github.com/microsoft/vscode-cpptools/files/4247696/c_c%2B%2B_afterVS_resetintellisensedatabase.log.txt)
[c_c++_afterVS.log.txt](https://github.com/microsoft/vscode-cpptools/files/4247697/c_c%2B%2B_afterVS.log.txt)
[diagnostics_afterVS.log.txt](https://github.com/microsoft/vscode-cpptools/files/4247699/diagnostics_afterVS.log.txt)
![image](https://user-images.githubusercontent.com/49181894/75207795-bb84e500-57b4-11ea-8f2c-f74601fba757.png)
![image](https://user-images.githubusercontent.com/49181894/75207809-c2abf300-57b4-11ea-8a3b-a8f35c1b112e.png)

**Comment by hellyzh** [comment]
Since I made a VM snapshot, I restore it to not installing VS status, and tried reset intellisense database. Intellisense still not work, logs as below.
[c_c++_beforeVS_resetintellisensedatabase.log.txt](https://github.com/microsoft/vscode-cpptools/files/4247748/c_c%2B%2B_beforeVS_resetintellisensedatabase.log.txt)

**Comment by Colengms** [comment]
Hi @hellyzh .  I think I'm able to repro the issue.  What I'm seeing does not appear to be specific to installation of VS.  But, the existance of VS changes the timing of our initialization (because we broke CL.exe if found on the system), making the repro more likely to happen.

The good news is: I'm no longer able to repro the issue with our latest code in development (which we expect to release as an 'Insiders' build, within the new few days).

When you see this issue, could you try opening the file that cannot be found, allowing several seconds for our extension to 'tag parse' the file (and files it includes), then using the `Developer: Reload Window' command (or re-launching VS Code).  Let me know if that does not work around the issue.

**Comment by hellyzh** [comment]
I tried open the mbed.h for serveral seconds and run "Developer: Reload Window", looks like not work.
![image](https://user-images.githubusercontent.com/49181894/75308784-3d930d80-588a-11ea-84e4-0a6049318d3a.png)

**Comment by Colengms** [comment]
Hi @hellyzh .  I see an anomaly in the last image you posted.  With "mbed.h" open, the first error you are seeing is that "mbed.h" cannot be opened.  The only way I know this is possible is with use of a `#include_next` statement.  Could you check if that error is associated with a `#include_next` statement?  If so, could you check for locations of other "mbed.h" files?

**Comment by hellyzh** [comment]
There is no `#include_next` statement in mbed.h, but I found if I double click on the file mbed.h to open it, the first problem for Arduino.h will change from `cannot open source file "mbed.h"` to `cannot open source file "mbed_stats.h"`.
![image](https://user-images.githubusercontent.com/49181894/75403978-2b75a580-5944-11ea-96a5-ff1d8a552722.png)
 If open mbed_stats.h, the problem will change back to `cannot open source file "mbed.h"`
![image](https://user-images.githubusercontent.com/49181894/75403984-30d2f000-5944-11ea-938f-3bd851be7c8b.png)

**Comment by sean-mcmanus** [comment]
Our latest Insiders release has a new multi-root implementation (which fixes this bug): https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders. Please let us know if you find any multi-root-related bugs or regressions so we can prioritize fixing those for 0.27.0.

**Comment by hellyzh** [comment]
Confirmed this issue has been fixed in the insider release.
