### ISSUE TITLE
Setting default configurations available to all folders

### ISSUE THREAD

**Issue by alejnp** [microsoft/vscode-cpptools#4995]
Currently, when you open up a folder and it loads the extension, you are moved to a configuration based on your system. For example on Linux, you get the following:

```json
{
  "name": "Linux",
  "defines": [],
  "compilerPath": "/usr/bin/gcc",
  "compileCommands": "${workspaceFolder}/build/compile_commands.json"
}
```

In this configuration, you can set things like the IncludePath or different Defines, and you can modify it on `.vscode/c_cpp_properties.json` to include additional configurations.

Is it possible to define a User-global list of available configurations so you don't have to redefine or copy one previous configuration file to the current open folder in order to select a configuration?

My use case is creating several different projects living on different folders but using the same IncludePath. Current workaround would be having a "template" folder and basing every new projects on that template folder.

**Comment by Colengms** [comment]
Hi @Alxe .  Would setting default configuration values in your user/global settings.json help?

```
    "C_Cpp.default.compilerPath": "...",
    "C_Cpp.default.includePath": [ "..." ],
    ...
```

**Comment by alejnp** [comment]
Unfortunately, no, it wouldn't help. That setting "just" pastes one ore more paths to the default IncludePath.

My use case is more related to versioning. A library may have several versions, with different headers/interfaces sharing the same header hierarchy, with a different root path i.e. `${Root Folder}/mylib-${Version}/same/name/space.h`.

I want to be able to choose which version is used in my configuration, but I don't want to create the same configurations over and over when creating a new project.

Hope this puts some more perspective into things, and thanks for hearing me out :)

**Comment by alejnp** [comment]
Hello, any update on this feature? I know this request may be a bit of a niche, so I'd like to collaborate on my free time if possible.

Any pointers as to where to look? Does "c_cpp_properties.json" inherit from anywhere else? An example properties file with configuration would be as follows:

```json
{
    "configurations": [
        {
            "name": "Linux",
            "defines": [],
            "compilerPath": "/usr/bin/gcc"
        },
        {
            "name": "Version 5",
            "defines": [
                "MyDefine=V5"
            ],
            "compilerPath": "/usr/bin/gcc",
            "includePath": [
                "/usr/share/MyLib-5/include/**"
            ]
        },
        {
            "name": "Version 8",
            "defines": [
                "MyDefine=V8"
            ],
            "compilerPath": "/usr/bin/gcc",
            "includePath": [
                "/usr/share/MyLib8/include/**"
            ]
        }
    ],
    "version": 4
}
```

Doing so, les me choose which configuration to choose on the fly.
![image](https://user-images.githubusercontent.com/3256915/78659982-995ea680-78cc-11ea-8d7d-b84d3d249954.png)
![image](https://user-images.githubusercontent.com/3256915/78660035-aed3d080-78cc-11ea-9a3a-8654f97d62ec.png)

In essence, I would like to be able to configure some of those configurations globally, as I create several workspaces (folders) for different things, all depending on the same library.

**Comment by sean-mcmanus** [comment]
There isn't any update (it hasn't been added to a pending milestone).

Most of our configuration processing is at https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/configurations.ts . Warning: It's possible master may be in an unusable state if changes have been made that require an updated cpptools binary that we haven't published yet. One workaround may be to create a branch off of the release branch, or let us know and we could publish a new binary.

I'm unclear on what the complete design proposal is. Would there be some setting like C_Cpp.default_cpp_properties.json that points to a c_cpp_properties.json? Any other commands or UI changes?

**Comment by alejnp** [comment]
> I'm unclear on what the complete design proposal is. Would there be some setting like C_Cpp.default_cpp_properties.json that points to a c_cpp_properties.json? Any other commands or UI changes?

More likely the first. From what I could gather from the source file linked, it appears that `CppProperties` is a representation of the `.vscode/c_cpp_properties.json` file.

I assume that this file is checked and parsed whenever the extension loads up in a workspace. When it's not found, it's generated with some default values. On my Linux machine, the default would go as:
```json
{
    "name": "Linux",
    "defines": [],
    "compilerPath": "/usr/bin/gcc"
}
```

My idea is being able to alter those defaults, either overriding or appending possible default configurations. No commands or UI modifications.

**Comment by sean-mcmanus** [comment]
That seems fine to me. @bobbrow Any thoughts?

**Comment by bobbrow** [comment]
We have the ability to set additional environment variables in the configuration file itself, but that will only apply for the current folder.

```
{
    "env": {
        "RootFolder": "/usr/share"
    },
    "configurations": [
        {
            "name": "Linux",
            "defines": [],
            "compilerPath": "/usr/bin/gcc"
        },
        {
            "name": "Version 5",
            "defines": [
                "MyDefine=V5"
            ],
            "compilerPath": "/usr/bin/gcc",
            "includePath": [
                "${RootFolder}/MyLib-5/include/**"
            ]
        },
        {
            "name": "Version 8",
            "defines": [
                "MyDefine=V8"
            ],
            "compilerPath": "/usr/bin/gcc",
            "includePath": [
                "${RootFolder}/MyLib8/include/**"
            ]
        }
    ],
    "version": 4
}
```

We could potentially add a `C_Cpp.default.env` which would allow you to define an `env` that is available for all projects.
