### ISSUE TITLE
Error: Cannot find module 'vscode-nls'

### ISSUE THREAD

**Issue by davidgtl** [microsoft/vscode-cpptools#4997]
**Type: LanguageService**

**Describe the bug**
- OS and Version: 5.3.0-28-generic #30~18.04.1-Ubuntu
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): No other extensions
- A clear and concise description of what the bug is.

Syntax highlight and code navigation are not working

**To Reproduce**

1. Open any C/C++ project
2. Open any file
3. Write an illegal line or go to definition of any function

**Expected behavior**

The syntax mistake being underlined in red/going to a functions header/body
**Screenshots**

**Additional context**

I found a stack trace in the Extensions Log:
`[2020-02-21 18:08:14.981] [exthost] [error] Activating extension ms-vscode.cpptools failed due to an error:
[2020-02-21 18:08:15.020] [exthost] [error] Error: Cannot find module 'vscode-nls'
Require stack:
- /home/david/.vscode/extensions/ms-vscode.cpptools-0.26.3/dist/main.js
- /snap/code/25/usr/share/code/resources/app/out/vs/loader.js
- /snap/code/25/usr/share/code/resources/app/out/bootstrap-amd.js
- /snap/code/25/usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
	at Function.Module._load (internal/modules/cjs/loader.js:531:27)`

**Comment by Colengms** [comment]
Hi @davidgtl .  Has this issue been occurring since the extension was installed?  We have been receiving reports of the extension not getting properly installed, perhaps due to VS Code being closed while the install was still in progress.  Could you try uninstalling it, closing VS Code, ensuring the extension directory is removed from the install location (likely in: ~\.vscode\extensions), and reinstalling it?

**Comment by davidgtl** [comment]
"Have you tried turning it off and on again?" Thanks! worked like a charm. 
I had tried to reinstall both the extension and the application, but forgot about the existence of ~/.vscode. I don't believe it ever worked properly on this machine, I had just basic syntax highlighting and just assumed it was a misconfiguration problem on my part
