### ISSUE TITLE
Yet another erroneous "expression must have a constant value" intellisense problem

### ISSUE THREAD

**Issue by FranciscoPombal** [microsoft/vscode-cpptools#4999]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04 (latest updates and HWE)
`$ uname -isrvmop`: `Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): Issue persists even with all other extensions disabled
- A clear and concise description of what the bug is:

A simple `constexpr` assignment generates an Intellisense error when there shouldn't be one, since the code compiles without warnings on both `gcc` and `clang` even when using `-Wall -Wextra -Wpedantic`. See minimal reproduction example below.

**To Reproduce**

Minimal example:

```cpp
#include <cmath>

int main(int argc, char const *argv[])
{
    constexpr double i = std::log10(1);
    return 0;
}
```

Result: screenshot below.

**Expected behavior**

No error.

**Screenshots**

![image](https://user-images.githubusercontent.com/17580742/75110609-1b9a5080-5628-11ea-8cab-b6ff64850eb5.png)

**Additional context**

Similar to the following fixed issue: https://github.com/microsoft/vscode-cpptools/issues/2939

**Comment by Colengms** [comment]
Hi @FranciscoPombal .  I believe this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4736 , tracked by https://developercommunity.visualstudio.com/content/problem/854941/intellisense-shows-squiggle-for-use-of-gcc-compile.html in VS.  You may want to add a comment and/or upvote that issue.

In your case, log10() is not declared as constexpr, yet the compile is able to resolve the call into a constant expression when passed a constant value.

**Comment by FranciscoPombal** [comment]
@Colengms Thanks. Closing as duplicate.
