### ISSUE TITLE
C++ Attach on Linux Mint 17.3 does not work.

### ISSUE THREAD

**Issue by jgminder** [microsoft/vscode-cpptools#5]
I attempted to use the C++ Attach feature of Visual Studio Code using gdb on Linux Mint 17.3 and it did not work. I created a simple helloworld application. Launching the application for debugging (C++ Launch) worked fine but attaching to an existing process did not. I placed a cin statement in to ensure it was paused while I did the attach. Here's the console output:

=thread-group-added,id="i1"
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word".
help
error while processing request 'evaluate' (exception: Specified argument was out of the range of valid values.\nParameter name: handle)

**Comment by delmyers** [comment]
@jgminder Thanks for the bug report. When you were attaching, did you attach to the same process that you used to launch? Was the program compiled with debug information, and what were the optimization options? We have seen some issues with applications that don't have correct debug symbols compiled into the binaries, with similar symptoms.

**Comment by jgminder** [comment]
I made sure it was the same process I launched.  All optimizations were removed and I ran gdb standalone without issue on the program so debug symbols should not be the issue.

**Comment by feliperobledo** [comment]
had a similar problem. I've gone through almost all of the documentation to install MacPorts and Quartz to get GDB to work, but it just wont attach to the process. I get the same output as jgminder and my breakpoints are never hit.

**Comment by pieandcakes** [comment]
Sorry for the delay. @jgminder Can you try it again? I'm using Linux Mint 7.3 in conjunction with VSCode 1.3.1 and our 0.7.1 extension and the attach seems to work fine. I notice I get a prompt to elevate as SU and I entered my password and i'm wondering if you are seeing that also

**Comment by pieandcakes** [comment]
@ProjectDestiny Are you trying to do this on Mac or on Linux Mint?

**Comment by pieandcakes** [comment]
It seems this has gone stale. Please comment or reopen this issue if it is still occurring.
