### ISSUE TITLE
Can vscode dynamically adjust the follow-fork-mode?

### ISSUE THREAD

**Issue by huanghantao** [microsoft/vscode-cpptools#5000]
My program looks like this: I have a master process, the master process forks a manager process, and the manager process forks the worker process. 
Assuming that I set the follow-fork-mode child, only breakpoints can end up in the worker process. 
Can I set the follow-fork-mode child to stop the breakpoint in the manager process, and then set the follow-fork-mode parent to stop the breakpoint in the manager. Because I just want to debug the manager process.

**Comment by pieandcakes** [comment]
This isn't something we support. In looking at the `gdb` [Fork](https://sourceware.org/gdb/onlinedocs/gdb/Forks.html) documentation, `follow-fork-mode` doesn't allow for you to debug that way.

 You want to set `detach-on-fork` mode set to `off` and then following the instructions [here](https://sourceware.org/gdb/onlinedocs/gdb/Inferiors-and-Programs.html#Inferiors-and-Programs) to switch between the two. This is an area that is not supported so you'd have to take a look at what you would need to issue in the `debugConsole` to get it all working right. I imagine in this case the UI isn't going to be correct either as we're only expecting one inferior at a time.
