### ISSUE TITLE
Custom browse configuration path irregularities

### ISSUE THREAD

**Issue by RobRuckOB** [microsoft/vscode-cpptools#5011]
**Type: LanguageService**
Whilst looking at another unrelated issue with the C/C++ extension I turned on debug logging and saw something unusual in the paths listed in the "Custom browse configuration received:" section. Specifically, there are repeated lower-cased versions of paths (I can just about believe that's intentional due to platform differences) and/or paths with the workspace folder appended twice (I can't think of any reason for this). If this is a somewhat scattergun approach to finding things, that's not ideal, but it also doesn't seem to work quite right - I see some paths in the lower case or repeated style that don't appear correctly in the list of paths at all.

- OS and Version: OSX 10.14.6
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3

**To Reproduce**
My c_cpp_properties.json:
`{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "~/.conan/data/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}`
I simply start up VS Code, and the paths issue is visible in the start up debug output from the extension. (I've verified the issue persists even without the CMake Tools extension being used as the configuration provider.

**Expected behavior**
Only valid paths are set in the browse configuration.

**Screenshots**
Lower casing of path (Notice /users):
<img width="442" alt="image" src="https://user-images.githubusercontent.com/42342894/75325319-83db7300-5870-11ea-9d8c-a089a64b6200.png">

Lower casing of path and repetition of the workspace folder:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/42342894/75324793-9c975900-586f-11ea-8751-4c43d694eea9.png">

Subsequent errors:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/42342894/75325022-fdbf2c80-586f-11ea-92d5-f455b535c041.png">

**Comment by Colengms** [comment]
Hi @RobRuckOB .  The "Custom browse configuration received:" in the log is referring to the custom configuration provider, and a browse configuration that we received from.  This looks like an issue with CMake Tools extension.  If you are seeing the issue without the CMake Tools extension, which other config provider were you using?  We would not log this message if we did not receive it from a config provider.

**Comment by RobRuckOB** [comment]
Thanks @Colengms, that was my first suspicion (CMake Tools, I mean), so I made sure to remove it from my c_cpp_properties.json file. But I guess that wasn't enough to properly clean it out.

I'll take this bug over to the CMake extension, thanks for looking.
