### ISSUE TITLE
Renaming hangs IDE, takes long time to return

### ISSUE THREAD

**Issue by bonfire62** [microsoft/vscode-cpptools#5014]
**Type: LanguageService**

**Describe the bug**
- OS and Version: _Windows w/ Remote Development on linux CentOS_
- VS Code Version: _1.42.1_
- C/C++ Extension Version: _0.26.3_
- Other extensions you installed (and if the issue persists after disabling them): _disabled all extensions_
- A clear and concise description of what the bug is.
Renaming Variable take an unusual amount of time to return "Candidates for Rename" options. around 1-2 minutes.

**To Reproduce**
I hit F2 on a variable to rename, then rename variable, and IDE hangs after searching files, saying "Rename: 0/3 files confirmed. _Source: C/C++ (Extension)_" in a notification. Variabled used around 3 times and searching for the variable within the workspace returns within seconds

**Expected behavior**
Search to return candidates for rename within seconds

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
This is "by design". It has to compile the translation units the references are found in, in order to "confirm" the references. We have other issues that track improving performance. If you have the files open with the references and IntelliSense is done processing them, then it should be faster.
