### ISSUE TITLE
[MinGW]To restart debugging need hit the Restart button two times

### ISSUE THREAD

**Issue by caslan** [microsoft/vscode-cpptools#502]
Internal bug id: 266662

Configuration:

VSCode(1.5.2)+ CPP Extension(20160917.1)

 

Sample Code:

//a.cpp

#include"iostream"
using namespace std;

sleeping()
{
    while(true)
    {
        cout<<"the process is running"<<endl;
    }
}
int main()
{
    sleeping();
    return 1;
}

 

steps to repro:

1. Compile the sample code: g++ -g -O0 a.cpp -o a.exe

2. Open the source code folder in vscode

3. Change launch.json

             "program": "${workspaceRoot}/a.exe",
            "miDebuggerPath": "C:/MinGw/mingw64/bin/gdb.exe",

4. F5

5. Hit restart

6. Hit restart again

 

Expected:

Restart can run when first time hit restart

 

Actual:

Restart need double hit 

 

Investigation:

1. Collecting log  blocked by Bug:199336

2. This issue repro at hit stop

3. This issue also can repro on Cygwin

4. The current console windows can't be closed when to restart debugging

**Comment by pieandcakes** [comment]
This does not repro on 0.27.0
