### ISSUE TITLE
Semantic colorization doesn't update after deleting settings.json with colorization changes

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5023]
1. Put
```     "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "entity.name.type",
                "settings": {
                    "foreground": "#FF0000",
                    "fontStyle": "italic bold underline"
                }
            }
        ]
    }
```
in settings.json.
2. See the colors update with code
```
void myfunction(int var1, std::string var2, std::string var3)
{
}
```
3. Delete settings.json.

Bug: The colors don't update. Reload window fixes it. The new colorization implementation might fix this: https://github.com/microsoft/vscode-cpptools/issues/4992

**Comment by Colengms** [comment]
This looks like a VS Code issue.  Editing settings.json, within VS Code or externally, results in the expected onDidChangeConfiguration notification.  However, deleting the file, or copying the file to the .vscode directory, does not appear to trigger a notification.

Curiously, it looks like we get 2 invocations of file watcher events in .vscode, but not in other directories.  (This also appears to be a VS Code issue).

**Comment by Colengms** [comment]
I've opened the following issue against VS Code: https://github.com/microsoft/vscode/issues/92288

**Comment by Colengms** [comment]
Closing this as the linked bug is now closed (fixed).  Though, the issue will persist until a version of VS Code containing the fix is shipped.
