### ISSUE TITLE
Pause analysis doesn't work

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode-cpptools#5027]
**Type: LanguageService**

**Describe the bug**
- OS and Version: arch linux 5.5
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

1. Open big project
2. Click the icon with cylinder in the status bar and select Pause analysis
3. Microsoft.VSCode.CPP.Extension still consumes a lot of CPU

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @Yanpas .  Thanks for reporting this.  I can repro.

**Comment by sean-mcmanus** [comment]
Do you have files open? If files are open, that can cause parsing of possible include dependencies of that file to occur even if the "pause parsing" is used.

Also, the pausing won't start until the dependencies of the currently "in progress" source file has all its dependencies finished parsing, so it may take a few seconds to actually pause if it's parsing system headers still, for example. Is that what you're seeing?

**Comment by Yanpas** [comment]
Yes, I had several files open, after hitting pause nothing happened after a minute or so.  Compiling 5-6 files would be much faster. Intellisence began indexing after I made svn switch (changed a branch), which doesn't affect system headers. And it felt like not only open files were being processed. I don't have any logs to prove it but anyway current UX is sad.

**Comment by sean-mcmanus** [comment]
Our next release will have a fix for the "switch branch" scenario, which would reduce IntelliSense parsing (different from the workspace parsing): https://github.com/microsoft/vscode-cpptools/issues/2806 .

**Comment by bobbrow** [comment]
This behavior is expected when the dependencies of a source file have not yet been determined.  When using recursive includes (e.g. an includePath with ** in it), we require parsing dependencies so we can determine the correct include path.
