### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#5028]
Hi, I'm having a problem, would you please help to check my log? Thanks!
```
-------- Diagnostics - 2/27/2020, 6:56:25 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/ModelMeshComputer.cpp ]:
Translation Unit Configurations:
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 92664
    Memory Usage: 556 MB
    Includes:
        /Users/GfxCore/GL
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 556 MB
```

_Originally posted by @flysumo in https://github.com/microsoft/vscode-cpptools/issues/4859#issuecomment-592288622_

**Comment by bobbrow** [comment]
Is your clang version supposed to be 5.0? Do you have the correct kit selected with CMake Tools?

*Orignally posted by @sean-mcmanus in #4859*

**Comment by bobbrow** [comment]
Hi,

Thank you for your reply. My clang version is 11.0.0. How to select correct kit with Cmake Tools?

*Originally posted by @flysumo in #4859*

**Comment by sean-mcmanus** [comment]
@flysumo Can you [enable logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) and look in the logs for a reason why clang 5.0 would be getting picked up? It might be falling back to some old compiler on your machine. Your log diagnostics output should show "--clang_version=11000".

The commands are CMake: Scan for Kits and Select a Kit.

**Comment by xzhang515** [comment]
@sean-mcmanus Here is the log:
-------- Diagnostics - 2/28/2020, 12:24:38 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/ModelMeshComputer.cpp ]:
Translation Unit Configurations:
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 93264
    Memory Usage: 520 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
[ /Users/CookiesEngine.cpp ]:
    Process ID: 96911
    Memory Usage: 166 MB
    Compiler Path: /usr/bin/clang++
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 686 MB

**Comment by sean-mcmanus** [comment]
The configuration for CookiesEngine.cpp looks correct, but the ModelMeshComputer.cpp appears to have incorrect configurations. Can you check the C/C++ Output window logging for "Custom configurations received" and look if it's returning incorrect data (e.g. bad compilerPath).

**Comment by xzhang515** [comment]
where to find the "custom configurations received"? 

I tried to use intellisense in CookiesEngine.cpp. It doesn't work either.

**Comment by sean-mcmanus** [comment]
Yeah, we need info from the "C/C++" log (enabled via setting C_Cpp.loggingLevel to "Debug") and not the "C/C++ Diagnostics" log.

What symptom do you see with CookiesEngine.cpp? Is it unable to find an include file?

**Comment by xzhang515** [comment]
-------- Diagnostics - 2/28/2020, 1:53:45 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/CookiesEngine.cpp ]:
    /Users/CookiesEngine.cpp
[ /Users/ModelMeshComputer.cpp ]:
    /Users/ModelMeshComputer.cpp
    /Users/Vector3.h
Translation Unit Configurations:
[ /Users/CookiesEngine.cpp ]:
    Process ID: 177
    Memory Usage: 97 MB
    Compiler Path: /usr/bin/clang++
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 368
    Memory Usage: 571 MB
    Includes:
        /Users/GfxCore/include
        /Users/GfxCore/GL
        /Users/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 668 MB

The symptom both for CookiesEngine.cpp and ModelMeshComputer.cpp is:
1. It doesn't show me the class members of a variable. 
2. The auto completion shows me something irrelevant. e.g. 
![vscode_cpptool](https://user-images.githubusercontent.com/15230566/75590756-ee3c1100-5a32-11ea-9c3d-2bdbf7f6c7ad.png)

**Comment by sean-mcmanus** [comment]
The info in the C/C++ Diagnostics logs is insufficient. Can you provide info from the C/C++ logs described at https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server ?

Is your C_Cpp.intelliSenseEngineFallback set to "Disabled" (the default)?

**Comment by xzhang515** [comment]
-------- Diagnostics - 2/28/2020, 1:53:45 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/CookiesEngine.cpp ]:
    /Users/CookiesEngine.cpp
[ /Users/ModelMeshComputer.cpp ]:
    /Users/ModelMeshComputer.cpp
    /Users/Vector3.h
Translation Unit Configurations:
[ /Users/CookiesEngine.cpp ]:
    Process ID: 177
    Memory Usage: 97 MB
    Compiler Path: /usr/bin/clang++
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 368
    Memory Usage: 571 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 668 MB

-------- Diagnostics - 2/28/2020, 2:34:25 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/CSGOperations2.cpp ]:
    /Users/CSGOperations2.cpp
    /Users/Vector3.h
[ /Users/SpatialHashMultiRes.cpp ]:
    /Users/SpatialHashMultiRes.cpp
[ /Users/ModelMeshComputer.cpp ]:
    /Users/ModelMeshComputer.cpp
    /Users/Vector3.h
Translation Unit Configurations:
[ /Users/CSGOperations2.cpp ]:
    Process ID: 601
    Memory Usage: 285 MB
    Compiler Path: /usr/bin/clang++
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
[ /Users/SpatialHashMultiRes.cpp ]: not ready
    Process ID: 913
    Memory Usage: 5 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        CURL_STATICLIB
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 1134
    Memory Usage: 604 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 894 MB

-------- Diagnostics - 2/28/2020, 2:39:23 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/ModelMeshComputer.cpp ]:
    /Users/ModelMeshComputer.cpp
Translation Unit Configurations:
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 1486
    Memory Usage: 538 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 538 MB

C_Cpp.intelliSenseEngineFallback is set to "Disabled". I tried to set it to "Enabled", nothing changes

**Comment by sean-mcmanus** [comment]
The logging that begins with
```
-------- Diagnostics - 2/28/2020, 1:53:45 PM
```
is not the logging we need.

Can you provide the C/C++ logs?

![image](https://user-images.githubusercontent.com/19859882/75593545-8ab5e180-5a3a-11ea-8ca4-7d5cc02064a5.png)

**Comment by xzhang515** [comment]
Sorry for the mistake. Here is the log: 

-------- Diagnostics - 2/28/2020, 1:53:45 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/CookiesEngine.cpp ]:
    /Users/CookiesEngine.cpp
[ /Users/ModelMeshComputer.cpp ]:
    /Users/ModelMeshComputer.cpp
    /Users/include/g3d/Vector3.h
Translation Unit Configurations:
[ /Users/CookiesEngine.cpp ]:
    Process ID: 177
    Memory Usage: 97 MB
    Compiler Path: /usr/bin/clang++
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 368
    Memory Usage: 571 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 668 MB

-------- Diagnostics - 2/28/2020, 2:34:25 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/CSGOperations2.cpp ]:
    /Users/CSGOperations2.cpp
    /Users/include/g3d/Vector3.h
[ /Users/SpatialHashMultiRes.cpp ]:
    /Users/SpatialHashMultiRes.cpp
[ /Users/ModelMeshComputer.cpp ]:
    /Users/ModelMeshComputer.cpp
    /Users/include/g3d/Vector3.h
Translation Unit Configurations:
[ /Users/CSGOperations2.cpp ]:
    Process ID: 601
    Memory Usage: 285 MB
    Compiler Path: /usr/bin/clang++
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110000
[ /Users/SpatialHashMultiRes.cpp ]: not ready
    Process ID: 913
    Memory Usage: 5 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        CURL_STATICLIB
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 1134
    Memory Usage: 604 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 894 MB

-------- Diagnostics - 2/28/2020, 2:39:23 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/ModelMeshComputer.cpp ]:
    /Users/ModelMeshComputer.cpp
Translation Unit Configurations:
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 1486
    Memory Usage: 538 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 538 MB

-------- Diagnostics - 2/28/2020, 3:20:00 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/ModelMeshComputer.cpp ]:
    /Users/ModelMeshComputer.cpp
Translation Unit Configurations:
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 2335
    Memory Usage: 480 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 480 MB

-------- Diagnostics - 2/28/2020, 3:21:18 PM
Version: 0.26.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "",
    "configurationProvider": "vector-of-bool.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/ModelMeshComputer.cpp ]:
    /Users/ModelMeshComputer.cpp
Translation Unit Configurations:
[ /Users/ModelMeshComputer.cpp ]:
    Process ID: 2335
    Memory Usage: 480 MB
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        BOOST_NO_AUTO_PTR
        BOOST_NO_CXX14_DECLTYPE_AUTO
        NDEBUG
        NDEBUG
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 480 MB

**Comment by sean-mcmanus** [comment]
That's still the wrong log.

**Comment by xzhang515** [comment]
I have already set the c_cpp: logging level to be debug, and output window to be C/C++. 
Is this the information you needed?

cpptools/getDiagnostics: 1612
terminating child process: 63640
terminating child process: 63641

**Comment by sean-mcmanus** [comment]
There should be lots more logging. Are you using a multi-root workspace folder? In that case, we might be sending the logs to a "cpptools: subfolder" location instead (our pending Insider release fixes that).
