### ISSUE TITLE
[C++ on Mac]Step to end of a function will has a unexpected break in 32-bit app

### ISSUE THREAD

**Issue by caslan** [microsoft/vscode-cpptools#503]
Internal bug id: 236208

Sample code attached.

 

Configuration:

 

VSCode(Stable) + cpptools(0.7.1)

 

Steps to repro:

1) Compile the sample code: g++ -g a.cpp b.cpp c.cpp -lpthread -m32

2) Open the sample code folder in vsocde.

3) Set a BP at line 40 in a.cpp

4) Set debug type to Launch, then F5

5) Step into

6) Step Over 3 times

 

Expected:

Break at line 16 in a.cpp

 

Actual:

Break somethere looks like is not in my code.

 

Note that this bug can reproduce in GDB.

 

 
[test (2).zip](https://github.com/Microsoft/vscode-cpptools/files/784842/test.2.zip)

**Comment by WardenGnaw** [comment]
Won't fix since Apple is EOLing 32-bit 

https://support.apple.com/en-us/HT208436
