### ISSUE TITLE
Unable to start the C/C++ Language Server (Missing binary Microsoft.VSCode.CPP.Extension.exe)

### ISSUE THREAD

**Issue by SharquiX** [microsoft/vscode-cpptools#5032]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at c:\Users\shawn\.vscode\extensions\ms-vscode.cpptools-0.26.3\bin\Microsoft.VSCode.CPP.Extension.exe

**To Reproduce**

**Expected behavior**

I just want the notification to go away.

**Screenshots**

**Additional context**

**Comment by michelleangela** [comment]
@SharquiX Based on the error
```
Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at c:\Users\shawn.vscode\extensions\ms-vscode.cpptools-0.26.3\bin\Microsoft.VSCode.CPP.Extension.exe
```
the binary of the extension failed to download or install. 


Can you try re-installing the extension by doing the following:
1. From VS Code, uninstall the C/C++ extension
2. Go the folder where VS Code extensions are stored and ensure the folder  `c:\Users\shawn.vscode\extensions\ms-vscode.cpptools-0.26.3` is deleted. If it's not deleted, manually delete it.
3. From VS Code, install the C/C++ extension

**Comment by minida28** [comment]
I cannot uninstall it because other extensions depend on it..

![image](https://user-images.githubusercontent.com/3026584/78555537-746c2400-7837-11ea-8a91-cb2613a60cf4.png)

My Visual Code version:
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by minida28** [comment]
I solved it by:
1. Deleting the extension folder as advised above.
2. Reinstall the extension.

**Comment by sean-mcmanus** [comment]
Let us know if anyone figures out a good way to repro this issue so we could figure out a way to prevent it from happening.

**Comment by bigjosh** [comment]
Same problem, deleting the directory and re-installing also worked for me.
