### ISSUE TITLE
Does this cpptools support debug adapter protocol

### ISSUE THREAD

**Issue by kesongyue** [microsoft/vscode-cpptools#5033]
I download the source and I find this cpptools just an extension , which do not support vscode debug adapter protocol(DAP), right? Did I miss anything?

**Comment by pieandcakes** [comment]
@kesongyue This extension uses [MIEngine](https://github.com/microsoft/MIEngine) to translate debugAdapter to gdb's MI command. 

There are instructions [here](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/Debugger/How%20To%20Debug%20MIEngine.md) on how to set it up and debug it.

**Comment by kesongyue** [comment]
Thanks！I know the connection between debugApapter and gdb. I want to ask if this cpptoosls communicating with vscode just by extension or DAP?

**Comment by pieandcakes** [comment]
So MIEngine converts VSCode DAP (in OpenDebugAD7) to AD7 and then converts AD7 to gdb. AD7 is the set of debugging interfaces that Visual Studio supports so that part of MIEngine is also used in Visual Studio.
