### ISSUE TITLE
Provide symbolLoadInfo for visual studio debugger

### ISSUE THREAD

**Issue by AlexandreRoy5** [microsoft/vscode-cpptools#5034]
Type: Debugger

Using **symbolLoadInfo** with cppvsdbg.

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Hello, is it possible to make the option **symbolLoadInfo** work for the Visual Studio debugger (cppvsdbg) ? I saw this option for gdb/lldb, and I understand it as something similar to the Visual Studio "Modules" window, where one can see and control the loaded dll/pdb during a debugging session. Maybe it would be simpler to provide some commands to type in the debug console instead of a complete UI ? I had some difficulties to find a clear documentation on this subject anyway.

Thanks

**Comment by WardenGnaw** [comment]
`cppvsdbg` has the `symbolOptions` in `launch.json` to customize how to control symbol loading. 

See https://github.com/microsoft/vscode-cpptools/pull/7680
