### ISSUE TITLE
No error squiggles appear in code

### ISSUE THREAD

**Issue by christian-vorhemus** [microsoft/vscode-cpptools#5045]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10.0.18363.657
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): Several; disabling didn't fix the issue

I don't see any error squiggles at all in VSC in C++ code. Other features like "Go to Definition" or autocomplete work fine. It's basically a similar behavior as described in #2164 but I basically left almost everything untouched in the extension settings.

**Screenshots**

<img src="https://user-images.githubusercontent.com/3229424/75783291-9ec25180-5d60-11ea-9535-47f6daaddfee.png" width="250">

![cpp](https://user-images.githubusercontent.com/3229424/75781959-6c175980-5d5e-11ea-8f40-d3f0ff61668d.png)

**Comment by Colengms** [comment]
Hi @christian-vorhemus .  Is there anything at all listed in under the Problems tab?  If there is a configuration issue and IntelliSense cannot resolve #included headers, that will result in a single squiggle at the top of the file.

I see that you have a number of other extensions.  Could any other extension be trying to provide language services for the file you are editing?  Perhaps try with all other extensions disabled.

Could you run `C/C++: Log Diagnostics` with the repro'ing file open, and post the result?  That will contain the IntelliSense configuration for the file.  Also, could you enable debug logging using `"C_Cpp.loggingLevel": "Debug"`, and post its output leading up to the repro, as well as post your configuration (`c_cpp_properties.json`) ?

**Comment by christian-vorhemus** [comment]
Hello @Colengms 

The problems tab is empty:
<img src="https://user-images.githubusercontent.com/3229424/75860378-024d8d00-5dfc-11ea-97ad-7254778aad46.png" width="400">

Also, there are no squiggles at the first directive:
<img src="https://user-images.githubusercontent.com/3229424/75860464-29a45a00-5dfc-11ea-9743-feeec0448663.png" width="400">

Here is the output of C/C++: Log Diagnostics:
```
-------- Diagnostics - 3/4/2020, 9:44:24 AM
Version: 0.26.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "C:/Python36/include",
        "C:/vcpkg/installed/x86-windows/include"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:/mingw/mingw64/bin",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "C:/Python36/include",
            "C:/vcpkg/installed/x86-windows/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\user\Desktop\CPP-Playground\hash_table.cpp ]:
    C:\USERS\USER\DESKTOP\CPP-PLAYGROUND\HASH_TABLE.CPP
Translation Unit Configurations:
[ C:\Users\user\Desktop\CPP-Playground\hash_table.cpp ]:
    Process ID: 17628
    Memory Usage: 29 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PYTHON36\INCLUDE
        C:\VCPKG\INSTALLED\X86-WINDOWS\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\VC\TOOLS\MSVC\14.16.27023\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\VC\TOOLS\MSVC\14.16.27023\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: msvc-x64
Total Memory Usage: 29 MB
```

Content of `c_cpp_properties.json`:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/Python36/include",
                "C:/vcpkg/installed/x86-windows/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/mingw/mingw64/bin",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```

Do you mean the debug output when I start debugging the file? Then of course I get compiler errors:
```
> Executing task: g++ -g c:\Users\user\Desktop\CPP-Playground\hash_table.cpp -IC:/vcpkg/installed/x86-windows/include -std=c++17 -o hash_table -fno-stack-protector <

c:\Users\user\Desktop\CPP-Playground\hash_table.cpp: In member function 'V HashTable<K, V>::get(const K&)':
c:\Users\user\Desktop\CPP-Playground\hash_table.cpp:62:13: error: expected ',' or ';' before 'int'
             int int int test ==== 2;
             ^~~
The terminal process terminated with exit code: 1
```

Also, I disabled all extensions except C/C++ - no change.

But I've just figured out, sometimes squiggles do appear, like here:
<img src="https://user-images.githubusercontent.com/3229424/75860642-78ea8a80-5dfc-11ea-84d5-1f15090fde01.png" width="400">

But then I'm wondering why obvious syntax errors are not marked.

**Comment by rtviii** [comment]
I have the same problem.

**Comment by Noboroto** [comment]
You can try command 
C/C++: Enable Error Squiggles. 
I tried enable in settings before but it didn’t  worked and I used this command. I tried this command by Ctrl P (Windows 10) and this feature was enabled

**Comment by christian-vorhemus** [comment]
@Noboroto - just tried it but didn't help.

**Comment by christian-vorhemus** [comment]
It looks like the latest VSC update fixed the issue. VSC now outputs a warning that pointed me to the source of the problem. In my case, I didn't provide a correct compilerPath and intelliSenseMode in c_cpp_properties.json. In my environment it now looks like this

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/Python36/include",
                "C:/vcpkg/installed/x86-windows/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/mingw/mingw64/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```
and error squiggles do appear now!

**Comment by yoberner** [comment]
I was having the same issue. Try using the "open folder" option when you first open a window, instead of opening a random file. It then started to work for me.
