### ISSUE TITLE
[FEATURE REQUEST] Make support

### ISSUE THREAD

**Issue by rvanlaar** [microsoft/vscode-cpptools#5047]
Please support `configure` and `makefiles`.

I would like for VSCode to figure out which configure options there are and have support for makefiles when creating build tasks.

As per: #4942 Making a new issues for this.

**Comment by jureid** [comment]
Hi @rvanlaar - Thanks for opening this issue. I'm excited to share that we have a beta release ready for Make support. Would you be interested in giving it a try and providing feedback?

**Comment by bobbrow** [comment]
I have more information about how to join the preview here: https://github.com/microsoft/vscode-cpptools/issues/1587#issuecomment-701590120

I will close this feature request as a duplicate of #1587.

**Comment by rvanlaar** [comment]
Yes, would love that. Is it available via the regular beta channels?

**Comment by bobbrow** [comment]
It doesn't have a channel yet.  It will be a separate extension for now.  I will invite you to the repository and you can download the VSIX from the Releases page.
