### ISSUE TITLE
Doxygen memberdoc comments are not displayed correctly when hovering mouse on the function

### ISSUE THREAD

**Issue by skwasniak** [microsoft/vscode-cpptools#5048]
**Type: LanguageService**

**Describe the bug**
```
Version 0.27.0-insiders: March 3, 2019

Visual Studio Code:
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-40-generic snap
```
If you would like to document function parameters, there is a very convenient way of doing it with the doxygen's one-liner comment:
http://doxygen.nl/manual/docblocks.html#memberdoc

Below is an example of such a comment:
```
/**
 * @brief  Prints given foo.
 * @return On success, the total number of characters written.
 */
int
printFoo(
    char* foo,          /**< [in]  A C-string to print. */
    int* charWritten /**< [out] The total number of characters written. */
);
```
Unfortunately, the extension will only display `@brief` and `@return` fields for the above code.

**To Reproduce**
1. Create a header file with the above code snippet.
2. Hover over the function name. 
3. Notice that comments for the function's arguments are missing.

**Expected behavior**
Function's arguments are visible.

**Screenshots**
![2020-03-04_12-00](https://user-images.githubusercontent.com/15678876/75873234-d805ca80-5e0f-11ea-90f0-99bc5a982d6f.png)

![2020-03-04_11-58](https://user-images.githubusercontent.com/15678876/75873123-b1479400-5e0f-11ea-97bc-dd99b7324b8c.png)

![2020-03-04_11-57](https://user-images.githubusercontent.com/15678876/75873052-8b21f400-5e0f-11ea-80e8-8f115f9c69c0.png)

**Comment by michelleangela** [comment]
The extension does not support Doxygen documentation yet. Please up-vote the issue tracking the feature request at https://github.com/microsoft/vscode-cpptools/issues/658.
