### ISSUE TITLE
Unable to start the C/C++ language server [Error: TypeError: vscode.workspace.workspaceFolders is not iterable]

### ISSUE THREAD

**Issue by FungluiKoo** [microsoft/vscode-cpptools#5049]
**Describe the bug**
- OS and Version: Windows 10 Home 1909
- VS Code Version: 1.42.1 (user setup)
- C/C++ Extension Version: 0.27.0
- Other extensions you installed (and if the issue persists after disabling them): ms-python.python, ms-vscode-remote.remote-wsl
- A clear and concise description of what the bug is: A similar issue appeared two months ago, and last week I uninstalled all the extensions and uninstalled the VSCode, and then reinstalled them, and it became fine, until today this error appeared again.

**To Reproduce**
1. Wake up in the morning
2. Open a .cpp file in my personal directory with VSCode
3. See error

**Screenshots**

Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: TypeError: vscode.workspace.workspaceFolders is not iterable

**Additional context**
This problem can be solved by uninstalling the extension and reinstall a 0.26.3 version

**Comment by gascenciom1998** [comment]
I have the same problem but uninstalling and reinstalling does not solve it for me

**Comment by bobbrow** [comment]
Thank you for reporting this issue.  If you are repeatedly hitting this error, you can set the `C_Cpp.updateChannel` setting back to `"Default"` while we investigate it.

Quick question though.  Do you have multiple folders open in a workspace, just one folder, or no folders open?

**Comment by michelleangela** [comment]
We found a repro, which involves opening just a file and not a folder or workspace.

1. Close a folder or workspace if you have one open.
2. Open a source file.

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. It's fixed with 0.27.0-insiders2: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders2

**Comment by FungluiKoo** [comment]
Thank you guys for fixing the issue :)

**Comment by FungluiKoo** [comment]
> I have the same problem but uninstalling and reinstalling does not solve it for me

@gascenciom1998  I meant to reinstall a previous steady version, like 0.26.3, not to reinstall the same (latest) version

**Comment by sean-mcmanus** [comment]
FYI, 0.27.0-insiders3 broke this again: https://github.com/microsoft/vscode-cpptools/issues/5136 .

We'll try to get a fix soon.

**Comment by sean-mcmanus** [comment]
FYI, 0.27.0-insiders4 fixed it (again), but we found that the database creation is failing, which we're tracking to fix for 0.27.0: https://github.com/microsoft/vscode-cpptools/issues/5176

**Comment by sean-mcmanus** [comment]
The database issue got fixed with 0.27.0-insiders5: https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders5
