### ISSUE TITLE
[C++ on Mac]Reattach will cause the process exit

### ISSUE THREAD

**Issue by caslan** [microsoft/vscode-cpptools#505]
Internal bug id: 236195
Sample code attached.

 

Configuration:

VSCode(Stable) + cpptools(0.7.1)

 

Steps to repro:

1) Compile the sample code: g++ -g a.cpp b.cpp c.cpp -lpthread

2) Run the app: ./a.out

3) Open the sample code folder in vsocde.

4) Add the process ID in launch.json

5) Set debug type to Attach, then F5(the process is waiting for input)

6) Reattach

 

Expected:

Reattach succeed, since the process should be existing.

 

Actual:

The prcocess has exitted. Debugger tried to attach all the time.

 

 
[test (3).zip](https://github.com/Microsoft/vscode-cpptools/files/784845/test.3.zip)

**Comment by pieandcakes** [comment]
No Repro
