### ISSUE TITLE
What's the best way to work with source control in VSCode to ensure the C/C++ integration stays up to date

### ISSUE THREAD

**Issue by mgaudet** [microsoft/vscode-cpptools#5052]
**Type: LanguageService**

When using VSCode, I tend to use the terminal to jump around between revisions a lot because I am more productive when I do this. 

However, this appears to challenge the C/C++ integration plugin, as when I change revisions it has an incomplete view of the types that may have changed from one revision to the next. For example, if I have a file open, and update to a new revision that adds a type in a file that's not open, I'll get Red-squiggles until I open the file that adds the new type, at which point the extension seems to realize its perspective on the types was no longer valid. 

I'm wondering if there's something I could add as an on-update hook to help keep VSCode + plugins aware that the revision of the working directory has changed, and that there may be processing still to do. 

I do find the state of the world is -way- better than it used to be, where changing working directory state would often mean that I'd totally lose all completion and error support. Now it seems to keep working, just with stale data (which often is totally fine, as changing revs rarely changes every datastructure in the project)

**Describe the bug**
- OS and Version: Linux Ubuntu 19
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.27.0-insiders

**To Reproduce**

A rough summary is something like this: 

1. Have a fairly large workspace open (I work on mozilla-central, the firefox codebase) 
2. Open a file that when you update will have a reference to a type that's defined in a file that's not open. 
2. in the terminal, do `hg up <some nearby revision>` that adds that type definition
3. Notice that you get red-squiggles under the new type in your current file, 
4. Open the file that defines that type: notice the red-squiggles in the original file go away. 

**Expected behavior**

`hg up` is able to inform VSCode that there are some files that changed. 

**Additional context**

I intermittently get the warning about too many files to watch on this workspace, though this seems to happen on sessions where I haven't gotten said warning.

**Comment by sean-mcmanus** [comment]
We added code in our "didChange" handler that would only send "FileChanged" notifications if the file has a modification time within 10 seconds due to what seemed like a VS Code bug where we would be getting erroneous onDidChange messages for files that never changed. See https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/client.ts#L1837 .

Do you know if when you change branches if the changed files have their modified times set to the current time or set to the modified time in your source control system?

There's a Rescan Workspace command, which may update some of the stale data.

**Comment by mgaudet** [comment]
Thanks for the feedback! So, I can confirm using `stat` that using `hg up` does change the modification time on a file changed. 

Is there a way to ask vscode if it's successfully watching a particular file? Or to get those `rootPathFileWatcher.onDidChange` notifications logged somewhere so I can do some further diagnostics?

**Comment by sean-mcmanus** [comment]
You might see some error in the Toggle Developer Tools console if VS Code hits a file watcher error.

You could also set your C_Cpp.loggingLevel to "Debug" to and look for a "fileChanged" logging message (but unfortunately we don't log the file that changed yet).

**Comment by Colengms** [comment]
Hi @mgaudet .  Are you still seeing this issue?  Some improvements have been made since you originally opened this issue.  Also, we now log the path associated with the fileChanges message.

**Comment by mgaudet** [comment]
I haven't really noticed it as badly as I used to for sure.

**Comment by mgaudet** [comment]
I am unable to provide further assistance; I've stopped using the cpptools extension these last few months. Having said that, I did notice improvement, and so I am going to close this issue for now.
