### ISSUE TITLE
How to choose cpptools OS version when use remote-ssh

### ISSUE THREAD

**Issue by farqq** [microsoft/vscode-cpptools#5067]
hi，我是在win10系统上通过vscode的remote-ssh插件在linux主机上远程开发，由于一些原因只能手动安装cpptools.vsix。想问下我该选择哪个操作系统下的vsix？([realease列表](https://github.com/Microsoft/VSCode-cpptools/releases))还有当有多个操作系统共存时选择vsix的原则是什么？

Hi, I'm a remote deveolper who writing code with vscode by using remote-ssh plugin in win10, while the code files are saving in cloud machine which OS is Linux.
Now I'm confusing about which vsix to download, Windows or Linux? ([the realease list](https://github.com/Microsoft/VSCode-cpptools/releases))What's the principle of vsix choosing when dealing with multi OS?

**Comment by michelleangela** [comment]
For remote development, the C/C++ extension will run on the remote machine. If the remote machine is Linux, the Linux vsix will need to be installed on that remote machine. 

You can let VS Code manage installing extensions on the remote machine. For more information about installing extensions on the remote machine using VS Code, go to https://code.visualstudio.com/docs/remote/ssh#_managing-extensions.

**Comment by farqq** [comment]
> For remote development, the C/C++ extension will run on the remote machine. If the remote machine is Linux, the Linux vsix will need to be installed on that remote machine.
> 
> You can let VS Code manage installing extensions on the remote machine. For more information about installing extensions on the remote machine using VS Code, go to https://code.visualstudio.com/docs/remote/ssh#_managing-extensions.

Thanks a lot.
BTW, I can't let vscode manage the installing because my machine is behand a strict firewall.
