### ISSUE TITLE
clang_format_sortIncludes ignores .clang-format setting at startup

### ISSUE THREAD

**Issue by johvik** [microsoft/vscode-cpptools#5068]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Fedora 31
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.27.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

The `Format Document` command does not work as exepcted. I can run the command and it does some kind of formatting but the it seems like it isn't using the `SortIncludes: true` from the `.clang-format` I have in my repository when `clang_format_sortIncludes` is the default value or null.

**To Reproduce**

1. Prepare a directory with a `.clang-format` with `SortIncludes: true` and a source file with #includes that requires sorting
2. (Not sure if needed, but I've set `"C_Cpp.clang_format_path": "/usr/bin/clang-format"` in `settings.json`
2. Open the directory in vscode (can re-trigger it using `Developer: Reload Window`)
3. Run `Format Document` on the source file
4. See the includes not being sorted

**Expected behavior**

Includes to be sorted according to the `.clang-format` rules when `C_Cpp.clang_format_sortIncludes`is the default value or null.

**Screenshots**

**Additional context**

If I do this the sorting starts to work:
1. Comment out some setting in `settings.json`
2. Save `settings.json`
3. Now the formatting works until I restart vscode or reload the window

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. It's a regression with 0.27.0-insiders2. We should be able to have a fix for 0.27.0-insiders3.

**Comment by michelleangela** [comment]
Is this issue related to the [old Clang format 6.0.0 in 0.27.0-insiders2](https://github.com/microsoft/vscode-cpptools/issues/2887?email_token=AJHQTT3QEHOUZWFIOI26H73RG3SONA5CNFSM4GHVCQ72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEONZC3I#issuecomment-596891400)?

**Comment by sean-mcmanus** [comment]
@michelleangela No. It was a different fix.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders3

**Comment by oxymoron87** [comment]
Same issue but now with `C_Cpp.clang_format_fallbackStyle` or `C_Cpp.clang_format_style`

VS Code Version: 1.43.1
C/C++ Extension Version: 0.27.0-insiders3

Same workaround still works:

> 1. Comment out some setting in settings.json
> 2. Save settings.json
> 3. Now the formatting works until I restart vscode or reload the window

UPDATE:
Fixed with C/C++ Extension Version: 0.27.0-insiders4
