### ISSUE TITLE
Header File could not found although added to includePath in c_cpp_properties.json

### ISSUE THREAD

**Issue by CreatorZZY** [microsoft/vscode-cpptools#5069]
![image](https://user-images.githubusercontent.com/38124587/76094096-fe3c8d80-5ffc-11ea-8e5c-624e36a188f4.png)
I have no idea what have happened.
I cann't found the std lib header file, since i install opencv(apt-get install libopencv-dev). but actually I can Compile the source file.

**Comment by michelleangela** [comment]
@CreatorZZY, can you verify that the path of the library header files set in c_cpp_properties.json is valid? The extension also tries to find system include paths based on the provided compilerPath settings. It could be that the extension is failing to query the compilerPath to get the system include paths.

Can you also sharing the following two logs:
1. The log output from running `C/C++: Log Diagnostics` in the command palette
2. [Enable logging of the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) and share the output logs

**Comment by sean-mcmanus** [comment]
The "file not found" message is not from our extension. It's from another extension you have installed.

**Comment by sean-mcmanus** [comment]
It's probably from the C/C++ Clang Command Adapter extension. Let us know if you still have a problem after disabling that extension and using ours. Or you can set our C_Cpp.intelliSenseEngine setting to "Disabled" if you can figure out how to get the other extension working instead.
