### ISSUE TITLE
IntelliSense and colorization broken when using coroutines

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5072]
This issue is to keep track of IntelliSense coroutines issues reported on Visual Studio at https://developercommunity.visualstudio.com/content/problem/941925/intellisense-and-colorization-broken-with-using-co.html

**Repro steps:**
1. Open empty folder on VS code
2. Add a new source file to folder
3. Add following sample code with coroutines:

```
#include <future>

std::future<int> async_func1()
{
    co_await async_func2();
    co_return 0;
}

std::future<int> async_func2()
{
    auto fut = std::async([=]() 
    {
        return 0;
    });

    return fut;
}
```
4. See that async_func1() is highlighted with two colors.
![image](https://user-images.githubusercontent.com/38734287/76121121-cd7e3900-5fa7-11ea-8114-ac6334dc54c4.png)

5. Hovering over the “async_” part of async_func1() gives incorrect hover info.
![image](https://user-images.githubusercontent.com/38734287/76121250-0e764d80-5fa8-11ea-9806-8973a6fca303.png)

6. Comment out the co_await and co_return statements and see that IntelliSense issue resolves.
![image](https://user-images.githubusercontent.com/38734287/76121282-20f08700-5fa8-11ea-87d4-54be89b0e196.png)

7. Uncomment co_await or co_return statements and see that IntelliSense issue returns.
![image](https://user-images.githubusercontent.com/38734287/76121319-349bed80-5fa8-11ea-88ed-8fb2ebe4d88a.png)

**Comment by Colengms** [comment]
I believe this has been addressed by recent work.  I'm no longer able to repro the issues described here.
