### ISSUE TITLE
#include completion exits out for header files that start with a number

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5073]
Try #include "123.h". include completion aborts after the "1" is typed.

**Comment by elahehrashedi** [comment]
It looks like it got fixed at some point. 
![image](https://user-images.githubusercontent.com/16143955/80140512-e72a0e80-855c-11ea-9852-44a11a1705de.png)

**Comment by sean-mcmanus** [comment]
Yeah, I don't repro this anymore with 0.27.0...not sure why I was reproing it originally.
