### ISSUE TITLE
Running C++ code will not allow user to input text in Terminal

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode-cpptools#5074]
They immediately closed my issue and tagged it , saying its the fault of your extension.
https://github.com/microsoft/vscode/issues/92178

**Comment by sean-mcmanus** [comment]
@pieandcakes @WardenGnaw Is this a known issue with the debugger?

Maybe try setting the externalConsole setting to "true" in your launch,json.

**Comment by pieandcakes** [comment]
@RobFosterNYC Can you post your `launch.json` file for me? If you are using our extension (`cpptools` or `"type": "cppdbg"` in your `launch.json`) then please try @sean-mcmanus 's suggestion above. 

I took a look at your original issue and I noticed you mention you use the RUN CODE extension but I was unable to find information on what that is. Your screen shot doesn't show you using this extension but if you want to install it and try, its called the `C/C++` extension in the gallery.

**Comment by RobFosterNYC** [comment]
@pieandcakes 
Sorry, my apologies.  the extension is called --->>>  Code Runner.  
But in the right click menu its called RUN CODE.  sorry about my typo.  :(
and yes I already have C++ extension installed for a long time now.
Also,  Im hoping you guys would create a feature that would allow users to use the internal console instead of the external console.
.
 anyways this screenshot shows what I see when I right click and chose to execute the code.
.
![Code Runner right click Menu](https://user-images.githubusercontent.com/18384135/76137284-ee2aab00-6008-11ea-9955-c5b35bf92857.png)

**Comment by pieandcakes** [comment]
@RobFosterNYC It looks like Code Runner's issues page is [here](https://github.com/formulahendry/vscode-code-runner/issues). It seems like the issue you are having is with their extension and I won't be able to help you with that. 

If you want to use the integrated terminal with our extension,  we have support. You change the value of `externalConsole` to `false` in your `launch.json` and it should work.

**Comment by WardenGnaw** [comment]
Closing as an external issue.
