### ISSUE TITLE
Light bulb influences code indent when tabs-based whitespace is rendered

### ISSUE THREAD

**Issue by mikedld** [microsoft/vscode-cpptools#5081]
**Describe the bug**
- OS and Version: Linux
- VS Code Version: 1.43.0-insider (was present on previous versions as well)
- C/C++ Extension Version: 0.26.3 (was present on previous versions as well)
- Other extensions you installed (and if the issue persists after disabling them): a few, the issue persists
- When `C_Cpp.dimInactiveRegions` and `editor.renderWhitespace` are enabled and tabs are used for indentation, putting cursor on a dimmed line of code shows the yellow light bulb which seems to offset the code past the expected indent.

**To Reproduce**
1. Set `C_Cpp.dimInactiveRegions` to `true` (the default)
2. Set `editor.renderWhitespace` to `"all"`
3. Use tabs for code indentation
4. Find an inactive code region and put the cursor on one of the inactive lines, so that it's on the non-indent part of the line (after leading whitespace)
5. Wait for the yellow light bulb (with "Disable inactive region colorization" action) to appear
6. Notice the indent increase

**Expected behavior**
Light bulb visibility doesn't influence the indent.

**Screenshots**
C++ code indented with tabs:
![Peek 2020-03-08 18-49](https://user-images.githubusercontent.com/298203/76166438-98bcde00-616f-11ea-8dfc-060573c2125b.gif)
![Peek 2020-03-08 20-44](https://user-images.githubusercontent.com/298203/76168133-b1cc8b80-617d-11ea-92f4-c3ce5c12c1c6.gif)

C++ code indented with spaces:
![Peek 2020-03-08 18-54](https://user-images.githubusercontent.com/298203/76166444-a07c8280-616f-11ea-9a22-30885c692ee2.gif)

JavaScript code indented with tabs (within Interactive Playground):
![Peek 2020-03-08 18-46](https://user-images.githubusercontent.com/298203/76166431-86db3b00-616f-11ea-96b1-89b311523306.gif)

**Additional context**
Font: Ubuntu Mono

**Comment by Colengms** [comment]
Hi @mikedld .  I'm not able to easily repro.  Are there any other extensions installed that might be doing this?  The positioning of the light bulb and its effect on the contents of that line, are not behaviors our extension should be effecting.  We simply return a list of actions.

**Comment by mikedld** [comment]
I think I may have missed one more piece... I've tried it again now and wasn't able to reproduce either until I realised that when this is happening I'm actually working through a Remote SSH extension connecting from Linux to Windows (native, w/o WSL). Failed to reproduce it locally, but was able to reproduce once connected to a Windows SSH target.

If you could please move this issue to the appropriate repo that would be awesome.

**Comment by Colengms** [comment]
Since this is related to VS Code UI and not something we can address in the C/C++ extension, closing this issue.
