### ISSUE TITLE
Build and Debug Active File could provide the latest supported std standard, if using a known compiler and compiler version.

### ISSUE THREAD

**Issue by TylerMSFT** [microsoft/vscode-cpptools#5085]
Type: General

**Describe the bug**
- OS and Version: MacOS 10.15.3
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- Configuring a default build tasks for Clang always defaults to c++98.  Per Bob Brown: "When this feature was implemented it was focused around gcc/g++ where the default standard version for latest compilers was c++14.  A better solution would be for to build a table of supported standards and supply this parameter based on the compiler version."

**To Reproduce**
1. In VS Code on MacoS, add a blank test.cpp file. 
2. Terminal > Configure Default Build Task > C/C++: clang++ build active file
3. Choose the clang compiler.
4. The resulting tasks.json file builds for C++98. 

**Expected behavior**
Would like the resulting tasks.json file to build for the latest version of C++

**Comment by Colengms** [comment]
The current implementation is by design.  This sounds like a feature request to consider the version of the compiler (if a known compiler and version) as pass the latest std value it would accept.
