### ISSUE TITLE
[Feature Request] Add 'Build and Debug active file' to Run and Debug Window

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode-cpptools#5096]
From: https://github.com/microsoft/vscode/issues/85548

We are now able to add buttons and text to the debug menu. Instead of having users right click to get to build and debug active file. If the user recently selected a cpp file, we can add to the debug menu. 

For example:
![image](https://user-images.githubusercontent.com/3953714/76450464-114bb680-638b-11ea-93e7-398e056b4e6a.png)
We cannot change the
```
Run: Start
[Run and Debug]
To customize run and debug, create a launch.json file.
```
but we can add after it.

**Comment by bobbrow** [comment]
This is cool.  Is it something we can get in for v1?  I would love to replace the current logic with this and stop generating tasks.json (basically moving the code into a command).

**Comment by Colengms** [comment]
@WardenGnaw Is this still "fixed (pending release)" ?

**Comment by WardenGnaw** [comment]
We have a iteration of it working. It can be improved. 

![image](https://user-images.githubusercontent.com/3953714/108142478-b4687e00-707a-11eb-848b-16b8cd0be387.png)

However, I'll close this issue for now.
