### ISSUE TITLE
Mammoth .browse.VC.db in .vscode after creating c_cpp_properties.json (Linux only)

### ISSUE THREAD

**Issue by Dan-McG** [microsoft/vscode-cpptools#51]
I've been through all the issues and there are many (both open and closed) that seem to report this bug and its associated behaviours but aren't linked:
#44 #39 #29 #26 #11 #6 (closed as duplicates #25 #14)

The problem: After installing the extension, as soon as you generate the c_cpp_properties.json file to declare the standard linux include location /usr/include, the extension goes off and builds .browse.VC.db (the symbol database) in the .vscode workfolder directory.  This however takes hours to build and becomes a 1-3GB symbol database of what I can only imagine is the entire system's libraries.  And it's created for each workfolder, and recreated in each workfolder everytime the project is opened.  Even if it's just a simple hello_world.c.  If you close vscode, the extension continues running, building this database with associated network, cpu and hdd activity.

This makes the extension unusable on linux.

Tried extension on Windows and the .browse.VC.db stays at small size.

vscode: 1.1.1
cppext: 0.5.0
distro: Archlinux
(I appreciate it's only officially tested on Ubuntu, and haven't tried to replicate on a Ubuntu distro)

As an aside the link on the [blog post](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/cc-extension-for-visual-studio-code/) to this github repo is incorrect (missing an s)

**Comment by sridmad** [comment]
In 0.7.0 we added the ability to control the files that are processed and added to the database.

/usr/include - recursively add all files under the folder to the database
/usr/include/* - Do not recurse folders under /usr/include, just add the files in /usr/include to database

This should allow finer grained control of the files processed through judicious use of includepaths

We are also adding another switch to allow adding just the files referenced (directly / indirectly) by files under the root folder.

**Comment by jgoshi** [comment]
In the next release, version 0.8.0, we also add a new switch to the c_cpp_properties.json file called limitSymbolsToIncludedHeaders. If you set that value to true we only add symbols for those files that are directly/indirectly included. This will greatly reduce the database size.
