### ISSUE TITLE
highlight the code, based on preprocessor definitions

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cpptools#510]
is it possible to implement like this does most of IDEs:
grayed (or other highlightiing) the code blocks of inactive preprocessor definitions. 
look at the screenshot to understand what I mean
![image](https://cloud.githubusercontent.com/assets/3259933/23139466/91108c02-f7bd-11e6-8282-166b2a3cbf70.png)

**Comment by sean-mcmanus** [comment]
VS Code doesn't provide any interface for the C++ extension to report which range of text is inactive and we don't control any of the colorization (it's done by atom/language-c), so I don't think this is currently possible.

**Comment by amigo421** [comment]
seems that is possible, 
please look at the linked request in vscode repository,
the reply there refers to the API for the discussed feature

**Comment by sean-mcmanus** [comment]
Ok, but showing inactive regions will have to wait till after we add the IntelliSense engine (which processes #define/#ifdef).

**Comment by amigo421** [comment]
thank you!

**Comment by agauniyal** [comment]
@sean-mcmanus when can we expect that engine? any dates or some hope 😅

**Comment by sean-mcmanus** [comment]
We're planning to release some IntelliSense engine-based features in April, but it won't include "inactive regions", which we don't have any schedule for yet.

**Comment by amigo421** [comment]
good news , thank you! (I'm about intellisense)

**Comment by bobbrow** [comment]
Merging this issue with #230

**Comment by bigwave-in-boulder** [comment]
Any update to this?

**Comment by sean-mcmanus** [comment]
@bigwave-in-boulder Yeah, we should be releasing the feature today in 0.15.0 (and the feature has been in the 0.15.0-insiders release for 2 weeks: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.15.0-insiders ).

**Comment by sean-mcmanus** [comment]
@amigo421 @agauniyal @bigwave-in-boulder Inactive region highlighting has been added with 0.15.0.

**Comment by ghost** [comment]
How do you disable this feature now ! I have many defined that are passed by makefile ! Now 80% of my code is grey.....

**Comment by sean-mcmanus** [comment]
@Darkstarxt You can set intelliSenseEngine to "Tag Parser". You could also follow the steps at https://github.com/Microsoft/vscode-cpptools/issues/1466#issuecomment-366304132. However -- if you see gray text, it means the code is not visible to the IntelliSense engine, so you won't get any of those features for that section of code.

**Comment by WZRPW** [comment]
@sean-mcmanus , I installed IntelliSense on my Visual Studio. I have defined a few macros (.e.g., OPENCV and CUDA etc) in Makefile and I use task.json to call my Makefile to build the project. Now the problem is that VSCode could not recognize all my macros defined in Makefile. See the below screenshot. I actually defined OPENCV in Makefile but VSCode could not recognize it thus lines 16 and below are shown as inactive. I wonder if there is a solution to overcome this issue.

####################################task.json####################################
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "darknetMakefile",
            "type": "shell",
            "command": "make",
            "options": {
                "cwd": "/home/xxx/workdir/"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            "args": [
                "QUIET=0"
            ],
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "absolute"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
    ]
}
####################################task.json####################################

![screenshot from 2018-08-24 19-17-47](https://user-images.githubusercontent.com/24899439/44613053-e95e2780-a7d3-11e8-84ea-741de2490f0f.png)

**Comment by bobbrow** [comment]
@Iamthegeekdavid, tasks.json is not used by IntelliSense.  Take a look at `c_cpp_properties.json` (you can use the "Edit Configurations..." command to open it).  There is a property in the configuration called `defines` where you can add macros that should be applied for IntelliSense.

Full reference here: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md

**Comment by WZRPW** [comment]
@bobbrow the pre-defined MACRO feature is good on my VSCode now. I wonder if c_cpp_properties.json only affect the code displaying but will not impact building my project, i.e., code compiling and linking. 
Thanks,

**Comment by bobbrow** [comment]
Correct, c_cpp_properties.json is just for IntelliSense, not for compiling or linking.

**Comment by WZRPW** [comment]
@bobbrow , hi Bob, one more question. I found that "debug disabled for cuda code in vscode". I wrote one issue about it: https://github.com/kriegalex/vscode-cuda/issues/4    Nobody replies yet. I wonder if you have any clue on this. Thanks,

**Comment by bobbrow** [comment]
I'm sorry, I don't know anything about that extension.

**Comment by WZRPW** [comment]
@bobbrow , thanks for replying my message. I know that Visual Studio has a debugging tool, parallel stack, which show a hierarchical graph of all running threads. I wonder if VSCode has this feature or will have it in the future. Thanks again!

**Comment by sean-mcmanus** [comment]
@Iamthegeekdavid VS Code and the C/C++ extension doesn't implement the parallel stacks feature -- you could open a feature request for that.

**Comment by WZRPW** [comment]
@sean-mcmanus , thanks for replying my issue. For me to write feature request of parallel stack, shall I write a request on GitHub page of VSCode-cpptool (https://github.com/Microsoft/vscode-cpptools/issues) or VScode (https://github.com/Microsoft/vscode/issues)? Thanks again!

**Comment by sean-mcmanus** [comment]
@Iamthegeekdavid I would try https://github.com/Microsoft/vscode-cpptools/issues first.

**Comment by WZRPW** [comment]
@sean-mcmanus , thanks. I have submitted a feature request there. 
https://github.com/Microsoft/vscode-cpptools/issues/2598

**Comment by baiwfg2** [comment]
Here's an issue I met. I work on mac's vscode, and I don't want code related to linux platform to be inactive. The following is not what I want. `#else` part should be highlighted. How could I do that ?
![image](https://user-images.githubusercontent.com/5157680/68098717-56ea0580-fef9-11e9-8230-5b964b5dcc52.png)

**Comment by sean-mcmanus** [comment]
@baiwfg2 There's a thread on this issue at https://github.com/microsoft/vscode-cpptools/issues/1083 . Cross-platform support (e.g. Mac to Linux) is a missing feature, with some potential workarounds users have found. Using the VS Code remoting extensions to remote into a Linux machine from Mac would also work.

**Comment by marcmerlin** [comment]
So, I know it's bad form to hijack a bug, but hopefully this enough of the same issue to be ok here?
From this bug, ifdefs should now be parsed for colorization, is that also true for includes?

In this case I'm getting a warning for an include I don't have but don't care about since the ifdef does not apply to me.
Is that the same issue and it should be fixed?
Is that a new issue that needs a bug?
Or is that an existing issue with an existing bug I wasn't able to find?
![image](https://user-images.githubusercontent.com/1369412/81527514-52226600-930f-11ea-8a3d-131d2b8f6582.png)

This is 1.44.2-1587059832 on linux/debian.  Thanks.

**Comment by sean-mcmanus** [comment]
@marcmerlin IntelliSense appears to think that SPARK is defined. If that's not true, can you file a new issue with more repro/logging details?

**Comment by marcmerlin** [comment]
@sean-mcmanus sure thing. I tried to gather the best I could in this bug:
https://github.com/microsoft/vscode-cpptools/issues/5514
