### ISSUE TITLE
static_assert not being handled correctly

### ISSUE THREAD

**Issue by assafmendelson** [microsoft/vscode-cpptools#5102]
**Type: LanguageService**
**Describe the bug**
- OS and Version: centos 7.4 (using remote ssh extension)
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.27.0-insiders2

Using remote ssh (vscode runs on windows 10 and connects to centos 7.4)

The following code:
`static_assert(true, "some message");`

shows red squiggly lines on both parameters with error "expected a type specifier"

Note: static_assert is defined outside any function (actual code includes validation of sizeof of a structure, however, event the simpler code above fails).

The code itself compiles correctly.

**Comment by sean-mcmanus** [comment]
I'm not able to repro that with my clang/g++. Can you run the C/C++: Log Diagnostics command and provide the output? It may be using settings that make static_assert invalid (like treating the code as C instead of C++).

**Comment by assafmendelson** [comment]
The project is a combined C/C++ project compiled externally by a build script.
The file is a c file which includes some C++ headers.
Our own compile script uses gcc.
The relevant configuration portions are:

Version: 0.27.0-insiders2
Current Configuration:
{
    "name": "Linux",
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c99",
    "cppStandard": "c++14",
    "intelliSenseMode": "gcc-x64",
}
    Standard Version: c99
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50001

**Comment by sean-mcmanus** [comment]
Logs show we're processing your active file as C and not C++ (C doesn't allow "static_assert"). What is the file type? Can you run C/C++: Log Diagnostics and look for what TU the file is being associated with? Can you check your files.associations settings to make sure they are correct -- we have code that will auto-add associations as navigation is done, but that may sometimes cause an unwanted association to be set.

**Comment by assafmendelson** [comment]
File association is:
`{
    "files.associations": {
        "deque": "c",
        "list": "c",
        "string": "c",
        "unordered_map": "c",
        "unordered_set": "c",
        "vector": "c"
    }
}`

the specific file is a .c (the only thing in the TU is the file and an associated h file). That said the project as a whole has both c and c++ code (and the .c file is in practice compiled as c++).

How do I make c files be considered as c++ for this case?

**Comment by sean-mcmanus** [comment]
If the source file is ".c" it will get compiled as C for IntelliSense. You can change that via adding appropriate lines to your files.associations settings, such as
```
        "*.c": "cpp"
```
and removing or replacing the existing "c" associations.

If you let us know how you're communicating with your compiler that the .c should be compiled as C++, then we (or you) could file a feature request to handle that automatically, i.e. via processing the compiler argument (or I could morph this issue into that).

**Comment by assafmendelson** [comment]
This works, thanks
