### ISSUE TITLE
insiders update/downgrade improvements

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#5105]
**Type: LanguageService**

![image](https://user-images.githubusercontent.com/12818240/76544200-e1f98000-6444-11ea-9f75-7c302fd1a500.png)

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
