### ISSUE TITLE
[GDB] follow-fork-mode child

### ISSUE THREAD

**Issue by ApoorvaJ** [microsoft/vscode-cpptools#511]
GDB has a command called `set follow-fork-mode child` that instructs GDB to follow the forked process. I couldn't find a way to do this with this plugin.

I tried adding various permutations of `"-exec set follow-fork-mode child"` to the setup commands in the launch.json, but wasn't able to get it to work.

Is it possible to set this up from launch.json?

**Comment by pieandcakes** [comment]
@ApoorvaJ Do you have a simple code example I can try out for this?

**Comment by ApoorvaJ** [comment]
```
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>

int main()
{
    pid_t pid = fork();
    if (pid != 0) {
        printf("Main process\n");
    } else {
        printf("Forked process\n");
    }

    return 0;
}
```

Compile using the `gcc -g fork.c` option on command line on Linux to enable debug symbols. Open in gdb using `gdb ./a.out` Set breakpoints on both printfs. Try running. You'll only ever hit the main process breakpoint.

To hit the other one, type in `set follow-fork-mode child` into gdb, and then run again. You'll now only hit the forked process breakpoint.

I'd like to control this behaviour in the launch.json file while debugging via VS Code.

**Comment by pieandcakes** [comment]
@ApoorvaJ Thanks. I'll take a look and let you know.

**Comment by pieandcakes** [comment]
@ApoorvaJ We use gdb's MI command structure. This is the block you need to add to your `launch.json` section:

```
            "setupCommands": [
                {"text": "-gdb-set follow-fork-mode child"}
            ]
```
Note: There is a bug in the current release version that crashes and makes it so that this doesn't work. I have fixed it (and referenced the [Pull Request](https://github.com/Microsoft/MIEngine/pull/564)) and it will be in our `0.10.2` release.

**Comment by pieandcakes** [comment]
@ApoorvaJ `0.10.2` is live. Closing this issue because it is resolved.

**Comment by z7z8th** [comment]
can't switch to child process in VS code version 1.34.0

**Comment by z7z8th** [comment]
Also, can't switch to child process in VS code version 1.35.0

**Comment by curtiskeisler** [comment]
Version 1.37.1 I'm unable to even start the process. I get a write EPIPE error. I have ensured that I'm in fact loading the correct child source code. It runs fine in stand-alone node.

**Comment by pieandcakes** [comment]
@curtiskeisler yours sounds like a different issue . Please file a new issue with logging information.

**Comment by Trass3r** [comment]
> This is the block you need to add to your `launch.json` section:
> 
> ```
>             "setupCommands": [
>                 {"text": "-gdb-set follow-fork-mode child"}
>             ]
> ```

Is this in the docs?

**Comment by geajack** [comment]
How do you do this on modern VS Code? Where do I put the `setupCommands` option? Putting it in `launch.json` at the root of the GDB configuration object doesn't seem to work.
