### ISSUE TITLE
Can't clear recently opened files from `Go To Definition` Peek

### ISSUE THREAD

**Issue by sharkweek** [microsoft/vscode-cpptools#5112]
## Issue
I currently have `editor.gotoLocation.multipleDeclarations` set to `peek`. When I use the `Go to Definition` command and have multiple definitions, the Peek window also includes recently opened files outside of my current workspace even when they are not open in the current editor. I have tried using the `Clear Recently Opened` command, but these files are not cleared from the Peek results. I've also tried reloading the window, but they still show up.

So far the only thing I've found that helps is deleting the recently opened file, which is less than ideal...

I had also filed an [issue](https://github.com/microsoft/vscode/issues/92525) with on the vscode repo.

## System info:
Version: 1.43.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by sean-mcmanus** [comment]
What do you mean by "Peek window also includes recently opened files". I don't see any UI that mentions "recently opened" files, so I assume the results are just from those files?

We intentionally parse opened files, which will cause their results too appear in the Go to Def in some cases, but when you do a Reload Window with those files no longer open, you should see output in the debug log (C_Cpp.loggingLevel set to "Debug") that says "removed from database" and then those external files will stop appearing. Can you provide more repro info?

**Comment by sharkweek** [comment]
The file does not appear to be explicitly labeled as "recently opened"; I only know it is because I had opened it to use as a reference. I have closed the file out and reloaded the window multiple times, restarted VS code, and even rebooted, but still it's still there. I have also checked to ensure that the file's directory didn't accidentally get added to the `includePath`.

I've included a screen shot below. The first file listed is the incorrect, recently opened file. The second file is the correct one in the workspace.

![recents](https://user-images.githubusercontent.com/18335862/76767290-9a316c00-6756-11ea-813d-902afbb4f91f.JPG)

**Comment by sean-mcmanus** [comment]
I'm not able to repro this still.

@michelleangela @Colengms Are you able to get a repro or have any ideas how a repro could get obtained?

I open an external file with symbol such as "func()", and doing Find All Refs locates that file, but after reloading, my logs show
"  2 file(s) removed from database\nDone discovering files." and then Find All References doesn't find that any more because it's removed from the database.
