### ISSUE TITLE
Some issues I want to clearify

### ISSUE THREAD

**Issue by CDitzel** [microsoft/vscode-cpptools#512]
I am loving VS Code so far (using the latest stable build), but unfortunately a few things really bug me:

1. mouse-wheel scrolling inside code files is really awkward, slow and unresponsive. Using the scrollbar at the side works fine, but the mouse wheel scroll seems delayed and almost unuseable. Is this a known problem or is the issue with me? Also marking file sections with pressed left mouse is sometimes really fast and sometimes laggy. Same issue I guess? Does it have to do with the size of the directory that i opened vs code on? should not depend on that ideally...

2. built-in git support is not working great. Every so often it says
Can't open this git resource. when i just click on some modified file in the git section of VS Code. What is that all about? It kind of defeats the purpose of the git support. My projects uses git submodules, may that be the reason? Some files can be opened to compare changes while others just display this error message

3. "Go to Definiton" should imo oben a new file rather than replacing the current one. that is really annoying if you want to keep working on that file after looking up some definition, especially in zenMode

4. Auto-compelte/Intelli Sende: i know its in progress, but please make it faster

5. How to get colorful output in the built-in console? I did not find any solution yet

6. the nightly builds are (at least on my Ubuntu 16.04) not working. I install via dpkg but after that, code would not start, prompting it has not been installed on the system

apart from that, I like VS Code a lot. Keep up the work guys! I am actively recommending it

**Comment by sean-mcmanus** [comment]
1. There is no known issue with mouse wheel scrolling. We don't control any scrolling-related code and none of our extension code should run in the general scrolling scenario. It sounds like either a VS Code bug or an issue with your mouse wheel. I don't know what "marking file sections with pressed left mouse" means. The size of the directory probably shouldn't matter -- it just affects how long it takes to build the browse database (red config in the bottom right).

2. Git issues should be reported to the vscode team: https://github.com/Microsoft/vscode . I haven't seen the git issues you describe.

3. Go to Definition does open a new file if the definition is in a new file and the current file is not in preview mode. You can double-click the file in the Explorer tab to get the file out of the preview mode (or right-click the tab and choose Keep Open). You can use Alt+<back arrow> to go back to the previous spot. You can also use Peek Definition to avoid losing your current context.

4. By "faster" do you mean ship it faster or make the implementation faster? I haven't seen any slowness with the current autocomplete.

5. Our extension doesn't do anything special with the console output color. Could you ask on the VS Code questions forum?: http://stackoverflow.com/questions/tagged/vscode  .

6. It sounds like you're having a problem with the VS Code Insiders build. It can be installed side-by-side with VS Code. It should be at /usr/share/code-insiders/code-insiders.

FYI, we are not part of the VS Code team. We are a completely separate team that implements functionality for the C++ extension.

**Comment by pieandcakes** [comment]
Please file these questions/issues at https://github.com/Microsoft/VSCode . 

Thanks
