### ISSUE TITLE
Remote SSH: Syntax Highlighting/Coloring Problems in erlnag

### ISSUE THREAD

**Issue by mhrdq8i** [microsoft/vscode-cpptools#5120]
I use vscode for my erlang development.

In my local machine, everything is, OK. but when I use ssh to connect into my remote server the Erlang syntax highlight does not work.

![erlang](https://user-images.githubusercontent.com/40826835/76678072-0f336300-65ea-11ea-8dd3-28761b24e079.jpg)

I use [ssh-remote](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) to handle my ssh connection.

what is the solution to my problem?

**Comment by Colengms** [comment]
Hi @mehrdad-drpc .  This repo is for the C/C++ Extension for VS Code.  Are you using another extension that provides language services for Erlang?

**Comment by mhrdq8i** [comment]
Hi @Colengms, oh sorry.
My bad :|
I use this extension for erlang, 
![vscode-erlang](https://user-images.githubusercontent.com/40826835/76827948-24e89880-6835-11ea-8114-1437cf82c831.png)
