### ISSUE TITLE
Linux: cppdbg seems to ignore cwd

### ISSUE THREAD

**Issue by bsekura** [microsoft/vscode-cpptools#5121]
OS: Arch Linux
VSCode: 1.43.0
cpptools: 0.26.3

launch.json:

```json
{
    "version": "0.2.0",
    "configurations": [        
        {
            "name": "(Linux)",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/target/debug/stuff",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [
                { 
                    "name": "DISPLAY",
                    "value": ":0.0"
                }
            ],
            "externalConsole": false,
            "MIMode": "lldb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
    ]
}
```
Expected result: 
when debugged, the working directory of `stuff` executable is set to workspace folder.

Actual result:
When `stuff` is debugged, its working directory is not workspace folder, but the executable folder.

As a side note, on Windows, the process working directory is correctly set to workspace folder.

**Comment by WardenGnaw** [comment]
We should be setting `cwd` to GDB with ` -environment-cd`.

Can you enable logging?
You can do this by adding:
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

**Comment by bsekura** [comment]
What does "-environment-cd" mean?
Do I need to "-environment-cd" to environment settings in a configuration?

It would be nice to have consistency, such that the "cwd" property of the configuration does necessary setup automatically for a platform.

**Comment by cs96and** [comment]
I'm seeing this issue too when trying to use LLDB as the debugger.  I tried setting the `setupCommands` to change the directory but it makes no difference

                {
                    "description": "Set working directory",
                    "text": "-environment-cd ${workspaceFolder}",
                    "ignoreFailures": false
                }

**Comment by bsekura** [comment]
Appears to be working as expected, so I'm closing it. Thank you!

**Comment by cs96and** [comment]
Not sure why this was closed.  Still doesn't work for me.

**Comment by floooh** [comment]
I still have the same issue on macOS with MIMode=lldb.
