### ISSUE TITLE
linter stopped working properly

### ISSUE THREAD

**Issue by rachitsaksena** [microsoft/vscode-cpptools#5122]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Microsoft Windows 10 Home, version: 10.0.18362 Build 18362
- VS Code Version: 1.43
- C/C++ Extension Version: <s>14.16.27023</s> -> 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- The snippets have stopped working(e.g. main printf, scanf etc. 
- Syntax highlighting is not functioning properly e.g. cin, cout, vector, set, etc. are not getting highlighted anymore.
- Problems are no longer being detected. No errors are being shown, e.g. expected ';'

![image](https://user-images.githubusercontent.com/44171107/76733600-2196d380-6787-11ea-8bc2-82a5da371a41.png)

I have checked all the setting mentioned in the simliar issue : https://github.com/Microsoft/vscode-cpptools/issues/2164

I have completely uninstalled and reinstalled the extension.

**Comment by michelleangela** [comment]
@rachitsaksena 

Can you provide the following logs to help get more information about the issue:
1. Log output from running the command `C/C++: Log Diagnostics`
2. Log output from the language server. To enable logging for the language server, see instructions at https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server

Also, you noted that the version of the C/C++ extension is `14.16.27023`. Could you verify the version again as the current latest version is `0.26.3`?

**Comment by rachitsaksena** [comment]
Here is the C/C++:  Log diagnostic

```
-------- Diagnostics - 17/3/2020, 12:26:07 pm
Version: 0.26.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.17763.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\Academics\Coding Practice\Christmas Spruce.cpp ]:
    D:\Academics\Coding Practice\Christmas Spruce.cpp
Translation Unit Configurations:
[ D:\Academics\Coding Practice\Christmas Spruce.cpp ]:
    Process ID: 15484
    Memory Usage: 43 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        C:\Users\Rachit\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7
        C:\Users\Rachit\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu\c++\7
        C:\Users\Rachit\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\c++\7\backward
        C:\Users\Rachit\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include
        C:\Users\Rachit\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\local\include
        C:\Users\Rachit\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\gcc\x86_64-linux-gnu\7\include-fixed
        C:\Users\Rachit\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include\x86_64-linux-gnu
        C:\Users\Rachit\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\include
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70400
Total Memory Usage: 43 MB

```
Log output from the language server
```
cpptools/getCodeActions: 8
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/getCodeActions: 9
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/Academics/coding%20practice/Christmas%20Spruce.cpp
Queueing IntelliSense update for files in translation unit of: D:\Academics\Coding Practice\Christmas Spruce.cpp
cpptools/cpptools_finishUpdateSquiggles
Update IntelliSense time (sec): 0.253
cpptools/textEditorSelectionChange
cpptools/getCodeActions: 10
cpptools/activeDocumentChange
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///d%3A/Academics/coding%20practice/Christmas%20Spruce.cpp
Queueing IntelliSense update for files in translation unit of: D:\Academics\Coding Practice\Christmas Spruce.cpp
cpptools/cpptools_finishUpdateSquiggles
Update IntelliSense time (sec): 0.259
```
I updated the version in the question. Sorry for the error.

**Comment by sean-mcmanus** [comment]
Can you re-open your folder under WSL using the Remote WSL extension? That will enable our extension to run our Linux binary and provide a better experience.

**Comment by rachitsaksena** [comment]
![image](https://user-images.githubusercontent.com/44171107/77040192-73d13200-69dd-11ea-9fa6-ef745f890abc.png)
@sean-mcmanus That does fix the linter but I am pretty sure vector and cin should be covered in syntax highlighting and it is malfunctioning.(Please correct me if I am wrong)
Also, why isnt the non wsl version not running the same way and how to correct that?

**Comment by bobbrow** [comment]
The syntax coloring issue with the Remote-WSL extension is known. See #3942.  We'll be updating the extension to use the new semantic tokens provider when VS Code moves those APIs to the stable release.

**Comment by bobbrow** [comment]
If the coloring issue is a deal breaker for you, you can try setting `compilerPath` to `/usr/bin/gcc` and reload the window and run the "Reset IntelliSense Database" command.  If I had to guess, something got messed up when you told it to use the MSVC compiler and then it switched to WSL mode with the case-sensitive file system.
