### ISSUE TITLE
Change clang-format "Visual Studio" fallback style to use NamespaceIndentation All

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5124]
It currently defaults to None. The fix should only require, adding text ", NamespaceIndentation: All" to the description of the clang_format_fallbackStyle in TypeScript and to the clang_format_style variable on the language server.

Unless we think VS's default formatting should be changed instead.

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
