### ISSUE TITLE
Recognize macro names as function names

### ISSUE THREAD

**Issue by ppggff** [microsoft/vscode-cpptools#5139]
Following code make vscode-cpptools recognising macro name as function name:
```
#define foreach(i, n)	\
	for (i = 0; i < n; i++)

void
test(void)
{
	int i, n;

	foreach(i, n)
	{
		/* ... */
	}
}
```

The correct function name should be `test(void)`, but it shows `foreach(i, n)` on outline.

**Comment by sean-mcmanus** [comment]
This is "by design" (limitation of our workspace symbol parser). The expected workaround is to create a file named cpp.hint in your workspace folder that has contents
```
#define foreach(i, n)
```
See https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2019 for more info.
