### ISSUE TITLE
Outline and Go to Symbol in file is incorrect (shows random results) if the opened file is under files.exclude

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5142]
If a files.exclude is manually opened, the outline view can have random symbols shown in it.

Ideally, the correct symbols would still be shown (or else something better).

**Comment by Colengms** [comment]
I'm not able to repro the random results, but I do see that an Outline is initially provided and is not updated as changes are made to the file.  We should disable Outline entirely for an excluded file.

**Comment by sean-mcmanus** [comment]
It's showing a "random" subset of all the symbols defined in the workspace. It should just return 0 results. We could tag parse the excluded file to have the document outline symbols appear, but that would result in symbol search and other operations returning an excluded file, which is probably not desired.
