### ISSUE TITLE
[Internal] Code in the namespace cannot be indented properly after press “Shift + Alt + F”

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode-cpptools#5144]
Repro steps:
1. Install VSCode with extension "C/C++ 0.27.0-insiders3"
2. Create and open a new workspace 
3. Add a cpp file to it with following code 
namespace foo {
	namespace bar {
		namespace baz {
			int qux = 42;
		}
	}
}

namespace foo::bar::baz
{
    int func1(float var1) {}
}
4. Pressing Shift + Alt + F to format the document

Expected:
The code was indented as below
![image](https://user-images.githubusercontent.com/29274719/76933076-8e09f380-68a9-11ea-82dc-3191ebc43bbb.png)

Actual:
Code is left justified
![image](https://user-images.githubusercontent.com/29274719/76933101-9e21d300-68a9-11ea-8329-fcbd57459a9b.png)

**Comment by sean-mcmanus** [comment]
This is the same issue as https://github.com/microsoft/vscode-cpptools/issues/5124 .

It isn't a regression as far as I can tell.
