### ISSUE TITLE
Copy with syntax highlighting doesn't use syntax highlighting

### ISSUE THREAD

**Issue by KrzaQ** [microsoft/vscode-cpptools#5145]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7
- VS Code Version: 1.43.0 (system setup)
- C/C++ Extension Version: 0.27.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): wandbox, yes
- Does this issue involve using SSH remote to run the extension on a remote machine?: yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

This extension changes syntax highlighting of C++ files. For example, with the extension disabled, this is what I see:
![](https://i.imgur.com/ajWHY7t.png)
And with it enabled:
![](https://i.imgur.com/2w7fgiW.png)

However, in both cases, when I copy the code into Google Docs or Libre Office Writer (I expect this behavior will be identical for other applications, too), I always end up with the former.

**Steps to reproduce**

1. Write code that has different syntax highlighting than the VS Code default
2. Copy
3. Paste into a rich formatting editor

**Expected behavior**
The pasted code uses the new formatting

1. Logs from the command `C/C++: Log Diagnostics`
2. Logs from [the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
 -->
<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 3/18/2020, 8:43:39 AM
Version: 0.27.0-insiders3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/krzaq/code/cpptest/wb.cpp ]:
    /home/krzaq/code/cpptest/wb.cpp
Translation Unit Configurations:
[ /home/krzaq/code/cpptest/wb.cpp ]:
    Process ID: 2472712
    Memory Usage: 43 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/9.3.0
        /usr/include/c++/9.3.0/x86_64-pc-linux-gnu
        /usr/include/c++/9.3.0/backward
        /usr/local/include
        /usr/lib/clang/9.0.1/include
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=90001
Total Memory Usage: 43 MB
```
</details>

**Screenshots**

Google docs, copied from the example with red "module" global variable:
![](https://i.imgur.com/bZSzH5P.png)

**Additional context**

**Comment by Colengms** [comment]
Hi @KrzaQ .  Our extension is using a [VS Code API](https://code.visualstudio.com/api/references/vscode-api#TextEditorDecorationType) to apply colors in  the editor.  Our extension does not have any control over copy operations in the editor.  You will see the same behavior with other extensions that use this API.  Consider reporting this to [the VS Code repo](https://github.com/microsoft/vscode).
