### ISSUE TITLE
About  configuring the C development environment

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-cpptools#5149]
@1470391328 commented on [Tue Mar 17 2020](https://github.com/microsoft/vscode-python/issues/10634)

I  like vscode very much, i give up the vs2019 to choose vscode as my C ide. But the problem is that:
Configuring the C development environment on vscode is too complex for people who have not learned programming.
 Can you provide more convenient configuration function?

---

@karthiknadig commented on [Wed Mar 18 2020](https://github.com/microsoft/vscode-python/issues/10634#issuecomment-600816836)

@1470391328 This should go to https://github.com/Microsoft/vscode-cpptools/issues

**Comment by sean-mcmanus** [comment]
What are the required configuration steps in your scenario that are "too complex"? Is this in regards to configuring Intellisense, the debugger, and/or the build/tasks.json? The configuration steps will depend on your build method and project details. Did you have any suggestions on what we could do to make configuration easier?
