### ISSUE TITLE
Configuration UI shows errors when older versions of cl.exe are specified

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5151]
When compilerPath is set to an old, non-existent version or non-existent path, such as

"C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.25.28508/bin/Hostx64/x64/cl.exe"

The UI gives the error

"Compiler path with spaces and arguments is missing double quotes " around the path.
Cannot find: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.25.28508/bin/Hostx64/x64/cl.exe".

The bug doesn't repro with 0.26.3. Without pending 0.27.0 release, the c_cpp_properties.json also shows squiggle errors (which didn't appear previously due to another bug).

**Comment by michelleangela** [comment]
For clarification, the compilerPath is valid for the following "cl.exe" inputs:
1. cl.exe
2. <valid_dir_path>/cl.exe
3. <invalid_dir_path>/cl.exe
4. <old_version_of_cl_path>/cl.exe

If the compiler is cl.exe, then any msvc IntelliSenseMode is valide.
