### ISSUE TITLE
OpenCV: not authorized to capture video (when debugging)

### ISSUE THREAD

**Issue by DickyQi** [microsoft/vscode-cpptools#5154]
Type: Debugger

**Describe the bug**
- OS and Version: MacOS 10.15.3
- VS Code Version: 1.43.0
- C/C++ Extension Version:0.27.0-insider3

OpenCV: not authorized to capture video (status 0), requesting...
This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by sean-mcmanus** [comment]
What is this about? Our extension doesn't use OpenCV.

**Comment by DickyQi** [comment]
I using VS code to debug c++/python project which is base on opencv library, and project need to access system camera hardware. If I start app with command line, then I can access system camera with no any issue. If I using cppdbg launch app, then it will cause authorize issue. This problem appeared since I update C/C++ Extension. BTW, if I using lldb in vscode to launch app, camera can be authorized and working fine.

**Comment by sean-mcmanus** [comment]
@WardenGnaw This sounds like a 0.27.0-insiders3 regression with the new lldb-mi.

**Comment by kunaltyagi** [comment]
I think this is a larger issue. When I launched an executable from the VSCode terminal, I got the same error. Going in the `Security & Privacy` -> `Camera`, I can confirm that VSCode didn't ask for permission of the camera (and didn't receive it), while my terminal application did.

**Comment by Colengms** [comment]
@WardenGnaw
