### ISSUE TITLE
0.27.0-insiders3 regression from C++/CX support -- can't find any symbol on Win7

### ISSUE THREAD

**Issue by gujinfei** [microsoft/vscode-cpptools#5155]
**Type: LanguageService**

**Describe the bug**
- OS and Version: win 7 sp1
- VS Code Version:1.43.0
- C/C++ Extension Version:0.27.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): No
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

I'm working on a computer that does not have access to the Internet. I install the extension by "Install from VSIX..." 
I have the following problems:
* The OUTLINE views show: No symbols found in document 'main.cpp'
* ctrl+shift+o : No symbols found
* "Find all reference": only found local variable, show "No results" when I search function or global variable

**Screenshots**
log infomation：Tag parsing eccountered a error， but it may not matter. Let us
 know if symbols in the file cant be found:
The picture link :https://github.com/gujinfei/res/blob/master/IMG_4339.JPG

**Comment by Colengms** [comment]
Hi @gujinfei .  Have you tried with insiders3?  If it still repro's with insiders3, could you provide the following? : 

 * The contents of your `c_cpp_properties.json`, if any.
 * Enable debug logging using `"C_Cpp.loggingLevel": "Debug"`, and provide the output of the C/C++ output channel leading up to the repro.
 * The results of invoking the command: `C/C++: Log Diagnostics`, while you have a file open that is not working as expected.

**Comment by sean-mcmanus** [comment]
In addition, can you close all the VS Code instances and then make sure no dangling cpptools processes still exist (kill those if they do). And also if you do a Reset IntelliSense Database, do you see any "tag parsing" messages that don't result in the error message?

**Comment by gujinfei** [comment]
@sean-mcmanus @Colengms 
**Thank you for reply**

## more infomation:
* I have tried 0.27.0-insiders3, The result is the same.
* Reboot VS Code instances and  make sure no dangling cpptools processes still exist: The result is the same.
* Reset IntelliSense Database, i can still see ：Tag parsing eccountered a error， but it may not matter. Let us know if symbols in the file cant be found:
* I have tried multiple versions (almost all versions from the "Find All reference" feature to now), and this problem has always existed on my offline machine。I also use cpptools on my MAC, and it works very well

## log and config information:
* The contents of my c_cpp_properties.json:
![cppjson](https://github.com/gujinfei/res/blob/master/json.jpg?raw=true)
* debug log
![debug](https://github.com/gujinfei/res/blob/master/debug_log.jpg?raw=true)
* Log Diagnostics(2 pic)
![log](https://github.com/gujinfei/res/blob/master/diagnostics1.jpg?raw=true)
![log2](https://github.com/gujinfei/res/blob/master/d2.jpg?raw=true)

**Comment by sean-mcmanus** [comment]
Ah, I suspect it may be a problem with Win7. Can you try 0.25.1? That was before we added C++/CX tag parsing capabilities, which could have caused it, but I don't recall other reports like this from Win7 users (I would update to the latest Win7 available, in case certain patches fixed stuff we require).

**Comment by gujinfei** [comment]
@sean-mcmanus 
Thank you very much. 
0.25.1 works!  I can see the symbols.  Everything seems all right！
I hope this problem can be confirmed  and modified in the new version。Thanks again!

**Comment by sean-mcmanus** [comment]
Thanks for the info. This "same" issue was fixed for Win7 with https://github.com/microsoft/vscode-cpptools/issues/4536 , but it looks like we regressed somehow, i.e. the msvcp140.dll and vcruntime140.dll files are missing now. A workaround should be to download the file at https://github.com/microsoft/vscode-cpptools/releases/download/0.26.2-insiders/cpptools-win32.vsix, rename it to cpptools-win32.vsix.zip, unzip the files, and copy over the msvcp140.dll and vcruntime140.dll at extension\bin to the extension\bin folder of a newer install of our extension. Or keep using 0.25.1 until we release a fix.

**Comment by sean-mcmanus** [comment]
Actually, 0.26.3 appears to have the fix as well, i.e. it's an "insider-only" bug, which explains why we haven't gotten that many complaints yet.

**Comment by gujinfei** [comment]
@sean-mcmanus Thanks for your replying.
I have tried 0.26.2 , it doesn't work. When I " reset Intellisense database", i can still see: Tag parsing eccountered a error， but it may not matter ....  
The problem on my machine does not seem to be caused by these two libraries
Until now，Only 0.25.1 works on my machine.

**Comment by sean-mcmanus** [comment]
This is fixed with 0.27.0-insiders4 now.

**Comment by gujinfei** [comment]
0.27.0-insiders4 cant work on the machine : Tag parsing eccountered a error ....
I have tried 0.27.0-insiders4 on another win7 sp1, it works well. 
It seems this problem only exist on my offline machine. Maybe some files are missing from the machine.

**Comment by sean-mcmanus** [comment]
Do you see 3 DLLs under `C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-0.27.0-insiders4\bin`? 2 of those DLLs were missing with 0.27.0-insiders3. It's possible we only run on Win7 SP1 due to other DLLs that are required on older Win7 OS's. Can you upgrade your OS to match the Win7 SP1 machine?

**Comment by sean-mcmanus** [comment]
To get the potentially missing DLLs, you could try to do the following steps:
1. Download the LLVM 9.0.1 installer executable from https://releases.llvm.org/download.html for Windows 32-bit (not 64-bit).
2. Install it.
3. Go to C:\Program Files\LLVM\bin .
4. Sort by "Date Modified".
5. Copy the DLLs with a "Date Modified" of 2018 or older -- there should be 44.
6. Paste all those DLLs into the `C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-0.27.0-insiders4\bin` folder.
7. Check if that fixes the issue.

If you can see which of those 44 DLLs is missing from your older Windows install, we might be able to add those to future releases.

**Comment by gujinfei** [comment]
Thanks for your patience and reply.
With your help, I can use 0.27.0 insiders4 normally
I follow your prompts, Download LLVM, and copy 44 DLLs to the corresponding directory, it takes effect.
At the same time that vscode works normally, I start to delete the DLL, and there are 22 DLLs left. These 22 DLLs are being used by the program. 
Thanks again.
![dll](https://github.com/gujinfei/res/blob/master/dll.jpg?raw=true)

**Comment by sean-mcmanus** [comment]
Thanks for the info. I've updated our build to include those other DLL dependencies.

**Comment by sean-mcmanus** [comment]
0.27.0-insiders5 has the missing DLLs added (https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0-insiders5).
