### ISSUE TITLE
Unable to start debugging.LLDB exited unexpectedly with exit code 134(0x84)

### ISSUE THREAD

**Issue by bruce1408** [microsoft/vscode-cpptools#5159]
Type: Debugger

while debug the C++ code , the vscode will display a window that shows 
**Unable to start debugging. LLDB exited unexpectedly with exit code 134 (0x86)**

**envs**
- OS and Version: macOS 10.13.6
- VS Code Version:  VScode 1.43.1
- Other extensions you installed : C/C++, Code Runner, C++ intellisense

**lanuch.json**
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch C++",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}.out",
      "args": [],
      "cwd": "${workspaceFolder}",
      "stopAtEntry": true, // if true then stop at the main entry (function)
      "environment": [],
      "externalConsole": true,
      "MIMode": "lldb",
      "preLaunchTask": "build C++"
    }
  ]
}
```

**task.json**
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "build C++",
      "type": "shell",
      "command": "g++",
      "args": [
        "${file}",
        "-std=c++17",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}.out",
        "-g"
      ],
      "group": "build",
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "new",
        "showReuseMessage": true,
        "clear": false
      }
    }
  ]
}
```

**Comment by sean-mcmanus** [comment]
It sounds like you're hitting issue https://github.com/microsoft/vscode-cpptools/issues/5146 (assuming you're using 0.27.0-insiders3). There's a workaround described at https://github.com/microsoft/vscode-cpptools/issues/5146#issuecomment-600804061 .

**Comment by bobbrow** [comment]
This should be fixed in insiders4

**Comment by xuancong84** [comment]
I also encounter the same problem. It is not related to issue #5146 and its workaround does not work here.

**Comment by clarkttfu** [comment]
> I also encounter the same problem. It is not related to issue #5146 and its workaround does not work here.

Same issue:
Version: 1.48.2
MacOS 10.15.6
cpptols 0.29.0
