### ISSUE TITLE
C++ extension not working.

### ISSUE THREAD

**Issue by shshnkreddy** [microsoft/vscode-cpptools#5161]
**Type: LanguageService**

C++

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.43
- C/C++ Extension Version: 0.27.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

*Works for a while everytime I re-install the extension. But when I reload the window, it says error loading extension.

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
What is the exact error message?

Can you try setting the C_Cpp.updateChannel setting to "Default", then wait for it to downgrade to 0.26.3, i.e. does 0.26.3 work?

**Comment by shshnkreddy** [comment]
![UpdateChannel](https://user-images.githubusercontent.com/45118450/77222979-4a9bd780-6b7e-11ea-84d3-fe9ae1ec5726.png)
It is already on Default.
The error occured when asked to reload the window for updates.
![B](https://user-images.githubusercontent.com/45118450/77223021-cb5ad380-6b7e-11ea-8e52-720e74f33b70.png)
![A](https://user-images.githubusercontent.com/45118450/77223022-cd249700-6b7e-11ea-820f-f1c4fe799405.png)

**Comment by shshnkreddy** [comment]
![C](https://user-images.githubusercontent.com/45118450/77223151-03aee180-6b80-11ea-9c32-6486bf6af5d6.png)
Version -0.26.3 is working.
