### ISSUE TITLE
Planned intellisense support for C++20

### ISSUE THREAD

**Issue by TerensTare** [microsoft/vscode-cpptools#5162]
I am using the C++ extension on Windows 10 with Visual Studio 2019 Build Tools. My "project" is written in C++17, and since it isn't a big project (recently started it, only about 20 files totally) I decided to migrate to C++20 since the Visual C++ compiler provides the /std:c++latest switch. I noticed that in VSCode, the intellisense had problems recognizing new C++20 keywords/reserved words such as module/concept/requires. My question is: is there momentally any plan to support intellisense for C++20, and if so, when is it planned to be "publicly available" ?

**Comment by sean-mcmanus** [comment]
It's being worked on, with more C++ features being added over time.
