### ISSUE TITLE
Can't open file in some situation,file path repeats

### ISSUE THREAD

**Issue by schtonn** [microsoft/vscode-cpptools#5166]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1809
- VS Code Version: 1.43.1
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them):C/C++ IntelliSense,C/C++ Compile Run
- Does this issue involve using SSH remote to run the extension on a remote machine?: I don't have remote machine, what should I do
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
In a workspace with only one .cpp file and auto configured .vscode folder, and only one extension enabled.

**Steps to reproduce**

1. Make some mistake in code
2. Compile
3. Show Errors
4. Click on the problem
5. In some situation, unable to open cpp, and file path repeats

**Expected behavior**

open the cpp on click

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 23/03/2020, 19:27:50
Version: 0.27.0-insiders3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\MinGW\\bin\\gcc.exe",
    "cStandard": "c11",
    "compilerArgs": [],
    "cppStandard": "c++98",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\liangliang\Desktop\test\test.cpp ]:
    C:\USERS\LIANGLIANG\DESKTOP\TEST\TEST.CPP
Translation Unit Configurations:
[ C:\Users\liangliang\Desktop\test\test.cpp ]:
    Process ID: 7848
    Memory Usage: 65 MB
    Compiler Path: C:\MinGW\bin\gcc.exe
    Includes:
        C:\MINGW\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE\C++
        C:\MINGW\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE\C++\I686-W64-MINGW32
        C:\MINGW\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE\C++\BACKWARD
        C:\MINGW\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE
        C:\MINGW\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE-FIXED
        C:\MINGW\I686-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++
    IntelliSense Mode: gcc-x86
    Other Flags:
        --g++
        --gnu_version=80100
Total Memory Usage: 65 MB


cpptools/didChangeCppProperties
$/setTraceNotification
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/60652675/77311943-13732500-6d3c-11ea-9268-82a26e1fb92f.png)
![image](https://user-images.githubusercontent.com/60652675/77311958-18d06f80-6d3c-11ea-8ac8-ec430c1fa9cb.png)
![image](https://user-images.githubusercontent.com/60652675/77312017-25ed5e80-6d3c-11ea-80f8-efe562df54b1.png)
![image](https://user-images.githubusercontent.com/60652675/77312050-30a7f380-6d3c-11ea-8f4e-e77719cfa036.png)
**Additional context**

**Comment by Colengms** [comment]
Hi @schtonn .  Based on the output in the Problems tab, this error message appears to be coming from gcc.  We do provide a `problemMatcher` for gcc in our package.json.

```
    "problemMatchers": [
      {
        "name": "gcc",
        "source": "gcc",
        "owner": "cpptools",
        "fileLocation": [
          "relative",
          "${workspaceFolder}"
        ],
        "pattern": {
          "regexp": "^(.*):(\\d+):(\\d+):\\s+(?:fatal\\s+)?(warning|error):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "message": 5
        }
      }
    ],
```

Can you get the error message that is actually being reported by gcc, by compiling from a terminal?  Perhaps there is something about that message causing it not to be parsed correctly by the problem matcher.

It looks like it was able to discern the file path, as it's listed under it in the Problems tab.  If the path is being parsed correctly, this may be a VS Code bug.

**Comment by schtonn** [comment]
The message:
```
c:\Users\liangliang\Desktop\test\test.cpp: In function 'int g(int)':
c:\Users\liangliang\Desktop\test\test.cpp:4:2: error: return-statement with no value, in function returning 'int' [-fpermissive]
  return;
  ^~~~~~
The terminal process terminated with exit code: 1
```

I opened it in another workspace and it looks like the path is separated into two parts.
The first part is the path to the workspace folder, and the second part is the path to the file.
![image](https://user-images.githubusercontent.com/60652675/77389394-0bfc5c00-6dce-11ea-8fd0-6552d97de970.png)
```
{
	"resource": "/c:/Users/liangliang/Desktop/program/c:/Users/liangliang/Desktop/test/test.cpp",
	"owner": "cpptools",
	"severity": 8,
	"message": "return-statement with no value, in function returning 'int' [-fpermissive]",
	"source": "gcc",
	"startLineNumber": 4,
	"startColumn": 2,
	"endLineNumber": 4,
	"endColumn": 2
}
```

**Comment by schtonn** [comment]
So when the problem is detected by IntelliSense, the path will be correct subfolder in the workspace folder, but when detected by compiling, it will report a full path.
![image](https://user-images.githubusercontent.com/60652675/77398592-cbf3a400-6de2-11ea-81b4-40ed57310b2d.png)

**Comment by Colengms** [comment]
Hi @schtonn .  It looks like this is a known issue: https://github.com/microsoft/vscode-cpptools/issues/4355

It looks like this was addressed by VS Code: https://github.com/microsoft/vscode/issues/74824

We have a PR that will address the issue: https://github.com/microsoft/vscode-cpptools/pull/3916
It should go in the our next release (after 0.27.0)

In the meanwhile, you could work around the issue by overriding the gcc problem matching by adding the following to tasks.json : 

```
"problemMatcher": { "base": "$gcc", "fileLocation": "absolute" }
```

or: 

```
"problemMatcher": { "base": "$gcc", "fileLocation": "autoDetect" }
```
