### ISSUE TITLE
git support of vscode

### ISSUE THREAD

**Issue by CDitzel** [microsoft/vscode-cpptools#517]
I am working a large directory and opened vscode in the root folder.

However, in the git area I am only shown the changed files of that very directory rather than those of subdirectories as well.

How can i change that?

**Comment by sean-mcmanus** [comment]
Maybe try changing "git.allowLargeRepositories" to true? You should see the git changes in the subdirectories too. It works for me. Make sure your .gitignore file isn't excluding stuff. It's also possible that git is crashing or taking too long. Our C++ team doesn't control any of the git stuff in VS Code.

**Comment by CDitzel** [comment]
thank you

**Comment by pieandcakes** [comment]
The VSCode repo is https://github.com/Microsoft/vscode
