### ISSUE TITLE
View a pointer as a 2D array in the debugger

### ISSUE THREAD

**Issue by johnjohnlin** [microsoft/vscode-cpptools#5177]
As reported in https://github.com/microsoft/vscode-cpptools/issues/172, we can use `*some_pointer@10` instead of `*(int(*)[10])some_pointer` to print a 10-element array of type int.

Is there any shortcut for debugging a 2D array such as `*(int(*)[10][10])(some_pointer)`?

**Comment by Colengms** [comment]
@WardenGnaw

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it*

**Comment by zdx-alex** [comment]
I met this problem too,  if I create a secondary pointer like this:
`
    int** secondary_pointer = new int*[100];
    for(int i=0;i<100;i++){
        secondary_pointer[i] = new int[10];
        memset(secondary_pointer[i],0,sizeof(int)*10);
    }
    //then, how can i see secondary_pointer as 2-D array?
`
how to show values of secondary_pointer in a convenient way in vscode when I'm in debugger?
