### ISSUE TITLE
Visual studio code + clang-format has not effect under Linux

### ISSUE THREAD

**Issue by sylwa06** [microsoft/vscode-cpptools#518]
Clang-format VS code pluggin is running but does'nt make the job at all on my linux system.
Exactly the same approach works nicely under Windows 10.

I've installed VS code 1.9.1 along with the Clang-Format pluggin 1.1.1 under a scientific linux :

```
> uname -a
> Linux matis 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 06:09:11 CST 2016 x86_64 x86_64 x86_64 GNU/Linux)
```

My settings.json looks to be properly set up :

```
{
    "window.zoomLevel": 1,
    "editor.formatOnSave": true,
    "editor.tabSize": 2,
    "extensions.autoUpdate": true,
    "clang-format.style": "LLVM"
}

```
But nothing occurs when saving a .h or .C code file...

I did the exactly same approach under Win10 and it works smoothly.

May I ask you some hints please ?

All the best

Sylvain

**Comment by sean-mcmanus** [comment]
We don't own the Clang-format extension. Can you file a bug with them? Are you using the C++ extension? If your issue only repros when the C++ extension is installed then we could be causing a problem. The C++ extension implements formatting too, but Scientific 7 is not supported unless you install glibc >= 2.18 (and we require a 64-bit OS). You can try setting "C_Cpp.formatting": "Disabled".

**Comment by sylwa06** [comment]
Hi Sean,
many thanks for your answer.

Yes I've installed the ms-vscode.cpptools as well. 
Set "C_Cpp.formatting": "Disabled" doesn't help.
I've just filed an issue to xaver.clang-format.
I'll let you know if I get some answer from there.

All the best

**Comment by sylwa06** [comment]
Hi Sean,
The problem comes from the outdated version of LLVM library installed on my scientific linux.
Thanks for your help.
With best regards
Sylvain
