### ISSUE TITLE
VSCode Showing Fake Error In Cpp-Properties

### ISSUE THREAD

**Issue by pitromattio** [microsoft/vscode-cpptools#5189]
VSCode Version: 1.43.2
OS Version: Windows 10 1909
Cpp Version: 0.27.0-insiders4

In the c_cpp_properties.json file, in the .vscode folder, VSCode says there are 4 errors. All those errors are because it cannot find a path to certain folders, but it is because they are under the mac configuration and I am on windows. Those are in fact fake errors, and they have never showed up before yesterday, when I opened the c_cpp_properties.json file to edit some cpp configurations, and those errors just popped up. The squiggly line below them is yellow instead of red, but its really annoying and I don't know how to remove it.

![image](https://user-images.githubusercontent.com/22168596/77555169-3ece4f00-6eb7-11ea-94b6-ccaa353b385e.png)

**Comment by michelleangela** [comment]
@pitromattio 

The input validation for the c_cpp_properties.json should only be applied to the current _active_ configuration. Can you check which configuration was active for that session?

The name of the active configuration will appear at the right side of the VS Code status bar when there is a C or C++ file in focus.
![image](https://user-images.githubusercontent.com/38734287/77567761-de261e80-6e84-11ea-9aa1-ecd478178998.png)

**Comment by pitromattio** [comment]
Oh ok never mind it was set for some reason to Mac... changed it back to Win32 and that fixed the problem. Thank you
