### ISSUE TITLE
Display compiler notes in Problems window

### ISSUE THREAD

**Issue by mqtthiqs** [microsoft/vscode-cpptools#5191]
**Type: LanguageService**

When I hit "Start Debugging" and there is a compiler error in my file, the Problems pane shows me only "errors" and "warnings", but ignores "notes". These are essential when working on template-heavy code; please show them, maybe as sub-lists under their respective errors. 

It is the case at least for single-file, single-project.

- OS and Version: MacOS Catalina
- VS Code Version: 1.43.2
- C/C++ Extension Version: 0.26.3

Example with this minimal file:
```
template<class T>
struct C {
    C(T x) {}
};

int main() {
    C<float> x {"hello"};
}
```
The compiler emits this (I can see it in the terminal):

```
> Executing task: /usr/bin/clang++ -g /Users/mpuech/Desktop/test/test.cc -o /Users/mpuech/Desktop/test/test <

/Users/mpuech/Desktop/test/test.cc:7:14: error: no matching constructor for initialization of 'C<float>'
    C<float> x {"hello"};
             ^
/Users/mpuech/Desktop/test/test.cc:3:5: note: candidate constructor not viable: requires single argument 'x', but no arguments
      were provided
    C(T x) {}
    ^
/Users/mpuech/Desktop/test/test.cc:2:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1
      argument, but 0 were provided
struct C {
       ^
/Users/mpuech/Desktop/test/test.cc:7:15: error: expected ';' at end of declaration
    C<float> x {"hello"};
              ^
              ;
2 errors generated.
```

Yet the Problems pane shows only the two errors (plus one in a different format, I imagine coming from IntelliSense)

**Comment by sean-mcmanus** [comment]
Can you try setting your problemMatcher in your task.json to:
```
            "problemMatcher": [
                {
                    "base": "$gcc",
                    "fileLocation": "absolute",
                    "pattern": [
                        {
                            "regexp": "^(.*):(\\d+):(\\d+):\\s+(?:fatal\\s+)?(warning|error):\\s+(.*)$",
                            "file": 1,
                            "line": 2,
                            "column": 3,
                            "severity": 4,
                            "message": 5
                        }
                    ]
                },
                {
                    "base": "$gcc",
                    "fileLocation": "absolute",
                    "pattern": [
                        {
                            "regexp": "^(.*):(\\d+):(\\d+):\\s+(note):\\s+(.*)$",
                            "file": 1,
                            "line": 2,
                            "column": 3,
                            "severity": 4,
                            "message": 5
                        },
                        {
                            "regexp": "^(.*)$",
                            "message": 1
                        }
                    ]
                }
            ]
```

That works for the case provided, but I'm not sure if gcc outputs messages that aren't matched by that correctly. If there are "notes" that are not 2 lines long or errors/warnings that are more than one line long then this will fail (not sure of a good way to deal with that).

We could update our package.json (at https://github.com/microsoft/vscode-cpptools/blob/master/Extension/package.json#L76 ) gcc problemMatcher to use that, but we'd probably want to get more feedback from users in regards to whether that makes things better or worse.

**Comment by mqtthiqs** [comment]
Thanks, this is better, but still not ideal:
- not all notes appear in the Problems pane (see below)
- the notes don't appear directly below the error they are related to, which is how gcc/clang outputs them.
- this might be unrelated but I'm still seeing each error twice with a different wording (see screenshot)

For instance, here is clang's output:
```

> Executing task: clang++ -g -std=c++17 /Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc <

/Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc:128:22: error: no viable constructor or deduction guide
      for deduction of template arguments of 'zip'
  for (auto [i, x] : zip(range<4>(), a)) {
                     ^
/Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc:18:3: note: candidate function [with T = Range<int, 0,
      4, 1>, Ts = <std::__1::array<int, 4>>] not viable: expects an l-value for 1st argument
  zip(T& t, Ts&... ts) : zip<Ts...>(ts...), t_(t) {}
  ^
/Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc:9:8: note: candidate function template not viable:
      requires 1 argument, but 2 were provided
struct zip : public zip<Ts...> {
       ^
/Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc:131:22: error: no viable constructor or deduction guide
      for deduction of template arguments of 'zip'
  for (auto [i, x] : zip(a, range<4>())) {
                     ^
/Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc:18:3: note: candidate function [with T =
      std::__1::array<int, 4>, Ts = <Range<int, 0, 4, 1>>] not viable: expects an l-value for 2nd argument
  zip(T& t, Ts&... ts) : zip<Ts...>(ts...), t_(t) {}
  ^
/Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc:9:8: note: candidate function template not viable:
      requires 1 argument, but 2 were provided
struct zip : public zip<Ts...> {
       ^
/Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc:134:22: error: no viable constructor or deduction guide
      for deduction of template arguments of 'zip'
  for (auto [i, j] : zip(range<4>(), range<0,8,2>())) {
                     ^
/Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc:18:3: note: candidate function [with T = Range<int, 0,
      4, 1>, Ts = <Range<int, 0, 8, 2>>] not viable: expects an l-value for 1st argument
  zip(T& t, Ts&... ts) : zip<Ts...>(ts...), t_(t) {}
  ^
/Users/mpuech/Documents/Projets/Brouillons/range-iterator-with-zip.cc:9:8: note: candidate function template not viable:
      requires 1 argument, but 2 were provided
struct zip : public zip<Ts...> {
       ^
3 errors generated.
The terminal process terminated with exit code: 1
```

And this is what I see in the Problems pane (each error is mentioned twice, and only two of the 6 notes appear):
<img width="958" alt="Capture d’écran 2020-03-26 à 15 01 49" src="https://user-images.githubusercontent.com/213786/77655479-c0cf7e00-6f72-11ea-8972-26145b68a825.png">

**Comment by sean-mcmanus** [comment]
The reason only 2 notes appears is because VS Code seems them as duplicates. The linking of the notes to errors appears to be covered by https://github.com/microsoft/vscode/issues/55253 . The duplicate errors without the "gcc" label at the end are coming from our IntelliSense process.

**Comment by mqtthiqs** [comment]
> The reason only 2 notes appears is because VS Code seems them as duplicates

Isn't this a bug? Even if VSCode merges duplicate notes, there are 4 distinct notes in the provided example.

> The linking of the notes to errors appears to be covered by microsoft/vscode#55253

Ok, seems so indeed.

> The duplicate errors without the "gcc" label at the end are coming from our IntelliSense process.

Out of curiosity, is that a completely separate process, from a different compiler, and if yes which one? Is there a way to disable it, or to replace it with my own compiler, still keeping error reporting as I type? Sorry if this is covered elsewhere, I'm new to VSCode and this extension.

**Comment by sean-mcmanus** [comment]
Yeah, it looks like VS Code is only showing 1 problem per "location" (i.e. line/column, or file if "kind": "file" is used). That seems like a bug or feature request on VS Code (I couldn't find an existing issue)...you could file an issue at https://github.com/microsoft/vscode (or I could).

Yes, you can disable our IntelliSense process's squiggles via the C_Cpp.errorSquiggles setting. The process is cpptools-srv.exe in 0.27.0-insiders5 (old Microsoft.VSCode.CPP.IntelliSense.Msvc with 0.26.3 or older). That's the one that supports "as you type" errors. The messages come from the EDG front end compiler that runs in a mode that tries to emulate gcc's parsing, but it uses its own error messages.

**Comment by mqtthiqs** [comment]
Got it, thanks.

**Comment by GitMensch** [comment]
@mqtthiqs I suggest to vote on the linking diagnostics issue. Did you create an issue for "duplicates are only resolved by location, not by text" already?
@sean-mcmanus Can you please commit the change concerning "note" to the repo? Or even better: let vscode handle "note" as "information" in general and for this extension only add it to the severity pattern (there are others using "note" as well and so far the only option is to always create an additional pattern for that as note!=info)?

**Comment by sean-mcmanus** [comment]
@GitMensch I was waiting for more feedback as to whether it was a good thing to change or not. We haven't gotten many complaints about this.

**Comment by GitMensch** [comment]
Thanks for the follow up. Yes, it is a good thing to have that matched and according to the screen provided by @mqtthiqs it works well enough. Please include your change from March now.

I still suggest to include "note" as variant of "info" on the vscode side, instead of here, allowing it to be used in more language extensions easily - if this needs longer it is better to hard-wire "note" here for now (providing the solution already) and create a reminder issue to later replace the special handling for it by matching it together with error and warning.

**Comment by sean-mcmanus** [comment]
@GitMensch Adding a "note" problem matcher to our package.json via the method I had previously suggested doesn't appear to work (I can't get the warning/errors to be combined with the notes, only one or the other appears, or none). If you anyone can figure out how, you could submit a PR.
