### ISSUE TITLE
Intellisense does not work on OS X latest for C/C++

### ISSUE THREAD

**Issue by sumonto** [microsoft/vscode-cpptools#52]
Hi,
I have installed Complete C/C++ extension but I still don't see intellisense working for C/C++

Thanks.

**Comment by delmyers** [comment]
@sridmad

**Comment by csholmq** [comment]
"Works" for me on and off. Mostly it does work. Not sure why.

OS X El Capitan running v1.1.1-insiders

**Comment by csholmq** [comment]
Intellisense only "works" in current file for me. When addressing a struct, the actual struct members are nowhere to be seen. The suggestions that do pop up are completely unrelated.

![intellisense](https://cloud.githubusercontent.com/assets/1297882/15678514/e6032200-274e-11e6-87ae-1623d0666ca7.gif)

And as you can see, the search is case sensitive. So not very fuzzy.

Win10.

**Comment by csholmq** [comment]
@sridmad I believe this can be closed. Works on El Capitan.

**Comment by sumonto** [comment]
HiI could not get it to work please elaborate the steps

Thanks

On Tue, Jun 28, 2016 at 1:16 AM -0700, "Sebastian Holmqvist" notifications@github.com wrote:

@sridmad I believe this can be closed. Works on El Capitan.

---

**Comment by csholmq** [comment]
@sumonto I just installed the extension and restarted VSCode. Do you get any errors in one of the console outputs?

**Comment by sumonto** [comment]
Hi,What are your include path setting?
Date: Tue, 28 Jun 2016 11:31:47 -0700

**Comment by dougpuob** [comment]
I got the same problem, it showed members not belongs to that data structure in C.

vscode 1.4.0/Ubuntu

```
typedef struct _TRACE_GEAR {
    char*      szLogPath;
    uint64_t   Level;
    uint64_t   Module;
} TRACE_GEAR, *PTRACE_GEAR;
```

![screenshot from 2016-08-20 15-23-31a](https://cloud.githubusercontent.com/assets/3453968/17829801/6e3e61f2-66ec-11e6-9e1d-f2f2ed1a9f0e.png)

**Comment by sridmad** [comment]
#13  covers enabling accurate auto completion
