### ISSUE TITLE
Function identify failed with Macro with loop

### ISSUE THREAD

**Issue by wzm-victor** [microsoft/vscode-cpptools#5200]
If there is a macro in a function, the symbol of function failed be be identified. Example:
![image](https://user-images.githubusercontent.com/41720825/77620858-430d7180-6f76-11ea-831e-4e81701dc474.png)
In the exmaple, 'test_ok' without macro is identified as a symbol, but 'test_error' is not.

**Comment by sean-mcmanus** [comment]
This is "by design" (limitation of our workspace symbol parser). The expected workaround is to create a file named cpp.hint in your workspace folder that has contents
```
#define ForEach(id, id2)
```
See https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2019 for more info.

**Comment by sean-mcmanus** [comment]
FYI, this is fixed with 1.10.3 (pre-release) -- no cpp.hint is required for this case.
