### ISSUE TITLE
Suggestions for struct field initialization

### ISSUE THREAD

**Issue by SPAstef** [microsoft/vscode-cpptools#5201]
Hi, would it be possible to add support for auto-completion when initializing structs as follows:
```
struct S my_struct = { .a = 10, .b = 20, .c = 30 };
```
Right now it doesen't even get highlighted (but it gets squiggled if the field doesen't exist).
Thanks!

**Comment by sean-mcmanus** [comment]
This is being tracked for C++ designated initializers at https://developercommunity.visualstudio.com/content/problem/822907/cc-intellisense-list-members-doesnt-work-with-desi.html (also https://github.com/microsoft/vscode-cpptools/issues/4610 ). If you have a Microsoft account you could upvote that.

The C case (based on a gcc extension) may be slightly different, but the C++ case would probably need to be fixed first.

**Comment by SPAstef** [comment]
It originally probably was an extension, but I am pretty sure it's in the standard (just checked, paragraph 6.7.9). Thanks for the link and the info!

**Comment by sean-mcmanus** [comment]
Ah, you're right it's an official part of C99, but an extension for C++ compilers prior to C++20.

**Comment by SPAstef** [comment]
I had nothing but nightmares everytime I tried to switch to C++. Inability to pass "anonymous" arrays to functions, 200 casts and initialization kinds (yet not anomimuos init...) and generally the incredible amount of duplication (or n-plication) of ways to do the exact same thing, often really something that the compiler should and does take care himself... But maybe that's just my guess.
