### ISSUE TITLE
Platformio

### ISSUE THREAD

**Issue by ednaramor** [microsoft/vscode-cpptools#5208]
Issue Type: <b>Bug</b>

I have installed "Visual Studio Code" and I am trying to load the "PlatformIO" extension and it can not find Python 3.8.2 which I previously installed on my computer. 

Extension version: 0.26.3
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz (8 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Did you mean to file an issue at https://github.com/platformio/platformio-vscode-ide/issues ? I don't think our C/C++ extension can affect this. Or can you just reinstall Python 3.8.2?

**Comment by ednaramor** [comment]
Thanks, I will try reinstalling Python 3.8.2.


-----Original Message-----

**Comment by robotdad** [comment]
The platformio extension should carry its own Python interpreter, you shouldn't need to install another. Have you happened to get this working yet?
