### ISSUE TITLE
Build task template use absolute path for building but relative path for problemMatcher

### ISSUE THREAD

**Issue by escape0707** [microsoft/vscode-cpptools#5209]
Type: General

## Environments
- OS and Version: Windows_NT x64 10.0.18363
- VS Code Version: 1.44.0-insider
- C/C++ Extension Version: 0.26.3

## Describe the bug
The build task templates on windows, e.g. `g++.exe build active file`, contains:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "g++.exe build active file",
            "command": "C:\\Users\\someone\\scoop\\apps\\gcc\\current\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\Users\\someone\\scoop\\apps\\gcc\\current\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

But the `problemMatcher` `$gcc` use relative path by default. And if there is warnings or errors emitted during the build process, we can't use the problem panel to track it down. Clicking on a problem entity will cause an error notification: 

`Unable to open 'test.cpp': Unable to read file 'd:\Workspaces\test\d:\Workspaces\test\test.cpp' (Error: Unable to resolve non-existing file 'd:\Workspaces\test\d:\Workspaces\test\test.cpp').`

## Potential fixes
Use relative path for build by default, or use absolute path for `problemMatcher` `$gcc` by default.

**Comment by escape0707** [comment]
It's probably better to use absolute path for `problemMatecher` by default, as error in library files reported by compilers will use absolute path anyway.

**Comment by sean-mcmanus** [comment]
This should be fixed by https://github.com/microsoft/vscode-cpptools/pull/3916 .

**Comment by escape0707** [comment]
OK, just subscribed to that PR.

Feel free to close this issue if the problem has been tracked elsewhere,
please.
