### ISSUE TITLE
for loop snippets now working well

### ISSUE THREAD

**Issue by NIRVANALAN** [microsoft/vscode-cpptools#5210]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Deepin 15.11
- VS Code Version: 1.30+
- C/C++ Extension Version:0.26.3
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is 
**Steps to reproduce**

1. create a cpp files with main function
2. type for and generate a for snippet
3. press tab once to locate on the looper name(i by default)
4. use backspace to delete the looper variable
then it comes:
```
for (size_t 0; i < count; i++)
 {
/* code */
}
```
what it should be:
```
for (size_t  = 0;  < count; ++)
{
    /* code */
}

```
**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue. What are your formatting and indentation settings? Do you have some sort of auto-format enabled? If you set C_Cpp.loggingLevel to "Debug" do you see a format occurring?

**Comment by NIRVANALAN** [comment]
Hi, I tried to disable the auto-format settings and it doesn't work;
I tried to reinstall a fresh new vscode and found that it's the conflict with extension vscode-vim
I ll try to reach the vscode-vim extension repo to report this bug, thanks. If you could solve it, that's also nice

**Comment by NIRVANALAN** [comment]
problem solved, this bug is partly due to vscode-vim extension.
