### ISSUE TITLE
Compiler path with spaces produces error

### ISSUE THREAD

**Issue by ivankravets** [microsoft/vscode-cpptools#5215]
Related topic https://community.platformio.org/t/platform-io-compiler-error/12684

1) We provide a full path to the compiler using `compilerPath` option
2) This a path option, so we do not do any modifications because arguments are passed to `compilerArgs`

Yes, we can escape `compilerPath` by default but it looks like a bug.

Thanks!

/cc @valeros @sean-mcmanus

**Comment by sean-mcmanus** [comment]
This issue existed for a "long time" (i.e. in 0.26.3), but the error squiggling was disabled by default in 0.26.3 and 0.27.0-insiders5 fixed that.

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. It's fixed by https://github.com/microsoft/vscode-cpptools/pull/5217 for our 0.27.0 release (planned for Monday).

**Comment by ivankravets** [comment]
Thank you so much! The most important release for our community!

**Comment by sean-mcmanus** [comment]
Fixed with 0.27.0.
