### ISSUE TITLE
CMake macro splitted by formatter

### ISSUE THREAD

**Issue by xq114** [microsoft/vscode-cpptools#5219]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.43.2
- C/C++ Extension Version: 0.26.3
- Other extensions you installed (and if the issue persists after disabling them): yes
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I'm going through a cmake tutorial. Here was the original file before the formatter exerting on the file:
![image](https://user-images.githubusercontent.com/42310255/77814968-fd28e880-70f0-11ea-9708-8d9b03235041.png)
And after that, the file came to
![image](https://user-images.githubusercontent.com/42310255/77814988-234e8880-70f1-11ea-8549-c14469b5a492.png)
I'm wondering why the formatter make the macro being splitted, and thus disabled the macro.

**Steps to reproduce**

1. Open a .h.in file and input
```c
#define Tutorial_VERSION_MAJOR @Tutorial_VERSION_MAJOR@
#define Tutorial_VERSION_MINOR @Tutorial_VERSION_MINOR@
```
2. Format the file

**Expected behavior**

A string between a couple of '@' in the macro should not be modified by the formatter.

<details>
  <summary><strong>Logs</strong></summary>

```
Version: 0.26.3
Current Configuration:
{
    "name": "Win32",
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:/Users/xq114/_src/bin/msys64/mingw64/bin/clang.exe",
    "intelliSenseMode": "clang-x64",
    "cStandard": "c11",
    "cppStandard": "c++11",
    "includePath": [
        "${workspaceFolder}/**",
        "C:/Users/xq114/src/local/include",
        "C:/Users/xq114/src/local/lib"
    ],
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "C:/Users/xq114/src/local/include",
            "C:/Users/xq114/src/local/lib"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\xq114\_doc\FreeSpace\code\cxx\buildsys\tutorial\Step1\TutorialConfig.h.in ]:
    C:\USERS\XQ114\_DOC\FREESPACE\CODE\CXX\BUILDSYS\TUTORIAL\STEP1\TUTORIALCONFIG.H.IN
Translation Unit Configurations:
[ C:\Users\xq114\_doc\FreeSpace\code\cxx\buildsys\tutorial\Step1\TutorialConfig.h.in ]:
    Process ID: 29672
    Memory Usage: 11 MB
    Compiler Path: C:/Users/xq114/_src/bin/msys64/mingw64/bin/clang.exe
    Includes:
        C:\USERS\XQ114\_SRC\BIN\MSYS64\MINGW64\INCLUDE\C++\9.3.0
        C:\USERS\XQ114\_SRC\BIN\MSYS64\MINGW64\INCLUDE\C++\9.3.0\X86_64-W64-MINGW32
        C:\USERS\XQ114\_SRC\BIN\MSYS64\MINGW64\INCLUDE\C++\9.3.0\BACKWARD
        C:\USERS\XQ114\_SRC\BIN\MSYS64\MINGW64\LIB\CLANG\9.0.1\INCLUDE
        C:\USERS\XQ114\_SRC\BIN\MSYS64\MINGW64\X86_64-W64-MINGW32\INCLUDE
        C:\USERS\XQ114\_SRC\BIN\MSYS64\MINGW64\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++11
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=90001
Total Memory Usage: 11 MB
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
It's from clang-format. I don't believe the @ is valid C++, so clang-format is treating it like Objective-C. It's possible there some way to configure it, but I'm not sure. The docs are at https://clang.llvm.org/docs/ClangFormatStyleOptions.html .

**Comment by xq114** [comment]
I've tried a number of compiler(including mingw-g++/mingw-clang/wsl-g++) and the same situation remained. I'm afraid it might be from a historical reason. Anyway, thanks to your replying!
