### ISSUE TITLE
a space is required  between consecutive right angle brackets (use '> >')

### ISSUE THREAD

**Issue by kvedantmahajan** [microsoft/vscode-cpptools#5220]
- OS and version: MacOS Catalina:
- VS Code Version: 1.43
- C/C++ Extension Version: ms-vscode.cpptools

All extensions disabled except one `ms-vscode.cpptools` which is required to run C++ in vscode as per docs.

When I try to build my program including a vector usage. It reports to me with the error mentioned in the title. 

Example usage might look like 

```
vector<vector<int>> &matrix
```

**Comment by ghuser404** [comment]
Does your program build and just shows red squiggles in code or it doesn't build at all? What compiler version are you using? Are you building your program with C++11 or later standard? The problem you described is how C++98 behaved - you had to put space in there. This was fixed in later standards.

**Comment by kvedantmahajan** [comment]
Program builds fine.  This error shows only in output console when hitting rub debug.

C++ compiler ? All what vscode is using. Mentioned the version for the same.

**Comment by ghuser404** [comment]
The used compiler doesn't depend on vscode, but rather on your setup.

Are you on Windows? Are you using cl.exe with Developer Command Prompt for Visual Studio? From what version of Visual Studio did you open the prompt?

Also, please post your tasks.json and c_cpp_properties.json here.

**Comment by kvedantmahajan** [comment]
Did you even read my issue properly?

Warm Regards,
Kushal V. Mahajan

**Comment by alexeilukin404** [comment]
Sorry, I didn't notice you were on Mac. I updated my message, but you didn't see it, saying please post your tasks.json and c_cpp_properties.json here.

**Comment by ghuser404** [comment]
Sorry, I didn't notice you were on Mac. I updated my message, but you didn't see it, saying please post your tasks.json and c_cpp_properties.json here.

**Comment by sean-mcmanus** [comment]
The message if from your clang compiler and not our C/C++ extension. You might need to set "-std=c++11" as a compiler argument in your tasks.json.

**Comment by sean-mcmanus** [comment]
The message from our extension is `"space required between adjacent '>' delimiters of nested template argument lists ('>>' is the right shift operator)"`. If you see that, then your cppStandard setting needs to be increased to c++11 or newer.
