### ISSUE TITLE
can not debug c/c++

### ISSUE THREAD

**Issue by GaussianPrince** [microsoft/vscode-cpptools#5221]
Issue Type: <b>Bug</b>

i configured launch.json, tasks.json, but not enter gebug mode

Extension version: 0.26.3
VS Code version: Code - Insiders 1.44.0-insider (6cf3dd97465b2f4f666b66758991d720e003b0f4, 2020-03-27T05:28:16.333Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ghost** [comment]
i cant even use the g++ command inside the terminal on visual studio. help.

**Comment by WardenGnaw** [comment]
@GaussianPrince Can you share your program, launch.json, tasks.json, and any specific error messages you are getting with hitting the start debug button?

**Comment by WardenGnaw** [comment]
@onlyshvdows Do you have g++ in your path? You can do this by running `which g++`

**Comment by GaussianPrince** [comment]
launch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "cppdbg",
            "request": "launch",
            "name": "debug",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": true,
            "externalConsole": true,
            "MIMode": "lldb",
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "clang++ build active file"
        }
    ]
}

**Comment by GaussianPrince** [comment]
tasks.json

{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "clang++ build active file",
            "command": "clang++",
            "args": [
                "-std=c++17",
                "-stdlib=libc++",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}",
                "--debug",
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ],
}

**Comment by GaussianPrince** [comment]
1.cpp

#include <iostream>
#include <vector>

using namespace std;

class Solution {
public:
    int longestValidParentheses(string s) {
        int i, j, maxans;
        vector<int> dp;

        dp.insert(dp.begin(), s.length(), 0);
        maxans = 0;
        for (i = 1; i < s.length(); i++) {
            if (s[i] == ')') {
                if (s[i - 1] == '(')
                    dp[i] = (i >= 2 ? dp[i - 2] : 0) + 2;
                else if (i - dp[i - 1] > 0 && s[i - dp[i - 1] - 1] == '(')
                    dp[i] = dp[i - 1] + ((i - dp[i - 1] >= 2) ? dp[i - dp[i - 1] - 2] : 0) + 2;
            }
            maxans = dp[i] > maxans ? dp[i] : maxans;
        }
        return maxans;
    }
};

int main(void)
{
    string s;
    Solution sol;
    int ans;

    while (getline(cin, s)) {
        ans = sol.longestValidParentheses(s);
        cout << "result: " << ans << endl;
    }
}

**Comment by GaussianPrince** [comment]
<img width="1278" alt="shortcu" src="https://user-images.githubusercontent.com/24266538/78133626-59716c80-7451-11ea-89b4-68ac71b60cc8.png">

**Comment by GaussianPrince** [comment]
I remember being successful, but I don't know what's going on, I can't do it anymore

**Comment by thorerikflekkum** [comment]
❤️🙈
