### ISSUE TITLE
No program runs in pop up terminal when debug on Mac

### ISSUE THREAD

**Issue by Garithe** [microsoft/vscode-cpptools#5224]
Type: Debugger

**Describe the bug**
- OS and Version: newest 10.15.4
- VS Code Version: 1.43.2
- C/C++ Extension Version: 0.27.0 insiders5

Becasue of the limitation of lldb I set ""externalConsole": true" in launch.json to run program in a
pop up terminal to get the input. But when debug begins nothing runs in a new pop up console.

But when set externalConsole false it runs fine in terminal in vscode(but can't input). 

I thought it might because that vscode can't switch path to workspace. But I switch the path to
it myself, there is still nothing in the console when click start debugging.

By the way  it's nothing about stopAtEntry, I tried both values.

Anyone ever meet this? Please!

**To Reproduce**
My lauch.json is like this(no strange terms at all):

> {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb",
            "preLaunchTask": "clang build active file",
        }
    ]
}

**Comment by Veeupup** [comment]
I have met this problem too.

**Comment by Veeupup** [comment]
@Garithe Have you solved the problem?

**Comment by Garithe** [comment]
> @Garithe Have you solved the problem?

@Veeupup CodeLLDB will do.  Install it from extension. When add configuration, choose "LLDB". But the official extension still has a problem.

**Comment by Veeupup** [comment]
Thanks! It finally worked. You can close the issue.

**Comment by Garithe** [comment]
> Thanks! It finally worked. You can close the issue.

@Veeupup It's a bug of cpptools, not CodeLLDB. It's not been solved.

**Comment by WardenGnaw** [comment]
@Garithe This is similar to https://github.com/microsoft/vscode-cpptools/issues/5079

Its an issue with the later macOS's not displaying the prompt for our Debug Adapter within VS Code to have permissions to use Terminal. 

The workaround is https://github.com/microsoft/vscode-cpptools/issues/5079#issuecomment-626090192

**Comment by Garithe** [comment]
Thank @WardenGnaw. It worked.
