### ISSUE TITLE
No auto suggestions via pointer available

### ISSUE THREAD

**Issue by Schuck84** [microsoft/vscode-cpptools#5228]
Hello,
I have set up a workspace with Intellisense and did the IncludePath definition.
Intellisense is also working partly but doesn't provide any suggestions for a instance variable with pointer access.
In the attachment you find some picture from the editor, VSCode Version and the output from the DiagnosticsLog.
Please let me know if you need further information
[DiagnosticsLog.txt](https://github.com/microsoft/vscode-cpptools/files/4402370/DiagnosticsLog.txt)

![image](https://user-images.githubusercontent.com/34914844/77907672-495b6080-728a-11ea-9084-5bdf45a4cbdd.png)

![image](https://user-images.githubusercontent.com/34914844/77907915-d30b2e00-728a-11ea-90e0-7d35c8e8eee0.png)

Thanks and regards

**Comment by sean-mcmanus** [comment]
Can you provide more repro details? It doesn't repro for me with a simple example:
```
#include <vector>
#include <memory>
struct ss {
    int i;
};
std::vector<std::shared_ptr<ss>> v;
int main()
{
    for (auto s : v)
        s->
}
```
![image](https://user-images.githubusercontent.com/19859882/77968571-86c8e980-729c-11ea-8778-66f14b6f56f1.png)

**Comment by Schuck84** [comment]
The problem is not easy to describe as the complete source code is checked out from a git repository and pointer which I would like to access is derived from other classes.
In a simple example I had no issues but this is more tricky. I try to reproduce it with a more descriptive example.

**Comment by luohancfd** [comment]
Same issue here.
![violentmonkey](https://user-images.githubusercontent.com/6806720/85643028-00d0fa80-b661-11ea-9cc2-b562b4177bc7.gif)

I'm still experiencing the issue. `error` is declared as `Error *&error;` and `all` is a method. I'm using vscode for remote WSL

Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.28.3
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

The repo is here https://github.com/luohancfd/sparta/tree/master/src
You can edit `collide_vss.cpp` and try it
