### ISSUE TITLE
Can not auto show data structure member when coding

### ISSUE THREAD

**Issue by vscpp** [microsoft/vscode-cpptools#523]
For a data structure:
typedef struct {
  UINT16 Address;
  UINT8  Data;
} DATA_STRUCTURE;

DATA_STRUCTURE DataStructure;

when I type DataSturcture.   , it should show Address or Data, I can select one like other editor. but nothing showing.
I set ""C_Cpp.autocomplete": "Disabled",", if set to "Default", many rubbish data.
I suppose C/C++ extension for VS code should focus on editor experience. VS code should be editor not debug tool.

**Comment by sean-mcmanus** [comment]
Address and Data are supposed to be found by autocomplete. There's a bug that randomly causes it to not work. We're working on a fix.

**Comment by bobbrow** [comment]
This should be working now.  I have tried it with both `"C_Cpp.intelliSenseEngine": "Default"` and `"C_Cpp.intelliSenseEngine": "Tag Parser"` settings.
