### ISSUE TITLE
The IntelliSense put error in using namespace std and in double dots to std

### ISSUE THREAD

**Issue by jhaos** [microsoft/vscode-cpptools#5230]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux Ubuntu 18.04.1
- VS Code Version: 1.43.2
- C/C++ Extension Version: 0.27.0
- Other extensions you installed (and if the issue persists after disabling them): No extension installed for c++ only this one.
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Hi I installed in vscode the extension and I put the path in a folder to get out the error of the #include once I made it I tried to use std::cin but I got an error in the second colon saying expected expresion. Also when I tried to put using namespace std; I get in using an type error and in std and expected ; error. 

**Expected behavior**

To let me use using namespaces and not report an error when I write std::cin.

<details>
  <summary><strong>Logs</strong></summary>

```
Sorry but I don't know where is the log file you are asking for.

```
</details>

**Screenshots**

![Captura de pantalla -2020-03-31 03-23-57](https://user-images.githubusercontent.com/32964229/77977155-333bb780-72ff-11ea-96ae-7b63572d7241.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
IntelliSense is parsing your ".c" file as C and not C++, which is "by design". You can add `"*.c": "cpp"` to your files.associations setting to make it parse as C++.

**Comment by jhaos** [comment]
Sorry was a too late thanks for your help it is solved.
