### ISSUE TITLE
Grammer check error for min() function in c++

### ISSUE THREAD

**Issue by Power-tile** [microsoft/vscode-cpptools#5232]
Issue Type: <b>Bug</b>

I used the default min() function in my c++ program. However the grammar checker marked min() as an error and told me "identifier 'min' is undefined". My program can debug and run successfully even when the error exists. See screenshot below.

![image](https://user-images.githubusercontent.com/44731563/77980294-84689d00-7339-11ea-9fbd-78e7e81ba4cd.png)

For the installation and debugger settings, I followed [this link](https://code.visualstudio.com/docs/cpp/config-mingw) for configuration.

Extension version: 0.27.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (0.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
What min method are you trying to call? "std::min"? Have you added "#include <algorithm>" and a "using namespace std;"? It seems like "min" in the global namespace may not be part of the standard, so depending on what headers IntelliSense is picking up, it may not be defined. If you use Go to Def on "min" do you see a list of locations where the min may be defined? If you do C/C++: Log Diagnostics that could help identify which Includes are being used.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. Please re-open for further investigation and with any updated information.
