### ISSUE TITLE
Request Support Developer PowerShell for VS 2019

### ISSUE THREAD

**Issue by ChihweiLHBird** [microsoft/vscode-cpptools#5237]
Issue Type: <b>Feature Request</b>

VS Code and this Microsoft official C++ extension only support the Developer Command Prompt for VS 2019 for debugging with Microsoft C++ compiler. I would like to use it with Developer PowerShell for VS 2019. Is there any plan for that? Thanks.

Extension version: 0.27.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.19041

**Comment by sean-mcmanus** [comment]
What isn't supported? I'm able to launch VS Code from the Developer PowerShell and build/debug with cl.exe.

**Comment by ChihweiLHBird** [comment]
Oh I try it again, and it success. Issue closed.
