### ISSUE TITLE
Nothing happens in debug mode

### ISSUE THREAD

**Issue by DridriLaBastos** [microsoft/vscode-cpptools#5238]
Type: Debugger
When I go in debug mode, nothing happens, clicking on the command does nothing, I can't see my variables wether in the "variables" panel or the "watch" pannel, but the program stop at the breakpoint:
<img width="1552" alt="Capture d’écran 2020-04-01 à 06 16 43" src="https://user-images.githubusercontent.com/19534959/78107830-7593f000-73f6-11ea-976f-a8389451fc4e.png">

<img width="1552" alt="Capture d’écran 2020-04-01 à 09 04 11" src="https://user-images.githubusercontent.com/19534959/78108531-e1c32380-73f7-11ea-8d77-29464c2630fc.png">

But I have two processes that launch and make the fans of my mac make go crazy (name of process %of CPU use)
<img width="259" alt="Capture d’écran 2020-04-01 à 06 36 46" src="https://user-images.githubusercontent.com/19534959/78107997-cb689800-73f6-11ea-8701-9567f3fb6ec9.png">

there are my launch and task files:
launch.json
```json-with-comments
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "clang++ - Générer et déboguer le fichier actif",
			"type": "cppdbg",
			"request": "launch",
			"program": "${fileDirname}/${fileBasenameNoExtension}",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"environment": [],
			"externalConsole": false,
			"MIMode": "lldb",
			"preLaunchTask": "clang++ build active file",
			"logging": { "engineLogging": true, "trace": true, "traceResponse": true }
		}
	]
}
```
tasks.json
```json-with-comments
{
    "tasks": [
        {
            "type": "shell",
            "label": "clang++ build active file",
            "command": "/usr/bin/clang++",
            "args": [
				"-g",
				"--std=c++11",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "/usr/bin"
            }
        }
    ],
    "version": "2.0.0"
}
```
Everything was fine until I changed my program and sudendly, debuging stoped working

**Comment by WardenGnaw** [comment]
Couple of questions:

1. What OS are you on and what version is it?

2. In your `launch.json` you have:
```
"logging": { "engineLogging": true, "trace": true, "traceResponse": true }
```

To investigate, can you share the logs from the debug console?

**Comment by DridriLaBastos** [comment]
macOS 10.15.4 with vscode 1.43.2, the extension version is 0.27.0 and clang is:
```shell
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

The log output is really, really huge, is there a way to redirect it to a file ?

**Comment by WardenGnaw** [comment]
You should be able to right click the window and there should be a `copy all` option. Then you can copy and save it to a file.

**Comment by DridriLaBastos** [comment]
macOS 10.15.4 with vscode 1.43.2, the extension version is 0.27.0 and clang is:
```shell
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
output:

[output.txt.zip](https://github.com/microsoft/vscode-cpptools/files/4413763/output.txt.zip)

**Comment by WardenGnaw** [comment]
Looking at the logs, it seems like VS Code is not requesting the debugger for any variables. So it is not displaying anything. 

We get a `scopes` request so we get the stack frames and we can show the call stack. We are ready to share variable information since we can see a bunch of variables available. 
```
variables=[
{arg="1",name="argc"},
{arg="1",name="argv"},
{name="V"},
{name="v1"},
{name="v2"},
{name="v3"},
{name="v4"},
{name="v5"},
{name="v6"},
{name="v7"},
{name="v8"},
{name="v9"},
{name="v10"},
{name="E1"},
{name="G1"}]
```

and they have values:
```
1: (6113) <-1020-var-create - - "V" --thread 1 --frame 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (6116) ->1020^done,name=\"var3\",numchild=\"8\",value=\"size=8\",type=\"std::__1::vector<VertexStruct, std::__1::allocator<VertexStruct> >\",thread-id=\"1\",has_more=\"0\"\n"},"seq":600}

```

Can you open an issue on the [VS Code GitHub issues page ](https://github.com/microsoft/vscode/issues)?

**Comment by DridriLaBastos** [comment]
I opened this [issue](https://github.com/microsoft/vscode/issues/94311) on the [VS Code GitHub issues page](https://github.com/microsoft/vscode/issues)
