### ISSUE TITLE
"Go to Definition" unavailable in a function

### ISSUE THREAD

**Issue by vscpp** [microsoft/vscode-cpptools#524]
For a function:
void Foo (int Data)
{
  Data = 1;     -> Here, select "Data" and right click "Go to Definition", report: No Definition found "Data"
}

C/C++ extension: 0.10.2

**Comment by sean-mcmanus** [comment]
Known issue. Local variable symbols won't be available until we switch to the IntelliSense engine.

**Comment by vscpp** [comment]
Do your developers have a schedule to enable IntelliSense engine?

**Comment by sean-mcmanus** [comment]
Yes, we have a schedule. It's not publically disclosed though. The 1st IntelliSense engine feature is planned to be released "soon", assuming there are no unforeseen delays.
