### ISSUE TITLE
My c++ code intelliSense falure

### ISSUE THREAD

**Issue by PowerfulCat** [microsoft/vscode-cpptools#5240]
Issue Type: <b>Bug</b>

我的 C++ 智能提示又失灵了，只能重启 vscode，可能是我的 C++ 代码包含关系比较复杂，具体原因不是很清楚。
希望 vscode 能增加智能提示失灵检测功能，如果在编辑时如果智能提示在指定时间没有出现，就自动重置一下，并且收集可能的原因。

My C++ intelliSense is not working again, and only to restart vscode, which may be that my C++ code contains a more complex header file relationship, for reasons that are not clear.
It is hoped that vscode will add intelliSense failure detection, if the intelliSense does not appear at the specified time during editing, it is automatically reset and the possible cause is collected.

Extension version: 0.27.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.3.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 x 1191)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|14.59GB (9.43GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
@PowerfulCat 

Can you provide more info and clarify about what's not working with IntelliSense and also an English translation of 

> 我的 C++ 智能提示又失灵了，只能重启 vscode，可能是我的 C++ 代码包含关系比较复杂，具体原因不是很清楚。
希望 vscode 能增加智能提示失灵检测功能，如果在编辑时如果智能提示在指定时间没有出现，就自动重置一下，并且收集可能的原因。

Instructions to change the language display of VS Code is at https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language.

If there is an issue with IntelliSense features not working (such as error squiggles not appearing when they should be or it can't find a reference or definition of functions) please also provide the following logs to help us investigate the issue:

1. Logs from running the command `C/C++: Log Diagnostics`
2. Logs from the[ language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
