### ISSUE TITLE
Doesn't show documentation for typedef in a namespace

### ISSUE THREAD

**Issue by ShukantPal** [microsoft/vscode-cpptools#5241]
**Type: LanguageService**

```cpp
/**
 * Summary
 */
typedef uint64_t Move;

constexpr Move move;
```

Hovering over `Move` doesn't show the documentation like moving over a method or class does.

**Comment by sean-mcmanus** [comment]
It's working for me. Can you provide more repro details?

![image](https://user-images.githubusercontent.com/19859882/78283496-b8c39100-74d2-11ea-8387-cb66d4548554.png)

**Comment by ShukantPal** [comment]
@sean-mcmanus 

<img width="1680" alt="Screen Shot 2020-04-02 at 2 14 42 PM" src="https://user-images.githubusercontent.com/22450567/78283820-62fbe280-74ec-11ea-9c92-9fc96832bfe1.png">

Hi, I'm working on https://github.com/SurakartaArcade/libsurakarta. The screenshot is from `include/skmove.h`.

This is a non-exhaustive list of extensions on my system:
* CMake Tools
* C/C++
* ESLint
* Flow Support

If you are more specific, I can given you more repro details.

**Comment by sean-mcmanus** [comment]
Thanks for the info. I reproed it. The bug is triggered by the surrounding "namespace ". It appears to be an issue inherited from Visual Studio, so you can upvote https://developercommunity.visualstudio.com/content/problem/975899/c-intellisense-show-no-documentation-comment-for-t.html if you have a Microsoft account.

**Comment by sean-mcmanus** [comment]
VS fixed it in a component that isn't shared yet, i.e. we'd need to make a different fix.

**Comment by sean-mcmanus** [comment]
@db-src @ShukantPal Sorry about that and thanks for the "ping" -- it looks like this "fell through the cracks" -- it was trivial to apply the fix that VS made. It should be fixed in our next update.

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.0.

**Comment by michelleangela** [comment]
Fixed in release version https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2.
