### ISSUE TITLE
Cpp not found in compile_commands.json but in fact there is

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-cpptools#5242]
![image](https://user-images.githubusercontent.com/8154646/78256502-32876900-752b-11ea-8c4c-03cc737dd2ec.png)

Issue Type: <b>Bug</b>

{
  "directory": "/home/victor/ModelDev/dev.olympia/build",
  "command": "/usr/bin/g++  -DOlympia_EXPORTS -I/home/victor/ModelDev/dev.olympia/include/ModelLoader -I/home/victor/ModelDev/dev.olympia/include/ModelEnv -I/home/victor/ModelDev/dev.olympia/include/Logger -I/home/victor/ModelDev/dev.olympia/include/OrderGateway -I/home/victor/ModelDev/dev.olympia/include/Common -I/home/victor/ModelDev/dev.olympia/include/Subscriptioner -I/home/victor/ModelDev/dev.olympia/include/MarketDataClient -I/home/victor/ModelDev/dev.olympia/include/RefData -I/home/victor/ModelDev/dev.olympia/include/MessageAgent -I/home/victor/ModelDev/dev.olympia/include/Timer -I/home/victor/ModelDev/dev.olympia/include/spdlog -I/home/victor/ModelDev/dev.olympia/Model -I/home/victor/ModelDev/dev.olympia/Factor -I/home/victor/ModelDev/dev.olympia/Utility -I/home/victor/ModelDev/dev.olympia  -g -O3 -feliminate-unused-debug-types  -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -m64  -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -fno-semantic-interposition -ffat-lto-objects  -fno-trapping-math -Wl,-sort-common -Wl,--enable-new-dtags -mtune=skylake  -Wa,-mbranches-within-32B-boundaries -fvisibility-inlines-hidden -Wl,--enable-new-dtags -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wno-unused-parameter -Wpedantic -g -fPIC   -std=gnu++17 -o CMakeFiles/Olympia.dir/Model/Common.cpp.o -c /home/victor/ModelDev/dev.olympia/Model/Common.cpp",
  "file": "/home/victor/ModelDev/dev.olympia/Model/Common.cpp"
}

Extension version: 0.27.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.19.91-101.lts2018
Remote OS version: Linux x64 4.19.91-101.lts2018

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (17.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: CyberPort98|
|OS|Linux x64 4.19.91-101.lts2018|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (64 x 2699)|
|Memory (System)|502.64GB (27.70GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: CyberPort98|
|OS|Linux x64 4.19.91-101.lts2018|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (64 x 2699)|
|Memory (System)|502.64GB (27.59GB free)|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
@Victsz 

Can you provide the following logs to help see the resolved paths:

1. Logs from running the command `C/C++: Log Diagnostics`
2. Logs from the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Comment by sean-mcmanus** [comment]
I've reproed the bug. It appears to be caused by the "." in the folder path "dev.olympia".

**Comment by sean-mcmanus** [comment]
Oops, I was wrong -- my compileCommands path was wrong -- pointing to the wrong compile_commands.json file.

**Comment by Victsz** [comment]
C/C++: Log Diagnostics
-------- Diagnostics - 4/3/2020, 9:17:00 AM
Version: 0.27.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**",
        "/usr/include"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compileCommands": "${workspaceFolder}/build/compile_commands.json"
}
Translation Unit Mappings:
[ /home/victor/ModelDev/rolling/circular_buffer.hpp ]:
    /home/victor/ModelDev/rolling/circular_buffer.hpp
[ /home/victor/ModelDev/dev.olympia/Model/Common.cpp ]:
    /home/victor/ModelDev/dev.olympia/Model/Olympia.hpp
Translation Unit Configurations:
[ /home/victor/ModelDev/rolling/circular_buffer.hpp ]: not ready
    Process ID: 2495488
    Memory Usage: 20 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/9
        /usr/include/c++/9/x86_64-generic-linux
        /usr/include/c++/9/backward
        /usr/local/include
        /usr/lib64/clang/9.0.0/include
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=90000
        --header_only_fallback
[ /home/victor/ModelDev/dev.olympia/Model/Common.cpp ]:
    Process ID: 2495710
    Memory Usage: 282 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/9
        /usr/include/c++/9/x86_64-generic-linux
        /usr/include/c++/9/backward
        /usr/local/include
        /usr/lib64/clang/9.0.0/include
        /usr/include
        /home/victor/ModelDev/dev.olympia/Model
        /home/victor/ModelDev/ne.install/include/RefData
        /home/victor/ModelDev/dev.olympia/Utility
        /home/victor/ModelDev/ne.install/include/ModelEnv
        /home/victor/ModelDev/ne.install/include/Common
        /home/victor/ModelDev/ne.install/include/MarketDataClient
        /home/victor/ModelDev/ne.install/include/Logger
        /home/victor/ModelDev/ne.install/include/ModelLoader
        /home/victor/ModelDev/ne.install/include/spdlog
        /home/victor/ModelDev/ne.install/include/OrderGateway
        /home/victor/ModelDev/ne.install/include/Subscriptioner
        /home/victor/ModelDev/ne.install/include/MessageAgent
        /home/victor/ModelDev/ne.install/include/Timer
        /home/victor/ModelDev/dev.olympia/Model
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=90000
Total Memory Usage: 302 MB

**Comment by Colengms** [comment]
Hi @Victsz .  Can you confirm if you are still seeing this issue with the latest version (1.2.0) ?  We recently addressed https://github.com/microsoft/vscode-cpptools/issues/6311 , which had the same symptom.
