### ISSUE TITLE
Debugger can't find source file to debug on windows.

### ISSUE THREAD

**Issue by Icedude907** [microsoft/vscode-cpptools#5245]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.43.2
- C/C++ Extension Version: 27.0
- Other extensions you installed (and if the issue persists after disabling them): CMake Tools, Beautify, Git History, CMake, JS Code Snippets, Markdown All in One, Open in Application, TODO Highlight, vscode-icons, x86/64 assembly, Zoom Bar, Excel Viewer. Disabling CMake Tools did nothing.
- A clear and concise description of what the bug is.
When debugging an application running on an external drive (`A:\`) the debugger is unable to open the source file that it is trying to debug, citing that it can't read it. It is trying to search in `\a\...`, which the operating system translates to `C:\a\...` (I know this because this is where the file is made when it asks to create a file in that place.) Everything else functions as normal, except the current line highlighting and an error message popping up whenever the debugger halts at a point.

**To Reproduce**
1: Create a c++ project in any drive that isn't the `C` drive
2: Build the code with debugging symbols
3: Run the debugger
4: The debugger functions as normal, except the current line highlighting and an error message popping up whenever the debugger halts at a point.

![Here is the image](https://user-images.githubusercontent.com/34080011/78316420-1a135f00-75bc-11ea-9069-03488e3e1116.png)

Thanks for your time.

**Comment by WardenGnaw** [comment]
Can you enable logging and share the logs here?

You can do this by adding the following to your `launch.json`:
```
"logging": {
   "engineLogging": true
}
```

**Comment by Icedude907** [comment]
I'm not entirely sure what I should be giving you, but I captured this from the `Debug Console`
[test.log](https://github.com/microsoft/vscode-cpptools/files/4430776/test.log)
The error message in the bottom right that it spat out like in the photo above is the correct path, but it is for some reason considered with `C:` as the root, resulting in it searching at `C:\a\...` rather than `A:\...`
Edit: Line 332 may be of interest.
I'm using GCC 9.2.0 with MSys64 if that helps.

**Comment by Icedude907** [comment]
Double oh, searching this part of the log file yielded this #257.
The little hack suggested by Knagis seems to do the trick for now.
I don't know if you want to add what was suggested over there as default behaviour on windows, but I guess this can be marked closed.

**Comment by vbrzeski** [comment]
I have had the same problem FYI. It may be wise to change this behavior for an out-of-the-box experience that I have been enjoying out of VS Code so far :)
