### ISSUE TITLE
[Bug] Natvis processing fails for templates with unsigned long parameters

### ISSUE THREAD

**Issue by lostgoat** [microsoft/vscode-cpptools#5253]
Type: Debugger

**Describe the bug**
- OS and Version: Manjaro 4/4/2020
- VS Code Version: 1.43.2
- C/C++ Extension Version: 0.27
- Other extensions you installed (and if the issue persists after disabling them):

A basic templated object is defined:
```
template<typename T> class MyObject
{
public:
    MyObject() : myVal( 5 ) {}
    T myVal;
};
```

An associated natvis visualization is available:
```
<Type Name="MyObject&lt;*&gt;">
  <DisplayString>{{myVal = {myVal}}}</DisplayString>
  <Expand>
    <Item Name="[myVal]">myVal</Item>
  </Expand>
</Type>
```

Depending on the template parameters the natvis visualization may or may not work as expected:
```
    MyObject<signed long> myWorks33;  // Natvis visualization shows {myVal = 5}
    MyObject<unsigned long> myFail1;    // Natvis visualization fails - it shows {...}
```

A non-exaustive list of types that fail includes:
```
    MyObject<unsigned long> myFail1;
    MyObject<unsigned long int> myFail2;

    MyObject<long long> myFail10;
    MyObject<long long int> myFail11;
    MyObject<signed long long> myFail12;
    MyObject<signed long long int> myFail13;
    MyObject<unsigned long long> myFail14;
    MyObject<unsigned long long int> myFail15;

    MyObject<long double> myFail4;
```

I've upload a git project that includes the necessary vscode config, natvis and source files to reproduce the issue here:
https://github.com/lostgoat/natvisrepro

**To Reproduce**
1. git clone git@github.com:lostgoat/natvisrepro.git
2. "Open Folder" the git checkout
3. Set a breakpoint at the end of `main()`
4. Hit F5 to compile and debug
4. Inspect the values of the `myFail*`  variables

**Comment by lostgoat** [comment]
Engine log snippet:
```
1: (121677) <-1171-var-create - * "myFail1"
1: (121678) ->1171^done,name="var102",numchild="1",value="{...}",type="MyObject<unsigned long>",thread-id="1",has_more="0"
1: (121678) ->(gdb)
1: (121678) 1171: elapsed time 0
1: (121679) Natvis failed to parse typename: MyObject<unsigned long>
1: (121682) <-1172-var-list-children --simple-values "var102" 0 1000
1: (121682) ->1172^done,numchild="1",children=[child={name="var102.public",exp="public",numchild="1",value="",thread-id="1"}],has_more="0"
1: (121682) ->(gdb)
1: (121682) 1172: elapsed time 0
1: (121683) <-1173-var-list-children --simple-values "var102.public" 0 1000
1: (121683) ->1173^done,numchild="1",children=[child={name="var102.public.myVal",exp="myVal",numchild="0",value="5",type="unsigned long",thread-id="1"}],has_more="0"
1: (121683) ->(gdb)
1: (121683) 1173: elapsed time 0
1: (121685) Natvis failed to parse typename: MyObject<unsigned long>
1: (121685) Natvis failed to parse typename: unsigned long
```

**Comment by caseymcc** [comment]
This needs to be re-opened as I have hit the same issue working with Android NDK.

![image](https://user-images.githubusercontent.com/2903823/122789995-7de77d80-d27d-11eb-920c-0f2a1c907495.png)

Working with the above std::vectors on Android's NDK. If I define the natvis for std::__ndk1::vector_base as follows

```
<Type Name="std::__ndk1::__vector_base&lt;*&gt;">
        <DisplayString>{{size={__end_ - __begin_}}}</DisplayString>
        <Expand>
            <Item Name="[size]" ExcludeView="simple">__end_ - __begin_</Item>
            <Item Name="[capacity]" ExcludeView="simple">__end_cap_.__value_ - __begin_</Item>
            <ArrayItems>
                <Size>__end_ - __begin_</Size>
                <ValuePointer>__begin_</ValuePointer>
            </ArrayItems>
        </Expand>
    </Type>
```

I get the following

![image](https://user-images.githubusercontent.com/2903823/122790141-a2dbf080-d27d-11eb-810b-a66a71a217ed.png)

After finding this bug I tested with just a `std::vector<long>` and it works just `unsigned long` does not.
