### ISSUE TITLE
vscode c c intellisense identifier undefined but can resolve definition

### ISSUE THREAD

**Issue by RogFedex** [microsoft/vscode-cpptools#5255]
Issue Type: <b>Bug</b>

source code files are covered in red. However, f12 works on red and not sure why we have so many red underscored macros, function calls and variables 

Extension version: 0.27.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.16GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
The red is from IntelliSense parsing and it probably means your settings are not properly configured. F12 can work without IntelliSense parsing. If you run C/C++: Log Diagnostics you can see what include paths, defines, etc. are being used.
