### ISSUE TITLE
GDB not working on OSX Mojave

### ISSUE THREAD

**Issue by sagmua** [microsoft/vscode-cpptools#5256]
Type: Debugger

I am trying to use GDB in VScode for Mac OSX. I have installed a functional version of GDB (version 9.1. It works when I use it directly on the terminal) but I am not able to configure VScode to run debugger with GDB instead of LLDB.

Then when I start the debugger the following error appears:
```
Unable to start debugging. GDB exited unexpectedly with exit code 134 (0x86).
```

**Environement**
- OS and Version: Mac OSX Mojave 10.14.6
- VS Code Version: 1.43.2
- C/C++ Extension Version: 0.27.0
- GDB version: 9.1
**To Reproduce**
I have this configuration in my launch.json:

```
"configurations": [
        {
            "name": "(GDB) Launch Mac",
            "type": "cppdbg",
            "request": "launch",
            "program": "/Users/sam/Documents/my_examples/GDB/objs/ShapeType_publisher",
            "osx": {
                "stopAtEntry": false,
                "cwd": "${workspaceFolder}",
                "environment": [],
                "externalConsole": false,
                "MIMode": "gdb",

                "setupCommands": [
                    {
                    
                        "ignoreFailures": true
                    }
                
                ]
            },
        }
    ]
```

1. Go to 'debug' and 'run'.
then the following error appears:
However when I start debugger VScode returns the previously described error.

Any idea of what is happening? please let me know if I am doing something wrong.

**Additional context**
Please keep in mind that GDB is working fine when I run it in the terminal and also in another IDE I am using.

**Comment by WardenGnaw** [comment]
Can you add the following to your `launch.json`?

```
"logging": {
   "engineLogging": true
}
```

And share the output from the debug console?

**Comment by sagmua** [comment]
Sure, this is the output from the debut console:
```
1: (154) LaunchOptions<LocalLaunchOptions xmlns='http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014'
1: (168) LaunchOptions  ExePath='/Users/scardenete/Documents/my_examples/GDB/objs/x64Darwin17clang9.0/ShapeType_publisher'
1: (168) LaunchOptions  WorkingDirectory='/Users/scardenete/Documents/my_examples/GDB'
1: (168) LaunchOptions  ExeArguments=''
1: (169) LaunchOptions  MIMode='gdb'
1: (169) LaunchOptions  MIDebuggerPath=''
1: (169) LaunchOptions  WaitDynamicLibLoad='false'
1: (169) LaunchOptions>
1: (169) LaunchOptions    <SetupCommands>
1: (169) LaunchOptions        <Command IgnoreFailures='true' Description='Enable pretty-printing for gdb'>-enable-pretty-printing</Command>
1: (169) LaunchOptions    </SetupCommands>
1: (169) LaunchOptions</LocalLaunchOptions>
1: (330) codeSign-stderr: Executable=/usr/local/bin/gdb
1: (337) Starting: "/usr/local/bin/gdb" --interpreter=mi
1: (353) DebuggerPid=54780
1: (481) ->=thread-group-added,id="i1"
1: (482) ->~"GNU gdb (GDB) 9.1\n"
1: (482) ->~"Copyright (C) 2020 Free Software Foundation, Inc.\n"
1: (482) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
1: (482) ->~"\nType \"show copying\" and \"show warranty\" for details.\n"
1: (482) ->~"This GDB was configured as \"x86_64-apple-darwin18.7.0\".\n"
1: (482) ->~"Type \"show configuration\" for configuration details.\n"
1: (483) ->~"For bug reporting instructions, please see:\n"
1: (483) ->~"<http://www.gnu.org/software/gdb/bugs/>.\n"
1: (483) ->~"Find the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>."
1: (483) ->~"\n\n"
1: (483) ->~"For help, type \"help\".\n"
1: (483) ->~"Type \"apropos word\" to search for commands related to \"word\".\n"
1: (483) ->=cmd-param-changed,param="startup-with-shell",value="off"
1: (483) ->(gdb)
1: (487) <-1001-gdb-set target-async on
1: (488) ->1001^done
1: (488) ->(gdb)
1: (489) 1001: elapsed time 2
1: (496) <-1002-enable-pretty-printing
1: (497) ->1002^done
1: (497) ->(gdb)
1: (497) 1002: elapsed time 0
1: (497) <-1003-interpreter-exec console "set pagination off"
1: (497) ->=cmd-param-changed,param="pagination",value="off"
1: (497) ->1003^done
1: (497) ->(gdb)
1: (497) 1003: elapsed time 0
1: (497) <-1004-gdb-set auto-solib-add on
1: (498) ->1004^done
1: (498) ->(gdb)
1: (498) 1004: elapsed time 0
1: (498) <-1005-gdb-set solib-search-path /Users/scardenete/Documents/my_examples/GDB/objs/x64Darwin17clang9.0:
1: (499) ->1005^done
1: (499) ->(gdb)
1: (499) 1005: elapsed time 0
1: (499) <-1006-environment-cd /Users/scardenete/Documents/my_examples/GDB
1: (499) ->1006^done
1: (499) ->(gdb)
1: (499) 1006: elapsed time 0
1: (499) <-1007-file-exec-and-symbols /Users/scardenete/Documents/my_examples/GDB/objs/x64Darwin17clang9.0/ShapeType_publisher
1: (1340) ->~"/Users/scardenete/Downloads/gdb-9.1/gdb/inferior.c:283: internal-error: struct inferior *find_inferior_pid(int): Assertion `pid != 0' failed.\nA problem internal to GDB has been detected,\nfurther debugging may prove unreliable."
1: (1340) ->~"\nQuit this debugging session? "
1: (1341) ->~"(y or n) [answered Y; input not from terminal]\n"
1: (1341) ->&"\nThis is a bug, please report it."
1: (1341) ->&"  For instructions, see:\n"
1: (1341) ->&"<http://www.gnu.org/software/gdb/bugs/>.\n\n"
1: (1341) ->~"/Users/scardenete/Downloads/gdb-9.1/gdb/inferior.c:283: internal-error: struct inferior *find_inferior_pid(int): Assertion `pid != 0' failed.\nA problem internal to GDB has been detected,\nfurther debugging may prove unreliable."
1: (1341) ->~"\nCreate a core file of GDB? "
1: (1341) ->~"(y or n) [answered Y; input not from terminal]\n"
1: (13618) "/usr/local/bin/gdb" exited with code 134 (0x86).
1: (13621) <-logout
1: (13636) Send Event AD7MessageEvent
1: (13637) Send Event AD7ProgramDestroyEvent
The program '/Users/scardenete/Documents/my_examples/GDB/objs/x64Darwin17clang9.0/ShapeType_publisher' has exited with code 42 (0x0000002a).


```

**Comment by WardenGnaw** [comment]
From the logs, it seems like GDB can't debug the process.
```
gdb-9.1/gdb/inferior.c:283: internal-error: struct inferior *find_inferior_pid(int): Assertion `pid != 0' failed.
A problem internal to GDB has been detected, further debugging may prove unreliable.
```

There also seems to be a signing issue with the gdb used.
```
codeSign-stderr: Executable=/usr/local/bin/gdb
```

Is the GDB that you are using that works in the terminal, `"/usr/local/bin/gdb"`?

**Comment by paulmadejong** [comment]
> From the logs, it seems like GDB can't debug the process.
> 
> ```
> gdb-9.1/gdb/inferior.c:283: internal-error: struct inferior *find_inferior_pid(int): Assertion `pid != 0' failed.
> A problem internal to GDB has been detected, further debugging may prove unreliable.
> ```
> 
> There also seems to be a signing issue with the gdb used.
> 
> ```
> codeSign-stderr: Executable=/usr/local/bin/gdb
> ```
> 
> Is the GDB that you are using that works in the terminal, `"/usr/local/bin/gdb"`?

I have the exact same issue and similar entries in the log when using the logging. My GDB (both the one in `/usr/local/bin` and in Cellar (from home-brew, which the link in /usr/local/bin points to) are code signed according as I have followed the instructions on https://sourceware.org/gdb/wiki/PermissionsDarwin. For example, the `codesign -vv` returns:
`/usr/local/Cellar/gdb/9.1_1/bin/gdb: valid on disk
/usr/local/Cellar/gdb/9.1_1/bin/gdb: satisfies its Designated Requirement
`

Running gdb standalone seems to work OK and no issues regarding taskgated are reported.

**Comment by yanite** [comment]
1: (484) ->~"../../gdb/inferior.c:283: internal-error: struct inferior *find_inferior_pid(int): Assertion `pid != 0' failed.\nA problem internal to GDB has been detected,\nfurther debugging may prove unreliable."

same issue gdb 9.1

Running gdb standalone seems to work OK and no issues

**Comment by sagmua** [comment]
> From the logs, it seems like GDB can't debug the process.
> 
> ```
> gdb-9.1/gdb/inferior.c:283: internal-error: struct inferior *find_inferior_pid(int): Assertion `pid != 0' failed.
> A problem internal to GDB has been detected, further debugging may prove unreliable.
> ```
> 
> There also seems to be a signing issue with the gdb used.
> 
> ```
> codeSign-stderr: Executable=/usr/local/bin/gdb
> ```
> 
> Is the GDB that you are using that works in the terminal, `"/usr/local/bin/gdb"`?

Yes, it is the same:

```
$ which gdb
/usr/local/bin/gdb
```

Ad it is actually signed:
```
$codesign -dv --verbose=4 /usr/local/bin/gdb

Executable=/usr/local/bin/gdb
Identifier=org.gnu.gdb
Format=Mach-O thin (x86_64)
CodeDirectory v=20100 size=80124 flags=0x0(none) hashes=2497+5 location=embedded
VersionPlatform=1
VersionMin=658944
VersionSDK=658944
Hash type=sha256 size=32
CandidateCDHash sha256=5b767c5843e326f232b2cfa1bbb839259a4f8919
Hash choices=sha256
Page size=4096
CDHash=5b767c5843e326f232b2cfa1bbb839259a4f8919
Signature size=1619
Authority=gdb-cert
Signed Time=Feb 24, 2020 at 12:00:19 AM
Info.plist entries=4
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=88
```

**Comment by Kosteg** [comment]
I have exactly the same issue. GDB works from the terminal but not from the VSCode. The same internal-error in the output log.

**Comment by ObliqueShockTS** [comment]
Same issue with 9.2. Exact same internal error with exit code 134.

**Comment by domingguss** [comment]
me three on macOS 10.14.6 , same issue with gdb 9.2, but in Eclipse O_o

```
~"../../gdb/inferior.c:283: internal-error: struct inferior *find_inferior_pid(int): Asserti\
on `pid != 0' failed.\nA problem internal to GDB has been detected,\nfurther debugging may prove unr\
eliable."
```

**Comment by paulmadejong** [comment]
Still the same problem with gdb 9.2.1 and latest VSCode 1.47.3

**Comment by delta512** [comment]
Hello everyone, I’m on macOS High Sierra 10.13.6 and I’m having the very same issue.

Actually, it’s independent from whatever IDE you choose. It works well from the Terminal when you pass the “debugee” as an argument, while it crashes when provided within gdb’s command promt.

Find out more (and possibly provide a solution) on [gdb’s Bugzilla](https://sourceware.org/bugzilla/show_bug.cgi?id=25560)

**Comment by xuancong84** [comment]
Hi all, I am on Mac Mojave 10.14.6, having the same problem. I have code-signed GDB with entitlement and GDB can debug my C++ program in standalone terminal. But VSCode cannot debug my program using GDB, error message being "Unable to start debugging. GDB exited unexpectedly with exit code 134 (0x86)."

I think the bug lies in VSCode's GDB interpreter. Anyway, I am pretty sure that VSCode developers have never tested GDB support on Mac.

**Comment by delta512** [comment]
> Hi all, I am on Mac Mojave 10.14.6, having the same problem. I have code-signed GDB with entitlement and GDB can debug my C++ program in standalone terminal. But VSCode cannot debug my program using GDB, error message being "Unable to start debugging. GDB exited unexpectedly with exit code 134 (0x86)."

Hi xuancong84, you should get the same problem in a standalone terminal by first invoking GDB, then loading your program from within the GDB's shell: (gdb) file "your-program-to-debug"

> I think the bug lies in VSCode's GDB interpreter. Anyway, I am pretty sure that VSCode developers have never tested GDB support on Mac.

Actually this is an issue with GDB itself, under macOS only. Starting GDB and loading the "debugee" through interpreter commands (GDB's shell or GDB/MI interface) performs an additional task that makes the OS unhappy (and VS sees the debugger crash), while that does not happen when your program is passed directly as an argument (no issue with standalone terminal).

As the maintainers said, Apple ditched GDB some time ago and further development got more difficult. I'd recommend you to report this on [GDB's official Bugzilla thread](https://sourceware.org/bugzilla/show_bug.cgi?id=25560). Hopefully, the more awareness we raise, the sooner it will get fixed.

As a temporary workaround, try to set a custom debugger invocation. Make VS first load the symbol table and then load the executable.

**Comment by xuancong84** [comment]
Thanks @delta512 , you are right, I have tested. And I saw someone has already reported this bug to GDB's official Bugzilla thread. Hope it can get fixed soon -:)

**Comment by Vegz78** [comment]
Thanks to @Fil on the [gdb's Bugzilla #25560](https://sourceware.org/bugzilla/show_bug.cgi?id=25560#c1)!!!

Gdb is now working with graphical debug and breakpoints from Windows VS2019 on my Mac Mojave, thanks to his proposed edit of _/gdb/exec.c_ repackaged inside @domq's Homebrew tap:
https://github.com/domq/homebrew-gdb
https://gist.github.com/mike-myers-tob/9a6013124bad7ff074d3297db2c98247

**Comment by delta512** [comment]
Glad it helped!

**Comment by timhdesilva** [comment]
Just as a follow up, the workaround mentioned by @Vegz78 worked great for me on Mac OSX 11.4!

**Comment by eldarkg** [comment]
Try:
```json
            "symbolLoadInfo": {
                "loadAll": false,
                "exceptionList": ""
            },
```
