### ISSUE TITLE
Set IntelliSenseMode to specific ARM mode if compilerPath query result is ARM

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5258]
Set IntelliSenseMode to specific ARM mode if there are ARM specific defines from compiler query. This is in case the incorrect IntelliSenseMode was set and compilerPath indicates that the target architecture to simulate is ARM specific.

**Comment by sean-mcmanus** [comment]
We also don't correct x86 versus x64 mode from compiler querying results.

**Comment by sean-mcmanus** [comment]
Issue https://github.com/microsoft/vscode-cpptools/issues/5681 would possibly have been auto-solved by this intelliSenseMode detection.

**Comment by bobbrow** [comment]
@michelleangela is this complete?

**Comment by michelleangela** [comment]
Yes, this is complete. I'll close it.
