### ISSUE TITLE
Provide better logging during setup of querying compilerPath

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5259]
Purpose:
To better inform users of setting up IntelliSense and provide them with more information so that issues with IntelliSense setup involving the compilerPath can be better root caused.

Suggestion to show the following:
1. display compiler args that are used to query the compiler
2. display results of compiler query
3. if query failed, display detailed query of where it could have failed.
4. display if IntelliSenseMode changed at the end of setup and reason why it changed
5. display warning if the end result of compilerPath and IntelliSenseMode are different from user specified settings.

**Comment by Colengms** [comment]
I just ran into an issue where, after upgrading VS, the version numbers in my CL.exe compiler paths were no longer valid, and I was falling back to MinGW.  Looking forward to getting a warning when that happens.  :)

**Comment by sean-mcmanus** [comment]
@Colengms In your case with cl.exe, it's supposed to stick with cl.exe/msvc mode and not fall back to mingw (i.e. not just give a warning).
