### ISSUE TITLE
IntelliSense not work for compileCommands

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-cpptools#5265]
Issue Type: <b>Bug</b>

The project can successfully build.
with compileCommands setting there is not any hint for even "this->"
![image](https://user-images.githubusercontent.com/8154646/78788782-d6b35900-79de-11ea-9588-970684694f3a.png)
Log
```
-------- Diagnostics - 4/8/2020, 9:23:12 PM
Version: 0.27.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**",
        "/usr/include"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "/usr/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/victor/ModelDev/dev.olympia/extern.cpp ]:
    /home/victor/ModelDev/ne.install/include/Common/ObjectRepo.hpp
Translation Unit Configurations:
[ /home/victor/ModelDev/dev.olympia/extern.cpp ]:
    Process ID: 1284405
    Memory Usage: 273 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /home/victor/ModelDev/ne.install/include/ModelLoader
        /home/victor/ModelDev/ne.install/include/ModelEnv
        /home/victor/ModelDev/ne.install/include/Logger
        /home/victor/ModelDev/ne.install/include/OrderGateway
        /home/victor/ModelDev/ne.install/include/Common
        /home/victor/ModelDev/ne.install/include/Subscriptioner
        /home/victor/ModelDev/ne.install/include/MarketDataClient
        /home/victor/ModelDev/ne.install/include/RefData
        /home/victor/ModelDev/ne.install/include/MessageAgent
        /home/victor/ModelDev/ne.install/include/Timer
        /home/victor/ModelDev/ne.install/include/spdlog
        /home/victor/ModelDev/dev.olympia/Model
        /home/victor/ModelDev/dev.olympia/Factor
        /home/victor/ModelDev/dev.olympia/Utility
        /home/victor/ModelDev/dev.olympia
        /usr/include/c++/9
        /usr/include/c++/9/x86_64-generic-linux
        /usr/include/c++/9/backward
        /usr/local/include
        /usr/lib64/clang/9.0.0/include
        /usr/include
        /home/victor/ModelDev/ne.install/include/Common
    Defines:
        Olympia_EXPORTS
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=90000
```

And removed the compileCommands, it works.
![image](https://user-images.githubusercontent.com/8154646/78788929-09f5e800-79df-11ea-9988-6c19c916aee7.png)

Extension version: 0.27.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.19.91-101.lts2018

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (15.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: CyberPort98|
|OS|Linux x64 4.19.91-101.lts2018|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (64 x 874)|
|Memory (System)|502.64GB (5.21GB free)|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
This works in general (i.e. it doesn't repro for me). Can you compare the C/C++: Log Diagnostics output with the results when you don't have a compileCommands set? Are there any error squiggles when you're using compileCommands? Does hovering over "this" show any info?

If the "C/C++" logging (not the "Diagnostics" logging) do you see any "fail" messages that would indicate the IntelliSense process has crashed?
