### ISSUE TITLE
C/C++ & CMake Tools Extensions Conflict (in Linux)

### ISSUE THREAD

**Issue by gfxnvdo** [microsoft/vscode-cpptools#5266]
Issue Type: <b>Bug</b>

Installing CMake Tools Extensions causes C/C++ extension to fail.

0. A fresh install of .vscode, so no extensions or configuration already exists
1. Navigate to directory containing C++ project using CMake
2. Run VSCode from this directory ($ code &)
3. Open a C++ file -- a popup appears in the lower right asking to install the C/C++ extension
4. Click "Yes" to install the C/C++ extension
5. After install completes, note that Intellisense works by hovering the pointer over keywords in the C++ file.
6. Also note that #include lines have no squiggles. If they do, modify the c_cpp_properties.json file to add the include path to includePath (recommend using ** for recursive search)
7. Open the CMakeLists.txt file -- a popup appears in the lower right asking to install the CMake Tools extension
8. Click "Yes" to install the CMake Tools extension
9. After install completes, note that there are new buttons on the blue bar on the bottom of the window, including a Build button
10. At this point, the #include lines do not have squiggles, and the C/C++ Intellisense still works.
11. Either build the project or close and reopen VSCode from the same directory.
12. Note that the #include lines now have squiggles, and Intellisense includes \<error-code\> types instead of correct types in hover-popups.
13. Also note that disabling CMake Tools fixes the C/C++ extension behavior (after restart from the same directory).

Obviously, I can't tell which of the extensions is failing, since both need to be installed for the error to occur.  I could file this bug report under both, but I didn't want to be redundant. However, I hope that if the C/C++ extension is not to blame, rather than closing this, it can be moved to the CMake Tools extension, so this is fixed either way.

C/C++ Extension version: 0.27.0
CMake Tools Extension version: 1.3.1
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|15.58GB (9.64GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|50%|
</details>

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue. Both extensions are supposed to be compatible, but the C/C++ should be using CMake Tools info unless the configurationProvider setting is set -- do you have that set? Can you run C/C++ Log Diagnostics before and after CMake Tools is installed to see what the difference is?

**Comment by gfxnvdo** [comment]
I'm sorry, I'm just a new VSCode user, not an expert on how it is designed. This is a fresh installation, so I would guess whatever the default values are what are being used, with the exception noted above.

Yes, the configurationProvider in c_cpp_properties.json is set to "vector-of-bool.cmake-tools". I see this page (https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference) indicates this is related to the CMake Tools extension. I'm not clear whether that's a good thing or not, but this is still the case when the CMake Tools extension is disabled (and VSCode is restarted) while the C/C++ extension is still enabled.

The reference I found to enabling logging (https://code.visualstudio.com/docs/cpp/enable-logging-cpp) shows multiple different types of logging, but none use the word diagnostics. Can you specify which type of logging? And after enabling, where do I get the log file, or do I cut and paste from the Output tab?

What type of operation would you want to see before and after the CMake Tools extension is enabled? Loading VSCode? Opening a file? Editing a file?

Thanks for looking into this.

**Comment by sean-mcmanus** [comment]
The logging from running the C/C++: Log Diagnostics command with a C++ file active should be sufficient (from View->Command Palette).

**Comment by gfxnvdo** [comment]
I captured the C/C++: Log Diagnostics with only the C/C++ extension enabled (correct Intellisense), then enabled the CMake Tools extension (between the dashes) and captured the C/C++: Log Diagnostics again (incorrect Intellisense). (You will forgive me that I obfuscated the output a bit, but no lines were removed or added.)

[CppLogDiagnosticsBeforeAfter-sanitized.txt](https://github.com/microsoft/vscode-cpptools/files/4456407/CppLogDiagnosticsBeforeAfter-sanitized.txt)

**Comment by sean-mcmanus** [comment]
The 1st 2 logs show it using /usr/bin/gcc as the compilerPath and the 3rd one shows it using /opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/bin/x86_64-target-linux/x86_64-target-linux-g++ . Which one are you using to compile? Assuming it's the last one, then it sounds like CMake Tools is choosing the wrong compiler (/usr/bin/gcc). Are you using CMake Tools to compiler or some other method? You may not have the correct "kit" selected (there are "Scan for kits" and "Select a kit" commands you can try).

**Comment by gfxnvdo** [comment]
The actual compilation is being done with the target compiler.

But, the behavior of the C/C++ extension is correct while the 1st log is in effect, before the CMake Tools extension is installed/enabled. That is, while it thinks the /usr/bin/gcc compiler is being used.

The 2nd and 3rd logs are generated after enabling the CMake Tools extension. I did nothing between them. It is after this that the behavior of the C/C++ extension is incorrect. However, at this point, if I use the (newly displayed) Build button that appears in the blue bar on the bottom of the screen, the CMake Tools extension correctly builds the project.

**Comment by sean-mcmanus** [comment]
It looks like our querying of `/opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/bin/x86_64-target-linux/x86_64-target-linux-g++"` is giving incorrect results (i.e. only the 2 headers).

Can you set C_Cpp.loggingLevel to "Debug" and then check the "C/C++" output window after opening a CMake-built source file? You should see something like
"Custom configurations received:"
after which you should check to see if the values all look correct, in particular: defines, includePath, and compilerArgs. And can you see if there are error reported from
```
Attempting to get defaults from compiler found on the machine: '/opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/bin/x86_64-target-linux/x86_64-target-linux-g++
```
and/or run
```
/opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/bin/x86_64-target-linux/x86_64-target-linux-g++ <any args from your compilerArgs> -Wp,-v -E -dD -x c++ /dev/null
```
and see if the output gives a failure or contains any non-English characters.

**Comment by gfxnvdo** [comment]
Thank you, Sean.

Attached is the C/C++ log with Debug level enabled. There are no defines in the log, and the includePath itself does not appear either. However, the included paths listed and searched appear correct. The compilerArgs seem OK (although they appear to have a redundant -g).

Neither of the two "Attempting to get defaults from compiler found on the machine:" lines shows an explicit error; just "terminating child process" for each. I don't know if that's an error or not. These are followed by a "browse configuration" JSON. What is there seems accurate, but I don't know if more should be there and is missing.

I also ran the command line you specified...

The results started with 6 lines like this:
"ignoring nonexistent directory "/not/exist/usr/include/c++/7.3.0"
with different paths, but all starting with "/not/exist/usr", and a
"ignoring nonexistent directory "/opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/lib/x86_64-target-linux/gcc/x86_64-target-linux/7.3.0/../../../../../x86_64-target-linux/include" line. The directory does not exist. I don't know if these constitute errors.

Following that, the include search paths:
`#include "..." search starts here:`
`#include <...> search starts here:`
`/opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/lib/x86_64-target-linux/gcc/x86_64-target-linux/7.3.0/include`
`/opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/lib/x86_64-target-linux/gcc/x86_64-target-linux/7.3.0/include-fixed`
`End of search list.`

Then:
`# 1 "/dev/null"`
`# 1 "/home/gfxnvdo/Projects/TestApp//"`
`# 1 "<built-in>"`
...
Followed by all the predefined #defines, and the output completes with:
...
`#define __DECIMAL_BID_FORMAT__ 1`
`# 1 "<command-line>"`
`#define _GNU_SOURCE 1`
`# 1 "/dev/null"`

[CppLoggingWithCMakeFile-sanitized.txt](https://github.com/microsoft/vscode-cpptools/files/4466765/CppLoggingWithCMakeFile-sanitized.txt)

**Comment by sean-mcmanus** [comment]
Okay, so far all those logs look good (for the browse configuration data), and the 2 includePaths appear correct, but it appears you didn't open a CMake-built source file so I can't see what results we get from CMake Tools in regards to IntelliSense. Can you add that logging (you can exclude all the logging prior to the file open)?

Also, at which path are the includes not getting resolved for? From looking at the previous logging, my guess is that the CMake Tools may not be sending "/opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/include/", although I do see `<sysroot>/usr/include/Custom` in your browse path.

**Comment by gfxnvdo** [comment]
CMake Tools log is quite short, so I guess you meant the C/C++ extension log, which is attached. For reference, here is the CMake Tools log:
```
[variant] Loaded new set of variants
[kit] Successfully loaded 6 kits from /home/gfxnvdo/.local/share/CMakeTools/cmake-tools-kits.json
[main] Configuring folder: TestApp 
[cmake] Configuring done
[cmake] Generating done
```

Yes, you are correct. `/opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/include/**` is the one that contains the header files needed. And if I read the attached file correctly, you are right that this path is not there.

Note that the c_cpp_properties.json file, located in the .vscode subdirectory with the source file (~/Projects/TestApp/TestApp), and where I always launch VSCode, looks like this:

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/include/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64",
            "configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}
```

Also, a reminder that without the CMake extension, the C/C++ extension appears to work correctly. And the C/C++ log for this situation (C/C++ enabled, but CMake Tools disabled) does not include an includePath entry:

```
Custom browse configuration received: {
  "browsePath": [
    "/opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/lib/cmake/Custom/../../../../usr/include/Custom",
    "/home/rtillery/Projects/TestApp"
  ],
  "standard": "c++17",
  "compilerPath": "/opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/bin/x86_64-target-linux/x86_64-target-linux-g++",
  "compilerArgs": [
    "-g"
  ]
}
```

[LoadingCMakeBuiltCpp-sanitized.txt](https://github.com/microsoft/vscode-cpptools/files/4475630/LoadingCMakeBuiltCpp-sanitized.txt)

**Comment by sean-mcmanus** [comment]
CMake Tools is sending an includePath with "/opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/lib/cmake/Custom/../../../../usr/include/Custom" -- is that not the correct one? If you use the `".../usr/include/**"` setting and the run C/C++: Log Diagnostics with the source file active it should show what the list of includes that the `"**"` resolves to.

**Comment by gfxnvdo** [comment]
No,

`/opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/lib/cmake/Custom/../../../../usr/include/Custom`

is not the correct path. The correct path would be

`/opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/include/**`

I don't actually know where this path is coming from. As I mentioned [in a previous comment](https://github.com/microsoft/vscode-cpptools/issues/5266#issuecomment-613472462), the only configuration I did was modifying the c_cpp_properties.json file to add the correct path (above).

In the `/opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/lib/cmake/Custom` directory are four `*.cmake` files. One of these has these lines:

```
get_filename_component(CUSTOM_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(PREFIX "${CUSTOM_CMAKE_DIR}/../../../..")

set(CUSTOM_INCLUDE_DIRS
    ${PREFIX}/usr/include/Custom
)
set(CUSTOM_INCLUDES
    ${PREFIX}/usr/include/Custom
)
...
```

I assume this is where the path is originating. But I don't know why the one that was specified in the c_cpp_properties.json file would be replaced. And if that's by design (replace path with what the CMake Tools extension finds), then I don't know why only the `CUSTOM_INCLUDE*` path(s) are all that are collected, since the CMake-based build is fine. It is able to find all the includes in the provided directory. (Note that I know very little about CMake, and am coming into this existing project, so I don't know how the correct include path gets into the build, yet.)

BTW, I don't know what you mean by "use the `".../usr/include/**"` setting." I only know to provide the include path in the c_cpp_properties.json file (and I don't know why there is no place in the Settings UI to modify this, requiring modification of a config file), which I've already done. Once I enable both extensions, where do I set this path again?

**Comment by sean-mcmanus** [comment]
By "use the `../usr/include/**`" setting I mean stop using the configurationProvider. Then the logging should show what the `**` expands to. If you have a configurationProvider set, then the includePath in c_cpp_properties.json will be ignored. This is sounding like a CMake Tools issue, i.e. our extension is using the includes we get from CMake Tools.

@bobbrow @andreeis Are you aware of any CMake Tools config issues that could be occurring that could cause the includePath to be incorrect? Maybe something to do with the sysroot not getting not getting used?

**Comment by gfxnvdo** [comment]
This issue was seen on a brand new VSCode installation, where the only thing I customized was the includePath in the c_cpp_properties.json. I have not modified anything else, including the configurationProvider. (With the obvious exception of turning on debugging as you asked, after the initial report of the issue.) I provided the c_cpp_properties.json [in a previous post](https://github.com/microsoft/vscode-cpptools/issues/5266#issuecomment-613472462), and it does contain this line:
```
            "configurationProvider": "vector-of-bool.cmake-tools"`
```

**Comment by bobbrow** [comment]
I may be missing something, but from what I've read in this issue, it appears as if the C++ headers were not installed.  Can you verify that they exist somewhere on your hard disk?

**Comment by bobbrow** [comment]
Oops, apparently there's a keyboard shortcut to post your message that I didn't know about (and I don't know what I pressed).  That message was unfinished.  You should look for a `.../usr/include/c++/7.3.0` path somewhere and see if that matches what your compiler is searching.  In your [earlier comment](https://github.com/microsoft/vscode-cpptools/issues/5266#issuecomment-612654024) you said that it was reporting these paths as non-existent.

**Comment by gfxnvdo** [comment]
The header files are all there, so compilation of the project is fine. (The project can even be built from the VSCode build button that appears when the CMake Tools extension is enabled.)

To be clear, I only changed one thing when I installed VSCode & these two extensions:
-> the `includePath` in the `c_cpp_properties.json` file.

After installing the C/C++ extension, then modifying the `includePath` in `c_cpp_properties.json`, Intellisense worked.

Then, when installing and enabling the CMake Tools extension, with no further modifications on my part, the Intellisense fails.

I do not know where the "`/not/exist`" prefixes in the above comment originated, but the path I provided in the `includePath` entry in the `c_cpp_properties.json` file, and all the paths needed for the compilation itself, exist.

Disabling the CMake Tools extension restores C/C++ extension Intellisense behavior.

**Comment by sean-mcmanus** [comment]
@bobbrow I believe there is some path under /opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/include/ that CMake is using to build, but for which they don't send it to our includePath -- we only get the "Custom" folder under that path. The 2 compiler-provided includePaths appear to be correct. Bob, can you move this to the CMake Tools repo? I'm not familiar enough to CMake Tools to know if there's a way to get more diagnostics from there.

**Comment by bobbrow** [comment]
What is the full list of paths needed?  What I'm trying to say is that CMake Tools sends `compilerPath` to cpptools and cpptools is supposed to get the system include paths from that.  The "custom" folder is specified in the CMakeLists.txt because it is not a system include path.  That is why CMake Tools explicitly adds that to the `includePath`.  Are there other paths that are not system include paths that are missing?

**Comment by bobbrow** [comment]
Perhaps you can share one of the entries from `compile_commands.json` (in your build folder) that CMake Tools will generate.  It's possible that there's an argument being passed to the compiler when compiling files that also needs to be sent to cpptools.

**Comment by gfxnvdo** [comment]
Since this is a cross compile, I believe what you refer to as the "system include paths" are embedded in the cross-compiler. Dumping these from the compiler (`/opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/bin/x86_64-target-linux/x86_64-target-linux-g++ -E -x c++ - -v < /dev/null`) gives:
```
#include "..." search starts here:
#include <...> search starts here:
 /opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/lib/x86_64-target-linux/gcc/x86_64-target-linux/7.3.0/include
 /opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/lib/x86_64-target-linux/gcc/x86_64-target-linux/7.3.0/include-fixed
End of search list.
```
for the include paths.

The `compile_commands.json` files looks like this:
```
[
{
  "directory": "/home/gfxnvdo/Projects/TestApp/build",
  "command": "/opt/target/1.1.1/sysroots/x86_64-targetsdk-linux/usr/bin/x86_64-target-linux/x86_64-target-linux-g++   -m64 -march=corei7 -mtune=corei7 -mfpmath=sse -msse4.2 --sysroot=/opt/target/1.1.1/sysroots/corei7-64-target-linux   -I/opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/lib/cmake/Custom/../../../../usr/include/Custom  -g   -o CMakeFiles/TestApp.dir/TestApp.cpp.o -c /home/gfxnvdo/Projects/TestApp/TestApp.cpp",
  "file": "/home/gfxnvdo/Projects/TestApp/TestApp.cpp"
}
]
```

**Comment by sean-mcmanus** [comment]
It looks like CMake Tools is not handling the --sysroot flag. We also have a bug with compileCommands not handling that either: https://github.com/microsoft/vscode-cpptools/issues/1575 . Adding a compilerArgs property with value `"--sysroot=/opt/target/1.1.1/sysroots/corei7-64-target-linux"` may fix the issue. Another user had a similar issue at https://github.com/microsoft/vscode-cpptools/issues/5113 when using another cross-compiler.

**Comment by sean-mcmanus** [comment]
@bobbrow If you look at the logs at https://github.com/microsoft/vscode-cpptools/files/4475630/LoadingCMakeBuiltCpp-sanitized.txt you can see CMake Tools is not sending the --sysroot in the compilerArgs. Can you create a bug for that?

**Comment by sean-mcmanus** [comment]
@bobbrow CMake Tools is supposed to add the --sysroot at https://github.com/microsoft/vscode-cmake-tools/blob/develop/src/cpptools.ts#L307 , and when I used set(CMAKE_SYSROOT <path>) it successfully added the --sysroot (in the develop branch, maybe there's a change there that hasn't shipped yet).

**Comment by bobbrow** [comment]
That code is in the released version of the CMake Tools extension. I'm not sure why the compile_commands.json would be generated with the flag, but not the config provider.

**Comment by andalevor** [comment]
Hello. I have similar conflict between CMake Tools and C/C++ in Linux. Here is [log](https://justpaste.it/6royi) before allowing CMake Tools to configure IntelliSense. Here is [log](https://justpaste.it/4g4z9) after configuration. Or I'm doing something wrong?

**Comment by sean-mcmanus** [comment]
@andalevor What's the conflict/problem? CMake thinks you're using g++ instead of clang to compile. You can run the Select a Kit command to change it.
