### ISSUE TITLE
Do not create tasks.json when creating debug configuration for gcc build active file

### ISSUE THREAD

**Issue by NaLaDcP** [microsoft/vscode-cpptools#5270]
Type: Debugger

**Describe the bug**
- OS and Version:Ubuntu 18.04.4
- VS Code Version:  1.43.2
- C/C++ Extension Version: 0.27.0
- Other extensions you installed (and if the issue persists after disabling them): Python and LiveShare, issue persistts after disabling the extensions
- A clear and concise description of what the bug is.

*Please include a code sample and `launch.json` configuration.*
`
[launch.json.txt](https://github.com/microsoft/vscode-cpptools/files/4454797/launch.json.txt)

`
Steps to Reproduce:

1. Install C/C++ extension ms-vscode.cpptools
2. Start debugging
3. Select environment: C++(GDB/LLDB)
4. Select gcc run and debug active file

A launch.json file is created but no tasks.json. So it does not compile before starting the debugger. I tried to do it by hand by going to Menu -> Terminal -> Configure tasks -> Create tasks.json file from template I do not have such option for creating tasks.json for 'gcc build active file'

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by bobbrow** [comment]
@elahehrashedi did you fix this with your build tasks change?

**Comment by elahehrashedi** [comment]
This is fixed in the new build task changes. Will be available in C/C++ Extension Version: 1.1.0.

**Comment by sean-mcmanus** [comment]
With https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders this is fixed for tasks.json, but not launch.json -- seems like VS Code doesn't yet have a way to fix the launch.json case, other than us adding text to the end of the launch.json name/lable.
