### ISSUE TITLE
cpptools up to 99.5% of processor time on macos

### ISSUE THREAD

**Issue by shinze** [microsoft/vscode-cpptools#5273]
Hello, my macbook pro puts the fan since a few days, looking at activity monitor shows up to 99.5% of processing time, is that ok ?

![image](https://user-images.githubusercontent.com/218396/78906465-aa034e00-7a7f-11ea-8cda-61dfb4b1ef8a.png)

**Comment by michelleangela** [comment]
@shinze 

Does the cpptools process use 99.5% all the time or only during certain operations such as initial load of a workspace? Is there a particular operation or feature you're using when the cpptools takes a up that much processing time?

Generally, it is expected for the cpptools process to take up a lot of processing time when initially tag parsing a large workspace.

**Comment by shinze** [comment]
It's a large codebasew(qmk_firmware) but it seemed to occur after a long time after the project was opened.

**Comment by thehigherlife** [comment]
i'm seeing similar behavior too with smaller project sizes. usually once i'm starting to jump definitions.  once the CPU is high, it does not go down without a restart of vscode.

**Comment by bobbrow** [comment]
@shinze, is it this codebase? https://github.com/qmk/qmk_firmware/
@thehigherlife, do you have repro steps that we can follow to get the extension into this state? It's difficult for us to address these runaway CPU issues without a project that reproduces the problem.

**Comment by shinze** [comment]
@bobbrow Yes, and if I remember I was editing this particular file. https://github.com/qmk/qmk_firmware/blob/master/keyboards/kyria/keymaps/default/keymap.c

**Comment by thehigherlife** [comment]
@bobbrow the basic steps to reproduce it have been, working in vscode usually on a project that uses the arduino extension. Start right clicking "Go To Definition" through different libraries.  CPU starts pegging.

**Comment by bobbrow** [comment]
Thank you @shinze. I don't have a mac to try on right now, but I can see if I get similar results on linux.

@thehigherlife Go to definition can incur parsing costs when you open a file that hasn't been parsed before. And you're saying that the CPU pegging is permanent instead of temporary (i.e. it doesn't go away until you restart VS Code)?

**Comment by bobbrow** [comment]
@shinze , can you share your configuration for qmk_firmware?  While opening that file you mentioned it starts out with a squiggle on the `#include` because I don't have `QMK_KEYBOARD` defined.

**Comment by shinze** [comment]
@bobbrow I've just installed the build environment. https://docs.qmk.fm/#/newbs_getting_started

**Comment by thehigherlife** [comment]
@bobbrow  It seems to peg, a quit & restart of vscode does not cause the CPU to ramp again.

**Comment by sean-mcmanus** [comment]
@thehigherlife It sounds like the CPU usage is from the Go to Definition. If you set C_Cpp.loggingLevel to "Debug", you may be able to see more in regards to what processing is occurring that is causing the CPU usage. Attaching a debugger (or a profiler tool) and providing us with the call stacks might also help to diagnose what is causing the CPU usage.

**Comment by antst** [comment]
I have similar issue. With different workspaces at certain point, after been open for couple of days, I always end up with cpptools CPU consumption hitting high numbers non-stop on macOS.

**Comment by MarcianoPreciado** [comment]
I also get this behavior on macOS 10.15.6
