### ISSUE TITLE
Cpptool do not indicate syntax error while intelliSenseEngine is set to Default

### ISSUE THREAD

**Issue by yd-yin** [microsoft/vscode-cpptools#5277]
**Type: LanguageService**

Working on remote server by ssh, so cpptool extension is installed remotely.
VSCode version 1.44.0
Cpptool version 0.27.0
intelliSenseEngine is set to Default
The extension only offers some #include errors in blue line.
![image](https://user-images.githubusercontent.com/37136395/78977167-409c4180-7b4a-11ea-9eae-762b9e9cc318.png)
![image](https://user-images.githubusercontent.com/37136395/78977024-fdda6980-7b49-11ea-9b74-ce31c82da132.png)
There is an extra 'r' after 'vector' and an extra 'd' at the end. There should be red lines under these typos.

All the installed extensions are listed below
![image](https://user-images.githubusercontent.com/37136395/78977514-d2a44a00-7b4a-11ea-9520-16e70007d345.png)

<!--

**Comment by sean-mcmanus** [comment]
Your intelliSenseEngineFallback setting is set to "Enabled". If you change it to the default of "Disabled" then you should get squiggles. However, it's unable to locate some system headers.

**Comment by yd-yin** [comment]
Thanks for the response. I set intelliSenseEngineFallback to Disabled. Indeed the extension then gives some red squiggles at the "#include" region showing "Cannot open source file ...", however, typos or syntax errors are still missed.
Actually I think it might be related to the ssh server. It works well locally. I tried to create a new user in the remote server and configure VSCode ssh connections from scratch, but in vain.
@5298 seems have the simillar issue, except that in my case it doesn't work all the time.

**Comment by sean-mcmanus** [comment]
I think you're not getting error squiggles because we intentionally don't show error squiggles on the single file scenario (without a workspace folder being open). See https://github.com/microsoft/vscode-cpptools/issues/5617 .

**Comment by yd-yin** [comment]
Thanks for your reply. Unfortunately, it's not my case. I have a project folder and I open the folder in vscode. 

Actually, the extension works correctly on another server (say serverB), but not on serverA. I tried to reinstall the extension, but nothing changed.

**Comment by yd-yin** [comment]
Ok I found the solution.

I set `C_cpp: Error Squiggles` in all `User`, `Remote` and  `Workspace` tags to `Enabled`. And it works

Thanks a lot
