### ISSUE TITLE
MacOS: Memory Storage Leak  (2,7 Gb) - Why ????

### ISSUE THREAD

**Issue by sea5kg** [microsoft/vscode-cpptools#5278]
Type: Debugger

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment]
Can you provide more info? Which process is using memory?

**Comment by sea5kg** [comment]
Ok. I try later more info add to this issue. I just removed vscode-cpptools (not enough space)

**Comment by sean-mcmanus** [comment]
By "space" do you mean hard drive space or memory?

**Comment by sea5kg** [comment]
> By "space" do you mean hard drive space or memory?

In first hard drive

**Comment by sean-mcmanus** [comment]
It sounds like the IntelliSense cache. You could set the C_Cpp.intelliSenseCacheSize to 0 to disable that (the default size is 5 GB). Let us know if that doesn't fix it.

**Comment by sea5kg** [comment]
> It sounds like the IntelliSense cache. You could set the C_Cpp.intelliSenseCacheSize to 0 to disable that. Let us know if that doesn't fix it.

Ok. thank you.
