### ISSUE TITLE
"hello-world" would like to access files in your Documents folder

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode-cpptools#5282]
- OS and Version: macOS 10.15.4
- VS Code Version: 1.44.0
- C/C++ Extension Version: 0.27.0

Hello, every time I start debugging, I get prompt like this:

"hello-world" would like to access files in your Documents folder

How to disable the prompt?

Thanks,

**Comment by WardenGnaw** [comment]
The `"hello-world" would like to access files in your Documents folder` comes from the macOS operating system. The terminal program you are using does not permissions to access your file system. You can fix this by giving your terminal access in `Security & Privacy` -> `Privacy` -> `Files and Folders` and click on the checkbox for `Terminal`.

![image](https://user-images.githubusercontent.com/3953714/79157950-55671800-7d8a-11ea-8c59-f31ba6e52809.png)

**Comment by kzhui125** [comment]
I see hello-world appear at the Files and Folders list,  and I uncheck the hello-world, now it works.

<img width="469" alt="3" src="https://user-images.githubusercontent.com/11925432/79177947-8735b880-7e36-11ea-9245-36a26ef1af7a.png">

I have tried to use g++-9(Homebrew GCC 9.3.0) / gdb(GNU gdb (GDB) 9.1) to build and debug. I have signed the gdb following this article: https://sourceware.org/gdb/wiki/PermissionsDarwin

```
codesign -vv /usr/local/bin/gdb
/usr/local/bin/gdb: valid on disk
/usr/local/bin/gdb: satisfies its Designated Requirement
```

But I still can't debug using VSCode with g++-9/gdb. It seems when using g++-9 to build, it will generate an application for hello-world.

Now I switch to use clang/lldb to build and debug. Hope VSCode will support documents for how to debug using gdb on macOS.

Thanks,

**Comment by dgazzoni** [comment]
> The `"hello-world" would like to access files in your Documents folder` comes from the macOS operating system. The terminal program you are using does not permissions to access your file system. You can fix this by giving your terminal access in `Security & Privacy` -> `Privacy` -> `Files and Folders` and click on the checkbox for `Terminal`.
> 
> ![image](https://user-images.githubusercontent.com/3953714/79157950-55671800-7d8a-11ea-8c59-f31ba6e52809.png)

This solution doesn't work for me. Access to Terminal is granted, but the permission popups haven't gone away.
