### ISSUE TITLE
FAILURE: Debugger cannot `Step Over` / `Step Into` `std::unordered_map`

### ISSUE THREAD

**Issue by alanjohnjames** [microsoft/vscode-cpptools#5283]
Type: Debugger

Compile this code using **CMake Tools** then run the following code in the **Debugger (F5)**

The debugger cannot **Step Over** or **Step Into** the line with `std::unordered_map` commented `FAILURE` in the code. 

```cpp
#include <unordered_map>
#include <string>
#include <iostream>

auto response(std::string input) -> std::string {
    auto reply = std::unordered_map<std::string, std::string> {  // FAILURE: Debugger cannot `Step Over` / Step Into line with `std::unordered_map`.
        { "hello", "world" },
        { "goodbye", "cruel world" },
    };
    return reply[input];
};

int main(int, char**) {
    const std::string& input = "hello";
    std::cout << input << ", " << response(input) << std::endl;
    return 0;
}
```

**Describe the bug**
- OS and Version:
**macOS Mojave Version 10.14.6**
- VS Code Version:
**Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0**
- C/C++ Extension Version:
**Latest..?** 
- Other extensions you installed (and if the issue persists after disabling them):
**CMake Tools**
- A clear and concise description of what the bug is.
**See above...**

**To Reproduce**
**See above...**

*Please include a code sample and `launch.json` configuration.*
```jsonc
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            // SEE: https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html#debugging-with-cmake-tools-and-launch-json
            "program": "${command:cmake.launchTargetPath}",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "logging": {
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            }
        }
    ]
}
```

Steps to reproduce the behaviour:
**See above**

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Attached output from the C/C++ Extension log file.**
[c_cpp_extension.log](https://github.com/microsoft/vscode-cpptools/files/4465436/c_cpp_extension.log)

**Comment by WardenGnaw** [comment]
Can you add the following to your `launch.json` configuration:
```
"logging": { 
   "engineLogging": true
 }
```
and share the output from the debug console?

**Comment by alanjohnjames** [comment]
I have run the code again with the `"engineLogging": true` in the `launch.json`. 
The output from the Debug Console is attached. 

[debug_console.log](https://github.com/microsoft/vscode-cpptools/files/4490041/debug_console.log)

Let me know if you need anything more info. 
I hope this helps.

**Comment by akalinin-ms** [comment]
I have this problem
