### ISSUE TITLE
Default 'preLaunchTask' in launch.json is not the same as 'label' in tasks.json

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#5285]
Type: Debugger

**Environment**
- OS and Version: Windows 10
- VS Code Version: 1.44.0
- C/C++ Extension Version:  0.27.0: March 30, 2020

**Bug Describe**

Default 'preLaunchTask' in launch.json is not the same as 'label' in tasks.json
- "preLaunchTask": "g++.exe build active file"
- "label": "C/C++: g++.exe build active file"

Users have to change one of them by themselves. It will be good if them are default the same, like both with "C/C++:" start.

**Comment by jmarmstrong1207** [comment]
I have this issue too with WSL Ubuntu & VSCode. I was just about to make a bug report about this until I found this one

**Comment by bobbrow** [comment]
@elahehrashedi did you fix this with your build tasks change?

**Comment by sean-mcmanus** [comment]
I'm not reproing this with 1.0.1 (prelaunch tasks has "C/C++: ...".

**Comment by elahehrashedi** [comment]
This is fixed in the new build task changes. Will be available in C/C++ Extension Version: 1.1.0

**Comment by ghost** [comment]
Thanks for your work!

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders .
