### ISSUE TITLE
Is it possible to expend type information popup?

### ISSUE THREAD

**Issue by cgringmuth** [microsoft/vscode-cpptools#5291]
It is not really a bug actually. However I couldn't find a forum or something similar to ask.
So, as the title said, is it possible to expand the information in the popup to show the full type information?

![image](https://user-images.githubusercontent.com/1169481/79129380-6b360680-7da5-11ea-977a-5ed7686e644b.png)

As you can see the popup information shortens the type information with dots. This is just a trivial case. However imagine `foo` is of "type" auto and stores the return value from a function. I could just hover over the function. But here is the same issue. Also if I want to check the type information of variable a couple lines below without going up. Hopefully you understand my point.

Following picture probably conveys the issue better:
![image](https://user-images.githubusercontent.com/1169481/79130770-cff26080-7da7-11ea-8042-5da269dad51a.png)

**Comment by sean-mcmanus** [comment]
Not sure yet...

**Comment by bobbrow** [comment]
I think this should be relatively easy to do.  We could potentially add a setting to control which set of flags we pass to the label formatting.

**Comment by sean-mcmanus** [comment]
@bobbrow But I don't know what is causing the "..." to appear -- you found the code that does that?

**Comment by sean-mcmanus** [comment]
Found it -- we're using a hardcoded value of 100 while VS uses 250. I'll just bump the value to match VS.

**Comment by bobbrow** [comment]
Sure. VS Code doesn't give us any control over the tooltip width though, so it may be difficult to read without a type alias.

**Comment by sean-mcmanus** [comment]
It looks fine to me:
![image](https://user-images.githubusercontent.com/19859882/80556842-c95c0f80-8989-11ea-9dc2-70391745e6bf.png)

**Comment by cgringmuth** [comment]
Thx, I tried to fix it myself. However I wasn't successful. I couldn't find where to change to it. Did you attach a commit to this issue? Or how can I see the change you made to fix this issue?

**Comment by sean-mcmanus** [comment]
@choffmann The change was in our closed source cpptools process. You need 0.28.0-insiders and not 0.27.1 -- we had an issue that prevented 0.28.0-insiders from autoupdating last night, but it should be fixed now (with updateChannel set to "Insiders").

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders2 ...unless the string is > 250 characters (previous limit was 100).
