### ISSUE TITLE
Mixed C#/Swig/C++ debugging

### ISSUE THREAD

**Issue by m17kea** [microsoft/vscode-cpptools#5292]
Type: Debugger

- OS and Version: OSX Remote SSH Connection to Amazon Linux 2 (RHEL7 equivalent)
- VS Code Version: 1.44.0
- C/C++ Extension Version: 0.27.0
- Swig 4.0.1
- GCC Version: 9.2
- GDB Version: 8.3
- Other extensions you installed (and if the issue persists after disabling them): C#, CMake, CMake Tools, Test Explorer UI, .Net Core Test Explorer

I am trying to implement mixed-mode debugging in vscode. 

**To Reproduce**
I am running a test with the following command: 
`VSTEST_HOST_DEBUG=1 &&
dotnet vstest testdll.dll --Tests:classname.testname --Parallel --logger:trx;LogFileName=output.trx`

This spins up three dotnet processes of which i attach to the third with: 
```
{
    name: '.NET Core Attach',
    type: 'coreclr',
    request: 'attach',
    processId: "${command:pickProcess}", 
    env: {
             "LD_LIBRARY_PATH": "/media/psf/Home/Documents/dev.nosync/Derivitec/symbols-2.2.8;/home/linuxbrew/.linuxbrew/lib/gcc/9/;/media/psf/Home/Documents/dev.nosync/Derivitec/src/build/Debug/Derivitec/;/media/psf/Home/Documents/dev.nosync/Derivitec/src/build/Debug/Derivitec.Wrap/;$LD_LIBRARY_PATH",
            "LD_DEBUG":"all",
            "LD_DEBUG_OUTPUT":"/tmp/testrunner.log"
    }
}
```
I successfully reach a break point in C# before the C++ I'm interested in. 

I attach again with: 

```
{
     "name": "(gdb) Attach",
    "type": "cppdbg",
    "request": "attach",
    "program": "/usr/share/dotnet/dotnet",
    "processId": "${command:pickProcess}",
    "additionalSOLibSearchPath": "${workspaceFolder}/symbols-2.2.8;/home/linuxbrew/.linuxbrew/lib/gcc/9/;${workspaceFolder}/src/build/Debug/Derivitec/;${workspaceFolder}/src/build/Debug/Derivitec.Wrap/",
    "MIMode": "gdb",
    "miDebuggerPath": "/home/linuxbrew/.linuxbrew/bin/gdb",
    "setupCommands": [
         {
             "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": true,
         }
    ],
    "logging": { 
         "trace": true, 
         "traceResponse": true,
         "engineLogging": true   
    }
}
```

The gdb debugger attaches successfully and my cpp breakpoints become active in the Breakpoints window. I then press play on the C# debugger. In the call stack the gdb debugger the pauses on an exception as follows: 

![Screenshot 2020-04-13 at 17 29 22](https://user-images.githubusercontent.com/25348489/79138390-59a42d00-7dac-11ea-98ef-e79b929fcc43.png)

After continuing the debugger a couple of times it crashes the dotnet process running the test. 

I tried adding the libcoreclr source using `dotnet-symbol --recurse-subdirectories /usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.8/libcoreclr.so -o symbols-2.2.8` and referencing it in both additionalSOLibSearchPath properties but it does not seem to load it.

GDB logs attached:

[gdb.log](https://github.com/microsoft/vscode-cpptools/files/4470499/gdb.log)

@pieandcakes you seem to have commented on many of these types of issue, perhaps you could point me in the right direction.

Many thanks in advance!

**Comment by pieandcakes** [comment]
cc @WardenGnaw 

It looks like the `dotnet` process is crashing (Seg Fault) per the log you provided:
>->*stopped,reason=\"exited-signalled\",signal-name=\"SIGSEGV\",signal-meaning=\"Segmentation fault\"\n"},"seq":1496}

I don't see anything in there that shows the extension doing something so this seems like a bug in `dotnet`. You will need to file a bug on their [repo](https://github.com/dotnet/core/issues) .

**Comment by m17kea** [comment]
Thanks @pieandcakes for the rapid response. 

This error appears only after hitting the debugger continue a few times, could this still be a cause rather than a symptom of an earlier problem? 

I'll raise it on their repo now.

**Comment by pieandcakes** [comment]
@armitagemderivitec The `gdb` log shows that the dotnet process SegFaulted which tells me that theres an unrecoverable error and its crashing.  I imagine there might be something in their code that says if its being debugged to go down a different code path and that might have a bug in it but I'm just speculating. Thanks for filing it in their repo. I'll close this for now but feel free to comment here if/when they fix it if there are other problems.

**Comment by m17kea** [comment]
@pieandcakes I managed to cure this crash by adding the following to the setup commands in the attach config for the debugger: 
```
{
    "ignoreFailures": true,
    "text": "handle SIGTRAP pass noprint nostop"
}
```

I noticed the SIGTRAP signals from dotnet and wondered if this was relevant, which it turns out it was. My knowledge of the debugger is limited however, do you know whether there is any harm in doing this? Or does it shed any more light?
