### ISSUE TITLE
Support natvis visualisers from extensions

### ISSUE THREAD

**Issue by KindDragon** [microsoft/vscode-cpptools#5293]
Type: Debugger

I want to port my Visual Studio extension to VS Code https://marketplace.visualstudio.com/items?itemName=ArkadyShapkin.CDebuggerVisualizersforVS2017, but I can't find any information on how to implement it.

Also, it probably depends on issue #925

**Comment by WardenGnaw** [comment]
VS Code does not have the same extensibility to add natvis as VS. The best would be to write an extension that depends on `vscode-cpptools` and inject all the natvis files/paths in `visualizerFile` once https://github.com/microsoft/vscode-cpptools/issues/925 is supported.

**Comment by KindDragon** [comment]
That would be great.

**Comment by Ashark** [comment]
I think this may be closed now.

**Comment by KindDragon** [comment]
> VS Code does not have the same extensibility to add natvis as VS. The best would be to write an extension that depends on vscode-cpptools and inject all the natvis files/paths in visualizerFile once https://github.com/microsoft/vscode-cpptools/issues/925 is supported.

Is there any example available how to do extension with such injection?
