### ISSUE TITLE
"ld: cannot open output file" error on Ubuntu 18.04

### ISSUE THREAD

**Issue by benoittachet** [microsoft/vscode-cpptools#5295]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 18.04.4 LTS
- VS Code Version: 1.43.2
- C/C++ Extension Version: 0.27.0
- Other extensions you installed (and if the issue persists after disabling them): CMakeExtensions - Issue persists after disabling
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

test.cpp
`#include <iostream>
#include <string>

int main()
{
    std::cout << "Hello, World !" << std::endl;
    std::cout << "How are you ?" << std::endl;
    return (0);
}`

launch.json
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - Générer et déboguer le fichier actif",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Activer l'impression en mode Pretty pour gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}`

tasks.json
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "g++ build active file",
            "type": "shell",
            "command": "/usr/bin/g++",
            "args": [
                // Ask msbuild to generate full paths for file names.
                "-g", "${file}", "-o", "${fileDirName}/${fileBasenameNoExtension}"
            ],
            "options": {"cwd": "/usr/bin"},
            "problemMatcher": ["$gcc"],
            "group": "build",
            "presentation": {
                // Reveal the output only if unrecognized errors occur.
                "reveal": "silent"
            }
        }
    ]
}`

1. Open the workspace with all these files
2. run the .cpp file

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*

No log or error messages in the specified windows

**Comment by WardenGnaw** [comment]
Can you add the following to your `launch.json`:

```
"logging": {
   "engineLogging": true
}

and share the output from the debug console?
```
