### ISSUE TITLE
Unable to start the C/C++ language server.

### ISSUE THREAD

**Issue by mbristol78** [microsoft/vscode-cpptools#5296]
I have the extension failing with the message

Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Launching server using command /home/mick/.vscode/extensions/ms-vscode.cpptools-0.27.0/bin/cpptools failed.

Any idea? 

Thanks

I am running linux, ubuntu 64
And vscode
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T11:22:13.689Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-46-generic snap

**Comment by sean-mcmanus** [comment]
The cpptools binary may be missing. Can you uninstall/install the C/C++ extension? Deleting the /home/mick/.vscode/extensions/ms-vscode.cpptools-0.27.0/install.lock file may also fix the issue via re-downloading the binary.

**Comment by mbristol78** [comment]
Hi, thanks for your help. Strangely today, there is no trouble. I had the issue more than once in the past so I may reinstall it the way you described. I will reopen this thread if needed. Thanks again.
