### ISSUE TITLE
unrecognized command line option '--interpreter=mi' or debugger no starting at all when debugging in VSCode

### ISSUE THREAD

**Issue by VcelistMC** [microsoft/vscode-cpptools#5297]
Type: Debugger
Whenever i try to debug code with c++, it shows me the following message. I tried replacing "C++.exe" in launch.json with "g++.exe" and still doesn't work. I don't know if this is worth mentioning or not but gdb.exe doesn't exist at all in MinGW and is nowhere to be found

> Unable to start debugging. Unable to establish connection with GDB, the following message was written to stderr
> Starting: "C:\MinGW\bin\c++.exe" --interpreter=mi
> c++.exe: error: unrecognized command line option '--interpreter=mi'
> c++.exe: fatal error: no input files
> compilation terminated.
> "C:\MinGW\bin\c++.exe" exited with code 1 (0x1).

However, I found that if I set "externalConsole" to false, the following message appears in the terminal and nothing happens after that, debugger doesn't start and no errors appear

> PS D:\MyProjects>  & 'c:\Users\Name\\.vscode\extensions\ms-vscode.cpptools-0.27.0\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-klueyhbi.zb4' '--stdout=Microsoft-MIEngine-Out-cmzxtyyt.fl1' '--stderr=Microsoft-MIEngine-Error-pezdogmc.kod' '--pid=Microsoft-MIEngine-Pid-mjkqj2co.h04' '--dbgExe=C:\MinGW\bin\g++.exe' '--interpreter=mi'

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.44
- C/C++ Extension Version: 0.27.0
- Other extensions you installed (and if the issue persists after disabling them): Code Runner
- When trying to debug C++ code using VSCode, the above message appears

**To Reproduce**
**Sample Code:**
```
#include <iostream>
using namespace std;
int main(){
    string j;
    string name;
    cin >> name;
    cout<<"Hello "<<name;
    cin>>j;
    return 0;
}
```
**launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        
        {
            "name": "C++ Launch (GDB)",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "x86",
            "program": "${workspaceRoot}\\C++\\${fileBasenameNoExtension}.exe",
            "miDebuggerPath": "C:\\MinGW\\bin\\c++.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "externalConsole": true,
            "preLaunchTask": "MyBuild"
        }
    ]
}
```
1. Go to debugging tab
2. Start debugging

**Comment by WardenGnaw** [comment]
`miDebuggerPath` is the path to your debugger. For MinGW, this is usually `gdb.exe`.

**Comment by VcelistMC** [comment]
It's fixed now, it was a mistake on my part, sorry. Apparently I missed a checkbox while installing MinGW.

gdb.exe now exists in my MinGW folder and the debugger is working. Thank you for your time
