### ISSUE TITLE
Error when debugging

### ISSUE THREAD

**Issue by SolarTorch** [microsoft/vscode-cpptools#53]
ERROR: Unable to start debugging. Cannot access a disposed object.

i have already added the .o file in lunch.json

**Comment by delmyers** [comment]
@Githelang, We haven't seen this error. Can you let us know what OS/distro you are using? Version of VsCode? Do you have a small repro?

**Comment by songwenshuai** [comment]
error:The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

china，vision 1.4 windows 7

**Comment by pieandcakes** [comment]
@githelang please reopen this issue and provide additional information if this is still happening on extension version `0.9.2` or later. 

@songwenshuai That issue should also be resolved as of `0.9.0`. please try the latest version of the extension and if it is still happening, please file a different issue.
