### ISSUE TITLE
The "Microsoft C/C++ extension for VS Code" doesn't work with MSVC unless VS Code is opened through the "Developer Command Prompt for Visual Studio"

### ISSUE THREAD

**Issue by krasimirkrustev** [microsoft/vscode-cpptools#5301]
The "Microsoft C/C++ extension for VS Code" doesn't work with MSVC unless VS Code is opened through the "Developer Command Prompt for Visual Studio".

- OS and Version: Windows 10 1909
- VS Code Version:  1.44.1
- C/C++ Extension Version: 0.27.0

The error message in the terminal tab is "cl.exe : The term 'cl.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

**Comment by sean-mcmanus** [comment]
This sounds like a duplicate of https://github.com/microsoft/vscode-cpptools/issues/5271 ?

**Comment by sean-mcmanus** [comment]
@krasimirkrustev This was added in https://github.com/microsoft/vscode-cpptools/releases/tag/v1.29.2
