### ISSUE TITLE
IntelliSense gives error using #pragma pack 

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5302]
this doesn't seem to work with #pragma pack too

```
#pragma pack(push, 1)
struct foo
{
	int x;
	char y;
};
#pragma pack(pop)

static_assert(sizeof(foo) == 5) // fail
```

_Originally posted by @bugproof in https://github.com/microsoft/vscode-cpptools/issues/5267#issuecomment-613925706_

**Comment by sean-mcmanus** [comment]
@bugproof I'm not able to repro the bug. Can you provide more info your settings, i.e. from C/C++: Log Diagnostics (intelliSenseMode, compilerPath, OS, etc.).

**Comment by bugproof** [comment]
@sean-mcmanus the code compiles fine but in the editor it says "static_assert failed" so quite misleading

![image](https://user-images.githubusercontent.com/3116731/79386950-34115200-7f6b-11ea-9b8f-8d5348cd8403.png)

btw im using vs2019, sorry this is probably not issue for this repo but for https://developercommunity.visualstudio.com/

**Comment by sean-mcmanus** [comment]
@bugproof What version? I don't repro the bug with the version of VS 2019 (16.6 Preview 3). Looks like 16.6 Preview 2 is publicly available https://devblogs.microsoft.com/visualstudio/visual-studio-2019-version-16-6-preview-2/ . It's possible some configuration/setting could be required for the repro. VS 2019 bugs are usually reported via Help->Send Feedback->"Report a Problem..." or https://developercommunity.visualstudio.com/content/problem/post.html?space=62 .

**Comment by bugproof** [comment]
@sean-mcmanus  Version 16.5.4 I don't use previews. Maybe it's fixed then

**Comment by michelleangela** [comment]
@bugproof, we verified that Visual Studio version 16.5.4 does not repro this issue. 

Do you have certain c_cpp_properties.json settings or project settings customized?

**Comment by bugproof** [comment]
@michelleangela
> Do you have certain c_cpp_properties.json settings or project settings customized?

nothing like that

surprisingly it started working again , weird you can close it I think
