### ISSUE TITLE
#include completion File info has the wrong casing and path separator directions

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5306]
On Windows it's all caps and the preferredPathSeparator set to Backslash shows it as forward slashes.

0.27.0 regression (works with 0.26.3).

**Comment by elahehrashedi** [comment]
This issue is fixed in 0.28.0.
0.28.0 release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0
