### ISSUE TITLE
Add support for CoreGuideLine Checker 

### ISSUE THREAD

**Issue by navidR** [microsoft/vscode-cpptools#531]
Both Microsoft and Clang (tidy) does provide infrastructure for CoreGuideLine checker. I estimate this is trivial amount of job to add *official* support to one of them to this extension. 

https://github.com/Microsoft/GSL
https://www.nuget.org/packages/Microsoft.CppCoreCheck
http://clang.llvm.org/extra/clang-tidy/

**Comment by amigo421** [comment]
Agreed, static analysis is required.

**Comment by terencechow** [comment]
Can we get an update on this? I feel like this should be a priority. Coding with the Core Guidelines should be mandatory...

**Comment by sean-mcmanus** [comment]
@terencechow No progress has been made. It's on our "backlog" and somewhat out of our feature scope focus. We'd be willing to accept a pull request to integrate static analysis tools. Or the teams who are implementing the other tools could create their own extension. If more people could request the VS team implementing the core guideline checker in VS 2017 to port it to VS Code too maybe they'd do the work: https://blogs.msdn.microsoft.com/vcblog/2017/08/11/c-core-guidelines-checker-in-visual-studio-2017/ .

**Comment by gocarlos** [comment]
there is an extension for clang-tidy: https://github.com/alesiong/clang-tidy-linter
