### ISSUE TITLE
IntelliSense not work corrtently when using inline assembly language in C code

### ISSUE THREAD

**Issue by smcdef** [microsoft/vscode-cpptools#5310]
**Type: LanguageService**

C

**Describe the bug**
- OS and Version: macOS Catalina 10.15.4
- VS Code Version:1.44.1
- C/C++ Extension Version:0.27.0
- Other extensions you installed (and if the issue persists after disabling them):None
- Does this issue involve using SSH remote to run the extension on a remote machine?:No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
workspace for Linux kernel code
**Steps to reproduce**

Highlight is not work corrently. The code can be found [here](https://elixir.bootlin.com/linux/v4.19.106/source/arch/x86/include/asm/processor.h#L49).

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![Snipaste_2020-04-16_16-10-52](https://user-images.githubusercontent.com/26999519/79431404-007f0800-7ffd-11ea-81d0-99f5222d8868.jpg)

**Additional context**

**Comment by sean-mcmanus** [comment]
I'm not reproing the bug. Can you provide more repro info? Does the bug happen even if the C/C++ extension is disabled? Do you get any IntelliSense errors?

![image](https://user-images.githubusercontent.com/19859882/79508151-d40fbf80-7fed-11ea-80a1-578d17adc0cf.png)

**Comment by smcdef** [comment]
> I'm not reproing the bug. Can you provide more repro info? Does the bug happen even if the C/C++ extension is disabled? Do you get any IntelliSense errors?
> 
> ![image](https://user-images.githubusercontent.com/19859882/79508151-d40fbf80-7fed-11ea-80a1-578d17adc0cf.png)

When I disable the C/C++ extension, the bug is exist too. So it may be the VSCode's bug?

**Comment by smcdef** [comment]
> I'm not reproing the bug. Can you provide more repro info? Does the bug happen even if the C/C++ extension is disabled? Do you get any IntelliSense errors?
> 
> ![image](https://user-images.githubusercontent.com/19859882/79508151-d40fbf80-7fed-11ea-80a1-578d17adc0cf.png)

The following code can cause the problem.
```c
static inline void *current_text_addr(void)
{
	void *pc;

	asm volatile("mov $1f, %0; 1:":"=r" (pc));

	return pc;
}
```

**Comment by sean-mcmanus** [comment]
Sure, you can try filing a VS Code bug, but I'm not able to repro the issue even with just VS Code, so it might be an issue with another extension you have installed.

**Comment by smcdef** [comment]
> Sure, you can try filing a VS Code bug, but I'm not able to repro the issue even with just VS Code, so it might be an issue with another extension you have installed.

Thanks a lot. I have find the problem because of anther extension which is "ARM assembly highlightling for Visual Code". Thanks very much again.
