### ISSUE TITLE
Incorrect warning "Path is not a directory"

### ISSUE THREAD

**Issue by Richhoef** [microsoft/vscode-cpptools#5314]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Microsoft Windows [Version 10.0.18363.752]
- VS Code Version: 1.44.1
- C/C++ Extension Version: 2.27.0
When I want to use the env section in c_cpp_properties, I get yellow squiggles under the paths at the default_forcedInclude saying "Path is not a directory". Although this is true, it is also completely irrelevant. The forcedInclude is ment to be a file (at least, in my case it is). 

**Steps to reproduce**

Here is my c_cpp_properties.json:
```
{
   "env": {
       "default_includePath": [
         "${workspaceFolder}/some_path",
         "${workspaceFolder}/some_other_path"
       ],
       "default_defines": [
           "some_defines",
           "some_other_defines"
       ],
       "default_defines2": [
           "some_more_defines",
           "some_more_other_defines"
       ],
       "default_forcedInclude": [
           "${workspaceFolder}/some_path/some_file.h",
           "${workspaceFolder}/some_path/some_file.c"
        ],
        "default_browsepath": [
           "${workspaceFolder}/some_more_path",
           "${workspaceFolder}/some_more_other_path"
         ]
   },
   "configurations": [
       {
           "name": "Debug",
           "includePath": [ "${default_includePath}" ],
           "defines": [
               "${default_defines}",
               "${default_defines2}",
               "_DEBUG"
           ],
           "intelliSenseMode": "msvc-x64",
           "cStandard": "c89",
           "forcedInclude": [ "${default_forcedInclude}" ],
           "browse": {
               "path": [ "${default_browsepath}" ],
               "limitSymbolsToIncludedHeaders": true
           }
       }
   ],
   "version": 4
}
```

**Expected behavior**

I did not expect it to show a warning and yellow squiggles.

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/51912545/79467226-d9750600-7ffd-11ea-8b34-223f50d89a38.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders .
