### ISSUE TITLE
After update, integrated terminal isn't working correctly

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode-cpptools#5319]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Delete tasks.json and launch.json (Doesn't make a difference)
2. Write a simple c++ console code. press F5 (or your debugging hotkey)
3.  A prompt appears, select C++ (GDB/LLDB)  (something like that)
4. Build task starts and completes(hopefully). 
<5.> A terminal panel named cppdbg:simple.exe opens up, a long command (@11tyOne 's Powershell error) is automatically passed to it, and thats it.

- No output from my program,
- terminal accepts no input(can't type anything).
- The floating debug toolbar shows up,
- The Debug View is blank, as if there's no debugging going on.
- There's a little badge on the debugview button on the sidebar with a clock icon on it which changes to '1' after a while.

But nothing else changes for all eternity.

It used work on my machine flawlessly before this(last year) I don't remember which version, some time last week I enabled auto-update for a while and I never checked the new version(no projects then). But now I need it.

I tried debugging externalConsole: true after reading this conversation and there was a popup with a traceback message of an error, also appeared in the Debug Console:

```
Starting: "C:\SDK\C++\MinGW\bin\gdb.exe" --interpreter=mi
Traceback (most recent call last):
  File "C:\SDK\C++\MinGW\bin\site.py", line 49, in <module>
    import os
  File "C:\SDK\C++\MinGW\bin\os.py", line 410
    yield from walk(new_path, topdown, onerror, followlinks)
             ^
SyntaxError: invalid syntax
"C:\SDK\C++\MinGW\bin\gdb.exe" exited with code 1 (0x1).

```
but didn't work.

Extension version: 0.27.0
VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2197)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

_Originally posted by @makeway4pK in https://github.com/microsoft/vscode-cpptools/issues/5051#issuecomment-615011634_

**Comment by pieandcakes** [comment]
Also, @pieandcakes , I noticed after reinstalling this extension, When its downloading its extra stuff (3-stage) it **restarts from stage 1/3** when its been on 3/3 for about 10 seconds (less than what 1/3 and 2/3 took) and quickly steps through 1/3, 2/3 to 3/3 which is the Debugger.
It stays on it for about a second and goes away, **no confirmation** of the extension being ready or anything. Intellisense works, documentation shows on hover,
but the same mess with the debugger.

_Originally posted by @makeway4pK in https://github.com/microsoft/vscode-cpptools/issues/5051#issuecomment-615014638_

**Comment by pieandcakes** [comment]
@WardenGnaw Please investigate

**Comment by makeway4pK** [comment]
Today, I tried using the debugger with the extension version 0.23.0 (offline installer) and weirdly, the behavior is EXACTLY the same as 0.27.0 and 0.26.3

Sorry for opening an issue here but I think this has to do with changes in vscode itself.

**Comment by makeway4pK** [comment]
I resolved this issue after reinstalling my MinGW package, please close this issue and sorry for the fuss😅, @pieandcakes
