### ISSUE TITLE
[feature request] Statistics for IntelliSense database

### ISSUE THREAD

**Issue by NerdyId** [microsoft/vscode-cpptools#5327]
**Type: LanguageService**

I'd like to have a command that lists filenames in database, number of records per file, last update time and other metadata.

It would be very useful to troubleshoot issues which I'm experiencing such as IntelliSense not parsing files which I was expecting it to pick up, parsing the same files again after restart and so on.

**Comment by sean-mcmanus** [comment]
Some of the info should be currently available via setting the C_Cpp.loggingLevel to "Debug" (i.e. the "tag parsing", "discovering files..." related messages), e.g.

```
cpptools/resetDatabase
cpptools/resetDatabaseReady
Database safe to open
Code browsing service initialized
Populate include completion cache.
Discovering files...
  Processing folder (recursive): C:/TEST/
  Discovering files: 4818 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  tag parsing file: TEST.CPP
  Parsing: 1 files(s) processed
```

You could also use a SQLite database browsing tool such as https://sqlitebrowser.org/ .

**Comment by NerdyId** [comment]
Thanks for the suggestion.

I can easily get the needed information via SQL browser. For some reason I expected this database to be using proprietary or custom format but luckily it's not the case.

I already have logging enable, so I can see these "tag parsing file", "N files removed", etc
But it would still be nice if it would tell how many files are currently are in the database and some other short summary. Listing all files is no longer needed since it can inspected with other tools.

**Comment by sean-mcmanus** [comment]
FYI, we add all the files under the browse.path to the database (even file types not recognized as C/C++) in case we find a #include and need it later (e.g. `#include <specialExt.foo>` we could/may change it to not do that later), but only a subset of those files will be parsed as C++ with symbols.

**Comment by NerdyId** [comment]
My intention was to populate this database as much as possible so that it would not need to parse files(avoiding 'problem' alerts) as often. I also assume this database is also used for features like Find All References and I'd like to be sure that I'm not missing any references due to some files not being parsed.

I wish the documentation would explain in greater details how discovering, parsing and lookups work, so that people would have less troubles configuring their projects.

Also I'm not sure how browse.path interacts with 'exclude', limitSymbolsToIncludedHeaders and similar rules.

**Comment by sean-mcmanus** [comment]
We have some docs at https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference , but it might not answer all the questions you raised.

browse.path uses files.exclude to filter out files/directories, but it's recommend that you use only folder exclusions (and if you need file-based exclusions you'll need to change the C_Cpp.exclusionPolicy). limitSymbolsToIncludedHeaders will make it not parse files external to the workspace folder unless they are included from another file (or the file is opened). If you have source files you want parsed in different locations, it's recommended to add multiple workspace folders.

This parsing doesn't affect the flame icon (IntelliSense parsing). It corresponds to the database icon. The database is used by Find All References for references that are external to the current TU.
