### ISSUE TITLE
make error catch (feature)

### ISSUE THREAD

**Issue by opensw** [microsoft/vscode-cpptools#533]
Hello there, will be nice to have an error handler from output console; I mean, if I want to compile a file with gcc/g++ or make (from task.json) and during compilation there are some errors, will be great to (Ctrl +) click on the error showed on output console of Visual Studio Code and to be redirected to specified file at specified line number and column number (like in Eclipse). 

The syntax error showed on the output console is like:
fileName:line number:column number: error: description error

Just an error example:
file.cpp:630:6: error: expected '}' before 'else'

What do you think? I think this feature can improve a lot the productivity.

Cheers
Paolo

**Comment by pieandcakes** [comment]
@opensw `task.json` parsing and handling is done by VSCode and not by our extension. As such, I don't know of a way we can do what you are suggesting. I would suggest you go to https://github.com/Microsoft/vscode/issues and file an issue with them.

Thanks

**Comment by opensw** [comment]
Done :)

**Comment by pieandcakes** [comment]
Thanks. I'm going to close this issue then.
