### ISSUE TITLE
Scope Labels are the same at Function Definition and Invocation

### ISSUE THREAD

**Issue by Redoubts** [microsoft/vscode-cpptools#5331]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS 10.15.4
- VS Code Version: 1.44.2
- C/C++ Extension Version: 0.27.0

In C and C++, function names at definition and invocation are marked with the same scope labels. I would expect these scope labels to be different because 

1) In [outside documentation](https://www.sublimetext.com/docs/3/scope_naming.html#variable), this is suggested:

> Function and method names should be scoped using the following [`variable.function`], but only when they are being invoked. When defined, they should use `entity.name.function`

2) I see other languages and editors make this distinction. Indeed, GitHub formatting gives different colors, as seen in snippets below.

For example, using some zmq code, the C version has

```c
static void *
worker_task(void *args)
{
    ...
    s_set_id(worker);
    ...
}
```
The defined function name "worker_task" is marked with the scopes
```
entity.name.function.c
meta.function.definition.parameters.c
meta.function.c
source.c
```

and "s_set_id" is marked with scopes
```
entity.name.function.c
meta.function-call.c
meta.block.c
source.c
```

* Meta.\* is hard to theme against because it's very language specific, and both def and call site use `entity.name.function` at the top level, which likely means any meta tags a theme uses will be ignored always. 

Similarly, the C++ version has 

```cpp
static void *
worker_thread(void *arg) {
    ...
    s_set_id(worker);
    ...
}
```

with the defined function "worker_thread" marked with the scopes

```
entity.name.function.call.cpp
source.cpp
```

and "s_set_id" with the scopes

```
entity.name.function.call.cpp
source.cpp
```

* This is the same problem with a different cause, since both def and call site use `entity.name.function.call` (???), creating a similarly vexing situation.

**Comment by sean-mcmanus** [comment]
This is a bug with https://github.com/jeff-hykin/cpp-textmate-grammar/issues , which is were C/C++ gets its lexical syntax from (can you file a bug there?). The issue occurs in your repro because the function name is on a new line (i.e. using `static void * worker_task(void *args)` on a single line gives the definition scope.
