### ISSUE TITLE
Outline display unusual when coding is UTF-16

### ISSUE THREAD

**Issue by conghaixu** [microsoft/vscode-cpptools#5334]
**Type: LanguageService**

**Describe the bug**
- OS and Version:WIN 10 Professional 1903 
- VS Code Version:1.44.2
- C/C++ Extension Version:Version 0.27.0: March 30, 2020

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![normal](https://user-images.githubusercontent.com/14147368/79814113-0afc2180-83b0-11ea-87c0-f4f92b6d8815.png)
![unusual](https://user-images.githubusercontent.com/14147368/79814161-26ffc300-83b0-11ea-9073-905109db492a.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
We currently only properly support UTF-8-based files. We're tracking  .UTF-16 support with https://github.com/microsoft/vscode-cpptools/issues/414

**Comment by sean-mcmanus** [comment]
Should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 . Let us know if you see any remaining bugs with non-UTF-8 encodings.
