### ISSUE TITLE
After I used the code format, there was no white space on either side of the < symbol

### ISSUE THREAD

**Issue by huye** [microsoft/vscode-cpptools#5342]
Issue Type: <b>Bug</b>

for (; a<z; ) {}

Extension version: 0.27.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.3.0-3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 x 1278)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.66GB (6.45GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @huye .  We currently utilize `clang-format` for formatting.  It's possible to configure it's behavior using a `.clang-format` file.  Some related documentation is [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).

We do plan to provide our own formatting and format settings in a future version.
