### ISSUE TITLE
Can't follow error in Problems tab in C++ project under WSL

### ISSUE THREAD

**Issue by dzvancuks** [microsoft/vscode-cpptools#5344]
Version: 1.44.0 (system setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
**WSL**

Steps to Reproduce:

1. Open pure makefile project in VSC under WSL, e.g. Ubuntu 16.04 with gcc and make.
2. Configure tasks.json for compilation (see below).
3. Create error. E.g.` int a = "a";`
4. Compile project using task.
5. Switch to PROBLEMS tab and click on error message.
5. Popup message will inform that:
> Unable to open 'file.cpp': Unable to read file 'vscode-remote://wsl+ubuntu-16.04/file.cpp' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu-16.04/file.cpp').

![image](https://user-images.githubusercontent.com/744090/79588426-95a4fe00-80dc-11ea-99a7-115005963cc0.png)

tasks.json:
 `{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Make project",
            "type": "shell",
            "command": "make",
            // use options.cwd property if the Makefile is not in the project root ${workspaceRoot} dir
            "options": {
                "cwd": "${workspaceRoot}"
            },
            // start the build without prompting for task selection, use "group": "build" otherwise
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            },
            // arg passing example: in this case is executed make QUIET=0
            "args": [
                "QUIET=0"
            ],
            // Use the standard less compilation problem matcher.
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "absolute"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
    ]
}`

Same issue if change problemMatcher to `"fileLocation": "relative",`.

Does this issue occur when you try this locally?: No
Does this issue occur when extensions are disabled?: Yes, when using WSL

(redirected here from https://github.com/microsoft/vscode-remote-release/issues/2786)

**Comment by sean-mcmanus** [comment]
I replied to the original issue. Your bug still repros with the C/C++ extension disabled right? Do you know if you're using WSL2 or what else is causing me to know repro the issue?

**Comment by dzvancuks** [comment]
Sorry, fixed item about extension.
I use WSL1 with Ubuntu16 LTS. Extension seems to not affect behavior. I'll re-open original thread as it seems to be Remote issue
