### ISSUE TITLE
Ending Linux 32-bit support

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#5346]
VS Code does not support 32-bit linux as of June 2019 (version 1.36) because it upgraded to a version of Electron that does not support 32-bit linux.  [[link]](https://code.visualstudio.com/updates/v1_36#_linux-32bit-support-ends)

Our extension updated its minimum supported VS Code version so that it can use newer VS Code features.  Unfortunately, as a result of this update, we will no longer be supporting 32-bit linux.

[0.27.0](https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.0) is the last version of the C++ extension with 32-bit linux support.

**Comment by sean-mcmanus** [comment]
Is this done now?
