### ISSUE TITLE
Intellisense bug with operator overload

### ISSUE THREAD

**Issue by zyd2001** [microsoft/vscode-cpptools#5347]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.44.2
- C/C++ Extension Version: 0.27.0
- Other extensions you installed (and if the issue persists after disabling them): none
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I created the test file using Remote-WSL in my WSL Ubuntu system, and saw valid code is marked error. And then I switched to Windows and the error persists. After I disabled all other extensions or change the compilerPath to clang, this error still persists

**Steps to reproduce**

With default setting, create a cpp file with following code
```cpp
class A
{
    friend bool operator==(const A &a, const A &b)
    {
        return true;
    }

    friend bool operator!=(const A &a, const A &b)
    {
        return !(a == b);
    }
};

int main() {}
```

`a == b` in `operator!=` is marked error with message `no operator "==" matches these operands -- operand types are: const A == const A`

This code compiled with no error by using `g++ test.cpp -Wall` or `clang++ test.cpp -Wall`

**Expected behavior**

This code should have no error 

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 4/22/2020, 1:59:07 PM
Version: 0.27.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/g++-8",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/zyd/Code/C++/BigInteger/test.cpp ]:
    /home/zyd/Code/C++/BigInteger/test.cpp
Translation Unit Configurations:
[ /home/zyd/Code/C++/BigInteger/test.cpp ]:
    Process ID: 934
    Memory Usage: 24 MB
    Compiler Path: /usr/bin/g++-8
    Includes:
        /usr/include/c++/8
        /usr/include/x86_64-linux-gnu/c++/8
        /usr/include/c++/8/backward
        /usr/lib/gcc/x86_64-linux-gnu/8/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=80300
Total Memory Usage: 24 MB

空闲环路: 重新分析活动文档
正在检查语法错误: file:///home/zyd/test.cpp
正在为以下项的翻译单元中文件的 IntelliSense 更新进行排队: /home/zyd/test.cpp
cpptools/cpptools_finishUpdateSquiggles
错误波形曲线计数: 1
更新 IntelliSense 时间(秒): 0.255
cpptools/getCodeActions: file:///home/zyd/test.cpp (id: 243)
```
</details>

**Screenshots**

![图片](https://user-images.githubusercontent.com/25120292/80024115-2cd6d080-84a4-11ea-9ba8-b46ceaa313ac.png)

**Additional context**

**Comment by Colengms** [comment]
Hi @zyd2001 .  Thanks for reporting this.  I'm able to repro this in VS.  (The C/C++ Extension for VS Code shares IntelliSense code with VS).  I've opened an issue against VS [here](https://developercommunity.visualstudio.com/content/problem/1002807/incorrect-intellisense-error-for-equality-operator.html).

**Comment by sean-mcmanus** [comment]
The VS team fixed it for "windows-clang-x64" mode, but the bug still repros on Linux with gcc mode, so this isn't isn't fixed for us...I've asked them if we need to create a new bug or if they can re-activate/fix the bug for the other mode.

**Comment by sean-mcmanus** [comment]
I've filed a new bug at https://developercommunity.visualstudio.com/content/problem/1067602/c-intellisense-incorrect-error-for-equality-operat.html .

**Comment by allanleal** [comment]
Any update on this? I get these IntelliSense errors across the entire project (in Linux). Compiling with either gcc or clang produces no errors.

**Comment by sean-mcmanus** [comment]
It's got 0 upvotes -- it could use more upvotes.

**Comment by sean-mcmanus** [comment]
This appears to have been fixed recently.
