### ISSUE TITLE
Cannot open "stdarg.h"

### ISSUE THREAD

**Issue by hect1995** [microsoft/vscode-cpptools#5349]
Type: Debugger

**Describe the bug**
- OS and Version: 10.15.4 OS Catalina
- VS Code Version:  1.44.2
- C/C++ Extension Version: 0.27.0
- A clear and concise description of what the bug is.
Sorry to bother but after updating XCode another problem arised:
<img width="926" alt="Captura de pantalla 2020-04-22 a las 23 06 00" src="https://user-images.githubusercontent.com/19693566/80034565-ebb7de00-84ee-11ea-8a86-7ffc4fbb311a.png">

I do not know how to get the message in English but basically says: "#Include errors have been detected. Consider updating the compile_commands.json file or the includePath value. Wavy error underlining is disabled for this translation unit (/Users/hectoresteban/Documents/C++/C++Projects/DailyCoding/Challenges/chall_278.cpp).C/C++(1696)
Can't open source file (error code "stdarg.h"). (dependency of "iostream") C / C ++ (1696)".

If I compile from outside VS Code it works.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

```
{
    "version": "0.2.0",
    "configurations": [
        {
            
            "name": "(lldb) Iniciar",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/Challenges/DailyCoding_run",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "targetArchitecture": "x86_64",
            "externalConsole": false,
            "MIMode": "lldb"  
        }
    ]
}


```

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}",
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
What do you get when you run the C/C++: Log Diagnostics command from the Command Palette?

**Comment by sean-mcmanus** [comment]
Also, can you try removing the "compilerPath" setting? That might be interfering with the compiler in the compileCommands.

**Comment by hect1995** [comment]
```
-------- Diagnostics - 4/23/2020, 10:05:28 AM
Version: 0.27.0
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}",
        "${workspaceFolder}/**",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks"
    ],
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}",
            "${workspaceFolder}/**",
            "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/hectoresteban/Documents/C++/C++Projects/DailyCoding/Challenges/chall_278.cpp ]:
    /Users/hectoresteban/Documents/C++/C++Projects/DailyCoding/Challenges/chall_278.cpp
Translation Unit Configurations:
[ /Users/hectoresteban/Documents/C++/C++Projects/DailyCoding/Challenges/chall_278.cpp ]:
    Process ID: 4448
    Memory Usage: 26 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /Users/hectoresteban/Documents/C++/C++Projects/DailyCoding
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110003
Total Memory Usage: 26 MB
```

**Comment by sean-mcmanus** [comment]
I get identical results with no errors, and the only difference is I'm not using "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks" in my macFrameworkPath (I don't have that path installed). Does removing that fix it for you or does your code actually need to use that macFrameworkPath? Or if you try to add "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks" to the macFrameworkPath beforehand that might give it higher precedence? I have stdarg.h a few levels under that Library/Frameworks path.

**Comment by sunilvijendra** [comment]
I have the same issue and macFrameworkPath has only "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks. I do not have Xcode installed and only have command line tools to compile and build C++. So, there is no /Applications/Xcode.app!

OS and Version: macOS Catalina 10.15.6 
VS Code Version: 1.49.1

Any workaround or fix available?

Output of C/C++ log diagnostics:

-------- Diagnostics - 9/20/2020, 7:37:02 AM
Version: 1.0.0
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang++",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/sunilvijendra/Projects/cpp-101/func.cpp ]:
    /Users/sunilvijendra/Projects/cpp-101/func.cpp
Translation Unit Configurations:
[ /Users/sunilvijendra/Projects/cpp-101/func.cpp ]:
    Process ID: 89827
    Memory Usage: 121 MB
    Compiler Path: /usr/bin/clang++
    Includes:
        /usr/local/include
        /Library/Developer/CommandLineTools/usr/include/c++/v1
        /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
        /Library/Developer/CommandLineTools/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110003
Total Memory Usage: 121 MB

**Comment by sean-mcmanus** [comment]
@sunilvijendra I'm not sure what is going wrong. Can you use Go to Definition on "stdarg.h" and see if it is able to locate the correct file?

**Comment by atsju** [comment]
Same error here on simple arm-none-eabi-gcc cross-compilation project on windows with cmaketool as configuration provider.
I will provide the link to project for you to reproduce.

**Comment by sunilvijendra** [comment]
> @sunilvijendra I'm not sure what is going wrong. Can you use Go to Definition on "stdarg.h" and see if it is able to locate the correct file?

After update to latest toolset (with BigSur update) i.e., 12.0.0, its working well and I am able to compile well and go to definition of stdarg.h too. 

Thank you

**Comment by carter-thaxton** [comment]
For anyone else seeing this, I ran into a similar problem, and all I had to do was change in `c_cpp_properties.json`:

`"intelliSenseMode": "macos-clang-x64"`  to  `"intelliSenseMode": "clang-x64"`

For some reason, the `macos-clang-x64` include paths have most of the standard C/C++ includes, but not `stdarg.h`.
You can confirm this by looking at the differences between the following platform/toolchain include paths included with Xcode.

Here is the location of the `macos` includes, and have most header files, like `stddef.h`, but not `stdarg.h` for whatever reason:
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include`

Here is where the clang builtin includes are located, and has very similar files as the above, and *does* have `stdarg.h` to support variadic functions:
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include`

It's a strange discrepancy.  If you query the `/usr/bin/clang` tool itself, using:  `clang++ -E -x c++ - -v < /dev/null`
You'll see that it includes both of the above directories in its system include path.
The C/C++ Extension for VSCode must have some special macOS setup for "macos-clang-x64" that avoids the clang toolchain directory above, and that's why `stdarg.h` of all files is causing the issue that surfaces in the error.

Hope this helps someone avoid some frustration...  :)

**Comment by michelleangela** [comment]
@carter-thaxton @sean-mcmanus @Colengc 

I created a new issue report at https://github.com/microsoft/vscode-cpptools/issues/7448 for the differing behavior of `clang-x64` and `macos-clang-x64` IntelliSenseModes. We need some logs to help figure out why the behavior is not the same. @carter-thaxton Please see requested logs from the new issue report.

**Comment by bboysnick5** [comment]
> For anyone else seeing this, I ran into a similar problem, and all I had to do was change in `c_cpp_properties.json`:
> 
> `"intelliSenseMode": "macos-clang-x64"` to `"intelliSenseMode": "clang-x64"`
> 
> For some reason, the `macos-clang-x64` include paths have most of the standard C/C++ includes, but not `stdarg.h`.
> You can confirm this by looking at the differences between the following platform/toolchain include paths included with Xcode.
> 
> Here is the location of the `macos` includes, and have most header files, like `stddef.h`, but not `stdarg.h` for whatever reason:
> `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include`
> 
> Here is where the clang builtin includes are located, and has very similar files as the above, and _does_ have `stdarg.h` to support variadic functions:
> `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include`
> 
> It's a strange discrepancy. If you query the `/usr/bin/clang` tool itself, using: `clang++ -E -x c++ - -v < /dev/null`
> You'll see that it includes both of the above directories in its system include path.
> The C/C++ Extension for VSCode must have some special macOS setup for "macos-clang-x64" that avoids the clang toolchain directory above, and that's why `stdarg.h` of all files is causing the issue that surfaces in the error.
> 
> Hope this helps someone avoid some frustration... :)

I tried your solution but problem persist. Is there a way to force the intelliSenseMode for a hard reset or something? Seems nothing changed after changing one line in c_cpp_properties.json file.

**Comment by sean-mcmanus** [comment]
@bboysnick5 What is your intelliSenseMode in c_cpp_properties.json and what is it reported as being when you run C/C++: Log Diagnostics (`IntelliSense Mode: ` section)?
