### ISSUE TITLE
c_cpp_properties.json not giving correct c++ library path under windows

### ISSUE THREAD

**Issue by mysterytony** [microsoft/vscode-cpptools#535]
- VSCode Version: 1.10.1
- OS Version: windows 10
I have Visual Studio 2017 Community RC version installed.

Steps to Reproduce:
1. create a `.cpp` file, write a `#include` statement, for example, `#include <iostream>`
2. hover the mouse on the yellow lightbulb and generate `c_cpp_properties.json`
3. the `includePath` property is not correct in my case. The default is `C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*` which in my case, the c++ library is under `C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.10.24930\\include\\*`

Perhaps need to detect which version of visual studio one has?

**Comment by bobbrow** [comment]
Yes, this value is currently hardcoded.  We are tracking this in #534 if you want to add any additional input.
