### ISSUE TITLE
Ensure intelliSenseMode matches default compiler

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5352]
When defaults are set in c_cpp_properties.json, there could be a case that the default compiler found does not match the set default intelliSenseMode .

**Task**
Add logic to ensure to select an intelliSenseMode that matches the found default compiler.

**Expected behavior:**

Default intelliSenseMode if default compiler is found:
Default compiler | Expected   IntelliSenseMode
-- | --
Clang | Clang-x64
GCC | Gcc-x64
MSVC | Msvc-x64
unknown | Default for host   development platform

Default intelliSenseMode if compiler is unknown:
Platform | Expected   IntelliSenseMode
-- | --
macOS | Clang-x64
Linux x64 | Gcc-x64
Windows | Msvc-x64

**Comment by bobbrow** [comment]
@michelleangela was this completed in 0.28.0?

**Comment by bobbrow** [comment]
If so, can you close it?  Otherwise, can you set the milestone on this for 0.29.0?
