### ISSUE TITLE
The includePath setting seems to be ignored by IntelliSense?

### ISSUE THREAD

**Issue by PewnyPL** [microsoft/vscode-cpptools#5354]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: VSCodium 1.37.1
- C/C++ Extension Version: 0.27.0
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

There are red error squiggly lines displayed for defines, as IntelliSense seems to not search through files in includePath.

Based on log output shown in (similar) issue #3731 it seems that in my case the entirety of includePath is ignored when the file is parsed. Here is the full log file:

```-------- Diagnostics - 23.04.2020, 20:43:47
Version: 0.27.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/include/**",
        "${workspaceFolder}/include/PR/**",
        "${workspaceFolder}/src/game/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "E:/cygwin64/bin/gcc.exe",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}/"
        ],
        "limitSymbolsToIncludedHeaders": true
    },
    "compilerArgs": []
}
Translation Unit Mappings:
[ C:\SM64ZelHack\src\game\behaviors\bobomb.inc.c ]:
    C:\SM64ZELHACK\SRC\GAME\BEHAVIORS\BOBOMB.INC.C
Translation Unit Configurations:
[ C:\SM64ZelHack\src\game\behaviors\bobomb.inc.c ]:
    Process ID: 10024
    Memory Usage: 12 MB
    Compiler Path: e:/cygwin64/bin/gcc.exe
    Includes:
        E:\CYGWIN64\LIB\GCC\X86_64-PC-CYGWIN\7.3.0\INCLUDE
        E:\CYGWIN64\USR\INCLUDE
        E:\CYGWIN64\USR\INCLUDE\W32API
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=70300
Total Memory Usage: 12 MB
```

The reason I think it's ignored, in the log supplied in issue #3731 the paths specified in includePath appear in Includes part of the process.

**Steps to reproduce**
Would be hard, as it would likely require the entire source code.

**Comment by sean-mcmanus** [comment]
When `"**"` is used, the path will only be sent to the IntelliSense process (in the Includes) if the file actually references a file under the particular recursive path. If you believe the path is incorrectly being omitted, you could try to workaround the bug via removing the `"**"` and replacing it with the actual paths that are required (assuming there are too many).

**Comment by PewnyPL** [comment]
That is true, the files in question do not reference any header files. Those files are segments of a much bigger C file that has all the #include directives, and are being included into it later on.

I tried to modify the settings as you mentioned, here is what the log looks like currently:

```
-------- Diagnostics - 24.04.2020, 00:34:49
Version: 0.27.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/include/**",
        "${workspaceFolder}/include/PR/**",
        "${workspaceFolder}/src/game/**",
        "C:/SM64ZelHack/src/game/",
        "C:/SM64ZelHack/",
        "C:/SM64ZelHack/include/",
        "C:/SM64ZelHack/include/PR/",
        "C:/SM64ZelHack/include/PR/ultratypes.h"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE",
        "VERSION_US"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "E:/cygwin64/bin/gcc.exe",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}/"
        ],
        "limitSymbolsToIncludedHeaders": true
    },
    "compilerArgs": []
}
Translation Unit Mappings:
[ C:\SM64ZelHack\src\game\behaviors\wiggler.inc.c ]:
    C:\SM64ZELHACK\SRC\GAME\BEHAVIORS\WIGGLER.INC.C
Translation Unit Configurations:
[ C:\SM64ZelHack\src\game\behaviors\wiggler.inc.c ]:
    Process ID: 7988
    Memory Usage: 12 MB
    Compiler Path: e:/cygwin64/bin/gcc.exe
    Includes:
        C:\SM64ZELHACK\SRC\GAME
        C:\SM64ZELHACK
        C:\SM64ZELHACK\INCLUDE
        C:\SM64ZELHACK\INCLUDE\PR
        E:\CYGWIN64\LIB\GCC\X86_64-PC-CYGWIN\7.3.0\INCLUDE
        E:\CYGWIN64\USR\INCLUDE
        E:\CYGWIN64\USR\INCLUDE\W32API
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=70300
Total Memory Usage: 12 MB
```

Now the directories are sent to IntelliSense process, however the .h file itself is still omitted.
Tag Parser finds the definitions properly, sadly it doesn't show error lines when actually using something undefined.

**Comment by sean-mcmanus** [comment]
If you want to have `"C:/SM64ZelHack/include/PR/ultratypes.h"` included for files, you should add it to the `forcedInclude` property (it takes an array of strings, e.g. `[ "C:/SM64ZelHack/include/PR/ultratypes.h" ]`). The includePath is just for paths. Does that solve all your issues?

**Comment by PewnyPL** [comment]
That DOES work. Guess I will have to make a huge force include list then.

**Comment by sean-mcmanus** [comment]
@PewnyPL FYI, `forcedInclude` is only intended to be used when your build process is also doing that, e.g. "-include" flag. Normally, the includePaths are added (e.g. -I) and the source code adds a `#include`, so `forcedInclude` just forces the `#include` to be added.

**Comment by PewnyPL** [comment]
Oh, I know. Again, the compiler doesn't have a problem, because those specific files are not compiled by themselves. They are all included into a parent c file that has all the proper includes. Not my choice in how to do it, but to be fair, if all of those were put into the c file, it would be massive.

**Comment by sean-mcmanus** [comment]
Can I close this issue, or do you believe you're hitting a bug still?

**Comment by PewnyPL** [comment]
Oh right, my bad there, I was going to hit Close and comment last time.
