### ISSUE TITLE
Find All References fails if it's used a 2nd time while a previous one is in progress

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5356]
Do Find All References and then do another Find All References before the 1st is complete. With a high probability, it will fail and give no results. There may be certain things that affect the repro probability (not sure what exactly). Error logging shows:

  ERR TreeError [CppReferencesView] Tree element not found: [object Object]: Error: TreeError [CppReferencesView] Tree element not found: [object Object]
    at t.ObjectTreeModel.getElementLocation 
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Cannot resolve tree item for element 0/0:
console.ts:137 [Extension Host] stack trace: Error: Cannot resolve tree item for element 0/0:

It's supposed to cancel the 1st Find All References and then show the results for the 2nd one.

**Comment by Colengms** [comment]
@sean-mcmanus Does this still repro for you?  I'm not (easily) able to repro.  Perhaps this was fixed by https://github.com/microsoft/vscode-cpptools/pull/5114 ?

**Comment by sean-mcmanus** [comment]
Yeah, I just reproed it with 0.28.0 on my 1st try: ERR Cannot resolve tree item for element 0/0:: Error: Cannot resolve tree item for element 0/0:

Could be related to https://github.com/microsoft/vscode-cpptools/issues/5424 (although in that case I don't recall an error message in the developer console).

**Comment by bobbrow** [comment]
We're not seeing other reports of this issue, and given that it's an old issue, we'll close as "won't fix" unless we see more community interest.
