### ISSUE TITLE
c_cpp_properties.json getting reset to default

### ISSUE THREAD

**Issue by yaofahua** [microsoft/vscode-cpptools#5363]
Host OS：Windows 10
Guest OS in VMware Workstation 15 Player: Ubuntu 14.04.05 LTS
VS Code version: 1.44.2
Extension version: 0.27.0

Source is put on some folder of Ubuntu , Windows can access this folder by network folder share .
To avoid access problems from VSCode, I also map the shared folder to local driver letter for example Z. So at last the path is like : Z:\src\some_project\.

Sometimes I found that Intelisense didn't work , so I check the c_cpp_properties.json file, the includepath has returned to ${workspaceFolder}, other include paths were disappeared.

I found this issue：https://github.com/Microsoft/vscode-cpptools/issues/927, but that's not my case，I didn't use cmake.

Intelisense is so important to me that I download and check the source of cpptools myself , then I found the following code: 

    public checkCppProperties(): void {
        // Check for change properties in case of file watcher failure.
        let propertiesFile: string = path.join(this.configFolder, "c_cpp_properties.json");
        fs.stat(propertiesFile, (err, stats) => {
            if (err) {
                if (this.propertiesFile) {
                    this.propertiesFile = null; // File deleted.
                    this.resetToDefaultSettings(true);
                    this.handleConfigurationChange();
                }
            } else if (stats.mtime > this.configFileWatcherFallbackTime) {
                if (!this.propertiesFile) {
                    this.propertiesFile = vscode.Uri.file(propertiesFile); // File created.
                }
                this.handleConfigurationChange();
            }
        });
    }

CheckCppProperties function is called every 2.5 seconds, and if something goes wrong when calling fs.stat, c_cpp_properties.json will resetToDefaultSettings. Because my source is accessed by network folder share, that's possible to happen I think. 

I tried to comment the if branch and include path hasn't disappeared anymore by now. Of cause this is not the final solution, maybe the err condtion should limit to some error code ?

**Comment by sean-mcmanus** [comment]
Do you know what the err.code is? Can you try making the change at https://github.com/microsoft/vscode-cpptools/pull/5368/files and seeing if that fixes it for you (instead of commenting out the "if" branch)?

**Comment by yaofahua** [comment]
In my situation err.code is UNKNOWN and err.errno is -4094. 
And https://github.com/microsoft/vscode-cpptools/pull/5368/files works for me .

**Comment by sean-mcmanus** [comment]
@yaofahua Okay, thanks. The fix should be in 0.28.0-insiders or 0.28.0-insiders2 (not sure yet).
