### ISSUE TITLE
MSYS2: Debugger variables don't display STL correctly

### ISSUE THREAD

**Issue by rewrking** [microsoft/vscode-cpptools#5364]
Type: Debugger

- OS and Version: Windows 10
- VS Code Version: 1.44.2
- C/C++ Extension Version: 0.27.0

I've been using MSYS2's version of mingw for a while now, and I've been seeing strange variable output for stl containers like std::map & std::vector. I'm assuming this is a Debugger bug in this extension, but I'm really not too sure. I'd be interested to know if this is a project configuration issue somewhere.

Here's the output:

![test](https://i.imgur.com/z1q5XSG.png)

Here's what it should look like (from the linux build of the same project, at the same breakpoint):

![test2](https://i.imgur.com/a3iHZQL.png)

As you can see, it looks like it's outputting some GCC internals, which are not at all useful.

Edit: this also happens for std::unique_ptr, std::shared_ptr, std::string (basically anything from the stl it seems)

**To Reproduce**
1. Install [MSYS2](https://www.msys2.org/) (msys2-x86_64-20190524) & open the terminal via mingw64.exe 
2. Install GCC toolchain (64-bit) via:
```
pacman -S mingw-w64-x86_64-toolchain 
```
(if you don't upgrade pacman, it should install GCC 8.3.0)
3. Configure a vscode project for gcc, and direct the any paths to C:/msys64/mingw64/bin (including gdb)
4. Make a simple std::map or std::vector and examine the output in the debugger when stepping through.

Here's my launch.json:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "GDB/LLDB",
			"type": "cppdbg",
			"request": "launch",
			"program": "${workspaceFolder}/bin/Debug/${workspaceRootFolderName}.exe",
			"args": [
				"-exec info registers"
			],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"preLaunchTask": "Build: Debug",
			"externalConsole": false,
			"internalConsoleOptions": "neverOpen",
			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			],
			"windows": {
				"MIMode": "gdb",
				"miDebuggerPath": "C:/msys64/mingw64/bin/gdb.exe",
				"env": {
					"Path": "C:/msys64/mingw64/bin"
				}
			},
			"linux": {
				"program": "${workspaceFolder}/bin/Debug/${workspaceRootFolderName}",
				"MIMode": "gdb",
				"miDebuggerPath": "/usr/bin/gdb",
				"env": {
					"PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
				}
			},
			"osx": {
				"program": "${workspaceFolder}/bin/Debug/${workspaceRootFolderName}",
				"MIMode": "lldb",
				"env": {
					"PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
				}
			},
		}
	]
}
```

I can make a sample project as well if that would be easier.

**Comment by rewrking** [comment]
Hmmm, updating all the msys packages & recompiling (on GCC 10.1.0 instead of maybe a bugged 8.3.0) seemed to have fixed this.

**Comment by AXDHY** [comment]
Thanks a lot. Because of your issue, I tried using MSYS2 and found that MSYS2 is a useful configuration tool for C++ debug in VSCode on Win32 with different debuggers and solved the problem which you have met 3 years ago.
