### ISSUE TITLE
Can not find path 

### ISSUE THREAD

**Issue by kinglezhuang** [microsoft/vscode-cpptools#5365]
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/Users/kingle.zhuang/emsdk/upstream/emscripten/system/include/"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

for include path, i try several below solutions but still can not find path at all
"/Users/kingle.zhuang/emsdk/upstream/emscripten/system/include/"
"/Users/kingle.zhuang/emsdk/upstream/emscripten/system/include/**"

> Executing task: /usr/bin/clang++ -std=c++11 -stdlib=libc++ -g /Users/kingle.zhuang/Desktop/testing/*.cpp /Users/kingle.zhuang/Desktop/testing/bind/*.cpp -o /Users/kingle.zhuang/Desktop/testing/.vscode/c_cpp_properties <

/Users/kingle.zhuang/Desktop/testing/main.cpp:4:10: fatal error: 'emscripten/emscripten.h' file not found
#include "emscripten/emscripten.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
The terminal process terminated with exit code: 1

any suggestion?

**Comment by Colengms** [comment]
Hi @kinglezhuang .  Can you confirm that there is a file titled "emscripten.h" in a folder titled "emscripten"?  Based on the information provided, it looks like the "emscripten" folder is a parent to "system/include".  Perhaps use? : 

```
#include <emscripten.h>
```

If that is not the issue, please provide the full path to the file you are trying to include, as well as the output of the "Log Diagnostics" command.  That should tell us the configuration that IntelliSense is using for the file you have open.
