### ISSUE TITLE
GCC Include path does not find '.h' in workspace/lib folder

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#5375]
Issue Type: <b>Bug</b>

See screen snapshot that contains the details

![Screenshot 2020-04-28 at 16 29 10](https://user-images.githubusercontent.com/5303630/80540758-88570180-896f-11ea-8cb5-215c86277fed.png)

1. setup standard(?) c++ workspace.
2. created c_cpp_properties.json file. (from vscode cmd).
3. place header file in lib folder under workspace
4. included '++include "file.h" in main program.
5. call user function in main function.
6. Press F6 to compile and run main function.
7. viewed c_cpp_properties.json - 
   has  "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/lib/**"    <== added first attempt failded, no change
            ],
8. receive compile error: can not find named include file.

Expect compile and run to work. - does not compile.
Change #include statement to "./lib/file.h" compiler finds the ".h" file.

I ran it without the path to "lib" folder and with it in. No difference.

see attached snapshot for clearer display

Extension version: 0.27.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.19.98-08076-g24ab33fb8e14

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (2 x 1607)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|6.48GB (0.90GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by sean-mcmanus** [comment]
The c_cpp_properties.json isn't used for building (just IntelliSense). You need to modify your tasks.json that does the actual compiling. See https://code.visualstudio.com/docs/cpp/config-linux

**Comment by ghost** [comment]
Yes I have found that out. I went to tasks.json and played with the 
args value.  I used -I $HOME/lib and it still gave the error.
Then I change the "-g" optoin to "-c".. The compile finish correctly
(with the -I option), but the "link" or those results after the compile
had a problem. I was left with the hello_world.o file in the workspace folder.
This tells me there is something about the default run command, that
does not change the include path values. I don;t know what is going on
behind the scenes. It only seems to work if all of the files are in the
same directory (does not mention this in the documentation that I have read)
Intellisense has no problem with the include statement It found it in the ./lib folder.

That is all that I know.
