### ISSUE TITLE
See https://github.com/microsoft/vscode/issues/96636

### ISSUE THREAD

**Issue by salda** [microsoft/vscode-cpptools#5379]
**Type: LanguageService**
**Describe the bug**
See https://github.com/microsoft/vscode/issues/96636
- C/C++ Extension Version: 0.28.0-insiders
- Other extensions you installed (and if the issue persists after disabling them): C++ Intellisense, persists after disabling it

**Steps to reproduce**
c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/SDL2-2.0.12/include/**",
                "${workspaceFolder}/SDL2_gfx-1.0.4/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++20"
        }
    ],
    "version": 4
}

**Expected behavior**
Intellisense run, build task work.

1. Logs from the command `C/C++: Log Diagnostics` => does not open

**Screenshots**
See https://github.com/microsoft/vscode/issues/96636

**Comment by salda** [comment]
Hm, one of the problems was "Nepovedlo se spustit jazykový server C/C++. Funkce IntelliSense se zakážou. Chyba: Missing binary at c:\Users\salda\.vscode-insiders\extensions\ms-vscode.cpptools-0.28.0-insiders\bin\cpptools.exe", but I don't even have that bin folder from that path.. try to reinstall, but how can this happen during the update?

**Comment by salda** [comment]
the same after reinstall:
![image](https://user-images.githubusercontent.com/3855627/80646362-daca1800-8a6c-11ea-846d-3f10001e3639.png)
and
![image](https://user-images.githubusercontent.com/3855627/80646385-e1588f80-8a6c-11ea-8159-2a7dd7e48232.png)

**Comment by salda** [comment]
Ok, by uninstalling, removing the folder (which is another bug, it should be removed automatically) and installing again, it works better, but now it produces incorrect outputs and in OUTPUT window, I see "The task provider for "C/C++" tasks unexpectedly provided a task of type "shell"."

**Comment by sean-mcmanus** [comment]
What version of the C/C++ extension are you using now? We have 0.28.0-insiders and 0.27.1 as the latest. How do you get that task provider error?

**Comment by sean-mcmanus** [comment]
@salda VS Code intentionally doesn't remove the extension folder after an extension is uinstalled -- you have to restart VS Code to get it to remove the extension folder.

**Comment by salda** [comment]
I have and had 0.28.0-insiders, the folder remained even after restart. Now it works, but somehow pdbs are corrupted and inls missing, it's totally strange. Trying to put it to functional state.

**Comment by salda** [comment]
Ok, rebuilt everything and it works now, but I don't have a clue what happened during that update.

**Comment by Colengms** [comment]
We occasionally get reports of dependencies failing to download.  Our ideal solution is tracked by https://github.com/microsoft/vscode/issues/23251 .  It sounds like this instance has been addressed, so closing this issue.
