### ISSUE TITLE
${command:pickRemoteProcess} doesn't seem to work when using Bash on Windows

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode-cpptools#538]
Its causing an unknown OS type error to come back.

**Comment by pieandcakes** [comment]
No Repro. Seems to be a machine issue at the time.

**Comment by hajekj** [comment]
I was able to reproduce it. It says that the file specified cannot be found. Followed this sample (https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/Windows%20Subsystem%20for%20Linux.md#example-launchjson-for-attaching-to-an-existing-process) however it doesn't work. Running latest version of Fall Creators Update 1709 and VS Code and CPP Tools also.
