### ISSUE TITLE
Delay tag parsing to wait for cached config for "open file on startup" scenario

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5380]
**Issue:**
When VS Code starts up with a source file already opened and there is an existing cached custom config and browse DB, the extension will tag parse any eligible browse files for the opened source file instead of using the cached config and cached browse DB. This causes unnecessary CPU cycles which can be a lot if the extension is tag parsing a lot of browse files on start up.

**Proposed solution:**
Delay tag parsing with the open file on startup scenario until any cached custom config and browse DB is processed.

**Comment by Colengms** [comment]
Is this confirmed?  I thought we investigated this, and it does not actually tag parse anything before applying the cached custom config.

**Comment by michelleangela** [comment]
Cannot reproduce the case that tag parses before using the cached custom config and cashed DB.
