### ISSUE TITLE
ARM64 mode: inline assembler clobber registers are still wrongly reported as error

### ISSUE THREAD

**Issue by RSDuck** [microsoft/vscode-cpptools#5381]
**Type: LanguageService**

**Describe the bug**

ARM64 registers in the clobber list of inline assembler statements are reported as errors, while x64 registers aren't.

**Steps to reproduce**
Set intellisenseMode to gcc-arm64 and paste the following code inside a file:

```cpp
#include <arm_neon.h>
#include <stdint.h>

typedef int32_t s32;

void MatrixMult4x4(s32* m, s32* s)
{
    __asm__ volatile
    (
        :
        :
        : "q0", "x0", "w0", "eax"
    );
}
```

**Expected behavior**

It should be the other way around.

**Comment by michelleangela** [comment]
Could you provide the following two logs to help us investigate the issue?

1. Log output from enabling the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
2. Log output from running the command `C/C++: Log Diagnostics`

**Comment by sean-mcmanus** [comment]
In particular, what compiler are you using or are special flags being used? The arm compilers I've tried don't compile that by default.

**Comment by RSDuck** [comment]
I am sorry, the code I provided is invalid, I remove some part to make it more compact, but didn't check if it would still work.

This is the correct snippet:
```c
#include <arm_neon.h>
#include <stdint.h>

typedef int32_t s32;

void MatrixMult4x4(s32* m, s32* s)
{
    __asm__ volatile
    (
        ""
        :
        :
        : "q0", "x0", "w0", "eax"
    );
}
```

This is my diagnostics log:

```
-------- Diagnostics - 30.4.2020, 16:54:06
Version: 0.28.0-insiders
Current Configuration:
{
    "name": "blarg",
    "intelliSenseMode": "gcc-arm64",
    "compilerPath": "C:\\msys64\\opt\\devkitpro\\devkitA64\\bin\\aarch64-none-elf-g++.exe",
    "compilerArgs": [],
    "cStandard": "c11",
    "cppStandard": "c++11",
    "browse": {
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Kemal\Desktop\cpptools_bug5381\main.cpp ]:
    C:\USERS\KEMAL\DESKTOP\CPPTOOLS_BUG5381\MAIN.CPP
Translation Unit Configurations:
[ C:\Users\Kemal\Desktop\cpptools_bug5381\main.cpp ]:
    Process ID: 2084
    Memory Usage: 23 MB
    Compiler Path: C:\msys64\opt\devkitpro\devkitA64\bin\aarch64-none-elf-g++.exe
    Includes:
        C:\MSYS64\OPT\DEVKITPRO\DEVKITA64\AARCH64-NONE-ELF\INCLUDE\C++\9.2.0
        C:\MSYS64\OPT\DEVKITPRO\DEVKITA64\AARCH64-NONE-ELF\INCLUDE\C++\9.2.0\AARCH64-NONE-ELF
        C:\MSYS64\OPT\DEVKITPRO\DEVKITA64\AARCH64-NONE-ELF\INCLUDE\C++\9.2.0\BACKWARD
        C:\MSYS64\OPT\DEVKITPRO\DEVKITA64\LIB\GCC\AARCH64-NONE-ELF\9.2.0\INCLUDE
        C:\MSYS64\OPT\DEVKITPRO\DEVKITA64\LIB\GCC\AARCH64-NONE-ELF\9.2.0\INCLUDE-FIXED
        C:\MSYS64\OPT\DEVKITPRO\DEVKITA64\AARCH64-NONE-ELF\INCLUDE
    Standard Version: c++11
    IntelliSense Mode: gcc-arm64
    Other Flags:
        --g++
        --gnu_version=90200
Total Memory Usage: 23 MB
```

**Comment by sean-mcmanus** [comment]
What are the errors? "unknown register name" or something else?

There's already a bug tracking the unknown register issue at
https://github.com/microsoft/vscode-cpptools/issues/4382
and
https://developercommunity.visualstudio.com/content/problem/778258/cc-intellisense-shows-unknown-register-name-with-a.html

**Comment by RSDuck** [comment]
yes, that's the same issue, as the ones you linked, I have to apologise for creating a duplicate issue.

The only difference is that those were created when there still was no arm/arm64 intellisense mode, i.e. the behaviour shown is correct for x64 intellisense mode.
