### ISSUE TITLE
Some IntelliSense operations cause cpptools to stall until a TU update is complete

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5382]
This works, but may be too slow at times. Sometimes it takes 30 seconds to jump into correct header. Is anything being done about IntelliSense performance?

_Originally posted by @ghuser404 in https://github.com/microsoft/vscode-cpptools/issues/2564#issuecomment-621510381_

**Comment by sean-mcmanus** [comment]
@ghuser404 Yeah, I saw some slowness when navigating through multiple headers.

My initial investigation showed that the main processing thread was getting stuck by a documentHighlight request when the cursor moved to the #include line before the Go to Def was done (this request is normally fast, but would be slow the 1st time the file is opened). So skipping that might fix this (it's possible there are more issues too though).

**Comment by bobbrow** [comment]
This should have been addressed with #7759. If you are still experiencing issues with this, please let us know.
