### ISSUE TITLE
[cppvsdbg] Integrated Terminal not working

### ISSUE THREAD

**Issue by datechnomadmole** [microsoft/vscode-cpptools#5386]
Type: Debugger

Describe the bug

- OS and Version:Windows 10 1909
- VS Code Version:1.44.2
- C/C++ Extension Version:0.27.1
- Other extensions you installed (and if the issue persists after disabling them):

I have a simple Hello World program written in C.  If I build it and then run the program from the integrated terminal I see the output but if I debug it I don't see any output in the integrated terminal.  If I set externalConsole to true then an external console opens and I see the output.

launch.json

 "version": "0.2.0",
    "configurations": [
        {
            "name": "debug active file",
            "type": "cppvsdbg",
             "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],

            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "preLaunchTask": "build active file"
        },

![image](https://user-images.githubusercontent.com/39510314/80709724-63979100-8b0b-11ea-8638-98461be6c337.png)

**Comment by WardenGnaw** [comment]
Unfortunately, the integrated terminal is not supported yet for cppvsdbg.

**Comment by olaldiko** [comment]
We are also lacking the support for using the integrated console for debugging in our company as well. Are there any plans to implement this feature soon?
Thanks!

**Comment by WardenGnaw** [comment]
As of [1.2.0](https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0), `cppvsdbg` supports `"console": "integratedTerminal"` in the `launch.json`.

https://github.com/microsoft/vscode-cpptools/pull/6794

**Comment by olaldiko** [comment]
Many thanks!!!
