### ISSUE TITLE
The task provider for "C/C++" tasks unexpectedly provided a task of type "shell".

### ISSUE THREAD

**Issue by sarahkittyy** [microsoft/vscode-cpptools#5388]
VSCode version:
```
1.45.0-insider
a0fe37870c42e0704a492cdc6b8550b4cf23f63c
x64
```
vscode-cpptools version: `0.28.0-insiders`

Here is my `tasks.json`.
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "gen",
			"type": "shell",
			"command": "cmake",
			"args": [
				"-DCMAKE_BUILD_TYPE=DEBUG",
				".."
			],
			"options": {
				"cwd": "build"
			}
		},
		{
			"label": "make",
			"type": "shell",
			"command": "make",
			"args": [
				
			],
			"group": {
				"kind": "test",
				"isDefault": true
			},
			"dependsOn": "gen",
			"options": {
				"cwd": "build"
			}
		},
		{
			"label": "run",
			"type": "shell",
			"command": "./build/infidungeon",
			"args": [
				
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"dependsOn": "make"
		}
	]
}
``` 

If I change my code, or otherwise sometimes completely randomly, when I run task `run`, I get this message:
![image](https://user-images.githubusercontent.com/31551546/80737329-56fe4300-8ae1-11ea-8446-77924abfb9df.png)
And when I hit, "Show output" I see:
```
The task provider for "C/C++" tasks unexpectedly provided a task of type "shell".
The task provider for "C/C++" tasks unexpectedly provided a task of type "shell".
```

Is something wrong with my `tasks.json`? I can't replicate this consistently? This does not happen when all extensions are disabled.

**Comment by taunusflieger** [comment]
Similar behavior here with ROS
```
The task provider for "catkin_cmake" tasks unexpectedly provided a task of type "catkin_make".
The task provider for "catkin_cmake_isolated" tasks unexpectedly provided a task of type "catkin_make_isolated".

```
This is there since one of the last Insider updates. My version
```
Version: 1.45.0-insider
Commit: ece7aaee861d7261a728d52ce436c667030ce17d
Date: 2020-05-01T09:46:11.716Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic
```

**Comment by dm17ryk** [comment]
reverting to 0.27.1 fix problem

**Comment by matteomandelli** [comment]
Same issue for me on macOS 

Version: 1.45.0-insider
Commit: fd5d9a30259bb2bebab3e62dfd8315c2e1b27744
Date: 2020-05-04T09:21:17.770Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by Kainichy** [comment]
Same issue on macOS.

macOS Catalina 10.15.5
Code Insiders 1.45.0
C/C++ 0.28.0-Insiders

**Comment by kunaldas1997** [comment]
facing a similar kind of issue on 0.28 Insiders version as well as 0.27.1 version. 

Edit: with all versions.

Version: 1.45.0-insider (user setup)
Commit: d4b8ec9da3bf1061a948fbb1b0d9d3db750cc79f
Date: 2020-05-05T07:13:50.890Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by ghost** [comment]
If I run task instead of build task, the issue will not appear.
And when I click "Show All Tasks" under drop-down list of normal run task, it shows again.

**Comment by Primimy** [comment]
Same issue for me.
Version: 1.45.0-insider (system setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
but it will not appear on vscode stable

**Comment by Ryu3tthz** [comment]
Same issue for me,

Version: 1.45.0-insider (system setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
C/C++ 0.28.0-insiders2

but it will not appear on my vscode stable.

Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
C/C++ 0.28.0-insiders2

**Comment by sean-mcmanus** [comment]
@Primimy If the bug occurs on 1.45-insiders but not 1.44.2 (both with 0.28.0-insiders2) then that suggests it's a VS Code bug and not a bug with out C/C++ extension.

**Comment by alexr00** [comment]
In this extension's call to `registerTaskProvider` it registers a `C\C++` task provider.
https://github.com/microsoft/vscode-cpptools/blob/ef120e83137799ba0438c283388b1647ab912445/Extension/src/LanguageServer/extension.ts#L174-L180
However, then it provides tasks of type `shell` not of type `C\C++`, which is unexpected. It used to work because VS Code was just blindly accepting all tasks. With the recent changes to the task quick pick to make it faster, it can't do that. I added this error message recently so that folks would notice this problem.

The quickest and most correct way for this extension to stop having this error would be to provide tasks of type `C\C++`. This will fix:
- The error in this bug
- Problems with these tasks showing in the "recent" section of the task picker that shows when you Run Task

That said, I'll make a small change to not show the notification in this case. Then, I'll see what can be done about the task not showing in the "recent" section.

**Comment by thomastech** [comment]
+1. 
After today's VSCode update, everytime I build with Platformio I see the "_There are task errors. See the output for details_"
After clicking the "Show Output" button it reports: _The task provider for "C/C++" tasks unexpectedly provided a task of type "shell"._
```
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

- Thomas

**Comment by linbo0518** [comment]
+1, same issue for macOS 10.14.4, after update VSCode to 1.45.0.

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z (14 hrs ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by ahomberger** [comment]
+1 Same issue on Windows 10 after update 1.45.0

Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by yin1999** [comment]
The same problem for me.

    version: 1.45.0 (user setup)
    commit: d69a79b73808559a91206d73d7717ff5f798f23c
    Date: 2020-05-07T16:18:48.860Z
    Electron: 7.2.4
    Chrome: 78.0.3904.130
    Node.js: 12.8.1
    V8: 7.8.279.23-electron.0
    OS: Windows_NT x64 10.0.18363

**Comment by aswinkrishna21** [comment]
+1 Same issue on Windows 10 after the new update

Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by br101** [comment]
Same here with the meson build extension

**Comment by wangenahs** [comment]
+1
![image](https://user-images.githubusercontent.com/39442168/81398256-75a4af80-915b-11ea-9eac-8264968864c5.png)

**Comment by sameer1994** [comment]
I see the same error on my Mac.

**Comment by olonsoft** [comment]
Same here!

**Comment by Tenshi65535** [comment]
![图片](https://user-images.githubusercontent.com/30772598/81402938-edc3a300-9164-11ea-9c32-c48b93731f50.png)
Same here.

**Comment by ahlixinjie** [comment]
> @Primimy If the bug occurs on 1.45-insiders but not 1.44.2 (both with 0.28.0-insiders2) then that suggests it's a VS Code bug and not a bug with out C/C++ extension.

Happens on 1.45 stable.

**Comment by ageprocpp** [comment]
I see the same error on MacOS too.

**Comment by alexr00** [comment]
If you try out the Insiders build of VS Code (version 1.46), you should no longer see a notification for this message.

**Comment by Gorgeous2017** [comment]
> If you try out the Insiders build of VS Code (version 1.46), you should no longer see a notification for this message.

When I disable C/C++ extension, this bug disappear. 
I hope this bug is fixed as soon as possible, it really make user confusing.

**Comment by ykuchin** [comment]
> If you try out the Insiders build of VS Code (version 1.46), you should no longer see a notification for this message.

When a fixed version will be deployed? 
Very annoying...

**Comment by andrew-r-king** [comment]
I saw this error when I had a trailing comma in my task.json at the end of the "presentation" block. Fixing it removed the popup each time I started a task, although it's clearly not a meaningful error notification.

**Comment by DProvinciani** [comment]
Same for me after updating to this version

Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by rewrking** [comment]
This error comes up every time I run a build task right now. Would appreciate a quick fix instead of waiting a month+ for 0.29.0.
 
1.45.0 w/ 0.28.0-insiders2

**Comment by space-orca** [comment]
Same issue since VS Code updated (yesterday?)

My info:
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Microsoft C/C++ version: 0.27.1

**Comment by astojanovic-tvz** [comment]
Same problem. Updated just now.

Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Bigous** [comment]
> In this extension's call to `registerTaskProvider` it registers a `C\C++` task provider.
> https://github.com/microsoft/vscode-cpptools/blob/ef120e83137799ba0438c283388b1647ab912445/Extension/src/LanguageServer/extension.ts#L174-L180
> 
> 
> However, then it provides tasks of type `shell` not of type `C\C++`, which is unexpected. It used to work because VS Code was just blindly accepting all tasks. With the recent changes to the task quick pick to make it faster, it can't do that. I added this error message recently so that folks would notice this problem.
> The quickest and most correct way for this extension to stop having this error would be to provide tasks of type `C\C++`. This will fix:
> 
> * The error in this bug
> * Problems with these tasks showing in the "recent" section of the task picker that shows when you Run Task
> 
> That said, I'll make a small change to not show the notification in this case. Then, I'll see what can be done about the task not showing in the "recent" section.

Did this and it solves the problem... at least stops the message and executes the tasks... I know it's not the best, but can we comment this lines for while?

**Comment by space-orca** [comment]
> > In this extension's call to `registerTaskProvider` it registers a `C\C++` task provider.
> 
> > https://github.com/microsoft/vscode-cpptools/blob/ef120e83137799ba0438c283388b1647ab912445/Extension/src/LanguageServer/extension.ts#L174-L180
> 
> > 
> 
> > 
> 
> > However, then it provides tasks of type `shell` not of type `C\C++`, which is unexpected. It used to work because VS Code was just blindly accepting all tasks. With the recent changes to the task quick pick to make it faster, it can't do that. I added this error message recently so that folks would notice this problem.
> 
> > The quickest and most correct way for this extension to stop having this error would be to provide tasks of type `C\C++`. This will fix:
> 
> > 
> 
> > * The error in this bug
> 
> > * Problems with these tasks showing in the "recent" section of the task picker that shows when you Run Task
> 
> > 
> 
> > That said, I'll make a small change to not show the notification in this case. Then, I'll see what can be done about the task not showing in the "recent" section.
> 
> 
> 
> Did this and it solves the problem... at least stops the message and executes the tasks... I know it's not the best, but can we comment this lines for while?

What exactly did you change? Did you change the tasks.json type from shell to something else? I thought type could only be shell or process?

**Comment by bobbrow** [comment]
> If you try out the Insiders build of VS Code (version 1.46), you should no longer see a notification for this message.

@alexr00 this is a very unfortunate predicament our customers have been put in.  The proposed fix doesn't work (we tried it before and it broke the feature).  We've been wanting to update how we do our tasks, but we can't turn on a dime and do that right before we're about to release.  Is there any way we can revert your change in the next stable patch to 1.45?  IMO, this should have been a `console.error` message since it's directed at extension developers, not the general public.

We're looking into other ways to solve this without rewriting the feature.  We'll keep this thread updated.

**Comment by sean-mcmanus** [comment]
@bobbrow @alexr00 Actually -- the fix does appear to work https://github.com/microsoft/vscode-cpptools/pull/5442 (I was hitting a failure due to another issue)...unless we find some other issue. We could ship this in our pending 0.28.0-insiders3 and/or 0.28.0 updates.

**Comment by bobbrow** [comment]
Yeah, I might have spoken too soon.  There are a number of other problems with our current task provider which we will work on for 0.29.0.  I think we'll try to release an insiders3 for people to try over the weekend and if it's good, then we'll get 0.28.0 out with a fix for this early next week.

**Comment by sean-mcmanus** [comment]
We have a fix with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders3 . We plan to release 0.28.0 on Monday (or maybe Tuesday).

**Comment by thomastech** [comment]
Thank you for the quick fix. Installed 0.28.0-insiders3. Issue resolved.
- Thomas

**Comment by Trafalgar99** [comment]
Good job,thank you.

**Comment by Gorgeous2017** [comment]
@sean-mcmanus

Nice.

But the terminal always displays the `Terminal will be reused by tasks, press any key to close it.` when tasks done.

Look like this:

![image](https://user-images.githubusercontent.com/33201519/81462281-09ba5980-91e4-11ea-9bb2-9ef671d96681.png)

I remember it didn’t appear before. It is a bug?

**Comment by imba-tjd** [comment]
@Gorgeous2017 It did appear before. It's basically similar to "press any key to continue"

**Comment by desaifa** [comment]
> +1 Same issue on Windows 10 after update 1.45.0
> 
> Version: 1.45.0 (user setup)
> Commit: d69a79b73808559a91206d73d7717ff5f798f23c
> Date: 2020-05-07T16:18:48.860Z
> Electron: 7.2.4
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.19041

**Comment by sky5454** [comment]
Actually, if you don't configure a right path for gdb, this error will occur.

**Comment by astojanovic-tvz** [comment]
What if I'm not using GDB? I use MS C++.

**Comment by muhammad-osaid-tekfocal** [comment]
For those having hard time figuring this out,

1. Open VS Code and Go to extensions, right click C/C++ then click Extension Settings
2. Scroll down to last and "C-Cpp: Update channel" will be  third last drop down list
3. Change from default to insiders. (this will be auto saved)
4. The downloading will start and will ask you to reload once completed AND you are done. :)
5. Try restarting VS code if step 4 does not asks you to reload. Be patient and pray for your internet speed till you see the reload message.

**Comment by lyq1996** [comment]
+1 Same problem here.

**Comment by astojanovic-tvz** [comment]
Thanks muhammad-osaid-tekfocal, it works like a charm! :)

**Comment by mangkoran** [comment]
is it okay to revert back to default update channel after updating?

**Comment by thomastech** [comment]
It's OK to revert back to the default Update Channel after installing the insiders release. The insider version will remain until a newer official release is available on the default Channel. 

- Thomas

**Comment by sean-mcmanus** [comment]
@ayams02 We had a bug that prevented auto-downgrading from 0.28.0-insiders3 to 0.27.1 when the updateChannel changes to "Default" (https://github.com/microsoft/vscode-cpptools/issues/5464), but that should be fixed for future Insider releases...and we should be releasing 0.28.0 soon anyway.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0 .

**Comment by thomastech** [comment]
Yoo-hoo! Platformio now reports it has 0.28.0 installed. @sean-mcmanus, Thank You.
- Thomas

**Comment by PogoRollo** [comment]
As of about an hour ago I have 0.28.0 installed and the issue is gone.
Thanks @ all the contributors!

**Comment by timeneverdie** [comment]
> Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0 .

The default template of launch.json and task.json may be not correct as before. I generate many times to get the fine version to debug like before. I don't why, but this is the truth. Wish you could find out the real problem which causes this error. Thanks.
