### ISSUE TITLE
Find All References confirms references for different file-local objects with different types

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5389]
In test1.cpp use
```
#include <map>
namespace {
	std::map<int, int> mm;
}
```
In test2.cpp use
```
#include <map>
#include <string>
namespace
{
	std::map<
		std::string, std::pair<std::string, std::map<std::string, std::map<std::string, std::map<std::string, std::pair<std::string, std::map<std::string, std::map<std::string, std::map<std::string, int>>>>>>>>
	> mm;
}
```
Do Find All References or Rename on “mm”.

Bug: It returns 2 confirmed references, even though the objects are both local to their respective files with different templated types.

Reported to VS at https://developercommunity.visualstudio.com/content/problem/1014321/c-intellisense-find-all-references-confirms-refere.html

**Comment by bobbrow** [comment]
The VS ticket was closed as "lower priority" which means that we won't be getting a fix for this issue.
