### ISSUE TITLE
Debugger switches threads too frequently

### ISSUE THREAD

**Issue by jduo** [microsoft/vscode-cpptools#539]
I have a Node.js application which loads a C shared object. If I put breakpoints in the shared object, the debugger can trigger the breakpoint on any thread. But every time I step, it switches back to thread 1, making it very difficult to follow through the workflow.

Using lldb directly does not do this.

**Comment by pieandcakes** [comment]
@jduo Can you give me an example app and a set of steps to repro this? Also please let me know which OS Version you are running into this on?

**Comment by sean-mcmanus** [comment]
This might be what I experienced when stepping with our extension process. The bug doesn't repro all the time though so I don't know if still have a repro.

**Comment by pieandcakes** [comment]
This is fixed in vscode and will be available in October Stable release or is in current Insiders build.
