### ISSUE TITLE
`Formatting failed` see debug window for details - but debug window is empty

### ISSUE THREAD

**Issue by GirkovArpa** [microsoft/vscode-cpptools#5391]
Using latest version of everything, Windows 10 64bit, how to get the formatter to work?

**Comment by sean-mcmanus** [comment]
I got a repro. Investigating...

**Comment by sean-mcmanus** [comment]
Oh, my C_Cpp.clang_format_path was incorrect. What is your clang_format_path setting? You can see more logging in the "C++" output window (you may need to C_Cpp.loggingLevel to "Debug").

**Comment by GirkovArpa** [comment]
It's empty, what should I put?  And shouldn't it determine it's own path automagically when I install it?

[![Image from Gyazo](https://i.gyazo.com/dca176ed208902f5c72998e079b96bac.png)](https://gyazo.com/dca176ed208902f5c72998e079b96bac)

**EDIT:** Nevermind, I need to find `clang.exe` I suppose.

**Comment by GirkovArpa** [comment]
I put `C:\Program Files\LLVM\bin\clang.exe` and I don't get any errors when clicking `Format Document`, but nothing happens.  It doesn't format.

**Comment by GirkovArpa** [comment]
I even turned on debug but I still get no information when I try to format:

[![Image from Gyazo](https://i.gyazo.com/a9f52fb8ece1eaa099b33e14f0d07bab.png)](https://gyazo.com/a9f52fb8ece1eaa099b33e14f0d07bab)

[![Image from Gyazo](https://i.gyazo.com/ece9f1c664f9f155dca477271513ab23.png)](https://gyazo.com/ece9f1c664f9f155dca477271513ab23)

**Comment by GirkovArpa** [comment]
I thought surely this would work:

[![Image from Gyazo](https://i.gyazo.com/9ebcd3daadaf05a774a5d6698d761f1e.png)](https://gyazo.com/9ebcd3daadaf05a774a5d6698d761f1e)

But no:

[![Image from Gyazo](https://i.gyazo.com/356ffcc018c6afa843fc49afb16e9d88.png)](https://gyazo.com/356ffcc018c6afa843fc49afb16e9d88)

**Comment by sean-mcmanus** [comment]
Yeah, when it's blank, it's supposed to use our installed clang-format or the one found on your PATH.

You need to select the "C/C++" pane to see that output. Your screenshot shows "Tasks" selected.

**Comment by GirkovArpa** [comment]
I had invalid values in the following boxes (screenshot taken after I fixed them though), and now it works:

[![Image from Gyazo](https://i.gyazo.com/0eb466a0dfc1e948ab62724e138c9ac4.png)](https://gyazo.com/0eb466a0dfc1e948ab62724e138c9ac4)
