### ISSUE TITLE
High CPU in WSL

### ISSUE THREAD

**Issue by dingqunfei** [microsoft/vscode-cpptools#5397]
I am coding c++  in WSL. But the cpu occupation of my computer is very high to 28%.
My windows version is windows 10 pro 1909,  the cpu of pc is 4c8t and the WSL is ubuntu20.04.
![微信图片编辑_20200502005044](https://user-images.githubusercontent.com/11921211/80823381-1f8db480-8c0f-11ea-8b56-16275277126b.jpg)
![微信图片编辑_20200502005121](https://user-images.githubusercontent.com/11921211/80823386-21f00e80-8c0f-11ea-8d1b-7119326bfe27.jpg)

The program of high cpu occupation is named "node" . The path is 
"C:\Users\...\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\dqflying\.vscode-server\bin\ff915844119ce9485abfe8aa9076ec76b5300ddd\node"

**Comment by sean-mcmanus** [comment]
That process is part of VS Code. Does this issue repro if you disable the C/C++ extension? What do you do to cause the CPU usage? Does it repro with only certain projects? Is there a flame or database icon in the status bar?

**Comment by dingqunfei** [comment]
I disabled the extension one by one. When Remote-WSL extension is disabled, the CPU usage is low. Does this extension cause high occupation? I just code or debug in VSCode by WSL, and the Remote-WSL helps me to use gcc/gdb in WSL. By the way,  this is no database icon or flame in the status bar.

**Comment by sean-mcmanus** [comment]
I have not seen the Remote WSL extension use high CPU. You might try filing an issue at https://github.com/Microsoft/vscode-remote-release/issues .

**Comment by dingqunfei** [comment]
I reported at https://github.com/microsoft/vscode-remote-release/issues/2921
