### ISSUE TITLE
Extension finds no symbols

### ISSUE THREAD

**Issue by radubacaran** [microsoft/vscode-cpptools#54]
I tried the latest variant (version in pic below) on a windows 7 machine, but regardless of what .c file I open, no symbols are shown. 
The same software works fine on my home pc,

I tried reinstalling a couple of times, reinstalling VS code, the Insider variant of vs code, and removing all extensions except for cpptools. 

![version](https://cloud.githubusercontent.com/assets/4575596/15572753/30092b90-234b-11e6-8e35-e943cd235afd.png)
![ext](https://cloud.githubusercontent.com/assets/4575596/15572766/4495f7b4-234b-11e6-89c7-4f8f817d712d.png)
![ext_not_working](https://cloud.githubusercontent.com/assets/4575596/15572745/198ab19a-234b-11e6-9452-64465ac5022b.jpg)

**Comment by delmyers** [comment]
@sridmad, is this fixed with the latest update?

**Comment by radubacaran** [comment]
Still happens with 0.6.0

**Comment by worms** [comment]
Still broken in 0.6.1 as well

**Comment by sridmad** [comment]
There is a bug when a file is opened as opposed to a folder. Something we will investigate soon

**Comment by jgoshi** [comment]
This is fixed and will appear in the next release, version 0.8.0
