### ISSUE TITLE
`Connection is closed` after 5 or 6 minutes 

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#540]
after the latest update the extension close automatically after like 5 or 6 minutes, i then have to reload vscode to get it to work again here is the log
[log.txt](https://github.com/Microsoft/vscode-cpptools/files/827290/log.txt)

**Comment by sean-mcmanus** [comment]
The log shows you're editing/saving on Linux and then our extension process dies. If you just open a workspace and don't do other actions and let the Microsoft.VSCode.CPP.Extension.linux process run, does it fail still? What does the memory/CPU usage of the process look like before/after it stops working? If you could narrow down the actions you do to the smallest possible set that would help find a repro/cause. Does the failure happen after the green squiggle on missing #includes says "Searching..." or "Include not found" and is the bottom Linux config still red? What is the size of your .browse.vc.db? under ~/.config/Code/User/workspaceStorage ? Does the bug still repro if you add these to your files.exclude settings: `"**/*.mm": true, "**/*.ino": true, "**/*.inl": true`? We're about to ship a 0.10.3 update that fixes some known instability issues.

**Comment by sean-mcmanus** [comment]
I hit a repro with 0.10.2, but I'm not sure if it's the same as yours. The CPU usage went to 0%, the Linux config got stuck red, and it was during the parsing phase (missing #include says "Include not found"). This indicates a failure occurred while parsing and the main thread is not responding. The good news is the bug is fixed with 0.10.3 (out today). So if the bug still repros, then you're hitting a different bug.

**Comment by ghost** [comment]
almost every time this happened i get this warning first
`[Extension Host] rejected promise not handled within 1 second`
then this errors
[log.txt](https://github.com/Microsoft/vscode-cpptools/files/829990/log.txt)
and i get more then one `.browse.vc.db` the biggest is 16MB,
the extension was fully working right before the crash

**Comment by sean-mcmanus** [comment]
Can you try 0.10.3 and see if it still repros?

**Comment by bobbrow** [comment]
In the log, I see:
```
Error: ENOENT: no such file or directory, open '/home/devel/.vscode/extensions/basdp.language-gas-x86-0.0.1/language-configuration.json'(…)
```
This looks like an issue with the gas extension, not the C++ extension.  Try disabling or reinstalling that extension and see if it helps.
