### ISSUE TITLE
Ignore include errors

### ISSUE THREAD

**Issue by aaronovz1** [microsoft/vscode-cpptools#5402]
How do you configure the extension to ignore the "#include errors detected" messages? I have files which are auto generated and won't be available in the workspace. This is causing a lot of spam and masking finding real issues from Flylint, etc.

**Comment by sean-mcmanus** [comment]
You can set C_Cpp.errorSquiggles to "Disabled", although that will disable all squiggles. You could also try adding the path to the generated files to your includePath.

**Comment by aaronovz1** [comment]
includePath isn't really an option as the workspace is kind of complicated. I'd rather just be able to disable this type of warning/error.

**Comment by sean-mcmanus** [comment]
So disable the missing include error, but show other errors still? Sounds similar to https://github.com/microsoft/vscode-cpptools/issues/1231 ...maybe another issue too.

**Comment by aaronovz1** [comment]
Yep that would be ideal. For now I've Disabled errorSquiggles to reduce the noise, but I am still seeing:
`Include file not found in browse.path.`

Shouldn't this check be disabled as well?

**Comment by sean-mcmanus** [comment]
Ah, there's no setting to get rid of that currently. We've had previous requests for this (not sure what issue number).

If this VS Code issue were fixed (https://github.com/microsoft/vscode/issues/51103) you could filter out all problems from our extension.

You could also set C_Cpp.intelliSenseEngine to "Disabled", which will disable all language features.

**Comment by aaronovz1** [comment]
What does `intelliSenseEngine` control? Does disabling that essentially turn off the entire extension? I still want intellisense and autocomplete features.

**Comment by sean-mcmanus** [comment]
@aaronovz1 Yeah, it would disable all IntelliSense, autocomplete, etc....everything except the debugger.

**Comment by bobbrow** [comment]
You don't want to disable all of  IntelliSense just to disable a squiggle.  I'm actually not able to reproduce this problem.  `"C_Cpp.errorSquiggles": "Disabled"` should be hiding all squiggles when the default IntelliSense is enabled.

That one you are reporting makes it sound like you're using the "Tag Parser" IntelliSense or something.  What is your setting for `C_Cpp.intelliSenseEngine` and `C_Cpp.intelliSenseEngineFallback`?

**Comment by sean-mcmanus** [comment]
@bobbrow Yeah, you're right. errorSquiggles "Disabled" with intelliSenseEngine "Default" doesn't show the include error message, but it does with intelliSenseEngine "Tag Parser" (with 0.28.0). I do see the message appear briefly, but then it disappears when the squiggle update finishes -- it's possible if the squiggle update fails (i.e. from an IntelliSense process crash) then the bug might repro.

**Comment by aaronovz1** [comment]
I had to turn the "Intellisense Engine Fallback" to Disabled and this looks to have removed the remaining warnings. Output is looking good now while using the C/C++ Advanced Lint + cppcheck as the replacement.
