### ISSUE TITLE
vscode could not resolve symbol for defined for

### ISSUE THREAD

**Issue by q2683252** [microsoft/vscode-cpptools#5404]
When I am using vscode for Postgres code. Some symbols are not found. because for_echo is a for loop which is a macro . After removing it, Everything goes back to normal.
![企业微信20200503110357](https://user-images.githubusercontent.com/13419047/80897706-50184000-8d2e-11ea-9d44-851fb9e8683e.png)
![企业微信20200503110444](https://user-images.githubusercontent.com/13419047/80897707-527a9a00-8d2e-11ea-810e-7806e033a1a5.png)
![企业微信20200503110518](https://user-images.githubusercontent.com/13419047/80897708-53abc700-8d2e-11ea-9b6b-032d0cd15381.png)
![企业微信20200503110806](https://user-images.githubusercontent.com/13419047/80897712-64f4d380-8d2e-11ea-84fe-63fdb45155fa.png)

**Comment by sean-mcmanus** [comment]
See https://github.com/microsoft/vscode-cpptools/issues/5200#issuecomment-604721202
