### ISSUE TITLE
Language Service

### ISSUE THREAD

**Issue by Answer-123** [microsoft/vscode-cpptools#5409]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
What?

**Comment by michelleangela** [comment]
I think this issue was created by a bot.

**Comment by sean-mcmanus** [comment]
That's a strange bot.

**Comment by Answer-123** [comment]
> I think this issue was created by a bot.

Hey, I’m not a bot

**Comment by sean-mcmanus** [comment]
@Answer-123 Can you create a new issue with more info then? This issue is blank.
