### ISSUE TITLE
Possible 0.27 regression

### ISSUE THREAD

**Issue by maxim-babenko** [microsoft/vscode-cpptools#5410]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS Catalina
- VS Code Version: 1.44.2
- C/C++ Extension Version: 0.27.1
- Other extensions you installed (and if the issue persists after disabling them): Remote SSH 0.51.0
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

After updating C++ extension from 0.26.3 to 0.27.1 I started getting autocompletion issues in certain large C++ files (slow response, lack of completion suggestions). Reverting back to 0.26.3 fixes the issue.

I have enabled the language server logging and suspect the problem is related to "Compiler exited with error - No IL available" error diagnostics. The full log can be viewed here:

https://gist.github.com/maxim-babenko/7f3f785391e3590f59be35e8692c40de

Please advise on further steps to help in diagnosing the problem.

Thanks!

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Can you try https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders2 ? It may have a fix (as in, we did a fix issues that could cause the symptom you're seeing).

**Comment by Answer-123** [comment]
> Can you try https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.0-insiders2 ? It may have a fix (as in, we did a fix issues that could cause the symptom you're seeing).

OK,thanks

**Comment by maxim-babenko** [comment]
I tried 0.28.0 but unfortunately it didn't help.

Here are the logfiles of 0.28.0 (no suggestions) and 0.26.3 (working intellisense):
https://gist.github.com/maxim-babenko/d4d42d406b7efb3292a31d5ddf0622c3
https://gist.github.com/maxim-babenko/c1b4737aa4dfa0b51345a979f5fb6ddf

Is there anything else I could do to ease the diagnostics?

**Comment by maxim-babenko** [comment]
There are multiple "Tag parsing encountered an error" in 0.28.0 log (not present in 0.26.3 one)

**Comment by sean-mcmanus** [comment]
The logging appears normal for 0.28.0. I don't see any crashes or unusual errors. The "tag parser encountered an error" message is somewhat normal and wouldn't cause any issue with IntelliSense-based completion from working. Are you saying you still get 
```
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
using Tag Parser for quick info
```
when hovering?

**Comment by sean-mcmanus** [comment]
The logging appears normal for 0.28.0. I don't see any crashes or unusual errors. The "tag parser encountered an error" message is somewhat normal and wouldn't cause any issue with IntelliSense-based completion from working. Are you saying you still get 
```Quick info operation failed: FE: 'Compiler exited with error - No IL available'
using Tag Parser for quick info```
when hovering?

**Comment by maxim-babenko** [comment]
No, I don't see "Compiler exited with error - No IL available" in the logs anymore. At the same time, completion is not working for me in 0.28.0, it just says "No suggestions". And it starts working back again when I revert to 0.26.3.

**Comment by sean-mcmanus** [comment]
Okay, it's most likely an IntelliSense parser regression. I assume it only repros with certain TU's right? We'd probably need some code sample repro in order to get a fix (i.e. if you're able to isolate what code you're using that is triggering the issue).

**Comment by sean-mcmanus** [comment]
Within the past hour, an autocomplete bug was just fixed (in the VS shared code) that could cause the "No suggestions", but I can't tell if it's the same issue you're hitting or not (we'll get that fix for 0.29.0-insiders).

**Comment by maxim-babenko** [comment]
OK, thanks! I will wait until 0.29.0 becomes available and will let you know if the update helps.

**Comment by maxim-babenko** [comment]
The issue is no longer reproducible in 0.28.2
