### ISSUE TITLE
Hello World For Learners

### ISSUE THREAD

**Issue by Answer-123** [microsoft/vscode-cpptools#5411]

**Comment by Answer-123** [comment]
Let's start with a function called “scanf”

**Comment by Answer-123** [comment]
Hello World

**Comment by WardenGnaw** [comment]
You can find our Hello World tutorials at [Visual Studio Code docs](https://code.visualstudio.com/docs/languages/cpp#_hello-world-tutorials)

**Comment by Answer-123** [comment]
> You can find our Hello World tutorials at [Visual Studio Code docs](https://code.visualstudio.com/docs/languages/cpp#_hello-world-tutorials)

I’m about to start it onPC
