### ISSUE TITLE
invalid operands to binary expression ('std::ostream' (aka 'int') and 'const char [2]')ccls(2)

### ISSUE THREAD

**Issue by joseph102outlaw102** [microsoft/vscode-cpptools#5416]
**Type: LanguageService**

**Describe the bug**
- OS and Version:  i use vscode remote development on my personal pc which is a win10, when the cloud dev machine(the project runtime environment) has a centos system.
-- my pc: win10
-- dev machine: Linux VM_110_148_centos
- VS Code Version:  1.44.2
- C/C++ Extension Version: 0.27.1
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: 
yes, it does. 
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
just like the operations in this docs https://code.visualstudio.com/docs/cpp/config-linux, i learn to 
mkdir a helloworld, and write a testhello.cpp. Whereas, there is always has a code-check warning below the symbol <<(the last <<, actually), when i hover my cursor on this symbol, it displays 

`std::__1::ostream &std::__1::operator<<<...>(std::__1::ostream &__os, const char *__str)
+18 overloads
invalid operands to binary expression ('std::ostream' (aka 'int') and 'const char [2]')ccls(2)`

then i click alt+f8, it show me

`base specifier must name a classccls(2)`
`stl_vector.h(164, 20): in instantiation of member class 'std::_Vector_base<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Vector_impl' requested here`
`stl_vector.h(210, 30): in instantiation of template class 'std::_Vector_base<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >' requested here`
`testhello.cpp(9, 20): in instantiation of template class 'std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >' requested here
`

**Steps to reproduce**

1. use the ssh func to connect the remote dec machine
2. create this helloworld project
3. paste these code in the following blank
![企业微信截图_15887513767616](https://user-images.githubusercontent.com/33682853/81149721-566a1e80-8fb1-11ea-9d85-266b2583259b.png)

4. it show me these code-check warning

but the strange thing is, this project still can be compiled and builded without any error.(it just a single cpp file, no multiple.)

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by Answer-123** [comment]
Awesome😍😍

**Comment by Answer-123** [comment]
∴you’re Chinese right?

**Comment by joseph102outlaw102** [comment]
> ∴you’re Chinese right?

yes, i am

**Comment by Answer-123** [comment]
> > ∴you’re Chinese right?
> 
> yes, i am

Are you interested in Cpp

**Comment by Answer-123** [comment]
> ∴you’re Chinese right?

所以说怎么把VScode设成中文的？

**Comment by sean-mcmanus** [comment]
@joseph102outlaw102 Those errors are not from our C/C++ extension. They appear to be from some ccls(2) extension?

Also, we don't know why @Answer-123 is posting strange messages.

**Comment by Answer-123** [comment]
> @joseph102outlaw102 Those errors are not from our C/C++ extension. They appear to be from some ccls(2) extension?
> 
> Also, we don't know why @Answer-123 is posting strange messages.

Use Dev-cpp and this error won’t be happening

**Comment by joseph102outlaw102** [comment]
> @joseph102outlaw102 Those errors are not from our C/C++ extension. They appear to be from some ccls(2) extension?
> Also, we don't know why @Answer-123 is posting strange messages.

**Comment by joseph102outlaw102** [comment]
> @joseph102outlaw102 Those errors are not from our C/C++ extension. They appear to be from some ccls(2) extension?
> Also, we don't know why @Answer-123 is posting strange messages.

you're right, i've solved this problem now, thank you very much.

**Comment by joseph102outlaw102** [comment]
> @joseph102outlaw102 Those errors are not from our C/C++ extension. They appear to be from some ccls(2) extension?
> Also, we don't know why @Answer-123 is posting strange messages.
> 
> Use Dev-cpp and this error won’t be happening

what's dev-cpp? is it a mode in vscode?

**Comment by Answer-123** [comment]
> > @joseph102outlaw102 Those errors are not from our C/C++ extension. They appear to be from some ccls(2) extension?
> 
> > Also, we don't know why @Answer-123 is posting strange messages.
> 
> > 
> 
> > Use Dev-cpp and this error won’t be happening
> 
> 
> 
> what's dev-cpp? is it a mode in vscode?

No, but it’s a better compiler.It uses GCC
