### ISSUE TITLE
mingw32/bin/ld.exe Cannot open output file

### ISSUE THREAD

**Issue by shriya-16** [microsoft/vscode-cpptools#5417]
After compiling the programs, the terminal says cannot open output file. 
OS : Windows 10
Compiler : mingw

**Comment by michelleangela** [comment]
@shriya-16 

Can you share your tasks.json and launch.json?

**Comment by shriya-16** [comment]
Please excuse for the delay.
Tasks.json
`{

    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\MinGW\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\MinGW\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "type": "shell",
            "label": "g++.exe build active file",
            "command": "C:\\MinGW\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\MinGW\\bin"
            }
        }
    ]
}`



launch.json
`{
 
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++.exe build active file"
        }
    ]
}`

**Comment by bobbrow** [comment]
I think the problem is that you need to add `c:\mingw\bin` to the `environment` in your launch.json.  Binaries built with MinGW take some dependencies on the dlls in that folder, if I recall correctly.

**Comment by elahehrashedi** [comment]
it looks like you have removed the type of the task's group from the definition. Change the definition to this and it should be working:

```
{
        "type": "shell",
        "label": "g++.exe build active file",
        "command": "C:\\MinGW\\bin\\g++.exe",
        "args": [
            "-g",
            "${file}",
            "-o",
            "${fileDirname}\\${fileBasenameNoExtension}.exe"
        ],
        "options": {
            "cwd": "C:\\MinGW\\bin"
        },
        "group":  "build"
    }
```

the definition of your first task is correct, but you are launching the second task in launch.json:

`"preLaunchTask": "g++.exe build active file"`
