### ISSUE TITLE
Show function documentation for C/C++ function with Intellisense 

### ISSUE THREAD

**Issue by josesimoes** [microsoft/vscode-cpptools#542]
Would like to know if Intellisense (auto-completion and hover) is supposed to show documentation for the specified function or variable. Similar to what Visual Studio shows.
If yes, what is the proper format of the comments to show that on VS Code Intellisense?
If not, please consider this as a suggestion for a future enhancement.

**Comment by bobbrow** [comment]
We don't show documentation yet.  It is on our backlog and is tracked by #399
Thank you for the feedback.

**Comment by sean-mcmanus** [comment]
Docs comments should work now with our latest Insiders release: https://github.com/Microsoft/vscode-cpptools/releases . If you're using VS Code Insiders or have http.proxySupport not set to "off", you might not get the 0.21.0-insiders2 update automatically with C_Cpp.updateChannel set to "Insiders".

**Comment by ntindle** [comment]
Is there a way to check this? Can we add an example?

**Comment by sean-mcmanus** [comment]
@ntindle I don't understand your comment. What do you want to check? An example of what? See the screenshot:

![image](https://user-images.githubusercontent.com/19859882/55774126-c0c82c80-5a48-11e9-9bdd-402be043f610.png)

**Comment by ntindle** [comment]
Perfect thanks. I think I have something configured wrong because mine isn't working.

**Comment by Shapeno** [comment]
I notice that if i use @brief in the comment block then it show the comment behind it. I think thats a good Function. But it dosent work in .cpp files. I dont kown if there is an option I didnt notice. Will it add more customized options?

**Comment by sean-mcmanus** [comment]
@Shapeno I don't understand what you are seeing. Can you give more info or a screenshot?

**Comment by mike2003** [comment]
How to fill in correctly so that service words are not visible?
![2020-02-11_01-30-12](https://user-images.githubusercontent.com/11754198/74196234-d9f3c800-4c6d-11ea-8a82-cd8702aa2ec9.jpg)

**Comment by sean-mcmanus** [comment]
@mike2003 We're tracking that with https://github.com/microsoft/vscode-cpptools/issues/658 .

**Comment by BullShark** [comment]
So did I download the wrong software? I don't usually develope something for Windows unless it's cross platform like Java.

I have VSCodium, but it was seriously lacking features. Then somebody told me that it's only an editor with syntax highlighting, and that was it. They said I needed Visual Studio Coder? I want documentation for function calls/api calls, etc. inside the code editor.

**Comment by sean-mcmanus** [comment]
@BullShark You should download Visual Studio Code and the C/C++ extension.
