### ISSUE TITLE
Unable use launch config from workspace config when it contains variable references to 'config'

### ISSUE THREAD

**Issue by nsgundy** [microsoft/vscode-cpptools#5421]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 19.10
- VS Code Version: 1.44.2
- C/C++ Extension Version: 0.28.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them):
* kristjantammekivi.hg
* jhartell.vscode-line-endings
When using a launch configuration configured within a `.code-workspace` file, variable references to the configuration do not work.
```json
{
	"folders": [
		{
			"name": "NeptuneApp",
			"path": "."
		}
	],
	"launch": {
		"configurations": [
			{
				"name": "Remote debug",
				"type": "cppdbg",
				"request": "launch",
				"program": "${workspaceFolder:App}/App",
				"stopAtEntry": false,
				"cwd": "${workspaceFolder:App}",
				"environment": [],
				"externalConsole": false,
				"MIMode": "gdb",
				"miDebuggerServerAddress": "${config:targetIp}:9091",
				"miDebuggerPath": "${config:linaroToolchain}/arm-linux-gnueabihf-gdb",
				"setupCommands": [
					{
						"description": "Enable pretty-printing for gdb",
						"text": "-enable-pretty-printing",
						"ignoreFailures": true
					}
				],
				"internalConsoleOptions": "neverOpen",
				"preLaunchTask": "NeptuneAppDebug"
			}
		]
	}
}
```
The settings `targetIp` and `linaroToolchain` are set in the users settings, their content is irrelevant. What I end up getting when trying to launch that configuration is the following:
`'${config:targetIp}' can not be resolved in a multi folder workspace. Scope this variable using ':' and a workspace folder name.

The same launch configuration configured inside `launch.json` works fine.

**Comment by WardenGnaw** [comment]
These variables are resolved by VS Code before they call `resolveDebugConfiguration`. 

However, this could be that we do not launch debug configurations with `resolveDebugConfigurationWithSubstitutedVariables`. 

But if this works in regular `launch.json` but not `.code-workspace`, there may be a bug when they pass the `.code-workspace` config. You will want to create an issue at https://github.com/microsoft/vscode/issues

**Comment by nsgundy** [comment]
If I try out a similar remote debugging setup for node (using the same `${config:targetIp}` variable), it works fine when configured within a `.code-workspace` workspace configuration.

**Comment by nsgundy** [comment]
Actually, my previous comment is not correct. I tried it in a workspace that only had a single folder inside. I do get the same issue once that workspace contains more than one folder.
