### ISSUE TITLE
Question about Settings at folder level.

### ISSUE THREAD

**Issue by bradlitterell** [microsoft/vscode-cpptools#5426]
Type: General

I have reviewed the settings documentation here:  https://code.visualstudio.com/docs/languages/cpp

The documentation states: "These settings have all of the benefits of VS Code settings, meaning that they can have default, "User", "Workspace", and "Folder" values."

However, searching the VS Code documentation does not make it obvious how to set Folder settings.
https://code.visualstudio.com/docs/getstarted/settings

It seems I can only set folder settings at the root of my workspace.  Or, more precisely, I have to add every folder under my workspace as a new workspace folder in order to create a "Multi-Root" workspace, in order to specify settings for that folder.

So, for example, I have something like this:

top/L1/L1.1/L1.1.1
top/L1/L1.1/L1.1.2
...
top/L1/L1.5/...
top/L2/L2.1/L2.1.1
...
top/L2/L2.1/L2.1.100
etc.

It appears that in order to customize includes for the leaf folders I need to add each one individually to the workspace as a new Root folder.  That is large number and sort of ruins the context of the treeview.

Is this the only way to create "Folder" settings?  or can I create c_cpp_properties.json files in the leaf folders (or leaf/.vscode folder)?

Thanks!

**Comment by sean-mcmanus** [comment]
Workspace folder settings are set in the .vscode/settings.json files in the particular workspace folder, and each workspace folder can have a .vscode/c_cpp_properties.json. They have to be actual workspace folders in a workspace and not just normal folders with a single root.

Other solutions for per-folder/per-file c_cpp_propertie.json settings would be to set the compileCommands or configurationProvider settings (with another extension that implements the vscode-cpptools-api, such as the CMake Tools extension).
