### ISSUE TITLE
vscode freezes for a few seconds when I put my cursor over a variable

### ISSUE THREAD

**Issue by GitHimanshuc** [microsoft/vscode-cpptools#5427]
Issue Type: <b>Performance Issue</b>

This happens only for this particular variable ("value") for now. Process explorer shows that the extension is consuming 25% of the CPU and vscode just freezes.
![Screenshot from 2020-05-07 10-39-51](https://user-images.githubusercontent.com/37404148/81256860-5d476e80-904f-11ea-9a68-ba2300dc68ba.png)

Extension version: 0.27.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (1.78GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   143	  3164	code main
    0	    32	  3166	   zygote
    0	   175	  3201	   gpu-process
    0	    64	  3215	   utility
    0	   111	  3350	   shared-process
    0	     0	  7317	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  7318	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    96	  7135	   window (Issue Reporter)
    0	     0	  7298	   /bin/sh -c "/usr/share/code/resources/app/out/vs/base/node/cpuUsage.sh" 3164 3166 3201 3215 3350 7135 7296 22269 7297 22304 22320 22353 22402 22414 25159
    0	     0	  7299	     /bin/bash /usr/share/code/resources/app/out/vs/base/node/cpuUsage.sh 3164 3166 3201 3215 3350 7135 7296 22269 7297 22304 22320 22353 22402 22414 25159
    0	     0	  7314	       sleep 1
    0	   287	 22269	   window (FEM1.h - CA1_template - Visual Studio Code)
    0	   191	 22304	     extensionHost
    0	    64	 22402	       electron_node server.js 
    0	   287	 22414	       /home/himanshu/.vscode/extensions/ms-vscode.cpptools-0.27.1/bin/cpptools
    0	    48	 25159	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=22304
    0	    64	 22320	     watcherService
    0	    64	 22353	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (FEM1.h - CA1_template - Visual Studio Code)
|    Folder (CA1_template): 115 files
|      File types: cmake(23) make(20) json(14) vtk(7) txt(5) internal(3) h(2)
|                  bin(2) out(2) gitignore(1)
|      Conf files: cmake(23) settings.json(1) makefile(1);
```

</details>

**Comment by Colengms** [comment]
Hi @GitHimanshuc .  Could you enable logging using `"C_Cpp.loggingLevel": "Debug"` and checking if there is output in the C/C++ output channel leading up to and/or during the issue?

It shouldn't be possible for our native processes to block the VS Code UI.  There is no synchronous dependency between those components.  I have recently seen a VS Code freeze due to an issue with the Better C++ Syntax extension - you might want to try disabling that if you're using it to see if the issue still repros.

High CPU activity is normal for the C++ extension native processes when parsing all include files, or building TU's for complex sources.  But, a lock up in the VS Code UI would seem to be related to (JavaScript) code running in the VS Code process.  If our extension is involved, there might be clues in the C/C++ output with logging enabled.

**Comment by GitHimanshuc** [comment]
@Colengms Here is the output I get when I hover over the variable 'value' in my file.
The only difference, when compared to hovering over some other variable or function name, is the line that says requests canceled.


cpptools/activeDocumentChange: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
textDocument/hover: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 9)
using Tag Parser for quick info
Request canceled: 9
textDocument/hover: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 10)
using Tag Parser for quick info

**Comment by GitHimanshuc** [comment]
Maybe this should be a new issue but I am posting it here in case it is related to the original problem.
![Screenshot from 2020-05-08 22-43-29](https://user-images.githubusercontent.com/37404148/81430672-72bab680-917d-11ea-8ad2-38fb82261ddb.png)

There is a comma instead of a semicolon in the for loop and the continue statement has no semicolon at all. But neither of these things gives an error.

___
### Debug output 
___
textDocument/hover: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 52)
using Tag Parser for quick info
textDocument/hover: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 53)
using Tag Parser for quick info
textDocument/hover: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 54)
using Tag Parser for quick info
textDocument/didChange: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
cpptools/getCodeActions: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 55)
cpptools/getDocumentSymbols: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 56)
cpptools/getDocumentSymbols
  tag parsing file: /home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h
textDocument/didChange: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 57)
cpptools/getCodeActions: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 58)
textDocument/formatting: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 59)
Formatting input:
/*This is a template file for use with 1D finite elements.
  The portions of the code you need to fill in are marked with the comment "//EDIT".

  Do not change the name of any existing functions, but feel free
  to create additional functions, variables, and constants.
  It uses the deal.II FEM library.*/

//Include files
//Data structures and solvers
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/function.h>
#include <deal.II/base/logstream.h>
#include <deal.II/base/tensor_function.h>
#include <deal.II/lac/vector.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/sparse_matrix.h>
#include <deal.II/lac/sparse_direct.h>
#include <deal.II/numerics/vector_tools.h>
#include <deal.II/numerics/matrix_tools.h>
#include <deal.II/numerics/data_out.h>
//Mesh related classes
#include <deal.II/grid/tria.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>
#include <deal.II/grid/tria_boundary_lib.h>
#include <deal.II/gr...
Formatting document: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h
Formatting raw output:
/*This is a template file for use with 1D finite elements.
  The portions of the code you need to fill in are marked with the comment "//EDIT".

  Do not change the name of any existing functions, but feel free
  to create additional functions, variables, and constants.
  It uses the deal.II FEM library.*/

//Include files
//Data structures and solvers
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/function.h>
#include <deal.II/base/logstream.h>
#include <deal.II/base/tensor_function.h>
#include <deal.II/lac/vector.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/sparse_matrix.h>
#include <deal.II/lac/sparse_direct.h>
#include <deal.II/numerics/vector_tools.h>
#include <deal.II/numerics/matrix_tools.h>
#include <deal.II/numerics/data_out.h>
//Mesh related classes
#include <deal.II/grid/tria.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>
#include <deal.II/grid/tria_boundary_lib.h>
#include <deal.II/gr...
terminating child process: 9534
cpptools/fileChanged: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h
textDocument/didSave: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h
  tag parsing file: /home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h
idle loop: reparsing the active document
cpptools/getDocumentSymbols
Database safe to open
textDocument/hover: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 61)
using Tag Parser for quick info
textDocument/hover: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 62)
using Tag Parser for quick info
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///home/himanshu/Desktop/learning/courses/finite_element_for_physicist/CA1_template/FEM1.h (id: 63)
idle loop: reparsing the active document

**Comment by sean-mcmanus** [comment]
Yes, that code is supposed to give a squiggle error. It appears that your IntelliSense is being disabled for some reason -- that's why your logging shows "using Tag Parser for quick info".

Can you make sure your intelliSenseEngine setting is set to "Enabled" and "intelliSenseEngineFallback" is set to "Disabled"?

**Comment by GitHimanshuc** [comment]
@sean-mcmanus I checked the intellisense setting and it was set to tagparser.
After doing what you suggested the UI no longer freezes when I hover over the variable.
Thanks for the help :smile:
I will close this issue now
