### ISSUE TITLE
error debugging with the message "could not find the task ..."

### ISSUE THREAD

**Issue by ezraluandre** [microsoft/vscode-cpptools#5428]
Type: Debugger

Trying to debugging code and error message popped up with the message "could not find the task 'cpp build active file'", trying to change the compiler using g++ and the error message still occur with the message "could not find the task 'g++ build active file'". 
here's my launch.json file
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "cpp - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "cpp build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```
and here's my task.json file
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "C/C++: cpp build active file",
			"command": "/bin/cpp",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}/${fileBasenameNoExtension}"
			],
			"options": {
				"cwd": "/bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": "build"
		}
	]
}
```

I completely have no idea what's wrong with it. Hopefully you guys can help me with the problem.

**Describe the bug**
- OS and Version: Ubuntu 20.04 LTS
- VS Code Version: ff915844
- C/C++ Extension Version: 0.27.1

**Comment by WardenGnaw** [comment]
`"preLaunchTask"` points to the label of which task you want to run in `task.json`. You will want to change it to `C/C++: cpp build active file`

**Comment by ezraluandre** [comment]
Already change it and another error message appear:
```
Unable to start debugging. Program path ... is missing or invalid.

GDB failed with message: "(Program path/Data)": not in executable format: file format not recognized

This may occur if the process's executable was changed after the process was started, such as when installing an update. Try re-launching the application or restarting the machine.
```
and the output windows tells me that 
```
"The task provider or "C/C++" tasks unexpectedly provided a task of type "shell"."
```
trying to restart and the problem still occur

**Comment by TomClesius** [comment]
got the same problem: "The task provider for "C/C++" tasks unexpectedly provided a task of type "shell""

**Comment by sean-mcmanus** [comment]
@ezraluandre The task provider error is https://github.com/microsoft/vscode-cpptools/issues/5388 .

Not sure about the other error yet.

**Comment by xi00ya** [comment]
my solution is that ensures your file name is "tasks.json" instead of "task.json". I hope it will be helpful to you. @ezraluandre
