### ISSUE TITLE
Code folding incorrectly matches to an inactive }

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5429]
Originally reported at https://github.com/microsoft/vscode-cpptools/issues/407.

Use code
```
int main()
{
    if (false)
    {
    #if false
    }
    #else
    }
    #endif
    return 0;
}
```

Bug: Code folding incorrectly matches to the inactive } instead of the active one that comes afterwards. The bug doesn't repro with VS.

**Comment by Colengms** [comment]
Code folding is lexer based.  It doesn't know the values of preprocessor conditions.  It looks like VS is initially folding this incorrectly as well, but doing another folding pass after inactive regions are available.  We might be able to do something similar, but need a way to trigger VS Code to request ranges from us again (without having to edit the document).  I've sent them a question on this, and am waiting for a reply.

**Comment by Colengms** [comment]
This is blocked on: https://github.com/microsoft/vscode/issues/99914

**Comment by Colengms** [comment]
Taking this out of tracking, as the blocking VS Code issue has been fixed.

**Comment by Colengms** [comment]
Although the blocking issue has been addressed by VS Code, it's still in insiders and not yet available in a general release.  This will need to be delayed until the next VS Code release.  This will also involve a dependency on that new VS Code version.

**Comment by Colengms** [comment]
The type we need is not yet present in @types/vscode 1.51.0.  It's expected to be in 1.52.0.
