### ISSUE TITLE
Passing linux escaped file paths on Windows to GDB is not possible

### ISSUE THREAD

**Issue by janjongboom** [microsoft/vscode-cpptools#543]
I have a debug configuration that connects to a remote target and flashes a binary:

```
            "windows": {
                "MIMode": "gdb",
                "MIDebuggerPath": "C:\\Program Files (x86)\\GNU Tools ARM Embedded\\4.9 2015q3\\bin\\arm-none-eabi-gdb.exe",
                "setupCommands": [
                    { "text": "-target-select remote localhost:3333", "description": "connect to target", "ignoreFailures": false },
                    { "text": "-file-exec-and-symbols ${workspaceRoot}\\BUILD\\${workspaceRootFolderName}.elf", "description": "load file", "ignoreFailures": false},
                    { "text": "-target-download", "description": "flash target", "ignoreFailures": false }
                ]
            }
```

However... GDB expects the file passed in to have the backslash escaped. It's easy to do if you have control over the path, e.g.:

```
c:\\\\path\\\\to\\\\BUILD\\\\${workspaceRootFolderName}.elf
```

But I don't want users to have to configure this themselves.

Can we get:

* A special variable `escapedWorkspaceRoot` with escaped backslashes.
* Or I'm open to better ways of doing this :-)

cc @sg-

**Comment by pieandcakes** [comment]
@janjongboom The piece where this would be implemented is https://github.com/Microsoft/MIEngine which is opensource and if you would like you can contribute to. Otherwise, I can add it to the backlog.

**Comment by pieandcakes** [comment]
@janjongboom also, if you use `"pipeTransport"` and ssh directly to the device, we don't change any of the path formats to Windows. Does that scenario work for you?

**Comment by janjongboom** [comment]
@pieandcakes I found the underlying issue, see https://github.com/Microsoft/vscode-cpptools/issues/548.

Closing this.
