### ISSUE TITLE
go to symbol in Editor loading slow [Python code]

### ISSUE THREAD

**Issue by Adolf-L** [microsoft/vscode-cpptools#5430]
**Type: LanguageService**

![image](https://user-images.githubusercontent.com/10137107/81275127-cfd24180-9083-11ea-99c5-599250aca2d7.png)

Intellisense Extremely Slow!

**Describe the bug**
- OS and Version:
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287

- VS Code Version:
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

- Other extensions you installed (and if the issue persists after disabling them):
1. vscode-neovim
2. python
3. settings sync

- Does this issue involve using SSH remote to run the extension on a remote machine?:
I don't think so, my py module to be installed local. I think vscode should search in local at first.

- A clear and concise description of what the bug is, including information about the workspace 
single .py file project. "go to symbol in Editor loading slow".

**Steps to reproduce**

1. install fmz  .py module with pip
2. check definition of the fmz function or class. back and forth 
3. enjoy the problems.

**Comment by michelleangela** [comment]
This repository is for the C/C++ extension. Did you mean to post this issue on the [Python GitHub repo](https://github.com/Microsoft/vscode-python)?

**Comment by Adolf-L** [comment]
sorry, I guess I should put it in another place.  moreover, I find the fmz.py module is too big. it works well when I use this feature with other modules so I am going to close this issue.
