### ISSUE TITLE
Message error when you change editor.fontWeight for a number value

### ISSUE THREAD

**Issue by severomario** [microsoft/vscode-cpptools#5434]
* File > Preferences > Settings
* Type **font** in the search field
* Try to update the value in **Editor: Font Weight**
* If you try to insert a number value the software will returns the following message: ``_Setting has an invalid type, expected "string". Fix in JSON_``

![image](https://user-images.githubusercontent.com/63346789/81349330-2e082000-9096-11ea-9d72-3e7291d3aa1f.png)

**Note:** In the previous version it worked perfectly.

![image](https://user-images.githubusercontent.com/63346789/81349393-4841fe00-9096-11ea-8ef9-38a829a26ded.png)

**Comment by sean-mcmanus** [comment]
Can you file a bug at https://github.com/microsoft/vscode/issues ? The issue is unrelated to our C/C++ extension.

**Comment by severomario** [comment]
> Can you file a bug at https://github.com/microsoft/vscode/issues ? The issue is unrelated to our C/C++ extension.

Thanks and I'm sorry for waste your time!
