### ISSUE TITLE
Syntax highlighting incorrect for comments near preprocessor statements

### ISSUE THREAD

**Issue by saberhawk** [microsoft/vscode-cpptools#5441]
Issue Type: <b>Bug</b>

I encountered some code that looks like:

```
#define ITEM_MASK 0x00000001U /**< Documentation
                                   that goes onto the next line */
```

The first line of the comment is correctly highlighted, but the rest of the comment is not.

According to the "Phases of translation" document (https://docs.microsoft.com/en-us/cpp/preprocessor/phases-of-translation), comments are replaced with a single space character in the "Tokenization" phase, before any preprocessor directives are processed. The entire comment should be highlighted the same way. If I switch the language type to "C" from "C++", this works correctly.

Extension version: 0.28.0-insiders2
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sean-mcmanus** [comment]
This bug repros without our C/C++ extension enabled. This sounds like it might be the same issue as https://github.com/jeff-hykin/cpp-textmate-grammar/issues/404 . If you don't believe, so could you file a new bug at https://github.com/jeff-hykin/cpp-textmate-grammar/issues ?

FYI, the default VS Code lexical highlighting comes from that extension (installing the extension provides a more recent version).

**Comment by bobbrow** [comment]
This issue is not caused by our extension.
