### ISSUE TITLE
IntelliSense does not support C++20 Concepts feature macro

### ISSUE THREAD

**Issue by MoritzMaxeiner** [microsoft/vscode-cpptools#5444]
**Type: LanguageService**

**Describe the bug**
- OS and Version: **Funtoo Linux 1.4**
- VS Code Version: **1.45.0**
- C/C++ Extension Version: **0.28.0-insiders2**
- Other extensions you installed (and if the issue persists after disabling them): **CMake Tools 1.3.3** used for simple steps to reproduce
- Does this issue involve using SSH remote to run the extension on a remote machine?: **No**
- IntelliSense does not support [C++20 Concepts feature macro](https://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros)

**Steps to reproduce**
1. Ensure `GCC 10.1.0` is available as a CMake Tools kit
2. Create new project folder
3. Create `CMakeLists.txt` with the following content:

```
cmake_minimum_required(VERSION 3.15)

project(test LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(${PROJECT_NAME})

target_sources(${PROJECT_NAME} PRIVATE main.c++)
```
4. Create `main.c++` with the following content:
```
#if defined(__INTELLISENSE__)
    #if !defined(__cpp_concepts)
        #error msg
    #endif
#endif
```
5. `File` -> `Open folder...` -> project folder
6. Select `GCC 10.1.0` as CMake Tools kit
7. Configure project with CMake Tools
8. See `#error` directive being triggered by IntelliSense

**Expected behavior**
`__cpp_concepts` should be defined.

**Additional context**

The extension correctly queries the proper GCC version with the following command line arguments:
```
$ -std=c++20 -Wp,-v -E -dD -x c++ -m64 /dev/null
```
, which does in fact return the correctly defined `__cpp_concepts`, so the error lies with the extension code itself. Since the only location in the extension I could find that contains `__cpp_*` strings (`grep -r __cpp_`) are the binaries `bin/cpptools` and `bin/cpptools-srv` I assume that these contain some kind of white list that filter unknown compiler feature macros out.

Please either fix these binaries or provide their source code.

**Comment by sean-mcmanus** [comment]
Okay, I was mislead by https://developercommunity.visualstudio.com/content/problem/946335/c20-concepts-not-supported-by-intellisense.html being marked as "Fixed". But it turns out there is more work to be done. See the VS issue tracking it at https://developercommunity.visualstudio.com/content/problem/745318/-cpp-lib-concepts-isnt-defined-in-vs-2019-1630-rel.html .

**Comment by Colengms** [comment]
@MoritzMaxeiner  Are you still seeing this issue?  I'm no longer able to repro.  I believe this may have been addressed by recent work to support concepts.  `__cpp_concepts` should now be defined as expected.

**Comment by MoritzMaxeiner** [comment]
I'm not seeing this issue anymore, either, thanks.
