### ISSUE TITLE
Incorrect IntelliSense error when passing this pointer as an argument

### ISSUE THREAD

**Issue by mouliangyu** [microsoft/vscode-cpptools#5447]
**Type: LanguageService**

```
class ObjA {
public:
  void funcA() {
    std::cout << "funcA" << std::endl;
  }
  class ObjB;
};

static std::set<ObjA::ObjB*> bset;
class ObjA::ObjB {
public:
  ObjB() {
    bset.insert(this);  // report error
  }
};
```

**Comment by Colengms** [comment]
Hi @MuLiangyu .  Thanks for reporting this.  The C/C++ Extension for VS Code shares IntelliSense code with VS.  This issue also repro's in VS, so I've opened a bug against VS [here](https://developercommunity.visualstudio.com/content/problem/1026193/incorrect-intellisense-error-passing-this-pointer.html).

**Comment by Colengms** [comment]
This appears to have been addressed some time ago.  I no longer repro this issue using 1.6.0.  Closing as fixed.
