### ISSUE TITLE
GetConsoleMode failing with error 5 (Access is denied) when debugging

### ISSUE THREAD

**Issue by Z1ni** [microsoft/vscode-cpptools#5449]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.45.0
- C/C++ Extension Version: 0.27.1
- Other extensions you installed (and if the issue persists after disabling them): issue persists when only ms-vscode.cpptools is installed

When debugging C programs built with MinGW64 GCC and using GetConsoleMode from ConsoleApi.h, the GetConsoleMode fails with error 5 (Access is denied). This does not happen when launching the affected program with the normal Terminal inside VS Code and other terminals (cmd, PowerShell, etc.).

Maybe the WindowsDebugLauncher is affecting this?

I have only tested this with MSYS2/GCC, maybe this happens with any debugged program that uses GetConsoleMode.

**To Reproduce**
Get the example `main.c` and `launch.json` from [here](https://gist.github.com/Z1ni/a14b32b7fdce7224505f1d017da847e7). Remember to replace the `miDebuggerPath` if needed.

1. Have MinGW64/MSYS2 installed (e.g. with Chocolatey, package "msys2")
2. Build the provided test program with `gcc -mconsole -o main.exe main.c`
3. Use the extension to debug the program (with the provided launch.json)
4. Observe that the program prints `GetConsoleMode failed: 5`
5. Run the same program with the VS Code Terminal or any other way (cmd, PowerShell, GDB) and observe the the program prints `All OK`.

**Comment by Z1ni** [comment]
Still occurs with 0.28.1

**Comment by kalineh** [comment]
This happens with 'git bash' shells as well (which seem to be MinGW64), any call to GetConsoleMode() or GetConsoleScreenBufferInfo() fails with ACCESS_DENIED. 

```
HANDLE handle = ::GetStdHandle(STD_OUTPUT_HANDLE);
RESULT result = ::GetConsoleScreenBufferInfo(handle, &info);
// result == FALSE, GetLastError() == 6
```

**Comment by ibigbug** [comment]
same issue, but with windows-rs

**Comment by ShadowMonster99** [comment]
Although I'm late to the conversation, editing my launch.json to use integrated terminal fixed this issue

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            ...
            "console": "integratedTerminal",
            ...
        }
    ]
}
```

it seems in my case since I was allocating a console inside the target app i was debugging, it was trying to overwrite vscode's console config (which it didn't have permission to do).
