### ISSUE TITLE
include file not found in include path 

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-cpptools#545]
_From @Eraldoosantos on March 9, 2017 16:45_

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.2|;

---

Hello, I've had some problems when I was programming in C language. So, everytime when I put the headers (includes) appeared this: "include file not found in include path". How can I fix this? The GCC compiler is installed in my computer. Ah, I'm using Windows 10 pro version. Could you solve this for me? I'm waiting for your answer.

Thanks for all =] 

_Copied from original issue: Microsoft/vscode#22309_

**Comment by ramya-rao-a** [comment]
_From @sean-mcmanus on March 9, 2017 18:41_

The location for C++ extension issues is: https://github.com/Microsoft/vscode-cpptools/issues .

You should click the yellow lightbulb to add your include path to the includePath setting in c_cpp_properties.json.

**Comment by eraldooneto** [comment]
Sorry, @ramya-rao-a! I don't understanding you.  When I click in the yellow lightbulb nothing happen, I do not know which folder I should open first. Could you tell me step by step? I'm so frustrated because of it. Thank you! 


![image](https://cloud.githubusercontent.com/assets/18681091/23766790/f511af7c-04e4-11e7-8a1e-f975eb1522bc.png)

**Comment by bobbrow** [comment]
The extension expects you to open a folder in your file system first - click the file icon in the upper left corner - before you can set include paths (it needs to know where to save the c_cpp_properties.json file).  It looks like you just opened a single file in the editor.

**Comment by bobbrow** [comment]
Adding a screen shot:
![545](https://cloud.githubusercontent.com/assets/12818240/23769911/d87c62d6-04c5-11e7-8cae-2ffe222459ba.png)

**Comment by eraldooneto** [comment]
![image](https://cloud.githubusercontent.com/assets/18681091/23771314/4bab93ec-04f5-11e7-8003-f7f740e35cdb.png)

@bobbrow

**Comment by eraldooneto** [comment]
@bobbrow , What I have to do now?

**Comment by bobbrow** [comment]
Add the path to your Windows SDK installation in the Win32 configuration's `includePath` (I'm assuming the latest in the example below):
```json
        {
            "name": "Win32",
            "includePath": [
                "c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                "c:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0"
            ],
            "browse" : {
                "limitSymbolsToIncludedHeaders" : true,
                "databaseFilename" : ""
            }
        }
```

**Comment by eraldooneto** [comment]
Thank you, Mr. @bobbrow !

**Comment by Friduric** [comment]
I still have the same problem after adding my Windows SDK installation in the Win32 configuration's `includePath`. 
![err](https://cloud.githubusercontent.com/assets/9356807/24322168/5eb9f486-115e-11e7-9671-5a1d1c82ff3f.png)

**Comment by Friduric** [comment]
If someone uses MinGW/gcc as I do, then the correct `includePath` would be something along the following lines:
"C:/MinGW/lib/gcc/mingw32/5.3.0/include/c++"

**Comment by melonshell** [comment]
@Friduric @Eraldoosantos 
it doesn't work, include iostream remains red, help me, vscode1.13.1, win10
{
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}",
                "C:/cygwin64/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/*"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "browse": {
                "path": [],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }

**Comment by fuzboxz** [comment]
@vinnyin  For me the iostream file doesn't have a .h extension in MinGW. Have you tried #include <iostream>?

**Comment by bobbrow** [comment]
@vinnyin, please take a look at the [template config I posted for MinGW](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md).  Cygwin will be slightly different, but the imporant part is that you need to make sure that you add all of the relevant directories in the includePath since the `includePath` paths are not recursively traversed.

If you are still having trouble, please open a new issue.  This one was closed months ago and the c_cpp_properties.json format has changed since then.  I would prefer for people searching for help not to land on this old issue.  Thanks!

**Comment by Adobe-Android** [comment]
This is for anyone having this same issue when using the Microsoft cl compiler. Assuming you are using the latest version of the build tools (15.6.6 at the time of this post), you are likely not including everything you need. Here's the includePath portion of my config (update any numbers to reflect the version you have installed). 

```
"includePath": [
                "${workspaceFolder}",
                "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\include\\*",
                "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.16299.0\\shared",
                "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.16299.0\\ucrt",
                "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.16299.0\\um",
                "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.16299.0\\winrt"
            ]
```

You only need to add this path to resolve this particular issue, but adding these additional ones may help keep you from running into a similar issue later.
`C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.16299.0\\ucrt`

**Comment by rameshkunasi** [comment]
Hi, 
I am using VS Code on Linux platform. I have included external C header files in my code. I added include path. Even though while compiling it is showing error.

c_cpp_properties.json file has

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "/home/user/Desktop/x",
                "/home/user/Desktop/y/include/",
                "/home/user/Desktop/z/a/include/"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
@rameshkunasi Remove "/usr/include" and "/usr/local/include" from you path. Adding those explicitly can cause the ordering to be incorrect compared to the ordering that the compiler expects (maybe we should better handle this common user error). Having your compilerPath set to /usr/bin/gcc is supposed to set the system includes for you. Does that fix your issue? If not [enabling logging] can help diagnose what is going wrong: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md .
