### ISSUE TITLE
Unreal programing,  can't find includePath and intellisence with a high cpu usage , the same in vs2019

### ISSUE THREAD

**Issue by han9088** [microsoft/vscode-cpptools#5451]
**env**
window 10
unreal 4.25
vs2019

**Steps to reproduce**
I just created a new unreal project, and opened it in vscode。
then intellisence analyzes all the time, vs2019, clion has the same problem

<details>
  <summary><strong>c_cpp_properties.json</strong></summary>

```
{
    "configurations": [
        {
            "name": "UnrealEngine",
            "includePath": [
                "C:\\Program Files\\Epic Games\\UE_4.25\\Engine\\Source",
                "C:\\Program Files\\Epic Games\\UE_4.25\\Engine\\Intermediate\\Build\\Win64\\UE4Editor\\Inc\\Engine",
                "C:\\Program Files\\Epic Games\\UE_4.25\\Engine\\Source\\Runtime",
                "C:\\Program Files\\Epic Games\\UE_4.25\\Engine\\Source\\Runtime\\Engine\\Classes",
                "C:\\Program Files\\Epic Games\\UE_4.25\\Engine\\Source\\Runtime\\Engine\\Public",
                "C:\\Program Files\\Epic Games\\UE_4.25\\Engine\\Source\\Runtime\\TraceLog\\Public",
                "C:\\Program Files\\Epic Games\\UE_4.25\\Engine\\Source\\Runtime\\Core\\Public",
                   ...ignore.....
                "C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um",
                "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt",
                "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared",
                "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um",
                "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\winrt"
            ],
            "intelliSenseMode": "msvc-x64",
            "defines": [],
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```
</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/45007226/81492444-41033600-92ca-11ea-9794-9f09ead85209.png)

**Comment by Colengms** [comment]
Hi @sewerganger .  The extension needs to lexically/syntactically parse all headers in the project (and system headers) the first time opened (or until it can complete).  I suspect this is what you are seeing.  During that time, the database cylindar icon should be present on the bottom of the window. If you enable logging using, `"C_Cpp.loggingLevel": "Debug"`, you can view details about its progress.  Once parsing is complete, squiggles should update and headers should be found.  This should only need to be done once to build the tag parser database.

Also, depending on the complexity of the file opened, IntelliSense (semantic) parsing can also be time consuming, and is indicated by a flame icon at the bottom of the window.  As this completes, squiggles update.

**Comment by han9088** [comment]
@Colengms  thanks for your time. I waited for it to parse end, but it still prompted errors. then i reloaded the vscode, it restarted parsing. 😂

**Comment by Colengms** [comment]
Hi @sewerganger .   Are you sure tag parsing had completed?  Can you check if "Warning: Database safety check failed. Recreating database." appears in your log when you reload?  If tag parsing is restarting, it should be associated with that error message.  Otherwise, it's likely continuing where it left off.

**Comment by han9088** [comment]
l tried it again until the cylindrical icon disappeared, but errors still display without any extension's 
error message tips,  i found the same issue in unreal community https://issues.unrealengine.com/issue/UE-87619.
I will give up resolving this, it spends too long time

![image](https://user-images.githubusercontent.com/45007226/81780490-2f6b9980-9529-11ea-95df-10ec676c5a8e.png)

![image](https://user-images.githubusercontent.com/45007226/81780438-1d89f680-9529-11ea-843d-62fb2280354c.png)
