### ISSUE TITLE
Bug for grammar analysis

### ISSUE THREAD

**Issue by CY-Pan** [microsoft/vscode-cpptools#5452]
![image](https://user-images.githubusercontent.com/59761962/81495250-9b5bc100-92e1-11ea-9f76-0d683376a9f0.png)
When I'm overwritting this operator in this way, it tells me the first parameter must be `size_t` type. But I'm doing correctly and this file worked before.

**Comment by Colengms** [comment]
Hi @CY-Pan .  Can you provide additional information, such as what platform you are running on, and the configuration you are using?  I'm not immediately able to repro the issue, and could use additional information.

To venture a guess, perhaps there is a mismatch between the compiler architecture you have the intelliSense mode set to, and the headers you are compiling against?  That could lead to a mismatch of the size of size_t.

**Comment by CY-Pan** [comment]
Sorry for the vague information. I’m running on Windows 10 Professional *64, 1909, with VS Code 1.45.0. And my compiler is GCC via mingw-w64.

 

I was using version 0.27.1 of this extension when I met another bug #5388 <https://github.com/microsoft/vscode-cpptools/issues/5388> . Then I tried 0.28.0-insider3 and met the bug I reported.

   

 

My other extensions:



 

My task.json:


{

    "version": "2.0.0",

    "command": "g++",

    "args": [

        "-g",

        "${file}",

        "-o",

        "${fileBasenameNoExtension}.exe"

    ],

    "echoCommand": true,

    "problemMatcher": {

        "owner": "cpp",

        "fileLocation": [

            "relative",

            "${workspaceRoot}"

        ],

        "pattern": {

            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",

            "file": 1,

            "line": 2,

            "column": 3,

            "severity": 4,

            "message": 5

        }

    }

}

 

 

My launch.json:


{

    "version": "0.2.0",

    "configurations": [

        {

            "name": "(gdb)c++",

            "type": "cppdbg",

            "request": "launch",

            "targetArchitecture": "x64",

            "program": "${workspaceFolder}/${fileBasenameNoExtension}.exe",

            "miDebuggerPath": "D:/MinGW/mingw64/bin/gdb.exe",

            "MIMode": "gdb",

            "args": [],

            "stopAtEntry": false,

            "cwd": "${workspaceFolder}",

            "environment": [],

            "externalConsole": false,

            "internalConsoleOptions": "neverOpen",

            "preLaunchTask": "g++"

        }

    ]

}

 

 

My c_cpp_properties.json


{

    "configurations": [

        {

            "name": "MinGW",

            "includePath": [

                "D:/MinGW/mingw64/include",

                "D:/MinGW/mingw64/x86_64-w64-mingw32/include",

                "${workspaceFolder}"

            ],

            "defines": [

                "_DEBUG",

                "UNICODE",

                "_UNICODE"

            ],

            "intelliSenseMode": "${default}",

            "browse": {

                "path": [

                    "D:/MinGW/mingw64/include",

                    "D:/MinGW/mingw64/x86_64-w64-mingw32/include",

                    "${workspaceFolder}"

                ],

                "limitSymbolsToIncludedHeaders": true,

                "databaseFilename": ""

            },

            "cStandard": "c11",

            "cppStandard": "c++20",

            "compilerPath": "D:/MinGW/mingw64/bin/g++.exe"

        }

    ],

    "version": 4

}

 

 

Wish you all good!

 

发件人: Colen Garoutte-Carson <notifications@github.com> 
发送时间: 2020年5月12日, 星期二 6:41
收件人: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
抄送: CY-Pan <adredpcy@qq.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/vscode-cpptools] Bug for grammar analysis (#5452)

 

Hi @CY-Pen . Can you provide additional information, such as what platform you are running on, and the configuration you are using? I'm not immediately able to repro the issue, and could use additional information.

To venture a guess, perhaps there is a mismatch between the compiler architecture you have the intelliSense mode set to, and the headers you are compiling against? That could lead to a mismatch of the size of size_t.

**Comment by CY-Pan** [comment]
Sorry for the vague information. I’m running on Windows 10 Professional *64, 1909, with VS Code 1.45.0. And my compiler is GCC via mingw-w64.

 

I was using version 0.27.1 of this extension when I met another bug #5388 <https://github.com/microsoft/vscode-cpptools/issues/5388> . Then I tried 0.28.0-insider3 and met the bug I reported.

  

 

My other extensions:



 

My task.json:


{

    "version": "2.0.0",

    "command": "g++",

    "args": [

        "-g",

        "${file}",

        "-o",

        "${fileBasenameNoExtension}.exe"

    ],

    "echoCommand": true,

    "problemMatcher": {

        "owner": "cpp",

        "fileLocation": [

            "relative",

            "${workspaceRoot}"

        ],

        "pattern": {

            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$ <file://d+):(/d+):/s+(warning|error):/s+(.*)$> ",

            "file": 1,

            "line": 2,

            "column": 3,

            "severity": 4,

            "message": 5

        }

    }

}

 

 

My launch.json:


{

    "version": "0.2.0",

    "configurations": [

        {

            "name": "(gdb)c++",

            "type": "cppdbg",

            "request": "launch",

            "targetArchitecture": "x64",

            "program": "${workspaceFolder}/${fileBasenameNoExtension}.exe",

            "miDebuggerPath": "D:/MinGW/mingw64/bin/gdb.exe",

            "MIMode": "gdb",

            "args": [],

            "stopAtEntry": false,

            "cwd": "${workspaceFolder}",

            "environment": [],

            "externalConsole": false,

            "internalConsoleOptions": "neverOpen",

            "preLaunchTask": "g++"

        }

    ]

}

 

 

My c_cpp_properties.json


{

    "configurations": [

        {

            "name": "MinGW",

            "includePath": [

                "D:/MinGW/mingw64/include",

                "D:/MinGW/mingw64/x86_64-w64-mingw32/include",

                "${workspaceFolder}"

            ],

            "defines": [

                "_DEBUG",

                "UNICODE",

                "_UNICODE"

            ],

            "intelliSenseMode": "${default}",

            "browse": {

                "path": [

                    "D:/MinGW/mingw64/include",

                    "D:/MinGW/mingw64/x86_64-w64-mingw32/include",

                    "${workspaceFolder}"

                ],

                "limitSymbolsToIncludedHeaders": true,

                "databaseFilename": ""

            },

            "cStandard": "c11",

            "cppStandard": "c++20",

            "compilerPath": "D:/MinGW/mingw64/bin/g++.exe"

        }

    ],

    "version": 4

}

 

 

Wish you all good!

 

 

发件人: Colen Garoutte-Carson <notifications@github.com> 
发送时间: 2020年5月12日, 星期二 6:41
收件人: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
抄送: CY-Pan <adredpcy@qq.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/vscode-cpptools] Bug for grammar analysis (#5452)

 

Hi @CY-Pen . Can you provide additional information, such as what platform you are running on, and the configuration you are using? I'm not immediately able to repro the issue, and could use additional information.

To venture a guess, perhaps there is a mismatch between the compiler architecture you have the intelliSense mode set to, and the headers you are compiling against? That could lead to a mismatch of the size of size_t.

**Comment by Colengms** [comment]
Hi @CY-Pan .  Could you run the `C/C++: Log Diagnostics` command while the repro file open, and post its output here?  Also, could you provide complete example code that I can paste to repro?  (With #include's, etc.)

I noticed the following in your configuration:
```
"intelliSenseMode": "${default}",
```

Have you set default.intelliSenseMode?  What is it set to?

**Comment by CY-Pan** [comment]
This is the output of Log Diagnostics:


-------- Diagnostics - 2020/5/13 上午8:42:45

Version: 0.28.0-insiders3

Current Configuration:

{

    "name": "MinGW",

    "includePath": [

        "D:/MinGW/mingw64/include",

        "D:/MinGW/mingw64/x86_64-w64-mingw32/include",

        "${workspaceFolder}"

    ],

    "defines": [

        "_DEBUG",

        "UNICODE",

        "_UNICODE"

    ],

    "browse": {

        "path": [

            "D:/MinGW/mingw64/include",

            "D:/MinGW/mingw64/x86_64-w64-mingw32/include",

            "${workspaceFolder}"

        ],

        "limitSymbolsToIncludedHeaders": true

    },

    "cStandard": "c11",

    "cppStandard": "c++20",

    "compilerPath": "D:/MinGW/mingw64/bin/g++.exe",

    "compilerArgs": []

}

Translation Unit Mappings:

[ D:\Onedrive\VS Code\C++\Test.cpp ]:

    D:\ONEDRIVE\VS CODE\C++\TEST.CPP

Translation Unit Configurations:

[ D:\Onedrive\VS Code\C++\Test.cpp ]:

    Process ID: 23332

    Memory Usage: 26 MB

    Compiler Path: D:/MinGW/mingw64/bin/g++.exe

    Includes:

        D:\MINGW\MINGW64\INCLUDE

        D:\ONEDRIVE\VS CODE\C++

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\X86_64-W64-MINGW32

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\BACKWARD

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE-FIXED

        D:\MINGW\MINGW64\X86_64-W64-MINGW32\INCLUDE

    Defines:

        _DEBUG

        UNICODE

        _UNICODE

    Standard Version: c++20

    IntelliSense Mode: gcc-x64

    Other Flags:

        --g++

        --gnu_version=80100

Total Memory Usage: 26 MB

 

 

And the content of the file is:


#include <iostream>

using namespace std;

 

class A

{

public:

    void *operator new(size_t sz)

    {

        cout << "construct A" << endl;

        return ::operator new(sizeof(A));

    }

};

 

int main()

{

    A *a = new A;

}

 

 

I didn’t set default.intelliSenseMode because I don’t know what it is. And there is no setting.json in this folder. In my user settings, ‘intelliSenseMode’ doesn’t appear. I just copy the other 3 .json from online tutorials.

 

Here is another Log Diagnostics for version 0.27.1, if you would like to find their difference.


-------- Diagnostics - 2020/5/13 上午8:52:56

Version: 0.27.1

Current Configuration:

{

    "name": "MinGW",

    "includePath": [

        "D:/MinGW/mingw64/include",

        "D:/MinGW/mingw64/x86_64-w64-mingw32/include",

        "${workspaceFolder}"

    ],

    "defines": [

        "_DEBUG",

        "UNICODE",

        "_UNICODE"

    ],

    "browse": {

        "path": [

            "D:/MinGW/mingw64/include",

            "D:/MinGW/mingw64/x86_64-w64-mingw32/include",

            "${workspaceFolder}"

        ],

        "limitSymbolsToIncludedHeaders": true

    },

    "cStandard": "c11",

    "cppStandard": "c++20",

    "compilerPath": "D:/MinGW/mingw64/bin/g++.exe",

    "compilerArgs": []

}

Translation Unit Mappings:

[ D:\Onedrive\VS Code\C++\Test.cpp ]:

    D:\ONEDRIVE\VS CODE\C++\TEST.CPP

Translation Unit Configurations:

[ D:\Onedrive\VS Code\C++\Test.cpp ]:

    Process ID: 22612

    Memory Usage: 49 MB

    Compiler Path: D:/MinGW/mingw64/bin/g++.exe

    Includes:

        D:\MINGW\MINGW64\INCLUDE

        D:\ONEDRIVE\VS CODE\C++

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\X86_64-W64-MINGW32

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\BACKWARD

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE

        D:\MINGW\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE-FIXED

        D:\MINGW\MINGW64\X86_64-W64-MINGW32\INCLUDE

    Defines:

        _DEBUG

        UNICODE

        _UNICODE

    Standard Version: c++20

    IntelliSense Mode: gcc-x64

    Other Flags:

        --g++

        --gnu_version=80100

Total Memory Usage: 49 MB

 

 

Wish you all good.

 

发件人: Colen Garoutte-Carson <notifications@github.com> 
发送时间: 2020年5月13日, 星期三 4:28
收件人: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
抄送: CY-Pan <adredpcy@qq.com>; Mention <mention@noreply.github.com>
主题: Re: [microsoft/vscode-cpptools] Bug for grammar analysis (#5452)

 

Hi @CY-Pan <https://github.com/CY-Pan>  . Could you run the C/C++: Log Diagnostics command while the repro file open, and post its output here? Also, could you provide complete example code that I can paste to repro? (With #include's, etc.)

I noticed the following in your configuration:

"intelliSenseMode": "${default}",

Have you set default.intelliSenseMode? What is it set to?

**Comment by Colengms** [comment]
I believe we are tracking the size_t issue with: https://github.com/microsoft/vscode-cpptools/issues/5457
