### ISSUE TITLE
semantic coloring issue with nested macros

### ISSUE THREAD

**Issue by not-name-but-id** [microsoft/vscode-cpptools#5455]
**Type: LanguageService**

The following C++ program produces incorrect coloring of the function argument when "A(f1(B param));" is called. It looks like the argument is somehow not parsed at all. Below the faulty line and some correctly working alternatives are shown. 

```
#define A(x) x
#define B

void f1(int x)
{
}

void f2(int param)
{
    A(f1(B param)); //bad
    A(f1(B (param))); //good
    A(f1(param)); //good
    f1(B param); //good
}

```
The variable "param" in the bad line is also not highlighted when the cursor is over that variable somewhere else:
![image](https://user-images.githubusercontent.com/64163171/81502853-d9a4b080-92e0-11ea-92a4-b6ece963eaef.png)

It seems this behavior is always the same independently of the setting of intelliSenseMode and cppStandard.

**Describe the bug**
- OS and Version: fedora linux fc31
- VS Code Version: 1.45.0
- C/C++ Extension Version: 0.27.1
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Themes 1.0.0 (not disabled)
- Does this issue involve using SSH remote to run the extension on a remote machine?: no

**Expected behavior**

Correct semantic coloring should be applied to the argument of the function in line 10 after the macro.

I can provide more details if needed.

**Comment by Colengc** [comment]
Hi @not-name-but-id .  Thanks for reporting this.  The C/C++ Extension for VS Code shares code for IntelliSense with VS, and this issue also repro's in VS.  I've opened a bug against VS [here](https://developercommunity.visualstudio.com/content/problem/1026082/semantic-coloring-issue-with-nested-macros.html).

**Comment by bobbrow** [comment]
The linked VS feedback ticket was closed as "lower priority." Unfortunately, that means we won't be getting a fix in the C++ extension either.
