### ISSUE TITLE
[Feature Request] Add UI feedback that 'Rescan Workspace' was completed successfully

### ISSUE THREAD

**Issue by guochengli** [microsoft/vscode-cpptools#5458]
Issue Type: <b>Improvement</b>

After running C-S-P 'c/c++ rescan workspace' command, there is no response, no status bar, no progress bar, no outputs..., It seems nothing happens after running this command

Extension version: 0.27.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-1050-oem

**Comment by Colengms** [comment]
Hi @guochengli .  Thanks for reporting this.  We'll add this to our backlog.

**Comment by bobbrow** [comment]
We do have some UI in the status bar that communicates this already.  If the database (![image](https://user-images.githubusercontent.com/12818240/84949893-ce446200-b0a2-11ea-9238-9dbfb2d987dd.png)) and flame (![image](https://user-images.githubusercontent.com/12818240/84949912-da302400-b0a2-11ea-944e-34a9c9c11132.png)) icons are present in the status bar, then the command is still working.  Are you looking for something else like a pop up message or log message in the output window?
