### ISSUE TITLE
Losing colorization in switch-case statements 

### ISSUE THREAD

**Issue by pelco** [microsoft/vscode-cpptools#5461]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux 5.3.0-51-generic 18.04.2-Ubuntu
- VS Code Version: 1.45.0
- C/C++ Extension Version: 0.28.0-insiders3

The _switch case_ statements lose syntax highlighting if `(void)` is added to discard a function return value.

**Screenshots**
![image](https://user-images.githubusercontent.com/16528048/81583144-d2e17080-93a8-11ea-8d54-f375da223ab0.png)

The below `case` and `default` keyword lose they color if `(void)` is added to discard a function 
return value.

If we add a space between `(void)` and function call we get the expected result:

**Expected behavior**
![image](https://user-images.githubusercontent.com/16528048/81583705-9febac80-93a9-11ea-8b53-70bbe4e20e44.png)

Thanks,

**Comment by Colengms** [comment]
Hi @pelco .  The C/C++ Extension does not actually provide colorization information based on syntax.  That is based on TextMate grammer built into VS Code (or possibly an extension that provides grammar, such as the Better C++ Syntax extension).  That said, I'm unable to reproduce what you are describing.  Is it possible you have another extension installed that might be influencing colorization?

**Comment by pelco** [comment]
Hi @Colengms. So I disabled all plugins and the result is the same:
![image](https://user-images.githubusercontent.com/16528048/81725428-ba8f5580-947d-11ea-96f8-b0c62b8dbaab.png)

Probably it's not related to the extension. Do you have any suggestions?

**Comment by Colengms** [comment]
Hi @pelco .  Aha.  I was unable to repro due to using a .cpp file.  The issue appears to only repro in .c files.  I would suggest opening an issue in the [VS Code repo](https://github.com/microsoft/vscode), or the [Better C++ Extension repo](https://github.com/jeff-hykin/cpp-textmate-grammar), as the later is the source of the syntactic grammar rules for C and C++ in VS Code.

**Comment by pelco** [comment]
Hi @Colengms. I reported the issue at https://github.com/jeff-hykin/cpp-textmate-grammar/issues/478.
Thank you for your support.
Stay safe.

**Comment by pelco** [comment]
Will close this issue since it's already being addressed by https://github.com/jeff-hykin/cpp-textmate-grammar/issues/478
