### ISSUE TITLE
Wrong colorization of `decltype` in trailing return type.

### ISSUE THREAD

**Issue by BillXWB** [microsoft/vscode-cpptools#5462]
Wrong colorization of `decltype` in trailing return type.

**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 19041.208
- VS Code Version: 1.45.0
- C/C++ Extension Version: 0.27.1
- Other Extensions: all disabled

The color of `decltype` is wrong in trailing return type.

**Screenshots**

![vscode-cpp bug](https://user-images.githubusercontent.com/40427537/81583725-53719280-93e4-11ea-87a3-dad0a85ceed7.png)

**Expected behavior**
The color should be the same as that on line 3. Maybe this extension thinks `decltype` here is a function?

**Comment by Colengms** [comment]
Hi @BillXWB .  The TextMate (syntactic) rules for colorization are coming from VS Code itself.  You can confirm this by using the command, `Developer: Inspect Editor Tokens and Scopes`, and clicking on the keyword to inspect.  In the near future (0.29.0), semantic tokens provided by the C/C++ Extension will be displayed there as well, though `decltype` is not a semantic token so its colorization will continue to be based on the syntactic rules.

My understanding is that VS Code ingests the C/C++ TextMate grammer provided by [this repo](https://github.com/jeff-hykin/cpp-textmate-grammar).  Installing the latest Better C++ Extension will likely give you more updated rules than are being used by VS Code.  I'd suggest opening an issue in that repo or the VS Code repo.

I suspect it would be an easy fix to always prioritize decltype as a keyword.

**Comment by Colengms** [comment]
Closing this issue as external.
