### ISSUE TITLE
0.28.0-insiders3: Tag parsing no longer working

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#5463]
Starting with 0.28.0-insiders3, I noticed that the tag parsing was no longer working. For example, now "Find all references" only works in the current TU (because I assume it relies on the tag parser to find other "potential references" in other TUs?).

I setup cpptools by providing the path to the compile_commands.json in the workspace level settings (I typically open multiple folders but I only configure at the workspace level):

"C_Cpp.default.compileCommands": "/path/to/compile_commands.json",

See attached log files. 

"old.log" is 0.27.1 and "new.log" is 0.28.0-insiders3

Notice that in "new.log" the tag parsing does not appear to be working. It seems like it tag parses the headers in the current TU (very slowly?) but nothing else. Every header it tries to parse gets the following error as well:

Tag parsing encountered an error, but it may not matter. Let us know if symbols in the file can't be found

[old.log](https://github.com/microsoft/vscode-cpptools/files/4611690/old.log)
[new.log](https://github.com/microsoft/vscode-cpptools/files/4611691/new.log)

**Comment by sean-mcmanus** [comment]
0.28.0-insiders3 fixed a bug with compile_commands.json that caused the browse.path (files that get tag parsed) to be missing files (although there are still some cases where file are missed). However, your log show that it's in the middle of tag parsing. Do you still get Find All Refs missing results when the workspace parsing is 100% finished? When you open a file that is failing to get tag parsed, does the Outline still populate with symbols? If so, it would be a regression with our parser.

**Comment by ghost** [comment]
> However, your log show that it's in the middle of tag parsing. Do you still get Find All Refs missing results when the workspace parsing is 100% finished?

The tag parsing never finishes.The cylinder on the status bar just shows parsing 0/3500 files forever. I attached another log where I opened vscode, opened a file and waited 30 minutes (the tag parsing never made progress):
[Insiders3.log](https://github.com/microsoft/vscode-cpptools/files/4615444/Insiders3.log)

I downloaded the vsix for Insiders2, followed the same steps and tag parsing was done in 5 minutes or less:
[insiders2.log](https://github.com/microsoft/vscode-cpptools/files/4615455/insiders2.log)

> When you open a file that is failing to get tag parsed, does the Outline still populate with symbols?

A few files I open show the outline but most just hang when trying to load it.




I'm also seeing red squiggles on all files that I open. Most are showing the error: 

'cannot open source file "sysdep/1/filesystem_impl_native.hpp" (dependency of'

Let me know if I can provide any more info.

**Comment by ghost** [comment]
Notice that in insiders3.log you will see:
  stdver: c++14
But in insiders2.log you will see:
  stdver: c++17

My compile_commands.json specifies c++17 and so something is definitely wrong in insiders3. 

This at least explains why I'm see the squiggly for "sysdep/1/filesystem_impl_native.hpp" because std::filesystem is only in c++17.

I'm checking to see if other defines/includes are wrong. I'm guessing that would explain why the tag parsing is failing?

**Comment by ghost** [comment]
Ok, I figured out the tag parser issue:

In insiders2, if you had a compile_commands.json specified in workspace settings, then only the workspaceFolder would be added to be added to the browse path. Now, everything in the compile_commands.json is being added to the browse path. In our codebase, we have "handwritten headers" and "generated headers". All the "generated headers" do is #include the "handwritten headers". However, they do it with a kind of ugly relative include path -- #include "../../../../../../../path/to/handwritten/header.hpp". Now the "generated headers" are being added to the browse path. The tag parser crashes on these.

Is there a way I can exclude a folder from the browse path but not the include path as a workaround? Otherwise, I guess I can't use compile_commands.json.

**Comment by sean-mcmanus** [comment]
You can add the folders to files.exclude to exclude them from tag parsing. 

By "tag parser crashes" you mean fails to parse the files and not cpptools actually crashes, right?

**Comment by ghost** [comment]
> By "tag parser crashes" you mean fails to parse the files and not cpptools actually crashes, right?

It fails to parse and it seems like it puts the tag parser in a bad state. It seems like nothing gets parsed correctly thereafter.

**Comment by ghost** [comment]
It seems like the files.exclude does workaround the problem. Thanks.

**Comment by michelleangela** [comment]
Closing this issue because it has not had recent activity.
