### ISSUE TITLE
Contradiction between includePath and compilerPath

### ISSUE THREAD

**Issue by niebayes** [microsoft/vscode-cpptools#5468]
It is said that if we explicitly declare the compilerPath, the extension will query the compiler to determine the system include paths and default defines to use for IntelliSense. If used, the includePath **would not be needed** since the IntelliSense will use the compiler to figure out the system include paths. See: https://stackoverflow.com/a/37548293 
Is it true ?

**Comment by Colengms** [comment]
Hi @niebayes .  If your code only needs to include files from system include paths, you may not need any additional include paths.  However, if your project leverages any non-system libraries, or if you have organized your headers into specific locations (i.e. an 'inc' directory), those paths will not be provided by the compiler, and would need to be provided via `includePath`.

**Comment by niebayes** [comment]
@Colengms Actually, as the doc said, the users shall modify the includePath when it comes to IntelliSense and nothing more. The includePath has nothing to do with the compilation. I ultimately solved this issue by explicitly setting the clang++ compiling options in the tasks.json file. Last but not least, thanks for your comment!
