### ISSUE TITLE
VSCODE reports thousands of problems when building my program with c++11.

### ISSUE THREAD

**Issue by Swordfish1990** [microsoft/vscode-cpptools#5469]
OS: Centos7
cpptools version: 0.28.0-insiders3
GCC version: 10.1.0

the problems like this:
stray '\177' in program
stray '\2' in program
stray '\1' in program
stray '@' in program
stray '#' in program
......

the task.json like this:
`{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "build",
			"command": "/usr/bin/g++",
			"args": [
				"-g",
				"${workspaceFolder}/main.cpp",
				"${workspaceFolder}/clean_entity_text.cpp",
				"-o",
				"${workspaceFolder}/build",
				"-lmysqlpp",
				"-std=c++11"
			],
			"options": {
				"cwd": "/usr/bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}`

However,when I chose c++03,VSCODE works fine.What's more,when I use the Centos Terminal to excute g++ command with c++11,it works too. So,it seems that my vscode can only use c++03 to
building programs.How to solve this issue?

**Comment by sean-mcmanus** [comment]
Does your issue repro with the C/C++ extension disabled? I'm not sure what could be causing this.

**Comment by Swordfish1990** [comment]
No,the C/C++ extension is enabled. And it works fine on c++03.

**Comment by sean-mcmanus** [comment]
Yes but if you change it to disabled, does the bug still repro?

By "on c++03" you mean "c++03" in your tasks.json, right? Our extension doesn't have any interaction with the tasks.json.

**Comment by Swordfish1990** [comment]
Yes,I mean "-std=c++03" in tasks.json. But if I disable the C/C++ extension,I can't use vscode to build my program.So,you want to make sure whether the issue caused by gcc? I have tried to use g++ command without vscode to build my program,no bug reports.

**Comment by sean-mcmanus** [comment]
I mean temporarily disable the C/C++ extension to see if the bug still repros. You should be able to run the task without the C/C++ extension installed.

There might be some difference in the way you're invoking g++ on the command line versus in the tasks.json.

**Comment by Swordfish1990** [comment]
I have run the task without the C/C++ extension installed,the bug still repros.

**Comment by sean-mcmanus** [comment]
Oh, I think your `"cwd"` is incorrect in your tasks.json. Could you change it to `${workspaceFolder}`?

Otherwise, I don't know what could cause this -- it sounds like it's using the wrong gcc (that doesn't support c++11). You might try add a "--version" as an argument to see what it returns. Or file a VS Code issue at https://github.com/microsoft/vscode/issues .

**Comment by Swordfish1990** [comment]
Thanks for your help.

**Comment by Swordfish1990** [comment]
Your advice is very helpful!The issue caused by "cwd".I change it to ${workspaceFolder},the bug solved.
