### ISSUE TITLE
Intellisense does not seem to be context-aware

### ISSUE THREAD

**Issue by janjongboom** [microsoft/vscode-cpptools#547]
I'm wondering if I have some configuration set up wrong, but Intellisense with the C/C++ plugin seems to be context unaware and always show all symbols.

E.g. I have the following header file:

```cpp
#ifndef _MORE_SYMBOLS_H_
#define _MORE_SYMBOLS_H_

#include <string.h>

namespace jan {
    const char* hello() {
        return "World";
    }

    class RandomClass {
public:
        static int MyPublicFunction() {
            return 7;
        }

private:
        int MyPrivateFunction() {
            return 5;
        }
    };
}

#endif
```

When I now start typing in my `main.cpp` (which references this header file), I get suggestions for all symbols (including the private function):

![screen shot 2017-03-10 at 09 56 34](https://cloud.githubusercontent.com/assets/816856/23788673/e16caae2-0577-11e7-9954-0ac8ff60b512.png)

These symbols should not show because:

1. They are in a namespace.
2. They are in a class.
3. One of them is private.

Is there a way to disable the current behavior?

(Note that when I type `jan::` I do only get symbols from that namespace, so there is definitely something implemented :-)).

cc @sg-

**Comment by bobbrow** [comment]
We don't have context aware auto-complete implemented in the extension yet.  We're tracking that with issue #13.  Seeing all of your symbols as you type is expected right now.  The `C_Cpp.autocomplete` setting in settings.json that allows you to disable our folder results and just use VS Code's local file parsing results, but that won't hide private methods either.

**Comment by sean-mcmanus** [comment]
Without the IntelliSense engine, the context we have available is from the calling point (e.g. if there's a ::, ., or -> before or after) and the ability to filter out different categories of symbols, e.g. if there's a :: on the right the autocomplete will only show things like classes that are able to be scoped. Generally, the current implementation will include too much, and it would only be considered a bug if it excludes symbols it shouldn't (we do have bugs like these, e.g. ::globalFunc and tempConstructedClass() are not found when they should be).

**Comment by janjongboom** [comment]
Thanks @bobbrow @sean-mcmanus. I'll follow #13.
