### ISSUE TITLE
Copying a long value from debug watch results in pasting partial value

### ISSUE THREAD

**Issue by da2r-20** [microsoft/vscode-cpptools#5470]
Type: Debugger

**Describe the bug**
- Version: 1.45.0
- Commit: d69a79b73808559a91206d73d7717ff5f798f23c
- Date: 2020-05-07T15:57:33.467Z
- Electron: 7.2.4
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 18.7.0
- C/C++ Extension Version: 0.27.1

While remote debugging I copied a long value from the watch area.
Pasting it resulted in a partial string with '...' at the end

**To Reproduce**
1. Start a debugging session
2. add an expression that has a long value to watch
![Screen Shot 2020-05-11 at 8 49 26](https://user-images.githubusercontent.com/6897301/81528088-92600380-9364-11ea-9017-deda24d06901.png)
3. Copy value
4. paste it somewhere in a text area
5. the pasted text appears is limited and ends with '...'
![Screen Shot 2020-05-11 at 8 50 33](https://user-images.githubusercontent.com/6897301/81528097-95f38a80-9364-11ea-8bc9-4e66f93b92f3.png)

**Additional context**
Initially I've opened a ticket here microsoft/vscode#97444
I was told to open it here and mention:
>VSCode sents the `clipboard` context when copying. Their extension should set the capability `supportsClipboardContext` and respect the clipboard context by evaluation the full thing.

**Comment by WardenGnaw** [comment]
You can work around this by adding the following to your launch.json with setupCommands or running it in the debug console with `-exec`:
`set print elements 0`.

The correct fix is to run `set print elements 0` before evaluating the request when it is a clipboard context and then reset it back to the value of `show print elements` before we changed it to 0.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders .

**Comment by igiona** [comment]
HI,

I'm facing this very same issue while debugging Rust, as described here into details: https://github.com/rust-lang/rust-analyzer/issues/15619.

VsCode: 1.82.2
CppTools extension: v1.17.5

My launch settings are:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "preLaunchTask": "rust: cargo build",
            "program": "${workspaceFolder}/target/debug/${workspaceFolderBasename}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
        }
    ]
}
```

Any suggestion?
