### ISSUE TITLE
Syntax Highlighting around cout not quite right

### ISSUE THREAD

**Issue by mlekena** [microsoft/vscode-cpptools#5473]
Issue Type: <b>Bug</b>

Simple main.cpp file with code below does not look quite correct. This remains like this even after building and running the application (in case this is a reconfigure build issue)

```cpp
#include <iostream>
#include "chapter1.hpp"

using namespace std;
int main() {
    cout << "String isAllUnique('Hi you!') = " << (chpt1::isAllUnique("Hi you!") ? "True": "False") << endl;
    cout << "String isAllUnique('Hello World!') = " << (chpt1::isAllUnique("Hello World!") ? "True": "False") << endl;
    
    return 0;
}
```
Will attempt to attach an image of what I see
Extension version: 0.28.0-insiders3
VS Code version: Code - Insiders 1.46.0-insider (288852d8c26d797974bfb8aed06e1bff9b809223, 2020-05-12T05:43:31.363Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mlekena** [comment]
![image](https://user-images.githubusercontent.com/4799593/81714948-a3cd0c80-9445-11ea-982b-27f15da61f54.png)

**Comment by sean-mcmanus** [comment]
I'm not able to repro the bug. Does it repro for you after you comment out the `#include "chapter1.hpp"`? It's possible the repro requires the contents of that file.

![image](https://user-images.githubusercontent.com/19859882/81733189-746acf80-9446-11ea-9067-4f1923cb4b23.png)

**Comment by yaroslavsadin** [comment]
I'm experiencing a lot of colorization issues with the latest version as well. It does work initially but eventually when I type something it's not colorized at all. Tag parser works though. All fine again after restart but issue comes back every time.
I tried to rollback vscode version (happened to be updated at the same time) but still the issue is there. Rolling back to previous stable version of cpptools fixes the issue.

**Comment by sean-mcmanus** [comment]
@yaroslavsadin Your issue could be the same root bug as https://github.com/microsoft/vscode-cpptools/issues/5486 . You can confirm by searching your C/C++ logging for "Failed to read" message. I wasn't able to repro that crash with the repro in this bug though (but it's possible the crash is dependent on code in the chapter1.hpp).

**Comment by mlekena** [comment]
After restarting vscode, that same code snippet doesnt reproduce the bug. I am still using vscode-insider and I am on the latest at the moment. So tbh Im not sure if it was silently fixed or is just a non-deterministic bug. Probably the latter.
