### ISSUE TITLE
If browse path not specified project folder path is automatically added

### ISSUE THREAD

**Issue by boocs** [microsoft/vscode-cpptools#5479]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10, 1909
- VS Code Version:  1.45.0
- C/C++ Extension Version: 0.28.0
- Compiler: VS 2019 Build Tools

- If browse path isn't specified the root workspace folder path is auto included. So the root workspace is now tag parsed recursively. To prevent this behavior you'll have to specify a include path and a browse path.

**Steps to reproduce**
This way is the easiest to see.
1. In c_cpp_properties create a blank include path. "includepath": []
2. In c_cpp_properties, create a blank browse path. "path": []
3. In the C++ debug log the desired behavior shows.
4. Remove the browse path from c_cpp_properties.
5. The debug log shows the tag parser recursively going through the entire Workspace directory.
6. This behavior happens even with paths in the include path.

**Expected behavior**
It used to be if you didn't specify a browse path then the include path would be used. 
There was some auto included stuff but nothing to do with workspace directories.

**Comment by sean-mcmanus** [comment]
This is "by design". I get the same behavior with versions as far back as 0.26.3. Do you know what version behaved differently? If you don't specify a browse.path, then the includePath will be copied over to the browse.path, but it will make sure ${workspaceFolder} added as well. The code that does this is at https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/configurations.ts#L606 and that code hasn't changed in over year. Are in the remote scenario with a User setting for C_Cpp.default.browsePath? That got changed to be a remote setting with 0.28.0.

**Comment by boocs** [comment]
I was going by memory and all the testing I was doing from my previous bug report. 

These were from Unreal Engine 4 projects. From previous bug report testing, I definitely remember the tag parser file used to be around 800 MB - 1 gig. Now it's 2 GB with the same settings and takes ~45 minutes to finish tag parsing. If my memory is correct it took half the time before. Maybe less.
I am using this setting:
"C_Cpp.default.browse.limitSymbolsToIncludedHeaders": true

Of course it's a new UE4 engine version, 4.24.3 vs 4.25.0, new VSCode version, and new extension version so it's hard to know anything for sure. 

UE4 does use two workspaces. Maybe the extension changed so it always tag parses both workspaces and it didn't in previous versions?

So the 2 Gig tag parser file could still be a symptom of a change but nothing to do with my first assumption.

**Comment by sean-mcmanus** [comment]
@boocs Yeah, that's it -- as of 0.27.0 the 2 workspace folders share a single database for all the workspaces, and we do a "search/parse" pass on both folders in sequence, whereas before it would use 2 databases and the parsing would occur in parallel (i.e. faster overall time, but using 2 times as much CPU at once). The recommended way to reduce the parsing time is to add files.exclude entries for folders you do not care about parsing for global workspace symbols (if you set the C_Cpp.loggingLevel to "Debug' you can see the files that are getting tag parsed in the C/C++ logging).

**Comment by boocs** [comment]
Ok, thanks for the info!
