### ISSUE TITLE
MIMode 'GDB' should respect 'cwd'

### ISSUE THREAD

**Issue by janjongboom** [microsoft/vscode-cpptools#548]
I'm having trouble getting GDB to find my ELF file on Windows. I now realize why:

**LocalTransport.cs**

```cpp
            // LLDB has the -environment-cd mi command that is used to set the working dir for gdb/clrdbg, but it doesn't work.
            // So, set lldb's working dir to the user's requested folder before launch.
            proc.StartInfo.WorkingDirectory = options.DebuggerMIMode == MIMode.Lldb ? options.WorkingDirectory : miDebuggerDir;

            // On Windows, GDB locally requires that the directory be on the PATH, being the working directory isn't good enough
            if (PlatformUtilities.IsWindows() &&
                options.DebuggerMIMode == MIMode.Gdb)
            {
                string path = proc.StartInfo.GetEnvironmentVariable("PATH");
                path = (string.IsNullOrEmpty(path) ? miDebuggerDir : path + ";" + miDebuggerDir);
                proc.StartInfo.SetEnvironmentVariable("PATH", path);
            }
```

Why is `cwd` only respected with MIMode set to `Lldb`?? I want this for GDB as well. When I change my mode to lldb I can suddenly find my ELF file again (but cannot debug).

**Comment by janjongboom** [comment]
**Note:** This seems to be handled by:

**DebuggedProcess.cs**

```cpp
                    if (!string.IsNullOrWhiteSpace(_launchOptions.WorkingDirectory))
                    {
                        string escapedDir = EscapePath(_launchOptions.WorkingDirectory);
                        commands.Add(new LaunchCommand("-environment-cd " + escapedDir));
                    }
```

But... this code is only executed when you don't have custom setup commands (which I do), but in there I do not have access to the escapedDir, thus running into the issue in #543.

**Comment by pieandcakes** [comment]
@janjongboom Could you add `"-environment-cd"` to your `customLaunchSetupCommands`? We allow for custom setup commands to override our basic behavior, as per our [launch](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md) file. If you want to get around it, use `"setupCommands"` instead of `"customLaunchSetupCommands"` to provide commands in addition to the ones we run.

**Comment by janjongboom** [comment]
@pieandcakes I'd run into the exact same problem... If I do `-environment-cd ${workspaceRoot}` the workspaceRoot is not escaped.

I'll try with `setupCommands` when I'm back in the office next week, but I don't think this is going to work. We need a specific order of GDB commands to connect to a remote target and flash the symbols.

**Comment by janjongboom** [comment]
`-environment-cd` actually worked, without the need to double-escape. So this issue is now solved for me.

Thanks!

**Comment by claynerobison** [comment]
Trying to figure out how this works on Linux. Getting a "System.ArgumentNullException" with:

{ 
      "name": "(gdb) Attach",
      "type": "cppdbg",
      "request": "attach",
      "program": "/usr/bin/python",
      "processId": "${command:pickProcess}",
      "MIMode": "gdb",
      "logging": {
        "exceptions": true,
        "programOutput": true,
        "trace": true
      },
      "setupCommands": [
        { 
          "environment-cd": "${workspaceRoot}"
        }
      ]
    }

**Comment by vinaychandra** [comment]
The following works
```
"customLaunchSetupCommands": [
                {
                    "text": "-environment-cd ${workspaceRoot}"
                },
]
```
