### ISSUE TITLE
[ms-vscode.cpptools]: Menu item references a command 'workbench.action.gotoSymbol' which is not defined in the 'commands' section

### ISSUE THREAD

**Issue by fangguangyang** [microsoft/vscode-cpptools#5489]
**Type: LanguageService**

**Describe the bug**
- OS and Version: win10 + remote-ssh; remoteos: centos7.7
- VS Code Version:1.46.0-insider
- C/C++ Extension Version: 0.28
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. just open vscode
2. See error

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
[ms-vscode.cpptools]: Menu item references a command 'workbench.action.gotoSymbol' which is not defined in the 'commands' section
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/14014903/81885835-cab64a80-95cd-11ea-9d4c-82048c91047d.png)
**Additional context**

**Comment by fangguangyang** [comment]
The previous vscode-insider version did not have this problem, it appear today when I update vscode-insider to the lastest version

**Comment by sean-mcmanus** [comment]
Looks like VS Code Insiders broke us. I'll see if they want us to change something: https://github.com/microsoft/vscode/issues/97774

**Comment by bobbrow** [comment]
The VS Code team committed a fix for this. It should be available soon.

**Comment by ChenYCL** [comment]
same issue.
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by sean-mcmanus** [comment]
@ChenYCL Can you give any more info? Is the C/C++ extension not getting installed correctly?
