### ISSUE TITLE
Add default include paths as a global configuration variable

### ISSUE THREAD

**Issue by kripod** [microsoft/vscode-cpptools#549]
As of now, include paths can only be set for projects by using `.vscode/c_cpp_properties.json`. I think it would be nice to have a global - *overridable* - default for include paths to be checked *(e.g. `C:/MinGW`)*, alongside the project-specific paths.

Project-specific include paths should have higher precedence than global ones.

**Comment by bobbrow** [comment]
#368 and #410 cover this scenario, albeit in slightly different ways.  We haven't decided what exactly we would like to do to enable this scenario at this point, but it's on our radar.
