### ISSUE TITLE
C_Cpp.clang_format_style not working with 0.28.0

### ISSUE THREAD

**Issue by jerinjacobk** [microsoft/vscode-cpptools#5493]
**Type: LanguageService**

**Describe the bug**
- OS and Version: WIndows 10
- VS Code Version: 1.45.0(user_setup_
- C/C++ Extension Version: 0.28.0
- Other extensions you installed (and if the issue persists after disabling them): 
ms-vscode-remote.remote-ssh
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Following setting works/enabled with 0.27.1 version. But when it migrated to 0.28.0, it stops working.

  "C_Cpp.default.cStandard": "c11",
    "C_Cpp.default.includePath": null,
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.clang_format_style": "{ BasedOnStyle: LLVM, IndentWidth: 8, TabWidth: 8, UseTab: Always, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 80, AllowShortFunctionsOnASingleLine: false, AlwaysBreakAfterReturnType: AllDefinitions, ColumnLimit: 80, ConstructorInitializerAllOnOneLineOrOnePerLine: true, ConstructorInitializerIndentWidth: 8, ContinuationIndentWidth: 8, BreakBeforeBraces: Linux, AllowShortBlocksOnASingleLine: false, AlignConsecutiveAssignments: false, AlignEscapedNewlines: Right, AlignConsecutiveMacros : true, MaxEmptyLinesToKeep : 1, Cpp11BracedListStyle : true, AlignTrailingComments : true, ForEachMacros: ['STAILQ_FOREACH', 'rte_graph_foreach_node', 'TAILQ_FOREACH', 'RTE_ETH_FOREACH_DEV']}",

**Steps to reproduce**
Upgrade the extension to 0.28.0 from 0.27.1
- Host PC is Windows 10
- Remote PC: x86 + ArchLinux 

**Expected behavior**

C_Cpp.clang_format_style should work.

**Comment by sean-mcmanus** [comment]
See issue https://github.com/microsoft/vscode-cpptools/issues/5477 . It was a "by design" change so that User settings that were only valid locally wouldn't be applied to the remote machine, i.e. to use the remote settings. Do you think we should change it back to the way it was before?

We changed it due to feedback we received from the VS Code team at https://github.com/microsoft/vscode-cpptools/issues/3774 .

**Comment by jerinjacobk** [comment]
OK. I have updated the settings in remote and it works. 

1. Copy your existing settings that are greyed out.
2. File->Preferences->Settings->Remote.
3. Click the Open Settings icon in the top right.
4. Paste the settings.

Thanks for the support.
