### ISSUE TITLE
"program" issue  (New in VS Code)

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#55]
Hello,

ich have an issue when i try to debug my simple c++ file i got an error:
`Unable to start debugging. Program path 'c:\Users\Zinyra\Desktop\C++\HelloWorld\main.cpp' is missing   or invalid.`

> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "C++ Launch (GDB)",
>             "type": "cppdbg",
>             "request": "launch",
>             "launchOptionType": "Local",
>             "targetArchitecture": "x64",
>             "miDebuggerPath":"c:/mingw/bin/gdb.exe",
>             "program": "${workspaceRoot}/main.cpp",
>             "args": [],
>             "stopAtEntry": false,
>             "cwd": "${workspaceRoot}",
>             "environment": [],
>             "externalConsole": true
>         },

^^^^^^^^^^^^^^^^^
         My launch.json

I don´t know why. I hope anybody can help me.

Thanks !

**Comment by radubacaran** [comment]
Debugging is not yet supported on windows. See here: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

**Comment by ghost** [comment]
On the side below:

 **Windows**

Debugging on Windows is currently only supported for Cygwin and MinGW.

**Comment by radubacaran** [comment]
Oh, I missed that completely. Now I notice they use backslashes instead of slashes for the path. Maybe try that and see if it works

`
User must manually set the path to GDB in launch.json if gdb is not on the path. For example: "miDebuggerPath":"c:\mingw\bin\gdb.exe" or "miDebuggerPath":"c:\cygwin64\bin\gdb.exe"
`

**Comment by ghost** [comment]
Thanks for the awsner. I already set the
 `"miDebuggerPath":"c:/mingw/bin/gdb.exe",`

See it in my first post here.

I think the error is in the "program" section

**Comment by radubacaran** [comment]
I was suggesting
using
`"miDebuggerPath":"c:\mingw\bin\gdb.exe",`
instead of
`"miDebuggerPath":"c:/mingw/bin/gdb.exe",`

It's a longshot, but maybe that will work...

**Comment by ghost** [comment]
Nope now i got an error:

`Unable to start debugging. Launch options string provided by the project system is invalid. ",hexadecimal value 0x08, is an invalid character. Line 6, Position 25.`

**Comment by radubacaran** [comment]
Dumb question, do you have version 
`Version 0.6.0: May 24, 2016
...
Support for debugging with GDB on Cygwin.`
For me at least, the extension repo still offers 0.5.0 to install.

**Comment by ghost** [comment]
I think i have instaled the version 0.6.0, I take a look later.

Edit: Yes i have the version 0.6.0

**Comment by delmyers** [comment]
@Zinyra 
There is currently a bug in the readme. The markdown didn't escape backslashes as expected. You will have to do the following:

"miDebuggerPath":"c:\\cygwin64\\bin\\gdb.exe"

Also, if you are going to debug with Cygwin, your application must have been compiled with Cygwin. You won't be able to compile MVC compiled binaries with Cygwin, for example.

**Comment by jacdavis** [comment]
Also, it looks like your program is set to ${workspaceRoot}/**main.cpp** Is it a mistake? It looks like you are pointing it to a source file instead of a compiled binary.

**Comment by ghost** [comment]
Yes, i thougt the extension will compile my .cpp file to an program.
Can you tell me exactly what i must do ?

**Comment by jacdavis** [comment]
You need to compile it with Cygwin's GCC/G++ compiler. If it is a single source file, open the Cygwin console, and type something like this from the folder where your source is:
g++ -g main.cpp
This will produce a debug build of the source file named a.exe in that folder. Note that if you have more than one file, or want other options, this gets more complex.

**Comment by ghost** [comment]
Okay i have compiled the file now i have an executable. So now i tried to launch it in Visual Code.

But in the launch.json is the type wrong.       "type": "cppdbg",

**Comment by jacdavis** [comment]
"type":"cppdbg" is correct. Did you change program to point to a.exe?

**Comment by ghost** [comment]
Yes.

This is the error message.
`Unable to start debugging. Launch options string provided by the project system is invalid. ",hexadecimal value 0x08, is an invalid character. Line 6, Position 28.`

**Comment by jacdavis** [comment]
Can you please attach you launch.json file here exactly as-is so I can take a look?

**Comment by ghost** [comment]
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "C++ Launch (GDB)",
>             "type": "cppdbg",
>             "request": "launch",
>             "launchOptionType": "Local",
>             "targetArchitecture": "x64",
>             "miDebuggerPath":"c:\cygwin64\bin\gdb.exe",
>             "program": "${workspaceRoot}/a.exe",
>             "args": [],
>             "stopAtEntry": false,
>             "cwd": "${workspaceRoot}",
>             "environment": [],
>             "externalConsole": true
>         },
>         {
>             "name": "C++ Attach (GDB)",
>             "type": "cppdbg",
>             "request": "launch",
>             "launchOptionType": "Local",
>             "targetArchitecture": "x64",
>             "program": "enter program name, for example ${workspaceRoot}/a.out",
>             "args": [],
>             "stopAtEntry": false,
>             "cwd": "${workspaceRoot}",
>             "environment": [],
>             "processId": "enter program's process ID",
>             "externalConsole": false
>         }
>     ]
> }

**Comment by jacdavis** [comment]
Try double backslashes in the gdb path like this
"miDebuggerPath":"c:\\cygwin64\\bin\\gdb.exe",

**Comment by ghost** [comment]
Now i have this issue. 

> Unable to start debugging. The value of miDebuggerPath is invalid

**Comment by jacdavis** [comment]
Is that the correct path to where you have Cygwin gdb installed? If not, please verify you have Cygwin installed and have installed gdb through the Cygwin package manager.

**Comment by ghost** [comment]
I had downloaded Cygwin there   https://www.cygwin.com

And the cygwin64 folder is on c

**Comment by jacdavis** [comment]
I believe Gdb is not installed by default with cygwin. You need to use the Cygwin package manager to install it. If you do dir c:\cygwin64\bin\gdb.exe
does it say it is there?

**Comment by ghost** [comment]
Oh no..... I don´t see it.. I reinstall Cygwin at the moment.  Thanks for the tipp!
I  report later the status

**Comment by jacdavis** [comment]
When you install it, the installer will ask you which packages to install. You'll want to search for gdb. I believe the package is called Devel or something similar to that.

**Comment by ghost** [comment]
I selected install all.

**Comment by ghost** [comment]
Worked thanks.

But i have a question. Will the extension later support that feature without all that programs ? And can i compile my file later with the extension ?

**Comment by jacdavis** [comment]
Thanks for the feedback!

You can configure vscode to compile using Tasks. It isn't as automatic as it would be in IDE like the free Visual Studio Community. 
This page goes through the details. https://code.visualstudio.com/Docs/editor/tasks

**Comment by sridmad** [comment]
Closing as the original issue is resolved

**Comment by sridmad** [comment]
and @jacdavis, answered the question about setting up build tasks

**Comment by lifuguan** [comment]
Thanks! I've solved the same problem following your advice.
