### ISSUE TITLE
#include errors detected. Please update your includePath. 

### ISSUE THREAD

**Issue by datechnomadmole** [microsoft/vscode-cpptools#5501]
Type: IntelliSense 

Describe the bug

    OS and Version:Windows 10 1909
    VS Code Version:1.44.2
    C/C++ Extension Version:0.28
    Other extensions you installed (and if the issue persists after disabling them):

I have a simple two function one file C program.  It compiles and links without errors.  Since the new release of ms-vscode.cpptools 0.28 I get squiggly lines under my standard C header include statements.  Nothing else has changed.  I assumed the standard  Include paths for Microsoft C++ are set and I am running VSCode from the Developer Powershell.

It is the same in another, similarly simple one file, one function C program.

In the docs it says "You only need to add to the Include path array setting if your program includes header files that are not in your workspace or in the standard library path."  and this was the case before.

![image](https://user-images.githubusercontent.com/39510314/82040470-409cdd80-96c4-11ea-833c-5c8e881b4614.png)

PS D:\Users\damole\Documents\tech\dev\src\substitution> ls env:* -Include INCLUDE | Format-List

Name  : INCLUDE
Value : C:\Program Files (x86)\Microsoft Visual
        Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual
        Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include;C:\Program Files (x86)\Windows
        Kits\10\include\10.0.18362.0\ucrt;C:\Program Files (x86)\Windows
        Kits\10\include\10.0.18362.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um;C:\Program
        Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt;C:\Program Files (x86)\Windows
        Kits\10\include\10.0.18362.0\cppwinrt

**Comment by sean-mcmanus** [comment]
Can you run C/C++: Log Diagnostics (from the Command Palette) and check if those system headers are being used or not?

**Comment by datechnomadmole** [comment]
`-------- Diagnostics - 16/05/2020, 17:44:17
Version: 0.28.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "D:\\Users\\damole\\Documents\\tech\\dev\\include"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compilerPath": "",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "D:\\Users\\damole\\Documents\\tech\\dev\\include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\Users\damole\Documents\tech\dev\src\substitution\substitution.c ]:
    D:\USERS\DAMOLE\DOCUMENTS\TECH\DEV\SRC\SUBSTITUTION\SUBSTITUTION.C
Translation Unit Configurations:
[ D:\Users\damole\Documents\tech\dev\src\substitution\substitution.c ]:
    Process ID: 9288
    Memory Usage: 10 MB
    Includes:
        D:\USERS\DAMOLE\DOCUMENTS\TECH\DEV\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c11
    IntelliSense Mode: msvc-x64
Total Memory Usage: 10 MB

`

**Comment by datechnomadmole** [comment]
In this project I am using a custom library so I have to the include path in c_cpp_properties.json for Intellisense and in tasks.json so it will compile.

from tasks.json:

{
    "version": "2.0.0",
    "options":{
        "env":  {
                "INCLUDE":  "${env:INCLUDE};D:\\Users\\damole\\Documents\\tech\\dev\\include",
                "LIB":      "${env:LIB};D:\\Users\\damole\\Documents\\tech\\dev\\lib"
        }
    },

My other project doesn't have a custom include path set but has the same problem.

**Comment by sean-mcmanus** [comment]
We had a bug that caused `compilerPath: ""` to not be handled that got fixed with 0.28.0. Does removing the `compilerPath: ""` fix your issue? i.e. using the `compilerPath: ""` will intentionally cause the cl.exe and Windows include paths to be not be included.

**Comment by datechnomadmole** [comment]
One of the projects doesn't have c_cpp_properties.json and the other that does never had compilerPath: set.

From the docs:

"compilerPath (optional) The full path to the compiler you use to build your project, for example /usr/bin/gcc, to enable more accurate IntelliSense. The extension will query the compiler to determine the system include paths and default defines to use for IntelliSense.."

How does this query work exactly?

**Comment by datechnomadmole** [comment]
I rolled back to 0.27.1 and the squiggles go away.

Here is the log diagnostics:

-------- Diagnostics - 28/05/2020, 19:06:33
Version: 0.27.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "D:\\Users\\damole\\Documents\\tech\\dev\\include"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "D:\\Users\\damole\\Documents\\tech\\dev\\include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.

-------- Diagnostics - 28/05/2020, 19:07:02
Version: 0.27.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "D:\\Users\\damole\\Documents\\tech\\dev\\include"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "D:\\Users\\damole\\Documents\\tech\\dev\\include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\Users\damole\Documents\tech\dev\src\substitution\substitution.c ]:
    D:\USERS\DAMOLE\DOCUMENTS\TECH\DEV\SRC\SUBSTITUTION\SUBSTITUTION.C
Translation Unit Configurations:
[ D:\Users\damole\Documents\tech\dev\src\substitution\substitution.c ]:
    Process ID: 26192
    Memory Usage: 18 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
    Includes:
        D:\USERS\DAMOLE\DOCUMENTS\TECH\DEV\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.25.28610\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.25.28610\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c11
    IntelliSense Mode: msvc-x64
Total Memory Usage: 18 MB

**Comment by sean-mcmanus** [comment]
Your log diagnostics originally showed "compilerPath": "". Your latest one doesn't show that. I'm not able to repro any bug with 0.28.1 when using the latest c_cpp_properties.json from you logs, i.e. I get the same results that you do with 0.27.1.

Yes, compilerPath shouldn't be needed, i.e. we should auto-select a cl.exe compiler if you have one. The setting of compilerPath to "" will overwrite that auto-selection though.

**Comment by datechnomadmole** [comment]
My c_cpp_properties.json doesn't have "compilerPath": but the debug outpuit shows it.  So I added "compilerPath": and set it correctly and the squiggles go away.

I'm attached an image of the debug showing the "compilerPath": that doesn't exist.

![compilerPath_ghost](https://user-images.githubusercontent.com/39510314/84899097-d6fa5f80-b0c5-11ea-848f-e763744f86ab.PNG)

**Comment by datechnomadmole** [comment]
At some point when I was going through the settings I clicked on "compilerPath": "" in the global settings which added that to the settings.json.  I just removed it and the problem is resolved.  Thanks for pointing me in the right direction.
