### ISSUE TITLE
Compile multiple .c and .h files

### ISSUE THREAD

**Issue by mich2k** [microsoft/vscode-cpptools#5502]
clang / gcc

- OS and Version: Ubuntu 20.04
- VS Code Version: 1.6.0
- C/C++ Extension Version: latest

Hello, i know that his is something vscode / tasks,json related
but is there a way / setting to compile multiple source and header files without doing it manually from the console?
thank you

**Comment by WardenGnaw** [comment]
You can convert what you type in your console to be a task.json shell command:

E.g. if you are typing
`g++ -g file1.cpp file2.cpp subfolder/file.cpp subfolder1/subfolder2/cpp -o a.out`

The equivalent task.json is:
```
{
		"type": "shell",
		"label": "compile",
		"command": "g++",
		"args": [
			"-g",
			"file1.cpp",
			"file2.cpp",
			"subfolder/file.cpp",
			"subfolder1/subfolder2/file.cpp",
                        .....
			"-o",
			"a.out"
		]
}
```

You can reference this task in your launch.json with the "prelaunchtask" field.

**Comment by mich2k** [comment]
Thank you, but since I use one .vscode for all my projects I should add manually all the file names
is there a wildcard way to do this?
like, *.c *.h

**Comment by WardenGnaw** [comment]
You can use wildcards. 

`g++ -g *.c` would be:
```
{
   "command": "g++",
   "args": [
      "-g",
      "*.c"
   ]
}
```

**Comment by mich2k** [comment]
this is my tasks.json at the moment:
```{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "clang debug & exec",
			"command": "/usr/bin/clang",	
			"args": [
				"-g",
				"${fileDirname}/*.c",	
				"-o",
				"${fileDirname}/${fileBasenameNoExtension}.out"
			],
			"options": {
				"cwd": "/usr/bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": "build"
		}
	]
}



output 

clang: error: no such file or directory: '/home/mich/Scrivania/UNI/Fond-INF-2/Training/Struttura Gen. Liste/*.c'
clang: error: no input files

**Comment by WardenGnaw** [comment]
Your filepath has a space (` `) in it, so you will need to surround the full command in quotes, but doing so will escape the `*` and it will not be used as a wildcard.

I cant seem to find a way to escape the spaces in ${fileDirname}, but that will fix the command.

**Comment by mich2k** [comment]
Removing the spaces actually did the trick, thank you very much!
