### ISSUE TITLE
Attach to Running Process

### ISSUE THREAD

**Issue by dfarley1** [microsoft/vscode-cpptools#5504]
Type: Debugger

**Describe the bug**
- OS and Version: Host ==Ubuntu 20.04, Target == Gentoo
- VS Code Version: 1.45.0
- C/C++ Extension Version: 0.28.0
- A clear and concise description of what the bug is.

I'm attempting to remote debug a process running on another machine. The process is running as root using respawn so I start gdbserver with `sudo gdbserver --attach :9091 $(pidof process)`.

I'm using the following launch target:
```
{
    "name": "process - attach",
    "type": "cppdbg",
    "request": "attach",
    "program": "/depot/out/cur/process",
    "args": [],
    "stopAtEntry": false,
    "cwd": "/depot",
    "environment": [],
    "externalConsole": false,
    "MIMode": "gdb",
    "miDebuggerServerAddress": "remote-target:9091",
    "setupCommands": [
        {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
        },
        {
            "description": "Set sysroot to use local symbols",
            "text": "set sysroot /",
            "ignoreFailures": true
        },
        {
            "description": "Set solib-search-path to use local symbols",
            "text": "set solib-search-path /depot/out/cur/debug",
            "ignoreFailures": true
        }
    ],
    "logging": {
        "trace": true,
        "traceResponse": true,
        "engineLogging": true
    }
}
```
This gives me the error: `attach: unable to parse the process id`

So I added `"processId": 1234` given by gdbserver to the launch config above. Now I get the error `attach: 'processId' cannot be used with miDebuggerServerAddress`. There is no output in the Debug Console or any of the log tabs. How do I get this working?

I briefly tried to use `"request": "launch"` which works except that it kills the process when I stop the debugger.

As a secondary question: Is there a way to have VSCode start gdbserver on the remote target automatically?

**Comment by WardenGnaw** [comment]
If you have `miDebuggerServerAddress` set, you should already have gdbserver that launched the process. There is no need to provide the process id unless you are trying to attach with another GDB.

>As a secondary question: Is there a way to have VSCode start gdbserver on the remote target automatically? 

There may be a way to do this via task.json but I have not personally tried.

**Comment by dfarley1** [comment]
> There is no need to provide the process id unless you are trying to attach with another GDB.

I figured that was the case, I'm just trying everything since it seems like this should work.

> There may be a way to do this via task.json but I have not personally tried.

While looking into debgger settings I found `preLaunchTask` ([link](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes)) so that should be able to do what I want.
