### ISSUE TITLE
Debugger doesn't show all application threads

### ISSUE THREAD

**Issue by bkonelson** [microsoft/vscode-cpptools#5505]
I'm trying to debug an MPI program by attaching gdb to all of the created processes.  When I run the debugger, I can select which process to attach to, and it shows all 4 processes.  After I select it though, the call stack only shows 3 of the processes in the debugger. When I pause the execution, it says that all 3 processes are paused, but I don't think this is the case. I notice in the output from 'top' that it is only pausing the execution of the process that I selected. 
  1) Shouldn't it show all of the processes in the call stack?
  2) Shouldn't it pause execution on all the actual processes?

Here is my  launch.json:
`{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Debug exec1",
			"type": "cppdbg",
			"request": "attach",
			"program": "/home/trunk/exec1",
			"processId": "${command:pickProcess}",
			"MIMode": "gdb",
			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			]
		},
		{
			"name": "Debug exec2",
			"type": "cppdbg",
			"request": "attach",
			"program": "/home/trunk/exec2",
			"processId": "${command:pickProcess}",
			"MIMode": "gdb",
			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			]
		}

	]
}`

**Comment by WardenGnaw** [comment]
> Shouldn't it show all of the processes in the call stack?

It should show all of the processes you connected to via `launch.json`, and child processes spawned or created do not get automatically attached.

> Shouldn't it pause execution on all the actual processes?
![image](https://user-images.githubusercontent.com/3953714/82100779-80ad9180-96bf-11ea-9a4f-52079ab91540.png)

Debug actions only affect the active debug session. One process is one debug session. 

https://code.visualstudio.com/docs/editor/debugging#_multitarget-debugging
