### ISSUE TITLE
Not all C++ keywords are color coded

### ISSUE THREAD

**Issue by rtve** [microsoft/vscode-cpptools#551]
I have noticed that not all C++ keyword are color coded.  Keyword such as sizeof, static_cast, dynamic_cast, and reinterpret_cast are not color coded.

**Comment by bobbrow** [comment]
This is a vs code issue.  I moved it to their repository. https://github.com/Microsoft/vscode/issues/22419

**Comment by sean-mcmanus** [comment]
The "bug" is that the default VS Code theme is making the color the same as normal text. Themes like Monokai don't repro the issue. They say the bug is with whatever theme you're using. See https://github.com/atom/language-c/issues/151 .
