### ISSUE TITLE
Defines and includes are not parsed from compilerPath or compilerArgs

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#5512]
Defines and includes are not parsed from compilerPath or compilerArgs, in c_cpp_properties.

Args are stripped from compilerPath.  This would seem to imply a simple way to configure the extension would be to paste in a fully populated compilation command line to compilerPath..  However, args gathered from the command line are used as args only.  If they contain defines and/or includes, the extension does not use them.

Args from compilerPath are handled the same way as compilerArgs.  So, handling defines and includes in compilerArgs would seem to handle both cases.  This parsing is already being done in handling of compile_commands.json.

**Comment by magdumnikhil** [comment]
Will the possible fix include issue reported in #4868 ?

**Comment by sean-mcmanus** [comment]
@magdumnikhil It doesn't seem like it would be.

**Comment by Colengms** [comment]
Note that this is currently only an issue for compilers we don't probe (CL.exe).  Because we are not stripping defines/includes when we probe a (gcc/clang) compiler, they are round-tripped through the probe and parsed as system defines/includes.  They should be removed from the probe as they aren't relevant to it, so this will also need to be addressed to do that.
