### ISSUE TITLE
include definition parser doesn't recurse as much as the code ifdef parser?

### ISSUE THREAD

**Issue by marcmerlin** [microsoft/vscode-cpptools#5514]
As requested by @sean-mcmanus  in https://github.com/microsoft/vscode-cpptools/issues/510

**Describe the bug**
- OS and Version: debian 10 / amd64
- VS Code Version: 1.45.0-1588868285
- C/C++ Extension Version: 

I open my code and get a warning about missing application.h.
cannot open source file "application.h" (dependency of "GifAnimViewer.h")

After clicking 5 files deep, I arrive in this file:
![image](https://user-images.githubusercontent.com/1369412/81527514-52226600-930f-11ea-8a3d-131d2b8f6582.png)
By the way, I should add that it was a bit painful to go file into file into file with F12 until I got to the correct file that was including application.h. I'm not sure if I missed a shortcut, but if not there should be one.

I then modified it to say
```
#elif defined (SPARK)
#error can't be here
#include "application.h"
#endif
```
while added the #error line to prove that the block wasn't defined, the workspace problem went away.

It looks like the source scanner that parses #define doesn't run as many files deep as the source scanner that computes blocks of code that are active/ifdef'ed out, giving me the warning until I went deep enough into the file for the file to be parsed, colorized and the warning to go away on its own.

Hope this helps.

Let me know if I can provide more relevant info. Given that I don't have an error anymore, I'm not sure if there are relevant logs to capture?

You can get the code here if it's easier for you to throw into your version of the code:
https://github.com/marcmerlin/NeoMatrix-FastLED-IR
The warning happens over line 37:
#include "GifAnimViewer.h"

**Comment by sean-mcmanus** [comment]
Yeah, if I could get a repro that would be good. I tried to use your repro project, but I seem to have configuration issues, e.g. I don't see code that uses "#elif defined (SPARK)". Do I need Arduino setup somehow?

If you could run C/C++: Log Diagnostics that would help as well.

**Comment by marcmerlin** [comment]
Hi sean, sorry , yes, arduino uses libraries and sub-libraries that get automatically installed if one uses platformio (so I'm told) but need to be installed manually otherwise.
That said in this case, the bit of code is in LzwDecoder_Impl.h (demos/AnimatedGIFS) which will get populated if you do a git submodule init as per the readme. You'll still be missing sub-libraries but at least you'll get the file with the defined(SPARK)
Repro/logs, I'll try to get that for you, but right now the problem has gone away and it seems that having LzwDecoder_Impl.h  open in a buffer is enough to make the issue go away. My guess is that the recursion doesn't go far enough, or something gets evicted from an LRU cache.
Sorry that I don't have anything more helpful for now, maybe the git submodule will get you enough source to repro this on your side.

**Comment by marcmerlin** [comment]
I forgot to add that despite this minor issue, coming from 30 years of vim only, vscode is quitte nice, especially with the plugin support, thanks to al the teams involved on making it reality.

**Comment by sean-mcmanus** [comment]
I'm still not able to repro the issue. I'm seeing ARDUINO defined via the compilerArg in the c_cpp_properties.json. What are the exact repro steps in regards to which files are opened?
