### ISSUE TITLE
[cppvsdbg] Skip standard C++ files after Step Into

### ISSUE THREAD

**Issue by csorvagep** [microsoft/vscode-cpptools#5516]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 (1909)
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.0
- Other extensions you installed (and if the issue persists after disabling them): cmaketools (1.3.1)

After hitting F11 (step into) the debugger steps into the next function. But if there is an intermediate  standard library function (e.g. shared_ptr dereference), debugger should skip it.
GDB can use skip these files. Is it possible to configure cpptools to do so?

**To Reproduce**
Project was generated with cmaketools Quick Start option
```
#include <iostream>

class a
{
public:
    double b() { return 3.0; }
};

int main(int, char**) {
    std::shared_ptr<a> aPtr = std::make_shared<a>();
    std::cout << aPtr->b();
}
```
launch.json is generated with default (Windows) Launch configuration

**Comment by csorvagep** [comment]
I tried CMake's variable (CMAKE_VS_JUST_MY_CODE_DEBUGGING) for setting the /JMC option in the compiler. After generateing Visual Studio Project files it works with Visual Studio but not with Code. I also tried creating a natstepfilter file but that does not work either.

**Comment by Trass3r** [comment]
JMC requires debugger support for the `__CheckForDebuggerJustMyCode` hooks.

**Comment by konradsa** [comment]
You can achieve that by adding the following to the gdbinit file:

```
skip -gfi /usr/include/c++/*/*/*
skip -gfi /usr/include/c++/*/*
skip -gfi /usr/include/c++/*
```

**Comment by Trass3r** [comment]
It looks like the OP uses the VS debugger though.

**Comment by konradsa** [comment]
> It looks like the OP uses the VS debugger though.

My bad, didn't see that.

**Comment by khlebnikov** [comment]
Note that `/JMC` is often much more useful than gdb's `skip`, specifically for cases like stepping into a `std::function`: `/JMC` will step into the (user) function bound to `std::function` bypassing all the cruft of `std::function` itself.

**Comment by csorvagep** [comment]
Just found out, there's a "justMyCode": true option in the launch.json.
