### ISSUE TITLE
Press space key when select multi-lines

### ISSUE THREAD

**Issue by vscpp** [microsoft/vscode-cpptools#552]
For coding style reason, sometimes, we need a backspace for multi-lines.
Currently, when select multi-lines, press space key, the codes deleted.
When press Tab key for multi-lines, the function is fine.
Will you improve this feature? Thanks.

**Comment by sean-mcmanus** [comment]
I don't understand what you are asking for. Backspace, space, and tab with multiple lines selected is controlled by VS Code itself and not our extension, and it appears to be working "by design". Can you post your feature request to https://github.com/Microsoft/vscode/issues ?

**Comment by bobbrow** [comment]
It sounds like @vscpp is asking for an indentation feature.  But yes, our extension would not be able to control that.  We don't get keystroke messages from VS Code.  If you would like to request this feature, please go to the link @sean-mcmanus shared.

**Comment by sean-mcmanus** [comment]
Yeah, maybe he's asking for indentation via one space at a time? We might be able to send a workspace/applyEdit in the didChange to implement this, but it doesn't seem like it belongs in the C++ extension. Someone could write their own extension to do this.

**Comment by vscpp** [comment]
Yes, this is indentation function via one space at a time for multiple lines.
It is helpful for coding style. Source Insight supports it. And seems Visual Studio doesn't support it, either.

**Comment by sean-mcmanus** [comment]
@vscpp Can you file a feature request with VS Code? https://github.com/Microsoft/vscode/issues ?

**Comment by vscpp** [comment]
Thanks, @sean-mcmanus, I filed a request to VS code just now. :)
