### ISSUE TITLE
Add code folding for multiline macros

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5524]
I've filed a feature request on VS at https://developercommunity.visualstudio.com/idea/1020490/c-intellisense-add-code-folding-for-case-regions.html .

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode-cpptools/issues/407#issuecomment-624988706_

**Comment by Colengms** [comment]
@sean-mcmanus The link is for https://github.com/microsoft/vscode-cpptools/issues/5523 and doesn't mention macros.  Is there another link?  Maybe: https://developercommunity.visualstudio.com/t/C-IntelliSense:-Code-folding-works-in/1021278

**Comment by sean-mcmanus** [comment]
Seems like this is a duplicate of https://github.com/microsoft/vscode-cpptools/issues/5525 .
