### ISSUE TITLE
Code folding works in a macro definition with "if() {" but stops if the { is on a new line

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5525]
I've filed VS bug https://developercommunity.visualstudio.com/content/problem/1021278/c-intellisense-code-folding-works-in-a-macro-defin.html .

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode-cpptools/issues/407#issuecomment-625120818_

**Comment by bobbrow** [comment]
The linked feedback ticket was closed with "lower priority" so it is unlikely that we will get a fix for this.
