### ISSUE TITLE
[loc][Query][vscode_extensions] Localizability of string

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cpptools#5526]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer Needed By
-- | -- | -- | -- | -- | --
49,837 | Src\vscode-extensions\vscode-cpptools.xlf | 0;   "./src/main.native.binaries.not.supported" | This {0} version of the   extension is incompatible with your OS. Please download and install the   "{1}" version of the extension. | Can you please explain the   contents of the first placeholder in this string? We assumed it indicates the   version number. |

**Comment by WardenGnaw** [comment]
`{0}` will be the Operating System name. It will be one of the following: `Windows`, `MacOS` or `Linux`.
https://github.com/microsoft/vscode-cpptools/blob/7ab06da098f3a424ad055150123d71b89a02e62e/Extension/src/platform.ts#L17-L21

**Comment by PDostalek** [comment]
thank you for reply @WardenGnaw
