### ISSUE TITLE
Server connection closed when using Clang-format extension

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5528]
# I have the same problem
* version:`April 2020 (version 1.45)`
 * `macos ,clang-format version 10.0.0`
* I don't confirm the exactly steps to reproduce it, but the happened time  is that I use the clang-format extension to format my cpp files on save.what's more ,I can not use the format on save when the error has happened.
* the error information as follows:
 ![image](https://user-images.githubusercontent.com/10096544/82153220-c07ba100-9898-11ea-927e-9e567df07a7d.png)

- yeah: sometimes ,I uninstall  and re-install the Clang-Format and cpptools extension, the issue can be solved for a while after un-re install the extension, but the issue happens after a while.
- the Clang-Format extension version is 1.9.0
- the cpptools extension version is 0.28.0

![image](https://user-images.githubusercontent.com/10096544/82337187-1168d200-9a1e-11ea-88d3-9abd9efa8072.png)
![image](https://user-images.githubusercontent.com/10096544/82337820-c1d6d600-9a1e-11ea-886e-1fcff3b350b0.png)

_Originally posted by @LIUHUANUCAS in https://github.com/microsoft/vscode-cpptools/issues/4770#issuecomment-630853364_

**Comment by michelleangela** [comment]
@LIUHUANUCAS 

It seems that Clang-Format extension is affecting the C/C++ extension. That is when VS Code sends a format document request, either the Clang-Format extension or C/C++ extension will handle the formatting.

The C/C++ extension ships with Clang-format capabilities. You can set the C/C++ extension to use a specific Clang-format executable by setting `"C_Cpp.clang_format_path"` in settings.json and disable the Clang-Format extension. Could you try this and see if it still affects the C/C++ extension?

**Comment by LIUHUANUCAS** [comment]
@michelleangela Thanks a lot! it works after uninstall Clang-format extension!

**Comment by michelleangela** [comment]
Closing as resolved.
