### ISSUE TITLE
[OS X]Breakpoint triggered in a newly opened editor other than the opened editor in which the breakpoint is set.

### ISSUE THREAD

**Issue by lippens** [microsoft/vscode-cpptools#553]
I'm using Code 1.10.1 with CppTools 0.10.3 on macOS Sierra 10.12.3.
After configuring the "lauch.json" and "task.json", I first set a breakpoint at main():10 in an opened editor "main.cpp", and then switch to Debug mode, hit the "Start debugging", the debugger works well, but the program breaks at main():10 in a newly opened editor "_main.cpp_". 
It seems to be very strange to me that the Debugger or the CppTools extension opens another editor, but ignores the editor that has already been opened. 
P.S.
I set the property "window.openFilesInNewWindow" to "Default".

1. Is this scenario works "right"?
2. How to fix it?

**Comment by pieandcakes** [comment]
@lippens This could be two things: 1) the path casing is different in one file versus the other. If you hover over the tab, you should be able to see if the casing is exactly the same or not. 2) This could be that the source at compile time is different than then one you have open and you have the same source file in two locations. 

We pass the path back to VSCode and VSCode's editor opens the file. If you can help narrow down which one it is, it would probably be something to ask [VSCode](https://github.com/Microsoft/vscode/issues) to fix. 

Please let me know what you find.

**Comment by lippens** [comment]
Well, I updated the VS Code to 1.10.2 and reinstalled cpptools, the problem seems to be gone away. Probably it is something that VSCode has fixed.

**Comment by lippens** [comment]
Sorry for closed the issue by mistake.

The two tabs indicated the path, and what's more, It seems that the VS Code or the CppTools treated the two editor as two different files or something else. 

I will refer "main.cpp" to the editor I opened in "Editing" view mode, and "_main.cpp_" to the editor opened automatically in "Debugging" view mode. Here is what I found:
1. "main.cpp" and "_main.cpp_" all refer to the same file with the same path casing.
2. The breakpoints set in "main.cpp" cannot be seen in "_main.cpp_", and vise versa.
3. I relaunched the VS Code and opened the source folder, I found two editor opened with tab title "main.cpp", this cannot be done by double click on the file in the file explorer, only one editor will be opened in that case.
4. After closing both of the editors, I double clicked the main.cpp in the file explorer, an editor with title "main.cpp" showed up, but the breakpoints set in "Debugging" view mode cannot be seen.
5. Switch to "Debugging" view mode, and click any one of the breakpoints which is originally set in "Debugging" view mode, an editor with title "_main.cpp_" is opened, if you double click on the breakpoint, the title will change from "_main.cpp_" to "main.cpp", which is odd.

For comparison, I tested this with the Python extension, and things seem to be OK with that. So I think this may not be some problem caused by VS Code.

**Comment by lippens** [comment]
I upgraded VS Code to 1.10.2 this morning, and tested with a simple program which contains only one file main.cpp, and everything works OK. And then I reopened my project which contains several .hpp and the main.cpp, and the tests fails.
So if any of you want to reproduce the scenario, an simple main.cpp program will be insufficient, I guess.

**Comment by kevinmoran** [comment]
I also have this issue, reported it in #473

I run my source on Windows and Mac, both running same VSCode version. Only happens on Mac.

**Comment by WardenGnaw** [comment]
This should be resolved in v1.1.0 with `sourceFileMap` and set `useForBreakpoints` to be true.
