### ISSUE TITLE
colorization when editing

### ISSUE THREAD

**Issue by culyee** [microsoft/vscode-cpptools#5532]
I have been developing a extension about colorization, and I have met a problem that I cannot solve, the question is described as followed. I wonder have you ever been meeting such problem?

In my extension, local variable is orange:

![image](https://user-images.githubusercontent.com/56422381/82419782-69044d80-9ab1-11ea-9706-9f0ac1c2c427.png)

but after removing the code `int a=0;` and inputting new code `double b;`, the contents are all orange, including `double`  and `;`

![image](https://user-images.githubusercontent.com/56422381/82419919-9b15af80-9ab1-11ea-9a76-936fcdd767cb.png)

when I saved test.h, the color turns normally

![image](https://user-images.githubusercontent.com/56422381/82419991-b84a7e00-9ab1-11ea-8813-723570bce1d1.png)

**Comment by michelleangela** [comment]
@culyee 

Just to clarify, are you creating your own extension that will apply colorization to C/C++ code? Or is this a question on using [colorization in Microsoft C/C++ extension](https://code.visualstudio.com/docs/cpp/colorization-cpp)?
