### ISSUE TITLE
VS Code (Ubuntu) - miDebuggerPath is invalid.

### ISSUE THREAD

**Issue by paxth** [microsoft/vscode-cpptools#5534]
Type: Debugger

When I try to use my debugger, I get the error showing:
Unable to start debugging. The value of miDebuggerPath is invalid.
![Screenshot from 2020-05-20 16-26-10](https://user-images.githubusercontent.com/63995679/82440460-f481dc80-9ab9-11ea-8f68-eab621115ffd.png)

- OS and Version: Ubuntu 20.04 LTS
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.0
- Other extensions you installed (and if the issue persists after disabling them): C++ Intellisense 0.2.2

Here is my launch.json
![Screenshot from 2020-05-20 16-59-18](https://user-images.githubusercontent.com/63995679/82441325-63136a00-9abb-11ea-98ab-5a008bb3c86e.png)

Any idea how do i fix it?

**Comment by WardenGnaw** [comment]
Does `/usr/bin/lldb-mi` exist?

**Comment by paxth** [comment]
I cant find that. Does that mean it's missing?

**Comment by sean-mcmanus** [comment]
It hit the same issue with MIMode "gdb" -- installing gdb fixed it.

**Comment by WardenGnaw** [comment]
@paxth Are you looking to use `clang/lldb` for build and debugging on Ubuntu 20.04 LTS? You will need to downgrade to clang/lldb 9 in order to get `lldb-mi`. 

lldb-mi has been removed from lldb and now Ubuntu will not build it independently and ship it: See https://github.com/microsoft/vscode-cpptools/issues/5415

If you can switch to `g++/gdb`, that will work in Linux scenarios.

**Comment by zipzit** [comment]
```
 "MIMode": "gdb",
 . . .
  "preLaunchTask": "shell: g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
```
this works for me...

**Comment by paxth** [comment]
> ```
>  "MIMode": "gdb",
>  . . .
>   "preLaunchTask": "shell: g++ build active file",
>             "miDebuggerPath": "/usr/bin/gdb"
> ```
> 
> this works for me...

Do i need to compile using gcc now or can i use clang too?

**Comment by sean-mcmanus** [comment]
@paxth Debugging clang-built binaries with gdb works for me on Linux...that is with gcc's libstdc++ though and not LLVM's libc++ (not sure if that matters or if there are other special cases).

**Comment by paxth** [comment]
Thanks guys, got it working!

**Comment by paxth** [comment]
Thanks guys, got it working!
