### ISSUE TITLE
Code formatter and intellisense not working after update the extension

### ISSUE THREAD

**Issue by Sarveshgithub** [microsoft/vscode-cpptools#5535]
Issue Type: <b>Bug</b>

Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at c:\Users\sarvesh.b.kumar\.vscode\extensions\ms-vscode.cpptools-0.28.0\bin\cpptools.exe

Extension version: 0.28.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
It looks like the binaries for the extension's language server and code formatter failed to install or download during the update. Could you try uninstalling and re-installing the extension and see if that resolves the issue? Ensure that the folder of extension `c:\Users\sarvesh.b.kumar.vscode\extensions\ms-vscode.cpptools-0.28.0` is deleted prior to re-installing.

**Comment by Sarveshgithub** [comment]
Working after reinstall
