### ISSUE TITLE
Use a glob pattern to add all files under system include paths to files.associations with a single entry

### ISSUE THREAD

**Issue by gatopeich** [microsoft/vscode-cpptools#5537]
Issue Type: <b>LanguageService</b>

**C/C++: Auto Add File Associations** setting has a side effect of changing workspace settings whenever user navigates to the C++ standard library headers.
e.g.:
			"array": "cpp",
			"istream": "cpp",
			"tuple": "cpp",
			"utility": "cpp",
			"variant": "cpp"

**This is a problem when the workspace settings are under version control.**

A simple improvement would be to add the C++ standard library path to the associations. E.g.:

```
  "files.associations": {
        "**/include/c++/**": "cpp"
    }

```
Or the path to the given header, rather than every individual file name.

Extension version: 0.28.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-101-generic
Remote OS version: Linux x64 4.15.0-88-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-4500M APU with Radeon(tm) HD Graphics (4 x 1644)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.00GB (2.73GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: viavi-reverse-ssh|
|OS|Linux x64 4.15.0-88-generic|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 1697)|
|Memory (System)|31.31GB (7.96GB free)|
|VM|0%|
</details>

**Comment by gatopeich** [comment]
It seems to be an intended effect of this setting, enabled by default:

**C_Cpp: Auto Add File Associations**

**Comment by gatopeich** [comment]
### Workaround
Can be avoided by adding a file association that captures C++ standard library headers like this:
```
    "files.associations": {
        "**/include/c++/**": "cpp"
    }
```

**Comment by sean-mcmanus** [comment]
Adding that particular system path would only work on certain Linux OS's, but adding a glob pattern using the 2 parent folders might work. Might be fixable via changes to addFileAssociations at https://github.com/microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/client.ts#L2008 .
