### ISSUE TITLE
C++ namespace suggestion triggers on C label

### ISSUE THREAD

**Issue by wgj** [microsoft/vscode-cpptools#554]
- Cpptools version: 0.10.3
- VSCode version: 1.10.2
- OS Version: MacOS 10.12.3

When typing a label in C, Intellisense adds a suggestion for C++ class members. I believe the suggestion should only appear on the second consecutive colon. 

![screen shot 2017-03-12 at 6 46 15 pm](https://cloud.githubusercontent.com/assets/463564/23838709/b64fddae-0755-11e7-9643-a031264609ac.png)

![screen shot 2017-03-12 at 6 46 38 pm](https://cloud.githubusercontent.com/assets/463564/23838710/b8074a6a-0755-11e7-87b3-d64e6c42a616.png)

Triggering on the first/any colon is a pain because by the time I hit <kbd>enter</kbd> for my label, that's a long enough window of time for the Intellisense suggestion to appear, causing a snippet instead of a new line.

(I'm learning C, and not familiar with C++; Sorry if this PR is confusing/wrong)

**Comment by sean-mcmanus** [comment]
The autocomplete on ":" is a bug. It looks like it only repros if your computer is slow enough.

Also, the autocomplete commitment on Enter (and ;) is very annoying. In our next update, we're removing that by default for C/C++. You can add this to your settings to manually remove it:
      "[cpp]": {
        "editor.acceptSuggestionOnCommitCharacter": false,
        "editor.acceptSuggestionOnEnter": false
      },
      "[c]": {
        "editor.acceptSuggestionOnCommitCharacter": false,
        "editor.acceptSuggestionOnEnter": false
      }

**Comment by sean-mcmanus** [comment]
Actually, we're still deciding if we want to add this setting by default...seems like we need more feedback from what users think. Visual Studio behaves this way when no result is selected in the autocomplete list, but VS Code always selects an item.

**Comment by bobbrow** [comment]
We're doing a little more testing of this on our side to try to tune the behavior better.  In the meantime, you can also try toggling this setting in your settings.json file if you don't want to disable committing real suggestions with the Enter key:
```
"editor.quickSuggestions": false
```

**Comment by wgj** [comment]
>It looks like it only repros if your computer is slow enough

_Did msft just call my computer slow?_ 😞

FWIW, I'm using a MBA that otherwise doesn't feel slow. We haven't quantified slow, but it doesn't feel like reproduction is performance related (the suggestion overlay appears quickly, ~300ms. Though, that is a long time to determine _whether it should appear_). Let me know if there's anything I can do to help with reproduction or otherwise improve the PR.

**Comment by sean-mcmanus** [comment]
We have a fix to be released soon. We could only get the bug to repro via breaking in the debugger to slow down the execution of our auto completion code, which is why we guessed it required a slow enough computer to repro.

**Comment by bobbrow** [comment]
> Did msft just call my computer slow? 😞

Sorry, @wgj. It was poor wording. We found an artificial time barrier someone left in the auto-complete code because of a misunderstanding of the VS Code protocol. The barrier was around 250ms and I suspect that your machine was just barely missing that mark.

**Comment by wgj** [comment]
No worries. I thought it was really funny, which didn't come across in text. Thanks for the quick response time.

**Comment by bobbrow** [comment]
This should be fixed in the latest version of the extension.  Please let us know if you continue to see this issue.
