### ISSUE TITLE
non-recursive tag parser doesn't go inside directories

### ISSUE THREAD

**Issue by akshdeep-singh** [microsoft/vscode-cpptools#5544]
My settings to non-recursive tag parser can search header files in the specified path, but can not find header files under some sub-directory (example `net/if.h`).

Why doesn't the tag parser go inside `net` folder in non-recursive search?

I want to include two header files, for example:
```c
#include <unistd.h>
#include <net/if.h>
```
This is my `c_cpp_properties.json` file:
```json
{
    "configurations": [
        {
            "name": "Linux",
            "intelliSenseMode": "gcc-x64",
            "cStandard": "gnu99",
            "compilerPath": "",
            "browse": {
                "path": [
                    "/usr/include/*"
                ]
            }
        }
    ],
    "version": 4
}
```
These `browse.path` find the `unistd.h` file but not the `net/if.h` file.

If I change the path to `/usr/include` (recursive), it finds multiple `unistd.h` files from the sub-directories. I do not want that.

**Comment by michelleangela** [comment]
Can you try adding the files you want to exclude under the setting `"files.exclude"`?
![image](https://user-images.githubusercontent.com/38734287/82595900-40d12900-9b5b-11ea-8ed2-b71af194fb0f.png)

**Comment by akshdeep-singh** [comment]
I don't want to exclude anything.
Changing the engine to intellisense is working fine for me, I don't know why I was having problems with it earlier.
