### ISSUE TITLE
concept/requires keywords are not highlighted

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5546]
I have 1.45.1 VSC and 0.28.1 C++ extension and _concept/requires_ keywords are not highlighted even though VSC clearly knows(they're suggested) that they're C++ keywords.

_Originally posted by @OleksandrKvl in https://github.com/microsoft/vscode-cpptools/issues/4195#issuecomment-632070662_

**Comment by michelleangela** [comment]
@Colengc does the extension support `_concepts` and `requires_` keywords for [enhanced colorization](https://code.visualstudio.com/docs/cpp/colorization-cpp)? Or is this a feature request?

**Comment by Colengms** [comment]
'concept' and 'requires' are syntactic tokens.  Semantic parsing is not required to identify them.  Syntactic colorization comes from VS Code and TextMate grammer.  So, I believe this would be a VS Code issue.

The issue may be tracked by:

https://github.com/jeff-hykin/cpp-textmate-grammar/issues/396

The TextMate grammer from that repo is contributed to VS Code.  Often changes are available in the "Better C++ Syntax" extension before they are available in VS Code.  Using the latest version of that extension, concept and requires are colorized.

**Comment by Colengms** [comment]
Closing this, as we don't generally keep tracking issues open in this repo for issues with VS Code's TextMate grammar.  Since this has been addressed in the Better Syntax extension, it should just seem to be a matter of time until VS Code gets an updated grammar.(?)
