### ISSUE TITLE
C/C++ Extension unable to activate

### ISSUE THREAD

**Issue by yixin0829** [microsoft/vscode-cpptools#5547]
I was debugging using "cppdbg" type in launch.json. I opened another folder and when came back try to debug .cpp file again it throws "couldn't find debug adaptor for debug type 'cppdbg'". 

My C/C++ extension is installed and enabled globally but still I got "command 'C_Cpp.ConfigurationProviderSelect' not found)"  when testing.

**Comment by yixin0829** [comment]
Update: IntelliSense is off as well. The issue now is C/C++ extension is not activated properly even it's enabled globally

**Comment by WardenGnaw** [comment]
The error `command 'C_Cpp.ConfigurationProviderSelect' not found` looks like the extension did not activate. Can you remove and reinstall the extension?

Can you also fill out the issue template?
```
Type: Debugger
**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
```

**Comment by yixin0829** [comment]
- OS: Windows 10
- VS Code version: 1.45.1
- C/C++ ext version: 0.28.1
- I tried to reinstall but did not resolve the issue. I could still build and run my .cpp but IntelliSense and debugging are not working.

My c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\MinGW\\lib\\gcc\\mingw32\\9.2.0\\include\\c++"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```

launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            
            //@ Build code before lauching the debugger
            "preLaunchTask": "echo",
            //"preLaunchTask": "g++.exe build active file",

            "setupCommands": [
                {
                    "description": "For gdb pretty print",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
            
        }
    ]
}
```

**Comment by yixin0829** [comment]
Update: One problem in c_cpp_properties.json

> Unable to load schema from 'cpptools-schema:///c_cpp_properties.schema.json': Request vscode/content failed with message: cannot open cpptools-schema:/c_cpp_properties.schema.json. Detail: resource is not available.

**Comment by bobbrow** [comment]
Can you try installing the latest release? https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0
I suspect the installation was corrupted, but it sounds like you tried reinstalling the extension already.  If you're still having problems, we can validate the package resources after you install the latest version.

**Comment by yixin0829** [comment]
Yes. The latest version works. Thanks
