### ISSUE TITLE
C language syntax highlighting breaks after declaring pointer to function argument

### ISSUE THREAD

**Issue by UR3IQO** [microsoft/vscode-cpptools#555]
Hi, All!

I know cpptools extension does not provide c/c++ syntax highlighting (it uses the built-in VS Code atom/language-c), so I posted it to vscode firstly [#22519](https://github.com/Microsoft/vscode/issues/22519), but they told to ask here...

- VSCode Version: 1.10.2
- OS Version: Windows 8
- Extensions:  cpptools / ms-vscode / 0.10.3
- Language: C

Steps to Reproduce:
1. Create .c or .h file
2. Declare function with the pointer to function argument (just type something similar to):
![image](https://cloud.githubusercontent.com/assets/25171239/23846168/3045ce48-07dd-11e7-891c-63673aab04eb.png)
arguments types (I tried char, int, long, void) are not highlighted after the pointer to function argument. Type modifiers (const) are highlighted.

**Comment by sean-mcmanus** [comment]
Yeah, the person on the vscode forum who closed your original issue didn't understand the situation. To get these colorization bugs fixed, someone needs to take the time to fix it. https://github.com/atom/language-c/issues might be your best bet. Or if anyone wants to contribute to the open source fix,

**Comment by UR3IQO** [comment]
OK. It looks like I have fixed it (not sure if I didn't broke something else :) ). Now I see that current C syntax file in VSCode repository was heavily modified recently (against the one in VSCode v.1.10.2). So the fix could not be applied to the current version (and I do not know if the problem exists in the development version of VSCode), but if somebody need a fix for the VSCode 1.10.2 here is a diff 
[c.json.diff.txt](https://github.com/Microsoft/vscode/files/840704/c.json.diff.txt)
![766](https://cloud.githubusercontent.com/assets/25171239/23893438/7c034c2a-08af-11e7-91f8-581033539cf0.png)

**Comment by UR3IQO** [comment]
I checked the most recent C grammar from VSCode repository and it also fixes the problem :)

**Comment by bobbrow** [comment]
Thanks for checking.

**Comment by sean-mcmanus** [comment]
Yeah, the Insider build recently took the newer atom/language-c which fixed a few issues.
