### ISSUE TITLE
Designated struct initializtion with default values gives an error

### ISSUE THREAD

**Issue by canirex** [microsoft/vscode-cpptools#5550]
**Type: LanguageService**

When working on an OpenGL wrapper I stumbled upon what seems to be either a bug in IntelliSense or a as of yet not implemented feature. When trying to use designated initializers for a struct, it would not work when the struct had default values. The code compiled happily, but IntelliSense gave me the error "class type not suitable for use with designators". More specifically, I get the error when one of the structs default values are omitted from the initialization. When initializing the entire struct it works fine.

- OS and Version: Kubuntu 20.04
- VS Code Version: 0.28.1
- C/C++ Extension Version: 1.45.1

**Silly example code**
```
// test.cpp
struct A {
    int x = 0;
    int y = 0;
    int z = 0;
};

A func() {
    return {
        .y = 0, // error here
        .z = 0,
    };
}
```
Compiled with ```g++-10 test.cpp -c -std=c++2a```
**Expected behavior**
There should be no such error message.

**Comment by sean-mcmanus** [comment]
Is this .c (C) code? Or C++20?

**Comment by sean-mcmanus** [comment]
I assume gnu++14 or equivalent, i.e. using gnu extensions. The code doesn't compile with C and IntelliSense works with C++20, but not with C++17 or older.

**Comment by sean-mcmanus** [comment]
I've filed bug https://developercommunity.visualstudio.com/content/problem/1044574/c-intellisense-errors-occur-when-using-designated.html on VS (it's from our shared code).

**Comment by canirex** [comment]
> I assume gnu++14 or equivalent, i.e. using gnu extensions. The code doesn't compile with C and IntelliSense works with C++20, but not with C++17 or older.

Oh sorry, didn't think to actually mention what language I was using. I'm using g++ 10, with -std=c++2a. C_Cpp.default.cppStandard is c++20, so if you're saying it should work I don't know what's up.

**Comment by sean-mcmanus** [comment]
Yeah, that should work (i.e. it's working for me). When you run C/C++: Log Diagnostics does it show c++20 as the standard version? What is the IntelliSenseMode?

**Comment by canirex** [comment]
Here's a dump of the Log Diagnostics:
```
Version: 0.28.1
Current Configuration:
{
    "name": "Linux",
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "includePath": [],
    "compilerArgs": [],
    "cppStandard": "c++20",
    "intelliSenseMode": "gcc-x64",
    "browse": {
        "path": [
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ *obfuscated*/main.cpp ]:
    *obfuscated*/main.cpp
Translation Unit Configurations:
[ *obfuscated*/main.cpp ]:
    Process ID: 20081
    Memory Usage: 209 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/10
        /usr/include/x86_64-linux-gnu/c++/10
        /usr/include/c++/10/backward
        /usr/local/include
        /usr/lib/llvm-10/lib/clang/10.0.0/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++20
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=100000
Total Memory Usage: 209 MB
```
There seem to be some discrepancies whether I'm actually using clang or gcc. All the settings I've managed to find have been put to gcc, so I'm at a bit of a loss. For completeness sake here is my workspace settings.json too:
```
{
    "files.associations": {
        "type_traits": "cpp",
        "*.ipp": "cpp",
        "*.tcc": "cpp",
        "rope": "cpp",
        "fstream": "cpp",
        "iostream": "cpp"
    },
    "C_Cpp.default.cppStandard": "c++20",
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
}
```
Am I missing something obvious here?

**Comment by sean-mcmanus** [comment]
Can you change your compilerPath to "/usr/bin/g++-10" or do you really want clang instead of gcc? As of clang 9 designated initializers were not implemented in C++20 so it's excluded in that case, but I can re-check if they added that for clang 10 and file a request for them to re-enable that for clang.

UPDATE: Yeah, just got added to clang 10, i.e we should fix that to match.

**Comment by canirex** [comment]
I wanted to use g++-10 and I thought I had changed all the settings to reflect that. Turns out I had not. Adding C_Cpp.default.compilerPath = "/usr/bin/g++" seems to have solved my issue.

Many thanks!

**Comment by nlieb** [comment]
Also seeing this issue with Clang++10. Would love to see this supported in Clang configurations if possible. Is it a simple matter of enabling this check for Clang?

**Comment by sean-mcmanus** [comment]
@nlieb It doesn't seem simple to me -- it's a bug with our parser You could try asking for more info at https://developercommunity.visualstudio.com/content/problem/1044574/c-intellisense-errors-occur-when-using-designated.html .

**Comment by willem640** [comment]
Hi! I'm having this problem too, any news?

**Comment by ellipticaldoor** [comment]
Hi, I have the same error

**Comment by Kayomn** [comment]
Can confirm the incorrect linter error is still replicable

![image](https://user-images.githubusercontent.com/15730577/108576786-c9613d80-7316-11eb-9b6e-8e14fdc85c04.png)

![image](https://user-images.githubusercontent.com/15730577/108576866-075e6180-7317-11eb-8d25-a753ebe1b06b.png)

```cpp
enum class TokenType {
	Invalid,
	BraceLeft,
	BraceRight,
	ParenLeft,
	ParenRight,
	Colon,
	SemiColon,
	Comma,
	Period,
	Identifier,
	NumberLiteral,
	StringLiteral,
	EOF,
};

struct Token {
	String text;

	TokenType type;
};
```

**Comment by Trees-D** [comment]
The bug still exists

**Comment by SteveGremory** [comment]
Yes, But how in the world do i fix it? it's so annoying even thought the thing is correct it shouts at you and just-

**Comment by ellipticaldoor** [comment]
For people having this partially working and having it to suddenly break, now you need to specify in your settings.json a c++ version that is compatible with this syntax like this

```json
{
  "C_Cpp.default.cppStandard": "c++20",
}
```

I'm having a bad experience with this plugin, every update breaks something different on my editor

**Comment by sean-mcmanus** [comment]
Status: 
* Fixed with gcc, c++20 .
* Tracking this issue with gcc < c++20 (or clang < 10.0.0) (it's an "unsupported" gcc extension): https://developercommunity.visualstudio.com/t/C-IntelliSense-errors-occur-when-using/1044574
* https://github.com/Microsoft/vscode-cpptools/issues/3491 is for clang version >=10.0.0, c++20 and is tracked by https://developercommunity.visualstudio.com/t/class-type-not-suitable-for-us-with-desi/1230928 (we possibly could have a fix for this soon...not sure yet).

@Trees-D @SteveGremory @ellipticaldoor If you can give more info on which case you're hitting then we could follow up if needed.

**Comment by sean-mcmanus** [comment]
This is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders (we initially forgot the fix made it in), i.e. designated initializers no longer give squiggles for C++14 or later with clang >= 6 and gcc >= 8 (gcc with C++20 already worked).
