### ISSUE TITLE
problems with variable declaration (string) - variable-length array

### ISSUE THREAD

**Issue by prax09** [microsoft/vscode-cpptools#5554]
Issue Type: <b>Feature Request</b>

hello,
 i am declaring a string with size n  and i give constant value  to it  , but even after it is showing errors. which is as  follows:

here is the code :
 int n;
    printf("what should be the length of string: ");
   scanf("%d",&n);
    char a[n],b[n];
    printf("enter the string content");
here is the error:
{
	"owner": "C/C++",
	"severity": 8,
	"message": "expression must have a constant value",
	"startLineNumber": 8,
	"startColumn": 12,
	"endLineNumber": 8,
	"endColumn": 13
}

Extension version: 0.28.1
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by michelleangela** [comment]
@prax09 , what compiler are you using for IntelliSense configuration and to compile the code? The Microsoft C++ compiler does not support variables to define length for arrays. Clang or GCC compilers with C++ language standard set to a version (I think starting with C++11 version or later) that supports variables for arrays does support this.

Here's an online tool where you can test different compilers of different versions https://godbolt.org/.

Note, if you set variable `n` to `const` and initialize it, then it works for Microsoft C++ compiler:
```
#include <iostream>
int main ()
{
    const int n = 1;  // variable n is const and initialized as 1
    printf("what should be the length of string: ");
    scanf("%d",&n);
    char a[n],b[n];
    printf("enter the string content");

    return 0;
}

**Comment by prax09** [comment]
I am using gcc compiler

**Comment by michelleangela** [comment]
@prax09 can you provide the log output from running the command `C/C++: Log Diagnostics`?
