### ISSUE TITLE
globs in include path lose their ranks in include order

### ISSUE THREAD

**Issue by meensu23** [microsoft/vscode-cpptools#5556]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS, Docker, RHEL 7
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.1
- Other extensions you installed (and if the issue persists after disabling them): NA
- Does this issue involve using SSH remote to run the extension on a remote machine?: NO
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
  **Issue**: When I have a file `a.h` under `${workspaceFolder}/src/libA/include/` and in `/opt/include `and if my include path in `c_cpp_properties.json` has the order` ${workspaceFolder}/**, /opt/include` intellisense picks up the `/opt/include/a.h` rather than `${workspaceFolder}/libA/a.h`. 
However if I change the paths to be: `${workspaceFolder}/**, ${workspaceFolder}/libA/, /opt/include` then  it picks up `${workspaceFolder}/libA/a.h`. Does this mean globs don't follow the include order ?

**Comment by sean-mcmanus** [comment]
`"**"` triggers the recursive includes feature (not really related to glob patterns), which intentionally is forced to be moved to the end of the includes list (and is order independent). For any includes that you need to be in a certain order, you should list those explicitly and not use `"**"`.

Did you want us to change the design of "**" to not be moved to the end (or add some setting to enable that)? I seem to remember there were reasons we did it that way (might have been performance related issues).

**Comment by meensu23** [comment]
An option would be great as you can leave it to the developer to decide.
