### ISSUE TITLE
clang --target compiler arg overridden when attempting to find system defaults

### ISSUE THREAD

**Issue by schultetwin1** [microsoft/vscode-cpptools#5557]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 19631
- VS Code Version: 1.45.1

When using the clang compiler, the logic in cpptools.exe to find compiler default defines and include paths finds the wrong information if the compiler arg `--target=<some target>` is present.

I believe this is because cpptools is overridding the `--target` argument. I notice that when I pass in the compiler argument `--target=aarch64-none-linux-android29`, the resulting process to detect system include paths and defines has both `--target=aarch64-none-linux-android29` and `--target=aarch64-arm-none-eabi`. This means the detected defines and include paths will not be Android specific but a generic aarch64 set of includes/defines instead.

**Expected behavior**
I would expect cpptools to not override the `--target` argument when that is past in as a compiler arg.

**Comment by Colengms** [comment]
There are likely other args that would cause similar issues.  i.e. -march, -mcpu

**Comment by sean-mcmanus** [comment]
Your fix should be available in https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders now.

**Comment by schultetwin1** [comment]
Looks like its working! Feel free to close this out if you'd like.

**Comment by michelleangela** [comment]
Thanks for verifying. We'll close the issue when 0.29.0 is out of insiders and is released.
