### ISSUE TITLE
"preLaunchTask" in launch.json and "label" in task.json are different while generating them by default

### ISSUE THREAD

**Issue by timeneverdie** [microsoft/vscode-cpptools#5561]
The default generated launch.json and task.json files are below:

>I don't know why there are some Chinese words. My VSCode is in English and doesn't install the language package. I think it's an another bug.

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gcc.exe - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\ProgramData\\chocolatey\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "gcc.exe build active file"
        }
    ]
}
```

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "shell: gcc.exe build active file",
			"command": "C:\\ProgramData\\chocolatey\\bin\\gcc.exe",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "C:\\ProgramData\\chocolatey\\bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": "build"
		}
	]
}
```

Notice the different:

```
"preLaunchTask": "gcc.exe build active file"    //from the launch.json
"label": "shell: gcc.exe build active file"    //from the task.json
```
They are not the same. It will cause an error when press F5 on the keyboard.

![image](https://user-images.githubusercontent.com/15784314/82813924-a9583700-9ec8-11ea-9ec4-b75a40138b9a.png)

If correct them as the same, the bug gone.

```
"preLaunchTask": "gcc.exe build active file"    //from the launch.json
"label": "gcc.exe build active file"           //from the task.json
```

**Comment by michelleangela** [comment]
@elahehrashedi is this the same or related to the build/task issue https://github.com/microsoft/vscode-cpptools/issues/3674 ?

**Comment by sean-mcmanus** [comment]
The label isn't supposed to include "shell: ". What steps did you use to generate that?

**Comment by sean-mcmanus** [comment]
You should be able to fix the language issue by running the Configure Display Language command (I believe it's a VS Code bug that causes issues with our localization support).

**Comment by sean-mcmanus** [comment]
Okay, I figured it out...

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.2 . You may need to change the default cwd to "C:\\ProgramData\\chocolatey\\bin" if it's not in your PATH though, we're tracking that issue with https://github.com/microsoft/vscode-cpptools/issues/5604.
