### ISSUE TITLE
Clicking on item in outline is not jumping right

### ISSUE THREAD

**Issue by lefebvresam** [microsoft/vscode-cpptools#5567]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1809
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.1

When you have a big header file in a single project and you click on function declarations in the outline window, the jump to the code is in some cases not correct. I always have an offset of about 300 lines. 

**Steps to reproduce**
1. Click on an item in the outline window

**Expected behavior**
I expect that the jump is correct.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/15315428/82906853-2685b980-9f66-11ea-82ab-3fdee1acf0dc.JPG)

**Comment by Colengms** [comment]
Hi @lefebvresam .  I'm not able to (easily) repro.  I've tried with various large files (with more than the ~1100 lines in your image).  There may be some detail that's required to repro, such the file's encoding, or preceding source code that was not correctly parsed.  Are you able to create a stand-alone repro that you can send us?

**Comment by lefebvresam** [comment]
Dear,

 

You can test it by using the lib:

 <https://os.mbed.com/users/WiredHome/code/RA8875/> https://os.mbed.com/users/WiredHome/code/RA8875/

 

I clicked on items in ra8875.h

 

Create an mbed project by installing mbed cli:

 <https://os.mbed.com/docs/mbed-os/v5.15/quick-start/offline-with-mbed-cli.html> https://os.mbed.com/docs/mbed-os/v5.15/quick-start/offline-with-mbed-cli.html

 

mbed new <name>

mbed add RA8874

 

Best regards,

Sam Lefebvre

 

 

Van: Colen Garoutte-Carson <notifications@github.com> 
Verzonden: Wednesday, 27 May 2020 02:10
Aan: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
CC: lefebvresam <sam.lefebvre@saleconix.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [microsoft/vscode-cpptools] Clicking on item in outline is not jumping right (#5567)

 

Hi @lefebvresam <https://github.com/lefebvresam>  . I'm not able to (easily) repro. I've tried with various large files (with more than the ~1100 lines in your image). There may be some detail that's required to repro, such the file's encoding, or preceding source code that was not correctly parsed. Are you able to create a stand-alone repro that you can send us?

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue:
![image](https://user-images.githubusercontent.com/19859882/83316967-41626300-a1de-11ea-8784-bbf942a89d5d.png)

What file encoding are you using? We only support UTF-8 currently.

It sounds like something is causing incorrect offsets to be associated with the code items.

**Comment by lefebvresam** [comment]
In the right bottom corner I can see UTF-8.

If I click on the same item, it jumps to line 1111 instead of 1424.

 

Van: Sean McManus <notifications@github.com> 
Verzonden: Saturday, 30 May 2020 03:59
Aan: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
CC: lefebvresam <sam.lefebvre@saleconix.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [microsoft/vscode-cpptools] Clicking on item in outline is not jumping right (#5567)

 

I'm not reproing the issue:
 <https://user-images.githubusercontent.com/19859882/83316967-41626300-a1de-11ea-8784-bbf942a89d5d.png> 

What file encoding are you using? We only support UTF-8 currently.

**Comment by sean-mcmanus** [comment]
Okay, that is very strange. Can you confirm whether the bug repros for you when opening the raw file at https://os.mbed.com/users/WiredHome/code/RA8875//file/83edda283d90/RA8875.h/ in a new workspace folder, or does it require additional files/settings?

**Comment by sean-mcmanus** [comment]
Also, if you make some edit (i.e. add a new global function), save the file, and wait for the outline to update), does the issue fix itself?

**Comment by sean-mcmanus** [comment]
Also, does your workspace contain any cpp.hint files?

**Comment by lefebvresam** [comment]
When I open it as a new workspace (opening the folder) then it works fine.

When I open my project I get this problem.

 

Van: Sean McManus <notifications@github.com> 
Verzonden: Wednesday, 3 June 2020 03:08
Aan: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
CC: lefebvresam <sam.lefebvre@saleconix.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [microsoft/vscode-cpptools] Clicking on item in outline is not jumping right (#5567)

 

Okay, that is very strange. Can you confirm whether the bug repros for you when opening the raw file at https://os.mbed.com/users/WiredHome/code/RA8875//file/83edda283d90/RA8875.h/ <https://os.mbed.com/users/WiredHome/code/RA8875/file/83edda283d90/RA8875.h/>  in a new workspace folder, or does it require additional files/settings?

**Comment by lefebvresam** [comment]
No, but my settings are in thay way that each file saves automatically.

 

Van: Sean McManus <notifications@github.com> 
Verzonden: Wednesday, 3 June 2020 03:19
Aan: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
CC: lefebvresam <sam.lefebvre@saleconix.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [microsoft/vscode-cpptools] Clicking on item in outline is not jumping right (#5567)

 

Also, if you make some edit/save the file, does the issue fix itself?

**Comment by lefebvresam** [comment]
no

 

Van: Sean McManus <notifications@github.com> 
Verzonden: Wednesday, 3 June 2020 03:31
Aan: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
CC: lefebvresam <sam.lefebvre@saleconix.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [microsoft/vscode-cpptools] Clicking on item in outline is not jumping right (#5567)

 

Also, does your workspace contain any cpp.hint files?

**Comment by sean-mcmanus** [comment]
I tried using the entire mbed project with (i.e. mbed_os and RA8875 folders), but I still wasn't able to repro the bug. Maybe there's some VS Code setting that is required for the repro? Are you able to repro the bug with any other projects?

**Comment by lefebvresam** [comment]
It’s the first time I saw it.

But maybe I can export my settings so that you can import them?

 

Van: Sean McManus <notifications@github.com> 
Verzonden: Friday, 5 June 2020 07:56
Aan: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
CC: lefebvresam <sam.lefebvre@saleconix.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [microsoft/vscode-cpptools] Clicking on item in outline is not jumping right (#5567)

 

I tried using the entire mbed project with (i.e. mbed_os and RA8875 folders), but I still wasn't able to repro the bug. Maybe there's some VS Code setting that is required for the repro? Are you able to repro the bug with any other projects?

**Comment by sean-mcmanus** [comment]
Yeah, if you can provide any settings.json or c_cpp_properties.json settings that you think could impact our parsing behavior that could help us repro the issue.

Why are some of the filenames grayed out in your screenshot?

**Comment by lefebvresam** [comment]
Where can I find those files?

I don’t know why some files are greyed out. I can open them like others.

 

Van: Sean McManus <notifications@github.com> 
Verzonden: Friday, 5 June 2020 21:59
Aan: microsoft/vscode-cpptools <vscode-cpptools@noreply.github.com>
CC: lefebvresam <sam.lefebvre@saleconix.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [microsoft/vscode-cpptools] Clicking on item in outline is not jumping right (#5567)

 

Yeah, if you can provide any settings.json or c_cpp_properties.json settings that you think could impact our parsing behavior that could help us repro the issue.

Why are some of the filenames grayed out in your screenshot?

**Comment by sean-mcmanus** [comment]
File->Preferences->Settings and click the Open Settings (JSON) button in the top right. There could be multiple settings.json files (user/remote/workspace/folder). c_cpp_properties.json should be unser ${workspaceFolder}/.vscode, but it may not exist.

**Comment by lefebvresam** [comment]
For an unknown reason, the problem looks solved.
