### ISSUE TITLE
Question: how to get ExtensionContext in unitTest

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cpptools#5573]
@sean-mcmanus  Hi sean, recently I am writing unit tests of my own vscode extension. I can't get ExtensionContext in unitTest. How to mock those functions which are using ExtensionContext? Do you have any ideas about this?

**Comment by sean-mcmanus** [comment]
I don't know. None of our tests use the extension context and we just get it when our extension activates from VS Code.

**Comment by Lennon925** [comment]
> I don't know. None of our tests use the extension context and we just get it when our extension activates from VS Code.

Thanks for your reply~
