### ISSUE TITLE
Some functions are not found in outline

### ISSUE THREAD

**Issue by xianhongye** [microsoft/vscode-cpptools#5575]
**Type: LanguageService**

**Describe the bug**
- OS and Version: win10 pro（10.0.17763）
- VS Code Version:  1.45.1
- C/C++ Extension Version: 0.28.1
- Other extensions you installed (and if the issue persists after disabling them):
    C++ Intellisense 0.2.2
    C/C++ Clang Command Adapter 0.2.3
- Does this issue involve using SSH remote to run the extension on a remote machine?:
   no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

    I'm using vs code to open the code for pg11.5.
    Some functions in the c file are not scanned, but other functions in the file can be scanned.
    You can't find the function in the outline, but the function is defined.
    CTRL +T, you can't find this function either.

**Steps to reproduce**

1. open pg11.5
2. open file postgres.c
3. in outline, exec_simple_query() cannot be found

**Expected behavior**

You should find the function exec_simple_query() in the outline.

<details>
  <summary><strong>Logs</strong></summary>

```
nothing
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/65698304/83018720-51e8d100-a058-11ea-8d14-8e08af437a52.png)
![image](https://user-images.githubusercontent.com/65698304/83018857-8ceb0480-a058-11ea-9cd0-3f7edd450dec.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
The usage of a macro might be causing our tag parser to fail. Do you have a repro sample we an try? If you have any macros like a FOR_EACH that require expansion in order for the surrounding code to be correctly parsed then that would be the cause (the solution is to add the macro to a cpp.hint file, see https://github.com/microsoft/vscode-cpptools/issues/5460).
