### ISSUE TITLE
Use compiler's default standard version(s) when probing the compiler, if none was specified.

### ISSUE THREAD

**Issue by ghuser404** [microsoft/vscode-cpptools#5579]
By default, gcc is using gnu C/C++ standard (gnu99, etc.). This means that `__STRICT_ANSI__` is not defined. However, cpptools will always define `__STRICT_ANSI__`, unless otherwise specified with `cStandard` (specifying `"cStandard": "gnu99"` will correctly result in `__STRICT_ANSI__` not being defined).

Consider the setup below. IntelliSense shows "\_\_STRICT_ANSI\_\_ defined", but running this program, it prints "\_\_STRICT_ANSI\_\_ not defined".

main.c
```
#include <stdio.h>

int main()
{
#ifdef __STRICT_ANSI__
    printf("__STRICT_ANSI__ defined\n");
#else
    printf("__STRICT_ANSI__ not defined\n");
#endif

    return 0;
}
```

c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Win32",
            "compilerPath": "C:/mingw-w64/8.1.0/mingw32/bin/gcc.exe"
        }
    ],
    "version": 4
}
```

**Comment by Colengc** [comment]
Hi @ghuser404 .  Thanks for reporting this.  It looks like we're adding the latest standard version when probing the compiler (and falling back to older standard versions if that fails).  But, that is the wrong approach, as it overrides the default standard version of the compiler.  We should instead be probing the compiler without a std version if none was configured.

**Comment by ghuser404** [comment]
@Colengc Thanks for looking into this. Really, this invalidates #2782 for me as I was hoping it would solve a handful IntelliSense errors in one of the libraries that we are using.

**Comment by Colengms** [comment]
@ghuser404 Does providing the appropriate value for `cStandard` in your config work around the issue?

**Comment by ghuser404** [comment]
@Colengms The library is based on CMake. Specifying gnu standard in CMake configuration solves the problem, but we cannot do this in an external library. In my local tests choosing gnu standard via `cStandard` worked too.

**Comment by sean-mcmanus** [comment]
Should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders

**Comment by ghuser404** [comment]
Works with my original example. But sadly, doesn't work with cmake-tools extension, as it sets c11 by default, instead of gnu11. Maybe will be fixed with https://github.com/microsoft/vscode-cmake-tools/issues/1152
