### ISSUE TITLE
Enhanced colorization doesn't work with recursive includes with header guard

### ISSUE THREAD

**Issue by b1r1b1r1** [microsoft/vscode-cpptools#5581]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Mac OS Mojave 10.14.4
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.1
- Other extensions you installed (and if the issue persists after disabling them): no
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- Explanation: 
When using file structure (header file + header guard + include implementation) + (implementation file + include header) enhanced colorization fails to provide a correct color sometimes.

**Steps to reproduce**

1) Create 2 files in a single workspace:

a.hpp
```c++
#ifndef GUARD
#define GUARD

namespace NLibPoly {

template<typename T>
class A {
private:
    T B;
};

}

#include "a.tpp"

#endif
```

a.tpp (which is cpp actually)
```c++
#include "a.hpp"
```

2) Choose dark+ theme, enable enhanced colorization and choose default intellisense engine
2) Open a.hpp
3) Look at color of T after private keyword
4) Comment `#include "a.tpp"` line
5) Look at color of T after private keyword again

**Expected behavior**

T and B keywords should be colored both on step 3 and 5.
Instead, on step 3 both keywords are not colored.

**Screenshots**

![step 3](https://i.imgur.com/Ehs3WX7.png)
![step 5](https://i.imgur.com/h8j6165.png)

**P.S.**
Replacing a.tpp content with 
```c++
#ifndef GUARD
#include "a.hpp"
#endif
``` 
fixes the issue, but idk reason of such behaviour, because nothing changed in fact.

**Comment by Colengms** [comment]
Hi @xmikasax .  Thanks for reporting this.  The issue also repro's in VS.  (We share common code for IntelliSense with VS).  I've opened an issue against VS here: https://developercommunity.visualstudio.com/content/problem/1054907/c-intellisense-fails-with-guarded-recursive-inclus.html
