### ISSUE TITLE
Support Windows ARM64 (Surface Pro X)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5583]
See https://github.com/microsoft/vscode/issues/98818 .

**Comment by driver1998** [comment]
clang/LLVM supports Windows ARM for both host and target, I guess libclang should also be working?

**Comment by ghost** [comment]
Are there any updates on this?

**Comment by sean-mcmanus** [comment]
@joshuakravitz We haven't started work on it -- still investigating Linux ARM.

**Comment by shuffle2** [comment]
On Surface Pro X, it seems both native as well as remote (connected to local WSL2 instance) does not work. Is that the expected current status? I was hoping using WSL remote could be a temporary workaround.

**Comment by sean-mcmanus** [comment]
@shuffle2 We haven't released Windows ARM binaries yet. For your WSL2 scenario, do you know what architecture the Linux instance is using? armhf or aarch64? https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders2 has armhf support and partial aarch64 support, and our next 0.30.0-insiders3 will have full aarch64 support.

**Comment by shuffle2** [comment]
The kernel in WSL2 (Microsoft-provided Ubuntu) is aarch64, and does not enable CONFIG_COMPAT. I have no idea if hyper-v actually supports running armv7 instructions in guests. Good to know support is being worked on, I'll continue using amd64 desktop for now.

**Comment by danlehmann** [comment]
Just my 2 cents: It would be nice to prioritize this higher. Windows-arm (e.g. Surface Pro X) still has very few applications and as someone who'd like to at least port my own things over I was quite surprised to see how even most developer tools don't even work on the device. Having a good C++ IDE would go a long way in improving this ecosystem.

**Comment by bobbrow** [comment]
@danlehmann you may not have noticed, but we assigned this to the next release milestone after the current one.  That puts the expected release date around the end of October, though if you join the Insiders program you will likely see it sooner.

**Comment by danlehmann** [comment]
Thank you @bobbrow, that's great to hear! Time to become an insider in that case :-)

**Comment by Alovchin91** [comment]
v1.0 was just released. Is Windows Arm64 support still planned for v1.1?

**Comment by bobbrow** [comment]
@Alovchin91, yes it is on the schedule for 1.1.0

**Comment by bobbrow** [comment]
@Alovchin91, yes it is on the schedule for 1.1.0

**Comment by sean-mcmanus** [comment]
We have a Windows ARM64 1.1.0-insiders3 vsix at https://github.com/microsoft/vscode-cpptools/releases/download/1.1.0-insiders3/cpptools-win-arm64.vsix . Debugging isn't enabled yet though.
