### ISSUE TITLE
C language symbol defect

### ISSUE THREAD

**Issue by siddharthmagadum16** [microsoft/vscode-cpptools#5589]
Issue Type: <b>Bug</b>

Problem:
When I add c file extension as a `.C` (capital letter) and save (for eg file1.C)
the symbol for the file changes to c++ symbol (i know it is a wrong way ).
I tried to revert back saving the file with `.c` (small c) extension, But the symbol of c++ never changes to c.
The code works in c language very well. The only problem is symbol.

![image](https://user-images.githubusercontent.com/60000624/83403989-65fd4b80-a427-11ea-818c-7b5a985a95e3.png)

Extension version: 0.28.1
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Can you check your files.associations setting? We may be adding that .C file to a cpp association.

**Comment by sean-mcmanus** [comment]
Yeah, I just tried it out -- that's what's happening. You should be able to fix it by removing the files.associations. Oh, maybe there's a way to detect a .C to .c rename to auto-remove the files.associations.

**Comment by siddharthmagadum16** [comment]
Yes, it worked by removing the filenames created in settings.json  under file.associations
Thank you
