### ISSUE TITLE
definition results are returned inside of comments

### ISSUE THREAD

**Issue by cpagravel** [microsoft/vscode-cpptools#559]
This is a known shortcoming stated in the [VS Code help page](https://code.visualstudio.com/docs/languages/cpp). 

> Currently, the C/C++ extension doesn't parse code in a way that helps it distinguish between competing definitions based on how the symbol is used.

I'm currently using Sublime text 3 with the [EasyClangComplete](https://packagecontrol.io/packages/EasyClangComplete) plugin for this, but would really like to try VS Code. Is there any chance of this feature getting added soon?

In my C++ project I have a lot of initialize methods for different classes and I get about 100+ matches when trying to follow an initialize call. I also have many overloaded functions which cause the same problem. It would be great to have this in VS Code!

**Comment by cpagravel** [comment]
As an example, even the comments in my code match function calls.

![example](https://cloud.githubusercontent.com/assets/9516565/23875086/89c5b9de-080e-11e7-91ba-aa733048a9d2.png)

**Comment by bobbrow** [comment]
Semantic auto-complete results are being tracked by issue #13.
We are aware of the issue with matching function calls inside comments, but I don't think anyone else reported it yet.  We can use this issue to track it.

**Comment by ghost** [comment]
Totally agree, that this should not happen. Also the function definitions context is called on macro preprocessor as shown below:
![screenshot from 2017-05-09 10-36-34](https://cloud.githubusercontent.com/assets/8155675/25842246/ac72d2d4-34a3-11e7-9f62-5d9dedb83845.png)

**Comment by bobbrow** [comment]
Thanks @Tankypon. We will address that as well.

**Comment by sean-mcmanus** [comment]
@Tankypon This should be fixed by changing the IntelliSense engine to Default (hover is fixed, but not Go to Def and other features). Let us know if that causes any other problems.

**Comment by sean-mcmanus** [comment]
Definitions should not longer be returned in comments with 0.19.0.
