### ISSUE TITLE
Unable to show error message when an identifier is undefined in C source file

### ISSUE THREAD

**Issue by ravy-alt** [microsoft/vscode-cpptools#5590]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows10 2004
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.1
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

  When an identifier is undefined or undeclared in C source file , this tools doesn't show any error message.
  ![image](https://user-images.githubusercontent.com/26875324/83410695-70c8d800-a449-11ea-8818-a75cb0fcd9af.png)

  But if an an identifier is undefined or undeclared in CPP source file, it can show error message correctly
  ![image](https://user-images.githubusercontent.com/26875324/83410680-6575ac80-a449-11ea-9848-5c3c989a71ad.png)

**Comment by sean-mcmanus** [comment]
This is currently "by design" because usage of undeclared function identifiers is valid and doesn't generate a compiler error in C, giving:
```
warning: implicit declaration of function 'func' [-Wimplicit-function-declaration]
    3 |     return func();
```

. We have an issue tracking potentially adding "warning" support at https://github.com/microsoft/vscode-cpptools/issues/828 .
