### ISSUE TITLE
GDB debugger for C++ not working on VS Code

### ISSUE THREAD

**Issue by ayonization** [microsoft/vscode-cpptools#5594]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.45.1
- C/C++ Extension Version:0.28.1
- Other extensions you installed (and if the issue persists after disabling them): None

Ive been using VS Code for c++ development for some time.

Yesterday I mistakenly deleted some files from my C drive, and now the Gdb debugger does not work.

I tried everything, Uninstalled VS Code along with all the extensions and installed it again, also did the same with Mingw.

I then followed the documentations https://code.visualstudio.com/docs/cpp/config-mingw thoroughly.
Everything goes well upto the "Running the build" point.

But whenver i try to debug, the terminal shows

`C:\Users\Ayon\c++\helloworld> cmd /C "c:\Users\Ayon\.vscode\extensions\ms-vscode.cpptools-0.28.1\debugAdapters\bin\WindowsDebugLauncher.exe --stdin=Microsoft-MIEngine-In-h5bb0jol.ikn --stdout=Microsoft-MIEngine-Out-euoebo4n.lli --stderr=Microsoft-MIEngine-Error-ex1jwjkz.d3i --pid=Microsoft-MIEngine-Pid-dawgddvs.jcv "--dbgExe=C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\gdb.exe" --interpreter=mi " 'cmd' is not recognized as an internal or external command, operable program or batch file.`

Previously, an "&" showed up in place of the "cmd /C" I see now, which seems to be the cause of the error.

Please help me solve this issue. I know this might not be the relevant forum for it since its not an issue with VS Code itself but rather a fault on my part. But Im only asking here because this is my last option. Ive tried everywhere else to no success.

Any help would be apprecitated.

For reference , here is my launch.json :

```
`{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "g++.exe build and debug active file",
        "type": "cppdbg",
        "request": "launch",
        "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false,
        "MIMode": "gdb",
        "miDebuggerPath": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\gdb.exe",
        "setupCommands": [
          {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
          }
        ],
        "preLaunchTask": "g++.exe build active file"
      }
    ]
  }`

```

**Comment by WardenGnaw** [comment]
The error:
>'cmd' is not recognized as an internal or external command, operable program or batch file.

If you open up `Command Prompt` and type `where cmd`. Does anything output?

**Comment by WardenGnaw** [comment]
Closing this issue for now. Please reopen if you have any other questions. 
If it is another issue, please file a new issue.
