### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by skandasuresh** [microsoft/vscode-cpptools#5597]
Issue Type: <b>Bug</b>

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.3.9600

Extension version: 0.28.2
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.93GB (1.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Was this auto-generated by something? We need more info.

**Comment by skandasuresh** [comment]
> Was this auto-generated by something? We need more info.

After installation of  c/c++ extension in vscode there was this message displayed at the right corner of the screen

**Comment by sean-mcmanus** [comment]
I don't believe this is a bug with our C/C++ extension (i.e. I'm not aware of any of our extension's code that could cause this). If you have more repro info, you may want to file a bug with VS Code itself, i.e. similar reports are https://github.com/microsoft/vscode/issues/95321 and https://github.com/microsoft/vscode/issues/94858 .

**Comment by skandasuresh** [comment]
antivirus was blocking the extension host file and I have excluded it from virus detection file, now vs code is functioning properly ... Thank you.
