### ISSUE TITLE
C language not an option, no syntax highlighting

### ISSUE THREAD

**Issue by DaveEveritt** [microsoft/vscode-cpptools#5598]
**Type: LanguageService**

**Describe the bug**

- OS and Version: OS X Mojave 10.14.6 (18G103
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.1
- Other extensions you installed (and if the issue persists after disabling them): Better C++ Syntax, yes
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- Single project in C, multiple files. There is no syntax highlighting. In the language syntax options, C does not appear.

**Steps to reproduce**

1. Open a C file ".c"
2. Click the language option, bottom right (reads "plain text" by default)
3. "Select language mode" shows
4. Choose "Configure file association for .c"
5. There is no option to choose C

**Expected behavior**

At point 5 above, I would expect "C" to be a language option

1. Logs from the command `C/C++: Log Diagnostics` ??
2. Logs from [the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) ??

<details>
  <summary><strong>Logs</strong></summary>

```
Tried, but logs not found.
```
</details>

**Comment by sean-mcmanus** [comment]
If you disable our C/C++ extension, I believe you will still repro the issue. Please open an issue on VS Code itself at https://github.com/microsoft/vscode/issues . Our extension isn't involved in the language mode functionality described.

**Comment by sean-mcmanus** [comment]
The VS Code team also might need more repro info, because I am unable to repro it.

You may also want to try temporarily disabling the Better C++ Syntax extension, although I'm not sure how they could affect the repro either.

**Comment by DaveEveritt** [comment]
I've opened an issue on VSCode… will leave this open for now until I get a response, and in case anyone else has the same issue or can reproduce it. Have been referred back here from the VSCode [issue #99178](https://github.com/microsoft/vscode/issues/99178#issue-629470134)

**Comment by bobbrow** [comment]
It appears this issue was resolved.
