### ISSUE TITLE
Unable to display variables in the debugger as hex or decimal

### ISSUE THREAD

**Issue by IanHoltham** [microsoft/vscode-cpptools#5599]
I have a project running on macOS using clang/lldb which for compatibility reasons uses a lot of "unsigned char" variables as integers (the code also runs on embedded targets where memory is at a premium).
When I debug this code within VSCode, all the variables are displayed as characters, however I wish to see the variables displayed as hex or decimal.
I have tried to add the variables to the Watch window and appending a ,h or ,x format (e.g. hour, x) but I get an error displayed 'Error: Unregcognized format of field "value" in result'.
This issue may be a duplicate of #557 but there seems to have been no update on that in over a year.

**Comment by WardenGnaw** [comment]
We are watching and prioriting debugger Feature Requests based on the number of 👍 indicated on the post.

Please indicate your interest by voting on #557.

Closing as duplicate.
