### ISSUE TITLE
What are .vscode/.browse.VC.db*?

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-cpptools#56]
_From @Tyriar on May 26, 2016 18:37_

These 2 files are being created, no idea what they are:

```
.vscode/.browse.VC.db
.vscode/.browse.VC.db-wal
```

Something to be concerned about or already fixed?

_Copied from original issue: Microsoft/vscode#6931_

**Comment by aeschli** [comment]
_From @alexandrudima on May 26, 2016 18:41_

@Tyriar Maybe you have installed the cpp extension?

**Comment by aeschli** [comment]
_From @Tyriar on May 26, 2016 18:44_

@alexandrudima ah that must be it, do you remember what the cpptools issue repo was?

**Comment by delmyers** [comment]
@aeschli 

Those files are nothing to worry about. They are just the databases that are used for enabling the C++ language service. They are needed for the go to symbol, go to declaration, and go to definition features.

With the latest update (https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools), they should only get created if you open a cpp or header file.
