### ISSUE TITLE
C++ Intellisense not working as expected 

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#5601]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: Lastest (and insider)
- C/C++ Extension Version: v0.28.2
- Other extensions you installed (and if the issue persists after disabling them): CMake
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The project is a small single project workspace. When overing over method and trying to autocomplete something I get these error.

**Steps to reproduce**

    1. Fresh vscode (insider too)
    2. Install extension c/c++ and cmake tools
    3. Over an element
![image](https://user-images.githubusercontent.com/52473004/83546992-8d0f5800-a4cf-11ea-8772-b84063bcfb74.png)
    3b. Or try to autocomplet and object
![image](https://user-images.githubusercontent.com/52473004/83547000-93053900-a4cf-11ea-86d6-74cf4b540acf.png)

**Expected behavior**

For the 3. A formated output, not with the backslash and for 3b the method desciption and not the file name "File: vector".

<!-- Please provide the following logs that show diagnostics and debugging information about the language server.
1. Logs from the command `C/C++: Log Diagnostics`
-------- Diagnostics - 6/2/2020, 12:53:10 PM
Version: 0.28.2
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compilerArgs": [],
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Alexandre\Documents\Projects\Games\multiblast\src\main.cpp ]:
    C:\USERS\ALEXANDRE\DOCUMENTS\PROJECTS\GAMES\MULTIBLAST\SRC\MAIN.CPP
Translation Unit Configurations:
[ C:\Users\Alexandre\Documents\Projects\Games\multiblast\src\main.cpp ]:
    Process ID: 11132
    Memory Usage: 84 MB
    Compiler Path: c:/program files (x86)/microsoft visual studio/2019/enterprise/vc/tools/msvc/14.25.28610/bin/hostx86/x86/cl.exe
    Includes:
        C:\LIBS\SFML-2.5.1\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\VC\TOOLS\MSVC\14.25.28610\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\VC\TOOLS\MSVC\14.25.28610\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        SFML_STATIC
        WIN32
        _WINDOWS
        NDEBUG
    Standard Version: ms_c++17
    IntelliSense Mode: msvc-x86
Total Memory Usage: 84 MB

**Comment by sean-mcmanus** [comment]
For 3a, doxygen support is still under development and being tracked with https://github.com/microsoft/vscode-cpptools/issues/658 .

For 3b, this appears to be "by design", as there is no description/comment associated with the definition of vector. If you use Go to Definition on the call to assign, you can verify that no comment exists for it. You could file a request to add documentation to the Microsoft STL at https://github.com/microsoft/STL/issues . Let us know if your implementation has comments (if so it could be a different bug).

**Comment by bobbrow** [comment]
Doxygen support has been release in version 0.29.0.
