### ISSUE TITLE
undefined reference issue - only in VSCode 

### ISSUE THREAD

**Issue by nimasaj** [microsoft/vscode-cpptools#5603]
Type: Debugger

**Describe the bug**
- OS and Version: Win 8 x64
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.2
- Other extensions you installed (and if the issue persists after disabling them): Aruino, CodeRunner, Auto Scroll, Platform IO IDE, ESP32 DEBUG ::::::: YES, the issue exists after disabling others. 
- A clear and concise description of what the bug is. The code doesn't compile with following error. However, the code compiles correctly in Code::Blocks and other IDEs, even on online interpreters and shells.
Error: 

> undefined reference to `revise(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
> collect2.exe: error: ld returned 1 exit status

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Copy/paste the code and try to compile it.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

<details>
 <summary>Launch.json::</summary>

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}
```
</details>

<details>
  <summary>tasks.json:</summary>

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\MinGW\\bin\\g++.exe",
			"args": [
				"-g",
				//"${workspaceFolder}\\*.cpp",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```
</details>

<details>
  <summary>c_cpp_properties.json:</summary>

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/MinGW/bin/g++.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```
</details>

<details>
  <summary>Code - (simplified) main (bleep.cpp):</summary>

```
#include <iostream>
#include <string>
#include <stdio.h>
#include <stdint.h>
#include <vector>
#include "functions.hpp"

using namespace std;

string w = "broccoli";
string s = "This is a sample text with broccoli repeated for two times, broccoli and yeah broccoli, everywhere broccoli.";



int main()
{

  revise(s,w);
  cout<< s<<endl;

  return 0;
}

```
</details>

<details>
  <summary>Code - (simplified) header (functions.hpp):</summary>

```
#include <iostream>
#include <string>
#include <stdio.h>
#include <stdint.h>
#include <vector>
using namespace std;

    void revise(string &sentence, string word);
    void pr_v(vector<int> v);
    void bleep_rev(string &sentence, uint16_t ind, uint8_t len);
```
</details>

<details>
  <summary>Code - (simplified) source (functions.cpp):</summary>

```
#include <iostream>
#include <string>
#include <stdio.h>
#include <stdint.h>
#include <vector>
#include "functions.hpp"

using namespace std;

void pr_v(vector<int> v){
  for (int j=0; j<v.size(); j++){
    cout << "v[" << j << "]: "<<v[j]<<endl;
  }
}

void bleep_rev(string &sentence, uint16_t ind, uint8_t len)
{
    bool dbg = false;
    string a="";
    int ss = sentence.size();
    if(dbg)
    {
        cout<< "sen: " << sentence << endl;////////////dbg line
    }
    a=sentence.substr(0,ind);

    for (uint8_t k=0; k<len; k++)
    {
        a+="*";
    }
    a+=sentence.substr(ind+len,ss);
    sentence=a;
    if(dbg)
    {
        cout<< "a: " << a << endl;////////////dbg line
    }
}

void revise(string &sentence, string word)
{
    int ws = word.size();
    vector<int> v;
    bool dbg = false;
    int ss = sentence.size();
    uint16_t a0 = sentence.find(word);
    int q = 0;
    if(dbg)
    {
        cout<< "a0: " << a0 << endl;////////////dbg line
        cout<< "ss: " << ss << endl;////////////dbg line
    }
    while (a0 < ss)
    {
        v.push_back(a0);
        a0 = sentence.find(word, a0 + ws);
        bleep_rev(sentence, v[q], ws);
        q++;
    }
}
```
</details>

**Comment by sean-mcmanus** [comment]
The code that you're building is just the 1 .cpp file in your tasks.json, but it references revise which is defined in a different .cpp file. You can fix it via adding the other .cpp with the definition to the list of files to compile in your tasks.json.

**Comment by nimasaj** [comment]
Thanks for your reply.
Based on [this page](https://code.visualstudio.com/docs/cpp/config-msvc#_modifying-tasksjson) and this part: 

> You can modify your tasks.json to build multiple C++ files by using an argument like "${workspaceFolder}\\*.cpp" instead of ${file}. This will build all .cpp files in your current folder.


I made changes to tasks.json file by un-commenting  `//"${workspaceFolder}\\*.cpp",`  and commenting  `"${file}",`.
But the issue still persists with the same error message, and the command for building includes only the main file. `g++ bleep.cpp -o bleep`




<details>
 <summary>new tasks.json::</summary>

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\MinGW\\bin\\g++.exe",
			"args": [
				"-g",
				"${workspaceFolder}\\*.cpp",
				//"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```
</details>

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue. What is the output in your Terminal window when you run the build task? It should show the `"*.cpp"` still, since g++.exe itself is supposed to handle the `"*"`.

If "C:\\MinGW\bin\\" isn't in your system environment path, you'll need to change the "cwd" to "C:\\MinGW\bin\\" or add it to your path.

**Comment by nimasaj** [comment]
As long as the error message is produced in Output window, Terminal window is empty. 

Error msg - Output window:
https://pasteboard.co/JbuDv24.png

But when I build it manually, it works.
Manual build- Terminal window:
https://pasteboard.co/JbuFaF0.png

User environment variable was already set:
https://pasteboard.co/JbuD68b.png

But not on system environment variable path. However, I added the path "C:\MinGW\bin\" to system env.var. and restarted VSCode afterward, but, still the same error is coming. 

A picture of tasks.json:
https://pasteboard.co/JbuDFDu.png


I have to clarify that I build the projects using the build button as shown below. It is added by CodeRunner. Could the issue be coming from here?
https://pasteboard.co/JbuRP2U.png

**Comment by sean-mcmanus** [comment]
@nimasaj Yes, it appears to be an issue with CodeRunner (i.e. it looks like that extension is writing to the output window).
