### ISSUE TITLE
Language server sometimes doesn't restart correctly after a crash in the multi-root scenario

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5606]
Originally discovered as part of https://github.com/microsoft/vscode-cpptools/issues/5591

It doesn't always repro though. The repro is to have 2 workspace folders and kill the cpptools process. Having .cpp files open may be required too.

**Comment by sean-mcmanus** [comment]
It looks like under some unknown conditions the code that switches out the crashed language client with the new one is hitting some issue.

I don't have time to investigate this further due to higher priority issues, but if anyone wants a challenging debugging task and/or are annoyed by this issue then feel free to try to figure out what is going wrong.

**Comment by bobbrow** [comment]
I'm not seeing any additional reports of this and given how old it is, we won't be fixing this unless we get more feedback.
