### ISSUE TITLE
vscode ssh remote c++无法转到定义

### ISSUE THREAD

**Issue by kongdingchao** [microsoft/vscode-cpptools#5609]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by kongdingchao** [comment]
vscode ssh remote c++无法转到定义
添加工程后，其它目录能正常转到定义，就是有一个目录不行（之前能转定义）

**Comment by michelleangela** [comment]
@kongdingchao Could you translate the issue or error message to English?

**Comment by michelleangela** [comment]
Also, could you provide more info, such as info about the local and remote machine, and steps to reproduce the issue?
