### ISSUE TITLE
cannot start teminal process

### ISSUE THREAD

**Issue by tomchenkang** [microsoft/vscode-cpptools#5613]
Issue Type: <b>Bug</b>

terminal process command "C:\Windows\System32\cmd.exe"could not be started(exit code is 2)

Extension version: 0.28.2
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (5.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
@tomchenkang 
Could you provide steps to reproduce the issue? Were you trying to build or debug or just open a terminal in VS Code?

**Comment by tomchenkang** [comment]
> @tomchenkang
> Could you provide steps to reproduce the issue? Were you trying to build or debug or just open a terminal in VS Code?

when i start VS Code, there's no terminal window, so i click terminal in menu, then the issue produce.
the day before yesterday i can open terminal, the morning of yesterday, when i open VS Code, the issue produce(i did nothing in the period)
when i debug there 's the info of the issue:

the information in window is:
> the prelaunchtask 'gcc.exe build active file' terminated.

the information in terminal window is:
> Executing task: C:\MinGW\bin\gcc.exe -g c:\Users\kangb\chen\cbase\1.c -o c:\Users\kangb\chen\cbase\1.exe <
>The terminal process command 'C:\Windows\System32\cmd.exe /d /c C:\MinGW\bin\gcc.exe -g c:\Users\kangb\chen\cbase\1.c -o c:\Users\kangb\chen\cbase\1.exe' failed to launch (exit code: {2})

**Comment by tomchenkang** [comment]
my security software stop it. i'm sorry to disturb your work
