### ISSUE TITLE
Unable to start the C/C++ language server. IntelliSense features will be disabled. [missing language server binary]

### ISSUE THREAD

**Issue by nehilsood** [microsoft/vscode-cpptools#5615]
Type: General

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by michelleangela** [comment]
Modifying title and adding error of issue below:

`Error: Missing binary at c:\Users\Nehil Sood\.vscode\extensions\ms-vscode.cpptools-0.28.2\bin\cpptools.exe`

**Comment by michelleangela** [comment]
The error suggests at the binary of the language server (cpptools.exe) is missing. It looks like the binary failed download or install. Please try to uninstall the extension and re-install again. Note that before re-installing, ensure that the folder `ms-vscode.cpptools-0.28.2` is deleted from uninstalling.

**Comment by Patuti** [comment]
I was having the same issue here (0.28.3), it was working flawless just yesterday. Fixed after uninstalling the extension, deleting `ms-vscode.cpptools-0.28.3`, and re-installing it.

I can't confirm this, but I think I updated the extension sometime yesterday, so maybe something went wrong during the update which resulted in missing files.
I don't know if there's a log from the update that I could check to confirm that, if there's let me know and I'll check it.

**Comment by michelleangela** [comment]
@Patuti do you recall if you had more than one instance of VS Code open when the extension was updated and failed to install?

**Comment by Patuti** [comment]
@michelleangela I can't remember for sure, but for most of the time I have 3 instances open, so most likely yes.

**Comment by bobbrow** [comment]
This scenario should be fixed in 0.30.0 (which is yet to be released).
