### ISSUE TITLE
Macro-defined scope not taken into account by IntelliSense

### ISSUE THREAD

**Issue by adrien-lenglet** [microsoft/vscode-cpptools#5616]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Education v.1803
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.2
- When writing code into a macro wrapping that code into a certain scope, main level scope is still used for code completion.
- IntelliSense doesn't detect any error and the project still compiles fine.

**Steps to reproduce**

1. Create a macro wrapping code into a scope
2. Call that macro and try to access members in that scope
3. Members available in that scope are not suggested

**Expected behavior**

- Having scope-dependent code suggestions
- In below example, `m_data` should be suggested

**Screenshots**

![impl_getter](https://user-images.githubusercontent.com/43445534/83849034-12348000-a70f-11ea-9383-11d5481b2299.PNG)

**Test code**
```cpp
void m_data_main(void)
{
}

class test
{
	int m_data;

public:
	int getData(void) const;
};

#define impl_getter(type, scope, ...) type scope(void) const { __VA_ARGS__ }

impl_getter(int, test::getData,
	return m_data;
)
```

**Comment by michelleangela** [comment]
This can be reproduced in Visual Studio. @sean-mcmanus , is this issue related to https://github.com/microsoft/vscode-cpptools/issues/4933?

**Comment by sean-mcmanus** [comment]
That's a different issue (completion not working in a macro definition). In this case, the completion is not occurring in the macro definition, and completion works, it's just that the scope used is incorrect. We should file a new bug on VS.

**Comment by michelleangela** [comment]
The issue is in the IntelliSense engine component, which is shared with Visual Studio. So this issue has been reported in Visual Studio https://developercommunity.visualstudio.com/content/problem/1067607/c-intellisense-incorrect-completion-in-macro-defin.html.

**Comment by rpjohnst** [comment]
As a workaround, you may be able to remove the function body `{ __VA_ARGS__ }` from the macro definition, and write the macro invocation like `impl_getter(int, test::getData) { return m_data; }` instead.

**Comment by FMC64** [comment]
@rpjohnst Agreed. This is now my preferred approach for declaring macro-enhanced lambdas or unit tests.
At the time, the underlying issue was more about pretty heavy metaprogramming with function implementations and nested function/method implementations (within namespaces, class, class in class, etc) all defined in a single macro invocation. I believe solving the shorter example provided would enable completion in that kind of depth.

**Comment by quantunm** [comment]
Is this issue forgotten ? I'm expecting the fixing for this issue.

**Comment by sean-mcmanus** [comment]
@quantunm The VS team closed the issue we filed as "low priority" and suggested "[Workaround]
As a workaround, you may be able to remove the function body { __VA_ARGS__ } from the macro definition, and write the macro invocation like impl_getter(int, test::getData) { return m_data; } instead.".

Someone could re-create the VS issue.

**Comment by AshrafMasoud5** [comment]
@sean-mcmanus  The workaround is specific to this case only, and not a feasible solution.
lots of embedded programming include macros in C language,
IMHO the macro IntelliSense is very important.
when having pages of macro constants, I must have autocompletion in my code editor.

**Comment by sean-mcmanus** [comment]
@AshrafMasoud5 I've forwarded your comment to the VS team to see if the internal issue can be re-opened...

**Comment by sean-mcmanus** [comment]
@AshrafMasoud5 Your comment "having pages of macro constants" implies you may be hitting a different bug. Can you clarify or provide more repro details? This particular bug is not possible to fix with our current design, but you may be hitting a different issue.

**Comment by AshrafMasoud5** [comment]
@sean-mcmanus Thanks for your consideration.
I think it is the same bug.
simple macro definitions will not have any autocomplete while writing them
```c
#define INVERTER_BASE        (0x80)
#define HAL_RX               (0x01+INVERTER_BASE)  // INVERTER_BASE will not be autocompleted even if declared as a variable
```
function renaming
```
#include "task.h"
#define os_add_task   xTaskCreate //same issue
```

I meant by "pages of macro constants"  the register map file for microcontroller registers. ex: CMSIS.
when making modifications or making your own it is very important to have IntelliSense.

many thanks

**Comment by sean-mcmanus** [comment]
@AshrafMasoud5 That issue is different -- I've moved it to https://github.com/microsoft/vscode-cpptools/issues/9078
