### ISSUE TITLE
Intelisense mulfunctions when RxCpp is used

### ISSUE THREAD

**Issue by dzmitry-babrovich** [microsoft/vscode-cpptools#5619]
Issue Type: <b>Bug</b>

I have create repository at https://github.com/dzmitry-babrovich/rxcpp-intelisense-bug to reproduce the bug. 
The container installs RxCpp and part of docker image generation. Check README.md for instructions how to reproduce intelisense mulfunctioning when RxCpp is used.

Extension version: 0.28.2
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-28-generic
Remote OS version: Linux x64 5.3.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.43GB (7.79GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: C++ Sample|
|OS|Linux x64 5.3.0-28-generic|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 3400)|
|Memory (System)|15.43GB (7.79GB free)|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
@dzmitry-babrovich 
I tried the provided repro and was able to reproduce the issue when including any files from the `/usr/local/include/rxcpp` path and if the C++ standard version is C++14 or gnu++14 or less. Since the default C++ standard of the gcc-8 compiler that's installed on the docker image is gnu++14, this is what the extension uses as default.

I found that by setting the C++ standard to c++17 or gnu++17, then IntelliSense works again with the included RxCpp file. Is this the same case for your project or does the issue persist even when the C++ standard version is set correctly? Does RxCpp library depend on a specific C++ standard version?

**Comment by dzmitry-babrovich** [comment]
Hi @michelleangela,
I use RxCPP with C++14 because that's what our company uses. As far as I know RxCpp supports C++11 and above. Mind you compilation time is not great. Where does intelisense take it's compiler setting: from CMakeLists.txt or .vscode/c_cpp_properties.json - option cppStandard?

**Comment by michelleangela** [comment]
The C/C++ extension gets IntelliSense configuration from [c_cpp_properties.json](https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp). Information from CMakeLists.txt can be passed on to the extension as well if the "configurationProvider" property is set (see https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference for more info about "configurationProvider ") to a CMake VSCode extension that extracts info from CMakeLists and provides it to the C/C++ extension. The C/C++ extension can also get IntelliSense configuration  info from a compile_commands.json file, by setting the "compileCommands" property in c_cpp_properties.json to the path of a compile_commands.json. Only set either "configurationProvider" or "compileCommands", but not both. If neither of those two properties are set, then IntelliSense will get info from the set properties in c_cpp_properties.json (or default values if no  c_cpp_properties.json is customized).

You can run `C/C++: Log Diagnostics` from the VS Code command palette to see the actual IntelliSense configurations that are used.

**Comment by dzmitry-babrovich** [comment]
Hi - I have added c_cpp_properties.json to the repo and pushed it up. Unfortunatelly I am still observing the same issue. Here what I get in log diagnostic:

-------- Diagnostics - 6/10/2020, 8:24:56 PM
Version: 0.28.3
Current Configuration:
{
    "name": "Linux",
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c18",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "includePath": [
        "/usr/local/include"
    ],
    "compilerArgs": [],
    "browse": {
        "path": [
            "/usr/local/include",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /workspaces/rxcpp-intelisense-bug/main.cpp ]:
    /workspaces/rxcpp-intelisense-bug/main.cpp
Translation Unit Configurations:
[ /workspaces/rxcpp-intelisense-bug/main.cpp ]:
    Process ID: 429
    Memory Usage: 0 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/8
        /usr/include/x86_64-linux-gnu/c++/8
        /usr/include/c++/8/backward
        /usr/lib/gcc/x86_64-linux-gnu/8/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=80300
Total Memory Usage: 0 MB

**Comment by michelleangela** [comment]
It looks like the issue may have something to do with the IntelliSense process (cpptools-srv) being slow to start, may be about 5-6 secs. Note that there will be an IntelliSense (cpptools-srv) per translation unit, but there should only be one extension process (cpptools). The extension process will spawn a cpptool-srv process per translation unit. If the log from `C/C++: Log Diagnostics` show that memory usage is 0 MB or says "no active translation units", it means the cpptools-srv is not running.

Regardless of the C++ standard version, IntelliSense was able to work provided that the cpptools-srv was able to start running. I haven't figure out yet what's causing the IntelliSense process to not start either immediately or not start at all, perhaps this has something to do with the container. 

![image](https://user-images.githubusercontent.com/38734287/84318464-5666bc80-ab23-11ea-85bd-157dcd251d94.png)

![image](https://user-images.githubusercontent.com/38734287/84318679-aba2ce00-ab23-11ea-88f8-bd83b026b259.png)

FYI: I didn't see the uploaded c_cpp_proeprties.json in https://github.com/dzmitry-babrovich/rxcpp-intelisense-bug/tree/master/.vscode, but this may not be a configuration issue, but I can just manually create a local copy of c_cpp_proeprties.json if needed.

**Comment by michelleangela** [comment]
This has been determined to be an issue with the IntelliSense engine that is shared with Visual Studio.

Edit:
A fix is in progress.

**Comment by sean-mcmanus** [comment]
This should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders .
