### ISSUE TITLE
C/C++ syntax highlighting broken after macro definition 

### ISSUE THREAD

**Issue by klinki** [microsoft/vscode-cpptools#562]
After defining macro, syntax highlighting is broken.
Example:
```c
#define hashmap_t khash_t(str)
bool hashMapContainsItem();
```

If I terminate macro with `;` it works as expected. But certain macros cannot be terminated with `;`.

[![Screenshot from 2017-03-14 16-03-35.png](https://s11.postimg.org/aztz7zdwj/Screenshot_from_2017_03_14_16_03_35.png)](https://postimg.org/image/6dxuzmsdb/)

[![Screenshot from 2017-03-14 16-03-13.png](https://s3.postimg.org/c079o964j/Screenshot_from_2017_03_14_16_03_13.png)](https://postimg.org/image/wx3hsx45b/)

**Comment by bobbrow** [comment]
This would be a bug in the C grammar.  You can file an issue here: https://github.com/atom/language-c/issues

**Comment by sean-mcmanus** [comment]
The bug is already fixed in atom/language-c and the Insiders build of VS Code.
