### ISSUE TITLE
Variables missing when debugging

### ISSUE THREAD

**Issue by duckbill70** [microsoft/vscode-cpptools#5620]
Type: Debugger

- OS and Version: macOS Catalina v10.15.5
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.2
- Other extensions you installed (and if the issue persists after disabling them):
- C++ Intellisense: 0.2.2
- ARM Cortex-M GDB Debugger : 0.3.6
- No 'Variables' present within Debug Session

![Screenshot 2020-06-06 at 13 04 02](https://user-images.githubusercontent.com/28783106/83943717-3323d080-a7f6-11ea-9ceb-1e0fc66ff250.png)

Launch.json
`{
  "version": "0.28.2",
  "configurations": [
    {
      "name": "Cortex Debug",
      "cwd": "${workspaceRoot}",
      "executable": "/Users/andrewplatts/Documents/GitHub/StingRay-NextGen-CPP/pca10056/s140/armgcc/_build/nrf52840_xxaa.out",
      "request": "launch",
      "type": "cortex-debug",
      "servertype": "jlink",
      "serverpath": "/Applications/SEGGER/JLink_V670g/JLinkGDBServerCLExe",
      "device": "nRF52840_xxAA",
      "interface": "swd",
      "serialNumber": "683464456",
      "armToolchainPath": "/Users/andrewplatts/opt/gcc-arm-none-eabi-9-2019-q4-major/bin",
      //"showDevDebugOutput": true,
      "runToMain": true,
      "svdFile": "/Users/andrewplatts/Documents/GitHub/StingRay-NextGen-CPP/nRF5SDK160098a08e2/modules/nrfx/mdk/nrf52840.svd"
    },
  ]
}`

**Comment by RisinT96** [comment]
This seems like an issue with the `cortex-debug` extension, it seems to implement it's own debug adapter (correct me if I'm wrong).
Also please format the `launch.json` properly, as a single code block.
```json
{
    "version": "0.28.2",
    "configurations": [
        {
            "name": "Cortex Debug",
            "cwd": "${workspaceRoot}",
            "executable": "path/to/elf",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "jlink",
            "serverpath": "/jlink/gdb-server",
            "device": "nRF52840_xxAA",
            "interface": "swd",
            "serialNumber": "1234567890",
            "armToolchainPath": "/path/to/gdb",
            "showDevDebugOutput": true,
            "runToMain": true,
            "svdFile": "svd"
        },
    ]
}
```

**Comment by WardenGnaw** [comment]
@RisinT96 is correct. The vscode-cpptools supports `launch.json` types `cppdbg` and `cppvsdbg`.

**Comment by duckbill70** [comment]
Hi

The issue was two opposing C/C++ debuggers: C/C++ Extension Version: 0.28.2 and C++ Intellisense: 0.2.2. I disabled the Intellisense extension and the problem has resolved.
