### ISSUE TITLE
Debugging process got stuck at predefined task

### ISSUE THREAD

**Issue by BorisPolonsky** [microsoft/vscode-cpptools#5628]
Issue Type: <b>Bug</b>
### Brief 
Debugging stage never starts as building stage defined in `task` got stuck. The terminal prints out 
things like `Executing task: /usr/bin/g++ -g <path-to-my-workplace>/main.cpp -o /<path-to-my-workplace>/main` and it stays forever. 

If I copy, paste and execute the `/usr/bin/g++ -g <path-to-my-workplace>/main.cpp -o /<path-to-my-workplace>/main` part in my own terminal the program got compiled successfully, however. So I assume it's not either environment setting nor missing dependency e.t.c. that causes the problem. 

### Steps to replicate

- Set up `main.cpp`, `launch.json` and `tasks.json` as specified below:

main.cpp

```
#include <iostream>
using namespace std;


int main()
{
    cout << "hello world!" << endl;
    return 0;
}
```

launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```
task.json
```
{
    "tasks": [
        {
            "type": "shell",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Build and debug main"
        }
    ],
    "version": "2.0.0"
}
```

- Hit F5

The task got stuck no matter what command I specified in `task.json`, even specifying a simple `ls` command (i.e.  `"command": "ls"`) .

Extension version: 0.28.3
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-53-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 3099)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|7.66GB (0.28GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by WardenGnaw** [comment]
Does debugging work if you build on the command line and remove `"preLaunchTask": "C/C++: g++ build active file"` in your `launch.json`?

**Comment by BorisPolonsky** [comment]
> Does debugging work if you build on the command line and remove `"preLaunchTask": "C/C++: g++ build active file"` in your `launch.json`?

No, I commented `//"preLaunchTask": "C/C++: g++ build active file"`, vscode prompts that `Program <path-to-workspace>/.vscode/launch` does not exist. Yet if if continue to click on the `open launch.json` button, it pops out correct file, however. It seems like a new bug to me. 
`

**Comment by WardenGnaw** [comment]
You will need to focus your window on `main.cpp` and then select `F5`.

**Comment by BorisPolonsky** [comment]
> You will need to focus your window on `main.cpp` and then select `F5`.

> Does debugging work if you build on the command line and remove `"preLaunchTask": "C/C++: g++ build active file"` in your `launch.json`?

Sorry, I've just noticed that. 
The answer is **no**. 
I commented `//"preLaunchTask": "C/C++: g++ build active file"`, and ran `/usr/bin/g++ -g $workspace/main.cpp --std=c++11 -o $workspace/main` in my terminal. I focused window on `main.cpp`, and hitted F5, VSCode popped out buttons for debugging (e.g. step, stop) but it does not seem to pasue at any breakpoint and I got no output. It just stuck.

**Comment by BorisPolonsky** [comment]
I reinstalled my OS and VSCode. I'm now on ubuntu 20.04 (instead of 18.04) and the problem's gone. I assume it's something with 18.04. Didn't know if someone else can replicate this problem. Closing now.
