### ISSUE TITLE
Define value not shown during break

### ISSUE THREAD

**Issue by Richhoef** [microsoft/vscode-cpptools#5630]
Type: Debugger

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
When I am debugging a file and hit a breakpoint, the value of the define is not shown on hover. Since I cannot use the define name in the watch window, it would be helpfull to not have to ctrl+click on the define to check its value and place it in the watch window, but to simply see its value on hover (as is the case when I am not paused in a file).

**Comment by WardenGnaw** [comment]
Preprocessor directives disappear after compilation of the program. 
For example:
Code:
```
#define NUMBER_3 3
int x = NUMBER_3;
```
Becomes
`int x = 3;`

the identifier `NUMBER_3` is replaced with the constant `3` so it is not possible for the debugger to find this identifier.

**Comment by sean-mcmanus** [comment]
Maybe they're asking for the language service's hover to show the value while debugging. Might not be possible.

**Comment by Richhoef** [comment]
Yes, the language service knows the value (it can show it in any file you are not breaking in, so why would the language service not be able to show it while debugging? If the debugger knows what to show on hover (functions/variables, etc), the debugger should provide the hover, but if it knows nothing (like while hovering over a define), then let the language service figure it out. And it would know the value. Would be very nice if this would be possible
