### ISSUE TITLE
C - Error Squiggles/Intellisense Don't Work Whatsoever

### ISSUE THREAD

**Issue by KeplerIO** [microsoft/vscode-cpptools#5631]
I'm writing C, not C++. Intellisense/Error squiggles don't even exist as far as I'm concerned.

I'm using the latest versions of both VSCode and the C/C++ extension. I have the MinGW-W64 compilers installed (obviously targeting gcc and NOT g++).

Consider this code sample.

![example](https://user-images.githubusercontent.com/26471970/84246707-d6593c00-aabb-11ea-9287-822e06b4f755.png)

I've not included stdio.h, and yet printf receives no error squiggling or error reporting at all. Hovering the function call will indeed show that VSCode is convinced this returns an int, but how?

This program obviously will not compile, begging me to add the #include <stdio.h> line.

In the extension settings, I've set the path to the MinGW-W64 gcc compiler and set the C standard to C18. Intellisense mode has been set to gcc-x64.

**Comment by sean-mcmanus** [comment]
The program will compile. It gives: "warning: implicit declaration of function 'printf'". We haven't implemented warnings yet. We have another issue tracking that: https://github.com/microsoft/vscode-cpptools/issues/828

**Comment by KeplerIO** [comment]
Laughable.
