### ISSUE TITLE
SSH remote vscode 'No symbols found in...' for c++ files

### ISSUE THREAD

**Issue by yeticle** [microsoft/vscode-cpptools#5633]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.3

**Comment by sean-mcmanus** [comment]
Can you provide more repro details? "No symbols" means there was some problem parsing the file and/or adding the symbols to the database.

**Comment by mingyangSunshine** [comment]
I've also found this problem while using SSH. But it recovered the next day when I opened VS code.

VSCode Version: 1.46.1
OS Version: windows
SSH remote OS: Ubuntu 16.04
C/C++ extension 0.28.3

**Comment by michelleangela** [comment]
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.
