### ISSUE TITLE
Problem with intellisense when using () vs {} for initialization

### ISSUE THREAD

**Issue by LeonFretter** [microsoft/vscode-cpptools#5636]
- Ubuntu 18.04
- VS Code Version: 1.45.1
- C/C++ Extension Version: 0.28.3

compare the following two ways of initialization
```cpp
auto a = FooClass{}; //case 1
auto b = FooClass(); //case 2
```
(round-brace vs curly-brace-initialization)
and consider the moment as soon as i type either:
(
or
{

In case 1, Intellisense is significantly faster in showing me the different constructors of FooClass than in case 2.
case 2 sometimes gets really slow, to the point of being very annoying..
Now that i saw that case 1 is much faster, i hope that there might be a fix, so that case 2 can be just as fast :)
![vscode_issue_new](https://user-images.githubusercontent.com/40633983/84431603-da0bd080-ac2b-11ea-9db0-ce7c719b0674.gif)

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue with std::string. Does it only repro with certain classes? Are you able to provide class that repros the issue?

Does it work okay if you do Ctrl+Shift+Space to invoke the signature help manually with existing code?

Your screenshot doesn't show the slow case giving any results -- do results appear if you wait longer? What is the performance difference in seconds?

**Comment by LeonFretter** [comment]
My example uses vk::DescriptorBufferInfo of vulkan.hpp (cpp version of Vulkan-Api),
i will investigate the behaviour with other classes. The slow behaviour definetely occured before, it was only now that i noticed that list-initialization had come intellisense come so much faster.

I think i have that command linked to Ctrl+Space, as Ctrl+Shift+Space has no effect, but using this shortcut only gives me a list of all sorts of variables and types that i could mean to write, not this inspection into the constructor-arguments.

For this particular case the intellisense indeed doesn't appear when using round-braces, even when waiting for up to a minute or so.

I will investigate the behaviour with other classes and then give an update here.
