### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by caslan** [microsoft/vscode-cpptools#564]
Internal bug id: 393317

Configuration:
OS: Win10 x64
VSCode: 1.10.2
 
Repro Steps: 
1. Open VSCode.
2. Open the latest extension to install it.
3. Restart VSCode to make the extension task effect
4. Download attachment and open with VSCode
5. Use "C++(GDB/LLDB)" Configuration,update "program" and "miDebuggerPath"Configuration in lanuch.json file as following:
            "program": "${workspaceRoot}/a.exe",
            "miDebuggerPath": "C:/cygwin64/bin/gdb.exe",
6. Press F5 to start debugging
 
Expected:
Start debugging without any error.
 
Actual:
 Pop up an error following the pic:

 
Investigation:
1. This issue affect gdb case on Windows.
2. This issue block Ubuntu atuo test on my hyper-v machine, but test machine wrok correctly.

**Comment by WardenGnaw** [comment]
From the ticket:
> There is no this issue in latest build. Could you please help me to confirm this issue have fixed?

Closing
