### ISSUE TITLE
It shows "No symbols found in document" in OUTLINE window.

### ISSUE THREAD

**Issue by chenqiu** [microsoft/vscode-cpptools#5641]
It also shows "No symbols found in document" in OUTLINE window.
OS: win7
extension version: 0.28.3

Upgrade failed, and it shows 
> This undefined version of the extension is incompatible with your OS. Please download and install the "cpptools-win32.vsix" version of the extension.

**Comment by michelleangela** [comment]
@chenqiu 
Could you try re-installing the win32 version of extension? That error means the incorrect binary of the extension was downloaded for that platform and therefore the extension was not installed.

**Comment by bobbrow** [comment]
We do not have enough information to investigate this issue further. If you continue to have issues with the extension, please try @michelleangela's suggestion and let us know if that didn't solve the problem.  Thank you!
