### ISSUE TITLE
Error Warning/Problem Squiggles seem to be incorrect 

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#5643]
- OS and Version: Mac, Version 10.14.6
- VS Code Version: 1.460
- C/C++ Extension Version: v0.28.3
- Other extensions: CodeRunner and C/C++ Clang command adaptor

When initialising vectors in C++, I get a red "problem" squiggle, for no apparent reason. Upon compilation, the code runs perfectly, so as you may imagine it is extremely frustrating to see loads of red when there isn't actually a problem. Additionally, when I use a range-based for loop, I get another error squiggle (not a red squiggle for this), with the problem being described as "range-based for loop is a C++11 extension [-Wc++11-extensions]". However, I compile the code using gnu++17, so why is this a problem? I have tried changing my IntelliSense mode but nothing seems to work. A picture of my screen when this happens is included below:

<img width="917" alt="Screenshot 2020-06-15 at 19 30 12" src="https://user-images.githubusercontent.com/66688430/84693076-ccfa2480-af3e-11ea-998f-6d1a95a78acd.png">

My c_cpp_properties.json are:

{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/usr/local/bin/gcc-9",
            "cStandard": "c18",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

C/C++: Log Diagnostics gives me:
Version: 0.28.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [],
    "compilerPath": "/usr/local/bin/gcc-9",
    "cStandard": "c18",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/sreeshmaheshwar/Documents/c++proj/vect.cpp ]:
    /Users/sreeshmaheshwar/Documents/c++proj/vect.cpp
Translation Unit Configurations:
[ /Users/sreeshmaheshwar/Documents/c++proj/vect.cpp ]:
    Process ID: 18194
    Memory Usage: 23 MB
    Compiler Path: /usr/local/bin/gcc-9
    Includes:
        /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0
        /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/x86_64-apple-darwin18
        /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/backward
        /usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin18/9.3.0/include
        /usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin18/9.3.0/include-fixed
        /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=90300
Total Memory Usage: 23 MB

Additional info: My C/C++ code colour recogniser is also very slow. That is to say, when I type my code, it takes a while for the variables, functions, etc. to change to the right colour (corresponding to the colour theme, that is). This is also annoying, as I have to wait some time before seeing any mistakes, and having blank text that suddenly changes colour after a few seconds is very distracting while I am coding.

**Comment by sean-mcmanus** [comment]
The error you describe is coming from "C/C++ Clang command adaptor". Can you disable that extension and let us know if that fixes it? Our next release is expected to have an improved colorizer.

**Comment by ghost** [comment]
Ahh thank you, this has fixed it. Your help is much appreciated.
