### ISSUE TITLE
Cascade #if defined() doesn't get colored properly

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vscode-cpptools#5646]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 2004
- VS Code Version: 1.46.0
- C/C++ Extension Version: 0.28.3
- Other extensions you installed (and if the issue persists after disabling them): Babel Javascript, CodeLLDB, JavaScript and TypeScript, PlatformIO IDE, Python, IntelliCode. Issue still persists after disabling all other extensions
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
When checking for multiple macro definitions with `#if defined()`, only the first `defined()` is colored properly, the rest is wrong.

**Steps to reproduce**

Code sample:
```
#if defined(A)
    #define B
#elif defined(C)
    #define D
#endif
```

**Expected behavior**

All the `defined()` are colored correctly

<details>
  <summary><strong>Logs</strong></summary>

```
cpptools/getCodeActions: file:///g%3A/Code/C%2B%2B/definetest.cpp (id: 56)
cpptools/activeDocumentChange: file:///g%3A/Code/C%2B%2B/definetest.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///g%3A/Code/C%2B%2B/definetest.cpp (id: 57)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///g%3A/Code/C%2B%2B/definetest.cpp (id: 58)
idle loop: reparsing the active document
Checking for syntax errors: file:///g%3A/Code/C%2B%2B/definetest.cpp
Queueing IntelliSense update for files in translation unit of: G:\CODE\C++\DEFINETEST.CPP
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.283
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/15729831/84787702-84169e80-b018-11ea-86a2-d38e757fadb2.png)

**Comment by Colengms** [comment]
Hi @longnguyen2004 .  The C/C++ Extension provides semantic colorization, however syntactic/lexical colorization is provided by VS Code.  You can confirm this by disabling `C_Cpp.enhancedColorization`, and observing that the inconsistent colorization of `defined` is still present.

The TextMate grammar for C/C++ is provided by this repo: https://github.com/jeff-hykin/cpp-textmate-grammar

I'd suggest following up with an issue in that repo, or the VS Code repo.

**Comment by longnguyen2004** [comment]
Alright thanks for the information, I'll make an issue over there
