### ISSUE TITLE
g++ error no such file or directory in task.json

### ISSUE THREAD

**Issue by supernova276** [microsoft/vscode-cpptools#5647]

**Comment by supernova276** [comment]
the g++ gives the following error probably because of the space in between program files (x86) how can this be fixed
![ss](https://user-images.githubusercontent.com/57044776/84811464-871a8a80-b02a-11ea-98ea-4bece86f0417.png)

**Comment by bobbrow** [comment]
@supernova276, the task builds the file that is active in the editor and it looks like `tasks.json` is the current active file.  Since it's not a c or c++ file, the compilation fails.  We're looking to reduce this confusion by hooking the task provider, but that work has not been completed yet.

**Comment by bobbrow** [comment]
There also seems to be a misquoting of the compiler.  Can you share the contents of your `tasks.json` file?

**Comment by supernova276** [comment]
sure!
 I just started today and i don't really know much abou it ...so i just copied the tasks.json configuration from the  visualstudio.com and just changed the path for command and cwd
![Screenshot (8)](https://user-images.githubusercontent.com/57044776/84814079-90a5f180-b02e-11ea-91ff-c79fcc9c5464.png)

**Comment by bobbrow** [comment]
Delete the first "g++" from the command and that should resolve the error you reported.

`command` should probably be just `C:\\Program Files (x86)\\codeblocks\\MinGW\\bin\\g++.exe` (assuming that's where your compiler resides)

EDIT:  I see you have `cwd` set, so you can set `command` to just `g++.exe` in that case

**Comment by supernova276** [comment]
thanks alot! that helped :)
