### ISSUE TITLE
Request: Add a memory window

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode-cpptools#5648]
Hello,

  Looking through previous issues the question of a memory window had come up from time to time.  One of the basic features of a robust debugger is a memory window.  The memory window should be allow one to chose the data width (8-bit, 16-bit, 32-bit, etc), interact with the memory to modify the values.  Using the command line gdb can be cumbersome and a stop gap, but really need an interactive memory window.

Thanks

**Comment by sean-mcmanus** [comment]
You can upvote the existing issue at https://github.com/microsoft/vscode-cpptools/issues/509 (it has 144 upvotes so far, the top 6th up-voted issue).
