### ISSUE TITLE
Syntax highlighting for __attribute__ is wrong

### ISSUE THREAD

**Issue by karljs** [microsoft/vscode-cpptools#5650]
Issue Type: <b>Bug</b>

Function `__attribute__` annotations in C++ are scoped as function calls by the built-in grammar, and that seems to make it impossible to write a grammar injection that matches on `__attribute__( ... )` as part of a function declaration.

There seems to also be a bug where when I report an issue for the built-in C++ support, it wants me to file it here rather than in the repo where that code lives (the main VSCode repo).  If I should move it there, please just let me know.

Extension version: 0.28.3
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.6.15-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 1789)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.39GB (5.11GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sean-mcmanus** [comment]
The location to file lexical syntax highlighting bugs is https://github.com/jeff-hykin/cpp-textmate-grammar/issues/. Your issue sounds like it could be https://github.com/jeff-hykin/cpp-textmate-grammar/issues/401 .
