### ISSUE TITLE
[WSL] Improve error message when pipeProgram is a invalid path

### ISSUE THREAD

**Issue by caslan** [microsoft/vscode-cpptools#566]
Internal bug id: 394236
Configuration:
OS: Build 15150.rs_onecore_base_bpt1.170305-1700
VSCode: 1.10.2
 
Repro Steps: 
1. Download attachment and copy it to Bash side. [app2.zip](https://github.com/Microsoft/vscode-cpptools/files/842971/app2.zip)
2. Open attachment in VSCode and use "C++(GDB/LLDB)" Configuration,update "program" "pipeTransport" "cwd" and "sourceFileMap"Configuration in lanuch.json file as following:
            "program": "/home/grace/temp/app2/a.out",
            "cwd": "/home/grace/temp/app2",
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "c:\\windows\\sysnative2\\bash.exe",
                "pipeArgs": ["-c"],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/home/grace/temp/app2": "c:\\temp\\app2"
            },
3. Press F5 to start debugging
 
Expected:
It is possible to improve the error message similar like "Unexpected bash.exe.  'c:\\windows\\sysnative2\\bash.exe' No such file or directory"
 
Actual:
Pop up an error message:

**Comment by WardenGnaw** [comment]
We get a pop up now and links to launch.json. Closing.

![image](https://user-images.githubusercontent.com/3953714/37806410-183a508e-2dfd-11e8-8a42-0e4ba0f2efef.png)
