### ISSUE TITLE
Function breakpoint icon disappear for C++ project

### ISSUE THREAD

**Issue by Tina2018** [microsoft/vscode-cpptools#5661]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu Server 18.04 LTS
- VS Code Version: 1.46.0.0
- C/C++ Extension Version: v0.29.0-master
- Other extensions you installed (and if the issue persists after disabling them): none

**To Reproduce**
1. Create an empty folder called projects and create a .cpp file.
2. Open projects folder using VSCode
3. Add following code in .cpp file, you can refer to attachment file
[projects.zip](https://github.com/microsoft/vscode-cpptools/files/4802190/projects.zip)
4. Set a function bp as sum(int,int)
5. Click F5 to start debugging

launch.json refer as below attachment: 
[launch.zip](https://github.com/microsoft/vscode-cpptools/files/4802203/launch.zip)

[Expected]
Function icon should display.

[Actual]
It can hit function bp and function bp icon is display.
![Untitled](https://user-images.githubusercontent.com/35017348/85091431-f5716f80-b219-11ea-8b99-2967a136d533.png)

**Comment by WardenGnaw** [comment]
Function breakpoints appear in the Breakpoints Panel. You can see that `sum` is bound with the solid red triangle. If it failed, it will be a gray triangle.

**Comment by WardenGnaw** [comment]
Closing this issue for now. Please reopen if you have any other questions. 
If it is another issue, please file a new issue.
