### ISSUE TITLE
Can't modify C++ string type variable in local window

### ISSUE THREAD

**Issue by Lili28** [microsoft/vscode-cpptools#5662]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu Server 18.04 LTS
- VS Code Version:1.46.0.0
- C/C++ Extension Version: v0.29.0-master
- Other extensions you installed (and if the issue persists after disabling them): None

**To Reproduce**
* [launch.zip](https://github.com/microsoft/vscode-cpptools/files/4802211/launch.zip)

**Steps to reproduce the behavior**
1. Open tests folder in attachments directly.
[a.zip](https://github.com/microsoft/vscode-cpptools/files/4802212/a.zip)
2. Set a breakpoint on line 20 in a.cpp file.
3. Press F5 to start debugging.
4. When hitting the breakpoint, modify the value of the String type variable in the Local window and press Enter.

**Excepted**
It can modify normally.

**Actual**
It pop up a error message:
![Capture](https://user-images.githubusercontent.com/46367699/85091825-f3f47700-b21a-11ea-85a4-d6f920364bb5.PNG)

**Investigation**
You can successfully modify int type variables in the local window.

**Comment by WardenGnaw** [comment]
With the current way the debug adapter works, we use `-var-assign` to modify variables. `std::string` are noneditable.

>std::string str = "abcdefghijklmnopqrstuvwxyz0abcdefghijk...."

_Variable Creation_
>1: (6172) <-1038-var-create - * "str"
>1038^done,name="var6",numchild="0",value="\"abcdefghijklmnopqrstuvwxyz0abcdefghijk\"...",type="std::__cxx11::string",thread-id="1",displayhint="string",dynamic="1",has_more="0"

_Show attributes_
>-exec -var-show-attributes var6
1: (58541) <-1041-var-show-attributes var6
1: (58547) ->1041^done,attr="noneditable"

**Comment by WardenGnaw** [comment]
Closing this issue for now. Please reopen if you have any other questions. 
If it is another issue, please file a new issue.
