### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by OLINCE** [microsoft/vscode-cpptools#5663]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `0.28.3`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.46.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by WardenGnaw** [comment]
The clipboard content data is not pasted here. Please include those so we can investigate the issue.

**Comment by WardenGnaw** [comment]
Closing due to not enough ifno.
