### ISSUE TITLE
Auto Complete doesn't work in unsaved file

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode-cpptools#5665]
**Type: LanguageService**

**Describe the bug**
Whenever I work on a C/C++ file without saving it, autocomplete menu does not show any suggestions at all whereas it works if I work on a unsaved Python file..
If file is saved, it works fine in all types of files.

- OS and Version: Windows 10 x64
- VS Code Version:1.46.1
- C/C++ Extension Version: 0.28.3

- Does this issue involve using SSH remote to run the extension on a remote machine?: No

**Steps to reproduce**

1. Open a new file by pressing ctrl+N
2. Set syntax to C by pressing ctrl+k m
3. Start writing:
 `#include<stdio.h>`
`main`
4. See error:
You will not see any autocomplete features whereas it gives option to auto complete it to main function if file is saved.

**Expected behavior**

Auto complete should work in unsaved files too

PS:
autocomplete features work in other editors without saving the file.

**Comment by sean-mcmanus** [comment]
This is being tracked by https://github.com/microsoft/vscode-cpptools/issues/3343 . The problem is our LSP process (cpptools) expects all the URIs it receives to be files.
