### ISSUE TITLE
Creating a Header File in C++ Does Not Work

### ISSUE THREAD

**Issue by aaronshahriari** [microsoft/vscode-cpptools#5667]
Type: General

When creating a header file such as "header.h" it lists the file as a C file not a C++ file and therefore will not run the program. I do not know how to fix this and it is keeping me from running the programs properly.

**Describe the bug**
- OS and Version: macOS Catalina
- VS Code Version: VS 1.44.2
- C/C++ Extension Version: 0.28.3
- Other extensions you installed (and if the issue persists after disabling them): Code Runner
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. Go to '..'

**Expected behavior**

**Screenshots**

<img width="193" alt="Screen Shot 2020-06-19 at 5 49 35 PM" src="https://user-images.githubusercontent.com/44651626/85181953-43f02f80-b255-11ea-9a56-b6924c1b7e3f.png">

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by bobbrow** [comment]
Interesting...  This looks like a bug in vscode.  Our extension doesn't pick the icons for files in the explorer.  I installed a different icon pack and didn't see this problem:
![image](https://user-images.githubusercontent.com/12818240/91496043-577ccf80-e870-11ea-843e-0efcf0bb7a6e.png)
