### ISSUE TITLE
[WSL] Pop an error message when press Pause

### ISSUE THREAD

**Issue by caslan** [microsoft/vscode-cpptools#567]
Internal bug id: 394239
Configuration:
OS: Build 15150.rs_onecore_base_bpt1.170305-1700
VSCode: 1.10.2
 
Repro Steps: 
1. Download attachment and copy it to Bash side.
[app2.zip](https://github.com/Microsoft/vscode-cpptools/files/842975/app2.zip)

2. Open attachment in VSCode and use "C++(GDB/LLDB)" Configuration,update "program" "pipeTransport" "cwd" and "sourceFileMap"Configuration in lanuch.json file as following:
            "program": "/home/grace/temp/app2/a.out",
            "cwd": "/home/grace/temp/app2",
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "c:\\windows\\sysnative\\bash.exe",
                "pipeArgs": ["-c"],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/home/grace/temp/app2": "c:\\temp\\app2"
            },
3. Press F5 to start debugging
4. Press Pause
 
Expected:
Pause work correctly
 
Actual:
Pop up an error message:

**Comment by pieandcakes** [comment]
This is an older issue and hasn't had any updates. Please comment/open a new issue if it is still happening.
