### ISSUE TITLE
clear Previous output is not working.

### ISSUE THREAD

**Issue by rishabhkadam** [microsoft/vscode-cpptools#5670]
Issue Type: <b>Bug</b>

The function in Code Runner of Clear Previous Output is not working, I do it manually. Please give a any solution or fix a bug.

Extension version: 0.28.3
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by WardenGnaw** [comment]
This repository is for the Cpptools extension for VS Code. You will want to post your issue on the [CodeRunner Extension GitHub](https://github.com/formulahendry/vscode-code-runner/issues) Issues page.
