### ISSUE TITLE
Persistent red squiggles and slow intellisense

### ISSUE THREAD

**Issue by Doomski99** [microsoft/vscode-cpptools#5672]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.41.1
- C/C++ Extension Version: 0.28.3
- Other extensions you installed (and if the issue persists after disabling them): Reloaded window after disabling all my extensions except for the C/C++ extension and intellicode and the issue is still there.
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
I'm still learning, please excuse my inexperience/english .
This bug seems to happen to an error that only shows up by compiling the file(not always,I'm lost). I get a red squiggle under the line after I compile and then whatever I replace that line with , the editor still retains the same old error as shown in the video I provided. After reloading the window, the error disappears and if I rewrite the error producing line , nothing appears until I compile and thus the same bug occurs.
Also, intellisense in c++ seems slower to me, compared to the java extension for example. In java, while writing , errors and warnings appear almost instantly unlike in c++, it takes a second or two to update and sometimes more even though the code is very small (In C/C++ output console I get Update IntelliSense time (sec): 0.255, though it doesn't seem that fast). Is there any way I can speed it up?
**Steps to reproduce**

c_cpp_properties.json :
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.10240.0\\ucrt"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}

launch.json : 
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "Java Debug (Launch) - Current File",
      "request": "launch",
      "mainClass": "${file}"
    },
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal",
      "justMyCode": true
    },
    {
      "name": "(msvc) Launch",
      "type": "cppvsdbg",
      "request": "launch",
      "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": true,
      "preLaunchTask": "msvc build"
    }
  ]
}

tasks.json:
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "msvc build",
            "type": "shell",
            "command": "cl.exe",
            "args": [
                "/EHsc",
                "/Zi",
                "/Fe:",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "${file}",
                "/W4"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal": "always"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}
**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
idle loop: reparsing the active document
Checking for syntax errors: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp
Queueing IntelliSense update for files in translation unit of: C:\USERS\DOOM\DOCUMENTS\CPPCODES\C++\FORTEST.CPP
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.292
cpptools/getDocumentSymbols: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 298)
cpptools/getDocumentSymbols
Checking for syntax errors: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp
Queueing IntelliSense update for files in translation unit of: C:\USERS\DOOM\DOCUMENTS\CPPCODES\C++\FORTEST.CPP
  tag parsing file: C:\USERS\DOOM\DOCUMENTS\CPPCODES\C++\FORTEST.CPP
textDocument/hover: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 299)
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.254
cpptools/getCodeActions: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 300)
textDocument/hover: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 301)
textDocument/hover: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 302)
cpptools/getCodeActions: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 303)
Database safe to open
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 304)
textDocument/hover: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 305)
cpptools/getCodeActions: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 306)
textDocument/documentHighlight: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 307)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 308)
textDocument/didChange: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 309)
cpptools/getCodeActions: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 310)
cpptools/textEditorSelectionChange
textDocument/hover: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 311)
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
cpptools/getCodeActions: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 312)
cpptools/getDocumentSymbols: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 313)
cpptools/getDocumentSymbols
textDocument/hover: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 314)
cpptools/getCodeActions: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 315)
Checking for syntax errors: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp
Queueing IntelliSense update for files in translation unit of: C:\USERS\DOOM\DOCUMENTS\CPPCODES\C++\FORTEST.CPP
  tag parsing file: C:\USERS\DOOM\DOCUMENTS\CPPCODES\C++\FORTEST.CPP
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.255
textDocument/hover: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 316)
cpptools/getCodeActions: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp (id: 317)
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///c%3A/Users/Doom/Documents/cppcodes/C%2B%2B/fortest.cpp
Queueing IntelliSense update for files in translation unit of: C:\USERS\DOOM\DOCUMENTS\CPPCODES\C++\FORTEST.CPP
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.29
Database safe to open

```
</details>

**Screenshots**

![vscode](https://user-images.githubusercontent.com/45564681/85222370-09a4a080-b3c3-11ea-8baa-8628d6e37316.gif)

**Additional context**

**Comment by Doomski99** [comment]
UPDATE: __cplusplus is outputting 199711L , that means it's using c++98 ,how is that possible? my cpp standard is set to c++17.

**Comment by Doomski99** [comment]
UPDATE 2: I have added "/std:c++latest" to my list of args and and changed cpp standard to c++20 but the bug still remains as seen in the GIF until I recompile or reload the window.

**Comment by sean-mcmanus** [comment]
Those errors are not from our C/C++ extension. They must be coming from another extension or from your build...it looks like from your build -- you need to re-compile to refresh the build squiggles.

Providing IntelliSense features for C/C++ is more difficult/time-consuming than for Java, so a 0.255 sec update time is not likely to be improvable.

**Comment by Doomski99** [comment]
I'm sorry but can you elaborate for me on why my build is stating errors not shown by intellisense ? and is there anyway I can fix it? I mean I'm using the latest MSVC compiler which should be in sync with intellisense no?

**Comment by sean-mcmanus** [comment]
Can you provide a code sample and what the compiler error you're getting is? It's hard to tell what is going on in your screenshot.
