### ISSUE TITLE
Warning: Matches Multiple Schema When Only One Must Validate. [7,9]

### ISSUE THREAD

**Issue by dejannenov** [microsoft/vscode-cpptools#5673]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 Pro Version 2004 OS Build: 19041.329
- VS Code Version: 1.46.1
- C/C++ Extension Version: 0.28.3
- Other extensions you installed (and if the issue persists after disabling them):
AutoHotkey 0.2.2
Azure Repos 1.161.0
Native Debug 0.25.0
Python 2020.6.89.148
Remote - WSL 0.44.4
Rust 0.7.8
- A clear and concise description of what the bug is.
When debugging a RUST Program, VSC shows warning in the Problems tab:

launch.json .vscode
    Matches Multiple Schema When Only One Must Validate. [7,9]

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

A/the attached hello-world.zip contains the entire project directory and launch.json
B/the attached file "vscode-cpptools-ext-warning-matches-multiple-schjemas-screenshot.png"
![vscode-cpptools-ext-warning-matches-multiple-schjemas-screenshot](https://user-images.githubusercontent.com/688538/85230347-97c15c80-b3ac-11ea-8e41-f81d4fab60c2.png)
 shows launch.json and package.json for the spp tools extension side by side with the relevant schema sections (I think)

1. With the extensions above open the project directory and start/debug the hello-world.exe

When looking for matches cppvsdebug in ALL installed extensions - only the ones in cpp tools are found (as expected):

PS C:\users\d\.vscode\extensions> Get-ChildItem -Path .\*.json -Recurse |  Select-String -Pattern '"cppvsdbg"'

ms-vscode.cpptools-0.28.3\package.json:1215:        "type": "cppvsdbg",
ms-vscode.cpptools-0.28.3\package.json:1245:                "default": "cppvsdbg"
ms-vscode.cpptools-0.28.3\package.json:1355:                "default": "cppvsdbg"

**Additional context**
[hello-world.zip](https://github.com/microsoft/vscode-cpptools/files/4809851/hello-world.zip)

*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment]
This is caused by the Native Debug extension -- can you only have either that extension or the C/++ extension enabled at a time?
