### ISSUE TITLE
#include errors detected. Please update your include path.

### ISSUE THREAD

**Issue by Ankur0Sarkar** [microsoft/vscode-cpptools#5674]
Hey guys this is my first time installing the Ms Visual studio code for c++. I wrote a very simple Hello World program but i am getting two errors which are as follows.

1. #include errors detected please update your include path.
2. cannot open source file "wchar.h"(dependency of iostream)

My c_cpp_properties.json file is as follows please tell me the changes i have to do in order to run any program.

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\MinGW\\lib\\gcc\\mingw32\\9.2.0\\include\\c++",
                "C:/MinGW/lib/gcc/mingw32/9.2.0/include/c++/mingw32"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @Ankur0Sarkar .  You might try using the `compilerPath` field.  The compiler at that path will be probed for system includes, defines, C++ standard version, etc..

```
{
    "configurations": [
        {
            "name": "MinGW x86",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\MinGW\\bin\\g++.exe",
            "intelliSenseMode": "gcc-x86"
        }
    ],
    "version": 4
}
```

**Comment by Ankur0Sarkar** [comment]
@Colengms Thanks for your feedback i will look into it but your c_cpp_properties.json does not have a include path so should i just copy your file or should i include the include path of my directory

**Comment by Colengms** [comment]
Hi @Ankur0Sarkar .  The C/C++ Extension will 'probe' the compiler specified by `compilerPath` to determine system #include paths.  You shouldn't need to add MinGW's system include paths yourself manually.
