### ISSUE TITLE
Cpptools using a lot of CPU time

### ISSUE THREAD

**Issue by fabriciofx** [microsoft/vscode-cpptools#5678]
Hi! It's my environment:
- Windows 10 2004
- WSL 2
- Ubuntu 20.04
- Vscode 1.46.1
- Cpptools 0.28.3

And I'm using it to develop a very small cpp application. I noticed cpptools process is using a lot of CPU all the time (note the 46.3%):
```
fbc      13212 46.3 14.8 2830516 948560 pts/1  Sl+  18:36 146:45   /mnt/c/Users/fbc/.vscode-server/extensions/ms-vscode.cpptools-0.28.3/bin/cpptools
```
and it isn't just for a while, but *all* the time (while I'm running vscode/cpptools).

**Comment by fabriciofx** [comment]
@sean-mcmanus I’m developer too. How can I profile cpptools to get a better diagnosis of the problem?

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue. How are you getting those CPU times? I'm seeing low CPU usage with "top". Also, why does it show /mnt as the location for cpptools? It should show ~/.vscode-server/extensions/ms-vscode.cpptools-0.28.3/bin/cpptools. Anything accessing /mnt is expected to be a lot slower on WSL2. Does the issue repro without any files open? What does the C/C++ logging show when you set C_Cpp.loggingLevel to "Debug"? You can attach a debugger and break while the CPU usage is high and provide the call stack for the thread that appears be doing work (it should have a relatively deep call stack). Does it repro for all projects (i.e. a simple project with just a main())? Does it repro when you set the compilerPath to ""? Does it only repro with WSL2 and not Windows?

**Comment by fabriciofx** [comment]
@sean-mcmanus I'm so sorry for the delay! But answering your questions:

1. I was using `ps` to check CPU usage, but I can use top too:

This image is related to an opened vscode with a small c ++ project but neither file or tab opened:
![image](https://user-images.githubusercontent.com/1964562/86198573-4a708800-bb2e-11ea-8e18-fe5bff21e97f.png)

And this image is after more than 30 minutes with only two (small) c++ files opened:
![image](https://user-images.githubusercontent.com/1964562/86200505-409d5380-bb33-11ea-91f5-290426438efb.png)

2. I'm using WSL2 and updated to `ms-vscode.cpptools-0.29.0-insiders` and the problem remains the same

3. I changed my home dir in WSL to be the same for Windows 10 home dir (`C:\Users\fbc`). Here the parameters used by WSL to mount `/mnt`:
```
C:\ on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
```
4. Without any files open, the CPU usage of `cpptools` process is around 15% to 20% percent, which I consider high

5. Sorry, but I didn't understand these instructions:

*What does the C/C++ logging show when you set C_Cpp.loggingLevel to "Debug"? You can attach a debugger and break while the CPU usage is high and provide the call stack for the thread that appears be doing work (it should have a relatively deep call stack). Does it repro for all projects (i.e. a simple project with just a main())? Does it repro when you set the compilerPath to ""?*
Where I change the `C_Cpp.loggingLevel to "Debug"`?

Just note I'm not using vscode to run or debug my c++ program, just to *edit* my files, which uses syntax highlight and vscode's intellisense.

So please, send more detailed instructions I can collect more information about this issue.

**Comment by sean-mcmanus** [comment]
Accessing files under /mnt is expected to be slow. Do you have the same performance issue when using files under ~?

C_Cpp.loggingLevel is a setting you can change (File->Preferences->Settings) that causes a C/C++ panel to be available in the Output window.

**Comment by fabriciofx** [comment]
@sean-mcmanus My problem isn't be or not be slow. It's about `cpptools` (and only this process) consuming around 40% to 50% CPU time during 30 minutes in a c++ project with no more than 15 (small) files. And I'm using a SSD!

About `C_Cpp.loggingLevel` setting, here it's the configurations:
![image](https://user-images.githubusercontent.com/1964562/86275819-43875b00-bbaa-11ea-90db-62ae45eeffdd.png)

I will change `C_Cpp.loggingLevel` to `None` and I'll observe the behaviour, ok?

**Comment by fabriciofx** [comment]
@sean-mcmanus `cpptools` program is closed source? If not, where can I found the sources?

**Comment by sean-mcmanus** [comment]
cpptools is closed source. loggingLevel should be "Debug" and not "None".

**Comment by fabriciofx** [comment]
@sean-mcmanus Ok. I'll change it now. Thanks!

**Comment by aka-mj** [comment]
I'm seeing the same issue under linux, except cpptools is using 100% of the CPU and consuming all the memory and swap space till its full and the system grinds to a halt.

```
> code --version
1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
> cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
> uname -a
Linux ubuntu 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fabriciofx** [comment]
@sean-mcmanus @dangerousHobo Just to report, I figure out what was causing this problem. As @sean-mcmanus have said, the problem is due the filesystem. My home dir is mounted in an Windows 10 NTFS filesystem, which WSL mount and use as 9p (Plan9) filesystem. After I moved my home dir to a ext4 partition, the problem vanished. So, I'll close this issue.
