### ISSUE TITLE
Execute a specified command before cpp debugger launching

### ISSUE THREAD

**Issue by Rullec** [microsoft/vscode-cpptools#5679]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.46.1
- C/C++ Extension Version: 0.28.3
- Other extensions you installed (and if the issue persists after disabling them): Yes
- A clear and concise description of what the bug is.

Specificially, I want to **execute this command** `handle SIGSEGV pass nostop` **everytime before the cpp debugger launches** in order to ban `SIGSEGV` during debugging. How can I do for it?

I know it can be achieved by setting in `~/.gdbinit`, but this certainly will affect all of projects in this end. Can I set up it in for example `launch.json` or `c_cpp.json`, so that it **only affects a single project**?

I checked the [doc](https://code.visualstudio.com/docs/editor/debugging) but didn't managed to get the answer.

Would you please help me about it? Any suggestion is appreciated. 

Thanks!

**Comment by WardenGnaw** [comment]
You will want to use [`setupCommands`](https://code.visualstudio.com/docs/cpp/launch-json-reference#_setupcommands) in your `launch.json`. You can configure it for a specific configuraiton in `launch.json`.

We will execute the `text` on start of the debugger.

**Comment by Rullec** [comment]
> setupCommands

Thank you for you reply! I will test it quickly and come back for the result!

**Comment by Rullec** [comment]
Sorry for my delayed reply. It works well, Thanks!
