### ISSUE TITLE
How to fix the error "identifier std not recognised" and " identifier cout not recognised" in VS code in C++?

### ISSUE THREAD

**Issue by Ankur0Sarkar** [microsoft/vscode-cpptools#5682]
Guys I am using the Vs Code version 1.46.1 on Windows 10 (64 bit). Currently i am getting problems like "identifier std not recognised" and "identifier cout not recognised" while compiling a simple helloworld program which goes as follows :

      #include <iostream>

      using namespace std;

      int main ()

      {

     cout <<"Hello World";

      }
Please help me in fixing this problem. It is appreciated if you can give me the c_cpp_properties.json , tasks.json, and launch.json file of your Vs code (latest version if possible)

**Comment by michelleangela** [comment]
@Ankur0Sarkar 

The C/C++ extension has a [tutorial on using the tasks.json to compile code](https://code.visualstudio.com/docs/cpp/config-msvc#_build-helloworldcpp). The sample code is similar to yours. Could try out the tutorial's sample?

**Comment by michelleangela** [comment]
Also, could you provide the tasks.json and launch.json files that you used that led to the issue?
