### ISSUE TITLE
How to install c++17 in dev c++ 5.11 tdm 4.9.2?

### ISSUE THREAD

**Issue by Ankur0Sarkar** [microsoft/vscode-cpptools#5685]
Guys i want to do programming in the latest c++17 standard and the software i use is dev c++ 5.11 TDM 4.9.2. Can anyone help me

**Comment by sean-mcmanus** [comment]
Your gcc 4.9.2 compiler only supports c++11 (see https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Standards.html#Standards). You would need to update to a newer compiler.
