### ISSUE TITLE
C++ debugger: Input character limit in a line is 4095, can i remove that limit?

### ISSUE THREAD

**Issue by eldon922** [microsoft/vscode-cpptools#5686]
So i use c++ debugger and need to input a long line. but when I copy paste the line to the terminal debugger, the line cuts off and i count only 4095 characters allowed. i can't type more character. how to prevent this limit?

**Comment by WardenGnaw** [comment]
Can you fill out the debugger template?

----
**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them): 
- Which terminal program are you using?

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by eldon922** [comment]
**Describe the bug**

- OS and Version: Windows 10 1903
- VS Code Version: 1.46.0
- C/C++ Extension Version: 0.28.3
- Other extensions you installed (and if the issue persists after disabling them):
- Which terminal program are you using? default one

**To Reproduce**
Steps to reproduce the behavior:

1. Go to a c++ file
2. Press f5 to start debug
3. Enter long input (a line with number characters more than 4095)
4. The line cuts off and I can't type more character in that line

**Comment by aoyulong** [comment]
I have the same problem.

**Comment by WardenGnaw** [comment]
>Which terminal program are you using? default one

If you are using cmd.exe, they have a limitation. https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation

For large inputs, I would recommend reading from a file.
