### ISSUE TITLE
getRemoteOSAndProcesses uses bash

### ISSUE THREAD

**Issue by andyneff** [microsoft/vscode-cpptools#569]
Not all Linuxes have `bash`, but practically all of them have `sh`. From what I can see, there are no features from `bash` that are not in `sh` being used. Would it be possible to change the `attachToProcess.js` from

```javascript
        const command = `bash -c 'uname && if [ $(uname) == "Linux" ] ; then ${nativeAttach_1.PsProcessParser.psLinuxCommand} ; elif [ $(uname) == "Darwin" ] ; ` +
            `then ${nativeAttach_1.PsProcessParser.psDarwinCommand}; fi'`;
```

to

```javascript
        const command = `sh -c 'uname && if [ $(uname) == "Linux" ] ; then ${nativeAttach_1.PsProcessParser.psLinuxCommand} ; elif [ $(uname) == "Darwin" ] ; ` +
            `then ${nativeAttach_1.PsProcessParser.psDarwinCommand}; fi'`;
```

This comes up more often when using the `pipeTransport` to debug on other operating systems.

**Comment by alex-che** [comment]
Stumbled upon the same problem when trying to set up vscode remote debugging with an embedded Linux device. Ended up making the same changes in `attachToProcess.js` and it helped. Seems like using 'bash' does not give anything useful here, but sacrifice cross-platformability.
