### ISSUE TITLE
Having problem running g++ in terminal of VS code

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#5692]
when i wrote a programm and open new terminal 
i type g++ .\tut1.cpp
it shows:

PS D:\c++ course> g++ .\tut1.cpp
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../libmingw32.a(main.o):(.text.startup+0xc0): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
PS D:\c++ course>

**Comment by WardenGnaw** [comment]
Do you have MinGW bin folder in your `$PATH`?
