### ISSUE TITLE
cpptools not working for Find all reference

### ISSUE THREAD

**Issue by chunyang-wen** [microsoft/vscode-cpptools#5693]
**Type: LanguageService**

**Describe the bug**
- OS and Version: mac 10.15.5 (19F101)
- VS Code Version:
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
- C/C++ Extension Version: v0.29.0-insiders, ms-vscode.cpptools
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Find all reference does not work. I cannot find the member variable reference in the header. For example

```cpp
// header

class A {
public:
    void foo();
private:
    int foo_;
};

// cpp
#include <iostream>

#include "a.h"

void A::foo() {
    std::cout << foo_ << std::endl;
}

```

I can `Find all reference` for `foo`. It will print the error in the image below.

BTW, I am using the tensorflow repo. Preivous code is just a simplified demonstration, not a minmal reproducible case.
**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
```
</details>

**Screenshots**

**Additional context**

![image](https://user-images.githubusercontent.com/2911134/85657303-7205c180-b6e4-11ea-8ec8-8f72d6297fd6.png)
![image](https://user-images.githubusercontent.com/2911134/85658347-bba2dc00-b6e5-11ea-8e26-dfcb422cf070.png)

**Comment by paczerny** [comment]
I have similar issue with the new cpptools version 0.29.0-insiders on Ubuntu 20.04.
Commands "C/C++ Switch Header/Source", "Go to Definition" doesn't work in this version.

Both commands are working in cpptools version 0.28.3

**Comment by sean-mcmanus** [comment]
@chunyang-wen I'm not reproing the issue with the sample code. Can you run C/C++: Log Diagnostics?
![image](https://user-images.githubusercontent.com/19859882/85796324-99fa2280-b6ee-11ea-9d42-50abbd07353a.png)

I haven't tried with tensorflow. @michelleangela Were you going to look at tensorflow?

@paczerny Can you provide more repro info? It's working for me so far with Ubuntu 20.  Are you getting the "No IL Available" or does it just fail to find results? If it's failing to find results, it's most likely an old cpptools process has a lock on your database (killing all the cpptools processes might fix it).

**Comment by sean-mcmanus** [comment]
A similar symptom with tensorflow was reported at https://github.com/microsoft/vscode-cpptools/issues/2976 .

**Comment by sean-mcmanus** [comment]
@chunyang-wen Is this a regression compared to 0.28.3?

**Comment by chunyang-wen** [comment]
> @chunyang-wen Is this a regression compared to 0.28.3?

Regression？ I haven't used 0.28.3.

> Can you run C/C++: Log Diagnostics?

How to run this?

I have tried to kill cpptools related processes and even restart vscode several times. Bad luck here.

**Comment by chunyang-wen** [comment]
![image](https://user-images.githubusercontent.com/2911134/85827154-4227ee00-b7b8-11ea-8962-0183396e02a1.png)
tensorflow/core/framework/op.[h/cc]

Go to definitions not working.

**Comment by chunyang-wen** [comment]
![image](https://user-images.githubusercontent.com/2911134/85827287-9206b500-b7b8-11ea-88ee-8a21004c5965.png)

**Comment by paczerny** [comment]
> @paczerny Can you provide more repro info? It's working for me so far with Ubuntu 20. Are you getting the "No IL Available" or does it just fail to find results? If it's failing to find results, it's most likely an old cpptools process has a lock on your database (killing all the cpptools processes might fix it).

Thanks, It was probably locked DB by older process. Reboot of the system solves the issue.

**Comment by michelleangela** [comment]
@chunyang-wen 

Could you try installing version 0.28.3 and verify if the issue reproduces with that version?

To run "C/C++: Log Diagnostics", open the VS Code command palette and type "C/C++: Log Diagnostics" then press enter to run the command. The output logs will be printed out in the VS Code output window.

**Comment by chunyang-wen** [comment]
-------- Diagnostics - 6/27/2020, 9:54:34 PM
Version: 0.28.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "${workspaceFolder}/"
        ]
    },
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": []
}
No active translation units.

**Comment by chunyang-wen** [comment]
I reinstalled cpptools, so it changes to version 0.28.3 which is a stable version I think. IMHO.

**Comment by michelleangela** [comment]
> I reinstalled cpptools, so it changes to version 0.28.3 which is a stable version I think. IMHO.

Does find all references work in version 0.28.3?

The diagnostic logs you provided does not show any active translation units which indicates no IntelliSense engine was running. Could you try running the "C/C++: Log Diagnostics" again while a source file is open?

**Comment by chunyang-wen** [comment]
[Warning] Some references may be missing, because workspace parsing was incomplete when Find All References was started.

**Comment by chunyang-wen** [comment]
-------- Diagnostics - 7/7/2020, 11:04:42 PM
Version: 0.29.0-insiders
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "${workspaceFolder}/"
        ]
    },
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": []
}
Translation Unit Mappings:
[ /Users/chunyangwen/opensource/tensorflow/tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc ]:
    /Users/chunyangwen/opensource/tensorflow/tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc
Translation Unit Configurations:
[ /Users/chunyangwen/opensource/tensorflow/tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc ]:
    Process ID: 1850
    Memory Usage: 59 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Users/chunyangwen/opensource/tensorflow
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/grpc/include
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/execroot/org_tensorflow/bazel-out/host/genfiles
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/jsoncpp_git/include/json
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/com_google_absl/absl/base/internal
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/external/com_google_absl
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/protobuf_archive/src
        /Users/chunyangwen/opensource/tensorflow/third_party/eigen3
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/farmhash_archive/dev
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110003
Total Memory Usage: 59 MB

**Comment by sean-mcmanus** [comment]
> [Warning] Some references may be missing, because workspace parsing was incomplete when Find All References was started.

That just means it's still in the process of scanning for files it may need to parse for potential references. Does the bug repro with 0.28.3 still?

**Comment by chunyang-wen** [comment]
-------- Diagnostics - 8/16/2020, 8:30:55 AM
Version: 0.30.0-insiders2
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "${workspaceFolder}/"
        ]
    },
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": []
}
Translation Unit Mappings:
[ /Users/chunyangwen/opensource/tensorflow/tensorflow/core/kernels/save_restore_v2_ops.cc ]:
    /Users/chunyangwen/opensource/tensorflow/tensorflow/core/kernels/save_restore_v2_ops.cc
[ /Users/chunyangwen/opensource/tensorflow/tensorflow/core/util/tensor_bundle/tensor_bundle.cc ]:
    /Users/chunyangwen/opensource/tensorflow/tensorflow/core/util/tensor_bundle/tensor_bundle.cc
    /Users/chunyangwen/opensource/tensorflow/tensorflow/core/util/tensor_bundle/tensor_bundle.h
Translation Unit Configurations:
[ /Users/chunyangwen/opensource/tensorflow/tensorflow/core/kernels/save_restore_v2_ops.cc ]:
    Process ID: 6412
    Memory Usage: 39 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Users/chunyangwen/opensource/tensorflow
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/execroot/org_tensorflow/bazel-out/host/genfiles
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/protobuf_archive/src
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/jsoncpp_git/include/json
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/com_google_absl/absl/base/internal
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/external/com_google_absl
        /Users/chunyangwen/opensource/tensorflow/third_party/eigen3
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110003
[ /Users/chunyangwen/opensource/tensorflow/tensorflow/core/util/tensor_bundle/tensor_bundle.cc ]:
    Process ID: 6425
    Memory Usage: 47 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
        /Users/chunyangwen/opensource/tensorflow
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/execroot/org_tensorflow/bazel-out/host/genfiles
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/protobuf_archive/src
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/external/com_google_absl
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/jsoncpp_git/include/json
        /private/var/tmp/_bazel_chunyangwen/9c12f2c26671947ef0481b4e1b9a399a/external/com_google_absl/absl/base/internal
        /Users/chunyangwen/opensource/tensorflow/third_party/eigen3
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=110003
Total Memory Usage: 86 MB

It seems that this version solves the problem. Close for now. Thanks for all the help.
