### ISSUE TITLE
Imitate Visual C++ with MinGW or other C++ compilers (for Python packages based on Visual C++)

### ISSUE THREAD

**Issue by lorenzznerol** [microsoft/vscode-cpptools#5695]
######################################################################
I had asked this feature request before against vscode core editor on https://github.com/microsoft/vscode/issues/100764#event-3469656740 and I was asked to re-open either against vscode-python or vscode-cpp. Now vscode-python cannot do anything about it: https://github.com/microsoft/vscode-python/issues/12540, this is the last vscode try. After this, I will might ask Visual C++, MinGW or Clang. ######################################################################
This is a full copy of https://stackoverflow.com/questions/62149329/imitate-visual-c-with-mingw-or-other-c-compilers-for-python-packages-based

With an interesting comment from @David Macek
The C++ ABIs (possibly headers even) of GCC and MSVC are just incompatible. You might have some luck using Clang, but I don't guarantee anything. /// If you're concerned about disk space, you might try installing the requisites and then stripping the parts irrelevant to Python packages. There might even be a way to make something of a portable MSVC toolchain, but don't distribute it (I believe it's not allowed in the license).
######################################################################

Is there a way to use MinGW as a substitute of MS Visual C++? A lot of Python packages need VS C++ to be installed: 4.5 GB of disk space! MinGW takes only 450 MB and reaches the same aim to compile C/C++. 

I am using Visual Studio Code, and I try to avoid the Microsoft Visual C++ installation that is proposed here under 3) --> *You can also install just the C++ Build Tools*: https://code.visualstudio.com/docs/cpp/config-msvc/#_prerequisites

Perhaps there is just a trick needed to imitate MS Visual C++ with MinGW, so that the Python packages directly find the MinGW compiler as if it were MS Visual C++? 

Perhaps adding symlinks to the lib directory and adding some system variable path?

My question is strongly linked with https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat/51087608#51087608

The error that I get when I install a package that needs MS Visual C++ as an example, installing `pip install dtaidistance`:

      creating build\temp.win-amd64-3.7\Release\dtaidistance

      C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Admin\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\Admin\Anaconda3\include -IC:\Users\Admin\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" /Tcdtaidistance/dtw_c.c /Fobuild\temp.win-amd64-3.7\Release\dtaidistance/dtw_c.obj /openmp /Ox /fp:fast /favor:INTEL64 /Og

      cl : Befehlszeile warning D9035 : Die Option "Og" ist veraltet und wird in einer der n„chsten Versionen entfernt.

      dtw_c.c

      C:\Users\Admin\Anaconda3\include\pyconfig.h(59): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "io.h": No such file or directory

      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

      ----------------------------------------

      ERROR: Failed building wheel for dtaidistance

      Running setup.py clean for dtaidistance

    Failed to build dtaidistance

    Installing collected packages: dtaidistance

      Running setup.py install for dtaidistance ... error

        ERROR: Command errored out with exit status 1:

         command: 'C:\Users\Admin\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-5lb8uekg\\dtaidistance\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-5lb8uekg\\dtaidistance\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-dzfe2cwr\install-record.txt' --single-version-externally-managed --compile

             cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-5lb8uekg\dtaidistance\

After installing only MSVC (1.8 GB) - only that, as a test to see if that is already all I need:

[![installation of only MSVC][1]][1]

We see that the installation still fails, but the error changes slightly, as at least `ERROR: Failed building wheel for dtaidistance` has disappeared now, see the following screenshot:

        creating build\temp.win-amd64-3.7\Release\dtaidistance

        C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Admin\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\Admin\Anaconda3\include -IC:\Users\Admin\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" /Tcdtaidistance/dtw_c.c /Fobuild\temp.win-amd64-3.7\Release\dtaidistance/dtw_c.obj /openmp /Ox /fp:fast /favor:INTEL64 /Og

        cl : Befehlszeile warning D9035 : Die Option "Og" ist veraltet und wird in einer der n„chsten Versionen entfernt.

        dtw_c.c

        C:\Users\Admin\Anaconda3\include\pyconfig.h(59): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "io.h": No such file or directory

        error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

        ----------------------------------------

    ERROR: Command errored out with exit status 1: 'C:\Users\Admin\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jr44cxi8\\dtaidistance\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jr44cxi8\\dtaidistance\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-t_8xl3_a\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

After installing the other 4 checkboxes directly below the MSVC checkbox in the screenshot of MS Visual++ above, I could install the package.

Perhaps changing the assigned `C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe` somewhere in the python settings to MinGW gcc compiler `C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\c++.exe` might already solve it? 

  [1]: https://i.stack.imgur.com/dVgKN.png

**Comment by sean-mcmanus** [comment]
MinGW uses gcc or clang, which are different compilers than that provided by Visual C++, which is the cl.exe compiler, although clang has more flags that can be configured to behave more like cl.exe in regards to what it will compile (or clang-cl.exe). So your code may not compile with MinGW.

You would have to talk with the Python library or whatever you're trying to compile to see if they can make it build with MinGW.

**Comment by lorenzznerol** [comment]
There are too many scattered packages using Visual C++, a centralized solution would be best, I would rather ask Visual C++ if I can somehow contact that. What do you think about the following comment of @david Macek:
_If you're concerned about disk space, you might try installing the requisites and then stripping the parts irrelevant to Python packages. There might even be a way to make something of a portable MSVC toolchain, but don't distribute it (I believe it's not allowed in the license)._

**Comment by sean-mcmanus** [comment]
@lorenzznerol Have you tried filing an issue at https://developercommunity.visualstudio.com/content/idea/post.html?space=62 ?

**Comment by lorenzznerol** [comment]
@sean-mcmanus thank you, that is done now, see https://developercommunity.visualstudio.com/idea/1093559/imitate-visual-c-with-mingw-or-other-c-compilers-f.html

**Comment by lorenzznerol** [comment]
Seems as if it is only possible to use MinGW compiler till Python 3.4 by adding a "distutils.cfg" to the folder "\Lib\distutils" in Python install directory. 
See https://stackoverflow.com/questions/51397164/microsoft-visual-c-14-0-is-required/55452735?noredirect=1#comment110750033_55452735 referring to https://wiki.python.org/moin/WindowsCompilers#GCC_-_MinGW_.28x86.29 for details.
At least, going down to Python 3.4 would perhaps solve it. That again would probably only be relevant for those with very small space left, e.g. on a netbook with just 64 gb disk size, and you still want to use a C++ compiler.

**Still, it would be nice to have that MinGW "distutils.cfg" workaround for the recent Python versions as well.**

**Comment by zooba** [comment]
Hi @lorenzznerol 

You seem to be asking about something that belongs with the Python community, rather than with the compilers. Sorry to redirect you again, but it really does belong at https://discuss.python.org/c/packaging/14 and specific bug reports at https://github.com/pypa/setuptools

To preview what the replies will be:
* CPython (specifically distutils and setuptools) currently only support MSVC on Windows, and not any other distros
* we're aware of the very large installation size of MSVC and the WinSDK, and so are the relevant teams at Microsoft, but all we can say right now is "sorry"
* it would be great for Linux source compatibility if the Microsoft CRT was closer to glibc, but that's much easier said than done
* the recommended approach is to compile once ("pip wheel") on a machine with the tools, and then install the precompiled versions on other machines (we actually recommend this for the package developers, but not everyone in the community is willing/able to support Windows...)

I'll copy-paste this into the DevCommunity reply, in case anyone at Microsoft sees that and wants to pursue it from our side. Best thing you can do is post your concerns to the Python community. Those are the people who can make the changes you're asking for.

**Comment by lorenzznerol** [comment]
@zooba, thank you for this, it is now opened at https://discuss.python.org/t/imitate-visual-c-with-mingw-or-other-c-compilers-for-python-packages-based-on-visual-c/4609
