### ISSUE TITLE
Debug with gcc9 and gdb9.2 doesn't work due to SIGUSR1 signal

### ISSUE THREAD

**Issue by AlexanderChiuluvB** [microsoft/vscode-cpptools#5696]
Type: Debugger

I am tring to debug with ClickHouse Source Code with gcc9 and gdb9.2. I launch a gdbserver, and when I set the breakpoint, the programe jump to the breakpoint perfectly. But when I step over, it does't work, showing that `user defined signal 1` when i continue to step over, it just loop back and keep returning the breakpoint I set, and still shows `user defined signal 1`

![image](https://user-images.githubusercontent.com/31793655/85714305-e0667600-b71c-11ea-8f97-e1fe4637dd8d.png)

But when I try to downgrade the gcc version to gcc8, it works perfectly.

Here's my launch.json config.
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/server/clickhouse_install/bin/clickhouse-server",
            "args": ["--config=/server/clickhouse_install/etc/clickhouse-server/config.xml"],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "logging": {
                "moduleLoad": false,
                "engineLogging": true,
                "trace": false
            },
            "linux": {
                "MIMode": "gdb",
                "miDebuggerPath": "/usr/bin/gdb",
                "miDebuggerServerAddress": "11.167.232.230:2333",
            },
        }
    ]
}
```

**Describe the bug**
- OS and Version: Ubuntu18.04
- VS Code Version: latest
- C/C++ Extension Version:v0.28.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

I google it and find a solution that I can use `handle SIGUSR1 nostop` to ignore the signal.
But how can I do so in such occasion? Where can I set this in vscode?

**Comment by WardenGnaw** [comment]
You will want to use [`setupCommands`](https://code.visualstudio.com/docs/cpp/launch-json-reference#_setupcommands) in your `launch.json`. You can configure it for a specific configuraiton in `launch.json`.

We will execute the `text` on start of the debugger.

**Comment by AlexanderChiuluvB** [comment]
> You will want to use [`setupCommands`](https://code.visualstudio.com/docs/cpp/launch-json-reference#_setupcommands) in your `launch.json`. You can configure it for a specific configuraiton in `launch.json`.
> 
> We will execute the `text` on start of the debugger.

thanks alot! I have solved the problem

**Comment by vladimir-golovchenko** [comment]
Just share the related settings for attach-case:

```json
{
    "version": "0.2.0",
    "configurations": [    
        {
            "name": "debugging of local ClickHouse server",
            "type": "cppdbg",
            "request": "attach",
            "program": "${workspaceFolder}/build/programs/clickhouse-server",
            "processId": "${command:pickProcess}",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "ignore SIGUSR1 signal",
                    "text": "handle SIGUSR1 nostop noprint pass"
                }
            ]            
        }
    ]
}
```

**Comment by Alois1505** [comment]
I have a similar issue. I want to use SIGINT and I included the SetupCommand as proposed.
Each time I start my application inside VSCode with "RunInTerminal" or from the shell, pressing Ctrl-C works as expected. But i my application is started either with Debug or with the configured launch setting and I press Ctrl-C, the application is terminated immediately.
When I stop the debugger at startup (beginning at the entry to main()), the command info signals SIGINT shows:
Signal        Stop	Print	Pass to program	Description
SIGINT        No	No	Yes		Interrupt
What can I do to achieve the desired behavior?
