### ISSUE TITLE
there is no task option for building the active file by clang/clang++ on windows?

### ISSUE THREAD

**Issue by FischLu** [microsoft/vscode-cpptools#5697]
I am using windows and msys2 + clang, I would like to compile my cpp code by clang++ in vscode. However, there is only three options when I create tasks with following step:
press F1 -> input tasks: configure default build task
then the popup window has only three options without clang.
![image](https://user-images.githubusercontent.com/10261662/85719733-fdd11b00-b6ef-11ea-8b08-1f2c2ff87216.png)

Of course I can select g++ and modify it to use clang, but if there is an option, that would be perfect. Is there a way I can create a custom task template by myself? Thank you

**Comment by sean-mcmanus** [comment]
Is your msys2 clang located in some default location? Is it at \\msys64\\mingw64\\bin\\? What's the exact compiler name? clang++.exe? We don't have msys + clang in our list of compilers to auto-detect, but we might be able to add it.

The workaround is to set your compilerPath to that msys2 clang -- that should cause it to be detected by our build task system.

**Comment by FischLu** [comment]
Thank you for the response. My clang locates in default location, more specifically "d:\msys64\mingw64\bin\clang.exe" and "d:\msys64\mingw64\bin\clang++.exe". The I have added "d:\msys64\mingw64\bin" into my environment PATH. After add clang path to compilerPath, I can select clang option now. Thank you.

**Comment by sean-mcmanus** [comment]
Thanks for the info. We've added the msys clang paths to our search paths for our next release (currently we only check for gcc/g++).

**Comment by sean-mcmanus** [comment]
msys clang paths should be auto-discovered at their default locations with https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders2 .
