### ISSUE TITLE
Open file from call stack during debug session broken when currently opened folder is on a network share

### ISSUE THREAD

**Issue by callumdmay** [microsoft/vscode-cpptools#5699]
Type: Debugger

Opening a VSCode session in a network share on another machine works great and debugging works as expected, however when pausing at a breakpoint, the current file that the breakpoint belongs to does not get resolved correctly and uses the local path (C:\src\.. etc.) to the file and not the network share path (\\remote-machine\src...).  The same occurs when you click on any frame in the callstack, an error pops up "Unable to resolve non-existing file...". I can repro this for C++.

**Describe the bug**
Version: 1.46.1 (user setup)
Commit: cd9ea64
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601
- C/C++ Extension Version: 0.28.3

**To Reproduce**
1. Create a VM or use another machine on the same network and install VS Code on it. 
2. On your current machine, share a src folder onto the network that has a working debug (launch.json) setup.
3. On the VM, open VS Code on the network share src folder
4. Set a breakpoint, start a debug session
5. Trigger the breakpoint, observer that the file that the breakpoint was set on is not opened when the breakpoint is hit and an error pops up  "Unable to resolve non-existing file..."
6. Click on different frames in the call stack and observe the same behaviour

```
{
      "name": "Launch",
      "type": "cppvsdbg",
      "request": "launch",
      "program": "${workspaceFolder}/out/debug_x64/program",
      "args": [
        "--user-data-dir=C:/profile",
      ], // Optional command line args
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}/out/debug_x64",
      "environment": [],
      "externalConsole": true,
      "preLaunchTask": "build",
    }
```
<img width="278" alt="Annotation 2020-06-25 084300" src="https://user-images.githubusercontent.com/10503759/85752025-ea0dc080-b6bf-11ea-8758-fcc893f32f4c.png">

**Comment by WardenGnaw** [comment]
Can you use [`sourceFileMap`](https://code.visualstudio.com/docs/cpp/launch-json-reference#_sourcefilemap) to map the local file paths it tries to search for to the file share path?

**Comment by callumdmay** [comment]
This worked, is this the recommended way to do it? This wasn't obvious to me when everything else "just worked"

**Comment by WardenGnaw** [comment]
This is the way to do it if you are building in a different location. When you compile your program with symbol information, it takes note of where the original file was when it was built relative to the compiler's perspective. 

The debug adapter allows you to modify where these file can be found with `sourceFileMap`.

**Comment by callumdmay** [comment]
Ah right of course. Thanks!
