### ISSUE TITLE
"the source \cygdrive\c\Users... not available"

### ISSUE THREAD

**Issue by mhobelsb** [microsoft/vscode-cpptools#57]
Hello,
I am using VSC on Windows 10, Version 1.1.1 with C/C++ for VS Code 0.6.0. For debugging i use cygwin x64. The debugger starts just fine but I do not see the source code while debugging. As far as I can see it has something to do with the source code lookup path. Is there a way to map the source code lookup path? 

Thx. 
Martin

**Comment by jacdavis** [comment]
Is your source code stored in the same location as it was compiled from? The symbol files produced by the compiler will point to the original source code path. In Cygwin, this was be a virtual unix style path mapped over the windows file system. The debugger will attempt to map that to a windows path using the cygpath utility included with Cygwin. 

You are correct that if the source has been copied to a different location, it will not find that path. We have it on the backlog to enable mapping to new paths but it isn't yet in the C++ extension. 

If the source code is still in the same location, then there may be a bug here. If so, can you please copy the full path that the debugger is looking for, /cygdrive/c/Users... and run it manually through the cygpath.exe utility available in the Cygwin console?

**Comment by mhobelsb** [comment]
hi,
thx, for the fast feedback. Yes, the source is stored in the same location as it was compiled from. 
I did run the full path throught the cygpath.exe:

the path printed in VSC (source not available) is: "\cygdrive\c\Users\marti\Dropbox\01_Privat\03_Projekte\99_Sandbox\01_HelloWorld\helloWorld.c." 
the original path (windows) is: "C:\Users\marti\Dropbox\01_Privat\03_Projekte\99_Sandbox\01_HelloWorld\helloWorld.c"
the path printed from the cygwin console (with cygpath -w -a \cygdrive\c\Users\marti\Dropbox..) is: 
C:\cygwin64\home\marti\cygdrivecUsersmartiDropbox01_Privat03_Projekte99_Sandbox01_HelloWorldhelloWorld.c

running cygpath in windows terminal (cmd) with cygpath -w -a: C:\cygdrive\c\Users\marti\Dropbox\01_Privat\03_Projekte\99_Sandbox\01_HelloWorld\helloWorld.c

**Comment by jacdavis** [comment]
Thanks. It is very interesting that the cygpath output when run from the Cygwin console is different from the windows console. I suspect the actual issue though is the output from a windows console (which is how it is run by the debugger):
C:\cygdrive\c\Users\marti\Dropbox\01_Privat\03_Projekte\99_Sandbox\01_HelloWorld\helloWorld.c

It looks like cygpath has a bug here. As you've pointed out, the correct path should be:
C:\Users\marti\Dropbox\01_Privat\03_Projekte\99_Sandbox\01_HelloWorld\helloWorld.c

I'll see if I can create a repro for this. In the meantime, if you move your project under under the virtual Cygwin file system (like your home folder) does everything work?

**Comment by mhobelsb** [comment]
I put the whole project in the home folder and unfortunatly it does not work.

**Comment by jacdavis** [comment]
I'm really sorry to hear that. Does cygath still return an incorrect windows path to the new source location?

**Comment by mhobelsb** [comment]
I copied the folder to "C:\cygwin64\home\marti\01_HelloWorld" ... Hope this was the right directory you meant with "virtual cygwin file system home folder". 
Debuggin there gives me: "Die Quelle \home\marti\01_HelloWorld\helloworld.c ist nicht verfügbar."

putting the path "\home\marti\01_HelloWorld\helloworld.c" in cygpath 

C:\Users\marti>cygpath.exe \home\marti\01_HelloWorld\helloworld.c
/cygdrive/c/home/marti/01_HelloWorld/helloworld.c

**Comment by delmyers** [comment]
@jacdavis do you have any more info to give to this user?

**Comment by jacdavis** [comment]
Unfortunately not.  Cygpath is still returning an incorrect path on this machine.

**Comment by pieandcakes** [comment]
@mhobelsb If this is still an issue, we enabled a `sourceFileMap` option that should allow you to map one to the other.

```
"sourceFileMap": {
        "\\cygdrive\\c\\Users\\marti\\Dropbox\\01_Privat\\03_Projekte\\99_Sandbox": "C:\\Users\\marti\\Dropbox\\01_Privat\\03_Projekte\\99_Sandbox"
}
```

Please comment/reopen if this is still an issue. Thanks
