### ISSUE TITLE
<error-type> and other erros occur with the Sparta project

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5702]
Same issue here.
![violentmonkey](https://user-images.githubusercontent.com/6806720/85643028-00d0fa80-b661-11ea-9cc2-b562b4177bc7.gif)

I'm still experiencing the issue. `error` is declared as `Error *&error;` and `all` is a method. I'm using vscode for remote WSL

Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.28.3
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

The repo is here https://github.com/luohancfd/sparta/tree/master/src
You can edit `collide_vss.cpp` and try it

_Originally posted by @luohancfd in https://github.com/microsoft/vscode-cpptools/issues/5228#issuecomment-649159396_

**Comment by sean-mcmanus** [comment]
The Error is being computed as `<error-type>` and I see some other errors. Looks like our parser is hitting some problem.

**Comment by bobbrow** [comment]
The repo link does not appear to work anymore.  If you have an updated link, we can keep this on our backlog for investigation.  Thanks.

**Comment by luohancfd** [comment]
> The repo link does not appear to work anymore. If you have an updated link, we can keep this on our backlog for investigation. Thanks.

Here is the updated repo link. https://github.com/sparta/sparta/tree/master/src

You can edit for example `src/collide_vss.cpp`. I can still reproduce the bug. I no longer contribute to the development of this repo though.

**Comment by bobbrow** [comment]
IntelliSense seems to work ok for this repo with the latest version of the extension.

![Image](https://github.com/user-attachments/assets/8f1c9d98-baca-492c-ae61-f15194a74469)
