### ISSUE TITLE
Malfunction to parse a variable with macro

### ISSUE THREAD

**Issue by Nathaniel7687** [microsoft/vscode-cpptools#5703]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Ver.1909
- VS Code Version: 1.46.1
- C/C++ Extension Version: v0.29.0-insiders
- Other extensions you installed (and if the issue persists after disabling them): C++ Intellisense
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc). **This is a problem that appears in all situations, such as workspace projects, folders, and single .c file.**

**Steps to reproduce**

1. Go to the File menu
2. Click on 'New File' for .c file
3. Type the below code
```
#include <stdio.h>

#define UINT8                       unsigned char
#define TEST_MACRO(ADDR)            (ADDR)

void TEST_FUNCTION(void addr)
{
    
}

UINT8 test;

int main()
{
    test;
    TEST_MACRO(test);
    TEST_FUNCTION(test);

    (UINT8)test;
    ((UINT8)test);
    TEST_MACRO((UINT8)test);
    TEST_MACRO(((UINT8)test));
    TEST_FUNCTION(((UINT8)test));
    
    (unsigned char)test;
    ((unsigned char)test);
    TEST_MACRO((unsigned char)test);
    TEST_MACRO(((unsigned char)test));
    TEST_FUNCTION(((unsigned char)test));

    return 0;
}
```
4. The abnormal symptom is below.
![image](https://user-images.githubusercontent.com/2202291/85819037-47337000-b7ad-11ea-9874-1616c456e10c.png)

**Expected behavior**
It needs to be able to parse everything correctly, regardless of the number of parentheses surrounding the variable passed as a macro function or function parameter.
But, the line number 22 shows something wrong. This symptom occurs when the defined variable type and macro function are used and a variable is wrapped more than once by the parentheses.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 6/26/2020, 12:55:59 PM
Version: 0.29.0-insiders
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\Program Files\\LLVM\\bin\\clang.exe",
    "cStandard": "c11",
    "cppStandard": "c++11",
    "compilerArgs": [],
    "intelliSenseMode": "gcc-arm",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\nathaniel.kim\Desktop\test.c ]:
    C:\USERS\NATHANIEL.KIM\DESKTOP\TEST.C
Translation Unit Configurations:
[ C:\Users\nathaniel.kim\Desktop\test.c ]:
    Process ID: 210856
    Memory Usage: 2 MB
    Compiler Path: C:\Program Files\LLVM\bin\clang.exe
    Includes:
        C:\PROGRAM FILES\LLVM\LIB\CLANG\10.0.0\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\VC\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\VC\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\8.1\INCLUDE\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\8.1\INCLUDE\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\8.1\INCLUDE\WINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c11
    IntelliSense Mode: gcc-arm
    Other Flags:
        --clang
        --clang_version=100000
Total Memory Usage: 2 MB
```
</details>

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug with VS at https://developercommunity.visualstudio.com/content/problem/1093308/cc-intellisense-has-a-problem-with-certain-macros.html .

**Comment by Nathaniel7687** [comment]
@sean-mcmanus, I appreciate your dedication to vscode-cpptools.

Is there any progress on this issue?

**Comment by sean-mcmanus** [comment]
No progress -- looks like the VS issue may need more upvotes. The team working on the parser is pretty busy adding new C++20 support and fixing issues related to that.

**Comment by Nathaniel7687** [comment]
@sean-mcmanus 
Hi, I already filed this issue to vscode team but an engineer said this problem is caused by cpptools.
Here is the link that I issue, https://github.com/microsoft/vscode/issues/105119.

**Comment by sean-mcmanus** [comment]
Yes, it's not a VS Code issue, it's a VS (Visual Studio 2019) issue, see https://developercommunity.visualstudio.com/content/problem/1093308/cc-intellisense-has-a-problem-with-certain-macros.html .
