### ISSUE TITLE
Changing C_Cpp.default.* doesn't work for the non-active workspace folders until a Reload Window occurs

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5707]
There might be a way to fix it via TypeScript only, but there is a potential fix that would require cpptools changes. I reproed it on Windows, but it wasn't reproing on Mac for some reason.

**Comment by bobbrow** [comment]
Closing this bug as lower priority since it's become stale and there are no comments from the community about it.
