### ISSUE TITLE
Code Parsing Stats

### ISSUE THREAD

**Issue by nickos556** [microsoft/vscode-cpptools#5708]
When dealing with a very large and complex C++ codebase, I frequently see 100% CPU usage for days on end. 
How can I generate statistics from this plugin to see where the time is going?
I am using the Linux version of this plugin, via RemoteSSH, and running the UI on windows. 

Thanks

**Comment by sean-mcmanus** [comment]
That is not normal. Which process is using the CPU? You can run "top" or some other similar process.

Next, what output is shown when you set the C_Cpp.loggingLevel to "Debug"?

One potential option is to attach a debugger to the cpptools process and get a call stack or to run a profiler that can get call stacks over time.

**Comment by nickos556** [comment]
Thanks for cominr back to me Sean.

1. The process is:
/home/<user>/.vscode-server/extensions/ms-code.cpptools-0.26.0/bin/Microsoft.VSCode.CPP.Extension.linux
I see two instances of this process, both spinning at 100% of CPU.
2. What output is shown after setting C_Cpp.loggingLevel to "Debug"? I am using a multi-root workspace, so I have lots of different outputs. None of them seem to be logging constantly, most say something to the effect of:
Intellisense Engine = Default
Autocomplete is enabled
Update Intellisense time (sec): 171.434

3. I gdb'ed one of the processes and Ctrl+C'ed a few times. It always seems to be at:
vscode::message_handler::documentSymbol_find_children

Nick

**Comment by bobbrow** [comment]
> /home//.vscode-server/extensions/ms-code.cpptools-0.26.0/bin/Microsoft.VSCode.CPP.Extension.linux

That is a relatively old version of the extension.  Are you able to update to the latest?
How many folders are open in your workspace?

> vscode::message_handler::documentSymbol_find_children

How deep is the stack?  There is a bailout for excessive recursion in that function, but if it is hitting frequently, we may want to get more information about the types in your project as it's possible there is a bug in the code that builds the hierarchy for the document outline.

**Comment by nickos556** [comment]
Hi guys, I updated to the most recent extension and the problem seemed to go away. However, I think that it would be very useful to have the parser generate stats so that problems can be identified.
Also, it seems that having a multi-root project causes the same external include directories to be parsed multiple times (i have 12 or so roots and most of the projects share similar includes).
Keep up the good work, and thanks for the pointers, 
Nick

**Comment by sean-mcmanus** [comment]
@nickos556 It shouldn't actually be parsing multiple times, just rescanning to see if anything needs to be reparsed. See https://github.com/microsoft/vscode-cpptools/issues/5156 . The reason is that the different folders could have different settings that cause different parsing behavior (the fix would be to check if those settings are the same to try to skip the extra processing).
