### ISSUE TITLE
no error is given when semicolon is missing in lambda function

### ISSUE THREAD

**Issue by rahgurung** [microsoft/vscode-cpptools#5711]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18
- VS Code Version: 1.44.1
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): No other extension related to C++ used
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

**Steps to reproduce**

1. Create a CPP file.
2. Write this code
    ``sort(arr.begin(), arr.end(),
         [](auto &a, auto &b) { return a.d < b.d });``
3. Observe if any warning comes.

**Expected behaviour**
Because there should be a semi-colon after `b.d`. It should give the warning to use a semicolon.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug on VS at https://developercommunity.visualstudio.com/content/problem/1095662/cc-intellisense-reports-no-errors-for-certain-func.html .

**Comment by bobbrow** [comment]
This appears to be fixed in the latest version of the extension.
