### ISSUE TITLE
Wrong Red Squiggles when using  vscode remote 

### ISSUE THREAD

**Issue by host452b** [microsoft/vscode-cpptools#5714]
![image](https://user-images.githubusercontent.com/32806348/86145361-6d4c6d80-bb29-11ea-83ee-b0a47063c608.png)

bug if you copy the same code for one line  , it fix for the copy one 

![image](https://user-images.githubusercontent.com/32806348/86145551-a08efc80-bb29-11ea-8baa-433e276fd3f6.png)

THAT'S REAL WEIRD / STRANGE！

**Comment by host452b** [comment]
![image](https://user-images.githubusercontent.com/32806348/86145650-c4524280-bb29-11ea-9fa5-ab629225b924.png)

here is my settings for c_cpp_properties.json

**Comment by sean-mcmanus** [comment]
We need more repro info. Do you have any sample repro code?
