### ISSUE TITLE
Different display color for defaulted construtor and operator

### ISSUE THREAD

**Issue by csorvagep** [microsoft/vscode-cpptools#5715]
**Type: LanguageService**

**Describe the bug**
- C/C++ Extension Version: 0.29.0-insiders
If one of the special constructor is defaulted or deleted it has a different color/stlye representation than a defaulted/deleted operator.
An example is shown in the image below. (It uses Material Theme Ocean High Contrast, but it is also true for the default Dark+ theme) 
![image](https://user-images.githubusercontent.com/2698569/86181072-a1c22880-bb2d-11ea-8320-8b8df00d4e9f.png)

**Expected behavior**
Although the default and delete keywords can have different meanings in a standard C++ code, in this case they should appear the same.

**Comment by sean-mcmanus** [comment]
This seems at least partially covered by https://github.com/jeff-hykin/cpp-textmate-grammar/issues/407 . The issue with default might be slightly different, since it's getting a scope of keyword.control.default.cpp (when it's not a control flow keyword).

**Comment by Colengms** [comment]
Closing external issue.

**Comment by sean-mcmanus** [comment]
@csorvagep This just got fixed with the latest update of the Better C++ Extension. The fix should be available in VS Code after they pull in an updated version.
