### ISSUE TITLE
using boost/multi_index error: sequenced is not a template 

### ISSUE THREAD

**Issue by georeith** [microsoft/vscode-cpptools#5720]
**Type: LanguageService**

**Describe the bug**

Incorrect error squiggle when trying to create a boost::multi_index_container with a sequenced index.

- OS and Version: Mac OS 10.15.5
- VS Code Version:  1.46.1 
- C/C++ Extension Version: 0.29.0-insiders
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
```c++
#include <boost/multi_index_container.hpp>
#include <boost/multi_index/sequenced_index.hpp>

using namespace boost::multi_index;

typedef multi_index_container<
    int,
    indexed_by<
        sequenced<>
    >>
    multi;
```

**Expected behavior**

Should not show an error squiggle

**Screenshots**

![image](https://user-images.githubusercontent.com/3090066/86414533-132fe180-bcbc-11ea-939f-f4d376d39a1d.png)

**Comment by sean-mcmanus** [comment]
I don't repro the issue with gcc 9 or clang 11 on Mac. Can you run C/C++: Log Diagnostics so I can tell what config settings are being used?

Also, what boost version are you using? I'm using boost 1.73 installed via vcpkg.

**Comment by georeith** [comment]
@sean-mcmanus my bad it was a difference in boost version in my compilation environment and my editing environment. (1.72 vs 1.56) Thanks for looking into this.
