### ISSUE TITLE
clang-format consumes memory until the system freezes (>3GB)

### ISSUE THREAD

**Issue by gatopeich** [microsoft/vscode-cpptools#5722]
**Type: LanguageService**

clang-format included in vscode-cpptools can hog all the memory in my system until it freezes.

The freezing part is a [long-standing Ubuntu issue](https://askubuntu.com/a/402940/81168) that can be avoided by setting `vm.oom_kill_allocating_task = 1`.

**Describe the bug**

- OS and Version: Linux Mint 19.3 / Ubuntu 18.04
- VS Code Version: 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d)
- C/C++ Extension Version: v0.29.0-insiders

**Steps to reproduce**
A single file can be used to reproduce the issue: the popular single-header JSON library: [nlohmann/json](https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp). While working on it, the issue is due to happen any minute or it can be triggered manually by `ctrl+shift+P` then "format document"
```
Insert logs here.
```
</details>

**Screenshots**
```top - 11:06:04 up 10 min,  1 user,  load average: 2.08, 2.22, 1.43
Tasks: 224 total,   2 running, 164 sleeping,   0 stopped,   0 zombie
%Cpu(s): 26.6 us,  0.7 sy,  0.0 ni, 69.8 id,  2.9 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  5966624 total,   121556 free,  5431564 used,   413504 buff/cache
KiB Swap:        0 total,        0 free,        0 used.    95916 avail Mem 

 PID USER PR NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
3962  me  20  0 3079700 2.922g   2684 R 100.0 51.3   1:03.98 /home/me/.vscode/extensions/ms-vscode.cpptools-0.29.0-insiders/bin/../LLVM/bin/clang-format -style={ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBrace+
3121  me  20  0 12.087g 376280  40144 S   0.3  6.3   0:48.81 /usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --field-trial-handle=16287341756966003520,11276319298504392950,131072 --disable-features=LayoutNG,Pictu+
3904  me  20  0 4598676 321880   2040 S   0.0  5.4   0:07.08 /home/me/.vscode/extensions/ms-vscode.cpptools-0.29.0-insiders/bin/cpptools-srv 3365 0
2505  me  20  0 3012492 229124  66476 S   0.3  3.8   0:50.25 /usr/lib/firefox/firefox
2800  me  20  0 32.822g 191752  36896 S   0.7  3.2   0:19.67 /usr/lib/firefox/firefox -contentproc -childID 4 -isForBrowser -prefsLen 6375 -prefMapSize 228249 -parentBuildID 20200602222727 -appdir /usr/lib/firefox/browser 2505 true tab
2905  me  20  0 2785408 155868  82552 S   0.0  2.6   0:25.06 /usr/lib/firefox/firefox -contentproc -childID 6 -isForBrowser -prefsLen 7292 -prefMapSize 228249 -parentBuildID 20200602222727 -appdir /usr/lib/firefox/browser 2505 true tab
```

**Expected behavior**

According to #1139 [the extension is supposed to close processes taking >1.5 GB](https://github.com/microsoft/vscode-cpptools/issues/1139#issuecomment-479189271).

<details>
  <summary><strong>Logs</strong></summary>

**Comment by sean-mcmanus** [comment]
It's a bug/issue with clang-format itself, i.e. repros via invoking clang-format on the command line, so it would need to be fixed/reported at https://bugs.llvm.org/. We have an alternative formatting implementation that doesn't involve clang-format pending for a future release (0.30.0?), which should be a workaround for this issue (except for users who really want clang-format style formatting).

**Comment by sean-mcmanus** [comment]
We close old IntelliSense processes when memory usage becomes too high, but we don't monitor clang-format for memory usage (maybe we could?).

**Comment by gatopeich** [comment]
> ... we don't monitor clang-format for memory usage (maybe we could?).

It should be done for the sake of robustness.
And perhaps with all extensions, not just cpptools.
Extension manager could have a setting: **"Max memory allowed per extension / subprocess"**

**Comment by bobbrow** [comment]
Closing this issue in favor of the new, more general issue #5750
