### ISSUE TITLE
cannot open source file "corecrt.h" (dependency of "iostream")

### ISSUE THREAD

**Issue by auadelaide** [microsoft/vscode-cpptools#5723]
> You fixed this problem by changing to gcc as the compiler...For someone choosing MSVC, I fixed the "cannot open source file "corecrt.h" (dependency of "iostream")" issue by changing the include path in _c_cpp_properties.json_
> 
> > "D:/Program Files/Microsoft/MSVC2017/VC/Tools/MSVC/14.12.25827/include/*",
> > "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10240.0/ucrt",
> > "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.10240.0/ucrt/x64",
> 
> I installed MSVC on D: drive, you may change that according.

The last line does the job. You can omit the rest lines safely.

_Originally posted by @hudsontek in https://github.com/microsoft/vscode-cpptools/issues/1237#issuecomment-508881471_

**Comment by auadelaide** [comment]
In my experience with this, I fixed it by adding:
**"C:/Program Files (x86)/Windows Kits/10/Include/10.0.10240.0/ucrt"**  this in the **"includePath":**
This path is enough to resolve this particular problem.

**Comment by bobbrow** [comment]
It is not recommended to set the system include path in the `includePath` property.
The recommended solution is to set the path to your compiler in the `compilerPath` property then set the Windows SDK version you want to target in the `windowsSdkVersion` property. Please let us know if that does not work for you.

**Comment by auadelaide** [comment]
No PROBLEMS encountered with your recommended fix. The program was successfully built.
Thank you very much for this correction. I appreciate this @bobbrow .

Is there anything I missed out? Thank you.
Attached is  the updated c_cpp_properties.json

![c_cpp](https://user-images.githubusercontent.com/67774560/86858943-3b707380-c0f4-11ea-97d8-233aaafcc5ef.JPG)

**Comment by sean-mcmanus** [comment]
Your setting for "browse": { "path": [] }} is not recommended. It should probably be the default (i.e. removed from c_cpp_properties.json). Was there a reason you changed it? In particular, "${workspaceFolder}" or some sub-folder of that should probably be in your browse.path setting, and including the Windows Kit directory in your browse.path shouldn't be necessary (it should be added by default as well).

**Comment by auadelaide** [comment]
> Your setting for "browse": { "path": [] }} is not recommended. It should probably be the default (i.e. removed from c_cpp_properties.json). Was there a reason you changed it? In particular, "${workspaceFolder}" or some sub-folder of that should probably be in your browse.path setting, and including the Windows Kit directory in your browse.path shouldn't be necessary (it should be added by default as well).

Thank you @sean-mcmanus for pointing this out.  
The following are the changes I made in the generated .json file:
1.  **"windowsSdkVersion": "10.0.10240.0"** from "windowsSdkVersion": "8.1"
2.  **"compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe"** from "compilerPath":  "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe"
3. Added **"browse": {"path": [ "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10240.0/ucrt" ] }**

These changes fixed the aforementioned problem. May I ask the possible complications I will encounter with these setup in the future? Thank you.

**Comment by sean-mcmanus** [comment]
Yes, changes 1 and 2 are okay, but your browse.path is insufficient, so operations that require global symbols lookups like Go to Definition and Find All References could fail to find results. The browse.path should be automatically set with `C:/Program Files (x86)/Windows Kits/10/Include/10.0.10240.0/ucrt` without excluding the ${workspaceFolder} default.

**Comment by auadelaide** [comment]
I am new to this VS Code. Thank you @sean-mcmanus for the assistance.
This is my new .json. No problems encountered. 

![c_cpp](https://user-images.githubusercontent.com/67774560/86987035-a8a10900-c1c7-11ea-839e-fbeaf5783499.JPG)
