### ISSUE TITLE
Toggle header/source file

### ISSUE THREAD

**Issue by zrno** [microsoft/vscode-cpptools#5732]
Issue Type: <b>Feature Request</b>

Currently an extension needs to be used to toggle between header and source files written in C, C++ and Objective-C.

https://marketplace.visualstudio.com/items?itemName=bbenoist.togglehs

Could this feature be implemented as part of cpp extension?

One the issues with the mentioned extension is that it doesn't work when using VS Codes Live Share extension.

Extension version: 0.28.3
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

**Comment by oo8dev** [comment]
Have you tried `Alt + O`?

**Comment by zrno** [comment]
Actually no. I only see the shortcut now. So it works it seems. Was this added in the last year or two?

**Comment by bobbrow** [comment]
Glad to hear you are unblocked.  We've had that feature since the beginning but it has improved over the years.
