### ISSUE TITLE
cpptools does not startup on ssh-remote

### ISSUE THREAD

**Issue by aprilweet** [microsoft/vscode-cpptools#5734]
Issue Type: <b>Bug</b>

Usually i connect to a centos machine by remote-ssh, both with Macbook and Windows PC.

Everything is ok on Macbook, but when i change working on PC, cpptools does not work. Sometimes it will be ok after cpptools reinstalled, but sometimes it still cannot work.

i find output like this:
```bash
 [exthost] [info] ExtensionService#_doActivateExtension codecc.cpplint {"startup":false,"extensionId":{"value":"codecc.cpplint","_lower":"codecc.cpplint"},"activationEvent":"onLanguage:cpp"}
```
it seems that cpptools is not activated, but my workspace and source file is surely cpp.

Extension version: 0.28.3
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.107-1-xxxxx

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: xxxxx |
|OS|Linux x64 3.10.107-1-xxxxxxx |
|CPUs|Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz (16 x 2494)|
|Memory (System)|62.67GB (19.98GB free)|
|VM|0%|
</details>

**Comment by aprilweet** [comment]
When cpptools works, i can see outline on left side bar, and click to symbol.

**Comment by Colengms** [comment]
Hi @aprilweet .  The output you provided refers to an extension with the ID "cpplint".  That would seem to be another extension that attempts to register to provide the same language services as the cpptools extension.  Depending on which attempts to register first, you may see different behavior.  Could you try disabling extensions other than cpptools and see if there is still an issue?  If not, it would seem to be a conflict with another extension.
