### ISSUE TITLE
Allow to use current tab/space indentation setting in Clang_format_fallback style

### ISSUE THREAD

**Issue by JeanMiK** [microsoft/vscode-cpptools#5736]
When using Clang_format_fallback Style "Visual Studio", the extension respects what is selected in the "Select indentation" part of the status line, using either spaces or tabs as indentation method, with the selected size for every indentation level, and the possibility of auto-detecting the best setting for the existing file.

This does not seem to work if one wants a different formatting based on existing templates, e.g.
  {BasedOnStyle: "LLVM",  PointerAlignment: Left, BreakBeforeBraces: Allman, AlignOperands: true, ColumnLimit: 0 }

Here, the formatting is done with the explicit values that are either given in the style option with UseTab /TabWidth , or set in the 'BasedOnStyle', so that changing the desired value requires modifying Clang_format_fallback Style .

When working with files created over time by many developers with many different styles, it would be nice to have the possibility to keep the auto-detection features or quick status bar selections possible with style "Visual Studio" even if one wants a special additional option to be specified in   Clang_format_fallback Style  (e.g. PointerAlignment: Left).

One possibility to introduce this without breaking existing configurations would be to foresee special values for UseTab /TabWidth that the C++ extension would replace by the current VusialStudio status bar settings before sending the code to be formatted to clang, e.g. a value 'VisualStudioCurrent':

  {BasedOnStyle: "LLVM",  UseTab: VisualStudioCurrent, TabWidth: VisualStudioCurrent, PointerAlignment: Left, BreakBeforeBraces: Allman, AlignOperands: true, ColumnLimit: 0 }

Maybe something like this is already possible, but I did not find out how.

**Comment by sean-mcmanus** [comment]
The VisualStudio style currently dynamically changes Standard, UseTab, IndentWidth, TabWidth, and AccessModifierOffset. It seems like we could just add these dynamic values as defaults to existing clang_format[_fallback]_style settings that don't have them already set...that would cause a change in behavior for users that were relying on the current default behavior, but the workaround for those users would be to just explicitly add the defaults they want to overwrote. I'd prefer to avoid adding a new "VisualStudioCurrent" value.

**Comment by bobbrow** [comment]
I agree with @sean-mcmanus.  I don't think we want to add our own custom settings logic over clang-format's spec.

Do your UseTab and TabWidth settings change frequently enough that you'd need a variable for this as opposed to just putting the value you want in there?

**Comment by JeanMiK** [comment]
For me, the proposal by @sean-mcmanus looks good, to just add the dynamic values to all other configurations as long as they have not have an explicit value set. 
I thought of this myself, but did not propose it as a possible solution as it is breaking existing behavior. Not in a very serious way, as just changing the config once to put the desired explicit values gives back the original behavior (alternatively, he can just enter the desired values in the status bar), but it still requires an action by the user. If you are accepting this little inconvenience for existing users than I agree that this is a nicer, cleaner solution.
And yes, unfortunately, the formatting of the existing code I am working with changes from file to file, sometimes even within a single file (one method indented with tabs, the other one indented with spaces). This is why being able to have the system detect the convention used by the current file is infinitely better than having to change the  Clang_format_fallback Style setting every time. I mean, this is why the setting exists in the status bar to begin with.

**Comment by bobbrow** [comment]
It turns out that the solution described above sounds a lot like feature request #1110.  This could be a duplicate.

**Comment by JeanMiK** [comment]
Yes, it is basically the same idea. Only difference I can see so far is that by the proposal by @sean-mcmanus, the system would always add Standard, UseTab, IndentWidth, TabWidth, and AccessModifierOffset with the dynamic values from VisualStudio unless the user provided an explicit value in the  Clang_format_fallback Style setting, while  #1110 was talking of an additional setting to tell the system to do this.

Also, #1110 mentions only TabWidth but none of the other related settings  mentioned above. So if you decide to keep  #1110 instead of this one, make sure to copy the relevant info over there.

**Comment by bobbrow** [comment]
If we do this work, we'd want to add a new setting to enable it.  We don't want to add new meaning to clang-format's actual spec. 

This wouldn't be the name, but something like `clang_format_style_override`: `useVSCodeSpacing`
