### ISSUE TITLE
Register logging handler from cpptools as early as possible on Typescript.

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#5739]

**Comment by Colengms** [comment]
@bobbrow I think we are already doing so.  We miss some early log output from the native side during initialization.  But, notifications must be registered after initialization, or will fail to register.

**Comment by bobbrow** [comment]
@Colengms I just created this task from the note that was on the 0.29.0 project board. If this is complete, please feel free to close it.

**Comment by Colengms** [comment]
Unless someone has additional information, I believe this is already happening as early as possible.
