### ISSUE TITLE
header file not found

### ISSUE THREAD

**Issue by fengxinming** [microsoft/vscode-cpptools#5744]
vscode always shows a wavy red underline that means 'emscripten.h' file not found, and I have included paths what it needs.

vscode version 1.46

c_cpp_properties.json

```json
{
    "env": {
        "myDefaultIncludePath": [
            "/Users/jesse/workspace/github/emsdk/upstream/emscripten/system/include/**",
            "${workspaceFolder}/**"
        ]
    },
    "configurations": [
        {
            "name": "Mac",
            "browse": {
                "path": [
                    "${myDefaultIncludePath}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "includePath": [
                "${myDefaultIncludePath}"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

```c
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <emscripten.h>

int main(int argc, char **argv)
{
  // ...
}

```

**Comment by sean-mcmanus** [comment]
Your settings seem like they should work. Can you run the C/C++: Log Diagnostics command (from the VS Code Command Palette) and check if the Includes it shows includes the path where emscripten.h exists?

What version of the C/C++ extension are you using? We had a bug with env variables with 0.28.1 -- see https://github.com/microsoft/vscode-cpptools/issues/5509 .

**Comment by fengxinming** [comment]
@sean-mcmanus 

C/C++ v0.29.0-insiders2
C/C++ Clang Command Adapter v0.2.3
C++ Intellisense v0.2.2

**Comment by sean-mcmanus** [comment]
What is the exact text of the error? It may be coming from the other 2 extensions. You should disable the other 2 extension (at least temporarily) to make sure those errors aren't from those extensions which provide similar functionality.

**Comment by fengxinming** [comment]
@sean-mcmanus vscode always shows a wavy red underline that means 'emscripten.h' file not found, but the c file can be compiled, I have found this reason that is about plugin "C/C++ Clang Command Adapter", so may I ask you what plugins are required for developing C or C++

**Comment by sean-mcmanus** [comment]
Our extension is the C/C++ extension, so that's what we recommend you use. The C/C++ Clang Command Adapter and C++ IntelliSense are not published by Microsoft and I'm not familiar with them, other than we occasionally get bug reports like this from users who have those other extensions installed.

**Comment by fengxinming** [comment]
@sean-mcmanus so you mean "C/C++ extension" is enough to develop C/C++, and it includes "snippets" and "go to definitions"

**Comment by sean-mcmanus** [comment]
Yes, we include snippets and go to definition support.
