### ISSUE TITLE
No Syntax Checker in cpp files

### ISSUE THREAD

**Issue by dustookk** [microsoft/vscode-cpptools#575]
![](http://i.imgur.com/xh1QJkq.jpg)

<br/><br/><br/>

# there is a extra ")" in the code , but the editor is not showing the error.

<br/><br/><br/>

**Comment by dustookk** [comment]
this function is working fine in java files

![](http://i.imgur.com/z4nxkwE.jpg)

**Comment by sean-mcmanus** [comment]
The C++ extension doesn't implement syntax checking during editing yet.

**Comment by dustookk** [comment]
@sean-mcmanus Thanks man, do you guys have any plans for this feature?

**Comment by bobbrow** [comment]
Yes, we plan to enable this.

**Comment by sean-mcmanus** [comment]
You could keep this issue open until the feature is added if you want.

**Comment by andyleejordan** [comment]
@dustookk I would love this to be kept open. I anxiously await on-the-fly syntax checking, it's easily the biggest missing component when compared to Emacs / Vim / Visual Studio.

**Comment by dustookk** [comment]
@andschwa You got it man LOL

**Comment by bobbrow** [comment]
v0.11.0 supports continuous syntax checking.  It is not on by default yet, but you can enable it by adding the `C_Cpp.intelliSenseEngine: "Default"` property to your settings.json file.  Try it out and let us know what you think!

If you have any issues with it or suggestions on how to make it better, please create a new issue so we can track it.  There are a few bugs with multi-byte characters and editing on the last line of the file that we know about, so you can expect fixes for those later, but we have tried it out on a number of projects large and small and are getting good enough results to feel comfortable publishing a preview of it for those willing to try it out.

**Comment by themightyoarfish** [comment]
Setting this property does not cause VSCode to notice any syntax errors. What else could the problem be?

**Comment by sean-mcmanus** [comment]
@themightyoarfish What does your Problems window show? It could be falling back to the Tag Parser.

**Comment by themightyoarfish** [comment]
@sean-mcmanus It does say something like that completions will be provided by the tag parser (don't remember the exact message right now).

**Comment by EECSGEEK** [comment]
@bobbrow  I need Live syntax checker when I editing C/C++ files,
I had install many extensions, but no one has syntax check on C/C++
> Yes, we plan to enable this.

**Comment by bobbrow** [comment]
@EECSGEEK, we have had live syntax checking for some time now.  Make sure `C_Cpp.intelliSenseEngine: "Default"` is set in your settings.  Also make sure that there are no green squiggles under your #include lines.  If we can't resolve a #include line, we will hide the red squiggles by default.

**Comment by EECSGEEK** [comment]
@bobbrow My settings is ok, but still no Live syntax check
 <img src="http://p1.cdn.img9.top/ipfs/QmNw5iUN2MC6YL8pSp3RTinNy6TKNYvoCm2SrY7iYfuSgS?1.PNG"></img>

**Comment by sean-mcmanus** [comment]
@EECSGEEK It would be better if you filed a new issue. This issue was for the original feature, which in general works for most people. I assume C_Cpp.errorSquiggles is set to Enabled. Do you see messages in your Problems window? Are you using VS Code Insiders? Can you set your C_Cpp.loggingLevel to Information and see if the C/C++ Output pane shows any useful diagnostic information?

**Comment by aditya-ramabadran** [comment]
Are there warnings for the C++ files?
For example, in Eclipse, the below code (setting a variable inside an if statement) would trigger a warning:
![image](https://user-images.githubusercontent.com/19241683/40878699-8657d602-6649-11e8-87fa-d6f2d85a087f.png)
However, in VS Code it does not.

I'm sure that syntax checking is working, because it _does_ detect this:
![image](https://user-images.githubusercontent.com/19241683/40878707-b0b8ef44-6649-11e8-877b-2ef414262c4a.png)

Are there any plans to add the warnings, or is there a way to enable them right now?

Thanks!

**Comment by sean-mcmanus** [comment]
@aditya-ramabadran We have warnings available as a hidden feature via removing the line with "--no_warnings" from the extension's `bin\msvc.json` file, but assignments in "if" statements currently do not generate a warning. If you're using the cl.exe compiler, you can use the build flag /Wall to get a warning at build time: "warning C4706: assignment within conditional expression". gcc/clang might also have such a warning level.

**Comment by X-Wei** [comment]
> @aditya-ramabadran We have warnings available as a hidden feature via removing the line with "--no_warnings" from the extension's `bin\msvc.json` file, but assignments in "if" statements currently do not generate a warning. If you're using the cl.exe compiler, you can use the build flag /Wall to get a warning at build time: "warning C4706: assignment within conditional expression". gcc/clang might also have such a warning level.

Will it be possible in the future to be able to config this "--no_warning" flag in the C_cpp_extension's configuration ?

**Comment by sean-mcmanus** [comment]
@X-Wei Yeah, we have warning enabling almost done (we just wanted to add a setting to enable particular warnings to be disabled before we turn it on), and that work has been post-poned (see https://github.com/Microsoft/vscode-cpptools/milestone/26 ) in favor of shipping IntelliSense-based Go to Definition sooner.
