### ISSUE TITLE
Add max memory per process setting (to avoid excessive memory usage)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5750]
> ... we don't monitor clang-format for memory usage (maybe we could?).

It should be done for the sake of robustness.
And perhaps with all extensions, not just cpptools.
Extension manager could have a setting: **"Max memory allowed per extension / subprocess"**

_Originally posted by @gatopeich in https://github.com/microsoft/vscode-cpptools/issues/5722#issuecomment-655035661_

**Comment by Colengms** [comment]
The setting `Cpp.intelliSenseMemoryLimit` was adding in 1.1.0, which addresses this for the `cpptools-srv` process.  I suspect that is what most of the upvotes here are for.

For the IntelliSense process, we have a viable recourse, to reset the translation unit.  For other (usually briefly run) processes such as clang-format that are implemented independently of our extension, our only recourse would seem to be to kill them.  Killing processes we didn't implement could have consequences, such as files being incompletely written to.  So, I don't think this is something we should implement.  Rather, issues with clang-format memory usage should probably be pursued as bugs in clang-format.

**Comment by sean-mcmanus** [comment]
So we can close this?
