### ISSUE TITLE
It takes too many clicks of "Load More Frames" to get the full call stack when there are lots of stack frames.

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5752]
I was a debugging a crash with 175+ stack frames and I had to keep hitting the "Load More Frames" over and over (it only loaded a small number of frames like 20). I think the "Load More Frames" should be replaced by "Load All Frames"...I don't know a good use case where you would not want that. I've never had this problem when using the Visual Studio debugger. This might be a VS Code issue?

It hit another case a few days ago with a possible stack over flow and I gave up trying to obtain stack frames because there were so many I had to manually load.

**Comment by WardenGnaw** [comment]
This is in [VSCode](https://github.com/microsoft/vscode/blob/13885429b79dc02db69c7f30dfb597db190e1b2e/src/vs/workbench/contrib/debug/browser/callStackView.ts#L715), we supply them with the full call stack when the process is stopped.

**Comment by sean-mcmanus** [comment]
I filed an issue at https://github.com/microsoft/vscode/issues/102048 .
