### ISSUE TITLE
Find All References does not search in other folders for multiroot

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5753]
This seems to only repro on Mac

**Repro steps:**
1. Have two project folders in different locations (such as /project_a/folder_1 and /project_b/folder_2).
2. Open /project_a/folder_1
3. Add /project_b/folder_2 to workspace
4. Open a file in folder_1 and do a Find All References on a symbol that can also be found in folder_2
5. Result: Find all references only returns results from folder_1.

**Note:**
If you open a source file in folder_2 and do another Find all references from a file in folder_1, then results will include symbols from folder_2.

**Comment by heartacker** [comment]
@sean-mcmanus  that will be great if cpp-tools can cache  all `find_all_references` results. Strong pleas to add caching functionality.3q

**Comment by sean-mcmanus** [comment]
@heartacker Caching does exist if the files with references are left open and your core count and memory is high enough to keep all the cpptools-srv processes in memory (requiring less parsing), i.e. it's a manual driven caching versus the automatic caching done by VS. However, that caching will only speed up "files confirmed" speed and not the "files searched" speed.

**Comment by michelleangela** [comment]
Can no longer reproduce issue (see screenshot of result from repro steps). Closing as resolved.

Did a find all references on a symbol from a file in **folder_1**, and results also included symbols from file in **folder_2**.
![image](https://user-images.githubusercontent.com/38734287/98030990-b279f800-1dc6-11eb-88a0-2036ac9e0b49.png)
