### ISSUE TITLE
Bad keyword highlighting

### ISSUE THREAD

**Issue by SuperiorArri** [microsoft/vscode-cpptools#5754]
When I type
`inline const ...`
in class prototype, 'inline' is not highlighted.

**Comment by sean-mcmanus** [comment]
Could you provide a more complete example and screenshot? I'm not seeing the issue. What theme are you using?

![image](https://user-images.githubusercontent.com/19859882/87070256-5e228b00-c1cd-11ea-828b-c726d432a89f.png)

**Comment by SuperiorArri** [comment]
Interesting...

Here is a screenshot:
![image](https://user-images.githubusercontent.com/17547286/87080084-60193800-c227-11ea-803e-1b148cd295cf.png)

I am on Ubuntu 19.10 and using VS Code version 1.46.1. Theme: Light+ (default light)

**Comment by sean-mcmanus** [comment]
Are you able to provide an isolated code repro?

Does the issue repro with the C/C++ extension disabled? If not, does it repro with C_Cpp.enhancedColorization set to "Disabled".

**Comment by SuperiorArri** [comment]
Oh, it seems not to be issue of this extension. It still doesn't highlight properly even after disabling the extension. I am sorry for that.

**Comment by sean-mcmanus** [comment]
@Aerrios The lexical C/C++ colorization in VS Code is implemented by https://github.com/jeff-hykin/cpp-textmate-grammar/issues, so you'll likely want to file a bug there. If you install the Better C++ Syntax extension, that will get you a later version (which may have fixes for issues). Our extensions adds some semantic colorization on top of that.

**Comment by SuperiorArri** [comment]
Installing the Better C++ Syntax extension fixed the issue. Thank you very much.
