### ISSUE TITLE
Security Vulnerability? Does IntelliSense download any file from remote to host when using remote SSH? 

### ISSUE THREAD

**Issue by PandaTinker** [microsoft/vscode-cpptools#5756]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Remote Linux RHEL 7.7, Host Latest MacOS
- VS Code Version: Latest
- C/C++ Extension Version: v0.28.3
- Other extensions you installed (and if the issue persists after disabling them):
Remote development (0.20.0)
Python
Pylance
- Does this issue involve using SSH remote to run the extension on a remote machine?:
Yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

My manager contacted me showing that there is a security leakage from dev server to my laptop. But the only thing I have done today is configuring the CPP IntelliSense so that all headers can be found. So I suspect the intellisense automatically leaked files.
**Steps to reproduce**

1. Prepare a very large C repo (~80G) 
2. Added the root of repo to the "C_Cpp.default.includePath"

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
When remoting, our C/C++ extension binaries (cpptools and cpptools-srv) run on the remote side and has no connection to the host side, with all communication being done via JSON messages to VS Code processes on the remote side (see https://code.visualstudio.com/docs/remote/ssh ). Our TypeScript code at https://github.com/microsoft/vscode-cpptools/tree/release also runs on the remote side. So I'm not aware of any downloading of files that could occur from the remote to host. Let us know if you can find more info, but I'd guess the issue would have to be with VS Code's remoting itself (https://github.com/Microsoft/vscode-remote-release/issues), or more likely, the security leakage is from something else.
