### ISSUE TITLE
Feature request -- More functional minimap & highlighting

### ISSUE THREAD

**Issue by zhouzq-thu** [microsoft/vscode-cpptools#5757]
Xcode's minimap:
<img width="400" alt="Screen Shot 2020-07-10 at 4 51 35 PM" src="https://user-images.githubusercontent.com/9458157/87136581-467efb80-c2ce-11ea-8a1b-6b95387c7adb.png">

Xcode's Highlighting:
<img width="590" alt="Screen Shot 2020-07-10 at 4 51 54 PM" src="https://user-images.githubusercontent.com/9458157/87136620-55fe4480-c2ce-11ea-8035-f080d42d2640.png">
In Xcode, different colors are used to distinguish between class member variables/functions (colored by green) and external member variables/functions (colored by purple). However, local variables/functions are colored by black. Therefore, the variables/functions are very easy to be distinguished based on their colors.

**Comment by sean-mcmanus** [comment]
The minimap issue would probably need to be handled by VS Code itself: https://github.com/microsoft/vscode/issues

The colorization is determined by the themes. You can overwrite the theme colors, by changing your settings to something like

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "variable.other.property.cpp",
                "settings": {
                    "foreground": "#91B5BA"
                }
            },
            {
                "scope": "variable.parameter.cpp",
                "settings": {
                    "foreground": "#000000"
                }
            },
            {
                "scope": "meta.body.function.definition.cpp",
                "settings": {
                    "foreground": "#7F50B8"
                }
            },
            {
                "scope": "variable.other.property",
                "settings": {
                    "foreground": "#91B5BA"
                }
            },
            {
                "scope": "variable.parameter",
                "settings": {
                    "foreground": "#000000"
                }
            },
            {
                "scope": "variable.other.readwrite",
                "settings": {
                    "foreground": "#7F50B8"
                }
            }
        ]
    }
```
![image](https://user-images.githubusercontent.com/19859882/87183339-d1460300-c29a-11ea-9297-9f9f2bd687c5.png)

You can use the command Developer: Inspect Editor Tokens and Scopes to see scope info. Also, see https://code.visualstudio.com/docs/cpp/colorization-cpp .

**Comment by zhouzq-thu** [comment]
In fact, I didn’t mean the color values. I mean the highlighting system. Xcode does better to analyze the C/C++ code structures and variables. Therefore, Xcode’s highlighting looks better.

**Comment by sean-mcmanus** [comment]
I don't understand. What do you mean by "highlighting" versus colorization? The C/C++ code gets assigned scopes and the themes/settings match the scopes to colors. Are you saying there's a problem with the scopes? VS Code itself implements the lexical scopes and our extension adds semantic scopes/colors when C_Cpp.enhancedColorization is set to "Enabled" -- for the remote scenario, you'll need 0.29.0-insiders2 and possibly VS Code 1.47.0.

**Comment by zhouzq-thu** [comment]
Yes, I mean the scopes. I will try 0.29.0-insiders2. Thank you very much.
