### ISSUE TITLE
[Feature Request] launch.json: pidfile path as an alternative to processId

### ISSUE THREAD

**Issue by eduardolippmann** [microsoft/vscode-cpptools#5758]
Type: Debugger

Hi!
I work on a Windows local machine developing UI on remote linux machine. I have to start the process in a vnc session and then remote-attach using the pid.
If I could specify a path to a pidfile I wouldn't need to change the launch.json anymore.
The command:pickProcess is nice but there are tons of process in the list and many are homonymous.

**Comment by WardenGnaw** [comment]
You can utilize VS Code's [`Input Variable`](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables) feature in your `launch.json`.

For example:
```
"tasks": [
    {
      "pid": "${input:pidFile}"
      // ...
    }
  ],
"inputs": [
    {
      "id": "pidFile",
      "type": "command"
      "command": "type",
      "args": [
         "%userprofile%\pidfile.txt"
      ]
    }
```

**Comment by eduardolippmann** [comment]
Thank you for your reply. I see that Input Variables can be a solution for this problem but I would need a command to read a file or a line from a file. Is there such command? I did not find it.
It would definitely solve the problem of getting the pid. The launch.json would be something like:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/path/to/my/program",
            "processId": "${input:pidFile}",
            "MIMode": "gdb"
        }       
    ],
    "inputs": [
        {
            "id": "pidFile",
            "type": "command",
            "command": "<fileReadingCommand>",
            "args": ["path/to/pid.pid"]
        }
    ]
}
```

**Comment by kgyrtkirk** [comment]
I came across this thread; while I was looking for kinda the same thing...you could do it with the extension: `rioj7.command-variable`
```
    "inputs": [
        {
            "id": "pidFile0",
            "type": "command",
            "command": "extension.commandvariable.file.content",
            "args": {
                "fileName": "/tmp/_pgsql_debug_pid"
            }
        },
  ],
```
or with `augustocdias.tasks-shell-input`

```
    "inputs": [
        {
            "id": "pidFile",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "useFirstResult": "true",
                "command": "cat /tmp/_pgsql_debug_pid"
            }
        },
        {
            "id": "pidWait",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "useFirstResult": "true",
                "command": "nc localhost 5555"
            }
        }
    ]
```
