### ISSUE TITLE
Feature Request: Stack for goto definition to allow return from it

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode-cpptools#576]
Moved from https://github.com/Microsoft/vscode/issues/22739
Steps to Reproduce:

1. Press F12 to goto to a (for example) a function.
2. Do some editing or just move around.
3. Now need to return where the function was called. No way of doing this.
In SlickEdit there is Ctrl+. to goto a definition and Ctrl+, to return from that.

Go back can be used, but this is slow as it follows all cursor movements. By just having the goto function stack it would be much quicker to navigate through code.
Possibly related to https://github.com/Microsoft/vscode-cpptools/issues/15

**Comment by bobbrow** [comment]
Commented on the VSCode issue.  This is a feature that the editor should provide.
