### ISSUE TITLE
Global variable color and other scopes not changing

### ISSUE THREAD

**Issue by gvcallen** [microsoft/vscode-cpptools#5762]
**Type: LanguageService**
I have followed the instructions at https://code.visualstudio.com/docs/cpp/colorization-cpp in attempt to change the color of my global variables, but am unable to get it working. Not sure if it is a bug or if I am doing something wrong, as the instructions are slightly unclear.

**Describe the bug**
- OS and Version: Windows 10 (Windows_NT x64 10.0.18362)
- VS Code Version: 1.46.1
- C/C++ Extension Version: 0.29.0-insiders2

**Steps to reproduce**

1. Create a settings.json and add the following code:
{
    "C_Cpp.enhancedColorization": "Enabled",
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "variable.other.global",
                "settings": {
                    "foreground": "#FF0000",
                    "fontStyle": "italic bold underline"
                }
            }
        ]
    }
}
2. Switch to the Default Dark+ Theme (although I believe this has no effect)
3. Create a main.cpp file, a main function and a global variable. Access it in the main function
4. Note that neither the instantiation of the variable or the accessing of it have a different color other than the default blue

**Expected behavior**
- The variable should be colored

**Additional information**
If I change the "scope" value to simply "variable" it correctly changes the color of all of my variables

**Comment by JON95Git** [comment]
I'm also having this bug.
My system is Ubuntu 16.04 LTS.
Did you resolve this?

**Comment by gvcallen** [comment]
Not yet. For me, it is crucial to be able to change the colors of individual variables etc. It changes things such as how I name my variables, coding efficiency etc. Would love a resolution to this

**Comment by JON95Git** [comment]
Well, I tried many things. For me, just changing theme resolved this. I used to code using "Dracula Dark Vibrant" theme. When I changed to another theme, my variable color setting was applied.

**Comment by Colengms** [comment]
Hi @gvcallen , @JON95Git .  Thanks for reporting this.  We recently switched to VS Code's Semantic Tokens API for our semantic colorization.  While we should be able to maintain backwards compatibility with our old token scopes, some of those mappings were missing.  This should be fixed in the next release (or when 0.29.0 is released).

**Comment by sean-mcmanus** [comment]
Fixed with 0.29.0.
