### ISSUE TITLE
I was facing issues in getting squiggles when I copied bigger code. Normally it worked fine. I am not sure what went wrong

### ISSUE THREAD

**Issue by LezendarySandwich** [microsoft/vscode-cpptools#5766]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by michelleangela** [comment]
@LezendarySandwich 
Could you provide more information about the issue by filling out the "bug template" questions and adding [logs from the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server))?
