### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by IGHMC-Reg** [microsoft/vscode-cpptools#5768]
CPP Tools showing as unresponsive and VSC very slow editing a medium (ish) project
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `0.28.3`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.47.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 29,
		"activateCallTime": 8,
		"activateResolvedTime": 260,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-vscode.cpptools",
				"_lower": "ms-vscode.cpptools"
			},
			"activationEvent": "onLanguage:cpp"
		}
	},
	"runtimeErrors": []
}
```

**Comment by michelleangela** [comment]
@IGHMC-Reg 
Could you provide information about the issue? About how many files is a medium project? 

Could you also collect [logs from the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)) while reproducing the issue?

**Comment by IGHMC-Reg** [comment]
Hi Michelle

Thank you for following up, I'm refactoring 'Marlin' which is available on GitHub if you are looking for more details but the folder properties shows 6,6561 files, 462 folders for a total of 249MB.

However I'm only working with a tiny subset: its on an Atmega variant of Arduino and I have about half a dozen files open at a time, its against one of the relatively larger files that I've observed the slowdown. The issue seems to arise over time and usually after I've pasted a few hundred lines of code to be refactored. It slows at first then returns to normal for a while but after a few hours  the response in that window slows until its unusable and I have to restart the IDE. It seems as though the intellisense scanning goes into overdrive and 'forgets' its already scanned the code, it repeatedly updates the 'problems' output window, blanking it completely then re-displaying the same errors (which are known and part of the refactor).

Note that I'm using PlatformIO and I tend to scroll rapidly up and down the window (with a Logitech mouse), when that scrolling gets choppy I know that the IDE needs to be rebooted. A separate VSC window and a copy of VS2019 still work normally if I switch away to them.

Log file is attached, let me know if you need a more details.

Regards
Greg

________________________________

**Comment by IGHMC-Reg** [comment]
Hi again Michelle

I realised the first file I sent wasn't at debug level, here's two examples, one whilst the problem is being observed and one after vscode is freshly opened and the workspace is loading

Regards
Greg

________________________________

**Comment by sean-mcmanus** [comment]
Are you still reproing this issue with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 ? I'm not sure I understand what the issue is. Is this an issue with slow activation? Your logs show tag parsing is occurring. Nothing unusual. Does performance get better after the tag parsing is finished?
