### ISSUE TITLE
cannot debug my arm linux remotely.

### ISSUE THREAD

**Issue by justin-romano** [microsoft/vscode-cpptools#577]
I get the error 
`error while processing request 'attach' (exception: Cannot perform runtime binding on a null reference)`
![image](https://cloud.githubusercontent.com/assets/1707226/24068638/c0df7890-0bf8-11e7-9a84-61a1390eba2d.png)

![image](https://cloud.githubusercontent.com/assets/1707226/24068629/96b22874-0bf8-11e7-9e38-7a4de199724a.png)

```
        {
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "miDebuggerServerAddress": "192.168.20.51:4444",
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb"
            }
        },
```
Im running gdbserver on jessie armbian
Is there a way to do this?

**Comment by pieandcakes** [comment]
@justin-romano You are using the wrong type. You need to specify the `"type": "launch"` to do remote gdbserver debugging.

**Comment by justin-romano** [comment]
Thanks. So after reading a bunch (yeah i know RTFM)
I have got as far as pointing the miDebuggerPath at the arm toolset debugger but im still having issues.
Here is my launch.json
```json
{
            "name": "C++ Debug",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/examples/blink",
            "sourceFileMap": {
                "/root/src/WiringOP-Zero/examples/blink.c": "${workspaceRoot}/examples/blink.c"
            },
            "cwd": "${workspaceRoot}",
            "miDebuggerServerAddress": "192.168.20.51:4444",
            "miDebuggerPath": "C:\\Program Files (x86)\\GNU Tools ARM Embedded\\6 2017-q1-update\\bin\\arm-none-eabi-gdb.exe",
            "windows": {
                "MIMode": "gdb"
            }
        }
```
but i'm still hitting walls.
This is the output i get and it breakpoints seems to not hold.
```
=thread-group-added,id="i1"
GNU gdb (GNU Tools for ARM Embedded Processors 6-2017-q1-update) 7.12.1.20170215-git
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-w64-mingw32 --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
0xb6fd7bc0 in ?? ()
Loaded 'shared libraries loaded at this time.'. Cannot find or open the symbol file.
Breakpoint 1, main () at blink.c:35
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
```
Any ideas?

**Comment by pieandcakes** [comment]
@justin-romano So heres a question: Do you need to use gdbserver on the remote arm device? Or can gdb be run on that device and you connect to it through SSH? If you can do the latter and have source locally, I think you might like the `"pipeTransport"` option (documentation [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md)).

Otherwise, i'd make sure you have compiled with the `"-g"` flag with gcc to build with symbols. You can also try and enable `"stopAtEntry": true` and see if it breaks on the first line of your `main()` method.

**Comment by pieandcakes** [comment]
This is an older issue and hasn't had any updates. Please comment/open a new issue if it is still happening.
