### ISSUE TITLE
compilerArg isn't used if compilerPath isn't explicitly set

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5776]
I wanted to add a compilerArg (using the existing default CompilerPath), but it didn't get used until I explicitly added the compilerPath.

**Comment by sean-mcmanus** [comment]
Or it should give some sort of warning that the compilerPath is required to be explicitly added.

**Comment by bobbrow** [comment]
@Colengms can you take a look at this?  I was thinking this was supposed to work because the Windows team has a custom config provider extension that depends on this behavior.  It could be that this only is a problem for standard `c_cpp_properties.json` configs.

**Comment by sean-mcmanus** [comment]
I hit this issue again today, when I added compilerArgs with "/clr" etc. with the intent of it applying to the default cl.exe compiler -- it didn't work until I manually added the compilerPath to be "cl.exe".

**Comment by Colengms** [comment]
I have tried a number of things, with no repro.

**Comment by Colengms** [comment]
Only repro's if the default compiler is not explicitly set.
