### ISSUE TITLE
Symbol search by "#" on Mac cannot find all matched items

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5778]
**Type: LanguageService**

**Describe the bug**
Searching symbols by "#" in command palette cannot file all of the matched items. Seems to be an issue on Mac.

Found by internal testing.

**Comment by michelleangela** [comment]
Update: this can also be reproduced on other platforms too, but it is inconsistent on different machines.

**Comment by Ashley-Li** [comment]
Tested on C/C++ 1.22.0-dogfood2, this issue not repro on Windows x64 & Linux x64 & Mac ARM64 platform, but it is reproes on MinGW on Windows (64-bit version) with gcc compiler. Not Shown "myLibStr" when inputting string "#s"
![image](https://github.com/user-attachments/assets/033b6233-acc4-47f0-9e0b-3e99ad4e0278)

**Comment by sean-mcmanus** [comment]
@Ashley-Li I'm guessing that is "by design" because the "s" query is too short and it may be hitting the internal query limit for results. I think if you use more letters in the search it should appear.

**Comment by Ashley-Li** [comment]
@sean-mcmanus Thanks for your confirmation and update. Tested on C/C++ 1.22.0 (pre-release) with MinGW on Windows (64-bit version) with gcc compiler, using more characters, such as “#my”,  the ”myLibStr“ can be searched.

![image](https://github.com/user-attachments/assets/db2ec8b9-23d1-45a0-adfe-69f906ddf489)

**Comment by Colengms** [comment]
There's been a lot of work done on this feature recently.  I think we can consider this particular issue completed.
