### ISSUE TITLE
Semantic Colorization is not working?

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#5780]
With 0.29.0, the Semantic Colorization feature has been migrated to VS Code's new Semantic Tokens API.  Depending on which version of VS Code is used and which theme is used, this feature may regress for some users.

For Semantic Colorization to work as expected with >=0.29.0, either:

a) Upgrade to a version of VS Code >=1.47
b) Use a theme that opts-in to semantic highlighting.  (All themes bundled with VS Code should).
c) Enable Semantic Highlighting using the following setting:
```
    "editor.semanticTokenColorCustomizations": {
        "enabled": true
    }
```

**Comment by hyuuko1** [comment]
It works well in my machine.
![@GZM_PS_TGKY)L@OX8IE7CS](https://user-images.githubusercontent.com/44204137/87677113-f6130c80-c7ab-11ea-8582-81cb647f43fb.png)
before 0.29.0:
![)2(OU)C29M1Y6LJU9AH4TR9](https://user-images.githubusercontent.com/44204137/87677245-1fcc3380-c7ac-11ea-8028-7dd902a72aca.png)
theme: Default Dark+

**Comment by Colengms** [comment]
Closing this, as it was created just to be pinned, for users who might have been impacted as these changes were introduced.
