### ISSUE TITLE
Multiline comments: * should be auto-inserted on enter

### ISSUE THREAD

**Issue by ecbrodie** [microsoft/vscode-cpptools#579]
When I am writing a multiline comment in C/C++ code (ie, ` /* ... */`) and I press enter while typing in the middle of the comment, then a `*` character should be automatically inserted at the beginning of the new line, indented to match the `*` character of the comment's opening line. This is the default behaviour in almost every other IDE that I've had experience working with. However, in VS Code, I need to add in this new character at the start of the line new. It is a little tedious to need to do this all the time.

Please fix. Thank you.

**Comment by FHTheron** [comment]
This: https://marketplace.visualstudio.com/items?itemName=kevinkyang.auto-comment-blocks
helps a bit, but has some quirks which I haven't yet tried to debug. For `/**` it works well, for `/*` it seems to only work if you already have three lines in place.

Built-in support would be great though.

**Comment by bobbrow** [comment]
Our implementation will be similar.  It won't turn on automatically for `/*`, but if you add the `*` on the next line, we will continue it for subsequent lines.  `/**` will work as you expect.

**Comment by bobbrow** [comment]
This was released in 0.13.0
