### ISSUE TITLE
Only Doxygen comments above function definition are parsed

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#5795]
Only doxygen comments above function definition are parsed and shown over tooltip. Comments above function declaration are ignored.

Is there any setting which decides this?

_Originally posted by @magdumnikhil in https://github.com/microsoft/vscode-cpptools/issues/658#issuecomment-660070996_

**Comment by michelleangela** [comment]
@magdumnikhil , there is no setting to choose which comment (declaration or definition) gets displayed in the tooltip.

However, I was not able to reproduce the behavior of _only comments from definitions are displayed in the tooltip_. Could you provide a sample repro for this?

The repro I tried was the following, where hover over function call displays comments from declaration
![image](https://user-images.githubusercontent.com/38734287/87831064-54d19800-c837-11ea-99b1-d20b66d7718a.png)

And repro with function declaration and definitions in separate files:
![image](https://user-images.githubusercontent.com/38734287/87831139-7df22880-c837-11ea-864f-022093bca226.png)

![image](https://user-images.githubusercontent.com/38734287/87831171-8a768100-c837-11ea-852c-e8d0999572a0.png)

![image](https://user-images.githubusercontent.com/38734287/87831186-95311600-c837-11ea-9e87-8617df713fc1.png)

![image](https://user-images.githubusercontent.com/38734287/87831198-9eba7e00-c837-11ea-9659-25682389230e.png)

**Comment by magdumnikhil** [comment]
In my current workspace, this is getting reproduced, but I can't share the it directly.
Also, I'm seeing some error squiggles for #includes, possibly that can be the reason for this.

I will try to get rid of those, and comment again.

**Comment by csgregg** [comment]
I am experiencing this too, but not consistently. It happens on some functions but not others and I cannot see what the determining factor is. Even with overloaded functions, it doesn't do it consistently between them. I just can't pin it down.

It's a real pain as I want to put the doxygen comments with the declarations following best practice - comment 'what it does' in the header and 'how it works' in the source.

Here's some examples -
Class comment not working -
![image](https://user-images.githubusercontent.com/18298829/96705509-50180500-138d-11eb-85a1-77e1d74214c5.png)

Function comment not working -
![image](https://user-images.githubusercontent.com/18298829/96705577-66be5c00-138d-11eb-91d5-57b0fe686669.png)

Overloaded function with one working and one not -
![image](https://user-images.githubusercontent.com/18298829/96705634-73db4b00-138d-11eb-822e-e5f50918b1ee.png)
![image](https://user-images.githubusercontent.com/18298829/96705651-789fff00-138d-11eb-8f08-f558f0bc9eae.png)

None of these have comments with the definitions. If I move them to the definitions, then they all work.

Here's the file in the repo - https://github.com/csgregg/csg-esp8266-rota/blob/Debuging-doxygen-comments/lib/Logger/src/Logger.h

**Comment by sean-mcmanus** [comment]
Can you still repro this with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2? I'm not reproing it, but I might not be configured the same.

![image](https://user-images.githubusercontent.com/19859882/105412978-4dc28280-5bea-11eb-94dc-64f46f65e18c.png)
