### ISSUE TITLE
No include autocomplete with Visual Assist

### ISSUE THREAD

**Issue by sreitbauer** [microsoft/vscode-cpptools#5796]
**Type: LanguageService**

**Describe the bug**
I'm using Visual Assist 10.9.2382 in Visual Studio 2019 and vcpkg 2020.06.15. When I try to include a header file, there is no autocomplete for folders and files from vcpkg. vcpkg itself works fine, but the missing autocomplete is quite annoying. With Visual Assist disabled, everything works again.

**Expected behavior**

Folders and files should be listed.

**Screenshots**

![image](https://user-images.githubusercontent.com/55457291/87814508-2ae29a80-c864-11ea-97c8-975897d72774.png)

**Comment by michelleangela** [comment]
Is this an issue from Visual Studio or the C/C++ extension for VS Code?

To report issues for Visual Studio, follow instructions at https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
