### ISSUE TITLE
Not able to give input to the program.

### ISSUE THREAD

**Issue by wangdefawaz** [microsoft/vscode-cpptools#5799]
Type: Debugger
When I run the program the the debug starts but when the control reaches the input line the debug stops.

- OS: macOS Catalina and Version:10.15.6
- VS Code Version:1.47.2
- C/C++ Extension Version:0.29.0
- Other extensions you installed (and if the issue persists after disabling them):Python by Microsoft. After disabling nothing happens.
- The debugger works fine as long as there is no external input required. Even running the program without debugging also works fine as long as external input is not required. Actually there is no option to insert the input after the task starts. And hence when the control reaches the line on which scanf is present it stops directly. I tried the launch.json config and the tasks.json config on the website as well as the defaults ones, the issue still remains. I also tried different workarounds available on the internet.

**Code Sample**
#include<stdio.h>

int main(){
    int n;
    printf("Enter the value to display");
    scanf("%d",&n);
    printf("%d",n);
}

**launch.json**
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang - Build and debug active file",
            "type": "cppdbg",
            "targetArchitecture": "x86_64",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang build active file"
        }
    ]
}

**tasks.json**
{
    "tasks": [
        {
            "type": "shell",
            "label": "C/C++: clang build active file",
            "command": "/usr/bin/clang",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ],
    "version": "2.0.0"
}

**Steps to reproduce the behavior:**
1. Save the above mentioned C file in the workspace folder.
2. Try running the program by clicking on Run in the top menu and then selecting either Start Debugging or Run without Debugging.
3. Once done, the running will start and C++:clang build active file will start running in Terminal column.
4. No problems shown in Problems section. Nothing is shown in output. The last line of Debug console is "@"Enter the value to display""
5. The last line of Terminal is "Terminal will be reused by tasks, press any key to close it."

**Additional context**
Not able to include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json. It is giving error as "engineLogging is not allowed" and same is the case with other two properties.

**Debug console**
=thread-selected,id="1"
=library-unloaded,id="/Users/fawazwangde/MyWorkspace/first",target-name="/Users/fawazwangde/MyWorkspace/first",host-name="/Users/fawazwangde/MyWorkspace/first"
Loaded '/usr/lib/dyld'. Symbols loaded.
Loaded '/Users/fawazwangde/MyWorkspace/first'. Symbols loaded.
Loaded '/usr/lib/libSystem.B.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcache.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcommonCrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcompiler_rt.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcopyfile.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcorecrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdispatch.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdyld.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libkeymgr.dylib'. Symbols loaded.
Loaded '/usr/lib/system/liblaunch.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libmacho.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libquarantine.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libremovefile.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_asl.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_blocks.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_c.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_configuration.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_coreservices.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_darwin.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_dnssd.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_featureflags.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_info.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_m.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_malloc.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_networkextension.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_notify.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_sandbox.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_secinit.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_kernel.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_platform.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_pthread.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_symptoms.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_trace.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libunwind.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libxpc.dylib'. Symbols loaded.
Loaded '/usr/lib/libobjc.A.dylib'. Symbols loaded.
Loaded '/usr/lib/libc++abi.dylib'. Symbols loaded.
Loaded '/usr/lib/libc++.1.dylib'. Symbols loaded.
@"Enter the value to display"

**Comment by WardenGnaw** [comment]
There is no `intergratedTerminal` support for macOS. You will need to set `"externalConsole": true` and then you will be able to provide input.

**Comment by wangdefawaz** [comment]
> There is no `intergratedTerminal` support for macOS. You will need to set `"externalConsole": true` and then you will be able to provide input.

Tried that. A blank terminal opens up. No prompt for input. Attaching the screenshot of terminal and the editor.
![Screenshot 2020-07-20 at 11 46 29 PM](https://user-images.githubusercontent.com/65999939/87971766-78206f80-cae3-11ea-8e7d-2baf1db5969c.png)
![Screenshot 2020-07-20 at 11 46 43 PM](https://user-images.githubusercontent.com/65999939/87971771-7a82c980-cae3-11ea-973e-5906c60abb47.png)
And after I stop the program by pressing Shift F5 a timeout error appears at the bottom right corner. Attaching the screenshot of that as well.
![Screenshot 2020-07-20 at 11 47 21 PM](https://user-images.githubusercontent.com/65999939/87972076-f4b34e00-cae3-11ea-9d5c-ca055f107ae4.png)

**Comment by WardenGnaw** [comment]
Looks like VS Code is having issues launching the externalConsole. Can you see if the the solution in https://github.com/microsoft/vscode-cpptools/issues/5079#issuecomment-626090192 works?

**Comment by wangdefawaz** [comment]
> Looks like VS Code is having issues launching the externalConsole. Can you see if the the solution in [#5079 (comment)](https://github.com/microsoft/vscode-cpptools/issues/5079#issuecomment-626090192) works?

Thanks, solved the problem. Now it takes the input. But the output doesn't show up on terminal until the end of the program when debugging. Is this normal?

**Look at the present line in the debugger.**
![Screenshot 2020-07-21 at 7 13 18 AM](https://user-images.githubusercontent.com/65999939/88003201-e84de600-cb21-11ea-99df-9a10632a5b2a.png)
![Screenshot 2020-07-21 at 7 13 30 AM](https://user-images.githubusercontent.com/65999939/88003218-f3087b00-cb21-11ea-8123-c14724dbd917.png)

**After the program is completed.**
![Screenshot 2020-07-21 at 7 14 05 AM](https://user-images.githubusercontent.com/65999939/88003308-3367f900-cb22-11ea-9a30-d4d1fb3e6557.png)

**Comment by WardenGnaw** [comment]
That is by the design of C++. You can have it immediate output to the window if you add `\n` to your printf statements. 

For more information, you will want to look into `Flushing the Output Buffer in C++`.

**Comment by wangdefawaz** [comment]
> That is by the design of C++. You can have it immediate output to the window if you add `\n` to your printf statements.
> 
> For more information, you will want to look into `Flushing the Output Buffer in C++`.

Thank you solved that problem as well.

**Comment by WardenGnaw** [comment]
Closing issue for now. If you have any other issues, let us know.

Thank you.

**Comment by umasankar-yedida** [comment]
> Looks like VS Code is having issues launching the externalConsole. Can you see if the the solution in [#5079 (comment)](https://github.com/microsoft/vscode-cpptools/issues/5079#issuecomment-626090192) works?

I have tried this approach, but still it shows blank terminal. Also, when I click on Stop, it shows *timeout after 1000 ms*. Don't know what that means.. :(
