### ISSUE TITLE
Snippet autocomplete suggestions no longer working

### ISSUE THREAD

**Issue by Nightro** [microsoft/vscode-cpptools#580]
.cpp snippet autocomplete suggestions have disappeared in the last week or so (I just noticed today). I can still insert my snippets if I do ctrl+shift+p Insert Snippet, but the suggestions are really what saves me time.

I tried adding the following to my settings.json and reloading. No difference.

```
    "C_Cpp.autocomplete": "Disabled",
    "C_Cpp.formatting": "Disabled",
    "editor.quickSuggestions": true
```
They start working again if I disable the cpp-tools extension :(

I am on version 0.10.4

An example snippet from my cpp.json:
```
    "Function Summary":
    {
        "prefix": "fs",
        "body": [
            "/// <summary>${1:Function Usage}</summary>"
        ],
        "description": "Insert Function Summary"
    }
```

**Comment by sean-mcmanus** [comment]
See https://github.com/Microsoft/vscode-cpptools/issues/572 for the solution.
