### ISSUE TITLE
word-base AutoComplete not working when I set "AutoComplete" as "Disabled"

### ISSUE THREAD

**Issue by vincentbryan** [microsoft/vscode-cpptools#5801]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOs 10.14.6 
- VS Code Version: June 2020 (version 1.47)
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Go to User Setting
2. Set "AutoComplete" as "Disabled"
3. In editor, word-base AutoComplete fails to work

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/17898371/87856717-7627a680-c953-11ea-916b-01572d747b33.png)
![image](https://user-images.githubusercontent.com/17898371/87856720-7f187800-c953-11ea-8f56-ee045bf645bd.png)

If I disable this plugin, word-base autocomplete will work.
![image](https://user-images.githubusercontent.com/17898371/87856791-0960dc00-c954-11ea-983d-ea33bc3f4daa.png)

**Comment by bobbrow** [comment]
Our extension disables the word-based suggestions because in most cases they confuse our developers.  To turn them back on, add the following settings into your "User" settings file to override our defaults:
```
    "[c]": {
        "editor.wordBasedSuggestions": true
    },
    "[cpp]": {
        "editor.wordBasedSuggestions": true
    }
```
