### ISSUE TITLE
cant identify friend class

### ISSUE THREAD

**Issue by m4p1e** [microsoft/vscode-cpptools#5802]
Type: General

**Describe the bug**
- OS and Version: Linux maple 5.3.0-kali2-amd64 # 1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux
- VS Code Version: 1.46.1
- C/C++ Extension Version: v0.29.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

1. git clone https://github.com/abenkhadra/bcov
2. open it with vscode

```c++
class ElfModule {
    friend class ElfModuleBuilder;
...
}

ElfModule
ElfModuleBuilder::build(sstring_view file)
{
    static auto is_ignorable = [](const ElfFunction &function) {
        auto name_it = std::find(IgnorableStaticFunctions.begin(),
                                 IgnorableStaticFunctions.end(), function.name());
        return name_it != IgnorableStaticFunctions.end();
    };

    ElfModule module;
    module.binary(ElfParser::parse(file));
```
it will report a error

function "bcov::ElfModule::binary(elf::elf binary)" (declared at line 611) is inaccessible

so many that error reported ,but this project work well, compiled without error.

**Expected behavior**
no error report

**Screenshots**
![Screenshot from 2020-07-19 15-33-15](https://user-images.githubusercontent.com/38675350/87869684-33f27980-c9d4-11ea-9373-c99cf37deeab.png)

**Additional context**

**Comment by michelleangela** [comment]
@m4p1e  can you provide your c_cpp_properties.json or IntelliSense configuration settings?

**Comment by m4p1e** [comment]
> @m4p1e can you provide your c_cpp_properties.json or IntelliSense configuration settings?

c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

user setting.json
```json
{
    "window.zoomLevel": 1,
    "diffEditor.renderSideBySide": false,
    "C_Cpp.updateChannel": "Insiders",
    "workbench.editor.enablePreview": false
}
```

workspace setting.json
```json
{
    "C_Cpp.errorSquiggles": "Disabled",
    "files.associations": {
        "typeinfo": "cpp",
        "array": "cpp"
    }
}
```

default setting.json didnt motified.

**Comment by sean-mcmanus** [comment]
@michelleangela Were you able to repro this? Did you need more info or did you want me to try to repro it?
