### ISSUE TITLE
Inline assembly-highlighting and strange highlighting of '__asm__' keyword

### ISSUE THREAD

**Issue by nkdmSum** [microsoft/vscode-cpptools#5804]
When you use inline assembly like this:
`__asm__
(
    "movl $1, %eax"
    "movl $2, %ecx"
)`
The assembly-code is the same colour as strings.

I understand that there is no standard assembly highlighting but it could be useful if you could select one(Extension) in the settings.

Also: The `__asm__` is only highlighted in blue if the '(' is in the same line. Else it's white.

This is how it looks with '(' in same line:
<img width="216" alt="Снимок экрана 2020-07-19 в 16 43 10" src="https://user-images.githubusercontent.com/51021475/87877518-1aa2fa80-c9df-11ea-8eae-758bf6888d5f.png">
This is how it looks with '(' in next line:
<img width="227" alt="Снимок экрана 2020-07-19 в 16 43 29" src="https://user-images.githubusercontent.com/51021475/87877515-14ad1980-c9df-11ea-94a6-8c097b5b308e.png">

**Comment by Colengc** [comment]
Hi @nkdmSum , The C/C++ extension (as of 0.29.0) provides semantic tokens to VS Code for colorization, but a lot of colorization is still coming from VS Code for syntactically identified keywords, etc., based on TextMate grammar.  The command `Developer: Inspect Editor Tokens and Scopes` now indicates whether something is colored semantically.

It looks like `__asm__` is not colored semantically, so this would be an issue with TextMate grammar.  That grammar for C++ is provided by [this repo](https://github.com/jeff-hykin/cpp-textmate-grammar).  There is also an extension "Better C++ Syntax" which uses this grammar and is often updated more frequently than VS Code.  Installing the latest version of that extension appears to correct this issue.

**Comment by Colengms** [comment]
Hi @nkdmSum , The C/C++ extension (as of 0.29.0) provides semantic tokens to VS Code for colorization, but a lot of colorization is still coming from VS Code for syntactically identified keywords, etc., based on TextMate grammar.  The command `Developer: Inspect Editor Tokens and Scopes` now indicates whether something is colored semantically.

It looks like `__asm__` is not colored semantically, so this would be an issue with TextMate grammar.  That grammar for C++ is provided by [this repo](https://github.com/jeff-hykin/cpp-textmate-grammar).  There is also an extension "Better C++ Syntax" which uses this grammar and is often updated more frequently than VS Code.  Installing the latest version of that extension appears to correct this issue.
