### ISSUE TITLE
LLDB debugger hangs (using 100% cpu) at launch if std::map is uninitialised 

### ISSUE THREAD

**Issue by zwangz** [microsoft/vscode-cpptools#5805]
Type: Debugger

**Describe the bug**
- OS and Version: macOS 10.14.6  (Darwin x64 18.7.0)
- VS Code Version: 1.47.2
- C/C++ Extension Version: 0.29.0
- Issue:

Similar log to [#860](https://github.com/microsoft/vscode-cpptools/issues/860#issuecomment-612632659)
When using `include <map>`and `std::map`/`std::multimap` without initialisation the debugger hangs at launch and is stuck at `-var-create - - "map_variable_name" --thread 1 --frame 0`; seems like no garbage value can be created
*See example **A** below*

However this does not happen, if before the (one) `std::map` declaration there is another `container` such as `std::vector` 
or `std::unordered_map` declared, even uninitialised.  
*See example **B** below*

And the problem re-surfaces if more than two `<map> contrainers` are used. 
*See example **C** below*

Therefore this seems to strangely happen only to std::map containers; a few other `stl containers` and `std::vector` alone uninitialised can launch fine and be seen in the local variables window

Please could you investigate? many thanks in advance

**To Reproduce**

1. *tasks.json*
```json
{
    "version": "2.0.0",
    "tasks": [
             {
            "type": "shell",
            "label": "clang++ build active file",
            "command": "/usr/bin/clang++",
            "args": [
                "-std=c++17", 			
                "-stdlib=libc++",
                "-Wall",
                "-g",
                "${fileDirname}/**.cpp",
                "-o",
		"${fileBasenameNoExtension}",
            ],
	    "options": {"cwd": "${fileDirname}"},
            "problemMatcher": ["$gcc"],
	    "group": "build",
		},
     ]
}
```
2. *launch.json*
```json
    "version": "0.2.0",
    "configurations": [
        {
            "name": "vscpp - Build and Debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb",
            "preLaunchTask": "clang++ build active file",
            "logging": {"engineLogging": true},
            "miDebuggerPath": "/Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi"
        },
    ]
```
3. *main.cpp* using examples below:

`EXAMPLE A`
```c++
#include <iostream>
#include <string>
#include <map> 
#include <unordered_map>
#include <vector>

int main() {
    std::cout << "ISSUE" << std::endl;

    // std::unordered_map<int, int> unord_map;
    // std::vector<int> my_v;             // Same effect as using unordered_map

    std::map<int,int> my_map;
    // std::multimap<int, int> multi_map; // Same issue as my_map
    // std::map<int,int> my_map2;

    std::cout << "ISSUE" << std::endl;
    return 0;
}
```
![image](https://user-images.githubusercontent.com/62851772/87885749-af255100-ca0f-11ea-8d7c-d68ce30f29be.png)

`EXAMPLE B`
```c++
int main() {
    std::cout << "ISSUE" << std::endl;

    std::unordered_map<int, int> unord_map;
    // std::vector<int> my_v;             // Same effect as using unordered_map

    std::map<int,int> my_map;
    // std::multimap<int, int> multi_map; // Same issue as my_map
    // std::map<int,int> my_map2;

    std::cout << "ISSUE" << std::endl;
    return 0;
}
```
![image](https://user-images.githubusercontent.com/62851772/87885756-c5331180-ca0f-11ea-8330-b6d7351bec98.png)

`EXAMPLE C` - stuck at `multi_map`
```c++
int main() {
    std::cout << "ISSUE" << std::endl;

    std::unordered_map<int, int> unord_map;
    // std::vector<int> my_v;             // Same effect as using unordered_map

    std::map<int,int> my_map;
    std::multimap<int, int> multi_map; // Same issue as my_map
    // std::map<int,int> my_map2;

    std::cout << "ISSUE" << std::endl;
    return 0;
}
```
![image](https://user-images.githubusercontent.com/62851772/87885780-e267e000-ca0f-11ea-90de-b5654bc36373.png)

4. launch debugger
Full log for example A
[log.txt](https://github.com/microsoft/vscode-cpptools/files/4944677/log.txt)
cpu usage when hanging
![image](https://user-images.githubusercontent.com/62851772/87885064-d3326380-ca0a-11ea-9341-768253eeed4c.png)

**Comment by WardenGnaw** [comment]
@zeeepw Thanks for the very detailed issue. 

I will need to validate if this occurs in `lldb` with the non-MI commands.

**Comment by zwangz** [comment]
> @zeeepw Thanks for the very detailed issue.
> 
> I will need to validate if this occurs in `lldb` with the non-MI commands.

Hello, has there been any progress pls?

**Comment by chrish42** [comment]
I'm having what looks like the same problem, on a big codebase (Apache Arrow). As soon as I get to a stack frame that contains more complex objects (that use STL collections in their implementation, the debugger freezes and does not respond to commands. Looking at things under the hood, VSCode is waiting forever on a reply to the following: `1: (18328) <-1041-var-create - - "parser" --thread 1 --frame 0` (`parser` is a variable that uses STL collections).

This is making C++ debugging completely unusable for me.

**Comment by bubbercn** [comment]
I've been experiencing this issue when debugging C++ program in macOS. When this happens, I have to turn to Xcode which works perfectly. So I would have to guess lldb works fine and it is a lldb-mi specific issue.

> @zeeepw Thanks for the very detailed issue.
> 
> I will need to validate if this occurs in `lldb` with the non-MI commands.

**Comment by DominicCabral** [comment]
Can confirm this is still happening on:
OS and Version: macOS 10.15.7
VS Code Version: 1.53.2
C/C++ Extension Version: 1.2.0

**Comment by arvindx101** [comment]
HI

Is there any update on this ? I am writing a simple C++ program for maps and not able to debug at all!!

**Comment by bubbercn** [comment]
I just can not believe this issue still hasn't been addressed. I've been running into this for more than one year. And my workaround is to not use lldb-mi at all.

**Comment by Wdong04** [comment]
just ran into it. Cannot believe it is still unresolved

**Comment by blanerhoads** [comment]
Happens to me with unordered_map, sometimes even if it's initialized.

I just need an IDE with a debugger and a CMake extension for OSX. Any workarounds or recommendations?

**Comment by remyers** [comment]
Can confirm this is still happening on:
OS and Version: macOS 11.6
VS Code Version: 1.62.0
C/C++ Extension Version: 1.7.1

When I uncomment the declaration of multi_map (example C) and set a breakpoint on the first line of main() or have "stopAtEntry": true then lldb-mi goes to high CPU and I have to kill it and the debugged process manually.

I could also reproduce the high cpu hang without a breakpoint on the first line of main() if I attached to the process and put the code in a function called after a sleep with a breakpoint at the start of the function.

**Comment by ScherbakovAl** [comment]
I also ran into a similar issue.

**Comment by TwentyPast4** [comment]
Same here

**Comment by BruceMorgan** [comment]
Same.  This happens frequently with Chromium code, macOS, latest versions of everything.

**Comment by nazavode** [comment]
> I have a similar problem and I noticed the local section in the variables window in the Visual Code debugger has a spinner during the hang. I hid the variables window and the debugger no longer hangs. Hopefully this works for someone else because this was driving me insane.

It works, thanks. Not a solution but this allows to actually debug stuff, at least.

**Comment by sebrockm** [comment]
@csloan-gmail Thanks! That works for me **if in addition** I'm also super careful with my mouse to not accidentally hover over a map.

**Comment by filipecustodio** [comment]
Thanks @csloan-gmail same problem here. Workaround (not looking at variables) at least allows me to move forward.

**Comment by eliyaoo32** [comment]
> I have a similar problem and I noticed the local section in the variables window in the Visual Code debugger has a spinner during the hang. I hid the variables window and the debugger no longer hangs. Hopefully this works for someone else because this was driving me insane.

Thanks, it solved the issues.
I hope it will be fixed soon.

**Comment by basdp** [comment]
Have the same problem on MacOS, hiding variable window is a partial workaround for now.

**Comment by filipecustodio** [comment]
I have the same experience both on LLDB and on Perl Debugger, using VSCode on Mac, so maybe the problem is not in LLDB but in VSCode?

Cheers

FC

**Comment by alexolog** [comment]
The CodeLLDB extension works without hanging (or hogging the CPU, or using all the memory) on Apple M1, so it can be done.
https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb

**Comment by gojzdar** [comment]
Same here. I can't debug at all if my HandleMouseEvent(SDL_mouse) ) is in the call stack. Works perfectly fine everywhere else.

Using Kubuntu 23.04, CodeLLDB

**Comment by javabr** [comment]
this is still happening!

**Comment by finnwang1984** [comment]
this is still happening!

**Comment by zeves095** [comment]
Apple M3 Pro MacOs 15.0  [ VSCode 1.94.2 (Universal) OS: Darwin arm64 24.0.0 ]

problem still exists.

I found several solutions:

1. as said above - hide variables and expand it when pass "bad" lines.  - but it's not solution for debug - if i have in code in many places not initialized vars - while they all not passed - if I expand - I hung up. 
in this variant I use external terminal and launch.json:
`{
    "configurations": [
       {
            "name": "C/C++: clang++ сборка и отладка активного файла",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang++ сборка активного файла"
        }
    ],
    "version": "2.0.0"
}`

2. second solution I'm using now is plugin CodeLLDB - with internal terminal. launch.json:
`{
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Launch",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}",
            "args": [],
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "C/C++: clang++ сборка активного файла"
        }
    ],
    "version": "2.0.0"
}`
this one best for now (but I hear that it plugin have some issues in other places.. will see)
