### ISSUE TITLE
Coloring and IntelliSense follows host computer, and defines platform incorrectly.

### ISSUE THREAD

**Issue by Elastino** [microsoft/vscode-cpptools#5808]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Darwin x64 19.5.0
- VS Code Version: 1.48-insider
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): N/A
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Coloring and IntelliSense follows host computer, and defines platform incorrectly.
On MacOS, it defines __APPLE__ which is not for the current active platform.

**Steps to reproduce**

<img width="732" alt="config" src="https://user-images.githubusercontent.com/8371666/88005794-1db7fb00-cb45-11ea-9126-18e95b60cc69.png">
<img width="641" alt="error" src="https://user-images.githubusercontent.com/8371666/88005808-214b8200-cb45-11ea-9fee-ee45b6b865eb.png">

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I believe this is the same issue as https://github.com/microsoft/vscode-cpptools/issues/1083 (we don't support cross compilation on the Mac targetting non-Mac platforms yet).

**Comment by Elastino** [comment]
Thank you for updating, I thought it was working fine until 0.28.3.
