### ISSUE TITLE
Autocompletion doesn't work for local variable

### ISSUE THREAD

**Issue by ymkim92** [microsoft/vscode-cpptools#5809]
**Type: LanguageService**
I can autocomplete functions and global variables but can't auto complete local variables.
When I disable cpptools, local variables can be autocompleted.

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.47.2
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

I have removed "code" folder from AppData. I think the location was "C:\Users\$USER$\AppData\Roaming\Code".
Before I removed the folder, there was no this problem. I am sorry I can't remember why I removed the folder.

**Expected behavior**

1. Logs from the command `C/C++: Log Diagnostics`
No error
```
Offering completion
Offering completion
idle loop: reparsing the active document
Offering completion
idle loop: reparsing the active document
Offering completion
Offering completion
Offering completion
Offering completion
```
2. Logs from [the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
No error in "toggle developer tools" > console

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![code1](https://user-images.githubusercontent.com/3033436/88014234-cb390780-cb61-11ea-871b-1d5277721298.png)
![code2](https://user-images.githubusercontent.com/3033436/88014244-d2601580-cb61-11ea-9456-d378772a8343.png)

**Additional context**

**Comment by bobbrow** [comment]
It looks like semantic IntelliSense is disabled here.  What is the value of the `C_Cpp.intelliSenseEngine` setting in your workspace?  Based on the symptoms, it appears that it is set to "Tag Parser".  Try setting it to "Default."

**Comment by ymkim92** [comment]
Thanks @bobbrow ,
It works after changing  `C_Cpp.intelliSenseEngine` to Default in the Windows code. 
But it still has the same problem in my WSL code. Please let me know if you need more information.

[settings.json]
```
    "C_Cpp.errorSquiggles": "Enabled",
    "C_Cpp.intelliSenseEngineFallback": "Enabled",
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.loggingLevel": "Debug"
```

```
>wslconfig/l
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
```

**Comment by bobbrow** [comment]
@ymkim92 did you delete your comment?  I saw you set "C_Cpp.intellisenseEngineFallback": "Enabled".  You should disable that setting (or we should just delete it from the extension).  That setting will cause the extension to use the Tag Parser when it fails to resolve one of your `#include` statements.  I suspect that's what's happening in your WSL project.

**Comment by ymkim92** [comment]
Thanks @bobbrow ,
Autocompletion works after changing `C_Cpp.intelliSenseEngine` to "Default".
But I found follow-up problems after that.
Please see the following code and comments:

```
#include <iostream>

int globalTestInt;
void Func(int intFunc)
{
    intFunc = 0; // works fine for auto-completion and "go to definition"
}

void Func2(data::Acceleration &intFunc)
{
    intFunc = 0; // doesn't work for auto-completion and "go to definition"
}

void Func3(uint32_t intFunc)
{
    intFunc = 0; // doesn't work for auto-completion and "go to definition"
}

int main()
{
    int testInteger;

    testInteger = 0;
    globalTestInt = 1;
    testI
    Fu
}
```

What I found from the above test is that if data type is not defined or can't find it, intellisense doesn't work after that.
Is this correct behavior?
But I think it could work for local variable within `Func3()` and `main()`. What do you think?

**Comment by bobbrow** [comment]
Usually the compiler can recover from an undefined symbol.  In this case it looks like the `&` after the undefined type breaks the compiler for the remainder of the source file.  Removing the `&` but keeping the undefined type appears to be a recoverable error.

This behavior is in our shared compiler code with Visual Studio.  Would you be willing to open an issue on [Developer Community](https://developercommunity.visualstudio.com/) so that the Visual Studio team can track this issue?

**Comment by ymkim92** [comment]
Thanks @bobbrow ,

I didn't know you could check my comment even if I delete it.
I wrote the previous comment without reading your comment for my deleted one. I am sorry.

**Comment by bobbrow** [comment]
I get email notifications, so I can still read it in my inbox if it was deleted. 😃 Hopefully my comment was still helpful.

**Comment by ymkim92** [comment]
It was very helpful. Thank you so much 👍.
