### ISSUE TITLE
Format document on C++ bad indent (Tab vs spaces)

### ISSUE THREAD

**Issue by funvill** [microsoft/vscode-cpptools#581]
Moving issue from https://github.com/Microsoft/vscode/issues/22859

- VSCode Version: 1.10.2
- OS Version: Windows 10 Home 64bit
- C/C++ extension: Version 0.9.2

Steps to Reproduce:

1. Create new file with extension .cpp (example.cpp)
2. Past code into document and save.
```
void bar()
{
    int foo = 0;
    if (foo)
    {
        foo = 1;
    }
}
```
3. [alt]+[shift]+F to "format document"

Expected the output to stay the same. Got the following output

```
void bar()
{
    int foo = 0;
    if (foo)
    {
    foo = 1;
    }
}
```

This looks to be an issue with tabs vs spaces. I think it's still a bug with the format document function as it produces an undesired output.

Below is a workaround

1. Create new file with extension .cpp (example.cpp)
2. Past code into document and save.
```
void bar()
{
    int foo = 0;
    if (foo)
    {
        foo = 1;
    }
}
```
3. Select all
4. From the command palette "Convert indentation to spaces"
5. Got the expected output

**Comment by funvill** [comment]
And it looks like this issue was resolved in version 0.10.4

**Comment by sean-mcmanus** [comment]
Was there a reason you were on 0.9.2? We fixed a lot of bugs since then.

**Comment by funvill** [comment]
@sean-mcmanus My own stupidity. I have not update my extensions in a while, and I didn't have auto update enabled. No good reason. 

Thank you!
