### ISSUE TITLE
PerfTips like in VS

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode-cpptools#5815]
Type: Debugger

Would be nice to have PerfTips with execution time like in Visual Studio:
https://docs.microsoft.com/en-us/visualstudio/profiling/perftips#perftips-1

microsoft/vscode#105417

**Comment by melroy89** [comment]
Yes please!!!

**Comment by Trass3r** [comment]
Shouldn't be done on a debug adapter level.
See https://github.com/microsoft/vscode/issues/105417#issuecomment-687004553
