### ISSUE TITLE
switch header not working for "*.hpp"

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#582]
i have 2 files
`main.cpp`, `main.hpp`
trying to `switch header/source` from `main.cpp` does not work, but trying from `main.hpp` do work,
and renaming `main.hpp` to `main.h` make every thing work

**Comment by sean-mcmanus** [comment]
I'm not able to repro the bug. What version of the extension do you have? Both .h and .hpp should be recognized equally.

**Comment by ghost** [comment]
i have the latest version,

**Comment by sean-mcmanus** [comment]
0.10.4? The latest version will depend on your VS Code version. What extensions do you have installed? How are you invoking the header switch? Alt+O? Do you see the C/Cpp: Switch Header/Source right-click option? I'm trying to figure out why we're not able to repro the bug.

**Comment by ghost** [comment]
i use this to do the switch
`
    {
        "key": "f4",
        "command": "C_Cpp.SwitchHeaderSource",
        "when": "editorTextFocus"
    }
`
and vscode is the latest

**Comment by sean-mcmanus** [comment]
It's possible the main.hpp is not in being parsed for some reason. Can you add some code to the header like "int main_hpp;" and see if it shows in the hover tooltip? Is the *.hpp in files.exclude? Are the files in the same folder? When it doesn't work, does nothing happen or does the wrong file open? We should be shipping an update today that fixes some bugs in this area, so let us know if that fixes it.

**Comment by ghost** [comment]
the file is being parsed, i can see the variables in the header files in the autocomplate. but the weird thing is that it do work if the files are named `a.hh` and `a.cc` but not `a.hpp` and `a.cpp`

**Comment by greazer** [comment]
Sorry for the trouble, hackereg35. We have been unable to reproduce the problem as has been described here. So we can think of a few things to try:
1) Temporarily disable any other extension to see if there is a conflict occurring somehow.
2) Try installing VSCode and the C++ extension on another machine to see if it repro's there too.

If you can get it to repro in those above two cases, then we must be missing some key aspect of your workspace. If you could zip up an example and send it to us we can take a look.

**Comment by bobbrow** [comment]
If you are able to send us additional information that can help us reproduce the issue, we can try to take a look again.  Closing the issue for now.
