### ISSUE TITLE
Problem with spaces in the first line of output

### ISSUE THREAD

**Issue by FreezeHands** [microsoft/vscode-cpptools#5820]
I was trying to create a star pattern in jupyter notebook on Visual Studio code, with this code:

        def pattern(n):
            k=2*n-2
            for i in range(0,n):
                for j in range(0,k):
                    print(end=' ')
                k-=1
                for j in range(0,i+1):
                    print('* ',end='')
                print('\r')
        pattern(4)
But for some reason it doesn't make the spaces in the first line of the output.
I tried in a normal juptyer notebook and it worked just fine.

Output from Visual Studio code in the jupyter notebook

           * 
                 * * 
                * * * 
               * * * *  

Output from jupyter notebook

                  * 
                 * * 
                * * * 
               * * * *  
I could resolve it by using the second line of output as it is the first for the pattern. With this post i want to put the attention on first line of output.

**Comment by bobbrow** [comment]
This sounds like a python issue.  Can you open an issue here instead: https://github.com/Microsoft/vscode-python/issues
