### ISSUE TITLE
error reported as "qualified name is not allowed" on preprocessor macro that compiles OK

### ISSUE THREAD

**Issue by dannypike** [microsoft/vscode-cpptools#5821]
Issue Type: <b>Bug</b>

It appears as though the C++ extension does not like this code in a header file:
```
#pragma once
#include "mikado.h"

namespace mikado
{
    namespace models {
        DECLARE_SHARED_PTR(Building);
        DECLARE_SHARED_PTR(BuildOperation);
        DECLARE_SHARED_PTR(City);
    }
}
```

where mikado.h contains this macro:
```
#define DECLARE_SHARED_PTR(TYPE) class TYPE; typedef std::shared_ptr<TYPE> TYPE##Ptr
```

It compiles OK, both in Visual Studio and Emscripten, but the VSCode editor underlines it with this [error message](https://prnt.sc/tmtmd9).

Is it perhaps confused because it's trying to scan and "understand" the header file as an stand-alone source module, and not as one of many header files in other source modules (one of which will define ```std```, for example)?

Extension version: 0.29.0
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
`#include <memory>` needs to be in the TU (source plus headers) somehow. It looks like that is missing in your repro? If you run C/C++: Log Diagnostics you can see info on how we are constructing the TU. The source file we are automatically choosing for the TU is probably not including that header (or is building a header only fallback TU if we fail to locate an includer source file).

I think it's a recommended practice to have your headers include all the include dependencies they rely on -- is there a reason for not adding the `#include <memory>`?

**Comment by dannypike** [comment]
@sean-mcmanus Thanks for your response.

That makes sense but, in my case, all of the ```std``` library headers are in the precompiled header for the project. I prefer not to have duplication, if I can avoid it - the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). 

Would you consider adding an option to the Intellisense that would allow me to give it name of a pre-compiled header? They're fairly ubiquitous now and, if it scanned that at the start, it might solve this problem.

**Comment by bobbrow** [comment]
> Would you consider adding an option to the Intellisense that would allow me to give it name of a pre-compiled header? They're fairly ubiquitous now and, if it scanned that at the start, it might solve this problem.

We do have such an option.  It is called "forcedInclude" in [c_cpp_properties.json](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference)

**Comment by dannypike** [comment]
@bobbrow . Thank you, that's perfect!

I missed that when I scanned the docs; I think that I may need to [drive to the nearest castle](https://www.theguardian.com/politics/video/2020/may/25/dominic-cummings-says-he-drove-to-barnard-castle-to-test-his-eyesight-video), tomorrow.
