### ISSUE TITLE
PROTO_WRITE not defined with g++ 10.1

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5829]
@sean-mcmanus 

```
-------- Diagnostics - 7/23/2020, 3:45:01 PM
Version: 0.29.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/usr/include/SDL2"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/g++",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "cppStandard": "c++17",
    "browse": {
        "path": [
            "/usr/include/SDL2",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/******/repos/cpp/HandmadeHero/handmade/code/sdl_handmade.cpp ]:
    /home/******/repos/cpp/HandmadeHero/handmade/code/sdl_handmade.cpp
    /home/******/repos/cpp/HandmadeHero/handmade/code/handmade.h
Translation Unit Configurations:
[ /home/******/repos/cpp/HandmadeHero/handmade/code/sdl_handmade.cpp ]:
    Process ID: 374398
    Memory Usage: 86 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/include/SDL2
        /usr/include/c++/10.1.0
        /usr/include/c++/10.1.0/x86_64-pc-linux-gnu
        /usr/include/c++/10.1.0/backward
        /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include
        /usr/local/include
        /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include-fixed
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100100
Total Memory Usage: 86 MB
```

---

I'm looking again at the squiggles. And I think it's primarily macros that IntelliSense is having an issue with. And oddly, upon hovering over the macros it'll pop out the definition (...expands to: ...) but then beneath the definition it'll have "identifier "PROT_WRITE" is undefined" (for example, from the mmap() function). Does that make sense?

Also, that Diagnostics spat out a slightly different configuration than what my c_cpp_properties.json has...which is:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${default}",
                "/usr/include/SDL2"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}

```

_Originally posted by @captainzonks in https://github.com/microsoft/vscode-cpptools/issues/5791#issuecomment-663249417_

**Comment by sean-mcmanus** [comment]
That is odd. I don't repro the issue with gcc 10.0 (might be specific to 10.1?). I see PROTO_WRITE defined at /usr/include/x86_64-linux-gnu/bits/mman-linux.h . Does Go to Defintion return any results for that?

Most likely IntelliSenese thinks the definition is in an inactive region due to some particular defines.

**Comment by captainzonks** [comment]
@sean-mcmanus 

Go to Definition works just fine. It knows where everything is. That's what is weird. Even my own defined Macros in another header also get squiggles (but it knows where to find them).

**Comment by sean-mcmanus** [comment]
I added the /usr/include/SDL2, but the issue still didn't repro.

After the Go to Defintion, do you see the definition as being inactive?

@Colengms @michelleangela Are any of you able to repro this?

I guess it could be a gcc 10.1 specific issue. Looks like gcc 10.2 fixes a bunch of bugs. Is there an easy way to get the gcc 10.1 binaries? I got the gcc 10.1 source, but I haven't gotten it to build yet.

**Comment by captainzonks** [comment]
@sean-mcmanus 
No, no inactive. "mman-linux.h" opens and those defines aren't wrapped in anything that would make them inactive.

Another example, the same issue is with "_rdtsc()" define for "__rdtsc()" in ia32intrin.h. It goes to the definition just fine too and that's not wrapped either.
