### ISSUE TITLE
IntelliSense showing error with constexpr array of size 65536

### ISSUE THREAD

**Issue by MichaelKim** [microsoft/vscode-cpptools#5833]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 19041
- VS Code Version: 1.47.2
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- The workspace is a folder containing a single file with the example below.

**Steps to reproduce**

1. Minimal example:

```c++
#include <array>

constexpr auto slides = std::array<int, 65536>{};
constexpr auto slides2 = std::array<int, 65535>{};
constexpr std::array<int, 65536> slides3{};
```

2. Intellisense shows the following error:
> expression must have a constant value -- cannot evaluate value of incomplete "std::array<int, 65536Ui64>" [3, 25]

I also get the same error in Visual Studio 2019, so it may be an issue with IntelliSense rather than the extension.

**Expected behavior**

There should be no error on line 3. I've tested with godbolt and the code compiles on MSVC 19.24, gcc 10.2, and clang 10.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 2020-07-24, 6:23:18 p.m.
Version: 0.29.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe",
    "cStandard": "c11",
    "intelliSenseMode": "msvc-x64",
    "compilerArgs": [],
    "cppStandard": "c++20",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Michael\Documents\test.cpp ]:
    C:\USERS\MICHAEL\DOCUMENTS\TEST.CPP
Translation Unit Configurations:
[ C:\Users\Michael\Documents\test.cpp ]:
    Process ID: 7852
    Memory Usage: 84 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.26.28801\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.26.28801\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++latest
    IntelliSense Mode: msvc-x64
Total Memory Usage: 84 MB
```
</details>

**Screenshots**

VSCode:
![image](https://user-images.githubusercontent.com/8509052/88440078-dea2d780-cdda-11ea-843f-d00c8a84150e.png)

VS:
![image](https://user-images.githubusercontent.com/8509052/88440547-49a0de00-cddc-11ea-851f-3535454a4cb1.png)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug on VS at https://developercommunity.visualstudio.com/content/problem/1127113/c-intellisense-gives-the-error-expression-must-hav.html .

**Comment by Colengms** [comment]
It looks like we picked up a fix for this.  I can no longer repro as of 1.2.0.  Closing as fixed.
