### ISSUE TITLE
Default cStandard is incorrectly c11 instead of gnu18 when the default compiler is gcc

### ISSUE THREAD

**Issue by minecraft2048** [microsoft/vscode-cpptools#5834]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.04 LTS
- VS Code Version:Version: 1.46.1
- C/C++ Extension Version: v0.29.0
- `CRTSCTS` from `termios.h` is squiggled with `identifier "CRTSCTS" is undefined`  but it can compile on gcc without any problems

**Steps to reproduce**

1. Enter this source file:
```
#include <stdio.h>
#include <stdlib.h>
#include <termios.h>

struct termios tty;
int main(){
    tty.c_cflag &= ~CRTSCTS;
    printf("hello");
}

```
2. Try compiling the code with `gcc -o test2 test2.c` and observe that the code compiles and run just fine
3. `CRTSCTS` is squiggled with `identifier "CRTSCTS" is undefined` but that code can compile in gcc just fine

**Expected behavior**

`CRTSCTS` is not squiggled

<details>
  <summary><strong>Logs</strong></summary>

Log Diagnostics: https://gist.github.com/minecraft2048/764f72423659df3c1c33c8b21c4136d0
Language server log: https://gist.github.com/minecraft2048/70006e0791459f875d40dc47a1876a6e

</details>

**Comment by sean-mcmanus** [comment]
Change your cStandard property to gnu11 to fix the issue
```
            "cStandard": "gnu11",
```
Let us know if you think there's a bug with the default cStandard not being set correctly (I think it should be gnu11 by default if we detect a gcc compiler by default).

**Comment by sean-mcmanus** [comment]
Yeah, I just reproed a bug where cStandard is being set to c11 by default instead of gnu11 (cppStandard is correctly gnu++14).

**Comment by sean-mcmanus** [comment]
The bug repros when the compiler reports `__STDC_VERSION__` 201710L. Should be trivial to fix. The default of gnu18 should be used (we were only handling the case where the compiler reported a 2018 version).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders .
