### ISSUE TITLE
Bugs: Intellisense autocomplete fails in Tensorflow project. However the feature works good in other project

### ISSUE THREAD

**Issue by ShenTonyM** [microsoft/vscode-cpptools#5835]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04 and Windows 10
- VS Code Version: 1.47.2
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): Python, Code Runner, Git History, Gitlens, Todo Tree
- Does this issue involve using SSH remote to run the extension on a remote machine?: Fails both local and remote SSH
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

In **Tensorflow** project, autocompletion only shows the suggestions for C++ keywords, such as "if, else, template".
![image](https://user-images.githubusercontent.com/18712278/88457226-50505380-ceb7-11ea-8ad5-3e750140d19f.png)

However, the intellisense to find the function definition works well.
![image](https://user-images.githubusercontent.com/18712278/88457412-b093c500-ceb8-11ea-840d-673ef0af29ee.png)

In other projects, such as oneDNN, the autocompletion works well.
![image](https://user-images.githubusercontent.com/18712278/88457237-69590480-ceb7-11ea-956f-0c89f33fbe7f.png)

**Steps to reproduce**

1. git clone https://github.com/tensorflow/tensorflow.git
2. open this folder
3. open the file tensorflow/core/kernels/mkl_concat_op.cc or any other cpp files
4. just try the autocompletion in the file.  There are no useful suggestions other than C++ keywords.

**Expected behavior**

Fix the bugs.

<details>
  <summary><strong>Logs</strong></summary>

c_cpp_properties.json
![image](https://user-images.githubusercontent.com/18712278/88457452-1b450080-ceb9-11ea-94b0-40528aa747e5.png)

```
Insert logs here.

```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I'm seeing `Quick info operation failed: FE: 'Compiler exited with error - No IL available'` in the logs.

How do I get mkldnn.hpp to resolve? I assume I have to build the 3rd party dependency somehow?

**Comment by ShenTonyM** [comment]
@sean-mcmanus 
Please git clone https://github.com/oneapi-src/oneDNN.git
And the we can include `include/mkldnn.h` 
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/mnt/f/Code/Vscode/oneDNN/include/"
            ],
            "defines": ["INTEL_MKL"],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
Okay, thanks, for the info. I'll try that out tomorrow.

**Comment by sean-mcmanus** [comment]
I'm still investigating this (I'm seeing includes not found with 0.30.0-insiders, but it's not showing me which ones).

**Comment by sean-mcmanus** [comment]
I was looking into a 0.30.0-insiders IntelliSense crash regression today and another issue and I'm OOF Friday...I'll try to look at this next week unless @Colengms or @michelleangela can investigate sooner.

**Comment by michelleangela** [comment]
@ShenTonyM 

Are there other third party dependencies to include? I also had to include https://github.com/abseil/abseil-cpp/tree/master/absl. But I am also getting `Quick info operation failed: FE: 'Compiler exited with error - No IL available` for the file "executor.cc".

Are there other requirements to setup Tensorflow? Does it build locally for you?

My c_cpp_properties.json in my repro is
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/home/blue/git2/oneDNN/include/**",
                "/home/blue/git2/abseil-cpp/**"
            ],
            "defines": ["INTEL_MKL"],
            "compilerPath": "/usr/bin/clang-9",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

**Comment by michelleangela** [comment]
@ShenTonyM 

Could you also provide logs from:


1. Log output from enabling the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

2. Log output from running the command `C/C++: Log Diagnostics`

**Comment by ShenTonyM** [comment]
@michelleangela 
Hi Michelle,
Here's the log from `C/C++: Log Diagnostics`

```
-------- Diagnostics - 8/13/2020, 10:15:16 AM
Version: 0.29.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**",
        "/home2/yunfeima/code/repo/oneDNN/include/**"
    ],
    "defines": [
        "INTEL_MKL",
        "ENABLE_MKL",
        "ENABLE_MKLDNN_V1"
    ],
    "compilerPath": "/home2/yunfeima/gcc-8.3.0/bin//gcc",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "/home2/yunfeima/code/repo/oneDNN/include/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.
```

I switch to another computer, you may find the absolute path different from my last reply. But the intellisense problem is the same.

**Comment by ShenTonyM** [comment]
I also find the `Quick info operation failed: FE: 'Compiler exited with error - No IL available`  in the `C\C++` log. But the message doesn't suggest which third party dependencies to include in vscode setting. 

Tensorflow is a very large project, and it is generally built with [bazel](https://bazel.build/), a tool like cmake. The third-party dependencies are listed in file [`tensorflow/workspace.bzl`.](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl) There are too many third-party repos, and I don't really want to manually include them all in the `.vscode/c_cpp_properties.json`.

**Comment by michelleangela** [comment]
@ShenTonyM 

The `Quick info operation failed: FE: 'Compiler exited with error - No IL available` error also repros on Windows. This seems to be an issue with having an incomplete list of includePaths input for the IntelliSense Engine. Similar to a compiler, IntelliSense will not have any context about what the required third party dependencies a project needs unless it is specified, other than it will detect that it cannot find some header file.

There are 3 ways to provide IntelliSense configuration to the IntelliSense Engine, so that the engine can "compile" and understand the context of a source code project:
1. Manually set the required configuration info in [c_cpp_properties.json](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference)

2. Use a configuration provider like [VS Code CMake Tools](https://github.com/microsoft/vscode-cmake-tools). For projects that is built with CMake, CMake Tools will send configuration info to the cpptools extension by setting the `configurationProvider` in c_cpp_properties.json
![image](https://user-images.githubusercontent.com/38734287/90939836-a4206080-e3c1-11ea-98ca-6ff6f6a0975c.png)

3. Use a compile_commands.json file to provide the configuration info by setting `compileCommands` in c_cpp_properties.json
![image](https://user-images.githubusercontent.com/38734287/90939890-cca85a80-e3c1-11ea-87e3-26bd2bbfc991.png)


I am not familiar with the [bazel ](https://bazel.build/) build tool. Is there a way for bazel to provide the required set of includePaths to the cpptools extension similar to generating compile_commands.json?

**Comment by ShenTonyM** [comment]
@michelleangela 
I find a [tool](https://github.com/grailbio/bazel-compilation-database) to generate `compile_commands.json` for bazel project. Then I can take solution 3 to enable the intellisense. 
This tool is not provided by bazel official, but it can be workaround. 
I will close this issue.  Thanks for your help.
