### ISSUE TITLE
ParameterHints within Doxygen comment - that uses colon after param

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#5836]
hi, c_cpp has support Doxygen comment.
thus, it would be great if  Parameter Hints support them.
<img width="681" alt="c++" src="https://user-images.githubusercontent.com/1876302/88469571-8c220200-cf25-11ea-86fc-2521813e28a7.png">

**Comment by michelleangela** [comment]
@heartacker 

The extension supports parameter hints. The name of the parameter is used as the key to find its corresponding comment from the Doxygen comment structure. It looks like from the screenshot, the name of the param in the comment has `:` and the actual parameter does not. The Doxygen parser will not be able to match `E4E2x:` with the actual parameter name `E4E2x`. Could you try removing the `:` from the name of the parameter comment and see if that displays the comment for the parameter hint?

Example of parameter hint:
```
// @brief this is brief comment
// @param GPIOx this is comment for parameter GPIOx
// @param E4E2x this is comment for parameter E4E2x
void myFunction(int GPIOx, int E4E2x)
{
}
```

![image](https://user-images.githubusercontent.com/38734287/88584577-b13a7180-d006-11ea-9649-5ef76d9522cc.png)

**Comment by heartacker** [comment]
https://github.com/doxygen/doxygen/issues/7928#issuecomment-667031139

The hint works within the standard format.
BTW, doxygen tolerates colons.

**Comment by michelleangela** [comment]
Thanks for confirming that the colon after the parameter is supported by Doxygen. I'll mark this as a bug to fix.

**Comment by heartacker** [comment]
> Thanks for confirming that the colon after the parameter is supported by Doxygen. I'll mark this as a bug to fix.

if colon follow parameter and also have space, that is accept. like `@para arg: args for method`
but using colon instead of space is wrong format, no need to be Compatible .`@para arg:args for method`, beacuse doxygen will identify `arg:args` as the para name.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders3 .
