### ISSUE TITLE
c_cpp_peroperty.json error when i change include path

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#5837]
Every time I **change/add/remove** the `include` path, It gets an error and only thing is to restart vscode

![image](https://user-images.githubusercontent.com/1876302/88546015-59bff400-d04e-11ea-8131-1144b8d9248b.png)

**Comment by heartacker** [comment]
{
	"resource": "/f:/ATCProjectFiles/MCU/NXP/S32K146_Study/.vscode/c_cpp_properties.json",
	"owner": "languageErrors25",
	"severity": 8,
	"message": "Parse error on line 74:\n...**\"                \"C:\\\\Keil_v5\\\\ARM\\\\P...\n----------------------^\nExpecting '}', ':', ',', ']', got 'STRING'",
	"startLineNumber": 74,
	"startColumn": 17,
	"endLineNumber": 74,
	"endColumn": 86
}

**Comment by sean-mcmanus** [comment]
Could you provide the text of c_cpp_properties.json? Or just the text of the includePath section. Also, what edits are you making?

**Comment by heartacker** [comment]
> Could you provide the text of c_cpp_properties.json? Or just the text of the includePath section. Also, what edits are you making?

there is the condition
![cpp_json](https://user-images.githubusercontent.com/1876302/88746143-65123d00-d17e-11ea-94ed-477f28b9d7c4.gif)

**Comment by sean-mcmanus** [comment]
Are you inserting a comma or some other character? It could be some character encoding issue. If you could provide the actual characters that are causing the failure I can see what is causing it.

**Comment by sean-mcmanus** [comment]
That error is not coming from our extension or from VS Code -- it must be from some other extension you have installed. I don't see a source for the error in the Problem window.

**Comment by heartacker** [comment]
> Are you inserting a comma or some other character? It could be some character encoding issue. If you could provide the actual characters that are causing the failure I can see what is causing it.



I'm not sure it's a coding problem.But when I reload the windows，There is no problem with parsing. I'll paste the code later.

**Comment by sean-mcmanus** [comment]
This is what is normally expected from VS Code when there's some syntax error:
![image](https://user-images.githubusercontent.com/19859882/88981467-e0591900-d27a-11ea-882a-a6cb720a5b30.png)
It comes from VS Code's json schema.

**Comment by heartacker** [comment]
> That error is not coming from our extension or from VS Code -- it must be from some other extension you have installed. I don't see a source for the error in the Problem window.


ok.By the way, Is there any easy way to determine which ext cause this problem?3q

**Comment by sean-mcmanus** [comment]
Extensions that post error/warnings are supposed to provide the source (e.g. json in my screenshot), but whoever is posting that diagnostic is not posting a source, so I don't know a way to detect the source other than to disable/enable trial and error.

**Comment by heartacker** [comment]
> Extensions that post error/warnings are supposed to provide the source (e.g. json in my screenshot), but whoever is posting that diagnostic is not posting a source, so I don't know a way to detect the source other than to disable/enable trial and error.

Try one by one, finally get it
