### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by djose1164** [microsoft/vscode-cpptools#5840]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.29.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.47.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\djose\ms-vscode.cpptools-unresponsive.cpuprofile.tx
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cpptools/files/4984175/ms-vscode.cpptools-unresponsive.cpuprofile.txt)
t`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by WardenGnaw** [comment]
Please attach `C:\Users\djose\ms-vscode.cpptools-unresponsive.cpuprofile.txt`

**Comment by djose1164** [comment]
> Please attach `C:\Users\djose\ms-vscode.cpptools-unresponsive.cpuprofile.txt`
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cpptools/files/4985865/ms-vscode.cpptools-unresponsive.cpuprofile.txt)

**Comment by sean-mcmanus** [comment]
Looks like some issue with the collectSettings code taking too long. Do you have a repro? Do you have a lot of settings set? I don't seem to be able to detect a performance issue when profiling.

**Comment by djose1164** [comment]
> Looks like some issue with the collectSettings code taking too long. Do you have a repro? Do you have a lot of settings set? I don't seem to be able to detect a performance issue when profiling.

Yes, I have repo and a lot of settings set. Perhaps that's the cause of the issue?

**Comment by bobbrow** [comment]
How many settings?  Can you share them?  Otherwise, I don't think we have the information we need to resolve this issue.  Thanks!

**Comment by djose1164** [comment]
> How many settings? Can you share them? Otherwise, I don't think we have the information we need to resolve this issue. Thanks!

Hmmm, 10-15 maybe. I did a clean install of vscode and it's ok. Thanks!

**Comment by bobbrow** [comment]
Glad to hear it.  10-15 settings is not very many.  I was thinking you were going to say 100 or so. 😄
