### ISSUE TITLE
c_cpp_properties.json is generated with intelliSenseMode clang-x64 instead of gcc-x64 with gcc

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5842]
The default intelliSenseMode uses gcc-x64 when gcc is chosen as the default compiler, but when the c_cpp_properties.json is generated it replaces that with clang-x64.

**Comment by michelleangela** [comment]
@sean-mcmanus  the issue  https://github.com/microsoft/vscode-cpptools/issues/5352 was created because of this potential mismatched with IntelliSenseMode and compiler.

**Comment by sean-mcmanus** [comment]
Oh, so you're saying this is a duplicate?

**Comment by michelleangela** [comment]
Yes, closing as a duplicate.
