### ISSUE TITLE
Pointer modifier recognized as different token

### ISSUE THREAD

**Issue by a5066987** [microsoft/vscode-cpptools#5844]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10 10.0.19042.421
- VS Code Version: 1.48.0 Insider
- C/C++ Extension Version: 0.29.0
- Does this issue involve using SSH remote to run the extension on a remote machine?:  **No**

Why the first "*" is recognized as `storage.modifier.pointer.cpp` but the second one is `keyword.operator.cpp`? Is this a bug or a feature? I think both of them should be a modifier?

![image](https://user-images.githubusercontent.com/13390857/88616093-12cf0000-d048-11ea-99f1-138838238cfc.png)
![image](https://user-images.githubusercontent.com/13390857/88616145-34c88280-d048-11ea-9da5-9a946d60c5eb.png)

**Comment by sean-mcmanus** [comment]
The issue is inherited from VS Code itself, which is then inherited from the Better C++ Syntax extension, which I've filed an issue on at https://github.com/jeff-hykin/cpp-textmate-grammar/issues/493
