### ISSUE TITLE
Parameter Name Hints shown inline

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#5845]
Now that we have doxygen comment supported to help code readability, it would be also useful to have a CLion-like name hint to be shown inline all the time (just like named parameters)

So that instead of this
![image](https://user-images.githubusercontent.com/53231928/88621427-a517e800-d0ca-11ea-974e-5578688cb26b.png)

we get this instead

![image](https://user-images.githubusercontent.com/53231928/88621418-97626280-d0ca-11ea-951b-1e955589245c.png)

**Comment by sean-mcmanus** [comment]
I've filed a feature request on VS at https://developercommunity.visualstudio.com/idea/1130438/c-intellisense-inline-parameter-name-hints.html , although it's possible we would still need to do some more work to setup VS Code specific code lens providers if they decide to implement the feature.

**Comment by Diegorro98** [comment]
The Inlay Hint provider API for VS Code has been released. Any updates on this?

**Comment by sean-mcmanus** [comment]
We haven't looked into it yet. Seems like we'd have to query our database for all function symbol parameter names for the entire document, which we don't currently only do as part of signature help.

**Comment by sean-mcmanus** [comment]
Parameter hints (aka inlay hints) are added with 1.11.0 (pre-release). The relevant settings to change are
```json
    "C_Cpp.inlayHints.autoDeclarationTypes.enabled": true,
    "C_Cpp.inlayHints.parameterNames.enabled": true,
    "C_Cpp.inlayHints.referenceOperator.enabled": true
```
assuming you want all those enabled or a subset.

Another setting we added is
```json
"C_Cpp.inlayHints.parameterNames.suppressWhenArgumentContainsName": true
```

Our next 1.11.1 release may change the defaults like
```json
    "[cpp]": {
        "editor.inlayHints.fontSize": 11
    },
    "[c]": {
        "editor.inlayHints.fontSize": 11
    },
```
to match VS and to avoid the confusing the inlay text too much with existing text, particular for the "auto" case.

One thing that may not be obvious is that the inlay hint for "auto" is intended to replace all the potential existing type modifiers and it is not just adding additional info that the auto hides, so any potentially confusing or redundant existing const *& modifier text is intended to be ignored in favor of the more complete inlay hint type info.
