### ISSUE TITLE
Adding custom language tokens into the cpptools

### ISSUE THREAD

**Issue by hyh19962008** [microsoft/vscode-cpptools#5847]
Yah Hi, we have a proprietary language which is based on c++. It's compatible with the c++ grammar and tokens while adding some other tokens and grammar. So, we wanted to add those tokens into the cpptools extension so that intellisense can work functionally but not printing red wavy line and emitting syntax error message on those tokens. I wonder if you guys is able to tell me where to start ? Is that I all need to do is to modify the code from this repository or do I need to change the language-server or anything else? 

PS. I have go over most of the docs and api docs on the vscode site and have done the syntax highlighting.
PSS. The bin file "/bin/cpptools-srv", where can i get the source code of it ? Because it doesn't looks like a ts compiled file.

**Comment by bobbrow** [comment]
I'm sorry, there's not much we can do to help here.  Our parser is not open source, so there is no way for you to implement this feature.

If you are just adding intrinsics, these can be handled by adding entries to the `"defines"` array in `c_cpp_properties.json` to make them look like standard C++ types, or make them invisible to our parser.  (e.g. "myint_t=int32_t", "myattribute=")

**Comment by sean-mcmanus** [comment]
@hyh19962008 You could also try wrapping the custom tokens used with 
```
#ifndef __INTELLISENSE__
// non-standard code
#endif
```
