### ISSUE TITLE
Debugger doesn't show correct information for array initialized with runtime length

### ISSUE THREAD

**Issue by nc-hyw** [microsoft/vscode-cpptools#585]
I ran into a problem that if I declare an array with know length such as
`int array[5];`
the debug works perfectly, however, if I initialize an array with length only know at run time for example
`int n = someinput;
int array[n]`
the debug doesn't show correct information for this array, it shows length of 0, and can't inspect the element. Please see pic below
![qq 20170323113416](https://cloud.githubusercontent.com/assets/13243206/24226785/abdadc92-0fbc-11e7-978b-3f95cfaf91c4.png)
I'm absolutely, completely, definitely sure image[] and input[] by the time is already initialized correctly.

**Comment by pieandcakes** [comment]
@YXuewei What OS are you running on and if you are using `gdb`, do you have gdb's `pretty-printing` enabled?

**Comment by nc-hyw** [comment]
@pieandcakes  I'm using windows, and I do turned pretty-printing on. I write a sample code to demonstrate what it looks like.
![25ebd9eea82c4c5a1f31154ff5ddc866](https://cloud.githubusercontent.com/assets/13243206/24488117/73c73a4a-1560-11e7-8e43-20f2a6d8e743.jpg)
![511d170097f556b5593ece93d9232dd7](https://cloud.githubusercontent.com/assets/13243206/24488120/79a9aa24-1560-11e7-83e1-9bec6aaafee2.jpg)
The First one is my lauch.jason setting. I use gdb-pyrhon27.exe so that I can use pretty-pritting. And the second pic is what it is like when I inspect values. Form debugger console you can see that I use command -exec -enable-pretty-printing to enable pretty-printing and it shows it have been done.

**Comment by pieandcakes** [comment]
@YXuewei The visualization of the variables through pretty printing is provided by gdb's community. If you want, you can search and see if there is another option to help visualize the array. We also support .natvis visualization using a .natvis visualizer file but you would also need to create one from scratch. It seems like gdb is returning different information for each case, which we have no control over.

**Comment by nc-hyw** [comment]
@pieandcakes Is that possible to let VSCode to use GDB in WSL? If it is what we going to have in Windows Creator update I will save me sometime for getting a *nix or some money on macOS.

**Comment by nc-hyw** [comment]
@pieandcakes It is the same if I use LLDB, see screen shoots below. I tried this with a MacBook Pro.
<img width="1440" alt="screen shot 2017-03-31 at 10 19 46 pm" src="https://cloud.githubusercontent.com/assets/13243206/24548339/59905dcc-1660-11e7-9e50-d682b0f5a941.png">

**Comment by pieandcakes** [comment]
@YXuewei We also enabled python formatting for lldb recently. I don't know if the behavior is the same. You can enable `"logging": { "engineLogging": true }` and see what we send gdb/lldb and what we get back. I suspect we are getting different data back for each case.

**Comment by nc-hyw** [comment]
@pieandcakes No it doesn't work, it didn't bring any difference without the command when inspecting. It should be a way in LLDB to enable something like pretty printing in GDB. There is no reason that gdb can do it but LLDB can not. Otherwise how does Xcode be able to view object contains or dynamic array?

**Comment by pieandcakes** [comment]
@YXuewei Unfortunately LLDB the pretty printing is compiled in and not able to be disabled. I don't know if Xcode provides additional pretty printing configurations but you can look at the documentation here: http://lldb.llvm.org/varformats.html

The ones included in our package are located at:
~/.vscode/extensions/ms-vscode.cpptools-0.10.5/debugAdapters\lldb\lib\python2.7\site-packages\lldb\formatters

**Comment by WardenGnaw** [comment]
Closing issue with no recent updates. 

If this issue is still occuring, please open a new issue.
