### ISSUE TITLE
CppVsDbg debugger hangs when trying to interactively debug user input 

### ISSUE THREAD

**Issue by GiovanniDicanio** [microsoft/vscode-cpptools#5851]
Type: Debugger
**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): None
- When trying to debug C/C++ programs that read user input (e.g. using `scanf`), the debugger hangs when stepping over the input instruction.

**To Reproduce**

Try to debug the following simple C code.

Insert a breakpoint at the `scanf` line, and select `Run | Start Debugging`.

The debugger hangs after you enter a number in the integrated Debug Console.

`Hello.c` sample:
```
#include <stdio.h>

int main() {
    setvbuf(stdout, NULL, _IONBF, 0);
    
    printf("Enter an integer number: \n ");

    int n;
    scanf("%d", &n);

    printf("You entered the number %d \n", n);
    return 0;
}
```

`launch.json` configuration:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "cl.exe - Compila ed esegui il debug del file attivo",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "preLaunchTask": "C/C++: cl.exe build active file"
        }
    ]
}
```

**Workaround Note**

Things work if I change the `externalConsole` property in the `launch.json` file to `true`:

`"externalConsole": true,`

But, in this way, we are _not_ using the _integrated_ debug console anymore.

**Comment by WardenGnaw** [comment]
We do not have support for the intergrated terminal for `cppvsdbg`. 

We are tracking that here https://github.com/microsoft/vscode-cpptools/issues/5386
