### ISSUE TITLE
Cannot find arm64 bit version

### ISSUE THREAD

**Issue by Quaziz-creator** [microsoft/vscode-cpptools#5852]
Type: General

**Describe the issue**
On https://github.com/microsoft/vscode-cpptools im promised that a 64bit version exist on https://github.com/Microsoft/vscode-cpptools/releases but i can't at all find it.

**Screenshots**
![image](https://user-images.githubusercontent.com/56341199/88798008-7c642100-d1a4-11ea-9bb0-6749d7b1e8ee.png)
![image](https://user-images.githubusercontent.com/56341199/88798097-a4538480-d1a4-11ea-89ee-e0adfb121936.png)

**Comment by Quaziz-creator** [comment]
Realised a bit too late that it did not state arm64 but only 64 bit versions of linux

**Comment by bobbrow** [comment]
Correct.  We are working on ARM64 support now: #2506.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.0.0
