### ISSUE TITLE
Make it possible to compile and debug C/C++ code even when VS Code is launched using its icon

### ISSUE THREAD

**Issue by GiovanniDicanio** [microsoft/vscode-cpptools#5853]
OS: Windows 10
VS Code Version: 1.47.3 
Microsoft C/C++ Extension Version: 0.29.0

When launching VS Code from its icon, I get errors when trying to compile and debug C/C++ code.
It seems VS Code must be launched from the Visual Studio Developer Command Prompt to properly build and debug C/++ code.

Please make it possible to simply launch VS Code from its icon, and have it work properly.

**Comment by sean-mcmanus** [comment]
We're tracking this request with a previous request at https://github.com/microsoft/vscode-cpptools/issues/4742 .

**Comment by sean-mcmanus** [comment]
@GiovanniDicanio This was added in https://github.com/microsoft/vscode-cpptools/releases/tag/v1.29.2
