### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by BrianSipple** [microsoft/vscode-cpptools#586]
Right now, the Marketplace page for this project contains a wonderful Changelog:

<img width="917" alt="screen shot 2017-03-22 at 7 12 33 pm" src="https://cloud.githubusercontent.com/assets/5483853/24228826/c90d5ada-0f33-11e7-888f-d357b1b87cd7.png">

However, I think it would be even more helpful to start maintaining that here as a CHANGELOG.md file, as per [the extension recommendations after 1.7](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_7.md#changelogs). That way, it can also show up for anyone viewing the project details page within their editor:

<img width="631" alt="screen shot 2017-03-22 at 7 05 36 pm" src="https://cloud.githubusercontent.com/assets/5483853/24228930/3c5cdb64-0f34-11e7-8dc0-2fdd481518bf.png">

**Comment by sean-mcmanus** [comment]
Yes, we are aware of this. It has been on our TODO list.

**Comment by bobbrow** [comment]
This issue has been fixed with v0.11.0.
