### ISSUE TITLE
disable some debug console messages

### ISSUE THREAD

**Issue by maidamai0** [microsoft/vscode-cpptools#5861]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 2004
- VS Code Version:1.47.3
- C/C++ Extension Version: 0.29.0
- A clear and concise description of what the bug is.

How do disable messages with the yellow color such as the one about `pdb` and 'thread'
I find these messages very annoying and mixed with my console output sometimes.
```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\msvcp140d.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\vcruntime140d.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\vcruntime140_1d.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\ucrtbased.dll'. Cannot find or open the PDB file.
The thread 21764 has exited with code 0 (0x0).
...
Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
The thread 19156 has exited with code 0 (0x0).
The thread 15344 has exited with code 0 (0x0).
The program '[2112] json_message.exe' has exited with code 0 (0x0).
```

**To Reproduce**
* Code sample
```cpp
#include <iostream>
int main() {
std::cout << "hello world!" << std::endl;
}
```
* Steps to reproduce the behavior:
compile and run in vs code.

**Comment by WardenGnaw** [comment]
You can disable these outputs by adding a `logging` block into your `launch.json` and disable `moduleLoad` and `threadExit`. See the [package.json](https://github.com/microsoft/vscode-cpptools/blob/236ea2af7a64402200822149889b85e1f6dfc996/Extension/package.json#L1752) for more information.

**Comment by maidamai0** [comment]
Thanks! No module loaded logs anymore.
But I still get thread and program exit log with `threadExit` and `processExit`  disabled.
```json
{
    "name": "(Windows) Launch",
    "type": "cppvsdbg",
    "request": "launch",
    "program": "${command:cmake.launchTargetPath}",
    "args": [],
    "stopAtEntry": false,
    "cwd": "${workspaceFolder}",
    "environment": [],
    "externalConsole": false,
    "logging": {
        "moduleLoad": false,
        "threadExit": false,
        "processExit": false
    }
}
```
Gives:
```console
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
The thread 23004 has exited with code 0 (0x0).
... program output
The thread 12584 has exited with code 0 (0x0).
... program output
The thread 8184 has exited with code 0 (0x0).
... program output
The program '[18604] json_message.exe' has exited with code 0 (0x0).
```

**Comment by WardenGnaw** [comment]
The thread and process exit messages logging is available in v1.1.0.

This should be in the vsdbg version 16.4.202272. You can find this at `%USERPROFILE%\.vscode\extensions\ms-vscode.cpptools-1.1.1\debugAdapters\vsdbg\bin\vsdbg.exe`

**Comment by Phyyl** [comment]
This works really well but there's still this message at the top:

```-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

Is there a setting I can turn on to disable printing this?

**Comment by anirugu** [comment]
@WardenGnaw 

I am able to hide moduleLoad message and others but I am still seeing the first 3 lines. Is there a way to hide it?

![image](https://user-images.githubusercontent.com/35772421/192933767-9cf1dde1-4da1-49a2-a441-a3c3e887f9aa.png)

**Comment by bobbrow** [comment]
@anirugu, @Phyyl, no there is no setting to disable that message.

**Comment by anirugu** [comment]
[.vscode.zip](https://github.com/microsoft/vscode-cpptools/files/9680808/default.vscode.zip)

@bobbrow  Thanks for the reply, I use the "console": "integratedTerminal" in launch.json, and using that I am able to achieve it. Uploading the whole .vscode folder.
