### ISSUE TITLE
Compatibility issues with arm64 on Ubuntu

### ISSUE THREAD

**Issue by ApurvZ** [microsoft/vscode-cpptools#5862]
![Screenshot_20200730-100049_VNC Viewer](https://user-images.githubusercontent.com/43213555/88903434-55275580-d271-11ea-8501-ae3ed07c6404.jpg)
I am running Ubuntu19 with desktop environment on Android, but that shouldn't be an issue, as arm64 version of vs code is running well. A lot of people were asking the same earlier, to port it to arm64 for raspberry pie. Hope the issue gets fixed!

**Comment by sean-mcmanus** [comment]
If you click on the License link in the top right of our extension page (https://marketplace.visualstudio.com/items/ms-vscode.cpptools/license), it says:
`
INSTALLATION AND USE RIGHTS. You may only use the C/C++ Extension for Visual Studio Code with Visual Studio Code, Visual Studio or Xamarin Studio software to help you develop and test your applications.
`
That excludes headmelted running on arm64, and our debugger component will explicitly check this and disable itself in that case (our language server binaries don't currently do this, but that could change later). You could file a new request for us to change our license if you want (or we could convert this issue to that).

Our future support for arm64 will be via using VS Code and the Remote Development extensions, which we are tracking at https://github.com/microsoft/vscode-cpptools/issues/2506 .
