### ISSUE TITLE
Basic CPP definitions missing when "limitSymbolsToIncludedHeaders": false

### ISSUE THREAD

**Issue by nilanjan** [microsoft/vscode-cpptools#587]
How can I delete old browser info and re-generate new browser info?

Previously it was set to true.
"limitSymbolsToIncludedHeaders": true

**Comment by sean-mcmanus** [comment]
Changing the limitSymbolsToIncludedHeaders setting should cause the headers to be parsed and deleting your browse info shouldn't be required (unless we have a bug?), although it may take a while (when the bottom right is no longer red).

The easiest way to regenerate the browse database is to change the databaseFilename property. Or you can locate the .browse.vc.db in your workspaceStorage folder, which is OS-specific, e.g. \<user\>/AppData/Roaming/Code/User/workspaceStorage for Windows. But the deletion should only be needed when you want items removed from the database.

If you #include cpp headers and the definitions are not available when limitSymbolsToIncludedHeaders is true, then that is a bug -- there is one known bug where we end up choosing the wrong header to parse, which could cause the definition to not appear (we have a work item to fix that in a future update).

**Comment by nilanjan** [comment]
For some reason in OS X clang headers and auto-complete do not work properly. I was trying to fix it by providing more info to the browser by limitSymbolsToIncludedHeaders=false. I hope the include file search is recursive. 

```
    "configurations": [
        {
            "name": "OSX",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "/usr/local/Cellar/boost/1.60.0_2",
"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/x.0.0/include",
"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/<OS X Version>/usr/include",
"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/<OS X Version>/System/Library/Frameworks"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "databaseFilename": ""
            }
        },
```
Still I when I type the name of the variable autocomplete does not show the variable. In fact the F12 says no definition found.
```
  // Controls auto completion for C/C++ code.  "Default" uses an experimental recursive directory tag parser (as of right now).  "Disabled" uses the word based completion provided by Visual Studio Code.
  "C_Cpp.autocomplete": "Disabled",
  // Enable completion
  "clang.completion.enable": true,
  // Compiler options for C (e.g. ["-std=c99"])
  "clang.cflags": [
    "-std=c99",
    "-I./",
    "-I/usr/include",
    "-I/usr/local/include",
    "-I/usr/local/Cellar/boost/1.60.0_2",
    "-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/x.0.0/include",
    "-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
    "-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
    "-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
  ],
  // Compiler options for C++ (e.g. ["-std=c++11"])
  "clang.cxxflags": [
    "-std=c++11",
    "-I./",
    "-I/usr/include",
    "-I/usr/local/include",
    "-I/usr/local/Cellar/boost/1.60.0_2",
    "-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/x.0.0/include",
    "-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
    "-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
    "-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
  ],
  // The delay after which diagnostic starts (in millisecond)
  "clang.diagnostic.delay": 500,
  // Tolerable size of the clang output for completion
  "clang.completion.maxBuffer": 8388608000,
```

**Comment by Inori** [comment]
@sean-mcmanus How about the bug you mentioned that cpptools choose the wrong header to parse now? I think I got in the same issues, my .browse.VC.db is about 400kb when I set limitSymbolsToIncludedHeaders to true. Only when I disable it I can get the right symbols.
By the way, what's the issues number?

Update:
I think I'v found out why this happen:
I'm using FreeType, and as the official tutorial suggest, I write `#include FT_FREETYPE_H` in my c file,
and  this cause `Tag parsing failed`.
When I comment this line, everything goes right.
Hope for a fix:)

**Comment by sean-mcmanus** [comment]
@Inori The `#include FT_FREETYPE_H` is a different issue -- the Tag Parser doesn't resolve macros automatically, but adding `#define FT_FREETYPE_H <definition>` to the cpp.hint file in your extension directory should be a workaround that fixes it (cpp.hint is also used by Visual Studio, which has info at https://msdn.microsoft.com/en-us/library/dd997977.aspx ). We eventually want to make this easier to configure (since the file gets re-written after an upgrade). Also, the bug in which the wrong header can be parsed when limitSymbolsToIncludedHeaders is true still exists (i.e. if another file with the same name is chosen instead).

**Comment by Inori** [comment]
@sean-mcmanus Thanks for your reply, that saves my problem partially, since FreeType have many include declared as such. But thank you, anyway. :)

**Comment by bobbrow** [comment]
@nilanjan, is this still a problem for you?  You should be able to shrink down the `c_cpp_properties.json` file if you have the most recent version of the extension installed and use the `compilerPath` property instead.
```
        {
            "name": "OSX",
            "includePath": [
                "/usr/local/Cellar/boost/1.60.0_2"
            ],
            "compilerPath": "/usr/bin/clang"
        },
```

Please reopen if you are still having issues.
