### ISSUE TITLE
Reliability issues with some of the automated tests

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#5870]
- [x] Add some mechanism to deal with tests that have known random failures, such as having alternative baselines, or a retry count for tests that have known random failures. But it would be good to not completely bury the failures (which could be real bugs).
- [x] recursive_includes test has a random failure on Linux (potentially a real race condition bug).
- [x] fix custom configuration test failure.
- [x] fix squiggles test failure.
- [x] fix intellisense_clients random failure on shutdown
- [ ] multiroot/SymbolSearch randomly gives no results.
- [ ] multroot/FindAllReferences randomly misses results.
- [ ] multiroot/SetFolderSettings randomly gets stuck.
- [x] multiple tests/OpenFile: IntelliSense process randomly shuts down.
- [ ] database_clearing test random gets stuck on the Linux/Mac build machines -- doesn't appear to be worth investigating because it doesn't repro on my local machines.

...some of these may have gotten fixed, I haven't checked recently.

**Comment by bobbrow** [comment]
Ideally, this would not be needed, but we could update the affected test(s) so that they are more stable.

**Comment by sean-mcmanus** [comment]
UPDATE: The multiroot test on Windows is still failing and the fallback/timeout-retry mechanism has some failure I need to investigate.

**Comment by sean-mcmanus** [comment]
This issue somewhat related to https://github.com/microsoft/vscode-cpptools/issues/6307 (debug build tests).
