### ISSUE TITLE
Refactor "providers" out of client.ts

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#5871]
Move Provider classes from `client.ts` into their own source files.

**Comment by devabhishekpal** [comment]
I have made a pull request for the refactored code. Kindly check the changes and recommend any further changes or instructions if any.

@bobbrow @michelleangela @Colengms

**Comment by spacemonkd** [comment]
Can someone check the code for the PR🥺 @bobbrow @Colengms

**Comment by Colengms** [comment]
Closing this now, since it's a code maintenance issue, not something that needs to ship.
