### ISSUE TITLE
c_cpp_properties document improvements

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#5875]
It is better to add some ref url to the config UI for new coming. it's hard to Find the document of  c/c++ each time we text a config.

![image](https://user-images.githubusercontent.com/1876302/88992133-22cf3400-d315-11ea-884b-503aa08a74c2.png)

BTW, After searching for a long time, I could not find any documents related to the setting of environment variables，although supported. 
For many beginners, they don't even know that those Settings exist

**Comment by sean-mcmanus** [comment]
We have docs at https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference . Is that the URL you'd like added to the UI?

**Comment by heartacker** [comment]
> We have docs at https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference . Is that the URL you'd like added to the UI?

yes.thanks

**Comment by spacemonkd** [comment]
I have opened a pull request with the necessary changes. Kindly review it.

**Comment by spacemonkd** [comment]
Could you kindly review it if time permits? @sean-mcmanus @bobbrow

**Comment by sean-mcmanus** [comment]
@devabhishekpal Yeah, thanks. This can probably get into 0.30.0-insiders4.

**Comment by spacemonkd** [comment]
Can we close the PR for this issue? 😅 @sean-mcmanus

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4. Thanks to @devabhishekpal
