### ISSUE TITLE
Debugger does not display values of C++ STL Containers within an object

### ISSUE THREAD

**Issue by bcaddy** [microsoft/vscode-cpptools#5879]
Type: Debugger

VSCode Version: 1.47.3
OS Version: macOS 10.15.6, remotely debugging on Red Hat Linux 3.10.0-1062.4.1.el7.x86_64
C/C++ Extension Version: 0.29.0
Steps to Reproduce:

Create an object with a public C++ STL container (vector in this case)
Run debugger, all public STL containers in the object show their value as {...}
I have a struct called Grid1D which contains several std::vector. When I'm using an object of that struct the debugger displays {...} as the value, even when I try to copy the value.

Does this issue occur when all extensions are disabled?: Yes/No - I'm working in a remote machine and I'm not sure how to test this

**Comment by sean-mcmanus** [comment]
@WardenGnaw I also hit this recently when trying to do debugging on Linux/gdb. I couldn't get values for strings.

I seem to recall this used to work previously on my other Linux machine with an older OS/compiler.

**Comment by bcaddy** [comment]
I figured out my issue! I was using `vector.reserve()` instead of `vector.resize` and then trying to read and write using the `[]` operator.
