### ISSUE TITLE
Confusing intellisense error due to missing (and arguably not needed) enum value (most compilers pass the code)

### ISSUE THREAD

**Issue by TheJCAB** [microsoft/vscode-cpptools#5880]
**Type: LanguageService**

- OS and Version: Windows 10 WSL with Ubuntu 20.
- VS Code Version: Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
- C/C++ Extension Version: 0.29.0

**Steps to reproduce**

Just load this code:

```
template < typename T, T DefaultValue >
class Value
{
};

enum class A {};
enum class B {};

Value<A, A{}> a;

class ValueA : public Value<A, A{}> { public: using Value<A, A{}>::Value; };
class ValueB : public Value<B, B{}> { public: using Value<B, B{}>::Value; };

ValueA VA;
```

Intellisense will show a "not a class or struct name" error around the base class of ValueA, and a "expected a '>'" error at the '>' of that base class (ironic, but true).

It doesn't show any errors at the definition of "a", which uses the exact same base class, nor at the base class of ValueB. In fact, if you remove the last line, which uses ValueA, then the error goes away. Note that valueA is concrete, so it's fully instantiated without that last line.

The root cause here seems to be that A doesn't contain a named value of zero. If I add it, the error also goes away.

All compilers I've tried accept the code without issue. See: https://godbolt.org/z/dsr7eh

**Expected behavior**

If intellisense found an issue (like a missing name for a constructed enumeration value), it should probably do a better job to report the specific issue it found. It definitely detected that, somehow, indirectly. But the errors shown were only vaguely related.

In the end, this error is not an error, strictly speaking (language lawyers might provide different opinions here), and the code is accepted by GCC, clang and MSVC, but not by intellisense.

**Comment by sean-mcmanus** [comment]
A VS bug has been filed at https://developercommunity.visualstudio.com/content/problem/1136090/cc-intellisense-gives-an-incorrect-error-not-a-cla.html . You could upvote that if you have a Microsoft account.

**Comment by bobbrow** [comment]
This issue appears to be fixed in the latest version of the extension.
