### ISSUE TITLE
A small Typo in the error message 

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#5881]
I wrote some code like this 

```cpp
int const nums[5] = {1, 2, 3, 4, 5};
nums[1] = 10;
```
And the Error i am getting there is small typo -

![Image](https://i.imgur.com/au0Z0BA.png)

This error message should be **expression must be a modifiable value**
I tried hard to find the file, but i dont think its possible for me.

**Comment by Colengms** [comment]
Hi @yanjanendra .  `lvalue` is a technical term, referring historically to the left side of an assignment expression.  https://en.cppreference.com/w/cpp/language/value_category

**Comment by ghost** [comment]
Thanks i am noob in c-plus-plus then i thought it misspelled.
