### ISSUE TITLE
Cannot remove MinGW from the include path in source files

### ISSUE THREAD

**Issue by kyle-goodwin** [microsoft/vscode-cpptools#5884]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.29.0
- Cannot remove MinGW from the include path in source files.

**Steps to reproduce**
1. Create C source file.
2. Type `#include <stdint.h>`

**Expected behavior**
Should indicate the file does not exist. Instead it finds the file in `C:\MinGW\include`.

**Screenshots**
![wrong](https://user-images.githubusercontent.com/45823898/89126180-b63d6c00-d4b1-11ea-96ed-3d10a93dcbfe.png)

**Comment by kyle-goodwin** [comment]
This behavior appears to have been caused by the compiler path defaulting to MinGW and then automatically selecting some related include paths. I have not set any defaults for this. In the absence of a explicit path or default path the behavior should be an error, not silently configuring hidden paths.

**Comment by bobbrow** [comment]
This is the designed behavior.  Most people want the extension to work without having to mess around with the configuration files.  If you want to disable the automatic compiler detection, set the `compilerPath` property to `""` in `c_cpp_properties.json`.

**Comment by kyle-goodwin** [comment]
I'm not sure I agree with the designed behavior, I would expect if something gets automatically and silently changed to be made aware of it in the c_cpp_properties.json file, but now I know. Thank you for the answer and solution. Adding `    "C_Cpp.default.compilerPath": ""` to settings.json appears to give me the behavior I want.

**Comment by bobbrow** [comment]
Once the `c_cpp_properties.json` has been written to disk, we avoid touching it.  If you open a new folder and generate a `c_cpp_properties.json` for the first time, the compiler should be written to it.  I think this would address your concern in most cases.

Is this a case where the `c_cpp_properties.json` file already existed, or was it newly generated without the `compilerPath` set (which I would consider to be a bug)?

**Comment by bobbrow** [comment]
Though I am curious... why don't you want the extension to find C/C++ system headers for you?

**Comment by kyle-goodwin** [comment]
Not wanting to modify a preexisting `c_cpp_properties.json` is a fair point. When generating a new `c_cpp_properties.json` I do not get the compiler path added despite it appearing in the diagnostics log. You are correct in that, if this behaved for me as you described, it would address my concern.

This is a case of a newly generated `c_cpp_properties.json` without the `compilerPath` set.

**Comment by kyle-goodwin** [comment]
I have multiple C compilers. It's not that I don't want the extension to include headers for me, it's that I don't want compiler A's headers when I'm working with B. Granted, if I setup my compiler path this won't be an issue, but if I forget, I expect an error, not compiler A's headers snuck in.

**Comment by kyle-goodwin** [comment]
![image](https://user-images.githubusercontent.com/45823898/89323994-8e3a3e00-d654-11ea-92d5-6b2148c60856.png)

1. `test.c` was created and includes one line: `#include <stdint.h>` with no errors.
2. `C/C++: Log Diagnostics` was run showing the MinGW paths.
3. `c_cpp_properties.json` was generated without MinGW in `includePath` or `compilerPath`.

**Comment by kyle-goodwin** [comment]
Strangely this only seems to affect source files. `test.h` which is identical to `test.c` except for the extension does not give me a link to the MinGW header. It also doesn't immediately give me a squiggly line either, I have to reload vscode which is slightly annoying.

**Comment by sean-mcmanus** [comment]
Is there any issue here that needs to be followed up on, i.e. reopened or a new issue created?

If you want to exclude headers from a compiler you're not using from the database, you can add the path to files.exclude.

**Comment by bobbrow** [comment]
It sounds like there might be an issue with populating the `compilerPath` when a new `c_cpp_properties.json` is created.  Would you be able to check and see @sean-mcmanus?
