### ISSUE TITLE
Compile Error hyperlink to the source code

### ISSUE THREAD

**Issue by nilanjan** [microsoft/vscode-cpptools#589]
Is there any way to enable compile error hyperlink to the C/C++/h source code?

**Comment by sean-mcmanus** [comment]
There's a blog that describes how to setup a build task with build errors listed in the Problems window at https://blogs.msdn.microsoft.com/vcblog/2016/03/31/cc-extension-for-visual-studio-code/ . Are you able to get that to work? The problem matchers are used to create links to code. We have plans to add additional build tasks to make this easier in the future.

**Comment by nilanjan** [comment]
For multiple definitions, this does not work. It can't even suggest variable that is defined in the same scope.

**Comment by bobbrow** [comment]
Source file linting (squiggles) and better autocomplete suggestions were added to the extension mid-last year.  If you are having any trouble setting that up, feel free to reopen this issue.

**Comment by sean-mcmanus** [comment]
@bobbrow The issue is with build tasks and not IntelliSense features, right?

**Comment by bobbrow** [comment]
It sounds like it's about both.  The original comment was solved with tasks and problem matchers.  The second comment is about autocomplete and was solved with #13.
