### ISSUE TITLE
STL function "random_shuffle" cannot be properly detected using C++ Intellisense

### ISSUE THREAD

**Issue by Linus-XZX** [microsoft/vscode-cpptools#5890]
Issue Type: <b>Bug</b>

Platform: macOS 10.15.6 (19G73).

**Steps for reproduction:**
Create a .cpp file that has `#include <algorithm>`, which contains the STL function `random_shuffle`, and use the function in the file.
For example (`#include <algorithm>` happens beforehand):

> vector\<int\> Player;
> for (int i = 0; i < Wolverines + Villagers + Power; i++){Player.push_back(i);}
> srand(uint(time(0)));
> random_shuffle(Player.begin(), Player.end());

**Expected behavior:**
No errors be reported for the file in the editor (assuming no other errors exist).

**Actual behavior:**
VS Code reports an error complaining that `random_shuffle` is undefined, even though the file can be compiled without error using g++ (Apple clang 11.0.0) and the function behaves as defined in the STL.

PS: "Goto definition" and "Goto declaration" on `random_shuffle` both refers me to Line 2983 of `/Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm`, which is the definition of `random_shuffle`.

Extension version: 0.29.0
VS Code version: Code - Insiders 1.48.0-insider (62503719349d04686a0704f7646b761aaf495b3d, 2020-08-04T05:28:25.360Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 4|
|Memory (System)|8.00GB (2.94GB free)|
|Process Argv|-psn_0_36873|
|Screen Reader|no|
|VM|0%|
</details>

My thanks in advance.

**Comment by sean-mcmanus** [comment]
That's because IntelliSense and your algorithm header is configured such that random_shuffle is removed: see https://meetingcpp.com/blog/items/stdrandom_shuffle-is-deprecated.html .

You should be able to change your "cppStandard" setting to "c++14" to fix the issue.
