### ISSUE TITLE
Give better diagnostics when invalid compilerArgs are used

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5893]
See the thread at https://github.com/microsoft/vscode-cpptools/issues/5797 . An invalid compilerArg was used and caused the wrong system includes to be used. Maybe we can detect that and show an error squiggle or pop or error level logging (instead of hidden in debug logging).

There may be other invalid configurations we could expose warnings for better as well.

**Comment by Colengms** [comment]
I believe this has been addressed by recent work to add logging around compiler probing. The compiler probe command line is logged.  If we fail to probe the compiler, messages are output to the C/C++ Configuration Warnings channel. Closing this as fixed.
