### ISSUE TITLE
Doesn't seem to work on Ubuntu 16.04 32-bit

### ISSUE THREAD

**Issue by fuchangjie** [microsoft/vscode-cpptools#59]
vscode version: 1.1.1
cpptools version: 0.6.0
platform: ubuntu 16.04 32-bit

navigating code or debugging, doesn't seem to work at all, sigh...

**Comment by bartmao** [comment]
My code can debug, but go to definition is quite slow when the code base size is large. When I load FFMPEG in Visual Studio Code, It never works for the navigating feature:(
I'm using 16.04 64-bit currently.

**Comment by sridmad** [comment]
Thanks for the feedback. We will take a look at the perf issues.

**Comment by jgoshi** [comment]
Could you try this again with the latest version (VSCode 1.4, cpptools 0.8.1)? There have been multiple improvements so things may work a little better for you now?

**Comment by joewood** [comment]
Doesn't work on my Ubuntu 16.0.4 64-bit. Debugging works but language service doesn't. Can't see any meaningful errors in verbose model. Is this the `glibc` issue?

**Comment by alex-che** [comment]
Is there any chance that Linux 32-bit support will be added? Did you measure the percentage of 32-bit Linux users of VSCode?

**Comment by adentinger** [comment]
I also currently have this problem on my 32-bit Ubuntu 16.04 VM. See : [StackOverflow](http://stackoverflow.com/questions/41604419/go-to-definition-and-and-find-references-not-working). It works on my 64-bit Ubuntu 16.04 partition, though.

**Comment by sean-mcmanus** [comment]
We don't know yet if 32-bit Linux support will be added.

**Comment by bobbrow** [comment]
We will be tracking 32-bit Linux support under issue #424

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
