### ISSUE TITLE
Symbol search looks outside the folder that's open

### ISSUE THREAD

**Issue by shivarajagopal** [microsoft/vscode-cpptools#590]
Running on Windows here:
I have a git directory with two clones of the same repo. Let's call them CloneA/ and CloneB/. I use both occasionally.
If I open CloneB/ in VS Code, and search for a symbol, the CppTools extension returns a symbol from the corresponding file in CloneA/. Is this a known issue? Can I re-run the indexing?

**Comment by sean-mcmanus** [comment]
This is not know. With the default settings, when you open a workspace, it should only search for things that are in the workspace or outside the workspace but in your includePath and referenced via #include. You can rebuild the .browse.vc.db by deleting it or renaming the databaseFilename property in the c_cpp_properties.json.

**Comment by shivarajagopal** [comment]
Great, and where are these files located?

**Comment by sean-mcmanus** [comment]
On Windows, the default .browse.vc.db is under %appdata%\Code\User\workspaceStorage . You get the c_cpp_properties.json via the C/Cpp: Edit Configurations command.

**Comment by shivarajagopal** [comment]
Great. Thanks, I'll let you know if rebuilding .browse.vc.db helps at all.

**Comment by bobbrow** [comment]
If not, please let us know whether you are opening CloneB/ specifically, or if you are opening a parent folder that contains both CloneA/ and CloneB/.

**Comment by shivarajagopal** [comment]
I'm only opening CloneB/, and CloneA/ is nowhere in my folder tree, which is why I didn't expect to see it in my symbol search.

**Comment by shivarajagopal** [comment]
Rebuilding the file seems to have done the trick. Not sure why it happened in the first place, but I'll let you know if it happens again.

**Comment by sean-mcmanus** [comment]
This could occur if you opened a file from the other clone, i.e. if you're in the CloneA workspace and you open a file in CloneB, then we automatically parse the opened file from CloneB, including any #included  headers. Our future "database cleanup" work is expected to remove the CloneB symbols the next time the workspace is reopened or becomes invalidated.
