### ISSUE TITLE
VSCode debugger unable to pause a program running under root rights

### ISSUE THREAD

**Issue by adel-belkhiri** [microsoft/vscode-cpptools#5902]
Unable to pause a program running under root rights.

VSCode version: 1.47.3
C/C++ extension : v0.30.0 ; v0.29.0 and v0.28.3.
OS : Ubuntu 18.04 (Kernel : 4.19.5)
gdb version : 8.1.0.
Architecture: x86_64

This issue happens while I was trying to debug a program with root rights using a bash script wrapping the gdb command. The content of the script is the following :

pkexec /usr/bin/gdb $*

I tried also with "sudo" but I had the same behavior: When a program is running it is not possible to interrupt it. Besides, I was unable to set breakpoints after the program is already started. It shows the message "attempting to bind the breakpoint". The same behavior when breakpoints are disabled and enabled. When breakpoints are set before the program is started, the program execution is paused when they are hit.

When I use my script in an external terminal (without vscode), I can pause the running program with gdb commands. 
Is there anybody who found a workaround for this issue? 
Thank you.

launch.json file:
        {
            "name": "Flow Classify (gdb)",
            "miDebuggerPath": "/home/adel/src/gdb-root",
            "MIMode": "gdb",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/build/examples/dpdk-flow_classify",
            "args": [
                 "-c", "1",
                 "-n", "1", 
                 "--vdev", "net_vhost0,iface=/tmp/vhost-user1",
                 "--vdev", "net_vhost1,iface=/tmp/vhost-user2",
                 "--proc-type","primary",
                 "--socket-mem","1024",
                 "--" ,
                 "--rule_ipv4", "./rule_ipv4__ver2.db"
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}/build/examples/",
            "environment": [],
            "externalConsole": false,
            "logging": { "engineLogging": true, "trace": true, "traceResponse": true },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": false
                }
            ]
        }

Debugger output:
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[Switching to thread 6 (Thread 0x7fffe224a700 (LWP 1067))](running)\n"},"seq":1991}
[Switching to thread 6 (Thread 0x7fffe224a700 (LWP 1067))](running)
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"=thread-selected,id=\"6\"\n"},"seq":1993}
=thread-selected,id="6"
1: (11312) ->(gdb)
--> R (continue-18): {"type":"response","request_seq":18,"success":true,"command":"continue","body":{},"seq":1980}
<--   C (pause-19): {"command":"pause","arguments":{"threadId":1049},"type":"request","seq":19}
--> R (pause-19): {"type":"response","request_seq":19,"success":true,"command":"pause","body":{},"seq":1997}
<--   C (pause-20): {"command":"pause","arguments":{"threadId":1049},"type":"request","seq":20}
--> R (pause-20): {"type":"response","request_seq":20,"success":true,"command":"pause","body":{},"seq":2000}
<--   C (pause-21): {"command":"pause","arguments":{"threadId":1049},"type":"request","seq":21}
--> R (pause-21): {"type":"response","request_seq":21,"success":true,"command":"pause","body":{},"seq":2003}
<--   C (pause-22): {"command":"pause","arguments":{"threadId":1049},"type":"request","seq":22}
--> R (pause-22): {"type":"response","request_seq":22,"success":true,"command":"pause","body":{},"seq":2006}
<--   C (pause-23): {"command":"pause","arguments":{"threadId":1058},"type":"request","seq":23}

**Comment by Colengms** [comment]
@WardenGnaw

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue.  We’ll let you know if we need more information to investigate it.
