### ISSUE TITLE
Doxygen comment tags aren't ended after a blank line

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5903]
Use code
```
/**
 * @brief Shuffle vector.
 * @return Nothing.
 * 
 * Details...
 */
void shuffle(std::vector<int> &v);
```

Hover over shuffle.

The "Details..." comment is incorrectly combined with the Nothing comment.

The issue repros with doxgyen comments in the gcc headers.

A bug on VS is filed at https://developercommunity.visualstudio.com/content/problem/1137513/doxygen-comment-tags-arent-ended-after-a-blank-lin.html

**Comment by michelleangela** [comment]
This might be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/57 which just got fixed for Visual Studio.

**Comment by sean-mcmanus** [comment]
It's not fixed...it might have been improved via add a whitespace though. They closed it as low pri.

![image](https://user-images.githubusercontent.com/19859882/143157968-dab6afad-e252-4cc0-8874-5c62934793d2.png)

**Comment by 0Grit** [comment]
I'm not sure how this doesn't bother more people.

**Comment by Mode-77** [comment]
> I'm not sure how this doesn't bother more people.

It is very frustrating.

**Comment by Mode-77** [comment]
The closest mechanism to a solution for this issue is to use the `@details` or `\details` marker after adding `details` to the supported tags in the settings. After you do this, the text will have its own section like the others. See #11842.

**Comment by tueda** [comment]
Seems to have been fixed.

- VS Code Version: 1.95.2
- C/C++ Extension Version: 1.22.11

<img src="https://github.com/user-attachments/assets/32da94a9-ab21-4765-9e95-a7fc733639bd" width="400">

**Comment by sean-mcmanus** [comment]
@tueda Yeah, I see it fixed too.
