### ISSUE TITLE
Doxygen tag with  __first,__last renders as <b>first</b>,last

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5904]
Use code
```
/**
 * @param Range __first,__last
 */
void shuffle(int __first, int __last);
```
hover shows:

![image](https://user-images.githubusercontent.com/19859882/89448731-da48b980-d70c-11ea-9ac2-7833a3d7b272.png)

Doesn't repro with Visual Studio.

I noticed the issue when using gcc 9.3 headers (random_shuffle).

**Comment by bobbrow** [comment]
Yeah, we probably need to escape those characters for the markdown rendering.
