### ISSUE TITLE
Array visualizer font is too small; please make it easily customizable, or at least scale accordingly to the font size used in the text editor

### ISSUE THREAD

**Issue by GiovanniDicanio** [microsoft/vscode-cpptools#5905]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): none

Try to hover over a C `char[]` array, like:

`char name[] = "Connie";`

The visualizer displays its content using a font that is too small, as shown in the attached screenshot.

This is annoying, for example when recording for screen casts or presentations that require larger font for easier readability.

The best option would be to **allow the user to easily customize the font used by the visualizer** (just like we can customize fonts in other parts of VS Code, like in the text editor).

Or, at least, the font size of the visualizer should be similar to the font size used to display the code in the editor.

![VS_Code_Bug_Visualizer_Font_Small](https://user-images.githubusercontent.com/4692631/89450388-bca24100-d75a-11ea-8683-e3b220fd455c.png)

**Comment by WardenGnaw** [comment]
UI is handled by VS Code. I posted this issue in their issues page.
