### ISSUE TITLE
Avoid adding Windows SDK include paths if already specified as include paths

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#5910]
Currently, if the `windowsSdkVersion` is not set, the latest Windows SDK installed on the system is used.  If include paths that refer into a prior Windows SDK are also specified, multiple Windows SDKs will be parsed.

If a Windows SDK is specified via include paths, additional Windows SDK paths should not be added.

**Comment by sean-mcmanus** [comment]
If it's hard to detect Windows SDK header paths in includePath maybe we could make setting a blank windowsSdkVersion cause the default to not be auto-added.
