### ISSUE TITLE
Ctrl F（find） cannot be used

### ISSUE THREAD

**Issue by hncat** [microsoft/vscode-cpptools#5920]
Issue Type: <b>Bug</b>

After downloading the latest C/C++, the Ctrl+F shortcut will not work properly

Extension version: 0.29.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-106-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (11.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: 120.25.248.199|
|OS|Linux x64 4.15.0-106-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz (2 x 2500)|
|Memory (System)|3.85GB (0.49GB free)|
|VM|100%|
</details>

**Comment by sean-mcmanus** [comment]
I'm not reproing the bug. Our extension doesn't add any keymappings for Ctrl+F -- see https://github.com/microsoft/vscode-cpptools/blob/master/Extension/package.json and search for "key".

Does the issue go away after disabling the C/C++ extension?
