### ISSUE TITLE
Can not find C or C++ for VS on Mac using extension tab

### ISSUE THREAD

**Issue by steelbiker** [microsoft/vscode-cpptools#5921]
Type: General

I followed the steps on the VS website for finding and downloading C and C++ for VS on Mac. They did not appear when I searched. I made sure I was accessing the gallery and not searching the downloaded extensions. I also refreshed.

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by sean-mcmanus** [comment]
What do you mean by "VS on Mac"? What VS website are you referring to? Our C/C++ extension only runs in VS Code and not VS for Mac.

**Comment by bobbrow** [comment]
C and C++ are not supported in VS for Mac.

This is the feature to go upvote: https://developercommunity.visualstudio.com/content/idea/356171/support-projects-with-c-c14-c17-language-with-inte.html
