### ISSUE TITLE
Parse Indirect paths

### ISSUE THREAD

**Issue by zachconfalone** [microsoft/vscode-cpptools#5924]
Hey Guys, quick feature request. The way I have my directory/build structure, The headers #included in files differ from the location that they are in the directories that Intellisense parses. So when the extension parses the active file, it cannot find some of the headers because it wasn’t in a path known to Intellisense. 

For Example, a path might look something like this:

`Includes/example_1/src/main/cpp/test.H`

A file “test.cpp” would just #include “/example_1/test.h”. It would be nice if Intellisense would be able to infer this and parse the indirect path.

**Comment by bobbrow** [comment]
Is that valid syntax?  Are you able to compile it?  If you start the include with a slash that will start the lookup in the root directory.  We support relative paths if you do `#include "./example_1/test.H"` or `#include "example_1/test.H`.  And note that case matters on some operating systems (for example, if you are on linux).

**Comment by zachconfalone** [comment]
> Is that valid syntax? Are you able to compile it? If you start the include with a slash that will start the lookup in the root directory. We support relative paths if you do `#include "./example_1/test.H"` or `#include "example_1/test.H`. And note that case matters on some operating systems (for example, if you are on linux).

The include should be `#include “example_1/test.H"`. It does compile, at compile time src/main/cpp in the path effectively go away. See the images below to better explain what I'm talking about. 

<img width="799" alt="Screen Shot 2020-08-07 at 10 19 19 PM" src="https://user-images.githubusercontent.com/32858613/89700519-a59b5480-d8fc-11ea-9da3-ee02b05784df.png">
<img width="782" alt="Screen Shot 2020-08-07 at 10 21 11 PM" src="https://user-images.githubusercontent.com/32858613/89700521-a8964500-d8fc-11ea-8cfe-a32ca9780dbb.png">

**Comment by bobbrow** [comment]
What is the command line you are using to compiling this?  The file `test.H` does not exist in the `example_1` folder. It exists in `includes/example_1/src/main/cpp`.  To get it to work you'd have to write `#include "includes/example_1/src/main/cpp/test.H"` in your source file.
