### ISSUE TITLE
"textmate scopes" coloring does not take effect

### ISSUE THREAD

**Issue by zb-007** [microsoft/vscode-cpptools#5927]
**Type: LanguageService**

![111](https://user-images.githubusercontent.com/54835759/89623001-81248580-d8c6-11ea-926c-1f3ea69b7194.PNG)

hello guys:
After I upgraded the c/c++ plugin to version 0.29.0，this happens.
How can i fix it?

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @zb-007 .  Can you clarify what behavior you were expecting, and what behavior you are seeing instead?  I see that there is a `semantic token type` referred to in the image you posted, which indicates our semantic token provider is working and we are successfully returning a semantic token for a function.  I see from the listed scopes that (a scope more specific than) `entity.name.function` is included, so should fall back that the same token we had supported previously, unless a more specific color assignment is available.  It's possible you are using a theme that also colors `function` semantic tokens, or perhaps `entity.name.function.call` differently?  That could explain why you are seeing different colors than you did previously.  I do not know why the last line is striked-out.  That's a VS Code behavior that I'm not familiar with.

**Comment by zb-007** [comment]
@Colengms

**Comment by zb-007** [comment]
@Colengms 
thank you for your reply. Actually I need more detailed syntax coloring.
Before the upgrade, the syntax coloring of my function calls and function definitions was different.
What I am wondering is that a more refined token ("entity.name.function.call") is provided by "textmate scope", why the syntax coloring still uses "entity.name.function".
Can I use semantic highlighting to color function definitions and function calls?
thanks alot!

**Comment by zb-007** [comment]
Before upgrade, my workbench like this:
![22](https://user-images.githubusercontent.com/54835759/89766563-ebd5fb00-db2a-11ea-9346-ec031563b266.PNG)
![23](https://user-images.githubusercontent.com/54835759/89766606-03ad7f00-db2b-11ea-9cb3-c397a31f6cbc.PNG)

The "Textmate scope" works well, and The tokens are all highlighted correctly according to the color I set.

**Comment by Colengms** [comment]
Hi @zb-007.

Previously, the C/C++ Extension had implemented its own support for semantic colorization.  We would look up the appropriate colors ourselves, and apply them as decorations in the editor.  Now that we have switched to the new Semantic Tokens API in VS Code, selecting the colors for those tokens is handled by VS Code.  There is a [Semantic Highlighting Guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#:~:text=Semantic%20highlighting%20is%20an%20addition,rules%20expressed%20in%20regular%20expressions.) that describes configuring colors for semantic tokens.  If you are using a theme that does not color them directly, our tokens should be falling back to the same TextMate scopes they were previously.

> Can I use semantic highlighting to color function definitions and function calls?

I notice in your images that function definitions were colored differently from function calls.  Our extension doesn't currently distinguish between these and considers them both 'function' tokens.  If this is a problem, we can open a bug against VS to consider these separate tokens.  (Our semantic parser is shared with VS).

Semantic Highlighting support can also be disabled in the C/C++ extension using: `"C_Cpp.enhancedColorization": "Disabled"`

**Comment by zb-007** [comment]
> Hi @zb-007.
> 
> Previously, the C/C++ Extension had implemented its own support for semantic colorization. We would look up the appropriate colors ourselves, and apply them as decorations in the editor. Now that we have switched to the new Semantic Tokens API in VS Code, selecting the colors for those tokens is handled by VS Code. There is a [Semantic Highlighting Guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#:~:text=Semantic%20highlighting%20is%20an%20addition,rules%20expressed%20in%20regular%20expressions.) that describes configuring colors for semantic tokens. If you are using a theme that does not color them directly, our tokens should be falling back to the same TextMate scopes they were previously.
> 
> > Can I use semantic highlighting to color function definitions and function calls?
> 
> I notice in your images that function definitions were colored differently from function calls. Our extension doesn't currently distinguish between these and considers them both 'function' tokens. If this is a problem, we can open a bug against VS to consider these separate tokens. (Our semantic parser is shared with VS).
> 
> Semantic Highlighting support can also be disabled in the C/C++ extension using: `"C_Cpp.enhancedColorization": "Disabled"`


thank you for your reply. I delete the "support.function" colored in my theme, all is ok.
thanks again!
