### ISSUE TITLE
\" won't be replace to " in launch.json

### ISSUE THREAD

**Issue by F-Unction** [microsoft/vscode-cpptools#5928]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 2004 19041.388
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is. `\"` in launch.json won't be replace to `"` when I debug.

**To Reproduce**
Code sample
```
int main()
{
    return 0;
}
```

launch.json
```json
            ....
            "program": "cmd",
            "args": [
                "/C",
                "echo \"test\" & pause",
            ],
            "externalConsole": true,
            ....
```
1. Open a file
2. Press `F5`
3. See the cmd.exe window

There are `\"test\"` but not `"test"`
![Snipaste_2020-08-07_15-46-32](https://user-images.githubusercontent.com/51352133/89622621-e62bab80-d8c5-11ea-86e9-c8f525b265f9.png)
How can I enter `"` into it?

**Comment by WardenGnaw** [comment]
Which debugger `type` are you using in your `launch.json`?

**Comment by F-Unction** [comment]
@WardenGnaw 
cppvsdbg
