### ISSUE TITLE
Shortcut key for calling function list

### ISSUE THREAD

**Issue by vscpp** [microsoft/vscode-cpptools#593]
May I know what's the keyboard shortcut for calling function list? Thanks.

Like below picture, click the function name in status bar.
![image](https://cloud.githubusercontent.com/assets/26138585/24341240/eaa8ac0c-12ea-11e7-8ced-19480b8f1c94.png)

Then below function list will appear here.
![image](https://cloud.githubusercontent.com/assets/26138585/24341258/0cb04774-12eb-11e7-8e3a-d180e29333df.png)

**Comment by sov1178** [comment]
@vscpp Try Ctrl+Shift+O

**Comment by sean-mcmanus** [comment]
We never added an external command or keybinding for that, but you can add one yourself by modifying the package.json file in the root of the extensions folder by replacing lines:
`      {
        "command": "C_Cpp.SwitchHeaderSource",
        "title": "C/Cpp: Switch Header/Source"
      }
    ],
    "keybindings": [
      {
        "command": "C_Cpp.SwitchHeaderSource",
        "key": "Alt+O",
        "when": "editorTextFocus"
      }
    ],`
with
`      {
        "command": "C_Cpp.SwitchHeaderSource",
        "title": "C/Cpp: Switch Header/Source"
      },
      {
        "command": "C_Cpp.Navigate",
        "title": "C/Cpp: Navigate"
      }
    ],
    "keybindings": [
      {
        "command": "C_Cpp.SwitchHeaderSource",
        "key": "Alt+O",
        "when": "editorTextFocus"
      },
      {
        "command": "C_Cpp.Navigate",
        "key": "Alt+F2",
        "when": "editorTextFocus"
      }
    ],`.

We'll add that in a future version.

**Comment by bobbrow** [comment]
We added an ALT+N keybinding in v.0.11.0 to open up this list.

**Comment by vscpp** [comment]
@sean-mcmanus, @bobbrow, Thanks very much for your effort. 👍
