### ISSUE TITLE
Infer compile_commands.json entries for new files

### ISSUE THREAD

**Issue by ryanpholt** [microsoft/vscode-cpptools#5934]
I've configured Intellisense using a compile_commands.json file. So, whenever I create a new file in my workspace, Intellisense shows a warning saying that there is no entry in the compile_commands.json for the new file (and no Intellisense operations work). Can the extension infer the build args from a different translation unit in the same folder/workspace?  My experience with ccls/clangd in the past is that they do something like this. Maybe the extension could emit a warning saying that it inferred the build arguments for the file that it could not find in compile_commands.json?

My current workflow involves regenerating the compile_commands whenever I add a new file but that is less than ideal. I suppose I could fill in the `includePath`, `defines`, etc. just for the case when I add new files. But, our build system is complicated and so it is much easier to rely on compile_commands.json.

**Comment by Colengms** [comment]
Hi @ryan-holt-1 .  Thanks for the suggestion.  In the meanwhile, you should be able to provide fallback settings in the same configuration in `c_cpp_properties.json`.  Normally, use of `compileCommands` would supersede any other configuration settings.  But, when an entry is not available in `compile_commands.json`, the extension should fall back the rest of that configuration in `c_cpp_properties.json` (or equivilent `C_Cpp.default.*` settings).  Please let us know if that doesn't work as expected for you.
