### ISSUE TITLE
Incompatible License 

### ISSUE THREAD

**Issue by Katana-Steel** [microsoft/vscode-cpptools#5935]
Type: General

LICENSE.md and extension/license.txt
Seem to be different please clarify is this MIT licensed or not?

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by michelleangela** [comment]
It's MIT licensed.

**Comment by bobbrow** [comment]
More information here: #5784
