### ISSUE TITLE
IntelliSense parser not handling correctly MinGW 64 headers

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vscode-cpptools#5940]
**Type: LanguageService**

![image](https://user-images.githubusercontent.com/145155/89725856-8abc0380-da14-11ea-974c-e40c39baa8ec.png)

- C/C++ Extension Version: 0.30.0 - insiders
- Other extensions you installed (and if the issue persists after disabling them): none
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- **Using fresh, vanilla MinGW setup ... Intellisense shows "Problems" where there are no problems.**

![image](https://user-images.githubusercontent.com/145155/89725928-601e7a80-da15-11ea-8a22-accea0d4ead2.png)

![image](https://user-images.githubusercontent.com/145155/89725959-bbe90380-da15-11ea-85af-2fcc23bd73cb.png)

**Comment by DBJDBJ** [comment]
**"non STL" version has no Intellisense issues**

![image](https://user-images.githubusercontent.com/145155/89726950-cbba1500-da20-11ea-9687-da91dbcc12ba.png)

**Comment by Colengms** [comment]
Hi @DBJDBJ .  Thanks for reporting this.  I suspect there is some code in MinGW's standard headers that our IntelliSense parser is not handling correctly, leading to other parsing issues.

**Comment by Colengms** [comment]
Hi @DBJDBJ Are you still seeing this issue?  With a recent build of the extension (1.1.0-insiders4), and having set cppStandard to either c++17 or c++20, I'm no longer able to repro the issue.

**Comment by DBJDBJ** [comment]
@Colengms sorry but we have moved away from MinGW. I trust you have tested and this now works correctly.

Alas, we are now experiencing IntelliSense issues while using clang-cl.exe ... But that is also endemic to VStudio, too. If time I will detail another issue.
