### ISSUE TITLE
insiders upgrade/downgrade is broken if we recall an insider release

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#5947]
While reviewing PR #5946, I was looking at the code that determines a valid array of builds.  It requires 3 or more assets to be marked as "valid".  But we also did a feature where if the assets are removed, then we downgrade a user to an older vsix.  It looks like our validity check will block the feature from being invoked (and actually break all downloads) if we ever remove the assets online, so instead of check `isArrayOfBuilds`, we need to `getArrayOfBuilds` which automatically filters out the recalled releases.  Am I reading the code right?

**Comment by zooba** [comment]
Is this what's causing me to cycle through these two prompts each time I restart VSC?
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1693688/89919149-d0362780-dbf2-11ea-99a0-856f619018a2.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1693688/89919156-d1ffeb00-dbf2-11ea-9f74-9d7d6efbcf63.png)

**Comment by bobbrow** [comment]
That looks like a different issue and I'm not sure of the cause.  I PM'ed you about it.

**Comment by elahehrashedi** [comment]
I changed the functionality of the isBuild function, to recognize if an input is a "build" type, or if it is a "build" type with 3 assets (i.e. "valid" build type)
