### ISSUE TITLE
Using clang-format on Linux ARM/ARM64 requires that libtinfo5 is installed

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5958]
The workaround is to install libtinfo5 (or libncurses5).

To fix this we would need to recompile clang-format for ARM/ARM64 with static linking (like we do for other architectures)

Upvote this if this fix is important to you. I hit it with the 64-bit Raspberry Pi OS.

**Comment by Colengms** [comment]
The build configs for this are complete, but M2 approval is required for real-signing, and our M2 is out until 12/15.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
