### ISSUE TITLE
Intellisense not working 

### ISSUE THREAD

**Issue by dbersan** [microsoft/vscode-cpptools#5963]
_Specs: Ubuntu 18.04, VSCode 1.47.3, C/C++ extension 0.30.0-insiders2 (also tried the non-insiders)_

It's truly remarkable C++ has been around for at least 40 years and we still don't have a proper intellisense. 

It is underlying in red the include header:
![image](https://user-images.githubusercontent.com/25873377/90163046-dc0e1f00-dd95-11ea-9212-1634b930090d.png)

 Even though I can still Ctrl+click it and go to the source file:
![image](https://user-images.githubusercontent.com/25873377/90163157-052eaf80-dd96-11ea-95e8-0cfd50a3e841.png)

Of course I wouldn't be posting this issue if this were the only problem. 

I also don't get auto-complete: 

![image](https://user-images.githubusercontent.com/25873377/90163293-314a3080-dd96-11ea-8f9b-eeecd050877f.png)

As a matter of fact, it gives me **_wrong_** auto-completion suggestions: 

![image](https://user-images.githubusercontent.com/25873377/90165396-e2ea6100-dd98-11ea-9e2e-fe059ef3cc01.png)

Yes, `.vscode/c_cpp_properties.json` exists, at the root of the folder, and contains the following: 

```json
{
    "configurations": [
        {
            "browse": {
                "databaseFilename": "",
                "limitSymbolsToIncludedHeaders": true
            },
            "includePath": [
                "/home/user/catkin_ws/devel/include/**",
                "/opt/ros/melodic/include/**",
                "/usr/include/**",
                "include/"
            ],
            "name": "ROS",
            "intelliSenseMode": "gcc-x64",
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu11",
            "cppStandard": "gnu++14",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

`/opt/ros/melodic/include/`contains the `ros` folder with the header. 

Am I doing something wrong?

**Comment by sean-mcmanus** [comment]
The "file not found" error message is from the C/C++ Clang Command Adapter extension and not the C++ extension.

After you disable that other extension, if you still get errors, you may want to run C/C++: Log Diagnostics (from the Command Palette) to see what include paths are getting passed to IntelliSense. And although you're using compileCommands, so the includePath setting won't be used unless it falls back to that, it would also be good to remove the system includes from includePath, because system includes should be auto-obtained from the compilerPath setting.

**Comment by dbersan** [comment]
> The "file not found" error message is from the C/C++ Clang Command Adapter extension and not the C++ extension.

You are right about this, I tried installing this C lang extension to see if it solved the problem and forgot to remove. Now there is no re underlining.

> it would also be good to remove the system includes from includePath, because system includes should be auto-obtained from the compilerPath setting

I removed it and still no auto complete. 

> you may want to run C/C++: Log Diagnostics (from the Command Palette)

here is the output, after removing system path. 

```bash
-------- Diagnostics - 8/13/2020, 9:00:17 PM
Version: 0.30.0-insiders2
Current Configuration:
{
    "browse": {
        "limitSymbolsToIncludedHeaders": true,
        "path": [
            "/home/user/catkin_ws/devel/include/**",
            "/opt/ros/melodic/include/**",
            "include/",
            "${workspaceFolder}"
        ]
    },
    "includePath": [
        "/home/user/catkin_ws/devel/include/**",
        "/opt/ros/melodic/include/**",
        "include/"
    ],
    "name": "ROS",
    "intelliSenseMode": "gcc-x64",
    "compilerPath": "/usr/bin/g++-7",
    "cStandard": "gnu11",
    "cppStandard": "gnu++14",
    "compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "compilerArgs": []
}
Translation Unit Mappings:
[ /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp ]:
    /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
    /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/include/driver/edo_driver.h
[ /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface_node.cpp ]:
    /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface_node.cpp
Translation Unit Configurations:
[ /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp ]:
    Process ID: 18461
    Memory Usage: 259 MB
    Compiler Path: /usr/bin/g++-7
    Includes:
        /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/include
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /home/user/catkin_ws/devel/include
        /opt/ros/melodic/include
        /opt/ros/melodic/include/g2o
        /opt/ros/melodic/include/moveit
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
[ /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface_node.cpp ]:
    Process ID: 18537
    Memory Usage: 466 MB
    Compiler Path: /usr/bin/g++-7
    Includes:
        /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/include
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /opt/ros/melodic/include
        /opt/ros/melodic/include/g2o
        /opt/ros/melodic/include/moveit
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
Total Memory Usage: 725 MB
```

**Comment by dbersan** [comment]
One weird thing that is happening is that I have the following structure: 

![image](https://user-images.githubusercontent.com/25873377/90175771-37e1a380-dda8-11ea-973d-1dd702a041f4.png)

And the autocomplete works fine on files like `edo_hardware.h`, `edo_hardware_interface.h`, `edo_hardware_interface.cpp` (each includes the other, sequentially): 

![image](https://user-images.githubusercontent.com/25873377/90176543-6a3fd080-dda9-11ea-9986-fe16c8892fad.png)

But it does not work on `edo_driver.h` (or `edo_driver.cpp`), which is on another folder and doesn't include those files: 

![image](https://user-images.githubusercontent.com/25873377/90176686-a3784080-dda9-11ea-84c7-0377631a3077.png)

Even though they include the same header...

**Comment by sean-mcmanus** [comment]
Your includePath output looks good. Are you getting any error squiggles in edo_driver.cpp? Does any other IntelliSense functionality work in edo_driver.cpp (or edo_driver.h), such as error squiggles (if you add a syntax error) or go to definition on a local variable?

If you check your "C/C++" logging (not the C/C++ Diagnostics logging) do you see a "Failed to read response from server"? That would mean the IntelliSense process is crashing. 0.30.0-insiders2 has one known completion crash regression (https://github.com/microsoft/vscode-cpptools/issues/5960). If you don't see the "C/C++" logging pane then there hasn't been any error level logging.

**Comment by dbersan** [comment]
> Your includePath output looks good. Are you getting any error squiggles in edo_driver.cpp? Does any other IntelliSense functionality work in edo_driver.cpp (or edo_driver.h), such as error squiggles (if you add a syntax error) or go to definition on a local variable?

Actually, in `edo_driver.cpp` auto-complete does not seem to work at all. I can still go to definitions, I don't see any syntax errors when I type somethign wrong:

![image](https://user-images.githubusercontent.com/25873377/90179231-6c0b9300-ddad-11ea-940b-3a56dbf569fb.png)

> If you check your "C/C++" logging (not the C/C++ Diagnostics logging) do you see a "Failed to read response from server"?

Where can I find this?

**Comment by sean-mcmanus** [comment]
If you don't get syntax errors, then IntelliSense is not functioning at all for that particular TU. Go to Definition on global variables can still operate without the IntelliSense process via querying the database, but you should see Go to Definition on local variables not working.

We have documentation on enabling debug logging at https://code.visualstudio.com/docs/cpp/enable-logging-cpp , but "Error" level logging should be sufficient for seeing if there's a crash, but Debug logging may show additional helpful diagnostics. Do you see any logging that appears to be unexpected?

**Comment by sean-mcmanus** [comment]
Also, we only shows errors for the currently open files, but it's possible a header file could be causing a parser error that is causing a cascading parse failure in the open files, so one potential thing to try is to use something like "g++ -E -std=c++17 > test.out.cpp" to generate a preprocessed file with no `#include`s and seeing if you see any IntelliSense errors with that file.

**Comment by dbersan** [comment]
I tried doing "Error" level logging, but I get absolutely no error ever. With "Information" level I get the following for working and non-working files: 

![image](https://user-images.githubusercontent.com/25873377/90181018-14baf200-ddb0-11ea-86ab-0d97c37ff943.png)

```bash
Checking for syntax errors: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/include/edo_hardware_interface/edo_hardware.h
0 include path suggestion(s) discovered.
```
![image](https://user-images.githubusercontent.com/25873377/90181338-94e15780-ddb0-11ea-837a-0122023814bb.png)

(this is a new header I just created inside the same folder as the header that works)

```bash
Checking for syntax errors: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/include/edo_hardware_interface/somefile.h
Checking for syntax errors: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/include/edo_hardware_interface/somefile.h
Checking for syntax errors: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/include/edo_hardware_interface/somefile.h
Checking for syntax errors: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/include/edo_hardware_interface/somefile.h
```

It seems to be searching over and over ...

**Comment by dbersan** [comment]
> Also, we only shows errors for the currently open files, but it's possible a header file could be causing a parser error that is causing a cascading parse failure in the open files, so one potential thing to try is to use something like "g++ -E -std=c++17 > test.out.cpp" to generate a preprocessed file with no `#include`s and seeing if you see any IntelliSense errors with that file.

I'm not sure if I understood exactly,.. when I try that command passing a cpp file it can't find the headers, I'm not sure how to specify the header locations that are not relative (the ones installed on the system, written inside `<>` brackets). 

ex: 
```bash
g++ somefile.cpp -I. -E -std=c++17 > somefile.out
```

result: 

```bash
somefile.h:3:10: fatal error: ros/ros.h: No such file or directory
 #include <ros/ros.h>
          ^~~~~~~~~~~
```

**Comment by sean-mcmanus** [comment]
So it sounds like someFile.h isn't getting IntelliSense (no squiggle for the missing include). That looks like a like https://github.com/microsoft/vscode-cpptools/issues/5923 that got fixed with 0.30.0-insiders2, but it looks like you have 0.30.0-insiders2 already. The "Checking for syntax error" is supposed to only happen after some edit or config change. If you enable "Debug" level logging you may be able to see what is triggering the multiple checks.

By "g++ ..." I meant to say you need to use whatever command line is required to build that particular file, so you may need to add -I or other flags, e.g. '-I /opt/ros/melodic/include`, etc.

**Comment by dbersan** [comment]
> So it sounds like someFile.h isn't getting IntelliSense (no squiggle for the missing include). That looks like a like #5923 that got fixed with 0.30.0-insiders2, but it looks like you have 0.30.0-insiders2 already. The "Checking for syntax error" is supposed to only happen after some edit or config change. If you enable "Debug" level logging you may be able to see what is triggering the multiple checks.
> 
> By "g++ ..." I meant to say you need to use whatever command line is required to build that particular file, so you may need to add -I or other flags, e.g. '-I /opt/ros/melodic/include`, etc.

Yes I have this version
![image](https://user-images.githubusercontent.com/25873377/90186813-1a690580-ddb9-11ea-85a2-8c98c10a9d46.png)

The log is extensive, but I will send it for the following cases
 
**1) I type a variable and press ".", wait for auto complete (but don't get it):**

![image](https://user-images.githubusercontent.com/25873377/90187199-af6bfe80-ddb9-11ea-80df-20a1d2aa457a.png)

```bash
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1835)
auto_complete::handle_completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (18:25)
Offering completion
sending 1 changes to server
cpptools/getFoldingRanges: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1836)
cpptools/getCodeActions: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1837)
cpptools/getSemanticTokens: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1838)
cpptools/getDocumentSymbols: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1839)
cpptools/getDocumentSymbols
Checking for syntax errors: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
Queueing IntelliSense update for files in translation unit of: /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
  tag parsing file: /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.258
Database safe to open
``` 

2) Clean the output and type gibberish: 

![image](https://user-images.githubusercontent.com/25873377/90187354-ec37f580-ddb9-11ea-95e2-1b7fa740f374.png)

```bash
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1847)
auto_complete::handle_completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (18:27)
Offering completion
sending 1 changes to server
sending 1 changes to server
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1848)
auto_complete::handle_completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (18:30)
Offering completion
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
cpptools/getSemanticTokens: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1849)
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1850)
cpptools/getCodeActions: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1851)
cpptools/getDocumentSymbols: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1852)
cpptools/getDocumentSymbols
Checking for syntax errors: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
Queueing IntelliSense update for files in translation unit of: /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
  tag parsing file: /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.259
cpptools/getSemanticTokens: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_driver.cpp (id: 1853)
Database safe to open
```
3) Same as (1), but with a working file:

![image](https://user-images.githubusercontent.com/25873377/90187487-243f3880-ddba-11ea-9434-3e876c4880a1.png)

```bash
textDocument/hover: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1895)
Database safe to open
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1896)
auto_complete::handle_completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (33:13)
Offering completion
sending 1 changes to server
completionItem/resolve (id: 1897)
cpptools/getFoldingRanges: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1898)
cpptools/getCodeActions: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1899)
cpptools/getSemanticTokens: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1900)
cpptools/getDocumentSymbols: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1901)
cpptools/getDocumentSymbols
```
4) Same as (2), but with working file: 
![image](https://user-images.githubusercontent.com/25873377/90187672-6e281e80-ddba-11ea-83b5-5e301c0d2eb1.png)
```bash
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1944)
auto_complete::handle_completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (33:14)
Offering completion
sending 1 changes to server
completionItem/resolve (id: 1945)
Request canceled: 1945
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
cpptools/textEditorSelectionChange
completionItem/resolve (id: 1946)
Request canceled: 1946
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1947)
auto_complete::handle_completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (33:17)
Offering completion
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1948)
auto_complete::handle_completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (33:18)
Offering completion
sending 1 changes to server
cpptools/getSemanticTokens: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1949)
textDocument/didChange: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1950)
auto_complete::handle_completion: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (33:19)
Offering completion
sending 1 changes to server
cpptools/getFoldingRanges: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1951)
cpptools/getCodeActions: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1952)
textDocument/hover: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1953)
cpptools/getDocumentSymbols: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1954)
cpptools/getDocumentSymbols
Checking for syntax errors: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
Queueing IntelliSense update for files in translation unit of: /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
  tag parsing file: /home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 3
Error squiggle count: 0
Update IntelliSense time (sec): 0.255
cpptools/getSemanticTokens: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1955)
cpptools/getSemanticTokens: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/include/edo_hardware_interface/edo_hardware.h (id: 1956)
cpptools/getSemanticTokens: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/somefile.h (id: 1957)
cpptools/getCodeActions: file:///home/user/catkin_ws/src/MoveitArm-Example/edo_hardware_interface/src/edo_hardware_interface.cpp (id: 1958)
Database safe to open
```

**Comment by dbersan** [comment]
Not sure if this is helpful, I guess the best approach would be to find out why one file is working and the other isn't. Probably would be the headers? ..

**Comment by sean-mcmanus** [comment]
Yeah, nothing stands out in those logs as being an error. My guess is that an included but not opened header dependency is causing an IntelliSense parser failure (not a crash). So either the -E mechanism or manually using Go to Definition on the `#include`s may help locate the root parser failure.

Another possibility is there's an error with our IntelliSense cache files, so it would be worth temporarily changing C_Cpp.intelliSenseCacheSize to 0 and seeing if that fixes the issue.

**Comment by bobbrow** [comment]
Is there a way you can share your project with us or help us get something similar on our machines so we can debug it?  I see references to Catkin and ROS and found this resource: http://wiki.ros.org/catkin/workspaces.  If there are sample projects on that website would they be able to reproduce the same problems?

**Comment by dbersan** [comment]
> Is there a way you can share your project with us or help us get something similar on our machines so we can debug it? I see references to Catkin and ROS and found this resource: http://wiki.ros.org/catkin/workspaces. If there are sample projects on that website would they be able to reproduce the same problems?

If you want to try to reproduce this I can help you, but it's not so easy because you'd need to set up some things... here is an overview: 

1. Follow the instructions to [install ROS](http://wiki.ros.org/melodic/Installation/Ubuntu) 
2. Install catkin build, it's easier to use: `sudo apt-get install ros-melodic-catkin`
3. Create a folder somewhere with src: `mkdir -p workspace/src`
4. Initialize the workspace there: `cd workspace; catkin build`
5. Clone the msgs package from comau into `src/`: `cd src; git clone https://github.com/Comau/eDO_core_msgs`
6. Build again: `catkin build`
7. Clone my repository also into `src/`where I'm having these errors: `git clone https://github.com/dhiegomaga/MoveitArm-Example.git`
8. Build again: `catkin build`

Then you can open vscode on the project folder.. `code src/MoveitArm-Example/edo_hardware_interface`.

**Comment by dbersan** [comment]
> Yeah, nothing stands out in those logs as being an error. My guess is that an included but not opened header dependency is causing an IntelliSense parser failure (not a crash). So either the -E mechanism or manually using Go to Definition on the `#include`s may help locate the root parser failure.
> 
> Another possibility is there's an error with our IntelliSense cache files, so it would be worth temporarily changing C_Cpp.intelliSenseCacheSize to 0 and seeing if that fixes the issue.

I've found which header causes this issue, although I don't know an easy solution to this because I need the header. 

As soon as I take off the header `edo_core_msgs/MovementCommand.h`, the extension works normally. 
![image](https://user-images.githubusercontent.com/25873377/90195815-c1a26880-ddca-11ea-8bba-b5b4ccfc0960.png)

The other files did not include this header, hence they worked normally. 

Why? Well, after some testing, I came to a conclusion... 

The file `edo_core_msgs/MovementCommand.h` looks like this: 

```cpp

#ifndef EDO_CORE_MSGS_MESSAGE_MOVEMENTCOMMAND_H
#define EDO_CORE_MSGS_MESSAGE_MOVEMENTCOMMAND_H

#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <edo_core_msgs/Point.h>
#include <edo_core_msgs/Frame.h>

namespace edo_core_msgs
{
template <class ContainerAllocator>
struct MovementCommand_
{
  typedef MovementCommand_<ContainerAllocator> Type;
//...
```
If I comment the whole thing, the problem disappears, so somewhere in there must be causing the issue. 
However, no single line was truly responsible, but a combination of lines. 

After some testing, I could reproduce the same issue with just four lines uncommented: 

```cpp
#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
```

Those are official ROS headers, and this suffices to reproduce this issue, so it is not the `edo_core_msgs/MovementCommand.h` necessarily. 

What changes when I add or remove those headers? 

_Without the headers_, if I peak definition on the namespace `ros`, I get this: 
![image](https://user-images.githubusercontent.com/25873377/90197908-6d01ec00-ddd0-11ea-8b0b-130748a429a7.png)

1 definition. 

However, _with the aforementioned headers_, when I peak definition, I get: 
![image](https://user-images.githubusercontent.com/25873377/90197952-90c53200-ddd0-11ea-8caa-9a06516eef29.png)

**108 definitions.** 

I managed to reduce to 58 definitions by removing the recursive search on one of the paths. But even with 58 definitions, the extension breaks. 

So my conclusion so far is: **The extension seems to break when it finds more than X (at least 58, but could be 1...) definitions of a namespace.** 

I can't go much further than this, I think it needs to be reviewed somehow, but maybe has something to do with multiple definitions not being handled correctly... 

**edit**: To clarify, when nothing is working, and I peak the definition, it happens to show 50+ definitions. And when the extension is working, and I peak the definition, it is always only 1 definition. But I literally mean everything stops working on that given file, not just the namespace itself.

**Comment by sean-mcmanus** [comment]
I'm OOF on Friday, but someone else on our team maybe be able to follow up on this to try to get a repro. If Go to Definition is returning a lot of bogus results, that is usually a sign that the IntelliSense-based Go to Definition has failed and it's falling back the tag parser based definitions found in the global symbol database without any IntelliSense-based verification.

**Comment by dbersan** [comment]
> I'm OOF on Friday, but someone else on our team maybe be able to follow up on this to try to get a repro. If Go to Definition is returning a lot of bogus results, that is usually a sign that the IntelliSense-based Go to Definition has failed and it's falling back the tag parser based definitions found in the global symbol database without any IntelliSense-based verification.

Yes, however I think it is _ok_ to have multiple definitions of a namespace, because many places declare the same namespace, not a single one. Maybe the extension wasn't coded to handle this use case? 

edit: Actually, I see that if I include something like `#include <string>`, and then type `std`, it gives me around 630 definitions, but the intelisense still works fine. I'm not sure then what is the issue. 

![image](https://user-images.githubusercontent.com/25873377/90230732-4b2d5700-de1a-11ea-8bf0-9ec612302e18.png)

**Comment by maetulj** [comment]
I am also experiencing the same problems while also using ROS. The intellisense is either not working (no tooltip) or showing all possible matches in the whole repo (not context aware). Output show nothing (set to Information).
The problems only happens with _0.30.0-insiders2_, going back to _0.29.0_ resolves the problems.

**Comment by dbersan** [comment]
I managed to circumvent the intellisense problem using **CMake Tools** intellisense. 

However, I'm still having the issue that headers can't be found, even though their folders are clearly included on the `includePath` variable in `c_cpp_properties.json`. It's crazy to me that it is that it is that difficult to look for files inside a folder. 

**edit**: I saw now that the error message on the missing header was: 
```bash
#include errors detected based on information provided by the configurationProvider
```

and the configuration provider was set to: `"configurationProvider": "ms-vscode.cmake-tools"` on the `c_cpp_properties.json`.  However, it states in their documentation that: 

> CMake Tools currently supports Microsoft’s cpptools extension. If the cpptools extension is installed and enabled, then configuring your project will attempt this integration automatically.

So it should be able to find the headers using the `c_cpp_properties.json`. But it doesn't. Without CMakeTools intellisense doesn't work at all, so it's really the C/C++ extension the root problem. CmakeTools for some reason can't find the paths so I will check with them

**Comment by sean-mcmanus** [comment]
@maetulj It sounds like you're hitting a different issue, because the original issue reproed with 0.29.0 still. Does your logging indicate crashing? Is there a particular file that has these issues? I'll see if I can get a repro.

@dhiegomaga Yes, if you're using CMake, then using CMake Tools is recommended for configuration (our team maintains that extension, although different people work on it usually). But it sounds like there might be an issue with CMake Tools finding the paths, and therefore IntelliSense might not be fully operating.

**Comment by dbersan** [comment]
> @maetulj It sounds like you're hitting a different issue, because the original issue reproed with 0.29.0 still. Does your logging indicate crashing? Is there a particular file that has these issues? I'll see if I can get a repro.
> 
> @dhiegomaga Yes, if you're using CMake, then using CMake Tools is recommended for configuration (our team maintains that extension, although different people work on it usually). But it sounds like there might be an issue with CMake Tools finding the paths, and therefore IntelliSense might not be fully operating.

I managed to get the whole thing working after configuring the CMakeLists.txt file correctly. Previously one of the source files were not having intellisense, and that was fixed after adding the source file as a library target... 

I assumed CMake Tools would look inside the **c_cpp_properties.json** for the include header path, and that's why I thought there was a bug. It's not so clear from the documentation that they don't actually consider those paths... 

What do you think could be done so people don't go through the same as me? I didn't use the tools the best way possible, but they also failed to "guide" me intuitively to use them properly, I would say. Took me a lot of time to understand it.

**Comment by sean-mcmanus** [comment]
When configurationProvider is used, the includePath is only used as a fallback for source files not handled by the configuration provider...not sure if that's documented anywhere. I didn't see it at https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference .

We have received other feedback in regards to configuration being difficult. I don't fully understand the issues you hit -- let us know if you have suggestions for improving the configuration experience or documentation.

**Comment by bobbrow** [comment]
It looks like this issue has been resolved.  Please let us know if there is anything else we can do to help.  We have considered turning CMake Tools on by default for new projects and also even bundling that code into this extension.  We're not 100% sure which direction we'll take on this, but it is definitely on our minds.

**Comment by Acwok** [comment]
Same issue here with ros autocompletion.  
Switching `"cppStandard": "gnu++14"` to `"cppStandard": "c++14"` in the `.vscode/c_cpp_properties.json` should do the trick.
with:
```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic
```
