### ISSUE TITLE
Failed to parse "/.vscode/c_cpp_properties.json": ENOENT: no such file or directory, open '/.vscode/c_cpp_properties.json'

### ISSUE THREAD

**Issue by shameerariff** [microsoft/vscode-cpptools#5966]
I have the visual code version 1.48 with C/C++ (ms-vscode.cpptools) version 0.30.0 insiders2. I do got the same error as follows

Failed to parse "/.vscode/c_cpp_properties.json": ENOENT: no such file or directory, open '/.vscode/c_cpp_properties.json'

The working environment was Ubuntu 20.04 LTS. The visual code application was installed via Snap package manager.

![Screenshot from 2020-08-15 16-35-58](https://user-images.githubusercontent.com/10761850/90311114-7183ed00-df15-11ea-8d96-29d246f05364.png)

**Comment by sean-mcmanus** [comment]
I'm not able to repro the issue. @Colengms @michelleangela Is anyone else able to repro this?

@shameerariff Are you able to workaround the issue by opening a folder? If you do Help->Toggle Developer Tools are you able to see a call stack? If you checkout https://github.com/microsoft/vscode-cpptools/tree/release and do Launch Extension, you may be able to debug the issue to see what is causing the unexpected failure (note: this approach will only work if 0.29.0 also repros the bug).

**Comment by sean-mcmanus** [comment]
Also, does the issue repro with 0.29.0, i.e. after changing C_Cpp.updateChannel to "Default"?

**Comment by shameerariff** [comment]
@sean-mcmanus Yes it is

**Comment by sean-mcmanus** [comment]
Okay, this is the only report we've heard about this and we're unable to repro it, so there may be something usual with your setup or settings.

Did you try opening a folder?
