### ISSUE TITLE
[lldb][Mac] When attaching to MS.VSCode.CPP.Extension.darwin lldb seems to terminate the process

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode-cpptools#597]
Repro:
1. Enable logging
2. Attach to a debug MS.VSCode.CPP.Extension.darwin with lldb

Notice: 
lldb on attach is sending <-gdb-exit after library load for some reason, which is terminating the process. Seems to be an issue with lldb. Can debug with GDB on Mac.

Reported by: @sean-mcmanus

**Comment by sean-mcmanus** [comment]
Let us know if any users are hitting this (we hit this on our 2 Macs for some reason).

**Comment by pieandcakes** [comment]
We have not encountered this anymore.
