### ISSUE TITLE
Suggestion/support ticket: Programmatically run vscode command from 'vscode' module outside of extension

### ISSUE THREAD

**Issue by djuleayo-embroker** [microsoft/vscode-cpptools#5970]
## Intro

I wrote some code generators. What I'd like to have is spec ----generate---> doc & test & code
so these are in sync as much as possible. Some applications are largely defined by models and there it would be useful.

## What I want
It would be *really reaaaally*  useful to have vscode commands at disposal in my code generators.
These are some ways I see it can be done and have semi/tried:
* extract the module provided for extensions - oh lord I didn't succeed - the one that is noted in onsite docs - 
```import vscode from 'vscode'```
* redirect user input - EPIPE right away.

## Suggestions??
Is there any way to programmatically run editing(formmating) and searching commands of vscode module provided to extensions

**Comment by michelleangela** [comment]
@djuleayo-embroker 

This is a feature request for VS Code client. Please report the request at https://github.com/Microsoft/vscode/issues
