### ISSUE TITLE
"count" autocompletes instead of "cout" when I type <cou>.

### ISSUE THREAD

**Issue by jaaahhhvin** [microsoft/vscode-cpptools#5971]
**Type: LanguageService**
Autocomplete error.

**Describe the bug**
- OS and Version: Windows: Windows 10 1903
- VS Code Version: 1.48.0
- C/C++ Extension Version: 0.29.0
- C++ Compliler:  g++ (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
- Other extensions you installed (and if the issue persists after disabling them): Python Intellicode and CodeRunner
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The workspace is multiple c++ files. There are also .exe files in the directory for the compiled files. This occurs on every instance of a C++ file. This issue does not persist after disabling the c++ extension.  

**Steps to reproduce**

1. Go to any c++ file.
2. Type 'cou'
3. Press tab.
4. See the extension autocomplete cou**n**t instead of cout.

**Expected behavior**

The extension autocompletes cout, after I type 'cou' and tab.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 2020-08-16, 12:26:40 a.m.
Version: 0.29.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\####\Desktop\##############\Part1\Chap5-7\examples\referenceInt.cpp ]:
    C:\USERS\####\DESKTOP\############\PART1\CHAP5-7\EXAMPLES\REFERENCEINT.CPP
Translation Unit Configurations:
[ C:\Users\####\Desktop\#######\Part1\Chap5-7\examples\referenceInt.cpp ]:
    Process ID: 10012
    Memory Usage: 54 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.26.28801\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.26.28801\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: msvc-x64
Total Memory Usage: 54 MB

```
</details>

**Screenshots**
![count](https://user-images.githubusercontent.com/15025146/90326406-0a3a5d00-df56-11ea-9adb-b7a03d50d948.png)

**Additional context**

Is there any way for me to remove 'count' from the C++ autocomplete, since I never use it?

**Comment by sean-mcmanus** [comment]
count is std::count (http://www.cplusplus.com/reference/algorithm/count/). So it's "by design" and there's no way to remove it. The iostream library would have to not define std::count.
