### ISSUE TITLE
If i press Shift+Alt+F it is not formatting the project please see the issue

### ISSUE THREAD

**Issue by Gurkarm** [microsoft/vscode-cpptools#5972]
[Type:](url) General

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by chengyongru** [comment]
maybe you can try ctrl+shift+i
:smile:

**Comment by Colengms** [comment]
Hi @Gurkarm .  I'm not able to reproduce a problem with a simple example, so there may be something about your scenario or environment that is required to repro the problem.  Could you provide:
* The version of the extension you are using (is it 0.29.0, or 0.30.0-insiders2?)
* The version of VS Code you are using.  (Is it insiders?)
* Some code that reproduces the issue.  Perhaps there is something within that code that is causing the formatter to crash.
* Any relevent `C_Cpp` settings.  Are you using the default formatter (clang-format), or vcFormat?
* Do you have any other extensions that might be trying to provide formatting that we might be conflicting with?  (Can you repro without any other extensions enabled?)

Could you also enable debugging logging using `"C_Cpp.loggingLevel": "Debug"`, and provide the output of the C/C++ channel for the repro?
