### ISSUE TITLE
Couldn't find a debug adapter descriptor for debug type 'cppdbg' (extension might have failed to activate)

### ISSUE THREAD

**Issue by JonJust** [microsoft/vscode-cpptools#5975]
I am using VSCode to develop homebrew for the Game Boy Advance. Everything was working fine until I opened VSCode one day and the debugger stopped working. 

Whenever I go to run and debug my code, this error pops up, "Couldn't find a debug adapter descriptor for debug type 'cppdbg' (extension might have failed to activate)". Sometimes, the game I am working on will pop up on the emulator before the I get the error message, and be able to play. Other times, the error message pops up and the emulator doesn't even load the game. Regardless, I am unable to use breakpoints or anything along those lines.

Note: I do have ms-vscode-cpptools installed and active in my VSCode, and have reloaded VSCode several times now to no avail.

I used a popular tutorial to configure my JSON to load the code into a GBA emulator.

My Launch.json looks like this:

```
{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "gdb-debug", 
            "postDebugTask": "stop emulation",
            "serverLaunchTimeout": 10000,
            "stopAtEntry": true,
            "program": "${workspaceFolder}/${workspaceFolderBasename}.elf",
            "MIMode": "gdb",
            "externalConsole": true,
            "cwd": "${workspaceFolder}",
            "targetArchitecture": "arm",
            "miDebuggerServerAddress": "localhost:2345",
            "windows": {
                "miDebuggerPath": "C:/devkitPro/devkitARM/bin/arm-none-eabi-gdb.exe",
                "setupCommands": [
                    {
                    "description": "Enable pretty-printing for gdb",
                    "ignoreFailures": true,
                        "text": "file ${workspaceFolder}/${workspaceFolderBasename}.elf -enable-pretty-printing"
                    }]
            },
            "osx":{
                "miDebuggerPath": "/opt/devkitPro/devkitARM/bin/arm-none-eabi-gdb",
                "setupCommands": [
                    {
                    "description": "Enable pretty-printing for gdb",
                    "ignoreFailures": true,
                        "text": "file ${workspaceFolder}/${workspaceFolderBasename}.elf -enable-pretty-printing"
                    }]
            },
        }
    ]
}
```

### Platform and Versions

- **Operating System**: Windows 10
- **C/C++**: v0.29.0
- **VSCode Version**: 1.48.0

### Other Notes/Information
I hope I did a decent job of outlining the problem, I am newer to forum posts like this. If there is any more information needed I would be pleased to update the post.

Edit for people of the future: The templates that I am working with are provided by Jamie D Stewart, with his repository listed [here
](https://github.com/JamieDStewart/GBA_VSCode_Basic). The video series he has documenting the basics of GBA development are can be found [here](https://youtu.be/Rj0lf46iljc).

**Comment by WardenGnaw** [comment]
The error message [`Couldn't find a debug adapter descriptor for debug type`](https://github.com/microsoft/vscode/blob/c233bf87bcf1bf1794a6aae62b01a09506b67d72/src/vs/workbench/api/common/extHostDebugService.ts#L423) comes from VS Code itself. 

However, the extension should activate on [`onDebugResolve:cppdbg`](https://github.com/microsoft/vscode-cpptools/blob/5d97af0fc139f1c4260473c7f6102d8e001af4ed/Extension/src/main.ts#L463) or if you open a c or cpp file. 

Could you make sure you touch a c or cpp file before trying to debug, and if so do you see the same error message?

**Comment by JonJust** [comment]
> 
> 
> The error message [`Couldn't find a debug adapter descriptor for debug type`](https://github.com/microsoft/vscode/blob/c233bf87bcf1bf1794a6aae62b01a09506b67d72/src/vs/workbench/api/common/extHostDebugService.ts#L423) comes from VS Code itself.
> 
> However, the extension should activate on [`onDebugResolve:cppdbg`](https://github.com/microsoft/vscode-cpptools/blob/5d97af0fc139f1c4260473c7f6102d8e001af4ed/Extension/src/main.ts#L463) or if you open a c or cpp file.
> 
> Could you make sure you touch a c or cpp file before trying to debug, and if so do you see the same error message?

Hi there!

By "touch a c file before trying to debug", do you mean click on the .c file that I am trying to debug before running? If so I did that and the issue persists.

Thanks!

**Comment by WardenGnaw** [comment]
Activating an extension is on VS Code. I have opened an issue there: https://github.com/microsoft/vscode/issues/104874

**Comment by jingzhengli** [comment]
Hi, How to solve this problem?

**Comment by prabhurajpatil634** [comment]
@WardenGnaw ,

I am facing the same issue as stated in the title of this thread.

**Platform and Versions**
Operating System: Ubuntu 24.04
C/C++: v1.21.6
VSCode Version: 1.91.1

Please suggest how to resolve the same

**Comment by tunmaker** [comment]
Hello,

i had the same issue, first i thought its the qt c++ extension but it got fixed after i installed the C/C++ vscode extension ms-vscode.cpptools using install [from vsix ](https://github.com/microsoft/vscode-cpptools/releases) because i use VS Code - OSS
or simply from [extension marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) if you can find it
i think the c++ debugging need that extension or they assume you have it [Using C++ on Linux in VS Code](https://code.visualstudio.com/docs/cpp/config-linux)
OS: ArchLinux
VS Code : 1.107.1 x64
