### ISSUE TITLE
Compiler Extension  under clang results in intellisense errors

### ISSUE THREAD

**Issue by jlandess** [microsoft/vscode-cpptools#5976]
**Type: LanguageService**

template<typename CharT, CharT ...String> constexpr LD::TypeString<String...> operator""_ts() noexcept
{
    //constexpr static CharT data[] = { String..., 0 };
    //static_assert(SpecialString::IsValidString(data), "not a valid string");
    return LD::TypeString<String...>();
}

![image](https://user-images.githubusercontent.com/1755496/90434493-812d3e00-e09b-11ea-91d6-f07d9df4e4c6.png)

https://github.com/jlandess/LandessDevCore/blob/master/Primitives/General/typestring.hpp is the offending file

Simply getting IntelliSense errors from the above stated user literal.

OS:>Linux x64 5.4.0-7634-generic
VS Version 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
Cmake: 0.0.17
Cmake Tools: 1.4.1
It's being done in a Graphical environment with no networking.
It's a single workspace and a single project

It should compile under cmake but still retain intellisense errors.

![image](https://user-images.githubusercontent.com/1755496/90435809-9014f000-e09d-11ea-9861-ba0586facdf5.png)

 -->
<details>
  <summary><strong>Logs</strong></summary>

```
![image](https://user-images.githubusercontent.com/1755496/90435783-84292e00-e09d-11ea-9d7d-2e0a0bb7b2b7.png)
```
</details>

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @jlandess .  In this case, it looks like our IntelliSense is reflecting the language rules related to user-defined literal operators.

https://en.cppreference.com/w/cpp/language/user_literal

> If the literal operator is a template, it must have an empty parameter list and _can have only one template parameter, which must be a non-type template parameter pack with element type char_ (in which case it is known as a numeric literal operator template)

> _or a non-type template parameter of class type_ (in which case it is known as a string literal operator template) (since C++20)

We try to support compiler-specific language extensions, but we do not actually use the same front end compiler as clang.  If clang is accepting this code, it may be a bug in clang that it is not adhering to these rules in the C++ spec regarding the declaration of user-defined literals.

**Comment by Colengms** [comment]
I'm going to close this as by-design.  If you feel strongly that this should work differently, we could open an issue against VS, and let them consider it.  (The C/C++ Extension for VS Code shares code for IntelliSense with VS).
