### ISSUE TITLE
Update license for use with non-VS Code distros (vscodium, headmelted, code-server, etc.)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5980]
@sean-mcmanus Pleeeeease update the licence :smiley:. VS code having a permissive license means people can do their own thing that upstream might not be interested in (e.g. independently packaging it for a distro) but it's a shame that we can't then use some of these standard extensions with it.

_Originally posted by @alexdewar in https://github.com/microsoft/vscode-cpptools/issues/2506#issuecomment-675393223_

**Comment by sean-mcmanus** [comment]
From the comments in regards to arm/aarch64 in https://github.com/microsoft/vscode-cpptools/issues/429 and https://github.com/microsoft/vscode-cpptools/issues/2506 it seems like there should be some sort of solution to address the case of users who want to use a local ARM machine.

The debugger disables itself and may have reason to have a stricter license than the language service component.

Wouldn't be necessary if VS Code would release for Linux ARM: microsoft/vscode#6442 and microsoft/vscode#1031

**Comment by shuaixr** [comment]
Please update the licence.I only have raspberry 4 and slow laptop(worse than raspberry.Thanks for your work.

**Comment by bobbrow** [comment]
We are working with our legal team to evaluate our options.

**Comment by bobbrow** [comment]
We won't be making changes to our license agreements, but we were able to make progress on ARM/ARM64 versions of VS Code. 😃 

Check it out!
https://github.com/microsoft/vscode/issues/6442#issuecomment-691111406

**Comment by sean-mcmanus** [comment]
Yeah, I tried it and it works.
