### ISSUE TITLE
ARM release has a dependency on glibc 2.27 (doesn't work with Ubuntu 16 or Debian 9)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#5984]
I tried out the insiders build.  It is crashing and I see these errors:
```
/home/byu/.vscode-server/extensions/ms-vscode.cpptools-0.30.0-insiders/bin/cpptools: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /home/byu/.vscode-server/extensions/ms-vscode.cpptools-0.30.0-insiders/bin/cpptools)
/home/byu/.vscode-server/extensions/ms-vscode.cpptools-0.30.0-insiders/bin/cpptools: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/byu/.vscode-server/extensions/ms-vscode.cpptools-0.30.0-insiders/bin/cpptools)
```

My arm system is running Ubuntu 16.04.  I believe (could be wrong) this is limited to libc-2.23.  Any suggestions?  Will this be limited to newer libc versions?

_Originally posted by @jgoeders in https://github.com/microsoft/vscode-cpptools/issues/429#issuecomment-675780402_

**Comment by sean-mcmanus** [comment]
@jgoeders Thanks for letting us know. I'll look into it.

**Comment by sean-mcmanus** [comment]
We built our binary using Debian Buster, which uses glibc 2.28, so Ubuntu 20 would work, but Ubuntu 16 and 18 won't.

I see Ubuntu 18 ARM builds available, which have a glibc 2.27 dependency that we could possibly build against, but I don't see an Ubuntu 16 ARM build -- how did you get Ubuntu 16 for ARM?

**Comment by jgoeders** [comment]
For context, the board I am using is a Xilinx PYNQ board (so not a raspberry PI board like most people)

I believe the Linux image was built using the files available at http://ports.ubuntu.com/ubuntu-ports/dists/bionic/ which seem to have armhf file.

**Comment by sean-mcmanus** [comment]
As of now, it's looking like we probably won't support Ubuntu 16 for ARM/aarch64 due to low usage (or this issue gets more upvotes). But we plan to support Ubuntu 18 (possibly with 0.30.0-insiders4 if 0.30.0-insiders2/3 don't work).

**Comment by jgoeders** [comment]
OK, Ubuntu 18 sounds reasonable.  Thanks for the quick followup.

**Comment by lucascheuer** [comment]
> 
> 
> As of now, it's looking like we probably won't support Ubuntu 16 for ARM/aarch64 due to low usage (or this issue gets more upvotes). But we plan to support Ubuntu 18 (possibly with 0.30.0-insiders4 if 0.30.0-insiders2/3 don't work).

I wanted to confirm that with 0.30.0-insiders2 the intellisense doesn't work with Ubuntu 16 on ARM (odroid xu4). Debugging does work. Thanks for the development!

**Comment by sean-mcmanus** [comment]
We're tracking Ubuntu 18 support with https://github.com/microsoft/vscode-cpptools/issues/5993 .

**Comment by sean-mcmanus** [comment]
Ubuntu 16 OS on ARM will be supported in our next Insiders release...even Ubuntu 14 and CentOS 7, i.e. we take glibc 2.17 dependency like our other Linux binaries.

**Comment by Misery42** [comment]
> We built our binary using Debian Buster, which uses glibc 2.28, so Ubuntu 20 would work, but Ubuntu 16 and 18 won't.
> 
> I see Ubuntu 18 ARM builds available, which have a glibc 2.27 dependency that we could possibly build against, but I don't see an Ubuntu 16 ARM build -- how did you get Ubuntu 16 for ARM?

I am glad that it will run with glibc 2.17 soon!

But just want to mention why i have a limited system.
I am using Revolution Pi from https://revolution.kunbus.de/ wich is running Debian Stretch.

Thank you!

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 .

**Comment by jgoeders** [comment]
Thanks @sean-mcmanus!  This release preview seems to be working well on our platform.
