### ISSUE TITLE
C_cpp_properties cppStandard Does Not Make Intellisense Use the Standard

### ISSUE THREAD

**Issue by joec58** [microsoft/vscode-cpptools#5985]
**Type: LanguageService**

IntelliSense for C++17 standard

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.48
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): No other C++ extensions
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

Setting c_cppProperties.json -> cppStandard to "c++17" does not set IntelliSense for C++17 

**Steps to reproduce**

Set up vscode according to procedures in [Using C++ on Linux in VS Code](https://code.visualstudio.com/docs/cpp/config-linux).

_c_cpp_properties.json_
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "${default}",
            "compilerArgs": []
        }
    ],
    "version": 4
}
```

_tasks.json_
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
_test_code.cpp_
```c++
#include <filesystem>
#include <iostream>

using namespace std;

namespace fs = std::filesystem;

int main()
{
    fs::path root{"/"};
    fs::path dir{"var/www/"};
    fs::path index{"index.html"};

    fs::path pathToIndex = root / dir / index;

    bool pathExists{fs::exists(pathToIndex)};
    if (pathExists)
        cout << "Yeah, path " << pathToIndex << " exists\n";
    else
        cout << "Nope, path " << pathToIndex << " doesn't exist.\n";
    return 0;
}
```
After Terminal -> Run Build Task:
- IntelliSense indicates errors (red squiggly lines) under `filesystem` and all uses of `fs`.
- The following is my terminal output:
```shell

> Executing task in folder FecForms: /usr/bin/g++ -g /testing/test_code.cpp -o /testing/test_code <

/testing/test_code.cpp:6:21: error: ‘filesystem’ is not a namespace-name
    6 | namespace fs = std::filesystem;
      |                     ^~~~~~~~~~
/testing/test_code.cpp: In function ‘int main()’:
/testing/test_code.cpp:10:5: error: ‘fs’ has not been declared
   10 |     fs::path root{"/"};
      |     ^~
/testing/test_code.cpp:11:5: error: ‘fs’ has not been declared
   11 |     fs::path dir{"var/www/"};
      |     ^~
/testing/test_code.cpp:12:5: error: ‘fs’ has not been declared
   12 |     fs::path index{"index.html"};
      |     ^~
/testing/test_code.cpp:14:5: error: ‘fs’ has not been declared
   14 |     fs::path pathToIndex = root / dir / index;
      |     ^~
/testing/test_code.cpp:16:21: error: ‘fs’ has not been declared
   16 |     bool pathExists{fs::exists(pathToIndex)};
      |                     ^~
/testing/test_code.cpp:16:32: error: ‘pathToIndex’ was not declared in this scope
   16 |     bool pathExists{fs::exists(pathToIndex)};
      |                                ^~~~~~~~~~~
The terminal process "/bin/bash '-c', '/usr/bin/g++ -g /testing/test_code.cpp -o /testing/test_code'" terminated with exit code: 1.
```

**Expected behavior**
IntelliSense should not indicate errors with the code and it should build and run cleanly.

I later discovered that by manually adding "-std=c++17" to the args list in task.json, then again Run Build Task, IntelliSense does not display errors in the code and it compiles with no errors.

Either the cppStandard setting in c_cpp_properties.json should update the tasks.json for the correct argument or there should be a note in the setup instructions that the manual update is required.

**Comment by sean-mcmanus** [comment]
Yeah, tasks.json is for building (a mechanism built-in to VS Code) and c_cpp_properties.json is for IntelliSense (added by our extension) and they don't share any settings between them. The task type "shell" is generic and there's no way for our extension to know what a user would want us to update in tasks.json when c_cpp_properties.json changes...a more likely approach to unifying build and IntelliSense settings would be to create a new task type whose settings would be used for IntelliSense (so c_cpp_properties.json settings would be ignored, similar to what happens when compileCommands or configurationProvider are set), but we don't have plans to implement that yet.

The page for filing documentation request changes is at https://github.com/microsoft/vscode-docs/issues . You could file an issue there, or I could file one for you.

**Comment by bobbrow** [comment]
> The task type "shell" is generic and there's no way for our extension to know what a user would want us to update in tasks.json when c_cpp_properties.json changes...a more likely approach to unifying build and IntelliSense settings would be to create a new task type whose settings would be used for IntelliSense (so c_cpp_properties.json settings would be ignored, similar to what happens when compileCommands or configurationProvider are set), but we don't have plans to implement that yet.

#5659 gets us closer to being able to share information between `c_cpp_properties.json` and `tasks.json`

**Comment by joec58** [comment]
Thanks.
I filed documentation request [#3953](https://github.com/microsoft/vscode-docs/issues/3953). Should I close this issue?

**Comment by sean-mcmanus** [comment]
Sure, I'll close it -- we may create a new issue on further tasks.json/c_cpp_properties.json mapping if we can figure out a design for that later on.
