### ISSUE TITLE
debugger for C

### ISSUE THREAD

**Issue by shuangma1990** [microsoft/vscode-cpptools#5988]
Type: Debugger

Hello VS Code Team! 
I've followed the tutorial (https://code.visualstudio.com/docs/cpp/config-clang-mac) for running and debugging C++ code. I wonder is there a tutorial on configuring VS Code for C? Are the set ups (launch.json and tasks.json files) the same for C?
I appreciate your help!

Regards,

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment]
The setup is similar, you will need to use a C compiler in your `tasks.json`. The `launch.json` will be the same.
