### ISSUE TITLE
If the VSCode doesn't support rename with cpp?

### ISSUE THREAD

**Issue by imhuay** [microsoft/vscode-cpptools#599]
I can rename in JavaScript with F2 but not in cpp. Whether the cpp languang server doesn't support rename now? 
If so, will this feature be implemented in the future?
And, the Issue #386 is still exist.

**Comment by sean-mcmanus** [comment]
We don't support rename now. We might in the future, but it's not on our schedule currently.

**Comment by kranzj** [comment]
I also very much miss this feature. Would be great to have!

**Comment by horvay** [comment]
It doesn't duplicate the functionality at all, but one thing I do that works for most cases is:

highlight the name
hold down ctrl + d until everything is selected
type the new name

**Comment by bobbrow** [comment]
We are tracking this with #296
