### ISSUE TITLE
Intellisense error with anonymous namespaces

### ISSUE THREAD

**Issue by uecasm** [microsoft/vscode-cpptools#5990]
Issue Type: <b>Bug</b>

1. Open https://github.com/uecasm/vscode_anon
2. Run "Reset IntelliSense database" and "Rescan Workspace" (just to make sure it's a clean slate).
3. Open meow_fwd.h
4. Hover the mouse over both `_Meow` and `Meow`.
5. Bug#1: `Meow` shows `<error_type>` in its tooltip.
6. Open anon.cpp.
7. Bug#2: a "problem" has now appeared on meow_fwd.h (if it doesn't, just switch back and forth a few times; it doesn't show up until you've looked at both files): it now says `_Meow is ambiguous`.

This is slightly different from what I'm seeing in a larger project (haven't been able to MCVE that yet), where with a similar sort of declaration structure I also see an error squiggle at point of usage `identifier "Meow" is undefined` -- despite successfully compiling and successfully being able to "Go to Definition" on that exact same symbol that's showing the error squiggle.  For that issue, a temporary workaround seems to be to F12 the symbol and go back, and then the squiggle disappears for a little while -- but it comes back again after doing the same thing on another symbol.

----

Extension version: 0.29.0
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz (20 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (9.05GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Debian/home/developer/software/ --remote=wsl+Debian|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|Dev Container: Docker from Docker|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz (20 x 3311)|
|Memory (System)|24.81GB (18.03GB free)|
|VM|0%|
</details>

**Comment by uecasm** [comment]
Another way to trigger the same problem is to edit meow_fwd.h to:

```
struct _Meow;
typedef _Meow Meow;
```

In this state (reset and rescan to confirm) it will show the "ambiguous" squiggle on the typedef `_Meow` immediately, with no need to switch to different files first.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. Sorry for the delay in responding. The bug is with our IntelliSense code shared with VS. I've filed a bug at https://developercommunity.visualstudio.com/content/problem/1170470/c-intellisense-incorrectly-reports-a-class-a-ambig.html .

**Comment by bobbrow** [comment]
This appears to be fixed in the latest version of the extension.
