### ISSUE TITLE
C/C++; C++ IntelliSense --> IntelliSense not working in VSCode on Raspberry Pi 4

### ISSUE THREAD

**Issue by Creepyc1345** [microsoft/vscode-cpptools#5997]
**Type: LanguageService**

Hi, I am pretty new to Programming and just started to use what I learned about C on my Raspi 4 with 4GB of RAM.
I installed VSCode on it because I wanted to have the benefit of IntelliSense etc. for faster Programming.
I installed the C/C++ extention made by Microsoft, restartet Code and my Pi, but Intellisence still wouldn't work.
Then i also installed C++ IntelliSense, still nothing.
My Code installation is fresh and blank exept for these two extetions.
I checked about 2 hours to find if somebody has a solution for this Problem, but coudn't find anything.
Would really apreciate your help.

Creepyc

**Describe the bug**
- OS and Version: everything as new as it gets. made every update possible
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. get VSCode on Raspi 4
2. Try using extentions

**Expected behavior**

IntelliSense to work

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
VS Code doesn't have build for ARM or Raspberry Pi. Are you using headmelted?

**Comment by Creepyc1345** [comment]
Yes, i'm using headmelted.
I'm sorry for my late answer, but I can only access my GitHub from my PC at work.

**Comment by sean-mcmanus** [comment]
@Creepyc1345 What version of the C/C++ extension does it show is available? From https://github.com/headmelted/codebuilds/issues/128 , I think the headmelted distro is too out of date to run the latest version of our extension (in addition to our license  currently not allowing it). And ARM binaries are currently only available from our offline vsix at https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders3 (not 0.29.0).

Currently, we only support running on Raspberry Pi via VS Code running on a non-ARM device and remoting into the Raspberry Pi. We encourage you to upvote microsoft/vscode#6442 . It is currently number 24 on VS Code's list of upvotes and behind releasing for ipad and Windows store.

**Comment by Creepyc1345** [comment]
@sean-mcmanus As you already said, I was trying to install 0.29.0. Sadly I am not able t connect via Remote because of the networking done in the company I work at, but i will be shure to talk to them. I also upvoted the post you linked, would be really nice to see an offical Support for ARM processors.
Before I close this I want to thank you for your support, as you probally can tell this is my first time interacting with github. Because of that I have one last question, because I have still problems navigating mysself thruh github. Is there an version of VS / VS code planed to release on Android, because it would be really nice to have a good IDE to also use on the go if you haven't got a Laptop with you. :)

**Comment by sean-mcmanus** [comment]
There's a VS Code issue on Android at https://github.com/microsoft/vscode/issues/94243 .

**Comment by Creepyc1345** [comment]
@sean-mcmanus Thanks again for your support. I am going to close the issue now. :)

**Comment by bobbrow** [comment]
@Creepyc1345 if you are doing GitHub development, there is a new service under development called "CodeSpaces" that lets you use VS Code in a browser on any device/tablet you choose.  https://github.com/features/codespaces
