### ISSUE TITLE
Clang/LLDB support

### ISSUE THREAD

**Issue by zethon** [microsoft/vscode-cpptools#60]
I saw a comment from 2 months ago that the "lldb support is not ready for public consumption" but I could not find any update or anything tracking this. Hence I've opened this issue is hopes that it can be updated when there is an update, or that someone can point me to an update if there is one.

**Comment by delmyers** [comment]
Thanks, zethon, for adding this public request. We are tracking it.

**Comment by zethon** [comment]
Keeping my fingers crossed for this!

**Comment by delmyers** [comment]
@zethon, by the way, what platform are you debugging on (Windows, Linux, or Mac)?

**Comment by jacdavis** [comment]
@zethon. We shipped lldb for mac in our last release. Is this what you were looking for? Are you also looking for lldb on Linux?

**Comment by pieandcakes** [comment]
@zethon Like @jacdavis said, we shipped a version of lldb for OS X with our extension. If you are looking for this for Linux, please comment at let me know. I am closing this issue for now.
