### ISSUE TITLE
compilerPath is squiggled if containing just compiler filename, despite resolving with environment path

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#6006]
In 0.30.0-insiders*, it's now possible to specify just a compiler filename in `compilerPath`.  If the file is resolvable using the current environment paths, it will be used.  However, it's still being squiggled in c_cpp_properties.json.

Fixing this is going to require handling compilerPath differently from other paths in handleSquiggles(), in configurations.ts.

**Comment by sean-mcmanus** [comment]
The related previous PR is https://github.com/microsoft/vscode-cpptools/pull/5965
