### ISSUE TITLE
Command to update references/symbols

### ISSUE THREAD

**Issue by rthier** [microsoft/vscode-cpptools#601]
Sometimes some references are missed because a file was deleted or git merge/rebase was executed.

I looking for a command/feature to update "browse.VC.db" and fixed all references in my code.

**Comment by sean-mcmanus** [comment]
The browse database should already be updated if the deleted/created file is in the workspace root (while our language service is running). Let us know if that is not working. External edits to files should get detected when the workspace is closed/reopened. Does closing/reopening the workspace not work for you? We may be able to add a file system watcher for edits for the deleted/created case so that the workspace reopen isn't required. The only known problem is that files/symbols are not removed from the database when the file is no longer available (i.e. includePath removed) or the file was deleted while VS Code is closed.

**Comment by rthier** [comment]
> The only known problem is that files/symbols are not removed from the database when the file is no longer available (i.e. includePath removed) or the file was deleted while VS Code is closed.

Exactly, when a file was removed the symbols are not removed in browse database.

In my case the temporary files generated by git rebase/merge are in the browse database, even though I reopened the desktop

I think that a command/feature to update this data is a good option. Like a "> C/Cpp: update browse database".

This is possible?

**Comment by sean-mcmanus** [comment]
We're planning to do a "database cleanup" when the workspace is opened to remove files/symbols that no longer exist, so a command to update the browse database won't be needed. Currently, the workaround for this is to manually delete the .browse.vc.db or change the databaseFilename setting.

**Comment by rthier** [comment]
> We're planning to do a "database cleanup" when the workspace is opened to remove files/symbols that no longer exist, so a command to update the browse database won't be needed.

This is good solution, but depends the developer reopen the VS/Project, I don't know if this is intuitive, I prefer a explicit command to do this too, like a update or reset.

> Currently, the workaround for this is to manually delete the .browse.vc.db or change the databaseFilename setting.

I deleted the .browse.VC.db to clean the "old" symbols/references.
This workaround works fine.

**Comment by sean-mcmanus** [comment]
After our fix, a reopen of the workspace shouldn't be necessary, because any file deletion or removal of includePath should cause the files to be removed from the database if VS Code is already open.

**Comment by maroc81** [comment]
What if the file delete/rename happens outside VS Code?  Our team uses subversion so renaming files must be done outside of VS Code.  I've been looking for a way to refresh the symbols manually and this is the first time I've seen instructions to delete the .browse.vc.db.  That did work but a command to refresh could be helpful if the automatic detection can't handle all use cases.

**Comment by sean-mcmanus** [comment]
Yeah, we use a file system watcher, so it should catch the changes if VS Code is running, even if the changes are made outside of VS Code. And if VS Code is not running, it should catch the changes after it starts (the problem is that it doesn't do that now).

**Comment by hungys** [comment]
@sean-mcmanus 

> The browse database should already be updated if the deleted/created file is in the workspace root (while our language service is running). Let us know if that is not working. External edits to files should get detected when the workspace is closed/reopened. Does closing/reopening the workspace not work for you? We may be able to add a file system watcher for edits for the deleted/created case so that the workspace reopen isn't required. The only known problem is that files/symbols are not removed from the database when the file is no longer available (i.e. includePath removed) or the file was deleted while VS Code is closed.

This doesn't work well on my side. Check the following screenshots, the symbol `MemoryIndexedRegion` was actually changed externally, but it still showed up on symbol search panel. Even restarting VS Code, it was still not invalidated and re-analyzed.

![](http://i.imgur.com/MYCuU3A.png)

Press Enter and it will navigate to the wrong line:

![](http://i.imgur.com/ivQNQVb.png)

No `MemoryIndexed` result can be found in the file:

![](http://i.imgur.com/Ekij976.png)

-----

The only way for me to trigger the database update is to force delete `.browse.VC.db` under `/Users/hungys/Library/Application Support/Code/User/workspaceStorage/<...>/ms-vscode.cpptools`.

BTW, I'm on the latest version of VS Code and CPP extension.

**Comment by sean-mcmanus** [comment]
@hungys If your MemoryIndexed is removed from the file while VS Code is not running, the next time VS Code is launched, it should scan the file, see that the timestamp has changed, and reparse the file, removing MemoryIndexed. I tried this on Mac and I'm not able to repro your issue. Can you provide more repro details? Does the behavior I describe work correctly for you on a simple project?

**Comment by hungys** [comment]
@sean-mcmanus 

All changes were made when VS Code is running.

After force deleting the old `.browse.VC.db`, it now works as expected. I'm not sure what's wrong with the language server, so I think it would be nice to have a command for rebuilding the database.

Moreover, I found that sometimes the function signatures shown when hovering on the function name are mixed with the old signature and the new one. (after the signature changes outside of VS Code) It seems that the old signature caches are not invalidated, because it works correctly after restarting VS Code.

**Comment by sean-mcmanus** [comment]
Your post said you restarted VS Code. If VS Code is running, we have file watchers in the workspace, but not outside the workspace, and the file watchers can fail if the OS-limit is hit. However, restarting VS Code should detect that the timestamp is different and re-parse the file (after it get the file search reaches the file).

Anyway, we decided to add a command to rebuild the database for unexpected scenarios (ETA is next month though).

**Comment by bobbrow** [comment]
We just released 0.12.3 which has a command to reset the database.

**Comment by CXX22** [comment]
First, if you're having issues such as this "command 'references-view.refresh' not found", as you can see here, the shortcut for REFRESH must have been assigned to one key and this key won't be functioning when we are typing on VS code.

To resolve this, open your vs code, under file, go to preferences, under preferences, go to keyboard shortcuts:

File -----> Preferences ---> Keyboard shortcuts
an attempt to type in the key you're having issue with would fail.

At the keyboard shortcut, press SHIFT + the particular key you're having issue with, then type Refresh or whatever word you used the affected letter as a shortcut.

Then edit the shortcut, change it from the affected letter to a combination of keys, maybe CTRL+ALT+(any key) or ALT+SHIFT+any key

Please do not use a single key as a shortcut, doing so would make the key not to function in VS code when coding.

If you're still not okay, you can send me a mail on caseyviva1@gmail.com
