### ISSUE TITLE
gdb not loading .gdbinit from cwd set in configuration

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-cpptools#6010]
Type: Debugger

**Describe the bug**
- OS and Version: macOS 10.14.6 (Remote Development on C++ Debian Buster template)
- VS Code Version: 1.48.1
- C/C++ Extension Version: 0.29.0

VS Code C/C++ gdb debugger integration doesn't try to load `.gdbinit` in the working directory/project root like invoking `gdb` from the CLI does.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Just any hello world, with a `.gdbinit` file at the workspace root folder, using a default launch.json.
2. Try to debug it in the CLI using `gdb`, gdb will try to load the `.gdbinit`, will probably warn/error on "auto-load safe-path", but otherwise tries to load the `.gdbinit`
3. Try to debug in VS Code using the default generated `launch.json`, it will not load the `.gdbinit`.

**Comment by RobotCaleb** [comment]
Yes, same on Ubuntu 18.04 with VSCode 1.52.1, C/C++ 1.2.0

I worked around it by setting `launch.json` `setupCommands` to include:
```
{
    "text": "source ${workspaceFolder}/.gdbinit"
},
```

**Comment by daniel-brosche** [comment]
the same principle works slightly modified for remote debugging:

```json
        "postRemoteConnectCommands": [
            {
                "text": "source ${workspaceFolder}/.gdbinit"
            }
        ],
```
