### ISSUE TITLE
[Debuger][Remote SSH]Current working dir is wrong

### ISSUE THREAD

**Issue by lixin-wei** [microsoft/vscode-cpptools#6019]
Type: Debugger

**Describe the bug**
- OS and Version: Client: macOS 10.15.6, Server:  Linux 3.10, with remote development plugin.
- VS Code Version: 1.48.0
- C/C++ Extension Version: v0.30.0-insider2

When I debug in remote ssh mode, I met the following error:
![image](https://user-images.githubusercontent.com/19600697/91116386-d16d5700-e6be-11ea-836b-c43cc3b95fc9.png)

It seems that the current working path(CWD) is wrong. In my case `direct_actor_transport.cc` actually placed in `/home/admin/ray`(the opened project dir), but the error message shows C++ extension try to find it in `/proc/self/cwd` which points to  `/home/admin/`(ssh home dir)

I've reported this issue in vscode-remote-release repo, and they said that you can't assume `/proc/self/cwd` of vscode's process pointing to the project dir. see (<https://github.com/microsoft/vscode-remote-release/issues/2871#issuecomment-679279897>)

Can anyone have a look?

**Additional context**
my launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "GDB Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/home/admin/py3/bin/python",
            "MIMode": "gdb",
            "processId": 81508,
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "miDebuggerPath": "/usr/bin/gdb",
        }
    ]
}
```

**Comment by WardenGnaw** [comment]
How are you building the program you are debugging? GDB provides the location of the symbol for the debug adapter to use and we will return that to VS Code to open. The symbols for the process you are debugging is finding that direct_actor_transport.cc was built in `/proc/self/cwd/src/`.

To work around how the symbols paths are returned, you can use [sourceFileMap](https://code.visualstudio.com/docs/cpp/cpp-debug#_locate-source-files) in your `launch.json` to help fix the debug adapter find where your files. 
E.g.
```
"sourceFileMap": {
   "/proc/self/cwd/src/ray": "/home/admin/ray"
}
```

**Comment by lixin-wei** [comment]
@WardenGnaw Thanks, it works!
