### ISSUE TITLE
[gdb] cannot not open source file with Chinese/Unicode characters in path when debugging

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-cpptools#602]
_From @MagicSong on March 29, 2017 14:22_

- VSCode Version:1.10
- OS Version:ubuntu 16.04 lts

Steps to Reproduce:
I'm a chinese user, so maybe my issue is relative with language support problem.
1.debug a c++ project with cpptool
2.then VS Code reminds me cannot open some file like this:无法打开“PointTransformer.cpp”: 找不到文件(/home/magicsong/346226207346241243/Codes/DataTransform/GeoDataTransformer/PointTransformer.cpp)。In my computer, the file above is located in "/home/magicsong/文档/Codes/DataTransform/GeoDataTransformer/PointTransformer.cpp", does cpptool not support chinese? or something i miss when i debug?

_Copied from original issue: Microsoft/vscode#23575_

**Comment by pieandcakes** [comment]
@MagicSong If you remove the Chinese characters in the path, does it work?

**Comment by magicsong** [comment]
@pieandcakes I still got this error when i change the path.I also change my OS language to English, and rebuild again, it still does not work.

**Comment by pieandcakes** [comment]
@MagicSong So you get the file not found after you change the path? Can you post the updated error when you remove the Chinese characters from the path?

**Comment by magicsong** [comment]
Unable to open 'raise.c': File not found (/build/glibc-9tT8Do/glibc-2.23/sysdeps/unix/sysv/linux/raise.c). After i google, it seems that the debug is OK now because this new error is different from my first error. So it does not work when i have chinese characters in my file path.

**Comment by pieandcakes** [comment]
I've marked this as a bug so we can go investigate and fix the Chinese characters in path issue. Thank you for reporting it.

**Comment by sean-mcmanus** [comment]
What is the new error?

**Comment by pieandcakes** [comment]
@sean-mcmanus Its the first sentence in @MagicSong's last post.

**Comment by sean-mcmanus** [comment]
But that sounds the same as the first error. Both errors are about not being able to open the file.

**Comment by pieandcakes** [comment]
The second error seems like the user is trying to step into library code and doesn't have the source files on their machine so the error is expected. The first is that the path is converting the Chinese characters into a series of numbers which is unexpected and a bug.

**Comment by wu38607** [comment]
@MagicSong  你好，我也碰上了相同的问题，请问问题解决了吗？

**Comment by ygrayson** [comment]
@MagicSong  Are you able to solve the error "Unable to open 'raise.c': File not found (/build/glibc-9tT8Do/glibc-2.23/sysdeps/unix/sysv/linux/raise.c)". I got the same one and coincidentally (or not) I'm also a Chinese user.

**Comment by pieandcakes** [comment]
@ygrayson  that isn't an issue with Chinese users. That is `gdb` stopping in `glibc` code and the debugger returning a source code path of `/build/glibc-9tT8Do/glibc-2.23/sysdeps/unix/sysv/linux/raise.c`. Since you don't have `glibc` source, this is why you get an `"Unable to open"` message.

**Comment by ygrayson** [comment]
@pieandcakes Do I have any way to have the glibc source under the correct directory? My debugger works fine right now without any seg fault or other errors, but do I have any way to solve this error?

**Comment by pieandcakes** [comment]
@ygrayson If you want to have the source for glibc, you can add mappings to it using `"sourceFileMap"`. Otherwise you can just ignore it. Its not a real error.

**Comment by n-p-e** [comment]
I'd like to know how to avoid this bug. If it is something about gdb, is removing Chinese the only solution?

**Comment by pieandcakes** [comment]
@coffee-sgr As far as I know that is the only solution. We have the same problem with any Unicode characters, whether it be Chinese or not. If you find another workaround, please let us know.

**Comment by mxdh** [comment]
@pieandcakes I'm a Chinese user.
It seems that this issue is caused by gdb.
When I run gdb with powershell,it cannot display Chinese characters in path.
When gdb runs in MI mode,it seems that gdb changes Chinese characters into numbers.

**Comment by LOVELIBERTY1314** [comment]
我也遇到了同样的问题，不知道有没有最佳的解决方案了

**Comment by LOVELIBERTY1314** [comment]
> @pieandcakes I'm a Chinese user.
> It seems that this issue is caused by gdb.
> When I run gdb with powershell,it cannot display Chinese characters in path.
> When gdb runs in MI mode,it seems that gdb changes Chinese characters into numbers.

If we ran gdb with cmd,Could it display Chinese charaters in path?

**Comment by mxdh** [comment]
@LOVELIBERTY1314 
Sorry,my English is not good.I am just a middle school student.
Win10 1809 x64,MinGw-w64 8.1.0,when I debug `19_1_递归.cpp`,after I use `b 21`,it displays `19_1_.cpp`.

**Comment by pieandcakes** [comment]
@mxdh @LOVELIBERTY1314 the issue is with `gdb` when it runs in MI mode does not support any Unicode characters. There needs to be a fix within `gdb` itself.

**Comment by mxdh** [comment]
@pieandcakes Has anyone reported this issue to gnu?

**Comment by pieandcakes** [comment]
@mxdh https://sourceware.org/bugzilla/show_bug.cgi?id=14903

**Comment by CodingByteFly** [comment]
I am glad to receive for your reply. Thank you very much. Let’s wait for the soultion of gnu.
                                                                                                Best wishes to you!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Pierson Lee <notifications@github.com>
发送时间: Sunday, May 5, 2019 12:30:16 AM
收件人: Microsoft/vscode-cpptools
抄送: LOVELIBERTY; Mention
主题: Re: [Microsoft/vscode-cpptools] cannot not open source file with Chinese/Unicode characters in path when debugging (#602)


Closed #602<https://github.com/Microsoft/vscode-cpptools/issues/602>.

―

**Comment by Kiswelrg** [comment]
and even i got into the debug process, the breakpoints don't seem to work. so when will gdb supports non-ascii characters on file names.

**Comment by BillKek** [comment]
Try solution with `lldb-mi` as replacement of `gdb`. I have success on `eclipse IDE` with bat-file:
```
chcp 65001
SET PATH=C:\msys64\clang32\bin;C:\msys64\usr\bin;%PATH%
lldb-mi.exe %*
``` 
and with installed `mingw-w64-clang-i686-lldb` and `mingw-w64-clang-i686-lldb-mi` packages of windows-based  `msys2` system. I assume that `VSCode` works in a similar way relative to `eclipse`.
