### ISSUE TITLE
Custom configuration browse.path is still used after a configuration provider extension is disabled

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6024]
It's using the cached configuration browse.path...not sure if there's a way to check if the configurationProvider is disabled or not. I saw this in the logging at https://github.com/microsoft/vscode-cpptools/issues/6012#issuecomment-679966603 .

**Comment by bobbrow** [comment]
This fix for this should be to remove the 'configurationProvider' setting from `c_cpp_properties.json` or clear the `C_Cpp.default.configurationProvider`.  We don't know how long it takes for a given provider to load so we make no determinations as to when to mark a provided configuration as stale.
