### ISSUE TITLE
graphics.h supported? 

### ISSUE THREAD

**Issue by dhruvrawat101** [microsoft/vscode-cpptools#6027]
I was trying to use graphics.h by adding it manually.But getting error related to update include path ,Squiggles are disabled ignoring the fact graphic file is just inside the folder . Tried including using this way -#include"C://Users/lenovo/Desktop/CG/graphics.h" , still getting the same error.

Is graphic.h not supported or I am doing wrong in including the file

**Comment by sean-mcmanus** [comment]
Try adding `"C://Users/lenovo/Desktop/CG"` to your "includePath" property in c_cpp_properties.json and then use `#include <graphics.h>`.

**Comment by dhruvrawat101** [comment]
> Try adding `"C://Users/lenovo/Desktop/CG"` to your "includePath" property in c_cpp_properties.json and then use `#include <graphics.h>`.

I have already done this step, still same issue.

**Comment by sean-mcmanus** [comment]
What is the exact error message that is being shown? Can you provide the output from C/C++: Log Diagnostics, in particular, does that CG path appear in the "Includes" output?

**Comment by dhruvrawat101** [comment]
> What is the exact error message that is being shown? Can you provide the output from C/C++: Log Diagnostics, in particular, does that CG path appear in the "Includes" output?

![log_error](https://user-images.githubusercontent.com/51899618/91459982-edcae880-e8a4-11ea-84ca-72e60e111e59.JPG)
I have attached the error message.Also, the cpp_property json picture
![cpp_property_1](https://user-images.githubusercontent.com/51899618/91460396-62058c00-e8a5-11ea-9021-5e134c11b3ba.JPG)
![cpp_property_2](https://user-images.githubusercontent.com/51899618/91460417-67fb6d00-e8a5-11ea-9eb3-da44e1092263.JPG)

**Comment by sean-mcmanus** [comment]
bits/c++config.h not being found means your system include paths are misconfigured. You'll want to remove any system include paths from your includePath setting and make sure the compilerPath is correct. If you provide the output of the Includes section of running the C/C++: Log Diagnostics command I could see what exactly is being used.
