### ISSUE TITLE
Cannot find "C:\\mingw32\\bin\\gcc.exe".

### ISSUE THREAD

**Issue by tariqawni** [microsoft/vscode-cpptools#6029]
how can i solve this i am a new in vscode and trying to learn c++ Cannot find "C:\\mingw32\\bin\\gcc.exe".
![Untitled](https://user-images.githubusercontent.com/50630306/91234695-78440880-e73c-11ea-8501-8082f5fdc37a.jpg)

**Comment by sean-mcmanus** [comment]
Does `C:\mingw32\bin\gcc.exe` exist? You need to use some mingw installer to install it (possibly at a different location).

**Comment by tariqawni** [comment]
i install it and add it in path my system is windows 10 64bit and i download a system installer vscode and this mingw http://www.mingw.org/

**Comment by bobbrow** [comment]
I thought for sure that that installer put it in c:\mingw, not c:\mingw32 by default.

**Comment by tariqawni** [comment]
yes its in in c:\mingw, not c:\mingw32 .

**Comment by tariqawni** [comment]
ok what i should to do could u tel me step by step

**Comment by sean-mcmanus** [comment]
I don't understand. Are you able to compile? Do you think this is a bug with our extension?

**Comment by tariqawni** [comment]
of course no but i am saying i am a new in c++ i start to learn this language today and some people they told me the best program to learn is vscode and when i download it i got this error so i ask to help

**Comment by sean-mcmanus** [comment]
Have you seen the docs at https://code.visualstudio.com/docs/cpp/config-mingw ?

**Comment by tariqawni** [comment]
no this is the first time and thank you so much i fix it with this new Mingw i delete the first one i use it from my system and when i download this it seem working good now thank you so much  http://mingw-w64.org/doku.php/download/mingw-builds

**Comment by tariqawni** [comment]
i solve my issue thank you all and thanks to bobbrow its help.
