### ISSUE TITLE
Color changing 

### ISSUE THREAD

**Issue by JaynishMandalia** [microsoft/vscode-cpptools#6030]
Hello there, I've been using VS code about a year now and new update is not so good. In c++ whenever we define string class or vector the color coding is not changing as it was changing before update (Keep this in mind) it looks so irritating please let me know about this extension what am I supposed to do with it as soon as possible........ And one more thing it's not showing me the suggestions for string and vector and all so please help out with this problem.

**Comment by sean-mcmanus** [comment]
What version of the C/C++ extension are you using? What version is behaving correctly for you? VS Code has the "Install Another Version..." option for extensions, but you may need to change the autoUpdate setting to false to prevent an autoupdate to the latest version.

Do you see any "Failed" messages in the C/C++ logging?

By "color coding" not changing do you mean the C_Cpp.enhancedColorization setting, i.e. semantic colorization? Can you provide an example of code that you expect to be colored?

Suggestions not working for string/vector implies that IntelliSense is not working.

**Comment by JaynishMandalia** [comment]
I am currently using the version for C/C++ extension is v 0.29.0 and yeah as you said to turn off the auto update i'll do that but I just what to know why it's happening and when i get the update from extension i simply just update that and this problem is occur. 


For example when we make any new vector <int> v; so this word "vector" should change to light green or dark green and the "int" should change to dark blue and "v" should change to light blue like that as it was changing in older version I am satisfied with older version but not with new version so do something please.....


Thanks for replying sir.....

**Comment by sean-mcmanus** [comment]
Do you know what version of VS Code was working for you? 0.29.0 was released over a month ago.

Is your C_Cpp.enhancedColorization setting set to "Enabled"?

I'm not reproing the issue:

![image](https://user-images.githubusercontent.com/19859882/91608851-29a89100-e92b-11ea-84cd-82609d2add68.png)

**Comment by JaynishMandalia** [comment]
Yes this version v0.29.0 is running very well for all the codes but new version is not that much good so... 

And yeah as you are showing me in the picture this is the exact thing which i want....
And it's available in v0.29.0 so i have disabled the auto update for this extension. Please let me if you have some solution with new extension.

Thanks for helping me out sir,

**Comment by JaynishMandalia** [comment]
Hello there, this is the problem with new extension sir
![Problem](https://user-images.githubusercontent.com/63401286/91651243-ee7f9c80-eaa7-11ea-9923-5293b77ea591.png)


In this color are not changing in as you have shown above in your picture.....
Can you help me out from this forever....

**Comment by JaynishMandalia** [comment]
> eproing the issue:

Yes it is enabled

**Comment by Colengms** [comment]
@Sjaynish Could you please provide the following information to help us investigate this issue?
* Enable the `"C_Cpp.loggingLevel": "Debug"` setting, and provide all output to the C/C++ channel leading up to and including the repro.
* Run the `C/C++: Log Diagnostics` command after the repro, and provide the output.
* The contents on your `c_cpp_properties.json`
* Any `C_Cpp` settings specified in `settings.json`

I suspect that lack of semantic colorization may be due to another issue, such as a failure in the IntelliSense process.

**Comment by michelleangela** [comment]
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.
