### ISSUE TITLE
IntelliSense shows an error that is no longer an error in C++17

### ISSUE THREAD

**Issue by Leo843** [microsoft/vscode-cpptools#6039]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04.5
- VS Code Version: 1.48.2
- C/C++ Extension Version: v0.30.0-insiders3

The following errors are highlighted by IntelliSense, however they should not appear since I set IntelliseSence cppStandard to c++17. 

```
include <cstdio>

class Bar{
public:
  template<typename T>
  void foo(int);

  template<> // IntelliSense: "explicit specialization is not allowed in the current scope"
  void foo<float>(int){puts("Hello World!");}

  template<> // IntelliSense: "explicit specialization is not allowed in the current scope"
  void foo<double>(int){puts("Bye!");}
};

int main()
{
    Bar b;
    b.foo<float>(0);
    b.foo<double>(0);
    return 0;
}
```

.vscode/c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/home/leo/.local/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Expected behavior**
Previous errors should not be highlighted by IntelliSense when using the C++17 standard since the syntax is valid.

At the bottom of this page https://en.cppreference.com/w/cpp/language/template_specialization there is a link to a defect report related to the error (https://wg21.cmeerw.net/cwg/issue727).

> An explicit specialization may be declared in any scope in which the corresponding primary template may be defined

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've forwarded the issue to the VS team (shared parser code): https://developercommunity.visualstudio.com/content/problem/1165995/c-intellisense-gives-the-incorrect-error-explicit.html .
