### ISSUE TITLE
C/C++ 0.29.0 clang-format not supported BitFields

### ISSUE THREAD

**Issue by amosran** [microsoft/vscode-cpptools#6042]
Issue Type: <b>Bug</b>

C/C++ 0.29.0
.clang-format files "AlignConsecutiveBitFields", This feature is not enabled.

Extension version: 0.29.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       M 640  @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.80GB (5.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Which version of clang-format supports that? We only bundle clang-format version 10.0. You could install a newer version and set the C_Cpp.clang_format_path to the newer version to use that as a workaround until we update to a newer version.

**Comment by amosran** [comment]
https://clang.llvm.org/docs/ReleaseNotes.html
ah, This is Clang 12.0.0 a new feature. It seems that the current version is not supported, I hope we can try to support later, thanks!

**Comment by sean-mcmanus** [comment]
The current clang release is 10.0.1 still: https://releases.llvm.org/download.html . There's a 11.0 rc2 prerelease at https://github.com/llvm/llvm-project/releases . Version 12 is still in development.

**Comment by Colengms** [comment]
Hi @amosran . You could install LLVM 12 on your system.  If clang-format is in the env path, and newer than our bundled version, we should use it instead.  Or, you could specify it using the `C_Cpp.clang_format_path` setting.

We are tracking upgrading the bundled version of clang-format using https://github.com/microsoft/vscode-cpptools/issues/6434 .  Closing this one.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders
