### ISSUE TITLE
VSCode Ccpp extension doesnt format anymore

### ISSUE THREAD

**Issue by Meoli96** [microsoft/vscode-cpptools#6043]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Pop_OS 20.04
- VS Code Version: 1.48.2
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): C/C++  Themes(Yes)
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The extension doesnt format my code anymore (that meaning it was formatting my code properly before), doesnt matter if im in a workspace or not. I set in the settings.json a custom .clang-format in the working folder, but the extension doesnt use it nor does format the document at all. Changing the output of the extension to debug shows these lines when hitting Ctrl + Shift + I (Format document shortcut):

```

textDocument/formatting: path/to/file.c (id: 304)
Formatting input:

int function (int var) {
var = 3;
return var;
}
Formatting document: path/to/file.c
terminating child process: 8361
```
but again, nothing changes.

EDIT: 
Done some testing, and after VSCode needs to be restarted due to settings change, it does break the autoformat thingy. The issue presents itself even if I restart VSCode before applying the format settings.

To return to a working formatter VSCode needs to be reinstalled and the .config/Code folder removed. Unistalling and reinstalling C_cppTools doesnt solve the issue.

Using another default formatter (https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) does fix the issue.

**Steps to reproduce**

Settings.json:
`"editor.defaultFormatter" : "ms-vscode.cpptools",
    "C_Cpp.clang_format_style": "file",
    "C_Cpp.clang_format_fallbackStyle": "LLVM",
    "C_Cpp.clang_format_path": "path/to/.clang-format",`
and other stuff about UI customization.

1.Insert an option that requires VSCode to restart. Restart.
2. Format document
3. Cry

**Expected behavior**

To have a working formatter. Please explain if im making something in the wrong way.

<details>
  <summary><strong>Logs</strong></summary>

```
Version: 0.29.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c11",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "clang-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /mnt/d/Shared/Coding/C_C++/LSP/Exercises/5_Adv_IO/ex5_2.c ]:
    /mnt/d/Shared/Coding/C_C++/LSP/Exercises/5_Adv_IO/ex5_2.c
[ /mnt/d/Shared/Coding/C_C++/CLI/CLI.cpp ]:
    /mnt/d/Shared/Coding/C_C++/CLI/CLI.cpp
[ /mnt/d/Shared/Coding/C_C++/LSP/Exercises/5_Adv_IO/test.c ]:
    /mnt/d/Shared/Coding/C_C++/LSP/Exercises/5_Adv_IO/test.c
Translation Unit Configurations:
[ /mnt/d/Shared/Coding/C_C++/LSP/Exercises/5_Adv_IO/ex5_2.c ]:
    Process ID: 8101
    Memory Usage: 11 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=90300
[ /mnt/d/Shared/Coding/C_C++/CLI/CLI.cpp ]:
    Process ID: 8165
    Memory Usage: 28 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/9
        /usr/include/x86_64-linux-gnu/c++/9
        /usr/include/c++/9/backward
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=90300
[ /mnt/d/Shared/Coding/C_C++/LSP/Exercises/5_Adv_IO/test.c ]:
    Process ID: 8195
    Memory Usage: 13 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=90300
Total Memory Usage: 52 MB


```
</details>

**Screenshots**

**Additional context**

**Comment by MeoliNasa** [comment]
Done some testing, and after VSCode needs to be restarted due to settings change, it does break the autoformat thingy. The issue presents itself even if I restart VSCode before applying the format settings. For completeness im editing the Steps to reproduce field.

**Comment by Colengms** [comment]
Hi @MeoliNasa .  Could you enable `"C_Cpp.loggingLevel": "Debug"`, and provide the output to the C/C++ channel leading up to and including the repro?

**Comment by sean-mcmanus** [comment]
It looks like this setting is wrong "C_Cpp.clang_format_path": "path/to/.clang-format". `clang_format_path` is supposed to be a path to the clang_format binary and not the .clang-format file. There is no option to specify a .clang-format file -- it should just be placed in the workspace root or in a parent folder.

**Comment by Meoli96** [comment]
@Colengms Not on my machine rn, i will provide the complete output of the extension asap, but the output about the formatting functionality was the one I included in the description.

@sean-mcmanus It cant be that. I mean, maybe that setting is wrong but it was always set up like that and it worked before. Reformatting the same code in the same folder (and with the same parent folder), with the same format settings, before and after restarting vscode due to settings change leads to different behavior (working the former, not working the latter).

**Comment by Meoli96** [comment]
@sean-mcmanus Actually removing that line fixed the issue. Im really sorry. The odd thing is that as i said that option was always there and it did never cause harm. Thank you very much for the assistance and im really sorry to have wasted your time. The issue can be closed.
