### ISSUE TITLE
Cuda completion

### ISSUE THREAD

**Issue by vmiheer** [microsoft/vscode-cpptools#6052]
**Type: LanguageService**

It would be great if cuda completion works with intellisense.

**Describe the bug**
- OS and Version: Windows (Linux remote)
- VS Code Version: 1.48.2
- C/C++ Extension Version: v0.30.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes

**Comment by sean-mcmanus** [comment]
Does the code compile with gcc or clang? Do you have any sample code? Our parser doesn't parse any CUDA-specific code, so it's unlikely to be able to provide completions if there's any non-standard C/C++ code that only compiles with the CUDA compiler.

Our parser would only support GPGPU compute code if it could get added in a future C/C++ standard.

**Comment by DaemonSnake** [comment]
@bobbrow Happy to see a change on that.
I would be interested to help out if it's possible.

**Comment by bobbrow** [comment]
@DaemonSnake thanks for the offer, but unfortunately, this is something that has to be done in the portion of code that is closed-source.

**Comment by bobbrow** [comment]
Actually, moving this to On Deck so that our Feature bot doesn't accidentally close it.

**Comment by Colengms** [comment]
@vmiheer With v1.3.0, we've added IntelliSense support for CUDA.  I believe this issue has been addressed.  If I'm mistaken, please open a new issue on functionality missing from our CUDA support.

**Comment by vmiheer** [comment]
Is there a blog post about how to use it? I trying vscode completion but I don't seem to get autocompletion.

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-49-generic
```

**Comment by vmiheer** [comment]
Okay apparently, cmake compile commands doesn't include absolute path to nvcc, which means intellisense doesn't know where to look for cuda include files. explicit `-I/path/to/cuda/include` makes intellisense work.

**Comment by sean-mcmanus** [comment]
@vmiheer I think the path to nvcc should be on your PATH when you install the SDK -- @Colengms might know more. Simply adding -I may not work 100% because it may be missing other system defines/includes that nvcc would add if we were able to query it.

**Comment by r3cebarnett** [comment]
Piggybacking off of @vmiheer I too am having trouble and editing my includepath didn't help. I'm assuming that I should be able to have intellisense/linting for kernel calls (<<<x,y>>>) and references for threadIdx, blockIdx, etc.

Also I see that the code change references having a language ID of cuda-cpp but I can't seem to add this language ID to "initiate" CUDA intellisense support. Having some documentation on how to get this setup would be awesome.

Thanks :)

**Comment by sean-mcmanus** [comment]
@r3cebarnett What version of VS Code do you have installed? You may need a more recent version.

**Comment by vmiheer** [comment]
Okay correction to my earlier comment:
cmake compile_commands.json does have full path to nvcc. I think if the plugin using compile_commands.json it should look at which nvcc is being used using compile commands than relying on path. Cuda is mostly used in high performance computing world where it's not uncommon to have multiple versions of cuda installed via lmods so I think PATH won't be best place to look for cuda installation (especially if compile_commands are explicitly providing nvcc path). :)

**Comment by r3cebarnett** [comment]
> @r3cebarnett What version of VS Code do you have installed? You may need a more recent version.

@sean-mcmanus, thanks for getting back to me! My version info is as follows:

Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

I'm unable to get any progress on both the Windows side and the Remote Host side to my Linux box (both have NVIDIA HW and CUDA libs).

**Comment by vmiheer** [comment]
@r3cebarnett here's what's working for me:
1. `build/compile_commands.json` file is created by cmake.
2. `ln -s build/compile_commands.json .`
3. Now add `-I /path/to/cuda/include` to all the "commands" in the compile_commands.json.
4. cmake generate `-isystem=somePath` for nvcc compilation commands but intellisense doesn't seem to like it, so replace `=` by space. Now the status bar should show :fire: emoji showing "updating intellisense", pressing `F12` on `#include <cuda.h>` should open cuda.h :smile:.

**Comment by r3cebarnett** [comment]
@vmiheer Is this functionality restricted to projects using CMake? I don't think I'm using the same environment as you, but I'm glad it's working for you :)

**Comment by sean-mcmanus** [comment]
@r3cebarnett Your version appears good. Are you opening a .cu file? That should cause it to open as a "Cude C++" file type.

@vmiheer The path to nvcc in the compile_commands.json is supposed to be used, but I'm guessing one of the arguments being passed is causing that to fail. If you set C_Cpp.loggingLevel to "Debug" and look at the "C/C++" logging it may say what error is occurring. @Colengms Can you try that compile_command.json?

Also, we  handle -isystem<path> but not with an =...we could add handling for the =...not sure if that's valid or not.

**Comment by r3cebarnett** [comment]
@sean-mcmanus I am opening a .cu file, but it defaults to a Plain Text. I had made an association to C++ in the past but I wiped that and tried to reopen it and it's still defaulting to Plain Text. I've tried to manually set the association as well but it seems like that failed silently.

**Comment by sean-mcmanus** [comment]
@r3cebarnett Ah, I see -- you need VS Code Insiders. I thought the CUDA stuff had made into the release VS Code already.

**Comment by r3cebarnett** [comment]
@sean-mcmanus Oh! Well that explains a lot haha! Let me get that installed real quick.

**Comment by vmiheer** [comment]
Okay my bad, let me try out vscode insiders. My cpptools version is `v1.3.1`.
