### ISSUE TITLE
how to compile cpptools and cpptools-srv from source?

### ISSUE THREAD

**Issue by winter-loo** [microsoft/vscode-cpptools#6053]
**Type: LanguageService**

I have managed to run [visual studio code server](https://github.com/cdr/code-server) on redhat 6 with customized gcc version 7.2.0 but failed to install cpptools-linux.vsix(version 0.30.0-insiders3). cpptools and cpptools-srv require greater glibc version which not in redhat 6 system.

Is it allowed users to compile cpptools and cpptools-srv from source ? And how?

**Comment by michelleangela** [comment]
The Typescript source of the extension is open source, while the executables cpptools and cpptools-srv are closed, therefore cannot be compiled externally. When the Typescript source is compiled or run in dev mode, it downloads the corresponding executables for that version.
