### ISSUE TITLE
'const __auto_type' gives mystery 'must be a placeholder for the complete type' error

### ISSUE THREAD

**Issue by yseymour** [microsoft/vscode-cpptools#6054]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS 10.15.6
- VS Code Version: 1.48.2
- C/C++ Extension Version: v0.30.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

`test.c`
```
typedef union { int foo; } foo;
int main() {
	const __auto_type f = (foo){ 1234 };
}
```

Gives the error: `'__auto_type' must be a placeholder for the complete type of the variable (not for a component of that type)`.  Removing `const` resolves the error.

gcc and clang both compile the code without error.

I had difficulty working out whether this error is being produced by the extension, or some other tool.  Googling the message did not uncover anything.  Hopefully someone can work it out.

My `c_cpp_properties.json` looks like:
```
{
	"configurations": [
		{
			"name": "Linux",
			"includePath": [
				"${workspaceFolder}",
				<snip>
			],
			"defines": [
				<snip>
			],
			"compilerPath": "/usr/bin/gcc",
			"cStandard": "c11",
			"cppStandard": "c++14",
			"intelliSenseMode": "gcc-x64"
		}
	],
	"version": 4
}
```

**Comment by sean-mcmanus** [comment]
I've reported a bug against our parser shared with VS at https://developercommunity.visualstudio.com/content/problem/1168897/incorrect-c-intellisense-error-in-gcc-mode-auto-ty.html .

A potential workaround is to add these lines somewhere in the TU:
```
#ifdef __INTELLISENSE__
    #pragma diag_suppress 2717
    #pragma diag_suppress 144
#endif
```

**Comment by bobbrow** [comment]
This is fixed in the latest version of the extension.
