### ISSUE TITLE
Add setting to disable reference/document highlighting

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6056]
Mentioned as part of https://github.com/microsoft/vscode/issues/100530 .

The simplest implementation would be similar to `C_Cpp.autocomplete`. Implementing a TypeScript documentHighlight provider instead of relying on the LSP would be another more complicted approach (e.g. C_Cpp.formatting).

**Comment by wolf99** [comment]
Yes please!

**Comment by wolf99** [comment]
Oh! 
What kind of an idea is that? 
Close good requests based on "likes"? Is this Facebook?
SMH.

**Comment by bobbrow** [comment]
If you don't want any highlighting, have you tried setting the `"editor.occurrencesHighlight"` setting to `"false"`?  I think the VS Code team added this a while ago and it works for me.
