### ISSUE TITLE
Allow configuring the terminal that is used for debugging when externalConsole=true

### ISSUE THREAD

**Issue by baldvin-kovacs** [microsoft/vscode-cpptools#6061]
Issue Type: <b>Feature Request</b>

Please allow configuring which terminal is used for debugging (I'm using cppvsdbg) when externalConsole is true.

That would allow to implement a terminal which doesn't disappear right after the program finished. 

Note: there are bugs directly about the terminal disappearing right away:  [Don't immediately close the external console window when the program ends #5899](https://github.com/microsoft/vscode-cpptools/issues/5899) , or [Add an option to prevent external console from closing after debugging is finished #805](https://github.com/microsoft/vscode-cpptools/issues/805)

Also note, that the workarounds offered in those bugs are not great, to say the least, for the education use case:

When one teaches the basics of C++ to a child, for example, then one of the earliest programs to try is

std::cout << "Type something: ";
std::cin >> a_string;
std::cout << "You typed this: " << a_string << std::endl;

This program simply "does not work", as far as the child is concerned. When externalConsole:false, then you can't type in the input, when externalConsole:true, then you don't see the output.

In the ideal case, this program could be executed by hitting F5, without any extra cognitive load. The offered workarounds, like adding std::cin >> at the end, or a breakpoint at the end are extra cognitive load, which may make it impossible to work with it, depending of the age and personality of the child.

Extension version: 0.29.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by luchongk** [comment]
I have the same request, but for different reasons. I want to be able to use Windows terminal as external console for debugging.

Ideally the c++ extension should use as external console the same console that is configured in "terminal.external.windowsExec".
At the moment that doesn't seem to be the case, and the extension seems to always use cmd for "cppvsdebug" type.

Thanks in advance

**Comment by hostilefork** [comment]
> Ideally the c++ extension should use as external console the same console that is configured in "terminal.external.windowsExec".

That sounds sensible (I thought the same)...and went looking to see if it would be some kind of easy patch.  But what I've found suggests it is not something that VSCode can control.  It comes from the OS launch of the process connecting to the default console.  Visual Studio has the same issue.

See here:

https://stackoverflow.com/questions/12602411/use-custom-console-for-visual-studio-console-application-debugging
https://conemu.github.io/en/DefaultTerminal.html

See also this issue in Windows Terminal:

https://github.com/microsoft/terminal/issues/492

**But one thing VSCode can do here is to add a note in the documentation for externalTerminal saying it must use the OS default terminal on Windows, and that this is beyond the control of the extension.**
