### ISSUE TITLE
Feature request: auto add declaration/implementation of functions

### ISSUE THREAD

**Issue by Host48** [microsoft/vscode-cpptools#6066]
Is it possible to get the auto insert declaration/definition feature that exists in Visual Studio? 
![image](https://user-images.githubusercontent.com/25237346/91898645-539be380-ec9c-11ea-94b5-8a4967a8dc49.png)
Thank you.

**Comment by sean-mcmanus** [comment]
This is being tracked by https://github.com/microsoft/vscode-cpptools/issues/664. You could upvote that issue.

**Comment by amir9480** [comment]
@H0stman 
For now, you can use my extension

https://marketplace.visualstudio.com/items?itemName=amiralizadeh9480.cpp-helper
