### ISSUE TITLE
Intellisense window wrong syntax colouring

### ISSUE THREAD

**Issue by Host48** [microsoft/vscode-cpptools#6067]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows
- VS Code Version: 1.48.2
- C/C++ Extension Version: 0.29.0
- Other extensions you installed (and if the issue persists after disabling them): No other extensions
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

Intellisense window is not showing colours of theme altered in editor.semanticTokenColorCustomizations.

**Steps to reproduce**

1. Override colours in editor.semanticTokenColorCustomizations.
2. Hover your mouse over some code so the intellisense window pops up.

**Expected behavior**

The intellisense window should display correct syntax colours.

<details>
  <summary><strong>Logs</strong></summary>

```
No logs
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/25237346/91900392-ea699f80-ec9e-11ea-982b-4f4a02d8c1ce.png)
![image](https://user-images.githubusercontent.com/25237346/91900436-fead9c80-ec9e-11ea-8946-70d3bbe3254e.png)

**Additional context**
None needed

**Comment by Colengms** [comment]
Hi @H0stman .  The C/C++ Extension implements a DocumentSemanticTokensProvider, which provides VS Code with semantic tokens for C/C++ files.  That appears to be working correctly.  I believe what you are seeing is VS Code behavior.  Semantic Token support is relatively new in VS Code, and it may not currently extend to hover windows  I'd suggest opening an issue in [the VS Code repo](https://github.com/microsoft/vscode).

**Comment by bobbrow** [comment]
This is not something that the C++ extension can fix.  We suggest opening an issue in the VS Code repository if you would like to see this fixed.
