### ISSUE TITLE
g++ is not recognized in vscode

### ISSUE THREAD

**Issue by asharhasan20** [microsoft/vscode-cpptools#6069]
g++ is not recognized in vscode . couldn't find g++in build task
<img width="558" alt="Capture" src="https://user-images.githubusercontent.com/70622383/91934350-cd69b680-ed08-11ea-8543-188326ebb74d.PNG">

**Comment by sean-mcmanus** [comment]
We have some docs at https://code.visualstudio.com/docs/cpp/config-mingw#_build-helloworldcpp . I think you need to provide the full path to g++.exe.

**Comment by elahehrashedi** [comment]
the kind is defined as "bbuild" which is why it is not showing up in the "build" tasks.
In the latest version, we can use "g++.exe" command without providing the full path.
