### ISSUE TITLE
Compiler argument in C/C++ configuration does not propagate to tasks.json for g++ compiler

### ISSUE THREAD

**Issue by MumblingFumbler** [microsoft/vscode-cpptools#6080]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 7
- VS Code Version: 1.48.2
- C/C++ Extension Version: 13.515.576
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Compiler argument in C/C++ configuration does not propagate to tasks.json for g++ compiler

**Steps to reproduce**

1.  Follow directions in the "Hello, World" example found here:
https://code.visualstudio.com/docs/cpp/config-mingw
2. Add a line to the helloworld.cpp
#include "(a header file not in the workspace or system include path).h"
3. Add the path to the above header file in win32 c++ IntelliSense  configuration under "Include path"
   (IntelliSense can now find the header file and its contents)
4. Add the path to the win32 c++ configuration under "Compiler arguments"
   -I"(path to header file)"
5. Select Terminal | "Configure Default Build Task"
6. Select "C/C++: g++.exe build active file"
7. View tasks.json.
8. NO -I"(path to header file)" APPEARS IN COMPILER ARGS!!! THE SOURCE FILE WON"T COMPILE!!!
9. Select Terminal | "Configure Default Build Task"
10. select "C/C++: gcc.exe build active file"
11 View tasks.json.
12. THE I"(path to header file)" APPEARS IN COMPILER ARGS! AND THE SOURCE FILE COMPILES CORRECTLY!!!

**Expected behavior**

I expect the source file to compile correctly whether I am using g++ or gcc

<details>
  <summary><strong>Logs</strong></summary>

```
 Executing task: ""C:\Program Files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin\g++.exe" -g "...\testinclude.cpp" -o "...\testinclude.exe"" <

...\testinclude.cpp:5:10: fatal error: xxxx.h: No such file or directory
 #include <xxxx.h>
          ^~~~~~~~~~~
compilation terminated.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
The C/C++ build tasks do no auto-populate -I based on the includePath values added in c_cpp_properties.json. A similar request was made at https://github.com/microsoft/vscode-cpptools/issues/5985 . We could potentially add that in the future (after we check in https://github.com/microsoft/vscode-cpptools/pull/5659 ).
