### ISSUE TITLE
Doxygen - Comment truncated if the character ‘\0’ appears in the comment

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6084]
If a Doxygen comment has the character '\0', then the text after it is truncated. Also reproduces on VS.

VS feedback ticket: 
https://developercommunity.visualstudio.com/content/problem/1081005/%E6%B3%A8%E9%87%8A%E4%B8%AD%E5%A6%82%E6%9E%9C%E5%87%BA%E7%8E%B0%E4%BA%86%E5%AD%97%E7%AC%A6-0-%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%AD%97%E7%AC%A6-0-%E4%B9%8B%E5%90%8E%E7%9A%84%E6%B3%A8%E9%87%8A%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA.html

![image](https://user-images.githubusercontent.com/38734287/92273806-e4431100-eea0-11ea-873a-b1693090cf87.png)

**Comment by spacemonkd** [comment]
Can I check this? @sean-mcmanus sir

**Comment by sean-mcmanus** [comment]
@devabhishekpal That is implemented in our shared code with VS, not in our our open source TypeScript.

**Comment by spacemonkd** [comment]
Okay sir

**Comment by IshFx** [comment]
Hello,

Is there a chance this will be fixed?

**Comment by michelleangela** [comment]
This is not fixed yet. The code for this is common between the C++ extension and C++ language service on Visual Studio. So once the issue (tracked by [feedback ticket](https://developercommunity.visualstudio.com/content/problem/1081005/%E6%B3%A8%E9%87%8A%E4%B8%AD%E5%A6%82%E6%9E%9C%E5%87%BA%E7%8E%B0%E4%BA%86%E5%AD%97%E7%AC%A6-0-%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%AD%97%E7%AC%A6-0-%E4%B9%8B%E5%90%8E%E7%9A%84%E6%B3%A8%E9%87%8A%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA.html)) is addressed for Visual Studio, the C++ extension will be able to port over the fix.

**Comment by IshFx** [comment]
Alright, thank you for the clarifications.

**Comment by sergey-kashlikov** [comment]
When this will be fixed? Still a problem

**Comment by michelleangela** [comment]
This feature is a shared component of Visual Studio C++ language server and VS Code C++ Extension. The status of this issue is driven by the feedback ticket on Visual Studio https://developercommunity.visualstudio.com/content/problem/1081005/%E6%B3%A8%E9%87%8A%E4%B8%AD%E5%A6%82%E6%9E%9C%E5%87%BA%E7%8E%B0%E4%BA%86%E5%AD%97%E7%AC%A6-0-%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%AD%97%E7%AC%A6-0-%E4%B9%8B%E5%90%8E%E7%9A%84%E6%B3%A8%E9%87%8A%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA.html

When the issue is fixed on Visual Studio, we'll be able to port over the fix to the C++ Extension.

**Comment by michelleangela** [comment]
>But I don't understand the original request on the Visual Studio ticket, seems like its super low prioriy. But entire doxygen view is almost not working due to this bug.

@sergey-kashlikov 
The original request on the Visual Studio ticket says that the usage of `\0` or any character proceeded with `\` in a comment truncates the Doxygen comment in the tooltip display.

The priority of a bug is determined by number of upvotes and also ranked against other current issues and projects and available resources.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.2
