### ISSUE TITLE
Stopped due to shared library event during WSL debugging

### ISSUE THREAD

**Issue by crispyricepc** [microsoft/vscode-cpptools#6088]
## System info
- OS and Version: Windows 10 2004, WSL2 Ubuntu 20.04
- VS Code Version: 1.48.2
- C/C++ Extension Version: v0.30.0-insiders4
- Other extensions installed: None

## Description
Launching using cppdbg on Linux causes gdb to hang, with the final message: `Stopped due to shared library event (no libraries added or removed)`

## To reproduce
Create new hello world project:
```cpp
#include <iostream>

int main() {
    std::cout << "Hello World" << std::endl;
    return 0;
}
```
Add `launch.json` and `tasks.json` based on `g++` presets:

`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": false
                }
            ],
            "preLaunchTask": "C/C++: g++ build active file",
            "miDebuggerPath": "/bin/gdb"
        }
    ]
}
```
'tasks.json':
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
Pressing launch causes the debug box at the top to appear like so:
![image](https://user-images.githubusercontent.com/16229426/92467495-a3613a00-f1c9-11ea-95cf-fb4640e030c5.png)
But the terminal is empty and hanging.

The debug console provides this:
![image](https://user-images.githubusercontent.com/16229426/92467606-cc81ca80-f1c9-11ea-8e2f-a5914db43d14.png)

Pressing any of the buttons in the debug box shows the message: "timeout after 1000 ms"
![image](https://user-images.githubusercontent.com/16229426/92467726-0226b380-f1ca-11ea-8bde-6b6db17f6236.png)

**Comment by WardenGnaw** [comment]
Can you add the following to your `launch.json` and share the output?
```
"logging": {
                "engineLogging": true,
                "traceResponse": true
            }
```

**Comment by crispyricepc** [comment]
> Can you add the following to your `launch.json` and share the output?
> 
> ```
> "logging": {
>                 "engineLogging": true,
>                 "traceResponse": true
>             }
> ```

Sorry I managed to fix this on my own by making a backup of my /home folder and reinstalling WSL and Ubuntu. Definitely not the solution anyone experiencing this needed.

If it helps I think it had something to do with corrupted debug symbols, since running in the `gdb` command line causes a failed to load error, while executing using `./` seems to work fine
