### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Jebug69** [microsoft/vscode-cpptools#6089]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `0.30.0-insiders4`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Jesse Ben-Emu\ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
There's not enough info. No ms-vscode.cpptools-unresponsive.cpuprofile.txt .
