### ISSUE TITLE
Add a log message explaining why "Open file" error squiggles are disabled

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6091]
I was having the same issue. Try using the "open folder" option when you first open a window, instead of opening a random file. It then started to work for me.

_Originally posted by @yoberner in https://github.com/microsoft/vscode-cpptools/issues/5045#issuecomment-688041962_

**Comment by yoberner** [comment]
Not sure exactly why it was happening, spend a few hours trying to fix it with no avail. But, when I would right click on a C file and click open in VSCode, it would not have the squiggles (although it did have some autocomplete), however, when first opening a VSCode window and then a folder and file from within the window, it then worked.

**Comment by sean-mcmanus** [comment]
@yoberner That is "by design", but we could do a better job explaining that error squiggles are intentionally disabled in the "Open File" scenario, i.e. we could log a warning message.

**Comment by yoberner** [comment]
Got it! Good to know. Thanks!!

**Comment by renyhp** [comment]
>  error squiggles are intentionally disabled in the "Open File" scenario

@sean-mcmanus is that a default which is possible to override in any way, or is it just impossible to have squiggles in this scenario? (Also, out of curiosity, whatever the answer to my question, may I ask why?)

**Comment by sean-mcmanus** [comment]
@renyhp It's not possible for users to override that currently. We'd have to make changes to enable that.

**Comment by Colengms** [comment]
It looks like we have https://github.com/microsoft/vscode-cpptools/issues/3171 tracking enabling squiggle for single files.

We'll use this issue to track explaining what's going on in single-file mode, as the title suggests.
