### ISSUE TITLE
Add instructions on cpptools memory profiling to the wiki

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6092]
@sean-mcmanus please provide memory profiling instructions and I'll run it on my system. The link you sent deals only with CPU profiling. Could not understand which perf command/args I need to use to profile memory. If there's another tool you would like me to use, please let me know.

_Originally posted by @arnonshp in https://github.com/microsoft/vscode-cpptools/issues/6035#issuecomment-688780697_

**Comment by sean-mcmanus** [comment]
@arnonshp We haven't written instructions on memory profiling yet. We had an internal task tracking that.

**Comment by michelleangela** [comment]
Closing as dup of https://github.com/microsoft/vscode-cpptools/issues/6093
