### ISSUE TITLE
Add docs for memory profiling

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#6093]
Add info on memory profiling to https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues .

Visual Studio "memory usage" tool is not available for profiling extension process
~~For Windows, use Visual Studio performance analysis tools~~
~~https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage-without-debugging2?view=vs-2019~~

For macOS, the Instruments tool can do memory profiling using the "allocations" template. However, it cannot attach to the cpptools or cpptools-srv processes as these processes are considered system apps.

For Linux, the Perf tool has the "mem" command to profile memory usage. However, this is limited to Intel CPUs, and it doesn't seem to work on Linux running on a VM.
http://www.brendangregg.com/perf.html#Usage

**Comment by michelleangela** [comment]
After researching tools to use for profiling memory usage of running processes on macOS, Linux, and Windows, it was determined that there were no tools that provide straightforward method for users to profile the extension's processes.

Instead, to mitigate this issue on macOS and Linux, a logic will be added to shut down an IntelliSense Engine process when it reaches a certain amount of memory usage. https://github.com/microsoft/vscode-cpptools/issues/6230
