### ISSUE TITLE
[macOS Catalina] Debugger sometimes doesn't start

### ISSUE THREAD

**Issue by IvanAli** [microsoft/vscode-cpptools#6096]
Type: Debugger

**Describe the bug**
- OS and Version: macOS Catalina 10.15.6
- VS Code Version: 1.47.3
- C/C++ Extension Version: 0.30.0

Clicking the green "Debug" button used to work fine before upgrading from Mojave to Catalina.
What happens now: Clicking the Debug button attempts to launch the debugging process, yet nothing happens. After a few unsuccessful tries, the debugging process finally launches.

At first, after a few unsuccessful tries, I would get a pop-up asking whether I would allow VSCode to launch the debug adapter (actually, I don't quite remember what process it was). 
Thought maybe doing "sudo DevToolsSecurity --enable" could solve this. The message did stop popping up, but the retries were still necessary.

Here's my launch.json: (probably the only interesting setting is `"console": "integratedTerminal"`
```
{
      "type": "lldb",
      "request": "launch",
      "name": "Debug",
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args": [],
      "cwd": "${fileDirname}",
      "console": "integratedTerminal",
    }

```

**Comment by WardenGnaw** [comment]
The C++ extension does not own `"type": "lldb"`. It is owned by https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb

If it is for this extension, it is:
```
"type": "cppdbg",
"miMode": "lldb"
```
