### ISSUE TITLE
C/C++ IntelliSense gives "has no suitable copy constructor" and other errors but compiles with all compilers

### ISSUE THREAD

**Issue by runner0353** [microsoft/vscode-cpptools#6097]
**Type: LanguageService**

![image](https://user-images.githubusercontent.com/36179001/92540155-4ec7c880-f276-11ea-8bca-832946ce96f6.png)

**Describe the bug**
- OS and Version:Ubuntu 18.04
- VS Code Version:
- C/C++ Extension Version:0.29.0
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).This kind of bug must shut down the computer. Then restart it to disappear

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Are you able to provide a small sample of code that repros the problem? The example in your screenshot may require additional code (type info) in order to reproduce.

**Comment by runner0353** [comment]
![image](https://user-images.githubusercontent.com/36179001/92542868-8df91800-f27c-11ea-8cdd-a60b9ea08fd5.png)
![image](https://user-images.githubusercontent.com/36179001/92542917-ac5f1380-f27c-11ea-8b5d-972f942b623e.png)

**Comment by runner0353** [comment]
If you don't mind, I am willing to upload part of the project for you to analyze separately. OK ?

**Comment by michelleangela** [comment]
@runner0353 
Could you also provide the following two logs:
1. Log output from enabling the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
2. Log output from running the command `C/C++: Log Diagnostics`

**Comment by sean-mcmanus** [comment]
Yeah, we still don't have enough repro info from those screenshots. We need an isolated code sample that includes the error line and then all the dependent code that is required for the error to occur. And as Michelle mentioned, info in the logs will help us identify the compiler, intelliSenseMode, etc. used.

**Comment by runner0353** [comment]
Unfortunately, this bug disappeared after I turned on the computer. If this bug happens again I will save the log file, thank you

**Comment by runner0353** [comment]
![image](https://user-images.githubusercontent.com/36179001/93692289-ddb0cc80-fb23-11ea-94c6-01872322bdbc.png)
[log.txt](https://github.com/microsoft/vscode-cpptools/files/5251025/log.txt)
[Tref.txt](https://github.com/microsoft/vscode-cpptools/files/5251027/Tref.txt)
[TrefTest.txt](https://github.com/microsoft/vscode-cpptools/files/5251028/TrefTest.txt)

There is no problem with compilation, but vscode always reports errors.
The error is as shown in the picture
log.txt is the configuration file
Tref.txt is the hpp file
TrefTest.txt is a cpp file
github does not support hpp and cpp types.

**Comment by runner0353** [comment]
@sean-mcmanus

**Comment by sean-mcmanus** [comment]
Thanks a lot for reporting this. I've filed a bug on our shared VS parser at https://developercommunity.visualstudio.com/content/problem/1194246/cc-intellisense-gives-has-no-suitable-copy-constru.html .

**Comment by sean-mcmanus** [comment]
If you didn't know already, this issue should be fixed with the latest release.
