### ISSUE TITLE
IntelliSense does not work on Win10

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#61]
From https://github.com/Microsoft/vscppsamples/issues/52#issuecomment-222711337

_Intellisense only "works" in current file for me. When addressing a struct, the actual struct members are nowhere to be seen. The suggestions that do pop up are completely unrelated._

![intellisense](https://cloud.githubusercontent.com/assets/1297882/15700820/ad59c78c-27d6-11e6-9d48-8352e6ea23ca.gif)

_And as you can see, the search is case sensitive. So not very fuzzy._

_Win10._

**Comment by delmyers** [comment]
@sridmad, was multi-file intellisense added with this release? Does it work for Win10?

**Comment by csholmq** [comment]
Perhaps I have an incorrect expectation of the IntelliSense at this stage. I can list all symbols, but there doesn't seem to be any solid support for e.g. structs.

**Comment by csholmq** [comment]
@delmyers @sridmad 
I believe this is very much connected with https://github.com/Microsoft/vscppsamples/issues/81.

Multi-file "IntelliSense" seems to work now - as in that struct members defined in other files show up. But with no context awareness it's pretty much a dull blade.
