### ISSUE TITLE
no goto definition in Fedora21 with glibc2.20

### ISSUE THREAD

**Issue by Yangnaan** [microsoft/vscode-cpptools#610]
os: fedora21, glibc2.20， version 1.11, only switch to header source avalible，no goto definition item
, i ve check #19 issue, it seems not like that, there is glibc2.20 .
who could help me?

**Comment by Yangnaan** [comment]
i ve uninstall all other plugins, problem still exist.

**Comment by sean-mcmanus** [comment]
Is your OS 32-bit? The language service process Microsoft.VSCode.CPP.Extension.linux only works on 64-bit Linux.

**Comment by Yangnaan** [comment]
well, it is true, i m using 32-bit OS, many thanks!

**Comment by bobbrow** [comment]
We're tracking 32-bit Linux support with issue #424

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
