### ISSUE TITLE
Use the source file's workspace configuration when opening a header in a multi-root workspace

### ISSUE THREAD

**Issue by thiloschulz** [microsoft/vscode-cpptools#6103]
I have been getting the dreaded "#include errors detected..." message in my workspace when opening some .h files and was investigating why this might occur. Apparently, when opening a .h file, VS Code always attempts to find a .c file which can be used as context for the test compilation shortly after cpptools/getSemanticTokens.

It now happens, that in my project the .c file used by VSCode might reside in a different project root than the .h file. When compiling the .c file, however, the c_cpp_properties.json from the .h file's project root is used.
This fails, because the chosen .c file must be compiled with the c_cpp_properties.json from its respective project root, which has different include paths or might even use a different compiler.

If using the .c file project root's c_cpp_properties.json is not acceptable, pray consider using a nearly empty dummy .c file which only includes the .h file under test.

**Comment by sean-mcmanus** [comment]
This sounds "by design" currently. It will use the configuration of the .c file if you open that file first, but if you open a header in a different workspace folder that doesn't have an active TU already, it will use the header's configuration. We haven't added the ability to switch TUs/configurations used by a header.

**Comment by sean-mcmanus** [comment]
But it seems like it would be better to use the configuration from the source file's workspace when it finds that.

**Comment by thiloschulz** [comment]
> It will use the configuration of the .c file if you open that file first, but if you open a header in a different workspace folder that doesn't have an active TU already, it will use the header's configuration.

Yes, that is exactly what happened in my case.

> But it seems like it would be better to use the configuration from the source file's workspace when it finds that.

Agreed. I guess you're better qualified to judge this, than me, however.

**Comment by sean-mcmanus** [comment]
Yeah, it's common for headers to have preprocessor statements that can be configured differently by different source files in different workspaces.

The fix was trivial (couple lines).
