### ISSUE TITLE
Linux TypeScript checkin test is broken

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6110]
[3663:0910/235235.289015:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.

Mac passes.

Seems related to 
(node:1043) Electron: Loading non-context-aware native module in renderer: '/Users/runner/work/1/s/Extension/.vscode-test/vscode-1.49.0/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

**Comment by Colengms** [comment]
This is: https://github.com/microsoft/vscode/issues/106569
