### ISSUE TITLE
The program compiles and exits itself with no input and output!!

### ISSUE THREAD

**Issue by NikhilNautiyal** [microsoft/vscode-cpptools#6113]
![image](https://user-images.githubusercontent.com/49453460/92899375-5d5fdc80-f43c-11ea-98be-5a1820ac59cd.png)
it happens of there are more lines of code, with short programs the terminal works fine...but as soon as the lines exceed 25 or more I face this issue always, after months I found the solution to my compilation problems in VS and then this!!
Please help..

**Comment by Colengms** [comment]
Hi @NikhilNautiyal .  The C/C++ Extension provides IntelliSense and other features, but it is not directly involved in how your project is compiled or executed.  I'm not familiar with the "Code" output channel.  Is there another extension involved in compiling and executing your code?  If so, I'd suggest following up with an issue against that extension.

**Comment by NikhilNautiyal** [comment]
Yes, I use a "Code Runner" extension, it's that 'play' button on top right.
