### ISSUE TITLE
Problems with #include definition in c++

### ISSUE THREAD

**Issue by Urban158** [microsoft/vscode-cpptools#6115]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

The program is not recognozing the #include and other variables

Extension version: 0.30.0-insiders5
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (9.21GB free)|
|Process Argv|--crash-reporter-id 1f226a8f-3c63-40c5-88b0-39fd5f960009|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    49	  7428	code main
    0	   298	  5904	   gpu-process
    0	    46	  9828	   shared-process
    2	    66	 11180	   window (Issue Reporter)
    0	   156	 13584	   window (Newman_ShapesCPP.cpp - _LaunchThis (Workspace) - Visual Studio Code)
    0	    97	  3264	     extensionHost
    0	    12	  9660	       "C:\Users\derri\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\derri\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3264
    0	    51	 11104	       c:\Users\derri\.vscode\extensions\ms-vscode.cpptools-0.30.0-insiders5\bin\cpptools.exe
    0	     6	  2760	         console-window-host (Windows internal process)
    0	    23	  7064	         "c:\Users\derri\.vscode\extensions\ms-vscode.cpptools-0.30.0-insiders5/bin/cpptools-srv.exe" 11104 0
    0	    20	  6168	     watcherService
    0	    17	  6228	     searchService
    0	    12	 14484	   utility
    0	     7	 15716	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Newman_ShapesCPP.cpp - _LaunchThis (Workspace) - Visual Studio Code)
|    Folder (Test): 2 files
|      File types: cpp(1) exe(1)
|      Conf files:
|    Folder (hw2-shapescpp-v0-2-Urban158): 17 files
|      File types: json(5) cpp(2) gitignore(1) gitkeep(1) h(1) exe(1) md(1)
|                  code-workspace(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg;
```

</details>

**Comment by sean-mcmanus** [comment]
We need more info on, such as from running C/C++: Log Diagnostics from the Command Palette.

**Comment by Urban158** [comment]
Thanks but I reinstalled everything and it is working now. Thank you again!

**Comment by michelleangela** [comment]
Closing as resolved.
