### ISSUE TITLE
vscode-server-insiders is compiled with GLIBC_2.28 causing problems on ARM

### ISSUE THREAD

**Issue by Misery42** [microsoft/vscode-cpptools#6116]
Type: General

The terminal process failed to launch: A native exception occurred during launch (/lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/pi/.vscode-server-insiders/bin/bc38b0accb3c62180317c63dbe7323200977db0f/node_modules/node-pty/build/Release/pty.node)).

Was once fixed with:
https://github.com/microsoft/vscode-cpptools/issues/429

> Ubuntu 16 OS on ARM will be supported in our next Insiders release...even Ubuntu 14 and CentOS 7, i.e. we take glibc 2.17 dependency like our other Linux binaries.

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode-cpptools/issues/5984#issuecomment-679582519_

**Describe the bug**
- OS and Version: Remote System is running
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- VS Code Version: 1.50.0-insider
- C/C++ Extension Version: 0.30.0-insiders5
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**Expected behavior**
Terminal should connect with ssh

**Screenshots**
![image](https://user-images.githubusercontent.com/42983952/92962076-adf12d00-f470-11ea-9ddd-37b78f1363c1.png)

**Comment by sean-mcmanus** [comment]
This is a bug with the remote SSH VS Code extension, right? Could you file a bug at https://github.com/microsoft/vscode-remote-release/issues and/or maybe https://github.com/Microsoft/node-pty/issues ? Sounds like it might be a regression with 1.50.0-insiders.

Our cpptools and cpptools-srv binaries should not have a glibc_2.28 dependency. You can verify that by running `readelf -a <path to cpptools> ~/info.txt` and check that info.txt only has a reference to glibc_2.17 at max. You could also try running that command on pty.node .

**Comment by Misery42** [comment]
> This is a bug with the remote SSH VS Code extension, right? Could you file a bug at https://github.com/microsoft/vscode-remote-release/issues and/or maybe https://github.com/Microsoft/node-pty/issues ? Sounds like it might be a regression with 1.50.0-insiders.
> 

I am not sure if this is related to rmote SSH VS Code extension. It has not updated since 9 days. And was working yesterday.
I have installed:

Remote - SSH (Nightly) 2020.09.2340
Remote - SSH: Editing Configuration Files (Nightly) 2020.9.2340

so i guess it must be related to pty.node due the 1.50.0-insiders update.

**Comment by Misery42** [comment]
Using VS Code 1.49.0 and the newest vscode-cpptools 0.30.0-insiders5
Everything seemes fine since it has only requirement for VS Code 1.44.0 or later.

**Comment by bobbrow** [comment]
The VS Code team reverted the dependency change and the insiders build should be back to normal now.
