### ISSUE TITLE
IntelliSense: forward parameter suggestion when using std::forward

### ISSUE THREAD

**Issue by csorvagep** [microsoft/vscode-cpptools#6121]
This is a feature request for function/constructor parameter suggestions.
If I use a function which uses std::forward, the suggested parameters should be also forwarded. For example using make_shared, vector.emplace_back, etc.

Here is the current suggestions:
![image](https://user-images.githubusercontent.com/2698569/92998105-3aa2f600-f518-11ea-8244-39cb48e93199.png)

And here's something like the expected behaviour:
![image](https://user-images.githubusercontent.com/2698569/92998117-4db5c600-f518-11ea-8f04-4f2414caacfc.png)

This is probably not trivial, but could be very useful.

**Comment by sean-mcmanus** [comment]
I've filed a feature request on VS at https://developercommunity.visualstudio.com/idea/1184443/cc-intellisense-forward-parameter-suggestion-when.html .

**Comment by Colengms** [comment]
It looks like this feature was implemented in VS, and we picked it up in 1.2.0.  Closing this as fixed.
