### ISSUE TITLE
User can't specify path to .clang-format file outside of current workspace.

### ISSUE THREAD

**Issue by irvinec** [microsoft/vscode-cpptools#613]
I work in an extremely large code base (Windows) and I use VSCode for quick editing. I often will only open the directories in which I am working in VSCode. It isn't practical for me to copy my .clang-format file into all of these directories. I'd like to have one .clang-format file that I can share with VSCode, Visual Studio, and clang-format.exe.

**Comment by sean-mcmanus** [comment]
clang-format style=file uses the .clang-format in the closest parent location and there isn't an option to use another file path. Adding a .clang-format in the root directory sounds like it should solve your issue. You could also specify the style explicitly in the style string, e.g. `-style="{BasedOnStyle:` llvm, IndentWidth: 8}"`.

**Comment by irvinec** [comment]
Thanks @sean-mcmanus! This solves 80% of my pain.
However, I keep all my environment/editor stuff in a separate git repo. This is where I keep my .clang-format file to share across multiple machines and also with my team.
So, if I have two Windows repos (e.g. F:\OS and E:\OS) and my .clang_format file is at C:\MyStuff\format\.clang_format, I would still need to remember to copy my .clang_format file from my private repo clone path to each of my Windows repos.

I can script the copy to the roots of all my repos, but that is just another script i need to create and maintain :)

**Comment by sean-mcmanus** [comment]
.clang-format files are intended to be checked into source control and not kept in a separate repro from the code it intends to format. Otherwise, people using the git repro without the .clang-format won't know what the intended formatting rules are. Is there a reason you don't just check in those .clang-format files? Theoretically, we could add a path setting to a .clang-format file, via copying the .clang-format file at the path to the current directory, running clang-format, and then deleting the .clang-format file (if it didn't exist previously). Is that a feature you would like us to add?

**Comment by irvinec** [comment]
> Is there a reason you don't just check in those .clang-format files?

I would say we have some reasons and some excuses why we don't ... :)

> Theoretically, we could add a path setting to a .clang-format file, via copying the .clang-format file at the path to the current directory, running clang-format, and then deleting the .clang-format file (if it didn't exist previously). Is that a feature you would like us to add?

I'd like to have as much as possible over what happens in my workspace and I don't like the idea of a file getting copied and deleted. I'd rather not have this feature if that is how it was implemented.
If there was a way for the extension to "load" the file from a different path, I would be interested in that feature.

Thanks again @sean-mcmanus for the help and for listening!

**Comment by sean-mcmanus** [comment]
Actually, we could also implement it via reading the external .clang-format file and then converting it to the command line -style.

**Comment by irvinec** [comment]
@sean-mcmanus after reading a bit more about how some other clang-format extensions/plugins work, I think my pain was mostly with not understanding how clang-format was intended to be used. While clang-format.exe will allow me to pass a .clang-format file via `-assume-filename` (I think), it doesn't look like many other IDE extensions/plugins allow for specifying the path to a .clang_format file. I might be misunderstanding how `-assume-filename` works. In that case, my feature ask is way out of line with the intent of clang-format. My intent was to ask for parity with what I can specify via the command line or another Visual Studio plugin/extension.

**Comment by sean-mcmanus** [comment]
The -assume-filename does not allow you to pass a .clang-format file. The comment on that flag is incorrect. It is used primarily for header sorting to tell clang-format the name of the file that is being formatted when the input is received via stdin (e.g. for myFile.cpp, it'll make sure myFile.h is at the top when sorting #includes). Yeah, no other tools or command line allow a path to the .clang-format file.
