### ISSUE TITLE
Add docs on how to get call stacks for crashing cpptools/cpptools-srv

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6137]
...

**Comment by elahehrashedi** [comment]
the instructions are here:
https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-cpptools-srv

**Comment by bobbrow** [comment]
Thanks @elahehrashedi.  Something else to think about... Should we add commands to the extension that automatically set up and launch the debugger for `cpptools` and `cpptools-srv`?  I'm not sure if it works for attach, but it would be nice for people to not have to update the path every time the extension releases an update.
