### ISSUE TITLE
Symbol lookup works incorrect.

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-cpptools#614]
_From @den13k on April 6, 2017 5:47_

- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T21:13:24.700Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cpptools|ms-vscode|0.10.5|;

[Description]
There is a library folder in the project where some C++ headers are resided. Despite the fact that path is included to the file "c_cpp_properties.json", variables from the library cannot be found via "Go to definition" command (but sometimes it's working for some reason). Both relative and absolute path definitions were used.

Example:
       {
            "name": "Linux",
            "includePath": [
                "/opt/arduino-1.8.1/hardware/arduino/avr/cores",
                "/opt/arduino-1.8.1/hardware/arduino/avr",
                "../library/Messaging.poll"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },

---

Steps to Reproduce:

1. Create a simple C++ project.
2. Create a library folder and some code inside.
3. Use some sources from the library folder in the project.
4. Adjust "c_cpp_properties.json" to make it pointing to the library folder.
5. Try to lookup a name present in the library from the project's file.

_Copied from original issue: Microsoft/vscode#23989_

**Comment by sean-mcmanus** [comment]
@den13k Does setting limitSymbolsToIncludedHeaders to false fix this? When it's true, we only find symbols if they're included in a header, but we sometimes choose the wrong header file (we plan to fix this in the future). I don't think ".." by itself works and it should be replaced by "${workspaceRoot}/.." Also, the "/opt" folder would need to be at the root -- if you meant it to be relative to the workspace you need to add the ${workspaceRoot}.

**Comment by den13k** [comment]
Hi guys. Thanks you for the response. I probably provided not enough information for the issue. Let me try to describe it in the other way. And please be informed that I've found the solution (hack) for that.

So, I have rather big project with a number of folders. Saying, master, slave and several libraries in a separate folder. During the project development some files were renamed as well as folders in the 'library'. As a result names from the library folder could not be found from the main projects. When I tried to perform 'go to definition', Code used some paths that were correct before renaming, but not any more. It led to a failure.

I suspected there was a problem with index and tried to find in the Internet a correct way to rebuild it.

Not being able to find the solution, I just removed Code's DB in ".config" folder and it helped.

Please consider adding a feature "Rebuild index" to Code.

**Comment by sean-mcmanus** [comment]
Yes, that is a known problem we intend to fix (see https://github.com/Microsoft/vscode-cpptools/issues/601, https://github.com/Microsoft/vscode-cpptools/issues/464 ).
