### ISSUE TITLE
Add some intelliSenseUpdateDelay setting

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6142]
VS uses 1 second. We currently use 3 seconds, but our next release may change to 2 seconds.

Based on feedback at https://github.com/microsoft/vscode-cpptools/issues/6129 .

**Comment by nholthaus** [comment]
@sean-mcmanus as another point of reference, clion uses 500ms as the default. The 1s value from VS is probably a reasonable upper bound for the default value.

Personally, I set the delay down to 250. I'm not sure squiggles as you type is an issue people care about versus feeling snappy when you want it to.

The most important thing is having a setting though.

**Comment by tjx666** [comment]
How long will it take to start fix?

**Comment by tjx666** [comment]
The 3 seconds delay is too long anyhow. I really can't stand the slow respond. Especially when I fix a syntax error, I can't see the error squiggle disappear immediately.

**Comment by sean-mcmanus** [comment]
We made the change from 3 to 2 seconds, but if anyone wants to make a PR on the TypeScript side for a new setting, we might be able to make the changes to the cpptools side to read that setting. See https://github.com/microsoft/vscode-cpptools/pull/5730 as an example.

**Comment by tjx666** [comment]
In fact, I have made some vscode extensions, but not familiar with lsp.

**Comment by sean-mcmanus** [comment]
I don't think you wouldn't need to change LSP stuff in order to add an intelliSenseUpdateDelay setting...the setting value just needs to be sent along with the other settings we send.

**Comment by tjx666** [comment]
> I don't think you wouldn't need to change LSP stuff in order to add an intelliSenseUpdateDelay setting...the setting value just needs to be sent along with the other settings we send.

I will make a pr about this today or tomorrow.

**Comment by tjx666** [comment]
https://github.com/microsoft/vscode-cpptools/pull/6344

**Comment by sean-mcmanus** [comment]
This is available in https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders3 .
