### ISSUE TITLE
add support for lldb-vscode.exe 

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/vscode-cpptools#6143]
Type: Debugger

pretty much the title.
this may help with the issues discussed in #5415

**Additional context**
https://reviews.llvm.org/D50365
https://github.com/llvm/llvm-project/blob/master/lldb/tools/lldb-vscode/README.md

**Comment by WardenGnaw** [comment]
lldb-vscode is its own extension that you can manually install: https://github.com/llvm/llvm-project/blob/master/lldb/tools/lldb-vscode/README.md#installation-for-visual-studio-code

If you wish to use lldb with the C/C++ extension, you can use `'miMode' : 'lldb'`
