### ISSUE TITLE
Debugging not possible on Ubuntu WSL2

### ISSUE THREAD

**Issue by conkerkh** [microsoft/vscode-cpptools#6145]
Type: Debugger
Debugger tries to start but quits without any sort of output in debug console, when downgrading to 0.29 everything works.

**Describe the bug**
- OS and Version: Ubuntu 20.04 WSL2 via Remote Plugin
- VS Code Version: current
- C/C++ Extension Version: 1.0.0 (most recent)
- Other extensions you installed (and if the issue persists after disabling them): no effect
- A clear and concise description of what the bug is.

**To Reproduce**
Runn pretty much whatever executable
```{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Main",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/main",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            ""
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": false
                }
            ],
            "miDebuggerPath": "/usr/bin/gdb",
        }
    ]
}
```

**Additional context**
logging doesn't show anything at all, unless I'm unable to turn it on using code snippet...

**Comment by sean-mcmanus** [comment]
Debugging with Ubuntu 20 (WSL2) is working for me. Nothing in our debugger changed from 0.29.0 to 1.0.0, so I'm not sure how this would be possible.

**Comment by WardenGnaw** [comment]
Are you not getting logs when you added:
```
"logging": {
   "engineLogging": true
}
```

**Comment by conkerkh** [comment]
strangely I installed 1.01 and the problem disappeared. I don't know exactly what was going on perhaps some components of the extension didn't install correctly at the time, bu anyway looks like the problem is solved.
