### ISSUE TITLE
provide option to configure syntax error squiggles language

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode-cpptools#6148]
```
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
vscode-cpptools: v1.0.0
```

My system language is Chinese, but I want to use English as the language of syntax error squiggles.

![screenshot_2020-09-16_00-58-41](https://user-images.githubusercontent.com/41773861/93244549-7f4ebb80-f7bc-11ea-88fa-79613528519a.png)

**Comment by michelleangela** [comment]
The extension follows whatever [display language is set for VS Code](https://code.visualstudio.com/docs/getstarted/locales). You can try setting VS Code to use English and the extension should follow that setting.

**Comment by tjx666** [comment]
@michelleangela Ok, I fix it by [https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language](https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language)
