### ISSUE TITLE
Cannot attach debugger to cpptools on Mac

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#6151]
Using the following `launch.json`, I'm unable to attach (to cpptools) on Mac Catalina 10.15.6.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "program": "/Users/Colen/.vscode/extensions/ms-vscode.cpptools-1.0.0/bin/cpptools",
            "MIMode": "lldb"
        }
    ]
}
```

This results in an immediate `Debugger has disconnected from the program /Users/Colen/.vscode/extensions/ms-vscode.cpptools-1.0.0/bin/cpptools` message.

**Comment by sean-mcmanus** [comment]
Bob was mentioning he thought this was an issue with cpptools/cpptools-srv exiting out of the message loop, so I'm trying the workaround he created a year ago.

**Comment by sean-mcmanus** [comment]
That seems to work for cpptools, but not sure about cpptools-srv yet.

**Comment by sean-mcmanus** [comment]
@WardenGnaw I can't investigate this because I get "WARNING: Debugger executable '/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/lldb-mi/bin/lldb-mi' is not signed. As a result, debugging may not work properly.

**Comment by sean-mcmanus** [comment]
I fixed the lldb-mi signing issue via signing it, and I fixed this issue for cpptools, but therer's still some other debugger issue preventing breaking into the debugger.
