### ISSUE TITLE
[clang-format] Format C code incorrectly

### ISSUE THREAD

**Issue by dsyx** [microsoft/vscode-cpptools#6153]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04.5 LTS
- VS Code Version: 1.49.0
- C/C++ Extension Version: v1.0.0

**Expected behavior**

This is my configuration file:

```
---
AccessModifierOffset: -4
AlignAfterOpenBracket: Align
AllowShortIfStatementsOnASingleLine: false
BasedOnStyle: LLVM
BreakBeforeBraces: WebKit
ColumnLimit: 0
IndentWidth: 4
IndentCaseLabels: false
Language: Cpp
TabWidth: 4
UseTab: Never
```

This is part of my code, it has been formatted:

```c
/* linkedlist.h */
#ifndef LINKEDLIST_H
#define LINKEDLIST_H

typedef struct node *link;
struct node {
    unsigned char item;
    link next;
};

link make_node(unsigned char item);
void free_node(link p);
link search(unsigned char key);
void insert(link p);
void delete (link p);
void traverse(void (*visit)(link));
void destroy(void);
void push(link p);
link pop(void);

#endif
```

In theory, my `delete` function declaration should be formatted as: `void delete(link p);`
However, the formatter added a space between `delete` and `(`. This seems to treat my `delete` signature as a keyword.
This is wrong for C code.

**Comment by Colengms** [comment]
Hi @dsyx .  I can repro the issue invoking clang-format directly via command line.  This appears to be external, and not something we can address from within the C/C++ Extension for VS Code.  You might consider opening a similar issue against LLVM/clang-format .
