### ISSUE TITLE
When I include bits/stdc++.h , IntelliSense won't work.

### ISSUE THREAD

**Issue by Delta-in-hub** [microsoft/vscode-cpptools#6154]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.19041
- VS Code Version:1.49.0 (user setup)
- C/C++ Extension Version: 1.0.0
- Compiler : TDM-GCC-64   gcc version 9.2.0 (tdm64-1)  Target: x86_64-w64-mingw32

When I include <bits/stdc++.h> in my file , the IntelliSense Engine won't work . But I  can still  `Go to Definition` of header file  or   ` Start Debugging` . 
If I just include headers such as  vector / string , all things will  go properly.

Moreover, if I install C/C++ Extension 0.29.0 Version rather than 1.0.0 , the same issue won't happen . Everything is working fine.
my c_cpp_properties.json 
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/TDM-GCC-64/include",
                "C:/TDM-GCC-64/x86_64-w64-mingw32/include/**",
                "C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/**",
                "C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/TDM-GCC-64/bin/gcc.exe",
            "intelliSenseMode": "gcc-x64",
            "cStandard": "gnu11",
            "cppStandard": "gnu++17",
            "browse": {
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
```

<details>
  <summary><strong>Logs</strong></summary>

```
sending 1 changes to server
cpptools/getDocumentSymbols: file:///d%3A/Document/%E9%82%93%E4%BF%8A%E8%BE%89%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/chapter_2.cpp (id: 59)
cpptools/getDocumentSymbols
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.589
cpptools/getCodeActions: file:///d%3A/Document/%E9%82%93%E4%BF%8A%E8%BE%89%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/chapter_2.cpp (id: 60)
cpptools/getSemanticTokens: file:///d%3A/Document/%E9%82%93%E4%BF%8A%E8%BE%89%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/chapter_2.cpp (id: 61)
Checking for syntax errors: file:///d%3A/Document/%E9%82%93%E4%BF%8A%E8%BE%89%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/chapter_2.cpp
Queueing IntelliSense update for files in translation unit of: D:\DOCUMENT\邓俊辉数据结构\CHAPTER_2.CPP
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.687
cpptools/getSemanticTokens: file:///d%3A/Document/%E9%82%93%E4%BF%8A%E8%BE%89%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/chapter_2.cpp (id: 62)
Database safe to open
cpptools/fileDeleted: file:///c%3A/Users/Delta/AppData/Roaming/Code/User/sync.lock
Checking for syntax errors: file:///d%3A/Document/%E9%82%93%E4%BF%8A%E8%BE%89%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/chapter_2.cpp
Queueing IntelliSense update for files in translation unit of: D:\DOCUMENT\邓俊辉数据结构\CHAPTER_2.CPP
cpptools/fileDeleted: vscode-userdata:/c%3A/Users/Delta/AppData/Roaming/Code/User/sync.lock
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.601
cpptools/getSemanticTokens: file:///d%3A/Document/%E9%82%93%E4%BF%8A%E8%BE%89%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/chapter_2.cpp (id: 63)
Database safe to open
textDocument/hover: file:///d%3A/Document/%E9%82%93%E4%BF%8A%E8%BE%89%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/chapter_2.cpp (id: 64)
Quick info operation failed: FE: 'Compiler exited with error - No IL available'
using Tag Parser for quick info

```
</details>

**Comment by rewrking** [comment]
I have a similar issue in #6147, so I decided to try this out...

I copied the contents of bits/std++.h into a project and started commenting out headers to see what breaks intellisense.

Specifically, it seems to be `#include <setjmp.h>` within `csetjmp`, so just doing this should be enough:

```
#include <iostream>
#include <setjmp.h>

int main()
{
	std::cout << "Hello world!" << std::endl;

	return 0;
}
```

**Comment by MiyaMorg** [comment]
I find that if the code below is in your code, intellisense won't work.

`#pragma push_macro("__has_builtin")
#ifndef __has_builtin
  #define __has_builtin(x) 0
#endif
#pragma pop_macro("__has_builtin")

#ifdef __has_builtin
# if __has_builtin(1)
# endif
#endif`

**Comment by MiyaMorg** [comment]
The code below seems to be a problem.

`
#pragma push_macro("__has_builtin")
#pragma pop_macro("__has_builtin")
#define A __has_builtin(0);
A;
`

**Comment by Salil03** [comment]
I am getting a similar issue. After updating to version 1.0.0, I am no longer getting Intellisense. Also warnings for wrong syntax is not working, Even insiders version does not work.

**Comment by Delta-in-hub** [comment]
> I am getting a similar issue. After updating to version 1.0.0, I am no longer getting Intellisense. Also warnings for wrong syntax is not working, Even insiders version does not work.

exactly the same issue
And  this issue duplicates to [#6147](https://github.com/microsoft/vscode-cpptools/issues/6147) , I will close this one.
