### ISSUE TITLE
Description of extension properties under settings UI not localized in WSL (or remote)

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6158]
This issue is to keep track of VS Code issue https://github.com/microsoft/vscode/issues/106371

**Comment by Colengms** [comment]
Removing from tracking, as the linked issue appears to have been addressed.

**Comment by bobbrow** [comment]
Is there anything we need to do here or can we close this?

**Comment by michelleangela** [comment]
Closing as issue was addressed.

**Comment by Jianchaoliang** [comment]
unsubscribe


| |
菅朝梁
|
|
18205601716@163.com
|
签名由网易邮箱大师定制
On 11/4/2020 03:36，Michelle Matias<notifications@github.com> wrote：

Closed #6158.
