### ISSUE TITLE
Outline shows duplicate local variables for a Python function

### ISSUE THREAD

**Issue by vk-coder** [microsoft/vscode-cpptools#6162]
**Type: LanguageService**

**Describe the bug**
- OS and Version: openSUSE Leap 15.2
- VS Code Version: 1.49.0
- C/C++ Extension Version: v1.0.0
- Other extensions you installed (and if the issue persists after disabling them): cannot test with disabling all extensions because outline does not show anything with all extensions disabled
- Does this issue involve using SSH remote to run the extension on a remote machine?: yes but issue is not related to that as it can be reproduced with just local file.
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
1. Open any python file (tested with python3) 
2. Write a sample function in which single variable is used multiple times in the function
3. Check the outline view and you will find same variable listed multiple times

**Expected behavior**
Outline should display a variable once per function (the line of first definition). multiple lines just clutter the view and adds too many lines for big files. 
to find all the occurrences of the variable we can simply put the cursor inside the word in editor.

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/6987535/93473890-94af0d00-f8c4-11ea-8a2c-49fad61aa43d.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
This appears to be an issue with an extension that provides Python language services, which our C/C++ extension does not. For example, https://github.com/microsoft/vscode-python/issues .
