### ISSUE TITLE
Failed to download package on remote Linux (Error: unable to get local issuer certificate)

### ISSUE THREAD

**Issue by Martin0698** [microsoft/vscode-cpptools#6168]
Issue Type: <b>Bug</b>

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed to download https://go.microsoft.com/fwlink/?linkid=2135548
Failed at stage: downloadPackages
Error: unable to get local issuer certificate
	at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
	at TLSSocket.emit (events.js:223:5)
	at TLSSocket._finishInit (_tls_wrap.js:794:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)

Extension version: 1.0.0
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 5.7.12-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.17GB free)|
|Process Argv|--crash-reporter-id b427d715-84a9-4233-a2b1-bb7d2199d8aa|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.7.12-arch1-1|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (2 x 2903)|
|Memory (System)|1.94GB (1.48GB free)|
|VM|100%|
</details>

**Comment by michelleangela** [comment]
@Martin0698 

The extension failed to download the binaries for Linux on the remote machine because of error "unable to get local issuer certificate". Do you know if the remote machine is behind some firewall or under security restrictions?

Could you try installing the extension on the remote machine with the offline installs https://github.com/microsoft/vscode-cpptools#offline-installation?

**Comment by michelleangela** [comment]
Closing this issue because it has not had recent activity,
