### ISSUE TITLE
Couldn't start client cpptools

### ISSUE THREAD

**Issue by szdytom** [microsoft/vscode-cpptools#6169]
Issue Type: <b>Bug</b>

Output of cpptools is

> Starting client failed
Launching server using command /home/szdytom/.vscode/extensions/ms-vscode.cpptools-1.0.1-insiders/bin/cpptools failed.

Then there is no intelliSense support or autocomplete

Extension version: 1.0.1-insiders
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.4.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3732)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.68GB (3.86GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 298cfea2-5d96-4066-b85f-b4b9515366fe|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by Salil03** [comment]
Also when I tried reinstalling the extension after this issue, it couldn't download cpptools automatically. I had to download cpptools vsix manually and then install it.

**Comment by michelleangela** [comment]
@Salil03 

From the manual installation, could you verify that the file cpptools and cpptools-srv exists under `/home/szdytom/.vscode/extensions/ms-vscode.cpptools-1.0.1-insiders/bin` ? IntelliSense is provided by these binaries.

Is this the first time you encountered a download issue on that Linux machine?

**Comment by Salil03** [comment]
@michelleangela That linux machine belongs to @szdytom who is the original poster. I am having the same issue on a windows machine. I checked for equivalent path on my machine and `cpptools.exe` does exist. Also important note: **Reverting to 0.29.0 fixes the issue.**

**Comment by michelleangela** [comment]
@Salil03 Thanks for the clarification. Sorry I miss reading the posters. Does using version 1.0.0? Or is the issue only with insiders version?

@szdytom Could you verify that the files `cpptools` and `cpptools-srv` exist under `/home/szdytom/.vscode/extensions/ms-vscode.cpptools-1.0.1-insiders/bin`? Also, installing version 1.0.0 work? Or is this only with insiders version?

**Comment by Salil03** [comment]
@michelleangela The issue occurs in both 1.0.0 and latest insiders version.

**Comment by michelleangela** [comment]
@sean-mcmanus  could this be an issue with the forward links?

**Comment by bobbrow** [comment]
Not if it affects Insiders.  Insiders doesn't use forward links.

**Comment by Salil03** [comment]
Good News: 1.0.1 fixes the issue. 😊

**Comment by szdytom** [comment]
Yeah, 1.0.1 works fine now, (but I have still no idea why itn't working on 1.0.0)
