### ISSUE TITLE
debug doesn't run when define map in the code 

### ISSUE THREAD

**Issue by mingzhou6381** [microsoft/vscode-cpptools#6170]
Type: Debugger

**Describe the bug**
- OS and Version: macOS Catalina. 10.15.6
- VS Code Version: 1.49.1
- C/C++ Extension Version:v1.0.1-insiders
launch.jason

 "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang++ build active file",
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
              }
        }
    ]
       
}

**To Reproduce**
If I define map container in the source code, the debugger will stop at the entry and can't step over or continue.

![image](https://user-images.githubusercontent.com/48453597/93668098-13848100-fa50-11ea-8f15-e61152f97852.png)

If comment out the map definition the debugger works.

**Comment by Colengms** [comment]
@WardenGnaw

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue.  We’ll let you know if we need more information to investigate it.
