### ISSUE TITLE
VS code cannot edit in read only editor

### ISSUE THREAD

**Issue by ahmedula** [microsoft/vscode-cpptools#6171]
Type: General
So I can't edit a running program and when I enabled "whether to run code in integrated terminal" I could no longer run the program as another issue arose "no such file or directory" I searched and found that this may be related or caused by an extension, but What do I have to do to get around this? My extensions are: c/c++ code-runner Remote-WSL

**Comment by ahmedula** [comment]
I'm very new to this so if you can please explain it to me as if I was a 5-year-old.

**Comment by sean-mcmanus** [comment]
I don't understand the problem you're hitting. Does your issue repro with the C/C++ extension disabled?
