### ISSUE TITLE
The portmacro.h file could not be automatically detected

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#6178]
Normally, all the files can be retrieved by "${workspacefolder} / * *", but only the portmacro.h file will have problems. You must add the relative address of the portmacro.h file or change the name of the file, such as portmacrozzz.h.

**Comment by sean-mcmanus** [comment]
Can you run C/C++: Log Diagnostics? Are the include paths correct?

**Comment by ghost** [comment]
@sean-mcmanus 
How to run log diagnostics?

c_cpp...json:
`
...
"includePath": [
                "${workspaceFolder}/**",
                "stm32f103rct/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3"
            ]
...
`
There is no problem with other files.
You must add the relative or absolute location of the file, or change the name of the file to solve the problem.

**Comment by sean-mcmanus** [comment]
Use the View->Command Palette:
![image](https://user-images.githubusercontent.com/19859882/94317834-f6fab400-ff3b-11ea-99bf-d027d3afaba1.png)

**Comment by ghost** [comment]
@sean-mcmanus 
The first is to add the relative address of'portmacro.h' in'c_cpp ... json'.
The second is to change the name of the file'portmacro.h', I changed it to'portmacroZ.h', in fact it can be changed to anything else.
The third one is not to add relative addresses and not to change file names.
I very much suspect it has something to do with this file name.
The content in the first and second'Includes:' is an extra'C: \ USER \ USER \ DATA \ PROJECT \ WORK \ STM32PROJECT \ PROJECTV2 \ NUM0 \ STM32F103RCT \ MIDDLEWARES \ THIRD_PARTY \ FREERTOS \ SOURCE \ PORTABLE \ GCC \ ARM_CM3'.
`
-------- Diagnostics - 2020/9/27 上午11:39:41
Version: 1.0.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "stm32f103rct/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE",
        "USE_HAL_DRIVER",
        "STM32F103xB"
    ],
    "compilerPath": "C:/user/software/9 2020-q2-update/bin/arm-none-eabi-gcc.exe",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "stm32f103rct/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\user\user\data\project\work\stm32Project\projectV2\num0\stm32f103rct\Core\Src\user\app\machineTask.cpp ]:
    C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\SRC\USER\APP\MACHINETASK.CPP
Translation Unit Configurations:
[ C:\user\user\data\project\work\stm32Project\projectV2\num0\stm32f103rct\Core\Src\user\app\machineTask.cpp ]:
    Process ID: 3632
    Memory Usage: 31 MB
    Compiler Path: C:/user/software/9 2020-q2-update/bin/arm-none-eabi-gcc.exe
    Includes:
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\MIDDLEWARES\THIRD_PARTY\FREERTOS\SOURCE\PORTABLE\GCC\ARM_CM3
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE\C++\9.3.1
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE\C++\9.3.1\ARM-NONE-EABI
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE\C++\9.3.1\BACKWARD
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\LIB\GCC\ARM-NONE-EABI\9.3.1\INCLUDE
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\LIB\GCC\ARM-NONE-EABI\9.3.1\INCLUDE-FIXED
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\MIDDLEWARES\THIRD_PARTY\FREERTOS\SOURCE\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\SRC\USER\DRIVER
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\SRC\USER\API
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\INC
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\CMSIS\RTOS2\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\STM32F1XX_HAL_DRIVER\INC
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\CMSIS\DEVICE\ST\STM32F1XX\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\CMSIS\CORE\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
        USE_HAL_DRIVER
        STM32F103xB
    Standard Version: c++14
    IntelliSense Mode: gcc-arm
    Other Flags:
        --g++
        --gnu_version=90301
Total Memory Usage: 31 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 3094
Number of files discovered (not excluded): 2759

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/Core/Include/cmsis_iccarm.h
    Alternative: "C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/Core_A/Include"
    Alternative: "C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/Include"
Using: C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/RTOS2/Include/cmsis_os2.h
    Alternative: "C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2"

。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
-------- Diagnostics - 2020/9/27 上午11:45:28
Version: 1.0.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE",
        "USE_HAL_DRIVER",
        "STM32F103xB"
    ],
    "compilerPath": "C:/user/software/9 2020-q2-update/bin/arm-none-eabi-gcc.exe",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\user\user\data\project\work\stm32Project\projectV2\num0\stm32f103rct\Core\Src\user\app\machineTask.cpp ]:
    C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\SRC\USER\APP\MACHINETASK.CPP
    C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\MIDDLEWARES\THIRD_PARTY\FREERTOS\SOURCE\INCLUDE\FREERTOS.H
    C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\MIDDLEWARES\THIRD_PARTY\FREERTOS\SOURCE\INCLUDE\PORTABLE.H
Translation Unit Configurations:
[ C:\user\user\data\project\work\stm32Project\projectV2\num0\stm32f103rct\Core\Src\user\app\machineTask.cpp ]:
    Process ID: 10088
    Memory Usage: 33 MB
    Compiler Path: C:/user/software/9 2020-q2-update/bin/arm-none-eabi-gcc.exe
    Includes:
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE\C++\9.3.1
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE\C++\9.3.1\ARM-NONE-EABI
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE\C++\9.3.1\BACKWARD
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\LIB\GCC\ARM-NONE-EABI\9.3.1\INCLUDE
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\LIB\GCC\ARM-NONE-EABI\9.3.1\INCLUDE-FIXED
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\MIDDLEWARES\THIRD_PARTY\FREERTOS\SOURCE\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\SRC\USER\DRIVER
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\SRC\USER\API
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\INC
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\CMSIS\RTOS2\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\STM32F1XX_HAL_DRIVER\INC
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\MIDDLEWARES\THIRD_PARTY\FREERTOS\SOURCE\PORTABLE\GCC\ARM_CM3
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\CMSIS\DEVICE\ST\STM32F1XX\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\CMSIS\CORE\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
        USE_HAL_DRIVER
        STM32F103xB
    Standard Version: c++14
    IntelliSense Mode: gcc-arm
    Other Flags:
        --g++
        --gnu_version=90301
Total Memory Usage: 33 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 3094
Number of files discovered (not excluded): 2759

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/Core/Include/cmsis_iccarm.h
    Alternative: "C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/Core_A/Include"
    Alternative: "C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/Include"
Using: C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/RTOS2/Include/cmsis_os2.h
    Alternative: "C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2"

。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
-------- Diagnostics - 2020/9/27 上午11:38:05
Version: 1.0.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE",
        "USE_HAL_DRIVER",
        "STM32F103xB"
    ],
    "compilerPath": "C:/user/software/9 2020-q2-update/bin/arm-none-eabi-gcc.exe",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\user\user\data\project\work\stm32Project\projectV2\num0\stm32f103rct\Core\Src\user\app\machineTask.cpp ]:
    C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\SRC\USER\APP\MACHINETASK.CPP
Translation Unit Configurations:
[ C:\user\user\data\project\work\stm32Project\projectV2\num0\stm32f103rct\Core\Src\user\app\machineTask.cpp ]:
    Process ID: 5980
    Memory Usage: 31 MB
    Compiler Path: C:/user/software/9 2020-q2-update/bin/arm-none-eabi-gcc.exe
    Includes:
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE\C++\9.3.1
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE\C++\9.3.1\ARM-NONE-EABI
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE\C++\9.3.1\BACKWARD
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\LIB\GCC\ARM-NONE-EABI\9.3.1\INCLUDE
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\LIB\GCC\ARM-NONE-EABI\9.3.1\INCLUDE-FIXED
        C:\USER\SOFTWARE\9 2020-Q2-UPDATE\ARM-NONE-EABI\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\MIDDLEWARES\THIRD_PARTY\FREERTOS\SOURCE\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\SRC\USER\DRIVER
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\SRC\USER\API
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\CORE\INC
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\CMSIS\RTOS2\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\STM32F1XX_HAL_DRIVER\INC
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\CMSIS\DEVICE\ST\STM32F1XX\INCLUDE
        C:\USER\USER\DATA\PROJECT\WORK\STM32PROJECT\PROJECTV2\NUM0\STM32F103RCT\DRIVERS\CMSIS\CORE\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
        USE_HAL_DRIVER
        STM32F103xB
    Standard Version: c++14
    IntelliSense Mode: gcc-arm
    Other Flags:
        --g++
        --gnu_version=90301
Total Memory Usage: 31 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 3094
Number of files discovered (not excluded): 2759

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/Core/Include/cmsis_iccarm.h
    Alternative: "C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/Core_A/Include"
    Alternative: "C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/Include"
Using: C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Drivers/CMSIS/RTOS2/Include/cmsis_os2.h
    Alternative: "C:/user/user/data/project/work/stm32Project/projectV2/num0/stm32f103rct/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2"

`

**Comment by sean-mcmanus** [comment]
Yes, it's possible 'portmacro.h` could be being picked up from another includePath earlier on. Adding the path of 'portmacro.h' that you want to use to the front your includePath is the recommended solution. Does that work? What error you getting exactly?

**Comment by ghost** [comment]
@sean-mcmanus After updating a version, add "gcc-arm", no problem! thank you
