### ISSUE TITLE
C/C++ debugger not outputting information on variables, watch and call stack. It also doesn't stop at breakpoints

### ISSUE THREAD

**Issue by hyperedge56** [microsoft/vscode-cpptools#6181]
Type: Debugger

**Describe the bug**
- OS and Version: Windows_NT x64
- VS Code Version: 1.49.1
- C/C++ Extension Version: v1.0.1
- Other extensions you installed (and if the issue persists after disabling them):
- I try to debug my C program but all that happens is that it doesn't stop at breakpoints and there is no info shown in the debug columns. The breakpoints have the problem of "Module containing this breakpoint has not yet loaded or the breakpoint adress could not be obtained." I have tried compiling using "gcc -og fileout.exe file.c" and "gcc -oggdb fileout.exe file.c" and "gcc -g file.c" and so far, nothing has worked.

Here's my launch.json file
`{
    "version": "0.2.0",
    "configurations": [
    {
        "name": "(gdb) Launch",
        "type": "cppdbg",
        "request": "launch",
        "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "args": [],
        "stopAtEntry": true,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false,
        "MIMode": "gdb",
        "miDebuggerPath": "C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin\\gdb.exe",
        "setupCommands": [
            {
                "description": "Enable pretty-printing for gdb",
                "text": "-enable-pretty-printing",
                "ignoreFailures": true
            }
        ],
        "logging": { "trace": true, "traceResponse": true }
    }
    ]
}`

and here's the debug console with the logging
` --> C (runInTerminal-2): {"type":"request","command":"runInTerminal","arguments":{"kind":"integrated","title":"cppdbg: params10_exer2.exe","cwd":"","args":["c:\\Users\\JackTheHipster\\.vscode\\extensions\\ms-vscode.cpptools-1.0.1\\debugAdapters\\bin\\WindowsDebugLauncher.exe","--stdin=Microsoft-MIEngine-In-mxcgnhqi.mmw","--stdout=Microsoft-MIEngine-Out-gdgrlpou.q1a","--stderr=Microsoft-MIEngine-Error-rupgm3pm.44d","--pid=Microsoft-MIEngine-Pid-rimmzn2c.2j5","--dbgExe=C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin\\gdb.exe","--interpreter=mi"],"env":{}},"seq":2}
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/MIEngine/WindowsRuntime","data":{"VS.Diagnostics.Debugger.MIEngine.WindowsRuntime":"MinGW"}},"seq":4}
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"16.5.10630.1","VS.Diagnostics.Debugger.HostVersion":"16.5.10630.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.Duration":664,"VS.Diagnostics.Debugger.Launch.IsCoreDump":false,"VS.Diagnostics.Debugger.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.SourceFileMappings":0,"VS.Diagnostics.Debugger.MIMode":"gdb"}},"seq":6}
--> R (launch-2): {"type":"response","request_seq":2,"success":true,"command":"launch","body":{},"seq":8}
--> E (initialized): {"type":"event","event":"initialized","body":{},"seq":10}
<--   R (runInTerminal-2) [578 ms]: {"type":"response","seq":3,"command":"runInTerminal","request_seq":2,"success":true,"body":{"shellProcessId":16840}}
<--   C (setBreakpoints-4): {"command":"setBreakpoints","arguments":{"source":{"name":"params09_exer1.c","path":"c:\\Users\\JackTheHipster\\Desktop\\TestCodeModules\\CMSC123Modules\\parameter-passing\\09 ArrayofStructures\\params09_exer1.c"},"lines":[28,29,43,47,48,63,71],"breakpoints":[{"line":28},{"line":29},{"line":43},{"line":47},{"line":48},{"line":63},{"line":71}],"sourceModified":false},"type":"request","seq":4}
--> R (setBreakpoints-4): {"type":"response","request_seq":4,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"id":1,"verified":true,"line":28},{"id":2,"verified":true,"line":29},{"id":3,"verified":true,"line":43},{"id":4,"verified":true,"line":47},{"id":5,"verified":true,"line":48},{"id":6,"verified":true,"line":63},{"id":7,"verified":true,"line":71}]},"seq":14}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":false,"message":"Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained.","line":28}},"seq":16}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":2,"verified":false,"message":"Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained.","line":29}},"seq":18}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":3,"verified":false,"message":"Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained.","line":43}},"seq":20}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":4,"verified":false,"message":"Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained.","line":47}},"seq":22}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":5,"verified":false,"message":"Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained.","line":48}},"seq":24}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":6,"verified":false,"message":"Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained.","line":63}},"seq":26}
--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":7,"verified":false,"message":"Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained.","line":71}},"seq":28}
<--   C (setFunctionBreakpoints-5): {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":5}
--> R (setFunctionBreakpoints-5): {"type":"response","request_seq":5,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]},"seq":31}
<--   C (configurationDone-6): {"command":"configurationDone","type":"request","seq":6}
--> R (configurationDone-6): {"type":"response","request_seq":6,"success":true,"command":"configurationDone","body":{},"seq":34}
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"=thread-group-added,id=\"i1\"\nGNU gdb (GDB) 8.1\nCopyright (C) 2018 Free Software Foundation, Inc.\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\nThis GDB was configured as \"x86_64-w64-mingw32\".\nType \"show configuration\" for configuration details.\nFor bug reporting instructions, please see:\n<http://www.gnu.org/software/gdb/bugs/>.\nFind the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\nFor help, type \"help\".\nType \"apropos word\" to search for commands related to \"word\".\nWarning: Debuggee TargetArchitecture not detected, assuming x86_64.\n=cmd-param-changed,param=\"pagination\",value=\"off\"\n"},"seq":36}
=thread-group-added,id="i1"
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
<--   C (threads-7): {"command":"threads","type":"request","seq":7}
--> R (threads-7): {"type":"response","request_seq":7,"success":true,"command":"threads","body":{"threads":[]},"seq":39}
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[New Thread 17528.0x2228]\n"},"seq":41}
[New Thread 17528.0x2228]
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[New Thread 17528.0x393c]\n"},"seq":43}
[New Thread 17528.0x393c]
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"\n"},"seq":45}

--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"Thread 1 hit Breakpoint 1, 0x0000000000401679 in main ()\n"},"seq":47}
Thread 1 hit Breakpoint 1, 0x0000000000401679 in main ()
--> E (thread): {"type":"event","event":"thread","body":{"reason":"started","threadId":1},"seq":49}
--> E (thread): {"type":"event","event":"thread","body":{"reason":"started","threadId":2},"seq":51}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\Windows\\SYSTEM32\\ntdll.dll'. Symbols loaded.\r\n"},"seq":53}
Loaded 'C:\Windows\SYSTEM32\ntdll.dll'. Symbols loaded.
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\Windows\\System32\\kernel32.dll'. Symbols loaded.\r\n"},"seq":55}
Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\Windows\\System32\\KernelBase.dll'. Symbols loaded.\r\n"},"seq":57}
Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\Windows\\System32\\msvcrt.dll'. Symbols loaded.\r\n"},"seq":59}
Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"Execute debugger commands using \"-exec <command>\", for example \"-exec info registers\" will list registers in use (when GDB is the debugger)\r\n"},"seq":61}
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
--> E (stopped): {"type":"event","event":"stopped","body":{"reason":"step","threadId":1,"allThreadsStopped":true},"seq":63}
<--   C (threads-8): {"command":"threads","type":"request","seq":8}
--> R (threads-8): {"type":"response","request_seq":8,"success":true,"command":"threads","body":{"threads":[{"id":1,"name":"Thread #1"},{"id":2,"name":"Thread #2"}]},"seq":66}
<--   C (threads-9): {"command":"threads","type":"request","seq":9}
--> R (threads-9): {"type":"response","request_seq":9,"success":true,"command":"threads","body":{"threads":[{"id":1,"name":"Thread #1"},{"id":2,"name":"Thread #2"}]},"seq":69}
<--   C (stackTrace-10): {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":10}
--> R (stackTrace-10): {"type":"response","request_seq":10,"success":true,"command":"stackTrace","body":{"stackFrames":[{"id":1000,"name":"main","line":0,"column":0}],"totalFrames":1},"seq":72}
<--   C (continue-11): {"command":"continue","arguments":{"threadId":1},"type":"request","seq":11}
--> R (continue-11): {"type":"response","request_seq":11,"success":true,"command":"continue","body":{},"seq":75}
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[Thread 17528.0x393c exited with code 0]\n"},"seq":77}
[Thread 17528.0x393c exited with code 0]
--> E (thread): {"type":"event","event":"thread","body":{"reason":"exited","threadId":2},"seq":79}
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[Inferior 1 (process 17528) exited normally]\n"},"seq":81}
[Inferior 1 (process 17528) exited normally]
--> E (thread): {"type":"event","event":"thread","body":{"reason":"exited","threadId":1},"seq":83}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"The program 'c:\\Users\\JackTheHipster\\Desktop\\TestCodeModules\\CMSC123Modules\\parameter-passing\\10 Linked List\\params10_exer2.exe' has exited with code 0 (0x00000000).\r\n\r\n"},"seq":85}
The program 'c:\Users\JackTheHipster\Desktop\TestCodeModules\CMSC123Modules\parameter-passing\10 Linked List\params10_exer2.exe' has exited with code 0 (0x00000000).
--> E (exited): {"type":"event","event":"exited","body":{"exitCode":0},"seq":87}
--> E (terminated): {"type":"event","event":"terminated","body":{},"seq":89}
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"16.5.10630.1","VS.Diagnostics.Debugger.HostVersion":"16.5.10630.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":1}},"seq":91}
<--   C (disconnect-12): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":12}
--> R (disconnect-12): {"type":"response","request_seq":12,"success":true,"command":"disconnect","body":{},"seq":94}
 `

**Comment by WardenGnaw** [comment]
If you are using `"program": "${fileDirname}\\${fileBasenameNoExtension}.exe"` in your launch.json. I would reccomend using the genereated tasks/launch json for _build and debug active file._ 

If you open your c file and right click in the editor, you should see this option.

Are you compiling `gcc -g params10_exer2.c -o params10_exer2.exe`?

**Comment by hyperedge56** [comment]
It's working now it seems. Thank you very much. I just changed the way I compiled the code and it gives me variable states now.
