### ISSUE TITLE
OUTLINE not match with file

### ISSUE THREAD

**Issue by Lafuente** [microsoft/vscode-cpptools#6185]
**Type: LanguageService**
C/C++

**Describe the bug**
- OS and Version: WINDOWS 7 64 bits FR (6.1.7601)
- VS Code Version: 1.49.1
- C/C++ Extension Version: 1.0.1

OUTLINE tree don't match the locations in the C++ file when using long 
#if defined
#endif

It's look like the OUTLINE is shifted by the length of the defined sections

**Comment by sean-mcmanus** [comment]
Could you clarify what you mean? Our symbol parser runs on both sides of an `#if` so the Outline will include symbols for code that isn't defined by IntelliSense (i.e. grayed out, inactive code).

**Comment by Lafuente** [comment]
![screenshot](https://user-images.githubusercontent.com/10392332/93923697-03042d00-fd14-11ea-8481-858710ad5211.jpg)

As example, in this screenshot, if I click on "changeVitesseCAN(String)" in the OUTLINE TREE, it go to the screen as you can see in the picture (line 2045).
"changeVitesseCAN(String)" is at line 2325 as shown in screenshot2.jpg
![screenshot2](https://user-images.githubusercontent.com/10392332/93924065-8aea3700-fd14-11ea-81f5-27c880850565.jpg)

**Comment by Lafuente** [comment]
All functions in main.cpp are shifted per 280 lines in regard with OUTLINE TREE
i.e => initEEprom() display line 2065 when the function in main.cpp is at line 2345

**Comment by Lafuente** [comment]
This situation happen only in a specific project, and only with the main.cpp file.
I can provide the code if needed and if you don't disclose it.

**Comment by Lafuente** [comment]
Sorry, it was a typo error in the code (in the defined). There where missing a } that shifted all the code. I didn't see this before I test all the #if defined possibilities.
Thank you
