### ISSUE TITLE
Cannot Open Source File "iostream"

### ISSUE THREAD

**Issue by smellynailclippings** [microsoft/vscode-cpptools#6188]
I'm very new to C++, and am trying to learn it, but I've ran into an issue. I am getting "Cannot Open Source File iostream". I tried editing my includePath but I wasn't entirely sure what to actually update it to. I'm using Windows.

**Comment by sameermahant** [comment]
Have you tried following steps given in following doc: [Configure VS Code for Microsoft C++](https://code.visualstudio.com/docs/cpp/config-msvc)
In that document "**To use MSVC from a command line or VS Code, you must run from a Developer Command Prompt for Visual Studio**" is really important.

**Comment by sean-mcmanus** [comment]
@SS4PPHIRE  You shouldn't edit your includePath for system defines. You should make sure you have a C/C++ compiler installed, and if it's not detected by default you should set the compilerPath. You can run C/C++: Log Diagnostics to see what compiler is getting used currently.

In addition to the docs @sameermahant mentioned (for cl.exe), you might also use WSL or mingw compilers on Windows:
https://code.visualstudio.com/docs/cpp/config-wsl
https://code.visualstudio.com/docs/cpp/config-mingw

**Comment by smellynailclippings** [comment]
I got it working, but now I'm unsure as to how I start the file. Is there a command in terminal?

**Comment by bobbrow** [comment]
Do you just want to compile a single source file and execute that program?  We have a command `"Build and Debug Active File"` that you can use.
