### ISSUE TITLE
syntax highlighting for CUDA (.cu) files

### ISSUE THREAD

**Issue by JamesAllingham** [microsoft/vscode-cpptools#619]
Would it be possible to add syntax highlighting for CUDA .cu files in VS Code? I know that CUDA and c/c++ are not exactly the same but much of the syntax is the same. It would be nice to even be able to tell cpptools that ".cu" is a c++ extension and just use normal c++ syntax highlighting for CUDA files. I know this is done in [Visual Studio](http://stackoverflow.com/questions/32307914/enable-syntax-highlighting-for-cuda-7-0-in-visual-studio-2013#32308028) (2013 at least) so I was hoping that the same could be done here.

I would be happy to make the changes my self and submit a pull request, if provided with a little guidance as I have never done so before.

EDIT: It seems this is a vs code setting ("files.associations": {"*.cu": "cpp"}), which I managed to miss, so I have closed the issue.

**Comment by shahrukhqasim** [comment]
How did you manage to add a new extension?
