### ISSUE TITLE
MS Code: Launching server using command ms-vscode.cpptools-1.0.1/bin/cpptools failed.

### ISSUE THREAD

**Issue by gregbarski** [microsoft/vscode-cpptools#6192]
After one on last auto-updates of MS Code extensions, it always fails to launch CPPTools which I use with Platform.io extension.

MS Code reports:

```
Couldn't start client cpptools
[Error - 10:18:50] Starting client failed
Launching server using command /home/username/.vscode/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools failed.

```

No other concious updates nor installation were made around that time.

PlatformIO 2.1.0

Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:23:33.049Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-117-generic

**Comment by michelleangela** [comment]
Could you try uninstalling and re-install the extension? Sometimes it fails to install some binaries, such as the cpptools file.

Could you also verify that cpptools and cpptools-srv exists under `/home/username/.vscode/extensions/ms-vscode.cpptools-1.0.1/bin/`?

**Comment by Apocalyt** [comment]
This sounds like the same problem I am having.
I get the same error message in lower right corner error console when Code starts.
I am now unable to compile my projects with Platform.io extension when using version 1.0.1 of C/C++ extension.
Reinstalling doesn't help for me. Going back to version 1.0.0 helps to resolve issue.

For me cpptools and cpptools-srv exist under that forder:
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T19:14:08.130Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.8.7-arch1-1

**Comment by sean-mcmanus** [comment]
What does /home/username/.vscode/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools output when run on the command line? Or what "file /home/username/.vscode/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools" output? It's possible VS Code might be installing the wrong Linux binaries for some reason. You may want to try our offline vsix at https://github.com/microsoft/vscode-cpptools/releases/download/1.0.1/cpptools-linux.vsix (installed via the Install From VSIX... command in VS Code).

**Comment by Apocalyt** [comment]
Here is output for what you asked. cpptools produces no output when run. It does nothing until killed.

[apocalyt@Nemesis ~]$ .vscode-oss/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools


^C
[apocalyt@Nemesis ~]$ file .vscode-oss/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools
.vscode-oss/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=d3e2def65f58837c0ed06650d2e7c5be73c5223d, not stripped

**Comment by shivammalviya712** [comment]
Hii!! I had the same issue, so I just made cpptools and cpptools-srv executable using "chmod +x <filename>". Now it's working.

**Comment by JohnKalesis1** [comment]
I also had the same issue and by making it an executable, it made the notifications that it failed disappear.

But the extension still does not work
