### ISSUE TITLE
intellisense did not work

### ISSUE THREAD

**Issue by suzukajiang** [microsoft/vscode-cpptools#6193]
**Describe the bug**
- OS and Version:  win10
- VS Code Version:  1.49.1
- C/C++ Extension Version:  1.0.1

cpptools intellisense doesn't work after i update to 1.0.1 from 0.29.0.
it reported too many errors, and there is no any error in 0.29.0
it also happened in 1.0.0

pitcure  below is the log from 0.29.0
![IMG_20200923_162317](https://user-images.githubusercontent.com/34700091/93988081-e5d66980-fdba-11ea-8661-6a7f1a8e3c8a.jpg)

pitcure below is the log from 1.0.1

![IMG_20200923_163343](https://user-images.githubusercontent.com/34700091/93988552-6eeda080-fdbb-11ea-936c-de676deb978d.jpg)

**Comment by michelleangela** [comment]
Could you provide the errors in English? To change the VS Code Display Language, follow the instructions at https://code.visualstudio.com/docs/getstarted/locales. And if possible, could you copy-and-paste the text of logs to the issue?

Could you also provide the log output from running the command `C/C++: Log Diagnostics` for both version 0.29.0 and 1.0.1?

**Comment by suzukajiang** [comment]
Log of 0.29.0
[Image]

[Image]


log of 1.0.1
[Image]

[Image]


获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by suzukajiang** [comment]
Sorry about the log. My pc is offline, I can't upload all of the log, just can provide some pitcure of the log

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by suzukajiang** [comment]
![IMG_20200924_103527](https://user-images.githubusercontent.com/34700091/94094301-baeb2480-fe51-11ea-8a95-2b594a7f9ae2.jpg)
![IMG_20200924_103519](https://user-images.githubusercontent.com/34700091/94094315-c0486f00-fe51-11ea-9e29-b55c9f8b1f02.jpg)

**Comment by suzukajiang** [comment]
![16009167933621845857206875276121](https://user-images.githubusercontent.com/34700091/94096196-1a4b3380-fe56-11ea-9ef7-c34fb4a7be8e.jpg)
![16009168453404173705134666748150](https://user-images.githubusercontent.com/34700091/94096222-26cf8c00-fe56-11ea-8e35-c16ae883e40c.jpg)
![1600916876256504224086274805276](https://user-images.githubusercontent.com/34700091/94096257-38189880-fe56-11ea-94d9-13f2575a079b.jpg)
![16009168918329064719209113261681](https://user-images.githubusercontent.com/34700091/94096275-41a20080-fe56-11ea-916b-cac64d6e379d.jpg)

**Comment by Delta-in-hub** [comment]
兄弟,你这对着屏幕拍也太瞎眼了.生产环境不方便就在自己电脑上复现,把log贴上来.
