### ISSUE TITLE
The bundled clang-format binary for Windows is built for x64 - should be x86 for compatibility with x86 and ia32 systems.

### ISSUE THREAD

**Issue by CodeNameHawk** [microsoft/vscode-cpptools#6195]
Issue Type: <b>Bug</b>

Press Shift+Alt+F not format text.

Formatting failed:
"c:\Users\Marian\.vscode\extensions\ms-vscode.cpptools-1.0.1/bin/../LLVM/bin/clang-format.exe" -style="{ BasedOnStyle: LLVM, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All }" -fallback-style="LLVM" -sort-includes=1 -assume-filename="c:\Users\Marian\Documents\Arduino\Atmega2560_Franek\Atmega2560_Franek.ino"
Unable to start child process!

Extension version: 1.0.1
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:38.048Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) D CPU 2.80GHz (2 x 2810)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.37GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by CodeNameHawk** [comment]
I try run clang-format.exe 
get error
"This version of C:\Users\Marian\.vscode\extensions\ms-vscode.cpptools-1.0.1\LLVM\bin\clang-format.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher."

**Comment by Colengms** [comment]
Hi @CodeNameHawk .  Thanks for reporting this.  It looks like clang-format binary bundled with the extension on Windows is built for x64, and should be built for x86 instead.

**Comment by sean-mcmanus** [comment]
The manual workaround would be to install https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win32.exe and set the C_Cpp.clang_format_path to `"C:\\Program Files\\LLVM\\bin\\clang-format.exe"`.

@elahehrashedi The x64 clang-format would be useful to keep around in case we ship an x64 vsix in the future.

**Comment by elahehrashedi** [comment]
I changed the pipeline to build the clang-format binary for Win32 target architecture. 
@sean-mcmanus maybe we should create another pipeline to build for Win64 in the future.

**Comment by sean-mcmanus** [comment]
Okay, that's fine.

**Comment by elahehrashedi** [comment]
1. The new Binary needs to be published and the fwlink needs to be updated.
2. The shared folder for offline/insiders builds needs to be updated.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.0-insiders .

**Comment by CodeNameHawk** [comment]
Bug fixed. Thx.
