### ISSUE TITLE
ROS Intellisense configuration

### ISSUE THREAD

**Issue by Pietroro** [microsoft/vscode-cpptools#6196]
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.49.1
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them): CMake, GitLens, Python, ROS, but the issue persists when all of them are disabled
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

Upon starting up a cleanly installed ROS workspace, built with catkin_make, the extension suggests there are errors in .cpp files claiming that there are missing namespaces.

![Screenshot from 2020-09-23 14-30-46](https://user-images.githubusercontent.com/27856599/94013509-7789ab00-fdaa-11ea-9b14-6759b451204d.png)

This to me looks like I have misconfigured the extension, as it probably isn't aware of the libraries linked via the catkin_make command. 
Would anyone help me to get to the bottom of this? I have tried using the ROS extension hoping their automatic configuration settings would fix the problem, but it doesn't seem like they do. 

A temporary fix I have found is to set the "Intellisense Engine" to "Tag parser". But as mentioned in #3416 that is not recommended.

Thanks for the help

**Comment by michelleangela** [comment]
Could you share the log output from running the command `C/C++: Log Diagnostics`? This will show what configuration info (includePaths, defines, etc) is being used for IntelliSense.

For more info about IntelliSense configuration for the C++ extension, see documentations at:
https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp#_updated-ccpppropertiesjson-syntax
https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference

**Comment by Pietroro** [comment]
Hi Michelle,

I looked into the docs you sent me, the Diagnostics output was very useful. I will include it into this post for completeness' sake.
It seems like the ROS extension set the c and cpp Standards way too high. ROS "noetic" seems to target c++14. Setting that as the cpp standard fixed the issue. 

Thanks for your time and help 

>  -------- Diagnostics - 9/24/2020, 10:12:41 AM
> Version: 1.0.1
> Current Configuration:
> {
>     "name": "ROS",
>     "browse": {
>         "limitSymbolsToIncludedHeaders": true,
>         "path": [
>             "${workspaceFolder}/devel/include",
>             "/opt/ros/noetic/include",
>             "/usr/include/**",
>             "${workspaceFolder}/**"
>         ]
>     },
>     "includePath": [
>         "${workspaceFolder}/devel/include",
>         "/opt/ros/noetic/include",
>         "/usr/include/**",
>         "${workspaceFolder}/**"
>     ],
>     "intelliSenseMode": "gcc-x64",
>     "compilerPath": "/usr/bin/gcc",
>     "cStandard": "gnu18",
>     "cppStandard": "gnu++20",
>     "compilerArgs": []
> }
> ...
