### ISSUE TITLE
Wrong background color for text areas in config UI with Insiders 1.50.0

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-cpptools#6201]
Type: General

**Describe the bug**
- OS and Version: Microsoft Windows [Version 10.0.19041.487]
- VS Code Version:

Version: 1.50.0-insider (user setup)
Commit: e80644fd7da69295b18e7f79403720dd1b155507
Date: 2020-09-22T10:11:29.896Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. Open config UI

**Expected behavior**

Using the same theme keys as the builtin settings UI:

![image](https://user-images.githubusercontent.com/2193314/94053548-510a4680-fd8f-11ea-8da0-022a76435dc1.png)

Otherwise it's hard to know what is input and what is just readonly text.

**Screenshots**

![image](https://user-images.githubusercontent.com/2193314/94053502-418afd80-fd8f-11ea-8499-2bd47d7787c0.png)

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by Colengms** [comment]
Hi @Tyriar .  Thanks for reporting this.  This looks to be a VS Code issue.  I've opened the following issue against VS Code: https://github.com/microsoft/vscode/issues/107332

**Comment by bobbrow** [comment]
The VS Code team fixed the bug.
