### ISSUE TITLE
Invalid expression error

### ISSUE THREAD

**Issue by aparna742** [microsoft/vscode-cpptools#6204]
Issue Type: <b>Bug</b>
```
#include <iostream>
using namespace std;

#define PI 3.14159
#define AREA(r) PI*r*r;
...
line 9:    cout << AREA(radius) << endl;
   ```
I am getting the following error but line 9 is valid. I can run the code. 
`{
	"resource": "..Area.cpp",
	"owner": "C/C++",
	"code": "29",
	"severity": 8,
	"message": "expected an expression",
	"source": "C/C++",
	"startLineNumber": 9,
	"startColumn": 26,
	"endLineNumber": 9,
	"endColumn": 28
}`

Extension version: 1.0.1
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2677M CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 3|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 8e415471-078d-400c-a07d-2919d7172ceb|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Remove the ";" to fix the compiler error.

**Comment by sean-mcmanus** [comment]
...the last character in the definition of AREA.

If you're running the code, maybe it's running an old version? It shouldn't be able to compile.
