### ISSUE TITLE
Terminal Fail

### ISSUE THREAD

**Issue by MrAlbino** [microsoft/vscode-cpptools#6210]
Issue Type: <b>Bug</b>

Good but i have problem with terminal, when i was writing C++ data structure codes and i use mingw32-make vscode terminal gives me different result than cmd

Extension version: 1.0.1
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.47GB free)|
|Process Argv|--crash-reporter-id ae765cc6-8290-4682-8b15-231e268b2da7|
|Screen Reader|no|
|VM|50%|
</details>

**Comment by bobbrow** [comment]
Hi there.  This sounds like a problem with VS Code and not C++.  Can you open an issue on the vscode repository?  Our extension does not own the Terminal implementation.
