### ISSUE TITLE
#include <cstdlib>  do not include abs() and become red underlined in abs()

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#6213]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I'm not reproing this. Please provide more repro info.

![image](https://user-images.githubusercontent.com/19859882/94312702-40de9c80-ff32-11ea-9085-f6836e6eeb06.png)
