### ISSUE TITLE
need support for arm64

### ISSUE THREAD

**Issue by tiankongsnow** [microsoft/vscode-cpptools#6216]
need support for arm64

**Comment by MicePilot** [comment]
> need support for arm64

已经支持了吧，看介绍里直接下载release里的cpptools-linux-aarch64.vsix，然后在vsc里使用Install from VSIX...命令安装就行了
![image](https://user-images.githubusercontent.com/13869645/94360947-8098b600-00e3-11eb-8df0-32fbbb877ed4.png)

**Comment by sean-mcmanus** [comment]
@tiankongsnow We have support for Linux ARM 64 (when using the remote extensions or via https://github.com/microsoft/vscode/pull/106289#issuecomment-691076575). Is it not working for you? What version are you trying to use? How are you installing and what is the error?

Windows ARM64 support is in progress, see https://github.com/microsoft/vscode-cpptools/issues/5583 .

Mac ARM64 support is possible in the future.

**Comment by tiankongsnow** [comment]
没用，装上，还是显示，不支持



在 2020-09-27 16:04:49，"裸奔丶小馒头" <notifications@github.com> 写道：

need support for arm64

已经支持了吧，看介绍里直接下载release里的cpptools-linux-aarch64.vsix，然后在vsc里使用Install from VSIX...命令安装就行了

**Comment by tiankongsnow** [comment]
显示，不支持arm64



At 2020-09-29 00:00:10, "Sean McManus" <notifications@github.com> wrote:

@tiankongsnow We have support for ARM 64. Is it not working for you? How are you installing and what is the error?

**Comment by sean-mcmanus** [comment]
What version of VS Code are you using and what version of the C/C++ extension are you using?

FYI, VS Code supports Linux ARM now on Insiders at microsoft/vscode#106289 (comment) .

**Comment by sean-mcmanus** [comment]
I'm closing this issue since it doesn't have enough info.

We have a Windows ARM64 1.1.0-insiders3 vsix at https://github.com/microsoft/vscode-cpptools/releases/download/1.1.0-insiders3/cpptools-win-arm64.vsix . Debugging isn't enabled yet though.
