### ISSUE TITLE
C++ could not read tuple header file

### ISSUE THREAD

**Issue by AnneMayor** [microsoft/vscode-cpptools#6218]
- OS Version: macOS Catalina version. 10.15.6
- VS Code Version: 1.49.0
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them): Code Runner
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

**Steps to reproduce**
1. Include header file "tuple" in .cpp file.
2. Initialize tuple Object in main() function and run the source code.

**Expected behavior**
1. Does not occur errors and print out the output value(1, 2, 3).

```
temp3.cpp:9:5: error: no template named 'tuple'
    tuple<int, int, int> tp;
    ^
temp3.cpp:10:10: error: use of undeclared identifier 'make_tuple'
    tp = make_tuple(1, 2, 3);
         ^
2 errors generated.
```

**Screenshots**
<img width="1791" alt="Screen Shot 2020-09-28 at 1 23 04 PM" src="https://user-images.githubusercontent.com/15176192/94390571-f9544c80-018d-11eb-8d2b-5ee60553863a.png">

**Comment by sean-mcmanus** [comment]
Those errors are not from our extension. They're from the g++ command on your path. It looks like the g++ on your path doesn't support tuple, i.e. maybe a version of g++ older than 6. Can you install a newer version of g++? You can use `g++ --version` to see the version.

**Comment by bobbrow** [comment]
It's also possible your compiler defaults to an older version of the standard.  Try adding `-std:c++11` to the command line.

**Comment by AnneMayor** [comment]
Thank you guys for all your support. Will try it.
