### ISSUE TITLE
c++ warnings disappears after project rebuild

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-cpptools#622]
_From @nikitablack on April 10, 2017 7:31_

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|
|debug|webfreak|0.17.0|;

---

Steps to Reproduce:

1. Add a code that generates a warning - add an unused variable, for example.
2. Build a project with a task (I'm using gcc).
3. Observe a warning in the Problems tab.
4. Rebuild the project.
5. The warning is missing now.

_Copied from original issue: Microsoft/vscode#24405_

**Comment by sean-mcmanus** [comment]
@nikitablack This appears to be a bug with another extension. We only show the "Include file not found" warning and not "unused variable" warnings.
