### ISSUE TITLE
Persistent compiler error: C/C++ (312) No suitable user-defined conversion

### ISSUE THREAD

**Issue by songyang-dev** [microsoft/vscode-cpptools#6222]
**Type: LanguageService**

My project compiles without problem on `cmake` + `nmake`. But Intellisense is still saying that I have a compiler error. The error goes away (for a while) if I reopen my script.

The compiler error is also nonsensical. It is saying that there is no conversion between things of the same type.
```no suitable user-defined conversion from "const trimesh::trimesh_t::halfedge_t" to "const trimesh::trimesh_t::halfedge_t" exists```

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.49.2
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them): Better TOML, ESLint, GitLens, Python, Visual Studio IntelliCode (maybe remove the problem when disabled)
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

*Copy paste from VS Code's _About_*
Version: 1.49.2 (user setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Steps to reproduce**

1. Install the half edge data structure by cloning this [open source repo](https://github.com/yig/halfedge).
2. Install the prerequisites for the half edge structure: the C++ Eigen library and include it in your path.
3. Type the following in a file where the include will be found.
```cpp
#include "trimesh.h"

void testFunction()
{
   trimesh::trimesh_t mesh; // should be initialized to run properly, but we are aiming at a compiler error
   const trimesh_t::halfedge_t forwardHE = mesh.halfedge(0); // this line should generate the Intellisense error
}
```

**Expected behavior**

An Intellisense compile error should show up, like in the screenshot below.

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/10444460/94504367-99ce5f00-01d6-11eb-86ab-d8c659b3b18b.png)

**Additional context**

In case the error doesn't show up, it may be because I disabled the Visual Studio IntelliCode extension. It may also be the code snippet is not comprehensive enough. I cannot release all my code because it is related to a University assignment. When the assignment is due and if the issue persists, I can share my private repo with all the code.

**Comment by songyang-dev** [comment]
The error is still here even after disabling Visual Studio IntelliCode.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I'll check (tomorrow) if it repros with our latest internal update which has a bunch of fixes such as the fix for https://github.com/microsoft/vscode-cpptools/issues/6097 , which have the same root cause.

**Comment by sean-mcmanus** [comment]
I'm not reproing the bug. Can you run the C/C++: Log Diagnostics command from the Command Palette?

Also, I had to add "using namespace trimesh;" to get it to compile.

**Comment by songyang-dev** [comment]
> 
> 
> I'm not reproing the bug. Can you run the C/C++: Log Diagnostics command from the Command Palette?
> 
> Also, I had to add "using namespace trimesh;" to get it to compile.

I'll provide the log. About the namespace, yes I forgot to use it. 😅 You did the correct thing.

**Comment by michelleangela** [comment]
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.

**Comment by xsw0** [comment]
I also encountered this bug
