### ISSUE TITLE
Incorrect red squiggly lines formed when syntax is correct

### ISSUE THREAD

**Issue by Mindjolt2406** [microsoft/vscode-cpptools#6226]
![Screenshot 2020-09-29 at 6 29 20 PM](https://user-images.githubusercontent.com/30757416/94561481-b4114700-0281-11eb-8e6f-c81ed4f64f78.png)

**Comment by sean-mcmanus** [comment]
We need more info. Such as sample repro code and/or what the error message say. I can't even tell if the errors are from our extension or not.

**Comment by Mindjolt2406** [comment]
[Bug Report.zip](https://github.com/microsoft/vscode-cpptools/files/5303392/Bug.Report.zip)
This is my code. I believe the error is in linking different files. It's not recognising the methods in the structs located in other files for some reason. This behaviour is surprising because it just stopped working all of a sudden.

OS: MacOS
OS Version: 10.14.6

VS Code Details
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

Extension Version Number: v1.0.1
Other extensions installed
1. Bash Beautify (shakram02.bash-beautify)
2. Docker (ms-azuretools.vscode-docker)
3. Live-Share by Microsoft (ms-vsliveshare.vsliveshare)
4. OCaml hackwaly.ocaml
5. StarDog RDF Grammars (stardog-union.stardog-rdf-grammars)
6. vs-code pdf (tomoki1207.pdf)


I can attest that it is from the ms-vscode.cpptools extension, because disabling it removes the squiggles. Restarting VS Code, deleting and reinstalling the extension does not help. I've attached the snapshots of the problems. Please do let me know what other information I can provide. My code is compiling successfully and can be compiled by running g++ -std=c++14 main.cpp

![Screenshot 2020-09-30 at 11 42 06 AM](https://user-images.githubusercontent.com/30757416/94649297-013cf980-0312-11eb-83fa-b4267ef76c71.png)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug on VS (for our shared code) at https://developercommunity.visualstudio.com/content/problem/1207039/c-intellisense-gives-a-bunch-of-invalid-class-has.html .

**Comment by sean-mcmanus** [comment]
The linked VS bug got closed, but I've filed a new bug internally (1487635).

**Comment by sean-mcmanus** [comment]
This is fixed with 1.10.3 (pre-release).
