### ISSUE TITLE
Task not working as expected

### ISSUE THREAD

**Issue by luisagd** [microsoft/vscode-cpptools#6229]
Issue Type: <b>Bug</b>

Start a task like Build Task.
Expected: Do the task(The command works fine in the console)
Result: Stuck in "Building..."(does not end), in case of Build Task, and in case of Debugging, the task does not starts as expected.

I tried re-installing it, and deleting the folder .vscode.

Extension version: 1.0.1
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS version: Linux x64 5.4.0-45-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1999)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|3.76GB (0.11GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sean-mcmanus** [comment]
Does your issue repro with the C/C++ extension disabled? This sounds like a VS Code issue: https://github.com/microsoft/vscode/issues
