### ISSUE TITLE
Shutdown IntelliSense cpptools-srv process when it reaches N amount of memory usage

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6230]
There has been issues on memory usage around IntelliSense engine process on macOS and Linux platforms. On Windows, the IntelliSense engine process will shutdown when it reaches a certain threshold of memory usage, therefore there has been no feedback issues on memory usage on Windows as the process will terminates before it uses an undesirable amount of memory.

To mitigate the memory usage issue on macOS and Linux, add a mechanism to terminate the IntelliSense engine process when it reaches N amount of memory usage. 

Value of memory usage limit:

- The limit is configurable
- default is 4 GB
- minimum is 256 MB
- maximum is 6 GB

**Comment by sean-mcmanus** [comment]
I think there should be a setting to configure this (the A/B testing might control that setting's default?). The default can probably start off high like 4 GB, because the bad case is when it uses "all" memory (like 8+ GB).

Also, it should work for Windows, for ARM64 or x64.
