### ISSUE TITLE
Debugging C++ code hangs

### ISSUE THREAD

**Issue by Silcet** [microsoft/vscode-cpptools#6231]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 18.04 5.4.0-48-generic
- VS Code Version: 1.49.2
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them): Issue persists after disabling them
- A clear and concise description of what the bug is.

I'm having problems with the debugger in my main project, so I have created one with this piece of code with a breakpoint in line 4 to test. The issue is that whenever I try to debug the code the debugger doesn't show anything in the call stack or variables, and the control buttons are grayed out, only allowing me to stop or restart the debug session. The issue looks very similar to [#2787](https://github.com/microsoft/vscode-cpptools/issues/2787). ~~I also get `&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"` but I don't get that random "2" file mentioned in that ticket.~~
Any ideas?

```cpp
#include <iostream>

int main() {
    std::cout << "Hello there" << std::endl;
    return 0;
}
```

This is my launch file:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/hello_world",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": { 
                "engineLogging": true,
                "trace": true, 
                "traceResponse": true
            },
        }
    ]
}
```

I attach the logging output I generated when trying to debug the program on a file [logging.txt](https://github.com/microsoft/vscode-cpptools/files/5303748/logging.txt) not to pollute the ticket.

**Comment by WardenGnaw** [comment]
I'm not seeing the `&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"` in the provided logs. However, we send `shell echo -e \\\\033c 1>&2` to GDB to prevent that error from showing up, which is being executed in the logs.

**Comment by Silcet** [comment]
Actually the message appeared only briefly in the terminal since the command you mention hides it. It makes good sense and I have crossed that out in the issue. Then my problem must lay somewhere else...

**Comment by Silcet** [comment]
I figured out the problem. My $SHELL variable was /usr/bin/fish, which seemed to make everything hang. I forced it to be /bin/bash in the settings in VSCode and the debugger works as expected. So for anyone with the same issue as me, simply add the following to your settings.json:
``` json
"terminal.integrated.env.linux": {
        "SHELL": "/bin/bash"
},
```
