### ISSUE TITLE
[C/C++ extension] code auto-completion issues for local variables and function parameters

### ISSUE THREAD

**Issue by prophett0527** [microsoft/vscode-cpptools#624]
static void test_function(int test_param)
{
    int abc_test = test_param;
}

For this test code, 
when "int abc_test = test" is entered, possible methods and definition in the entire project is listed, but the parameter "test_param" is NOT displayed.
However, when "int abc_test = test_p" is entered, the suggestion list is disappeared. At this point, if "ctrl + space" is pressed, "test_param" is listed as code-completion suggestion.

Local variables and function parameters are NOT listed as code-completion at first time. They are listed ONLY when no motheds and functions are matching with the input in the entire project.

If I remember correctly, Visual Studio is displaying local variables and methods and functions all-together at the same time.
Is is possible to list all variables and methods together at the same time in VSCode?

**Comment by prophett0527** [comment]
My environment is Windows 7 + VSCode 1.11.1

**Comment by sean-mcmanus** [comment]
Our auto-complete currently doesn't work for local variables and the completion for test_param is actually when we find no results and fall back to VS Code's default textmate word completion. We intend to make this better (see https://github.com/Microsoft/vscode-cpptools/issues/13 ). VS Code doesn't seem to allow multiple auto-complete providers to accumulate results. You can disable ours via the C_Cpp.autocomplete setting.
