### ISSUE TITLE
Format Document doesn't sort my includes

### ISSUE THREAD

**Issue by mundodisco8** [microsoft/vscode-cpptools#6242]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1909 
- VS Code Version: 1.49.1 system
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Open a .c file where the includes are not sorted alphabetically

```c
#include "b.h"
#include "a.h"

#include "c1.h"
#include "a2.h"

int main() {
    uint32_t a = 1;
    return 0;
}
```
2. Have a .clanformat file that specifies that includes must be sorted. IndentWidth can be used to check that the config file is being used

```
SortIncludes: 'True'
IndentWidth: '12'
```
3. Run "Format Document"

**Expected behavior**

1. The file is formatted, with the desired Indent Width and the includes are sorted alphabetically (in groups, so only adjacent includes are sorted)
```c
#include "a.h"
#include "b.h"

#include "a2.h"
#include "c1.h"

int main() {
            uint32_t a = 1;
            return 0;
}
```

<details>
  <summary><strong>Logs</strong></summary>

```
cpptools/formatDocument: file:///c%3A/Users/Joel/OneDrive%20-%20Brompton%20Bicycle%20Ltd/Desktop/New%20folder%20%283%29/main.c (id: 314)
Formatting input:
#include "b.h"
#include "a.h"

#include "c1.h"
#include "a2.h"

int main() {
            uint32_t a = 1;
            return 0;
}
Formatting document: file:///c%3A/Users/Joel/OneDrive%20-%20Brompton%20Bicycle%20Ltd/Desktop/New%20folder%20%283%29/main.c
Formatting Engine: clangFormat
Formatting raw output:
#include "b.h"
#include "a.h"

#include "c1.h"
#include "a2.h"

int main() {
            uint32_t a = 1;
            return 0;
}
```
</details>

**Screenshots**

**Additional context**

I am running a newer version than the included in VS Code (10.0), and pointed to the right path in the settings. If I add an incorrect path to the clang-format executable, **I see that it's run with -sort-includes=0** for some reason
```
C:/INCORRECTPATH/clang-format.exe -style="file" -fallback-style="LLVM" -sort-includes=0 -assume-filename="c:\Users\Joel\Workspace\bgm111-application\BGM111-Application\main.c"
Unable to start child process!
```

If I run the clang-format in the command line, the format is the expected one, with the includes sorted properly
```
#include "a.h"
#include "b.h"

#include "a2.h"
#include "c1.h"
[...]
```

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue with
```
SortIncludes: true
IndentWidth: 12
```

What is the value of your C_Cpp.clang_format_sortIncludes setting? Is it set to false? It should be the default of "null" if you want the .clang-format value to be used.

**Comment by mundodisco8** [comment]
Aha! I must have set this one by mistake. It was lost in a massive settings file (it would be so helpful if VS Code grouped and sorted settings...)

Sorry! You can close this one.
