### ISSUE TITLE
specific variable name `amp` - rename problem

### ISSUE THREAD

**Issue by beauxq** [microsoft/vscode-cpptools#6244]
Issue Type: <b>Bug</b>

with c++ extension installed, new folder, new cpp file

Put this code in the file: `int amp;`

right click `amp`
rename symbol
type any other variable name and press enter

error: `A definition for the selected symbol could not be located.`

Most variable names make no error. (`x`, `my_var`, `am`, `amps`)
I think I have seen this bug with other variable names, but `amp` is the only one I can find doing it right now.

Extension version: 1.0.1
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS version: Linux x64 4.15.0-118-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|11.63GB (5.91GB free)|
|Process Argv|--unity-launch --crash-reporter-id e5a759f8-56e2-4ef2-8056-76b15f14ce2e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug on VS (it's an issue with our shared code): https://developercommunity.visualstudio.com/content/problem/1207937/c-intellisense-doesnt-work-on-variables-named-amp.html

**Comment by bobbrow** [comment]
Thanks for checking, @mrx23dot.
