### ISSUE TITLE
macOS Build Active File App permission request 

### ISSUE THREAD

**Issue by ajitpeter** [microsoft/vscode-cpptools#6247]
Issue Type: <b>Bug</b>

The presence of "preLaunchTask": "C/C++: clang++ build active file" in the launch.json file causes [“AppName” would like to access files in your Documents folder] to be prompted every time debugging is initiated. It still does it even after allowing access each and every time. I have built my CPP and it resides in the Documents folder. Removing it makes the access request go away everytime debugging is initiated. It is the same for the code example provided [here](https://github.com/microsoft/vscode-cpptools/tree/master/Code%20Samples/Fib). Every time I start a debugging session for the example provided I get a request to access the folder.

Extension version: 1.0.1
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.6.0

The launch.json version used 
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang++ build active file"
        }
    ]
}
```

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (24.64GB free)|
|Process Argv|--crash-reporter-id 66e59190-08d4-4435-a61f-f3a21bdbc57f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by WardenGnaw** [comment]
That would be macOS's GateKeeper making sure the application you want to run can access personal files.
They specifically check Documents, Desktop, and Downloads. 

Do you see this permission request if you build in your home folder?

**Comment by ajitpeter** [comment]
Yes that worked @WardenGnaw Thanks for that. I had my folder in the Documents folder. A point to note for any body facing similar issue is that the folder has be located in `\Users\usernname` level. That is where QtCreator creates folder by default.
