### ISSUE TITLE
Issue in VS Code.

### ISSUE THREAD

**Issue by Andrei20035** [microsoft/vscode-cpptools#6248]
i have this issue in vs code that say "g++ : The term 'g++' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again" and also when i type g++ in command prompt it says "gcc' is not recognized as an internal or external command,
operable program or batch file." What should i do??
![Untitled](https://user-images.githubusercontent.com/72299251/94988417-a572aa80-0575-11eb-9fac-aa856ac47e5d.png)

**Comment by sean-mcmanus** [comment]
It sounds like you need to install g++, such as from mingw. Also, on Windows, g++ ends with an ".exe". See https://code.visualstudio.com/docs/cpp/config-mingw .
