### ISSUE TITLE
Intellisense dies with this code snippet

### ISSUE THREAD

**Issue by daiyousei-qz** [microsoft/vscode-cpptools#6251]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 2004 build 19041.508
- VS Code Version: 1.49.3
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them): CMake Tools
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

Use the following code snippet with a new cmake project.
``` c++
#include <span>
#include <vector>

int main()
{
    std::vector xs{1, 2, 3};
    std::span s{xs};

    return 0;
}
```

**Expected behavior**

Intellisense stops working. 
Extension Host shows
[2020-10-04 03:51:45.671] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2020-10-04 03:51:45.671] [exthost] [error] undefined

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue. Are you using C++20? What version of the C++ headers are you using? Running C/C++: Log Diagnostics can provide this info.

![image](https://user-images.githubusercontent.com/19859882/95118215-c3b7e200-06fe-11eb-9642-0b1422944eb2.png)

Do you see any error or fail messages in the C/C++ logs?

The extension host errors are unrelated and should be ignored.

**Comment by daiyousei-qz** [comment]
Yes, I'm using c++20 with Visual Studio 16.7.4. I suppose STL is shipped with the compiler.

Here's the CMakeLists.txt I'm using for a testing project.
```
cmake_minimum_required(VERSION 3.16)

project(test)
set(CMAKE_CXX_STANDARD 20)

if (MSVC)
    add_compile_options(/std:c++latest)
endif()

include_directories(include)

file(GLOB HEADER_FILE "include/*.h")
file(GLOB SOURCE_FILE "src/*.cpp")
add_executable(foo ${HEADER_FILE} ${SOURCE_FILE})
```
Here's the log. I don't see any error messages, though.
```
-------- Diagnostics - 10/5/2020, 3:40:10 PM
Version: 1.0.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe",
    "intelliSenseMode": "msvc-x64",
    "compilerArgs": [],
    "cStandard": "c99",
    "cppStandard": "c++17",
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "d:/projects/test2/build/cmakefiles/4c8cee86b3ee52a49c13493fc5417b5e",
        "d:/projects/test2/include",
        "d:/projects/test2/src"
    ],
    "standard": "c++20",
    "compilerPath": "c:/program files (x86)/microsoft visual studio/2019/community/vc/tools/msvc/14.27.29110/bin/hostx64/x64/cl.exe",
    "compilerArgs": [
        "/DWIN32",
        "/D_WINDOWS",
        "/GR",
        "/EHsc",
        "/Zi",
        "/O2",
        "/Ob1",
        "/DNDEBUG",
        "-MD",
        "/std:c++latest",
        "-std:c++latest"
    ]
}
Custom configurations:
[ D:\Projects\test2\src\main.cpp ]
{
    "defines": [
        "WIN32",
        "_WINDOWS",
        "NDEBUG"
    ],
    "standard": "c++20",
    "includePath": [
        "d:/projects/test2/include"
    ],
    "intelliSenseMode": "msvc-x64",
    "compilerPath": "c:/program files (x86)/microsoft visual studio/2019/community/vc/tools/msvc/14.27.29110/bin/hostx64/x64/cl.exe",
    "compilerArgs": [
        "/DWIN32",
        "/D_WINDOWS",
        "/GR",
        "/EHsc",
        "/Zi",
        "/O2",
        "/Ob1",
        "/DNDEBUG",
        "-MD",
        "/std:c++latest",
        "-std:c++latest"
    ]
}
Translation Unit Mappings:
[ D:\Projects\test2\src\main.cpp ]:
    D:\PROJECTS\TEST2\SRC\MAIN.CPP
Translation Unit Configurations:
[ D:\Projects\test2\src\main.cpp ]: not ready
    Process ID: 17528
    Memory Usage: 23 MB
    Compiler Path: c:/program files (x86)/microsoft visual studio/2019/community/vc/tools/msvc/14.27.29110/bin/hostx64/x64/cl.exe
    Includes:
        D:\PROJECTS\TEST2\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.27.29110\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.27.29110\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
    Defines:
        WIN32
        _WINDOWS
        NDEBUG
    Standard Version: ms_c++latest
    IntelliSense Mode: msvc-x64
Total Memory Usage: 23 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 4849
Number of files discovered (not excluded): 4819
```

![image](https://user-images.githubusercontent.com/12378019/95124704-d1cb2a00-0721-11eb-93a3-8261c9e33eea.png)

**Comment by sean-mcmanus** [comment]
Okay, I repro the issue with 14.27.29110 -- it doesn't repro with my headers for 16.9 Preview 1. The cpptools-srv process is crashing.

**Comment by sean-mcmanus** [comment]
I've opened a bug on our shared parser code at https://developercommunity.visualstudio.com/content/problem/1209658/c-intellisense-process-crashes-when-using-span-wit.html ...although in that case it's even crash with the 16.9 Preview 1 headers, so I'm not sure what's different.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2

**Comment by sean-mcmanus** [comment]
However, there's still a bug with hover (and possibly other features) involving the span variable that is being tracked by https://github.com/microsoft/vscode-cpptools/issues/6514 still.
