### ISSUE TITLE
Red squiggly lines in code that compiles correctly: name followed by '::' must be a class or namespace name

### ISSUE THREAD

**Issue by brentgracey** [microsoft/vscode-cpptools#6252]
Issue Type: <b>Bug</b>

Disclaimer: I'm not sure if my diagnosis of the root cause is correct.

I am looking in a code set that uses macros; the macro seems to be expanding correctly; yet the below error is highlighted whilst the code will compile and run as expected; so it is a valid use of a macro.

Perhaps there is additional setup / configuration I need to complete in order for the plugin to process this macro expansion correctly?

Please let me know if I can provide any additional info to triage the issue further

```
#define ROS_INFO(__VA_ARGS__...) ROS_LOG(::ros::console::levels::Info, ROSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
Expands to:

ROS_LOG(::ros::console::levels::Info, ROSCONSOLE_DEFAULT_NAME, "I heard: [%s]", msg->data.c_str())
name followed by '::' must be a class or namespace nameC/C++(276)
```
![image](https://user-images.githubusercontent.com/476578/95065555-2312f380-06f9-11eb-95ba-134a13589d0b.png)

Extension version: 1.0.1
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:56:11.027Z)
OS version: Linux x64 5.4.0-48-generic snap
Remote OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 2199)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 3|
|Memory (System)|62.75GB (40.06GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 205183f6-0566-4829-8349-b40996aca137|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container ros_vsc_debug_2 (/reverent_fe…|
|OS|Linux x64 5.4.0-48-generic|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 2199)|
|Memory (System)|62.75GB (40.07GB free)|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Are you able to provide the fully expanded code, assuming it still repros? In particular, I don't see the definition for ROS_LOG_COND.

**Comment by brentgracey** [comment]
The code is from this repo - https://github.com/ros/rosconsole/blob/noetic-devel/include/ros/console.h#L383

Perhaps VS Code has a limit on how deep it tries to expand macros? I don't know the above code that well; but it does seem to be using quite a few macros in the logging approach.

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue -- my configuration may be different from yours. The most likely cause of the :: error is that your configuration is not able to find the definition for the identifier to the right of the ::.

![image](https://user-images.githubusercontent.com/19859882/95245951-a8b1a480-07c8-11eb-8937-56f8a5822dd7.png)

Can you please run
```<your compiler> -E <your std> <any other required build flags> ./test.cpp > ./test.out.cpp```
e.g.
```/usr/bin/g++-10 -E -std=c++17 ./test.cpp > ./test.out.cpp```
where test.cpp contains something like
```
#include <whatever-is-required>
int func()
{
	ROS_INFO("DFD");
	return 0;
}
```
Doing that should enable you to see which identifier is to the right of the :: and see what definition is missing.

**Comment by brentgracey** [comment]
Thanks for the debugging tips

The codeset that this error is showing up in does use a custom build tool, and trying to compile a single file does fail. Currently its on the imports; so earlier than the Macro expansion.

There is a vs-code plugin specific for the framework; so I will post there to see if they can advise on if there is any way to support the build logic.

https://github.com/ms-iot/vscode-ros/issues/314

If it makes more sense to copy all the details to the vscode-ros and close this ticket; please advise.

Thanks again

**Comment by sean-mcmanus** [comment]
I'm not familiar with the custom build tool or what it does. If it's a VS Code extension, they could implement our vscode-cpptools-api to provide configuration info, like the CMake Tools extensions does: https://github.com/microsoft/vscode-cpptools-api .

**Comment by brentgracey** [comment]
Very interesting, that indeed seems like the route that would be needed.

Just for reference; an overview of the build system is given - http://wiki.ros.org/catkin/conceptual_overview

**Comment by brentgracey** [comment]
Turns out it was a simple mis-configuration on my part 

Answer was provided on: https://github.com/ms-iot/vscode-ros/issues/314
Red squiggly lines for ROS_INFO and for ros::Time() dissapeard for me when i switched "cppStandard": "gnu++14" to "cppStandard": "c++14" in the .vscode/c_cpp_properties.json

source of solution: microsoft/vscode-cpptools#5963 (comment)

Thank you for the debugging help provided under this issue
