### ISSUE TITLE
my include path not work

### ISSUE THREAD

**Issue by quantrpeter** [microsoft/vscode-cpptools#6256]
Hi
   my include path seems not working. the .h file not found. please help

Thanks
Peter
<img width="1680" alt="Screenshot 2020-10-05 at 8 26 14 PM" src="https://user-images.githubusercontent.com/50471577/95149455-916abb00-07b8-11eb-8bf1-505908a93eea.png">

**Comment by sean-mcmanus** [comment]
What is the exact error message? It could be dependent header isn't being found.

**Comment by michelleangela** [comment]
Closing this issue because it has not had recent activity. Please install the latest version of the C++ extension to see if the issue has been fixed. If the issue still reproduces, please re-open the issue and provide the requested additional information.
