### ISSUE TITLE
[Feature request]Inactive regions support shortcut key hiding and display functions

### ISSUE THREAD

**Issue by luckzylp** [microsoft/vscode-cpptools#6258]
**Type: LanguageService**

In order to facilitate the reading of c/c++ code, it is required to support the hidden inactive area function through shortcut key commands, so as to hide invalid precompiled macro code blocks to facilitate code reading. I have seen this feature on SciTools Understand, which is very good for embedded development engineers. I strongly request that this feature be added later.

I want to use VSCode as the main embedded environment, which will be an amazing feature.

Thank you.

**Comment by Colengms** [comment]
I don't believe an extension has the ability to fold (hide) code-folding regions in the editor.  This would seem to be a feature request for VS Code, and would be similar to "Folder All Comments" and "Fold All Regions".  @jay-zhou-yan , I'd suggest opening this against the vscode repo instead.  I suspect they could implement this generically, and it would require a new FoldingRangeKind type (i.e. FoldingRangeKind.Inactive).
