### ISSUE TITLE
auto-formatting pointer declaration style in cpp

### ISSUE THREAD

**Issue by vivek-kurma** [microsoft/vscode-cpptools#6260]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.19041
- VS Code Version: 1.49.3 
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them):https://marketplace.visualstudio.com/items?itemName=austin.code-gnu-global
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
Formatting input:
#include <iostream>
using namespace std;
int main(){
    int x = 10;
    int* p=&x;
}
Formatting document: file:///c%3A/Users/DELL/Programs/DSA/6-oct/sample.cpp
Formatting Engine: clangFormat
Formatting raw output:
{ "Cursor": 89, "IncompleteFormat": false }
#include <iostream>
using namespace std;
int main(){
    int x = 10;
    int *p = &x;
}
Formatting diffed output before cursor:
 *p = &x;
Formatting diffed output after cursor:


textDocument/didChange: file:///c%3A/Users/DELL/Programs/DSA/6-oct/sample.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///c%3A/Users/DELL/Programs/DSA/6-oct/sample.cpp (id: 1605)
cpptools/getCodeActions: file:///c%3A/Users/DELL/Programs/DSA/6-oct/sample.cpp (id: 1606)
Database safe to open
```
</details>

**Screenshots**

**Additional context**

ISSUE:
```cpp
int* a;
```
this declaration of pointer gets auto formatted to:

```cpp
int *a; // can be quite confusing while initializing at the time of declaration
```
SOLUTION:
Is there anyway to disable or change this ? 

FEATURE-SUGGESTION:
It would be good if the auto-formatter worked the other way around rather than the present way .

**Comment by sean-mcmanus** [comment]
What is confusing about "int *a = &b;"? We use the same default that clang-format uses (I think it's the more common style for C++). You can use the PointerAlignment property in a .clang-format file or the C_Cpp.clang_format_style setting. See http://clang.llvm.org/docs/ClangFormatStyleOptions.html . Let me know if you have trouble getting that to work.

**Comment by VIVEKKURMA** [comment]
> What is confusing about "int *a = &b;"? We use the same default that clang-format uses (I think it's the more common style for C++). You can use the PointerAlignment property in a .clang-format file or the C_Cpp.clang_format_style setting. See http://clang.llvm.org/docs/ClangFormatStyleOptions.html . Let me know if you have trouble getting that to work.

```
int *a=new int ;
// it looks misleading as if we are dereferencing a and assigning it the address of new integer pointer

int *b;
*b=10;
// in the above declaration of variable a  looks similar to that of b , as a beginner i was confused regarding 
// this aspect 
```

```
int* a,b,c;
//this gets autoformatted to
int *a,b,c;
// thus b and c are now integer variables where as the actual declaration is integer pointer .
```

But since the format is default  clang format , i will try and  make changes on my .clang-fomat as you stated . Can you help me get started on how to change  the format options ?

**Comment by sean-mcmanus** [comment]
With "int *a, b, c", only a is a pointer, and b and c are integers -- that's the argument in favor of the * being on the right. Also, the original C designers intentionally wanted *a in the declaration to look like the usage in dereferencing.

Something like this in a file named ".clang-format" in the workspace root (or a parent folder).
```
BasedOnStyle: LLVM
UseTab: Never
IndentWidth: 4
TabWidth: 4
BreakBeforeBraces: Allman
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
AccessModifierOffset: -4
NamespaceIndentation: All
PointerAlignment: Left
```
