### ISSUE TITLE
"Add Watch" on local should add expression, not address

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-cpptools#6265]
Issue Type: <b>Bug</b>

when I "Add Watch" a member of a local, i get this monster in the watch window:
````
((std::__shared_ptr<my::type, (__gnu_cxx::_Lock_policy)2>::element_type *)0x3016710)->member: <value>
````

i'd expect to get this:
````
local->member: <value>
````

(this is what Visual Studio does)

and then maybe a menu item to 'fix' the reference (ie convert the first part of the watch expression from `local` to `((std::__shared_ptr<my::type, (__gnu_cxx::_Lock_policy)2>::element_type *)0x3016710)`)

Extension version: 1.0.1
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1127.18.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (2.14GB free)|
|Process Argv|--crash-reporter-id 70645636-42ae-4864-b371-1810b42a2956|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.18.2.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|3.70GB (0.35GB free)|
|VM|100%|
</details>

**Comment by Colengms** [comment]
@WardenGnaw

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue.  We’ll let you know if we need more information to investigate it.
