### ISSUE TITLE
Extension fails installing (extension "not found")

### ISSUE THREAD

**Issue by elisaado** [microsoft/vscode-cpptools#6266]
Type: General

**Describe the bug**
- OS and Version: Arch Linux @ 5.8.12
- VS Code Version: 1.49.1
- C/C++ Extension Version: N/A
- Other extensions you installed (and if the issue persists after disabling them): Flutter, ESLint, issue persists.
- A clear and concise description of what the bug is.
When trying to search for the extension, it's not in the list. When installing using the command line, the command fails with the message "Extension 'ms-vscode.cpptools' not found."

**To Reproduce**

Command line:
1. Open your terminal
2. Use `code --install-extension ms-vscode.cpptools` to try and install the extension.
3. See error

Editor:
1. Open extension installation window
2. Search for c++.
3. Watch cpptools not being in the list.

**Expected behavior**
Extension should be findable and installable.

**Additional context**
Offline installation works (using the `.vsix` files)

**Comment by sean-mcmanus** [comment]
I'm not able to repro this on Windows or Linux (ARM64/Debian 10). What is the exact error message? I think this would be a bug with VS Code and not our extension: https://github.com/microsoft/vscode/issues .

**Comment by ghost** [comment]
I can reproduce this issue on Manjaro @ 5.4.67-MANJARO with the "community/code 1.49.1-1" package. But I don't have this issue with the AUR "Microsoft" build (aur/visual-studio-code-bin).

**Comment by elisaado** [comment]
Hey (sorry for my late reply)

@sean-mcmanus, the issue only seems to occur with this extension, it's oddly specific so I thought I'd open it here, however, the comment by @niklasLieb seems to suggest it's an issue with the specific build on the Arch Linux repository.

**Comment by sean-mcmanus** [comment]
Yeah, I don't think our extension is able to fix this. Sounds like there's some issue with the VS Code marketplace.
