### ISSUE TITLE
Debugger pause button deactivated in top "debug menu", but still working in thread list sidebar

### ISSUE THREAD

**Issue by ruabmbua** [microsoft/vscode-cpptools#6267]
Type: Debugger

**Describe the bug**
- OS and Version: Debian 10.6
- VS Code Version: 1.49.2
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them): Issue persists when only C++ plugin is activated

When attaching to a remote process using gdbserver and ARM gdb, after initially attaching to the process, the pause button in the top "debugger menu" does not work. It is disabled. Strangely, in the thread view in the sidebar, the debug pause button is not disabled on the different threads. Pausing a thread successfully pauses the program. After pausing the program once, the top "debugger menu" recovery, and updates the pause button.

**To Reproduce**

```json
{
			"name": "(gdb) Attach to ...",
			"type": "cppdbg",
			"request": "launch",
			"program": "${workspaceFolder}/builds/debugBinary",
			"cwd": "${workspaceFolder}",
			"MIMode": "gdb",
			"miDebuggerServerAddress": "<IP_ADDRESS>:<PORT>",
			"miDebuggerPath": "/opt/arm-poky-linux-gnueabi-gdb",
			"setupCommands": [
				{
					"description": "Set sysroot",
					"text": "set sysroot /opt/sysroot",
				},
				{
					"description": "custom pretty printers",
					"text": "source ${workspaceFolder}/gdb/pretty_printers/init.py"
				},
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			],
			"linux": {"MIMode": "gdb"},
			"sourceFileMap": {
			}
		},
```

1. Launch the process on the remote ARM machine
2. Attach with gdbserver to the PID on the remote ARM machine
3. Start debugging on local machine, connect to gdbserver

**Comment by WardenGnaw** [comment]
Can you add the following to your `launch.json`:
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```
and share the output from the Debug Console?

**Comment by ruabmbua** [comment]
Here you go: https://gist.github.com/ruabmbua/79c941e233ed0a22c1a24514ad292f65
Hope this can help.

I just noticed, that the F6 keyboard shortcut is also working, just the GUI is broken.

**Comment by WardenGnaw** [comment]
Thanks for providing a log, this clarified that it wasnt an extension issue but VS Code's.

They have a bug and fix pending. It is currently fixed in vscode-insiders: 
https://github.com/microsoft/vscode/issues/107053
