### ISSUE TITLE
Timeout when debugging with gdb

### ISSUE THREAD

**Issue by asdfffy** [microsoft/vscode-cpptools#6269]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 19.10
- VS Code Version: 1.47.2
- GDB Version: 8.3
- C/C++ Extension Version: 1.0.1

In debug mode, I want to use 'exec commands [n]' to debug at a breakpoint, but after entering the above command, DEBUG CONSOLE has no output and no response. How do I use the ‘commands’ command in debug mode.

**To Reproduce**
`{

    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++-9 - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++-9 build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}`

1. Press 'F5' to start debugging
2. Use '-exec b' to set breakpoints
3. Enter '-exec commands' in DEBUG CONSOLE
4. The debug console is unresponsive

**Comment by WardenGnaw** [comment]
When `-exec commands` is sent, it outputs `>>` to console and never returns `^done` so we are waiting for GDB to complete that request.

```
-exec commands
1: (24860) <-1040-interpreter-exec console "commands"
1: (24873) ->~">"
1: (24873) ->~">"
```

**Comment by WardenGnaw** [comment]
Ah, `commands` is requesting multiline input from the user.

This is not supported in MIEngine.
```
-interpreter-exec console "commands"
~"Type commands for breakpoint(s) 1, one per line.\nEnd with a line saying just \"end\".\n"
~">"
```
