### ISSUE TITLE
Issues with the fstream file in the database

### ISSUE THREAD

**Issue by Nacandcheese** [microsoft/vscode-cpptools#6276]
**Type: LanguageService**

I needed to create a program that can read or write from a file and even after naming the path, the terminal keeps stating that it's object types are undefined.

**Describe the bug**
- OS and Version: Windows 10 Pro version 2004
- VS Code Version: 1.49.3
- C/C++ Extension Version: v1.0.1
- Other extensions you installed (and if the issue persists after disabling them): A rather small set of other extensions that work in tandem to create Unity projects. (If I disabled them it would likely not change anything except whether or not I can use Unity.)
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- The files for <fstream> keep stating they are undefined even after including them.

**Steps to reproduce**
The only step needed is to open a .cpp file and use `#include <fstream>`, and then put an object creation statement in main.
**Expected behavior**
I expected the program to let me state and use ifstream, ofstream, and fstream objects.

**Screenshots**

![image](https://user-images.githubusercontent.com/56834638/95484675-61591e80-0956-11eb-84df-3b1f76526c51.png)
![image](https://user-images.githubusercontent.com/56834638/95484708-6cac4a00-0956-11eb-9e3d-6d627e7aa9ec.png)

**Comment by sean-mcmanus** [comment]
According to your repro steps, you need to add "using namespace std;" or use "std::ifstream". Let me know if you're still seeing an issue after making that change.

**Comment by Nacandcheese** [comment]
It worked perfectly, and everything is going well now. Thank you so much! I will keep this in mind for future programs.
