### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by Run396** [microsoft/vscode-cpptools#6277]
Issue Type: <b>Bug</b>

I get this message everytime i open visual studio code: 
"The C/C++ extension failed to install successfully. You will need to reinstall the extension for C/C++ language features to function properly."

Extension version: 1.0.1
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

**Comment by sean-mcmanus** [comment]
That means expected files are not being found. See https://github.com/microsoft/vscode-cpptools/blob/7817a10b5f6b55d5ae514470d1cc90581e749dd6/Extension/src/common.ts#L538 . Are you able to see which of those files don't exist for you?

Are you able to fix the issue by uninstalling the C/C++ extension, restarting VS Code, and then reinstalling the C/C++ extension?

You could also try the offline vsix at https://github.com/microsoft/vscode-cpptools/releases/download/1.0.1/cpptools-win32.vsix (installed via the "Install from VSIX" command in VS Code, not double-clicking it).

**Comment by Run396** [comment]
i installed the offline thing and it worked! thanks
