### ISSUE TITLE
No relative include path

### ISSUE THREAD

**Issue by opensw** [microsoft/vscode-cpptools#629]
Hi,
   I have in cpp code something like this

`#include "../../path/myFile.h"`

Visual Studio Code shows an error like "Include file not found in include path" when in edit mode, this means I cannot open that file (and all other header files included with relative paths). The relative path is right 100%, is there a workaround to fix it?

**Comment by sean-mcmanus** [comment]
Our code ignores the "../../path" part, so if it can't find myFile.h it means that the file itself was not found in our search of the workspace root and includePath. You should add the path to myFile.h to the includePath. Let us know if that doesn't work. The includePath setting in c_cpp_properties.json accepts relatives paths via ${workspaceRoot}/../

**Comment by opensw** [comment]
Good morning, I have added to c_cpp_properties.json the include path and now #include "../../path/myFile.h" it is working.

Thank you for your help :)
