### ISSUE TITLE
MSVC support

### ISSUE THREAD

**Issue by liuslnlp** [microsoft/vscode-cpptools#63]
"Warning: Debugging is currently only supported for Windows when using MinGW or Cygwin". In my opinion, we should Increase the support for Microsoft C++ compiler(MSVC).

**Comment by jhasse** [comment]
Possible duplicate: #65

**Comment by delmyers** [comment]
The two are similar, but not exactly the same if there is some specific WinDBG feature that the other user would like.

**Comment by TurkeyMan** [comment]
This is probably a duplicate of #66, not #65. The OP refers to compilers, but appears to be talking about debuggers, so it's not clear. Suspect OP means the debugger from the MSVC compiler distribution (ie, Concord).

**Comment by delmyers** [comment]
Closing as duplicate of #66

**Comment by delmyers** [comment]
@WiseDoge @jhasse, We released support for this with version 0.9.0, available now. Go check it out.
