### ISSUE TITLE
Type of variable not shown in debugger watch window

### ISSUE THREAD

**Issue by petke** [microsoft/vscode-cpptools#6301]
Type: Debugger
gdb 7.6.1-119.el7
OS and Version: centos7
VS Code Version: 1.49.1

The watch window only shows the value of a variable but not its type. See picture.

![watch](https://user-images.githubusercontent.com/822399/95854262-5c81d980-0d5f-11eb-830a-a64eb2afe032.png)

I'm using "visual studio code" on linux, with the GDB debugger (c++),
Is there a setting for this, so the type is also shown? 

I'm used to how the debugger watch windows works in visual studio (proper) on windows, where the type is also displayed. (So maybe I can replace the debugger visualizer natvis file, with the one visual studio on window uses, somehow?)

**Comment by WardenGnaw** [comment]
If there are no child elements to the variable, the type is hidden in the tooltip.
![image](https://user-images.githubusercontent.com/3953714/95890256-62b08f80-0d38-11eb-865d-aa3cbc4c2bda.png)


If it is an object, it will display it next to the name:
![image](https://user-images.githubusercontent.com/3953714/95890208-53314680-0d38-11eb-8323-54f7e8c7a9df.png)
