### ISSUE TITLE
Configurable single-line comment style

### ISSUE THREAD

**Issue by dfarley1** [microsoft/vscode-cpptools#6309]
**Type: LanguageService**

- OS and Version: Ubuntu 20.04
- VS Code Version: 1.50
- C/C++ Extension Version: 1.0.1

Our code style insists on `/* func(foo); */` style comments, even for single line comments. Can cpptools have a config option to support this?

Given some line of code
```
1  for(int i = 0; i < len; i++) {
2      func(foo[i]);
3  }
```
Place the cursor anywhere in line 2 and run command "Toggle Line Comment", I get:
```
1  for(int i = 0; i < len; i++) {
2      // func(foo[i]);
3  }
```
If I format this file (save with `formatOnSave`), clang converts this to a `/*  */` style comment:
```
1  for(int i = 0; i < len; i++) {
2      /* func(foo[i]); */
3  }
```
This is actually really nice as it's way easier to type `//` style comments and let the formatter "fix" it (I unfortunately have no say in the style we use).

However, say I want to un-comment line 2. Place the cursor in the line and hit "Toggle Line Comment" again and I get
```
1  for(int i = 0; i < len; i++) {
2      // /* func(foo[i]); */
3  }
```
Doh! Now I have to un-comment lines manually. If I've done this to several lines (for debugging or whatever) it becomes a bit of a pain to un-comment manually.
Using "Toggle Block Comment" to un-comment works, but two different shortcuts for the same toggle is annoying. Using "Toggle Block Comment" to comment out code requires me to select the entire statement, not just place my cursor on the line, also annoying.
A "good enough" solution for me would be to detect `/* ... */` on the same line and consider that something to un-comment rather than comment out, but I can see how that might be problematic in some cases.

**Comment by sean-mcmanus** [comment]
Toggle Block Comment is implemented by VS Code and there's no extensibility available for extensions, unless someone wants to make a PR to the VS Code repo. I see issues like https://github.com/microsoft/vscode/issues/67732 and https://github.com/microsoft/vscode/issues/9311 that are Won't Fix due to not enough upvotes.

**Comment by sean-mcmanus** [comment]
Should I close this issue or did you have an alternative suggestion?

**Comment by dfarley1** [comment]
> Toggle Block Comment is implemented by VS Code and there's no extensibility available for extensions

I'm guessing same goes for Toggle Line Comment? If so then I don't have any better ideas. I guess I'll rebind "Toggle Block Comment" to `Ctrl+Shift+/` as an "undo" of Toggle Line Comment (`Ctrl+/`) for now. Maybe if I annoy our principals enough I can get the style loosened up :sweat_smile:

**Comment by sean-mcmanus** [comment]
Yes, same goes for Toggle Line Comment.
