### ISSUE TITLE
C/C++ Debugging: "&" is lost if used in "setupCommands" array

### ISSUE THREAD

**Issue by sjroe** [microsoft/vscode-cpptools#631]
`&` is being lost if used in the `text` of the `setupCommands` array causing the following error on launch:

> Unable to start debugging. Launch options string provided by the project system is invalid

 For example:

`
"setupCommands" : [ { "text" = "-gdb-set SCB->VTOR=&exception" } ],
`

This can be fixed by using `&amp;` in place of `&`:

`
"setupCommands" : [ { "text" = "-gdb-set SCB->VTOR=&amp;exception" } ],
`

I have observed this on both Windows 7 64-bit and Windows 10 64-bit.
VSCode v1.11.1
C/C++ Extension v0.10.5

**Comment by WardenGnaw** [comment]
This should be fixed in 1.1.0.
