### ISSUE TITLE
template   no warning;

### ISSUE THREAD

**Issue by solfcolin** [microsoft/vscode-cpptools#6315]
```
template <class K, class V>
struct BSTreeNode
{
    BSTreeNode *left;  //left child;
    BSTreeNode *right; //right child;
    K key_;            //key
    V val;             //value

    BSTreeNode(const K &key, const V &value) //init
        : left(NULL), right(NULL), key_(key), val(value)
    {
    }
};

template <class K, class V>
class BSTree
{
    typedef BSTreeNode<K, V> Node;

public:
    BSTree()
        : root_(NULL)
    {
    }
    test()
    {
        root->rigrightht;//this is error;
    }
};
```
no warning;

**Comment by Colengms** [comment]
Hi @danwangXia .  It's currently by-design that squiggles are not provided within templates.  This is also the behavior of VS.  (We share IntelliSense with VS).  However, VS has UI allowing for arg types to be manually provided.  The following issue tracks adding that feature to the C/C++ Extension as well: https://github.com/microsoft/vscode-cpptools/issues/1946
