### ISSUE TITLE
setting include in c_cpp_properties.json not working

### ISSUE THREAD

**Issue by qt1** [microsoft/vscode-cpptools#6317]
**Type: LanguageService**

Intelisens marks include as "error detected"

setting the appropriate settings according to docs or automatically does not stop the error report.

I have found many references to similar situation' all resolved in "change the configuration file. Yet this does not help.

**Describe the bug**
- OS and Version:
Ubuntu 20.04

- VS Code Version:
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:01:33.073Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic

- C/C++ Extension Version:
1.1.0-insiders

- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: 
no

- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

This is how it looks. Pressing the "fix" buttons adds lines to the configuration file but does not stop the error report.

![vscode_include_problem](https://user-images.githubusercontent.com/7355327/95990675-7c370180-0e34-11eb-9127-e8bef9d61de1.png)

**Additional context**

The config file:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/src/**",
                "${workspaceFolder}/build",
                "${workspaceFolder}/vendor/spdlog/include/",
                "${workspaceFolder}/vendor/nlohmann_json/single_include",
                "${workspaceFolder}/vendor/**",
                "${workspaceFolder}/vendor/nlohmann_json/single_include",
                "${workspaceFolder}/vendor/nlohmann_json/single_include"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}/src",
                    "${workspaceFolder}/build",
                    "${workspaceFolder}/vendor"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "defines": [],
            "compilerPath": "/usr/bin/g++-10",
            "cStandard": "c11",
            "cppStandard": "c++20",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
I'm not able to repro this. Where is the missing header located?

**Comment by qt1** [comment]
Hi,

Thanks for the question! I tried to find a trivial example but then I found that after commenting out the following from `settings.json`

     "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",

The problem is gone.

I suspect this has something to do with the cmake tools extension and inconsistent cache.
I am removing the 'cmake tools' and I'll manage everything by hand..

**Comment by sean-mcmanus** [comment]
Ah, yeah, if you have C_Cpp.default.configurationProvider set, then the includePath won't be used for files managed by the configuration provider. It's not supposed to show the "Add to include path" code action in that case (I'm not able to repro that with a configuration provider set). If you do a C/C++ Log Diagnostics, it should report "Custom configurations" that are received from CMake Tools.
