### ISSUE TITLE
Remote debugging with gdb - breakpoints are not working

### ISSUE THREAD

**Issue by oktonion** [microsoft/vscode-cpptools#632]
## System info

- VSCode Version: 1.11.1

- extension Version: 0.10.5

- OS Version: Ubuntu 14.04 LTS

## Issue

Trying to attach to GDB server on QNX remote system. After recreating steps from #321 issue I finally was able to connect and run my application on remote host with this script:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "./TestImitator_g",
            "cwd": "/root/Projects/TestImitator/x86/o-g/",
            "stopAtEntry": false,
            "linux": {
                "MIMode": "gdb",
                "miDebuggerPath": "/opt/qnx650/host/linux/x86/usr/bin/ntox86-gdb",
                "miDebuggerServerAddress": "10.42.0.42:8000",
                "launchCompleteCommand": "exec-run",
                "customLaunchSetupCommands": [
                {
                    "description": "Connecting to QNX qdebug",
                    "text": "target qnx 10.42.0.42:8000",
                    "ignoreFailures": false
                },
                {
                    "description": "Loading symbol table",
                    "text": "file /media/alexander/C216B9FC16B9F191/TestImitator_g",
                    "ignoreFailures": true
                },
                {
                    "description": "Uploading",
                    "text": "upload /media/alexander/C216B9FC16B9F191/TestImitator_g /root/Projects/TestImitator/x86/o-g/TestImitator_g",
                    "ignoreFailures": true
                }
            ]
            },
            
             
            
            "logging": {
                "engineLogging": true,
                "trace": true, 
                "traceResponse": true
            },
            "targetArchitecture": "x86"
        }
    ]
}
```

However when inserting breakpoint in my cpp files I get the 

> ERROR: Error while trying to enter break state. Debugging will now stop. Failed to find thread 1 for break event

caused by 

> 1: (2399) ->1008*stopped,reason="breakpoint-hit",disp="keep",bkptno="1",thread-id="1",frame={addr="0x0805fa76",func="MainWindow_Opening",args=[{name="widget",value="0x80e4e10"},{name="apinfo",value="0x80472a8"},{name="cbinfo",value="0x80473f0"}],file="/root/Projects/TestImitator/src/MainWindow_Opening.cpp",line="354"}
> 1: (2399) ->(gdb)
> 1: (2419) <-1009-thread-info
> 1: (2420) ->1009^error,msg="Undefined mi command: thread-info (missing implementation)"
> 1: (2420) ->(gdb)
> 1: (2423) 1009: elapsed time 3
> E output: {"category":"stderr","output":"ERROR: Error while trying to enter break state. Debugging will now stop. Failed to find thread 1 for break event\n","data":null,"type":"output"}

As I understand error message the question is: how could I disable sending mi command **thread-info** when breakpoint is hit or overwrite this by my implementation like I did in **customLaunchSetupCommands** for connecting to GDB server and loading symbols from file.
Or could your team provide other solution to this.

**Comment by pieandcakes** [comment]
@oktonion the `-thread-info` command is how we build our thread cache and then request stack frames. I don't think we'd work properly if we didn't send -thread-info.

**Comment by oktonion** [comment]
@pieandcakes, I see. So could I somehow override your implementation of breakpoint command? I will be happy with just some simple *break filename:linenum* or similar.

**Comment by pieandcakes** [comment]
@oktonion Most of that logic is in https://github.com/Microsoft/MIEngine if you wanted to take a look.

**Comment by oktonion** [comment]
@pieandcakes Thank you for response, I'll take a look. But unability to use VSCode to debug code on remote QNX host is making me sad. Could I use an option to connect (over ssh f.e.) to remote machine with your extension and then run gdb directly without using the server? If yes then how?

**Comment by pieandcakes** [comment]
@oktonion You can SSH directly to the local version of gdb using SSH by using the `pipeTransport` configuration within the `launch.json`. You can find the documentation [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md).

It will still call `-thread-info` though.

**Comment by oktonion** [comment]
@pieandcakes finaly was able to upgrade my gdb so -thread-info is implemented int it. Debuging over SSH works like charm however not all variables are shown correcly (like class members) and not able to put breakpoints on go when debuging is started already. Will try to reproduce it to send a bug report. This issue can be closed I think.
