### ISSUE TITLE
when i do my debugging it doesn't take any input

### ISSUE THREAD

**Issue by irfan-hossain-bhuiyan** [microsoft/vscode-cpptools#6322]
Issue Type: <b>Bug</b>

I am using g++ exe debugger.Because others is not working.In g++ debugger it is okay overall but in cin>>variable it doesn't take any input not from debug console or terminal.

Extension version: 1.0.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.52GB free)|
|Process Argv|--crash-reporter-id e154b062-c64b-4aa8-8867-3638ddc17c20|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by WardenGnaw** [comment]
Are you using `"externalConsole": true` or `"externalConsole": false`? 

If you are using externalConsole true, there should be a terminal for you to input into. Else if it is false, you can use the integrated terminal. 

DebugConsole is used to evaluate variables or send commands to the debugger.

**Comment by irfan-hossain-bhuiyan** [comment]
Yeah,external window:false
