### ISSUE TITLE
The argc and argv of "main()" are wrong when set multiple arguments (Linux version only)

### ISSUE THREAD

**Issue by lifpan** [microsoft/vscode-cpptools#633]
When debug C++ code with launch mode, in function "main()", the "argc" is awalys 2 when set multiple arguments. (Linux version only)

E.g.

launch.json:
      ...
      "program": "/media/lifeng/ocean/llvm/llvm-3.7.0.src/builder/bin/llc ",
      "args": ["mytest.ll -print-after-all"],
      ...
      "linux": {
        "MIMode": "gdb",
        "setupCommands": [
          {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
          }
        ]
      },

Expect:
argc: 3;
argv[0]: /media/lifeng/ocean/llvm/llvm-3.7.0.src/builder/bin/llc
argv[1]: mytest.ll
argv[2]: -print-after-all

**Comment by pieandcakes** [comment]
@lifpan the issue is that you are passing it as a single argument. if you want 2 arguments, you need to comma separate each one:
`"args": ["mytest.ll", "-print-after-all"],`

That should resolve what you are running in to.

**Comment by lifpan** [comment]
It works. Thanks!
