### ISSUE TITLE
Changing gnu11 to c11 or a similar change doesn't have any effect until a Reload Window occurs when compileCommands is set

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6332]
It's potentially confusing when dealing with gnu versus non-gnu configuration issues (see https://github.com/microsoft/vscode-cpptools/issues/6279 ). In addition to confusing users, it could confuse us developers when we try to repro issues and changing the cStandard doesn't work as expected, leading to a non-repro.

This is a regression compared to 0.29.0.

**Comment by Colengms** [comment]
What do you expect to see?  We don't do anything with gnu standard versions other than convert them to non-gnu standard versions before passing them to edge, right?  Is there something I'm missing?

**Comment by sean-mcmanus** [comment]
Use this repro code
```
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <netinet/in.h>
#include <unistd.h>

int main(int argc, char *argv[])
{
    char buffer[PATH_MAX];
    struct in6_addr a, b;

    puts(optarg);
    IN6_ARE_ADDR_EQUAL(&a, &b);

    return 0;
}

```

It should squiggle with c11 and not squiggle with gnu11.

The gnu part needs to be preserved when querying the compiler so that certain system defines are used.

**Comment by Colengms** [comment]
I'm not able to repro this issue.  When switching the cStandard from c11 to c17 (On Linux, with gcc 10), I immediately see it probe the compiler with the new standard.  I see a number of different defines in the new TU.  After reloading the workspace, I see exactly the same TU data as before reloading.

Perhaps your are seeing another issue, perhaps stale diagnostics?

I also don't get squiggles with that code, with either c11 or gnu11 mode, having reloaded the window with each setting.

**Comment by sean-mcmanus** [comment]
It squiggles on Linux with gcc 10.2.

However, I'm not reproing the bug now...I don't know what changed.

**Comment by sean-mcmanus** [comment]
The repro requires compileCommands to be set.

Squiggles with c11 may not repro on Windows with mingw/gcc-8. I used Linux/gcc-10.
