### ISSUE TITLE
Pretty printing of types in gdb is not taken into account for pointers

### ISSUE THREAD

**Issue by JacquesLucke** [microsoft/vscode-cpptools#6334]
Type: Debugger

- OS and Version: Linux x64 5.8.14-arch1-1
- VS Code Version: 1.50.0
- C/C++ Extension Version: 1.0.1

**Bug Description**

A custom pretty printer for gdb is not taken into account in the *variables* and *watch* window. It does work when the variable is a struct, but not when it is a pointer to a struct.

![image](https://user-images.githubusercontent.com/5881326/96262493-21331500-0fc2-11eb-985d-4dfc114f9484.png)

**Steps to Reproduce**
1. Create the files listed below in a new directory.
2. Compile `main.c` (`gcc main.c -g`). That generates `a.out`.
3. Set a breakpoint on the return statement and start debugging.
4. See how the `[Sum]` field is only shown in some cases in the *variables* and *watch* window.

`main.c`
```c
typedef struct MyStruct {
  int a, b;
} MyStruct;

int main(int argc, char const *argv[]) {
  MyStruct s1 = {4, 6};
  MyStruct *s2 = &s1;
  return 0;
}
```
`pretty_print.py`
```python
import gdb

class MyStructPrinter:
    def __init__(self, value):
        self.value = value

    def children(self):
        yield "[Sum]", self.value["a"] + self.value["b"]
        yield "a", self.value["a"]
        yield "b", self.value["b"]

def lookup_pretty_printer(value):
    if value.type.code == gdb.TYPE_CODE_TYPEDEF:
        if value.type.name == "MyStruct":
            return MyStructPrinter(value)

gdb.printing.register_pretty_printer(None, lookup_pretty_printer)
```
`.vscode/launch.json`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "text": "source /home/jacques/Documents/gdb_print_test/pretty_print.py"
                }
            ]
        }
    ]
}
```

**Comment by WardenGnaw** [comment]
In order for pointers to be pretty printed, you will need to handle the case of `val.type.code == gdb.TYPE_CODE_PTR or val.type.code == gdb.TYPE_CODE_MEMBERPTR` in `lookup_pretty_printer`

**Comment by JacquesLucke** [comment]
I did try that before, however that does come with its own problems.

1. Now `s1` and `s2` are both displayed as struct in the *variables* window. Therefore, you cannot see what is a pointer and what is not. Furthermore, you can't see the address that `s2` points to anymore.
![image](https://user-images.githubusercontent.com/5881326/96291603-94e81880-0fe8-11eb-9ddc-92efae745d85.png)

2. It fails to display anything in cases like the one below. That probably happens due to an exponentially growing number of children, that makes it very slow. Note, that this is a very simplified example. My actual use case was more complex, but the fundamental issue seems to be the same (I'm trying to [simplify Blender debugging](https://github.com/JacquesLucke/blender_pretty_printers), that's very WIP, since I just started learning about the gdb api a few days ago).
![image](https://user-images.githubusercontent.com/5881326/96292067-4edf8480-0fe9-11eb-91da-dc3cf20ea7cb.png)

**Comment by WardenGnaw** [comment]
1. This seems to be the behavior by design. If you want to see if the address, you will need to include printing the address in the children. 
2. The debug adapter in the cpptools extension does not build/develop on the pretty printing features. We just send the information for GDB to use. However, we do enumerate through all the frames in the stack and their variables so that will be slow. There is currently no way to quickly retrieve all the variables in all the stackframes without making it an individual request.

You can report bugs/perf issues to https://sourceware.org/bugzilla/

**Comment by JacquesLucke** [comment]
Thanks for your responses!

> This seems to be the behavior by design. If you want to see if the address, you will need to include printing the address in the children.

Yes, I did that. That partially mitigates the problem. It does make it a less comfortable, though.

> The debug adapter in the cpptools extension does not build/develop on the pretty printing features.

I understand that. I just thought that since I can get all the information from gdb manually in the terminal, this vscode extension could just ask gdb for the "more useful" (from my perspective at least) information.

Maybe I'm simply missing, but seems to be more useful to show the same information when expanding `s1` and `s2`. I'm not sure how the extension decides that it should just show all the data members when expanding `s2`. Is this decision made by gdb? Instead, I'd think that it should show the pretty printed `*s2`, when `s2` is expanded.

I haven't found a way to customize how `s2` is visualized in the *variables* window, without the two issues in my previous post.

Currently, I do not think that this is a gdb bug, but simply a matter of what information this extension requests from gdb. Maybe I'll have to try to change the extension myself to better understand the implications. Right now I don't see any problems/disadvantages of my requested change.

**Comment by WardenGnaw** [comment]
What commands are you sending to gdb that provide the information that you expect in the terminal?

We are always looking to improve the experience and at the moment, we get the information for locals is by sending:
`-var-create - * "<variable>"`.

The response for a pointer is:
`^done,name="var6",numchild="1",value="0x871a08",type="Object *",thread-id="1",has_more="0"`

When you click to expand it, we send 
`-var-list-children --simple-values "<from-var-create>.private" 0 1000`

You can see the commands we send to gdb by adding logging to your launch.json:
```
"logging": {
   "engineLogging": true
}
```

**Comment by JacquesLucke** [comment]
Thanks for the information! I'm done for the today. I will report back tomorrow or next week. Have a good day.

**Comment by JacquesLucke** [comment]
I haven't had enough time to further look into this in the last couple of days. I'll close this until I've got some more information.
