### ISSUE TITLE
Syntax Coloring Stops working if 2d array is hit that is split across lines.

### ISSUE THREAD

**Issue by tmaslach** [microsoft/vscode-cpptools#6335]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.50.1
- C/C++ Extension Version: 1.0.1
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

When defining an 2d array with long symbol names, I have to split the statement on two lines due to an 80 character limit.  This causes all coloring to stop working after the statement.

**Steps to reproduce**

1. Create a new file in vscode, make sure to save it with .cpp extension.
2. Paste the following contents into the new file:
```
// comment1 - nice and green
int ItIsAReallyLongVariableNameWith[A_REALLY_LONG_CONSTANT_NAME_HERE]
                                   [AND_A_REALLY_LONG_CONSTANT_NAME_HERE];

// comment2 - it's unfortunately white and everything below as well
typedef const int OtherStuff;

class Test
{
};
```
3. The code will look like this in VSCode:
![image](https://user-images.githubusercontent.com/7267036/96267122-71e04900-0f95-11eb-9750-9d67db5201dc.png)

Notice everything after the 2d array is white.

**Expected behavior**
If you move the `[AND_A_REALLY_LONG_CONSTANT_NAME_HERE]` to the line above, everything starts working correctly again. This is how the above code should behave for 'comment2' and below:
![image](https://user-images.githubusercontent.com/7267036/96267416-bf5cb600-0f95-11eb-9f23-ddeaf6c70e5b.png)

**Comment by Colengms** [comment]
Hi @tmaslach .  Does the happen when the C/C++ Extension is disabled?  The C/C++ Extension provides semantic colorization (colorization of symbols that essentially require compilation to identify).  Syntax highlighting is actually still handled by VS Code, and is based on TextMate grammar for C/C++.  This repo that is the source of the C/C++ TextMate grammar used by VS Code, is here: https://github.com/jeff-hykin/cpp-textmate-grammar

**Comment by tmaslach** [comment]
Ah! I didn't realize coloring existed without the C/C++ Extension.  You are right, with it disabled, the problem still happens. I have posted this in the textmate repo you mentioned: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/510

I will close this out..
