### ISSUE TITLE
Correct Code Mismarked

### ISSUE THREAD

**Issue by UndefBhvr** [microsoft/vscode-cpptools#6338]
Issue Type: <b>Bug</b>
![屏幕截图 2020-10-17 134249](https://user-images.githubusercontent.com/46280451/96329446-73863b80-107f-11eb-9166-e1f23b2e7b6c.jpg)

This program can be successfully compiled by MinGW-w64 gcc 8.1.0.
But it is marked by C/C++ IntelliSense.
```cpp
#include<cstdio>
#include<algorithm>

struct treap
{
    struct Node;
    Node *root;

	treap():
		root(NULL)
	{}

	treap(const treap &_Src):
		root(get_same_node(_Src.root))
	{}

    Node *get_node(int);
    Node *get_same_node(Node*);

	Node *merge(Node*,Node*);
	void split(Node*,int,Node*&,Node*&);
};

struct treap::Node
{
    int val,sum,size,pri;
    bool rev;
    Node *lc,*rc;
    treap *this_tree;
    
    Node(int Value):
        val(Value),
        sum(val),
        size(1),
        pri(rand()),
        rev(0),
        lc(NULL),
        rc(NULL),
        this_tree(NULL)
    {}

	void version_keep()
	{
		if(lc!=NULL&&lc->this_tree!=this_tree)
		{
			lc=this_tree->get_same_node(lc);//This line
		}
	}
	void push_down(){};
	void maintain(){};
};

int main()
{}
```

Extension version: 1.0.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.01GB free)|
|Process Argv|--crash-reporter-id 607dc872-fe4f-48ca-b7ee-e540cba2be15 --crash-reporter-id 607dc872-fe4f-48ca-b7ee-e540cba2be15|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug on VS (for our shared parser): https://developercommunity.visualstudio.com/content/problem/1226014/cc-intellisense-gives-incorrect-e0513-and-e0167-er.html

**Comment by bobbrow** [comment]
Related to #3883?

**Comment by sean-mcmanus** [comment]
@bobbrow No, it's not related.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
