### ISSUE TITLE
Querying the compiler fails when compileCommands is used for a file with spaces

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6339]
@dslijepcevic Thanks for the info -- the incorrect logging "Compiler probe command line: "/usr/bin/cc" -g /proj/test2/test file.c -std=gnu11 -Wp,-v -E -dD -x c -m64  /dev/null" helped me figure it out -- the "/proj/test2/test file.c" test should not be there, most likely a bug in the code that removes the `-c <arg>`. I was able to get the bug repro by deleting the compilerPath from my c_cpp_properties.json, so a potential workaround would be to add that. We should have a fix in our next Insiders release.

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode-cpptools/issue_comments/710757287_

**Comment by Colengms** [comment]
The command line as posted here appears incorrect.  There must be quotes around the path that contains the filename with a space in it.  Otherwise, the content after the space appears as an entirely separate arg.

```
/proj/test2/test file.c
```

Should be:

```
"/proj/test2/test file.c"
```

Or, in compile_commands.json, more correctly:

```
\"/proj/test2/test file.c\"
```

**Comment by sean-mcmanus** [comment]
Did you see https://github.com/microsoft/vscode-cpptools/issues/6279#issuecomment-712409324 ?

**Comment by Colengms** [comment]
Sorry, I had mistakenly trusted the compiler probe command line.  I can repro, and have a fix.
