### ISSUE TITLE
console.integratedTerminal support in launch.json?

### ISSUE THREAD

**Issue by bitjson** [microsoft/vscode-cpptools#634]
Is it possible for the C++ debugger to support the `console.integratedTerminal` property in `launch.json`? It's mentioned in [this documentation](https://code.visualstudio.com/docs/editor/debugging), but doesn't seem to be implemented.  

(Also mentioned here: https://github.com/Microsoft/vscode/issues/16890)

**Comment by pieandcakes** [comment]
@bitjson We have an issue on our backlog to do this work: #371

**Comment by vrbadev** [comment]
Any progress at this issue? I'm really looking forward to the implementation of this feature...

**Comment by Muny** [comment]
I also wish for this feature to be implemented.

**Comment by macmillen** [comment]
+1

**Comment by lentotski** [comment]
+1

**Comment by mrkrynmdsco** [comment]
+1

**Comment by maximegregoire** [comment]
+1

**Comment by voltflake** [comment]
Could this be done?

**Comment by pieandcakes** [comment]
@daniladyabin This is done by setting `externalConsole` to `false`.

**Comment by LauritsLL** [comment]
Yes I am also really looking forward to this feature being added!
Any news yet?

**Comment by pieandcakes** [comment]
My [previous comment](https://github.com/microsoft/vscode-cpptools/issues/634#issuecomment-571770770) explains how to use the integrated terminal. If this doesn't work, please file a new issue.

**Comment by LauritsLL** [comment]
@pieandcakes It doesn't help at all to use `externalConsole: false`, and I don't think that this should be an issue, as it doesn't seem like this is a bug. What about a new property like `console: ‘integratedTerminal’`, like in python, which would then show all output in integrated terminal?

**Comment by pieandcakes** [comment]
@WardenGnaw Can you look into this?
