### ISSUE TITLE
Windows Scripting Host

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vscode-cpptools#6340]
https://github.com/microsoft/vscode/issues/108847#issue-723683735

**Comment by DBJDBJ** [comment]
Basically, this changes the Windows behaviour for "some customers". Namely, the ones who have

1. installed VS Code
2. are using *.js files from a command line 

If I am windows admin and if I try to run my js file from a command line as I did for last 20+ years, I do not want VS Code opened with it instead.

I assume this is a matter of registry setup for when  VSCode is installed. Can I kindly suggest we do not escalate this one?  @sean-mcmanus  who do we talk to?

**Comment by sean-mcmanus** [comment]
It would be a VS Code issue (or a Windows issue?).

**Comment by DBJDBJ** [comment]
@sean-mcmanus  many thanks for a reply. It is a windows issue provoked by VS Code installation. namely WSH (aka Windows Scripting Host) does not function as it was after Electron "hijacks" the `*.js` files as a part of VS Code installation.

Namely `cscript.exe` looses its association with `*.js` files. 

To repeat

write `wrong.js`
```json
// wrong: there is no dom in WSH
alert("wrong");
```
Try to execute it on its own. VS code opens it. You close the VS Code and command line displays:
```
[main 2020-10-23T05:20:40.652Z] update#setState idle
(node:13572) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:13572) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:8416) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
```
Now execute: `cscript wrong.js`. You are prompted with 
```
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

...\wrong.js(3, 1) Microsoft JScript runtime error: Object expected
```

I assume a simple script might re-associate `*.js` files with cscript.exe. But ideally, VSCode should not touch that in the first place?

![image](https://user-images.githubusercontent.com/145155/96960024-9a21f780-1501-11eb-999a-bc8da58358b1.png)

**Comment by bobbrow** [comment]
This issue would be caused by the VS Code editor, not the C++ extension.  If you could open an issue here: https://github.com/microsoft/vscode/issues/new/choose, the right team should be able to take a look.

Thank you!
