### ISSUE TITLE
Incorrect highlighting of override and final C++ modifiers if both are used

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#6345]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 / Linux Ubuntu 16.04
- VS Code Version: 1.50.1
- C/C++ Extension Version: 1.0.1 (and 1.1.0-insiders2 too)
- Other extensions you installed (and if the issue persists after disabling them): Issue is present after disabling other extensions.
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

If both modifiers (```override``` and ```final```) are used in a row, only the last of them is highlighted:

**Steps to reproduce**
1. Paste the code below to the vscode editor with C++ language mode:
```c++
class A
{
    public:
    A() {};
    virtual ~A() {};
    
    virtual void test() {};
};

class B : public A
{
    public:
    B() {};
    virtual ~B() {};
    
    virtual void test() override final {};
};
```
2. See that ```final``` is highlighted correctly, whereas ```override``` not.

**Expected behavior**
Both modifiers are highlighted.

**Screenshots**
Only ```final``` is highlighted:
![image](https://user-images.githubusercontent.com/13915612/95676219-2e689200-0bc5-11eb-81db-f1baf180c320.png)
Only ```override``` is highlighted:
![image](https://user-images.githubusercontent.com/13915612/95676252-4b04ca00-0bc5-11eb-8bcb-0d3663983933.png)

**Comment by Colengms** [comment]
Hi @r44083 I believe this repros with the C/C++ Extension disabled.  Is that correct?  The C/C++ Extension provides semantic colorization, which colors symbols that essentially require compilation to identify.  Syntactic colorization is actually still handled by VS Code, using their TextMate C/C++ grammar.  The source of that grammar is this repo: https://github.com/jeff-hykin/cpp-textmate-grammar   I would suggest following up with an issue there.
