### ISSUE TITLE
Compiler's default includes in `systemIncludePath`

### ISSUE THREAD

**Issue by dslijepcevic** [microsoft/vscode-cpptools#6346]
The documentation on `systemIncludePath` states: "We may want to provide a VS Code command to populate this value from the compiler's default for users who are interested in using it in case they want to make some modifications to the defaults."

This exactly describes what I would like to do. Is this command already implemented somewhere? If not, can we get the compiler defaults with a "${default}" entry?

Thanks

**Comment by bobbrow** [comment]
We might need to update that documentation.  `systemIncludePath` was added before we supported querying the values directly from the compiler.  You should be able to get the behavior you want by setting `C_Cpp.default.compilerPath`.  Please let us know if that meets your needs.

**Comment by dslijepcevic** [comment]
I would like to have a combination of those two: default includes from the compiler **and** some extra system include directories that are not normally in the include path (sources for a system library). Is this currently possible to achieve? The same documentation mentions that system includes are stripped away from normal include and browse path. Last time I tried specifying both `C_Cpp.default.compilerPath` and `C_Cpp.default.systemIncludePath` the latter took priority and did completely override compiler defaults.

**Comment by sean-mcmanus** [comment]
Currently it uses either the compilerPath's system includes or the systemIncludePath without combining them. Are you able to add those additional system includes in the includePath?

**Comment by dslijepcevic** [comment]
Unfortunately no. And the documentation says anything that looks like a system path is ignored in user includes. I think this could be easily solved by allowing "${default}" entry in `C_Cpp.default.systemIncludePath` that would insert compiler paths.

**Comment by sean-mcmanus** [comment]
And are you able to determine why adding it to C_Cpp.default.includePath doesn't work, i.e. when you do C/C++: Log Diagnostics, what is wrong with the resulting Includes that are used? We only consider it a system include if it matches what the compilerPath returns as a system include, and we exclude it in that case, because it causes the include path ordering to be incorrect. The only potential difference with using systemIncludePath instead of includePath and compilerPath should be the ordering (i.e. system include paths occur after the non-recursive include paths).

**Comment by dslijepcevic** [comment]
Thanks for the clarification. It actually works with `C_Cpp.default.includePath`. The documentation on `C_Cpp.default.systemIncludePath` was a bit confusing about silent removal of (any) system includes.

**Comment by bobbrow** [comment]
Thanks for confirming.  Yes, this should work with:

**settings (User/Workspace)**
```jsonc
  "C_Cpp.default.compilerPath": "/path/to/compiler",  // Add system includes to the includePath
  "C_Cpp.default.includePath": [
    "/extra/path"
  ],
```

**c_cpp_properties.json**
```jsonc
  "includePath": [
    "/local/path",
    "${default}"  // include the paths from C_Cpp.default.includePath
  ]
```
