### ISSUE TITLE
Support for gcc-10 -fcoroutines flag

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode-cpptools#6349]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.50.1
- C/C++ Extension Version: 1.0.1
- C/C++ Extension doesn't honor gcc-10's `-fcoroutines` flag

The code (e.g. boost/asio) uses feature check like
```
#   if (__cplusplus >= 201709) && (__cpp_impl_coroutine >= 201902)
```
Which results in squiggles when I create file with coroutines (For example this: https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/example/cpp17/coroutines_ts/refactored_echo_server.cpp)

Apparently gcc version 10 implies __cpp_impl_coroutine=201902 when `-fcoroutines` flag is specified on the command line (See also https://gcc.gnu.org/projects/cxx-status.html)

If I hack `bin/msvc.json` in the extension folder to
```
    "defaults": [
        ...
        "-D__cpp_impl_coroutine=201902"
    ]
```

I see no squiggles and code navigation works better.

I also noted that `__cplusplus` is defined as `201709` (when hovering over it) even though command-line flag is `-std=c++2a`.

**Comment by sean-mcmanus** [comment]
This appears fixed with our 1.1.0-insiders2 release (i.e. __cpp_impl_coroutine is defined when c++20 is used). Can you try setting C_Cpp.updateChannel to "Insiders" to try that out?

**Comment by ytimenkov** [comment]
Hmm... I already have `C_Cpp.updateChannel` set to "Insiders" however I don't see any updates...
I use Remote SSH extension but C/C++ are on 1.0.1 both locally and remotely.

**Comment by ytimenkov** [comment]
Ok, maybe "autoUpdate" needs to be set to true (which I have set to false).

After manually downloading vsix I can confirm that `__cpp_impl_coroutine` correctly seen by IntelliSense.
