### ISSUE TITLE
Handle all comments as Doxygen when there are Doxygen comments in code base

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6353]
I'm trying to encourage the adoption of Doxygen + VSCode for a complex code base, and this silly inconsistency in how the comments are handled is a sore point. 

Any chance of seeing an improvement in the near future?

_Originally posted by @tlemo in https://github.com/microsoft/vscode-cpptools/issues/6235#issuecomment-712373405_

**Comment by michelleangela** [comment]
To add context, the feature request is to handle all comments as Doxygen comments when there are Doxygen comments and non-structured or simple comments in the project. That is also handle non-structured comments such as ~~`// This is a simple comment`~~ `//! function comment` for a function as Doxygen as well.

A possible user-experience solution is to add a setting on how comments are handled.

Update:
Handle comments with the same Doxygen comment style (such as `//!`) as Doxygen.

**Comment by tlemo** [comment]
Thanks @michelleangela for opening this issue.

A small clarification: the goal is to handle all the valid Doxygen comments, as defined by the Doxygen parser itself. `// This is a simple comment` is not a Doxygen comment (and the default handing for comments seems perfectly reasonable so there's nothing to change in this case. 

The only problem I noticed is that `//!` comments are not correctly recognized as Doxygen comments, which leads to the `!` being included in the comment text (as demonstrated in #6235)

**Comment by michelleangela** [comment]
@tlemo 

Thank you for clarifying and sorry for missing the `//!` part.

**Comment by tlemo** [comment]
Sigh. It's not the end of the world, but it's sad to see fit-and-polish features dropped on the floor, especially when implementing the fix would likely take less than then effort to report and debate the issue.

**Comment by sean-mcmanus** [comment]
Another user reported the same issue with VS a year ago at https://developercommunity.visualstudio.com/idea/433955/support-doxygen-style-suffix-comments.html and the issue was marked as "fixed" but it's not really fixed. @tlemo Are you able to file an issue with VS? That might increase the likelihood of the change making it to VS Code. Otherwise, we could file an issue on your behalf (I commented on the original issue that the user's comment wasn't addressed).

I'm not sure if this is a fit-and-finish (quick fix) issue or a larger design/implementation change.

**Comment by tlemo** [comment]
thanks for the pointer @sean-mcmanus. If you can file a VS issue to for this would be fantastic!

**Comment by sean-mcmanus** [comment]
I've filed a feature request at https://developercommunity.visualstudio.com/idea/1302034/c-doesnt-handle-doxgyen-comments-correctly-for-hov.html . It might need more upvotes though.
