### ISSUE TITLE
[Error - 2:46:36 AM] Connection to server got closed. Server will not be restarted. /root/.local/share/code-server/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools: 1: /root/.local/share/code-server/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools: Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by foreverhui** [microsoft/vscode-cpptools#6355]
[Error - 2:46:36 AM] Connection to server got closed. Server will not be restarted.
/root/.local/share/code-server/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools: 1: /root/.local/share/code-server/extensions/ms-vscode.cpptools-1.0.1/bin/cpptools: Syntax error: word unexpected (expecting ")")

using C++ extension@1.0.1 with code-server，having this error。cause I can't use other extensions above c++ extension。

**Comment by sean-mcmanus** [comment]
Same issue as https://github.com/microsoft/vscode-cpptools/issues/6190 . Our extensions doesn't support running in code-server.
