### ISSUE TITLE
Standard libraries won't link [Win10]

### ISSUE THREAD

**Issue by trincasidra** [microsoft/vscode-cpptools#636]
Hi,

I've searched land and sea for a solution to this, tried everything I came up with, asked everyone I know could help, asked in StackOverflow, but to no good. So here I am, I really don't know if I am doing something wrong, or it's cpptools who's doing something wrong.

What happens is; whenever I include a standard library, it tells me "Include file not found in include path.". Even with just a Hello World test. Below you'll find the code in images that showcase the problem. The fun fact is, I can compile the code without problems.

![no_include](https://cloud.githubusercontent.com/assets/15145418/25037458/7e564c86-20f9-11e7-8323-c88f5b7926f2.png)

![tasks](https://cloud.githubusercontent.com/assets/15145418/25037459/7f3a0516-20f9-11e7-8b08-daf2879a0f82.png)

![properties](https://cloud.githubusercontent.com/assets/15145418/25037544/ee488248-20f9-11e7-96b6-6a830a28d415.png)

![cmd](https://cloud.githubusercontent.com/assets/15145418/25037462/8134c02c-20f9-11e7-86df-2e2d6763a286.png)

Hope we can manage to fix this!

EDIT:  To clarify, I'm using Windows 10, and I do have the Windows 10 SDK installed, with the ucrt and everything. I also tried installing various Visual C++ and Runtimes, but to no good.

**Comment by sean-mcmanus** [comment]
Can you make sure this file exists and it's on the includePath: `C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/iostream`.

**Comment by trincasidra** [comment]
Hi, Thanks for the answer!
I don't have an includePath to that folder, as I don't have a Visual Studio other than Code installed. iostream isn't on my includePath, but for instance, string is, and I can't include it either.
![sin titulo](https://cloud.githubusercontent.com/assets/15145418/25048085/beaf3dce-213a-11e7-8c69-080be0fbdbf2.png)

**Comment by sean-mcmanus** [comment]
You'll need to obtain iostream from another library then; otherwise, you won't even be able to compile with iostream. I assume your g++ compiler has the headers somewhere.

**Comment by trincasidra** [comment]
Oh, thanks god! I searched for the include headers in g++ folders, included them, and voilà! I can't believe how much hours I have spent installing packages from MSDN... I just thought standard libraries were for granted.

So, really thanks a lot! Maybe this will help other stone-headed guys like me in the future :)
