### ISSUE TITLE
Intellisense can't see friend operator!= from friend operator==

### ISSUE THREAD

**Issue by zajo** [microsoft/vscode-cpptools#6362]
**Type: LanguageService**

This line in Boost LEAF implements `operator!=` in terms of `operator==`: https://github.com/boostorg/leaf/blob/develop/include/boost/leaf/error.hpp#L624

Intellisense reports:

```
{
	"resource": "/Users/zajo/Desktop/zajo/boost-git/libs/leaf/include/boost/leaf/error.hpp",
	"owner": "C/C++",
	"code": "349",
	"severity": 8,
	"message": "no operator \"==\" matches these operands -- operand types are: boost::leaf::error_id == boost::leaf::error_id",
	"source": "C/C++",
	"startLineNumber": 624,
	"startColumn": 24,
	"endLineNumber": 624,
	"endColumn": 24
}
```

I'm guessing it is confused by the fact that these are friend definitions (rather than member functions) that are accessible only via ADL.

More information:

```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Intellisense version: v1.1.0-insiders2
```

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug on our parser, shared with VS, at https://developercommunity.visualstudio.com/content/problem/1229376/c-intellisense-gives-error-no-operator-matches-the.html .

**Comment by zajo** [comment]
Thank you!
