### ISSUE TITLE
 C++ syntax highlighting error

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode-cpptools#6365]
Issue Type: <b>Bug</b>

In the "Cold Horizon" theme, `#define NULL ((void *)0)` shows incorrect syntax highlighting.
![屏幕截图 2020-10-21 191555](https://user-images.githubusercontent.com/20399194/96712941-73b16e80-13d2-11eb-9725-81d1a4f732ff.png)
![屏幕截图 2020-10-21 191751](https://user-images.githubusercontent.com/20399194/96712953-7744f580-13d2-11eb-973f-4b11bfbbe95c.png)
![屏幕截图 2020-10-21 191814](https://user-images.githubusercontent.com/20399194/96712957-77dd8c00-13d2-11eb-9fcc-ace3596b3308.png)

Extension version: 1.0.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.17GB free)|
|Process Argv|C:\Users\Test\Desktop\api.S --crash-reporter-id a73dd5f5-0be8-4f88-821e-9ec46cdb5893|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @mxdh .  Does this repro with the C/C++ Extension disabled?  The C/C++ Extension provides colorization of semantic tokens, which are symbols that essentially require compilation to identify.  Colorization based on syntax is still handled by VS Code, and is based on TextMate grammar for C/C++.  I'd suggest following up in this repo, which is the source of VS Code's TextMate grammar for C/C++: https://github.com/jeff-hykin/cpp-textmate-grammar

**Comment by mxdh** [comment]
Yes，it does.
Thank you.
