### ISSUE TITLE
"C/C++ Build and Debug Active File" and "F5" are causing the wrong build task to be run, i.e. the default build task is not run (it's using the pre-generated task)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6375]
@elahehrashedi The problem is that F5 (Build and Debug Active File) is causing the wrong build task to be run, i.e. the default build task is not run (it's using the pre-generated task). I see it working correctly when Run Build Task is used.

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode-cpptools/issues/6366#issuecomment-714684171_

**Comment by michelleangela** [comment]
What are the repro steps for this issue? Is this from creating a new build task or from an existing one?

**Comment by sean-mcmanus** [comment]
> What are the repro steps for this issue? Is this from creating a new build task or from an existing one?

F5 or Build and Debug Active File -- with no tasks.json/launch.json.

**Comment by Jianchaoliang** [comment]
unsubscribe


| |
菅朝梁
|
|
18205601716@163.com
|
签名由网易邮箱大师定制
On 11/4/2020 06:40，Elaheh Rashedi<notifications@github.com> wrote：

Closed #6375 via #6420.
