### ISSUE TITLE
"C/C++ build and debug active file" doesn't show the compilers path in the API

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cpptools#6376]
after running "C/C++: Build and debug active file"
![image](https://user-images.githubusercontent.com/16143955/96955345-3ae4c880-14aa-11eb-90a9-293b50c79e8f.png)
the compilers paths should be visible

**Comment by Jianchaoliang** [comment]
unsubscribe


| |
菅朝梁
|
|
18205601716@163.com
|
签名由网易邮箱大师定制
On 11/4/2020 08:19，Elaheh Rashedi<notifications@github.com> wrote：

Closed #6376 via #6435.
