### ISSUE TITLE
Format On Save (modifications) formats entire file when resolving merge conflicts

### ISSUE THREAD

**Issue by emptyVoid** [microsoft/vscode-cpptools#6378]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 Pro x64 2004 19041.572
- VS Code Version: 1.50.1 (system setup)
- C/C++ Extension Version: 1.0.1
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

With `Format On Save` enabled and `Format On Save Mode` set to **modifications** VSCode formats entire C++ file when saving the file while resolving merge conflicts.

**Steps to reproduce**

1. Edit GIT merge conflict.
2. Save the file.

**Expected behavior**

Only the modified parts should be formatted, rest should be left as is.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I didn't repro this in a normal edit/save scenario (only the modifications were formatted) -- can you confirm that that is the same behavior you're seeing, i.e. the bug only repros with a GIT merge conflict? I can investigate the Git Merge conflict scenario later.

**Comment by emptyVoid** [comment]
Yes, the issue manifests during GIT merge conflict only. Normal edits work as expected for me too.

**Comment by sean-mcmanus** [comment]
Okay, thanks. I've reproed the bug.

**Comment by sean-mcmanus** [comment]
This appears to be a bug with VS Code itself and not our extension. See the screenshot:
![image](https://user-images.githubusercontent.com/19859882/97644541-d5438f80-1a07-11eb-8331-0765bf31106a.png)

VS Code is sending us a range that encompasses the whole file (at https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/Providers/documentRangeFormattingEditProvider.ts#L17 ).

Can you file a bug at https://github.com/microsoft/vscode/issues ? If not, I could file one on your behalf.

**Comment by emptyVoid** [comment]
Originally I filed the bug as https://github.com/microsoft/vscode/issues/109022, though they deemed it as extention-caused.
Could you please add the info to that issue or may be open a new one.

**Comment by sean-mcmanus** [comment]
I asked them to reopen it.

**Comment by sean-mcmanus** [comment]
Looks like they fixed the bug in VS Code Insiders...might have to wait till tomorrow's build (not sure).
