### ISSUE TITLE
Can't run C program, Remote-SSH, Ubuntu Server 20.10 on Raspberry Pi 4

### ISSUE THREAD

**Issue by gitspeaks** [microsoft/vscode-cpptools#6385]
Local Setup: VS Code 1.50.1 running on Windows 10 (PC)
Remote Setup: Ubuntu Server 20.10 (32bit) running on Raspberry Pi 4 (4gb) (OS Boot from USB Flash Drive. No SD Card inserted)

Post Ubuntu Server installation:

sudo apt install build-essential
sudo apt-get install gdb

Successfully established SSH connection through Windows Terminal to remote Ubuntu Server.

1. Opened Remote-SSH connection through VS Code to Ubuntu host.
2. Created C file.
3. Installed C/C++ Extension, ms-vscode.cpptools, v1.1.0-insiders3.
4. Configured Default Build Task “C/C++: gcc build active file” - tasks.json.
5. Clicked "Run without Debugging" (C file is the active tab)
6. Selected "C++ (GDB/LLDB)". Selected "gcc - Build and debug active file" - launch.json

Editor stuck in debugging with the following message displayed in the Terminal view:

```
&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"
```

VS Code auto-generated config files:

launch.json:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gcc - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: gcc build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```

tasks.json:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: gcc build active file",
			"command": "/usr/bin/gcc",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}/${fileBasenameNoExtension}"
			],
			"options": {
				"cwd": "/usr/bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: /usr/bin/gcc"
		}
	]
}
```
Screenshots:

![1](https://user-images.githubusercontent.com/37540903/97085470-58d73800-1626-11eb-9b7b-d135a7ebd01d.png)
![2](https://user-images.githubusercontent.com/37540903/97085478-5d035580-1626-11eb-93a9-2a6c71b16955.png)
![3](https://user-images.githubusercontent.com/37540903/97085483-5ffe4600-1626-11eb-9e83-d92f37cdd506.png)
![4](https://user-images.githubusercontent.com/37540903/97085488-62f93680-1626-11eb-8fc0-bcf5c3c3170f.png)

**Comment by gitspeaks** [comment]
Installed new Ubuntu Server 20.10 (64bit) image on WSL according to:

https://discourse.ubuntu.com/t/installing-ubuntu-20-10-on-wsl/18941

from:

https://cloud-images.ubuntu.com/groovy/current/groovy-server-cloudimg-arm64-wsl.rootfs.tar.gz

Here I'm able to run the program in a Remote-WSL session taking the same steps and extension version as I detailed initially.

![5](https://user-images.githubusercontent.com/37540903/97087012-8ffe1700-162f-11eb-9411-cf053a2cefc5.png)

**Comment by gitspeaks** [comment]
Installed new Ubuntu Server 20.10 (64bit) image on WSL from:

https://cloud-images.ubuntu.com/groovy/current/groovy-server-cloudimg-amd64-wsl.rootfs.tar.gz (*)

by running:

```
cmd.exe /C "wsl.exe --import Ubuntu-20.10 %USERPROFILE%\WSL\Groovy %USERPROFILE%\Downloads\groovy-server-cloudimg-amd64-wsl.rootfs.tar.gz --version 2"
```

as instructed by:

https://discourse.ubuntu.com/t/installing-ubuntu-20-10-on-wsl/18941

Here I'm able to run the program in a Remote-WSL session taking the same steps and extension version as I detailed initially.

![5](https://user-images.githubusercontent.com/37540903/97087194-c8eabb80-1630-11eb-8f2b-12d347b692ac.png)

(*) WSL 2 Distro boot message states: "Welcome to Ubuntu 20.10 (GNU/Linux 4.19.128-microsoft-standard x86_64)"

**Comment by gitspeaks** [comment]
This issue is specific to Pi 4 running Ubuntu Server 20.10 32bit. 

Things work OK on 64bit.

**Comment by WardenGnaw** [comment]
Can you enable logging and share it to help us figure out which command it is stuck on?

```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

Thank you.

**Comment by gitspeaks** [comment]
Attached.

[log.txt](https://github.com/microsoft/vscode-cpptools/files/5444799/log.txt)

**Comment by davidgurnsey** [comment]
relevant: https://bugs.launchpad.net/ubuntu/+source/gdb/+bug/1901966
