### ISSUE TITLE
More support on symbol resolved of the include files of std

### ISSUE THREAD

**Issue by yamsjix** [microsoft/vscode-cpptools#6387]
**Type: C/C++**

**Describe the bug**
- All windows version :
- All versions:
- C/C++ Extension Version 1.50/1.48/1.46...:
- I'm read/write project log4c  on windows, All files include and ABI symbol from c/c++ std cannot be resolved.

**Steps to reproduce**

1. Open project of log4c.
2. Open file  appender_type_mmap.c
3. Errors occurses at  all includes such as fcntl.h and sys/mman.h

**Expected behavior**

Want more support on all symbol resolved of the include files of std. What's more, addtions symbols and include files can be added in the config files.

- 

**Screenshots**

![Snipaste_2020-10-26_09-43-29](https://user-images.githubusercontent.com/64062253/97125730-cd69be00-176f-11eb-804c-349f185f44c1.png)

**Comment by Colengms** [comment]
Hi @yamsjix . `sys/mman.h` is linux system header, which would explain why it was not found on Windows.  You would likely need to configure your `c_cpp_properties.json` with the appropriate #defines macros, etc., such that the project is configured for Windows.  The C/C++ Extension essentially needs the same information as the build system, as IntelliSense involves compilation. 
 When using VS Code and the C/C++ Extension, there is not a built-in build system, so some project-specific manual configuration may be required.

There are some 'configuration provider' extensions, that can ingest this information from the build system.  For example, the CMake Tools extension will do this for projects that use CMake.  Your project appears to be makefile based.  We do have a Makefile config provider extension in development, but it's not yet generally available.

**Comment by yamsjix** [comment]
Thanks for @Colengms 's answer. Emm, I just want to hide this warning message.
What's more,  a new improve is my ideas, which analyze smoothly without fully supported compiler, after written some symbols configurations or describes.

**Comment by Colengms** [comment]
Hi @yamsjix One way you could hide those warning would be to create empty header files of those names, and add an include path that points to them.  Unfortunately, we don't currently have a way to arbitrarily disable specific warnings.  Would you like to use this issue to track a feature request for that or a similar capability?

**Comment by yamsjix** [comment]
Yeah， I am looking forward.

**Comment by yamsjix** [comment]
> Hi @yamsjix One way you could hide those warning would be to create empty header files of those names, and add an include path that points to them. Unfortunately, we don't currently have a way to arbitrarily disable specific warnings. Would you like to use this issue to track a feature request for that or a similar capability?

Yeah， I am looking forward.

**Comment by Colengms** [comment]
https://github.com/microsoft/vscode-cpptools/issues/2814 is currently tracking adding a way to disable specific errors/warnings.  Closing this as a duplicate.
