### ISSUE TITLE
Windows ARM64 debugging doesn't work

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6392]
cppvsdbg/cl.exe debugging doesn't work.

cppdbg/mingw-w64 debugging doesn't work if std::vector/string/etc. are used.

**Comment by Alovchin91** [comment]
Hi @sean-mcmanus Is this blocked by the extension or by Windows itself? I'm asking because Rust debugging on Windows currently depends on C/C++ extension.

**Comment by sean-mcmanus** [comment]
Our extension. I believe the debugger team is scheduled to implement this...might be available for 1.6.0 in August.

**Comment by Alovchin91** [comment]
Thanks! That's great to know; it's one of the final missing pieces to get a decent Rust development environment on Windows arm64 🙂

**Comment by sean-mcmanus** [comment]
Fixed with 1.5.0 (https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0).
