### ISSUE TITLE
Can't correctly highlight the code

### ISSUE THREAD

**Issue by alphagocc** [microsoft/vscode-cpptools#6398]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Window 10 20H2 19042.608
- VS Code Version: 1.50.1
- C/C++ Extension Version: 1.0.1

**Steps to reproduce**

![image](https://user-images.githubusercontent.com/28982331/97278298-90d3ba80-1874-11eb-9e69-06d4a836f879.png)
Write code like above
return if and [] aren't highlight
But IntelliSense and autocomplete is OK

**Comment by sean-mcmanus** [comment]
I don't understand. Can you provide a complete code example? What type of highlighting are you referring to?

**Comment by alphagocc** [comment]
Ok
I've modified my code
You can see the problem more clear.
![image](https://user-images.githubusercontent.com/28982331/97399777-cc2fc100-1928-11eb-82ef-241078be978a.png)
The full code i've pasted here
https://paste.ubuntu.com/p/QmZKpzwNxT/

**Comment by Colengms** [comment]
Hi @alphagocc .  The C/C++ extension provides colorization for semantic tokens, which are symbols that essentially require compilation to identiy.  For syntactic tokens, colorization is provided by VS Code and it's TextMate grammar for C/C++.  The source of that TextMate grammar in VS Code is this repo: https://github.com/jeff-hykin/cpp-textmate-grammar   There is often some time between when fixed are made to the grammar and when VS Code ingests those changes.  There is an extension "Better C++ Syntax" which you can use to pick up those changes sooner.  With that extension enabled, the issues you pointed out appear to already be addressed.
