### ISSUE TITLE
"Include file not fount in include directory" when header files has no .h exstension

### ISSUE THREAD

**Issue by Miniwoffer** [microsoft/vscode-cpptools#64]
Currently running ubuntu 16.04 LTS 64-bit.

The C/C++ for Visual Studio Code extension, does not seem to detect header files that does not have a .h extension in the include path. 

When renamed the header files and added a .h extension, it seemed to find it no problem. 

I experienced this when i tried to include this library https://www.webtoolkit.eu/wt

Extension ver: 0.6.1

Vs code ver: 1.2.0

**Comment by jhasse** [comment]
But `iostream` works for me. The problem might be something else then the file extension.

**Comment by sridmad** [comment]
There are two issues.
1. Colorization. There is no colorization for extension less files.
2. Populating database with contents from these files: We have a hard coded list for STL files. We have to figure out a way to allow devs to add additional files to the list in an update.

**Comment by jgoshi** [comment]
The fix will be available in the next release, version 0.8.0

**Comment by hmny** [comment]
Using version `1.7.1` and still have this problem for `<sys/time.h>`, `<stdlib.h>`, `<stdio.h>` etc.
