### ISSUE TITLE
Improve exposure of cpp.hint

### ISSUE THREAD

**Issue by iq2luc** [microsoft/vscode-cpptools#640]
Code completion issues happening in Linux (but I guess it behaves the same in Windows).
Example:

```c
#define PRIVILEGED_FUNCTION __attribute__((section("privileged_functions")))
#define DUMMY_DEFINE

void foo(bool x, int y);
void bar1(bool x, int y) __attribute__((section("privileged_functions")));
void bar2(bool x, int y) (__attribute__((section("privileged_functions"))));
void zap1(bool x, int y) PRIVILEGED_FUNCTION;
void zap2(bool x, int y) (PRIVILEGED_FUNCTION);
void duh1(bool x, int y) DUMMY_DEFINE;
void duh2(bool x, int y) (DUMMY_DEFINE);

int main() {
   foo(true, 1);   // Code completion works
   bar1(true, 1);  // Code completion works
   bar2(true, 1);  // Code completion works, but suggests 'void bar2(bool x, int y)()' <--- notice another pair of brace at the end
   zap1(false, 0); // Code completion fails <--- press Ctrl+Shift+Space after 'zap1('
   zap2(true, 1);  // Code completion works, but suggests 'void zap2(bool x, int y))' <--- notice double brace at the end
   duh1(false, 0); // Code completion fails <--- press Ctrl+Shift+Space after 'duh1('
   duh2(true, 1);  // Code completion works, but suggests 'void duh2(bool x, int y))' <--- notice double brace at the end
}
```

c_cpp_properties.json snippet:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ]
}
```

**Comment by sean-mcmanus** [comment]
Unfortunately, our parser doesn't handle #defined attributes at the end of functions well, so all of them need to be included in the cpp.hint text file that is in the root of the extension folder (i.e. at /home/user/.vscode/extensions/ms-vscode.cpptools-version), so adding the #define lines below to that file should fix the issue. Later we could look into adding a setting for this so it's easier to add things too. I'm not familiar with the (__attribute) syntax so I'm not sure what the expected behavior is, but we could look into fixing that later too.
`
#define PRIVILEGED_FUNCTION
#define DUMMY_DEFINE
`

**Comment by iq2luc** [comment]
Hi Sean,

thank you for your prompt response.

Regarding the (__attribute) syntax comment -- there is nothing specific about parentheses, I just noticed that when I placed the defined __attribute inside the parentheses it kind of works (see comments above).

As I just started to evaluate VS Code + cpptools extension, I didn't know about cpp.hint file, I will give it a try. In my line of work (bare metal software development), declaring attributes for functions is very common.

Thanks,
Luc

**Comment by markchuaca** [comment]
I am new to vscode and it seems autocomplete is not working at all for me...
OS version: ubuntu 16.04
VS Code version: 1.11.2
Cpptools versoin: 0.10.5
Did i miss something in my installation?

**Comment by sean-mcmanus** [comment]
@yeguicai Are you using 32-bit Ubuntu? What is the behavior of Microsoft.VSCode.CPP.Extension.linux?

**Comment by bobbrow** [comment]
@iq2luc, did the cpp.hint solution work for you?

**Comment by iq2luc** [comment]
Hi @bobbrow , yes, the `cpp.hint` workaround suggested by @sean-mcmanus worked.

I just added `#define PRIVILEGED_FUNCTION __attribute__((section("privileged_functions")))` to `~/.vscode/extensions/ms-vscode.cpptools-0.10.5/cpp.hint` and after re-parsing the source code everything was OK.

Sorry for replying so late.

Thanks,
Luc

**Comment by bobbrow** [comment]
Thank you. We can use this issue to track potential improvements in how the extension consumes cpp.hint since currently any changes you make to it will be overwritten by the extension when you update to a newer version.
