### ISSUE TITLE
VS Code does not properly disconnect the debug adapter in Remote SSH Extension if connection is lost

### ISSUE THREAD

**Issue by skipper2cic** [microsoft/vscode-cpptools#6402]
Type: General

After reboot the remote machine, SSH connection was stable for a while, then disconnection repeats again.
The followings were shown even the user has not been connected via vscode for several days.

ps auwx | grep vscode
root 5898 0.0 0.0 112712 984 pts/7 S+ 17:01 0:00 grep --color=auto vscode
user 28392 0.0 0.1 920200 48596 ? Sl Oct22 0:00 /home/user/.vscode-server/extensions/ms-vscode.cpptools-1.1.0-insiders2/debugAdapters/mono.linux-x86_64 --config /home/user/.vscode-server/extensions/ms-vscode.cpptools-1.1.0-insiders2/debugAdapters/framework/config.linux /home/user/.vscode-server/extensions/ms-vscode.cpptools-1.1.0-insiders2/debugAdapters/bin/OpenDebugAD7.exe

**Describe the bug**
- OS and Version: Windows 10 (remote machine: CentOS 7)
- VS Code Version:  1.50.1
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them): Remote-Development, Vim
- A clear and concise description of what the bug is.

**Comment by WardenGnaw** [comment]
Is the process that is being debugged still alive? 

If the VS Code client crashes or does not have the ssh connection to send a `disconnect` request to the debug adapter, there is no good way for it to know to close unless the debugged process dies.

**Comment by WardenGnaw** [comment]
Closing due to not enough information and being an SSH Extension scenario.
