### ISSUE TITLE
variable uint8_t is not a type name issue with a not supported compiler

### ISSUE THREAD

**Issue by mnschipper** [microsoft/vscode-cpptools#6406]
**Type: LanguageService**

Hi,
I am using VSCode 1.50.1 with C/C++ IntelliSense extension 1.1.0-insiders3 on Windows 10 in combination with a very old IAR cross compiler. This compiler and the libraries don't support a stdint.h include file. So, I created my own types.h file. In this header file there is a typedef for a uitn8_t type. Some lines below this typedef a new type is defined based on the uint8_t  type. Now IntelliSense is showing red error squiggels below the uint8_t type definition with the error variable "uint8_t" is not a type name (see screen shot below).

![image](https://user-images.githubusercontent.com/73600753/97457864-706e3380-193a-11eb-9ed9-3d14a184cde0.png)

I discovered it has something to do with the MEMORY_ATTRIBUTE define between the typedefs:

#define MEMORY_ATTRIBUTE	near_func

When hovering over near_func IntelliSense is telling "\<error-type\> near_func" 
When I comment this line out uint8_t and uint32_t are correct recognized as types. However uint16_t is still not recognized as a type.

I see a lot of users having problems with this stdint types to get recognized by IntelliSense and that they have to solve these by setting correct compiler type, defines etc. But I am not using a gcc based compiler. And in this case the error is already shown in the same file where the uint8_t type is defined.

Kind regards,

Martijn Schipper

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @mnschipper .  I'm unable to easily repro your issue, so I'd like to get more information about how things are getting configured for you.  Could you share the following?

 * The output in the `C/C++` output channel leading up to the repro, with `"C_Cpp.loggingLevel": "Debug"` set.
 * The output in the `C/C++ Diagnostics` channel having run `C/C++: Log Diagnostics` after the repro.
 * The output in the `C/C++ Configuration Warnings` channel, if any.

If the extension is unable to probe a compiler (which only works for cl.exe and gcc/clang based compilers), it is likely falling back to the default compiler found on your system.  The error your are seeing may be related to that compiler.  A possible work-around might be to set `compilerPath` to an empty string (`""`) in `c_cpp_properties.json`, which instructs the extension not to probe the compiler.

**Comment by mnschipper** [comment]
Hi @Colengms,

Here is the loggings of the C/C++ output channel:
`cpptools/didChangeCppProperties`
`Skipping probe of compiler due to explicitly empty compilerPath`
`Code browsing service initialized`
`Skipping probe of compiler due to explicitly empty compilerPath`
`  Folder: C:/SOFTWARE4.Y/MBX2/ will be indexed`
`Populate include completion cache.`
`textDocument/didOpen: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c`
`Discovering files...`
`cpptools/activeDocumentChange: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c`
`cpptools/textEditorSelectionChange`
`cpptools/getDocumentSymbols: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 2)`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 3)`
`cpptools/getDocumentSymbols`
`  Processing folder (recursive): C:/SOFTWARE4.Y/MBX2/`
`cpptools/getFoldingRanges: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 4)`
`cpptools/getDocumentSymbols: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 5)`
`cpptools/abortRequest`
`cpptools/getDocumentSymbols`
`sending compilation args for C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C`
`  include: C:\IAR\INC`
`  include: C:\SOFTWARE4.Y\MBX2\INCLUDE`
`  include: C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\INCLUDE`
`  define: NEC`
`  define: DO_PIM`
`  define: MAAS_EPURSE`
`  define: WIN32=0`
`  define: __GNUC__=0`
`  define: RPI=0`
`  other: --gcc`
`  other: --gnu_version=100000`
`  stdver: c89`
`  intelliSenseMode: gcc-arm`
`cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 6)`
`cpptools/getFoldingRanges: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 7)`
`Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c`
`Queueing IntelliSense update for files in translation unit of: C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C`
`  Discovering files: 3739 file(s) processed`
`  77 file(s) removed from database`
`Done discovering files.`
`Parsing remaining files...`
`  Parsing: 0 files(s) processed`
`Done parsing remaining files.`
`cpptools/finishUpdateSquiggles`
`Error squiggle count: 294`
`Update IntelliSense time (sec): 1.146`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 8)`
`idle loop: reparsing the active document`
`Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c`
`Queueing IntelliSense update for files in translation unit of: C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C`
`cpptools/finishUpdateSquiggles`
`Error squiggle count: 294`
`Update IntelliSense time (sec): 0.337`
`cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 9)`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 10)`
`Database safe to open`
`textDocument/hover: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 11)`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 12)`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 13)`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 14)`
`textDocument/didOpen: file:///c%3A/software4.Y/mbx2/Include/Types.h`
`Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Include/Types.h`
`Queueing IntelliSense update for files in translation unit of: C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C`
`cpptools/activeDocumentChange: file:///c%3A/software4.Y/mbx2/Include/Types.h`
`cpptools/textEditorSelectionChange`
`cpptools/getDocumentSymbols: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 15)`
`cpptools/textEditorSelectionChange`
`cpptools/getDocumentSymbols`
`cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 16)`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 17)`
`cpptools/finishUpdateSquiggles`
`Error squiggle count: 294`
`Error squiggle count: 44`
`Update IntelliSense time (sec): 0.607`
`cpptools/getFoldingRanges: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 18)`
`idle loop: reparsing the active document`
`Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Include/Types.h`
`Queueing IntelliSense update for files in translation unit of: C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C`
`cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 19)`
`cpptools/finishUpdateSquiggles`
`Error squiggle count: 294`
`Error squiggle count: 44`
`Update IntelliSense time (sec): 0.382`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 20)`
`cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 21)`
`cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 22)`
`textDocument/hover: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 23)`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 24)`
`textDocument/hover: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 25)`
`textDocument/hover: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 26)`
`textDocument/hover: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 27)`
`textDocument/hover: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 28)`
`cpptools/activeDocumentChange: file:///c%3A/software4.Y/mbx2/Include/Types.h`
`cpptools/textEditorSelectionChange`
`idle loop: reparsing the active document`
`Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Include/Types.h`
`Queueing IntelliSense update for files in translation unit of: C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C`
`cpptools/finishUpdateSquiggles`
`Error squiggle count: 294`
`Error squiggle count: 44`
`Update IntelliSense time (sec): 0.379`
`cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 29)`
`cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 30)`
`cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 31)`

And here the loggings of the C/C++ Diagnostics:
`-------- Diagnostics - 29-10-2020 10:25:01`
`Version: 1.1.0-insiders3`
`Current Configuration:`
`{`
`    "name": "Win32",`
`    "includePath": [`
`        "${workspaceFolder}/**"`
`    ],`
`    "defines": [],`
`    "compilerPath": "",`
`    "cStandard": "c89",`
`    "cppStandard": "c++17",`
`    "intelliSenseMode": "gcc-arm",`
`    "compilerArgs": [`
`        "-IC:/IAR/INC/",`
`        "-DNEC",`
`        "-DDO_PIM",`
`        "-DMAAS_EPURSE",`
`        "-DWIN32=0",`
`        "-D__GNUC__=0",`
`        "-DRPI=0",`
`        "-IC:/software4.Y/mbx2/include/",`
`        "-IC:/software4.Y/mbx2/projects/mb/include/",`
`        "-e",`
`        "-g",`
`        "-K",`
`        "-Lout/",`
`        "-ml",`
`        "-P",`
`        "-q",`
`        "-z9"`
`    ],`
`    "browse": {`
`        "path": [`
`            "${workspaceFolder}/**"`
`        ],`
`        "limitSymbolsToIncludedHeaders": true`
`    },`
`    "intelliSenseModeIsExplicit": true,`
`    "cStandardIsExplicit": true,`
`    "cppStandardIsExplicit": true,`
`    "compilerPathIsExplicit": true`
`}`
`Translation Unit Mappings:`
`[ C:\software4.Y\mbx2\Projects\MB\Drivers\Network\ctn.c ]:`
`    C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C`
`    C:\SOFTWARE4.Y\MBX2\INCLUDE\TYPES.H`
`Translation Unit Configurations:`
`[ C:\software4.Y\mbx2\Projects\MB\Drivers\Network\ctn.c ]:`
`    Process ID: 12752`
`    Memory Usage: 21 MB`
`    Includes:`
`        C:\IAR\INC`
`        C:\SOFTWARE4.Y\MBX2\INCLUDE`
`        C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\INCLUDE`
`    Defines:`
`        NEC`
`        DO_PIM`
`        MAAS_EPURSE`
`        WIN32=0`
`        __GNUC__=0`
`        RPI=0`
`    Standard Version: c89`
`    IntelliSense Mode: gcc-arm`
`    Other Flags:`
`        --gcc`
`        --gnu_version=100000`
`Total Memory Usage: 21 MB`

`------- Workspace parsing diagnostics -------`
`Number of folders and files enumerated: 5426`
`Number of files discovered (not excluded): 3739`

As you can see I already set the the `compilerPath` to an empty string. But as I see now from these loggings the `compilerArgs` are still used.
**I have removed these compilerArgs and now it seems to work OK!**
So, I will play a little with defines/compilerArgs to get an optimal configuration for my environment.
Thanks a lot for the help.

**Comment by mnschipper** [comment]
I found what compiler argument was causing this issue `-D__GNUC__=0`.
Still weird that when I specify I am not using a GNU C compiler IntelliSense is going mad on stdint types??

**Comment by mnschipper** [comment]
Hmmm, I was to early with my conclusion that it works now.
After switching between 2 files the errors squiggles are there again :-(
This is the log output:
<pre>
cpptools/didChangeCppProperties
Skipping probe of compiler due to explicitly empty compilerPath
Code browsing service initialized
Skipping probe of compiler due to explicitly empty compilerPath
  Folder: C:/SOFTWARE4.Y/MBX2/ will be indexed
  Folder: C:/IAR/INC/ will be indexed
textDocument/didOpen: file:///c%3A/software4.Y/mbx2/Include/Types.h
Populate include completion cache.
Discovering files...
Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Include/Types.h
cpptools/activeDocumentChange: file:///c%3A/software4.Y/mbx2/Include/Types.h
cpptools/textEditorSelectionChange
  Processing folder (recursive): C:/SOFTWARE4.Y/MBX2/
cpptools/getDocumentSymbols: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 2)
cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 3)
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 4)
  Processing folder (recursive): C:/IAR/INC/
  Discovering files: 3816 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 5)
cpptools/getDocumentSymbols: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 6)
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 7)
sending compilation args for C:\SOFTWARE4.Y\MBX2\LIBS\FUNCTION\STABLES.C
  include: C:\SOFTWARE4.Y\MBX2\INCLUDE
  include: C:\IAR\INC
  include: C:/SOFTWARE4.Y/MBX2/INCLUDE
  define: NEC
  define: DO_PIM
  define: MAAS_EPURSE
  other: --gcc
  other: --gnu_version=100000
  stdver: c89
  intelliSenseMode: gcc-arm
Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Include/Types.h
Shutting down IntelliSense server: C:\SOFTWARE4.Y\MBX2\LIBS\FUNCTION\STABLES.C
Closing the communication channel.
sending compilation args for C:\SOFTWARE4.Y\MBX2\LIBS\FUNCTION\STABLES.C
  include: C:\SOFTWARE4.Y\MBX2\INCLUDE
  include: C:\IAR\INC
  include: C:/SOFTWARE4.Y/MBX2/INCLUDE
  define: NEC
  define: DO_PIM
  define: MAAS_EPURSE
  other: --gcc
  other: --gnu_version=100000
  stdver: c89
  intelliSenseMode: gcc-arm
Queueing IntelliSense update for files in translation unit of: C:\SOFTWARE4.Y\MBX2\LIBS\FUNCTION\STABLES.C
idle loop: reparsing the active document
Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Include/Types.h
Queueing IntelliSense update for files in translation unit of: C:\SOFTWARE4.Y\MBX2\LIBS\FUNCTION\STABLES.C
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 2.134
textDocument/hover: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 8)
textDocument/hover: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 9)
textDocument/hover: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 10)
textDocument/hover: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 11)
cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 12)
textDocument/didOpen: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c
cpptools/activeDocumentChange: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 13)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 14)
sending compilation args for C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C
  include: C:\SOFTWARE4.Y\MBX2\INCLUDE
  include: C:\IAR\INC
  define: NEC
  define: DO_PIM
  define: MAAS_EPURSE
  other: --gcc
  other: --gnu_version=100000
  stdver: c89
  intelliSenseMode: gcc-arm
Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c
Queueing IntelliSense update for files in translation unit of: C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C
cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 15)
idle loop: reparsing the active document
cpptools/getFoldingRanges: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 16)
Shutting down IntelliSense server: C:\SOFTWARE4.Y\MBX2\LIBS\FUNCTION\STABLES.C
Closing the communication channel.
Checking for syntax errors: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c
Queueing IntelliSense update for files in translation unit of: C:\SOFTWARE4.Y\MBX2\PROJECTS\MB\DRIVERS\NETWORK\CTN.C
cpptools/finishUpdateSquiggles
Error squiggle count: 294
Error squiggle count: 44
Update IntelliSense time (sec): 1.237
cpptools/getSemanticTokens: file:///c%3A/software4.Y/mbx2/Include/Types.h (id: 17)
cpptools/getCodeActions: file:///c%3A/software4.Y/mbx2/Projects/MB/Drivers/Network/ctn.c (id: 18)
</pre>

**Comment by mnschipper** [comment]
Ok, now I know what was causing the problem: compiler specific types. I have added these as empty defines and now it works like a charm.
<pre>
             "defines": [
               "callt=",
                "near_func=",
                "far=",
                "huge="
              ],
</pre>
