### ISSUE TITLE
Launch.json for WSL does not allow for relative address of program to launch and debug

### ISSUE THREAD

**Issue by TryerGit** [microsoft/vscode-cpptools#6407]
Type: Debugger

WSL does not allow for relative address in launch.json for "program" to launch.
- OS and Version: Windows 
- VS Code Version: 1.50
- C/C++ Extension Version:1.0.1
- Other extensions you installed (and if the issue persists after disabling them): C++ Intellisense 0.2.2, multi-command 1.4.0, vscodevim, vscode-pdf. Yes
WSL debug configuration in launch.json only accepts absolute address starting with /mnt/<path.to.executable> for "program", while for pure windows debugging and pure linux debugging, relative addresses suffice.

Any simple C++ file, even one included in official VSCode documentation (https://code.visualstudio.com/docs/cpp/config-wsl) should do. 

My launch.json file looks like this:

```
"version": "0.2.0",
"configurations": [
    {
        "name": "(gdb)DbgLaunch",//For pure linux machine
        ...
        "program": ".vscode/dist/Debug/GNU-Linux/linux",
        ...
    },
    {
        "name": "(WSLgdb) Launch",//For WSL under windows machine
        ...
        "program": "/mnt/c/myproject/.vscode/dist/Debug/GNU-Linux/linux",
        ...
    },
    {
        "name": "(Windows)DbgLaunch",//For pure windows machine
        ...            
        "program": ".vscode/x64/Debug/windows.exe",
        ...
    }
]
```
On launching "(WSLgdb) Launch" on WSL, with the full path to executable "linux" works fine. However, if a relative address is provided such as:

 "program": ".vscode/dist/Debug/GNU-Linux/linux"

VSCode in WSL complains that the path to executable is not found. Relative addresses work fine under "(gdb)DbgLaunch" and "(Windows)DbgLaunch" configurations above for debugging and launching.

**Comment by WardenGnaw** [comment]
I could not get the relative path to work for the windows case. If you want to use relative paths, you will want to use `${workspaceFolder}`. 

E.g. `${workspaceFolder}/.vscode/x64/Debug/windows.exe`

By design, we validate that the program exists if you are debugging without `pipeTransport`, since this is the one GDB will be spawning.
https://github.com/microsoft/MIEngine/blob/2268582b48c40e416ecf656e6b7878decfbc2673/src/OpenDebugAD7/AD7DebugSession.cs#L155

**Comment by prahaladvenkateshan** [comment]
@WardenGnaw I am not sure what you tried. But if there is a .vcxproj inside the .vscode folder, then the following task within tasks.json compiles and builds the executable just fine.

```
    {
            "label": "winbuilddebug",
            "type": "shell",
            "command": "msbuild",
            "args": [
                ".vscode/windows.vcxproj",
                "/property:GenerateFullPaths=true",
                "/property:Configuration=Debug",
                "/property:Platform=x64",
                "/t:build",
                "/consoleloggerparameters:NoSummary"
            ],
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        },
```

Then, this task is referenced within launch.json thus:

```
{
            "name": "(Windows)DbgLaunch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": ".vscode/x64/Debug/windows.exe",
            "args": [],
            "preLaunchTask": "winbuilddebug",
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "internalConsoleOptions": "openOnSessionStart", 
        }
```

So, using ClCompile and MSBuild.exe from via vcxproj works just fine with relative addressing.

**Comment by TryerGit** [comment]
@WardenGnaw I am not sure how you tried it, but for me, using .vcxproj stored in the .vscode folder works just fine with relative addressing.

tasks.json:

```
    {
            "label": "winbuilddebug",
            "type": "shell",
            "command": "msbuild",
            "args": [
                ".vscode/windows.vcxproj",
                "/property:GenerateFullPaths=true",
                "/property:Configuration=Debug",
                "/property:Platform=x64",
                "/t:build",
                "/consoleloggerparameters:NoSummary"
            ],
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        },
```

This task is referenced in launch.json thus:

```
    {
            "name": "(Windows)DbgLaunch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": ".vscode/x64/Debug/windows.exe",
            "args": [],
            "preLaunchTask": "winbuilddebug",
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "internalConsoleOptions": "openOnSessionStart",
        },
```

With the above setup, I have been using relative addressing for path to the executable to launch and debug just fine under windows. It needs .vcxproj within .vscode folder and ClCompile and MSBuild. In other words, the .vcxproj created by Visual Studio IDE works just fine.

**Comment by TryerGit** [comment]
@WardenGnaw Using your suggestion, I have setup for linux as well as WSL, the same configuration that refers to 

`"program": "${workspaceFolder}/.vscode/dist/Debug/GNU-Linux/linux",`

and this works fine on both linux and WSL alike. So, there is no longer any need to have full path beginning `/mnt/` and therefore a separate configuration for WSL.

Thanks!

**Comment by WardenGnaw** [comment]
I believe `tasks.json` launches the shell in `${workspaceFolder}` so relative paths will work for any commands executed for that. 

Unfortunately the debugger requires a full path to the program.
A possible feature can be to check to see if the `program` path is a relative one and concat it with `cwd`.
