### ISSUE TITLE
Set .clang-format file as fallback

### ISSUE THREAD

**Issue by Chillee** [microsoft/vscode-cpptools#641]
I have a set of formatting options I like to use across projects, but doesn't quite align with any of the provided format. It would be an appreciated feature if I could provide one as a fallback.

I may take a crack at implementing this myself.

**Comment by sean-mcmanus** [comment]
clang-format itself doesn't allow setting the fallback_style to something custom but we could add that feature ourselves, like we did for the "Visual Studio" fallback_style, but allowing arbitrary styles in the same format as the "style" property. E.g.
`"C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: LLVM, UseTab: Always }"`.
Would that be okay or did you want a path to a settings file?

**Comment by Chillee** [comment]
I originally meant the second one, but I think your suggestion would be preferable. 

I noticed this extension doesn't have the source on this repository; is there no way for me to contribute this feature myself?

**Comment by sean-mcmanus** [comment]
Unfortunately, the extension is closed source.

**Comment by Chillee** [comment]
Well, that's unfortunate. Any particular reason why?

Either way, appreciate the responsiveness, and hope to see this feature in a future release!

**Comment by sean-mcmanus** [comment]
See https://github.com/Microsoft/vscode-cpptools/issues/457 for a discussion on why our extension is not "open source".

**Comment by sean-mcmanus** [comment]
This was added in 0.11.0, but bug https://github.com/Microsoft/vscode-cpptools/issues/604 will always cause the .clang-format file to not be looked at on Linux/Mac (which we plan to fix "soon").

**Comment by Chillee** [comment]
Thank you! It's really useful for me since I'm typically writing a lot of different small c++ projects.

**Comment by rivalak** [comment]
Why set   > "C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: LLVM, UseTab: Always }"   
cannot help me.

**Comment by sean-mcmanus** [comment]
@rivalak I don't understand what you're asking. Can you open a new issue with more info?

**Comment by rivalak** [comment]
> @rivalak I don't understand what you're asking. Can you open a new issue with more info?  

@sean-mcmanus Sorry to my late. I just cannot use the google format in my vscode by configuring the .clang-format, I don't know why, this really bother me. :sob:

**Comment by sean-mcmanus** [comment]
The .clang-format file should be picked up if it's in the workspace folder or a parent path. It's possible some error is occurring that is causing it to not be used. Can you [enable debug logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) to see if it shows any errors? What version of clang-format.exe are you using? We currently ship with 6.0 (we should probably update 9.0 after it's released).

**Comment by rivalak** [comment]
@sean-mcmanus Thanks for your advice. I am using 6.0 version of clang-format. I find "ctrl + shift + I" works well as my wish. And the issues about the format of auto-complete code snippets maybe caused by the 'Intellisense' extension.
