### ISSUE TITLE
Debugger: natvis breaks when using enum class template argument types 

### ISSUE THREAD

**Issue by JessyDL** [microsoft/vscode-cpptools#6422]
Type: Debugger

**Describe the bug**

Debugger does not display custom natvis visualizer when any of the template type arguments is an enum class. This does not happen in Visual Studio (showcasing the natvis itself is working), but does in VSCode.

- OS and Version: Windows_NT x64 10.0.19041 (using WSL2 Linux x64 4.4.0-19041-Microsoft)
- VS Code Version: Code 1.50.1 (d2e414d, 2020-10-13T15:06:15.712Z)
- C/C++ Extension Version: latest (v1.1.0-insiders3)
- Other extensions you installed (and if the issue persists after disabling them): CMake / CMake tools, which have no effect on this, disabling them had the same results.

**To Reproduce**
Given the following basic example code:
```
enum class bar_enum {};

template <bar_enum E = bar_enum{0}>
class foo
{
  public:
	int value{5};
};
```
accompanied by the following natvis
```
<?xml version="1.0" encoding="utf-8"?> 
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
  <Type Name="foo&lt;*&gt;">
    <DisplayString>{{ size=0 }}</DisplayString>
    <Expand>
    </Expand>
  </Type>
</AutoVisualizer>
```
You'll notice this works in Visual Studio, but not in VSCode.

Expected:
Debugger would use the natvis correctly and display the string. Note that any other template arg type does work, the moment an enum class is added is when it breaks.

launch.json:
```
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "debug (gdb)",
			"type": "cppdbg",
			"request": "launch",
			"program": "${workspaceFolder}/build/tests/psl_tests",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"visualizerFile": "${workspaceFolder}/natvis/psl.xml",
			"showDisplayString": true,
			"environment": [],
			"externalConsole": false,
			"MIMode": "gdb",
			"setupCommands": [
				{
					"description": "Enable pretty-printing",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			]
		}
	]
}
```

**Comment by Jianchaoliang** [comment]
unsubscribe
| |
菅朝梁
|
|
18205601716@163.com
|
签名由网易邮箱大师定制
On 11/3/2020 04:27，Jessy De Lannoit<notifications@github.com> wrote：

Closed #6422.
