### ISSUE TITLE
Debbuger doesn't change local variables to it's actual value.

### ISSUE THREAD

**Issue by frenchiveruti** [microsoft/vscode-cpptools#6423]
Issue Type: <b>Bug</b>

Given that images speak for a 1000 words. 
![imagen](https://user-images.githubusercontent.com/1095997/97870401-d841c700-1d0a-11eb-80ab-52f6d8dcfdf8.png)
![imagen](https://user-images.githubusercontent.com/1095997/97870459-ea236a00-1d0a-11eb-9891-c2698ebba06a.png)
![imagen](https://user-images.githubusercontent.com/1095997/97870476-ee4f8780-1d0a-11eb-9799-8e1ee89e74ba.png)

As you can see, the variable named "m" doesn't change when it reaches it's line of assignation to y. 
The program DOES change m to y when it reaches that line, but the debugger does not reflect that.  
If I print m it will be valued at 4.  

How to solve? Why does this happen? 
Thanks

Extension version: 1.0.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4007)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.28GB free)|
|Process Argv|D:\Google Drive\Facultad\Facultad 2018\FaMAF\Algoritmos y Estructuras de Datos 1\Proyecto 3 C\proyecto3.c --crash-reporter-id dd9fe75e-e210-4b1e-b705-6eade4254e9d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by frenchiveruti** [comment]
Here's the code if you want to check it out.
[proyecto3.zip](https://github.com/microsoft/vscode-cpptools/files/5475984/proyecto3.zip)

**Comment by WardenGnaw** [comment]
Can you enable logs and share the output up till you reach the `if (m < z)`.
```
"logging": {
   "engineLogging": true
}
```

**Comment by frenchiveruti** [comment]
> 
> 
> Can you enable logs and share the output up till you reach the `if (m < z)`.
> 
> ```
> "logging": {
>    "engineLogging": true
> }
> ```

You forgot to tell me where do I edit this line or where do I find this engineLogging parameter.

**Comment by WardenGnaw** [comment]
This will be in your `launch.json`.

**Comment by frenchiveruti** [comment]
> 
> 
> This will be in your `launch.json`.

Hi, this is my actual launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gcc.exe - Compilar y depurar el archivo activo",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Habilitar la impresión con sangría para gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: gcc.exe build active file"
        }
    ]
}
```

**Comment by frenchiveruti** [comment]
~~Where do I add it? Anywhere?~~

**Comment by frenchiveruti** [comment]
[Log output.txt](https://github.com/microsoft/vscode-cpptools/files/5478089/Log.output.txt)
Is this it? I think I did it

**Comment by WardenGnaw** [comment]
From the logs, you are using GDB 7.6.1 and it is reporting at line 118 the values of:
 `x` is `5`
`y` is `4`
`z` is `8`
`m` is `0`

Related logs:
```
1: (25675) ->*stopped,reason="end-stepping-range",frame={addr="0x00401889",func="ejercicio_4_b",args=[{name="x",value="5"},{name="y",value="4"},{name="z",value="8"},{name="m",value="0"}],file="D:\\Google Drive\\Facultad\\Facultad 2018\\FaMAF\\Algoritmos y Estructuras de Datos 1\\Proyecto 3 C\\proyecto3.c",fullname="D:\\Google Drive\\Facultad\\Facultad 2018\\FaMAF\\Algoritmos y Estructuras de Datos 1\\Proyecto 3 C\\proyecto3.c",line="118"},thread-id="1",stopped-threads="all"
1: (25730) <-1120-var-create - * "x"
1: (25730) ->^done
1: (25730) ->(gdb)
1: (25741) ->1120^done,name="var37",numchild="0",value="5",type="int",thread-id="1",has_more="0"
1: (25741) ->(gdb)
1: (25741) 1120: elapsed time 10
1: (25741) ->&"\n"
1: (25741) ->^done
1: (25741) ->(gdb)
1: (25741) <-1121-var-delete var37
1: (25752) ->1121^done,ndeleted="1"
1: (25752) ->(gdb)
1: (25752) 1121: elapsed time 10
1: (25752) ->&"\n"
1: (25752) ->^done
1: (25752) ->(gdb)
1: (25752) <-1122-var-create - * "y"
1: (25763) ->1122^done,name="var38",numchild="0",value="4",type="int",thread-id="1",has_more="0"
1: (25763) ->(gdb)
1: (25763) 1122: elapsed time 10
1: (25763) <-1123-var-delete var38
1: (25763) ->&"\n"
1: (25763) ->^done
1: (25763) ->(gdb)
1: (25774) ->1123^done,ndeleted="1"
1: (25774) ->(gdb)
1: (25774) 1123: elapsed time 10
1: (25774) ->&"\n"
1: (25774) ->^done
1: (25774) ->(gdb)
1: (25774) <-1124-var-create - * "z"
1: (25785) ->1124^done,name="var39",numchild="0",value="8",type="int",thread-id="1",has_more="0"
1: (25785) ->(gdb)
1: (25785) 1124: elapsed time 10
1: (25785) <-1125-var-delete var39
1: (25785) ->&"\n"
1: (25785) ->^done
1: (25785) ->(gdb)
1: (25796) ->1125^done,ndeleted="1"
1: (25796) ->(gdb)
1: (25796) 1125: elapsed time 10
1: (25796) <-1126-var-create - * "m"
1: (25796) ->&"\n"
1: (25796) ->^done
1: (25796) ->(gdb)
1: (25807) ->1126^done,name="var40",numchild="0",value="0",type="int",thread-id="1",has_more="0"
1: (25807) ->(gdb)
```

This would be a bug on GDB since the VS Code C++ extension is just an adapter to communicate with GDB with the extension.
I would recommend upgrading the version of GDB used. 

I did a quick test with your project with GDB 8.1 and the `m = y` seemed to be resolved there.

**Comment by frenchiveruti** [comment]
Alright, I wish my college gave me a better understanding on how the hell does GDB work and how to make it run **properly** on windows.  
Sadly they prefer the "Just use Linux" mantra and the "use linux or bye bye"
I am stuck with an unknown issue. You can close this thread because it seems has nothing to do with VS.Code
And you're right, I tried with GDB on a shell and it also has a problem on that function.

**Comment by frenchiveruti** [comment]
Hi, sorry to go off the topic but you may be able to help me with this one @WardenGnaw . I used MinGW and the installed version I have is indeed 7.6.1-1 but I don't have a newer version available to be installed, how can I find the source of my issue?

**Comment by sean-mcmanus** [comment]
@frenchiveruti Maybe see http://mingw-w64.org/doku.php/download ?

**Comment by sean-mcmanus** [comment]
Or https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download

**Comment by WardenGnaw** [comment]
If you are interested sticking with Windows, we recommend installing this version of [MinGW](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download) mentioned in our [docs](https://code.visualstudio.com/docs/cpp/config-mingw). 

If you are interested in more of a Linux like scenario, you can use the C++ extension with WSL with VS Code. 
See https://code.visualstudio.com/docs/cpp/config-wsl

**Comment by frenchiveruti** [comment]
Thank you both, I'll close this and try to solve the issue on my end. 
You both have been very helpful! 
Have a nice day :D

**Comment by frenchiveruti** [comment]
I ended up following this: https://code.visualstudio.com/docs/cpp/config-wsl
Great documentation, very easy to follow and it just works fine.

**Comment by Jianchaoliang** [comment]
unsubscribe
| |
菅朝梁
|
|
18205601716@163.com
|
签名由网易邮箱大师定制
On 11/3/2020 11:24，frenchiveruti<notifications@github.com> wrote：

I ended up following this: https://code.visualstudio.com/docs/cpp/config-wsl
Great documentation, very easy to follow and it just works fine.
