### ISSUE TITLE
Disable Error Squiggles for specific files.

### ISSUE THREAD

**Issue by pespinho** [microsoft/vscode-cpptools#6426]
**Type: LanguageService**

**Expected behavior**

It would be nice to have an option for disabling the error squiggles for specific files in the workspace.
Something like a gitignore file, but for error squiggles.

Use case: I have an arduino file in workspace that is not part of the main code in workspace. For this file it is nice to have the c/c++ highlights, but the squiggles are annoying.

**Comment by sean-mcmanus** [comment]
We're tracking this with https://github.com/microsoft/vscode-cpptools/issues/1231 .

**Comment by Jianchaoliang** [comment]
unsubscribe
| |
菅朝梁
|
|
18205601716@163.com
|
签名由网易邮箱大师定制
On 11/3/2020 05:47，Sean McManus<notifications@github.com> wrote：

Closed #6426.
