### ISSUE TITLE
Bug for not showing syntax errors

### ISSUE THREAD

**Issue by gerzarko** [microsoft/vscode-cpptools#6428]
Issue Type: <b>Bug</b>

the ide do not show the syntax error writted on porpouse for the errors in C language, I tried to disable and enable a lot of things and follow differents solutions that are in the web and in the vscode website.

Extension version: 1.1.0-insiders3
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|-psn_0_938213 --crash-reporter-id 67cae0b9-2fe3-4a37-bdc4-16de13afd90c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Does your code give errors with your compiler or only warnings? We only support showing squiggles for errors currently.

**Comment by Jianchaoliang** [comment]
unsubscribe
| |
菅朝梁
|
|
18205601716@163.com
|
签名由网易邮箱大师定制
On 11/3/2020 07:54，Sean McManus<notifications@github.com> wrote：

Does your code give errors with your compiler or only warnings? We only support showing squiggles for errors currently.

**Comment by gerzarko** [comment]
It give errors with the compiler, but when I have a syntax error it don't show it. And this is happening not only with the languages you have to compile all at once (C), it happens to with my python code too.

**Comment by sean-mcmanus** [comment]
The Python issue would have to be caused by another extension because our C/C++ extension doesn't provide Python language errors.

Does `int i&;` give an error? Is your C_Cpp.errorSquiggles setting set to "Disabled"? Otherwise, can you give a code example that doesn't show an error?

**Comment by gerzarko** [comment]
Perfect, I have a vscode error with the the json file. So I delete the file, and it works great now. Thank you and sorry for bothering.
