### ISSUE TITLE
Show Symbols List(Function List) in tree explorer viewlet

### ISSUE THREAD

**Issue by LiPengfei19820619** [microsoft/vscode-cpptools#643]
Many modern editors have an import feature: function list. It is very useful to view the outline of the c/c++ file.
Although vscode can view the symbols list via Ctrl-Shift-O, but many programmers prefer function list, I think.

So, I expect vscode can implement function list via the extension.

Thanks.

**Comment by sean-mcmanus** [comment]
We do show a function/class list (that also enables navigation) via clicking on the section to the left of the Ln# in the status bar (which should have a command and keyboard shortcut in the next update). Is that sufficient or did you want something else? FYI, VS Code currently doesn't enable extensions to add things like the EXPLORER tab tree view, if that's what you want, but maybe they'll add that ability later.

**Comment by LiPengfei19820619** [comment]
@sean-mcmanus  Thanks for your attention.
Yes, I can navigate via the status bar. 
Because I move from UltraEdit, I am customed to have a function list side by the main window(the code editor). I think it is very useful for me to see the outline of the code while I am writing code.
So I prefer the function list viewlet side by the code, it is very convenience.
As I know, many editors for programmers have a function list view side by the code, such as UE, Notepad++, Atom, Eclipse... ...
Thank you.

**Comment by sean-mcmanus** [comment]
Can you move this request to VS Code? Our extension isn't able to add this feature because they don't have extension points for that UI element. https://github.com/Microsoft/vscode/issues

**Comment by rapus95** [comment]
There now is some sort of outline feature implemented in VS Code. Can you extend that? (Since it's some sort of buggy and really not what people expect for highly structured languages like C++)

**Comment by bobbrow** [comment]
we're going to track this with #2230

**Comment by xiagw** [comment]
> Many modern editors have an import feature: function list. It is very useful to view the outline of the c/c++ file.
> Although vscode can view the symbols list via Ctrl-Shift-O, but many programmers prefer function list, I think.
> 
> So, I expect vscode can implement function list via the extension.
> 
> Thanks.

Yes, good suggestion.
We also really want this feature.
Thanks.
