### ISSUE TITLE
show matching bracket line on the top when cursor placed beside a bracket

### ISSUE THREAD

**Issue by baiwfg2** [microsoft/vscode-cpptools#6430]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version: 1.46
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

When I place the cursor beside a right bracket `}`,  I often want to see which line matches with it, especially when the code snippet is long and the matching line is beyond the view. So can vscode do like the following in clion , showing the matching line on the top temporarily ?

![image](https://user-images.githubusercontent.com/5157680/97948556-e73c7e00-1dcb-11eb-9431-76fc76aeb27f.png)

**Comment by sean-mcmanus** [comment]
Yeah, that works in VS, but not in VS Code (it's implemented in a code layer that hasn't been ported to VS Code). See https://devblogs.microsoft.com/cppblog/c-productivity-improvements-in-visual-studio-2019-preview-2/#QuickInfoClosingBrace.

**Comment by Jianchaoliang** [comment]
unsubscribe


| |
菅朝梁
|
|
18205601716@163.com
|
签名由网易邮箱大师定制
On 11/3/2020 13:07，Sean McManus<notifications@github.com> wrote：

Yeah, that works in VS, but not in VS Code.

**Comment by bobbrow** [comment]
This seems like a feature that VS Code should be able to do generically instead of having the languages all implement it.  Is there a feature request for VS Code to do it?

**Comment by sean-mcmanus** [comment]
@bobbrow VS Code just has generic brace matching, but obtaining the block of code associated with the `{}` requires language level lexical processing. So I don't think this can implemented generically without being buggy.

**Comment by bobbrow** [comment]
That's fair, but I still think support should be available via a "Provider" API of some sort that we would code against.  I don't think we should do our own thing here.  VS Code aims for consistency across languages where ever possible.

**Comment by sean-mcmanus** [comment]
The provider API is the same textDocument/hover, the same as what VS uses. Were you thinking that VS Code should provide something additional?

**Comment by bobbrow** [comment]
Yes. I don't know what logic they use to implement "smart select" (another scope-related feature in the editor), but I figured there must be a way to influence how it works.  And if not, then we need them to add an API for it.  When they have the data model for that, they should be able to implement this feature as well.

**Comment by sean-mcmanus** [comment]
@bobbrow What are you referring to in regards to "smart select"? How is that related to this issue? I think we would just need to port the VS implementation into our hover implementation.

**Comment by bobbrow** [comment]
I didn't mean to distract you with the smart select thing.  All I was trying to get at is that as smart select (SHIFT+ALT+Right Arrow) expands its selections, one of the stopping points is matching curly braces.  So VS Code is already partitioning the source file into regions (or maybe it does it on the fly).  The fact that it does this means that they could also be doing the highlighting suggested by this issue.

Adding a provider API is just a way for us to plug into that.  And when that API is available, *then* we can take VS's implementation and bring it to VS Code.

**Comment by bobbrow** [comment]
In other words, the feature as requested belongs on VS Code's plate in my opinion.  The ability to supply better information to VS Code so that the feature works well would be on our plate, but it requires an API for us to provide that data.

**Comment by sean-mcmanus** [comment]
VS Code's smart selection and brace matching is only able to handle `{}` regions. Getting the correct code region for the code before the `{` on hover requires language specific parsing.

It sounds like you're asking for additional UI in addition to the hover UI that VS supports. Adding the hover support over } that VS supports would require no VS Code APIs. If you want additional UI that appears whenever the cursor auto-matches a brace without hovering then that would be a separate VS Code request we could make, but since we don't have the data available yet, it doesn't seem like the right time to ask VS Code for the additional UI until we're able to actually use it (which VS doesn't even have).

**Comment by sean-mcmanus** [comment]
I've filed a feature request on VS for the auto-quick info when the cursor is at } at https://developercommunity.visualstudio.com/idea/1247494/c-auto-show-quickinfo-closing-brace-info-on-brace.html .

**Comment by Trass3r** [comment]
https://github.com/microsoft/vscode/issues/134888
