### ISSUE TITLE
Semantic prompt failed

### ISSUE THREAD

**Issue by 544892012** [microsoft/vscode-cpptools#6433]
Type: Debugger

**Describe the bug**
- OS and Version: windows x64
- VS Code Version: 1.50.1
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

Semantic prompt suddenly does not work:

![image](https://user-images.githubusercontent.com/8295239/98009084-23092f00-1e30-11eb-84f1-0c07cbbba53b.png)

![image](https://user-images.githubusercontent.com/8295239/98009119-2a303d00-1e30-11eb-9e2b-4b8f618fd25e.png)

![image](https://user-images.githubusercontent.com/8295239/98009137-2dc3c400-1e30-11eb-8d11-98691090ed49.png)

![image](https://user-images.githubusercontent.com/8295239/98009150-30beb480-1e30-11eb-85a5-5c79d6f7f8e3.png)

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment]
We need more repro info. I'm not able to repro the bug with code
```
#include <string>
#include <map>
#include <vector>
using namespace std;

class UNLayoutModule {
public:
	static const std::string LAYOUT_MODULE_TYPES_CMS;
public:
	string un_module_id;
};

void VideoDetailService()
{
	UNLayoutModule layout;
	// lay // invoke completion here
}
```
Do you have a code sample that repros the bug, along with settings (like the OS, compiler, cppStandard, etc.)?
