### ISSUE TITLE
Run Button not available

### ISSUE THREAD

**Issue by JANMAY007** [microsoft/vscode-cpptools#6437]
Issue Type: <b>Feature Request</b>

In my c/c++ code file I am not able to find the run button and if I use ahortcut then it saya that .json file have some problem of MiDefaultPath is wrong but I have not made any changes then how does it gone wrong? 
How to make button visible back?

Extension version: 1.1.0-insiders4
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

**Comment by JANMAY007** [comment]
Its MiDebuggersPath

**Comment by Colengms** [comment]
@WardenGnaw

**Comment by WardenGnaw** [comment]
The run button will not be available if you have not configured a `launch.json` to start the debugger. 
![image](https://user-images.githubusercontent.com/3953714/107707759-3b7eb600-6c77-11eb-90a6-5f17ed185b37.png)
Once a `launch.json` has been created, you should see the `Run` tab show a Run option.
![image](https://user-images.githubusercontent.com/3953714/107707816-56512a80-6c77-11eb-80db-6770eb4adf0f.png)
