### ISSUE TITLE
Gives error when an empty array is declared

### ISSUE THREAD

**Issue by sahin52** [microsoft/vscode-cpptools#6439]
char line[80]={};
This line shows an error, which mustn't happen
if I write like this:
char line[80]={'a'};
it doesn't give error. 
I have downloaded gcc, but I couldn't use it for debug while writing code.
OS: windows 10
VS Code: latest version 2020-11-4
Other extensions: No related extension for this problem.

**Comment by Colengms** [comment]
Hi @sahin52 .  I'm unable to easily reproduce this issue, in either a .c or .cpp source file, and regardless of what `cStandard` or `cppStandard` setting I use.  Can you provide more information, such as your configuration (the contents of your `c_cpp_propertiers.json`), the output of the C/C++ output channel with `"C_Cpp.loggingLevel": "Debug"` enabled and leading up to the repro, as well as the output of the `Log Diagnostics` command after the repro?

**Comment by sahin52** [comment]
here is a link to the files: The problem is on simpleRaytracer.c https://drive.google.com/drive/folders/1r_0PevARwuA3ldoaq9oq-PuSOvxMoNfJ?usp=sharing
I probably have a problem on my cpp downloads. Thanks in advance. The error is on 148 and 166th rows.

**Comment by Colengms** [comment]
Hi @sahin52 .  I'm not sure why I wasn't able to repro before in a C file.  Although that syntax is valid in a C++ file, it's not valid in C.  When I try to compile using MSVC, I get the following errors:

```
C:\TEMP\temp c program\simpleRaytracer.c(148,20): error C2059: syntax error: '}'
C:\TEMP\temp c program\simpleRaytracer.c(166,20): error C2059: syntax error: '}'
```
I believe you could specify just a single 0 element, and C will fill the remaining elements with 0's. 

```
char line[80]={0};
```

This behavior of C is specified here in:
C11 standard (ISO/IEC 9899:2011):
6.7.9/12-38 Initialization (p: 140-144)

`The initializer ends early, so ... is initialized with zeros`

http://c0x.coding-guidelines.com/6.7.8.html

**Comment by sean-mcmanus** [comment]
The error is valid for the cl.exe compiler, so my guess is that you're incorrectly configured for msvc/cl.exe mode instead of gcc mode, in which case the code compiles and we don't give squiggles. Are you able to correctly configure for gcc?
