### ISSUE TITLE
Alphanumeric and underscore wide-char literal causes incorrect syntax highlighting

### ISSUE THREAD

**Issue by bad-ed** [microsoft/vscode-cpptools#644]
![wide-char-literal](https://cloud.githubusercontent.com/assets/24456989/25094540/489eafc6-23a0-11e7-9b74-cb28e7aac61c.png)

As shown in the screenshot above, `L'_'` is not highlighted correctly, instead the whole remainder of file is highlighted as string. Seems like using any alphanumeric character also causes this problem.

**Comment by sean-mcmanus** [comment]
This bug has already been fixed in atom/language-c, but VS Code Insiders hasn't been updated with the latest version yet. See https://github.com/Microsoft/vscode/issues/24909 . Our extension doesn't actually implement the C++ colorization.
