### ISSUE TITLE
Is it possible to set priority or exclude directories when searching header files?

### ISSUE THREAD

**Issue by liuzqt** [microsoft/vscode-cpptools#6442]
**Type: LanguageService**

I'm developing a library, and I installed it to the default location in my system. 

So there're two copy of header files, 

- one under system default locaiton `/usr/include/`
- the other under my project dir

when I'm editing source files under my project dir, I hope it use the header files under my project instead of the header files I've installed to my system, but it seems that the IntelliSense use the wrong one

Is there any approach I can deal with this situation? (I suppose this should be a common  one for most lib developer), either set high priority to the `include` dir under my project, either exclude the system installed header path

what I have in my `c_cpp_properties.json`

```
          "includePath": [
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}/**"
                ],
                "limitSymbolsToIncludedHeaders": true
            }

```
I think this should be enough to tell the LSP searching the `include` dir under my project dir, but it doesn't work in my situation

**Comment by bobbrow** [comment]
If you add the project dir location to the includePath, we will prioritize it over the recursive path:

```jsonc
  "includePath": [
    "${workspaceFolder}/include",  // This path will be preferred
    "${workspaceFolder/**"
  ]
```

You can also remove what you have for "browse".  The values you have would be auto-populated based on `includePath` and the default setting for `limitSymbolsToIncludedHeaders`.

**Comment by liuzqt** [comment]
@bobbrow that solve my problem, thanks!
