### ISSUE TITLE
The term 'nameofmyfile' is not recogonized as name of cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by vratzrover3** [microsoft/vscode-cpptools#6445]
![WhatsApp Image 2020-11-05 at 4 29 19 PM](https://user-images.githubusercontent.com/73995581/98235675-26afc980-1f88-11eb-9ff8-ccc9cde35be6.jpeg)
I have tried running VS Code as Administrator but hasn't worked for me. I have downloaded the latest versions of MinGW and VS Code. I have also pasted the bin folder of MinGW in system variables, but still isn't working,

**Comment by sean-mcmanus** [comment]
What is "./determine"? Does it exist? Does it run in a cmd shell?

**Comment by vratzrover3** [comment]
Determine is the name of my CPP File.
./determine is code to run the program

**Comment by vratzrover3** [comment]
Determine is the name of my CPP File.
./determine is code to run the program

**Comment by vratzrover3** [comment]
I solved it by first compiling my code in "Command Prompt." After compiling I compiled it again in VS Code terminal by using "g++ nameoffile.cpp -o run", and then changing the settings of "default code run" in terminal.
