### ISSUE TITLE
show more variables

### ISSUE THREAD

**Issue by NumberX** [microsoft/vscode-cpptools#645]
Hello
I would like to show the globale and static variable in debug mode at view for lldb on darwin .
I need your help for that:
1-First a need the source code for this plugin.
2-some help from you.
Best regards.

**Comment by pieandcakes** [comment]
@NumberX you should be able to view it through the watch window. We query lldb using MI for variables. If you enable `"logging": { "engineLogging": true }` in your `launch.json` you can see what we pass to `lldb-mi` and what it returns. 

One of our layers, MIEngine, is available at https://github.com/Microsoft/MIEngine.
