### ISSUE TITLE
High and constant CPU usage 

### ISSUE THREAD

**Issue by julorenz117** [microsoft/vscode-cpptools#6459]
![Constant and High CPU usage](https://user-images.githubusercontent.com/60625130/98414759-d3de1c80-2030-11eb-8c75-958ce2300723.png)

**Comment by sean-mcmanus** [comment]
This is most likely caused by tag parsing.

See https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues#windows on ways to get more diagnostics info.

You may also be able to get more info via setting C_Cpp.loggingLevel to "Debug".

**Comment by skyleaworlder** [comment]
I also encounter this tough problem...

And this problem occured 3 days ago the first time on my `VS Code / "C/C++"` perhaps.

From my Debug Log, it seems that `cpptools` are stuck in the next step of `cpptools/cpptools_finishUpdateSquiggles`.

**Comment by skyleaworlder** [comment]
update IntelliSense time(s): 0.254
     D:\EXERICISE\CPPEXERCISE\METOCARLO\BMP.HPP
cpptools/getDocumentSymbols
cpptools/getDocumentSymbols
Database safe to open

**Comment by sean-mcmanus** [comment]
@skyleaworlder We need more repro info. Your debug logging doesn't show anything abnormal. Is cpptools stuck? If so, could you attach a debugger to get a call stack (see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv ).
