### ISSUE TITLE
File destination info when jumping to a multi-defined symbol

### ISSUE THREAD

**Issue by savioret** [microsoft/vscode-cpptools#646]
I already opened an issue with this feature request, https://github.com/Microsoft/vscode/issues/24224
I open it here as @bpasero suggested, seems that the plugin is the one that should provide the necessary information for this purpose:

When navigating to a symbol in a project, if that symbol exists in multiple files VSCode allows you to choose wich one you one to jump to, but the information is incomplete as it does not describe the destination file (sorry I could not take a clean snapshot):

![xxx](https://cloud.githubusercontent.com/assets/5497332/25142217/7902a87c-2466-11e7-8b83-c1801e93be85.png)

It would be great if we could also know the destination file (I took SublimeText as example):
![capture](https://cloud.githubusercontent.com/assets/5497332/25142250/8f06fa24-2466-11e7-8f66-e1d01a3d125d.PNG)

Thank you.

**Comment by sean-mcmanus** [comment]
It's a vscode issue. cpptools returns the Location(uri/range) to vscode and they decide what to show in the symbols results UI.
