### ISSUE TITLE
Support C++20 non-type templates 

### ISSUE THREAD

**Issue by Link1J** [microsoft/vscode-cpptools#6462]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.51.0
- C/C++ Extension Version: 1.1.0

Support C++20 non-type templates 

**Steps to reproduce**

Code example, Compiles with MSVC 19.27 or newer and GCC 9.1 or newer and their respective C++20 flags.
```cpp
#include <cstddef>
#include <string_view>
#include <array>

template<typename C, std::size_t N> struct compile_time_string
{
    C content[N] = {};
    constexpr compile_time_string(const C (&input)[N + 1]) noexcept
    {
        for (std::size_t i{0}; i < N; ++i) { content[i] = input[i]; }
    }
    constexpr operator std::basic_string_view<C>() const noexcept
    {
        return std::basic_string_view<C>{content,N};
    }
};

template<typename C, std::size_t N> compile_time_string(const C (&)[N]) -> compile_time_string<C, N - 1>;

struct A00{};
struct A01{};
struct A02{};
struct A03{};

constexpr std::array info{"A00", "A01", "A02", "A03"}; 

constexpr uint8_t get_op(std::string_view name)
{
    uint8_t op = 0;
    for (auto& data : info)
    {
        if (data == name) break;
        op++;
    }
    return op;
}

template<int type>
constexpr auto cast_to()
{
         if constexpr (type ==  1) { return A01{}; }
    else if constexpr (type ==  2) { return A02{}; }
    else if constexpr (type ==  3) { return A03{}; }
    else                           { return A00{}; }
}

template<compile_time_string string>
constexpr auto get()
{
    constexpr auto data = get_op(string);
    return cast_to<data>();
}

int main()
{
    auto cool_string_stuff = get<"A01">();
    return 0;
}
```

**Expected behavior**

No error squiggles, and auto type deduction not reporting `<error-type>`.
Error squiggles appear on the two lines in the `get` function.

<details>
  <summary><strong>Logs</strong></summary>

```
```
</details>

**Screenshots**

![C++20 string problems](https://user-images.githubusercontent.com/22891267/98420843-0c442180-2056-11eb-8bb8-179dbc4fea63.PNG)
![C++20 string problems 2](https://user-images.githubusercontent.com/22891267/98420847-0ea67b80-2056-11eb-9823-b0c461e3b605.PNG)

**Additional context**

Sometimes the error squiggle do not show up, but the auto type deduction still fails.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug with our shared VS parser at https://developercommunity.visualstudio.com/content/problem/1247486/c-intellisense-gives-squiggles-and-with-constexpr.html .

I also hit a crash at https://developercommunity.visualstudio.com/content/problem/1247485/c-intellisense-process-crashes-after-deleting-stri.html after deleting the headers...not sure if matters though, since it's invalid code.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
