### ISSUE TITLE
Unable to start C/C++ language  server Missing cpptools.exe

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#6464]
Good Day,

I am experiencing a issue when starting VSCode the extention C/C++ IntelliSense does not start as the error refers to cpptools.exe binary is missing. I have re-installed, VSCode, PlatformIO, and C/C++ extension with no success, I have downloaded the offline installer and it also has a error as it does not find the VSCode installation I have on my machine.

Please advise for a possible resolution,

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/50953663/98425073-87c8c180-209c-11eb-9a67-1c3b21943a37.png)

**Comment by sean-mcmanus** [comment]
We got a report from 2 other users at https://github.com/microsoft/vscode-cpptools/issues/6453 , so we'll that issue to track this. One user was able to workaround it via installing the offline vsix at https://github.com/microsoft/vscode-cpptools/releases/download/1.1.0/cpptools-win32.vsix (you're saying that didn't work?) and another downgraded to 1.0.1 (you'll need to change the extensions.autoUpdate to false.

What do you mean by "it does not find the VS Code installation"?

We're not sure yet what could be causing this or how to get more info.

**Comment by ghost** [comment]
Hi Sean,

Thank you for the reply, I was running the installation of the extension directly from the downloads folder after some reading I downloaded the version in your link and installed it manually in VS code; viola all is good again.

Thank you for the assistance much appreciated;


Kind Regards
Jonathan Gainsford | TACCESS – Klerksdorp | 36 Williams Street Wilkoppies | Office +27 (0) 18 474 2002 | Cell +27 (0) 66 306 5532 | jonathang@taccess.co.za<mailto:jonathang@taccess.co.za> | www.taccess.co.za<http://www.taccess.co.za/> |

**Comment by sean-mcmanus** [comment]
It should be fixed now with 1.1.1: https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.1.
