### ISSUE TITLE
Where is the documentation for C (not C++)?

### ISSUE THREAD

**Issue by sdudnic** [microsoft/vscode-cpptools#6466]
I see there is great doc for C++, but why do you name the C/C++ but talk only about C++? How to compile the C programs? 

Also, is not really clear how to compile multiples files (.h, +.c ) together

**Comment by Colengms** [comment]
Hi @sdudnic .  The C/C++ Extension supports both C and C++ files.  I think most documentation specifically for this extension should be applicable to using it with either C or C++ files.

The C/C++ Extension does not actually build/compile code.  It provides 'language services', such as features that involve navigation, error detection, colorization, etc., to provide a rich editing experience.  What you are asking seems to be more generally about compiling and building C code.  If so, I'd suggest online tutorials or books.

**Comment by sean-mcmanus** [comment]
You could also request more C documentation at https://github.com/microsoft/vscode-docs/issues .
