### ISSUE TITLE
打开的文件实例无效。忽略文件 c:\Users\qcnhy\Documents\C\b.c 的 IntelliSense 消息。

### ISSUE THREAD

**Issue by qcnhy** [microsoft/vscode-cpptools#6467]
**Describe the bug**
- OS and Version:20180.1000
- VS Code Version:1.51.0
- C/C++ Extension Version:1.10
- Other extensions you installed (and if the issue persists after disabling them):none
- Does this issue involve using SSH remote to run the extension on a remote machine?:no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

when i run "formatDocument"

cpptools/formatDocument: file:///c%3A/Users/qcnhy/Documents/C/b.c (id: 6)
打开的文件实例无效。忽略文件 c:\Users\qcnhy\Documents\C\b.c 的 IntelliSense 消息。
![image](https://user-images.githubusercontent.com/42377311/98456431-63fa9e00-21b8-11eb-92bc-abe6f1ea8c08.png)

**Comment by Colengms** [comment]
Hi @qcnhy .  Can you provide all of the output in the C/C++ channel?  There is a known issue in which this error could occur if a file is open multiple times in VS Code, each with different path/filename casing.  Can you confirm if multiple instances of the file were open with different casing (perhaps already open in VS code when launched) ?
