### ISSUE TITLE
Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Error: Unable to read process.env.HOME

### ISSUE THREAD

**Issue by FerhatBingol** [microsoft/vscode-cpptools#6468]
Type: General

I use 
- 3.6.2 as a code-server 
- C/C++ 1.0.1 vscode-cpptools
- ubuntu 18.04 server (VPS)

When I install the extension first I get:

_"The C/C++ extension failed to install successfully. You will need to repair or reinstall the extension for C/C++ language features to function properly."_

When I click on REPAIR button, it gives: 

_"Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Error: Unable to read **process.env.HOME**"_

I also tried to delete the extension directory and re-install it.

**Comment by Colengms** [comment]
Hi @FerhatBingol .  Thanks for reporting this.  It looks like `process.env.HOME` can potentially fail, and we should be using `os.homedir()` instead.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
