### ISSUE TITLE
Please install [clang](http://clang.llvm.org/) or check configuration `clang.executable`

### ISSUE THREAD

**Issue by SeakyLuo** [microsoft/vscode-cpptools#647]
I got this error message after I updated the latest vscode.
Then I can see it all the time even I close it for a thousand times.
I think I have installed all the plugin I need.
How do I fix it or disable it?
I can't disable it by commenting that part of codes.

**Comment by sean-mcmanus** [comment]
That error is not from our extension. Can you file an issue with the clang-related extension that is causing the error?

**Comment by SeakyLuo** [comment]
How? I am a freshman I don't know how to do it, sorry.
![image](https://cloud.githubusercontent.com/assets/25042708/25300086/8d75794e-26bc-11e7-8595-15a9a7d4d85a.png)

**Comment by sean-mcmanus** [comment]
Assuming the message is from the Clang Format extension, you can try asking at https://github.com/xaverh/vscode-clang-format-provider/issues . I think you need to go to that LLVM website and download the clang-format executable and then set the clang.executable path. Our C/C++ extension automatically downloads clang-format 3.8, so you could use our tool to format instead, although there are slight differences between ours and the other extension.

**Comment by yuanhuihe** [comment]
Download LLVM from its website, install LLVM, check "Add LLVM to system path", restart vscode. It can fix this issue.

**Comment by ARHollisSr** [comment]
@yuanhuihe Thanks!

**Comment by nlqq** [comment]
@yuanhuihe hi，i think ur answer is right, but i just wonder how should i do this in the Windows env?

**Comment by sean-mcmanus** [comment]
@nlqq The process should be the same on Windows as other OSS's, e.g. http://releases.llvm.org/6.0.0/LLVM-6.0.0-win32.exe or http://releases.llvm.org/6.0.0/LLVM-6.0.0-win64.exe .

**Comment by nlqq** [comment]
@sean-mcmanus  nice！！！ thx！！！

**Comment by IIvexII** [comment]
thanks

**Comment by cur1ousss** [comment]
> Download LLVM from its website, install LLVM, check "Add LLVM to system path", restart vscode. It can fix this issue.

but isnt LLVM for macOS?
i am beginner so please correct me if i am wrong
also could you please explain how to solve the error for linux system example ubuntu

**Comment by sean-mcmanus** [comment]
@cybrpnkkrtos LLVM is cross-platform: http://releases.llvm.org/download.html , but not installed on Linux by default usually.

**Comment by saurabhkanswal** [comment]
> @nlqq The process should be the same on Windows as other OSS's, e.g. http://releases.llvm.org/6.0.0/LLVM-6.0.0-win32.exe or http://releases.llvm.org/6.0.0/LLVM-6.0.0-win64.exe .

link is not working!
