### ISSUE TITLE
`{$workspaceRoot}\.vscode\db*` files gets created

### ISSUE THREAD

**Issue by swarnendubiswas** [microsoft/vscode-cpptools#6474]
Type: General

I have a `.vscode` directory, I also have `c_cpp_properties.json` file configured. However, I get to see `{$workspaceRoot}\.vscode\db*` files getting created for every C/C++ project I am working with. 

This did not happen a few releases earlier, I am not sure what changed or what am I doing wrong. 

![Screenshot from 2020-11-09 15-38-05](https://user-images.githubusercontent.com/7343807/98528681-a7c9d200-22a2-11eb-8166-488cc4585255.png)

- OS and Version: Ubuntu 20.04
- VS Code Version: 1.51
- C/C++ Extension Version: 1.1.0
- Other extensions you installed (and if the issue persists after disabling them): Happens with other extensions disabled
- A clear and concise description of what the bug is.

**Expected behavior**
I would prefer the `db` files to go into `.vscode`.

**Comment by Colengms** [comment]
Hi @swarnendubiswas .  Is it possible you have configured the following setting?  `C_Cpp.default.browse.databaseFilename`
`{$workspaceRoot}` appears to be a typo.  It should be `${workspaceRoot}`.  I do not see this typo in our code.

**Comment by swarnendubiswas** [comment]
Thanks, it is a mistake in my settings. I had `"C_Cpp.default.browse.databaseFilename": "{$workspaceRoot}/.vscode/db"` in my `settings.json`. That should fix it.
