### ISSUE TITLE
“view the definition“ Highlight box selection is missing the last letter

### ISSUE THREAD

**Issue by JiGuangYuan** [microsoft/vscode-cpptools#648]
If you use the right-click to view the definition, the displayed method name box is missing the last letter
![image](https://cloud.githubusercontent.com/assets/22188316/25163068/0df3a376-24fa-11e7-904b-b0f0cace585b.png)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I am able to repro it too. I'm not sure why no one has noticed this before.

**Comment by sean-mcmanus** [comment]
Yeah, this wasn't fixed in 0.11.0 (maybe the next update).

**Comment by bobbrow** [comment]
This was fixed in version 0.11.1. Please reopen if you continue to have this issue.
