### ISSUE TITLE
The msvc-x64 intellisense is NOT compatible with the access path of the compiler.

### ISSUE THREAD

**Issue by frenchiveruti** [microsoft/vscode-cpptools#6484]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 1903
- VS Code Version: 1.51
- C/C++ Extension Version: 1.1.1
- Other extensions you installed (and if the issue persists after disabling them): - 
- A clear and concise description of what the bug is. 
I'm using msys64 and the path is similar to linux/unix, therefore the parser thinks I'm on linux, then it fails horribly.

![imagen](https://user-images.githubusercontent.com/1095997/98674374-79e29d00-2337-11eb-8940-0bb0c3f49b71.png)

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Download msys64.
2. Install gcc 
3. Try to use it as the compiler.
4. extension thinks it's Linux
5. Intellisense and compiling/debbuggin tries to use linux path system.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by frenchiveruti** [comment]
To add on to this, when you try for example to run de debugger through `F5`, it will try to 'debug' on a Linux type of path.  
(instead of say C:/path/to/file) will parse it as c/path/to/file. Which of course fails.

**Comment by Colengms** [comment]
Hi @frenchiveruti .  Both the IntelliSenseMode and the compilerPath settings are used by the C/C++ Extension to determine how to interpret the source code, to provide language services such as code navigation, colorization, etc..  The "msvc" IntelliSenseMode's are specifically for the MSVC compiler ("cl.exe").  So, the error is to inform you that the IntelliSenseMode and the compilerPath you have specified are incompatible.  If your code is expected to compile using gcc, and you want gcc-specific language features to be allowed (not flagged as errors in the editor), you should use one of the "gcc" IntelliSenseMode's.

The C/C++ Extension does not provide a build system.  How are you building your project?  The linux-like paths seem to be the result of your build system or compiler.  Perhaps if you are using CMake or Make from MSYS64, they may output linux-like paths, as MSYS64 is a linux shell and would accept those paths.  Or, perhaps the build of gcc you have installed is not intended to be used outside of MSYS64?  The mingw64-w64 packages for MSYS64 should work properly when invoked outside of MSYS64.

**Comment by frenchiveruti** [comment]
Hello Colengms .  
I don't understand what do you mean.  
I'm building my "project" which is composed of a single c file, using the gcc provided by msys64.  
Anyways I really can't provide more info, I installed minwg-x64 following the docs and it works, but I thought it was a bug worth reporting.
thanks-

**Comment by bobbrow** [comment]
@Colengms is saying to change `msvc-x64` to `gcc-x64` and the error will go away.

**Comment by frenchiveruti** [comment]
That made another error where vscode would use a route like unix, d/path/to/file.

**Comment by sean-mcmanus** [comment]
Is this still an issue? Could you elaborate on what the error is? Is this just an IntelliSense error?

**Comment by frenchiveruti** [comment]
I have no idea Sean, that's the problem, to be able to report an issue on VSCode you need a degree in Comp. Sci.  
That's why I closed it.

**Comment by sean-mcmanus** [comment]
You can see the source of the error:
![image](https://user-images.githubusercontent.com/19859882/99333324-4fac4600-2835-11eb-8670-29d582336176.png)
so if it says "gcc" that's an error from the compiler (or if the error appears in the Terminal window) or if it says "C/C++" then that's an IntelliSense error.

If you can give more info on the error you're hitting we might be able to figure out what's going on.

We have some docs at https://code.visualstudio.com/docs/cpp/config-mingw, although it hasn't been updated for the latest MSYS64.

**Comment by frenchiveruti** [comment]
Hello Sean. I appreciate the effort but I had to reset my computer for an unrelated problem and now I have vsc and cpptools working fine, I know how to "redo" the so called 'bug' but it really isn't worth the time, as the docs are already extensive and accurate enough to not fall into any of these issues.  
thanks
