### ISSUE TITLE
extension is installed as ARM binary instead of x86

### ISSUE THREAD

**Issue by simonebaracchi** [microsoft/vscode-cpptools#6486]
Type: General

When installing the c++ extension from VSCode menus, the actual binary seems to be ARM-based. 
My machine is x86 so any attempt to use the C++ extension fails.

**Describe the bug**
- OS and Version: CentOS 8.2 x86_64
- VS Code Version: 3.6.2
- C/C++ Extension Version: 1.1.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*
1. Go to Extensions, install C++ extension, reload if required
2. Most likely the extension will try to get started in the background, or try to open some cpp files
3. The "output" window will show an error like this:
`/root/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.0/bin/cpptools: /root/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.0/bin/cpptools: cannot execute binary file`

**Expected behavior**
My analysis is that cpptools is installed for a wrong architecture. The x86_64 version should be installed instead.

**Screenshots**
The cpptools binary cannot be run:
`[root@sigma40 ~]# /root/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.0/bin/cpptools`
`bash: /root/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.0/bin/cpptools: cannot execute binary file: Exec format error`
`[root@sigma40 ~]#  file /root/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.0/bin/cpptools`
`/root/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.0/bin/cpptools: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=1f1d022564fe3736517f4b233ca3286638074a16, not stripped`
`[root@sigma40 ~]# uname -a`
`Linux sigma40 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Thu Oct 22 00:20:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
If asked about enabling the VSCode insiders channel, this might trigger an upgrade to version 1.1.1 which apparently does not have the issue. However, downgrading to 1.0.1 or 1.0.0 does not seem to help; as such I suspect this might be an issue in VSCode rather than cpptools.

**Comment by sean-mcmanus** [comment]
1.1.1 is our latest version and has this fixed this, right?

**Comment by simonebaracchi** [comment]
Yes but not really. In the past when I was using vscode 3.5.0 which came with cpptools 1.0.1 I used to manually downgrade to 1.0.0 (using the vsix package) and this fixed it. Today I upgraded to vscode 3.6.2 and downgrading to 1.0.0 (using the ui) didn't help. My "feeling" is that vscode always downloads the arm version, unless it's using the insiders channel. But I have no idea how to prove this.

**Comment by sean-mcmanus** [comment]
Why are you downgrading to 1.0.0? You need to get 1.1.1 to get the bug fix for the Linux arm issue.

1.1.1 is not an insider version. You can set extensions.autoUpdate to false to stop updating, otherwise, our C_Cpp.updateChannel set to "Insiders" may auto-update to the latest version.

**Comment by zeroxia** [comment]
cpptools-1.1.3 still installs the arm version on x86_64 architecture:

```
coder@afd98ee2c1ba: ~/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.3/bin
$ ./cpptools
/lib/ld-linux-aarch64.so.1: No such file or directory
coder@afd98ee2c1ba: ~/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.3/bin
$ file cpptools
cpptools: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=1f1d022564fe3736517f4b233ca3286638074a16, not stripped
coder@afd98ee2c1ba: ~/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.3/bin
$ uname -a
Linux afd98ee2c1ba 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux
coder@afd98ee2c1ba: ~/.local/share/code-server/extensions/ms-vscode.cpptools-1.1.3/bin
$ 
```

**Comment by sean-mcmanus** [comment]
@zeroxia We don't know what could be causing that. Can you do "git clone https://github.com/microsoft/vscode-cpptools.git" then open the vscode-cpptools/Extension folder, set a breakpoint at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/platform.ts#L31 , and run "Debug: Start Debugging" to see what the result of os.arch() is?
