### ISSUE TITLE
showing red line (intellisense issue) in abs() function in c++ , i already included cstddlib header file still red line not going away

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#6488]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @shankFab .  I don't think we have enough information to repro your issue.  I'm not easily able to repro an issue with the following code:

```
#include <stdio.h>
#include <stdlib.h>

#include <cstdlib>

int main()
{
    // C abs
    long l1 = -1;
    long l2 = abs(l1);
    printf("%d\n", (int)l2);

    // C++ abs
    l1 = -1;
    l2 = std::abs(l1);
    printf("%d\n", (int)l2);
}
```

Can you provide the following? 
* A snippet of code that reproduces the issue
* Your configuration (the content of your `c_cpp_properties.json` file)
* The output of the C/C++ output channel, with `"C_Cpp.loggingLevel": "Debug"` set, leading up to the issue.
* The output of the `C/C++: Log Diagnostics` command, after repro'ing the issue (while the repro file is still open).
* Any output logged to the `C/C++ Configuration Warnings` channel.

**Comment by Colengms** [comment]
The user's account has been deleted.  Closing this issue.  shankFab, if you are still seeing a problem, please open a new GitHub issue.
