### ISSUE TITLE
Update notification comes up when opening a workspace with no C/++ files

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-cpptools#6489]
Type: General

**Describe the bug**

- OS and Version: Windows_NT x64 10.0.19041
- VS Code Version: 1.52.0-insider (user setup)
- C/C++ Extension Version: 1.1.1
- A clear and concise description of what the bug is: I opened a folder containing only some .js files -- no .cpp, .h, .c, Makefiles, or anything like that. When I did so, the C++ update banner came up.

**To Reproduce**
1. Open (apparently) any folder or workspace
2. The update prompt has the possibility to come up

**Expected behavior**
Users get very annoyed and fatigued with notifications, most of which come from various extensions they have installed.

In this case, I installed the extension a while ago to work on some C++. But I just opened a new folder that's totally unrelated to any C/++ code. I don't care _at all_ that the extension is updating stuff at this time; I had actually forgotten I had it installed.

If it fails, I might be interested, but even then I only really care the next time I go to work on C/++ code -- which could be in a day, a week, or never again.

**Screenshots**
![](https://memes.peet.io/img/20-11-509f345d-0469-46d7-9e03-47ba02b3f2f9.png)

**Comment by sean-mcmanus** [comment]
We intentionally want to always download these files even if the current workspace is not C++; however, we could fix it so that the notification is hidden if the activation requirements for the C/C++ extension have not been hit.

**Comment by bobbrow** [comment]
This will no longer be an issue when #8152 is complete. We will no longer need to have a separate download process.
