### ISSUE TITLE
Whether it can support Using Inline Assembly in C/C++(x86/x64)

### ISSUE THREAD

**Issue by stonedreamforest** [microsoft/vscode-cpptools#649]

**Comment by sean-mcmanus** [comment]
What do you mean by "support"? What feature? Can you file a specific bug where our support is not as desired?

**Comment by stonedreamforest** [comment]
@sean-mcmanus
sorry my english is not fluent
can insert assembly code in c/c++ code ，like this：
x86:
```
__asm{
        push 0
        push 0
        push 0
        push 0
        call MessageBox
	}
```

x64:
```
__asm{
        mov rcx,0
        mov rdx,0
        mov r8,0
        mov r9,0
        call MessageBox
	}
```
[https://msdn.microsoft.com/en-us/library/45yd4tzz(v=vs.120).aspx](https://msdn.microsoft.com/en-us/library/45yd4tzz(v=vs.120).aspx)

**Comment by sean-mcmanus** [comment]
I tried it and the C/C++ functionality doesn't break. We don't currently provide any special features for the assembly code though. Let us know if you think you find a bug or have a particular feature you would want added.

**Comment by stonedreamforest** [comment]
i would want added. but my code style unprofessional,  thanks for your Answer :+1:
