### ISSUE TITLE
Unable to install C/C++ extension

### ISSUE THREAD

**Issue by JustenK** [microsoft/vscode-cpptools#6496]
Issue Type: <b>Bug</b>

Current version of Visual Studio Code 

"The C/C++ extension failed to install successfully. You will need to reinstall the extension for C/C++ language features to function properly."

Followed instructions several times, uninstalled the program and extension several times. Have rebooted system several times and the extension will still not install.

Extension version: 1.1.1
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.25GB free)|
|Process Argv|--crash-reporter-id 6a7d167c-2d74-4fe4-abe5-13fdcd9ce16a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
Does the offline vsix at https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.1 work?

The error means some files from the installation are missing. One potential fix is to delete the install.lock file in the root of the extension folder to re-download the binaries.

**Comment by JustenK** [comment]
When I try to run cpptools I immediately get an error saying "The install of 'C/C++' was not successful for all the selected products. For more information, click on the install log link at the bottom of the dialog." I will try and delete the install.lock file in the root of the folder

Here is the contents of the install log 

11/10/2020 7:17:52 PM - Microsoft VSIX Installer
11/10/2020 7:17:52 PM - -------------------------------------------
11/10/2020 7:17:52 PM - vsixinstaller.exe version:
11/10/2020 7:17:52 PM - 16.8.3036
11/10/2020 7:17:52 PM - -------------------------------------------
11/10/2020 7:17:52 PM - Command line parameters:
11/10/2020 7:17:52 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Kessman\Desktop\cpptools-win32.vsix
11/10/2020 7:17:52 PM - -------------------------------------------
11/10/2020 7:17:52 PM - Microsoft VSIX Installer
11/10/2020 7:17:52 PM - -------------------------------------------
11/10/2020 7:17:53 PM - Initializing Install...
11/10/2020 7:17:53 PM - Extension Details...
11/10/2020 7:17:53 PM - 	Identifier         : cpptools
11/10/2020 7:17:53 PM - 	Name               : C/C++
11/10/2020 7:17:53 PM - 	Author             : ms-vscode
11/10/2020 7:17:53 PM - 	Version            : 1.1.1
11/10/2020 7:17:53 PM - 	Description        : C/C++ IntelliSense, debugging, and code browsing.
11/10/2020 7:17:53 PM - 	Locale             : en-US
11/10/2020 7:17:53 PM - 	MoreInfoURL        : 
11/10/2020 7:17:53 PM - 	InstalledByMSI     : False
11/10/2020 7:17:53 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
11/10/2020 7:17:53 PM - 
11/10/2020 7:17:53 PM - 	SignatureState     : Unsigned
11/10/2020 7:17:53 PM - 	Supported Products : 
11/10/2020 7:17:53 PM - 		Microsoft.VisualStudio.Code
11/10/2020 7:17:53 PM - 			Version : 
11/10/2020 7:17:53 PM - 
11/10/2020 7:17:53 PM - 	References         : 
11/10/2020 7:17:53 PM - Signature Details...
11/10/2020 7:17:53 PM - 	Extension is not signed.
11/10/2020 7:17:53 PM - 
11/10/2020 7:17:53 PM - Searching for applicable products...
11/10/2020 7:17:53 PM - Found installed product - Global Location
11/10/2020 7:17:53 PM - Found installed product - Visual Studio Community 2019
11/10/2020 7:17:53 PM - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)


**EDIT**: after deleting the install.lock from the root folder of vscode it appears to have fixed my issue. Thank you for the assistance!

**Comment by sean-mcmanus** [comment]
FYI, the offline vsix failed to installed because you double-clicked it which invoked the VS installer (the "Install from VSIX" command from inside VS Code is required to load a VS Code .vsix). But if deleting the install.lock worked, then the offline vsix isn't need.
