### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by DaMammoth** [microsoft/vscode-cpptools#6502]
OS: Windows 10, build 19042.610.
 VS Code version: October 2020 (version 1.51)
Extension version: v1.1.1
Other extensions: N/A
Issue: There isn't even an option for a C debugger/compiler. There are only ones for C++. When I press either, it just brings me to settings.JSON, and does nothing else.
Steps:
1. Press "F5" or click debug/run.
2. Click on one of the C++ compilers. There is no C compiler.
3. It opens the Settings.JSON file, and does nothing.

What should happen:
First, I want an option to use a C compiler, because if you are going to make a compiler, put the languages in the title, in the compiler. It also doesn't work with C++, which is an even bigger problem, because there are options to compile C++.

Also:
The Intellisense doesn't work. It says that #include <stdio.h> doesn't exist.

**Comment by DaMammoth** [comment]
Oh, never mind. I just realized that this STUPID extension, doesn't do CRAP. I have NO idea why this thing even exists. I can't use GNU, so I was going to use this instead, but you need GNU Y|TO RUN IT. What a piece of absolute crap.

**Comment by sean-mcmanus** [comment]
What C compiler do you have installed? It's working for me with the mingw C compiler:

![image](https://user-images.githubusercontent.com/19859882/99304059-bb2aef00-2806-11eb-9aca-02eda1cd6b70.png)

If it says stdio.h doesn't exist, that means the compilerPath wasn't set to a valid compiler.

We have docs at https://code.visualstudio.com/docs/cpp/config-mingw, although you'd have to change it for C instead of C++.

**Comment by DaMammoth** [comment]
I have no compiler. That's why I was using this.

**Comment by sean-mcmanus** [comment]
Our extension doesn't install a compiler -- we require you install one yourself.

Also, the settings.json appearing is because we require that you open a workspace folder. I've filed an issue to show a better error message https://github.com/microsoft/vscode-cpptools/issues/6545 .

**Comment by DaMammoth** [comment]
There is no compiler that I can get that works with Windows.

**Comment by sean-mcmanus** [comment]
What compilers have you tried and why are they not working for you? You could also use WSL on Windows to build with gcc/clang in a Linux environment.

Have you tried https://visualstudio.microsoft.com/vs/community/ or https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160 ?

**Comment by DaMammoth** [comment]
I have tried GNU, mingw, and the Visual Studio one. None of them worked.

**Comment by sean-mcmanus** [comment]
What do you mean by not working? What error do you get? Did they install? What happens when you run the Developer Command Prompt (i.e. `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat`) and type "cl"?

**Comment by DaMammoth** [comment]
Nevermind, I'm just using CLion as my IDE for C and C++.
