### ISSUE TITLE
VSCode with C++ does not index workspace folder

### ISSUE THREAD

**Issue by aradove** [microsoft/vscode-cpptools#6508]
Issue Type: <b>Bug</b>

I'm trying to get my project indexed in VSCode, but when pressing "Go to Definition", I only get a rolling bar at the top of the editor which then disapear. The definition is never found, and no message is given. 

![image](https://user-images.githubusercontent.com/9294134/99230285-721b7080-27ef-11eb-8910-f95de5390043.png)

 It is a git project with multiple subrepositories, where I have different definitions since I also have mocks/stubs for certain files. The folder is opened as a workspace, and with all compiled files the folder is 5 mb, with ~files. 

I've installed the C/C++ plugin, GCC compiler with addons, and setup the project ```c_cpp_properties.json``` in the following way
```
{
   "configurations": [
        {
            "name": "vscode_config",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17763.0",
            "compilerPath": "C:/MinGW/bin/gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "gcc-x86"
    },
 
    ],
    "version": 4
}
```
Is there something I'm missing? I've tried restarts, resetting the IntelliSense database, and much more I don't remember. 

Extension version: 1.1.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @aradove .  Could you describe a specific operation that does not work as you expect, and provide the output of the C/C++ output channel leading up to the repro, as well as the output of the `Log Diagnostics` command after the repro?  Given the include path specified in c_cpp_properties.json, the tag parser should have indexed all files in your workspace.  However, not all of the extensions features are based on tag parser data.

Also, it looks like you're using an older version of MinGW.  To get 10.2.0 of MinGW, you'll want to install MSYS2 and install the mingw64 package.  Instructions are here: https://www.msys2.org/  This version of MinGW seems to work well with our extension, while there are a number of issue with older version.

**Comment by aradove** [comment]
Hi @Colengms , thank you for taking the time with my issue. I updated the question with the information that it is when I try to use "Go to Definition", available with pressing shortcut F12 and right click. 

I can try using MSYS2 to install the latest minGW. To me it seems to be unlikely the fault but I will nontheless test it out to rule out possible errors.

**Comment by aradove** [comment]
Log diagnostics on my old configuration
```
-------- Diagnostics - 2020-11-16 11:42:41
Version: 1.1.1
Current Configuration:
{
    "name": "vscode_config",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.17763.0",
    "compilerPath": "C:/MinGW/bin/gcc.exe",
    "cStandard": "c11",
    "cppStandard": "c++11",
    "intelliSenseMode": "gcc-x86",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ ...\REPO\PROJECT_FOLDER\TEST\PLATFORM\HALIO.H ]:
    ...\REPO\PROJECT_FOLDER\TEST\PLATFORM\HALIO.H
[ ...\REPO\PROJECT_FOLDER\TEST\UNITTEST\IQC_CONFIG_UT.C ]:
    ...\REPO\PROJECT_FOLDER\TEST\UNITTEST\IQC_CONFIG_UT.C
Translation Unit Configurations:
[ ...\REPO\PROJECT_FOLDER\TEST\PLATFORM\HALIO.H ]:
    Process ID: 26272
    Memory Usage: 11 MB
    Compiler Path: C:/MinGW/bin/gcc.exe
    Includes:
        C:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE\C++
        C:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE\C++\MINGW32
        C:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE\C++\BACKWARD
        C:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE
        C:\MINGW\INCLUDE
        C:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE-FIXED
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++11
    IntelliSense Mode: gcc-x86
    Other Flags:
        --g++
        --gnu_version=90200
        --header_only_fallback
[...\REPO\PROJECT_FOLDER\TEST\UNITTEST\IQC_CONFIG_UT.C ]:
    Process ID: 9144
    Memory Usage: 12 MB
    Compiler Path: C:/MinGW/bin/gcc.exe
    Includes:
        C:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE
        C:\MINGW\INCLUDE
        C:\MINGW\LIB\GCC\MINGW32\9.2.0\INCLUDE-FIXED
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c11
    IntelliSense Mode: gcc-x86
    Other Flags:
        --gcc
        --gnu_version=90200
Total Memory Usage: 23 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 1357
Number of files discovered (not excluded): 1308
```

**Comment by aradove** [comment]
With Msys instead
```
-------- Diagnostics - 2020-11-16 11:50:07
Version: 1.1.1
Current Configuration:
{
    "name": "vscode_config_msys",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.17763.0",
    "compilerPath": "C:/msys64/usr/bin/gcc.exe",
    "cStandard": "c11",
    "cppStandard": "c++11",
    "intelliSenseMode": "gcc-x64"
}
Translation Unit Mappings:
[ ...\REPO\PROJECT_FOLDER\TEST\PLATFORM\HALIO.H ]:
...\REPO\PROJECT_FOLDER\TEST\PLATFORM\HALIO.H
[ ...\REPO\PROJECT_FOLDER\TEST\UNITTEST\IQC_CONFIG_UT.C ]:
...\REPO\PROJECT_FOLDER\TEST\UNITTEST\IQC_CONFIG_UT.C
Translation Unit Configurations:
[ ...\REPO\PROJECT_FOLDER\TEST\PLATFORM\HALIO.H ]:
    Process ID: 54796
    Memory Usage: 13 MB
    Compiler Path: c:/msys64/usr/bin/gcc.exe
    Includes:
        C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE
        C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE-FIXED
        C:\MSYS64\USR\INCLUDE\W32API
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=100200
[...\REPO\PROJECT_FOLDER\TEST\UNITTEST\IQC_CONFIG_UT.C ]:
    Process ID: 45744
    Memory Usage: 13 MB
    Compiler Path: c:/msys64/usr/bin/gcc.exe
    Includes:
        C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE
        C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE-FIXED
        C:\MSYS64\USR\INCLUDE\W32API
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c11
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=100200
Total Memory Usage: 26 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 2343
Number of files discovered (not excluded): 2294
```

**Comment by Colengms** [comment]
Hi @aradove .  When the C/C++ Extension parsed files, there is a little cylinder icon on the bottom of the window:

![image](https://user-images.githubusercontent.com/49173979/99315144-0baa4880-2817-11eb-86f5-2f28ec6e5b63.png)

If this icon is visible, does the issue repro if you wait for it to eventually complete and dismiss?

If something is going wrong with parsing or the Go To Definition operation, there should be something logged to the C/C++ output channel.  Could you provide the output of the C/C++ output channel leading up with the repro, with `"C_Cpp.loggingLevel": "Debug"` set?

**Comment by aradove** [comment]
Hi @Colengms , I  had the icon in the bottom corner when I opened the project. Also when I made a reset of the intellisense database. It dissapears after 20-30 seconds. 
![image](https://user-images.githubusercontent.com/9294134/99357023-7dcc6d00-28ab-11eb-8dd3-f661022b1c3d.png)


So when it is finished, I only get this when pressing "Going to definition". I.e. I can only find local file calls to the function, but not any definition that is stored outside a single file. 

![image](https://user-images.githubusercontent.com/9294134/99356349-4b6e4000-28aa-11eb-82ab-ba62700d2793.png)

I set ```"C_Cpp.loggingLevel": "Debug" ``` but what do you want me to print here?

The Log diagnostics looks the same to me.

I also have the output in the problems section:
![image](https://user-images.githubusercontent.com/9294134/99357910-0992c900-28ad-11eb-8976-f806d2a140ba.png)
The files are not all stored in the same subfolder, and I include them with ```#include "halIo.h"```

Using eclipse, this is not a problem when the project is indexed. Is there something I'm missing here?

**Comment by sean-mcmanus** [comment]
Does the Outline view show results?

Does this repro for all cases or only certain definitions?

We're looking for "tag parser" messages in the C/C++ logging, such as

```
  tag parsing file: <file>
Tag parsing encountered an error, but it may not matter. Let us know if symbols in the file can't be found: <file>
```

Also, what is the size of the browse database and is it being modified when edits are made? You can use `"C_Cpp.default.browse.databaseFilename": "${workspaceFolder}\\.vscode\\vc.db"` to more easily locate the database and verify that it is correct.

**Comment by aradove** [comment]
Here is the database file.

![image](https://user-images.githubusercontent.com/9294134/99632777-1561c500-2a3e-11eb-8470-c63a0b3d1770.png)

A small edit in a file made it grow from 900kb to 1.4kb. 

It is a problem for all definitions in any file. 

If I run log diagnostics there is no line with ```tag parsing file:...```. Or did you mean I find it elsewhere?

**Comment by Colengms** [comment]
Hi @aradove .  Do you have any `C_Cpp` settings set?  If so, could you post those, in case they might be related to the issue?

> there is no line with tag parsing file:...

With logging set to Debug, you should see this output as files are parsed.  However, a DB file of only 900K suggests that no files are being populated to the database other than the file you opened.  Normally, I would expect your `includePath` setting to cause all files under your workspace folder to be parsed.  I can repro a similar issue only if omit `includePath` from the configuration.

Those 'cannot open source file` errors seems to point to the root of the issue. If unable to find headers, they won't be parsed.  Can you confirm the directory you are opening, and the relative location of those files that were not found?

Is there anything special about your environment, such as the folder being on a network share?  (Does the "..." path in your Log Diagnostics actually point to a local path that you redacted?)

**Comment by aradove** [comment]
Hi @Colengms. Thanks for your support.

I didn't understand there was an specific output panel that you could select in the outputs.
Regarding network drive the answer is yes, the software is stored on a network drive. And it does seem to be related to the fault. 

And as you guessed it seems like it cannot find any of the files. Here is the output of c/c++ channel:

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (7144 KB)  Done!
Downloading package 'ClangFormat (Windows)' (814 KB)  Done!
Downloading package 'Visual Studio Windows Debugger' (13813 KB)  Done!

Installing package 'C/C++ language components (Windows)'
Installing package 'ClangFormat (Windows)'
Installing package 'Visual Studio Windows Debugger'

Finished installing dependencies

cpptools/didChangeCppProperties
MSVC intelliSenseMode specified.  Configuring for compiler cl.exe.
Code browsing service initialized
MSVC intelliSenseMode specified.  Configuring for compiler cl.exe.
  Unable to retrieve file system information for \\NETWORKDRIVE\home\USER\repo\GITREPO\**. error = -1
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/BUILDTOOLS/VC/TOOLS/MSVC/14.16.27023/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/CPPWINRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/SHARED/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UCRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UM/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/WINRT/ will be indexed
Populate include completion cache.
cpptools/resetDatabase
cpptools/resetDatabaseReady
Database safe to open
Code browsing service initialized
Populate include completion cache.
Discovering files...
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/BUILDTOOLS/VC/TOOLS/MSVC/14.16.27023/INCLUDE
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/CPPWINRT/
cpptools/fileCreated: file://NETWORKDRIVE/home/USER/repo/GITREPO/.vscode/VC.DB-wal
cpptools/fileCreated: file://NETWORKDRIVE/home/USER/repo/GITREPO/.vscode/VC.DB-shm
cpptools/fileCreated: file://NETWORKDRIVE/home/USER/repo/GITREPO/.vscode/VC.DB-shm
cpptools/fileCreated: file://NETWORKDRIVE/home/USER/repo/GITREPO/.vscode/VC.DB-journal
cpptools/fileDeleted: file://NETWORKDRIVE/home/USER/repo/GITREPO/.vscode/VC.DB-journal
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/SHARED/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UCRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UM/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/WINRT/
cpptools/fileCreated: file://NETWORKDRIVE/home/USER/repo/GITREPO/.vscode/VC.DB-wal
  Discovering files: 4681 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Database safe to open

Attempting to get defaults from C compiler in "compilerPath" property: 'C:\msys64\usr\bin\gcc.exe'
Probing compiler for default C language standard using command line: "C:\msys64\usr\bin\gcc.exe" -x c -E -dM nul
Probing compiler for default C++ language standard using command line: "C:\msys64\usr\bin\gcc.exe" -x c++ -E -dM nul
Probing compiler's default target using command line: "C:\msys64\usr\bin\gcc.exe" -dumpmachine
Compiler returned default target value: x86_64-pc-msys

Compiler probe command line: "C:\msys64\usr\bin\gcc.exe" -std=c11 -Wp,-v -E -dD -x c -m64  nul
Compiler probe command line: "c:\msys64\usr\bin\gcc.exe" -std=c11 -Wp,-v -E -dD -x c -m64  /dev/null
Compiler include path not found: c:\msys64\usr/usr/include
Compiler include path not found: c:\msys64\usrEnd of search list.
Attempting to get defaults from C++ compiler in "compilerPath" property: 'C:\msys64\usr\bin\gcc.exe'
Compiler probe command line: "C:\msys64\usr\bin\gcc.exe" -std=c++11 -Wp,-v -E -dD -x c++ -m64  nul
Compiler probe command line: "c:\msys64\usr\bin\gcc.exe" -std=c++11 -Wp,-v -E -dD -x c++ -m64  /dev/null
Compiler include path not found: c:\msys64\usr/usr/include
Compiler include path not found: c:\msys64\usrEnd of search list.
  Unable to retrieve file system information for \\NETWORKDRIVE\home\USER\repo\GITREPO\**. error = -1
  Folder: C:/MSYS64/USR/INCLUDE/W32API/ will be indexed
  Folder: C:/MSYS64/USR/LIB/GCC/X86_64-PC-MSYS/10.2.0/INCLUDE/ will be indexed
  Folder: C:/MSYS64/USR/LIB/GCC/X86_64-PC-MSYS/10.2.0/INCLUDE-FIXED/ will be indexed

```

I though this was the configuration, that will be project specific?

```
{
    "configurations": [
        {
            "name": "vscode_config_msys",
            "includePath": [
                "${workspaceFolder}\\**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.17763.0",
            "compilerPath": "C:\\msys64\\usr\\bin\\gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "gcc-x64"
        },
    ],
    "version": 4
}
```

Anyway, I updated the project path to be absolute like this:
```
...
"includePath": [
                "\\NETWORKDRIVE\\home\\USER\\repo\\GITREPO\\**"
            ],
...
```

In a matching header and c file I can find references and definitions now, but if I try to use it in another c file, such as in a unittest I get the following:

```
textDocument/definition: file://NETWORKPATH/home/USER/repo/GITREPO/test/unittest/evc_ut.c (id: 117)
cpptools/findAllReferences: file://NETWORKPATH/home/USER/repo/GITREPO/test/unittest/evc_ut.c
Unable to resolve include path: /NETWORKPATH/home/USER/repo/GITREPO
Unable to resolve include path: /NETWORKPATH/home/USER/repo/GITREPO
sending compilation args for \NETWORKPATH\home\USER\REPO\GITREPO\SW\EVC\SRC\EVC.C
  include: C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE
  include: C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE-FIXED
  include: C:\MSYS64\USR\INCLUDE\W32API
  define: __STDC__=1
...
stdver: c11
  intelliSenseMode: gcc-x64
sending compilation args for \\NETWORKPATH\home\USER\REPO\GITREPO\SW\PARSER\SRC\PARSER.C
  include: C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE
  include: C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE-FIXED
  include: C:\MSYS64\USR\INCLUDE\W32API
  define: __STDC__=1
...
 intelliSenseMode: gcc-x64
Shutting down IntelliSense server: \\NETWORKPATH\home\USER\REPO\GITREPO\SW\EVC\SRC\EVC.C
Closing the communication channel.
Shutting down IntelliSense server: \\NETWORKPATH\home\USER\REPO\GITREPO\SW\PARSER\SRC\PARSER.C
Closing the communication channel.
Unable to resolve include path: /NETWORKPATH/home/USER/repo/GITREPO
```

The output here: ```Unable to resolve include path: /NETWORKPATH/home/USER/repo/GITREPO``` seems to be a faulty path, since it is missing a extra slash such as this one: ```\\NETWORKPATH\home\USER\REPO\GITREPO```? 

Also I do not know why the IntelliSense server shuts down here.


The last thing I did was copying the project to local disk on my computer. In that case, I also needed to set a absolute project path in the file ``` c_cpp_properties.json```. When that is done, it seems that references are working properly.

So in the end it seems to be a trouble with having it on a network drive. Is that a known issue or is there anything specific I need to address here to make it work?

edit: Just to be clear, I replaced some folder names in the paths to NETWORKPATH, USER, GITREPO.

**Comment by aradove** [comment]
I changed to only forward slashes in the configuration. 

In the output, I believe all files have been parsed as all files of interest get
```  tag parsing file: \NETWORKPATH\home\USER\REPO\GITREPO\... ```
Also, all source files for the compiler seems to be parsed as well.

If I press goto definition on the include statement for any of the files that have been parsed I get output such as this one.
```textDocument/definition: file://NETWORKPATH/home/USER/repo/REPO/sw/parser/src/parser.c```

but nothing happens.

**Comment by Colengms** [comment]
Hi @aradove .  Unfortunately, there are currently some issues with support of opening folders on network shares.  We are tracking that with this issue: https://github.com/microsoft/vscode-cpptools/issues/4008

If you'd like to upvote that issue, we generally focus on issues with the most up-votes.

**Comment by aradove** [comment]
@Colengms Thanks for all the support.

This maybe is a stupid question, but how do I vote? Do I just do thumps up on the first post?

**Comment by aradove** [comment]
I checked the issue and if I map the network drive to for example X:/, then it actually works. 

So I guess it's a workaround that works for me in this case.
