### ISSUE TITLE
"File not found" - Changed Directory

### ISSUE THREAD

**Issue by BadHermano** [microsoft/vscode-cpptools#6509]
Hi Guys, 

i have a problem with CPP tools of Visual studio code. 
I attached Visual Studio code to a process.
Sometimes he tries to access a function in a diffrent file. 
Then he doesn't find the file. THe path which is showing is also wrong. 
If i say him to jump out the program runs normally till it tries to open another function again in a diffrent file. 
Also here he is using a wrong path. 
These paths are not completely wrong just old.
In Visual studio i was able to open the browser and then just navigate to the file. 
But in visual studio code he just tries to create a new file in this specific folder. 

Does sb know how i can solve this ? 

Cheers
GIovanni

**Comment by WardenGnaw** [comment]
In your `launch.json` you can add `sourceFileMap` to help the debug adapter map files from the old path to your new path.

Example:
```
"sourceFileMap": {
   "/old/source/path": {
      "editorPath": "/new/source/path",
      "useForBreakpoints": true 
   }
}
```

Reference: https://github.com/microsoft/vscode-cpptools/blob/f6d75776884ede4a56cac917d3233407c069bb29/Extension/package.json#L1462-L1503

**Comment by BadHermano** [comment]
Hi warden, thank you very much for your answer and the solution approach but is there no more user friendly solution like in visual studio where immediately if a file was not found the file browser opens to navigate to the source file ? Because otherwise I have to always restart the debugging and edit the launch json file and manually add for each file the paths. Thanks again for your help

**Comment by WardenGnaw** [comment]
We do not have a way to provide this path to the debug adapter once we have sent the path to VS Code to open. 
We currently have a feature request for navigating to the correct source file here: https://github.com/microsoft/vscode-cpptools/issues/5361
