### ISSUE TITLE
Error: Updating C/C++ dependencies behind a corporate proxy

### ISSUE THREAD

**Issue by tempseptember** [microsoft/vscode-cpptools#651]
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:564:26)

Finished

The proxy is set properly and the extension is getting installed. But throws error, when it updates the dependencies, after the Reload of the VS Code,

**Comment by sean-mcmanus** [comment]
What version of VS Code and cpptools do you have? We haven't seen this error before. All the JavaScript that does this downloading is available in our extension's folder at out/src/packageManager.js so if anyone sees the issue let us know. @pieandcakes do you have any ideas?

**Comment by pieandcakes** [comment]
@tempseptember I'm assuming closing and reopening VSCode gives you the same error. 

Are you able to download the file from the link? It can be found in the `C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-<version>\package.json` file at the bottom under `runtimeDependencies`. For the version I'm running it shows as:

```
     "description": "C/C++ language components (Windows)",
      "url": "https://go.microsoft.com/fwlink/?linkid=845223",
``` 
As @sean-mcmanus mentioned, we have code in the `packageManager.js` file, specifically the `DownloadFile` method that will try and get the proxy settings from VSCode's settings and use them.

**Comment by jrtitus** [comment]
I also had this same problem until I found and updated the VSCode `http.proxy` setting.

File > Preferences > HTTP (section). 
Copy `http.proxy` to User Settings, set its value, save the file, restart VSCode and voila:

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (4664 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (810 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (12081 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Installing package 'ClangFormat (Windows)'
Installing package 'Visual Studio Windows Debugger'

Finished
```

Verified working with VSCode 1.10.2 and C/C++ 0.11.0.

**Comment by githubclose2me** [comment]
I meet the same question, please give the example,thanks! @jrtitus 

console output messages:

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
Error: getaddrinfo EAI_AGAIN go.microsoft.com:443
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Finished

**Comment by githubclose2me** [comment]
resolved
proxy set error

**Comment by tempseptember** [comment]
@pieandcakes 
Yes, opening and closing the editor gives the same error each time.

> {
	"description": "C/C++ language components (Windows)",
	"url": "https://go.microsoft.com/fwlink/?linkid=847741",
	"platforms": [
		"win32"
	],
	"binaries": []
}

Able to download the Bin_Windows.zip from the above location.
http.proxy is set in the User Settings.
Able to update to version 0.11.0 without any problem.
But, still updating fails with the following error:

> Updating C/C++ dependencies...
Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:564:26)
Finished

**Comment by cliv3ong** [comment]
@pieandcakes i am facing the same error as @tempseptember.
No proxy set here.  The error occured both behind the corporate proxy and using mobile connections.  
Extension installation works fine and I am able to download the Bin_Windows.zip

Version: VS Code 1.11.2 and C/C++ 0.11.0

> Updating C/C++ dependencies...
> 
> Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
> Error: connect ETIMEDOUT 104.78.105.39:443
>     at Object.exports._errnoException (util.js:1026:11)
>     at exports._exceptionWithHostPort (util.js:1049:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
> 
> Finished

**Comment by sean-mcmanus** [comment]
Maybe if you set `"http.proxyStrictSSL": false`?

**Comment by tempseptember** [comment]
Set `"http.proxyStrictSSL": true`
Same error:

> Updating C/C++ dependencies...
> 
> Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
> Error: read ECONNRESET
>     at exports._errnoException (util.js:1022:11)
>     at TLSWrap.onread (net.js:572:26)
> 
> Finished

Set `"http.proxyStrictSSL": false`
Same error:

> Updating C/C++ dependencies...
> 
> Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
> Error: read ECONNRESET
>     at exports._errnoException (util.js:1022:11)
>     at TLSWrap.onread (net.js:572:26)
> 
> Finished

**Comment by pieandcakes** [comment]
@tempseptember The workaround for you might be to manually download and extract the required files and place the lock file manually. The only other suggestion I have to get us more information is to try and grab a Fiddler trace of the request going out and seeing what is hanging it up.

The zip files contain folders relative to your `c:\users\<username>\.vscode\extensions\ms-vscode.cpptools-0.11.0` folder. After they are extracted, place an `install.lock` blank file in the folder and it will stop checking.

**Comment by shankarsiddharth** [comment]
Set `http.proxy` to the proxy address and set `"http.proxyStrictSSL": true` in settings.
```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (4923 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (905 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (11875 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Installing package 'ClangFormat (Windows)'
Installing package 'Visual Studio Windows Debugger'

Finished
```
Working with VS Code 1.14.1 and C/C++ 0.12.1.

**Comment by tempseptember** [comment]
Was setting the wrong proxy in the setting for `http.proxy`.
Set correct proxy address and set `http.proxyStrictSSL` to `true` and now it's working. 
Apologies for this false negative issue.

> Updating C/C++ dependencies...
> 
> Downloading package 'C/C++ language components (Windows)' (4923 KB) .................... Done!
> Downloading package 'ClangFormat (Windows)' (905 KB) .................... Done!
> Downloading package 'Visual Studio Windows Debugger' (11875 KB) .................... Done!
> 
> Installing package 'C/C++ language components (Windows)'
> Installing package 'ClangFormat (Windows)'
> Installing package 'Visual Studio Windows Debugger'
> 
> Finished

**Comment by pavel-zhigulin** [comment]
I have almost same problem on LInux (Mint). VSCode download packages, but freezes on Install step. The only way to solve it - run VSCode as root.

**Comment by pieandcakes** [comment]
@MooNDeaR So you set the correct proxy and it still doesn't download? by running VSCode as root, i'm wondering if you have permissions issues to the temp directory or to your user root. we write in the temp as its downloading and to the user root (~/.) when the extension is expanded.

**Comment by mthcrts** [comment]
Hi all!
I had exactly the same problem (on Debian).
My http_proxy environment variable contains "server_name:port".
Even adding this value in my user settings (http.proxy) the download did not start.

I just added "https://" in http.proxy (ie "http.proxy": "https://server_name:port"), restart and VSCode starts downloading at startup.
Hope this helps ;-)

**Comment by sinhyeok-seo** [comment]
Just added
```
"http.proxyStrictSSL": false
```
Working! (macOS Sierra, VSCode v1.18.1)

**Comment by yongli-abc** [comment]
FWIW, I set `"http.proxy"` and `"http.proxyStrictSSL": true`, but it doesn't work.
Only after I changed to `"http.proxyStrictSSL": false`, then it worked.

**Comment by MSoegtropIMC** [comment]
I had to set `"http.proxySupport": "on"`. The default is `override` - whatever that means. Setting any of the other settings mentioned above didn't work for me. The `http.proxy` setting is picked up correctly from environment variables if not set.
