### ISSUE TITLE
Switching between header and source file does not work unless the src file folder is opened in the sidebar

### ISSUE THREAD

**Issue by AravindGopala** [microsoft/vscode-cpptools#6510]
**Type: LanguageService**

**Describe the bug**
About:
When the src and header are in different folders, when we open the header file and tried to switch to the src file by F12 on one of the function declarations in the header file or use Alt + O to switch to the src file, this will not work unless the folder containing the src file is opened in the sidebar.

- OS and Version: Ubuntu 20.04
- VS Code Version: 1.52.0-insider
- C/C++ Extension Version: v1.1.1
- Other extensions you installed (and if the issue persists after disabling them): Yes
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Go to the header file in a workspace folder(the src file should be in a different folder)
2. Click on try to navigate to the src file by F12 on one of the function declarations or use Alt + O to switch to the src file, this will not work unless the folder containing the src file is opened in the sidebar

**Expected behavior**
In the previous releases I was able to switch between header/src file this even though the folder containing the src file is not opened.

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I'm not reproing this bug. Could you provide more info and/or screenshots? What exactly does "opened in the sidebar" mean? Could you more fully describe what the workspace contains? Is this related to multi root?

**Comment by AravindGopala** [comment]
Hi Sean, Side bar is the location where the directory tree for a folder is present in the vs code, I tried to reproduce the issue outside our project, but unsuccessful, I tried to debug the issue, seems like the issue is due to cmake tools failed to configure which is breaking the path. I am closing this issue, thank you.
-
