### ISSUE TITLE
How to add multiple include path to task.json?

### ISSUE THREAD

**Issue by Zeinab-Rahmani** [microsoft/vscode-cpptools#6516]
I am trying to debug this repository: [MP-SPDZ][1], in which many `.h`, `.hpp` and `.cpp` files are placed in various folders. Additionally, in each `.cpp` file, several header files are included.

To be clearer here is what the file tree looks like :

      >ProjectTP
          >Machines
              -mascot-party.cpp
              -SPDZ.cpp
              -SPDZ.hpp
              -Player-Online.cpp
              -Player-Online.hpp
              -more files ...
          >Processor
              -Machine.h
              -Machine.hpp
              -more files ...
          >More folders ...

Note that in some cases `.hpp` files are considered as `.h` files while for some other cases they are considered a `.cpp` files. The problem is when I try to compile the project, VS Code is not able to find the headers, while I added all the include path to `task.json`.

Here is my main `.cpp` file `(mascot-party.cpp)` that is placed in a folder called `Machines` in the root directory. 

    #include "Player-Online.hpp"
    #include "Math/gfp.hpp"
    #include "GC/TinierSecret.h"
    
    int main(int argc, const char** argv)
    {
        ez::ezOptionParser opt;
        return spdz_main<Share<gfp>, Share<gf2n>>(argc, argv, opt);
    }

This is `Player-Online.hpp` that is included in `(mascot-party.cpp)` (Just to show how nested the repository is)

    #include "Processor/Machine.h"
    #include "Processor/OnlineOptions.h"
    #include "Math/Setup.h"
    #include "Protocols/Share.h"
    #include "Tools/ezOptionParser.h"
    #include "Networking/Server.h"
    
    #include <iostream>
    #include <map>
    #include <string>
    #include <stdio.h>
    using namespace std;
    
    template<class T, class U>
    int spdz_main(int argc, const char** argv, ez::ezOptionParser& opt, bool live_prep_default = true)
   
    ...
        return 0;
    }

Here is my `task.json`:

    {
    	"version": "2.0.0",
    	"tasks": [
    		{
    			"type": "shell",
    			"label": "C/C++: g++ build active file",
    			"command": "/usr/bin/g++",
    			"args": [
    				"-g",
    				"${workspaceFolder}/Machines/mascot-party.cpp",
    				//"${workspaceFolder}/Machines/SPDZ.cpp",
    				"${workspaceFolder}/Tools/*.cpp",
    				"${workspaceFolder}/Math/*.cpp",
    				"${workspaceFolder}/OT/*.cpp",
    				"${workspaceFolder}/Networking/*.cpp",
    				"${workspaceFolder}/Processor/*.cpp",
    				"${workspaceFolder}/Protocols/*.cpp",
    
    				"${workspaceFolder}/Machines/*.hpp",
    				"${workspaceFolder}/Tools/*.hpp",
    				"${workspaceFolder}/Math/*.hpp",
    				"${workspaceFolder}/OT/*.hpp",
    				"${workspaceFolder}/Processor/*.hpp",
    				"${workspaceFolder}/Protocols/*.hpp",
    
    				"-Idir",
    				"${workspaceFolder}/Processor",
    				"${workspaceFolder}/Tools",
    				"${workspaceFolder}/Math",
    				"${workspaceFolder}/OT",
    				"${workspaceFolder}/Networking",
    			
    				
    				"-o",
    				"${fileDirname}/${fileBasenameNoExtension}",
    			],
    			"options": {
    				"cwd": "${workspaceFolder}"
    			},
    			"problemMatcher": [
    				"$gcc"
    			],
    			"group": {
    				"kind": "build",
    				"isDefault": true
    			},
    			"detail": "compiler: /usr/bin/g++"
    		}
    	]
    }

And my `c_cpp_properties.json`:

    {
        "configurations": [
            {
                "name": "Linux",
                "includePath": [
                    "${workspaceFolder}/**"
                ],
                "defines": [],
                "compilerPath": "/usr/bin/g++",
                "cStandard": "c11",
                "cppStandard": "c++17",
                "intelliSenseMode": "gcc-x64"
            }
        ],
        "version": 4
    }

This is the compiler error:
[![enter image description here][2]][2]

**Important note:** When I put the absolute path in my .cpp files (e.g. instead of `#include "Processor/Machine.h"` I put `#include "/home/user/MP-SPDZ_VSCode/Processor/Machine.h"`) it finds the headers. However, the repository is huge, and it's not possible to fix it this way.

I tried many different configurations for so long, but no result. Any help is appreciated. Thank you.

  [1]: https://github.com/data61/MP-SPDZ
  [2]: https://i.stack.imgur.com/cm9yo.png

**Comment by sean-mcmanus** [comment]
Add ${workspaceFolder} to your include path. Does that fix the issue?

**Comment by Zeinab-Rahmani** [comment]
Thank you for your reply. I have already added `${workspaceFolder} `to the include path in `task.json `as follows:
```
"-Idir",
				"${workspaceFolder}/Processor",
				"${workspaceFolder}/Tools",
				"${workspaceFolder}/Math",
				"${workspaceFolder}/OT",
				"${workspaceFolder}/Networking",
```
 Where do you mean should I add it?

**Comment by sean-mcmanus** [comment]
You've added subfolders of ${workspaceFolder} -- it looks like those 5 subfolders should be replaced by a single reference to ${workspaceFolder}, because your `#include` statements reference the subfolders directly, e.g. `#include <Process/file.h>` (if you have other references to the files in the subfolders directly, such as `#include <file.h>` then you could keep the subfolders in the includes list as well).

**Comment by Zeinab-Rahmani** [comment]
Thank you for the detailed explanation. Yes, this solved the problem. I needed to add `${workspaceFolder}` to my include path as well as all the 5 subfolders. 

However, new errors have appeared as:   
`error: ‘PREP_DIR’ was not declared in this scope (In file ssl_sockets.h) `
Then later it says:
```
note: it was later defined here (in file setup.h)
   17 | #define PREP_DIR "Player-Data/"
```
**Note** This variable is defined in their` makefile` as follows:
` PREP_DIR = '-DPREP_DIR="Player-Data/"'`

Here is the screenshot:
![image](https://user-images.githubusercontent.com/53405693/99519118-58ae2c00-2989-11eb-8596-ac9fd0869c47.png)

1. Does the order of `.cpp` and `.hpp` and `.h` files that are passed in `task.json` is important? 
2. Or it's necessary to pass `PREP_DIR` as a command-line argument in` task.json`? If yes, how can I do that?
3. Since there are many variables defined in their makefile, is it possible to feed the makefile into ` task.json`?

Thank you once again for your time.

**Comment by sean-mcmanus** [comment]
The "build active" file template was intended for building single files, so there might be issues with building/linking multiple files.

You could add a -D arg to your tasks.json args for PREP_DIR.

We're working on a Makefile Tools extension that will be able to build and provide IntelliSense directly from the makefile, see https://github.com/microsoft/vscode-cpptools/issues/1587 .

You could also change your command to run "make", see https://github.com/microsoft/vscode-cpptools/issues/6546 .
