### ISSUE TITLE
No C/C++ extension on the Open VSX marketplace (for Arch Linux, VSCodium, etc.)

### ISSUE THREAD

**Issue by BackMountainDevil** [microsoft/vscode-cpptools#6518]
Type: General

**Describe the bug**
- OS and Version: Linux Deepin 2020
- VS Code Version: VSCodium 1.51.1
- C/C++ Extension Version: none
- Other extensions you installed (and if the issue persists after disabling them): python
- A clear and concise description of what the bug is.
There is no a c/c++ extension on VSCodium marketplace....

**Expected behavior**
Would you publish one to [open-vsx.org](https://open-vsx.org/) in addition to the VS Code Marketplace. The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by sean-mcmanus** [comment]
Our license doesn't support vscodium, only VS Code. We've had previous issues like this. Maybe we could keep this open as a request to change our license?

In particular, see https://github.com/microsoft/vscode-cpptools/tree/master/RuntimeLicenses

**Comment by BackMountainDevil** [comment]
Thanks for your answer. Actually, it is impolite to ask your company you change the license. Maybe just like VSCodium, rebuild a clean one. Is that ok?
 According to this [comment](https://github.com/Microsoft/vscode/issues/60) from a Visual Studio Code maintainer:
```text
   When we [Microsoft] build Visual Studio Code, we do exactly this. We clone the vscode repository, 
we lay down a customized product.json that has Microsoft specific functionality (telemetry, gallery, 
logo, etc.), and then produce a build that we release under our license.
    When you clone and build from the vscode repo, none of these endpoints are configured in the 
default product.json. Therefore, you generate a “clean” build, without the Microsoft 
customizations, which is by default licensed under the MIT license
```
Thanks all the time.

**Comment by sean-mcmanus** [comment]
A "clean" C/C++ extension with just the MIT license (i.e. TypeScript on GitHUb) would not include the cpptools/cpptools-svr binaries listed under https://github.com/microsoft/vscode-cpptools/tree/master/RuntimeLicenses , so it wouldn't be usable. Therefore, the license would need to be changed for those binaries.

**Comment by ghost** [comment]
You can use [Clangd ](https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd) extension in VScodium.

If you want to use Cmake Tools with it, follow this [workaround](https://github.com/microsoft/vscode-cmake-tools/issues/654#issuecomment-592983916)

**Comment by BackMountainDevil** [comment]
> You can use [Clangd ](https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd) extension in VScodium.

The [Clangd ](https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd) extension requires the clangd language server. Emm, is that work with gcc??

**Comment by BackMountainDevil** [comment]
Here are some solution I found:
1.  Just gcc command line like this
```bash
$ gcc filename
$ ./a.out
```
I use that for less operation for a few days
2. just make command like this
```bash
$ make
$ ./a.out
```
But you need to make a Makefile before like this one, this will use less word
```c
a.out:tmp.c
	gcc tmp.c  -Wall -Wextra -pedantic -std=c99
```
3. Use extendsion called Code Runner, install it . Make Sure  it check in Setting "Run in Termianl" 
see [this](https://github.com/formulahendry/vscode-code-runner/issues/589)

**Comment by ghost** [comment]
@BackMountainDevil compiling is so easy, what we need is auto-completion and syntax error highlighter.

Cland extension works fine for me on VScodium.

**Comment by chintan-mishra** [comment]
@rouisibra

Which C and C++ compiler are you using with Clangd plugin?

LLVM Clang or GCC?

How is the performance, and code completion experience?

**Comment by bobbrow** [comment]
> This feature request has received enough votes to be added to our backlog.

Unfortunately, this issue is not something that we are going to be able to address.  We've discussed the licensing terms with our product managers and legal team and it doesn't look like anything is going to change (at least for now).  I'm closing this issue to set the correct (though understandably disappointing) expectations for folks.

**Comment by G2G2G2G** [comment]
Microsoft obviously doesn't <3 open source
