### ISSUE TITLE
"All Exceptions" doesn't de-activate after unchecking it

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-cpptools#652]
_From @sean-mcmanus on April 20, 2017 20:11_

- VSCode Version: 1.12.0-Insiders
- OS Version: Windows

Steps to Reproduce:

1. Launch Extension: I used our cpptools extension.
2. Select the All Exceptions breakpoints option and have some exception trigger.
3. Uncheck the All Exceptions option.

Bug: It keep breaking on All Exceptions until I stop debugging.

_Copied from original issue: Microsoft/vscode#25095_

**Comment by sean-mcmanus** [comment]
It's not a bug with the cpptools extension. It's a bug with the javascript debugging in VS Code.

**Comment by mjbvz** [comment]
Please provide more context on this in the original issue then. Is vscode not sending your extension the correct events when the user changes these settings or not updating the debug filter?
