### ISSUE TITLE
extension not available on the marketplace

### ISSUE THREAD

**Issue by wlmr** [microsoft/vscode-cpptools#6520]
Type: General
Noticed a few days ago that none of the functionality provided by the extension was present. After having removed it, when trying to install it it wasn't present in the marketplace. Also tried `ext install ms-vscode.cpptools` with the result of "no matching command". When trying a manual install with the .vsix the output is: "The C/C++ extension failed to install successfully. You will need to repair or reinstall the extension for C/C++ language features to function properly." 

**Describe the bug**
- OS and Version: Arch Linux (Linux 5.9.8-arch1-1 x86_64)
- VS Code Version: 1.51.1
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
1. Uninstall the extension
2. Look for it in the marketplace

**Expected behavior**
Not being able to find vscode-cpptools

**Comment by sean-mcmanus** [comment]
We're tracking this with https://github.com/microsoft/vscode-cpptools/issues/6518 (there are other previous issues as well).

**Comment by wlmr** [comment]
Ok I thought #6518 was solely concerning vscodium but I see now you changed the title of it to include Arch Linux.

**Comment by wlmr** [comment]
Ok. I thought, #6518 was specific to VScodium but I see now that you changed the title to include Open VSX marketplace.
