### ISSUE TITLE
Large header files breaking intelisense / highlighting / autocompletion / linting

### ISSUE THREAD

**Issue by GideonUng** [microsoft/vscode-cpptools#6525]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.1
- Other extensions you installed (and if the issue persists after disabling them): -
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- Large header files breaking intelisense / highlighting / auto completion / linting

**Steps to reproduce**
include large -ish header file (windows.h, vulkan.h, vulkan.hpp, any header from the c++ standard library like vector)
navigate to one or two of the large header files.
after some moments everything starts to break
- code highlighting is completely off
- navigating to symbols will teleport you to seemingly random lines in unrelated header files
- auto completion is stuck for ever or will recommend garbage

**Expected behavior**
windows.h should not break the c++ editor from Microsoft? 
this has been persistent on about 5 different machines including linux for the last year or more

**Screenshots**
std::any not recognized as a symbol anymore
![image](https://user-images.githubusercontent.com/5054701/99282530-1c1cec00-2834-11eb-8722-0d55bcf83a6e.png)

**Comment by sean-mcmanus** [comment]
It sounds like the IntelliSense process is crashing. We need more repro info. We aren't able to repro this issue and we haven't gotten other reports of this, in regards to headers like Windows.h and the standard library headers. Can you provide the logging from running the C/C++: Log Diagnostics command? In particular, the cppStandard and compilerPath used and any important defines. Also, if you could attach a debugger to the cpptools-srv process before it crashes, that would identify what crash is occurring: see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv .

**Comment by GideonUng** [comment]
From short testing it seems like intelisense isnt crashing but every time i switch back and forth between tabs the intelisense refresh gets significantly slower. 

I several of the large header files open and ctrl-tabbed between them without opening any new ones.
the debug console tells me that after each window switch the intelisense reload got slower. 
from the console (on a ryzen 7 3700X):
`Update IntelliSense time (sec): 15.638`
`Update IntelliSense time (sec): 44.121`
`Update IntelliSense time (sec): 88.706`
`Update IntelliSense time (sec): 142.8`
This if related would be consistent with my previous experience using the plugin. i restart vs code every 5 minutes or so so that i can get auto completion back.

this is all i could see in the most verbose console output and with the debugger attached.

**Comment by GideonUng** [comment]
`c_cpp_properties.json`:
```
{
	"configurations": [
		{
			"name": "Win32",
			"defines": [
				"WINDOWS",
				"WIN32_LEAN_AND_MEAN",
				"UNICODE",
				"_UNICODE",
				"VULKAN_HPP_NO_EXCEPTIONS",
				"VULKAN_HPP_DISABLE_ENHANCED_MODE",
				//"VULKAN_HPP_NO_STRUCT_CONSTRUCTORS",
				"VK_USE_PLATFORM_WIN32_KHR"
			],
			"includePath": [
				"src/cpp/services",
				"src/cpp/dusk_and_dawn",
				"${VULKAN_SDK}/Include"
			],
			"intelliSenseMode": "msvc-x64",
			"cStandard": "c11",
			"cppStandard": "c++17"
		}
	],
	"version": 4
}
```

**Comment by sean-mcmanus** [comment]
Yeah, a crash would show "Failed to send request to server" in the logging (and break in the debugger), so it sounds like you're not hitting a crash.

Does the memory usage also increase as the update time increases?

Does the issue repro without the Vulkan SDK?

**Comment by GideonUng** [comment]
Yes memory usage of intelisense server goes up to 4-5gb 
Yes it appears without referencing the vulkan.hpp or vulkan.h headers (problem appears for both)
It also appears when just using C
And when simply including `windows.h`
Problem seems to be consitant on windows and linux. But not sure if they have the same origin

**Comment by sean-mcmanus** [comment]
Windows is limited to around 3 GB (32-bit process), at which point it is expected to crash from an out of memory, so I assume the 4-5 GB is on Linux?

You're seeing cpptools-srv using the memory/CPU and not cpptools, right?

Are you using windows.h on Linux too?

What version of the cl.exe headers and Windows headers are you using or what version of gcc/clang headers? e.g. the logging related to
```
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.28.29333\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UM
```

**Comment by sean-mcmanus** [comment]
Also, FYI, C_Cpp.intelliSenseMemoryLimit, which will restart cpptools-srv after a certain point when high memory usage is detected (defaults to 4 GB, i.e. 4096 MB) -- that's intended to fix cases where memory is accumulated over a period of time in which restarting cpptools-srv is expected to reduce the memory usage. You might want to try adjusting that setting (e.g. either 2 GB or 6 GB).
