### ISSUE TITLE
MSVC compile_commands.json - Intellisense not handling -external:I includes

### ISSUE THREAD

**Issue by paul-reilly** [microsoft/vscode-cpptools#6531]
Issue Type: <b>Bug</b>

If our compile_commands.json contains `-experimental:external` and include paths such as `-external:IC:/myincludepath`, Intellisense does not appear to handle these paths, resulting in a case of the dreaded squiggles with files `#include`d from these locations.

Extension version: 1.1.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

**Comment by sean-mcmanus** [comment]
I see it described at https://devblogs.microsoft.com/cppblog/broken-warnings-theory/ , but not in the current docs (https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=msvc-160).

**Comment by paul-reilly** [comment]
Yes, it does seem as though it has been stuck in `experimental` limbo for 3 years.

**Comment by sean-mcmanus** [comment]
cl /? Gives “/external:I <path>      - location of external headers”, so it looks like it got promoted out of experimental (i.e. /experimental:external doesn’t appear to be needed anymore). The missing docs might be a "bug", not sure yet.

**Comment by paul-reilly** [comment]
Oh yeah I see that it's in cl help. I just checked and it seems that it still can't be used without `/experimental:`:
```
cl : Command line warning D9007 : '/external:I' requires '/experimental:external or /external:W'; option ignored
```

**Comment by sean-mcmanus** [comment]
Yeah, you're right (I was mistaken).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders

**Comment by paul-reilly** [comment]
Thanks @sean-mcmanus!
