### ISSUE TITLE
Please take the vscode-cpptools GitHub survey

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6535]
As part of our ongoing efforts to improve the vscode-cpptools GitHub repo, we’ve created a survey to better understand your experience. We would appreciate your feedback. You have the option to reply anonymously or to supply contact details.

https://www.surveymonkey.com/r/92RLF7R?Source=Microsoft/vscode-cpptools

**Comment by melroy89** [comment]
You are aware of another survey? https://www.research.net/r/VBVV6C6

**Comment by bobbrow** [comment]
@danger89, yes we are aware. The survey you linked is about the C++ development experience.  The survey @sean-mcmanus linked is about your experience interacting with us on GitHub.  It is temporary and will be removed in a few weeks.
