### ISSUE TITLE
Update docs to refer to latest mingw-w64

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#6536]
Opening this issue to track updating https://code.visualstudio.com/docs/cpp/config-mingw to refer to the latest version of mingw-w64 (10.2.0), which is provided as a package in MSYS2.  https://www.msys2.org/

**Comment by Colengms** [comment]
It looks like there are multiple versions of MinGW (and multiple versions of Mingw_w64).

The [web site for MinGW](http://www.mingw.org/) appears dated, with just one update to the Welcome message in the last decade.

The [web site for Mingw_w64](http://mingw-w64.org/doku.php) indicates it's a fork of the original MinGW project, and there are recent updated.

The [web site for MSYS2](https://www.msys2.org/) says it "provides up-to-date native builds for GCC, mingw-w64, ...".
In its [MSYS2 introduction](https://www.msys2.org/wiki/MSYS2-introduction/) it indicates:

>It is an independent rewrite of MSys, based on modern Cygwin (POSIX compatibility layer) and MinGW-w64 with the aim of better interoperability with native Windows software.

There are also other incarnations of MinGW, such as: https://nuwen.net/mingw.html

The two primary versions of Mingw_w64 appear to be from http://mingw-w64.org/doku.php , and https://www.msys2.org/

GCC in the latest build from http://mingw-w64.org reports as 8.1.0, though it's unclear how/if that maps to an actual version of GCC:

```
C:\Program Files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin>gcc --version
gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

It indicates a copyright of 2018, which might suggest it's built from a dated version of GCC, but that is unclear.

Within MSYS2 there is a package for Mingw_w64.  That package reports to be 10.2.0, and appears to be in alignment with the GCC version:

```
C:\msys64\mingw64\bin>gcc --version
gcc (Rev5, Built by MSYS2 project) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

 It's unclear to me what incarnation of MinGW is the most appropriate to refer users to.  I have personally had the most success with the version bundled with MSYS2, but the original Mingw_w64 project is also active.

**Comment by Colengms** [comment]
Another issue that should be addressed when updating this doc: https://github.com/microsoft/vscode-cpptools/issues/4670

**Comment by sean-mcmanus** [comment]
It'd be nice to add docs for how to get the 10.2 version. We could add other mingw versions if we find a reason.

**Comment by sean-mcmanus** [comment]
I've filed a docs bug at https://github.com/microsoft/vscode-docs/issues/4319 .

**Comment by jureid** [comment]
https://github.com/microsoft/vscode-docs/pull/4645 addresses this
