### ISSUE TITLE
C++ Intellisense too slow on Unreal Project

### ISSUE THREAD

**Issue by mirkojpn87** [microsoft/vscode-cpptools#6540]
C/C++ Extension and Unreal Engine 4.25

To Check this : 
Create a new Unreal Engine Project, Create a New C++ class and ope it with VSCode, you'll se how much intellisense is slow, 10-15 seconds to get a response from intellisense.. any fix?

**Comment by sean-mcmanus** [comment]
That is a known issue. See https://github.com/microsoft/vscode-cpptools/issues/5849 .

**Comment by michelleangela** [comment]
Closing as duplicate.
