### ISSUE TITLE
Debug session not started without any feedback

### ISSUE THREAD

**Issue by fgropengieser** [microsoft/vscode-cpptools#6541]
***Environment***
- OS and Version:
     Host: macOS Catalina
     Working within Ubuntu 18.04 docker container with Remote Containers extension
- VS Code Version: 1.51
- C/C++ Extension Version: 1.1.2
- Remote-Containers Extension Version: v0.148.1

***Description***
I am working within an Ubuntu 18.04. docker container as root. When I run the debug launch configuration, the debug toolbar (with pause, step and so on) shows up but then immediately debugging exits without ANY feedback. 

***Steps to reproduce***
1. Create a helloWorld.cpp file in your workspace:
```
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```

2. Compile it with g++ -g helloWorld.cpp -o hello .
3. Set a breakpoint somewhere in the helloWorld.cpp .
4. Create a launch configuration:
 ```
{
	"name": "Hello",
	"type": "cppdbg",
	"request": "launch",
	"program": "${workspaceFolder}/hello",
	"args": [],
	"stopAtEntry": false,
	"cwd": "${workspaceFolder}",
	"environment": [],
	"externalConsole": false,
	"MIMode": "gdb",
	"setupCommands": [
		{
			"description": "Enable pretty-printing for gdb",
			"text": "-enable-pretty-printing",
			"ignoreFailures": true
		}
	]
}
```
5. Run the configuration.

***Additional info***
I can debug with gdb on command line without any problem. I also added 
   ```
 cap_add:
        - SYS_PTRACE
    security_opt:
        - seccomp:unconfined
```
to my container in the docker-compose file.

**Comment by WardenGnaw** [comment]
Can you add the following to your `launch.json` and share the output from the `Debug Console`?
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

**Comment by fgropengieser** [comment]
Hi! I did that. But there is no output at all on the Debug Console.

**Comment by WardenGnaw** [comment]
I believe this is an issue with the Remote Containers extension connecting to the debug adapter. If there are no logs there, it means the debugger failed to start up.

**Comment by james2432** [comment]
I tried enabling logging on mine as well:

    > Executing task: /usr/bin/make debug <

    /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en-GB)
    gcc -std=c17 -O0 -ggdb3 -g -D DEBUG -std=c17 -lSDL2 -lSDL2_image -D DEBUG obj/Debug/config/configuration.o obj/Debug/io/mem-map.o obj/Debug/vendor/my_itoa.o obj/Debug/Game.o obj/Debug/main.o -o ../bin/Debug/moosecasa-keypad

    Terminal will be reused by tasks, press any key to close it.

It looks like it's about to launch on the debug icon on the left(blue loading bar type) then just dies and doesn't launch the gdb session. I tried running gdb manually and have no issues:

    $ gdb ./moosecasa-keypad 
    GNU gdb (GDB) 10.1
    Copyright (C) 2020 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    Type "show copying" and "show warranty" for details.
    This GDB was configured as "x86_64-pc-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <https://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
        <http://www.gnu.org/software/gdb/documentation/>.

    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from ./moosecasa-keypad...
    (gdb) break main.c:main
    Breakpoint 1 at 0x19c0: file main.c, line 4.
    (gdb) run
    Starting program: /home/james/Github/moosecasa-keypad/bin/Debug/moosecasa-keypad 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/usr/lib/libthread_db.so.1".

    Breakpoint 1, main (argc=1, argv=0x7fffffffe5b8) at main.c:4
    4    	{
    (gdb) 



> Version: 1.51.1
>Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
>Date: 2020-11-12T10:54:25.653Z
>Electron: 9.3.4
>Chrome: 83.0.4103.122
>Node.js: 12.14.1
>V8: 8.3.110.13-electron.0
>OS: Linux x64 5.8.14.a-1-hardened-custom

**Comment by fgropengieser** [comment]
So, how to proceed with this issue? Open up another one for the Remote Containers extension?
