### ISSUE TITLE
Please help me how to run c programm in visual studio 

### ISSUE THREAD

**Issue by reddi2** [microsoft/vscode-cpptools#6542]
Issue Type: <b>Bug</b>

GCC and G++ commands are not working here in  windows 
please do help me 

Extension version: 1.1.2
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (0.73GB free)|
|Process Argv|--crash-reporter-id 260b2129-4f5f-43b9-bd8d-27c89839f9dc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eathtespagheti** [comment]
Issues are not for this, plus seems a GCC/G++ configuration problem, unrelated with vscode-cpptools

**Comment by WardenGnaw** [comment]
You can get gcc/g++ from Cygwin or MinGW.

You can use this guide to help you get started: https://code.visualstudio.com/docs/cpp/config-mingw

**Comment by heartacker** [comment]
vscode is powerful but Obscure

**Comment by sean-mcmanus** [comment]
Is this issue resolved?
