### ISSUE TITLE
Debug multiple C++ files "undefined reference" 

### ISSUE THREAD

**Issue by Welsoon** [microsoft/vscode-cpptools#6546]
**Describe the bug**
I'm tring to compile and debug muliple C++ files in VSCode, and this is my reference:https://code.visualstudio.com/docs/cpp/config-linux. I can compile my program in both VSCode tasks.josn and command line, I can also debug it in termianl by GDB. But I cant debug in VSCode using lanuch.json.
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.51.1
- C/C++ Extension Version: v1.1.2

**To Reproduce**
*My code:*
(define myprintf() in file.cpp and use it in main.cpp)
main.cpp
```
#include "file.h"
using namespace std;
int main()
{
    myprintf();
    cout<<"main: test ok"<<endl;
    return 0;
}
```
file.h
```
#include <iostream>
void myprintf();
```
file.cpp
```
#include "file.h"
using namespace std;
void myprintf()
{
    cout<<"file: test ok"<<endl;
}
```
tasks.json
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++ build active file",
			"command": "/usr/bin/g++",
			"args": [
				"-g",
				"${workspaceFolder}/*.cpp",
				"-o",
				"${fileDirname}/${fileBasenameNoExtension}"
			],
			"options": {
				"cwd": "/usr/bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: /usr/bin/g++"
		}
	]
}
```
launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true> Executing task: C/C++: g++ build active file <
                }
            ],
            "preLaunchTask": "C/C++: g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```

*Build and Debug*
I can build the program file by both VSCode "Terminal->Run build task..." or Command line "g++ main.cpp file.cpp -o mian". And the output is noraml:
```
wellsoon@wellsoon:~/solving_projrct/vscode_test$ ./main
file: test ok
main: test ok
```
but when I click"Run->Start Debugging" to debug it in VSCode, error happens:
```
> Executing task: C/C++: g++ build active file <
Starting build...
Build finished with error:
/tmp/cc6Wn0ES.o: In function `main':
/home/wellsoon/solving_projrct/vscode_test/main.cpp:5: undefined reference to `myprintf()'
collect2: error: ld returned 1 exit status
The terminal process failed to launch (exit code: -1).
Terminal will be reused by tasks, press any key to close it.
```
but i try to debug by GDB, everything is ok:
```
(gdb) file main
Reading symbols from main...done.
(gdb) run
Starting program: /home/wellsoon/solving_projrct/vscode_test/main 
file: test ok
main: test ok
[Inferior 1 (process 24557) exited normally]
(gdb) q
```

I'm not familiar with gdb in command line, I want ro debug my program in VSCode debuger.
I need your help, thanks.

**Comment by TryerGit** [comment]
The problem you have is that your tasks.json is not configured to build file.cpp.

I suggest that you use make in order to build multiple file projects.

For instance, in your case, I would suggest to have a tasks.json thus:

{
    "label":
    "command": "make",
    "args": [
        "CONF=Debug",
        "-C",
        "./.vscode"
        ]
...other stuff.
}

What the above does is that it looks for Makefile in directory ./vscode and executes it. Your actual Makefile is going to have commands like g++ -g -o and such.

There are many tutorials on how to create makefiles. I would suggest that on linux, take the help of an ide (such as Netbeans) to create and compile this project. Then, within Netbeans project folder, you will be able to find sample Makefile-Debug.mk and Makefile-Release.mk files.

Then, what you need to do is to simply copy over those makefiles into your ./.vscode/ folder. That way, your build task in tasks.json will simply call make.

**Comment by Welsoon** [comment]
Thank you for your help!
I change tasks.json and creat makefile like your suggestion, and make it.
here is my code
*tasks.json*
```
"type": "shell",
"label": "build",
"command": "make",
"args":
[
	//"-C ./.vscode"
],
```
a simple *makefile*
```
main: main.o file.o
	g++ -g main.o file.o -o main
	-rm *.o
main.o: main.cpp file.h
	g++ -c -g main.cpp -o main.o
file.o: file.cpp file.h
	g++ -c -g file.cpp -o file.o
clean:
	-rm *.o main
```
then I can build and debug my program in vscode.
I will learn to creat makefile like your suggestion later.
thanks again!

**Comment by Colengms** [comment]
It looks like this has been addressed.  If I'm mistaken, please let us know, and we can re-open this.
