### ISSUE TITLE
INCLUDE environment variable distracts IntelliSense

### ISSUE THREAD

**Issue by krzikalla** [microsoft/vscode-cpptools#6548]
**Type: LanguageService**

**Describe the bug**
- OS and Version: WIndows -> Linux (Remote SSH)
- VS Code Version:  1.51.1
- C/C++ Extension Version: 1.1.2

I have loaded a module, which sets the INCLUDE environment variable. The module contains an older version of the code I am developing (and thus INCLUDE points to a bunch of older header files).
When browsing to a symbol (Go to definition), IntelliSense opens the old header file instead of the one in my workspace folder. Changing the folder order in includePath or browse.path didn't help. limitSymbolsToIncludedHeaders is true.

**Expected behavior**
IntelliSense should open the header file in my workspace folder. If the INCLUDE environment variable is used, then only as a fallback please.

**Comment by sean-mcmanus** [comment]
Can you add the folder with the unwanted files to your files.exclude setting?

Our global symbols don't have a concept of priority or fallback for symbols at different paths.

**Comment by krzikalla** [comment]
Didn't help. Even after resetting and rescanning the unwanted file pops up. Maybe the wanted file isn't found, since I can't choose one of several findings. How can I debug Intellisense?

**Comment by sean-mcmanus** [comment]
You could set C_Cpp.loggingLevel to "Debug" or the hidden value of "7" and look for "tag parsing" logging to try to see why it is tag parsing those files that should be excluded. Your files.exclude and C_Cpp.exclusionPolicy might not be set correctly.

If the wanted file isn't shown in the list of results, the it isn't found.

The cpptools process is closed source so you'd need to work at Microsoft to get debug it.

**Comment by krzikalla** [comment]
C_Cpp.exclusionPolicy is set to the default (checkFolders). With the raised logging level  I can see, that the files are indexed, but I can't see, why. And it looks, like changing "files.exclude" has absolutely no effect. I even tried "**/*.hpp", but it still indexes all folders and finds hpp header files.

**Comment by sean-mcmanus** [comment]
"**/*.hpp" is a file-based exclusion. What syntax for exclusion are you using? The exclusion policy needs to be changed to checkFilesAndFolders if you want file-based exclusions to work.

**Comment by krzikalla** [comment]
I tried all possible combinations of exclusionPolicy and (wildcarded) patterns. To no effect. Even if I insert a particular full-pathed filename in files.exclude, that file is still indexed and will be found. 
All editing happens in the workspace settings. "search.exclude" in the same settings file works as expected BTW.
