### ISSUE TITLE
VSCPP langauge service does not respect include path

### ISSUE THREAD

**Issue by navidR** [microsoft/vscode-cpptools#655]
I did opened v8 kernel and linux kernel source code in VSCode. Since in kernel there is no shared library or anything other than you are compiling standalone, I am removing all include paths from include path in c/cpp configuration file : 
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [""],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ]
}
```

But even I am removing all include paths and I have only add rootworkspace in my settings, when I am reading source code I always get suggestion from std:: , or boost, or openssl or other libraries I do have in /usr/include .

look at this for example : 
![Image of wrong suggestions](https://cloud.githubusercontent.com/assets/3811601/25312163/833a08ca-2827-11e7-9f25-b86f02016e7e.png)

**Comment by sean-mcmanus** [comment]
The workaround is to delete the .browse.vc.db file or change your databaseFilename. This is a known issue that has existed "forever". We are not removing old stuff from the browse database. We plan to fix it: https://github.com/Microsoft/vscode-cpptools/issues/262 .
