### ISSUE TITLE
Doxygen not highlighting for C++ files

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode-cpptools#6551]
**Type: LanguageService**

Doxygen annotations are not highlighting for C++ files. By contrast, Doxygen annotations ARE highlighting fairly well for C files.

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.2
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Doxygen hello.cpp.

**Expected behavior**

The Doxygen annotations highlight as distinct from plain comments.

**Comment by sean-mcmanus** [comment]
Can you give an example? If it's a colorization issue issue then it's probably caused by https://github.com/jeff-hykin/cpp-textmate-grammar , see some existing issues: https://github.com/jeff-hykin/cpp-textmate-grammar/issues?q=is%3Aissue+is%3Aopen+doxygen
