### ISSUE TITLE
cpptools crashed on remote linux

### ISSUE THREAD

**Issue by pn1k** [microsoft/vscode-cpptools#6552]
**Type: LanguageService**

**Describe the bug**
- OS and Version: local OSX 10.12 remote ubuntu 14.04
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.2
- Other extensions you installed (and if the issue persists after disabling them): n/a
- Does this issue involve using SSH remote to run the extension on a remote machine?: yes

~/.vscode-server/extensions/ms-vscode.cpptools-1.1.2/bin/cpptools crashed with core:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000006ca495 in bool comm_client::send_request<microsoft::cpp::intellisense::InitializeRequest, microsoft::cpp::intellisense::InitializeResponse>(microsoft::cpp::intellisense::InitializeRequest&, microsoft::cpp::intellisense::InitializeResponse&, bool) ()
(gdb) bt
#0  0x00000000006ca495 in bool comm_client::send_request<microsoft::cpp::intellisense::InitializeRequest, microsoft::cpp::intellisense::InitializeResponse>(microsoft::cpp::intellisense::InitializeRequest&, microsoft::cpp::intellisense::InitializeResponse&, bool) ()
#1  0x00000000006bedce in intellisense_client::send_compilation_args() ()
#2  0x00000000006c0d7b in intellisense_client::update_compiler_args(char const*, std::shared_ptr<compilation_args_provider>) ()
#3  0x00000000006edf8c in std::_Function_handler<void (), intellisense_client_factory::update_compiler_args(char const*, std::shared_ptr<compilation_args_provider>, std::function<void ()>)::$_7>::_M_invoke(std::_Any_data const&) ()
#4  0x00000000007be4c2 in std::_Function_handler<void (), msvc::thread_pool::enqueue(std::function<void ()>, std::future<void>*)::$_2>::_M_invoke(std::_Any_data const&) ()
#5  0x00000000007bd350 in msvc::thread_pool::do_work(unsigned long) ()
#6  0x0000000000eabc80 in execute_native_thread_routine ()
#7  0x00007f3ccc734184 in start_thread (arg=0x7f3ccbd3e700) at pthread_create.c:312
#8  0x00007f3ccc46103d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by sean-mcmanus** [comment]
Hmm...that code doesn't exist with our pending 1.2.0-insiders, so it might be "fixed" (or it could crash at a different spot with our new code).

Do you have any more repro details?

**Comment by thoratou** [comment]
+1

Same issue on my side with similar settings:

OS and Version: local Windows 10 remote rhel7
VS Code Version: 1.51.1
C/C++ Extension Version: 1.1.2
Other extensions you installed (and if the issue persists after disabling them): n/a
Does this issue involve using SSH remote to run the extension on a remote machine?: yes

**Comment by michelleangela** [comment]
@pn1k does this issue still reproduce on the latest version of the C++ Extension (version 1.4.1 or insiders)?

**Comment by michelleangela** [comment]
@thoratou does this issue still reproduce on the latest version of the C++ Extension (version 1.4.1 or insiders)?
