### ISSUE TITLE
Windows Kits 10.0

### ISSUE THREAD

**Issue by Clinkz24** [microsoft/vscode-cpptools#6555]
Type: Debugger

I edit my c_cpp_properties.json, but IntelliSense still can't find corecrt.h.

**Describe the bug**
- OS and Version:
- VS Code Version:
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

- C/C++ Extension Version: v1.1.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Win32",
            "defines": [
                "_DEBUG"
            ],
            "windowsSdkVersion": "8.1",
            "cStandard": "c17",
            "cppStandard": "c++14",
            "intelliSenseMode": "msvc-x64",
            "compileCommands": ".vscode/compile_commands.json"
        }
    ],
    "version": 4
}
```

1. Go to 'corecrt.h'
2. See error

I try add includePath in c_cpp_properties.json (add windows kit 10.0.10240.0 Include),but it is still can't find corecrt.h.
How can I fix this problem. thanks

**Comment by sean-mcmanus** [comment]
Can you try removing `"windowsSdkVersion": "8.1"`?

Also, are  you really trying to use 10.0.10240.0? I'm seeing only the ucrt folder under C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0 -- is that what you see? Can you use a newer version of the SDK? Our code won't recognize a Windows SDK that just has a ucrt folder. If you add a "um" and "shared" folder, then that could trick our code into recognizing that as a valid Windows SDK install.

**Comment by diablodale** [comment]
Perhaps related to the known issue https://github.com/microsoft/vscode-cpptools/issues/5335

**Comment by Colengms** [comment]
Hi @Clinkz24 .  Your use of `compileCommands` takes precedence over your other settings in `c_cpp_properties.json`.  When that field is set, the command-lines in your `compile_commands.json` are assumed to contain all of the information necessary to configure IntelliSense.  They should be complete command lines, capable of successfully compiling your sources.  IntelliSense should be using the same version of the Windows SDK as is used when compiling those sources.

**Comment by Clinkz24** [comment]
> Can you try removing `"windowsSdkVersion": "8.1"`?
> 
> Also, are you really trying to use 10.0.10240.0? I'm seeing only the ucrt folder under C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0 -- is that what you see? Can you use a newer version of the SDK? Our code won't recognize a Windows SDK that just has a ucrt folder. If you add a "um" and "shared" folder, then that could trick our code into recognizing that as a valid Windows SDK install.

sorry,I didn't get back to you immediately. I didn't see the github notification email...
* remove 'windowsSdkVersion' or set "windowsSdkVersion":"10.0.10240.0" doesn't solve the my problem.
* actually,I don't use 10.0.10240.0, I hava other compilation tool (xmake),it is work find on my code. I just want VsCode not to show those error messages and to jump to the header files normally.

**Comment by Clinkz24** [comment]
> Hi @Clinkz24 . Your use of `compileCommands` takes precedence over your other settings in `c_cpp_properties.json`. When that field is set, the command-lines in your `compile_commands.json` are assumed to contain all of the information necessary to configure IntelliSense. They should be complete command lines, capable of successfully compiling your sources. IntelliSense should be using the same version of the Windows SDK as is used when compiling those sources.

sorry,I didn't get back to you immediately. I didn't see the github notification email...
What you said should be right.'includePath' works when I remove 'comile_commands.json'.
my Visual Studio 2015 show my windowsSdk Version is 8.1,but it jumps correctly to 'corecrt.h' in '10.0.10240.0'.
My code needs same libraries,so I don't want to set headers to contain directories, and they have versions.
If this isn't reconceiable, I'll just set 'includePath' to remove 'compile_commands.json'.

**Comment by Clinkz24** [comment]
I copy folder(um and shared) from windows kit 8.1 to windows kit 10.0.10240.
look solve my problem :)
so I close this issues.
thanks guys.
