### ISSUE TITLE
Missing warnings

### ISSUE THREAD

**Issue by KristofMerey** [microsoft/vscode-cpptools#6556]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.2
- Other extensions you installed (and if the issue persists after disabling them): I disabled all the other installed extensions (Coverage Gutters, GitLens, Hex Editor, Live Share, Remote - WSL) but the problem still exists.
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Problems window (in the place of the built-in terminal window) does not contain warnings but errors. Similarly, the output of build task suppresses warnings and only shows the direct output of gcc if any error occurs.

**Steps to reproduce**

Use any code that contains code that produces warnings. The following code gives two warnings (implicit declaration of function 'printf', and unused variable 'i' with the -Wall argument). The implicit function declaration produces warning even if -Wall flag is inactive.

```
int main(void) {
    int i;
    printf("Hello");
    return 0;
}
```

**Expected behavior**

Warnings should be displayed in problems window as well as errors. Warnings should not suppress in the output of build task.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 2020. 11. 20. 15:24:20
Version: 1.1.2
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.17763.0",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "compilerArgs": [],
    "intelliSenseMode": "gcc-x64",
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "compilerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-win32-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ PRIVATE_PATH_TO_COMPILED_FILE ]:
    PRIVATE_PATH_TO_COMPILED_FILE
Translation Unit Configurations:
[ PRIVATE_PATH_TO_COMPILED_FILE ]:
    Process ID: 16544
    Memory Usage: 12 MB
    Compiler Path: C:\Program Files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin\gcc.exe
    Includes:
        C:\PROGRAM FILES\MINGW-W64\X86_64-8.1.0-WIN32-SEH-RT_V6-REV0\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE
        C:\PROGRAM FILES\MINGW-W64\X86_64-8.1.0-WIN32-SEH-RT_V6-REV0\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE-FIXED
        C:\PROGRAM FILES\MINGW-W64\X86_64-8.1.0-WIN32-SEH-RT_V6-REV0\MINGW64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=80100
Total Memory Usage: 12 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 2440
Number of files discovered (not excluded): 2386


```
</details>

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. Until we have a fix, a workaround is to change the task's type to from "cppbuild" to "shell" (you may need to Reload Window after the change).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.3
