### ISSUE TITLE
warning "Unable to resolve configuration with compilerPath "...rc.exe".  Using "cl.exe" instead."

### ISSUE THREAD

**Issue by diablodale** [microsoft/vscode-cpptools#6559]
**Type: LanguageService**

A new unexpected warning appears in its own dedicated output window/tab "c/c++ configuration warnings"

```
[11/20/2020, 9:19:13 PM] Unable to resolve configuration with compilerPath "C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe".  Using "cl.exe" instead.
```

That path in the warning does exist and I can use that exact path at a CMD prompt and it does run the RC compiler. I have no idea what this warning is warning me about and I have yet seen any side affects.

### Describe the bug
- OS and Version: Microsoft Windows [Version 10.0.19042.630]
- VS Code Version: 1.51.1 (system setup)
- C/C++ Extension Version: v1.1.2
- Other extensions you installed (and if the issue persists after disabling them): reproduces with only enabled:  c/c++, cmake tools
- Does this issue involve using SSH remote to run the extension on a remote machine?: no

This new warning appears in its own dedicated output window/tab "c/c++ configuration warnings". The new warning appears within the last two weeks. During that time I did update VS Studio 2019 to version 16.8.0 and then 16.8.2. VSCode itself or the c++ extension might have auto updated itself.

No workspace other than this single folder. It is a cmake project. When I open vscode to that project folder, this tab/window opens and I see this warning.

### Steps to reproduce

1. Open VSCode to the project folder

### Result

A tab/window opens "c/c++ configuration warnings" and a warning appears in it

```
[11/20/2020, 9:19:13 PM] Unable to resolve configuration with compilerPath "C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe".  Using "cl.exe" instead.
```

### Expected

No tab window. No warning. No side affects.

#### c_cpp_properties.json

```json
{
    "configurations": [
        {
            "name": "Win32",
            "intelliSenseMode": "msvc-x64",
            "configurationProvider": "ms-vscode.cmake-tools",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "RC_INVOKED"
            ],
            "windowsSdkVersion": "10.0.17134.0",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

#### folder's settings.json

Notice the `files.associations` setting. Perhaps a recent change to the extension is surfacing a warning that was not before.

```json
{
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "cmake.configureOnOpen": false,
    "cmake.configureSettings":{
        "CMAKE_VERBOSE_MAKEFILE": "ON"
    },
    "cmake.parseBuildDiagnostics": true,
    "C_Cpp.default.configurationProvider": "vector-of-bool.cmake-tools",
    "C_Cpp.default.intelliSenseMode": "msvc-x64",
    "C_Cpp.default.windowsSdkVersion": "8.1",
    "C_Cpp.default.cStandard": "c11",
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.default.compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "C_Cpp.default.includePath": [
        "${workspaceFolder}",
        "${workspaceFolder}/build"
    ],
    "C_Cpp.default.defines": [
        "RC_INVOKED"
    ],
    "C_Cpp.vcpkg.enabled": true,
    "files.associations": {
        "*.rc": "cpp",
        "*.rc.in": "cpp"
    },
    "C_Cpp.loggingLevel": "Debug"
}

```

**Logs**

Some of the logs are redacted. Please contact me in this issue or email if you want the full content.

<details>
  <summary><strong>C/C++: Log Diagnostics</strong></summary>

```
-------- Diagnostics - 11/20/2020, 10:31:25 PM
Version: 1.1.2
Current Configuration:
{
    "name": "Win32",
    "intelliSenseMode": "msvc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE",
        "RC_INVOKED"
    ],
    "windowsSdkVersion": "10.0.17134.0",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
...redacted...
    ],
    "standard": "c++17",
    "compilerPath": "c:/program files (x86)/microsoft visual studio/2019/community/vc/tools/msvc/14.28.29333/bin/hostx64/x64/cl.exe",
    "compilerArgs": [
        "-DWIN32",
        "/DWIN32",
        "/D_WINDOWS",
        "/GR",
        "/EHsc",
        "/O2",
        "/Ob2",
        "/DNDEBUG",
        "-MD",
        "/GL",
        "/W4",
        "/wd4200",
        "/WX",
        "/ZH:SHA_256",
        "/utf-8",
        "/Y-",
        "/arch:AVX",
        "/fp:fast",
        "/Qpar-report:1",
        "/Qvec-report:1",
        "/guard:cf",
        "/GS-",
        "/Gw",
        "/QIntel-jcc-erratum",
        "-std:c++17"
    ]
}
Translation Unit Mappings:
...redacted...
Translation Unit Configurations:
...redacted...
------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 17586
Number of files discovered (not excluded): 14185
```
</details>

<details>
  <summary><strong>Language Server logs</strong></summary>

```
Custom browse configuration received: {
  "browsePath": [
     ...redacted...
  ],
  "standard": "c++17",
  "compilerPath": "c:/program files (x86)/microsoft visual studio/2019/community/vc/tools/msvc/14.28.29333/bin/hostx64/x64/cl.exe",
  "compilerArgs": [
    "-DWIN32",
    "/DWIN32",
    "/D_WINDOWS",
    "/GR",
    "/EHsc",
    "/O2",
    "/Ob2",
    "/DNDEBUG",
    "-MD",
    "/GL",
    "/W4",
    "/wd4200",
    "/WX",
    "/ZH:SHA_256",
    "/utf-8",
    "/Y-",
    "/arch:AVX",
    "/fp:fast",
    "/Qpar-report:1",
    "/Qvec-report:1",
    "/guard:cf",
    "/GS-",
    "/Gw",
    "/QIntel-jcc-erratum",
    "-std:c++17"
  ]
}
cpptools/didChangeCppProperties
MSVC intelliSenseMode specified.  Configuring for compiler cl.exe.
Code browsing service initialized
MSVC intelliSenseMode specified.  Configuring for compiler cl.exe.
Attempting to get defaults from C++ compiler in compile_commands.json file: 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe'
Attempting to get defaults from C++ compiler in compile_commands.json file: 'C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe'
Probing compiler for default C language standard using command line: "C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe" -x c -E -dM nul
Probing compiler for default C++ language standard using command line: "C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe" -x c++ -E -dM nul
Probing compiler's default target using command line: "C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe" -dumpmachine
Unhandled default compiler target value detected: 
Compiler probe command line: "C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe" /fo CMakeFiles\redacted.dir\version.rc.res -std=c++17 -Wp,-v -E -dD -x c++ -m64  nul
Failed to query compiler. Falling back to 32-bit intelliSenseMode.
Compiler probe command line: "C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe" /fo CMakeFiles\redacted.dir\version.rc.res -std=c++17 -Wp,-v -E -dD -x c++ -m32  nul
Failed to query compiler. Falling back to no bitness.
Compiler probe command line: "C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe" /fo CMakeFiles\redacted.dir\version.rc.res -std=c++17 -Wp,-v -E -dD -x c++   nul

MSVC intelliSenseMode specified.  Configuring for compiler cl.exe.
Attempting...
```
</details>

**Comment by sean-mcmanus** [comment]
Yeah, I think you can ignore the message. We're not handling rc.exe ideally in regards to the warnings.

**Comment by Jimbo99** [comment]
In case it is useful to know, Sean,  in the past week I've started getting the same warning appearing when using a different compiler. The compiler is XC8 made by Microchip (microchip.com) for their microcontrollers.

`[25/11/2020, 10:50:44] Unable to resolve configuration with compilerPath "C:/Program Files (x86)/microchip/xc8/v1.38/bin/cpp.exe".  Using "D:\PIC18\bin\cpp.exe" instead.`

Been using XC8 ok in VSCode for months with no such warning appearing previously.

**Comment by Colengms** [comment]
@diablodale The extension should not attempt to configure a compiler from `compile_commands.json` unless it has a default file extension that indicates the file is C/C++ (such as .cpp, .c, .h, .cxx, etc.), or is specified in a `files.association` settings indicating C or C++.  Could you confirm that you have not specified the file name or file extension being passed to your RC, compiler as a C or C++ file?

@Jimbo99 This warning is relatively new, and the intention was to surface configuration errors (and fallback to default behavior) that were otherwise hidden from users.  There should be additional information in the C/C++ output channel (if `"C_Cpp.loggingLevel": "Debug"` is set) indicating the command line we attempted to use to probe the compiler, which failed.

**Comment by diablodale** [comment]
I do. See original post in section "folder's settings.json"
My intention is to get `ifdef`, parsing, and colorization of RC files.

**Comment by Colengms** [comment]
This would seem to be by design, if you've indicated that RC files be treated like C/C++ files.  Would you like to convert this issue into a feature request for support of parsing and colorization of .rc files (in such a way that does not require disguising them as C/C++ files) ?

**Comment by Jimbo99** [comment]
> @Jimbo99 This warning is relatively new, and the intention was to surface configuration errors (and fallback to default behavior) that were otherwise hidden from users. There should be additional information in the C/C++ output channel (if `"C_Cpp.loggingLevel": "Debug"` is set) indicating the command line we attempted to use to probe the compiler, which failed.

@Colengms Thank you for the information. Very helpful. I can see from the debug info that the XC8.exe compiler is causing issues currently so I'll work on that.

**Comment by diablodale** [comment]
ok. I have no strong disagreement with the 'by design' for file.associations (ab)use to have intellisense for RC files. The benefit is worth the new warning.

I'll leave this issue open as @Jimbo99 scenario is under investigation

**Comment by RogFedex** [comment]
Adding my observation:
The below warning message is observed
Unable to resolve configuration with compilerPath "C:\Program Files (x86)\GNU Arm Embedded Toolchain\9 2020-q2-update\bin\arm-none-eabi-gdb.exe".  Using "cl.exe" instead.

My Settings is as below
"C_Cpp.default.compilerPath": "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\9 2020-q2-update\\bin\\arm-none-eabi-gdb.exe"

**Comment by bobbrow** [comment]
@RogFedex
Did you mean to use the cross compiler for `gcc` instead of `gdb` (the debugger)?

**Comment by RogFedex** [comment]
Intention is to use gdb for debugging C++ code and cross compiler arm gdb
for C code. How do i configure ?

**Comment by Colengms** [comment]
@RogFedex Did you mean to specify `arm-none-eabi-gcc` instead?  `gdb` refers to a debugger.  I suspect you are not using the debugger executable to compile code.  The `C_Cpp.default.compilerPath` setting (or the `compilerPath` field in `c_cpp_properties.json`) refers to the compiler to configure language services (IntelliSense) based on.  We query that compiler for system includes and system defines.  Building/compiling source code would require a build system (such as CMake).  Or, you could generate a `tasks.json` using the `Build and Debug Active File` command, if building just a single source file.  Attempting to debug should trigger generation of a `tasks.json` file, which you could then configure to refer to a specific `gdb` executable, if necessary.

Since it looks like diablodale's and Jimbo99's concerns have been addressed, I'm going to close this issue.  @RogFedex , if you need further assistance, could you create a new issue?
