### ISSUE TITLE
Certain clang-format options are not recognized

### ISSUE THREAD

**Issue by Vultraz** [microsoft/vscode-cpptools#656]
When running Format Document, certain options in a local clang-format config file are not recognized and cause the tool to fall back on default formatting. I've observed this with at least these:

- `SpaceAfterTemplateKeyword`
- `FixNamespaceComments`

I have confirmed these are valid according to [the clang-format style guide](https://clang.llvm.org/docs/ClangFormatStyleOptions.html). Only thing I can think of is these options are newer than the included clang-format version.

**Comment by sean-mcmanus** [comment]
We install/use clang-format 3.8, but those options are newer. You can set the C_Cpp.clang_format_path to a newer clang-format version if you want. We were planning to update to 4.0 soon, but that version doesn't have FixNamespaceComments. Is there a specific version you wanted us to use? I don't think version 5.0 is officially released yet.

**Comment by Vultraz** [comment]
I had no specific version in mind, no. `SpaceAfterTemplateKeyword` is more useful to the project we're working on than `FixNamespaceComments` anyway.

Thanks for clearing this up :)

**Comment by bobbrow** [comment]
This was fixed in version 0.11.1. Please reopen if you continue to have this issue.

**Comment by Vultraz** [comment]
Nope, it works fine now. Thanks :)
