### ISSUE TITLE
Highlighting breaks after macro expanding to C++ attribute

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode-cpptools#6560]
VSCode cpptools extension 1.1.2.

On this file: https://github.com/google/flatbuffers/blob/master/include/flatbuffers/flatbuffers.h

Highlighting after `FLATBUFFERS_ATTRIBUTE` is broken.
![image](https://user-images.githubusercontent.com/7413219/99869247-d8c2d480-2bc9-11eb-9467-e1add03896c5.png)

If I comment it out it restores:
![image](https://user-images.githubusercontent.com/7413219/99869262-e7a98700-2bc9-11eb-9710-d519474f60d7.png)

The macro is expanded to (with C++17):
```
#define FLATBUFFERS_ATTRIBUTE(attr) [[attr]]
```

If I replace macro with the attribute highlighting is okay.

**Comment by Colengms** [comment]
Hi @ytimenkov I'm able to repro, however I'm also able repro with the C/C++ Extension disabled, so it doesn't seem to be the cause.  The C/C++ Extension provides colorization for semantic tokens.  Colorization for syntax is coming from VS Code and it's TextMate grammar for C/C++.  That grammar is contributed by from this repo: https://github.com/jeff-hykin/cpp-textmate-grammar  I'd suggest following up with an issue against that repo.

**Comment by ytimenkov** [comment]
Ah, I see... I thought that when enabled LS takes colorization over completely.
