### ISSUE TITLE
can't stop the code from running

### ISSUE THREAD

**Issue by Omar-mohammed-ibrahim** [microsoft/vscode-cpptools#6564]
Issue Type: <b>Bug</b>

i just want to say that my language isn't good as it's my second language so please don't judge my mistakes at writing my issue.

when i finished the code and started to run it, the code commands didn't appear in the output.
and when i tried to end running the code, i couldn't cause i didn't find the (stop) button.
when i tried to rerun the code it told me (the code is already running).
but the code isn't appearing in the output and there is no problem in the code.
![11](https://user-images.githubusercontent.com/74864515/99906042-b0c89380-2ce5-11eb-9dfb-7d562e51b6fb.png)

t appearing in the output and there is no problem in the p

Extension version: 1.1.2
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.63GB free)|
|Process Argv|--crash-reporter-id 165c7316-288c-4c3a-8355-c49e468872db|
|Screen Reader|no|
|VM|67%|
</details>

**Comment by sean-mcmanus** [comment]
Your question appears to be with the C/C++ Compile Run extension or some other extension (not the C/C++ extension). We're not familiar with those other extensions.
