### ISSUE TITLE
cpptools fails on raspbian desktop buster

### ISSUE THREAD

**Issue by ConnectMyEV** [microsoft/vscode-cpptools#6566]
Type: General

**Describe the bug**
- OS and Version: raspbian desktop buster (running on intel x86-64 Virtual Machine)
- VS Code Version: 1.32
- C/C++ Extension Version: 0.27.1
- Other extensions you installed (and if the issue persists after disabling them): No other extensions installed
- A clear and concise description of what the bug is.
 cpptools supplied by the extension fails to tun. As a result debugging is not possible. I understand that I am using vscode 1.32. However, that is the latest version available for this particular OS configuration and consequently, 0.27.1 is also best available extension version.
Note that all of this was working on raspbian desktop "stretch".
As of now, I am going back to raspbian stretch. However it would be good to get this sorted out going forward.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**
When I open a c++ file, I get the following error:
Launching server using command /home/pi/.vscode-oss/extensions/ms-vscode.cpptools-0.27.1/bin/cpptools failed.

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by sean-mcmanus** [comment]
Your Raspbian OS is ARM right? We didn't add support for Linux ARM until version 1.0.0, which requires VS Code 1.44.0: https://github.com/microsoft/vscode-cpptools/releases/tag/1.0.0 . You also may be hitting other bugs that have been fixed in our latest version.

Raspbian Buster should be able to download the latest VS Code and C/C++ extension versions.

**Comment by ConnectMyEV** [comment]
Dear Sean,
No. My computer is using an Intel Xeon processor.
The raspbian in question is running as a Virtual Machine on this computer.
When I run "hostnamectl", I get the following. Note that the architecture says x86-64. (Please ignore that it now says Debian 9 because after my unsuccessful attempt to upgrade to "Raspbian Buster", I had to go back to "Raspbian Stretch" and that's why it shows Debian 9 in the following output).:

   Static hostname: raspberry
   Icon name: computer-vm
   Chassis: vm
   Machine ID: xxxxx (Removed by me)
   Boot ID: xxxxx (Removed by me)
   Virtualization: vmware
   Operating System: Debian GNU/Linux 9 (stretch)
   Kernel: Linux 4.9.0-14-amd64
   Architecture: x86-64

**Comment by sean-mcmanus** [comment]
What does it show when you run `/home/pi/.vscode-oss/extensions/ms-vscode.cpptools-0.27.1/bin/cpptools` and `file  `/home/pi/.vscode-oss/extensions/ms-vscode.cpptools-0.27.1/bin/cpptools` from the command line?

FYI, our extension doesn't support running on .vscode-oss (Code OSS), only the official VS Code distro.

**Comment by ConnectMyEV** [comment]
Dear Sean,
Yes, I do recognize that Microsoft extension is not guaranteed to work on code-oss and perhaps the support for the virtual machines for raspbian is also out of scope for you. Hence I did an immediate reversal to "Raspbian Stretch". I will live with it for now. Although it would be good to address this, it's not stopping me now.

In the meantime, when I try to run cpptools from the command line I get:
bash: ./cpptools: No such file or directory

**Comment by sean-mcmanus** [comment]
That means the binaries didn't get downloaded installed, possibly a known issue that was fixed with newer releases. A potential workaround could be to use the offline vsix at https://github.com/microsoft/vscode-cpptools/releases/tag/0.27.1 .

**Comment by ConnectMyEV** [comment]
Dear Sean,
I will try that some time tonight, but the binary file exists in the said
directory. I did not post the output of ls -lai, but I see cpptools being
present.
When I am in front of the computer, I will post output of ls -lai
I will also try your workaround and let you know.
Thanks.

**Comment by ConnectMyEV** [comment]
Dear Sean,
As I stated earlier, the cpptools file exists and it has execution permissions. See the output of "ls -lai" below:
pi@raspberry:~/.vscode-oss/extensions/ms-vscode.cpptools-0.27.1/bin $ ls -lai
total 25148
790748 drwxr-xr-x  3 pi pi     4096 Nov 24 18:50 .
668115 drwxr-xr-x  9 pi pi     4096 Nov 24 18:50 ..
790926 -rwxr-xr-x  1 pi pi 15045520 Nov 24 18:50 cpptools
790927 -rwxr-xr-x  1 pi pi 10633424 Nov 24 18:50 cpptools-srv
790749 drwxr-xr-x 15 pi pi     4096 Nov 24 18:49 messages
790776 -rw-r--r--  1 pi pi      103 Nov 24 18:49 msvc.32.darwin.json
790777 -rw-r--r--  1 pi pi      357 Nov 24 18:49 msvc.32.darwin.msvc.json
790778 -rw-r--r--  1 pi pi      105 Nov 24 18:49 msvc.32.intel.clang.json
790779 -rw-r--r--  1 pi pi      359 Nov 24 18:49 msvc.32.intel.json
790780 -rw-r--r--  1 pi pi      103 Nov 24 18:49 msvc.32.linux.json
790781 -rw-r--r--  1 pi pi      357 Nov 24 18:49 msvc.32.linux.msvc.json
790782 -rw-r--r--  1 pi pi      103 Nov 24 18:49 msvc.64.darwin.json
790783 -rw-r--r--  1 pi pi      383 Nov 24 18:49 msvc.64.darwin.msvc.json
790784 -rw-r--r--  1 pi pi      105 Nov 24 18:49 msvc.64.intel.clang.json
790785 -rw-r--r--  1 pi pi      383 Nov 24 18:49 msvc.64.intel.json
790786 -rw-r--r--  1 pi pi      105 Nov 24 18:49 msvc.64.linux.json
790787 -rw-r--r--  1 pi pi      383 Nov 24 18:49 msvc.64.linux.msvc.json
790788 -rw-r--r--  1 pi pi      684 Nov 24 18:49 msvc.json

**Comment by sean-mcmanus** [comment]
Okay, then can your execute "cpptools" and "file cpptools" via the command line to see what it gets? We need info on what is wrong with those binaries.

**Comment by ConnectMyEV** [comment]
pi@raspberry:~/.vscode-oss/extensions/ms-vscode.cpptools-0.27.1/bin $ ls -lai
total 25148
790748 drwxr-xr-x  3 pi pi     4096 Nov 24 18:50 .
668115 drwxr-xr-x  9 pi pi     4096 Nov 24 18:50 ..
790926 -rwxr-xr-x  1 pi pi 15045520 Nov 24 18:50 cpptools
790927 -rwxr-xr-x  1 pi pi 10633424 Nov 24 18:50 cpptools-srv
790749 drwxr-xr-x 15 pi pi     4096 Nov 24 18:49 messages
790776 -rw-r--r--  1 pi pi      103 Nov 24 18:49 msvc.32.darwin.json
790777 -rw-r--r--  1 pi pi      357 Nov 24 18:49 msvc.32.darwin.msvc.json
790778 -rw-r--r--  1 pi pi      105 Nov 24 18:49 msvc.32.intel.clang.json
790779 -rw-r--r--  1 pi pi      359 Nov 24 18:49 msvc.32.intel.json
790780 -rw-r--r--  1 pi pi      103 Nov 24 18:49 msvc.32.linux.json
790781 -rw-r--r--  1 pi pi      357 Nov 24 18:49 msvc.32.linux.msvc.json
790782 -rw-r--r--  1 pi pi      103 Nov 24 18:49 msvc.64.darwin.json
790783 -rw-r--r--  1 pi pi      383 Nov 24 18:49 msvc.64.darwin.msvc.json
790784 -rw-r--r--  1 pi pi      105 Nov 24 18:49 msvc.64.intel.clang.json
790785 -rw-r--r--  1 pi pi      383 Nov 24 18:49 msvc.64.intel.json
790786 -rw-r--r--  1 pi pi      105 Nov 24 18:49 msvc.64.linux.json
790787 -rw-r--r--  1 pi pi      383 Nov 24 18:49 msvc.64.linux.msvc.json
790788 -rw-r--r--  1 pi pi      684 Nov 24 18:49 msvc.json
pi@raspberry:~/.vscode-oss/extensions/ms-vscode.cpptools-0.27.1/bin $ file cpptools
cpptools: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=d8d75d34e57462f231e14c34ac13bb54e5e09d18, not stripped
pi@raspberry:~/.vscode-oss/extensions/ms-vscode.cpptools-0.27.1/bin $ ./cpptools
bash: ./cpptools: No such file or directory

**Comment by sean-mcmanus** [comment]
Okay...I don't know what is going on then. The file info says your binary is the 64-bit binary and you appear to have permissions, so executing ./cpptools should work.

What results do you get with ~/.vscode-oss/extensions/ms-vscode.cpptools-0.27.1/bin/LLVM/bin/clang-format? Those binaries should be similar to the Ubuntu binaries at https://releases.llvm.org/download.html .
