### ISSUE TITLE
The priority of includePath does not seem to be in effect?

### ISSUE THREAD

**Issue by huanghantao** [microsoft/vscode-cpptools#6568]
This is my configuration:

```json
{
    "configurations": [{
        "name": "PHP",
        "includePath": [
            "${workspaceFolder}/**",

            "/usr/local/include",

            "/usr/local/Cellar/php/7.4.10/include/php",
            "/usr/local/Cellar/php/7.4.10/include/php/Zend",
            "/usr/local/Cellar/php/7.4.10/include/php/main",
            "/usr/local/Cellar/php/7.4.10/include/php/TSRM"
        ],
        "defines": [],
        "compilerPath": "/usr/bin/g++",
        "cStandard": "c11",
        "cppStandard": "c++11"
    }],
    "version": 4
}
```

But search for two definitions:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/22836925/99950901-3b79c300-2db8-11eb-80c0-6f5cb103c281.png">

I just want it to show the first one, which is under the workspaceFolder. The second one I don't want to show.

What's wrong with my configuration?

**Comment by huanghantao** [comment]
I've reset the database, but it doesn't work.

**Comment by sean-mcmanus** [comment]
It sounds like there are 2 issues.

1. ${workspaceFolder}/** (recursive includes) will cause all those sub folders to get the lowest priority, so any subfolders that should be included before the other non-recursive includes should be explicitly added non-recursively, e.g. add ${workspaceFolder} to your includePath (and/or subfolders).
2. Multiple definitions should not appear if the current TU is compiled/configured correctly for IntelliSense and should only appear if it's falling back to the tag parser database (which has no concept of a priority/ordering). One potential workaround is to configure the files.exclude and C_Cpp.exclusionPolicy settings to exclude symbols from the unwanted folders or to set the C_Cpp.default.browse.path setting to a subset of the includePath setting (normally it inherits from the includePath).

Does that solve your issue?
