### ISSUE TITLE
semantic tokens: use 'method' instead of 'member'

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-cpptools#6569]
After requests in microsoft/language-server-protocol#1087 we decided to deprecate the 'member' token type in favor of a new 'method' token type.

The 'method' token type stands for all types of member functions (also if the language calls it differently)

VSCode issue: microsoft/vscode#111172

@Colengms FYI

**Comment by Colengms** [comment]
I gather this change will need to wait until VS Code 1.52 is released.

**Comment by aeschli** [comment]
Yes, you better wait until 1.52 is out (or restrict the extension to 1.52)

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
