### ISSUE TITLE
sizeof keyword not recognized in C++ mode

### ISSUE THREAD

**Issue by SPAstef** [microsoft/vscode-cpptools#6571]
Hello,
I'm running the 1.1.2 version of the C/C++ tools extension. When in C++ mode, the `sizeof` operator doesen't get recognized if not parenthesized. Example:

C mode:
![image](https://user-images.githubusercontent.com/9153046/100077072-32cdcf00-2e42-11eb-8980-22719edce059.png)
 
C++ mode:
![image](https://user-images.githubusercontent.com/9153046/100077164-509b3400-2e42-11eb-91ce-12b02a31c920.png)

I am not expert of the C++ standard, but cppreference says that `sizeof` is a builtin operator (keyword) in C++ too, and that doesen't require parentheses (unless evaluating a type name of course).

**Comment by Colengms** [comment]
Hi @SPAstef .  By 'recognized', are you are referring to colorization?  I can repro, but even with the  the C/C++ Extension disabled, so it does not appear to be the cause.  While the C/C++ Extension provides colorization for Semantic tokens, syntactic tokens (such as for keywords, like sizeof) are provided by VS Code using TextMate grammar for C/C++.  That grammar is contributed by this repro: https://github.com/jeff-hykin/cpp-textmate-grammar   I'd suggest opening an issue there.

**Comment by SPAstef** [comment]
> Hi @SPAstef . By 'recognized', are you are referring to colorization? I can repro, but even with the the C/C++ Extension disabled, so it does not appear to be the cause. While the C/C++ Extension provides colorization for Semantic tokens, syntactic tokens (such as for keywords, like sizeof) are provided by VS Code using TextMate grammar for C/C++. That grammar is contributed by this repro: https://github.com/jeff-hykin/cpp-textmate-grammar I'd suggest opening an issue there.

Thanks a lot! I opened an issue there! In the meantime, is there any way to add a custom keyword manually?

**Comment by Colengms** [comment]
>is there any way to add a custom keyword manually?

Hi @SPAstef .  I suspect there would be more to it than manually adding a keyword, as the same keyword gets colorized correctly in other contexts.  The issue would seem to be with regular expressions in the TextMate grammar which would need to be updated to properly match the keyword also for the syntax that is failing.  Jeff's TextMate grammar repro would probably be the best place to discuss how to locally apply a fix.
