### ISSUE TITLE
Format on `;` with vcFormat isn't working

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6576]
With C_Cpp.formatting set to vcFormat see the repro:

```
int main()
{
	for (int k = 1; k < 10; k++) {
			int i = 0; // auto-format on ; fails here
		int j=1+2; // on type ; formatting fails here too
	}
}
```

The bug doesn't repro with VS.

This was originally reported as part of https://github.com/microsoft/vscode-cpptools/issues/6561

**Comment by Colengc** [comment]
@sean-mcmanus  I'm not repro'ing this.  Did you also set? `"editor.formatOnType": true`.  If so, there is more info needed, as simply copying and pasting that code, I see it format when I type ";" over the existing instances.

**Comment by Colengms** [comment]
@sean-mcmanus I'm not repro'ing this. Did you also set? "editor.formatOnType": true. If so, there is more info needed, as simply copying and pasting that code, I see it format when I type ";" over the existing instances.

**Comment by sean-mcmanus** [comment]
You're right -- I was confused because typing } was invoking format on type behavior -- is that the real bug? It seems like type } shouldn't format if formatOnType is disabled.

**Comment by sean-mcmanus** [comment]
Oh -- looks like the formatting on } is coming from VS Code.

**Comment by sean-mcmanus** [comment]
@Colengms Any idea how to disable that behavior? Changing editor.autoIndent isn't working.

**Comment by sean-mcmanus** [comment]
I filed bug https://github.com/microsoft/vscode/issues/111265
