### ISSUE TITLE
strange C++ symbol jumping

### ISSUE THREAD

**Issue by baiwfg2** [microsoft/vscode-cpptools#6578]
**Type: LanguageService**

**Describe the bug**
- OS and Version: mac 10.14.5
- VS Code Version: 1.50.1
- C/C++ Extension Version: 1.1.2
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![vscpp-strange-jump](https://user-images.githubusercontent.com/5157680/100206083-dbfaef00-2f40-11eb-97bf-602a6fc89e8f.gif)

**Additional context**

Hi. I'm open facebook/mysql-5.6 project and find the above phenomena. Strange, isn't it ? It cannot find `rocksdb::TransactionDB`, but it surprisingly jumps to `Table::Open()` within leveldb header in system path instead of telling me `No definition Found`.

**Comment by baiwfg2** [comment]
It works well most of time. It just happens in this case.

**Comment by michelleangela** [comment]
@baiwfg2 

Could you run the command `C/C++: Log diagnostics` from the VS Code command palette and share the output? It will show what include paths the IntelliSense refers to.
