### ISSUE TITLE
Feature Request — Support for doxygen Documentation

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-cpptools#658]
Moved from Microsoft/vscode#25231
From @rei-vilo 

---

[Doxygen](http://www.stack.nl/~dimitri/doxygen/) provides a very nice way of adding documentation to the code thanks to keywords.

Some IDEs support Doxygen natively and display the documentation related to the function being typed in.

<img width="547" alt="capture 2017-04-24 a 16 35 56" src="https://cloud.githubusercontent.com/assets/951776/25342373/2e6c7d06-290c-11e7-94be-63caf31ae1e3.png">

<img width="704" alt="capture 2017-04-24 a 16 35 30" src="https://cloud.githubusercontent.com/assets/951776/25342372/2e50a8f6-290c-11e7-9051-0e792ddef688.png">

**Comment by hoffmael** [comment]
Adding my vote to this one. Doxygen would be very useful and I'd hope for it being as robust as the JsDoc implementation.

**Comment by benjaminjack** [comment]
I would also really like to see this feature implemented. Doxygen support for C++ is the one feature that's really feels missing coming over from Atom.

**Comment by trybik** [comment]
I fourth that.. had to go back to Eclipse to generate some of them docs

**Comment by aa6moham** [comment]
I also feel that adding Doxygen support in VS code would be very beneficial !

**Comment by cesar-pa** [comment]
The lack of Doxygen block generation is the only thing stopping me to leave Sublime. I need to have something like DocBlockr.

**Comment by HallEffect** [comment]
I'd like to have something like DoxyDoxygen in Sublime to generate comment by Alt+Q

**Comment by Ikar-Rahl** [comment]
ADDITIONALLY:
- Syntax highlighting
- (smart) Docstring generation (customisable)
- Ability to run Doxygen and Doxyfile configurator from the ide.

I don't know what from that could be done by a plugin.

**Comment by rei-vilo** [comment]
Any update on that feature request? Thanks!

**Comment by sean-mcmanus** [comment]
@rei-vilo Comments attached to variables are part of our ongoing work of porting code from VS. If you're asking for doxygen support that don't exist in VS code itself, then that would not something we currently have plans to add.

**Comment by rei-vilo** [comment]
Good to know, thank you for the feed-back.

**Comment by Trevinlc1997** [comment]
Definitely want! I hope this can come soon,

**Comment by moof2k** [comment]
+1

This was my favorite feature of Visual Studio and Visual Assist: https://docs.wholetomato.com/default.asp?W206

![](https://docs.wholetomato.com/default.asp?pg=pgDownload&pgType=pgWikiAttachment&ixAttachment=30247&sFileName=hoverTooltipComment.png)

**Comment by loucyx** [comment]
:+1:

**Comment by Trevinlc1997** [comment]
I just want to bump and say this would be really helpful as documenting code without Doxygen just feels awkward, to be honest. 

I'll have my friend learn the VSCode API just to try and implement something like requested ;)

**Comment by rainaby** [comment]
Do we have any updates on this?

**Comment by sean-mcmanus** [comment]
@rainaby No updates. We haven't done any work on this feature and it's not on our schedule yet.

**Comment by creikey** [comment]
Couldn't this be a simple extension?

**Comment by cschlosser** [comment]
> Couldn't this be a simple extension?

I tried and no it is not really. We're missing features from the language server. The Typescript server has the necessary information but the C/C++ one doesn't. If the information would be available it would be super eayy.

I'm really interested in this and the only way right now to do it would be to do some form of heuristic analysis on the source code (essentially reimplementing the whole Doxygen engine and keeping a seperate data base like intellisense) which is quite error prone.

**Comment by rainaby** [comment]
Is there a hack for now to get to work? Like using 2 different plugins to get it to work?

**Comment by rei-vilo** [comment]
I've given up Visual Studio Code because of the lack of customer focus and technical support.

**Comment by Tanja-4732** [comment]
+1

Please have it support _**syntax highlighting**_ inside of the Doxygen comments.
That'd be great.

:heart: VS ode

PS: Consider adding an extension-request-tag or something like that to this issue, in case you aren't interested in implementing this functionality natively.

**Comment by LeThiHyVong** [comment]
@Bernd-L I am using an alternative syntax parser ([Reloaded C/C++](https://marketplace.visualstudio.com/items?itemName=reloadedextensions.reloaded-cpp) with [Reloaded Themes](https://marketplace.visualstudio.com/items?itemName=reloadedextensions.reloaded-themes)), hope it usable.

**Comment by Tanja-4732** [comment]
@LeThiHyVong Yes, I've been using it too, however, it still lacks Doxygen-command auto-completion (=IntelliSense). Also, it can't display a popover-like bubble with the documentation of a method. (or something else).

 The functionality described above really needs to be implemented into the Microsoft C++ plugin.

**Comment by rewrking** [comment]
Bumping this. I noticed VS Code at least places the documentation comments into the info popup for a method (albeit unformatted it looks like). It would be really slick to see them formatted.

Also of note is that some documentation blocks are formatted like this:
```
////////////////////////////////////////////////////////////  
/// \brief Retrieve the color as a 32-bit unsigned integer  
/// \return Color represented as a 32-bit unsigned integer  
////////////////////////////////////////////////////////////
```
SFML uses this style for instance: https://github.com/SFML/SFML

VS Code doesn't parse this into the info popup at all it seems since it's not in a ```/** */``` block, however it seems to be one of the recommended styles in the doxygen manual, so maybe the extension could look for any comment block that has ```@keyword``` or ```\keyword``` above a declaration.
http://www.doxygen.nl/manual/docblocks.html

**Comment by Bernd-L** [comment]
Why is this issue both in February 2019 AND in Triage?

**Comment by mklemarczyk** [comment]
Is there any active branch for this feature to contribute to?

**Comment by sean-mcmanus** [comment]
No, it's in our closed source code. Stuff that could be contributed to in the TypeScript could be found in the list https://github.com/Microsoft/vscode-cpptools/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22 .

**Comment by BlueG** [comment]
I'm glad to see this is already in the pipeline. Although I generally prefer C# XML style documentation (not surprising since I work primarily in C#), as I begin working on C++ projects I am finding Doxygen in heavy usage everywhere. Having Intellisense recognize it will make my work much easier.

**Comment by w3lld0ne** [comment]
++ waiting for it (in visual studio as well)

**Comment by rfzeg** [comment]
+1 on this feature request

**Comment by jurf** [comment]
There are 25 people subscribed to this, please add a reaction to the top post instead of +1ing (and thus notifying everyone waiting for this). Cheers. :pray:

**Comment by ousugo** [comment]
happy to see the status change to "In Progess"

**Comment by zhouzq-thu** [comment]
Finally in progress. Can’t wait any longer.

**Comment by bobbrow** [comment]
Leaving it open, but in "fixed (release pending" state until we release it.

**Comment by michelleangela** [comment]
Example of Doxygen comments displayed on tooltip by the C/C++ extension:

![image](https://user-images.githubusercontent.com/38734287/85440089-890cae00-b542-11ea-9040-d85e17a4a117.png)
![image](https://user-images.githubusercontent.com/38734287/85440111-8ca03500-b542-11ea-918c-7a431693a278.png)

**Comment by michelleangela** [comment]
If you would like for the C/C++ extension to also generate stub Doxygen comments, please upvote the "Feature request - Doxygen stub generation" at https://github.com/microsoft/vscode-cpptools/issues/5683. Votes on features will help determine a feature's priority against other features or work items.

**Comment by sean-mcmanus** [comment]
Doxygen comment support in hover, signature help, and completion is available now with https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders .

**Comment by rewrking** [comment]
Works awesome so far! I'm now spending an evening documenting my code... any plan to add support for @tparam (template parameters) though?

**Comment by ben-edna** [comment]
Great! Minor detail, our code-base uses the Qt-Style exclamation mark [docblocks](https://www.doxygen.nl/manual/docblocks.html) (`/*!` instead of `/**`), and the exclamation mark is shown in the hover.

**Comment by ebinans** [comment]
Fantastic! Another small detail - documentation block after members show `/<`, `!<` or `<` depending on chosen syntax.
https://www.doxygen.nl/manual/docblocks.html#memberdoc

**Comment by michelleangela** [comment]
> Works awesome so far! I'm now spending an evening documenting my code... any plan to add support for @tparam (template parameters) though?

The work to support @tparam is in progress.

**Comment by michelleangela** [comment]
>Great! Minor detail, our code-base uses the Qt-Style exclamation mark docblocks (/*! instead of /**), and the exclamation mark is shown in the hover.

The work to support Qt-Style exclamation mark `/*!` is in progress.

**Comment by Boddlnagg** [comment]
We have configured Doxygen to use `\par` instead of `\param`, can that somehow also be supported (probably through some setting?).
Also, for some reason we put our Doxygen comments in between the function signature and the opening `{`. Doxygen parses that just fine ... will that work here as well?

**Comment by michelleangela** [comment]
> We have configured Doxygen to use `\par` instead of `\param`, can that somehow also be supported (probably through some setting?).
> Also, for some reason we put our Doxygen comments in between the function signature and the opening `{`. Doxygen parses that just fine ... will that work here as well?

@Boddlnagg , I created a new issue for your feature request at #5700

**Comment by michelleangela** [comment]
> Fantastic! Another small detail - documentation block after members show `/<`, `!<` or `<` depending on chosen syntax.
> https://www.doxygen.nl/manual/docblocks.html#memberdoc

@ebinans , I created a new issue for your feature request at #5701

**Comment by jhortenstine** [comment]
Is it possible to leave the commands that are not being converted? We use \note, \pre, and \post. The current behavior is that they don't show up in the tool tip at all.

**Comment by ben-edna** [comment]
We sometimes use the [`\copydoc`](https://www.doxygen.nl/manual/commands.html#cmdcopydoc) to not duplicate documentation when it is not needed. It would be great if the documentation of the mentioned symbol would be used for the tooltip.

**Comment by carlolars** [comment]
Looks great! Just one little detail.

We trim trailing whitespace in our source files, so if a doxy-comment is split in two lines then there is no space between the last word on the first line and the first word on the second line.
```
/**
 * Comment in
 * correct format
 */
```
becomes `Comment incorrect format` instead of `Comment in correct format`.

**Comment by sean-mcmanus** [comment]
@carlolars What's the repro for that space issue? I'm not reproing it.

![image](https://user-images.githubusercontent.com/19859882/86643549-a7869680-bf91-11ea-99cc-c6a4b5614f00.png)

**Comment by carlolars** [comment]
> 
> 
> @carlolars What's the repro for that space issue? I'm not reproing it.

It happens for functions if it has `@return` and/or `@param`, the examples below are failing for me. 
```
/**
 * Comment in
 * correct format.
 *
 * @param arg1
 * @return int
 */
int func1(int arg1)
{
    return arg1;
}

/**
 * Comment in
 * correct format.
 *
 * @return int
 */
int func2(void)
{
    return 2;
}

/**
 * Comment in
 * correct format.
 *
 * @param arg1
 */
void func3(int arg1)
{
    (void)arg1;
}
```

**Comment by michelleangela** [comment]
@carlolars @sean-mcmanus 
I was able to repro the issue on Visual Studio. 
![image](https://user-images.githubusercontent.com/38734287/86841292-9e143180-c058-11ea-89a9-6808c57d62cc.png)


Edit:
I created a new issue #5741 for this and filed an issue on Visual Studio.

**Comment by magdumnikhil** [comment]
Only doxygen comments above function definition are parsed and shown over tooltip. Comments above function declaration are ignored.

Is there any setting which decides this?
