### ISSUE TITLE
IntelliSense update seemingly stuck in an endless loop

### ISSUE THREAD

**Issue by voidtrance** [microsoft/vscode-cpptools#6581]
Hi,

I am filing this as a general question as I am not sure if it is an actual issue.

I am working on a rather large project with large number of files (c/c++). For my settings, I've tried to limit the "includePath" and "browser.path" directories as much as I can. However, after starting VSCode and opening the workspace, the IntelliSense engine starts updating but seems to never finish.

I am working with VSCode Remote on a Window client and Linux server. VSCode version 1.5.1.1, cpptools version 1.1.2, c++ intellisense version 0.2.2.

I see the _cpptools_ process is taking 100% of one of the CPUs on the Linux server machine with 4 _cpptools-srv_ child processes. Attaching strace to the _cpptools_ process shows that is contantly reading from its standard input:

```
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n", 4096) = 22
read(0, "{\"jsonrpc\":\"2.0\",\"method\":\"cppto"..., 4096) = 53
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n", 4096) = 22
read(0, "{\"jsonrpc\":\"2.0\",\"method\":\"cppto"..., 4096) = 53
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n{\"jsonrpc\""..., 4096) = 75
futex(0x7ffd67c09610, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n", 4096) = 22
read(0, "{\"jsonrpc\":\"2.0\",\"method\":\"cppto"..., 4096) = 53
futex(0x7ffd67c09614, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "Content-Length: 53\r\n\r\n", 4096) = 22
read(0, "{\"jsonrpc\":\"2.0\",\"method\":\"cppto"..., 4096) = 53
```

_cpptools_' parent process is _.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node ${HOME}/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/bootstrap-fork --type=extensionHost --uriTransformerPath=${HOME}/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/uriTransformer.js_.

Using strace on the _bootstrap-fork_ process shows that it's writing content to file descriptor 33 with content matching what _cpptools_ is reading. However, the writes are happing pretty slowly.

```
epoll_wait(14, [], 1024, 318)           = 0
getpid()                                = 1716776
kill(1557751, 0)                        = 0
epoll_wait(14, [], 1024, 171)           = 0
epoll_wait(14, [{EPOLLIN, {u32=19, u64=19}}], 1024, 828) = 1
read(19, "\4\0\0\0\0\0\0\0\0\0\0\0\0", 65536) = 13
epoll_wait(14, [], 1024, 786)           = 0
getpid()                                = 1716776
kill(1557751, 0)                        = 0
epoll_wait(14, [], 1024, 704)           = 0
write(33, "Content-Length: 53\r\n\r\n", 22) = 22
write(33, "{\"jsonrpc\":\"2.0\",\"method\":\"cppto"..., 53) = 53
futex(0x29fd588, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x29fd520, FUTEX_WAKE_PRIVATE, 1) = 1
epoll_wait(14, [{EPOLLIN, {u32=17, u64=17}}], 1024, 295) = 1
read(17, "\1\0\0\0\0\0\0\0", 1024)      = 8
epoll_wait(14, [], 1024, 294)           = 0
getpid()                                = 1716776
kill(1557751, 0)                        = 0
epoll_wait(14, [], 1024, 1000)          = 0
getpid()                                = 1716776
kill(1557751, 0)                        = 0
epoll_wait(14, [], 1024, 155)           = 0
epoll_wait(14, [], 1024, 0)             = 0
write(19, "\4\0\0\0\0\0\0\0\0\0\0\0\0", 13) = 13
epoll_ctl(14, EPOLL_CTL_MOD, 19, {EPOLLIN, {u32=19, u64=19}}) = 0
epoll_wait(14, [], 1024, 844)           = 0
getpid()                                = 1716776
kill(1557751, 0)                        = 0
epoll_wait(14, [], 1024, 202)           = 0
write(33, "Content-Length: 53\r\n\r\n", 22) = 22
write(33, "{\"jsonrpc\":\"2.0\",\"method\":\"cppto"..., 53) = 53
futex(0x29fd58c, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x29fd520, FUTEX_WAKE_PRIVATE, 1) = 1
```

Unfortunately, I don't know how to provide steps for reproduction since I expect it is highly dependent on the project that I am working on. If there is any information that I can provide, please let me know.

**Comment by Colengms** [comment]
Hi @voidtrance .  The native component of the extension (the cpptools process) uses standard input/output to communicate with the TypeScript component.  So, it would be expected that you'd seen this communication channel in use almost constantly when not idle.

Regarding the update that never finishes; could you set `"C_Cpp.loggingLevel": "Debug"` and check the C/C++ Output channel for activity at that time?  That might provide some clues as to what it's parsing, in case it's getting stuck on a particular file or processing files in locations it should not be.

**Comment by boocs** [comment]
I've noticed this tag parser behavior too when testing my extension. It's would be very hard to find something to replicate it though since it seems random.

Sometimes clicking on the tag parser cylinder icon and pausing the Tag Parser and then resuming will fix it but sometimes it won't let you pause it at all. 

Sometimes waiting for ~5-10 minutes and it will start up again by itself and finish the tag parsing.

I haven't noticed any problems when looking at the debug logging level.

**Comment by voidtrance** [comment]
> Hi @voidtrance . The native component of the extension (the cpptools process) uses standard input/output to communicate with the TypeScript component. So, it would be expected that you'd seen this communication channel in use almost constantly when not idle.
> 
> Regarding the update that never finishes; could you set `"C_Cpp.loggingLevel": "Debug"` and check the C/C++ Output channel for activity at that time? That might provide some clues as to what it's parsing, in case it's getting stuck on a particular file or processing files in locations it should not be.

I've done what you asked and the last few lines of the output are:
```
...
completionItem/resolve (id: 4297)
cpptools/getDocumentSymbols
cpptools/getDocumentSymbols
cpptools/getDocumentSymbols
cpptools/getDocumentSymbols
cpptools/getDocumentSymbols
```

There is no additional output.

I've also see long delays when saving a document. When this happens, I get a pop-up notification saying that the code formatting is happening. No output is appearing in the Output window. I also checked the process table during one of those delayed saves, expecting to see clang-format running but it wasn't:

```
user 3299801  0.0  0.0 216652  2876 ?        S     2020   0:00 sh /home/user/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shut
user 3299812  0.2  0.1 1855840 62668 ?       Sl    2020  27:32  \_ /home/user/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node /home/user/.vscode-server/bin/ea3859d4ba2f3e577a159bc91
user 3300323  0.0  0.0 885584  7960 ?        Sl    2020   0:10      \_ /home/user/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node /home/user/.vscode-server/bin/ea3859d4ba2f3e577a159
user 3300616  2.2  0.5 1669384 168384 ?      Sl    2020 226:23      \_ /home/user/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node /home/user/.vscode-server/bin/ea3859d4ba2f3e577a159
user 3302310 18.7  1.9 2799156 622832 ?      Sl    2020 1874:54      |   \_ /home/user/.vscode-server/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools
user 3303720  0.0  0.2 5178404 85912 ?       Sl    2020   0:30      |   |   \_ /home/user/.vscode-server/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools-srv 3302310 0
user 3303808  0.0  1.1 5312532 389860 ?      Sl    2020   2:21      |   |   \_ /home/user/.vscode-server/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools-srv 3302310 1
user 1167797  0.0  0.2 5178836 91316 ?       Sl   Jan04   0:08      |   |   \_ /home/user/.vscode-server/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools-srv 3302310 2
user 1886938  0.0  0.2 5176060 77568 ?       Sl   08:09   0:00      |   |   \_ /home/user/.vscode-server/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools-srv 3302310 5
```

Eventually, the pop-up disappears and a bunch of output related to code formatting appears in the Output window.

**Comment by sean-mcmanus** [comment]
We did have an infinite loop a long time ago with getDocumentSymbols -- can you attach a debugger to cpptools and get a call stack that looks like it's doing work? (ignoring the bunch of threads that are idle). https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

getDocumentSymbols only runs when a file is open -- does cpptools get stuck using CPU when no file is opened?

**Comment by voidtrance** [comment]
> We did have an infinite loop a long time ago with getDocumentSymbols -- can you attach a debugger to cpptools and get a call stack that looks like it's doing work? (ignoring the bunch of threads that are idle). https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv
> 
> getDocumentSymbols only runs when a file is open -- does cpptools get stuck using CPU when no file is opened?

Not that I have noticed. The only times that I've seen it stuck is when tag parser (I think, the little flame icon is present on the bottom right) is working and when saving files and running them through the code formatter.

**Comment by boocs** [comment]
@voidtrance 

Are you working with multiple workspaces? Try the empty array method of setting up the Tag Parser. You can see the results I got with a Unreal Engine 4.26 project: [My q&a post](https://github.com/microsoft/vscode-cpptools/discussions/6801)

You basically put all browse paths in the main workspace and an empty array with all other workspaces. You can specify an empty array in c_cpp_properties.json like so:

```
            ,
            "browse": {
                "path": []
            },
```

**Comment by sean-mcmanus** [comment]
Putting all the browse.paths in one workspace folder is not supposed to have an effect on performance unless the "main" folder has additional files.exclude set.
