### ISSUE TITLE
It's always "Activating Extensions..."

### ISSUE THREAD

**Issue by ThinBuffalo** [microsoft/vscode-cpptools#6585]
Type: Debugger

**Describe the bug**
- OS and Version:Windows 7 x64
- VS Code Version:1.51.1
- C/C++ Extension Version:v1.1.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
When I use any command for this extension, you are prompted: "Activating Extensions..." and nothing happens.
And sometimes when vscode is started, an error is reported in the output: "Connection to server got closed. Server will not be restarted."
**
**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment]
It sounds like cpptools.exe is crashing.

Win7 is at it's end of life: https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information

@bobbrow Do we still support Win7?

**Comment by ThinBuffalo** [comment]
I can use it on another computer with the same configuration, but not this one.

**Comment by sean-mcmanus** [comment]
You mean on another Win7 machine? Do you know what is special about the computer that it doesn't work on?

Are you able to somehow get a crash dump for the cpptools.exe process?

**Comment by Colengms** [comment]
I have a Win7 machine set up for testing, but am not repro'ing any obvious issue.  @ThinBuffalo Is there more you can tell us about the configuration of the machine that repros?

**Comment by bobbrow** [comment]
> Win7 is at it's end of life: https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information
> 
> @bobbrow Do we still support Win7?

We have enough users still on Win7 that we would investigate a major blocking issue were it to arise, but that hasn't been the case yet.

**Comment by sean-mcmanus** [comment]
@ThinBuffalo You might want to make sure your Win7 machine is patched to the latest available updates: Service Pack 1 with March 19, 2019 or later update rollup (6.1.7601.24499) .
