### ISSUE TITLE
Unused variables are not highlighted in the editor

### ISSUE THREAD

**Issue by dortamiguel** [microsoft/vscode-cpptools#6588]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macos 10.15.6
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.2
- Description of what the bug is: When a variable is unused the editor doesn't warn that is unused.

**Steps to reproduce**
Create a variable a don't use it

**Expected behavior**
When I create a variable I will expect vscode to highlight the line with a warning to tell me that is unused

**Comment by sean-mcmanus** [comment]
Is this a request for when building or for IntelliSense squiggles?

1.0.2 has a bug that can cause warnings to not appear for `cppbuild` build tasks (https://github.com/microsoft/vscode-cpptools/issues/6556) that should be fixed with our pending 1.2.0-insiders. See
![image](https://user-images.githubusercontent.com/19859882/100676878-a67a4b00-331e-11eb-83bd-54c1636ad1c8.png)

Is that sufficient? If you're requesting IntelliSense warnings that's being tracked by https://github.com/microsoft/vscode-cpptools/issues/828 .

**Comment by ellipticaldoor** [comment]
Yes, I will like to have the behaviour that show on the screenshot, but its seems is not working on my editor.

**Comment by sean-mcmanus** [comment]
We need more info. Are you using 1.1.3? Are you building with gcc? Do you see the warning in your termainl output?

**Comment by ellipticaldoor** [comment]
Yes, I'm on latest 1.1.3. I'm compiling with clang and the warning appears on the terminal

![Screenshot 2020-12-14 at 21 40 11](https://user-images.githubusercontent.com/3449006/102138902-ff84cb80-3e54-11eb-837a-ebc13af84ef5.JPG)

**Comment by sean-mcmanus** [comment]
What is your tasks.json? You need to use the gcc problem matcher, e.g.
```
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: clang++-10 build active file",
            "command": "/usr/bin/clang++-10",
            "args": [
                "-g",
                "-Wall",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

**Comment by ellipticaldoor** [comment]
Is it possible to make this settings global? I don't have a tasks.json

I just use the terminal to compile

**Comment by sean-mcmanus** [comment]
It's not possible. The problem matchers are associated with tasks. You'd have to make a feature request on VS Code: https://github.com/microsoft/vscode/issues

**Comment by ellipticaldoor** [comment]
Oh I see! Thanks for your help
