### ISSUE TITLE
Architecture arm64 is not supported.

### ISSUE THREAD

**Issue by tkreindler** [microsoft/vscode-cpptools#6589]
Type: General

Now that Visual Studio Code - Exploration pretty much fully supports Apple Silicon, is there an open issue for porting this extension over? Not to oversimplify matters but it seems like a pretty trivial port.

**Describe the bug**
- OS and Version: Mac OS Big Sur, arm64
- VS Code Version: Exploration - Latest Version

**Comment by xymeng16** [comment]
Clone this repo into your Mac and modify the activate(context: vscode.ExtensionContext) function at line 36 in extension/main.ts by adding one condition in the following if expression as:
```Typescript
if (
        arch !== 'x64' 
        && 
        
    (process.platform !== 'win32' || (arch !== 'ia32' && arch !== 'arm64')) 
    && 
    (process.platform !== 'darwin' || arch !== 'arm64') // add this condition
    &&
    (process.platform !== 'linux' || (arch !== 'x64' && arch !== 'arm' && arch !== 'arm64'))
    )
```
Then build it and export an VSIX extension file to install it. I am using this modified version for 3 days on my C++ development without any bug of this extension.

**Comment by michelleangela** [comment]
This feature request requires changing our closed source code.

Duplicating this to https://github.com/microsoft/vscode-cpptools/issues/6595
