### ISSUE TITLE
ClangFormat ignores .clang-format file when fallback style is "Visual Studio"

### ISSUE THREAD

**Issue by barsan-md** [microsoft/vscode-cpptools#659]
I have Linux Mint 18.1 with kernel 4.10.12-041012-generic #201704210512.
I created a test .clang-format containing a large indentation (so change is visible)

    BasedOnStyle: Mozilla
    IndentWidth: 20

If in the configuration json I have
`"C_Cpp.clang_format_fallbackStyle": "Visual Studio"`
or removed and leaved default ("Visual Studio"), the format rules are not applied.
With any other fallback style (Google, LLVM, ...), the file is detected and rules applied. This seems a bug.

**Comment by sean-mcmanus** [comment]
It's https://github.com/Microsoft/vscode-cpptools/issues/604 . Our code that looks for .clang-format files when the Visual Studio style is used doesn't work on Linux (it's buggy). Hopefully the fix will make it into 0.11.1.
