### ISSUE TITLE
no space when two >  are used consecutively. 

### ISSUE THREAD

**Issue by arpitgupta1214** [microsoft/vscode-cpptools#6590]
Issue Type: <b>Bug</b>

declare a 2-D vector
vector<vector<int> >
and save the file.
The formatter changes it to:
vector<vector<int>> (removing the space in > >)
This leads to a compilation error in g++.

Extension version: 1.1.2
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 8333606b-65db-4560-9088-41bcc039ea85|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Colengms** [comment]
Hi @arpitgupta1214 .  What is your `cppStandard` version, and which formatting engine are you using?  If using clang-format (default), it should correctly either add or remove spaces between angle-brackets, based on your `cppStandard`.  Support to disambiguate template angle-brackets from `<<` and `>>` operators was added in C++11.    A value of `c++03` or `c++98` should result in adding/preserving those space when formatting.  Can you also confirm what C++ standard version is being used by g++ when compiling?

**Comment by arpitgupta1214** [comment]
I am using c++11 standard and the microsoft c++ tools for formatting.

**Comment by Colengms** [comment]
Hi @arpitgupta1214 .  Could you provide the contents of or `c_cpp_properties.json` and any other relevant `C_Cpp` settings in your settings.json files?

**Comment by arpitgupta1214** [comment]
c_cpp_properties.json :
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${default}"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "gnu17",
            "cppStandard": "c++20",
            "intelliSenseMode": "${default}"
        }
    ],
    "version": 4
} 
```
settings.json:
```
 "C_Cpp.default.includePath": [
    "/Library/Developer/CommandLineTools/usr/include/c++/v1"
  ]
```

**Comment by Colengms** [comment]
Hi @arpitgupta1214 .  Your configuration indicates `"cppStandard": "c++20"`.  C++20 allows the space to be removed from between those angle-brackets.  It sounds like perhaps you are not also passing `-std=c++20` (or `-std=gnu++20`) when you compile, leading to the compilation error.  To ensure IntelliSense (and formatting) are aligned with how you are configuring the compiler when compiling, `cppStandard` should be set to the same value passed to the compiler.  Or, you could remove the `cppStandard` field, and the extension should query the compiler for its default.
