### ISSUE TITLE
How do I use compile_commands.json

### ISSUE THREAD

**Issue by AverageComet250** [microsoft/vscode-cpptools#6592]
So I've been looking into ultralight and uses the below to build a project

```
mkdir build
cd build
cmake ..
cmake --build . --config Release
```

I'm not fully sure what vscode does to build projects (and whether its this plugin or the cmake one that I need to change the settings for), but I know it isn't this. It seems I need a `compile_commands.json` file that I tell this plugin to use at the project level but I cant find documentation on this or anything showing the file format. I would appreciate it if someone could tell me how to use this file.

**Comment by michelleangela** [comment]
For the C++ Extension to use the compile_commands.json file, place its full file path into the [c_cpp_properties.json](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference) file. This file is used to configure the C++ Extension IntelliSense. You can edit the file by running one of the two commands: `C/C++: Edit Configurations (JSON)` or `C/C++: Edit Configurations (UI)`. If you are using the UI settings, the input field for  compile_commands.json is under "Advanced Settings".

**Comment by AverageComet250** [comment]
I know that but what do I actually put in the `compile_commands.json` file

**Comment by michelleangela** [comment]
> I know that but what do I actually put in the `compile_commands.json` file

The compile_commands.json file is generated by CMake and it is not usually modified for the C++ Extension to use, unless there is some special case or workaround that needs to be done. https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html

**Comment by Colengms** [comment]
@AverageComet250 The format specifications for `compile_commands.json` can be found here: https://clang.llvm.org/docs/JSONCompilationDatabase.html

It would be possible to manually compose `compile_commands.json`.  Though, unless individual files need to be configured differently, it would seem simpler to specify the same information in `c_cpp_properties.json`.  Support for `compile_commands.json` is generally used to easily configure the extension if this file already exists as part of your build system.

**Comment by bobbrow** [comment]
If you are using CMake, then we recommend you install the [CMake Tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools) extension.  If you let that extension configure your project, you will not need compile_commands.json.  If you have any trouble configuring it, [open an issue here](https://github.com/microsoft/vscode-cmake-tools/issues/new) and we can help you out.

**Comment by AverageComet250** [comment]
I want to make it so that the build option runs 

```
cmake .
cmake --build . --config Release
```

Instead of 

`cmake .` or whatever the build button underneath the terminal or file does

Also I am using the cmake tools extension and my objective is to change what the build button on the bar at the bottom does

**Comment by Colengms** [comment]
Hi @AverageComet250 .  With CMake Tools installed, you should see a text button at the bottom of the window that allows selection of build configuration type (Release, Debug, RelWithDebInfo, MinSizeRel), . Alternatively, you can use `CMake: Select Variant` command.  With both a variant and a 'kit' selected, and a valid CMakeLists.txt file, run the `CMake: Configure` command to generate the build script.  Then you should then be able to build your project using the `CMake: Build` command.

It sounds like you want to leverage a multi-config build, based on the command line you specified above (which passes in the variant at build time).  Depending on the kit you've selected, CMake may or may not generate a 'multi-config' build.  I don't believe CMake Tools exposes this (as some generators do not support multi-config).  However, you can use `CMake: Configure` then `CMake: Build` to build based on whatever config is currently selected in the UI.

`compile_commands.json` should not contain invocation of CMake.  Some CMake generators support creating a `compile_commands.json` when CMAKE_EXPORT_COMPILE_COMMANDS is specified.

**Comment by AverageComet250** [comment]
I think my variant is Release and I'm using the x86_64 visual studio 2019 kit. I will test the cmake configure command and come back on whether that works.

Thanks

**Comment by Colengms** [comment]
@AverageComet250 .  Did my last response help you get this working?  Or, if not, was there some part that did not work as described?

**Comment by AverageComet250** [comment]
Sorry I'm still yet to do a proper test, though I can confirm that my variant is Debug and my kit is as specified in earlier post.

I'll come back after a proper test.

I closed it by accident by the way which is why I reopened it

**Comment by AverageComet250** [comment]
I'm gonna close this as I haven't actually tested it yet and I don't think I'm ever gonna need this. If someone could tell me how to modify what the build button does though, I'd really appreciate it

**Comment by sean-mcmanus** [comment]
@AverageComet250 What build button?

**Comment by AverageComet250** [comment]
The one on the bar at the bottom, the one where you can select things like the python interpreter and other things
