### ISSUE TITLE
Huge .cache folder (4.8G) - ipch

### ISSUE THREAD

**Issue by aghArdeshir** [microsoft/vscode-cpptools#6594]
Type: General

- OS and Version: Ubuntu 20.10
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.2
- Other extensions you installed: Remote Development Collection, VSIntellicode, GitLens, ESLint, Prettier, LiveServer 
- A clear and concise description of what the bug is.

**Additional context**

VSCode is installed using snap

**Comment by michelleangela** [comment]
This cache folder stores cached precompiled headers or "ipch" files that the IntelliSense engine uses to improve performance. You can limit the size of the cache by changing the setting value of `C_Cpp.intelliSenseCacheSize`

![image](https://user-images.githubusercontent.com/38734287/100649962-10cbc500-32f8-11eb-9664-b637d7e10d00.png)

**Comment by aghArdeshir** [comment]
Thanks! Well, I think my problem is solved, but I still think its strange to have ~5GB of cache data, for a single project. But I don't know the internals. 

Thanks @michelleangela 

Should I close the issue?

**Comment by michelleangela** [comment]
I forgot to mention that the cache under the default path is the total of all workspace that have cached precompiled headers. That is if the same path is used for all workspace, then the cache of all workspace will be stored under the same path, unless user specifies a different cache path per workspace.

![image](https://user-images.githubusercontent.com/38734287/100785822-11329180-33c6-11eb-869b-31da6b3fab6e.png)

I'll close the issue as resovled.
