### ISSUE TITLE
Support Apple Silicon ARM64 architecture natively

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6595]
VS Code now works on Apple Silicon (https://github.com/microsoft/vscode/issues/101662).

This is a feature request to enable the language server binaries to also run on Apple Silicon natively.

The feature request to have the debugger binaries run on Apple Silicon natively is tracked by https://github.com/microsoft/vscode-cpptools/issues/7035.

**Note:** the cpptools, cpptools-srv, and debugger binaries built for macOS x64 may work on Apple Silicon's x64 emulator, however this may use more resources than having binaries run natively as ARM64 on Apple Silicon.

**Comment by sean-mcmanus** [comment]
I think we'll need Azure support for Big Sur first: https://github.com/actions/virtual-environments/issues/2072 ... unless we can get a "hosted" Big Sur machine added (I don't see one currently).

**Comment by michelleangela** [comment]
This now available on our 1.3.0-insiders4 version as VSIX package **cpptools-osx-arm64.vsix** from
 https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders4

**Comment by FischLu** [comment]
> This is now available on our 1.3.0-insiders4 version as VSIX package **cpptools-osx-arm64.vsix** from
> https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders4

hello, I have tried this version, but still cannot debug any cpp code, the error message is "ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (attach failed ((os/kern) invalid argument))"

**Comment by bobbrow** [comment]
Thank you for trying out the insiders build!  We are tracking support for IntelliSense and the debugger separately.  The work for native debugger support on Apple Silicon is #7035 and has not been completed yet.

**Comment by michelleangela** [comment]
This is now available in the 1.3.0 release version https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0
