### ISSUE TITLE
Outline grouping is incorrect with anonymous typedefs

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6597]
Repro is
```
typedef struct // test
{
    int ii;
    int jj;
} test_t;
```
in a .c file and view the Outline view.

Uncomment the `// test` to get the expected behavior.

Originally reported as a sub-issue of https://github.com/microsoft/vscode-cpptools/issues/5877

**Comment by huye** [comment]
If the problem is not solved, you can hide them or set them to the default collapsed state. Do not interfere with our quick jump from the outline to the code.

**Comment by Colengms** [comment]
This appears to have been addressed in 1.3.0.  Closing as fixed.
