### ISSUE TITLE
no required output only 

### ISSUE THREAD

**Issue by aneel56** [microsoft/vscode-cpptools#6598]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Windows 10\Documents\c c++> cd "c:\Users\Windows 10\Documents\c c++\program.cpp\" ; if ($?) { g++ hello.cpp -o hello } ; if ($?) { .\hello }
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../libmingw32.a(main.o):(.text.startup+0xc0): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
PS C:\Users\Windows 10\Documents\c c++\program.cpp>

**Comment by sean-mcmanus** [comment]
Does program.cpp define a main function? The linker error indicates main is missing.

**Comment by aneel56** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Windows 10\Documents\c c++> cd "c:\Users\Windows 10\Documents\c c++\program.cpp" ; if ($?) { g++ hello.cpp -o hello } ; if ($?) { .\hello }
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../libmingw32.a(main.o):(.text.startup+0xc0): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
PS C:\Users\Windows 10\Documents\c c++\program.cpp>




HOW CAN I SOLVE THIS PROBLEM ?HELP

**Comment by sean-mcmanus** [comment]
Did you see my comment: https://github.com/microsoft/vscode-cpptools/issues/6598#issuecomment-736727962 ?

**Comment by aneel56** [comment]
What more info is required ?

**Comment by sean-mcmanus** [comment]
Did you try defining adding

```
int main()
{
return 0;
}
```

**Comment by aneel56** [comment]
Yeah, but it is not working either
Can you tell me how to install vscode without download mingw for c++?
I am new to vscode and coding !!

**Comment by sean-mcmanus** [comment]
We have some docs at https://code.visualstudio.com/docs/cpp/config-mingw .
