### ISSUE TITLE
Support Visual Studio's 'Concord' debug engine in windows?

### ISSUE THREAD

**Issue by TurkeyMan** [microsoft/vscode-cpptools#66]
Please support Visual Studio's Concord debug engine? Using GDB to debug local windows apps is pretty awkward. I think everyone agrees; Visual Studio has the best debugger in the world, and it's available to everyone via the free community edition.

**Comment by delmyers** [comment]
@TurkeyMan is this different from #65?

**Comment by TurkeyMan** [comment]
Concord is the VS debugger, and isn't available as an independent software bundle. It's only useful to people who are also VS users. I suspect a lot of people use code because they don't have VS?
Concord is probably the best C++ debugger that exists on any platform anywhere, and as such it would be nice to be able to use it in code if available.

**Comment by delmyers** [comment]
@TurkeyMan fixed.

**Comment by TurkeyMan** [comment]
Awesome work guys!
