### ISSUE TITLE
VS Code uses non-stop CPU and memory after the cpptools process is killed

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6603]
Reproed on Windows with VS Code and VS Code Insiders, 1.1.2 and 1.2.0-insiders.

**Comment by sean-mcmanus** [comment]
It's stuck in an infinite "loop" involving: `                        allClients.forEach(client => { allClients.replace(client, true); });`.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.3

**Comment by BillDenton** [comment]
Still using a core per editor instance in 1.1.3.

**Comment by sean-mcmanus** [comment]
@BillDenton This bug was not with cpptools/cpptools-srv using CPU/memory, but with VS Code itself (the extension host  process where our TypeScript runs). It was caused by an infinite processing when cpptools crashed, see the fix at https://github.com/microsoft/vscode-cpptools/pull/6604 . I believe you're referring to a different issue.

**Comment by mojomojo52** [comment]
I'm getting this bug after the 1.1.3 bug fix. Didn't have this before.
