### ISSUE TITLE
Failure to select a debug configuration results in 'unknown error'

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#6608]
Using `create a launch.json file`, after selecting an 'Environment', if I click away from the 'build configuration' menu to dismiss it, I get an error, "An unknown error occured.  Please consult the log for more details".

In this case, the user is cancelling the operation, and we probably shouldn't display an 'unknown error' message.

**Comment by sean-mcmanus** [comment]
Yeah, this is a known issue -- I didn't see a way to fix it. Did anyone have any idea what we're doing wrong to avoid that?

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
