### ISSUE TITLE
Microsoft Visual Debugging and Run Error - Projects, also.

### ISSUE THREAD

**Issue by ejoia** [microsoft/vscode-cpptools#6612]
Please bare with me as I am jsut beginning on my journey of Software Design.  My visual code automatically creates a "setting.json" file after I attempt to debug and run my .cpp file.  I just want to run the program and see if it is a functional program, while using an user interface to integrate input(s) when I run the programs.  How do I configure my program to do these things? These are the C++ Environments offered to me when I click Debug and Run: GDB/LLDB and Windows.

How do I configure the project and repository features, so that I may proceed with creating projects in lieu of have to all all programs on the screen.  I know that I could just create a file on my hard drive but learning these features is what it is all about....

Open to short tutorial videos and short articles, momentarily.  I'm doing a lot of work.

**Comment by WardenGnaw** [comment]
For documentation about using Microsoft Visual C++ with the VS Code C++ Extension you see the debugging section of the  ["Hello World" example](https://code.visualstudio.com/docs/cpp/config-msvc#_debug-helloworldcpp). This will tell you to use the "Windows" configuration for the debugger. 
If you are looking to pass arguments to your program, you can this to the `"args": []` in the generated `launch.json`.

Configuration for intellisense will be available if you open your project folder in the Visual Studio Developer Command Prompt.

Let us know if this helped with your questions or if you have any more.

**Comment by ejoia** [comment]
I just want to run the program, momentarily, and am not trying to program the debugger.  I'm going to look through this but my vs code won't just run my program with a user interface.

**Comment by WardenGnaw** [comment]
At the moment, we do not support "Run without Debugging" for both cppdbg and cppvsdbg debuggers.
