### ISSUE TITLE
[Feature Request] Add an option to choose if comments are automatically folded

### ISSUE THREAD

**Issue by mundodisco8** [microsoft/vscode-cpptools#6615]
**Type: LanguageService**

**Describe the Issue**
- OS and Version: Windows 10 20H2
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.2

When I fold my code with "Fold All" or "Fold Level X", my comments are folded too.  I use decorated comment blocks to separate areas of my code thematically, and I like to keep the details of a function visible even if the code is collapsed. The current behaviour of folding comments clashes a bit with my workflow, as I have to unfold a bunch of areas after the autofold. Also, I use VS Code to edit files that I might also change at some point on the IDE provided by my manufacturer. These external changes sometimes trigger a general code unfold, so I have to frequently autofold my code.

I see how some users would like the current behaviour to be kept (or even be the default), so that's why I suggest that this behaviour could be controlled by a flag in the settings. It could be a flag that affects only autofolding, while keeping comments foldable by clicking on the downward pointing arrow thingy.

I think that the C/C++ extension now controls folding for C/C++ files. If that's not the case I can move the request to the VS Code repo.

**Steps to reproduce**

1. Write a multiline comment
2. Autofold all the file or its level
3.The comment is automatically collapsed.

![Folding](https://user-images.githubusercontent.com/8402707/101017801-791ddf00-3562-11eb-8e59-7563373fc3af.gif)

**Expected behavior**

1. With the new flag set to "don't autofold comments", all code is folded, but comments are not

![image](https://user-images.githubusercontent.com/8402707/101017458-09a7ef80-3562-11eb-96b9-1cb6e33a1c0d.png)

**Comment by Colengms** [comment]
Hi @mundodisco8 .  The C/C++ extension provides folding ranges to VS Code, but I don't believe there is currently a way for it to 'control' them.

Included in the information provided to VS Code by the extension is a range 'type', including a `FoldingRangeKind.Comment` type.  It would seem that VS Code would have sufficient information to provide the feature you are requesting.  Addressing this in VS Code, rather than in the extension, could potentially benefit other languages as well.  Would you like to open a new feature request in the VS Code repo to track this?

**Comment by mundodisco8** [comment]
Thanks for your reply. I wasn't aware of what "provide folding" to VS Code. I'll open a request on their side. The issue, in case someone stumbles upon this, is this one https://github.com/microsoft/vscode/issues/111876

**Comment by Colengms** [comment]
Great.  I'll close this one, as there shouldn't be any additional work needed in the C/C++ extension to support this.
