### ISSUE TITLE
Cpptools-srv crashed when Offering completion if exist structure initializing code.

### ISSUE THREAD

**Issue by HuskyLens** [microsoft/vscode-cpptools#6624]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS 10.15.7
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Cpptools-srv crashs when Offering completion if exist structure initializing code.
Main.cpp like this:
```
#include <cstdint> 
typedef union
{
    struct
    {
        uint16_t blue : 5;
        uint16_t green : 6;
        uint16_t red : 5;
    } ch;
    uint16_t full;
} lv_color_t;

int main(void)
{
    lv_color_t test = ((lv_color_t){{225 >> 3, 225 >> 2, 225 >> 3}});
}
```

**Steps to reproduce**

1. Open C/C++ debug mode
2. Click on main.cpp
3. Type `uint16_t` in main function, auto complete could not work.
4. `Cpptools-srv` no longer exists in Activity Monitor.
5. Comment `lv_color_t test = ((lv_color_t){{225 >> 3, 225 >> 2, 225 >> 3}});` and restart VSCode.
6. Type `uint16_t` in main function again, auto complete can work now.

**Expected behavior**

auto_complete should work and auto complete the uint16_t

See error in Output:
<details>
  <summary><strong>Logs</strong></summary>

```
auto_complete::handle_completion: file:///Users/***/Desktop/Test/main.cpp (16:6)
Offering completion
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
Failed to read response from server: 8
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/52154022/101135836-56192b00-3647-11eb-9704-c5ebed2f50ba.png)

**Additional context**

c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/System/Library/Frameworks",
                "/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @HuskyLens .  Thanks for reporting this.  I can repro the issue.  Fortunately, with the latest code in development, this appears to have been fixed.  This should be resolved when we release version 1.2.

**Comment by sean-mcmanus** [comment]
@Colenms I'm still seeing this crash with 1.2.0-insiders.

**Comment by Colengms** [comment]
> @Colenms I'm still seeing this crash with 1.2.0-insiders.

I think your recent FI may have included the fix.  I do not repro with latest code.

**Comment by sean-mcmanus** [comment]
Ah, okay...I haven't checked the most recent bits yet.

**Comment by sean-mcmanus** [comment]
Yeah, you're right.

**Comment by HuskyLens** [comment]
Awesome! Waiting for the update.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
