### ISSUE TITLE
v1.1.3 fails to load on VS code and prompts to install from website.

### ISSUE THREAD

**Issue by brianq-ti** [microsoft/vscode-cpptools#6626]
v1.1.3 fails to load on VS code and prompts to install from website.

Older version is working fine.

**Comment by bobbrow** [comment]
Can you provide more information about how you installed it?  Did VS Code install it automatically?  Did you download the VSIX from GitHub and install it that way?  Which operating system are you using?

This information will help us determine what to do next.  Thank you!

**Comment by brianq-ti** [comment]
Yes, VS Code attempted to install it automatically.   Win10 Pro Build1909.

Regards,
Brian

**Comment by bobbrow** [comment]
Ok.  So in this case, the expected log output should look like this, but instead you are seeing a log that says the installation failed and you should download the VSIX from GitHub and install that instead?

The expected log:
```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (7144 KB)  Done!
Downloading package 'ClangFormat (Windows)' (814 KB)  Done!
Downloading package 'Visual Studio Windows Debugger' (13813 KB)  Done!

Installing package 'C/C++ language components (Windows)'
Installing package 'ClangFormat (Windows)'
Installing package 'Visual Studio Windows Debugger'

Finished installing dependencies
```

The installation depends on the ability to download Windows-specific binaries, so if your Internet connection was disrupted during the installation process or you have a firewall restriction that does not include our download URL as "safe", that could be the cause of the message.  Could either of these conditions be possible in your case?

EDIT: For reference, I have installed 1.1.3 successfully on Windows a few times, so the binary dependencies do appear to be in place.  Another possibility is that there was a temporary outage while you were trying to download.

**Comment by brianq-ti** [comment]
Correct.  I also tried uninstalling and reinstalling the plug-in.   I don’t think it’s a connection problem because if I manually select old v1.1.2 to install, it works fine still.

Regards,
Brian

**Comment by bobbrow** [comment]
Sorry, I don't know what else it could be then.  @sean-mcmanus, @Colengms, @michelleangela any ideas?

**Comment by Colengms** [comment]
Hi @brianq-ti .  If you haven't already tried this, could you try uninstalling the extension and deleting the existing installation directory (usually in `C:\Users\<user>\.vscode\extensions`) before reinstalling?  When VS Code uninstalls an extension, the directory may linger, and subsequent attempts to install will reuse the existing contents.  If your installation of the extension was somehow corrupted, it may be necessary to delete the existing directory to correct the issue.

**Comment by vbaderks** [comment]
Had the same problem, solved it with:
1) Uninstalling
2) Exit Visual Studio Code
3) Deleting the existing installation directory C:\Users\<user>\.vscode\extensions\ms-vscode.cpptools-1.1.3
4) Start Visual Studio Code again and re-install 1.1.3 of the C/C++ extension.

**Comment by brianq-ti** [comment]
Thanks!  That resolved the installation issue.  I’ve been using this extension for over a year and this is the first time I had this issue.

Regards,
Brian
