### ISSUE TITLE
editor hover Cannot display Chinese (UTF-8) correctly in string literals

### ISSUE THREAD

**Issue by pingseran** [microsoft/vscode-cpptools#6628]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux Mint 20  & WIN10
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them):  none
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

see pic
locale = zh_CN.UTF-8

![image](https://user-images.githubusercontent.com/31583951/101247004-ae3c5400-3751-11eb-948e-95e418a71aeb.png)

 also see   https://github.com/microsoft/vscode/issues/109975

**Comment by sean-mcmanus** [comment]
The "char" type is only 8 bytes, which is not large enough to store the Chinese characters.

You should use wchar_t instead:

![image](https://user-images.githubusercontent.com/19859882/101397823-0d00eb00-3882-11eb-9505-e352bd54499e.png)

I think the garbage characters is "by design".

**Comment by sean-mcmanus** [comment]
Oh, duh, char is big enough to contain UTF-8 characters, but they are multi-byte.

**Comment by sean-mcmanus** [comment]
You should use the "u8" string prefix:

![image](https://user-images.githubusercontent.com/19859882/101399629-974a4e80-3884-11eb-817b-e93dd1b2f63d.png)

See https://en.cppreference.com/w/cpp/language/string_literal .

**Comment by welod** [comment]
It works.    
Thanks
