### ISSUE TITLE
Ability to indent each case in a switch?

### ISSUE THREAD

**Issue by ItsCubeTime** [microsoft/vscode-cpptools#6629]
Type: Question/Feature request if there is no functionality for this yet.

So, when making a switch like so:
```
switch()
{
    default:
         cout << "default" << endl;
         break;
    case 0:
        cout << "case 0" << endl;
        break;
}
```
The default formatting settings will remove the first indentation:
```
switch()
{
default:
     cout << "default" << endl;
     break;
case 0:
    cout << "case 0" << endl;
    break;
}
```
Is there any way that I can have the formatter indent like my first example instead? I already have C_Cpp > Vc Format > Indent set to: `Within parentheses`

Also curious on when I type, I dont seem to be able to see any automatic formatting happening, instead I have to run the ctrl K F shortcut. I already have `Editor: Format On Type` set to `True`. Am I missing something here?

**Comment by sean-mcmanus** [comment]
![image](https://user-images.githubusercontent.com/19859882/101401662-83541c00-3887-11eb-851d-c262d3b1ffbd.png)

Use that setting.

**Comment by ItsCubeTime** [comment]
Thanks
