### ISSUE TITLE
Remove Go to declaration feature.

### ISSUE THREAD

**Issue by Mason-L** [microsoft/vscode-cpptools#663]
Visual Studio Code does already have a **Go to declaration** feature. Can you remove it in C/C++ for Visual Studio Code(Version 0.11.0: April 24, 2017)? Or tell me how to disable it in my Context Menu. Bucause there is two options of Go to declaration. My Visual Studio Code Version : 1.11.2.  And I use it in china.

**Comment by bobbrow** [comment]
What other extensions do you have installed?  I suspect that another extension you are using is providing the second implementation of go to declaration.  VS Code does not support this natively.

**Comment by sean-mcmanus** [comment]
It's pretty easy to modify the context menus in an extension via changing the "menus" section of the package.json in the extension's root folder. The main issue with manual modification is that updates will overwrite the modification.

**Comment by Mason-L** [comment]
I didn't find anything about disable **Go to declaration** feature in package.json(C:\Program Files (x86)\Microsoft VS Code\resources\app). And I checked many other package.json. I didn't find anything either.
If you please tell the exact way to disable it ?(Modify the context)

**Comment by sean-mcmanus** [comment]
In the "menus" section, you'll see the section with the commands for "C_Cpp.GoToDeclaration" and the other extension should have a similar entry for their menu item. You can remove the entire sections or modify them, such as changing the group to "other@5".

**Comment by bobbrow** [comment]
@Mason-L we still did not hear back as to which other extensions you have installed.  You can run `code --list-extensions` in your command prompt/terminal and share the output here.

In any case, there isn't much we can do here. We do not plan to remove/disable the **go to declaration** feature.  If you want to share a screenshot of the menu, we can help you identify which one comes from our extension.

**Comment by Mason-L** [comment]
Thank you all !   I hava send you a E-mail with my .json file and two screenshots.
