### ISSUE TITLE
mac vscode include error detected; include path issues

### ISSUE THREAD

**Issue by Kanstarry9T** [microsoft/vscode-cpptools#6631]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

![image](https://user-images.githubusercontent.com/43159305/101307351-36217b80-3882-11eb-9896-e119e1f4dd19.png)

**Comment by Kanstarry9T** [comment]
c_cpp_properties.json file

![image](https://user-images.githubusercontent.com/43159305/101307460-7bde4400-3882-11eb-804d-c78d255090dd.png)

**Comment by sean-mcmanus** [comment]
If your workspace folder is "carla", then an include path of "${workspaceFolder}" won't find "carla" unless a folder like "carla/carla" exists. You may want to open the parent folder as a workspace folder, or use "${workspaceFolder}/../**". Let us know if that doesn't work.

**Comment by Kanstarry9T** [comment]
Thanks a lot for your help! I tried open the parent folder (also use "${workspaceFolder}/../**"), and problem partially solved, however, some includepath error still exists. I attached some screenshot for your reference, and I appreciate if you can help me out. Thanks.

![image](https://user-images.githubusercontent.com/43159305/101462544-4b2c0680-3977-11eb-9993-ba7f7609c3fd.png)
![image](https://user-images.githubusercontent.com/43159305/101463111-f6d55680-3977-11eb-8e73-88ff1d267c2d.png)

**Comment by sean-mcmanus** [comment]
You need to add the path to the boost library. That is sometimes an external dependency that needs to be downloaded.

The squiggle on `#pragma once` is most likely about a missing include in the TU associated with the header file -- can you provide the error message? You can use the C/C++: Log Diagnostics command to see what source file is getting associated with the header. I assume an include path needs to be added.

**Comment by Kanstarry9T** [comment]
Thanks for your help, I also find there's a Cmake error - Bad CMake executable "". Is it installed or settings contain the correct path (cmake.cmakePath)?". 

And, the error message as you requested is as follows,
-------- Diagnostics - 12/9/2020, 9:54:27 AM
Version: 1.1.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/../**"
    ],
    "defines": [],
    "macFrameworkPath": [],
    "compilerPath": "/usr/local/bin/gcc-10",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${workspaceFolder}/../**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/kanwu/Desktop/postdoc/code/carla/LibCarla/source/carla/trafficmanager/ALSM.cpp ]:
    /Users/kanwu/Desktop/postdoc/code/carla/LibCarla/source/carla/trafficmanager/Constants.h
Translation Unit Configurations:
[ /Users/kanwu/Desktop/postdoc/code/carla/LibCarla/source/carla/trafficmanager/ALSM.cpp ]:
    Process ID: 4152
    Memory Usage: 223 MB
    Compiler Path: /usr/local/bin/gcc-10
    Includes:
        /usr/local/Cellar/gcc/10.2.0/include/c++/10.2.0
        /usr/local/Cellar/gcc/10.2.0/include/c++/10.2.0/x86_64-apple-darwin19
        /usr/local/Cellar/gcc/10.2.0/include/c++/10.2.0/backward
        /usr/local/Cellar/gcc/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0/include
        /usr/local/Cellar/gcc/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0/include-fixed
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
        /Users/kanwu/Desktop/postdoc/code/carla/LibCarla/source
        /Users/kanwu/Desktop/postdoc/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source
        /Users/kanwu/Desktop/postdoc/code/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla
        /Users/kanwu/Desktop/postdoc/code/carla/LibCarla/source/carla/trafficmanager
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100200
Total Memory Usage: 223 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 11095
Number of files discovered (not excluded): 10164
Number of files parsed: 799

**Comment by sean-mcmanus** [comment]
Is that error coming from the CMake Tools extension? Do you have CMake installed? Does that project use CMake? If not, you can disable the CMake Tools extension.

**Comment by Kanstarry9T** [comment]
Thanks for your help. I will try to install CMake, and try the options you provided. Thanks!
