### ISSUE TITLE
a bug (cpptools crash)

### ISSUE THREAD

**Issue by HeliosDragon** [microsoft/vscode-cpptools#6632]
Issue Type: <b>Bug</b>

[Error - 下午2:38:20] Connection to server got closed. Server will not be restarted.

Extension version: 1.1.3
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.84GB (15.21GB free)|
|Process Argv|--crash-reporter-id 1ef8d4d3-5abe-4236-9e40-611528b2fb12|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
That means our cpptools process crashed. Are you able to get a repro for us? Or follow the steps at https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv to get a crash call stack?

**Comment by HeliosDragon** [comment]
<- (E) {"seq":2,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the C/C++ Extension for Visual Studio Code\nwith Visual Studio Code, Visual Studio or Visual Studio for Mac\nsoftware to help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code
with Visual Studio Code, Visual Studio or Visual Studio for Mac
software to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"attach"}
-> (C) {"type":"response","seq":1,"command":"handshake","request_seq":1,"success":true,"body":{"signature":"037cVDLc/l4TYONCfY63WzJF2vFeCz5OQ2Fd4Y4w3d1wME="}}
<- (E) {"seq":7,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"name":"test.c","path":"e:\\NOJ作业\\034最大整数\\test.c"},"lines":[4],"breakpoints":[{"line":4}],"sourceModified":false},"type":"request","seq":3}
<- (R) {"seq":10,"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":4}]}}
-> (C) {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":4}
<- (R) {"seq":13,"type":"response","request_seq":4,"success":true,"command":"setFunctionBreakpoints","message":"","body":{"breakpoints":[]}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":5}
<- (R) {"seq":16,"type":"response","request_seq":5,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","type":"request","seq":6}
<- (E) {"seq":19,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/ProcessCreate","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.4.20227.2 commit:86e0ca2a3a756c16e152003f9c3bfbabaa22065f","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.18363"}}}
<- (E) {"seq":21,"type":"event","event":"process","body":{"name":"C:\\Users\\administrater\\.vscode\\extensions\\ms-vscode.cpptools-1.1.3\\bin\\cpptools.exe","systemProcessId":15680,"startMethod":"attach","pointerSize":32}}
<- (E) {"seq":23,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/Attach","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.4.20227.2 commit:86e0ca2a3a756c16e152003f9c3bfbabaa22065f","VS.Diagnostics.Debugger.vsdbg.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.18363","VS.Diagnostics.Debugger.vsdbg.TargetType":"Live","VS.Diagnostics.Debugger.vsdbg.AdapterId":"cppvsdbg","VS.Diagnostics.Debugger.vsdbg.SourceFileMappings":0,"VS.Diagnostics.Debugger.vsdbg.Attach.Duration":2281}}}
<- (R) {"seq":25,"type":"response","request_seq":6,"success":true,"command":"configurationDone"}
<- (E) {"seq":27,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":false,"message":"No symbols have been loaded for this document.","line":4}}}
-> (C) {"command":"threads","type":"request","seq":7}
<- (R) {"seq":30,"type":"response","request_seq":7,"success":true,"command":"threads","message":"","body":{"threads":[]}}
