### ISSUE TITLE
How to attach to a gdb

### ISSUE THREAD

**Issue by mttbx** [microsoft/vscode-cpptools#6635]
I want to attach to a gdb, not a program. This is not a launch type nor a attach type. Is it possible. This may help when debug a hardware.

**Comment by WardenGnaw** [comment]
Did you want to debug `gdb` with `gdb`? If you want to attach, then you can use the attach configuration with `type: cppdbg` and use the process picker to attach to `gdb`.

**Comment by mttbx** [comment]
I can start gdb to debug a program. But the gui of gdb is not good. I want to start debugging with gdb, then in the vscode I attach to that gdb, so that I can debug a program with vscode. The vscode need to forward command to that gdb.

**Comment by WardenGnaw** [comment]
You will want to use `gdbserver`. You can use `gdbserver` to debug your program, and then you can attach/detach multiple instances of GDB as long as it does not terminate the `gdbserver`.

You can connect to a local gdbserver with `miDebuggerServerAddress` with `127.0.0.1:<port>`.

**Comment by mttbx** [comment]
I'm gona close this issue.
