### ISSUE TITLE
range-v3 issue

### ISSUE THREAD

**Issue by grishalipenko** [microsoft/vscode-cpptools#6639]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux x64 5.4.0-56-generic
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.3

**Steps to reproduce**
I have code: 
```
#include <range/v3/algorithm/all_of.hpp>

......

    if (ranges::all_of(v, [](bool val) { return val; })) {
        publish();
    }
```
And I get message:

> no instance of overloaded function "ranges::all_of_fn::operator()" matches the argument list -- argument types are: (std::vector<bool, std::allocator<bool>>, lambda []bool (bool val)->bool) -- object type is: const ranges::all_of_fn

With another ranges same problem about "no instance".

How I can avoid this problem?

**Comment by Colengms** [comment]
Hi @grishalipenko .  Thanks for reporting this.  The issue also repro's in VS.  (We share code for IntelliSense with VS).  I've opened a bug against VS.  A link to that issue is here, in case you want to up-vote it: https://developercommunity.visualstudio.com/content/problem/1281603/incorrect-intellisense-squiggle-with-use-of-range.html

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders

**Comment by grishalipenko** [comment]
I installed 1.3.0-insiders from VSIX. And squiggle reproduce:

> no instance of overloaded function "ranges::all_of_fn::operator()" matches the argument list -- argument types are: (std::vector<bool, std::allocator<bool>>, lambda []bool (bool b)->bool) -- object type is: const ranges::all_of_fn

I can add screenshots if needed.

**Comment by grishalipenko** [comment]
I installed 1.3.0-insiders from VSIX. And squiggle reproduce:

> no instance of overloaded function "ranges::all_of_fn::operator()" matches the argument list -- argument types are: (std::vector<bool, std::allocator<bool>>, lambda []bool (bool b)->bool) -- object type is: const ranges::all_of_fn

I can add screenshots if needed.

**Comment by grishalipenko** [comment]
Another example:

> no instance of overloaded function "ranges::minmax_element_fn::operator()" matches the argument list -- argument types are: (const std::vector<int64_t, std::allocator<int64_t>>) -- object type is: const ranges::minmax_element_fn -- detected during instantiation of function "lambda []auto (const auto &v)->auto [with <auto-1>=std::vector<int64_t, std::allocator<int64_t>>]" at line 149 C/C++(304)

`                auto [min, max] = ranges::minmax_element(v);`

**Comment by sean-mcmanus** [comment]
It's fixed for me on Ubuntu 20 with g++ 10.2 and the latest https://github.com/ericniebler/range-v3. What g++ version are you using? What version of the range-v3 library are you using?
![image](https://user-images.githubusercontent.com/19859882/111839339-e2c6bc80-88b7-11eb-8be2-d4a493dcfc9c.png)

The code `auto [min, max] = ranges::minmax_element(v);` doesn't compile for me with g++: `error: ‘minmax_element’ is not a member of ‘ranges’; did you mean ‘bind_element’?
   11 |     auto [min, max] = ranges::minmax_element(v);`

**Comment by grishalipenko** [comment]
```
$ apt-cache policy librange-v3-dev
librange-v3-dev:
  Installed: 0.10.0-1
  Candidate: 0.10.0-1
  Version table:
 *** 0.10.0-1 100
        100 /var/lib/dpkg/statu
```
```
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
```
I tried to set c++20 and it don't fixed squiggle.

**Comment by grishalipenko** [comment]
same C/C++(304) squiggle with your configuration on test project
![v3](https://user-images.githubusercontent.com/18384142/111850424-4c2ee580-8921-11eb-87c1-fdd03073dabe.png)
c_cpp_properties.json:
```
{
  "configurations": [
    {
      "browse": {
        "databaseFilename": "",
        "limitSymbolsToIncludedHeaders": true
      },
      "includePath": [
        "/usr/include/**"
      ],
      "defines": [],
      "compilerPath": "/usr/bin/gcc-10",
      "cStandard": "c11",
      "cppStandard": "c++20",
      "intelliSenseMode": "gcc-x64",
      "name": "test"
    }
  ],
  "version": 4
}
```

**Comment by sean-mcmanus** [comment]
What if you remove the "/usr/include/**" from your includePath (which shouldn't be there and could cause the wrong header to be used)?

**Comment by grishalipenko** [comment]
Oh, I can fix it with latest range-v3 version - 0.11.0 that I set to `"${workspaceRoot}/include"`
![v3latest](https://user-images.githubusercontent.com/18384142/111851172-594cd400-8923-11eb-8063-bd1c8d9855c0.png)
```
{
  "configurations": [
    {
      "browse": {
        "databaseFilename": "",
        "limitSymbolsToIncludedHeaders": true
      },
      "includePath": [
          "${workspaceRoot}/include",
          "/usr/include",
          "/usr/local/include"
      ],
      "defines": [],
      "compilerPath": "/usr/bin/gcc",
      "cStandard": "c11",
      "cppStandard": "c++17",
      "intelliSenseMode": "gcc-x64",
      "name": "Linux"
    }
  ],
  "version": 4
}
```

But I have problem with librange-v3-dev that was installed 
`sudo apt install librange-v3-dev
`

**Comment by sean-mcmanus** [comment]
Okay, I repro that. I'm looking into it...

**Comment by grishalipenko** [comment]
Good. Thanks.

**Comment by sean-mcmanus** [comment]
I've filed a Visual Studio bug at https://developercommunity.visualstudio.com/t/C20-IntelliSense-gives-incorrect-error/1376696 .

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0-insiders
