### ISSUE TITLE
Add the ability to generate definitions from declarations and vice versa

### ISSUE THREAD

**Issue by benjaminjack** [microsoft/vscode-cpptools#664]
I spend a lot of time typing out lists of arguments (or copying and pasting them) when I'm defining functions that have already been declared in a header file. It would be nice if cpptools could automatically generate a skeleton definition of a function that has already been declared, or at least provide a shortcut to auto-fill the argument list.

**Comment by BrianSipple** [comment]
I was going to suggest something very similar. I'd also be interested in a feature to create a header- and source-file pair with a single task invocation. This would be similar to XCode, for example, which generates both a `.h` and `.cpp` file when the user selects an option to create a new class file.

**Comment by sean-mcmanus** [comment]
@bobbrow I believe this is the most used feature in VS that we are missing (used more often than Find All References).

As mentioned in https://github.com/Microsoft/vscode-cpptools/issues/3056, we should also support the "opposite" case of adding the declaration to the header from an existing definition.

**Comment by bobbrow** [comment]
Yeah, I have seen this feedback a few times in our survey responses.  It is on my radar.

**Comment by daranday** [comment]
Would love to have this feature!

**Comment by davidbitton** [comment]
Upvote!

**Comment by exocode** [comment]
Is this something you are looking for?: 

It is able to preserve existing methods and inclusions

![2019-06-03 12 55 16](https://user-images.githubusercontent.com/1597621/58797001-165f2680-85ff-11e9-9b97-46e02c5c2547.gif)


https://github.com/reignofwebber/vscode-c-cpp-definition-generator

**Comment by davidbitton** [comment]
@exocode yep! your work?

**Comment by yannickbt64** [comment]
Can't wait to have this implemented. Such a basic feature, yet very useful.

**Comment by ArcticLampyrid** [comment]
Can't wait to use it.
Do we have any plan to implement it?

**Comment by sean-mcmanus** [comment]
@1354092549 Yes, but we don't have it on our schedule yet.

**Comment by rafaelchen** [comment]
it would be really useful feature :)

**Comment by PoetaKodu** [comment]
I would love that!

**Comment by exocode** [comment]
@davidbitton sorry, no.. some other genius did that for all of us  :-)

**Comment by dbsxdbsx** [comment]
Just  upVote it, and it woud be better to have it with funcitonality like "changing signature".

**Comment by Flamefire** [comment]
Very related: Move implementation to source file (possibly creating it) which not only generates the signature but also moves the implementation from header to source.

**Comment by asynchronoust** [comment]
this feature will be very useful

but, when this feature will be implemented?

**Comment by sean-mcmanus** [comment]
@asynchronoust It's scheduled for post-v1, which would be some time (not early) next year (no guarantees though).

**Comment by victorvianna** [comment]
It would also be nice to have similar auto-generation for the initializer list in a class constructor.

**Comment by stonedreamforest** [comment]
+1

**Comment by amir9480** [comment]
I also created an extension for generating implementations last week.
With namespace, nested class/namespace, classes with templates and methods with templates support.

![screenshot](https://user-images.githubusercontent.com/16279288/75574465-9a055100-5a73-11ea-87b5-f9faa26cf29b.gif)

[amir9480/vscode-cpp-helper](https://github.com/amir9480/vscode-cpp-helper)

https://marketplace.visualstudio.com/items?itemName=amiralizadeh9480.cpp-helper

**Comment by ArcticLampyrid** [comment]
@amir9480 Great work.

**Comment by dbsxdbsx** [comment]
@amir9480,nice work, and it would be better  to add creating declaration.  Anyway, good job!

**Comment by santhisenan** [comment]
Much needed feature! It will save a lot of time and effort. Waiting for it🤞

**Comment by BoldHonor** [comment]
@amir9480  thankyou so much

**Comment by Rullec** [comment]
Waiting for it!

**Comment by bobbrow** [comment]
We began investigating this, but it won't likely be completed in time for the 0.30.0 milestone.

**Comment by thisisprateeksaxena** [comment]
Bumping for visibility ! It'll be great if it can be included in the next scheduled release. It is a big noticeable difference when alternating between QT and VSCode.

**Comment by cjwijtmans** [comment]
I would like the opposite feature. Auto generate a `.hpp` file on save(and update it every time saved). Would save a lot of time. Just use the same file path except use the `.hpp` extension. However this could be configured of course but it would be a sane default.

**Comment by maxint** [comment]
Recommend another extensions: https://marketplace.visualstudio.com/items?itemName=amiralizadeh9480.cpp-helper
![](https://raw.githubusercontent.com/amir9480/vscode-cpp-helper/master/images/screenshot.gif)

**Comment by BigBahss** [comment]
Figured I'd plug my extension for people looking for C/C++ code generation. You can add definitions & declarations, move definitions, generate getters, setters, equality operators, and more.

https://marketplace.visualstudio.com/items?itemName=tdennis4496.cmantic
https://github.com/BigBahss/vscode-cmantic

**Comment by Tasselmi** [comment]
> https://marketplace.visualstudio.com/items?itemName=amiralizadeh9480.cpp-helper

how to select multi method and generate definitions in batch . thx

**Comment by tibotix** [comment]
Hey guys, 

I just finished writing an extension that provides definition autocompletion suggestions for a function declared in the associated header file. Maybe this is something you would also like.
It supports member functions,  template functions,  and many more:

![](https://github.com/tibotix/vscode-definition-autocompletion/raw/master/images/member_function_completion_demo.gif)

Check it out if you want and I would love to hear some feedback.
https://marketplace.visualstudio.com/items?itemName=Tibotix.definition-autocompletion

**Comment by UtsavTrivedi16** [comment]
> @Tasselmi
> 
> https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

Move definition to source file action is not applied to multiple cursors. I tried selecting multiple definitions in a class and had no luck. Has anyone tried this?

**Comment by nathanradavies** [comment]
This is an important feature for my workflow. Would love to see this.

**Comment by omerbguclu** [comment]
Any news about that. I don't want to install extra extensions.

**Comment by douysu** [comment]
Upvote, it is important for us.

**Comment by crackwitz** [comment]
not gonna happen. I read somewhere that they consider this to be the responsibility of extension authors... meaning someone's gotta implement this in some LSP.

**Comment by bobbrow** [comment]
This is actively being worked on but it's been more work than we anticipated as we're trying to unify the codebase between VS and VS Code.

**Comment by davidbitton** [comment]
> This is actively being worked on but it's been more work than we anticipated as we're trying to unify the codebase between VS and VS Code.

The plugin or the two entire IDEs?

**Comment by bobbrow** [comment]
> @bobbrow The plugin or the two entire IDEs?

VS already has it.  We are working on it for the VS Code C++ extension which involves making the current VS implementation usable by the VS Code C++ extension.

**Comment by bobbrow** [comment]
This feature is available for preview.  Switch to the prerelease version of the C/C++ extension to install version 1.13.4 and give it a try.  There are a few known issues with the first implementation documented here: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.4.

**Comment by khlebnikov** [comment]
Filed an issue related to the new functionality: #10189

**Comment by bobbrow** [comment]
@khlebnikov thanks! We're looking into it.

**Comment by tirupatihemanth** [comment]
Hello! I this feature released for the general public?
i.e the ability to generate definitions of methods/classes from declarations/function calls etc.,

**Comment by pfeerick** [comment]
Please read https://github.com/microsoft/vscode-cpptools/issues/664#issuecomment-1319477285

**Comment by tirupatihemanth** [comment]
@pfeerick Thank you for the reply. I have the v1.13.8 of cpp extension. I am using gcc compiler on the windows machine. 
I still couldn't seem to activate this feature. I call a function in a method which hasn't been written yet. Now when I type
"Ctrl+." which brings up quickfix I don't see a suggestion to generate the method. How do I activate this feature?

**Comment by sean-mcmanus** [comment]
@tirupatihemanth Do you see the "..." under the start of the declaration of the methods that aren't implemented yet? Like in this screenshot?

![image](https://user-images.githubusercontent.com/19859882/209740820-79aadac3-82d3-4c6c-b0ad-24961b897294.png)

**Comment by tirupatihemanth** [comment]
@sean-mcmanus Yes I get that for function declarations in a class. 
Say If I call a function func2(); from main() function or any other global function then it doesn't suggest to generate the definition. It would be super useful if it can do that.

**Comment by sean-mcmanus** [comment]
@tirupatihemanth The feature works for you on a function declaration, right? It doesn't work when on a usage of a function that is not defined because our parser will see the identifier as just being undefined.

**Comment by tirupatihemanth** [comment]
@sean-mcmanus Yes it works for function declarations. It would be super useful if it suggests to generate definition of an undefined function on usage.
It works on visual studio this way for c#. Hope this feature comes to vscode for cpp. 
Thank you,
Happy New Year

**Comment by sean-mcmanus** [comment]
I've filed a feature request on VS at https://developercommunity.visualstudio.com/t/Add-support-for-Create-Declaration--Def/10242237 .

**Comment by Mulf** [comment]
Other than genenrating function definition one by one, we need to generate a whole cpp files from the header. i.e. After we finish the declaration of a class or some functions in .h, we can create a .cpp with those definitions there. The extention  [c/c++ definition generator](https://marketplace.visualstudio.com/items?itemName=reignofwebber.c-cpp-definition-generator) extenstion implements some functions, but far away from perfect. 

It would be great if cpptool adding such a feature.

**Comment by sean-mcmanus** [comment]
@Mulf Your suggested feature request is being tracked in https://github.com/microsoft/vscode-cpptools/issues/10414 .
