### ISSUE TITLE
Code autocomplete not works on macOS

### ISSUE THREAD

**Issue by SRTwILeK** [microsoft/vscode-cpptools#6640]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macos 10.15.6
- VS Code Version: 1.15.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): CMake 0.0.17, CMake Tools 1.5.3
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
I have a single project with cmake and cmake includes from prebuild libraries. The size of the project is around 1000 files (cpp tools parse around 14.000 files)

**Steps to reproduce**

I try to use the autocomplete feature, but I get that message: no suggestion
example:
namespace myns {
   class A {};
   class B {};
}

void func() {
 myns::[try autocomplete] -> no suggestion
}

Sometimes it works ... when I fully reinstall vscode and project cpp tools database, it works ~10 minutes, than stop working :(

**Expected behavior**

Autocomplete works on macos

**Comment by Colengms** [comment]
Hi @SRTwILeK .  Thanks for reporting this.  We will likely need more information to investigate this.  Basic failures such as this are usually related to a prior crash of a cpptools or cpptools-srv process, and may be related to specific source code it is failing to parse.

Could you try enabling debug logging, using `"C_Cpp.loggingLevel": "Debug"`, and provide the output of the C/C++ output channel leading up to the issue?  I'm particularly interested in any errors that are logged when you attempt to use auto-complete, or before that repro.  Also, could you explain how your project is configured - perhaps include your `c_cpp_properties.json` contents and any `C_Cpp` settings that might be relevant?
