### ISSUE TITLE
Extend the diagnostics API to allow the diagnostic collections without of a URIs

### ISSUE THREAD

**Issue by denis-shienkov** [microsoft/vscode-cpptools#6643]
**Type: LanguageService**

Right now, the diagnostic API use the file URI to set the diagnostics array: https://code.visualstudio.com/api/references/vscode-api#DiagnosticCollection :

![изображение](https://user-images.githubusercontent.com/8415796/101525521-7b39d080-399c-11eb-90ca-6c8957806084.png)

But, it does not work for the messages comes from the linker (for some custom toolchains), because there are these messages does not contains the path to the file, e.g.:

```
Error: L6415E: Could not find a unique set of libraries compatible with this image.
```

```
*** WARNING L16: UNCALLED SEGMENT, IGNORED FOR OVERLAY PROCESS
    SEGMENT: ?PR?FOO?MAIN
```

```
?ASlink-Warning-Undefined Global '_putchar' referenced by module 'vprintf'
```

and so forth.

So, it would be good to allow to add these messages to the `problems` panel too.

**Comment by Colengms** [comment]
Hi @denis-shienkov .  Did you intend to open this issue in [the vscode repro](https://github.com/microsoft/vscode)?  This repo is specifically for the C/C++ Extension.

**Comment by denis-shienkov** [comment]
@Colengms , ahh, do you meat, that this issue belongs directly to the vscode repo, but not to this cpp-tools repo?
