### ISSUE TITLE
Show executed command with cppbuild tasks

### ISSUE THREAD

**Issue by saulaxel** [microsoft/vscode-cpptools#6647]
Type: Debugger

Hello. I wonder where how can I see compilation commands being executed. Something like

gcc -g file.c ...

This could be helpful for checking if all de "args" are ok. When there is an error the output just says:

Starting to build...
/* No compilation commands here */
Build finished with error(s):
/* List of errors */

- OS and Version: Windows 10 - 1909
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.3

**To Reproduce**

I just created a new folder and a file sample.c in it.
```C
#include <stdio.h>

int main(void)
{
    printf("Hello, world\n");
}
```
Create a launch.js choosing C++ (GDB/LLDB), and gcc after that.

Later, go to task.json and write some options in "args" tha contain some error. For example:
```json
    "args": [
                "-g",
                "somple.c", // Note the misspelling here
                "-o",
                "${fileDirname}\\sample.exe"
            ],
```

The complete task.json file is something like this:
```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc.exe build active file",
            "command": "C:\\Program Files (x86)\\ZinjaI\\mingw32-gcc6\\bin\\gcc.exe",
            "args": [
                "-g",
                "somple.c",
                "-o",
                "${fileDirname}\\sample.exe"
            ],
            "options": {
                "cwd": "C:\\Program Files (x86)\\ZinjaI\\mingw32-gcc6\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

After pressing F5, I get the aforementioned messages. Gcc reports its errors, but I can't see the command that was executed to get those errors. This is a situation where I already know the code compiles correctly, and it is not obvious which of many args could be causing the problem (not like in the example, where the error message issued from the compiler should be enough).

Basically that's all. Here is the lauch.json just because you ask for it:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gcc.exe - Compilar y depurar el archivo activo",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "C:\\Program Files (x86)\\ZinjaI\\mingw32-gcc6\\bin",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files (x86)\\ZinjaI\\mingw32-gcc6\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Habilitar la impresión con sangría para gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: gcc.exe build active file"
        }
    ]
}
```

**Comment by sean-mcmanus** [comment]
Was there a reason looking at the args in tasks.json is not sufficient? Would showing commands and args used be more convenient?

**Comment by saulaxel** [comment]
Mostly to check things that have to be escaped, when there are a lot.

**Comment by TryerGit** [comment]
If you use make, it should work fine atleast on Ubuntu 20.10 and VSCode 1.51.1

Here is my sample from the Terminal popup after choosing the task to build.

```
> Executing task: make CONF=Debug -C ./.vscode <

make: Entering directory '/home/project/.vscode'
"make" -f Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory '/home/project/.vscode'
"make"  -f Makefile-Debug.mk dist/Debug/GNU-Linux/linux
make[2]: Entering directory '/home/project/.vscode'
mkdir -p build/Debug/GNU-Linux/_ext/1
rm -f "build/Debug/GNU-Linux/_ext/1/Main.o.d"
g++ -fno-common -fPIC -fno-strict-aliasing -fexceptions -fopenmp -DVSCODE   -c -g -D_LINDEBUG -I../include  -std=c++14 -MMD -MP -MF "build/Debug/GNU-Linux/_ext/1/Main.o.d" -o build/Debug/GNU-Linux/_ext/1/Main.o ../src/Main.cpp
mkdir -p dist/Debug/GNU-Linux
g++ -fno-common -fPIC -fno-strict-aliasing -fexceptions -fopenmp -DVSCODE    -o dist/Debug/GNU-Linux/linux build/Debug/GNU-Linux/_ext/1/Main.o  -lm -lpthread -ldl
make[2]: Leaving directory '/home/project/.vscode'
make[1]: Leaving directory '/home/project/.vscode'
make: Leaving directory '/home/project/.vscode'

Terminal will be reused by tasks, press any key to close it.
```

My tasks.json is:
```
{
            "label": "lindbgbuild",
            "type": "shell",
            "command": "make",
            "args": ["CONF=Debug", "-C", "./.vscode"],
            "group": "build"
}
```

Also, it is a good idea to have `On Task Error: Abort` in `settings.json` so that you don't inadvertently launch a wrong build.

**Comment by sean-mcmanus** [comment]
@elahehrashedi Did you want to fix this? Otherwise, I could look at it.

**Comment by saulaxel** [comment]
@TryerGit Hhm, I see. Make can be a good option. Also, is it my imagination or your version shows the command being executed just on: "> Executing task: make CONF=Debug -C ./.vscode <"? Because "make CONF=Debug -C ./.vscode" looks like the command I want to get.

**Comment by TryerGit** [comment]
@saulaxel 

Yes, only that is the command that is executed. So, only that needs to be within tasks.json. The rest of the commands like g++ -fno-common -fPIC, etc. that you see need to be within Makefile-Debug.mk and so on. So, the terminal in VSCode simply display what you would have otherwise got had you run the make command on bash/command prompt. There are many online tutorials about how to create makefiles. You can use one of those to get started.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
