### ISSUE TITLE
Cannot attach to qemu gdbserver

### ISSUE THREAD

**Issue by Trolldemorted** [microsoft/vscode-cpptools#6649]
Type: Debugger

**Describe the bug**
- OS and Version: W10 2004 -> Ubuntu 18.04.5 LTS (Remote - SSH)
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): (Remote - SSH)

**To Reproduce**
I am emulating an Armv7 operating system with qemu:
`qemu-system-arm -M raspi2 -nographic -s -kernel /data/kernel_debug -monitor telnet:0.0.0.0:1235,server,nowait`

I can debug that nicely with `gdb-multiarch data/kernel_debug` and `target remote 127.0.0.1:1234` in my `.gdbinit`. However, I have not been able to convince vs code to use that gdbsever. 

This config:
```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "GDB",
        "type": "cppdbg",
        "request": "attach",
        "program": "${workspaceRoot}/data/kernel_debug",
        "miDebuggerServerAddress": "127.0.0.1:1234",
        "miDebuggerPath": "/usr/bin/gdb-multiarch",
        "MIMode": "gdb",
      }
    ]
}
```
gives me an `attach: unable to parse the process id` error. Since the linter was also complaining that I should provide a processId, I put in the pid of my QEMU process:

```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "GDB",
        "type": "cppdbg",
        "request": "attach",
        "program": "${workspaceRoot}/data/kernel_debug",
        "miDebuggerServerAddress": "127.0.0.1:1234",
        "miDebuggerPath": "/usr/bin/gdb-multiarch",
        "MIMode": "gdb",
        "processId": 187816
      }
    ]
}
```
but this gives me an `attach: 'processId' cannot be used with miDebuggerServerAddress` error.

How can I convince the debugger to just connect to the gdbserver without it attempting to start processes or requiring process ids it shouldn't need to know?

**Comment by WardenGnaw** [comment]
Thank you for reporting this bug.

I am not familiar with qemu but we will investigate further to have this process work. 

The process with `miDebuggerServerAddress` is it assumes the debugServer (e.g. gdbserver) is already attached to the process and we will use `miDebuggerPath` to connect to the server. 

You should be able to do this with this configuration:
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "GDB",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceRoot}/data/kernel_debug",
        "miDebuggerServerAddress": "127.0.0.1:1234",
        "miDebuggerPath": "/usr/bin/gdb-multiarch",
        "MIMode": "gdb",
      }
    ]
}
```

**Comment by becominginsane** [comment]
Issue persists: launch configuration fails, it seems that it's trying to launch `program` (at least in my case)...
