### ISSUE TITLE
Syntax highlighting failure with '

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode-cpptools#665]
The following code is highlighted incorrectly:
#error doesn't work
int a;
![image](https://cloud.githubusercontent.com/assets/17859340/25480869/9e4328e0-2b42-11e7-84d4-1c1b2ff89a2c.png)
(This is a simplified version of the original code).  The following does work:
#error doesnt work
int a;
![image](https://cloud.githubusercontent.com/assets/17859340/25480884/b563b5d0-2b42-11e7-9538-0b7df6d9f877.png)

**Comment by sean-mcmanus** [comment]
I filed bug https://github.com/atom/language-c/issues/233 with atom/language-c.

**Comment by BillDenton** [comment]
Any news on this? I've just tripped over it again.

**Comment by sean-mcmanus** [comment]
This should be fixed now with the latest VS Code.
