### ISSUE TITLE
Not showing errors

### ISSUE THREAD

**Issue by Devashish-25** [microsoft/vscode-cpptools#6651]
Issue Type: <b>Bug</b>

Earlier the extension used to highlight the errors but is has stopped highlighting errors for now

Extension version: 1.1.3
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (6.61GB free)|
|Process Argv|--crash-reporter-id c35005c8-ef0c-4db7-9e6d-c98efc2564f3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30233463
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30233462

```

</details>

**Comment by sean-mcmanus** [comment]
What do you mean by "highlight the errors"? Can you give an example or screenshot?

**Comment by Reptile2503** [comment]
The problem was because of c++ extension. Installing from VSIX fixed the problem. Thanks

**Comment by michelleangela** [comment]
Closing as resolved.
