### ISSUE TITLE
C++ intellisense does not work when renaming pointer variable

### ISSUE THREAD

**Issue by miroslavradojevic** [microsoft/vscode-cpptools#6655]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04.5 LTS
- VS Code Version: 1.51.1
- C/C++ Extension Version: v1.1.3
- Renaming pointer variable using F2 (Rename Symbol) does not work. C/C++ plugin reports error: A definition for the selected symbol could not be located.

**Steps to reproduce**
In following C++ code snippet that uses PCL pointcloud library (https://pointclouds.org) classes and pointers:

```
pcl::PointCloud<pcl::PointXYZI>::Ptr pcl(new pcl::PointCloud<pcl::PointXYZI>());            
pcl::fromROSMsg(*pointCloudBuffer.front(), *pcl);

```
1. Mark pointer variable named `pcl`
2. Press F2 or right-click>Rename Symbol
3. Enter new name
4. See error: A definition for the selected symbol could not be located. shown in the plugin popup window 

**Expected behavior**
Variable should be renamed to newly typed name

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 12/11/2020, 11:54:11 PM
Version: 1.1.3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu11",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/miro/catkin_ws/src/AGV/src/lidar_read_node.cpp ]:
    /home/miro/catkin_ws/src/AGV/src/lidar_read_node.cpp
Translation Unit Configurations:
[ /home/miro/catkin_ws/src/AGV/src/lidar_read_node.cpp ]:
    Process ID: 2669
    Memory Usage: 122 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
Total Memory Usage: 122 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 36451
Number of files discovered (not excluded): 33485
Number of files parsed: 2633
```
</details>

**Screenshots**

![Screenshot from 2020-12-11 23-16-52](https://user-images.githubusercontent.com/24230674/101962431-724f3600-3c0c-11eb-9748-dcae2ff111d4.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
It works for me. Can you provide more info? Are you not configured correctly?

![image](https://user-images.githubusercontent.com/19859882/101968894-7e200580-3bd6-11eb-937d-fe81eedafe3b.png)
