### ISSUE TITLE
Possible to load Default Intellisense in the background?

### ISSUE THREAD

**Issue by boocs** [microsoft/vscode-cpptools#6657]
**Type: LanguageService, Feature Request**

**Describe the request**
- OS and Version: Windows 10
- VS Code Version: always Latest
- C/C++ Extension Version: always Latest

- With large projects, like an Unreal Engine project, the Default Intellisense can take ~20 secs to load when switching between header/source and vice versa. This also happens when typing a line in a header file. 
The problem is the Default Intellisense blocks all code suggestions while it loads.

Would it be possible to load Default Intellisense in the background and allow snippets, suggestions, and maybe even Tag Parser Intellisense to work for the ~20 seconds it takes for the Default Intellisense to load?

**Steps to reproduce**

1. Large project (like an Unreal Engine project)
2. Switch between header and source
3. Try to type something to get any code completions/suggestions/snippets.
4. Nothing will work until the Default Intellisense is finished loading

**Comment by sean-mcmanus** [comment]
Are you asking for it to fallback to tag parser completions, like it does for hover results?

**Comment by boocs** [comment]
> Are you asking for it to fallback to tag parser completions, like it does for hover results?

I'm talking about whenever the Default parser is loading Intellisense for the current file. Like so:

```
sending compilation args for J:\USERS\AUSER\DOCUMENTS\UNREAL PROJECTS\COOPGAME\SOURCE\COOPGAME\PRIVATE\SCHARACTER.CPP
include: J:\PROGRAM FILES\EPIC GAMES\UE_4.26\ENGINE\INTERMEDIATE\BUILD\WIN64\UE4EDITOR\INC\ENGINE
include: J:\PROGRAM FILES\EPIC GAMES\UE_4.26\ENGINE\SOURCE\RUNTIME
include: J:\PROGRAM FILES\EPIC GAMES\UE_4.26\ENGINE\SOURCE\RUNTIME\ENGINE\CLASSES
...
```

While it's loading it blocks all other completions so you get 0 completions when this happens. No snippets, or the new suggestions based on files that are open, and yes it would be nice to have Tag Parser completions while the Default Intellisense parses the current file's headers.

Here's some loose benchmarks (each test no other files open and Tag Parser is done loading at start).
Using heftier Character class files, this is how long 'sending compilation args' blocks all other completions:

Cold open a source file: ~20 seconds before any completions become available.
Cold open a header file: ~40 seconds before any completions become available.
Add var to header class and Alt-O switch to source file: ~40 seconds before any completions become available.
Add var to header class and try to get completion for the next line in the header: ~20 seconds (Source files don't have this issue)

**Comment by sean-mcmanus** [comment]
The snippets are provided by IntelliSense, which is why it's blocking for it to load. We could potentially give "tag parser" completion results in the cold open case (or in any case an existing cpptool-srv isn't active) like it does for hover, but probably not in the update cases.

But @bobbrow was thinking the "tag parser" results were or could confuse people, and we were considering removing even the hover tag parser results.

**Comment by boocs** [comment]
> But @bobbrow was thinking the "tag parser" results were or could confuse people, and we were considering removing even the hover tag parser results.

An option to just turn something like it on would be great! It could be off by default.

**Comment by sean-mcmanus** [comment]
That sounds good to me.
