### ISSUE TITLE
Extension search fails to find TeX Comments

### ISSUE THREAD

**Issue by pauljurczak** [microsoft/vscode-cpptools#6661]
Extension search inside VS Code with `TeX Comments` query fails to find TeX Comments (https://marketplace.visualstudio.com/items?itemName=vs-publisher-1305558.VsTeXCommentsExtension). It's not in the top 30 results.

**Describe the bug**
- OS and Version: Ubuntu 18.04.5
- VS Code Version: 1.52.0

**Comment by Colengms** [comment]
Hi @pauljurczak .  This repo is for the C/C++ Extension for VS Code.  Did you intend to post this to [the VS Code repo](https://github.com/microsoft/vscode) ?

**Comment by pauljurczak** [comment]
You are right - wrong repo!
