### ISSUE TITLE
Stopped due to shared library event (no libraries added or removed) when trying to debug with shared library

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6666]
I'm seeing similar issue with shared objects. When debugging and you see in next step that application is about to load dynamic library (=shared object), during that period of time "Debug" > "Step Over (F10)" does not work correctly - as debug session is terminated. This can happen in global your own global function call or actual function which performs that .so loading, like 

`iconv_t    cd_to = iconv_open(fLocalCP, eptr->fSchema);`

Visual studio debugger will show following error message (while stopping debug session):

```Breakpoint 2, xercesc_3_1::IconvGNUTransService::IconvGNUTransService (this=0x84c7c48, manager=0x84c7970) at .../xerces/src/xercesc/util/Transcoders/IconvGNU/IconvGNUTransService.cpp:450
450         iconv_t    cd_to = iconv_open(fLocalCP, eptr->fSchema);
Stopped due to shared library event (no libraries added or removed)
Stopped due to shared library event:
  Inferior loaded /usr/lib/x86_64-linux-gnu/gconv/UTF-16.so
Loaded '/usr/lib/x86_64-linux-gnu/gconv/UTF-16.so'. Symbols loaded.
[Inferior 1 (process 31480) exited normally]
The thread 'testApplication' (0x7af8) has exited with code 0 (0x0).
The program '' has exited with code 0 (0x0).
```

Problem is only within a debugger, not application itself.

You can walk around this problem by setting breakpoint to 
next statement which shall be executed, and execute "Debug" > "Continue"
then you can successfully bypass that problematic point.

_Originally posted by @tapika in https://github.com/microsoft/vscode-cpptools/issues/2526#issuecomment-495266770_

**Comment by WardenGnaw** [comment]
Marking as need to investigate. More information can be found in related issue.
