### ISSUE TITLE
Can't configure C Standard (Always uses old c standards)

### ISSUE THREAD

**Issue by krnlcode** [microsoft/vscode-cpptools#6669]
**Type: LanguageService**

My project always fails,  because the extension thinks I want to use really old c standards, but I do specify that I want c99 (or gnu 99).

**Describe the bug**
- OS and Version: 
- VS Code Version: Latest release (just installed)
- C/C++ Extension Version: Latest release (just installed)
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Workspace is a single project, size of the project is just a single source code file that consists of 130 lines. I tried to change the C standard from the c_cpp_properties and also from the extension settings window, not working.

**Steps to reproduce**

1. Install extension C/C++
2. Open your project
3. Load the c/c++ extension
4. get errors

**Expected behavior**

Should not alert that a function header must have a ; at the end, for example:
`int code() {
    return 0;
}`
"int code()" -> expected a ';'C/C++(65)

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 15/12/2020, 11:12:12
Version: 1.1.3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}",
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu99",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}",
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/../main.c ]:
    /home/../main.c
Translation Unit Configurations:
[ /home/../main.c ]:
    Process ID: 26540
    Memory Usage: 11 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /home/../project name
    Standard Version: c99
    IntelliSense Mode: gcc-x64
    Other Flags:
        --gcc
        --gnu_version=90300
Total Memory Usage: 11 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 70453
Number of files discovered (not excluded): 59568

```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I don't repro the issue. Your Log Diagnostics info looks correct -- it's using c99/gnu99. Can you provide any more repro info?

![image](https://user-images.githubusercontent.com/19859882/102256932-e44fa580-3ec0-11eb-917a-8791f11a1e3c.png)

**Comment by sean-mcmanus** [comment]
What makes you think it's using an old standard?

I don't know why `int code() { return 0; }` would squiggle even under an old standard.

**Comment by codekrnl** [comment]
I have no clue why it doesn't want to compile, surely it ain't my fault. I tried to reconfigure it many times, but I always encounter the same error. I've already reinstalled the IDE with the extensions and still the same error occurs.

**Comment by codekrnl** [comment]
I fixed it by reinstalling the extension again and reconfiguring the include paths.
