### ISSUE TITLE
can not open the source code file header while using cmake.tool & this extension

### ISSUE THREAD

**Issue by byterii** [microsoft/vscode-cpptools#6670]
**Type: LanguageService**

**Describe the bug**
- OS and Version: mac remote to ubuntu-18.0 
- VS Code Version: 1.52.0
- C/C++ Extension Version:v1.1.3
- Other extensions you installed (and if the issue persists after disabling them): CMake Tools
- Does this issue involve using SSH remote to run the extension on a remote machine?:yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

i'm new to vscode ,when i use this in a project using third party library, i config it cmake.tool to config my intellisense,and i set the compile_command.json in the right way,but it can't open the source code correctly in some source code ,and in other folder, it can work well, i can't figure out the reson,
**Steps to reproduce**

c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
           ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "clang-x64",
            "configurationProvider": "ms-vscode.cmake-tools",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
What do you see when you run the C/C++: Log Diagnostics command? That will show what includes are actually being used by IntelliSense.

**Comment by sean-mcmanus** [comment]
Also, the compileCommands and configurationProvider options are mutually exclusive -- you should probably remove the compileCommands option if you want to use the configurationProvider (or if the configurationProvider isn't behaving as desired you can try using only the compileCommands method).

**Comment by SteinsElite** [comment]
Hello & thanks, when i remove compileCommands,it does not work eigther, but remove the configurationProvider is effective.
And when i run the C/C++: Log Diagnostics, the browse path indicate what will be included?

**Comment by sean-mcmanus** [comment]
If removing the configurationProvider makes things better, it's probably because you haven't configured CMake Tools correctly (you have to run commands like CMake: Configure and possibly set some CMake settings).

The "Includes" section indicates what include paths will be used.

**Comment by SteinsElite** [comment]
Thanks for the quick reply, but i can't figure out what cmake seeting should be setting after reading the cmake doc：https://github.com/microsoft/vscode-cmake-tools/blob/master/docs/cmake-settings.md,i'm very appreciated if you could give me some suggestion about the change of default seeting to make things right.
