### ISSUE TITLE
Hash named directory keep generated whenever open c++ files that has include errors.

### ISSUE THREAD

**Issue by lesomnus** [microsoft/vscode-cpptools#6671]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.04, open workspace on remote container.
- VS Code Version: 1.52.0 940b5f4bb5fa47866a54529ed759d95d09ee80be x64
- C/C++ Extension Version: v1.1.3
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: remote container
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Single project workspace, small size project, git, cmake (cmake extension is not related to this issue), vcpkg.

**Steps to reproduce**

1. Open workspace
2. Open c++ files (.cpp, .hpp, or etc.)
3. Problem reported -> "#include errors detected..." (This is usual problem)
4. Some hash named directory generated on the workspace root

One directory is created per file.

I confirm that the directory is not generated for the c++ files that has no include related errors.

Sample of name generated directories:
- dff70c4b0a2e3776
- ac773b0e520b8268
- 42afe8a1a9fea4e6
- 4d4ce71399027b20

so random

and has mod 888
```sh
❯ ls -l | grep 42af     
drwxrwxrwx 2 thor 1000 4096 Dec 15 13:15 42afe8a1a9fea4e6
```

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 12/15/2020, 1:17:36 PM
Version: 1.1.3
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/local/bin/gcc",
    "cStandard": "gnu17",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "cppStandard": "c++17",
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": []
}
Translation Unit Mappings:
[ /workspaces/fast-gicp/include/thor/fast_gicp/gicp/impl/fast_gicp_impl.hpp ]:
    /workspaces/fast-gicp/include/thor/fast_gicp/gicp/impl/fast_gicp_impl.hpp
[ /workspaces/fast-gicp/include/thor/fast_gicp/gicp/impl/fast_gicp_st_impl.hpp ]:
    /workspaces/fast-gicp/include/thor/fast_gicp/gicp/impl/fast_gicp_st_impl.hpp
    /workspaces/fast-gicp/include/thor/fast_gicp/gicp/gicp_settings.hpp
[ /workspaces/fast-gicp/include/thor/fast_gicp/gicp/impl/fast_vgicp_cuda_impl.hpp ]:
    /workspaces/fast-gicp/include/thor/fast_gicp/gicp/impl/fast_vgicp_cuda_impl.hpp
Translation Unit Configurations:
[ /workspaces/fast-gicp/include/thor/fast_gicp/gicp/impl/fast_gicp_impl.hpp ]:
    Process ID: 3982
    Memory Usage: 265 MB
    Compiler Path: /usr/local/bin/gcc
    Includes:
        /usr/local/include/c++/10.2.0
        /usr/local/include/c++/10.2.0/x86_64-linux-gnu
        /usr/local/include/c++/10.2.0/backward
        /usr/local/lib/gcc/x86_64-linux-gnu/10.2.0/include
        /usr/local/include
        /usr/local/lib/gcc/x86_64-linux-gnu/10.2.0/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include
        /workspaces/fast-gicp/include/thor
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include/flann
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include/pcl
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/tools/boost-build/src/engine
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include/boost/predef/os
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100200
        --header_only_fallback
[ /workspaces/fast-gicp/include/thor/fast_gicp/gicp/impl/fast_gicp_st_impl.hpp ]:
    Process ID: 4024
    Memory Usage: 600 MB
    Compiler Path: /usr/local/bin/gcc
    Includes:
        /usr/local/include/c++/10.2.0
        /usr/local/include/c++/10.2.0/x86_64-linux-gnu
        /usr/local/include/c++/10.2.0/backward
        /usr/local/lib/gcc/x86_64-linux-gnu/10.2.0/include
        /usr/local/include
        /usr/local/lib/gcc/x86_64-linux-gnu/10.2.0/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /workspaces/fast-gicp/include/thor
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include/flann
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include/pcl
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/tools/boost-build/src/engine
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include/boost/predef/os
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100200
        --header_only_fallback
[ /workspaces/fast-gicp/include/thor/fast_gicp/gicp/impl/fast_vgicp_cuda_impl.hpp ]:
    Process ID: 4226
    Memory Usage: 505 MB
    Compiler Path: /usr/local/bin/gcc
    Includes:
        /usr/local/include/c++/10.2.0
        /usr/local/include/c++/10.2.0/x86_64-linux-gnu
        /usr/local/include/c++/10.2.0/backward
        /usr/local/lib/gcc/x86_64-linux-gnu/10.2.0/include
        /usr/local/include
        /usr/local/lib/gcc/x86_64-linux-gnu/10.2.0/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include/flann
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include/pcl
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/tools/boost-build/src/engine
        /workspaces/fast-gicp/build/vcpkg_installed/x64-linux/include/boost/predef/os
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100200
        --header_only_fallback
Total Memory Usage: 1370 MB


```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
My guess is that that the strange file is generated from your OS as a result of a process crashing, possibly cpptool-srv. When headers can't be resolved, that increases the likely hood that our parser could hit an unexpected condition and crash. There are ways to configure your OS to change its core dump behavior.

Can you comment out (or #if 0) all the code, attach a debugger to cpptool-srv (see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) and then re-enable the code and see if the debugger hits a crash?

**Comment by lesomnus** [comment]
I noticed that **some** cpp files without problem also generate a directory and this issue occurs only in the remove workspace (there is no problem on the host workspace).
1. Attach a debugger
1. Open cpp file which all code is commented (so, no problem reported)
1. Directory generated
1. Un-comment all code
1. Nothing happens
1. Open another cpp file which has no problem
1. Nothing happens
1. Open another cpp file which has #include problem
1. Directory generated
1. Debugger SIGKILLed

I can't say that include problem causes this issue, because some files have no include problem but directory is generated. In that case, the debugger not crashes.

**Comment by sean-mcmanus** [comment]
Okay, it doesn't sound like it's caused by crashing.

Are you able to determine what process is generating the directories?

We don't know how our extension could be causing those directories to be generated by us. We do generate hash directories for the C_Cpp.intelliSenseCachePath setting, but they go under an ipch folder.

**Comment by lesomnus** [comment]
I removes all configuration (on devconfig.json, settings.json, and global one) but directory still generated.

It seems that C_Cpp.intelliSenseCacheSize is not visible to me but I set it to 0 but directory still generated.

After C_Cpp.intelliSenseEngine to "Tag Parser", directory is NOT generated ;)

**Comment by sean-mcmanus** [comment]
If setting the intelliSenseEngine to "Tag Parser" causes the directory to not be generated, then that implies that the IntelliSense process cpptools-srv may be creating that directory (the same process that would create the intelliSense cache folder with the guid name). Or it could be something related to the IPC code, which we've replaced as of our pending 1.2.0-insiders.

Do guid folders get created when you do a Find All References that has lots of potential references (with the status bar saying "<big number> files confirmed"? Doing that should launch multiple temporary cpptool-srv processes that don't generate ipch caches.

What do you mean by the intelliSenseCacheSize not being visible to you? You have to set it as a remote/workspace/folder setting:

![image](https://user-images.githubusercontent.com/19859882/102515588-c8740d00-4042-11eb-9305-29987590fae3.png)

Can you try setting the C_Cpp.intelliSenseCachePath to ${workspaceFolder}/.vscode (with intelliSenseCacheSize = 5120 and intelliSenseEngine = "Default") and verify the ipch files are generated with the guid folders? That's the only code I can locate that generates a guid folder.

Otherwise, I'd suggest waiting till 1.2.0-insiders gets released in January to see if that fixes it.

**Comment by lesomnus** [comment]
Ah, it seems that intellisenseCache* configuration only visible on remote configuration tab when in the remote workspace? I looked for that on the global configuration tab yesterday.

- `intelliSenseCacheSize=0` does not generate directories on workspace root.
- `intelliSenseCachePath="path"` with `intelliSenseCacheSize=5120` generate directories on `path` with some binary files.

Much of thank you!
