### ISSUE TITLE
&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"

### ISSUE THREAD

**Issue by azuric** [microsoft/vscode-cpptools#6672]
Hi running VS Code form an Ubuntu 18.04 with an ssh into a Cent OS 7. Iam getting this error:

> &"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"
> /bin/bash: /home/akhil/cp_libs/OnixS.EurexEtiHandlerCpp-CentOS7-gcc485-c++11-x64-9.5.0/samples/Connect/Main.o: Permission denied
> /bin/bash: line 0: exec: /home/akhil/cp_libs/OnixS.EurexEtiHandlerCpp-CentOS7-gcc485-c++11-x64-9.5.0/samples/Connect/Main.o: cannot execute: Permission denied

Here is my launch.json

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/akhil/cp_libs/OnixS.EurexEtiHandlerCpp-CentOS7-gcc485-c++11-x64-9.5.0/samples/Connect/Main.o",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]`

**Comment by azuric** [comment]
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/akhil/cp_libs/OnixS.EurexEtiHandlerCpp-CentOS7-gcc485-c++11-x64-9.5.0/samples/Connect/Main.o",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
```

**Comment by WardenGnaw** [comment]
How was `Main.o` built? The error is `exec: /home/akhil/cp_libs/OnixS.EurexEtiHandlerCpp-CentOS7-gcc485-c++11-x64-9.5.0/samples/Connect/Main.o: cannot execute: Permission denied`

**Comment by azuric** [comment]
```
#
# Makefile to produce TradingClient executable
#

CXX = c++
CC = c++
CXXFLAGS = -O3 -pthread -std=c++11 -Wall -g
CPPFLAGS = -DNDEBUG -I. -I.. -I../../include
LDFLAGS = -pthread -L../../lib -Wl,-rpath ../../lib
LDLIBS = -lonixs-eurex-eti

SOURCES = Main.cpp \
	      Application.h \
		  Application.cpp \
	      json/json.h \
		  jsoncpp.cpp \
          MessageFactory.cpp \
          MessageFactory.h \
          Order.cpp \
          Order.h \
          Settings.cpp \
          Settings.h \
          stdafx.cpp \
          stdafx.h \
          UniquePtr.h \
          Utils.cpp \
          Utils.h

OBJECTS = $(patsubst %.cpp,%.o,$(filter-out %.h,$(SOURCES)))

Application: $(OBJECTS)

clean:
	rm -f Application $(OBJECTS)

.PHONEY: clean
```

**Comment by WardenGnaw** [comment]
I blelieve you want to replace `program` in your `launch.json` to point to `Application`.

Main.o is an object file that is a intermediate file that is then later used in the part of linking and creating the `Application` executable.

**Comment by azuric** [comment]
Hi thanks I see my error

**Comment by WardenGnaw** [comment]
Closing as resolved.
