### ISSUE TITLE
Severe performance regression in 1.52 making vscode unusable

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-cpptools#6676]
Originally created by @QwertyZW  at https://github.com/microsoft/vscode-remote-release/issues/4186

---

- VSCode Version: 1.52
- OS Version: Windows 10

I'm using vscode with the Microsoft C/C++ intellisense + remote development plugins enabled.

Vscode auto upgraded itself to 1.52. When highlighting any variables/headers/etc, it would simply display "Loading..." for minutes on end. Opening a new file takes about a minute or two to load the git gutter change highlighting.

Sshing into the remote server and looking at htop shows vscode at the top using 100% CPU. This never ends.

I rolled back to 1.51.1 and disabled auto updates and everything is back to normal

---

The extension (along With others) also auto updated, but I didn't have to roll it back. I might look into rolling forWard and debugging this if I have time, but no plans for noW.

For the time being I encourage you to be able to try and reproduce this yourself for the sake of the quality of your future releases. There's nothing special about my setup. Pretty sure soon enough more users Will come With the same problem. Just thought I'd report it While it's still fresh, note the problematic version of vscode and provide a remedy to people suffering from the same problem.

---

One thing to note is that I'm working on multiple projects, all in the same WS, approximately 60-70k lines of code in total, with 400k-500k+ lines of code worth of dependency headers. It looks like you have a trivial program there that probably isn't representative of most of the users' setups out there.

Try setting up the linux kernel (correctly) or a large enough C++ project (qt creator might be a better choice). That should be a similar setup to what I have. Be sure to update your c_cpp json to include all the directories that have header files and that vscode (1.51.1) is able to find at least most of the headers. I definitely recommend that you keep such setup handy and ready to go for occasions such as this.

Not sure what this means "(I chose wsl instead of ssh)" or if it has any thing to do with the problem. Do you mean that your target "remote" box is your local WSL as opposed to something that is actually physically remote? Because I'm using WSL too. I can run ssh directly from windows commandline (only works after setting up WSL), and I run some other authentication program directly from windows cmd line that generate a local certificate which vscode then uses. (the program binary is for linux, and I originally installed it for WSL). To be clear, my "remote" is a physically remote node

Let me know if you still can't reproduce the problem after that

**Comment by sean-mcmanus** [comment]
@QwertyZW Are you using the "C/C++" extension or the "C/C++ IntelliSense" extension? What version of the extension? What OS is the remote one? Does the issue repro if you disable the extension?

Can you use Help->Toggle Developer Tools->Performance and use the record button to get a perf trace?

**Comment by alexdima** [comment]
This might be caused by our new automatic port forwarding feature which scans the remote OS for available ports in order to forward them locally (https://github.com/microsoft/vscode/issues/112843)
