### ISSUE TITLE
IntelliSense not providing full list of struct members from included library

### ISSUE THREAD

**Issue by weinix** [microsoft/vscode-cpptools#6680]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.52.1
- C/C++ Extension Version: v1.1.3
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I am developing MQL5(C++ like) application with VS code and observed below 

**Below screen is the behavior, I can see a few members of the struct, but missing most of them.** 

![image](https://user-images.githubusercontent.com/8346873/102558094-8ddd9500-4081-11eb-84a4-bb068fdd1d14.png)

**Below is the screenshot of my actual struct in the included library.
![image](https://user-images.githubusercontent.com/8346873/102558156-ab126380-4081-11eb-8d78-d5f71fc290d0.png)

**Steps to reproduce**

1. Get the library: https://c.mql5.com/3/176/MQLsyntax.mqh
2. Write a small test code that #include <MQLsyntax.mqh> first
3. define mrequest with MqlTradeRequest: "MqlTradeRequest   mrequest;"
3. type "mrequest." to see the member list and you will see the issue.

**Expected behavior**

Expect to see the full list or be able to search any member by typing the first few characters.

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
https://c.mql5.com/3/176/MQLsyntax.mqh doesn't have a definition for MqtTradeRequest. Do you have a different version?

**Comment by weinix** [comment]
sorry, I actually added below to the top of the version from the link:

//----------- Added by Wei ---------------
#define _Symbol 
#define _Period 
struct MqlTradeRequest {
  ENUM_TRADE_REQUEST_ACTIONS    action;           // Trade operation type.
  ulong                         magic;            // Expert Advisor ID (magic number).
  ulong                         order;            // Order ticket.
  string                        symbol;           // Trade symbol.
  double                        volume;           // Requested volume for a deal in lots.
  double                        price;            // Price.
  double                        stoplimit;        // StopLimit level of the order.
  double                        sl;               // Stop Loss level of the order.
  double                        tp;               // Take Profit level of the order.
  ulong                         deviation;        // Maximal possible deviation from the requested price.
  ENUM_ORDER_TYPE               type;             // Order type.
  ENUM_ORDER_TYPE_FILLING       type_filling;     // Order execution type.
  ENUM_ORDER_TYPE_TIME          type_time;        // Order expiration type.
  datetime                      expiration;       // Order expiration time (for the orders of ORDER_TIME_SPECIFIED type.
  string                        comment;          // Order comment.
  ulong                         position;         // Position ticket.
  ulong                         position_by;      // The ticket of an opposite position.
};
// @see: https://www.mql5.com/en/docs/constants/structures/mqltraderesult
struct MqlTradeResult  {
  uint     retcode;          // Operation return code.
  ulong    deal;             // Deal ticket, if it is performed.
  ulong    order;            // Order ticket, if it is placed.
  double   volume;           // Deal volume, confirmed by broker.
  double   price;            // Deal price, confirmed by broker.
  double   bid;              // Current Bid price.
  double   ask;              // Current Ask price.
  string   comment;          // Broker comment to operation (by default it is filled by description of trade server return code).
  uint     request_id;       // Request ID set by the terminal during the dispatch.
  uint     retcode_external; // Return code of an external trading system.
};`

Thanks for looking into it!
`

**Comment by sean-mcmanus** [comment]
Completion is failing because the types of the other members are not defined. If you don't see squiggles, that means you have errorSquiggles disabled, a header isn't being resolved, or you don't have a workspace folder open.

Are you able to include the file that defines the types used?

**Comment by weinix** [comment]
Thank you, Sean! That makes sense. Let me check from my side and will report back.

**Comment by weinix** [comment]
I was able to make it working  by adding typedef for missing type definitions:

```
typedef ulong;
typedef string;
typedef  ENUM_ORDER_TYPE;
typedef  ENUM_ORDER_TYPE_FILLING;
typedef  ENUM_ORDER_TYPE_TIME;
typedef  datetime;
typedef  ENUM_TRADE_REQUEST_ACTIONS;
typedef  uint;
```
They are MQL5 internal types and don't have a library file for them readily.. But now I know how I can get it working.
Appreciated your help!
