### ISSUE TITLE
can this extension auto-complete when some header file detected error?

### ISSUE THREAD

**Issue by sakizhu** [microsoft/vscode-cpptools#6681]
**Describe the bug**
- OS and Version: linux
- VS Code Version: 1.52.0
- C/C++ Extension Version: v1.1.3
- Does this issue involve using SSH remote to run the extension on a remote machine?: yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

here is my workspace struct:
![image](https://user-images.githubusercontent.com/9567827/102627211-d630ac00-4182-11eb-8438-1ce38d5d4b26.png)
 The 'autocomplete' function in vscode didn't work as what I expect. For example, if I have defined a class "CException" in one file, when I type "ce" in another file, what I want is it can autocomplete "CException" for me. Howerer, it didn't do that.
![image](https://user-images.githubusercontent.com/9567827/102628527-c619cc00-4184-11eb-8c86-a85dfb84ea6f.png)

The "CException" class define in ${worksapceFolder}/comm/exception.h 
![image](https://user-images.githubusercontent.com/9567827/102628499-ba2e0a00-4184-11eb-98da-3601931125d4.png)

**Comment by sean-mcmanus** [comment]
Is exception.h included by the TU? IntelliSense completion requires that the definition exists in the TU.

**Comment by sakizhu** [comment]
> Is exception.h included by the TU? IntelliSense completion requires that the definition exists in the TU.

sorry, what's TU mean?where I can find it

**Comment by sean-mcmanus** [comment]
TU means the .cpp file plus all the header files that are included. You run the C/C++: Log Diagnostics command to see info on the TU and what the include paths are and if exception.h is being included in that TU or another one.

**Comment by sakizhu** [comment]
> TU means the .cpp file plus all the header files that are included. You run the C/C++: Log Diagnostics command to see info on the TU and what the include paths are and if exception.h is being included in that TU or another one.

I have set "includePath" varibale and "browser.path" variable, 
![image](https://user-images.githubusercontent.com/9567827/103348020-ae6f0b80-4ad3-11eb-8baf-b40a981dec2f.png)
but exception.h not appear in TU， what should I  do to make it work well？
