### ISSUE TITLE
std::filesystem::path

### ISSUE THREAD

**Issue by jwkunz** [microsoft/vscode-cpptools#6683]
std::filesystem is part of the c++17 standard.  The editor does not seem to recognize the namespace.
```
#include <filesystem>
int main(){
auto filename = std::filesystem::path("hello.txt");
}
```
Gives an editor error "name followed by '::' must be a class or namespace name C/C++(276)".
The peek feature allows me to view the definition in the source code.
The code compiles and runs just fine with c++17.

**Comment by sean-mcmanus** [comment]
Works for me. What is your OS, compilerPath, and cppStandard, i.e. output of C/C++: Log Diagnostics?

![image](https://user-images.githubusercontent.com/19859882/102656192-537b0300-4128-11eb-8e46-c09c3c38a049.png)

**Comment by jwkunz** [comment]
Thank you for the quick response.

I'm in the Ubuntu-20.04 WSL terminal
g++ -g -Wall -std=c++17

Now that I have to be more rigorous, the plot thickens.

If I take an existing project where I have the error, strip down all of my source code to the simple code above, I get the following squiggle errors:

idle loop: reparsing the active document
Checking for syntax errors: file:///mnt/c/Users/jakek/Repos/dsp_tools/LPF_gen/test/temp.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/c/Users/jakek/Repos/dsp_tools/LPF_gen/test/temp.cpp
Error squiggle count: 1
Error squiggle count: 0
Update IntelliSense time (sec): 0.376

If I start a brand new VS code project, using my same  .vscode directory, makefile, WSL environment, as the projects where I have been seeing this error, I cannot reproduce the error in the new project.

Since it is not reproducible in a new project, looks like this error is beyond the scope of this forum.   Thank you for your time.

**Comment by jackeykong** [comment]
I ran into a similar problem. The CPP file just wrote the following code, and the compile prompted an error：
```
#include <filesystem>
using namespace std;
namespace fs = std::filesystem;
```
> error: ‘filesystem’ is not a namespace-name
    4 | namespace fs = std::filesystem;

**c_cpp_properties.json：**

> {
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "${default}"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
@jackeykong The error " is not a namespace-name" is not from our C/C++ extension. You can tell because our messages show the "C/C++" source.

**Comment by rizet** [comment]
I have found a solution to this issue, and it may be wise to attempt it.

I, also, had the issue where the C/C++ Visual Studio Code extension was having a squiggly under that line that did not show up in compilation.

In my command line flags, I was compiling with `-std=c++20`.
But in my `.vscode/c_cpp_properties.json`, `"cppStandard"` was set to `"c++14"`. Changing the value to `"c++20"` (or whatever standard you are using, in your case "c++17") resolved the issue.
