### ISSUE TITLE
Using pipeTransport with machinectl doesn't work

### ISSUE THREAD

**Issue by daandemeyer** [microsoft/vscode-cpptools#6686]
Type: Debugger

**Describe the bug**
- OS and Version: Arch Linux
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): Irrelevant
- A clear and concise description of what the bug is.

Using pipeTransport configured as follows doesn't work:

```
"pipeTransport": {
    "pipeCwd": "/usr/bin",
    "pipeProgram": "/usr/bin/machinectl",
    "pipeArgs": ["--quiet", "shell", "image"],
    "debuggerPath": "/usr/bin/gdb",
},
```

The logs print: `"/usr/bin/machinectl" --quiet shell image "/usr/bin/gdb --interpreter=mi"` after which `machinectl exits immediately. 
Launching this command manually via the terminal gives the same results.

**To Reproduce**

See above

**Additional context**

Removing the quotes from the gdb command (`"/usr/bin/machinectl" --quiet shell image /usr/bin/gdb --interpreter=mi`) makes everything work as expected. I suspect the extension should do the same to make machinectl work.

**Comment by DaanDeMeyer** [comment]
Fixed by using `quoteArgs` option
