### ISSUE TITLE
Excluding folders from parsing, but keep them in workspace

### ISSUE THREAD

**Issue by xolom** [microsoft/vscode-cpptools#6692]
I have a relatively big project set up with VSCode and use the C++ Extension for the main source code (which is located in one of multiple root folders in my multi-root workspace). 
There are other important folders which contains generated code with ~600k LOC or more. Intellisense parsing is slowed down massively, because of those generated files.

I noticed that this Extension always parses all root folders inside the workspace, except i exclude it explicitily with `files.exclude`. Unfortunately this also hides those files completely from the user in vscode. 

I'm now searching for a solution to exclude particular files from intellisense parsing, but still have them available inside the vscode workspace

**Comment by sean-mcmanus** [comment]
You should be able to get it to work via using a multi-root workspace, in which one workspace folder has the folders under files.exclude, and the 2nd one has
```
            "includePath": [
            ],
            "browse": {
                "path": []
            },
```
set in the c_cpp_properties.json (or the equivalent C_Cpp.default.* settings).

Let me know if that doesn't work for you.

**Comment by xolom** [comment]
As soon as I set `files.exclude` in `ws_folder1/.vscode/settings.json` for instance, the defined files are hidden in the file explorer.

**Comment by sean-mcmanus** [comment]
Setting files.exclude will hide the files in the current workspace folder, but they'll be available in the 2nd one that doesn't have the files.exclude set (but has the browse.path empty). If that workaround isn't good enough, we'd need to add some other setting (or maybe we could look at watcher.exclude or search.exclude).

**Comment by xolom** [comment]
I'm not sure, if i understand your workaround completely. I think i should explain my setup in more detail.
My workspace looks like this (simplified):
```
ws_folder1  <---  Contains generated code (should NOT be parsed)
├── .vscode
│   └── settings.json  <---  Setting files.exclude to '**/rendered' hides 'rendered'
├── rendered
│   │── rendered_header.h 
│   └── <more rendered files>
ws_folder2  <---  Main source code where intellisense should be active and parsing
├── .vscode
│   └── c_cpp_properties.json
└── main.cpp
```
You could say that `ws_folder1` has nothing to do with `ws_folder2`. The easiest would be to exclude the whole `ws_folder1` workspace folder from intellisense parsing.

> but they'll be available in the 2nd one that doesn't have the files.exclude set 
With second folder I assume you mean now `ws_folder2` in my example. The folder `rendered` only exists in the first folder, so I'm not sure what you mean with available in the second one.

**Comment by sean-mcmanus** [comment]
That scenario is simpler -- can you just set `"C_Cpp.default.browse.path": []` in `ws_folder1/.vscode/settings.json` without settings files.exclude? My previous suggestion would apply if "rendered" was a subfolder of ws_folder2, then ws_folder2 could have a files.exclude and rendered would still be available under ws_folder1.

**Comment by xolom** [comment]
Wow. It is really that simple... That was unexpected. Thank you!
