### ISSUE TITLE
Allow to re-use the `outline` feature for custom extensions

### ISSUE THREAD

**Issue by denis-shienkov** [microsoft/vscode-cpptools#6693]
**Type: LanguageService**

It would be good if somehow it was possible to re-use the `outline` feature from the `cpp-tools` extension and for other custom extensions.

I'm talking, seems, about the following code: https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/Providers/documentSymbolProvider.ts

Because the `outline` feature only present on the base `Explorer` tree-view. But, it is not exists on the custom tree-views (e.g. provided from the custom extensions). In thet case a custom extension should re-implement the `outline` form the scratch, that is very expensive work. 

Maybe it is a reason why this `outline` feature is missing e.g. and on `cmake-tools` extention, which use the `cpp-tools` extension.

**Comment by sean-mcmanus** [comment]
The Outline feature is implemented by VS Code. We just implement the the vscode.DocumentSymbolProvider.

I don't fully understand what the goal of this request is (maybe you could provide some mock up screenshots?), but it sounds like it should be filed at https://github.com/microsoft/vscode/issues since the Outline view and document symbol providers apply to all languages.

**Comment by denis-shienkov** [comment]
Hi @sean-mcmanus ,

> maybe you could provide some mock up screenshots?

Yes, sorry, please look on (I will talk only about the C/C++ languages):

I meant that if we are use the default `explorer` tree, then we can see and the `outline` with the found function names and so on (with the symbols):

![изображение](https://user-images.githubusercontent.com/8415796/102884897-7c223600-4463-11eb-8755-0311ab414a88.png)

But, when we are use the project tree provided by a custom extensions, then we don't see any
`outline` with the symbols (e.g. using the `cmake-tools` extension or any other):

![изображение](https://user-images.githubusercontent.com/8415796/102885508-8133b500-4464-11eb-96cc-9e6e6775fa8a.png)

So, as I understand, that if someone provide a custom extension (e.g. `cmake-tools` or any other),
based (or which are used) on this `cpp-tools` extension, then in this case we need to re-implement 
all `vscode.DocumentSymbolProvider` feature again? If yes, then it is a bit strange way..

**Comment by sean-mcmanus** [comment]
You can drag the Outline view to the CMake: Project Outline -- is that sufficient?

![image](https://user-images.githubusercontent.com/19859882/102916249-17051b00-4438-11eb-8be9-adb588c04da8.png)

**Comment by denis-shienkov** [comment]
@sean-mcmanus , WOW, many thanks. Yes, it is enough, thanks again. :)
