### ISSUE TITLE
Crash on Mac when switching branches

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6695]
This also happens when switching between branches.. the server crashes in versions 0.29 - 1.1.3, maybe in older versions too.
<img width="466" alt="image" src="https://user-images.githubusercontent.com/31617071/102712204-eb632300-42c7-11eb-9390-0155aa489175.png">

_Originally posted by @guyberger in https://github.com/microsoft/vscode-cpptools/issues/6503#issuecomment-748595617_

**Comment by sean-mcmanus** [comment]
@guyberger Are you able to somehow get a crash call stack?

**Comment by guyberger** [comment]
Unfortunately I am not compiling nor running my code in VSCode so I think I won't be able to generate a crash stack.

I use VSCode as an editor, but the server crash happens very often when I switch between branches (these repos are quite large).

**Comment by sean-mcmanus** [comment]
Compiling or running your code on VS Code isn't required. Your OS may have tools that can log crash call stacks to a file. Unfortunately, we don't a walkthrough on how to do that yet, and attaching a debugger to the cpptools process on Mac causes the process to exit (we're tracking that with https://github.com/microsoft/vscode-cpptools/issues/6151 ).
