### ISSUE TITLE
C++ IntelliSense crash in gcc mode (from attach_attributes_to_routine_instance)

### ISSUE THREAD

**Issue by manujgrover71** [microsoft/vscode-cpptools#6698]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 (Build 19041.685)
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): Yes
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- I mostly do Competitive Programming in VsCode and usually copy code from websites like GeeksForGeeks and stackoverflow, but sometimes wherever I paste the code in my cpp file, auto-complete and suggestions no longer work on that paricular file however, in my other cpp files, it works as expected. 

**Steps to reproduce**

1. Create a CPP file.
2. Copy Code from internet
3. Write incomplete code to see error.

**Expected behavior**

Red line should appear at the errors and auto complete should work.

**Screenshots**

In file where I copied Code.
![image](https://user-images.githubusercontent.com/56198659/102866923-036cab00-445e-11eb-92a2-3e10ca9e1dd7.png)
In other cpp files
![image](https://user-images.githubusercontent.com/56198659/102866983-18493e80-445e-11eb-8163-fa64abc74605.png)

**Additional context**

This bug/error started occurring recently, quite a few vscode updates earlier. I searched the net for all the possible solutions to this, but no luck, in the end writing this issue.

**Comment by sean-mcmanus** [comment]
Error squiggles are disabled in the Open File scenario. We require a workspace or folder to be open.

You can upvote the existing feature request at https://github.com/microsoft/vscode-cpptools/issues/3171 .

**Comment by manujgrover71** [comment]
I open my files while I am in a folder.

Can you please clarify one doubt here? Whenever I start my vscode, It opens in the folder where I last closed it with my files loaded and to be worked upon. Does this count as a single file opening or a folder opening? All the files are in a folder though.

**Comment by sean-mcmanus** [comment]
Yeah, that sounds like Open Folder. What is your errorSquiggles setting? What is the result of running C/C++: Log Diagnostics after opening a C++ file?

**Comment by manujgrover71** [comment]
In the settings.json file, "**C_Cpp.errorSquiggles**" is set as "**Enabled**".

C/C++: Log Diagnostics result:
```
-------- Diagnostics - 24/12/2020, 10:00:09 am
Version: 1.1.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "C:\\boost_1_74_0\\**",
        "C:\\boost_1_74_0\\boost\\**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\MinGW-64\\mingw32\\bin\\gcc.exe",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "C:\\boost_1_74_0\\**",
            "C:\\boost_1_74_0\\boost\\**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ E:\AtomCodes\E_Enemy_is_weak.cpp ]:
    E:\ATOMCODES\E_ENEMY_IS_WEAK.CPP
[ E:\AtomCodes\Codeforces\a.cpp ]:
    E:\ATOMCODES\CODEFORCES\A.CPP
Translation Unit Configurations:
[ E:\AtomCodes\E_Enemy_is_weak.cpp ]:
    Process ID: 17960
    Memory Usage: 0 MB
    Compiler Path: C:\MinGW-64\mingw32\bin\gcc.exe
    Includes:
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE\C++
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE\C++\I686-W64-MINGW32
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE\C++\BACKWARD
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE-FIXED
        C:\MINGW-64\MINGW32\I686-W64-MINGW32\INCLUDE
        C:\BOOST_1_74_0\TOOLS\BUILD\SRC\ENGINE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++17
    IntelliSense Mode: gcc-x86
    Other Flags:
        --g++
        --gnu_version=80100
[ E:\AtomCodes\Codeforces\a.cpp ]: not ready
    Process ID: 17524
    Memory Usage: 0 MB
    Compiler Path: C:\MinGW-64\mingw32\bin\gcc.exe
    Includes:
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE\C++
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE\C++\I686-W64-MINGW32
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE\C++\BACKWARD
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE
        C:\MINGW-64\MINGW32\LIB\GCC\I686-W64-MINGW32\8.1.0\INCLUDE-FIXED
        C:\MINGW-64\MINGW32\I686-W64-MINGW32\INCLUDE
        C:\BOOST_1_74_0\TOOLS\BUILD\SRC\ENGINE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++17
    IntelliSense Mode: gcc-x86
    Other Flags:
        --g++
        --gnu_version=80100
Total Memory Usage: 0 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 81254
Number of files discovered (not excluded): 70772
```

I want to add one more thing here, that I just noticed, whenever this happens(red lines and autocomplete stops working), in the output window of vscode, there appear "**Failed to read response from server: RANDOM NUMBER**", here the random number can be 4, 8 or 20.

**Comment by sean-mcmanus** [comment]
"Failed to read response from server" means our IntelliSense parser is crashing (cpptools-srv.exe). Can you attach a debugger to cpptools-srv.exe (see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv ) to get a crash call stack.

Or can you provide a code sample that causes the crash?

Also, it's possible our most recent build at https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-preview has fixed the crash (the crash error message is different with that build).

**Comment by manujgrover71** [comment]
I tried attaching the debugger to cpptools-srv.exe but messed up something and now when I try it again, there is no "cpptools-srv.exe" in the list anymore.

But I can provide you the code on which this happens:
```c++
#pragma GCC optimize("Ofast,unroll-loops")
#pragma GCC target("avx,avx2,sse,sse2")
#include <bits/stdc++.h>
using namespace std;
#define ll long long
#define mod 1000000007
#define pi 3.141592653589
#define mxsize (int)3e5
#define pb push_back
#define nl cout << "\n"
#define db(x) cout << x << " "
#define fi(a, b) for (int i = a; i < b; i++)
#define fj(a, b) for (int j = a; j < b; j++)
#define fk(a, b) for (int k = a; k < b; k++)
#define F first
#define S second

ll fastexp(ll a, ll n, ll nod = LLONG_MAX) {
    ll ans = 1;
    while (n) {
        if (n & 1)
            ans = (ans * a) % nod;
        a = (a * a) % nod;
        n >>= 1;
    }
    return ans;
}

vector<ll> t, cost;
vector<vector<ll>> dp;
int n;

ll help(int ind, int time) {

    if (ind == -1) {
        if (time < 0)
            return LLONG_MAX;
        return 0;
    }

    if (time >= ind + 1)
        return 0;
        
    if (time < 0 && abs(time) > ind)
        return LLONG_MAX;

    if (time >= 0 && dp[ind][time] != -1)
        return dp[ind][time];

    ll ans = LLONG_MAX;
    
    ans = min(ans, help(ind - 1, time - 1));
    ans = min(ans, cost[ind] + help(ind - 1, t[ind] + time - 1));
    
    if (time >= 0)
        return dp[ind][time] = ans;
    else
        return ans;
}

void fun() {
    dsadasdas // vscode should show error here.
    cin >> n;
    
    cost = t = vector<ll>(n + 1, 0);
    dp = vector<vector<ll>>(n + 1, vector<ll>(n + 1, -1));
    
    fi(0, n) {
        cin >> t[i] >> cost[i];
    }
    cout << help(n - 1, 0) << "\n";
}

int main() {
    int t = 1;
    // cin>>t;
    while (t--) {
        fun();
    }
}
```

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've reported the crash against our shared VS parser at https://developercommunity.visualstudio.com/content/problem/1297976/c-intellisense-crash-with-linux-gcc-mode-in-attach.html .

**Comment by Rajan-226** [comment]
Hey @sean-mcmanus , is there any progress regarding this issue?

**Comment by sean-mcmanus** [comment]
No fix yet, but it seems like the same crash as https://github.com/microsoft/vscode-cpptools/issues/7377, which has a bug filed against our parser.

As workaround is to use

```
#ifndef __INTELLISENSE
#pragma GCC target("avx,avx2,sse,sse2")
#endif
```

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders2
