### ISSUE TITLE
Add includePath for OS X/iOS frameworks?

### ISSUE THREAD

**Issue by jjgod** [microsoft/vscode-cpptools#67]
How do I add `includePath` to find headers like `<CoreFoundation/CoreFoundation.h>` with OS X/iOS SDK? I haven't found a way yet.

<img width="349" alt="screen shot 2016-06-09 at 1 57 17 pm" src="https://cloud.githubusercontent.com/assets/1017/15920125/2b0366f6-2e4a-11e6-9479-8a8e79e369d0.png">

**Comment by sridmad** [comment]
See Specifying Additional Include Directories for Better Symbol Support. in https://code.visualstudio.com/docs/languages/cpp

**Comment by jjgod** [comment]
@sridmad It doesn't solve my problem, Framework directory structure is not possible to express in `includePath`, as I clearly stated in my original comment. Please re-open this.

**Comment by sridmad** [comment]
We will have to add the capability to specify frameworks. For the short term, if you add path to the root of the framework folder the headers should be picked up. This is ofcourse not feasible as a long term solution.
Example: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework"

**Comment by jjgod** [comment]
Awesome, that's good enough for me. I will try this. Thanks!
