### ISSUE TITLE
Using Clang Diagnostics

### ISSUE THREAD

**Issue by rdlaner** [microsoft/vscode-cpptools#670]
I just started using this extension and it has been working wonderfully for auto-completion. However, I am not able to get it to work for any kind of clang diagnostics. All the diagnostic settings are at their default values:
  // Enable diagnostic
  "clang.diagnostic.enable": true,

  // The delay after which diagnostic starts (in millisecond)
  "clang.diagnostic.delay": 500,

  // Tolerable size of the clang output for diagnostic
  "clang.diagnostic.maxBuffer": 262144,

I've also updated the clang.cflags setting to the following:
`"clang.cflags": ["-std=c99", "-Wall"]`

Is there anything else I need to do in order to get diagnostics working?
Thanks!

**Comment by sean-mcmanus** [comment]
You should file an issue at https://github.com/mitaki28/vscode-clang/issues . This is for cpptools issues.
