### ISSUE TITLE
Suggestion: add textmate scope info to distinguish between integers and reals

### ISSUE THREAD

**Issue by xaxazak** [microsoft/vscode-cpptools#6700]
**Type: LanguageService**

I suggest adding scopes to disambiguate between integers and reals, such as:
* constant.numeric.decimal.cpp.integer
* constant.numeric.decimal.cpp.real

Allowing different highlighting for integers and reals can help to avoid type-mismatch issues.

**Comment by sean-mcmanus** [comment]
Our extension doesn't provide lexical scopes. I think you'd want to file an issue with https://github.com/jeff-hykin/cpp-textmate-grammar/issues , which is where the VS Code C++ lexical scopes are inherited from.

**Comment by xaxazak** [comment]
Issue filed here: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/525
