### ISSUE TITLE
Away for Christmas Eve and Christmas Day holidays

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6706]
...back on the 28th (although others on our team won't be back till the following week).

In the mean time, consider trying https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-preview to see if it has fixed your issue and/or report regression bugs with that release so we can prioritize fixing those for our next 1.2.0-insiders release in January.

**Comment by heartacker** [comment]
merry Christmas

**Comment by moe123** [comment]
You are already vacationing; everyday since a year. Engineering ain't the post-office.
