### ISSUE TITLE
how to disable syntax highlight in VSCode?

### ISSUE THREAD

**Issue by neuromagus** [microsoft/vscode-cpptools#6708]
I want work in monochrome editor. How disable syntax highlight? And plugin, who coloring my code (TextMate)?

**Comment by sean-mcmanus** [comment]
You should search for a Theme extension in the Marketplace:

![image](https://user-images.githubusercontent.com/19859882/103240899-7070bc80-4906-11eb-9a88-e96aac2f1096.png)
