### ISSUE TITLE
cpptools-srv just spins using 100% CPU and renders IntelliSense not working

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode-cpptools#6709]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.10
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.2.0-preview
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes, I run VS Code Remote SSH extension
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The following combination of ranges, concepts and coroutines makes cpptools-srv process consume 100% CPU and no IntelliSense features work. If I close VS Code process is still hanging around (together with its parent process):

```c++
    auto count = ranges::count_if(contents,
                                  [&](MediaObject const& object) -> bool {
                                      return serialize(didl_root, content_base, object);
                                  });
```

If I comment it out, everything works. As soon as I uncomment - same picture.

I think (hope?) this can be reproduced on this snippet (I ran with gcc -E to produce a single file) around line 60:

[repro.zip](https://github.com/microsoft/vscode-cpptools/files/5741146/repro.zip)

1.1.3 can parse the file but crashes when trying to invoke IntelliSense (due to coroutines).

**Comment by ytimenkov** [comment]
Fortunately this can be guarded with  `#if __INTELLISENSE__ == 1`.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. We'll be looking into it...

**Comment by sean-mcmanus** [comment]
Update: The issue only repros when our compiler runs in gcc mode (i.e. not in clang mode), although the code doesn't compile 100% with clang. And it doesn't repro with VS because VS doesn't run in gcc mode, so I need to hear back from the VS IntelliSense compiler developer when he gets back next week...

**Comment by ytimenkov** [comment]
I think I distilled this to the minimal example:
```c++
#include <range/v3/view/facade.hpp>
#include <string>

class list_result_view : public ranges::view_facade<list_result_view>
{
public:
    explicit list_result_view(std::vector<std::string>&& objects)
        : objects_{std::move(objects)}
    {
    }

private:
    friend ranges::range_access;

    class cursor
    {
    public:
        cursor() noexcept = default;
        explicit cursor(std::vector<std::string>::const_iterator key_it) noexcept
            : key_it_{key_it} {}

        auto read() const -> std::string const&;

        auto next() noexcept -> void
        {
            ++key_it_;
        }

        auto prev() noexcept -> void
        {
            --key_it_;
        }

        auto equal(cursor const& other) const noexcept -> bool
        {
            return key_it_ == other.key_it_;
        }

        auto distance_to(cursor const& other) const
        {
            return ranges::distance(key_it_, other.key_it_);
        }

        auto advance(ranges::iter_difference_t<std::vector<std::string>> n) noexcept -> void
        {
            return ranges::advance(key_it_, n);
        }

    private:
        std::vector<std::string>::const_iterator key_it_{};
    };

    auto begin_cursor() const { return cursor{objects_.begin()}; }
    auto end_cursor() const { return cursor{objects_.end()}; }

    std::vector<std::string> objects_;
};

void foo(list_result_view const list)
{
    auto const size = ranges::size(list);
    // ^^^ This line causes intellisense to spin.
}

int main()
{
    return 0;
}
```
```json
{
  "directory": "/home/dev/eems/build/dev",
  "command": "/usr/bin/g++-10 -D_GLIBCXX_USE_CXX11_ABI=1 -isystem /home/dev/.conan/data/range-v3/0.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -Og -g -Werror -Wall  -m64 -fdiagnostics-color -fconcepts-diagnostics-depth=2 -std=c++2a -o src/CMakeFiles/repro.dir/repro.cpp.o -c /home/dev/eems/src/repro.cpp",
  "file": "/home/dev/eems/src/repro.cpp"
},
```

I've tried this snippet at Compiler Explorer and it compiles with both gcc and clang (msvc seems to have issues finding ranges library).

**Comment by sean-mcmanus** [comment]
@ytimenkov Thanks for the simplified repro -- that could help our investigation. Our IntelliSense parser expert is looking into a fix or workaround now (potentially for 1.2.0-insiders).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2 -- but our "fix": was just a workaround to bail out of the loop after too many iterations (i.e. after a second or so), which turned out to not be infinite but something like exponential time processing, due to a bug in our parser that we're awaiting a proper fix for still. I'm not aware of any bug that results from the unideal workaround, but there could be something incorrect in regards to constraint checking being incorrect.

**Comment by ytimenkov** [comment]
> but our "fix": was just a workaround to bail out of the loop after too many iterations 

Thank you anyways. It is still much better because hanging language server blocks everything else: code formatting during save, intellisense in other files.
