### ISSUE TITLE
C++ highlighting fails detecting quotes like '\"' or single " in comments

### ISSUE THREAD

**Issue by gajanak** [microsoft/vscode-cpptools#671]
Using  `'\"' ` in Code will begin highlight all following code as an String literal.

```cpp
void foo()
{
  auto bar =  '\"';
  //this is code but is marked in editor as continued string because \" is interpreted as start of a string

  //this " in a comment is also interpreted as begin or end of a string, instead of ignored because its an comment
}
```

Expect:  formating like in Code box above
Saw:  from \" until " in comment is highlighted as string

Please ask, if it's not clear what I mean, or more information are needed.

---
- VSCode Version: Code - Insiders 1.12.0-insider (5590786c2f676ca2aee12b16cd01b4e0ac621984, 2017-04-20T08:39:52.610Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.0|

With disabled Extension, highlighting is working.

**Comment by sean-mcmanus** [comment]
I'm not able to repro the bug. Our extension doesn't implement any keyword colorization, so it doesn't make sense why the behavior would change when disabling our extension. Can you update your VS Code - Insiders version? You're using a week old one.

**Comment by bobbrow** [comment]
I don't see any problems in the latest versions of VS Code and the C/C++ extension either.
