### ISSUE TITLE
Inconsistency between LS and GCC regarding std::basic_string_view's constructor taking iterators pair with C++20

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode-cpptools#6712]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.10
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.2.0-preview
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes, I'm using remote ssh on Linux
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
```c++
#include <string>

int main()
{
    std::string s;
    std::string_view v{s.begin(), s.end()};
    // And from cpp-reference
    std::array ar = {'P', 'u', 'b'};
    std::string_view ar_v{ar.begin(), ar.end()};
}
```
Compiles successfully in C++20 mode (/usr/bin/g++-10 -std=c++20).
However Intellisense gives following warning:
```
no instance of constructor "std::basic_string_view<_CharT, _Traits>::basic_string_view [with _CharT=char, _Traits=std::char_traits<char>]" matches the argument list -- argument types are: (__gnu_cxx::__normal_iterator<char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, __gnu_cxx::__normal_iterator<char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>)C/C++(289)
```

Given that the second constructor overload doesn't issue a problem it may be that std::basic_string::const_iterator doesn't model the concept `std::contiguous_iterator`. Not sure who's right but it would be definitely easier if both compilers behave the same.

Originally the case was when I needed to construct a `std::string_view` from `std::sub_match` (maybe LWG should consider inheriting it from a view rather than a pair 😊).

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug against our shared VS parser at https://developercommunity.visualstudio.com/content/problem/1297507/c-intellisense-gives-a-no-instance-of-constructor.html .

**Comment by Colengms** [comment]
I'm not able to repro this issue.  If I use gcc 10.2, which can compile the code, and see that the TU has been configured with `--gnu_version=100200` having successfully queried the compiler, and I do not get any squiggles.  If I switch to gcc 9.3, I see squiggles, but the compiler also reproduces those errors when compiling.

It looks like Sean opened an issue against VS for clang mode IntelliSense.  Given that the behavior differs for gcc based on its version, I think that is a separate issue.

@ytimenkov Can you provide more information on how you are configuring the extension?  This should work if you specify gcc-10 in your compiler path.  If you did not, and it was picking up gcc 9 by default, that would explain the error.

**Comment by ytimenkov** [comment]
Good question...

There is something in your research 😊. Iirc at that time I had ubuntu 20.04 with gcc version 9 by default in system path and was using gcc 10 to compile my code.
I use compile_commands.json produced by cmake. But I noticed that sometimes LS behaves strangely as if mixing up information from compile commands and system-wide discovery.

I do not remember whether mini repro was standalone or a part of my project with compile commands 🙁.

You may close this issue if it looks like fixed.
