### ISSUE TITLE
C++ Warnings are not parsed

### ISSUE THREAD

**Issue by pdrap** [microsoft/vscode-cpptools#6716]
When the C++ compiler generates an error, it is reported in the problems pane and is noted in the code with a squiggle. When the compiler generates a warning, it is completely ignored. I can't see it in the problems pane, or in the code marked with a squiggle.

If I go to the command line and type make, I see all my warnings. This is not a compiler flag problem. Also, if I install the clangd plugin, the warnings are recognized and parsed by that extension correctly.

**Comment by sean-mcmanus** [comment]
Compiler generated warnings are created in the Problems window via problemMatchers in tasks.json, e.g.
![image](https://user-images.githubusercontent.com/19859882/103301965-5c38c800-49b7-11eb-8d6f-5ba95917afcb.png)

If the errors you see generated have "C/C++" as the source, then you're hitting the fact that our IntelliSense engine doesn't currently report warnings, which is being tracked by https://github.com/microsoft/vscode-cpptools/issues/828 .

Does that address your issue?

**Comment by pdrap** [comment]
I think that does address the issue. I have switched to the clangd plugin and language server for now. Thank you very much.
