### ISSUE TITLE
compiler path not used from compile_commands.json

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode-cpptools#6717]
**Type: LanguageService**

I am pretty sure the compiler path is not taken from the compile_commands.json file. What do I need to provide to you here to see if my suspicion is correct?

**Comment by sean-mcmanus** [comment]
Do you have compilerPath set? That could be overriding the compiler set in compile_commands.json. You can find more info via running C/C++: Log Diagnostics.

**Comment by BMBurstein** [comment]
No. compilerPath was not set and I was getting al kinds of intellisense errors and mistakes. I manually set compilerPath and everything started working great.

**Comment by sean-mcmanus** [comment]
It sounds like something is causing the compiler to get not picked up in compile_commands.json. If you set C_Cpp.loggingLevel to "Debug" the "C/C++" logging pane might show info on what error is causing the compiler to to get picked up. Or if you could provide an example of the command that is being used in compile_commands.json that might help identify what is going wrong. It could be we're not handling some argument correctly.

@Colengms might have more thoughts on what could be going wrong (when he gets back).

**Comment by Colengms** [comment]
Hi @BMBurstein .  Are you still seeing an issue with the latest version (currently 1.2.0) ?  If we're unable to query the specified compiler for system includes and system defines, we will try to fall back to a compiler found on the system, or none if none found.  I suspect what you were seeing was a failure to query the compiler.  If so, the failed command line should be mentioned in the logs.
