### ISSUE TITLE
Include file not found despite (seemingly) valid includePath

### ISSUE THREAD

**Issue by darvid** [microsoft/vscode-cpptools#672]
I'm running Code on Windows 10, and trying to add WSL lxss paths to includePath but it doesn't appear to work, despite the paths being correct:

```
            "includePath": [
                "${workspaceRoot}",
                "C:/Users/dave/AppData/Local/lxss/rootfs/usr/include",
                "C:/Users/dave/AppData/Local/lxss/rootfs/usr/local/include",
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0/um",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0/shared",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0/winrt"
            ],
```

Is there any reason this shouldn't work?

**Comment by sean-mcmanus** [comment]
What is the error message exactly? It sounds like you also need to set the browse.path.

includePath is used when the intelliSenseEngine is set to Default and should match the compiler, and the browse.path is the path where you want symbols to be searched.

**Comment by darvid** [comment]
Oh wow, I didn't realize. Setting browse.path worked. Apologies for the noise, and thanks.
