### ISSUE TITLE
Autocompleting indirect struct attributes with multiple cursors converts '.' to '.>' instead of '->'

### ISSUE THREAD

**Issue by nmay231** [microsoft/vscode-cpptools#6720]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.1.5
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

NOTE: Please let me know if I'm using the phrase "indirect struct attribute" incorrectly; I'm relatively new to the c-lang world. By "indirect struct attribute" I am referring to accessing the struct attribute by a pointer to a struct, e.g. `indirect->attribute` as opposed to `direct.attribute`.

When using multiple cursors, autocompleting indirect struct attributes changes the period `.` to a partial arrow `.>` instead of `->`. For example, I type `my_struct.at` with multiple cursors, I press `tab` to autocomplete, and I get `mystruct->attribute` for the first cursor, but `mystruct.>attribute` for any subsequent ones. See the screenshot for this example.

Note that typing `->` for each structure and THEN using autocomplete works as expected. It is only when you use `.`

**Steps to reproduce**

1. Create and save a file with the following content:
```c

struct my_struct {
    int attr;
};

int main() {
    struct my_struct *a;
    a;
    a;
    a;
}
```
2. Select the first `a` and use `ctrl-d` to select the other two with multiple cursors.
3. Type a `.` after the `a` and autocomplete `attr`.

**Expected behavior**

I expect ALL periods (`.`) to convert to arrows (`->`).

**Screenshots**

![vscode_c_extension_autocomplete](https://user-images.githubusercontent.com/35386821/103259871-72fc0200-4958-11eb-8d13-d681c605cb69.png)

**Comment by sean-mcmanus** [comment]
This appears to be a bug or design problem with VS Code itself. When you type . and invoke the completion, we're only getting 1 completion request for the 1st cursor position and we return an "additionalEdit" of "-" and an insertText of ">attr", but VS Code replicating the insertText. Can you file a bug on VS Code at https://github.com/microsoft/vscode/issues ? I don't see any means for our extension to handle this correctly. We need to be sent a completion request for every cursor position. In other cases, the cursors could be on different variables that have different completion results.

**Comment by nmay231** [comment]
Issue being tracked in microsoft/vscode#113551. Will update this one if resolved or updated with correct approach.

Also, must have had dyslexia when writing my vscode version :eyes: . It's 1.52.1

**Comment by nmay231** [comment]
@sean-mcmanus 
I reviewed the LSP. Wouldn't changing the range of the [`textEdit`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textEdit) option suffice instead of using `additionalTextEdits`? You can use a range that overrides the period when adding `->` and that should work for each cursor, right? Let me know if I'm missing something.

**Comment by sean-mcmanus** [comment]
textEdit is deprecated, but using it doesn't work anyway, because it ignores any textEdit with a Range that is before the completion invocation position (i.e. the dot). Using insertText with a "range" also doesn't work -- VS Code ignores a range before the period. I don't know if that's a VS Code bug or not.

**Comment by nmay231** [comment]
Gotcha

**Comment by nmay231** [comment]
@sean-mcmanus I'm assuming this issue will be closed automatically as soon as the release is put out?

**Comment by nmay231** [comment]
Eh, I'll just close it now. Thanks again!

**Comment by sean-mcmanus** [comment]
@nmay231 
1. If we decide to release a 1.2.0-preview2, the fix be available at  https://github.com/microsoft/vscode-cpptools/releases with no announcement (i.e. to limit the audience).
2. After we release 1.2.0-insiders we'll post to this issue saying the fix is available.
3. We usually would only close an issue until the fix is available in 1.2.0, but you could close it if you want (VS Code's and GitHub's general policy is to close when it's fixed internally)...to close or not to close is up to debate.

**Comment by nmay231** [comment]
Okay, I'll reopen to try to limit duplicate issues in case someone else happens upon the bug. :+1:

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
