### ISSUE TITLE
Incorrect IntelliSense error "no suitable user-defined conversion"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6721]
I also encountered this issue

<img width="1014" alt="Screen Shot 2020-12-28 at 12 56 31 AM" src="https://user-images.githubusercontent.com/66742822/103175777-8bf8aa80-48a7-11eb-8d1e-634a974abf19.png">

[The whole project can be seen here](https://github.com/xsw0/Bignum/blob/97ea7160d0d7cd5bd6602c8aa799c2132f1c6608/Bignum_Arithmetic.cpp#L100)

OS : macOS 10.15.7
VS Code version : 1.52.1
C/C++ Extension Version: 1.1.3

After closing all other extensions and restarting vscode, the issue still exists.
The incredible thing is that when I turned off the VPN, the issue disappeared.

_Originally posted by @xsw0 in https://github.com/microsoft/vscode-cpptools/issues/6222#issuecomment-751490557_

**Comment by sean-mcmanus** [comment]
Might be related to https://github.com/microsoft/vscode-cpptools/issues/6372 . I'll check...

**Comment by sean-mcmanus** [comment]
@xsw0 What compiler and version are you using? I get the compiler error
`error: constructor cannot be redeclared
    Bignum(size_t n) : Bignum(static_cast<uint64_t>(n)) {}`
and
`error: 'Bignum::Bignum(size_t)' cannot be overloaded with 'Bignum::Bignum(uint64_t)'
  270 |     Bignum(size_t n) : Bignum(static_cast<uint64_t>(n)) {}`

I've filed an IntelliSense bug for "too many recursive comparison rewrite operations" at https://developercommunity.visualstudio.com/content/problem/1297998/c-intellisense-in-linux-gcc-mode-with-c20-and-oper.html .

**Comment by xsw0** [comment]
> @xsw0 What compiler and version are you using? I get the compiler error
> `error: constructor cannot be redeclared Bignum(size_t n) : Bignum(static_cast<uint64_t>(n)) {}`
> and
> `error: 'Bignum::Bignum(size_t)' cannot be overloaded with 'Bignum::Bignum(uint64_t)' 270 | Bignum(size_t n) : Bignum(static_cast<uint64_t>(n)) {}`
> 
> I've filed an IntelliSense bug for "too many recursive comparison rewrite operations" at https://developercommunity.visualstudio.com/content/problem/1297998/c-intellisense-in-linux-gcc-mode-with-c20-and-oper.html .

Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.6.0
In my environment, without adding this overloaded function, the compiler will prompt 
```
main.cpp:49:35: error: ambiguous conversion for functional-style cast from 'size_t' (aka 'unsigned long') to 'Bignum'
```
My complete vs code c++ configuration can be seen [here](https://github.com/xsw0/vscode/tree/fec28e51a568c9514babceb96f5bab5ae2523242/CodeLLDB_C%2B%2B/.vscode)

**Comment by sean-mcmanus** [comment]
I don't get any error with Apple clang 12. Are you able to upgrade to that? The 11.0.3 headers might have some issue with C++20.

**Comment by xsw0** [comment]
> I don't get any error with Apple clang 12. Are you able to upgrade to that? The 11.0.3 headers might have some issue with C++20.

I did not find a way to upgrade to clang12. Is it really released? Or I need to upgrade macOS to 11.1 to get it

**Comment by sean-mcmanus** [comment]
You don't need to update your OS to 11.1, just update XCode: developer.apple.com/support/xcode/

**Comment by xsw0** [comment]
> You don't need to update your OS to 11.1, just update XCode: developer.apple.com/support/xcode/

I updated the version
<img width="408" alt="Screen Shot 2021-01-07 at 7 46 23 AM" src="https://user-images.githubusercontent.com/66742822/103833649-7318a200-50bc-11eb-86b1-3ef1d0dc39f5.png">
This issue still occurs
<img width="772" alt="Screen Shot 2021-01-07 at 7 44 14 AM" src="https://user-images.githubusercontent.com/66742822/103833685-904d7080-50bc-11eb-93e3-f8e505c45945.png">

**Comment by sean-mcmanus** [comment]
Ah, okay -- I was able to somehow get a repro via making some edits and I also noticed it shows `Term(<error-type> exp` on hover.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug against our shared VS parser at https://developercommunity.visualstudio.com/content/problem/1303152/c20-intellisense-in-linux-gcc-mode-and-using-sint.html (the root error is the "sint" type is somehow not getting seen as defined).

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
