### ISSUE TITLE
ipch folder might end up inside the workspace root instead of intelliSenseCachePath

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6723]
@Colengms Hi! Didn't have a chance to test if intellisense works for nested roots. Since then I've been using a slightly different approach as a workaround, and thus don't see the issue in question:

instead of putting projects inside a workspace
```
- repository folder and workspace root
- - projects roots
```

... they are put at the same level with it
```
- repository folder
- - workspace root
- - projects roots
```

... which makes the extensions satisfied and decouples responsibilities quite nicely. An issue with rerouting `C_Cpp.intelliSenseCachePath` rises sometimes: despite the setting I have, `ipch` folder might end up inside the workspace root instead of a target path. Quite a minor nuisance anyways.

[repository is here](https://github.com/Feacur/CustomEngineStudy)

![image](https://user-images.githubusercontent.com/1132582/103190940-09daa700-48e4-11eb-92b5-cd05113227ad.png)

_Originally posted by @Feacur in https://github.com/microsoft/vscode-cpptools/issues/2930#issuecomment-751577519_

**Comment by sean-mcmanus** [comment]
@Feacur I see some code that could cause the symptom described. Any more definitive repro steps would be helpful though.

**Comment by sean-mcmanus** [comment]
@Feacur The intelliSenseCachePath in the multi-root scenario isn't valid at the workspace folder scope. Are you setting it at the workspace scope? With the workspace intelliSenseCachePath set to `${workspaceFolder}/.vscode/ipch3` I'm seeing ipch files get created on different folders depending on which file is opened. Let me know if you have more repro steps.

**Comment by Feacur** [comment]
lately I've been putting it like `${workspaceFolder:__ workspace __}/../bin-int` in the `*.code-workspace` file, expecting something along the lines of:
```
- repository root
- __ workspace __
- - .vscode
- - *.code-workspace
- bin-int
- - ipch
- other project folders
- - .vscode
- any other folders
```

however, `ipch` folder, as I've mentioned, sometimes might be found inside the `__ workspace __` folder regardless

**Comment by sean-mcmanus** [comment]
Do you know how to trigger the bug? I tried your setup, but it's not reproing for me. Are you opening certain files or changing certain settings/configurations?

**Comment by Feacur** [comment]
No, don't think so: if I recall correctly, all I did was open a workspace. The thing happened several times a while ago, but I encounter none currently. In the end this broke nothing and did nothing aside from catching my eye.
