### ISSUE TITLE
8GB of Cache files in $XDG_CONFIG_HOME #113421

### ISSUE THREAD

**Issue by AlanRosenthal** [microsoft/vscode-cpptools#6725]
Also posted here: https://github.com/microsoft/vscode/issues/113421

- VSCode Version: 
```
code -v      
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
```
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Running Ubuntu 20.04 and I checked my disk usage.
Looks like there are lots of cache files from the cpptools extension.
A) There's multiple folders of cache files, is this expected?
B) Cache files are in **XDG_CONFIG_HOME** and not **XDG_CACHE_HOME**

![image](https://user-images.githubusercontent.com/1288897/103137726-66965180-4699-11eb-9a66-4e1165dfd443.png)

**Comment by sean-mcmanus** [comment]
This is configured via intelliSenseCacheSize, which defaults to 5 GB. You can set it to 0 to clear it out. Does that solve your issue?

**Comment by AlanRosenthal** [comment]
Cache files should not be saved in ~/.config they should be in ~/.cache

**Comment by sean-mcmanus** [comment]
Ah, sorry, I didn't catch that -- yeah, I think you're seeing the databaseFilename storage and not the ipch storage and the 8 GB is probably "by design". You can change the default storage location for the database file setting C_Cpp.default.databaseFilename to "${workspaceFolder}/.vscode/vc.db" to verify that the .config location is no longer used. We're using the VS Code workspace storage location. There's a related thread at https://github.com/Microsoft/vscode/issues/22557 .

**Comment by sean-mcmanus** [comment]
Did you have some suggestion for a change in behavior? I believe the folders have database files that are created when workspace folders are opened. They are safe to delete...they'll just get rebuilt.

**Comment by AlanRosenthal** [comment]
> They are safe to delete...they'll just get rebuilt

Based on the definitions here: https://wiki.archlinux.org/index.php/XDG_Base_Directory#User_directories I think it makes sense to put these files in either `XDG_CACHE_HOME` or `XDG_DATA_HOME`.

As for the logistics of changing the location of storage, I'm not familiar workings of the inner workings of vscode, but it might make sense to create a new variable `${workspaceCacheFolder}` for use cases exactly like this

**Comment by sean-mcmanus** [comment]
Your suggestion sounds good to me -- it's being tracked in VS Code by https://github.com/microsoft/vscode/issues/3884 and has 303 upvotes so far.
