### ISSUE TITLE
lldb macos bundle

### ISSUE THREAD

**Issue by ajax16384** [microsoft/vscode-cpptools#6726]
Type: Debugger

**Describe the bug**
- OS and Version: 11.1
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.2

I want be able to launch macos app bundle through vscode:

````json
{
            "name": "LLDB Test",
            "type": "cppdbg",
            "request": "launch",
            // "program": "${workspaceFolder}/Test.app/Contents/MacOS/test", // OK
            "program": "${workspaceFolder}/Test.app", // Fails
}
````

Command line lldb allows to launch debug session with bundle directory specified as argument:
lldb ./Test.app

VSCode fails to start with error dialog:
"launch: program '/Users/username/Test.app' does not exist"

Debug console is empty (it seems "program exist" check prevents lldb start).

**Comment by WardenGnaw** [comment]
The debugger uses `lldb-mi` to communicate to lldb. So the entry point is different from `lldb ./Test.app`, we use `-file-exec-and-symbols` to point lldb to the executable file. 

To help us further investigate can you share the logs from the developer console when you add the following to your launch.json?
```
"logging": {
    "traceResponse": true,
    "engineLogging": true
}
```

**Comment by ajax16384** [comment]
- If "program" points to "${workspaceFolder}/Test.app" then debug session simply unable to start due system dialog:
"launch: program 'yadayada/Test.app' does not exist".
(Just as i already mentioned - "debug console" is empty even if all "logging" options are enabled).

- If "program" points to full executable path "${workspaceFolder}/Test.app/Contents/MacOS/test" then debug launches without problem. But it's inconvient to specify full name cause console lldb can deal only with short one (without /Conents/MacOS/*).

- Thanks for describing "-file-exec-and-symbols" command. I have made following experiment:
````bash
pwd
yadayada/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/lldb-mi/bin

./lldb-mi
(gdb)
-file-exec-and-symbols /Applications/VLC.app
^done
(gdb)
=library-loaded,id="/Applications/VLC.app/Contents/MacOS/VLC",target-name="/Applications/VLC.app/Contents/MacOS/VLC",host-name="/Applications/VLC.app/Contents/MacOS/VLC",symbols-loaded="0",loaded_addr="-",size="20480"
````

As You can see it can deal with "short" application path, so if "cppdbg" will loose "program" param validation for file existense (only for lldb variant?) then it would be possible to specify only short app bundle path to perform debug.

**Comment by WardenGnaw** [comment]
Thanks for testing the `-file-exec-and-symbols`. 

The issue is that we check to see if the file exists, but the `.app` extension should be treated as a directory if we are on macOS and using lldb.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
