### ISSUE TITLE
Outline does not work if folder ends with 'app'

### ISSUE THREAD

**Issue by fjordan2020** [microsoft/vscode-cpptools#6727]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 (10.0.16299.431)
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): none
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

In a project with a folder which ends with 'app' (e.g. bug_app), the outline shows 'No symbols found in document'; if the folder is renamed to anything different (e.g., bug_app->bug_appl), the outline is correct.

**Steps to reproduce**

Create a small project as shown in the first half of the figure and open it in VS Code: no outline.

Close and change the folder name from bug_app to bug_appl as shown in the second half of the figure; open it in VS Code: outline is correct.

NOTE: This did not occur with VS Code for MAC, V 1.48.2, C/C++ Extension V 1.0.1.

**Expected behavior**

See above and image below.

<details>
  <summary><strong>Logs</strong></summary>

**This log is for the correct operation ('bug_appl' folder name); differences are indicated with '<--'**
```
cpptools/didChangeCppProperties
Code browsing service initialized
MSVC intelliSenseMode specified.  Configuring for compiler cl.exe.
MSVC intelliSenseMode specified.  Configuring for compiler cl.exe.
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.16.27023/ATLMFC/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.16.27023/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/CPPWINRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/SHARED/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UCRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UM/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/WINRT/ will be indexed
  Folder: C:/VSCODE_FOLDER_NAME_BUG/ will be indexed
textDocument/didOpen: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c
Populate include completion cache.
Discovering files...
cpptools/activeDocumentChange: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c (id: 2)
cpptools/getCodeActions: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c (id: 3)
cpptools/getDocumentSymbols
  tag parsing file: C:\VSCODE_FOLDER_NAME_BUG\MOD\BUG_APPL\DMI_MAIN_TASK.C                          <-- this line does not appear when folder is BUG_APP
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.16.27023/ATLMFC/INCLUDE
  Processing folder (non-recursive): C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/VC/TOOLS/MSVC/14.16.27023/INCLUDE
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/CPPWINRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/SHARED/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UCRT/
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UM/
idle loop: reparsing the active document                                                            <-- this line does not appear when folder is BUG_APP
Checking for syntax errors: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c        <-- this line does not appear when folder is BUG_APP
cpptools/getFoldingRanges: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c (id: 4) <-- this line does not appear when folder is BUG_APP
  Processing folder (recursive): C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/WINRT/
  Processing folder (recursive): C:/VSCODE_FOLDER_NAME_BUG/
  Discovering files: 4742 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  tag parsing file: C:\VSCODE_FOLDER_NAME_BUG\MOD\BUG_APPL\GATEWAY_APP.H
  Parsing: 25 files(s) processed
Done parsing remaining files.
cpptools/getSemanticTokens: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c (id: 5)
cpptools/getCodeActions: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c (id: 6)
  tag parsing file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\VC\TOOLS\MSVC\14.16.27023\INCLUDE\CODEANALYSIS\SOURCEANNOTATIONS.H
sending compilation args for C:\VSCODE_FOLDER_NAME_BUG\MOD\BUG_APPL\DMI_MAIN_TASK.C
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\VC\TOOLS\MSVC\14.16.27023\INCLUDE
  include: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\VC\TOOLS\MSVC\14.16.27023\ATLMFC\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\WINRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.17763.0\CPPWINRT
  define: _DEBUG
  define: UNICODE
  define: _UNICODE
  stdver: ms_c17
  intelliSenseMode: msvc-x64
Queueing IntelliSense update for files in translation unit of: C:\VSCODE_FOLDER_NAME_BUG\MOD\BUG_APPL\DMI_MAIN_TASK.C
cpptools/finishUpdateSquiggles
Error squiggle count: 48
Error squiggles will be disabled in: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c
Update IntelliSense time (sec): 0.934
cpptools/getCodeActions: file:///c%3A/vscode_folder_name_bug/mod/bug_appl/dmi_main_task.c (id: 7)
Database safe to open

```
</details>

**Screenshots**

![vscode_bug](https://user-images.githubusercontent.com/76777375/103353392-0a706a80-4aa9-11eb-9008-ca3a023516f4.PNG)

**Additional context**

**Comment by sean-mcmanus** [comment]
I'm not able to repro the issue. Do you have any special settings set that could be causing the issue? If you set `"C_Cpp.default.browse.databaseFilename": "${workspaceFolder}/.vscode/vc.db"` do you see that file get created? Can you provide the logging for when the bug occurs? What happens if you edit/save the file that has no outline?

You mention 1.0.1 on Mac doesn't repro the issue -- but what about 1.1.3 on Mac or 1.0.1 on Windows?

![image](https://user-images.githubusercontent.com/19859882/103367531-2f99b480-4a7a-11eb-8bed-6d4bfe218c44.png)

Our implementation doesn't have any special case code for any files or folders with "app" in the name. So I don't currently see how we could be causing this.

**Comment by fjordan2020** [comment]
Hello,
Thanks for your reply.

I will be checking some more later.  I did a test app just like yours, and I keep having the same problem as shown in the 4 tests below.

I added the vc.db file (I added in .vscode/c_cpp_properties.json: “configurations”, "browse": {"databaseFilename": "${workspaceFolder}/.vscode/vc.db”}; is that correct?); attached.

How exactly can I generate the logs?

BR
Fernando




On 30 Dec 2020, at 17:47 , Sean McManus <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm not able to repro the issue. Do you have any special settings set that could be causing the issue? If you set "C_Cpp.default.browse.databaseFilename": "${workspaceFolder}/.vscode/vc.db" do you see that file get created? Can you provide the logging for when the bug occurs? What happens if you edit/save the file that has no outline?

You mention 1.0.1 on Mac doesn't repro the issue -- but what about 1.1.3 on Mac or 1.0.1 on Windows?

[image]<https://user-images.githubusercontent.com/19859882/103367531-2f99b480-4a7a-11eb-8bed-6d4bfe218c44.png>

Our implementation doesn't have any special case code for any files or folders with "app" in the name. So I don't currently see how we could be causing this.

**Comment by sean-mcmanus** [comment]
The logging would be from the C/C++ pane. If you set "compilerPath": "" temporarly (to disable the Windows SDK files), then do C/C++: Reset IntelliSense Database, the expected output should be similar to:
```
cpptools/resetDatabase
cpptools/resetDatabaseReady
Database safe to open
Code browsing service initialized
Populate include completion cache.
Discovering files...
  Processing folder (recursive): C:/TEST_APP/
  Discovering files: 1 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  tag parsing file: C:\TEST_APP\BUG_APP\TEST_APP.CPP
  Parsing: 1 files(s) processed
Done parsing remaining files.
```
If not, set C_Cpp.loggingLevel to the hidden value of "9" (temporarily) and you look for any differences compared to:

```
[threadpool] Idle
[threadpool] Pool size = 8
cpptools/resetDatabase
cpptools/resetDatabaseReady
Database safe to open
Code browsing service initialized
Populate include completion cache.
Discovering files...
  Processing folder (recursive): C:/TEST_APP/
process_path: C:/TEST_APP/
update_directory_excluded(): C:/TEST_APP/.vscode...
pattern_matcher::matches(): **/.git -> "(?:.*\.git)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/.vscode
  subpath under root: .vscode
  Regex doesn't match
pattern_matcher::matches(): **/.svn -> "(?:.*\.svn)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/.vscode
  subpath under root: .vscode
  Regex doesn't match
pattern_matcher::matches(): **/.hg -> "(?:.*\.hg)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/.vscode
  subpath under root: .vscode
  Regex doesn't match
pattern_matcher::matches(): **/CVS -> "(?:.*CVS)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/.vscode
  subpath under root: .vscode
  Regex doesn't match
pattern_matcher::matches(): **/.DS_Store -> "(?:.*\.DS_Store)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/.vscode
  subpath under root: .vscode
  Regex doesn't match
pattern_matcher::matches(): **/.vscode -> "(?:.*\.vscode)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/.vscode
  subpath under root: .vscode
  Regex matches, no filter
  found matching exclude entry
update_directory_excluded(): C:/TEST_APP/bug_app...
pattern_matcher::matches(): **/.git -> "(?:.*\.git)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/bug_app
  subpath under root: bug_app
  Regex doesn't match
pattern_matcher::matches(): **/.svn -> "(?:.*\.svn)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/bug_app
  subpath under root: bug_app
  Regex doesn't match
pattern_matcher::matches(): **/.hg -> "(?:.*\.hg)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/bug_app
  subpath under root: bug_app
  Regex doesn't match
pattern_matcher::matches(): **/CVS -> "(?:.*CVS)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/bug_app
  subpath under root: bug_app
  Regex doesn't match
pattern_matcher::matches(): **/.DS_Store -> "(?:.*\.DS_Store)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/bug_app
  subpath under root: bug_app
  Regex doesn't match
pattern_matcher::matches(): **/.vscode -> "(?:.*\.vscode)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/bug_app
  subpath under root: bug_app
  Regex doesn't match
exclusion_checking_iterator::update_state: C:/TEST_APP/bug_app
  Current directory is "C:/TEST_APP/bug_app"
  New file name is ""
  New full path name is "C:/TEST_APP/bug_app"
  New path is directory: "true"
exclusion_checking_iterator::update_state: C:/TEST_APP/bug_app/test_app.cpp
  Current directory is "C:/TEST_APP/bug_app"
  New file name is "test_app.cpp"
  New full path name is "C:/TEST_APP/bug_app/test_app.cpp"
  New path is directory: "false"
update_file_if_needed: C:\TEST_APP\BUG_APP\TEST_APP.CPP
  File added. Time stamp: 0
  Just enumerating files now. It won't be parsed until it is needed...
  Discovering files: 1 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
update_file_if_needed: C:\TEST_APP\BUG_APP\TEST_APP.CPP
  Update time stamp. Old: 0, New: 1609434962
  tag parsing file: C:\TEST_APP\BUG_APP\TEST_APP.CPP
edge::host - read file: C:\USERS\USERNAME\.VSCODE\EXTENSIONS\MS-VSCODE.CPPTOOLS-1.1.3\CPP.HINT
  Parsing: 1 files(s) processed
Done parsing remaining files.
```

It's possible something is wrong with the Kernel32.dll that is being loaded which is causing folders with "app" to be skipped. If you attached a debugger to cpptools.exe, using launch.json entry
```
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "symbolSearchPath": "https://msdl.microsoft.com/download/symbols",
            "logging": {
                "engineLogging": true,
                "trace": true
            },
        }
```
you should see some logging like `<- (E) {"seq":255,"type":"event","event":"module","body":{"reason":"new","module":{"id":"{5499C8E2-213B-410C-B819-FA7E152543A4}","name":"kernel32.dll","path":"C:\\Windows\\SysWOW64\\kernel32.dll","isUserCode":false,"version":"10.0.19041.662 (WinBuild.160101.0800)","symbolStatus":"Symbols loaded.","symbolFilePath":"C:\\Users\\username\\AppData\\Local\\Temp\\SymbolCache\\wkernel32.pdb\\d95140a200e97b14f7274b326a79d7211\\wkernel32.pdb"}}}`.

We use https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfileexa to iterate over files, so you could possibly use that sample code there to see what if that API is able to find the "_app" files or not.

**Comment by fjordan2020** [comment]
Hello,
Happy New year and thank you for your help; problem solved (and my mistake)! Using the C_Cpp.loggingLevel “9” I found out that:

pattern_matcher::matches(): **/app -> "(?:.*app)(?:(/.*|$))"
  normalized file path: C:/TEST_APP/bug_app
  subpath under root: bug_app
  Regex matches, no filter
  found matching exclude entry
  Discovering files: 0 file(s) processed
  0 file(s) removed from database

That was due to some setting I did some time ago, forgotten and did not think it would be “imported” to new Code projects (BTW, where is this globally stored, then?):

**Comment by sean-mcmanus** [comment]
VS Code has some sort of settings sync feature, but I haven't enabled it before. VS Code has a bunch of different settings scopes, e.g. a User scope setting will be used if it's modified and not overwritten by another scope's settings, such as a workspace folder's setting. You can hover over the "User"/etc. label to see the location of the settings.json file.

![image](https://user-images.githubusercontent.com/19859882/103597463-26af4580-4eb5-11eb-9e60-fb2bc92e9d7f.png)
