### ISSUE TITLE
sourceFileMap paths are being converted to Windows paths for cross-compiling/debugging

### ISSUE THREAD

**Issue by stever29** [microsoft/vscode-cpptools#6729]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 / Centos 7 (VirtualBox)
- VS Code Version: 1.52.1
- C/C++ Extension Version: v1.1.3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

The project cross-compiles Windows binaries (specifically Excel Xlls) building on Centos 7 (VirtualBox) via mingw/clang. We are trying to use VSCode to seamlessly build and debug from VSCode client running on Windows via Remote SSH to the linux VM. 

By forcing the cpptools extension to run on the client side, we are able to:
- build the Windows binaries on Linux
- successfully start the debugger on Windows (binaries and pdb's shared via a mount). This includes viewing the stack, variables etc.

The problem occurs with the source file mapping - on hitting a breakpoint VSCode is being asked to open the source file with a drive letter added to the source path (even though the source is residing on Linux). 

This happens both with and without sourceFileMap set. 

e.g. the following error is displayed where the paths are mapped to '/home/git'
`Unable to open 'HelloWorld.cpp': Unable to read file 'c:\home\git\HelloWorld.cpp' (Error: Unable to resolve non-existing file 'c:\home\git\HelloWorld.cpp').`

Note the conversion to a windows path, with a drive letter addition. Since VSCode is running on a remote connection to Linux this path should not be converted.

**To Reproduce**
settings.json:
`    "remote.extensionKind": {
        "ms-vscode.cpptools": ["ui"]
    },`

launch.json:
`        {
            "name": "debug",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "C:\\Share\\helloWorld.exe",
            "args": [  ],
            "stopAtEntry": false,
            "cwd": "C:\\Share",
            "environment": [],
            "externalConsole": false,
            "symbolSearchPath": "C:\\Share",
            "sourceFileMap": { "C:\\Share\\": "/home/git/" },
        }`

error:
`Unable to open 'HelloWorld.cpp': Unable to read file 'c:\home\git\HelloWorld.cpp' (Error: Unable to resolve non-existing file 'c:\home\git\HelloWorld.cpp').`

Thanks for your help

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment]
To clarify, you are running VS Code with the SSH Remote Extension but you are debugging locally on Windows? 

We have not yet tested the debugger when it is [forced to be local/remote](https://code.visualstudio.com/docs/remote/wsl#_can-i-force-an-extension-to-run-locally-remotely-). 

To help us further investigate can you share the logs from the developer console when you add the following to your launch.json?

"logging": {
    "traceResponse": true,
    "engineLogging": true
}

**Comment by stever29** [comment]
Hi @WardenGnaw - that's correct. 

I had to make a few changes to share, this was the launch.json:
`{
            "name": "helloworld",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "C:\\dev\\helloworld.exe",
            "args": [  ],
            "stopAtEntry": false,
            "cwd": "C:\\dev",
            "environment": [],
            "externalConsole": false,
            "symbolSearchPath": "C:\\dev\\",
            "logging": { "engineLogging": true, "trace": true, "traceResponse": true },
            "sourceFileMap": {
                "/proc/self/cwd": "/home/git/"
            },
        },`

log from the debug console attached, 
[debug_log.txt](https://github.com/microsoft/vscode-cpptools/files/5755622/debug_log.txt)

appreciate your help - and I do also appreciate this is a bit of an unusual setup, if there are any non-standard workarounds you can think of I'd be happy to give them a shot.

**Comment by WardenGnaw** [comment]
Ah, I see you are trying to set the breakpoint in `/home/git/mod/models/QUnitTest/helloworld.cpp"` but the debugger somehow finds the module and debug line to be at `C:\\home\\git\\helloworld.cpp`.

Associated Logs:
```
-> (C) {"command":"setBreakpoints","arguments":{"source":{"name":"helloworld.cpp","path":"vscode-remote://ssh-remote%2Blocalhost/home/git/mod/models/QUnitTest/helloworld.cpp"},"lines":[4],"breakpoints":[{"line":4}],"sourceModified":false},"type":"request","seq":3}
...
<- (E) {"seq":35,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":true,"source":{"name":"helloworld.cpp","path":"C:\\home\\git\\helloworld.cpp","sourceReference":0,"sources":[],"checksums":[{"algorithm":"MD5","checksum":"271825a10a704a367d79c180ea2c2531"}]},"line":4,"endLine":4}}}
```

Do you have a simple project than I can easily build on a linux VM and run the debugger on Windows to repro these steps?

**Comment by stever29** [comment]
yea, exactly, although I had my sourceFileMap set to /home/git - it should have been /home/git/mod/models/QUnitTest/ for that example. But the issue is it takes /home/git from the sourceFileMap and spits out c:\home\git back to VSCode (remote) which then can't locate the files. So something is converting the paths to legal windows ones

In order to get pdb's generated compiling on linux we're using mingw with clang, along with bazel as the build tool. Let me see how to get the simplest project set up and I'll get back to you shortly.

Thanks again for your help

**Comment by stever29** [comment]
Hi @WardenGnaw , 

I think skipping the cross-compile will be the simplest way to reproduce. So steps below to compile on windows then simulate the remote debugging:

**Set up VM**
- Install VirtualBox
- Download and install Centos 7 ISO 
- Install guest additions
- Add user to vboxsf group
- Set up port mapping for SSH
- Create a folder locally at c:\dev
- Set up shared folder for c:\dev - mount at /mnt/dev

**Set up VSCode**
- Install latest stable VSCode
- Install C++ Build Tools: https://visualstudio.microsoft.com/downloads/#other
- Open VSCode from within the developer command prompt
- Install C++ extension
- Install Remote - SSH extension
- Add the following to settings.json:
`{
    "remote.extensionKind": {
        "ms-vscode.cpptools": [ "ui" ],
    },
    "remote.SSH.remotePlatform": {
        "localhost": "linux"
    }
}`

** Build project**
- unzip the attached file into c:\dev : [helloworld.zip](https://github.com/microsoft/vscode-cpptools/files/5757256/helloworld.zip)
- Open the c:\dev folder **locally** in VSCode
- Run the 'Windows - Build and debug helloworld' target
- Close VSCode

** Run project**
- Move the contents of c:\dev to a subfolder c:\dev\build (c:\dev is baked in the PDBs so to simulate it properly we need to move change the location).
- Open VSCode as Remote - SSH to localhost
- Open the /mnt/dev/build folder
- Add a breakpoint in helloworld.cpp
- Run the 'Remote - Debug helloworld.exe' target

You'll get the error: 
`Unable to open 'helloworld.cpp': Unable to read file 'c:\mnt\dev\build\helloworld.cpp' (Error: Unable to resolve non-existing file 'c:\mnt\dev\build\helloworld.cpp').`

Thanks
