### ISSUE TITLE
Watch window shows wrong value (scope bug)

### ISSUE THREAD

**Issue by gvrancken** [microsoft/vscode-cpptools#6732]
Type: Debugger

**Describe the bug**
- OS and Version: Mac OS 10.15.7 (19H2)
- VS Code Version: 1.43.1
- C/C++ Extension Version: 0.28.3

See the simple C/C++ program below. When I view `result` in the for-loop in the watch window it does not show the correct value `10` but the unitialized value, caused by the outer scoped result (below the loop). The program does prints the `10` correctly of course.

```
#include <stdio.h>

int main()
{
    for (int i=0; i < 5; i++) {
        int result = 0;
        result = 6 + 4;
        printf("result: %d\n", result);
    }
    int result;
}
```

https://user-images.githubusercontent.com/161886/103466304-1af04180-4d44-11eb-84f9-cb95cef96ca1.mov

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue.

I could not reproduce this issue with Cygwin GDB 10.1. Will need to investigate with lldb.

**Comment by gvrancken** [comment]
Ohh yes the debugger is lldb!

**Comment by gvrancken** [comment]
This bug is still not solved.

**Comment by gvrancken** [comment]
Anytime you shadow an outer scope variable, the lldb-debugger will show the wrong value when watching the inner scope variable.
```
float a = 5.0f;
for (;;) {
    float a = 3.0f; 
    printf("%f", a); // will print 3.0f, but watch window and hover will show a = 5.0f.
}
```
