### ISSUE TITLE
Large Inefficient workspaceStorage. Separate Common/Shared/Large Includes

### ISSUE THREAD

**Issue by vindicatorr** [microsoft/vscode-cpptools#6733]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Arch Linux
- VS Code Version: 1.52.0-insider (24b28f57be22fe3029cb17a1dd72d8d9c2d6468b)
- C/C++ Extension Version: v1.1.3
- Other extensions you installed (and if the issue persists after disabling them): N/A
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc): Common/Shared/Large framework includePaths are parsed for every project and placed in workspaceStorage, when it should only need to be done once and shared/referenced among new projects including the same paths.

**Steps to reproduce**

1. Create an Arduino project using that extension
2. Have it auto-generate the c_cpp_properties.json using the Initialize function.
3. Create the app.ino using a simple blink test code.
4. Watch the associated ~/.config/Code - Insiders/User/workspaceStorage/ project database folder balloon to 1GB+ in size.
5. Repeat the above steps for another Arduino project, using any other test code.

**Expected behavior**

There should be a separate workspaceStorage for includes that are not native to the project so the parsing database magic doesn't unnecessarily replicate, wasting time/resources.

I first brought it up here https://github.com/microsoft/vscode/issues/3884#issuecomment-753576400 after coming from https://github.com/microsoft/vscode-cpptools/issues/6725 which I guess was only about the location (.cache/.config) rather than about the unnecessary large size which originally looked to be the takeaway.

Basically, the workspaceStorage folder associated with the new project should only contain the parsed "${workspaceFolder}/**" stuff, since it is only associated with that project.

When you start parsing the includePaths for large frameworks like ~/.arduino15/packages/STM32/ (or the gcc includes?), that can be used among other projects as well, it makes no sense in duplicating/replicating the same parsed data resulting in wasted time/resources.

So the thought is to separate those into their own workspaceStorage folder. Then any new project that references those same includePaths, there won't be any need to reparse what was already done, and can simply reference that folder.

While I don't actually know what's going on in/for workspaceStorage, that's what I surmise is happening (parsing includes).
I mentioned the 1GB+ db size for the STM32 Arduino project without any customizations. That took a long time to parse, stressing my (already weak) system, and the cpptools had taken 1.5GB of RAM (out of 8GB total, maybe 3 usable).
I'm actually stepping back from the Arduino extension and trying to use the core and board-specific code alone.
That helps with only 300MB in workspaceStorage used, but I'm sure that's mostly parsed data that can be shared among other projects referencing the same core/STM32 framework code.

I also believe that if I create a project, that workspaceStorage folder is created, the database built... But if I delete the project, that folder will forever still remain, wasting space.

**Comment by sean-mcmanus** [comment]
All our code relies on having 1 database for workspace files. There's no system for using multiple databases, and doing so is problematic because of there are multiple per-workspace settings that can affect what files are in the database, such as files.exclude, limitSymbolsToIncludedHeaders, etc.

You can set C_Cpp.default.databaseFilename to something like "${workspaceFolder}/.vscode/vc.db" to cause the db file to be deleted when the folder is deleted and stop populating at the .cache/.config location.

You can also use files.exclude to stop parsing certain folders outside of the workspace folder.

You can also share a single database across multiple projects via adding multiple root folders in a single workspace.

**Comment by vindicatorr** [comment]
I REALLY like that C_Cpp.default.databaseFilename. Thanks for that. I don't know why that path wouldn't default to the project workspace from the start. Hmm, going to assume it's "C_Cpp.default.browse.databaseFilename".

I'm sure I wouldn't want to use files.exclude for the reason you specified since I'd lose the intellisense for those folders (STM32/Arduino-core), but I could at least use it to exclude board-specific folders.

That "multiple root folders" has me intrigued. Thinking it through... from a STM32/Arduino standpoint, I'd create a single workspace folder, containing the .vscode.
Then I create a blink led project folder within that workspace folder for an F1-based board.
I also create a temperature sensor-based folder also within that same workspace for an F4-based board.
The F1 and F4 projects would need to include/parse the <pathToArduinoCoreSTM32>/cores/arduino/** subdirs for the common arduino and stm32 headers.
But for the F1, I'd also need to include <pathToArduinoCoreSTM32>/variants/DISCO_F100RB while for the F4, I'd include the DISCO_F407VG folder.
No need to use files.exclude in this case, nor parse the entire variants/** subs, so I'd just add those 2 folders specifically for includePath.
Okay, that actually sounds reasonable, ESPECIALLY when paired with the "C_Cpp.default.browse.databaseFilename" set for the workspace.
If there is an issue with this approach, I'd think it'd be the common tasks.json, but I'd just add each F1 and F4 build sections and switch between them using Configure Default Build Task.
It could get lengthy for a whole bunch of projects. I thought there might be a "#include" type of way to separate out the lengthy sections, but found https://github.com/Microsoft/vscode/issues/60043. I'd think it could be handled by using separate Makefiles and calling for their builds within tasks.json.

I'll close this since, this approach is more efficient/organized than my original suggestion/request. Thanks for that.
Feel free to correct me if my thinking is wrong anywhere, as I'm about to give this approach a try.

**Comment by sean-mcmanus** [comment]
Yeah, I forgot the "browse" part of the setting. We originally had the default databaseFilename be in the .vscode folder, but we changed it 4 years ago as a result of issue https://github.com/microsoft/vscode-cpptools/issues/211 and other user complaints -- in particular we had people mistakenly uploading the database file to source control.

Your approach sounds good to me. Let us know if you hit any multi-root bugs...we haven't gotten many user complaints about multi-root specifici issues, but usage of multi-root is relatively low: https://github.com/Microsoft/vscode-cpptools/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature%3A+Multiroot%22

FYI, we're planning to a release a Makefile-Tools extension soon that is similar to the CMake Tools extension, i.e. enabling IntelliSense configuration and building, but I don't know yet if the multi-root scenario will be supported initially.

**Comment by vindicatorr** [comment]
I "may" have hit a bug ("Fetching build tasks"), but it may be explained away...
**Cause found at the bottom**

I had moved all of my STM32 projects under a single ST root (containing c, c++, c#... projects).

They all have their original .vscode in their project folder since I only moved them, while the workspace has it's own .vscode, and these "children" .vscodes may be my problem. What do you think?

My CPU is being consumed by the "fetch"ing process. No building is occurring. Oh, I had copied over the contents of one of the children tasks.json into the workspace tasks.json, and adjusted the pathing of everything to coincide with the mv that I did.

Is there a way I can see in more verbose detail what the "fetching" is doing (like it may be walking through the children .vscode and getting the tasks.json from them too (which still shouldn't be taking this long))?
I also had disabled the C and C# extensions (while leaving others enabled).
The "fetching" issue had never happened before I made this structure shift, and I had been able to run the build for that one project I was testing with this new structure (before I made this mv).

I also tried a test where the workspace tasks.json only contained:
```
        {
            "label": "Test",
            "command": "/usr/bin/arm-none-eabi-gcc",
            "args": [
                "--version"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
```
Yup, I disabled all extensions (wanted to avoid that) and the fetching issue still exists.
Okay, interesting... I moved out every child project except for that one I tested before the mv which worked, and the test task I created worked. Now to move things back a little at a time...
```
Workspace
    Chip1
        Board1
            Project1 //C
    Chip2
        Board2
            Project1 //original test project which remained and task build worked
            Project2
            Project3
            Project4
            ...
```
First other folder (Board1/Project1) moved back, test still works.
Three more folders (Board2/Project{2-4} moved back, test still works.
Hmm... I put all the C/C++ projects back, and the test build worked... BUT when I started moving back C# projects, it started failing, and I had a feeling this was the issue... but it was not.
I had a BlazorServer project that I moved in there and the test build worked... Still looking to the cause.
Really weird. I moved the BlazorWASM folder back, which was fine. But moving 2 other web-related projects (still for STM32 projects), the long "fetching" issue happened again.
I moved another child project containing 3 projects ((C# stuff) library, razor, console), and that was failing. I moved the razor one out and the task worked.

**Cause**
Okay, I did NOT see that coming... It was the existence of the filename "package.json" that caused the problem. LITERALLY the filename alone.
I tested with adding a character to the end of "packageZ.json", and the test build worked.
I renamed it to a .bak file and created an empty "package.json". BOOM! The test build failed. No explanation from me on that weird one.
Yup, I moved the last 2 projects back, which both also contained that file somewhere in the directory, and after renaming them, the build task worked again.

I see there have been various issues for "Fetching build tasks", and don't know if you would like me to create another one, or link to this comment on an existing open one (or neither needed).

**Comment by sean-mcmanus** [comment]
I'm not sure what you mean by the "workspace has it's own .vscode". A workspace is just a json file. We process the .vscode/c_cpp_properties.json and settings.json in each workspace folder.

We don't output the message "Fetching build tasks". I'm not familiar with what could cause that. It sounds like you might be hitting a VS Code bug?: https://github.com/microsoft/vscode/issues .

**Comment by vindicatorr** [comment]
I guess I should've said "workspace folder"? The root. Like in the tree I provided above, The folder I'd name "ST" would be the workspace folder, and it would contain the sole/main .vscode that gets worked with.
Then there's the non-functional folder (other than providing structural descriptions) "Chip", which only contains the "Board" folder, which then contains the actual project folders "BlinkLed"... which used to be their own separate workspace folders and still could be on their own if I opened those project folders in vscode.
The root and leaf folders in that tree all have .vscode. The leafs normally would not have the .vscode in this structure, but only do since I moved them from being in their own "root" position.

I'll certainly bring up the problem to the vscode folks then. I just didn't know where until you mentioned it. When you do a google search for "Fetching build tasks", you'll see both vscode and vscode-cpptools have the issue brought up with some still open.

**Comment by vindicatorr** [comment]
Hey Sean, I'm an idiot. I didn't realize workspaces were an actual "[thing](https://code.visualstudio.com/docs/editor/multi-root-workspaces)" instead of just a concept. I include an "**Issue**" below (you can ignore in-between).

What I did wrong, for idiots like myself:
Previously, I had no actual workspace set up and it was just a folder structure I displayed before, where I just opened the ST folder.
Everything seemed fine with the .vscode containing the db file at the root (ST) level, which I figured was good as it would be shared among all of the ST projects.
I just wasn't understanding why none of the project tasks were showing up when I hit "Run Task" (only npm and tsc I think, oh and the echo task in the global json).
I had an idea and did a quick test and realized that I couldn't use the same folder structure displayed before. I had to manually add each project to the workspace, and they all had to be root so the Run Task can find the build command.
Once I did that, Run Tasks immediately showed the build task for the root project.

**Issue**:
This is no good though because I may have a structure like:
```
ST
    F1
        discovery
            temperature
                firmware //c/cpp
                clientInterfaceLibrary //c#
                clientInterfaceConsole //c#
                clientInterfaceWeb //c#
            motion
                ...
            ...
        ...
    F#...
```
But with a workspace, for each build task to be seen, I'd have to add each one flat at the root level.
That can get ugly pretty quickly. Especially when the project/folder name is "firmware", but there's a separate one for each board/chip/sensor, and I can't determine which is for which (of course that could simply be solved by making the folder name more descriptive (st_f1_discovery_temperature_firmware), but that's ugly all its own.

The other issue is that I expected the shared/common db file to be at the workspace root (ST (st.code_workspace)), not the project folder root (firmware). That didn't happen.
I also read that workspaceRoot is deprecated for workspaceFolder. I would've assumed workspaceRoot would be "ST" (or more specifically, wherever folder the "st.code-workspace" file is located), and workspaceFolder would be like a "workspaceProject".
```
For example, in a multi root workspace with folders Server and Client, a ${workspaceFolder:Client} refers to the path of the Client root.
```
That led me to think that workspaceFolder would've been ST, and to reference the project for the db location, I would've set it as something like "${workspaceFolder:firmware}/.vscode/vc.db", which would've put it in <pathTo>ST/F1/discovery/temperature/firmware/.vscode/vc.db.
And if I just set it as "${workspaceFolder}/.vscode/vc.db", it would put it in <pathTo>ST/.vscode/vc.db (assuming ST contained "st.code-workspace").

**Comment by sean-mcmanus** [comment]
Yeah, there's no way currently to reference the location of the .code-workspace file (there was a request on VS Code to add such a variable), so ${workspaceFolder} would resolve to either the 1st workspace folder or whatever folder the active file is associated with.
