### ISSUE TITLE
How can I reset the extension setting?

### ISSUE THREAD

**Issue by TheEpicFace007** [microsoft/vscode-cpptools#6734]
I sync my setting in vscode if this can help

**Comment by sean-mcmanus** [comment]
What do you mean by "extension setting"? You can open the json files with settings and manually delete the settings that start with C_Cpp.

**Comment by ViniDalvino** [comment]
resetting the setting of the cpp extension to the default

**Comment by sean-mcmanus** [comment]
Yeah, removing all the C_Cpp settings should reset it to the default. Were you requesting we add another method?

**Comment by ViniDalvino** [comment]
Yea. I was requesting for doing it globally and so vscode sync the changes

**Comment by sean-mcmanus** [comment]
What do you mean by "globally" and "vscode sync"? Are you referring to VS Code's settings sync feature across multiple machines? Do you know of any other extension that can reset settings globally like this? I'm not sure yet if we're able to implement that.
