### ISSUE TITLE
debugger terminated with no error when using clang++

### ISSUE THREAD

**Issue by fara-nak** [microsoft/vscode-cpptools#6739]
1. try running [this ](https://github.com/microsoft/vssaas-planning/issues/1640)scenario or simply create a simple c++ app. \
2. go to debug tab and choose `create a launch.json file` 
3. then choose `GDB` 
4. then any of `clang++`

then try to debug , debugger will stop with no error. Howeer if you choose `g++` instead of `clang++` it works.

*it seems like GDB [issue ](https://github.com/microsoft/vscode-cpptools/issues/2778)

**Comment by WardenGnaw** [comment]
> try running this scenario or simply create a simple c++ app. \

That link has 10 secnarios and is running on codespaces.

In the `launch.json`, can you add the following to the configurations:
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

and share the Debug Console output of each run?
