### ISSUE TITLE
After enabling this extension Polish letter "ó" stops working in VScode.

### ISSUE THREAD

**Issue by Marqin** [microsoft/vscode-cpptools#674]
After enabling this extension I cannot write Polish letter "ó" in VScode (in any type of file). After disabling this extension I can.

This letter is written by pressing `right alt` + `o` on Polish keyboard (layout is like US-one).

OS: OS X 10.11.6
VScode: 1.11.2
vscode-cpptools: 0.11.0

**Comment by sean-mcmanus** [comment]
Our extension maps Alt+O to Switch Header/Source. You can change the key mapping to something else via Preferences->Keyboard Shortcuts.

**Comment by Marqin** [comment]
@sean-mcmanus but in all programs such shortcuts work with Left Alt, and Right Alt is used for special letters.

Also, why is this shortcut still blocking in files that are not C++? It should only register shortcuts for C++ files.

**Comment by sean-mcmanus** [comment]
VS Code itself has no notion of left versus right Alt. Can you open an issue at https://github.com/Microsoft/vscode/issues ?

Yes, we plan to add a "when" clause for our keyboard shortcuts in our next update (planned for some time next week): see https://github.com/Microsoft/vscode-cpptools/issues/662 .
