### ISSUE TITLE
"#include" statements are always invalid

### ISSUE THREAD

**Issue by Phoupraw** [microsoft/vscode-cpptools#6740]
Type: General

"#include" statements are always invalid. If I create a folder and set the options files, the errors disappear but it goto a file of option and never compile and run. I've installed GCC.

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.49.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): None
- A clear and concise description of what the bug is:
"#include" statements are always invalid, just like the image below.

**To Reproduce**
[C动态数组测试.zip](https://github.com/microsoft/vscode-cpptools/files/5773709/C.zip)
1. Unzip and open the c file using VSCode and Cpptools
2. See error of include statements

**Expected behavior**
No error for include statements.

**Screenshots**
![include总是错误](https://user-images.githubusercontent.com/50520903/103724842-3f803e00-5010-11eb-8855-3c039b771215.png)

**Comment by sean-mcmanus** [comment]
What gcc did you install? Did you set your compilerPath? Can you run the C/C++: Log Diagnostics command to see if it's picking up the correct gcc path?

**Comment by Phoupraw** [comment]
> What gcc did you install? Did you set your compilerPath? Can you run the C/C++: Log Diagnostics command to see if it's picking up the correct gcc path?

**I execute the command "g++ -v -E -x c++ -" in cmd and followings are the returns:**
Reading specs from D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/specs
Configured with: ../gcc-3.4.5-20060117-3/configure --with-gcc --with-gnu-ld --with-gnu-as --host=mingw32 --target=mingw32 --prefix=/mingw --enable-threads --disable-nls --enable-languages=c,c++,f77,ada,objc,java --disable-win32-registry --disable-shared --enable-sjlj-exceptions --enable-libgcj --disable-java-awt --without-x --enable-java-gc=boehm --disable-libgcj-debug --enable-interpreter --enable-hash-synchronization --enable-libstdcxx-debug
Thread model: win32
gcc version 3.4.5 (mingw-vista special r3)
 D:/Applications/MinGW/bin/../libexec/gcc/mingw32/3.4.5/cc1plus.exe -E -quiet -v -iprefix D:\Applications\MinGW\bin\../lib/gcc/mingw32/3.4.5/ -
ignoring nonexistent directory "D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../mingw32/include"
ignoring nonexistent directory "/mingw/include/c++/3.4.5"
ignoring nonexistent directory "/mingw/include/c++/3.4.5/mingw32"
ignoring nonexistent directory "/mingw/include/c++/3.4.5/backward"
ignoring nonexistent directory "/mingw/include"
ignoring nonexistent directory "/mingw/include"
ignoring nonexistent directory "/mingw/lib/gcc/mingw32/3.4.5/include"
ignoring nonexistent directory "/mingw/mingw32/include"
ignoring nonexistent directory "/mingw/include"
#include "..." search starts here:
#include <...> search starts here:
 D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/c++/3.4.5
 D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/c++/3.4.5/mingw32
 D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/c++/3.4.5/backward
 D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include
 D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/include

**I execute the command "C/C++: Log Diagnostics" in vscode and followings are the returns:**
Version: 1.1.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "forcedInclude": [
        "D:\\Applications\\MinGW\\include"
    ],
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}

**Comment by Colengms** [comment]
Hi @Phoupraw .  Could you post the contents of your `c_cpp_properties.json`?  The `compilerPath` reported by `C/C++: Log Diagnostics` appears to be `cl.exe`, not MinGW.  `compilerPath` should instead refer to the compiler you are using, to ensure the correct system include paths and other settings are configured properly to match that compiler.

You might also enable debug logging using `"C_Cpp.loggingLevel": "Debug"`, to see if we are logging any issues encountered when trying to query the compiler.

It looks like you are setting `forcedInclude` to `"D:\\Applications\\MinGW\\include"`.  `forcedInclude` is for specifying header files (by name, individually) to automatically include before parsing the contents of any C/C++ files.  That setting may need to be cleared.

Also, the version of MinGW you are using appears to be rather outdated.  You might consider using a more recent build.  There is some discussion of recent MinGW builds here: https://github.com/microsoft/vscode-cpptools/issues/6536

**Comment by Phoupraw** [comment]
> Hi @Phoupraw . Could you post the contents of your `c_cpp_properties.json`? The `compilerPath` reported by `C/C++: Log Diagnostics` appears to be `cl.exe`, not MinGW. `compilerPath` should instead refer to the compiler you are using, to ensure the correct system include paths and other settings are configured properly to match that compiler.
> 
> You might also enable debug logging using `"C_Cpp.loggingLevel": "Debug"`, to see if we are logging any issues encountered when trying to query the compiler.
> 
> It looks like you are setting `forcedInclude` to `"D:\\Applications\\MinGW\\include"`. `forcedInclude` is for specifying header files (by name, individually) to automatically include before parsing the contents of any C/C++ files. That setting may need to be cleared.
> 
> Also, the version of MinGW you are using appears to be rather outdated. You might consider using a more recent build. There is some discussion of recent MinGW builds here: #6536

`c_cpp_properties.json` in `D:\Applications\Microsoft VS Code\.vscode`：
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```
There is another `c_cpp_properties.json` in the .vscode in the folder where the cpp file above I uploaded is:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/c++/3.4.5",
                "D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/c++/3.4.5/mingw32",
                "D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/c++/3.4.5/backward",
                "D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include",
                "D:/Applications/MinGW/bin/../lib/gcc/mingw32/3.4.5/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```
When I open the folder in vscode, the header file errors disappear. But there is no `tasks.json` in the .vscode, only `c_cpp_properties.json` and `launch.json`.

I've clear the `forcedInclude` in `settings.json`.

I'm downloading and installing the latest MinGW from your link.

**Comment by sean-mcmanus** [comment]
You should replace the compiler path with the path to the mingw compiler, e.g. `"D:/Applications/MinGW/bin/g++.exe"` and also remove the system includes from "includePath".

`D:\Applications\Microsoft VS Code\.vscode\c_cpp_properties.json` can be ignored (only `${workspaceFolder}/.vscode/c_cpp_properties.json` is used).

**Comment by Phoupraw** [comment]
> You should replace the compiler path with the path to the mingw compiler, e.g. `"D:/Applications/MinGW/bin/g++.exe"` and also remove the system includes from "includePath".
> 
> `D:\Applications\Microsoft VS Code\.vscode\c_cpp_properties.json` can be ignored (only `${workspaceFolder}/.vscode/c_cpp_properties.json` is used).

I've already done these. But there's no `tasks.json`. I spawned a `tasks.json` but it dosen't work. Then I don't know how to complie the c file.

**Comment by sean-mcmanus** [comment]
What is the tasks.json you are using? Your mingw is not located at a spot we can automatically locate so you'd have to manually populate the tasks.json.

**Comment by sean-mcmanus** [comment]
See https://code.visualstudio.com/docs/cpp/config-mingw for example.

**Comment by Phoupraw** [comment]
> What is the tasks.json you are using? Your mingw is not located at a spot we can automatically locate so you'd have to manually populate the tasks.json.

There is no automatically spawned tasks.json in my folder. I've add the mingw path to the system path. I have to run a spawned file 
![C++编译生成任务](https://user-images.githubusercontent.com/50520903/104263277-40a7e400-54c4-11eb-95f4-be66101462e6.PNG)
to complie the c file and then press the Ctrl+F5 to run the complied file. When I press the Ctrl+F5 to run the c file, there's always following words in the debug soncole, 
```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code
with Visual Studio Code, Visual Studio or Visual Studio for Mac
software to help you develop and test your applications.
-------------------------------------------------------------------
```
and the output of printf is followed. I run the c file not in debug mode but the output is still in the debug console.

Could you please tell me how to complie and run a single c/cpp file without opening a project folder just like DevC++?

**Comment by sean-mcmanus** [comment]
What happens if you click on the C/C++: gcc.exe build active file? It should build the file behind the scenes. You can use the "Configure Build Task" option to generate a tasks.json, such as
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: \"C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe\""
		}
	]
}
```

**Comment by Phoupraw** [comment]
> What happens if you click on the C/C++: gcc.exe build active file? It should build the file behind the scenes. You can use the "Configure Build Task" option to generate a tasks.json, such as
> 
> ```
> {
> 	"version": "2.0.0",
> 	"tasks": [
> 		{
> 			"type": "cppbuild",
> 			"label": "C/C++: g++.exe build active file",
> 			"command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
> 			"args": [
> 				"-g",
> 				"${file}",
> 				"-o",
> 				"${fileDirname}\\${fileBasenameNoExtension}.exe"
> 			],
> 			"options": {
> 				"cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
> 			},
> 			"problemMatcher": [
> 				"$gcc"
> 			],
> 			"group": {
> 				"kind": "build",
> 				"isDefault": true
> 			},
> 			"detail": "compiler: \"C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe\""
> 		}
> 	]
> }
> ```
I clicked the C/C++: gcc.exe build active file and the c file was complied. I've generated a tasks.json in the way you told me. However, I just want to complie and run a separate c/cpp file without opening any folder. I directly complie or run java and py file, but not c/cpp file. The c/cpp file even reported header file not found when the folder isn't open. Instead, the DevC++ can directly complile and run a separate c/cpp file. I want to know how to do this in vscode.

**Comment by Phoupraw** [comment]
> We don't support the open file scenario for build tasks currently. You can either open a folder or build from the Terminal or a separate command prompt with a command line such as `"D:/Applications/MinGW/bin/g++.exe -g <file> -o <output>"`

Thank you. 
```
switch(language) {
case C++:
    return DevC++;
case Java:
case Python:
    return VSCode;
default:
    return Notepad++;
}
```
