### ISSUE TITLE
Issues with C/C++ and Remote SSH

### ISSUE THREAD

**Issue by ericsanch** [microsoft/vscode-cpptools#6741]
I am connecting to a remote host for development using a jump box in the order local -> jump -> remote. I can successfully connect to 'remote' through 'jump', but debugger extensions seem to not work when connected. I can compile and debug code when SSH'd directly to 'jump' without issue, but when logging into 'remote' I get the following error:

`terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
[Error - 7:59:22 PM] Connection to server got closed. Server will not be restarted.` 

And when I create a hello world test program in 'remote,' I get the following errors the following two errors when attempting to compile and run a program.
`Error: The cppbuild task detection didn't contribute a task for the following configuration:
{
    "label": "C/C++: gcc build active file",
    "type": "cppbuild",
    "command": "/bin/gcc",
    "args": [
        "-g",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}"
    ],
    "options": {
        "cwd": "${workspaceFolder}"
    },
    "problemMatcher": [
        "$gcc"
    ],
    "group": {
        "kind": "build",
        "isDefault": true
    },
    "detail": "Task generated by Debugger."
}`

and subsequently
`Could not fin the task 'C/C++: gcc build active file'.` alert with the options of editing the tasks.json or launch.json files (which have been set up for the test project)

The SSH connection to remote is successful because I am able to work with files and even run gcc in the terminal within vscode to compile/run, but the compiler extension doesn't seem to be working with the server.

local os: Mac OS 10.15.7
server os: CentOS 7
VS Code version: 1.52.1
Remote - SSH version: 0.62.0
C/C++ extension version 1.1.3

**Comment by sean-mcmanus** [comment]
Hmm, I'm not sure what could cause this. "Connection to server got closed" usually indicates our cpptools process has crashed. Are you able to determine if that process has crashed or is running, i.e. does IntelliSense and other language service features like hover work?

Are you able to get your task to work via changing the "type" from "cppbuild" to "shell"?

**Comment by NicolasNewman** [comment]
I'm facing a similar issue as well when attempting to access a remote C project on my school's systems. I noticed the locked issue #4863 was from another student at my university, and was faced with the same issue. I'm not sure about the scenario for the person who started this issue, but in our case could it be due to the way our unis systems are configured? I've also tried opening an empty folder on the remote, creating a new C file, and opening it which results in the same error. Outside of the `std::system_error` error mentioned above, I don't know how to find logs containing more information.

**Comment by sean-mcmanus** [comment]
Are you able to execute `~/.vscode-server/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools` on the remote machine?

This might be a VS Code issue. Are you able to get other extensions to work? I saw the issue at https://github.com/microsoft/vscode-remote-release/issues/4269 , but they might not have enough info.

Are you able to `git clone https://github.com/microsoft/vscode-cpptools.git` on the remote side and `git checkout release` and do Launch Extension (development) to debug what is going wrong and see if there are any error call stacks (Help->Toggle Developer Tools->Console might show some error call stacks too).

**Comment by NicolasNewman** [comment]
Executing the file mentioned resulted in:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted
```

I tried running the language server for Java and I received a crash with a nearly identical error. I'll take a look at the issue you mentioned since this does in fact appear to be a VSCode issue

**Comment by sean-mcmanus** [comment]
So executing cpptools results in that "std::system_error" message?

When you run `file ~/.vscode-server/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools` does the output text appear to correctly match the architecture of the OS?

**Comment by parisosuch-dev** [comment]
> So executing cpptools results in that "std::system_error" message?
> 
> When you run `file ~/.vscode-server/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools` does the output text appear to correctly match the architecture of the OS?

I too ran into this same issue. I am running the executable cpptools and it provides:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted
```
I am currently using 1.3.0-insiders3.

**Comment by EzioZz** [comment]
same issue.
I am currently using 1.3.1.
ARM server.
centos7
[Error - 8:17:19 AM] Connection to server got closed. Server will not be restarted.
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable

**Comment by sean-mcmanus** [comment]
@EzioZz When you run file ~/.vscode-server/extensions/ms-vscode.cpptools-1.3.1/bin/cpptools does the output text appear to correctly match the architecture of the OS?

**Comment by EzioZz** [comment]
> @EzioZz When you run file ~/.vscode-server/extensions/ms-vscode.cpptools-1.3.1/bin/cpptools does the output text appear to correctly match the architecture of the OS?

Output is the same as I run the extension in vscode.
I am sure that I download the right architecture from github release.

**Comment by sean-mcmanus** [comment]
I mean run `file ~/.vscode-server/extensions/ms-vscode.cpptools-1.3.1/bin/cpptools`. The `file` program should report the architecture. Is your ARM server 32-bit or 64-bit?

**Comment by EzioZz** [comment]
Sorry, my fault.
64bit.It matches with my architecture of the OS
Here is the output. 
```
/home/xxx/.vscode-server/extensions/ms-vscode.cpptools-1.3.1/bin/cpptools: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 3.7.0, BuildID[sha1]=3f5cf22f9f84be669e76c9264997b57f1418497a, not stripped
```

**Comment by sean-mcmanus** [comment]
Okay. Unfortunately, we don't know yet what is causing that error (and don't have a machine that repros it).

@bobbrow @michelleangela @Colengms Any ideas what could be causing this? I checked for any new glibc dependencies previously and it seemed okay.

**Comment by michelleangela** [comment]
@sean-mcmanus I haven't seen this error. To help investigate locally, we'll need to image a machine with Centos 7 aarch64 server.

**Comment by sean-mcmanus** [comment]
If this is only reproing on CentOS 7 aarch64, then I'm thinking we may not support that OS due to low usage, but we could reconsider in the future. We build our Linux arm/aarch64 binaries with a sysroot based on Ubuntu 14, so CentOS might require a different build/sysroot. I've filed https://github.com/microsoft/vscode-cpptools/issues/7404 to track potentially adding support for that.

**Comment by sean-mcmanus** [comment]
It looks like CentOS 8 works, so you may want to consider updating to that if possible. Still investigating though...

**Comment by sean-mcmanus** [comment]
Actually, looks like our binaries should run on CentOS 7 too...so we don't know yet why some users aren't able to run the binaries. There could be some dependencies that need to be installed on the OS.

**Comment by EzioZz** [comment]
Thanks for your work.
May be it is caused by the abnormal disconnection of the network.
Killing all the pid related to 'cpptools' will fix this issue. That works for me.

**Comment by parisosuch-dev** [comment]
Can confirm from what @EzioZz said here. The server I was running on did not properly kill the cpp-tool task after disconnection. SIGTERMing the cpp-tool tasks using `htop -u [user_name]`.

**Comment by sean-mcmanus** [comment]
We added a 5 minute timeout with 1.4.0 (https://github.com/microsoft/vscode-cpptools/issues/7262 ).
