### ISSUE TITLE
Fix support_case_sensitive_files for macOS

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6747]
For compilation args, there is no need to support case sensitive files. Currently, code supports case sensitive files for both Linux and macOS. It should only be Linux.

**Comment by sean-mcmanus** [comment]
A related issue is https://github.com/microsoft/vscode-cpptools/issues/1994 (which also covers Windows). This might be considered a duplicate of that or we could track Windows and Mac separately.

**Comment by michelleangela** [comment]
Closing as duplicate of #1994
