### ISSUE TITLE
"workbench.editor.revealIfOpen" option does not work for command "C/C++: Switch Header/Source"

### ISSUE THREAD

**Issue by dmurph** [microsoft/vscode-cpptools#6749]
VSCode Version: 1.52.1
C++ extension version: v1.1.3
Commit: ea3859d
Date: 2020-12-16T16:30:02.420Z (2 wks ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

Use the C++ extension
HAve two different editor panels
Open a header on one panel, and the implementation (cc) on the other
Set the above option in the user settings.json to true (workbench.editor.revealIfOpen) (possibly restart?)
Use the command "C/C++: Switch Header/Source"
Expected:

The focus should shift to the other editor panel

Actual:

A new tab will open in the active panel, with the corresponding header / implementation file, duplicating the one already open in the other panel.

Does this issue occur when all extensions are disabled?: Yes/No

Unknown

**Comment by sean-mcmanus** [comment]
Thanks for letting us know about this. We have a fix at https://github.com/microsoft/vscode-cpptools/pull/6751.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders2
