### ISSUE TITLE
debug stops

### ISSUE THREAD

**Issue by DenisKaz** [microsoft/vscode-cpptools#675]
Hi!
I've googled for a while, but can't find the answer..
launching the debugger i have the following message:

> C setFunctionBreakpoints: {"breakpoints":[]}
C configurationDone: null
C threads: null
=thread-group-added,id="i1"
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Stopped due to shared library event (no libraries added or removed)
C threads: null
Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.
Breakpoint 1, main () at main.c:4
4	    printf("Hello!");
[Inferior 1 (process 30758) exited normally]
The program '/home/merlin/Coding/C_projects/main' has exited with code 0 (0x00000000).
C disconnect: {"restart":false}

my tasks.json:
>{
    "version": "0.1.0",
    "command": "gcc",
    "isShellCommand": true,
    "args": [
       "-g", "-o", "main", "main.c"
        ],
    "showOutput": "always",
    "echoCommand": true
}` 

my launch.json:

`{

    "version": "0.2.0",

    "configurations": [
        {
            "name": "C Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/main",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true, 
              "logging": {
                "moduleLoad": true,
                "programOutput": true,
                "trace": true
            },

            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "${workspaceRoot}/main",
            "processId": "${command:pickProcess}",
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        }
    ]   
}

i'm trying it on linux mint 18.1 Serena

**Comment by pieandcakes** [comment]
@DenisKaz Did you set a breakpoint? It looks like the program is executing and is exiting the debugger normally.

```
 4 printf("Hello!");
 [Inferior 1 (process 30758) exited normally]
 The program '/home/merlin/Coding/C_projects/main' has exited with code 0 (0x00000000).
 C disconnect: {"restart":false}
```

**Comment by DenisKaz** [comment]
I also think so, but why doesn't it show me smth in terminal?
when i set "stop at entry" and press F11 after start it looks like
![default](https://cloud.githubusercontent.com/assets/21154702/25636829/45108842-2f8b-11e7-8312-d9c0c689e7cd.png)

**Comment by DenisKaz** [comment]
i've tried vs code before and it worked fine, i think this happens after updates..

**Comment by DenisKaz** [comment]
added sleep() in main function - and i see that the program is realy working. Will look now for instructions of using the debugger properly..

**Comment by pieandcakes** [comment]
@DenisKaz the output should show up in a separate terminal window(either gnome-terminal or XTerm). We have a backlog item to incorporate the VSCode terminal for output. 
I've seen this happen when it doesn't get enough information to set a breakpoint. Can you make sure that the compilation is done with the `-g` flag? I see it in the `task.json` but I wanted to make sure that the task is being run every time.

**Comment by DenisKaz** [comment]
Yes, there is `-g`  flag.
And the external terminal opens and closes after the program is complete (why?). and there is smth, that is also been written in terminal _before_ the main() runs, but i can't discern it

**Comment by DenisKaz** [comment]
managed to take screenshot
thats it before the main() runs
![2017-05-03 21-58-55](https://cloud.githubusercontent.com/assets/21154702/25676773/f69c461c-304b-11e7-8470-f36348b5654f.png)

**Comment by pieandcakes** [comment]
I wonder why it is failing to set the terminal . which terminal app are you using?

**Comment by DenisKaz** [comment]
GNOME terminal 3.18.3

**Comment by DenisKaz** [comment]
can i use internal terminal of vs code, when using debug? i only can use it as usual - complie and run my program. but when i start debug - it launches external console

**Comment by DenisKaz** [comment]
new problem found
