### ISSUE TITLE
Only my main.cpp gets compiled - general solution by editing tasks.json does not work

### ISSUE THREAD

**Issue by DvdFrck** [microsoft/vscode-cpptools#6753]
I use visual studio code with the "C/C++" extension and installed Mingw-w64 as compiler.
Regardless of the Project _(more than one .cpp file)_ I am trying to run I always get several Linking errors: "[...] undefined reference to '[...]'"

Usually this is fixed by editing the tasks.json file like it is described here: https://code.visualstudio.com/docs/cpp/config-mingw
I edited the file accordingly, but it didn't change anything. Even calling all direct paths of the cpp files doesn't change anything. I think the edited tasks.json file is not even used.

I've written a little testprogramm to demonstate it:

1. testy_1.cpp
          #include "testy_2.hpp"

          int main()
          {
              testfunction();
              return 0;
          }

2. testy_2.hpp
         #ifndef testy_2_guard
         #define testy_2_guard

         #include <iostream>

         void testfunction();

         #endif //testy_2_guard 

3. testy_2.cpp
         #include "testy_2.hpp"

         void testfunction(){
             std::cout << "works" << std::endl;
             return;
         }

by running the programm I get the folling error message:
![image](https://user-images.githubusercontent.com/75978753/103988632-c0654400-518e-11eb-9360-6a832c603089.png)

The compiler does not give an error because by the #include of testy_2.hpp the compiler knows that "void testfunction()" exists. But the linker than does not find the declaration because testy_2.cpp is not compiled.

Normally by editing the tasks.json file, all .cpp-files from the current folder are compiled, but in my case  this doesn't work. I even think that my edited tasks.json-file isn't even used.

What can I do to fix this? I try to solve this for 3 days now and I am getting crazy.
Thank for your help in advance!

Best Regards,
David

**Comment by sean-mcmanus** [comment]
You need to link your files correctly. There's some info at https://stackoverflow.com/questions/7032709/linking-two-cpp-and-a-h-files . If you can't get that to work still, can you provide your tasks.json?

**Comment by DvdFrck** [comment]
I did, but the problem is, that my second .cpp-file is not getting compiled.
This is my tasks,json:

         {
         	"version": "2.0.0",
	         "tasks": [
		         {
			         "type": "cppbuild",
         			"label": "C/C++: g++.exe build active file",
	         		"command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
		         	"args": [
			         	"-g",
	         			"${workspaceFolder}\\*.cpp",
		         		"-o",
		         		"${fileDirname}\\${fileBasenameNoExtension}.exe"
		         	],
		         	"options": {
		         		"cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
		         	},
		         	"problemMatcher": [
		         		"$gcc"
		         	],
		         	"group": "build",
		         	"detail": "compiler: \"C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe\""
	         	},
	         ]
         }

**Comment by sean-mcmanus** [comment]
It's working for me. What version of VS Code and the C/C++ extension are you using?

![image](https://user-images.githubusercontent.com/19859882/104244612-a4c09e80-5417-11eb-8687-b222f7270606.png)

**Comment by DvdFrck** [comment]
I use the latest visual studio code version 1.52.1 and the c/c++ extension. Mingw-w64 I installed the version 8.0.0
