### ISSUE TITLE
namespace "std" has no member "any"

### ISSUE THREAD

**Issue by shreyasm-dev** [microsoft/vscode-cpptools#6756]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS 11.0.1
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions that areinstalled: C++ Intellisense
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- When using `std::any`, it underlines it in red with the message `namespace "std" has no member "any"`, but the code compiles and runs fine

**Steps to reproduce**

1. Create a new C++ file
2. Paste in the following content:
```cpp
#include <any>

int main() {
  std::any xyz = 4;

  return 0;
}
```
3. `std::any` should be underlined in red
4. Compiling and running the code works fine

**Expected behavior**

I would expect it to not display the error message `namespace "std" has no member "any"`.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 1/8/2021, 9:40:21 PM
Version: 1.1.3
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [],
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "compilerPath": "/usr/bin/g++",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/sm/test.cpp ]:
    /Users/sm/test.cpp
Translation Unit Configurations:
[ /Users/sm/test.cpp ]:
    Process ID: 19147
    Memory Usage: 25 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++14
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=120000
Total Memory Usage: 25 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 11210
Number of files discovered (not excluded): 10419
```
</details>

**Screenshots**

<img width="492" alt="Screen Shot 2021-01-08 at 9 52 03 PM" src="https://user-images.githubusercontent.com/62489066/104082424-c0e7f400-51fb-11eb-8b31-98ec1bc7b0d3.png">

**Comment by sean-mcmanus** [comment]
What cppStandard and compilerPath are you using? C/C++: Log Diagnostics output may help as well.

**Comment by sean-mcmanus** [comment]
Ooops -- I didn't see the logs -- your logs show you're using c++14, can you change cppStandard to "c++17"? std::any requires c++17.

**Comment by shreyasm-dev** [comment]
Thanks, that seems to have fixed the problem.
