### ISSUE TITLE
Can I change "breakbeforebraces" for snippets (if, for, while...)?

### ISSUE THREAD

**Issue by RuvymYush** [microsoft/vscode-cpptools#6757]
How it looks now:
if (/* condition */)
{
  /* code */
}

I would like to change so:
if (/* condition */) {
  /* code */
}

**Comment by sean-mcmanus** [comment]
There's no way to do that currently. It's already being tracked by https://github.com/microsoft/vscode-cpptools/issues/5538 or https://github.com/microsoft/vscode-cpptools/issues/3556 . You could upvote those issues.
