### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by zhoujit** [microsoft/vscode-cpptools#6758]
const auto &iter = sliceBucketMap.find(item);

Some case, when I move cursor to sliceBucketMap, it returned below message:
Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object

WSL2/Ubuntu.
Extension version: 1.1.3
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by sean-mcmanus** [comment]
Where is that error appearing? That sounds like .NET runtime exception, but our extension doesn't run any .NET code. Is it from another extension?
