### ISSUE TITLE
VS code is not interpreting __VA_OPT__ correctly.

### ISSUE THREAD

**Issue by m0hithreddy** [microsoft/vscode-cpptools#6759]
**Type: LanguageService**
<VS code not parsing __VA_OPT__ correctly>

**Describe the bug**
- OS and Version: Ubuntu 20.10
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): autoconf
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc). VS code is not interpreting  \_\_VA_OPT\_\_ correctly. Intellisense showing error while there is no error (gcc is successful). Workspace with a single file.

**Steps to reproduce**

1. Create a C file and have the following code in it.

        #include <stdio.h> 

        int set_flags(int first, ...) {
            return first;
        }

        #define set_flags(...) (set_flags)(__VA_ARGS__ __VA_OPT__(,) -1)

        int main() {
            printf("%d %d %d\n", set_flags(), set_flags(2), set_flags(-1));
            return 0;
        }

**Expected behavior**
 Intellisense shouldn't report it as  error. 

<details>
  <summary><strong>Logs</strong></summary>

```
{
	"resource": "/tmp/test1.c",
	"owner": "C/C++",
	"code": "29",
	"severity": 8,
	"message": "expected an expression",
	"source": "C/C++",
	"startLineNumber": 10,
	"startColumn": 34,
	"endLineNumber": 10,
	"endColumn": 43
}
{
	"resource": "/tmp/test1.c",
	"owner": "C/C++",
	"code": "18",
	"severity": 8,
	"message": "expected a ')'",
	"source": "C/C++",
	"startLineNumber": 10,
	"startColumn": 47,
	"endLineNumber": 10,
	"endColumn": 56
}
{
	"resource": "/tmp/test1.c",
	"owner": "C/C++",
	"code": "18",
	"severity": 8,
	"message": "expected a ')'",
	"source": "C/C++",
	"startLineNumber": 10,
	"startColumn": 61,
	"endLineNumber": 10,
	"endColumn": 70
}
```
</details>

**Screenshots**
[https://ibb.co/BNsf3mg](https://ibb.co/BNsf3mg)
**Additional context**

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug against our shared VS parser at https://developercommunity.visualstudio.com/content/problem/1306672/c-intellisense-gives-errors-in-linux-gcc-mode-when.html

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders2, but if you're using gcc on Windows then -fms-extension is getting automatically added with that version, which causes some IntelliSense parsing regressions, which we plan to either fix or switch back to -fno-ms-extensions by default for 1.8.0-insiders3.
