### ISSUE TITLE
#include giving red squiggles even though intellisense and other features are working and includePath is correct

### ISSUE THREAD

**Issue by Kh4n** [microsoft/vscode-cpptools#6760]
**Type: LanguageService**

When in a file, lets say `main.cpp` and try to include something in folder `include`, it will highlight it with red squiggles (see screenshot). Strangely, all other intellisense works, and I can even right click the line and hit "Switch header/source" and it will work flawlessly. The standard includes (eg. `iostream`) do not have this issue; only files that I make and put in my folder have this issue.

`includePath` is already setup properly:
```
{
    "configurations": [
        {
            "name": "Win64",
            "includePath": [
                "${workspaceFolder}/*"
            ],
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ]
            }
        }
    ],
    "version": 4
}
```

**Describe the bug**
- Version: 1.52.1 (system setup)
- OS: Windows_NT x64 10.0.18363
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): 32+ extensions, disabling did not affect

**Steps to reproduce**

1. Make a folder with `main.cpp` and subfolder named `include` and put `Test.hpp` in it
2. Create a `c_cpp_properties.json` with the correct settings
3. See the red squiggles after a line like `#include <Test.hpp>`

**Expected behavior**

No red squiggles

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![annoying](https://user-images.githubusercontent.com/13110513/104155823-9b025100-53ad-11eb-89df-646233d3bdc0.PNG)
**Additional context**

**Comment by Kh4n** [comment]
So, I actually solved the problem as I was writing this: I had another extension called "C/C++ Clang Command Adapter
" (I have no recollection of installing this), and when I uninstalled it, the problem resolved. Hope this can help someone else!

**Comment by sean-mcmanus** [comment]
Yes, multiple users have hit that over the years -- we added code to detect the situation at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/extension.ts#L295 , but we haven't followed up with additional actions yet.
