### ISSUE TITLE
can‘t input data  while debugging my c++ project 

### ISSUE THREAD

**Issue by evancao7** [microsoft/vscode-cpptools#6762]
Type: Debugger

**Describe the bug**
- OS and Version:
![image](https://user-images.githubusercontent.com/39895686/104279274-fd11a200-54e4-11eb-94e6-dd90fdea09f2.png)

- VS Code Version:
![image](https://user-images.githubusercontent.com/39895686/104279327-131f6280-54e5-11eb-9408-032d4cc0eb86.png)

- C/C++ Extension Version:v1.1.3
- Other extensions you installed (and if the issue persists after disabling them):
![image](https://user-images.githubusercontent.com/39895686/104279352-1d416100-54e5-11eb-969d-835a9093ccad.png)

- A clear and concise description of what the bug is.
- When attempting to debug a simple C++ script that requires user‘s input, the terminal doesn't allow me to input anything but command line.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

code
```
#include <bits/stdc++.h>
using namespace std;

int main( ){
    int a=1;
    for (int i=0;i<3;i++){
        cin>>a;
        cout<<i<<" "<<a<<" ";
    }
    return 0;
}
```
launch
```
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": ["<", "input_file.in"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: g++ build active file"
        }
    ]
}
```
1. i set the breakpoint at cin>>a;
2. Click on start debugging
3. and i cant find the place for me to input data, as is shown in the pic
![image](https://user-images.githubusercontent.com/39895686/104280038-457d8f80-54e6-11eb-9842-33a33c50be65.png)

4. and as i click on step over the program is stuck. the only thing i can do is to stop as shown in the pic
5. 
![image](https://user-images.githubusercontent.com/39895686/104280257-97beb080-54e6-11eb-88ff-3c77aa10ad5f.png)

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

it has puzzled me for a long time thx for your help!

**Comment by evancao7** [comment]
Now i installed CodeLLDB 
my launch :
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {   
            "preLaunchTask": "C/C++: g++ build active file",
            "type": "lldb",
            "request": "launch",
            "name": "Debug",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "terminal": "external",
            "args": [],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```
it can recognize my breakpoint ,but i still can't input number, and the "please enter a: " didn't show up 
![image](https://user-images.githubusercontent.com/39895686/104305079-31965580-5507-11eb-9e34-9fe7b5baa0b9.png)

**Comment by WardenGnaw** [comment]
> Now i installed CodeLLDB
> my launch :
> 
> ```
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {   
>             "preLaunchTask": "C/C++: g++ build active file",
>             "type": "lldb",
>             "request": "launch",
>             "name": "Debug",
>             "program": "${fileDirname}/${fileBasenameNoExtension}",
>             "terminal": "external",
>             "args": [],
>             "cwd": "${workspaceFolder}"
>         }
>     ]
> }
> ```
> 
> it can recognize my breakpoint ,but i still can't input number, and the "please enter a: " didn't show up
> ![image](https://user-images.githubusercontent.com/39895686/104305079-31965580-5507-11eb-9e34-9fe7b5baa0b9.png)

We do not own `type: "lldb"`, you will want to post that error at https://github.com/vadimcn/vscode-lldb/issues

For the original post, does using externalConsole: true not work for `cppdbg`?

**Comment by evancao7** [comment]
Thank you ,Andrew.
I upgraded my mac os to Big Sur yesterday and the "externalConsole: true" way works in a sense, but not perfect. 
There are several questions:
Fitst: It seems that the debug process is lagging and i don't how to fix it. For example:
![image](https://user-images.githubusercontent.com/39895686/104405819-d57c1180-5598-11eb-8208-33650b5ad268.png)
1.this loop has run once but 2.the output didn't show up as supposed.

![image](https://user-images.githubusercontent.com/39895686/104405906-09efcd80-5599-11eb-9a14-b4f6cbaff75f.png)
it didn't show up in the terminal until i am at "cin>>a" command line again.

Second:
![image](https://user-images.githubusercontent.com/39895686/104406124-884c6f80-5599-11eb-911f-702099611480.png)
1.i am expecting to see ans[0],ans[1] what can i do?
2.can i just use the integrated terminal rather than the externalConsole?
here is my launch
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: g++ build active file"
        }
    ]
}
```

**Comment by evancao7** [comment]
@WardenGnaw

**Comment by WardenGnaw** [comment]
> 1.i am expecting to see ans[0],ans[1] what can i do?
This is the behavior of C++. you need to flush your output or it will be buffered.
E.g.
```
cout<<i<<" "<<a<<" "<endl
```
> 2.can i just use the integrated terminal rather than the externalConsole?
This needs to be investigated, it should allow redirecting output to the intergrated terminal.
