### ISSUE TITLE
Intellisense extremely slow while in remote container

### ISSUE THREAD

**Issue by enricocirignaco** [microsoft/vscode-cpptools#6763]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows Version 10.0.18363 Build 18363
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): 
- C++ Intellisense
- Cortex-Debug
- Remote Containers
- Issue persist if other extensions are disabled.

- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
If the project is open on local machine instellisense is extremly fast. When I reopen the workspace in the container I have to press ctrl+space and after around 10 seconds the menu will appear. Tried to manually run gtags. The behaviour doesn't change.

**Steps to reproduce**

1. Open C/C++ project in a docker container
2. Open main.c file 
3. Start typing something
3. Press ctrl+space
4. Wait 10-20 seconds for the menu to appear

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 1/12/2021, 2:18:34 PM
Version: 1.1.3
Current Configuration:
{
    "name": "test",
    "intelliSenseMode": "gcc-x64",
    "includePath": [
        "${workspaceFolder}",
        "Core/Inc",
        "Drivers/STM32F0xx_HAL_Driver/Inc",
        "Drivers/STM32F0xx_HAL_Driver/Inc/Legacy",
        "Drivers/CMSIS/Device/ST/STM32F0xx/Include",
        "Drivers/CMSIS/Include",
        "Drivers/CMSIS/Include",
        "/usr/local/lib/gcc/arm-none-eabi/10.2.1/include"
    ],
    "browse": {
        "path": [
            "${workspaceFolder}",
            "Core/Inc",
            "Drivers/STM32F0xx_HAL_Driver/Inc",
            "Drivers/STM32F0xx_HAL_Driver/Inc/Legacy",
            "Drivers/CMSIS/Device/ST/STM32F0xx/Include",
            "Drivers/CMSIS/Include",
            "Drivers/CMSIS/Include",
            "/usr/local/lib/gcc/arm-none-eabi/10.2.1/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    },
    "defines": [
        "USE_HAL_DRIVER",
        "STM32F031x6",
        "VERSION=\\\"$(shell python .vscode/git_version.py)\\\""
    ],
    "forcedInclude": [],
    "compilerPath": "/usr/local/bin/arm-none-eabi-gcc",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true
}
Translation Unit Mappings:
[ /workspaces/test/Core/Src/main.c ]:
    /workspaces/test/Core/Src/main.c
Translation Unit Configurations:
[ /workspaces/test/Core/Src/main.c ]:
    Process ID: 5857
    Memory Usage: 0 MB
    Compiler Path: /usr/local/bin/arm-none-eabi-gcc
    Includes:
        /workspaces/test
        /workspaces/test/Core/Inc
        /workspaces/test/Drivers/STM32F0xx_HAL_Driver/Inc
        /workspaces/test/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy
        /workspaces/test/Drivers/CMSIS/Device/ST/STM32F0xx/Include
        /workspaces/test/Drivers/CMSIS/Include
        /usr/local/lib/gcc/arm-none-eabi/10.2.1/include
        /usr/local/lib/gcc/arm-none-eabi/10.2.1/include-fixed
        /usr/local/arm-none-eabi/include
    Defines:
        USE_HAL_DRIVER
        STM32F031x6
        VERSION=\"$(shell python .vscode/git_version.py)\"
    Standard Version: c11
    IntelliSense Mode: gcc-arm
    Other Flags:
        --gcc
        --gnu_version=100201
Total Memory Usage: 0 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 3092
Number of files discovered (not excluded): 2705




```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
The "0 MB" in the logs is not normal. What is the memory and CPU usage of the cpptools and cpptools-srv processes?

**Comment by enricocirignaco** [comment]
Sorry for the late answer.
CPU Usage of single Processes is around 20%.
htop executed in the container while intellisense window is loading:
![2021-01-15 09_32_20-Window](https://user-images.githubusercontent.com/61552432/104701011-53652780-5715-11eb-9ab8-136fba65d0e4.png)
Local Machine CPU Load never exeed 30% while window is loading

**Comment by sean-mcmanus** [comment]
The IntelliSense process cpptools-srv is using the 30% CPU. That CPU usage seems low if I'm interpreting it correctly. That could mean there's a disk usage issue. Can you try setting your C_Cpp.intelliSenseCacheSize setting to 0 to see if that improves the performance (you might need to do a Reload Window afterwards)?

**Comment by enricocirignaco** [comment]
I put the Cache setting in the Settings.json file situated in the .vscode folder in the project folder.
The settings file looks lie that:
`{
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseCacheSize": 0
}`
I didn't notice any changes. I also tryed to restart vscode. The Delay still there.

**Comment by enricocirignaco** [comment]
I Tried to replicate the same issue on a MacBook running MacOS Big Sur 11.1. Here there are no problems, Intellisense is responsive on local machine and in the docker container.

**Comment by enricocirignaco** [comment]
I tried to run C/C++ Log on MacOS and memory usage still 0MB

`-------- Diagnostics - 1/19/2021, 10:12:15 AM
Version: 1.1.3
Current Configuration:
{
    "name": "test",
    "intelliSenseMode": "gcc-x64",
    "includePath": [
        "${workspaceFolder}",
        "Core/Inc",
        "Drivers/STM32F0xx_HAL_Driver/Inc",
        "Drivers/STM32F0xx_HAL_Driver/Inc/Legacy",
        "Drivers/CMSIS/Device/ST/STM32F0xx/Include",
        "Drivers/CMSIS/Include",
        "Drivers/CMSIS/Include",
        "/usr/local/lib/gcc/arm-none-eabi/10.2.1/include"
    ],
    "browse": {
        "path": [
            "${workspaceFolder}",
            "Core/Inc",
            "Drivers/STM32F0xx_HAL_Driver/Inc",
            "Drivers/STM32F0xx_HAL_Driver/Inc/Legacy",
            "Drivers/CMSIS/Device/ST/STM32F0xx/Include",
            "Drivers/CMSIS/Include",
            "Drivers/CMSIS/Include",
            "/usr/local/lib/gcc/arm-none-eabi/10.2.1/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    },
    "defines": [
        "USE_HAL_DRIVER",
        "STM32F031x6",
        "VERSION=\\\"$(shell python .vscode/git_version.py)\\\""
    ],
    "forcedInclude": [],
    "compilerPath": "/usr/local/bin/arm-none-eabi-gcc",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true
}
Translation Unit Mappings:
[ /workspaces/test/Core/Src/main.c ]:
    /workspaces/test/Core/Src/main.c
Translation Unit Configurations:
[ /workspaces/test/Core/Src/main.c ]:
    Process ID: 1115
    Memory Usage: 0 MB
    Compiler Path: /usr/local/bin/arm-none-eabi-gcc
    Includes:
        /workspaces/test
        /workspaces/test/Core/Inc
        /workspaces/test/Drivers/STM32F0xx_HAL_Driver/Inc
        /workspaces/test/Drivers/STM32F0xx_HAL_Driver/Inc/Legacy
        /workspaces/test/Drivers/CMSIS/Device/ST/STM32F0xx/Include
        /workspaces/test/Drivers/CMSIS/Include
        /usr/local/lib/gcc/arm-none-eabi/10.2.1/include
        /usr/local/lib/gcc/arm-none-eabi/10.2.1/include-fixed
        /usr/local/arm-none-eabi/include
    Defines:
        USE_HAL_DRIVER
        STM32F031x6
        VERSION=\"$(shell python .vscode/git_version.py)\"
    Standard Version: c11
    IntelliSense Mode: gcc-arm
    Other Flags:
        --gcc
        --gnu_version=100201
Total Memory Usage: 0 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 3240
Number of files discovered (not excluded): 2702
Number of files parsed: 1266

`

**Comment by sean-mcmanus** [comment]
Is the 0 MB on the local Mac or in docker? The 0 MB might just be a logging issue...it might not affect IntelliSense.

**Comment by enricocirignaco** [comment]
the 0MB is in the container. If I run C/C++ Diagnostic on the mac the line with the total memory usage doesn't even appear.

Log from the mac (local machine):
```
-------- Diagnostics - 1/22/2021, 8:37:00 AM
Version: 1.1.3
Current Configuration:
{
    "name": "stm32_training",
    "intelliSenseMode": "gcc-x64",
    "includePath": [
        "${workspaceFolder}",
        "Core/Inc",
        "Drivers/STM32F0xx_HAL_Driver/Inc",
        "Drivers/STM32F0xx_HAL_Driver/Inc/Legacy",
        "Drivers/CMSIS/Device/ST/STM32F0xx/Include",
        "Drivers/CMSIS/Include",
        "Drivers/CMSIS/Include",
        "/usr/local/lib/gcc/arm-none-eabi/10.2.1/include"
    ],
    "browse": {
        "path": [
            "${workspaceFolder}",
            "Core/Inc",
            "Drivers/STM32F0xx_HAL_Driver/Inc",
            "Drivers/STM32F0xx_HAL_Driver/Inc/Legacy",
            "Drivers/CMSIS/Device/ST/STM32F0xx/Include",
            "Drivers/CMSIS/Include",
            "Drivers/CMSIS/Include",
            "/usr/local/lib/gcc/arm-none-eabi/10.2.1/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    },
    "defines": [
        "USE_HAL_DRIVER",
        "STM32F031x6",
        "VERSION=\\\"$(shell python .vscode/git_version.py)\\\"",
        "VERSION=\\\"$(shell python /workspaces/stm32_training/.vscode/git_version.py)\\\""
    ],
    "forcedInclude": [],
    "compilerPath": "/usr/local/bin/arm-none-eabi-gcc",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true
}
No active translation units.

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 2614
Number of files discovered (not excluded): 1856
Number of files parsed: 228
```

**Comment by sean-mcmanus** [comment]
On the Mac, did you open a C/C++ file and wait for the flame icon to disappear? It shows "No active translation" unit, which means the IntelliSense process hasn't launched.

**Comment by enricocirignaco** [comment]
@sean-mcmanus  do you have some news? Do you know if the bug will be fixed in future updates?

**Comment by sean-mcmanus** [comment]
No news. We don't know what could be causing this and we haven't investigated a repro yet. We haven't received similar complaints from other users yet.

**Comment by sean-mcmanus** [comment]
@enricocirignaco We were not able to repro the issue in a docker container. You may want to try disabling the "C++ IntelliSense" extension, which could randomly be interfering with our functionality. You could also try to gather perf logs (https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues) or call stacks (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) when the slowness occurs. Also, setting C_Cpp.loggingLevel to "Debug" and viewing the "C/C++" logs might also help show what is causing the slowness.
