### ISSUE TITLE
Symbols limit to 1000 per file

### ISSUE THREAD

**Issue by jenuc78** [microsoft/vscode-cpptools#6766]
**Type: LanguageService**

C/C++

**Describe the bug**
- OS and Version: WSL2
- VS Code Version: 1.53.0-insider
- C/C++ Extension Version: v1.1.3
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
-

**Steps to reproduce**

1. Go to '...' Ctrl+Alt+O on C header with more than 1000 symbols

**Expected behavior**

To display all symbols from file, or to provide a way to increase limit

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/76923885/104370376-6dd9ae00-5527-11eb-8c9a-c2e38b5f08e2.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
The main issue to investigate would be if there's some performance issue with returning too many results to VS Code.

**Comment by sean-mcmanus** [comment]
https://github.com/microsoft/vscode/issues/28400 suggests 10000 is reasonable and results only take around a couple seconds. Does 10k seem like enough for your scenario or did you still want some setting to increase that?

**Comment by jenuc78** [comment]
> [microsoft/vscode#28400](https://github.com/microsoft/vscode/issues/28400) suggests 10000 is reasonable (although that's in the context of completion results and not symbols) and results only take around a couple seconds. Does 10k seem like enough for your scenario or did you still want some setting to increase that?

Yes, 10k would be enough for our case, thank you

**Comment by jenuc78** [comment]
Hello I see now that limit was increased, but the (Ctrl+T) Go To Symbols Workspace is not working anymore. Is there a connection with this fix?

**Comment by sean-mcmanus** [comment]
I've filed a new issue at https://github.com/microsoft/vscode-cpptools/issues/6793 . It is highly unlikely that this change caused the workspace symbol failure, but we'll find out. We have a cpptools test case that covers workspace symbol search, so my guess is that it's failing somewhere in our TypeScript layer (which has less automated test coverage).

**Comment by jenuc78** [comment]
Thank you
