### ISSUE TITLE
lldb: Unrecognized format of field "threads" in result

### ISSUE THREAD

**Issue by ajax16384** [microsoft/vscode-cpptools#6770]
Type: Debugger

**Describe the bug**
- OS and Version: MacOS 11.1
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3

Breakpoint at program lldb debug session stop whole debug process

````
<--   C (threads-14): {"command":"threads","type":"request","seq":14}
--> R (threads-14): {"type":"response","request_seq":14,"success":true,"command":"threads","body":{"threads":[{"id":23,"name":"Thread #23"},{"id":22,"name":"Thread #22"},{"id":-25,"name":"Thread #-25"},{"id":-24,"name":"Thread #-24"},{"id":-23,"name":"Thread #-23"},{"id":18,"name":"Thread #18"},{"id":17,"name":"Thread #17"},{"id":16,"name":"Thread #16"},{"id":-22,"name":"Thread #-22"},{"id":-21,"name":"Thread #-21"},{"id":-20,"name":"Thread #-20"},{"id":-19,"name":"Thread #-19"},{"id":-18,"name":"Thread #-18"},{"id":-17,"name":"Thread #-17"},{"id":9,"name":"Thread #9"},{"id":-16,"name":"Thread #-16"},{"id":-15,"name":"Thread #-15"},{"id":-14,"name":"Thread #-14"},{"id":5,"name":"Thread #5"},{"id":4,"name":"Thread #4"},{"id":3,"name":"Thread #3"},{"id":2,"name":"Thread #2"},{"id":24,"name":"Thread #24"},{"id":25,"name":"Thread #25"},{"id":26,"name":"Thread #26"},{"id":-26,"name":"Thread #-26"},{"id":-27,"name":"Thread #-27"}]},"seq":2072}
--> E (output): {"type":"event","event":"output","body":{"category":"stderr","output":"ERROR: Error while trying to enter break state. Debugging will now stop. Unrecognized format of field \"threads\" in result: result-class: done\r\n\n"},"seq":2074}
ERROR: Error while trying to enter break state. Debugging will now stop. Unrecognized format of field "threads" in result: result-class: done
````

````json
            "externalConsole": false,
            "showDisplayString": true,
            "MIMode": "lldb",
            "logging": {
                "trace": true,
                "traceResponse": true,
            }

````

**Comment by ajax16384** [comment]
'1.2.0-preview' has same issue

**Comment by WardenGnaw** [comment]
This may be an issue with macOS Big Sur (11.1).

The latest machine we have tested the debugging scenario is 10.15 (Catalina)

**Comment by ajax16384** [comment]
Nop it's not related to Big Sur, also can be reproduced on catalina.

I finally find out fault sequence:

````
...
frame={level="2",addr="0x00000001000d3719",func=""-[TCocoaClass mouseMoved:]"",
...
E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (9590) MI parsing error: Unexpected list termination: \"-[TCocoaClass mouseMoved:]\"\"
````

For some strange reason dwarf function declaration contains quotes. LLDB can deal with such nonsense:

````
(lldb) s
Process 40791 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = step in
    frame #0: 0x0000000100002c21 testsym`"-[TCocoaClass mouseMoved:]"(self=0x0000000101004730, _cmd="mouseMoved:", AEVENT=0x0000000000000000) at testsym
````

But lldb-mi (or MIEngine - do not know who shoulf be blamed first) does not escape quotes and MIEngine fails to parse output.

**Comment by WardenGnaw** [comment]
> frame={level="2",addr="0x00000001000d3719",func=""-[TCocoaClass mouseMoved:]"",
It looks like lldb-mi is not escaping `func` from the `frame` response when it gives it back to MIEngine. 

It should be:
```
frame={level="2",addr="0x00000001000d3719",func="\"-[TCocoaClass mouseMoved:]\"",
```

**Comment by ajax16384** [comment]
> > frame={level="2",addr="0x00000001000d3719",func=""-[TCocoaClass mouseMoved:]"",
> > It looks like lldb-mi is not escaping `func` from the `frame` response when it gives it back to MIEngine.
> 
> It should be:
> 
> ```
> frame={level="2",addr="0x00000001000d3719",func="\"-[TCocoaClass mouseMoved:]\"",
> ```

You're quite right. So it must be lldb-mi adapter bug? (It should escape quotes for "func=" output)
https://github.com/lldb-tools/lldb-mi/blob/de66243aabfb2526d5828e0beb5a0f99e1b27ed7/src/MICmnLLDBDebugSessionInfo.cpp#L631
https://github.com/lldb-tools/lldb-mi/blob/de66243aabfb2526d5828e0beb5a0f99e1b27ed7/src/MICmnLLDBDebugSessionInfo.cpp#L723
https://github.com/lldb-tools/lldb-mi/blob/de66243aabfb2526d5828e0beb5a0f99e1b27ed7/src/MICmnLLDBDebuggerHandleEvents.cpp#L1394
