### ISSUE TITLE
Can't pause or add breakpoints when running gdb with sudo priviledges

### ISSUE THREAD

**Issue by pmattione** [microsoft/vscode-cpptools#6778]
Type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 20.04.1 LTS
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3

When debugging my programming by launching gdb with root permissions, I cannot pause the debugger with the pause button, nor can I add breakpoints after execution has started.  Breakpoints set before launch do work however.  I need this to work because I'm running a web server and cannot bind to port 80 without root permissions. 

My launch.json:
```
"configurations": [
	{
		"name": "(gdb) MyProgram",
		"type": "cppdbg",
		"request": "launch",
		"program": "${workspaceFolder}/build/MyProgram",
		"args": [],
		"stopAtEntry": false,
		"cwd": "${workspaceFolder}",
		"environment": [],
		"externalConsole": false,
		"MIMode": "gdb",
		"miDebuggerPath": "/usr/bin/gdbsudo",
		"setupCommands": [
			{
				"description": "Enable pretty-printing for gdb",
				"text": "-enable-pretty-printing",
				"ignoreFailures": true
			}
		],
		"logging": {
			"engineLogging": true,
			"trace": true,
			"traceResponse": true
		 }
	}
```

My /usr/bin/gdbsudo:
```
#!/bin/sh
sudo gdb $@
```

Program you can repro with.  Just try to pause or set a breakpoint while its running:
```
#include <chrono>
#include <thread>
#include <iostream>

int main(void)
{
	static constexpr std::chrono::seconds sSleepTime{ 1 };
	size_t loop_count = 0;
	while(true)
	{
		std::cout << loop_count++ << "\n";
		std::this_thread::sleep_for(sSleepTime);
	}
	return 0;
}
```

Debug Console upon Pause:
 ```
<--   C (pause-9): {"command":"pause","arguments":{"threadId":50373},"type":"request","seq":9}
--> R (pause-9): {"type":"response","request_seq":9,"success":true,"command":"pause","body":{},"seq":829}
```

**Comment by WardenGnaw** [comment]
We have support for attaching to a process with root permissions, I'll double check the way to launch GDB with the correct permissions.

For attach we use `pkexec` so a dialog shows up for elevation. Do you get that password prompt with your gdbsudo script?

**Comment by pmattione** [comment]
No, I ran visudo and added the following so that it would launch without entering permissions:

`<username> ALL=(ALL:ALL) NOPASSWD:/usr/bin/gdb`
