### ISSUE TITLE
[Big Sur M1] ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (attach failed ((os/kern) invalid argument))

### ISSUE THREAD

**Issue by wzh4464** [microsoft/vscode-cpptools#6779]
Type: Debugger

**Describe the bug**
- OS and Version: macOS Big Sur 11.1 M1 Chip
- VS Code Version: VSCode - Insiders 1.53.0
- C/C++ Extension Version: 1.2.0-preview
- Other extensions you installed (and if the issue persists after disabling them): no
- I run a simple c++ profile and the debug console shows like the title. And if I run g++ in the terminal it works all good.

**To Reproduce**

```
#include <iostream>
using namespace std;
int main()
{
    cout << "hello world" <<endl; 
    return 0;
}
```
launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "clang++ - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "arm",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang++ 生成活动文件"
        }
    ],
    "logging": { "engineLogging": true, "trace": true, "traceResponse": true }
}
```
c_cpp_properties.json
```{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++98",
            "intelliSenseMode": "clang-arm",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

Debug Console
```
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (attach failed ((os/kern) invalid argument))
The program '/private/tmp/vscode/main' has exited with code 42 (0x0000002a).
```
Terminal
```
> Executing task: C/C++: clang++ 生成活动文件 <

正在启动生成...
生成已成功完成。

Terminal will be reused by tasks, press any key to close it.
```

**Comment by WardenGnaw** [comment]
We do not have support for the Apple M1 Chips. See https://github.com/microsoft/vscode-cpptools/issues/6595

**Comment by wzh4464** [comment]
@WardenGnaw I thought the preview version supports Apple Silicon, doesn't it?

**Comment by sean-mcmanus** [comment]
@wzh4464 1.2.0-preview disabled the blocking of the extension from running on Mac M1 so that the language service features can work, but the binaries are not built natively for arm64 (https://github.com/microsoft/vscode-cpptools/issues/6595) .

**Comment by wzh4464** [comment]
@WardenGnaw OK, I see it now. Thank you!

**Comment by michelleangela** [comment]
Created a separate issue to track supporting debugger binaries to run natively on M1 https://github.com/microsoft/vscode-cpptools/issues/7035

**Comment by CarterGunale** [comment]
Same issue ,did you solve?

**Comment by markfaction** [comment]
Having the same issue on Apple M1, while following this guide - https://code.visualstudio.com/docs/cpp/config-clang-mac.

**Comment by michelleangela** [comment]
@CarterGunale, @markfaction 
The feature to support native debugging on Apple Silicon ARM64 has not been done yet. You can run the current debugger binaries built for Apple Intel x64 using the Rosetta emulator. Note that the debugger for Apple Intel x64 can only debug x86_64 binaries. Please see issue #7035.

**Comment by GregNumworks** [comment]
@michelleangela could you explain how to do that ? I mean how to 1) compile for x86 and 2) how to call the debugger on it ?

**Comment by theBeginner86** [comment]
@GregNumworks 
I would suggest you to use CodeLLDB debugger (vadimcn.vscode-lldb). It's an extension in VSCode and works exactly like the native debugger in VSCode. For its setup, you just need to change the configuration of your launch.json file with the one provided by the extension. And that should do the trick. 

Now if you would try to debug then, VSCode will make use of that extension and should be able to debug your programs as it was to be done by the native debugger.

I am personally using it on my M1 chip MacBook Air, and it works perfectly fine. It's much easier to implement than other workarounds present at the moment.

**Comment by GregNumworks** [comment]
Wow @theBeginner86 you changed my life thanks ! I've been debugging from a terminal for months now.

**Comment by theBeginner86** [comment]
> Wow @theBeginner86 you changed my life thanks ! I've been debugging from a terminal for months now.

No problem. Happy to help.😁
Even I was stuck with this for more than a month but after researching for some weeks I found that workaround.

**Comment by AlaNLrdE** [comment]
the

> @GregNumworks
> I would suggest you to use CodeLLDB debugger (vadimcn.vscode-lldb). It's an extension in VSCode and works exactly like the native debugger in VSCode. For its setup, you just need to change the configuration of your launch.json file with the one provided by the extension. And that should do the trick.
> 
> Now if you would try to debug then, VSCode will make use of that extension and should be able to debug your programs as it was to be done by the native debugger.
> 
> I am personally using it on my M1 chip MacBook Air, and it works perfectly fine. According to me, It's much easier to implement than other workarounds present at the moment.

You saved my life! thanks for the help 👍

**Comment by raphaelleveque** [comment]
``> > Wow @theBeginner86 you changed my life thanks ! I've been debugging from a terminal for months now.
> 
> Happy to help.😁
> Even I was stuck with this for more than a month but after researching for some weeks I found that workaround.

Hey, can you help me with that? I'm a new CS student and i'm struggling to debug my c programs on my m1 mac.
I installed this extension but i cant debug, it only runs the code. I can't see the "yellow line" that goes through my program.

My program is in a folder called teste, and in this folder i have my program teste.c, the teste executable and the .vscode, which has my launch.json file

I just copied in the launch.json file the minimal configuration, and now my launch.json file is:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "lldb",
            "request": "launch",
            "program": "${workspaceFolder}/teste",
            "args": ["-arg1", "-arg2"],
        }
    ]
}`

The debug console console shows this:
`Launching: /Users/raphaellev/Desktop/teste.c/teste -arg1 -arg2
Launched process 29733
Process exited with code 0.
`

 
Can you help me? that would really help me?

**Comment by theBeginner86** [comment]
> ``> > Wow @theBeginner86 you changed my life thanks ! I've been debugging from a terminal for months now.
> 
> > Happy to help.😁
> > Even I was stuck with this for more than a month but after researching for some weeks I found that workaround.
> 
> Hey, can you help me with that? I'm a new CS student and i'm struggling to debug my c programs on my m1 mac.
> I installed this extension but i cant debug, it only runs the code. I can't see the "yellow line" that goes through my program.
> 
> My program is in a folder called teste, and in this folder i have my program teste.c, the teste executable and the .vscode, which has my launch.json file
> 
> I have just copied in the launch.json file the minimal configuration, and now my launch.json file is:
> `{ "version": "0.2.0", "configurations": [ { "name": "Launch", "type": "lldb", "request": "launch", "program": "${workspaceFolder}/teste", "args": ["-arg1", "-arg2"], } ] }`
> 
> The debug console console shows this:
> `Launching: /Users/raphaellev/Desktop/teste.c/teste -arg1 -arg2 Launched process 29733 Process exited with code 0. `
> 
> Can you help me? that would really help me

I know it is obvious. But just wanted to confirm, have you placed the breakpoints? These breakpoints help the debugger to detect where to stop and show you the values in variables.
For more info, check out: https://code.visualstudio.com/docs/editor/debugging

I tried debugging the code without breakpoints, then it is behaving in a similar way as you described, i.e just running the code without debugging. Rest everything which you described seems fine.

**Comment by raphaelleveque** [comment]
> Rest everything which you described seems fine. 👍

Yes i put the red dot inside my main function, but once i run the code, the breakpoint turns into a black point (when i put my cursor on it, it shows: Locations: 0), and not into the yellow line as expected.

I don't know if this matters but i run my c programs using gcc installed from homebrew (although i also have my gcc from apple's developpers toolkit)

lldb-1205.0.27.3
Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)

Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

gcc-11 (Homebrew GCC 11.1.0) 11.1.0

**Comment by theBeginner86** [comment]
> <img alt="Screen Shot 2021-06-23 at 01 37 34" width="1440" src="https://user-images.githubusercontent.com/81882870/123036587-b2fde800-d3c3-11eb-95a8-996799eabe1a.png">
> 
> > Rest everything which you described seems fine. 👍
> Yes i put the red dot inside my main function, but once i run the code, the breakpoint turns into a black point (when i put my cursor on it, it shows: Locations: 0), and not into the yellow line as expected.
> 
> I don't know if this matters but i run my c programs using gcc installed from homebrew (although i also have my gcc from apple's developpers toolkit)
> 
> lldb-1205.0.27.3
> Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
> 
> Apple clang version 12.0.5 (clang-1205.0.22.9)
> Target: arm64-apple-darwin20.4.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> 
> gcc-11 (Homebrew GCC 11.1.0) 11.1.0

I am not sure about it.
BTW I am using clang++ as the compiler.
Try changing the compiler to clang++, if you are using something different. Even VSCode documentation for setting C/C++ programs is demonstrated using clang++. You can refer to this link: https://code.visualstudio.com/docs/cpp/config-clang-mac
After this change the task.json to the one you get from the CodeLLDB extension. 
Personally, I proceeded like this.

**Comment by raphaelleveque** [comment]
@theBeginner86 it worked, thanks
I just needed to change my .json files for these ones https://www.programmersought.com/article/42826675760/

**Comment by MudrakshnMcShaw** [comment]
> https://www.programmersought.com/article/42826675760/

Thank you so much. Worked great for me on MacOS Monterey.

**Comment by Aditya-D96** [comment]
> @theBeginner86 it worked, thanks
> I just needed to change my .json files for these ones https://www.programmersought.com/article/42826675760/

Thanks. Worked for me on macOS Monterey

**Comment by chdorian-logitech** [comment]
> > @theBeginner86 it worked, thanks
> > I just needed to change my .json files for these ones https://www.programmersought.com/article/42826675760/
> 
> Thanks. Worked for me on macOS Monterey with M1 MacBook Air

Many thanks! After 2 days of searching and trying all the different options, this one finally worked for me too! 

`Mac Mini M1, Big Sur 11.0`

**Comment by mosmar99** [comment]
> > > @theBeginner86 it worked, thanks
> > > I just needed to change my .json files for these ones https://www.programmersought.com/article/42826675760/
> > 
> > 
> > Thanks. Worked for me on macOS Monterey with M1 MacBook Air
> 
> Many thanks! After 2 days of searching and trying all the different options, this one finally worked for me too!
> 
> `Mac Mini M1, Big Sur 11.0`

It worked for me aswell, although, ONLY for C++. 
--> Is there corresponding way around to debug in C?

**Comment by gtn1024** [comment]
> @GregNumworks I would suggest you to use CodeLLDB debugger (vadimcn.vscode-lldb). It's an extension in VSCode and works exactly like the native debugger in VSCode. For its setup, you just need to change the configuration of your launch.json file with the one provided by the extension. And that should do the trick.
> 
> Now if you would try to debug then, VSCode will make use of that extension and should be able to debug your programs as it was to be done by the native debugger.
> 
> I am personally using it on my M1 chip MacBook Air, and it works perfectly fine. According to me, It's much easier to implement than other workarounds present at the moment.

Special Thanks to you!!!

**Comment by trinitronx** [comment]
I ran into this issue when setting up debugging with `gdb` / `lldb` in VSCode (yeah, Xcode CLT uses LLVM / LLDB even for GCC binary now).  This will be an issue with using `vscode-cpptools` / `ms-vscode.cpptools` extension with any newer Arm64 / AArch64 Apple hardware (M1, M1 Pro / Max CPU chips).  I figured that I should share this here in case anyone is taking this course while using this newer Apple hardware.

### Related VSCode issues:

- vscode-cpptools#7035
- vscode-cpptools#376
- vscode-cpptools#5079

While others are finding workarounds using alternative VSCode plugin, this config uses the official Micro$oft  extension.  So, here's what I did to "fix" (_**cough**_ workaround ) the issue on macOS Monterey 12.1 macBook with an Apple M1 Pro chip.

## Minimal "helloworld" Setup:

Apple has added some new security features that prevent debuggers from attaching to a process.  You can either try to launch it and hope the GUI window pops up to allow it, or just enable "Developer Mode" (recommended if you're going to be coding & developing software).

First, we need to enable Developer Mode for XCode + CLT:

```bash
DevToolsSecurity -status
# You need to enable it if this returns: Developer mode is currently disabled.
DevToolsSecurity -enable
# Prompts for user's password
# If enabled it returns: Developer mode is now enabled.
# Make sure your user is either in one of (or both): admin or _developer groups
groups
# should output list of groups.. check for "admin" or "_developer"
# If you're not in either group, add yourself to them:
sudo dseditgroup -o edit -a $USER -t user _developer
sudo dseditgroup -o edit -a $USER -t user admin
```

Next, set `targetArchitecture`  and `miDebuggerArgs` in `launch.json`

`$ cat .vscode/launch.json`
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "x86_64",  // <= ADD this!
            "program": "${workspaceFolder}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
// ADD the following section
            "osx": {
                "MIMode": "lldb",
                "miDebuggerArgs": "--arch x86_64"
            }
        }
    ]
}
```

Finally, we need to tell `gcc` / `clang` to build the `x86_64` target (Minimal config at least to get debug for `x86_64` architecture working!)

`cat .vscode/tasks.json`

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build hello world (x86_64)", // Optional: Name this task for arch
            "type": "shell",
            "command": "clang",
            "args": [
                "-arch", "x86_64", // <= ADD this line
                "-g",
                "-o",
                "helloworld.x86_64", // <= NOTE: arch-specific suffix (not needed for this minimal config, but pay attention for later)
                "helloworld.c"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

This should get minimal build & debug working again in small projects using VSCode with stock `llvm` / `lldb` (GCC / gdb) on M1 Macs!

## Optional Universal Setup:

This will allow you to build "Universal" `Mach-O` binaries (both `x86_64` and `aarch64` / `arm64` in one wrapped binary file).  It's also without using hardcoded "`helloworld.c`" filenames in the build task config.

References:
- https://code.visualstudio.com/docs/cpp/launch-json-reference
- https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

This configuration is more advanced but will build universal binaries on macOS using VSCode.  (Note: CMake & Makefile syntax also are options, as in the Apple Developer guide, but that's out of scope for me to figure out right now...)

We need to configure build tasks for both architectures, then combine them into a universal `Mach-O` binary.  The debug launch command will just use the one compiled for `x86_64`.

This is probably the only way to debug for now because, unfortunately, it seems like VSCode's latest version of `ms-vscode.cpptools-1.7.1` extension only ships with the `x86_64` binary for `lldb-mi`:

```bash
$ file  ~/.vscode/extensions/ms-vscode.cpptools-1.7.1/debugAdapters/lldb-mi/bin/lldb-mi
~/.vscode/extensions/ms-vscode.cpptools-1.7.1/debugAdapters/lldb-mi/bin/lldb-mi: Mach-O 64-bit executable x86_64
```

Here are the configuration files needed for this setup:

`cat .vscode/launch.json`

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "x86_64",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}.x86_64",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "osx": {
                "preLaunchTask": "build (x86_64)",
                "MIMode": "lldb",
                "miDebuggerArgs": "--arch x86_64"
            }
        }
    ]
}
```

`cat .vscode/tasks.json`
```bash
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build (x86_64)",
            "type": "shell",
            "command": "clang",
            "args": [
                "-arch", "x86_64",
                "-g",
                "-o",
                "${workspaceFolder}/${fileBasenameNoExtension}.x86_64",
                "${fileDirname}/${fileBasename}"
            ],
            "group": "build"
        },
        {
            "label": "build (arm64)",
            "type": "shell",
            "command": "clang",
            "args": [
                "-arch", "arm64",
                "-g",
                "-o",
                "${workspaceFolder}/${fileBasenameNoExtension}.arm64",
                "${fileDirname}/${fileBasename}"
            ],
            "group": "build"
        },
        {
            "label": "build (Mach-O Universal)",
            "type": "shell",
            "command": "lipo",
            "dependsOn":["build (x86_64)", "build (arm64)"],
            "args": [
                "-create",
                "-output",
                "${workspaceFolder}/${fileBasenameNoExtension}",
                "${workspaceFolder}/${fileBasenameNoExtension}.x86_64",
                "${workspaceFolder}/${fileBasenameNoExtension}.arm64"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

Hope this helps someone in the meantime while M$ fixes their `arm64` macOS support!

**Comment by sean-mcmanus** [comment]
This should be fixed with 1.9.3 (Pre-Release).

**Comment by PengyuApp** [comment]
@sean-mcmanus Hey Thanks for the info that this issue will be fixed. However, what you mean by `1.93`? 
is it the version number for vscode itself?
or c/c++ extension version number?

**Comment by sean-mcmanus** [comment]
It's C/C++ version 1.9.3 via the VS Code Pre-Release installation.

**Comment by jjm2473** [comment]
> ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (this is a non-interactive debug session, cannot get permission to debug processes.)

For users who use ssh to remotely develop on macOS, you need to log in to the macOS desktop first, execute `DevToolsSecurity -enable`, and an authorization dialog box will pop up. Enter the administrator account password as required. Then you can debug.
