### ISSUE TITLE
Starting debugging target does nothing

### ISSUE THREAD

**Issue by xolom** [microsoft/vscode-cpptools#6780]
Type: Debugger

**Describe the bug**
- OS and Version: MacOS 11.1 (ubuntu docker)
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): 
```
eamodio.gitlens
ms-azuretools.vscode-docker
ms-vscode.cpptools
gitlab.gitlab-workflow
renesackers.angelscript
ms-python.python
ms-python.vscode-pylance
```
- A clear and concise description of what the bug is:
If i try to start the debugger, nothing happens. No debugger is started, no terminal opens, no output at all. After enabling logging in `launch.json` only the json configuration is printed in the C/C++ debug output window. I also checked all other logging outputs, but nothing is printed anywhere (if i didn't overlook something). I also tried to set `externalConsole` to `false`, but no change. How can i debug that further? What is important to mention here is: I'm running the vscode instance inside a docker container. It already worked before and no big changes were made. So there must be a way to check why there is no debugger started now at all. If i use another extension like CodeLLDB, it works perfectly fine. But i prefer to use the C++ plugin.

#### launch.json
```json
{
  "name": "Debug",
  "type": "cppdbg",
  "request": "launch",
  "program": "/home/user/build/bin/binary",
  "cwd": "/home/user",
  "logging": { "engineLogging": true, "trace": true, "traceResponse": true }
},
```

**Comment by WardenGnaw** [comment]
This seems to be an issue with VS Code not sending the debug configuration to the extension. 

If you have engineLogging enabled, we print the launch.json in an output window. 

Does reinstalliing the extension fix the issue?
