### ISSUE TITLE
When you create a .c file with a capital C, vscode shows Cpp symbol

### ISSUE THREAD

**Issue by EmirhanKarahan** [microsoft/vscode-cpptools#6791]
OS : Windows 10 Education 20H2
VS Code version : v1.52
C/C++ Extension Version : v1.1.3

When you create a C file with a capital C, vscode shows Cpp symbol. if i disable c/c++ extension bug goes

![Ekran Alıntısı](https://user-images.githubusercontent.com/48404459/104759155-8b4d8880-5770-11eb-9763-310ed0c00d15.PNG)

**Comment by lakshits11** [comment]
Maybe you can try clearing vs code cache. because I tried that and I have no problem like u mentioned. Or what u can do is to uninstall the extension, delete it from ~/.vscode/extensions/ms-vscode.cpptools  and then reinstall it

**Comment by lakshits11** [comment]
Or u can use a different icon theme extension..maybe we can try that?

**Comment by sean-mcmanus** [comment]
That is "by design". "*.C" files are normally considered C++ files. You can disable that via setting the C_Cpp.autoAddFileAssociations setting to false.
