### ISSUE TITLE
1.2.0-insiders regression: "Go To Symbol in Workspace" is not working anymore

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6793]
Hello I see now that limit was increased, but the (Ctrl+T) Go To Symbols Workspace is not working anymore. Is there a connection with this fix?

_Originally posted by @jenuc78 in https://github.com/microsoft/vscode-cpptools/issues/6766#issuecomment-761006756_

**Comment by sean-mcmanus** [comment]
@jenuc78 cpptools and TypeScript are returning the symbols to VS Code, but for some reason VS Code isn't showing them. It could be a VS Code bug. Still investigating...

**Comment by sean-mcmanus** [comment]
It was a TypeScript regression -- unfortunately, the TypeScript system doesn't do a good enough job warning when a "string" type doesn't match a "vscode.Uri" type. Fix at https://github.com/microsoft/vscode-cpptools/pull/6795

**Comment by jenuc78** [comment]
Hello, how to get this fix? I have version 1.2.0-insiders but does not seems to work, the same version was also before reporting the issue.

**Comment by sean-mcmanus** [comment]
The fix is in 1.2.0-insiders2, which should be released later today.

**Comment by jenuc78** [comment]
Thank you, it works now
