### ISSUE TITLE
Duplicated path result by search symbol

### ISSUE THREAD

**Issue by samjegal** [microsoft/vscode-cpptools#68]
<img width="312" alt="screen shot 2016-06-12 at 11 34 47 am" src="https://cloud.githubusercontent.com/assets/1227196/15988592/b2a3af28-3091-11e6-8ed0-2b1ac58824fd.png">

Duplicated path by search somthing symbol. But that's same result.

**Comment by jgoshi** [comment]
Are you still seeing this with the latest version (VSCode 1.4 and cpp tools extension 0.8.1)?

**Comment by jgoshi** [comment]
This is fixed and will appear in the next cpptools release (version 0.9.0). If it still repros when you try that version, please reopen the bug.
