### ISSUE TITLE
suggestion(intellisense ?) does not show field names on editing C source code file

### ISSUE THREAD

**Issue by otsuka-kohei** [microsoft/vscode-cpptools#680]
suggestion shows many field names that in "C:\Program Files (x86)\Windows Kits\10\Include".
So, I cannot input names automatically, for example, "double","break",my defined structure name and so on.
Please make priority high for general names(double, break...) and local defined names.

**Comment by bobbrow** [comment]
Which IntelliSense engine are you using? (check settings.json if you don't know)
If you are using `"C_Cpp.intelliSenseEngine": "Default"` it should show just the struct field names.
If you are using `"C_Cpp.intelliSenseEngine": "Tag Parser"` it will show anything that matches the characters you typed.

**Comment by sean-mcmanus** [comment]
Local variable completions is being tracked by https://github.com/Microsoft/vscode-cpptools/issues/255 .

If there are other issues, we need more information.

**Comment by sean-mcmanus** [comment]
Go to definition with local variables was implemented with 0.19.0 -- are you still having issues?
