### ISSUE TITLE
"C_Cpp.vcFormat.indent.caseLabels": true NOT WORKING!

### ISSUE THREAD

**Issue by mrezabayat** [microsoft/vscode-cpptools#6806]
"C_Cpp.vcFormat.indent.caseLabels": true and "C_Cpp.vcFormat.indent.caseContentsWhenBlock": true do not work!

**Comment by Colengms** [comment]
Hi @mrezabayat .  I'm not easily able to repro an issue with these settings.  Have you set `"C_Cpp.formatting": "vcFormat"`?  Perhaps if there an `.editorconfig` file in your tree, that may be taking precedence?

**Comment by mrezabayat** [comment]
Hi @Colengms, Thanks for your reply.
This is my `.editorconfig` contents:
`[*]
cpp_indent_braces=false
cpp_indent_multi_line_relative_to=innermost_parenthesis
cpp_indent_within_parentheses=indent
cpp_indent_preserve_within_parentheses=false
cpp_indent_case_labels=true
cpp_indent_case_contents=true
cpp_indent_case_contents_when_block=true
cpp_indent_lambda_braces_when_parameter=true
cpp_indent_goto_labels=one_left
cpp_indent_preprocessor=leftmost_column
cpp_indent_access_specifiers=true
cpp_indent_namespace_contents=true
cpp_indent_preserve_comments=false
cpp_new_line_before_open_brace_namespace=ignore
cpp_new_line_before_open_brace_type=ignore
cpp_new_line_before_open_brace_function=ignore
cpp_new_line_before_open_brace_block=ignore
cpp_new_line_before_open_brace_lambda=ignore
cpp_new_line_scope_braces_on_separate_lines=false
cpp_new_line_close_brace_same_line_empty_type=false
cpp_new_line_close_brace_same_line_empty_function=false
cpp_new_line_before_catch=true
cpp_new_line_before_else=true
cpp_new_line_before_while_in_do_while=false
cpp_space_before_function_open_parenthesis=remove
cpp_space_within_parameter_list_parentheses=false
cpp_space_between_empty_parameter_list_parentheses=false
cpp_space_after_keywords_in_control_flow_statements=true
cpp_space_within_control_flow_statement_parentheses=false
cpp_space_before_lambda_open_parenthesis=false
cpp_space_within_cast_parentheses=false
cpp_space_after_cast_close_parenthesis=false
cpp_space_within_expression_parentheses=false
cpp_space_before_block_open_brace=true
cpp_space_between_empty_braces=false
cpp_space_before_initializer_list_open_brace=false
cpp_space_within_initializer_list_braces=true
cpp_space_preserve_in_initializer_list=true
cpp_space_before_open_square_bracket=false
cpp_space_within_square_brackets=false
cpp_space_before_empty_square_brackets=false
cpp_space_between_empty_square_brackets=false
cpp_space_group_square_brackets=true
cpp_space_within_lambda_brackets=false
cpp_space_between_empty_lambda_brackets=false
cpp_space_before_comma=false
cpp_space_after_comma=true
cpp_space_remove_around_member_operators=true
cpp_space_before_inheritance_colon=true
cpp_space_before_constructor_colon=true
cpp_space_remove_before_semicolon=true
cpp_space_after_semicolon=false
cpp_space_remove_around_unary_operator=true
cpp_space_around_binary_operator=insert
cpp_space_around_assignment_operator=insert
cpp_space_pointer_reference_alignment=left
cpp_space_around_ternary_operator=insert
cpp_wrap_preserve_blocks=one_liners
`
Although `cpp_indent_case_labels=true` the Code Formatting does not indent the cases of the switch and it looks like this:
![image](https://user-images.githubusercontent.com/32814496/105175814-b7785900-5b24-11eb-894d-4d80426c2151.png)

**Comment by Colengms** [comment]
Hi @mrezabayat .  Using the `.editorconfig` content you provided, and using `Format Document` with the following code, it appears to format correctly for me:

```
void foo(int i)
{
    switch (i)
    {
        case 1:
            {
            }
        case 2:
            {
            }
    }
}
```

Changing those 2 settings (`cpp_indent_case_labels` and `cpp_indent_case_contents_when_block`) to `false`, and formatting again, I get the following:

```
void foo(int i)
{
    switch (i)
    {
    case 1:
    {
    }
    case 2:
    {
    }
    }
}
```

This is using 1.2.0-insiders.  If you haven't tried with 1.2.0-insiders, could you confirm if this still repro's for you with this latest version of the extension?

Also, if I set`"editor.formatOnType": true`, I see that this formatting occurs as closing brackets are typed.

Do you perhaps have another extension installed that is applying formatting that might be conflicting with the C/C++ extension?

Since this doesn't seem to be a simple repro, is there any additional information you could provide, such as: version of the extension you are using, other extensions you have installed, any relevant settings, or any C/C++ log output leading up to the repro?

**Comment by sean-mcmanus** [comment]
My guess is that the user is referring to bug https://github.com/microsoft/vscode-cpptools/issues/5538 in which the snippet code isn't automatically formatted when it's generated. @mrezabayat Is that the case, i.e. the snippet formatting becomes fixed after manually invoking formatting, right?

**Comment by mrezabayat** [comment]
> Hi @mrezabayat . Using the `.editorconfig` content you provided, and using `Format Document` with the following code, it appears to format correctly for me:
> 
> ```
> void foo(int i)
> {
>     switch (i)
>     {
>         case 1:
>             {
>             }
>         case 2:
>             {
>             }
>     }
> }
> ```
> 
> Changing those 2 settings (`cpp_indent_case_labels` and `cpp_indent_case_contents_when_block`) to `false`, and formatting again, I get the following:
> 
> ```
> void foo(int i)
> {
>     switch (i)
>     {
>     case 1:
>     {
>     }
>     case 2:
>     {
>     }
>     }
> }
> ```
> 
> This is using 1.2.0-insiders. If you haven't tried with 1.2.0-insiders, could you confirm if this still repro's for you with this latest version of the extension?
> 
> Also, if I set`"editor.formatOnType": true`, I see that this formatting occurs as closing brackets are typed.
> 
> Do you perhaps have another extension installed that is applying formatting that might be conflicting with the C/C++ extension?
> 
> Since this doesn't seem to be a simple repro, is there any additional information you could provide, such as: version of the extension you are using, other extensions you have installed, any relevant settings, or any C/C++ log output leading up to the repro?

Thanks @Colengms. This is the list of extensions that I have installed:

- C/C++ 1.2.0-insiders2
- CMake 0.0.17
- CMake Tools 1.5.3
- Output Colorizer 0.1.2
- Qt tools 0.8.1
- Prettier - Code Formatter 5.8.0
This is my vscode information:

- Version: 1.52.1
- Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
- Date: 2020-12-16T16:32:10.090Z
- Electron: 9.3.5
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Linux x64 5.8.0-38-generic snap

If you need any other information please tell me.
Thanks in advance

**Comment by mrezabayat** [comment]
> My guess is that the user is referring to bug #5538 in which the snippet code isn't automatically formatted when it's generated. @mrezabayat Is that the case, i.e. the snippet formatting becomes fixed after manually invoking formatting, right?

Hi @sean-mcmanus Thanks for your reply. But I did not follow what you said. Would you possibly clarify more?

**Comment by sean-mcmanus** [comment]
Can you disable `Prettier - Code Formatter 5.8.0`? That could be interfering with our formatting.

I was thinking you may be reporting bug https://github.com/microsoft/vscode-cpptools/issues/5538, which the formatting isn't immediately applied when a snippet like the "switch" snippet is used, but manually invoking a format should work.

**Comment by mrezabayat** [comment]
> Can you disable `Prettier - Code Formatter 5.8.0`? That could be interfering with our formatting.
> 
> I was thinking you may be reporting bug #5538, which the formatting isn't immediately applied when a snippet like the "switch" snippet is used, but manually invoking a format should work.

Dear @sean-mcmanus thanks for your suggestion I disabled the `Prettier - Code Formatter 5.8.0` but the problem still exists.

**Comment by Colengms** [comment]
Hi @mrezabayat .  I'm not able to easily repro the issue as described.  Would you be able to create a simple GitHub repo that we could clone to repro the issue?  There may be some detail we've overlooked, that a self-contained explain might shed some light on.

**Comment by sean-mcmanus** [comment]
Also, if you can set C_Cpp.loggingLevel to "Debug" and view the "C/C++" pane output you should verify that it shows "vcFormat" formatting output and not "clang-format" messages (or other errors).

**Comment by BilBomba** [comment]
Same Problem here with VSCode 1.53.2 on windows 10

`#include <stdio>

void main() {
  int a = 3;
  switch (a) {
    case 0: {
      cout << "<=0";
    } break;
    case 1: {
      cout << "something else";
    }
  }
}`

with settings.json
`{
    "C_Cpp.vcFormat.indent.accessSpecifiers": true,
    "C_Cpp.vcFormat.indent.caseLabels": true,
    "C_Cpp.vcFormat.space.insertAfterSemicolon": true,
    "C_Cpp.vcFormat.indent.caseContentsWhenBlock": true,
    "C_Cpp.clang_format_fallbackStyle": "Google",
}`

**Comment by sean-mcmanus** [comment]
@BilBomba I get the expected results when I add
```
"C_Cpp.formatting": "vcFormat",
"editor.tabSize": 2
```

![image](https://user-images.githubusercontent.com/19859882/109701990-84c07800-7b48-11eb-855e-06a454958687.png)

**Comment by mrezabayat** [comment]
Thanks @sean-mcmanus . My settings.jason file was missing `"C_Cpp.formatting": "vcFormat"`!
