### ISSUE TITLE
how to find references of struct member at the struct definition?

### ISSUE THREAD

**Issue by taihangg** [microsoft/vscode-cpptools#6810]
c/c++
shift+F12 could not find struct member's reference correctly at the definition.

**Comment by sean-mcmanus** [comment]
I'm not reproing this. Can you provide a short code sample and/or a screenshot?

![image](https://user-images.githubusercontent.com/19859882/105119224-c1e31600-5a84-11eb-8f21-a12dc4f8e6b4.png)

**Comment by taihangg** [comment]
@sean-mcmanus 
thanks!
when the cursor is at line 4, shift+F12 could not show the window of reference

**Comment by sean-mcmanus** [comment]
Can you provide a screenshot? Do you see symbols in the Outline view? Does right-click and invoking Find All References work?

**Comment by taihangg** [comment]
thanks!
right-click and invoking Find All References does work! it just have some interferent item, and does not pop a window which have the reference list.
thank you!
