### ISSUE TITLE
how to make intellisense read though all the files in the workspace ?

### ISSUE THREAD

**Issue by tidnaptima** [microsoft/vscode-cpptools#6811]
I have a workspace of like 1200 files in different folders now each time when I try to map a symbol it says no references found and now when I load the file on the editor its able to find the symbol, is it possible to have it done all at once during the intial load ?
if so how ?

**Comment by sean-mcmanus** [comment]
Are you using 1.2.0-insiders? There's a bug (https://github.com/microsoft/vscode-cpptools/issues/6793) with workspace symbols -- we should have a fixed release tomorrow.

Otherwise, we'll need more info. It's supposed to parse the entire workspace for global symbols.

**Comment by tidnaptima** [comment]
I am using vscode - 1.52.1
I can't share you the complete logs as this is something protected.. which will be visible while the tags are generated, else I request you to share me the help to understand the miss.
you can guide me what to look for in the logs, and I can share them in this thread.

**Comment by sean-mcmanus** [comment]
1.52.1 is the version of VS Code itself -- what version of the C/C++ extension are you using? FYI, we're about to release 1.2.0-insiders2, which has the fix Go to Symbol in Workspace.

In the logs, what files are getting tag parsed and which ones are getting skipped? There could be something special causing specific files to not be parsed.

**Comment by tidnaptima** [comment]
sorry to comment, I have moved to sublime and sublcodeintel does a better job for my project.
will take in the 1.2.0 insider2 and try out ovevr the weekend Thanks!
