### ISSUE TITLE
Unable to install C/C++ extension via ssh to Ubuntu

### ISSUE THREAD

**Issue by wxycsi** [microsoft/vscode-cpptools#6815]
I have the same issue as this [https://github.com/microsoft/vscode-cpptools/issues/6496].  So I would like to try deleting install.lock first. Btw, how could I find the root of extension folder?

**Comment by wxycsi** [comment]
This seems to be an issue of VM. In the VM if I tried many times, I would install the extension in the end.

**Comment by sean-mcmanus** [comment]
The root of the extension folder is usually at some location like "~/.vscode/extension/".
