### ISSUE TITLE
Exclude macOS Framework from parsing

### ISSUE THREAD

**Issue by xolom** [microsoft/vscode-cpptools#6821]
Hi!

I would like to speedup intellisense parsing as much as possible. We don't need the macOS framework in our project, so i would like to exclude it completely.

I tried to set `C_Cpp.default.macFrameworkPath` in the workspace settings to an empty array (`[]`) or `null`, but nothing changes.

I always get folloing output:
```
...
  Processing folder (recursive): /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/AdServices.framework/Versions/A/Headers/
  Processing folder (recursive): /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/USBDriverKit.framework/Versions/A/Headers/
  Processing folder (recursive): /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CryptoTokenKit.framework/Versions/A/Headers/
  Processing folder (recursive): /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/VideoToolbox.framework/Versions/A/Headers/
  Processing folder (recursive): /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/UserNotifications.framework/Versions/A/Headers/
  Processing folder (recursive): /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/DeveloperToolsSupport.framework/Versions/A/Headers/
  Processing folder (recursive): /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/iTunesLibrary.framework/Versions/A/Headers/
  Processing folder (recursive): /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/SceneKit.framework/Versions/A/Headers/
...
```

**Comment by sean-mcmanus** [comment]
Those "processing" messages are for the "tag parser" and should only cause a few seconds of one-time parsing of some headers under those paths and it shouldn't cause IntelliSense parsing to be slower. If you set C_Cpp.loggingLevel to "Debug" you can see what parsing is being done for the framework files. Let me know if you're seeing a higher performance hit. The frameworks are being picked up from your compilerPath (it's possible there could be some args you could pass to get it to remove those frameworks from being used by your compiler, and/or you could switch to a compiler that doesn't have the frameworks in it's default include path...e.g. if you setup to cross compile for Linux it shouldn't have those frameworks).

**Comment by xolom** [comment]
Thanks, you're right. Setting `"C_Cpp.default.compilerArgs": ["-nostdinc"],` helped.
