### ISSUE TITLE
Intellisense Autocomplete Bug for macro define struct

### ISSUE THREAD

**Issue by ybpcn** [microsoft/vscode-cpptools#6824]
**Type: Intellisense **

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 
版本: 1.52.1 (user setup)
提交: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
日期: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
- C/C++ Extension Version:v1.2.0-insiders2

**Steps to reproduce**

1. file1.h
`
#define DECL_STRUCT_tagGlobalSpreadInfo(...)	\\
MAKE_ITEM(uint32_t,uID,##__VA_ARGS__)	\\
MAKE_ITEM(int32_t,nGrant,##__VA_ARGS__)

#define HX_BT_L() (
#define HX_BT_R() )

#define MAKE_ITEM(t,n,...)     t n;

#define HXMAKE_STRUCT(nm) \\
    struct R_##nm { \\
        DECL_STRUCT_##nm HX_BT_L() HX_BT_R()\\
    };

HXMAKE_STRUCT(tagGlobalSpreadInfo)

#undef MAKE_ITEM
#undef HXMAKE_STRUCT
`

2. file1.cpp
`
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include "file1.h"

int main()
{
   R_tagGlobalSpreadInfo mm;
   mm. 
}
`

3. intellisense show: mm.DECL_STRUCT_tagGlobalSpreadInfo

**Comment by sean-mcmanus** [comment]
How are you getting your code to compile? i.e. what compiler, etc.? Because the code doesn't compile with gcc 10.2 and clang 11:
```
error: ISO C++ forbids declaration of 'DECL_STRUCT_tagGlobalSpreadInfo' with no type [-fpermissive]
   12 | DECL_STRUCT_##nm HX_BT_L() HX_BT_R()\
      | ^~~~~~~~~~~~
<source>:15:1: note: in expansion of macro 'HXMAKE_STRUCT'
   15 | HXMAKE_STRUCT(tagGlobalSpreadInfo)
```
and with cl.exe/msvc mode there isn't a bug:

![image](https://user-images.githubusercontent.com/19859882/105316106-4319d600-5b75-11eb-8354-896129e106ee.png)

The completion not working correctly is just a side effect of the gcc parsing error.

**Comment by ybpcn** [comment]
Thank you for @sean-mcmanus reply. I use the MSVC compiler. I will check what is the reason. My vscode does have this problem.
