### ISSUE TITLE
Add a setting to stop automatically tag parsing all headers under the current workspace folder

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6827]
Currently, headers under the workspace folder are always tag parsed, even if they're not `#included`. This decision was made before multi-root workspaces were possible in which users could add large external libraries with lots of headers that aren't used, but can increase the database size and decrease performance (see https://github.com/microsoft/vscode-cpptools/discussions/6801).

Most of the work involved is just adding the setting and plumbing it through, similar to what is already done for the limitSymbolsToIncludedHeaders setting.

**Comment by bobbrow** [comment]
I don't think we want to do this.  At some point we'd like to have a feature that will allow us to suggest types that have not yet been `#include`d.  Auto-completing those types would also add the `#include` statement.

**Comment by sean-mcmanus** [comment]
Sure, I'll close this.
