### ISSUE TITLE
Rename symbol (F2) language support for C++

### ISSUE THREAD

**Issue by salda** [microsoft/vscode-cpptools#683]
Is there a chance to have rename symbol (defaultly F2) working with C++ language? It is the only blocker for my use of VS Code as primary IDE for C++ development. And I am waiting for this feature to come from the beginning of VS Code and I am very surprised that noone else submitted request about it yet. 

Btw, I guess that it already works by default in Visual Studio 2017 using ctrl+r. 
I have been using Visual Assist in older versions of VS for that. 

Is it hard to port it somehow from VS2017 by myself? Or how can I help it?

**Comment by sean-mcmanus** [comment]
VS 2017 is closed source, so I don't know how you'd port the renaming feature from there unless you worked at Microsoft. We're tracking the renaming feature at https://github.com/Microsoft/vscode-cpptools/issues/296 .

**Comment by salda** [comment]
Thanks, I tried to search a lot, but couldn't find already existing ticket.

**Comment by imhuay** [comment]
Is this project not from Microsoft, isn't it?

**Comment by sean-mcmanus** [comment]
@imhuay VS Code is by Microsoft and this C++ extension is from Microsoft too, but different teams.

**Comment by salda** [comment]
Is there a war in Microsoft?

**Comment by sean-mcmanus** [comment]
@salda No. There is no war in Microsoft as far as I know.

**Comment by xahon** [comment]
So what? Should we waiting for such simple thing? Vscode highlights scoped symbols right but ctrl+f2 selects out-of-scope occurrences. Just need to implement this feature in built-in symbol recognition and that's all

**Comment by mipac** [comment]
I try vscode for c++ on linux and refactoring does not work, for the moment I hope 😊
I agree with some comment it's an important feature, enough to choose this IDE or not

but it's very promising! I'm really surprised by this portable editor++ and I will follow his evolution 😊

**Comment by nkhlktn** [comment]
Its a very good editor. Refactorings for C++ will just add to the whole thing. One of those new good things coming out of MS :)

**Comment by trcwm** [comment]
I'm want this feature! Can't believe QtCreator does this and VS Code doesn't! Whyyyyy..

**Comment by bobbrow** [comment]
We are tracking this with #296.  Please go and upvote that issue.  There is also more discussion there as to why it hasn't been implemented yet.

**Comment by trcwm** [comment]
> 
> 
> We are tracking this with #296. Please go and upvote that issue. There is also more discussion there as to why it hasn't been implemented yet.

Thanks, done!
