### ISSUE TITLE
Nested scopes with the same name confuses intellisense (Outline/vscode.DocumentSymbols)

### ISSUE THREAD

**Issue by BigBahss** [microsoft/vscode-cpptools#6830]
**Type: LanguageService**

**Describe the bug**
- OS and Version: **Manjaro Linux, kernel 5.10.2-2**
- VS Code Version: **1.52.1-2**
- C/C++ Extension Version: **1.2.0-insiders2**
- Other extensions you installed (and if the issue persists after disabling them): **Disabled all other extensions**
- Does this issue involve using SSH remote to run the extension on a remote machine?: **No**

**Steps to reproduce**

1. Create a file containing:
```cpp
namespace foo {
    namespace bar {
        namespace foo {
            int testFunc();

            class bar
            {
                bar();
            };
        }
    }
}
```
2. Note the outline view:
![Screenshot_2021-01-22_00-15-59](https://user-images.githubusercontent.com/58710639/105450058-ad02b000-5c47-11eb-997c-00ac8e5f4a72.png)
`testFunc()` and `class bar` appear within the outer-most `namespace foo`, whereas the constructor `bar()` appears in `namespace bar`. However, `bar()` is still recognized as being a method, rather than a function.
3. If you change the inner-most `namespace foo` to `namespace notfoo`, you get this outline:
![Screenshot_2021-01-22_00-42-03](https://user-images.githubusercontent.com/58710639/105451564-bfcab400-5c4a-11eb-9d44-9978d6da3d06.png)
`testFunc()` and `class bar` are now positioned correctly, while the constructor `bar()` still appears under `namespace bar`.

I recognize that this is an edge case that isn't likely to come up. I found it while coming up with edge cases when testing my own extension.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 1/22/2021, 12:28:37 AM
Version: 1.2.0-insiders2
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c17",
    "cppStandard": "c++14",
    "compilerArgs": [],
    "intelliSenseMode": "gcc-x64",
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/tyler/repos/test.h ]:
    /home/tyler/repos/test.h
Translation Unit Configurations:
[ /home/tyler/repos/test.h ]:
    Process ID: 137320
    Memory Usage: 9 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/10.2.0
        /usr/include/c++/10.2.0/x86_64-pc-linux-gnu
        /usr/include/c++/10.2.0/backward
        /usr/local/include
        /usr/lib/clang/11.0.0/include
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=110000
        --header_only_fallback
Total Memory Usage: 9 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 45423
Number of files discovered (not excluded): 41148
Number of files parsed: 4245

```
</details>

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. It should be fixed in our next release.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0-insiders3

**Comment by sean-mcmanus** [comment]
This is going to be broken again with 1.2.2 due to infinite looping issues that were found. We should have a new fix for 1.3.0.

**Comment by BigBahss** [comment]
I think this is related, but I found a case that produces duplicate namespaces:
```cpp
namespace foo {
    namespace bar::baz {
        int fooBarBaz();
    }
}
```
Outline:
![Screenshot_2021-03-11_08-46-06](https://user-images.githubusercontent.com/58710639/110796700-3e54d280-8246-11eb-8f66-8430e8760526.png)

Hopefully this is fixed in the pending release.

**Comment by sean-mcmanus** [comment]
@BigBahss Fixed with our pending 1.3.0-insiders:

![image](https://user-images.githubusercontent.com/19859882/110842953-9c8cb000-825c-11eb-85e4-c559b3dcbcb4.png)

We're still working on other issues before releasing it.

**Comment by BigBahss** [comment]
Excellent 👍

**Comment by sean-mcmanus** [comment]
@BigBahss ETA is now this Thursday (or next week if we find any issues).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders . Let us know if you notice any other bugs in regards to the symbol outlining.

**Comment by BigBahss** [comment]
The examples I gave all look like they have been fixed, however I found a new example that is not outlined correctly:
```cpp
namespace foo::bar {
    namespace baz::inline boop {
        class beep {
        public:
            beep();
        };

        int foobarbaz();
    }
}
```
![Screenshot_2021-03-23_10-11-39](https://user-images.githubusercontent.com/58710639/112160067-2ffca400-8bc0-11eb-8d19-8d21251f78d5.png)

Of course, this syntax is new to c++20, so it is understandable that it's not fully supported yet.
