### ISSUE TITLE
i no longer see the highlighting red line to show syntax error in my c/c++ programs

### ISSUE THREAD

**Issue by Dannyshyk** [microsoft/vscode-cpptools#6832]
**Type: LanguageService**

**when i make a syntax error  in a c/c++ program i no longer see the red wavy line under the error however if i go back to previous version of c/c++ extension like 0.17.3 it works fine currently the version i am facing the issue with is 1.1.3**
- OS and Version: windows and 64bit
- VS Code Version: 1.51.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): yes
- Does this issue involve using SSH remote to run the extension on a remote machine?:
-

**Steps to reproduce**

 added some code in it with some syntax error 
but there is no error or warning 
i tried to set most of the configurations to default but the issue still persists

**Expected behavior**
a red line should highlight that there is an syntax error 

**Screenshots**

![Screenshot (33)](https://user-images.githubusercontent.com/74501927/105473248-e75d6300-5cc2-11eb-988e-0e664ec96ff1.png)
![Screenshot (36)](https://user-images.githubusercontent.com/74501927/105473272-ef1d0780-5cc2-11eb-868a-5b0a83983abb.png)

**Comment by michelleangela** [comment]
@Dannyshyk 

Could you provide the following 2 log outputs to get more info about the issue?

1. Log output from enabling the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
2. Log output from running the command `C/C++: Log Diagnostics`

**Comment by Dannyshyk** [comment]
Thankyou for showing your concern, but it is settled already now. I just reinstalled the vs code and the extensions. Now it is working fine.
