### ISSUE TITLE
回格键无法使用

### ISSUE THREAD

**Issue by ALEXMORCER87** [microsoft/vscode-cpptools#6834]
Issue Type: <b>Bug</b>

回格键无法使用

Extension version: 1.1.3
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (11.37GB free)|
|Process Argv|E:\\cpp_2 --crash-reporter-id 4182ece0-06fc-42bf-8f75-8fe658e2f419|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600:30247031

```

</details>

**Comment by michelleangela** [comment]
@ALEXMORCER87 
Could you provide more info about the issue? Such as sample code that can be used to reproduce the issue and instructions to reproduce the issue? And what the expected and actual behaviors are?

**Comment by sean-mcmanus** [comment]
The title seems to translate to `The backbar is not available` so I'm assuming this should be filed at https://github.com/microsoft/vscode/issues
