### ISSUE TITLE
Intellisense updating forever (vscode 1.44.2 on Cent OS 7, linux)

### ISSUE THREAD

**Issue by Mastiff37** [microsoft/vscode-cpptools#6835]
I searched through a bunch of related topics, but most are pretty old.   I'm using vscode 1.44.2 on Cent OS 7, linux.  Intellisense does not work at all (always says "loading") and I have the little flame icon going indefinitely. I'm on a sequestered system, so can't easily just test out a newer version of vscode.  Is there any sort of workaround?

**Comment by michelleangela** [comment]
@Mastiff37, what is the version of the C++ extension? Could you provide the logs from the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)?

**Comment by xolom** [comment]
Is it possible that this is somehow related to my issue? (https://github.com/microsoft/vscode-cpptools/issues/6809#issuecomment-765295490) I also get an infinite flame icon, which says `Updating IntelliSense...`.

**Comment by Mastiff37** [comment]
My C++ is 0.26.1.  I left my machine running over the weekend and it may have resolved.  I noticed that the database icon was up and said updating was "paused".  I clicked and resumed and it was "discovering files" for many hours.  Perhaps intellisense won't work or update until this file discovery thing is complete?  The odd thing is that I've been using vscode with this code base for a long time, but it seems to have discarded its index or something.  It was up to about 8000 files discovered by the time I left on Friday.

**Comment by Mastiff37** [comment]
Well, I opened another file and now the flame icon is back and it says "parsing paused".  I cannot unpause it.  I will open a different issue since the intellisense problem may actually just be a parsing problem.

**Comment by sean-mcmanus** [comment]
0.26.1 is a year and 3 months old -- we'd recommend update your VS Code in order to get the more recent version of our extension which could fix the issue you're seeing.

Discovering files isn't supposed to take a long time (unless it's over 100k). You may be able to workaround the issue via changing your includePath setting so no "**" paths exists (that might unblock IntelliSense from requiring tag parsing to finish).

**Comment by Mastiff37** [comment]
I'm on a network isolated from the internet, but was able to push up to 1.1.3.  Also code 1.51.1.

After the update, it's discovering files again from scratch.  Perhaps normal?  I'm struck by the slowness of this process though, like finding a file every 5-10 seconds.  Last time it had many thousands before it was done, so this is on track to be a very long process.  

My code base is large but not enormous.  Thing is, it does use libraries from the linux install, so my path has "/usr/include/**" and "/usr/lib/**".  Is this bad practice?  Thanks for the help.

**Comment by sean-mcmanus** [comment]
Yeah, it's not supposed to be that slow. The "discovering files" stage is just looking through the paths in the browse.path setting for a list of the files it may need to parse for workspace symbols, but it's not doing any actual parsing at that point. Is something with your system causing slow file acceses, i.e. are the files remote? Ideally, you could set files.exclude to exclude certain folders -- we're tracking that with https://github.com/microsoft/vscode-cpptools/issues/3123 .

**Comment by Mastiff37** [comment]
Running overnight found 2200 files and still discovering.  All the files are either local to the machine or on network drives within the building.  Maybe I'll try pulling the repo to a fresh location and starting vscode fresh in there just to see what happens.

**Comment by xolom** [comment]
What does `iotop` shows you? The slow parsing sounds more like slow disk I/O performance than an extension issue, but what do i know..

**Comment by Mastiff37** [comment]
I can see how it sounds that way, but I've tried with all local data and on different machines here.  I can only think I somehow butchered my settings or something, although I started with a fresh repo pull and discarded all my vscode settings with the same result.  My working area directory has a total of ~23000 files including binaries and everything, yet somehow the "discovering files" bounced up to ~33000 in the last few minutes.  How can this be?  Is it recursing through all the linux include directories or something?

**Comment by sean-mcmanus** [comment]
"Paused parsing" refers to the background workspace parsing when it's doing foreground parsing related to the includes of the open files.

If you do a C/C++: Log Diagnostics it'll show output like 
```
------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 34897
Number of files discovered (not excluded): 32742
Number of files parsed: 3355
```

The discovering of 30k files is normally supposed to take only a second or so.

Yes, if your compiler uses /usr/include by default (as normal) then that would be iterated through. Setting compilerPath to "" would stop that, but you wouldn't get the default includePaths or system defines unless you specified those manually.

**Comment by Mastiff37** [comment]
I enabled logging and it just gave back the configuration json, then said "no active translation units".  Any other suggestions?  I've been dead in the water for 3 days.   It seems kind of angry in various ways about not having access to the internet.  Is there something special I need to do to have it make peace with the fact I'm offline?

**Comment by sean-mcmanus** [comment]
If you don't see the "Workspace parsing diagnostics" that means it didn't finish enumerating files. You could try setting
```
            "compilerPath": "",
            "browse": {
                "path": []
            }
```
or the equivalent C_Cpp.default settings. That should unblock the enumeration, but you'd probably need to add some system include paths and defines to make IntelliSense work. We don't currently have another way to override the default system browse paths to be non-recursive, since the recursive one that we auto-add from the compilerPath is taking precedence over any non-recursive path (e.g. ending with "/*").

**Comment by bobbrow** [comment]
> Running overnight found 2200 files and still discovering. All the files are either local to the machine or on network drives within the building.

How long does it take you to do `ls -R` on the same set of folders/drives?  Like @sean-mcmanus says, discovering files should be quick.  I suspect the network drives may be having issues.  I don't recommend disabling the automatic compiler detection.  Enumerating the system headers should be fast (if they are on your local disk).  We won't parse them until we detect that they've been included by source files in your workspace.

**Comment by Mastiff37** [comment]
ls -R takes about 10 seconds.

**Comment by bobbrow** [comment]
If you're feeling up to it, we have some [instructions here](https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues) on how to send us more information that we can use to diagnose this issue.  There's definitely something weird going on, but we're unable to figure out what exactly that is based on the information we have right now.
