### ISSUE TITLE
Intellisense / autocomplete not working

### ISSUE THREAD

**Issue by Duffsman** [microsoft/vscode-cpptools#6840]
Issue Type: <b>Bug</b>

Intellisense is not working properly, it doesn't provide any suggestions when typing, not even of local variable names. But when hovering over the name of a variable or method additional informations are displayed in a popup window

Extension version: 1.2.0-insiders2
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.57GB free)|
|Process Argv|--crash-reporter-id 18fdcb11-a0c8-4ad4-8b70-72d556a26d7f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600:30247031

```

</details>

**Comment by rcknaman** [comment]
same problem

**Comment by Duffsman** [comment]
I was able to fix it for now by reverting the c/c++ tools to version 1.1.1 and turning off auto extension update.

**Comment by sean-mcmanus** [comment]
When you do the repro do you see any "crash" messages in the C/C++ logging?

I assume 1.1.3 is working for you too?

Do you have any more repro info, such as some sort of sample code along with with compiler you're using?

**Comment by Duffsman** [comment]
The following message was shown in the C/C++ log: `Quick info operation failed: FE: 'Unknown error'`
Version 1.1.3 caused the problems for me. 
I'm using https://openframeworks.cc/ and the clang++ compiler from the XCode toolchain.

**Comment by sean-mcmanus** [comment]
Okay, yeah, I see some IntelliSense changes during that time period that may have caused it. We'll see if we could repro it (we may have to ask for me info if we're not able to).

**Comment by andyj513** [comment]
I believe I'm seeing the same issue.  I believe it started when I (was automatically) upgraded to 1.53.  If I hover the mouse over a symbol, it shows the definition.  But if I select "Go to Definition" it shows a blue bubble that says "No definition found for 'x'".  It seems to do this for all symbols, even ones defined in the same file.  This is a cpp file, running Code on Windows 10, but Remote editing files on a Linux machine.  This worked before the update.

**Comment by andyj513** [comment]
I now think I am seeing a different issue.  A) Using version 1.1.1 did not help, and B) I only see this issue for one solution, but it is working correctly in another solution (for code on the same Remote machine).

**Comment by bobbrow** [comment]
@andyj513 since it sounds like your issue is different, can you open a new issue with more details about the project you are having trouble with?

**Comment by andyj513** [comment]
Yes, thank you.  I was aware of that, and would have, but rebooting the Linux box seemed to resolve the issue.

**Comment by sean-mcmanus** [comment]
@andyj513 The update of VS Code may have caused a dangling cpptools process that had a lock on the database, so resetting would have killed the dangling cpptools process.

**Comment by davidwin** [comment]
I have started to get the `Quick info operation failed: FE: 'Unknown error'` error message and no IntelliSense on some projects in v1.2, but not all. Right now I don't know specifically what triggers this but will try to look for a pattern.

**Comment by davidwin** [comment]
I think that, in my case at least, the reason for the IntelliSense error is faulty handling of `-idirafter` in `compile_commands.json`. In the project that I am working with, what is specified with `-idirafter` really needs to be searched *after* all system includes, or there will be an include loop and normal compilation will fail after an spewing endless error messages. I should write a separate issue for this.

**Comment by davidwin** [comment]
It seems that if you have an include loop that involves system include directories, you don't get a diagnostic about a header including itself, but rather just the not very helpful `Quick info operation failed: FE: 'Unknown error'` message in the C/C++ log.

**Comment by sean-mcmanus** [comment]
@davidwin More useful error might get shown if we fixed https://github.com/microsoft/vscode-cpptools/issues/3207 .

**Comment by PhoebeTf** [comment]
Hi @Duffsman Thanks for your reporting this issue. 
1. While I can't repro this issue on Windows and Mac with C++ extension1.22 installed, no matter with simple project or OpenFramework downloaded from https://openframeworks.cc/download/ or https://github.com/openframeworks/openFrameworks/tree/master/examples, you can get my status from attachment.
![Intellisense_Work](https://user-images.githubusercontent.com/37648162/111433605-76be4a00-8739-11eb-86b5-7067bd09b807.gif)

2. To go on investigate this issue, could you help to confirm below 2 questions?
1) Could you share us detailed steps about how did you using OpenFramework?
2) Could you let us know whether we need with extra settings in VSCode?

We look forward to hearing from you.

**Comment by Spongman** [comment]
I'm seeing this issue today, fully updated.

**Comment by sean-mcmanus** [comment]
@Spongman IntelliSense/autocomplete not working is a general symptom. We need more info to determine what the root cause bug is, i.e. some code sample and/or logging.

**Comment by HannoG** [comment]
Hi There,

It seems like there is an ongoing issue with my VS Code Configuration, Intellisense does not find anything and keeps coming up with errors. It keeps saying, that I should update my compile_commands.json etc.

Some technical data about my setup:
Hardware:
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2,7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  System Firmware Version:	427.0.0.0.0
  SMC Version (system):	2.28f7

MAC OS Version: Big Sur
  System Version:	macOS 11.4 (20F71)
  Kernel Version:	Darwin 20.5.0

VS Code: Version: 1.57.1 (Universal)



Hope this is sufficient. Thanks!
<img width="1043" alt="Screenshot 2021-07-02 at 16 55 15" src="https://user-images.githubusercontent.com/3615646/124293506-0952ef80-db57-11eb-97b7-cba1ca5bef63.png">

**Comment by sean-mcmanus** [comment]
@HannoG It would be better to file a new issue. The general symptom of not being able to find headers could have many possible causes. We would need the output of running the C/C++: Log Diagnostics command. Your includePath could be incorrect or if you have compileCommands set then the compile_commands.json entry might be missing an include.

**Comment by HannoG** [comment]
Thanks, Sean it looks like I was able to fix it after a few experiments with the settings.
Turned out, that the workspace file from my developer course has its own compileCommands json file and I didn't know how to configure this correctly by heart. The official VS documentation helped a lot after all.
Sorry about the fuss.

**Comment by deanhsjones** [comment]
> Thanks, Sean it looks like I was able to fix it after a few experiments with the settings.
> Turned out, that the workspace file from my developer course has its own compileCommands json file and I didn't know how to configure this correctly by heart. The official VS documentation helped a lot after all.
> Sorry about the fuss.

Could you please clarify the steps you took to correct this?
