### ISSUE TITLE
Issue with loading c_cpp_properties.schema.json

### ISSUE THREAD

**Issue by nvmker** [microsoft/vscode-cpptools#6841]
- OS and Version: macOS 11.1
- VS Code Version: 1.52.1
- C/C++ Extension Version: v1.1.3
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
I found #4841 issue, and looks like I can reproduce it with updated extension with "onFileSystem:cpptools-schema" activation.

Here is an error:
```
{
	"resource": "/Volumes/Main/Dropbox/code/personal/DaisyMy/Playground/.vscode/c_cpp_properties.json",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json': Unable to load schema from 'schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json': cannot open schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json. Detail: Unable to resolve resource schemaservice://combinedschema/cpptools-schema%3A/c_cpp_properties.schema.json.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}
```

And c_cpp_properties.json:
```
{
  "configurations": [
    {
      "name": "macOS",
      "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/../../Daisy/libDaisy/**",
        "${workspaceFolder}/../../Daisy/DaisySP/**"
      ],
      "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
      ],
      "compilerPath": "/usr/local/bin/arm-none-eabi-g++",
      "cStandard": "c11",
      "cppStandard": "c++17"
    }
  ],
  "version": 4
}
```

**Comment by sean-mcmanus** [comment]
It looks like it's trying to process a bogus ":" from `%3A/c_cpp_properties.schema.json`. Are you using a non-English VS or anything else that might be unusual?

Are you able to do `git clone https://github.com/microsoft/vscode-cpptools.git`, put a breakpoint at https://github.com/microsoft/vscode-cpptools/blob/insiders/Extension/src/main.ts#L65, and run Launch Extension (development) to see what we're returning? It's supposed to give a path like `/home/<user>/vscode-cpptools/Extension/c_cpp_properties.schema.json` And/or can you get the Help->Toggle Developer Tools->Console for other erros we may be reporting?

**Comment by nvmker** [comment]
I'm using English VSCode but with localized OS, I tried to debug extension as you described but got no output from debugger using this breakpoint. How I can debug it in case of non-localized VSCode?

**Comment by nvmker** [comment]
Looks like I found extension which cause this issue, it's https://github.com/42Crunch/vscode-openapi

**Comment by sean-mcmanus** [comment]
You mean that extension is somehow breaking our extension's functionality? Can you file a bug against that extension?

I'm not sure what you mean by getting no output from the debugger. If you're not seeing breakpoints set, that probably means you need open a .cpp file to activate our extension.

You should see 
![image](https://user-images.githubusercontent.com/19859882/105933429-3ed13b00-6003-11eb-9b4b-5d0bbe4db322.png)
so if you can set through that function and see what the variables are that could show what is going wrong.

**Comment by nvmker** [comment]
Without vscode-openapi extension I got correct value of localizedFilePath in debugger, with vscode-openapi I got nothing. vscode-openapi is related to JSON files, so I assume that there is an issue with this extension, not your and I'm closing this issue.
