### ISSUE TITLE
Completion includes don't show recursive results in a header file

### ISSUE THREAD

**Issue by boocs** [microsoft/vscode-cpptools#6842]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10 latest
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Other extensions you installed (and if the issue persists after disabling them): n/a
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

You can determine a list of paths for the IntelliSense engine to use dynamically, for the source code, using recursive root paths in the includePath setting.

The forcedInclude headers don't get this ability. If a forcedInclude header has an #include and the required header, for this #include, is not explicitly set in includePath, it will produce Intellsense errors.

**Steps to reproduce**

1. Have a forcedInclude header that has an #include
2. The header required for this #include is not explicitly set in includePath
3. Have the root path of that needed path for the #include, inside the forcedInclude header, set as recursive in includePath e.g. "rootPathNeededForIncludeOfForcedInclude/**"
4. The forcedInclude header wont use the recursive path, in includePath, to figure out paths any #include needs
5. Intellisense errors occur

**Expected behavior**
 
1. Before adding forcedIncludes, check for any recursive paths in includePath
2. If there are recursive paths, in includePath, check for paths any #include needs in any forcedInclude file
3. Add found paths to list of paths for the IntelliSense engine to use
4. Process forcedInclude headers as normal

**Additional context**

Tested on a UE4 project. Was testing out an extension idea for dynamic compile commands creation, using the C/C++ logs, when I found out this behavior.

**Comment by sean-mcmanus** [comment]
Sounds like this is supposed to work, i.e. fixed with https://github.com/Microsoft/vscode-cpptools/issues/2986 . I'll check...

**Comment by boocs** [comment]
I'll test more too. UE4 is multi workspace so maybe that is the reason.

**Comment by sean-mcmanus** [comment]
Yeah, I'm not reproing this with a basic scenario -- are you using compile_commands.json to configure? Or if you think it's a multi-root issue can you describe how it's setup? The recursive includes feature only works with c_cpp_properties.json includePaths and not with compile_commands.json, because in the compile_commands.json case, we expect to be provided with the correct includes without having to resort to the recursive incudes processing.

**Comment by boocs** [comment]
It wasn't compile commands. 

I created a extension that fixes the bugs in the UE4/VSCode config and sets up the config it what I believe is the optimal configuration. I have two options for fixes. Fix compile commands or Converter fix that converts the 4.26 to non compile commands.

I also had an optional setting that allowed you to use recursive paths in includePath.

For the UE4 c_cpp_properties.json, I generalized it and took out all the main workspace references.

For forcedInclude paths, I added those to the Main workspaces *.code-workspace file. This is because both workspaces needed it but I didn't want to pollute the UE4 c_cpp_properties with specific references.

I'll try to recreate the same UE4 config in a test project and see if it acts the same.

**Comment by boocs** [comment]
Here's the  test project. The readme has the info.

https://github.com/boocs/ue4-forced-include-test

**Comment by sean-mcmanus** [comment]
Okay, thanks for the repro project -- I'll try to check that out tomorrow after we release 1.2.0-insiders3.

**Comment by sean-mcmanus** [comment]
Changing it to 
		"C_Cpp.default.forcedInclude": [
			"${workspaceFolder}/Intermediate/Build/Win64/MainGameEditor/Development/Engine/SharedPCH.Engine.ShadowErrors.h"
		]
fixed the issue for me. We don't support implicit relative include paths yet -- we have an issue tracking that at https://github.com/microsoft/vscode-cpptools/issues/4983 for our next 1.3.0 release.

**Comment by boocs** [comment]
Ok thanks!

**Comment by boocs** [comment]
Sorry, my poorly configured test project screwed both of us up. I should've tested UE4 as well before closing... Your fix fixed that erred path but it is still bugged. 

The reason it wasn't bugged was because we hadn't been using the Main.code-workspace file to open the project.

I rearranged the project to make it more clear. What's good is now it mimics the UE4 errors. Main.h and Main.cpp both give errors now.

The readme in Main shows tests you can do to the project.

**Comment by sean-mcmanus** [comment]
Okay, I'll check...

**Comment by sean-mcmanus** [comment]
Hmm, I'm not getting any error squiggles. Any ideas why?

![image](https://user-images.githubusercontent.com/19859882/106335735-40d50d00-6242-11eb-8456-7fc19095bb3c.png)

**Comment by boocs** [comment]
I deleted my browse cache and the errors went away. Which is strange because they're Intellisense errors?

I'm pretty sure I've already tested that on UE4 but I'm doing that now.

I do have my browse cache setup weird. Maybe with multi workspaces something weird is going on.
"C_Cpp.default.browse.databaseFilename": "K:\\.vscode\\cache\\browse\\${workspaceFolderBasename}\\user.vs.db",

I have my Intellisense cache turned off.

Will test more.

**Comment by sean-mcmanus** [comment]
The browse database could contain data that used by the recursive includes feature that could affect IntelliSense. It could also affect what source file is chosen when opening a header file.

If you see `K:\.vscode\cache\browse\${workspaceFolderBasename}\user.vs.db` created then it should be good, except you be aware that if you open multiple workspace folders with the same ${workspaceFolderBasename} then the database could be re-written.

**Comment by boocs** [comment]
Forgetting the previous wierdness, I found the real bug. Tested this with UE4 and it worked.

### Real error in test project
Change the #include in Main/Intermediate/Build/Win64/MainGameEditor/Development/Engine/SharedPCH.Engine.ShadowErrors.h  to an absolute path. The absolute path causes the bug.


### UE4 tested
I moved a project to the UE4 directory so I could test it with a relative path and it worked. 
```
//#include "J:/Program Files/Epic Games/UE_4.26/Engine/Source/Runtime/Engine/Public/EngineSharedPCH.h" // doesn't work
#include "../../UE_4.26/Engine/Source/Runtime/Engine/Public/EngineSharedPCH.h"  // works
```

**Comment by boocs** [comment]
I discovered in UE4 that I could just use:
```
#include "EngineSharedPCH.h"
// or #include "Public/EngineSharedPCH.h"
// and so on
```
I thought I had tested this before but I think it could be another bug with #include code completion.

It depends on what file you click on first for it to work.

---
### 1st Test in Test Project
1. Click on c_cpp_properties.json so it's the first file you see when you reopen
2. Reset Intellisense database(Tag Parser)
3. Close VSCode and reopen 
4. Open Main.cpp
5. Open SharedPCH.Engine.ShadowErrors.h
6. Type #include "" so completion appears
7. No paths in includePath show up.

---
### 2nd Test in Test Project
1. Click on c_cpp_properties.json so it's the first file you see when you reopen
2. Reset Intellisense database(Tag Parser)
3. Close VSCode and reopen 
5. Open SharedPCH.Engine.ShadowErrors.h (don't open Main.cpp first)
6. Type #include "" so completion appears
7. includePath paths now show up.

**Comment by sean-mcmanus** [comment]
I repro the issue with the #include not working with the full path, but I'm not reproing the issue with the `#include` not working. What file are you typing `#include` in?

![image](https://user-images.githubusercontent.com/19859882/106538451-13da6180-64b1-11eb-80c6-ed178f652106.png)

**Comment by boocs** [comment]
I'm using the latest insiders with just Intellisense cache turned off. No other settings

I meant the includePath folders don't appear in completion list for the 1st test.

If you type Engine or Public, do those folders appear in the completion list?

```
#include "Engin"
// #include "Publ" // another test
```

They don't with the first test but they do for the second.

**Comment by sean-mcmanus** [comment]
Ah, okay -- I repro that issue now.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0-insiders3 .

**Comment by boocs** [comment]
Tested current public release - Still bugged.

Tested 1.5.0-insiders3 - Confirmed fixed!

Thanks!
