### ISSUE TITLE
Incorrectly identifies a problem with "os_assumes_zero" macro

### ISSUE THREAD

**Issue by sbingner** [microsoft/vscode-cpptools#6846]
**Type: LanguageService**

**Describe the bug**

VSCode incorrectly tags code using the `__OS_COMPILETIME_ASSERT__` macro as "a variable-length array is not allowed inside of a statement expression" because it does not understand that the variable length array is being removed by the compiler.

- OS and Version: macOS any version
- VS Code Version: 1.53.0-insider (also tried latest stable)
- C/C++ Extension Version: 1.2.0-insiders2 (also same issue on stable)
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
Import the below code into a folder and once it resolves imports it will show the problem: 
```json
{
	"resource": "/vscodetest/Untitled-1.c",
	"owner": "C/C++",
	"code": "1233",
	"severity": 8,
	"message": "a variable-length array is not allowed inside of a statement expression",
	"source": "C/C++",
	"startLineNumber": 30,
	"startColumn": 5,
	"endLineNumber": 30,
	"endColumn": 20
}
```

Sample code to duplicate (OSX):
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

extern void _os_avoid_tail_call(void);
extern void _os_assumes_log(uint64_t code);
#define OS_EXPECT(x, v) __builtin_expect((x), (v))
#define os_constant(x) __builtin_constant_p((x))
#define os_fastpath(x) ((__typeof__(x))__builtin_expect((long)(x), ~0l))
#define __OS_COMPILETIME_ASSERT__(e) __extension__({ \
	char __compile_time_assert__[(e) ? 1 : -1];	\
	(void)__compile_time_assert__; \
})
#define os_assumes_zero(e) __extension__({ \
	__typeof__(e) _e = os_fastpath(e); \
	if (!_e) { \
		if (os_constant(e)) { \
        	__OS_COMPILETIME_ASSERT__(e); \
		} \
		_os_assumes_log((uint64_t)(uintptr_t)_e); \
		_os_avoid_tail_call(); \
	} \
	_e; \
})

int main() {
    char *foo1 = "foo";
    char *foo2 = strdup(foo1);
    os_assumes_zero(strcmp(foo1, foo2));
    free(foo2);
    return 0;
}
```

**Expected behavior**

It should show valid code with no problems.

<details>
  <summary><strong>Logs</strong></summary>

```
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/sam/source/vscodetest/Untitled-1.c
Queueing IntelliSense update for files in translation unit of: /Users/sam/source/vscodetest/Untitled-1.c
  tag parsing file: /Users/sam/source/vscodetest/Untitled-1.c
sending 1 changes to server
Checking for syntax errors: file:///Users/sam/source/vscodetest/Untitled-1.c
Queueing IntelliSense update for files in translation unit of: /Users/sam/source/vscodetest/Untitled-1.c
cpptools/finishUpdateSquiggles
Error squiggle count: 1
Update IntelliSense time (sec): 2.419
cpptools/getFoldingRanges: file:///Users/sam/source/vscodetest/Untitled-1.c (id: 75)
cpptools/getCodeActions: file:///Users/sam/source/vscodetest/Untitled-1.c (id: 76)
cpptools/getDocumentSymbols: file:///Users/sam/source/vscodetest/Untitled-1.c (id: 77)
cpptools/getDocumentSymbols
Database safe to open

```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug against our shared VS parser at https://developercommunity.visualstudio.com/content/problem/1321221/cc-intellisense-gives-incorrect-error-a-variable-l.html .

**Comment by sean-mcmanus** [comment]
This appears to have been fixed a long time ago.
