### ISSUE TITLE
qt.natvis file not fully supported in Linux (gdb) QVariant

### ISSUE THREAD

**Issue by borro0** [microsoft/vscode-cpptools#6848]
Type: Debugger

I've setup a qt5.natvis file to see some qt debug info.

For QString and QVector it works.

However for QVariant, it doesn't show anything.
I'm in linux using gdb.
![image](https://user-images.githubusercontent.com/15669405/105814462-bb3b2e00-5fb1-11eb-85c1-97742a4be38e.png)
Natvis file:
https://code.qt.io/cgit/qt-labs/vstools.git/plain/src/qtvstools/qt5.natvis.xml

**Describe the bug**
- OS and Version: Ubuntu 20.04.1 LTS
- VS Code Version: 1.52.1
- C/C++ Extension Version: v1.1.3
- Other extensions you installed (and if the issue persists after disabling them):
![image](https://user-images.githubusercontent.com/15669405/105815537-54b70f80-5fb3-11eb-9787-2554423d13c8.png)

- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Use the qt5.natvis file given for debug information on Qt symbols
2. Create QT application, put a breakpoint in some function with a QVariant local variable.
3. Make sure a string is stored inside the QVariant
4. Debug the code and see that the program stops at the breakpoint
5. Inspect and verify that QVariant doesn't get a DisplayString

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
I assume that not all natvis functionality is supported on Linux (gdb). However, not seeing the contents of a QVariant is a real bummer for debugging Qt applications in VsCode

**Comment by WardenGnaw** [comment]
Thanks for filing this issue. We will investigate why QVariant isnt getting resolved by the Visualizer.

**Comment by sean-mcmanus** [comment]
@Colengms Is the bot supposed to close an issue like this? Isn't there supposed to be a "more votes needed" message?

**Comment by hgtsoi** [comment]
qt5 natvis is broken (QString)
