### ISSUE TITLE
C++ No output when running the code.

### ISSUE THREAD

**Issue by benjitriesc** [microsoft/vscode-cpptools#6850]
I am taking a programming course and for the final project we have to write a simple program. I figured before I dive in, I would get my VSCode set up for C++. 

I followed the guide on here: https://www.freecodecamp.org/news/how-to-compile-your-c-code-in-visual-studio-code/

I was able to get the MinGW directory included in the environment variable PATH, and was able to have it show up in my cmd prompt. 

![image](https://user-images.githubusercontent.com/78042741/105886613-9ad29a00-5fd8-11eb-857a-d1597167bb55.png)

![image](https://user-images.githubusercontent.com/78042741/105886431-6828a180-5fd8-11eb-89e4-6318fbd45254.png)

I have also added the code runner extension to VScode, but when I try running the helloworld code, I get nothing in the output.

`#include <iostream>
using namespace std;
int main() 
{
    cout << "Hello world!";
    return 0;
}
`
Not sure what I am missing or doing wrong.

**Comment by sean-mcmanus** [comment]
It works for me when I use F5 to debug. We have some docs at https://code.visualstudio.com/docs/cpp/config-mingw . I don't know about the Code Runner extension -- that could be messing things up.

You may also try adding a `<< endl;` since some times that is needed to force the output to flush.
