### ISSUE TITLE
The language server crashed 5 times in the last 3 minutes. It will not be restarted.

### ISSUE THREAD

**Issue by tsat-psv** [microsoft/vscode-cpptools#6856]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.2.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): Cmake Tools (no change if stopped)
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I get the error: The language server crashed 5 times in the last 3 minutes. It will not be restarted. and Connection to server got closed. Server will not be restarted. 

**Steps to reproduce**
Start Vscode and see OUTPUT tab

**Expected behavior**

1. Logs from the command `C/C++: Log Diagnostics`
Not possible, crashed
2. Logs from [the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
See below.

<details>
  <summary><strong>Logs</strong></summary>

```
[Error - 12:53:52 PM] Connection to server got closed. Server will not be restarted.
```
```
Custom browse configuration received: {
  "browsePath": []
}
cpptools/didChangeCppProperties
Custom configuration provider 'CMake Tools' registered
```
</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/43535969/105990312-9672b380-60a2-11eb-9b56-239aaaba9396.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
Does the issue repro if you remove the configurationProvider setting? If so, can you attach a debugger to the cpptools process and then set the configurationProvider to cause the crash and get a call stack? (see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv).

**Comment by sveip** [comment]
@sean-mcmanus , I'm not quite sure how  I do that. when I try to open the panel to change it (from ctrl+shift+p typing configurationProvider) nothing happens since it's crashed.

**Comment by sean-mcmanus** [comment]
Can you open `${workspaceFolder}/.vscode/c_cpp_properties.json` or the settings file that has C_Cpp.default.configurationProvider set?

**Comment by sean-mcmanus** [comment]
Oh...but your comment "Cmake Tools (no change if stopped)" implies that the configuration provider is not required for the repro. Are you able to provide any other repro info? Does it repro with any simple project? Does it repro with after you set C_Cpp.updateChannel to "Default" and it starts using version 1.1.3?

**Comment by tsat-psv** [comment]
Hi, I removed the `configurationProvider`  line from `c_cpp_properties.json`, but that did not change anything unfortunately.  I also tried another project, and it seems to work there. 

I haven't changed anything, so not much info to provide to repro the issue. It happened when I opened the setting the first time (successfully) to set some gcc flags, I then switched focus to another app, and when I came back it had crashed (no changes made.)

**Comment by tsat-psv** [comment]
I think it might be as simple as that before I opened the settings, no `c_cpp_properties.json` file exsisted, and it all worked fine. 

I tried to move it now, and now I can open the settings, but the minute I change some settings and the config json is written it crashes.

**Comment by sean-mcmanus** [comment]
Hmm, I'm still not able to repro it (maybe I'm not understanding your repro steps). Are you able to attach a debugger to cpptools before it enters the crashing state and then trigger the crash to get a call stack? By "toolchain file" do you mean CMAKE_TOOLCHAIN_FILE?

**Comment by tsat-psv** [comment]
I ended up re-installing the plugin, and that solved it, but I can't say specifically what.
