### ISSUE TITLE
Outline error

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#6858]
as the two pics
![image](https://user-images.githubusercontent.com/1876302/106104564-91cefd80-617d-11eb-81a6-6f0a5f78892f.png)
![image](https://user-images.githubusercontent.com/1876302/106104584-972c4800-617d-11eb-8503-1e866ad23fdd.png)
```c
#define SOCKET_INC(a) // SOCKET self inc
#define VOID_ void
VOID_ test()
{
    SOCKET_INC(FRZ_ON)
    {
        printf("Surrounded by \'SOCKET_INC\'");
    }
}
```

**Comment by heartacker** [comment]
v1.2.0-insiders3

**Comment by heartacker** [comment]
when toggle commentLine `SOCKET_INC(frZ_ON)`, outline works correctly.

**Comment by heartacker** [comment]
somebody help me, 3Q, there is  a very bad effect on my work. thanks

**Comment by bobbrow** [comment]
Thanks for reporting this issue.  We'll have to take a look and get back to you.  Sorry for the delay!

**Comment by sean-mcmanus** [comment]
This is "by design". Add a "cpp.hint" file too your workspace folder root with contents
```
#define SOCKET_INC(a)
```.
