### ISSUE TITLE
Running C console apps print nothing

### ISSUE THREAD

**Issue by KeplerIO** [microsoft/vscode-cpptools#686]
Hey guys I'm working in C in VScode using cpptools. I'm getting a weird issue where my console app will run correctly and exit with code 0 before showing anything. Here is an example of code and screenies of the issue.

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main()
{
    char firstName[20];
    char crush[20];
    int numOfBabies;

    printf("What is your name?\n");
    scanf("%s", firstName);

    printf("Who are you going to marry?");
    scanf("%s", crush);

    printf("How many kids will you have?");
    scanf("%d", &numOfBabies);

    printf("%s and %s are in love and will have %d babies", firstName, crush, numOfBabies);

    return 0;
}`

Screenies:
![2017-05-03_11-20-14](https://cloud.githubusercontent.com/assets/26471970/25675292/cb1fe952-2ff2-11e7-8c80-e59ce2be44a1.png)

*ignore the symbols not loading. This is not an issue.

**Comment by pieandcakes** [comment]
@KeplerIO can you provide your `launch.json`? Also what compile options did you use?

**Comment by pieandcakes** [comment]
I tested with this setting:
```
         {
            "name": "C++ Launch (Windows)",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceRoot}/main.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true
        }
```

and I compiled with 
` C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe main.cpp `

this produced `main.exe` that ran above. 

This gave me a window that had my output:
![capture](https://cloud.githubusercontent.com/assets/17558378/25679512/7d181ff8-3002-11e7-8d8c-42683f7bb404.PNG)

**Comment by KeplerIO** [comment]
Here's my launch.json:

`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (Windows)",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceRoot}/a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false
        },
        {
            "name": "C++ Attach (Windows)",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
`

I compiled using MinGW GCC here: C:/MinGW/x86_64-w64-mingw32/include/*

to produce "a.exe". Idk why it's formatted like that..

**Comment by KeplerIO** [comment]
I actually think switching externalConsole to true might fix this. One moment.

**Comment by pieandcakes** [comment]
@KeplerIO Yea, the problem is you are using the Windows C++ debugger to debug a gcc compiled MinGW App. You need to start with the `gdb` template.

If you recreate the `launch.json` and choose C++ (gdb/lldb) that will get you the right template to start with.

**Comment by KeplerIO** [comment]
@pieandcakes thank you for your help. It works now. Sometimes it jsut takes another set of eyes to look over something. This was a good example of the "rubber ducky" method lol. One more thing, if I'm sticking to standard prodecural C, will selecting C++(gdb/lldb) give me any errors down the road?

**Comment by pieandcakes** [comment]
@KeplerIO If you want to do Bash On Windows, MinGW or Cygwin development for cross platform to Linux, use the gdb/lldb template. This is because it compiles with `gcc/g++` and has to be debugged with the associated debugger. If you are creating a Windows only app, you can use Visual C/Visual C++ and then choose to use the Windows debugger to debug them.

Both should do what you need to do if you are doing a C console app.

**Comment by pieandcakes** [comment]
@KeplerIO It looks like your issue is resolved. I'm going to mark this as closed. If you leave further comments I can respond. Thanks
