### ISSUE TITLE
Switch from a depth-first to breadth first traversal with "Discovering files" and add an abort timeout

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6861]
Currently, the workspace parsing will do a depth first traversal of the browse.path when locating potential files to parse, which may cause it to take too long, particularly since files.exclude aren't checked (https://github.com/microsoft/vscode-cpptools/issues/3123). It would be better to do a breadth first traversal and then check some timeout setting to abort if it's taken too long. That would cause some files that are too deeply nested to not be parsed, but it's possible those files wouldn't matter, and adding those paths to the browse.path would be a workaround.

**Comment by sean-mcmanus** [comment]
Depth first might actually be better if we don't want to abort on a timeout and we don't expect certain trees with a high depth to be causing issues.

**Comment by bobbrow** [comment]
We decided not to do this.
