### ISSUE TITLE
Symlinks that point to a parent folder can cause duplicate directory iteration and parsing on Windows

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6864]
With a single .cpp and symlink, it gets parsed 20 times (the max recursive depth).

**Comment by Colengms** [comment]
@sean-mcmanus Did this make it into 1.2.1 ?

**Comment by sean-mcmanus** [comment]
No, the change is bundled into my bigger symlink PR that is dealing with files.exclude stuff.

**Comment by sean-mcmanus** [comment]
It's fixed but it's currently bundled into a PR with the other symlink changes (which aren't finished yet).

**Comment by michelleangela** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders4

**Comment by michelleangela** [comment]
Fix is released in the 1.3.0 release version https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0
