### ISSUE TITLE
Bug on startup

### ISSUE THREAD

**Issue by ajbravodeveloper** [microsoft/vscode-cpptools#6866]
We have written the needed data into your clipboard because it
Issue Type: <b>Performance Issue</b>

After startup of vscode the saved c++ program is giving me error about that header file is wrong. But when I restart the program that problems get fade away. Why it is showing up daily

Extension version: 1.2.0-insiders3
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.98GB (1.13GB free)|
|Process Argv|--crash-reporter-id 3679e273-b982-4f94-9b71-b93178b84eba|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	  8808	code main
    0	   164	  2392	   window (● tut14.cpp - c++ - Visual Studio Code)
    0	    83	  2600	     extensionHost
    0	    18	  1576	       c:\Users\Clairvoyant\.vscode\extensions\ms-vscode.cpptools-1.2.0-insiders3\bin\cpptools.exe
    0	    21	  5372	         c:\Users\Clairvoyant\.vscode\extensions\ms-vscode.cpptools-1.2.0-insiders3/bin/cpptools-srv.exe 1576 {120FFCF2-979B-41FB-AB3B-A7EBE113C672}
    0	     6	  8440	         console-window-host (Windows internal process)
    0	    65	  3540	       "C:\Users\Clairvoyant\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Clairvoyant\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=2600
    0	     6	  6724	     console-window-host (Windows internal process)
    0	     6	  6844	     console-window-host (Windows internal process)
    0	     4	  8156	     C:\Windows\System32\cmd.exe
    0	    13	  8384	     watcherService 
    0	     5	  8376	       console-window-host (Windows internal process)
    0	     4	  8936	     C:\Windows\System32\cmd.exe
    0	     6	  8988	     console-window-host (Windows internal process)
    0	     4	  9012	     C:\Windows\System32\cmd.exe
    0	    73	  2608	   gpu-process
    0	    83	  4544	   shared-process
    0	    37	  6216	   utility
    0	    22	  8060	   crashpad-handler
    2	    82	 10732	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● tut14.cpp - c++ - Visual Studio Code)
|    Folder (c++): 24 files
|      File types: cpp(16) exe(4) json(2)
|      Conf files: settings.json(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617cf:30244267
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

 was too large to send. Please paste.

**Comment by sean-mcmanus** [comment]
We need more info. Can you share a code sample or screenshot of the issue?

**Comment by ajbravodeveloper** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/68113158/107207281-20693780-6a26-11eb-951f-78fdaa7f2e9c.png)

**Comment by sean-mcmanus** [comment]
It's not finding the iostream header. Do you have a C++ compiler installed? Which one? i.e. what does it show when you run the C/C++: Log Diagnostics command (from the Command Palette), e.g. for a cl.exe compiler, you want some output like

```
Translation Unit Configurations:
[ C:\<path>\test.cpp ]:
    Process ID: 13516
    Memory Usage: 18 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/PublicPreview/VC/Tools/MSVC/14.28.29828/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PUBLICPREVIEW\VC\TOOLS\MSVC\14.28.29828\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\CPPWINRT
```
See https://code.visualstudio.com/docs/cpp/config-msvc
