### ISSUE TITLE
includes become unresolved after the parsing (but resolved before and during the parsing)

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cpptools#6869]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.1.3
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

single C++ project , middle size project (~3500 files) , uses STL, boost and some proprietary libs. 
opened as folder, build system is scons configured in tasks and compile the project successfully 

**Steps to reproduce**

1. Open project folder
2. Open any cpp file
3. Look at the include statements and Ctrl+click to resolve. headers are opened successfully . all look fine
4. As project is large, at the same time , the parsing is still running (the icon in status bar)
5. when the parsing is finished, include statements are now highlighted as not more resolved and tip about fix into includePath required showed. 

the paths are valid, as those are used in a few projects and copy/pasted.
as well as initially includes were resolved.

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Comment by sean-mcmanus** [comment]
We need more info. How are you configuring your IntelliSense? The output of C/C++: Log Diagnostics after opening a file that shows the errors could help.

**Comment by amigo421** [comment]
going to close the request, 
It 's reproduced but not stably ,
sometimes it 's not resolved , sometimes resolved.
sometimes intellisense database reset helps , sometimes no.
I believed that I found the scenario how to reproduce , however now I see that's not so

and seems I can't collect data due of the project/company restrictions,
I'm going to reproduce on small private project and re-open ticket in case of success.

**Comment by sean-mcmanus** [comment]
You may also want to try (temporarily) setting your intelliSenseCacheSize to 0 to see if that fixes the issue, since if there's a cache corruption bug then that could cause headers to not be found. Also, be sure you're on 1.2.0 (unless you're hitting a regression with that in certain scenarios, which we're working on fixing for 1.2.1).

**Comment by amigo421** [comment]
> You may also want to try (temporarily) setting your intelliSenseCacheSize to 0 to see if that fixes the issue, since if there's a cache corruption bug then that could cause headers to not be found. Also, be sure you're on 1.2.0 (unless you're hitting a regression with that in certain scenarios, which we're working on fixing for 1.2.1).

got it, thank you for the tip, I'll try this
