### ISSUE TITLE
Infer typedef names for unnamed classes / structures

### ISSUE THREAD

**Issue by adentinger** [microsoft/vscode-cpptools#687]
In pure C, some programmers tend to use the syntax:

`typedef struct { /* ... */ } MyStruct;`

Currently, cpptools doesn't recognize this syntax ; the structs are simply called `__unnamed_struct_xxxx_x` by cpptools. See picture attached.

I think it would be a good patch for cpptools to recognize this specific syntax.

![screenshot from 2017-05-03 15-43-55](https://cloud.githubusercontent.com/assets/22079861/25678683/99b4092c-3018-11e7-80bc-d9b6e082ba05.png)

Sincerely,

**Comment by sean-mcmanus** [comment]
Changing IntelliSenseEngine to Default fixes this issue with our improved hover implementation. Is that sufficient? If you get bogus error squiggles you can change the errorSquiggles to "Disabled", and/or you might want to update your includePath and defines setting to match your build settings. I noticed some <unnamed>:: appearing in other scenarios with hover, but these issues were also reproing with Visual Studio 2017, so it appears to be an issue with our shared code.

**Comment by adentinger** [comment]
@sean-mcmanus I edited the `settings.json` to set IntelliSenseEngine to Default, as you suggestd. I can't tell if that solves the problem, since VSCode has been indexing the files (showing the red flame next to the configuration name) in my project for over an hour now.

**Comment by sean-mcmanus** [comment]
Are you saying the config was not red, but then when you changed the IntelliSenseEngine to Default it made the red flame appear for an hour? That sounds like a bug. I'm seeing the red flame for 7 seconds for a large file as the IntelliSense does compiling stuff. What OS are you on? Does it show "Loading" when you hover?

**Comment by adentinger** [comment]
Yes, this is exactly what I mean. When I changed it to default, it started indexing and kept on for over an hour. Yes, it was showing "Loading..." when I hovered. It seems to no longer be the case, however.

I'm on Ubuntu 16.04 LTS 64-bit.

**Comment by sean-mcmanus** [comment]
Hmmm....yeah, I'm observing 2 random bugs: sometimes hover get stuck with "Loading..." and sometimes the red config gets stuck red, when it shouldn't...seems like you hit both bugs as once. We'll need to investigate more. And I've also observed that (seemingly) randomly it will show `<unnamed>::`'

**Comment by Wetmelon** [comment]
I'd still like to see this inference working.  This is a very common practice in code I work with - for example, the entire STM32 HAL uses anonymous structs.

With the correct includePaths setup in the properties file, and the  following settings:
```
    "C_Cpp.intelliSenseEngine": "Default",
    "C_Cpp.intelliSenseEngineFallback": "Disabled",
```

Example:
```
typedef struct
{
  TIM_TypeDef                 *Instance;     /*!< Register base address             */
  TIM_Base_InitTypeDef        Init;          /*!< TIM Time Base required parameters */
  HAL_TIM_ActiveChannel       Channel;       /*!< Active channel                    */
  DMA_HandleTypeDef           *hdma[7];      /*!< DMA Handlers array
                                             This array is accessed by a @ref DMA_Handle_index */
  HAL_LockTypeDef             Lock;          /*!< Locking object                    */
  __IO HAL_TIM_StateTypeDef   State;         /*!< TIM operation state               */
}TIM_HandleTypeDef;
```
`
TIM_HandleTypeDef htim2;
htim2.something = 0;
`

I get red squiggles under `something` as expected, with an error/hover message of:
`struct "<unnamed>" has no field "something"`

It's not impossible to get the information elsewhere (such as by hovering over `htim2`), but it's a bit frustrating to see "unnamed" when one is trying to debug.

VSCode: 
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Cpptools:
Version 0.15.0: Feb 15, 2018

**Comment by sean-mcmanus** [comment]
Is this issue still a problem? I'm not able to repro the problem. It's possible that there is some other parsing error causing some failure, but I need more repro info.

![image](https://user-images.githubusercontent.com/19859882/43557645-7afeaca4-95ba-11e8-9355-a27b79656911.png)

**Comment by adentinger** [comment]
Seems to be fixed for me too.

**Comment by Wetmelon** [comment]
Can confirm issue as described is fixed
![image](https://user-images.githubusercontent.com/3612694/43558939-c5fc986e-95d9-11e8-8bd0-6fcb39403285.png)

Noticed that the same issue now crops in the new OUTLINE feature, but not sure whose responsibility that is
![image](https://user-images.githubusercontent.com/3612694/43558960-dafb9756-95d9-11e8-92fc-b86d521d9a2a.png)

**Comment by sean-mcmanus** [comment]
The outline feature (added by VS Code via querying our symbol results) still uses the tag parser (symbol database)...fixing that would require us using the intellisense engine to populate the outline.
