### ISSUE TITLE
Make punctuation marks in description of property and configuration settings consistent

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6870]
Some property descriptions have periods at the end and some don't. Example:

With "." period
![image](https://user-images.githubusercontent.com/38734287/106331785-5fcfa100-623a-11eb-932e-2972a2986a9b.png)

Without "." period
![image](https://user-images.githubusercontent.com/38734287/106331838-77a72500-623a-11eb-838b-a5762e029a63.png)

Some property descriptions use double quotes, and some use single quotes. Example:

This uses single quotes:
![image](https://user-images.githubusercontent.com/38734287/106331904-986f7a80-623a-11eb-89e6-2257b4bc8248.png)

This uses double quotes:
![image](https://user-images.githubusercontent.com/38734287/106331917-9c030180-623a-11eb-8521-412bb6c40d9d.png)

**Comment by sean-mcmanus** [comment]
I think it should be normalized to end with periods and use double quotes.

**Comment by sean-mcmanus** [comment]
I was going to do this for 1.5.0, but I think it'll break too many translations before we want to ship.
