### ISSUE TITLE
Localize item label when doing "#include" autocomplete

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#6873]
Steps to reproduce:
1. Change language to something other than English.
2. Type `#include` then space to invoke suggestion list to autocomplete a header file.
3. See that the item label "Folder" or "File" or "Multiple locations" are not localized

![image](https://user-images.githubusercontent.com/38734287/106340052-69163900-624d-11eb-93f3-1a92e39ced83.png)

![image](https://user-images.githubusercontent.com/38734287/106340058-6ddaed00-624d-11eb-87c5-bc01c7fb1b88.png)

**Comment by Colengms** [comment]
Fixed in 1.9.1 (or 1.9.0?).
