### ISSUE TITLE
Constant Notification to reload window

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode-cpptools#6875]
Issue Type: <b>Bug</b>

Each time I open a C project, I get this notification popup:
```
The C/C++ Extension has been updated to version 1.2.0-insiders3 (release candidate). Please reload the window for the changes to take effect.
```

I click the Reload Window button, the window reloads ... and the message pops up again. Nonstop.

The only way to stop it is to change the setting
<img width="743" alt="image" src="https://user-images.githubusercontent.com/13488/106345111-d771f000-627b-11eb-9f99-910033960e61.png">

from "Insiders" (the default) to "Default".

Extension version: 1.1.3
VS Code version: Code - Exploration 1.53.0-exploration (0c9e2dadd986d0bc085f1c5352245531eef65e84, 2021-01-07T06:27:03.244Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2promptcf:30219163
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. Fixed with https://github.com/microsoft/vscode-cpptools/pull/6882 . We plan to release 1.2.0 soon which should fix the issue. The issue also doesn't repro with VS Code Insiders (only the Exploration version).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0 , i.e. should be noticeable when 1.3.0-insiders is released.
