### ISSUE TITLE
Report error for requires statement

### ISSUE THREAD

**Issue by GuLicheng** [microsoft/vscode-cpptools#6876]
```
#include<concepts>

template <typename T>
concept string_c = requires (const T& str)
{
    {str.c_str()} -> ::std::same_as<typename T::const_pointer>; 
//                        ^ expected concept name c/c++3257, if I remove "::", it will not report this issue
};

int main()
{
}
```
os: windows10
extension : 1.1.3

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug against our shared VS parser at https://developercommunity.visualstudio.com/content/problem/1326714/c-intellisense-with-clatest-gives-incorrect-error.html

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.6
