### ISSUE TITLE
lldb: can't provide input (stdin)

### ISSUE THREAD

**Issue by DamianFekete** [microsoft/vscode-cpptools#6879]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 (10.0.19041) + **WSL** (Debian GNU/Linux bullseye/sid)
- VS Code Version: 1.52.1 (2020-12-16T16:34:46.910Z) 
- C/C++ Extension Version: v1.2.0-insiders3
- Remote - WSL Extension: v0.52.0

The call to `getchar()` doesn't return, I can't provide input to the program.

**To Reproduce**

* Start VS Code from WSL
* Launch.json:
  
<details>
<pre>
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            // "console": "externalTerminal",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: gcc-8 build active file",
            "miDebuggerPath": "/usr/bin/gdb",
        },
        {
            "name": "clang-11 - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            //console": "externalTerminal",
            "externalConsole": false,
            "MIMode": "lldb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: clang-11 build active file",
            "miDebuggerPath": "/usr/bin/lldb-mi-11",
            "targetArchitecture": "x64",
        }
    ]
}
</pre>
</details>

* Start `clang-11 - Build and debug active file` for this program
```c
#include <stdio.h>

int main() {
	printf("test\n");
	printf("x = ");
	int x = getchar();
	printf("%X\n", x);
	
	return 0;
}
```
* Output generated by `printf`s is only visible under the "Debug console" tab, not under "Terminal".
```
=thread-selected,id="1"
Loaded '/lib/x86_64-linux-gnu/ld-2.31.so'. Symbols loaded.
Loaded '[vdso]'. Cannot find or open the symbol file.
Loaded '/home/adamian/test-c/test-brk'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Symbols loaded.
@"test\r\n"
@"x = "
```
* Typing in "Terminal" tab has no effect, program does **not** continue.

* `(gdb) Launch` works correctly: it shows the output in the Terminal tab and the program can read from stdin

**Additional context**
* Writing a character (as root) using an ioctl call to the correct pts resumes the getchar call.
```python
#!/usr/bin/env python3
import fcntl
import termios

with open('/dev/pts/5', 'w') as fd:
    fcntl.ioctl(fd, termios.TIOCSTI, 'a')
```

**Comment by WardenGnaw** [comment]
There is an issue with `lldb` and using the VS Code integrated terminal. This is an issue with `lldb-mi`. 

WSL has difficulties spawning external windows so `externalConsole: true` does not work in WSL. VS Code should be giving us an error if it could not spawn the external console. This should be investigated.
