### ISSUE TITLE
cpptools-srv not do auto exit after cpptools crashed

### ISSUE THREAD

**Issue by yusj** [microsoft/vscode-cpptools#6880]
**Type: LanguageService**
cpptools-srv processes do not auto exit, after cpptools process crashed (or killed). And there is a new cpptools will be started, with two new cpptools-srv processes. If cpptools process crashed 10 times, we will have 22 cpptools-srv processes alive.

**Describe the bug**
- OS and Version:Ubuntu 20.04
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.2.0
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. ps -ef | grep cpptools
2. kill -9 [pid]  # [pid] is the pid of cpptools
3. cpptools-srv processes are still alive.

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. It's a regression with 1.2.0-insiders3. It only repros on Linux (not Mac/Windows).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.0
