### ISSUE TITLE
includePath problem

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#6881]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.52.1
- C/C++ Extension Version: v1.2.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): CMake Tools 1.5.3
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Intellisense is failing to find various header files in my C++ project. Here is one example:

![image](https://user-images.githubusercontent.com/7724321/106498391-30799800-64b7-11eb-8719-fd6234019053.png)
Here is my .vscode\c_cpp_properties.json:

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/Kernel"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\Hostx64\\x64\\cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64"
            //"configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}
```
All header files are in the workspace.

This is a CMake project but the squiggle appears whether or not I enable the configurationProvider.

Here is the Output window:

![image](https://user-images.githubusercontent.com/7724321/106498943-dd541500-64b7-11eb-9e52-3cf5efa5bbcf.png)
(I don't know why the Output window mentions the configurationProvider as it is commented out).

Can you help me please?

**Comment by sean-mcmanus** [comment]
We're automatically trying to use the configurationProvider. Can you make the CMake-Tools configuration provider be configured correctly? Otherwise, can you disable the CMake-Tools extension?

**Comment by DavidA2014** [comment]
@sean-mcmanus Thanks for your reply. I fixed the issue by deleting:

`"C_Cpp.default.configurationProvider": "vector-of-bool.cmake-tools"`

from settings.json.

**Comment by bobbrow** [comment]
Is the header with the squiggles being included by any of the source files in the CMake project?  Do you list header files as part of the target in `add_executable` or `add_library`, etc?  Oftentimes the trouble with configuring IntelliSense is that CMake doesn't give us information about headers unless they are listed in the CMakeLists.txt as being associated with a target.  In those cases we have to hope that the headers are included by some other source file so that we can "borrow" the configuration from those.

**Comment by DavidA2014** [comment]
@bobbrow Thanks for your reply. My problem is now fixed (by deleting incorrect configurationProvider).
