### ISSUE TITLE
Debugger: How to tell if vsdbg is available?

### ISSUE THREAD

**Issue by WebFreak001** [microsoft/vscode-cpptools#6895]
Type: Debugger

I am writing an extension where I am wrapping the C++ debug configuration in my own simpler debug configuration, which has a mode to auto-detect installed debuggers and choose the subjectively "best" one.

For GDB / LLDB I can check the user's PATH for binaries, however the cppvsdbg debug type has its own exe bundled with the extension, so it's always there. Is there a way for me to query whether the bundled vsdbg.exe can actually debug? (check if it has dependencies / Visual Studio available)

I know it uses Visual Studio but that is usually not in PATH, nor does it use a fixed installation location to check. There are some ways to find out if it's installed, but then there is the question if it's even compatible with the bundled vsdbg.exe.

As the vsdbg executable probably already checks for a proper VS version, can I somehow call it to check if dependencies are installed and it's ready to use?

**Comment by WardenGnaw** [comment]
You can use a similar check as we do when we download packages.

https://github.com/microsoft/vscode-cpptools/blob/76e427fdb24014399497f0598727f2fd2a097454/Extension/src/packageManager.ts#L141-L150

This are the checks for vsdbg: https://github.com/microsoft/vscode-cpptools/blob/76e427fdb24014399497f0598727f2fd2a097454/Extension/package.json#L2751-L2757

**Comment by WebFreak001** [comment]
ah I get what the vsdbg.exe is actually now. So does the user actually not need to have Visual Studio installed to use that debugger?

**Comment by WardenGnaw** [comment]
VS does not have to be installed. The `vsdbg.exe` shipped in this extension a standalone debugger for Windows Visual C++ for VS Code.

**Comment by WebFreak001** [comment]
ok thanks, that answers all my questions
