### ISSUE TITLE
Ugly (raw) output in Debug console from GTest

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#6897]
Type: Debugger

To run GTests I use:

https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer
https://marketplace.visualstudio.com/items?itemName=matepek.vscode-catch2-test-adapter

When debugging the output in Debug console looks like this typically:

      @"Note: Google Test filter = SystemProfilerTest/SystemProfilerTestF.ItemCount/2\r\n"
      @"[==========] Running 1 test from 1 test suite.\r\n"
      @"[----------] Global test environment set-up.\r\n"
      @"[----------] 1 test from SystemProfilerTest/SystemProfilerTestF\r\n"
      @"[ RUN      ] SystemProfilerTest/SystemProfilerTestF.ItemCount/2\r\n"
      @"unknown file: Failure\r\n"
      @"\r\n"
      @"Unexpected mock function call - returning default value.\r\n"
      @"    Function call: SpawnProcess(@0x7ffeefbfe9e0 { \"system_profiler\", \"-xml\", \"SPMemoryDataType\" }, @0x7ffeefbfe978 8-byte object <00-87 93-03 00-00 00-00>)\r\n"
      @"          Returns: 72-byte object <00-00 00-00 00-00 00-00 E8-E8 B7-88 FF-7F 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>\r\n"
      @"Google Mock tried the following 1 expectation, but it didn't match:\r\n"
      @"\r\n"
      @"/Users/ffdf/Projects/GitHub/mfdfd-fdfd/test/data/hard/detail/SystemProfilerTest.cpp:28: EXPECT_CALL(*spawner, SpawnProcess(args, boost::posix_time::seconds(timeoutSeconds)))...\r\n"
      @"  Expected arg #0: is equal to { \"system_profiler\", \"-xml\", \"Undefined DataType\" }\r\n"
      @"           Actual: { \"system_profiler\", \"-xml\", \"SPMemoryDataType\" }\r\n"
      @"         Expected: to be called once\r\n"
      @"           Actual: never called - unsatisfied and active\r\n"

https://github.com/matepek/vscode-catch2-test-adapter/issues/254#issue-799997863

If this behavior is intentional then it would be nice to not be enabled by default or to have an easily accessible button on the UI to quickly switch between views. In any case this is not the default style I'd like to see my printf/cout output by default.

Current OS is Mac OS Big Sur 11.2 and the extension is 1.2.

**Comment by WardenGnaw** [comment]
Are these strings coming from your debuggee?

The debug adapter should not format any output. Can you enable logging in your `launch.json` by adding:
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```
This will clarify if the strings are going through the debug adapter/being sent over Debug Adapter Protocol to VS Code.

**Comment by H-G-Hristov** [comment]
I guess so:
```
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=thread-selected,id="1"
=library-unloaded,id="/Users/xxx/Projects/GitHub/msp-xxx-engine/build/vccode.Darwin/universal/bin/unicorn-test",target-name="/Users/hristohristov/Projects/GitHub/msp-unicorn-engine/build/vccode.Darwin/universal/bin/xxx-test",host-name="/Users/xxx/Projects/GitHub/msp-xxx-engine/build/vccode.Darwin/universal/bin/xxx-test"
Loaded '/usr/lib/dyld'. Symbols loaded.
Loaded '/Users/xxx/Projects/GitHub/msp-xxx-engine/build/vccode.Darwin/universal/bin/unicorn-test'. Symbols loaded.
Loaded '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation'. Symbols loaded.
Loaded '/usr/lib/libc++.1.dylib'. Symbols loaded.
Loaded '/usr/lib/libSystem.B.dylib'. Symbols loaded.
Loaded '/usr/lib/libobjc.A.dylib'. Symbols loaded.
Loaded '/usr/lib/liboah.dylib'. Symbols loaded.
Loaded '/usr/lib/libfakelink.dylib'. Symbols loaded.
Loaded '/usr/lib/libicucore.A.dylib'. Symbols loaded.
Loaded '/System/Library/PrivateFrameworks/SoftLinking.framework/Versions/A/SoftLinking'. Symbols loaded.
Loaded '/usr/lib/libc++abi.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcache.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcommonCrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcompiler_rt.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcopyfile.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libcorecrypto.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdispatch.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libdyld.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libkeymgr.dylib'. Symbols loaded.
Loaded '/usr/lib/system/liblaunch.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libmacho.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libquarantine.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libremovefile.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_asl.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_blocks.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_c.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_collections.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_configuration.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_containermanager.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_coreservices.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_darwin.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_dnssd.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_featureflags.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_info.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_m.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_malloc.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_networkextension.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_notify.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_product_info_filter.dylib'. Cannot find or open the symbol file.
Loaded '/usr/lib/system/libsystem_sandbox.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_secinit.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_kernel.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_platform.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_pthread.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_symptoms.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_trace.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libunwind.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libxpc.dylib'. Symbols loaded.
@"Note: Google Test filter = SystemProfilerTest/SystemProfiler_InvalidPlist.InvalidPlist/0\r\n"
@"[==========] Running 1 test from 1 test suite.\r\n"
@"[----------] Global test environment set-up.\r\n"
@"[----------] 1 test from SystemProfilerTest/SystemProfiler_InvalidPlist\r\n"
@"[ RUN      ] SystemProfilerTest/SystemProfiler_InvalidPlist.InvalidPlist/0\r\n"
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
@"[       OK ] SystemProfilerTest/SystemProfiler_InvalidPlist.InvalidPlist/0 (2653 ms)\r\n"
@"[----------] 1 test from SystemProfilerTest/SystemProfiler_InvalidPlist (2653 ms total)\r\n"
@"\r\n"
@"[----------] Global test environment tear-down\r\n"
@"[==========] 1 test from 1 test suite ran. (2653 ms total)\r\n"
@"[  PASSED  ] 1 test.\r\n"
The program '/Users/xxx/Projects/GitHub/msp-xxx-engine/build/vccode.Darwin/universal/bin/unicorn-test' has exited with code 0 (0x00000000).

```

**Comment by H-G-Hristov** [comment]
@WardenGnaw The issue is definitely not related to GTest.
I now have a normal application, which uses boost::log. The boost log looks like this in the Debug Output:
```
@"\e[1m\e[35m[UNICORN LOG] \e[0m\e[36mINFO: \e[36mStaring UNICORN Test Tool\r\n"
```
The debugger appears to output some raw string. Which appears properly in a terminal. Such as:

![Screen Shot 2021-04-07 at 4 31 41 PM](https://user-images.githubusercontent.com/47526411/113875299-48bfa900-97bf-11eb-8c28-3aee7f7c8faa.png)

```
[UNICORN LOG] INFO: Staring UNICORN Test Tool
```
![Screen Shot 2021-04-07 at 4 34 31 PM](https://user-images.githubusercontent.com/47526411/113875205-304f8e80-97bf-11eb-81c9-8830dd1cc11b.png)

Is it possible to get a properly formatted output in the Debug Console just like as it would appear in a Termninal?

**Comment by H-G-Hristov** [comment]
The above is on MacOS only. On Linux the application output appears in *Terminal: cppgdb* just as I expect  which is great.

![Screen Shot 2021-04-07 at 7 02 20 PM](https://user-images.githubusercontent.com/47526411/113897910-0785c400-97d4-11eb-9628-8dfba96ede83.png)

**Comment by H-G-Hristov** [comment]
This may have been solved by the current Testing API ???

**Comment by H-G-Hristov** [comment]
This may have been fixed. I'm closing it for now.
