### ISSUE TITLE
Cannot inspect the content of STL containers in debugger

### ISSUE THREAD

**Issue by hungys** [microsoft/vscode-cpptools#69]
Currently when I tried to inspect a STL container or a C++ string, the debugger are not able to provide useful information such as the content of a STL vector or string variable. As shown in the screenshot, I have a pretty printer registered to `.gdbinit` and I'm able to use `-exec print v` to see the content of a vector (even a string), but it seems the VSCode debugger doesn't know them.

![](http://i.imgur.com/TVHcvw3.png)

It will be helpful when debugging if the debugger provides such features :)

**Comment by delmyers** [comment]
@hungys, sorry for the delayed response. Try typing "-exec set print pretty" in the debug console. This will turn on pretty printing for gdb. We turned it off by default because of performance issues.

**Comment by dmazuronak** [comment]
The option pretty print only affect the way how [gdb](http://www.delorie.com/gnu/docs/gdb/gdb_58.html) print structures.
The output in Varaiables windows remains unaffected.

**Comment by mschuckmann** [comment]
I'm seeing the same thing, it would be really nice if VSCode could use the pretty printers when show STL variables in mouse hovers and the Watch window.

**Comment by paulmaybee** [comment]
Type "-exec -enable-pretty-printing" in the debug console.

**Comment by hungys** [comment]
@delmyers @paulmaybee Thanks. It works now with `-exec -enable-pretty-printing`.
Btw, can we set it as the default configurations, or is there any roadmap to add this feature? Seems that we need to type that command in the debug console every time.

![STL debugging](http://i.imgur.com/DEewS4n.png)

**Comment by mschuckmann** [comment]
Yes works for me too and I second the need for some way to set it as the default configuration or event some way to provide a list of command gdb at launch. 

I tried adding it my ~/.gdbinit file and it doesn't seem to work.

**Comment by filipsky** [comment]
You can setup initial gdb commands this way in the launch.json

```
            "linux": {

                "MIMode": "gdb",

                "setupCommands": [

                    { "text": "-enable-pretty-printing", "description": "enable pretty printing", "ignoreFailures": true },

                    { "text": "handle SIGPIPE nostop noprint pass", "description": "ignore SIGPIPE", "ignoreFailures": true }  
                ]
            },
```

**Comment by mschuckmann** [comment]
@filipsky 
That's great, where did you find this documented? 
Also where in the launch.json file does this block?

**Comment by filipsky** [comment]
I found it here {just search for **setupCommands** on the page):
[https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md)

I have added the setupCommands block in my OS specific (`"linux": {}` in my case) branch

Best, Honza

**Comment by mschuckmann** [comment]
Thank you, I figured out that it works if the OS specific block is in the
configuration block, which means it has to be repeated for each
configuration, not terrible.
Also thank you for the link.

Matt S.

**Comment by yoyo930021** [comment]
macOS for lldb
have any function?

**Comment by pieandcakes** [comment]
@yoyo930021 If you download our new version, `cpptools 0.10.0` , we have enabled the python pretty printers on macOS. You can also look at natvis and write your own visualizer file which we also support.

**Comment by pieandcakes** [comment]
This issue should be resolved as we have added the gdb pretty printer commands by default in the `launch.json` file. Please comment/reopen if this is still an issue.

**Comment by jhscsc** [comment]
Hi, how do I set up pretty printing for VS Code? I'm running GDB on Cygwin (Windows 10) . Specifically, I don't understand what to do with said ".gdbinit" file. Thank you very much!

**Comment by pieandcakes** [comment]
@jhscsc If you are using the default pretty-printers you don't need to do anything with a `.gdbinit` file. If you want to extend and add your own pretty-printers, you will need to create a `.gdbinit` file. Since that is a `gdb` feature and not one provided by the extension, you may need to do some searching online for the file format. On Windows, that should go in the root of your home directory `c:\users\<username>`. 

In your `launch.json` you should see:
```
"setupCommands": [

                    { "text": "-enable-pretty-printing", "description": "enable pretty printing", "ignoreFailures": true }
]
```
If not, then add that and it should tell `gdb` to enable pretty-printing. This does rely on your version of `gdb` shipping the Python script files that tell it how to visualize the STL objects.

**Comment by jhscsc** [comment]
Thank you for your quick response. I currently have that snippet in my `launch.json`; however, when I type `-exec print v` in the example program shown below, I'm still unable to look into the vector. Do you have any suggestions on how to get it to work? 
![image](https://user-images.githubusercontent.com/32603287/35701512-e451ab40-075b-11e8-890f-ae4d5f24d47e.png)

**Comment by pieandcakes** [comment]
If you expand the variable in your locals, does it show a formatted value? `-exec print v` is telling `gdb` to print `v`. It could be you are missing the Python files that do the formatting, and if that is the case you may need to figure out where they come from. My experience with Cygwin `gdb` is limited. It looks like according to the answer on this [link](https://stackoverflow.com/questions/45070895/eclipse-cdt-pretty-printing-not-working-for-strings) that you need to do additional work to get the files.

**Comment by jhscsc** [comment]
Installing `gcc-debuginfo` like the link instructed enabled formatting when looking in STL containers in locals - that's what I was going for. Thanks so much @pieandcakes!

**Comment by Snape3058** [comment]
I am using gdb 8.0.1 on my PC, and if I use gdb from command line, it can print the inner content of the STL classes correctly. But when I am using vscode, both `-exec print v` and the variables window will not show the inner content. What should I do? Thx

OS: Arch Linux
VSCode Version 1.19.3
cpptools Version 0.14.6
No `~/.gdbinit` file and `/etc/gdb/gdbinit` is empty.
"pretty printing" is enable in `launch.json` just as mentioned above.

**Comment by DollarAkshay** [comment]
I tried all the steps in this github issue. I am using the MinGW compiler and I made sure to install the `mingw32-gdb-python` package via the MinGW Installation Manager which I assume is required to view the STL container. After all that. All I can see is this 

![gdb pretty printing](https://user-images.githubusercontent.com/6565924/35768062-5dbb529e-091c-11e8-8421-c82e6f29c8d4.png)


I have Python 3.6. Do I seriously need to install Python 2.7 ? IS there a solution that uses Python 3 ? :/

**Update**
I have installed Python 2.7 and gdb-python.exe is running fine right now (also followed the additional steps from [this stackoverflow question](https://stackoverflow.com/questions/26844538/windows-eclipse-pretty-printers-importerror-no-module-named-gdb)). I still can't look at the STL vector

![gdb pythonno errors](https://user-images.githubusercontent.com/6565924/35768524-07536cbe-0923-11e8-81f2-a6dd380282e3.png)


Also this is the command I am using to build the C++ executable : `g++ '${file}' -g -o out`

**Comment by pieandcakes** [comment]
@DollarAkshay That looks correct. 

To be clear: Pretty printing is something that gdb provides, although from this thread it looks like it isn't the same across different implementations. Your question about which version of Python should probably be asked to MinGW as that is the tool set that you are using and they control the dependencies for the toolset? From searching online, it looks like the MinGW pretty-printing is a lot harder to setup and you will need to set `"miDebuggerPath"` to point to the python version of `gdb` in your `launch.json`. 

The document I found that sort of explains some steps for MinGW is [here](https://stackoverflow.com/questions/4985414/how-to-enable-gdb-pretty-printing-for-c-stl-objects-in-eclipse-cdt), scroll to the section labeled "This is for MinGW users...".

**Comment by pieandcakes** [comment]
@Snape3058 The only documentation I found is [this](https://bbs.archlinux.org/viewtopic.php?id=177967). I don't know if that is something you can check/verify/try but that might get you started in the right direction.

**Comment by DollarAkshay** [comment]
@pieandcakes Okay. I finally switched to Cygwin GDB and installed the `gcc-debuginfo`. It works on windows now 😄  Thank you.

Now it shows only the basic array for a vector. If I want it to show like the capacity, size and other data members, like how VisualStudio does it, I will have to use a custom `.gdbinit` file ?

**Comment by pieandcakes** [comment]
@DollarAkshay I assume so. We don't do anything special for visualization so it is whatever `gdb` provides us through pretty printing.  There may be some expression shortcuts that you can find online that might give you what you are looking for too that you can add to the `watch` pane.

**Comment by rszibele** [comment]
I've also encountered this problem on Debian, however, the solution is to install the GDB package which is linked to python2.

When you install the `gdb` package with apt, you install `gdb-minimal` which isn't linked against python. You need to install the `gdb-python2` package.

On newer GCC/GDB versions (I'm using 8.2.0/8.1) you no longer need a .gdbinit file, unless you need something custom.

**Comment by ismailhkose** [comment]
It doesn't show STL container accurately on the variable window.
For example, I added two strings to vector and it stills show "size: 0" in the variables window as seen in the following screenshot.

![image](https://user-images.githubusercontent.com/353824/50730289-9fc90600-10fe-11e9-8f70-ccb54ce55b8c.png)

**Comment by pieandcakes** [comment]
@ismailhkose Can you include a log? This looks like a pretty printing issue within the debugger you are using but the log would show us what we are getting back from `gdb`.

**Comment by noodlecollie** [comment]
I'm getting this issue on MacOS 10.13.6 with Python 3.6.5, LLDB 1000.11.38.2 and C/C++ extension 0.21.0. When I put `-exec -enable-pretty-printing` into the debug console, I get the following:

```
result-class: done
supported: 0
```

I'm assuming this means my version of LLDB doesn't support pretty printing? Is there anything else I'd need to download?

**Comment by Snape3058** [comment]
> @Snape3058 The only documentation I found is [this](https://bbs.archlinux.org/viewtopic.php?id=177967). I don't know if that is something you can check/verify/try but that might get you started in the right direction.

It is the `-static` compiler parameter that makes gdb not able to recognize the STL objects. Thank you for your reply.

**Comment by pieandcakes** [comment]
@x6herbius the pretty printing command is a feature of `gdb` and not `lldb`.

**Comment by kamala-nayana** [comment]
Pretty printing is not working for me. I am using gdb in ubuntu.
![Screenshot from 2020-02-22 00-56-15](https://user-images.githubusercontent.com/30267517/75065113-2bbe0d00-550e-11ea-82c3-3cc81b1cd783.png)

**Comment by pieandcakes** [comment]
@knayan111 Please run `info pretty-printer` in `gdb` and let me know if you have them installed.

**Comment by 3AceShowHand** [comment]
This also happens to me. I am using mac 10.14.6, with vscode 1.42, c/c++ plugin is 0.26.3, gdb 8.3. I cannot see the content of any STL containers, this is awful. 
![image](https://user-images.githubusercontent.com/7138436/75466526-4b00e280-59c5-11ea-8bdb-550e0c8d80d5.png)
@pieandcakes, is there any suggestion to help me solve the problem ?

**Comment by pieandcakes** [comment]
@knayan111 @JinLingChristopher In reading this [StackOverflow article](https://stackoverflow.com/questions/11606048/how-to-pretty-print-stl-containers-in-gdb) it looks like you are missing the `stl` pretty printers. You will need to figure out where you can get those for the `gdb` you are using. Unfortunately I don't know where that would be. 

I would expect something like `libstdc++` or something to show up in your pretty printer list with references to `std::` namespace items. 

This [article](https://stackoverflow.com/questions/54394057/mac-pretty-print-gdb) might also give you some hints on how to get it for macOS and its limitations depending on the compiler (`gcc` vs `clang`).

**Comment by jaques-sam** [comment]
This issue is not resolved at all, please reopen. Even with the pretty printer setting in `launch.json`, stl containers are still not readable.

**Comment by pieandcakes** [comment]
@jaques-sam Can you paste your  output for `info pretty-printer` in `gdb`? My [previous comment](https://github.com/microsoft/vscode-cpptools/issues/69#issuecomment-592122044) shows that if you can't resolve `stl` containers, your installation of `gdb` is most likely missing the actual pretty printers.

**Comment by yueyingjuesha** [comment]
Not working+1, my gdb launch.json looks like this:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/src/target",
            "args": ["-x4", "-k12M"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
```
can't not display the contents of stl, using vscode on winodows 10 using WSL 2

**Comment by escape0707** [comment]
@yueyingjuesha From what source did you installed your gdb? I'm using Mingw-w64 8.1.0.0 with Windows 10 and VSCode stable + cpptools stable and have no issue. I'm also using WSL 2 and ArchLinux with all latest packages and still no issue.

```json
    {
      "name": "Clang++: Current file",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
      "cwd": "${workspaceFolder}",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "preLaunchTask": "clang++ build active file"
    }
```

**Comment by yanglr** [comment]
For **Windows**:
If you only see memory address for STL containers when debugging, you probably used x64 Windows.

I found one valid solution, when installing MinGW in x64 Windows, install `i686 (win32)` version (the bottom of this comment gives its official download link) of MinGW instead of `x86_64` version, see below:

![pretty-printing-not-work-with-MinGW GDB-solution](https://user-images.githubusercontent.com/3152813/108173684-6797ac80-7139-11eb-9d03-9eee32578458.png)

**win32 version of MinGW download:**
[i686-posix-dwarf](https://mmbizurl.cn/s/Xtn6Gu8sa)

More details, see:
<https://stackoverflow.com/a/66238128/6075331>

**Comment by herrberk** [comment]
I was able to solve this issue for `gdb` on Linux using the following configuration:
```
    {
        "name": "Start Debugging",
        "type": "cppdbg",
        "linux": {
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "python import sys;sys.path.insert(0, '/usr/share/gcc-8/python');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
                    "ignoreFailures": false
                },
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
        "request": "launch",
        "program": "${cwd}/myExe.exe",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "externalConsole": false
    }
```

Hope this helps someone.

**Comment by ParkHaeChan** [comment]
Using Windows 10, 64 bit, I tried @yanglr  's comment.
It works! Unzip the mingw32 file and overwrite c:\\MINGW\\mingw32 and change
.vscode/launch.json : "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
--> "miDebuggerPath": "C:\\MinGW\\mingw32\\bin\\gdb.exe",


 That's all.

**Comment by yogendrarp** [comment]
> Installing `gcc-debuginfo` like the link instructed enabled formatting when looking in STL containers in locals - that's what I was going for. Thanks so much @pieandcakes!

Worked for me

**Comment by yanglr** [comment]
> Using Windows 10, 64 bit, I tried @yanglr 's comment.
> It works! Unzip the mingw32 file and overwrite c:\MINGW\mingw32 and change
> .vscode/launch.json : "miDebuggerPath": "C:\MinGW\bin\gdb.exe",
> --> "miDebuggerPath": "C:\MinGW\mingw32\bin\gdb.exe",
> 
>  That's all.

@ParkHaeChan Happy to know that. 😎

**Comment by stellarpower** [comment]
If anyone happens to be in a conda/mamba environment, this did it for me (Using the micromamba extension):
- Install gdb (and python, if not already present) *inside* the environment
- change `miDebuggerPath` to point explicitly to this (`bin/gdb` under your env root)
- Point to the corresponding location in the workaround as above - i.e., inserting the import manually:

> I was able to solve this issue for `gdb` on Linux using the following configuration:
> 
> ```
>     {
>        ....
>             "setupCommands": [
>                 {
>                     "description": "Enable pretty-printing for gdb",
>                     "text": "python import sys;sys.path.insert(0, '/path/to/your/env/share/gcc-version/python');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
>                     "ignoreFailures": false
>                 },
>         ...
>     }
> ```
> 
> Hope this helps someone.

Note that you don't need to adjust the cxx standard number above - this is presumably with the breaking ABI changes around C++11.

**Comment by onlytailei** [comment]
> I was able to solve this issue for `gdb` on Linux using the following configuration:
> 
> ```
>     {
>         "name": "Start Debugging",
>         "type": "cppdbg",
>         "linux": {
>             "MIMode": "gdb",
>             "setupCommands": [
>                 {
>                     "description": "Enable pretty-printing for gdb",
>                     "text": "python import sys;sys.path.insert(0, '/usr/share/gcc-8/python');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
>                     "ignoreFailures": false
>                 },
>                 {
>                     "description": "Enable pretty-printing for gdb",
>                     "text": "-enable-pretty-printing",
>                     "ignoreFailures": true
>                 }
>             ]
>         },
>         "request": "launch",
>         "program": "${cwd}/myExe.exe",
>         "args": [],
>         "stopAtEntry": false,
>         "cwd": "${workspaceFolder}",
>         "externalConsole": false
>     }
> ```
> 
> Hope this helps someone.

It works for me, change the gcc version to the local one in ubuntu.  
Save my day.

**Comment by zhalice2011** [comment]
very very thinks, it work for me

**Comment by Telanx** [comment]
@[herrberk](https://github.com/herrberk) 
thx a lot,it also works fine on window7
![微信图片_20220322001619](https://user-images.githubusercontent.com/3286367/159306016-dfd448d6-e0a7-448d-bfc1-46e91aec05a4.png)

```json
{
                "description": "Enable pretty-printing for gdb",
                "text": "python import sys;sys.path.insert(0, 'C:\\Users\\Administrator\\stlprettyprinter');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
                "ignoreFailures": false
            }
```

**Comment by mukulodd1** [comment]
How to address this issue in windows
