### ISSUE TITLE
always get this error with visual studio code in linux mint

### ISSUE THREAD

**Issue by mechanicalsoftwareengineer** [microsoft/vscode-cpptools#6900]
under
#include <stdio.h>
its highlighted red/orange and this error and hint comes up

#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (/home/dev/programming/test.c).C/C++(1696)
cannot open source file "gnu/stubs-32.h" (dependency of "stdio.h")C/C++(1696)

**Comment by sean-mcmanus** [comment]
You're on Linux? What version of the C/C++ extension are you using? What is your compilerPath set to? Output of C/C++: Log Diagnostics (after opening test.c) may also help. Be sure to remove all system includes from your includePath setting.

**Comment by sean-mcmanus** [comment]
You should get output like
```
    Compiler Path: /usr/bin/gcc-10
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/10/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c11
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=100200
```

The stubs-32.h should be at /usr/include/x86_64-linux-gnu/gnu/, but it shouldn't be used unless your intelliSenseMode is set to "linux-gcc-x86" -- is that intentional or did you intend to use linux-gcc-x64? We don't support 32-bit Linux as a host platform, so if you're targeting 32-bit Linux you'll need to make sure you've installed the necessary gcc libraries to target 32-bit apps.

**Comment by mechanicalsoftwareengineer** [comment]
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/x86_64-linux-gnu"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x86"
        }
    ],
    "version": 4
}

is that what your looking for?otherwise how do i print output of log diagnostics?

**Comment by sean-mcmanus** [comment]
Can you run the C/C++: Log Diagnostics comment from the Command Palette?

**Comment by sean-mcmanus** [comment]
Also, you should remove /usr/include/x86_64-linux-gnu from includePath.

**Comment by mechanicalsoftwareengineer** [comment]
-------- Diagnostics - 09/02/2021, 11:49:55 pm
Version: 1.2.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**",
        "/usr/include/x86_64-linux-gnu"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "c++17",
    "intelliSenseMode": "gcc-x86",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "/usr/include/x86_64-linux-gnu"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/dev/programming/test.c ]:
    /home/dev/programming/test.c
Translation Unit Configurations:
[ /home/dev/programming/test.c ]:
    Process ID: 80697
    Memory Usage: 13 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/x86_64-linux-gnu
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x86
    Other Flags:
        --gcc
        --gnu_version=90300
Total Memory Usage: 13 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 3252
Number of files discovered (not excluded): 3103

**Comment by mechanicalsoftwareengineer** [comment]
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (/home/dev/programming/test.c).
cannot open source file "gnu/stubs-32.h" (dependency of "stdio.h")
problems tab

**Comment by mechanicalsoftwareengineer** [comment]
cannot open source file "bits/libc-header-start.h" (dependency of "stdio.h")
cannot open source file "bits/libc-header-start.h" (dependency of "stdlib.h")
since removing the include path as u mentioned more errors

**Comment by sean-mcmanus** [comment]
When you go to definition on `#include <bits/libc-header-start.h" it should open

/usr/include/x86_64-linux-gnu/bits/libc-header-start.h

and when you do C/C++: Log Diagnostics you should see
```
/usr/lib/gcc/x86_64-linux-gnu/9/include
/usr/local/include
/usr/include/x86_64-linux-gnu
/usr/include
```
are you seeing different results?

**Comment by mechanicalsoftwareengineer** [comment]
https://ibb.co/hDHqSHd

**Comment by bobbrow** [comment]
Did you mean to set the `intelliSenseMode` to `gcc-x86` if you're adding x86_64 headers to the path?  Can you try `gcc-x64`?

**Comment by mechanicalsoftwareengineer** [comment]
> Did you mean to set the `intelliSenseMode` to `gcc-x86` if you're adding x86_64 headers to the path? Can you try `gcc-x64`?

what you mean? im still trying to fix the definition problem? the error i get for stdio and stdlib

**Comment by sean-mcmanus** [comment]
Yeah, Bob was saying the /usr/include/x86_64-linux-gnu paths are for 64-bit targets. Did you want to pass -m32 to target a 32-bit target or use a gcc-x64 intelliSenseMode? From your screenshot, it looks like you may not have the 64-bit gcc libs installed, so using -m32 might fix it. You should also compare with whatever you're using to build with to make sure they match the IntelliSense configuration.

**Comment by mechanicalsoftwareengineer** [comment]
> > Did you mean to set the `intelliSenseMode` to `gcc-x86` if you're adding x86_64 headers to the path? Can you try `gcc-x64`?
> 
> what you mean? im still trying to fix the definition problem? the error i get for stdio and stdlib

can u give me the exact instruction of what to add to make this work?

**Comment by mechanicalsoftwareengineer** [comment]
> Did you mean to set the `intelliSenseMode` to `gcc-x86` if you're adding x86_64 headers to the path? Can you try `gcc-x64`?

okay if thats the issue how do i fix that?

**Comment by mechanicalsoftwareengineer** [comment]
> Yeah, Bob was saying the /usr/include/x86_64-linux-gnu paths are for 64-bit targets. Did you want to pass -m32 to target a 32-bit target or use a gcc-x64 intelliSenseMode? From your screenshot, it looks like you may not have the 64-bit gcc package installed, so using -m32 might fix it. You should also compare with whatever you're using to build with to make sure they match the IntelliSense configuration.

where do i add the -m32 ?

**Comment by sean-mcmanus** [comment]
Can you add it to compilerArgs? However, even with "-m32" I'm still seeing "/usr/lib/gcc/x86_64-linux-gnu/10/include", but I don't have `include/i386-linux-gnu/c++/10` paths which you might have if you've installed the 32-bit gcc targetting libraries.

**Comment by mechanicalsoftwareengineer** [comment]
{
    "configurations": [
        {
            "name": "Linux",
            "compilerArgs":["-m32"],
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x86"
        }
    ],
    "version": 4
}
still gives same error

**Comment by sean-mcmanus** [comment]
Are you able to build with /usr/bin/gcc? Are you using different arguments to build?

**Comment by mechanicalsoftwareengineer** [comment]
> Executing task: C/C++: gcc build active file <

Starting build...
/usr/bin/gcc -g /home/dev/programming/test.c -o /home/dev/programming/test -m32
In file included from /home/dev/programming/test.c:1:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
   27 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Build finished with error(s).
The terminal process failed to launch (exit code: -1).

Terminal will be reused by tasks, press any key to close it.

**Comment by sean-mcmanus** [comment]
Yeah, that error occurs when you don't have the 32-bit gcc libraries installed. Do you want to build a 32-bit or 64-bit binary?

**Comment by mechanicalsoftwareengineer** [comment]
i thought i had installed 64 bit vscode ? i do have binutils installed in linux too? so whats missing?

**Comment by mechanicalsoftwareengineer** [comment]
> Yeah, that error occurs when you don't have the 32-bit gcc libraries installed. Do you want to build a 32-bit or 64-bit binary?

honestly right now doesnt matter , what is the quickest way to fix this?

**Comment by sean-mcmanus** [comment]
64-bit VS Code doesn't matter. Assuming your OS is 64-bit and your desired target is 64-bit, you should change your intelliSenseMode to "linux-gcc-x64" and remove the -m32 from your build.

**Comment by mechanicalsoftwareengineer** [comment]
> 64-bit VS Code doesn't matter. Assuming your OS is 64-bit and your desired target is 64-bit, you should change your intelliSenseMode to "linux-gcc-x64" and remove the -m32 from your build (and compilerArgs).

how do i change it?

**Comment by mechanicalsoftwareengineer** [comment]
> linux-gcc-x64

https://ibb.co/bHMS6dr
https://ibb.co/vVzRKtQ

ok i done this seems to have done the trick, damn man u should have said that from the start, we did a whole big u turn for nothing
