### ISSUE TITLE
headerfile not found

### ISSUE THREAD

**Issue by vivek-2567** [microsoft/vscode-cpptools#6903]
Issue Type: <b>Bug</b>

For C source files, IntelliSenseMode was changed from "macos-gcc-arm64" to "macos-clang-arm64" based on compiler args and querying compilerPath: "/usr/bin/gcc"
For C++ source files, IntelliSenseMode was changed from "macos-gcc-arm64" to "macos-clang-arm64" based on compiler args and querying compilerPath: "/usr/bin/gcc"

I found this written on the output tab. I tried to change the IntelliScense mode to 'macos-clang-arm64' but it does not stop showing read line under the statement "#include<stdio.h>"

Extension version: 1.2.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id d0370efe-1fd9-453f-9e57-eda51c5dda38|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by sean-mcmanus** [comment]
The config warning means that /usr/bin/gcc is actually a symlink to a clang compiler so it auto-fixed your intelliSenseMode.

stdio.h getting a squiggle is a different issue. I'm seeing it at Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h or Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include/stdio.h -- can you locate where stdio.h is or install those libraries?
