### ISSUE TITLE
Enhanced colorization does not work for some keywords

### ISSUE THREAD

**Issue by mmatrosov** [microsoft/vscode-cpptools#6904]
I am customizing colors for C++ code with help of this guide: https://code.visualstudio.com/docs/cpp/colorization-cpp

It works fine, however, seems like there is no way to change colors for some keywords like `const`, `using` or `virtual`. Here is my `settings.json`:

```
{
  "workbench.colorTheme": "Visual Studio Dark - C++",
  "editor.tokenColorCustomizations": {
    "[Visual Studio Dark - C++]": {
      "keywords": "#fafa47"
    }
  },
  "editor.semanticTokenColorCustomizations": {
    "[Visual Studio Dark - C++]": {
      "rules": {
        "method": "#fd952c",
        "property": "#FFBF80",
        "parameter": "#c8c8c8",
        "namespace": "#4ec9b0",
        "function": "#FF8080",
        "method.static": "#FF8080",
        "variable.global": "#fcacac",
        "property.static": "#fcacac"
      }
    }
  }
}
```

Here is how some code looks:

![image](https://user-images.githubusercontent.com/3617951/106888161-3a89d980-66f7-11eb-87ec-40c702922c2b.png)

As you can see, `int` and `void` have the color specified in "keywords", but `using` and `const` do not. And it seems like there is no way to change their color.

**Comment by Colengms** [comment]
Hi @mmatrosov .  Enhanced colorization is semantic.  It's used to color tokens that essentially require compilation to identify, such as class names, function names, etc..  The tokens you are referring to are keywords, and are colored syntactically.  Syntactic colorization is provided by VS Code directly.  VS Code uses TextMate grammar to identify keywords, and currently ingests the grammar provided by Jeff Hykin in this repo: https://github.com/jeff-hykin/cpp-textmate-grammar

I'd suggest following up in that repo for any issues involving syntactic tokens.  Jeff also releases an extension called "Better C++ Syntax" which may contain fixes to this grammar before ingested into VS Code.

That said, you might try using the "Inspect Editor Tokens and Scopes" command, and clicking on the elements you'd like to recolor.  That should provide the semantic or syntactic 'scope' used to color the token.

**Comment by Colengms** [comment]
Closing, as this is external to the C/C++ Extension.

**Comment by mmatrosov** [comment]
I am currently discussing this issue with @jeff-hykin (see https://github.com/jeff-hykin/cpp-textmate-grammar/issues/535) and I am frustrated. It seems like there is no simple way to do a thing as simple as to set a color for C++ keywords. As a user, I want to be able to define it in a single place. Now I have to have several complex items in the config. Are there any ideas on how to fix this in the future and to make this more user-friendly?

**Comment by sean-mcmanus** [comment]
I don't know.

**Comment by Colengms** [comment]
Hi @mmatrosov .  We used to color semantic tokens directly using 'text decorations', until the Semantic Tokens API was added to VS Code.  We now return semantic token scopes (which don't overlaps with TextMate scopes), and associate those with TextMate scopes to fall back to if there is no color specified for the semantic scope, for backwards compatibility.  I don't think our current implementation would cause issues with `keyword.operator` or `keyword.operator.cast`, as we don't directly refer to either.  There may be VS Code bugs here.  I'd suggest following up in the [VS Code repo](https://github.com/microsoft/vscode).

**Comment by mmatrosov** [comment]
Concerning the issue with `static_cast` (https://github.com/jeff-hykin/cpp-textmate-grammar/issues/535#issuecomment-779119445). Could it be related with the textmate scopes:

```
keyword.operator.cast.static_cast.cpp
keyword.operator.wordlike.cpp
meta.body.function.definition.cpp
meta.function.definition.cpp
source.cpp
```

The issue appears when I use `keyword.operator` pattern, which matches two of the items in this list.

**Comment by mmatrosov** [comment]
Ok, I got it. The current color theme is "Dark+ (default dark)", which is represented by `/snap/code/55/usr/share/code/resources/app/extensions/theme-defaults/themes/dark_plus.json` (cannot find this file on github), which includes `dark_vs.json`, which has the following content:

```
{
	"$schema": "vscode://schemas/color-theme",
	"name": "Dark (Visual Studio)",
	"include": "./dark_defaults.json",
	"tokenColors": [
    // ...
		{
			"scope": [
				"keyword.operator.new",
				"keyword.operator.expression",
				"keyword.operator.cast",
				"keyword.operator.sizeof",
				"keyword.operator.alignof",
				"keyword.operator.typeid",
				"keyword.operator.alignas",
				"keyword.operator.instanceof",
				"keyword.operator.logical.python",
				"keyword.operator.wordlike"
			],
			"settings": {
				"foreground": "#569cd6"
			}
		},
```

So it causes the troubles and seems like I cannot change it.

**Comment by Colengms** [comment]
Hi @mmatrosov .  You might considered creating your own theme, so you are no longer inheriting these values from an existing Theme.  You could copy Dark+ theme, make your changes to it, and remove the scopes that are causing you problems.  (Themes can include other themes, which I believe Dark+ uses, so you may need to duplicate multiple files).

On Windows, the default themes appear to be here: `%USERPROFILE%\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes`
