### ISSUE TITLE
Make intellisense not browse specific /usr/include subdirectories

### ISSUE THREAD

**Issue by LoeDK** [microsoft/vscode-cpptools#6905]
Hi!

I am developing a lib of which I also have the official `-dev` package installed. In other words: I have sources and packaged libs of one common project on one machine. The packaged libs are installed and the headers are in `/usr/include/`. The sources are in my `workspaceFolder`.

I need the packaged libs for other projects but would like to be able to continue my work on this lib locally.

During development in vscode, I would like Intellisense to ignore the presence of the header files that are present in `/usr/include/` and instead only refer to my local sources.
Is there any way for me to tell cpptools not to browse certain paths in `/usr/include/`? `CTRL+Mouse1` always opens the ones in `/usr/include` and also indicates mistakes when I locally declare function interfaces differently than in the packaged lib / headers.

Any pointers are greatly appreciated!

**Comment by yulei900609** [comment]
I had the same problem. excludepath?

**Comment by LoeDK** [comment]
I've done some research on it and couldn't find an excludepath option. Could you give me a list of steps, please?

**Comment by yulei900609** [comment]
> I've done some research on it and couldn't find an excludepath option. Could you give me a list of steps, please?

You are right, there is no excludepath parameter for now.

**Comment by sean-mcmanus** [comment]
If you do Go to Definition on a `#include` and it opens a file under /usr/include, that means your compilerPath and compilerArgs setting is returning /usr/include as the first matching path that has the include -- so you need to configure those arguments to match what however you're compiling to get those to be ignore. However, my guess is that your local library that you want to use is being configured as a recursive includes (ending with `**`) which is causing it to get moved to a lower priority than system includes, so you'll need to explicitly add those user library paths to your includePath as a non-recursive include to get them to be used instead of /usr/include.

If you want to remove the /usr/include files from workspace symbol parsing, you can add that path to your files.exclude setting.

**Comment by LoeDK** [comment]
Thank you so much for writing this up. I will make sure to test it asap.

**Comment by LoeDK** [comment]
Yes, sorry. I had to take a break.
I will report back as soon as I could test it.

Thank you for the reminder

**Comment by LoeDK** [comment]
I tried it out and it didn't work for me.
Let me elaborate on what "it" is that I tried - hopefully you can point out the mistake(s) I made:

The library that I want to enhance is called `foo` and has a single header file that is present in `/usr/include/foo/foo.h` and in `${workspaceFolder}/cpp/lib/foo/foo.h`.
I added a member `bar` to the `Foo` class in my ${workspaceFolder} and included `<foo/foo.h>` in another file in my ${workspaceFolder}.

My settings look like this:
settings.json:
```
    "files.exclude": {
        "/usr/include/foo/**": true
    },
    "search.exclude": {
        "/usr/include/foo/**": true
   }
```
c_cpp_properties.json:
```
{
    "configurations": [
        {
            "includePath": [
                "${workspaceFolder}/cpp/lib/foo",
                "${workspaceFolder}/**"
            ]
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu11",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

When I access `Foo::bar` in another file, C/C++ still raises a problem:
class "Foo" has no member "bar" C/C++(135)

Go To Definition on `#include <foo/foo.h>` still opens /usr/include/foo/foo.h
Go To Definition on `Foo::bar` opens `${workspaceFolder}/cpp/lib/foo/foo.h`.

When I add a forcedInclude to c_cpp_properties.json, the error immediately disappears and `bar` is correctly identified as a member of `Foo`.
Like so:
```
            "forcedInclude": [
                "${workspaceFolder}/cpp/lib/foo/foo.h"
            ],
```
This however doesn't change the Go To Definition behavior.

What am I doing wrong? @sean-mcmanus

**Comment by sean-mcmanus** [comment]
`"/usr/include/foo/**": true` won't work until 1.4.0-insiders, i.e. it's a bug we fixed. Can you remove the "/**" part as a workaround?

**Comment by LoeDK** [comment]
Thank you, @sean-mcmanus!
1.4.0-insiders is out and the workaround did work too.
