### ISSUE TITLE
C++17 Not working?

### ISSUE THREAD

**Issue by ErikDz** [microsoft/vscode-cpptools#6907]
Type: General

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: Latest
- C/C++ Extension Version: Latest
- Other extensions you installed (and if the issue persists after disabling them): Python
- C++17 claims to be default but upon compiling, error as if version compiling wasn't C++17

**To Reproduce**
```
#include <string>
#include <iostream>
#include <filesystem>
namespace fs = std::experimental::filesystem;

int main()
{
    std::string path = "/path/to/directory";
    for (const auto & entry : fs::directory_iterator(path))
        std::cout << entry.path() << std::endl;
}
```
```
{
	"version": "2.0.0",
	"tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: cl.exe compilar archivo activo",
            "command": "cl.exe",
            "args": [
                "-std=c++17",
                "/Zi",
                "/EHsc",
                "/nologo",
                "/Fe:",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "${file}"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$msCompile"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "compilador: cl.exe"
        }
    ]
}
```

**Expected behavior**
Program should list directories

**Screenshots**
![image](https://user-images.githubusercontent.com/22724935/106926971-f48e3f00-6711-11eb-9f79-9d9e0bd1ff2b.png)
![image](https://user-images.githubusercontent.com/22724935/106927016-01ab2e00-6712-11eb-8800-e546b2b4ac42.png)

**Comment by Colengms** [comment]
Hi @ErikDz .  It looks like the `std` arg is incorrect in your `tasks.json`.  For `cl.exe`, it should be `/std:c++17`.  This arg doesn't appear to be generated for me, when using `Build and Debug Active File`, so it's unclear to me if this is an issue with the C/C++ Extension.  Could you confirm whether this arg was added by you, or added automatically somehow?
