### ISSUE TITLE
clang-format does not work well

### ISSUE THREAD

**Issue by otsuka-kohei** [microsoft/vscode-cpptools#691]
I write `C_Cpp.clang_format_style": "{BasedOnStyle: Google,IndentWidth: 4,ColumnLimit: 0}` to settings.json.
But clang-format does not format with IndentWidth option and ColumnLimit option.
[clang-format by xaver](https://github.com/xaverh/vscode-clang-format-provider) works with these options.
Please fix this problem.

**Comment by sean-mcmanus** [comment]
Hmm...I am not able to repro a problem on Windows and Linux. Could you give more specific details? Maybe there's some other requirement?

**Comment by sean-mcmanus** [comment]
I reviewed the code and fixed one bug which could cause this failure if there's a space before the {. Does removing any space before the { fix it?

**Comment by otsuka-kohei** [comment]
Thank you response.
My settings.json does not include a space before the "{".
But I use this extesion that I can install by standard VSCode function.

**Comment by sean-mcmanus** [comment]
I am not able to repro the bug, so I need more repro details.

**Comment by bobbrow** [comment]
Can you please try out 0.16.0 and look at the "C/C++" log channel of the Output window when your formatting fails? If you are unable to resolve your clang-format issues with the logging message, please reopen this issue and we can help you resolve it.
