### ISSUE TITLE
[windows][include problem]fatal error C1083: Cannot open include file

### ISSUE THREAD

**Issue by xuanyuanlei1020** [microsoft/vscode-cpptools#6911]
**Type: LanguageService**
**Describe the bug**
- OS and Version: windows_NT x64 10.0/18363
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.2.0
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

**Steps to reproduce**
Steps: 
1. Copy boost include files to workspace directory.
2. Create a cpp file like below to build. 
```cpp

#include <boost/graph/adjacency_list.hpp>
#include <iostream>

int main()
{
  boost::adjacency_list<> g;

  boost::adjacency_list<>::vertex_descriptor v1 = boost::add_vertex(g);
  boost::adjacency_list<>::vertex_descriptor v2 = boost::add_vertex(g);
  boost::adjacency_list<>::vertex_descriptor v3 = boost::add_vertex(g);
  boost::adjacency_list<>::vertex_descriptor v4 = boost::add_vertex(g);

  std::cout << v1 << ", " << v2 << ", " << v3 << ", " << v4 << '\n';
}

```
3. Run Build Task ->  C/C++: cl.exe build active file
4. ERROR: "fatal error C1083: Cannot open include file: 'boost/graph/adjacency_list.hpp': No such file or directory"

**Expected behavior**

Step4 should build successfully.

**My Guess**

1. It seems that it is the "/"(slash) and "\\"(backslash) triggered this issue. As windows uses "\\"(backslash)  as path separator . And it seems that cl.exe only parse the path who uses "\\"(backslash).
2. When I change above " <boost/graph/adjacency_list.hpp>" to "<boost\graph\adjacency_list.hpp>", then cl.exe can find the "adjacency_list.hpp".
3. But cl.exe still can not find the dependency file of "adjacency_list.hpp", as it uses "/"(slash)

**Others**
Maybe it is not the problem of "c/c++ enxtension", is it  any possible to let cl.exe to parse "/"(slash) as path separator ?

!!Thanks!!

**Comment by sean-mcmanus** [comment]
Forward slash should work. I'm not sure why it's not working for you. I don't think the issue is related to our extension or VS Code. You could try compiling with cl.exe on the command line to verify. See https://stackoverflow.com/questions/29119638/why-path-in-vs-c-contains-forward-slash-not-backslash

**Comment by xuanyuanlei1020** [comment]
> Forward slash should work. I'm not sure why it's not working for you. I don't think the issue is related to our extension or VS Code. You could try compiling with cl.exe on the command line to verify. See https://stackoverflow.com/questions/29119638/why-path-in-vs-c-contains-forward-slash-not-backslash

First of all, thanks for your reply. Your explanation is correct. **Forward slash did work** to cl.exe. 

After some test, it seems that it was triggered by "<>" of include.  Below include pattern can **not** work.
```cpp
#include <boost/graph/adjacency_list.hpp>
```
But below include pattern works:
```cpp
#include "boost/graph/adjacency_list.hpp"
```

My guess is:

It is the preprocessor's problem. As we all know for `#include <filename>`, the preprocessor searches directories pre-designated by the compiler/IDE.  And for `#include "filename"` the preprocessor searches first in the same directory. 

So my question become how to let preprocessor to search local directory for `#include <filename>` pattern. 

Thanks a lot again.

**Comment by sean-mcmanus** [comment]
c_cpp_properties.json doesn't apply to build tasks. You need to add `"/I", "${workspaceFolder}"` to "args" in your tasks.json.

**Comment by xuanyuanlei1020** [comment]
Thank you very much. Your reply did solve my problem. 

Below is my summary to use this wonderful extension:

1. In build task, if your `VS code` can **not** find cl.exe, you might need to open `VS code` at `Developer Command Prompt for VS xxxx`. 
2. In build task,  if your `VS code` still can **not** find cl.exe, you might need to open `VS code` at `Developer Command Prompt for VS xxxx` with Administrator role. => `Run as Administrator`.
3. If build task, if your `VS code` can not find the `include` file, you might need to add your include folder to `tasks.json`

 For example:

```json
{
    "version": "2.0.0",
    "tasks": [
      {
        "type": "shell",
        "label": "cl.exe build active file",
        "command": "cl.exe",
        "args": [
          "/Zi",
          "/EHsc",
          "/Fe:",
          "${fileDirname}\\${fileBasenameNoExtension}.exe",
          "${file}",
          "/I",
          "${workspaceFolder}"
        ],
        "problemMatcher": ["$msCompile"],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]
  }
```

Again, thanks a lot . Happy Chinese New Year to you.
