### ISSUE TITLE
Debugger hangs when any breakpoint gets triggered (MSVC)

### ISSUE THREAD

**Issue by Zylann** [microsoft/vscode-cpptools#6913]
Type: Debugger

**Describe the bug**
- OS and Version: Windows 10 64 bits
- VS Code Version: 1.53.0
- C/C++ Extension Version: 1.2.0
- Other extensions you installed (and if the issue persists after disabling them): Git Blame, Python, Jupyter, reStructuredText

I'm using VSCode to debug [Godot Engine](https://github.com/godotengine/godot). I haven't changed anything to my setup which was working for months/years.
A few days ago, starting a debug session on Godot took about 10 to 15 more seconds of hang, which was unusual.
But today I noticed it also hangs endlessly, whenever any breakpoint is hit. That happens for breakpoints I place myself, or automatic breakpoints that occur due to an assert or exception. As a result, it's become impossible to use the debugger at all. I'm back to using prints...
Interestingly, so far it only happens on Godot, but it doesn't happen on much smaller projects.

**To Reproduce**
I don't precisely know what reproduction steps this would require, or if it will even work on others computer, because so far nobody else I asked has the issue. It seems to have started overnight without explicit actions from me, so there is no steps I can think of.
The steps would be to clone Godot Engine, build it in debug using MSVC (I got it from Visual Studio 2017):
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x64
```
And then trying to debug it using VSCode.
This is what my json looks like:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bin/godot.windows.tools.64.exe",
            "args": [
                "-v", // Verbose output
            ],
            "stopAtEntry": false,
            "cwd": "D:/PROJETS/INFO/GODOT/Games/SolarSystem",
            "environment": [],
        }
    ]
}
```

**Additional context**
- There are no logs or error messages of any kind, it just hangs.
In the task manager, I can also see the debugger spinning a full CPU core and not responding.
![image](https://user-images.githubusercontent.com/1311555/107099531-dad02300-6809-11eb-929a-b5d7bd84858d.png)
Memory seems to keep going up as well.

- I tried using MinGW instead but this comes with its own can of worms: with Godot Engine, link times are absurdly long and debugging is only half-working.

- I tried rolling back to VSCode 1.52 but it did not change anything. While debugging Godot if I put a breakpoint in the beginning of the main function, I can see it is paused on a breakpoint, but the editor doesn't react to this, and if I try to unfold the call stack it loads forever, and I can't step either:
![image](https://user-images.githubusercontent.com/1311555/107128139-2be82180-68b3-11eb-989d-80dcfd09b5af.png)

- I tried installing a newer version of Visual Studio compiler and debugger (2019), but apart from confusing Godot's build system (SCons) it didn't fix anything, and I could not find any info to tell which debugger VSCode is going to use...

- I tried using Visual Studio to attach to the Godot process, and I was able to break and step through the main loop of the engine. So this looks like a bug in VSCode/CppTools.
    - I could not figure out how to simply tell Visual Studio to start debugging the executable without a project. Godot doesn't come with one, and SCons could not generate any project due to the presence of two versions of MSVC, so I wasn't able to test putting a breakpoint in the same spot of the main function.
    - I could not figure out how to use "attach to process" from VSCode so I have no idea if the problem also happens when using that.

- I'd like to emphasize that the edit-compile-debug workflow was perfectly working for years until a few days ago, even though nothing changed in my setup (I did not even get a more recent version of Godot's repo). It seems to have broke overnight, and now my workflow is crippled.

**Comment by ringoz** [comment]
yep, something bad has happened with debugging performance recently.
it hangs on first pause/breakpoint, about 5 seconds in my case.

**Comment by WardenGnaw** [comment]
We will have to investigate. The version of vsdbg shipped in the C/C++ extension uses the same components as the debugger in Visual Studio to example the process/memory and fetch the results. We have not seen any performance issues there. 

> I could not figure out how to simply tell Visual Studio to start debugging the executable without a project. Godot doesn't come with one, and SCons could not generate any project due to the presence of two versions of MSVC, so I wasn't able to test putting a breakpoint in the same spot of the main function.

You could use the Visual Studio `Open -> File` and select your exe and `F5` to start a debug session. 

> I'd like to emphasize that the edit-compile-debug workflow was perfectly working for years until a few days ago, even though nothing changed in my setup (I did not even get a more recent version of Godot's repo). It seems to have broke overnight, and now my workflow is crippled.

Do you see this issue in an older version of cpptools (1.1.3)?  You can downgrade by going to the Extensions tab, click on the gear on C/C++ and select `Install Another Version`

**Comment by Zylann** [comment]
> Do you see this issue in an older version of cpptools (1.1.3)? You can downgrade by going to the Extensions tab, click on the gear on C/C++ and select Install Another Version

I just tried that and the issue went away. Maybe something broke in version 1.2.0 from February 2?

**Comment by William-H-M** [comment]
Would like add to this that if when the interface alert of the break point being hit, if you minimize and then immediately restore the window the break point will start working, if you don't it will take more time.

OS and Version: Windows 10 64 bits
VS Code Version: 1.53.2
PHP Version: 7.2.22
Extension: PHP Debug 1.14.9
XDubug: 2.7.2 and 3.X

**Comment by ringoz** [comment]
Looks like hanging time is somehow related to PDB loading.
It hangs for longer times if PDB symbols are available (in my case for system libs, like kernel32, ntdll, etc.)

**Comment by Zzephaniahh** [comment]
Getting a similar issue on Catalina 10.15.7 it hung forever and consumed all my CPU on my brand new Mac. I was able to fix it by disabling my Jupyter v2021.5.702919634 plugin. I wouldn't have expected the plugin to crash my C++ debugging. No idea what is the root cause.

**Comment by Zylann** [comment]
Interesting, I do have Jupyter too as a side-effect of https://github.com/microsoft/vscode-python/issues/14857, since our project uses SCons to build so I use the Python extension to edit our build scripts.

I'm still stuck on C++ plugin version 1.1.3, so I tried updating to 1.2.2, and the issue still persists. I tried uninstalling the Python extension (just so I could uninstall the Jupyter extension...) but it didn't fix the problem for me.

**Comment by Zzephaniahh** [comment]
A few things I noticed:
It seems that it only hangs in my .cc files and not my .h files. If I start in a .h then I can proceed to a .cc in most cases, though it does still hang and move slowly. 

As soon as I disabled Jupyter last night it worked. It was getting late and I was glad to just be able to get some work done. I should have realized that it was just the only extension I had enabled on my new machine. This reoccurs if any extension (I tried a handful) is enabled. 

If I enable an extension and reload the window it will hang every time. If I then disable all extensions (other than c/c++), it will hand the first few (0-2) runs and then stop hanging. It will start a new instance of lldb-mi which spins my i9 CPU at 98% non-stop. After some moderate debugging I had 30 running concurrently, but they just appear and never stop every time I run a debug session. I closed vscode and the processes did not end until I manually killed them via the activity manager.

I can reproduce the issue so if you know any way to get less anecdotal, and more concrete information that might help let me know. Also if anyone knows what is going on with lldb-mi I'd be really grateful for someway to stop it from conquering my computer. I found this https://github.com/microsoft/vscode-cpptools/issues/4097 but they don't solve the issue.

**Comment by T6Guus** [comment]
I use the C++ extension to debug UE4.

I tested a few versions and it indeed seemed to have regressed from 1.1.3 => 1.2.0.
Looking at vsdbg.exe in process explorer shows that it's running 100% but only on a single-thread with memory usage slowly growing until it starts to respond again after ~15-20 seconds. No disk IO during the hang.

**Comment by WardenGnaw** [comment]
This is due to external performance regressions in the Expression Evaluator and vcruntime.

**Comment by AchilleBineli** [comment]
I have the same issue with Visual Code on MacOS while debugging a simple C++ project.

Context : MacOS Big Sur v 11.5.2, Visual Code Version: 1.60.1

The debugger stops at the first breakpoint as I want. Afterwards, it cannot load variables or step through. 

The process lldb-mi seems to take more than 90% of CPU even when I stop the debugging session. The laptop's fan goes wild too.

#
<img width="801" alt="lldb-mi process CPU percent" src="https://user-images.githubusercontent.com/32594342/134789560-a1b56db1-9d6b-40e3-a459-824dd36ba4ab.png">
