### ISSUE TITLE
Activate a conda environment when Debugging a python C++ module

### ISSUE THREAD

**Issue by tkuraku** [microsoft/vscode-cpptools#6919]
Type: Debugger

**Describe the bug**
- OS and Version: Linux 
- VS Code Version: 1.53.0
- C/C++ Extension Version: v1.2.0
- A clear and concise description of what the bug is.

**To Reproduce**

I have a python c++ module that has dependencies in a conda environment. However if the conda environment is not active in the shell that launches vscode, like when launching vscode using the desktop shortcut, there is no way to activate the environment during debug. I would like an option to be able to run a command in the debug window before the debug process is launched to setup the environment.

```
conda activate $myenv
```

**Comment by sean-mcmanus** [comment]
@WardenGnaw Did you know about this?

**Comment by tkuraku** [comment]
This would apply to any framework that wants you to activate it and isn't on the path by default, for example openvino.

FYI, I have the same problem with Visual Studio 2019 on Windows 10. There is no way to activate a conda environment to debug a c++ library. The same work around applies, activate a conda environment in a shell and launch Visual Studio from that shell.

**Comment by WardenGnaw** [comment]
You can use the `miDebuggerPath` to point to your own bash script that sets the environment and launches gdb

```
#!/bin/sh
conda activate $myenv
gdb $@
```

**Comment by tkuraku** [comment]
Thanks for the work around. By chance do you have a workaround for Visual Studio 2019?

**Comment by WardenGnaw** [comment]
I do not know of a good way to do the same thing in Visual Studio. 

You can ask this question at https://developercommunity.visualstudio.com/spaces/8/index.html

**Comment by andrei-pokrovsky** [comment]
You may also need to add

conda activate env_name

to your ~/.bashrc on your remote server.
