### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by maanisim** [microsoft/vscode-cpptools#6920]
Where problem was found on the following page: https://code.visualstudio.com/docs/languages/cpp#_install-the-extension

There is a link to an empty page, specifically "http://mingw.org/" within a phrase "install the Minimalist GNU for Windows " please remove this as it might be a future security risk. 👍

**Comment by WardenGnaw** [comment]
Moved to VSCode docs. https://github.com/microsoft/vscode-docs/issues/4308
