### ISSUE TITLE
Intellisense reports errors in a Cortex-M project using  the Nordic SDK

### ISSUE THREAD

**Issue by pthorn** [microsoft/vscode-cpptools#6923]
I have a C project for a Cortex-M target using the Nordic nRF5 SDK version 15.3.0, the compiler is arm-none-eabi-gcc 9.3. There're no include file errors. All uses of NRF_LOG_INFO, NRF_LOG_WARNING, NRF_LOG_ERROR etc.. macros generate squiggles with the error "expression must have integral typeC/C++(31)". (The code compiles and runs fine.)

![Screenshot 2021-02-08 at 10 59 25](https://user-images.githubusercontent.com/1325493/107191226-e9caf700-69fc-11eb-8059-ee6fac975d12.png)

- OS and Version: Mac OS 10.15.7
- VS Code Version: 1.53.0
- C/C++ Extension Version: 1.2.0

My c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "arm-gcc-macos",
            "compilerPath": "/(redacted)/arm-none-eabi-gcc/xpack-arm-none-eabi-gcc-9.3.1-1.4/bin/arm-none-eabi-gcc",
            "compilerArgs": [
                    "-mthumb",
                    "-mcpu=cortex-m4",
                    "-mfloat-abi=hard",
                    "-mfpu=fpv4-sp-d16"
	    ],
            "cStandard": "c99",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-arm",
            "compileCommands": "${workspaceRoot}/_build/compile_commands.json",
            "browse": {
                "path": ["${workspaceFolder}/src"],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceRoot}/.vscode/browse.vc.db"
            }
        }        
    ],
    "version": 4
}
```

**Comment by michelleangela** [comment]
@pthorn 
Could you provide the additional following logs to help us further investigate:

1. Log output from enabling the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
2. Log output from running the command `C/C++: Log Diagnostics`
