### ISSUE TITLE
Can't goto declaration or goto definition in .c file

### ISSUE THREAD

**Issue by khanhnt93** [microsoft/vscode-cpptools#693]
I have installed cpptools to code my C project. My code stored in server so I use share file feature to run vscode in my computer and coding directly in server.
I can't use goto declaration or goto definition feature. It show this message: command 'C_Cpp.GoToDeclaration' not found and there isn't option goto definition when right click.

**Comment by sean-mcmanus** [comment]
I think I have seen this problem randomly on startup on Mac, but it goes away after a while. What OS are you on? Are you able to get it to work after the bottom right is no longer red or on a smaller workspace?

**Comment by khanhnt93** [comment]
I'm using vscode in window 10. My project is large project (about 60k files), first times there is a red fire in a conner but recently I don't see it when start project. In smaller workspace, both features work fine. In my project, my code only in one file (over 2000 lines). I remember that 2 features work fine and recently it's not work.

**Comment by bobbrow** [comment]
If you don't ever see the red fire icon when opening your large folder, then it's possible that the extension has crashed.  This would also explain why you don't see "goto definition" in the right-click menu.  That red fire icon should always appear (even if it is only for a second) every time you open a folder - especially a large one with 60k files.

* Is the Microsoft.VSCode.CPP.Extension.exe process running after you open a C or C++ file in the editor?
* Can you give us any more information about your source server setup?
  * Is the server also a Windows PC?
  * Do you map the network path to a drive letter?
  * Do you have write access to all sub-folders of the folder you are opening?

**Comment by khanhnt93** [comment]
Hello bobbrow,
How to check extentsion running?
I use PC windows 10 to run vscode and store my project in a ubuntu server (install in vmware). I installed smb share file between windows 10 PC and ubuntu server so vscode have all write access to all sub-folders.
C/Cpp extention work fine before and it's have this problem recently.

**Comment by bobbrow** [comment]
To check if the extension is running, open Task Manager (taskmgr.exe).  You should see at least one of the Microsoft.VSCode.CPP.* processes running.

![taskmgr](https://cloud.githubusercontent.com/assets/12818240/25884687/10ea6a28-3509-11e7-98c3-135a9cf66535.png)

**Comment by khanhnt93** [comment]
I checked, there's not extention.

**Comment by khanhnt93** [comment]
I checked, it's not in task manager. When I try to close my folder and open a small file, this extention work fine and I saw it in task manager. After, I close vscode an open my project folder, cpp extension don't exist in task manager and of course I still can't use go to define :(.
So, I try to open a sub-folder, I saw the red fire icon and go to define work fine. I think cpp extention has problem with large project.

**Comment by bobbrow** [comment]
Ok, it sounds like the extension might be crashing then.  Just to double-check, when you opened your large project folder, did you open any C/C++ files too?  The extension process won't start until the first code file is open.

If you could help us debug this by attaching to the extension process when it launches, that would be very helpful.  [This blog post has instructions](https://bugslasher.net/2011/03/26/how-to-debug-a-process-as-soon-as-it-starts-with-windbg-or-visual-studio-2010/) on how to set up the debugger (WinDBG or Visual Studio) to attach to a process as soon as it is launched.  A note about the instructions is that they assume you have gflags.exe available (it comes with the [Debugging tools for Windows](https://msdn.microsoft.com/en-us/library/windows/hardware/ff551063(v=vs.85).aspx)), but if you don't it also tells you which registry key needs to be created.

The process that you want to attach to is **Microsoft.VSCode.CPP.Extension.exe**.  If the process never starts at all, that would also be interesting information.

**Comment by khanhnt93** [comment]
I open some C/C++ files when I open my large project folder and cpp extension wasn't start. I use processxp64 to view process started by vscode. This is result, there is'nt cpp extension process (this extension existed when I open smaller project folder):
![process](https://cloud.githubusercontent.com/assets/8996795/25931757/70163286-3638-11e7-9102-27b8c61564f3.png)

I will try to follow that instructions but I have a question, what process I need attach? Microsoft.VSCode.CPP.Extension.exe or vscode.exe?

**Comment by khanhnt93** [comment]
I used glags.exe to attach Microsoft.VSCode.CPP.Extension.exe when it was lunched in 2 case (first case is open large project folder, second is open smaller project folder) but windgb just break when I open my smaller project. So I think when I open my large project, Microsoft.VSCode.CPP.Extension.exe wasn't lunched. I believe that vscode has a function to check some coditions and lunch extensions before, how to debug at this function?
![windbg](https://cloud.githubusercontent.com/assets/8996795/25936956/04214770-3654-11e7-959d-0528b55ad883.png)

**Comment by MAntal001** [comment]
I had same problem. Solution from #667 helped

**Comment by sean-mcmanus** [comment]
@khanhnt93 Did https://github.com/Microsoft/vscode-cpptools/issues/667 help? You can also launch VS Code and do Help->Toggle Developer Tools to see more errors that might occur in our javascript code.

**Comment by khanhnt93** [comment]
Thank @bobbrow @martanec @sean-mcmanus for your help. #667 helped, I  added line 122 and this problem complete solve :D.
