### ISSUE TITLE
Unable to debug C++ Standard Library on macOS

### ISSUE THREAD

**Issue by afuschetto** [microsoft/vscode-cpptools#6930]
Type: Debugger

I am using _Visual Studio Code 1.53.0_ on macOS 11.1 with the _Microsoft C/C++ 1.2.0_ extension to evaluate the real usability in a production environment.

In my scenario, I am using Clang/LLVM 12.0.0 compiler and LLDB 1200.0.32.1 debugger.

For some unknown reason, I am unable to debug the C++ Standard Library. I can step into symbols defined in my application, but no way do the same with the standard ones, e.g. `std::vector` constructor.

Reading on web, I noticed that the C++ Standard Library debugging definitely works well on Linux using the GNU toolchain.

It is unclear whether this is an incorrect configuration or a limitation of these tools, although I am able to achieve the same goal using the LLDB tool from command line.

Regarding the tasks and launch configuration, I used the basic one suggested in the official documentation (of course, I can provide the files if needed).

**Comment by WardenGnaw** [comment]
This maybe be the difference of how `lldb` starts up vs `lldb-mi`. 

If you run `show target.process.thread.step-avoid-regexp` it shows the regex of functions to skip.

Does it step into the C++ Standard Library if you add the following to your `launch.json`:

```
"setupCommands" : [
   {
      "text": "settings set target.process.thread.step-avoid-regexp \"\"",
      "description": "Enable stepping into STL"
   }
]
```

Reference: https://stackoverflow.com/questions/19413181/step-into-stl-sources-in-xcode-5

**Comment by afuschetto** [comment]
Thanks @WardenGnaw, this answers my question. It is strange that using `lldb` from the command line, I am able to step into standard library symbols even if `target.process.thread.step-avoid-regexp` is set to `^std::` (default):

```
(lldb) settings show target.process.thread.step-avoid-regexp
target.process.thread.step-avoid-regexp (regex) = ^std::
(lldb) si
Process 39690 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = instruction step into
    frame #0: 0x00000001000017d9 test`main at test.cpp:8:23
   5   	using namespace std;
   6   	
   7   	int main() {
-> 8   	    vector<string> v{ "Hello", "World" };
   9   	    for (const auto& s : v) {
   10  	        cout << s << " ";
   11  	    }
Target 0: (test) stopped.
(lldb) si
Process 39690 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = instruction step into
    frame #0: 0x0000000100001a70 test`std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<std::nullptr_t>(this="", __s="") at string:817
   814 	
   815 	    template <class = typename enable_if<__is_allocator<_Allocator>::value, nullptr_t>::type>
   816 	    _LIBCPP_INLINE_VISIBILITY
-> 817 	    basic_string(const _CharT* __s) : __r_(__default_init_tag(), __default_init_tag()) {
   818 	      _LIBCPP_ASSERT(__s != nullptr, "basic_string(const char*) detected nullptr");
   819 	      __init(__s, traits_type::length(__s));
   820 	#   if _LIBCPP_DEBUG_LEVEL >= 2
Target 0: (test) stopped.
(lldb) 
```
