### ISSUE TITLE
New vision of  the New Year For MS-CPP-TEAMS

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#6932]
with VSCode's openness and full platform full language goals. I think the vscode-cpptools team has a responsibility and obligation to maintain and support this great goal.

But the c language is the most complex, so I implore the cpp team to support a broader scenario. 
Thus language compliance, software development design as well as extensible cooperation, can work with the community more convenient. 

For example, I am an embedded developer and I really need a language service that supports semantic analysis rather than debugging. But I don't think any other team can develop such a huge extension for the special c language to support this request. So thank you and hope you can consider the needs of the community. Just as c language complexity. This may complicate your extension. But the challenge is very meanful for any developer.

**Comment by sean-mcmanus** [comment]
What exactly are you requesting?

Our extension supports the C and C++ language standards. So if you can get your embedded extensions to those languages added to the standard then we'd support that. If you can get your extensions implemented in the gcc or clang or edg compilers (https://www.edg.com/) then that would increase the likelihood that we'd be able to have IntelliSense support.
