### ISSUE TITLE
vscode-cpptools fails to install offline with remote-SSH (remote.downloadExtensionsLocally)

### ISSUE THREAD

**Issue by aallrd** [microsoft/vscode-cpptools#6933]
**Describe the bug**
- OS and Version: RHEL 7.6
- VS Code Version: 1.53.0
- C/C++ Extension Version: 1.2.0

I am using VSCode to attach to my offline remote development environment using the remote-SSH extension.
In my VSCode settings I have listed the `ms-vscode.cpptools` as a default extension for my remote development session.
I have also configured the `remote.downloadExtensionsLocally` setting that downloads extensions locally and install them on the remote since it is offline.
```
{
    "remote.SSH.defaultExtensions": [
      "ms-vscode.cpptools",
      "mjcrouch.perforce",
      "llvm-vs-code-extensions.vscode-clangd"
    ],
    "remote.downloadExtensionsLocally": true
  }
```
It works fine for all the other extensions I am using but it seems that the `ms-vscode.cpptools` tries to download some stuff on the remote while it is being installed:

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed to download https://go.microsoft.com/fwlink/?linkid=2153757
Failed at stage: downloadPackages
Error: read ECONNRESET
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
```

Grabbing and manually installing the release from https://github.com/microsoft/vscode-cpptools/releases as stated in the error message works.
However I would like for the full offline release to be installed by default so it does not fail on this error.

Is there another version of the extension like `ms-vscode.cpptools-offline` I could configure to directly use the extension with all the dependencies pre-included?

**Comment by michelleangela** [comment]
The setting `remote.downloadExtensionsLocally` to `true` and failing to download locally and install remotely is a known issue https://github.com/microsoft/vscode-cpptools/issues/5290.

> Is there another version of the extension like ms-vscode.cpptools-offline I could configure to directly use the extension with all the dependencies pre-included?
The offline versions of the ms-vscode.cpptools package with all dependencies are available from https://github.com/microsoft/vscode-cpptools/releases as suggested from the error message. Each VSIX package pre-includes all dependencies so there is no need to download them when installing.
