### ISSUE TITLE
Add a command to add includePath/browse.path folders to the workspace

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cpptools#6935]
**Type: LanguageService**

**Describe the bug**
- OS and Version: win10 with remote on RHEL7
- VS Code Version: 1.53.0
- C/C++ Extension Version:, 1.2.0
- Does this issue involve using SSH remote to run the extension on a remote machine?: yes
- Description:

the project uses a lot of libraries - e.g. boost and zlib.
when I click on include statement it opens successfully however when i try to open the same or other header file from Ctrl+P, it can't find those by (partial) name
For sure: all those are in includePath

**Comment by michelleangela** [comment]
@amigo421 
Could you provide logs from the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) after you open the project and the extension has completed tag parsing? The logs will show which files are getting parsed.

**Comment by amigo421** [comment]
@michelleangela okay, I'll provide you with.
it's not unique for some one project, it 's for any project.

I'm writing "hello world" , and this can't open any header of standard library, if I write include <iostream>, I can open this by ctrl+click but not from Ctrl+P

anyway, I'll provide you with logs

**Comment by Colengms** [comment]
> when i try to open the same or other header file from Ctrl+P, it can't find those by (partial) name

Hi @amigo421 .  The files provided by Ctrl+P are within your project directory.  Are boost and zlib outside of your project directory?  If so, I believe that would be by-design.  That is a feature provided by VS, not the C/C++ Extension.

Consider opening a feature request in [the VS Code repo](https://github.com/microsoft/vscode), suggesting they add support for extensions to extend the list of files provided by Ctrl+P .

**Comment by amigo421** [comment]
> Hi @amigo421 . The files provided by Ctrl+P are within your project directory. Are boost and zlib outside of your project directory? If so, I believe that would be by-design. That is a feature provided by VS, not the C/C++ Extension.

Yes, this is what I mean. outside of the project folder
 
> Consider opening a feature request in [the VS Code repo](https://github.com/microsoft/vscode), suggesting they add support for extensions to extend the list of files provided by Ctrl+P .
Yes, I'll raise a request then 

thank you

**Comment by amigo421** [comment]
guys from vscode project suggested a good solution : add optional command to add additional folders to workspace by parsing includePath setting (manual adding include folders to the workspace works fine but wanted some automation).
