### ISSUE TITLE
Deprecated code 'externalConsole'

### ISSUE THREAD

**Issue by SmohcStahc** [microsoft/vscode-cpptools#6939]
Issue Type: <b>Bug</b>

Just press F5.
You will receive a new notification "The key 'externalConsole' is deprecated. Please use 'console' instead."
Receiving this notification causes the debug console to lose focus.

Extension version: 1.2.0
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041

**Comment by WardenGnaw** [comment]
Per https://github.com/microsoft/vscode-cpptools/pull/6794, `externalConsole` for `cppvsdbg` is now deprecated. 

Use `"console": "externalTerminal"` if you wanted `externalConsole: true` or `console: "internalConsole"` if you wanted `externalConsole: false`
