### ISSUE TITLE
cpptools uses up all memory (or crashes) with certain code

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6940]
@sean-mcmanus, IMHO this issue appears to be C code text format and parser related. You should be able to reproduce the memory and processor resource eat up with a simple test in a header file and taking observations with _top_ sorting by memory (M).
First enter a struct like this in your C header file:

typedef struct quux
{ 
    struct quux *prev;
    struct quux *next; 
    int foo;
} quux_t;

This far _cpptools_ memory should not grow considerably and CPU stays rather idle.
Now delete the new line between the first two struct pointers:

typedef struct quux
{ 
    struct quux *prev;    struct quux *next; 
    int foo;
} quux_t;

Now _top_ shows quickly growing memory figures for _cpptools_ (in my case from a few GB to 24 GB  RES and > 33 GB VIRT) and %CPU hits high scores. 
Eventually the misbehaving _cpptools_ process gets killed and your server connection gets closed, but a newly restarted process repeats the same pattern - OUTPUT tab occasionally printing error (and getting focus).
Closing the header file editor tab or reverting the text to have the struct pointers on separate lines removes the problem, which is seen after the misbehaving _cpptools_ process gets killed (by you or some starvation supervisory). Some other changes in the latter format would cure the sink as well, for example commenting the line with `int foo;` and I have no idea which are the patterns that turn the gates loose.

I do hope that these observations are correct and they would help leading to the root cause.

_Originally posted by @perttiarjanne in https://github.com/microsoft/vscode-cpptools/issues/6035#issuecomment-776203848_

**Comment by sean-mcmanus** [comment]
@perttiarjanne Thanks a lot for finding that repro and reporting it.

**Comment by perttiarjanne** [comment]
@sean-mcmanus, could it be that two or more of a particular type of nodes/references sharing a mutual line entry/number would have been set with or would select to follow a wrong link leading to infinite recursion?

**Comment by sean-mcmanus** [comment]
Yeah, it was something like that. The fix for nested namespaces in the outline view (https://github.com/microsoft/vscode-cpptools/issues/4456 ) didn't handle a particular special case correctly, in part, due to a separate bug with our symbol parser which will interpret "struct quux *prev;" as being a symbol of type quux::quux (https://github.com/microsoft/vscode-cpptools/issues/4383). We'll try to release 1.2.1 with the fix on Wednesday.

**Comment by perttiarjanne** [comment]
Ok - thanks!

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.1
