### ISSUE TITLE
Call stack symbols don't appear correctly occur without a good warning/error message when the "program" doesn't match the selected process

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#6941]
See the screenshot. All the symbols are wrong. I thought debugging was broken until I realized I had the wrong debug configuration selected. It would nice if this could be detected and some warning given. This was with Linux.
![image](https://user-images.githubusercontent.com/19859882/107471118-753da880-6b21-11eb-8da7-2e8d189ba72c.png)

**Comment by WardenGnaw** [comment]
By GDB design we need to provide the program path to help it resolve symbols and you are allowed to attach to any process. 
By having a different program path, it did not resolve any symbols for the process you attached to so it will result in empty call stacks. 

This should be fixed when we have a way to have 1-1 PID and process from the process picker: https://github.com/microsoft/vscode-cpptools/issues/909
