### ISSUE TITLE
Format on Type doesn't trigger on next line (using vcFormat)

### ISSUE THREAD

**Issue by Leopard20** [microsoft/vscode-cpptools#6942]
**Type: LanguageService**

In Visual Studio, when you type something like this:
```cpp
for(auto i=1;i<10;++i){
```
and press Enter to go to the next line, the line automatically formats like this:
```cpp
for (auto i = 1; i < 10; ++i) {
```
Unfortunately, in this VSCode extension, auto formatting only occurs when you type a semicolon `;`, not next line.
I'm using `vcFormat`, not `Clang`

I tested this in JS/TS and it works:
```js
for(let i=1;i<10;++i){
```
so the issue is only with this extension.

If this is because you believe it could be an undesirable feature to some people, you can make it optional.

P.S: This file seems to indicate that auto formatting is indeed supposed to trigger if I use vcFormat:
https://github.com/microsoft/vscode-cpptools/blob/4f4d662541a0d55234630f6ce3a5ff32b882e304/Extension/src/LanguageServer/Providers/onTypeFormattingEditProvider.ts#L52

**Comment by Leopard20** [comment]
This file seems to indicate the formatting is supposed to happen if I use `vcFormat` and press Enter:
https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/Providers/onTypeFormattingEditProvider.ts

**Comment by Colengms** [comment]
Hi @Leopard20 .  Thanks for reporting this.  I can repro, and have a fix in queue for our next release.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.1
