### ISSUE TITLE
Can't use cppvsdgb

### ISSUE THREAD

**Issue by andyleejordan** [microsoft/vscode-cpptools#695]
After upgrading Code, and reinstalling the C++ extensions, I cannot use the Windows C++ any more. My configuration has not changed. I start the debugger, go to the debug output, and see this:

```
--------------------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with Visual Studio
Code, Visual Studio or Xamarin Studio software to help you develop and test your
applications.
--------------------------------------------------------------------------------
```

And it just hangs there.

Snippet from `launch.json`:

```json
{
    "version": "0.2.0",
    "configurations": [
         {
            "name": "stout-tests",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceRoot}/build/3rdparty/stout/tests/Debug/stout-tests.exe",
            "args": [ "--gtest_filter=FsTest.LongPath" ],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false
        },    
```

I see `clrdbg.exe` running, consuming ~15% of my CPU, and the debugger hasn't crashed, it just doesn't move forward. It is _not_ at a breakpoint.

I'm totally blocked from working right now with the debugger being broken. I'll try rolling back VS Code.
![debugger](https://cloud.githubusercontent.com/assets/2226434/25759465/7cd4a828-3187-11e7-9403-2d8f764e9407.PNG)

**Comment by andyleejordan** [comment]
Some version info (sorry for screenshots, none of this text was copyable):

## VS Code

![code_version](https://cloud.githubusercontent.com/assets/2226434/25759536/ccec4546-3187-11e7-9bfb-808a27d5115b.PNG)

## Windows

![windows_version](https://cloud.githubusercontent.com/assets/2226434/25759539/cff278fa-3187-11e7-996f-55b6c8805ef5.PNG)

**Comment by andyleejordan** [comment]
Version 0.11.0 of the C++ extension.

**Comment by andyleejordan** [comment]
Interesting note: under "Add Configuration..." on the `launch.json` file, the `C++ (Windows)` option I originally used to add these is no longer available.

**Comment by andyleejordan** [comment]
Rolling back to Code 1.11.2 didn't help; that said, it doesn't appear to have cleared any caches (i.e. all my extensions are still installed).

**Comment by pieandcakes** [comment]
this is a duplicate of #484. I talked to Andy offline and resolved it.

**Comment by andyleejordan** [comment]
Thank you @pieandcakes!

Summary:

I had also started building with `/debug:fastlink` at the same time I updated (woo, too many variables), and this caused the hang. A current work-around is to replace a certain DLL, per [these steps](https://github.com/Microsoft/vscode-cpptools/issues/484#issuecomment-279583712).
