### ISSUE TITLE
Does not detect mingw, even though terminal detects it.

### ISSUE THREAD

**Issue by Joe23232** [microsoft/vscode-cpptools#6953]
I have followed these steps:

https://code.visualstudio.com/docs/cpp/config-mingw

And I have even restarted the entire computer, still this extension does not detect Mingw. It is added to my systems path and everything. I am able to compile C++ code just fine I don't have to give the full filepath to use `g++`.

This is for Windows 10 by the way. Any idea how to fix this?

**Comment by sean-mcmanus** [comment]
We don't check for Mingw compilers on your path when searching for "known compilers". We only look in some hardcoded default locations. What feature are you trying to use that isn't detecting the mingw compilers? The build task features?

**Comment by Joe23232** [comment]
@sean-mcmanus Apparently on startup (when I start up vscode) on a C++ project, I immediately get errors from the extension:

![image](https://user-images.githubusercontent.com/34926497/107624382-e3fc3c80-6cae-11eb-8211-96a7dc815bc3.png)

**Comment by sean-mcmanus** [comment]
You're hitting a different issue. Your install doesn't appear to be valid. It's not able to launch the cpptools process, which is unrelated to mingw. Can you uninstall/reinstall the extension? `C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-1.2.0\bin\cpptools.exe` is supposed to exist and be executable.

**Comment by Joe23232** [comment]
Yeah I know now the file permission for that folder was screwed, the entire `.vscode`.
