### ISSUE TITLE
C/c++ extension crash on my ssh remote 

### ISSUE THREAD

**Issue by Qiaodan007** [microsoft/vscode-cpptools#6957]
Type: General

**Describe the bug**
- OS and Version: macOS 11.1
- VS Code Version:1.53.2
- C/C++ Extension Version:1.2.0
- Other extensions you installed (and if the issue persists after disabling them): remote-SSH
- A clear and concise description of what the bug is.
After I connect to my ssh remote via VScode, and install the c/c++ extension on that ssh remote. Once I open any of  .c files, the terminal shows:
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
[Error - 2:42:56 PM] Connection to server got closed. Server will not be restarted

also there is a pop window says the language server crash 5 times last three minutes -- c/c++ extension. 

the c/c++ extension works fine on locally, but once I connect to my ssh remote, it shows the issue. 

please help..

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Sounds like the same issue as https://github.com/microsoft/vscode-cpptools/issues/6741 -- can you read my responses in that thread an provide more info? It sounds like our cpptools process may not be executable on your machine or may be crashing.

**Comment by Qiaodan007** [comment]
I have read the post you tagged, and what info you want me to provide?

**Comment by sean-mcmanus** [comment]
Are you able to execute ~/.vscode-server/extensions/ms-vscode.cpptools-1.2.0/bin/cpptools on the remote machine?

When you run file ~/.vscode-server/extensions/ms-vscode.cpptools-1.2.0/bin/cpptools does the output text appear to correctly match the architecture of the OS?

**Comment by Qiaodan007** [comment]
I am not able to execute the file, when I type the cpptools, my remote machine is not giving response, I have to control-c to get out.

**Comment by sean-mcmanus** [comment]
The behavior you're describing is normal, i.e. it sounds like you're able to run it okay. When using VS Code, do you ever see cpptools running successfully? Are you able to get a crash call stack somehow, such as from a core dmp?

**Comment by Qiaodan007** [comment]
few months ago, the extension works fine on my ssh remote machine, and recently have this issue. I don't know how to get a crash call stack..

**Comment by sean-mcmanus** [comment]
Are you able to revert to an older version of the C/C++ extension?

You can get a crash dump if you can attach at debugger to the cpptools process before it crashes (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) or if you can setup a core dumper on your OS...the procedure for doing that is different for different OS's.

**Comment by Qiaodan007** [comment]
I will try to install the older version first, could you give an instruction for change the autoupdate or  C_Cpp.updateChannel settings ? (so I change the settings on my remote machine right?)

**Comment by sean-mcmanus** [comment]
In File->Preferences->Settings, search for autoUpdate (set to false) and updateChannel (which should be Default). The settings are user settings so they should apply to the remote and local machine.

**Comment by c-x-berger** [comment]
I'm having the same issue with an Ubuntu 18.04.5 LTS host. Running `~/.vscode-server/extensions/ms-vscode.cpptools-1.2.2/bin/cpptools` on the host gives:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted
```
... which is the same error I see in VS Code on opening C/C++ files on the remote.

I don't know of any working version for this host, so reverting doesn't seem to be a viable option.

Since the crash occurs instantly after starting the program, attaching a debugger to it after the fact seems a bit out of the question.
