### ISSUE TITLE
expression parsing and analyzing problem with macros

### ISSUE THREAD

**Issue by idoktz** [microsoft/vscode-cpptools#6963]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Xubuntu 20.04
- VS Code Version: 1.53.0
- C/C++ Extension Version: 1.2.0
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
-- workspace: temp.c file
-- bug: IntelliSense and code analyzer wrong parsing
-- code:
```c
#define TEST(x) x

int main TEST((int argc, char **argv)) {
	return 0;
}
```

-- gcc version: 9.3.0

**Steps to reproduce**
1. write the source code above to some tmp.c file and save it.
2. the function symbol is parsed as TEST instead of main, i.e. the symbol in the outline is TEST instead of main (same for symbols search in workspace).

**Expected behavior**
The symbols should be parsed **after** macros expension (just like what the compiler does during the preprocessing stage), and be main instead of TEST.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 2/12/2021, 10:25:07 PM
Version: 1.2.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /tmp/tmp.c ]:
    /tmp/tmp.c
Translation Unit Configurations:
[ /tmp/tmp.c ]:
    Process ID: 17687
    Memory Usage: 16 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=90300
Total Memory Usage: 16 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 102525
Number of files discovered (not excluded): 87396
Number of files parsed: 2771
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/32374393/107819602-1e82d980-6d82-11eb-9f29-5b2403d75bc0.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
This is a "by design" limitation of our symbol parser. The macro needs to be added to a cpp.hint file.

![image](https://user-images.githubusercontent.com/19859882/107823704-0afd5180-6d35-11eb-81bb-39d0fd2abdea.png)
