### ISSUE TITLE
cpptools %cpu 99.7

### ISSUE THREAD

**Issue by durongze** [microsoft/vscode-cpptools#6967]
top - 08:59:28 up 1 day, 18:04,  1 user,  load average: 1.43, 1.55, 2.23
任务: 349 total,   1 running, 348 sleeping,   0 stopped,   0 zombie
%Cpu(s): 12.9 us,  0.2 sy,  0.0 ni, 83.1 id,  0.0 wa,  0.0 hi,  3.8 si,  0.0 st
MiB Mem :   7827.6 total,    621.6 free,   2748.4 used,   4457.5 buff/cache
MiB Swap:   2048.0 total,   1469.9 free,    578.1 used.   4596.3 avail Mem 

 进程号 USER      PR  NI    VIRT    RES    SHR    %CPU  %MEM     TIME+ COMMAND                                          
 132013 du        20   0 2236772 210360   9176 S  99.7   2.6 576:19.94 cpptools

**Comment by durongze** [comment]
当vscode关闭的时候，能不能不要在后台继续运行cpptools ？

**Comment by qutorial** [comment]
+1 here!

**Comment by michelleangela** [comment]
@durongze 
Could you provide the following additional information to help us investigate the issue:

1. Version of C++ extension
2. Version of VS Code
3. OS information
4. Log output from the [language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) when reproducing the issue.
5. Estimated size of project you're working on
6. Performance analysis logs for the C++ extension (see instructions at https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues).

**Comment by michelleangela** [comment]
> +1 here!

@qutorial 
The cause of performance issue may very based on project, machine, versions of extension, etc. Therefore, the initial issue posted here may not be the same as the one you're running into. Could you create a new issue for the performance issue you're experiencing and provide the following information?

Version of C++ extension
Version of VS Code
OS information
Log output from the language server when reproducing the issue.
Estimated size of project you're working on
Performance analysis logs for the C++ extension (see instructions at https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues).

**Comment by zethon** [comment]
+1 here. Have been dealing with this constantly for the past few weeks.

**Comment by michelleangela** [comment]
@zethon 
The cause of performance issue may very based on project, machine, versions of extension, etc. Therefore, the initial issue posted here may not be the same as the one you're running into. Could you create a new issue for the performance issue you're experiencing and provide the following information?

1. Version of C++ extension
2. Version of VS Code
3. OS information
4. Log output from the language server when reproducing the issue.
5. Estimated size of project you're working on
6. Performance analysis logs for the C++ extension (see instructions at https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues).

**Comment by sean-mcmanus** [comment]
In particular, 1.2.1 has some fixes that could address this (does this repro with that?), and https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders has some more fixes (although unrelated to CPU usage as far as we know).

**Comment by zethon** [comment]
I'm on 1.2.1 and am constantly seeing this: 

![image](https://user-images.githubusercontent.com/5203583/108302822-c0d00200-7172-11eb-9990-cae91aafa10b.png)

I will file a separate issue with the requested info.

**Comment by durongze** [comment]
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-65-generic  （Unbuntu 20.04）

忘记当时收集相关信息了。上面是现在的版本信息。问题现在不存在了，等下一次再出现的时候，我再反馈。 感谢你们的付出。
