### ISSUE TITLE
request: pickRemoteProcess enhancements

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-cpptools#6973]
some enhancements to `pickRemoteProcess` for your consideration:
- allow filtering by process name (or potentially other attributes)
- given the above, allow automatic selection when the number of matches is one.

**Comment by WardenGnaw** [comment]
Duplicate: https://github.com/microsoft/vscode-cpptools/issues/909 and https://github.com/microsoft/vscode-cpptools/issues/5967
