### ISSUE TITLE
remembers the last deleted included/browser path configuration 

### ISSUE THREAD

**Issue by 123swk123** [microsoft/vscode-cpptools#698]
recently I created a default single configuration with some include path and browse path and later I removed the physical path.

next I added another configuration with new include path and browse path.
later I selected this new configuration and when I try to open those header files using F12(go to definition)
it points to the deleted previous configuration path and asks me to create the file since its not in existence.

I even deleted the previous configuration and just had only one  configuration with new include paths but still the same error continues.

is there any workaround to resolve this? or am I doing something wrong?

**Comment by sean-mcmanus** [comment]
It's a known bug (we don't delete the symbols when the browse.path changes). The workaround is to delete the .browse.vc.db or rename the databaseFilename. See https://github.com/Microsoft/vscode-cpptools/issues/464

**Comment by 123swk123** [comment]
in my case .browse.vc.db is not even created under .vscode so how can I delete it ?

**Comment by 123swk123** [comment]
found it under app "AppData\Roaming\Code\User\workspaceStorage\" let me try your solution now
