### ISSUE TITLE
Couldn't find a debug adapter descriptor for debug type 'cppdbg'

### ISSUE THREAD

**Issue by kacza78** [microsoft/vscode-cpptools#6980]
Extension version: 1.2.1
VSCode: 1.53.2
OS: Ubuntu 18.04 

Today I started getting this issue when I trying to launch a debug session (F5):
Couldn't find a debug adapter descriptor for debug type 'cppdbg' (extension might have failed to activate). 

There is also no option to select GDB when I removed launch.json

launch.json:
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/out/bin/app",
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}/../test_data/",
            "environment": [
                {
                    "name": "LD_LIBRARY_PATH",
                    "value": "${workspaceRoot}/build/out/lib/"
                }
            ],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]

**Comment by WardenGnaw** [comment]
> Couldn't find a debug adapter descriptor for debug type 'cppdbg' (extension might have failed to activate).

This will occur if the extension failed to install properly. Can you reinstall the extension from the marketplace and ensure that `~/.vscode/extensions/ms.cpptools-*` exists?

**Comment by kacza78** [comment]
Yes, I did reinstall the extension, rebooted my pc etc. 
I can use llvm debugger normally, only GDB is missing. 
Also Intellisense and code navigation fails (but I suppose it is due to the failure)

Just to check, I downgraded to v1.2.0 and it I can debug. 

Right now these two folders exist
ms-vscode.cpptools-1.2.0/
ms-vscode.cpptools-1.2.1/
but I think that when I re-launch vscode the older will be deleted.

**Comment by WardenGnaw** [comment]
It may be in a weird state of updating the extension after downgrading. Do you have the extension.autoUpdate set to false?
See https://code.visualstudio.com/docs/supporting/FAQ#_opt-out-of-extension-updates

@sean-mcmanus Any ideas why the extension might be failing to install on ubuntu after downgrading?

**Comment by kacza78** [comment]
It is trying to update immediately after I downgrade so probably it is not set to false. 
Is there any way to hard-reinstall the extension? 
As I expected, after re-launching the vs code it is back to 1.2.1 and GDB fails to start, then I revert to 1.2.0 and right away I can debug, until next relaunch of vscode

**Comment by sean-mcmanus** [comment]
I don't know.

**Comment by kacza78** [comment]
1.2.2-insiders works fine

**Comment by sean-mcmanus** [comment]
1.2.2-insiders has identical debug bits with 1.2.1. Sounds like there's some installation issue with 1.2.1 maybe.
