### ISSUE TITLE
cpptools consuming a lot of CPU

### ISSUE THREAD

**Issue by zethon** [microsoft/vscode-cpptools#6988]
Per the request [in this issue](https://github.com/microsoft/vscode-cpptools/issues/6967), here is the information requested:

> Version of C++ extension

1.2.1

> Version of VS Code

![image](https://user-images.githubusercontent.com/5203583/108303033-21f7d580-7173-11eb-8a91-a5c7adf9a30d.png)

> OS information

![image](https://user-images.githubusercontent.com/5203583/108303067-363bd280-7173-11eb-9a64-96ce1d299d49.png)

> Log output from the language server when reproducing the issue.

I'm not sure what this is. Can you please provide me with instructions or a link?

> Estimated size of project you're working on

This is a large enterprise project. Approximately 800k lines of code, 10 or so CMake targets (not including unit tests).

> Performance analysis logs for the C++ extension (see instructions at https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues).

![image](https://user-images.githubusercontent.com/5203583/108303705-6637a580-7174-11eb-91d3-2e34e77a86e3.png)

NOTE:

This *feels* like some type of zombie process issue. I've also seen where cpptools continues to run even when I've completely quit out of VSCode.

I've just upgraded to the 1.2.2 insiders edition. I will update this issue tomorrow with an update.

**Comment by sean-mcmanus** [comment]
That call stack appears to be normal workspace folder parsing. You should be able to reduce the amount of parsing by either adding folders to the files.exclude setting or adding folders to the C_Cpp.default.browse.path setting (or the equivalent setting in c_cpp_properties.json) (to replace the default value of ${workspaceFolder} with some subset). You can set C_Cpp.loggingLevel to "Debug" to see what files are being parsed unnecessarily. It doesn't sound like this would be a regression compared to 1.1.3.

**Comment by zethon** [comment]
FWIW, 1.2.2 insider edition has fixed nothing. cpptools is still consuming a ton of memory.

@sean-mcmanus Wouldn't the workspace parsing you mention stop at some point? I can walk away from VSCode, come back an hour later and cpptools is still using 100% CPU. 

What amount of parsing should I change? I don't understand what I should exclude (I've already excluded my build folder).

Also, I've se `C_Cpp.loggingLever` to "Debug" as suggested but where can I see the output?

**Comment by zethon** [comment]
![image](https://user-images.githubusercontent.com/5203583/108357359-555e5280-71bb-11eb-990e-2ffcb8d82413.png)

**Comment by sean-mcmanus** [comment]
Yeah, we didn't make any change with 1.2.2-insiders that would change the behavior described.

You can see the progress of tag parsing via hovering over the database icon (although the percentage shown might not be 100% accurate if there is tag parsing occurring as a result of open files, and also dependent includes can cause the total number of files parse to rise).

![image](https://user-images.githubusercontent.com/19859882/108407705-f1e31d80-71d8-11eb-9234-1978e8ee6e66.png)

It should stop when it reaches 100%.

The tag parsing output is in the C/C++ pane:

![image](https://user-images.githubusercontent.com/19859882/108407595-c95b2380-71d8-11eb-9ed4-c5047e3ed41b.png)

It could be parsing some system directories that you don't need symbols for.

**Comment by zethon** [comment]
I do not see this output. I have set the logging level to `Debug` as suggested:

![image](https://user-images.githubusercontent.com/5203583/108717012-c9b23200-74ea-11eb-8fcc-0acc134ea01e.png)

But I do not see the database icon, nor do see any kind of output.

Yet I continue to see this pretty much non-stop:

![image](https://user-images.githubusercontent.com/5203583/108717112-e5b5d380-74ea-11eb-866f-8f9314d39dc7.png)

**Comment by zethon** [comment]
And just to be thorough, here is another profiler screenshot. 

![image](https://user-images.githubusercontent.com/5203583/108717569-6d9bdd80-74eb-11eb-8b89-b70b2365e3b6.png)

**Comment by zethon** [comment]
I was trying to find a way to reproduce this but I couldn't trigger it manually. Visual Studio Code was running as expected and CPU usage was normal. However after about 30 minutes I heard my fan kick on and sure enough I see this:

![image](https://user-images.githubusercontent.com/5203583/108724540-6d9fdb80-74f3-11eb-955f-8a36d00aaada.png)

One thing to note is that that screenshot was taken after I've already quit out of VSC. I see no evidence that any background process of VSC is still running, just cpptools. Here is the Instruments profiling of this zombie process:

![image](https://user-images.githubusercontent.com/5203583/108724816-c0799300-74f3-11eb-8323-44533bb83a5a.png)

**Comment by sean-mcmanus** [comment]
@zethon Yes, you're hitting the same freeze reported by https://github.com/microsoft/vscode-cpptools/issues/7022 and https://github.com/microsoft/vscode-cpptools/issues/7025. We're working on a fix. I think downgrading to 1.2.1 should be a workaround.

**Comment by sean-mcmanus** [comment]
We have a fix for the 2 known causes of this for our pending 1.2.2 release. If you can isolate the sample code that triggers the infinite loop in the document we could verify that your case is also fixed (or you can verify yourself after we release on Thursday, but if it's not fixed, it'll take us longer to get a fix). We're working on re-writing that code for 1.3 (nested inline namespaces aren't being handled correctly).

**Comment by zethon** [comment]
Is the fix in 1.2.2-insiders2? I haven't noticed the problem today.

**Comment by sean-mcmanus** [comment]
We fixed 1 issue with 1.2.2-insiders2, but that build had at least 2 other cases that could generate infinite loops, but those should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 .

You may notice a bugs with the Outline view and breadcrumbs with nested symbols -- we plan to fix that for 1.3: https://github.com/microsoft/vscode-cpptools/issues/6830
