### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by sridmad** [microsoft/vscode-cpptools#7]
From 白乐航 - User review comment on extension market place page

> > > This is what I have been looking for something lightweight,C++ compiler.Much love~ **support Chinese**,support windows.

**Comment by leaon4** [comment]
How to close this feature?
Actually, the Chinese error tips are not helpful to learn c/c++.

**Comment by michelleangela** [comment]
@leaon4 , the C/C++ extension follows the display language setting of VS Code. If you would like the extension to be in English or some other language, the [VS Code display language](https://code.visualstudio.com/docs/getstarted/locales) must be set to that language.
