### ISSUE TITLE
Completion options at wrong places

### ISSUE THREAD

**Issue by 0x6773** [microsoft/vscode-cpptools#70]
Using `vscode : 1.2.0`
Some time cpptools(or vscode) gives code completion options at wrong places. Like this : 
![animation](https://cloud.githubusercontent.com/assets/7235212/15999475/aa53c042-3163-11e6-9177-a56afb4926dd.gif)
See after `cin >> x;`, if I press `Enter` before `Esc` what happens.

**Comment by sridmad** [comment]
This should be fixed with 0.9.0 version of the extension.
