### ISSUE TITLE
Is there a way not to open a terminal and a shell?

### ISSUE THREAD

**Issue by DavidPeicho** [microsoft/vscode-cpptools#700]
Hi,

I did not find anything about it, but, when debugging, a new terminal is opened. I wanted to know if it is possible, instead of using a new terminal, to use only the output window of the vscode editor ?

**Comment by pieandcakes** [comment]
@DavidPeicho There is an item on the backlog, #35 that we have to do the work. Currently it will output to the external terminal only.
