### ISSUE TITLE
problemMatcher gcc does not show compiling error for related filename

### ISSUE THREAD

**Issue by jumpapex** [microsoft/vscode-cpptools#7001]
**Type: LanguageService**

**Describe the bug**
- OS and Version: CentOS 8.2
- VS Code Version: 1.46.1
- C/C++ Extension Version: 1.0.1
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

A make project for cpp, if the source only include filename, then gcc compiling error will not matched, while it works with absolute path. 

**Steps to reproduce**
directory layout
```
/work
    work.code-workspace
    /proxy
        /.vscode
            tasks.json
        Makefile
        bridge.cpp

```
Makefile content:
```
...
SRCS := bridge.cpp
OBJS = $(addsuffix .o,$(basename ${SRCS}))
...
```

tasks.json content:
```
...
        {
            "label": "build proxy",
            "type": "shell",
            "command": "make",
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
...
```

when run build task, there is errors:
_bridge.cpp: In member function ‘void Bridge::handle_connect_upstream(const std::error_code&)’:
bridge.cpp:527:17: error: ‘hello_msg_’ was not declared in this scope
   setup_str_msg(hello_msg_, upstream_data_, size);_
**there is no hint at "bridge.cpp:527:17"**

if I change **bridge.cpp** to absolute **/path to the file/bridge.cpp** in Makefile，the build error will be:
/path to the file/bridge.cpp: In member function ‘void Bridge::handle_connect_upstream(const std::error_code&)’:
/path to the file/bridge.cpp:527:17: error: ‘hello_msg_’ was not declared in this scope
   setup_str_msg(hello_msg_, upstream_data_, size);_
**this time there will be hint "Open file in editor" on /path to the file/bridge.cpp:527:17**

**Expected behavior**
there will be hint "Open file in editor" on bridge.cpp:527:17 if just use the filename in Makefile.

**Comment by sean-mcmanus** [comment]
What do you mean by "hint"? Can you show a screenshot? I don't see see the hint. Are you able to provide more of the Makefile contents? I added my own, but they might be not be sufficient for reproing what you're seeing.

This sounds like it may be an issue with VS Code and not the gcc problem matcher that we provide.

**Comment by jumpapex** [comment]
more Makefile content:
```
OUTPUT := ../Release/proxy

SRCS := /home/paul/work/proxy/bridge.cpp
OBJS = $(addsuffix .o,$(basename ${SRCS}))

all: $(OUTPUT)

$(OUTPUT): $(OBJS)
	@mkdir -p $(@D)
	$(CXX) -o $@ $^ $(LDFLAGS) -lpthread
clean:
	rm -f *.o ${OUTPUT}
```
sorry, when I say hint, it means a tip window.
when set full path of source file in Makefile, a tip windows "Open file in editor" is shown when mouse cursor is on compiling error msg. when click the tip windows, vscode will open the file and position at the error line.
<img width="879" alt="vscode-with-tip" src="https://user-images.githubusercontent.com/35085456/108582620-6ea80000-736f-11eb-9b5d-d4c8f9655762.PNG">
But when only set filename of source file in Makefile, only a tip windows "Search workspace"  is shown when mouse cursor is on compiling error. Also I expect a tip windows "Open file in editor" in this case.
<img width="619" alt="vscode-without-tip" src="https://user-images.githubusercontent.com/35085456/108582628-736cb400-736f-11eb-862d-78603dbe9be3.PNG">

**Comment by sean-mcmanus** [comment]
That is a VS Code issue: https://github.com/microsoft/vscode/issues . The $gcc problem matcher is just responsible for generating the problems in the Problems tab and not generating links in the terminal window.
