### ISSUE TITLE
Extension periodically freezes whole KDE Plasma 5.21 DE

### ISSUE THREAD

**Issue by higaski** [microsoft/vscode-cpptools#7002]
I have to apologize upfront because the issue I'm going to describe is probably going to be very hard to reproduce and I don't have the slightest clue on which info I should provide, what might be relevant and what not...

Since about a week I'm experiencing strange periodical freezes with my current VSCode installation on two different machines running Garuda Linux with KDE Plasma 5.21 as desktop environment. The freezes are somewhere between 5 to 20s long and only happen with the cpptools extension enabled. After a couple of seconds the freezes suddenly stop and everything goes back to normal. It seems that only the desktop environment is affected since e.g. audio and video output from players or a web browser continue normally. The freezes also seem to happen independently from the current opened project. Checking the CPU load and memory consumption I couldn't find anything unusual. cpptools does neither consume processing power nor a lot of memory.

I've downgraded to version 1.0.0 which so far doesn't seem to produce those freezes. I haven't tried more recent versions yet, but will when I can find the time.

Feel free to suggest anything I can try or post to narrow the issue.

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.15-120-tkg-bmq

/edit
Freeze just happened again, even with version 1.0.0...
Maybe this has something to do with disk access? My networking traffic brakes down completely during those freeze periods:
![network_](https://user-images.githubusercontent.com/13762516/108533878-cbf17200-72d9-11eb-82fa-10719500f80e.png)

**Comment by higaski** [comment]
Recorded Perf data as suggested [here](https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues#macos)

[perf_data.zip](https://github.com/microsoft/vscode-cpptools/files/6011792/perf_data.zip)

**Comment by higaski** [comment]
Now I'm far from a kernel dev, but those *_fault calls look strange to me?

![perf_data](https://user-images.githubusercontent.com/13762516/108540664-c1d37180-72e1-11eb-8912-46623b2a44ab.png)

**Comment by sean-mcmanus** [comment]
Can you try https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders2 ?

What's strange about the *_fault calls? Are you able to expand the profiler UI to get a call stack that shows what work is being performed?

**Comment by higaski** [comment]
I've just tried the 1.2.2-insiders2 build and the issue stays the same.

What's strange though is that the exact same installation (same linux distribution, same extensions, same versions) running on XFCE instead of KDE Plasma does not have those freezes.

The *_fault calls sound like something ain't working as its supposed to be? But again, not an expert on this.

Can you elaborate on what you mean with expand the profiler UI?
Any calls in particular I should expand?

**Comment by sean-mcmanus** [comment]
If you can click the + icons to expand the frames it might show some interesting call stacks. Maybe try expanding the call stacks that appear to be doing the most work? @michelleangela might be more familiar with the profiling tool. I usually just attach a debugger and break.

The machine with ECC RAM might be slower? A 5-10s long freeze might be caused a garbage collector being run. Some OS's GUI might not be able to handle that well?

**Comment by higaski** [comment]
Here is another screenshot of most of the highest-% calls extended.
![cpptools_perf_ext](https://user-images.githubusercontent.com/13762516/108856281-2ea08180-75ea-11eb-9ec0-1d229222b0d9.png)

Seems there is a lot of time spent waiting on a mutex of some kind?

**Comment by sean-mcmanus** [comment]
It's possible that your OS uses some sort of global mutex that our cpptools process is locking and that the UI also needs to lock, blocking the UI. I don't see any of our code in the call stacks though so I can't tell which of our code is locking the mutex. You may want to try setting C_Cpp.intelliSenseCacheSize to 0, which will disable our caching system which uses memory mapped file IO which could potentially be the cause of this issue.

**Comment by higaski** [comment]
Sadly neither disabling the cache nor disabling Intelli Sense Engine (option C_Cpp.intelliSenseEngine) altogether made any difference.

**Comment by sean-mcmanus** [comment]
That means the cpptools-srv is not causing the issue, but cpptools. Do you see any logging in the C/C++ output pane after setting C_Cpp.loggingLevel to "Debug" when the freeze occurs? The cpptools process normally doesn't do any intensive work, other than tag parsing and potentially some other operations that shouldn't be slow except in buggy conditions, which you should see logging for. I assume it still repros with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 ?

**Comment by higaski** [comment]
The debug output consists almost entirely of "tag parsing" messages. Apart from occasional tag parsing errors the output looks like this when it slows down:

`cpptools/fileDeleted: file:///home/vinci/Develop/VSCode/MSxxx/build/_deps/cmsis_5-subbuild/CMakeFiles/3.19.6/CMakeSystem.cmake.tmp
cpptools/fileDeleted: file:///home/vinci/Develop/VSCode/MSxxx/build/_deps/cmsis_5-subbuild/CMakeFiles/cmsis_5-populate.dir/Labels.txt.tmp24af4
Checking for syntax errors: file:///home/vinci/Develop/VSCode/MSxxx/src/sys/sys.cpp
Queueing IntelliSense update for files in translation unit of: /home/vinci/Develop/VSCode/MSxxx/src/sys/sys.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 14
Update IntelliSense time (sec): 0.757
cpptools/getSemanticTokens: file:///home/vinci/Develop/VSCode/MSxxx/src/sys/sys.cpp (id: 982)
cpptools/fileCreated: file:///home/vinci/Develop/VSCode/MSxxx/build/_deps/cmsis_5-subbuild/cmsis_5-populate-prefix/src/cmsis_5-populate-stamp/cmsis_5-populate-mkdir
Checking for syntax errors: file:///home/vinci/Develop/VSCode/MSxxx/src/sys/sys.cpp
Queueing IntelliSense update for files in translation unit of: /home/vinci/Develop/VSCode/MSxxx/src/sys/sys.cpp
cpptools/fileCreated: file:///home/vinci/Develop/VSCode/MSxxx/build/_deps/cmsis_5-subbuild/.ninja_log
Checking for syntax errors: file:///home/vinci/Develop/VSCode/MSxxx/src/sys/sys.cpp
Queueing IntelliSense update for files in translation unit of: /home/vinci/Develop/VSCode/MSxxx/src/sys/sys.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 14
Update IntelliSense time (sec): 0.505
cpptools/getSemanticTokens: file:///home/vinci/Develop/VSCode/MSxxx/src/sys/sys.cpp (id: 983)
Database safe to open`

**Comment by sean-mcmanus** [comment]
Yeah, that parsing will use CPU on one core (I assume you have > 1 core). Does the freezing go away when the parsing finishes? You can add folders to files.exclude to reduce the parsing. The database should usually be retained after the workspace is reloaded.

**Comment by higaski** [comment]
> I assume it still repros with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 ?

For whatever reason, problem seems to be gone with 1.2.2.
I'll report back in a couple of days if it really is.

**Comment by higaski** [comment]
For whatever reason the problem is gone after a kernel update to _5.11.7-zen1-1-zen_

**Comment by sean-mcmanus** [comment]
That's good. Maybe they fixed a bug.
