### ISSUE TITLE
IO installer

### ISSUE THREAD

**Issue by ernestomendoza100** [microsoft/vscode-cpptools#7005]
Issue Type: <b>Bug</b>

The PlatformIO installer seems to crash in the middle of the installation. The progress bar just stop and adter several minutes one get an error saying connection interruption.
System Windows 10, PC

Extension version: 1.2.1
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.97GB free)|
|Process Argv|--crash-reporter-id 86bd562a-a705-4e81-b1a0-7c95bf103f4d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by sean-mcmanus** [comment]
PlatformIO isn't our extension. Are you saying our extension is causing the failure?

https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders2 fixed an issue that could cause the C/C++ extension to fail to activate, which might impact the PlatformIO extension.

**Comment by ernestomendoza100** [comment]
PlatformIO Installer: Installing PlatformIO Core

Hi Sean. This is the extension i am trying to install. It comes directly from the searchable list on visual studio. I have python x64 installed too.  Do this helps?

**Comment by sean-mcmanus** [comment]
I don't know. Maybe try asking at https://github.com/platformio/platformio-vscode-ide/issues ?
