### ISSUE TITLE
How to enable the function definition not found warning

### ISSUE THREAD

**Issue by januwA** [microsoft/vscode-cpptools#7006]
**Describe the bug**
- OS and Version: Windows10
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.1

**Expected behavior**

When I create a "fun.h" header file and declare "void hello();", but now I have not defined this function in the "fun.cpp" file, so I want to receive a warning like this "The definition of the function for'hello' was not found"

Have this function in vs2019, whether to also enable this function in vscode

**Comment by sean-mcmanus** [comment]
That feature hasn't been implemented for VS Code yet.

**Comment by bobbrow** [comment]
I believe that you'll get a hint squiggle for this case when we finish #664.  I don't think we'll add a separate warning for this, but you will get a "lightbulb" code action notification for it when you select the squiggled content.
