### ISSUE TITLE
Error regarding #include

### ISSUE THREAD

**Issue by kambojshalabh35** [microsoft/vscode-cpptools#7007]
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\MyPc\Documents\C++\sum.cpp).C/C++(1696)

include paths are as followed 
{
${workspaceFolder}
C:/MinGW/lib/gcc/mingw32/6.3.0/include
C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++
C:/MinGW/lib/gcc/mingw32/6.3.0/include/c++/mingw32
}

**Comment by rahulaarora** [comment]
**Had the same issue but got solved by** @kambojshalabh35
