### ISSUE TITLE
ISO date string in args unexpectedly get converted to local format when passed to program.

### ISSUE THREAD

**Issue by grapland0** [microsoft/vscode-cpptools#7008]
Type: Debugger
- OS and Version:  NT x64 10.0.19042
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.1
- Other extensions you installed (and if the issue persists after disabling them): CMake and CMake tools, clangd, and devcontainer support.
- A clear and concise description of what the bug is.

ATT. I put items "2020-03-07T07:00:00" in args list, but the program receive a local formatted argv "03/07/2020 07:00:00".

My launch item:
```json
    {
      "name": "(gdb) Debug with SPY download parameter on vr downloader",
      "type": "cppdbg",
      "request": "launch",
      // Resolved by CMake Tools:
      "program": "${command:cmake.launchTargetPath}",
      "args": [
        "--download-profile",
        "booktick",
        "-s",
        "2020-03-07T07:00:00",
      ],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [
        {
          // add the directory where our target was built to the PATHs
          // it gets resolved by CMake Tools:
          "name": "PATH",
          "value": "$PATH:${command:cmake.launchTargetDirectory}"
        }
      ],
      "MIMode": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
```

The major part of the cpp program is just `std::cerr<<argv[4]`, and it prints `03/07/2020 07:00:00`

**Comment by sean-mcmanus** [comment]
What component do you believe is buggy? The debugger? What happens if you run your program via the command line?

**Comment by grapland0** [comment]
I think the bug should be between launch.json processing and the place just before my program run.

If I launch my program from terminal, everything looks good. The arguments get passed as-is.
But when I put the exact arguments in launch.json and launch the program by vscode debugger, the date string arguments gets changed.

**Comment by sean-mcmanus** [comment]
@WardenGnaw This sounds like a bug with cppdbg?
