### ISSUE TITLE
Inconsistent highlighting for '= default' and '= delete'

### ISSUE THREAD

**Issue by BigBahss** [microsoft/vscode-cpptools#7010]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Manjaro Linux 5.10
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.2-insiders2
- Other extensions you installed (and if the issue persists after disabling them): All others disabled
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. With the following code:
```cpp
class Entity
{
public:
    Entity() = default;
    Entity(const Entity &) = default;
    Entity(Entity &&) = delete;
    Entity &operator=(const Entity &) = default;
    Entity &operator=(Entity &&) = delete;
};
```
There is inconsistent highlighting for `= default` and in `= delete` between constructors and assignment operators in Dark+:
![Screenshot_2021-02-21_04-01-25](https://user-images.githubusercontent.com/58710639/108620781-6ba72100-73fc-11eb-9b75-7f38204e7c84.png)
Or Material:
![Screenshot_2021-02-21_04-03-01](https://user-images.githubusercontent.com/58710639/108620785-6e097b00-73fc-11eb-88da-27a5d834352f.png)

**Expected behavior**

I would expect them to be colored the same across constructors and assignment operators. Maybe there's a reason for this distinction that I'm unaware of, but being that there's even more distinct highlighting in Material theme tells me otherwise.

**Comment by csorvagep** [comment]
I created an issue (#5715) few months ago, but it is closed because this is a bug of an external issue. Unfortunately that issue (https://github.com/jeff-hykin/cpp-textmate-grammar/issues/407) is still open.

**Comment by BigBahss** [comment]
Ah, thank you for letting me know. I didn't bother searching closed issues.

**Comment by sean-mcmanus** [comment]
Okay, sounds like I can close this.
