### ISSUE TITLE
Inline Assembly Error

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#7011]
VSCode shows me an error message when I use inline assembly in my code.
Normally there shouldn't be an error because it's valid C code.

![image](https://user-images.githubusercontent.com/64029790/108623570-f8bf9980-743f-11eb-994a-f715aeb59a12.png)

The error of the asm keyword is: "The identifier ""asm"" is not defined." and the error message of the volatile keyword is: "";" was expected". It doesn't affect the compiler but it's pretty annoying.

**Comment by sean-mcmanus** [comment]
This works correctly with gcc/clang on Linux/Mac and mingw on Windows -- what compiler and OS are you using? It sounds like you might be using a windows-msvc-x64 IntelliSense mode (you can check via running the C/C++: Log Diagnostics command).
