### ISSUE TITLE
Can't follow the gdb debugger for a WSL-built Windows program! "Unable to resolve non-existing file"

### ISSUE THREAD

**Issue by twilson90** [microsoft/vscode-cpptools#7013]
- VS Code Version: 1.53.2
- OS Version: Windows 10 64bit

I have a source code repository that I've cross-compiled in WSL into a Windows executable and I need to debug this windows exectuable with gdb in vscode.

The debugger works and stops on breakpoints, and while I can see the stack variables and all that, it can't resolve the linux filepaths on windows which makes debugging a real headache.

![image](https://user-images.githubusercontent.com/5526342/107848084-a996ba80-6de8-11eb-8d16-a8d78cf5e942.png)

So I can't see the executing line in the file by clicking on the call stack frames, and if I open the file manually I can't hover over variables and see their values.

I tried using a sourceFileMap in my launch.json so the paths resolved... but now it doesn't hit any of the breakpoints! I guess they get mapped too :/

I know the sourceFileMap is working because If I run into an exception it'll now resolve the filepath and open the file in the editor.

My only option up to now has been to debug a Linux build in the remote WSL, but now I need to test the Windows build and due to the complexity of the source code I find it difficult to keep track without seeing the line and knowing where I am in the file.

**Comment by WardenGnaw** [comment]
Can you share the console logs?

You can do this by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your launch.json and copy the output from the Debug Console

**Comment by hedgehog90** [comment]
I finally worked out a solution last night.

I added to the setupCommands arg for gdb:
```
{ "text": "set substitute-path /expected/src/path/ C:/actual/src/path/" }
```
