### ISSUE TITLE
Red squiggles under #include <stdio.h> when the workspace is in ~/src but not in /tmp

### ISSUE THREAD

**Issue by ddribin** [microsoft/vscode-cpptools#7014]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Catalina 10.15.7
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.1
- Other extensions you installed (and if the issue persists after disabling them):
  -  CMake Tools Extension: 1.6.0 + CMake: 3.19.5
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

VS Code shows red squiggles under `#include <stdio.h>` in the editor when the workspace is in `~/src` but not when it is in `/tmp`. Both workspaces compile and run the code fine. It's only an error in the editor.

I can reproduce this with a very simple `Hello World` C workspace using CMake and the CMake Tools extension.

**Steps to reproduce**

1. Setup a directory with this structure:

```
% tree hello_world
hello_world
├── CMakeLists.txt
└── main.c
```

<details>
  <summary><code>CMakeLists.txt</code></summary>

```
cmake_minimum_required(VERSION 3.0.0)
project(hello_world VERSION 1.0.0)

add_executable(hello_world main.c)
```
</details>

<details>
  <summary><code>main.c</code></summary>

```
#include <stdio.h>

int main(int argc, char** argv)
{
    printf("hello world\n");
    return 0;
}
```
</details>

[hello_world.tar.gz](https://github.com/microsoft/vscode-cpptools/files/6019783/hello_world.tar.gz)

2. Open the directory as a workspace: `code hello_word/`
3. When CMake asks to configure the project, click "Yes".
4. Open `main.c` in the editor.

**Expected behavior**

The `#include <stdio.h>` should be found.

**Logs**

- Log Diagnostics for `~/src`: [diagnostics-src.txt](https://github.com/microsoft/vscode-cpptools/files/6019788/diagnostics-src.txt)
- Log Diagnostics for `/tmp`: [diagnostics-tmp.txt](https://github.com/microsoft/vscode-cpptools/files/6019789/diagnostics-tmp.txt)
- Language server logs for `~/src`: [language-server-src.txt](https://github.com/microsoft/vscode-cpptools/files/6019790/language-server-src.txt)
- Language server logs for `/tmp`: [language-server-tmp.txt](https://github.com/microsoft/vscode-cpptools/files/6019791/language-server-tmp.txt)

**Screenshots**

<details>
  <summary><strong>Workspace in <code>~/src</code> with red squiggles</strong></summary>

<img width="1136" alt="workspace-src" src="https://user-images.githubusercontent.com/20428/108669028-dc544900-74a1-11eb-8e09-f8e258223f3d.png">
  </summary>
</details>

<details>
  <summary><strong>Workspace in <code>/tmp</code> with no squiggles</strong></summary>

<img width="1136" alt="workspace-tmp" src="https://user-images.githubusercontent.com/20428/108669056-e9713800-74a1-11eb-8775-bfae0821eb9e.png">
  </summary>
</details>

**Additional context**

I understand this is an [FAQ](https://code.visualstudio.com/docs/cpp/faq-cpp#_why-do-i-see-red-squiggles-under-standard-library-types):

> Q: Why do I see red squiggles under Standard Library types?
>
> A: The most common reason for this is missing include paths and defines. The easiest way to fix this on each platform is as follows:
>
> **Linux/Mac**: Set `"intelliSenseMode": "clang-x64"` or `"intelliSenseMode": "gcc-x64"` and `compilerPath` in `c_cpp_properties.json` to the path to your compiler.

I changed only `intelliSenseMode` to `clang-x64` (it was unset), leaving `compilerPath` alone, and that fixed the problem. However it seems like a bug that the source directory causes "missing include paths" or that this mode is not the default.

**Comment by sean-mcmanus** [comment]
Your ~/src case is hitting a sysroot bug we've fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders2 . Can you try that?

**Comment by ddribin** [comment]
Thanks for the quick reply! I tried that and it is indeed fixed. Attaching new diagnostics and language server debug logs:

- [diagnostics-src-insiders.txt](https://github.com/microsoft/vscode-cpptools/files/6029702/diagnostics-src-insiders.txt)
- [language-server-src-insiders.txt](https://github.com/microsoft/vscode-cpptools/files/6029705/language-server-src-insiders.txt)

Diffing `diagnostics-src.txt` and `diagnostics-src-insiders.txt` does show the proper include directory now:

```diff
     Compiler Path: /usr/bin/clang
     Includes:
         /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include
+        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
         /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
+    Frameworks:
+        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
     Standard Version: c11
```

So, yes, this looks to be fixed in the upcoming 1.2.2. Thanks again!

I am curious though... why does the `~/src` case include a `Custom configuration:` in the "Log Diagnostics" but `/tmp` does not:

```
Custom configurations:
[ /Users/dave/src/hello_world/main.c ]
{
    "defines": [],
    "standard": "c11",
    "includePath": [],
    "intelliSenseMode": "clang-x64",
    "compilerPath": "/usr/bin/clang",
    "compilerArgs": [
        "-g",
        "-isysroot",
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk",
        "-mmacosx-version-min=10.15"
    ]
}
```

**Comment by bobbrow** [comment]
linking to #6992 (the duplicate issue)

**Comment by sean-mcmanus** [comment]
I believe using the customConfiguration is the normal behavior when a CMakeLists.txt is found, but for the /tmp case is hitting some issue in which the CMake Tools extensions isn't sending us custom configuration (i.e. "Custom configurations received:" in your logging). @Colengms Any other thought? Looks like a CMake Tools issue. Maybe due to some permissions issue under /tmp versus ~.
