### ISSUE TITLE
mingw breakpoints infinitely tries to bind 

### ISSUE THREAD

**Issue by elemich** [microsoft/vscode-cpptools#7015]
with mingw64  (xst86_64-win32-seh-rev0) there is a strange behaviour: all breakpoints works only if setted before debugging,
and all is configured properly...
can you try to solve this?

**Comment by WardenGnaw** [comment]
Can you share the different consoleLogs per each scenario?

You can do this by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json` and copy the output from the Debug Console
