### ISSUE TITLE
Placement New Calls Misrecogenized by cpptools

### ISSUE THREAD

**Issue by DCZYewen** [microsoft/vscode-cpptools#7016]
**Type: LanguageService**

    SnowFlake(t) {
        int t = 0;
    };
    SnowFlake() {
        new (this) SnowFlake(0);
    };

**Describe the bug**
- OS and Version: Windows 10 2019 LTSC
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.1
- Other extensions you installed (and if the issue persists after disabling them): Python, GitLens
- Does this issue involve using SSH remotely to run the extension on a remote machine?:  Yes
- There is a significant need for "placement new" when calling another constructor in a constructor. In my case, there is a SnowFlake class, a constructor SnowFlake() calling constructor SnowFlake(int t1. int t2). Calling SnowFlake(int t1, int t2) in the default constructor will make cpptools raise "没有与参数列表匹配的重载 "operator new" 实例 -- 参数类型为:  (unsigned long, SnowFlake *)C/C++(384)". I don't have a console running the English version of cpptools, so I can't provide an English version of the error.

**Steps to reproduce**

As above.

**Expected behavior**

As above.

<details>
  <summary><strong>Logs</strong></summary>

```
g++  .\driver.cpp -o .\lightlog.exe -std=c++11
//gcc version9 tdm-gcc will produce no errors.
```
</details>

**Screenshots**

![Screenshot 2021-02-22 184156](https://user-images.githubusercontent.com/50488784/108697533-f2174c00-753d-11eb-8e1b-b578cbe8d36b.png)
**Additional context**

**Comment by sean-mcmanus** [comment]
I'm getting errors with gcc.

Do you repro the issue with code
```
class SnowFlake
{
public:
    SnowFlake(int a, int b) {}
    SnowFlake() {
        new (this) SnowFlake(0, 0);
    }
};
```

**Comment by DCZYewen** [comment]
Thank you for all these efforts you put here.
This is the screenshot, it seem that you did not include <new> header, this overload of new is provided not out of the box.
[cid:image003.png@01D709F0.8907A6A0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by DCZYewen** [comment]
It seemed that outlook images are not capable of github. Let me paste it here.
![t](https://user-images.githubusercontent.com/50488784/108820764-9f01cf80-75f7-11eb-80f4-a111d3d2a7c9.png)

**Comment by sean-mcmanus** [comment]
I repro the issue. The underlying cause is handling of size_t on Windows for clang
```
namespace std
{
  typedef __SIZE_TYPE__ 	size_t;
}

inline void* operator new(std::size_t, void* __p)
{ return __p; }
```

**Comment by sean-mcmanus** [comment]
The fix didn't make our pending 1.2.2, but it should make it to our next 1.3 release.

**Comment by DCZYewen** [comment]
Thanks for your great effort.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders .

**Comment by DCZYewen** [comment]
It's very nice of you.
________________________________
发件人: Sean McManus ***@***.***>
发送时间: 2021年3月20日 4:08
收件人: microsoft/vscode-cpptools ***@***.***>
抄送: DCZ_Yewen ***@***.***>; State change ***@***.***>
主题: Re: [microsoft/vscode-cpptools] Placement New Calls Misrecogenized by cpptools (#7016)


Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders .

―
