### ISSUE TITLE
Occasional incorrect formatting with successive preprocessor directives

### ISSUE THREAD

**Issue by Vultraz** [microsoft/vscode-cpptools#702]
As you can see in the screenshot below, certain successive preprocessor directives aren't formatted correctly (specifically, the `# ifdef INADDR_ANY` line), resulting in erroneous highlighting of the final closure. Adding a new line after `# define BOOST_ASIO_DISABLE_IOCP` fixes the formatting.

EDIT: it only seems to happen with `#define`. `#pragma` doesn't trigger the issue. I'm guessing the formatting rule always looks for a new line after a macro definition or something?

EDIT 2: seems `#define` also results in incorrect formatting for a forward inclusion in the immediate next line.

![bad preprocessor formatting](https://cloud.githubusercontent.com/assets/3558659/25840833/2d5ea04a-34e9-11e7-8724-eb8d1ed872a9.PNG)

**Comment by sean-mcmanus** [comment]
The root cause is https://github.com/Microsoft/vscode-textmate/issues/40 . Someone needs to fix that. It's been broken for a couple months or so. Not sure what the plan is.
