### ISSUE TITLE
Extension overriding cpp standard settings for VS2010 compiler

### ISSUE THREAD

**Issue by selassje** [microsoft/vscode-cpptools#7020]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win 10 
- VS Code Version: 1.53.2
- C/C++ Extension Version: .2.2-insiders2:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

When setting compiler to VS2010, the extensions sets the standard to c++14 :

[22/02/2021, 15:16:21] For C++ source files, the cppStandard was changed from "c++11" to "c++14" based on compiler args and querying compilerPath: "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\cl.exe"

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @selassje .  Thanks for reporting this.  Recent versions of cl.exe only go back to C++14.  We will need to detect the version of cl.exe in order to correctly associate standard versions.  https://github.com/microsoft/vscode-cpptools/issues/5127 is a similar issue.

**Comment by bobbrow** [comment]
We'll track this with #5127
