### ISSUE TITLE
Default detection failure should not cause a compiler to become non-queryable

### ISSUE THREAD

**Issue by Namarius** [microsoft/vscode-cpptools#7021]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.53.2
- C/C++ Extension Version: >=1.2.0
- Other extensions you installed (and if the issue persists after disabling them): Not Tested
- Does this issue involve using SSH remote to run the extension on a remote machine?: No

I'm using cpptools in combination with a modified clang compiler from ARM Keil named armclang.
armclang needs a target to function properly.
Without it it simply presents you this error message:
`armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi`
In order to get the standard values of armclang cpptools needs to call the following:
```
armclang.exe --target=arm-arm-none-eabi -x c -E -dm nul
armclang.exe --target=arm-arm-none-eabi -x c++ -E -dm nul
armclang.exe --target=arm-arm-none-eabi -dumpmachine
```
For some reason cpptools tries to do all these calls without the target information even if compilerArgs are present.
In older versions before 1.2.0 cpptools seems to try out some more specific commands in which compilerArgs are used like this:
```
armclang.exe --target=arm-arm-none-eabi -std=c99 -Wp,-v -E -dD -x c   nul
armclang.exe --target=arm-arm-none-eabi -std=c++17 -Wp,-v -E -dD -x c++   nul
```
Newer versions >=1.2.0 just give up and ignore compilerArgs completely

**Steps to reproduce**
- Setup a configuration with compilerPath and compilerArgs set.
- Look at the debug output of cpptools
- Search for standard value detection and look at the called command

**Expected behavior**
compilerArgs shouldn't be ignored or an alternative configuration for standard value detection

**Additional context**

Used configuration file:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "C:/Keil_v5/5.33/ARM/ARMCLANG/include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/ARM/CMSIS/5.5.1/CMSIS/Core/Include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/ARM/CMSIS/5.5.1/CMSIS/DSP/Include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/ARM/CMSIS/5.5.1/CMSIS/Driver/Include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/ARM/CMSIS/5.5.1/CMSIS/RTOS2/Include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/ARM/CMSIS/5.5.1/CMSIS/RTOS2/RTX/Include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/Keil/ARM_Compiler/1.6.1/Include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/Keil/MDK-Middleware/7.8.0/FileSystem/Include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/Keil/MDK-Middleware/7.8.0/Network/Include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/Keil/STM32F4xx_DFP/2.13.0/Drivers/CMSIS/Device/ST/STM32F4xx/Include",
                "C:/Users/lehmkuehler/AppData/Local/Arm/Packs/Keil/STM32F4xx_DFP/2.13.0/Drivers/STM32F4xx_HAL_Driver/Inc",
                "${workspaceFolder}",
                "${workspaceFolder}/RTE/_debug_20",
                "${workspaceFolder}/includes",
                "${workspaceFolder}/RTE/Device/STM32F429BITx",
                "${workspaceFolder}/Cube/Clock_Template/Inc",
                "${workspaceFolder}/Jansson/src",
                "${workspaceFolder}/libpng/libpng-1.6.30",
                "${workspaceFolder}/fmt/include"
            ],
            "defines": [
                "__UVISION_VERSION=\"532\"",
                "_RTE_",
                "STM32F429xx",
                "HSE_VALUE=\"50000000\"",
                "DATA_IN_ExtSDRAM",
                "RTE_CMSIS_RTOS_RTX",
                "ARM_MATH_CM0",
                "VECT_TAB_OFFSET=\"0x20000\"",
                "_ARM_LIBCPP_EXTERNAL_THREADS",
                "VIEW_RANGE_20"
            ],
            "compilerPath": "C:\\Keil_v5\\5.33\\ARM\\ARMCLANG\\bin\\armclang.exe",
            "compilerArgs": ["--target=arm-arm-none-eabi"],
            "cStandard": "c99",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-arm"
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @Namarius .  The command lines you are referring to are trying to determine the default target and default standard version.  We will use the results of these if/when cStandard/cppStandard or target architecture (IntelliSenseMode) are not explicitly provided.  It's currently by-design that user-provided compiler args are not used.

The issue here is that we consider a compiler to be non-queryable if we can't  get a default standard version from it.  We see a similar issue with arm-poky-linux-musleabi-gcc, which requires -sysroot .  I'll use this issue to track ignoring these failures and falling back to hard-coded defaults, and not considering the compiler to be non-queryable.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 .
