### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kumarp149** [microsoft/vscode-cpptools#7028]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.2.2-insiders2`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cpptools/files/6026948/ms-vscode.cpptools-unresponsive.cpuprofile.txt)
 from your *home*-directory:
:warning:`c:\Users\*******\AppData\Local\Temp\ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by michelleangela** [comment]
@kumarp149 
Could you provide performance analysis logs by following the instructions at https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load?

Also, do you have repro steps and sample code we could use to reproduce the issue?

**Comment by sean-mcmanus** [comment]
The cpuprofile.txt shows it has something to do with completion, but I don't know what...I don't see any call stack with our code. Maybe there could just be a lot of results? I think we have 10k limit.
