### ISSUE TITLE
Support multiple compile commands files per project

### ISSUE THREAD

**Issue by stertingen** [microsoft/vscode-cpptools#7029]
**Type: LanguageService**

This is a feature request.

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.53.2
- C/C++ Extension Version: v1.2.1
- Other extensions you installed (and if the issue persists after disabling them): ROS (ms-iot.vscode-ros), disabling makes no difference.
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Some ROS build systems (catkin_tools, catkin_make_isolated) run CMake separately in different repositories. Thus, passing `CMAKE_EXPORT_COMPILE_COMMANDS=ON` generates n files for n projects. Merging the files manually is cumbersome, so the ideal solution would be the possibility to specify multiple compile commands files and/or support wildcards in the config.

**Expected behavior**

This configuration to be valid and all compilation databases merged:
```json
{
    "configurations": [
        {
            "compileCommands": [
              "${workspaceFolder}/build/foo_pkg/compile_commands.json",
              "${workspaceFolder}/build/bare_pkg/compile_commands.json",
              "${workspaceFolder}/build/**/compile_commands.json",
            ]
        }
    ],
}
```

**Comment by Colengms** [comment]
Hi @stertingen .  Thanks for taking the time to suggest this.

Since the project is using CMake, have you considered using the CMake Tools extension?  CMake Tools provides configurations to the C/C++ Extension, and should properly handle the full hierarchy of projects from a single top-level `CMakeFiles.txt`.

**Comment by stertingen** [comment]
> Hi @stertingen . Thanks for taking the time to suggest this.
> 
> Since the project is using CMake, have you considered using the CMake Tools extension? CMake Tools provides configurations to the C/C++ Extension, and should properly handle the full hierarchy of projects from a single top-level `CMakeFiles.txt`.

There exists a single top-level `CMakeLists.txt` for catkin_make, but not for the tools I mentioned (catkin_tools & catkin_make_isolated). The point of catkin_make_isolated is avoiding side-effects during the build of packages due to global CMake variables. A single top-level `CMakeLists.txt` would break that isolation.

**Comment by Colengms** [comment]
@stertingen With CMake Tools, it's possible to specify an arbitrary CMakeLists.txt location, using `cmake.sourceDirectory`.  Since it sounds like you're not using CMake Tools to build, you could use CMake Tools just to provide configurations to the C/C++ Extension, by pointing it to a CMakeList.txt that includes all of the other project directories.

**Comment by stertingen** [comment]
> @stertingen With CMake Tools, it's possible to specify an arbitrary CMakeLists.txt location, using `cmake.sourceDirectory`. Since it sounds like you're not using CMake Tools to build, you could use CMake Tools just to provide configurations to the C/C++ Extension, by pointing it to a CMakeList.txt that includes all of the other project directories.

You mean, using `add_subdirectory()`? This solution sounds rather hacky to me, I think, I stick to this one: https://github.com/catkin/catkin_tools/issues/551#issuecomment-732989966

**Comment by kjeremy** [comment]
@Colengms I don't think that would work for ROS since the top-level CMakeLists.txt is autogenerated. What I really want is glob support:
```json
"compileCommands": "${workspaceFolder}/build/**/compile_commands.json"
```

**Comment by visstro** [comment]
As an alternative, there is also [clangd plugin](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) which supports multiple configs files per directory, but also regex on paths.

Example `.clangd` config file:
```
Diagnostics:
    UnusedIncludes: Strict

---

If:
    PathExclude: .*/tests/.*
CompileFlags:
    CompilationDatabase: build/production/

---

If:
    PathMatch: .*/tests/.*
CompileFlags:
    CompilationDatabase: build/testing/
```

**Comment by MichaelVoelkel** [comment]
I would also love this feature. Well, actually I have a multiple-project-workspace and would like to have one per project. Each project generates its own compile_commands.json (naturally), so each should optimally have its own file. But I would also be fine to just have one for all.

**Comment by sla89** [comment]
This may also needs adaption of `C_Cpp.default.compileCommands` which is currently just a string but should be an array to also support multiple file in a workspace.

The workaround of @visstro currently works! Thanks.
