### ISSUE TITLE
Remote debugging

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#703]
I'm currently trying to debug a program on a remote machine through VSCode with this extension, but I encounter some problems.
First this is my launch script:

> {
  "version": "0.2.0",
  "configurations": [
    {
      "name": "C++ remote launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceRoot}/software/Lgdn001Demonstrator",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${workspaceRoot}/software/src",
      "MIMode": "gdb",
      "miDebuggerPath": "gdb",
      "setupCommands": [
        {"text": "target remote 10.1.38.10:8080"}
      ],      
      "externalConsole": false
    }
  ]
}

Before to launch the remote debugging, I launch the gdbserver on the remote machine to listen on port 8080. After that when I launch the remote debugging, the connection is established and I get that from gdbserver: 
> Process Lgdn001Demonstrator created; pid = 2157
Listening on port 8080
Remote debugging from host 10.1.38.22
....some messages....
Child exited with status 0
GDBserver exiting

and get that from gdb: 
> =thread-group-added,id="i1"
GNU gdb (Ubuntu 7.11.90.20161005-0ubuntu1) 7.11.90.20161005-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Reading /lib64/ld-linux-x86-64.so.2 from remote target...
=library-unloaded,id="/lib64/ld-linux-x86-64.so.2",target-name="/lib64/ld-linux-x86-64.so.2",host-name="target:/lib64/ld-linux-x86-64.so.2",thread-group="i1"
Reading /lib64/ld-linux-x86-64.so.2 from remote target...
Reading /lib64/ld-linux-x86-64.so.2 from remote target...
Reading /lib64/ld-2.12.so.debug from remote target...
Reading /lib64/.debug/ld-2.12.so.debug from remote target...
Loaded 'target:/lib64/ld-linux-x86-64.so.2'. Symbols loaded.
Stopped due to shared library event (no libraries added or removed)
[Inferior 1 (process 2161) exited normally]
The program '/home/jeremy/Algodone/Demonstrateur/Sources/lgdn001_demonstrator/software/Lgdn001Demonstrator' has exited with code 0 (0x00000000).

There are few issues there:
- First, the remote application does not stop at the entry of the program
- Then the remote program ignores all my breakpoints
- Additionally an external console is launch, even if I configure to not open it in the configuration file
- To finish, I find weird to specify a program option, because this program shouldn't exist on the local machine. The trick, here, is I made a copy of the program on my local machine to be able to launch the remote debugging

**Comment by kanflo** [comment]
Hi @Tankypon. See #328, tr setting a breakpoint at main(...) in the IDE before you launch.

**Comment by pieandcakes** [comment]
@Tankypon You're missing the `"miDebuggerServerAddress": 10.1.38.10:8080` in your `launch.json`. Try that also in your `launch.json`. 

From [launch.json](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md) documentation:

> miDebuggerServerAddress: Network address of the debugger server (e.g. gdbserver) to connect to for remote debugging (example:  localhost:1234 ).

Let me know if changing that works or set a breakpoint in your code.

>•Additionally an external console is launch, even if I configure to not open it in the configuration file

We redirect stdin and stdout for gdb locally and that requires a terminal to launch. We have a workitem to try and fix this.

>•To finish, I find weird to specify a program option, because this program shouldn't exist on the local machine. The trick, here, is I made a copy of the program on my local machine to be able to launch the remote debugging

If you don't want to do that, you can look at using [pipeTransport](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md) which uses `ssh` to talk to the remote gdb and then all you need locally is your source code. The requirement of the program locally is because the local gdb needs to be able to load symbols.

**Comment by ghost** [comment]
Thank you both for your answers. I just tried but I didn't work.
This is my new configuration:
>     {
      "name": "C++ remote launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceRoot}/software/Lgdn001Demonstrator",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${workspaceRoot}/software/src",
      "miDebuggerPath": "gdb",
      "miDebuggerServerAddress": "10.1.38.10:8080",
      "externalConsole": false
    }

The connection is established to the GDBServer:
> Process Lgdn001Demonstrator created; pid = 2898
Listening on port 8080
Remote debugging from host 10.1.38.22
...some messages...
Child exited with status 0
GDBserver exiting

But the debugger didn't stop at the breakpoint set in the main function. The breakpoint has been set before the execution of the debugging. And I set multiple breakpoints just to be sure.

**Comment by pieandcakes** [comment]
@Tankypon can you confirm your program was compiled with the -g flag to include symbols? Without that, the debugger doesn't know where to stop.

**Comment by ghost** [comment]
I enabled the -g flag. I even enabled the flag -g3 in the makefile

**Comment by ghost** [comment]
Seems to be fixed now. I'm able to connect to the remote GDB server, but I have modified nothing from my config. So maybe there is a fix from you I don't know. But great that it's working now!

**Comment by pieandcakes** [comment]
@Tankypon Reading back I don't think we changed anything in this scenario but i'm glad its working for you.
