### ISSUE TITLE
Extension stops responding after a while

### ISSUE THREAD

**Issue by roblunx** [microsoft/vscode-cpptools#7032]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Catalina
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.1
- Other extensions you installed (and if the issue persists after disabling them): none
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc): I'm working on a small project (1 file of ~1000 lines) which uses [ImGui](https://github.com/ocornut/imgui), [ImNodes](https://github.com/rokups/ImNodes) and [Lua](http://www.lua.org). After about an hour working on the code from a clean start of VS Code the extension stops responding. Hovering words only shows `Loading...`, IntelliSense coloring does not work, code completion does not work etc. I don't know if there is a single specific thing I do (like triggering a specific functionality) that causes this or if there are multiple state changes that eventually lead to the extension not responding. 

**Steps to reproduce**
As described above I'm not sure exactly what triggers this, but it is reproducible in the sense that it happens again and again efter restarting VS Code.

**Expected behavior**
The extension to continue being responsive.

<details>
  <summary><strong>Logs</strong></summary>

```
[c_cpp_debug_log.txt](https://github.com/microsoft/vscode-cpptools/files/6028814/c_cpp_debug_log.txt)
```
</details>

**Screenshots**

**Additional context**

Stack trace samples taken with Activity Monitor:
[cpptools-stacktrace.txt](https://github.com/microsoft/vscode-cpptools/files/6028828/cpptools-stacktrace.txt)
[cpptools-srv-stacktrace.txt](https://github.com/microsoft/vscode-cpptools/files/6028832/cpptools-srv-stacktrace.txt)

Also, restarting VS Code does not terminate cpptools and cpptools-srv. After a while there are a bunch of those processes still hanging around. I can't seem to kill them either, maybe because they are hardened (cpptools and cpptools-srv processes missing `get-task-allow` policy). That also prevents attaching lldb to debug.

**Comment by michelleangela** [comment]
@roblunx 
Could you try the latest insiders version https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2-insiders2? It has fixes for issues on random communication failure of the language server on macOS. Could you see if this version resolves the issue for you?

**Comment by roblunx** [comment]
Ok, running that version now. Let's see if that works.

**Comment by sean-mcmanus** [comment]
Can you try https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 now? We fixed a few more issues that could cause non-responsiveness.

**Comment by roblunx** [comment]
So far, version `1.2.2-insider2` have been working without any problem. I’ll switch to `1.2.2` and see if it continues to work reliably.

**Comment by roblunx** [comment]
Now I've been using version `1.2.2` for a couple of days and it still responds. A bit slow sometimes, but eventually it figures it out. For my part you can close this issue now. Thank you!

**Comment by sean-mcmanus** [comment]
Yes, our telemetry and other user feedback shows that the reliability is equivalent to what it was in 1.1.3 (1.2.0/1.2.1) issues got resolved).
