### ISSUE TITLE
No documentation displayed when function declaration is not right after its doc comments

### ISSUE THREAD

**Issue by dearoneesama** [microsoft/vscode-cpptools#7033]
**Type: LanguageService**

**Describe the bug**
- OS and Version: MacOS Catalina 10.15.7
- VS Code Version: 1.54.0-insider
- C/C++ Extension Version: 1.2.2-insiders2
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: both
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
If there is a macro identifier between the comments and the function, then documentation is not displayed when hovering on it.

**Steps to reproduce**

Have a function declaration like this:
<img width="548" alt="Screen Shot 2021-02-23 at 2 10 28 PM" src="https://user-images.githubusercontent.com/57923352/108895703-ef6e3280-75e1-11eb-8841-56ba6c3012f2.png">
where there is a macro `EVENT2_EXPORT_SYMBOL` that expands to nothing, then when you hover on it, the doc is not showed:
<img width="365" alt="Screen Shot 2021-02-23 at 2 10 56 PM" src="https://user-images.githubusercontent.com/57923352/108895857-1cbae080-75e2-11eb-8359-c3dedbd6371e.png">
Either removing the macro or putting it on the same line as the function declaration will make the docs appear.

c_cpp_properties.json is empty.

**Expected behavior**

There should be docs displayed like this:
<img width="395" alt="Screen Shot 2021-02-23 at 2 21 48 PM" src="https://user-images.githubusercontent.com/57923352/108896137-83d89500-75e2-11eb-9f06-b08e82c2e8f1.png">

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by michelleangela** [comment]
This by design. The documentation comment is only applied to the function on the next line.

**Comment by dearoneesama** [comment]
Why close it in a rush...
This might be a good feature to have because it's sad if the vscode extension does not support a coding style. And the screenshot comes from [libevent](https://github.com/libevent/libevent), which is rather a popular library.

**Comment by sean-mcmanus** [comment]
I think this is "by design" due to the nature of our implementation. You can workaround it via adding a cpp.hint file to your workspace with contents such as
```
#define EVENT2_EXPORT_SYMBOL void
```

In other situations "void" might be replaced by something more appropriate.

![image](https://user-images.githubusercontent.com/19859882/109240631-ac03f780-778c-11eb-8874-318a877d81da.png)

**Comment by sean-mcmanus** [comment]
@michelleangela The doc comments work with declarations spread across multiple lines as long as no lines expand to a blank macro, which is why defining the macro in cpp.hint is a workaround for the issue.
