### ISSUE TITLE
Support Apple Silicon ARM64 architecture natively for debugger

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7035]
Type: Debugger

This feature request is to have debugger binaries to run natively on Apple Silicon ARM64.

The feature request to have the language server binaries to run natively on Apple Silicon ARM64 is tracked by 
https://github.com/microsoft/vscode-cpptools/issues/6595

**Note:** the cpptools, cpptools-srv, and debugger binaries built for macOS x64 may work on Apple Silicon's x64 emulator, however this may use more resources than having binaries run natively as ARM64 on Apple Silicon.

**Comment by XIAZY** [comment]
Just some extra info here. VSCode (stable channel) has been released for ARM64-based Macs. Attempting to start debuggers on ARM64 Macs with `"targetArchitecture": "arm64"` will yield this error:
```
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (attach failed ((os/kern) invalid argument))
```

**Comment by Lihp8270** [comment]
I'm also experiencing the same issue on the latest update on VSCode running natively on M1.

**Comment by michelleangela** [comment]
@Lihp8270 
The feature to support native debugging on Apple Silicon ARM64 has not been done yet. You can run the current debugger binaries built for Apple Intel x64 using the Rosetta emulator. Note that the debugger for Apple Intel x64 can only debug x86_64 binaries.

**Comment by jmarti44** [comment]
Any updates on this. I've been having issues running the debugger the debugger for C++

**Comment by benjirer** [comment]
Does anyone know if this has been fixed? Quite new to vs code, would you recommend downloading the intel version and running through rosetta to use the debugger?

**Comment by cloph** [comment]
> Does anyone know if this has been fixed? Quite new to vs code, would you recommend downloading the intel version and running through rosetta to use the debugger?

No, get the M1 version of Visual Studio Code - but the application you want to debug needs to be built for x86_64 and will be run via Rosetta.

**Comment by benjirer** [comment]
Thanks for the hint! Building using Clang x86_64-apple-darwin and then debugging yields the same error. I think I'm way in over my head here, do I need to change anything else?

**Comment by nicudo** [comment]
You need both the executable and the debugger to target x86_64.
I have: "targetArchitecture": "x86_64" in launch.json and "-DCMAKE_OSX_ARCHITECTURES=x86_64" in my build command (use --target=x86-64 if you just use clang).

**Comment by kinkard** [comment]
@benjirer As alternative, you may try another debug extension for C++ - https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb which is able to debug native M1 binaries.

To switch to CodeLLDB debug extension you need to [update your launch.json and set `"type": "lldb"`](https://github.com/vadimcn/vscode-lldb#quick-start) and all should work fine.

**Comment by stelatoris** [comment]
> You need both the executable and the debugger to target x86_64.
> I have: "targetArchitecture": "x86_64" in launch.json and "-DCMAKE_OSX_ARCHITECTURES=x86_64" in my build command (use --target=x86-64 if you just use clang).

I'm new to all of this so bare with me please. When you say place -DCMAKE_OSX_ARCHITECTURES=x86_64 in your build command? What do you mean by build command? Is it the tasks.json? More info would be greatly appreciated.

I just migrated from Windows to Mac, but getting an IDE for C++ has proven to be a headache, now I'm contemplating going back to VS Community on Windows.

**Comment by FLovison** [comment]
> I just migrated from Windows to Mac, but getting an IDE for C++ has proven to be a headache, now I'm contemplating going back to VS Community on Windows.

Currently the best C++ IDE on a Mac with M1 is Xcode of Apple, while wait vscode ...

**Comment by jsm174** [comment]
@stelatoris, I have a normal library and test executable. When I started using my M1, I could not debug it unless I specified for cmake to only build the x86_x64 version. To do that, go into Settings -> Cmake: Configure Args:

![Screen Shot 2021-05-24 at 5 12 27 PM](https://user-images.githubusercontent.com/1197137/119408128-3805bc80-bcb3-11eb-9623-733939168fdd.png)

Otherwise, it builds one binary with x86_x64 and arm_x64 slices, and the debugger will try to run the arm_x64 slice.

**Comment by stelatoris** [comment]
> > I just migrated from Windows to Mac, but getting an IDE for C++ has proven to be a headache, now I'm contemplating going back to VS Community on Windows.
> 
> Currently the best C++ IDE on a Mac with M1 is Xcode of Apple, while wait vscode ...

I tried Xcode, but it does not seem to highlight anything for C++ syntax like Intelisense or VS Community. Do I need to install some plugins? I'm new to programming, for about 5 months now. So I'm not building anything heavy, just simple multi file programs while I go through Stroustrups PPP book.

What about CLion? The demo I tried seems to be close enough to VS Community feel.

**Comment by ilia-glushchenko** [comment]
I use CLion, there are even vs code windows hotkeys available, which makes using it a lot easier. Debugger experience is more or less dissent.

**Comment by theBeginner86** [comment]
@stelatoris,
I would suggest you to use CodeLLDB debugger (vadimcn.vscode-lldb). It's an extension in VSCode and works exactly as the native debugger in VSCode. For its setup you just need to add the configuration provided by the extension in your launch.js file. That should do the trick.

**Comment by FLovison** [comment]
> I tried Xcode, but it does not seem to highlight anything for C++ syntax like Intelisense or VS Community. Do I need to install some plugins? ...

You have to create a _Command Line Tool_ project and so add C or C++ files: intellisense is ok with this project type and C++ files ...

**Comment by sh-cho** [comment]
+1

**Comment by KishenSharma6** [comment]
Has this been resolved or is  kinkard's workaround still the best option? Still unable to debug C++ natively on VSC w/ an m1 Mac

**Comment by sean-mcmanus** [comment]
@KishenSharma6 It's not resolved. If you enable x64 emulation in your OS you could run the x64 version of the debugger or use the other workaround.

**Comment by jesusdeveloper** [comment]
+1 please :) It will be great to debugging with visual studio code and ARM64 / M1 :)

**Comment by kinkard** [comment]
@jesusdeveloper You can use CodeLLDB extension as I described earlier in https://github.com/microsoft/vscode-cpptools/issues/7035#issuecomment-841614784 for debugging with vscode on arm64/m1

**Comment by kinkard** [comment]
@MicePilot Your issue caused by invalid expressions syntax usage, please see [vscode-lldb documentation about Expressions](https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#expressions) for more details.

**Comment by geoffrey4444** [comment]
+1 for this feature request! Debugging natively on Apple Silicon would be very useful for me, and I hope this is something Microsoft will work on

**Comment by Damacustas** [comment]
Yeah this would indeed help a lot!

**Comment by mikekenn** [comment]
+1 for this feature. Come on MS!!

**Comment by lademinoye** [comment]
Ditto!

**Comment by floooh** [comment]
+1

**Comment by ilg-ul** [comment]
+1

**Comment by janekb04** [comment]
I believe I have found a better workaround until this gets fixed. I used `-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64`. This makes CMake generate a Universal build which contains both an Intel-compatible and an Apple Silicon native executable. 

Apparently, when this build is ran without a debugger (with <kbd>⇧ fn F5</kbd>), the native ARM executable gets chosen. At the same time, when running with a debugger (with <kbd>⌃ fn F5</kbd>) the Intel one runs and it can be successfully debugged.

**Comment by AvivPeledTalon** [comment]
This would help a lot! +1

**Comment by kammce** [comment]
Just hit this issue. +1

**Comment by FischLu** [comment]
Why after one and half years of M1 MacBook release, this basic feature is still unsupported? Are there any terrible challenges? Why CodeLLDB can do it?

**Comment by 1111mp** [comment]
`Good things are worth the wait.`

**Comment by Colengms** [comment]
Native debugging support for M1 macOS has been added in 1.9.3.

**Comment by blue42** [comment]
@Colengms  I am actually having this same issue. Running cpptools version 1.13.8 on an Intel mac. Getting the exact same error as the OP stated
```
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (attach failed (Not allowed to attach to process.  Look in the console messages (Console.app), near the debugserver entries, when the attach failed.  The subsystem that denied the attach permission will likely have logged an informative message about why it was denied.))
The program '/Path/to/Project/GameDev/dapper-dasher/main' has exited with code 42 (0x0000002a)
```
launch.json
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
      "version": "0.2.0",
      "configurations": [
        {
          "name": "Debug",
          "type": "cppdbg",
          "request": "launch",
          "program": "${workspaceFolder}/${fileBasenameNoExtension}",
          "args": [],
          "stopAtEntry": false,
          "cwd": "${workspaceFolder}",
          "environment": [],
          "externalConsole": false,
          "MIMode": "gdb",
          "setupCommands": [
            {
              "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": false
            }
          ],
          "windows": {
            "miDebuggerPath": "C:/raylib/w64devkit/bin/gdb.exe",
          },
          "osx": {
            "MIMode": "lldb"
          },
          "linux": {
            "miDebuggerPath": "/usr/bin/gdb",
          },
          "preLaunchTask": "build debug"
        },
        {
          "name": "Run",
          "type": "cppdbg",
          "request": "launch",
          "args": [],
          "stopAtEntry": false,
          "cwd": "${workspaceFolder}",
          "environment": [],
          "externalConsole": false,
          "program": "${workspaceFolder}/${fileBasenameNoExtension}",
          "MIMode": "gdb",
          "windows": {
            "program": "${workspaceFolder}/${fileBasenameNoExtension}.exe",
            "miDebuggerPath": "C:/raylib/w64devkit/bin/gdb.exe"
          },
          "osx": {
            "MIMode": "lldb"
          },
          "linux": {
            "miDebuggerPath": "/usr/bin/gdb"
          },
          "preLaunchTask": "build release",
        }
      ]
    }
```
I did not have any issues two days ago, and now I am getting this error. I haven't changed anything.
