### ISSUE TITLE
cannot open source file "crtdbg.h" (dependency of "iostream")C/C++(1696)

### ISSUE THREAD

**Issue by JamieJeanD** [microsoft/vscode-cpptools#7036]
Full error message:

> #include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\jamie\Documents\C++\HW3\HelloWorld.cpp).C/C++(1696)
> cannot open source file "crtdbg.h" (dependency of "iostream")C/C++(1696)

This happens with a simple Hello World program:

`#include <iostream>

using namespace std;

int main(){
	cout << "Hello World";
}`

A similar message occurs on VSCommunity 2019 (installed alongside Unity, I believe, before I installed VSCode).

**Comment by michelleangela** [comment]
@JamieJeanD 
It could be that the c_cpp_properties.json is not configured to have the desired include paths. Could you provide the log from running the command `C/C++: Log Diagnostics` from the [VS Code command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)? This will show which include paths and compiler is being used to get include path info for the language server to use.

**Comment by JamieJeanD** [comment]
@michelleangela
Here's the log:

```
-------- Diagnostics - 23/02/2021, 23:24:34
Version: 1.2.2-insiders2
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\jamie\Documents\C++\HW3\HelloWorld.cpp ]:
    C:\USERS\JAMIE\DOCUMENTS\C++\HW3\HELLOWORLD.CPP
Translation Unit Configurations:
[ C:\Users\jamie\Documents\C++\HW3\HelloWorld.cpp ]:
    Process ID: 2456
    Memory Usage: 53 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.28.29333\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 53 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 239
Number of files discovered (not excluded): 233

```

**Comment by michelleangela** [comment]
The header file "crtdbg.h" is part of the Windows 10 SDK kit. Example folder path for this file is `C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt`. Do you have any Windows 10 SDK installed? If so, the extension should try to find the folder path to the latest Windows SDK on your machine. If you have Windows 10 SDK installed, and the extension is not finding it automatically, you could you try adding the path to the "includePath" property?

**Comment by JamieJeanD** [comment]
It works fine now on VSCode and VSCommunity, thanks!
