### ISSUE TITLE
auto-complete problem 

### ISSUE THREAD

**Issue by cuiguoxin** [microsoft/vscode-cpptools#704]
recently I used vscode to write C++ code. I use the C/C++ tools but auto-complete function is problematic. Here is the picture about what I met with \:
![image](https://cloud.githubusercontent.com/assets/8746710/25853838/a921907c-3500-11e7-88e5-662e1804f609.png)
How do I get rid of this?

**Comment by bobbrow** [comment]
Autocomplete is not semantic-aware yet.  What you see today is the entire list of symbols encountered by our tag parser.  The list will filter down as you type more characters, but what you see today is currently expected.  We are using issue #13 to track the semantic auto-complete implementation.
