### ISSUE TITLE
Invalid on CentOS7

### ISSUE THREAD

**Issue by deanzxl** [microsoft/vscode-cpptools#7040]
Type: General

this extension is invalid on CentOS7 when I update the vs code to version 1.53.2

**Describe the bug**
- OS and Version:CentOS 7
- VS Code Version: 1.53.2
- C/C++ Extension Version: v1.2.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by michelleangela** [comment]
@deanzxl 
Version 1.2.2 of the C++ extension was just released. Could you try uninstalling an re-installing the extension again? Could you ensure that the older versions of the extensions are deleted from the extension installation path?

If the "invalid error" occurs again, could you provide a screenshot?

**Comment by michelleangela** [comment]
This issue has been closed because it needs more information and has not had recent activity.
