### ISSUE TITLE
identify Variable parameter macro as error

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#7042]
![image](https://user-images.githubusercontent.com/1876302/109091392-a6d48780-774f-11eb-88b5-03c3db7fe8ec.png)

**Comment by sean-mcmanus** [comment]
What compiler are you using to compile? Is it the same as your compilerPath setting or what's reported from C/C++: Log Diagnostics? This issue can occur if you're using cl.exe or an msvc intelliSenseMode by mistake.
