### ISSUE TITLE
autocomplete lag

### ISSUE THREAD

**Issue by Ramblestsad** [microsoft/vscode-cpptools#7044]
**Type: LanguageService**

**Describe the bug**
- MacOS and 11.2.1 Version:
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.1
- Other extensions you installed (and if the issue persists after disabling them): not clear
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
- Just simple intro C program one main.c file, nothing else.
- "C_Cpp.autocomplete": "Default",
   "C_Cpp.intelliSenseEngine": "Default",
   With these two settings, the response time of autocomplete is slow, I am physically outside of the U.S but I am not sure if my physical location is the reason.

**Steps to reproduce**

1. Go to 'New C file'

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Your physical location should have no impact on the performance of IntelliSense completion.

What is the magnitude of lag? Do you see the flame icon when the lag is occurring? Are you able to provide sample code that demonstrates the lag?

**Comment by Ramblestsad** [comment]
> Your physical location should have no impact on the performance of IntelliSense completion.
> 
> What is the magnitude of lag? Do you see the flame icon when the lag is occurring? Are you able to provide sample code that demonstrates the lag?

Here is a gif caught when I type in.
![image](https://user-images.githubusercontent.com/45003009/109252504-acea6700-7828-11eb-8271-bbf7705c510a.png)
It is wierd that the intellisense autocomplete response is much faster inside the "main function" than outside the main function..

Here is my c_cpp properties.json and file tree
![image](https://user-images.githubusercontent.com/45003009/109252584-e4591380-7828-11eb-9b0e-ee44cab8cb2d.png)

Oh, and this is my c_cpp tools config:
"C_Cpp.autocomplete": "Default",
"C_Cpp.intelliSenseEngine": "Default",

**Comment by Ramblestsad** [comment]
> > Your physical location should have no impact on the performance of IntelliSense completion.
> > What is the magnitude of lag? Do you see the flame icon when the lag is occurring? Are you able to provide sample code that demonstrates the lag?
> 
> Here is a gif caught when I type in.
> ![image](https://user-images.githubusercontent.com/45003009/109252504-acea6700-7828-11eb-8271-bbf7705c510a.png)
> It is wierd that the intellisense autocomplete response is much faster inside the "main function" than outside the main function..
> 
> Here is my c_cpp properties.json and file tree
> ![image](https://user-images.githubusercontent.com/45003009/109252584-e4591380-7828-11eb-9b0e-ee44cab8cb2d.png)
> 
> Oh, and this is my c_cpp tools config:
> "C_Cpp.autocomplete": "Default",
> "C_Cpp.intelliSenseEngine": "Default",

oh, it seems the gif broke...
here is the scenario:
when I typed "ty" or "t" on line 38, after like 1 to 1.5 seconds, the autocomplete pops out.

**Comment by Ramblestsad** [comment]
> Your physical location should have no impact on the performance of IntelliSense completion.
> 
> What is the magnitude of lag? Do you see the flame icon when the lag is occurring? Are you able to provide sample code that demonstrates the lag?

Here is a gif:
![image](https://user-images.githubusercontent.com/45003009/109254724-94308000-782d-11eb-8f92-5af1eb4acdae.png)

The problem is when I typed "t" or "ty" on line 38, the suggestions pop out like with 1 to 1.5 seconds delay not immediately.

Here are my file tree and c_cpp_properties.json file screenshots.
![image](https://user-images.githubusercontent.com/45003009/109254927-fab59e00-782d-11eb-85ae-ce942a6c829e.png)
![image](https://user-images.githubusercontent.com/45003009/109254949-0739f680-782e-11eb-9423-5069e507ea43.png)

**Comment by Ramblestsad** [comment]
> > Your physical location should have no impact on the performance of IntelliSense completion.
> > What is the magnitude of lag? Do you see the flame icon when the lag is occurring? Are you able to provide sample code that demonstrates the lag?
> 
> Here is a gif:
> ![image](https://user-images.githubusercontent.com/45003009/109254724-94308000-782d-11eb-8f92-5af1eb4acdae.png)
> 
> The problem is when I typed "t" or "ty" on line 38, the suggestions pop out like with 1 to 1.5 seconds delay not immediately.
> 
> Here are my file tree and c_cpp_properties.json file screenshots.
> ![image](https://user-images.githubusercontent.com/45003009/109254927-fab59e00-782d-11eb-85ae-ce942a6c829e.png)
> ![image](https://user-images.githubusercontent.com/45003009/109254949-0739f680-782e-11eb-9423-5069e507ea43.png)

Oh...
It seems the gif has broken.
The problem is:
1. for example on line 38, When I type character, the suggestion appears with like 1.5 seconds delay. However, when I typed something inside my main function, the response is much better but still a little delayed, not immediately.
2. When I changed my "C_Cpp.intelliSenseEngine": "Default", to "Tag Parser", it cannot suggest my local variables.

**Comment by Ramblestsad** [comment]
and yes there is the flame icon when lag is occuring.

**Comment by sean-mcmanus** [comment]
That appears to be "by design" (as expected), but you may be able to reduce that delay by changing C_Cpp.intelliSenseUpdateDelay to 500.

**Comment by Ramblestsad** [comment]
> That appears to be "by design" (as expected), but you may be able to reduce that delay by changing C_Cpp.intelliSenseUpdateDelay to 500.

Thanks for the reply! So "by design", that little delay is expected.
