### ISSUE TITLE
C Compiler Error

### ISSUE THREAD

**Issue by sun-rishi** [microsoft/vscode-cpptools#7045]
While declaring an array with variable size getting "Expression must have some constant value"

![Visual Studio Code Issue](https://user-images.githubusercontent.com/17306329/109147787-6f83cc00-778b-11eb-81e3-012578f9ded6.PNG)
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 .
