### ISSUE TITLE
VSC: HTML language not supported or defined

### ISSUE THREAD

**Issue by whatabearthinks** [microsoft/vscode-cpptools#7050]
**Type: HTML**
macOS Catalina 10.15.7
VSC version 1.53.2 
I have the Google Chrome and Safari browsers.

On a Visual Studio Code page I wrote some HTML code (I have it linked to a CSS file but I don't think that matters for my problem), and when I click the "Run Code" button, I am presented with the message "Code language not supported or defined".

I have the language set to HTML, not "Auto Detect"

Under the message, it says the source is "Code Runner (Extension)"

I have Disabled and Uninstalled/Reinstalled this extension and restarted VSC multiple times.

I have other extensions installed, but am not entirely sure how to use them to "Run" the code.

I have read be "sure the executor PATH of each language is set in the environment variable," but I'm not entirely sure how I can do that.

**Comment by Colengms** [comment]
Hi @whatabearthinks .  This repo is for the C/C++ Extension for VS Code.  Since you are referring to HTML and not C or C++, I'd suggest opening an issue directly in the VS Code repo here: https://github.com/microsoft/vscode .  They should be able to assist.

Closing this issue as external.
