### ISSUE TITLE
Auto-complete of #include with angle bracket "<" does not complete closing angle bracket ">" 

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#7054]
Typing the following:

```
#include <iostr
```

Will result in auto-complete suggesting for 'iostream', but selecting it does not add the trailing ">".  When using quotes, the end quote is added automatically.  This issue tracks adding a closing angle bracket.

**Comment by sean-mcmanus** [comment]
Should there be a setting for potentially disabling this?

**Comment by michelleangela** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders4

**Comment by michelleangela** [comment]
Fix is released in the 1.3.0 release version https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0
