### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rajarajput2** [microsoft/vscode-cpptools#7059]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `1.2.2`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by WardenGnaw** [comment]
Missing `⚠️ We have written the needed data into your clipboard. Please paste! ⚠️`
