### ISSUE TITLE
Error when loading C/C++ extension

### ISSUE THREAD

**Issue by mathisloge** [microsoft/vscode-cpptools#7068]
Type: General

**Describe the bug**
- VsCode Version: 1.53.2 (system setup)
- Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
- Date: 2021-02-11T11:48:04.245Z
- Electron: 11.2.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT x64 10.0.19042
- C/C++ Extension Version: 1.2.2
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Getting the following error message, after opening a c++ project (cmake based)
![image](https://user-images.githubusercontent.com/13556116/109387931-54889780-7904-11eb-8a75-4233a8b5d253.png)

Error text translated: The C/C++ extension could not be installed successfully. You need to reinstall the C/C++ language features extension for the extension to work properly.

This just popped up after updating to 1.2.2.
I've Visual Studio 2019 Community Edition updated to the latest version and cmake 3.19.5 installed. 

**To Reproduce**
Happens for all c++ projects. uninstall and reinstalling does not resolve this. 

When trying to install with the `cpptools-win-arm64.vsix` file, comes the following error: 
![image](https://user-images.githubusercontent.com/13556116/109388046-058f3200-7905-11eb-882a-937bb7ddd8e1.png)

and the install log: 
```
27.02.2021 14:06:22 - Microsoft VSIX Installer
27.02.2021 14:06:22 - -------------------------------------------
27.02.2021 14:06:22 - vsixinstaller.exe version:
27.02.2021 14:06:22 - 16.8.3036
27.02.2021 14:06:22 - -------------------------------------------
27.02.2021 14:06:22 - Command line parameters:
27.02.2021 14:06:22 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\mathi\Downloads\cpptools-win-arm64 (2).vsix
27.02.2021 14:06:22 - -------------------------------------------
27.02.2021 14:06:22 - Microsoft VSIX Installer
27.02.2021 14:06:22 - -------------------------------------------
27.02.2021 14:06:22 - Initializing Install...
27.02.2021 14:06:22 - Erweiterungsdetails...
27.02.2021 14:06:22 - 	Identifier         : cpptools
27.02.2021 14:06:22 - 	Name               : C/C++
27.02.2021 14:06:22 - 	Author             : ms-vscode
27.02.2021 14:06:22 - 	Version            : 1.2.2
27.02.2021 14:06:22 - 	Description        : C/C++ IntelliSense, debugging, and code browsing.
27.02.2021 14:06:22 - 	Locale             : en-US
27.02.2021 14:06:22 - 	MoreInfoURL        : 
27.02.2021 14:06:22 - 	InstalledByMSI     : False
27.02.2021 14:06:22 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
27.02.2021 14:06:22 - 
27.02.2021 14:06:22 - 	SignatureState     : Unsigned
27.02.2021 14:06:22 - 	Unterstützte Produkte : 
27.02.2021 14:06:22 - 		Microsoft.VisualStudio.Code
27.02.2021 14:06:22 - 			Version : 
27.02.2021 14:06:22 - 
27.02.2021 14:06:22 - 	Verweise           : 
27.02.2021 14:06:22 - Signaturdetails...
27.02.2021 14:06:22 - 	Extension is not signed.
27.02.2021 14:06:22 - 
27.02.2021 14:06:22 - Er wird nach passenden Produkten gesucht...
27.02.2021 14:06:22 - Installiertes Produkt gefunden - Globaler Pfad
27.02.2021 14:06:22 - Installiertes Produkt gefunden - Visual Studio Community 2019
27.02.2021 14:06:22 - VSIXInstaller.NoApplicableSKUsException: Mindestens eine Erweiterung ist für Visual Studio Code bestimmt. Installieren Sie sie in Visual Studio Code.
   bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

VsCode is installed in `C:\Program Files\Microsoft VS Code` and in PATH

**Comment by mathisloge** [comment]
just an additional screenshot after installing directly from vsix 
![image](https://user-images.githubusercontent.com/13556116/109388242-3b80e600-7906-11eb-94ea-e91f09fea3d1.png)

**Comment by mathisloge** [comment]
okay. funnily enough, i was able to fix it by reinstalling version 1.2.1 via vsix and then upgrading to 1.2.2.

**Comment by DivineStride** [comment]
I get the same error but the solution above doesn't resolve anything for me.

`Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (7288 KB)  Failed. Retrying...(7288 KB)  Failed. Retrying...(7288 KB)  Failed. Retrying...Waiting 8 seconds...(7288 KB)  Failed. Retrying...Waiting 16 seconds...(7288 KB)  Failed to download https://go.microsoft.com/fwlink/?linkid=2156410
Failed at stage: downloadPackages
Invalid content received. Hash is incorrect.

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
`

**Comment by DivineStride** [comment]
I solved the issue by manually installing the correct package instead of the ARM64.

**Comment by sean-mcmanus** [comment]
@mathisloge You were double-clicking the .vsix instead of using the Install from VSIX command).

```
Instructions
To use the "offline" .vsix (that doesn't download OS-based dependencies on extension activation), download the .vsix that matches your OS and run the "Install from VSIX" command in VS Code (don't double-click the .vsix or another app like VS might try to open it incorrectly).
```

@DivineStride https://go.microsoft.com/fwlink/?linkid=2156410 is the x64 Windows binary -- were you seeing the ARM64 version being used instead?

We're not sure what is causing the install problems (we haven't seen a failure ourselves yet). Let us know if anyone has more repro info. I could be some VS Code installation problem.

**Comment by mathisloge** [comment]
@sean-mcmanus i know that the first picture was the wrong installation. But the described error came from updateting through visual studio code itself, without installing the extension via vsix. 
The vsix step was a try to workaround the error. 

As described, the i have fixed the error with the following steps: 

Precondition:
Visual Studio Code updated the extension to 1.2.2, error shows as " The C/C++ extension could not be installed successfully. You need to reinstall the C/C++ language features extension for the extension to work properly."

Steps to fix:
* uninstall extension
* install extension version 1.2.1 manually via vsix
* update to 1.2.2 again

**Comment by sean-mcmanus** [comment]
We believe your original issue is a VS Code bug: https://github.com/microsoft/vscode/issues/100537 . They need more info: https://github.com/microsoft/vscode/issues/100537#issuecomment-646540267
