### ISSUE TITLE
Update exception in ipv6 network

### ISSUE THREAD

**Issue by daimaxiaxie** [microsoft/vscode-cpptools#7069]
Issue Type: <b>Bug</b>

When my computer installs a new C++ plug in the ipv6 network, the update component will be abnormal, and the progress bar will get stuck when it reaches about halfway. And it is normal under the ipv4 network.

Extension version: 1.2.2
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.80GB (6.56GB free)|
|Process Argv|--crash-reporter-id 3268bc52-8b89-4580-8062-df769f271e33|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475

```

</details>

**Comment by sean-mcmanus** [comment]
What progress bar are you referring to? What stage is it stuck at? Can you provide a screenshot? Is this with the online installer? I assume it doesn't repro with the offline vsix's at https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 ?

**Comment by daimaxiaxie** [comment]
I mean the lower right corner of the vscode notification schedule, when after updating the CPP plug-in restart, there will be displayed to update the component.

**Comment by sean-mcmanus** [comment]
What does the text of the progress bar say?
