### ISSUE TITLE
identifier "strdup" is undefined

### ISSUE THREAD

**Issue by rupinderg00** [microsoft/vscode-cpptools#7070]
in cpp code, strdup is underlined ( if used) with a red squiggle with the error 'identifier "strdup" is undefined', even after including string.h library. How to get rid of this?
VS code version: 1.53.2
Windows : 20H2

**Comment by sean-mcmanus** [comment]
What is your compilerPath and includePath? The output of running the C/C++: Log Diagnostics command could help. Is this with C or C++. The screenshot below shows the expected results:

![image](https://user-images.githubusercontent.com/19859882/109544825-e0253400-7a7c-11eb-86a2-d29471534999.png)

**Comment by rupinderg00** [comment]
![image](https://user-images.githubusercontent.com/57314419/109547049-f10f8d00-7af0-11eb-9579-54d6b5c60e9d.png)
![image](https://user-images.githubusercontent.com/57314419/109547150-12707900-7af1-11eb-8104-ac5460854d22.png)
Screenshots are attached. I am using C++.

**Comment by sean-mcmanus** [comment]
Can you remove any system includes from your includePath setting? It looks like that may be causing your last 2 system includes to be in the wrong order. Also, can you change your intelliSenseMode to "gcc-x86", assuming that is what you intend? Otherwise, can you do Go to Definition on the `#include <string.h>` to look for why the definition for strdup is not being processed, e.g. look to see if there are error squiggles or if it's in an inactive region?

**Comment by rupinderg00** [comment]
I changed the intelliSenseMode to "gcc-x86".  There isn't any error squiggle on #include <string.h> (screenshot is attached.) 
When I tried to change the includePath, I couldn't find those paths (shown in log diagnostic command) in the include Path settings in C/C++ configurations. Is it the correct place to check?

![image](https://user-images.githubusercontent.com/57314419/109607245-f64ef500-7b4d-11eb-8804-b00bff86e7b9.png)
![image](https://user-images.githubusercontent.com/57314419/109607286-04047a80-7b4e-11eb-8358-9cc4eb2d240b.png)
![image](https://user-images.githubusercontent.com/57314419/109607311-0f57a600-7b4e-11eb-85ff-a1625287e9f2.png)

**Comment by sean-mcmanus** [comment]
Yeah, the includePath to the mingw path should not be required and implies that querying your compiler is failing to get the necessary system includes/defines which would cause the strdup definition to not be found. When you set C_Cpp.loggingLevel to "Debug" do you see errors after "Compiler query command line:"?

What do you get if you Go to Definition on strdup?

**Comment by rupinderg00** [comment]
Removed few includePath from the setting and now it is working fine.
Thanks for your assistance, sir!

Final includePaths
![image](https://user-images.githubusercontent.com/57314419/109701374-f0422e00-7bb8-11eb-9485-8296846a905d.png)
