### ISSUE TITLE
cannot open source file "stddef.h" ubuntu 20.04 gcc-10

### ISSUE THREAD

**Issue by plantoscloud** [microsoft/vscode-cpptools#7071]
**Type: LanguageService**

cannot open source file "stddef.h" ubuntu 20.04 gcc-10

i have a brand new fresh snow white VM of Ubuntu 20.04.
i installed vscode and added the C++ extension.   
i then wrote some C++ code hello world. with the following includes
 iostream
 vector
 string

all three showed squiggly
of course i then installed C++ like so...

sudo apt install gcc-10 gcc-10-base gcc-10-doc 
sudo apt install libstdc++-10-dev libstdc++-10-doc 

and configured the C++ extension like so
            "compilerPath": "/usr/bin/gcc-10",
            "cStandard": "gnu17",
            "cppStandard": "gnu++20",
            "intelliSenseMode": "linux-gcc-x64"
            
 Now the stubborn squiggly stays at #include iostream only
 
 the error message with the light bulb states that   cannot open source file "stddef.h"
 
 it gives me the option of choosing 
 /usr/lib/gcc/x86_64-linux-gnu/10/include
 or 
 "/usr/include/linux"
 
 when i choose  /usr/lib/gcc/x86_64-linux-gnu/10/include the squiggly goes away
when i choose  "/usr/include/linux" it does not.

then the weirdest thing happened.  I deleted all the includes the tooltips had me add, and went back to see what would happen.
now its giving me the choice of "/usr/include/c++/10/tr1"

what?!!? LOL.

the actual file seems to be located at /usr/include/c++/10
no matter what include is in the include path.

then i said wait hold up.  im a newb but lemme check if im really installing C++ and not just beleiving some guy on the internets directions.    so i went rogue and did this...

sudo apt install g++-10

squigglies are now gone no include path needed.. might help someone down the line this post.

i then built my exe from the command line first
/usr/bin/g++-10 -v -g /home/meta/org/vscode/mydriver.cpp -o /home/meta/org/vscode/mydriver

seems like the include path for standard libraries comes inside G++.. e.g. no environment variable or IDE setting needed

#include <...> search starts here:
 /usr/include/c++/10
 /usr/include/x86_64-linux-gnu/c++/10
 /usr/include/c++/10/backward
 /usr/lib/gcc/x86_64-linux-gnu/10/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
 
 
 then i went to Terminal >> Configure Default Build Task.
 
 make sure you pick the G++ one not the GCC one
 
 i then add a -v to the build arguements just for kicks.
 i build and run from the command line.
 
 "Hello world!"  #great 
 
 so then i pressed control shift B to run my build the active file task.
worked like a charm.

i then went to Run >> Add Configuration

thats when things go crazy again.   I didnt get that drop down you usually get when you do Ctrl P.
i got some in editor drop down that was kindof vague.  but i picked C/C++ gdb Launch

the config it gave me was incomplete.
it was missing the 

            "preLaunchTask": "C/C++: g++-10 build active file",
            "miDebuggerPath": "/usr/bin/gdb"
            
 and i had to add my own     value for Program
 "program": "${fileDirname}/${fileBasenameNoExtension}",
 
 when i    pressed f5 it did indeed stop at the breakpoint but i had to manually change the sidebar to the debugging side bar.
 
 
 here are the links i followed
 https://code.visualstudio.com/docs/cpp/config-linux
 https://ducciogasparri.it/2020/07/30/installing-c17-and-c20-on-ubuntu-and-amazon-linux/
 and i added my own sudo apt install g++-10
 
 ive used vscode marvelously for things like Blockchain, nodejs, Kubernetes, powershell on both ubuntu, windows and WSL.
this is the first time im having troubles understanding whats going on.
Im kinda hesitant going forward with C++ on VScode as my ultimate project is having me do multiplatform stuff like migrating C++ code from ROS to ROS2
and build some components for another robotics system called Nvidia ISaac.    Which means im going to be bouncing from Ubuntu 1804 or 20.04 on PCs to things like Ubuntu on NVidia and Raspbian on Raspberry PI.

Im already a newb at C++ so any little funkiness like i went through here with VSCode extension my sanity cannot afford it.

im going to try to do everything i just did in CLion and compare.

any insight into the above matters would be greatly appreciated.
 
 

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by plantoscloud** [comment]
p.s. 

i just saw that i had left the UI Configured C++compiler path at gcc-10 and not g++-10
this helps with intellisense my understanding hello world doesnt do anything in the G++-10 space so i got lucky

**Comment by plantoscloud** [comment]
p.s.s. let me add that i just now installed build-essential
sudo apt-get install build-essential
not sure why this doesnt come with g++-10

after messing around with CLion i was getting weird problems with cmake.
clion uses Cmake alot as build system.

even though i had the compilers i wanted to use installed somehow installing build-essential ( which has dependencies on g++-9 in ubuntu 2004 ) fixed my problem.

**Comment by sean-mcmanus** [comment]
Did you have a bug to report? We have a tutorial at https://code.visualstudio.com/docs/cpp/config-linux .
