### ISSUE TITLE
#include not working for implementation-defined header using Remote - SSH

### ISSUE THREAD

**Issue by jamesbraza** [microsoft/vscode-cpptools#7074]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS Catalina, v10.15.7
- VS Code Version: v1.53.2
- C/C++ Extension Version: v1.2.2
- Other extensions you installed (and if the issue persists after disabling them): [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-edit) v0.64.0
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes
    - Remote machine OS: Ubuntu 16.04.4 LTS
    - `g++ --version`: `g++ (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010`
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

A `my-file.cpp` file on a remote machine has the following include: `#include "socket++/sockstream.h"`

However, Intellisense is not able to properly include the file, the `#include` has a red squiggle underneath.  Hovering over it, I get this message:

```
#include errors detected. Please update your includePath. Squiggles are disabled
for this translation unit (/afs/some.thing/users/path/to/my-file.cc).C/C++(1696)
cannot open source file "socket++/sockstream.h"C/C++(1696)
```

There are two locations relevant to this `include`:
- `/usr/foo/bar/include/socket++` there are a few files: `sockstream.h  sockstream.h~`
- `/usr/foo/bar/lib/socket++` are the precompiled binaries: `libsocket++.a  libsocket++.la  libsocket++.so  libsocket++.so.1  libsocket++.so.1.0.2`

Using `g++` with `-MM` yields the following:

```
my-file.o: my-file.cc \
 /usr/foo/bar/include/socket++/sockstream.h
```

**Expected behavior**

I would like to be able to CMD + click on the header file and jump to it.

Is this supported?  And if yes, what am I missing?

**Additional context**

<details>
  <summary><code>settings.json</code></summary>

```json
{
    "window.zoomLevel": 2,
    "editor.renderWhitespace": "all",
    "editor.minimap.enabled": true,
    "explorer.confirmDragAndDrop": false,
    "remote.SSH.remotePlatform": {
        "some.thing": "linux"
    },
    "remote.SSH.useFlock": false
}
```

</details>

<details>
  <summary><code>c_cpp_properties.json</code></summary>

```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/foo/bar/local/include",
                "/usr/foo/bar/include",
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-clang-x64"
        }
    ],
    "version": 4
}
```

</details>

<details>
  <summary><code>baz.code-workspace</code></summary>

```json
{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "../../code"
		}
	],
	"settings": {
		"editor.rulers": [
			{
				"column": 80
			},
			{
				"column": 120
			},
		],
		"files.associations": {
			"errno.h": "c",
			"exception": "cpp",
			"string": "cpp",
			"set": "cpp",
			"ostream": "cpp",
			"iostream": "cpp",
			"iosfwd": "cpp",
			"bitset": "cpp",
			"string_view": "cpp",
			"functional": "cpp"
		}
	}
}
```

</details>

**Comment by jamesbraza** [comment]
Hello @sean-mcmanus thank you for the response!

<details>
  <summary>C/C++ Log Diagnostics Initial</summary>

```
-------- Diagnostics - 3/1/2021, 6:59:39 PM
Version: 1.2.2
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /afs/some.thing/users/path/to/my-file.cc ]:
    /afs/some.thing/users/path/to/my-file.cc
Translation Unit Configurations:
[ /afs/some.thing/users/path/to/my-file.cc ]: not ready
    Process ID: 20431
    Memory Usage: 3 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/local/include
        /usr/lib/llvm-10/lib/clang/10.0.1/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=100001
Total Memory Usage: 3 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 48977
Number of files discovered (not excluded): 43822
```

</details>

The "includePath" and the Translation Unit Configurations' "Includes" doesn't have the "/usr/foo/bar/include" inside.

I did not know that each of the `folders` in the `.code-workspace` needs an associated `c_cpp_properties.json`.  You correctly observed that only the folder `"path": "."` has a corresponding `.vscode/c_cpp_properties.json`.

For the folder `"path": "../../code"`, I copied the original `c_cpp_properties.json` into a `.vscode/c_cpp_properties.json` there too.

<details>
  <summary>C/C++ Log Diagnostics Updated</summary>

```
-------- Diagnostics - 3/1/2021, 7:16:15 PM
Version: 1.2.2
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/usr/foo/bar/local/include",
        "/usr/foo/bar/include",
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "/usr/foo/bar/local/include",
            "/usr/foo/bar/include",
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /afs/some.thing/users/path/to/my-file.cc ]:
    /afs/some.thing/users/path/to/my-file.cc
Translation Unit Configurations:
[ /afs/some.thing/users/path/to/my-file.cc ]:
    Process ID: 21338
    Memory Usage: 82 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /afs/some.thing/foo/bar/local/include
        /afs/some.thing/foo/bar/include
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/local/include
        /usr/lib/llvm-10/lib/clang/10.0.1/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=100001
Total Memory Usage: 82 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 50033
Number of files discovered (not excluded): 44777
```

</details>

So, the problem was that I didn't know `c_cpp_properties.json` only applies on a per-workspace folder basis.

@sean-mcmanus do you think it's better to have:

- Identical `c_cpp_properties.json`, on a per-workspace folder basis
- Configure the include path globally in `.code-workspace`?

**Comment by sean-mcmanus** [comment]
Either method of configuring is fine -- up to you. Having 2 c_cpp_properties.json keeps it pretty simple and independent to me, but other people like to use the C_Cpp.default settings more.

**Comment by jamesbraza** [comment]
Thank you for following up, and thank you for the assistance!  Case closed.
