### ISSUE TITLE
memory checking failed while debugging cplusplus with gdb

### ISSUE THREAD

**Issue by jihuacao** [microsoft/vscode-cpptools#7076]
![image](https://user-images.githubusercontent.com/22140223/109506581-c285b800-7ad8-11eb-95cf-222b6f2577c5.png)
![image](https://user-images.githubusercontent.com/22140223/109506700-e812c180-7ad8-11eb-8335-77f08a6933bb.png)

**Comment by WardenGnaw** [comment]
In order to use gdb commands directly, you will need to prefix your commands with `` ` `` or `-exec`
