### ISSUE TITLE
If autocomplete is disabled, VSCode's completion is gone.

### ISSUE THREAD

**Issue by dangerousNull** [microsoft/vscode-cpptools#7082]
**Type: LanguageService**

In the UI settings, there is an option called "`C_Cpp: Autocomplete`." By description, if this is "disabled," VSCode's original code completion would take its place. However, when I disable it, there are no completions at all, besides my set up snippets from a snippet file.

**Describe the bug**
- OS and Version: macOS 11.2.2
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.2
- Other extensions you installed (and if the issue persists after disabling them): PlatformIO, and it doesn't persist, but that's because it's dependant on the C++ extension, so **I can only disable both.**
- Does this issue involve using SSH remote to run the extension on a remote machine?: No.
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I disable the whole extension, I have VSCode's completion, if I disable the in-extension autocomplete, completion is gone all together.

**Steps to reproduce**

1. Go to your C++ extension's UI settings.
2. Tick off `C_Cpp: Autocomplete` to disable it.
3. You don't have any completion in your C++ projects.

**Expected behavior**

You would still get red error underlines, but you wouldn't get the VSCode built-in completion.

**Comment by sean-mcmanus** [comment]
This is "by design". To get VS Code's built-in completion, add
```
      "[cpp]": {
        "editor.wordBasedSuggestions": true
      },
      "[c]": {
        "editor.wordBasedSuggestions": true
      },
```

**Comment by sean-mcmanus** [comment]
We're tracking improving the documentaiton on this at https://github.com/microsoft/vscode-cpptools/issues/3920
