### ISSUE TITLE
Not showing the content of std::vector and similar STL containers when using g++-9

### ISSUE THREAD

**Issue by aniervs** [microsoft/vscode-cpptools#7086]
Type: Debugger

**Describe the bug**
- OS and Version: macOS Catalina 10.15.3
- VS Code Version: 1.52.0
- C/C++ Extension Version: 1.2.2

When I have a std::vector<> and I want to watch the elements it contains, it shows some memory directions (to the start, the finish, and the end of  storage), but I'm unable to watch all the elements at once.

- I have other extensions you installed non related to C++: Microsoft Python, Java Extension Pack, Microsoft Jupyter Notebook, Markdown + Math. After disabling them, the issue persists.

I'm using these `launch.json` and `tasks.json` files:

[launch.txt](https://github.com/microsoft/vscode-cpptools/files/6065722/launch.txt)

[tasks.txt](https://github.com/microsoft/vscode-cpptools/files/6065723/tasks.txt)

This is a picture of how the debugging UI looks like.

<img width="1680" alt="Screen Shot 2021-03-01 at 9 20 30 PM" src="https://user-images.githubusercontent.com/44501642/109586700-b9461c80-7ad3-11eb-9033-59effdaac464.png">

Here it's a picture of how the debugging UI looks like when using the `launch.json` and `tasks.json` files as appear in the guide.

<img width="1680" alt="Screen Shot 2021-03-01 at 9 29 53 PM" src="https://user-images.githubusercontent.com/44501642/109587404-07a7eb00-7ad5-11eb-9e57-bf1fb036e11b.png">

**Comment by WardenGnaw** [comment]
The visualization fails because `lldb` knows how to visualize `clang` built STL. If you are using `g++`, you will want to use `gdb` with visualizers installed to get this working.

**Comment by aniervs** [comment]
@WardenGnaw can you guide me to set gdb as the debugger? I already installed it though home-brew, but when I set it on the `launch.json` file it just doesn't run.
