### ISSUE TITLE
cygwin.S 

### ISSUE THREAD

**Issue by Urbaner3** [microsoft/vscode-cpptools#7090]
Issue Type: <b>Bug</b>

I don't get how that closed problem on stackflow. Please show me a method to solve the problem. I don't understand why it's trying to find src directory in C:// on Windows System which should be a directory in Unix-like system.

Extension version: 1.2.2
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.29GB free)|
|Process Argv|--crash-reporter-id fff18e92-0b7a-434f-8296-e0b00ab8839e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425

```

</details>

**Comment by Urbaner3** [comment]
Does anyone understand these pages?
https://sourceforge.net/p/mingw-w64/bugs/742/
https://bugreports.qt.io/browse/QTBUG-68502
https://github.com/microsoft/vscode/issues/28433
 It seems that mingw just left the problem like it is now.

**Comment by sean-mcmanus** [comment]
I don't understand what you're talking about.
