### ISSUE TITLE
Find All References Takes 10 minutes to execute on large codebases

### ISSUE THREAD

**Issue by frojoroku** [microsoft/vscode-cpptools#7096]
![FindAllreferences](https://user-images.githubusercontent.com/78876665/109742431-9fb8d980-7b94-11eb-9945-cf339b656caa.png)
![FindAllreferences](https://user-images.githubusercontent.com/78876665/109742498-c119c580-7b94-11eb-8678-62e253d0d50f.png)

Issue Type: <b>Performance Issue</b>

+use cmake to generate compile_commands.json for a large C++ project more than 10,000 files)
+use VScode to open the root folder where the source is located
+configure VSCode to use compile_commands.json to generate intellisense information
+Navigate to a function, right click and choose "find all references"

Observe 
VSCode scans over 10 thousand fiels, this process takes aproximately 10 minutes

Expected result
VSCode should take less than 10 minutes to find the references to a function

Extension version: 1.2.2
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.4.0-60-generic snap

**Comment by sean-mcmanus** [comment]
If if says 8892 files need to be confirmed, that means 8892 files have a lexical reference to the text that the Find was invoked on and it needs to parse the TUs to confirm if the signatures match. It is expected that Find All Reference would be aborted or canceled in those scenarios -- the feature is designed to be used on references that are used in a limited number of files and not common text like "string". If you have a specific example or scenario that you believe we could optimize or you think is behaving incorrectly we could potentially consider fixing that.

**Comment by frojoroku** [comment]
Good point I will try to optimize this on my side, thanks for the quick response
