### ISSUE TITLE
Breakpoint is not loaded in Debug mode in Mac OSX El Capital.

### ISSUE THREAD

**Issue by elyuh** [microsoft/vscode-cpptools#71]
Dear M,
I tried to use this on my Macbook running El Capital.
I strictly followed the installation manual as well as the addition steps to configure the tool correctly.
But when I run a debug session, the breakpoint couldn't be loaded hence the whole program is executed instead.
The same problem also happened when using it in Fedora 19 (I understand this OS is not officially supported yet but pretty similar to Ubuntu).
One thing I recognized is that I have to change my terminal shell into a BASH shell to make it open the external terminal.
Look forward to your feedback. Thank you.

**Comment by jacdavis** [comment]
elyuh, 

If you debug your application with the same instance of gdb on your Mac, is it able to launch the target debuggee and hit breakpoints? If it is, this rules out any signing issues.

What flags to gcc/g++ did you use to compile your application? Did you pass -g to generate symbols? Are the symbols stripped or anything like that?

Thanks for the feedback. 

Jackson

**Comment by pierregreborio** [comment]
Make sure you have the -g option in your tasks.json:

"args": ["-pipe", "-O2", "-std=c++14", "${workspaceRoot}/${relativeFile}", "-o", "${fileDirname}/a.out", _"-g"_],

That option generates the debugging symbols

**Comment by pieandcakes** [comment]
@elyuh We now include `lldb` with our extension which might work better. This should no longer be an issue. Please comment/reopen if you have further questions.
