### ISSUE TITLE
WSL Include file not found in include path 

### ISSUE THREAD

**Issue by eesaber** [microsoft/vscode-cpptools#710]
-  VSCode Version: 1.12.1
-  C/C++Plugin Version: 0.11.0
-  OS Version: Windows 10 64-Bit with Creator update
![default](https://cloud.githubusercontent.com/assets/13211320/25901153/6d28da3a-35c8-11e7-9a9b-761175fb6657.png)

Hello, I am a bash on Ubuntu on Windows user. And I've had some problems when I was programming in C++. When I put the headers (includes) then it appeared this: "include file not found in include path". How can I fix this?  I try to add "/usr/include" into it as the figure shows.
![default](https://cloud.githubusercontent.com/assets/13211320/25901734/3c9bd208-35ca-11e7-9683-9c2a201b9b5e.png)

 in c_cpp_properties.json . But it does not works. 
Thank you!

**Comment by SkyRiderMike** [comment]
I meet the same problem also..

VSCode Version: 1.12
OS Version: windows 10 Latest Update
Steps to Reproduce:
set bash Ubuntu on win10 asthe default command window for visual code
add include path for c++ headers on WSL, such as : "C:/Users/user_name/AppData/Local/lxss/rootfs/usr/include/c++/5 " in c_cpp_properties.jason
And this won't work...visual code still can't find these c++ header for linux sub-system.

**Comment by JirkaValtr** [comment]
I just had a similar issue trying to use VSCode with MinGW on Windows 10 (no Ubuntu on Windows in my case). And I have been able to solve it by adding the include paths to the `browse.path` property rather than just to the `includePath` property. So in your case
```json
"browse": { 
    "path": [
        "/usr/include",
        "/usr/local/include"
    ],
```
It seems to be an inconsistency between the recommended property to edit (`includePath`) and the one that is being used by IntelliSense by default (`browse.path`). See the [FAQ here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md) for more info (note that the default intelliSenseEngine in the VSCode settings is the Tag Parser).

**Comment by zinechant** [comment]
@JirkaValtr Thanks for your solution. I am also using VSCode with MinGW on Windows 10. After I added the paths to the browse.path, I found that the C/C++ plugin complains that functions like 'fprintf'. 'fopen' are not defined although I did include \<cstdio\> or <stdio.h>(I tried both of them, they both don't work). Have you ever encountered the similar situations? Thanks.

VSCode Version: 1.12.2
C/C++Plugin Version: 0.11.1

![image](https://cloud.githubusercontent.com/assets/7436105/26280768/525ecb16-3da6-11e7-9b47-274c33cf16a1.png)

**Comment by JirkaValtr** [comment]
I tried to replicate your situation, but the following code ran fine for me, and the C/C++ plugin didn't complain about anything.
```cpp
#include <cstdio>
#include <cstdlib>

int main() {
    FILE* fo = fopen("myfile.txt","w");
    if (fo != NULL) fclose(fo);
}
```

**Comment by sean-mcmanus** [comment]
@zinechant What version of gcc and/or libc++ are you using?

**Comment by zinechant** [comment]
@JirkaValtr Thanks a lot for your reply. I have no clue why it doesn't work in my situation.
@sean-mcmanus I am using MinGW with g++ V5.3.0. I don't know how to check the libc++ version that MinGW uses. From a quick search, it seems MinGW built against libmsvcrt.a rather than glibc.

**Comment by sean-mcmanus** [comment]
@zinechant Probably there are more paths you need to add. If you open the #include files to see what squiggles they show, that might help diagnose the problem. I don't think we've tested on WSL yet, so there might be issues.

**Comment by bobbrow** [comment]
Since you're on Windows, the IntelliSense mode defaults to Microsoft mode, not gcc/clang mode.

We don't expose any controls to switch this right now, but you can see if replacing `%userprofile%\.vscode\extensions\ms-vscode.cpptools-0.11.1\bin\msvc.64.intel.json` with `msvc.64.linux.json` fixes it.

**Comment by eesaber** [comment]
@bobbrow  Thanks for your reply. It still not works. Will the control which can switch to gcc mode become a setting option in future release?

**Comment by bobbrow** [comment]
Yes, it is on our backlog.

**Comment by SkyRiderMike** [comment]
That's great to hear...i am looking forward windows' version of visual code cpptools will support bash on ubuntu gcc mode

**Comment by bobbrow** [comment]
@eesaber I had success with the following config:

```
        {
            "name": "WSL",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}",
                "${localappdata}/lxss/rootfs/usr/include/c++/5",
                "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                "${localappdata}/lxss/rootfs/usr/include/c++/5/backward",
                "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                "${localappdata}/lxss/rootfs/usr/local/include",
                "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu",
                "${localappdata}/lxss/rootfs/usr/include"
            ],
            "defines": [
                "__linux__",
                "__x86_64__"
            ],
            "browse": {
                "path": [
                    "${localappdata}/lxss/rootfs/usr/include/c++/5",
                    "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                    "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                    "${localappdata}/lxss/rootfs/usr/local/include",
                    "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                    "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu",
                    "${localappdata}/lxss/rootfs/usr/include/*"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
```

An option to select clang/gcc mode on Windows is coming in the next update.  I have tested it with MinGW on Windows and it works well for me.  I will test it with WSL tomorrow.  Watch the release notes for instructions.  We'll add a FAQ for WSL with this config in it as well, since we're not going to auto-detect it for you right now.

**Comment by eesaber** [comment]
@bobbrow I success too. Thank you so much!

**Comment by bobbrow** [comment]
I updated the config above after doing some testing with WSL.  It now includes the new `intelliSenseMode` setting which was added in version 0.12.0.  I tested this config using the `"C_Cpp.intelliSenseEngine": "Default"` setting and can confirm that semantic autocomplete, quick info tooltips, and linting are working as expected.

**Comment by lurium** [comment]
So...where is clang actually running here if I am using VSCode on windows10?

Thanks

**Comment by sean-mcmanus** [comment]
@lurium Our clang-x64 mode doesn't run clang, it just makes our parser compatible with it. Is that what you're referring to?

**Comment by lurium** [comment]
Yes, though I'm curious as to how you did this specifically.  

Is this behavior different if I run VSCode from linux?

Thank you

**Comment by sean-mcmanus** [comment]
@lurium clang-x64 mode theoretically should behave the same on Windows and Linux, but parts of our code are compiled differently and use different library implementations on Windows/Linux, so there may be unintended differences (i.e. bugs on a particular platform, just like any other feature).

**Comment by CoenraadS** [comment]
For people like me who run across this topic from google, see: https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md

**Comment by sus007** [comment]
### Although the **linter** seems to be working fine, I still couldn't get any *memberlist autocomplete, and quick info (tooltips)* features while writing C++. What might be the cause for this ?   
@bobbrow @sean-mcmanus @CoenraadS 

![bandicam-2017-12-26-17-36-07-889](https://user-images.githubusercontent.com/7630815/34356289-aaefb2fc-ea64-11e7-9147-ab8e0ef298ae.gif)

**Comment by galah92** [comment]
I'm having that exact problem with a `C` project.

Added a "c_cpp_properties.json" files with the exact config as above. No "launch.json" yet as I'm only interested in linting currently. I'm still getting the same message.

Running `($(get-appxpackage).PackageFamilyName | findstr /i 'SUSE Ubuntu') -replace '^', "$`{localappdata`}/Packages/"` in PowerShell yields nothing, though.

Windows 10 Creators Update (10.0.16299 Build 16299).
VSCode version 1.19.2.

What can be done?

**Comment by timothyr** [comment]
This is one of the top links from google, and the link is out of date.
Here's the most recent config and a little tutorial:

**1) Ctrl+Shift+P then type `C/Cpp: Edit Configurations`
2) Add the following to the config file:**
```
{
            "name": "WSL",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}",
                "${localappdata}/lxss/rootfs/usr/include/c++/5",
                "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                "${localappdata}/lxss/rootfs/usr/include/c++/5/backward",
                "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                "${localappdata}/lxss/rootfs/usr/local/include",
                "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu",
                "${localappdata}/lxss/rootfs/usr/include"
            ],
            "defines": [
                "__linux__",
                "__x86_64__"
            ],
            "browse": {
                "path": [
                    "${localappdata}/lxss/rootfs/usr/include/c++/5",
                    "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                    "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                    "${localappdata}/lxss/rootfs/usr/local/include",
                    "${localappdata}/lxss/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                    "${localappdata}/lxss/rootfs/usr/include/x86_64-linux-gnu",
                    "${localappdata}/lxss/rootfs/usr/include/*"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
```
**3) Ctrl+Shift+P then type `C/Cpp: Select a Configuration`
4) Select WSL**

Happy coding.

**Comment by bobbrow** [comment]
@timothyr can you clarify why you think the WSL documentation is out of date?  What you've posted looks like the "old" WSL config which is also in the documentation.

**Comment by timothyr** [comment]
@bobbrow I checked again and you're right, it's included. I missed it the first time because WSL has been out of beta for >9 months. Perhaps the labels should be switched. The current "Beta" instructions are working for the release, and the current "Release" instructions are deprecated.

**Comment by xemox** [comment]
@bobbrow Can you help me, why I'm still getting error after I select WSL config? 
![image](https://user-images.githubusercontent.com/5990702/36626355-db89f30e-1963-11e8-9014-c867cd91598d.png)

**Comment by ab37695543xs** [comment]
I use Ubuntu App for WSL with VSC, and I've followed [cpptools WSL](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md) but still have the problem "Include Error".
I've also checked the folders in Windows, and indeed there exists these files.
Did I missed something?

```
{
    "configurations": [
        {
            "name": "WSL",
            "intelliSenseMode": "clang-x64",
            "includePath": [
                "${workspaceRoot}",
                "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/5",
                "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/5/backward",
                "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include",
                "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu",
                "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include"
            ],
            "defines": [
                "__linux__",
                "__x86_64__"
            ],
            "browse": {
                "path": [
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/c++/5",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu/c++/5",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/local/include",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/x86_64-linux-gnu",
                    "${localappdata}/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/usr/include/*"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```
<a href="https://imgur.com/ij5bnqU"><img src="https://i.imgur.com/ij5bnqU.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/kDP7zQQ"><img src="https://i.imgur.com/kDP7zQQ.png" title="source: imgur.com" /></a>

**Comment by sean-mcmanus** [comment]
@ab37695543xs I'm not able to repro the issue with my WSL setup and your c_cpp_properties.json settings. I'm not sure what the difference is...maybe your WSL version and/or the compiler/libs installed? I have clang-3.9 installed. If you install the insiders build (cpptools-win32.vsix at https://github.com/Microsoft/vscode-cpptools/releases/download/v0.16.0-insiders/ ) it will have more logging (the "sending compilation args" output) if you temporarily set the loggingLevel to the hidden value of "6", but the new compilerPath option doesn't work on Windows or WSL with that version (actually, WSL-basec compilerPath got post-poned till April, but Windows-based clang/gcc should work for March).

**Comment by ab37695543xs** [comment]
Ok, I installed the LLVM 6.0.0 in Windows and added the following to my VSC user settings.
Howerver, it seems not working, do I need to add any other setting or install somthing else?
Or... maybe I should install clang in WSL?
<img src="https://i.imgur.com/jLzEUcB.png" width=70%>
<img src="https://i.imgur.com/62hLzH2.png" width=40%>

**Comment by bobbrow** [comment]
@ab37695543xs, are you using a Windows Insiders build?  We are tracking another WSL issue that looks similar to yours here: #1694

**Comment by ab37695543xs** [comment]
@bobbrow Yes, I'm using Windows Insider 17115, too
