### ISSUE TITLE
Detect/fix *Explicit properties appearing in c_cpp_properties.json

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7100]
After HOURS of debugging, including attempting your repro and then confused about why I couldn't get my larger project to behave like that, I FINALLY though sheer luck noticed this: 
![image](https://user-images.githubusercontent.com/41658770/109776682-b6245c80-7bb7-11eb-8020-a35be029050d.png)

It seems some rogue settings that never worked (as far as I can recall) but from another time have broken this. Removing these lines fixes the problem. I have no idea what those settings mean(t) and whether they are obsoleted, or just disallowed with clang, or whatever.

I believe those lines were autogenerated.
VERY confusing. So anyway, I deleted them. This seemed to fix the problem mostly.

EXCEPT that for the nlohmann_json library in particular, the squiggles CAME BACK after 5 minutes. It wasn't REALLY fixed.

In the repro I did, a very simple cmake project from scratch as you recommended, I copied over this subdir and it works fine. But in my larger project it just refuses to work.

I'm combing through everything trying to debug this. At this point, my C++ configurations file looks the same between the two, and so does everything else. So I'm completely stuck. I have NO IDEA why these random bugs just keep popping up each time and it takes days or even weeks to figure it all out. Again, FAR too many moving parts. It seems like tens or hundreds of things could affect it. I'm sure it's more like 30 things. But that's 26 or 27 things too much.

I'll continue to pull my hair out until I can find the source of the problem.

At the moment, I'm fresh out of ideas. I've copied over the EXACT clang configuration from my c_cpp_properties.json file in the simple repro project into the bigger real project: no luck.

I've made sure that I am on the same CMake kits in both projects: no luck.

This is truly odd.

_Originally posted by @danielmrussell in https://github.com/microsoft/vscode-cmake-tools/issues/770#issuecomment-789536519_

**Comment by Colengms** [comment]
These are not added when a `c_cpp_properties.json` is created, or when editing the configuration via configuration UI.  Are we sure the user didn't add these manually, by copying contents from the results of Log Diagnostics?  Or, perhaps this was a bug that was fixed long ago, and the configuration is very old (as the user mentions, "settings that never worked (as far as I can recall) but _from another time_").

**Comment by sean-mcmanus** [comment]
Are you able to repro the bug when they exist? I haven't tried yet. I think Bob was suggesting that fix that case.

**Comment by bobbrow** [comment]
My suggestion was that we should just extend this code in configurations.ts to delete the additional fields in case we ever see them:

```ts
            this.configurationJson.configurations.forEach(e => {
                if ((<any>e).knownCompilers) {
                    delete (<any>e).knownCompilers;
                    dirty = true;
                }
            });
```

**Comment by Colengms** [comment]
No, I have not been able to repro an issue.  These fields are dynamically set each time the related values are read and sent to the native process.  Even if they are set in `c_cpp_properties.json`, the values are replaced.  We can strip them from the `c_cpp_properties.json`, but I do not believe that would address any issue.

**Comment by bobbrow** [comment]
> No, I have not been able to repro an issue. [...] I do not believe that would address any issue.

Correct, we don't know how to repro this, but it would remove the problem squiggles for the odd cases where they were added (such as in the screenshot above).
