### ISSUE TITLE
No "VARIABLES" when debugging GTests with Test Explorer - Debugging not working after stopping on a breakpoint

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#7105]
Type: Debugger

**Describe the bug**
- OS and Version: MacOS BigSur 11.2.2
- VS Code Version: January 2021 (version 1.53)
- C/C++ Extension Version: 1.2.2
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Extension Pack, C++ TestMate, Test Explorer UI, etc.

**To Reproduce**

Debugging Google Test Unit Tests with Google Test:
1. Set a break point
2. Start debugging by clicking the bug icon in Test Explorer.

*Sometimes* when the breakpoint is hit - the VARIABLES pane is empty. The Call Stack is available usually (maybe even always). Unfortunately that is all the information I could provide.

![Screen Shot 2021-03-04 at 2 10 38 PM](https://user-images.githubusercontent.com/47526411/109962105-7bbfda00-7cf3-11eb-89d0-10ec5bfc87ca.png)

**Comment by WardenGnaw** [comment]
Which debugger are you using `cppdbg` or `cppvsdbg` and if possible can you provide logging by adding `"logging": { "engineLogging": true, "trace": true, "traceResponse": true }` in your `launch.json`

**Comment by H-G-Hristov** [comment]
@WardenGnaw I don't know about: `cppdbg` or `cppvsdbg`? How can I find that out? Also I am quite sure where to see the expected logs? I use the default "settings" if that's correct to say.

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [],
    "logging": {
        "engineLogging": true, 
        "trace": true, 
        "traceResponse": true
     }
}
```

**Comment by H-G-Hristov** [comment]
@sean-mcmanus Thanks for the tip. I changed my `launch.json` to:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "enter program name, for example ${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            // "logging": {
            //     "engineLogging": true,
            //     "trace": true,
            //     "traceResponse": true
            // }
        },
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "enter program name, for example ${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            // "logging": {
            //     "engineLogging": true,
            //     "trace": true,
            //     "traceResponse": true
            // }
        }
    ]
}
```

**Comment by H-G-Hristov** [comment]
I haven't experienced the described issue recently (maybe because I wasn't doing much debugging). Unfortunately as seen above I have just disabled the logging.
And just got the following, which seems that the locals are just partially displayed, incl. there is nothing in `this`, etc.
I am launching the debugging via the GTest extension: 

![Screen Shot 2021-03-16 at 11 40 01 AM](https://user-images.githubusercontent.com/47526411/111288891-46997d00-864d-11eb-931d-db1f3164f544.png)
![Screen Shot 2021-03-16 at 11 45 53 AM](https://user-images.githubusercontent.com/47526411/111288897-48634080-864d-11eb-96f3-746e1b0961e8.png)

So maybe this is a partial issue of the original issue?

**Comment by H-G-Hristov** [comment]
I generally experience a variety of issues when debugging on MacOS Big Sur. Like debugger shortcuts F12, F11 etc. seem to interfere with MacOS shortcuts. I don't get *step in* functionality, instead some MacOS functionality gets triggered.
The debugger appears to hang: clicking on the buttons *Continue (F5)* doesn't do anything, etc.
[VisualStudioCodeBigSur.log](https://github.com/microsoft/vscode-cpptools/files/6162696/VisualStudioCodeBigSur.log)

**Comment by H-G-Hristov** [comment]
One way the previously described hang happens is like that:

I click on *"Debug"* (as seen on the Screenshot) in the Test file:

![Screen Shot 2021-03-18 at 11 31 26 AM](https://user-images.githubusercontent.com/47526411/111604516-133a2800-87de-11eb-88e1-91941f50b1d6.png)

Then I click "Continue". The second breakpoint in another file (Source file) is hit:

![Screen Shot 2021-03-18 at 11 31 53 AM](https://user-images.githubusercontent.com/47526411/111604173-bb9bbc80-87dd-11eb-860d-cb312511ad09.png)

Then regardless what I click: *"Continue"*, *"Step in"*, etc. the debugger appears to hang. If I click *"Stop"*. I can place the next break point in the constructor itself and remove the second one to work around this.

I get a CPU meltdown again:

![Screen Shot 2021-03-18 at 11 40 02 AM](https://user-images.githubusercontent.com/47526411/111605189-c3a82c00-87de-11eb-81c9-6cbab532dced.png)

[MeltDown.log](https://github.com/microsoft/vscode-cpptools/files/6162899/MeltDown.log)

**Comment by H-G-Hristov** [comment]
Today I consistently once again I experience this issue. I have attached a log.

[debug.log.txt](https://github.com/microsoft/vscode-cpptools/files/6298674/debug.log.txt)
![Screen Shot 2021-04-12 at 8 37 19 PM](https://user-images.githubusercontent.com/47526411/114437222-ed325880-9bce-11eb-8f53-a321eb8ba08b.png)

**Comment by H-G-Hristov** [comment]
And the `lldb-mi` process is again using 100% CPU. This didn't happen for nearly a month.
![Screen Shot 2021-04-12 at 8 40 34 PM](https://user-images.githubusercontent.com/47526411/114437625-78abe980-9bcf-11eb-88d9-98b70deb822b.png)

**Comment by H-G-Hristov** [comment]
And again debugging doesn't actually work. After stopping on a breakpoint nothing but "Stop" works - continue, step, step over - don't do anything.

**Comment by H-G-Hristov** [comment]
@sean-mcmanus @WardenGnaw I noticed a pattern. If the debugging pane is opened - debugging fails. If the debugging panel is opened and I point over a variable I get to see its value. Then debugging works - I step to the next variable and if I open the debugging pane - I see the variables. Does this make any sense?

![Screen Shot 2021-04-13 at 10 16 57 AM](https://user-images.githubusercontent.com/47526411/114518846-7639a600-9c48-11eb-9472-cfa21a017098.png)

**Comment by hchxdu** [comment]
> 今天，我再次经历这个问题。我附上了一根圆木。
> 
> [debug.log.txt](https://github.com/microsoft/vscode-cpptools/files/6298674/debug.log.txt)
> ![屏幕截图 2021-04-12 晚上 8 37 19](https://user-images.githubusercontent.com/47526411/114437222-ed325880-9bce-11eb-8f53-a321eb8ba08b.png)

**Comment by H-G-Hristov** [comment]
New info here: https://github.com/microsoft/vscode-cpptools/issues/7105

**Comment by H-G-Hristov** [comment]
Continued here: https://github.com/microsoft/vscode-cpptools/issues/9831
