### ISSUE TITLE
Request: Show the selected C/C++ configuration more prominently

### ISSUE THREAD

**Issue by fstanchina** [microsoft/vscode-cpptools#7106]
**Type: LanguageService**

- OS and Version: Linux and Windows
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.2

We're using VSCode to work on a multiplatform C++ project.

We set up multiple configurations in `c_cpp_properties.json` and we connected `tasks.json` to the selected configuration, so we can build for the different platforms from within VSCode (previously we had to go to the console and explicitly `make TARGET=<platform>`).

This is very good, but the label in the status bar that's showing the active configuration is far too small and hard to see, especially as we're used to Visual Studio where the project configurations are prominently displayed in the toolbar. Also, the label disappears when the currently open file is not C/C++: it should always be visible if there's a `c_cpp_properties.json` file in this project.

Is there a way to show the current configuration in a more visible place, and possibly larger?

This might be considered a superset of issue #5822...

**Comment by sean-mcmanus** [comment]
The Makefile Tools extension at https://github.com/microsoft/vscode-makefile-tools appears to have a UI that will show the makefile target in the status bar.

There's no way to increase the size of elements in the status bar, but we could always show it (i.e. https://github.com/microsoft/vscode-cpptools/issues/5822), and/or add `[]` around the text.
