### ISSUE TITLE
Alternative operators (or, not) do not work with #if defined()

### ISSUE THREAD

**Issue by embedder72** [microsoft/vscode-cpptools#7108]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Win 10 18363
- VS Code Version: 1.54.0
- C/C++ Extension Version: V1.2.2
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The intellisense preprocessor is not handling the alternative operators 'or', 'not', and 'and'.

**Steps to reproduce**

Create a file temp.h and include the following.

```
#define DEFINE_B

#if defined(DEFINE_A) || defined(DEFINE_B)
    #define DEFINE_OR
#endif

#if defined(DEFINE_A) or defined(DEFINE_B)
    #define DEFINE_ALT_OR
#endif

#if defined(DEFINE_B) or defined(DEFINE_A)
    #define DEFINE_ALT_OR_2
#endif

#if !defined(DEFINE_OR)
    #error ("DEFINE_OR is not undefined")
#endif

#if not defined(DEFINE_C)
    #error ("DEFINE_C is not undefined")
#else
    #error ("Where is DEFINE_C defined?")
#endif

#if !defined(DEFINE_ALT_OR)
    #error ("DEFINE_ALT_OR is not undefined")
#endif

```

**Expected behavior**

**DEFINE_ALT_OR** should be defined
**not defined(DEFINE_C)** should evaluate to false

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/80073669/110041065-b9cbf680-7d11-11eb-9e47-487fe16be117.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
What compiler are you using? i.e. output of C/C++: Log Diagnostics should show. The cl.exe compiler doesn't compile that code unless C++20 is used. It would work if clang/gcc is used.

**Comment by embedder72** [comment]
I am using two compilers:

**IAR 8.40 (C++ with extensions)**

And GCC via WSL:
~/$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
**gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)**

**Comment by sean-mcmanus** [comment]
Our IntelliSense might be picking up a different compiler. What "IntelliSense Mode" do you see when you run the C/C++: Log Diagnostics command?

**Comment by embedder72** [comment]
**GCC**
-------- Diagnostics - 3/4/2021, 8:58:59 PM
Version: 1.2.2
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}

**IAR**
- I modified the output to shorten it and remove confidential names.
- -------- Diagnostics - 3/4/2021, 9:03:53 PM
Version: 1.2.2
Current Configuration:
{
    "name": "IAR",
    "defines": [
    ],
    "includePath": [
        "C:\\Users\\xxxx\\AppData\\Local\\Programs\\Microsoft VS Code",
        "C:\\Users\\xxxx\\AppData\\Local\\Programs",
        "C:\\Users\\xxxx\\AppData\\Local\\Programs\\inc",
        "C:\\Users\\xxxx\\AppData\\Local\\Programs\\Microsoft VS Code",
        "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.40.1\\arm\\inc",
        "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.40.1\\arm\\inc\\c",
        "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.40.1\\arm\\inc\\cpp"
    ],
    "forcedInclude": [],
    "cStandard": "c11",
    "cppStandard": "c++14",
    "compilerPath": "",
    "intelliSenseMode": "msvc-x64",
    "configurationProvider": "pluyckx.iar-vsc",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "C:\\Users\\xxxx\\AppData\\Local\\Programs\\Microsoft VS Code",
            "C:\\Users\\xxxx\\AppData\\Local\\Programs",
            "C:\\Users\\xxxx\\AppData\\Local\\Programs\\inc",
            "C:\\Users\\xxxx\\AppData\\Local\\Programs\\Microsoft VS Code",
            "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.40.1\\arm\\inc",
            "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.40.1\\arm\\inc\\c",
            "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.40.1\\arm\\inc\\cpp",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom configurations:
[ C:\git\yyyyy\main.cpp ]
{
    "compilerPath": "",
    "defines": [
    ],
    "includePath": [
        "C:\\Users\\xxxx\\AppData\\Local\\Programs\\Microsoft VS Code",
        "C:\\Users\\xxxx\\AppData\\Local\\Programs",
        "C:\\Users\\xxxx\\AppData\\Local\\Programs\\inc",
        "C:\\Users\\xxxx\\AppData\\Local\\Programs\\Microsoft VS Code",
        "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.40.1\\arm\\inc",
        "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.40.1\\arm\\inc\\c",
        "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.40.1\\arm\\inc\\cpp"
    ],
    "forcedInclude": [],
    "intelliSenseMode": "msvc-x64",
    "standard": "c++14"
}
Translation Unit Mappings:
[ C:\git\yyyyy\main.cpp ]:
    C:\GIT\YYYYY\HVPGPIOPINS.H
Translation Unit Configurations:
[ C:\git\yyyyy\main.cpp ]:
    Process ID: 14976
    Memory Usage: 72 MB
    Includes:
        C:\USERS\XXXX\APPDATA\LOCAL\PROGRAMS
        C:\USERS\XXXX\APPDATA\LOCAL\PROGRAMS\MICROSOFT VS CODE
        C:\PROGRAM FILES (X86)\IAR SYSTEMS\EMBEDDED WORKBENCH 8.40.1\ARM\INC
        C:\PROGRAM FILES (X86)\IAR SYSTEMS\EMBEDDED WORKBENCH 8.40.1\ARM\INC\C
        C:\PROGRAM FILES (X86)\IAR SYSTEMS\EMBEDDED WORKBENCH 8.40.1\ARM\INC\CPP
    Defines:
    Standard Version: ms_c++14
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 72 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 35272
Number of files discovered (not excluded): 30476

**Comment by sean-mcmanus** [comment]
The gcc case is missing out put (you need to open a file first). The other case shows an msvc IntelliSenseMode is incorrectly being used. Your configuration provider is sending the wrong intelliSenseMode (which those operators don't work with c++14).

**Comment by embedder72** [comment]
Thanks for the quick responses.  Here's the full output from GCC.

-------- Diagnostics - 3/4/2021, 9:20:59 PM
Version: 1.2.2
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom configurations:
[ /home/XXX/main.cpp ]
{
    "defines": [
        "TARGET_HVP_P2_1"
    ],
    "standard": "gnu++14",
    "includePath": [
        "/home/XXXX/src",
    ],
    "intelliSenseMode": "gcc-x64",
    "compilerPath": "/bin/g++-9",
    "compilerArgs": [
        "-Werror",
        "-Wall",
        "-Wextra",
        "-Wfloat-equal",
        "-Wswitch-default",
        "-Wunreachable-code",
        "-g",
        "-std=gnu++14"
    ]
}
Translation Unit Mappings:
[ /home/XXX/main.cpp ]:
    /home/XXX/main.cpp
Translation Unit Configurations:
[ /home/XXX/main.cpp ]:
    Process ID: 3463
    Memory Usage: 177 MB
    Compiler Path: /bin/g++-9
    Includes:
        /usr/include/c++/9
        /usr/include/x86_64-linux-gnu/c++/9
        /usr/include/c++/9/backward
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Defines:
        TARGET_HVP_P2_1
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=90300
Total Memory Usage: 177 MB
Browse Paths from compile_commands.json, from workspace folder: /home/aaquino/xxxx
------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 5646
Number of files discovered (not excluded): 5400

**Comment by sean-mcmanus** [comment]
Seems like the gcc case should work -- I'll investigate tomorrow.

**Comment by embedder72** [comment]
I re-evaluated under GCC and it does evaluate correctly.  I'll try a different configuration when using the IAR compiler.

Thank you.
