### ISSUE TITLE
No documentation for simplest possible Mac C/C++ project

### ISSUE THREAD

**Issue by peterwoods1** [microsoft/vscode-cpptools#711]
For Mac users, cpptools suffers from a lack of documentation for someone trying to get started.

I've created a github repo with a simple project that works (provided XCode is installed):
https://github.com/peegee123/vscode-mac-c-example

I'm sure cpptools would attract more users if the docs were updated to include simple projects like mine for all platforms.

**Comment by pieandcakes** [comment]
@peterwoods1 We are hoping the community can help contribute to our repo here with samples and documentation. Our team is small and we're also working on other projects so we will try and contribute when possible. 

What is causing the XCode dependency?

**Comment by peterwoods1** [comment]
Sure - it makes sense for the developer community to help.

I don't believe that cpptools installs the C/C++ header files, whereas XCode does install them, hence the dependency.

**Comment by pieandcakes** [comment]
Yea, we provide a debugger and a language service I would assume that you would acquire the compiler and the header files separately. 

If you want to write a quick Pull request with a link to your example in this repo we can certainly do that or if you want to contribute directly to this repo that's fine too.

**Comment by bobbrow** [comment]
We have some new documentation available for various platforms.  macOS is [here](https://code.visualstudio.com/docs/cpp/config-clang-mac)
