### ISSUE TITLE
Default C++ standard is not changing to C++17

### ISSUE THREAD

**Issue by 0Ky** [microsoft/vscode-cpptools#7110]
Type: General

### Describe the bug
- **OS and Version**: Microsoft Windows 10 Pro, v10.0.19042 Build 19042
- **VS Code Version**: v1.54.1 (user setup) Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
- **C/C++ Extension Version**: ms-vscode.cpptools v1.2.2
- **Other extensions you installed (and if the issue persists after disabling them)**: Persists after disabling
- **A clear and concise description of what the bug is**: Changing `C_Cpp › Default: 𝗖𝗽𝗽 𝗦𝘁𝗮𝗻𝗱𝗮𝗿𝗱` from extension settings to '_C++17_' does not change compiler's C++ standard version when I '_run and debug_' from VSCode using C++(Windows) environment and cl.exe compiler.

### To Reproduce
1. Make sure you have installed the following [prerequisites](https://code.visualstudio.com/docs/cpp/config-msvc#_prerequisites): **Visual Studio Code**, **C/C++ extension for VS Code** and **Microsoft Visual C++ (MSVC) compiler toolset**.
2. Open VSCode
3. Open extensions (CTRL+SHIFT+X) then go to `C/C++ Extension Settings` by clicking the cog icon
4. In the search bar lookup "standard"
5. Edit `C_Cpp › Default: 𝗖𝗽𝗽 𝗦𝘁𝗮𝗻𝗱𝗮𝗿𝗱` change from default to **C++17**
6. Exit VScode
7. Open 'Developer Command Prompt for VS 2019' (VsDevCmd.bat)
8. Create a new folder and cd (change directory) into it (using developer command prompt, not regular CMD)
9. Type `code .` to open VSCode in current directory
10. Create a new `.cpp` file
11. Paste the following code:
```C++
#include <iostream>

int main()
{
    std::cout << _MSVC_LANG << std::endl;
    return 0;
}
```
12. Go to 'Run and Debug' (CTRL+SHIFT+D), click Run and Debug button
13. Select `C++ (Windows)` environment
14. Select `cl.exe - Build and debug active file`

### Expected behavior
The program should output **201703**, indicating `C++17` standard is being used.

### Current behavior
The program outputs **201402**

### Additional context
The following files are created under `.vscode` folder:

_tasks.json_
```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: cl.exe build active file",
            "command": "cl.exe",
            "args": [
                "/Zi",
                "/EHsc",
                "/nologo",
                "/Fe:",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "${file}"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$msCompile"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

_launch.json_
```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "cl.exe - Build and debug active file",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "console": "externalTerminal",
            "preLaunchTask": "C/C++: cl.exe build active file"
        }
    ]
}
```

**Comment by 0Ky** [comment]
I'm assuming that the extension does not add **/std:c++17** into args when you select C++17 from `Cpp Standard` through extension settings.

**Comment by sean-mcmanus** [comment]
The cppStandard setting only affects IntelliSense and not build tasks. They are 2 completely different systems controlled by 2 different json files.
