### ISSUE TITLE
Doesn't see C++ includes even if code compiles without errors

### ISSUE THREAD

**Issue by nexeleriot** [microsoft/vscode-cpptools#7113]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Fedora 33
- VS Code Version: 1.52.1
- C/C++ Extension Version: 1.2.2
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I use gtkmm in my C++ code and all gtkmm includes could not be found by IntelliSense, e. g.:
`#include <gtkmm/headerbar.h>`
Message (in translation):
cannot open source file "gtkmm/headerbar.h" 

Gtkmm is installed with dnf. Code compiles and runs without any errors or warnings

**Steps to reproduce**

1. Write C++ code with gtkmm
2. Include any gtkmm file
3. Include is underlined and autocompletion doesn't work

**Expected behavior**

No errors and autocompletion

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 05.03.2021, 17:32:37
Version: 1.2.2
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "c++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/nexeleriot/Prog/TestCpp/src/testcpp-window.cpp ]:
    /home/nexeleriot/Prog/TestCpp/src/testcpp-window.h
Translation Unit Configurations:
[ /home/nexeleriot/Prog/TestCpp/src/testcpp-window.cpp ]:
    Process ID: 271401
    Memory Usage: 10 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/10
        /usr/include/c++/10/x86_64-redhat-linux
        /usr/include/c++/10/backward
        /usr/lib/gcc/x86_64-redhat-linux/10/include
        /usr/local/include
        /usr/include
        /home/nexeleriot/Prog/TestCpp/src
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=100201
Total Memory Usage: 10 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 6378
Number of files discovered (not excluded): 6109


```
</details>

**Screenshots**

![Снимок экрана от 2021-03-05 17-34-23](https://user-images.githubusercontent.com/70663363/110129620-3544ab00-7dd9-11eb-9569-43bf5346c298.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
Did you add the path to gtkmm to your includePath setting?

**Comment by nexeleriot** [comment]
OK, it works after I added some paths from pkg-config
Now there is another question: is there a way to use pkg-config with IntelliSense automatically?

**Comment by sean-mcmanus** [comment]
I'm not familiar with pkg-config. Did you have a suggestion on how we could make IntelliSense work with pkg-config automatically? We have some support for automatic configuring for vcpkg and node-addon-api.

@bobbrow @jureid @Colengms Anyone else know?

**Comment by nexeleriot** [comment]
Maybe something like a json property with library names, so IntelliSense could use output of `pkg-config lib_name --cflags-only-I` command, which prints paths to header files

**Comment by sean-mcmanus** [comment]
I tried it with several libraries but I just a blank output. Do you know a lib_name that prints a path or am I doing something wrong?

**Comment by nexeleriot** [comment]
`pkg-config gtkmm-3.0 --cflags-only-I`
Maybe you don't have dev packages of this libs in your system?

**Comment by sean-mcmanus** [comment]
Okay, I got the command to work. It seems like you should be able to use
```
"compilerArgs": [ "`pkg-config --libs --cflags gtkmm-3.0`"]
```
but we don't currently support the backquotes -- we can convert this issue to that feature request or create a new issue to track supporting the backquotes.

**Comment by sean-mcmanus** [comment]
Looks like that is already being tracked by https://github.com/microsoft/vscode-cpptools/issues/6773
