### ISSUE TITLE
Feature Request: Allow outline panel to show access specifier (i.e. private, public, protected)

### ISSUE THREAD

**Issue by YalandHong** [microsoft/vscode-cpptools#7120]
I found #3117 and microsoft/vscode#113845 discussing similar problem. Actually I only want some extra small, grey text showing `private` or `public` beside the names of class members, just like what "declaration" does now.

**Screenshots**
![Screenshot from 2021-03-05 21-02-02](https://user-images.githubusercontent.com/52960068/110207413-487d7680-7ebe-11eb-8d26-1a3b6ff93225.png)

Displaying other keywords, such as `override`, `virtual` would also be helpful.

_Originally posted by @YalandHong in https://github.com/microsoft/vscode-cpptools/discussions/7112_

**Comment by sean-mcmanus** [comment]
Looks like the private/public data isn't immediately available with our current implementation so we'd have to investigate how to get that from our database.

**Comment by HO-COOH** [comment]
It's kind of related to #1955 

In VS, there will be a lock icon on private/protected member, in both the object view and the auto completion pop-up.
![image](https://user-images.githubusercontent.com/42881734/118606344-dee8e500-b7e9-11eb-9eaf-68033af3487d.png)

Would be nice to see in vscode too.

**Comment by sean-mcmanus** [comment]
@HO-COOH Thanks for you comment -- it made me realize that VS had it, so the data must be easily obtainable in our database, and I was able to locate it when I looked again.

![image](https://user-images.githubusercontent.com/19859882/118903418-9b1adc00-b8cc-11eb-9bf7-f1f08db5119b.png)

Icons are being tracked by https://github.com/microsoft/vscode/issues/113845

**Comment by sean-mcmanus** [comment]
private/protected labels are shown with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders3 (public is the default and is not shown).

**Comment by sean-mcmanus** [comment]
FYI, this only works in the definition of the class/struct, and the modifiers don't appear in the implementation of methods that are in a separate .cpp file (handling that case would probably be a VS bug since they don't even support that).
