### ISSUE TITLE
vcFormat: Wrong next-line indentation for braces

### ISSUE THREAD

**Issue by Leopard20** [microsoft/vscode-cpptools#7125]
When I go to the next line after a function/class/if, etc., the autocompletion adds an extra indent in the next line.
This is fine. But when I type `{`, it is expected that this indent be removed (like VS 2019) to prevent indentation issues.

VSCode cpp tools:
![rec](https://user-images.githubusercontent.com/16115820/110262878-44d71600-7fca-11eb-9c29-b436712f287c.gif)

Visual Studio 2019:
![rec1](https://user-images.githubusercontent.com/16115820/110262882-46a0d980-7fca-11eb-8bf2-206377088328.gif)

If you look closely at both videos, you can notice that VS2019 removes the indent as soon as I type `{`, whereas in VSCode this happens after I press `Enter` and thus causes a misplaced indent.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. A fix should be in our next release (unless we find a reason to revert it).

FYI, I noticed the ";" is not added after the "}" -- I filed an issue on VS Code for potentially fixing that: https://github.com/microsoft/vscode/issues/118577

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders . Let us know if you notice any other issues in regards to the format on type behavior.

**Comment by michelleangela** [comment]
Fix is released in the 1.3.0 release version https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0
