### ISSUE TITLE
Real-time code linting feedback not working properly for C++ code.

### ISSUE THREAD

**Issue by hssaluja25** [microsoft/vscode-cpptools#7126]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `1.2.2`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.54.1`

When working on C++ files, the red squiggly lines are not highlighting syntax errors I make in my code. However, syntax errors I make in the preprocessor directive are being highlighted.
![Bug](https://user-images.githubusercontent.com/75522742/110275732-a5c91300-7ff7-11eb-9f85-3322ab0a731f.jpg)
![Bug2](https://user-images.githubusercontent.com/75522742/110275509-2d625200-7ff7-11eb-92a9-92921836eda5.jpg)
### What have I tried?

- I deleted all my VSCode settings as someone said that they might be interfering with the extension.

- I also tried reinstalling the C/C++ Extension by Microsoft. (I uninstalled the C/C++ extension, restarted VSCode and installed the extension again.)

- I uninstalled VSCode and then reinstalled it.

**Comment by sean-mcmanus** [comment]
Error squiggles are intentionally disabled in the Open File scenario. Did you Open a Folder?

**Comment by hssaluja25** [comment]
No, I did not open a folder. Since error squiggles work when I Open Python files, I thought that they might work with C++ too.  Anyways, opening a folder brings back linting feedback.
Thank you so much for resolving this.
