### ISSUE TITLE
Directories specified with -idirafter are included too early

### ISSUE THREAD

**Issue by davidwin** [microsoft/vscode-cpptools#7129]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.54.1
- C/C++ Extension Version: 1.2.2 (but has been an issue for a while back)
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes, to a Linux host

When the `compile_commands.json` file contains an `-idirafter` option, that directory will not be searched after all system includes (e.g. `/usr/include`), which is the gcc and clang behavior. This will lead to various discrepancies between IntelliSense and actual compilation.

**Steps to reproduce**
1. Create a file `source.c` with contents:
```C++
#include <stdio.h>

int main()
{
  printf("FAKE_STDIO is %d", FAKE_STDIO);
}
```
2. Create a file `stdio.h` (yes) in a separate directory `fake`:
```C++
#define FAKE_STDIO 42
```
3. Verify that if you build `source.c` with `gcc -idirafter foo source.c`, you get an error stating that `FAKE_STDIO` is undefined.
4. Create a `compile_commands.json` file for `source.c` with the command line above as the `command` property and point `compileCommands` in `.vscode/c_cpp_properties.json` to it:
```json
[
  {
    "command": "gcc -idirafter /my/path/foo source.c",
    "directory": "/my/path",
    "file": "source.c"
  }
]
```
5. Open `source.c` in VS Code

**Expected behavior**
The IntelliSense diagnostic should be the same as the gcc diagnostic, that is `FAKE_STDIO` is undefined. Because `stdio.h` is an existing system include, it will not be included although the directory containing the fake version was specified with `-idirafter`.

**Actual behavior**
The IntelliSense diagnostic will state that `printf` is undefined instead, indicating that the fake version of `stdio.h` was included before the system version.

**Reference**
See the [gcc Options for Directory Search documentation](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html#Directory-Options).

**Comment by sean-mcmanus** [comment]
Thanks for reporting this.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders

**Comment by davidwin** [comment]
Thanks, IntelliSense is working great now!
