### ISSUE TITLE
Breakpoints sometimes not synced between GDB and VSCode

### ISSUE THREAD

**Issue by kanflo** [microsoft/vscode-cpptools#713]
I found that sometimes BPs are not synced between GDB and VS Code. My "BREAKPOINTS" pane is empty, yet the command ```-exec info breakpoints``` yields the following:

```
Num     Type           Disp Enb Address    What
1       breakpoint     keep y   0x08000152 in main at main.c:33
    breakpoint already hit 1 time
2       breakpoint     keep y   0x08000152 in main at main.c:33
    breakpoint already hit 1 time
```

Running the latest released versions of VSCode and cpptools.

**Comment by pieandcakes** [comment]
@kanflo Do you have a good way to repro this? Which version of gdb are you running and which OS?

**Comment by kanflo** [comment]
Hi @pieandcakes. Sorry but no, I have tried to reproduce but in vain. I use the ```Version 6-2017-q1-update``` downloaded from [ARM](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads) using macOS.

**Comment by ghost** [comment]
Hi @pieandcakes. I have the same problem. I am running VSCode 1.16.0 and the C/C++ extension 0.12.4 on a Windows computer. I have the ARM compiler 2017 q2 update, and I am using the SEGGER J-Link GDB server.
Breakpoints are not hit when I set them, and the breakpoint list in VSCode is different from that given by exec info breakpoints.
Can you help?

**Comment by pieandcakes** [comment]
@treesaregreen Can you tell me what is different? There may be one extra one from 'info breakpoints' for the one we set. You can also enable the logging block if you want to see what we call gdb with and what we get back. If you set breakpoints through the command line, they will not show up in the UI.

**Comment by ghost** [comment]
Hi @pieandcakes. Thank you for your very quick reply!!

Actually, I think the problem may lie between user and keyboard. I did a clean build of my software and reflashed the target to be sure that the debugger and flashed code are in sync, and now it hits breakpoints as it should.

Thank you again for your help and for helping to develop such a good tool.

To help anyone who lands here trying to get VSCode + cpptools working with an ARM target, here is my launch.json

```
{
   // Use IntelliSense to learn about possible attributes.
   // Hover to view descriptions of existing attributes.
   // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
   "version": "0.2.0",
   "configurations": [
      {
         "name": "Debug",
         "type": "cppdbg",
         "request": "launch",
         "miDebuggerPath": "E:/tools/gcc-arm-none-eabi-6-2017-q2-update-win32/bin/arm-none-eabi-gdb.exe",
         "targetArchitecture": "arm",
         "program": "${workspaceRoot}/Application/Application.axf",
         "cwd": "${workspaceRoot}",
         "externalConsole": false,
         "stopAtEntry": false,
         //"logging": { "trace": true, "traceResponse": true, "engineLogging": true },
         "MIMode": "gdb",
         "setupCommands": [
            { "text": "target remote :2331" },
            { "text": "monitor reset init" }
         ]
      }
      ]
}
```
