### ISSUE TITLE
${env:XXX} gives invalid warnings when used in intelliSenseMode

### ISSUE THREAD

**Issue by aivazis** [microsoft/vscode-cpptools#7133]
**Type: LanguageService**

I would like to be able to use environment variable expansions in more places. As an example, I have attached a snippet from my c_cpp_properties.json, which uses information from the environment to improve the way the editor integrates with my build procedure. There are obvious workarounds, but they all involve manual expansion and multiple almost entirely identical configuration sections.

```
{
"configurations": [
{
"name": "macports - mm",
"includePath": [
"${workspaceFolder}/",
"${env:USER_TOOLS_DIR}/mm/${env:mm_bld_abi}/include/",
"/opt/local/include/**"
],
"defines": [],
"macFrameworkPath": [
"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
],
"compilerPath": "/opt/local/bin/${env:mm_bld_compiler}",
"cStandard": "c17",
"cppStandard": "c++17",
"intelliSenseMode": "macos-${env:mm_bld_compiler}-arm64"
}
],
"version": 4
}
```
In this example, intelliSenseMode complains that the setting is not in the approved set, clearly because it doesn't perform the ${env:XXX} expansion before comparing the supplied value against the canonical set.

**Comment by sean-mcmanus** [comment]
Yeah, I see the squiggle give a warning due to the property being an enum in our package.json, but I see it working/expanding the variable anyway. Is the warning the only issue you're seeing? Are any other properties causing an issue for you?

**Comment by aivazis** [comment]
Hmm... I guess I assumed that the warning was an indication that my setting is ignored. But perhaps that's because I don't understand the mechanism by which the extension selects the configuration. I'm very new to this, so i'm not sure what, if anything, are the consequences of the warning. I'll go read the documentation so i can calibrate my expectations and get back to you

Thanks for taking the time to check on this

**Comment by sean-mcmanus** [comment]
I think you can ignore the warning. We could probably fix the issue via changing the setting's type to string instead of enum and then adding our own custom error checking to see if the value is valid after the variable in the setting have been resolved.

**Comment by aivazis** [comment]
Thanks for the help. Just out of curiosity, what do you do with the value of this variable? What actual functional effect does it have in the operation of the extension?

**Comment by sean-mcmanus** [comment]
By "this variable" do you mean the intelliSenseMode? That tells our parser which <platform>-<compler>-<architecture> it should emulate, e.g. windows-msvc-x64 or linux-clang-arm64, etc.

**Comment by aivazis** [comment]
I get that from the set of possible values. I was hoping to find out what difference this information makes to the extension. For example, what fails to work correctly if the value is not set to the correct value.

**Comment by sean-mcmanus** [comment]
IntelliSense can give many incorrect results if the intelliSenseMode is incorrect, particularly showing invalid squiggles. Having an msvc versus clang or gcc compiler will cause the big difference since the compilers behave differently (clang and gcc are usually the same, but they diverge in some cases, such as built-in intrinsics and language extensions). The platform and architecture can affect the size of builtin data types and defines, see for example: https://github.com/microsoft/vscode-cpptools/blob/main/Extension/bin/macos.gcc.x86.json .
