### ISSUE TITLE
Unable to use gdb as debugger on macOS

### ISSUE THREAD

**Issue by aniervs** [microsoft/vscode-cpptools#7135]
Type: Debugger

**Describe the bug**
- OS and Version: macOS Catalina 10.15.3
- VS Code Version: 1.52.0
- C/C++ Extension Version: v1.2.2

I'm compiling C++ with g++, and naturally I'm trying to use gdb as debugger instead of lldb. I already installed gdb, but when I set it on the `launch.json` file and try to debug, it shows me the following error:
```Unable to start debugging. GDB exited unexpectedly with exit code 134 (0x86).```

Here is a copy of my `launch.json` file:
```

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++-10 - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/local/bin/gdb",
            "preLaunchTask": "C/C++: g++-10 build active file"
        }
    ]
}

```

**Comment by WardenGnaw** [comment]
The error 
> Unable to start debugging. GDB exited unexpectedly with exit code 134 (0x86)

indicates that GDB does not have the permissions to debug your process. Because GDB is obtained via different ways and not by apple itself, you will have to ensure you have given it entitlements and self signed it.

You can check to see if it is signed by running:
```
codesign -dv --verbose=4 /path/to/gdb
codesign -d --entitlements :- /path/to/gdb
```

Here is GDB's documentation on setting GDB up on Darwin: https://sourceware.org/gdb/wiki/PermissionsDarwin

**Comment by aniervs** [comment]
I already signed it and gave it the entitlements. It's still not working with the same error.

**Comment by aniervs** [comment]
Please, any help?!

**Comment by aniervs** [comment]
The Debug console shows this:
`1: (125) LaunchOptions{"name":"g++-10 - Build and debug active file","type":"cppdbg","request":"launch","program":"/Users/aniervs/test/A","args":[],"stopAtEntry":false,"cwd":"/Users/aniervs/test","environment":[],"externalConsole":true,"MIMode":"gdb","miDebuggerPath":"/usr/local/bin/gdb","logging":{"engineLogging":true},"preLaunchTask":"C/C++: g++-10 build active file","__configurationTarget":5,"__sessionId":"49a81a6e-7b12-4ca2-b227-94393f02df3e"}
1: (223) codeSign-stderr: Executable=/usr/local/Cellar/gdb/10.1_1/bin/gdb
1: (231) Starting: "/usr/local/bin/gdb" --interpreter=mi
1: (245) DebuggerPid=26623
1: (299) ->=thread-group-added,id="i1"
1: (300) ->~"GNU gdb (GDB) 10.1\n"
1: (300) ->~"Copyright (C) 2020 Free Software Foundation, Inc.\n"
1: (301) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
1: (301) ->~"\nType \"show copying\" and \"show warranty\" for details.\n"
1: (301) ->~"This GDB was configured as \"x86_64-apple-darwin19.6.0\".\n"
1: (301) ->~"Type \"show configuration\" for configuration details.\n"
1: (301) ->~"For bug reporting instructions, please see:\n"
1: (303) ->~"<https://www.gnu.org/software/gdb/bugs/>.\n"
1: (303) ->~"Find the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>."
1: (303) ->~"\n\n"
1: (303) ->~"For help, type \"help\".\n"
1: (303) ->~"Type \"apropos word\" to search for commands related to \"word\".\n"
1: (303) ->=cmd-param-changed,param="startup-with-shell",value="off"
1: (303) ->(gdb)
1: (307) <-1001-gdb-set target-async on
1: (308) ->1001^done
1: (308) ->(gdb)
1: (309) 1001: elapsed time 2
1: (318) <-1002-interpreter-exec console "set pagination off"
1: (318) ->=cmd-param-changed,param="pagination",value="off"
1: (318) ->1002^done
1: (318) ->(gdb)
1: (318) 1002: elapsed time 0
1: (318) <-1003-gdb-set auto-solib-add on
1: (318) ->1003^done
1: (318) ->(gdb)
1: (318) 1003: elapsed time 0
1: (319) <-1004-gdb-set solib-search-path /Users/aniervs/test:
1: (319) ->1004^done
1: (319) ->(gdb)
1: (319) 1004: elapsed time 0
1: (319) <-1005-environment-cd /Users/aniervs/test
1: (319) ->1005^done
1: (319) ->(gdb)
1: (319) 1005: elapsed time 0
1: (319) <-1006-file-exec-and-symbols /Users/aniervs/test/A
1: (323) ->~"../../gdb/thread.c:95: internal-error: struct thread_info *inferior_thread(): Assertion `current_thread_ != nullptr' failed.\nA problem internal to GDB has been detected,\nfurther debugging may prove unreliable."
1: (323) ->~"\nQuit this debugging session? "
1: (323) ->~"(y or n) [answered Y; input not from terminal]\n"
1: (323) ->&"\nThis is a bug, please report it."
1: (323) ->&"  For instructions, see:\n"
1: (323) ->&"<https://www.gnu.org/software/gdb/bugs/>.\n\n"
1: (323) ->~"../../gdb/thread.c:95: internal-error: struct thread_info *inferior_thread(): Assertion `current_thread_ != nullptr' failed.\nA problem internal to GDB has been detected,\nfurther debugging may prove unreliable."
1: (323) ->~"\nCreate a core file of GDB? "
1: (323) ->~"(y or n) [answered Y; input not from terminal]\n"
1: (340) "/usr/local/bin/gdb" exited with code 134 (0x86).
1: (343) <-logout
1: (355) Send Event AD7MessageEvent
1: (356) Send Event AD7ProgramDestroyEvent
The program '/Users/aniervs/test/A' has exited with code 42 (0x0000002a).
`

**Comment by petioptrv** [comment]
Trying to solve this as well. Post if you find a solution, please.

**Comment by jbecca** [comment]
I have the same issue. I have attached screenshots showing that GDB simply runs without asking any permissions when started from a terminal. I have also attached the output of the two codesign commands that were pasted above in case this helps hunting this bug down. 
![Screen Shot 2021-05-31 at 10 23 19 AM](https://user-images.githubusercontent.com/16378139/120207366-53fce700-c1fa-11eb-9960-924a9cb82248.png)
![Screen Shot 2021-05-30 at 7 58 43 PM](https://user-images.githubusercontent.com/16378139/120206825-aab5f100-c1f9-11eb-918f-b976b7edbc8f.png)
![Screen Shot 2021-05-30 at 7 56 36 PM](https://user-images.githubusercontent.com/16378139/120206836-aee20e80-c1f9-11eb-9f12-74fbe128758b.png)

**Comment by jbecca** [comment]
If it helps at all, I attempted to use many different older versions of the C++ extension and received the same error message. I then created and signed an entirely separate certificate. When I did, running GDB in my terminal asked me for the following prompt:
![Screen Shot 2021-05-31 at 11 12 38 AM](https://user-images.githubusercontent.com/16378139/120213829-ae4d7600-c201-11eb-858b-d0c195c3a5ae.png)

After typing in my credentials, I was able to get GDB working in my terminal. However, I still cannot get it to work inside of VSCode.

**Comment by jbecca** [comment]
I have now tried upgrading GDB from 10.1 to 10.2 and resigned it. Once again, I can run gdb in a terminal, but not in visual studio code.

**Comment by aniervs** [comment]
> I have now tried upgrading GDB from 10.1 to 10.2 and resigned it. Once again, I can run gdb in a terminal, but not in visual studio code. Here are some logs for the debugger if they help.
> 
> `--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (129) LaunchOptions{\"name\":\"Fortran Launch (gdb)\",\"type\":\"cppdbg\",\"request\":\"launch\",\"program\":\"/Users/jeffreybecca/Projects/nwchem-myfork/bin/MACX64/nwchem\",\"args\":[\"/Users/jeffreybecca/Projects/nwchem-myfork/QA/tests/dimqm_spe_uhf/dimqm_spe_uhf.nw\"],\"stopAtEntry\":false,\"cwd\":\"/Users/jeffreybecca/Projects/nwchem-myfork\",\"environment\":[],\"externalConsole\":false,\"MIMode\":\"gdb\",\"miDebuggerPath\":\"/usr/local/bin/gdb\",\"logging\":{\"trace\":true,\"traceResponse\":true,\"engineLogging\":true},\"__configurationTarget\":5,\"__sessionId\":\"a898a4b1-5df7-4efb-a4c8-0788022e4bcc\"}\n"},"seq":2} 1: (129) LaunchOptions{"name":"Fortran Launch (gdb)","type":"cppdbg","request":"launch","program":"/Users/jeffreybecca/Projects/nwchem-myfork/bin/MACX64/nwchem","args":["/Users/jeffreybecca/Projects/nwchem-myfork/QA/tests/dimqm_spe_uhf/dimqm_spe_uhf.nw"],"stopAtEntry":false,"cwd":"/Users/jeffreybecca/Projects/nwchem-myfork","environment":[],"externalConsole":false,"MIMode":"gdb","miDebuggerPath":"/usr/local/bin/gdb","logging":{"trace":true,"traceResponse":true,"engineLogging":true},"__configurationTarget":5,"__sessionId":"a898a4b1-5df7-4efb-a4c8-0788022e4bcc"} --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (238) codeSign-stderr: Executable=/usr/local/Cellar/gdb/10.2/bin/gdb\n"},"seq":4} 1: (238) codeSign-stderr: Executable=/usr/local/Cellar/gdb/10.2/bin/gdb --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (245) Starting: \"/usr/local/bin/gdb\" --interpreter=mi\n"},"seq":6} 1: (245) Starting: "/usr/local/bin/gdb" --interpreter=mi --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (261) DebuggerPid=6775\n"},"seq":8} 1: (261) DebuggerPid=6775 --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (323) ->=thread-group-added,id=\"i1\"\n"},"seq":10} 1: (323) ->=thread-group-added,id="i1" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (324) ->~\"GNU gdb (GDB) 10.2\\n\"\n"},"seq":12} 1: (324) ->~"GNU gdb (GDB) 10.2\n" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (325) ->~\"Copyright (C) 2021 Free Software Foundation, Inc.\\n\"\n"},"seq":14} 1: (325) ->~"Copyright (C) 2021 Free Software Foundation, Inc.\n" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (325) ->~\"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\\nThis is free software: you are free to change and redistribute it.\\nThere is NO WARRANTY, to the extent permitted by law.\"\n"},"seq":16} 1: (325) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law." --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (325) ->~\"\\nType \\\"show copying\\\" and \\\"show warranty\\\" for details.\\n\"\n"},"seq":18} 1: (325) ->~"\nType \"show copying\" and \"show warranty\" for details.\n" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (325) ->~\"This GDB was configured as \\\"x86_64-apple-darwin20.3.0\\\".\\n\"\n"},"seq":20} 1: (325) ->~"This GDB was configured as \"x86_64-apple-darwin20.3.0\".\n" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (325) ->~\"Type \\\"show configuration\\\" for configuration details.\\n\"\n"},"seq":22} 1: (325) ->~"Type \"show configuration\" for configuration details.\n" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (325) ->~\"For bug reporting instructions, please see:\\n\"\n"},"seq":24} 1: (325) ->~"For bug reporting instructions, please see:\n" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (325) ->~\"<https://www.gnu.org/software/gdb/bugs/>.\\n\"\n"},"seq":26} 1: (325) ->~"<https://www.gnu.org/software/gdb/bugs/>.\n" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (326) ->~\"Find the GDB manual and other documentation resources online at:\\n <http://www.gnu.org/software/gdb/documentation/>.\"\n"},"seq":28} 1: (326) ->~"Find the GDB manual and other documentation resources online at:\n <http://www.gnu.org/software/gdb/documentation/>." --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (326) ->~\"\\n\\n\"\n"},"seq":30} 1: (326) ->~"\n\n" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (326) ->~\"For help, type \\\"help\\\".\\n\"\n"},"seq":32} 1: (326) ->~"For help, type \"help\".\n" --> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (326) ->~\"Type \\\"apropos word\\\" to search for commands related to \\\"word\\\".\\n\"\n"},"seq":34} 1: (326) ->~"Type \"apropos word\" to search for commands related to \"word\".\n"`

from your log I see that you're using the built-in terminal. You should use an external one. That's a well-known issue of this extension. Nevertheless, probably you won't able to use gdb in the UI of vscode.

**Comment by jbecca** [comment]
I tried both external console false and true, and got the same results. I've also tried setting the "startup-with-shell off" as arguments which also did not help.
