### ISSUE TITLE
intelligence works not well

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#7141]
**Type: LanguageService**

**Describe the bug**
- OS and Version: win10
- VS Code Version:1.54
- C/C++ Extension Version:1.22
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
can not show
```
    double VoltSet[VOLT_MAXE]; // 不同电压下的值
    bool VoltSelct[VOLT_MAXE]; // 选择需要测试的电压
```
![image](https://user-images.githubusercontent.com/1876302/110565756-ee183a80-8189-11eb-836a-fe97533cc236.png)

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I don't repro the issue. 
![image](https://user-images.githubusercontent.com/19859882/110567582-9be20580-8106-11eb-9591-6888a9febce2.png)
Do you repro the issue with code
```
const int VOLT_MAXE = 5;
typedef struct
{
    const char *TestName /* dfd */;
    bool AutoReset;
    double VoltSet[VOLT_MAXE]; // 不同电压下的值
    bool VoltSelct[VOLT_MAXE]; // 选择需要测试的电压
    double CVolt;
} HQA_Configuration;

void func()
{
    HQA_Configuration c;
    c.
}
```
Or do you have code that repros it? What file encoding is the file? Is this C or C++?

Can you provide the output of C/C++: Log Diagnostics?

**Comment by heartacker** [comment]
@sean-mcmanus yes，i disable it
