### ISSUE TITLE
VS Code C++ debugger crashes when hitting play after breakpoint

### ISSUE THREAD

**Issue by damckinn-microsoft** [microsoft/vscode-cpptools#7148]
Type: Debugger
I have a known working program, which I am debugging. No matter where I put a breakpoint, two things always happen:

1. VS Code takes at least 30 seconds to break on this and load locals
2. When I hit play, after inspecting things, the program dies. Anywhere the breakpoint is.
This program does not crash on its own, it runs fine. I have stepped through this program before, and others can do it right now. But I can't play after hitting a breakpoint, and it takes far too long to load locals

debugger is cppvsdbg, and others who are using the same report this working

Contact internally for the code I am using to repro this and launch config

VS Code version: Code 1.53.2 (622cb03, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.21327

**Comment by WardenGnaw** [comment]
Can you share the logging by adding `"logging": { "engineLogging": true, "trace": true, "traceResponse": true }` in your `launch.json`?

**Comment by damckinn-microsoft** [comment]
Attached is my debug console output after adding that line, which I think is what you meant?
At the end, it hits a breakpoint, takes a while to load symbols. I hit play, and then every window in the program closed ... but it said the debug session was still open. After some time, I hit stop. Without the breakpoint, the windows do not close and someone else managed to place the same breakpoint and play without windows closing
[vscodeoutput.txt](https://github.com/microsoft/vscode-cpptools/files/6125297/vscodeoutput.txt)

**Comment by WardenGnaw** [comment]
From your logs, I'm seeing:
1. Symbols loading
2. A bunch of exceptions are being thrown:
```
Exception thrown at 0x00007FFEFA63677C in HeadTrackerHydra.exe: Microsoft C++ exception: HStudio::GetBinaryMetaDataError at memory location 0x000000F5F078D040.
```
3. More Symbol Loading
4. You hit a breakpoint at `sourceEventPumpThread.cpp:324`
5.. You have `continued` from here.
6. Breakpoint hit at `HeadTrackerSystemComponent.cpp:1900`
7. Got StackFrames and variables for threads: SourceEventPumpThread and MovingPlatformExperiment
8. `Continued` from here
8. Program ends and exits with code `0`.


Do you have the logs for the person who does not experience the windows closing and hitting the same breakpoints you placed?

**Comment by damckinn-microsoft** [comment]
everything from 1-4 is normal, and sorry, I'd forgtten about that breakpoint. But that says something .. this was early enough to avoid the problem? 
I will get logs from someone with a breakpoint on HeadTrackerSystemComponent.cpp:1900
