### ISSUE TITLE
How to clean c intellisense tags

### ISSUE THREAD

**Issue by samsong8610** [microsoft/vscode-cpptools#715]
I installed a lib from package tool and intellisense worked perfectly. When I remove this lib and reinstall from source code in which the signature of some functions are changed. But the IDE provides both tags for me.
How to clean unused tags? Restarting can not work.
Thanks.

**Comment by sean-mcmanus** [comment]
Remove the .browse.vc.db file (OS-dependent location) or change the databaseFilename setting in the c_cpp_properties.json. We plan to fix this so it automatically cleans up the database (https://github.com/Microsoft/vscode-cpptools/issues/464 ).

**Comment by samsong8610** [comment]
I removed the .browse.vc.db files by `rm -f $HOME/.config/User/workspaceStorage/XXXXX/ms-vscode.cpptools/.browse.vc.db*` and reopen the workspace, the db is reset. Thanks.
BTW, the default location is like `$HOME/.config/Code/User/workspaceStorage/<workspace hash>/` on linux or `C:\Users\<user>\AppData\Roaming\Code\User\workspaceStorage` on windows.
