### ISSUE TITLE
I am facing issue with the debugger. It slows down VS code horribly, they CPU usage spikes. I start seeing rg.exe and Antimalware windows service eating up memory.

### ISSUE THREAD

**Issue by ahmadafrasiyab** [microsoft/vscode-cpptools#7160]
Type: Debugger

Here is a snap shot:

![image](https://user-images.githubusercontent.com/57048984/110879747-5a7e6100-8292-11eb-9ee6-3889603c01ab.png)

And i get stuck at "debugger attached" stage.

I have already gone over a 100 threads on github and stackoverflow and havent found a single solution.

This is extremely frustrating.

**Describe the bug**
![image](https://user-images.githubusercontent.com/57048984/110880143-00ca6680-8293-11eb-823e-b112b7f2ccc7.png)

- A clear and concise description of what the bug is.
Whenever I try to start the debugger, the debugger gets stuck at "debugger attached" stage. I see the Windows Antimalware service spike up in CPU usage alongwith "rg.exe".

**Comment by sean-mcmanus** [comment]
Your issue doesn't appear to be with the C/C++ extension. You should file your issue at https://github.com/microsoft/vscode/issues . Could be related to https://github.com/microsoft/vscode/issues/64984

Are you using the C/C++ debugger?

@WardenGnaw Could this be a bug with our debugger?

**Comment by ahmadafrasiyab** [comment]
I am not sure. But this has been a reason for wasting my time for the past 2 days. I dont know what is wrong. How would I check if its a C/C++ debugger?

**Comment by sean-mcmanus** [comment]
Does the issue repro with the C/C++ extension disabled (or not installed)? Your launch.json "type" would be "cppdbg" if it's our C++ debugger.

**Comment by sean-mcmanus** [comment]
The thread at https://github.com/microsoft/vscode/issues/64984 has some potential workaround -- the issue might be triggered by another extension you have installed and/or you can try adding the rg.exe to your Defender exclude list.

**Comment by ahmadafrasiyab** [comment]
This is from my launch.json file. 
 "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\server.js"
        }
    ]

**Comment by ahmadafrasiyab** [comment]
And the whitelisting in windows defender does not help

**Comment by ahmadafrasiyab** [comment]
Also I do not have the C/C++ extension installed.

**Comment by michelleangela** [comment]
> Also I do not have the C/C++ extension installed.

@ahmadafrasiyab 
Please file an issue at the VS Code client repository: https://github.com/microsoft/vscode

When filing the issue, I would suggest to repro the issue with any extensions on VS Code turned off (or disabled) to rule out any extensions.

**Comment by ahmadafrasiyab** [comment]
This was not resolved yet and there was no point closing it.

**Comment by michelleangela** [comment]
> This was not resolved yet and there was no point closing it.

This issue was closed as it does not relate to the C/C++ extension.

**Comment by ahmadafrasiyab** [comment]
I would need a resolution please, open the issue where it needs to be. I cannot keep opening issues and spending my development time here. Thank you

**Comment by michelleangela** [comment]
> I would need a resolution please, open the issue where it needs to be. I cannot keep opening issues and spending my development time here. Thank you

Please file the issue at https://github.com/microsoft/vscode/issues as it seems to be related to VS Code and not the C++ extension. As suggested, it could be related to the existing issue https://github.com/microsoft/vscode/issues/64984
