### ISSUE TITLE
cpptools generate coredump sometimes

### ISSUE THREAD

**Issue by Modnars** [microsoft/vscode-cpptools#7161]
使用vs-code插件时，偶尔会出现coredump文件，我的使用方式是Remote-SSH连接远程开发机。
对于何时会出现coredump，暂未发现明显的规律，使用gdb调试core可以观察到下面的信息：
![image](https://user-images.githubusercontent.com/22772190/110881467-5f3b2780-831b-11eb-83be-16491ab46fbf.png)
原谅我对gdb使用不太熟悉，只能从中看到这个coredump是cpptool是抛出来的。

**Comment by sean-mcmanus** [comment]
Can you provide the call stack from the core dump? Such as via something like `gdb ~/.vscode-server/extension/ms-vscode.cpptools-1.2.2/bin/cpptools-srv core.4751` ? Our binary should have symbols.

**Comment by Modnars** [comment]
抱歉，这个是偶尔会出现的问题。但最近一段时间出现得很频繁，以至于我需要将它们remove掉才能让我的工作目录更加整洁。所以很抱歉，最近一次的coredump文件已经被我remove掉了，再出现的话我会立即反馈相关gdb调试信息的。

**Comment by Modnars** [comment]
它又一次出现了！按照你说的binary位置，我启动gdb调试了一下，信息如下：
![image](https://user-images.githubusercontent.com/22772190/110942763-3d6e8e80-8375-11eb-859c-90e4228bd97c.png)
似乎，我还需要再安装其他的一些工具？

**Comment by sean-mcmanus** [comment]
Yes, that is one crash we are aware of (i.e. one of our highest hitting crashes), but we believe it happens during shutdown without much user impact so have not given it a high priority to fix. Are you able to provide any more repro info as to when that occurs? Does it just randomly happen? Do you know what actions causes it? After closing a file or after closing VS Code?

**Comment by Modnars** [comment]
我在开发过程中都是一直打开着远程SSH连接的，所以如果说coredump发生可能是由于关闭文件或VS Code导致的，那我觉得更可能是关闭文件造成的。此外，最近发现cpptools-srv的CPU占有率常常突然很高，希望这个问题也能引起你们的重视，谢谢！

**Comment by sean-mcmanus** [comment]
The CPU issue is different. We might need some perf logs (https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues) or a call stack (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) to identify what is going on (setting C_Cpp.loggingLevel to "Debug" may also show what is using CPU).

**Comment by Modnars** [comment]
你好，今天我又尝试用gdb查看了core文件的堆栈信息，希望这些内容能够对你们起到帮助。
![image](https://user-images.githubusercontent.com/22772190/114529520-9b480c00-9c7c-11eb-8284-1d9e86b71b59.png)

**Comment by sean-mcmanus** [comment]
@Modnars That is a different crash. I've opened https://github.com/microsoft/vscode-cpptools/issues/7354 to track that.

**Comment by michelleangela** [comment]
Fix is released in the 1.3.0 release version https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0
