### ISSUE TITLE
not accepting code of "c++17" or "gnu++17" unable to compile code

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#7162]
Issue Type: <b>Bug</b>

Trying to run code which have "constexpr" keyword and continiously getting this error , the same code is successfully compiled in codeblock.
Note: Also checked by changing cppstandard setting to "c++17" and "gnu++17" but still same error

[Running] cd "d:\codeblock\" && g++ t.cpp -o t && "d:\codeblock\"t
t.cpp: In member function 'void Solution_3sum::nSumStep(const int*, const int*, int, FoundNums ...)':
t.cpp:178:12: warning: 'if constexpr' only available with -std=c++17 or -std=gnu++17
         if constexpr (count == 2)

Extension version: 1.2.2
VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.64GB free)|
|Process Argv|--crash-reporter-id 05c17531-75db-4467-a8a7-f1e58ae986c6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by michelleangela** [comment]
@mdsadiqueinam 

This sounds like a compiler argument configuration issue and not an issue with the C++ extension. Please note the C++ extension does not provide compiling features, for example it does not provide compilers and it does not configure what arguments to provide compilers.

What compiler is used on Codeblocks IDE and how is it configured or what arguments are passed to it? What compiler is being using on VS Code and what arguments are passed to it?

**Comment by mdsadiqueinam** [comment]
Since I am beginner in programming I don't know that much, but I know that MinGw is used as a compiler in codeblock IDE which was installed along with it and I set the same compiler on VScode and yes I do have task.json and I also set c++17 in there

**Comment by sean-mcmanus** [comment]
What is the output of running your task.json?

**Comment by mdsadiqueinam** [comment]
Starting build...
"C:\Program Files\CodeBlocks\MinGW\bin\gcc.exe" -g D:\codeblock\.vscode\tasks.json -o D:\codeblock\.vscode\tasks.exe --std c++17
Command failed: "C:\Program Files\CodeBlocks\MinGW\bin\gcc.exe" -g D:\codeblock\.vscode\tasks.json -o D:\codeblock\.vscode\tasks.exe --std c++17

Build finished with error(s).
The terminal process terminated with exit code: -1.

**Comment by sean-mcmanus** [comment]
"--std c++17" is not valid input to gcc. Does using "-std=c++17" fix your issue?

**Comment by mdsadiqueinam** [comment]
no still same issue
`{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc.exe build active file",
            "command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "-std",
                "c++17"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}`
Starting build...
"C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe" -g D:\codeblock\.vscode\tasks.json -o D:\codeblock\.vscode\tasks.exe -std c++17
gcc.exe: error: c++17: No such file or directory
gcc.exe: error: unrecognized command line option '-std'; did you mean '-mrtd'?

Build finished with error(s).
The terminal process failed to launch (exit code: -1).

**Comment by mdsadiqueinam** [comment]
`{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc.exe build active file",
            "command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "-std=c++17"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}`
Starting build...
"C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe" -g D:\codeblock\.vscode\tasks.json -o D:\codeblock\.vscode\tasks.exe -std=c++17
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe:D:\codeblock\.vscode\tasks.json: file format not recognized; treating as linker script
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe:D:\codeblock\.vscode\tasks.json:1: syntax error
collect2.exe: error: ld returned 1 exit status

Build finished with error(s).
The terminal process terminated with exit code: -1.

**Comment by sean-mcmanus** [comment]
It looks like you fixed the c++17 issue, but you need to run the build task with a .cpp file active and not the tasks.json file active. Does that fix your issues?

**Comment by mdsadiqueinam** [comment]
You mean I have to change the tasks extension from .json to .cpp

**Comment by sean-mcmanus** [comment]
No. The build task is setup to reference the currently active file, so you just need to make the .cpp file active and then run the build task in order to build the .cpp; otherwise, it tries to build the tasks.json file.

**Comment by michelleangela** [comment]
For clarification, a "currently active file" is the file that's currently open or in view in the VS Code editor.

**Comment by mdsadiqueinam** [comment]
still having some errors(s)
`
Starting build...
"C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe" -g D:\codeblock\MergeSortLinkedList.cpp -o D:\codeblock\MergeSortLinkedList.exe -std=c++17
C:\Users\mdsad\AppData\Local\Temp\ccgbG5xi.o: In function `push(Node**, int)':
D:/codeblock/MergeSortLinkedList.cpp:86: undefined reference to `operator new(unsigned long long)'
C:\Users\mdsad\AppData\Local\Temp\ccgbG5xi.o: In function `main':
D:/codeblock/MergeSortLinkedList.cpp:94: undefined reference to `std::istream::operator>>(long&)'
D:/codeblock/MergeSortLinkedList.cpp:98: undefined reference to `std::istream::operator>>(long&)'
D:/codeblock/MergeSortLinkedList.cpp:100: undefined reference to `std::istream::operator>>(long&)'
C:\Users\mdsad\AppData\Local\Temp\ccgbG5xi.o: In function `__tcf_0':
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/iostream:74: undefined reference to `std::ios_base::Init::~Init()'
C:\Users\mdsad\AppData\Local\Temp\ccgbG5xi.o: In function `__static_initialization_and_destruction_0':
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/iostream:74: undefined reference to `std::ios_base::Init::Init()'
C:\Users\mdsad\AppData\Local\Temp\ccgbG5xi.o:MergeSortLinkedList.cpp:(.rdata$.refptr._ZSt3cin[.refptr._ZSt3cin]+0x0): undefined reference to `std::cin'
collect2.exe: error: ld returned 1 exit status

Build finished with error(s).
The terminal process terminated with exit code: -1.`

**Comment by sean-mcmanus** [comment]
Does switching from gcc.exe to g++.exe fix it?
