### ISSUE TITLE
Debugger crashes after update to 1.54.2

### ISSUE THREAD

**Issue by denchii** [microsoft/vscode-cpptools#7164]
After updating VSCode to version 1.54.2, I see the following message when trying to launch debugging in WSL.
![image](https://user-images.githubusercontent.com/7037552/110957190-6f272b80-835c-11eb-9591-8d491a3fb999.png)
<details><summary>Message text</summary>
<p>
Unable to start debugging. Internal error in MIEngine. Exception of type 'System.IndexOutOfRangeException' was thrown.

at MICore.LaunchOptions.QuoteArgument (System.String arg) [0x00000] in <995b18037abc4fce874f752756054699>:0
at MICore.LaunchOptions.ParseArguments (System.Collections.Generic.IEnumerable`1[T] arguments, System.Boolean quoteArguments) [0x0002f] in <995b18037abc4fce874f752756054699>:0
at MICore.LaunchOptions.InitializeLaunchOptions (MICore.Json.LaunchOptions.LaunchOptions launch) [0x0006f] in <995b18037abc4fce874f752756054699>:0
at MICore.LocalLaunchOptions.CreateFromJson (Newtonsoft.Json.Linq.JObject parsedOptions) [0x0006e] in <995b18037abc4fce874f752756054699>:0
at MICore.LaunchOptions.GetInstance (Microsoft.DebugEngineHost.HostConfigurationStore configStore, System.String exePath, System.String args, System.String dir, System.String options, System.Boolean noDebug, MICore.IDeviceAppLauncherEventCallback eventCallback, MICore.TargetEngine targetEngine, MICore.Logger logger) [0x0013a] in <995b18037abc4fce874f752756054699>:0
at Microsoft.MIDebugEngine.AD7Engine.Microsoft.VisualStudio.Debugger.Interop.IDebugEngineLaunch2.LaunchSuspended (System.String pszServer, Microsoft.VisualStudio.Debugger.Interop.IDebugPort2 port, System.String exe, System.String args, System.String dir, System.String env, System.String options, Microsoft.VisualStudio.Debugger.Interop.enum_LAUNCH_FLAGS launchFlags, System.UInt32 hStdInput, System.UInt32 hStdOutput, System.UInt32 hStdError, Microsoft.VisualStudio.Debugger.Interop.IDebugEventCallback2 ad7Callback, Microsoft.VisualStudio.Debugger.Interop.IDebugProcess2& process) [0x0004b] in <14c1087b16a547279b44dfea401fdf16>:0
</p>
</details>

GNU arm-none-eabi-gdb attached to the STLinkGdbServer, which is launch in Windows. Before the update, I didn't saw such a message.

C/C++ Extension Version: 1.2.2
<details><summary>OS and Version</summary>
<p>

- Processor: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz   3.20 GHz
- Installed RAM: 32.0 GB (31.9 GB usable)
- System type: 64-bit operating system, x64-based processor
- Pen and touch: No pen or touch input is available for this display

</p>
</details>

<details><summary>VS Code Version</summary>
<p>

- Version: 1.54.2 (user setup)
- Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
- Date: 2021-03-11T00:56:19.848Z
- Electron: 11.3.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT x64 10.0.19043

</p>
</details>

<details><summary>Other extensions</summary>
<p>

- alefragnani.Bookmarks
- alefragnani.project-manager
- be5invis.toml
- cheshirekow.cmake-format
- cschlosser.doxdocgen
- darkriszty.markdown-table-prettify
- DavidAnson.vscode-markdownlint
- donjayamanne.githistory
- DotJoshJohnson.xml
- eamodio.gitlens
- esbenp.prettier-vscode
- IBM.output-colorizer
- kevinkyang.auto-comment-blocks
- marus25.cortex-debug
- mishkinf.goto-next-previous-member
- ms-python.python
- ms-python.vscode-pylance
- ms-toolsai.jupyter
- ms-vscode.cmake-tools
- ms-vscode.cpptools
- njpwerner.autodocstring
- shd101wyy.markdown-preview-enhanced
- twxs.cmake
- webfreak.debug
- wmaurer.change-case
- xaver.clang-format
- yzhang.markdown-all-in-one

</p>
</details>

<details><summary>launch.json</summary>
<p>

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "load",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceRoot}/build/evault_modem",
      "targetArchitecture": "arm",
      "args": [""],
      "stopAtEntry": true,
      "cwd": "${workspaceRoot}",
      "environment": [],
      "externalConsole": false,
      "serverLaunchTimeout": 20000,
      "filterStderr": true,
      "filterStdout": false,
      "serverStarted": "Info\\ :\\ [\\w\\d\\.]*:\\ hardware",
      "setupCommands": [
        { "text": "cd ${workspaceRoot}/build" },
        { "text": "file evault_modem" },
        { "text": "target remote xxx.xxx.xxx.xxx:xxx" },
        { "text": "monitor reset halt" },
        { "text": "load" },
        { "text": "monitor reset init" },
        { "text": "set output-radix 16" }
      ],
      "logging": {
        "moduleLoad": true,
        "trace": true,
        "engineLogging": true,
        "programOutput": true,
        "exceptions": true
      },
      "MIMode": "gdb",
      "miDebuggerPath": "/home/denchi/tools/gcc-arm/bin/arm-none-eabi-gdb"
    }
]
}
```

</p>
</details>

<details><summary>Debug output window text</summary>

<p>
1: (140) LaunchOptions{"name":"load","type":"cppdbg","request":"launch","program":"/home/denchi/proj/evault/build/evault_modem","targetArchitecture":"arm","args":[""],"stopAtEntry":true,"cwd":"/home/denchi/proj/evault","environment":[],"externalConsole":false,"serverLaunchTimeout":20000,"filterStderr":true,"filterStdout":false,"serverStarted":"Info\\ :\\ [\\w\\d\\.]*:\\ hardware","setupCommands":[{"text":"cd /home/denchi/proj/evault/build"},{"text":"file evault_modem"},{"text":"target remote xxx.xxx.xxx.xxx:xxxx"},{"text":"monitor reset halt"},{"text":"load"},{"text":"monitor reset init"},{"text":"set output-radix 16"}],"logging":{"moduleLoad":true,"trace":true,"engineLogging":true,"programOutput":true,"exceptions":true},"MIMode":"gdb","miDebuggerPath":"/home/denchi/tools/gcc-arm/bin/arm-none-eabi-gdb","__configurationTarget":5,"__sessionId":"xxxx-xxx-xxx-xxx-xxx"}
1: (190) EXCEPTION: System.IndexOutOfRangeException
1: (206) Send Event AD7MessageEvent
</p>
</details>

**Comment by denchii** [comment]
Rolled back to 1.53.2 and the debugger starts. But I see the "Exception has occurred" message - can't take any steps. Then I rebuild the project, restart the debugger, and the error comes back. Same window with text as above.

**Comment by WardenGnaw** [comment]
Duplicate: https://github.com/microsoft/vscode-cpptools/issues/7077

**Comment by WardenGnaw** [comment]
You can workaround this issue by removing `"args": [""]` from your launch.json.
