### ISSUE TITLE
c/c++ Extension Version

### ISSUE THREAD

**Issue by drajkumar5358** [microsoft/vscode-cpptools#7166]
Type: General

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including log messages from the Output window.

**Comment by drajkumar5358** [comment]
The c/c++ extension failed to install successfully.  You will need to repair or reinstall the extension for c/c++ language features to function properly

**Comment by sean-mcmanus** [comment]
What OS? What VS Code version? Installed via the marketplace or offline vsix? Was a previous version of the extension previously installed?

Did uninstalling the extension, restarting VS Code, and reinstalling the extension fix the issue?
