### ISSUE TITLE
Intellisense not working on Ubuntu 18.04 amd_x64

### ISSUE THREAD

**Issue by DimasVeliz** [microsoft/vscode-cpptools#7168]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.54.2
- C/C++ Extension Version: v1.2.2
- Other extensions you installed (and if the issue persists after disabling them):Yes, it persist after disabling them
- Does this issue involve using SSH remote to run the extension on a remote machine?:No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The project is a simple cpp file in which the intellisense wasnt working. After reading the instructions in the VS code extension page I went to the command palette.

When launching the command palette and trying to execute : Edit Configuration(UI) or Edit Configuration(JSON) I get the following error: "command 'c/c++: edit configurations (ui)' resulted in an error (command 'c_cpp.configurationeditui' not found)" or "command 'c/c++: edit configurations (json)' resulted in an error (command 'c_cpp.configurationeditjson' not found)"

I've created the c_cpp_properties.json file myself within the .vscode folder and still doesnt work. Tried Reinstalling Vscode, from both the official site and the Ubuntu App store.

**Steps to reproduce**

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
It sounds like our extension is not installing/activating correctly for you. It's most likely a VS Code bug (https://github.com/microsoft/vscode/issues). You may want to try VS Code Insiders as well to see if it's fixed there. Output from Help->Toggle Developer Tools->Console might help.

**Comment by Tuweky** [comment]
I am experiencing the same issue on a system running Ubuntu (20.04) at both VS Code (1.54.3) and VS Code Insiders (1.55.0-insider). When checking the console output at Help->Toggle Developers Tools->Console I get the following error:

> (node:30329) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
v @ console.ts:137

The error is triggered when enabling the C/C++ plugin (1.2.2) and opening any source file.

**Comment by sean-mcmanus** [comment]
@Tuweky The DeprecationWarning is "normal". Do you see "activating extension" also? I'm unable to repro the issue, but the C/C++: Edit Configuration command won't work in single file mode and should give a "Open a folder first to edit configurations" message instead. Can you think of anything special about your system which could be causing the failure?

**Comment by Tuweky** [comment]
@sean-mcmanus Oh okay thank you for clarifying, I did not expect that about the DeprecationWarning.

Yes, I do see the "activating extension" message at the console log output. The full log output with all log levels enabled is as following:
![image](https://user-images.githubusercontent.com/41124626/111610420-a2920c00-87db-11eb-8bd6-5146477429db.png)

When opening the Log (Extension Host), I get a bunch of the following warning and error messages:

> [2021-03-18 11:21:53.494] [exthost] [warning] ms-vscode.cpptools - Code actions of kind 'quickfix 'requested but returned code action does not have a 'kind'. Code action will be dropped. Please set 'CodeAction.kind'.
[2021-03-18 11:22:56.306] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-03-18 11:22:56.306] [exthost] [error] undefined

I'm not sure what could be "special" at my system that could lead to this issue. In my team there two other users which are experiencing the same problems. Both are also running Linux on their system (Ubuntu and Manjaro).

**Comment by sean-mcmanus** [comment]
@Tuweky  The "provider FAILED" message is also normal and can be ignored.

Are you experience any buggy symptoms?

**Comment by Tuweky** [comment]
@sean-mcmanus Yes, I do experience buggy symptoms. The bug that I encounter is that the intellisense does not refresh after editing source code. When reloading the plugin, the intellisense works as expected, but after some source code edits the intellisense does not seem to refresh autonomously.

I experience visual bugs like these as example:
![image](https://user-images.githubusercontent.com/41124626/111752035-79ce4d00-8895-11eb-8ea6-ad5ca9bbd679.png)

Jumping to definitions is also broken at that moment as it jumps to incorrect lines. Seems like it tries to jump to old locations, before the file was edited.

I do not seem to experience the "Command not found error" which you are referring to. Where would I expect to encounter this?

**Comment by sean-mcmanus** [comment]
@Tuweky The original bug report describes a "command not found error". Your symptoms appear to be completely different. I'm moving your issue to a new issue.

**Comment by bobbrow** [comment]
The original issue this thread is tracking seems to have been addressed.  Please let us know if you continue to have problems activating the extension.
