### ISSUE TITLE
Auto indentation doesn't preserve space

### ISSUE THREAD

**Issue by frozar** [microsoft/vscode-cpptools#717]
Steps to Reproduce:

1. Copy a struct definition ("Ctrl+C")
2. Paste it inside a function
3. Ask VSCode to indent the structure definition inside the function : Ctrl+K Ctrl+F

As illustrated in the animation, after the indentation, the white spaces between the type and the name of a field is not preserve, and so the alignement of the field names inside the structure definition doesn't exist anymore.
![peek 11-05-2017 14-15](https://cloud.githubusercontent.com/assets/1025244/25960916/b594dfca-3678-11e7-854d-ff3495850548.gif)

What I except from VSCode indentation is just to add the correct number of white spaces at the beginning of each lines of the structure definition.

A solution may be to add a keyword in the setting to ask VSCode to not modify the ending of lines to indent.

**Comment by sean-mcmanus** [comment]
Use AlignConsecutiveDeclarations: true in a .clang-format file or C_Cpp.clang_format_style. See http://releases.llvm.org/3.8.0/tools/clang/docs/ClangFormatStyleOptions.html . Let us know if you're having problems still.

**Comment by frozar** [comment]
Thank you @sean-mcmanus, with the line 
`"C_Cpp.clang_format_style": "{ AlignConsecutiveDeclarations: true }",`, things are better.
My last notice is that, the indentation doesn't preserve the space before the final semicolon.

**Comment by sean-mcmanus** [comment]
A space before a semi-colon is a style I have never seen before, so I don't think there's an option for that. You could try to add that option to clang-format yourself, but they might not accept it (https://mydeveloperday.wordpress.com/2015/09/18/contributing-to-clang-format/ ).

**Comment by frozar** [comment]
You're right, I think it is a too custom style and I will never get it in maintain way.
