### ISSUE TITLE
High CPU usage on OSX

### ISSUE THREAD

**Issue by jayteemo** [microsoft/vscode-cpptools#7178]
Type: General

![cpp_tools_profile](https://user-images.githubusercontent.com/4138391/111370979-15717a80-8656-11eb-9579-3be055aabac1.png)

I experience high (>90%) CPU usage from cpptools v1.2.2.
This occurs when I open a workspace, generally the workspace has a few root project folders loaded.
Projects are generally a fork of https://github.com/nrfconnect/sdk-nrf with dependencies loaded (https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/gs_installing.html).
CPU usage remains high while I am working in the editor.
If I minimize VS Code, the cpu usage will go down to an unnoticeable level after a few minutes.

Let me know if you need more information.
Thanks.

Arrived here from: https://github.com/microsoft/vscode-cpptools/issues/6238#issuecomment-793232388

```
System Info:
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,2
  Processor Name:	Intel Core i5
  Processor Speed:	2.4 GHz
  Memory:	16 GB

Visual Studio Code:
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0
  ```

**Comment by sean-mcmanus** [comment]
Your perf logging indicates it is tag parsing and the CPU usage is expected. If you set C_Cpp.loggingLevel to "Debug" you can see which files are being tag parsed and the symbols are not needed you can add the folders to your files.exclude setting to avoid parsing those files. You could also set the browse.path to a subset of ${workspaceFolder} (see https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp for details). Let me know if those settings aren't able to solve your issue.
