### ISSUE TITLE
`C_Cpp.exclusionPolicy` + `files.exclude` appears to be ignored [macOS, SSH]

### ISSUE THREAD

**Issue by jlennox** [microsoft/vscode-cpptools#7188]
**Type: LanguageService**

**Describe the bug**
- OS and Version: macOS 10.15.7
- VS Code Version: 1.53.2
- C/C++ Extension Version: 1.2.2
- Other extensions you installed (and if the issue persists after disabling them): n/a
- Does this issue involve using SSH remote to run the extension on a remote machine?: Yes
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I am using vscode remote, connecting from a Windows machine to a macOS machine. I did not test on any other combination.

cpptools on macOS is excessively using CPU and never completing analysis. Using the command `sudo opensnoop -n cpptools` I am seeing that it's endlessly scanning files. This is a relatively large code base that consists of many languages. There's a lot of easy directory pruning I could do here.

```JSON
  "C_Cpp.exclusionPolicy": "checkFolders",
  "files.exclude": {
    "**/target": true,
    "*lock": true,
    "*svg": true,
    "*.bzl": true,
    "**/debug": true,
    "**/node_modules": true,
    "node_modules": true,
    "**/deps": true,
    "**/_build": true,
    "**/discord_gateway": true,
    "**/lib/python3.*": true,
    "**/.go": true,
  },
```

Not too sure of the syntax, I added `node_modules` in both of those forms. I tried both `checkFolders` and `checkFilesAndFolders` for sake of elimination.

After setting those, and restarting VSCode, I still seeing it recursing into the `node_modules` directories.

**Steps to reproduce**
See above.

**Expected behavior**
It should be checking against the `files.exclude` object and seeing that it should not be reading into node_modules.

I'd actually prefer that the extension has its own list of excluded paths. This is because when writing typescript, I actually need to search and complete inside of node_modules. It's not logical that every language would want to exclude the same set of paths.

**Comment by sean-mcmanus** [comment]
This sounds like what I'm working on fixing right now: https://github.com/microsoft/vscode-cpptools/issues/3123 . It's expected for 1.3.0-insiders2 in a few weeks. We're also considering the separate exclude setting (not sure if that will make it in at the same release though)...we might create a separate issue to track that later.

I'm closing this as a duplicate for now, but I'll follow up when we release the fix to confirm that it's fixed for your scenario.
