### ISSUE TITLE
compilerArgs from compile_commands.json are not used

### ISSUE THREAD

**Issue by b1r1b1r1** [microsoft/vscode-cpptools#7189]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Linux 5.4.72-microsoft-standard-WSL2 x86_64
- VS Code Version: 1.54.3
- C/C++ Extension Version: v1.2.2
- Other extensions you installed (and if the issue persists after disabling them): -
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).: compilerArgs from compile_commands.json are not used

**Steps to reproduce**

1. Create directory with next structure

.vscode/c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-clang-x64",
            "compileCommands": "${workspaceFolder}/compile_commands.json"
        }
    ],
    "version": 4
}
```
compile_commands.json (change /home/xmikasax/git/test to path of your directory)
```
[
{
    "directory": "/home/xmikasax/git/test",
    "command": "/bin/clang++-10 -Wpointer-bool-conversion -Werror -I/home/xmikasax/git/test/lib -o /home/xmikasax/git/test/a.cpp.o -c /home/xmikasax/git/test/a.cpp",
    "file": "/home/xmikasax/git/test/a.cpp"
}
]
```

a.cpp
```
#include "b.hpp"

int main() {
  if (func) {
    return 1;
  }
}
```

lib/b.hpp
```
bool func() { return false; }
```

2. Open root folder in VSC

**Expected behavior**

1. func symbol is resolved from b.hpp according to -Ilib from compile_commands.json
2. compile error (red underline) occurs because of -Wpointer-bool-conversion -Werror in compile_commands.json

**Actual behaviour**
1. func symbol is resolved from b.hpp according to -Ilib from compile_commands.json
2. there is no compile error, compile flags are not used

<details>
  <summary><strong>Logs</strong></summary>

-------- Diagnostics - 3/18/2021, 1:44:49 AM
Version: 1.2.2
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "compileCommands": "${workspaceFolder}/compile_commands.json",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/xmikasax/git/test/a.cpp ]:
    /home/xmikasax/git/test/a.cpp
    /home/xmikasax/git/test/lib/b.hpp
Translation Unit Configurations:
[ /home/xmikasax/git/test/a.cpp ]:
    Process ID: 13171
    Memory Usage: 15 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /home/xmikasax/git/test/lib
        /usr/include/c++/9
        /usr/include/x86_64-linux-gnu/c++/9
        /usr/include/c++/9/backward
        /usr/local/include
        /usr/lib/llvm-10/lib/clang/10.0.0/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=100000
    compile_commands.json entry:
        directory: /home/xmikasax/git/test
        file: /home/xmikasax/git/test/a.cpp
        command: /bin/clang++-10 -Wpointer-bool-conversion -Werror -I/home/xmikasax/git/test/lib -o /home/xmikasax/git/test/a.cpp.o -c /home/xmikasax/git/test/a.cpp
Total Memory Usage: 15 MB
Browse Paths from compile_commands.json, from workspace folder: /home/xmikasax/git/test
    /home/xmikasax/git/test
    /home/xmikasax/git/test/lib

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 6437
Number of files discovered (not excluded): 5962

File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/.vscode
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
Search exclude: **/.vscode
Populate include completion cache.
Discovering files...
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /usr/lib/llvm-10/lib/clang/10.0.0/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /home/xmikasax/git/test/
  Discovering files: 5962 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Done parsing open files.
idle loop: reparsing the active document
Checking for syntax errors: file:///home/xmikasax/git/test/a.cpp
Queueing IntelliSense update for files in translation unit of: /home/xmikasax/git/test/a.cpp
Error squiggle count: 0
Error squiggle count: 0
Update IntelliSense time (sec): 0.267
idle loop: reparsing the active document
Checking for syntax errors: file:///home/xmikasax/git/test/a.cpp
Queueing IntelliSense update for files in translation unit of: /home/xmikasax/git/test/a.cpp
Error squiggle count: 0
Error squiggle count: 0
Update IntelliSense time (sec): 0.264
idle loop: reparsing the active document
Checking for syntax errors: file:///home/xmikasax/git/test/a.cpp
Queueing IntelliSense update for files in translation unit of: /home/xmikasax/git/test/a.cpp
Error squiggle count: 0
Error squiggle count: 0
Update IntelliSense time (sec): 0.268

</details>

**Comment by sean-mcmanus** [comment]
Our IntelliSense parser doesn't implement warnings like -Wpointer-bool-conversion . That feature is being tracked by https://github.com/microsoft/vscode-cpptools/issues/2814 .
