### ISSUE TITLE
launch.json does not use automation shell

### ISSUE THREAD

**Issue by bbennetts** [microsoft/vscode-cpptools#7192]
Issue Type: <b>Bug</b>

The documentation (https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch) states that "terminal.integrated.automationShell.{platform} - Shell path for automation-related terminal usage like tasks and debug." however debugging as far as I can tell is invoking the non-automation shell.

Extension version: 1.2.2
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.0.0-38-generic snap
Remote OS version: Linux x64 4.18.0-277.el8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 1|
|Memory (System)|31.27GB (3.89GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id c9ada280-44c2-4a34-a7fc-748193a9bb8e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: hollie|
|OS|Linux x64 4.18.0-277.el8.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz (40 x 1000)|
|Memory (System)|62.34GB (1.69GB free)|
|VM|0%|
</details>

**Comment by bbennetts** [comment]
Ultimately I do not strongly care whether it does use the automation shell or not - I need to be able to differentiate between an interactive shell opened by the user via the menus, and a shell opened for the debugger.  At the moment the debugger one is an interactive shell (in bash $- contains an "i") so I cannot gate behaviours between automated invocations and user interactive invocations.

**Comment by sean-mcmanus** [comment]
@bbennetts Is this a VS Code issue (it sounds like it is) or an issue with the "cppdbg" or "cppvsdbg" debugger types from the C/C++ extension?

**Comment by bbennetts** [comment]
@sean-mcmanus I've just tried vadimcn.vscode-lldb and the shell it starts has the same bash options "himBH".  Does this imply it is VSCode at fault?

**Comment by sean-mcmanus** [comment]
I don't know. @WardenGnaw ?

**Comment by WardenGnaw** [comment]
If it happens across extensions, it would be VSCode or an API they created that has not been supported by the extensions.

**Comment by bbennetts** [comment]
So shall I raise a ticket against vscode?

Ta.

**Comment by sean-mcmanus** [comment]
Yes
