### ISSUE TITLE
$FILEPOS outputting source file and line number - doesn't go to line number in Debug Console

### ISSUE THREAD

**Issue by gordody** [microsoft/vscode-cpptools#7193]
Type: Debugger

**Describe the bug**
- OS and Version: Mac OS 10.15.7 (Catalina)
- VS Code Version: Version: 1.54.1 / Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8 / Date: 2021-03-04T22:42:18.719Z / Electron: 11.3.0 / Chrome: 87.0.4280.141 / Node.js: 12.18.3 / V8: 8.7.220.31-electron.0 / OS: Darwin x64 19.6.0
- C/C++ Extension Version: Version 1.2.2: February 25, 2021
- Other extensions you installed (and if the issue persists after disabling them): -
- A clear and concise description of what the bug is.

Not sure if it's a VSCode Debug Console issue or the extension issue, I'm filing it here for now:

When using the cppdbg MIDebugger Logpoint `$FILEPOS` token, the file position line is displayed as 
`/Users/jsmith/develop/myproject/src/main.cpp(912) myvariable=42`

When I Cmd + Click on this, it takes me to the top of the file (eg the line number is disregarded).

The same string pasted into the Terminal works properly with Cmd + Click. However Logpoints don't display in the Terminal.

**To Reproduce**
1. Add a Logpoint in your C++ code with the contes like this: `$FILEPOS myvariable={myvariable}`
2. Set the debugger to use the Debug Console for output in the launch config in launch.json
3. When the logpoint is hit and the line is displayed in the Debug Console, it display like this: `/Users/jsmith/develop/myproject/src/main.cpp(912) myvariable=42`
4. When Cmd + Clicking on this line, it displays the file in the editor scrolled to the top, not the line number (912)

![image](https://user-images.githubusercontent.com/24533582/111710748-7a200700-8807-11eb-82ed-963715495dee.png)

launch.json snippet:
```
         {
            "name": "Launch App (cppdbg)",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/<my app>",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb"
        },
```

**Comment by WardenGnaw** [comment]
Format for string to jump to line is `filepath:line`, the current output uses `filepath(line)`

See https://github.com/microsoft/MIEngine/blob/9470e98d946772ed1ace9ab68e9fbd4d88090b42/src/OpenDebugAD7/Tracepoint.cs#L165

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders
