### ISSUE TITLE
After using any manipulators it's add parentheses automatically.

### ISSUE THREAD

**Issue by santobollove** [microsoft/vscode-cpptools#7199]
**Type: LanguageService**

After installing c/c++ `ms-vscode.cpptools` wait few minutes it will updated to 1.3.0-insiders after that every time you use any manipulators it will add parentheses (In every manipulators).

**Describe the bug**
- OS and Version: Linux x64 5.11.5-arch1-1
- VS Code Version: 1.54.3
- C/C++ Extension Version: 1.3.0-insiders
- Other extensions you installed (and if the issue persists after disabling them): yes
- Does this issue involve using SSH remote to run the extension on a remote machine?: I don't try that on remote machine
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc). It was only 1 .cpp file 1KB in size

**Steps to reproduce**

1. Install ms-vscode.cpptools from vs extension 
2. Wait until you see a notification "The C/C++ Extension has been updated to version 1.3.0-insiders. Please reload the windows for the changes to take effect".
3. Reload the windows.

**Expected behavior**

Normally manipulators don't need any parentheses (26) except parameterized manipulators (6) so after auto completing manipulators it put parentheses even i don't need that.

**Comment by sean-mcmanus** [comment]
What do you mean by "manipulators"? Are the manipulators "types"? If so, we're tracking that with https://github.com/microsoft/vscode-cpptools/issues/7209 .

**Comment by sean-mcmanus** [comment]
Are you referring to C++/CX properties? https://docs.microsoft.com/en-us/cpp/cppcx/properties-c-cx?view=msvc-160

**Comment by sean-mcmanus** [comment]
Oh, I assume you mean IO stream manipulators that don't take an argument, like https://en.cppreference.com/w/cpp/io/manip/boolalpha .

**Comment by sean-mcmanus** [comment]
One workaround is to change the C_Cpp.autocompleteAddParentheses setting to false.

**Comment by sean-mcmanus** [comment]
We're changing the C_Cpp.autocompleteAddParentheses setting to be false by default for 1.3.0-insiders2.
