### ISSUE TITLE
Please support data breakpoints while debugging Microsoft C++ on Windows

### ISSUE THREAD

**Issue by Ben136KBC** [microsoft/vscode-cpptools#7201]
The documentation says that if a debugger supports data breakpoints, you can set them in the VARIABLES section. However, I can find nothing there for this extension while debugging Microsoft C++ under Windows. Is it missing or somewhere else?

The extension is awesome, super, but being able to set data breakpoints is very important and that appears to be missing?

I love VSCode and use it by default now, and the apparent lack of data breakpoints is baffling. Sometimes they are indispensable.  I would rate this as the top feature I need.

**Comment by sean-mcmanus** [comment]
This is being tracked by https://github.com/microsoft/vscode-cpptools/issues/1410 .

I switch to VS 2019 when I need to use data breakpoints.
