### ISSUE TITLE
Auto add parentheses incorrectly occurs with template methods

### ISSUE THREAD

**Issue by KnewHow** [microsoft/vscode-cpptools#7203]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.54.3
2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
x64
- C/C++ Extension Version: 1.3.0-insider
- Other extensions you installed (and if the issue persists after disabling them): Cmake
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- I know you add some parenthesis after some value function, for example `std::optional<Person> s;` s.value`()`, the parenthesis is auto complete is prefect here, but when I input `std::share_ptr`, it will auto add `()` after it, it see very terrible! I just want a code like `std::share_ptr<>` to add some type, but you give me a parenthesis. I hope you can do better, thank you!

**Comment by KnewHow** [comment]
the vesion is: 1.3.0-insiders!

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders2

**Comment by michelleangela** [comment]
Fix is released in the 1.3.0 release version https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0
