### ISSUE TITLE
Auto adding parentheses incorrectly occurs with type names

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7209]
> Auto adding parentheses is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders . It's enabled by default (C_Cpp.autocompleteAddParentheses). The behavior of when to add the closing `)` also responds to the editor.autoClosingBrackets setting (default is to always close the `)`). Let us know if you find any issues related to this.

Thanks for the enhancement, it helps a lot!
In using the feature, I found 2 annoying unexpected auto completions, please take a look:
```
class Foo {
public:
  Foo(int n) : n_(n) {}
  virtual ~Foo() {}
};

class Bar : public Foo {
public:
  void func() {
    Foo* a = nullptr; // Autocomplete Foo to "Foo()" is unexpected in typing 'Foo'
  }

private:
  vector<Foo*> x_; // Autocomplete Foo to "Foo()" is unexpected in typing 'Foo'
};
```

_Originally posted by @xiray in https://github.com/microsoft/vscode-cpptools/issues/882#issuecomment-803234757_

**Comment by xiray** [comment]
Thanks for the fix. In using the feature, I found another bug:
```
vector<int> v;
v.empty()|; // Autocomplete 'empty' to "empty()", and the cursor is after ')', this is expected.
v.front(|); // Autocomplete 'front' to "front()", but the cursor is between '(' and ')', this is unexpected, because "front" has no argument.
```
Please take a look, thanks a lot for your work.

**Comment by sean-mcmanus** [comment]
@xiray Thanks for reporting that. I've moved your issue to https://github.com/microsoft/vscode-cpptools/issues/7540 . It's caused by front() having a const and non-const overload.
