### ISSUE TITLE
Go To Definition doesn't work for namespace-qualified symbols

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#721]
Hi folks,
I've noticed that Go to Definition only seems to work part of the time for me, and I finally realized what (I think) the significant difference is -
This situation works, I can do a Go To Definition on "DefinedSomewhereElseFoo" successfully:
class Foo : public DefinedSomewhereElseFoo {}
This does not work, I cannot look up "DefinedSomewhereElseBar"
class Bar : public ns::DefinedSomewhereElseBar {}
But it's definitely aware of that symbol, because when I do a Ctrl-T symbol search I can find "DefinedSomewhereElseBar" successfully. 
Is this a known issue/is there a workaround?
Thanks.

**Comment by ghost** [comment]
I think there's additional subtlety - it only occurs when the namespace is a relative namespace, not an absolute namespace.

**Comment by sean-mcmanus** [comment]
Thanks for the bug details. We are able to repro the problem.

**Comment by sean-mcmanus** [comment]
This seems to be fixed with our latest version? If not, please reactivate and paste the repro code in a `block` so I can easily repro it.
