### ISSUE TITLE
C++ Unable to establish a connection to GDB

### ISSUE THREAD

**Issue by zhouyium** [microsoft/vscode-cpptools#7212]
Type: Debugger

The VSCode is doing great job, until few days before, VSCode broke down.

Describe the bug
    OS and Version: Windows10 Pro.
    VS Code Version: 1.54.3 (user setup)
    C/C++ Extension Version: g++ (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
    Extensions: C/C++
When I ran an internal debugger for my c++ project, I met below pop-up message at everytime. Unable to start debugging, Unable to establish a connection to GDB.
![图片](https://user-images.githubusercontent.com/70430188/112081946-77cefb80-8bbf-11eb-8167-25a2fcadb102.png)

The following is the information from debug panel:
`--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (71) LaunchOptions{\"name\":\"g++.exe - 生成和调试活动文件\",\"type\":\"cppdbg\",\"request\":\"launch\",\"program\":\"e:\\\\zhouyi\\\\vscode\\\\C++\\\\Untitled-1.exe\",\"args\":[],\"stopAtEntry\":false,\"cwd\":\"E:\\\\zhouyi\\\\vscode\\\\C++\",\"environment\":[],\"externalConsole\":true,\"MIMode\":\"gdb\",\"miDebuggerPath\":\"E:\\\\Program Files\\\\mingw64\\\\bin\\\\gdb.exe\",\"setupCommands\":[{\"description\":\"Enable pretty-printing for gdb\",\"text\":\"-enable-pretty-printing\",\"ignoreFailures\":true}],\"logging\":{\"trace\":true,\"traceResponse\":true,\"engineLogging\":true},\"preLaunchTask\":\"C/C++: g++.exe build active file\",\"__configurationTarget\":5,\"__sessionId\":\"dc5c3235-9417-4de2-832f-54d18f09b860\"}\r\n"},"seq":2}
1: (71) LaunchOptions{"name":"g++.exe - 生成和调试活动文件","type":"cppdbg","request":"launch","program":"e:\\zhouyi\\vscode\\C++\\Untitled-1.exe","args":[],"stopAtEntry":false,"cwd":"E:\\zhouyi\\vscode\\C++","environment":[],"externalConsole":true,"MIMode":"gdb","miDebuggerPath":"E:\\Program Files\\mingw64\\bin\\gdb.exe","setupCommands":[{"description":"Enable pretty-printing for gdb","text":"-enable-pretty-printing","ignoreFailures":true}],"logging":{"trace":true,"traceResponse":true,"engineLogging":true},"preLaunchTask":"C/C++: g++.exe build active file","__configurationTarget":5,"__sessionId":"dc5c3235-9417-4de2-832f-54d18f09b860"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (126) Starting: \"E:\\Program Files\\mingw64\\bin\\gdb.exe\" --interpreter=mi\r\n"},"seq":4}
1: (126) Starting: "E:\Program Files\mingw64\bin\gdb.exe" --interpreter=mi
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (133) DebuggerPid=14008\r\n"},"seq":6}
1: (133) DebuggerPid=14008
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (146) \"E:\\Program Files\\mingw64\\bin\\gdb.exe\" exited with code 1 (0x1).\r\n"},"seq":8}
1: (146) "E:\Program Files\mingw64\bin\gdb.exe" exited with code 1 (0x1).
--> E (output): {"type":"event","event":"output","body":{"category":"stderr","output":"Starting: \"E:\\Program Files\\mingw64\\bin\\gdb.exe\" --interpreter=mi\r\n\"E:\\Program Files\\mingw64\\bin\\gdb.exe\" exited with code 1 (0x1).\r\n\r\n"},"seq":10}
Starting: "E:\Program Files\mingw64\bin\gdb.exe" --interpreter=mi
"E:\Program Files\mingw64\bin\gdb.exe" exited with code 1 (0x1).
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (153) <-logout\r\n"},"seq":12}
1: (153) <-logout
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (153) Send Event AD7MessageEvent\r\n"},"seq":14}
1: (153) Send Event AD7MessageEvent
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/Launch","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"16.5.11030.1","VS.Diagnostics.Debugger.HostVersion":"16.5.11030.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.Launch.ErrorCode":1005,"VS.Diagnostics.Debugger.Launch.IsError":true}},"seq":17}
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/MIEngine/DebuggerAborted","data":{"VS.Diagnostics.Debugger.MIEngine.DebuggerName":"GDB","VS.Diagnostics.Debugger.MIEngine.LastSentCommandName":"","VS.Diagnostics.Debugger.MIEngine.DebuggerExitCode":"1 (0x1)"}},"seq":16}
--> R (launch-2): {"type":"response","request_seq":2,"success":false,"command":"launch","message":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information.","body":{"error":{"id":1005,"format":"Unable to start debugging. Unable to establish a connection to GDB. Debug output may contain more information."}},"seq":20}
`
I have uninstall python and reboot pc, it is the same problem.

The following is the launch.json:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "E:\\Program Files\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
            },
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}`

tasks.json
`{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "C/C++: g++.exe build active file",
            "command": "E:\\Program Files\\mingw64\\bin\\g++.exe",
            "args": [
                "-g",
                "-std=c++11",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}`

I have try the all information I can find by google. But nothing change.

**Comment by sean-mcmanus** [comment]
@WardenGnaw ?

**Comment by WardenGnaw** [comment]
Looks like gdb is failing to launch. Can you run `E:\Program Files\mingw64\bin\gdb.exe" --interpreter=mi` in your terminal and it does not crash?

**Comment by zhouyium** [comment]
@WardenGnaw Thanks. gdb is crash. Very strange, I use the offline package, the gdb is crashed. I download from mingw-w64, it is OK.
