### ISSUE TITLE
autocomplete does not work after including p18f4550.h

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#7217]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Add "#include <p18f4550.h>"
2. all the structs should be available for autocompletion

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
What is p18f4550.h? Are you able to provide that file?

**Comment by phgmacedo** [comment]
They are header files from the [mplab c compiler
](https://www.microchip.com/Developmenttools/ProductDetails/SW006011)

[pic.zip](https://github.com/microsoft/vscode-cpptools/files/6190611/pic.zip)

**Comment by sean-mcmanus** [comment]
The "near" is not standard C++ so our compiler doesn't recognize it. Are you getting IntelliSense errors when you open the header file? You can add "near=" in the "defines" section to avoid that. After that completion should work.

**Comment by phgmacedo** [comment]
@sean-mcmanus I'm not trying to _compile_  with vscode.

Also, vscode recognizes where the PORTDbits is defined: 
![2](https://user-images.githubusercontent.com/2473545/112233740-b5f90900-8c19-11eb-8ec9-c19a3da2fe0a.png)

But does not provide any autocompletion suggestion:

![1](https://user-images.githubusercontent.com/2473545/112233762-c315f800-8c19-11eb-8044-504e13643393.png)

This extends to everything declared in the header files.

**Comment by sean-mcmanus** [comment]
In order to provide IntelliSense autocomplete, our parser needs to be able to compile the code. Go to Definition maybe provided by a different parser than the autocomplete which is more forgiving with tokens it doesn't recognize. It looks like IntelliSense may not be running. Do you get any error squiggles when you type incorrect code? What do you get when you run the C/C++: Log Diagnostics command?

**Comment by phgmacedo** [comment]
No error squiggles. 

Output of the log diag: 

```
-------- Diagnostics - 24/03/2021, 11:53:21
Version: 1.2.2
Current Configuration:
{
    "name": "pic18",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/h/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE",
        "near= "
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "macFrameworkPath": [],
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": false,
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe",
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${workspaceFolder}/h/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\phg\OneDrive\UTFPR\Semestre 9.5\IF68E - Sistemas Embarcados\exs\ex3.c ]:
    C:\USERS\PHG\ONEDRIVE\UTFPR\SEMESTRE 9.5\IF68E - SISTEMAS EMBARCADOS\EXS\EX3.C
Translation Unit Configurations:
[ C:\Users\phg\OneDrive\UTFPR\Semestre 9.5\IF68E - Sistemas Embarcados\exs\ex3.c ]:
    Process ID: 4896
    Memory Usage: 18 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.28.29910\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.28.29910\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
        C:\USERS\PHG\ONEDRIVE\UTFPR\SEMESTRE 9.5\IF68E - SISTEMAS EMBARCADOS\H
        C:\USERS\PHG\ONEDRIVE\UTFPR\SEMESTRE 9.5\IF68E - SISTEMAS EMBARCADOS\FREERTOS_MPLABX\SOURCE\INCLUDE
        C:\USERS\PHG\ONEDRIVE\UTFPR\SEMESTRE 9.5\IF68E - SISTEMAS EMBARCADOS\FREERTOS_MPLABX\DEMO\PIC18_MPLAB
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
        near= 
    Standard Version: ms_c17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 18 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 5374
Number of files discovered (not excluded): 5304
Number of files parsed: 320

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt/stddef.h
    Alternative: "C:/Users/phg/OneDrive/UTFPR/Semestre 9.5/IF68E - Sistemas Embarcados/h"
Using: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/include/stdint.h
    Alternative: "C:/Users/phg/OneDrive/UTFPR/Semestre 9.5/IF68E - Sistemas Embarcados/FreeRTOS_MPLABX/Demo/PIC18_MPLAB"
```

**Comment by sean-mcmanus** [comment]
Strange. I'm not reproing the issue. I'll see if someone else on our team can repro this.

![image](https://user-images.githubusercontent.com/19859882/112342072-300fa900-8c7f-11eb-98c3-457a343daa99.png)

By "no error squiggles" you mean that if you type invalid code you don't get error squiggles?

**Comment by phgmacedo** [comment]
> By "no error squiggles" you mean that if you type invalid code you don't get error squiggles?

Yes.

**Comment by sean-mcmanus** [comment]
That is strange. I'm not sure what is going on. Do you have another extension installed that could be providing the empty completion? Do you have the C_Cpp.errorSquiggles setting not set to "Disabled"?

**Comment by phgmacedo** [comment]
This is my c_cpp settings: 
```
{
    "configurations": [
        {
            "name": "pic18",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/h/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "near= "
            ],
            "cStandard": "c17",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by phgmacedo** [comment]
> That is strange. I'm not sure what is going on. Do you have another extension installed that could be providing the empty completion? Do you have the C_Cpp.errorSquiggles setting not set to "Disabled"?

I looked at my settings.json file, and indeed, I have ```    "C_Cpp.errorSquiggles": "Disabled",```. Does this affect auto-completion as well? And why can't the extension work out of the box for auto-completion of the structs it knows are defined, even if with "nonstandard" syntax?

**Comment by v-ericawu** [comment]
@phgmacedo Sorry, We can't repro your issue when "C_Cpp.errorSquiggles" set to "Disabled" or "Enabled":
![actual](https://user-images.githubusercontent.com/78774400/112431717-d4c2e100-8d7a-11eb-853d-60bafa168b3d.gif)

**Comment by sean-mcmanus** [comment]
@phgmacedo The errorSquiggles setting doesn't affect completion, but the existence of error squiggles can help locate code that is failing to get parsed, which can cause autocomplete to be missing entries. Completion by default uses IntelliSense and not the tag parser -- you could switch intelliSenseMode to "Tag Parser" to get that completion. I'm guessing that IntelliSense isn't seeing the definition but the tag parser results are (error squiggles around the definition could explain why).

@v-ericawu Can you try your repro with .c file file instead of a .cpp file?

**Comment by v-ericawu** [comment]
@sean-mcmanus We didn't repro this issue with .c file:
![actual](https://user-images.githubusercontent.com/78774400/112567410-c24cb400-8e1b-11eb-8871-01bbc1a4dec8.PNG)

**Comment by phgmacedo** [comment]
> This is my c_cpp settings: 
> ```
> {
>     "configurations": [
>         {
>             "name": "pic18",
>             "includePath": [
>                 "${workspaceFolder}/**",
>                 "${workspaceFolder}/h/**"
>             ],
>             "defines": [
>                 "_DEBUG",
>                 "UNICODE",
>                 "_UNICODE",
>                 "near= "
>             ],
>             "cStandard": "c17",
>             "cppStandard": "c++17"
>         }
>     ],
>     "version": 4
> }
> ```

The amount of time I lost with this extension, with this issue. This is really extremely frustrating. Why can't this extension *just work*?? 

I found out that the near= thing must be *exactly* that. In my config it was written  ```"near=[space]"```. 

That's why the completion doesn't work. 
It was defeated by a space. 

I wander how many issues like this one is scattered across the extension.

**Comment by phgmacedo** [comment]
> Let us know if you have any suggestions on how we could be more compatible with compilers which have behaviors we don't know about.

You know _something_. You at least exactly where it is defined.

**Comment by sean-mcmanus** [comment]
The definition coming from a different parser, which we only fallback to in certain cases because the results are not usually accurate. It is undesirable for the majority of cases to fallback to the tag parser for completion results, because it would cause the majority of users to get incorrect completion results. We could potentially add a setting for that, but so far we haven't gotten many requests for that.

**Comment by phgmacedo** [comment]
I cannot reproduce the issue anymore, even with spaces added.
