### ISSUE TITLE
No way to increase 'Run and Debug' font?

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode-cpptools#7228]
Type: Debugger

It would be nice to control the font of the 'Run and Debug' view; is there a setting for it? I did not find it and I find it kind of small (compared to the font I set on editor).

Thanks.

**Comment by sean-mcmanus** [comment]
This would be a request on VS Code and not our C/C++ extension. Also, you might want to provide them with a screenshot, because I don't understand what you mean by it being small compared to the other fonts.

**Comment by dariomx** [comment]
got it, will file it there, thanks Sean
