### ISSUE TITLE
Is there a way to attach to specific thread within process?

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode-cpptools#7229]
I can't find an attribute like threadId or similar on the launch.json schema, is this feature supported? Cause otherwise, I guess I would be attaching to main thread (which is not useful for my usecase).

Thanks.

**Comment by sean-mcmanus** [comment]
Attaching attaches to the entire process (all threads of the process).

**Comment by dariomx** [comment]
Thanks Sean, but if that is the case, how do I tell vscode/debugger to switch to desired thread?

**Comment by sean-mcmanus** [comment]
You have to set a breakpoint in code that the particular thread is executing. The call stack windows should show all the thread call stacks.

**Comment by dariomx** [comment]
I am afraid I do not see such behavior, I only see one of the threads and
not sure which one. Is not there a way to picked desired one? I have thread
id btw.

Thanks.

**Comment by sean-mcmanus** [comment]
Are you sure another thread is executing? If you only see one thread when you break in the debugger, that implies only 1 thread is running, unless there's some strange debugger bug which only shows 1 thread.

@WardenGnaw Any thoughts?

**Comment by dariomx** [comment]
Oh, I see; well, I checked all threads at OS level (Linux), and that
process indeed had many threads. So yeah, maybe something wrong going on ...

**Comment by dariomx** [comment]
Mmm, I take it back; I double checked and indeed I see all threads on the
stack section. After setting up a breakpoint, I can see proper thread
showing the stack, etc.

So yeah, I agree with closing this; sorry for the false alarm.

Thanks.
