### ISSUE TITLE
Can c_cpp_properties.json support wildcard paths?

### ISSUE THREAD

**Issue by bbalp** [microsoft/vscode-cpptools#723]
The scripts I am using to build my projects are generating the dependencies in a folder. It could be very useful in this situation to be able to give a path like this `/my/path/*/include` to simplify `/my/path/dep1/include` `/my/path/dep2/include` `/my/path/dep3/include`

I would be pleased to have your opinion. :)

**Comment by sean-mcmanus** [comment]
This should be implementable in our open source typescript if anyone wants to contribute :)

**Comment by jericbryledy** [comment]
I am not sure if it is related, but I am planning to use this feature for a [Conan](https://conan.io/) project. I plan to add all libraries in my local repo with ".conan/data/*/*/*/*/*/*/include". But I fear that this would include duplicates in the future, like including different versions of the same library. Is there a better approach to this?

**Comment by bobbrow** [comment]
With 0.17.5 you should be able to use `/my/path/**` and it will add all of the relevant paths.  Let us know if that works for you.

**Comment by aaronlelevier** [comment]
Hi, is a middle wildcard not supported though?  For example:

```
/Users/aaron/Documents/github/opencv/modules/*/include/**
```

It's not finding the path, and I'm trying to avoid adding each `opencv/modules/<some-module>/include/**` to the `includePath`

Thanks

**Comment by BillDenton** [comment]
As far as I can see the middle wildcard doesn't work. Our include files are all "include" & "interface" directories in many places. So this only leaves using everything via "${workspaceFolder}/**", or adding each one in turn when required (which may be better where there are duplicated names). I suspect using "${workspaceFolder}/**" isn't great for performance.

**Comment by bobbrow** [comment]
A middle wildcard is not currently supported.  I started a branch that would support this a while ago, but I forget what state it was in and now the branch is out of date.  If anyone wants to get it back in sync with master and finish it, we can consider taking it.  I'll reopen this issue since the original request was not actually addressed.

This is the branch: https://github.com/Microsoft/vscode-cpptools/tree/bobbrow/expand-wildcards

**Comment by dzchoi** [comment]
In my opinion, in addition to supporting the normal "*" it would be also good have "**" as the `globstar` in bash.

From the bash manpage:
> `globstar`
>    If set, the pattern ** used in a pathname expansion context will
>    match all files and zero or more directories and subdirectories.
>    If the pattern is followed by a /, only directories and
>    subdirectories match.

Then, we could use, for example,
- /my/path/\*\*/include
- /my/path/\*\*/include/\*\*/

**Comment by NZSmartie** [comment]
Hey @bobbrow, 
>A middle wildcard is not currently supported. I started a branch that would support this a while ago, but I forget what state it was in and now the branch is out of date. If anyone wants to get it back in sync with master and finish it, we can consider taking it. I'll reopen this issue since the original request was not actually addressed.
>
>This is the branch: https://github.com/Microsoft/vscode-cpptools/tree/bobbrow/expand-wildcards

Looking into how the wildcard support is added to vscode-cpptools, I've come across a couple PRs (#1896, #2136); Their changes do not make much sense into how the recursive `includePath` is implemented. 
Looking around for uses of `IncludePath` don't yield much insight apart from UI settings, json settings and verification of it `includePath`.

It looks like it's all passed off to pre-compiled `cpptools` binaries. which I can't find the source code for. Are you able to link to the repository so that I may continue investigation and figure out how to implement `includePath` globbing.

**Comment by sean-mcmanus** [comment]
@NZSmartie cpptools is closed source. It seems like `"*"` and/or `"**"` in paths should be implementable in the TypeScript. The implementation is complicated and tries to filter out unneeded paths in order to reduce the performance impact on cpptools-srv, but usage of `"*"` and `"**"` in path segments isn't expected to generate the same performance hit as `"**"` at the end of a path.

**Comment by BillDenton** [comment]
@sean-mcmanus @bobbrow Any update on this? All my include headers are in "include" or "interface" directories. Hence I would like to use all sub-directories that end in "include" or "interface", and nothing else.

**Comment by sean-mcmanus** [comment]
@BillDenton No update (the issue hasn't been assigned to a milestone yet). I believe the fix could be implemented in our open source typescript.

**Comment by heaths** [comment]
Seems that way. Off hand I'm not sure of any VSCode-provided APIs, but a package to resolve/expand globstars could be used to format a value to pass to cpptools right from the extension.

**Comment by BillDenton** [comment]
@sean-mcmanus Any update on the time scale for this? Thanks.

**Comment by sean-mcmanus** [comment]
@haolly Not yet -- it's been pushed back repeatedly. It's currently "On Deck" which means we don't have a definite target Milestone yet. The best case might be September, but it certainly could be delayed further.

**Comment by lifo888** [comment]
ran across this Issue.  also interested. any good news yet?

**Comment by sean-mcmanus** [comment]
@lifo888 No news. I don't have an ETA.

**Comment by yne** [comment]
Here is a standalone working example of a glob walker
<details>
<summary>show</summary>

```js
import fs from 'fs';
import path from 'path';
import process from 'process'
class Demo {
	globMatch(pattern, str) {// use picomatch ?
		let i = 0;
		let j = 0;
		while (i < pattern.length && j < str.length) {
			if (pattern.charAt(i) == '*') {
				if (i + 1 == pattern.length)
					return true;
				for (let k = j; k < str.length; k++)
					if (this.globMatch(pattern.substring(i + 1), str.substring(k)))
						return true;
				return false;
			} else {
				if (pattern.charAt(i) != str.charAt(j))
					return false;
				i++;
				j++;
			}
		}
		return (i == pattern.length && j == str.length);
	}
	tryReadDir = (dir) => { try { const res = fs.readdirSync(dir); return res; } catch (e) { return []; } };
	globWalkDir(components, i = 0) {
		if (i >= components.length || components[i] == '**') {
			return path.sep + components.join(path.sep); // end of expression
		}
		const cwd = path.sep + components.slice(0, i).join(path.sep);
		return this.tryReadDir(cwd)
			.filter(name => this.globMatch(components[i], name))
			.filter(match => fs.lstatSync(path.join(cwd, match)).isDirectory())
			.map(match => this.globWalkDir([...components.slice(0, i), match, ...components.slice(i + 1)], i + 1));
		//console.log({components,i, cwd, ls, res})
	}
}

if (!process.argv[2] || !path.isAbsolute(process.argv[2])) {
	throw 'USAGE: glob.mjs ABS_GLOB_EXP';
}
const compo = process.argv[2].split(path.sep).slice(1);

console.log(new Demo().globWalkDir(compo).flat(compo.length));
```
</details>
which can be used in `~/.vscode/extensions/ms-vscode.cpptools-*/dist/main.js` as this :

```js
    /* FIX #723 */
    globMatch(pattern, str) { // TODO: use picomatch ?
      let i = 0;
      let j = 0;
      while (i < pattern.length && j < str.length) {
        if (pattern.charAt(i) == '*') {
          if (i + 1 == pattern.length)
            return true;
          for (let k = j; k < str.length; k++)
            if (this.globMatch(pattern.substring(i + 1), str.substring(k)))
              return true;
          return false;
        } else {
          if (pattern.charAt(i) != str.charAt(j))
            return false;
          i++;
          j++;
        }
      }
      return (i == pattern.length && j == str.length);
    }
    tryReadDir(...args) { try { return fs.readdirSync(...args); } catch (e) { return []; } }
    globWalkDir(components, i = 0) {
      if (i >= components.length || components[i] == '**') {
        return path.sep + components.join(path.sep); // end of expression
      }
      const cwd = path.sep + components.slice(0, i).join(path.sep);
      return this.tryReadDir(cwd)
        .filter(name => this.globMatch(components[i], name))
        .filter(match => fs.lstatSync(path.join(cwd, match)).isDirectory())
        .map(match => this.globWalkDir([...components.slice(0, i), match, ...components.slice(i + 1)], i + 1));
    }
    resolveAndSplit(paths, defaultValue, env) { //// <<<<<
      return paths ? this.resolveDefaults(paths, defaultValue).map(entry =>
          util.resolveVariables(entry, env).split(util.envDelimiter).filter(e => e)
          .map(e => e.replace("${workspaceFolder}", this.rootUri.fsPath).split(path.sep).slice(1))
          .map(e => this.globWalkDir(e).flat(e.length))
          .flat()
      ).flat() : [];
    }
    /* END OF FIX #723 */
```

It's a flexible glob that allow partial path matching (`/usr/l*/**` give `[ '/usr/lib/**', '/usr/lib32/**', '/usr/local/**' ]`)

Tell me if you have any usecase that doesnt work

**Comment by sean-mcmanus** [comment]
@yne Sure, can you submit a PR?

**Comment by yne** [comment]
@sean-mcmanus: I've PR'd a working exemple with `*` path support.

**Comment by BillDenton** [comment]
@sean-mcmanus Slightly confused about the status of this issue and the related issue #10388. What is the status with the latest VS Code 1.79.2 and C/C++ extension v1.16.3? What is the syntax?
Thanks.
