### ISSUE TITLE
On Windows cpptools.exe is 32-bit and running out of memory in large workspace

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#7230]
**Type: LanguageService**

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I'm trying to work with Intellisense in a ~1.5m file workspace with compile_commands.json, which was working before. As of 1.22, it is broken for me. Upon further investigation I see that the cpptools.exe is crashing after going over 4 GB because it's 32-bit process even though I'm running 64-bit VSCode. 

**Steps to reproduce**

1. Run vscode-cpptools on a large workspace such as Chromium.
2. Intellisense doesn't work as cpptools.exe crashes.

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

```
Insert logs here.
```
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Do you know what version worked for you? Did you want us to use less memory or provide a 64-bit vsix for 1.2.2? The last 64-bit vsix we made available is with 1.1.0 at https://download.visualstudio.microsoft.com/download/pr/17062e60-bd73-48b7-bc31-54d71ef5d48d/2895a0d0eda48a734f6575e103524c42/cpptools-win64.vsix .

**Comment by sean-mcmanus** [comment]
It sounds like we have an internal repro we could try.

**Comment by yildirimcagri** [comment]
This seems to be resolved with the platform specific binaries in 1.8.0-insiders3. Thank you!
