### ISSUE TITLE
Sporadic extension timeout

### ISSUE THREAD

**Issue by valerioformato** [microsoft/vscode-cpptools#7231]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Ubuntu 20.04 running on WSL (Win10 build 19041.487)
- VS Code Version: 1.54.3
- C/C++ Extension Version: 1.2.2
- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: no, but I am using VSCode remote on WSL

After a while (i.e.: random amount of time) working on a medium-size project (~500 files, ~70k LOC, with a few external dependencies) Intellisense gets unresponsive and stuck. The remote extension host shows several timeouts and there is no way of recovering besides closing the whole VSCode session and reopen it.

(I have experiences the same issue working on the same project on a OSX Mojave laptop, but I don't have the logs from that)

**Steps to reproduce**

No clear sequence of steps to reproduce this issue. 
1. Open a medium-size project
2. Work on it
3. Realize Intellisense is stuck

c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "configurationProvider": "vector-of-bool.cmake-tools",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Expected behavior**

<details>
  <summary><strong>Logs</strong></summary>

[Remote extension host log](https://gist.github.com/valerioformato/41f6b409f9ae2a36954f1d78a49ff819)
[Language server log](https://gist.github.com/valerioformato/baa30a2e5f732668ced2722d42174f89)
(The command `C/C++: Log Diagnostics` doesn't do anything after intellisense is stuck? I had to restart the session in order to get this, so take it with a grain of salt)
[Log Diagnostics log](https://gist.github.com/valerioformato/5ebaf5f9247fb3982dfed8c8eda925e6)
</details>

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
When it's stuck are cpptools or cpptools-srv using CPU? Are you able to attach to cpptools or cpptools-srv to get a call stack? (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv). From the logs, it appears that the last action is queueing an update to the IntelliSense process. The call stacks might help determine where it's stuck. Do other non-IntelliSense operations like formatting work in this stuck state?

**Comment by valerioformato** [comment]
> When it's stuck are cpptools or cpptools-srv using CPU? Are you able to attach to cpptools or cpptools-srv to get a call stack? (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv). From the logs, it appears that the last action is queueing an update to the IntelliSense process. The call stacks might help determine where it's stuck. Do other non-IntelliSense operations like formatting work in this stuck state?

From what I was able to observe:
- In this state neither `cpptools` not `cpptools-srv` seem to be using the CPU (at least judging by what `top` reports).
- Formatting doesn't work, and syntax highlighting works in a more "primitive" fashion (I don't know how to explain this better, but I can tell when Intellisense has parsed the code because things such as enums change color)

As soon as it freezes again I'll try to attach gdb to the process and get a stack trace

**Comment by sean-mcmanus** [comment]
That suggests there could be a deadlock. Another possibility is our IPC mechanism is hitting some disconnected state. Formatting not working usually means that cpptools is stuck waiting on a request from cpptools-srv to finish.

**Comment by valerioformato** [comment]
I am also experiencing [this issue](https://github.com/microsoft/vscode-cpptools/issues/5558#issuecomment-809178104), I have no idea if this is related or not, but working on even a smaller project has become really impractical.

**Comment by zhackwyatt** [comment]
I too am having this issue, although the color coding works fine for me.  Red error underlines stop updating, intellisense stops working.

Unfortunately due to the fact that I'm on RHEL7, The latest VScode that seems to work is
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 3.10.0-1062.1.2.el7.x86_64
```
with C/C++ of 1.2.2.

**Comment by sean-mcmanus** [comment]
@zhackwyatt The only (potential) solution is to update your OS to one that is compatible with VS Code 1.53.0, because otherwise you don't be able to get any newer version which has a fix. Our C/C++ extension may also have to break compatibility with old Linux OS's around September 2021, because our build machines will also need to be updated from Ubuntu 16 to 18 as Azure images stop being available.

**Comment by zhackwyatt** [comment]
> 
> 
> @zhackwyatt The only (potential) solution is to update your OS to one that is compatible with VS Code 1.53.0, because otherwise you don't be able to get any newer version which has a fix. Our C/C++ extension may also have to break compatibility with old Linux OS's around September 2021, because our build machines will also need to be updated from Ubuntu 16 to 18 as Azure images stop being available.

Right, I didn't know it was fixed in a newer version though.  Thanks.

**Comment by sean-mcmanus** [comment]
@zhackwyatt I don't know if it's fixed either, but it's possible. If you still repro it with the latest version, then we'd need to get more repro info.
