### ISSUE TITLE
Feature Request: Show 'public/protected/private' scope of cursor position

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#7232]
Is it possible to show a status bar item which says what the current visibility is for the cursor position in a header file?

Some of my (legacy) code base headers are huge and have the various sections spread about in the header.

**Comment by Gruntfuggly** [comment]
I was thinking about creating an extension to do it, using regexes, but that's obviously problematic. I am hoping that as you have access to the parsed files, this would be much simpler for cpp-tools.

**Comment by sean-mcmanus** [comment]
There's a similar request at https://github.com/microsoft/vscode-cpptools/issues/7120 .

VS doesn't have this feature so we're unlikely to add it, and the info is not trivially available to show. You could request the feature on VS at https://developercommunity.visualstudio.com/report?space=62&entry=problem .

**Comment by Gruntfuggly** [comment]
Yes - that would effectively be the same thing. I was hoping it would be trivial. Thanks anyway.

**Comment by sean-mcmanus** [comment]
private/protected labels are shown with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders3 (public is the default and is not shown).

**Comment by gimphammer** [comment]
It's sad.....This feature request has been reported 3-year ago, and closed because of no enough upvotes
