### ISSUE TITLE
inconsistent colour formatting

### ISSUE THREAD

**Issue by Wilbo007** [microsoft/vscode-cpptools#724]
![image](https://cloud.githubusercontent.com/assets/3623279/26024440/a52ca5be-3803-11e7-9d34-e11a67bc35e8.png)

![image](https://cloud.githubusercontent.com/assets/3623279/26024443/ac9eb9a4-3803-11e7-80d2-0a2bc91e925c.png)

**Comment by bobbrow** [comment]
This issue does not appear to reproduce on latest versions of the extension.
