### ISSUE TITLE
std::same_as concept causes "constraint not satisfied" error

### ISSUE THREAD

**Issue by mmatrosov** [microsoft/vscode-cpptools#7251]
Type: General

**Describe the bug**
- Ubuntu 20.04.2
- VS Code Version:
```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-44-generic snap
```
- C/C++ Extension Version: 1.2.2
 
**To Reproduce**
Create a .cpp file with the content:

```
template <class T>
concept ParamsConcept = requires {
  { T::kFlag } -> std::same_as<const bool>;
};

template <ParamsConcept P>
class Base {};

struct Params {
  static constexpr bool kFlag = false;
};

class Derived : public Base<Params> {}; // template constraint not satisfied -- type constraint failed for "Params" -- atomic constraint evaluates to falseC/C++(3244)
```

Note that this code compiles fine.

**Expected behavior**
No problems found by the extension

**Additional context**
No error is reported if I replace `std::same_as` with `std::convertible_to`.

**Comment by sean-mcmanus** [comment]
What compiler (and concepts library implementation) are you using? The code gives errors with gcc and cl, but not clang. I'll file a VS bug against our shared parser but I'm not sure if the code is valid C++ or not.

**Comment by sean-mcmanus** [comment]
The VS issue is at https://developercommunity.visualstudio.com/t/C20-IntelliSense-with-clang-mode-gives/1384769

**Comment by mmatrosov** [comment]
I am using clang 11.1 with libstdc++ 10. Hm, indeed, I see how gcc cannot compile the code. Which also seems like a bug to me.

**Comment by sean-mcmanus** [comment]
It was a bug with clang 11.1 that got fixed with clang 13.
