### ISSUE TITLE
Code formatting automatically deletes space between `#define` and `something`

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode-cpptools#7254]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version:Insiders
- C/C++ Extension Version: 1.2.2
- Other extensions you installed (and if the issue persists after disabling them): NO
- Does this issue involve using SSH remote to run the extension on a remote machine?: NO
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**- Here in before and after you can see that it automatically deletes spaces between #define and something after define**
**Like I had `#define ll ************* long long int` . Here * means spaces.**
**But after formatting it becomes `#define ll long long int`**

**Before**
![beforee](https://user-images.githubusercontent.com/54276661/112884942-bdbf1e80-90ed-11eb-852a-b5daa5de4390.PNG)

**After**
![after](https://user-images.githubusercontent.com/54276661/112884950-c3b4ff80-90ed-11eb-9e2b-e92ed30d9a52.PNG)

**Steps to reproduce**

1. Make a folder and inside it create a cpp file.
2. Copy code from [pastebin](https://pastebin.com/PLwvA1pQ)
3. Format file using clang-format according to settings.

**Expected behavior**

What I want is that it should not delete those spaces and everything else like formatting style for braces etc. remain same as it is now.
**And yes, I use gcc compiler on my system. Editor uses the default clang format bundled with the extension and I also didn't created any  file for specifying any format settings.**

**Comment by lakshits11** [comment]
Well I got the `AlignConsecutiveMacros: true` to work. But still I am not able to move brackets to new line using vcFormat. Please help me with that. Thank You!

**Comment by lakshits11** [comment]
I did that too but still got problems.

**Comment by sean-mcmanus** [comment]
Are you able to provide more info on the problem?
