### ISSUE TITLE
_MSVC_TRADIONAL has value 1 in intellisense even if /Zc:preprocessor is specified (MSVC 19.28.29913)

### ISSUE THREAD

**Issue by h-bex** [microsoft/vscode-cpptools#7259]
**Type: LanguageService**

I just created a small c++ 17 project (see the files attached). Hovering information I get from intellisense about the symbol _MSVC_TRADITIONAL shows a 1.

**Describe the bug**
- OS and Version: Windows 10 10.0.19042 Build 19042
- VS Code Version: 1.54.3
- C/C++ Extension Version: Microsoft (R) C/C++Compiler Version 19.28.29913 for x64
- Other extensions you installed (and if the issue persists after disabling them): Only C/C++ for Visual Studio Code V 1.2.2
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- Hovering over _MSVC_TRADITIONAL shows
> #define _MSVC_TRADITIONAL 1 Expands to 1.

  Expected is

> #define _MSVC_TRADITIONAL 0 Expands to 0

**Steps to reproduce**
1. From a visual studio 2019 command prompt open the directory containing the files attached with code
2. Hover over _MSVC_TRADITIONAL; It shows the unexpected behaviour

**Expected behavior**
See above

1. Logs from the command `C/C++: Log Diagnostics` (see File "C, C++ Log Diagnostics.txt")
2. Logs from [the language server](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) (See File "Language Server Output.txt")
<details>
  <summary><strong>Logs</strong></summary>

```
C, C++ Log Diagnostics.txt
Language Server Output.tx
```
</details>

**Screenshots**

See "BugIntellisense.png"

**Additional context**
N/A

**NOTE**
Even adding a line at the top with the content
`#define _MSVC_TRADITIONAL 0
`
does not change the behaviour (for intellisense _MSVC_TRADITIONAL is still 1). However adding
```
#undef _MSVC_TRADITIONAL
#define _MSVC_TRADITIONAL 0
```
will change the behaviour for intellisense to show _MSVC_TRADITIONAL as 0.

![BugIntellisense](https://user-images.githubusercontent.com/35868329/112984345-111d8500-915f-11eb-91f1-c21726b11379.png)
[BugVSCode.zip](https://github.com/microsoft/vscode-cpptools/files/6228851/BugVSCode.zip)

**Comment by sean-mcmanus** [comment]
Currently, we don't handle the /Zc:preprocessor command argument, but it's already fixed in an internal branch that handles like 40 other cl.exe arguments, but the changes aren't ready to ship yet.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders
