### ISSUE TITLE
how to debug this extension

### ISSUE THREAD

**Issue by NumberX** [microsoft/vscode-cpptools#726]
I have try to debug this extension ,by doing this step:
1-I copied a folder of extension  to new directory in desktop.
2-I opened this folder ny vscode.
3-i create it an launch.jscon:
{
   "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "protocol": "inspector",
            "request": "launch",
            "name": "Lancer le programme",
            "program": "${workspaceRoot}/out/src/main"
        }
    ]
}

but he dont run .can you tell how i need to do it.
Many thanks.

**Comment by pieandcakes** [comment]
@NumberX what part of the extension are you trying to debug?
