### ISSUE TITLE
operators of Template Class can't be recognized as operator when it is used in another template function.

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode-cpptools#7260]
**Type: LanguageService**

**Describe the bug**
- OS and Version:win 10 (2004)
- VS Code Version:1.54.3
- C/C++ Extension Version:v1.3.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): None
- Does this issue involve using SSH remote to run the extension on a remote machine?: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
when use the template function, the `vector<T>`'s operator `=` won't be recognized as `operatorOverload`, but when use it normally, the `=` will be recognized as an operator.
![](https://raw.githubusercontent.com/JoeyRxy/tmp/master/vscode-cpp-ls-bug1.png)
![](https://raw.githubusercontent.com/JoeyRxy/tmp/master/vscode-cpp-ls-bug2.png)

**Comment by sean-mcmanus** [comment]
This works in VS after you use the UI to assign a type to T, so this would be tracked by https://github.com/microsoft/vscode-cpptools/issues/1946 .
