### ISSUE TITLE
Add a heartbeat/keep-alive to detect orphaned cpptools processes

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#7262]
Breaking this out of https://github.com/microsoft/vscode-cpptools/issues/5316 , as it's not entirely clear that making this change would address that issue.

Opening this to track adding a heartbeat or keep-alive in cpptools.  In a separate thread, cpptools would send a message to the TypeScript side.  The TypeScript side, if present, would send a response immediately when receiving it.  In another separate thread in cpptools, it would check to see if a response had been received (by the main thread), using a timeout.  If that timeout was exceeded, it would assume that either the TypeScript side is not present or the main thread has not been able to process message, and would kill the process.

**Comment by Colengms** [comment]
The response timeout needs to be sufficiently long to include any valid amount of time spent processing a single message in the message handler.  That would include cases in which some operations pause to wait for a TU creation to complete (so should include maximum acceptable TU creation time).  Otherwise, existing perf issues will be transformed into apparent crash issues, as cpptools will go missing.

**Comment by sean-mcmanus** [comment]
I think the keep-alive should be checked in a completely separate thread from any thread that can get blocked on an IntelliSense operation.
