### ISSUE TITLE
Default cppbuild task doesn't have C/C++ standard flag

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vscode-cpptools#7268]
VS Code version: 1.54.3
Extension version: 1.3.0-insiders2

I don't really know where to put this, please tell me if this issue should be moved.

The default `cppbuild` task doesn't add a C/C++ standard flag when an explicit standard is set in the compiler configurations. It should be added automatically to prevent confusion.

Build output:
```
> Executing task: C/C++: clang-12.exe build active file <

Starting build...
C:\llvm-mingw\bin\clang-12.exe -g [REDACTED] -o [REDACTED] -glldb -lc++ -lunwind -IC:\vcpkg\installed\x64-mingw-dynamic\include -LC:\vcpkg\installed\x64-mingw-dynamic\lib -lcpr -lcurl
Build finished successfully.
```
(Notice there's no `-std=...` flag)

My compiler configuration:
```
{
    "configurations": [
        {
            "name": "llvm-mingw",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\vcpkg\\installed\\x64-mingw-dynamic\\include"
            ],
            "defines": [
                "_DEBUG"
            ],
            "compilerPath": "C:\\llvm-mingw\\bin\\clang-12.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-clang-x64",
            "compilerArgs": [
                "-glldb",
                "-lc++",
                "-lunwind",
                "-IC:\\vcpkg\\installed\\x64-mingw-dynamic\\include",
                "-LC:\\vcpkg\\installed\\x64-mingw-dynamic\\lib",
                "-lcpr",
                "-lcurl"
            ]
        }
    ]
}
```
(`cStandard` and `cppStandard` are set explicitly)

**Comment by sean-mcmanus** [comment]
What is your tasks.json? The tasks.json is where the build flags are set. The compilerArgs in c_cpp_properties.json are separate and only used for IntelliSense.

**Comment by longnguyen2004** [comment]
I don't have a `tasks.json`, since I don't want to duplicate the settings between two files. If it's not possible to add the flag to the pre-provided task, is there a way to get the currently set standard, through command substitution?

**Comment by sean-mcmanus** [comment]
Okay, I see, you're using the Run: Build Task (without an existing tasks.json). Normally, I use F5, Build and Debug Active File, or Configure Default Build Task, which generates the tasks.json. 

The scenario you're hitting where it uses the compilerArgs from c_cpp_properties.json seems like a corner case that wasn't even aware of, and it doesn't seem like the scenario was fully developed (i.e. the cppStandard not being used).

Adding a `-std=` command line should be a workaround.

**Comment by longnguyen2004** [comment]
Unfortunately I'm using Clang, and it doesn't like the `-std=c++17` flag when invoked with `-x c` during the compiler probe, so it'll fail.

I can workaround this with a `tasks.json`, but not having to update 2 files to change the standard is definitely better.

**Comment by sean-mcmanus** [comment]
Ah, I see, I've filed bug https://github.com/microsoft/vscode-cpptools/issues/7269 .

Another (more complicated) alternative is to switch Makefile or CMake to build and set Makefile/CMake Tools as the configurationProvider, in which case the build and IntelliSense configurations will be shared.

We have a related issue tracking propogating c_cpp_properties.json settings to tasks.json https://github.com/microsoft/vscode-cpptools/issues/6080 .

**Comment by bobbrow** [comment]
Ok, just to make sure we understand the action item for this issue, this is what we're planning to do:
* add the cppStandard or cStandard into the compile command for the file (assuming we can get the file type before the task provider executes)

**Comment by longnguyen2004** [comment]
Yes that is what I want to see.

**Comment by sean-mcmanus** [comment]
The issue blocking usage of -std=c++17 is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders
