### ISSUE TITLE
Opening large array in watch hangs debugging session

### ISSUE THREAD

**Issue by praveen-miller** [microsoft/vscode-cpptools#727]
VSCode Version: Code 1.12.1 (f6868fc, 2017-05-04T21:40:39.245Z)
OS Version: Linux x64 4.4.0-75-generic
Extensions:
Extension	Author	Version
Bookmarks	alefragnani	0.14.1
code-gnu-global	austin	0.2.1
githistory	donjayamanne	0.2.0
cppcheck	matthewferreira	0.0.7
vscode-clang	mitaki28	0.2.2
cpptools	ms-vscode	0.11.0

Steps to Reproduce:
1. Add a watch expression for a large array (in this case 65535)
2. Click dropdown arrow for watch expression/array in watch window
. This hangs the debugging session and the circle spins forever

**Comment by praveen-miller** [comment]
Forgot to mention... Language is C++ and I'm cross debugging.

**Comment by pieandcakes** [comment]
@praveen-miller if you disable pretty-printing in your launch.json does it go faster? Pretty-printing makes resolution slower and that's an issue with gdb that we won't be able to solve.

**Comment by praveen-miller** [comment]
Thanks for the quick reply, pieandcakes.

I do not have pretty-printing explicitly enabled in my launch.json. Is it enabled by default?

**Comment by Yuki-Nagato** [comment]
I'm still experiencing this problem. Disable pretty-printing for gdb doesn't work.

VSCode Version: 1.26.1
OS Version: Windows 10 1803
Compiler and gdb: mingw-w64 8.1.0 x86_64
C/C++ Extension Version: 0.18.1
