### ISSUE TITLE
Getting Started experience

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#7273]
VS Code is working on a "getting started" workflow (https://github.com/microsoft/vscode/issues/118402) that would enable us to plug in and provide information for new and returning users.  This would make it easier for folks to get onboarded to using the extension with links to tutorials, etc.

**Comment by Colengms** [comment]
Re-opening as only a preliminary implemenation was included in 1.4.0.  There is more work to do here.

**Comment by jureid** [comment]
There are two enhancements we want to make:

1. Add a when clause for the presence of CMakeLists.txt. When we detect CMakeLists.txt:

    - Hide the steps for Edit IntelliSense Configuration and Run and Debug C++ file
    - Show step for Install CMake Tools 

    (Current behavior is to show all three of these steps always)

    - Dependent on https://github.com/microsoft/vscode/issues/121778 

2. Add a completionEvent for already having a C++ build task / debug configuration.
