### ISSUE TITLE
Intellisense squiggles on std members

### ISSUE THREAD

**Issue by Kerryliu** [microsoft/vscode-cpptools#728]
I am getting error squiggles on various std members: 
![screenshot from 2017-05-15 17-54-13](https://cloud.githubusercontent.com/assets/1123996/26081145/8523ec9c-3997-11e7-8cba-3247b00fa41b.png)

I am using the default paths in c_cpp_properties.json:
![screenshot from 2017-05-15 17-55-51](https://cloud.githubusercontent.com/assets/1123996/26081202/be6282de-3997-11e7-8ab4-a291cbc95e09.png)

What's odd is that I'm getting all the members as autocomplete options, but the squiggles still appear.  
I'm running vscode 1.12.1 on Linux.

**Comment by bobbrow** [comment]
Autocomplete is still powered by the old IntelliSense engine (aka. tag parser), so that would explain why the results are not in sync with the error squiggles.  I'll see if I can reproduce your issue on Linux.

**Comment by sean-mcmanus** [comment]
It doesn't repro for me, but I have a 6.2.0 header. Can you open iostream and look for any #define macros that might need to be set for the std::cout to be visible?

**Comment by Kerryliu** [comment]
It doesn't seem to be occurring on just iostream members.  It also occurs when using things such as vectors and lists.  The problem does not seem to occur when using other libraries, only "usr/include/c++/6.3.1" seems to be having issues.

**Comment by sean-mcmanus** [comment]
What is your Linux distro and version or how did you get the libstdc++ 6.3.1?

**Comment by Kerryliu** [comment]
I am using Arch Linux, however I think Fedora 26 which is currently in alpha has the same if not a newer version.

**Comment by sean-mcmanus** [comment]
Okay, I was able to download the gcc-6.3.0 headers and I reproed the bug. I'm seeing errors with the system headers.

**Comment by Ashod** [comment]
Same issue with gcc-5.2.1 on Ubuntu 16.04. Though not sure if this is due to 0.11.1 update issues reported elsewhere (c.f. #741), which I suffer as well.

**Comment by CaptainDaVinci** [comment]
Yes, same bug can be reproduced on Ubuntu(16.10) as well. It is not limited to `<iostream>` header.

**Comment by sean-mcmanus** [comment]
I got it working with 6.3 via adding "/usr/include/x86_x64-linux-gnu" and "/usr/include/x86_64-linux-gnu/c++/6.3.0" to the includePath ("/usr/include/c++/6.3.0" is also required). Let us know who still has issues. These sort of issues can be diagnosed via traversing the headers until you find the first header that can't be found...we should probably do that automatically for users though.

**Comment by kilometer3604** [comment]
For Arch Linux, add both `"/usr/include/c++/6.3.1"` and `"/usr/include/c++/6.3.1/x86_64-pc-linux-gnu"` to `includePath`.

**Comment by bobbrow** [comment]
We put out a fix for the default include paths in 0.11.3.  It was working in 0.11.0, but unfortunately regressed in 0.11.1 right when we turned on the new IntelliSense engine for everyone.

Please let us know if that works for you.
