### ISSUE TITLE
Multiroot GoToPrevDirectiveInGroup shows a popup

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7283]
unfortunately， when in multifolder workspace, it will show a popup window which chosing the workspace when using command `GoToPrevDirectiveInGroup` and `GoToNextDirectiveInGroup`

_Originally posted by @heartacker in https://github.com/microsoft/vscode-cpptools/issues/4779#issuecomment-812265776_

**Comment by michelleangela** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders4
