### ISSUE TITLE
Operator placement new error in problems window (PlatformIO project)

### ISSUE THREAD

**Issue by leventesen** [microsoft/vscode-cpptools#7289]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.55.0
- C/C++ Extension Version: v1.3.0-insiders3
- Project Based On: PlatformIO IDE v2.3.1
- Base Framework: Arduino
- Platform: AVR Microcontroller (GCC based)
- STL Header Files: Absent (Limited Platform)
- "cstdlib, new" Header Files: Absent (Limited Platform)

Project compiles but there is an error in problems window like "First parameter of the placement function must be size_t type [C/C++(351)]" (Manually translated from locale Turkish message text).

This issue is similiar to other IntelliSense placement new issues with some exceptions:
- v1.3.0-insiders3 is installed which says that it has bugfix of this issue 
- There are no necessary header files because of the limited platform, so std::size_t is not defined

What can be done in this situation?

**Comment by leventesen** [comment]
I found a possible workaround by wrapping the lines with `#ifndef __INTELLISENSE__` and `#endif` macros but it's annoying.

**Comment by sean-mcmanus** [comment]
This is already being tracked by https://github.com/microsoft/vscode-cpptools/issues/6246. You can upvote https://developercommunity.visualstudio.com/t/CC-IntelliSense-gives-errors-regardin/1207998 (if you have a developer community account).
