### ISSUE TITLE
The #include order throws a fatal error. Include path doesn't add the -I switch.

### ISSUE THREAD

**Issue by MarcM1998** [microsoft/vscode-cpptools#7293]
Type: General
I'm new to using the C++ extension of Visual Studio Code. I have some experience compiling C++ code using other IDEs.

**Describe the bug**
- OS and Version: Windows 10 Home
- VS Code Version: 1.55
- C/C++ Extension Version: v1.3.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): Jupyter Pylance Python

When I build a cpp file, in the terminal I can see the call to the compiler g++.exe the flag -g of the source and the -o flag of the output executable. There is no -I flag. The #include throws an error.
What I see:
Starting build...
"C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\g++.exe" -g C:\Users\marmo\Desktop\horario\example.cpp -o C:\Users\marmo\Desktop\horario\example.exe
C:\Users\marmo\Desktop\horario\example.cpp:4:10: fatal error: boost\accumulators\accumulators.hpp: No such file or directory
 #include <boost\accumulators\accumulators.hpp>

**To Reproduce**
*Source code*
```
#include <iostream>
#include <iterator>
#include <algorithm>
#include <boost\accumulators\accumulators.hpp>
#include "boost\lambda\lambda.hpp"
#include <boost\algorithm\string.hpp>

 int main()
 {
   using namespace boost::lambda;
     typedef std::istream_iterator<int> in;
 
     std::for_each(
         in(std::cin), in(), std::cout << (_1 * 3) << " " );
 }
```

*tasks.json*
```
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                // "-I",
                // "C:\\Users\\marmo\\Downloads\\Cpp_libs\\boost_1_75_0"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```
*c_cpp_properties.json*
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${default}",
                "C:\\Users\\marmo\\Downloads\\Cpp_libs\\boost_1_75_0"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "windows-gcc-x64"
        }
    ],
    "version": 4
}
```
**Expected behavior**
I don't know if I have to edit the args in the tasks.json file, but according to the json files I have seen, I shouldn't.

**Additional context**
If I add the the elements "-I", "C:\\Users\\marmo\\Downloads\\Cpp_libs\\boost_1_75_0" to the args list in the tasks.json file, the build instruction works correctly, but the includePath option should affect all tasks in the folder, isn't that its purpose?

**Comment by sean-mcmanus** [comment]
This is "by design". The includePath in c_cpp_properties.json is not used for building, just IntelliSense. You're supposed to add the -I to your tasks.json. We have some other existing issues tracking potential unification of the settings.

**Comment by ndanilo8** [comment]
I'm facing the same problem.. whenever I try to compile it throws a: fatal error: "somelibrary".h: No such file or directory

I've added "-I", to "compilerArgs": [] found in c_cpp_properties.json

but it didn't work.. Now I'm stuck and can't seem to compile my project!

**Comment by ndanilo8** [comment]
also I don't seem to have any "tasks.json"
![image](https://user-images.githubusercontent.com/31519404/114753421-5a6cf780-9d4f-11eb-8ac4-07b83f98d7a1.png)

**Comment by sean-mcmanus** [comment]
c_cpp_properties.json isn't used for compiling. You can try compiling via the command line or tasks.json. You can try using the Configure Default Build Task command or "Build and Debug Active File".

**Comment by ndanilo8** [comment]
Now I can see Tasks.json and added "-I", "pathToLibFolders", but that didn't work :(

**Comment by sean-mcmanus** [comment]
What is the error? How you running the task?

**Comment by ndanilo8** [comment]
![image](https://user-images.githubusercontent.com/31519404/114758870-5ba12300-9d55-11eb-9aa6-ca1a33c94b38.png)
![image](https://user-images.githubusercontent.com/31519404/114758960-7a9fb500-9d55-11eb-8dd3-4709aeeb1c11.png)
this is the error I get, my tasks.json looks like this

I compile by using this on the lower left part of vscode

![image](https://user-images.githubusercontent.com/31519404/114759040-96a35680-9d55-11eb-9713-0b013785c399.png)

**Comment by sean-mcmanus** [comment]
This seems like a PlatformIO issue. Clicking that check button doesn't appear to build via tasks.json. You'd have to look into the PlatformIO documentation on how to configure the compiler arguments.

**Comment by ndanilo8** [comment]
Okay I will check that

**Comment by ndanilo8** [comment]
I just got tired of trying to debug.. went ahead and reinstalled everything vscode related. It is working now
