### ISSUE TITLE
libc includes not found in vs code

### ISSUE THREAD

**Issue by hyyu** [microsoft/vscode-cpptools#73]
VS code doesn't find include paths such as /usr/include
![screenshot from 2016-06-15 14 45 20](https://cloud.githubusercontent.com/assets/13220072/16080189/d752c66a-3307-11e6-93f5-a721bd62d31e.png)

How is it possible to make vs code recognize it?

**Comment by dmazuronak** [comment]
Hi,

you should put the path into includePath property in the file **c_cpp_properties.json** located in **.vscode** folder.

**Comment by sridmad** [comment]
By default the extension does not process outside of the root folder. Adding the include path requires generating c_cpp_properties.json if it is not already present.

See Specifying Additional Include Directories for Better Symbol Support section in https://code.visualstudio.com/docs/languages/cpp

**Comment by hyyu** [comment]
Thank you for your answers. I'll be checking the help =)

**Comment by ZHOUYue67** [comment]
Hi, @sridmad, is it possible to set those include paths in global settings? Sometimes I just want to edit a single .c file and not to create a workspace only for this purpose. I think headers like `stdio.h`, `string.h`, etc. should be available by default for every .c file.
