### ISSUE TITLE
Debugger Stops after first breakpoing

### ISSUE THREAD

**Issue by runfastman** [microsoft/vscode-cpptools#730]
Often the debugger stops working after hitting the first break-point.  You can't step in or over or go to the next break-point.  Is this a known issue, I could not find it.  Any work around, it is driving me insane?

C++ Package 0.11.0

**Comment by pieandcakes** [comment]
@runfastman Can you provide me with an example or some additional steps to duplicate this?

What OS are you on, which debugger are you using, etc...

**Comment by runfastman** [comment]
OS is osx El Capitan

all Extensions
C++ Package 0.11.0
Clang-Format 1.4.0

c++ Launch - version 0.2.0,  MIMode lldb

It is a large project given to me so I can't specify how to reproduce.  I was hoping someone else had the same issue.

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
