### ISSUE TITLE
C/C++ plugin freezes on "modify a file "

### ISSUE THREAD

**Issue by thanhlev** [microsoft/vscode-cpptools#7311]
Issue Type: <b>Bug</b>

1. open c/c++ file.
2. pin the file.
3. split the current window.
4. edit file
Issue:
- VS code  freezes
- Able to move the mouse, but vscode no response.
- 100% CPU consumsion in one core.
-  No click, wait for 8 -10 seconds, VS can response, but happen requently. 
- If continue to click, VScode popup a window that ask for reopen/close .... 

Extension version: 1.3.0-insiders4
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:02:21.560Z)
OS version: Linux x64 4.19.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.42GB (5.22GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 60da3c6c-0147-414a-80bf-3798a3b8b317|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by sean-mcmanus** [comment]
We're not able to repro the issue and need more info. What process is using the CPU? Are you able to get snapshot call stack of that process (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) or profiler logging (https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues)? Does the issue repro with 1.3.0-insiders3 (https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders3) you'll need to change the extensions.autoUpdate setting to avoid auto-updating to 1.3.0-insiders4?
