### ISSUE TITLE
IntelliSense is unable to use recursive search

### ISSUE THREAD

**Issue by Diamondemon** [microsoft/vscode-cpptools#7314]
**Type: LanguageService**

**Describe the bug**
- OS and Version: Windows 10, 20H2
- VS Code Version: 1.55.0 (latest)
- C/C++ Extension Version: v1.3.0-insiders4
- Other extensions: HTML CSS Support for IntelliSense (issue persists after disabling)
- Does not involve using SSH remote to run the extension on a remote machine.
- I am working on a bunch of .cpp and .h files that I use as libraries for an arduino project. I do not use VSCode to compile. My problem is that I am not able to make clear for IntelliSense where to find all the Arduino and Esp32 libraries I use. I modified the IncludePath, and did not manage to make recursive search work properly (specifying one folder is okay, but I have too much folders to copy/paste them all one by one). Please note that all the code compiles well in Arduino with the same directories, so my files are in fact on my computer.

**Steps to reproduce**

1. Go to "C/C++ configuration" (bottom right, label indicating the platform you are working on)
2. Click on "Modify configurations (UI)"
3. Scroll down to "Include Path"
4. Use recursive search to dig two folders deep before reaching a header file that is not in the workspace.

**Expected behavior**

You should not get any error "Cannot open file ...", and all the autocompletion should work properly.

**Screenshots**

![image](https://user-images.githubusercontent.com/75697279/113940816-5ea08e80-97fe-11eb-95a1-84def5867f77.png)

All my header files are in subdirectories of the directory specified before "/**" (above image)but they are not found (see below):

![image](https://user-images.githubusercontent.com/75697279/113940980-a7584780-97fe-11eb-9460-a67b6f64811c.png)
(Translation: impossible to open source file "BLEDevice.h")

**Comment by sean-mcmanus** [comment]
This bug only repros with 1.3.0-insiders4, right? I think we have a fix pending for our 1.3.0-insiders5. We were incorrectly resolving symlinks during recursive includes generation.

**Comment by sean-mcmanus** [comment]
Are there symlinks under the 1.0.4 folder?

**Comment by Diamondemon** [comment]
> Are there symlinks under the 1.0.4 folder?

I am a bit new with the vocabulary. What do you mean by "symlink"?

**Comment by Diamondemon** [comment]
> This bug only repros with 1.3.0-insiders4, right? I think we have a fix pending for our 1.3.0-insiders5. We were incorrectly resolving symlinks during recursive includes generation.

I may not be able to answer this question, I started working with VSCode in the morning. But according to the fact that no similar issue was reported on the github, I would say "yes".

**Comment by sean-mcmanus** [comment]
Symbolic link. If you run the "dir" command from the command line in directory with a symlink you'd see something like "01/28/2021  03:22 PM    <SYMLINKD> " or you'd see an arrow icon in Explorer.

![image](https://user-images.githubusercontent.com/19859882/113948848-b3261880-97c2-11eb-94fc-d1d99e46b516.png)

We should have a fix today or tomorrow, so you could let us know if it's fixed with that build.

**Comment by Diamondemon** [comment]
I am pretty sure there is no symlink. Anyway the problem happened when I took the first link and replaced "/esp32" with "/**", so this is probably not a symlink problem.

**Comment by Diamondemon** [comment]
I played around with the versions of IntelliSense for C/C++ and did not manage to make it work even on older versions. But I think this was off topic anyway.
However, since coming back to insiders4 I had an odd behaviour. Sometimes the recursive search did work, but only if I put it as the first link. And now it does not work anymore.
I also saw that some of the files in my workspace folder are found, others are not. This got me really lost.

**Comment by sean-mcmanus** [comment]
When you run the C/C++: Log Diagnostics command do you see any paths under 1.0.4 in the Includes output and/or can you provide that output?

**Comment by Diamondemon** [comment]
I do not know how to run this command, could you please enlighten me?

**Comment by sean-mcmanus** [comment]
From the menu View->Command Palette->C/C++: Log Diagnostics.

**Comment by sean-mcmanus** [comment]
Recursive includes is picking up 1.0.4\VARIANTS\ALKSESP32 . Where is BLEDevice.h located?

**Comment by Diamondemon** [comment]
BLEDevice.h is located inside 1.0.4\libraries\BLE\src

**Comment by sean-mcmanus** [comment]
Can you set C_Cpp.loggingLevel to "Debug", then run the C/C++: Reset IntelliSense Database command, and look at the "C/C++" output pane, and look for the "tag parsing" messages and see what tag parsing message appear for folders under 1.0.4, i.e. does libraries\BLE\src appear with BLEDevice.h?

**Comment by Diamondemon** [comment]
Here was the result:
--------------------------------------------------
Exclusion de fichier : **/.vscode
Exclusion de fichier : **/.git
Exclusion de fichier : **/.svn
Exclusion de fichier : **/.hg
Exclusion de fichier : **/CVS
Exclusion de fichier : **/.DS_Store
Rechercher dans l'exclusion : **/node_modules
Rechercher dans l'exclusion : **/bower_components
Rechercher dans l'exclusion : **/*.code-search
Remplissez le cache de fin d'inclusion.
Découverte de fichiers...
  Traitement du dossier (récursif) : D:/PROGRAMMES/GCC/I686-PC-MINGW32/INCLUDE/
  Traitement du dossier (récursif) : D:/PROGRAMMES/GCC/INCLUDE/C++/6.2.0/
  Traitement du dossier (récursif) : D:/PROGRAMMES/GCC/LIB/GCC/I686-PC-MINGW32/6.2.0/INCLUDE/
  Traitement du dossier (récursif) : D:/PROGRAMMES/GCC/LIB/GCC/I686-PC-MINGW32/6.2.0/INCLUDE-FIXED/
  Découverte de fichiers : 2296 fichier(s) traité(s)
  4 fichier(s) supprimé(s) dans la base de données
Découverte de fichiers terminée.
Analyse des fichiers restants...
  Analyse : 0 fichier(s) traité(s)
Analyse des fichiers restants terminée.
0 suggestion(s) de chemin Include découverte(s).
boucle inactive : réanalyse du document actif
Recherche des erreurs de syntaxe : file:///c%3A/Users/Julien/Desktop/Ecole/Telecom/PACT/pact31/Modules/SE_bracelets/Arduino/libraries/Leds_strip/Leds_strip.cpp
Mise en file d'attente de la mise à jour IntelliSense pour les fichiers dans l'unité de traduction de : C:\USERS\JULIEN\DESKTOP\ECOLE\TELECOM\PACT\PACT31\MODULES\SE_BRACELETS\ARDUINO\LIBRARIES\LEDS_STRIP\LEDS_STRIP.CPP
Nombre de tildes d'erreur : 8
Durée de mise à jour d'IntelliSense (s) : 0.261
0 suggestion(s) de chemin Include découverte(s).
0 suggestion(s) de chemin Include découverte(s).
boucle inactive : réanalyse du document actif
Recherche des erreurs de syntaxe : file:///c%3A/Users/Julien/Desktop/Ecole/Telecom/PACT/pact31/Modules/SE_bracelets/Arduino/libraries/BluetoothWIZZ/BluetoothWIZZ.cpp
Mise en file d'attente de la mise à jour IntelliSense pour les fichiers dans l'unité de traduction de : C:\USERS\JULIEN\DESKTOP\ECOLE\TELECOM\PACT\PACT31\MODULES\SE_BRACELETS\ARDUINO\LIBRARIES\BLUETOOTHWIZZ\BLUETOOTHWIZZ.CPP
Nombre de tildes d'erreur : 49
Durée de mise à jour d'IntelliSense (s) : 0.276
0 suggestion(s) de chemin Include découverte(s).
0 suggestion(s) de chemin Include découverte(s).
boucle inactive : réanalyse du document actif
Recherche des erreurs de syntaxe : file:///c%3A/Users/Julien/Desktop/Ecole/Telecom/PACT/pact31/Modules/SE_bracelets/Arduino/libraries/Leds_strip/Leds_strip.cpp
Mise en file d'attente de la mise à jour IntelliSense pour les fichiers dans l'unité de traduction de : C:\USERS\JULIEN\DESKTOP\ECOLE\TELECOM\PACT\PACT31\MODULES\SE_BRACELETS\ARDUINO\LIBRARIES\LEDS_STRIP\LEDS_STRIP.CPP
Nombre de tildes d'erreur : 8
Durée de mise à jour d'IntelliSense (s) : 0.272
0 suggestion(s) de chemin Include découverte(s).
0 suggestion(s) de chemin Include découverte(s).
Service de navigation du code initialisé
Remplissez le cache de fin d'inclusion.
Découverte de fichiers...
  Traitement du dossier (récursif) : D:/PROGRAMMES/GCC/I686-PC-MINGW32/INCLUDE/
  Traitement du dossier (récursif) : D:/PROGRAMMES/GCC/INCLUDE/C++/6.2.0/
  Traitement du dossier (récursif) : D:/PROGRAMMES/GCC/LIB/GCC/I686-PC-MINGW32/6.2.0/INCLUDE/
  Traitement du dossier (récursif) : D:/PROGRAMMES/GCC/LIB/GCC/I686-PC-MINGW32/6.2.0/INCLUDE-FIXED/
  Découverte de fichiers : 2296 fichier(s) traité(s)
  0 fichier(s) supprimé(s) dans la base de données
Découverte de fichiers terminée.
Analyse des fichiers restants...
  Analyse : 0 fichier(s) traité(s)
Analyse des fichiers restants terminée.
boucle inactive : réanalyse du document actif
Recherche des erreurs de syntaxe : file:///c%3A/Users/Julien/Desktop/Ecole/Telecom/PACT/pact31/Modules/SE_bracelets/Arduino/libraries/Leds_strip/Leds_strip.cpp
Mise en file d'attente de la mise à jour IntelliSense pour les fichiers dans l'unité de traduction de : C:\USERS\JULIEN\DESKTOP\ECOLE\TELECOM\PACT\PACT31\MODULES\SE_BRACELETS\ARDUINO\LIBRARIES\LEDS_STRIP\LEDS_STRIP.CPP
Nombre de tildes d'erreur : 8
Durée de mise à jour d'IntelliSense (s) : 0.271
0 suggestion(s) de chemin Include découverte(s).
0 suggestion(s) de chemin Include découverte(s).
--------------------------------------------------------------

I am very sorry that it is in french, only the outputs and debugs are not in english (and I do not know how to change it).

I then realize that this file is not related to BLEDevice.h so I opened the one related to it, and ran the command again.

I was afraid that this may have added too much information into the log and restarted VSCode in order to run it again. 
While I opened the C/C++ output pane before running the reset database command, IntelliSense was digging into the whole 1.0.4 folder.

All my include errors magically disappeared. I guess this means the issue should be marked as solved?

**Comment by sean-mcmanus** [comment]
The Reset IntelliSense Database might have fixed the issue.

**Comment by Diamondemon** [comment]
Yes, thank you for your support and teaching me about the functionalities of VSCode
I will wait for some days to see if the issue pops again. If not, I will close the issue.
