### ISSUE TITLE
Trouble with breaking on uncaught exceptions with MinGW gdb

### ISSUE THREAD

**Issue by tankwyn** [microsoft/vscode-cpptools#7316]
Issue Type: <b>Bug</b>

1) install the C/C++ extension
2) setup the i686-w64-mingw32 environment (8.1.0).
3) setup gdb as the debugger backend in 'launch.json':
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "cppdbg",
            "request": "launch",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "gdb.exe",
            "program": "${workspaceFolder}/output/main.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build"
        }
    ]
}
4) throw an exception & compile with g++. For example:
#include <iostream>
#include <exception>
using namespace std;

void foo() {
	throw exception();
}

void bar() {
	foo();
}

int main(int argc, char *argv[])
{
	std::cout << "Hello world!" << std::endl;
	bar();
}
5) press F5

Additional information:
1) Got no 'break on uncaught exception' or anything like this to be checked in the 'breakpoints' pane.
2) No problem with breaking on exceptions on GNU/Linux when debugging with gdb in vscode.
3) The `catch throw` command works fine in MinGW gdb.
4) With the above two points, it becomes obvious that this is a bug with the WindowsDebuggerLauncher.exe
5) Googled alot but nothing really helps.
6) One temporary solution is adding `catch throw` to the end of the `gdbinit` file.

Extension version: 1.2.2
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (1.14GB free)|
|Process Argv|--crash-reporter-id 068221c3-0972-4906-92d3-e3d4553f2de9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vsget980cf:30284046
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071

```

</details>

**Comment by WardenGnaw** [comment]
Duplicate: https://github.com/microsoft/vscode-cpptools/issues/1800

**Comment by JamesBremner** [comment]
I am running C++ extension v1.7.1.  This problem seems to be still present.  For details https://stackoverflow.com/q/70880806/16582
