### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode-cpptools#733]
Since the latest version of vscode 1.12.2, I can no longer start the debugger. I am attempting to attach to a running gdbserver. The problem occurs with or without the gdbserver running, so it seems local to vscode.

I now get the error:

```
Debug adapter process has terminated unexpectedly
```
and then
```
null
```

Here is my launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch Application",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/asl-pid-y10-display-d",
            "miDebuggerServerAddress": "172.17.0.2:2000",
            "args": [
                "--locationprefix=sta-1"
            ],
            "stopAtEntry": true,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
        },
    }
}
```

This is quite irritating as it was working fine before, but I can no longer debug my application. 8-(

I have tried the insiders build too and also a minimal installation (cpp only)...

**Comment by pieandcakes** [comment]
@Gruntfuggly Can you try specifying `"miDebuggerPath": "/path/to/gdb"` and see if that fixes it?

**Comment by Gruntfuggly** [comment]
Sorry, no difference. I've also tried reverting to previous versions of vscode, and also the previous version of the extension, as well as deleting cached data.

Is there any way to get a better log of what is happening? I've tried the logging parameters in the launch.json file, but that didn't seem to make any difference. The console log only seems to reveal that 'something' failed:

```
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Debug adapter process has terminated unexpectedly
e.doShow @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 null
e.doShow @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
```

**Comment by Gruntfuggly** [comment]
I created a new account on my machine and started the debugger through a clean installation of vscode. This worked, and now the debugger works in my original account, so I guess something somewhere must have been reset or cleared?
