### ISSUE TITLE
Unable to find #include <stdio.h> or any other header files

### ISSUE THREAD

**Issue by GaaneshT** [microsoft/vscode-cpptools#7336]
I am on my M1 Mac and am currently trying out the new insider release but I am experienceing erros trying to include header files.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/61627677/114300146-5c397f80-9af1-11eb-8495-d30f4ce86f64.png">

**Comment by michelleangela** [comment]
@GaaneshT 
Could you provide the following info that might give clues why the library header paths are not found?

- VS Code Version:

- C/C++ Extension Version:

- Other extensions you installed (and if the issue persists after disabling them):

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Comment by GaaneshT** [comment]
@michelleangela Thanks for your reply. Below is the information requested.


------VS CODE Version-------
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:00:52.911Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0

-----------------------------------

C/C++ Extention version : v1.3.0-insiders5

c_cpp_properties.json: 

{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/opt/homebrew/bin/gcc-10",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "macos-gcc-arm64"
        }
    ],
    "version": 4
}

------------------------------------------

Logs: 

-------- Diagnostics - 4/13/2021, 2:09:33 AM
Version: 1.3.0-insiders5
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [],
    "compilerPath": "/opt/homebrew/bin/gcc-10",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "macos-gcc-arm64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp ]:
    /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Translation Unit Configurations:
[ /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp ]:
    Process ID: 16780
    Memory Usage: 47 MB
    Compiler Path: /opt/homebrew/bin/gcc-10
    Includes:
        /opt/homebrew/Cellar/gcc/10.2.0_4/include/c++/10.2.1
        /opt/homebrew/Cellar/gcc/10.2.0_4/include/c++/10.2.1/aarch64-apple-darwin20
        /opt/homebrew/Cellar/gcc/10.2.0_4/include/c++/10.2.1/backward
        /opt/homebrew/Cellar/gcc/10.2.0_4/lib/gcc/10/gcc/aarch64-apple-darwin20/10.2.1/include
        /opt/homebrew/Cellar/gcc/10.2.0_4/lib/gcc/10/gcc/aarch64-apple-darwin20/10.2.1/include-fixed
    Standard Version: c++14
    IntelliSense Mode: macos-gcc-arm64
    Other Flags:
        --g++
        --gnu_version=100201
Total Memory Usage: 47 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 826

--------------------------------------------------
Logs from language Server: 

File exclude: **/.vscode
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
Populate include completion cache.
Discovering files...
  Processing folder (recursive): /opt/homebrew/Cellar/gcc/10.2.0_4/include/c++/10.2.1/
  Processing folder (recursive): /opt/homebrew/Cellar/gcc/10.2.0_4/lib/gcc/10/gcc/aarch64-apple-darwin20/10.2.1/include/
  Processing folder (recursive): /opt/homebrew/Cellar/gcc/10.2.0_4/lib/gcc/10/gcc/aarch64-apple-darwin20/10.2.1/include-fixed/
  Processing folder (recursive): /Users/gaanesh/Desktop/Sandbox/
  Discovering files: 826 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
1 include path suggestion(s) discovered.
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Error squiggle count: 24
Update IntelliSense time (sec): 0.263
sending 1 changes to server
sending 1 changes to server
Offering completion
sending 1 changes to server
Offering completion
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
  tag parsing file: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Error squiggle count: 25
Update IntelliSense time (sec): 3.153
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Error squiggle count: 25
Update IntelliSense time (sec): 0.411

---------------------------------------------------------

**Comment by GaaneshT** [comment]
I am also getting this error under the 'debug' tab
`Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (attach failed ((os/kern) invalid argument))`

**Comment by michelleangela** [comment]
@GaaneshT 
Thank you for the additional info and logs.

I installed gcc-10 using homebrew for Apple silicon and saw that the extension was not able to query the compiler to get the header include paths. Could you verify in your language server logging that this is also happening for you? In the language server logging look for keywords "Querying compiler". What are the returned results from querying the compiler? Also could you verify that the gcc-10 compiler can successfully compile?

As for the debugger issue, we have not completed the feature to support native debugging for Apple Silicon (see issue https://github.com/microsoft/vscode-cpptools/issues/7035). The current debugging binaries can run on Apple Silicon using the Rosetta emulator and it can only debug x86_64 programs.

**Comment by GaaneshT** [comment]
Hi @michelleangela 

**I updated my C/C++ to version 1.3.0

The new language server logs are :**

Finished installing dependencies

cpptools/didChangeCppProperties
$/setTraceNotification
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 205)
cpptools/activeDocumentChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 206)
cpptools/getDocumentSymbols
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 207)
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.258
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 208)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 209)
cpptools/activeDocumentChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.256
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 210)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 211)

------------------------------------------------------------------

**Comment by michelleangela** [comment]
Sorry, I forgot to mention to make sure to set the logging to level to "debug" for the logs to show extra logging. Could you set it the level to "debug" as instructed from https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server and re-send those logs?

Also could you verify that the gcc-10 compiler can successfully compile?

**Comment by GaaneshT** [comment]
These are the logs after setting the logging level to debug:

Finished installing dependencies

cpptools/didChangeCppProperties
$/setTraceNotification
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 205)
cpptools/activeDocumentChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 206)
cpptools/getDocumentSymbols
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 207)
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.258
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 208)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 209)
cpptools/activeDocumentChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.256
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 210)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 211)
cpptools/activeDocumentChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.264
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 212)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 213)
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 214)
cpptools/activeDocumentChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 215)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 216)
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.257
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 217)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 218)
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 219)
cpptools/activeDocumentChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 220)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 221)
cpptools/textEditorSelectionChange
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.263
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 222)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 223)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 224)
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 225)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 226)
textDocument/hover: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 227)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 228)
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 229)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 230)
auto_complete::handle_completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (6:6)
Offering completion
sending 1 changes to server
sending 1 changes to server
completionItem/resolve (id: 231)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 232)
auto_complete::handle_completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (6:7)
Offering completion
sending 1 changes to server
completionItem/resolve (id: 233)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 234)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
completionItem/resolve (id: 235)
sending 1 changes to server
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 236)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
completionItem/resolve (id: 237)
sending 1 changes to server
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 238)
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 239)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 240)
auto_complete::handle_completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (6:10)
textDocument/signatureHelp: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 241)
sending 1 changes to server
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 242)
auto_complete::handle_completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (6:11)
textDocument/signatureHelp: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 243)
sending 1 changes to server
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 244)
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 245)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 246)
auto_complete::handle_completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (6:12)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 247)
auto_complete::handle_completion: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (6:13)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 248)
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 249)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 250)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 251)
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 252)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 253)
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 254)
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 255)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 256)
textDocument/didSave: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
textDocument/didChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
  tag parsing file: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/fileChanged: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 258)
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 259)
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
cpptools/finishUpdateSquiggles
Error squiggle count: 0
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 260)
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 261)
textDocument/didSave: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
  tag parsing file: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/fileChanged: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/getDocumentSymbols: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 263)
cpptools/getDocumentSymbols
textDocument/documentHighlight: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 264)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 265)
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 7.303
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 266)
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 267)
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.256
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 268)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 269)
cpptools/fileCreated: file:///Users/gaanesh/Desktop/Sandbox
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop/Sandbox
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop/Sandbox
Database safe to open
cpptools/textEditorSelectionChange
cpptools/fileCreated: file:///Users/gaanesh/Desktop/Sandbox
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop/Sandbox
cpptools/fileCreated: file:///Users/gaanesh/Desktop
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.261
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 270)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 271)
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop/Sandbox
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop/Sandbox
cpptools/fileCreated: file:///Users/gaanesh/Desktop
cpptools/fileCreated: file:///Users/gaanesh/Desktop/Sandbox
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 272)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 273)
cpptools/getDocumentSymbols
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 274)
cpptools/activeDocumentChange: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 275)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 276)
idle loop: reparsing the active document
Checking for syntax errors: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Queueing IntelliSense update for files in translation unit of: /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.257
cpptools/getSemanticTokens: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 277)
cpptools/getFoldingRanges: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 278)
textDocument/hover: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 279)
cpptools/fileCreated: file:///Users/gaanesh/Desktop/Sandbox
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp (id: 280)
--------------------------------------------------------------
<img width="600" alt="Screenshot 2021-04-15 at 1 10 59 AM" src="https://user-images.githubusercontent.com/61627677/114751668-029eb280-9d88-11eb-89c7-f2769f63b901.png">

I'm currently using clang to compile and it compiles successfully

**Comment by GaaneshT** [comment]
To add on, I am not getting the include header errors anymore. 
I only did 2 things, I updated C/C++ to 1.3.0 from the previous insiders5 version and I moved VS code to the applications folder from the downloads folder because I wanted to fix the path.

**Comment by michelleangela** [comment]
The compiler used for actual compiling and the compiler used for the IntelliSense configuration (c_cpp_properties.json) are usually the same compilers. From your initial provided IntelliSense configuration (c_cpp_properties.json), gcc-10 compiler was used (see property `compilerPath` that was set to path of gcc-10). And from my testing of trying to use gcc-10, the extension could not query the compiler gcc-10. Also, I could not also compile with gcc-10 (haven't figured out the issue of gcc-10 on Apple Silicon yet). So it looks like the initial issue was with the gcc-10 compiler.

Based on your changes to update the C++ extension and change its installation location, the extension maybe querying the Clang compiler instead of the gcc-10 compiler? You can verify which compiler the IntelliSense configuration is using by running the command `C/C++: Log Diagnostics` from the VS Code command palette.

**Comment by GaaneshT** [comment]
Hi @michelleangela ,

The output for C/C++: Log Diagnostics is :

-------- Diagnostics - 4/15/2021, 4:05:17 PM
Version: 1.3.0
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++98",
    "intelliSenseMode": "macos-clang-arm64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp ]:
    /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp
Translation Unit Configurations:
[ /Users/gaanesh/Desktop/Sandbox/sandboxcpp.cpp ]:
    Process ID: 2496
    Memory Usage: 25 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++03
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=100000
Total Memory Usage: 25 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 8156

----------------------------------------------------------------------------

It appears the default compiler changed to clang compiler instead of gcc-10 compiler

**Comment by michelleangela** [comment]
@GaaneshT 
Thanks for confirming which compiler is used in the IntelliSense configuration. If you ever need to change the compiler for the IntelliSense configuration, you can set the `compilerPath` property by opening the IntelliSense configuration via the `C/C++: Edit Configurations (UI)` or  `C/C++: Edit Configurations (JSON)` commands.

![image](https://user-images.githubusercontent.com/38734287/114905922-5b913980-9dce-11eb-9ba3-af2377049fd6.png)

I'll create a separate issue to investigate the gcc-10 compiler on Apple Silicon.

**Comment by michelleangela** [comment]
Created issue #7375 to investigate usage and querying of gcc-10 compiler on Apple Silicon.

Closing this issue as resolved.
