### ISSUE TITLE
[Linux] About the gdb mi args

### ISSUE THREAD

**Issue by freshxxxx** [microsoft/vscode-cpptools#7337]
**Type: Feature Request**

**Situation:**
As the extension call "$GDB_PATH --interpreter=mi...", there is always gdb information like
> [1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-6v1pmf4t.baj" 1>"/tmp/Microsoft-MIEngine-Out-9eprptvz.l63".

The information disturbs stdout.

**Problem:**
To solve that, I set the "miDebuggerArgs" as "-q", but it doesn't work as the default gdb command format is 
> $gdbpath --interpreter=mi miargs

So '-q' behind won't make gdb silent.
I found a rough solution on the Internet
> "miDebuggerArgs": "-q -ex quit; wait() { fg >/dev/null; }; /bin/gdb -q --interpreter=mi"

**Request:**
Is there any elegant solution or can you add a new feature to insert miargs before "--interpreter"?
Save germophobes' lives, plz.

**Comment by WardenGnaw** [comment]
You can use `miDebuggerPath` to point to a custom script that runs 
```
/path/to/gdb -q $@
```
Then it will put the `-q` before the miDebuggerArgs.

**Comment by gantianciyu** [comment]
Thank you for your help!
