### ISSUE TITLE
Extension "C/C++" cannot format <file> (when C_Cpp.intelliSenseEngine is set to "Disabled")

### ISSUE THREAD

**Issue by smaassen** [microsoft/vscode-cpptools#7339]
The cpp extension shows me an error on the status bar when saving that it can not format the file, however, no further information is displayed. I tried putting the logging level of the extension to debug but it the file stays empty. 

It was working fine untill i changed something totally unrelated in the settings file (python setting)

![image](https://user-images.githubusercontent.com/17762954/114427087-05987800-9bbb-11eb-9d75-5065859a3383.png)

OS: Ubuntu 16.04
VS Code Version:1.55.1
C/C++ Extension Version: 1.2.2
Other extensions (Problem persists as in no formatting is done but the error messages does not appear when all other are disabled):

- Activtius  Bar
- Auto Comment Blocks
- clangd
- CMake
- Code Spell Checker
- Edit csv
- Git Blame
- Jupyter
- Markdown Preview Enhanced
- Module Templates
- Proto Lint
- Protobuf support
- Pylance
- Python 
- Python for VSCode
- vscode-proto3

settings.json:
```
{
    // General Settings
    "editor.rulers": [
        100
    ],
    "breadcrumbs.enabled": true,
    "editor.minimap.enabled": false,
    "editor.cursorBlinking": "smooth",
    "[cpp]": {
        "editor.defaultFormatter": "ms-vscode.cpptools",
        "editor.formatOnSave": true
    },
    "workbench.editor.enablePreview": false,
    // Clandg settings
    "clangd.path": "/home/smaassen/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/bin/clangd",
    "clangd.semanticHighlighting": false,
    "clangd.arguments": [
        "-header-insertion=never",
        "-log=verbose",
    ],
    "clangd.onConfigChanged": "restart",
    // C_cpp
    // "C_Cpp.clang_format_path": "/usr/bin/clang-format",
    "C_Cpp.clang_format_path": "/home/smaassen/.vscode-insiders/extensions/ms-vscode.cpptools-0.21.0/LLVM/bin/clang-format",
    "C_Cpp.clang_format_fallbackStyle": "LLVM",
    "editor.formatOnSave": true,
    "C_Cpp.intelliSenseCacheSize": 0,
    "C_Cpp.loggingLevel": "Debug",
    "C_Cpp.intelliSenseEngine": "Disabled",
    // python 
    "python.venvPath": "/opt/",
    "python.linting.enabled": true,
    "python.linting.flake8Enabled": true,
    "python.pythonPath": "/opt/verity-python-environment/bin/python",
    "python.formatting.provider": "yapf",
    "python.formatting.yapfArgs": [],
    "python.defaultInterpreterPath": "python3",
    // other extensions
    "cSpell.userWords": [
        "discretization",
        "ulid"
    ],
    "explorer.confirmDelete": false,
    "jupyter.sendSelectionToInteractiveWindow": false,
    "workbench.startupEditor": "newUntitledFile",
    "json.maxItemsComputed": 20000,
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "window.zoomLevel": -1,
    "editor.largeFileOptimizations": false,
    "python.languageServer": "Pylance",
    "python.analysis.diagnosticSeverityOverrides": {
        "reportGeneralTypeIssues": "error"
    },
}
```

Output from Log Diagnostics (Had to enabled intellisense):
```
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/lib/ccache/gcc",
    "cStandard": "gnu11",
    "cppStandard": "gnu++98",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.
```

After enabling intellisense i get an output and when setting the clang format path to the right executable it seems to work. 

I am using clangd as a language server and want to use C_cpp for formatting. Is this not possible without enabling intellisense?

**Comment by michelleangela** [comment]
@smaassen 

Could you provide the following info to help us investigate the issue further?

- OS and Version:

- VS Code Version:

- C/C++ Extension Version:

- Other extensions you installed (and if the issue persists after disabling them):

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Comment by smaassen** [comment]
updated initial ticket message with requested information

**Comment by michelleangela** [comment]
>I am using clangd as a language server and want to use C_cpp for formatting. Is this not possible without enabling intellisense?

In order to use the formatting feature of C++ extension, `C_Cpp.intelliSenseEngine` needs to be enabled. Currently there's no way to disable the language server of C++ extension without also disabling formatting (see https://github.com/microsoft/vscode-cpptools/issues/7083#issuecomment-789940496a).

There is a [clang-format extension](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) that you could use if you haven't tried it yet.
