### ISSUE TITLE
Can't see variables in call stack

### ISSUE THREAD

**Issue by nilanjan** [microsoft/vscode-cpptools#734]
When it hits a breakpoint we can see or dump variables anywhere in the call stack. For some reason the tool not allowing me to print the variables somewhere down (not the top) in the call stack. 

OS X Sierra
lldb

**Comment by pieandcakes** [comment]
@nilanjan can you post your `launch.json` ? Variables should show up in the debug window. can you provide more of an example of the problem you are having?

**Comment by nilanjan** [comment]
{
            "name": "C++ Launch Test",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/../../bin/exe”,
            "args": [ "-a", “arg1”],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}/test",
            "externalConsole": false,
            "filterStdout": true,
            // "filterStderr": true,
            "environment": [
            ],
            
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },

**Comment by nilanjan** [comment]
If I move to any position (excluding top) in the call stack and type "-exec p/x var" It's not showing the var. It can only see the top of the call stack vars. I have to do this because vscode does not show variables in HEX. So I always have to use p/x to see the var.

**Comment by WardenGnaw** [comment]
Closing older issues.

If you are still encountering issues, please create a new issue.
