### ISSUE TITLE
C/C++(1696)

### ISSUE THREAD

**Issue by CarloEO** [microsoft/vscode-cpptools#7341]
Bug type: General

**Describe the bug**
- OS and Version: Mac 11.1
- VS Code Version: 1.55
- C/C++ Extension Version: v1.3.0-insiders5
- Other extensions you installed (and if the issue persists after disabling them):
- Code Runner Extension Version: v0.11.3

Hello
For no reason, the next error started to show up

![](https://user-images.githubusercontent.com/59629936/114465246-18ec1900-9ba4-11eb-9eec-2b3433a39ed9.png)
This is my .json configuration

{
"configurations": [
{
"name": "Mac",
"includePath": [
"${workspaceFolder}/**"
],
"defines": [],
"macFrameworkPath": [
"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
],
"compilerPath": "/usr/bin/clang",
"intelliSenseMode": "macos-clang-x64"
}
],
"version": 4
}

**Comment by sean-mcmanus** [comment]
Can you check your C/C++: Log Diagnostics logging? That will show what configuration details are actually getting used.

**Comment by sean-mcmanus** [comment]
Also, are you on Mac M1/arm64? If so, do you know if you're using the arm64 or x64 vsix? The arm64 version is available at https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.0-insiders5 .

**Comment by sean-mcmanus** [comment]
Also, where is your iostream header installed at (does Go to Definition open the file)? I'm getting it from /Library/Developer/CommandLineTools/usr/include/c++/v1/iostream.
