### ISSUE TITLE
Extension doesn't activate when opening a folder with /.vscode/c_cpp_properties.json

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7344]
The workaround is to open a C/C++ file.

**Comment by sopka13** [comment]
![image](https://user-images.githubusercontent.com/69894970/115352455-0edba300-a1c0-11eb-8976-e01b34edba28.png)
This started after the last changes took effect. What does he want from me?

**Comment by sean-mcmanus** [comment]
What do those squiggle errors say in the Problems window?

**Comment by sopka13** [comment]
> Что говорят эти волнистые ошибки в окне "Проблемы"?

This is my mistake. I'm sorry. I didn't see the error in parentheses. Thank you for your time. The tired look and coincidence with the version update dulled my guard.
