### ISSUE TITLE
modify the warning message when "compileCommands" is not a valid file

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cpptools#7346]
in this setting, the "compileCommands" is set to a file that exists, but is not valid:
![image](https://user-images.githubusercontent.com/16143955/114481662-de8d7680-9bb9-11eb-89a3-e823b365256e.png)

the warning message is as below:
`"abc.h" could not be found. 'includePath' from c_cpp_properties.json in folder 'testMultiRoot2' will be used instead.`

**Comment by michelleangela** [comment]
Accidentally closed the wrong issue.

**Comment by Colengms** [comment]
@elahehrashedi I'm not easily able to repro this issue.  I tried creating an empty json file, or one containing non-json content, and got an appropriate warning: `"bad_compile_commands.json" could not be parsed. 'includePath' from c_cpp_properties.json in folder 'test2' will be used instead.`

Was there something additional with your repro that caused the "could not be found" error to occur despite the file existing?
