### ISSUE TITLE
IntelliSense crash in conv_line_loc_to_source_pos

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7354]
你好，今天我又尝试用gdb查看了core文件的堆栈信息，希望这些内容能够对你们起到帮助。
![image](https://user-images.githubusercontent.com/22772190/114529520-9b480c00-9c7c-11eb-8284-1d9e86b71b59.png)

_Originally posted by @Modnars in https://github.com/microsoft/vscode-cpptools/issues/7161#issuecomment-818588177_

**Comment by sean-mcmanus** [comment]
@Modnars Are you able to provide any sample code to repro the issue? This bug repros with 1.2.2 and is not a recent regression. It's between our top 10-20 IntelliSense processes crashes.

**Comment by Modnars** [comment]
抱歉，coredump文件的产生一直是偶现的，目前还没有找到一种稳定可行的方式来复现这个问题。如果找到了一种途径来复现它，我会及时反馈的。
