### ISSUE TITLE
Add descriptions for enums to package.json

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#7358]
A lot of enum settings in `package.json` lack `enumDescriptions`.  Opening this issue to track adding a description for each enum value.

**Comment by sean-mcmanus** [comment]
Some cases of this are fixed in my clang-tidy branch (along with other description fixes). The other cases didn't seem like an enum description would be much help. Were there particular cases you thought should have an enum description?

**Comment by sean-mcmanus** [comment]
I'm considering this fixed...let me know if you think other enums should have descriptions. One thing to be aware of is that the enumDescriptions aren't currently copyable via the settings UI, which can make some descriptions that contain "sample text" better placed in the "description" instead.
