### ISSUE TITLE
CUDA support could use setTextDocumentLanguage instead of files.associations

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#7359]
Currently, when a `cpp` file is determined to be a CUDA file (due to nvcc compiler path), a `files.associations` entry is added to map the file to the `cuda-cpp` language ID, to ensure it gets the proper TextMate grammar.

It looks like it would be possible to use `setTextDocumentLanguage` instead to switch the file from `cpp` to `cuda-cpp` on the fly.  It's OK that the association is not persisted, as we should continue to handle `cpp` files and continue to remap them.  This solution seems preferable, as it doesn't incur a bunch of entries in `settings.json`.

**Comment by Colengms** [comment]
As part of this fix, headers should get updated to be associated with CUDA C++ when associated with a CUDA source file.  Otherwise, the header may not have the proper CUDA syntax highlighting.

**Comment by soulman710** [comment]
This is awesome
