### ISSUE TITLE
Adding libc++ 4.0.0's headers to the includePath of a configuration crashes IntelliSense (cpptools 0.11.0, vscode 1.12.2, Ubuntu 14.04)

### ISSUE THREAD

**Issue by jfroy** [microsoft/vscode-cpptools#736]
One of my project uses libc++ (from a custom sysroot and clang toolchain), so I added libc++'s headers directory to includePath to my cpp configuration. That causes the cpp helper process to crash, with an error banner in the editor containing: "The intellisense engine has stopped responding".

I'm not sure how to provide more information.

**Comment by sean-mcmanus** [comment]
Yeah, I'm able to repro this. Looks like IntelliSense (and the tag parser) don't work with libc++ 4.0 (3.8 works). The headers changed and our code is erroring out. We should have a fix in a future update...

**Comment by sean-mcmanus** [comment]
Actually, I don't repro the crash with our pending 0.11.1, but it just isn't parsing the headers correctly. For me to repro the crash, I need to know the details of the translation unit (i.e. what C++ library headers/classes are you using?).

**Comment by jfroy** [comment]
I'll try to reduce to a TU I can share, but glancing at the source, we import a lot of the STL in most of our TUs. algorithm, atomic, bitset, chrono, memory, string, thread, utility, vector.

**Comment by sean-mcmanus** [comment]
I'm assuming this has been fixed by now? We haven't gotten similar complaints from other users. Let us know if it's still an issue. We've fixed lots of crashing and parsing issues. 0.17.8-insiders has more fixes https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.17.8-insiders .
