### ISSUE TITLE
Different result for manual clang-format invocation vs 'Format Document'

### ISSUE THREAD

**Issue by sschleemilch** [microsoft/vscode-cpptools#7360]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.55.1
- C/C++ Extension Version: 1.3.0

Problem is an inconsistent formatting when using a manual `clang-format -i <file>` vs the VSCode's `Format Document` as far as I can reproduce for blank lines.
- `settings.json` has the path to the `clang-format` that is also invoked through the command line:
```
  "C_Cpp.clang_format_fallbackStyle": "none",
  "C_Cpp.clang_format_path": "/usr/bin/clang-format",
```
- Using the [clang-format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) plugin does not show this kind of problem.

Example input file:
```cpp
#include <iostream>







int main()
{
    std::cout << "Hello World!";
    return 0;
}
```
Using `clang-format -i hello.cpp` results in:

```cpp
#include <iostream>


int main()
{
    std::cout << "Hello World!";
    return 0;
}

```

Using VSCode's format mechanism:
```cpp
#include <iostream>





int main()
{
    std::cout << "Hello World!";
    return 0;
}
```
Invoking the VSCode's format mechanism again produces the correct result.

**Steps to reproduce**

1. Create a `hello.cpp` with the example code and add >= 6 blank lines
2. Run `Format Document`
3. Run `Format Document`

**Expected behavior**

One format run should produce the same result as invoking `clang-format -i` manually.

**Code sample and logs**

- Configurations in `c_cpp_properties.json` not relevant

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
[ /workspace/hello.cpp ]:
    Process ID: 6332
    Memory Usage: 42 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++11
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
Total Memory Usage: 197 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 24513
```

**Comment by sean-mcmanus** [comment]
What is your C_Cpp.formatting setting? It seems like it's set to "vcFormat" instead of "clangFormat".

**Comment by sschleemilch** [comment]
Hi @sean-mcmanus,
Thanks for getting back so quickly.

> What is your C_Cpp.formatting setting? It seems like it's set to "vcFormat" instead of "clangFormat".

Was **unset** before. Setting it explicitly does not change the behavior. After rebuilding the container one still has to save the example `hello.cpp` twice to get the same result as `clang-format`.

**Comment by sean-mcmanus** [comment]
Ah, sorry for the misunderstanding -- I repro the issue now.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders
