### ISSUE TITLE
Windows x86 is incompatible with your OS

### ISSUE THREAD

**Issue by jeremyd2019** [microsoft/vscode-cpptools#7368]
Bug type: General

**Describe the bug**
- OS and Version: Windows 10 20H2 (32-bit)
- VS Code Version: 
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:00.942Z (2 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT ia32 10.0.19042
- C/C++ Extension Version: 1.3.0
- Other extensions you installed (and if the issue persists after disabling them): Arduino, Fenix, Hex Editor, Jupyter, Pylance, Python
- A clear and concise description of what the bug is.
After updating to 1.3.0 and reloading, get a message:
> This Windows x86 version of the extension is incompatible with your OS. Please download and install the "cpptools-win32.vsix" version of the extension.

I tried that, but got the same message

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. A fix should be in our next release. Downgrading to https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2 is recommended for now.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.3.1
