### ISSUE TITLE
C++ IntelliSense isense_driver crashes with this code (in attach_attributes_to_routine_instance)

### ISSUE THREAD

**Issue by sandeepshiven** [microsoft/vscode-cpptools#7377]
I am a newbie so I don't know all the technicalities please bear with me. 
Intellisense is working on all the files expect for a single one.
For example when I type something in other files let say gfg_test.cpp it is working fine
![Screenshot from 2021-04-16 13-33-45](https://user-images.githubusercontent.com/39735595/114992441-63c5a380-9eb8-11eb-9106-f1513896dedc.png)

But when I do something on this specific test.cpp file Intellisense is not working.
![Screenshot from 2021-04-16 13-35-17](https://user-images.githubusercontent.com/39735595/114992632-996a8c80-9eb8-11eb-93df-fa346a1a5e25.png)

If you want code of this file then.

[Untitled Document 1.txt](https://github.com/microsoft/vscode-cpptools/files/6323482/Untitled.Document.1.txt)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. Our parser shared with VS is crashing.

**Comment by sandeepshiven** [comment]
@sean-mcmanus  glad to help. By the way I realised its not the problem with the file its the problem with this code. Somehow Intellisense is not working for this code, I copied the code to other files and this problem still remains.

**Comment by sean-mcmanus** [comment]
I've filed an internal bug against our shared VS parser.

**Comment by sandeepshiven** [comment]
Debugger is also not working properly with this code.

**Comment by sean-mcmanus** [comment]
@sandeepshiven Can you file a different issue on that using the debugger bug template https://github.com/microsoft/vscode-cpptools/issues/new?assignees=&labels=&template=debugger.md&title=? They'll probably need more info on what "not working" means and the debugger logging.

**Comment by sean-mcmanus** [comment]
@sandeepshiven In particular, debugging is working for me via using F5 with g++ and clang with gdb.

**Comment by sandeepshiven** [comment]
@sean-mcmanus  I was checking why parser was not working I found out that the line number 2 and 3 in the code were causing the problem so I commented these lines
`#pragma GCC optimize("Ofast") 
#pragma GCC target("avx,avx2,fma")`
and reloaded the window and intellisense and debugger worked fine. Please look into it why these two lines were causing problem because I do competitive programming and those two lines are almost present all times in my code.

**Comment by sean-mcmanus** [comment]
You can use
```
#ifndef __INTELLISENSE__
#pragma GCC target("avx,avx2,fma")
#endif
```
as a workaround until our parser gets the fix. I don't know if that fixes the debugger issue, since I couldn't repro that.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders2

**Comment by sandeepshiven** [comment]
@sean-mcmanus  Yeah!! now its working fine.
