### ISSUE TITLE
VSCode Intellisense does not find headers of packages installed with vcpkg (WSL2)

### ISSUE THREAD

**Issue by pfuerste** [microsoft/vscode-cpptools#7379]
I am pretty new to CMake and just installed some packages via vcpkg. Am I missing something?
I used vcpkg to install some package for my project, but intellisense tells me it cant open the source file:

![grafik](https://user-images.githubusercontent.com/26963125/115040621-edce3600-9ed1-11eb-905a-8b5adab8e1ee.png)

This are the 3 items in my includepath:

`${workspaceFolder}/**
~/vcpkg/installed/x64-linux/
~/vcpkg/installed/x64-linux/**`

CMake does find the files of the installed packages after 
`set(CMAKE_PREFIX_PATH "~/vcpkg/installed/x64-linux/")`
 and is able to compile.

**Comment by sean-mcmanus** [comment]
You're using the CMake Tools configuration provider? Did you run CMake: Configure? Can you look at the out of running C/C++: Lo g Diagnostics and look for what includes paths are being sent by the configuration provider? This may be a CMake Tools bug.

**Comment by pfuerste** [comment]
Thanks for your answer.
I did not configure at first, but did now, the error remains the same. 
I had the CMake and CMake Tools extensions installed, but did not actually use them yet (my project structure is rather simple and I wanted to get into the extensions soon). Uninstalling them fixed the problem.

I hope this is the right output for the Log diagnostics you asked for:
![grafik](https://user-images.githubusercontent.com/26963125/115142991-ea0ef080-a044-11eb-8ba2-81d484cd7559.png)

**Comment by sean-mcmanus** [comment]
Can you run C/C++: Log Diagnostics from the View->Command Palette?

The logging you provided suggests that /vcpkg/installed/x64-linux/include is in your include path. Where is the catch2 folder located? You'll want to make sure that folder is in your include path. If you think that the "**" recursive includes is not finding the path when it should be, you can try running the C/C++: Reset IntelliSense Database command.

**Comment by sean-mcmanus** [comment]
You have configurationProvider set, which will cause includePath to not be used. Can you remove that?

**Comment by pfuerste** [comment]
Yeah, that fixed it. I don't know why it was set though (or what it is), will this impact other functionality?

**Comment by sean-mcmanus** [comment]
There are some code paths that may auto-set that or in response to a prompt button if we detect that you have CMake Tools installed and have a CMakeLists.txt. If you're using a CMake project, it usually recommended to be configured via the CMake Tools configuration provider, but if your project is simple enough you can configure it via c_cpp_properties.json as well. It shouldn't affect anything except how IntelliSense is getting its configuration information.
