### ISSUE TITLE
After upgrade to 0.11.1, opening one of my projects shows "The intellisense engine has stopped responding"

### ISSUE THREAD

**Issue by rossnichols** [microsoft/vscode-cpptools#738]
No other output is produced. This error is in the banner at the top.

**Comment by sean-mcmanus** [comment]
That means the IntelliSense engine process crashed. You can change the IntelliSenseEngine to "Tag Parser" to stop using the IntelliSense engine. We're in the process of changing how we deal with crashes.

**Comment by bobbrow** [comment]
If you see this banner, the extension will automatically revert back to using the tag parser for the active translation unit (e.g. c++ source file) where the crash occurred.  I would only recommend setting the `intelliSenseEngine` back to tag parser if the messages are so frequent that they disrupt your work.

We are looking at the callstacks of the crashes as they are reported and working to improve the experience for everyone.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
