### ISSUE TITLE
C_Cpp.files.exclude should be removed from telemetry

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#7380]
Bug type: Language Service

We can see who sets it, but we shouldn't log any of the values.  Because I blocked this property, we'll need to create a new key name like we did for clang_format_style in settingsTracker.ts.

**Comment by sean-mcmanus** [comment]
I'm not able to detect a problem, i.e. I can't get it to send any telemetry with files.exclude.

**Comment by Colengms** [comment]
For telemetry, it looks like we're not handling settings which are objects (unless we add explicit handling per object setting).  The default route through the code will fail to find `C_Cpp.files.exclude.**/.vscode` (the first/default property in the `C_Cpp.files.exclude` object) and skip it.  It doesn't looks like `C_Cpp.files.exclude` should be showing up in the telemetry.
