### ISSUE TITLE
Feature Request: Add template instantiation based intellisense

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/vscode-cpptools#7382]
Type: Feature Request

Visual Studio has this wonderful feature that allow you to automatically or manually add existing template instantiation and provide better intellisense like this:
![image](https://user-images.githubusercontent.com/42881734/115100836-086dd280-9f05-11eb-801e-ed666240d6a7.png)

Would be nice to have that in VSCode too, like having a codelen on top of a template.

**Comment by HO-COOH** [comment]
Found duplicate of #1946 and #3535

**Comment by SMJSGaming** [comment]
I would also love to see this feature being added, I've been working with a low level system  for an arduino which has to use a lot of templates and the fact that this feature doesn't exist practically forces me to have the arduino with me at all times.

**Comment by bobbrow** [comment]
@SMJSGaming it's on the list for 1.7 which is a couple of months out, but it is on the roadmap.
