### ISSUE TITLE
compilerPath not taken from compile_commands.json

### ISSUE THREAD

**Issue by ykoehler** [microsoft/vscode-cpptools#7388]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.55.2
- C/C++ Extension Version: 1.3.0
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: Linux
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

compilerPath is unset in .c_cpp_properties.json I configured a compileCommands, within the compileCommand the compiler is arm-linux-gcc but once I load a C file and run C/C++ Log diagnostic, I see /usr/bin/ccache/gcc

If I set the compilerPath to the arm-linux-gcc manually in c_cpp_properties.json then it works.

**Steps to reproduce**

Create a compilerCommands.json with a non-standard compiler
remove the compilerPath from c_cpp_properties.json file
run C/C++ Log diagnostic 

**Expected behavior**

I would expect to see arm-linux-gcc as the compiler.

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Linux",
            "cStandard": "c89",
            "cppStandard": "gnu++98",
            "intelliSenseMode": "linux-gcc-arm",
            "compileCommands": "${workspaceFolder}/compile_commands.json",
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 4
}
```
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

```
[ /mypath/myfile.c ]:
    Process ID: 3541
    Memory Usage: 7 MB
    Compiler Path: /usr/lib64/ccache/gcc
    Includes:
        /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
        /usr/local/include
        /usr/include
    Standard Version: c89
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=40805
Total Memory Usage: 18 MB
```
- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

Here is my compile_commands.json

```
[
 {
  "directory": "/myoath", 
  "arguments": [
   "arm-linux-gcc", 
   "-pipe", 
   "-Wall", 
   "-Werror", 
   "-Wno-unused", 
   "-fno-unit-at-a-time", 
   "-Wno-pointer-sign", 
   "-Wno-strict-aliasing", 
   "-Wno-unused-but-set-variable", 
   "-fgnu89-inline", 
   "-ggdb", 
   "-O2", 
   "-Werror-implicit-function-declaration", 
   "-O2", 
   "-g", 
   "-I.", 
   "-c", 
   "cfg.c", 
   "-o", 
   "myfile.o"
  ], 
  "file": "myfile.c"
 }
]
```

**Comment by sean-mcmanus** [comment]
In the C/C++ logging, I'm seeing 
cc1plus.exe: error: command-line option '-Wno-pointer-sign' is valid for C/ObjC but not for C++ [-Werror]
cc1plus.exe: error: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++ [-Werror]
cc1plus.exe: error: command-line option '-fgnu89-inline' is valid for C/ObjC but not for C++ [-Werror]

So, removing those 3 arguments should fix it...if that's possible.

We should also fix it on our end to not send those flags when querying for C++.

**Comment by ykoehler** [comment]
this is a C project, and while I can temporarily remove those, unlikely I can request that they be removed permanently.

**Comment by sean-mcmanus** [comment]
Yeah, we'd have to fix the bug and/or do other changes. Removing "-Werror" would be a simpler potential workaround (our fix might be to just filter out that). I also see a bug when intelliSenseMode is set so you may want to remove that from c_cpp_properties.json (https://github.com/microsoft/vscode-cpptools/issues/7390).

**Comment by ykoehler** [comment]
If you could point the area of the code, I could actually put some time and work on this, I also saw some other issues with the compile_commands.json parsing related to gcc arguments, such as if all the -D options and -I are not grouped together it seems the vscode only take the first bunch and stop parsing.  Knowing which area to look code wise, I can give some of my time to contribute.

**Comment by sean-mcmanus** [comment]
Unfortunately, it's handled in our closed source cpptools process and not our open source TypeScript side. We could probably fix it ourselves for 1.4.0-insiders.

**Comment by sean-mcmanus** [comment]
If you can provide a repro and/or report a new bug on the -D/-I issue we could look into that as well.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders
