### ISSUE TITLE
Unable to debug using LLDB on Windows via launch.json

### ISSUE THREAD

**Issue by LouChiSoft** [microsoft/vscode-cpptools#7395]
**[Description]**
- OS and Version: Windows 10 (21H1)
- VS Code Version: 1.56.0 Insiders
- C/C++ Extension Version: 1.31.1
- When setting up a tasks.json and launch.json to build and debug using clang++ and LLDB respectively on Windows it is possible to build using clang, but using LLDB will leave VS Code in an infinite loading state never entering the main function.

**[To Reproduce]**
1: Download the extension (no other extensions installed)
2: Create a folder containing a main.cpp file containing a simple Hello, World example, and a .vscode folder containing tasks.json and launch.json

tasks.json
```
{
    "version": "2.0.0",
    "tasks": [
      {
        "type": "shell",
        "label": "clang++ build",
        "command": "clang++",
        "args": [
          "-std=c++17",
          "-g",
          "${workspaceFolder}/*.cpp",
          "-o",
          "${workspaceFolder}/out.exe"
        ],
        "options": {
          "cwd": "${workspaceFolder}"
        },
        "problemMatcher": ["$gcc"],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]
  }
```
launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Program",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/out.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "miDebuggerPath": "C:/Program Files/LLVM/bin/lldb.exe",
            "preLaunchTask": "clang++ build",
            "logging": { "engineLogging": true, "trace": true, "traceResponse": true }
        }
    ]
}
```
3. Begin debugging (F5)

This results in VS Code beginning the debugging process but never actually starting and never reaching the entry point or any breakpoint placed in the code. If the process is launched with `"externalConsole":"true"` it will instead create an "error: unknown option: --interpreter=mi" dialog box and stop trying to debug

**Comment by longnguyen2004** [comment]
`"miDebuggerPath": "C:/Program Files/LLVM/bin/lldb.exe",`

You need to set this to the path of `lldb-mi`, not `lldb`.

**Comment by WardenGnaw** [comment]
@longnguyen2004 Is correct, the debug adapter expects the debugger to understand Machine Interface in order for the information between the debug adapter and the debugger (`lldb-mi`) to be well formatted.

**Comment by LouChiShu** [comment]
Yeah, I did some research after @longnguyen2004 answered and it appears that lldb-mi was included in the llvm installer for Windows for a previous version but at somepoint was removed with no way to download a release of it on it's own. There was also something mentioned about the VS Code team looking to work around this limitation but in the meantime to use CodeLLDB for debugging on Windows with LLDB.
