### ISSUE TITLE
only find the symbols in the first directly headers

### ISSUE THREAD

**Issue by OptSolution** [microsoft/vscode-cpptools#740]
I update it to 0.11.1 , and I set the includePath and browse 

my os is ubuntu 14.04

**Comment by bobbrow** [comment]
I'm sorry, I don't really understand what your issue is.  Can you describe it in a little more detail?  Where do your include files live relative to your `${workspaceRoot}`?  Did you add your include paths to the `"includePath"` array?

**Comment by cenomla** [comment]
What I think this is referring to is that the new intellisense engine only recognizes symbols that are defined in the first include statement for each source file, even if the includePath is set correctly.

eg.

include "vector"
include "bitmap"

intellisense would know about std::vector but report std::bitmap as not being defined. Sounds like the same issue I was having #739.

**Comment by bobbrow** [comment]
Thanks for chiming in @cenomla .  @OptSolution, can you let us know if you are using GCC 6.3 as well?

**Comment by OptSolution** [comment]
I am using GCC 4.8

**Comment by cenomla** [comment]
I am using GCC 6.3.1

**Comment by sean-mcmanus** [comment]
@OptSolution I'm not seeing this issue with gcc Ubuntu 4.8.5. Can you give the exact includePath? Are you using /usr/include/c++/4.8? Unlike browse.path, the includePath setting is not recursive.

**Comment by sean-mcmanus** [comment]
I reproed the issue with 6.3.1, and adding these to my includePath fixed it:  "/usr/include/x86_x64-linux-gnu" and "/usr/include/x86_64-linux-gnu/c++/6.3.0". One way to manually figure out these issues is to search the #include tree until you find the 1st file with an error (i.e. usually a header that can't be found due to a missing includePath)...we want to do this automatically for users later.

**Comment by cenomla** [comment]
Adding "/usr/include/c++/6.3.1/x86_64-pc-linux-gnu" and "/usr/include/c++/6.3.1/x86_64-pc-linux-gnu/bits" fixed most of the errors except it still says size_t is undefined. Am I correct to assume that the intellisense engine stops parsing after it encounters a missing include file and that is why the intellisense engine doesn't recognize symbols from files included after the one with the errors?

**Comment by sean-mcmanus** [comment]
size_t should be defined somewhere. Can you try to find the location via Peek Definition or searching for `typedef __SIZE_TYPE__ size_t`? I'm seeing it at /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h. The IntelliSenseEngine doesn't stop parsing, but if an earlier includePath was not found, then it could cause a cascade of additional failures later on. I was seeing vector failing when it was after iostream, which had a missing includePath in a child header, but after moving vector above iostream, vector started to work.

**Comment by cenomla** [comment]
The location shown in the Peek Definition is "/usr/include/c++/6.3.1/x86_64-pc-linux-gnu/bits/c++config.h", which is in my include path. There are no errors inside that file. Another odd thing is that "max_align_t" as referenced in cstddef is also showing up as undefined and the peek definition shows no location for it.

**Comment by cenomla** [comment]
It appears that size_t is a typedef of a builtin type in GCC `__SIZE_TYPE__` same with ptrdiff_t `__PTRDIFF_TYPE__`. Both of those symbols are defined right next to each other in c++config.h. Could this be why the intellisense engine does not recognize them?

**Comment by sean-mcmanus** [comment]
I see the same thing, but it's working for me. I'm not sure what the difference is (I think I have 6.3.0, but they seem similar). One thing to try is to delete the .browse.vc.db -- setting the databaseFilename to "${workspaceRoot}/.vscode/.browse.vc.db" is the easiest way.

**Comment by cenomla** [comment]
Deleting/setting the databaseFilename does nothing.

**Comment by cenomla** [comment]
I fixed it. For some reason the include path for clang needs to be present even though I am using GCC. If I add "/usr/include/clang/4.0.0/include" to the path it works.

**Comment by sean-mcmanus** [comment]
We're supposed to auto-generate the clang include path if it exists. Did that not happen for you or did you not create a new c_cpp_properties.json? FYI, we've received reports of errorSquiggle issues with clang 4.0 we haven't investigated yet, since we're on 3.8-9 still. If it's working for you, maybe the other users were missing includePaths..

**Comment by cenomla** [comment]
I made a new c_cpp_properties.json. So does that mean that the intellisense engine relies on both the GCC and clang includes not just one or the other?

**Comment by bobbrow** [comment]
the IntelliSense engine should only require one of clang or gcc, not both.

`__SIZE_TYPE__`, `__PTRDIFF_TYPE_`, et al are supposed to be defined internally by the engine when it is compiled for Linux (I'm looking at the code right now).  Can you share your includePath?  I believe that most STD headers include the c++config as `<bits/c++config.h>` so you'd need to have `/usr/include/c++/6.3.1/x86_64-pc-linux-gnu` in your includePath as opposed to `/usr/include/c++/6.3.1/x86_64-pc-linux-gnu/bits`

**Comment by cenomla** [comment]
This is the contents of my includePath:
"/usr/include/c++/6.3.1"
"/usr/include/c++/6.3.1/x86_64-pc-linux-gnu",
"/usr/lib/clang/4.0.0/include",
"/usr/local/include",
"/usr/include"
When I remove "/usr/lib/clang/4.0.0/include" `size_t` is not recognized.

**Comment by sean-mcmanus** [comment]
What OS are you on?

**Comment by cenomla** [comment]
I am using Arch Linux.

**Comment by evanglasgow** [comment]
I was having this issue and solved it by adding this to my includePath: `/usr/lib/gcc/x86_64-linux-gnu/5.4.0/include`

**Comment by dtasev** [comment]
I was having the same issue on Ubuntu 16.04. Adding `"/usr/lib/gcc/x86_64-linux-gnu/5.4.0/include"` indeed solved the issue (as the guy above). Something I noticed was that `size_t` would fail, but `std::size_t` would be properly found without the additional include.

**Comment by saivert** [comment]
I find that the order of the include paths matter.

                "/usr/lib/gcc/x86_64-solus-linux/6.4.0/include",
                "/usr/include/c++/6.4.0",
                "/usr/include",
                "/usr/include/linux",

"/usr/lib/gcc/x86_64-solus-linux/6.4.0/include" has to come first, otherwise size_t will be undefined.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.

If you are having issues resolving system headers, please set the `compilerPath` property in `c_cpp_properties.json` and remove any system include paths from the `includePath` property.
