### ISSUE TITLE
Unable to execute any command in debug console: '-var-create: unable to create variable object' is the responce

### ISSUE THREAD

**Issue by alsam** [microsoft/vscode-cpptools#7400]
Bug type: Debugger

**Describe the bug**
- OS and Version: Arch Linux Linux 5.11.15-arch1-2 SMP PREEMPT Sat, 17 Apr 2021 00:22:30 +0000 x86_64 GNU/Linux
- VS Code Version: 1.54.3-3
- C/C++ Extension Version: 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "launch",
            "name": "gdb (local program)",
            "program": "${workspaceFolder}/build/poisson_solver",
            "cwd": "${workspaceFolder}/build/",
            "args": ["--M", "32", "--N", "64"],
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```
![Снимок экрана_2021-04-21_15-50-25](https://user-images.githubusercontent.com/5341924/115556467-5eea6080-a2b9-11eb-85ca-69d41ce526f5.png)

1. start debug session
2. go to debug console
3. type any command here, say **!pwd**, **pwd** or **ls**
4. get the error message on any command: _-var-create: unable to create variable object_

Thank you!

**Comment by WardenGnaw** [comment]
Any input in the debug console is interpreted as an evaluate command. So just `!pwd` is looking for the variable called `!pwd`. 

To execute the command, as you would be in a gdb terminal is prepending the command with `-exec`

E.g.
`-exec !pwd`
`-exec !ls`

**Comment by alsam** [comment]
About executing the commands such as `-exec !pwd` you are quite right, just checked it, thanks you for clarifying it!
Much more interesting are intrinsic `gdb` command such as `ptype`, they do work excellent as well:
```gdb
-exec ptype po
type = namespace boost::program_options

-exec ptype popt
type = struct program_options {
    bool verbose;
    size_t M;
    size_t N;
    double x_min;
    double x_max;
    double y_min;
    double y_max;
    std::string asy_name;
}

-exec p popt
$1 = {verbose = false, M = 32, N = 32, x_min = -1, x_max = 1, y_min = -1, y_max = 1, asy_name = ""}

popt
{...}
verbose: false
M: 32
N: 32
x_min: -1
x_max: 1
y_min: -1
y_max: 1
asy_name: ""

```

**Comment by liulangrenaaa** [comment]
Is there a way to just type "pwd" in debug console to excute pwd cmd?
like some configs in lauch.json? maybe is more effective

**Comment by tandr** [comment]
This "by design" decision is extremely annoying. I wouldn't mind to have a switch somewhere, so I can use gdb the way it was intended to be used.

**Comment by mattagape** [comment]
It is rather annoying having to type "-exec" in front of each command!

**Comment by bobbrow** [comment]
You should also be able to use a backtick to escape the command instead of `-exec`.  It was added in https://github.com/microsoft/MIEngine/pull/976.

**Comment by uecasm** [comment]
If you want to step through the code then use F10/F11, it's less keys than using the command line or mouse to do it.

This is a very counterintuitive design decision though, especially for a window labelled "Debug Console".  You expect consoles to be accepting commands by default.

**Comment by maximilianmordig** [comment]
Which commands work without using this `-exec` or backtick prefix? Even a gdb command like `help` needs to be prefixed.

**Comment by mickeyl** [comment]
Can't we just have a mode switch between `expression REPL` and `gdb REPL`? It's extremely unconvenient with this `-exec` prefix.

**Comment by bcattle** [comment]
Just want to echo this is a bad design decision because it crushes gdb's elegant syntax for allowing you to [specify the format](https://sourceware.org/gdb/current/onlinedocs/gdb.html/Output-Formats.html) of the output, for example `p/x` to get hexadecimal.

**Comment by jlitewski** [comment]
I also want to echo how dumb this "by design" choice is. If I use the GDB debugger, I want to be able to use it the way I would in literally any other terminal. Appending a backtick or ``-exec`` is extremely unintuitive and counterproductive.

**Comment by bensternlieb** [comment]
Still doesn't work with `-exec` for me (below `s_led_state` is a variable from the blink example, it evaluates directly as expected.). This is a bit from the `>`  dbg console.

```
[esp32s3.cpu1] Target halted, PC=0x40378F16, debug_reason=00000000
s_led_state
1 '\001'
-exec ls
-var-create: unable to create variable object
-exec help
-var-create: unable to create variable object
```
vscode Version info:
```
Version: 1.96.4
Commit: cd4ee3b1c348a13bafd8f9ad8060705f6d4b9cba
Date: 2025-01-16T00:16:19.038Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-51-generic
```
(ESP-IDF extension generated) launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "gdbtarget",
      "request": "attach",
      "name": "Eclipse CDT GDB Adapter"
    },
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
}
```
Other Version info
```
$ ps -xo 'exe' | grep "gdb\|openocd\|vscode"
/home/<me>/.espressif/tools/openocd-esp32/v0.12.0-esp32-20241016/openocd-esp32/bin/openocd
/home/<me>/.vscode/extensions/ms-vscode.cpptools-1.23.5-linux-x64/bin/cpptools
/home/<me>/.espressif/tools/xtensa-esp-elf-gdb/14.2_20240403/xtensa-esp-elf-gdb/bin/xtensa-esp-elf-gdb-3.12
/home/<me>/.vscode/extensions/ms-vscode.cpptools-1.23.5-linux-x64/bin/cpptools-srv
```

**Comment by bryghtlabs-richard** [comment]
@bensternlieb , same inability to use GDB commands, basically same IDE. Maybe this is a difference in gdbtarget vs gdb?

**Comment by bryghtlabs-richard** [comment]
Looks like `gdbtarget` has [its own deviant escape syntax](https://docs.espressif.com/projects/vscode-esp-idf-extension/en/latest/debugproject.html#send-commands-to-gdb).
