### ISSUE TITLE
Support for additional Doxygen tags in hover popup

### ISSUE THREAD

**Issue by szepeu** [microsoft/vscode-cpptools#7406]
Type: Feature Request

While working on a module, which has some specific requirements, I noticed that the docs text marked with `@warning` or `@attention` does not display at all in the docs' hover popup. Moreover, it would be great to handle `@brief` in a separate line (well... I don't think newlines are supported at all :/ ).

![115567764-e507a680-a2bb-11eb-88a8-3b3f715b1049](https://user-images.githubusercontent.com/24934271/115680284-ba692c80-a353-11eb-8339-fea69e03ac21.gif)

**Comment by michelleangela** [comment]
@szepeu 
There's the setting `C_Cpp.simplifyStructuredComments`. If this is set to `true` only certain labels of structured comments will be displayed. Otherwise, all comments (all labels) will be displayed.

**Comment by szepeu** [comment]
Okay, I see You added "by design" label. Thanks for support!
