### ISSUE TITLE
Intellisense/Syntax Highlighting No Longer Works After Enabling CMake Tools Extension

### ISSUE THREAD

**Issue by bradke73** [microsoft/vscode-cpptools#7407]
Bug type: Language Service

**Describe the bug**
- Windows 10
- VS Code Version: 1.55.2
- C/C++ Extension Version: 1.3.1
- Other extensions you installed (and if the issue persists after disabling them): CMake Tools

I will get include errors for headers that exist within the workspace. Intellisense is unable to assist.

**Steps to reproduce**

1. Enable the CMake Tools extension
2. Intellisense no longer functions. Syntax highlighting no longer recognizes classes.

**Expected behavior**
Intellisense will function and class recognition is functional.

**Comment by bradke73** [comment]
It looks like this is a known issue in the CMake Tools extension:

https://github.com/microsoft/vscode-cmake-tools/issues/1786

**Comment by bobbrow** [comment]
CMake Tools 1.7.1 was released with a patch for this bug.
