### ISSUE TITLE
Add some C_Cpp.nonRecursiveDirectories setting to avoid excessive directory iteration/parsing with /, /usr/include, etc.

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7415]
Hit by https://github.com/microsoft/vscode-cpptools/issues/7394 . / should be probably be the default, adding /usr/include has the potential to cause regressions.

**Comment by bobbrow** [comment]
What if we just disabled `/` (without a setting) and changed the compiler query results to add `/*` to all system include paths?  Would that be enough to deal with the problem?  I'm not really fond of the idea of adding a setting for this.

**Comment by sean-mcmanus** [comment]
Yeah, the "/" seems fine, but making the system includes non-recursive could regress an unknown number of users who are relying on /usr/include (etc.) being recursive since it's been that way for a few years...i.e. not sure many users would complain about it. The current workaround is to add the subdirectories of /usr/include (etc.) to C_Cpp.files.exclude (but the problem with that is there could be many, although I've found that excluding just the largest ones seems to be pretty good).
