### ISSUE TITLE
"Go to definition" feature stopped working suddenly

### ISSUE THREAD

**Issue by dortamiguel** [microsoft/vscode-cpptools#7419]
Bug type: Language Service

**Describe the bug**
- OS and Version: macOS Catalina
- VS Code Version: 1.55.2
- C/C++ Extension Version: v1.3.1

- I used to be able to select "Go to definition" or "alt + click" some code like a function, and when doing so the editor opened the file that contained the declaration for that function. Seems like it suddenly stopped.

**Steps to reproduce**

1. Go to to a cpp file, right click in a function, click "Go to definition"

**Expected behavior**

- After clicking "Go to definition" I expect the header file that contains the declaration for the function to open

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`
```json
{
  "C_Cpp.default.forcedInclude": [
    "${workspaceFolder}/src/pch.hpp"
  ],
  "C_Cpp.default.cppStandard": "c++20",
  "C_Cpp.default.includePath": [
    "${workspaceFolder}/include"
  ]
}
```

**Comment by ellipticaldoor** [comment]
I uninstalled vscode, clear all the caches and extensions. And after reinstalling everything it started to work again
