### ISSUE TITLE
How to pass VSC variables from c_cpp_properties.json to a Task?

### ISSUE THREAD

**Issue by rei-vilo** [microsoft/vscode-cpptools#742]
I'm running a makefile with the C/C++ for Visual Studio Code extension and I've defined some configurations in `c_cpp_properties.json`. 

How to read and get the configurations values from the makefile? 

Thanks!

**Comment by sean-mcmanus** [comment]
You have to manually open the makefile and modify the includePath/defines settings in c_cpp_properties.json accordingly. Does that work for you?

**Comment by rei-vilo** [comment]
Editing the make-file works for me, but the idea was to have a better integration. Leveraging Visual Studio Code interface to set parameters and retrieving those parameters from the makefile.

Is there something like `export VARIABLE=VALUE` available?

**Comment by bobbrow** [comment]
Which VS Code variables are you trying to read?  Our extension does not set any environment variables.  The contents of c_cpp_properties.json is not exported to the environment.

**Comment by sean-mcmanus** [comment]
@rei-vilo I assume you mean editing the "c_cpp_properties.json"? You shouldn't need to edit the makefile. Are you asking for cpptools to read the makefile and set the includePath and defines ourselves? Visual Studio 2017 does that for cmake, but we haven't implemented that yet. Theoretically, anyone could write a VS Code extension (or any script) that read makefiles or other build settings and read/modified our c_cpp_properties.json to correctly set the includePath/defines.

**Comment by rei-vilo** [comment]
I've modified `c_cpp_properties.json` to define different configurations with tool-chains and SDK instead of the OSes.

```
{
    "configurations": [
        {
            "name": "LaunchPad MSP432",
            "includePath": [
                "~/Library/Energia15/packages/energia/hardware/msp432r",
                "~/Library/Energia15/packages/energia/tools/arm-none-eabi-gcc"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "",
                "path": [
                    "~/Library/Energia15/packages/energia/hardware/msp432r",
                    "~/Library/Energia15/packages/energia/tools/arm-none-eabi-gcc"
                ]
            }
        },
       {
            "name": "LaunchPad LM4F120",
            "includePath": [
                "~/Library/Energia15/packages/energia/hardware/tivac",
                "~/Library/Energia15/packages/energia/tools/arm-none-eabi-gcc"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "",
                "path": [
                    "~/Library/Energia15/packages/energia/hardware/tivac",
                    "~/Library/Energia15/packages/energia/tools/arm-none-eabi-gcc"
                ]
            }
        }
    ]
}
```

I need to get the `"name"` field so the main makefile can switch to the appropriate secondary one. Similarly, I’d like to add other fields and read them from the main makefile.

**Comment by rei-vilo** [comment]
Once a configuration is selected, _e.g._ `LaunchPad MSP432` as per https://github.com/Microsoft/vscode-cpptools/issues/742#issuecomment-304382278, how to get that value and pass it to the task `Build`, _i.e._ `{{name}}`?

```
{
    "version": "0.1.0",
    "isShellCommand": true,
    "tasks": [
        {
            "taskName": "Build",
            "isBuildCommand": true,
            "showOutput": "always",
            "command": "make",
            "args": ["build", {{name}}],
            "suppressTaskName": true,
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
    ]
}
```

**Comment by rei-vilo** [comment]
Title **How to pass VSC variables from c_cpp_properties.json to a Task?** seems more appropriate.

**Comment by sean-mcmanus** [comment]
@rei-vilo There is currently no way to automatically get the value of the cpptools configuration name.

**Comment by rei-vilo** [comment]
Ok, thanks, this is a show-stopper.

**Comment by rei-vilo** [comment]
@czgtest

Maybe you can help on this issue too.

**Comment by bobbrow** [comment]
https://github.com/Microsoft/vscode/issues/43782

**Comment by rei-vilo** [comment]
@bobbrow  Link to https://github.com/Microsoft/vscode/issues/43782 seems to be dead.

**Comment by rei-vilo** [comment]
@bobbrow What do mean by **more info needed**?

**Comment by bobbrow** [comment]
I removed that tag while doing some issue cleanup last week.  It was set a long time ago before we understood the issue.

**Comment by rei-vilo** [comment]
From [c_cpp_properties.json reference | Configuration properties](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference#_configuration-properties)
>**defines** A list of preprocessor definitions for the IntelliSense engine to use while parsing files. Optionally, use `=` to set a value, for example `VERSION=1`.

Why not provide a similar logic for definitions **tasks.json** may read and use from **c_cpp_properties.json**?

[Integrate with External Tools via Tasks | Variable substitution](https://code.visualstudio.com/Docs/editor/tasks#_variable-substitution) details [Predefined variables](https://code.visualstudio.com/docs/editor/variables-reference), [Environment variables](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables) and [Configuration variables](https://code.visualstudio.com/docs/editor/variables-reference#_configuration-variables), but is mum about variables defined in **c_cpp_properties.json** `configurations`.

**Comment by sean-mcmanus** [comment]
VS Code itself controls the execution of tasks.json and there's no way for us to get them to use c_cpp_properties.json info.

**Comment by bobbrow** [comment]
Sorry, I should have resolved this issue a long time ago.  VS Code added a feature that lets us do [this](https://github.com/microsoft/vscode-cpptools/issues/742#issuecomment-334995844) and we added a command to get the active configuration name that you can use in your tasks.json.

`${command:cpptools.activeConfigName}`

**Comment by rei-vilo** [comment]
Thank you!

**Comment by rei-vilo** [comment]
@bobbrow It works fine. 

Where can I find the documentation related to this feature? Pages [Customizing default settings](https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp) and [c_cpp_properties.json reference](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference) for the **C++ extension**, and page [Integrate with External Tools via Tasks](https://code.visualstudio.com/docs/editor/tasks#vscode) for **Tasks**, do not mention `cpptools.activeConfigName`.

Thank you!
