### ISSUE TITLE
Add a "Complete Switch Statement" refactoring feature

### ISSUE THREAD

**Issue by iamsergio** [microsoft/vscode-cpptools#7420]
Some C++ IDEs allow you to right-click on a _switch_ statement and choose "Complete Switch".
The IDE then inserts all the missing case blocks.

This applies only when switching on enums, not ints.

**Comment by sean-mcmanus** [comment]
I don't believe extensions have an API for implementing a context-sensitive right-click, but this might be implementable via a RefactorRewrite CodeAction. VS has a switch snippet that will auto-create all the cases at the initial switch creation (which we could also potentially implement in VS Code), but there's no ability to complete an existing switch statement with missing cases (I've filed a feature request on VS at https://developercommunity.visualstudio.com/t/Add-the-ability-to-auto-add-missing-case/1408111 ).

**Comment by sean-mcmanus** [comment]
Which IDE has this feature?

**Comment by iamsergio** [comment]
> Which IDE has this feature?

QtCreator
