### ISSUE TITLE
#include<stdio.h> won't work

### ISSUE THREAD

**Issue by Dude-Guy-Man** [microsoft/vscode-cpptools#7421]
These are the errors it gives me in the terminal when I try to run it:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\User\Documents\C and C++> cd "c:\Users\User\Documents\C and C++\" ; if ($?) { gcc test.c -o test } ; if ($?) { .\test }
gcc : The term 'gcc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:56
+ cd "c:\Users\User\Documents\C and C++\" ; if ($?) { gcc test.c -o  ...
+                                                        ~~~
    + CategoryInfo          : ObjectNotFound: (gcc:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\User\Documents\C and C++>
```

I'm new to C so sorry if there's an extreme lack of context

**Comment by sean-mcmanus** [comment]
Can you try deleting your launch.json/tasks.json and just using the F5 with test.c active to create a new launch.json/tasks.json? I'm not sure what shell that script is expected to run in -- are you sure it's powershell? You may want to try adding the full path to gcc or adding the path to gcc to your environment PATH variable.

We have some docs at https://code.visualstudio.com/docs/cpp/config-mingw .
