### ISSUE TITLE
C compiler false errors

### ISSUE THREAD

**Issue by 0xENDER** [microsoft/vscode-cpptools#7422]
![image](https://user-images.githubusercontent.com/72353925/116010518-1075f280-a628-11eb-9e61-5d3fbf365335.png)

**Comment by sean-mcmanus** [comment]
Does the error go away when you move your cursor to a new line? I'm not reproing the bug. Do you have more repro info? Are you able to repro it consistently via certain steps? What OS and compiler are you using? The output of running C/C++: Log Diagnostics from the Command Palette could help us.

![image](https://user-images.githubusercontent.com/19859882/116132035-ebae6900-a681-11eb-94a1-5b51f4c32835.png)

**Comment by adel-sbeh** [comment]
I just reinstall the whole thing, and all the errors stopped...I'mma close this for now.
