### ISSUE TITLE
The compilerPath option does not match the tick in front of the option in the drop-down box (Mac OS only)

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7427]
Bug type: Language Service

**Describe the bug**
- OS: Mac and Mac ARM64
- C/C++ Extension Version: 1.3.0
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Open IntelliSense Configuration UI
2. Change the compiler path selection option.
3. The option does not match the tick in front of the option in the drop-down box (select any of the compiler paths, re-open the drop-down box, the tick is in the first path unchanged)
![image](https://user-images.githubusercontent.com/38734287/116159332-e31b5a00-a6a4-11eb-90a5-c299bed146fb.png)

**Expected behavior**
The "check mark" should be in front of the corresponding compilation path.

**Comment by michelleangela** [comment]
This was found from internal testing of 1.3.0

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.22.3
