### ISSUE TITLE
IncludePath of IntelliSense Configuration UI is not resolved correctly on ARM64?

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7428]
Bug type: Language Service

**Describe the bug**
- OS: Windows ARM64
- C/C++ Extension Version: 1.3.0
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

It looks like IncludePath is not getting resolved correctly on Windows ARM64.

**Steps to reproduce**

1. Open IntelliSense Configuration UI
2. Type in an invalid path in "IncludePath" property.
![image](https://user-images.githubusercontent.com/38734287/116161378-81f58580-a6a8-11eb-84ed-29aadceff795.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/38734287/116161396-8ae65700-a6a8-11eb-8801-727ffbc3702d.png)

**Comment by michelleangela** [comment]
This was found from internal testing of 1.3.0

**Comment by Colengms** [comment]
@michelleangela I'm not able to repro this, even with 1.3.0.  Is it possible the original repro was while connected to a Linux machine via SSH?  On Linux, `:` is not a valid character to use in a path, and is used as a path delimiter.

**Comment by michelleangela** [comment]
This was reported through internal testing. It looks like the scenario of using a drive letter such as "c:/" was used for testing on all platforms. 

Using an invalid path with a drive letter on Windows does not reproduce, so closing this issue as no repro.  Note, if ":" is used on Linux and macOS, it will be used a path delimiter and therefore the invalid path error creates two errors for one path.
