### ISSUE TITLE
vsc dialog "未能完成该操作。（OSStatus 错误 -60006。）"

### ISSUE THREAD

**Issue by begend** [microsoft/vscode-cpptools#745]
my env is 

- mac os 10.10.12

- vsc version: 1.10.2

- cpptools: 0.11.0
-code : cpp

**Comment by sean-mcmanus** [comment]
Does the error occur without our extension? When do you see the error? Can you update your VS Code to 1.12.2 and cpptools to 0.11.1? Your Mac OS is also out of date by a couple years. We don't do any Mac testing on version 10.10, only 10.11 and 10.12.

**Comment by begend** [comment]
i will try, thanks

**Comment by begend** [comment]
what's wrong with "The intellisense engine has stopped responding" ?

**Comment by sean-mcmanus** [comment]
That means our IntelliSense engine process crashed. We are aware of various crashes and plan to fix them (and give a better experience when a crash occurs).

**Comment by begend** [comment]
my project has about 20w lines of code and my encoding is gbk. Maybe it has something to do with it

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
