### ISSUE TITLE
C/C++ includePath does not support ** well

### ISSUE THREAD

**Issue by efikarl** [microsoft/vscode-cpptools#7450]
Issue Type: <b>Bug</b>

For example: 
There are lots of *.h in MdeModulePkg/Include/Protocol,
`${workspaceFolder}/**/Include/**` of includePath setting doesn't work for me.

Besides, why not support exclude at the same time, is there is a way to do this?

Extension version: 1.3.1
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.21370

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz (16 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.27GB free)|
|Process Argv|--crash-reporter-id 1256280c-a6e0-4f90-8949-e0a355680eaf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

**Comment by sean-mcmanus** [comment]
We don't support "**" in the middle of the path, only at the end. We support files.exclude and C_Cpp.files.exclude for directories. Is that sufficient?

**Comment by efikarl** [comment]
ok, thank you, this ticket can be closed now.
