### ISSUE TITLE
"gets" is not identified as pre defined function. Which causes it to give pseudo warning. please see to it.

### ISSUE THREAD

**Issue by AkshayDeopurkar** [microsoft/vscode-cpptools#7452]
Bug type: Language Service

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
```
char *gets(char *__s)
Get a newline-terminated string from stdin, removing the newline.

This function is impossible to use safely. It has been officially
removed from ISO C11 and ISO C++14, and we have also removed it
from the _GNU_SOURCE feature list. It remains available when
explicitly using an old ISO C, Unix, or POSIX standard.
```

Are you able to fix your issue by changing the cStandard or cppStandard? Or try fgets instead https://www.cplusplus.com/reference/cstdio/fgets/ ?
