### ISSUE TITLE
Request: Guess Function Argument

### ISSUE THREAD

**Issue by ericbaobao** [microsoft/vscode-cpptools#7453]
Type: Productivity Feature Request

1. when printf, auto add bracket, quotation and semicolon. ex: printf(""); when scanf add extra comma scanf("", );

2. if that line is calling a function, on select it, auto add bracket and semi-colon in the end of line. ex: test();

3. Java vscode plugin got guess function argument, cpptool should have too, it is so convienient. [here](https://github.com/microsoft/vscode-cpptools/issues/7453#issuecomment-831649185)
 ![Untitled Project](https://user-images.githubusercontent.com/78641493/116955744-fb533080-acc5-11eb-9f41-5b66c6c69071.gif)

I don't want to rely on other extension like tab9 to suggest the argument(s) because for me vscode-cpptools is good enough and tab9 tend to take lot of ram.

this will help to improve all developers productivity very much
I deeply appreciated if this request can be aded, I love you guys for providing and improving this extension.
![image](https://user-images.githubusercontent.com/78641493/116785222-ee1e2200-aaca-11eb-94fd-84f89ffeed96.png)

**4. Lastly a proposal to solve the world security issue, add option to enforce initialise every variable. If this 4th proposal is too hard to implement, it is ok leave it now.**

Again, thank you very much for all you guys contribution making it better day by day. 
![image](https://user-images.githubusercontent.com/78641493/122683317-00961b80-d231-11eb-93d1-237a66d97a93.png)

**Comment by sean-mcmanus** [comment]
Which Java vscode extension has that feature?

**Comment by ericbaobao** [comment]
> Which Java vscode extension has that feature?

It is the official java extension of vscode one, to be specific if I am not mistaken it is this one. 
https://marketplace.visualstudio.com/items?itemName=redhat.java

If you rely on voting you will not get much I believe because this is the feature only Java developers that tried this know how convenient it is. Even official Visual Studio don't have this feature.

It will guess the argument(s) base on the datatype of the parameter.
Then automatic fit in the variable name matching with the same datatype.
If the function/method argument match the variables name in upper scope, then the it will auto suggest the same one.

Sample:
int sumTwoNum(int numOne, int numTwo)
{
    return numOne + numTwo;
}

int main()
{
    int answer, numOne, numTwo;

    answer = sumTwoNum <-- then intellisense will suggest same variable name become sumTwoNum(numOne, numTwo)
    return 0;
}

**Comment by ericbaobao** [comment]
Hope this help, afaik they adapt it from here 
https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
```
private void appendGuessingCompletion(StringBuilder buffer, CompletionProposal proposal) {

private String[] guessParameters(char[][] parameterNames, CompletionProposal proposal) throws JavaModelException {
		int count = parameterNames.length;
		String[] result = new String[count];
		String[] parameterTypes = getParameterTypes(proposal);
		IJavaElement[][] assignableElements = getAssignableElements(proposal);
		ParameterGuesser guesser = new ParameterGuesser(compilationUnit);
		for (int i = count - 1; i >= 0; i--) {
			String paramName = new String(parameterNames[i]);
			String argumentProposal = guesser.parameterProposals(parameterTypes[i], paramName, assignableElements[i]);
			if (argumentProposal != null) {
				result[i] = argumentProposal;
			} else {
				result[i] = paramName;
			}
		}
		return result;
}

```

**Comment by ericbaobao** [comment]
Hope this help act as pseudocode, afaik they adapt it from here 
https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
```
private void appendGuessingCompletion(StringBuilder buffer, CompletionProposal proposal) {

private String[] guessParameters(char[][] parameterNames, CompletionProposal proposal) throws JavaModelException {
		int count = parameterNames.length;
		String[] result = new String[count];
		String[] parameterTypes = getParameterTypes(proposal);
		IJavaElement[][] assignableElements = getAssignableElements(proposal);
		ParameterGuesser guesser = new ParameterGuesser(compilationUnit);
		for (int i = count - 1; i >= 0; i--) {
			String paramName = new String(parameterNames[i]);
			String argumentProposal = guesser.parameterProposals(parameterTypes[i], paramName, assignableElements[i]);
			if (argumentProposal != null) {
				result[i] = argumentProposal;
			} else {
				result[i] = paramName;
			}
		}
		return result;
}

```

**Comment by ericbaobao** [comment]
Hope this help act as pseudocode, afaik they adapt it from here 
https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
```
private void appendGuessingCompletion(StringBuilder buffer, CompletionProposal proposal) {

private String[] guessParameters(char[][] parameterNames, CompletionProposal proposal) throws JavaModelException {
		int count = parameterNames.length;
		String[] result = new String[count];
		String[] parameterTypes = getParameterTypes(proposal);
		IJavaElement[][] assignableElements = getAssignableElements(proposal);
		ParameterGuesser guesser = new ParameterGuesser(compilationUnit);
		for (int i = count - 1; i >= 0; i--) {
			String paramName = new String(parameterNames[i]);
			String argumentProposal = guesser.parameterProposals(parameterTypes[i], paramName, assignableElements[i]);
			if (argumentProposal != null) {
				result[i] = argumentProposal;
			} else {
				result[i] = paramName;
			}
		}
		return result;
}

```
