### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by szabolcsdombi** [microsoft/vscode-cpptools#747]
![image](https://cloud.githubusercontent.com/assets/11232402/26284962/8a1c7d3c-3e46-11e7-80c6-a55da19de3ae.png)

This button does nothing for this extension.

> overly attached extension 🤣

**Comment by bobbrow** [comment]
😆 As far as I am aware, we don't control the uninstall - VS Code does.  One thing you can try is to just delete the extension folder from your computer.

On Windows it is `%userprofile%\.vscode\extensions\ms-vscode-cpptools-0.11.1`
On Linux/Mac it is `~/.vscode/extensions/ms-vscode-cpptools-0.11.1`

**Comment by szabolcsdombi** [comment]
Maybe some files were locked. Manually delete is fine.
You can close the issue.
Thank you
