### ISSUE TITLE
-std=c2x support for C++-style attributes in C-code.

### ISSUE THREAD

**Issue by Iipal** [microsoft/vscode-cpptools#7471]
Bug type: Language Service

- OS and Version: Ubuntu 20.04
- VS Code Version: 1.56
- C/C++ Extension Version: 1.3.1

**Expected behavior**

No errors?
inside union `allocator_t`->`data` appears as an unknown data type (2nd screenshot)

**Code sample and logs**
- Code sample && Configurations in `c_cpp_properties.json`: on the screenshot below
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette: shows nothing

![image](https://user-images.githubusercontent.com/31858171/117289895-d43b6100-ae75-11eb-948c-e5d34ee35cff.png)
![image](https://user-images.githubusercontent.com/31858171/117290536-9854cb80-ae76-11eb-9957-0502ae86211b.png)
> Theme: Darcula with JetBrains Mono font.

**Comment by Iipal** [comment]
even `__auto_type` behavior is strange for `linux-clang-x64` mode even if `__is_identifier` says it's valid;

if I change the mode to `linux-gcc-x64` as well as a compiler to `gcc` - then everything works fine. But why in clang-mode it's said that it's a valid identifier but then I see errors?
![image](https://user-images.githubusercontent.com/31858171/117298386-fd60ef00-ae7f-11eb-9ffb-d9b7bc4d8133.png)

**Comment by sean-mcmanus** [comment]
Can you provide a code sample that compiles with C but gives an error with our extension? I'm seeing gcc and clang both fail to compile 
```
typedef union {
    int i;
} allocator_t [[gnu::transparent_union]];

int main()
{
    return 0;
}
```

error: expected expression
} allocator_t [[gnu::transparent_union]];

**Comment by sean-mcmanus** [comment]
Oh -- I got it to compile with -std=c2x -- we don't support that std version yet. We can use this issue to track adding that.

**Comment by sean-mcmanus** [comment]
I've filed a bug against our shared VS parser at https://developercommunity.visualstudio.com/t/C-standard-2x-isnt-supported-by-Intelli/1416530 . After they enable that we can add support on our side.

**Comment by TDHolmes** [comment]
I hope this lands soon. My project has started adopting these features and causes syntax errors throughout the project (specifically sized enums)

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.14.4
