### ISSUE TITLE
Completion fails when it's on the last line of a file

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/vscode-cpptools#7472]
Type: Feature Request

header file:
 
![image](https://user-images.githubusercontent.com/5162926/117296435-a0792f00-aea7-11eb-918f-ef03356eebed.png)

source file:
![image](https://user-images.githubusercontent.com/5162926/117296513-b8e94980-aea7-11eb-9665-e04ae0452935.png)

I think TCPClient should appear in the suggestion list

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue on Windows or Linux. Can you provide more info, such as the results of running C/C++: Log Diagnostics from the Command Palette?

![image](https://user-images.githubusercontent.com/19859882/117361421-dc43d280-ae6e-11eb-83a2-c8a694537f54.png)

**Comment by xspeed1989** [comment]
> I'm not reproing the issue on Windows or Linux. Can you provide more info, such as the results of running C/C++: Log Diagnostics from the Command Palette?
> 
> ![image](https://user-images.githubusercontent.com/19859882/117361421-dc43d280-ae6e-11eb-83a2-c8a694537f54.png)
> 
> It's possible the contents of asio.hpp is causing a problem (I don't have that file).


@sean-mcmanus 
```
-------- Diagnostics - 2021/5/7上午9:54:52
Version: 1.3.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "c:/users/changjiong/desktop/test/build/cmakefiles/816faa749c7ce6139e9e43527e1469ff",
        "g:/work/lwassistant/source/server/kyservice/thirdparty/asio/include",
        "c:/users/changjiong/desktop/test"
    ],
    "compilerPath": "c:/program files (x86)/microsoft visual studio/2019/community/vc/tools/msvc/14.28.29910/bin/hostx64/x64/cl.exe",
    "compilerArgs": [
        "/DWIN32",
        "/D_WINDOWS",
        "/W3",
        "/GR",
        "/EHsc",
        "/MD",
        "/Zi",
        "/O2",
        "/Ob1",
        "/DNDEBUG",
        "-MD"
    ]
}
Custom configurations:
[ C:\Users\changjiong\Desktop\test\tcpClient.cpp ]
{
    "defines": [
        "WIN32",
        "_WINDOWS",
        "NDEBUG"
    ],
    "includePath": [
        "e:/asio/include"
    ],
    "compilerPath": "c:/program files (x86)/microsoft visual studio/2019/community/vc/tools/msvc/14.28.29910/bin/hostx64/x64/cl.exe",
    "compilerArgs": [
        "/DWIN32",
        "/D_WINDOWS",
        "/W3",
        "/GR",
        "/EHsc",
        "/MD",
        "/Zi",
        "/O2",
        "/Ob1",
        "/DNDEBUG",
        "-MD"
    ]
}
Translation Unit Mappings:
[ C:\Users\changjiong\Desktop\test\tcpClient.cpp ]:
    C:\USERS\CHANGJIONG\DESKTOP\TEST\TCPCLIENT.CPP
Translation Unit Configurations:
[ C:\Users\changjiong\Desktop\test\tcpClient.cpp ]:
    Process ID: 9120
    Memory Usage: 26 MB
    Compiler Path: c:/program files (x86)/microsoft visual studio/2019/community/vc/tools/msvc/14.28.29910/bin/hostx64/x64/cl.exe
    Includes:
        E:\ASIO\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.28.29910\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.28.29910\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\CPPWINRT
    Defines:
        WIN32
        _WINDOWS
        NDEBUG
        WIN32
        _WINDOWS
        NDEBUG
    Standard Version: ms_c++14
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 26 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5687
Number of files parsed: 1382


```

**Comment by xspeed1989** [comment]
> Yeah, your C/C++: Log Diagnostics results seem good. It seems like something is getting parsed incorrectly in your TU. Is the asio library available somewhere?

@sean-mcmanus https://github.com/chriskohlhoff/asio/

**Comment by sean-mcmanus** [comment]
@xspeed1989 Thanks -- I repro the issue now. Investigating...

**Comment by sean-mcmanus** [comment]
Completion is failing when it's at the end of the file. Can you try adding a new line afterwards? It should start working then.

![image](https://user-images.githubusercontent.com/19859882/117519961-c6134080-af5a-11eb-9bfd-be8013980023.png)

**Comment by xspeed1989** [comment]
> Completion is failing when it's at the end of the file. Can you try adding a new line afterwards? It should start working then.
> 
> ![image](https://user-images.githubusercontent.com/19859882/117519961-c6134080-af5a-11eb-9bfd-be8013980023.png)

@sean-mcmanus  it's works for me, but the constructor didn't in the suggestion list when i type TCPClient::

**Comment by sean-mcmanus** [comment]
@xspeed1989 I've filed issue https://github.com/microsoft/vscode-cpptools/issues/7505 to track that -- it's a recent regression.

**Comment by xspeed1989** [comment]
@sean-mcmanus 
OK, thanks a lot.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders2
