### ISSUE TITLE
Few syntax highlighting issues in class inheritance declarations

### ISSUE THREAD

**Issue by Vultraz** [microsoft/vscode-cpptools#748]
Inherited class names aren't highlighted correctly if they're on a new line

![class formatting issue](https://cloud.githubusercontent.com/assets/3558659/26288042/2f626a58-3ed4-11e7-9bd8-d0acaab6f751.JPG)

Virtual keyword in inheritance takes the class name highlighting.

![class formatting issue2](https://cloud.githubusercontent.com/assets/3558659/26288057/9bb59ba8-3ed4-11e7-9318-bdd9214a1074.JPG)

**Comment by bobbrow** [comment]
It looks like the grammar has an issue tracking this.  See https://github.com/atom/language-c/issues/232
I will add a note about the virtual keyword to that issue.

Thank you for the report.
