### ISSUE TITLE
intellisense error when preprocess variable is a string

### ISSUE THREAD

**Issue by pwittich** [microsoft/vscode-cpptools#7484]
Issue Type: <b>Bug</b>

This is for a C/C++ project. I have a preprocessor macro which is a string. In my compile_commands.json file it is defined as 

`   "-DFIRMWARE_VERSION=\"v0.31.14-1-g0731f-dirty\"",`

however the quotes get stripped from it and so code such as 

  Print("Staring Apollo CM MCU firmware " FIRMWARE_VERSION
        "\r\n\t\t (FreeRTOS scheduler about to start)\r\n");

gets flagged as an error, though it compiles just fine. 

mousing over FIRMWARE_VERSION shows it as 

#define FIRMWARE_VERSION v0.31.14-1-g0731f-dirty

i.e., the quotes get lost. 

Extension version: 1.3.1
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|40.00GB (3.93GB free)|
|Process Argv|--crash-reporter-id c670bf7f-6611-4ff8-bc75-7eaf3fbae75d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
I believe that is "by design" -- we expect the compile_commands.json to use `\\\"v0.31.14-1-g0731f-dirty\\\"` too get `"v0.31.14-1-g0731f-dirty"` . @Colengms might have more info.

**Comment by pwittich** [comment]
The compilation path is via a makefile, so it does not directly use the compile_commands.json. I am creating the JSON file via the `compiledb` Python script.

**Comment by sean-mcmanus** [comment]
Then it's most likely a bug with the compiledb Python script. You may want to consider trying the vscode-makefile-tools extension and setting that as the configurationProvider instead of setting compileCommands as a workaround.

**Comment by pwittich** [comment]
ok, thank you, I guess I should close this issue (or will you do it?). 

re vscode-makefile-tools, I am excited about that project, but as of now it doesn't appear to work with my makefiles (recursive make).
