### ISSUE TITLE
Why Not Support Semantic Analysis for C/CPP

### ISSUE THREAD

**Issue by eaglexiang** [microsoft/vscode-cpptools#749]
symbol search does be useful in mini projects, but not so useful in large projects too. Why not share the semantic analysis of visual studio? At least support it when with VS installed on PC.

**Comment by bobbrow** [comment]
This is a work in progress.  We are tracking semantic auto-complete with issue #13.  Semantic goto definition is issue #255.  Find all references is #15.

Thank you for your feedback.
