### ISSUE TITLE
Namespace std has no member cout

### ISSUE THREAD

**Issue by RahulYddv** [microsoft/vscode-cpptools#7491]
this is my json properties file
![Screenshot (1)](https://user-images.githubusercontent.com/83851235/117523578-c8b37b80-afd6-11eb-886f-d89d3d2deeca.png)
and this is a simple program which i write
![Screenshot 2021-05-08 082650](https://user-images.githubusercontent.com/83851235/117523649-29db4f00-afd7-11eb-9292-1d6f9db658b3.png)
please give me a solution

**Comment by pisanglemonmelon** [comment]
1. On the `#include <iostream>`, please right click on the `iostream` then `Go to Definition`.  The content of the `iostream` should be shown successfully. Let me know when it's not the case.
2. Please post the full content of `c_cpp_properties.json`. I can't see the full text from your screenshot.
3. Your `c_cpp_properties.json` seems inconsistent. You use mingw32 (32-bit of GCC) on `includePath`, but you use MSVC 32-bit on `compilerPath`, and then you set windows-msvc-x64 on `IntelliSenseMode`. Those three are different. Please edit to make it consistent.

**Comment by RahulYddv** [comment]
1. The file which you said for iostream was below
![Screenshot 2021-05-08 165817](https://user-images.githubusercontent.com/83851235/117557057-d297b600-b08c-11eb-935e-4e701fc7501c.png)
2. And my c_cpp_properties.json 
![Screenshot 2021-05-09 060608](https://user-images.githubusercontent.com/83851235/117557075-01ae2780-b08d-11eb-8e82-c6af0ebea690.png)
