### ISSUE TITLE
Add a button to build and run the program like Code Runner Extension

### ISSUE THREAD

**Issue by clicktodev** [microsoft/vscode-cpptools#7497]
Type: Feature Request

A button to easily build and run the file would be great, something like the java, python and code runner extensions provide.

**Comment by sean-mcmanus** [comment]
Is the right-click "Build and debug active file" not sufficient? Is this a request to just add a UI button?

**Comment by hichemfantar** [comment]
Yeah something like what the java extension provides would be great.
![image](https://user-images.githubusercontent.com/34947993/117833757-85733a00-b26e-11eb-9567-a0a7ff14ccf2.png)

**Comment by hichemfantar** [comment]
Glad this was picked up again, would appreciate it if you added a "Build and Run active file" in addition to "Build and Debug active file".
Basically a way to run the file without the debugger.

**Comment by Lunchb0ne** [comment]
Implementation depends on the OS, but generally, you can do something like `&& .\${fileBasenameNoExtension}` at the end of the build task to run it too, so you can then make the build task the default, letting you use Ctrl+B keybind to build and run it in a single step.

**Comment by bobbrow** [comment]
I must have pushed a wrong button. I didn't mean to close this.

**Comment by Zingam** [comment]
Will there be an unified experience, which unifies the UI regardless of the build system like with the CMake extension.
Like build, run, test, etc, which also take into account the selected launch config. Well maybe this should be more of a VSCode thing. Currently every language, debugger extension do their own thing. I'm comparing cpptools, cmake tools, codelldb, rust analyzer, the new Swift extension, etc. Maybe I'm wrong and I'm getting confused but well maybe it's confusing.

**Comment by michelleangela** [comment]
This feature is now available to try in version 1.9.0 Insiders. 

To enable feature, set `C_Cpp.debugShortcut` to `true`.
