### ISSUE TITLE
CMAKE_CUDA_FLAGS causes problem on kernel parameter

### ISSUE THREAD

**Issue by benchislett** [microsoft/vscode-cpptools#7498]
Bug type: Language Service

**Describe the bug**
- OS and Version: Arch linux 5.11.13-arch1-1
- VS Code Version: 1.57.0-insider
- C/C++ Extension Version: v1.3.1
- Other extensions: CMake and CMake Tools. Issue disappears without them

When `CMAKE_CUDA_FLAGS` is set in my CMakeLists.txt configuration, I get a strange squiggly error on lines with kernel calls (red line under the first item after `<<<`), and highlighting is disabled for that line.

**Steps to reproduce**
1. Create a cuda project using cmake
2. Set some cuda flags in the cmakelists.txt config using `CMAKE_CUDA_FLAGS`
3. Configure the project using CMakeTools

Here's a [link to a gist of an MWE](https://gist.github.com/benchislett/fa82d90cfbf09f49b25fefa0ca4fbe95)

**Expected behavior**
I was hoping C/C++ highlighting for CUDA would be compatible with CMake and CMakeTools, as I need both for my project.

**Code sample and logs**
- Configurations in `c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${default}"
            ],
            "defines": [],
            "compilerPath": "/opt/cuda/bin/nvcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 5/9/2021, 5:34:54 PM
Version: 1.3.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${default}"
    ],
    "defines": [],
    "compilerPath": "/opt/cuda/bin/nvcc",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${default}",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/opt/cuda/include",
        "/home/benchislett/tmp"
    ],
    "standard": "c++14",
    "compilerPath": "/usr/bin/g++",
    "compilerArgs": [
        "-Wall",
        "-ffast-math",
        "-g",
        "--generate-code=arch=compute_60,code=[compute_60,sm_60]",
        "-std=c++14"
    ]
}
Custom configurations:
[ /home/benchislett/tmp/mwe.cu ]
{
    "defines": [],
    "standard": "c++14",
    "includePath": [
        "/opt/cuda/include"
    ],
    "compilerPath": "/opt/cuda/bin/nvcc",
    "compilerArgs": [
        "-Wall",
        "-ffast-math",
        "-g",
        "--generate-code=arch=compute_60,code=[compute_60,sm_60]",
        "-std=c++14"
    ]
}
Translation Unit Mappings:
[ /home/benchislett/tmp/mwe.cu ]:
    /home/benchislett/tmp/mwe.cu
Translation Unit Configurations:
[ /home/benchislett/tmp/mwe.cu ]:
    Process ID: 26045
    Memory Usage: 15 MB
    Includes:
        /opt/cuda/targets/x86_64-linux/include
        /usr/include/c++/10.2.0
        /usr/include/c++/10.2.0/x86_64-pc-linux-gnu
        /usr/local/include
        /usr/lib/clang/11.1.0/include
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=100000
        --cuda
Total Memory Usage: 15 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 63480
```
- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
```
Querying compiler for default C++ language standard using command line: "/usr/bin/g++" -x c++ -E -dM /dev/null
Detected language standard version: gnu++14
Querying compiler for default C language standard using command line: "/usr/bin/g++" -x c -E -dM /dev/null
Detected language standard version: gnu17
Querying compiler's default target using command line: "/usr/bin/g++" -dumpmachine
Compiler returned default target value: x86_64-pc-linux-gnu

Failed to query compiler. Falling back to 32-bit intelliSenseMode.
Failed to query compiler. Falling back to no bitness.
g++: error: unrecognized command-line option ‘--generate-code=arch=compute_60,code=[compute_60,sm_60]’

Unable to find host compile command in output of nvcc.
Failed to query compiler. Falling back to 32-bit intelliSenseMode.
Failed to query compiler. Falling back to no bitness.
gcc: error: unrecognized command-line option ‘--generate-code=arch=compute_60,code=[compute_60,sm_60]’
```

**Screenshots**

![image](https://user-images.githubusercontent.com/31750416/117587758-6d27e180-b0ed-11eb-9afb-01177fc04bbe.png)

![image](https://user-images.githubusercontent.com/31750416/117587777-816bde80-b0ed-11eb-8db7-63c269ea8dee.png)

**Comment by Colengms** [comment]
Hi @benchislett .  The C/C++ Extension parses a temporary file generated by nvcc, to find the command line used to invoke the host compiler.  In your case, I'm seeing the following error:

>Unable to find host compile command in output of nvcc.

Could you try invoking an nvcc command line generated by your project with the addition of `-keep -v`?  That should cause a file ending in `.ii.res` to be generated and not deleted.  Could you post that file here?

**Comment by benchislett** [comment]
Thanks @Colengms for the advice but I'm pretty sure the issue is on my end. After some tweaking, I realized that `-Wall` is not a valid `nvcc` argument. Passing a bad argument is probably what stopped that temporary file from being generated, hence the issue. 

Feel free to close :)
