### ISSUE TITLE
Too slow autocomplete on remote Ubuntu

### ISSUE THREAD

**Issue by Mactarvish** [microsoft/vscode-cpptools#7503]
Bug type: Language Service

**Describe the bug**
- OS and Version: MacOS
- VS Code Version:1.56.0
- C/C++ Extension Version :v0.65.4
- Other extensions you installed (and if the issue persists after disabling them): SSH-extension
- If using SSH remote, specify OS of remote machine:Ubuntu 18.04
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I'm using remote-SSH and C++ extension to code on my remote Ubuntu server, but the intelligence auto-complete is too slow to use:
![image](https://user-images.githubusercontent.com/13399458/117695086-76e73d00-b1f2-11eb-9270-086cf08feeaa.png)

This "loading..." will keep for about 5 seconds and then it will show the optional chioces.

By the way, another remote server works well, so if there's any options about network configurations that may confluent this extension, please hint me. Thanks in advance.

- Configurations in `c_cpp_properties.json`
- {
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-clang-x64"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
Do you have any sample repro project we could try and compare performance against what you're seeing?

**Comment by Mactarvish** [comment]
![image](https://user-images.githubusercontent.com/13399458/117774850-7a1f0f00-b26c-11eb-8c7e-a9c1b4248bd7.png)

This is my screenshot on htop. There're too much process about cpp-tools, but when I typed something need auto-complete, only two of them will raise to about 10%, is it normal?

**Comment by sean-mcmanus** [comment]
Also, using top instead of htop presents a simpler view, i.e. it will only show CPU/memory for 1 cpptools/cpptools-srv processes instead of all the threads.

**Comment by Mactarvish** [comment]
I've found C_Cpp.intelliSenseCacheSize in defaultSettings.json, but it's read-only so I cannot edit it, how to change it to writable?

**Comment by sean-mcmanus** [comment]
You should be able to change the remote/workspace/folder setting (not the user setting if you're remote).

**Comment by Mactarvish** [comment]
![image](https://user-images.githubusercontent.com/13399458/117919467-9fb92080-b31f-11eb-87fc-c091e02d7ee7.png)

That's what I did, but it seems not work...

**Comment by sean-mcmanus** [comment]
Then the issue is not caused by the IntelliSense cache, i.e. we may need perf logs or some sort of repro.

It also might help to see if you can find a case that isn't slow, i.e. for a TU that has no `#include`s, i.e. to determine what factor is the cause. You could also try setting C_Cpp.intelliSenseEngine to "Tag Parser" to switch to the faster, but less accurate (not type checked) completion, but that's it's not recommended.

**Comment by TaylorDale** [comment]
I'm encountering the same issue on virtually the same setup. Remote Ubuntu 18.04, AARM64, making the whole setup very unusable. Even with Tag Parser it's very slow, and also very inaccurate, very strange/old suggestions.
