### ISSUE TITLE
GDB exits with code 127 when running c++ console app debugger from within container running on a remote host.

### ISSUE THREAD

**Issue by aleksasp** [microsoft/vscode-cpptools#7515]
Trying to debug c++ console app from within container running on a remote host. Remote host is accessed via ssh. Same problem, terminal output:
```bash
&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"
&"Cannot create process: Operation not permitted\n"
```
Debug console output:
```
=thread-group-added,id="i1"
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
=cmd-param-changed,param="args",value="HIDDEN_PARAMS"
ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". During startup program exited with code 127.
The program 'HIDDEN_EXECUTABLE_PATH' has exited with code 0 (0x00000000).
```

Setting following values did not help.
`/home/USERNAME/.config/Code/User/settings.json`
```json
    "terminal.integrated.defaultProfile.linux": "bash",
    "terminal.integrated.automationShell.linux": "bash",
```

It doesn't matter if executing using `launch.json` or via cmake toolbar.

### Environment:
Remotely hosted container image: **Centos 7**
Remote host OS: **Centos 7**
Host OS: **Ubuntu 18.04**
VSCode version: **1.56.1**
Project type: **CMake**

_Originally posted by @aleksasp in https://github.com/microsoft/vscode-cpptools/issues/121#issuecomment-839682476_

**Comment by WardenGnaw** [comment]
Attaching to a process in Linux requires additional permissions. 

For docker containers you need an additional capability, `--cap-add=SYS_PTRACE`. For SSH, you have set the `ptrace_scope` to `0`.

Reference: https://github.com/Microsoft/MIEngine/wiki/Troubleshoot-attaching-to-processes-using-GDB

**Comment by aleksasp** [comment]
Worked like a charm, thanks @WardenGnaw .

**Comment by CS50etudiant** [comment]
> Attaching to a process in Linux requires additional permissions.
> 
> For docker containers you need an additional capability, `--cap-add=SYS_PTRACE`. For SSH, you have set the `ptrace_scope` to `0`.
> 
> Reference: https://github.com/Microsoft/MIEngine/wiki/Troubleshoot-attaching-to-processes-using-GDB

how do I run this command? on terminal? when I do "docker run --cap-add=SYS_PTRACE" on the terminal it says "docker run" requires at least 1 argument.
