### ISSUE TITLE
IntelliSense process crash detected.

### ISSUE THREAD

**Issue by srinivasst** [microsoft/vscode-cpptools#7518]
Issue Type: <b>Bug</b>

I am using VS Code for C++ development with WSL Remote Development. Intellisense works fine until I include libraries from arrow project. 

Example: as soon as I add #include <gandiva/filter.h>

I get: IntelliSense process crash detected.

Extension version: 1.3.1
VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (1.82GB free)|
|Process Argv|--crash-reporter-id d7ebde15-3794-44e4-b053-6c0b7a5c0b58|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|12.32GB (9.00GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vspre833cf:30267465
vsdfh931:30280409
vshan820:30294714
vscus158cf:30286554

```

</details>

**Comment by sean-mcmanus** [comment]
Is that library available somewhere?

If not, can you open the file the `#include <gandiva/filter.h>` commented out, attach a debugger to the cpptools-srv, then uncomment the include to get a crash call stack? (see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv for more info).

**Comment by lf-shaw** [comment]
I have the same issue. (I am also using VS Code for C++ development with WSL Remote Development.)
It's ok a few days ago. But now the IntelliSense is not working (The environment is similar with srinivasst's). 
But I test it with a ssh-remote project and it's ok. 
I guess this problem is related with WSL and Arrow.

Arrow is an open source project. you can find it [here](https://arrow.apache.org/install/).

A very simple code sample:
```C++
#include <iostream>
#include <vector>
#include "arrow/api.h"

int main()
{
    std::vector<int> vec = {1, 2};
    vec.s;     // here: no member function to select
    return 0;
}
```

But if comment `#include "arrow/api.h"` and reset IntelliSense  database, it will work as expected.

**Comment by lf-shaw** [comment]
![intellisense_problem](https://user-images.githubusercontent.com/16026142/118240933-214eb100-b4ce-11eb-82a1-f7589a928b5f.jpg)

In this code snippet, `depths` is a vector,  but the intellisense shows many wrong candidates.  (It does not know the type of `depths`?)

If i hover mouse over `depths`, no information will display.

It is weird ...

**Comment by sean-mcmanus** [comment]
@lf-shaw Your screenshot can occur when the IntelliSense process crashes and it falls back to the tag parser. The C/C++ logging should show some crashed error message.

When you add an include, the translation unit can become "non-simple" (i.e. possibly >100k lines). I'll see if I can repro the crash...

**Comment by sean-mcmanus** [comment]
I reproed the crash with 1.4.0-insiders. It was already fixed with our pending 1.4.0-insiders2:

![image](https://user-images.githubusercontent.com/19859882/118326397-c9a64a80-b4b9-11eb-97d1-7615a5cf4050.png)

**Comment by srinivasst** [comment]
One of the threads paused on exception when uncommenting the library.
Here is the stack trace.
```
add_symbol_to_overload_list(a_symbol*, a_symbol*, int, a_namespace*) (Unknown Source:0)
enter_overloaded_symbol(unsigned char, a_symbol_locator*, int, a_symbol*, a_symbol**) (Unknown Source:0)
decl_member_function(a_symbol_locator*, a_func_info_block*, a_class_def_state*, a_member_decl_info*, int) (Unknown Source:0)
class_member_declaration(a_class_def_state*, a_tmpl_decl_state*, an_ms_attribute*, int, a_template_param*, int*, a_type**, a_template_instance*, a_template*, a_decl_pos_block*) (Unknown Source:0)
scan_class_definition(a_type*, a_decl_parse_state*, int, int, int, int, int, int, a_template*, a_decl_pos_block*) (Unknown Source:0)
template_declaration(a_tmpl_decl_state*) (Unknown Source:0)
template_or_specialization_declaration_full(a_tmpl_decl_state*, int, a_decl_parse_state*) (Unknown Source:0)
template_or_specialization_declaration(a_token_kind*, int, a_source_position*, int, a_decl_parse_state*) (Unknown Source:0)
template_directive_or_declaration(a_token_kind*, int, a_source_position*) (Unknown Source:0)
scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) (Unknown Source:0)
namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) (Unknown Source:0)
scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) (Unknown Source:0)
namespace_declaration(a_token_kind*, int, int, a_source_position*, a_symbol**) (Unknown Source:0)
scan_nonmember_declaration(a_decl_parse_state*, a_source_range*) (Unknown Source:0)
translation_unit() (Unknown Source:0)
process_translation_unit(char const*, int, an_exported_template_file*) (Unknown Source:0)
cfe_main(int, char**) (Unknown Source:0)
cfe_main_exception_handler(int, char**) (Unknown Source:0)
edg_main(int, char**) (Unknown Source:0)
edge_compiler_main(int, char const**) (Unknown Source:0)
preparse(int, char const**, a_scout_store*, edge::translation_unit*) (Unknown Source:0)
a_compiler_thread::compiler_thread_routine(a_compiler_thread*) (Unknown Source:0)
execute_native_thread_routine (Unknown Source:0)
libpthread.so.0!start_thread(void * arg) (\build\glibc-S9d2JN\glibc-2.27\nptl\pthread_create.c:463)
libc.so.6!clone() (\build\glibc-S9d2JN\glibc-2.27\sysdeps\unix\sysv\linux\x86_64\clone.S:95)
```

**Comment by srinivasst** [comment]
@sean-mcmanus 
The second time I tried the experiment got the following stack trace
```
sqlite3Select (Unknown Source:0)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
```

**Comment by lf-shaw** [comment]
@sean-mcmanus 
Great! Thanks!

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders2

**Comment by lf-shaw** [comment]
thanks again.
