### ISSUE TITLE
Enable warnings for unused variables

### ISSUE THREAD

**Issue by ellizonn** [microsoft/vscode-cpptools#7522]
Type: Feature Request

Hello everybody.
I think that it would be a great feature to get warnings for unused variables and unused imports, especially for large projects.
Thanks for listening to me.

**Comment by sean-mcmanus** [comment]
We're tracking the "warning" feature with https://github.com/microsoft/vscode-cpptools/issues/828 . If we ever add the warnings feature we can follow up on this specific case to see if it's fixed or not.
