### ISSUE TITLE
Edit Configurations (UI) is randomly blank

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7523]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows (local) and optionally Linux (remote)
- VS Code Version: today's Insiders
- C/C++ Extension Version: 1.4.0-insiders
- Other extensions you installed (and if the issue persists after disabling them):

1. Use C/C++: Edit Configurations (UI).

Bug: The UI will randomly be blank (everything except for IntelliSense mode and cStandard/cppStandard, i.e. the enums, which instead of being blank have incorrect values). The repro probability seems to increase when the workspace is remote. It seems like this could be a VS Code bug, but I'm not sure since I don't have a repro without our UI yet. Repro probability may also increase when invoked through the walkthrough (not sure).

![image](https://user-images.githubusercontent.com/19859882/118310426-72957b00-b4a3-11eb-814a-727471394590.png)

**Comment by heartacker** [comment]
still repro. using 1.4.0-insider2

**Comment by sean-mcmanus** [comment]
@heartacker Do you have more repro details? Is the blank UI random for you? Are you using remote? Our fix was to delay the load by 500ms -- can you tell if increasing that delay would fix that issue for you? See https://github.com/microsoft/vscode-cpptools/pull/7524 , i.e. via either modifying the shipped javascript or debugging the TypeScript?

**Comment by heartacker** [comment]
1. always，not random
2. not using remote
3. after 20s, it works

**Comment by sean-mcmanus** [comment]
@heartacker That sounds like a different issue. What do you mean by "after 20s, it works"? Do you mean it's blank for 20 seconds and then after waiting it suddenly populates or are some actions required to get it to populate after 20 seconds?

**Comment by sean-mcmanus** [comment]
@heartacker It's a regression with VS Code 1.56 (it doesn't repro with 1.55 or earlier). I've filed a bug at https://github.com/microsoft/vscode/issues/125546 . It's possible we may be able to add a workaround (not sure yet). Certain conditions such as changing to a Chinese language pack appear to increase the repro probability.
