### ISSUE TITLE
Intellisense incorrect squiggles

### ISSUE THREAD

**Issue by creinarz** [microsoft/vscode-cpptools#7532]
Bug type: Language Service

**Describe the bug**
- OS and Version: macOS Catalina, Version 10.15.7
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.4.0-insiders
- Other installed extensions:  CMAKE 0.0.17, CMAKE Tools 1.7.3
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I am using CMAKE to cross compile a project with the GNU ARM Embedded Toolchain 9-2020-q2-update version 9.3.1 20200408 (release) on macOS. Possibly after an update (really don't remember exactly when) I started getting error squiggles on constants #defined in some files. For example, LED_RED in the screenshot below. The program compiles fine though.

<img width="1388" alt="Screen Shot 2021-05-16 at 14 49 32" src="https://user-images.githubusercontent.com/64421910/118408952-0018cc80-b656-11eb-91c0-1f5c6165dd2d.png">

I am building three targets: gateway in app.c, sensor_push in sensor_push.c and sensor_pull in sensor_pull.c. Right after opening the workspace the constants #defined in "platform.h" appear with squiggles in all three files. After compiling squiggles disappear only in app.c but not in the other two.  See LED_GREEN ins the next screenshot.

<img width="1388" alt="Screen Shot 2021-05-16 at 15 04 46" src="https://user-images.githubusercontent.com/64421910/118409389-2e97a700-b658-11eb-9912-a5d2736ac304.png">

- Configurations in `c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/usr/local/bin/arm-none-eabi-gcc",
            "cStandard": "gnu99",
            "intelliSenseMode": "macos-gcc-arm",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

- Settings in `settings.json`
```
{
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
    "cmake.configureArgs": [
        "-DPLATFORM=FMLR_72_X_STL0Z",
        "-DAPP_GATEWAY=y",
        "-DAPP_SENSOR_PUSH=y",
        "-DAPP_SENSOR_PULL=y",
        "-DAPP_SENSOR_ACTION=n"
    ],
    "C_Cpp.autoAddFileAssociations": false,
    "files.associations": {
        "*.c": "c",
        "*.h": "c",
        "*.json": "jsonc"
    },
    "cortex-debug.armToolchainPrefix": "arm-none-eabi"
}

```
- Logs

Since the project is large (well over 1000 files) and posting all diagnostic information here would make this a very long message I am attaching a text file with the logs.
(https://github.com/microsoft/vscode-cpptools/files/6490235/logs.txt)

I have tried many configuration options, deleting build files, rescan workspace, resetting intellisense database, modifyinging CMake files, etc. but nothing works. A minor inconvenience perhaps but it's driving me crazy. 

Thanks in advance for your help.
Christof

**Comment by sean-mcmanus** [comment]
We have a bug that can cause macros to get undefined: https://github.com/microsoft/vscode-cpptools/issues/7270 . A fix should be available in our pending 1.4.0-insiders2 (might be released later today).

**Comment by sean-mcmanus** [comment]
This may be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders2 . Can you try it and let us know?

**Comment by creinarz** [comment]
Yes, squiggles are gone! Great work!
