### ISSUE TITLE
Can I use shell and gdb together in the VSCode?

### ISSUE THREAD

**Issue by AdamPengG** [microsoft/vscode-cpptools#7533]
I have a shell script which sets up various environment variables for debugging.
Is it possible to set up the environment used for debugging (in launch.json) from this shell script, rather than explicitly setting variables with the "environment" key?

**Comment by WardenGnaw** [comment]
In your launch.json, you can point to your script via `miDebuggerPath`, but the very last line if your script should be a call to gdb that takes in all the parameters passed to the script.
