### ISSUE TITLE
Consider using dynamic configurations to make starting debugging easier

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-cpptools#7535]
Hi VS Code dev here 👋 

VS Code supports dynamic debug configurations to make it easier for users to start debugging without having a launch configuration.
Currently this is supported by js-debug and by [mock-debug](https://github.com/microsoft/vscode-mock-debug/blob/main/src/activateMockDebug.ts#L65) for example.
The idea is that these dynamic configurations can be computed on the fly by the debug extension and thus the user would not need to create his or her own configuration in launch.json

Here are some docs about this https://code.visualstudio.com/api/extension-guides/debugger-extension#using-a-debugconfigurationprovider

It would be great if C++ could also provide dynamic configurations (if it already does not) to make starting debugging easier for users.

fyi @weinand @jureid

**Comment by WardenGnaw** [comment]
Hi @isidorn!

I believe we already support the dynamic configuration provider.

https://github.com/microsoft/vscode-cpptools/blob/e5cdfac6b7c01606d8dcb9f004806a245968c05a/Extension/src/Debugger/extension.ts#L42

https://github.com/microsoft/vscode-cpptools/blob/e5cdfac6b7c01606d8dcb9f004806a245968c05a/Extension/src/Debugger/extension.ts#L45

**Comment by isidorn** [comment]
@WardenGnaw if that is the case then ideally the welcome view could be simplified.
I have only created this issue because I was in the meeting with @jureid and she presented a debug welcome view which was talking about configurations.
Ideally a new user that is using a welcome view should just be able to press F5 and things would just work.

Is some input from the user still needed? How does this flow look today?

**Comment by weinand** [comment]
Yes, dynamic launch configs are one way to make it easier for users to start debugging without having a launch configuration.
But they still require that the user selects a launch config and then runs it.

Another option is to implement the extension's `resolveDebugConfiguration` method in a way that detects the absence of a launch configuration and either generates a launch config on the fly from data found in the project folder, or by asking the user some questions with a wizard like UI. With this a approach a single "F5" is sufficient to start debugging (if no launch.json exists).

What approach to use, requires answering Isi's questions from above,

**Comment by jureid** [comment]
> @WardenGnaw if that is the case then ideally the welcome view could be simplified.
> I have only created this issue because I was in the meeting with @jureid and she presented a debug welcome view which was talking about configurations.
> Ideally a new user that is using a welcome view should just be able to press F5 and things would just work.
> 
> Is some input from the user still needed? How does this flow look today?

After our sync yesterday, I tested this out and found that F5 does work for a simple helloworld program. I'm confused why in all of our public docs we recommend creating the debug configuration first and then pressing F5, rather than leading with pressing F5 and then mentioning the option to customize the debug configuration further if desired. My plan is to test a few other scenarios (like if the program includes common libraries) to make sure F5 does mostly work. If so, I'll update the Welcome view and our public docs.

**Comment by WardenGnaw** [comment]
The simple F5 scenario is blocked by the `QuickPickConfigurationProvider`. 

The additional layer is used to determine which compiler they want to use. I believe we want F5 to be similar to just `C_Cpp.BuildAndDebugActiveFile` but remove selecting the compiler and debug configuration, just default to a specific compiler per OS and select the launch.json (depending on compiler type: `cppvsdbg` for windows `cl.exe` and `cppdbg` for the rest).

See 
https://github.com/microsoft/vscode-cpptools/blob/9e592073dddc12f4bbdfb10e7360ef9fc08b9723/Extension/src/Debugger/configurationProvider.ts#L72

**Comment by sean-mcmanus** [comment]
@WardenGnaw What? Build and debug active file also prompts for a compiler. We have never had a scenario in which a compiler isn't prompted. Is the prompt breaking something?

**Comment by WardenGnaw** [comment]
I believe the idea is to have 0 prompts, the customer should be able to just F5 to build and debug.

**Comment by WardenGnaw** [comment]
@jureid You will want to discuss with @sean-mcmanus and folks with how to potentially remove that `showQuickPick` call if you want to simplify the debugging process. 

If we know the user is going through the simple F5 process, we can default with local launch config:
```
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
```

**Comment by sean-mcmanus** [comment]
I think the dropdown that shows the list of known compilers is important/valuable to the user to make sure the correct compiler is being selected (e.g. mingw versus cl.exe makes a big difference). Otherwise, if we auto-choose and choose incorrectly, then it's more work later on to find the path to the compiler they actually want.

I think Julia may have been discussing removing the 1st dropdown for the (GDB/LLDB) versus (Windows) options?

**Comment by WardenGnaw** [comment]
Discussed offline. Debugger does support dynamic configurations. 

Thanks for the help!
