### ISSUE TITLE
Support .clang-format-ignore file

### ISSUE THREAD

**Issue by austriancoder** [microsoft/vscode-cpptools#7543]
Type: Feature Request

It would be really nice if .clang-format-ignore file would be taken into account. I often work in on projects where there is already a .clang-format-ignore file (which tells clang-format to not touch 3rd party sources).

The end goal is to enable "editor.formatOnSave": true.

**Comment by sean-mcmanus** [comment]
Since clang-format itself already processes .clang-format files, I would expect support for .clang-format-ignore to also come form clang-format itself (i.e. we wouldn't have to do anything special).

Any idea who owns/created the .clang-format-ignore file/concept and/or what other tools support that? I didn't find any info in my search.

**Comment by davidmatson** [comment]
It looks like this may be a concept from Mozilla, implemented by the scripts in their build system.

From https://firefox-source-docs.mozilla.org/code-quality/lint/linters/clang-format.html:
```
While excludes: will work, this linter will read the ignore list from .clang-format-ignore file at the root directory. This because it is also used by the ./mach clang-format -p command.
```
(if I'm reading that explanation correctly)

I was looking for the same support today and would love to see VS Code add it. We have a large tree with some third-party or auto-generated files, and being able just to run a Format Document extension on the whole thing would be great.

**Comment by davidmatson** [comment]
Yeah, see the build script here:
https://searchfox.org/mozilla-central/source/tools/lint/clang-format/__init__.py#97

**Comment by davidmatson** [comment]
The comment above says this request is being closed due to insufficient upvotes and would be reconsidered when enough upvotes are received, but it doesn't say how to submit an upvote. How are upvotes submitted/totaled?

**Comment by bobbrow** [comment]
Click on the 👍 in the first comment to vote.

**Comment by alexeismith** [comment]
Hi, please can you have a look at this?
clang-format-ignore had strong support in the LLVM repo and was merged in December 2023:
https://github.com/llvm/llvm-project/issues/52975

**Comment by bobbrow** [comment]
@sean-mcmanus do we need to do anything for this besides check if the version of `clang-format` we bundle with the extension is new enough to have the support?  I wouldn't expect the tool users to have to own parsing through this ignore file since it should "just work" on the command line.

**Comment by sean-mcmanus** [comment]
@bobbrow I would think we wouldn't need to do anything. The support for .clang-format-ignore is from clang-format itself. I'm just going to close this issue.
