### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by barikinil** [microsoft/vscode-cpptools#7545]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.3.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`d:\Users\Cuneyt.000\AppData\Local\Temp\ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-
[ms-vscode.cpptools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cpptools/files/6501656/ms-vscode.cpptools-unresponsive.cpuprofile.txt)
[austin.code-gnu-global-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cpptools/files/6501660/austin.code-gnu-global-unresponsive.cpuprofile.txt)

high-cpu-load

**Comment by michelleangela** [comment]
@barikinil 
Could you provide performance analysis logs by following the instructions at https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load?

Also, are there specific repro steps and sample code we could use to reproduce the issue?

**Comment by bobbrow** [comment]
no cpu profile attached.  Closing.
