### ISSUE TITLE
C/C++ Intellisense extension features (code completion, lint, etc. ) not working

### ISSUE THREAD

**Issue by ishfaqahmed29** [microsoft/vscode-cpptools#7547]
Hi, I need some help with fixing my IntelliSense extension for C/C++ 
I think this might have something to do with IntelliSense not being able to read the header files to parse the code
It had been working fine then suddenly it broke when I tried to build and run some programs yesterday ( I might have done something to the json files unknowingly)
![Capture-1](https://user-images.githubusercontent.com/34355989/118681125-59573c00-b7cd-11eb-907e-b8951b8fcf60.PNG)
![Capture-2](https://user-images.githubusercontent.com/34355989/118681143-5bb99600-b7cd-11eb-8dee-4b69d8b42c8d.PNG)

When I initially set up VS Code and mingw, I followed the instructions on the website (https://code.visualstudio.com/docs/cpp/config-mingw) to download and use IntelliSense, and it had been working without any issues

I deleted VS Code, IntelliSense, Visual Studio 2019 Community edition and also Windows SDK, reinstalled them, no change. I even reset my Windows.. still no avail

I feel very lost, PLEASE ANY HELP WOULD BE APPRECIATED THANK YOU!
![Capture-3](https://user-images.githubusercontent.com/34355989/118682577-953ed100-b7ce-11eb-8219-92d44d7f9b2f.PNG)
![Capture-4](https://user-images.githubusercontent.com/34355989/118682586-966ffe00-b7ce-11eb-9944-16251e048272.PNG)
![Capture-5](https://user-images.githubusercontent.com/34355989/118683054-0aaaa180-b7cf-11eb-9113-7f0950434a7e.PNG)

**Comment by ishfaqahmed29** [comment]
![Capture-6](https://user-images.githubusercontent.com/34355989/118683458-6aa14800-b7cf-11eb-9210-af91f5897e36.PNG)
This is the current state (no code completion or definitions)

**Comment by Colengms** [comment]
Hi @ishfaqahmed29 

Could you enable the following setting?

```
"C_Cpp.loggingLevel": "Debug",
```

This will enable debug logging to the C/C++ Output channel.  Could you then repro the issue, and post the output of the C/C++ output channel here?  That might tell us more about what is occuring.

Also, after repro'ing the issue, could you run the `C/C++: Log Diagnostics` command, and include that output?  That should tell us how/if the file has been configured for IntelliSense.

**Comment by michelleangela** [comment]
@ishfaqahmed29 

>I think this might have something to do with IntelliSense not being able to read the header files to parse the code
It had been working fine then suddenly it broke when I tried to build and run some programs yesterday ( I might have done something to the json files unknowingly)

To clarify, the c_cpp_properties.json is used to configure IntelliSense, while tasks,json and launch.json files are used for building and running the program. Any changes to the properties in c_cpp_properties.json file (which can also be viewed/edited via the IntelliSense UI configuration as shown in your screenshots) could affect IntelliSense features (code completion, etc).

**Comment by ishfaqahmed29** [comment]
@Colengms  @michelleangela Hi thank you for taking the time to help me out 

UPDATE: IntelliSense seems to be working again. I followed on from what Michelle said "Any changes to the properties in c_cpp_properties.json file could affect IntelliSense features (code completion, etc)." and reset it to the default settings 
![update](https://user-images.githubusercontent.com/34355989/118724823-1a40df00-b7fd-11eb-8256-32e00e7b5c63.PNG)

@Colengms here are the diagnostic and output files you asked for -
![diagnostics](https://user-images.githubusercontent.com/34355989/118725316-cb477980-b7fd-11eb-8687-8b9751a50646.PNG)
![debug](https://user-images.githubusercontent.com/34355989/118725320-cc78a680-b7fd-11eb-8bd2-a48049855661.PNG)

Now there is one more issue. I get this error message when I try to run the program by selecting "Run Without Debugging" command. Also, the external debugger is not being displayed/executed when I try to run the program by force , so which setting should I try to fix to enable it? 
![Run_Error](https://user-images.githubusercontent.com/34355989/118725907-8cfe8a00-b7fe-11eb-8568-871f4853de81.PNG)

**Comment by michelleangela** [comment]
@ishfaqahmed29 
The preLaunchTasks named "C/C++: gcc.exe build active file" should be defined in tasks.json file. Could you copy and paste the contents of the tasks.json file to this issue?

Example of tasks.json
```

{
    "version": "2.0.0",
    "tasks": [
      {
        "type": "shell",
        "label": "C/C++: g++.exe build active file",
        "command": "C:\\mingw-w64\\mingw32\\bin\\g++.exe",
        "args": ["-g", "${file}", "-o", "${fileDirname}\\${fileBasenameNoExtension}.exe"],
        "options": {
          "cwd": "${workspaceFolder}"
        },
        "problemMatcher": ["$gcc"],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]
  }
```

To run the preLaunchTask task, go the VS Code top bar menu, select **"Terminal" > "Run Build Tasks..."**. If there are build errors, could you copy and paste the entire log from the terminal Window? The log should show the command line that is being executed to build the program.

Also, in your launch.json file, it's missing the property `preLaunchTask` which if set to a value of "C/C++: gcc.exe build active file" (or this is the name of your preLaunchTask in tasks.json). By setting `preLaunchTask`, it will first execute the task to build the program, and then it will launch the program based on the requested settings in launch.json.

**Comment by michelleangela** [comment]
For external debugger:

>Also, the external debugger is not being displayed/executed when I try to run the program by force , so which setting should I try to fix to enable it?

See documentations
Configure debugger: https://code.visualstudio.com/docs/cpp/launch-json-reference
Debugging with gdb: https://code.visualstudio.com/docs/cpp/cpp-debug#_windows-debugging-with-gdb

**Comment by ishfaqahmed29** [comment]
@michelleangela Here's the tasks.json file. Do I need to make any additions/changes in order for it to be able to build, compile and run C/C++/Python programs?

![tasks](https://user-images.githubusercontent.com/34355989/118732186-da332980-b807-11eb-8443-f8639ca9c534.PNG)

Where exactly should I include the property preLaunchTask in my launch.json file?

![launch](https://user-images.githubusercontent.com/34355989/118732597-a73d6580-b808-11eb-99f9-e28c1ea5bcd2.PNG)

I get this error message if I comment out this command "C_Cpp.loggingLevel": "Debug", 

![error](https://user-images.githubusercontent.com/34355989/118732471-6fceb900-b808-11eb-9b2f-b526a183c61d.PNG)

When I remove the comment identifier

![no_error](https://user-images.githubusercontent.com/34355989/118732723-de137b80-b808-11eb-9dd0-25c7c879c6f6.PNG)

**Comment by michelleangela** [comment]
>Here's the tasks.json file. Do I need to make any additions/changes in order for it to be able to build, compile and run C/C++/Python programs?

I see duplicate tasks in tasks.json, you can delete the second one. The first tasks is used by default for building on VS Code. In order to build for other programs via VS Code tasks, you will need to create a task for each program. For general info about tasks in VS Code, see https://code.visualstudio.com/docs/editor/tasks#_custom-tasks. For understanding VS Code tasks to build for C++ see example https://code.visualstudio.com/docs/cpp/config-wsl#_build-helloworldcpp. I suggest to go to the VS Code Python repository or documentations to look for specific building for Python using the VS Code task.

>Where exactly should I include the property preLaunchTask in my launch.json file?
It looks like the configuration named "gcc.exe - Build and debug active file" in launch.json file already has `preLaunchTask` set.
![image](https://user-images.githubusercontent.com/38734287/118735037-76ebcc00-b7f4-11eb-998a-046b04430fd5.png)

Perhaps since there are duplicate tasks in tasks.json with the same name "C/C++: gcc.exe build active file", it is causing some confusion for launch.json to find the correct tasks to execute?

>I get this error message if I comment out this command "C_Cpp.loggingLevel": "Debug",

**"C_Cpp.loggingLevel": "Debug"** is a setting to enable Language Service IntelliSense logs (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server). It is not a setting for debugging a program. It seems that when this setting is commented out in settings.json file, it may create syntax errors in json files (as suggested in the error from the screenshot) which indirectly affect other json files? You can leave the setting **"C_Cpp.loggingLevel": "Debug"** as it's only to display additional logging info from the Language Service IntelliSense and does not affect actual debugging of a program.

**Comment by ishfaqahmed29** [comment]
I added the path to "gdb" debugger in launch.json

![new_launch](https://user-images.githubusercontent.com/34355989/118742182-e629e600-b81d-11eb-915b-8455cee3eeab.PNG)

Edited tasks.json to include the path to compiler

![new_task](https://user-images.githubusercontent.com/34355989/118742265-0ce81c80-b81e-11eb-9a32-1a173184b8dc.PNG)

When I try to "Run Build Task", it builds successfully. When I click "Debugging" or "Run without Debugging", it executes the program but the command console pops up and exits almost immediately afterwards

**Comment by ishfaqahmed29** [comment]
Hey Michelle the debugger seems to be working fine, just having issues when I try to run without debugging.. I'm trying to look more up about console commands for launch or task. As I mentioned, it was working alright before I messed the settings up! Thank you for helping once again appreciate it! 
![debugger](https://user-images.githubusercontent.com/34355989/119003085-73268980-b95b-11eb-97bd-f8efbe5f65f3.PNG)

**Comment by ishfaqahmed29** [comment]
Haven't really used breakpoints before, I think the debugger is working fine? Trying to look up console command settings 

![debugger](https://user-images.githubusercontent.com/34355989/119003452-bda80600-b95b-11eb-818d-f5142bb94c7f.PNG)

**Comment by michelleangela** [comment]
I'm not familiar with this area, @WardenGnaw is there documentation for console command settings?

**Comment by sean-mcmanus** [comment]
When the debugger hits a breakpoint it's supposed to stop and not exit the program. It's working for me with mingw/gdb.

**Comment by ishfaqahmed29** [comment]
Yes the debugger is functioning correctly.. thank you!
