### ISSUE TITLE
Recursive Include Path Does Not Search Nested Folders

### ISSUE THREAD

**Issue by Mortichar** [microsoft/vscode-cpptools#7548]
Bug type: Language Service

**Describe the bug**
- OS and Version: **Windows 10 Build 19041**
- VS Code Version: **1.56.1**
- C/C++ Extension Version: **1.3.1**
- Other extensions you installed (and if the issue persists after disabling them): **Nothing that runs in the workspace. I have some python extensions and such, and yes, it persists.**
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc). **The recursive includePath search `${workspaceFolder}/**`, provided by default, seems to stop at directories that contain other directories but not non-directory files.**

**Steps to reproduce**

Create new workspace (folder) and open it in vscode (the folder).

Inside of workspace, create folder structure similar to:

![image](https://user-images.githubusercontent.com/8473466/118684352-c2d44c00-b7c7-11eb-9ed0-1dbc1355b6cb.png)

Then, `#include <FreeRTOS.h>`, which `#include`s `portable.h`, which - in turn - `#include`s `portmacro.h`.

Observe the problem:

![image](https://user-images.githubusercontent.com/8473466/118684904-3d04d080-b7c8-11eb-87a8-7d3e00a0ac9e.png)

**Expected behavior**

I expected it to find the header. It seems like perhaps the intellisense hits the "empty" GCC folder and then stops. Explicitly adding a path to ARM_CM4F works to resolve the missing header, but should not be required.

**Code sample and logs**

```
/*! 
    @file main.cpp
    @author me (me@myemail.com)
    @brief 
    @date 2021-05-18
    @copyright Copyright (c) 2021
*/

#include <FreeRTOS.h>
```

- Configurations in `c_cpp_properties.json`

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64"
        }
    ],
    "version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 5/18/2021, 11:05:27 AM
Version: 1.3.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.18362.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Development\vscodecppext_bug_test\source\main.cpp ]:
    C:\DEVELOPMENT\VSCODECPPEXT_BUG_TEST\SOURCE\MAIN.CPP
Translation Unit Configurations:
[ C:\Development\vscodecppext_bug_test\source\main.cpp ]:
    Process ID: 19252
    Memory Usage: 18 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.25.28610\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.25.28610\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.18362.0\CPPWINRT
        C:\DEVELOPMENT\VSCODECPPEXT_BUG_TEST\FREERTOS_KERNEL\INCLUDE
        C:\DEVELOPMENT\VSCODECPPEXT_BUG_TEST
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 18 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5087
```

I attached a copy of the entire workspace I used to reliably recreate the issue.

[vscodecppext_bug_test.zip](https://github.com/microsoft/vscode-cpptools/files/6502724/vscodecppext_bug_test.zip)

**Comment by sean-mcmanus** [comment]
This is "by design". Add a cpp.hint file with `#define PRIVILEGED_FUNCTION` to fix it. The macro breaks our tag parser, which in terms breaks our ability to locate the `#include` for recursive include generation.

![image](https://user-images.githubusercontent.com/19859882/118869841-bbca3e00-b89a-11eb-9bf4-e077da22e1f0.png)

**Comment by Mortichar** [comment]
How is this "by design"? Is this behavior documented somewhere as expected?

The macro is `#define`d to nothing in mpu_wrappers.h, which is included at the top of portable.h, long before it gets to any uses of it. portmacro.h is included before that, even, and doesn't use any of those macros.

I guess I what I'm really asking is:

Is there any way I could have figured out that I needed to add a cpp.hint file to resolve this other than coming here and opening an issue? This seems like something that should just . . . work.

**Comment by sean-mcmanus** [comment]
It's behavior inherited from VS: https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-160 .

Maybe we could add it to some docs or FAQ? @bobbrow @jureid 

I don't think there's a way to make it "just work". A redesign suggestion would have to be requested on VS at https://developercommunity.visualstudio.com/report?space=62&entry=suggestion .

**Comment by Mortichar** [comment]
Sorry, by "just work" I meant that it did not seem like anything was incorrect about my setup and I was not getting any meaningful errors. I realize it is almost never simply "just works" in reality.

Thank you for the reference, I at least understand the problem now.
