### ISSUE TITLE
After the update intellisense is unusable on Mac

### ISSUE THREAD

**Issue by zajo** [microsoft/vscode-cpptools#755]
It fails to find pretty much anything and everything, filling the Problems tab with bogus errors.

Is there a way to disable the intellisense without disabling the c_cpp altogether? Disabling the entire extension is not desirable because then even debugging doesn't work.

**Comment by fredrikryden** [comment]
Same problem happens in ubuntu

**Comment by sean-mcmanus** [comment]
You can change C_Cpp.errorSquiggles to "Disabled".

**Comment by zajo** [comment]
This does not solve the problem as it will still flood the Problems tab with bogus errors, which makes it impossible to see actual errors from the compiler. It is necessary to add an option specifically to turn off intellisense but leave the rest of the C++ support on. This is needed as a last resort defense: C++ is very difficult to parse and to this day intellisense crashes with sufficiently complex language constructs, even in Visual Studio.

**Comment by sean-mcmanus** [comment]
The errorSquiggles setting also removes the errors from the Problems window. You can also change the IntelliSenseEngine to "Tag Parser", but that should be unnecessary unless you have problems with other IntelliSense features, such as hover.

**Comment by bobbrow** [comment]
[I wrote up a FAQ for this.](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md#why-do-i-have-red-underlines-everywhere-after-updating-to-the-latest-version)

You likely just need to update your includePath.  There are kill switches that disable the new IntelliSense if you need to go that route, but I recommend taking a minute to update your includePath so that you can take advantage of new semantic-aware features as they come in.

**Comment by zajo** [comment]
"C_Cpp.errorSquiggles to false" -> this is wrong, "false" is not a valid value. "Disabled" is, but it still doesn't work for me (on Windows). Besides the flooded Problems tab, after a while VS code says that intellisense has stopped responding (on Mac).

Please provide support for COMPLETELY disabling intellisense. As it is the only option is to disable the entire extension but then I can't debug.

**Comment by bobbrow** [comment]
The third option in the FAQ I linked to earlier is what you are looking for.

**Comment by sean-mcmanus** [comment]
@zajo The Problems tab should not be flooded when you set errorSquiggles to disabled. The IntelliSense not responding means there was a crash...maybe we should just silently fall back to the tag parser until we fix the crashing issues?

**Comment by zajo** [comment]
Updated to 0.11.2, the Problems window still gets flooded with "errors" which the compiler does not report. I haven't tried setting up the include directories for intellisense but just setting error squiggles to disabled still does not work.

Meanwhile, if anyone wants intellisense completely disabled I found a solution which works for me using cpptools-0.11.2:

~~1. In the extensions/ms-vscode.cpptools-0.11.2/bin directory (on Mac it is located under \~/.vscode), rename Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin to Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin.disabled (the corresponding file on other platforms should be easy to spot.)~~

2. In settings.json, make sure you have:
{
  "C_Cpp.intelliSenseEngine": "Tag Parser",
  "C_Cpp.errorSquiggles": "Disabled"
}

~~3. Restart vscode.~~

**Comment by bobbrow** [comment]
A note to anyone reading this issue.  Do not rename the intellisense provider binary as stated in step 1. above.  All you need to do to turn off squiggles is set C_Cpp.intelliSenseEngine to "Tag Parser".  You don't need to restart VS Code either.

[We document this here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md#why-do-i-have-red-underlines-everywhere-after-updating-to-the-latest-version)

**Comment by zajo** [comment]
@bobbrow I spoke too soon, I *still* get the Problems window flooded with bogus errors. Occasionally it gets turned off, so the errorSquiggles setting does have "some" effect but then later it resumes the squiggles and flooding the Problems with "errors".

I guess there is no way to fix this problem until Microsoft provides an option to turn it all off.

**Comment by sean-mcmanus** [comment]
If you have the Tag Parser set you should only get the "Include file not found in include path" warning (there is no way to turn off that squiggle, but it should be fixable via setting the browse.path).

**Comment by bobbrow** [comment]
Can you give us an example of the errors you're seeing?  Are you saying that what you did in your step 2 above didn't work for you?  Setting the IntelliSense engine to Tag Parser gives you the same behavior that we've published for months.  What other extensions do you have installed?

**Comment by zajo** [comment]
@sean-mcmanus "If you have the Tag Parser set you should only get the "Include file not found in include path" warning (there is no way to turn off that squiggle, but it should be fixable via setting the browse.path)." Sean, thank you so much for this note! It explains what's going on.

Can we please have an option to completely disable intellisense and _all_ "errors" it finds, even "missing" includes?

**Comment by bobbrow** [comment]
Why would you want to turn off missing include errors?  Our extension does not provide much help for you if it can't find symbols for the types you are working with.  And if you don't receive some sort of notification from the extension you will start to think it is broken when it is unable to find any symbols.

**Comment by zajo** [comment]
I do not have missing includes, my code compiles. The reason I need the extension at all is for the debugger integration, which works flawlessly. The option I am asking for is to be able to disable intellisense without disabling the entire extension, which gets rid of the debugger as well.

**Comment by bobbrow** [comment]
That makes sense.  I created a new issue to track your request.  #785
