### ISSUE TITLE
Bash error 127 after recent update

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-cpptools#7551]
Issue Type: <b>Bug</b>

Whenever i'm running a debug configuration on a remote Linux host, i get the following error:

```
The terminal process "bash ''" failed to launch (exit code: 127).
```

This started happening after today's update.

Extension version: 1.4.0-insiders2
VS Code version: Code - Insiders 1.57.0-insider (a9c5e37ea0dc020f5df3b1c82ef020627fc8cd7c, 2021-05-19T08:54:56.348Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.8.7
Remote OS version: Linux x64 5.4.0-56-generic
Remote OS version: Linux x64 5.4.0-56-generic

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30303025
vscorehov:30301224
vscod805cf:30301675

```

</details>

**Comment by gnikit** [comment]
Same issue here. Reverting to an older version of the extension (1.3.1 or 1.3.0) does not fix the problem. The issue appears to be with VS Code Insiders itself, so I suspect the issue should be migrated in the vscode repo. 

Nonetheless, a temporary fix around this is to set `"externalConsole": true` in your launch.json

**Comment by gnikit** [comment]
Same debugger issue, unrelated to the C++ extension: https://github.com/microsoft/vscode/issues/124173

**Comment by Xinyu-Wu-0000** [comment]
Issue Type: <b>Bug</b>

I got the following error too.

``The terminal process "bash ''" failed to launch (exit code: 127).``

Extension version: 1.4.0-insiders2
VS Code version: Code - Insiders 1.57.0-insider (4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5, 2021-05-21T05:13:19.775Z)
OS version: Linux x64 5.11.0-17-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.41GB (8.51GB free)|
|Process Argv|--unity-launch --crash-reporter-id 23cadddf-5002-4f61-9b06-032b924ce5a5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805:30301674

```

</details>

**Comment by payonel** [comment]
This issue is causing me to revert to non-insiders builds. I cannot properly debug my programs.
1. with msft cpptools the internal shell cannot open (as stated)
2. with external=true, I cannot change the cwd, this setting seems to be ignored
3. with webfreak.debug i cannot print '*' and flush stdout (not your problem, sure) but i'm out of options

I do hope this is fixed before this merges to mainline

**Comment by sean-mcmanus** [comment]
@WardenGnaw Any ideas about this? Looks like java debugging hit this too.
