### ISSUE TITLE
C++ taking longer time to compile and run

### ISSUE THREAD

**Issue by IamVigneshG** [microsoft/vscode-cpptools#7557]
I just installed c++ extension and updated vs code yesterday.From that cpp compilation alone taking longer time.say for python its less than 1 seconds, for same logic cpp taking 60sec.
After 4to5 times running the same code, it will complete around 1s.
![Screenshot 2021-05-20 at 3 28 18 PM](https://user-images.githubusercontent.com/43438142/118959755-3de06280-b980-11eb-9d2c-44511e18a6e7.png)
<img width="1680" alt="Screenshot 2021-05-20 at 3 31 24 PM" src="https://user-images.githubusercontent.com/43438142/118959995-76803c00-b980-11eb-847d-48ce3d68d526.png">
<img width="1680" alt="Screenshot 2021-05-20 at 3 31 57 PM" src="https://user-images.githubusercontent.com/43438142/118960092-8e57c000-b980-11eb-9f79-489e78411912.png">

Not getting any error logs.
Cant find whats wrong with the settings.
Could anyone help me on this issue?

PS: Attached properties and settings file screenshot.

**Comment by Colengms** [comment]
Hi @IamVigneshG .  The C/C++ Extension provides IntelliSense (auto-completion, hover, semantic colorization), formatting, and other features, only in the editor.  It is not involved in compiling.  Can you confirm the issue does not occur if you disable the C/C++ extension?

It's possible that the C/C++ Extension is still parsing system headers, and that could cause CPU and disk usage, which could potentially have an impact on other processes.  It would be possible to monitor the activity of the C/C++ extension by enabling:

```
"C_Cpp.loggingLevel": "Debug"
```

and looking at the output to the C/C++ Output channel (by selecting C/C++ in the popup menu associated with the Output panel).  Are you are seeing performance issues only while there is output actively occurring in the C/C++ output channel?

**Comment by IamVigneshG** [comment]
Hi @Colengms Thanks for responding.
I am getting a warning in C/C++ configuration warning.Attached the screenshot.
The performance issue I am facing was not happening always.After sometimes of working/restart its working fine.Even in the C/C++ output channel there is no suspicious logs.

<img width="1680" alt="Screenshot 2021-05-21 at 7 13 35 AM" src="https://user-images.githubusercontent.com/43438142/119070073-f5b75380-ba04-11eb-9a24-9e18a84b448a.png">

<img width="1680" alt="Screenshot 2021-05-21 at 7 13 03 AM" src="https://user-images.githubusercontent.com/43438142/119070104-0071e880-ba05-11eb-9735-26afa044fcbe.png">

**Comment by Colengms** [comment]
Hi @IamVigneshG .  It doesn't seem like the C/C++ extension would be causing an issue with compile performance, unless it's contributing to an overall slow-down of your system for some reason.  Consider keeping the "Activity Monitor" application running, and looking at which processes are consuming the most CPU time or generating disk activity, while you are seeing the performance issue.

Regarding Configuration Warnings - I noticed that you have a `c_cpp_properties.json`.  Within it, is the `intelliSenseMode` set explicitly to `macos-gcc-x64` (or `gcc-x64`), and compiler set to `/usr/bin/gcc`?  I believe by default `/usr/bin/gcc` on macOS will actually be a symbolic link to clang.  If so, the warning would seem accurate.

**Comment by IamVigneshG** [comment]
Hi @Colengms I agree that issue may not because of C/C++ extenstion.But also It wont be because of any other system's process/slowness to keep monitor through Activity Monitor ( Even for the same code sometimes its working fine within 2s) if so for other languages also I has to face this lag. Do you have any idea on what would be the issue if not because of extension? How to check for any  configuration issue/mishandled? 

And for the Configuration Warnings - Is it okay to have such warning?

**Comment by dylank** [comment]
C++ debugging broke after 1.1.3. I've found that going back to this version solves most of my issues like this.

**Comment by sean-mcmanus** [comment]
@dylank Did you post to the correct issue? This issue isn't about debugging. Can you create a new issue with more info or add to an existing one?

**Comment by Colengms** [comment]
> And for the Configuration Warnings - Is it okay to have such warning?

Hi @IamVigneshG .  Configuration Warnings should only be displayed when there is a setting you may have explicitly specified (such as `"intelliSenseMode": "gcc-x64"`, in `c_cpp_properties.json`) that was not used as specified due to a higher priority setting (such as the results of checking the specified compiler and determining it was `clang` and not `gcc`).  It doesn't indicate a problem, just that you may not be getting exactly the configuration you had specified.

> Do you have any idea on what would be the issue if not because of extension?

Maybe low memory?  Perhaps when there is not sufficient available RAM, there is a lag due to memory paging?

**Comment by IamVigneshG** [comment]
Hi @Colengms 
Seems its pretty fine with Memory and Ram right? 
<img width="729" alt="Screenshot 2021-05-25 at 6 52 12 AM" src="https://user-images.githubusercontent.com/43438142/119427359-80ab8d00-bd28-11eb-9bbd-ef9707fc0af3.png">
<img width="586" alt="Screenshot 2021-05-25 at 7 10 11 AM" src="https://user-images.githubusercontent.com/43438142/119427388-8dc87c00-bd28-11eb-893b-25b79a1c35a0.png">

**Comment by IamVigneshG** [comment]
<img width="805" alt="Screenshot 2021-05-25 at 9 11 01 AM" src="https://user-images.githubusercontent.com/43438142/119436239-6af29380-bd39-11eb-9557-49ea35ae2fbb.png">
Here's the memory monitor

**Comment by Colengms** [comment]
Hi @IamVigneshG .  I don't know what else to suggest.  If the C/C++ extension is not actively consuming processor time or excessive memory when you see the performance issue with compiling, then it would seem to be unrelated to the C/C++ extension.
