### ISSUE TITLE
Autodetect cpptools configuration by `"compileCommands"` path

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#7559]
Type: Feature Request

## Preconditions
c_cpp_properties.json contains multiple configuration object with `"compileCommands"` field. For example:
```json
{
    "configurations":
    [
        {
            "name": "qt5-desktop",
            "compileCommands": "build-qt5/compile_commands.json"
        },
        {
            "name": "qt4-arm",
            "compileCommands": "build-qt4-arm/compile_commands.json"
        }
    ],
    "version": 4
}

```

## Autodetect cpptools configuration by `"compileCommands"` path
I propose the following logic:
- Go through each configuration object in **c_cpp_properties.json** which has `"compileCommands"` and try to find (check for existence) the matching **compile_commands.json** file.
- If matching **compile_commands.json** was found - select appropriate configuration object as default for this workspace.

Current (existing) implementation always selects the last configuration object from c_cpp_properties.json despite the fact that its **compile_commands.json** doesn't exists.

**Comment by Colengms** [comment]
Hi @yhsb2k .  Could you clarify what you mean by, "always selects the last configuration object"?  Are you referring only to when used on a new machine for the first time?  Otherwise, the current configuration be (restored on launch to) the one last selected by the user.  Are you seeing the current configuration change to the last, despite selecting a different configuration?

**Comment by yhsb2k** [comment]
Hi @Colengms ,
> Are you referring only to when used on a new machine for the first time?

Yes, exactly. And after clearing vscode-cpptools\ipch folder too.

> Are you seeing the current configuration change to the last, despite selecting a different configuration?

No, it works fine. Previously selected configuration is restored for workspace.

Now I thought that fixing #7560 will be enough to solve the problem, which I describe in this issue.
