### ISSUE TITLE
Support wildcard (* regex pattern) in `"compileCommands"` file path

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#7560]
Type: Feature Request

Sometimes build folder name depends of build parameters (target platform, build type). There is no existing solution to handle it in `"compileCommands"` path. Creating multiple configuration objects isn't handy.
Having support of wildcard pattern in `"compileCommands"` will easily solve such problems.
Example:

```jsonc
{
    "configurations":
    [
        {
            "name": "myproject",
            // It will find compile_commands.json at least in one of them: build-debug or build-release folders
            "compileCommands": "build-*/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Comment by Colengms** [comment]
Hi @yhsb2k .  Thanks for suggesting this.  We'll see what we can do to better handle this scenario.
