### ISSUE TITLE
Intellisense crash with std::ranges::unique

### ISSUE THREAD

**Issue by SPAstef** [microsoft/vscode-cpptools#7576]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 19042
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.3.1
- Other extensions you installed (and if the issue persists after disabling them):  a lot, but disabling them makes no difference
- A clear and concise description of what the bug is, including information about the workspace: I'm writing C++ code on Windows, and I'm trying out the new std::ranges stuff... For some reason, `std::ranges::unique` makes Intellisense crash.

**Steps to reproduce**
1. Create a C++ file
2. Write any code which uses `std::ranges::unique`
3. Intellisense crashes

**Expected behavior**
Intellisense should not crash.

**Code sample and logs**
```
#include <algorithm>
#include <vector>

int main()
{
    std::vector<int> v(100);

    std::ranges::sort(v); // this causes no problems

    std::ranges::unique(v); // this causes problems

    return 0;
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/9153046/119220529-443f1d80-baeb-11eb-9947-538a5568b7de.png)
![image](https://user-images.githubusercontent.com/9153046/119220559-6769cd00-baeb-11eb-9736-37d223a1de11.png)

**Comment by sean-mcmanus** [comment]
This is already fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders2 . We should be releasing 1.4.0-insiders3 soon and 1.4.0 later this week.
