### ISSUE TITLE
Hide compilation errors hints

### ISSUE THREAD

**Issue by Raspredval** [microsoft/vscode-cpptools#7580]
Type: Feature Request

Please hide compilation errors hints after making changes into the code, or add some switch to hide compilation errors\warnings
In current state compilation errors hints are indistinguishable from IntelliSence errors hints. And it's rather confusing to fix code issues and still see the hint of a typo or template instantiation failure even when the issue is no longer there.
Right now the only valid way is to reopen the whole workspace to get rid of those hints without recompiling the file.
![image](https://user-images.githubusercontent.com/46839056/119367509-3997aa80-bcdc-11eb-9f4d-a07faf6f1865.png)

**Comment by sean-mcmanus** [comment]
Compilation error hints are distinguishable via the source text, which is "gcc" for compilation errors and "C/C++" for IntelliSense errors. You can stop showing the compilation errors by removing the problemMatcher property from your build task.
