### ISSUE TITLE
Code formatting doesn't work if intellisense is disabled

### ISSUE THREAD

**Issue by rjra100** [microsoft/vscode-cpptools#7584]
Issue Type: <b>Bug</b>

- In the settings, set 
    "C_Cpp.intelliSenseEngine": "Disabled",
    "C_Cpp.formatting": "Default"
- Reload the window.
- Open a .cpp file.
- Do "Format Document" from the command palette.

Actual behaviour: 
Dialog saying "There is no formatter for 'cpp' files installed."

Expected behaviour: 
File is formatted.

If I set the intellisense mode to "Tag Parser" or "Default" and reload the window, formatting works.

Extension version: 1.3.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.43GB free)|
|Process Argv|--folder-uri vscode-remote://dev-container%2B5c5c77736c245c5562756e74752d31382e30345c686f6d655c72616c6578616e64657237325c6769745c706f7274616c/workspaces/portal --crash-reporter-id 3b02320b-d5a4-4fea-91a2-32fa216b37ff|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: portal-dev|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|9.73GB (1.58GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|9.73GB (1.58GB free)|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
This is being tracked by the existing issue https://github.com/microsoft/vscode-cpptools/issues/7083 , so you can upvote that.
