### ISSUE TITLE
Insiders notification immediately after install

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-cpptools#7586]
Our team has been trying to minimize the amount of notifications that show, particularly after install or startup. This one seems particularly bad as I installed the CPP extension for the first time (or first time in a long time), and was asked if I wanted to use the insiders version:

<img width="448" alt="Screen Shot 2021-05-25 at 5 02 33 AM" src="https://user-images.githubusercontent.com/2193314/119494756-839d8200-bd16-11eb-9698-65815cd79a89.png">

cc @isidorn @devinvalenciano

**Comment by isidorn** [comment]
Yes, agree 100% here.
Another issue is that this is on startup, which we always recommend against.

**Comment by bobbrow** [comment]
We currently disable it for Codespaces as that was the case we have prioritized reducing notifications for.

**Comment by Tyriar** [comment]
Please rethink when it's presented also to non-codespaces. For example, a slightly less intrusive option would be when you open a cpp file for the first time, as opposed to on start up.

**Comment by isidorn** [comment]
Additional idea: only offer this for advanced users after some usage period. You can detect advanced users for example if they started debugging or used some refactoring...
I do not think it is a good idea to show this to a novice user as soon as he installs. Why would a novice user use insiders.

**Comment by bobbrow** [comment]
Fair enough. We can come up with a criteria that should be met before prompting.

**Comment by sean-mcmanus** [comment]
The prompt won't appear unless a C/C++ "real activation" event occurs. You may have had a c_cpp_properties.json file in your workspace folder, or you may have opened a C/C++ file, etc.

Showing the prompt after a certain number of real activations seems fine to me -- how many activations should we require?
