### ISSUE TITLE
ENOTFOUND

### ISSUE THREAD

**Issue by xzmagic** [microsoft/vscode-cpptools#759]
after update for latest version and click reload i encouter this error:
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' Failed at stage: downloadPackages
Error: getaddrinfo ENOTFOUND 123.147.165.21:9999 123.147.165.21:9999:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Finished
I don't know how to workaround

**Comment by pieandcakes** [comment]
@xzmagic it is trying to download packages from the Microsoft Download Center. Are you behind a proxy? Can you try and open the c:\users\<username>\.vscode\extensions\ms-vscode.cpptools-<version>\package.json and locate the package for C/C++ language components (windows) at the bottom of the file and try and access that link?

**Comment by xzmagic** [comment]
I'don't do anything,but now its ok!
Updating C/C++ dependencies...
Downloading package 'C/C++ language components (Windows)' (4661 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (905 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (12081 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Installing package 'ClangFormat (Windows)'
Installing package 'Visual Studio Windows Debugger'

Finishe
