### ISSUE TITLE
Intellisense showing error when variable length arrays are declared, even though the compiler supports them.

### ISSUE THREAD

**Issue by SciSaif** [microsoft/vscode-cpptools#7593]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10 Pro Version: 20H2
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.4.0
- Other extensions you installed (and if the issue persists after disabling them): C/C++ extensions pack, no
- A clear and concise description of what the bug is:
Intellisense marks Variable Length Arrays as errors, but the program runs and compiles without any errors.
Error: expression must have a constant value -- the value of variable "v" (declared at line 77) cannot be used as a constant
![image](https://user-images.githubusercontent.com/51053279/119918990-1b090c00-bf87-11eb-979c-c54f77dc7976.png)

GCC Version: 
![image](https://user-images.githubusercontent.com/51053279/119919217-95399080-bf87-11eb-8331-f42dc0247c9e.png)

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment]
This should work in general if your compilerPath and intelliSenseMode is set correctly. Can you provide a code sample and what compilerPath/intelliSenseMode is being used from running C/C++: Log Diagnostics and if it's with C or C++ and which c/cppStandard? And what does the error say?

![image](https://user-images.githubusercontent.com/19859882/119706914-6c8e8b00-be0f-11eb-9b72-e7182a2da32e.png)

**Comment by SciSaif** [comment]
> This should work in general if your compilerPath and intelliSenseMode are set correctly. Can you provide a code sample and what compilerPath/intelliSenseMode is being used from running C/C++: Log Diagnostics and if it's with C or C++ and which c/cppStandard? And what does the error say?
> 
> ![image](https://user-images.githubusercontent.com/19859882/119706914-6c8e8b00-be0f-11eb-9b72-e7182a2da32e.png)

@sean-mcmanus 
I have edited the issue with relevant information, please take a look.

**Comment by sean-mcmanus** [comment]
It should work (i.e. works for me). 
![image](https://user-images.githubusercontent.com/19859882/119921147-59b8ab00-bf22-11eb-8ef1-390201800231.png)

Make sure you set your compilerPath to something like "C:\\Program Files\\mingw-w64\\i686-8.1.0-posix-dwarf-rev0\\mingw64\\bin\\gcc.exe" (check what path exists on your machine) and set the intelliSenseMode to "windows-gcc-x86" (assuming you're targetting Windows, otherwise it'd be "linux-gcc-x86").

**Comment by SciSaif** [comment]
> It should work (i.e. works for me).
> ![image](https://user-images.githubusercontent.com/19859882/119921147-59b8ab00-bf22-11eb-8ef1-390201800231.png)
> 
> Make sure you set your compilerPath to something like "C:\Program Files\mingw-w64\i686-8.1.0-posix-dwarf-rev0\mingw64\bin\gcc.exe" (check what path exists on your machine) and set the intelliSenseMode to "windows-gcc-x86" (assuming you're targetting Windows, otherwise it'd be "linux-gcc-x86").
> 
> Otherwise, can you check our C/C++: Log Diagnostics output?

@sean-mcmanus 
That fixed it, all I had to do was set the intelliSenseMode to "windows-gcc-x86"
I was stuck on this for 5 months, thanks a lot!
