### ISSUE TITLE
show/hide "case" of switch

### ISSUE THREAD

**Issue by ErikDaVinci** [microsoft/vscode-cpptools#7596]
![Unbenannt](https://user-images.githubusercontent.com/31970750/119667152-4d572400-be36-11eb-8303-addef49fe4d0.PNG)

Hello,
in VSCode I can hide some code, if I click on the arrow pointing down.
This works for a lot of commands (like the "if" in the picture) - but not for a "case" of a switch.
Maybe there is a reason, but I would like it, if it would be possible to hide "case" commands too.

Sorry for not knowing the right technical terms - I hope you still get what I mean.

Best regards,
Erik

**Comment by sean-mcmanus** [comment]
`case` doesn't form a scope. You can can get outlining with `case` via enclosing the block in `{}`. I've filed a feature request on VS (for our shared code) at https://developercommunity.visualstudio.com/t/CC-switch-case-outlining/1433324

**Comment by ErikDaVinci** [comment]
Thank you very much!
