### ISSUE TITLE
IntelliSense finds usages outside of the current workspace

### ISSUE THREAD

**Issue by leosh64** [microsoft/vscode-cpptools#7599]
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.3.1
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

IntelliSense tends to find usages/definitions of functions/symbols outside of the current workspace in a second copy of the workspace. This is highly irritating since one doesn't know if the found symbol is really in the current codebase, and needs to double-check the path manually every time.

**Steps to reproduce**

1. Have a large C++ project workspace (let's call it `ddad`)
2. Create a copy of that workspace (e.g. to work on two different branches at the same time, let's call it `second_ddad`)
3. Open VSCode with the C++ extension installed in one of the workspaces
4. Use IntelliSense to show the definition of a symbol, e.g. CTRL+Click on a function name
5. IntelliSense will show both definitions of the function (see attached screenshot)

In the screenshot below, both the file in the  *current workspace* as well as in the second workspace (here called `second_ddad`) are found:

![intellisense_outside_workspace](https://user-images.githubusercontent.com/4062160/119754202-b7bda200-bed2-11eb-8810-c21ac3ae9258.png)

**Expected behavior**
Only the file in the current workspace should be found

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`: Unmodified default, with 
```
            "includePath": [
                "${workspaceFolder}/**"
            ],
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette:
Diagnostics shows some duplicates to be found:
```
Using: /home/user/ddad/third_party/somepath/somefile.hpp
    Alternative: "/home/user/second_ddad/third_party/somepath/"
```

**Additional context**

This project workspace is using `bazel`, which creates various symlinks within the workspace (e.g. `bazel-out -> /home/user/.cache/bazel/_bazel_q474974/8d1c200e573b8da3ee18c97f4656aca6/execroot/ddad/bazel-out`). Could IntelliSense be following these symlinks and somehow end up including files in the second workspace?

**Comment by sean-mcmanus** [comment]
Yes, the symlinks are probably being followed. You can add the symlinks or the targets to the C_Cpp.files.exclude setting to stop those from being used. Let me know if you're still having issues after trying that.

**Comment by leosh64** [comment]
Hmm, that doesn't seem to help. I added the following to `settings.json` and killed the `cpptools` process:
```
    "C_Cpp.files.exclude": {
        "/home/user/second_ddad/**": true,
        "**/.vscode": true,
        "bazel-*/**": true
    }
```
The files in `second_ddad` are still found. After excluding the `bazel-*` symlinks, I'd expect nothing in the `.cache` folders to be found anymore, but IntelliSense still finds lots of files in there, as shown in the screenshot below:

![intellisense_cache](https://user-images.githubusercontent.com/4062160/119757074-01a88700-bed7-11eb-9755-399f3f94f411.png)

Is there an IntelliSense-cache that I need to clean?

**Comment by sean-mcmanus** [comment]
Support for "/**" in files.exclude is only available in https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0-insiders3 , i.e. it's a bug we fixed...you could also remove the "/**" to just exclude the folder (which affects the files too).
