### ISSUE TITLE
ESP32 device incorrectly auto-detected as ESP8266

### ISSUE THREAD

**Issue by gojimmypi** [microsoft/vscode-cpptools#760]
When plugging in an ESP32_Core_Board_V2, VSCode incorrectly identifies the board as an Adafruit HUZZAH ESP8266,

```
[Main Instruction]
Visual Studio Code
[Content]
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:20:36.315Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

perhaps this issue is more for VSCode-arduino - but I could not find here on GitHub?

**Comment by sean-mcmanus** [comment]
It looks like the Micorosft Arduino extension team is using https://gitter.im/Microsoft/vscode-arduino . Can you try asking there?
