### ISSUE TITLE
Passing an input file to C++ debugger throws "no such file or directory"

### ISSUE THREAD

**Issue by davidjuhyung** [microsoft/vscode-cpptools#7600]
Bug type: Debugger

**Describe the bug**
- OS and Version: macOS Big Sur Version 11.2.3
- VS Code Version: 1.56.2
- C/C++ Extension Version:  1.4.0-insiders3
- A clear and concise description of what the bug is: When running the debugger, the build is done successfully. But when the debugger starts (and reads the input file), it throws an error "no such file or directory: `pathToInputFile`".

**To Reproduce**
My code:
![image](https://user-images.githubusercontent.com/38872151/119766599-50c4cc80-be83-11eb-9f44-228af7d98927.png)
My `launch.json`:
![image](https://user-images.githubusercontent.com/38872151/119766640-633f0600-be83-11eb-8bfc-a3d27b3a9aeb.png)
My `tasks.json`:
![image](https://user-images.githubusercontent.com/38872151/119766732-8cf82d00-be83-11eb-9dcc-04750275c8e2.png)
My code structure:
![image](https://user-images.githubusercontent.com/38872151/119766784-a4cfb100-be83-11eb-941f-1cd8cc930f79.png)

To reproduce, press `F5` and you should see the following
![image](https://user-images.githubusercontent.com/38872151/119766828-b7e28100-be83-11eb-9935-26463df00230.png)
After that, a terminal should pop up, and it should show the following
![image](https://user-images.githubusercontent.com/38872151/119766894-d6e11300-be83-11eb-9f60-6cec0d812de2.png)

Please enlighten this poor little boy.

**Comment by WardenGnaw** [comment]
`<` is a redirection that a shell interprets. 

Using `"args": ["<"]` means that the string "<" will be passed to your program as an argument. 

If you want to read from a file, pass in the name of the file as a parameter and use methods to read the file by name. e.g. `fopen`.

**Comment by davidjuhyung** [comment]
> `<` is a redirection that a shell interprets.
> 
> Using `"args": ["<"]` means that the string "<" will be passed to your program as an argument.
> 

So by your response, is it fair to assume that input redirection is impossible in vscode debugger? That's a shame.

**Comment by eeegnu** [comment]
> `<` is a redirection that a shell interprets.
> 
> Using `"args": ["<"]` means that the string "<" will be passed to your program as an argument.
> 
> If you want to read from a file, pass in the name of the file as a parameter and use methods to read the file by name. e.g. `fopen`.

For anyone that has this problem, note that this is false. I had this problem, but managed to get it to work. My launch.json looks like this right now.

```
{
    "version": "0.2.0",
    "configurations": [{
            "name": "Run with file input",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "args": ["<","${workspaceFolder}/input.txt"],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "externalTerminal",
	    "preLaunchTask": "C/C++: g++.exe build active file",
	    "windows":{
			"MIMode": "gdb",
			"miDebuggerPath": "gdb.exe"
		}
        }]
}
```

I scoured dozens of pages on related issues, and while I'm still not exactly sure what caused it, my fix was to install g++/gdb from scratch using the instructions here https://code.visualstudio.com/docs/languages/cpp#_example-install-mingwx64. After that I had to swap out the absolute path I used for `C_Cpp.default.compilerPath` with just `g++.exe` after adding `C:\msys64\mingw64\bin` as a system environmental variable (it does not work at all with an absolute path.) 

I don't know if lldb has different issues, but I found in many sources this workaround that seems to work for others: https://github.com/microsoft/vscode-cpptools/issues/1219#issuecomment-581735277
