### ISSUE TITLE
ERROR: Exception while processing MIEngine operation. An item with the same key has already been added.

### ISSUE THREAD

**Issue by tjohnsonhvac** [microsoft/vscode-cpptools#7602]
Hello, our team is getting an intermittent issue where when adding a break point while debugging, we get an MIEngine error that causes gdb to crash.

We are debugging a remote linux device, so we are connected to a gdb  server. 

GDB Version:  GNU gdb (Linaro_GDB-2016.11) 7.12.0.20161122-git
GDB Server Version: 7.12
Compiler: linaro 6.2
VSCode: 1.56
CPP Tools: v1.4.0-insiders3

Launch Configuration:
[launch.txt](https://github.com/microsoft/vscode-cpptools/files/6553414/launch.txt)

Debug Output:
[gdb_crash_log.txt](https://github.com/microsoft/vscode-cpptools/files/6553406/gdb_crash_log.txt)

Unfortunately the top was chopped off, hopefully it contains enough info.

This is the error with logging turned off:
```
Thread 1 "pic6_app" received signal SIGINT, Interrupt.
0xb6bd7364 in __libc_do_syscall () from target:/lib/libpthread.so.0
run_gdb_server: pwr monitor loop t_error = 9468145
ERROR: Exception while processing MIEngine operation. An item with the same key has already been added. If the problem continues restart debugging.
[New Thread 21716.21716]
/home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/snapshots/binutils-gdb.git~gdb-7.12-branch/gdb/thread.c:89: internal-error: thread_info* inferior_thread(): Assertion `tp' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) [answered Y; input not from terminal]
/home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/snapshots/binutils-gdb.git~gdb-7.12-branch/gdb/thread.c:89: internal-error: thread_info* inferior_thread(): Assertion `tp' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB? (y or n) [answered Y; input not from terminal]
ERROR: GDB exited unexpectedly with exit code 3 (0x3). Debugging will now abort.
The program 'C:\Users\cbs0426\Workspaces\WaterCooledScrew\build\bin\WCS' has exited with code -1 (0xffffffff).
```

**Comment by WardenGnaw** [comment]
From the logs, it looks like GDB is internally failing.

> \"/home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/snapshots/binutils-gdb.git~gdb-7.12-branch/gdb/thread.c:89: internal-error: thread_info* inferior_thread(): Assertion `tp' failed.
A problem internal to GDB has been detected, further debugging may prove unreliable.
Quit this debugging session?

I found a relevant bug from 2017 their forms, I would reach out to them and provide additional details that got you to this scenario. 
https://sourceware.org/bugzilla/show_bug.cgi?id=21405

**Comment by tjohnsonhvac** [comment]
@WardenGnaw Thank you for looking into this. I will see of I can use a newer version of GDB to resolve the issue.
