### ISSUE TITLE
identifier "__packed" is undefined

### ISSUE THREAD

**Issue by Jackie-Yang** [microsoft/vscode-cpptools#761]
<img width="359" alt="1" src="https://cloud.githubusercontent.com/assets/18381153/26367796/6549f5e2-4022-11e7-9ace-9eb1fcea57aa.png">

**Comment by Jackie-Yang** [comment]
__packed is a memory alignment type～

**Comment by sean-mcmanus** [comment]
__packed is a keyword specific to the armcc compiler, so our tool isn't configured to recognize it yet. You may be able to work around this via adding this to your defines in c_cpp_properties.json: `"__packed="`

**Comment by Jackie-Yang** [comment]
@sean-mcmanus Thanks~

**Comment by bobbrow** [comment]
Marking as feature request for ARM IntelliSense mode.

**Comment by bobbrow** [comment]
tracking ARM IntelliSense mode feature with #661
