### ISSUE TITLE
Updates to compile_commands.json are not handled if specified using a relative path

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#7610]
If I specify `compileCommands` like so:
`"compileCommands": "build/compile_commands.json"`

.. it seems to work as expected, however changes to the file are not (always?) handled properly.

If I specify it like so:
`"compileCommands":"${workspaceFolder}/build/compile_commands.json"`

.. it appears to work as expected, including when changes are made.

It looks like we're resolving this path to within the workspace directory in some cases, but not in others.  If the current working directory is different, the file is looked for there.  This should either default to always resolving as relative to the workspace folder if not a full path (after variables like `${workspaceFolder}` are expanded).  Or, it should result in a squiggle in `c_cpp_properties.json`.

We had added some additional checking for changes to compile_commands.json, to address user reports that changes were not always being handled properly.  This is likely the actual cause, and that additional handling could potentially be removed.

**Comment by michelleangela** [comment]
When the file path property `compileCommands` in the `c_cpp_properties.json` file (IntelliSense configuration) is set with a relative path, extension does not resolve path to the correct absolute path.

Examples of relative path cases for a workspace folder under path `Home/projects/myFolder` or the value of `${workspaceFolder}` is `Home/projects/myFolder` .


**Example path value:** `"${workspaceFolder}/build/compile_commands.json"` 
**Should resolve to:**  `"Home/projects/myFolder/build/compile_commands.json"` 

**Example path value:** ` "some_subfolder/compile_commands.json"`
**Should resolve to:**  `"Home/projects/myFolder/some_subfolder/compile_commands.json"` 

**Example path value:**` "compile_commands.json"`
**Should resolve to:**  `"Home/projects/myFolder/compile_commands.json"`
