### ISSUE TITLE
Can't connect to my remote machine

### ISSUE THREAD

**Issue by TarcioV** [microsoft/vscode-cpptools#7613]
**Describe the bug**
- OS and Version: Windows 10 x64
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.4.0
- Other extensions you installed (and if the issue persists after disabling them): Remote SSH version 0.65.4

I'm not able to connect to my remote machine with cpptools v1.4.0, but I do with version 1.3.1.

it says `c:\windows\sysnative\openssh\ssh.exe` not found.

I also has remote ssh version 0.65.4.

aditional information:
where ssh
`C:\Windows\System32\OpenSSH\ssh.exe`

launch.json
`"pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "C:\\Windows\\System32\\OpenSSH\\ssh.exe",
                "pipeArgs": [
                    "user@mymachine"
                ],
                "debuggerPath": "/usr/bin/gdb"
            }`

**Comment by sean-mcmanus** [comment]
@WardenGnaw Is this a debugger regression?

**Comment by WardenGnaw** [comment]
Doesn't look like this code path has changed. 

The VS Code version that is being used is 32-bit and the terminal is trying to convert System32 to sysnative so we can get the 64-bit folder.

You can verify if the terminal being spawned is 32-bit or 64-bit by creating a simple `task.json` that run `echo %PROCESSOR_ARCHITECTURE%`

E.g.
```
{
            "type": "shell",
            "label": "Echo",
            "command": "echo",
            "args": [
                "%PROCESSOR_ARCHITECTURE%"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
```

See https://github.com/microsoft/vscode-cpptools/blob/d9551d2dcc21226ce4545c6d78c182ed13d9194b/Extension/src/Debugger/utils.ts#L29
