### ISSUE TITLE
[Bug] The compilation error hint mismatch

### ISSUE THREAD

**Issue by were** [microsoft/vscode-cpptools#7615]
**Describe the bug**
- OS and Version: Windows WSL2 Ubuntu 4.19.128-microsoft-standard Ubuntu
- VS Code Version: 1.56.2 054a9295330880ed74ceaedda236253b4f39a33[5
- C/C++ Extension Version: 1.4.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
As you can see in the figure below: the color highlight mismatch, and the error hint of the corresponding line also mismatch.

![image](https://user-images.githubusercontent.com/2356965/119927599-8f639100-bf2e-11eb-98c2-55fd8578b316.png)

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Comment by sean-mcmanus** [comment]
Are you able to provide more repro info? Like a code sample and your configuration info from C/C++: Log Diagnostics?

Is this a regression compared to 1.3.1?

**Comment by were** [comment]
> Are you able to provide more repro info? Like a code sample and your configuration info from C/C++: Log Diagnostics?
> 
> Is this a regression compared to 1.3.1?

I am not sure how to have a minimized example to reproduce this. I am developing a very large and niche project.

I looked at Log Diagnostics, it gets the include path from `compile_commands.json` as expected.

The weird thing is that the frontend does not refresh as the translation unit is edited. I can only force the refresh by reloading the whole vscode.

I want to know, if there is somewhere else I can look at the logs to see what happens and gather more information for you?

**Comment by sean-mcmanus** [comment]
It sounds like the IntelliSense process may be crashing. Do you see any crash message in the C/C++ logging?

If you compile the translation unit with the -E flag, you may be able to locate an error from one the headers which could cause some cascading failures.

**Comment by were** [comment]
@sean-mcmanus Sorry for my late response. Besides `> C/C++: Log Diag`, where can I see more logs?

**Comment by sean-mcmanus** [comment]
https://code.visualstudio.com/docs/cpp/enable-logging-cpp
