### ISSUE TITLE
Error in downloading C++ exstension for visual studio code

### ISSUE THREAD

**Issue by DipakTech** [microsoft/vscode-cpptools#7619]
Issue Type: <b>Bug</b>

always shows up  downloading c/c++ language components(windows).is there is any option for disabling this pop up 

Extension version: 1.4.0
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (6.51GB free)|
|Process Argv|--crash-reporter-id 641be7cf-0eb2-4ef5-9cb7-e17b1ede7eff|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by aldenshoup** [comment]
I am also having the same problem. It fails to download automatically and it also fails when I try to install the win32 version with VSIX

**Comment by sean-mcmanus** [comment]
Can you try uninstalling the extension, restarting VS Code, and then reinstalling it?

Using the offline vsix also doesn't work? https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0

**Comment by aldenshoup** [comment]
> Can you try uninstalling the extension, restarting VS Code, and then reinstalling it?
> 
> Using the offline vsix also doesn't work? https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.0

I have done both of these things as well as uninstalled and reinstalled VS Code (before I realized it was an extension problem). VSIX fails with the error "Extensions: Install from VSIX...' resulted in an error (Corrupt ZIP: end of central directory record signature not found)" even though I downloaded the Win32 from the same link above today.

**Comment by aldenshoup** [comment]
> Hmm, it works for me. Is the vsix 28,712,496 bytes in size?
> 
> That error appears to be coming from VS Code. It's possible it could be some VS Code bug.

The VSIX is 9,597,312,422 bytes for some reason.

**Comment by aldenshoup** [comment]
> > Hmm, it works for me. Is the vsix 28,712,496 bytes in size?
> > That error appears to be coming from VS Code. It's possible it could be some VS Code bug.
> 
> The VSIX is 9,597,312,422 bytes for some reason. I'm downloading cpptools-win32.vsix

Did a fresh download, it's now 2,628,499 bytes

**Comment by sean-mcmanus** [comment]
The vsix needs to be 28,712,496 bytes or around 28 MB. Something may be causing your download to be interrupted before it can be completed.

![image](https://user-images.githubusercontent.com/19859882/120029818-73ea9b80-bfab-11eb-879d-aade1ecf9608.png)

**Comment by aldenshoup** [comment]
> The vsix needs to be 28,712,496 bytes or around 28 MB. Something may be causing your download to be interrupted before it can be completed.
> 
> ![image](https://user-images.githubusercontent.com/19859882/120029818-73ea9b80-bfab-11eb-879d-aade1ecf9608.png)

I tried with Firefox and got this.
![image](https://user-images.githubusercontent.com/84984089/120041485-51ba4300-bfd6-11eb-9237-860fa6d58b18.png)

**Comment by sean-mcmanus** [comment]
Can you try right-clicking the link and selecting some Save As option?

**Comment by aldenshoup** [comment]
> Can you try right-clicking the link and selecting some Save As option?

It ended up being a problem with our company's firewall, I was able to get IT to download it and give it to me. 
Thanks
