### ISSUE TITLE
Language Server crashing after installing

### ISSUE THREAD

**Issue by AnikNath114911** [microsoft/vscode-cpptools#7623]
Bug type: Language Service
- OS and Version: Windows 7 SP 1
- VS Code Version: 1.56.2
- C/C++ Extension Version: v1.4.0
- Other extensions you installed (and if the issue persists after disabling them): No extensions installed
- If using SSH remote, specify OS of remote machine: No SSH
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
When I try to install the C/C++ extension, it shows me a log that "Connection to server got closed. Server will not be restarted."

**Comment by sean-mcmanus** [comment]
It's possible our binary doesn't work on Windows 7 (that OS isn't really supported and we don't test with it). Upgrading to Windows 10 is highly recommended.

Does downgrading the C/C++ extension to 1.3.1 fix the issue (i.e. is it a regression)?

**Comment by AnikNath114911** [comment]
Oh sorry pls close this issue this is a duplicate one

**Comment by AnikNath114911** [comment]
Because I got the answer already
