### ISSUE TITLE
case keyword without space followed by character literal breaks syntax highlighting

### ISSUE THREAD

**Issue by MrExquisite** [microsoft/vscode-cpptools#7631]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.19043
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.4.0
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

When a keyword like `case` is immediately followed by a character literal, syntax highlighting gets broken.

**Steps to reproduce**
1. Open a new file
2. Click on Select Language Mode
3. Select C++
4. Insert the code sample provided below.
5. Observe syntax highlighting

**Expected behavior**

Syntax highlighting should work correctly, like when a space is positioned between `case` and the string literal.

**Code sample and logs**

- Code sample
```cpp
switch(i)
{
  case'g':break;
  case'H':break;
  case'\0':break;
  case'\'':break;
  case'\\':break;
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
[logs_syntax_highlight_bug.txt](https://github.com/microsoft/vscode-cpptools/files/6567478/logs_syntax_highlight_bug.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/83462034/120133921-5006a000-c1cd-11eb-8bb5-e550b8a2a6b5.png)

**Comment by sean-mcmanus** [comment]
This is not our bug, i.e. repros with our extension disabled. Can you file a bug at https://github.com/jeff-hykin/cpp-textmate-grammar/issues ? That is the repro for the C/C++ lexical colorization that is used by VS Code.

**Comment by MrExquisite** [comment]
Thank you and SFTI, moved to [here](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/552#issue-909783639).
