### ISSUE TITLE
Range based For Loops not supported

### ISSUE THREAD

**Issue by shantanu0323** [microsoft/vscode-cpptools#7632]
Bug type: Debugger

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by michelleangela** [comment]
@shantanu0323 
Could you provide code sample to clarify the issue? 

Also, could you provide the follow info for:

- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
