### ISSUE TITLE
Debugger may cause system errors when command initiative is left in the console

### ISSUE THREAD

**Issue by vincedani** [microsoft/vscode-cpptools#7633]
Bug type: Debugger

Hi there!

I would like to debug a C++ application, so a new console is created as `cppdbg: name...`.
The problem is, if I write a command initiative into that console, then start the debugger, it fails.

Like
```
$ ^C  /usr/bin/env /bin/sh /tmp/Microsoft-MIEngine-Cmd-2bopttgv.y62
bash: :s^C  /usr/bin/env /bin/sh /tmp/Microsoft-MIEngine-Cmd-2bopttgv.y62 : substitution failed
```
A bigger problem there if e.g. a remove command initiative is there:

```
$ rm -rf ./build /usr/bin/env /bin/sh /tmp/Microsoft-MIEngine-Cmd-2bopttgv.y62
rm: cannot remove '/usr/bin/env': Permission denied
rm: cannot remove '/bin/sh': Permission denied
```
If somebody started the IDE with root privileges, then this would cause an uncomfortable surprise.

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.15.2 (user setup)
- C/C++ Extension Version: 1.4.0

**Comment by WardenGnaw** [comment]
Can you clarify what you mean by ` if I write a command initiative into that console`?

The output you are seeing is how the debugger is able to add the program output to the integrated terminal.

**Comment by vincedani** [comment]
# Steps to reproduce 

1. Open a C/C++ project and run and finish debug. A new console is opened as `3: cppdbg: ...` and after the debugging session this console is usable. 

```bash
[1] + Done "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-tweqswsb.2ss" 1>"/tmp/Microsoft-MIEngine-Out-w7s7bewy.4vb"
user@host:path/to/project$
```

2. Write a random command to the console, _but not hit enter_. The terminal should look like this:

```bash
user@host:path/to/project$ rm -rf build
```

3. Press F5 to start a new debugging session. The session fails to start with the following error messsage:

```bash
rm -rf build  /usr/bin/env /bin/sh /tmp/Microsoft-MIEngine-Cmd-cemwf1kv.yjv 
rm: cannot remove '/usr/bin/env': Permission denied
rm: cannot remove '/bin/sh': Permission denied
```

The debugger placed  `/usr/bin/env /bin/sh /tmp/Microsoft-MIEngine-Cmd-cemwf1kv.yjv `  to the terminal and tried to start the whole thing that was there: `rm -rf build  /usr/bin/env /bin/sh /tmp/Microsoft-MIEngine-Cmd-cemwf1kv.yjv `.

**Comment by WardenGnaw** [comment]
This is due to VS Code not clearing the terminal before starting a new debug session.

They recently added a new feature in the March 2021 release to clear it if you enable it in preferences.
https://github.com/microsoft/vscode/issues/116699

To enable this option, go to File -> Preferences -> Settings
Search for `clearBeforeReusing`

![image](https://user-images.githubusercontent.com/3953714/120696719-b7d51900-c461-11eb-9d5d-3b77cd834e48.png)
