### ISSUE TITLE
Edit Configuration (UI) is sometimes blank with VS Code 1.56

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#7641]
Bug type: General

**Describe the bug**
版本: 1.56.2 (system setup)
提交: 054a9295330880ed74ceaedda236253b4f39a335
日期: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.14393

- C/C++ Extension Version: 1.4.0

**To Reproduce**
*Please include code sample and `task.json` files.*
![CPP_TOOL](https://user-images.githubusercontent.com/1876302/120573279-e2b67180-c44f-11eb-9def-cd89b3fee575.gif)

**Comment by sean-mcmanus** [comment]
I'm seeing it fail to populate randomly. If you give focus to a different file and then to the settings UI does it repopulate?

**Comment by heartacker** [comment]
> I'm seeing it fail to populate randomly. If you give focus to a different file and then to the settings UI does it repopulate?

yes, it repopulate after refocusing

**Comment by sean-mcmanus** [comment]
The issue seems like a VS Code bug...I thought I had worked around it by adding a delay, but there may be other factors that increase the probability of hitting it. I'll see if I can find another fix or I maybe I'll file a VS Code bug.

**Comment by sean-mcmanus** [comment]
As mentioned in the other issue: It's a regression with VS Code 1.56 (it doesn't repro with 1.55 or earlier). I've filed a bug at microsoft/vscode#125546 . It's possible we may be able to add a workaround (not sure yet). Certain conditions such as changing to a Chinese language pack appear to increase the repro probability.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.4.1 . Note however, that VS Code 1.56 has a network-related performance regression that can cause the initial loading to take 8 or more seconds, but the UI will eventually populate when the loading is done (see https://github.com/microsoft/vscode/issues/125546).
