### ISSUE TITLE
Unable to load c_cpp_properties.schema.json in v1.4.0

### ISSUE THREAD

**Issue by yellowweak** [microsoft/vscode-cpptools#7642]
Bug type: General

**Describe the bug**
- OS and Version: win10
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.4.0
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Compile Run (seems doesn't matter)

**Description**
At the first line in `.vscode/c_cpp_properties.json`, it pops up a warning saying
`Unable to load schema from 'cpptools-schema:///c_cpp_properties.schema.json': cannot open cpptools-schema:/c_cpp_properties.schema.json. Detail: Unable to resolve resource cpptools-schema:/c_cpp_properties.schema.json.(768)`

And this causes some of syntax highlight not working and suggestion window doesn't show up.
![0535](https://user-images.githubusercontent.com/10696321/120614172-e79c1500-c491-11eb-93a5-098f6ec4ffab.png)
![0536](https://user-images.githubusercontent.com/10696321/120614196-f08ce680-c491-11eb-9319-1eaffe396e7f.png)

Even if I renamed the json file to `c_cpp_properties.schema.json`, the issue persists, including missing syntax highlight, suggestion window, error detecting, etc...
![0533](https://user-images.githubusercontent.com/10696321/120614978-c556c700-c492-11eb-85e0-b13ca28d35a2.png)

I noticed that it works perfectly with `.vscode/c_cpp_properties.json` if I downgrade extension to 1.3.1
![0537](https://user-images.githubusercontent.com/10696321/120614219-f84c8b00-c491-11eb-8783-05e2ca5dc1e9.png)

I'm not sure whether it is a bug or there are just some mistakes in settings.
How could I deal with this?

**Comment by Colengms** [comment]
Hi @b00902076 .  The failure to load `c_cpp_properties.schema.json` would result in lack of edit features in `c_cpp_properties.json`, such as help text on hover.  It would have no impact on other features of the extension.

It's possible 1.4.0 failed to installed properly.  Could you try deleting the installed extension folder (usually in `%USERPROFILE%\.vscode\extensions`), and reinstalling the extension?  It's necessary to delete the installed folder, as it gets reused if uninstall and reinstall are done via the UI, or when switching between versions via the UI.

If that does not resolve the issue, could you enable logging with `"C_Cpp.loggingLevel": "Debug",`, and provide the output of your C/C++ output channel?

**Comment by b00902076** [comment]
Hi @Colengms , I tried your solution and the issue fixed!!!
Really thank for your kind and rapid reply 👍
