### ISSUE TITLE
Intellisense is trying to open the same cpp file but with a relative path version on compilation error

### ISSUE THREAD

**Issue by iomeanslife** [microsoft/vscode-cpptools#7643]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 Pro
- VS Code Version: 1.56.2
- C/C++ Extension Version: v 1.4.0
- Other extensions you installed (and if the issue persists after disabling them): C#;Rust;

**To Reproduce**
This is very similar to the issue #4062 .

I have compilation errors in my file `win32_handmade.cpp`, but two of the problems listed are supposedly at `\..\code\win32_handmade.cpp` if the file doesn't exist, I can even create it and reopen it whenever I select the error, even if the file itself is empty. take note of the weird **root** style address that doesn't make sense.

After a while I also get an unrecognized token error on the first characters of the actual file.

**Expected behavior**
All problems should refer to the original and find them there.

**Code sample and logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/628820/120713740-3c538600-c4ba-11eb-9363-f249e5adf4de.png)

**Comment by sean-mcmanus** [comment]
I believe the relative paths are created by VS Code's msbuild problem matcher. You can modify that to use a
