### ISSUE TITLE
Class methods list parsing issue

### ISSUE THREAD

**Issue by MKras** [microsoft/vscode-cpptools#7646]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.4.0
Sometimes with some cpp files OUTLINE sub-item displays 'Loading document symbols for <FileName>'. Forever.
At the same time I get 
```
[exthost] [error] Canceled: Canceled
	at FoldingRangeProvider.<anonymous> (......\.vscode\extensions\ms-vscode.cpptools-1.4.0\dist\main.js:35700:23)
	at Generator.next (<anonymous>)
	at fulfilled (........\.vscode\extensions\ms-vscode.cpptools-1.4.0\dist\main.js:35674:58)
	at runMicrotasks (<anonymous>)
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
```
The mentioned line number leads to the throw:
```
    provideFoldingRanges(document, context, token) {
        return __awaiter(this, void 0, void 0, function* () {
            const id = ++client_1.DefaultClient.abortRequestId;
            const params = {
                id: id,
                uri: document.uri.toString()
            };
            yield this.client.awaitUntilLanguageClientReady();
            token.onCancellationRequested(e => this.client.abortRequest(id));
            const ranges = yield this.client.languageClient.sendRequest(client_1.GetFoldingRangesRequest, params);
            if (ranges.canceled) {
                throw new vscode.CancellationError();
            }
```

```
exports.GetFoldingRangesRequest = new vscode_languageclient_1.RequestType('cpptools/getFoldingRanges');
```

Is It a bug or should/can I increase the FoldingRanges any where?

**Comment by sean-mcmanus** [comment]
Yeah, I've seen that before. It could be a bug. Not sure what a repro is yet.

**Comment by Colengms** [comment]
The error message being logged seems to be a VS Code issue.  This scenario occurs due to cancellation, which can be due to a new request invalidating a previous request.  The switch to CancellationError was intended to suppress logging of an error message.

**Comment by Colengms** [comment]
When https://github.com/microsoft/vscode/issues/125799 is addressed, the error message should cease to be logged.  However, that error message would be unrelated to problems populating the outline view.

@MKras Can you provide additional information about the issue you are seeing?

**Comment by sean-mcmanus** [comment]
@Colengms This is fixed, right?

**Comment by Colengms** [comment]
@sean-mcmanus My understand is that the issue the useris reporting here is:

> Sometimes with some cpp files OUTLINE sub-item displays 'Loading document symbols for '. Forever.".  

The folding ranges issue that was noticed in the log is unrelated.  It would not cause outline to stop working.

**Comment by sean-mcmanus** [comment]
Okay, I skipped over that line. Loading document symbols forever could be different things, but I haven't seen that recently. Is cpptools using CPU? If so, can you attach a debugger to get a call stack? There could be some issue creating the database. You could try running the C/C++: Reset IntelliSense Database command or change the C_Cpp.default.browse.databaseFilename setting to "${workspaceFolder}/.vscode/vc.db" to verify that its' being created correctly. Does it only repro with certain files and not a simple file with a single variable?
