### ISSUE TITLE
Massive performance regression / document edits not registered by language service

### ISSUE THREAD

**Issue by ruabmbua** [microsoft/vscode-cpptools#7654]
Bug type: Language Service

**Describe the bug**
- OS and Version: Debian 10.9
- VS Code Version: 1.56.2
- C/C++ Extension Version: v1.4.0
- Other extensions you installed (and if the issue persists after disabling them): all other extensions disabled

Essentially all features of the extension have become unusable:
1) Syntax highlighting stops to update shortly after initial workspace scan / index
2) Syntax error squiggles are added, but then never removed.
3) Syntax error squiggle position does not make any sense.
4) autocomplete information not up-to-date (i.e. new locals never show up)

This happens on medium to large scale projects. I never had any issues this extreme with these projects before.

**Steps to reproduce**

1) Check out the Linux kernel, and open with editor.
2) Try to edit some simple function (introduce syntax error)
3) Remove the syntax error
4) The error squiggles are still there, syntax highlighting was never updated

**Expected behavior**

Syntax highlighting should keep working, syntax errors should be removed, after gone.

**Code sample and logs**

- Use a mid-sized to large sized C / C++ project. Essentially all projects I tried have this regression (including the Linux kernel)

- Configurations in `c_cpp_properties.json`
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/include/"
            ],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14"
        }
    ],
    "version": 4
}
```
There is nothing significant in any of the logs. The LSP log shows the usual stuff, when saving the file etc...

**Additional context**

**Comment by sean-mcmanus** [comment]
What version of the C/C++ extension did it work for you?

Using "${workspaceFolder}/**" with the Linux kernel is likely to cause issues because of name conflicts with system headers -- using a configurationProvider set to "ms-vscode.makefile-tools" may give better results. Another alternative is to use non-recursive paths and manually list the ones you need.

Do you see crash messages in the C/C++ output pane? What do you see when you run the C/C++: Log Diagnostics command after opening the file?

**Comment by ruabmbua** [comment]
A thanks, I did not notice the `${workspaceFolder}/**` at all. Will try without that. About the last working version: I tried to go back as far as 6 months of releases, it seems like the problem is persistent everywhere.

Maybe something else changed. Will try to get some of the requested logs as soon as I can.

**Comment by ruabmbua** [comment]
When I reopen the file, all errors are gone, until I edit something again. Seems like it is just not refreshing visible information, while editing / saving the file. Only reopening files / workspace helps for a very short time.

Here is a log, when reopening the file (note: not the Linux kernel, a proprietary project, I have to redact paths):

```
Checking for syntax errors: file:///{REDACTED}.cpp
Queueing IntelliSense update for files in translation unit of: /{REDACTED}.cpp
Error squiggle count: 1
terminating child process: 29846
Error squiggle count: 0
Update IntelliSense time (sec): 0.374
idle loop: reparsing the active document
Checking for syntax errors: file:///{REDACTED}.cpp
Queueing IntelliSense update for files in translation unit of: /{REDACTED}.cpp
Error squiggle count: 1
Error squiggle count: 0
Update IntelliSense time (sec): 0.29
idle loop: reparsing the active document
Checking for syntax errors: file:///{REDACTED}.cpp
Queueing IntelliSense update for files in translation unit of: /{REDACTED}.cpp
Error squiggle count: 1
Error squiggle count: 0
Update IntelliSense time (sec): 0.289
terminating child process: 29885
terminating child process: 29886
idle loop: reparsing the active document
Checking for syntax errors: file:///{REDACTED}.cpp
Queueing IntelliSense update for files in translation unit of: /{REDACTED}.cpp
Error squiggle count: 1
Error squiggle count: 0
Update IntelliSense time (sec): 0.285
Request canceled: 869
idle loop: reparsing the active document
Checking for syntax errors: file:///{REDACTED}/sysroots/armv7vet2hf-neon-poky-linux-gnueabi/usr/include/sys/stat.h
Queueing IntelliSense update for files in translation unit of: /{REDACTED}.cpp
Error squiggle count: 0
Update IntelliSense time (sec): 0.341
Checking for syntax errors: file:///{REDACTED}.cpp
Queueing IntelliSense update for files in translation unit of: /{REDACTED}.cpp
Error squiggle count: 1
terminating child process: 30089
Error squiggle count: 0
Update IntelliSense time (sec): 0.365
idle loop: reparsing the active document
Checking for syntax errors: file:///{REDACTED}.cpp
Queueing IntelliSense update for files in translation unit of: /{REDACTED}.cpp
Error squiggle count: 1
Error squiggle count: 0
Update IntelliSense time (sec): 0.288
```

Nothing suspicious at all, although I would expect more headers to be parsed? (e.g. why is stat.h reparsed, and not the other headers?)

Here are the diagnostics after opening the file:

```
-------- Diagnostics - 6/8/2021, 11:20:03 AM
Version: 1.4.0
Current Configuration:
{
    "name": "Muppets",
    "defines": [],
    "compilerPath": "{REDACTED}/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "compilerArgs": [
        "-march=armv7ve",
        "-mthumb",
        "-mfpu=neon",
        "-mfloat-abi=hard",
        "--sysroot={REDACTED}/sysroots/armv7vet2hf-neon-poky-linux-gnueabi"
    ],
    "intelliSenseMode": "gcc-arm",
    "includePath": [
        "{REDACTED}/030724437f753479d7997db9ed3e73b43d1a9ea4/include",
        "{REDACTED}/89ff7676fb7c905380327c16681e9f5b9db40ac3/include",
        "{REDACTED}/1d1b1afc10d1157dd1d9b7b88f9cb961ad4aab17/include",
        "{REDACTED}/42598760fdfc357c6c963839bc855b5356e0cc9b/include",
        "{REDACTED}/dfa573b5416f7344036a9c4b4e6538abfa0d4b83/include",
        "{REDACTED}/14815a52002e670817c3f35a0d525a6de21a36fb/include",
        "{REDACTED}/1dac7bcfde3c318febbb3a5a4750a77882cf848d/include",
        "{REDACTED}/14815a52002e670817c3f35a0d525a6de21a36fb/include",
        "{REDACTED}/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include",
        "{REDACTED}/1d1b1afc10d1157dd1d9b7b88f9cb961ad4aab17/include",
        "{REDACTED}/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include",
        "{REDACTED}/01fa27e4325008bc90134e7e378858dd2dfda1c7/include",
        "{REDACTED}/a0fa4fdfc4f1ffb7802b3a889e5d6182a471c191/include",
        "{REDACTED}/a0fa4fdfc4f1ffb7802b3a889e5d6182a471c191/include",
        "{REDACTED}/fcb20bc50f25a5bd770742cf734b75b64a6c7e24/include",
        "{REDACTED}/14815a52002e670817c3f35a0d525a6de21a36fb/include",
        "build/",
        "./"
    ],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "browse": {
        "path": [
            "{REDACTED}/030724437f753479d7997db9ed3e73b43d1a9ea4/include",
            "{REDACTED}/89ff7676fb7c905380327c16681e9f5b9db40ac3/include",
            "{REDACTED}/1d1b1afc10d1157dd1d9b7b88f9cb961ad4aab17/include",
            "{REDACTED}/42598760fdfc357c6c963839bc855b5356e0cc9b/include",
            "{REDACTED}/dfa573b5416f7344036a9c4b4e6538abfa0d4b83/include",
            "{REDACTED}/14815a52002e670817c3f35a0d525a6de21a36fb/include",
            "{REDACTED}/1dac7bcfde3c318febbb3a5a4750a77882cf848d/include",
            "{REDACTED}/14815a52002e670817c3f35a0d525a6de21a36fb/include",
            "{REDACTED}/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include",
            "{REDACTED}/1d1b1afc10d1157dd1d9b7b88f9cb961ad4aab17/include",
            "{REDACTED}/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include",
            "{REDACTED}/01fa27e4325008bc90134e7e378858dd2dfda1c7/include",
            "{REDACTED}/a0fa4fdfc4f1ffb7802b3a889e5d6182a471c191/include",
            "{REDACTED}/a0fa4fdfc4f1ffb7802b3a889e5d6182a471c191/include",
            "{REDACTED}/fcb20bc50f25a5bd770742cf734b75b64a6c7e24/include",
            "{REDACTED}/14815a52002e670817c3f35a0d525a6de21a36fb/include",
            "build/",
            "./",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ {REDACTED}.cpp ]:
    {REDACTED}.cpp
    {REDACTED}/sysroots/armv7vet2hf-neon-poky-linux-gnueabi/usr/include/sys/stat.h
Translation Unit Configurations:
[ {REDACTED}.cpp ]:
    Process ID: 27576
    Memory Usage: 62 MB
    Compiler Path: {REDACTED}/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++
    Includes:
        {REDACTED}/030724437f753479d7997db9ed3e73b43d1a9ea4/include
        {REDACTED}/89ff7676fb7c905380327c16681e9f5b9db40ac3/include
        {REDACTED}/1d1b1afc10d1157dd1d9b7b88f9cb961ad4aab17/include
        {REDACTED}/42598760fdfc357c6c963839bc855b5356e0cc9b/include
        {REDACTED}/dfa573b5416f7344036a9c4b4e6538abfa0d4b83/include
        {REDACTED}/14815a52002e670817c3f35a0d525a6de21a36fb/include
        {REDACTED}/1dac7bcfde3c318febbb3a5a4750a77882cf848d/include
        {REDACTED}/14815a52002e670817c3f35a0d525a6de21a36fb/include
        {REDACTED}/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
        {REDACTED}/1d1b1afc10d1157dd1d9b7b88f9cb961ad4aab17/include
        {REDACTED}/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
        {REDACTED}/01fa27e4325008bc90134e7e378858dd2dfda1c7/include
        {REDACTED}/a0fa4fdfc4f1ffb7802b3a889e5d6182a471c191/include
        {REDACTED}/fcb20bc50f25a5bd770742cf734b75b64a6c7e24/include
        {REDACTED}/14815a52002e670817c3f35a0d525a6de21a36fb/include
        {REDACTED}/build
        {REDACTED}
        {REDACTED}/sysroots/x86_64-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/9.3.0/include
        {REDACTED}/sysroots/x86_64-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/9.3.0/include-fixed
        {REDACTED}/sysroots/armv7vet2hf-neon-poky-linux-gnueabi/usr/include/c++/9.3.0
        {REDACTED}/sysroots/armv7vet2hf-neon-poky-linux-gnueabi/usr/include/c++/9.3.0/arm-poky-linux-gnueabi
        {REDACTED}/sysroots/armv7vet2hf-neon-poky-linux-gnueabi/usr/include/c++/9.3.0/backward
        {REDACTED}/sysroots/armv7vet2hf-neon-poky-linux-gnueabi/usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-arm
    Other Flags:
        --g++
        --gnu_version=90300
Total Memory Usage: 62 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 11360
```

**Comment by ruabmbua** [comment]
Here is a small picture of some of the artifacts, that are all over the code, as soon as I start editing:

**Comment by sean-mcmanus** [comment]
@ruabmbua Why does your logging show repeated "idle loop: reparsing the active document"? That normally shouldn't happen repeatedly. Do you have C_Cpp.enhancedColorization enabled? I don't see that message in your logs.

Normally, you should only see 1 idle loop update after opening a file, e.g.
```
idle loop: reparsing the active document
Checking for syntax errors: 
Queueing IntelliSense update for files in translation unit of: 
cpptools/getFoldingRanges: 
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.254
cpptools/getSemanticTokens: 
```

**Comment by sean-mcmanus** [comment]
Are you editing the file from a different editor or something? I don't see any didChange messages in the logging.

**Comment by ruabmbua** [comment]
The "idle loop: reparsing the active document" might have been my fault, I probably reopened the file twice. 
I am not editing anything from an external editor, and the advanced colorization is enabled (per default).

I do not have any modified settings for the C_Cpp plugin, except the update channel:

```json
"C_Cpp.updateChannel": "Insiders",
```

I already reverted that, for testing.

**Comment by sean-mcmanus** [comment]
@Colengms Any ideas?

**Comment by Colengms** [comment]
Hi @ruabmbua .  Does the issue repro with a simple project?  If not, does it repro with a simple/minimal file in your main (Linux kernel?) project?

Although it may not explain the behavior you're describing, my understanding is that the Linux kernel requires a lot of configuration for IntelliSense to be set up properly.  Some code may not be parse-able without certain macros defined that would have been defined by the build system.  I believe the Linux kernel is one of the test cases for the new "Makefile Tools" extension, which is a custom configuration provider (`configurationProvider`) for the C/C++ extension.  Consider trying that extension.

If the issue does not repro with a simple project or a simple/minimal file in the repro'ing project, it may be due to a bug in the IntelliSense parser that is triggered by parsing some specific segment of code.  That code may be in a header, and could be putting the parser in a bad state prior to your modifications, which it then fails to interpret.  Addressing that would seem to require tracking down the segment of code that triggers the issue.  It's also possible that fully configuring IntelliSense (such as with Makefile Tools) may cause the code to be interpreted differently/properly, and the issue cease to repro.

Anothing thing to try might be to generate a preprocessed source file out of the file you are repro'ing with (using the `-E` arg to gcc).  That preprocessed file may expose the earliest code in the unit that the IntelliSense parser is failing to interpret.  Addressing those the detected issues (which may require fully configuring defines, etc., needed to compile the kernel) might lead the IntelliSense parser to a good state.
