### ISSUE TITLE
Disassembler viewer in debug view.

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#766]
Could you please add a disassembler viewer in dubug view. It will be so helpful for C/C++ developers.
It should not take long time to implement this.

Below placed examples how this view looks like:

![disassembler_1](https://habrastorage.org/web/92b/9a6/773/92b9a677387b4b009538d745fabb3118.png)

![disassembler_2](https://habrastorage.org/web/a0a/406/2d9/a0a4062d938143949fe7f7029cf6020d.png)

**Comment by sean-mcmanus** [comment]
See https://github.com/Microsoft/vscode-cpptools/issues/206 . The last I heard, the debugger team doesn't plan to implement this.

**Comment by hydrogen666** [comment]
sad...
