### ISSUE TITLE
Check some hash instead of just the time stamp for tag parsing

### ISSUE THREAD

**Issue by daoluan** [microsoft/vscode-cpptools#7667]
Bug type: Language Service

**Describe the bug**
- OS and Version: macos catalina 10.15.5 (19F101)
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.40

**Steps to reproduce**

1. Open a c++ git repository in VS Code
2. Wait for the cpp extension to end its work
3. Switch to another git branch in shell
4. Checkout top for high cpu usage and keep high always util reopen vscode

**Expected behavior**

The cpu usage should lower to normal levels after few second/minutes

**Comment by daoluan** [comment]
there is a closed issue #4609, but it seems not be repaired.

**Comment by sean-mcmanus** [comment]
We fixed some issues that could cause it, but you may be hitting something else. When you set C_Cpp.loggingLevel to "Debug" what messages do you see after switching branches? i.e. do you see any messages that seem like unnecessary updating?

There is a certain amount of updating that may need to occur to reparse changed files in the workspace database, but it shouldn't be infinite processing.

Also, a call stack (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) or perf log might help (https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues).

**Comment by sean-mcmanus** [comment]
The "by design" logging would be
cpptools/fileChanged: 
  tag parsing file: 
For every changed file in the branches.

Open files may also trigger an IntelliSense update.

**Comment by sean-mcmanus** [comment]
In other words, I'm not reproing the issue...there might be some special condition you're hitting.

**Comment by daoluan** [comment]
> We fixed some issues that could cause it, but you may be hitting something else. When you set C_Cpp.loggingLevel to "Debug" what messages do you see after switching branches? i.e. do you see any messages that seem like unnecessary updating?
> 
> There is a certain amount of updating that may need to occur to reparse changed files in the workspace database, but it shouldn't be infinite processing.
> 
> Also, a call stack (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) or perf log might help (https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues).

yep, I found that one of my scripts touch all my source files (update all files modifed time to the latest), it hit it XD

I have suggest that use md5 to decide whether reparse the file.

**Comment by sean-mcmanus** [comment]
Okay, that sounds like a good idea...not sure when that we'll get around to that though since we haven't heard of many users hitting this scenario.

**Comment by sean-mcmanus** [comment]
Even though this is closed, it still may be get fixed later on.
