### ISSUE TITLE
Reduce `.ipch` file size

### ISSUE THREAD

**Issue by mingoal** [microsoft/vscode-cpptools#7676]
Type: Feature Request

My project contains a lot of files. The intellij is very slow. So I followed [cpp faq](https://code.visualstudio.com/docs/cpp/faq-cpp) and configured its cache. But I found these cache files are really large.

Is it possible to share some information across `.ipch` files?

I suppose it could improve the performance as the shared part don't need to be parsed again and again. And it should reduce the disk size for `.ipch` files.

configuration `settings.json`
```json
    "C_Cpp.intelliSenseCacheSize": 40960,
    "C_Cpp.intelliSenseCachePath":"/home/<myusername>/.vscode-cpptools",
```

All these `*.ipch` are for source code in one same project. It looks like each `.cpp` has one `.ipch`.
```
.
├── [   55]  4dd4687c9b97399a
│   ├── [    8]  mmap_address.bin
│   └── [ 428M]  X11111111.ipch
├── [   55]  d95dd0a123686235
│   ├── [ 326M]  X22222222.ipch
│   └── [    8]  mmap_address.bin
└── [   54]  f5d20c9ffb34f464
    ├── [ 429M]  X33333333.ipch
    └── [    8]  mmap_address.bin

3 directories, 6 files
```

**Comment by sean-mcmanus** [comment]
The number of files in a project doesn't affect IntelliSense speed, only the size of the TU.

It's not possible to share info, except if the explicit pch feature is implemented -- upvote https://github.com/microsoft/vscode-cpptools/issues/3628. Other requests for improvements to the auto-pch/ipch scenario would need to be made on VS at https://developercommunity.visualstudio.com/search?space=62 .

**Comment by mingoal** [comment]
@sean-mcmanus  thanks for the information.
Do you have any suggestion or guide link for speeding up IntelliSense?
Is it possible to create `.ipch` files for specific files so I don't need to wait one by one?

At present, it takes several minutes for waiting "Updating IntelliSense..." completed.
And it's a large project, but most files are internal libraries which will not be touched.
My develop machine has 16GB memory, 6 cores, centos 8. I use remote ssh for coding on it.

**Comment by sean-mcmanus** [comment]
IPCH files just saves the parsed contents of the header files.

The only way to create an IPCH file is to open the source file.

If your includePath has "**" with a large project, then that could be contributing to the slowness (you'd see CPU processing in cpptools), so making it be non-recursive would reduce that processing.
