### ISSUE TITLE
Unable to initialize gdb debugger.

### ISSUE THREAD

**Issue by anmol065** [microsoft/vscode-cpptools#7677]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10 x64
- VS Code Version:  1.56.2
- C/C++ Extension Version: 1.4.1
- Other extensions you installed (and if the issue persists after disabling them): NO
- A clear and concise description of what the bug is.
- 
- I'm using GNU gcc compiler, make and gdb debugger from cygwin.com.
Compiler work fine but there is issue with debugger.
Some says it is because of space in between my username folder (Anmol Garg)
but i can not rename my username folder. Because of risk of data loss...
If anyone have other solution please tell me.

1: (2014) <-1015-exec-run
1: (2024) ->1015^error,msg="Error creating process /cygdrive/c/Users/Anmol Garg/Documents/projects/helloworld/helloworld.exe, (error 193)."
1: (2024) ->(gdb)
1: (2024) 1015: elapsed time 10
1: (2024) ->&"\n"
1: (2025) ->^done
1: (2025) ->(gdb)
1: (2027) Send Event AD7MessageEvent
ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". Error creating process /cygdrive/c/Users/Anmol Garg/Documents/projects/helloworld/helloworld.exe, (error 193).
1: (2034) <--gdb-exit
1: (2038) ->^exit
1: (2044) Send Event AD7ProgramDestroyEvent
The program 'C:\Users\Anmol Garg\Documents\projects\helloworld\helloworld.exe' has exited with code 42 (0x0000002a).
![Screenshot (565)](https://user-images.githubusercontent.com/55704065/121527344-ea5db380-ca17-11eb-86dd-9fed54d7d0dd.png)

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

Here is my launch.json
![Screenshot (561)](https://user-images.githubusercontent.com/55704065/121511706-8ed6fa00-ca06-11eb-9f51-461962799cdc.png)

task.json
![Screenshot (562)](https://user-images.githubusercontent.com/55704065/121511809-aca45f00-ca06-11eb-9f1e-f8812706da39.png)

setting.json
![Screenshot (560)](https://user-images.githubusercontent.com/55704065/121511932-ce9de180-ca06-11eb-81b2-d4005cb0138f.png)

extension
![Screenshot (563)](https://user-images.githubusercontent.com/55704065/121512005-e37a7500-ca06-11eb-9ad1-785fdc28ebba.png)

gcc-core and gdb version:
![Screenshot (539)](https://user-images.githubusercontent.com/55704065/121512225-20466c00-ca07-11eb-96fa-9b53953863e6.png)
![Screenshot (542)](https://user-images.githubusercontent.com/55704065/121512254-26d4e380-ca07-11eb-896b-35e652486c1e.png)

Please forgive me for my bad English or any other mistake. Cause am new to programming world.
and please give me solution of above problem step by step so i can understand.
It will be very helpful..
Thanks..

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment]
The `task.json` is running `gcc -g -o helloworld helloworld.c` which will generate the binary `helloworld`. 

Your `launch.json` is looking for the program `helloworld.exe` which is not what your compiler is creating.

You can either change the program to point to `helloworld` or change the compilation step to output `helloworld.exe`.

**Comment by anmol065** [comment]
Thanks @WardenGnaw for replying. But what exactly should i change, as i said in my issue am new to programming and GitHub.
So can you please elaborate in which file(or where) and which line of code should i change.
