### ISSUE TITLE
Add support for "*endOfExtensionlessFile" and "*" syntax in files.associations

### ISSUE THREAD

**Issue by Ben-Voris** [microsoft/vscode-cpptools#7679]
I work with many C files that do not have extensions (e.g., they have names like "testc" instead of "test.c").

So, I add something like this to .vscode/settings.json:

```json
{
    "files.associations": {
        "*c": "c"
    }
}
```

This causes the file to be highlighted as C and puts "C" in the status line. But include files are not found. For example, in a file named "testc", the line `#include <stdio.h>` is highlighted with a warning that I should update my include path. And yet, if I simply rename the file with ".c" at the end its name, the squiggly lines disappear.

I use c_cpp_properties.json to set "includePath". The values given there are used for a file name "test.c" but not "testc".

## Version info

```text
Version: 1.57.0 (system setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363
```

## C/C++ Log diagnostics

```text
-------- Diagnostics - 6/10/2021, 3:36:35 PM
Version: 1.4.1
Current Configuration:
{
    "name": "test",
    "intelliSenseMode": "linux-gcc-x64",
    "includePath": [
        "C:\\Users\\BVoris/git/per-version/ABC/include",
        "C:/Compiler/ABC/usr/include/**"
    ],
    "compilerPath": "",
    "cStandard": "c99",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": false,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "browse": {
        "path": [
            "C:\\Users\\BVoris/git/per-version/ABC/include",
            "C:/Compiler/ABC/usr/include/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Temp\junk\srcc ]:
    C:\TEMP\JUNK\SRCC
Translation Unit Configurations:
[ C:\Temp\junk\srcc ]:
    Process ID: 32304
    Memory Usage: 12 MB
    Includes:
        C:\USERS\BVORIS\GIT\per-version\ABC\INCLUDE
    Standard Version: c99
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=103000
        --header_only_fallback
Total Memory Usage: 12 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 655
```

If I rename testc to test.c, "Translation Unit Mappings" lists the second include directory and "--header_only_fallback" is removed.

**Comment by sean-mcmanus** [comment]
There appears to be a bug where the "testc" file is not getting tag parsed. That is causing the recursive includes `**` to fail. You may be able to workaround the issue via not using recursive includes `**` but other things may be broken still (such as the outline view and other global symbols in the file).

**Comment by sean-mcmanus** [comment]
Our extension don't currently support the "*c" syntax, only "extensionlessFilename" or "*.extension". Using "testc" should fix that particular file. Could you explain more what the full scope of the files.associations you're using are?

**Comment by Ben-Voris** [comment]
I'm not exactly sure what you're looking for, but I have many tens of thousands of C files like this (without an extension). Unfortunately for my use of code, I cannot change the file names.

How does this work for C++, where file names without extensions are more common?

**Comment by sean-mcmanus** [comment]
The entire file normally gets added to the files.associations. This is the only report we've seen of "*endOfFileName" being used as a file.associations.

**Comment by sean-mcmanus** [comment]
I was asking do you all your C files end with "c"?

**Comment by Ben-Voris** [comment]
The names of many of the C and C++ source files end with "c" or "h", but not nearly all. Depending on the particular source base, I might associate "*" with C or C++ and then use a mix of other patterns and individual file names for the other file types.￼ And, sometimes, other development team followed other conventions.￼

Old, but still heavily used, code can be weird and wonderful.￼

**Comment by bobbrow** [comment]
> How does this work for C++, where file names without extensions are more common?

This is really only common for header files and our extension has code to deal with that case.  The `files.associations` doesn't give us any hint of what is a header file versus a source file, so I'm not sure how we would be able to make a distinction for extensionless source files.

**Comment by sean-mcmanus** [comment]
@bobbrow The problem is that the files.associations check fails to recognize the "*c" or "*" as a match since it's only looking for "filename" or "*.extension" cases, which causes the files to not be parsed as all, i.e. as if they were not C/C++ files, so it's not an issue of header versus source file (although that could be an additional issue).

**Comment by bobbrow** [comment]
Yes, I wasn't intending to comment on whether extension vs. no extension worked or not. I was just referring to the issue that might arise later.  Our code doesn't treat any extensionless files as source files that I'm aware of.

**Comment by sean-mcmanus** [comment]
When `"extensionlessFile": "c"` exists in files.associations then we'll correctly parse the file. The "as source" distinction only matters in certain cases such as whether the file will be tag parsed without being opened or included if it's not in the workspace folder, i.e. the limitSymbolsToIncludedHeaders setting.
