### ISSUE TITLE
How or Can I launch or attach a program/process across platform

### ISSUE THREAD

**Issue by YinglinJiang** [microsoft/vscode-cpptools#768]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|logcat|abhiagr|0.0.7|
|code-gnu-global|austin|0.2.2|
|GBKtoUTF8|bukas|0.0.2|
|java-debug|DSnake|0.0.2|
|vscode-javac|georgewfraser|0.0.41|
|CppSnippets|hars|0.0.9|
|start-git-bash|McCarter|1.2.1|
|vscode-csscomb|mrmlnc|4.0.1|
|cpptools|ms-vscode|0.11.1|
|PowerShell|ms-vscode|1.1.0|
|remote-vscode|rafaelmaiolla|1.0.1|
|vscode-icons|robertohuertasm|7.7.0|
|vscode-header-source|ryzngard|1.0.4|
|code-settings-sync|Shan|2.8.0|
|guides|spywhere|0.7.0|
|java-imports-snippets|tushortz|0.0.1|
|java-snippets|tushortz|0.0.1|
|cmake|twxs|0.0.17|
|vscode-react-native|vsmobile|0.3.2|
|vscode-proto3|zxh404|0.1.1|;

Problem description：
I want debug a Linux c/c++ program. But sometimes it better if it can be debugging the remote program or progress.  If so we can edit&debug the code on Windows. It's very convenient to develop a c++ server program.

Can you help me to solve it.

thanks.

**Comment by pieandcakes** [comment]
@YinglinJiang [This](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md) documentation should be able to help you get started using SSH to talk to `gdb` remotely.

**Comment by aengusjiang** [comment]
Great!!!
 Thank a lot.
