### ISSUE TITLE
`autocompleteAddParentheses` should place the cursor inbetween the new parentheses

### ISSUE THREAD

**Issue by AaronRecord** [microsoft/vscode-cpptools#7687]
Type: Feature Request

When autocompleting a function with `autocompleteAddParentheses`, the cursor should be added inbetween the parentheses to make it easier to insert arguement values. If a function has no arguements, the current behavior is fine, but if a function has arguements (very common) then you have to use left arrow, type in the arguements and then use the right arrow. Not a big deal but I think this would make more sense then the current behavior which is placing the cursor after the parentheses.

**Comment by LightningAA** [comment]
If you wanted to get really smart about it, functions that don't take any arguments could keep the current behavior, but that might be overcomplicating things.

**Comment by sean-mcmanus** [comment]
This should already be the case. Can you provide more repro info?

**Comment by LightningAA** [comment]
I'm sorry, I hadn't tested this setting very thoroughly before making this issue and I guess I only tested it on methods that didn't take any parameters. Thank you for your time and this wonderful feature, sorry.
