### ISSUE TITLE
Quick Suggestion is not working after the update to V 1.57.0 on Windows 10.

### ISSUE THREAD

**Issue by bhaskarakhil29** [microsoft/vscode-cpptools#7688]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 and 10.0.19042 Build 19042
- VS Code Version: 1.57.0
- C/C++ Extension Version: 1.4.1
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

![Screenshot (5)](https://user-images.githubusercontent.com/22377079/121798972-0dba7580-cc47-11eb-8e1c-9ea5cf2e58d5.png)
![Screenshot (6)](https://user-images.githubusercontent.com/22377079/121798974-0f843900-cc47-11eb-877a-9248fb064eaa.png)
![Screenshot (7)](https://user-images.githubusercontent.com/22377079/121798975-101ccf80-cc47-11eb-86ae-385571038a04.png)

**Comment by michelleangela** [comment]
@bhaskarakhil29 
Is this issue for HTML files or C++ files? From the screen shot provided, it looks like this issue is for HTML. 

This GitHub page is for the vscode-cpptools C++ extension. For HTML issues, please report bugs to either the extension you're using for HTML or at https://github.com/microsoft/vscode/issues for basic HTML IntelliSense features.
