### ISSUE TITLE
i cant code using c or c++

### ISSUE THREAD

**Issue by AISHU755** [microsoft/vscode-cpptools#7689]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by michelleangela** [comment]
@AISHU755 
Could you provide more information, such as example code and what feature is working with the C++ extension? Also, could you provide the following info:

- OS and Version:
- VS Code Version: 
- C/C++ Extension Version: 
- Other extensions you installed (and if the issue persists after disabling them):
