### ISSUE TITLE
package.json squiggles appear for "primary" (walkthrough)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7692]
Not sure how to get rid of them...

**Comment by Colengms** [comment]
With the latest VS Code Insiders, I see 1 squiggle, so if you are seeing multiple of 'them', could you be more specific about what you are seeing?

The feature is not complete, so it may be premature to open an issue against squiggles in package.json.

**Comment by Colengms** [comment]
I don't see any squiggles for media.markdown with the latest VS Code Insiders.

**Comment by sean-mcmanus** [comment]
Oops, my bad. I was using non-Insiders. I see a squiggle on "primary" though...maybe this issue can track that?
