### ISSUE TITLE
the enum type can't highlight

### ISSUE THREAD

**Issue by AllenHuai** [microsoft/vscode-cpptools#7698]
Bug type: General

![image](https://user-images.githubusercontent.com/23722095/122006614-9d982500-cde9-11eb-8537-74fc2bb12dc7.png)

**Describe the bug**
- OS and Version: linux
- VS Code Version: 1.57.0
- C/C++ Extension Version: 1.5.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Can you give more repro info? Do you repro it with
```
class foo
{
    enum efoo
    {
        aaa,
        bbb
    };
};
```
Is the issue with the highlighting in the document or in the hover?

What do you see when you use the "Inspect Editor Token and Scopes" command? I see
![image](https://user-images.githubusercontent.com/19859882/122100466-15555800-cdc8-11eb-904a-674366eb82e3.png)
