### ISSUE TITLE
Can't jump to the right place and can't find function

### ISSUE THREAD

**Issue by myrfy001** [microsoft/vscode-cpptools#77]
When use VS Code to edit Contiki OS's source code,which can be found from https://github.com/contiki-os/contiki

for example, in contiki/core/net/rpl 

when editing rpl_icmp6.c at line 420, can't jump to the defination of rpl_process_dio() . In fact, it can only jump to the Prototype of this function but can't find the body of this function.

**Comment by jgoshi** [comment]
Marking this as a won't fix since this is a difficult to parse corner case.

Anytime we have a brace as part of the conditional (as shown below), the function won't parse properly. The fix is to move the "{" out of the #ifdef block.

void foo()
{
    bool b;
#ifdef M1
    if (b) {
#else
    if (!b) {
#endif
        b = true;
    }
}
