### ISSUE TITLE
Mac framework include support in the new IntelliSense engine

### ISSUE THREAD

**Issue by xchen-cs** [microsoft/vscode-cpptools#770]
I've encountered a problem on Mac for OpenGL, F12 works.
But it marks both the header files and symbols.
![untitled](https://cloud.githubusercontent.com/assets/1148756/26389306/ee09ee8c-408b-11e7-9dfd-bc0f77a00d15.jpeg)
![untitled1](https://cloud.githubusercontent.com/assets/1148756/26389307/ee1acec8-408b-11e7-8cc8-735e8d07abc6.jpeg)
I guess it may due to the use of frameworks on Mac, and I've tried to add "/System/Library/Frameworks" to the include path, but it doesn't work.
Is there any way to overcome this?

**Comment by bobbrow** [comment]
You can make this work by editing the msvc.64.darwin.json file in `~/.vscode/extensions/ms-vscode.cpptools-<version>/bin`.

Add `"--framework_include_directory=/System/Library/Frameworks"` to the "defaults" array.  We'll add it by default in a future update.

**Comment by bobbrow** [comment]
And BTW, sorry for the delay.  I thought I had posted a comment on this last week, but apparently I didn't click the button. :(

**Comment by xchen-cs** [comment]
According to your method, it indeed works quite well, thanks Bob!

**Comment by bobbrow** [comment]
Thanks for confirming.  I'll put this in the next update.

**Comment by bobbrow** [comment]
This is fixed in 0.12.0

**Comment by xgalaxy** [comment]
This seems broken again. And the workaround doesn't work.

EDIT: Figured it out. Had to run the below command to get the framework path. Its too bad this isn't done for us.

`clang -v -E -x C++ - < /dev/null`

**Comment by bobbrow** [comment]
Can you paste the output of your clang command?  We should be parsing the framework directories (I'm staring at the code that does this).  If you have multiple versions of clang installed, make sure that `/usr/bin/clang` symlinks to the correct one.  If that path doesn't resolve, we try the version installed with XCode.

**Comment by augustocdias** [comment]
Is this fixed? The workaround did not work...
I'm using this as a temp solution https://github.com/emcrisostomo/link-osx-framework-headers
But I could not get IntelliSense to work with the frameworks headers...

**Comment by sean-mcmanus** [comment]
@augustocdias We support the "macFrameworkPath" in c_cpp_properties.json. Does that work for you?

**Comment by lummish** [comment]
EDIT: *issue moved to #2917*

**Comment by bobbrow** [comment]
@lummish, I moved your issue to #2917
