### ISSUE TITLE
"Find all references" on a file scope symbol returns extra results

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7702]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.57.0
- C/C++ Extension Version: 1.4.0 and 1.5.0-insiders
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Code sample**
main.cpp
```
int var1;

int func1()
{
    if (var1 == 0)
        return 0;
    return 1;
}
```
test.cpp
```
void myfunction(int var1, int var2, int var3)
{
}
```

**Steps to reproduce**

1. Create the two provided sample files.
2. Do a "find all references" on symbol `var1` in file main.cpp.
3. Observe results also includes symbol from test.cpp that is not true reference of `var1`.

Does not reproduce on Visual Studio.

**Comment by sean-mcmanus** [comment]
There's a similar bug on VS at https://developercommunity.visualstudio.com/t/c-intellisense-find-all-references-confirms-refere/1014321, but the difference is that VS is differentiating between the references that are local to the function and global, e.g. a simpler repro is:
```
int test;
int func(int test){}
```

**Comment by michelleangela** [comment]
Is this bug on VS then?

**Comment by sean-mcmanus** [comment]
No. I may have a fix soon...
