### ISSUE TITLE
vcFormat not work when use Chinese

### ISSUE THREAD

**Issue by frostylight** [microsoft/vscode-cpptools#7703]
Bug type: Language Service

**Describe the bug**
- OS and Version: **Windows_NT x64 10.0.19042**
- VS Code Version: **1.57.0**
- C/C++ Extension Version: **1.4.1**
- Other extensions you installed : **Chinese (Simplified) Language Pack**
- **When use Chinese( more than 3 charaters in total ), vcFormat cannot work in some parts of file**
- file encoding: GBK or UTF-8
- similar with #5951

![bug](https://user-images.githubusercontent.com/31412334/122232663-fd77f400-ceed-11eb-9cfd-e3f02e580506.gif)

**Steps to reproduce**
1. Creat .cpp file
2. use Chinese( more than 3 charaters in total ) in output or comment
3. format file with vcFormat

**Expected behavior**
**vcFormat work normally**

**Code sample and logs**

- Code sample
```
#include<bits/stdc++.h>
using namespace std;
void main(){
    //中文注释
    printf("中文输出\n");
    for (int i = 1;i <= 5;++i){

            }
    for (int i = 5;i <= 7;++i){

            }
}
```

- Configurations in `c_cpp_properties.json`
**No, single file**

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
<details>
  <summary>log</summary>
 <pre><code>  
-------- Diagnostics - 2021/6/16下午10:20:35
Version: 1.4.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe",
    "compilerArgs": [],
    "cStandard": "c11",
    "cppStandard": "c++11",
    "intelliSenseMode": "windows-gcc-x64",
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\light\Documents\Workfolder\C++\abug.cpp ]:
    C:\USERS\LIGHT\DOCUMENTS\WORKFOLDER\C++\ABUG.CPP
Translation Unit Configurations:
[ C:\Users\light\Documents\Workfolder\C++\abug.cpp ]:
    Process ID: 8876
    Memory Usage: 131 MB
    Compiler Path: C:\mingw64\bin\gcc.exe
    Includes:
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\X86_64-W64-MINGW32
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE\C++\BACKWARD
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE
        C:\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE-FIXED
        C:\MINGW64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++11
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=80100
Total Memory Usage: 131 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2380
</code></pre>
</details>

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
<details>
  <summary>log</summary>
<p>it seems stuck</p>
 <pre><code>  
cpptools/formatDocument: file:///c%3A/Users/light/Documents/Workfolder/C%2B%2B/abug.cpp (id: 1735)
正在格式化输入:
#include<bits/stdc++.h>
using namespace std;
void main(){
    //中文注释
    printf("中文输出\n");
    for (int i = 1;i <= 5;++i){

            }
    for (int i = 5;i <= 7;++i){

            }
}
正在格式化文档: file:///c%3A/Users/light/Documents/Workfolder/C%2B%2B/abug.cpp
Formatting Engine: vcFormat
</code></pre>
</details>

**Comment by sean-mcmanus** [comment]
Probably the same root issue as https://github.com/microsoft/vscode-cpptools/issues/7704

**Comment by sean-mcmanus** [comment]
This is the same root cause as https://github.com/microsoft/vscode-cpptools/issues/7704, so we'll use that to track the fix (since I saw that issue first, even though this was reported earlier).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0-insiders2
