### ISSUE TITLE
engineLogging errors when accessing array values

### ISSUE THREAD

**Issue by curtisembedded** [microsoft/vscode-cpptools#7707]
Issue Type: <b>Bug</b>

Hello,

I am debugging a remote application using gdbserver. Break points and stepping works fine. Scalar values in the watch window work. Attempting to display the values of an array in the watch window fails. This is what is displayed when engineLogging is enabled.

1: (25318) <-1055-var-list-children --simple-values "var13" 0 1000
1: (25318) ->1055^error,msg="mi_cmd_var_list_children: Usage: [PRINT_VALUES] NAME"
1: (25318) ->(gdb)
1: (25318) 1055: elapsed time 0

ALSO, no local variables are displayed in the "variables" window. Entering GDB commands to display variables works fine in the Debug Console.

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-73-generic

C/C++ Extension v1.4.1

Extension version: 1.4.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.4.0-73-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (2 x 3990)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|1.91GB (0.08GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 1a20e38d-432d-4e39-a4a6-0277d870a237|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehov:30309549
vscod805:30301674
binariesv615cf:30321889

```

</details>

**Comment by WardenGnaw** [comment]
Can you share the version of GDB that you are using on the remote side?

**Comment by curtisembedded** [comment]
Hello Warden,

This is a very old version of GDB. It is probably the issue. The commands like "info locals" and "info variables" work from the debug console. There is something about the commands used by the VSC debugger interface.

GNU gdb (Sourcery G++ Lite 2008q3-72) 6.8.50.20080821-cvs
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-pc-linux-gnu --target=arm-none-linux-gnueabi".
For bug reporting instructions, please see:

**Comment by WardenGnaw** [comment]
It looks like that version of GDB only supports: 
```
-var-list-children [print-values] name
```

Where we are expecting: 
```
-var-list-children [print-values] name [from to]
```
Here is the line we send the command: https://github.com/microsoft/MIEngine/blob/fd0cd48c82f00ce0e6e31240dfade21ba63c8270/src/MICore/CommandFactories/MICommandFactory.cs#L353

We update the commands we send to GDB based on https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html

Are you able to use an updated version of GDB that supports this newer MI command?

**Comment by curtisembedded** [comment]
Would this require updating gdbserver as well?

I could try a newer gdb version but may be stuck with the old gdbserver since that runs on the target.

**Comment by WardenGnaw** [comment]
I believe `gdb` handles the MI commands and will communicate with its own connection with `gdbserver`. So there should not be a need to update `gdbserver`.
