### ISSUE TITLE
save slow on C++ file with default intelli sense engine

### ISSUE THREAD

**Issue by garymm** [microsoft/vscode-cpptools#7718]
**Steps to reproduce**

* Create a workspace with a mix of C++ and Python code
* Enable both C/C++ and Python extensions
* Edit a C++ file
* Save all

Expected behavior:
Save happens instantaneously.

Actual behavior:
I sometimes see "save" take over 2 seconds to complete. It seems to happen about 1/4 of the time.

I have only been able to reproduce with both the Python and C/C++ extension enabled, but not with only one of them enabled.

Note if it matters: I always do "save all" rather than just "save".

I have format on save enabled.

**versions**

C/C++ 1.4.1
Python 2021.6.999406279 (this also pulls in PyLance and Jupyter)
VSCode 1.57.0 (user setup)

**System information**

CPUs | Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | &nbsp;
Memory (System) | 31.83GB (21.42GB free)
Process Argv | --crash-reporter-id 6857c1a2-a597-4d5d-96f9-c80d4cb7c851
Screen Reader | no
VM | 0%

<hr style="box-sizing: border-box; color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Remote | SSH: garymiguel-dev0.westus.cloudapp.azure.com
-- | --
OS | Linux x64 5.4.0-1041-azure
CPUs | Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (64 x 2593)
Memory (System) | 125.90GB (115.23GB free)
VM | 0%

**A/B experiment info:**

vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vshan820:30294714
vscus158:30321503
vscod805cf:30301675

**Logs from remote extension host with trace log level during a slow save:**

```
[2021-06-18 00:14:16.124] [exthost] [trace] [ms-vscode.cpptools] provider DONE after 3ms
[2021-06-18 00:14:20.338] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2021-06-18 00:14:20.339] [exthost] [trace] [ms-vscode.cpptools] INVOKE provider 'W'
[2021-06-18 00:14:20.376] [exthost] [trace] [ms-vscode.cpptools] provider DONE after 37ms
[2021-06-18 00:14:20.395] [exthost] [debug] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' finished after 0ms
[2021-06-18 00:14:20.528] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2021-06-18 00:14:20.943] [exthost] [trace] [DiagnosticCollection] change many (extension, owner, uris) ms-vscode.cpptools C/C++ [[{"$mid":1,"external":"file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h","path":"/home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h","scheme":"file"},[]]]
[2021-06-18 00:14:20.966] [exthost] [trace] [ms-vscode.cpptools] INVOKE provider 'T'
[2021-06-18 00:14:20.966] [exthost] [trace] [ms-vscode.cpptools] provider DONE after 0ms
[2021-06-18 00:14:21.023] [exthost] [trace] [ms-vscode.cpptools] INVOKE provider 'T'
[2021-06-18 00:14:21.023] [exthost] [trace] [ms-vscode.cpptools] provider DONE after 0ms
[2021-06-18 00:14:21.161] [exthost] [trace] [ms-vscode.cpptools] INVOKE provider 'Te'
[2021-06-18 00:14:21.162] [exthost] [trace] [ms-vscode.cpptools] provider DONE after 1ms
[2021-06-18 00:14:21.859] [exthost] [trace] ExtHostCommands#executeCommand setContext
[2021-06-18 00:14:22.199] [exthost] [trace] ExtHostSCM#$provideOriginalResource 0 file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h
[2021-06-18 00:14:24.439] [exthost] [debug] ProxyResolver#resolveProxy unconfigured https://vortex.data.microsoft.com/collect/v1 DIRECT 
Error: Error for stack trace
	at resolveProxy (/home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/vscode-proxy-agent/out/index.js:105:69)
	at /home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/vscode-proxy-agent/out/index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (/home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/vscode-proxy-agent/out/index.js:293:54)
	at _PacProxyAgent.<anonymous> (/home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/vscode-proxy-agent/out/agent.js:71:37)
	at Generator.next (<anonymous>)
	at /home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/vscode-proxy-agent/out/agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/vscode-proxy-agent/out/agent.js:4:12)
	at _PacProxyAgent.callback (/home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/vscode-proxy-agent/out/agent.js:53:16)
	at _PacProxyAgent.addRequest (/home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/agent-base/dist/src/index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (/home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/vscode-proxy-agent/out/index.js:297:24)
	at Object.request (/home/azureuser/.vscode-server/extensions/ms-vscode.cpptools-1.4.1/dist/main.js:255:22)
	at Function.__webpack_modules__.604.Util.makeRequest (/home/azureuser/.vscode-server/extensions/ms-vscode.cpptools-1.4.1/dist/main.js:5625:26)
	at Gzip.cb (/home/azureuser/.vscode-server/extensions/ms-vscode.cpptools-1.4.1/dist/main.js:4608:28)
	at Gzip.zlibBufferOnEnd (zlib.js:152:10)
	at Gzip.emit (events.js:315:20)
	at endReadableNT (internal/streams/readable.js:1327:12)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by Colengms** [comment]
> I have format on save enabled.

Hi @garymm .  Does the issue still occur with format on save disabled?  If so, what is the value of your `C_Cpp.formatting` setting?  If unset, or set to `ClangFormat` (or `Default`), `clang-format` is executed on the system before the save can be completed.  That may account for the delay, but I'm not sure why it would only occur if the Python extension is also installed.  Are you also using a feature of the Python extension that would apply to C++ sources when saved?

**Comment by garymm** [comment]
Thanks for taking a look!

Yes format on save is enabled and is using the default clang-format.

But clang-format by itself is plenty fast, as can be seen when I only enable the C++ extension, or when I invoke it manually in the terminal.

I don't know of anything in the Python extension that should react to C++ sources being saved, and I don't see anything in the extension host logs that I pasted that would suggest that.

I'm not sure how to dig further though. Any suggestions?

(I work at MS BTW and would be happy to do a teams call with screen share if that'd be helpful)

**Comment by sean-mcmanus** [comment]
Can you set C_Cpp.loggingLevel to "Debug" and then look at the C/C++ logging pane and see what messages appear when the repro occurs, particularly the message before and after the 2 second freeze?

Also, which processes are using CPU when the save is taking a long time?

It's possible our main process is blocked by an IntelliSense update caused by a modification to one of the saved files. If you set C_Cpp.intelliSenseEngine to "Tag Parser" (temporarily) and it stops reproing, then that is most likely the cause.

**Comment by garymm** [comment]
I think `cpptools-srv` is the top process using CPU during the freeze.

I **can** reproduce with intelliSenseEngine  = "Tag Parser".

C/C++ log output during freeze:

```
Formatting document: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h
Formatting Engine: clangFormat
Formatting raw output:
#pragma once

#include <torch/csrc/jit/ir/ir.h>

#include <memory>

namespace torch {
namespace jit {
// see .cpp for docs
TORCH_API void RemoveInplaceOps(const std::shared_ptr<Graph>& graph);

TORCH_API void ImplicitCastForBinaryInplaceOps(Block* block);
} // namespace jit
} // namespace torch

Formatting diffed output:

terminating child process: 305808
textDocument/didChange: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h
cpptools/textEditorSelectionChange
cpptools/fileChanged: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h
cpptools/getFoldingRanges: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h (id: 216)
cpptools/getCodeActions: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h (id: 217)
idle loop: reparsing the active document
  tag parsing file: /home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h
Checking for syntax errors: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h
Queueing IntelliSense update for files in translation unit of: /home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.cpp
sending 1 changes to server
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 7.758
cpptools/getFoldingRanges: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h (id: 218)
cpptools/getSemanticTokens: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h (id: 219)
Database safe to open
cpptools/getDocumentSymbols: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h (id: 220)
cpptools/getDocumentSymbols
textDocument/didSave: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h
idle loop: reparsing the active document
Checking for syntax errors: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h
Queueing IntelliSense update for files in translation unit of: /home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Update IntelliSense time (sec): 0.255
cpptools/getSemanticTokens: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h (id: 221)
cpptools/getFoldingRanges: file:///home/azureuser/src/pytorch/pytorch/torch/csrc/jit/passes/remove_inplace_ops.h (id: 222)
```

**Comment by sean-mcmanus** [comment]
cpptools-srv won't be launched when intelliSenseMode is "Tag Parser" -- if you see it running, that could be from another instance of VS Code or a dangling process that should be killed. When you repro it with "Tag Parser" mode and there's no cpptools-srv, what is the process using CPU?

Your logging indicates the format is happening, then it takes 7 seconds to update the IntelliSense process (cpptool-srv), which could be blocking the didSave that comes in later on. I'll see if I can repro something similar with a file that takes a while to update.

What is the symptom you see that indicates that saving is slow? Is the modified dot taking a long time to disappear?

**Comment by garymm** [comment]
Yes it's the modified dot taking a long time to disappear.
I just tried and failed to repro with tag parser. Previously I just switched the setting without reloading the window. This time I changed the setting and reloaded the window. Not sure if that matters.

Will try to repro again and see what's using the CPU.

**Comment by sean-mcmanus** [comment]
On save/formatting, I see the python extension creating a .tmp file in the current folder, which is triggering our fileCreated/Deleted handler to run, which in certain cases could cause an additional delay -- we fixed that for didChange...I think we can apply the same fix for fileCreated/Deleted.

**Comment by sean-mcmanus** [comment]
Does adding the tmp file extension to your files.exclude setting fix the issue for you, e.g.
```
    "C_Cpp.files.exclude": {
        "**/*.tmp": true,
        "**/.vscode": true
    }
```

**Comment by sean-mcmanus** [comment]
If adding the files.exclude fixes the issue, I would say it's the Python's extension's fault for creating tmp files at the same location as the python files. They should probably be using some other temp file location, the .vscode folder, or some other folder that is commonly excluded.

**Comment by garymm** [comment]
I've managed to repro the slowness with the python extensions disabled but not with tag parser.
It's pretty reliable to reproduce by adding / removing `#include <memory>` to a .h file in my project (which is pytorch/pytorch).

When the slow save is happening `cpptools-srv` is using lots of CPU.

Updated the issue title, since it seems that this doesn't have anything do with the Python extension.

**Comment by sean-mcmanus** [comment]
@Colengms Are you able to repro this?

**Comment by Colengms** [comment]
The issue would seem to be due to the format-on-save operation getting blocked on an intelliSense update.  I don't think the format operation itself would block, but the entire message handling thread may get blocked due to a subsequent IntelliSense operation such as hover (which is really easy to cause when moving the mouse around).

@garymm Could you provide a bit more log output, leading up to the freeze?  I suspect we would see an IntelliSense update as well as some other IntelliSense operation get queued and allowed to complete before the format operation begins.

If that is the underlying cause, it's a known issue and something we plan to address as part of our Unification milestone.  I believe this issue is tracking by: https://github.com/microsoft/vscode-cpptools/issues/5382

**Comment by sean-mcmanus** [comment]
The previous logging shows the didSave getting delayed until after the IntelliSense updating, but I always see formatting, didSave, IntelliSense update. If you have multiple files open that are unsaved, then that could cause the main queue to be backlogged a little since it has to handle all the formatting in sequence before it can handle the didSave's. A hover could also block the main thread as Colen mentioned. You could attach a debugger to get call stacks of the main thread, but that might be hard to do accurately if the delay is only a couple seconds.
