### ISSUE TITLE
Feature request: support for xtensa architecture for ESP32 and ESP8266

### ISSUE THREAD

**Issue by gojimmypi** [microsoft/vscode-cpptools#772]
@pieandcakes  - Per the comment in issue #763 - I'd like to add a feature request to have remote gdb working for the xtensa architecture in VSCode, please.  :)

**Comment by pieandcakes** [comment]
@gojimmypi @dymo I left comments in #763 on what the issue looks like. It lies in the version of `gdb` and it having issues in MI interpreter mode which is the remote controlling interface we use with gdb. This isn't a cpptools extension or a VS Code problem.
