### ISSUE TITLE
Renaming with F2 returns "cannot refactor because file X has changed"

### ISSUE THREAD

**Issue by andrea-nistico** [microsoft/vscode-cpptools#7720]
Bug-type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.57
- C/C++ Extension Version: v1.5.0-insiders

Every time I try to refactor the name of a variable I get the correct preview of all occurrences, when I hit enter I get the message: "cannot refactor because file X has changed" where file X is the file where I start my refactoring.

**Comment by sean-mcmanus** [comment]
Hmm, I'm not reproing this.

@Colengms Are you able to repro this?

**Comment by sean-mcmanus** [comment]
@andrea-nistico This might be a VS Code bug -- are you able to try refactoring with another language, such as with a TypeScript file?

**Comment by Colengms** [comment]
Hi @andrea-nistico .  This behavior is not part of the C/C++ Extension.  The message you are seeing is coming from VS Code itself. 
 I believe you will see that message any time you make modifications to a file after having started a rename operation that requires previewing.  The operation must be completed without any changes being made to the associated files, or you will see that message.

**Comment by andrea-nistico** [comment]
sorry for my late reply, I wasn't in the office last week. The file itself is not changing during renaming, I was able to variable simply by applying the refactor from a different occurrence inside a different file. I guess it is related to some vscode bug.

**Comment by Colengms** [comment]
Hi @andrea-nistico Is it possible you have an extension or feature enabled that may modifying a document automatically (such as formatting) ?  Otherwise, this would seem to be a VS Code issue.  The C/C++ Extension essentially just returns the list of locations to rename, and the rest is handled by VS Code.

**Comment by andrea-nistico** [comment]
@Colengms thanks for the hints, I do not have any formatting extensions but I'll dig into it. I double-checked and the file in question is not changing at all.
