### ISSUE TITLE
Problem in debugger c++

### ISSUE THREAD

**Issue by 2cai** [microsoft/vscode-cpptools#7721]
Bug type: Debugger

- VS Code Version:
- C/C++ Extension Version:

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Open some file  in " Área de trabalho" in VScode.
2. After config gdb debug, try run it .
When I try to use debugger gdb in vscode, I always had this problem: "unable to satart debugging. Unexpected GDB output from command ... no such file or directory. The path of directory is "C:\Users\gabri\OneDrive\Área de Trabalho" and I figure out that the problem is in accent of "Área de Trabalho" which desktop in portuguse i.e the desktop area for pc's in portuguese. I hope you can fix this bug. Thanks !

**Comment by WardenGnaw** [comment]
GDB does not handle spaces properly. 

The workaround would be to remove the spaces in `cwd` and `program`.
