### ISSUE TITLE
Don't squiggle a `compilerPath` of `cl` or `cl.exe` in `c_cpp_properties.json`

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#7723]
It's OK to specify a `compilerPath` of `cl` or `cl.exe`.  We don't invoke `cl.exe`, but it's location would tell us where to find system headers.  If only `cl` or `cl.exe` is specified, we should  search for an install of VS on the system and use those system headers.  So, this is valid, doesn't result in any configuration errors/warnings, and doesn't need to be squiggled in `c_cpp_properties.json`

**Comment by sean-mcmanus** [comment]
Oh, this must be a regression -- it didn't squiggle cl/cl.exe previously.

**Comment by sean-mcmanus** [comment]
I had fixed this bug previous at https://github.com/microsoft/vscode-cpptools/pull/3263
