### ISSUE TITLE
Extension won't load anymore, stuck at "reload required"

### ISSUE THREAD

**Issue by TheGreyDiamond** [microsoft/vscode-cpptools#7727]
Bug type: General

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.57.1
- C/C++ Extension Version: 1.4.1
- Other extensions you installed (and if the issue persists after disabling them): Issue persists
The Cpptools extension shows "Reload required" in the extension viewer. Looking at the devs tools it generates this error:
```
Activating extension 'ms-vscode.cpptools' failed: Invalid or unexpected token.
$onExtensionActivationError @ mainThreadExtensionService.ts:95
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:634
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:634
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
D @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

The "Reload required" even shows up when the extension is not installed!

**Comment by sean-mcmanus** [comment]
It sounds like your install may be corrupted somehow. Can you uninstall the extension, reload VS Code, and then re-install it?

The error log doesn't show any reference to our code, except for the 1st line.

**Comment by TheGreyDiamond** [comment]
I've already tried that. Even when it's uninstalled and still showing "Reload required" even after reloading multiple times.

**Comment by sean-mcmanus** [comment]
Can you go into the C:\Users\username\.vscode\extensions folder to make sure the extension is being fully deleted? There might be some VS Code issue that is preventing the folder from being removed.

**Comment by TheGreyDiamond** [comment]
Removing the folder and installing it via the extension browser worked. Thanks.
