### ISSUE TITLE
Natvis visualizer doesn't support <LinkedListItems>

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#7730]
Issue Type: <b>Bug</b>

1. Use the following natvis file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
    <Type Name="std::__cxx11::list&lt;*&gt;">
        <DisplayString>{{ size={_M_impl._M_node._M_size} }}</DisplayString>
        <Expand>
            <LinkedListItems>
                <Size>_M_impl._M_node._M_size</Size>
                <HeadPointer>_M_impl._M_node-&gt;_M_next</HeadPointer>
                <NextPointer>_M_next</NextPointer>
                <ValueNode>($T1)((std::_List_node&lt;$T1&gt; *)_M_impl._M_node)-&gt;_M_storage</ValueNode>
            </LinkedListItems>
        </Expand>
    </Type>
</AutoVisualizer>
```

2. Setup debug for the following file:
([MinGW-W64 gcc](https://github.com/brechtsanders/winlibs_mingw/releases/download/11.1.0-12.0.0-9.0.0-r2/winlibs-x86_64-posix-seh-gcc-11.1.0-mingw-w64-9.0.0-r2.zip) is used)
```c++
#include <list>

int main()
{
    std::list<int> testlist = { 7, 5, 16, 8 };
    testlist.push_front(25);

    return 0;
}
```

3. See that natvis visualizer is showing `{ size=4 }` for `testlist` variable, but `LinkedListItems` isn't displayed.
**NOTE: when I add `(int)((std::_List_node<int> *)testlist._M_impl._M_node)->_M_storage` <ValueNode> expression to watch points - I see value of current node.**

Extension version: 1.5.0-insiders
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.90GB free)|
|Process Argv|--locale=en --crash-reporter-id c8510ba5-736a-4465-9c29-9471122a68c5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30323119

```

</details>

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue.  We’ll let you know if we need more information to investigate it.

We have something similar in our Android case which works:
https://github.com/microsoft/MIEngine/blob/8456c49b4731971b885c2909f9feaac4bdcd494d/src/AndroidDebugLauncher/Microsoft.Android.natvis#L296-L306

and is part of our [xsd](https://github.com/microsoft/MIEngine/blob/8456c49b4731971b885c2909f9feaac4bdcd494d/src/MIDebugEngine/Natvis.Impl/natvis.xsd#L267) and parsed in this [block of code](https://github.com/microsoft/MIEngine/blob/8456c49b4731971b885c2909f9feaac4bdcd494d/src/MIDebugEngine/Natvis.Impl/Natvis.cs#L561).

**Comment by yhsb2k** [comment]
Hi @WardenGnaw,

Thank you for the link to gnu stl natvis file.
Unfortunately, it doesn't fit to modern gcc 11.1.0, but it gave me few ideas. Now, with little modifications, `<LinkedListItems>` type is working fine:

```xml
    <Type Name="std::__cxx11::list&lt;*&gt;">
        <DisplayString>{{ size={_M_impl._M_node._M_size} }}</DisplayString>
        <Expand>
            <Item Name="size">_M_impl._M_node._M_size</Item>
            <LinkedListItems>
                <Size>_M_impl._M_node._M_size</Size>
                <HeadPointer>(std::__cxx11::list&lt;$T1,$T2&gt;::_Node *)_M_impl._M_node</HeadPointer>
                <NextPointer>_M_next</NextPointer>
                <ValueNode>($T1)_M_storage</ValueNode>
            </LinkedListItems>
        </Expand>
    </Type>
```
