### ISSUE TITLE
vcFormat inserts additional spaces between } and else

### ISSUE THREAD

**Issue by Aegel5** [microsoft/vscode-cpptools#7731]
Bug type: Language Service

**Describe the bug**
OS and Version: NT 10.0.19042
VS Code Version: 1.57.1
C/C++ Extension Version: 1.5.0-insiders

**Steps to reproduce**
1. Open a.cpp source file with settings.json
2. Right-click on the document -> select _Format Document_
3. Additional 4 spaces would be inserted between `}` and `else`

**Expected behavior**
1. After _Format Document_ additional spaces must not be inserted.

a.cpp
```
void f(int a) {
    if (a > 0) {}
    else {}
}
```

settings.json
```
{
    "editor.formatOnType": true,
    "C_Cpp.formatting": "vcFormat",
    "C_Cpp.vcFormat.newLine.beforeElse": false,
    "editor.formatOnPaste": true
}
```
a.cpp after format
```
void f(int a) {
    if (a > 0) {}     else {}
}
```

**Comment by alexzh2** [comment]
Another example. Before:
```
void f(int a) {
    if (a > 0) {
    }
    else {
    }
}
```
After:
```
void f(int a) {
    if (a > 0) {
    }     else {
    }
}
```

**Comment by Colengms** [comment]
Hi @alexzh2 . I'm not able to easily repro the issue.  With files containing only your example code, and with only the settings you provided, I do not see the extra spaces after I format the document.  Are you sure you do not have another extension installed that may also be trying to provide formatting?

Could you try setting `"C_Cpp.loggingLevel": "Debug"`, and provide the output of the C/C++ output channel after you format the document?  That should have some additional information about the formatting operation.

**Comment by sean-mcmanus** [comment]
@Colengms I repro it. It requires     "C_Cpp.vcFormat.newLine.beforeElse": false,

**Comment by Colengms** [comment]
Thanks @sean-mcmanus .  It looks like I had a `.editorconfig` file which was taking precedence.

@alexzh2 .  I can repro your issue in VS as well.  (We shared common code for formatting with VS, when using vcFormat).  I opened a bug against VS here: https://developercommunity.visualstudio.com/t/incorrect-c-formatting-when-place-else-on-a-new-li/1456310

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders .
