### ISSUE TITLE
browse.path is incorrect if an invalid compileCommands is used ("Go to definition" doesn't work until file with definition is opened once)

### ISSUE THREAD

**Issue by Diadlo** [microsoft/vscode-cpptools#7737]
Bug type: Language Service

**Describe the bug**
- OS and Version: Arch Linux
- VS Code Version: 1.56.0-insider
- C/C++ Extension Version: v1.5.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): N/A
- If using SSH remote, specify OS of remote machine: SSH remote on Arch Linux

**Steps to reproduce**
1. Open workspace
2. Reset IntelliSense database
3. Open one file with source code
4. Find a function call that refers to a function outside of the current file.
5. Click "Go to definition"
6. See that declaration is opened
7. Open and close the file with the definition
8. Click "Go to definition" again
9. See that definition is opened

**Expected behavior**
The function definition is opened on first click too

**Code sample and logs**

In the logs below filenames and paths are changed.
* `foo.c` is file that calls `bar()`
* `bar.h` is the header, that declares `bar()` function
* `bar.c` is file that defines `bar()` function

----

- Configurations in `c_cpp_properties.json`

```
{
    "env": {},
    "configurations": [
        {
            "name": "Linux",
            "intelliSenseMode": "linux-clang-arm",
            "includePath": [
                "${workspaceFolder}/include",
                // other project-releated includes
            ],
            "defines": [],
            "forcedInclude": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c89",
            "cppStandard": "c++17",
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ".vscode/browse.db"
            },
            "compilerArgs": [
                "-O3",
                "-pipe",
                "-W",
                "-Wall",
                "-Wpointer-arith",
                "-Wcast-align",
                "-std=gnu99",
                "-pedantic",
                "-Wformat=0",
                "-Wno-format-zero-length",
                "-Wno-unused-but-set-variable",
                "-Wdeclaration-after-statement",
                "-Wformat",
                "-fno-strict-aliasing",
                "-fshort-enums",
                "-fPIC",
                "-funwind-tables"
            ]
        }
    ],
    "version": 4
}

```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

```
-------- Diagnostics - 6/22/2021, 8:22:36 PM
Version: 1.5.0-insiders2
Current Configuration:
{
    "name": "Linux",
    "intelliSenseMode": "linux-clang-arm",
    "includePath": [
        "${workspaceFolder}/include",
        // other includes
    ],
    "defines": [
    ],
    "forcedInclude": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c89",
    "cppStandard": "c++17",
    "browse": {
        "path": [
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": ".vscode/browse.db"
    },
    "compilerArgs": [
        "-O3",
        "-pipe",
        "-W",
        "-Wall",
        "-Wpointer-arith",
        "-Wcast-align",
        "-std=gnu99",
        "-pedantic",
        "-Wformat=0",
        "-Wno-format-zero-length",
        "-Wno-unused-but-set-variable",
        "-Wdeclaration-after-statement",
        "-Wformat",
        "-fno-strict-aliasing",
        "-fshort-enums",
        "-fPIC",
        "-funwind-tables"
    ],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compileCommands": "${workspaceFolder}/compile_commands.json"
}
Translation Unit Mappings:
[ /path/to/foo.c ]:
    /path/to/foo.c
    /path/to/bar.h
Translation Unit Configurations:
[ /path/to/foo.c ]:
    Process ID: 4030958
    Memory Usage: 55 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /path/to/include
    Defines:
    Standard Version: c99
    IntelliSense Mode: linux-gcc-arm
    Other Flags:
        --gcc
        --gnu_version=40603
Total Memory Usage: 55 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 1705
```

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

```
Checking for syntax errors: file:///path/to/foo.c
Queueing IntelliSense update for files in translation unit of: /path/to/foo.c
cpptools/getCodeActions: file:///path/to/foo.c (id: 2)
cpptools/activeDocumentChange: file:///path/to/foo.c
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///path/to/foo.c (id: 3)
cpptools/getDocumentSymbols
cpptools/getCodeActions: file:///path/to/foo.c (id: 4)
cpptools/getFoldingRanges: file:///path/to/foo.c (id: 5)
cpptools/getSemanticTokens: file:///path/to/foo.c (id: 6)
cpptools/finishUpdateSquiggles
Error squiggle count: 0
terminating child process: 4031004
Update IntelliSense time (sec): 0.57
cpptools/getCodeActions: file:///path/to/foo.c (id: 7)
cpptools/activeDocumentChange: file:///path/to/foo.c
cpptools/textEditorSelectionChange
textDocument/hover: file:///path/to/foo.c (id: 8)
cpptools/activeDocumentChange: file:///path/to/foo.c
cpptools/textEditorSelectionChange
textDocument/hover: file:///path/to/foo.c (id: 9)
textDocument/hover: file:///path/to/foo.c (id: 10)
textDocument/definition: file:///path/to/foo.c (id: 11)
cpptools/getCodeActions: file:///path/to/bar.h|% (id: 12)
textDocument/didOpen: file:///path/to/bar.h|%
Checking for syntax errors: file:///path/to/bar.h|%
Queueing IntelliSense update for files in translation unit of: /path/to/foo.c
cpptools/activeDocumentChange: file:///path/to/bar.h|%
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///path/to/bar.h|% (id: 13)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
  tag parsing file: /path/to/bar.h|%
textDocument/documentHighlight: file:///path/to/bar.h|% (id: 14)
cpptools/getSemanticTokens: file:///path/to/bar.h|% (id: 15)
cpptools/getCodeActions: file:///path/to/bar.h|% (id: 16)
cpptools/getFoldingRanges: file:///path/to/bar.h|% (id: 17)
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Error squiggle count: 0
terminating child process: 4031137
Update IntelliSense time (sec): 0.257
cpptools/getCodeActions: file:///path/to/bar.h|% (id: 18)
textDocument/hover: file:///path/to/bar.h|% (id: 19)
cpptools/getSemanticTokens: file:///path/to/foo.c (id: 20)
cpptools/getCodeActions: file:///path/to/bar.h|% (id: 21)
textDocument/hover: file:///path/to/bar.h|% (id: 22)
Database safe to open
```

Some info from the database:

```
$ sqlite3 .vscode/browse.db 'SELECT * FROM code_items WHERE name="bar";'
8|1706|0|22|1|bar|int |1|45|75|45|10|45|30|45|||||||bar

$ sqlite3 .vscode/browse.db 'SELECT * FROM files WHERE id=1706;'  
1706|1621580740|0.0|0.0|0.0|/path/to/bar.h|bar.h|0|00000000000000000000000000000000
```

**Comment by Colengms** [comment]
Hi @Diadlo . Go To Definition leverages the tag parser database.  In your repro steps, it looks like you are resetting that database. Based on your log, it look like it has not yet finished repopulating.  It shows that it has started parsing files: `tag parsing file: /path/to/bar.h|%`.  But, tag parsing is not complete until the following is logged:
```
  Parsing: X files(s) processed
Done parsing remaining files.
```

The `Database safe to open` may be a bit misleading.

Does the issue still repro if you wait for that log output before using Go To Definition?

**Comment by Diadlo** [comment]
@Colengms How long should it take? My VSCode was opened for 10 hours and in the language server log I see only this:

```
[...]
Database safe to open
cpptools/getCodeActions: file:///path/to/bar.h (id: 18)
cpptools/activeDocumentChange: file:///path/to/bar.h
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///path/to/bar.h (id: 19)
cpptools/getCodeActions: file:///path/to/bar.h (id: 20)
cpptools/getCodeActions: file:///path/to/foo.c (id: 21)
cpptools/activeDocumentChange: file:///path/to/foo.c
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/getFoldingRanges: file:///path/to/foo.c (id: 22)
cpptools/getCodeActions: file:///path/to/foo.c (id: 23)
idle loop: reparsing the active document
Checking for syntax errors: file:///path/to/foo.c
Queueing IntelliSense update for files in translation unit of: /path/to/foo.c
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Error squiggle count: 0
Update IntelliSense time (sec): 0.278
cpptools/getSemanticTokens: file:///path/to/bar.h (id: 24)
cpptools/getSemanticTokens: file:///path/to/foo.c (id: 25)
textDocument/hover: file:///path/to/foo.c (id: 26)
textDocument/hover: file:///path/to/foo.c (id: 27)
textDocument/hover: file:///path/to/foo.c (id: 28)
textDocument/hover: file:///path/to/foo.c (id: 29)
cpptools/activeDocumentChange: file:///path/to/foo.c
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: file:///path/to/foo.c (id: 30)
cpptools/getCodeActions: file:///path/to/foo.c (id: 31)
textDocument/didClose: file:///path/to/bar.h
cpptools/getCodeActions: file:///path/to/foo.c (id: 32)
cpptools/activeDocumentChange: file:///path/to/foo.c
cpptools/textEditorSelectionChange
cpptools/textEditorSelectionChange
textDocument/documentHighlight: file:///path/to/foo.c (id: 33)
cpptools/getFoldingRanges: file:///path/to/foo.c (id: 34)
cpptools/getCodeActions: file:///path/to/foo.c (id: 35)
textDocument/hover: file:///path/to/foo.c (id: 36)
cpptools/getDiagnostics (id: 37)
terminating child process: 4173058
terminating child process: 4173059
cpptools/activeDocumentChange: file:///path/to/foo.c
cpptools/textEditorSelectionChange
```

**Comment by Colengms** [comment]
Hi @Diadlo .  Your last log does not include `tag parsing file` I assume it starts after tag parsing has completed.  Does the problem occur after tag parsing is complete?

I can't easily repro an issue with a simple header and a source file.

test.cpp
```cpp
#include "test.hpp"

void foo()
{
}
```

test.hpp
```cpp
void foo();
```

After running `Reset IntelliSense database` and waiting for parsing to complete, then opening test.hpp and doing a Go To Definition on foo, test.cpp is opened (having not been opened before).  I also tried putting the definition in a source other than the one associated with the header (in Log Diagnostics), but that still correctly opened the source with the definition. Perhaps there is something else specific to your scenario that we would need to know to repro the issue?  It's possible there is some code involved in one of those files that the tag parser is failing to parse properly.

**Comment by Diadlo** [comment]
@Colengms Unfortunately, I can reproduce this error only on one machine with a remote SSH connection. Even with simple projects like this one: https://github.com/Diadlo/test_vscod. I've tried to create an SSH connection to my PC. And everything works fine.

**Comment by sean-mcmanus** [comment]
Logging shows the ${workspaceFolder} is not being processed as part of the browse.path, most likely due to your compile_commands.json:
```
Discovering files...
  Processing folder (recursive): ${workspaceFolder}
```

Are you able to repro the issue without the compileCommands set? Can you check your compile_commands.json file to make sure it references something in the ${workspaceFolder}?

**Comment by sean-mcmanus** [comment]
Oh, I don't see compileCommands set in your c_cpp_properties.json -- so I'm guessing it's set via C_Cpp.default.compileCommands in your remote or workspace settings?

**Comment by Diadlo** [comment]
@sean-mcmanus I haven't `compile_commands.json`. And it doesn't seem to be set (maybe I missed something).

defaultSettings.json
```
	// The value to use in a configuration if "compileCommands" is either not specified, or set to "${default}".
	"C_Cpp.default.compileCommands": "",
```

user settings
```
{
    "task.problemMatchers.neverPrompt": {
        "shell": true
    },
    "files.trimTrailingWhitespace": true,
    "editor.tabSize": 2,
    "C_Cpp.updateChannel": "Insiders",
    "files.insertFinalNewline": true,
    "cortex-debug.JLinkGDBServerPath": "/usr/bin/JLinkGDBServerCLExe",
    "C_Cpp.loggingLevel": "Debug",
}
```

Workspace settings
```
{
  "files.associations": {
    // Some associations
  },
  "C_Cpp.dimInactiveRegions": false
}
```

**Comment by sean-mcmanus** [comment]
Ah, I recall we have code that will automatically set compileCommands if we detect it -- can you delete that file?

**Comment by Diadlo** [comment]
@sean-mcmanus But there is no `compile_commands.json` :(

Maybe useful somehow. Message from "C/C++" Configuration Warnings window:

```
[6/28/2021, 11:36:43 PM] "${workspaceFolder}/compile_commands.json" could not be found. 'includePath' from c_cpp_properties.json in folder 'test_vscode' will be used instead.
```

**Comment by sean-mcmanus** [comment]
Yeah, I repro the issue now via adding a non-existent compileCommands. Are you able to workaround the bug via removing the compileCommands reference somehow or do you not know how that is getting set...or setting it explicitly to ""?

**Comment by Diadlo** [comment]
It seems I can workaround the issue by setting `compileCommands` explicitly to "" in my `c_cpp_properties.json`. Thank you!

**Comment by Colengms** [comment]
Hi @Diadlo @sean-mcmanus .  I don't believe the C/C++ Extension would be automatically detecting a `compile_commands.json`.  @Diadlo , if not in `c_cpp_properties.json`, is it possible you have `C_Cpp.default.compileCommands` set in global or workspace settings?  If so, the fix would seem to be to remove that setting.  It shouldn't be necessary to set `compileCommands` explicitly to `""` in `c_cpp_properties.json`.

**Comment by Diadlo** [comment]
@Colengms As I [said above](https://github.com/microsoft/vscode-cpptools/issues/7737#issuecomment-869483083), `C_Cpp.default.compileCommands` is set to "".

Also, I think if settings refer to non-existing `compile_commands.json` it should be ignored. And tag parser should be used instead.

https://user-images.githubusercontent.com/6306608/124067082-7032b480-da42-11eb-908e-851d7bcd6dcb.mp4

**Comment by sean-mcmanus** [comment]
With https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0-insiders3 the invalid compileCommands won't break the browse.path.

**Comment by Diadlo** [comment]
@sean-mcmanus With v1.5.0-insiders3 it works. So I'm going to close the issue. Thanks!
