### ISSUE TITLE
`cannot open source file "alloca.h" C/C++(1696)`

### ISSUE THREAD

**Issue by AaronRecord** [microsoft/vscode-cpptools#7742]
Bug type: Language Service

*Might be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/7740, but that issue didn't provide very much information.*

**Describe the bug**
- OS and Version: **Windows 10**
- VS Code Version: **1.57.1**
- C/C++ Extension Version: **1.4.1**
- Other extensions you installed (and if the issue persists after disabling them): **Don't think it's related to other extensions.**
- If using SSH remote, specify OS of remote machine: **n/a**
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
<hr>

I'm using vscode with https://github.com/godotengine/godot, and I'm getting these error in most of my files:
`cannot open source file "alloca.h" (dependency of [...]) C/C++(1696)`.
I'm using msvc-x64.
Everything compiles and builds successfully (using scons).
<details>
  <summary>tasks.json</summary>

```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "scons",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "args": [
                "platform=windows",
                "target=debug",
                "-j4"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
```
</details>

**Steps to reproduce**

1. Go to [platform/android/platform_config.h](https://github.com/godotengine/godot/blob/master/platform/android/platform_config.h#L31)
2. See error

**Expected behavior**

To not get an error.

**Code sample and logs**

- Code sample
`#include <alloca.h>`
- Configurations in `c_cpp_properties.json`
<details>
  <summary>c_cpp_properties.json</summary>

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
```
</details>

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

<details>
  <summary>Log</summary>

```
-------- Diagnostics - 6/23/2021, 11:53:58 AM
Version: 1.4.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compilerPathIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "macFrameworkPath": [],
    "compilerArgs": [],
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Me\Projects\GodotSource\godot\scene\gui\scroll_container.cpp ]:
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\SCENE\GUI\SCROLL_CONTAINER.CPP
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\SCENE\GUI\SCROLL_CONTAINER.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\SCENE\GUI\CONTAINER.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\SCENE\GUI\CONTROL.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\CORE\MATH\TRANSFORM_2D.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\CORE\MATH\RECT2.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\CORE\MATH\VECTOR2.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\CORE\MATH\MATH_FUNCS.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\CORE\MATH\RANDOM_PCG.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\THIRDPARTY\MISC\PCG.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\CORE\TYPEDEFS.H
    C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\PLATFORM\ANDROID\PLATFORM_CONFIG.H
Translation Unit Configurations:
[ C:\Users\Me\Projects\GodotSource\godot\scene\gui\scroll_container.cpp ]:
    Process ID: 2676
    Memory Usage: 118 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.28.29910\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.28.29910\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\CPPWINRT
        C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT
        C:\USERS\Me\PROJECTS\GODOTSOURCE\GODOT\PLATFORM\ANDROID
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 118 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 14712

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: C:/Users/Me/Projects/GodotSource/godot/core/image.h
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/thirdparty/oidn"
Using: C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/ucrt/math.h
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/thirdparty/oidn/core"
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/thirdparty/embree/common/math"
Using: C:/Users/Me/Projects/GodotSource/godot/platform/android/platform_config.h
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/platform/iphone"
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/platform/javascript"
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/platform/osx"
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/platform/uwp"
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/platform/windows"
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/platform/server"
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/platform/x11"
Using: C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/ucrt/string.h
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/modules/gdnative/include/gdnative"
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/thirdparty/embree/common/sys"
Using: C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/ucrt/time.h
    Alternative: "C:/Users/Me/Projects/GodotSource/godot/thirdparty/enet/enet"

```
</details>

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
**n/a?**

**Screenshots**

![image](https://user-images.githubusercontent.com/50304111/123145366-000ca900-d41a-11eb-9be0-d04cf2b2f18c.png)

**Additional context**

**Comment by Colengms** [comment]
@LightningAA `alloc.h` is a linux system header.  There is no system header with this name for Windows.  It looks like you are trying to build for android, on Windows, is that correct?  If so, I imagine there is some configuration necessary to inform the C/C++ Extension of android system include paths.  Could you post the content of your `c_cpp_properties.json` containing that configuration?  If you are using a build system such as CMake or makefiles, consider using the CMake Tools or Makefile Tools extensions, as those provide configuration information to the C/C++ Extension directly from your build system.

**Comment by LightningAA** [comment]
1) I'm trying to build for windows, not android
2) I already did include my `c_cpp_properties.json`

See https://github.com/godotengine/godot/blob/master/core/typedefs.h#L41

There are multiple `platform.h`s, I'm guessing that's the problem is that it's including the wrong one, although I'm not sure yet.

**Comment by Colengms** [comment]
@LightningAA Sorry, I didn't notice the collapsed sections.

The build system is probably providing some defines that you would need to provide in your `c_cpp_properties.json` in order for the C/C++ Extension to chose the same conditional source code and header files, etc..  I'm not familiar with godot.  You might have better luck asking the godot community what those defines should be.  Perhaps: https://docs.godotengine.org/

I did find this example: https://gist.github.com/neikeq/8cc43c3c8ce88d7ddc8c59a5308c0847

**Comment by LightningAA** [comment]
I discussed this with some people who know more about godot etc., apparently this is a limitation of msvc or something like that (it's probably not a problem with the language extension)? Adding `${workspaceFolder}/platform/windows` fixed it though.
