### ISSUE TITLE
cpptools doesn't look at .gitignore, it's cumbersome to add them one by one in large repo

### ISSUE THREAD

**Issue by pansila** [microsoft/vscode-cpptools#7743]
> Our extension doesn't look at .gitignore. Did you want to file a feature request for that or is adding the folders you want to ignore to C_Cpp.files.exclude sufficient?

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode-cpptools/issues/7408#issuecomment-825139877_

I'm working on a project based on `buildroot`, it's a giant project with tons of thousands of files. But most of files can be ignored, they are defined in the different `.gitignore` files scattered in the subdirectories of packages.

I listed all files in the project as following compared to the result of filtered files.
```
$ fd -H -t f -I |wc -l
573904
$ fd -H -t f|wc -l
158034
```

cpptools can filter files somehow in the discovering stage.
```
File exclude: **/.vscode
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
File exclude: **/VDK_Linux_Build/mini-aarch64-linux/buildroot-2018.02.1
File exclude: **/VDK_Linux_Build/mini-aarch64-linux/output
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
  Discovering files: 127790 file(s) processed
Done discovering files.
```
But the database parsing icon in the status bar keeps tipping that it's discovering many more files, like
![图片](https://user-images.githubusercontent.com/5125601/123220920-fad65980-d500-11eb-92f2-a536c231d475.png)
When it finished, it drops to a smaller number but is still more than one of filtered files.
![图片](https://user-images.githubusercontent.com/5125601/123221125-2f4a1580-d501-11eb-9f75-dbdcd338a426.png)

### Code sample and logs
* Logs from running C/C++: Log Diagnostics from the VS Code command palette
```
-------- Diagnostics - 6/24/2021, 3:31:54 PM
Version: 1.4.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/VDK_Linux_Build/mini-aarch64-linux/buildroot-2021.02/xxx_override/linux-5.10.25/include"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${workspaceFolder}/VDK_Linux_Build/mini-aarch64-linux/buildroot-2021.02/xxx_override/linux-5.10.25/include"
        ],
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": "/aaa/bbb/uuu/.config/vscode/ms-vscode.cpptools/.browse.VC.db"
    }
}
No active translation units.

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 522023
```

**Comment by sean-mcmanus** [comment]
Ok. If this were implemented, it might also be good to add a setting to disable the .gitignore filtering for projects that generate temporary build files that shouldn't be checked in but which have important global symbols.
