### ISSUE TITLE
> The text "squiggles are disabled" is incorrect is the errorSquiggles setting is "Enabled" (it's correct if the setting is "EnabledIfIncludesResolve".

### ISSUE THREAD

**Issue by madhukan1106** [microsoft/vscode-cpptools#7744]
> The text "squiggles are disabled" is incorrect is the errorSquiggles setting is "Enabled" (it's correct if the setting is "EnabledIfIncludesResolve".
> 
> The error occurs when a `#include` header can't be found. You could try using the C/C++: Log Diagnostics command to see if the paths are setup correctly.
> 
> There is no way to remove that particular error, unless all errors are removed via the errorSquiggles "Disabled" setting.

Hi Sean,

I set the errorSquiggles to 'Enabled' and the error still occur. And there is no errors in output window after I use 'Log Diagnostics'.

![1](https://user-images.githubusercontent.com/39362073/60377562-e1ea5900-9a4a-11e9-824f-1765435e4c0c.PNG)

And output as follow:

`-------- Diagnostics - 2019/6/29 上午8:43:44
Version: 0.24.0-insiders3
Translation Unit Mappings:
[D:\Lennon\xxxx\xxxx.c]:
    D:\LENNON\xxxx\xxxx.C
Translation Unit Configurations:
[D:\Lennon\xxxx\xxxx.c]:
    Process ID: 8504
    Memory Usage: 366 MB
    Includes:
        ....(FilePath)
    Standard Version: c11
    IntelliSense Mode: clang-x64
    Other Flags:
        --clang
        --clang_version=50000
Total Memory Usage: 366 MB

`

_Originally posted by @Lennon925 in https://github.com/microsoft/vscode-cpptools/issues/3852#issuecomment-506913181_

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0-insiders3
