### ISSUE TITLE
Intellisense Support for C++20 `concept`

### ISSUE THREAD

**Issue by mfs409** [microsoft/vscode-cpptools#7746]
Type: Feature Request

(This is somewhat related to  #1946, but since it doesn't relate to UI, I'm presenting it as a new request.  I mistakenly posted it to the VSCode main issue tracker at <https://github.com/microsoft/vscode/issues/127123>, but was advised to move it here.)

Historically, even in very simple C++ code, the use of templates limits IntelliSense's ability to give good documentation.  For example, consider this code:
```c++
template <class T>
class MyClass {
  T myT;
  void myMethod() {
    if (myT.explode(42)) { 
      std::cout << "boom" << std::endl; 
    }
  }
};
```
There isn't any pop-up documentation when I hover over `explode(42)`.  This is, of course, an expected behavior, since the type of `T` is not known.  It could be thought of as the cost of compile-time generics.

However, with the arrival of concepts in C++20, it seems like if I put doxygen-style comments into the concept declaration, then IntelliSense might be able to pick them up.  For example, suppose I were to provide the following concept code:

```c++
template <typename T>
concept Explodable = requires(T a, int i) {
  {/// `Documentation for the explode() method`
   ///
   /// @param duration `Documentation for the duration argument`
   ///
   /// @return `Documentation for the return value`
   a.explode(i)};
};
```

Then suppose I used it in when declaring `MyClass`:
```c++
template <Explodable T>
class MyClass {
  T myT;
  void myMethod() {
    if (myT.explode(42)) { 
      std::cout << "boom" << std::endl; 
    }
  }
};
```

It would be very helpful if hovering over `explode` in this code would give a pop-up with "`Documentation for the explode() method`"

I'm not sure if this feature is possible.  If it is, I suspect that in addition to providing developers with better documentation, it would also incentivize the use of concepts more broadly.

**Comment by sean-mcmanus** [comment]
I'm not able to repro the issue with Windows/cl or Linux/gcc -- can you provide more repro info? Can you run C/C++: Log Diagnostics and verify it shows info such as
```
    Standard Version: c++20
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=100300
```
or similar info for clang or cl.exe?

![image](https://user-images.githubusercontent.com/19859882/123477034-57458180-d5b2-11eb-8af8-584081ac6337.png)

**Comment by mfs409** [comment]
Thanks!  The diagnostics are indicating that I have not have configured something that needs to be configured:

```json
-------- Diagnostics - 7/12/2021, 11:00:56 PM
Version: 1.5.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.
```

**Comment by mfs409** [comment]
Marking closed.  I used `C/C++: Edit Configurations (JSON)` from the command palette to change to C++20, and the problem resolved.
