### ISSUE TITLE
Can not use ${execPath} in c_cpp_properties.json file!

### ISSUE THREAD

**Issue by fiveight58** [microsoft/vscode-cpptools#7753]
Bug type: Language Service

**Describe the bug**
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:03:00.337Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT ia32 6.1.7601

**Steps to reproduce**

In c_cpp_properties.json file, I can use ${workspaceFolder}, But I can not use ${execPath}! Why?Thanks!

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Looks like the the variables that got added by VS Code later on haven't been added (https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/variables-reference.md) and we only handle some of the older ones: https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/common.ts#L310

**Comment by bobbrow** [comment]
Of those variables documented, I think only `${execPath}` and `${pathSeparator}` are the only ones that make sense in the context of c_cpp_properties.json

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
