### ISSUE TITLE
Unable to use non exe file clang-format under Windows

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode-cpptools#7755]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.17763
- VS Code Version: 1.57.1 (system setup)
- C/C++ Extension Version: v1.5.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): N/A
- If using SSH remote, specify OS of remote machine: N/A
- Unable to use non-exe file as the clang-format executable in setting "C_Cpp.clang_format_path". I would like to use a python script there so I can hook it into our code formatter (which will use clang-format under hood).

**Steps to reproduce**

1. Format Document on C++/C file
4. C/C++ output:
Formatting failed:
\<removed\>/clang-format.py -style="file" -fallback-style="LLVM" -assume-filename="\<removed\>.cpp"
Unable to start child process!

**Expected behavior**
Python script is run and arguments are passed to it.

**Code sample and logs**
N/A

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
See above

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
Not collected. Didn't think relevant.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by BillDenton** [comment]
Found that ".bat" file works. The ".bat" file uses py to run the python code.

**Comment by sean-mcmanus** [comment]
Is that a sufficient workaround? We expect it to be a file that is directly executable as a process.

**Comment by BillDenton** [comment]
@sean-mcmanus Yes, that is sufficient. I didn't think of that at the start. I close the issue.
