### ISSUE TITLE
Generate IntelliSense results progressively

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#7759]
Currently, the C/C++ Extension will process an entire translation unit before returning results (squiggles) for a file.  Those results are monolithic.  When a new set is generated, they replace the prior set.

My understanding is that VS will generate IntelliSense results progressively.  It will return an initial block of results after having parsed up until the end of the currently visible region of the file, in order to populating the visible area as quickly as possible.  Then it will progressively populate the rest of the file, potentially in multiple sections, allowing squiggles to show up more or less as they are determined.

This issue is tracking doing something similar in the C/C++ Extension, instead of always processing an entire file at a time.

Other features, such as "Creating Definition from Declaration (and vice versa)", are implemented in a similar progressive manner in VS.  We could also implement that feature in the extension by processing the entire file, but it may be worthwhile to establish some patterns for returning progressive results that could be used by both features.

**Comment by bobbrow** [comment]
This potentially addresses #3626
