### ISSUE TITLE
"xxxxxx/a.cpp" is misssing or in valid.

### ISSUE THREAD

**Issue by spursy** [microsoft/vscode-cpptools#776]
after I create a new a.cpp and configure for C++ demo project.
Press F5, VSCode display "Unable to start debugging. Program path xxxxxxx\a.cpp" is misssing or in valid.

My a.cpp file is like the followed:
`#include <iostream> 
using namespace std; 

int main() { 
    cout<<"Hello World!"<<endl; 
}`

**Comment by pieandcakes** [comment]
@spursy It looks like you have a `*.cpp` file instead of an executable in your program field. Please compile your program with the symbols (`-g` when using g++) and then set the output of your compilation in the program path.
