### ISSUE TITLE
breakpoints not hit

### ISSUE THREAD

**Issue by Shirhe-Lyh** [microsoft/vscode-cpptools#7761]
Bug type: Debugger

**Describe the bug**
- OS and Version: win7 SP1
- VS Code Version: **VSCodeUserSetup-x64-1.57.1
- C/C++ Extension Version: v1.4.1
- Other extensions you installed (and if the issue persists after disabling them): Code Runner 0.11.4
- MinGW: x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z

When i **Start debugging** the following simple code:

![image](https://user-images.githubusercontent.com/33980058/124126209-06032980-daad-11eb-93ad-00a0b8c968b4.png)

it hits no breakpoint, and nothing prints out but builds successfully:

![image](https://user-images.githubusercontent.com/33980058/124126635-74e08280-daad-11eb-8d3b-e3bf4fc7d725.png)

Moreover, it is very surprising to note that no logs in the **DEBUG CONSOLE**:

![image](https://user-images.githubusercontent.com/33980058/124127578-7a8a9800-daae-11eb-92a6-59f59ea82282.png)

**My configurations**

+ tasks.json:
```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "D:\\MinGW\\mingw64\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

+ launch.json:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gdb (Launch)",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "D:\\MinGW\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++.exe build active file",
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
            }
        }
    ]
}
```

**Other Info**

When i debugging in win10 with the same configurations, all goes well.

**Comment by WardenGnaw** [comment]
The debug adapter has a minimum requirement of using .NET Framework v4.6.2.

What version of .NET Framework do you have installed on that Windows 7 machine? You can find out the version installed with: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#detect-net-framework-45-and-later-versions

**Comment by Shirhe-Lyh** [comment]
> The debug adapter has a minimum requirement of using .NET Framework v4.6.2.
> 
> What version of .NET Framework do you have installed on that Windows 7 machine? You can find out the version installed with: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#detect-net-framework-45-and-later-versions

@WardenGnaw Thanks so much. After installed the latest version of .NET Framework 4.8, the **Start Debugging** function is normal. (By the way, a new negligible issue is raised: **Run Without Debugging** also hits breakpoint.)
