### ISSUE TITLE
"reset intellisense" doesn't update compiler path

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-cpptools#7764]
Issue Type: <b>Bug</b>

I have changed my compiler path and reset the intellisense database. however, the extension debug output still shows it using the old compiler path, and grepping for the old compiler path in my .vscode directory still shows matches in .browse.VC.db.

Extension version: 1.4.1
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (12.02GB free)|
|Process Argv|--crash-reporter-id 70645636-42ae-4864-b371-1810b42a2956|
|Screen Reader|no|
|VM|29%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.35GB (13.71GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
binariesv615:30325510
aatestflight:30331711

```

</details>

**Comment by Colengms** [comment]
Hi @Spongman .  Are you referring to having changed the value of `compilerPath` in your `c_cpp_properties.json`?  If so, the change to that setting should occur immediate after you've made it.  It shouldn't be necessary to reset the IntelliSense database for that change to take effect.  However, it's also unclear to me why you would see your compiler path in your browse database.  I don't believe it would be stored there.  Perhaps we are seeing paths to system includes there?  If those appear to be incorrect, it's possible that the new compiler path you have set could not be queried and the extension fell back to another compiler.

Could you try enabling `"C_Cpp.loggingLevel": "Debug"` and providing the output of your C/C++ Output channel when repro'ing the issue?  That may provide some insights into whether the compiler is being used as specified.  Also, can you provide more information on the paths in that (SQLite) DB are you seeing that appear to be incorrect, or functionality that is not working as expected?

**Comment by Spongman** [comment]
no, i just changed `C_Cpp.default.compilerPath` in my machine-level `settings.json`. that's where the settings dialog took me.

**Comment by sean-mcmanus** [comment]
The C_Cpp.default.compilerPath may be overwritten by another source. Do you have a c_cpp_properties.json? If there was some problem querying the compiler, it could also fall back to a different one. Your logging could help determine what is going on.

**Comment by Spongman** [comment]
i don't have a `c_cpp_properties.json` file. I couldn't wait. i deleted everything on the remote machine and started over from scratch, it looks like it's working now, so it much have been some ephemeral condition causing the bug.
