### ISSUE TITLE
Compilers under C:\Program Files\LLVM\bin, C:\Program Files (x86)\LLVM\bin aren't auto-detected

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7767]
Follow up to https://github.com/microsoft/vscode-cpptools/issues/6718 .

Downloads installed from https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.0 . I was hitting some issue with Windows Defender thinking the installers contained a virus.

Maybe this can make it into 1.5.0 if it's not a risky fix.

**Comment by Colengms** [comment]
This should be addressed in 1.6.0-insiders.
