### ISSUE TITLE
error n warning not working 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-cpptools#777]
_From @aKEERTHICPD15 on May 25, 2017 16:48_

- VSCode Version: 1.12.1 n 1.13.0-INSIDER
- OS Version:WINDOWS 8 64 BIT

Steps to Reproduce:

1.no error is showing in C program even i made a mistake
2. its not showning output

_Copied from original issue: Microsoft/vscode#27282_

**Comment by roblourens** [comment]
Have you installed the C++ extension?

**Comment by roblourens** [comment]
_From @aKEERTHICPD15 on May 26, 2017 8:3_

yes i have c++ , c# extension

**Comment by roblourens** [comment]
_From @aKEERTHICPD15 on May 26, 2017 8:20_

![12121](https://cloud.githubusercontent.com/assets/17075732/26486776/3852c3da-421a-11e7-89f2-32ace88505e8.JPG)

**Comment by sean-mcmanus** [comment]
@aKEERTHICPD15 We changed the default IntelliSenseEngine setting back to "Tag Parser" in 0.11.2. You need to change the setting to "Default" to get errorSquiggles to work.

**Comment by bobbrow** [comment]
My guess is that you have not opened a folder for your workspace.  We do not enable linting underlines for single file edits because there is a high chance that the includePath will not be correct.

@sean-mcmanus, this screenshot is from the Insider build, which should have intelliSenseEngine set to "Default" by default.

**Comment by sean-mcmanus** [comment]
@bobbrow Ah, yeah, you're right.

**Comment by pieandcakes** [comment]
Also, your file needs to have a `.cpp` extension which your screenshot doesn't show.

**Comment by bobbrow** [comment]
@pieandcakes the language is set to C in the status bar at the bottom.

@aKEERTHICPD15, can you confirm whether you have opened a folder for your workspace or not?  I will close this issue based on my earlier guess as this behavior is expected.  Please reopen if my guess is incorrect.
