### ISSUE TITLE
Lags during code editing after saving on remote wsl

### ISSUE THREAD

**Issue by ahemwe** [microsoft/vscode-cpptools#7777]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 1909
- VS Code Version: 1.57.1 (user setup)
- C/C++ Extension Version:1.4.1
- Other extensions you installed (and if the issue persists after disabling them): Overtype, SFTP
- If using SSH remote, specify OS of remote machine: SSH WSL with Ubuntu 18.06
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

Save an open file on remote wsl and directly try to do any kind of edit on this file: Add some letter, copy & paste, ...
In that case. VS does pause for some seconds without any reaction. After that all actions (keystrokes) are done.

**Expected behavior**
Smooth editing experience without any lag.
**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

```
    "configurations": [
        {
            "name": "Win64",
            "includePath": [
                "..."
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "",
            "cStandard": "c11",
            "cppStandard": "c++11",
            "intelliSenseMode": "${default}",
            "compilerArgs": [
                "-fopenmp"
            ]
        },
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/......./**",
                "/opt/ros/melodic/include/**",
                "/usr/include/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "gcc-x64",
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "compilerArgs": [
                "-fopenmp"
            ]
        }
    ],
    "version": 4
}
```

- Logs from Remote Extension:
```
[2021-07-03 17:30:33.163] [exthost] [error] Canceled: Canceled
	at FoldingRangeProvider.<anonymous> (/home/z124089/.vscode-server/extensions/ms-vscode.cpptools-1.4.1/dist/main.js:35700:23)
	at Generator.next (<anonymous>)
	at fulfilled (/home/z124089/.vscode-server/extensions/ms-vscode.cpptools-1.4.1/dist/main.js:35674:58)
[2021-07-03 17:30:42.305] [exthost] [error] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' threw ERROR
[2021-07-03 17:30:42.310] [exthost] [error] Error: timeout
	at Timeout._onTimeout (/home/z124089/.vscode-server/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:84:30165)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[2021-07-03 17:31:10.573] [exthost] [error] [ms-vscode.cpptools] provider FAILED
```

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Does this repro with the C/C++ extension disabled? If so, you should file an issue at https://github.com/microsoft/vscode-remote-release/issues .

**Comment by Colengms** [comment]
Hi @ahemwe .  The log output seems to refer to a timeout in onWillSaveTextDocument.  Could you post the output of the C/C++ Extension leading up to the issue, with the following setting enabled?  `"C_Cpp.loggingLevel": "Debug"`

Depending on the value of the `C_Cpp.formatting`, the timeout is likely due to a format-on-save operation, perhaps delayed due to being blocked behind another slow-running IntelliSense operation.  The log output might help confirm this.

**Comment by ahemwe** [comment]
Hi @Colengms.
Thanks for looking into it. After enabling debug I've switch several times between open tabs and changed the content of a cpp file.

Log:

> File exclude: **/.vscode
File exclude: **/.git
File exclude: **/.svn
File exclude: **/.hg
File exclude: **/CVS
File exclude: **/.DS_Store
Search exclude: **/node_modules
Search exclude: **/bower_components
Search exclude: **/*.code-search
Populate include completion cache.
Discovering files...
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /usr/lib/gcc/x86_64-linux-gnu/7/include/
  Processing folder (recursive): /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /opt/ros/melodic/include/
  Processing folder (recursive): /mnt/c/<..>
  Discovering files: 23717 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 2276 files(s) processed
Done parsing remaining files.
idle loop: reparsing the active document
Checking for syntax errors: file:///mnt/<..>/foo.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/<..>/foo.cpp
Error squiggle count: 0
Update IntelliSense time (sec): 0.903
Offering completion
sending 1 changes to server
Update IntelliSense time (sec): 2
Request canceled: 25
idle loop: reparsing the active document
Checking for syntax errors: file:///mnt/<..>/foo.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/<..>/foo.cpp
sending 1 changes to server
  tag parsing file: /mnt/<..>/foo.cpp
Checking for syntax errors: file:///mnt/<..>/foo.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/<..>/foo.cpp
Request canceled: 37
Offering completion
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
Error squiggle count: 3
Update IntelliSense time (sec): 2.051
idle loop: reparsing the active document
Checking for syntax errors: file:///mnt/<..>/foo.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/<..>/foo.cpp
Error squiggle count: 3
Update IntelliSense time (sec): 1.059
idle loop: reparsing the active document
Checking for syntax errors: file:///mnt/<..>/foo.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/<..>/foo.cpp
Error squiggle count: 3
Update IntelliSense time (sec): 0.262
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
idle loop: reparsing the active document
Checking for syntax errors: file:///mnt/<..>/foo.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/<..>/foo.cpp
sending 1 changes to server
sending 1 changes to server
Error squiggle count: 0
Checking for syntax errors: file:///mnt/<..>/foo.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/<..>/foo.cpp
  tag parsing file: /mnt/<..>/foo.cpp
Error squiggle count: 0
Update IntelliSense time (sec): 3.961
idle loop: reparsing the active document
Checking for syntax errors: file:///mnt/<..>/foo.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/<..>/foo.cpp
Error squiggle count: 0
Update IntelliSense time (sec): 0.815
Request canceled: 79
Offering completion
sending 1 changes to server
sending 1 changes to server
sending 1 changes to server
Update IntelliSense time (sec): 2.011
idle loop: reparsing the active document
Checking for syntax errors: file:///mnt/<..>/foo.cpp
Queueing IntelliSense update for files in translation unit of: /mnt/<..>/foo.cpp
Error squiggle count: 1
Update IntelliSense time (sec): 1.061


It turns out that:
- This delay of 2 s happens not only after saving, but simply after changing tabs.
- This delay also happens on yaml files

**Comment by Colengms** [comment]
Hi @ahemwe .  Could you confirm whether the issue can still repro with the C/C++ Extension disabled?  Extensions should be running asynchronously with regard to the UI in VS Code.  It seems unusual that an extension would cause delay with typing in the UI.  The C++ extension does not provide language services for YAML files.  Is it possible another extension may be involved that activates for YAML files?

In your logs, I see that your file sometimes requires a couple of seconds to complete an IntelliSense update.  And, I see instances of "Offering Completion", which would not complete until a pending IntelliSense pass is completed.  But, I don't think that would explain any delays related to directly to typing or explain delays when switching tabs.  When the delay occurs, is it immediately followed by display of an auto-complete suggestion?

The error related to FoldingRangeProvider can be ignored, and should no longer be occurring with the latest 1.5.0 insiders build.  Does the error related to onWillSaveTextDocument occur every time the delay occurs?  Could you check if using the latest 1.5.0 insiders build results in any change in the issue?

**Comment by sean-mcmanus** [comment]
Also, using a /mnt path to files on the Windows file system is not recommended and could cause performance issues (although I wasn't able to repro the issue described, using the Remote WSL extension, not the Remote SSH extension):

> This workspace is on the Windows file system (/mnt/). For best performance, we recommend moving the workspace to the Linux file system (~/home).

**Comment by ahemwe** [comment]
> Hi @ahemwe . Could you confirm whether the issue can still repro with the C/C++ Extension disabled? Extensions should be running asynchronously with regard to the UI in VS Code. It seems unusual that an extension would cause delay with typing in the UI. The C++ extension does not provide language services for YAML files. Is it possible another extension may be involved that activates for YAML files?

After disabling the C/C++ Extension the issue still occurs.
I've disabled all other (remote) extensions. The the issue is gone. 

Consequently I've checked each and every extension it turns out, that the issue is linked to Overtype (adammaras.overtype)

When disabling this extension and enabling all others, almost no lag is noticeable.

Thanks for your support.
