### ISSUE TITLE
Problems window displays error information out of order

### ISSUE THREAD

**Issue by zajo** [microsoft/vscode-cpptools#778]
In C++, some diagnostic messages are not independent but clarify other errors. For example the error message "animation.cpp:35:5: error: no matching function for call to 'get_float_track'" is followed by the clarifying note: "animation.h:18:8: note: candidate function not viable: no known conversion from 'bool' to 'const float *' for 9th argument".

Unfortunately the Problems window is organized by files not by the order the errors are displayed in Output. This results in the note being displayed by itself under 'animation.h', detached from the error it clarifies, which is displayed separately under 'animation.cpp'.

Please provide an option for the Problems display to be flattened rather than organized by file name. Better yet, provide an option for deleting the Problems display altogether and simply augment the Output with clickable links.

**Comment by sean-mcmanus** [comment]
This is a VS Code issue. See https://github.com/Microsoft/vscode/issues/18685 .
