### ISSUE TITLE
Debugging crashes on "Step Out" and function evaluation

### ISSUE THREAD

**Issue by JoshKaron** [microsoft/vscode-cpptools#7781]
Bug type: Debugger

Hi, I followed this tutorial https://code.visualstudio.com/docs/cpp/config-mingw. and the debugger crashes when I do either of the following:
1) step out of a function
2) evaluate a function in the debug console 

in both cases I get a window that says `gdborig.exe` has stopped working.

- OS and Version: Windows 10
- VS Code Version: 1.57.1
- C/C++ Extension Version: 1.4.1
- Other extensions you installed: None
- Mingw Version: 8.1.0 (installed from link in tutorial)
- g++ Version: 8.1.0
- gdb Version: 8.1

Here is the code:
```
#include <iostream>
#include <vector>
#include <string>

int add(int a, int b) {
	return a + b;
}

int main()
{
    std::vector<std::string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};
    
    for (const std::string& word : msg)
    {
        std::cout << word << " ";
    }
    std::cout << std::endl;

    int x = add(1, 2);
    int y = add(3, 4);
}
```

launch.json and tasks.json were the defaults from the tutorial linked above.

I have tried this on multiple computers and it produces the same result.

also see [this issue](https://github.com/microsoft/vscode-cpptools/issues/103)

Thanks in advance

**Comment by WardenGnaw** [comment]
Can you add 
```
            "logging": {
                "engineLogging": true,
                "traceResponse": true
            },
```
to your launch.json and provide the logging output in the Debug Console?

**Comment by JoshKaron** [comment]
Here is the log when I try to Step Out:

[stepOutLog.txt](https://github.com/microsoft/vscode-cpptools/files/6776111/stepOutLog.txt)

and here is the log when I try to evaluate the function in the debug console:

[evalFuncLog.txt](https://github.com/microsoft/vscode-cpptools/files/6776116/evalFuncLog.txt)

**Comment by JoshKaron** [comment]
Is there any other information I could provide?

**Comment by WardenGnaw** [comment]
From the logs, it seems like GDB is not responding to the debug adapter.
For stepOut, we never receive a stop event and for the evalFunc it never returns the value of `-var-create - * "add(4, 5)"`

This is from the MinGW download from https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download?

**Comment by JoshKaron** [comment]
Yes that is the distribution of MinGW that I am using.

**Comment by JoshKaron** [comment]
Just to be sure I re-installed MinGW from sourceforge and here are the logs:
[stepOutLog.txt](https://github.com/microsoft/vscode-cpptools/files/6839738/stepOutLog.txt)

[evalFuncLog.txt](https://github.com/microsoft/vscode-cpptools/files/6839741/evalFuncLog.txt)
