### ISSUE TITLE
Cannot Execute Program By Click Run

### ISSUE THREAD

**Issue by weimch** [microsoft/vscode-cpptools#7782]
Bug type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 20.04.2 LTS
- VS Code Version: Version: 1.57.1
- C/C++ Extension Version: v1.4.1(aarch64)
- Other extensions you installed (and if the issue persists after disabling them): None
- Create a simple hello world cpp program, just click run, using the default generated launch.json and tasks.json file. Although the build process is triggered, the program seems not be started.(The DEBUG CONSOLE output nothing)

![problem_report](https://user-images.githubusercontent.com/28728444/124388390-52e93900-dd15-11eb-92e1-5e0366addb16.gif)

The hello world program is as below:
```c++
#include <iostream>

int main() {
    std::cout << "hello world" << std::endl;
    return 0;
}
```

The generated 'task.json' is as below:
```json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

The generated 'lanuch.json' is as below:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```

**Comment by sean-mcmanus** [comment]
It's working for me. What does `gdb --version` output? Can you add 
```
            "logging": {
                "engineLogging": true,
                "traceResponse": true
            },
```
to your launch.json and provide the logging output (and/or look for an error there)?

**Comment by lonegamedev** [comment]
The same problem on Windows. The app compiles just fine, can be started manually, won't start through launch config (which means debugging is a no-op).
Temp fix: downgraded to `1.4.1`

**Comment by sean-mcmanus** [comment]
@lonegamedev Linux uses a different debugger, so your issue is most likely https://github.com/microsoft/vscode-cpptools/issues/7808 .

**Comment by lonegamedev** [comment]
@sean-mcmanus I use VS debugger but I think the problem is not with the debugger as such. It won't start even without the debugger attached. I won't pretend like I know what is going on, but for whatever reason, it seems like the app is not starting at all.

**Comment by weimch** [comment]
> It's working for me. What does `gdb --version` output? Can you add
> 
> ```
>             "logging": {
>                 "engineLogging": true,
>                 "traceResponse": true
>             },
> ```
> 
> to your launch.json and provide the logging output (and/or look for an error there)?

Sorry for latter reply.

The gdb version is 9.2
![image](https://user-images.githubusercontent.com/28728444/125049568-b2f42c80-e0d3-11eb-8c4c-ee6adb1990e4.png)

 I have added the config into lanuch.json file. Below are the outputs:
![image](https://user-images.githubusercontent.com/28728444/125050523-9ad0dd00-e0d4-11eb-9fe9-2bbc9c0612d9.png)

**Comment by sean-mcmanus** [comment]
@weimch The debugger logging should appear in the "Debug Console" pane and not the C++ section of the "Output" pane.

**Comment by weimch** [comment]
@sean-mcmanus The 'Debug Console' ouputs nothing.

![Jul-09-2021 16-54-39](https://user-images.githubusercontent.com/28728444/125052291-64945d00-e0d6-11eb-92f4-ff04f2d35174.gif)
