### ISSUE TITLE
Outline of class's methods in a .cpp fie is difficult to read

### ISSUE THREAD

**Issue by zethon** [microsoft/vscode-cpptools#7785]
When working in a .cpp file with lots of methods of the same class, the class name is shown for each method making it difficult to find a method by name. For example:

![image](https://user-images.githubusercontent.com/5203583/124506521-d0ef2380-dd99-11eb-8fad-52ceb5ab163c.png)

Now compare that to viewing the same class's header file:

![image](https://user-images.githubusercontent.com/5203583/124506536-d9475e80-dd99-11eb-818f-1361de9e9a64.png)

It would be great to have the same kind of the view in the .cpp file that we have in the header file.

**Comment by sean-mcmanus** [comment]
Understood.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
