### ISSUE TITLE
Symbol navigation in code sometimes moves to the wrong line

### ISSUE THREAD

**Issue by berlunt** [microsoft/vscode-cpptools#7788]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows_NT x64 10.0.19041
- VS Code Version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
- C/C++ Extension Version:  1.5.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them): 
Extension|Author (truncated)|Version
---|---|---
cppincludeguard|aki|1.4.0
todo-tree|Gru|0.0.213
output-colorizer|IBM|0.1.2
better-cpp-syntax|jef|1.15.6
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.1
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.5.0-insiders3
code-settings-sync|Sha|3.4.3
go-to-method|tri|0.2.0

- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Working on a small project (~10 source files). Every so often it seems that the symbol navigation stops working correctly. When I navigate to a function using 'Go to symbol...' the cursor will be placed at the incorrect line in the file, not where the function signature is as expected. Interestingly, if I close VS code, move the contents of the project elsewhere and then re-open VS Code on the empty folder. Then close VS Code again, put the contents back and re-open. That seems to temporarily fix the issue for a few hours/days. I can only assume the internal symbol database somehow gets out of sync and that manages to trigger it to re-calculate the positions of all of the symbols. I've tried moving/deleting the symbol database file that gets created inside the build directory but that doesn't seem to help. 

Even if there was a way to manually force a refresh of the symbol database without having to move the entire project out of the directory, that would probably be enough to 'fix' this for me.

**Steps to reproduce**

1. Use keyboard shortcut or '#' to initiate a symbol search
2. Begin typing the name of a function
3. Once the desired function appears in the top bar, select the function and hit enter.
4. The cursor will move to the 
[CppDiagnostics.txt](https://github.com/microsoft/vscode-cpptools/files/6775195/CppDiagnostics.txt)
middle of another, unrelated function in the same file.
5. Note: I have only been able to reproduce this in a project that I've been working on for some time. Never in a new project

**Expected behavior**

Expectation is that when selecting a function during symbol search, the cursor will move to the line where the function signature is.

**Comment by berlunt** [comment]
A further note on this, I think it may be to do with something with the files in question being on a remapped drive. 

I have my C:\Projects folder mapped to the Z: drive. I tend to navigate to Z:\PROJECT_NAME in my terminal and then open the VS Code project using the "code ." command. 

If I use the "Go to File..." shortcut to bring up a list of files in the project, it shows duplicates of each file, one with the full "C:\Projects\PROJECT_NAME\code" path next to it and one with just the relative path "code" next to it. If I actually open the C:\... one, the symbol search works perfectly, however, if I open the relative path (Z: drive one) then it is broken. Incidentally the Z: drive (broken) one is also the one that is opened when selecting the file in the Explorer panel. This is the same in the source control window which seems to reference the full C: drive paths of the files rather than the Z: drive one.

It seems that somehow the editor doesn't realise that the two files are the same and thus it doesn't update the database for the symbol search in the Z: drive file when I make changes. 

Just to confirm this, if I navigate to the full path C:\Projects\PROJECT_NAME\ in the terminal and run "code ." from there instead of the Z: drive, it works completely fine. 

Is this just an issue wth VS Code as a whole and the way it handles the remapped drive letters? I don't think it's that uncommon for devs to have something like C:\Projects mapped to a drive letter on their PC?

**Comment by sean-mcmanus** [comment]
Does C/C++: Reset IntelliSense Database from the command palette fix the issue after opening the project with a consistent location, i.e. the C or Z drive?

I'm not able to repro the issue. I see it create a database entry for the Z path when that's open and the C path then that is used. When you use the Z drive and the bug repros, can you enable logging (https://code.visualstudio.com/docs/cpp/enable-logging-cpp) and look for any paths that reference the C drive locations?

**Comment by berlunt** [comment]
Resetting IntelliSense seems to have fixed the issue for now. Hasn't shown up again yet. Leaving logging on so I can hopefully catch it if it does return
