### ISSUE TITLE
"There are too many errors for the IntelliSense engine" message with GCC arm-none-eabi includes

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#779]
I use **GCC arm-none-eabi** toolchain in my projects. So in my source code I have a lot of inculudes like this:
```
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
```
Without inculde path to these files in **c_cpp_properties.json** I get error like this:
```
cannot open source file "stddef.h"
```

But if I add these include paths into the **c_cpp_properties.json**, I get the next error in analyzed file:
```
There are too many errors for the IntelliSense engine to function properly, some of which may not be visible in the editor
```

![](https://habrastorage.org/web/a75/2dd/26d/a752dd26de5d42bc8affff061a84b59f.png)

**What is the reazon of this behaviour and how to avoid it?**

**Comment by sean-mcmanus** [comment]
Seems like the same issue as https://github.com/Microsoft/vscode-cpptools/issues/661. Our IntelliSense engine doesn't support ARM compilation targets yet. You should probably change the IntelliSenseEngine to "Tag Parser" until we add ARM support.

**Comment by bobbrow** [comment]
Tracking ARM support with #661
