### ISSUE TITLE
finding cl.exe compilers paths

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cpptools#7795]
It's possible (likely) for someone to install only the x86 hosted compilers on an x64 system. It's also possible to only install the x86 (target) compiler on a x64 system, or only the x64 (target) compiler on a x86 system. There are now also arm and arm64 (target) compilers, and each may be the only one installed. Ideally, this logic would separately check for any of the following:

On an x86 system:
bin/Hostx86/x86/cl.exe
bin/Hostx86/x64/cl.exe
bin/Hostx86/arm/cl.exe
bin/Hostx86/arm64/cl.exe

On an x64 system:
bin/Hostx86/x86/cl.exe
bin/Hostx86/x64/cl.exe
bin/Hostx86/arm/cl.exe
bin/Hostx86/arm64/cl.exe
bin/Hostx64/x86/cl.exe
bin/Hostx64/x64/cl.exe
bin/Hostx64/arm/cl.exe
bin/Hostx64/arm64/cl.exe

**Comment by Colengms** [comment]
This should be addressed in 1.6.0-insiders.
