### ISSUE TITLE
Code folding doesn't work for single-line if/else statements

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7809]
> @vacing The fix is in 1.5.0 (https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0).

thank you, it workes fine for the previous case, now I have a new bad case : (

```cpp
    if (true) {
        if (true) {
            ;
        } else {
            ;
        }
        ;
    } else if(true)  // else or else if(), the most important is no bracket here
        ;
```

_Originally posted by @vacing in https://github.com/microsoft/vscode-cpptools/issues/5521#issuecomment-876859588_

**Comment by sean-mcmanus** [comment]
@vacing Thanks, I'll check it out tomorrow...

**Comment by vacing** [comment]
> @vacing Thanks, I'll check it out tomorrow...

It's me who should say thanks for your great work and rapid response.

**Comment by sean-mcmanus** [comment]
@vacing I'm seeing code folding not working for single line if/else statements. So in your case, the last "else if" doesn't fold, but it also repros with
```
    if (true)
        return 0;
```.

Is that the issue you are seeing?

It seems like that behavior may be "by design", since it also repros with VS. I'll see if I can find out for sure. Was there a reason you believe folding of 1 line if/else would be desirable?

**Comment by sean-mcmanus** [comment]
TypeScript in VS Code has the same folding behavior -- I'm closing this as "by design".

**Comment by vacing** [comment]
> @vacing I'm seeing code folding not working for single line if/else statements. So in your case, the last "else if" doesn't fold, but it also repros with
> 
> ```
>     if (true)
>         return 0;
> ```
> 
> Is that the issue you are seeing?

What I mean is fold `if` will hide the `else if` line if it doesn't has a brace.
Do you mean this behavior is "by design"?

**Comment by sean-mcmanus** [comment]
Oops, sorry, I didn't see that behavior previously.

**Comment by vacing** [comment]
> Oops, sorry, I didn't see that behavior previously.

: >
