### ISSUE TITLE
Include file not found in include path with Cygwin

### ISSUE THREAD

**Issue by kumiao** [microsoft/vscode-cpptools#781]
![01](https://cloud.githubusercontent.com/assets/16172180/26522366/d20e8cd0-4331-11e7-911e-eb796cfdc2dc.png)
![02](https://cloud.githubusercontent.com/assets/16172180/26522369/d72576b6-4331-11e7-8c2e-5ff0e0a5d636.png)

I have added include path ，but it not working！

**Comment by szabolcsdombi** [comment]
why is the `"path": []` empty on line 48?

**Comment by kumiao** [comment]
thank you very match , my mistake ,  i did not see this
