### ISSUE TITLE
C/C++ Debugger stopped working after 1.58 upgrade

### ISSUE THREAD

**Issue by bsekura** [microsoft/vscode-cpptools#7810]
Bug type: Debugger

After updating to 1.58, debugger doesn't run. Starting debugger does nothing.
No output, nothing. Debugger toolbar shows up briefly, then exits.

Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

Worked fine before upgrade.

After upgrade to 1.58, C/C++ tools were upgraded automatically. 
After that debugging stopped working.

C/C++ ms-vscode.cpptools version: v1.5.0

**Comment by sean-mcmanus** [comment]
Sorry about that. We're tracking this with https://github.com/microsoft/vscode-cpptools/issues/7808 . A temporary workaround is to downgrade the extension to version 1.4.1 (possibly https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.0-insiders3, but we're not sure yet).

**Comment by sean-mcmanus** [comment]
Fixed with 1.5.1 (https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.1)
