### ISSUE TITLE
Windows 10: cpptools dont't find include file

### ISSUE THREAD

**Issue by Pylsur** [microsoft/vscode-cpptools#782]
Hello,
I'm trying to use VS Code and cpptools for programming C. So I tried a simple hello-world-program.
![vs code hello world](https://cloud.githubusercontent.com/assets/6266992/26531848/8f17f56c-43f2-11e7-9e12-e769a2e2d1f0.png)

I use gcc in MSYS2 / MinGW64. I added the include path in c_cpp_properties.json.
![c_cpp_properties json](https://cloud.githubusercontent.com/assets/6266992/26531877/53a4f6fa-43f3-11e7-823b-960772c9971b.png)

The include file <stdio.h> is in this directory, as you can see here.
![msys](https://cloud.githubusercontent.com/assets/6266992/26531895/c82665ae-43f3-11e7-93a0-ba179cf9d99a.png)

But VS Code keeps saying "Include file not found in include path". Does anyone have an idea, what's going wrong and the include file still isn't found? Building and running the project works. Thank you!

**Comment by sean-mcmanus** [comment]
The message "Include file not found in include path" is from a missing "browse.path" setting, so setting browse.path should fix the issue. Previously, that setting was named "includePath" -- we should probably enhance that comment to be less confusing.

**Comment by Pylsur** [comment]
Thank you, that fixed it for me. I agree that the comment should be improved.
