### ISSUE TITLE
"Force Include" config UI should not report validation errors.  Whether a forced include can be resolved is unknown until compiler is queried.

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7822]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows
- C/C++ Extension Version: 1.5.1

**Steps to reproduce**

1. Enter an invalid path in "Force include" property in IntelliSense config UI. There should be error saying cannot find path.
2. Open the c_cpp_properties.json file
3. Observe there is not error in json file for invalid path
![image](https://user-images.githubusercontent.com/38734287/125572885-cd17624e-84e2-4d8b-8e7a-1111b5b20789.png)

**Expected behavior**
UI and json file should show the same errors if the current selected active configuration is the one also show on config UI

**Comment by Colengms** [comment]
If not a full path, a forced include may refer to a partial path (or filename) that will be resolved against all include paths (including system include paths, which are not available at the time of validation).  So, I think the more correct behavior may be to not report validation issues here at all.

**Comment by bobbrow** [comment]
If we can validate absolute paths, let's do that.  We can ignore validation errors for relative paths.
