### ISSUE TITLE
There is an additional `"` in "Compile commands" description in the IntelliSense config UI (Only zh-cn)

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7823]
Bug type: Language Service

This is localization issue on the IntelliSense configuration UI.

Actual:
![image](https://user-images.githubusercontent.com/38734287/125576183-cda40f9e-9c8a-48a2-a226-c2a2c1b5409b.png)

Expected:
![image](https://user-images.githubusercontent.com/38734287/125576195-e32ad9dd-02e0-4d73-aced-fea1ed5627dc.png)

**Comment by Colengms** [comment]
@michelleangela Was this also opened internally against the Loc team?  There is a section in our internal OneNote with instructions on filing bugs against our loc strings.

**Comment by michelleangela** [comment]
Sorry, forgot to file an internal bug. I'll create one.

**Comment by Colengms** [comment]
This should be addressed in 1.6.0-insiders.
