### ISSUE TITLE
"here" of C_Cpp.files.exclude is not localized for zh-cn

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7824]
Bug type: Language Service

![image](https://user-images.githubusercontent.com/38734287/125577300-31476bde-c671-4649-83c6-0e8179709ffc.png)

**Comment by v-ericawu** [comment]
@michelleangela Tested on 1.14.1(pre-release) extension version, now the result is as follows:
"here" localized, while translation string missing for "Read more about glob patters":
CHS:
![image](https://user-images.githubusercontent.com/78774400/219594820-c7ff7cf7-a30b-4cfc-9d2c-6c417afd37a9.png)

ENU:
![image](https://user-images.githubusercontent.com/78774400/219595555-4e261b5d-1662-434b-bb15-8e9cf12c3cc7.png)

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.22.3

**Comment by bobbrow** [comment]
I changed the string, but did we get an updated translation for it yet? It looks like it's still English in the Loc PR which is still open.

**Comment by sean-mcmanus** [comment]
Ok, so maybe keep this open until we get the translation.

**Comment by sean-mcmanus** [comment]
@Colengms Oh, but it's been 2 weeks -- shouldn't we have gotten the string translated by now? I don't see it translated in the loc branch. But I also didn't see any failure with the loc pipeline.

**Comment by sean-mcmanus** [comment]
It looks like the English strings got updated in the loc branch just 10 hours ago, so it looks like there's just some delay in the translations and we're getting updates still.

**Comment by sean-mcmanus** [comment]
It looks like we still haven't gotten the translation yet (maybe for 1.23.0).

**Comment by v-ericawu** [comment]
Verified on C/C++ 1.23.0 (pre-release), this bug has been fixed:


Language| Verify Result |
-- | --
CHS |![Image](https://github.com/user-attachments/assets/075f9641-c496-41bd-8991-c52c6149618d)
CHT |![Image](https://github.com/user-attachments/assets/9494a515-9c50-4ac0-b938-c2c6847f8b6d)
CSY |![Image](https://github.com/user-attachments/assets/ed88d142-0099-4ff4-96a8-9a15066507f5)
DEU |![Image](https://github.com/user-attachments/assets/81c7791c-ba16-44f8-9eaa-18c8893d88ca)
ENU |![Image](https://github.com/user-attachments/assets/2799de1b-2cb9-4201-b576-4a0b9f234a3d)
ESN |![Image](https://github.com/user-attachments/assets/b903aab0-f623-4127-8eec-5760a58d4dbc)  
FRA |![Image](https://github.com/user-attachments/assets/28143e2c-2d7a-4cf3-981e-a503640b2fc8)
ITA |![Image](https://github.com/user-attachments/assets/bbd6044b-e7ac-4237-9f50-9bb42590f503)
PLK |![Image](https://github.com/user-attachments/assets/52b293f2-8b52-42bc-90c3-7d20b663f79e)
PTB |![Image](https://github.com/user-attachments/assets/eb64f2ad-6799-46f7-b7f6-9b83e31984cd)
TRK |![Image](https://github.com/user-attachments/assets/99445291-730b-48b4-b3b2-708fda6f936b)
RUS |![Image](https://github.com/user-attachments/assets/14544a17-b345-427e-a60d-a13331b80731)
KOR |![Image](https://github.com/user-attachments/assets/0f3eb707-1f04-4898-8c4c-c804ce960614)
JPN |![Image](https://github.com/user-attachments/assets/4c271edd-be52-4d25-b8a1-7f64ca062ef0)
