### ISSUE TITLE
Information in rename preview panel is truncated or missing

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#7826]
Bug type: Language Service

Some code comments are missing in preview panel when doing a rename, while other comments are complete.
![image](https://user-images.githubusercontent.com/38734287/125581609-8aa6717d-325f-4e00-8dc4-997e9de4e6fd.png)

![image](https://user-images.githubusercontent.com/38734287/125581636-12d98314-1ebc-4d6e-87d8-e0d7e23b4d46.png)

Is this a limitation on VS Code's preview panel?

**Comment by Colengms** [comment]
@michelleangela I think this would be a VS Code issue.  The RenameProvider returns a WorkspaceEdit, which indicates files, what range to replace, and what to replace it with.  The rest of the existing line appears to be added by VS Code itself.

**Comment by v-ericawu** [comment]
Verified C/C++ Extension 1.16.0, Only 'f' in func1 is missing:
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/2eafbe77-e727-49e8-b357-cc44ed3a07f9)

**Comment by sean-mcmanus** [comment]
It looks like VS Code fixed this for VS Code Insiders.

**Comment by v-ericawu** [comment]
@sean-mcmanus Verified on VS Code 1.78.2 with C/C++ Extension 1.16.0(Pre-Release), this issue still repro:

'f' still missing:
![image](https://github.com/microsoft/vscode-cpptools/assets/78774400/a386539d-98dc-48b3-b088-fac89de807a8)

**Comment by sean-mcmanus** [comment]
@v-ericawu No, the fix was with VS Code Insiders 1.79.0, not our extension's insiders.

**Comment by v-ericawu** [comment]
@sean-mcmanus Got it, Thanks for your confirmation!
