### ISSUE TITLE
C++ Reference Integration

### ISSUE THREAD

**Issue by sclel016** [microsoft/vscode-cpptools#7828]
Type: Feature Request

Hi,

I would like to be able to view the cppreference page for a given type or function from vscode. There are existing extensions such as [cpp-reference](https://marketplace.visualstudio.com/items?itemName=Guyutongxue.cpp-reference) but I think the functionality would fall within the scope of vscode-cpptools. 

Thanks,
Stew

**Comment by Colengms** [comment]
Hi @sclel016 .  Thanks for opening this feature request.  We generally prioritize feature requests based on up-votes.
