### ISSUE TITLE
Adding the Clang analysis (clang ... --analyze) capabilities

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#783]
Hi, I some times ago I had used SublimeText to work with C/C++ projects. To simplify my workflow I wrote extension which analyzed my opened files. It work pretty intellectually, see example below:

![](https://habrastorage.org/web/9d2/8e8/b11/9d28e8b11611408a9a9202988d98c9c9.png)

https://github.com/r44083/clang-linter

Now I have completely migrated to the VSCode and I was disappointed by the lack of such analysis. So I am going to implement this feature for VSCode.

**I would like to integrate this into the "vscode-cpptools" extension. In this case Clang linter disables intellisense analyzer**
**Let me know if you agree to integrate my pool requests.**

Clang analysis tool works really fast, reliably and deeply analyzes the code "on the fly".

**Comment by bobbrow** [comment]
Have you tried our linter?  Add `"C_Cpp.intelliSenseEngine": "Default"` to your settings.json file.

We're not ruling out the possibility of supporting Clang as a linter at some future date, but it's not in our current roadmap.  Our extension is not open source due to license restrictions in some of the code we use, so unfortunately there is no way for us to integrate any pull requests at this time.

**Comment by DemiMarie** [comment]
@bobbrow Are you talking about the EDG C++ front end?

**Comment by bobbrow** [comment]
Yes, we use the EDG C++ front end.

**Comment by boazsegev** [comment]
@bobbrow ,

I'm thankful for all the work you're all putting in to help create and improve this wonderful program.

However, this isn't just about the fact that the default `C_Cpp.intelliSenseEngine` isn't working (see #746 ) or whether using `clang` will provide better results (even though I believe it will).

The fact of the matter is that `clang` is also used as collaborative "glue" in many projects, where the `.clang_complete` file allows us to share settings and flags across development environments. 

If vscode can't support `clang` and it's `.clang_complete` convention, than collaboration is made that much harder.

I don't know if you code in C or C++ as much, but as a C developer I find `clang` integration to provide a major improvement to my workflow and I totally appreciate @r44083 's offer to fix this up.

This might just be my 2¢, but I would appreciate if you gave the matter some consideration.

**Comment by yh-sb** [comment]
Now, the cpptools extension works really well, so it isn't any need to extend it with clang mode support.
Thank you.
