### ISSUE TITLE
IntelliSense flame icon can get stuck after multiple file creation events occur with recursive includes

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7838]
Regression from https://github.com/microsoft/vscode-cpptools/issues/7783 . Pretty easy to repro (i.e. if a bunch of build/tmp files are created in a workspace, then it'll repro nearly 100% when opening a folder).

**Comment by Colengms** [comment]
This should be addressed in 1.6.0-insiders.
