### ISSUE TITLE
Intellisense struct member suggestion is wrong.

### ISSUE THREAD

**Issue by bearx3f** [microsoft/vscode-cpptools#784]
I know cpptools don't parse it's own file declared, so I declare 2 struct in main.h and use it in main.c but Intellisense suggested all struct member I declared in `main.h` only struct member of variable maybe more useful.

main.h
```c
#ifndef MAIN_H
#define MAIN_H

struct SomeStructA
{
    int member_a;
    int member_b;
    int member_c;
};

struct SomeStructB
{
    int member_d;
    int member_e;
    int member_f;
};

#endif
```

![image](https://cloud.githubusercontent.com/assets/9717561/26566769/f9559960-451f-11e7-8028-3f2f9a34da41.png)

vscode:
![image](https://cloud.githubusercontent.com/assets/9717561/26566863/a751b850-4520-11e7-81ae-13053d154b5b.png)

cpptools: Version 0.11.2: May 24, 2017

**Comment by sean-mcmanus** [comment]
This is a known issue. We're working on adding enhanced auto-complete (via the IntelliSense engine) that should fix this scenario. https://github.com/Microsoft/vscode-cpptools/issues/13 .
