### ISSUE TITLE
Also look in .vscode for cpp.hint files.

### ISSUE THREAD

**Issue by anthroid** [microsoft/vscode-cpptools#7841]
Bug type: Language Service

- OS and Version: macOS 11.4
- VS Code Version: 1.58.2 (Universal)
- C/C++ Extension Version: 1.5.1

When a macro is defined within a translation unit, and is used within the body of a function, if the argument to the macro contains at least one pair of nested parentheses, the enclosing function name in the Outline view is replaced with the macro instance.

**Steps to reproduce**
1. Create a new C file (either a standalone file, or in a new folder)
2. In the C file, create a `main()` function and one macro definition with the following form:
```c
#define unless(x) if (!(x))

int main(int argc, char **argv)
{
    int a = 1;
    unless (a == 0) {
        return a;
    }
    return 0;
} 
```
3. Note that `main(int, char**)` is correctly shown in the Outline view
4. Modify the line using the macro by adding an enclosed set of parentheses around `a == 0` as follows:
```c
#define unless(x) if (!(x))

int main(int argc, char **argv)
{
    int a = 1;
    unless ((a == 0)) {
        return a;
    }
    return 0;
} 
```
5. Note that `main(int, char**)` has now been replaced with `unless ((a == 0))` in the Outline view

**Expected behavior**
The function name should remain in the Outline view. It should not be replaced by macro references that appear within the function body.

**Code sample and logs**

- Configurations in `c_cpp_properties.json`
```json
{
	"configurations": [
		{
			"name": "Mac",
			"includePath": [],
			"defines": [],
			"cStandard": "${default}",
			"intelliSenseMode": "macos-clang-arm64"
		}
	],
	"version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 7/18/2021, 12:50:02 AM
Version: 1.5.1
Current Configuration:
{
    "name": "Mac",
    "includePath": [],
    "defines": [],
    "intelliSenseMode": "macos-clang-arm64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "cppStandard": "c++17",
    "compilerPath": "/usr/bin/gcc",
    "browse": {
        "path": [
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ .../temp/test/test.c ]:
    .../temp/test/test.c
Translation Unit Configurations:
[ .../temp/test/test.c ]:
    Process ID: 8244
    Memory Usage: 10 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/local/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c17
    IntelliSense Mode: macos-clang-arm64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 10 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 8155
```

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
```
Checking for syntax errors: file://.../temp/test/test.c
Queueing IntelliSense update for files in translation unit of: .../temp/test/test.c
Error squiggle count: 0
Update IntelliSense time (sec): 0.26
sending 2 changes to server
idle loop: reparsing the active document
Checking for syntax errors: file://.../temp/test/test.c
Queueing IntelliSense update for files in translation unit of: .../temp/test/test.c
  tag parsing file: .../temp/test/test.c
Checking for syntax errors: file://.../temp/test/test.c
Queueing IntelliSense update for files in translation unit of: .../temp/test/test.c
Error squiggle count: 0
Update IntelliSense time (sec): 1.013
  tag parsing file: .../temp/test/test.c
idle loop: reparsing the active document
Checking for syntax errors: file://.../temp/test/test.c
Queueing IntelliSense update for files in translation unit of: .../temp/test/test.c
Error squiggle count: 0
Update IntelliSense time (sec): 0.26
```

**Screenshots**

<img width="550" alt="outline-main" src="https://user-images.githubusercontent.com/352426/126057466-54666570-6a86-4a08-aa77-f9c3999b91b8.png">

<img width="550" alt="outline-macro" src="https://user-images.githubusercontent.com/352426/126057472-c06d2e7c-dfc7-4d9b-aff1-ec65978ba8f2.png">

**Comment by michelleangela** [comment]
@anthroid this is by design, please follow instructions at https://github.com/microsoft/vscode-cpptools/issues/7802#issuecomment-876706721 to add a cpp.hint file with the macro defined.

**Comment by anthroid** [comment]
Hi @michelleangela, I'm afraid I must respectfully disagree, and I hope you would reconsider classifying this as a bug, simply based on the following factors:

1. The function is completely lost in the outline. I could understand if the macro instance was _added_ to the outline (nested underneath the function name for example), but I cannot think of any conceivable situation where you would want to completely _lose_ a reference to a function in the outline simply because you have used a macro _within_ it.
2. The function is only lost if the macro invocation contains a nested set of parentheses (as shown above). Both function bodies contain the same macro, the only difference is the extra set of parentheses. Again, I don't understand how this is a "feature" by any stretch of the word.

**Comment by sean-mcmanus** [comment]
@anthroid It's a "by design" artifact of our parser inherited from VS, see https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-160 for details. The parser doesn't evaluate macros so situations where a macro defines a control block with an if/for/etc. can break our parser unless the define is added to a cpp.hint file. Either way it's classified, it's unlikely to be fixed any time soon, so the workaround is recommended.

**Comment by anthroid** [comment]
@sean-mcmanus @michelleangela Understood. The cpp.hint file works, but could I request that this instead be defined as an array in `.vscode/c_cpp_properties.json`? At least then, since this is a VS-specific artifact, it could be contained within the `.vscode` hidden directory (which could be excluded by `.gitignore`, etc), and within an appropriate file, as to not clutter the root directory?

**Comment by sean-mcmanus** [comment]
Hmm, our code functions like clang-format/clang-tidy in regards to searching up the directory path for cpp.hint files, so we'd have to do something fancy internally to make it also check within .vscode folders...seems possible though.

**Comment by sean-mcmanus** [comment]
Would having the cpp.hint in the .vscode folder be sufficient? Adding some property to cpp_properties.json might be more "problematic" (not 100% sure).

**Comment by anthroid** [comment]
@sean-mcmanus Yes, I think just having the cpp.hint in .vscode would be sufficient, that way it's contained within a VS-specific asset.
