### ISSUE TITLE
my auto suggestion is stoped automaticaly and now it cant show any taype of suggestion... 

### ISSUE THREAD

**Issue by Ganeshrath** [microsoft/vscode-cpptools#7842]
Bug type: Debugger

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
@ #my auto suggestion is stoped automaticaly and now it cant show any taype of suggestion...

**Comment by Ganeshrath** [comment]
my auto suggestion is stoped automaticaly and now it cant show any taype of suggestion... 
![Uploading Screenshot (12).png…]()

**Comment by Colengms** [comment]
Hi @Ganeshrath .  It doesn't look like your image was successfully uploaded.

There is not currently a known issue preventing suggestions from working, in general.  So, we would need more information about your configuration.

How are you configuring the C/C++ Extension?  Could you provide your `c_cpp_properties.json`, if you have one?

Could you enable the following setting `"C_Cpp.loggingLevel": "Debug"` and provide the output of the C/C++ output channel leading up to the repro?

Could you provide the output of the "Log Diagnostics" command after opening a file which repros the issue?

Is specific code necessary to trigger the repro?  If so, can you provide some example code we can use to investigate further?
