### ISSUE TITLE
Doc comment autoindentation and expansion

### ISSUE THREAD

**Issue by jgcodes2020** [microsoft/vscode-cpptools#7843]
Type: Feature Request

JSDoc comments are automatically expanded. So if I typed this:
```js
/**‸
function foo(bar) {
   console.log(`foo: ${bar}`)
}
```
Pressing <kbd>Enter</kbd> would do this:
```js
/**
 * ‸
 * @param bar
 */
function foo(bar) {
   console.log(`foo: ${bar}`)
}
```

In addition, these comments are autoindented. So if I were to put the cursor in a position like so:
```js
/**
 * This is a very cool function.‸
 * @param bar something to put in
 */
function foo(bar) {
   console.log(`foo: ${bar}`)
}
```
Pressing <kbd>Enter</kbd> would do this:
```js
/**
 * This is a very cool function.
 * ‸
 * @param bar something to put in
 */
function foo(bar) {
   console.log(`foo: ${bar}`)
}
```
This doesn't work in the C++ extension. Although a third-party extension provides Doxygen expansion, it does not provide autoindent. However, this is a feature I'd like to see in the main C++ extension or heck, even the built-in editor functionality!

**Comment by michelleangela** [comment]
Thank you for submitting this feature request. We currently have the same request at https://github.com/microsoft/vscode-cpptools/issues/5683. Closing this issue as a duplicate.
