### ISSUE TITLE
Include completion cursor position is incorrect when the ending " or > exists

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#7856]
...it's before the " or > instead of after it, so after typing `#include "fil` and completing, then the user is forced to unnecessarily type the ending " or > or they don't expect the bug they can accidentally hit Enter and put the " or > on the new line. It's confusing because after typing `#include <fil` and completing you don't need to add the > (although you would if > was pre-existing), which is inconsistent with the "" behavior since normally VS Code auto-adds the ending ".

After the fix, it consistently puts the cursor after the " or > in all cases.

**Comment by Colengms** [comment]
This should be addressed in 1.6.0-insiders.
