### ISSUE TITLE
Renaming does not work properly

### ISSUE THREAD

**Issue by Omcsesz** [microsoft/vscode-cpptools#7859]
Hello, Team!

When I want to rename a function parameter, I can't do it (see attachment). Can you support?
[RenameDoesNotWork](https://user-images.githubusercontent.com/1839739/126612723-472cdb53-6f74-47e1-92a3-f9c09b542c73.gif)

**Comment by sean-mcmanus** [comment]
Your screenshot shows error squiggles above, most likely causing subsequent failures in your parser that affect the rename. Can you fix those errors and try rename again?

**Comment by Omcsesz** [comment]
I fixed those errors, but it is still the same.

**Comment by sean-mcmanus** [comment]
Can you provide another screenshot? What are you trying to rename it to and what is the error/result? We don't accept renames with spaces.

**Comment by MiguelGuthridge** [comment]
If it helps, I've mainly experienced issues with renaming when the symbol was contained throughout multiple files (eg a typedef in a header of a C project).

**Comment by Omcsesz** [comment]
> 
> 
> If it helps, I've mainly experienced issues with renaming when the symbol was contained throughout multiple files (eg a typedef in a header of a C project).

Yes, this happens with me also.

**Comment by Colengms** [comment]
Hi @MiguelGuthridge @Omcsesz .  The Rename feature depends on both the Tag Parser (which scans all files in the workspace and include paths for symbols, syntactically) and IntelliSense (which parses semantically).  The Tag Parser finds occurrences of all symbols with the same name, and the IntelliSense parser then processes those files to determine semantically if the symbol is actually the same symbol (and not a symbol of the same name in a different scope or context).  The Rename feature is implemented using the Find All References feature, so issue with Rename likely also repro as issues with Find All References.

Issues with either Tag Parser or IntelliSense could cause Rename/FAR to fail.  The configuration of the extension is important, as missing include paths or incorrect settings (language standard, `compilerArgs` relevant to how sources are parsed, etc.)  could cause files to be interpreted differently.  If you are seeing issues with Rename/FAR, I'd suggest first ensuring there are no squiggles in the respective files that might point to issues with your configuration.  If there are no issues with your configuration, it's possible there is some code in your project that is not being parsed properly by the Tag Parser or the IntelliSense parser. If that is the case, it would be helpful if you could isolate the code that is not parsed as expected so we can use that to repro the issue and investigate further.
