### ISSUE TITLE
Provide settings for default build and run parameters 

### ISSUE THREAD

**Issue by djairao** [microsoft/vscode-cpptools#7860]
Type: Feature Request

### Target Customers/Users: Novice users
This feature request is from the perspective of novice users (like high school and undergraduate students) who need a simple and streamlined approach to set up compiler flags once and keep reusing them on every project. Sure using CMake or Makefiles is a possibility. However, those add a level of complexity that many students find intimidating and cumbersome (they often forget to set them in a new project and that causes secondary/tertiary issues that they find hard to troubleshoot), which distracts/deviate from focusing on problem-solving and programming. In my experience (with about 200 students), `VS-Code` currently given this feel, and many turn away from it. On the other hand, having a more familiar and streamlined approach for setting compiler flags and running would make it more inviting for novice users who can then progress to more sophisticated build systems.

### Suggested feature

1. Provide default settings for compiler and runtime flags that are honored when `tasks.json` or `launch.json` is generated. By default, these flags are to be the same as those used by IntelliSense settings, to provide consistency. For example, settings something along the lines of:
```yaml
{
    "C_Cpp.default.build.compilerAddlArgs": [ "-g", "-std=c++17", "-Wall", "-Wextra", "-fsanitize=address" ],
    "C_Cpp.default.build.linkerAddlArgs": [ "-lstdc++fs", "-lboost_system", "-lpthread" ],
```

2. Include comments in the generated `tasks.json` indicating where the overrides were obtained from to ease tracing and troubleshooting settings. For example, something along the lines of:
```yaml
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++ build active file",
            "command": "/apps/gnu/8.4.0/bin/g++",

             // Overrides from C_Cpp.default.build.compilerAddlArgs from settings.json
            "args": [  "-g",  "-std=c++17",  "-Wall", "-Wextra", "-fsanitize=address",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}",

                // Overrides from C_Cpp.default.build.linkerAddlArgs from settings.json
                "-lstdc++fs", "-lboost_system", "-lpthread"
            ],
```

### Workaround
If you are desperate like me to help students learn and succeed, then a possible workaround (of course, usual disclaimers apply)  is to edit `main.js` (for me, the path to this fiile was: `~/.vscode-server/extensions/ms-vscode.cpptools-1.5.1/dist/main.js`) after you install the extension, as shown below:

```javascript
44676                 let args = isCl ? ['/Zi', '/EHsc', '/nologo', '/Fe:', filePath + '.exe', '${file}'] : 
                              ['-g', '-Wall', '-std=c++17', '-fsanitize=address', '${file}', '-o', filePath + (isWindows       ? '.exe' : '')];
44677                 if (compilerArgs && compilerArgs.length > 0) {
44678                     args = args.concat(compilerArgs);
44679                 }

```

If you are working with an existing project that already has a `tasks.json` file, then you will need to recreate `tasks.json` in order to see the updated set of compiler flags.

**Comment by sean-mcmanus** [comment]
Adding the default arg settings should be possible, but there may not be any API to add comments to the tasks.json, because I believe we just return a Task object to VS Code and they create the file.

**Comment by djairao** [comment]
Thinking about it a bit more -- Given that `VS Code` allows multiple tasks to be returned, maybe it would be better to also let users define a "Tasks template" file that would be used when creating tasks. The template file can contain multiple tasks, say one for "Debug" one for "Release" etc. Any of the task values specified in the template would override the defaults used by `cpptools`.

Ideally, this template would be at a Machine or User level. 

For example, I would provide the following `tasks_settings.json` (these settings could also be part of the settings.json I guess):

```yaml
{
    "tasks": [
         {
              "label": "Custom debug task",
              "args": [ "-g", "-Wall", "-std=c++17", "-fsanitize=address", "${file}, "-o", 
                            "${fileDirname}/${fileBasenameNoExtension}"]
         },
         {
              "label": "Custom release task",
              "args": [ "-O3", "-Wall", "-std=c++17", 
                           "-fno-omit-frame-pointer", "${file}, 
                           "-o", 
                           "${fileDirname}/${fileBasenameNoExtension}_release"]
         }
}
```

The above template would then result in the following default `tasks.json` being generated:

```yaml
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "Custom debug task",
            "command": "/usr/bin/g++-9",
            "args": [
                "-g",
                "-Wall", 
                "-std=c++17", 
                "-fsanitize=address",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        },
        {
            "type": "cppbuild",
            "label": "Custom release task",
            "command": "/usr/bin/g++",
            "args": [
                "-O3", 
                "-Wall", 
                "-std=c++17", 
                "-fno-omit-frame-pointer",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
            "detail": "compiler: /usr/bin/g++"
        }
    ],
    "version": "2.0.0"
}
```

**Comment by sean-mcmanus** [comment]
VS Code doesn't currently have an API for extensions to add task templates, see https://github.com/microsoft/vscode/issues/10742, although we could probably add our own setting/command to do something similar via the tasks we generate.
