### ISSUE TITLE
s

### ISSUE THREAD

**Issue by sneha-rathore** [microsoft/vscode-cpptools#7862]
Issue Type: <b>Feature Request</b>

it is showing pull request in github but when i open github it is not loading

Extension version: 1.5.1
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by sean-mcmanus** [comment]
What? I don't understand.
