### ISSUE TITLE
command-line error: language modes specified are incompatible C++/C++ 1027

### ISSUE THREAD

**Issue by devclyde** [microsoft/vscode-cpptools#7864]
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 21.04
- VS Code Version: 1.58.2
- C/C++ Extension Version: v1.5.
- Other extensions you installed (and if the issue persists after disabling them): CMake, CMake Tools
- If using SSH remote, specify OS of remote machine: I don't use
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The extension reports the C/C++ 1027 error for every file I open, it's a single project and I use it with CMake and CMake Tools, and in that I lose Intellisense.

**Steps to reproduce**

1. Clone https://github.com/devclyde/minicraft
2. Open in VS Code.
3. Open any C++ file

**Expected behavior**

I expect my intellisense to work.
I expect errors to actually reflect real errors in my source code and not random things that don't actually exist with no line numbers to tell me where it even went wrong and nothing I can change to remove it.

- Configurations in `c_cpp_properties.json`
I don't use.

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 22/07/2021 19:08:58
Version: 1.5.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "intelliSenseMode": "linux-clang-x64",
    "compilerArgs": [],
    "cStandard": "c11",
    "cppStandard": "c++11",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "compilerPathIsExplicit": true,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/home/clyde/repos/minicraft/include",
        "/home/clyde/repos/minicraft/build/_deps/raylib-src/src",
        "/home/clyde/repos/minicraft/build/_deps/raylib-src/src/external/glfw/include",
        "/home/clyde/repos/minicraft/build/CMakeFiles/minicraft.dir",
        "/home/clyde/repos/minicraft/src",
        "/home/clyde/repos/minicraft/src/tiles",
        "/home/clyde/repos/minicraft/build/_deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir",
        "/home/clyde/repos/minicraft/build/_deps/raylib-src/src/external/glfw/src",
        "/home/clyde/repos/minicraft/build/_deps/raylib-build/raylib/external/glfw/src",
        "/home/clyde/repos/minicraft/build/_deps/raylib-src/src/external/glfw/include/GLFW"
    ],
    "standard": "c99",
    "compilerPath": "/bin/x86_64-linux-gnu-g++-10",
    "compilerArgs": [
        "-fno-strict-aliasing",
        "-Werror=implicit-function-declaration",
        "-Werror=pointer-arith",
        "-O3",
        "-DNDEBUG",
        "-fPIC",
        "-Wall",
        "-std=c99",
        "-Wdeclaration-after-statement",
        "-fno-strict-aliasing",
        "-Werror=implicit-function-declaration",
        "-Werror=pointer-arith",
        "-O3",
        "-DNDEBUG",
        "-fPIC",
        "-Wall",
        "-std=c99"
    ]
}
Translation Unit Mappings:
[ /home/clyde/repos/minicraft/include/stores/texture_store.hh ]:
    /home/clyde/repos/minicraft/include/stores/texture_store.hh
Translation Unit Configurations:
[ /home/clyde/repos/minicraft/include/stores/texture_store.hh ]:
    Process ID: 32883
    Memory Usage: 7 MB
    Compiler Path: /bin/x86_64-linux-gnu-g++-10
    Includes:
        /usr/lib/gcc/x86_64-linux-gnu/10/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=100300
        --header_only_fallback
Total Memory Usage: 7 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 8068
Number of files parsed: 1490
```

**Screenshots**

![image](https://user-images.githubusercontent.com/49321124/126718582-1043e35f-5ced-4007-b2a3-520c4652505c.png)
**NOTE:** The error description is in Brazilian Portuguese, the error ID is 1027

**Comment by Colengms** [comment]
Hi @devclyde .  It looks like the issue may be related to either CMake Tools or your `CMakeLists.txt`.  The `compilerPath` and `standard` provided by CMake Tools (in the custom browse configuration) are contradictory.  The `compilerPath` refers to g++ (a C++ compiler), while the `standard` is `c99` (a C standard, not C++ standard).  Since your `CMakeLists.txt` sets `CMAKE_CXX_STANDARD` to `11`, it's unclear to me where this `c99` standard is coming from.  However, I do see it included in the command line args as well, as `-std=c99`, which suggests that this is what CMake it generating.  Could you confirm by running a build and checking what command line is being generated by CMake when compiling a file, to see if it includes `-std=c99`?

There may be a larger issue here, as the external config provider API only provides a single `standard` value in the custom browse config, which implies only fully C or fully C++ projects are supported.  But, it your case, it looks like all sources are intended to be C++, correct?

Would you like to open a new issue in the [CMake Tools repo](https://github.com/microsoft/vscode-cmake-tools)?  Or, we should we transfer this one.

**Comment by Colengms** [comment]
I tried to repro with the repo you provided, but ran into issues.  In order to repro, it's necessary to generate the CMake build, which appears to have a bunch of dependencies.  I installed many, but then got stuck on the following:

```
[cmake] CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
[cmake] Please set them or make sure they are set and tested correctly in the CMake files:
[cmake] /home/colen/repos/minicraft/build/_deps/raylib-src/src/OPENGL_INCLUDE_DIR
[cmake]    used as include directory in directory /home/colen/repos/minicraft/build/_deps/raylib-src/src
```

**Comment by devclyde** [comment]
I use C++11 and I looked at the extension diagnostics and it was forcing the file to use C++17, I just opened my settings.json and changed the default to c++11
