### ISSUE TITLE
Clang format doesn't accept AlignArrayOfStructures argument

### ISSUE THREAD

**Issue by comiluv** [microsoft/vscode-cpptools#7867]
We have written the needed data into your clipboard because it was too
Issue Type: <b>Bug</b>

Formatting with AlignArrayOfStructures option causes error:
Error parsing -style: invalid argument

Extension version: 1.5.1
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (55.30GB free)|
|Process Argv|. --crash-reporter-id bbfbb75b-5e28-4eaa-87a7-7cf239f2c4c2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

 large to send. Please paste.

**Comment by Colengms** [comment]
Hi @comiluv .  Does this occur when invoking clang-format directly?  We bundle clang-format with the C/C++ Extension, but issues with clang-format itself should go through https://llvm.org/docs/HowToSubmitABug.html .  

Is the issue related to using the `C_Cpp.clang_format_style` setting to configure clang-format through the C/C++ Extension (instead of using a `.clang-format` file), could you provide the value you using for that setting that is not working as expected?

**Comment by comiluv** [comment]
It occurs with clang-format that is bundled with C/C++ extension.
My settings.json looks like
```json
"[c]": {
		"editor.defaultFormatter": "ms-vscode.cpptools"
	},
"C_Cpp.clang_format_style": "{ BasedOnStyle: WebKit, UseTab: ForIndentation, TabWidth: 4, IndentWidth: 4, DerivePointerAlignment: false, PointerAlignment: Right, AllowShortCaseLabelsOnASingleLine: true, AlignAfterOpenBracket: true, AlignArrayOfStructures: right }",
```
Exact error message output in VSCode output window is:
```
Formatting failed:
"c:\Users\choij\.vscode\extensions\ms-vscode.cpptools-1.5.1/bin/../LLVM/bin/clang-format.exe" -style="{ BasedOnStyle: WebKit, UseTab: ForIndentation, TabWidth: 4, IndentWidth: 4, DerivePointerAlignment: false, PointerAlignment: Right, AllowShortCaseLabelsOnASingleLine: true, AlignAfterOpenBracket: true, AlignArrayOfStructures: right }" -fallback-style="LLVM" -assume-filename="c:\Dev\cprogramming\ch27\quadratic.c"
<command-line>:1:204: error: unknown key 'AlignArrayOfStructures'
  { BasedOnStyle: WebKit, UseTab: ForIndentation, TabWidth: 4, IndentWidth: 4, DerivePointerAlignment: false, PointerAlignment: Right, AllowShortCaseLabelsOnASingleLine: true, AlignAfterOpenBracket: true, AlignArrayOfStructures: right }
```
AlignArrayOfStructures is a valid key that is described in https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by sean-mcmanus** [comment]
We ship clang-format 12.0. AlignArrayOfStructures is for clang-format 13.0. See https://releases.llvm.org/12.0.0/tools/clang/docs/ClangFormatStyleOptions.html .

You can set clang_format_path to a clang-format 13.0 if you have one built locally.
