### ISSUE TITLE
Can't set breakpoint when remote debugging by ssh

### ISSUE THREAD

**Issue by aengusjiang** [microsoft/vscode-cpptools#787]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|cpptools|ms-vscode|0.11.2|

Issue description:
 My program named test is local Centos7 run at Vmware on Windows.
 Then open the code project by vscode on windows and begin to debugging the program :
case one:
       the breakpoint  is work if it set before the program run or attach.
case two:
       the breakpoint is not work if it set after the program run or attach.
you cat see the breakpoint is grey. See the pic below：
![image](https://cloud.githubusercontent.com/assets/22406984/26623823/8cdd77e6-4621-11e7-8efb-314dd11e7285.png)
it seem to still try to bind the breakpoint.

Please help me check and fix it.
Thanks.

**Comment by aengusjiang** [comment]
here the example code:
[test.tar.gz](https://github.com/Microsoft/vscode-cpptools/files/1040788/test.tar.gz)

**Comment by yh-sb** [comment]
I faced with this issue too.
In my case I couldn't set brakepoint on the `asm("nop");`

I still have not found a solution to this situation :(

**Comment by pieandcakes** [comment]
@r44083 @AbelaroJiang Can either of you post your `launch.json` ? The above picture doesn't show you attached or launched, so my assumption is that it is having a problem communicating with the other machine.

**Comment by aengusjiang** [comment]
Ok, I will provide more info to help you make sense of this problem.
![image](https://cloud.githubusercontent.com/assets/22406984/26707617/aaf00dc2-4778-11e7-8a7d-6e04b2f8ff3a.png)

Here my launch.json 
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Remote Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "./build/bin/test", // the program locate remote pc
            "args": [],
            "stopAtEntry": false,
            "cwd": "~/test",               // can use the relative path
            "environment": [],
            "externalConsole": true,
            "pipeTransport": {
                "pipeCwd": "",             // Set empty if We have added the ssh.exe to path, or set the full path
                "pipeProgram": "ssh.exe",
                "pipeArgs": [
                    "abelardo@192.168.1.78"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/home/abelardo/test": "${workspaceRoot}" // [remote：local] remote must be use the absolute path
            },
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
            "name": "Remote Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/home/abelardo/test/build/bin/test",
            "processId": "${command:pickRemoteProcess}",
            "pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "ssh",
                "pipeArgs": [
                    "abelardo@192.168.1.78"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/home/abelardo/test": "${workspaceRoot}"
            },
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        }
    ]
}`

Here a Sample Cmake project code. You can have a try follow the steps below:
[test.tar.gz](https://github.com/Microsoft/vscode-cpptools/files/1046471/test.tar.gz)

Step1: Put the test code to remote pc (In my case: remote IP: 192.168.1.78)
Step2: authorized your local machine ssh key to remote machine. So we need't input the password when we use the ssh to connect the remote machine.
Step3: build the code on remote machine. 
          >cd test
          > mkdir build 
          > cd build
          > cmake ..
          > make
  then everything is ready.

**Comment by aengusjiang** [comment]
Step5: You can test it now. 
Case one set the breakpoint before launch or attach(work).
Case two set the breakpoint after launch or attach(not work).

Note:
My Local machine: OS Version: Windows_NT ia32 10.0.15063
My Remote machine: Centos7.2

**Comment by pieandcakes** [comment]
@AbelaroJiang Your issue is that you didn't compile with symbols. I added the cmake flag -DCMAKE_BUILD_TYPE=Debug to the command line call for CMake and then I can set breakpoints and debug.  Please make sure you are compiling with symbols. if you call `g++` from the command line and pass the `-g` flag, its the same thing.

**Comment by pieandcakes** [comment]
@AbelaroJiang The reason why you can set it before you start debugging is that the UI (VSCode) allows you to with out sending anything to the debugger. It then sends it when you start debugging but it will fail to bind because symbols aren't loaded. This is why when you launch or attach, it isn't showing as bound.

**Comment by aengusjiang** [comment]
Oh, no. 
I follow you advise. But the result is same as before.
I try debugging on the the Centos Os mathie, It 's ok. 
I do some change about the test code. 
1.Add the local attach or launch on linux.
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Local Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/build/bin/test",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}/build",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
            "name": "Local Attach",
            "type": "cppdbg",
            "request": "attach",
            "program":"${workspaceRoot}/build/bin/test",
            "processId": "${command:pickProcess}",
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
            "name": "Remote Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "./build/bin/test", // the program locate remote pc
            "args": [],
            "stopAtEntry": false,
            "cwd": "/smbshare/test",               // can use the relative path
            "environment": [],
            "externalConsole": true,
            "pipeTransport": {
                "pipeCwd": "",             // Set empty if We have added the ssh.exe to path, or set the full path
                "pipeProgram": "ssh.exe",
                "pipeArgs": [
                    "abelardo@192.168.1.78"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/smbshare/test": "${workspaceRoot}" // [remote：local] remote must be use the absolute path
            },
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
            "name": "Remote Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/smbshare/test/build/bin/test",
            "processId": "${command:pickRemoteProcess}",
            "pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "ssh",
                "pipeArgs": [
                    "abelardo@192.168.1.78"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/smbshare/test": "${workspaceRoot}"
            },
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        }
    ]
}`
2.Add the CXX flag:
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -g -pipe -D_NEW_LIC -D_GNU_SOURCE -fPIC -D_REENTRANT -std=c++11"). 

I can see the compiler flags when I make:
/usr/bin/c++    -Wall -g -pipe -D_NEW_LIC -D_GNU_SOURCE -fPIC -D_REENTRANT -std=c++11    CMakeFiles/test.dir/test.cpp.o  -o bin/test -rdynamic

So I think it is not cause by the symbls not include to complie.
The problem is binding breakpoint error by ssh. 
So you could you help me tracing this problem.

I think it is useless only set breakpoint before launch&attach the program.
Thank you.

**Comment by aengusjiang** [comment]
can you receive my last comment?

**Comment by aengusjiang** [comment]
Could you tell me what Os that you test it on?

I test it in the same way on Ubuntu16.04. It is ok when I set the CMAKE_BUILD_TYPE=Debug.
but it is not work on Centos7.2.

**Comment by pieandcakes** [comment]
@AbelaroJiang I'll take another look on Monday when I can install a new version of Centos

**Comment by pieandcakes** [comment]
@AbelaroJiang I tried this with CentOS Linux release 7.3.1611 (Core) running in Hyper-V and I can't duplicate the problem. I am using plink.exe as my pipeProgram. I set a breakpoint and F5 and it hits. I can set more breakpoints, step and stop debugging. 

Can you try adding:
```
            "logging": {
                "engineLogging": true
            },
```

and sending me the Debug Console output when you reproduce your scenario?

**Comment by aengusjiang** [comment]
Ok, here it is:
1: (20106) Debugger failed to break. Trying again.
1: (20106) <-1016-exec-interrupt
1: (20114) ->1016^done
1: (20114) ->(gdb)
1: (20114) ->&"Quit\n"
1: (20114) 1016: elapsed time 7
1: (23106) Debugger failed to break. Trying again.
1: (23106) <-1017-exec-interrupt
1: (23118) ->1017^done
1: (23118) ->(gdb)
1: (23118) ->&"Quit\n"
1: (23118) 1017: elapsed time 12
1: (26107) Debugger failed to break. Trying again.
1: (26107) <-1018-exec-interrupt
1: (26120) ->1018^done
1: (26120) ->(gdb)
1: (26120) 1018: elapsed time 13
1: (26120) ->&"Quit\n"

**Comment by aengusjiang** [comment]
Here my environment information:
VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
OS Version: Windows_NT ia32 10.0.15063
Centos Version: CentOS Linux release 7.3.1611 (Core) 
I used the virtual matchine software is VMware® Workstation 12 Pro 12.5.6 build-5528349, not the Hyper-V. 
I used the bridge way the connect the windows he the virtual Centos.

I hope this info can help you.
I will try it with the Hyper-V later, and the give you answer tomorrow.

**Comment by aengusjiang** [comment]
I have try check it on centos install with Hyper-V.
But it still can duplicate the problem.
My vscode version 1.12.2

I use the ssh remote login the centos.
then I run the the test program.
the then it will print the info:
Pid 7326: 0
Pid 7326: 1
Pid 7326: 2
Pid 7326: 3
Pid 7326: 4
Pid 7326: 5
Pid 7326: 6
Pid 7326: 7
Pid 7326: 8
Pid 7326: 9
Pid 7326: 10

then I remote attach the 7326 and set a breakpoint, then it is not work.
But if press ctr+c to kill the program I have run. then the breakpoint is active. 

It is so strange.
Centos version: CentOS Linux release 7.3.1611 (Core)
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7

Is that the problem of my launch.json?
