### ISSUE TITLE
Debug hangs at loading symbols

### ISSUE THREAD

**Issue by jsjtczh** [microsoft/vscode-cpptools#7874]
Bug type: Debugger

**Describe the bug**
- OS and Version: MacOS Catalina 10.15.7 
- VS Code Version: 1.58.2
- C/C++ Extension Version: 1.5.1
- Description: When the program used a third party library like opencv (I tried opencv3 and opencv4), the debugger cannot work. It hangs at loading symbols.

**To Reproduce**
[test.zip](https://github.com/microsoft/vscode-cpptools/files/6872108/test.zip)Steps to reproduce the behavior:
The attachment is a simple project. Brew install opencv and use cmake to build the program. And then run debugger. 

launch.json:
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(lldb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/build/opencv",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "externalConsole": false,
      "MIMode": "lldb",
      "environment": [],
      "logging": {
        "engineLogging": true,
        "trace": true,
        "traceResponse": true
      }
    }
  ]
}

log:
1: (1674) ->=breakpoint-modified,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x0000000100011e0b",func="testImage()",file="main.cpp",fullname="/Users/czh190502/Projects/test/test/main.cpp",line="7",pending=["main.cpp:7"],times="0",original-location="main.cpp:7"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1674) ->(gdb)\n"},"seq":142}
1: (1674) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1674) ->(gdb)\n"},"seq":144}
1: (1674) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1674) ->=library-loaded,id=\"/usr/lib/dyld\",target-name=\"/usr/lib/dyld\",host-name=\"/usr/lib/dyld\",symbols-loaded=\"0\",loaded_addr=\"0x000000010002c000\",size=\"598016\"\n"},"seq":146}
1: (1674) ->=library-loaded,id="/usr/lib/dyld",target-name="/usr/lib/dyld",host-name="/usr/lib/dyld",symbols-loaded="0",loaded_addr="0x000000010002c000",size="598016"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1675) ->=library-loaded,id=\"/Users/czh190502/Projects/test/test/build/opencv\",target-name=\"/Users/czh190502/Projects/test/test/build/opencv\",host-name=\"/Users/czh190502/Projects/test/test/build/opencv\",symbols-loaded=\"0\",loaded_addr=\"0x0000000100000000\",size=\"81920\"\n"},"seq":148}
1: (1675) ->=library-loaded,id="/Users/czh190502/Projects/test/test/build/opencv",target-name="/Users/czh190502/Projects/test/test/build/opencv",host-name="/Users/czh190502/Projects/test/test/build/opencv",symbols-loaded="0",loaded_addr="0x0000000100000000",size="81920"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1675) ->*running,thread-id=\"all\"\n"},"seq":150}
1: (1675) ->*running,thread-id="all"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1675) ->(gdb)\n"},"seq":152}
1: (1675) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1677) <-1010-thread-info 1\n"},"seq":154}
1: (1677) <-1010-thread-info 1
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1678) ->1010^done,threads=[{id=\"1\",target-id=\"Thread 1\",frame={level=\"0\",addr=\"0x000000010002d000\",func=\"_dyld_start\",args=[],file=\"??\",fullname=\"??\",line=\"-1\"},state=\"running\"}]\n"},"seq":156}
1: (1678) ->1010^done,threads=[{id="1",target-id="Thread 1",frame={level="0",addr="0x000000010002d000",func="_dyld_start",args=[],file="??",fullname="??",line="-1"},state="running"}]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1678) ->(gdb)\n"},"seq":158}
1: (1678) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"=thread-selected,id=\"1\"\n"},"seq":160}
=thread-selected,id="1"
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"=library-unloaded,id=\"/Users/czh190502/Projects/test/test/build/opencv\",target-name=\"/Users/czh190502/Projects/test/test/build/opencv\",host-name=\"/Users/czh190502/Projects/test/test/build/opencv\"\n"},"seq":162}
=library-unloaded,id="/Users/czh190502/Projects/test/test/build/opencv",target-name="/Users/czh190502/Projects/test/test/build/opencv",host-name="/Users/czh190502/Projects/test/test/build/opencv"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1681) Send Event AD7ModuleLoadEvent\n"},"seq":164}
1: (1681) Send Event AD7ModuleLoadEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"Loaded '/usr/lib/dyld'. Symbols loaded.\n"},"seq":166}
Loaded '/usr/lib/dyld'. Symbols loaded.
--> E (module): {"type":"event","event":"module","body":{"reason":"new","module":{"id":1,"name":"dyld","path":"/usr/lib/dyld","symbolFilePath":"/usr/lib/dyld","vsLoadAddress":"4295147520","vsPreferredLoadAddress":"4295147520","vsModuleSize":598016,"vsLoadOrder":0,"vsTimestampUTC":"1600734629","vsIs64Bit":true}},"seq":168}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1712) Send Event AD7ModuleLoadEvent\n"},"seq":170}
1: (1712) Send Event AD7ModuleLoadEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"Loaded '/Users/czh190502/Projects/test/test/build/opencv'. Symbols loaded.\n"},"seq":172}
Loaded '/Users/czh190502/Projects/test/test/build/opencv'. Symbols loaded.
--> E (module): {"type":"event","event":"module","body":{"reason":"new","module":{"id":2,"name":"opencv","path":"/Users/czh190502/Projects/test/test/build/opencv","symbolFilePath":"/Users/czh190502/Projects/test/test/build/opencv","vsLoadAddress":"4294967296","vsPreferredLoadAddress":"4294967296","vsModuleSize":81920,"vsLoadOrder":1,"vsTimestampUTC":"1627115027","vsIs64Bit":true}},"seq":174}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1713) 1010: elapsed time 35\n"},"seq":176}
1: (1713) 1010: elapsed time 35
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1716) Send Event AD7ProcessInfoUpdatedEvent\n"},"seq":178}
1: (1716) Send Event AD7ProcessInfoUpdatedEvent
--> E (process): {"type":"event","event":"process","body":{"startMethod":"launch","name":"/Users/czh190502/Projects/test/test/build/opencv","systemProcessId":88213},"seq":180}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1726) Send Event AD7ThreadCreateEvent\n"},"seq":182}
1: (1726) Send Event AD7ThreadCreateEvent
--> E (thread): {"type":"event","event":"thread","body":{"reason":"started","threadId":1},"seq":184}
<--   C (threads-7): {"command":"threads","type":"request","seq":7}
--> R (threads-7): {"type":"response","request_seq":7,"success":true,"command":"threads","body":{"threads":[{"id":1,"name":"Thread #1"}]},"seq":187}

**Comment by jsjtczh** [comment]
My program and setting is similar to https://thecodinginterface.com/blog/opencv-cpp-vscode/.

**Comment by WardenGnaw** [comment]
We appreciate any issues opened to help us keep track and prioritize issues. There is a known slowness with lldb-mi. However, The VSCode C++ Extension does not directly work on `lldb` or `lldb-mi`. We use and build `lldb-mi` from the [lldb-mi repository](https://github.com/lldb-tools/lldb-mi) and publish it. 

We build the debug adapter `MIEngine` to communicate with `lldb-mi`, but that will be in the `OpenDebugAD7` process. 

If memory usage is high for the `lldb-mi` process, this is directly related to [LLDB](https://lldb.llvm.org/) itself which you can report bugs to https://bugs.llvm.org/

You can capture and send trace files to help them investigate performance issues. Here is a [tutorial](https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues#macos) on how to capture a trace file but for `cpptools` and `cpptools-srv`. You will want to capture the trace on `lldb-mi`.
