### ISSUE TITLE
extention is not working

### ISSUE THREAD

**Issue by utopiansprateek** [microsoft/vscode-cpptools#7879]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Colengms** [comment]
Hi @utopiansprateek .  We'd like to help, but the issue you created doesn't provide any information about the problem you encountered.  Could you post the information requested by the new issue template?

**Comment by alekbabich** [comment]
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed to download https://go.microsoft.com/fwlink/?linkid=2167520
Failed at stage: downloadPackages
failed (error code '404')

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.

**Comment by sean-mcmanus** [comment]
@alekbabich Our test machines are also hitting the 404 randomly (starting today) -- we're trying to get it resolved.

**Comment by sean-mcmanus** [comment]
@alekbabich Can you try again? The issue seems to have resolved itself.

**Comment by hzcheng** [comment]
Updating this extention is a disaster. It almost drives me crasy.

**Comment by alekbabich** [comment]
No longer an issue.  Thanks!
