### ISSUE TITLE
Microsoft Lumia 950 DUAL SIM

### ISSUE THREAD

**Issue by grzesimaj-74** [microsoft/vscode-cpptools#7881]
Bug type: Debugger

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by Colengms** [comment]
Hi @grzesimaj-74 .  Do you have an issue to report with the C/C++ Extension for VS Code?

**Comment by grzesimaj-74** [comment]
Mam problem, bo Orane blokuje mi DNS i Hosty mi na to nie zezwala na zmianę Azure VS Code i Push Microsoft Lumia 950 DUAL SIM. W Polsce mają stare terminale inaczej trupy do wysyłania anonimowych reklam a nie zabezpieczeń. Nie zgadzają się z zabezpieczeniami Windows 11. Mam zablokowany Microsoft Defender. Precz z Grami, reklamami i pornografią 💻📱👎📵 Żądają Window 10 Home. Ja takiego badziewia nie mam zainstalowanego a w BIOS cały czas jest konfiguracja Windows 10 Home.

**Comment by bobbrow** [comment]
@Colengms I translated from Polish and it doesn't sound like it.
