### ISSUE TITLE
"clang-format on Save" setting causes duplication of programmatically created editor tabs

### ISSUE THREAD

**Issue by Arkadiy-bb** [microsoft/vscode-cpptools#7882]
Bug type: Language Service

- OS and Version: Windows 10
- VS Code Version: 1.58.2
- C/C++ Extension Version: v1.5.1
- If using SSH remote, specify OS of remote machine: Using Docker Container, Linux RH 7.

I wrote an extension that creates new C++ and header files.

The file is created like so: 

```
  const document = await vscode.workspace.openTextDocument(file);
  const editor = await vscode.window.showTextDocument(
    document,
    vscode.ViewColumn.Active,
    true
  );

  const protoSnippet = config<string[]>(
    "make-class-files." + configMarker + "Snippet"
  )?.join("\n");
  const readySnippet = substituteVariables(protoSnippet, substitution);
  await editor.insertSnippet(new vscode.SnippetString(readySnippet));
```

Where `file` is a path in my workplace created as follows:

```
  if (fileName?.charAt(0) === "/") {
    directory = vscode.workspace.getWorkspaceFolder(directory)?.uri!;
    fileName = fileName.substr(1);
  }

  const file = addFileName(directory, fileName!).with({ scheme: "untitled" });
```

The editor tab shows up in the workspace, it's shown as "modified". When I save it, I get two tabs: one contains the saved text, clang-format applied, the other is still marked "modified" and contains the original text.

The path and local path are same for both tabs and correct for the value of `file` passed in the code. After closing the modified tab, I can proceed with my work as normal.

Please note that the documents created this way do not show in the file tree on the left until they are saved. I think that is the root cause of my issue.

**Comment by Colengms** [comment]
Hi @Arkadiy-bb .  I think the issue you are describing would be a VS Code bug.  I'd suggest opening an issue in [the VS Code repo](https://github.com/microsoft/vscode).   `editor.formatOnSave` is a VS Code setting.  VS Code will invoke our `DocumentFormattingEditProvider`, which returns a set of edits to make to the file.  I don't believe we should be influencing the editor at all in the process of providing those results.  Do you see the same behavior when the C/C++ Extension is not installed and another extension is used which provides formatting for C++ files (or if using a file extension that would receive formatting from VS Code, such as a `.js` file)?

**Comment by Arkadiy-bb** [comment]
I see. I'll close this one and resubmit it to VSCode. If the folks there don't recognize the issue, I'll have to create a custom "extension" just to reproduce it and test with multiple formatting providers.
