### ISSUE TITLE
Header inclusion is not working correctly

### ISSUE THREAD

**Issue by Omcsesz** [microsoft/vscode-cpptools#7890]
Hello, Team!

After adding a path which includes a header file, when I want to include it in a cpp file, it is not found (see attachment).
Can you please support?

OS: Ubuntu 21.04
[Catch2IsNotFound](https://user-images.githubusercontent.com/1839739/127306339-3adc4164-f7d1-4fdf-9b5b-7391d69e30ca.jpg)

**Comment by Colengms** [comment]
Hi @Omcsesz .  Is the parent directory of `thirdparty` included in your set of include directories in `c_cpp_properties.json`?

Based on the configuration warning that was displayed, it looks like you're trying to configure the C/C++ extension to use `compile_commands.json`, but it was not found.  If that had already been corrected, does the command line for that file in `compile_commands.json` specify the include path containing `thirdparty`?  For a file in `compile_commands.json`, its command line there is used to configure IntelliSense, so must be valid and contain all required arguments (such as include path args)..

Could you provide a bit more information, so we can investigate further.

* The contents of your `c_cpp_properties.json`, if you are using one to configure the C/C++ extension.
* After enabling debug output using `"C_Cpp.loggingLevel": "Debug"` in `settings.json`, could you provide the contents of the C/C++ output channel leading up to the repro?
* With the repro'ing file open, could you run the `C/C++: Log Diagnostics` command and provide its output?  That should tell us exactly how the file was configured for IntelliSense.

**Comment by Omcsesz** [comment]
With VSCode version 1.60, it seems to be solved.
