### ISSUE TITLE
 Gdb cannot insert breakpoint and cannot access memory at address

### ISSUE THREAD

**Issue by houlei1994** [microsoft/vscode-cpptools#7899]
Bug type: Debugger

**Describe the bug**
- OS and Version: window10
- VS Code Version: 1.58.2
- C/C++ Extension Version: 1.5.1
- Other extensions you installed (and if the issue persists after disabling them): Remote-WSL 0.58.2 (ubuntu18.04)
- A clear and concise description of what the bug is.
- 
I use vscode, WSL and gdb to debug shared library on Android and meet some problem about gdb. Gdb report: gdb cannot insert breakpoint and Cannot access memory at address. The gdb I use is android-ndk-r21e-linux-x86_64/android-ndk-r21e/prebuilt/linux-x86_64/bin/gdb.

But after gdbserver attach process, I can debug the same shared library normally with using gdb in WSL (android-ndk-r21e-linux-x86_64/android-ndk-r21e/prebuilt/linux-x86_64/bin/gdb).

**To Reproduce**
On Android board

1. start app
2. `ps -ef` to get pid
3. gdbserver xx.xx.xx.xx:1234 --attach pid

vscode

1. open code in WSL
2. set breakpoint
3. start debugging

**launch.json**
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(Android gdb)",
            "type": "cppdbg",
            "request": "launch",
            //In oder to link with gdbserver, set another program to cheat vscode
            "program": "/mnt/d/RemoteDebug/logcat",
            "args": [],
            "cwd": "${fileDirname}",
            "stopAtEntry": false, 
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "set shared library paths",
                    "text": "set sysroot /lhome/android/imx-android11-L5.10-daily-imx8qxp-8qm-20210412/out/target/product/mek_8q/symbols/"
                },
                {
                    "description": "set sysroot",
                    "text": "set solib-search-path /lhome/android/imx-android11-L5.10-daily-imx8qxp-8qm-20210412/out/target/product/mek_8q/symbols/"
                },
                {
                    "description": "set architecture",
                    "text": "set architecture armv8-a"
                }
            ],
            "miDebuggerPath": "/mnt/d/RemoteDebug/android-ndk-r21e-linux-x86_64/android-ndk-r21e/prebuilt/linux-x86_64/bin/gdb",
            "miDebuggerServerAddress": "xx.xx.xx.xx:1234",
            "remote": true,
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
            }
        }
    ]
}`

**See error**

`(70667) <-1032-stack-list-frames 0 1000
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73438) ->1032^done,stack=[frame={level=\"0\",addr=\"0xef8fb72c\",func=\"??\",arch=\"armv8-a\"},frame={level=\"1\",addr=\"0xef8cd20c\",func=\"??\",arch=\"armv8-a\"}]\n"},"seq":3258}
1: (73438) ->1032^done,stack=[frame={level="0",addr="0xef8fb72c",func="??",arch="armv8-a"},frame={level="1",addr="0xef8cd20c",func="??",arch="armv8-a"}]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73439) ->(gdb)\n"},"seq":3260}
1: (73439) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73439) 1032: elapsed time 2772\n"},"seq":3262}
1: (73439) 1032: elapsed time 2772
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73452) <--exec-continue\n"},"seq":3264}
1: (73452) <--exec-continue
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73453) ->^running\n"},"seq":3266}
1: (73453) ->^running
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73453) ->*running,thread-id=\"all\"\n"},"seq":3268}
1: (73453) ->*running,thread-id="all"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73685) ->&\"Warning:\\n\"\n"},"seq":3270}
1: (73685) ->&"Warning:\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73685) ->&\"Cannot insert breakpoint 1.\\n\"\n"},"seq":3272}
1: (73685) ->&"Cannot insert breakpoint 1.\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73686) ->&\"Cannot access memory at address 0x10b08\\n\"\n"},"seq":3274}
1: (73686) ->&"Cannot access memory at address 0x10b08\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73686) ->&\"\\n\"\n"},"seq":3276}
1: (73686) ->&"\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73687) ->^error,msg=\"Command aborted.\"\n"},"seq":3278}
1: (73687) ->^error,msg="Command aborted."
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73688) ->(gdb)\n"},"seq":3280}
1: (73688) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (73692) Send Event AD7MessageEvent\n"},"seq":3282}
1: (73692) Send Event AD7MessageEvent
--> E (output): {"type":"event","event":"output","body":{"category":"stderr","output":"ERROR: Command aborted. See the output window for additional details.\n"},"seq":3284}
ERROR: Command aborted. See the output window for additional details.
`

**Comment by houlei1994** [comment]
Deleting breakpoint 1 can solve this problem.

**Comment by WardenGnaw** [comment]
Breakpoint 1 is the breakpoint the debug adapter uses to stop at main in order for us to setup GDB for the debugger while the process is stopped.

https://github.com/microsoft/MIEngine/blob/d3b2415500dd5a822d573cf96908c58a45bd83b1/src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs#L818

Does your application not have access to `main`?

**Comment by houlei1994** [comment]
> Breakpoint 1 is the breakpoint the debug adapter uses to stop at main in order for us to setup GDB for the debugger while the process is stopped.
> 
> https://github.com/microsoft/MIEngine/blob/d3b2415500dd5a822d573cf96908c58a45bd83b1/src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs#L818
> 
> Does your application not have access to `main`?
My application is an Android app, so maybe it not have an main function。
![1](https://user-images.githubusercontent.com/21049928/129151619-5656d415-ce6f-4ccf-94eb-ac2f0e5d74f4.png)

**Comment by WardenGnaw** [comment]
From https://stackoverflow.com/questions/1099640/is-there-a-function-in-android-analogous-to-int-main-in-c-c-which-contains-t:
> As far as an Android program is concerned there is no main(). There is a UI loop that the OS runs that makes calls to methods you define or override in your program. These methods are likely called from/defined in onCreate(), onStart(), onResume(), onReStart(), onPause(), onStop(), or onDestroy(). All these methods may be overriden in your program.

Can you see if you try to add a function breakpoint on `onCreate` and see if it hits? We may need to detect if we are debugging with android or have a special flag in the `launch.json` to indicate so to give a different spot to stop the debugger to initialize the debug session.

**Comment by gnaggnoyil** [comment]
Not related to vscode-cpptools perhaps though but @houlei1994 which WSL version and which distribution were you using when you encountered the bug?

**Comment by houlei1994** [comment]
> SL version and which distribution were you usin

wsl1 and ubuntu 18.04. The reason of this isssue is that there is no main function in android app. Deleting breakpoint 1 can resolve this problem.
