### ISSUE TITLE
C++ Extension Installation Problem

### ISSUE THREAD

**Issue by eventualzenith** [microsoft/vscode-cpptools#79]
I'm new to programming and coding (which is probably why I've messed up the installation process) and want to install this as a platform on which to run programs I learn. The instructions say to paste the command into Visual Studio Code (which I did) and then press enter (which I also did), but when I do, the cursor just moves onto a new line and does nothing. Like I said, it's probably just my ignorance that's stopping it from working, but please can someone tell me where I'm going wrong?

**Comment by IanMatthewHuff** [comment]
EventualZenith. Could you possibly share the instructions that you are looking at? I'm not fully sure from the context given so far what you are trying to do.

**Comment by delmyers** [comment]
@eventualzenith when you type Ctrl+P, a small text box should show up at the top of VsCode. That is where you should paste the text. See the example in the picture on the home page of vscode: http://code.visualstudio.com

**Comment by anorak** [comment]
I had this same issue.

For OSX VS you have to click the square box on the bottom left hand purple bar or (shift + command + P). This brings up a dialog box at the top filled with >Extensions:

Clear this text and paste in: ext install cpptools
Click on C/C++, it will install in a few seconds and prompt you to restart VS.

**Comment by eventualzenith** [comment]
Thank you! It's working perfectly now.

**Comment by anorak** [comment]
@eventualzenith Getting off topic from your original question, but since i can't PM you on GitHub...

Let me know if you figure out how to compile/build and run. I need to do some more digging, but haven't figured it out yet.

**Comment by sridmad** [comment]
@anorak 

You can build using tasks. See http://code.visualstudio.com/docs/editor/tasks for details
Setting up debugging for C++ is covered in https://code.visualstudio.com/docs/languages/cpp
