### ISSUE TITLE
VS code multithreading-cannot find path

### ISSUE THREAD

**Issue by itvhub-sketch** [microsoft/vscode-cpptools#7903]
have been trying to execute a simple c++ program in vs code. when I compile the program it is ok however, when I try to execute the file I get error message cannot find path because it does not exist. does anyone know what I am doing wrong, it seems as though I am following the tutorial correctly? I am using cygwin with windows 10 compiler I am posting a screenshot of the code and error codes.
![VS-2](https://user-images.githubusercontent.com/59344318/127767881-0dd66e9f-72f9-4bea-9ae7-d7bc48273b9b.PNG)
![VS-1](https://user-images.githubusercontent.com/59344318/127767892-2ad9eda1-625b-4477-a832-a790a09dc8bd.PNG)

**Comment by Colengms** [comment]
Hi @itvhub-sketch .  It looks like you are trying to build but have not provided all necessary include paths (`-I` args) to the compiler, so it's not able to find your header file.

I suspect you need to either:
A) Add a `-I` argument to the compile command line, to refer to the directory above `src`.
B) Change the `#include` statement to use a relative path: `#include "../lib/utility.h"`
C) Add a `-I` argument to the compile command line, to refer to the `src` directory, and use a path from that directory in your `#include` statement: `#include "lib/utility.h"`
or D) Add a `-I` argument to the compile command line, to refer to the `src/lib` directory, and use a path from that directory in your `#include` statement: `#include "utility.h"`
