### ISSUE TITLE
Architecture Arm64 not supported (code-server v3.10.2)

### ISSUE THREAD

**Issue by Gengar-lab** [microsoft/vscode-cpptools#7906]
Bug type: General

**Description**

- VS Code Version: v1.56.1
- C/C++ Extension Version: 1.5.1
- Other extensions you installed: None

- I am running VS Code through **code-server v3.10.2** on my Android. When I installed C/C++ Extension, It gave me error that Architecture arm64 is not supported .

**Expected behavior**
Extension should work.

**Screenshots**
![Screenshot_VHEditor](https://user-images.githubusercontent.com/42458260/127956964-dbfcc64c-15d0-45a3-bb3d-8db1e56198a4.jpg)

**Comment by sean-mcmanus** [comment]
What do you get when you type `process.platform` in the Help->Toggle Developer Console->Console? The result is probably an unsupported platform (not equal to win32, linux, or darwin), I'm guessing "android".

**Comment by sean-mcmanus** [comment]
You could get past that error this via modifying `<pathToExtensions>/extensions/ms-vscode.cpptools-1.5.1/dist/main.js` line 51129 from `        if (arch !== 'x64' && (process.platform !== 'win32' || (arch !== 'x86' && arch !== 'arm64')) && (process.platform !== 'linux' || (arch !== 'x64' && arch !== 'arm' && arch !== 'arm64')) && (process.platform !== 'darwin' || arch !== 'arm64')) {` to `        if (arch !== 'x64' && (process.platform !== 'win32' || (arch !== 'x86' && arch !== 'arm64')) && ((process.platform !== 'linux' && process.platform !== 'android') || (arch !== 'x64' && arch !== 'arm' && arch !== 'arm64')) && (process.platform !== 'darwin' || arch !== 'arm64')) {` where 'android' is whatever you get from running process.platform.

If you do that workaround, let us know if you encounter another error, possibly related to our binaries not being downloaded or not executable on android.

**Comment by Xoti-lab** [comment]
> You could get past that error this via modifying `<pathToExtensions>/extensions/ms-vscode.cpptools-1.5.1/dist/main.js` line 51129 from ` if (arch !== 'x64' && (process.platform !== 'win32' || (arch !== 'x86' && arch !== 'arm64')) && (process.platform !== 'linux' || (arch !== 'x64' && arch !== 'arm' && arch !== 'arm64')) && (process.platform !== 'darwin' || arch !== 'arm64')) {` to ` if (arch !== 'x64' && (process.platform !== 'win32' || (arch !== 'x86' && arch !== 'arm64')) && ((process.platform !== 'linux' && process.platform !== 'android') || (arch !== 'x64' && arch !== 'arm' && arch !== 'arm64')) && (process.platform !== 'darwin' || arch !== 'arm64')) {` where 'android' is whatever you get from running process.platform.

Yeah this workaround worked without any errors.

**Comment by Colengms** [comment]
This should be addressed in 1.6.0-insiders.
