### ISSUE TITLE
Include path search order with #include "somefile.h" and #include <somefile.h>

### ISSUE THREAD

**Issue by Xeenych** [microsoft/vscode-cpptools#7907]
Bug type: Language Service

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.58.2
- C/C++ Extension Version: 1.5.1

I have a .c file with 
```
#include "signal.h"
```
and a signal.h file somewhere in a workspace

When I ctrl+click on this line Intellisence opens file from %toolchain_dir%\include\, but not the one in a workspace so this produces other inmtellisence errors becuase my signal.h and toolcahin signal.h are completely different.

c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-arm",
            "compilerPath": "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2020-q4-major\\bin\\arm-none-eabi-g++",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}
```

**Expected behavior**
When I write #include <signal.h>  intellisence should search toolchain dir (compilerPath in settings).
When writing #include "signal.h" intellisence should search workspace dir (includePath in settings).

**Comment by sean-mcmanus** [comment]
You're using makefile tools, so your includePath and compilerPath may be coming from that.

But even if you were, you're also using recursive includes, "**" so those paths will go after the system include paths -- you can override that behavior by adding the path to your local signal.h to the includePath as a non-recursive include (doesn't end with `**`).

**Comment by Xeenych** [comment]
Ok, thanks, this is a workaround, but shouldn't this bug be fixed?

**Comment by bobbrow** [comment]
@sean-mcmanus it seems like it's more related to this: https://github.com/microsoft/vscode-cpptools/issues/2564.  It is probably a case that was missed.

**Comment by bobbrow** [comment]
No, I misread the issue.  What @sean-mcmanus said is correct and is a limitation of the recursive includes (but we log a workaround in the extension).  If the IntelliSense config is incorrect, it sounds like it's possibly an issue with the Makefile Tools extension or how it's configured.  Can you run the `C/C++: Log Diagnostics` command and share the output so that we can be sure where the configuration is coming from?

**Comment by Xeenych** [comment]
Sorry. I have to doublecheck this again.
I have another arm-none-eabi toolchain installed in one of the project's subfolders.
Also, disabling makefile tools extension solved this problem.

**Comment by bobbrow** [comment]
If there is an issue with the Makefile Tools extension, we'd be happy to help you troubleshoot that too.  You can start a discussion over here: https://github.com/microsoft/vscode-makefile-tools/issues/new

**Comment by Xeenych** [comment]
Sorry, I can't reproduce this. Everything is ok.
