### ISSUE TITLE
How to completely disable intelliSense linting?

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#791]
I need to disable all linting (or error output to the "PROBLEMS" view) and autocomplete. I want to use only "go/pick to definition/declaration" function.
At this moment I have these settings, which related to cpptools extension:
```
	"C_Cpp.autocomplete": "Disabled",
	"C_Cpp.errorSquiggles": "Disabled",
	"C_Cpp.formatting": "Disabled",
	"C_Cpp.intelliSenseEngine": "Tag Parser",
```

**But I still get "Include file not found in include path." errors in "PROBLEMS" view.**

![](https://habrastorage.org/web/0e3/7dc/aa9/0e37dcaa9c624de69f241ebea9839c14.png)

**So, is it possible at all?**

**Comment by bobbrow** [comment]
We don't have an option to turn off linting for include paths.  The extension won't work as you expect if include files cannot be opened so we need to let you know somehow that the the symbols defined in those files won't be available to you for goto/peek definition/declaration.

**Comment by yh-sb** [comment]
But in my case I don't setup include paths for cpptools and "go/pick to definition/declaration" works very well despite the fact that the .h files are in different folders in the project.

So, **"go/pick to definition/declaration" works well without include paths**, should be option to disable these annoying and senseless error messages about the include paths?

**Note:** the problem is related only to .h file which goes with GCC toolchain.

![](https://habrastorage.org/web/353/229/a72/353229a720c04d189502f9c5f7f4bc4b.png)

**Comment by bobbrow** [comment]
Exactly. Those files are not in your `browse.path` by default. You won't be able to goto definition or get tooltips on symbols defined in your GCC toolchain because they are not in the `browse.path`.  You have no need for these?

**Comment by yh-sb** [comment]
I write it one more time: "go/pick to definition/declaration" works well without include paths.

All *.h and *.c files which have well working "go to definition" function placed in directories, which doesn't described in c_cpp_properties.json and they are included like this (for example) "sys_rtc.h" or "v_convert.c" (without direct path in the source code).

Does cpptools extension make recursive search on the ${workspaceRoot} directory?

**Comment by sean-mcmanus** [comment]
The browse.path setting is recursive unless it ends with *, and the default settings includes ${workspaceRoot} in the browse.path (behind the scenes).

**Comment by bobbrow** [comment]
Yes, @r44083, I understand that goto definition/declaration will work for your files under ${workspaceRoot}.  I was asking whether you cared about this working for stuff defined in GCC headers.  It sounds like you don't.

We have no current plans to add a setting to disable these, but we can add this to our backlog.  The messages are not senseless, but I'm sorry if they annoy you.  There are other users would do care about goto definition/declaration working for files outside of the ${workspaceRoot} and appreciate getting feedback from the editor as to why.

**Comment by r44083** [comment]
Well, would you like to add this at least to the backlog.
