### ISSUE TITLE
"Go To Symbol in Workspace..." searchs are not "snappy" on large projects

### ISSUE THREAD

**Issue by noam-zur** [microsoft/vscode-cpptools#7914]
Bug type: Language Service

OS and Version: Windows10 (Version 2004)
VS Code Version: 1.58.2
C/C++ Extension Version: v1.5.1
"Go To Symbol in Workspace..."(CTRL+T) is very slow on large projects.

As a benchmark, I opened a workspace on Linux code base, and searched for "memory".
Results for the first search are abnormally long (~25 seconds).  **to be handled in another bug report (#7980)** 

**Results for additinal searchs are around ~3s.**
Since browsing large code bases requires many such searches, non-instant results becomes a burden.

**Notes:**

I set C_Cpp.intelliSenseEngine to "Tag Parser" (my preferred choice)
The workspace was fully parsed before running the search.
For comparison, on ** Source Insight IDE **,** results for the same symbol search are instant (<1s).**

**Expected behavior**
Full Workspace Symbols Search should return results faster (<1s)

**Comment by fearthecowboy** [comment]
A significant update to Go To Symbol has been published in the insiders build - see #11557

**Comment by Colengms** [comment]
This should be addressed in 1.19.4.
