### ISSUE TITLE
intellisense not honoring specified includePath

### ISSUE THREAD

**Issue by kellycouch** [microsoft/vscode-cpptools#7919]
Bug type: Language Service

- OS and Version: Windows 10 v1909 (10.0.18363)
- VS Code Version: v1.58.2
- C/C++ Extension Version: v1.5.1

Intellisense is not honoring the specified includePaths in a CMake project and thus not able to function (can't identify types, definitions, etc). The project is somewhat convoluted in setup (and I'll do my best to describe it), but I am struggling to identify why intellisense fails to include the paths specified.

project-root/
  proj-source/
  edk2/
    proj-source/ (symlink back to project-root/proj-source)
      CMakeList.txt
    MdePkg/Include/
      <VariousIncludeFiles.h>
  CMakeList.txt

Project is a Pkg/module to be built within the edk2 project: https://github.com/tianocore/edk2.
Project is CMake based with root CMakeList.txt that includes (add_subdirectory) additional under edk2/proj-source/CMakeList.txt. The build rules are only used to create custom_targets because the build system uses the edk2 custom build flow, which is not CMake based.

The project source under development is found project-root/proj-source. But this source only builds correctly when located within the folder project-root/edk2, thus a symlink is created to point here for the purpose of building.
The CMakeList produces 

I have attempted many permutations of changes to c_cpp_properties.json. Attaching files for reference. including debug output which has been scrubbed lightly.

Diagnostics.txt 'Custom browse configuration' included paths that I don't understand why they are present. I have only added include paths to the browse:path as an attempt to force it to include these paths, but it did not work. I've tried with this clear as well.

I am not concerned about CMake build of this project, just to get the intellisense working as expected to aid in development.

**Steps to reproduce**
1. Force rebuild of Intellisense database. 
2. Observe that intellisense is complete, but squiggly lines appear under most header files.
3. Review debug logs and note that specified include paths are NOT included, while others are unexpectedly included.

**Expected behavior**
Parse the includepaths as provided in json settings.

**Code sample and logs**
Update 8/5: Added settings files to zip:
[intellisense-bug-report.zip](https://github.com/microsoft/vscode-cpptools/files/6939716/intellisense-bug-report.zip)

**Screenshots**
Example of failed include.
![image](https://user-images.githubusercontent.com/26443855/128266576-56eec70f-c224-48b6-8aec-671733a31c1c.png)

* Please excuse any typos. Scrubbed the files for project specific names, so may have some unintended inaccuracies.

**Comment by Colengms** [comment]
Hi @kellycouch .  I see from your `c_cpp_properties.json` that you are using the CMake Tools extension.  `"configurationProvider": "ms-vscode.cmake-tools",`

However, I don't see any configuration information provided by CMake Tools in your log output from the C/C++ output channel.  Though, it's possible that log is incomplete, as I don't see where it indicates the source/header file being opened.  Could you provide the contents of the C/C++ output leading up to opening the file that repros the issue?

Also, have you run the CMake Tools command `CMake: Configure`?  It's necessary to configure CMake through CMake Tools to enable it to provide configuration information to the C/C++ Extension.  Whenever a `configurationProvider` is specified in `c_cpp_properties.json`, any file that it successfully provides a configuration for will use only those settings from CMake Tools - the other values in `c_cpp_properties.json` will not be used.

I see that the file referred to by your `Log Diagnostics` output is a header file and that we were unable to fine an appropriate source file to associate with it, so opened it in `--header_only_fallback` mode.  When opening a header file, we try to find an appropriate source file that includes that header, as configuration providers provide configurations for source files and not header files.  I also see in your in C/C++ output that Tag Parsing was still in progress.  Until Tag Parsing is complete, we likely have not finished building the mapping of source files and headers, so this may explain why we were not able to find a source file to associate with the header file.

I'd suggest waiting for Tag Parsing to complete (It will log "Done parsing remaining files." when done), running CMake Tool's "Configure" command, then opening the file.  If a header, a source file should be chosen for it.  If that source file is tracked by CMake Tools, you should see a custom configuration provided for that source file in the log output.  If that doesn't lead to correctly configured IntelliSense, could you provide the C/C++ output while doing these steps?

**Comment by kellycouch** [comment]
Hi @Colengms. 

> Whenever a configurationProvider is specified in c_cpp_properties.json, any file that it successfully provides a configuration for will use only those settings from CMake Tools - the other values in c_cpp_properties.json will not be used.

I wonder if this could be the issue. For this project, CMake is being used just as a wrapper to invoke a custom build script (EDK2 doesn't support a build flow using CMake natively). So, CMake doesn't have information about source, headers, etc. that it normally does. 
Can I simply remove the configurationProvider or choose an alternative? Would that enable the c_cpp_properties.json values to be used for includePaths?

Appreciate your response. If above theory isn't on the right track, I'll work on providing additional folllow-up based on your other comments.

**Comment by Colengms** [comment]
> Can I simply remove the configurationProvider or choose an alternative?

Yes, absolutely.  With `configurationProvider` removed, it should use the other settings in your `c_cpp_properties.json`.

It's possible we automatically added the `configurationProvider` when you created your `c_cpp_properties.json`, as we will default to using a custom configuration provider that registers with cpptools, if it's the only one to do so.  Due to the existence of a `CMakeLists.txt`, CMake Tools likely registered itself with cpptools.
