### ISSUE TITLE
Support standard `.editorconfig` fields

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#7920]
Since `cpp_*` fields in `.editorconfig` files are supported (when `"C_Cpp.formatting": "vcFormat"`), users may expect the standard `.editorconfig` fields to also be applied.  Currently, this requires installing another extension specifically for that support.  (i.e. the "EditorConfig for Visual Studio Code" extension)

Supporting those fields would seem to involve setting the equivalent VS Code settings, as they are applied in scenarios other than processing a "Format" operation.  Also, unlike `.editorconfig`, the VS Code setting equivalent of `indent_style`, `indent_size`, `tab_width`, `end_of_line`, etc., could not be more granular than workspace-level.

**Comment by ChrisGuzak** [comment]
This is very important for my intended use in the OS.2020 repo. thanks for filing this.

**Comment by bobbrow** [comment]
Does it present a problem for us to support those if the EditorConfig extension is installed?  IOW, will the changes be applied twice?

**Comment by Colengms** [comment]
@bobbrow Based on it's code [here](https://github.com/editorconfig/editorconfig-vscode), it looks like it will apply the settings directly to the document in response to notifications from `onDidChangeActiveTextEditor` or `onDidChangeWindowState`.  With that approach instead of modifying settings, we can support finer (per folder) granularity.  I assume the extension that changes the options last would take precedence.  As long as each extension is setting the same values for these settings, it should work as expected.

**Comment by Colengms** [comment]
This should be addressed in 1.6.0-insiders.

**Comment by bl-ue** [comment]
>This is very important for my intended use in the OS.2020 repo. thanks for filing this.

@ChrisGuzak what's that?
