### ISSUE TITLE
Failed to parse "\.vscode\c_cpp_properties.json"

### ISSUE THREAD

**Issue by NoahELE** [microsoft/vscode-cpptools#7921]
Bug type: Language Service

**Describe the bug**
- OS and Version: win10
- VS Code Version: 1.58.2
- C/C++ Extension Version: 1.5.1
- When opening c file that is not in a project, the default compiler path and default include path don't work. It keeps showing `Failed to parse "\.vscode\c_cpp_properties.json": ENOENT: no such file or directory, open '\.vscode\c_cpp_properties.json'`.
![image](https://user-images.githubusercontent.com/49080986/128295770-2d7ec929-3e04-4c68-ba97-66097c94a0c6.png)
![image](https://user-images.githubusercontent.com/49080986/128295795-a7d42b6a-caef-4572-8cd6-2a7c4a82afca.png)

**Comment by Colengms** [comment]
Hi @NoahELE .  I'm not easily able to repro this error.  With a folder open with no `c_cpp_properties.json` (or a VS Code window with no folder open), and using similar settings as shown in your image, I'm not able to trigger that error when opening a C file (that is not under the opened folder).  There would seem to be more details about your setup that we need to understand to repro the issue.

Could you try enabling debug logging using `"C_Cpp.loggingLevel": "Debug"`, and provide the output the C/C++ output channel leading up to the repro?

**Comment by NoahELE** [comment]
Hi, sorry, the error seems appear randomly, can't repro it this morning. However I still have problems with code completion, I'll open a new issue.
