### ISSUE TITLE
Class keyword is not highlighted when hovering over the name of a templated class.

### ISSUE THREAD

**Issue by BlueStaggo** [microsoft/vscode-cpptools#7922]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 x64 1909
- VS Code Version: 1.58.2
- C/C++ Extension Version: 1.5.1
- Other extensions you installed (and if the issue persists after disabling them): C++ Syntax (issue still persists)

When you hover over a class name with a template, the `class` keyword is not highlighted.

**Steps to reproduce**

1. Create an empty class called `clazz`.
2. Hover over `clazz`; the `class` keyword is highlighted.
3. Create an empty class called `clazz_generic` that uses a template.
4. Hover over `clazz_generic`; the `class` keyword before the class name is not highlighted but the `template` and `class` keyword before the type parameter are highlighted correctly.

**Expected behavior**
The `class` keyword before the class name is highlighted correctly.

**Code sample and logs**
```cpp
- Code sample
/**
 * @brief Highlighted correctly
 */
class clazz
{

};

/**
 * @brief Highlighted incorrectly
 */
template <typename T>
class clazz_generic
{

};
```
- Configurations in `c_cpp_properties.json`
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/src"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "cStandard": "c17",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe",
            "intelliSenseMode": "windows-msvc-x64",
            "cppStandard": "c++20"
        }
    ],
    "version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette (doesn't help)

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) (doesn't help)

**Screenshots**

![image](https://user-images.githubusercontent.com/71090710/128334477-6fc087f2-f5c2-446e-88bf-a314131b288b.png)

**Additional context**

None

**Comment by Colengms** [comment]
Hi @BlueStaggo .  The C/C++ Extension does not actually provide colorization/highlighting for the contents of hover tips.  Those are colored by VS Code's syntax highlighting support, based on the TextMate grammar contributed here: https://github.com/jeff-hykin/cpp-textmate-grammar   You will see the same colorization if you copy the contents of the hover tip, paste it into code, and disable the C/C++ extension (and reload the window).

That said, this issue could potentially be addressed by us by adding a semicolon to the hover tip to make it valid C++ code.  I'll investigate whether we can safely make that change.
