### ISSUE TITLE
No auto completion as to include for single c file

### ISSUE THREAD

**Issue by NoahELE** [microsoft/vscode-cpptools#7928]
Bug type: Language Service

**Describe the bug**
- OS and Version: win 10
- VS Code Version: 1.59.0
- C/C++ Extension Version: 1.5.1
- When opening a single c file, the auto completion for #include does not work.
![image](https://user-images.githubusercontent.com/49080986/128452541-43797d46-d8a9-4208-af94-69dd56b4a605.png)
- However, with no other change, just open the folder in vscode, the completion will work.
![image](https://user-images.githubusercontent.com/49080986/128452525-51328a53-fdf9-4429-9130-df76cd72063d.png)

**Expected behavior**

I expect include completion work all the time, regardless of whether I am opening a single file or a folder.

**Code sample and logs**

- Code sample: as shown in screenshot

- Configurations in `c_cpp_properties.json`: no c_cpp_properties.json

**Comment by sean-mcmanus** [comment]
This may be "by design" or there may be a reason it doesn't work (I don't remember)...in general, our extension doesn't support the "open file" scenario well and other scenarios also require a folder to be open. We could investigate later...

**Comment by Colengms** [comment]
Hi @NoahELE . I'm not able to repro this issue with 1.7.0-insiders2.  Could you confirm if you are still seeing this?
