### ISSUE TITLE
Remote debugging in VSCode Ubuntu 17.04 exits unexpectedly with error 255

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#793]
I'm debugging a multi-threaded application running on CentOS 6.9 with GDB 7.2-92 from Ubuntu 17.04. The application only spawns two threads and when breaking in the second thread VSCode does not go to the break point though the output shows that the application has been interrupted. The call stack window shows there are two threads but when I want to expand them the loader spins until the gdb session exits with the output as shown in the [log.txt](https://github.com/Microsoft/vscode-cpptools/files/1046805/log.txt)  file. I have tried using GDB 7.12 but the error persists.

The debugging works fine with Eclipse on CentOS 6.9 but I'd prefer to work on a more modern OS and use VSCode. An Omnisharp user seemed to have the same problem  and he fixed it by downgrading his kernel [(see this issue)](https://github.com/OmniSharp/omnisharp-vscode/issues/839).

Below is the content of my launch.json code:

```
{
    "version": "0.2.0",
    "configurations": [   
         {
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "name": "RTSP Proxy",
            "type": "cppdbg",
            "program": "${workspaceRoot}/app-RtspProxy/m2RtspProxy",
            "stopAtEntry": true,
            "externalConsole": true,
            "args": [
                "--d",
                "-port",
                "8080"
            ],

            "linux": 
            {
                "MIMode": "gdb",  
                "logging": {
                    "moduleLoad": true,
                    "trace": true,
                    "engineLogging": true,
                    "programOutput": true,
                    "exceptions": true
                },
                
		// update this to use your user details
                "pipeTransport": {
                    "pipeCwd": "",
                    "pipeProgram": "ssh",
                    "pipeArgs": [
                        "jaco@centos6"
                    ],
                    "debuggerPath": "gdb"   
                }
            }
        }
    ]
}
```

Lines 28 to 37 in [log.txt](https://github.com/Microsoft/vscode-cpptools/files/1046805/log.txt) seem to be of interest:

> ERROR: GDB exited unexpectedly with exit code 255 (0xFF). Debugging will now abort.
> The program '/home/jaco/projects/envr-m2/app-RtspProxy/m2RtspProxy' has exited with code -1 (0xffffffff).
> EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
>   at OpenDebugAD7.AD7DebugSession.StackTrace (Int32 threadReference, Int32 startFrame, Int32 levels) <0x41f3bf00 + 0x0021b> in <filename unknown>:0 
>   at OpenDebug.DebugSession.Dispatch (System.String command, System.Object args) <0x41e33bc0 + 0x01fcb> in <filename unknown>:0 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)
>   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet] (System.Runtime.CompilerServices.CallSite site, System.Dynamic.T0 arg0, System.Dynamic.T1 arg1, System.Dynamic.T2 arg2) <0x41dfe230 + 0x001b9> in <filename unknown>:0 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)
>   at OpenDebug.Program+<>c__DisplayClass6_0.<Dispatch>b__2 (System.String command, System.Object args, IResponder responder) <0x41dee5c0 + 0x014c7> in <filename unknown>:0 
> C disconnect: {"restart":false}

**Comment by pieandcakes** [comment]
@soundssource Can you tell me which version of the extension you are using? Also, can you enable logging and paste a log around the time this happens so I know what we're getting?
`"logging" : { "trace": true, "traceResponse": true, "engineLogging": true }`

**Comment by ghost** [comment]
@pieandcakes I'm using version 0.11.2 of the plugin. I have to point out that I was testing the setup using a CentOS container in LXC. I'll test it with a lab machine and let you know whether it makes any difference.  Below is the log output generated when it "hits" the breakpoint and becomes unresponsive up until GDB decides to exit:

>  Thread 2 "m2RtspProxy" hit Breakpoint 2, Exp::EncodeFileObserver::notifyFileChanged (this=0x807bb90, reason=Exp::OsalFileMonitor::FileObserver::R_INACTIVITY, fileOperations=...) at RpUrlTranslator.cpp:131
> E output: {"category":"stdout","output":"131\t    if (fileOperations.size() > 0) // change occured on file through\n","data":null,"type":"output"}
> 131	    if (fileOperations.size() > 0) // change occured on file through
> 1: (93259) <-1023-thread-info
> 1: (93261) ->1023^done,threads=[{id="1",target-id="Thread 0xf700c710 (LWP 2108)",name="m2RtspProxy",frame={level="0",addr="0x4eb7cf33",func="__call_pselect6",args=[],from="/lib/libc.so.6"},state="stopped",core="0"},{id="2",target-id="Thread 0xf7003b70 (LWP 2113)",name="m2RtspProxy",frame={level="0",addr="0xf7fc8eae",func="Exp::EncodeFileObserver::notifyFileChanged",args=[{name="this",value="0x807bb90"},{name="reason",value="Exp::OsalFileMonitor::FileObserver::R_INACTIVITY"},{name="fileOperations",value="..."}],file="RpUrlTranslator.cpp",fullname="/home/jaco/projects/envr-m2/rp/RpUrlTranslator.cpp",line="131"},state="stopped",core="0"}],current-thread-id="2"
> 1: (93261) ->(gdb)
> 1: (93261) 1023: elapsed time 1
> 1: (93261) <-1024-stack-list-frames 0 1000
> 1: (93306) ->1024^done,stack=[frame={level="0",addr="0xf7fc8eae",func="Exp::EncodeFileObserver::notifyFileChanged",file="RpUrlTranslator.cpp",fullname="/home/jaco/projects/envr-m2/rp/RpUrlTranslator.cpp",line="131"},frame={level="1",addr="0xf7a9289f",func="Exp::OsalFileMonitor::Imp::FileObservers::notifyObservers",file="OsalFileMonitorLinux.cpp",fullname="/home/jaco/projects/envr-m2/osal/OsalFileMonitorLinux.cpp",line="184"},frame={level="2",addr="0xf7a951ce",func="Exp::OsalFileMonitor::Imp::notifyReadTimeout",file="OsalFileMonitorLinux.cpp",fullname="/home/jaco/projects/envr-m2/osal/OsalFileMonitorLinux.cpp",line="817"},frame={level="3",addr="0xf7a91ac9",func="Exp::OsalFileMonitor::Imp::ReadObserver::notifyReadTimeout",file="OsalFileMonitorLinux.cpp",fullname="/home/jaco/projects/envr-m2/osal/OsalFileMonitorLinux.cpp",line="900"},frame={level="4",addr="0xf7ebc5c4",func="Exp::FdSelector::Worker::notifyTimeout",file="FdSelector.cpp",fullname="/home/jaco/projects/envr-m2/fd/FdSelector.cpp",line="2549"},frame={level="5",addr="0xf7ec25bb",func="Exp::FdSelector::Worker::checkFdInfoList<Exp::FdSelector::Worker::ReadFdInfo>",file="FdSelector.cpp",fullname="/home/jaco/projects/envr-m2/fd/FdSelector.cpp",line="2341"},frame={level="6",addr="0xf7ebaebc",func="Exp::FdSelector::Worker::processSelections",file="FdSelector.cpp",fullname="/home/jaco/projects/envr-m2/fd/FdSelector.cpp",line="1583"},frame={level="7",addr="0xf7eb9659",func="Exp::FdSelector::Worker::work",file="FdSelector.cpp",fullname="/home/jaco/projects/envr-m2/fd/FdSelector.cpp",line="1020"},frame={level="8",addr="0xf7eaf671",func="(anonymous namespace)::FdSelectorThread::threadStart",file="FdSelector.cpp",fullname="/home/jaco/projects/envr-m2/fd/FdSelector.cpp",line="2677"},frame={level="9",addr="0xf7a3217c",func="Exp::ThrdVehicle::startThread",file="ThrdThread.cpp",fullname="/home/jaco/projects/envr-m2/thrd/ThrdThread.cpp",line="64"},frame={level="10",addr="0xf7a33400",func="Exp::ThrdVehicleLinux::specialStarter",file="ThrdThreadLinux.cpp",fullname="/home/jaco/projects/envr-m2/thrd/ThrdThreadLinux.cpp",line="436"},frame={level="11",addr="0xf7a32569",func="Exp::ThrdVehicleLinuxStarter::ThrdVehicleLinuxStarter",file="ThrdThreadLinux.cpp",fullname="/home/jaco/projects/envr-m2/thrd/ThrdThreadLinux.cpp",line="105"},frame={level="12",addr="0xf7a32420",func="(anonymous namespace)::startPthread",file="ThrdThreadLinux.cpp",fullname="/home/jaco/projects/envr-m2/thrd/ThrdThreadLinux.cpp",line="40"},frame={level="13",addr="0x4ec40bc9",func="start_thread",from="/lib/libpthread.so.0"},frame={level="14",addr="0x4eb7d04e",func="clone",from="/lib/libc.so.6"}]
> 1: (93306) ->(gdb)
> 1: (93306) 1024: elapsed time 45
> 1: (93307) <-1025-var-delete var1
> 1: (93308) ->1025^done,ndeleted="1"
> 1: (93308) ->(gdb)
> 1: (93308) 1025: elapsed time 0
> 1: (93308) <-1026-var-delete var2
> 1: (93308) ->1026^done,ndeleted="1"
> 1: (93309) ->(gdb)
> 1: (93309) 1026: elapsed time 0
> 1: (93309) <-1027-var-delete var3
> 1: (93309) ->1027^done,ndeleted="1"
> 1: (93309) ->(gdb)
> 1: (93309) 1027: elapsed time 0
> E stopped: {"threadId":2113,"reason":"breakpoint","source":{"name":"RpUrlTranslator.cpp","path":"/home/jaco/projects/envr-m2/rp/RpUrlTranslator.cpp","sourceReference":0},"line":131,"column":1,"text":null,"allThreadsStopped":true,"type":"stopped"}
> C threads: null
>  R: {"success":true,"message":null,"request_seq":14,"command":"threads","body":{"threads":[{"id":2108,"name":"m2RtspProxy"},{"id":2113,"name":"m2RtspProxy"}]},"running":false,"refs":null,"seq":0,"type":"response"}
> C stackTrace: {"threadId":2113,"startFrame":0,"levels":20}
> 1: (93323) <-1028-stack-list-arguments 2 0 14
> 1: (266432) "ssh" exited with code 255 (0xFF).
> 1: (266434) <-logout
> E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/MIEngine/DebuggerAborted","data":{"VS.Diagnostics.Debugger.MIEngine.DebuggerName":"GDB","VS.Diagnostics.Debugger.MIEngine.LastSentCommandName":"-stack-list-arguments","VS.Diagnostics.Debugger.MIEngine.DebuggerExitCode":"255 (0xFF)"},"type":"output"}
> E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/NonFatalError","data":{"VS.Diagnostics.Debugger.NonFatalError.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.NonFatalError.ExceptionType":"System.NullReferenceException","VS.Diagnostics.Debugger.NonFatalError.ExceptionStack":"  at OpenDebugAD7.AD7DebugSession.StackTrace (Int32 threadReference, Int32 startFrame, Int32 levels) <0x41002000 + 0x0021b> in <filename unknown>:0 \n  at OpenDebug.DebugSession.Dispatch (System.String command, System.Object args) <0x40ef8bc0 + 0x01fcb> in <filename unknown>:0 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)\n  at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet] (System.Runtime.CompilerServices.CallSite site, System.Dynamic.T0 arg0, System.Dynamic.T1 arg1, System.Dynamic.T2 arg2) <0x40ec3230 + 0x001b9> in <filename unknown>:0 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)\n  at OpenDebug.Program+<>c__DisplayClass6_0.<Dispatch>b__2 (System.String command, System.Object args, IResponder responder) <0x40eb35c0 + 0x014c7> in <filename unknown>:0 ","VS.Diagnostics.Debugger.NonFatalError.HResult":-2147467261,"VS.Diagnostics.Debugger.EngineVersion":"14.0.40306.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.HostVersion":"1.0.30301.1"},"type":"output"}
> EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
>   at OpenDebugAD7.AD7DebugSession.StackTrace (Int32 threadReference, Int32 startFrame, Int32 levels) <0x41002000 + 0x0021b> in <filename unknown>:0
> at OpenDebug.DebugSession.Dispatch (System.String command, System.Object args) <0x40ef8bc0 + 0x01fcb> in <filename unknown>:0 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)
>   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet] (System.Runtime.CompilerServices.CallSite site, System.Dynamic.T0 arg0, System.Dynamic.T1 arg1, System.Dynamic.T2 arg2) <0x40ec3230 + 0x001b9> in <filename unknown>:0 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)
>   at OpenDebug.Program+<>c__DisplayClass6_0.<Dispatch>b__2 (System.String command, System.Object args, IResponder responder) <0x40eb35c0 + 0x014c7> in <filename unknown>:0 
> E output: {"category":"stderr","output":"ERROR: GDB exited unexpectedly with exit code 255 (0xFF). Debugging will now abort.\n","data":null,"type":"output"}
> ERROR: GDB exited unexpectedly with exit code 255 (0xFF). Debugging will now abort.
> E output: {"category":"console","output":"The program '/home/jaco/projects/envr-m2/app-RtspProxy/m2RtspProxy' has exited with code -1 (0xffffffff).\r\n\n","data":null,"type":"output"}
> The program '/home/jaco/projects/envr-m2/app-RtspProxy/m2RtspProxy' has exited with code -1 (0xffffffff).
> 
> E exited: {"exitCode":-1,"type":"exited"}
> E terminated: {"type":"terminated"}
> E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.40306.1","VS.Diagnostics.Debugger.HostVersion":"1.0.30301.1","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":2},"type":"output"}
>  R: {"success":false,"message":"error while processing request 'stackTrace' (exception: Internal error in OpenDebugAD7. Exception of type 'System.NullReferenceException' was thrown.\r\n\r\n  at OpenDebugAD7.AD7DebugSession.StackTrace (Int32 threadReference, Int32 startFrame, Int32 levels) <0x41002000 + 0x0021b> in <filename unknown>:0 \n  at OpenDebug.DebugSession.Dispatch (System.String command, System.Object args) <0x40ef8bc0 + 0x01fcb> in <filename unknown>:0 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)\n  at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet] (System.Runtime.CompilerServices.CallSite site, System.Dynamic.T0 arg0, System.Dynamic.T1 arg1, System.Dynamic.T2 arg2) <0x40ec3230 + 0x001b9> in <filename unknown>:0 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)\n  at OpenDebug.Program+<>c__DisplayClass6_0.<Dispatch>b__2 (System.String command, System.Object args, IResponder responder) <0x40eb35c0 + 0x014c7> in <filename unknown>:0 )","request_seq":15,"command":"stackTrace","body":{"error":{"id":1104,"format":"error while processing request '{_request}' (exception: {_exception})","variables":{"_request":"stackTrace","_exception":"Internal error in OpenDebugAD7. Exception of type 'System.NullReferenceException' was thrown.\r\n\r\n  at OpenDebugAD7.AD7DebugSession.StackTrace (Int32 threadReference, Int32 startFrame, Int32 levels) <0x41002000 + 0x0021b> in <filename unknown>:0 \n  at OpenDebug.DebugSession.Dispatch (System.String command, System.Object args) <0x40ef8bc0 + 0x01fcb> in <filename unknown>:0 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)\n  at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet] (System.Runtime.CompilerServices.CallSite site, System.Dynamic.T0 arg0, System.Dynamic.T1 arg1, System.Dynamic.T2 arg2) <0x40ec3230 + 0x001b9> in <filename unknown>:0 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,OpenDebug.IDebugSession,string,object)\n  at OpenDebug.Program+<>c__DisplayClass6_0.<Dispatch>b__2 (System.String command, System.Object args, IResponder responder) <0x40eb35c0 + 0x014c7> in <filename unknown>:0 "}}},"running":false,"refs":null,"seq":0,"type":"response"}
> C disconnect: {"restart":false}
>  R: {"success":true,"message":null,"request_seq":16,"command":"disconnect","body":null,"running":false,"refs":null,"seq":0,"type":"response"}

**Comment by pieandcakes** [comment]
>1: (93323) <-1028-stack-list-arguments 2 0 14
1: (266432) "ssh" exited with code 255 (0xFF).
1: (266434) <-logout

It looks like we request `stack-list-arguments` and then the ssh connection to gdb goes down which is unexpected. The System.NullReferenceException is because we're trying to send additional information but the connection is broken. 

This looks like a gdb or ssh issue as it is crashing from the response that gdb is sending or gdb is crashing on the remote end. I'm wondering if there is an issue with the gdb version you are running. Maybe try and update that? The other option would be to try it on the machine itself and see if it has the same issue. I"d be interested in what `-stack-list-arguments `returns that is taking down the ssh pipe.

**Comment by ghost** [comment]
I have built and installed gdb 7.12 previously and it behaves in exactly the same way. I'll still try it with the lab machine instead of the lxc container. It makes sense that it's an ssh/gdb issue as it works fine with Eclipse and gdb on the local machine. Getting VSCode to run on the machine itself is a bit of a headache due to compiler versions. Is there any way I can get the `-stack-list-arguments` for you?

**Comment by pieandcakes** [comment]
@soundssource you can. If you only have `"logging": { "engineLogging": true }`  on, you will get the list of MI commands we send gdb. You can then start gdb in MI-mode by executing gdb with the `--interpreter=mi` flag and feed it the `mi` commands one by one until you get to that `-stack-list-arguments` call. All commands that start with `<-` are ones we send gdb whereas `->` is the response we get from gdb. The number afterwards is just a sequence number and you don't need to send it.

**Comment by ghost** [comment]
I have verified that it's not related to the lxc container as the same thing happens if I ssh into a machine in the lab running CentOS. I'll post the output of the suggested test as soon as I get around to it.

**Comment by pieandcakes** [comment]
It sounds like either `ssh` or `gdb` that you are using is not liking something. I wonder if that call is returning `too` much data.

**Comment by ghost** [comment]
So I isolated the commands and ran them using different versions of gdb:

```
# run gdb
gdb --interpreter=mi

# execute initial setup
set target-async on
interpreter-exec console "set pagination off"
set solib-search-path /home/jaco/projects/envr-m2/app-RtspProxy:
set stop-on-solib-events 1
-environment-cd /home/jaco/projects/envr-m2
-file-exec-and-symbols /home/jaco/projects/envr-m2/app-RtspProxy/m2RtspProxy
interpreter-exec console "show architecture"
-exec-arguments --d -port 8080
-break-insert main
-break-insert -f RpUrlTranslator.cpp:131
-exec-run
-thread-info 1
-break-info 2
interpreter-exec console "info sharedlibrary"
-exec-continue
-break-info 2
-interpreter-exec console "info sharedlibrary"
-exec-continue
-thread-info
-stack-list-frames 0 1000
-exec-continue
-thread-info 2
-exec-interrupt
-break-insert -f RpUrlTranslator.cpp:131
-symbol-list-lines /home/jaco/projects/envr-m2/rp/RpUrlTranslator.cpp
-exec-continue

# execute once breakpoint is hit
-thread-info
-stack-list-frames 0 1000
-stack-list-arguments 2 0 14
```
Which results in gdb responding with a segmentation fault. Using `-stack-list-arguments 0` works and it returns:

```
-stack-list-arguments 0
^done,stack-args=[frame={level="0",args=[name="this",name="reason",name="fileOperations"]},frame={level="1",args=[name="this",name="reason",name="fileOperations"]},frame={level="2",args=[name="this",name="fd",name="timerOp",name="timerVal",name="now",name="directCommands"]},frame={level="3",args=[name="this",name="fd",name="timerOp",name="timerVal",name="now",name="directCommands"]},frame={level="4",args=[name="i",name="info",name="timerOp",name="now",name="directCommands"]},frame={level="5",args=[name="this",name="infos",name="i",name="fdSet",name="fdMask",name="haveRealFds",name="maxFdPlus1",name="directCommands"]},frame={level="6",args=[name="this",name="readFds",name="writeFds",name="exceptionFds",name="haveWriteFds",name="haveExceptionFds",name="maxFdPlus1",name="tv"]},frame={level="7",args=[name="this",name="cleanup",name="signalMask",name="stopCallback"]},frame={level="8",args=[name="this"]},frame={level="9",args=[name="this"]},frame={level="10",args=[name="this"]},frame={level="11",args=[name="this",name="tv"]},frame={level="12",args=[name="vehicle"]},frame={level="13",args=[]},frame={level="14",args=[]}]
```
But setting the print-values parameter to either 1 or 2 causes a segmentation fault. So this seems to be a gdb related issue. I get the same results for gdb 7.2, 7.12 and 7.12.1.

**Comment by pieandcakes** [comment]
@soundssource If you try a simple app does it fail on the same thing? Might be an issue on Ubuntu 17.04. 

I'm on Ubuntu 16.04 and gdb 7.11.1 and I haven't seen this behavior.

**Comment by ghost** [comment]
I was running gdb directly on the Linux container eliminating ssh. I'll give your setup a go and see if solves anything. I'll also try to see if attaching - rather than launching it - makes a difference.

I have used the setup to debug a different application that spawns quite a few threads but doesn't give the same problem. It does seem to be a problem unique to the code base I'm working on. I guess there would have to be something seriously wrong in the code to have gdb crash. The application runs fine if I never break in the second thread.

I'll post updates as soon as I can.

**Comment by ghost** [comment]
I haven't had any luck with my problem but [Issue 103](https://github.com/Microsoft/vscode-cpptools/issues/103) seems to be related. Downgrading GDB worked for them. Seems to be a problem with the **MI interface** when calling **-stack-list-arguments**. Hopefully, it helps somebody else with a similar problem.

**Comment by pieandcakes** [comment]
@soundssource Might be worth filing a bug with gdb if you can get a repro and a stack trace for them so someone working on that project can fix it.
