### ISSUE TITLE
Unable to debug as of VSCode 1.58

### ISSUE THREAD

**Issue by jonas-k** [microsoft/vscode-cpptools#7930]
After updating to VSCode 1.58, C++ debugging stopped working. I tried different versions of the cpptools extension including 1.4.1, 1.5.0 and 1.5.1. All of these worked fine in VSCode 1.57. It is still broken in VSCode 1.59.

The issue is that VSCode doesn't turn orange to indicate it is in debugging mode and that breakpoints don't work anymore. Assertions still halt the program, but it is not possible to continue from there since VSCode doesn't show the continue button. (It still shows the pause symbol as if the program was still running.)

My launch configuration looks like this:
```
{
	"name": "Name",
	"preLaunchTask": "Build App",
	"type": "cppdbg",
	"MIMode": "lldb",
	"request": "launch",
	"expressions": "native",
	"cwd": "${workspaceFolder}",
	"program": "path/to/executable"
}
```

**Comment by sean-mcmanus** [comment]
@WardenGnaw Is this a VS Code bug?

@jonas-k You may want to file a VS Code bug: https://github.com/microsoft/vscode/issues

**Comment by jonas-k** [comment]
Alright I'l file a VS Code bug. Thank you for looking at it.

**Comment by jonas-k** [comment]
The VSCode bug ticket is: [https://github.com/microsoft/vscode/issues/130419](https://github.com/microsoft/vscode/issues/130419)
Unfortunately they are very fast to close anything that could have something to do with an extension, so they closed this one as well.
Can you reproduce this issue on your side?

**Comment by sunpihai-up** [comment]
![image](https://user-images.githubusercontent.com/64977779/129734339-ed5519c9-0698-4dfa-94b4-43720c8a09f0.png)
Is your situation like this?
The cpp file will be compiled, but the exe file will not be run.

**Comment by sunpihai-up** [comment]
> ![image](https://user-images.githubusercontent.com/64977779/129734339-ed5519c9-0698-4dfa-94b4-43720c8a09f0.png)
> Is your situation like this?
> The cpp file will be compiled, but the exe file will not be run.

I also encountered the same situation. My solution is to reinstall the C++ extension and it will work normally. But after restarting, you need to reinstall the C++ extension again

**Comment by jonas-k** [comment]
For me the pause button is not greyed out, but breakpoints will not hit. I could temporarily solve the issue by deleting the file ~/Library/Application Support/Code/CachedExtensions/user
Then after restarting VS Code, debugging works for one session. For the next session it is necessary again to delete the file and restart VS Code.
