### ISSUE TITLE
Get rid of association files

### ISSUE THREAD

**Issue by AlexDev2020** [microsoft/vscode-cpptools#7934]
Type: Feature Request

The vscode-cpptools extension creates association files, for example when we open standard library files. This is because these files do not have an extension to detect the language. You can now get rid of this association mechanism as vscode has learned to guess the language based on the trained model. I think you can do that when you open a standard library file (for example, iostream), the association file is not created, and the language is determined by the model. I think that would be cool!

**Comment by sean-mcmanus** [comment]
I don't see this work with `#include <vector>` with msvc headers with VS Code Insiders. Do you have examples of it working or a link to the VS Code issue about this?

You can also change C_Cpp.autoAddFileAssocations to false to manually disable it.

**Comment by AlexDev2020** [comment]
@sean-mcmanus  
I didn't say it works now. If I turn off the addition of associations, the editor will have plain text if I open the <vector>.
I meant that maybe you can implement such an opportunity so that when you open
file with C ++ code without an extension, the editor itself sets the language based on automatic language detection, which, in turn, will allow you to get rid of the association files

**Comment by AlexDev2020** [comment]
So far, automatic detection works for unnamed files, but it may be possible to apply this feature for editors, when, for example, we open a <vector>

**Comment by sean-mcmanus** [comment]
What are "unnamed files"? By "apply this feature" would that be work for the VS Code team or our extension? Also, your comment appears to have gotten cut off.

**Comment by AlexDev2020** [comment]
@sean-mcmanus This functionality has been added to vscode https://github.com/microsoft/vscode/issues/118455

I would like that when opening files without extensions (for example <vector>), the language is set automatically and association files are not created.

I don't know where it will be implemented (in this extension or vscode)

**Comment by sean-mcmanus** [comment]
@AlexDev2020 You would need to file an issue with VS Code to have them apply the language guessing to saved files that have no extension. Our extension doesn't control the language guessing.
