### ISSUE TITLE
Support for clang-tidy

### ISSUE THREAD

**Issue by Bascy** [microsoft/vscode-cpptools#7936]
Type: Feature Request

It would be really neat if this extension would also support the use of clang-tidy to include hints on improvements and code-smells.
From my experience in IntelliJ coding in Java, I know I learned a lot from all the suggestions it makes while writing the code (and the quick fix system is awsome in IntelliJ)

**Comment by Colengms** [comment]
Hi @Bascy .  This looks like a duplicate of https://github.com/microsoft/vscode-cpptools/issues/2908 
Closing as a duplicate.
