### ISSUE TITLE
[cpp] Highlight not working when `enable_if_t<X<Y, Z>` is used

### ISSUE THREAD

**Issue by Nuullll** [microsoft/vscode-cpptools#7937]
Bug type: Language Service

**Describe the bug**
- OS and Version: macOS Big Sur 11.4
- VS Code Version: 1.57.0
- C/C++ Extension Version: 1.5.1
- Other extensions you installed (and if the issue persists after disabling them): the issue persists after disabling all the extensions
- If using SSH remote, specify OS of remote machine: N/A
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

See the code and screenshot below. A simple cpp code file is enough to trigger the highlighting bug.
Looks like the `<` symbol used in the `bool` predicate of `enable_if_t` is recognized as a template starting left angle bracket (I guess) unexpectedly, even though it stands for "less than".

**Steps to reproduce**

Create a cpp file containing the code snippet above.

**Expected behavior**

Both `M0` and the second `class` keyword (for `class Bar`) should be highlighted.

**Code sample and logs**

- Code sample
```cpp
#include <iostream>

template<std::uint32_t M0, std::uint32_t M1, std::enable_if_t<M0<M1, bool> = true>
class Foo { // `class` keyword is highlighted, but `M0` above is not.
};

template<std::uint32_t M0, std::uint32_t M1,
         std::enable_if_t<M0<M1, bool> = true>
class Bar { // `class` keyword not highlighted!
};
```

Ah, looks like Github highlights the same code snippet well :)
- Configurations in `c_cpp_properties.json`
Default.

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 8/7/2021, 9:48:34 PM
Version: 1.5.1
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/local/bin/clang",
    "cStandard": "c17",
    "cppStandard": "c++14",
    "intelliSenseMode": "macos-clang-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /Users/nuullll/Projects/playground/cpp/test.cpp ]:
    /Users/nuullll/Projects/playground/cpp/test.cpp
Translation Unit Configurations:
[ /Users/nuullll/Projects/playground/cpp/test.cpp ]:
    Process ID: 9252
    Memory Usage: 122 MB
    Compiler Path: /usr/local/bin/clang
    Includes:
        /usr/local/include/c++/v1
        /usr/local/lib/clang/13.0.0/include
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    Frameworks:
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
    Standard Version: c++14
    IntelliSense Mode: macos-clang-x64
    Other Flags:
        --clang
        --clang_version=130000
Total Memory Usage: 122 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 8276
```

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

I don't think this is helpful. I could attach it if needed.

**Screenshots**

![image](https://user-images.githubusercontent.com/7253534/128602247-d04caa76-2f87-4f8c-b9e7-b4bf67c7aee6.png)

**Additional context**

N/A

**Comment by Colengms** [comment]
Hi @Nuullll .  The C/C++ Extension provides semantic colorization.  Syntactic colorization (such as for the `class` keyword) comes from VS Code itself, based on the TextMate grammar contributed here: https://github.com/jeff-hykin/cpp-textmate-grammar  I'd suggest opening an issue there.

The uncolored `M0` would seem to require semantic parsing to color properly, but the C/C++ Extension (and VS) do not currently support semantic colorization of template parameters.  The TextMate grammar appears to be coloring M0 only where it can syntactically determine it's a variable.  You would see the same behavior with the C/C++ Extension disabled.  (The `Inspect Editor Tokens and Scopes` command can be used to inspect the syntactic and semantic scopes associated with colorization).

Would you like to use this issue as a feature request for semantic colorization of template parameters?

**Comment by Nuullll** [comment]
Per @Colengms:
> I would suggest opening the issue against Visual Studio directly [here](https://developercommunity.visualstudio.com/home), instead. That would give you more direct control over the request. The semantic colorization in the C/C++ extension is based on the semantic colorization algorithm provided by VS. In order to support this, it would first need to be supported in VS. Once VS supports it, the C/C++ extension should get the support automatically.

Thanks, I'll try to reproduce this in VS and submit feature request there. Will get back to u if any updates.
