### ISSUE TITLE
Failed at stage: installPackages Error: Unknown system error -122: Unknown system error -122, close

### ISSUE THREAD

**Issue by LeoLeoHu** [microsoft/vscode-cpptools#7939]
Bug type: General

**Describe the bug**
- OS and Version: Release 16.04.7 LTS (Xenial Xerus) 64-bit Kernel Linux 4.15.0-142-generic x86_64  MATE 1.12.1
- VS Code Version: Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:20.182Z (4 days ago)
- C/C++ Extension Version: v1.5.1
- Other extensions you installed (and if the issue persists after disabling them):
![image](https://user-images.githubusercontent.com/29404176/128974519-153572ec-10a6-4734-8bac-9e4770d9d0b1.png)

- A clear and concise description of what the bug is.
Cannot install the extension always. whether online or offline

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

**Screenshots**
If I choose to install with the downloaded package:
![image](https://user-images.githubusercontent.com/29404176/128693039-a7eb38f5-ef6a-4517-8142-f3a15f8eedf2.png)

**Additional context**

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)' (10584 KB)  Done!
Downloading package 'ClangFormat (Linux / x86_64)' (868 KB)  Done!
Downloading package 'Mono Framework Assemblies' (5368 KB)  Done!
Downloading package 'Mono Runtime (Linux / x86_64)' (1862 KB)  Done!

Installing package 'C/C++ language components (Linux / x86_64)'
Failed at stage: installPackages
Error: Unknown system error -122: Unknown system error -122, close

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.

**Comment by Colengms** [comment]
Hi @LeoLeoHu .  Thanks for reporting this.  Is there any additional info for this error if you open the Developer Tools (Help -> Toggle Developer Tools)?

Is it possible you may have run out of storage space for the user account?  I can't find any documentation on error code -122, but 122 is EDQUOT (Quota exceeded).

**Comment by sean-mcmanus** [comment]
Yeah, another VS Code user hit the same issue at https://github.com/microsoft/vscode/issues/44729

**Comment by LeoLeoHu** [comment]
Thank you @Colengms for helping me check.
It's possible it's storage space issue, since my {HOME} is a IT managed net disk. (space limited)  Is it possible I can move the default .vscode folder to a large place?

By the way, here is the Develop Tool logs:
> **workbench.desktop.main.js:630   ERR [uncaught exception in main]: SQLITE_IOERR_FSYNC: disk I/O error: Error: SQLITE_IOERR_FSYNC: disk I/O error
workbench.desktop.main.js:2038 Activating extension 'ms-vscode.cpptools' failed: ENOENT: no such file or directory, open '/usr2/guodhu/.vscode/extensions/ms-vscode.cpptools-1.5.1/install.lock'.**
$onExtensionActivationError @ workbench.desktop.main.js:2038
_doInvokeHandler @ workbench.desktop.main.js:1551
_invokeHandler @ workbench.desktop.main.js:1551
_receiveRequest @ workbench.desktop.main.js:1551
_receiveOneMessage @ workbench.desktop.main.js:1551
(anonymous) @ workbench.desktop.main.js:1551
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
T @ workbench.desktop.main.js:2899
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
**workbench.desktop.main.js:630   ERR [uncaught exception in main]: SQLITE_IOERR_FSYNC: disk I/O error: Error: SQLITE_IOERR_FSYNC: disk I/O error**

**Comment by Colengms** [comment]
Hi @LeoLeoHu .  The location where extensions are installed is set by VS Code.  You may want to open an issue in the [vscode repo](https://github.com/microsoft/vscode).

I see this question on stackoverflow with some suggested solutions: https://stackoverflow.com/questions/40080793/is-there-a-way-to-change-the-extensions-folder-location-for-visual-studio-code

**Comment by LeoLeoHu** [comment]
Hi @Colengms, how about the error message
> workbench.desktop.main.js:2038 Activating extension 'ms-vscode.cpptools' failed: ENOENT: no such file or directory, open '/usr2/guodhu/.vscode/extensions/ms-vscode.cpptools-1.5.1/install.lock'.
If you confirm this is OK, then I agree to close this help request and let me to explore how to move .vscode to a larger folder.
Thank you very much for the support.

**Comment by Colengms** [comment]
Hi @LeoLeoHu .  That file is written to indicate all additional online dependencies have been downloaded and installed.  If download and/or install failed (due to out of available disk space), it might explain the error.  Though, we could potentially present a more user-friendly error message in this scenario.

**Comment by LeoLeoHu** [comment]
Installing C++ extension succeed with the workaround from StackOverflow: https://stackoverflow.com/a/46266402/9561440

**Comment by LeoLeoHu** [comment]
root-cause: issue caused by space-limited ${HOME} folder, which the default ./extension is placed.
solution: https://stackoverflow.com/a/46266402/9561440
