### ISSUE TITLE
The type initializer for 'System.Xml.Serialization.XmlSerializationReader' threw an exception. when debugging.

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cpptools#794]
From @liencouer - https://github.com/Microsoft/vscode/issues/27875

- VSCode Version: 
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version: Linux x64 4.8.0-53-generic

Steps to Reproduce:

When starting to debug, get the following error message.  

Unable to start debugging. Launch options string provided by the project system is invalid. The type initializer for 'System.Xml.Serialization.XmlSerializationReader' threw an exception.

messageService.ts:125 Unable to start debugging. Launch options string provided by the project system is invalid. The type initializer for 'System.Xml.Serialization.XmlSerializationReader' threw an exception.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ debugService.ts:814
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
then @ winjs.base.raw.js:1436
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
(anonymous) @ v8Protocol.ts:53
e.dispatch @ v8Protocol.ts:136
e.handleData @ v8Protocol.ts:104
(anonymous) @ v8Protocol.ts:41
emitOne @ events.js:96
emit @ events.js:188
readableAddChunk @ _stream_readable.js:176
Readable.push @ _stream_readable.js:134
onread @ net.js:551

**Comment by pieandcakes** [comment]
@liencouer Can you tell me which version and type of gdb you are using?

**Comment by pieandcakes** [comment]
This is the same as #792. Please provide information there.

**Comment by mbbill** [comment]
Mine is gdb on ubuntu 7.11.1
100% reproduce on the latest vscode and extension for Linux.

**Comment by pieandcakes** [comment]
@mbbill Please update #792 and provide your launch.json also.
