### ISSUE TITLE
[IntelliSense] Go to Definition Issue

### ISSUE THREAD

**Issue by taronlee** [microsoft/vscode-cpptools#7943]
Bug type: Language Service

**Describe the bug**
- OS and Version: windows (but testing on linux [Remote-ssh])
- VS Code Version: 1.59.0
- C/C++ Extension Version: v1.5.1
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: linux
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

in the same project,

testA.cpp
```
TestFunction(); // intelliSense and Go to Definition works
```
testB.cpp
```
TestFunction(); // it doesn't work
```

I tested the below ways, but IntelliSense doesn't work in **testB.cpp**.
(`TestFunction` in **testA.cpp** is the same function as **testB.cpp**.)
1. relaunch VS Code
2. C/C++: Rescan Workspace

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by taronlee** [comment]
Now, it works in `testB.cpp` ..
I just relaunched and <kbd>ctrl/cmd + shift + p</kbd> + `Reload Window` again.
nothing has changed.. (at that time, I tested it more than 10 times)

is it C/C++ extension's bug?

**Comment by michelleangela** [comment]
@taronlee 

We'd have to get a consistent repro in order to help determine if this is a C/C++ extension bug or a Remote-SSH issue.

If you're able to get a consistent repro, could you provide the logs from the language server? See instructions at https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server.
