### ISSUE TITLE
includePath is empty 

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cpptools#795]
I remember there was a discussion to fill up this value with standard paths to C++ headers 
at the moment of c_cpp_properties.json creating time.
so the problem is 

1. just opened the project and see that standard headers are red.
2. create properties json via lamp icon and got this 
```
{
    "configurations": [
        {
            "name": "null",
            "includePath": [],
            "defines": [],
            "browse": {
                "path": [],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ]
}
```
I remember the autogenerating the paths to c++ and sdk headers works now for windows.
but seems it doesn't for linux ???

would be preferable to read the settings like this from cmake via server-mode, it's possible? isn't it?

**Comment by bobbrow** [comment]
It gave you "null" for the configuration name?  I haven't seen this before.  Something is definitely wrong.  What distro are you using?  Is it 32-bit?  Does deleting the c_cpp_properties.json file and re-creating it help?  This is supposed to work for Linux.

cmake support is on our backlog.

**Comment by amigo421** [comment]
this is 64-bit version downloaded today from official site and installed via dpkg
OS: latest Mint
![image](https://cloud.githubusercontent.com/assets/3259933/26735717/c7685a60-47cb-11e7-99fc-903308fffb4b.png)

![image](https://cloud.githubusercontent.com/assets/3259933/26735928/b6a810e8-47cc-11e7-9c21-bde71de7391d.png)

![image](https://cloud.githubusercontent.com/assets/3259933/26736066/3f1a178c-47cd-11e7-90a9-6ef903cc71c9.png)

let me re-create json

**Comment by amigo421** [comment]
this is a magic. now standard headers are available , no red highlighting
probably there was a scanning.. but I remember there should be special icon during this process , it was not.

however deleted c_cpp_properties.json, auto created with the same content

let me know how can I help with
logs? additional tests?

**Comment by bobbrow** [comment]
If the c_cpp_properties.json is still wrong, I don't think your problem is solved.  What I think happened is that you also picked up the 0.11.2 or 0.11.3 update to the extension which turns off the squiggles by default.

I also have a box with Mint 18.1 Serena, and I don't see this.  This is what I get (you can copy it into yours in the meantime ... and edit the clang path with the version you have installed)

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}",
                "/usr/include",
                "/usr/local/include"
            ],
            "defines": [],
            "browse": {
                "path": [
                    "/usr/include",
                    "/usr/local/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Linux",
            "includePath": [
                "${workspaceRoot}",
                "/usr/include/x86_64-linux-gnu/c++/5.4.0",
                "/usr/include/c++/5.4.0",
                "/usr/local/include",
                "/usr/lib/clang/3.8.0/include",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include"
            ],
            "defines": [],
            "browse": {
                "path": [
                    "/usr/include/x86_64-linux-gnu/c++/5.4.0",
                    "/usr/include/c++/5.4.0",
                    "/usr/local/include",
                    "/usr/lib/clang/3.8.0/include",
                    "/usr/include/x86_64-linux-gnu",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}",
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ]
}
```

**Comment by amigo421** [comment]
please close the request, found the root of the issue and this is not related with cpptools.
the problem was [here](https://marketplace.visualstudio.com/items?itemName=maddouri.cmake-tools-helper). the extension works incorrect and damages the config of cpptools
after removing all works fine, and properties looks like your version

**Comment by bobbrow** [comment]
Thanks for the update.
