### ISSUE TITLE
Code navigation is broken on a large codebase

### ISSUE THREAD

**Issue by sridhargopinath** [microsoft/vscode-cpptools#7951]
Bug type: Language Service

**Describe the bug**
- OS and Version: MacOS 11.5.1
- VS Code Version: 1.59.0
- C/C++ Extension Version: 1.5.1
- Other extensions you installed (and if the issue persists after disabling them): None
- Code navigation is showing incorrect results on the latest LLVM repository. Some types are noted as undefined and navigating to the definition of some types leads to incorrect file locations. This problem was not present in version 1.1.3. I have tried reloading and restarting the language server. I have attached a screenshot as well.

**Steps to reproduce**

1. Download LLVM 12.0.1 source.
2. Open the source folder in VS Code
3. Open file `llvm/lib/Transforms/Hello/Hello.cpp`
4. See error `variable "Function" is not a type name`

**Expected behavior**
Repeat the above step on version 1.1.3 and there are 0 problems reported by the extension.

**Code sample and logs**
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
[C/C++: Log Diagnostics.log](https://github.com/microsoft/vscode-cpptools/files/6964360/Log.log)

**Screenshots**
![Screen Shot 2021-08-10 at 12 52 00 PM](https://user-images.githubusercontent.com/8598560/128930340-7b861377-0233-49e8-b827-3ae0d9bdf1b3.png)

**Comment by Colengms** [comment]
Hi @sridhargopinath .  Could you provide more information about your configuration?  Large projects often require quite a few include directories and defines to be specified.

The C/C++ Extension can be configured automatically based on data from the build system, using a 'configuration provider' extension, such as CMake Tools.  I believe LLVM is built using CMake.  Can you confirm whether you are using CMake Tools to configure the C/C++ Extension for the LLVM build?

**Comment by sridhargopinath** [comment]
I am using default configurations for both VS Code and the C++ extension. I do not have a `c_cpp_properties.json` file or `settings.json` file.

I am configuring and building LLVM within the workspace folder. All the build time files are within the workspace. The default include path is `workspace/**` which recursively includes all the files both in source and build directory.

I am using CMake from the command line to configure the project. I can try installing the CMake Tools extension. After that, how can I use that to configure the C/C++ Extension?

**Comment by Colengms** [comment]
> I can try installing the CMake Tools extension. After that, how can I use that to configure the C/C++ Extension?

Just adding the CMake Tools extension should be enough.  If CMake Tools sees a `CMakeLists.txt` file, it should register with the C/C++ Extension.  If there is no `c_cpp_properties.json`, and only one custom config provider has registered, it will be used by default.  Or, you can specify the extension ID of a custom config provider in `c_cpp_properties.json` like so: 

```
"configurationProvider": "ms-vscode.cmake-tools"
```

.. Or by setting it as the default in `settings.json`:

```
"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"
```

If you have difficulty configuring LLVM with CMake Tools, definitely let us know.  It's a popular project, so I expect it should be well supported.

**Comment by sridhargopinath** [comment]
I installed the CMake Tools extension and that alone wasn't sufficient. In the LLVM source, the `CMakeLists.txt` file is not on the top of the tree so the extension couldn't find it automatically. I had to invoke `Configure` on CMake Tools and then locate the file manually. These steps fixed the problems I was facing.

It is worth exploring whether the process could be simplified. I am not sure what changed since version 1.1.3 where C/C++ Extension was working without any problems and without the CMake Tools extension. If the functionality could be restored in the current version, that'd be great. If not, documenting the process of integrating with CMake Tools to resolve the problems is also very useful. Let me know if you need more information.

**Comment by sridhargopinath** [comment]
Thanks for providing more context on this. I understand that it is difficult to automate this process. Even I am not sure how IntelliSense was functional without a config provider in the previous version of C/C++ Extension. I remember being able to navigate most of the codebase without any issues.

Closing the issue. Thanks!
