### ISSUE TITLE
Indent seems have the highest privilege in folding

### ISSUE THREAD

**Issue by cloud-yu** [microsoft/vscode-cpptools#7955]
I've got some code like following
```
void func()
{   //<----  1
    if (1)
    {  //<---- 2
        if (1)
        {
            return;
        }
#if 0
        else
        {
            return;
        }
#endif
        if (1)
        {
            return;
        }
    }
}
```
1.  when code folding starts at point 1 or point 2, it ends before condition compile statetment (`#if 0`)
2.  condition compile statement works well start from `#if ` end with `#endif`.  But why this allows folding starts from `#endif`,end before the ending of function?

so, i got some questions:
1. indentation seems  the highest privilege folding strategy,  in other editor like source insight, "bracket pairs" strategy works well.
2.  why `#endif` could be a start place for code folding ?

**Comment by Colengms** [comment]
Hi @cloud-yu .  Are you using the C/C++ Extension?  You seem to be describing the behavior of VS Code without the C/C++ Extension installed.  With the C/C++ Extension installed, a different algorithm is used for code folding, which does not start at the positions you indicated.

I'd suggest trying the C/C++ Extension to see if it's behavior is closer to what you are expected.  Or, consider opening an issue in the vscode repo: https://github.com/microsoft/vscode

**Comment by cloud-yu** [comment]
I'm sure the cpp extension is enabled,  and i disabled clangd extension.  you can see the red square in pic.

![image](https://user-images.githubusercontent.com/8436078/129314545-ef6d07d9-66c2-4be0-8415-7d6b482bcdd0.png)

after folding works looks like this.

![image](https://user-images.githubusercontent.com/8436078/129314934-ad075df0-6fbf-4908-ad74-427a1cbf6c16.png)

**Comment by sean-mcmanus** [comment]
Make sure C_Cpp.intelliSenseEngine is set to "Default" and C_Cpp.codeFolding is also "Enabled". You should see:

![image](https://user-images.githubusercontent.com/19859882/129419251-4ccd0e2a-19ed-4159-aa6a-ce650f5ed1f2.png)

**Comment by cloud-yu** [comment]
Thanks , I checked my setttings, when I enabled clangd and cpp , clangd keep telling me to disabled the C_Cpp.intelliSenseEngine .
Thanks for your information again.

**Comment by cloud-yu** [comment]
got a way to disable some feature but not disable the whole engine ?

**Comment by sean-mcmanus** [comment]
Which features did you want to enable/disable? You could try setting the C_Cpp.intelliSenseEngine to "Tag Parser"? Setting C_Cpp.intelliSenseEngine to "Disabled" will disable all the language features.

Your request may be a duplicate of https://github.com/microsoft/vscode-cpptools/issues/7083, so you could upvote that.
