### ISSUE TITLE
Error squiggles for members in namespace `std` (std::max, std::min, std::size_t, etc.)

### ISSUE THREAD

**Issue by o-lim** [microsoft/vscode-cpptools#796]
* VSCode Version: 1.12.x
* Extension Version: 0.11.3
* OS: Linux

Cannot recognize `std::max`, `std::min`, `std::size_t`, etc. Instead you get an error message of the form `namespace "std" has no member "xxx"`, but the proper include files are specified and the include path is setup correctly.  Removing `std::` prefix seems to make the squiggles go away, at least for `std::max`, `std::min`, `std::size_t`, but this does appear be the case for `std::vector`.  On the other hand auto-complete does appear to be working for `std::max`, `std::min`, `std::size_t`, etc.

**Comment by bobbrow** [comment]
can you share your include path?  The next update to the extension is going to propagate #include errors from nested #includes so that you can see exactly which file(s) we weren't able to find.

**Comment by o-lim** [comment]
Sure, here is the standard include path for gcc:
```
 /usr/include/c++/4.8
 /usr/include/x86_64-linux-gnu/c++/4.8
 /usr/include/c++/4.8/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
```
and here is the include path when I use nix:
```
 /nix/store/jvm15h49snl8njir2lh3xm8f1n46inr0-gcc-4.6.4/include/c++/4.6.4
 /nix/store/jvm15h49snl8njir2lh3xm8f1n46inr0-gcc-4.6.4/include/c++/4.6.4/i686-pc-linux-gnu
 /nix/store/jvm15h49snl8njir2lh3xm8f1n46inr0-gcc-4.6.4/include/c++/4.6.4/backward
 /nix/store/jvm15h49snl8njir2lh3xm8f1n46inr0-gcc-4.6.4/lib/gcc/i686-pc-linux-gnu/4.6.4/include
 /nix/store/jvm15h49snl8njir2lh3xm8f1n46inr0-gcc-4.6.4/include
 /nix/store/jvm15h49snl8njir2lh3xm8f1n46inr0-gcc-4.6.4/lib/gcc/i686-pc-linux-gnu/4.6.4/include-fixed
 /nix/store/ggvbphy7c98lhj6gdl8nw6irxrbd5kqn-glibc-2.20/include
```

**Comment by bobbrow** [comment]
And do you have these paths listed in the c_cpp_properties.json file at the root of your workspace?  (Use the command palette action: "C/Cpp: Edit Configurations" if you do not see this file in your workspace)

**Comment by o-lim** [comment]
Yes, these are the paths listed in .vscode/c_cpp_properties.json.

**Comment by o-lim** [comment]
I can even press `F12` on \<cstddef> and it will go to that file, with contents:
```cpp
// Under Section 7 of GPL version 3, you are granted additional
// permissions described in the GCC Runtime Library Exception, version
// 3.1, as published by the Free Software Foundation.

// You should have received a copy of the GNU General Public License and
// a copy of the GCC Runtime Library Exception along with this program;
// see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
// <http://www.gnu.org/licenses/>.

/** @file cstddef
 *  This is a Standard C++ Library file.  You should @c \#include this file
 *  in your programs, rather than any of the @a *.h implementation files.
 *
 *  This is the C++ version of the Standard C Library header @c stddef.h,
 *  and its contents are (mostly) the same as that header, but are all
 *  contained in the namespace @c std (except for names which are defined
 *  as macros in C).
 */

//
// ISO C++ 14882: 18.1  Types
//

#pragma GCC system_header

#include <bits/c++config.h>
#include <stddef.h>
```
Then pressing `F12` again on \<bits/c++config.h> takes me to:
```cpp
...
namespace std
{
  typedef __SIZE_TYPE__ 	        size_t;
  typedef __PTRDIFF_TYPE__	ptrdiff_t;

#ifdef __GXX_EXPERIMENTAL_CXX0X__
  typedef decltype(nullptr)	nullptr_t;
#endif
}
...
```

**Comment by bobbrow** [comment]
Can you try doing goto definition on std::max or std::min and see if any squiggles show up in the file that opens?  Goto definition is not powered by the new IntelliSense engine yet, so it might work.

For me it's defined in <bits/stl_algobase.h> and I don't see any squiggles on my distro (Mint) with GCC 5.4 toolchain.

**Comment by o-lim** [comment]
When I try goto definition on `std::max` or `std::min`, I don't see any squiggles for min/max in that file \<bits/stl_algobase.h>.  However, there are some squiggles in various places in the file for stuff like template specializations, enable_if, as well as the `_GLIBCXX_BEGIN_NAMESPACE_VERSION` and `_GLIBCXX_VISIBILITY` macros, and \<bits/c++config.h>.

**Comment by bobbrow** [comment]
Where is <bits/c++config.h> in your filesystem?  It would seem that the path to the bits folder containing this file is missing from your includePath in the c_cpp_properties.json file if there is an #include error on that line.

**Comment by o-lim** [comment]
It's located at `/nix/store/jvm15h49snl8njir2lh3xm8f1n46inr0-gcc-4.6.4/include/c++/4.6.4/i686-pc-linux-gnu/bits/c++config.h`, which is in the includePath under `/nix/store/jvm15h49snl8njir2lh3xm8f1n46inr0-gcc-4.6.4/include/c++/4.6.4/i686-pc-linux-gnu`.

**Comment by bobbrow** [comment]
So is there a squiggle in stl_algobase.h for the #include <bits/c++config.h> line or were you saying that there are squiggles in the actual <bits/c++config.h> file?  Both of those macros are defined in c++config.h, so I would assume the former.

Can you paste the full contents of your c_cpp_properties.json file into a comment?  You paths look right, but I want to check and see if there is something else possibly missing.

Which Linux distro are you using?

**Comment by o-lim** [comment]
It is the former. Squiggles in <stl_algobase.h> for `#include <bits/c++config.h>`.

After double checking my `c_cpp_properties.json` file, it appears I was missing a path in that file after all, `/nix/store/jvm15h49snl8njir2lh3xm8f1n46inr0-gcc-4.6.4/include/c++/4.6.4/i686-pc-linux-gnu`.  I must have gotten confused between the 2 separate VSCode instances I had open.  One of them had the complete set of include paths, but the other one did not.

Sorry for the false alarm, and thanks for all your help.

**Comment by bobbrow** [comment]
Glad to hear this is now working for you.

**Comment by ryan-feeley** [comment]
This may help somebody else who ends up on this page. I was getting a similar linter message: "namespace "std" has no member cout". 

My setup:

- Developing on Windows
- Using the clang compiler under msys64/mingw-64.
- Using the "Default" (non tag-parser) intellisense engine
- Using "intellisenseMode = clang-x64 in my c_cpp_properties.json file

My issue seemed to involve some defines that I needed to pass to the intellisense engine. I haven't dug into this, but I expect MinGW or its headers uses some variations that differ from assumptions made by the cpp-tools clang-x64 mode. You can see the default clang++ macros with
`$ clang++ -dM -E -x c++ /dev/null`

I eliminated my linter messages by adding a few settings to the defines in c_cpp_properties.json:
```
"__GNU_C = 4"                               // allows size_t to be found
"__cdecl=__attribute__((__cdecl__))"        // allows strlen, cout, etc to be found
```
@bobbrow , if my understanding of the issue is correct, aspects of this solution may be a useful addition to https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md
