### ISSUE TITLE
Some time after code start up, it fails to display the Declaration，it displays Loading

### ISSUE THREAD

**Issue by MasonSu** [microsoft/vscode-cpptools#797]
OS: Ubuntu 14.04
Code version: 1.12.2

when the code start up, it behaves normally, when the mouse hovers over the symbol, it can show the declaration，but after some time later，it suddenly stopped working，show the Loading...

![Alt text](http://i.imgur.com/fzF4bpz.png)

**Comment by bobbrow** [comment]
If this is happening persistently in your project, you can add `"C_Cpp.intelliSenseEngine": "Tag Parser"` to your settings.json file to switch back to the old IntelliSense engine.  If you are able to attach a debugger and get a callstack for us during the hang, that might help us diagnose the problem.

**Comment by bobbrow** [comment]
We added some crash recovery code to the extension in version 0.12.0.  If you are still seeing this in version 0.12.0, could you let us know whether any Microsoft.VSCode.CPP.IntelliSense.Msvc.linux processes are still running when you get into this state?  And also if Reloading the window or restarting VS Code fixes the issue?

**Comment by sean-mcmanus** [comment]
We recently fixed a bug that could randomly lead to a deadlock and endless "Loading..." ( https://github.com/Microsoft/vscode-cpptools/issues/1759 ). Please re-activate this issue if it still repros with 0.16.1 or later. If the "Loading..." appears upon opening a file and there's a red flame in the bottom right, that is likely a different issue (blocked by IntelliSense parsing).

**Comment by NoSuchProcess** [comment]
This issue is still reproduced with Version 0.16.1

stalled processes:
```
$ ps ax | fgrep Microsoft
 1816 ?        Sl     0:06 /home/*/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.Extension.linux
 1839 ?        Sl     0:00 /home/*/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 1816 0
 2043 ?        Sl     0:00 /home/*/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 1816 3
```

main process
```
$ sudo strace -s 100 -p 1816
Process 1816 attached
read(0, "Content-Length: 53\r\n\r\n", 4096) = 22
read(0, "{\"jsonrpc\":\"2.0\",\"method\":\"cpptools/onIntervalTimer\"}", 4096) = 53
futex(0x7ffc4667c66c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7ffc4667c668, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
read(0, "Content-Length: 53\r\n\r\n", 4096) = 22
read(0, "{\"jsonrpc\":\"2.0\",\"method\":\"cpptools/onIntervalTimer\"}", 4096) = 53
futex(0x7ffc4667c66c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7ffc4667c668, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
read(0, ^CProcess 1816 detached
```

subprocesses:
```
$ sudo strace -s 100 -p 1839
Process 1839 attached
futex(0x13b6b5c, FUTEX_WAIT_PRIVATE, 1, NULL^CProcess 1839 detached
 <detached ...>
```
```
stepanov@stepanov:~/1$ sudo strace -s 100 -p 2043
Process 2043 attached
futex(0x234db5c, FUTEX_WAIT_PRIVATE, 1, NULL^CProcess 2043 detached
 <detached ...>
```

backtrace is the same for both subprocesses:
```
$ sudo gdb -p 1839 /home/stepanov/.vscode/extensions/ms-vscode.cpptools-0.16.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
... (skipped)
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000008b91fd in neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long, int&) ()
#2  0x00000000008b747a in microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) ()
#3  0x00000000008b1034 in comm_server::wait_for_requests() ()
#4  0x00000000005354fb in main ()
```

**Comment by sean-mcmanus** [comment]
@NoSuchProcess Can you provide more repro info? "Loading..." is a general symptom of a deadlock (if it's permanent), so we need more info to fix these. What is the main process Microsoft.VSCode.CPP>Extension.linux blocked on, ignoring the threads that aren't doing any work? I assume it'll be blocked on at least one IntelliSense operation. Does killing the IntelliSense process causing the main process to continue?
