### ISSUE TITLE
File type recognization 

### ISSUE THREAD

**Issue by nimitmore27** [microsoft/vscode-cpptools#7970]
Issue Type: <b>Bug</b>

in my vs code , even if i save my file with extension with .c then also my file is recogized as C++ file and i have to use CPP user snippet for .C file 
please let me know solution for this problem 

Extension version: 1.5.1
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by Colengms** [comment]
Hi @nimitmore27 .  Are you using a ".C" file (with a capital C) ?  If so, that would actually indicate a C++ file.  https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html

Or, if your files use a lower-case ".c", could you provide more information about your repro?  Does it happen with a fresh workspace?  With a simple repro, I see that files ending in ".c" are associated with "C", which I can see at the bottom of the window:

![image](https://user-images.githubusercontent.com/49173979/129403123-9367d5eb-7d14-4fed-a495-13a8ddef3ff9.png)

That indicate can be clicked on to change the language association of the file.

One possibility might be that a `settings.json` file is associating your files with the wrong language ID.  For example, this would cause C files to be associated with C++:

```
    "files.associations": {
        "*.c": "cpp",
        "test.c": "cpp"
    }
```
