### ISSUE TITLE
Cannot open the debugging terminal after updating C/C++ extension  to version 1.6.0

### ISSUE THREAD

**Issue by Joe-Jack** [microsoft/vscode-cpptools#7975]
Issue Type: <b>Bug</b>

After updating the C/C++ extension to the latest version 1.6.0, vscode cannot be used for debugging normally, the terminal window cannot be opened, and the message "Terminal is reused by tasks, press any key to close" is displayed. After rolling back to the old version, the terminal can be opened normally

Extension version: 1.6.0-insiders
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (4.07GB free)|
|Process Argv|--crash-reporter-id 98100806-7db8-4578-8f29-30e1163f6ccb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30351387
vstre464cf:30350173
bridge0723cf:30351748
javagetstartedt:30351793

```

</details>

**Comment by median-dxz** [comment]
I have the same problem with the same version of the extension.
VS Code version: 1.60.0-insider(58454f7bec838f79fe2422ab5914419147d82e40)

**Comment by jok1991** [comment]
I'm also having the same issue. Any solution please let us know! thanks

**Comment by gokunik** [comment]
Refer the #7971 issue for this problem. The solution is mentioned their. Either roll back or delete some of the files which are mentioned in it.

**Comment by WardenGnaw** [comment]
Duplicate: https://github.com/microsoft/vscode-cpptools/issues/7971
