### ISSUE TITLE
Run Hello World 

### ISSUE THREAD

**Issue by AdarshPawar29** [microsoft/vscode-cpptools#7976]
`.\helloworld` is not working for me but `./helloworld` works fine. I'm using macOS.

**Comment by WardenGnaw** [comment]
macOS (similar to Linux) uses `/` as a path separator. `\` is reserved for the escape character in the shell. 
Reference: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02_01

This is by design by the OS.
