### ISSUE TITLE
Variable Length Arrays Misidentified as Errors by Intellisense

### ISSUE THREAD

**Issue by m0hit-rai** [microsoft/vscode-cpptools#7979]
The bug is almost the same as #6500

**Describe the bug**

- OS and Version: Windows 10
- VS Code Version: 1.59
- C/C++ Extension Version: 1.5.1
- I recently installed Visual Studio 2019 and Unity.

**Steps to reproduce :**

1. Create a .cpp file
2. Declare an array using a variable as shown in the screenshot below

**Screenshots**
![VS Code error](https://user-images.githubusercontent.com/84135699/129472411-8f930388-ac30-40fe-9a00-2cd4fe099b89.JPG)

**Additional context**

I have tried uninstalling and then reinstalling the Intellisense extension. I have tried downgrading the Intellisense extension to 1.2.2 as the issue has been officially resolved in that version. I have even tried uninstalling VS code and then reinstalling it. I have also tried deleting the MinGW folder and then reinstalling it.

The issue is with Intellisense extension as the code is compiling and running correctly.

**Comment by franneck94** [comment]
VLA are not part of the C++ Standard

**Comment by m0hit-rai** [comment]
**The issue was resolved as soon as I uninstalled Visual Studio 2019. So I am closing this Issue now.**

@franneck94 Yes, VLA are not a part of C++ standard but the program compiles and runs perfectly. My VSC intellisnse extension is working as before and not marking this as an error. 

I think they had removed this error specifically in its 1.2.2 version. You can check here [v1.2.2](https://github.com/microsoft/vscode-cpptools/releases/tag/1.2.2#:~:text=Fix%20IntelliSense%20errors%20with%20variable%20length%20arrays%20with%20C%20Clang%20mode.%20%236500)
