### ISSUE TITLE
Add Gitter chat room for C++ extension

### ISSUE THREAD

**Issue by rei-vilo** [microsoft/vscode-cpptools#798]
Polease add a Gitter chat room for C++ extension. 

Thank you!

**Comment by bobbrow** [comment]
Thank you for the suggestion.

Unfortunately, since Gitter is not specific to C++, it is not something that belongs to this extension.  Perhaps you can contact the VSCode or Gitter teams and ask them if they will create an extension.

**Comment by rei-vilo** [comment]
Sorry for not being clear enough on my initial post. 

Both Visyal Studio Code and the Arduino extensions have a dedicated Gitter chat-room. 

Wouldn't be nice adding another Gitter chat-room for the C++ extension.
