### ISSUE TITLE
Help me shift from Turbo C++

### ISSUE THREAD

**Issue by AtigDev** [microsoft/vscode-cpptools#799]
I am a student and was using Turbo C++ till now but now I have downloaded VS Code, but cant output or run my programs.

**Comment by pieandcakes** [comment]
@AtigDev I don't know what Turbo C++ is. Can you tell us more about what you have tried and what OS you are using?

**Comment by AtigDev** [comment]
Using Windows 8 OS
Turbo C++ is an old compiler which was recommended to me in my school.
It's similer to Borland C++

**Comment by sean-mcmanus** [comment]
Here's a blog on how to build stuff in VS Code: https://blogs.msdn.microsoft.com/vcblog/2016/10/24/building-your-c-application-with-visual-studio-code/ . You can also build via the command line and use VS Code for editing and debugging. You might also want to consider Visual Studio 2017 Community Edition if you're on Windows.

**Comment by AtigDev** [comment]
Thanks a lot
