### ISSUE TITLE
Wrong name is shown for function typedef in OUTLINE

### ISSUE THREAD

**Issue by lzeng14** [microsoft/vscode-cpptools#7990]
Issue Type: <b>Bug</b>

All the details are in https://github.com/microsoft/vscode/issues/130092 which is asked to be directed to the extension.

Extension version: 1.5.1
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

**Comment by michelleangela** [comment]
@lzeng14, could you provide a sample code that shows the wrong name is shown for a function typedef in outline view?

**Comment by Colengms** [comment]
Hi @lzeng14 .  Thanks for reporting this.  I can repro with the following reduced example:

```
#define SOMETYPE int
#define APITYPE

typedef SOMETYPE (APITYPE *test)(int x);
```

![image](https://user-images.githubusercontent.com/49173979/129804244-00939d2c-5650-4d2a-8374-a64cc3453317.png)

In this case, it looks like the combination of `APITYPE` and `SOMETYPE` macros are causing the function pointer type to be parsed incorrectly, and the return type macro is misidentified as the name of the declared type.

**Comment by lzeng14** [comment]
Mentioned in microsoft/vscode#130092, there are some real examples in https://github.com/tianocore/edk2/blob/master/MdeModulePkg/Include/Guid/MemoryProfile.h.

**Comment by sean-mcmanus** [comment]
This is "by design". You need to add `#define SOMETYPE int` to a cpp.hint file in your workspace folder.
