### ISSUE TITLE
Cannot detect .hpp Header files.

### ISSUE THREAD

**Issue by SakthiMahendran** [microsoft/vscode-cpptools#7993]
Bug type: Language Service

**Describe the bug**
- OS and Version:  Windows and 10
- VS Code Version:  1.59
- C/C++ Extension Version: 1.5.1
- Other extensions you installed (and if the issue persists after disabling them): None
- If using SSH remote, specify OS of remote machine: None
- A clear and concise description of what the bug is, including information about the workspace 
-  I am trying to use OpenCv libraries with C++ using VsCode. But the Problem is that the intellisense only detecting the C HeaderFiles(.h) and not the C++ HeaderFiles(.hpp).

**Steps to reproduce**

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by michelleangela** [comment]
@Sakthimahandran 
Could you check your "files.associations" settings? .hpp header files should already be supported, perhaps there is something configured that is causing the IntelliSense to not find .hpp files.

It could also be the OpenCv library path is not included in the IntelliSense configuration settings or the `c_cpp_properties.json` file, which could cause IntelliSense to not find the libraries. If the OpenCv library path is not  `c_cpp_properties.json` under the "includePath" property, could you try adding and see if it fixes the issue?
