### ISSUE TITLE
Unable to debug using Cygwin gdb

### ISSUE THREAD

**Issue by rafid149** [microsoft/vscode-cpptools#7994]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 7 32 bit
- VS Code Version: 1.60.0
- C/C++ Extension Version: 1.5.1
- Other extensions you installed (and if the issue persists after disabling them): Nothing
- A clear and concise description of what the bug is.

When I try to debug with cygwin gdb the output is always shown in debug console. I can't give any input/output there. And that's why when i tried to make external console true , it immediately closes the window after running it... 

https://user-images.githubusercontent.com/85733811/129704568-b1a3832d-59d4-46c2-90dc-e7558dec0b95.mp4

**Comment by phudang882** [comment]
You can return to 1.5.1
https://github.com/microsoft/vscode-cpptools/issues/7971

**Comment by WardenGnaw** [comment]
With `"externalConsole": false`, you should be able to input from the `Terminal` pane.

With `"externalConsole": true`, a window appears and immediately disappears because your program ends.

**Comment by marcoschou** [comment]
Hi,

I have exactly the same issue and don't understand why it was closed. Regardless of whether I choose externalConsole true or false, the debugger starts hits the first breakpoint and stops immediately. It is not possible to use the debugger at all.

**Comment by aivascu** [comment]
In case someone stumbles on this thread.
There is a bug in Cygwin's gdb (v11.x - v12.x) that prevents VS Code from stopping at breakpoints.
At the moment rolling back gdb to v9.x seems to solve the issue.

**Comment by P-Arun02** [comment]
> In case someone stumbles on this thread. There is a bug in Cygwin's gdb (v11.x - v12.x) that prevents VS Code from stopping at breakpoints. At the moment rolling back gdb to v9.x seems to solve the issue.

thanks, now it works.
Also downgraded gcc-core and g++ from v11.x to run perfectly
