### ISSUE TITLE
Add .editorconfig support for vertical spacing rules (blank lines) to vcFormat

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/vscode-cpptools#7997]
Type: Feature Request

clang-format, by default collapses multiple blank lines into one and removes blank lines at the start of code blocks (they have `KeepEmptyLinesAtTheStartOfBlocks` that disables this). This is the preferred behavior in or coding standards formatting rules. For example we have rules like "only one blank line" and "no blank line between setting a value and testing it". 

Ideally this would be the default in the vcFormat engine, but if that can't be done I'd like it to be an option we can select. 

I'd like this to work in VS Code and VS.

**Comment by ChrisGuzak** [comment]
@Colengms I have not. can you do that? what is best, via user feedback or entering the ADO item in the DevDiv instance?

**Comment by sean-mcmanus** [comment]
@ChrisGuzak https://developercommunity.visualstudio.com/report?space=62&entry=suggestion

**Comment by ChrisGuzak** [comment]
I created [this request](https://developercommunity2.visualstudio.com/t/Add-editorconfig-support-for-vertical-s/1603971?space=62&entry=suggestion)
