### ISSUE TITLE
Intellisense *.hh Files

### ISSUE THREAD

**Issue by blakebarber** [microsoft/vscode-cpptools#80]
Using the latest release of Visual Studio Code with the latest release of the C/C++ Extension.  I'm adding my directory to the c_cpp_properties.json:

```
       {
            "name": "Linux",
            "includePath": ["/usr/include","${workspaceRoot}/source"]
        },
```

This seems to work fine for finding my include file so long as the include file is `*.h`, but if the include file is `*.hh` it doesn't get parsed.  There may be a setting to set file extensions the Intellisense feature parses, but I haven't quickly been able to locate it.

**Comment by sridmad** [comment]
I have fixed this and the fix should appear in a version of the extension > 0.7.0

**Comment by blakebarber** [comment]
This same issue appears to persist in version 0.7.1.  I just tried it out
and same symptoms.  If the file is `*.h` it's found just fine, if it's
`*.hh` then the include file cannot be found.  Thanks for looking into this!

Blake

**Comment by sridmad** [comment]
0.7.1 had a very small bug fix for a regression. 0.8.0 should have the changes to handle .hh files.
