### ISSUE TITLE
Cannot get C/C++ navigation to work / language server crashes? 

### ISSUE THREAD

**Issue by ronys** [microsoft/vscode-cpptools#800]
VSCode Version: Code 1.12.2 (19222cd, 2017-05-10T13:16:25.899Z)
OS Version: Linux x64 3.10.0-514.10.2.el7.x86_64
Extensions:
Extension	Author	Version
code-gnu-global	austin	0.2.2
python	donjayamanne	0.6.4
cpptools	ms-vscode	0.11.4
Steps to Reproduce:

Opening a C file, selecting a function, all navigation options are grayed out
Error "The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted." appears consistently in popup - perhaps this is related?

**Comment by bobbrow** [comment]
Are you able to share any additional information about your project?  Is it open source so we can experiment with it, or are you able to produce this error consistently with a test file of some sort?

**Comment by dcourtois** [comment]
On CentOS, we have an old glibc version. See #19 and check if this is the cause of your problem.

**Comment by sean-mcmanus** [comment]
We believe this should work now. Please re-open with more info if there's a problem still.
