### ISSUE TITLE
Don't downgrade if insiders was manually installed

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#8005]
Currently, if the user does not have `updateChannel` set to `Insiders`, and an insiders build is manually installed, it will be immediately uninstalled when activated.

Opening this issue to track setting aside some persistent data whenever an insiders build is installed due to the `updateChannel`.  Only if that is data is set would a downgrade occur.  That should allow manually installed insider builds to remain installed.

**Comment by bobbrow** [comment]
Superceded by #8507
