### ISSUE TITLE
Cannot update - TLS issues

### ISSUE THREAD

**Issue by ronys** [microsoft/vscode-cpptools#801]
VSCode Version: Code 1.12.2 (19222cd, 2017-05-10T13:16:25.899Z)
OS Version: Linux x64 3.10.0-514.10.2.el7.x86_64
Extensions:
Extension	Author	Version
code-gnu-global	austin	0.2.2
python	donjayamanne	0.6.4
cpptools	ms-vscode	0.11.4
Steps to Reproduce:

1.Updating C++ support, I get the following
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux)' Failed at stage: downloadPackages
Error: unable to get local issuer certificate
at TLSSocket. (_tls_wrap.js:1085:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:185:7)
at TLSSocket._finishInit (_tls_wrap.js:603:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)

Finished

My guess is that this is because I'm behind a corporate firewall that does MITM on "select" https connections.

**Comment by pieandcakes** [comment]
@ronys can you try and enable the proxy settings in VSCode and close and reopen it and see if it will download?

**Comment by ronys** [comment]
Yes, setting http.proxyStrictSSL" to false fixed this issue. Ticket can be closed.

Thanks!
