### ISSUE TITLE
Extension not work

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8020]
Issue Type: <b>Bug</b>

hello sir 

My pc Vs code C/C++ Extension not work plz help me 
i hope you team help me
Thank you

Extension version: 1.6.0-insiders3
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5200  @ 2.50GHz (2 x 2493)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.87GB (1.68GB free)|
|Process Argv|--crash-reporter-id 3ca21ad0-05d3-4a29-8ae9-a13869ab5bd3|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michelleangela** [comment]
@NikunjMumna 
Could you provide information about what is not working with the C++ extension? For example, is the issue about IntelliSense or debugging? What are the steps to reproduce the issue? Does the issue reproduce on the **1.6.0-insiders3** version or **1.5.1** version?

Could you also try running `C/C++: Log Diagnostics` from the VS Code command palette and share the logs?
