### ISSUE TITLE
"type": "cppdbg" => No extension found

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vscode-cpptools#8023]
Bug type: General

**Describe the bug**
- OS and Version: macOS 11.5.1 with arm64/M1
- VS Code Version: 1.56.2
- C/C++ Extension Version: 1.5.1
- Other extensions you installed (maybe interesting, but should be unimportant): Cmake tools, CodeLLDB 

**To Reproduce**
Like in your documentation I create a configuration with `"type": "cppdbg"`, but when I start debugging it says I have to install an extension and searches for `@category:debuggers cppdbg`, but there a no results ("No extensions found")
```json
        {
            "name": "clang++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "./build.amd64.debug/vcpkg",
            "cwd": "${workspaceFolder}",
        }
```

**Expected behavior**
There should be an extension (idk)?

**Comment by WardenGnaw** [comment]
`cppdbg` is the debugger type. The extensions pane searches by the extension name, e.g. `C++`
![image](https://user-images.githubusercontent.com/3953714/130498306-20389515-4daa-49e9-a654-61acea073091.png)

However, if you believe you should be able to find the C++ debugger by searching `cppdbg`, the extensions pane is owned by VS Code. Please file an issue in their repo: https://github.com/microsoft/vscode/issues
