### ISSUE TITLE
Suddenly it wasn't available to debugging

### ISSUE THREAD

**Issue by throne-developer** [microsoft/vscode-cpptools#8027]
Bug type: Debugger

**Describe the bug**
- OS and Version: macos 10.15.7 
- VS Code Version: 1.59.1
- C/C++ Extension Version: v1.6.0-insiders3
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Hello, I in the remote development mode of vscode, connect Linux host, debugging C++ program on Linux with GDB and vscode, just started out everything is normal, I can single step debugging on vscode, view the value of variables.

However debugging for some time, almost ten minutes or so, suddenly can't continue debugging, several buttons of the debugging toolbar can't be clicked, and the variable window does not show variables.I can only stop debugging and restart debugging.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/a/server",
            "args": [],
            "stopAtEntry": false,
            "cwd": "/home/a",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

**Comment by WardenGnaw** [comment]
Can you add the following to your `launch.json` configuration and share the output from the Debug Console?
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

**Comment by throne-developer** [comment]
I sent the output log into your email, thank you.

**Comment by WardenGnaw** [comment]
From the logs, it looks like the debugger is waiting for the next event to happen.

```
<--   C (next-232): {"command":"next","arguments":{"threadId":20586},"type":"request","seq":232}
--> R (next-232): {"type":"response","request_seq":232,"success":true,"command":"next","body":{},"seq":19652}
```

There are the final two events indicating you have continued the program and nothing else is happening.
