### ISSUE TITLE
Error: end of central directory record signature not found

### ISSUE THREAD

**Issue by holdjun** [microsoft/vscode-cpptools#803]
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (4663 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (905 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (12081 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: end of central directory record signature not found

Finished

**Comment by betterjun** [comment]
the same issue with 1.17 on windows 10, log below

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (4969 KB) . Done!
Downloading package 'ClangFormat (Windows)'  Failed. Retrying... Failed. Retrying...(905 KB) ..... Done!
Downloading package 'Visual Studio Windows Debugger' (11875 KB) ... Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: end of central directory record signature not found

Finished

**Comment by sean-mcmanus** [comment]
@betterjun Less than 1% of users hit this. It seems like your zip file did not download correctly and was corrupt. Does trying the download again eventually fix this?

In case anyone else hits this "corrupt zip" error, it means that the zip file was somehow not downloaded completely. I hit this "by accident" when I tried to install a vsix at https://github.com/Microsoft/vscode-cpptools/releases before it was fully downloaded.
