### ISSUE TITLE
PHP public static functions not recognized by Go To Definition

### ISSUE THREAD

**Issue by lcsqlpete** [microsoft/vscode-cpptools#8034]
Bug type: Language Service

- OS and Version: MacOS 10.14.6
- VS Code Version: 1.59.1

Right clicking on a reference to a public static function in a class that is instantiated within another class results in either "No definition found' message or the outer class script being opened depending on where in the reference the right click occurs.

For example using the following line.

$credentials = $model->keu::getAuthHeader();

The class referenced by $model instantiates an instance of the class referenced in keu.

If the right click is on $model or keu, the class file referenced in $model is opened.  If the right click is on getAuthHeader() the "No definition found" message is displayed.

**Comment by Colengms** [comment]
Hi @lcsqlpete .  This is the repo for the C/C++ extension for VS Code.  It looks like PHP support is internal to VS Code, so you'll want to open your issue in the [VS Code repo](https://github.com/microsoft/vscode/issues).

Closing this issue as external.
