### ISSUE TITLE
Error detector can't recognize cout/cin operands

### ISSUE THREAD

**Issue by sdi1900232** [microsoft/vscode-cpptools#8043]
Hello. Recently I made the change from Dev-C++ to VS code. I fined tuned everything, to the point where my scripts all run, but there is one problem left. For some reason, even though the code runs fine, when editing, error squiggles appear beneath all the file operands(for example: cout <<, cin >>) and the only way to fix this is disabling error squiggles. I was wondering what could be causing this.  The error shown in this example as pictured below is 'no operator "<<" matches these operands -- operand types are: ostream << long long'.

Here is the example:
![image](https://user-images.githubusercontent.com/79796115/130645961-f303eb3f-31c2-4de5-b9f8-51c4a8688837.png)

Here are my settings:
![image](https://user-images.githubusercontent.com/79796115/130647012-f37858dd-0ce8-424f-b7bb-ec9c9e5dcbae.png)

**Comment by sean-mcmanus** [comment]
1. Run the C/C++: Log Diagnostics command to see what settings are actually being used by IntelliSense.
2. You have the configurationProvider set, so the configuration info may be coming from that extension, which may either be configured incorrectly by you or it may have a bug, depending on what configuration we're being provided.
3. Without the configurationProvider set, you shouldn't be setting your includePath to have system includes, which could cause errors if the ordering is wrong. You should instead just set the compilerPath to your mingw g++ compiler.
