### ISSUE TITLE
Extension does not detect imports in 1.6.0

### ISSUE THREAD

**Issue by okuma10** [microsoft/vscode-cpptools#8049]
Bug type: General

`#include` does not include `.h` files in a C project. Extension version: 1.6.0.
Working extension where the bug is not present is 1.4.1.
I reverted to 1.4.1 (default - to stop it updating automatically) and it works just fine.

**Comment by sean-mcmanus** [comment]
This issue doesn't repro in general (i.e. our team isn't able to repro it, nor have we received other bug reports like this yet), so we'll need more info. Are you able to provide more repro info, such as some simple test case or output from running C/C++: Log Diagnostics? Does the bug happen in 1.5.1?

**Comment by okuma10** [comment]
Not sure how reproducible it is. I'm following a vulkan tutorial
 But here is what I get This is on 1.6.0:
![image](https://user-images.githubusercontent.com/44575116/130784541-16acc176-a22e-4457-b6db-1615b203c863.png)

Same thing but on 1.51(I've tried it and that works as well). File was not modified. The only thing I did was to click `unistnall>install another version>1.5.1` from the extension settings:
![image](https://user-images.githubusercontent.com/44575116/130785325-8f713385-9edc-4df4-8c35-17768c564b93.png)
![image](https://user-images.githubusercontent.com/44575116/130785403-84da0f02-1ef0-40b6-8c04-d91e9aec45a5.png)
Now all header includes work as they should.
So to me there is something that changed in 1.6.0, because I did not change anything, yet in 1.5.1 it works but not in 1.6.0. More over the first time I saw this I was on vacation for a week. So 7days no one had even powered the PC. And when I got back and booted it up(no windows updates performed) it automatically updated the extension to 1.6.0 and now the imports don't work.

**Comment by okuma10** [comment]
Not sure how reproducible it is. I'm following a vulkan tutorial
 But here is what I get This is on 1.6.0:
![image](https://user-images.githubusercontent.com/44575116/130784541-16acc176-a22e-4457-b6db-1615b203c863.png)

Same thing but on 1.51(I've tried it and that works as well). File was not modified. The only thing I did was to click `unistnall>install another version>1.5.1` from the extension settings:
![image](https://user-images.githubusercontent.com/44575116/130785325-8f713385-9edc-4df4-8c35-17768c564b93.png)
![image](https://user-images.githubusercontent.com/44575116/130785403-84da0f02-1ef0-40b6-8c04-d91e9aec45a5.png)
Now all header includes work as they should.
So to me there is something that changed in 1.6.0, because I did not change anything, yet in 1.5.1 it works but not in 1.6.0. More over the first time I saw this I was on vacation for a week. So 7days no one had even powered the PC. And when I got back and booted it up(no windows updates performed) it automatically updated the extension to 1.6.0 and now the imports don't work.

**Comment by georgev93** [comment]
Not to confuse things too much, but I can confirm that my Intellisense is not working properly in v1.6.0 in the same manner that has been described in this thread. I've rolled back to v1.5.1 and everything is working perfectly.

To expend a bit more, I have noticed when I use a struct defined in another file in my project (a .h file located within the project directory), it is showing up as undefined (red squiggles). Then as I hover over it, the error remains. I can ctrl+click it to show its definition elsewhere in the project, which VS code correctly identifies. When I open up the file that the struct has been defined in, then I navigate back to the original file with the error, the error remains. BUT if I then hover over the symbol (not ctrl+click, just hover) the error goes away after a few seconds. Then I can close the file that the struct has been defined in, and the error returns!

All of this occurs after intellisense parsing has completed. I've also been able to recreate this with symbols from system headers, such as uint8_t.

**Comment by okuma10** [comment]
This is my Log Diagnostics without the line
```
-------- Diagnostics - 8/28/2021, 3:16:59 PM
Version: 1.6.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/engine/src/**",
        "C:\\VulkanSDK\\1.2.176.1/include"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE",
        "KEXPORT"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "compilerPathIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "macFrameworkPath": [],
    "compilerArgs": [],
    "compilerPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\Hostx64\\x64\\cl.exe",
    "browse": {
        "path": [
            "${workspaceFolder}/engine/src/**",
            "C:\\VulkanSDK\\1.2.176.1/include",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.
```

**Comment by okuma10** [comment]
To add to the thread, I've also talked with the creator of the series, (about some issues I was stuck with). He also reported the same issue and that he also reverted back to 1.5.1

**Comment by sean-mcmanus** [comment]
@okuma10 Your log diagnostics output shows "No active translation units", i.e. it needs to be run after opening a file and having the IntelliSense finished parsing it. The most important information we're looking for is the IntelliSense mapping.

We're not sure if this is a bug yet or not. If your code isn't compilable with clang-cl and your compilerPath is set to that, then the results could be unpredictable. Is anyone reproing a bug with the compilerPath set to cl?

**Comment by okuma10** [comment]
oh sorry I'm not aware that I should had closed the issue. Yes in latest version the issue appears to be resolved
Thanks for all the hard work.
