### ISSUE TITLE
false error squiggles "invalid multibyte character sequence" when including files contains chinese chracter

### ISSUE THREAD

**Issue by Grizzbear** [microsoft/vscode-cpptools#806]
Hi, I got a problem when the including files containing chinese character. 

For example, I define something something like `#define A "中文"`in a.h, and there is no error squiggle   in a.h. But if I include a.h in a.c, there would be red squiggles under `A` in a.c,  saying "invalid multibyte character sequence". 

This problem only happens when reopen existing files. If I edit the a.h which contain the multibyte character, the red squiggle in a.c would disapear.

This could lead to so many false errors in a file that I can hardly use error squiggles in my project. Could you please fix this problem, or at least change this error to a warning? 

update: I found there is no need to edit the a.h, just open a.h could make the red squiggles disappear. But it is still anoying to open every including files containing chinese character to clear the red squiggles.

**Comment by sean-mcmanus** [comment]
I'm not able to repro the problem. My test.h has the #define A, and my test.c has the #include "test.h" and uses `A;` in a main function and I get no errorSquiggles. I just open the test.c. I tested it on Windows. What OS are you using? Am I doing the repro incorrectly? We have some known bugs with UTF-8 characters > 1 with the Default IntelliSenseEngine, e.g. the tooltip on A in test.h has a garbled character. I assume your encoding is UTF-8.

**Comment by Grizzbear** [comment]
I'm runing vscode on windows 7, and my encoding is GBK. I think you should define A to a chinese character to repro the problem, e.g, `#define A "中文"`, and reopen working folder. The tooltip garbled chracter problem also shows up in this case.

**Comment by sean-mcmanus** [comment]
Yeah, most of our code assumes UTF-8 and we don't have a layer to convert GBK to UTF-8 yet. We plan to fix this, but we don't have an ETA. Our extension is still in "Preview" so we're not fully localized or world ready yet. See https://github.com/Microsoft/vscode-cpptools/issues/414 .

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.30.0-insiders4 . Let us know if you see any remaining bugs with non-UTF-8 encodings.
