### ISSUE TITLE
LogPoint stopped working v1.6.0

### ISSUE THREAD

**Issue by jakarman** [microsoft/vscode-cpptools#8065]
Bug type: Debugger

- OS and Version: Windows 10 Home
- VS Code Version: 1.59.1
- C/C++ Extension Version: 1.6.0

- I just installed version 1.6.0, and the LogPoint functionality stopped working as it should. Instead of printing to the debug console, the message now stops as if it were a common breakpoint.

**To Reproduce**
1. Create a simple file of C++
```c
#include <iostream>
#include<windows.h>
using namespace std;

int main()
{
  while (1)
  {
    Sleep(1000);
    cout << "Hello World" << endl;
  }
    
}
```
2. Compile the program
3. Add a Logpoint at  `cout << "Hello World" << endl`;
4. Run the debugger.

**Context**

I'm using the default config for lauch.json to test the error. Using 1.5.1 works fine.

**Comment by WardenGnaw** [comment]
This is a bug in v1.6.0. There will be a fix in the next release. 

The current workaround is to use v1.5.1 if you need LogPoints.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
