### ISSUE TITLE
Debugger won't read/write from/to stdio

### ISSUE THREAD

**Issue by qiulang** [microsoft/vscode-cpptools#8075]
Bug type: Debugger

**Describe the bug**
```
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0
C/C++ Extension Version:v.1.6.0
```
A simple code demonstrate it. 

```
#include <stdio.h>

int main()
{
    char str[80];
    printf("Enter your family name: ");
    scanf("%79s", str);
}
```

launch.json 

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "clang++ - Build and debug active file",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${fileDirname}",
      "environment": [],
      "externalConsole": true,
      "MIMode": "lldb",
      "preLaunchTask": "clang++ build active file"
    }
  ]
}

```

I got the external terminal open, but it did not read my input, nor does it output anything. If I kill the terminal, the debugger stops as well.

In https://github.com/Microsoft/vscode-cpptools/issues/449   @pieandcakes said "Please file a new issue and fill out the template. " So I am filing this issue.

I also asked at https://github.com/microsoft/vscode-cpptools/discussions/8074 but it does look like a bug to me.

**Comment by WardenGnaw** [comment]
With the .NET 5 change, the platform detection is incorrectly detecting macOS. 

To workaround this issue for now. Please us v1.5.1

**Comment by qiulang** [comment]
One more question, is it possbile to use integrated terminal not external terminal when you guys fix it? I will try find a 1.5.1 version to test it.

**Comment by WardenGnaw** [comment]
Allowing stdin through the integrated terminal for macOS is a known issue and is due to a limitation of `lldb-mi`. `gdb` through MI Mode allows us to redirect the tty, but this has not been implemented for `lldb-mi`.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
