### ISSUE TITLE
Add dynamic snippets to wrap selected code

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8076]
Type: Feature Request
insert outside code is very useful for use to surround code block with some statement.
just like VS 2019, we could insert `#if` to surround code block
```
# if 0
code block
#endif
```

snippet is a way to implement this.

so, let support them in C/C++ snippets.

C# now is supported
https://github.com/OmniSharp/omnisharp-vscode/pull/4715/files

after that we could select some code block， and trigger `insert snippet` to insert outside code.
demo:
https://github.com/heartacker/snippet-plus#usage

**Comment by sean-mcmanus** [comment]
We stopped using VS Code's .json-based snippets because it leads to undesirable completions (https://github.com/microsoft/vscode-cpptools/issues/2734). The VS insert snippet command appears to require the .json files, but we could possibly add our own C/C++: Insert Snippet command.
