### ISSUE TITLE
VS 14.0 msvc headers aren't automatically detected (fixed in 1.5.0, but is in 1.6.0)

### ISSUE THREAD

**Issue by Clinkz24** [microsoft/vscode-cpptools#8078]
#7789 

fix in 1.5.0, but it reappeared in 1.6.0.

**Comment by bobbrow** [comment]
@elahehrashedi can you investigate?  Thank you!

**Comment by elahehrashedi** [comment]
@Clinkz24 we will have a fix for this. I have a question though, do you have multiple versions of Visual Studio installed?

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
