### ISSUE TITLE
How to debug the third party library and entering the source cpp file of the library  in different workspace folder?

### ISSUE THREAD

**Issue by Mengke-Yuan** [microsoft/vscode-cpptools#8086]
### Brief Issue Summary

 How to debug the third party library and entering the source cpp file of the library  in different workspace folder?

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**:  3.18.0-rc2 
- **VSCode Version**:  1.57.0
- **CMake Tools Extension Version**:  v1.8.0
- **Compiler/Toolchain**: GCC 7.5.0

### Other Notes/Information

The main project use some third party libraries which has source files  header .h file and implementation cpp files in different workspace folder.  These libraries can be compiled into shared or static libraries and installed in system path with CMAKE_BUILD_TYPE set to Debug . The question is I cannot step into the cpp files of the third party libraries in the debuging process. Is there any suggestions to fix this problem. Thanks

**Comment by bobbrow** [comment]
@WardenGnaw is there any reason to suspect that multi-root would affect step in/step out?

@Mengke-Yuan I might suggest that you try to set breakpoints in the code and see if those will work.  If not, it might indicate that the libraries are not actually building with debug information like you expect. You might also want to set up some debugger logging as @WardenGnaw will suggest.  If you are using `launch.json` the settings will be in there, but if you are using the "Quick debug" button from CMake Tools, you can edit those settings with the `cmake.debugConfig` setting object.

**Comment by WardenGnaw** [comment]
@bobbrow No. Debugger is not aware of multiroot, but it will use the launch configuration it is given to set its current working directory for relative paths.

> I might suggest that you try to set breakpoints in the code and see if those will work. If not, it might indicate that the libraries are not actually building with debug information like you expect.

This will only work if you know how the 3rd party built its shared library and the source path it generated. 

You will need to add a [sourceFileMap](https://code.visualstudio.com/docs/cpp/launch-json-reference#_sourcefilemap) key:
```
"sourceFileMap": { 
   "<compiled-source-path>": "<editor-path>" 
}
```

Another issue is that it would be release bits so stepping may jump everywhere since it is not debug symbols.

**Comment by Mengke-Yuan** [comment]
After adding "set(CMAKE_CXX_FLAGS "-g")" in the CMakeLists.txt of main project , I can succesfully step into the source code of add.cpp.
