### ISSUE TITLE
Can't switch header/source

### ISSUE THREAD

**Issue by SteveShaw** [microsoft/vscode-cpptools#8087]
Bug type: Language Service

**Describe the bug**
- OS and Version: windows, 1.59.1
- VS Code Version:
- C/C++ Extension Version:  1.6.0
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: redhat linux
- I can't switch between header and source files even after the database is regenerated.
- 

- Configurations in `c_cpp_properties.json`

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/lib64/ccache/g++",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools",
            "compileCommands": "${workspaceFolder}/compile_commands.json",
            "browse": {
                "databaseFilename": "${workspaceFolder}/.vscode/cts.db"
            }
        }
    ],
    "version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Does it not work at all, even for the simple case with a test.cpp and test.h in the same folder? Is the Outline view also blank?

**Comment by savioret** [comment]
In my case, it works if they are in same folder.
If does not work anymore in 1.60.0 for this case (it worked with previous version):
```
./myfile.h
./source/myfile.cpp
```

**Comment by sean-mcmanus** [comment]
It's working for me, i.e. I'm not reproing the problem and we haven't gotten other reports of this not working. It sounds like there might be some issue with one of the files being excluded from the database. Is the Outline view populated for both files?

Are you opening the workspace via a symlink or is there a symlink on the path to the files?

**Comment by savioret** [comment]
No links. Nothing special.
The funny thing is that I have a copy of the same project folder and it works in there with the exact same file. So (I guess) there must be something related with cached data. 
I have cleared the Intellisense data, but no luck. I've also cleared the .vscode folder for the local project.
Is there anything else I could remove to force a kind of "reset" of the project or C++ cached data ? (I'm also in Windows).

**Comment by sean-mcmanus** [comment]
Did you do a Reset IntelliSense Database command? That should reset the database, which should be the only cached data that can affect the switching header source.

**Comment by SteveShaw** [comment]
Thank you, Sean. I found it may relate to my own project setting. I use remote-ssh to edit the project file. The switch between header and source files had been working perfectly until recently. I have tried many ways like delete the intellisense database/change the database name, but failed. Could you give me an example how to use the Reset IntelliSense Database Command?

**Comment by sean-mcmanus** [comment]
Did you try the command from the View->Command Palette?

**Comment by SteveShaw** [comment]
Is that `C/C++: Reset IntelliSense Database`? I did. Do I need to restart the vscode?

**Comment by sean-mcmanus** [comment]
That's the command. You shouldn't need to restart VS Code. What happened when you ran that command? If it fails somehow, it's possible another cpptools process has a lock on the database.

**Comment by SteveShaw** [comment]
How to check if it is failed, I can't see any output

**Comment by sean-mcmanus** [comment]
If it fails, it's supposed to show a failure error popup and if it succeeds it should show "The IntelliSense database was successfully reset." in the popup message. You could also double check by setting C_Cpp.default.databaseFilename to something like "${workspaceFolder}/.vscode/vc.db" and verify that the file is being deleted/recreated.

**Comment by SteveShaw** [comment]
I saw it shows `The IntelliSense database was successfully reset`. Do I need to set this value

```
"browse": {
                "databaseFilename": "${workspaceFolder}/.vscode/cts.db"
            }
```

**Comment by sean-mcmanus** [comment]
You can set it if you think the database isn't being created/reset correctly.

You could also set C_Cpp.loggingLevel to "Debug" and check the C/C++ pane in the Output panel for "tag parsing" messages and make sure the source/header files in question are being shown as parsed (something might be causing them to get skipped or fails to parse).

**Comment by SteveShaw** [comment]
Yes, I did that from the view menu

**Comment by SteveShaw** [comment]
This is the output

```
loggingLevel: Debug
loggingLevel has changed to: Debug
cpptools/didChangeCppProperties
$/setTraceNotification
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 231)
cpptools/getDocumentSymbols
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp
cpptools/getFoldingRanges: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 232)
cpptools/getCodeActions: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 233)
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 234)
Request canceled: 234
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 235)
Request canceled: 235
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 236)
Request canceled: 236
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp
cpptools/resetDatabase
cpptools/resetDatabaseReady
Database safe to open
Code browsing service initialized
Discovering files...
  Discovering files: 0 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Populate include completion cache.
  tag parsing file: /home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
  tag parsing file: /home/sshao/cts_dev/cts/core/cts/executioner/src/OrderManager.cpp
Done parsing open files.
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 237)
Request canceled: 237
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 238)
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 239)
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 240)
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 241)
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 242)
textDocument/hover: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp (id: 243)
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: file:///home/sshao/cts_dev/cts/core/cts/executioner/src/ExecutionerHost.cpp
```

**Comment by sean-mcmanus** [comment]
Do you have a workspace open? The logging "Discovering files: 0 file(s) processed" indicates that no files are being found. Only the open files are being tag parsed. If you have compileCommands set, then that could be causing the browse.path to be too small. The compile_commands.json needs to have references to the sources files which you want switch header/source to work for, since that is used to determine which folders should be iterated over.

**Comment by sean-mcmanus** [comment]
Running the C/C++: Log Diagnostics command can show info on the browse paths that are used by compileCommands and configurationProvider settings.

**Comment by savioret** [comment]
Hello Sean, 

In my case, I've changed the database to be local:
```json
"C_Cpp.default.browse.databaseFilename": "${workspaceFolder}/.vscode/vc.db",
```
I can see now the files there:
```
VC.DB
VC.DB-shm
VC.DB-wal
```

But same problem, no switch between .h and .cpp and vice-versa working.

**Comment by sean-mcmanus** [comment]
@savioret When you set C_Cpp.loggingLevel to "Debug" do you see "tag parsing" messages for those files when they are edited/saved (or when the database is reset)? The files might be excluded.

**Comment by JanGray** [comment]
I have no idea what you are talking about.

**Comment by JanGray** [comment]
I have no idea what you are talking about.

**Comment by savioret** [comment]
I have renamed a function and saved the file.
I got dozens of messages. The routes appear all uppercased, is that correct ?
Anyway I don't know what could this have to do with the h/cpp switch, as the tags of the files are perfectly discovered when I do "Go to symbol in workspace"

```
Discovering files...
  Discovering files: 0 file(s) processed
  656 file(s) removed from database
Done discovering files.
Populate include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Offering completion
sending 1 changes to server
  tag parsing file: C:\RT\SDK\RTAPP\INTERFACES\SOURCE\RT_IVIDEOPROCESS.CPP
   [ HERE DOZENS OF TAG PARSING OF FILES ]
  ```

**Comment by sean-mcmanus** [comment]
@savioret Uppercase is expected (the logging happens to show the case insensitive file name stored in the database). It seems like the files are getting tag parsed correctly. I'll try to see if anyone else on our team is able to repro the issue.

**Comment by savioret** [comment]
I have more info.
my project is in a folder:
`c:\vfx\rt`
If I just rename the parent folder it works:
`c:\vfx2\rt`

It makes me think about the "trusted" folders feature, which turns some plugins off when not accepted.
In theory the folder has all the permissions and it's in the trusted list, in fact I have disabled it just in case:
`"security.workspace.trust.enabled": false,`
But same results.

I think that somehow VSCode is blocking the folder even explicitly trusted.
Is there any way to hard-reset all trusting stuff ?

**Comment by sean-mcmanus** [comment]
If you're getting impacted by the trusted workspace feature, then our entire C/C++ extension would be disabled (none of our features would work, not just switch header/source). The command to use is "Workspace: Manage Workspace Trust".

Is "vfx" matching a files.exclude or C_Cpp.files.exclude setting?

@v-ericawu was also not able to repro this issue.

**Comment by savioret** [comment]
No is not. 
Likewise, if it was excluded, intellisense would not work and it's working.

Another think I just came up with, two or three months ago I forced the directory to be case sensitive, you know, from a Powershell:
```bash
(Get-ChildItem -Recurse -Directory).FullName | ForEach-Object {fsutil.exe file setCaseSensitiveInfo $_ enable}
```

I tried to just set it back to "disable" but same.
I don't know is this could have something to do because I did it 2 or 3 months ago, and the switch problem started with version 1.60

**Comment by savioret** [comment]
Well, also tried downgrading VSCode, even downgrading the C++ extension to several older versions.
Finally decided to delete `C:\Users\xxx\AppData/Roaming/Code` folder.

I works now !

I'm using settings sync so theoretically I'm using the same exact settings as before uninstalling it.
Definitely there was something wrong in `Code` folder.

**Comment by SteveShaw** [comment]
I found that if I disable `cmake` to configure my project folder, vscode can switch between source and header file.

**Comment by sean-mcmanus** [comment]
@savioret Hmm, I'm not sure what could have been wrong with the Code folder, other than the database (which can be cleared with the C/C++: Reset IntelliSense Database command).

@SteveShaw It's possible there some issue with the CMake Tools extension not sending us the correct browse info. We need more logging, such as from C/C++: Log Diagnostics to determine if that's the case or not, or a repro project. In general, switch header/source works with the CMake Tools configurationProvider.

**Comment by JeffyOLOLO** [comment]
Hi everyone!
I had the same problem, switching stopped working.
I read your comments and tried to Reset IntelliSence database, then uninstall Microsoft Makefile Tools and remove it as `configProvider` in `c_cpp_properties.json`
Not sure what exactly helped, but now it works!
