### ISSUE TITLE
ssh remote debug can't set the breakpoint when the program started by  bash shell script

### ISSUE THREAD

**Issue by aengusjiang** [microsoft/vscode-cpptools#809]
VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
cpptools - Version :0.11.4
local machine OS Version: Windows_NT ia32 10.0.15063
remote machine: 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

g++ version： g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
gdb version： GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
bash version： GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
===============================================================

Problem description：
debug way：ssh remote attach

step：
case one:
1. run the program on remote machine in terminal such as ./bin/Test
2. choose remote attach.
3. set the breakpoint.
     Note: in this case: it works well.

case two:
1. run the program on remote machine in terminal with bash shell script such as ./test.sh
   `#!/bin/bash
   ./bin/Test
   ` 
2. choose remote attach.
3. set the breakpoint.
     Note: in this case: it doesn't work. the breakpoint is in gray color. hint the attemping to  bind the beakpoint.

Here some log:
`1: (208) LaunchOptions    </SetupCommands>
1: (208) LaunchOptions</PipeLaunchOptions>
1: (267) Starting: "ssh" smite@192.168.1.78 "gdb --interpreter=mi"
1: (572) ->=thread-group-added,id="i1"
1: (572) ->~"GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1\n"
1: (572) ->~"Copyright (C) 2017 Free Software Foundation, Inc.\n"
1: (572) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
1: (572) ->~"This GDB was configured as \"x86_64-pc-linux-gnu\".\nType \"show configuration\" for configuration details."
1: (572) ->~"\nFor bug reporting instructions, please see:\n"
1: (573) ->~"<http://www.gnu.org/software/gdb/bugs/>.\n"
1: (573) ->~"Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\n"
1: (573) ->~"For help, type \"help\".\n"
1: (573) ->~"Type \"apropos word\" to search for commands related to \"word\".\n"
1: (573) ->(gdb)
1: (580) <-1001-gdb-set target-async on
1: (583) ->1001^done
1: (583) ->(gdb)
1: (583) 1001: elapsed time 2
1: (589) <-1002-enable-pretty-printing
1: (592) ->1002^done
1: (592) ->(gdb)
1: (592) 1002: elapsed time 3
1: (592) <-1003-interpreter-exec console "set pagination off"
1: (598) ->=cmd-param-changed,param="pagination",value="off"
1: (598) ->1003^done
1: (598) ->(gdb)
1: (598) 1003: elapsed time 5
1: (598) <-1004-gdb-set solib-search-path /smbshare/test/build/bin:
1: (600) ->1004^done
1: (600) ->(gdb)
1: (600) 1004: elapsed time 2
1: (600) <-1005-gdb-set stop-on-solib-events 1
1: (602) ->1005^done
1: (602) ->(gdb)
1: (602) 1005: elapsed time 2
1: (619) ->=thread-created,id="1",group-id="i1"
1: (622) ->1008^done
1: (622) ->=library-loaded,id="/usr/lib/x86_64-linux-gnu/libstdc++.so.6",target-name="/usr/lib/x86_64-linux-gnu/libstdc++.so.6",host-name="/usr/lib/x86_64-linux-gnu/libstdc++.so.6",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007f4fc7228d20",to="0x00007f4fc72d4cc9"}]
1: (622) ->=library-loaded,id="/lib/x86_64-linux-gnu/libgcc_s.so.1",target-name="/lib/x86_64-linux-gnu/libgcc_s.so.1",host-name="/lib/x86_64-linux-gnu/libgcc_s.so.1",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007f4fc6f8ba70",to="0x00007f4fc6f9b8b5"}]
1: (622) ->=library-loaded,id="/lib/x86_64-linux-gnu/libc.so.6",target-name="/lib/x86_64-linux-gnu/libc.so.6",host-name="/lib/x86_64-linux-gnu/libc.so.6",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007f4fc6bdf8b0",to="0x00007f4fc6d31f14"}]
1: (622) ->=library-loaded,id="/lib/x86_64-linux-gnu/libm.so.6",target-name="/lib/x86_64-linux-gnu/libm.so.6",host-name="/lib/x86_64-linux-gnu/libm.so.6",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007f4fc68bc600",to="0x00007f4fc692dd0a"}]
1: (622) ->=library-loaded,id="/lib64/ld-linux-x86-64.so.2",target-name="/lib64/ld-linux-x86-64.so.2",host-name="/lib64/ld-linux-x86-64.so.2",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007f4fc7521ac0",to="0x00007f4fc753f640"}]
1: (627) <-1009-thread-info 1
1: (629) 1008: elapsed time 12
1: (667) ->~"0x00007f4fc6c8b740 in nanosleep () from /lib/x86_64-linux-gnu/libc.so.6\n"
1: (667) ->*stopped,frame={addr="0x00007f4fc6c8b740",func="nanosleep",args=[],from="/lib/x86_64-linux-gnu/libc.so.6"},thread-id="1",stopped-threads="all",core="0"
1: (668) ->1009^done,threads=[{id="1",target-id="process 55426",name="Test",frame={level="0",addr="0x00007f4fc6c8b740",func="nanosleep",args=[],from="/lib/x86_64-linux-gnu/libc.so.6"},state="stopped",core="0"}]
1: (668) ->(gdb)
1: (672) 1009: elapsed time 45
=thread-group-added,id="i1"
GNU gdb (GDB) 8.0
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
1: (923) ->^running
1: (923) ->*running,thread-id="all"
1: (923) ->(gdb)
1: (920) <--exec-continue
1: (923) ->^running
1: (923) ->*running,thread-id="all"
1: (923) ->(gdb)
1: (75368) <-1013-exec-interrupt
1: (75371) ->1013^done
1: (75371) ->(gdb)
1: (75371) 1013: elapsed time 3
1: (78369) Debugger failed to break. Trying again.
1: (78369) <-1014-exec-interrupt
1: (78379) ->1014^done
1: (78379) ->(gdb)
1: (78379) 1014: elapsed time 10
1: (81370) Debugger failed to break. Trying again.
1: (81370) <-1015-exec-interrupt
1: (81380) ->1015^done
1: (81380) ->(gdb)
1: (81380) 1015: elapsed time 10
`
Here the demo code(I can't upload the source code, so i insert it here)
cmake file:
`cmake_minimum_required (VERSION 2.8)

# set the project name
project(Test)

#set cxx flags
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -g -pipe -D_NEW_LIC -D_GNU_SOURCE -fPIC -D_REENTRANT -std=c++11")

# set the exe lib output dir
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

# set the target name fot this target
set(TARGE_NAME "Test")

# for the servers
include_directories("include")

aux_source_directory("." TARGET_SRC)
add_executable(${TARGE_NAME} ${TARGET_SRC})
target_link_libraries(${TARGE_NAME})
`
test.cpp:
`#include <iostream>
#include <stdio.h>
#include <unistd.h>
#include <vector>

int main()
{
    int x = 0;
    std::vector<int> testVec { 1, 2, 3, 4, 5 };
    while (1)
    {
        printf("Pid %d: %d\n", getpid(), x++);
        sleep(1);
    }
    return 0;
}`

launch:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Local Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/build/bin/Test",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}/build",
            "environment": [],
            "externalConsole": true,
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
            "name": "Local Attach",
            "type": "cppdbg",
            "request": "attach",
            "program":"${workspaceRoot}/build/bin/Test",
            "processId": "${command:pickProcess}",
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
            "name": "Remote Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "build/bin/Test", // the program locate remote pc
            "args": [],
            "stopAtEntry": false,
            "cwd": "/smbshare/test",               // can use the relative path
            "environment": [],
            "externalConsole": false,
            "pipeTransport": {
                "pipeCwd": "",             // Set empty if We have added the ssh.exe to path, or set the full path
                "pipeProgram": "ssh.exe",
                "pipeArgs": [
                    "smite@192.168.1.78"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/smbshare/test": "${workspaceRoot}" // [remote：local] remote must be use the absolute path
            },
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },
        {
            "name": "Remote Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/smbshare/test/build/bin/Test",
            "processId": "${command:pickRemoteProcess}",
            "pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "ssh",
                "pipeArgs": [
                    "smite@192.168.1.78"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/smbshare/test": "${workspaceRoot}"
            },
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "logging": {
                "engineLogging": true
            }
        }
    ]
}`

**Comment by pieandcakes** [comment]
@AbelaroJiang Is this a different issue or the same issue as #787 but on Ubuntu? Is the second instance actually debugging? I assume since the script has it running as a child process of bash that it might not allow you to directly attach? I will try this when I have some time.

**Comment by aengusjiang** [comment]
Hi, My friend. I think this is a different issue about setting the breakpoint.
Remember do some change before you test it on ubuntu or it can remote attach by ssh for required the super user permission.
reference to: https://askubuntu.com/questions/41629/after-upgrade-gdb-wont-attach-to-process

**Comment by aengusjiang** [comment]
This issue seem to be solved.
