### ISSUE TITLE
The address location @ is not support.

### ISSUE THREAD

**Issue by JasonLeeCn** [microsoft/vscode-cpptools#8093]
Issue Type: <b>Bug</b>

Example: volatile unsigned int a @0x100; 
The variable 'a' is not define becouse the '@' flag is not supported.

Extension version: 1.6.0
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (10.52GB free)|
|Process Argv|D:\\Material\\STM8\\STM8S_StdPeriph_Lib --crash-reporter-id 29eef5cb-e61a-49fe-93ba-ff93b9f63ac6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
vsdyn321cf:30356811
vscus224cf:30358040

```

</details>

**Comment by sean-mcmanus** [comment]
Is the @ flag part of the C or C++ standard? As far as I know, it is not. What compiler or compiler extension is required for that?
