### ISSUE TITLE
#include error for <bits/stdc++.h>

### ISSUE THREAD

**Issue by Piyush-Bora** [microsoft/vscode-cpptools#8098]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 11
- VS Code Version: latest
- C/C++ Extension Version: latest
- Other extensions you installed (and if the issue persists after disabling them): none
- A clear and concise description of what the bug is.:       cannot open source file "bits/stdc++.h"

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment]
We need more repro info, such as what would be shown via from the C/C++: Log Diagnostics command from the Command Palette, i.e. what compiler are you using?
