### ISSUE TITLE
highlighting and auto-complete is on and off

### ISSUE THREAD

**Issue by ManasVegi** [microsoft/vscode-cpptools#8099]
Issue Type: <b>Bug</b>

The highlighting and auto-complete is very on and off on C++. All other Intellisense work quite well in VSC
![image](https://user-images.githubusercontent.com/53593482/131973719-82f20075-3a19-4bf7-8607-1e703c1558b2.png)

Extension version: 1.6.0
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (3.54GB free)|
|Process Argv|--crash-reporter-id c1d9d651-ee66-48ac-970c-f4bcce38f46a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn321cf:30356811
pydsgsc2:30361791
vscus224cf:30358040

```

</details>

**Comment by michelleangela** [comment]
@ManasVegi 
Could you provide the following info to help investigate the cause of why highlighting and auto-complete is not working consistently?

- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- Information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).


**Steps to reproduce**
(please include any specific steps to reproduce the issue if any)


**Logs**

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
- Logs from the language server logging. For instructions to get these logs, please see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server
