### ISSUE TITLE
IntelliSense shows everything - Context Awareness required

### ISSUE THREAD

**Issue by StefanFabian** [microsoft/vscode-cpptools#81]
While it's really good how IntelliSense finds everything in all the include files, it's rather annoying that it displays everything all the time.
What point is there in showing me functions that I can't even access in this context because I don't have the object that has that method?
This makes finding the stuff that I really need a real pain in the...
It's rather annoying to have to check every suggestion if it actually is part of the object and most times there are just so many that I have to check the docs anyway which renders IntelliSense pretty much completely useless.

**Comment by sridmad** [comment]
Agree. We are looking into making it better and you should see improvements in the area in future updates.

**Comment by csholmq** [comment]
@sridmad Any roadmap available for the public yet? E.g feature plan or perhaps a date for open sourcing?

**Comment by xziya** [comment]
And it always shows the suggestions after punctuation like semicolon and left brace.

**Comment by agauniyal** [comment]
https://github.com/Valloric/ycmd could be of help here.

**Comment by agauniyal** [comment]
two similar issues - 
- https://github.com/Microsoft/vscode-cpptools/issues/180
- https://github.com/Microsoft/vscode-cpptools/issues/13

**Comment by sridmad** [comment]
@csholmq - We plan to implement more context aware intellisense in a couple of months.
Open source - we are actively discussing how and when we can open source the extension. We should have more about this in about a month.

@sinpen - auto complete after punctuations should be fixed in 0.9.0 of the extension. If you are still seeing the behavior please open an issue.

**Comment by sridmad** [comment]
#13   covers enabling accurate auto completion
