### ISSUE TITLE
No symbol information for *.cpp/*.h  files for vscode on CentOs

### ISSUE THREAD

**Issue by linlinzy** [microsoft/vscode-cpptools#810]
Env: 
   CentOS 7.2 64bit; VSCode 1.11.2; vscode-cpptools: 0.11.4.
Issues:
    No symbols found when using Ctrl+Shift+O, and also cannot Go to definition and so on.
Anyone may help about this?

**Comment by sean-mcmanus** [comment]
The language service doesn't work out of the box on CentOS due to a dependency on glibc 2.18. See https://github.com/Microsoft/vscode-cpptools/issues/19 for a workaround.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
