### ISSUE TITLE
Solve ages of security issues by providing option to auto initialise

### ISSUE THREAD

**Issue by ericsia** [microsoft/vscode-cpptools#8106]
Type: Feature Request

So I've been wondering it's always dangerous for leaving preventable security issue like dangling pointer.
Here is my proposal, is it possible to add an option for intellisense to always auto initialise when a user finish typing a variable?

Meaning when a comma or semicolon is met, then the variable is auto initialise by intellisense adding " = NULL" for example:
```
int ex = 0;
char ex = '\0';
double ex = 0.0;
char[] ex = NULL;
int *pointer = NULL;
char *ex = NULL;
double *ex = NULL;
etc
```
![image](https://user-images.githubusercontent.com/24624808/132267883-5cf6a8e2-b180-4559-836f-2bb1bd1c65a7.png)

**Comment by sean-mcmanus** [comment]
I'm not sure if this is possible...maybe as part of formatting it could check for this.

**Comment by ericsia** [comment]
> clang-tidy
I never use clang-tidy before, after google I found it got option to check it but it didn't mention about fixing it.
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-init-variables.html

It would be nice if vscode-cpptools extension can perform auto-initialise rather than just giving warning. 
This would make a huge impact for people switch from other ide like CodeBlock DevC etc to VsCode.

**Comment by ericsia** [comment]
> What about code analysis? Does clang-tidy have a feature like this combined with `--fix` or something?

I never use clang-tidy before, after google I found it got option to check it but it didn't mention about fixing it.
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-init-variables.html

It would be nice if vscode-cpptools extension can perform auto-initialise rather than just giving warning. 
This is a sweet deal and would make a huge impact for people switch from other ide like CodeBlock DevC etc to VsCode.

**Comment by sean-mcmanus** [comment]
Yeah, I haven't checked if clang-tidy provides a fix for that yet via --fix.

**Comment by ericsia** [comment]
I just ran it, wow it is quite powerful. Here is the command line
`clang-tidy  --checks=cppcoreguidelines-init-variables -fix-errors "inputFile.cpp"`
![image](https://user-images.githubusercontent.com/24624808/132440676-f1f4b152-ee0b-4dba-9379-28552274bdde.png)

Btw this is a very good reference on what other security issue they check:
https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/cppcoreguidelines/InitVariablesCheck.cpp

But still, I wish everyone who use vscode-cpptools can enjoy this awesome feature without installing the whole llvm package.
This will be very handy to make it as built-in feature.

**Comment by sean-mcmanus** [comment]
Yeah, we're working on integrating clang-tidy for our next release: https://github.com/microsoft/vscode-cpptools/issues/2908
