### ISSUE TITLE
Attaching the debugger to a python process crashes

### ISSUE THREAD

**Issue by tjahn** [microsoft/vscode-cpptools#8115]
# Bug type: Debugger

Hello I struggle with an error when trying to debug a native python c++ module by attaching the C++ debugger to  the python process. Some months ago the same workflow did not make any problems. 

## Description
For debugging I usually execute my python scripts interactively in vscode with the python extension and attach the c++ debugger to it.
This stopped working.
The debug-console shows that the debugger attached and the symbols got loaded. But the next time I execute some python cell, I get an error in the debug-console:
```
Stopping due to fatal error: InvalidOperationException: No handler registered for request of type 'setPydevdSourceMap'!
``` 

## To Reproduce
* Install the extensions  ms-python.python and ms-vscode.cpptools.
* create a python script 
```python
# %% first run this cell to start the python process and get its PID
import os
print(os.getpid())
# %% after attaching the debugger run this cell to trigger the error
print("test")
```
* execute the first cell of the python script in vscode interactively
* attach you debugger to the printed pid using the following launch.json entry
```json
        {
            "name": "(lldb) Attach Debugger",
            "type": "cppdbg",
            "request": "attach",
            "program": "/proc/${command:pickProcess}/exe",
            "processId": "${command:pickProcess}",
            "MIMode": "lldb",
        },
```
* try executing the second cell after the debugger attached

## Versions:
* VSCode  1.60.0 on MacOS Big Sur 11.5.2
* remote SSH server is an OpenSuse 15.2
* ms-python.python@v2021.9.1191016588
* ms-vscode.cpptools@v1.6.0.

**Comment by WardenGnaw** [comment]
I'm not sure exactly what `SetPydevdSourceMap` is supposed to be. The generic error `Stopping due to fatal error: InvalidOperationException: No handler registered for request of type '<Request>'` is due to our Debug Adapter Protocol handler. 

The only requests we handle are from https://microsoft.github.io/debug-adapter-protocol/specification

The only occurrences I could find online are `pydev` and `ptvsd`.

This also may be a python debug adapter specific request that is bleeding into the C++ debug adapter.

**Comment by tjahn** [comment]
Thank you for reviewing the issue. SetPydevdSourceMap indeed seems to somehow leak from the python extension. I try bringing it up in microsoft/vscode-python.

**Comment by greazer** [comment]
@WardenGnaw, not sure how the Python extension or the Jupyter extension could play any role here.

**Comment by tjahn** [comment]
The string 'setPydevdSourceMap' is only used in microsoft/ptvsd (deprecated) and microsoft/debugpy, at least within this organisation. Maybe they have an idea on how these messages bleed into the VSCode C++ debugger.

**Comment by WardenGnaw** [comment]
@greazer Something is sending the C/C++ Debug Adapter `setPydevdSourceMap` which is not an official DAP and it seems to be a python specific request. It may be from the Python Extension or as mentioned the ptvsd or debugpy repos.
