### ISSUE TITLE
Add enum completions at the call site for functions that take enums

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8117]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/8103

<div type='discussions-op-text'>

<sup>Originally posted by **ivan64435** September  4, 2021</sup>
![constant](https://user-images.githubusercontent.com/79205604/132115982-56963925-849f-4477-9d26-a6b9bb0a2ff4.gif)
</div>

**Comment by bobbrow** [comment]
A C++ example:
```
enum class Foo
{
    Item1,
    Item2
};

void Func(Foo f1, Foo f2)
{
}

int main()
{
    Func(Foo::Item1, );
}
```
`Foo` should be suggested after the `(` and the `,`.  If it was regular enum, it would suggest `Item1` and `Item2`.

**Comment by bobbrow** [comment]
We'd need this feature in VS before we'll get it here.

**Comment by sean-mcmanus** [comment]
I assume it would be able to suggest the full Foo::Item1, etc. and not just Foo.

**Comment by bobbrow** [comment]
> I assume it would be able to suggest the full Foo::Item1, etc. and not just Foo.

I think that would be a good feature too.  I've never seen our IntelliSense suggest fully scoped enums before though.  That would be new for sure.

**Comment by mhamri** [comment]
in MQL it becomes a little more uglier

![image](https://user-images.githubusercontent.com/8991783/137576100-8d78b7d2-4a8c-4862-b1c5-22dab40c14e5.png)

while the available options only should be one of these two 

![image](https://user-images.githubusercontent.com/8991783/137576108-fe47d934-215f-4f4c-ae5a-87f34e5639b6.png)

the correct suggestion isn't even at the top of the list
