### ISSUE TITLE
Peek definition and peek declaration break the minimap 

### ISSUE THREAD

**Issue by donatoaguirre24** [microsoft/vscode-cpptools#812]
Since the last VS Code update (1.13) after I use peek definition or peek declaration the minimap disappear. I have no idea why it happens, the only solution I found is to close and reopen the file in which I am working to recover the minimap, but it is really very annoying.

**Comment by sean-mcmanus** [comment]
It's a VS Code bug -- https://github.com/Microsoft/vscode/issues/28093 . It looks like it's been fixed but hasn't made it into the Insider's build yet.
