### ISSUE TITLE
cppdbg lost "args" setting if use customLaunchSetupCommands

### ISSUE THREAD

**Issue by fbs2016** [microsoft/vscode-cpptools#8125]
Bug type: General

**Describe the bug**
    OS and Version: Ubuntu 20.04
    VS Code Version: 1.56.2
    C/C++ Extension Version: v1.4.1
    Other extensions you installed (and if the issue persists after disabling them):
cppdbg lost "args" setting if use customLaunchSetupCommands

**To Reproduce**
*Please include code sample and `task.json` files.*

I set the args a/b/c in "args", but it lost when running after use customLaunchSetupCommands. The args work well if no customLaunchSetupCommands.

` {
            "name": "ccc",
            "type": "cppdbg",
            "request": "launch",
            "program": "dddd",
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "externalConsole": false,
            "args": [
                "a=main",
                "b=100",
                "c=222"
            ],
   
            "MIMode": "gdb",
            "miDebuggerPath": "xxx",
            "targetArchitecture": "x86_64",
            "miDebuggerServerAddress": "",
            "setupCommands": [
                {
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "customLaunchSetupCommands": [
   
                {
                    "text": "file xxx"
                },
      
            ],
            "launchCompleteCommand": "exec-run",
            "logging": {
                "trace": true,
                "engineLogging": true
            },
        },`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by WardenGnaw** [comment]
`CustomLaunchSetupCommands ` is used to override the default launch commands which includes setting up the executable, arguments, `main` breakpoint, environment, and more. 

See https://github.com/microsoft/MIEngine/blob/d7d2c7e68f2d03286fb9f7ba8f789719ff8adc3d/src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs#L676-L681
