### ISSUE TITLE
GDB breakpoint not working in 1.6.0.

### ISSUE THREAD

**Issue by hotTeaFun** [microsoft/vscode-cpptools#8126]
Bug type: Debugger

**Describe the bug**
- OS and Version: Manjaro 20.01
- VS Code Version: 1.60.0
- C/C++ Extension Version: 1.6.0
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
GDB breakpoint is ignored.

**To Reproduce**
1.  create a demo cpp source file.
2.  debug it with a breakpoint enabled.
3. It wouldn't stop at any breakpoint.

launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "g++ build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```
task.json
```
{
    "tasks": [
        {
            "type": "shell",
            "label": "g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "/usr/bin"
            }
        }
    ],
    "version": "2.0.0"
}
```

**Comment by WardenGnaw** [comment]
To help me further investigate, can you add the following to your launch.json configuration and share the output from the Debug Console?

```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

**Comment by Y24** [comment]
Here's the log file: [logs.txt](https://github.com/microsoft/vscode-cpptools/files/7140519/logs.txt)

I think the  "Enabled breakpoint detection mechanism" is broken because there are no relevant events at the event queue.

> It's very annoying because I have tried cLion and it works.

**Comment by xgdgsc** [comment]
Why is it closed? I see disable breakpoints not working when debug is running in recent versions. I need to restart debug to make the disabled breakpoint effective.
