### ISSUE TITLE
switching header/source not working

### ISSUE THREAD

**Issue by SunkyeHwang** [microsoft/vscode-cpptools#8130]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

swithcing between  cpp/h doesn't work, it works c/h although.

Extension version: 1.6.0
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 4.15.0-156-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (16 x 2401)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.39GB (22.28GB free)|
|Process Argv|--unity-launch --crash-reporter-id 3b9a149f-d286-411c-9ec0-0b9941baa06d|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30364559
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224:30358039
vssid140:30363603

```

</details>

**Comment by sean-mcmanus** [comment]
We need more repro info, i.e. we're not able repro this issue and it hasn't been widely reported by others. It's possible the .cpp/.h files might not be in the database or something else could be causing the switching to knot work. Do types in the .cpp/.h files get found via Find All References or Go to Definition? How are the .cpp/.h located relative to each other?

**Comment by SteffKeller** [comment]
I have exactly the same issue.
Switch between source/ header is not working anymore. Neither with right click ""alt" + "o" , or context menu "Switch Header/Source".

_"It's possible the .cpp/.h files might not be in the database or something else could be causing the switching to knot work. "_
No, except from this issue all other features like "Go the declaration" are working properly.

_Do types in the .cpp/.h files get found via Find All References or Go to Definition?_ 
Yes.

_How are the .cpp/.h located relative to each other?_
..appl/src/folder_foo/module.cpp
..appl/inc/folder_foo/module.h

The whole environment is running inside a docker container inside vs code.
I also tried a completely new Docker container, but the problem persists.
Remove and reinstall of the extension and vs code did not help.

C/C++ Version: v1.6.0

Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:01:43.795Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-37-generic snap

**Comment by SteffKeller** [comment]
The bugis gone, for whatever reason.
