### ISSUE TITLE
C++ Intellisense : Quickly go back to the position previous to last Goto Declaration/Definition

### ISSUE THREAD

**Issue by fredjm31** [microsoft/vscode-cpptools#8134]
Type: Feature Request

Could you add a way to quickly go back to the position previous to last Goto Declaration/Definition ?
The Alt Left key is not doing that, because, if after Goto Declaration/Definition you did some cursor movements (Page Up/Down, Mouse clics, ...), you have to roll back all these movements before rolling back the Goto Declaration/Definition.

Thanks.
Fred.

**Comment by Colengms** [comment]
Hi @fredjm31 .  You might consider moving this feature request to [the VS Code repo](https://github.com/microsoft/vscode/issues).  The C/C++ extension will respond to VS Code's request for the location of a declaration/definition, but it's VS Code that is performing the navigation.  Also, addressing this in VS Code itself would provide a solution for all languages, not just C/C++.

**Comment by sean-mcmanus** [comment]
It's https://github.com/microsoft/vscode/issues/27112
