### ISSUE TITLE
Syntax error not highlighted

### ISSUE THREAD

**Issue by bryanfok** [microsoft/vscode-cpptools#814]
For example, `std::vectoor vec;` does not highlighted in the visual studio code editor. Or do I need to provide additional configure it?

**Comment by bobbrow** [comment]
If you are using the VS Code Insiders build, linting will be on by default.  If you are using the regular VS Code build, then you need to add `"C_Cpp.intelliSenseEngine": "Default"` to your settings.json file to turn it on.

You then need to ensure that your `"includePath"` is set correctly in the c_cpp_properties,json file in order for standard libraries to be discovered.

**Comment by bryanfok** [comment]
@bobbrow Thanks for your response.
