### ISSUE TITLE
Additional include directories not found

### ISSUE THREAD

**Issue by danielwolbach** [microsoft/vscode-cpptools#8142]
Bug type: Language Service

**Describe the bug**
- OS and Version: Fedora 34 (Workstation Edition)
- VS Code Version: 1.60.0
- C/C++ Extension Version: 1.60
- Other extensions you installed (and if the issue persists after disabling them): CMake Tools (issue persists after disable)

The extension does not find my header files in the `include` directory in my workspace folder even though `${workspaceFolder}/include` is in my `includePath` . 

**Expected behavior**

The extension should find the header files in the `include` directory.

**Code sample and logs**

Content of `.vscode/c_cpp_properties.json`:

```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${default}",
                "${workspaceFolder}/include/"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "intelliSenseMode": "linux-clang-x64",
            "configurationProvider": "ms-vscode.cmake-tools",
            "cppStandard": "c++17",
            "browse": {
                "path": [],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
}
```

**Screenshots**

![screenshot](https://i.ibb.co/SBbCFY0/Bildschirmfoto-vom-2021-09-13-02-55-50.png "screenshot")

**Comment by michelleangela** [comment]
@octowaddle 
Could you try adding `**` to the include path? For example: `${workspaceFolder}/include/**` or `${workspaceFolder}/**`.

By adding `**`, it will search a path recursively. For example, `${workspaceFolder}/**` will search through all subdirectories while `${workspaceFolder}` will not.

For more information about the properties in c_cpp_properties.json see
https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference#_configuration-properties. The property description is also available by hovering over the property name in c_cpp_properties.json or in the IntelliSense Configuration UI via command `C/C++: Edit configurations (UI)`.

**Comment by octowaddle** [comment]
Already tried these. Didn't work either. The weird thing is that for some reason it works on Ubuntu Linux. Then, I tried it on Windows 10 and again, it didn't work. At this point I am just very confused. I'll keep trying some more settings, maybe I can resolve it.

**Comment by michelleangela** [comment]
Does your project have CMake? Sorry, I just noticed that `ms-vscode.cmake-tools` is set. If this is set, then the extension will try to get includes provided by cmake-tools.

You can also enable the language server logging to see which includes are being processed and from where.
https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server

**Comment by octowaddle** [comment]
I just noticed that! Even though CMake Tools extension was diasabled, the C++ extension tried to use it as a configuration provider. I have now manually disabled it and it works just fine. But it's weird that CMake Tools does not properly provide the include path, I set it up in my ` CMakeLists.txt`.

**Comment by michelleangela** [comment]
> But it's weird that CMake Tools does not properly provide the include path, I set it up in my ` CMakeLists.txt`.

If the cmake-tools extension is failing to provide the include paths when the extension is enabled, you can report the issue at https://github.com/microsoft/vscode-cmake-tools/issues. I would also first check if cmake-tools extension is able to configure successfully too.

**Comment by octowaddle** [comment]
CMake Tools configures successfully. I'll open an issue at the CMake Tools extensions. Thank you very much for your assistance!
