### ISSUE TITLE
Intellisense is not giving warning for syntax error

### ISSUE THREAD

**Issue by Ankan1998** [microsoft/vscode-cpptools#8144]
![error](https://user-images.githubusercontent.com/36896102/133071865-44c99a3f-eea4-4101-bc7d-00e1ea4629e0.PNG)

**I omitted ";" (semicolon) after namespace, but it is not giving any warning**

**Comment by bobbrow** [comment]
We currently do not show warnings unless a folder is open.  If you have opened a workspace folder, then the other reason the warnings wouldn't show is if the `C_Cpp.errorSquiggles` setting is set to "Disabled".
