### ISSUE TITLE
Ctrl+click does not always navigate to definition

### ISSUE THREAD

**Issue by Omcsesz** [microsoft/vscode-cpptools#8151]
Bug type: Language Service

Hello, Team!

In some cases, when I try to open header file from a source file with Ctrl+click, it does not work (see attachment). Can you please support?
[ClickOnHeaderFilesDoesNotWork](https://user-images.githubusercontent.com/1839739/133336342-09f34bc8-f670-4ca0-a9d7-9a6bb8303025.gif)

**Describe the bug**
- OS and Version: Ubuntu 21.04
- VS Code Version: 1.60

**Expected behavior**

The header file being clicked on shall be opened.

**Comment by sean-mcmanus** [comment]
I'm not able to repro the issue. I'm guessing the root problem is that the target header file is not being located in your browse database for some reason, such as not being in the workspace or blocked by a files.exclude setting. Are you able to identify a reason why the file would not be in the database? Are you able to provide some repro workspace? Are there any symlinks on the path?

**Comment by Omcsesz** [comment]
@sean-mcmanus Can he problem be that the header filename contains a dash?

**Comment by sean-mcmanus** [comment]
I tried that, but the dash is being handled correctly for me. You only repro the issue with files with a dash in the name? What happens after you manually open the file, does it become fixed?

**Comment by Omcsesz** [comment]
I only experienced this issue with headers with dash in their name.

**Comment by sean-mcmanus** [comment]
I'll try to see if anyone else on our team is able to repro the issue.

**Comment by sean-mcmanus** [comment]
@v-ericawu was also not able to repro the issue.

@Omcsesz Is it possible the "-" is matching a files.exclude or C_Cpp.files.exclude setting? Or could it be an issue with Ubuntu 21 (we only test with Ubuntu 20)?

**Comment by Omcsesz** [comment]
@sean-mcmanus I could reproduce it on Ubuntu 20.10.

**Comment by sean-mcmanus** [comment]
Does it work if you use right-click and select "Go to Definition"? If so, the Ctrl+Click issue is probably a VS Code.

**Comment by Omcsesz** [comment]
@sean-mcmanus Yes, that way it is working.

**Comment by sean-mcmanus** [comment]
Could you file a bug at https://github.com/microsoft/vscode/issues ? Tell them our C/C++ extension doesn't believe it's a bug with our extension due to the fact that it appears to be a UI-level issue that doesn't repro via the Go to Definition command -- our extension just gets a go to definition request from VS Code regardless of if it's via Ctrl+Click or right-click Go to Def.
