### ISSUE TITLE
Implement platform-specific extensions

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#8152]
- [x] Update minimum required VS Code version to 1.61
- [x] Replace "*" in package.json with actual events
- [x] Remove "*" activation logic (remove rewrite logic, merge activation and realActivation, remove TemporaryCommandRegistrar)
- [x] Remove code that downloads platform-binaries and checks `install.lock`
- [x] Remove 'runtime dependencies' from package.json
- [x] Update Offline release pipeline to add `--target <platform>` when packaging each vsix
- [x] Add manual intervention step after building vsix'es, before invoke `vsce publish` to publish each vsix
- [ ] Remove Online release pipeline

[Platform-Specific Extension Documentation](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions)

**Comment by isidorn** [comment]
@Colengms thanks a lot for creating this
Refs: https://github.com/microsoft/vscode/issues/23251

**Comment by heartacker** [comment]
c# has add this implement, https://github.com/OmniSharp/omnisharp-vscode/issues/4775   hope that we can earn it ASAP

**Comment by bobbrow** [comment]
Our next release (1.8.0) will have it.

**Comment by Colengms** [comment]
HI @isidorn , I noticed that `vsce login` doesn't accept a PAT directly.  Is there a way to script login such that no user interaction is required (so we can automate that step - publishing 10 VSIX's) ?

**Comment by isidorn** [comment]
@Colengms great that you are automating this.
I suggest to follow the sample that @joaomoreno created here https://github.com/microsoft/vscode-platform-specific-sample/blob/main/.github/workflows/ci.yml

So yes, you can use the `VSCE_PAT` env variable. [Example](https://github.com/microsoft/vscode-platform-specific-sample/blob/main/.github/workflows/ci.yml#L76) how Joao sets it.

**Comment by isidorn** [comment]
👏  🎉 🚀

**Comment by puremourning** [comment]
After this change, is there any way to get the vscode-cpptools packages from a known URL ? the vscode marketplace  doesn't (to my knowledge) allow direct downloads for offline use

**Comment by sean-mcmanus** [comment]
@puremourning The marketplace allows direct downloads, e.g. https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/cpptools/<version>/vspackage?targetPlatform=linux-x64

**Comment by puremourning** [comment]
Unfortunately, that's heavily rate-limited and frequency leads to HTTP 429 when this is automated in any way (e.g. in CI, or as part of other DAP client's installation tools):


```
ben@BenMBP2021 gadget_upgrade % ./download_and_checksum_gadget.py vscode-cpptools
Downloading https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/cpptools/1.9.7/vspackage?targetPlatform=l
inux-x84 to ./cpptools-linux.vsix
Failed - HTTP Error 429: , will retry in 1 seconds
```

**Comment by puremourning** [comment]
It seems that the marketplace has a CDN api of some sort, but it seems ... internal... https://github.com/actions/virtual-environments/pull/3244/files / https://github.com/microsoft/vscode/pull/16275/files.

To explain why this matters to me [vimspector](https://github.com/puremourning/vimspector) has an installer which grabs the vsix and uses the debug adapter out of it. It does this for a number of things and while a few of them are using the marketplace, these are not let's say high-volume, but almost all vimspector users install vscode-cpptools and I use it my CI, so it's likely to hit the 429 issue frequently.

**Comment by sean-mcmanus** [comment]
@puremourning We could potentially go back to our old practice of posting the vsix's on our GitHub Release's page. Do you know if those have the same issue or are you requesting the binaries be available via the fwlinks?

**Comment by puremourning** [comment]
GitHub releases work great! If you would be willing to add them as artefacts in the GitHub releases that would completely solve my issue!

**Comment by sean-mcmanus** [comment]
@puremourning Did you want that for pre-releases, which we stopped posting Release pages on GitHub, or the non-pre-release releases (i.e. 1.7.1, 1.8,4, 1.9.7)?

**Comment by puremourning** [comment]
I only grab release versions, so 1.9.7, etc. for me, there's no need to go earlier than 1.9.7 as I'm going to update to that now but if you can upload them for future 'release' versions that would be great.

**Comment by sean-mcmanus** [comment]
@puremourning Sure, we can start doing that. The 1.9.7 vsix's have been added: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.9.7

**Comment by puremourning** [comment]
@sean-mcmanus  thank you so much. You're an absolute hero.
