### ISSUE TITLE
Support /kernel flag for MSVC

### ISSUE THREAD

**Issue by thhous-msft** [microsoft/vscode-cpptools#8158]
Our team is working on undocking many of our kernel components from the Windows build. While working in the Windows build, many of our devs used VS Code. When switching to undocked and building with msbuild, intellisense does not work for kernel mode components. Passing /kernel to compilerArgs does not help, as it seems that the user mode header directories are always chosen, even with that flag set.

**Comment by sean-mcmanus** [comment]
Can you provide an example of what code is behaving incorrectly, i.e. how exactly is IntelliSense processing incorrect? Can you just add the appropriate kernel header directories to your includePath so they take precedence over the library ones? And/or use different includes via #ifdef _KERNEL_MODE?

We handle the /kernel flag via adding the define _KERNEL_MODE=1 and args --no_exceptions and --no_rtti.

https://docs.microsoft.com/en-us/cpp/build/reference/kernel-create-kernel-mode-binary?view=msvc-160

**Comment by thhous-msft** [comment]
With /kernel, I get 2 errors.

The first is the missing header directories. That is something that happens automatically inside the compiler from my understanding when /kernel is passed. That is easy enough to work around by adding the km include directory manually, but its something that should be automatic, since it is inside the compiler.

The 2nd is that every file gives the following error 
"command-line error: exception handling option can be used only when compiling C++"
Those extra arguments are not necessary for C, and shouldn't be passed.

**Comment by sean-mcmanus** [comment]
So the um include folder gets changed to km? That would be easy to change.

Yeah, we should be skipping the --no_exceptions and --no_rtti for C++ -- easy to fix.

**Comment by sean-mcmanus** [comment]
A potential workaround is to remove the /kernel arg and just define _KERNEL_MODE=1 (and add the km include path).

**Comment by sean-mcmanus** [comment]
How are you getting cl.exe to use the km folder? I'm see it not do that and requires /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\km" . Maybe you're using some extension that adds it? The docs at https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver also mention adding the path explicitly.

**Comment by sean-mcmanus** [comment]
The "exception handling option can be used only when compiling C++" is fixed for our next releases, but we need more info on the km or other include paths, because from what I can tell they need to be manually added and /kernel doesn't affect that.

**Comment by thhous-msft** [comment]
When I run a build from VS, it calls cl.exe with the following arguments

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\CL.exe /c /IC:\Users\thhous\Documents\GitHub\xdp\lib\rtl\inc /IC:\Users\thhous\Documents\GitHub\xdp\published\private /IC:\Users\thhous\Documents\GitHub\xdp\build\x64_Debug\obj\nmr\ /I"C:\Users\thhous\Documents\GitHub\xdp\submodules\ndis-driver-library\src\include" /IC:\Users\thhous\Documents\GitHub\xdp\published\external /IC:\Users\thhous\Documents\GitHub\xdp\build\x64_Debug\obj\nmr\ /Zi /nologo /W4 /WX /diagnostics:column /MP /Od /Oi /Ot /Oy- /GL /D CODE_ANALYSIS /D POOL_NX_OPTIN_AUTO=1 /D POOL_ZERO_DOWN_LEVEL_SUPPORT=1 /D FNDIS=1 /D _DEBUG /D _WIN64 /D _AMD64_ /D AMD64 /D DEPRECATE_DDK_FUNCTIONS=1 /D MSC_NOOPT /D _WIN32_WINNT=0x0A00 /D WINVER=0x0A00 /D WINNT=1 /D NTDDI_VERSION=0xA00000B /D DBG=1 /D KMDF_VERSION_MAJOR=1 /D KMDF_VERSION_MINOR=15 /GF /Gm- /Zp8 /GS /guard:cf /Gy /fp:precise /Qspectre /Zc:wchar_t- /Zc:forScope /Zc:inline /GR- /Fo"C:\Users\thhous\Documents\GitHub\xdp\build\x64_Debug\obj\nmr\\" /Fd"C:\Users\thhous\Documents\GitHub\xdp\build\x64_Debug\bin\xdpnmr.pdb" /external:W4 /Gz /wd4748 /wd4603 /wd4627 /wd4986 /wd4987 /FI"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\warning.h" /analyze /analyze:projectdirectory"C:\Users\thhous\Documents\GitHub\xdp\lib\nmr" /analyze:rulesetdirectory";C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Static Analysis Tools\\Rule Sets;" /analyze:ruleset"C:\Program Files (x86)\Windows Kits\10\CodeAnalysis\DriverMinimumRules.ruleset" /analyze:quiet /analyze:stacksize1024 /analyze:plugin"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\EspXEngine.dll" /analyze:plugin"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\WindowsPrefast.dll" /analyze:plugin"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\drivers.dll" /FC /errorReport:prompt /Gw /kernel /ZH:SHA_256 -d2jumptablerdata -d2epilogunwindrequirev2 client.c common.c provider.c
```

In there, there is no include path pointing to the km folder. But it works. It also doesn't look like any environment variables are getting set either.

**Comment by thhous-msft** [comment]
If you want a project to test, you can use 
https://github.com/microsoft/msquic

It does a user mode build, but it also builds in kernel mode. A kernel mode specific file is datapath_winkernel.c

**Comment by sean-mcmanus** [comment]
How do I get it to build in kernel mode? I only see DATAPATH_WINUSER.C getting built.

**Comment by thhous-msft** [comment]
The cmake build is for user mode. The msquic.kernel.sln in the root is the VS solution for kernel mode. We never figured out how to get kernel mode building in cmake (Although we wanted to).

**Comment by sean-mcmanus** [comment]
When I replace /kernel with /D_KERNEL_MODE=1, it still builds, so it doesn't appear that /kernel is causing the km folder to be used. Are you able to identify which args are causing cl.exe to use the km folder?

**Comment by thhous-msft** [comment]
I'm not sure. I just turned on verbose msbuild logging, and was just looking at what was passed to the compiler. Not sure exactly which arg is adding the headers. I was assuming /kernel was.

**Comment by sean-mcmanus** [comment]
I created https://github.com/microsoft/vscode-cpptools/issues/8164 to track the km include path issue.

**Comment by sean-mcmanus** [comment]
msbuild is setting the INCLUDE path environment variable: 1>Property reassignment: $(IncludePath)="C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\km\crt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\km;...

So there isn't a way for us to automatically do the same thing, short of creating some sort of msbuild configuration provider.

**Comment by JanGray** [comment]
I have no idea what you are talking about.

**Comment by sean-mcmanus** [comment]
The fix is available with https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
