### ISSUE TITLE
Symbol browser for C/C++ extension doesn't work on 32bit Linux system

### ISSUE THREAD

**Issue by GeezleCode** [microsoft/vscode-cpptools#816]
Symbol browser (cntrl+shift+o) for C/C++ extension doesn't work ("no symbol information ...").
Found on Ubuntustudio 16.04 32bit with code 1.13.0 32-bit.

**Comment by sean-mcmanus** [comment]
The language service features are not supported on 32-bit Linux (only 64-bit). See https://github.com/Microsoft/vscode-cpptools/issues/424 .

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
