### ISSUE TITLE
Windows SDK km/etc. include paths aren't added for cl.exe

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8164]
See https://github.com/microsoft/vscode-cpptools/issues/8158 .

It's unknown what exactly is triggering cl.exe to automatically include those paths, and it's unknown exactly what the full lists of paths are.

**Comment by sean-mcmanus** [comment]
msbuild is setting the INCLUDE path environment variable: 1>Property reassignment: $(IncludePath)="C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\km\crt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\km;...

**Comment by JanGray** [comment]
I have no idea what you are talking about.
