### ISSUE TITLE
${wokspaceFolder}/** not finding header file?

### ISSUE THREAD

**Issue by jalanh11640** [microsoft/vscode-cpptools#8170]
Bug type: Language Service

**Describe the bug**
- OS and Version: Linux Ubuntu 21.04
- VS Code Version:1.60.1
- C/C++ Extension Version: 1.6.0
- Other extensions you installed (and if the issue persists after disabling them): None
- If using SSH remote, specify OS of remote machine: N/A
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

My current workflow involves a centrally located code repository.  When I want to make a change, I check out a portion of the repository and make the changes locally. This will result in a tree that looks like this..

/local/data/code/code.cpp
/local/data/code/include/code.h

/home/jeff/code/code.cpp
/home/jeff/code/include/code.h

I'm using a single root project with the path being /home/jeff/code.

There's a function that takes no parameters that I want to change to taking 1 parameter (an int).  When I make the change in my local area, intellisense tells me the function doesn't take a parameter.  I have ${workspaceFolder}/** in my includePath so it should be able to find the changed file.  If I explicitly add the ${workspaceFolder}/include directory to the includePath, the error goes away.

**Code sample and logs**
/local/data/code/include/someModule.h:
int someFunction();

/home/jeff/code/include/someModule.h:
int someFunction(int x);

/home/jeff/code/someModule.cpp:
#include "someModule.h"

void myFunction(void)
{
    someFunction(1); // "too many arguments in function call" C/C++(140) [5, 18]
}

- Configurations in `c_cpp_properties.json`
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/local/data/code/include"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c99",
            "cppStandard": "c++03",
            "intelliSenseMode": "gcc-x86"
        }
    ],
    "version": 4
}

Is there a setting or something I'm missing?
Thanks,
Jeff

**Comment by michelleangela** [comment]
@jalanh11640 
When adding `#include someModule`, the path to "someModule.h" resolves to the one at `/local/data/code/include`. If you do `#include "include/someModule.h"` then the path will resolve to the include folder in from the `${workspaceFolder}`. Or `#include someModule` will resolve to `${workspaceFolder}/include` if `${workspaceFolder}/include` is explicitly added to includePath.

Could you verify if `#include "include/someModule.h"` resolves the issue without adding `${workspaceFolder}/include` to includePath?

**Comment by jalanh11640** [comment]
> @jalanh11640
> When adding `#include someModule`, the path to "someModule.h" resolves to the one at `/local/data/code/include`. If you do `#include "include/someModule.h"` then the path will resolve to the include folder in the `${workspaceFolder}`. Or `#include someModule` will resolve to `${workspaceFolder}/include` if `${workspaceFolder}/include` is explicitly added to includePath.
> 
> Could you verify if `#include "include/someModule.h"` resolves the issue without adding `${workspaceFolder}/include` to includePath?

Can can confirm that when I '#include "include/someModule.h"' the issue is resolved.  However, that doesn't resolve my issue as this error is a distilled down version I'm seeing in code at my work where I'm not at the liberty to add pathing elements to the include.

**Comment by michelleangela** [comment]
@jalanh11640 
The recursive includes `**` is order independent. If there are includes with the same name, then non-recursive includes will need to be added to includePath property to disambiguate which include path will get used.

So adding `${workspaceFolder}/include` is the correct configuration to resolve the squiggles if there is another include path with similar names.

You can also run the command `C/C++ Log Diagnostics` to see which include paths are used for the IntelliSense engine.
