### ISSUE TITLE
Variadic macro not expanded correctly

### ISSUE THREAD

**Issue by stephane-archer** [microsoft/vscode-cpptools#8178]
In the following code:
```cpp
#define Get2ndVariadicArg(a, b, ...) b

#define Assert(condition, ...) HandleAssert("msg", Get2ndVariadicArg(0, ##__VA_ARGS__, #condition))

#define HandleAssert(msg, format) MyAssert(msg, format)

int main()
{
    void * p = nullptr;
    auto mytest = Assert(p != nullptr);
}
```

visual studio code IntelliSense expend the `Assert` macro like this:
```cpp
auto mytest = MyAssert("msg", )
```
but `cl /P /C main.cpp` expend the macro the following
``` cpp
auto mytest = MyAssert("msg", "p != nullptr");
```

How can I have a consistent behavior with `cl`? Is it a bug in IntelliSense?

**Comment by Colengms** [comment]
Hi @stephane-archer .  Thanks for reporting this.  I'm able to repro.  The issue also repro's in VS, which shares the same IntelliSense implementation.  I've opened an issue internally against VS to address this.

**Comment by sean-mcmanus** [comment]
@Ma-XX-oN I believe so.

**Comment by sean-mcmanus** [comment]
This is tracked internally as 1409182, but there are multiple other __VA_ARGS__/macro issues that may be duplicates as well.

**Comment by sean-mcmanus** [comment]
@stephane-archer @Ma-XX-oN Fixed in 1.13.1: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.1

**Comment by stephane-archer** [comment]
@sean-mcmanus you are the best! :D

**Comment by Adrian-Hawryluk** [comment]
Glad to hear that this got fixed.  Well done!
