### ISSUE TITLE
Clicking the call stack results in "Unable to resolve non-existing file". The path-name appears twice in the file name that is attempted to be opened.

### ISSUE THREAD

**Issue by Justin-Randall** [microsoft/vscode-cpptools#8179]
Bug type: Debugger

Situation:

Cross compiling for Linux from Windows using llvm (Unreal Engine).
Debugging the resulting application with VSCode via a WSL2 session on Windows 10 (Ubuntu distro).

When debugging from WSL and gdb directly, of course the source file locations do not match. Adding a search directory to GDB solves it from with GDB.

When using cppdbg under VSCode, I can get the call-stack. Click on it and an error like this appears:

`Unable to open 'Internationalization.cpp': Unable to read file 'c:\github.com\EpicGames\UnrealEngine\Engine\Source\C:\github.com\EpicGames\UnrealEngine\Engine\Source\Runtime\Core\Private\Internationalization\Internationalization.cpp' (Error: Unable to resolve non-existing file 'c:\github.com\EpicGames\UnrealEngine\Engine\Source\C:\github.com\EpicGames\UnrealEngine\Engine\Source\Runtime\Core\Private\Internationalization\Internationalization.cpp').`

Note the double entry: first the base path, then the absolute path rather than the file name being appended to the base path when attempting to open the file. `c:\github.com\EpicGames\UnrealEngine\Engine\Source\` + `C:\github.com\EpicGames\UnrealEngine\Engine\Source\Runtime\Core\Private\Internationalization\Internationalization.cpp` when what one would expect is: `C:\github.com\EpicGames\UnrealEngine\Engine\Source\Runtime\Core\Private\Internationalization\Internationalization.cpp` which does exist (on the hosted filesystem). It also exists under `/mnt/c/github.com/EpicGames/UnrealEngine/Engine/Source/Runtime/Core/Private/Internationalization/Internationalization.cpp`. 

I attempted setting `"sourceFileMap": { "c:\\": "/mnt/c" },` in launch.json for the debugger configuration with no luck (also tried a reverse mapping).

When I click to follow the file link in the debug console output, it works just fine, right to the file and line number.

**Comment by WardenGnaw** [comment]
I've noticed the same issue of the base path being appended twice when compiling on windows for MSYS2, this comes from the debug information of the binary and not something the debug adapter appends. 

Are you using VS Code with the WSL Remote extension? If so, you will want to try 
```
"sourceFileMap": { "C:\github.com\EpicGames\UnrealEngine\Engine\Source\": "/mnt/c/github.com/EpicGames/UnrealEngine/Engine/Source/" }
```

Another thing to try is where the path is duplicated twice and force it into the linux context. 
```
"sourceFileMap": { "c:\github.com\EpicGames\UnrealEngine\Engine\Source\C:\github.com\EpicGames\UnrealEngine\Engine\Source\": "/mnt/c/github.com/EpicGames/UnrealEngine/Engine/Source/" }
```
