### ISSUE TITLE
C# intellisense not working

### ISSUE THREAD

**Issue by Smaran1832** [microsoft/vscode-cpptools#8184]
I am sorry I am new to vs code and Unity(for that matter git hub itself ).
So the issue is that my vscode IntelliSense does not give me the library functions or the suggestions that I see it is supposed to give.
I am currently doing an introduction to gaming course online and the vs code from the tutorial videos and mine differ greatly in functionality and I am having difficulties.

The way it is supposed to work is to give me basic suggestions such as transform and errors that happen to be in my program but even after multiple installations and reinstallation, it does not work. My Unity gives me the errors I need to sort.

The Tutorial :
<img width="622" alt="Screenshot 2021-09-24 000415" src="https://user-images.githubusercontent.com/81876237/134564330-d66dcfa6-5044-4075-806e-dfb82b9fd914.png">

Mine:
<img width="958" alt="Screenshot 2021-09-24 001404" src="https://user-images.githubusercontent.com/81876237/134565611-41092600-9595-471b-9e1e-78194aa9548b.png">
<img width="960" alt="Screenshot 2021-09-24 001433" src="https://user-images.githubusercontent.com/81876237/134565625-08511ce4-7b6f-44f0-b972-15899dd5f6e5.png">

**Comment by Colengms** [comment]
Hi @Smaran1832 .  This is the repo for the C/C++ extension for VS Code.  I think you're looking for [the repo for the C# extension for VS Code](https://github.com/OmniSharp/omnisharp-vscode).

Closing this issue, as it's not related to the C/C++ extension.
