### ISSUE TITLE
Support backticks in documentation comments

### ISSUE THREAD

**Issue by somerandomdev49** [microsoft/vscode-cpptools#8186]
Type: Feature Request

> I'm sorry if this is a duplicate, but I couldn't find a similar issue Or an alternative to this feature already exists

Currently, if you hover over a function with a documentation comment, backticks are ignored and displayed without formatting. For example when a comment contains example code, it is hard to read. Also Doxygen supports backticks.
```cpp
/**
 * This function does something...
 * Example usage: `fee->bar(foo(true));`
 */
int foo(bool yes);
```

This should be implemented as a separate option though because in lot of code quotes are written ``` ``like this''```
(Or you could ignore empty code blocks)

**Comment by Colengms** [comment]
Hi @somerandomdev49 .  If I understand correctly, you are requesting that documentation comments support the markdown format (which uses [backticks for code blocks](https://www.markdownguide.org/basic-syntax/#code)) .  We are currently tracking that with https://github.com/microsoft/vscode-cpptools/issues/6020 , so I will close this as a duplicate.
