### ISSUE TITLE
Help please in vs code Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by anzz03** [microsoft/vscode-cpptools#8188]
Bug type: Debugger

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by Colengms** [comment]
Hi @anzz03 .  Was that error message specifically associated with the C/C++ extension?  If so, that would seem to be a crash in the native component of the C/C++ extension.  Is there a specific file that causes this crash when you open it?  If so, can you reduce that file to a simple repro that you can share so we can investigate further?
