### ISSUE TITLE
could not pop up the parameter hints window when ctrl+shift+space insider the branckets

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-cpptools#819]
_From @wangjihu on June 10, 2017 1:14_

![image](https://user-images.githubusercontent.com/19356729/26998827-a08fe6fa-4dbc-11e7-8713-567b494eeab9.png)
like this cpp code ,when i type ctrl +shift+ space , i cannot see the parameter hints windows pops up .....
ps: 
os versiong :ubuntu 16.04 lts and c/c++ extensions has been installed.
thanks 

_Copied from original issue: Microsoft/vscode#28401_

**Comment by sean-mcmanus** [comment]
@wangjihu Is your OS 32-bit? Does it work when `(` is used?

**Comment by wangjihu** [comment]
@sean-mcmanus vscode 1.13 on 64bit ubuntu,
as i type  "(" followed by the function name ,the parameter hints windows pops up successfully,
however ,i type input something in other places of my cpp text ，then come back inside the “（）” https://user-images.githubusercontent.com/19356729/26998827-a08fe6fa-4dbc-11e7-8713-567b494eeab9.png and type crtl shift backspace , the preview window pop up failed!!!
ps : sorry about my chinese style english that is non-standard , and thanks for your time...

**Comment by sean-mcmanus** [comment]
Yeah, signatureHelp was implemented to require that initial Ctrl+Shift+Space be invoked immediately after the ( and for the cursor to not go beyond the final ). Eventually, we plan to re-implement signature help using the IntelliSense engine so the experience should become better.

**Comment by bobbrow** [comment]
This should be fixed with version 0.14.3
