### ISSUE TITLE
When I opened the folder, there were some CPP files Outline said "No symbols found in document"

### ISSUE THREAD

**Issue by xtchn** [microsoft/vscode-cpptools#8190]
Issue Type: <b>Bug</b>

When I open a large folder, there are some CPP files said "No symbols found in document". If I save this file and switch to another file and switch back to this file, it will display the symbols normally. I get this problem again when I restart my computer.

Extension version: 1.6.0
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.64GB free)|
|Process Argv|--crash-reporter-id 9da428d9-2519-481e-92c9-437f07ad7d31|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by xtchn** [comment]
loggingLevel: Debug
cpptools/didChangeCppProperties
Attempting to get defaults from compiler found on the machine: 'D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe'
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
Code browsing service initialized
Attempting to get defaults from compiler found on the machine: 'D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe'
No suitable compiler found. Please set the "compilerPath" in c_cpp_properties.json.
  Folder: D:/DESKTOP/SYNCHELPER/ will be indexed
Discovering files...
textDocument/didOpen: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp
  Processing folder (recursive): D:/DESKTOP/SYNCHELPER/
  Discovering files: 15 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing open files...
Populate include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Done parsing open files.
cpptools/getDocumentSymbols: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 2)
cpptools/getDocumentSymbols
cpptools/getCodeActions: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 3)
cpptools/getFoldingRanges: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 4)
textDocument/didSave: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp
  tag parsing file: D:\DESKTOP\SYNCHELPER\TIMESTAMPSYNCDATAUPDATER.CPP
Tag parsing encountered an error, but it may not matter. Let us know if symbols in the file can't be found: D:\DESKTOP\SYNCHELPER\TIMESTAMPSYNCDATAUPDATER.CPP
cpptools/fileChanged: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp
cpptools/getCodeActions: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 6)
idle loop: reparsing the active document
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp
textDocument/documentHighlight: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 7)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 8)
textDocument/hover: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 9)
using Tag Parser for quick info
textDocument/documentHighlight: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 10)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 11)
textDocument/hover: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 12)
using Tag Parser for quick info
cpptools/getCodeActions: file:///d%3A/Desktop/SyncHelper/SyncQueue.h (id: 13)
textDocument/didOpen: file:///d%3A/Desktop/SyncHelper/SyncQueue.h
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///d%3A/Desktop/SyncHelper/SyncQueue.h (id: 14)
cpptools/activeDocumentChange: file:///d%3A/Desktop/SyncHelper/SyncQueue.h
cpptools/getDocumentSymbols
Database safe to open
cpptools/getFoldingRanges: file:///d%3A/Desktop/SyncHelper/SyncQueue.h (id: 15)
cpptools/getCodeActions: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 16)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 17)
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols
textDocument/documentHighlight: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 18)
cpptools/activeDocumentChange: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp
cpptools/getFoldingRanges: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 19)
cpptools/getCodeActions: file:///d%3A/Desktop/SyncHelper/TimestampSyncDataUpdater.cpp (id: 20)
idle loop: reparsing the active document

**Comment by Colengms** [comment]
Hi @xtchn .  Would you be able to provide a minimum repro that we could investigate?

I noticed you are getting a `No suitable compiler found.` error, despite a reference to a compiler found on your system: `D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe`.  Could you run the `C/C++: Log Diagnostics` command with a source file open, and provide that output?  I'm curious how the extension is configured for you.
