### ISSUE TITLE
Support customized highlight color for the item in outline view (Follow Cursor option)

### ISSUE THREAD

**Issue by raymond-wh-leung** [microsoft/vscode-cpptools#8194]
Bug type: Language Service

**Describe the bug**
The cpp extension supports a "Follow Cursor" option in the outline view. For example, the selected item in the outline view will be based on the current function the cursor is in in the source *.cpp file. The selected / highlighted item in the outline view is a bit hard to see though. The default color is light grey (and in dark theme it is hard to see.) The bug is about allowing the selected / highlighted color item in the outline view to be customized.

- OS and Version:
Win10 

- VS Code Version:
1.60.2

- C/C++ Extension Version:
1.60

- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
1. Open a *.cpp file.
2. In the outline view, press the "..." button and select the "Follow cursor" option.
3. Change cursor location in *.cpp to different function.
4. The selected / highlighted item in outline view is in dark grey, which is a bit hard to see in dark mode.

**Expected behavior**
1. Allow the selected / highlighted color of the item in outline view to be customized, to make it easier to see in dark theme.

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @raymond-wh-leung .  The C/C++ extension provides data that enables that feature for C/C++ code, but the UI is owned by VS Code.  I'd suggest opening a feature request in the [VS Code repo](https://github.com/microsoft/vscode/issues).
