### ISSUE TITLE
.clang-format files aren't being used?

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8199]
This occurs for me when using the remote dev feature with WSL2.
 
![image](https://user-images.githubusercontent.com/1082293/134854415-11a50c89-d51e-4991-89af-f2991865ed15.png)

### 1. Does not use .clang-format file

My paths are of the form: `/home/sketch34/Dev/project/src/subdir/test.cpp`

I cannot make vscode use the `.clang-format` file located at `/home/sketch34/Dev/project` with any combination of options. I have tried setting the fallback style to `"none"`. I also tried moving the .clang-format file into the `/src` directory.

```
    "C_Cpp.clang_format_fallbackStyle": "",
    "C_Cpp.clang_format_style": "file",
```

### 2. Empty fallbackStyle disables clang_format_style

Additionally if the fallback style is empty `"C_Cpp.clang_format_fallbackStyle": ""` then the `C_Cpp.clang_format_style` has no effect.

E.g. This works and applies the LLVM style:
```
    "C_Cpp.clang_format_fallbackStyle": "WebKit",
    "C_Cpp.clang_format_style": "LLVM",
```

This has no effect and will not apply any formatting:
```
    "C_Cpp.clang_format_fallbackStyle": "",
    "C_Cpp.clang_format_style": "LLVM",
```

Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

_Originally posted by @sketch34 in https://github.com/microsoft/vscode-cpptools/issues/2124#issuecomment-927568913_

**Comment by sean-mcmanus** [comment]
@sketch34 What OS version of Debian are you using and what C/C++ extension version are you using?

**Comment by rgeorgiev583** [comment]
Can confirm that this is reproducible in a dev container environment as well.  I suppose that it has something to do with improper path resolution for the `.clang-format` file in the container.

**Comment by Colengms** [comment]
Hi @sketch34 .  I'm not able to easily reproduce the issue in Debian (11/bullseye) via WSL with a simple project.  Could you set `"C_Cpp.loggingLevel": "Debug"`, try to format a file, and provide the resulting output to the C/C++ output channel?  That should include the command line used to invoke clang-format.

**Comment by Colengms** [comment]
Hi @sketch34 .  I believe the issue with formatting failing when `C_Cpp.clang_format_fallbackStyle` is an empty string is by-design, as that is not a currently a valid value for that setting.  However, it's failing silently.  We should at least report the issue to the user.  An issue tracking that is here: https://github.com/microsoft/vscode-cpptools/issues/8944

For the remaining issue of the `.clang-format` file not being used, I don't yet have a repro for this that I can investigate.  Can you provide a self-contained repro, in the form of a githug repo or zip file?

**Comment by Colengms** [comment]
It's possible this issue may have been caused by: https://github.com/microsoft/vscode-cpptools/issues/8900
