### ISSUE TITLE
c symbol cant be resolved in header file that is customer defined file extensions

### ISSUE THREAD

**Issue by mdzyduan** [microsoft/vscode-cpptools#82]
for example： "files.associations": {"*.inc":"c"}

then ：#include "*.inc" in a c source code,

vscode dont know *.inc is a header file,and the symbol in *.inc cant be resolved.

**Comment by jgoshi** [comment]
This will be fixed in the next release, version 0.8.0. Anything you explicitly include should now end up being parsed for symbols.
