### ISSUE TITLE
Minimap disappeard when ctrl+click a symbol

### ISSUE THREAD

**Issue by Antman2023** [microsoft/vscode-cpptools#820]
```
#ifdef A
#define X 1
#else
#define X 2
#endif

int x = X;
```

In this case, ctrl+click the symbol 'X', then click anywhere in editor window, the minimap will disappeared.

**Comment by sean-mcmanus** [comment]
This has been fixed in the latest Insider's build (see https://github.com/Microsoft/vscode/issues/28478 ).
