### ISSUE TITLE
Error using c/c++ extension : The language server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8207]
I am getting this error while running the c++ extension in vscode. 
The language server crashed 5 times in the last 3 minutes.

The output log says:
[Error - 2:06:42 pm] Connection to server got closed. Server will not be restarted.
/home/ratnesh/.vscode/extensions/ms-vscode.cpptools-1.7.0-insiders/bin/cpptools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/ratnesh/.vscode/extensions/ms-vscode.cpptools-1.7.0-insiders/bin/cpptools)

**Comment by FrostMonarch95** [comment]
same problem here

**Comment by qqshka** [comment]
same

**Comment by michelleangela** [comment]
1.7.0-insiders2 is now available with a fix for this issue. https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.0-insiders2
