### ISSUE TITLE
includePath doesn't resolve include errors

### ISSUE THREAD

**Issue by bryanfok** [microsoft/vscode-cpptools#821]
Ok so I installed a new vscode insiders build. And by default it does give me all the error highlights.

First of all, I try to resolve all the include errors. for example, `#include <platform/base/logging/logger.h>`, and my workspace folders structure is like this:

platform
----|_ cpp
--------|_ platform
-------------|_ base
------------------|_ logging
-----------------------|_ logger.cc
-----------------------|_ logger.h

so I add this include path to the `includePath` :
```
       {
            "name": "Linux",
            "includePath": [
                "${workspaceRoot}",
                "${workspaceRoot}/platform/cpp",
                "/usr/include/c++/6.3.1",
                "/usr/local/include",
                "/usr/include"
            ],
            "defines": [],
            "browse": {
                "path": [
                    "/usr/include/c++/6.3.1",
                    "/usr/local/include",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
```

However the platform related include errors are still showing. But if i do a Ctrl + click on the include definition, it is taking me to that header file..

**Comment by bryanfok** [comment]
By the way, when I hover over the include statement, I dont see the "add include to setting" statement either.

**Comment by bryanfok** [comment]
I read https://github.com/Microsoft/vscode-cpptools/issues/786 and somewhat similiar to my situation. But when it say the includePath is non-recusive, what does it mean. By including this `${workspaceRoot}/platform/cpp`, will it able to find `#include <platform/base/logging/logger.h>` ?

**Comment by bryanfok** [comment]
After restart, all the highlight is gone, and left me one message 

> There are too many errors for the IntelliSense engine to function properly, some of which may not be visible in the editor.

Which make sense, however is there anyway to enable the highlighting again?

**Comment by bobbrow** [comment]
Your includePath may be missing some entries.  What do you see in the terminal when you run `gcc -v -E -x c++ - < /dev/null`?  Your includePath should contain the paths listed by your compiler.  You can copy them in or delete and regenerate your c_cpp_properties.json file to correct it.

**Comment by bryanfok** [comment]
By follow your procedure it works, I will do more test with other in-house c++ modules within the workspace, then I will close the issue. Thanks again.
