### ISSUE TITLE
C/C++: Unable to resolve configuration with compilerPath "...\cc1.exe"

### ISSUE THREAD

**Issue by cmcqueen** [microsoft/vscode-cpptools#8210]
Bug type: General

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.60.2
- C/C++ Extension Version: 1.6.0

    [01/10/2021, 12:05:09 pm] Unable to resolve configuration with compilerPath "C:\Program Files\Rowley Associates Limited\CrossWorks for ARM 4.8\gcc\arm-none-eabi\bin\cc1.exe".  Using "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\cl.exe" instead.

The issue seems to be that the `cc1.exe` doesn't accept all the command-line parameters that `gcc.exe` does. But, I'm using CrossWorks from Rowley Associates (for cross-compiling for an embedded ARM platform), and that provides `cc1.exe` but no `gcc.exe`.

But, I also do have Microsoft Visual Studio command-line compiler installed. So VS Code finds that, and uses that.

Therefore, VS Code decides not to analyse the code in GCC mode, and marks all the GCC `__attribute__()` usage in our code as an error.

**To Reproduce**

1. Configure C/C++ extension `compilerPath` to point to a valid `cc1.exe` from a GCC tool installation.
2. Have Visual Studio compiler installed too.
3. Observe an error message something like:
    [01/10/2021, 12:05:09 pm] Unable to resolve configuration with compilerPath "C:\Program Files\Rowley Associates Limited\CrossWorks for ARM 4.8\gcc\arm-none-eabi\bin\cc1.exe".  Using "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\cl.exe" instead.
4. Observe that VS Code marks all usage of GCC `__attribute__()` as an error in the C code of the project.

**Comment by cmcqueen** [comment]
> Are you compiling sources by invoking `cc1` directly, or is there some instance of `gcc` that is invoking the custom `cc1`?

I'm using Rowley CrossWorks, an IDE for cross-compiling embedded firmware for eg ARM processors. It appears that CrossWorks is calling `cc1` followed by `as` directly. CrossWorks doesn't provide a `gcc` executable amongst its installed tools (which is a little surprising).

>  I would suggest specifying `""` as the `compilerPath`...

Thanks, that's helpful to know as a short-term solution.

I will contact Rowley, and let them know of this situation, and ask if they could also provide a `gcc` executable in their bundled tools.

Should I leave this issue open, or close it for now?

**Comment by Colengms** [comment]
Hi @cmcqueen .  I think we can close this, for now.  If your communication with Rowley leads to a potential fix that would require changes in the C/C++ extension, feel free to open a new issue.
