### ISSUE TITLE
Cannot auto complete namespace

### ISSUE THREAD

**Issue by eterlan** [microsoft/vscode-cpptools#8216]
Bug type: Language Service

**Describe the bug**
- OS and Version: Win10
- VS Code Version: 1.60
- C/C++ Extension Version: 1.60
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Open a new C++ file, and then type "cout".

**Expected behavior**

   it would automatically suggest std::cout. Now it can't do that like Clion does.

I don't know if that is a bug, sry for that.

**Comment by sean-mcmanus** [comment]
Are you saying "cout" gives "std::cout" in the suggestion list? Are you able to provide a screenshot?
