### ISSUE TITLE
Add variables to watch panel using drag and drop

### ISSUE THREAD

**Issue by yh-sb** [microsoft/vscode-cpptools#8220]
**In debug mode:**
Ability to add items in WATCH by drag and dropping them from VARIABLES section.

Would be nice if this feature will work with separate members of class (including its submembers).

**Comment by WardenGnaw** [comment]
Is this possible with other languages in VS Code?

If not, you will want to open this issue at [VS Code issues](https://github.com/microsoft/vscode/issues)
