### ISSUE TITLE
Merge `C_Cpp.default.defines` into base config, or add a setting for defines to merge into base config

### ISSUE THREAD

**Issue by AndersHogqvist** [microsoft/vscode-cpptools#8229]
Bug type: Language Service

**Describe the bug**
- OS and Version: CentOS 7.5
- VS Code Version: 1.60.1
- C/C++ Extension Version: 1.6.0
- Other extensions you installed (and if the issue persists after disabling them): ANSI Colors (yes), C++ Class Creator (yes), C++ Helper (yes), CMake (yes), CodeBucket (yes), Doxygen Documentation Generator (yes), File Templates (yes), GitLens (yes), Jira Plugin (yes), Open in Application (yes), PureEclipse (yes), Python (yes), XML Tools (yes)
- If using SSH remote, specify OS of remote machine: N/A
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
1. Make sure that the array at "defines" in n c_cpp_properties.json is empty
2. Open or create a source code file and add the following:
```
#ifdef VARIABLE
void do_something() {

}
#endif
```
3. Close the file and open it again. Verify that the function is "greyed out". 
4. Close the file
5. Open settings and add the following to either settings.json, <workspace name>.code-workspace or both:
`"C_Cpp.default.defines": ["VARIABLE"],`
6. Open the file

**Expected behavior**
The function between #ifdef VARIABLE and #endif shouldn't be "greyed out".

**Code sample and logs**

- Code sample
N/A
- Configurations in `c_cpp_properties.json`
```
{
  "configurations": [
    {
      "name": "Linux",
      "includePath": [
        "${default}"
      ],
      "defines": [],
      "compilerPath": "/path/to/gcc",
      "intelliSenseMode": "linux-gcc-x64"
    }
  ],
  "version": 4
}
```
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
N/A
- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
N/A

**Screenshots**

N/A

**Additional context**
It works only when I add "VARIABLE" to "defines" in c_cpp_properties.json, but according to the documentation (https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp) C_Cpp.default.defines in either user or workspace settings should override c_cpp_properties.json

**Comment by Colengms** [comment]
Hi @AndersHogqvist .  It is currently 'by-design' that the default value is not used if the `defines` field is provided in `c_cpp_properties.json`.  In the configuration you posted, the following would indicate that no defines should be provided by the configuration:

```
      "defines": [],
```

Would you like to convert this issue into a Feature Request, that default defines always be merged into the active configuration instead?

**Comment by AndersHogqvist** [comment]
Ah I see! Well yes then I would like to convert this to a feature request. I recon I'm not the only one having multiple workspaces that I switch between. I have different macros as the provided example in each workspace so I believe it would be logic with the option to specify defines in workspace settings alone.
