### ISSUE TITLE
2bugs

### ISSUE THREAD

**Issue by ZZYSonny** [microsoft/vscode-cpptools#823]
for example I got this from problem
''i' was not declared in this scope (8,9)
and I want to let the cursor move to it, so I left click it
then vscode tell me that it can't open it
If my file is located at D:\code\1.cpp
it says it can't open D:\code\D:\code\1.cpp

also when I want to see the part of code in stl (for example I want to see some usage of queue from the stl, not from the code itself), I use ctrl+left click
it will open the file with vscode, and show a small window of it.
I think I just need one of them, so it will be better if we can first show the window then choose to open with one page of vscode

**Comment by bobbrow** [comment]
The second issue is just how VS Code behaves when we find multiple matches.  When goto definition is updated to be semantic-aware this should be less of a problem.  We're tracking that with #255.

I don't fully understand what you are experiencing for your first issue. Can you provide a bit more detail?  Left-clicking in the editor shouldn't open any files.  It just moves the blinking cursor.

**Comment by ZZYSonny** [comment]
Yes, it should just move the blinking cursor, but it didn't move and show the message that it can't open that file.
Does that have something to do with my other plugins (native debug)

**Comment by ZZYSonny** [comment]
here is the photo after clicking the problem
![1](https://user-images.githubusercontent.com/28442838/27128028-a3d49c54-512f-11e7-89e8-0bfac668b75a.png)

**Comment by bobbrow** [comment]
Does the message go away when you disable the other plugins?  That doesn't look like any of the messages that we would send.

**Comment by ZZYSonny** [comment]
Oh, I have found a mistake in my tasks.json .
I used "fileLocation": ["relative", "${workspaceRoot}"],
when I changed to "fileLocation":"absolute",
It became ok.

I will close this problem.
