### ISSUE TITLE
Erroneous message  'There's no formatter for c file installed'.

### ISSUE THREAD

**Issue by zandr14** [microsoft/vscode-cpptools#8230]
Issue Type: <b>Bug</b>

Have enabled extension C/C++  v1.6.0.  Have a simple Hello World 'c' file. Try to format the doc by Shift-Alt-F, a message box occurs with 'There's no formatter for c file installed'. How is it to make  C/C++  extension to format the doc? Tried to tune settings - without any luck.

The doc says: "The C/C++ extension for Visual Studio Code supports source code formatting using clang-format which is included with the extension."

Is it really included?

Extension version: 1.6.0
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (20.19GB free)|
|Process Argv|--crash-reporter-id cfc29846-d50f-46f7-a063-48ac2cc99e58|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis300:30374797
vsaa593:30376534

```

</details>

**Comment by zandr14** [comment]
Found where the problem is: the text (not the file) was created from the ground up in memory and not saved to disk yet. After I saved it, all went ok. I think the message 'There's no formatter for c file installed' should be something else, not confusing.

**Comment by Colengms** [comment]
Hi @zandr14 .  The error message you are seeing is coming from VS Code, not the C/C++ extension.  When using an unsaved file, the context menu does not contain the option to format (which is normally present), so it seems inconsistent that it accepted the keyboard shortcut.  I can repro this while the C/C++ extension has indeed registered as a formatting provider.  I can't think of any reason we would not be able to format the unsaved file properly.  This looks like a VS Code issue to me.  I'd suggest opening this issue [in the VS Code repo](https://github.com/microsoft/vscode/issues).

**Comment by zandr14** [comment]
Ok. As you told.
