### ISSUE TITLE
incorrect sorting of includes from compile_commands.json

### ISSUE THREAD

**Issue by vakokako** [microsoft/vscode-cpptools#8231]
I attach the archive with small toy project showcasing the problem.
[test_compile_commands.zip](https://github.com/microsoft/vscode-cpptools/files/7285570/test_compile_commands.zip)

1. When using `compile_commands.json`, cpptools incorrectly prioritizes includes by sorting alphabetically, instead of using the order of includes in `command`. In `compile_commands_bug_order.json`, the `a_include_wrong` folder will be prioritized, even though it was included after `b_include_correct` folder.
2. Also, when one of the command for one of the `.cc` files will include the directory that another command doesn't include, it will still be used for another `.cc` file. In `compile_commands_bug_no_include.json`, the command for `OtherSource.cc` includes `a_include_wrong`, but for `ImageBase.cc`, this folder is not included, when indexing, the `a_include_wrong` is still used for `ImageBase.cc`.

For testing:
1. in all `compile_commands*` replace `/home/mvankovych/Tmp/test_compile_commands` with folder where you extracted the archive.
2. copy `compile_commands_bug*` to `compile_commands.json` to showcase each bug.
3. reload window to restart IntelliSense
4. use `Alt+O` or `Go To Definition` from `ImageBase.cc`, which will take you to `a_include_wrong/ImageBase.hh` instead of `b_include_correct/ImageBase.hh`.

**Comment by Colengms** [comment]
Hi @vakokako .  When using your `compile_commands_bug_order.json`, I believe I am getting the correct behavior for `Go To Definition`.  Also, when I run `C/C++: Log Diagnostics` with the source file open, I see that IntelliSense has processed the include paths in the correct order.  The algorithm used to determine the corresponding file to open when using `Switch Header/Source` (Alt-O) is not based on IntelliSense - rather it is based on the filename, and searches the directory structure for the nearest file with a similar filename (other than extension).

When using `compile_commands_bug_no_include.json`, and doing a `Go To Definition` on the header in `ImageBase.cc`, I see that it correctly opens `b_include_correct/ImageBase.hh`.

Are the issues you are seeing isolated to the `Switch Header/Source` (Alt-O) feature?  Would you like to use this issue to track improving `Switch Header/Source` search algorithm to consider the order of include paths?  Are you seeing this issue with any other features?

**Comment by Colengms** [comment]
This could be part of https://github.com/microsoft/vscode-cpptools/issues/2635 .  Closing as a dupe.
