### ISSUE TITLE
Organize extension settings by subheading

### ISSUE THREAD

**Issue by jureid** [microsoft/vscode-cpptools#8237]
Type: Feature Request

VS Code now supports h2 sections in the Settings UI: https://github.com/microsoft/vscode/issues/126089 

![image](https://user-images.githubusercontent.com/44306969/136238285-8981136e-af7d-4a57-bb08-c9566f636619.png)

The subheadings make extension settings easier to read and navigate. It would be great to organize the C++ extension's many settings into subgroups!

**Comment by daviddossett** [comment]
[Here's the code](https://github.com/microsoft/vscode/blob/main/extensions/css-language-features/package.json#L37) for the CSS languages features sections pictured above 🙏
