### ISSUE TITLE
[Windows] include files not found if case sensitive

### ISSUE THREAD

**Issue by ECquadrat** [microsoft/vscode-cpptools#8239]
Bug type: Language Service

Hey guys,
there is some weird behavior when using case sensitive file names in #include statements.

I created an empty .c file and added the following code:
#include <string.h>
#include "vstdlib.h"
#include "D:/svn/ProjectXx/Appl/CoreMsr/BSW/StbM/StbM.h"
#include "StbM.h"
#include <stdio.h>

1) Now Intellisense shows a wiggled line below "D:/svn/ProjectXx/Appl/CoreMsr/BSW/StbM/StbM.h" but this file exists at this place in the file system. The line "StbM.h" below is correctly found (without wiggled line) and it's possible to open the file with "go to definition".

2) Now I comment out the include line with "D:/svn/ProjectXx/Appl/CoreMsr/BSW/StbM/StbM.h". As result there is a wiggled line below "StbM.h" now, and it shows the error "file not found in include path".

3) If I rename the "StbM.h" file to "stbm_test.h" and change the include statement, the file is found with full path name as well with file name only.

4) During typing the code, the code complete feature has no file name suggestion when starting typing with "D:/" part of filename. Nevertheless the full path include is afterwards correctly acknowledged and used by Intellisense even the code complete feature doesn't work. The other way round, when typing "Stb" without full path, there are correct suggestions with the filename "StbM.h" in the code completion but Intellisense fails when parsing afterwards and a wiggled line is drawn below.

It seems for me like in topic (1) the file has been correctly found with full pathname and parsed, but Intellisense shows a wrong wiggled line. In the next line with the include with file-name only, Intellisense recognizes this file as already available in it's database and accepts that line even the file may NOT really be found in filesystem. Maybe because of that the in test topic (2) a wiggled line is drawn below.

Is there any hint for a workaround to this issue? Please ask for more information if required.

Thanks a lot in advance,
Marc

My configuration:
OS: Windows 10 1909
NTFS file system in "D:\"
Visual Studio Code 1.60.2
VS Code 1.6.0
All other extensions disabled
Single Workspace project (right click on folder "Appl" and selected "open with Code")
Intellisense Include-path: "${workspaceFolder}/**"
Intellisense Exclude-path is empty

**Comment by Colengms** [comment]
I believe this has been addressed (to an extent) by the addition of the `C_Cpp.caseSensitiveFileSupport` setting, which can be used to switch the C/C++ Extension into case-sensitive mode on Windows.  (This is currently a single sensitive vs insensitive switch and does not currently support use of mixed case sensitive and case insensitive file systems.)
