### ISSUE TITLE
gcc problem matcher should understand gmake directory enter/exit messages

### ISSUE THREAD

**Issue by kmbgit** [microsoft/vscode-cpptools#8240]
Type: Feature Request

gcc is often called by gmake through the Makefile system, and complex projects may have hundreds of Makefiles in different directories, with one Makefile calling gmake to perform an action in a different directory, either using the `-C` flag or with a explicit `cd` command before the call to `$(MAKE)`.  The problem is that `gcc` reports the name of the file it was told to compile, so if that name is relative (e.g. `gcc c.c`) then error messages are relative to the directory `gmake` happened to be in when it ran the command, making it difficult for the problemMatcher to know what file is being referred to.

Fortunately `gmake` has a solution to the problem: it outputs `Entering directory '/path/to/directory'` when it enters a directory and `Leaving directory '/path/to/directory'` when it leaves.  Each line also reports the nesting level of calls to `gmake`.  Venerable editors such as GNU Emacs grok these lines to know what directory each command was run in, and use the information to calculate the correct absolute file name for each warning message that contains a relative path.

The gcc problem matcher should do the same - keep track of the Entering/Leaving messages to know which directory relative pathnames are relative to.  Simple!

Note that this was discussed before in https://github.com/microsoft/vscode-cpptools/issues/2266 but the proposed solution didn't take into account the face that different commands can be run in different directories.  C'mon guys, Emacs has been doing this properly for YEARS!

**Comment by Colengms** [comment]
Hi @kmbgit .  Thanks for opening this Feature Request.
