### ISSUE TITLE
Bug of 1.70 insider 'Go To Type Definition' ???

### ISSUE THREAD

**Issue by LoserJL** [microsoft/vscode-cpptools#8245]
1.70 insider added'Go To Type Definition', but the shortcut key can't jump to the defined place normally. It has been jumped to the referenced place. You must click on'Go To Type Difinition' to jump to the defined place. I think There is something wrong with this logic,
Please fix it，thanks

**Comment by LoserJL** [comment]
Thanks, after reset, I still have this problem

**Comment by wgqimut** [comment]
same problem on C project

**Comment by LoserJL** [comment]
Hi, @sean-mcmanus , I want to know if this is a bug, I still use it downgraded to 1.6.0, upgrade to 1.7.0 will have this problem, Thanks
