### ISSUE TITLE
-enable-pretty-printing option does't work for std::list  on Windows but std::map does

### ISSUE THREAD

**Issue by aengusjiang** [microsoft/vscode-cpptools#825]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 
cpptools|ms-vscode|0.11.4|

Description：
when I using gdb debug c++ program  on Window10 with vscode, I find that-enable-pretty-printing option does't work for std::list  on Windows but std::map does.

it probably a bug.

**Comment by pieandcakes** [comment]
@AbelaroJiang The pretty-printers are provided by gdb itself and not our extension.  I would verify that the version of gdb you are running has a pretty printer for that type. 

Here is a reference for the gdb command:
https://sourceware.org/gdb/onlinedocs/gdb/Pretty_002dPrinter-Commands.html#Pretty_002dPrinter-Commands

**Comment by aengusjiang** [comment]
Ok, I will take some time to have a look.
