### ISSUE TITLE
Issue #6290 went 404

### ISSUE THREAD

**Issue by mitsukuri** [microsoft/vscode-cpptools#8256]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/8253

<div type='discussions-op-text'>

<sup>Originally posted by **mitsukuri** October 11, 2021</sup>
There was an issue **#6290** which tracked the status of c++20 module support. Trying to check that today, I'm getting error 404.

What happened to the issue and how do we track the progress on that?</div>

**Comment by Colengms** [comment]
Hi @mitsukuri .  This looks like it may be a GitHub service outage of some sort.  We don't intentionally remove issues.  If I can find any additional information, I will respond on this issue.
