### ISSUE TITLE
browse.path doesn't work if compile_commands.json is provided

### ISSUE THREAD

**Issue by Kztpia** [microsoft/vscode-cpptools#8258]
Bug type: Language Service

**Describe the bug**
- OS and Version: windows 7
- VS Code Version:1.55.2
- C/C++ Extension Version:1.5.1
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: ubuntu 14.04
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

browse.path doesn't work if compile_commands.json is provided

**Steps to reproduce**

1.download AOSP
2.generate compile_commands by soong(follow instruction in  AOSP/build/build/soong/docs/compdb.md )
3.open anyfolder with vscode  in aosp, set browse.path to "${workspaceFolder}"
4.set cpptools debug level to "debug"
5.reset intellisense database
         cpptools log shows that  parsing folder are toolchain includes and workspaceFolder, works find
6.set cpptools compils_commands as compial_commands.json generated in step 2
6.reset intellisense databse
         cpptools log shows that  parsing folder are toolchain includes and whole aosp folder
         seems browse.path doesn't work anymore
   
parsing is a very performance hungry behavior, especially in large project.
It would be nice if the user can control what to parse, what not to parse

**Comment by bobbrow** [comment]
Can you try using the `"C_Cpp.files.exclude"` setting to set the paths to folders you don't want us to index?

**Comment by Kztpia** [comment]
> Can you try using the `"C_Cpp.files.exclude"` setting to set the paths to folders you don't want us to index?

"C_Cpp.files.exclude" works, but I have to exclude "AOSP/non-X" and "AOSP/X/non-Y" when working on AOSP/X/Y.
I exclude whole AOSP to disable cross reference now.

Now autocomplete works fine. Folders I am working got less than 1000 thousand file. "ctrl + shift + F" is usable in this scope.
