### ISSUE TITLE
Cannot create multiline string

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8269]
Bug type: Language Service

**Describe the bug**
- OS and Version: macOS Big Sur 11.6
- VS Code Version: 1.61.0
- C/C++ Extension Version: 1.6.0
- Other extensions you installed (and if the issue persists after disabling them): Yes issue still persists
- If using SSH remote, specify OS of remote machine: No SSH

So when I try to use C++ 11 multiline string feature like so,
```
  const char *vertexShaderSource = R"(
    aaa
  )";
```

I get this error,
```
identifier "R" is undefined C/C++(20)
missing closing quote C/C++(8)
```

**Steps to reproduce**
1. Add the following code,
```
#include <stdio.h>

int main()
{
  const char *vertexShaderSource = R"(
    aaa
  )";

  return 0;
}
```
2. See the error: `identifier "R" is undefined C/C++(20)`

**Code sample and logs**

- Code sample: See above

- Configurations in `c_cpp_properties.json`: No custom configs.

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 10/13/2021, 1:59:42 PM
Version: 1.6.0
Current Configuration:
{
"name": "Mac",
"includePath": [
"${workspaceFolder}/**"
],
"defines": [],
"macFrameworkPath": [
"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
],
"compilerPath": "/usr/bin/clang",
"cStandard": "c17",
"cppStandard": "c++98",
"intelliSenseMode": "macos-clang-x64",
"compilerPathIsExplicit": true,
"cStandardIsExplicit": true,
"cppStandardIsExplicit": true,
"intelliSenseModeIsExplicit": true,
"compilerArgs": [],
"browse": {
"path": [
"${workspaceFolder}/**"
],
"limitSymbolsToIncludedHeaders": true
}
}
Translation Unit Mappings:
[ /Users/axel/tests/c++/main.c ]:
/Users/axel/tests/c++/main.c
Translation Unit Configurations:
[ /Users/axel/tests/c++/main.c ]:
Process ID: 6251
Memory Usage: 39 MB
Compiler Path: /usr/bin/clang
Includes:
/usr/local/include
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
Frameworks:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
Standard Version: c17
IntelliSense Mode: macos-clang-x64
Other Flags:
--clang
--clang_version=110000
Total Memory Usage: 39 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 12181
Number of files parsed: 889
```

**Screenshots**

<img width="775" alt="Screen Shot 2021-10-13 at 2 01 08 PM" src="https://user-images.githubusercontent.com/91611516/137094486-22c5c4b3-276b-48f1-bc95-1e9543a8d995.png">

**Comment by Colengms** [comment]
Hi @axelthat2 .  It looks like you are trying to use a feature of C++20, but are configured for C++98.  Also, it looks like you are using a ".c" file, which is associated with the C language by default, not C++.

If you use a ".cpp" file, and use one of the `C/C++: Edit Configurations` commands to change `cppStandard` to `c++20`, I believe that would avoid the squiggle.

**Comment by axelthat2** [comment]
Thank you! I wasn’t aware the R syntax is not supported in C.
