### ISSUE TITLE
Autocomplete and go to definition regression

### ISSUE THREAD

**Issue by eangeloff** [microsoft/vscode-cpptools#8273]
Bug type: Language Service

Hello,

In the latest version of C/C++ (v1.7.0) I observe regression regarding the autocomplete and
go to definition. Both are super slow. It takes a very long time to go to definition of function for example.
Autocomplete is "loading" for very long time too. Both functions are not usable anymore.
If I disable the extension at least the autocomplete is working.
With version (v1.6.0) it is working just fine. 

I can observe the same behavior on Windows and Linux. Here is information about the Linux version:
![Screenshot from 2021-10-14 00-31-49](https://user-images.githubusercontent.com/5672135/137215995-633a85bb-4d53-4250-b4de-5a1a564c020c.png)

**Comment by constroy** [comment]
also on windows10

```
Version: 1.61.0 (user setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363
```

headers included cannot be found.
`find all references` takes no effect.

**Comment by eugeneko** [comment]
I have somewhat similar problem.
When I open my repo, both IntelliSense and the rest of CppTools commands stuck.
Files are not parsed (or parsed so long I didn't have patience to wait), cannot Ctrl+O to matching header/source, cannot even Reset Database.
Rolling back to 1.6.1 helps.

```
Version: 1.61.1 (system setup)
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:19:42.089Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by peterwaller-arm** [comment]
This manifests on https://github.com/llvm/llvm-project with a debug build for me. Versions above 1.5 do not show `tag parsing file: ` in the log at all, and subsequently are extremely slow for any kind of navigation or completion. On 1.5 it populates the index and is instant. I didn't see a smoking gun in the log as to what is wrong other than the absence of the tag parser log lines.
