### ISSUE TITLE
debug.onTaskError setting is ignored

### ISSUE THREAD

**Issue by JamEck** [microsoft/vscode-cpptools#8275]
Bug type: Debugger

**Describe the bug**
- Windows Version: Windows 10 Home 19043.1237 
- VS Code Version: Version: 1.61.0
- C/C++ Extension Version: 1.7.0

- A clear and concise description of what the bug is.

I have vscode's debug.onTaskError set to "prompt" for both the user and workspace profiles.

My launch.json has a preLaunchTask that builds the executable using msbuild.

Before updating to the latest 1.7.0, debug sessions would prompt me if any msbuild errors were encountered before launching the executable.

After updating to the latest 1.7.0, debug sessions will continue regardless of debug.onTaskError setting.

Reverting to the previous version, 1.6.0, solves the issue.

Relevant errors from msbuild still show in the 'PROBLEMS' window, in any version.
The debug session is behaving as though debug.onTaskError = 'debugAnyway'.

**launch.json:**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug64",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "<path_to_exe>",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "console": "externalTerminal",
            "preLaunchTask": "MSBuild"
        }
    ]
}
```

The prelaunch task runs msbuild on a Visual Studio solution file

**Comment by sean-mcmanus** [comment]
@WardenGnaw should be able to respond to this next week.
