### ISSUE TITLE
[Regression] 1.7.0 no longer automatically using custom configuration provider

### ISSUE THREAD

**Issue by DDevine** [microsoft/vscode-cpptools#8276]
Bug type: Language Service

**Describe the bug**
- OS and Version:  Windows 10 pro 19043.1288
- VS Code Version: 1.61.0
- C/C++ Extension Version: 1.7.0
- Other extensions you installed (and if the issue persists after disabling them): `ms-vscode.cmake_tools` 1.7.3

The the includes don't seem to be fed into intellisense, so my #ifdefs grey-out blocks of code that should be shown, and ctrl-click to navigate does not work. There are errors indicating that my includes could not be found, however the code builds and runs fine so my actual cmake configuration is not to blame.

When I downgrade `ms-vscode.cpptools` down to the previous version (1.6.0) the issues are fixed. 

I specifically use `ms-vscode.cmake_tools` 1.7.3 due to this bug: https://github.com/microsoft/vscode-cmake-tools/issues/2120

**Screenshots**
Good (1.6.0) - the #if works as expected, and I can ctrl+click on things.
![image](https://user-images.githubusercontent.com/913394/137265667-bf2c04d4-2dfd-4b7f-8aa6-f0e4ccfae1b5.png)

Bad (1.7.0) - cannot control click on things, eg. cannot ctrl+click to navigate to bsp.h.
![image](https://user-images.githubusercontent.com/913394/137265964-59b72d8d-4f3a-4c34-bf30-06ba9382c9d5.png)

**Comment by DDevine** [comment]
Hi sorry I have been very busy.

Log Diagnostics: https://gist.github.com/DDevine/7614495a2fb41ba8a5b52b9a14aa5d4d
Log for file on a fresh build: https://gist.github.com/DDevine/2b98b985fb6f85e8d883d9a45f1b00d9

**Comment by Colengms** [comment]
Hi @DDevine .  This should also now be fixed in 1.7.1.
