### ISSUE TITLE
TypeError: Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by JaxxArmstrong** [microsoft/vscode-cpptools#8280]
Got this error (see title) upgrading the extension as per usual. First time I ever had any issues whatsoever.

Upgraded VS Code today to the latest version (see below for details) and tried again. Same issue.

Version: 1.61.1
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:15:35.620Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-37-genericVersion: 1.61.1
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:15:35.620Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-37-generic

Installed the extension manually via Github -> Release as recommended in the Output text, but same issue.

Removed the lingering .vscode/extensions/ms-vscode.cpptools-1.7.0 and tried again, but same issue.

Made sure all the files was owned by me (normal chown), but same issue.

![VS Code error 1](https://user-images.githubusercontent.com/13659704/137411639-552035cb-0d0b-47c9-ae64-e400ed1d9df5.png)

**Comment by JaxxArmstrong** [comment]
I have a workspace for often-edited-files, when not coding, and have been for a long time without issues. No specific folder is involved and a few of aforementioned files are also pinned.

Only ran into this problem yesterday when trying to update the extension in question.

**Comment by Colengms** [comment]
This should be fixed in 1.7.1.
