### ISSUE TITLE
LLVM formatting is not working.

### ISSUE THREAD

**Issue by lazyboson** [microsoft/vscode-cpptools#8284]
Bug type: Debugger

**Describe the bug**
- macOs Big Sur, 11.6
- VSCode Version: 1.61.0
- C/C++ Extension Version - Version 1.7.0::
- other VSCode extensions installed  - .run, python extension by Microsoft, and GitLens — Git supercharged:
- Even after modifying the desired flag of Clag in cpp extension(screen shot attached), i am not getting braces formatted in LLVM style.

![Screen Shot 2021-10-15 at 3 05 14 PM](https://user-images.githubusercontent.com/63603603/137471634-1a6b2ba2-f297-4991-9a39-3531a5e60513.png)

https://user-images.githubusercontent.com/63603603/137471341-e197e3de-2572-4ff7-9863-b69c6135bccf.mov

**Comment by lazyboson** [comment]
Hi @Colengms. I have a snippet for c++(same is attached), but the issue is independent of snippets(verified by me), The issue is specific to "Format Document" and ideally the behaviour should have been at auto-complete level. 
example - I it use auto complete to write FOR loop, then it should write loop like this - 
for() {
}
rather than -
for()
{

}

![Screen Shot 2021-10-16 at 10 11 07 AM](https://user-images.githubusercontent.com/63603603/137574027-4f44013b-97f1-4f96-9236-5628334d4684.png)

**Comment by Colengms** [comment]
Hi @lazyboson .  I can't easily repro an issue with formatting.  There would seem to be more about your configuration or environment that we would need to know to investigate further.

Could you set `"C_Cpp.loggingLevel": "Debug"`, and provide the output of the C/C++ channel leading up to and including the formatting operation (by invoking "Format Document") ?  The extension should output detailed logging regarding invoking `clang-format`.
