### ISSUE TITLE
vscode tries to launch when compile error

### ISSUE THREAD

**Issue by Anlarry** [microsoft/vscode-cpptools#8285]
Bug type: Language Service

**Describe the bug**
- OS and Version: 5.10.70-1-MANJARO
- VS Code Version: 1.61.1
- C/C++ Extension Version: v1.7.0
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
- Bug description: I press `F5` to debug a single cpp file, a compile error occurs, however vscode still try to launch. `launch.json` and `task.json` is default.

my launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - 生成和调试活动文件",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "为 gdb 启用整齐打印",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++ 生成活动文件",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```

my task.json:
```
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++ 生成活动文件",
            "command": "/usr/bin/g++",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "调试器生成的任务。"
        }
    ],
    "version": "2.0.0"
}
```

**Steps to reproduce**

1. create a new workspace and a cpp file with syntax error
2. press `F5` to debug and select `C++(GDB/LLDB)`, then `g++ - 生成和调试活动文件`
3. See error, vscode will try to launch target even if compile error

**Expected behavior**
vsode should aborts debug launch

**Additional context**

However, if I change  `"type": "cppbuild"` in `task.json` to `"type": "shell"` or `"type": "process"`, vscode will abort debug launch when compile error occurs.

**Comment by WardenGnaw** [comment]
This would be an issue with VS Code since they are trying to launch the debugger even though the `preLaunchTask` failed.

**Comment by Colengms** [comment]
This is being tracked by https://github.com/microsoft/vscode-cpptools/issues/8467 .  Closing this one as a dupe.
