### ISSUE TITLE
Breakpoint detection doesn't work well.

### ISSUE THREAD

**Issue by hotTeaFun** [microsoft/vscode-cpptools#8288]
Bug type: Debugger

- OS and Version:  Linux x64 5.10.68-1-MANJARO
- VS Code Version: 1.61.1
- C/C++ Extension Version: 1.70
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
Breakpoint detection doesn't work well.

**Describe the bug**

This bug does exist for quite a while as I have proposed a similar issue before which there are no response till now.
When targeting a breakpoint at a `cpp` file and trying to debug it, the debugger wouldn't stop as expected. It's quite amazing because this obvious bug can exist for such a long time. I began to wonder whether I'm the exception. But I have found another phenomenon: if I deleted the `.vscode` folder which means I have both the `task.json` ans `launch.json` removed, then I target a breakpoint and try to debug it using the default build and launch configuration, It will stop! I think it's quite funny. As I have used vscode for c++ coding for a long time, I sincerely hope this bug could be fixed soon for its priority. At last, I don't want to upload any log file requested or something else for its simpleness. If this bug is of my own bussiness, I apologize for my disturbance frankly.

**Comment by WardenGnaw** [comment]
> When targeting a breakpoint at a cpp file and trying to debug it, the debugger wouldn't stop as expected. 

This will happen if you build your project without debug symbols. The generated `task.json` will ensure your binary is built with debug symbols via `-g`.

>  At last, I don't want to upload any log file requested or something else for its simpleness.

Sorry, in order to investigate this issue. I will be needing the logs when you add the following to your `launch.json`.
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```
