### ISSUE TITLE
`new`/`delete` color not changing

### ISSUE THREAD

**Issue by cerevra** [microsoft/vscode-cpptools#8289]
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 20.04.3 LTS
- VS Code Version: 1.61.1
- C/C++ Extension Version: v1.7.0
- Other extensions you installed: [clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd)=v0.1.13

It is impossible to set some colors with settings.json. Problem related at least to this features from `/editor.tokenColorCustomizations/textMateRules`:
  - variable.other.global
  - variable.other.local
  - keyword.operator.new
  - entity.name.function.operator.member
  - entity.name.function.member.static

Also partly works `/editor.tokenColorCustomizations/keywords`: it doesn't effect words `using` and `operator`

I found previous [discussion](https://github.com/microsoft/vscode-cpptools/issues/5762): probably it will be useful.

**Steps to reproduce**

1. Provide in settings.json with overriding for global variables:
```
{
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "variable.other.global",
                "settings": {
                    "foreground": "#FF0000"
                }
            },
        ]
    },
    "clangd.path": "...",
    "C_Cpp.enhancedColorization": "Enabled",
    "workbench.colorTheme": "Default Dark+"
}
```
2. Create main.cpp with example
3. Note that neither the instantiation of the variable or the accessing of it have a different color other than the default blue

**Expected behavior**
The global variable should be red

**Code sample and logs**

- Code sample
```
int SOME_GLOBAL_VALUE = 42;

int main() {
    (void)SOME_GLOBAL_VALUE;

    return 0;
}
```

**Additional information**
If I change the "scope" value to simply "variable" it correctly changes the color of all of my variables

**Comment by cerevra** [comment]
>Semantic colorization requires that `C_Cpp.IntelliSenseEngine` is `Enabled`

`new`/`delete` are resist to be colored even with this condition: [category](https://github.com/cerevra/vs_colors/blob/5c499188503fa0a4b4bd972a362a6caca4f5d5af/settings.json#L8) `keywords` and [scope](https://github.com/cerevra/vs_colors/blob/5c499188503fa0a4b4bd972a362a6caca4f5d5af/settings.json#L66) `keyword.operator.new` both don't provide any effect for `new`/`delete`.

>a semantic (IntelliSense) parse of the translation unit is required to identify the tokens

It's offtopic now =)
I hope IntelliSense is not the only option to provide semantic parse: there is [public](https://code.visualstudio.com/updates/v1_44#_semantic-tokens-provider-api) [API](https://code.visualstudio.com/api/references/vscode-api#DocumentSemanticTokensProvider) which [used](https://github.com/clangd/vscode-clangd/pull/54) in clangd. It partly works as we can see: may be colleagues can fix it.

**Comment by Colengms** [comment]
Hi @cerevra .  In your example code, `new` and `delete` are being colored syntactically by VS Code (not semantically by the C/C++ extension).  You can see this by running the `Developer: Inspect Editor Tokens and Scopes` command, then clicking on the token to inspect.  Semantic scopes handled by the C/C++ Extention are indicated by mention of `semantic token type`, and syntactic tokens handled by VS Code refer only to `textmate scopes`.

The example you provided appears to have `settings.json` in an incorrect location.  If I move it to under a `.vscode` subdirectory, and change `keyword.operator.new` to `keyword.operator.new.cpp`, it appears to work as expected.  It's not clear to me why the `.cpp` must be added to the scope to override the theme color in this case.  You may want to follow up in the VS Code repo, if that is an issue.

**Comment by cerevra** [comment]
Hi @Colengms

`new`/`delete` are special keywords in C++: so they should be effected by `editor.tokenColorCustomizations/keywords` - it is expected behaviour (I guess). This issue is about breaking of expectations =)

>change `keyword.operator.new` to `keyword.operator.new.cpp`

Yes, this is solution - it works for me. So my problem is solved now, and this behaviour can confuse only newbie in VS Code.

It is story about product view. It is up to you: may be, it is OK to change syntactical to semantical analysis - who knows? =)
It can help users in future.

If you don't see problem here, we can close this issue: it was solved with help of `Developer: Inspect Editor Tokens and Scopes`.

**Comment by Shadowblitz16** [comment]
@Colengms I have this issue too.
![image](https://user-images.githubusercontent.com/2453707/144168441-73432715-752f-45a9-9992-b80178beaa07.png)

**Comment by Colengms** [comment]
Hi @Shadowblitz16 .  I don't see use of `new` or `delete` in the image you posted.  Actually, I don't see proper colorization for many things.  I assume the issue you are seeing is unrelated to this one.  Could you open a new issue with details on how we might reproduce it to investigate further?  I suspect IntelliSense is not running at all for that file.
