### ISSUE TITLE
Can not debug windows dll files compiled with gcc

### ISSUE THREAD

**Issue by GACLove** [microsoft/vscode-cpptools#829]
### example
[demo.zip](https://github.com/Microsoft/vscode-cpptools/files/1076839/demo.zip)

![example](https://user-images.githubusercontent.com/8307193/27169511-c16c0844-51dc-11e7-9b0a-f1e63d725b69.png)
**tools**
+ cmake
+ gdb (version 8.0)

**Comment by pieandcakes** [comment]
@GACLove The problem with the project is you didn't specify CMAKE_BUILD_TYPE of Debug. Once I did that in the CMake configuration, it worked.

**Comment by GACLove** [comment]
it's work after changed mingw 64 gdb, thanks


Sent from Mail Master
On 06/17/2017 05:41, Pierson Lee wrote:

@GACLove The problem with the project is you didn't specify CMAKE_BUILD_TYPE of Debug. Once I did that in the CMake configuration, it worked.

**Comment by GACLove** [comment]
https://nuwen.net/
I now use the nuwen version 15 compiler and TDM GDB. The GDB of nuwen cannot load the dynamic library symbol  @pieandcakes

**Comment by pieandcakes** [comment]
@GACLove Sounds like that version of 'gdb' has a compatibility issue?  Can you give me more information about this error:
>The GDB of nuwen cannot load the dynamic library symbol

If the implementation on that version of gdb is missing something, then there isn't anything I can do.
