### ISSUE TITLE
Go To Implementation

### ISSUE THREAD

**Issue by ljbade** [microsoft/vscode-cpptools#8292]
Type: Feature Request

After enjoying the recent addition of Go To Definition for my C++ projects, I realise that it is annoying not having the complementing "Go To Implementation" option.

It seems that it should be possible to support once the language extension implements according to the documentation at https://code.visualstudio.com/docs/editor/editingevolved#_go-to-implementation

I had a quick search in the issues but I can't see this mentioned already.

**Comment by sean-mcmanus** [comment]
Yes, it's a duplicate.
