### ISSUE TITLE
cpptools-srv EXC_BAD_ACCESS crash on macOS, in normal_id_lookup()

### ISSUE THREAD

**Issue by kenroser** [microsoft/vscode-cpptools#8293]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/8283

<div type='discussions-op-text'>

<sup>Originally posted by **kenroser** October 14, 2021</sup>
On a Intel Macbook Pro, I believe I have vscode setup properly and am using compile_commands.json.  The .cpp files don't have any squiggly lines and all the headers are found.

My problem is when I hover over something to see what it is, "Loading..." appears and it takes about 40-60 seconds before the result appears.  Similarly if I hit F12, there's a very long delay.  

Using Process Explorer, I see in both cases a cpptools-srv process starts up with 100% CPU usage and stays running for the same waiting period I have to see what a symbol is.

VSCode and the C++ extension are all up-to-date as of today.

This problem is not seen with VSCode on Linux with the same software in the workspace.

I'm hoping someone can provide some guidance on resolving this issue.</div>

**Comment by kenroser** [comment]
f I turn on the C/C++ debugger, when hovering, an IntelliSense process crash is detected:
```
terminating child process: 18651
IntelliSense process crash detected.
cpptools/finishUpdateSquiggles
Update IntelliSense time (sec): 22.855
Checking for syntax errors: file:///Users/roser/code/file.cpp
Update IntelliSense time (sec): 0
```

**Comment by Colengms** [comment]
Hi @kenroser .  Thanks for capturing the stack.  It appears to involve parsing a complex template class.  I don't believe we've seen this stack before.  Does it occur with a very simple project, or only with a more complex project?  Would you be able to provide a minimum example that reproduces the issue, that we could use to investigate further?

**Comment by kenroser** [comment]
I have not been able to produce a minimal example that demonstrates the problem.  I hope the call stack I provided is enough to track this down.  If/when a fix is ready, I'll be glad to test it.

**Comment by Colengms** [comment]
I think we will need a repro in order to investigate this further.  Leaving this open as 'more info needed' in case someone can provide a repro.

**Comment by kenroser** [comment]
In 1.8.5, the log output is now different:
```textDocument/hover: /Users/xxxr/code/file.cpp (id: 14)
Quick info operation failed: FE: 'Unknown error'
using Tag Parser for quick info

**Comment by kenroser** [comment]
As of 1.9.0, the problems I cited earlier in this bug are now gone.  It's working great!
Probably fixed by https://github.com/microsoft/vscode-cpptools/issues/7215.
