### ISSUE TITLE
__builtin_choose_expr is not evaluated in constant contexts

### ISSUE THREAD

**Issue by medhefgo** [microsoft/vscode-cpptools#8294]
Bug type: Language Service

**Describe the bug**
- OS and Version: Arch Linux
- VS Code Version: 1.61.1
- C/C++ Extension Version: 1.7.0

The following code sample produces bogus warnings that neither gcc or clang produce when compiling. The macro is from systemd and is designed to give a compiler error if the expression *cannot* be evaluated at compile time.

```c
#define ELEMENTSOF(x)                                                    \
        (__builtin_choose_expr(                                          \
                !__builtin_types_compatible_p(typeof(x), typeof(&*(x))), \
                sizeof(x)/sizeof((x)[0]),                                \
                (void)0))

int main(void) {
    int array1[1] = {};
    int array2[__builtin_choose_expr(1, 1, (void)0)] = {};
    int array3[ELEMENTSOF(array1)] = {};
    return 0;
}
```
`variable may not be initialized` and `incomplete type is not allowed` warnings for both `array2` and `array3` despite the fact that the expression is/must be evaluated at compile time (which is kind of the whole point of `__builtin_choose_expr`).

**Comment by sean-mcmanus** [comment]
This is fixed with 1.10.3 (pre-release).

**Comment by sean-mcmanus** [comment]
But it's only fixed for gcc mode and not clang.

**Comment by sean-mcmanus** [comment]
The remaining bug with clang mode is being tracked by https://github.com/microsoft/vscode-cpptools/issues/9368
