### ISSUE TITLE
Function-try-block syntax may be problematic

### ISSUE THREAD

**Issue by claudio-perrotta** [microsoft/vscode-cpptools#8297]
Issue Type: <b>Bug</b>

Code with more function like this (with function-try-block and trailing return type), make Intellisense unusable.

```
auto f(int n = 2) -> int try {
   ++n; // increments the function parameter
   throw n;
} catch(...) {
   ++n; // n is in scope and still refers to the function parameter
   assert(n == 4);
   return n;
}
```

Extension version: 1.7.0
VS Code version: Code 1.61.1 (c13f1abb110fc756f9b3a6f16670df9cd9d4cf63, 2021-10-14T01:19:42.089Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.15.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (1.19GB free)|
|Process Argv|--crash-reporter-id f5707333-7bc4-4342-9202-bf112defebd2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: RedHat-7-VM|
|OS|Linux x64 3.10.0-1160.15.2.el7.x86_64|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (4 x 2807)|
|Memory (System)|7.72GB (2.29GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200cf:30381675
vsaa593:30376534
vssld246cf:30379912

```

</details>

**Comment by Colengms** [comment]
Hi @claudio-perrotta .  When I paste the code you provided into a simple project, it's parsed properly and no squiggles are reported.  Could you provide a complete example that demonstrates the issue you are seeing?
