### ISSUE TITLE
functions and symbols reference  feature needed

### ISSUE THREAD

**Issue by mdzyduan** [microsoft/vscode-cpptools#83]
functions and symbols reference not support now, if you  using vscode read a large project , you will find it is not  convenient .

**Comment by kinreven** [comment]
agree

**Comment by sridmad** [comment]
Duplicate of #15

**Comment by sean-mcmanus** [comment]
Find All References is available in 0.25.0-insiders: https://github.com/microsoft/vscode-cpptools/releases/tag/0.25.0-insiders , but you'll need to set the C_Cpp.experimentalFeatures setting to "Enabled".
