### ISSUE TITLE
No Format Document for C++ on Linux (RH)

### ISSUE THREAD

**Issue by netdiver13** [microsoft/vscode-cpptools#830]
There are no "Format Document/Selection" options on Linux (at least, by default), while on Windows they are available right after installing the C/C++ extension!

**Comment by sean-mcmanus** [comment]
What is your Linux distro version? Are you using 32-bit Linux? The language service requires 64-bit and glibc 2.18 or greater, which RHEL 7 doesn't have (for a work around, see https://github.com/Microsoft/vscode-cpptools/issues/19 ).

**Comment by netdiver13** [comment]
Centos 7, 64 bit
So, it's all due to the glibc 2.18 dependency?
Thanks

**Comment by sean-mcmanus** [comment]
Yes.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4.
