### ISSUE TITLE
"Downloading C/C++ language components" is stuck or not downloading

### ISSUE THREAD

**Issue by thepranjal02** [microsoft/vscode-cpptools#8306]
Bug type: 
extension not downloading it showing only downloading and error in running the program.

![1](https://user-images.githubusercontent.com/92870736/138112047-d78869cb-aaa9-4148-b8ed-a82490bc030f.PNG)

**Comment by michelleangela** [comment]
The server that hosts the links to the binaries could be experiencing temporary issues and as a result causing issues to download the binaries during installation.

As a workaround for installation, please try to install the offline package installation of the extension found at https://github.com/microsoft/vscode-cpptools/releases/tag/1.7.1

**Comment by bobbrow** [comment]
Is the outage that caused this issue mitigated?  Can we close this issue?

**Comment by michelleangela** [comment]
Closing issue as it seem it has been resovled.. Please re-open if it still occurs.
