### ISSUE TITLE
The "and" operator is highlighted as an error

### ISSUE THREAD

**Issue by Apsapeh** [microsoft/vscode-cpptools#8307]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 x64
- VS Code Version: 1.61.2
- C/C++ Extension Version: 1.7.1

Hello, when i use the "and" or "or" or "not" operators, it is highlighted as an error and underlined with a red squiggly line. But the program compiles. This makes me very uncomfortable, is there any way to solve this? I will attach a screenshot below.

P.S English is not my native language, I used a translator to write this text, so there may be errors.

**Steps to reproduce**
Write "and" or "or" or "not" operators in a loop condition or in "if else"

**Expected behavior**
The operators "and", "or " and "not" should not be marked as error and should be highlighted like "&&", "||" and "!".

**Code sample**

```
#include <iostream>
#include <string>

int main()
{
    using namespace std;

    string str = "Tof123214256";

    for (char ch : str)
    {
        if (ch >= '1' and ch <= '9')   // error "and"
        {
            cout << ch << endl;           
        }
    }
}
```

**Screenshots**

![Desktop Screenshot 2021 10 20 - 23 22 20 95](https://user-images.githubusercontent.com/89659777/138166498-da6a6e67-107b-4176-b7e6-74eeb044b058.png)

**Additional context**
Please don't laugh if you find the code funny or too simple. I am just learning C++

**Comment by Colengms** [comment]
Hi @Apsapeh .  I tried a few compilers, and it looks like most do not support the spelled out "and" and "or" operators unless configured to use C++20.  The C/C++ extension tries to emulate the behavior of a compiler, as specified by the `IntelliSenseMode` and `cppStandard` (etc.) settings in a `c_cpp_properties.json`.  You might try running the command `C/C++: Edit Configuration (JSON)` and changing the value of `cppStandard` to `c++20`.
