### ISSUE TITLE
includePath doesn't work

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-cpptools#832]
_From @vinnyin on June 17, 2017 5:24_

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|vscode-lua|gccfeli|0.1.2|
|cpptools|ms-vscode|0.11.4|;

my stl source code is located at F:/code/stl
here is my c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "F:/code/stl"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "browse": {
                "path": [],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ]
}
but this doesn't work, #include<iostream> remains red, help me!!

_Copied from original issue: Microsoft/vscode#28924_

**Comment by charmingelle** [comment]
I have the same issue. These are my configurations:

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "C:/MinGW/lib/gcc/mingw32/4.8.1/include/c++"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "browse": {
                "path": [],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ]
}
```

**Comment by bobbrow** [comment]
Can you try copying `"F:/code/stl"` into the browse.path array and let us know if you are still having problems after that?

**Comment by David-AJ** [comment]
@bobbrow  @ramya-rao-a  I got the same problem, and I commented my details in #741            
Please tell me how to fix it, thanks!

**Comment by bobbrow** [comment]
@David-AJ, I looked at the other thread and it appears that you received the help you needed.  Please let us know if there is anything else you need.
