### ISSUE TITLE
can not find head files with cmake tools

### ISSUE THREAD

**Issue by RiverShi** [microsoft/vscode-cpptools#8321]
Issue Type: <b>Bug</b>

In the folder kinect_xtion, the vscode can find all the head files properly.
When I copy the whole folder to another path, rename it xtion, it does not work well.
I was very confused!

Extension version: 1.7.1
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 5.11.0-38-generic
Restricted Mode: No

situation
![image](https://user-images.githubusercontent.com/46646775/138594051-d4fc4c15-9ca7-4a98-ac95-360438579884.png)

setting.json

![image](https://user-images.githubusercontent.com/46646775/138594538-202ae91e-3bd2-4788-9cd8-ea5510e1e4d7.png)

path 
![image](https://user-images.githubusercontent.com/46646775/138594133-a0d0bdd7-24da-4412-8ab8-f6da161c3b02.png)

cmakelists
![image](https://user-images.githubusercontent.com/46646775/138594262-d79f6d39-8a44-4dc0-b1a4-e791e160afb2.png)

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|23.38GB (11.90GB free)|
|Process Argv|. --crash-reporter-id 93f47b1e-05ca-4a3b-a6dc-17c3f8b3a60e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by bobbrow** [comment]
Usually the `CMake: Configure` command is enough.  Delete cache and reconfigure is usually only needed when you switch compilers, make major changes, or mix up build types.  Lots of people like to set the `cmake.buildDirectory` to `${workspaceFolder}/build/${buildType}` to prevent regenerating the cache every time you switch from Debug to Release.
