### ISSUE TITLE
go to type definition get unexpected behavior on pointer

### ISSUE THREAD

**Issue by cloud-yu** [microsoft/vscode-cpptools#8337]
Bug type: Language Service

**Describe the bug**
- OS and Version:  ubuntu 20.04 for wsl2
- VS Code Version:  1.61.2
- C/C++ Extension Version:  v1.7.1

**Expected behavior**
go to type definition on pointers should find type definition by "variable type" not by "variable name"

here comes the e.g.
go to type def on `pre`  --> comes `LINKED` member， with the same "variable name"
go to type def on `curpos`  --> got null. 

both were expected to jump to  `NODE` 
**Screenshots**
![11](https://user-images.githubusercontent.com/8436078/139240989-c125f271-ece1-41a4-93b7-adedf36098d2.gif)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. It should be fixed in our next release.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/edit/1.8.0-insiders
