### ISSUE TITLE
Association of breakpoints and file editors not working in remote debugging of multiple source code folders

### ISSUE THREAD

**Issue by dmrauch** [microsoft/vscode-cpptools#834]
When remotely debugging C++ source code residing in a "complex" folder hierarchy VS Code seems to lack proper graphical debugging integration in the GUI. Specifically, when break points are hit, the editor does not properly indicate this.

A full minimal working example including step-by-step instructions to reproduce this issue is available at [dmrauch/vscode-cpp-remote-debug](https://github.com/dmrauch/vscode-cpp-remote-debug).

Any hints/help is extremely welcome! Many thanks!

**Comment by pieandcakes** [comment]
@dmrauch I think you want `"sourceFileMap"` option in `launch.json`. You should be able to specify a few different ones to get the compiled source location to be mapped to the local source location.

**Comment by dmrauch** [comment]
This indeed fixed it - awesome, many thanks, @pieandcakes!
All that was needed in this case was to map the remote file system root (`/`) to the local file system root (in my case `/run/user/1000/gvfs/sftp:host=<remote-host>/`).
