### ISSUE TITLE
while using gdb to view registers gdb unexpectedly exit

### ISSUE THREAD

**Issue by dfddgge** [microsoft/vscode-cpptools#8342]
Issue Type: <b>Bug</b>

1.c++ program is running in debug mode.
2.open registers at variaty window or type '-exec info registers' at debugging console.
3.gdb unexpectedly exit
ps. I've tested in command line that gdb can successfully run with command 'info registers'.

Extension version: 1.7.1
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.31GB free)|
|Process Argv|--crash-reporter-id fe020d40-cd38-42d2-93e5-a4fb2136c238|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
[1.zip](https://github.com/microsoft/vscode-cpptools/files/7443137/1.zip)

vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by WardenGnaw** [comment]
Can you share the output from the `Debug Console` when you add the following to your `launch.json`?
```json
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

**Comment by dfddgge** [comment]
The output is in the file attached when I add those command.
[debug console.txt](https://github.com/microsoft/vscode-cpptools/files/7457123/debug.console.txt)

**Comment by dfddgge** [comment]
> Can you share the output from the `Debug Console` when you add the following to your `launch.json`?
> 
> ```json
> "logging": {
>    "engineLogging": true,
>    "traceResponse": true
> }
> ```

The output is in the file attached when I add those command.
[debug console.txt](https://github.com/microsoft/vscode-cpptools/files/7457123/debug.console.txt)

**Comment by WardenGnaw** [comment]
Ah, this is an issue with the version of GDB which crashes when you send `-data-list-register-values`

From the logs:
```
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (6659) <-1035-data-list-register-values x\r\n"},"seq":740}
1: (6659) <-1035-data-list-register-values x
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (7642) Shell exited, stop debugging\r\n"},"seq":742}
1: (7642) Shell exited, stop debugging
```

Marking as external since this is an issue with GDB.

The work around is to use the x86 version of GDB v8,1 or a newer version of GDB should fix the issue.
