### ISSUE TITLE
对于宏条件判断高亮识别错误

### ISSUE THREAD

**Issue by hbuexinxin** [microsoft/vscode-cpptools#8346]
Issue Type: <b>Bug</b>

形如如下代码,宏A值为TRUE，但是内容不是高亮的，范围内容B是高亮的。
有时重新加载VSCode后初次时正确的，但是过一会就有可能不正确了。
AAA在头文件a.h中定义

``` c
#include “a.h”

#if AAA
内容A
#else
内容B
#endif
```

![Snipaste_2021-10-30_10-06-52](https://user-images.githubusercontent.com/2741609/139516747-f9806021-c84c-47ff-96a6-df2170dab876.png)

Extension version: 1.7.1
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.94GB free)|
|Process Argv|--crash-reporter-id a8fc0120-4c6e-4031-a3f1-eeb17dd38a76|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sean-mcmanus** [comment]
I suspect that TRUE is not defined. Can you confirm whether it's defined or not?
