### ISSUE TITLE
Debugging seems to stall if preLaunchTask is defined

### ISSUE THREAD

**Issue by evdenaxas** [microsoft/vscode-cpptools#8352]
Bug type: Debugger

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.61.2
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
-Adding a simple preLaunchTask in a launch command seem to stall the process. I am adding a task to simply echo a string. If I enable the preLaunchTask with that task and I start the debugging session it stalls, my CPU utilization maxes out, top shows cpptools as the process that consumes most resources and the debugging session never activates. When I remove the preLaunchTask, debugging proceeds properly. 

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
Add the following task as a prelaunchtask to any debugging config
{
            "label": "noop_echo",
            "type": "shell",
            "command": "echo",
            "args": [
                "foobar"
            ]
        },

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment]
The C++ extension does not control running `preLaunchTask`. I would re-open this issue at https://github.com/microsoft/vscode/issues.
