### ISSUE TITLE
MS extensions should be enabled by default for Cygwin and MinGW

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#8353]
This is derived from: https://github.com/microsoft/vscode-cpptools/issues/6412

Apparently (based on experimentation), Cygwin supports MS Extensions despite not returning the associated define (`_MSC_EXTENSIONS`).

Opening this issue to track enabling MS Extensions for Cygwin gcc, by default.

**Comment by Colengms** [comment]
Re-opening and using to track re-enabling of `ms_extensions` by default for Cygwin and MinGW.

We have some known bugs (internally: 1447675, 1450571) with `ms_extensions` on gcc, which we'd like to address before enabling this by default.  Users can manually enable it by adding `-fms_extensions` as a compiler arg.

**Comment by sean-mcmanus** [comment]
1450651 has been fixed (pending integration).

**Comment by Colengms** [comment]
It looks like the remaining two issues blocking this have been fixed.  Maybe we can enable MS extensions for Cygwin and MinGW by default now?

**Comment by sean-mcmanus** [comment]
Sure, we could try that for 1.15.
