### ISSUE TITLE
cpptools.exe is a 32-bit process

### ISSUE THREAD

**Issue by Rattenhirn** [microsoft/vscode-cpptools#8356]
Bug type: Language Service (I think)

**Describe the bug**
- OS and Version: Windows 10.0.19042 Build 19042
- VS Code Version: 1.61.2
- C/C++ Extension Version: v1.7.1

When installing the extension through VS Code Extensions or using the .vsix from GitHub, it will still always launch the 32-bit version of cpptools.exe. When working with a large project, over time this can hit the 2 GiB memory limits that 32-bit processes have, slowing down everything, despite enough memory being available on the system.

**Steps to reproduce**
1. Install C/C++ extension
2. Open a project with C/C++ files in it
3. Observe the bit-ness of the cpptools.exe process in Process Explorer

**Expected behavior**
A 64-bit version of cpptools.exe being launched

**Screenshots**
![cpptools](https://user-images.githubusercontent.com/10184133/139816379-a47b9f65-b025-4a81-830b-426f4517c540.png)

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).
