### ISSUE TITLE
struct syntax highlighting problem

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8358]
![image](https://user-images.githubusercontent.com/49903949/140013230-369a70ea-921d-423f-bcb3-9633780b52bb.png)

**Comment by Colengms** [comment]
Hi @Xiagb728 .  The C/C++ Extension provides colorization for tokens that are identified semantically.  In this case, the issue you are seeing is with a token that should be identified syntactically/lexically.  The TextMate grammar used by VS Code for C/C++ source files should be identifying that token using the `variable.parameter.c` scope, but appears to be misidentifying it.

The TextMate grammar VS Code uses for C/C++ is provided by a contributor.  I'd suggest opening this issue in their repo here: https://github.com/jeff-hykin/better-cpp-syntax/issues

**Comment by Xiagb728** [comment]
@Colengms I see
