### ISSUE TITLE
 Installing package 'C/C++ language components (Windows)' failed

### ISSUE THREAD

**Issue by iuuniang** [microsoft/vscode-cpptools#836]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (4663 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (905 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (12081 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Warning: File 'C:\Users\iuuni\.vscode\extensions\ms-vscode.cpptools-0.11.4\bin\Microsoft.VSCode.CPP.Extension.exe' already exists and was not updated.
Failed at stage: installPackages
Error: invalid local file header signature: 0x16d537e7

Finished

**Comment by alexchicn** [comment]
I have same problem.
You need reinstall C/C++ and update C/C++ dependencies again by proxy, if you are in China like me.

**Comment by iuuniang** [comment]
@alexchicn 
老哥，那个依赖怎么更新呀，我重新安装了好多次，还是失败。😌

**Comment by iuuniang** [comment]
"C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-0.11.4\package.json"

Open the file, and then find the corresponding project download link, manually extract.
