### ISSUE TITLE
Select All / Refactor Settings

### ISSUE THREAD

**Issue by nosjojo** [microsoft/vscode-cpptools#8361]
Type: Feature Request

The refactor setting works great for simple usage, but it lacks settings/modifiers to expand the functionality's default behavior.

- It currently only selects "CONFIRMED REFERENCES" as the default.
- Items that are "COMMENT REFERENCES" do not get auto-selected, but are selectable.
- Each file is separated, so 100 files with 1 function and 1 comment requires 100 checkboxes to be clicked to capture the comments.
- The grouping mechanism just separates the categories, but still nests by file.

I see two reasonable ways to address this:
- Nest the results of the refactor 1 level deeper, allowing for a root level "select all" checkbox to exist.
- Add refactor settings to vscode to enable/disable defaults on the different types of refactor results to always select comments.

**Comment by sean-mcmanus** [comment]
I think some of theses changes may require changes to VS Code itself, since we re-use their UI (the "other references" section might be our UI though).
