### ISSUE TITLE
support show  local variable of Function in outline

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8364]
Type: Feature Request

just like typescript, please support  local variable in outline
![image](https://user-images.githubusercontent.com/1876302/140098747-48bafb0d-8799-46f8-9a10-69dbd576f32f.png)

**Comment by sean-mcmanus** [comment]
We're unlikely to support local variables in the outline view, since VS itself doesn't support that and the system that provides the non-local symbols for a file doesn't parse the contents inside of functions. This is also probably a duplicate of a previously filed issue.

**Comment by heartacker** [comment]
@sean-mcmanus  thanks for you clarify

and what is the due day of 1.8.0 . I can't wait for new experience since its Significant performance improvements

**Comment by sean-mcmanus** [comment]
I'm not sure when 1.8.0 will be released. We've been fixing bugs with it. Hopefully within the next 2 weeks.
