### ISSUE TITLE
Include path is not working

### ISSUE THREAD

**Issue by daldr-ntml** [microsoft/vscode-cpptools#837]
VS Code 1.13.1, C/C++ 0.11.4, on Windows platform.

snippet from my c_cpp_properties.json:

        {
            "name": "Win32",
            "includePath": [
                "C:/Leda_sdk/sysroots/haswell-64-wrs-linux/usr/include/c++/5.2.0/*"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "c:/SVNProj/Leda/trunk/software/.vscode/.browse2.vc.db",
                "path": [
                    "c:/Program Files (x86)/Windows Kits/10/Include/10.0.10586.0/um"
                ]
            }
        }

but #include <iostream> in .cpp file has wiggly underline.

Does the include path need '/*' at the end?  (I've tried it without - neither works).

When is a changed includePath adopted?  Can I refresh?

Is 'Win32' configuration automatically adopted on Windows platform?

Would appreciate some help please.

**Comment by sean-mcmanus** [comment]
What is the message for the squiggle and what is your intelliSenseEngine set to? For includePath, "*" is ignored at the end (it means don't search recursively for browse.path). Win32 is automatically used for Windows -- you can see the current config name in the bottom right corner. Changing the includePath and saving the .json file should refresh the results -- unless the file watcher on the config file fails (a fix for that will be in the next update).

**Comment by daldr-ntml** [comment]
Thank you for your reply.  Adding:

  "C_Cpp.intelliSenseEngine": "Default"

to the workspace settings fixed the problem (it wasn't set before).

Perhaps this needs to be made clearer in the documentation?

**Comment by sean-mcmanus** [comment]
We have an FAQ at https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md . The intelliSenseEngine is default to "Default" in the Insider's build, and we eventually plan to re-enable it as the default for the non-Insider's build too.

**Comment by daldr-ntml** [comment]
Thank you for the link to the FAQ.
