### ISSUE TITLE
includePath wildcard /** is not working 

### ISSUE THREAD

**Issue by Panhjt** [microsoft/vscode-cpptools#8376]
Bug type: Language Service

**Describe the bug**
- OS and Version: Win 10 family 20H2
- VS Code Version: 1.62.0 system set up
- C/C++ Extension Version:  v1.7.1
- Other extensions you installed (and if the issue persists after disabling them): fortran, jupyter, jupyter notebook renderers, jupyter keymap, python, pylance. The problem persists after disabling them all.

- The /** in includePath cannot search for child folders recursively. For example, a foobar.h file is under ${workspaceFolder}/headFiles, but there is an include error not finding foobar.h. The quick fix option is to give the full path ${workspaceFolder}/headFiles while ${workspaceFolder}/** is already specified in includePath. 

**Steps to reproduce**

-creat a new file
-include some .h file under workspace folder(but not in the .vscode folder)

**Expected behavior**
include error detected. cannot open source file "blabla.h".

**Code sample and logs**
**This one is the failed one:**
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64"
        }
    ],
    "version": 4
}
```

**on another computer there's no this problem. the configuration file is:**
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\Hostx64\\x64\\cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64"
        }
    ],
    "version": 4
}
```
**Screenshots**
the error and quick fix options
![image](https://user-images.githubusercontent.com/81690069/140631867-dd50e3a1-15a3-4a83-82ee-941387300918.png)

the includePath lists
![image](https://user-images.githubusercontent.com/81690069/140631884-718c6b8e-584d-4c07-84c4-9f81769fff5d.png)

**Comment by Jademalo** [comment]
Also having this issue.

`${workspaceFolder}/**` seems to include none of my headers at all.
Interestingly, `${workspaceFolder}/include` also seems to include subfolders of include without the wildcards.

**Comment by Colengms** [comment]
Hi @Panhjt .  There is no significant difference between the 2 configuration you provided.

Use of recursive includes are resolved when the file is opened.  Instead of configuring IntelliSense will ALL possible include paths found recursively, it will only add paths to headers that were included by the file.  As you modify (and save) a file, it will be rescanned, and newly referred to headers will have their paths added to the IntelliSense configuration.  Is it possible you were seeing this error on an unsaved file?  If so, does saving the file (and waiting briefly for the rescan to complete) clear up the squiggle?
