### ISSUE TITLE
Code navigation shortcuts do not work after update

### ISSUE THREAD

**Issue by TimCondon** [microsoft/vscode-cpptools#838]
I recently updated to VSCode 1.13, and many code navigation shortcuts no longer work - such as switch header/source, go to declaration, navigate..., go to Symbol, etc. The navigation shortcuts that still work include going to a particular line (:) and go to file. 

This is true even after a clean reboot with all other VSCode extensions disabled, and it affects these commands whether executed via shortcut keys or through the right-click context menu

---

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 3.10.0-327.4.4.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-clip-ring|SirTobi|0.0.2|
|code-gnu-global|austin|0.2.2|
|cpptools|ms-vscode|0.11.4|
|vs-keybindings|ms-vscode|0.1.3|
|perforce|slevesque|2.1.0|;

**Comment by sean-mcmanus** [comment]
Can you delete your c_cpp_properties.json and create a new one? You may also want to delete your .browse.vc.db (or rename the databaseFilename). What result do you get when it fails? Have you tried opening a new folder with a simple C++ example?

**Comment by TimCondon** [comment]
Hi @sean-mcmanus --

Deleting the c_cpp_properties.json (and creating a new empty file with the same name, as a seperate test) had no effect, nor did deleting all the browse.vc.db. I also created a new folder with a very simple .hpp and matching cpp, and I get the same (broken) behavior.

For some operations such as switch header/source, go to declaration, and navigate..., nothing happens at all. For operations like go to symbol in file, the box opens with the appropriate symbol (ie @), but it continues to say "No symbol information for the file" no matter what I type.

Any other suggestions or information I can provide?

--Tim

**Comment by sean-mcmanus** [comment]
You don't want to create an empty c_cpp_properties.json -- you want the default from C/Cpp: Edit Configurations.

**Comment by TimCondon** [comment]
Hi @sean-mcmanus --

Thanks for the clarification. Unfortunately, I see the same behavior with running that command from the palette, and I verified the content of the newly created c_cpp_properties.json file seems reasonable. 

It's probably worth noting that VSCode doesn't seem to regenerate the .db file after I've deleted it, it doesn't show the red platform flame icon at all (even for a very large project), and it doesn't underline any of the external headers in green.

**Comment by sean-mcmanus** [comment]
You only want to delete the .browse.vc.db once (in case it's somehow corrupt with old data). The database should get re-created when you re-open the workspace. Setting the databaseFilename to "${workspaceRoot}/.vscode/.browse.vc.db" is convenient for diagnosing issues. For the browsing features to work, the database file will need to exist, and the red flame in the right should appear for a little as it parses the browse.path files. The Microsoft.VSCode.CPP.Extension.linux process should also be running.

**Comment by TimCondon** [comment]
Hi @sean-mcmanus --

Yes, I only deleted the .browse.cs.db file once, and it does not get recreated when I reopen a workspace (regardless of whether I change databaseFilename or not). I also do not see a process named anything like "Microsoft.VSCode.CPP.Extension.linux process." What might prevent this process from running?

--Tim

**Comment by sean-mcmanus** [comment]
What is your Linux distro? The process requires glibc version 2.18 and 64-bit Linux. We're not aware of other requirements. Are you saying that only an older version of the extension created a .browse.vc.db and you can't get the newer version of our extension to launch the Linux process or create the .browse.vc.db?

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
