### ISSUE TITLE
namespace "std" has no member "cout". Linux

### ISSUE THREAD

**Issue by MKrbm** [microsoft/vscode-cpptools#8380]
Bug type: Language Service

**Describe the bug**
- OS and Version: 20.04.3 LTS
- VS Code Version: 1.62.0
- C/C++ Extension Version: ms-vscode.cpptool (v1.7.1)

I have an issue with the IntelliSense of C/C++ extension that . I think this is the same issue with [#765](https://github.com/microsoft/vscode-cpptools/issues/765), and I read many related issues like [#1374](https://github.com/microsoft/vscode-cpptools/issues/1374) and [#7491](https://github.com/microsoft/vscode-cpptools/issues/7491), but I couldn't solve mine. 

My code is : <br>
```
#include <iostream>
using namespace std;

int main()

    cout << "hello world" << endl;
    return 0;
}
```
and vscode says 
`identifier "cout" is undefined`.
<br>
I tried many different cpp_properties.json, but now is like :
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "${default}"
        }
    ],
    "version": 4
}
```

also, the output from C/C++ : Log Diagnostics is : 
```
Version: 1.7.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/g++",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/keisuke/Documents/study/CMake-master/Help/guide/tutorial/test.cpp ]:
    /home/keisuke/Documents/study/CMake-master/Help/guide/tutorial/test.cpp
Translation Unit Configurations:
[ /home/keisuke/Documents/study/CMake-master/Help/guide/tutorial/test.cpp ]:
    Process ID: 23134
    Memory Usage: 56 MB
    Compiler Path: /usr/bin/g++
    Includes:
        /usr/include/c++/9
        /usr/include/x86_64-linux-gnu/c++/9
        /usr/include/c++/9/backward
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=90300
Total Memory Usage: 56 MB

------- Workspace parsing diagnostics -------
```

I'd appreciate it if someone help me. 

**screenshots*
![Screenshot from 2021-11-09 14-50-29](https://user-images.githubusercontent.com/57752203/140870641-dab50a84-8785-4e37-9f6c-157205f3d8ef.png)
![Screenshot from 2021-11-09 14-50-00](https://user-images.githubusercontent.com/57752203/140870644-bd98676f-dae5-48bf-9429-30a3e72175d8.png)
*

**Comment by Colengms** [comment]
Hi @keisukemurota .  The code you provided was:

```
#include <iostream>
using namespace std;

int main()

    cout << "hello world" << endl;
    return 0;
}
```

In that code, `cout` is squiggled, but I'm not able to reproduce the specified error you are seeing.  Rather, that code is squiggled due to a missing `{`.  With that added, I'm unable to reproduce an error with the same settings you've provided (On Ubuntu 20.04.3 LTS).

Could you perhaps provide a full self-contained repro (perhaps in the form of a github repo?) that we could use to reproduce the issue locally and investigate further?

**Comment by keisukemurota** [comment]
Thank you for the reply. <br><br>

> Rather, that code is squiggled due to a missing {

I'm sorry, I accidentally deleted the parentheses. <br><br>

As for the squiggles, they actually disappeared after rebooting my ubuntu machine for the first time in two days for some reason, although they hadn't disappeared by rebooting before I posted this issue. So, I cannot reproduce this behavior as well, but I give a link to my [github repo](https://github.com/keisukemurota/vscode_intellisense.git), which used to have the squiggle issue.

**Comment by eypsume** [comment]
It's same issue for me.
My c_cpp_properties:
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/include/**",
                "/usr/include/c++/11/**",
                "/usr/include/c++/11/x86_64-redhat-linux/**",
                "/usr/include/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "c++20",
            "intelliSenseMode": "linux-gcc-x64",
            "compilerArgs": [
                "-Os",
                "-std=c++20",
                "-Wall"
            ],
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}

ms-vscode-cpptool is v1.8.0 insiders2

**Comment by Colengms** [comment]
Hi @eypsume .  I suspect your issue has a different cause.  You have `configurationProvider` set, which will take precedence over the other settings in `c_cpp_properties.json`.  The IntelliSense configurations for your source files are being provided from CMake Tools, so issues may be related to what CMake Tools is providing (or possibly the contents of your CMakeLists.txt).

Can you open a new issue for your repro?  In it, could you provide the output of the `C/C++: Log Diagnostics` command for the file that is repro'ing the issue?  Also, could you set `"C_Cpp.loggingLevel": "Debug"` and provide the output from the C/C++ output channel leading up to the repro?

**Comment by eypsume** [comment]
But I have got this issue without CMake tool before.
You're right, the  CMake Tool appends the configurationProvider set  when I installed the CMake Tools and configure them for my project.
I got tested it as that I remove the set but still same.

Here,  c_cpp Log Diagnostics:
-------- Diagnostics - 2021. 12. 22. 오후 4:37:47
Version: 1.8.0-insiders2
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/include/**",
        "/usr/include/SDL2/**",
        "/usr/include/c++/11/**",
        "/usr/include/c++/11/x86_64-redhat-linux/**",
        "/usr/include/**"
    ],
    "defines": [
        "USE_CI=1"
    ],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu17",
    "cppStandard": "c++20",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [
        "-Os",
        "-std=c++20",
        "-Wall"
    ],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${workspaceFolder}/include/**",
            "/usr/include/SDL2/**",
            "/usr/include/c++/11/**",
            "/usr/include/c++/11/x86_64-redhat-linux/**",
            "/usr/include/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/ToposApp.cpp ]:
    /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/ToposApp.cpp
[ /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/ToposWarping.cpp ]:
    /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/ToposWarping.cpp
[ /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/ToposWindow.cpp ]:
    /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/ToposWindow.cpp
Translation Unit Configurations:
[ /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/ToposApp.cpp ]:
    Process ID: 27878
    Memory Usage: 195 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/c++/11/x86_64-redhat-linux
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-redhat-linux/11/include
        /usr/local/include
        /usr/include
        /usr/include/SDL2
        /usr/include/opencv4/opencv2/flann
    Defines:
        USE_CI=1
    Standard Version: c++20
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110201
[ /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/ToposWarping.cpp ]:
    Process ID: 27980
    Memory Usage: 485 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/c++/11/x86_64-redhat-linux
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-redhat-linux/11/include
        /usr/local/include
        /usr/include
        /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/include
        /usr/include/SDL2
        /usr/include/linux
        /usr/include/opencv4/opencv2/flann
    Defines:
        USE_CI=1
    Standard Version: c++20
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110201
[ /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/ToposWindow.cpp ]:
    Process ID: 28031
    Memory Usage: 510 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/11
        /usr/include/c++/11/x86_64-redhat-linux
        /usr/include/c++/11/backward
        /usr/lib/gcc/x86_64-redhat-linux/11/include
        /usr/local/include
        /usr/include
        /home/dragontesa/spider.w/topos/topos_mcm/HelloToposMCM/include
        /usr/include/SDL2
        /usr/include/linux
        /usr/include/opencv4/opencv2/flann
    Defines:
        USE_CI=1
    Standard Version: c++20
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110201
Total Memory Usage: 1190 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5685

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: /usr/include/c++/11/algorithm
    Alternative: "/usr/include/c++/v1"
    Alternative: "/usr/include/c++/v1/experimental"
    Alternative: "/usr/include/c++/11/parallel"
    Alternative: "/usr/include/c++/11/ext"
    Alternative: "/usr/include/c++/11/experimental"
Using: /usr/include/c++/11/array
    Alternative: "/usr/include/c++/11/tr1"
Using: /usr/include/c++/11/x86_64-redhat-linux/bits/atomic_word.h
    Alternative: "/usr/include/c++/11/x86_64-redhat-linux/32"
Using: /usr/include/c++/11/deque
    Alternative: "/usr/include/c++/11/debug"
Using: /usr/include/endian.h
    Alternative: "/usr/include/bits"
Using: /usr/include/errno.h
    Alternative: "/usr/include/sys"
    Alternative: "/usr/include/linux"
    Alternative: "/usr/include/asm-generic"
    Alternative: "/usr/include/asm"
Using: /usr/lib/gcc/x86_64-redhat-linux/11/include/limits.h
    Alternative: "/usr/include/c++/v1/__support/ibm"
Using: /usr/include/c++/11/ratio
    Alternative: "/usr/include/c++/11/tr2"
Using: /usr/include/wchar.h
    Alternative: "/usr/include/c++/v1/__support/solaris"

**Comment by eypsume** [comment]
It's solved for me after build and change header inclusion from <ostream> to <iostream>.
I take the mistake which use <ostream> for std::cout.
Something there, I remember the issue was there even with <iostream> if I don't build the project.
No matter what, I'm happy as this solved.
Thanks a lot.
