### ISSUE TITLE
Intellisense issues with github.com/cilium/cilium project

### ISSUE THREAD

**Issue by briantopping** [microsoft/vscode-cpptools#8384]
Bug type: Language Service

**Describe the bug**
- OS and Version: MacOS 12.0.1 (21A559)
- VS Code Version: Version: 1.62.1 (Universal) Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
- C/C++ Extension Version: 3/29/2016, 19:27:12
- Other extensions you installed (and if the issue persists after disabling them): Makefile Tools 0.2.2
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Working on the C code in https://github.com/cilium/cilium, project imported via the Makefile extension. Found the configuration to be reasonably accurate and was able to tune configuration when the `configurationCache.log` indicated a mismatch:

The issue is the rendering of many of the C source files, such as `cilium/bpf/bpf_lxc.c` from that tree. Cilium team intends that the code matches [Linux kernel standards](https://www.kernel.org/doc/html/latest/process/programming-language.html), so `gnu89`. Backend is probably inconsequential, but the target is eBPF bytecode via LLVM. 

Generally, the Intellisense engine in `default` mode has 240+ errors. A common problem seems to be dialect problems such as incorrect handling of varargs in macros, which have a lot of variations between dialects. Generating code for eBPF has a heavy dependency on `inline` as well. Putting the renderer in tag mode results in no errors. The project builds with no errors as well.

`Translation Unit Mappings` are seeing the file dialect as `c89` rather than `gnu89`, but those may be equivalent (it's not `c11`...). 

**Steps to reproduce**

1. Import https://github.com/cilium/cilium
2. Configure Makefile tools extension to bring in code configuration. There is a root makefile and it should do the right thing.
3. Open `cilium/bpf/bpf_lxc.c`

**Expected behavior**

Should render without errors

**Code sample and logs**

- Code sample

- Configurations in `settings.json`
```
{
  "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools",
  "[c]": {
    "editor.detectIndentation": false,
    "editor.tabSize": 8,
    "editor.insertSpaces": false,
    "editor.rulers": [80]
  },
  "makefile.loggingLevel": "Debug",
  "makefile.extensionLog": "extension.log",
}
```
- Configurations in `c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Mac",
            "cStandard": "gnu89",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 11/10/2021, 12:55:50 PM
Version: 1.7.1
Current Configuration:
{
    "name": "Mac",
    "cStandard": "gnu89",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.makefile-tools",
    "compilerPathIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": false,
    "intelliSenseModeIsExplicit": true
}
Custom browse configuration: 
{
    "browsePath": [
        "/Users/brian/go/src/github.com/cilium/cilium/bpf",
        "/Users/brian/go/src/github.com/cilium/cilium/bpf/custom",
        "/Users/brian/go/src/github.com/cilium/cilium/bpf/include",
        "/Users/brian/go/src/github.com/cilium/cilium/bpf/include/",
        "/Users/brian/go/src/github.com/cilium/cilium/bpf/sockops"
    ],
    "compilerArgs": [
        "-O2",
        "-g",
        "-target",
        "bpf",
        "-nostdinc",
        "-emit-llvm",
        "-Wall",
        "-Wextra",
        "-Werror",
        "-Wshadow",
        "-Wno-address-of-packed-member",
        "-Wno-unknown-warning-option",
        "-Wno-gnu-variable-sized-type-not-at-end",
        "-Wdeclaration-after-statement",
        "-c",
        "bpf_custom.c",
        "-o",
        "bytecount.ll"
    ],
    "compilerPath": "/usr/bin/clang",
    "standard": "gnu89",
    "windowsSdkVersion": ""
}
Custom configurations:
[ /Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c ]
{
    "defines": [
        "SKIP_DEBUG=1",
        "ENABLE_IPV4=1",
        "ENABLE_IPV6=1",
        "ENABLE_HOST_SERVICES_TCP=1",
        "ENABLE_HOST_SERVICES_UDP=1",
        "ENABLE_HOST_REDIRECT=1",
        "ENABLE_ROUTING=1",
        "NO_REDIRECT=1",
        "POLICY_VERDICT_NOTIFY=1",
        "ALLOW_ICMP_FRAG_NEEDED=1",
        "ENABLE_IDENTITY_MARK=1",
        "MONITOR_AGGREGATION=3",
        "CT_REPORT_FLAGS=0x0002",
        "ENABLE_HOST_FIREWALL=1",
        "ENABLE_SERVICE_PROTOCOL_DIFFERENTIATION=1",
        "HAVE_LPM_TRIE_MAP_TYPE=1",
        "HAVE_LRU_HASH_MAP_TYPE=1",
        "ENABLE_MASQUERADE=1",
        "ENABLE_SRC_RANGE_CHECK=1",
        "ENABLE_NODEPORT=1",
        "ENABLE_EXTERNAL_IP=1",
        "ENABLE_NODEPORT_ACCELERATION=1",
        "ENABLE_SESSION_AFFINITY=1",
        "ENABLE_DSR_ICMP_ERRORS=1",
        "ENABLE_DSR=1",
        "ENABLE_HOSTPORT=1",
        "ENABLE_LOADBALANCER",
        "ENABLE_DSR_HYBRID=1",
        "ENABLE_IPV4_FRAGMENTS=1",
        "ENCAP_IFINDEX=1",
        "TUNNEL_MODE=1",
        "ENABLE_EGRESS_GATEWAY=1",
        "__NR_CPUS__=10"
    ],
    "standard": "gnu89",
    "includePath": [
        "/Users/brian/go/src/github.com/cilium/cilium/bpf/include",
        "/Users/brian/go/src/github.com/cilium/cilium/bpf"
    ],
    "forcedInclude": [],
    "intelliSenseMode": "clang-x64",
    "compilerPath": "/usr/bin/clang",
    "compilerArgs": [
        "-O2",
        "-g",
        "-target",
        "bpf",
        "-nostdinc",
        "-emit-llvm",
        "-Wall",
        "-Wextra",
        "-Werror",
        "-Wshadow",
        "-Wno-address-of-packed-member",
        "-Wno-unknown-warning-option",
        "-Wno-gnu-variable-sized-type-not-at-end",
        "-Wdeclaration-after-statement",
        "-c",
        "bpf_lxc.c",
        "-o",
        "bpf_lxc.ll"
    ],
    "windowsSdkVersion": ""
}
[ /Users/brian/go/src/github.com/cilium/cilium/bpf/sockops/bpf_redir.c ]
{
    "defines": [
        "__NR_CPUS__=10",
        "SKIP_DEBUG",
        "HAVE_LPM_TRIE_MAP_TYPE",
        "HAVE_LRU_HASH_MAP_TYPE",
        "ENABLE_IPV4",
        "ENABLE_IPV6",
        "ENCAP_IFINDEX=1",
        "ENABLE_SERVICE_PROTOCOL_DIFFERENTIATION=1"
    ],
    "standard": "gnu89",
    "includePath": [
        "/Users/brian/go/src/github.com/cilium/cilium/bpf/include",
        "/Users/brian/go/src/github.com/cilium/cilium/bpf"
    ],
    "forcedInclude": [],
    "intelliSenseMode": "clang-x64",
    "compilerPath": "/usr/bin/clang",
    "compilerArgs": [
        "-O2",
        "-g",
        "-target",
        "bpf",
        "-nostdinc",
        "-emit-llvm",
        "-Wall",
        "-Wextra",
        "-Werror",
        "-Wshadow",
        "-Wno-address-of-packed-member",
        "-Wno-unknown-warning-option",
        "-Wno-gnu-variable-sized-type-not-at-end",
        "-Wdeclaration-after-statement",
        "-c",
        "bpf_redir.c",
        "-o",
        "bpf_redir.ll"
    ],
    "windowsSdkVersion": ""
}
Translation Unit Mappings:
[ /Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c ]:
    /Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c
[ /Users/brian/go/src/github.com/cilium/cilium/bpf/sockops/bpf_redir.c ]:
    /Users/brian/go/src/github.com/cilium/cilium/bpf/sockops/bpf_redir.c
Translation Unit Configurations:
[ /Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c ]:
    Process ID: 55401
    Memory Usage: 24 MB
    Includes:
        /Users/brian/go/src/github.com/cilium/cilium/bpf/include
        /Users/brian/go/src/github.com/cilium/cilium/bpf
        /usr/local/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        SKIP_DEBUG=1
        ENABLE_IPV4=1
        ENABLE_IPV6=1
        ENABLE_HOST_SERVICES_TCP=1
        ENABLE_HOST_SERVICES_UDP=1
        ENABLE_HOST_REDIRECT=1
        ENABLE_ROUTING=1
        NO_REDIRECT=1
        POLICY_VERDICT_NOTIFY=1
        ALLOW_ICMP_FRAG_NEEDED=1
        ENABLE_IDENTITY_MARK=1
        MONITOR_AGGREGATION=3
        CT_REPORT_FLAGS=0x0002
        ENABLE_HOST_FIREWALL=1
        ENABLE_SERVICE_PROTOCOL_DIFFERENTIATION=1
        HAVE_LPM_TRIE_MAP_TYPE=1
        HAVE_LRU_HASH_MAP_TYPE=1
        ENABLE_MASQUERADE=1
        ENABLE_SRC_RANGE_CHECK=1
        ENABLE_NODEPORT=1
        ENABLE_EXTERNAL_IP=1
        ENABLE_NODEPORT_ACCELERATION=1
        ENABLE_SESSION_AFFINITY=1
        ENABLE_DSR_ICMP_ERRORS=1
        ENABLE_DSR=1
        ENABLE_HOSTPORT=1
        ENABLE_LOADBALANCER
        ENABLE_DSR_HYBRID=1
        ENABLE_IPV4_FRAGMENTS=1
        ENCAP_IFINDEX=1
        TUNNEL_MODE=1
        ENABLE_EGRESS_GATEWAY=1
        __NR_CPUS__=10
    Standard Version: c89
    IntelliSense Mode: macos-clang-x64
[ /Users/brian/go/src/github.com/cilium/cilium/bpf/sockops/bpf_redir.c ]:
    Process ID: 55404
    Memory Usage: 19 MB
    Includes:
        /Users/brian/go/src/github.com/cilium/cilium/bpf/include
        /Users/brian/go/src/github.com/cilium/cilium/bpf
        /usr/local/include
    Frameworks:
        /System/Library/Frameworks
        /Library/Frameworks
    Defines:
        __NR_CPUS__=10
        SKIP_DEBUG
        HAVE_LPM_TRIE_MAP_TYPE
        HAVE_LRU_HASH_MAP_TYPE
        ENABLE_IPV4
        ENABLE_IPV6
        ENCAP_IFINDEX=1
        ENABLE_SERVICE_PROTOCOL_DIFFERENTIATION=1
    Standard Version: c89
    IntelliSense Mode: macos-clang-x64
Total Memory Usage: 43 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 153
```
- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
```
sending compilation args for /Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c
  include: /Users/brian/go/src/github.com/cilium/cilium/bpf/include
  include: /Users/brian/go/src/github.com/cilium/cilium/bpf
  include: /usr/local/include
  framework: /System/Library/Frameworks
  framework: /Library/Frameworks
  define: SKIP_DEBUG=1
  define: ENABLE_IPV4=1
  define: ENABLE_IPV6=1
  define: ENABLE_HOST_SERVICES_TCP=1
  define: ENABLE_HOST_SERVICES_UDP=1
  define: ENABLE_HOST_REDIRECT=1
  define: ENABLE_ROUTING=1
  define: NO_REDIRECT=1
  define: POLICY_VERDICT_NOTIFY=1
  define: ALLOW_ICMP_FRAG_NEEDED=1
  define: ENABLE_IDENTITY_MARK=1
  define: MONITOR_AGGREGATION=3
  define: CT_REPORT_FLAGS=0x0002
  define: ENABLE_HOST_FIREWALL=1
  define: ENABLE_SERVICE_PROTOCOL_DIFFERENTIATION=1
  define: HAVE_LPM_TRIE_MAP_TYPE=1
  define: HAVE_LRU_HASH_MAP_TYPE=1
  define: ENABLE_MASQUERADE=1
  define: ENABLE_SRC_RANGE_CHECK=1
  define: ENABLE_NODEPORT=1
  define: ENABLE_EXTERNAL_IP=1
  define: ENABLE_NODEPORT_ACCELERATION=1
  define: ENABLE_SESSION_AFFINITY=1
  define: ENABLE_DSR_ICMP_ERRORS=1
  define: ENABLE_DSR=1
  define: ENABLE_HOSTPORT=1
  define: ENABLE_LOADBALANCER
  define: ENABLE_DSR_HYBRID=1
  define: ENABLE_IPV4_FRAGMENTS=1
  define: ENCAP_IFINDEX=1
  define: TUNNEL_MODE=1
  define: ENABLE_EGRESS_GATEWAY=1
  define: __NR_CPUS__=10
  stdver: c89
  intelliSenseMode: macos-clang-x64
cpptools/getDocumentSymbols: file:///Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c (id: 284)
cpptools/getFoldingRanges: file:///Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c (id: 285)
cpptools/getDocumentSymbols
cpptools/getCodeActions: file:///Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c (id: 286)
Checking for syntax errors: file:///Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c
Checking for syntax errors: file:///Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c
Queueing IntelliSense update for files in translation unit of: /Users/brian/go/src/github.com/cilium/cilium/bpf/bpf_lxc.c
cpptools/finishUpdateSquiggles
Error squiggle count: 246
```

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @briantopping .  I'm trying to repro the issue, but am getting an error (`Cannot read property 'includes' of undefined`) from Makefile Tools when I try to configure the project.  Are you seeing that error?  If not, I'll try again to repro your issue once I resolve my own.  :)

The C/C++ Extension does not actually alter its behavior based directly on whether the standard mode is 'gnu' or not.  It should pass the appropriate value to gcc/clang when querying for system includes and system defines, and it should influence those values (which are then used to configure IntelliSense).  You should be able to confirm the correct value is being passed to clang/gcc based on the log output, as it logs the command line used to query the compiler.  Otherwise, the C/C++ extension does not keep track of the standard's gnu-ness, and it's not reflected in the Log Diagnostics output.

It seems likely that either IntelliSense is not getting configured correctly (by Makefile Tools), or perhaps the errors are occurring with code that the C/C++ extension is failing to parse properly for another reason.  Would it be possible for you to isolate some of those issues (down to just the construct generating the error) to determine whether they can be remedied in a simple project, or persist in a simple project even when configured correctly manually (without Makefile Tools)?

**Comment by briantopping** [comment]
> Hi @briantopping . I'm trying to repro the issue, but am getting an error (Cannot read property 'includes' of undefined) from Makefile Tools when I try to configure the project. Are you seeing that error? If not, I'll try again to repro your issue once I resolve my own. :)

Hi @Colengms thanks for checking this out! Let's focus on a new project per your last request. Hopefully what I have below is a better example.

> The C/C++ Extension does not actually alter its behavior based directly on whether the standard mode is 'gnu' or not. It should pass the appropriate value to gcc/clang when querying for system includes and system defines, and it should influence those values (which are then used to configure IntelliSense). You should be able to confirm the correct value is being passed to clang/gcc based on the log output, as it logs the command line used to query the compiler. Otherwise, the C/C++ extension does not keep track of the standard's gnu-ness, and it's not reflected in the Log Diagnostics output. 

That's probably shouldn't break anything, true?

> It seems likely that either IntelliSense is not getting configured correctly (by Makefile Tools), or perhaps the errors are occurring with code that the C/C++ extension is failing to parse properly for another reason. Would it be possible for you to isolate some of those issues (down to just the construct generating the error) to determine whether they can be remedied in a simple project, or persist in a simple project even when configured correctly manually (without Makefile Tools)?

For context, I am new to eBPF programming in Cilium and thought VSC would be the best IDE for dealing with its multi-language and cross-platform nature. Your point is well-made about the complexity of the Cilium build and I ran across a BPF starter project last night and shows similar issues with the macros that are used, maybe it's a better place to start.

That project is [forked here](https://github.com/briantopping/libbpf-bootstrap) to include a basic `.vscode` directory. I haven't been able to get the `makefile.makeDirectory` to work from `.vscode/settings.json`, so you'll have to add `examples/c` to the `workspace.json` for the project. (Not sure if that's something I should report or I misunderstand some constraints..) I made you a collaborator in case there are changes you want to push without effort. 

With this project, you should be able to `make bootstrap` on Linux and get the header file skeletons, then `Makefile: Configure` in VSC. That will generate the `configurationCache.log`. You'll see that `bootstrap.bpf.c` is generated, but it doesn't render cleanly due to some idiomatic BPF macros. My sense is getting them resolved here will allow them to be resolved in Cilium with the same process. 

I started this with a mind to cross-compile to amd64 Linux from Apple Silicon. That's likely possible with a docker-based build. I'm curious to learn VSC, making this a seamless import and build using Makefile configurations will be a good experience to learn all these tools. (I'm a big believer in "lazy programmer" ethos, so putting in this work now is good...)

How can I help? Thanks!

**Comment by Colengms** [comment]
>similar issues with the macros that are used

Ah, if the issue relates specifically to 'macros', that might be an important clue.  Our tag parser (syntactic parse) that combs the source code for symbols, is not macro aware.  This causes it to skip past portions of code that it cannot understand without better knowledge of the macro.  Some additional information on that issue, and a potential work-around (use of a cpp.hint file) is here: https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-170

**Comment by briantopping** [comment]
Thanks @Colengms, good catch. I'm almost sure that's what's going on here. 

I mentioned above, there are no squiggles in "tag mode" though. Probably a misunderstanding on my end, but thought I would mention it again. No need to explain it, there's not much that we can do to fix it right now.

I'll leave it to you to decide if it's worth closing or is something your team's workflow would like to catalog in an open state. More people are going to find these tools are ideal for this kind of environment, will be a thill to see the parser get beyond this some day! Thanks for great tooling and support! 👍🙏👍
