### ISSUE TITLE
Clear build console and scroll up to top after build

### ISSUE THREAD

**Issue by Ma-XX-oN** [microsoft/vscode-cpptools#8391]
Type: Feature Request

Every time before I build a file/solution, I have to clear the build terminal window and then after, scroll to the top of it to figure out what didn't work.  It would be VERY helpful if this would be done by default.  godbolt.org does this and I've actually started to use this over VSCode just for that feature alone.

**Comment by Colengms** [comment]
Hi @Ma-XX-oN .  Consider opening this feature request in the VS Code repo instead: https://github.com/microsoft/vscode/issues 

The C/C++ extension mainly responds to programmatic requests from VS Code.  The UI functionality you are requesting would most likely need to be implemented on the VS Code side, not in the extension.  Also, what you are suggesting would potentially be desirable for users of other languages.
