### ISSUE TITLE
selected clang-format apparently not being used

### ISSUE THREAD

**Issue by nonchip** [microsoft/vscode-cpptools#8396]
Bug type: Language Service

**Describe the bug**
- OS and Version: `Void Linux`
- VS Code Version: `1.62.0`
- C/C++ Extension Version: `1.7.1`
- Other extensions you installed (and if the issue persists after disabling them): plenty, but it persists if i disable them all

---

After building a new version of `clang-format`, and:
- installing it to `/usr/bin` (which is the version found via `$PATH`, verified with `which`)
- setting its path in the Settings: `C_Cpp.clang_format_path`
- even overwriting the bundled version: `$HOME/.vscode-oss/extensions/ms-vscode.cpptools-1.7.1/LLVM/bin/clang-format`

it seems like the old version is still *somehow* being used instead.

Because i had to update due to new features, if i leave those features out of the config file, it works, but if i enable them, it falls back to a broken default style instead. if i however run `clang-format` from any of the paths above in the terminal, it works as expected.

**Steps to reproduce**
1. Have `clang-format v12` installed system-wide
2. Manually build `clang-format v13` from git
3. Install to `$PATH`, set `C_Cpp.clang_format_path`, and/or even overwrite the bundled version
4. Try to use v13 features in `.clang-format`
5. The whole of `.clang-format` is ignored

**Expected behavior**

v13 features should be used, because clang-format v13 should be used

---

**Code sample and logs**

```yaml
# .clang-format
---
ColumnLimit: '20' # to make it suuuper obvious if the file is used
Language: Cpp
NamespaceIndentation: All
TabWidth: '1'
UseTab: ForIndentation


# the following 2 lines are v13 specific
EmptyLineBeforeAccessModifier: Always
IndentAccessModifiers: 'true'
```

```c++
// example.cpp
namespace {
struct blah {
private:
int this_is_a_rather_long_name = function_call(1, 2, 3, 4, 5);
};
}
```

result in vscode with the 2 v13 lines **commented out**:
```c++
// example.cpp
namespace {
		struct blah {
		private:
				int this_is_a_rather_long_name =
				    function_call(
				        1, 2, 3,
				        4, 5);
		};
} // namespace
```

result in vscode with the 2 v13 lines **left in**:
```c++
// example.cpp
namespace {
struct blah {
private:
  int this_is_a_rather_long_name = function_call(1, 2, 3, 4, 5);
};
} // namespace
```

**this is the same behaviour as if clang-format was still pre-version-13** (= ignoring all the settings in that file while complaining about the new ones) but that should not be possible

---

output of manually running (both from an external and vscode's own terminal) `$clang13-format example.cpp` (with `$clang13-format` being either of the above installation locations) with the 2 v13 lines **left in**:
```c++
// example.cpp
namespace {
		struct blah {
				private:
						int this_is_a_rather_long_name =
						    function_call(
						        1, 2,
						        3, 4,
						        5);
		};
} // namespace
```

**this is the same i would expect in the vscode output above**

**Comment by Colengms** [comment]
Hi @nonchip .  I'm not sure why we would be using an older version, especially if the bundled version was overwritten.  That is definitely odd.  Could you run `which clang-format` to see if there may be other instances of clang-format <13 installed?

The C/C++ extension should use the clang-format instance specified by `C_Cpp.clang_format_path`, no matter what.  All of the logic that might choose another instance is circumvented if a value is seen for `C_Cpp.clang_format_path` .  That logic is here: https://github.com/microsoft/vscode-cpptools/blob/aa53c7181bbed2d441b46a74d07eea40683ebad8/Extension/src/LanguageServer/settings.ts#L87-L89

Perhaps there is something set in one of the clang-format related settings, that differs from what is used when invoking it directly?  Could you check the values you are using for? : `C_Cpp.clang_format_style`, `C_Cpp.clang_format_fallbackStyle`, and `C_Cpp.clang_format_path`

**Comment by nonchip** [comment]
@Colengms

> Could you run `which clang-format`

like i already said, i overwrote the version in `$PATH`:
```
$ which -a clang-format
/usr/bin/clang-format
/usr/sbin/clang-format
/bin/clang-format
/sbin/clang-format
# note /usr/bin, /usr/sbin and /sbin are symlinks to /bin on my distro
$ /usr/bin/clang-format --version
clang-format version 13.0.0 (https://github.com/llvm/llvm-project.git d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
```

> The C/C++ extension should use the clang-format instance specified by `C_Cpp.clang_format_path`, no matter what.

that is how i understood that setting too.

> Could you check the values you are using for? : `C_Cpp.clang_format_style`, `C_Cpp.clang_format_fallbackStyle`, and `C_Cpp.clang_format_path`

```
"C_Cpp.clang_format_style": "file"
"C_Cpp.clang_format_fallbackStyle": "Visual Studio"
"C_Cpp.clang_format_path": "" // also tried with /usr/bin/clang-format and (first) the path to where i built it, as already mentioned
```

---

so yeah, all instances of `clang-format` i can find are the one i want, and *at least*: the one in `$PATH`, the one in `clang_format_path` and the one in `~/.vscode-oss/extensions/ms-vscode.cpptools-1.7.1/LLVM/bin/clang-format` (again, like i stated in the ticket).

**Comment by Colengms** [comment]
Hi @nonchip .

>> The C/C++ extension should use the clang-format instance specified by C_Cpp.clang_format_path, no matter what.
>
> that is how i understood that setting too. but the behaviour seems to disagree.

The code I linked was to an IF statement that bypasses all searching for clang-format when that setting has a value.  :)  The issue would seem to be something other than picking up the wrong instance of clang-format.

Could you enable `"C_Cpp.loggingLevel": "Debug"` then repro the issue, and provide the output from the C/C++ output channel?  That should include the command line that was used to invoke 'clang-format'.

**Comment by nonchip** [comment]
ok sorry for the massive confusion but looking at that debug output you mentioned i realized that *somehow* `clangd/vscode-clangd` actually hooked itself in there and ran its own clang-format through the old version of `clangd` it bundled. doesn't really explain *how* it managed to do that even when i temporarily disabled that extension (maybe i just didn't notice the old clangd instance still running in the background or something), but telling that about my custom clang build actually fixed it. so yeah it's not actually an issue with cpptools.
