### ISSUE TITLE
Cannot debug Linux Mint 17.3

### ISSUE THREAD

**Issue by fsacer** [microsoft/vscode-cpptools#84]
I get **error while processing request 'launch' (exception: Invalid launch option type, is not supported.** while I try to debug on Linux Mint 17.3 with vscode 1.2.1 and C/C++ extension version 0.7.0. I have the following launch.json file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (GDB)",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "x64",
            "program": "${workspaceRoot}/main",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true
        }
    ]
}
```

**Comment by delmyers** [comment]
@fsacer, can you try updating the extension? There was a short lived bug in which this could occur because the we released two binaries that were not in sync.

**Comment by fsacer** [comment]
@delmyers, thanks it works now, just had to remove .vscode folder and readd the config. This can be closed now.
