### ISSUE TITLE
fatal error: 'windows.h' file not found

### ISSUE THREAD

**Issue by gyurmey** [microsoft/vscode-cpptools#8407]
Hi there. i have issue with using some C/C++ extension in vscode. it gives error as above. 
My MacOS catalina version is 10.15.2 and VsCode version is Version: 1.38.1. i have similar error with other header extension such as  conio.h and MMsystem.h etc. i have install mingw-w64 and also did the installation of vcpkg as suggested by vscode but still the error still there -- . any suggestion would be great. thank you in advance "^^"

**Comment by Colengms** [comment]
Hi @gyurmey .  Do I understand correctly that you are running on MacOS, but have installed MinGW in order to target Windows?  If so, I believe you would also need to install/extract a Windows 10 SDK to acquire the header files you are referring to.

**Comment by gyurmey** [comment]
> Hi @gyurmey . Do I understand correctly that you are running on MacOS, but have installed MinGW in order to target Windows? If so, I believe you would also need to install/extract a Windows 10 SDK to acquire the header files you are referring to.

thank you @Colengms for the answer. i have been trying to extract window 10 SDK or find a way to use it in MacOS but haven't found any solution or executable files for MacOS. is there any other way or vscode extension that enable the headers? thank you ^^

**Comment by Colengms** [comment]
Hi @gyurmey .  How did you install MinGW?  It looks like MinGW packages should include Windows headers.  On Ubuntu Linux, `windows.h` is in the following packages:

```
mingw-w64-common
mingw-w64-i686-dev
mingw-w64-x86-64-dev
```

If you already have Windows headers installed, the issue you are seeing might be related to file system and case sensitivity.  On Windows, the file system is (generally) not case sensitive, so a #include of "Windows.h" would find "windows.h".  If the file system on your Mac is case sensitive, you may need to alter some casing used in source code to match the file system.

**Comment by gyurmey** [comment]
> Hi @gyurmey . How did you install MinGW? It looks like MinGW packages should include Windows headers. On Ubuntu Linux, `windows.h` is in the following packages:
> 
> ```
> mingw-w64-common
> mingw-w64-i686-dev
> mingw-w64-x86-64-dev
> ```
> 
> If you already have Windows headers installed, the issue you are seeing might be related to file system and case sensitivity. On Windows, the file system is (generally) not case sensitive, so a #include of "Windows.h" would find "windows.h". If the file system on your Mac is case sensitive, you may need to alter some casing used in source code to match the file system.

thank you again for the answer @Colengms .. i used the command brew install mingw-w64 . i tried to find the path for mingw but couldn't find it. I tried to reinstall but it give warning that it is already installed.

**Comment by Colengms** [comment]
Hi @gyurmey .  I tried using `brew install mingw-w64`.  It prompted me to run `xcode-select --install` and to also install gcc.  That resulted in `windows.h` being found here: `/usr/local/Cellar/mingw-w64/9.0.0_2/toolchain-x86_64/x86_64-w64-mingw32/nclude/windows.h`

I then configured the C/C++ Extension to use `x86_64-w64-mingw32-gcc` by setting `compilerPath` to its path, in `c_cpp_properties.json`.  Then I was able to #include `windows.h` in a source file, without getting any squiggles.

I did the above using Big Sur, but I suspect the process is the same or similar for Catalina.

Is the above enough information to help you solve the issue?

**Comment by gyurmey** [comment]
> Hi @gyurmey . I tried using `brew install mingw-w64`. It prompted me to run `xcode-select --install` and to also install gcc. That resulted in `windows.h` being found here: `/usr/local/Cellar/mingw-w64/9.0.0_2/toolchain-x86_64/x86_64-w64-mingw32/nclude/windows.h`
> 
> I then configured the C/C++ Extension to use `x86_64-w64-mingw32-gcc` by setting `compilerPath` to its path, in `c_cpp_properties.json`. Then I was able to #include `windows.h` in a source file, without getting any squiggles.
> 
> I did the above using Big Sur, but I suspect the process is the same or similar for Catalina.
> 
> Is the above enough information to help you solve the issue?
Thank you so much @Colengms . Now the squiggles are gone and i can go to the definition of the header file as is was not the case earlier. i also found a new compiler path in C/C++ config. but when i run the C/C++ file on vscode, it still give same error on the terminal even the file doesn't have any error warning. ^^ .. i will try to dig deeper into it..  "^_^"

**Comment by Colengms** [comment]
> but when i run the C/C++ file on vscode, it still give same error on the terminal

Could you clarify what you mean by "run the C/C++ file"?  Are you referring to running a particular command line in the terminal, using `Build and Debug Active File`, pressing F5 (`Debug: Start Debugging`), clicking on `Run and Debug`, or something else?  :)

Config values in `c_cpp_properties.json` are used to configure IntelliSense (squiggles, colorization, etc.), and not used directly to compile sources.  The C/C++ extension is separate from (though somewhat connectable to) the various build systems projects might employ (such as Make or CMake) to compile sources.  

If you had previously used one of the various features to Build/Run/Debug a single source file, `tasks.json` and/or `launch.json` files were likely created the first time and persistent, and may need corrections.  However, since you are running on macOS, and MinGW generates executables for Windows, I assume you would be unable to *run* the program directly from VS Code.

**Comment by gyurmey** [comment]
> > but when i run the C/C++ file on vscode, it still give same error on the terminal
> 
> Could you clarify what you mean by "run the C/C++ file"? Are you referring to running a particular command line in the terminal, using `Build and Debug Active File`, pressing F5 (`Debug: Start Debugging`), clicking on `Run and Debug`, or something else? :)
> 
> Config values in `c_cpp_properties.json` are used to configure IntelliSense (squiggles, colorization, etc.), and not used directly to compile sources. The C/C++ extension is separate from (though somewhat connectable to) the various build systems projects might employ (such as Make or CMake) to compile sources.
> 
> If you had previously used one of the various features to Build/Run/Debug a single source file, `tasks.json` and/or `launch.json` files were likely created the first time and persistent, and may need corrections. However, since you are running on macOS, and MinGW generates executables for Windows, I assume you would be unable to _run_ the program directly from VS Code.
Thank you @Colengms for the answer. i have tried running both from Build and Debug Active File command and also vscode run tab. i do have task.json and launch.json. i think windows.h is not supported in MacOS using vscode. i tried in Linux Ubuntu as well and i did the same procedure but result in same error. May be it is only supported in window itself but unfortunately, could not test it ^^ .

**Comment by Colengms** [comment]
Hi @gyurmey .  MinGW stands for "Minimalist GNU for Windows".  You should be able to (cross-)compile with MinGW, but you will not be able to run the program you generate on macOS or Linux.  The program it generates would only run on a Windows PC.  If you would like to build an application for macOS or Linux, I'd suggest using the inbuild versions of clang or gcc on those platforms.

**Comment by gyurmey** [comment]
> Hi @gyurmey . MinGW stands for "Minimalist GNU for Windows". You should be able to (cross-)compile with MinGW, but you will not be able to run the program you generate on macOS or Linux. The program it generates would only run on a Windows PC. If you would like to build an application for macOS or Linux, I'd suggest using the inbuild versions of clang or gcc on those platforms.
thank you so much for thorough discussion and explanation..  @Colengms
