### ISSUE TITLE
Macro intentifier undefined but LS knows definition

### ISSUE THREAD

**Issue by Sirius902** [microsoft/vscode-cpptools#8408]
Bug type: Language Service

- OS: Windows 11
- VS Code Version: 1.62.2
- C/C++ Extension Version: v1.7.1

A macro definition can be considered undefined by the Language Server even though it knows what the macro expands to.

**Steps to reproduce**

The below steps require the the Windows SDK to be installed. If not, the same steps can be followed with the `Remote - WSL` plugin replacing `#include <winsock.h>` with `#include <arpa/inet.h>`, and instead opening the folder using the WSL plugin to reproduce the issue.
1. Create a new folder.
2. Open that folder in VS Code.
3. Create a file called `main.cpp` inside the directory.
4. Open the file and then paste the following code inside:
```cpp
#include <cerrno>
#include <cstring>
#include <iostream>
#include <sstream>
#include <string>
#include <winsock.h>

using namespace std;

int main() {
    cout << AF_INET << endl;
}

```
5. At this point Intellisense should be working as expected, hovering over `AF_INET` should look like this:
![image](https://user-images.githubusercontent.com/10891979/142082818-ce11633c-feee-4010-9153-5bea1e33a751.png)
6. Move the `winsock.h` include to be underneath the `using namespace std;` and then close and re-open `main.cpp`.
7. Checking the `PROBLEMS` tab at the bottom on the same window as the terminal, it now says `identifier "AF_INET" is undefined` and it is underlined in red.
8. Now move the `winsock.h` include back to its original location, then close and re-open the file.
9. At this point the same exact code that was fine in step 5 still has the same `identifier "AF_INET" is undefined` message under
the `PROBLEMS` tab and it is still underlined in red. Hovering over it shows this:
![image](https://user-images.githubusercontent.com/10891979/142083343-744cfa47-db3b-4f3d-bca1-dc998717e645.png)

Once you've reached step 9, no matter how many times you close and re-open `main.cpp` or close the entire folder and re-open it in VS Code, it will continue to behave as in step 9. The strangest part of this is that when you hover over the macro while the error is present, it knows exactly what the definition of the macro looks like and what it expands to, yet claims the identifier is undefined.

**Expected behavior**

The Intellisense should behave as it did after completing step 5 in all steps afterwards. It should not be possible for `AF_INET` to be considered undefined in any of the above shown permutations of the source code, all of them compile and run printing the value of `AF_INET` exactly the same.

**Comment by Colengms** [comment]
Hi @Sirius902 .  Does this issue go away if you disable the IPCH cache by setting `"C_Cpp.intelliSenseCacheSize": 0`?  If so, this may be the same issue as: https://github.com/microsoft/vscode-cpptools/issues/8149

**Comment by Sirius902** [comment]
Yes, the issue seems seems to go away with `"C_Cpp.intelliSenseCacheSize": 0`.

**Comment by Colengms** [comment]
Ok.  I'll close this issue in favor of tracking it with https://github.com/microsoft/vscode-cpptools/issues/8149
