### ISSUE TITLE
The extension should not ask for a cmake file on projects that are not C++

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode-cpptools#8414]
Issue Type: <b>Bug</b>

I work with a lot of codebases, and just a very few of them are C/C++
However, this extension keeps asking me to create Cmake files on every project I open. Ideally the extension should detect the project language and don't bother me with it unless it is an obvious C/C++ project.

Extension version: 1.7.1
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|34, 34, 17|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 3bf10e6d-54c9-4df4-8aaa-781f2b9fc1b9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402016
vsaa593:30376534
vssld246:30401890
vscexrecpromptt3:30400063

```

</details>

**Comment by bobbrow** [comment]
I saw you moved this to the CMake Tools repo. Just wanted to post here as well in case anyone else sees it.  The VS Code team was activating CMake Tools if the search for CMakeLists.txt took "too long" (e.g. more than a few seconds).  They just changed their policy and won't activate CMake Tools in this case anymore.  This fix should be available in VS Code Insiders.

https://github.com/microsoft/vscode/issues/135673#issuecomment-973870861
