### ISSUE TITLE
Include file not found in include path. Unless it was opened already.

### ISSUE THREAD

**Issue by iFreilicht** [microsoft/vscode-cpptools#842]
I'm using the C/C++ and Arduino extension to program for an Arduino Micro.

![Extensions](https://user-images.githubusercontent.com/9742635/27492123-55404ee0-5845-11e7-9be0-e7a29600e73b.PNG)

When opening the Arduino core files, I get error messages like these:

![Includes](https://user-images.githubusercontent.com/9742635/27492024-eadbfce8-5844-11e7-874f-4d2e8f580413.PNG)
![Includes with error message](https://user-images.githubusercontent.com/9742635/27492025-eade803a-5844-11e7-828d-48e3fa2d4423.PNG)

In this example, `inttypes.h`, `stddef.h` and `avr/io.h` all sit in the same parent folder "G:\Programme\Arduino\hardware\tools\avr\avr\include", which is included in my `c_cpp_properties.json`:

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "G:\\Programme\\Arduino\\hardware\\arduino\\avr\\cores\\arduino",
                "G:\\Programme\\Arduino\\hardware\\arduino\\avr\\variants\\micro",
                "G:\\Programme\\Arduino\\hardware\\tools\\avr\\avr\\include"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "path": [
                    "G:\\Programme\\Arduino\\hardware\\arduino\\avr\\cores\\arduino"
                ]
            }
        }
    ]
}
```

I can navigate to that folder and verify that all those files are there. In the case of `inttypes.h`, I even opened the file in VSCode, and after doing that reloading the VSCode window, the red squiggles under any occurence of  `#include <inttypes.h>` vanished. This seems to be 100% repeatable. Even when I then close the file and reload the window, the error won't re-appear.

This leads me to believe that VSCode/Intellisense is somehow caching these files in a hidden location, but doesn't fill up that cache when changes to `c_cpp_properties.json` were made.

I also tried restarting VSCode completely, but that didn't help either. Am I maybe doing something wrong?

**Comment by sean-mcmanus** [comment]
You appear to be using the intelliSenseEngine "Tag Parser", which uses the browse.path setting instead of the "includePath" setting, so it seems like you should add paths to the browse.path.

**Comment by bobbrow** [comment]
What happens if you add `"G:\\Programme\\Arduino\\hardware\\tools\\avr\\lib\\gcc\\avr\\4.9.2\\include"` to your includePath (version number may be different)?

**Comment by iFreilicht** [comment]
@sean-mcmanus that was it
