### ISSUE TITLE
How to Autocomplete headers?

### ISSUE THREAD

**Issue by David-AJ** [microsoft/vscode-cpptools#843]
Actually vscode-cpptools works better than I expected.  But the Autocomplete is really confusing me! I have already added all my `#include` headers into the includePath of `c_cpp_properties.json`, but it still can't auto-complete those headers. How can I do for that?

**Comment by David-AJ** [comment]
BTW, my OS is Windows10 and cpptools version is 0.11.4.

**Comment by sean-mcmanus** [comment]
Autocomplete inside of #include <> or "" isn't implemented yet. I know this issue has been reported before, but I don't know the issue number.

**Comment by David-AJ** [comment]
#802  
I guess I've found that issue.
Thank you, hope you and your team can implement this feature soon!

**Comment by bobbrow** [comment]
Leave a comment
