### ISSUE TITLE
Highlight only perform after jumping code on remote server

### ISSUE THREAD

**Issue by PowerDi** [microsoft/vscode-cpptools#8431]
If I directly open a file (*.cpp), the highlight work unnormally.
![image](https://user-images.githubusercontent.com/15917030/142825162-dfda26a3-5345-476a-a504-02827e3ba242.png)
However, if i click (left + random parameter) to jump to same file, the highlight work normally.
![image](https://user-images.githubusercontent.com/15917030/142825339-f6d657c8-a7ee-4095-ac50-dfb8309afdca.png)
![image](https://user-images.githubusercontent.com/15917030/142825362-845af926-d585-45d5-915f-35b6ea442dbd.png)

**Comment by sean-mcmanus** [comment]
What does "left + random parameter" mean? Are you able to create a complete code sample that repros this? What theme are you using? What is your C_Cpp.enhancedColorization setting, i.e. is it fixed if you change that to "Disabled"?

**Comment by PowerDi** [comment]
> What does "left + random parameter" mean? Are you able to create a complete code sample that repros this? What theme are you using? What is your C_Cpp.enhancedColorization setting, i.e. is it fixed if you change that to "Disabled"?

That means when I use left button on mouse and then click one of variable in the code. It would jump to the same code file but the colorization would be different from directly opening the code file by double click mouse.
It is confused that some projects generated normal colorization, but the projects which created recently generated wrong colorization (Opencv Class).
The theme is One Dark Pro 3.13.2  vscode 1.62.3
The Enhanced Coloraztion setting is Disabled.

**Comment by PowerDi** [comment]
```
int main()
{
    std::cout << "please input template generator type: input 1 for LCR template, input 2 for multiLidar template" << std::endl;
    int generator_type;
    std::cin >> generator_type;
}
```
Created recently project:
![image](https://user-images.githubusercontent.com/15917030/142961375-e59d19ad-491d-4c83-adbb-64bf5500666a.png)
Left button click:
![image](https://user-images.githubusercontent.com/15917030/142961429-746ce97a-cb64-4a59-a4ef-7f9e13a426a1.png)

![image](https://user-images.githubusercontent.com/15917030/142961567-49f8f5f3-5922-43e2-9935-26df9e9839de.png)

**Comment by PowerDi** [comment]
I use CMakeLists.txt to organize the project.
This is the log
[2021-11-23 10:08:33.175] [renderer9] [error] [Extension Host] Error: Error: Command failed: global --encode-path " " -xa std
/bin/sh: 1: global: not found
 `global --encode-path " " -xa std` (exited with error code 127)

**Comment by PowerDi** [comment]
By the Way, in old project 
![image](https://user-images.githubusercontent.com/15917030/142962164-4259afd7-343c-4c85-9df4-e72f6addee06.png)
is wold normally.

But in the new project, the Scopes function can not appear or show "loading" information. 
![image](https://user-images.githubusercontent.com/15917030/142962280-f9c82ade-02a3-4e5c-9459-ce68de86e65b.png)

**Comment by sean-mcmanus** [comment]
This repros with the C/C++ disabled, right? If so, it seems like this is not our bug, but a bug with VS Code.
