### ISSUE TITLE
[feature request] Collapsible outline view

### ISSUE THREAD

**Issue by tarpmaster** [microsoft/vscode-cpptools#8438]
Type: Feature Request

Please make the Explorer:Outline view more customizable.  Being able to filter out object types we don't want to see, or being a collapsible view would be helpful for large files.  

Either that or update the overall interface to allow me to put window panes on another monitor...

**Comment by sean-mcmanus** [comment]
See https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=feature_request.md .

Our extension doesn't provide the Outline view UI, just the C/C++ data to populate it.
