### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by montery8** [microsoft/vscode-cpptools#844]
visual studio code vsersion 1.13.1

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (4663 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (905 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (12081 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Warning: File 'C:\Users\hanmeng\.vscode\extensions\ms-vscode.cpptools-0.11.4\bin\Microsoft.VSCode.CPP.Extension.exe' already exists and was not updated.
Failed at stage: installPackages
Error: invalid local file header signature: 0x16d537e7

Finished

**Comment by sean-mcmanus** [comment]
Can you delete your extension folder and try again?

**Comment by bobbrow** [comment]
Please try to install version 0.12.0 of the extension and let us know if it is still failing for you.

**Comment by montery8** [comment]
It works! Thank you.
