### ISSUE TITLE
Heed /TP in compilerArgs of c_cpp_properties.json to process .c files as C++

### ISSUE THREAD

**Issue by AE1020** [microsoft/vscode-cpptools#8445]
Type: Feature Request

I have some .c files that are able to be compiled as C++.  (Reasonable authority considers it best practices to be able to do so!  See [C++ core guidelines CPL.2](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-cpl))

When compiled as C++ there are some extra defines that kick in.  I manually turn these #defines on during editing for the extra checks they provide, and I would like them to not cause syntax errors in the "Problems" tab of VSCode.  Currently they are causing hundreds of red squigglies (e.g. that it doesn't know what `static_cast` is, since it is treating the .c file as C.)

Searching vscode-cpptools sources (for `".c"`), I found some LanguageServer code that looks like it makes a decision on `fileIsCpp` and `fileIsC`:

https://github.com/microsoft/vscode-cpptools/blob/bf25e3ddb71dd0d6473aca398a2b229284c8611b/Extension/src/LanguageServer/cppBuildTaskProvider.ts#L78-L89

That suggested that if I gave my files an uppercase .C instead of a lowercase .c that it would be willing to treat them as "C and C++".  (I hadn't heard of this convention...)  It indeed does seem that if I rename a file to an uppercase C then the errors in the "Problems" tab go away.

*...but...* I'd rather not use mixed-case filenames.  Could there be instead a check for [/Tc, /Tp, /TC, /TP (Specify Source File Type)](https://docs.microsoft.com/en-us/cpp/build/reference/tc-tp-tc-tp-specify-source-file-type?view=msvc-170) in `compilerArgs` instead?  It's easier to support just /TP and /TC (global options), which would be enough for my case.

(Or is there already a way to do this override that I am not seeing?)

**Comment by sean-mcmanus** [comment]
You can work around the issue via adding
```
"files.associations": {
        "*.c": "cpp",
    },
```
to your settings.json (or user/workspace settings).

**Comment by AE1020** [comment]
>     "files.associations": {
>           "*.c": "cpp",
>       },

Thanks!  (This actually solves my personal issue well enough...)

**Comment by Colengms** [comment]
Keeping this open to track successfully handling /TP (and related args) when specified in `compilerArgs`, or on a command line from `compile_commands.json`, etc.

**Comment by sean-mcmanus** [comment]
I believe this got fixed in 1.12.0. Let us know if it's not fixed and we can re-open it.
