### ISSUE TITLE
Intellisense error in remote Linux cmake environment with clang++ or g++

### ISSUE THREAD

**Issue by akemihomura0105** [microsoft/vscode-cpptools#8446]
Bug type: Language Service

**Describe the bug**
- OS and Version:  Windows10 1969
- VS Code Version:  1.62.3 (system setup)
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Extension Pack,  CMake
- If using SSH remote, specify OS of remote machine: CentOS Linux release 7.4.1708 (Core)
- Bug info: I set the CMAKE_CXX_STANDARD 17 and generate the compile_commands.json, then set it in c_cpp_properties.json. However the intellisense can't search C++14 or higher libraries.

- Code sample

```cpp
#include<iostream>
#include<string_view>
```

- Configurations in `c_cpp_properties.json`
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/home/fan.zhang/tools/llvm/bin/clang",
            "intelliSenseMode": "linux-clang-x64",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}
```
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 11/26/2021, 4:55:09 AM
Version: 1.7.1
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/home/fan.zhang/tools/llvm/bin/clang",
    "intelliSenseMode": "linux-clang-x64",
    "compileCommands": "${workspaceFolder}/build/compile_commands.json",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "cStandard": "gnu17",
    "cppStandard": "gnu++20",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/fan.zhang/vscode_test/main.cpp ]:
    /home/fan.zhang/vscode_test/main.cpp
Translation Unit Configurations:
[ /home/fan.zhang/vscode_test/main.cpp ]:
    Process ID: 347645
    Memory Usage: 46 MB
    Compiler Path: /home/fan.zhang/tools/llvm/bin/clang
    Includes:
        /usr/include/c++/4.8.2
        /usr/include/c++/4.8.2/x86_64-redhat-linux
        /usr/include/c++/4.8.2/backward
        /home/fan.zhang/tools/llvm/lib/clang/14.0.0/include
        /usr/local/include
        /usr/include
    Defines:
        NDEBUG
    Standard Version: c++20
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=140000
    compile_commands.json entry:
        directory: /home/fan.zhang/vscode_test/build
        file: /home/fan.zhang/vscode_test/main.cpp
        command: /opt/tool/gcc-9.1.0/bin/g++ -O3 -DNDEBUG -std=gnu
[vscode_test.zip](https://github.com/microsoft/vscode-cpptools/files/7607933/vscode_test.zip)
++17 -o CMakeFiles/zf_lib.dir/main.cpp.o -c /home/fan.zhang/vscode_test/main.cpp
Total Memory Usage: 46 MB
Browse Paths from compile_commands.json, from workspace folder: /home/fan.zhang/vscode_test
    /home/fan.zhang/vscode_test

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 9407
Number of files parsed: 2
```
- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

![image](https://user-images.githubusercontent.com/43955018/143561783-3de35fe3-2701-40b0-aacb-c55e71fa4392.png)
![image](https://user-images.githubusercontent.com/43955018/143561825-fcd00466-4c7b-4168-a176-b104ab443361.png)
![image](https://user-images.githubusercontent.com/43955018/143561868-7bcdda7e-5450-4df5-ae06-a11fd8d5bffa.png)
![image](https://user-images.githubusercontent.com/43955018/143561916-c324941a-3bb6-4bfa-b82a-7d74d976991e.png)

**Comment by Colengms** [comment]
Hi @akemihomura0105 .  When setting `compileCommands`, it will take precedence over other fields of your `c_cpp_properties.json`.  It looks like the command line in your `compiler_commands.json` file for the file you opened is: 
```
/opt/tool/gcc-9.1.0/bin/g++ -O3 -DNDEBUG -std=gnu++17 -o CMakeFiles/zf_lib.dir/main.cpp.o -c /home/fan.zhang/vscode_test/main.cpp
```

However, there is one exception.  If you have `compilerPath` set, it will override the compiler specified in `compile_commands.json`.  Was it your intention to use clang to get IntelliSense for this file, instead of using the compiler specified in `compile_commands.json`?

All of the following directories were used by IntelliSense to find headers:

```
        /usr/include/c++/4.8.2
        /usr/include/c++/4.8.2/x86_64-redhat-linux
        /usr/include/c++/4.8.2/backward
        /home/fan.zhang/tools/llvm/lib/clang/14.0.0/include
        /usr/local/include
        /usr/include
```

Can you confirm if `string_view` is present in one of these directories?
