### ISSUE TITLE
cpp-tools high CPU and RAM utilization casue losing controll on WSL2

### ISSUE THREAD

**Issue by trzecieu** [microsoft/vscode-cpptools#8448]
Bug type: General

**Describe the bug**
- OS and Version: Windows 10 + WSL2
- VS Code Version: 1.62.3
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
cpp-tools consumes unreasonable amount of resources while working under Windows 10 and connected to WSL2. This is especially painful during compilation of large projects, where it impacts CPU and Memory usage. Frequently leads to `wsl --shutdown` as the only one to reclaim control on the PC. 

![image](https://user-images.githubusercontent.com/4076929/143615663-6eff6a9a-c363-4505-bd4e-003f8d84cf8e.png)

**To Reproduce**
*Please include code sample and `task.json` files.*

**Expected behavior**

- Limit amount of processes that can be spawned by cpp-tools or add some 

**Screenshots**

**Additional context**

**Comment by Colengms** [comment]
Hi @trzecieu .  I'm not sure how to interpret the image you posted.  I assume it's referring to a single process consuming 1.9G.  That may not be unreasonable for a large project.

Only a single instance of 'cpptools' is launched by the extension.  (It may launch multiple instances of `cpptools-srv`, but not `cpptools`).  If that image does indicate multiple instances of cpptools, that would suggest an issue in which instances from previous lauches are not being terminated.  Though, I suspect it's actually a single instance, as the values in some columns are identical.

Could you try enabling `"C_Cpp.loggingLevel": "Debug"` and monitoring the output of the C/C++ output channel for indications of an error?

It's by-design that cpptools will execute (at 100% of 1 CPU core) when it's busy doing tasks such as tag-parsing (indicated by a database icon at the bottom of the window).  If tag parsing is never completing, is it possible your project is making use of symbolic links that are leading to a circular reference?  In that case, `cpptools` may be following those circular references perpetually.

**Comment by trzecieu** [comment]
Thank you for a kind reply. I'm closing that issue as fundamentally it isn't this to fault.  Cheers
