### ISSUE TITLE
Locate symbols wrongly when the cpp file is changed and not saved

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/vscode-cpptools#845]
The C/C++ is very good, but there are some deficiencies.
Symbol Searching works well when the cpp files are saved. like below:
![qq 20170626211826](https://user-images.githubusercontent.com/8075421/27541057-12bab8fe-5ab5-11e7-98ef-feebd5823093.png)
And i changed the file and didn't save, so it is not right, like below:
![qq 20170626212218](https://user-images.githubusercontent.com/8075421/27541201-9c4434ec-5ab5-11e7-9fba-18200a7cfb83.png)
I would like you to fix this. I think you can do it. Because C# plugin doesn't have the same problem.
Additionally, the pulgin doesn't support header files autocomplete, i want to know when will you support it?

**Comment by DFVSQY** [comment]
C/C++ Extension version : 0.11.4
OS : Windows 10 pro

**Comment by szabolcsdombi** [comment]
try saving the file first.
Oh I see the full title now, sorry.
How do you expect external modules to analyze files **not** saved? Where should those collect the necessary data? directly from your editor? then what about having the file open 3 times with three different content?

**Comment by DFVSQY** [comment]
I know it, but i don't want to save frequently.
Sometimes i just want it to be unsaved. I really want you to fix this.

**Comment by DFVSQY** [comment]
What ? 
I just want to locate symbols right when i changed the cpp file and didn't save it. i don't know external modules and don't care it.

**Comment by sean-mcmanus** [comment]
Yeah, I think it would be possible for us to implement. The IntelliSense engine features work without file saving (hover and errorSquiggles). We don't have an ETA yet.

**Comment by bobbrow** [comment]
This is the same as #202

**Comment by sean-mcmanus** [comment]
The saving requirement for symbol updating has been fixed with 0.19.0.
