### ISSUE TITLE
Get  object information before slicing

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8455]
Type: Feature Request

Get object information before slicing. 

Example Code
```

#include <iostream>

class Base
{
    public:
        virtual ~Base(){std::cout << "Base destructor" << std::endl; }

        virtual void say_hello()
        {
            std::cout << "I am the base object" << std::endl;
        }

        double b{1};
};


class Derived: public Base
{
    public:
        ~Derived(){std::cout << "Derived destructor" << std::endl; }
        void say_hello()
        {
            std::cout << "I am the Derived object" << std::endl;
        }
};

void func1(Base& obj)
{
    std::cout << "Hi there"<< std::endl;
    obj.say_hello();
}



int main(int argCount, char *args[])
{


    Base a;
    Derived b;

    func1(a);
    func1(b);

  return 0;
}


When debugging to func1(b) slicing is performed, and I can only see the base part inside the func1. It would be nice to know from which object the slicing is being made.
```

![image](https://user-images.githubusercontent.com/90978953/143794612-0d6eb778-f9a6-4362-8897-17896d8d0a9a.png)

**Comment by WardenGnaw** [comment]
In your `launch.json`, you will want to add a `setupCommands` that will enable GDB to show the most derived type.
E.g.
```json
"setupCommands": [
   {
      "description": "Display derived type",
      "text": "-interpreter-exec console \"set print object on\"",
      "ignoreFailures": true
   }
],
```

This will show up as
![image](https://user-images.githubusercontent.com/3953714/143935406-c2c31816-3e50-4c8b-948a-903e93a596d7.png)


Please note that this will only work with RTTI enabled.

From GDB docs:
>  Note that the virtual function table is required—this feature can only work for objects that have run-time type identification; a single virtual method in the object’s declared type is sufficient.
