### ISSUE TITLE
when i open a project , this extension can will hang all the way

### ISSUE THREAD

**Issue by supermanmsc** [microsoft/vscode-cpptools#8459]
Bug type: Debugger

**Describe the bug**
- OS and Version: mac  12.0.1
- VS Code Version: 1.62
- C/C++ Extension Version: v1.7.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
when i  open this project : https://github.com/deepgrace/monster.git   I can't jump use this extension

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. clone this project https://github.com/deepgrace/monster.git
2. open this project and use goto define function.

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by Colengms** [comment]
Hi @supermanmsc .  The repo you referred to contains a `CMakeLists.txt` file.  Are you using the CMake Tools extension to build this project, and configure the C/C++ extension?  Does the project build successfully using CMake?  IntelliSense involves essentially compiling the source file, so any configuration issues that might be blocking the build may also prevent IntelliSense from working properly.

That said, I'm able to use "Go to Definition" in various places in this project, even without a successful build.  Could you be more specific about how you have things set up, what you tried, what you expected and what you saw instead of what you expected?

You might consider deleting the 1.7.1 extension from: `~/.vscode/extensions` and reinstalling it.  If it was somehow corrupted, it's necessary to delete it from the file system before reinstalling via VS Code, as VS Code will keep the extension around and use the existing copy when reinstalling.

**Comment by supermanmsc** [comment]
Thanks for your attention, I have never build this project , I doesn't installed any cmake extension. 
I have installed vim extension.
I opened a file memoized_invoke.cpp , move cursor to the word memoized_invoke, then press ctrl+] ,
![图片](https://user-images.githubusercontent.com/12078448/144038758-db327584-ca7f-4d6b-b0bf-d7b13fdb0e6f.png)
I expecte take me to the define of memoized_invoke. but it's nothing happend. 
I hava reinstalled   first rm ~/.vscode/extensions/ms-vscode.cpptools, and then install from extension market.
![图片](https://user-images.githubusercontent.com/12078448/144039622-f96e8284-e834-4afe-9103-b1dede71fe03.png)

I have checked my c_cpp_properties.json  
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/include",
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c17",
            "cppStandard": "c++98",
            "intelliSenseMode": "macos-clang-arm64"
        }
    ],
    "version": 4
}

My workspace directory tree:
.
├── CMakeLists.txt
├── Guidelines.md
├── LICENSE_1_0.txt
├── README.md
├── Tutorial.md
├── build.sh
├── example
│   ├── CMakeLists.txt
│   ├── curry
│   ├── curry.cpp
│   ├── curry.dSYM
│   │   └── Contents
│   │       ├── Info.plist
│   │       └── Resources
│   │           └── DWARF
│   │               └── curry
│   ├── is_lambda.cpp
│   ├── memoized_invoke.cpp
│   ├── monster.cpp
│   ├── object_pool.cpp
│   ├── overview.cpp
│   ├── sort_tuple.cpp
│   ├── stream.cpp
│   ├── tensor.cpp
│   ├── thread_pool.cpp
│   ├── tuple_algorithm.cpp
│   ├── unique_tuple.cpp
│   └── ycombinator.cpp
└── include
    ├── arity.hpp
    ├── compiler_detector.hpp
    ├── curry.hpp
    ├── hof.hpp
    ├── is_lambda.hpp
    ├── memoized_invoke.hpp
    ├── monster.hpp
    ├── object_pool.hpp
    ├── ring.hpp
    ├── sort_tuple.hpp
    ├── stream.hpp
    ├── tensor.hpp
    ├── thread_pool.hpp
    ├── to_array.hpp
    ├── tuple_algorithm.hpp
    ├── unique_tuple.hpp
    └── ycombinator.hpp

**Comment by Colengms** [comment]
Hi @supermanmsc .  I think I'm able to repro the issue.  It looks like the extension will lock up when tag parsing `monster.h`.  We've isolated the issue to the following line of code, which the parse never returns from:

```
template <template <typename ...> typename B, typename T>
struct is_base_template_of<B, T, std::void_t<decltype([]<typename... Args>(B<Args...>*){}(std::declval<T*>()))>> : std::true_type {};
```

.. and are working on a fix.  Thanks for reporting this.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders2
