### ISSUE TITLE
Invalid success message when build task fails

### ISSUE THREAD

**Issue by jureid** [microsoft/vscode-cpptools#8467]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 11
- VS Code Version: 1.62.3
- C/C++ Extension Version: 1.7.1
- "Build finished successfully." message showing in Terminal when build fails

**To Reproduce**
1. Clone https://github.com/jureid/simple-fibonacci
2. Open project in VS Code using Developer Command Prompt for VS
3. Run vcpkg install in project directory
4. Open main.cpp and select Run > Start debugging
5. Choose Windows > cl.exe
6. See debugger error (main.exe doesn't exist because the build task failed)
7. Navigate to Terminal and see successful build task message even though it failed to find fmt/format.h
8. If you re-run the build task (Terminal > Run Build Task) you'll see it happen again

![image](https://user-images.githubusercontent.com/44306969/144083899-b85c0bd5-3d10-4936-9076-9f063481b572.png)

**Comment by Colengms** [comment]
This may be related to: https://github.com/microsoft/vscode-cpptools/issues/8467
