### ISSUE TITLE
Be a little puzzled about the intellisense ???

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/vscode-cpptools#847]
![qq 20170627211903](https://user-images.githubusercontent.com/8075421/27589525-54127d40-5b7e-11e7-91e4-4815b18f53b0.png)
Doc says that i need a c_cpp_properties.json file to enable code completion and navigation. But i have code completion and navigation whitout this file, like below:
![qq 20170627212151](https://user-images.githubusercontent.com/8075421/27589642-b715773a-5b7e-11e7-8bcc-e22a53ffbced.png)
![qq 20170627212339](https://user-images.githubusercontent.com/8075421/27589723-fb7f0634-5b7e-11e7-8c8d-b234948c8dd1.png)
My folder doesn't have c_cpp_properties.json file, so why i have code completion and navigation ? 
Please tell me what happened ? THANKS!

**Comment by sean-mcmanus** [comment]
If you don't have the c_cpp_properties.json yet, it uses the default. For the Default IntelliSense engine to work, you'll probably need to add additional includePath settings, but with the Tag Parser engine, the default c_cpp_properties.json is more likely to give results.

**Comment by DFVSQY** [comment]
Thank you for this question. 
I want to know where the default c_cpp_properties.json locate? How does Tag Parser find my visual studio 2017's includepath?
![qq 20170629005047](https://user-images.githubusercontent.com/8075421/27649746-496a160e-5c65-11e7-8cff-7332f65d15cd.png)

**Comment by sean-mcmanus** [comment]
The default is constructed internally by our code. You can create/view it under ${workspaceRoot}/.vsocde by doing a C/Cpp: Edit Configurations command. The Tag Parser uses the browse.path setting in the c_cpp_properties.json. We have code that searches for it to properly set the defaults.
