### ISSUE TITLE
Update images and markdown files in Getting Started walkthrough

### ISSUE THREAD

**Issue by jureid** [microsoft/vscode-cpptools#8470]
Update the media in the C++ Getting Started walkthrough to use new svgs. This issue will be used to track progress and share the new svgs.

**Comment by lydiayschung** [comment]
[c++illustrations.zip](https://github.com/microsoft/vscode-cpptools/files/7636481/c%2B%2Billustrations.zip)
Here are the SVGs!

**Comment by lychung7** [comment]
Here is the updated SVG for the Learn step. This is to align with VS Code's new learn illustration that reduces file size. 
[NewLearn.svg.zip](https://github.com/microsoft/vscode-cpptools/files/7840418/NewLearn.svg.zip)

**Comment by bobbrow** [comment]
Closing in favor of tracking #8304
