### ISSUE TITLE
onWillSaveTextDocument sometimes times out eventually causing save to fail when clang-tidy is running

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8474]
[2021-11-30 14:31:04.891] [exthost] [error] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' threw ERROR
[2021-11-30 14:31:04.891] [exthost] [error] Error: timeout

Not sure what is causing the timeout yet.

After 5 or so timeouts, we no longer get onWillSaveTextDocument messages, which causes the saves to start failing if clang-tidy is running on the file.

I'm not sure of a good repro yet.

**Comment by sean-mcmanus** [comment]
Upvote this if anyone is hitting this and/or add more repro info if anyone finds a good way to reproduce this.

**Comment by mudanzasIPROM** [comment]
https://github.com/microsoft/vscode-cpptools/issues/8474#issuecomment-1016828829

**Comment by mudanzasIPROM** [comment]
> [2021-11-30 14:31:04.891] [exthost] [error] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' arrojó ERROR [2021-11-30 14:31:04.891] [exthost] [error] Error: timeout
> 
> Todavía no estoy seguro de qué está causando el tiempo de espera.
> 
> Después de aproximadamente 5 tiempos de espera, ya no recibimos mensajes en WillSaveTextDocument, lo que hace que los guardados comiencen a fallar si clang-tidy se está ejecutando en el archivo.
> 
> Todavía no estoy seguro de una buena repetición.

**Comment by sean-mcmanus** [comment]
We've improved fixed some issues that could cause onWillSaveTextDocument to be unusually delayed and timeout, so this may no longer be an issue with 1.15.0.
