### ISSUE TITLE
IntelliSense giving errors when C++20 features are used(when it didn't previously) 

### ISSUE THREAD

**Issue by StandingPadAnimations** [microsoft/vscode-cpptools#8475]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.62.3
- C/C++ Extension Version: 1.8.0-insiders
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

In C++20, string_views can be initialized like:
```std::string_view Buffer(Code.begin() + StartIndex, Code.begin() + (EndIndex));```
In previous versions, the C++ extension would not throw errors. However, now I've noticed that I get this error```
no instance of constructor "std::basic_string_view<_CharT, _Traits>::basic_string_view [with _CharT=char, _Traits=std::char_traits<char>]" matches the argument listC/C++(289)
Lexer.cpp(26, 37): argument types are: (__gnu_cxx::__normal_iterator<const char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, __gnu_cxx::__normal_iterator<const char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>)```

My compiler(Msys2 GCC 11.2 64-bit) is C++20 compatible, and the include paths should be fine. I've set the C++ Standard setting to C++20. Plus, I've never had this issue until now

**Steps to reproduce**

1. Open a C++ file
2. Make sure the C++ standard setting is set to C++20
3. Initialize a string_view using ```std::string.begin()``` and ```std::string.end()```
4. Error pops up

**Expected behavior**
Normally, it shouldn't throw an error because it's valid C++20 code 

**Code sample and logs**

- Code sample
```std::string_view Buffer(Code.begin() + StartIndex, Code.begin() + (EndIndex));```
- Configurations in `c_cpp_properties.json
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "C:/C++ and Python programs/EnderKnight Python Port/Rendor/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "gnu17",
            "cppStandard": "c++20",
            "intelliSenseMode": "windows-gcc-x86",
            "compilerPath": "C:/msys64/mingw64/bin/g++.exe"
        }
    ],
    "version": 4
}
```
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 11/30/2021, 8:23:09 PM
Version: 1.8.0-insiders
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "C:/C++ and Python programs/EnderKnight Python Port/Rendor/include"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "cStandard": "gnu17",
    "cppStandard": "c++20",
    "intelliSenseMode": "windows-gcc-x86",
    "compilerPath": "C:/msys64/mingw64/bin/g++.exe",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [
        "-std=c++20"
    ],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "C:/C++ and Python programs/EnderKnight Python Port/Rendor/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\C++ and Python programs\EnderKnight Python Port\Rendor\src\RendorCompiler\Lexer.cpp ]:
    C:\C++ and Python programs\EnderKnight Python Port\Rendor\src\RendorCompiler\Lexer.cpp
Translation Unit Configurations:
[ C:\C++ and Python programs\EnderKnight Python Port\Rendor\src\RendorCompiler\Lexer.cpp ]:
    Process ID: 7644
    Memory Usage: 169 MB
    Compiler Path: C:/msys64/mingw64/bin/g++.exe
    Includes:
        C:\C++ AND PYTHON PROGRAMS\ENDERKNIGHT PYTHON PORT\RENDOR\INCLUDE
        C:\MSYS64\MINGW64\INCLUDE\C++\11.2.0
        C:\MSYS64\MINGW64\INCLUDE\C++\11.2.0\X86_64-W64-MINGW32
        C:\MSYS64\MINGW64\INCLUDE\C++\11.2.0\BACKWARD
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE
        C:\MSYS64\MINGW64\INCLUDE
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE-FIXED
        C:\MSYS64\MINGW64\X86_64-W64-MINGW32\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++20
    IntelliSense Mode: windows-gcc-x86
    Other Flags:
        --g++
        --gnu_version=110200
        --ms_extensions
Total Memory Usage: 169 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 18559
Number of files parsed: 1863
```

**Screenshots**

![image](https://user-images.githubusercontent.com/75058058/144160613-a6135bc9-1a08-4076-8aa1-78e53818fd0e.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
@michelleangela Was an internal bug filed on VS?

**Comment by michelleangela** [comment]
@sean-mcmanus This is fixed in latest internal main build.

**Comment by sean-mcmanus** [comment]
@michelleangela I'm still reproing it -- how did you verify the fix?

**Comment by sean-mcmanus** [comment]
@michelleangela I also repro the bug in the lastest VS 17.1 Preview 3.

**Comment by sean-mcmanus** [comment]
I've filed an internal VS bug -- hopefully they'll be able to get a fix before we release 1.8.0.

**Comment by sean-mcmanus** [comment]
@StandingPadAnimations FYI, you can also work around the bug by adding "-fno-ms-extensions" to compilerArgs if you want to use 1.8.0-insiders2 (assuming you don't have other code that requires that flag to compile). The regression was triggered by a 1.8.0 bug fix that adds -fms-extensions. When this bug gets fixed, you should probably remove the -fno-ms-extensions though.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).

Unless you're explicitly adding -fms-extensions, in which case that bug fix is still pending (https://github.com/microsoft/vscode-cpptools/issues/8353 ).
