### ISSUE TITLE
I hope the intellisense engine can work without file saving

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/vscode-cpptools#848]
When i have a cpp file and don't save it, the errorSuiggle doesn't appear, like below:
![qq 20170627214716](https://user-images.githubusercontent.com/8075421/27590769-4475924c-5b82-11e7-9601-b6203eeba159.png)
The errorSuiggle appears when i save the file, like below:
![qq 20170627214858](https://user-images.githubusercontent.com/8075421/27590835-82e20164-5b82-11e7-8b33-b9ecb9688dc6.png)
So i hope the intellisense engine can give me a error squiggle whitout saving files. THANKS!

**Comment by sean-mcmanus** [comment]
Using the Default "intelliSenseEngine" setting gives errorSquiggles without saving the file. What you appear to be seeing is the Tag Parser showing a squiggle for missing headers, which requires the file to be saved first (https://github.com/Microsoft/vscode-cpptools/issues/845 is tracking that).

**Comment by sean-mcmanus** [comment]
The saving requirement for symbol updating has been fixed with 0.19.0.
