### ISSUE TITLE
c++ can’t  detect the .clang-format and format my code with default style in stead

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8480]
Bug type: General

**Describe the bug**
- OS and Version: Win 7
- VS Code Version: 1.62.3
- C/C++ Extension Version: 1.8.0-insider
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
`.clang-format` is on my workspaceRoot

**Expected behavior**

format using .clang-format style

but it seems that there is no .clang-format and format my code within the default style

**Screenshots**

**Additional context**

**Comment by heartacker** [comment]
work in my win10 pc, and have trouble in my win7 pc

**Comment by michelleangela** [comment]
@heartacker 
Could provide logging of the language server (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) that captures the repro of format issue on Windows 7?

Also, were there any formatting settings configured such as `C_Cpp.clang_format_path` or `C_Cpp.clang_format_style` or `C_Cpp.clang_format_fallbackStyle`?

**Comment by heartacker** [comment]
sorry, i found that it we set to using vcformat in the win7.
