### ISSUE TITLE
Shouldn't wrap lines automatically when formatting

### ISSUE THREAD

**Issue by kriswgc** [microsoft/vscode-cpptools#8482]
Issue Type: <b>Performance Issue</b>

By defualt, shouldn't wrap lines automatically when formatting

Extension version: 1.7.1
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by sean-mcmanus** [comment]
@michelleangela Were you able to repro this? It doesn't repro for me.

@kriswgc Can you provide more repro info? What formatting engine is being used? vcFormat or clangFormat? Can you give an example of code that is wrapped? By default, with clangFormat as the engine the ColumnLimit should be 0 (no limit).
