### ISSUE TITLE
Is it possible to emulate gdb's 'subsitute-path' behavior in the gcc problemMatcher ?

### ISSUE THREAD

**Issue by TTimo** [microsoft/vscode-cpptools#8486]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/8198

<div type='discussions-op-text'>

<sup>Originally posted by **TTimo** September 28, 2021</sup>
I have a build task that uses the gcc problemMatcher, but the output has file paths that need to be transformed in order to match with the source locally.

I haven't found the documentation detailing all the features supported by `fileLocation`; the typical defaults `"autoDetect"` and `"${workspaceFolder}/src"` are not doing me much good atm.

Can I remap the paths or use a regexp in some way? In gdb world, this is what we do: `set substitute-path /data_docker G:/project/src` .. how can I do the same in problemMatcher?</div>

**Comment by Colengms** [comment]
Hi @TTimo .  How exactly do the paths need to be transformed?  Is it a matter of relative paths vs absolute paths?  Is this related to https://github.com/microsoft/vscode-cpptools/issues/7031 ?

Consider opening an issue in the VS Code repo: https://github.com/microsoft/vscode/issues .  The gcc problem matcher is a feature of VS Code itself, and someone in that repo may be more knowledgeable.
