### ISSUE TITLE
Add textmate scope for declarations and definitions

### ISSUE THREAD

**Issue by gracicot** [microsoft/vscode-cpptools#8489]
Type: Feature Request

I tried to create a color theme that all name introduction (like declarations and definitions) are bold. However, it's not possible to unambiguously select all of those.

For example, here's a struct definition and usage:
```cpp
struct MyStruct {}; // 1

MyStruct myInstance; // 2

auto function() -> decltype(myInstance) { // 3
    MyStruct myVar; // 4
    return myVar;
}
```
I tried to make `MyStruct` in `1`, `myInstance` in `2`, `function` in 3, `myVar` in 4 all bold. However, any attempt to make them bold also resulted in `MyStruct` being bold in `2`, but it's a usage of `MyStruct`, not it's definition. Then any attempt to make `myInstance` bold in `2` also resulted in `myInstance` being bold in `3`, but it is also a usage of it, not it's declaration like in `2`. Then, same thing at `4`. Local variable are indistinguishable in declaration and uses.

A solution would be to introduce a new `meta` scope around all name introduction.

Today `myVar` at line `4` have those scopes:

 - `meta.body.function.definition.cpp`
 - `meta.function.definition.cpp`
 - `source.cpp`

And semantic token type `variable` with modifier `local`.

With my proposition, it would look like this:

 - `meta.name-introduction.cpp`
 - `meta.body.function.definition.cpp`
 - `meta.function.definition.cpp`
 - `source.cpp`

That meta scope would surround the name `MyStruct` in `1`, the name `myInstance` in `2`, the name `function` in `3` and the name `myVar` in `4`.

That way, a color theme could highlight declaration and definition differently from uses of a name.

A name can be introduced multiple times. For example:

```cpp
struct MyStruct;

struct MyStruct {
    auto fn() -> void;
};

auto MyStruct::fn() -> void {
   // ...
}
```

Here, both name have a declaration and a definition and no uses.

**Comment by gracicot** [comment]
Ah! It seem other languages supports the semantic token modifier `declaration` and `definition`. It would be great if the cpptools supported those token modifiers so a theme could work with that.

**Comment by Colengms** [comment]
Hi @gracicot .  Thanks for suggesting this.  I think you're asking for semantic tokens, not textmate scopes.  The C/C++ extension does not provide syntactic/lexical colorization using TextMate scopes.  It provides semantic colorization.  Updating the title to reflect.

This is similar to: https://github.com/microsoft/vscode-cpptools/issues/6013
https://developercommunity.visualstudio.com/t/request-that-vc-provide-different-semantic-token-colorization-for-declaration-vs-use/1160898
