### ISSUE TITLE
IntelliSense parsing extremely slow

### ISSUE THREAD

**Issue by xolom** [microsoft/vscode-cpptools#8490]
We have a rather big codebase for our embedded system C++  project. The biggest part are the generated files which represents the hardware in software. Those files are pretty big (11MB and 190k lines) and we need them in almost every translation unit (.cpp file). Parsing one file takes approx 20-30 seconds. As soon as another .cpp file is opened, parsing starts again. Browsing through the code with "Goto definition" is pretty troublesome.
I checked how big the generated IPCH files are and for each .cpp file the cache file is ~1GB, which is too much and therefore i disabled the IntelliSense cache. 
As a trade-off, we now switched over to "Tag Parser" Engine which is way faster, but less accurate.

The question now is: Is it possible to optimize the settings somehow to improve the parsing runtime? Something line using precompiled headers for only manually defined files?

**Comment by sean-mcmanus** [comment]
We have a feature request tracking enabling precompiled headers to improve IntelliSense speed at https://github.com/microsoft/vscode-cpptools/issues/3628 .

**Comment by Colengms** [comment]
Closing duplicate.
