### ISSUE TITLE
could not set locale ".1252" to allow processing of multibyte characters

### ISSUE THREAD

**Issue by Xeenych** [microsoft/vscode-cpptools#8491]
Bug type: General

**Describe the bug**
- OS and Version: Windows 10 21H2
- VS Code Version: 1.62.3
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Opening every .c or .cpp file results in an error in "Problems" tab. Intellisense and code navigation is not working. A few days ago everything worked.
`could not set locale ".1252" to allow processing of multibyte characters`

**Comment by sean-mcmanus** [comment]
The call to setlocale is failing: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-170 . I'm not sure why it would start failing. Seems like some change to your OS may have occurred?
