### ISSUE TITLE
Fail to parse includes from amigaos compiler

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cpptools#8496]
CppTools fails to parse properly the includes when querying the Amiga GCC cross compiler (https://github.com/bebbo/amiga-gcc/releases/tag/y%C3%BCtosikanom%C3%B6)

Example of include with squiggle:
#include <intuition/classes.h>

_Originally posted by @hitman-codehq in https://github.com/microsoft/vscode-makefile-tools/issues/194#issuecomment-985729152_

**Comment by sean-mcmanus** [comment]
@hitman-codehq This should be fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders2 .

**Comment by hitman-codehq** [comment]
Many thanks @sean-mcmanus, this has been driving me crazy for months.  Out of curiosity, what was the problem?  Because what is strange is that the parsing seemed to work *sometimes* but I would expec such a bug be always present or not at all.

I couldn't see any link to a patch set in the issue so I couldn't check myself.

**Comment by Colengms** [comment]
Hi @hitman-codehq .  The issue had to do with the command line required to invoke the compiler to query system includes and system defines.  On Windows, most compilers accept `nul` to indicate no input file.  On Linux/Mac, the equivalent arg is `/dev/null`.  The AmigaOS compiler required use of `/dev/null`.  We've seen this behavior on Windows for compilers intended to emulate Linux/Unix, such as in Cygwin and the GCC bundled with MSYS2.  Those compilers return full unix-like paths for system includes, which need to be remapped to Windows paths.  The AmigaOS compiler, however, returns proper Windows paths.  So, this compiler exhibited a combination of behaviors we have never seen before.  We needed to make some code changes to properly invoke it and parse what it returns.

**Comment by hitman-codehq** [comment]
@Colengms thanks for the info!  Sadly, we are stuck with this UNIX/DOS path differences for ever.  Sometimes I wish someone could go back in a time machine to the days when 86-DOS (the precursor to MS-DOS) was being created and say to its creator "PLEASE!  Use a / and not a \ for path separator!!!"  :-). That would at least be a start.

Too late, we're stuck with it.  Many thanks again for the fix and have a relaxing couple of weeks over the holidays!
