### ISSUE TITLE
Cannot enable default IntelliSenseEngine in workspace when it is disabled in user settings

### ISSUE THREAD

**Issue by travisdowns** [microsoft/vscode-cpptools#8498]
I have intellisense engine set to "Disabled" in my user settings (as I'm often using clangd instead). For some projects, I want to enable IntelliSenseEngine but it doesn't work in the UI. Specifically, I can't set it to "Default" because it seems to think that "Default" is the user setting, so doesn't do a local override in the settings.json. That is, if I select "tag parser" or "disabled" in the workspace settings, it will say "**Also** modified in: User" (i.e., it was overridden at the workspace level), while if I select "Default" it will just say "Modified in: User", indicating that the settings UI thinks the setting is the same as the user setting, and so doesn't do a workspace override. This is wrong because the user setting is "Disabled" not "Default".

Workaround is to manually edit the json to specify Default.

**Comment by sean-mcmanus** [comment]
This is VS Code bug https://github.com/microsoft/vscode/issues/58038. You can upvote that.

**Comment by travisdowns** [comment]
Thanks @sean-mcmanus - although it did blow my mind that this is apparently by design.
