### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tuanlysc** [microsoft/vscode-cpptools#8499]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.8.0-insiders`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.62.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Vanxuan\AppData\Local\Temp\ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
Can you attach the file?
