### ISSUE TITLE
Adopt pre-release extension support

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-cpptools#8507]
Refs: https://github.com/microsoft/vscode/issues/15756

VS Code now supports pre-release extensions. Docs that should help: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions

I know C++ uses the setting to move users to an insiders version.
This is a bit of a special case since you do not have a separate extension so we do not support migration here. However we suggest that C++ does the following for users that have this settings set:
* Show a modal dialog or notification to user where she can confirm the transition
* Once user confirms, execute the command `workbench.extensions.installExtension` and pass `{ installPreReleaseVersion: true }`
* Deprecate the setting

Let me know what you think or if I can help somehow.

fyi @bobbrow @sandy081

**Comment by bobbrow** [comment]
Thanks for opening this @isidorn.  It is in our implementation plan for 1.9.0 (which will be the first pre-release), but I think we forgot to create an issue for it so we will use this one.

**Comment by Colengms** [comment]
@isidorn Could you confirm the format of the call to installExtensions?  I have:

```
vscode.commands.executeCommand("workbench.extensions.installExtension", "ms-vscode.cpptools", { installPreReleaseVersion: true });
```

Is there a way to detect if this type of installation has already been configured?  We could check if we're currently running an Insiders build, but it's possible the user has already switched and not yet reloaded.  (Not critical, but thought I would ask.)

**Comment by isidorn** [comment]
@Colengms that looks like a correct code snippet. But @sandy081 should also confirm.
I think there is no way to detect apart from the idea which you already mentioned: check if you are currently running an insiders build.

**Comment by sandy081** [comment]
Command format is correct 👍 and also confirms what @isidorn mentioned
