### ISSUE TITLE
Syntax highlighting of types not always working

### ISSUE THREAD

**Issue by iFreilicht** [microsoft/vscode-cpptools#851]
When defining a type, it will not be highlighted in variable declarations.

![capture](https://user-images.githubusercontent.com/9742635/27655725-a9b93072-5c46-11e7-887a-6a14dd515cea.PNG)

I'd expect `a_struct` in the last statement to be coloured the same way it is in it's definition.
And as you can see, when mousing over, cpptools clearly knows what it is looking at. Even if it didn't, the first token in this statement unambiguously is a type.

This also happens inside functions. The only types that are highlighted are the ones built in to C++ like `string` or `uint8_t`.

Is this an issue with my setup? Or could this be a bug?

**Comment by bobbrow** [comment]
We haven't implemented any colorization features yet.  We're using #230 to track this.

**Comment by iFreilicht** [comment]
I see, thank you for pointing it out!
