### ISSUE TITLE
Condition breakpoint "strcmp(c-string, "char7")==0" is invalid in debug using VSCode C++ gdb debuger

### ISSUE THREAD

**Issue by 2994186010** [microsoft/vscode-cpptools#8515]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/8509

<div type='discussions-op-text'>

<sup>Originally posted by **2994186010** December  9, 2021</sup>
My example code(testStr.cpp) is as following.
```
#include <iostream>
#include <string>
#include <cstring>
 
using namespace std;
 
int main() {
  char str1[15] = "char";
  string str2 = "string";
  char temp[5];
 
  for(int i=0; i<15; i++) {
    memset(temp, 0, sizeof(temp));
    sprintf(temp, "%d", i);
    strcat(str1, temp);
    cout << str1 << endl;
    str2 = str2 + temp;
    cout << str2 << endl;
  
    strcpy(str1, "char");
    str2 = "string";
  }
 
  return 0;
}
```
The executed commands is as following.
```
g++ /path/testStr.cpp -o /path/testStr
gdb /path/str
b 16 if strcmp(str1, "char4")==0
r
```
It is clear that the above gdb debug process is in the linux shell.
The running program suspend when str1 is char4. The detail is as the following picture.
![gdbincmd](https://user-images.githubusercontent.com/15965075/145405870-f6099052-636d-4bc9-8087-ed3d736c44f2.png)

I set one same condition breakpoint "strcmp(str1, "char4")==0" in the 16th in testStr.cpp in VSCode IDE. The execution result of the program in VSCode is different from the above gdb debug result. The same breakpoint in VSCode seems to be invalid. The program doesn't suspend when str1 is char4 and finishes    all the code lines. The detail is as following.
![debuginVSCode](https://user-images.githubusercontent.com/15965075/145406593-c51bccd8-4a20-4841-b24c-5fe60d6b6bda.png)

</div>

**Comment by WardenGnaw** [comment]
Issue seems to be that the debug adapter is not escaping the double quotes when sending the condition to the debugger.

```
1: (676) <-1014-break-insert -f -c "strcmp(str1, "char4")==0" main.cpp:20
1: (685) ->1014^error,msg="Problem parsing arguments: break-insert -f -c \"strcmp(str1, \"char4\")==0\" main.cpp:20"
```

**Comment by WardenGnaw** [comment]
Fixed in https://github.com/microsoft/MIEngine/pull/1249

**Comment by sean-mcmanus** [comment]
@WardenGnaw Is this fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.2 ?

**Comment by WardenGnaw** [comment]
Yes
