### ISSUE TITLE
Non-ASCII output of `cppbuild` task is corrupted.

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#8518]
This is based on: https://github.com/microsoft/vscode-cpptools/discussions/8514

The C/C++ extension will invoke a build command line directly in `CustomBuildTaskTerminal` in `cppBuildTaskProvider.ts`.  It uses `"shell": true`, and assumes the stdout/stderr of the executed process is UTF-8 encoded.  It passes the text it reads along to VS Code, which displays it in a terminal.  In the case of `cl.exe` on non-US systems (and likely other scenarios), that text is encoded with the current code page, not UTF-8.  The text output to the terminal will appear incorrect if it contains non-ASCII characters.  This is an issue with the "cppbuild" task type but is not an issue for VS Code's "shell" and "process" task types, which it handles internally.

**Comment by LuanVSO** [comment]
maybe there's a way to force MSVC to print utf-8 to the console.
acording to the [docs](https://docs.microsoft.com/en-us/cpp/build/reference/unicode-support-in-the-compiler-and-linker?view=msvc-170) and local testing it is possible to force it to print utf-8 if the output is redirected.
![image](https://user-images.githubusercontent.com/43626415/145660833-32b63ad0-78e4-4bf5-86a1-5d32a3dccccc.png)

**Comment by Colengms** [comment]
@LuanVSO Thanks for the suggestion.  I like that better than my approach.  :)
