### ISSUE TITLE
Need way to force-include files for intellisense

### ISSUE THREAD

**Issue by nwgh** [microsoft/vscode-cpptools#852]
I came across this while trying to work around #661 (I'm on a Mac, building a native app). When building firefox, we force-include <objdir>/mozilla-config.h, which has a significant number of `#define`s (around 150 by my count right now). As it stands, I can copy/paste them from my mozilla-config.h, but this file is auto-generated, and subject to change (at least once per firefox release, every 6 weeks), so that's not the most useful or practical thing to do in the long run. Our command line for building with clang includes `-include /Users/nwgh/src/mozilla/gecko/obj-dbg/mozilla-config.h`. It would be nice to have this same effect in c_cpp_properties.json without having to copy/paste and double-check my work every once in a while.

I'll also note that adding the defines from that file does not actually fix #661 for me, but from reading that issue, it at least seems like the appropriate first step.

**Comment by sean-mcmanus** [comment]
This feature exists in VS 2017 C++ IntelliSense, but it's in the part of the code we haven't ported yet, which we're working on now, but we don't have an ETA, other than it won't be "soon".

**Comment by aenima1891** [comment]
This feature will be very usefull.
Its absence is one of the main reasons that does not make me migrate to VSCode.

**Comment by sean-mcmanus** [comment]
@nwgh @aenima1891 A workaround is to modify the bin/msvc.json file in same folder the Microsoft.VSCode.CPP.Extension process is in by appending code to the "defaults" array like:
`      "-D_USE_DECLSPECS_FOR_SAL=1",
      "--preinclude",
      "F:\\forcedInclude.h"
    ],`
We might be able to add a setting to c_cpp_properties.json in the next release, since that file gets overwritten on updates.

**Comment by nwgh** [comment]
@sean-mcmanus a setting would be great (since I use this for multiple checkouts, some of which may have different definitions in my force-include), but in the meantime, the workaround is awesome! Thanks!

**Comment by aenima1891** [comment]
@sean-mcmanus  Thank you for the reply. I'll be waiting impatiently the c_cpp_properties.json setting, since every project has its own forced include files

**Comment by alex-che** [comment]
By an unfortunate coincidence the force-include is not supported within the compile_commands.json also (#1252).

**Comment by bobbrow** [comment]
We just posted an insider release with support for forced include files.  There is a new `"forcedInclude"` string array property in the **c_cpp_properties.json** configuration schema that you can use to set the forced includes.  If you want to get an early preview, you can install the VSIX that matches your OS.

https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders

**Comment by sean-mcmanus** [comment]
FYI a crash was found if the forcedInclude has a #include reference that can't be found. We're working on a fix: https://github.com/Microsoft/vscode-cpptools/issues/1536 .

**Comment by sean-mcmanus** [comment]
FYI, the crash has been fixed with the latest 0.16.0-insiders.

**Comment by qclzdh** [comment]
not sure what happened, I see this error "Property forceInclude is not allowed."
I am using vscode 1.36.1 in Ubuntu  with C/C++ for Visual Studio Code 0.24.0.
Is there anyone know how to fix this?

**Comment by michelleangela** [comment]
@qclzdh , can you provide your `c_cpp_properties.json` and run `C/C++: Log Diagnostics` command?

**Comment by sean-mcmanus** [comment]
@qclzdh  "forceInclude" should be "forcedInclude".

**Comment by qclzdh** [comment]
@sean-mcmanus Thanks, "forcedInclude" works well now.
