### ISSUE TITLE
Feature Request: Add refactoring to convert string to raw string literal

### ISSUE THREAD

**Issue by contre** [microsoft/vscode-cpptools#8521]
Type: Feature Request

It would be great to get a refactoring to be able to turn a string literal into a raw string literal.

Basically, it'd be great to get this feature in VS Code. https://docs.microsoft.com/en-us/cpp/ide/refactoring/convert-to-raw-string-literal?view=msvc-170

**Comment by sean-mcmanus** [comment]
We're working on unification work with VS that should make this easier to add in the future.
