### ISSUE TITLE
"cwd" in default "task.json" and "launch.json" shoud be "${workspaceFolder}" instead of compiler path

### ISSUE THREAD

**Issue by Kaznov** [microsoft/vscode-cpptools#8524]
Type: Feature Request

By default, when creating a launch.json and task.json for C++ project (build and launch current file), the "cwd" is set to compiler folder. It is at least unexpected behaviour, as I believe it should be either ${fileDirname} or ${workspaceFolder}.

**Comment by KristofHorvath** [comment]
@sean-mcmanus, the ${fileDirname} also could be okay for cwd path. However, now, the compiler's path appears here, e.g. mingw's bin folder. The problem is, that for example, opening a file in write mode creates the new file in the compiler's folder, which is very unexpected behavior, as @Kaznov has written.

**Comment by sean-mcmanus** [comment]
Yeah, but "normally" if the compiler isn't in your path, then it will fail to build the binary, which is a more common problem. What compiler are you using? Does replacing the compiler path with $(fileDirname) successfully build? Does adding the compiler path to the environment path cause the cwd to be the $(fileDirname)?

**Comment by KristofHorvath** [comment]
Sorry, I didn't read the title correctly, and I didn't realize that task.json is also there. I'm talking only about launch.json. Debugging is not related to compiling, so I don't expect that launch.json contains the compiler path anywhere. And this configuration causes the weird behavior that I described earlier.

**Comment by sean-mcmanus** [comment]
Yeah, the same issue with cwd applies for the launch.json to prevent the debugger from failing.

**Comment by KristofHorvath** [comment]
I cannot reproduce the issue on my own computer. Now, `${fileDirname}` appears as `cwd` in `launch.json`. (I discovered the problem with my working computer earlier.) @Kaznov, how about you? Does the problem persist? In that case, could you copy the content of the `launch.json` file here?
