### ISSUE TITLE
Debugging, stop program when variable value changes

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8526]
Hello,

I would like to request the possibility of including a debug break-point when the data of a variable changes. I would guess something similar to the CodeLLDB extension. 

I am inexperienced with vscode, but I can only find stand breakpoints and conditional breakpoints, and this feature would be really helpful to track where are certain variables being changed.

**Comment by WardenGnaw** [comment]
Duplicate: https://github.com/microsoft/vscode-cpptools/issues/1410
