### ISSUE TITLE
Clang++ build tasks not recognised with C++ extension enabled

### ISSUE THREAD

**Issue by Rhahkeem** [microsoft/vscode-cpptools#8527]
Issue Type: <b>Bug</b>

This `tasks.json` file used to work:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: clang++-12 build active file",
            "command": "/usr/bin/clang++-12",
            "args": [
                "-fdiagnostics-color=always",
                "-std=c++17",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ]
}
``` 
previously with the cpp extension enabled (also as evidenced by various posts on the net).

However starting in the last couple days Vscode no longer picks up any build tasks if the C++ extension is enabled. When I disable it then it complains about  ` "type": "cppbuild",`. I then need to update the type to be `process` for it to work, and then my `launch.json` doesn't pick it up and uses the fallback of `g++` instead

Extension version: 1.7.1
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.6.19-050619-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 4169)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.42GB (9.05GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 1484eb56-5798-4939-ab35-9222fc229628|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710cf:30405999
vscexrecpromp3t1:30407762

```

</details>

**Comment by Rhahkeem** [comment]
For further info,  here is my `launch.json`
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++-12 - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: clang++-12 build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```
And I get an error for the `type` here as well
> The debug type is not recognized. Make sure that you have a corresponding debug extension installed and that it is enabled.(1)

**Comment by Rhahkeem** [comment]
Further details. When trying to launch from my launch.json I get this error
```
Error: The cppbuild task detection didn't contribute a task for the following configuration:
{
    "type": "cppbuild",
    "label": "C/C++: clang++-12 build active file",
    "command": "/usr/bin/clang++-12",
    "args": [
        "-fdiagnostics-color=always",
        "-std=c++17",
        "-g",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}"
    ],
    "options": {
        "cwd": "${fileDirname}"
    },
    "problemMatcher": [
        "$gcc"
    ],
    "group": {
        "kind": "build",
        "isDefault": true
    },
    "detail": "Task generated by Debugger."
}
The task will be ignored.
```

**Comment by Colengms** [comment]
Hi @Rhahkeem .  Looking at where VS Code emits that error, it would seem that the C/C++ extension did not register the `cppbuild` provider for some reason.

Can you confirm whether the C/C++ extension is running as expected?  Perhaps set `"C_Cpp.loggingLevel": "Debug"` and check the output of the C/C++ channel to ensure it isn't reporting an error?  Also, can you confirm whether the C/C++ extension is being activated prior to trying to build with the cppbuild task?

You might also consider deleting the C/C++ extension files from your machine (`~/.vscode/extensions`), and reinstalling it?  (It's necessary to delete the files, to ensure VS Code doesn't reuse the existing file when reinstalling an extension).

**Comment by Rhahkeem** [comment]
This somehow started working again. I'm not sure what i ended up tweaking but it seems to be fine. I'll close this out to prevent any clutter. If i ever figure it out I'll update to let other users know
