### ISSUE TITLE
Unexpected token / in JSON at position 1360

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#853]
![image](https://user-images.githubusercontent.com/1297882/27690178-dde059c6-5ce0-11e7-87a7-e93a4cd266a0.png)

Not really sure why it's complaining. Can anyone see it?

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}/Sw/A_XMC/out/obj"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            // "intelliSenseMode": "msvc-x64",
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/um",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/ucrt",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/shared",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.14393.0/winrt"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ]
}
```

**Comment by bobbrow** [comment]
Looks ok to me.  My guess is that you saved it while it was in a bad state and then fixed it later, but hadn't dismissed the message from the previous error.  This happens to me all the time because I am constantly pressing CTL+S.  Press ESC to dismiss the message and save again.  If it works, then you're fine.  If it doesn't work, you should see a red squiggle in the editor highlighting the error.

**Comment by sean-mcmanus** [comment]
The / in the // comment is invalid -- it's not valid JSON. Some of the VS Code JSON files like the settings.json supports the // as an extension to the JSON format, but our c_cpp_properties.json doesn't. If anyone knows a way to use a JSON parser that supports // let us know.

**Comment by csholmq** [comment]
Yes, that was exactly it. Thank you.

**Comment by csholmq** [comment]
Would have been nice if it had pointed out the row. Would have saved me some time.
