### ISSUE TITLE
C_Cpp.clang_format_path won't accept environment variable

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8531]
Bug type: Debugger/Settings

Currently it is not possible to configurate the C_Cpp.clang_format_path with an environment. This was already an issue and fixed, but now it is not working.

**Describe the bug**
- OS and Version: Windows 10 21H1 19043,1348
- VS Code Version: 1.63
- C/C++ Extension Version: 1.7.1

I have different proejcts on different machines, where each machine has a different clang-formatter versions. (mostly older projects). Thats the reason I have stored my CLANG-Path in a custom PATH ($VSC_CLANG_PATH), which will be set on each machine individually.
In my settings.json I have configurated it with the env prefix
`    "C_Cpp.clang_format_path": "${env:VSC_CLANG_PATH}",`

But if I execute the format command I get an error, with an absolut path it is working.

`Formatting failed:
${env:VSC_CLANG_PATH} -style=file -fallback-style=LLVM -assume-filename=/projects/project/main.cpp
Can't find or run process_name
`

There was already an issue for this [https://github.com/microsoft/vscode-cpptools/issues/2344](https://github.com/microsoft/vscode-cpptools/issues/2344)

Should this still work or did I configurate it wrong?
Are there workarounds for this?

**Comment by michelleangela** [comment]
@sean-mcmanus, this may have regressed from the code changes of adding clang-tidy.

**Comment by sean-mcmanus** [comment]
@michelleangela The user is using 1.7.1, right? If so, then it can't be a clang-tidy-related regression, unless it regressed some an intermediate change made for 1.7.1.

I'm seeing the env variable work after a Reload Window is done. It looks like the settings update causes it to break.

**Comment by sean-mcmanus** [comment]
The same bug affects clang-tidy, so I might as well fix it.

**Comment by sean-mcmanus** [comment]
@Marcel-95 I have a fix at https://github.com/microsoft/vscode-cpptools/pull/8538 . However, if you're seeing the bug repro after a Reload Window and no further settings change, then you might be hitting a different bug we don't have a repro for yet.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).
