### ISSUE TITLE
Add support for tricore-gcc IntelliSenseMode

### ISSUE THREAD

**Issue by Siogian** [microsoft/vscode-cpptools#8532]
Type: Feature Request

When i use IntelliSense for cross-compiling, i need select an intelliSenseMode for my compiler, i use tricore-gcc, netheir arm nor x86, i can't select it.

what things is intelliSenseMode do?
If i can customized some items in intellisenseMode when i can't found an selection matched to me, i think it is usefull for me.

**Comment by sean-mcmanus** [comment]
We don't have official support for tricore-gcc, so you should try one of the available modes and see which ones gives the best results. If none of the modes gives good results, we could use this issue to potentially track adding support for that platform.

**Comment by Colengms** [comment]
Possibly related: https://github.com/microsoft/vscode-cpptools/issues/4653
