### ISSUE TITLE
Missing white-spaces around `` in PTB translations

### ISSUE THREAD

**Issue by jogo-** [microsoft/vscode-cpptools#8536]
Bug type: General

In Portuguese Brazilian translations (e.g. Extension/i18n/ptb/package.i18n.json), a lot of white-spaces are missing around the `` and some are misplaced just after the first `.

**Comment by michelleangela** [comment]
@Colengms who's currently fixing localization issues.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).
