### ISSUE TITLE
provide problem matchers for common compilers

### ISSUE THREAD

**Issue by dlech** [microsoft/vscode-cpptools#854]
Please add `contributes.problemMatchers` as described [here](https://code.visualstudio.com/updates/v1_11#_tasks).

**Comment by sean-mcmanus** [comment]
For what build systems? gcc?

**Comment by dlech** [comment]
gcc definitely. Makefile might be useful too. I imagine others might be interested in msvc, but it is not important to me.

**Comment by agauniyal** [comment]
I see this was added in recent changelogs for this plugin, what is it exactly?

**Comment by dlech** [comment]
A problem matcher is something you can add to a task.

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "build",
            "command": "gcc",
            "args": [
                "-g",
                "hello.c"
            ],
            "type": "process",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": "$gcc"
        }
    ]
}
```

It matches errors and warnings in the task output (used to be in the output panel, but now with tasks 2.0 in the terminal panel).

```
> Executing task: gcc hello.c <

hello.c:3:1: warning: return type of 'main' is not 'int' [-Wmain-return-type]
void main(void) {
^
hello.c:3:1: note: change return type to 'int'
void main(void) {
^~~~
int
hello.c:5:2: error: use of undeclared identifier 'syntax'
        syntax error
        ^
1 warning and 1 error generated.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

It uses the information in the matching text to list the items in the problem panels and also indicate them in the source code with squiggles.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/963645/29007944-956f460a-7ad3-11e7-8c05-479239f8fe31.png">

**Comment by dlech** [comment]
Looks like it is working, so closing. Thanks!
