### ISSUE TITLE
Default intellisence engine - can't find a symbol.

### ISSUE THREAD

**Issue by nikitablack** [microsoft/vscode-cpptools#856]
Hello. If you include, for example, [this](https://github.com/eidheim/Simple-WebSocket-Server/blob/master/server_wss.hpp) file and enable default engine, the intellisence will report a lot of false errors. For, example, for this line `using WsServer = SimpleWeb::SocketServer<SimpleWeb::WS>;` it tells `namespace "SimpleWeb" has no member "SocketServer"`, thought it's there and the code can be compiled and run.

**Comment by bobbrow** [comment]
Hmm... I don't repro.  My c_cpp_properties.json looks like this:

```
            "includePath": [
                "${workspaceRoot}",
                "${workspaceRoot}/../openssl/include",
                "${workspaceRoot}/../boost_1_63_0",
                <system_includes>,

            "browse": {
                "path": [
                    "${workspaceRoot}/../openssl/include",
                    "${workspaceRoot}/../boost_1_63_0",
                    <system_includes>,
```

![nikita](https://user-images.githubusercontent.com/12818240/27742658-5704dc2c-5d6e-11e7-8bd4-ffa68805d341.png)

**Comment by nikitablack** [comment]
Ok, sorry. The include path for boost was wrong, though vscode was silent about that. Now everything fine.
