### ISSUE TITLE
"Too many errors for the IntelliSense engine"/"No IL available" on native project

### ISSUE THREAD

**Issue by nwgh** [microsoft/vscode-cpptools#857]
I was originally following #661 for this, but that one seems to have been repurposed to be ARM-specific, so I'm filing a new issue, as I'm seeing this on OS X, with a project targeting my native machine.

When working with mozilla-central (https://hg.mozilla.org/mozilla-central), I get the error message "Too many errors for the IntelliSense engine. Compiler exited with error - No IL available" on any of my c++ files. Using the directions in the aforementioned issue, I upped the error limit for my cpptools extension, and saw a lot of parsing errors in code that compiles just fine (with gcc, clang, and msvc).

<img width="1440" alt="screen shot 2017-06-30 at 11 55 42" src="https://user-images.githubusercontent.com/98339/27750082-2469d458-5d8b-11e7-930b-0943fee60467.png">

Above is an example of one of the problems seen when upping the error limit. The macro that is underlined expands to a function definition (which shows up just fine in the code lens when I hover over it). I imagine some of these other errors are cascading failures from previous errors getting the compiler in a bad state, but I'm not sure.

**Comment by bobbrow** [comment]
Yes, I repurposed that issue since the error itself is quite generic and this makes it easier for us to track the actual issue causing it.  We will likely rename this issue as well once we identify the root cause.  Perhaps we should also create a feature request issue to expose an easier way to increase the error limit.

Can you share your c_cpp_properties.json file?  I have downloaded the Mozilla source code, but don't really know where to start as far as the include paths go.

**Comment by nwgh** [comment]
Sure thing! My c_cpp_properties.json is at https://gist.github.com/nwgh/1b0a179d2f6919a305393c8a894c6068

Note that the vast majority of the defines in there are copy/pasted from the mozilla-config.h that gets autogenerated by the build system (I filed #852 to not have to do this, since they could change at will). The rest came from the output of `./mach compile-flags <filename>` inside the firefox directory. Both of these need a properly-configured build environment.

If you would like to see my build config, I keep it in https://github.com/nwgh/mozconfigs (I have the environment variable `MOZCONFIG` set to the full path of `mac_debug` in that directory, and `MOZCONFIG_ROOT` set to the directory created by cloning that repo). I don't use a `.mozconfig` file in the source directory. In case you need them, full build instructions for firefox are at https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions

**Comment by nwgh** [comment]
One thing I forgot to note - you will need to build firefox once for those include paths to work. Most of them are (as you may be able to tell) in the objdir, which doesn't appear until there are objs to put in a dir! :)

**Comment by bobbrow** [comment]
I just tried this file on Windows (because it's easier for me to debug and I already had the source downloaded) with the bulk of your c_cpp_properties.json file intact.  One error I saw was that `"FIREFOX_VERSION 56.0a1"` is missing the `=` in your `"defines"` array.  I also couldn't find `"semaphore.h"`, but I disabled the tag parser fallback option and only saw 2 other errors in the problems window.

Can you fix that define and try again?  If you are still having trouble after that, I can go download the code and build on a Mac.

**Comment by nwgh** [comment]
*facepalm* thanks for catching that missing `=` sign. Unfortunately, though, I still see the same errors on my mac. I'll finally have access to my linux & win10 machines again later today, so I'll see if I can reproduce on those OSes to try to help narrow it down to "problem with mac" or "problem with something else in my setup".

**Comment by bobbrow** [comment]
I downloaded the source and kicked off a build of Mozilla before I left work on Monday.  I have a repro of your issue on Mac and I'll take a look.

**Comment by bobbrow** [comment]
Interesting.  When I hover over types, it appears that IntelliSense thinks the mozilla namespace lives inside `std::__1` for some reason.  So I see `std::__1::mozilla` in a lot of places.

**Comment by nwgh** [comment]
Hrm, indeed, I'm seeing that, too. Thinking about it for a second, I wonder if that has to do with some of my include paths (I had to do some deep digging to find a few of the includes, as they didn't live under /usr/include as I would've expected).

A quick grep shows `std::__1` being defined in `/Library/Developer/CommandLineTools/usr/include/c++/v1` so I wonder if there's a bug in one of apple's headers there that never closes the namespace. I'll try installing a clang straight from llvm.org and pointing the headers there to see if that issue persists.

**Comment by bobbrow** [comment]
Removing the "defines" in the c_cpp_properties.json and directly including mozilla-config.h in Http2Session.cpp resolved that issue for me so I can look at the other errors.  I suspect there may be some other issue with the "defines" causing the namespace to not be closed.

**Comment by bobbrow** [comment]
Ok, this is looking like a configuration issue to me.  I started fresh with a new c_cpp_properties.json that matches the output of `clang -v -E -x c++ - < /dev/null` and then added the mozilla paths in and IntelliSense only reported two errors about redefinitions of CreateFrameHeader for me.  Can you confirm whether the system include paths in the config you shared match the output of that command on your Mac? 

I ran this command using two different versions of Clang, the one that was installed with Xcode and version 3.9 which I had downloaded a while ago.  This is what my configs look like for each of those versions of Clang and each of them get me the same result (2 errors in IntelliSense):

```
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}",
                "${workspaceRoot}/netwerk/base",
                "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include",
                "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include/nspr",
                "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/ipc/ipdl/_ipdlheaders",
                "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include/nss",
                "${workspaceRoot}/ipc/chromium/src",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/usr/local/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/usr/include/machine",
                "/usr/include"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}/netwerk/base",
                    "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include",
                    "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include/nspr",
                    "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/ipc/ipdl/_ipdlheaders",
                    "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include/nss",
                    "${workspaceRoot}/ipc/chromium/src",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                    "/usr/local/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                    "/usr/include/machine",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
```
```
        {
            "name": "Mac",
            "includePath": [
                "${workspaceRoot}",
                "${workspaceRoot}/netwerk/base",
                "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include",
                "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include/nspr",
                "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/ipc/ipdl/_ipdlheaders",
                "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include/nss",
                "${workspaceRoot}/ipc/chromium/src",
                "/Users/cpptools/tools/clang-3.9.0/bin/../include/c++/v1",
                "/usr/local/include",
                "/Users/cpptools/tools/clang-3.9.0/bin/../lib/clang/3.9.0/include",
                "/usr/include/machine",
                "/usr/include"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceRoot}/netwerk/base",
                    "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include",
                    "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include/nspr",
                    "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/ipc/ipdl/_ipdlheaders",
                    "${workspaceRoot}/obj-x86_64-apple-darwin16.5.0/dist/include/nss",
                    "${workspaceRoot}/ipc/chromium/src",
                    "/Users/cpptools/tools/clang-3.9.0/bin/../include/c++/v1",
                    "/usr/local/include",
                    "/Users/cpptools/tools/clang-3.9.0/bin/../lib/clang/3.9.0/include",
                    "/usr/include/machine",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
```

**Comment by nwgh** [comment]
OK, so leaving the `defines` section out, explicitly `#include`ing `mozilla-config.h` and using the above method to figure out the appropriate include directories, I confirm that the only errors I see are the ones about CreateFrameHeader being redefined.

I'll see what happens when I add back in the `defines` section.

(I'm also wondering if we still need those multiple definitions of CreateFrameHeader - I don't know if any of our supported compilers care about char* vs uint8_t* any more, but that's for me to dig into - could still be a nice-to-have for code if it turns out we still need both of those instantiations.)

**Comment by nwgh** [comment]
So it looks like adding the `defines` back in (and not explicitly `#include`ing `mozilla-config.h`) now has the same effect as the other way 'round (including not having the strange `std::__1` namespace). So this seems to be in a good state now.

I'm happy to let this issue be closed, and I can open a new issue if the error about `CreateFrameHeader` is something that still needs fixing on code's end (after I run some tests with our supported compilers to see if I can just get rid of that second instantiation.)

Thanks for all your help on this, @bobbrow !

**Comment by sillykelvin** [comment]
@nwgh Could you please share that how to enlarge the error size limitation? I don't see there is an option in the C/C++ Configuration section. Thank you.

I also have the "too many errors" problem, but only some source files, not all, so I want to check what's wrong with these files.

**Comment by sean-mcmanus** [comment]
@kelvinh There isn't a way to enlarge the error size limitation. The "too many errors" usually occurs when there's some configuration error with the includePath and defines. Can you open a new issue with more repro details regarding your c_cpp_properties.json settings?

**Comment by sillykelvin** [comment]
@sean-mcmanus Sorry, the project is a private project, I cannot post any source code here, so a new issue would not help. And as I said, the "too many errors" **only occur with some source files**, the others work well, so I think this might not be a configuration problem, however, the following is my c_cpp_properties.json and user settings that might provide some helpful information:

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include/c++/5.4.0",
                "/usr/include/x86_64-linux-gnu/c++/5.4.0",
                "/usr/local/include",
                "/usr/lib/clang/3.8.0/include",
                "/usr/include",
                "/usr/include/x86_64-linux-gnu",
                "${workspaceRoot}",
                "${workspaceRoot}/auth",
                "${workspaceRoot}/bus",
                "${workspaceRoot}/chat",
                "${workspaceRoot}/common",
                "${workspaceRoot}/dbproxy/api",
                "${workspaceRoot}/dbproxy/service",
                "${workspaceRoot}/deps/curl/include",
                "${workspaceRoot}/deps/gdk/include",
                "${workspaceRoot}/deps/hiredis/include",
                "${workspaceRoot}/deps/libuv/include",
                "${workspaceRoot}/deps/json/include",
                "${workspaceRoot}/deps/protobuf/include",
                "${workspaceRoot}/deps/readline/include",
                "${workspaceRoot}/deps/spdlog/include",
                "${workspaceRoot}/deps/pugixml/include",
                "${workspaceRoot}/gate",
                "${workspaceRoot}/idip",
                "${workspaceRoot}/libsk",
                "${workspaceRoot}/match",
                "${workspaceRoot}/monitor/agent",
                "${workspaceRoot}/monitor/api",
                "${workspaceRoot}/monitor/console",
                "${workspaceRoot}/proto",
                "${workspaceRoot}/rank",
                "${workspaceRoot}/resource",
                "${workspaceRoot}/room",
                "${workspaceRoot}/schema/game",
                "${workspaceRoot}/schema/oss",
                "${workspaceRoot}/service/center",
                "${workspaceRoot}/service/client",
                "${workspaceRoot}/world",
                "${workspaceRoot}/world/bag",
                "${workspaceRoot}/world/basic",
                "${workspaceRoot}/world/battle",
                "${workspaceRoot}/world/chat",
                "${workspaceRoot}/world/gmcmd",
                "${workspaceRoot}/world/guide",
                "${workspaceRoot}/world/idip",
                "${workspaceRoot}/world/login",
                "${workspaceRoot}/world/mail",
                "${workspaceRoot}/world/rank",
                "${workspaceRoot}/world/rela",
                "${workspaceRoot}/world/role",
                "${workspaceRoot}/world/setting",
                "${workspaceRoot}/world/shop",
                "${workspaceRoot}/world/signin",
                "${workspaceRoot}/world/task"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/usr/include/c++/5.4.0",
                    "/usr/include/x86_64-linux-gnu/c++/5.4.0",
                    "/usr/local/include",
                    "/usr/lib/clang/3.8.0/include",
                    "/usr/include",
                    "/usr/include/x86_64-linux-gnu",
                    "${workspaceRoot}",
                    "${workspaceRoot}/auth",
                    "${workspaceRoot}/bus",
                    "${workspaceRoot}/chat",
                    "${workspaceRoot}/common",
                    "${workspaceRoot}/dbproxy/api",
                    "${workspaceRoot}/dbproxy/service",
                    "${workspaceRoot}/deps/curl/include",
                    "${workspaceRoot}/deps/gdk/include",
                    "${workspaceRoot}/deps/hiredis/include",
                    "${workspaceRoot}/deps/libuv/include",
                    "${workspaceRoot}/deps/json/include",
                    "${workspaceRoot}/deps/protobuf/include",
                    "${workspaceRoot}/deps/readline/include",
                    "${workspaceRoot}/deps/spdlog/include",
                    "${workspaceRoot}/deps/pugixml/include",
                    "${workspaceRoot}/gate",
                    "${workspaceRoot}/idip",
                    "${workspaceRoot}/libsk",
                    "${workspaceRoot}/match",
                    "${workspaceRoot}/monitor/agent",
                    "${workspaceRoot}/monitor/api",
                    "${workspaceRoot}/monitor/console",
                    "${workspaceRoot}/proto",
                    "${workspaceRoot}/rank",
                    "${workspaceRoot}/resource",
                    "${workspaceRoot}/room",
                    "${workspaceRoot}/schema/game",
                    "${workspaceRoot}/schema/oss",
                    "${workspaceRoot}/service/center",
                    "${workspaceRoot}/service/client",
                    "${workspaceRoot}/world",
                    "${workspaceRoot}/world/bag",
                    "${workspaceRoot}/world/basic",
                    "${workspaceRoot}/world/battle",
                    "${workspaceRoot}/world/chat",
                    "${workspaceRoot}/world/gmcmd",
                    "${workspaceRoot}/world/guide",
                    "${workspaceRoot}/world/idip",
                    "${workspaceRoot}/world/login",
                    "${workspaceRoot}/world/mail",
                    "${workspaceRoot}/world/rank",
                    "${workspaceRoot}/world/rela",
                    "${workspaceRoot}/world/role",
                    "${workspaceRoot}/world/setting",
                    "${workspaceRoot}/world/shop",
                    "${workspaceRoot}/world/signin",
                    "${workspaceRoot}/world/task"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 3
}
```

```
"C_Cpp.intelliSenseEngine": "Default",
"C_Cpp.loggingLevel": "Information",
"C_Cpp.clang_format_path": "/usr/bin/clang-format"
```

**Comment by bobbrow** [comment]
Actually, there is a way to bump up the error limit, but we don't expose a setting for it yet.

Edit `~/.vscode/extensions/ms-vscode.cpptools-0.14.0/bin/msvc.json` by adding `"--error_limit"`, `"5000"` to the **"defaults"** array (two separate items).  This will raise the error limit for the IntelliSense engine.  VS Code won't show you more than 250 at a time though.

If you find anything that looks like a bug, please open a new issue.  This one is closed.

**Comment by sillykelvin** [comment]
@bobbrow Thanks for the information, I will try and update later.
