### ISSUE TITLE
Printing to the Debug Console adds '@"' to the start of every line, and prints newline characters at the end.

### ISSUE THREAD

**Issue by ImJimmi** [microsoft/vscode-cpptools#8576]
Bug type: Debugger

**Describe the bug**
- OS and Version: macOS 12.0.1
- VS Code Version: 1.63.1
- C/C++ Extension Version: v1.8.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): N/A
- A clear and concise description of what the bug is.

Printing anything to the Debug Console from a C++ app running in VSCode adds a `@` character to the start of every line, ends every line with the raw newline characters (e.g. "\r\n") and wraps the whole line in quotes.

This bug is even visible in one of the tutorials on the VSCode youtube channel (from 4:33): https://www.youtube.com/watch?v=G9gnSGKYIg4&t=1s&ab_channel=VisualStudioCode

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
```cpp
std::cout << "Hello, World!" << std::endl;

// Outputs:
@"Hello, World!\r\n"

// Expected Output:
Hello, World!
```

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${default}",
                "some paths..."
            ],
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${command:cmake.launchTargetPath}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [
                {
                    "name": "PATH",
                    "value": "$PATH:${command:cmake.launchTargetDirectory}"
                }
            ],
            "MIMode": "lldb",
            "logging": {
                "moduleLoad": false
            }
        }
    ]
}
```

**Comment by WardenGnaw** [comment]
Since this is not occurring on the gdb side, it may be a bug in lldb-mi. But first investigating the differences.
