### ISSUE TITLE
Syntax hightlighting issue

### ISSUE THREAD

**Issue by Leedehai** [microsoft/vscode-cpptools#858]
Problem 1: Class name hightlighting is not handled properly if namespace is involved:
![image](https://user-images.githubusercontent.com/18319900/27766540-289f241c-5e88-11e7-8b89-265c85088812.png)
Here, "InternalException" is the class name, not "hcc" (it is the namespace)
While other IDEs, like CLion, can properly handle it.

Problem 2: custom type not highlighted when used to declare an object:
![image](https://user-images.githubusercontent.com/18319900/27766552-a0129b14-5e88-11e7-88e5-1207feba1116.png)
Here "MyStruct" should be highlighted. But maybe this Problem 2 is a big ask, as the definition of MyStruct type might not be in the same file.

Maybe I filed this issue to the wrong recipient? Please let me know if this issue should go to the VSCode team instead. I really want VSCode to succeed :)

**Comment by bobbrow** [comment]
Thank you for your feedback.  It helps us to prioritize feature requests.  What you are seeing is actually Atom's colorizer.  Our extension doesn't provide any colorization support yet.  We are tracking this request via #230.

**Comment by Leedehai** [comment]
Suggestion: a Visual Studio 2010 Extension (Highlighterr [here](http://highlighterr.codeplex.com), open source GPLv2) supports this feature. By IntelliSense engine it can detect the names for custom classes, structs, typedefs, etc. and highlights them correctly. I believe this feature will be a great selling point (though VSCode is open source.. :) )

**Comment by sean-mcmanus** [comment]
VS 2010/2015/2017 support C++ syntax highlighting for custom classes without an extension. The UI model for implementing the colorization is different from VS and VS Code, so the code from VS can't be easily re-used. In other words, VS will actually make calls into an extension saying "what is the type for colorization", but in VS Code, we don't get any requests like that, and it's implemented via TextMate and atom/language-c (grammars defined in json files), i.e. see files under C:\Program Files\Microsoft VS Code\resources\app\extensions\cpp .
