### ISSUE TITLE
(C) VLA recognized as a bug in v1.8.0-insiders2

### ISSUE THREAD

**Issue by patrykkozuch** [microsoft/vscode-cpptools#8581]
Bug type: Language Service - Intellisens recognizes VLA as a bug

**Describe the bug**
- OS and Version: Windows 11
- VS Code Version: 1.63.2
- C/C++ Extension Version: v1.8.0-insiders2

**Steps to reproduce**
After creating VLA in C (C89 standard) IntelliSense marks every use of Variable Length Arrays as an error.

**Code sample and logs**
```c
#include <stdlib.h>
#include <stdio.h>

void bubblesort(int k, int n, char p1[][k]); /* Line marked as "a parameter is not allowed" */

int main(void)
{
    int n, l;
    scanf(" %d", &n);
    scanf(" %d", &l);

    char tab[n][l]; /*This line is marked as "expression must have constant value" */
    return 0;
}
```

- Configurations in `c_cpp_properties.json`:  none

**Additional context**
It works well with v1.7.1, but after switching to Insiders channel IntelliSense shows errors.

**Comment by Colengms** [comment]
Hi @rico305 .  Are you using a GCC compiler/IntelliSenseMode?  I'm able to repro the issue if I use GCC on Windows.  In my case, the issue appears to be related to `-fms-extensions` (which should be enabled by default for Cygwin and MinGW).  We had 'fixed' this in v1.8.0-insider2, but it exposed some other issues.  If this is what you are encountering, you should be able to work around it by adding a `compilerArg` of `-fno-ms-extensions`.  We plan to disable `-fms-extensions` for MinGW and Cygwin in the next insiders/release, until we can address the immediate issues.  Re-enabling it is then tracked by: https://github.com/microsoft/vscode-cpptools/issues/8353   I've opened a bug internally against VS related to `-fms-extensions` breaking VLAs.  (The C/C++ extension shares the IntelliSense implementation with VS).

**Comment by rico305** [comment]
Yes, I use GCC compiler - MinGW under Windows. You're right - adding `-fno-ms-extensions` to `compilerArg` works. Thank's for your attention!

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).

Unless you're explicitly adding -fms-extensions, in which case that bug fix is still pending (https://github.com/microsoft/vscode-cpptools/issues/8353 ).
