### ISSUE TITLE
Upstream pevents changes, early testing or feedback requested

### ISSUE THREAD

**Issue by mqudsi** [microsoft/vscode-cpptools#8582]
Hello team,

I'm the author of [pevents](https://github.com/neosmart/pevents/), the WIN32 manual/auto-reset events library for Linux. To my knowledge, VS Code is (or was) one of the bigger projects depending on pevents; iirc it was used in some of the language-specific extensions.

There's [a fairly large change](https://github.com/neosmart/pevents/pull/20) that's been finalized and is ready for merging into master that improves the determinism of the API on non-Windows hosts to match the Win32 behavior, but I was wondering if someone from the team working on the extensions that use pevents could get in touch. Presumably your project has some LSP unit/integration tests that cover multithreaded synchronization; it would be great if I could get an all-ok that everything continues to work fine with the latest changes. Given the nature of multithreaded code (especially with optimizations enabled) it's extremely tricky to validate architectural changes to synchronization primitives, even with all the unit and regression tests passing on our end. Having further real-world verification would be great, and in case any issues arise, hopefully it would be better than you guys updating to master and having your production release randomly fail.

(This request previous incorrectly filed [under the main VSCode project](https://github.com/microsoft/vscode/issues/130191).)

**Comment by Colengms** [comment]
Hi @mqudsi .  I don't believe the C/C++ extension currently makes use of `pevents`.  It had been used at one time, in an area of the code that has since been refactored.  I no longer see any sign of `pevents` or `neosmart` use in our native codebase.

Thanks so much for your efforts.  I'm sorry we can't be of more help.

**Comment by mqudsi** [comment]
Thanks for clarifying, @Colengms.
