### ISSUE TITLE
Cannot build and debug because the active file is not a C or C++ source file.

### ISSUE THREAD

**Issue by Kemal321** [microsoft/vscode-cpptools#8586]
I start to use VS Code. I followed "https://code.visualstudio.com/docs/cpp/config-mingw" but when I choose Ctrl+Shift+B or from the Terminal main menu Run Build Task. I take error . " Cannot build and debug because the active file is not a C or C++ source file.
The terminal process failed to launch (exit code: -1). "
My task.json config.
` {
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\msys64\\mingw64\\bin\\g++.exe",
			"args": [
				"-fdiagnostics-color=always",
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${fileDirname}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: C:\\msys64\\mingw64\\bin\\g++.exe"
		}
	]
} `

**Comment by sean-mcmanus** [comment]
What is the active file?

**Comment by Ignatij3** [comment]
Hello! I have the same issue. When I select .cpp file as active it compiles fine, but when I switch to .hpp or any other file really (even though compilation process is not dependent on active file) it shows exactly that error. I tried searching debugger and C/C++ extension, but found nothing.

**Comment by sean-mcmanus** [comment]
@Ignatij3 That is "by design" with the "Build and Debug Active File" feature. You'd have to modify the tasks.json to build differently or use another method building.

**Comment by Ignatij3** [comment]
@sean-mcmanus Could you, please, provide example of how to build anywhere I want?

**Comment by Ignatij3** [comment]
> @sean-mcmanus Could you, please, provide example of how to build anywhere I want?

Or rather what changes exactly I need to make

**Comment by sean-mcmanus** [comment]
Replace the "file" references in tasks.json with something else:
```
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
```
to
```
            "args": [
                "-g",
                "test.cpp",
                "-o",
                "test.o"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
```
and change the "type" from "cppBuild" to "shell".

Or build with some other extension, like CMake Tools if you use CMake: https://code.visualstudio.com/docs/cpp/cmake-linux

**Comment by Ignatij3** [comment]
Thanks a lot, @sean-mcmanus, that helped!

**Comment by bobbrow** [comment]
It seems like a bug that the cppbuild provider would block the task if you hardcode a file name in there.  We should fix it so that it only blocks the task if you're using the `${file}` variable.

**Comment by Ignatij3** [comment]
@bobbrow You can take a look in my `tasks.json` in [this commit](https://github.com/Ignatij3/Bouncy-squares-Qt/commit/e3ffcc54e272bd18304f8b7629a2e3ec430be4b3), not a single `${file}` reference, not even explicitely stated file extensions.

**Comment by bobbrow** [comment]
Yep, I just submitted a PR for the fix.

**Comment by Ignatij3** [comment]
Sorry for somewhat stupid question, but when does the fix roll out after PR is approved?

**Comment by Ignatij3** [comment]
Alright, I got it

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).
