### ISSUE TITLE
C_Cpp Default:Defines in settings not working

### ISSUE THREAD

**Issue by alan-gu** [microsoft/vscode-cpptools#8589]
Bug type: Language Service

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
client:
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
host:
Linux farmnode02 4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
c/c++ extension version:v1.7.1

**Steps to reproduce**

1. open settings
2. go to Workspace/Extensions/C/C++/C_Cpp>Default:Defines
3. add one item, in my case ANDROID=1
4. not neccesary but I've tried restart vscode

**Expected behavior**

after setting, code inclosed in
#if ANDROID
#endif
should be displayed normally
but they are displayed in dissaturated color, like before.

Below is the workspace file:
{
	"folders": [
		{
			"path": "a"
		},
		{
			"path": "b"
		},
		{
			"path": "c"
		},
		{
			"path": "d"
		}
	],
	"settings": {
		"C_Cpp.default.defines": [
			"ANDROID=1"
		]
	}
}

**Comment by sean-mcmanus** [comment]
Do you have a c_cpp_properties.json? If so, you need to make sure the defines has "${default}" in it and you don't have configurationProvider or compileCommands set.

It's working for me:
![image](https://user-images.githubusercontent.com/19859882/146841437-b77831b6-a017-4d6b-af5d-c05239f6fa76.png)

**Comment by alan-gu** [comment]
Thx for your reply @sean-mcmanus
I think my question is answered, below is some following info that I think might improve the extension.

I do have 4 c_cpp_properties.json file under the 4 folders of my workspace.
if I open c/c++: edit configuration(JSON OR UI), the 4 folders will be prompted for me to choose one of them.
I added ANDROID=1 to one folder, and see it works, inside that folder.
I don't see a c_cpp_properties.json for the workspace.

I observed that by doing this, I opened a page named IntelliSense Configurations. Adding "defines" on this page will write to c_cpp_properties.json. The way I used was ctrl-, and goto extensions/C/C++. This will write to xxx.code-workspace and won't work.
But only the latter way allows setting to whole workspace.

So I think there're 2 issues:
1. what is the setting in setting->extensions->c/c++->defines used for(since it is not working this way and there's duplicate setting else where)
2. how or is it possible to set define for workspace.

**Comment by sean-mcmanus** [comment]
It sounds like you have a multi-root workspace with 4 workspace folders. The c_cpp_properties.json only applies to the particular folder and there is no such file for an entire workspace. You can set C_Cpp.default.defines in the workspace file to have it be used by all the workspace folders, but you need to make sure "${default} is in the"defines" list in the c_cpp_properties.json. Does that answer your questions?

**Comment by alan-gu** [comment]
@sean-mcmanus 
Yes, It works. Sorry I didn't understand the first time.
Thanks a lot.
