### ISSUE TITLE
Failed when downloading 'C/C++ language components (OS X)'

### ISSUE THREAD

**Issue by Yingjie-Zhao** [microsoft/vscode-cpptools#859]
Here is the error message:
```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (OS X)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
Failed at stage: downloadPackages
Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

Finished
```

I have read about some relative issues and tried to reset my http.proxy,but it seems not working as the error message shows that the plugin still using an incorrect http proxy ```127.0.0.1:443```after I changed my http proxy to ```127.0.0.1:1087```

**Comment by sean-mcmanus** [comment]
We're not able to repro this. What is your http.proxy setting exactly? `http://127.0.0.1:1087`? Our code doesn't do any changing of the port or proxy address.

**Comment by Yingjie-Zhao** [comment]
Thanks for your replying,I have tried downloading this component again and it didn't report any error message and started successfully,though I don't know why...but it is working now.
