### ISSUE TITLE
RE: Debugger fails when 'vector<string>' comes in 

### ISSUE THREAD

**Issue by pik1432** [microsoft/vscode-cpptools#8592]
Bug type: Debugger

**Describe the bug**

- OS and Version:
- VS Code Version:
VS Code Version: 1.63.2 (user setup)
commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

- C/C++ Extension Version:

g++ --version
g++.exe (Rev5, Built by MSYS2 project) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gdb --version
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

When the code comes with the vector type, the debugger fails to connect to the debuggee. 

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Go to the line commented // !!!!
2. when the entire line is commented out, no problem occurs. 
3. When the line is uncommented, the debugger fails. 

Here is the code:

#include <iostream>
#include <vector>
#include <string>

using namespace std;

int main()
{

    // ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". During startup program exited with code 0xc0000139.
    // vector<string> msg{"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};

    // for (const string &word : msg)
    // {
    //     cout << word << " ";
    // }

    cout << endl;
    cout << "So be it! pik-20211107";
    cout << endl;

    /* declare and initialize string */
    char myString[] = "This is an example of string declaration!";

    /* print string */
    printf("%s", myString);

    int numberA = 5;
    int numberB = 10;

    int sum = numberA + numberB;

    /* Printing a number */
    printf("A soma de numberA + numberB é: %d", sum);

    vector<string> msg{"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"}; // !!!!

    // for (const string &word : msg)
    // {
    //     cout << word << " ";
    // }
}

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

Here are the gdb output messages:

1: (102) LaunchOptions{"name":"g++ - build and debug active file","type":"cppdbg","request":"launch","program":"c:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64\\program_test.exe","args":[],"stopAtEntry":true,"cwd":"c:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64","environment":[],"externalConsole":false,"MIMode":"gdb","setupCommands":[{"description":"Enable pretty-printing for gdb","text":"-enable-pretty-printing","ignoreFailures":false}],"preLaunchTask":"C/C++: g++ build active file","miDebuggerPath":"C:\\msys64\\mingw64\\bin\\gdb.exe","logging":{"engineLogging":true},"__configurationTarget":5,"__sessionId":"5ed22e26-8279-4cc8-8870-199d233f9a26"}
1: (166) Wait for connection completion.
1: (582) ->=thread-group-added,id="i1"
1: (583) ->~"GNU gdb (GDB) 11.1\n"
1: (583) ->~"Copyright (C) 2021 Free Software Foundation, Inc.\n"
1: (583) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
1: (584) ->~"\nType \"show copying\" and \"show warranty\" for details.\n"
1: (584) ->~"This GDB was configured as \"x86_64-w64-mingw32\".\n"
1: (585) ->~"Type \"show configuration\" for configuration details.\n"
1: (585) ->~"For bug reporting instructions, please see:\n"
1: (585) ->~"<https://www.gnu.org/software/gdb/bugs/>.\n"
1: (585) ->~"Find the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>."
1: (586) ->~"\n\n"
1: (587) ->~"For help, type \"help\".\n"
1: (587) ->~"Type \"apropos word\" to search for commands related to \"word\".\n"
1: (591) ->(gdb)
1: (594) <-1001-gdb-set target-async on
1: (617) ->~"Warning: 'set target-async', an alias for the command 'set mi-async', is deprecated.\n"
1: (617) ->~"Use 'set mi-async'.\n\n"
1: (617) ->1001^done
1: (618) ->(gdb)
1: (618) ->&"\n"
1: (618) ->^done
1: (618) ->(gdb)
1: (620) 1001: elapsed time 27
1: (630) <-1002-enable-pretty-printing
1: (633) ->1002^done
1: (633) 1002: elapsed time 2
1: (633) <-1003-interpreter-exec console "set pagination off"
1: (633) ->(gdb)
1: (634) ->&"\n"
1: (634) ->^done
1: (634) ->(gdb)
1: (634) ->=cmd-param-changed,param="pagination",value="off"
1: (634) ->1003^done
1: (634) 1003: elapsed time 0
1: (634) ->(gdb)
1: (634) <-1004-gdb-set auto-solib-add on
1: (634) ->&"\n"
1: (634) ->^done
1: (635) ->(gdb)
1: (648) ->1004^done
1: (648) 1004: elapsed time 14
1: (648) ->(gdb)
1: (648) <-1005-gdb-set solib-search-path c:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64;
1: (649) ->&"\n"
1: (649) ->^done
1: (649) ->(gdb)
1: (663) ->1005^done
1: (664) 1005: elapsed time 15
1: (664) ->(gdb)
1: (664) <-1006-environment-cd c:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64
1: (664) ->&"\n"
1: (664) ->^done
1: (664) ->(gdb)
1: (680) ->1006^done
1: (680) 1006: elapsed time 16
1: (680) ->(gdb)
1: (680) ->&"\n"
1: (680) ->^done
1: (680) ->(gdb)
1: (681) <-1007-interpreter-exec console "show configuration"
1: (694) ->~"This GDB was configured as follows:\n   configure --host="
1: (695) ->~"x86_64-w64-mingw32 --target=x86_64-w64-mingw32\n"
1: (695) ->~"\t     --with-auto-load-dir=$debugdir:$datadir/auto-load\n\t     --with-auto-load-safe-path="
1: (695) ->~"$debugdir:$datadir/auto-load\n"
1: (695) ->~"\t     --with-expat\n"
1: (696) ->~"\t     --with-gdb-datadir=/mingw64/share/gdb (relocatable)\n"
1: (696) ->~"\t     --with-jit-reader-dir=/mingw64/lib/gdb (relocatable)\n"
1: (696) ->~"\t     --without-libunwind-ia64\n"
1: (696) ->~"\t     --with-lzma\n"
1: (696) ->~"\t     --without-babeltrace\n"
1: (696) ->~"\t     --without-intel-pt\n"
1: (696) ->~"\t     --with-mpfr\n"
1: (697) ->~"\t     --with-xxhash\n"
1: (697) ->~"\t     --with-python=/mingw64 (relocatable)\n"
1: (697) ->~"\t     --with-python-libdir=/mingw64/lib (relocatable)\n"
1: (697) ->~"\t     --without-debuginfod\n"
1: (697) ->~"\t     --without-guile\n"
1: (697) ->~"\t     --disable-source-highlight\n"
1: (697) ->~"\t     --with-separate-debug-dir=/mingw64/lib/debug (relocatable)\n"
1: (697) ->~"\t     --with-system-gdbinit=/mingw64/etc/gdbinit (relocatable)\n"
1: (697) ->~"\n(\"Relocatable\" means the directory can be moved with the GDB installation\ntree, and GDB will still find it.)\n"
1: (697) ->1007^done
1: (698) 1007: elapsed time 16
1: (698) ->(gdb)
1: (698) ->&"\n"
1: (698) ->^done
1: (698) ->(gdb)
1: (703) <-1008-file-exec-and-symbols c:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64\\program_test.exe
1: (727) ->1008^done
1: (728) 1008: elapsed time 24
1: (728) ->(gdb)
1: (728) <-1009-interpreter-exec console "show architecture"
1: (728) ->&"\n"
1: (728) ->^done
1: (728) ->(gdb)
1: (740) ->~"The target architecture is set to \"auto\" (currently \"i386:x86-64\").\n"
1: (740) ->1009^done
1: (740) 1009: elapsed time 12
1: (740) ->(gdb)
1: (740) ->&"\n"
1: (740) ->^done
1: (741) ->(gdb)
1: (741) <-1010-exec-arguments 2>CON 1>CON <CON
1: (755) ->1010^done
1: (756) 1010: elapsed time 14
1: (756) ->(gdb)
1: (756) <-1011-break-insert -f main
1: (756) ->&"\n"
1: (756) ->^done
1: (756) ->(gdb)
1: (776) ->1011^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x0000000140001599",func="main()",file="C:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64\\program_test.cpp",fullname="C:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64\\program_test.cpp",line="18",thread-groups=["i1"],times="0",original-location="main"}
1: (777) ->(gdb)
1: (777) ->&"\n"
1: (777) ->^done
1: (777) ->(gdb)
1: (780) 1011: elapsed time 24
1: (785) Send Event AD7EngineCreateEvent
1: (788) Send Event AD7ProgramCreateEvent
1: (812) ShellPid=11740
1: (818) DebuggerPid=36180
1: (843) <-1012-break-insert -f HelloWorld.cpp:9
1: (848) ->&"No source file named HelloWorld.cpp.\n"
1: (848) ->1012^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="<PENDING>",pending="HelloWorld.cpp:9",times="0",original-location="HelloWorld.cpp:9"}
1: (849) 1012: elapsed time 6
1: (849) ->(gdb)
1: (849) ->&"\n"
1: (849) ->^done
1: (849) ->(gdb)
1: (857) Send Event AD7BreakpointErrorEvent
1: (876) <-1013-break-insert -f Program_34b_TreeSortTasking.cpp:123
1: (879) ->&"No source file named Program_34b_TreeSortTasking.cpp.\n"
1: (879) ->1013^done,bkpt={number="3",type="breakpoint",disp="keep",enabled="y",addr="<PENDING>",pending="Program_34b_TreeSortTasking.cpp:123",times="0",original-location="Program_34b_TreeSortTasking.cpp:123"}
1: (879) 1013: elapsed time 3
1: (879) ->(gdb)
1: (880) Send Event AD7BreakpointErrorEvent
1: (880) ->&"\n"
1: (880) ->^done
1: (880) ->(gdb)
1: (880) <-1014-break-insert -f program_test.cpp:34
1: (893) ->1014^done,bkpt={number="4",type="breakpoint",disp="keep",enabled="y",addr="0x000000014000166e",func="main()",file="C:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64\\program_test.cpp",fullname="C:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64\\program_test.cpp",line="34",thread-groups=["i1"],times="0",original-location="program_test.cpp:34"}
1: (893) 1014: elapsed time 13
1: (893) ->(gdb)
1: (893) ->&"\n"
1: (894) ->^done
1: (894) ->(gdb)
1: (900) <-1015-symbol-list-lines C:\\parkik\\MEng_Study\\ECE7650_T38_ParallelProcessing\\Code\\VScode_msys64\\program_test.cpp
1: (909) ->1015^done,lines=[{pc="0x0000000140001581",line="8"},{pc="0x0000000140001594",line="8"},{pc="0x0000000140001599",line="18"},{pc="0x00000001400015b2",line="19"},{pc="0x00000001400015cb",line="20"},{pc="0x00000001400015e4",line="23"},{pc="0x0000000140001630",line="26"},{pc="0x0000000140001646",line="28"},{pc="0x0000000140001650",line="29"},{pc="0x000000014000165a",line="31"},{pc="0x000000014000166e",line="34"},{pc="0x0000000140001685",line="36"},{pc="0x0000000140001862",line="42"},{pc="0x000000014000188d",line="36"},{pc="0x0000000140001933",line="42"},{pc="0x000000014000193f",line="0"},{pc="0x000000014000195d",line="42"},{pc="0x000000014000196b",line="42"},{pc="0x000000014000197a",line="0"},{pc="0x0000000140001998",line="42"},{pc="0x000000014000199f",line="42"},{pc="0x00000001400019a7",line="42"},{pc="0x00000001400019bd",line="0"}]
1: (910) ->(gdb)
1: (910) ->&"\n"
1: (910) 1015: elapsed time 10
1: (910) ->^done
1: (910) ->(gdb)
1: (917) Send Event AD7BreakpointBoundEvent
1: (974) Send Event AD7LoadCompleteEvent
=thread-group-added,id="i1"
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: 'set target-async', an alias for the command 'set mi-async', is deprecated.
Use 'set mi-async'.

Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
1: (976) <-1016-exec-run
1: (1699) ->=thread-group-started,id="i1",pid="21588"
1: (1700) ->=thread-created,id="1",group-id="i1"
1: (1703) <-1017-thread-info 1
1: (1708) ->=thread-created,id="2",group-id="i1"
1: (1708) <-1018-thread-info 2
1: (1708) ->~"[New Thread 21588.0x76c0]\n"
1: (1708) ->=thread-created,id="3",group-id="i1"
[New Thread 21588.0x76c0]
1: (1708) ->~"[New Thread 21588.0x8d5c]\n"
1: (1708) ->=thread-created,id="4",group-id="i1"
1: (1708) ->~"[New Thread 21588.0x2514]\n"
1: (1709) <-1019-thread-info 3
[New Thread 21588.0x8d5c]
1: (1709) <-1020-thread-info 4
[New Thread 21588.0x2514]
1: (1713) ->~"[Thread 21588.0x76c0 exited with code 3221225785]\n"
[Thread 21588.0x76c0 exited with code 3221225785]
1: (1713) ->=thread-exited,id="2",group-id="i1"
1: (1713) ->~"[Thread 21588.0x4cd4 exited with code 3221225785]\n"
1: (1713) ->=thread-exited,id="1",group-id="i1"
1: (1713) ->~"[Thread 21588.0x8d5c exited with code 3221225785]\n"
1: (1713) ->=thread-exited,id="3",group-id="i1"
1: (1713) ->=thread-exited,id="4",group-id="i1"
1: (1714) ->=thread-group-exited,id="i1"
1: (1714) ->1016^error,msg="During startup program exited with code 0xc0000139."
1: (1714) ->(gdb)
1: (1714) ->&"\n"
1: (1714) ->^done
1: (1714) ->(gdb)
1: (1714) ->1017^done,threads=[]
1: (1714) ->(gdb)
1: (1714) ->&"\n"
1: (1714) ->^done
1: (1714) ->(gdb)
1: (1714) ->1018^done,threads=[]
1: (1714) ->(gdb)
1: (1714) ->&"\n"
1: (1714) ->^done
1: (1715) ->(gdb)
1: (1715) ->1019^done,threads=[]
1: (1715) ->(gdb)
[Thread 21588.0x4cd4 exited with code 3221225785]
1: (1715) ->&"\n"
[Thread 21588.0x8d5c exited with code 3221225785]
1: (1715) ->^done
1: (1715) ->(gdb)
1: (1715) ->1020^done,threads=[]
1: (1715) ->(gdb)
1: (1715) ->&"\n"
1: (1715) ->^done
1: (1715) 1016: elapsed time 739
1: (1715) ->(gdb)
1: (1718) 1017: elapsed time 15
1: (1719) Send Event AD7MessageEvent
1: (1720) 1018: elapsed time 12
1: (1720) 1019: elapsed time 12
1: (1722) 1020: elapsed time 12
ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". During startup program exited with code 0xc0000139.
1: (1728) Send Event AD7ProgramDestroyEvent
The program 'c:\parkik\MEng_Study\ECE7650_T38_ParallelProcessing\Code\VScode_msys64\program_test.exe' has exited with code 0 (0x00000000).
1: (1732) Shell exited, stop debugging
1: (1740) <--gdb-exit

**Comment by WardenGnaw** [comment]
As of Nov 8, 2021, mingw-w64-x86_64-toolchain-11.1.x causes GDB to return "During startup program exited with code 0xc0000139"
The current workaround is to downgrade to working toolchain such as 10.2.
