### ISSUE TITLE
Updating Extension Fails: "downloadPackages" Failed - "ECONNRESET"

### ISSUE THREAD

**Issue by vindicatorr** [microsoft/vscode-cpptools#8594]
Bug type: General

**Describe the bug**
- OS and Version: Linux x64 5.15.7-dirty
- VS Code Version: 1.64.0-insider
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them): I disabled all others.
- A clear and concise description of what the bug is:
```
Failed at stage: downloadPackages
Error: read ECONNRESET
```

**To Reproduce**
*Please include code sample and `task.json` files.*
1. Update the extension to v1.7.1
2. Let it try to download the remainder of the update after the initial extension update succeeds.

**Expected behavior**

Successfully finish the update as it has done in the past.

**Screenshots**

**Additional context**

```
loggingLevel: Debug
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux / x86_64)' (11486 KB)  Failed. Retrying...(11486 KB)  Failed. Retrying...(11486 KB)  Failed. Retrying...Waiting 8 seconds...(11486 KB)  Failed. Retrying...Waiting 15 seconds...(11486 KB)  Failed. Retrying...Waiting 15 seconds...(11486 KB)  Failed. Retrying...Waiting 15 seconds...(11486 KB)  Failed. Retrying...Waiting 15 seconds...(11486 KB)  Failed. Retrying...Waiting 15 seconds...(11486 KB)  Failed. Retrying...Waiting 15 seconds...(11486 KB)  Failed to download https://go.microsoft.com/fwlink/?linkid=2175018
Failed at stage: downloadPackages
Error: read ECONNRESET

If you work in an offline environment or repeatedly see this error, try downloading a version of the extension with all the dependencies pre-included from https://github.com/microsoft/vscode-cpptools/releases, then use the "Install from VSIX" command in VS Code to install it.
```
Going to that `linkid=2175018` in my browser, the `bin_linux.zip` downloaded just fine (though I don't know where it would need to be extracted if that's all there was.
I know I can just get the .vsix, but thought I'd put this issue out there first.

**Comment by sean-mcmanus** [comment]
We're switching to the platform-specific vsix support provided by VS Code in our next release, so this issue won't be a problem after that.

**Comment by vindicatorr** [comment]
Ah yes, sure enough. I see that in the coming 1.8.0 vsix, as you said. Installed.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).
