### ISSUE TITLE
C/C++ parser displays "Command '' not found"

### ISSUE THREAD

**Issue by duongvuhong** [microsoft/vscode-cpptools#8599]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

1. Open c/c++ project.
2. Parser running
3. Click on parser status icon
4. "Command '' not found" error message

Extension version: 1.7.1
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.64GB (0.51GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/cuncon-wsl/projects/alink/SAL2 --remote=wsl+Ubuntu --crash-reporter-id 24a2238d-530f-4238-a634-5a8b8957f2a4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|Memory (System)|5.92GB (2.36GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|Memory (System)|5.92GB (2.36GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614
vscexrecpromp3t2:30407763

```

</details>

**Comment by duongvuhong** [comment]
I attach vs code log
[vscode-app-1640222943777.log](https://github.com/microsoft/vscode-cpptools/files/7766071/vscode-app-1640222943777.log)
.

**Comment by sean-mcmanus** [comment]
That just means the pausing menu is not usable. I have a fix for the error at https://github.com/microsoft/vscode-cpptools/pull/8609 .

However, if you expect to be able to use the Pause/Resume workspace parsing commands, then that could be a bug -- we have to receive the "Parsing workspace" notification before that can be used. The icon can appear even when workspace parsing isn't being done, but in those cases pause isn't usable.

**Comment by duongvuhong** [comment]
At that time, I cannot use F12 key to navigate to definition of functions, vars, etc.
I have no idea if the error is related to this issue.
However, I uninstalled and removed all extension, data folders and reinstall vs code again.
Now it works.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).
