### ISSUE TITLE
Error on Ubuntu trying to debug using GDB "Invalid launch option type, is not supported"

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-cpptools#86]
_From @wirecat on June 26, 2016 18:9_
- VSCode Version: 1.2.1
- OS Version: Ubuntu 16.04 LTS

I am quite new to VS Code and g++... so I am highly suspicious I am the problem. Submitting this issue because I am unable to find anything on SO, github, or google.

Steps to Reproduce:
1. Make a simple HelloWorld.cpp which contains hello world.
2. Compile using "g++: g++ -g HelloWorld.cpp".
3. Add the folder for HelloWorld.cpp to VSCode.
4. Go to the debug tab.
5. Add a debug configuration for "C++ (GDB)".
6. Modify the "program" field to point at the HelloWorld output. Mine is: "${workspaceRoot}/a.out"
7. Receive error: "error while processing request 'launch' (exception: Invalid launch option type, is not supported."

_Copied from original issue: Microsoft/vscode#8160_

**Comment by dbaeumer** [comment]
_From @zhu-liang on June 27, 2016 7:3_

Go the same problem here. For step 6, mine was using absolute directory of my g++ compiled binary.

**Comment by dbaeumer** [comment]
_From @zhu-liang on June 27, 2016 8:23_

Please try add 
 "launchOptionType": "Local",
into your launch.json file and try again. Solved my side. Should be version problem.

**Comment by dbaeumer** [comment]
@wirecat do you have a C++ extension installed.

**Comment by dbaeumer** [comment]
_From @wirecat on June 28, 2016 18:38_

I hve the C/C++ extension from M$ installed.

**Comment by dbaeumer** [comment]
_From @wirecat on June 28, 2016 18:45_

@zhu-liang Thank you! After I updated the C/C++ extension and put that option in I was able to start debugging. Is this a long term fix or something temporary on the insiders build?
Unsure of if I should be closing this or not.

**Comment by delmyers** [comment]
@dbaeumer, there was a short-lived bug in the debugger due to us accidentally releasing two binaries that were not in sync. After updating your C/C++ extension, that should have been fixed. Sorry for the inconvenience.

**Comment by pieandcakes** [comment]
I am closing this since it has been resolved. Please reopen if you are still having problems.
