### ISSUE TITLE
c/c++ Confuse the macro and prepress

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-cpptools#8600]
```c
#ifndef __AC7840X_ANA_REG_H__
#define __AC7840X_ANA_REG_H__
/*====================================================================================================================**
                                                        ANA start
**====================================================================================================================*/

#define _ANA_Base 0x40008800 /*!< Analog Registers */

#define _ANA_SYSLDO_CFG0_Addr (_ANA_Base + 0x0000) /*!< (@0x40008800) SYSLDO CONFIGURATION 0 REGISTER */
#define _ANA_SYSLDO_CFG1_Addr (_ANA_Base + 0x0004) /*!< (@0x40008804) SYSLDO Configuration Register1 */
#endif
```

- can any body tell me what is the diffenence between macro and preprocess?
- with the setteing and disable c/c++ externion
   ```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "entity.name.function.preprocessor",
                    "entity.name.variable.preprocessor.symbol.cs",
                ],
                "settings": {
                    "foreground": "#be5c44",
                    "fontStyle": ""
                }
            },
            {
                "scope": [
                    "meta.preprocessor.macro",
                ],
                "settings": {
                    "foreground": "#c70060",
                    "fontStyle": ""
                }
            },
        ]
    }
   ```
  it shows as: Orange(preprocess) and red (macro)
  ![image](https://user-images.githubusercontent.com/1876302/147188528-c9ee4e2c-f470-422a-bb48-5e3e3bf87a46.png)

- but enable c/c++ extension; it shows as： all orange( why all is preprocess?)
![image](https://user-images.githubusercontent.com/1876302/147188766-430d05ad-ec3c-4185-ac7a-2cf267ddb9d0.png)

- then enable semanticTokenColorCustomizations
  ```json
    "editor.semanticTokenColorCustomizations": {
        "enabled": true,
        "rules": {
            "macro": {
                "foreground": "#0d5f14",
                "bold": false,
                "italic": false,
                "fontStyle": "",
                "underline": false
            },
            "preprocessor": {
                "foreground": "#ec3011",
                "bold": false,
                "italic": false,
                "fontStyle": "",
                "underline": false
            },
        }
    }
    ```
all green(macro)*why all is preprocess?):
![image](https://user-images.githubusercontent.com/1876302/147189012-c4b0ec60-caa7-4c0a-b57f-45c4161703db.png)

**Comment by sean-mcmanus** [comment]
Our extension doesn't provide any semantic colorization for "preprocessor" rules, just "macro" (see https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L4130). You can change "C_Cpp.enhancedColorization" to "Disabled" to see the previous behavior, but that is not recommended. The previous red colors from the lexical colorization will also appear in an `#else` where IntelliSense is not active.
![image](https://user-images.githubusercontent.com/19859882/147501159-d316989c-58d1-47e9-a741-64ffb8226df8.png)

**Comment by heartacker** [comment]
> Our extension doesn't provide any semantic colorization for "preprocessor" rules, just "macro" (see https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L4130). 

so, is it necessary to add `preprocessor`  semantic colorization?

**Comment by sean-mcmanus** [comment]
We don't currently support a "preprocessor" semantic token scope. It's not a standard token type: https://github.com/Microsoft/vscode-docs/blob/main/api/language-extensions/semantic-highlight-guide.md . And also our IntelliSense engine doesn't generate a semantic token of that type (even if we were to add a custom token type for it).
