### ISSUE TITLE
Debugger won't start

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8603]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10 Version 19043.1415
- VS Code Version: 1.63.2
- C/C++ Extension Version: v1.8.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): 
![image](https://user-images.githubusercontent.com/96447414/147369791-7b3867bc-3e12-498d-b320-bd83c81a9760.png)

- A clear and concise description of what the bug is. After I run my debugger it closes immediately 

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*

Open a New Folder in VSCode
Add a file.cpp
Add some C++ Code
```
#include <fstream>

using namespace std;
ifstream cin("numere2.in");
ofstream cout("numere2.out");
int main()
{
    int n,nr,in;
    cin>>n;
    for(int i = 0; i < n; i++)
    {
        cin>>nr;
        in = (nr+1)/2;
        for(int i = 0; i < nr; i++)
        {
            cout<<in<<" ";
            in++;
        }
        cout<<'\n';
    }
    return 0;
}
```

Go to the Debugger Window
Press F5
Choose Windows Compiler (C++ in this case)
Configure the .json file

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Windows Debugger",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "externalTerminal"
        }
    ]
}
```
Go back into the script
Add a Breakpoint at Line 13
Go to the debugger window
Run the debugger (F5)
A cmd-like window with appear which means the program runned
It closes
And it does work it outputs fine but I can't see the watch or use the debugger controller

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`* It doesn't make a difference
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by WardenGnaw** [comment]
In your `launch.json`, can you add the following and share the output in the `Debug Console`?
```
"logging": {
   "engineLogging": true
}
```
