### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by al20878** [microsoft/vscode-cpptools#8606]
Bug type: Language Service

**Describe the bug**
Exactly as #5831

```Connection to server got closed. Server will not be restarted.```

- OS and Version:
OS Name	Microsoft Windows 7 Home Premium
Version	6.1.7601 Service Pack 1 Build 7601
- VS Code Version:
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.1.7601
- C/C++ Extension Version:
Released on
3/29/2016, 21:27:12
Last updated
10/19/2021, 22:54:55
Identifier
ms-vscode.cpptools
- Other extensions you installed (and if the issue persists after disabling them):
Released on
9/8/2020, 16:28:11
Last updated
11/16/2021, 12:20:52
Identifier
ms-vscode.cpptools-extension-pack
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
See above

**Steps to reproduce**

Seeing this error every morning when the computer wakes up (from hibernate overnight) with VS Code window left open when the OS went to sleep

**Comment by sean-mcmanus** [comment]
That message is from VS Code -- it just means our cpptools process crashed. The message is misleading and the cpptools server is actually restarted by our extension, so if it doesn't happen repeatedly after the computer is woken up, then you could probalby ignore it. If you can attach a debugger to the cpptools process to get a crash call stack, that could help us identify and fix the issue: see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv .

**Comment by al20878** [comment]
Alright and thanks for clarifying!  I was actually restarting the VS Code because I did not know what it could have affected, but according to you it appears to be quite harmless.  Nonetheless, making sure the message didn't confuse anybody it'd be best not to display it altogether.

There was no other such messages seen while the computer was up and running (except the one at wake-up time).

**Comment by sean-mcmanus** [comment]
The "Connection to server got closed. Server will not be restarted." message is from VS Code (https://github.com/microsoft/vscode-languageserver-node/blob/756cf416e98bc9ce843416cf1c03881ddd1ef322/client/src/common/client.ts#L3571) so our extension is not able to suppress that error.

**Comment by bobbrow** [comment]
@sean-mcmanus maybe we could log a message right before it telling people not to worry. 😃 Which output does it go to?

**Comment by sean-mcmanus** [comment]
It goes to the "cpptools" output pane:
![image](https://user-images.githubusercontent.com/19859882/147512678-64b307c6-64b6-47fb-9988-05b5607b93f6.png)

I tried logging our own message to the C/C++ channel (before or after we detect the crash), but the VS Code message just ends up covering up our message. We could potentially delay it by some timer to attempt to cover up their message pane. Also, when it's added to the C/C++ logging it may be hard to notice if Debug logging is enabled.

**Comment by bobbrow** [comment]
It would need to go to this 'cpptools' channel instead of our C/C++ channel.  Are we able to log to a channel that we don't own?

**Comment by sean-mcmanus** [comment]
@bobbrow There is no API to obtain pre-existing output channel objects from other sources. The only API is to create an output channel (and use it).
