### ISSUE TITLE
error is a false : expected a ';'C/C++(65) runs perfectly in gcc 

### ISSUE THREAD

**Issue by Yahia-Ghadiry** [microsoft/vscode-cpptools#8607]
when writing c++ code the following line gives an error in vscode while it is compiled normally without any errors:

using std::cout, std::vector, std::string, std::ifstream;
it highlights the first , right after std::cout

and yes I used #include in the beginning.

it seems to only happen when enabling the microsoft c/c++ extension.

**Comment by sean-mcmanus** [comment]
We need more info. What is the OS and compilerPath? The output of running C/C++: Log Diagnostics may help.

**Comment by sean-mcmanus** [comment]
Ignore my previous comment -- it appears your cppStandard is c++11 or c++14 and changing it to c++17 should fix the issue.

**Comment by sean-mcmanus** [comment]
gcc with -std=c++14 gives: warning: comma-separated list in using-declaration only available with '-std=c++17' or '-std=gnu++17' , but it still compiles it...looks like it's non-compliant in that regards, but our IntelliSense engine parser is stricter.

**Comment by yahia20** [comment]
> Ignore my previous comment -- it appears your cppStandard is c++11 or c++14 and changing it to c++17 should fix the issue.

I am going to try that once I get home in about 8-9 hours

**Comment by yahia20** [comment]
> gcc with -std=c++14 gives: `warning: comma-separated list in using-declaration only available with '-std=c++17' or '-std=gnu++17'` , but it still compiles it...looks like it's non-compliant in that regards, but our IntelliSense engine parser is stricter.

When I compile it just `gcc nameOfFile` I get no warnings or errors so I am probably useing c++17 standard by default but I will check wonce I get home.

**Comment by yahia20** [comment]
It worked thanks,  don't know why this isn't the default.

**Comment by yahia20** [comment]
for more details I did ctrl+shift+P then scrolled to C++ standard (and C standard for future use) then chose C++20 (and c17)
