### ISSUE TITLE
Built-in telemetry module needs to be updated

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-cpptools#8612]
The current version of the telemetry module is quite old and doesn't support a lot of the new data cleaning and performance improvements that the newer versions have. My suggestion is to bump all the way to latest 0.4.4 and try to continue tracking the latest changes. Old interfaces should never change so in theory it shouldn't break anything.

Code pointer
https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L4370

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders3 or 1.8.0 (via using VS Code's "Pre-Release Version" UI or https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#version-history ).
