### ISSUE TITLE
Programmes are not running properly

### ISSUE THREAD

**Issue by Vishal973** [microsoft/vscode-cpptools#8619]
Issue Type: <b>Bug</b>

When I try to run some big programmes, it only shows "Running" and they never execute or complete. One of programmes I tried to run is: 
#include<stdio.h>

int main()
{
int a=1, n;
printf("Enter your number \n");
scanf("%d", &n);

while((a+1)<n)
{a++;
n%a;
if(n%a==0){printf("Given number is not a prime number"); break;}
}
if((a+1)==n){printf("Given number is a prime number");}
if(n<=1){printf("Given number is not a prime number");}
return 0;    
}

For this I have already mailed so many times but my problem has not solved yet. Please help me to overcome this situation and I have so much work to do on VS code.
Thank you.

Extension version: 1.8.0-insiders2
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.73GB (6.64GB free)|
|Process Argv|--crash-reporter-id 6c762e54-8133-4012-846f-6ffd6cc54a7c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t1:30407762

```

</details>

**Comment by WardenGnaw** [comment]
What value of `n` are you using that it does not complete? 
I was able to execute this program for the extreme ranges of an `int`. e.g. -2,147,483,648 and 2,147,483,647

**Comment by Vishal973** [comment]
I think the problem is in Code Runner extension because I can easily run programmes using powershell terminal.Details about Code Runner extension: Name: Code RunnerId: formulahendry.code-runnerDescription: Run C, C++, Java, JS, PHP, Python, Perl, Ruby, Go, Lua, Groovy, PowerShell, CMD, BASH, F#, C#, VBScript, TypeScript, CoffeeScript, Scala, Swift, Julia, Crystal, OCaml, R, AppleScript, Elixir, VB.NET, Clojure, Haxe, Obj-C, Rust, Racket, Scheme, AutoHotkey, AutoIt, Kotlin, Dart, Pascal, Haskell, Nim, Version: 0.11.6Publisher: Jun HanVS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner Sent from Mail for Windows From: Andrew WangSent: 03 January 2022 23:42To: microsoft/vscode-cpptoolsCc: Vishal973; AuthorSubject: Re: [microsoft/vscode-cpptools] Programmes are not running properly (Issue #8619) What value of n are you using that it does not complete?I was able to execute this program for the extreme ranges of an int. e.g. -2,147,483,648 and 2,147,483,647—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by WardenGnaw** [comment]
This is the issues page for VS Code C/C++ Extension. You will want to post at https://github.com/formulahendry/vscode-code-runner/issues if you are having issues with the VS Code CodeRunner extension.

**Comment by Vishal973** [comment]
Thanks for your guidance. Now my problem has been completely solved. And I
want to close my issue.
Thank you for your support
