### ISSUE TITLE
C preprocessor: "defined" turns RED with bitwise operators in expression

### ISSUE THREAD

**Issue by tylov** [microsoft/vscode-cpptools#8623]
Issue Type: <b>Bug</b>

// The first "defined" turns RED, but the
// expression is evaluated correctly it seems:

#if defined(A) ^ defined(B)
#define RED_ALERT
#endif

Extension version: 1.7.1
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by sean-mcmanus** [comment]
I'm not reproing the behavior. What do you mean by "turns RED"? Is there an error message? Can you provide more info? A screenshot? What compiler are you using?

![image](https://user-images.githubusercontent.com/19859882/148259547-1b095ec5-319d-47ae-ad2d-6d2007c4d79a.png)

**Comment by tylov** [comment]
![image](https://user-images.githubusercontent.com/60263450/148261611-c04c751d-c9ca-45b9-bef9-ac58eb39de9e.png)

The red color only appear on bitwise operators, as if I used some illegal operator. && || is fine.  As you see, the RED_ALERT is greyed when both A and B (or none)  are defined, and normal when one of them is defined, which is all correct.
I use tdm-gcc 10.3, my .vscode\c_cpp_properties.json are:
```
{
    "configurations": [
        {
            "name": "gcc",
            "includePath": [
                "${default}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/Dev/TDM-GCC-64/bin/gcc.exe",
            "cStandard": "c99",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
The red color appears to be coming from some syntax colorizer and not our extension. We report errors as "Problems" with a red squiggle and not a red font color change. Are you using some other extension for syntax colorization or theming? Or is there some other code beforehand that could cause the issue?

![image](https://user-images.githubusercontent.com/19859882/148282787-f7e3bfe7-4e46-4a01-886e-12549f46f590.png)

**Comment by tylov** [comment]
I didn't think I used another syntax colorizer than the standard, but I will check on that. I thought too it was a bit strange that it didn't appear as squiggle, so you are probably correct. It is a very minor issue anyway.

**Comment by tylov** [comment]
I Figured it out. It only happens only when I select C language, not C++ !!

**Comment by sean-mcmanus** [comment]
VS Code itself implements the lexical colorization (not our C/C++ extension) -- and it's fixed with the latest VS Code Insiders.

**Comment by operamint** [comment]
Thank you!
