### ISSUE TITLE
category:issue  My C/C++ extension can not work

### ISSUE THREAD

**Issue by XuMingxing** [microsoft/vscode-cpptools#8628]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/8574

<div type='discussions-op-text'>

<sup>Originally posted by **XuMingxing** December 15, 2021</sup>
My C/C++ extension can not work when I use vs code to editor a C file. 
    The outline shows "No symbols found in document xxx".  
    And when I pressed F12 or press ctrl+ left click , it always shows "no definition found for xxx".
    I found the C/C+ extension runtime status has som uncaught errors: "Message header must separate key and value using: "

    I need help. </div>

**Comment by sean-mcmanus** [comment]
I don't see anything unsual in that logging. Is there no other cpptools logging?

**Comment by XuMingxing** [comment]
all of the log about cpptools is here, I add "cpptools.trace.server":"verbose" in settings.json and restart vs code, select "cpptools" channel, copy all of the log in output.
