### ISSUE TITLE
Slow compiling

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-cpptools#8631]
https://github.com/microsoft/vscode/issues/139732

cc @Priyanshuwork

**Comment by Priyanshuwork** [comment]
Ok, thank you🙂

**Comment by bobbrow** [comment]
Hi @Priyanshuwork. Many factors affect the compilation of your code.  Our extension does not provide compilation services, but we're happy to help consult if you provide more information about your project.  I will convert this issue to a discussion as this is not likely a bug in the extension.
