### ISSUE TITLE
Intellisense not working with STL

### ISSUE THREAD

**Issue by Zylann** [microsoft/vscode-cpptools#8642]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 64 bits
- VS Code Version: 1.63.2
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them): Git Blame

One day, in a usually working project, red squiggles appeared everywhere. I quickly realized even stuff like STL types were unrecognized, even if blatantly included just above:

![image](https://user-images.githubusercontent.com/1311555/148617291-3e406d5f-b5b7-428a-9490-caa668f8232a.png)

If I jump to the `<shared_mutex>` header file, it finds it though. But then inside it has more errors:
![image](https://user-images.githubusercontent.com/1311555/148617419-979c6b62-4266-407b-adf7-b326c76e2623.png)

As another example, it also underlines `std::vector` elsewhere, stating that `namespace "std" has no member "vector"C/C++(135)`. But the project compiles fine.

**Steps to reproduce**

Well, the weird part is, that issue only occurs in one of my workspaces, which is too heavy to be posted here. I have another workspace with another (very different) branch of the same project, which I had originally created by *copying* the first. The new workspace has no such issue. Maybe the only difference is that it uses C++17, while the first uses C++14.

I tried creating a new empty workspace, wrote a hello world `main.cpp`, and *copy-pasted* the exact same `.vscode` folder from the faulty workspace in there... could not reproduce the issue. So what's going on with my workspace?

I tried renaming the workspace root folder to simulate "making a new one" again... but it is still broken.

**Expected behavior**

I expected intellisense to continue working, as it worked for years before in that same workspace.

**Code sample and logs**

Here is my `c_cpp_properties.json`:
```json
{
    "version": 4,
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}",
                "${workspaceRoot}/editor",
                "${workspaceRoot}/core",
                "${workspaceRoot}/core/math",
                "${workspaceRoot}/core/bind",
                "${workspaceRoot}/core/helper",
                "${workspaceRoot}/core/io",
                "${workspaceRoot}/core/os",
                "${workspaceRoot}/drivers",
                "${workspaceRoot}/platform/windows",
                "${workspaceRoot}/modules",
                "${workspaceRoot}/modules/gdnative/include",
                "${workspaceRoot}/modules/voxel/thirdparty/fast_noise_2/include"
            ],
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe",
            "cppStandard": "c++14",
            "defines": [
                "_DEBUG",
                "UNICODE",
                "WINDOWS_ENABLED",
                "DEBUG_ENABLED",
                "TOOLS_ENABLED",
                "VOXEL_ENABLE_SMOOTH_VOXELS"
            ],
            "intelliSenseMode": "msvc-x64"
        }
    ]
}
```

```
-------- Diagnostics - 07/01/2022, 23:10:38
Version: 1.7.1
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceRoot}",
        "${workspaceRoot}/editor",
        "${workspaceRoot}/core",
        "${workspaceRoot}/core/math",
        "${workspaceRoot}/core/bind",
        "${workspaceRoot}/core/helper",
        "${workspaceRoot}/core/io",
        "${workspaceRoot}/core/os",
        "${workspaceRoot}/drivers",
        "${workspaceRoot}/platform/windows",
        "${workspaceRoot}/modules",
        "${workspaceRoot}/modules/gdnative/include",
        "${workspaceRoot}/modules/voxel/thirdparty/fast_noise_2/include"
    ],
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe",
    "cppStandard": "c++14",
    "defines": [
        "_DEBUG",
        "UNICODE",
        "WINDOWS_ENABLED",
        "DEBUG_ENABLED",
        "TOOLS_ENABLED",
        "VOXEL_ENABLE_SMOOTH_VOXELS"
    ],
    "intelliSenseMode": "msvc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceRoot}",
            "${workspaceRoot}/editor",
            "${workspaceRoot}/core",
            "${workspaceRoot}/core/math",
            "${workspaceRoot}/core/bind",
            "${workspaceRoot}/core/helper",
            "${workspaceRoot}/core/io",
            "${workspaceRoot}/core/os",
            "${workspaceRoot}/drivers",
            "${workspaceRoot}/platform/windows",
            "${workspaceRoot}/modules",
            "${workspaceRoot}/modules/gdnative/include",
            "${workspaceRoot}/modules/voxel/thirdparty/fast_noise_2/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\PROJETS\INFO\GODOT\Engine\godot_fork2\modules\voxel\generators\graph\voxel_generator_graph.cpp ]:
    D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\CORE\OS\RW_LOCK.H
Translation Unit Configurations:
[ D:\PROJETS\INFO\GODOT\Engine\godot_fork2\modules\voxel\generators\graph\voxel_generator_graph.cpp ]:
    Process ID: 10664
    Memory Usage: 43 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
    Includes:
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\EDITOR
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\CORE
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\CORE\MATH
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\CORE\BIND
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\CORE\HELPER
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\CORE\IO
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\CORE\OS
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\DRIVERS
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\PLATFORM\WINDOWS
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\MODULES
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\MODULES\GDNATIVE\INCLUDE
        D:\PROJETS\INFO\GODOT\ENGINE\GODOT_FORK2\MODULES\VOXEL\THIRDPARTY\FAST_NOISE_2\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.28.29333\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.19041.0\CPPWINRT
        D:/PROJETS/INFO/GODOT/ENGINE/GODOT_FORK2/MODULES/VOXEL/GENERATORS/GRAPH
    Defines:
        _DEBUG
        UNICODE
        WINDOWS_ENABLED
        DEBUG_ENABLED
        TOOLS_ENABLED
        VOXEL_ENABLE_SMOOTH_VOXELS
    Standard Version: ms_c++14
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 43 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 27633
Number of files parsed: 9498
```

**Additional context**
I have both MSVC 2017 and 2019.

**Comment by sean-mcmanus** [comment]
That seems odd. Can you try setting your C_Cpp.intelliSenseCacheSize to 0? It may be using a corrupted .ipch file.

So the C++14 workspace has issues? Can you try changing it to use C++17?

I assume it builds in all cases, right?

**Comment by Zylann** [comment]
I tried setting `intelliSenseCacheSize` to 0, it did not fix the issue, even after a restart.

> So the C++14 workspace has issues? Can you try changing it to use C++17?

I tried changing `cppStandard` to `c++17`, it did not fix the issue. My `compilerPath` on the other hand is already targetting Visual Studio 2019.

> I assume it builds in all cases, right?

Yes

**Comment by sean-mcmanus** [comment]
I'll see if anyone else on our team has any ideas (on Monday).

**Comment by sean-mcmanus** [comment]
Your screenshot shows "std::std::" which is incorrect -- do you know what that would be occurring? Are your `#include` inside an extra `namespace std`?

**Comment by Zylann** [comment]
Oh, I haven't noticed that. Thats really odd. No I haven't seen the opening of an `std` namespace above this 🤔 Wouldnt it fail to compile? (it compiles fine)

**Comment by sean-mcmanus** [comment]
What's the 1st error you see when you open the `mutex` header (when you're reproing the bug).

**Comment by Zylann** [comment]
This is the first error I see inside `<shared_mutex>`:
![image](https://user-images.githubusercontent.com/1311555/148830496-016eab8f-1edf-4042-8aa0-014f7fe04256.png)

**Comment by sean-mcmanus** [comment]
Also, are you able to generate a preprocessed file with whatever simplest repro you have via running `cl.exe /EP /std:c++14 <file>` plus whatever other command line arguments are required to compile the TU? The errors in the preprocessed file may shed light on the root cause, because it'll show errors from all the headers, which are otherwise hidden unless the header is open.

Are you able to generate a repro using only system headers or does it require code from your project?

**Comment by sean-mcmanus** [comment]
I was asking for the 1st error in `mutex` not `shared_mutex` -- are you able to use Go to Def on mutex to open the `mutex` header?

**Comment by Zylann** [comment]
> I was asking for the 1st error in mutex not shared_mutex -- are you able to use Go to Def on mutex to open the mutex header?

Hard to tell what the repro is, it's a bit volatile. To look inside `mutex` I tried opening the project with no files open. Then I opened the file in my project that uses `std::mutex`, no error squiggles showed up yet. I opened `<mutex>` and this shows up:
![image](https://user-images.githubusercontent.com/1311555/148834071-2942d632-a35b-466d-8beb-12b69d80796d.png)

> Are you able to generate a repro using only system headers or does it require code from your project?

Alternatively, if I close and reopen the project while `<mutex>` is the only file open, it will reopen and have the same error. Not sure if that rules out the project though, because that doesnt happen in other workspaces.

I tried `cl.exe /EP /std:c++14 /I. /Iplatform/windows core/os/mutex.cpp > core/os/mutex.out.cpp` and obtained a 1Mb file, but once open in VSCode it had no Intellisense errors.

**Comment by sean-mcmanus** [comment]
The "invalid friend declaration" is because "condition_variable" is not being recognized as a type -- do you see errors around that definition or is it in an inactive region?

The squiggles in mutex will in part be determined by which TU (source file) it's chosen to be associated with. You can double check which TU is selected via looking at the Log Diagnostics output.

One thing to potentially double check is that the mutex.out.cpp is not causing a crash to be reported in the logging (which is another way no squiggles could occur). You'll also want to make sure that `platform/windows` is the only include path that is being passed to IntelliSense, otherwise the proprocessing would be different from what IntelliSense is doing (your previous logging showed a lot more include paths).
