### ISSUE TITLE
Running clang-tidy on active file highlights problems in other files as well

### ISSUE THREAD

**Issue by vadi2** [microsoft/vscode-cpptools#8643]
Bug type: General

- C/C++ Extension Version: v1.8.0-insiders2

When I run "C/C++: Run code analysis on active file", my Problems view gets lit up with 100's of errors in files other than the one I was focused in. I'd expect it to highlight problems only on the file I've asked it to check?

**Comment by sean-mcmanus** [comment]
Is it showing errors for header files that are included by the TU? By default, the headerFilter is set to include the `${workspaceFolder}` -- you can check what is used in the debug logging (C_Cpp.loggingLevel set to "Debug"). You can also add folders to the `C_Cpp.codeAnalysis.exclude` setting. Otherwise, can you provide more repro info?

**Comment by vadi2** [comment]
Hmm, here is the command -

```
cpptools/runCodeAnalysis
/home/vscode/.vscode-remote/extensions/ms-vscode.cpptools-1.8.0-insiders2/bin/../LLVM/bin/clang-tidy
--header-filter=/workspaces/Mudlet
--quiet
/workspaces/Mudlet/src/TArea.cpp
--
-std=c++17
-I/workspaces/Mudlet/build/src
-I/workspaces/Mudlet/src
-I/workspaces/Mudlet/build/src/mudlet_autogen/include
-I/workspaces/Mudlet/3rdparty/communi/include/IrcCore
-I/workspaces/Mudlet/3rdparty/communi/include/IrcModel
-I/workspaces/Mudlet/3rdparty/communi/include/IrcUtil
-I/workspaces/Mudlet/3rdparty/edbee-lib/vendor/onig
-I/workspaces/Mudlet/3rdparty/edbee-lib/vendor/onig/enc/unicode
-I/workspaces/Mudlet/3rdparty/edbee-lib/edbee-lib
-I/workspaces/Mudlet/build/3rdparty/dblsqd
-I/workspaces/Mudlet/build/3rdparty/dblsqd/dblsqd_autogen/include
-I/workspaces/Mudlet/3rdparty/dblsqd
-I/usr/include/x86_64-linux-gnu/qt5
-I/usr/include/x86_64-linux-gnu/qt5/QtCore
-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork
-I/usr/include/x86_64-linux-gnu/qt5/QtUiTools
-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets
-I/usr/include/x86_64-linux-gnu/qt5/QtGui
-I/usr/include/lua5.1
-I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent
-I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia
-I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL
-I/usr/include/x86_64-linux-gnu/qt5/QtDBus
-I/usr/include/x86_64-linux-gnu/qt5/QtTextToSpeech
-I/usr/include/c++/10
-I/usr/include/x86_64-linux-gnu/c++/10
-I/usr/include/c++/10/backward
-I/usr/local/include
-I/usr/lib/llvm-11/lib/clang/11.0.1/include
-I/usr/include/x86_64-linux-gnu
-I/usr/include
-DAPP_BUILD="-dev"
-DAPP_TARGET="mudlet"
-DAPP_VERSION="4.14.1"
-DBOOST_ALL_NO_LIB
-DINCLUDE_3DMAPPER
-DINCLUDE_FONTS
-DINCLUDE_OWN_QT5_KEYCHAIN
-DINCLUDE_UPDATER
-DINCLUDE_VARIABLE_SPLASH_SCREEN
-DIRC_STATIC
-DLUA_DEFAULT_PATH="/usr/local/share/mudlet/lua"
-DQTKEYCHAIN_NO_EXPORT
-DQT_CONCURRENT_LIB
-DQT_CORE_LIB
-DQT_DBUS_LIB
-DQT_GUI_LIB
-DQT_MULTIMEDIA_LIB
-DQT_NETWORK_LIB
-DQT_OPENGL_LIB
-DQT_TEXTTOSPEECH_LIB
-DQT_UITOOLS_LIB
-DQT_WIDGETS_LIB
-DZIP_EXTERN=
-xc++
-Wno-pragma-pack
66900 warnings and 1 error generated.
Error while processing /workspaces/Mudlet/src/TArea.cpp.
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1286:4: error: "You must build your code with position independent code if Qt was built with -reduce-relocations. "         "Compile your code with -fPIC (and not with -fPIE)." [clang-diagnostic-error]
#  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
   ^
/workspaces/Mudlet/3rdparty/edbee-lib/edbee-lib/edbee/edbee.h:27:20: warning: class 'Edbee' defines a non-default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator [cppcoreguidelines-special-member-functions]
class EDBEE_EXPORT Edbee : public QObject
                   ^
/workspaces/Mudlet/3rdparty/edbee-lib/edbee-lib/edbee/edbee.h:43:1: warning: redundant access specifier has the same accessibility as the previous access specifier [readability-redundant-access-specifiers]
public slots:
^~~~~~~~~~~~~
/workspaces/Mudlet/3rdparty/edbee-lib/edbee-lib/edbee/edbee.h:34:1: note: previously declared here
public:
^
```

edbee for example is not an include in this file or it's direct header. The codebase [is open-source](https://github.com/Mudlet/Mudlet), to replicate you can run the analysis on the `TArea.cpp`.

**Comment by sean-mcmanus** [comment]
Your workspace is `/workspaces/Mudlet`, so by default our extensions set the `--header-filter=/workspaces/Mudlet`, which will cause `/workspaces/Mudlet/3rdparty/edbee-lib/edbee-lib/edbee` headers to give errors (i.e. "by design"). The solution is to either set the C_Cpp.codeAnalysis.clangTidy.headerFilter yourself or set C_Cpp.codeAnalysis.exclude, although you may actually get better performance if you add `"/workspaces/Mudlet/3rdParty": true` to C_Cpp.files.exclude , which will also prevent those symbols from being tag parsed (assuming you don't need those symbols). Does that solve your issue?

**Comment by vadi2** [comment]
I adjusted my `.vscode/settings.json` to the following, since this ought to be shared by everyone in the project:

```json
{
    "cmake.configureOnOpen": true,
    "cmake.configureSettings": {
        "CMAKE_TOOLCHAIN_FILE": "${workspaceFolder}/3rdparty/vcpkg/scripts/buildsystems/vcpkg.cmake"
      },
    "Lua.runtime.version": "Lua 5.1",
    "C_Cpp.files.exclude": {
      "${workspaceFolder}/3rdparty": true
    }
}
```

However it did not seem to be picking it up: https://gist.github.com/vadi2/aac67848619dbffbeae9ab6f0966c071

Excluding 3rdparty is a nice bonus, though I was really hoping to be able to focus on errors at just one file at a time - that's what I understood by "run analysis on the active file".

**Comment by sean-mcmanus** [comment]
You should change your C_Cpp.files.excude to `"3rdparty": true` -- the "${workspaceFolder}" is not supported (VS Code's files.exclude doesn't support that either).

The Run on Active File is running clang-tidy on the active file, but clang-tidy has to compile the entire TU, which is the source file and all the dependent headers, which must include the edbee.h at some point (if it's not supposed to, then the includePath or defines could be incorrect), and the headerFilter setting regex says which headers should have issues reported for. You could set it C_Cpp.codeAnalysis.clangTidy.headerFilter to "" to change it to "one file at a time".

**Comment by vadi2** [comment]
Gotcha. Still the same deal with the settings adjustment: https://gist.github.com/vadi2/d7f32026871ce45e79e066d045c91668 to:

```json
{
    "cmake.configureOnOpen": true,
    "cmake.configureSettings": {
        "CMAKE_TOOLCHAIN_FILE": "${workspaceFolder}/3rdparty/vcpkg/scripts/buildsystems/vcpkg.cmake"
      },
    "Lua.runtime.version": "Lua 5.1",
    "C_Cpp.files.exclude": {
      "3rdparty": true
    }
}
```

Am I doing something wrong?

**Comment by sean-mcmanus** [comment]
There's a bug -- we don't handle the exclude correctly when it's part of C_Cpp.files.exclude, but it works with files.exclude. I've filed bug https://github.com/microsoft/vscode-cpptools/issues/8676 .

A workaround is to use files.exclude or "**/3rdparty" -- assuming you don't have other folders named 3rdparty in your workspace that you don't want to exclude.

**Comment by vadi2** [comment]
Works great, thanks!
