### ISSUE TITLE
Debugging with lldb 11 doesn't work

### ISSUE THREAD

**Issue by vadi2** [microsoft/vscode-cpptools#8644]
Bug type: Debugger

**Describe the bug**
- C/C++ Extension Version: v1.8.0-insiders2

**To Reproduce**
Debugging with lldb 11 doesn't work:
```
error: unknown option: --interpreter=mi
error: unknown option: --tty=/dev/pts/1
Use 'lldb-11 --help' for a complete list of options.
[1] + Done(1)                    "/usr/bin/lldb-11" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-tltmi5ql.2rm" 1>"/tmp/Microsoft-MIEngine-Out-0s4qjota.4mc"
```
GDB runs fine however.

**Comment by WardenGnaw** [comment]
`lldb-11` is not an MI based debugger.

You will need to use `lldb-mi` in order to debug using lldb as the debugger.

**Comment by vadi2** [comment]
I have no idea what lldb-mi is? I just installed clang from Debian's apt and it doesn't work out of the box.

**Comment by WardenGnaw** [comment]
LLVM has dropped including `lldb-mi` in their packages. You will need to build it from the source. 

Folks have been able to build it on Ubuntu, but similar steps can be taken for Debian. 

See https://github.com/microsoft/vscode-cpptools/issues/5415 for more information.
