### ISSUE TITLE
Progress bar for parsing a large compile_commands.json file

### ISSUE THREAD

**Issue by hriekehof** [microsoft/vscode-cpptools#8647]
Type: Feature Request

I searched the open issues and didn't find anything so i hope this is not a duplicate :)

I work with a project with a larger `compile_commands.json` file. It's around 102MB.
The parsing and the intellisense seem to work fine but i have to wait around 3-5min until everything is
setup correctly. 
It would be great to have a progress bar in the bottom right corner for example which indicates the progress of the intellisense engine when parsing a larger compile command database.

**Comment by sean-mcmanus** [comment]
We currently just a show a flame icon and don't have any progress reporting code when parsing a compile_commands.json.

Is the project with a 102 MB compile_commands.json open source? I'm guessing LLVM might generate one of a similar size.

**Comment by bobbrow** [comment]
It seems like something we should add as part of #8405.  Maybe we should track it there.

**Comment by sean-mcmanus** [comment]
That is independent. https://github.com/microsoft/vscode-cpptools/issues/8405 is a UI change. If we decide to do that, then this issue would require additional changes to gather that status, which is not currently available.

**Comment by bobbrow** [comment]
Yes, #8405 is a UI change which links to a [discussion here ](https://github.com/microsoft/vscode/issues/129037)talking about supporting progress as well.  Though we can keep this open if we don't want to do them together.

**Comment by hriekehof** [comment]
The project is not open source unfortunately :)

In my case the flame icon does not appear at the beginning. The 5min have no visual indications that intellisense is doing something. But there is a `cpptools` process with 30 threads running. According to activity monitor i'm on mac os currently. 
After that initial time the flame icon appears and also additional files get discovered. At this point i also can jump to definitions etc.

**Comment by sam-mccall** [comment]
If you're looking for examples:
 - llvm-project's compile_command.json is "only" 7MB on my machine
 - my old checkout of chromium had a 166MB compile_commands.json (and that's from 2018! I bet it's bigger now)

FWIW, we never migrated LLVM's compile_commands.json parsing to our "nice" JSON parser, because it had a high level API that wanted to eagerly parse/decode/heap-allocate all those objects, and that hurt startup of chromium too much. It's still using an event-based YAML parser, and only decodes the keys upfront...

**Comment by hriekehof** [comment]
The compile db i use has 12500 entries. The actual `command` string is quite long for every entry so file size might be a little misleading
