### ISSUE TITLE
"Go to Definition" disappers since last month

### ISSUE THREAD

**Issue by worldwalk** [microsoft/vscode-cpptools#865]
hi,

I use win vscode 1.13.1, but from last monday, the "Go to Definition" and "Peek Definition" disappears for my C++ files.  

when start up vscode, it show below error msg from console:

              Updating C/C++ dependencies...

              Downloading package 'C/C++ language components (Windows)'  Failed. Retrying...

**Comment by sean-mcmanus** [comment]
Can you wait longer? It's trying to download our files.

**Comment by worldwalk** [comment]
the full log: 

Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying...Waiting 32 seconds...
Failed at stage: downloadPackages
Error: connect ETIMEDOUT 23.66.239.97:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

Finished

**Comment by sean-mcmanus** [comment]
The download is 5 MB. It's trying to download https://go.microsoft.com/fwlink/?linkid=852141 . Are you able to download that manually? We're not sure why people are hitting these download issues. Maybe our download server is having problems.

**Comment by worldwalk** [comment]
yes, I can download the Bin_Windows.zip within a few seconds manually.

cannot connect to download server.   except this 'C/C++ language components (Windows)', other components also need download.

is there FAQ how I manually install this ?

**Comment by sean-mcmanus** [comment]
Manually downloading the files isn't recommended, because we also do some installation steps afterward. You could try downloading all the Win32 files listed in the package.json in the extension folder, unzip it to `.vscode/extensions/ms-vscode.cpptools-0.12.0`, and then adding a file named install.lock . See https://github.com/Microsoft/vscode-cpptools/issues/284

**Comment by worldwalk** [comment]
thanks so much! it works!

I guess the cpptools extension firstly remove old files, then try to download new files....  so if download fail, the whole func not work.   why not we firstly download, then remove old files...

**Comment by sean-mcmanus** [comment]
We don't remove old files. VS Code is supposed to remove all the old extension files during the update process. When it installs the new version, none of the downloaded files should exist, so we need to download them.

**Comment by worldwalk** [comment]
ok, I will close the issue, thanks.
