### ISSUE TITLE
cpptools cannot be installed offline

### ISSUE THREAD

**Issue by KKyang** [microsoft/vscode-cpptools#866]
My PC does not have internet. Thus cannot complete the installation cause cpptools required internet to download stuffs. Will there be an offline installer?

**Comment by bobbrow** [comment]
Thank you for your feedback.  Offline installation support is on our backlog being tracked by #298.

**Comment by sean-mcmanus** [comment]
Fixed with 0.14.4. Offline installers are at https://github.com/Microsoft/vscode-cpptools/releases .
