### ISSUE TITLE
Debug: adapter not respecting threadId for stopped events

### ISSUE THREAD

**Issue by gregg-miskelly** [microsoft/vscode-cpptools#867]
_From @isidorn on July 3, 2017 9:20_

Original comments from user:

- VSCode Version: 1.13.1
- OS Version: Fedora 21

Steps to Reproduce:

1. Place a breakpoint to interrupt execution.
2. Once the breakpoint is hit, step over (F10).

The focus in the call stack window will change from the current thread's call stack to the first call stack in the list. To continue stepping, the correct call stack (thread) must first be selected. 

This make stepping through threaded code quite tedious. 

The expected behaviour is that the focus in the call stack window remains at the top of the call stack for the current thread and doesn't change.

_Copied from original issue: OmniSharp/omnisharp-vscode#1617_

**Comment by gregg-miskelly** [comment]
_From @isidorn on July 3, 2017 9:20_



The issue here is that the `stop` event coming from the debug adapter does not respect the threadId for the `next` request from vscode.

Example, there are threads with the following ids 1, 2, 3. User focuses thread 1, preses step, VSCode sends `next` request for threadId: 1, adapter incorrectly sends stopped event for threadId: 2 with allThreadsStopped: true. Adapter should respect the threadId in the `next` request.

As the user is pointing out this makes debugging tedious and it would be great to fix.

**Comment by gregg-miskelly** [comment]
@Anketell is your scenario that you have the same code running on multiple threads and so when you hit step your original breakpoint winds up getting hit on the first thread?

**Comment by gregg-miskelly** [comment]
_From @Anketell on July 3, 2017 23:54_

@gregg-miskelly apologies, I didn't mention that I am running C++. FWIW, it was different code running on different threads.

**Comment by gregg-miskelly** [comment]
@Anketell: A few more questions to try and get your bug to the right place:

1. You are using the Microsoft C++ VS Code extension correct?
2. What OS are you on? 
3. If Windows, what debug adapter 'type' in your launch.json?
4. If using MIEngine, are you using LLDB or GDB?
5. The behavior you are seeing is that you hit a breakpoint on a thread other than the main thread, you do a step, and it acts like it is stepping the main thread?

**Comment by gregg-miskelly** [comment]
_From @Anketell on July 5, 2017 0:22_

@gregg-miskelly 

1. Yes, I have raised an issue under vscode-cpptools.

2. See above.

3. N/A

4. GDB

5. No. It focuses the correct stack (not main) after the break then steps the correct thread (currently focused) but incorrectly focuses the main thread immediately after the step. 

Having used GDB extensively for well over a decade directly and also with various front ends, it tracks the correct thread. Somewhere in the adaptor it's getting lost.

_Sent from my HTC 0PJA10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gregg-miskelly** [comment]
@Anketell thanks! I will move your issue. Hopefully the folks over there can help.

**Comment by Anketell** [comment]
See: Issue https://github.com/Microsoft/vscode-cpptools/issues/864

**Comment by gregg-miskelly** [comment]
Closing this one since @Anketell already opened another.
