### ISSUE TITLE
Align trailing comments at a fixed column value

### ISSUE THREAD

**Issue by mkriegel1976** [microsoft/vscode-cpptools#8672]
Type: Feature Request

First, let me thank you for the great work you're doing!!
I love clang-format as it's clean, fast and just awesome.

Rationale:
When AlignTrailingComments is enabled, the comments will be aligned if there are trailing comments over multiple lines.
The distance of the trailing comment is controlled via SpacesBeforeTrailingComments with the drawback, that show lines of code will have the "comments" close to longer lines of code. 
For the case that a trailing comment is on a long line of code, then it's mostly pushed so far too the right, that it's not visible anymore.

Feature request:
Align trailing comments on at a fixed column value.
e.g. SpacesBeforeTrailingComments: -60
Negative values indicate a fixed column, whereas positive values could indicated a relative distance for trailing comments.

Here's an example:
```
function_A(a, b, c, d);                                                                                                       // Trailing comment A
function_B_with_a_long_function_name(very_long_parameter_name, b, c, d);                                                      // Trailing comment B

function_C(a, b, c, d);                                                        // Trailing comment C
function_D(a, b, c, d);                                                        // Trailing comment D
``` 
With the empty line between the function calls, the alignment of trailing comments the "alignment" is broken.

Here's how I would wish the alignment would be:
```
function_A(a, b, c, d);                                                                     // Trailing comment A
function_B_with_a_long_function_name(very_long_parameter_name, b, c, d);                    // Trailing comment B

function_C(a, b, c, d);                                                                     // Trailing comment C
function_D(a, b, c, d);                                                                     // Trailing comment D
```
All comments are aligned on a fixed column position. In case the code line is longer than the trailing comment column, the comment could just be appended behind the code line with a distance of e.g. 3 spaces.

**Comment by sean-mcmanus** [comment]
You want to file a feature request on LLVM/clang-format. You could try https://github.com/llvm/llvm-project/issues .

Our team doesn't normally implement clang-format features.
