### ISSUE TITLE
Showing false error for private member non accessible inside friend function

### ISSUE THREAD

**Issue by sk-gaurav** [microsoft/vscode-cpptools#8677]
Bug type: Language Service

**Describe the bug**
- OS and Version: Mac OS Big Sur (11.6)
- VS Code Version: 1.63.2
- C/C++ Extension Version: v1.8.0-insiders2
- Other extensions you installed (and if the issue persists after disabling them): C++ Intellisense (v0.2.2)
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
If I try to access private member of a class inside the friend function, intellisense is referring as an issue. But code compiles fine and run properly. 

**Steps to reproduce**
Please look at the attached image

**Expected behavior**

**Code sample and logs**

- Code sample
- attached in the image

- Configurations in `c_cpp_properties.json`
- {
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
-------- Diagnostics - 1/15/2022, 9:48:22 AM
Version: 1.8.0-insiders2
Current Configuration:
{
    "name": "Mac",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "clang-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": []
}
Translation Unit Mappings:
[ /Users/gauravk/Documents/vscode/default/current/others/hello.cpp ]:
    /Users/gauravk/Documents/vscode/default/current/others/hello.cpp
Translation Unit Configurations:
[ /Users/gauravk/Documents/vscode/default/current/others/hello.cpp ]:
    Process ID: 87884
    Memory Usage: 30 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/local/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1
        /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include
        /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include
        /Library/Developer/CommandLineTools/usr/include
    Frameworks:
        /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks
    Standard Version: c++17
    IntelliSense Mode: macos-clang-x64
    Other Flags:
        --clang
        --clang_version=110000
Total Memory Usage: 30 MB

**Screenshots**

![Screenshot 2022-01-15 at 9 41 12 AM](https://user-images.githubusercontent.com/30268409/149608647-73c845f8-e5c6-4400-b927-90424958ca84.png)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. It doesn't repro with 1.7.1 (i.e. a regression).

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.1
