### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by scheung38** [microsoft/vscode-cpptools#868]
Using a basic example:

    int main()
    {
        return 0;
    }

Clicked Start without Debugging, then asked to select Environment:

How to run basic hello world.cpp here, do I need to setup additional configuration files?

**Comment by bobbrow** [comment]
Take a look at [this blog post](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/cc-extension-for-visual-studio-code/) which should have answers for most of your startup questions.  If anything is unclear or incorrect, feel free to open a new issue.
