### ISSUE TITLE
using WSL: "The language server crashed 5 times in the last 3 minutes. It will not be restarted."

### ISSUE THREAD

**Issue by fig02** [microsoft/vscode-cpptools#8682]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10.0.19043 + WSL Ubuntu 20.04
- VS Code Version: 1.63.2
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them): 
This issue happens on a clean install of vscode with c/c++ and WSL remote as the only extensions.
- If using SSH remote, specify OS of remote machine: n/a
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Booting up vscode with any repo (via WSL), I will get "Connection to server got closed. Server will not be restarted." 5 times, and then the error indicated in the title. After this happens, none of my expected intellisense features work because the program has crashed.

I've been using the same setup for years now on this same repo, and this only started happening about a month ago. Its not clear to me what updated, if anything, that started causing this issue. I have a very similar setup on my laptop and the issue does not happen there.
I have tried:
-fully uninstalling vscode from windows (including deleting the contents of Appdata/Roaming)
-fully uninstalling vscode server from wsl
-using a brand new/clean wsl instance
-using other repositories to test with (which lack c_cpp_properties.json, unlike the one I provided below)
-downgrading to older c/c++ extension verisons

and the issue still persists. The fact that it still happens using a new wsl installation tells me its probably windows side.

**Steps to reproduce**
Unfortunately this seems dependent on my specific setup, as explained above I start vscode on my desktop and it crashes right away. This does not happen with the same setup/repo on my laptop.

**Expected behavior**
I expect the errors to not occur and for the extension to boot correctly.

**Code sample and logs**

- Configurations in `c_cpp_properties.json`
https://pastebin.com/zm8P5a1w

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

https://pastebin.com/q4i5icwk

**Additional context**
Im not too experienced with using the debugger built into vscode, let me know if theres anything else I can provide.

![image](https://user-images.githubusercontent.com/22045047/149713604-d75126f3-fd09-40fb-a68f-d3b2a52b7281.png)
![image](https://user-images.githubusercontent.com/22045047/149713626-798b29b9-4c9a-4fc6-87ee-452a5178ac58.png)
![image](https://user-images.githubusercontent.com/22045047/149713651-e9d44d2a-de01-41b0-b9d8-e4e4b67387fc.png)

**Comment by sean-mcmanus** [comment]
This is https://github.com/microsoft/vscode-cpptools/issues/8312 -- it's fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.0-insiders2 . Another alternative is to update your bios.
