### ISSUE TITLE
Unable to use gdb in remote_ssh to Fedora35

### ISSUE THREAD

**Issue by Eplankton** [microsoft/vscode-cpptools#8689]
![捕获](https://user-images.githubusercontent.com/86543401/150134985-16d2daaa-9673-485a-ad08-eb1074255ef4.PNG)

I have set the externalConsole as:false

**Comment by Eplankton** [comment]
...And something more funny is that,after waiting for about half an hour,the breakpoints works!! But i can't get anything in terminal stil
![2](https://user-images.githubusercontent.com/86543401/150144613-fb2a4c05-9c41-4311-af74-f8cf40c789f9.PNG)
![3](https://user-images.githubusercontent.com/86543401/150144622-eccec579-706c-4f0d-b0d7-7be437f107a8.PNG)
![捕获](https://user-images.githubusercontent.com/86543401/150144631-582c6175-6f96-4166-af8e-196510a2cf1f.PNG)
l

**Comment by Eplankton** [comment]
You must wait for a long long time then

**Comment by Eplankton** [comment]
![5](https://user-images.githubusercontent.com/86543401/150145855-5b5e5f94-63d9-4793-9abb-a76dc4ff92a9.PNG)

**Comment by WardenGnaw** [comment]
In order to assist with your issue, can you share your `launch.json` and also paste the text in the Debug Console here in a text format instead of images?

**Comment by Eplankton** [comment]
> In order to assist with your issue, can you share your `launch.json` and also paste the text in the Debug Console here in a text format instead of images?

Thanks for your concern , Sir.
But I have already figured out a way to fix the bug . It seems to be a gdb problem instead of a vscode-cpptools error.
I try to start gdb directly in the terminal and then it says : `Missing spereate debuginfod Download xxx/lib64/xxx.so`
And the downloading speed is so slow that it is what i describe the image "It STOPs for a LONG time when debugging".
So, the method to workaround is clear : ( In my Fedora35 ) `sudo dnf debuginfo-install glibc-2.34-11.fc35.x86_64 libgcc-11.2.1-7.fc35.x86_64 libstdc++-11.2.1-7.fc35.x86_64`
Then the problems solved, i can smoothly use vscode-cpptools to debug or etc.

**Comment by Eplankton** [comment]
The gdb has to be set as " not to download debuginfod itself " ,
And then i restart the gdb again ,it suggest as i post `dnf debuginfo-install glibc-2.34-11.fc35.x86_64 libgcc-11.2.1-7.fc35.x86_64 libstdc++-1
![捕获](https://user-images.githubusercontent.com/86543401/150275386-5f62b7fb-4d56-4ce8-9b54-b915779c492c.PNG)
1.2.1-7.fc35.x86_64`to download some libs which are missing in my environment,
