### ISSUE TITLE
Debugging fails when windows binaries at linked with /PDBPageSize > 4k 

### ISSUE THREAD

**Issue by chrdavis** [microsoft/vscode-cpptools#8690]
Bug type: Debugger

Debugging fails when windows binaries at linked with /PDBPageSize > 4k (/PdbPageSize:[4096|8192|16384|32768]).  This is a new feature in LLD/MSVC to support PDBs > 4GB.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.8.2
