### ISSUE TITLE
Go To Definition for 'auto' typed variables (and return values)

### ISSUE THREAD

**Issue by sebastianzander** [microsoft/vscode-cpptools#8699]
Type: Feature Request

I could not find anything regarding the function of being able to go the definition of the type that is behind a certain occurrence of `auto`. Neither here in the issues nor with a web search. Although it may be a bug and should already be working, I doubt it. This is why I create this feature request. IntelliSense is able to easily resolve the type behind `auto` and show it in the balloon/tooltip, but there is no easy way to go to the definition of it (e.g. via Ctrl+Click on `auto`). Especially if there is a complex "hierarchy" of typedefs/usings and if the function that returns the object also utilises auto or is a template, it is a pain to navigate through so many files and places until the definition is found.

**Comment by sean-mcmanus** [comment]
Go to definition on "auto" and/or Go to Type Definition on either auto or the variable should work. Can you provide more info on the case that isn't working for you?

It sounds like you may be hitting an issue related to typedefs/using.

**Comment by sebastianzander** [comment]
I am having the issue with a huge code base at work. I tried the feature yesterday in a personal project and there it worked. The differences between the projects, environments and IDE configuration are manifold, however. I don't see any differences between the way the typedefs/usings are declared. In my work's code base, if I explicitly declare a variable with a _typedef/using_, "go to definition" works as intended.

Example of a simple _using_: `using portIndex_t = std::size_t;`
Nothing special.

The machine at work (Windows 10) is connected to a workstation (Ubuntu 20.04.1) via SSH using the Visual Studio Code _SSH - Remote_ extension. Additionally I use the _clangd_ and _CodeLLDB_ extensions.

Here is the local configuration of _C/C++_ extension:

```
"C_Cpp.clang_format_fallbackStyle": "",
"C_Cpp.intelliSenseEngineFallback": "Enabled",
"C_Cpp.intelliSenseEngine": "Disabled",
"C_Cpp.autocomplete": "Disabled",
"C_Cpp.errorSquiggles": "Disabled",
"C_Cpp.addNodeAddonIncludePaths": true,
"C_Cpp.autocompleteAddParentheses": true,
"C_Cpp.default.cStandard": "c17",
"C_Cpp.formatting": "clangFormat",
"C_Cpp.updateChannel": "Insiders",
```

Here is the remote configuration of _C/C++_ extension:

```
"C_Cpp.default.intelliSenseMode": "clang-x64",
"C_Cpp.default.compileCommands": "${workspaceFolder}/compile_commands.json",
"C_Cpp.intelliSenseMemoryLimit": 16276,
```

I don't know, maybe the configuration is incorrect, already. Next week I want to test that when I create a totally new .cpp file with e.g. `using id = std::size_t;`, maybe a `auto foo() { return id { 0 }; }` and some `const auto &var = foo();` whether that works or not. I will keep you updated.

**Comment by sean-mcmanus** [comment]
If you're usng clangd with intelliSenseEngine disabled, then Go to Definition requests are being handled by clangd and not our extension and the other C_Cpp.* settings won't be used.

**Comment by sebastianzander** [comment]
Thank you for clarifying. I thought clangd only acts as an information provider to Visual Studio Code and the C/C++ extension. I am a little confused over the interaction of both extensions. At least regarding clangd making use of some C_Cpp.* settings. I am sorry to have bothered you.

**Comment by sean-mcmanus** [comment]
Yeah, with C_Cpp.intelliSenseEngine set to "Disabled" all the language service features are disabled from our extension (along with some other features that aren't strictly language service related), but debugging should still work.
