### ISSUE TITLE
Support virtual workspaces

### ISSUE THREAD

**Issue by shuffle2** [microsoft/vscode-cpptools#8706]
Type: Feature Request

There is a previous issue with this topic: https://github.com/microsoft/vscode-cpptools/issues/7483

The issue was resolved by marking that the extension does not support virtual workspaces.

In my case, I'd like to be able to use intellisense when using live share feature (in fact, I thought this worked before? Maybe I'm mis-remembering). Currently, the extension is disabled when connected to a live share session.

**Comment by sean-mcmanus** [comment]
@shuffle2 Yeah, I believe our extension is supposed to work with the Live Share extension, but we're unlikely to support virtual workspaces in the near future since we require file URIs.

@jureid might have more info on how to use Live Share.
