### ISSUE TITLE
Links in browse path not recognised as legit headers

### ISSUE THREAD

**Issue by nitrologic** [microsoft/vscode-cpptools#872]
To reproduce start with simple c++ program in which the dependency uses a file link (ncurses.h->curses.h).

#include <ncurses.h>

Note the include file is "not found in browse path" even though the /usr/include does have an ncurses.h file as show here:

lrwxrwxrwx 1 root root    8 Feb 19  2016 ncurses.h -> curses.h

**Comment by sean-mcmanus** [comment]
I've reproed the issue. It doesn't repro on Windows (via hard links).

**Comment by sean-mcmanus** [comment]
Fix has been released.
