### ISSUE TITLE
C/c++ intellisense with clang and cmake not detecting libraries

### ISSUE THREAD

**Issue by Fabxx** [microsoft/vscode-cpptools#8729]
Bug type: General

**Describe the bug**
- OS and Version: Kali Linux Rolling 2021.4
- VS Code Version: 1.63.2 - 899d46d82c4c95423fb7e10e68eba52050e30ba3 - x64
- C/C++ Extension Version: v1.8.0
- Other extensions you installed (and if the issue persists after disabling them): c-cpp-cmake-project generator, cmaketools, cmake, c/c++ extension pack.
- A clear and concise description of what the bug is: Despite trying everything found on stackoverflow and other websites (and the official ms guide too), i can't find external libraries at all, regargind either Qt, or GTK, or anything else that i need to develop something. ALso re-writing the folder path in include like #include <qt5/QtCore/qcoreapplication.h> doesn't help.
Yes i tried to use c_cpp_properties.json with the includepaths too, nothing. tried changing configuration from clang to gcc/g++ and changing the intellisense mode too, nothing. Here are the files  about my configs:

**Expected behavior**

**Screenshots
![Screenshot_20220127_095650](https://user-images.githubusercontent.com/30447649/151325756-8b93c6c5-ccdd-4fd0-9387-5210f62c9e47.png)
**

**Additional context**
[c_cpp_properties.json.txt](https://github.com/microsoft/vscode-cpptools/files/7949039/c_cpp_properties.json.txt)
[tasks.json.txt](https://github.com/microsoft/vscode-cpptools/files/7949040/tasks.json.txt)
[CMakeLists.txt](https://github.com/microsoft/vscode-cpptools/files/7949057/CMakeLists.txt)

**Comment by revix-0** [comment]
LIttle udpate, running code as root, makes the recursive search work in the Qt5 folder, as user, even if i move the libraries to the Desktop where my group user has access, it won't read them.

**Comment by sean-mcmanus** [comment]
You have `"configurationProvider": "ms-vscode.cmake-tools"` set, so IntelliSense configuration is coming from there -- is that extension properly configured? You can run the C/C++: Log Diagnostics command to see more info about what IntelliSense configuration is being used. I'm not sure what "recursive search" you're expecting to work or which includes are not being found.

**Comment by revix-0** [comment]
I fixed by reworking cmakelists.txt, the macro looking for include paths was broken
