### ISSUE TITLE
Question: supported file schemes

### ISSUE THREAD

**Issue by worksofliam** [microsoft/vscode-cpptools#8733]
Hi

I have an extension that provides two new file system schemes: `member` and `streamfile`.

I did a quick search and it looks like the expected scheme pretty much all over the place is `file`.

Is it possible that in the future we might be able to add more file system support? `member` and `streamfile` are for filesystems on an IBM i (prev. AS/400) where users can write C and C++. I was hoping to be able to make use of content assist functionality.

**Comment by sean-mcmanus** [comment]
All our code in cpptools/cpptools-srv closed source binaries expected "file" URIs. We don't currently have plans to support other file system schmes. I'm not familiar with member or streamfile schemes.

**Comment by worksofliam** [comment]
@sean-mcmanus Thanks for getting back to me so quickly.

The likely action I should take is to find an extension that will simply add the language tools for C and CPP.
