### ISSUE TITLE
watch window doesn't work as expected on m1 mac

### ISSUE THREAD

**Issue by pr0m1see** [microsoft/vscode-cpptools#8734]
Bug type: Debugger

**Describe the bug**
- macOS Monterey 12.0.1
- VS Code Version: (version 1.63)
- C/C++ Extension Version: v1.7.1
- Other extensions you installed (and if the issue persists after disabling them): CodeLLDB v1.6.10

All the methods from others don't work for me. See the picture below.
![image](https://user-images.githubusercontent.com/34335870/151486755-46035000-9e50-499d-9943-8e2a5a30a603.png)

**Comment by WardenGnaw** [comment]
Can you share your `launch.json` and share the logs in the `debug console` when you add the following to your `launch.json`:
```
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

**Comment by Ch1ldr3n** [comment]
Thanks for reply. Here is my `launch.json`.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            /* ------ these three options are mandatory ------ */
            "type": "lldb",
            "request": "launch",
            "targetArchitecture": "arm64",
            "name": "C++ Debug", /* ------ some optional attributes available to all launch configurations ------ */
            "preLaunchTask": "g++ compile", /* ------ Many debuggers support some of the following attributes: ------ */
            "program": "${fileDirname}/${fileBasenameNoExtension}.out",
            "args": [],
            "environment": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "externalConsole": false,
            /* ------ Customizing GDB or LLDB ------ */
            "MIMode": "lldb",
            "outputCapture": "std"
        }
    ],
    "logging": {
        "engineLogging": true,
        "traceResponse": true
    }
}
```
As for the debug logs, I can only get this from the `debug console`:
![image](https://user-images.githubusercontent.com/34335870/151644803-773a2df4-9451-451b-a2cc-29a4495041cc.png)



> Can you share your `launch.json` and share the logs in the `debug console` when you add the following to your `launch.json`:
> 
> ```
> "logging": {
>    "engineLogging": true,
>    "traceResponse": true
> }
> ```

**Comment by WardenGnaw** [comment]
`"type": "lldb"` is the CodeLLDB extension, you will want to post your issue there.

https://github.com/vadimcn/vscode-lldb/issues
