### ISSUE TITLE
Intellisense is abnormal while coding c++, typing something under a line comment in a namespace

### ISSUE THREAD

**Issue by BH2WFR** [microsoft/vscode-cpptools#8735]
Bug type: Language Service

**Describe the bug**
- OS and Version:         Windows 10 21H1 x64 
- VS Code Version:       1.63.2
- C/C++ Extension Version:     1.8.1
- Other extensions you installed (and if the issue persists after disabling them):    
    - **C/C++**
    - **C++ intellisense,** 
    - **Visual Studio IntelliCode,** 
    - **Keil Assisstant**
- Compiler:       **Keil MDK v5, arm compiler v6(armclang)**
- If using SSH remote, specify OS of remote machine:   no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Description of Problem**
like this gif, I found a problem while coding c++, the intellisense is abnormally working while I type something in a namespace with the other namespace with a same name before it.

If I remove the line comment, it works normally, but when I add any comment, it works abnormally, and can't give me items in the privious namespace with the same name.

Also, if this problem occers, **enumerations** defined front also can't be recognized when I type its name.

**I resently asked it in StackOverFlow and a comment says that It might be a bug of the extension... so may I know if it is a real bug or just I had typo on my code ...**

Here is the GIF screen record of my problem...

<img src="https://i.stack.imgur.com/It2Vg.gif]" width="70%">

Problem Code
```
namespace Gunseban{
	int asdf = 1234;      // **elements inside the namespace, I want the intellisense to recognize these**

	class shsh{
		public:
		int c = 20;
		
	};	
	namespace MYTEST{
		int dgm = 300;
	}
}
// two namespaces with same name
namespace Gunseban{
	//==== **This comment cause the problem, If I add this, Intellisense can't recognize the items defined in the previous namespace**
	int bb = 30;	// **this comment also cause the problem**
	
	class MyProblem{
	  public:
	    int cc = 90;
			
	};
}
```

**Comment by sean-mcmanus** [comment]
I'm not able to repro the bug. The extension "C++ intellisense" provides conflicting functionality so it might be caused by that extension. Can you disable that and try again?

Are you able to repro the problem with the gcc, clang, or cl compilers?
