### ISSUE TITLE
downloading c++ packages failed...

### ISSUE THREAD

**Issue by wangjihu** [microsoft/vscode-cpptools#874]
![image](https://user-images.githubusercontent.com/19356729/27981753-bcc8ed68-63c3-11e7-8090-df02284785ef.png)

**Comment by sean-mcmanus** [comment]
That means it had some problem download and is trying again. Make sure your internet connection is good. Does it fail after retrying 4 times? See https://github.com/Microsoft/vscode-cpptools/issues/865 for a similar report. They were able to work around the issue via manually installing the download.

**Comment by traffictse** [comment]
Hey man I met the same problem... Have you solved it yet?

**Comment by wangjihu** [comment]
@TrafficTse ,,,,connect your internet by using mobile 4g

**Comment by traffictse** [comment]
@wangjihu Gosh! It really worked! After I connected the computer with mobile 4G! What's wrong with Microsoft???

**Comment by scropion86** [comment]
same issue i tried WIFI and Mobile Network connection and both failed to download the package
only the below lines appearing in the Output  
```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)'  Failed. Retrying...(4983 KB) 
```

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
