### ISSUE TITLE
Provide keys to color status bar working (flame symbol)

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-cpptools#875]
_From @ajitid on June 29, 2017 15:14_

Don't know what it is called
![27671023-90a1cbfe-5cae-11e7-9d7e-825f6b10825e](https://user-images.githubusercontent.com/26769888/27695099-90c6aa48-5d0b-11e7-8527-2eaa1879b17d.PNG)
Are there any keys to color this?

_Copied from original issue: Microsoft/vscode#29873_

**Comment by aeschli** [comment]
_From @bpasero on June 29, 2017 15:34_

Currently not, these colors are provided by extensions and are not theme aware as far as I know. But I think @aeschli was thinking of giving extension authors more access to theme colors?

**Comment by aeschli** [comment]
Yes, extension authors can now use one of the known theme colors, so they can be changed by users. @ajitid Do you know which extension this comes from?

**Comment by aeschli** [comment]
_From @ajitid on July 11, 2017 10:51_

That screenshot is of C/C++ extension from Microsoft

**Comment by aeschli** [comment]
Use `StatusBarItem.color` with a `ThemeColor`
https://code.visualstudio.com/docs/getstarted/theme-color-reference is the list of known theme colors.

**Comment by sean-mcmanus** [comment]
Thanks for letting us know about this. We should have a fix soon.

**Comment by sean-mcmanus** [comment]
@aeschli Actually, I don't see a ThemeColor that matches our desired scenario. We want a color for "busy" in the status bar -- some error color like red would work. Maybe we should change the UI to not rely on color and use some other progress indicator UI? Reworking the UI will probably not be till after our pending 0.12.1 update.

**Comment by sean-mcmanus** [comment]
We just got rid of the color (using the default foreground), since the image conveys the meaning well enough.

**Comment by sean-mcmanus** [comment]
@ajitid Fix has been released.
