### ISSUE TITLE
Custom configuration provider ready handling is broken

### ISSUE THREAD

**Issue by jscissr** [microsoft/vscode-cpptools#8752]
Bug type: Language Service

Configuration providers can signal that they are ready by calling `CppToolsApi.notifyReady`.
But the cpptools extension does not actually wait until the provider is ready:

- [`provideCustomConfiguration`](https://github.com/microsoft/vscode-cpptools/blob/6ad565886b9cbfca9876c05d9a0fd1967d4291f6/Extension/src/LanguageServer/client.ts#L1966) expects the provider to already be ready, and throws an error otherwise.
- [`updateCustomBrowseConfiguration`](https://github.com/microsoft/vscode-cpptools/blob/6ad565886b9cbfca9876c05d9a0fd1967d4291f6/Extension/src/LanguageServer/client.ts#L1824) does not even do that, and requests a configuration before `notifyReady` is called.

Here are steps to reproduce the `${this.configurationProvider} is not ready` error with the CMake Tools extension:

1. Install ms-vscode.cpptools and ms-vscode.cmake-tools extensions
2. Create a new folder
3. Create an empty file `main.cpp` in this folder
4. Open the folder in VS Code
5. Open Developer Tools (in Help menu)
6. Open the `main.cpp` file
7. Run 'CMake: Configure' command and select a compiler
8. Observe `rejected promise not handled within 1 second: Error: ms-vscode.cmake-tools is not ready` in the console

## How to fix this

When this code was originally introduced, there was an error handler which ignored the 'is not ready' error: https://github.com/microsoft/vscode-cpptools/commit/2f931d930d6ba3ec37a2fb7e082d1d8d353cd078#diff-cf95416e0b96ac189174d8648175492ff64a57e9214f434eb8e5e983a16342e3R590 (Go to `client.ts` and click 'Load diff'.)
But this no longer exists.
This suggests that the problem could be fixed by simply returning when the provider is not ready, rather than throwing an error.
The same could be done for `updateCustomBrowseConfiguration`, which currently does not check `isReady` as mentioned above.

I could submit a PR if you agree with this approach.

**Comment by sean-mcmanus** [comment]
This code got changed in https://github.com/microsoft/vscode-cpptools/pull/4671 .

@Colengms ?

**Comment by Colengms** [comment]
Hi @jscissr .  Thanks for reporting this.

When I follow the repro steps, I don't see the error message logged.  Rather, I'm prompted to create a CMakeLists.txt file, as none currently exists.  Are there some necessary steps that I might be missing?

Indeed, `provideCustomConfiguration` should not be throwing an error.  It could simply return without the error, as `updateCustomConfigurations` will be called to refresh configurations for all tracked documents when the provider is ready.  I can fix that.  Similarly, `updateCustomBrowseConfiguration` could simply return, as it will be called again when the provider is ready.  Error messages resulting from either of these operations prior to the provider being ready could be ignored for now, as the configurations would be refreshed when the provider is ready.

**Comment by jscissr** [comment]
Hi @Colengms . After a very recent update of either VS Code or cpptools, the reproduction steps for cmake-tools no longer work. But as you have already fixed the bug, I guess that's no longer relevant. Thanks a lot for fixing this!

**Comment by Colengms** [comment]
Fixed in 1.9.1
