### ISSUE TITLE
identifiers aren't identified

### ISSUE THREAD

**Issue by Nixo371** [microsoft/vscode-cpptools#8753]
I've been using size_t for some time now, but recently IntelliSense started saying "identifier "size_t" is undefined". My code compiles and works as expected but I still get those squiggles and error messages. It also will make NULL an error "identifier "NULL" is undefined". And there's a really strange one that completely boggles me where in c_cpp_properties.json I get a yellow squiggle with the error message, "Cannot find "C:\Users\nicol\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr/bin/gcc"."
![image](https://user-images.githubusercontent.com/93920983/152021169-dada0c19-20bc-4fb7-a785-a474d066e202.png)
![image](https://user-images.githubusercontent.com/93920983/152020807-0d0228a6-372d-4d31-be15-61f7a8b56f8f.png)
![image](https://user-images.githubusercontent.com/93920983/152021228-def9dc8e-a281-4561-84f0-91fce73ed409.png)

**Comment by bobbrow** [comment]
Are you able to access that path?  Did you recently update Windows or your WSL instance?

The most reliable way to work with WSL is via the [Remote WSL](https://code.visualstudio.com/docs/remote/wsl-tutorial) extension.  We strongly recommend you use that extension to connect to your workspace instead of reaching into WSL from a Windows process.  We aren't making any improvements to our WSL support in Windows processes because it works seamlessly via the Remote WSL VS Code extension which runs the C++ extension as a Linux process instead.

**Comment by Nixo371** [comment]
I currently have the Remote WSL extension installed (although if there is a separate process to "link" it I have not done it nor do I know how to do it). I can find the file in File Explorer.
![image](https://user-images.githubusercontent.com/93920983/152033667-7be47b31-de9b-450f-8bd2-f8d3a9c1fc72.png)

**Comment by bobbrow** [comment]
Take a look at the tutorial link I pasted above.  You need to open the folder with WSL for it to work.  You can click the green `><` button in the bottom left corner of the status bar to get started.

I'm not sure why the extension was unable to access the path.  Did you have to accept an elevation prompt in Windows to open it?

**Comment by Nixo371** [comment]
Opening a remote WSL session worked, is there any way to make it so it opens it automatically? Or do I have to open a remote WSL session every time I open VScode?

**Comment by bobbrow** [comment]
If believe that if you run VS Code from your WSL terminal (using `code .`) in the folder you want to open, that it will automatically set it up for you.  If you have VS Code in your Taskbar, you can also right click on the icon and reopen any of your previous sessions.

**Comment by Colengms** [comment]
@bobbrow WSL2 changed how files can be accessed from the host OS.  Now it support: `\\wsl.localhost\<distroname>\` i.e. 
```
dir \\wsl.localhost\Ubuntu-20.04\usr\bin
```

The legacy WSL support could be updated to look there.  Or, the legacy WSL support could be removed entirely in favor of the Remote SSH extension.

**Comment by bobbrow** [comment]
If we make any changes, I'd prefer to remove the legacy WSL support and point folks to the Remote extensions.
