### ISSUE TITLE
Automatically set target architecture in tasks.json and launch.json to unblock build/debug on M1 chip

### ISSUE THREAD

**Issue by jureid** [microsoft/vscode-cpptools#8755]
Type: Feature Request

Unblock "Build and debug active file" on macOS ARM64 (M1 chip) by automatically adding "--target=x86_64-apple-darwin-gnu" to the args array in tasks.json and setting "targetArchitecture" to "x86_64" in launch.json.

If using CMake Tools, can we automatically set "-DCMAKE_OSX_ARCHITECTURES=x86_64"?

Next step would be to get the debugger binaries to run natively on Apple Silicon ARM64.: https://github.com/microsoft/vscode-cpptools/issues/7035

**Comment by jureid** [comment]
@WardenGnaw can you confirm these are the correct properties / values?

**Comment by WardenGnaw** [comment]
You will want `--target= x86_64-apple-darwin-gnu`. Possible cross compilation targets are listed in the clang reference. 

https://clang.llvm.org/docs/CrossCompilation.html

**Comment by michelleangela** [comment]
>If using CMake Tools, can we automatically set "-DCMAKE_OSX_ARCHITECTURES=x86_64"?

Since this workaround is specific to the cpptool extension's default build settings that it defines in tasks.json, the extension should not also modify the default value of a build setting from another extension such as CMake Tools.
