### ISSUE TITLE
Local Error: There is no formatter for cpp files installed

### ISSUE THREAD

**Issue by Laser42** [microsoft/vscode-cpptools#8761]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 x64
- VS Code Version: 1.63.2
- C/C++ Extension Version: v1.7.1
- Other extensions you installed (and if the issue persists after disabling them):
Material Theme
Code Spell Checker
Docker
ESList
formate: CSS/LESS/SCSS
HTML Preview
oScript Language
PowerShell
XML Tools
- If using SSH remote, specify OS of remote machine: none
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
Formatting (Alt+Shift+F) doesn't work: I got the error: There is no formatter for cpp files installed

**Steps to reproduce**

1. Go to 'File -> New File'
2. Select language C++
3. Paste the code below

**Expected behavior**

I expected my code to be formatted

**Code sample and logs**

![image](https://user-images.githubusercontent.com/40018028/152167876-689dd064-2c1e-4c63-9b80-9fdf791bfee0.png)
no c_cpp_properties.json

**Screenshots**

![image](https://user-images.githubusercontent.com/40018028/152167511-43ec609a-210a-4d48-a4e7-344cd303d160.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
Our extension requires that the file be saved first and not be an "Untitled" document.
