### ISSUE TITLE
VS Code instantly closes when I go to C/C++: Edit Configuration(UI)

### ISSUE THREAD

**Issue by dastangosu** [microsoft/vscode-cpptools#8771]
Issue Type: <b>Bug</b>

Go to C/C++: Edit Configuration(UI) through Command Palette (Cmd+shift+p).
VS Code instantly closes.

Extension version: 1.8.3
VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

**Comment by sean-mcmanus** [comment]
Is this the same as https://github.com/microsoft/vscode/issues/142043 ?

**Comment by dastangosu** [comment]
I am not sure, but I have just updated to mac OS Monterey version 12.2. Before the update it was working fine. What can I do to solve the problem?

**Comment by Colengms** [comment]
Hi @dastangosu Has the C/C++ extension been activated yet, or is that command triggering activation?  (You can determine this by enabling `"C_Cpp.loggingLevel": "Debug"` and checking if there is any output to the C/C++ output channel yet, prior to running the command).

Could this be a symptom of [this issue](https://github.com/microsoft/vscode/issues/141696), occurring as the C/C++ extension is first activated?  I don't know how it would cause the main VS Code process to crash.  Though, technically, it shouldn't be possible for an extension to cause the main VS Code process to crash...

**Comment by HarryZhang0911** [comment]
I am experiencing an issue on my end. VSCode crashed as soon as I tried to open the UI for C_CPP_Properties

**Comment by sean-mcmanus** [comment]
@HarryZhang0911 Can you file a bug at https://github.com/microsoft/vscode/issues ? I don't think our extension could be responsible for that.
