### ISSUE TITLE
Strikethrough text for deprecated code snippets

### ISSUE THREAD

**Issue by TerensTare** [microsoft/vscode-cpptools#8772]
Type: Feature Request

The Java extension from Red Hat "decorates" deprecated code snippets with a strikethrough. It would be cool if we could have such feature on the C/C++ extension as well.

Example from the Java extension:
![image](https://user-images.githubusercontent.com/37905314/152411812-7434d729-b124-47fb-8171-7fab9444c3b8.png)

**Comment by sean-mcmanus** [comment]
You mean code marked with the `[[deprecated]]` attribute? https://en.cppreference.com/w/cpp/language/attributes/deprecated

**Comment by TerensTare** [comment]
Yes, I should've specified that.
There are also non-standard extensions such as MSVC's [__declspec(deprecated)](https://docs.microsoft.com/en-us/cpp/cpp/deprecated-cpp?view=msvc-170) and GCC/Clang's [__attribute__(deprecated)](https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/Common-Function-Attributes.html#Common-Function-Attributes) which might strikethrough deprecated code on their respective intellisense mode.

**Comment by sean-mcmanus** [comment]
I've filed a feature request on VS at https://developercommunity.visualstudio.com/t/Add-strikethrough-rendering-for-CC-/1653887 . If our shared IntelliSense engine adds support for that, then I think it'd be pretty easy for us to add the "deprecated" (https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide).
