### ISSUE TITLE
[cppvsdbg] Rust: Variables are not refreshed immediately and thus, have to step twice

### ISSUE THREAD

**Issue by selvavm** [microsoft/vscode-cpptools#8774]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.64
- C/C++ Extension Version: v1.8.2 (also tried pre-release and older versions. same issue)
- Other extensions you installed (and if the issue persists after disabling them): Rust-analyzer and issue persist
- When executing a line, the variables are not updated immediately. However, the values are shown as some abstract temporary variable. Stepping through next line, variables are updated and the abstract temporary variable is deleted

**To Reproduce**
```
fn main() {
    let a = 10;
    let b = &"test".to_string();
    let c = "test";
    let d = "test".to_string();
    let e = Some(10);
    let f = Some("test".to_string());
    let g = vec!["a".to_string(), "b".to_string()];
    let mut h = HashMap::new();
    h.insert("a".to_string(), "aa".to_string());
    h.insert("b".to_string(), "bb".to_string());
    let i = &e;
    let j = &f;
    let k = &g;
    let l = &h;
    println!("{a},{b},{c},{d}");
}
```
```
        {
            "name": "(Windows) Debug Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceRoot}/target/debug/${workspaceRootFolderName}.exe",
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "console": "internalConsole",
            "preLaunchTask": "cargo build",
        },
```
```
        {
            "label": "cargo build",
            "type": "shell",
            "command": "cargo +stable-msvc build"
        },
```

![image](https://user-images.githubusercontent.com/16543422/152473699-9db75837-243f-423c-99e9-586baac716ce.png)
From the image, you can see that `g` is assigned in line 111 and the debugger is in line 112. However, g is still not available but at the top the values are seen as `alloc....`. Now stepping to next line, `g` is updated.
![image](https://user-images.githubusercontent.com/16543422/152473757-b00f619c-8e28-480a-a97c-1bd58d11e249.png)

**Comment by WardenGnaw** [comment]
The debugger uses the current information from the current line it is stopped at and PDB information to retrieve debug information. 

This would all be dependent on how Rust compiles and generates its debug information. 

If you look into the disassembly of this program, do you see if `g` has been created when you are stopped at "line 112"?

One possibility is that Rust does not actually create variable `g` until you hit "line 113". 

Also, `cppvsdbg` is intended to be used for C/C++, but it also can "just work" for Rust. As this is the C/C++ extension, our primary focus is for C/C++.
