### ISSUE TITLE
Loading huge PDBs with cppvsdbg is extremely slow (+ a workaround)

### ISSUE THREAD

**Issue by talkeren** [microsoft/vscode-cpptools#8775]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.62.1
- C/C++ Extension Version: 1.7.1 (EDIT: also with 1.8.2)

As part as my job I have to work with chromium source code and debug it, but I couldn't do the debugging part with vscode since it took few minutes just to launch the debugger. It takes for it a long time to load chrome.dll.pdb (~2GB+ PDB) and some more big pdbs. So that is why I used Visual Studio instead for debugging. (Not only me, my whole team had the same issue).
I found out the reason for this bug. I think that this is a suitable place to create an issue for it.
**TL;DR: It seems that it is caused by a compiler bug in the x86 version of msdia140.dll**

**To Reproduce**
Build chormium:
https://chromium.googlesource.com/chromium/src/+/HEAD/docs/windows_build_instructions.md
Use this launch.json: (Replace cppdbg with cppvsdbg)
https://chromium.googlesource.com/chromium/src/+/main/tools/vscode/launch.json5
Put a breakpoint somewhere in chromium source code and launch. Now it would take few minutes to launch.

**The bug and the solution**
So I decided to dive dipper and figure out why it is so slow, while in Visual Studio it is fast. I was even more confused when I saw that both Visual Studio and vsdbg uses the same infrastructure to debug and load pdbs (vsdebugeng.dll and specifically msdia140.dll to parse and load PDBs). (For vscode it is in `%HOMEPATH%\.vscode\extensions\ms-vscode.cpptools-1.7.1\debugAdapters\vsdbg\bin`)
I couldn't take the msdia140.dll from visual studio because it is x64 while vsdbg is x86, but there was a x86 version of it in visual studio that I took but it still was slow.
Luckily the x86 version of that dll had symbols.
I saw that the slow function that took few minutes to complete was `TPI1::fInitHashToPchnMap`. Luckily there are sources online for that class:
https://github.com/microsoft/microsoft-pdb/blob/master/PDB/dbi/tpi.cpp#L527
This function initialize an hash map for TI (type infos). The function that was called a lot is `TPI1::precForTi`, which load the TI from the PDB for hash calculation. but when I read the code, it seems that only for old versions of PDBs (`hdr.vers < impv70`) it should load that info. In newer version of PDBs (when I assume that new is for at least a decade, that code seems to be old...) the code just read the hash map from the PDB. I checked while debugging, and saw that the version in my PDB is impv80, so it shouldn't read all the TIs from the PDBs.
https://github.com/microsoft/microsoft-pdb/blob/master/PDB/dbi/tpi.cpp#L596-L599
![image](https://user-images.githubusercontent.com/24737697/152535532-d440e57f-950c-4e19-9722-82387cc4bbe4.png)

So I reversed engineered it, and saw something weird: 
![pdb_bug](https://user-images.githubusercontent.com/24737697/152535477-38975b39-86f7-469c-9817-1b507ac585ed.png)
The first if is checking the version, all the other elseifs are inline `TPI1::hashPrec`. So you can see that `TPI1::precForTi` is **ALWAYS** called, even if it isn't used. So it seems like a compiler bug. I don't understand how it is even possible that the compiler produced such output since `TPI1::precForTi` isn't a const function, so the compiler calls a non const function that isn't called in the code!

Anyway, the fix was to change the order of some opcodes, so `TPI1::precForTi` will be called only after the test:

```
5E22D903     56             PUSH ESI
5E22D904     8D85 70FFFFFF  LEA EAX,DWORD PTR SS:[EBP-90]
5E22D90A     8BCB           MOV ECX,EBX
5E22D90C     50             PUSH EAX
5E22D90D     E8 FE1F0000    CALL msdia140.5E22F910
5E22D912     81BB B0030000  CMP DWORD PTR DS:[EBX+3B0],1310977
5E22D91C     8B78 04        MOV EDI,DWORD PTR DS:[EAX+4]
5E22D91F     0F83 D9000000  JNB msdia140.5E22D9FE
```

=>

```
5E22D903     81BB B0030000  CMP DWORD PTR DS:[EBX+3B0],1310977
5E22D90D     0F83 EB000000  JNB msdia140.5E22D9FE
5E22D913     56             PUSH ESI
5E22D914     8D85 70FFFFFF  LEA EAX,DWORD PTR SS:[EBP-90]
5E22D91A     8BCB           MOV ECX,EBX
5E22D91C     50             PUSH EAX
5E22D91D     E8 EE1F0000    CALL msdia140.5E22F910
5E22D922     8B78 04        MOV EDI,DWORD PTR DS:[EAX+4]
```

And suddenly the debugger launches in few seconds! (and everything works, including type infos)

I assume that it doesn't happen in Visual Studio because probably that bug isn't present in the x64 compilation of this DLL.

**EDIT:** I see in the release notes of 1.8.2 that it supposes to switch to the x64 version of the binaries, which could theoretically solve this issue at least for x64 Windows, but I upgraded and my extension still has the x86 binary with the bug.

**Comment by talkeren** [comment]
Hey, I just saw a comment from an Edge developer that mentions that the Edge team still uses version 1.1.3:
https://github.com/microsoft/vscode-cpptools/issues/8738#issuecomment-1024737712

I tried to downgrade to that version and the debugger launched quickly, so I won't be surprised if the Edge team were encountered with the same issue in later version...
I took a look on the msdia140.dll from that version and the bug is really not presented there:
![pdb_bug2](https://user-images.githubusercontent.com/24737697/152594774-0cb528e6-50af-41f4-970e-630fd1b1129f.png)
So working version of msdia140.dll is: 14.16.27027.1
Version with the bug: 14.29.30130.2
(the compilation looks totally different as you can see in the picture, so there probably some big change in the compilation at some point that introduced this bug, a lot more optimizations, or deoptimization in this case....)

**Comment by WardenGnaw** [comment]
@talkeren Thank you for looking into this and reporting where to investigate.

This will be fixed in the next release.
