### ISSUE TITLE
cpptools stuck using 100% cpu, probably ignoring C_Cpp.codeAnalysis.exclude setting

### ISSUE THREAD

**Issue by prosenboim** [microsoft/vscode-cpptools#8792]
Bug type: Language Service

Using VScode 1.64 on Mac, with Ubuntu 18 as remote machine. Extension version is 1.8.2.

cpptools process is using 100% CPU while stuck at 15% of parsing files. Commads like "Goto Definition" or "Goto Declaration" do not work.

According to the log it attempts to parse files, which it is supposed to exclude. I have a setting in settings.json
```
    "C_Cpp.codeAnalysis.exclude": {
        "${workspaceFolder}/containers/builder/wb/whitebox_sdk/**": true,
        "${workspaceFolder}/whitebox_sdk/**": true
    },
```

But I see in its output
```
[Trace - 12:06:22 PM] Received notification 'cpptools/debugLog'.
Params: {
    "text": "tag parsing file: {0}",
    "stringId": 77,
    "stringArgs": [
        "/home/dn/cheetah/containers/builder/wb/whitebox_sdk/include/opennsa/time.h"
    ],
    "indentSpaces": 2
}
```

and in "C/C++" output:
```
  tag parsing file: /home/dn/cheetah/containers/builder/wb/whitebox_sdk/include/soc/kbp/alg_kbp/include/kbp_mem_test.h
  tag parsing file: /home/dn/cheetah/containers/builder/wb/whitebox_sdk/include/soc/kbp/alg_kbp/include/kbp_pcie.h
  tag parsing file: /home/dn/cheetah/containers/builder/wb/whitebox_sdk/include/soc/kbp/alg_kbp/include/kbp_portable.h
  tag parsing file: /home/dn/cheetah/containers/builder/wb/whitebox_sdk/include/soc/kbp/alg_kbp/include/key.h
  tag parsing file: /home/dn/cheetah/containers/builder/wb/whitebox_sdk/include/soc/kbp/alg_kbp/include/model.h
```

[cpptools_output.txt](https://github.com/microsoft/vscode-cpptools/files/8014374/cpptools_output.txt)
[c_cpp_output.txt](https://github.com/microsoft/vscode-cpptools/files/8014375/c_cpp_output.txt)

**Comment by sean-mcmanus** [comment]
Also, replace the `${workspaceFolder}/containers/builder/wb/whitebox_sdk/**` with something else, such as `containers/builder/wb/whitebox_sdk` or `**/containers/builder/wb/whitebox_sdk` (same with the other exclude). You can test the glob via using VS Code's files.exclude setting to see if the folder gets removed from the Explorer view (although our `C_Cpp.files.exclude` also supports excluding folders external to the workspace folder).
