### ISSUE TITLE
Semantic colorization tokens are randomly missing for the 1st TU created when a configuration provider is used

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8799]
Use `"configurationProvider": "ms-vscode.cmake-tools"`. Have a file open on workspace startup.

Bug: Seemingly random identifiers may be missing semantic tokens -- the tokens will re-appear after the file is closed, waiting for the cpptools-srv to shutdown, and then reopening the file, and/or if you switch to the file from another file after the configuration provider has already initialized.

**Comment by sean-mcmanus** [comment]
I repro this with 1.8.4/5, but not with our current debug bits, so maybe this could be fixed or the process of debugging somehow interferes with the repro?

**Comment by sean-mcmanus** [comment]
Oh -- I got a repro with our latest release bits, but not debug bits -- might be timing related.

**Comment by Colengms** [comment]
Fixed in 1.9.1
