### ISSUE TITLE
Feature Request: Linting

### ISSUE THREAD

**Issue by assumptionsoup** [microsoft/vscode-cpptools#88]
Some form of linting would be really awesome.  Something basic to help reduce the number of "Oh, I forgot a semi-colon/colon/bracket/type" could go a long way!

**Comment by ivomachado** [comment]
Any updates on this?

**Comment by ryancoppa** [comment]
This would be a great feature, especially if it offered lint-as-you-type functionality similar to other linting extensions for VSCode.

**Comment by rdlaner** [comment]
I think this feature is quite valuable. Would absolutely love to see it added! Any chance it will be in a future update?

**Comment by sean-mcmanus** [comment]
It's added in 0.11.0. Change the C_Cpp.intelliSenseEngine setting to Default.
