### ISSUE TITLE
Update documentation to reflect Tasks 2.0.0 format

### ISSUE THREAD

**Issue by aaccioly** [microsoft/vscode-cpptools#880]
[The C/C++ for VS Code (Preview)](https://code.visualstudio.com/docs/languages/cpp#_getting-started) page is still referencing `tasks.json` version `0.1.0`. 

We should [convert it to version `2.0.0`](https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200]).

**Comment by bobbrow** [comment]
The docs have been updated.  Sorry for not closing it sooner. We lost track of this issue.
