### ISSUE TITLE
complier path error

### ISSUE THREAD

**Issue by william2ai** [microsoft/vscode-cpptools#8801]
Bug type: General

**Describe the bug**
- OS and Version: Win10 21H1
- VS Code Version: Latest 22Jan
- C/C++ Extension Version: Latest
- Other extensions you installed (and if the issue persists after disabling them): None,only C++
- A clear and concise description of what the bug is.
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit
Cannot find: C:\Users\William\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\rootfs\usr/bin/gcc
However gcc could be complied under my WSL 1.
I've read the previous issues and found it maybe cause by WslFs file system format problems.
In case of it, I have to create a .vscode folder and create a c_cpp_properties.json each time, which is really inconvienient.

**Expected behavior**

About 2 months ago, same MinGW configuration, it works out smoothly.

**Screenshots**

![](https://s3.bmp.ovh/imgs/2022/02/49bd752e0b7fdfd4.png)

![](https://s3.bmp.ovh/imgs/2022/02/6ecdc289105a5c63.png)

![](https://s3.bmp.ovh/imgs/2022/02/d135261c79793112.png)

**Additional context**

Thanks a lot!!

**Comment by sean-mcmanus** [comment]
We don't currently support accessing WSL/Linux paths from Windows. You should connect to WSL directly via the Remote - WSL extension, which will run the Linux version of our extension in WSL.

**Comment by sean-mcmanus** [comment]
You can set the C_Cpp.default.compilerPath setting.

**Comment by william0620** [comment]
Thanks, I solved my problem!
