### ISSUE TITLE
About how the json works

### ISSUE THREAD

**Issue by developer6hyx** [microsoft/vscode-cpptools#8804]
OS : MacOS Big Sur 11.5

Compiler : macports g++11 (g++-mp-11)

VSCode version : 1.64.0

---------------

Today I installed g++11 through macports. At first it didn't work, with an error message:

> fatal error: wchar.h: No such file or directory

Then I added something in both `.zshrc` and `.bash_profile` : 

```
export SDKROOT=`xcrun --show-sdk-path`
```
and it DID work when I typed `/opt/local/bin/g++-mp-11 -o main main.cpp` to compile the source code (in both zsh and sh).

But it DIDN'T work when I use cpptools, with a `tasks.json` like

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++ build active file",
			"command": "/opt/local/bin/g++-mp-11",
			"args": [
				"-fdiagnostics-color=always",
				"-g",
				"${file}",
				"-o",
				"${fileDirname}/${fileBasenameNoExtension}"
			],
			"options": {
				"cwd": "${fileDirname}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": "build",
			"detail": "编译器: g++-mp-11"
		}
	]
}
```

and the error message `fatal error: wchar.h: No such file or directory` appeared again.

I wonder how the json works. The compiler could work in bash and zsh but it couldn't work in such a json file.

Could you please help me how to solve the problem?

(PS : I'm really bad at English so perhaps there are lots of grammar mistakes)

Thank you very much.

**Comment by sean-mcmanus** [comment]
I believe the cppbuild task launches the command directly with running it in a shell, and you added an environment variable to your shell. You could try changing the tasks.json type to "shell" or launching VS Code from the shell to have it inherit the environment variable.

**Comment by developer6hyx** [comment]
Now it works. Thank you a lot for your reply. 

PS : change the tasks.json type to "shell" DOESN'T work for me(I tried it yesterday), but launching VSCode from zsh DOES work. 

At last, thank you for your reply again.

**Comment by sean-mcmanus** [comment]
In the future, if we get more reports like this, we could potentially detect the scenario and show a warning message like we do with cl.exe on Windows when it's not launched from the developer command prompt.
