### ISSUE TITLE
Close the visual studio and reopen it by right clicking on it and selecting run as administrator. I had similar problem and this worked for me

### ISSUE THREAD

**Issue by Neeraj1213** [microsoft/vscode-cpptools#8805]
Close the visual studio and reopen it by right clicking on it and selecting run as administrator. I had similar problem and this worked for me

_Originally posted by @priyamadhu in https://github.com/microsoft/vscode-cpptools/issues/1329#issuecomment-381384275_

**Comment by Neeraj1213** [comment]
It worked.

**Comment by sean-mcmanus** [comment]
I don't understand what this issue is for.
