### ISSUE TITLE
Problem with suggestion

### ISSUE THREAD

**Issue by xyf007** [microsoft/vscode-cpptools#8809]
Issue Type: <b>Bug</b>

After I updated to the latest version of vscode, the suggestion didn't depend on the frequency. For example, when I type `#i` it always suggests `#if` now, but `#include` before.

Extension version: 1.8.4
VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:17:47.733Z)
OS version: Linux x64 5.4.0-96-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 3915)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.52GB (0.16GB free)|
|Process Argv|--unity-launch --crash-reporter-id 5e6fd454-e9d1-4891-b375-ea8fd2eebaf4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop341:30404997
vsrem710cf:30416617
vscscmwlcmc:30433760

```

</details>

**Comment by sean-mcmanus** [comment]
It's working for me:
![image](https://user-images.githubusercontent.com/19859882/153102562-d18aa939-bdc7-4504-86a3-63d710e92cc8.png)

Can you provide a screenshot?

Do you have another extension installed that could be interfering?

**Comment by sean-mcmanus** [comment]
Also, if updating VS Code (and not our extension) caused the bug to occur, that implies there could be some bug with VS Code and not our extension.

**Comment by yerguntalasagar** [comment]
> It's working for me: ![image](https://user-images.githubusercontent.com/19859882/153102562-d18aa939-bdc7-4504-86a3-63d710e92cc8.png)
> 
> Can you provide a screenshot?
> 
> Do you have another extension installed that could be interfering?

Hello Sir I am facing this issue Can you please help me on this. I can't see any suggestion even after installing c\c++ intellisense in vs code

**Comment by xyf007** [comment]
![screenshot](https://user-images.githubusercontent.com/41227294/153316120-46897e43-14e9-4067-9112-1a573f2eaf67.png)

I searched the issues of VS Code but didn't find similar issues yesterday. And I have done nothing but update my VS Code.

**Comment by sean-mcmanus** [comment]
@yerguntalasagar The C/C++ IntelliSense extension is a different extension.

@xyf007 Your screenshot shows what is expected -- is the issue fixed for you now?

**Comment by sean-mcmanus** [comment]
Our C/C++ extension has never sorted completion results by frequency. Maybe VS Code itself or another extension was doing the sorting and then they changed?

**Comment by yerguntalasagar** [comment]
> 

Nothing has changed Sir I don't understand what to do. next month I have exams But I am stucked with this problem since last 15days. Kindly help me on this Sir. The C C++ IntelliSense not working in VS Studio Code. I have installed mingw64 for compile the code and for the Suggestions C C++.
