### ISSUE TITLE
syntax error checker c VS code mac os (found solution)

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#8817]
hello 
my VS code syntax error  checker for C language didn't work. someone can help me
thanks
![Schermata 2022-02-09 alle 14 48 32](https://user-images.githubusercontent.com/96428032/153214391-54ec4a8c-16ec-46ed-b65d-e1a8f7899c5b.png)

**Comment by sean-mcmanus** [comment]
Did you solve your issue?
