### ISSUE TITLE
On Windows vsdbg.exe is 32-bit and running out of memory when debugging large binaries

### ISSUE THREAD

**Issue by talkeren** [microsoft/vscode-cpptools#8818]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.64.0
- C/C++ Extension Version: 1.8.4

Recently some of the binaries in this plugin were changed to x64 bit (#7230). But some binaries are still 32-bit - specifically 
vsdbg.exe. So when debugging large binaries with large pdbs (chromium for example) - parsing structures and type infos seems to consume a lot of memory, which causes crashes. (It doesn't take a lot of time to crash vsdbg.exe when debugging chromium...)

**Comment by WardenGnaw** [comment]
Thank you for your feature idea. We may not be able to implement it immediately, but we will track the community reactions to determine where this might fit into our backlog.

**Comment by talkeren** [comment]
I can confirm that it is fixed on insiders version 1.9.1. Thank you.
