### ISSUE TITLE
[Intellisense] Hover-over suggestion shows comments from code block eliminated by preprocessor.

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode-cpptools#8827]
Bug type: Language Service

**Describe the bug**

- OS and Version:
- VS Code Version:

```none
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:23:11.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.15-76051515-generic
```

- C/C++ Extension Version: `v1.8.4`
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Create two implementations of a function controlled by a preprocessor switch...

```c
#if 0
// I DO NOT expect to see this description of `foo`
// param: bar can only be a value between 0 and 7
void foo (int bar) {}
#else
// I DO expect to see this description of `foo`
// param: bar can only be a value between 8 and 15
void foo (int bar) {}
#endif
```

2. Hover over `foo(...)` elsewhere in your code, and you will be shown the wrong comment block.

Obviously, this example is trivial, but in my real scenario the code comments I was being shown were very misleading and would have caused me to introduce a bug into the system.

**Expected behavior**

The editor already detects which blocks should be "darkened" to indicate they are commented out. It would be very helpful to use this same logic to decide whether or not a comment block should be shown when you hover over text.

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Hmm, I don't repro the issue on Linux (or Windows). Any idea what could be going different?

![image](https://user-images.githubusercontent.com/19859882/153520069-34282765-f5b1-48b7-835d-9888ac1a9890.png)

**Comment by zfields** [comment]
What versions of Linux and VSCode are you running? I will try and repro what you are seeing, or dig deeper into my own system.

Thanks,
Zak

**Comment by zfields** [comment]
Dang it, you're right. The contrived example I fashioned works as expected. :facepalm: 

In real life, I'm developing an embedded application and I'm using the generated files from the STM32Cube. The code in question is elided by the preprocessor, and highlighting (or lack thereof) works correctly. Unfortunately, the tool tip is failing. It has multiple implementations in different files, all of which VSCode can dig up with F12.

Thank you for your time. I apologize for not validating my trivial example code.

Unfortunately, it appears I cannot provide "simple steps" to reproduce the issue, so I will close.
