### ISSUE TITLE
Misleading error message when GDB is not installed

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#8836]
Bug type: Debugger

If I don't have GDB installed (yet), and try to use the 'build and debug active file' feature (on Linux, with g++), I get an error message: 

![image](https://user-images.githubusercontent.com/49173979/153512038-872c3ce3-84d8-4c84-8e94-d75bd39e2637.png)

However, all I have at this point is `tasks.json` (not `launch.json`, which it refs to), and there is no reference to `miDebuggerPath` in it.

It would be useful if this error message provided enough information to determine that the issue is that GDB needs to be installed.

**Comment by Colengms** [comment]
Same issue when trying to use clang++.  The error message could be more actionable.

**Comment by sean-mcmanus** [comment]
@elahehrashedi Should this moved to 1.11?
