### ISSUE TITLE
Automatic (recursive) include paths

### ISSUE THREAD

**Issue by decimad** [microsoft/vscode-cpptools#885]
I'm using this extension together with cmake-helpers. The include paths generated by cmake-helpers would suffice, but the default recursive ones still seem to be looked at by cpptools, resulting in multiple results where there should only be one. Is there a way to suppress the implicitly defined include paths?

**Comment by sean-mcmanus** [comment]
What feature are you seeing multiple results with? The recursive browse.path setting is still used by Go to Definition. You can add "*" to the end of the browse.path paths to remove the recursiveness.

**Comment by decimad** [comment]
I'm not all too sure which feature is responsible for which behaviour, so I'll describe the behaviour that I see:

"Ctrl+Left" finds functions and type-definitions. Though sometimes with multiple alternative files of which only one should be visible by the include paths configured by the cmaketools-helper extension. The others include temporary/result copies which I figure are found by the built-in recursive default paths.

When "Ctrl+Left" works but reports multiple results in its hover-tooltip, then the IntelliSense-engine is not able to find the type definitions for types defined in those files, as I suppose it can't decide on where to take definition from, but that is only my suspicion. In that case all those types are squiggled red visually.

**Comment by sean-mcmanus** [comment]
Ctrl+Left definitions are from the browse.path ("fuzzy" results). Hover and red squiggles are from results compiled using the non-recursive includePath setting. If you have red squiggles (without the missing header message) then you probably need to add correct "define"s. You can use files.exclude to suppress files/folders from being parsed by the tag parser.

**Comment by decimad** [comment]
Thank you for the information! I will try files.exclude today, that should absolutely do the trick. Will "Ctrl + Left" eventually use the IntelliSense-Information rather than the "fuzzy" results, maybe per project/global setting?

**Comment by sean-mcmanus** [comment]
Yes, Ctrl+Left click (Go to Definition) will eventually use the semantic-aware IntelliSense, but it requires a bunch or porting and infrastructure work, because the definitions are in different translation units, so we don't have an ETA. Go to Declaration would be easier to get working with IntelliSense since we have that data already in the translation unit, but I don't know if we're going to add that earlier or not.

**Comment by eddy-geek** [comment]
@sean-mcmanus is there a tracking issue for using semantic-aware IntelliSense for Go to Definition?

**Comment by sean-mcmanus** [comment]
@eddy-geek I guess this issue can track it. There might be an older issue tracking it too.

**Comment by sean-mcmanus** [comment]
@eddy-geek Actually, I found the tracking issue for the improved Go to Definition: https://github.com/Microsoft/vscode-cpptools/issues/255 .

**Comment by bobbrow** [comment]
Closing this old issue which seems to be resolved.  Please reopen or create a new issue if your question has not been answered yet.
