### ISSUE TITLE
20-60 minutes of 100% CPU usage

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8863]
In my case this is happening every time I open a project with `.vscode/c_cpp_properties.json`.
I've been searching the intelli sense cache database file in ` $HOME/Library/Caches/vscode-cpptools` but there is nothing in this folder:

```
$ ll  $HOME/Library/Caches/vscode-cpptools
total 0
```

This happens each time I open a c++ project, the fan start to run, it turns really hot and my laptop seems ready to take off... If I open two c++ projects at the same time, two `cpptools` processes are launched.

After those 20-60 minutes of 100% CPU usage, it calms down and after some time then intellisense starts to work. It works all the time along that I have vscode opened, but when I shutdown and open again it starts the same process.

I can't see any db icon on the bottom bar.

C/C++: v1.8.4
osx: 11.2.3

_Originally posted by @miqmago in https://github.com/microsoft/vscode-cpptools/issues/5574#issuecomment-1038420745_

**Comment by miqmago** [comment]
Thanks a lot for your help. I'm not really sure on what is going on, after setting up the debug mode, it went really really fast, it took about a couple of minutes at most. I'm planning to leave `debug` level on :)

I usually setup projects in a workspace manner, so I usually have `server`, `app` and `firmware` folders on the same workspace. The only one which has `c_cpp_properties.json` is the `firmware` one, but for each opened folder in the workspace it seems that it parses all the folders (and it finds headers inside `node_modules`).

It's also including folders like:
- `/usr/local/Cellar/boost/` (4.701 files)
- `/Applications/Xcode.app/Contents/` (1.371 files)
- `/usr/local/Cellar/` (+1.226 files other than boost)
- `**/node_modules/` folders (297 files)
- `/usr/local/include/` (101 files)

which I'm not using in my projects, I think that I should exclude as you proposed, definitively going to do it. The strange think is that they are not included in `c_cpp_properties.json`, but they are parsed anyway...

Sometimes it's useful to have some full library in the workspace, so it's easy to search for source files, examples, etc. But usually the same folder it's also in some other standard place. It's the case of `~/.platformio/packages/framework-arduinoespressif32`. The question is that it's scanned twice, once per workspace and another one per `.platformio` folder.

I've also found several `Tag parsing encountered an error, but it may not matter. Let us know if symbols in the file can't be found` (93 times), but the file is there... For example, it's the case of `~/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/mbedtls/mbedtls/md5.h`, etc.

**Comment by sean-mcmanus** [comment]
It was probably fast this time because the database was already built. The `/usr/local/Cellar` may be pulled in from the compiler querying. I'm a little on how the .platformio is causing duplicate suggestions, but you may be able to fix it by adding it to files.exclude for one of the workspace folders. It is normal for additional workspace folder to cause additional scanning, since different workspace folders could have different exclude or symbol parsing settings. The `Tag parsing encountered an error` error can usually be ignored unless you're able to open that file and find symbols missing.

**Comment by miqmago** [comment]
I can confirm that after adding the folders to `C_Cpp.files.exclude` I can still see once per workspace folder:

- `  Folder: /Applications/Xcode.app/...  will be indexed`
- `  Folder: /usr/local/include/ will be indexed`

And then:
- `  Processing folder (recursive): /usr/local/include/`
- `  Processing folder (recursive): /Applications/Xcode.app/`

It ends with `  Discovering files: 84727 file(s) processed`.

I've tried with:

```json
    "C_Cpp.files.exclude": {
        "**/.vscode": true,
        "/usr/local/Cellar": true,
        "**/node_modules": true,
        "/Applications/Xcode.app": true,
        "/Applications/Xcode.app/Contents/": true,
        "/Applications/Xcode.app/**/*": true,
        "/usr/local/include": true,
    }
```


I've also found that if I kill `cpptools` process, reload the window via F1 > Developer: Reload Window, `cpptools` process starts to 100% CPU. Output window shows all the folders that will be indexed (including `/Applications/Xcode.app`) then it says `  Discovering files: 84727 file(s) processed` and then `cpptools` remains using 100% CPU. It does not appear any message on the output window. I suppose that if I leave for 20-60 minutes it will automatically disappear...

<img width="1299" alt="Captura de Pantalla 2022-02-14 a les 23 24 42" src="https://user-images.githubusercontent.com/1849488/153956783-7305ed1e-6558-4928-9c1c-528645de72e0.png">

**Comment by sean-mcmanus** [comment]
The logging isn't accurate and doesn't take into account the excludes. The excludes are handled later on. Killing cpptools can leave the database in an invalid state if not enough time has occurred since the last database write, causing the database to need to be reparsed on reload. The files.exclude should cause our directory iterator to not iterate into those folders and also to not tag parse them. The way to confirm this is to make sure no "tag parsing" messages appear to files in folders that should be excluded.

**Comment by miqmago** [comment]
Ok, this seems to solve the problems, right now when reloading the project it seems to work smooth and fast... Maybe the huge amount of files to be parsed left `cpptools` unresponsive, killing it makes database corrupt and then it starts again and again...
Thanks a lot!! Crossing fingers for the next time that I restart computer, but seems to work fine right now!
