### ISSUE TITLE
Debug Disassembly View For Other Languages (e.x. Ada)

### ISSUE THREAD

**Issue by grochoge** [microsoft/vscode-cpptools#8866]
Type: Feature Request

The GDB debugging experience built in to the C/C++ extension works fairly well for Ada if the option to allow breakpoints anywhere is enabled. I'm assuming this would be similar for any other (native) language supported by GDB.

However I haven't found a way to launch the disassembly view.

Please add a way to open the disassembly view for language other than C/C++.

**Comment by WardenGnaw** [comment]
When stopped at a breakpoint, what do you see if you right click your source code? Is there no option for `Open Disassembly View`?

**Comment by hongshui3000** [comment]
I also can't find the disassembly view under the assembly code @WardenGnaw
https://github.com/microsoft/vscode/issues/141127

**Comment by grochoge** [comment]
@WardenGnaw Correct.

Right-clicking in C:
![image](https://user-images.githubusercontent.com/66436177/154512394-8876d96b-fc87-4cf8-a375-1b21f9b5a2dc.png)

Right-clicking in Ada:
![image](https://user-images.githubusercontent.com/66436177/154512591-12fd0479-6593-409b-8b67-32b94c8de4ba.png)

I now found out that I can right-click on the frame in the call stack and successfully Open Disassembly View though (this wasn't mentioned in the article first announcing the capability).

**Comment by WardenGnaw** [comment]
I believe for source file context menu, it looks at the supported languages for the debugger.
```
        "languages": [
          "c",
          "cpp",
          "cuda-cpp"
        ],
```
https://github.com/microsoft/vscode-cpptools/blob/49720023bd28b40bb1b1c6512fbec3c484576734/Extension/package.json#L2754-L2758

As we do not have assembly or ada as languages registered, it will not show in the source file context menu but the stack frame.
