### ISSUE TITLE
Break Lines with Allman doesn't "work"?

### ISSUE THREAD

**Issue by wizardlink** [microsoft/vscode-cpptools#887]
So, i usually actually work with Pico indent style, but allman applies the same "technique", and people know it better than Pico... So, when i break a line, on an if statement for example instead of going like this
```js
    if () 
    {
        
    }
    else
    {

    }
```
It actually goes like this
```js
    if (!client || !message || !args) 
        {
        
        }
        else
            {

            }
```
Which makes me loose some time with it... I use VSCode on Windows 10, does anyone know how i'd go on fixing this?

**Comment by sean-mcmanus** [comment]
That doesn't repro for me. Is some other extension causing the formatting? Are you doing some format on type or what?

**Comment by wizardlink** [comment]
No i literally had a clean and fresh VSC instance, never touched the editor before, i mean i did, but not in this computer, i changed some settings so now i can do it a little better, but i still can't press enter without breaking the line and having some space after it.

**Comment by sean-mcmanus** [comment]
Does the bug repro without our extension enabled? If so, you should file the bug with VS Code: https://github.com/Microsoft/vscode .

**Comment by wizardlink** [comment]
I'm sorry... It was 4AM when i opened this issue, i was looking on google about it, and the first results were other issues on this repository, so i thought it was vscode repo... Sorry for the trouble i caused!

**Comment by sean-mcmanus** [comment]
That's fine. It highlights a potential problem if our extension were to implement auto-indent on if/for/etc. statements. I think we'd need to add an auto-unindent rule after the { is added on the 2nd line.
