### ISSUE TITLE
VSCode cpptools generate a lot of `mmap_address.bin` files in project folder

### ISSUE THREAD

**Issue by hijkzzz** [microsoft/vscode-cpptools#8873]
VSCode version: 1.64.2
cpptools version: 1.8.4
System: Ubuntu 20.04 remote docker

My settings
```
{
    "editor.fontSize": 15,
    "ycy.reminderViewIntervalInMinutes": 50,
    "C_Cpp.intelliSenseCachePath": "~/.cache/vscode-cpptools/",
    "openInGitHub.defaultPullRequestBranch": "main",
    "openInGitHub.requireSelectionForLines": true,
    "C_Cpp.intelliSenseCacheSize": 1024,
}
```

![image](https://user-images.githubusercontent.com/19810594/154231965-f1bf634e-8021-4d09-8164-7ea5c336ba3d.png)

**Comment by michelleangela** [comment]
Those *.bin files are used to cache information about included header files (referred also as Intellisense Precompiled Header or 
 ipch files) to improve the performance of IntelliSense compilation.

To disable IntelliSense caching so that the extension will not create *.bin files, set `C_Cpp.intelliSenseCacheSize` to `0`.

For more information about IntelliSense caching, please see https://code.visualstudio.com/docs/cpp/faq-cpp#_what-is-the-ipch-folder

**Comment by hijkzzz** [comment]
> Those *.bin files are used to cache information about included header files (referred also as Intellisense Precompiled Header or ipch files) to improve the performance of IntelliSense compilation.
> 
> To disable IntelliSense caching so that the extension will not create *.bin files, set `C_Cpp.intelliSenseCacheSize` to `0`.
> 
> For more information about IntelliSense caching, please see https://code.visualstudio.com/docs/cpp/faq-cpp#_what-is-the-ipch-folder

Hi, I set "C_Cpp.intelliSenseCachePath": "~/.cache/vscode-cpptools/".
However, the cpptools also generate bin files in project root folder.
It is strange~~

**Comment by michelleangela** [comment]
Sorry, I did not look carefully that your `C_Cpp.intelliSenseCachePath` is set to `~/.cache/vscode-cpptools/`. The extension should only place cached files under that folder, assuming that setting is set only for the workspace.

Could you check that cache files are being written under `~/.cache/vscode-cpptools/`? Is `C_Cpp.intelliSenseCachePath` set in any other scope? For example, User vs Workspace scope and is the setting for the remote machine?

**Comment by hijkzzz** [comment]
Hi, it seems there is no folder named `~/.cache/vscode-cpptools/`

And, the tools also generate a lot of bin files today.
![image](https://user-images.githubusercontent.com/19810594/155488519-17b12a1a-a1ad-4ecc-b274-568df4c09be7.png)


```
[jianh@7bede241abed trt]$ ls  ~/.cache/vscode-cpptools/
ls: cannot access /home/jianh/.cache/vscode-cpptools/: No such file or directory

[jianh@7bede241abed trt]$ ls  ~/.cache
JetBrains
```

**Comment by hijkzzz** [comment]
I solved this problem by setting the dir to ~/vscode-cpptools/.
It seems vscode can't process the case that ` ~/.cache/vscode-cpptools/` can't be write ?

**Comment by michelleangela** [comment]
@hijkzzz 

>And, the tools also generate a lot of bin files today.

It's normal for the extension to generate bin and ipch files when  `C_Cpp.intelliSenseCacheSize` is set to a value that is greater than 0. It will generate these cached files for each translation unit or source file that gets opened. If you do not want the extension to generate these cached files, set `C_Cpp.intelliSenseCacheSize` to `0`.

>It seems vscode can't process the case that ~/.cache/vscode-cpptools/ can't be write ?

If your machine's file system or some particular folder has read/write access restriction then that could explain why the extension cannot access or write to a folder.

You could try creating the folder `/home/jianh/.cache/vscode-cpptools/` and making sure there is no read or write restriction on it for VS Code and see if that works. Normally, if no path is set for `C_Cpp.intelliSenseCachePath`, then the extension should create the folder `~/.vscode-cpptools`.
