### ISSUE TITLE
Error reporting stopped randomly

### ISSUE THREAD

**Issue by infalmo** [microsoft/vscode-cpptools#8879]
Issue Type: <b>Bug</b>

Intellisense was working fine, till it all of a sudden decided to stop showing error squiggles on syntax errors. However, documentation on hover still works.

```
-------- Diagnostics - 2/18/2022, 3:40:33 AM
Version: 1.8.4
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc-10",
    "cStandard": "gnu17",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-arm64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/home/ubuntu/dev/et-engine/engine/include",
        "/home/ubuntu/dev/et-engine/engine/src/base",
        "/home/ubuntu/dev/et-engine/engine/src/core",
        "/home/ubuntu/dev/et-engine/engine/src"
    ],
    "standard": "gnu++20",
    "compilerPath": "/bin/g++-10",
    "compilerArgs": [
        "-g",
        "-Wall",
        "-Wextra",
        "-Wfloat-equal",
        "-Wno-psabi",
        "-ffast-math",
        "-fopenmp",
        "-std=gnu++2a"
    ]
}
Custom configurations:
[ /home/ubuntu/dev/et-engine/engine/src/base/constraint.cpp ]
{
    "defines": [
        "JSON_DIAGNOSTICS=0",
        "JSON_USE_IMPLICIT_CONVERSIONS=1",
        "SPDLOG_FMT_EXTERNAL",
        "base_EXPORTS"
    ],
    "standard": "gnu++20",
    "includePath": [
        "/home/ubuntu/dev/et-engine/engine/include"
    ],
    "compilerPath": "/bin/g++-10",
    "compilerArgs": [
        "-g",
        "-fPIC",
        "-Wall",
        "-Wextra",
        "-Wfloat-equal",
        "-Wno-psabi",
        "-ffast-math",
        "-std=gnu++2a"
    ]
}
Translation Unit Mappings:
[ /home/ubuntu/dev/et-engine/engine/src/base/constraint.cpp ]:
    /home/ubuntu/dev/et-engine/engine/src/base/constraint.cpp
Translation Unit Configurations:
[ /home/ubuntu/dev/et-engine/engine/src/base/constraint.cpp ]:
    Process ID: 219105
    Memory Usage: 368 MB
    Compiler Path: /bin/g++-10
    Includes:
        /home/ubuntu/dev/et-engine/engine/include
        /usr/include/c++/10
        /usr/include/aarch64-linux-gnu/c++/10
        /usr/include/c++/10/backward
        /usr/lib/gcc/aarch64-linux-gnu/10/include
        /usr/local/include
        /usr/include/aarch64-linux-gnu
        /usr/include
    Defines:
        JSON_DIAGNOSTICS=0
        JSON_USE_IMPLICIT_CONVERSIONS=1
        SPDLOG_FMT_EXTERNAL
        base_EXPORTS
    Standard Version: c++20
    IntelliSense Mode: linux-gcc-arm64
    Other Flags:
        --g++
        --gnu_version=100300
Total Memory Usage: 368 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2330
```

Extension version: 1.8.4
VS Code version: Code 1.64.2 (Universal) (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No
Remote OS version: Linux arm64 5.4.0-99-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id b8397ae3-af20-49b7-ba4f-2b69a7180586|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu|
|OS|Linux arm64 5.4.0-99-generic|
|CPUs|unknown (8 x 0)|
|Memory (System)|7.75GB (2.67GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrt:30437039
vsrem710:30416614
vscop841cf:30438916
dsvsc008:30440022
vsbas813:30436447
vscscmwlcmt:30438805
helix:30438806

```

</details>

**Comment by infinitepr0** [comment]
settings.json
```
{
    "C_Cpp.clang_format_style": "Google",
    "C_Cpp.workspaceParsingPriority": "low",
    "cmake.configureOnOpen": false,
    "C_Cpp.intelliSenseCacheSize": 0
}
```

**Comment by sean-mcmanus** [comment]
Documentation hover may be falling back to the non-IntelliSense-based results -- do you see (int)0 when hovering over a 0 literal?

Do you get no error squiggles with constraint.cpp?

Does doing a Reload Window fix it?

When you set C_Cpp.loggingLevel set to "Debug" do you see logging like:

Queueing IntelliSense update for files in translation unit of: ...constrain.cpp
cpptools/finishUpdateSquiggles
Error squiggle count: 1

**Comment by infinitepr0** [comment]
> Documentation hover may be falling back to the non-IntelliSense-based results -- do you see (int)0 when hovering over a 0 literal?
> 
> Do you get no error squiggles with constraint.cpp?
> 
> Does doing a Reload Window fix it?
> 
> When you set C_Cpp.loggingLevel set to "Debug" do you see logging like:
> 
> Queueing IntelliSense update for files in translation unit of: ...constraint.cpp cpptools/finishUpdateSquiggles Error squiggle count: 1

Adding the following lines
```
{
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
    "C_Cpp.default.cppStandard": "c++20",
}
```
to `settings.json` fixed the issue.

I'm unable to reproduce the error now (even on removing those lines).

**Comment by infinitepr0** [comment]
Okay, looks like I am wrong.
Intellisense has had no issues (regardless of not specifying the above settings). The `constraint.h` file has a forward declare, which caused it to give no errors.

**Comment by infinitepr0** [comment]
> I don't understand -- does that mean I can close this issue or do you believe there's still a bug?

There's no issue, thank you.
