### ISSUE TITLE
MinGW (TDM-GCC) IntelliSense problems

### ISSUE THREAD

**Issue by tehKaiN** [microsoft/vscode-cpptools#888]
Hi there,
I'm developing using VSCode 1.14.1, ms-vscode.cpptools 0.12.0

I've problem using TDM GCC 5.1 - everything works fine except Intellisense with Boost. After including boost to my project, it's `#include` squiggles with intrin.h not found error. So I've switched intellisense mode to clang-x64 and now squiggles changed to termios.h. My include & browse paths look like this:

```
"D:/prg/kompilatory/TDM-GCC/include",
"D:/prg/kompilatory/TDM-GCC/lib/gcc/mingw32/5.1.0/include",
"D:/prg/kompilatory/TDM-GCC/lib/gcc/mingw32/5.1.0/include/c++",
"D:/prg/kompilatory/TDM-GCC/lib/gcc/mingw32/5.1.0/include/c++/mingw32",
"D:/prg/kompilatory/TDM-GCC/lib/gcc/mingw32/5.1.0/include/c++/tr1",
"D:/prg/kompilatory/TDM-GCC/include",
"D:/prg/libs/wxWidgets-3.0.3/include",
"D:/prg/libs/wxWidgets-3.0.3/lib/gcc_lib/mswu",
"D:/prg/libs/boost_1_64_0"
```
Problems disappear if I don't use boost, but I guess that's not really a solution. ;)

**Comment by sean-mcmanus** [comment]
Can you locate the missing file and add the path to it? From what I read online, MinGW doesn't have termios.h. Maybe you can add a path to a dummy termios.h file as a workaround.

**Comment by bobbrow** [comment]
If the file doesn't exist, the issue is most likely due to a missing "define" sending IntelliSense down the wrong path during compilation.  I haven't had a chance to look into this issue yet, but will soon.

BTW, clang-x64 mode is what you want if you're using MinGW.

**Comment by bobbrow** [comment]
(Oh, and if you could provide a source code snippet that would be nice so I can see which Boost headers are giving you trouble)

**Comment by tehKaiN** [comment]
Ok, so it goes like this:
In my soruce code I have:

```
#include <wx/wx.h>
#include <boost/asio.hpp> // squiggles with netdb.h
```

In asio.hpp:

```
#include <boost/asio/basic_datagram_socket.hpp> // squiggles with netdb.h
#include <boost/asio/basic_deadline_timer.hpp>
#include <boost/asio/basic_io_object.hpp>
#include <boost/asio/basic_raw_socket.hpp>
#include <boost/asio/basic_seq_packet_socket.hpp>
#include <boost/asio/basic_serial_port.hpp> // squiggles with termios.h
```

netdb.h: basic_datagram_socket.hpp -> basic_socket.hpp -> basic_io_object.hpp -> io_service.hpp:
```
#if defined(BOOST_ASIO_HAS_IOCP)
# include <boost/asio/detail/win_iocp_io_service.hpp>
#else
# include <boost/asio/detail/task_io_service.hpp> // squiggles changed to task_io_service, I guess it should've gone IOCP way since it's win32.
#endif
```
And there in task_io_service.hpp squiggles are gone, wtf.

Let's go with termios:

basic_serial_port.hpp -> serial_port_base.hpp and there squiggles disappear.

**Comment by bobbrow** [comment]
Thanks for the additional information.  I can reproduce the missing squiggles when you open the header files.  There is something strange going on when you open certain of these boost headers which results in starving the processing of our input queue which basically disables our extension.  I'm investigating.

**Comment by bobbrow** [comment]
Adding `"_WIN32"` to the `"defines"` array in **c_cpp_properties.json** resolved the squiggles for me.  I haven't tested enough to see if that causes other issues with MinGW, but in the code files I tried it didn't introduce any new problems.  It looks like Boost might also want you to set `"__MINGW32__"` as well but it didn't make any difference in this particular case.

I have another fix for the input queue starving as well.
