### ISSUE TITLE
Extension produces error on comments!

### ISSUE THREAD

**Issue by justinefication** [microsoft/vscode-cpptools#8882]
Bug type: Language Service

C/C++ Extension produces an error saying `expected a ';' C/C++(65)` on a comment!

![report-bug](https://user-images.githubusercontent.com/40228037/154716320-e4d03ec4-c921-48aa-bc5f-3e2191fbc584.jpg)

```
-------- Diagnostics - 2/18/2022, 11:39:49 PM
Version: 1.8.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\msys64\\mingw64\\bin\\gcc.exe",
    "cStandard": "c99",
    "cppStandard": "c++20",
    "intelliSenseMode": "windows-gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Justine\CodeProjects\c-programming\01-intro-to-c\symbolic-constant.c ]:
    C:\Users\Justine\CodeProjects\c-programming\01-intro-to-c\symbolic-constant.c
Translation Unit Configurations:
[ C:\Users\Justine\CodeProjects\c-programming\01-intro-to-c\symbolic-constant.c ]:
    Process ID: 912
    Memory Usage: 15 MB
    Compiler Path: C:\msys64\mingw64\bin\gcc.exe
    Includes:
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE
        C:\MSYS64\MINGW64\INCLUDE
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE-FIXED
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c99
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=110200
Total Memory Usage: 15 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3314
```

OS and Version: Windows 10 21H2 (Build 19044.1526)
VS Code Version: 1.64.2 (user setup)
C/C++ Extension Version: 1.8.4

**Comment by aLexiusxx** [comment]
Hello @michelleangela 

Thanks for looking into this, The source code I used was from the book, The C Programming Language 2nd Edition by B. Kernighan and D. Ritchie.

Turns out the issue appears when the [Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) extension was installed alongside this extension which is part of the [C/C++ Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack)

When I first try to disable it (Better C++ Syntax) prior to reporting an issue, the problem persist even after restarting the IDE. Now that I completely remove it, the errors don't show up anymore.

**Comment by michelleangela** [comment]
@Colengms 
Are there any known issues with the usage of [Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) extension and the C++ extension together to cause incorrect positioning of error squiggles?

**Comment by michelleangela** [comment]
@aLexiusxx 
I installed the [C/C++ Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack) and I am still not able to get a repro. 

Could you try installing only the [Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) extension and not the extension pack to confirm that using Better C++ Syntax and the C++ extension is causing this problem?  If the issue doesn't occur, it could be something else that's causing the incorrect error location.

**Comment by aLexiusxx** [comment]
I wasn't using the whole extension pack but rather a subset of it since I
was still learning the language and doesn't need a complex build system
like Make yet. Specifically, I've installed the ff. from the pack:
1. C/C++
2. Better C++ Syntax
3. Doxygen Documentation Generator

**Comment by michelleangela** [comment]
@aLexiusxx 
It could be the browse database of parsed symbols got corrupted. Could you try resetting the browse database of the IntelliSense by running `C/C++: Reset IntelliSense Database` on the [VS Code command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)?
