### ISSUE TITLE
[cpp] Coloring options for code disabled via preprocessor directives [Preprocessor] [UI]

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-cpptools#889]
_From @rezorrand on June 9, 2017 7:4_

Currently code within preprocessor directives and code outside it has no difference in visual style. This can result in less readable code as it's hard to tell what is currently relevant. Intellisense doesn't work properly in disabled parts either, so having it shown with ordinary colors doesn't help.

While changing it all into one color (e.g. like green, comment-like, in MonoDevelop with Unity) is one option, maybe having a different background color is another possibility too.

_Copied from original issue: Microsoft/vscode#28305_

**Comment by aeschli** [comment]
I think this would have to be done by the language extension. Is your request for C++?

**Comment by aeschli** [comment]
_From @rezorrand on June 9, 2017 15:38_

Hi, thank you for consideration.

I was thinking C# in this case, but might apply to C++ too.

**Comment by sean-mcmanus** [comment]
@rezorrand We're tracking this with https://github.com/Microsoft/vscode-cpptools/issues/230 .

**Comment by sean-mcmanus** [comment]
@rezorrand Inactive code colorization was added in 0.15.0.
