### ISSUE TITLE
Display files differently in the explorer view if excluded using `C_Cpp.files.exclude`

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-cpptools#8895]
like eclipse does ,
https://dzone.com/articles/exclude-source-files-build
"Exclude Source Files from Build in Eclipse"
![image](https://user-images.githubusercontent.com/25566498/154834959-2341691c-7d51-4cca-9fe1-fdd39bac8a4c.png)

![image](https://user-images.githubusercontent.com/25566498/154834869-bc6d3089-b6aa-4789-9d93-2091055e5d76.png)
This way I can also edit the temporarily excluded code

**Comment by Colengms** [comment]
Hi @hongshui3000 .  Could you clarify what you would like to exclude files from?  The C/C++ extension does not directly provide build functionality (except for generating `tasks.json` for single source files).

Does the existing `C_Cpp.files.exclude` setting (which differs from the global `files.exclude` setting) already provide the functionality you are requesting?

**Comment by hongshui3000** [comment]
@Colengms Thanks for the reply, exactly what I wanted. One not so good point is that I can't directly distinguish from the workspace which files have been excluded using the "C_Cpp.files.exclude" configuration. Eclipse will display the file in gray and slashes, which is very intuitive.

**Comment by Colengms** [comment]
Hi @hongshui3000 .  We can use this issue to track your suggestion.  I'm not certain there is currently an API that would allow extensions to modify the appearance of files listed in the explorer view, so that may depend on VS Code providing that capability.
