### ISSUE TITLE
Navigate to Symbol, Go to Definition, Go to Declaration are gone

### ISSUE THREAD

**Issue by lamqhoang** [microsoft/vscode-cpptools#89]
Hi, 
This is the first time I'm working with Visual Studio Code. I installed the C/C++ extension  few days ago, it was working fine. Today those functions are gone. I tried to uninstall and reinstall the extension but it doesn't help.
What should I do?
Regards,
Hoang

**Comment by ghost** [comment]
Hi, 

Symbol/Definition navigation completely stops working when c_cpp_properties.json exists. If I delete only this file then navigation appears to work.

If c_cpp_properties.json exists then no browse.VC.db file is  generated.

C/C++ v 0.7.1, on Debian Sid (everything else seems fine - can do makefile builds fine, stop-mode debugging TypeScript).

Version 1.3.0-insider
Commit a1293f5056e79c3f0e2cd3e24909f41ff4eef472
Date 2016-07-05T13:18:41.201Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

**Comment by jgoshi** [comment]
Could you try this again with the latest release (VSCode 1.4, cpptools 0.8.1) and let us know if it still repros?

**Comment by sridmad** [comment]
Can you try with the latest version of the extension 0.9.0 and let us know if still see the issue.

**Comment by lamqhoang** [comment]
Hi, I have not seen the issue since the lastest update. 
Thanks
