### ISSUE TITLE
.editorconfig with root=true causes format-document to fail

### ISSUE THREAD

**Issue by barcharcraz** [microsoft/vscode-cpptools#8900]
I've got both a `.clang-format` and a `.editorconfig` file in one of my projects, and if `root = true` is set in the editorconfig file cpptools can't format any documents in my project. For "format document" it fails silently, for `Format document with" I get a popup with content:

`Command 'Format Document With...' resulted in an error (_a.toLowerCase is not a function)`

removing `root = true` from my .editorconfig or renaming the .editorconfig file resolves the issue.

This happens on linux (fedora 35) and windows 10, at least.

**Comment by Colengms** [comment]
Hi @barcharcraz .  When `C_Cpp.formatting` is set to `Default`, it will attempt to use a `.clang-format` file or `.editorconfig` file (if the `.editorconfig` file contains any `c_cpp` formatting properties) that is relative/nearest to the file being formatted.

I'm not able to easily reproduce this issue.  Could you provide a simple repro example in the form of a zip of the folder, or a github repo?

**Comment by barcharcraz** [comment]
[code_bug.zip](https://github.com/microsoft/vscode-cpptools/files/8128174/code_bug.zip)

Attached is a folder that demonstrates the issue. 

Open Folder
Open `main.c`
Ctrl-p->Format Document With...->C/C++
Error

**Comment by Colengms** [comment]
Hi @barcharcraz .  Thanks, that helps a lot.  With your repro, I was able to pinpoint the problem and fix it pretty quickly.  Until we can get a release out with the fix included, you should be able to work around the issue by specifying "TRUE" or "FALSE" (in upper case) for the `root` value in your `.editorConfig` file.  That should be compatible with other tools, as the specification [here](https://editorconfig.org/) mentions:

> Currently all properties and values are case-insensitive.

**Comment by Colengms** [comment]
I believe this should be fixed with 1.9.1, so closing this as fixed.  If you still repro an issue, let us know, and we can reopen the issue.
