### ISSUE TITLE
Intellisense reports an error when using ad-hoc constraints with abbreviated function templates

### ISSUE THREAD

**Issue by nickelpro** [microsoft/vscode-cpptools#8912]
Bug type: Language Service

**Describe the bug**
- OS and Version: Arch Linux
- VS Code Version: 1.64.2
- C/C++ Extension Version: 1.9.0 Pre-Release
- Other extensions you installed (and if the issue persists after disabling them): N/A
- If using SSH remote, specify OS of remote machine: No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Intellisense reports an error when using adhoc constraints with abbreviated template functions

**Steps to reproduce**
The following code:
```cpp
void f(const auto& v) requires requires {v.x();} {
    v.x();
}
```
Produces two errors:
>a requires-clause is not allowed here (not a templated function) C/C++(3249)

>expression preceding parentheses of apparent call must have (pointer-to-) function type C/C++(109)

Both from failing to realize an abbreviated function template is allowed to apply anonymous constraints to its parameters

**Expected behavior**

No error reported for this code

**Code sample and logs**
See above

**Screenshots**
N/A

**Additional context**
N/A

Performance analysis:
N/A

**Comment by Colengms** [comment]
Hi @nickelpro .  Thanks for reporting this.  I'm able to reproduce the issue in VS as well.  (We share the IntelliSense implementation with VS).  I've opened an internal issue against VS for this.

**Comment by nickelpro** [comment]
Not sure when it happened, but as of 1.13.5 this appears to be fixed.
