### ISSUE TITLE
cpptools used 99% CPU

### ISSUE THREAD

**Issue by shiyunfengCN** [microsoft/vscode-cpptools#8913]
Bug type: General

**Describe the bug**
- VS Code Version:
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18362
- C/C++ Extension Version:1.8.4
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
Just open my Andorid hal workspace though ssh-remote to my workshop service, I always use clang-formt or jump function which provided by cpptools, but the recent period I found my computer running very slow, I found cpptools alway use 99% cpu.

**Comment by Colengms** [comment]
Hi @alvin08s .  If your system has a single-core processor, it would be expected that any time a process is busy it would use ~100% of the CPU until no longer busy.  The Android codebase is very large, and it could take some time to completely parse those sources, particularly on a single-core system.  While that's occurring, you should also see a little database icon in the status bar:

![image](https://user-images.githubusercontent.com/49173979/155644411-b1ff5058-466c-4ded-bb38-9452d2cd6554.png)

You might try enabling the setting `"C_Cpp.loggingLevel": "Debug"` and monitoring the output to the C/C++ output channel.  It should provide some indicate of the work that it is occurring at any given time.  When you are seeing heavy CPU usage, do you see anything unusual in that log output?

**Comment by alvin08s** [comment]
CPU is i5-8500, this issue is almost 100% happened.
I have already delete this extension and installed clangd.Thanks.
