### ISSUE TITLE
command-line error: language modes specified are incompatibleC/C++(1027) View Problem Quick Fix... (Ctrl+.)

### ISSUE THREAD

**Issue by manuel5975p** [microsoft/vscode-cpptools#8915]
Bug type: Language Service

**Describe the bug**
- OS Linux 5.10.98-1-MANJARO
- VS Code Version: 1.64.2
- C/C++ Extension Version: 1.8.4
- Other extensions you installed (and if the issue persists after disabling them): None, but it doesn't matter. The issue is always there
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
For all the files files, c_cpp complains "command-line error: language modes specified are incompatibleC/C++(1027)". The language mode is set to C++, the file has a .cpp extension. The content of the files does not matter. 

**Steps to reproduce**
Create a .cpp file and open it in vscode.

**Code sample and logs**
c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c99",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-clang-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```
Anyways, I can also delete this config, or edit it arbitrarily, and the error persists. I can put anything into the files, and the error persist, I can have any extensions installed and uninstalled, and the error persists.

Here also the diagnostics log:

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 2/23/2022, 11:23:35 AM
Version: 1.8.4
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c99",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-clang-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true
}

Custom browse configuration: 
{
    "browsePath": [
        "/run/media/manuel/docpart/gitclones/raytest/include",
        "/run/media/manuel/docpart/gitclones/raytest/build/_deps/raylib-src/src",
        "/run/media/manuel/docpart/gitclones/raytest/build/_deps/raylib-src/src/external/glfw/include",
        "/run/media/manuel/docpart/gitclones/raytest/build/_deps/raylib_cpp-src/include",
        "/usr/include/eigen3",
        "/run/media/manuel/docpart/gitclones/raytest/src",
        "/run/media/manuel/docpart/gitclones/raytest/build/_deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir",
        "/run/media/manuel/docpart/gitclones/raytest/build/_deps/raylib-src/src/external/glfw/src",
        "/run/media/manuel/docpart/gitclones/raytest/build/_deps/raylib-build/raylib/external/glfw/src",
        "/run/media/manuel/docpart/gitclones/raytest/build/_deps/raylib-src/src/external/glfw/include/GLFW"
    ],
    "standard": "c99",
    "compilerPath": "/usr/bin/c++",
    "compilerArgs": [
        "-fno-strict-aliasing",
        "-Werror=implicit-function-declaration",
        "-Werror=pointer-arith",
        "-O3",
        "-DNDEBUG",
        "-fPIC",
        "-Wall",
        "-std=c99",
        "-Wdeclaration-after-statement",
        "-fno-strict-aliasing",
        "-Werror=implicit-function-declaration",
        "-Werror=pointer-arith",
        "-O3",
        "-DNDEBUG",
        "-fPIC",
        "-Wall",
        "-std=c99"
    ]
}
Translation Unit Mappings:
[ /run/media/manuel/docpart/gitclones/raytest/src/game_state.cpp ]:
    /run/media/manuel/docpart/gitclones/raytest/src/game_state.cpp
Translation Unit Configurations:
[ /run/media/manuel/docpart/gitclones/raytest/src/game_state.cpp ]:
    Process ID: 184644
    Memory Usage: 7 MB
    Compiler Path: /usr/bin/c++
    Includes:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include
        /usr/local/include
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include-fixed
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=110100
Total Memory Usage: 7 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 35928
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5041338/155300687-0c0eb279-2bc3-4e81-a34f-92826b973876.png)
![image](https://user-images.githubusercontent.com/5041338/155300730-b3171133-47d1-4c83-b7e7-24bad2c272d0.png)

**Comment by Colengms** [comment]
Hi @manuel5975p .  It looks like you are using the CMake Tools extension.  However, since there is no "Custom configurations" section in your Log Diagnostics output, it looks like your `CMakeLists.txt` may not contain an entry for that source file.  It's possible that adding this source file to your `CMakeLists.txt` may address the issue.

Otherwise, the issue appears to be CMake or CMake Tools related.  As part of the custom browse configuration (which is used to configure files not explicitly specified in a `CMakeLists.txt`) provided by CMake Tools, there appears to be an explicit C (not C++) standard version argument (actually, two of them):

```
"-std=c99"
```

It is possible there could be an issue with how you have the language associations configured in your `CMakeLists.txt` file, causing this language standard arg to arise where it shouldn't.
