### ISSUE TITLE
Trim out "__unnamed_*" from quick info tooltips

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#892]
From #454:

> "__unnamed_enum_04a4_31::" bit doesn't add any value so would be better omitted.

This would look better as "\<unnamed\>::" (Visual Studio-style) or simply omitted.

**Comment by Colengms** [comment]
This looks to have been addressed.  unnamed enums now display with ```<unnamed>::```.

![image](https://user-images.githubusercontent.com/49173979/66778189-df87ff80-ee7f-11e9-9a42-6047d58673f7.png)
