### ISSUE TITLE
Display the contents of std::valarray in the debugger

### ISSUE THREAD

**Issue by mqnc** [microsoft/vscode-cpptools#8925]
Type: Feature Request

Being able to inspect the content of std::vector and std::array in the debugger is really valuable and I miss that feature for std::valarray. There I can only see a memory address (and the first value when expanding it).

![image](https://user-images.githubusercontent.com/12005608/155477121-dd033098-9ae1-4aa6-b818-a205f35a743b.png)

I'd appreciate if this was added.
Thanks in advance!

**Comment by WardenGnaw** [comment]
To enable visualization of arrays, if you are using GCC/G++, you will need to have `-enable-pretty-printing` in your setup commands. Can you share your `launch.json`?

You will also need to make sure GDB is loading the pretty printers.
See https://github.com/microsoft/vscode-cpptools/issues/4568#issuecomment-675538975 for an example but you may need to modify it based on the OS image you are using.

**Comment by szchenshixi** [comment]
I ran into the same problem and I think it is related to the rarely-seen container `std::valarry`. It is not recognized as a container and thus not pretty-printed. My `launch.json` is basically the default.
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "C/C++ Runner: Debug Session",
      "type": "cppdbg",
      "request": "launch",
      "args": [],
      "stopAtEntry": false,
      "externalConsole": false,
      "cwd": "${workspaceFolder}",
      "program": "${cwd}/main",
      "MIMode": "gdb",
      "miDebuggerPath": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/29043711/235348883-eaea452c-eb40-4bb9-9f3f-cd3f72cec7fe.png)
As you can see the container has a size of two but only one of its value is printed.
