### ISSUE TITLE
Tiào zhuǎn dìngyì yǔ shēngmíng Bug 10 / 5,000 Translation results Jump definition and declaration bug 

### ISSUE THREAD

**Issue by ericellis7** [microsoft/vscode-cpptools#8926]
Bug type: General

**Describe the bug**
- OS and Version: ubuntu20.04
- ssh OS：ubuntu18.04
- VS Code Version:1.64.2
- C/C++ Extension Version:1.8.4
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

1. In a large-scale C++ mixed project, when clicking on a function body, it does not jump to the definition, but jumps all the way to the declaration.

**Comment by michelleangela** [comment]
@EricMzky 
Is there a sample repository or project that we can use to reproduce the issue? Also, it could be that the extension is still tag parsing a large project while the "Go to definition" operation is in progress.

Could you try enabling the Language Server logging? In the logging, look for the message "Done parsing remaining files.
Database safe to open" to wait for the extension to complete tag parsing before doing a "Go to definition" and see if the issue persists.

To enable on Language Server logging follow instructions at https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server.

**Comment by sean-mcmanus** [comment]
It's possible this could be the same as https://github.com/microsoft/vscode-cpptools/issues/8577
