### ISSUE TITLE
Read the content of existing launch.json

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cpptools#8930]
Currently, if the user changes the name of a debug configuration in launch.json, and plays the "Run and Debug" button, the config won't show in the list of available configs. (however, this renamed config will be shown in the list of available configs in "Run and Debug" panel)

**Comment by sean-mcmanus** [comment]
@elahehrashedi Is this for 1.9?

**Comment by elahehrashedi** [comment]
@sean-mcmanus yes
