### ISSUE TITLE
Add ; to break/continue keyword completion

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#8932]
As mentioned in https://github.com/microsoft/vscode-cpptools/issues/3087#issuecomment-1047379453 .

**Comment by sean-mcmanus** [comment]
@xgdgsc It's available in 1.9.2 (pre-release).

**Comment by xgdgsc** [comment]
Thanks!

**Comment by sean-mcmanus** [comment]
@xgdgsc Unfortunately, we're going to have to revert the change in our next release due to https://github.com/microsoft/vscode-cpptools/issues/9115 .
