### ISSUE TITLE
Electron takes 100% of cpu

### ISSUE THREAD

**Issue by christopherhesse** [microsoft/vscode-cpptools#8945]
Bug type: General

**Describe the bug**
- OS and Version: Mac OS X 12.1
- VS Code Version: 1.64.2
- C/C++ Extension Version: v1.8.4
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

An "Electron" process will periodically take 100% of my laptop CPU for an extended period of time.  The little fire icon at the bottom of the VSCode window is displayed while this is happening and indicates that clang-tidy is running.  It might be this is just how clang-tidy works (if it's even clang-tidy actually using the CPU, maybe it's just the CPP extension), but I can't figure out how to disable it.

I have not observed this issue when the CPP extension is disabled.  I have set the following settings in an attempt to make this not happen:

```
    "C_Cpp.default.compilerPath": "",
    "C_Cpp.codeAnalysis.runAutomatically": false,
    "C_Cpp.codeAnalysis.clangTidy.path": "/invalid/path",
```

Because I don't actually see clang-tidy in the process list, it seems plausible the extension is just running a tight loop that uses 100% cpu, but I don't know how to see what the extension is doing while the cpu is being used.

**Comment by michelleangela** [comment]
Setting "C_Cpp.codeAnalysis.clangTidy.enabled" to false should disable clang-tidy to run automatically. 

If "C_Cpp.codeAnalysis.clangTidy.path" is set to invalid, then one of two alternative paths will be used by the extension:
"If clang-tidy is available in the environment path, that is used. If not found in the environment path, the clang-tidy bundled with the extension will be used." Again though, if "C_Cpp.codeAnalysis.runAutomatically" is set to false, then no clang-tidy should be executed unless it is manually run. 

Side note: the process for the C/C++ extension's language server is `cpptools`. A `cpptools-srv` process is created for every translation unit (TU) of source files that are active.

Could you enable the C++ language server logging (see https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server) to verify that clang-tidy is running while the flame icon at bottom of VS Code appears? Look for logging "cpptools/runCodeAnalysis" and results of clang-tidy should be logged when the operation completes.

**Comment by christopherhesse** [comment]
`C_Cpp.codeAnalysis.clangTidy.enabled` is not set by me, but seems to say that it is set to false already:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/440336/156080109-6549c2d5-95f2-49d0-8cd4-59070711d211.png">

I have added it to the JSON just to be certain, and removed the invalid path.

It looks like I already have debug logging enabled, but this is all I see in the output:

<img width="2079" alt="image" src="https://user-images.githubusercontent.com/440336/156079968-795a3a58-47cc-41bb-bfcf-fc86feefc622.png">

It's hard to take a picture of the flame icon, but it says "Updating IntelliSense | Running clang-tidy: 0 / 1 (0%)" and Electron is using 100% CPU:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/440336/156080083-5f64c9fc-a9a5-47d0-aba9-507fb3aeac51.png">

I don't see "runCodeAnalysis" in the logs, I will try reloading the VSCode window with the explicit false setting for `clangTidy.enabled`.

**Comment by christopherhesse** [comment]
When electron is using 100% CPU is there a way to get a stack trace for the process?

**Comment by sean-mcmanus** [comment]
I'm not sure how to get a stack trace for Electron, maybe something under Help->Toggle Developer Tools -- it's part of VS Code itself and we don't normally encounter issue with Electron using abnormal CPU.

If your C_Cpp.loggingLevel is "Debug" and you don't see "runCodeAnalysis" in the C/C++ logging but you see "Running clang-tidy: 0 / 1 (0%)" that would seem to be impossible according to our understanding.

**Comment by michelleangela** [comment]
Do you have other extensions installed? If so, could you try disabling them too?

Does this reproduce with any project?

What happens if you try to "Cancel clang-tidy" by clicking on the flame icon?

**Comment by christopherhesse** [comment]
I only use one project, and the following 4 extensions:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/440336/156088782-1acc9d07-ac8f-48c9-842e-334f98e6eea6.png">

Since adjusting the settings according to @michelleangela's description and restarting VSCode, I still see the flame icon but I also still do not see `runCodeAnalysis` in the logs.

However, I have not caught Electron using 100% of my CPU either, so perhaps the issue is worked around.  If I don't see anything tomorrow I will close the issue.  Thanks for the help!

**Comment by christopherhesse** [comment]
With @michelleangela's changes to the settings I have not seen the 100% CPU issue today.  I will close this issue for now since it could be some weird edge case that nobody else is encountering and this workaround seems sufficient.  Thanks for the quick help!

**Comment by sean-mcmanus** [comment]
FYI, I've reproed the flame icon with "Running clang-tidy" even though code analysis was never run. I've filed bug https://github.com/microsoft/vscode-cpptools/issues/8964 to track that, but I don't understand yet how to repro it or what could be causing it.
