### ISSUE TITLE
Codeanalysis with clang-tidy fails when run from VSCode but not from commandline

### ISSUE THREAD

**Issue by hriekehof** [microsoft/vscode-cpptools#8952]
Bug type: Language Service

**Describe the bug**
- OS and Version: macOS Monterery 12.2.1 (ARM) 
- VS Code Version: 1.64.2
- C/C++ Extension Version: 1.9.1 pre-release

I want to run code analysis with `clang-tidy` on my codebase for which i have a large `compile_commands.json`. Around 100MB with 12000 entries. Also the compile command itself is quite long. Many defined symbols mostly. If count the lines in the C++ Extension output with loglevel="Information" there are 547 lines.

For all files i have tested i get a `clang-diagnostic-error` when i run the `Run Code Analysis on Active File` command. The errors are not shown on the extension output so i ran the same command in the terminal which shows alot of errors.
```bash
/Users/hriekehof/.vscode/extensions/ms-vscode.cpptools-1.9.1/bin/../LLVM/bin/clang-tidy \
--checks="clang-analyzer-*" \
--header-filter=".*" \
--extra-arg=-ferror-limit=0 \
--quiet \
/Users/hriekehof/src/repo/shared/someFile.cpp \
-- \
-std=c++14 \
-xobjective-c++ \
-Wno-pragma-pack \
...
```
 Unfortunately i cannot share the full output since the project is closed source, but i can share the first error printed:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__hash_table:123:76: error: call to '__libcpp_clz' is ambiguous [clang-diagnostic-error]
    return __n < 2 ? __n : (size_t(1) << (numeric_limits<size_t>::digits - __libcpp_clz(__n-1))); 
```
The list of errors in the system headers goes on a while. To try around a little i installed a separate clang toolchain via `brew install llvm` and tried this version of `clang-tidy` instead of the one which comes with VSCode. 
```bash
/opt/homebrew/opt/llvm/bin/clang-tidy \
--checks="clang-analyzer-*" \
--header-filter=".*" \
--extra-arg=-ferror-limit=0 \
--quiet \
/Users/hriekehof/src/repo/shared/someFile.cpp \
-- \
-std=c++14 \
-xobjective-c++ \
-Wno-pragma-pack \
...
```
I get the same errors in this case. Then i put my `compile_commands.json` at the top of my repo folder at `/Users/hriekehof/src/repo/compile_commands.json` so that `clang-tidy` could extract the information for the compilation by itself. If i use the included clang-tidy the error output changes to this.
```bash
~ via 🅒 base
➜ /Users/hriekehof/.vscode/extensions/ms-vscode.cpptools-1.9.1/bin/../LLVM/bin/clang-tidy --checks="clang-analyzer-*" --header-filter="/Users/hriekehof/src/repo" --quiet --extra-arg=-ferror-limit=0 /Users/hriekehof/src/repo/shared/someFile.cpp
1 error generated.
Error while processing /Users/hriekehof/src/repo/shared/someFile.cpp.
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/wchar.h:89:10: error: 'stdarg.h' file not found [clang-diagnostic-error]
#include <stdarg.h>
         ^~~~~~~~~~
```
If i then use the clang-tidy version from brew it seems to work fine. I get the same diagnostic result for `someFile.cpp` like in XCode. 
```bash
~ via 🅒 base
➜ /opt/homebrew/opt/llvm/bin/clang-tidy --checks="clang-analyzer-*" --header-filter="/Users/hriekehof/src/resp" --quiet --extra-arg=-ferror-limit=0 /Users/hriekehof/src/repo/shared/someFile.cpp
../../../../../../artifacts/boost_source_libraries/1.74.0/boost_libraries/boost/rational.hpp:999:43: warning: Division by zero [clang-analyzer-core.DivideZero]
    return static_cast<T>(src.numerator())/static_cast<T>(src.denominator());
```
I'm only guessing, but for me it seems that the cpp extension does not pass the correct command line arguments from the `compile_commands.json` to clang-tidy after the `--`. Since the brew version of clang-tidy seems to work.
I would love to share all logs etc. but unfortunately i can't 😄 

Thanks for any help and tipps in advance.

**Steps to reproduce**
Sadly i cannot provide a clear list of steps since it would need my project which i cannot share since its closed source.

**Expected behavior**
Code Analysis works out of the box when i compilation database is present. 

**Code sample and logs**

Configuration in `c_cpp_properties.json`
```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "intelliSenseMode": "macos-clang-arm64",
            "compileCommands": "${workspaceFolder}/make/macArm/compile_commands.json"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
This seems like the same issue as https://github.com/microsoft/vscode-cpptools/issues/8740 , i.e. switching to using -p could fix it.

**Comment by sean-mcmanus** [comment]
With 1.10.2 (pre-release), setting `C_Cpp.codeAnalysis.clangTidy.useBuildPath: true` is expected to fix this, but you may also need to set C_Cpp.codeAnalysis.clangTidy.path if there is a problem locating the system includes from the environment using the bundled clang-tidy binary.
