### ISSUE TITLE
ban popping up window "Would you like to use a compile_commands.json file to auto-configure IntelliSense for this folder"

### ISSUE THREAD

**Issue by congmingyige** [microsoft/vscode-cpptools#8958]
Type: Feature Request

The window opens all the time when opening a folder(project) troubles me. Is that a way to ban the window in the setting?

Previous discussion: [link](https://github.com/microsoft/vscode-cpptools/discussions/8942).

**Comment by sean-mcmanus** [comment]
We could potentially just add a "Don't show again" option in the dialog box (or a setting).
