### ISSUE TITLE
Code format can break the code when comment in lambda

### ISSUE THREAD

**Issue by karuboniru** [microsoft/vscode-cpptools#8972]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 11 22557.1
- VS Code Version: 1.65.0
- C/C++ Extension Version: v1.8.4
- Other extensions you installed (and if the issue persists after disabling them): whole C/C++ Extension Pack
- If using SSH remote, specify OS of remote machine: also persists when ssh to Fedora 35 Server 
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
1. Create any `.cpp` file with content (won't build, just for testing formatting)
```
int main()
{
    std::for_each(x.begin(), x.end(), [](auto *h)
        {
            some_code(h);
            // some comments
        });
    return 0;
}
```
2. Press `Ctrl+Shift+F` (format code), or use it in menu
3. Checked the formatted code, getting 
```
int main()
{
    std::for_each(x.begin(), x.end(), [](auto *h)
                  {
            some_code(h);
            // some comments });
    return 0;
}
```
notice `});` being placed to comments

**Expected behavior**
Code format should not change the meaning of the code

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by karuboniru** [comment]
Seems to be an `clang-format` issue with specific style
tested a style like `--style="{BasedOnStyle: LLVM, BreakBeforeBraces: Allman, ColumnLimit: 0}"` can trigger the exact problem

**Comment by karuboniru** [comment]
https://github.com/llvm/llvm-project/issues/51234
seems to be an upstream reported problem, I will left the issue here on you Microsoft people whether to close the issue or not.

**Comment by sean-mcmanus** [comment]
@bobbrow Close as external or keep it open for tracking?

**Comment by bobbrow** [comment]
We can close it.  Thanks for asking.
