### ISSUE TITLE
Language Detection error

### ISSUE THREAD

**Issue by IC-killer** [microsoft/vscode-cpptools#8982]
Bug type: Language Detection abnormal

**Describe the bug**
- OS and Version: win10
- VS Code Version: 1.65.0
- C/C++ Extension Version: 1.8.4

**Steps to reproduce**

1. right click to open the project folder
2. open the header files
3. this happened, between c and c++ blink

- Configurations in `c_cpp_properties.json`
{
    "configurations": [
        {
            "name": "stc51",
            "includePath": [
                "${workspaceFolder}/STCLIB",
                "${workspaceFolder}/src",
                "C:/Keil_v5/C51/INC",
                "C:/Keil_v5/C51/INC/STC",
                "${workspaceFolder}/inc",
                "${workspaceFolder}/MYLIB"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "bit=char",
                "sbit=char",
                "sfr=char",
                "code=const",
                "xdata=_Alignas"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30037\\bin\\Hostx64\\x64\\cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64"
        }
    ],
    "version": 4
}
```
<img src="https://www.z4a.net/images/2022/03/07/bug.gif" alt="show" />

**Comment by michelleangela** [comment]
@IC-killer
Could you share the sample of the header file that reproduces this behavior?

While the header file is open, could you also run the `C/C++: Log Diagnostics` from the [VS Code command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and copy the logs to this issue?
