### ISSUE TITLE
Function Prototype not updated in outline

### ISSUE THREAD

**Issue by eunwoo** [microsoft/vscode-cpptools#8986]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 (Windows_NT x64 10.0.19041)
- VS Code Version: 1.65
- C/C++ Extension Version: 1.8.4
- Other extensions you installed (and if the issue persists after disabling them): 
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Open cpp file.
2. Click on Outline view
3. See error.
There are two different functions, one is member function and the other is global function.
void	PMSensorless::InitBeforeRun() {}
void	PMSL_InitBeforeRun() {}
The global function is not shown in the Outline view.
![image](https://user-images.githubusercontent.com/8966503/157190666-cefb4fe0-15d7-4cad-9c27-ec178bdc27d9.png)

**Expected behavior**

The global function should be shown in Outline view.

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I'm not reproing the issue. Can you provide more repro info?

![image](https://user-images.githubusercontent.com/19859882/157321270-d251bcb2-a183-488e-a3b3-8e669b150bc9.png)
