### ISSUE TITLE
1.9.2 Pre Release: Problem matcher does not correctly interpret file path. 

### ISSUE THREAD

**Issue by endsofinvention** [microsoft/vscode-cpptools#8988]
Bug type: General

**Describe the bug**
Problem matcher interprets the file path of a problem file as
/../my_directory/myfile.c 
Prior to the latest update it would be something like:
~/my_directory/myfile.c

This results in the Problem matcher not being able to open a file from the PROBLEMS tab. 
- OS and Version:
- Linux Mint 20 
- VS Code Version:
Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:36.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-100-generic

- C/C++ Extension Version:
1.9.2

- A clear and concise description of what the bug is.
Clicking on the compile error results in the file not being found and vscode prompting to 'create' the file. Which of course it cannot do as the directory that is pointed to is not a valid path. There is no valid path below '/ ' so '/../ ' cannot possibly exist

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. We have a fix pending at https://github.com/microsoft/vscode-cpptools/pull/8993 .

**Comment by sean-mcmanus** [comment]
We believe the issue is fixed with 1.9.3 -- let us know if it's still not working.

**Comment by endsofinvention** [comment]
Thanks Sean. I will check and revert if anything is amiss. Your work is most appreciated.
