### ISSUE TITLE
new intellisense engine doesn't understand conditionals

### ISSUE THREAD

**Issue by gdamore** [microsoft/vscode-cpptools#899]
I have a project that has different symbols compiled differently on different platforms.  This is a C project.  (github.com/nanomsg/nng)

It would appear that the engine is confused by conditional compilation, and I see no documented way to inform it of which paths to check for.  (And frankly, its unclear how to resolve competing definitions -- perhaps that would be part of the "Configuration" thing which I'm still trying to wrap my mind around.)

Its distinctly possible that I'm misunderstanding the real root issue here, and that this is simply another instance of #897  since there are multiple recursive includes involved.  I certainly think that I've seen #897 in this build too.

For now I've gone back to the Tag Parser.

**Comment by sean-mcmanus** [comment]
You can add conditional compilation definitions to the "defines" section of c_cpp_properties.json. I tried out the C project and I get IntelliSense working when I open the src folder (opening the parent folder would require adding the ${workspaceRoot}/src to the includePath). What error specifically do you see?

**Comment by sean-mcmanus** [comment]
Actually, on Linux I'm getting an endless "Loading..." message. We'll investigate.

**Comment by gdamore** [comment]
what i saw was that some symbols were not understood.  for example in src/core/endpt.h it had trouble with a few things like nni_mtx.

**Comment by sean-mcmanus** [comment]
Hmm...the "Loading..." message went away after I opened another folder, so that looks like some other intermittent issue.

**Comment by sean-mcmanus** [comment]
Okay, I see what you're seeing too. "incomplete type is not allowed". We'll investigate. Adding a define for "NNG_PRIVATE" fixed one of those issues, but not the nni_mtx case.

**Comment by sean-mcmanus** [comment]
I found a fix. Add `            "defines": [
                "NNG_PRIVATE",
                "PLATFORM_POSIX_THREAD"
            ],`
to your config (or maybe PLATFORM_POSIX instead). That should fix it. We plan to eventually support compile_commands.json, which should automatically use the defines from the CMakeLists.txt.

**Comment by bobbrow** [comment]
I also cloned it and it appears that you need to add either `PLATFORM_POSIX` or `PLATFORM_WINDOWS` to the `"defines"` array in your c_cpp_properties.json file.  After that, I didn't see any major problems with IntelliSense.

**Comment by gdamore** [comment]
Cool, the defines thing was what I needed.  Thanks.
