### ISSUE TITLE
Add option for setting location of Intellisense cache

### ISSUE THREAD

**Issue by HenryAWE** [microsoft/vscode-cpptools#8990]
Type: Feature Request
C/C++ Extension currently only provides option for limiting the cache size used by Intellisense, but it still stores them in the default `AppData\Local\Microsoft\vscode-cpptools`, which can cost precious space of the `C:` drive.
I think an option for setting the cache location to other place with more storage space would be better.

**Comment by michelleangela** [comment]
There is the setting [C_Cpp.intelliSenseCachePath](https://code.visualstudio.com/docs/cpp/faq-cpp#_ccppintellisensecachepath-string) to customize the default location of IntelliSense cache. Does changing this setting work? If not, then there is a bug with the extension not applying the setting changes.

**Comment by HenryAWE** [comment]
It works fine.
