### ISSUE TITLE
Language service does not work in Windows 7/8/8.1 without VS2015 installed

### ISSUE THREAD

**Issue by sridmad** [microsoft/vscode-cpptools#9]
Multiple comments on various forums

**Comment by abc100m** [comment]
To someone who can't running this extension on windows 7:

.vscode\extensions\ms-vscode.cpptools-0.5.0\bin\Microsoft.VSCode.CPP.Extension.exe
this file can not  running if you don't install VS2015 Redistributable Package.

on my laptop cpptools extersion works after installed "Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.23026"

**Comment by sridmad** [comment]
Fixed. Next update to the extension will have the fix.
