### ISSUE TITLE
Syntax highlighting not consistent

### ISSUE THREAD

**Issue by Flyboy1010** [microsoft/vscode-cpptools#9011]
Issue Type: <b>Bug</b>

asterisk from pointers and ampersand from references are highlighted in function declarations and function definitions, now ok, but in the constructors they are only highlighted in the declaration but not in the definition aswell, also when creating a pointer or reference in the code the asterisk or ampersand is not highlighted, and some lack of consistency when highlighting the operator delete sometimes blue, sometimes pink.

Some Pictures:

 <b>Function declaration -> OK</b>
![image](https://user-images.githubusercontent.com/59151174/157782407-bbae1bfe-1fea-4008-aa34-a85f5a11e0ca.png)
 <b>Function definition -> OK</b>
![image](https://user-images.githubusercontent.com/59151174/157782478-ebd4cf3e-6c8d-4821-81ba-4bba958093fe.png)
 <b>Contructor declaration(in .h file) -> OK</b>
![image](https://user-images.githubusercontent.com/59151174/157782532-ed36820a-4a94-4e28-bc74-04569430cb48.png)
 <b>Contructor definition(in .cpp file) -> WRONG(& not highlighted)</b>
![image](https://user-images.githubusercontent.com/59151174/157782604-aca79aa7-4377-49c7-9519-ea9acdc0d6b2.png)
 <b>Delete operator -> COLORED BLUE</b>
![image](https://user-images.githubusercontent.com/59151174/157782740-2bd52976-caf9-428e-89cf-311983c13ec9.png)
 <b>Delete operator -> COLORED PINK</b>
![image](https://user-images.githubusercontent.com/59151174/157782771-f233a1b9-59b8-4f10-87bb-0c81264e8bfb.png)
 <b>Pointer or reference creation and usage -> WRONG(* or & not highlighted)</b>
![image](https://user-images.githubusercontent.com/59151174/157782884-3fa68fcc-342a-4e1c-8cf8-44970b4ff250.png)

Extension version: 1.8.4
VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:09:03.269Z)
OS version: Linux x64 5.16.13-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 2824)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.75GB (0.50GB free)|
|Process Argv|. --crash-reporter-id 9c4a48ce-336c-4955-99f8-a636a74851d1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc008:30440022
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvidc:30447482
pynewfile477:30450038

```

</details>

**Comment by sean-mcmanus** [comment]
Our C/C++ extension doesn't provide the highlighting for the * and & cases. It's from VS Code itself, which gets its behavior from https://github.com/jeff-hykin/better-cpp-syntax/issues (i.e. you should file an issue there, although I'm guessing an issue may already exist).
