### ISSUE TITLE
Formatter c

### ISSUE THREAD

**Issue by Hassan77155** [microsoft/vscode-cpptools#9015]
Issue Type: <b>Bug</b>

I have C/C++ installed and I used to use its C formatter, But now it is not working.

Extension version: 1.8.4
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

**Comment by sean-mcmanus** [comment]
Can you give more info? What formatter settings are you using? When you set C_Cpp.loggingLevel to "Debug" what formatter logging messages are shown in the C/C++ pane (there might be errors reported there).

**Comment by michelleangela** [comment]
@Hassan77155 
Could you provide logs from the language server while trying to reproduce the issue. See https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server for log instructions.

Are there any c_cpp.* settings customized for formatting?

**Comment by Hassan77155** [comment]
> Can you give more info? What formatter settings are you using? When you set C_Cpp.loggingLevel to "Debug" what formatter logging messages are shown in the C/C++ pane (there might be errors reported there).

Sorry for replying late, How can I give more info?

**Comment by sean-mcmanus** [comment]
@Hassan77155 Did you see Michelle's previous comment?

**Comment by Hassan77155** [comment]
> @Hassan77155 Did you see Michelle's previous comment?

I solved the issue by uninstalling the c/c++ extension completely and reseting  all my settings.
Thank you,

**Comment by Hassan77155** [comment]
> @Hassan77155 Could you provide logs from the language server while trying to reproduce the issue. See https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server for log instructions.
> 
> Are there any c_cpp.* settings customized for formatting?

yeah, I removed them all and  installed the extension again and it fixed my issue.

Thank you,
