### ISSUE TITLE
Global variable access in debugger

### ISSUE THREAD

**Issue by pjyoung63** [microsoft/vscode-cpptools#9019]
Type: Feature Request

It is not possible to change the value of a global variable when debugging C++ with GBD since globals are only visible when added to the watch window which does not allow editing of a variables value.
Either globals need to be made available by a selection process in Variables window, or the watch window needs to enable editing of values.

**Comment by WardenGnaw** [comment]
As this is marked as a feature request, it will need to be implemented.

In the meantime, you should be able to assign to it if it is a child item in the `Watch Window` e.g.
```
int c = 5;
```

In the watch window, use `&c` and expand it, right click on the child item and you should see a `Set Value`.

The other option is to set it via GDB commands using the `Debug Console`.

**Comment by Trass3r** [comment]
> Either globals need to be made available by a selection process in Variables window, or the watch window needs to enable editing of values.

Yeah I remember seeing local/static/... sections in the variables view with other debug adapters like https://github.com/vadimcn/vscode-lldb#screenshots.

**Comment by sean-mcmanus** [comment]
This seems to have gotten fix a while ago.

**Comment by reporter123** [comment]
Where is this fix? Still not present in the current release of this extension. Although the workaround is.

**Comment by starball5** [comment]
should this still be tagged "release-pending"? It seems to be released.

**Comment by sean-mcmanus** [comment]
@starball5 The fix was released in 1.10.5 (in 2022). The label has been updated to "fixed" with the description "Check the Milestone for the release in which the fix is or will be available.".
