### ISSUE TITLE
Intellsense crashes on compilation

### ISSUE THREAD

**Issue by Samega7Cattac** [microsoft/vscode-cpptools#9022]
Bug type: Language Service

**Describe the bug**
- OS and Version: Linux x64 5.16.13-arch1-1
- VS Code Version: 1.65.2
- C/C++ Extension Version: 1.8.4
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Extension Pack
- If using SSH remote, specify OS of remote machine: N/A
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Open a big C++ project
2. Click on build (status bar)
3. Puff Intellsense crashes

**Expected behavior**

To not crash

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**
Because of issue #9007 I notice my intellsense crashed frequently, this time it crashed every time I tried to compile
I tried to attach gdb on it but it just exists when crashes, no call stack, nothing.
Still don't know if it's related to that issue

**Comment by sean-mcmanus** [comment]
Are you attaching to the cpptools-srv process? That is the IntelliSense process. Is that the one that is crashing?

**Comment by Samega7Cattac** [comment]
@sean-mcmanus yes I attached to cpptools-srv and it crashed on compile, I will try again today

**Comment by sean-mcmanus** [comment]
How do you know IntelliSense is crashing? Does it say in the logging?

What exactly is the "build" option in the status bar? From CMake Tools?

**Comment by Samega7Cattac** [comment]
> What exactly is the "build" option in the status bar? From CMake Tools?
Yes
> How do you know IntelliSense is crashing? Does it say in the logging?
2 days ago it was crashing (showing on the Output tab), now it just exits debugging like nothing happened (I will keep testing)

**Comment by Samega7Cattac** [comment]
Forgot to mention I'm on a VM

**Comment by sean-mcmanus** [comment]
Do you remember if the crash message was in a "cpptools" pane or "C/C++" pane? The "cpptools" pane would be from a cpptools crash and the "C/C++" outputs a message about IntelliSense process crashes (cpptools-srv).

Does the C/C++ logging indicate the IntelliSense process is shutting down when it shouldn't? We have one known repro of that in a Linux container in which we're currently investigating.

**Comment by Samega7Cattac** [comment]
C/C++, it clearly said it was Intellsense

**Comment by sean-mcmanus** [comment]
Yeah, in that case, we'd want a crash call stack for cpptools-srv.
