### ISSUE TITLE
Format Document using user specified clang-format not working anymore

### ISSUE THREAD

**Issue by christophe-calmejane** [microsoft/vscode-cpptools#9028]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.65.2
- C/C++ Extension Version: 1.9.3
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc): c++ file code formatting using clang-format is not working, an error is printed in C/C++ output window saying the file cannot be found.
- Pretty sure it used to work a few weeks ago, but not 100% sure if I was testing on windows or macOS

**Steps to reproduce**
- Create a simple .cpp file with just one line
- Add a .clang-format file in the same folder
- Try to format the file (saving it, using `Format Document` shortcut, ...)

**Expected behavior**
- Document formatted using clang-format file

**Code sample and logs**
test.cpp file:
```c++
/* Test file to exhibit clang-format formatting bug */
```

- c_cpp and format properties in  `settings.json`
```
"C_Cpp.clang_format_path": "d:\\dev\\clang-format.exe",
"C_Cpp.formatting": "clangFormat",
"editor.formatOnType": true,
"[cpp]": {
  "editor.defaultFormatter": "ms-vscode.cpptools"
},
"editor.formatOnSave": true,
"editor.formatOnPaste": true
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 15/03/2022, 14:17:30
Version: 1.9.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.20348.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\dev\test.cpp ]:
    D:\dev\test.cpp
Translation Unit Configurations:
[ D:\dev\test.cpp ]:
    Process ID: 31732
    Memory Usage: 14 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PROFESSIONAL\VC\TOOLS\MSVC\14.29.30133\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PROFESSIONAL\VC\TOOLS\MSVC\14.29.30133\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.20348.0\CPPWINRT
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 14 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 4932
```

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
```
Formatting input:
/* Test file to exhibit clang-format formatting bug */

Formatting document: file:///D%3A/dev/test.cpp
Formatting Engine: clangFormat
Failed to spawn process. Error: 2 (Le fichier sp�cifi� est introuvable.)
```

Manually calling  (from a terminal shell) `clang-format -i -style=file d:\\dev\\test.cpp` works as expected

**Comment by sean-mcmanus** [comment]
It works with 1.8.4?

**Comment by sean-mcmanus** [comment]
It sounds like there's some issue finding `d:\\dev\\clang-format.exe`.

**Comment by christophe-calmejane** [comment]
Hi,

my bad, it looks like the drive is now case sensitive and the exact file name is not the same as the value of C_Cpp.clang_format_path.
I noticed it when testing without the value specified in settings, and putting it back by copying the file name ;)

Just so I know for next time, how can I easily test with 1.8.4 (or any other version)?
Sorry again, thanks for your time!

**Comment by sean-mcmanus** [comment]
You can easily switch versions from the VS Code extensions pane via Install Another Version (or potentially switching from a Release to Pre-Release version):
![image](https://user-images.githubusercontent.com/19859882/158650595-49a1c1ab-b78f-4680-ac48-2c5a3815aa0c.png)
