### ISSUE TITLE
IntelliSense stops working after a period of time on Linux

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#9035]
@sean-mcmanus Here are the details: https://github.com/microsoft/vscode/issues/145150

I was told to file the issue here, but was looking through existing issues first.

A source code reproducer will be difficult for two reasons:
1. The problem is intermittent. It seems kind of random how long you have to wait until it happens and then when it fixes itself is also kind of random.
2. The source code is proprietary, so I cannot provide it. However, the compiler is LLVM-based, I may try to reproduce with the _open source_ LLVM compiler.

_Originally posted by @naromero77intel in https://github.com/microsoft/vscode-cpptools/issues/8610#issuecomment-1069380000_

**Comment by naromero77intel** [comment]
> @naromero77intel We need more details about the symptoms in order to determine what is actually going on -- it's unclear if the problem is with IntelliSense, our main process, or the database, etc.. When you repro the issue again, can you set the C_Cpp.loggingLevel to "Debug" to see what is being logged when you hover or type and/or attach a debugger to the cpptools or cpptools-srv processes (https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv) and break to get a call stack and/or check what CPU and memory usage is occurring with the cpptools/cpptools-srv processes via "top" or something else.
> 
> We're not familiar with any issue like this (and the issue you originally reported this on is different).
> 
> You may also want to try 1.9.3 (or our pending 1.9.4) which has several bug fixes.

Got it. Thanks for the helpful information.

It don't see 1.9.3 available here:
https://github.com/microsoft/vscode-cpptools/releases

It jumps from 1.8.4 to 1.9.4-prerelease1

**Comment by sean-mcmanus** [comment]
It's available via the VS Code Extensions view after using Switch to Pre-Release Version:

![image](https://user-images.githubusercontent.com/19859882/158666883-98e5a53a-a3f3-4b19-b16f-c2ecc1df40c1.png)

We don't normally publish pre-releases on GitHub (1.9.4-prerelease1 was a special case for Windows x64 only -- that version is very similar to the 1.9.4 we're about to release in an hour or so).

**Comment by naromero77intel** [comment]
@sean-mcmanus  Thanks for help and for being so responsive. Looking forward to see if 1.9.x solves my issues.

**Comment by sean-mcmanus** [comment]
We just published 1.9.4 (pre-release) -- it's expected to be the same as 1.9.5 (non-pre-release) which we plan to release on Monday.

**Comment by naromero77intel** [comment]
@sean-mcmanus I would like to re-open this issue as it is continuing to happen with greater frequency lately. (perhaps because I am working working on a different section of the compiler and opening different files from last time).

Here is the output of top. Again, I am using the Windows client but SSH into a Linux box.
```
 top -p `pgrep -d "," cpp`
```

I attach a snapshot of the output. I am on a powerful workstation with 384GB of memory. If I am reading this correctly, there are multiple `cpptools-server` and one of them is using 11+ GB of virtual memory?
 
![VisualStudioCodeTop](https://user-images.githubusercontent.com/88206970/175207055-c8a2c0ca-4cae-47a4-afb8-cd486a6c0609.png)

Here is the call stack for cpptools:
![VisualStudioCPPTOOLS](https://user-images.githubusercontent.com/88206970/175209660-5e04fd03-c421-4d91-8101-6777d7480cfc.PNG)

Here is the call stack for cpptools-srv (the one that is using over 11GB of memory). I also opening the three other cpptools-srv and they all looked the same.
![VisualStudioCPPTOOLS-SRV-HIGHMEMORY](https://user-images.githubusercontent.com/88206970/175209773-03dfcc93-ca46-480c-a3d6-490fb72c63f7.PNG)

Let me know if there is any other information I can gather. Again, this is Intel Fortran compiler which is an LLVM-based compiler.

**Comment by naromero77intel** [comment]
@sean-mcmanus Also, please let me know if I should open another issue... but it would be easier to just re-open this one.

**Comment by naromero77intel** [comment]
I can confirm that the problem is much more reproducible now.  I can do `Peak` definition exactly once and then it gets hosed. The output of top looks similar to what I had before -- except there is only one `cpptools-srv` process.

**Comment by naromero77intel** [comment]
OK, I just tried `Tag Parser`. It worked exactly once and then it didn't work again.

Now I don't even see `cpptools-srv` process at all.

**Comment by Colengms** [comment]
> I am not sure if this is relevant, but I will mention that the filesystem on this workstation is NFS mounted.

Hi @naromero77intel .  Can you attempt to repro when opening the project from a local file system?  We have in the past seen issues with projects on mounted remote file systems.

**Comment by naromero77intel** [comment]
> > I am not sure if this is relevant, but I will mention that the filesystem on this workstation is NFS mounted.
> 
> Hi @naromero77intel . Can you attempt to repro when opening the project from a local file system? We have in the past seen issues with projects on mounted remote file systems.

Unfortunately, this is not possible. The Intel IT folks have a ridiculously small quota on the local file system. Its not even big enough to install the VS extensions :(

**Comment by Colengms** [comment]
Hi @naromero77intel .  That error message generally indicates a crash of the `cpptools` native process.  Does it happen right away?  If you're able to get the extension to activate without crashing (perhaps lauching VS Code with no source files open, and running an otherwise innocuous command, such as `C/C++: Log Diagnostics` to activate cpptools), could you try attaching a debugger to `cpptools`?  If a crash then occurs, perhaps when opening a source file, the debugger should catch the crash and make it possible to collect the stack.  If so, could you post the stack here?

**Comment by sean-mcmanus** [comment]
Peek Definition may cause Find All References to be invoked. Are using Peek Definition on the definition itself or on the usage of a variable/function?

If you set C_Cpp.loggingLevel to "Debug" you can see logging for what operations are being performed, so you could see if the Find All References is getting called and what the last message request we receive is before it starts to fail.

The "Tag Parser" mode is not supposed to launch cpptools-srv -- I wanted to see if other features like the workspace symbol stuff still worked as expected.

You don't see Format Document in the right-click menu or Command Palette? I wanted to see if you could launch the clang-format executable successfully.

**Comment by sean-mcmanus** [comment]
Also, the cpptools server crash seems like a new regression -- if you're able to attack to the process before it crashes to get a crash call stack (or enable a core dump logging), it could help us get a fix. We are not aware of what could be causing this crash yet.

**Comment by sean-mcmanus** [comment]
If the logging indicates that it's just getting stuck after a textDocument/definition (no references) then it could somehow be stuck accessing the database. You may try doing a Reset IntelliSense Database command from the command palette or changing the browse.databaseLocation setting (in c_cpp_properties.json or the C_Cpp.default.* setting). If an old process has a lock on the database, then restarting your machine or killing those dangling processes could fix it too.

**Comment by naromero77intel** [comment]
> Peek Definition may cause Find All References to be invoked. Are using Peek Definition on the definition itself or on the usage of a variable/function?

Usage of function. These functions are used sparingly as its new functionality that I am developing.

> 
> If you set C_Cpp.loggingLevel to "Debug" you can see logging for what operations are being performed, so you could see if the Find All References is getting called and what the last message request we receive is before it starts to fail.
> 

Yes, I have it set. Should the logging be going into the `OUTPUT` window? Or does it go somewhere else? I am not seeing anything.

> The "Tag Parser" mode is not supposed to launch cpptools-srv -- I wanted to see if other features like the workspace symbol stuff still worked as expected if cpptools-srv was not launched.

Correct. In "Tag Parser" mode, `cpptools-srv` is not launched.


> 
> You don't see Format Document in the right-click menu or Command Palette? I wanted to see if you could launch the clang-format executable successfully.

Sorry, I didn't make the connection (thought this was a setting). I just tried this and `Format Document` doesn't seem to do anything.

**Comment by sean-mcmanus** [comment]
You're opening the workspace folder through a symlink path, right? I believe you're hitting bug https://github.com/microsoft/vscode-cpptools/issues/4573 . Can you try to open the folder using the target of the symlink path instead?

**Comment by sean-mcmanus** [comment]
If that's not the issue, the logging seems to indicate it's somehow getting stuck after the call to "textDocument/definition", but I didn't see any stuck thread with the go to definition work on the call stack, so I'm not sure why it would be stuck.

**Comment by naromero77intel** [comment]
> You're opening the workspace folder through a symlink path, right? I believe you're hitting bug #4573 . Can you try to opening the folder using the target of the symlink path instead? And you should change C_Cpp.intelliSenseEngine back to "Default" if you want full IntelliSense to work again.

Yes, I am opening it through symlink. Now that I am opening it with the target of the symlink path it seems to be working with the `Default` IntelliSenseEngine.

Thanks for your help. Let's consider this a duplicate github issue and close it for now.

**Comment by sean-mcmanus** [comment]
Sure, I've filed an issue to potentially give a warning message when this happens, since people hit this issue somewhat frequently and the cause is not always immediately obvious: https://github.com/microsoft/vscode-cpptools/issues/9498 .
