### ISSUE TITLE
Intellisense is finding a ridiculous number of files in the workspace

### ISSUE THREAD

**Issue by Mastiff37** [microsoft/vscode-cpptools#9037]
Bug type: Language Service

**Describe the bug**
- OS and Version:  Linux CentOS7
- VS Code Version: 1.62.3
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them):  MS Python

My intellisense runs endlessly.  The big red flag is that it says "Parsing open files | Parsing workspace files: 0 / 31361340 (0%)".  That's 31 million files.  There is no way I have that many files even on the entire file system.  My actual workspace has approximately 24K files.

I can't say for sure this is a bug, but I really haven't done anything unusual with my config.  I don't know how it could reasonably have convince itself there are this many files to look at.

**Comment by sean-mcmanus** [comment]
Are you able to update to 1.8.4 or 1.9.4 (pre-release)?

You might be hitting some bugs/issue with our symlink handling. It's possible this might be worked around via adding paths to C_Cpp.files.exclude.

**Comment by Mastiff37** [comment]
I can look into updating, but I am on a sequestered system, so it'll take a little doing.  

Regarding exclude, are you suggesting looking through my workspace and basically pruning paths that don't lead to required code?  Thanks.

**Comment by sean-mcmanus** [comment]
Yeah, you'd need to update your VS Code to at least 1.63 to install 1.8.4 or later.

If you temporarily set the C_Cpp.loggingLevel to the hidden value of "7" and then C/C++: Rescan Workspace command -- it should output a bunch of logging about what paths it is finding during directory enumeration and I'm guessing there's a small number of "bad" paths or symlinks that are causing the issue that could be excluded.

**Comment by Mastiff37** [comment]
Thanks for the help.  If I want to exclude a path using C_Cpp.files.exclude, is it correct to add something like "/usr/include/boost/*":true ?  Just want to make sure I get that syntax right, as opposed to using double ** for example.

**Comment by sean-mcmanus** [comment]
You should just use "/usr/include/boost" (exclude the folder and therefore everything under it) without the `/*` (excluding all the files under it) because by default we set C_Cpp.exclusionPolicy such that file exclusions are disabled (for performance reasons).

**Comment by zinface** [comment]
![image](https://user-images.githubusercontent.com/46606043/158765751-0ee63364-6376-436b-ba2b-26fe48b5b88f.png)

My workspace was producing a lot of unaccessible files, and by excluding every plug-in I found that VScode-cppTools was causing the problem. A file name SQL statement was caught, for reasons I'm not sure if this is a vscode plug-in

**Comment by sean-mcmanus** [comment]
@zinface You hit https://github.com/microsoft/vscode-cpptools/issues/9041 -- it's fixed with 1.9.5.
