### ISSUE TITLE
Compiling and Running C

### ISSUE THREAD

**Issue by NejiHyuuga** [microsoft/vscode-cpptools#904]
I am new to vs code and have been working quite comfortably before the july update.
I tried a very basic Hello World Example and configured my Task.json and launch.json file.
I am able to build my code successfully but i am not able to view my output.
In my debug console, I see few warning messages too. I could not get that.
Help me resolve this issue.

VSCode Version:1.14.1
OS Version: Windows 7
Steps to Reproduce:

Build tasks.json by Ctrl+Shift+B
Run the code by F5.

**Comment by pieandcakes** [comment]
@nejihyuuga Please post your `launch.json`. When debugging it should open a separate command window on Windows that will close when debugging is over. I'd suggest adding a `scanf` statement after your `printf` if you want to see it.

**Comment by NejiHyuuga** [comment]
Hi Pieandcakes,

this is my launch.json file

{
    "version":"0.2.0",
      "MIDebuggerPath": "C://MinGW//bin//gdb.exe",
            "reveal":"always",
    "configurations": [
        {

        "name": "C++ Launch (Windows)",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "a.exe",
        "stopAtEntry": true,
        "externalConsole": true ,
        "cwd":"${workspaceRoot}"
        }
    ]    
}

**Comment by pieandcakes** [comment]
@nejihyuuga After looking at your project that you included in #905, I noticed you are compiling with `gcc` but expecting the Windows debugger to debug it. You need to create a `(gdb/lldb)` launch configuration. The Windows configuration is for use with Visual C++ on Windows.

**Comment by NejiHyuuga** [comment]
Does that mean, I should change my launch.json file like this

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:/MinGW/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

I still wonder what should be the text in setup commands

**Comment by pieandcakes** [comment]
@NejiHyuuga That looks correct except `"program"` needs to be the full path to the executable so you can probably use `"${workspaceRoot}\\a.exe"`

**Comment by NejiHyuuga** [comment]
Yeah. I got it and changed it

**Comment by NejiHyuuga** [comment]
But the problem is , I am facing an issue ."Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)" in debug console. What's the setup command attribute i should set

**Comment by pieandcakes** [comment]
@NejiHyuuga That isn't an issue. That's just letting you know you can execute additional debugger commands that the UI doesn't support. When you get that, it is debugging. Set a breakpoint in your code and F5. You should hit it.

**Comment by NejiHyuuga** [comment]
okay. I did try running the code. I still don't get the result. in console. I get only an empty console.

**Comment by NejiHyuuga** [comment]
And My code is not hit

**Comment by NejiHyuuga** [comment]
Yeah Got my output. thanks PieandCakes

**Comment by NejiHyuuga** [comment]
Thanks for the help

**Comment by pieandcakes** [comment]
@NejiHyuuga Sorry. Forgot you need to add "`-g`" to your `gcc` command in your `task.json` to compile with debug symbols.

**Comment by NejiHyuuga** [comment]
Okay Pieandcakes. :)
