### ISSUE TITLE
Version 1.9.4 (pre-release) C++ extension automatically creates garbled files in the workspace

### ISSUE THREAD

**Issue by j1angle0** [microsoft/vscode-cpptools#9041]
Bug type: Language Service

**Describe the bug**
- OS and Version:
   Win11
- VS Code Version:
   1.65.2
- C/C++ Extension Version:
   1.9.4(pre-release)
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
   Cent0S 7
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
  I updated to version 1.9.4 (pre-release), C/C++ automatically creates garbled files in the workspace，please check it, thanks
![Uploading 20220317-163832.png…]()

**Comment by Chuvi-w** [comment]
Same issue.
Also some source files becomes empty.

**Comment by sbovbjerg** [comment]
Confirmed on Linux in pre-release version. Lots of empty files with random filenames.
It seems to trigger when there are updates to the files in the project folder.
I can trigger the issue when this pre-release plugin is enabled. Problem goes away if I switch to the release version

**Comment by howardlau1999** [comment]
Same issue.

**Comment by RenoirTan** [comment]
> Confirmed on Linux in pre-release version. Lots of empty files with random filenames. It seems to trigger when there are updates to the files in the project folder. I can trigger the issue when this pre-release plugin is enabled. Problem goes away if I switch to the release version

Can confirm too. When I went back to 1.8.4, I didn't see anymore garbled files but once I switched back to the pre-release version vs code immediately spat out 300+ random files.

![Screenshot_20220317_205633](https://user-images.githubusercontent.com/76728966/158813779-e51f9afa-4965-46a8-803e-06119a8884c2.png)

**Comment by wendal** [comment]
Same issue. use a simple C project.
1. open it with vscode
2. exit vscode
3. rename the  directory
4. reopen it with vscode

then, one or many emtry file will create ,and some other file will be emtry.

![QQ图片20220317222544](https://user-images.githubusercontent.com/589819/158827918-fcd7b239-8453-46cd-be79-446251a6e99f.png)

**Comment by Hyreos** [comment]
Same issue.

![image](https://user-images.githubusercontent.com/21271840/158830322-115b3a5a-cf51-4543-a6b6-f23d6bc6aa5a.png)

**Comment by kblackcn** [comment]
> > Same issue. Also some source files becomes empty.
> 
> This problem also nuked entire files of my Boost installation. Since it is installed through the `mamba` package manager I got warnings that the files in my include folder has incorrect size (0kb).
> 
> Other projects I was working on are now full of garbled files and fail to compile. This kind of side effect really really shouldn't happen.
> 
> Update: this bug also deletes parts of the Python headers, so a reinstall of the affected Python environment is required.

I'm using root in docker for development. It seems any referenced headers with proper permission may be nuked. In my case, several linux headers are nuked and almost nothing compiles any more. If someone uses root on physical machine, they might have a very bad day fixing everything.

**Comment by sean-mcmanus** [comment]
Yeah, hugely sorry about this -- we have not yet been able to repro this issue locally and haven't identified the cause yet. Does anyone know if there's any pre-condition required for this to repro? Are there any special characters or spaces in the paths?

Downgrading to 1.9.3 or 1.8.4 is recommended.

Can someone on Windows x64 try https://github.com/microsoft/vscode-cpptools/releases/tag/1.9.4-prerelease1 and let us know if the bug repros with that or not? That vsix is identical to 1.9.4 except for one change to cpptools server and 3 updated DLL dependencies.

**Comment by kblackcn** [comment]
> Yeah, hugely sorry about this -- we have not yet been able to repro this issue locally and haven't identified the cause yet. Does anyone know if there's any pre-condition required for this to repro? Are there any special characters or spaces in the paths?
> 
> Downgrading to 1.9.3 or 1.8.4 is recommended.
> 
> Can someone on Windows x64 try https://github.com/microsoft/vscode-cpptools/releases/tag/1.9.4-prerelease1 and let us know if the bug repros with that or not? That vsix is identical to 1.9.4 except for one change to cpptools server and 3 updated DLL dependencies (and those DLLs were Windows-only show they couldn't cause the Linux issues).

I tried to reproduce this bug from scratch and find that a large project might help reproduction a lot. I tried with a single hello world and there is no problem, but once I extract `nginx.tgz`, the problem shows up (since vscode is actively monitoring the opened folder, then called the extension).

Also, since the written file looks like pieces of memory a lot, emptied file might just be the special case when that piece of memory happened to be the path of an included file in memory. So those two problems might just be one.

One of my colleague uses linux (without remote) only and I tried windows sshing linux and linux sshing linux. These combinations are all done. So it is definitely not a Windows problem.

**Comment by daantimmer** [comment]
To add, the files that are randomly created appear to be coming from a running process memory dumps. Some names are short, some are very long with strings that normally appear in an executable file. Without trying to give false pointers, but it sounds somewhere like a pointer had gone rogue, stack corruption or out of bounds issues

**Comment by michelleangela** [comment]
> Same issue. use a simple C project.
> 
> 1. open it with vscode
> 2. exit vscode
> 3. rename the  directory
> 4. reopen it with vscode
> 
> then, one or many emtry file will create ,and some other file will be emtry.
> 

@wendal 
Could you share this simple repository that we can reproduce this locally? And by "rename the directory", is this rename the project path or folder?

**Comment by sean-mcmanus** [comment]
1.9.5 is released -- which reverts to the 1.9.3 binaries, which should fix this issue.

**Comment by wendal** [comment]
@michelleangela
rename from "D:\github\LuatOS" to "D:\github\LuatOS123" , it will happen.
I just try 1.9.5, it seem ok.

**Comment by wendal** [comment]
install vxis from https://github.com/microsoft/vscode-cpptools/releases/tag/1.9.4-prerelease1, it happen again.
I uploaded the local directory as 7z. 
https://wetransfer.com/downloads/38c3b9dea19da30151708d1f6f5165b520220318010110/85d0e01b6ad6888d42c54634b301aba520220318010125/91e497

**Comment by sean-mcmanus** [comment]
@wendal Okay, thanks, that rules out some changes we made post-1.9.4-prerelease1 as the cause.

**Comment by j1angle0** [comment]
> 1.9.5 is released -- which reverts to the 1.9.3 binaries, which should fix this issue.
> 
> We're still investigating an actual fix though...

@sean-mcmanus Thanks, it's good for me

**Comment by sean-mcmanus** [comment]
The repro of renaming a folder doesn't repro the issue for us. None of us on our team have been able to repro the issue so far on multiple machines and projects (multiple user specified GitHub projects along with LLVM). We have not identified what factor causes the repro.

We've released a [1.9.6-prerelease1](https://github.com/microsoft/vscode-cpptools/releases/tag/1.9.6-prerelease1) update on GitHub (not via the Marketplace) that has a fix for a read of deleted memory along with the other reverted changes, but since we don't know how that read of deleted memory could cause the bug and we can't repro the bug, we're not sure yet if it's been fixed or not. We've run cpptool under Application Verifier and so far have not found any memory corruption issue.

I've created a discussion at https://github.com/microsoft/vscode-cpptools/discussions/9048 .

**Comment by Chuvi-w** [comment]
@sean-mcmanus 

I was unable to repro the issue in 1.9.4 with **C_Cpp: Logging Level** set to **debug**
When logging level was returned back to default, the issue appears again

**Comment by sean-mcmanus** [comment]
@sean-mcmanus Thanks a lot -- that makes sense (we typically test with debug logging set to Debug) -- changed the logging level to Error and now I got a app verifier hit with 1.9.6-prerelease1, i.e. it wasn't fixed. Investigating now...

**Comment by mtvjr** [comment]
I was hitting this bug today at work. I was using VSCode with a windows client over SSH into a Linux host. I only saw files generated in the base directory of my workspace on the Linux machine.

**Comment by sean-mcmanus** [comment]
@mtvjr Yeah, there was a memory corruption so in some cases if the memory happened to point to an existing file it would get reset to empty. It's been fixed and we're looking into various ways this could be prevented in the future.

**Comment by wangym307** [comment]
A python tool(works in Linux OS) wrote to delete files generated by this problem: https://github.com/wangym307/del_null_file
I hope it was useful for you, though it have risk of deleting useful null file.

**Comment by jake-the-eng** [comment]
> 
@sean-mcmanus Is there a 1.9.6 pre-release Linux VSIX as well? I have to install all of my extensions on an standalone machine and ran across this yesterday, specifically using the same setup as @mtvjr.

**Comment by michelleangela** [comment]
@jake-the-eng
The 1.9.6 pre-release version is not yet shipped, but when it is available the VSIX will be available for all our supported platforms including Linux.

You can use 1.9.5 pre-release (which does not have the file corruption issue) if you'd like until 1.9.6 is available.
The 1.9.5 pre-release VSIX for all our supported platforms can be downloaded from https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools.

**Comment by jharmer95** [comment]
I see this was moved to being done, but I didn't see it in the release notes for 1.9.7. Was this issue resolved for this release or was the behavior rolled back like the 1.9.5 prerelease?
