### ISSUE TITLE
Intellisense Not Working On Remote SSH

### ISSUE THREAD

**Issue by Bahnschrift** [microsoft/vscode-cpptools#9049]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 11 (Local), Debian (Remote)
- VS Code Version: 1.65.2
- C/C++ Extension Version: v1.8.4
- Other extensions you installed (and if the issue persists after disabling them): Remote - SSH
- If using SSH remote, specify OS of remote machine: Debian
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

This issue seems very similar to #7131 (though it does seem to be a different issue), in that it is arising when connecting to a school computer over ssh. I would have added this as a comment on that issue, but it's locked.

When connecting to the remote, intellisense does not appear to be functioning at all. There are no squiggles under invalid code, and some syntax highlighting is missing (see images). Interestingly, some of the auto suggestions do show up as I type, for example, variable and function names. 

There are no issues when using the extension locally.

I believe this to be a different issue to #7131 because it appeared that that issue was primarily caused by a slow remote, and waiting for a few seconds would allow intellisense to catch up, which doesn't work for me.

**Steps to reproduce**

1. Download the Remote - SSH extension and C/C++ extension
2. Connect to remote
3. Install the C/C++ extension on the remote
4. Open a directory containing a C/C++ file
5. Open the file and observe

**Expected behavior**

**Code sample and logs**

- Code sample
I tested using this cpp file:
```cpp
#include <iostream>
#include <vector>
#include <string>

using namespace std;

int main()
{
    vector<string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};

    for (const string& word : msg)
    {
        cout << word << " ";
    }

    cout << "There should be a squiggle because no semicolon." << endl

    cout << endl;
}
```

- Configurations in `c_cpp_properties.json`
Default (no configurations)

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 18/03/2022, 4:10:02 pm
Version: 1.8.4
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/clang",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /tmp_amd/kamen/export/kamen/4/username/intelisense/hello_world.cpp ]:
    /tmp_amd/kamen/export/kamen/4/username/intelisense/hello_world.cpp
Translation Unit Configurations:
[ /tmp_amd/kamen/export/kamen/4/username/intelisense/hello_world.cpp ]:
    Process ID: 49069
    Memory Usage: 49 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/8
        /usr/include/x86_64-linux-gnu/c++/8
        /usr/include/c++/8/backward
        /usr/lib/llvm-7/lib/clang/7.0.1/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=70001
Total Memory Usage: 49 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 8809
Number of files parsed: 345
```

- Debug Logs
Opening the file with log level set to debug gives this: https://pastebin.com/5VAvKkSf

**Screenshots**

Here's a side-by-side of the file open on the remote (left) and local (right)
![image](https://user-images.githubusercontent.com/31170809/158941558-c6c7eb18-246f-402c-b507-a606874a7b0e.png)

**Comment by sean-mcmanus** [comment]
Error squiggles are not supported for the "open file" scenario. You need to open a workspace folder first. Does that solve your issue? I see there is 1 error squiggle being reported in your logging.

**Comment by Bahnschrift** [comment]
My bad, I should have been more careful writing out the steps to reproduce the issue. I'll update them.

On both local and remote, I was opening the directory containing the file using code, not the files directly. I just tried creating a .code-workspace file in the directory on the remote with `hello_world.cpp`, which didn't seem to help either.

The debug log for opening the directory now with both  `hello_world.cpp` and the `.code-workspace` file is: https://pastebin.com/ueC2efYH

I should probably add that the issues are present with both C and C++ files.

**Comment by sean-mcmanus** [comment]
So are you able to see what the error squiggle says or is it not showing?

**Comment by Bahnschrift** [comment]
Same as the screenshot. No error squiggles showing and missing some syntax highlighting.

**Comment by sean-mcmanus** [comment]
Is there a symlink on the path? You may be hitting https://github.com/microsoft/vscode-cpptools/issues/4573

**Comment by Bahnschrift** [comment]
I didn't think to check that! Yes there is, it must be part of how the school handles ssh connections. Luckily, I also have access to the actual files, and accessing those works fine with intellisense.

Thanks for your help.
