### ISSUE TITLE
Compiling and Running C/C++ Code in Vs Code

### ISSUE THREAD

**Issue by NejiHyuuga** [microsoft/vscode-cpptools#905]
I am new to vs code and have been working quite comfortably before the july update.
I tried a very basic Hello World Example and configured my Task.json and launch.json file.
I am able to build my code successfully but i am not able to view my output.
In my debug console, I see few warning messages too. I could not get that(Refer the Debug console image attached).
Help me resolve this issue. 

VSCode Version:1.14.1
OS Version: Windows 7
Steps to Reproduce:

Build tasks.json by Ctrl+Shift+B
Run the code by F5.

[C.zip](https://github.com/Microsoft/vscode-cpptools/files/1162183/C.zip)
[debug console](https://user-images.githubusercontent.com/30308029/28416517-fbc26ef6-6d71-11e7-8174-1a87bcc77031.png)
(Note: When I reported this issue in , I was asked to repost it here.)

**Comment by pieandcakes** [comment]
@nejihyuuga this is the same issue as #904
