### ISSUE TITLE
Ability to use g++-10 instead of g++

### ISSUE THREAD

**Issue by AdamJamil** [microsoft/vscode-cpptools#9059]
Type: Feature Request

As title. I'm getting lints for g++ in WSL, but I'm compiling with g++-10, which is pretty confusing.

**Comment by sean-mcmanus** [comment]
We support usage of g++-10. Can you provide more info on the error you're seeing? What do you mean by "lints"?

**Comment by michelleangela** [comment]
Could you also provide your IntelliSense configuration (settings in c_cpp_properties.json file) or run the command `C/C++: Log Diagnostics`?
