### ISSUE TITLE
Intellisense doesn't seem to recognize #include_next directive

### ISSUE THREAD

**Issue by theseankelly** [microsoft/vscode-cpptools#906]
Using clang intellisense on an ARM project. Project overrides a standard header (stdint) and uses #include_next to selectively include stdint or throw an #error depending on build environment.

Intellisense doesn't seem to know what to do with it -- F12 doesn't open the header, it doesn't seem to register it as an include.

**Comment by sean-mcmanus** [comment]
IntelliSense works with #include_next (code items are correctly being found in the file), and so does Go to Definition on code items, but Go to Definition fails to work on the file name. We can probably fix that.

**Comment by theseankelly** [comment]
Oh I see. I'm having other issues with Intellisense that I thought I had narrowed down to that include_next directive.. guess I'm wrong! I'll keep looking through my project/environment defines for the issue. Thanks!
Sean

**Comment by nathanaelg** [comment]
Did you ever work out what the problem was @theseankelly I'm also having the same issue...

**Comment by sean-mcmanus** [comment]
@nathanaelg The issue that I fixed was "Go to Definition" on a #include_next.

There are many reasons a #include file may not be getting found. Can you file a new issue with more repro details, i.e. what OS and compiler framework are you using?

You might also want to try our insiders build and setting your compilerPath to your compiler to automatically pick up the correct compiler includes/defines: https://github.com/Microsoft/vscode-cpptools/releases/tag/v0.16.0-insiders .

**Comment by nathanaelg** [comment]
@sean-mcmanus I'm not really sure it's a bug, could just be a mis-configuration but I've tried the insider build (didn't seem to make a difference) and raised a new issue https://github.com/Microsoft/vscode-cpptools/issues/1672 as you suggested.
