### ISSUE TITLE
launch occurs (running previous executable file) even when build finishes with errors

### ISSUE THREAD

**Issue by KittenBill** [microsoft/vscode-cpptools#9060]
Steps to reproduce the problem:

1. open an empty folder and open it with vscode
2. write a C++ hello world program with an error
3. press F5 key to debug
4. VSCode automatically creates .vscode folder
5. Build finished with error(s), but launch still occurs

the cause of the problem probably lies at the "type" key in "tasks.json" file that VSCode automatically created. "type" should be either "process" or "shell", but VSCode sets it with initial value "cppbuild"

after changing value of "type" key from "cppbuild" to "process", launch fails as expected.

**Comment by elahehrashedi** [comment]
@KittenBill, This is by design. When hitting the F5, the program is being launched, and the prelaunch task is defined as to build the active file. The build fails and thus the launch fails too. 
the type of the tasks created by C/C++ extension is "`cppbuild`"

**Comment by KittenBill** [comment]
You didn't get me. The thing is when the value of "type" key is "cppbuild", launch just won't fail as expected however build fails.

**Comment by elahehrashedi** [comment]
related issue opened in VsCode: https://github.com/microsoft/vscode/issues/141654
