### ISSUE TITLE
macOS:  Unable to start debugging

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#9067]
I recently updated Xcode 13.3. When I try to start debugging I get the following message:

> Unable to start debugging. Program path '/Users/xxxxxx/Projects/GitHub/xxxxxx/build/vscode.macOS.Debug/bin/nc-tests' is missing or invalid.
>
> LLDB failed with message: Command 'file-exec-and-symbols'. Target binary '/Users/xxxxxx/Projects/GitHub/xxxxxx/build/vscode.macOS.Debug/bin/nc-tests' is invalid. error: more than one platform supports this executable (host, remote-macosx), specify an architecture to disambiguate
>
> This may occur if the process's executable was changed after the process was started, such as when installing an update. Try re-launching the application or restarting the machine.

**Comment by michelleangela** [comment]
Based on the error message, the file `nc-tests` is either missing or invalid. Could you check if `nc-tests` exists and can be executed manually? Also for which architecture is `nc-tests` compiled for? The error message form LLDB also says "more than one platform supports this executable" and to specify a target architecture for it.

**Comment by WardenGnaw** [comment]
> LLDB failed with message: Command 'file-exec-and-symbols'. Target binary '/Users/xxxxxx/Projects/GitHub/xxxxxx/build/vscode.macOS.Debug/bin/nc-tests' is invalid. error: more than one platform supports this executable (host, remote-macosx), specify an architecture to disambiguate

Can you add a `setupCommands` section in your `launch.json` configuration?

```
"setupCommands": [
   {
      "text": "set architecture arm64", // or x86_64
      "description": "Specifies target architecture",
      "ignoreFailures": false
   }
}
```

**Comment by H-G-Hristov** [comment]
> > LLDB failed with message: Command 'file-exec-and-symbols'. Target binary '/Users/xxxxxx/Projects/GitHub/xxxxxx/build/vscode.macOS.Debug/bin/nc-tests' is invalid. error: more than one platform supports this executable (host, remote-macosx), specify an architecture to disambiguate
> 
> Can you add a `setupCommands` section in your `launch.json` configuration?
> 
> ```
> "setupCommands": [
>    {
>       "text": "set architecture arm64", // or x86_64
>       "description": "Specifies target architecture",
>       "ignoreFailures": false
>    }
> }
> ```

I tried this setting but I still get the same error message.

**Comment by FrankBlabu** [comment]
Might that be related to https://github.com/microsoft/vscode-cpptools/issues/9088 ?

**Comment by H-G-Hristov** [comment]
I'm closing this as it appears to be an LLDB issue. It is not yet fixed. I'm waiting for LLDB 5.7.
