### ISSUE TITLE
Cannot Auto-Break During Assert Failure In Remote Machine

### ISSUE THREAD

**Issue by daiyousei-qz** [microsoft/vscode-cpptools#9072]
Bug type: Debugger

- OS and Version: Windows 10
- VS Code Version: 1.65.2
- C/C++ Extension Version: v1.8.4
- Other extensions you installed (and if the issue persists after disabling them): clangd and etc.
- A clear and concise description of what the bug is.

Actually, I'm not sure if this should be counted as a bug/missing feature. When an assertion failure is hit in windows, the system would pop a message box and asks for the next action. When clicking retry, we could break on the failed assert. But when debugging in a remote machine, GUI isn't available so the program will just abort.

**To Reproduce**
```
#include <cassert>

int main() {
    assert(0); // abort the program in remote machine
}
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
