### ISSUE TITLE
Some times syntax highlighting is not available for some words.

### ISSUE THREAD

**Issue by thefatwhale** [microsoft/vscode-cpptools#9077]
Bug type: Language Service

**Describe the bug**
- OS and Version: Microsoft Windows 7 x64 sp1
- VS Code Version: 1.63.2
- C/C++ Extension Version: 1.7.1
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. Use it and it becomes like this
2. 
![image](https://user-images.githubusercontent.com/50515732/159754927-080e63ff-5b3f-478d-8bfa-39037dbb8b31.png)
![image](https://user-images.githubusercontent.com/50515732/159754991-453ecea1-043a-480d-852b-387ad43901db.png)

**Only the reloaded vscode will display properly**

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
It seems like the IntelliSense process may be crashing, losing the enhanced colorization. Do you repro the issue with 1.9.6 (pre-release) or the 1.9.7 (which we'll release later today)?

Do you get C/C++ logging about the IntelliSense process crashing?

This info might help:
* Logs from running C/C++: Log Diagnostics from the VS Code command palette

* Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Comment by thefatwhale** [comment]
After using the new version this problem does not seem to appear anymore, thank you
