### ISSUE TITLE
A symbol named "virtual" can be renamed (in C)

### ISSUE THREAD

**Issue by emsaks** [microsoft/vscode-cpptools#9081]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 7 & 11
- VS Code Version: 1.65.2
- C/C++ Extension Version: 1.9.7
- Other extensions you installed (and if the issue persists after disabling them):

- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

In a C file, when a symbol named 'virtual' is renamed, or you try to find all references, the error "A definition for the selected symbol could not be located." is given. This is probably because it is a keyword in C++.

**Steps to reproduce**

Create new file with .c extension;

Type: 
```
int virtual;

main () {
 virtual = 5;
}
```

Right click on 'virtual', choose rename.
See error.

**Expected behavior**
Proper renaming support

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. Yeah, we were excluding C++ keywords. I've changed it to only exclude the C keywords when processing go to def, find all references, and rename

**Comment by sean-mcmanus** [comment]
This should be fixed with 1.10.2 (pre-release).
