### ISSUE TITLE
data-disassemble slows down debugging a lot

### ISSUE THREAD

**Issue by devzeb** [microsoft/vscode-cpptools#9084]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10 
- VS Code Version: 1.65.2
- C/C++ Extension Version: v1.9.7

I am having trouble debugging using vscode.
If i hit a breakpoint and want to continue, sometimes vscode needs a long time.
In the "Debug Console" window, i can see the following output during that step:

```
Debug: Gdb command: -data-disassemble -s 0x00041efc -e 0x000425f0 -- 5     1780 bytes  
Debug: Gdb command: -data-disassemble -s 0x000425f0 -e 0x0004271c -- 5      300 bytes  
Debug: Gdb command: -data-disassemble -s 0x0004271c -e 0x00042788 -- 5      108 bytes  
Debug: data-disassemble -s 0x00041efc -e 0x000425f0 -- 5 => Found 821 instrunctions. 820 with source code, 1 without
Debug: data-disassemble -s 0x000425f0 -e 0x0004271c -- 5 => Found 138 instrunctions. 137 with source code, 1 without
Debug: data-disassemble -s 0x0004271c -e 0x00042788 -- 5 => Found 49 instrunctions. 49 with source code, 0 without
Debug-48: Elapsed time for Disassembly Request: 17022 ms
```

I do not have the disassembly view open, so I am a bit confused why these commands run in the first place.
Is there an option to disable these data-disassemble requests?

I am debugging an embedded target using a CMSIS DAP debugger through openocd.

**Comment by WardenGnaw** [comment]
This log dosen't look like the format of our debug adapter `cppdbg`, can you share your `launch.json` file?

**Comment by devzeb** [comment]
My mistake, it seems like this output is from the cortex-debug extension.
If I'm directly using gdb instead of this plugin in my launch.json, it works as expected.
