### ISSUE TITLE
Extension cannot be installed via command line option '--install-extension'

### ISSUE THREAD

**Issue by FrankBlabu** [microsoft/vscode-cpptools#9088]
Bug type: General

**Describe the bug**
- OS and Version: Windows 10 Enterprise 20H2
- VS Code Version: 1.65.2
- C/C++ Extension Version: 1.9.7
- Installed extensions: - (Just this one)

When installing the extension via command line option `--install-extension`, the command initially succeeds. But after starting VSCode afterwards the first time, the extension initializes itself and in this process deletes its installation data again.

The extension host log shows the following message after the VSCode restart:

`[2022-03-25 08:59:57.036] [sharedprocess] [error] Delete: Unable to delete the existing folder 'c:\gom\VSCode-1.65.2\data\extensions\ms-vscode.cpptools-1.9.7' while installing the extension 'ms-vscode.cpptools'. Please delete the folder manually and try again
    at r.extractUserExtension (vscode-file://vscode-app/c:/gom/VSCode-1.65.2/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:206754)
    at async M.extract (vscode-file://vscode-app/c:/gom/VSCode-1.65.2/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:220509)
    at async M.doRun (vscode-file://vscode-app/c:/gom/VSCode-1.65.2/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221402)`

Afterwards, the extension folder misses various data. This does **not** happen if the extension is installed interactively via the VSCode UI.

Command used for extension installation:

`<vscode-dir>\bin\code.cmd --install-extension ms-vscode.cpptools`

**To Reproduce**

1. Download VSCode 1.65.2 (ZIP file version) and unzip it.
2. `<vscode-dir>\bin\code.cmd --install-extension ms-vscode.cpptools`.
3. Start VSCode.
4. Open extensions tab and wait until the cpptools extension state switches from 'installing' to 'installed'.
5. Take a look into the extension host log and see the above error message.
6. Take a look into the `<vscode-dir>\data\extensions\ms-vscode.cpptools` directory and you will notice that various files are missing.

**Expected behavior**

Command line based installation should work the same way as if installed interactively.

**Screenshots**

Empty directory after the 'reproduce' steps above (German version only, sorry):

![empty](https://user-images.githubusercontent.com/27698648/160081302-8810e5eb-98f8-4102-98a3-bbe6a8cdccbd.png)

**Workaround**

* Install extension interactively.
* **But:** This breaks automated rollout processes (we are using a script to setup a VSCode installation for rollout of this amazing tool with every major version) and will add lots of data to the `data/user-data` folder.

**Comment by FrankBlabu** [comment]
Actually, I cannot rule out that some external effect like a virus scanner is involved here (disabling it would require a huge amount of bureaucracy). The remaining content of the directory is:

![bin](https://user-images.githubusercontent.com/27698648/160088479-e0a9f6ae-5036-42f0-832b-4a70ad788c1e.png)

So an educated guess is that `cpptools` is either not properly terminated or some other tool like a virus scanner is accessing and locking it. Either way, a fail-safe delete might be of some use here.

**Comment by FrankBlabu** [comment]
And some more insight: After comparing an old and a more recent installation, this effect does **not** happen in vs-code.cpptools version 1.8.4 ! So I claim you do have a bug here.

![versions](https://user-images.githubusercontent.com/27698648/160131760-65726528-09ba-45a0-afdf-9c582bd72fd1.png)

**Comment by sean-mcmanus** [comment]
Can you file a bug with VS Code? I don't think our extension can be responsible for this. VS Code is responsible for all the installation.

**Comment by FrankBlabu** [comment]
Yes, but version 1.9.6 is working fine in the exact same setup. So I suspect there might be some change in the 1.9.7 code which triggers this behavior. Additional remark: "Insiders channel" has been enabled. Maybe this plays some role.

Please just close this issue if I should file a VSCode bug instead, I will then do so.

**Comment by sean-mcmanus** [comment]
Version 1.9.6 is identical to 1.9.7 except 1.9.6 was built with the "pre-release flag" (and a different changelog.md file, which shouldn't make a difference). I still think this is a VS Code bug.
