### ISSUE TITLE
Unable to start debugging. No terminal is available to launch the debugger. Please install Gnome Terminal or XTerm

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#91]
I'm using rxvt-unicode, do I really need to install one of those? Can I set what terminal to use somewhere?

**Comment by delmyers** [comment]
Unfortunately, we can't support all terminals. We have to set up special stdin/stdout redirection in order to make gdb work correctly. Each terminal has a different way to do this, and the debugger must launch the terminal in order to do the redirection. Sorry for the inconvenience.
