### ISSUE TITLE
Why IntelliSense does not suggest struct members?

### ISSUE THREAD

**Issue by UR3IQO** [microsoft/vscode-cpptools#910]
Is the following behavior normal? I expect IntelliSense to give suggestions after typing . or ->

![vscode1](https://user-images.githubusercontent.com/25171239/28488854-970ddd32-6ebc-11e7-939f-b93e36df5c48.gif)

Here are Windows 8, VSCode v1.14.1 and cpptools 0.12.1.

**Comment by MrSparc** [comment]
You can turn on the new IntelliSense by changing the “C_Cpp.intelliSenseEngine” setting in your settings.json file (open from menu File->Preferences->Settings) from “Tag Parser” to “Default”, as shown in the screenshot below.

https://blogs.msdn.microsoft.com/vcblog/2017/07/18/visual-studio-code-cc-extension-july-2017-update-time-to-try-out-the-new-intellisense/

**Comment by UR3IQO** [comment]
@MrSparc it was set to ``"Default"`` on that screen.

**Comment by MrSparc** [comment]
Your code works as expected in my VSC with intelliSense for struct members, so I think that the issue can be something related with your installation or folder/projet preferences. The described behaviour is not normal using the new intellisense engine.
Try to create a C/C++ file in a new empty folder and open using VSC to check if this issue continues to happen.

**Comment by UR3IQO** [comment]
@MrSparc 
The same behaviour with the new folder and single test file in it.

**Comment by sean-mcmanus** [comment]
I'm not able to repro the problem. You might be falling back to the Tag Parser. Do you have errors in your Problems window?

**Comment by UR3IQO** [comment]
@sean-mcmanus No, I have no errors in the Problems window.

**Comment by bobbrow** [comment]
I just ran into this on Windows 7 while testing something out yesterday.  Sometimes the list popped up automatically, and sometimes I had to manually invoke the list with <kbd>CTRL</kbd>+<kbd>Space</kbd>.

@sov1178 Does <kbd>CTRL</kbd>+<kbd>Space</kbd> pop up the list for you after typing the `.` or `->`?  I'm wondering if it's a Windows 7/8 issue since we don't see it on Windows 10.

**Comment by UR3IQO** [comment]
@bobbrow If I press Ctrl+Space it shows the list, but list content is not what I expect. It lists all symbols in database or something similar:
![vscode2](https://user-images.githubusercontent.com/25171239/28731795-0199b2b8-73de-11e7-882b-d8cae9088475.gif)
And yes I use Windows 8.

**Comment by UR3IQO** [comment]
I do not know if it is important, but I use VS Code for cross platform development (for the ARM target and arm-gcc compiler).

**Comment by sean-mcmanus** [comment]
@sov1178 You're seeing the TextMate completion provided by VS Code (the "abc" results). You're not getting results from our extension (which give the different icons based on type). You need to change your intelliSenseMode in c_cpp_properties.json to "clang-x64" if you're building with gcc.

**Comment by UR3IQO** [comment]
@sean-mcmanus I have changed intelliSendMode to clang-x64, but had the same problem - it use IntelliSense completion until I type . or -> (as on picture in the first message). :(

**Comment by UR3IQO** [comment]
With "clang-x64" I have one more problem. After minute or so of normal work - the red flame icon does not go away indicating "Parsing...".

**Comment by FMLS** [comment]
@sov1178 @sean-mcmanus 
the same problem as sov1178, when i type -> or .  that list a large list that content is not what I expect!

**Comment by sean-mcmanus** [comment]
@FMLS The behavior you describe is from the "Tag Parser" engine. Is your intelliSenseEngine setting "Default" with no message in the Problems window?

**Comment by FMLS** [comment]
@sean-mcmanus thanks！ I ignore the Problems window, I find a file can't be search, It auto use Tag parse .

**Comment by UR3IQO** [comment]
Some news about the problem after VSCode and cpptools update (VSCode v.1.15.1 / x64, cpptools 0.12.2). Now IntelliSense shows suggestions. It looked like it was ok, but I have added one more struct and got:
![vscode2](https://user-images.githubusercontent.com/25171239/29402715-a90677a6-833e-11e7-9319-2482d51cbd53.gif)
Is it ok? I expect that only 'S' struct members should be in the list. Now it behaves as the Tag Parser, but I have the "C_Cpp.intelliSenseEngine": "Default" line in the settings.

I would be glad to provide any additional information.

**Comment by bobbrow** [comment]
That is definitely the Tag Parser providing your suggestions.  Notice the difference in the detail tooltip between your GIF and my screenshot:

![910](https://user-images.githubusercontent.com/12818240/29420643-5e4c4108-8327-11e7-9055-3b5db25a1c3f.png)

The Tag Parser doesn't attempt to show you the type that owns the member.  I don't reproduce your problem on my PC when I set the engine to "Default".  But if this is the only file in the workspace and your c_cpp_properties.json only includes ${workspaceRoot} in the browse.path, I can confirm that I saw the exact same suggestions as you when the Tag Parser was enabled.  Can you double-check your settings?

**Comment by UR3IQO** [comment]
@bobbrow I have checked my settings several times - it should use new intelliSense engine. I also added intelliSense selection option to the workspace settings with no effect. Changing "Default" to "Tag Parser" does not change intelliSense behavior. Here is the archived test project.  
[pr1.zip](https://github.com/Microsoft/vscode-cpptools/files/1233507/pr1.zip)

And here are the logs:
[vscode.cpp.log.5236.txt](https://github.com/Microsoft/vscode-cpptools/files/1233513/vscode.cpp.log.5236.txt)
[vscode.cpp.log.8168.txt](https://github.com/Microsoft/vscode-cpptools/files/1233514/vscode.cpp.log.8168.txt)

**Comment by bobbrow** [comment]
I copied your project and it still doesn't repro for me. 😢

Your logs confirm that you have selected the new IntelliSense engine and that completion is being offered, but I don't see any requests appearing in the IntelliSense engine's log (implying that the request is going to the tag parser).  The logs also report 2 error squiggles, but doesn't say what they are.  When I open your project on my PC, I don't see any squiggles.  Does your problems window say that we are using the Tag Parser?  Sadly, I don't have this information in the log (I need to add it...).

**Comment by UR3IQO** [comment]
@bobbrow 
> Does your problems window say that we are using the Tag Parser?

My problems windows says that there are no problems. I do not know how I can see what intellisense mode is used from the information in the problems window.

**Comment by bobbrow** [comment]
When we start using the Tag Parser instead of the Default engine, we add a problem to the problems window so that was what I was looking for.  This is the only spot in the extension where we override your settings.

I'm at a loss as to why you are not getting the correct IntelliSense behavior so I am adding some additional logging to the extension which should help us diagnose this further.

**Comment by UR3IQO** [comment]
@bobbrow  Thank you for the explanation!

I have just upgraded to cpptools 0.12.3, and checked the problem. Now it behaves differently - it does not provide any suggestions after typing `.` or `->`.

Here is the log (I increased verbosity level to 7 in hope to record any useful information, please let me know if you need logs with different settings). I see some errors in the log (see line 225 and the following lines). Also there are 4 more log files with zero size.
[vscode.cpp.log.6640.txt](https://github.com/Microsoft/vscode-cpptools/files/1235368/vscode.cpp.log.6640.txt)

Let me know if you need any help I may provide.

**Comment by bobbrow** [comment]
Oh, I see.  The IntelliSense engine appears to have crashed:

> failed to read response from server: 16
> errorSquiggles count: 0
> IntelliSense client has disconnected from the server

The error messages are incorrectly categorized and should have shown up in the earlier log.  I'll get that fixed.

If you have the time, [this article](https://bugslasher.net/2011/03/26/how-to-debug-a-process-as-soon-as-it-starts-with-windbg-or-visual-studio-2010/) has some information about how to attach to a process when it launches (I believe you said you're using Windows 7).  If you are able to attach to the process, save the crash dump, and paste it here, that would be very helpful.

**Comment by bobbrow** [comment]
Sorry, I left out an important detail.  The process you want to attach to is `Microsoft.VSCode.CPP.IntelliSense.Msvc.exe`.

**Comment by UR3IQO** [comment]
@bobbrow Here is Windows 8 x64, I will try to attach to the process tomorrow.

**Comment by UR3IQO** [comment]
@bobbrow 
I have the crash dump, hope it will help:
[Microsoft.VSCode.CPP.IntelliSense.Msvc.dmp.zip](https://github.com/Microsoft/vscode-cpptools/files/1236139/Microsoft.VSCode.CPP.IntelliSense.Msvc.dmp.zip)

**Comment by bobbrow** [comment]
Thank you.  I can reproduce the crash and am working on a fix.

**Comment by bobbrow** [comment]
The fix for this is in the update we pushed yesterday
