### ISSUE TITLE
[Run/Debug Code] button unable to run code from global launch configurations ('program' is missing)

### ISSUE THREAD

**Issue by vecbool** [microsoft/vscode-cpptools#9106]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 11 22000.593
- VS Code Version: 1.65.2
- C/C++ Extension Version: 1.9.7
- Other extensions you installed (and if the issue persists after disabling them): no other related extensions
- A clear and concise description of what the bug is: Can‘t run code through [run/debug] button, but no problem with F5

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
1. Open global (not workspace) settings, add c++ launch configuration
```json
    "launch": {
        "configurations": [
            {
                "name": "C++",
                "type": "cppdbg",
                "request": "launch",
                "program": "${workspaceFolder}/build/${fileBasenameNoExtension}.exe",
                "cwd": "${workspaceFolder}",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ],
                "preLaunchTask": "c++-build", // generate executable program in the build directory
            }
        ]
    }
```
2. Open a c++ source file
3. Click the run/debug button
4. Select the previously added configuration
5. See error: 'program' is missing
<img width="274" alt="image" src="https://user-images.githubusercontent.com/49444390/160541348-17b18469-a2d2-4bf3-b4ff-58ae1ac6318e.png">

**Additional context**
*If applicable, please include logging by adding "logging": { "engineLogging": true, "trace": true, "traceResponse": true } in your `launch.json`*
Add any other context about the problem here including log or error messages in your Debug Console or Output windows.

**Comment by sean-mcmanus** [comment]
Fixed with 1.10.5.
