### ISSUE TITLE
The command `Tasks: Run Build Task` not working in single-mode file.

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cpptools#9111]
Currently, this feature doesn't seem to be used in single-mode files that frequently, most users are using this feature when a folder is open. We can shift the priority if more users are interested in this feature.

**Comment by bobbrow** [comment]
@elahehrashedi was this done in 1.9 or 1.10?

**Comment by sean-mcmanus** [comment]
@bobbrow 1.10.
