### ISSUE TITLE
"return cnt;<Enter>" incorrectly completes to "return continue;"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#9115]
Caused by https://github.com/microsoft/vscode-cpptools/issues/8932 .

We return the "continue;" as completion, but then VS Code never gives us an opportunity to cancel the completion after the ";" is typed. I don't see a good way to work around it, so I'm just going to revert the change.

UPDATE: Reverting the change isn't necessary -- we found another fix.

**Comment by Dromantor** [comment]
Also interferes when defining single letter variables with custom/typedef'd types.

`uint16_t b;<Enter> => uint16_t break;`

**Comment by sean-mcmanus** [comment]
@Dromantor Yes, that is right. Anything that happens to "fuzzy match" the characters in "break" or "continue" and ends with a semicolon.

**Comment by sean-mcmanus** [comment]
Fixed with 1.10.2 (pre-release).
