### ISSUE TITLE
name followed by '::' must be a class or namespace name

### ISSUE THREAD

**Issue by chaslain** [microsoft/vscode-cpptools#9118]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: 1.6.52
OS Version: Windows 10 Pro 19044.1586
Steps to Reproduce:

Install Microsoft C/C++ Extensions
Write a program that uses std::chrono::time_point
Chrono will appear in read underlines with the message
Compile and run, the program has no issues (g++ compiler)

**Comment by sean-mcmanus** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/19859882/160922463-335740ce-4b15-4f5f-959f-55b2942828ac.png)

What do you see when you run the C/C++: Log Diagnostics command from the Command Palette, i.e. what g++ compiler are you using?

**Comment by AlanHeckinJohnston** [comment]
@sean-mcmanus 
-------- Diagnostics - 3/30/2022, 5:02:54 PM
Version: 1.9.7
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:/msys64/mingw64/bin/gcc.exe",
    "cStandard": "c99",
    "cppStandard": "c++98",
    "intelliSenseMode": "gcc-x64",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ C:\Users\Alan\Documents\cpp\main.cpp ]:
    C:\Users\Alan\Documents\cpp\main.cpp
Translation Unit Configurations:
[ C:\Users\Alan\Documents\cpp\main.cpp ]:
    Process ID: 2528
    Memory Usage: 31 MB
    Compiler Path: C:/msys64/mingw64/bin/gcc.exe
    Includes:
        C:\MSYS64\MINGW64\INCLUDE\C++\11.2.0
        C:\MSYS64\MINGW64\INCLUDE\C++\11.2.0\X86_64-W64-MINGW32
        C:\MSYS64\MINGW64\INCLUDE\C++\11.2.0\BACKWARD
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE
        C:\MSYS64\MINGW64\INCLUDE
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\11.2.0\INCLUDE-FIXED
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++03
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=110200
Total Memory Usage: 31 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3330
![image](https://user-images.githubusercontent.com/31631811/160930578-da0f01b4-2f4e-4fd4-ad26-0acfdf88f9f7.png)
I am not using a template on the type, which I'm not sure if it is an issue as it compiles just fine.

**Comment by sean-mcmanus** [comment]
It doesn't compile for my g++ 11.2. Also, your cppStandard is set to C++98/03, which doesn't support the chrono header.

**Comment by AlanHeckinJohnston** [comment]
Got it, so it's a divorce between version of g++ and c++ within vscode. Thank you for your time, you can mark this closed.
