### ISSUE TITLE
Language service is idle, "Invalid opened file instance. Ignoring IntelliSense message for file" for multiroot workspace

### ISSUE THREAD

**Issue by VFeoktistov** [microsoft/vscode-cpptools#9120]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 21H2
- VS Code Version: 1.66
- C/C++ Extension Version: 1.9.7
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Extension pack v1.1.0 (without CMake-related extensions). Issue still persists.
- If using SSH remote, specify OS of remote machine: Windows Server 2019
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
1. Connect via SSH to remote Windows OS;
2. Add the directory that is adjacent to the `${workspaceFolder}` in step 4 (it should not have `.vscode` folder unlike the next two);
3. Add several sub-directories of a `${workspaceFolder}`;
4. Add the `${workspaceFolder}` itself;
5. Switch "C_Cpp: Logging Level" to "Debug"
6. Hovering over C++ code will reveal `Unsupported Markup content received. Kind is:`
7. In "C/C++" Output window there should be `Invalid opened file instance. Ignoring IntelliSense message for file X`

**Expected behavior**
IntelliSense is expected to work on hover.

**Code sample and logs**

- Configurations in `c_cpp_properties.json`
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/subdir1/**",
                "${workspaceFolder}/subdir2/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
        }
    ],
    "version": 4
}
```

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 3/31/2022, 2:50:23 PM
Version: 1.9.7
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/include/sycl"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.17763.0",
    "compilerPath": "cl.exe",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": false,
    "compilerArgs": [],
    "cStandard": "c17",
    "cppStandard": "c++17",
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/include/sycl"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.
```

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
```
loggingLevel: Debug
cpptools/didChangeCppProperties
Attempting to get defaults from C++ compiler in "compilerPath" property: 'cl.exe'
Attempting to get defaults from C compiler in "compilerPath" property: 'cl.exe'
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/VC/TOOLS/MSVC/14.16.27023/ATLMFC/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/VC/TOOLS/MSVC/14.16.27023/INCLUDE/* will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/CPPWINRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/SHARED/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UCRT/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/UM/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/WINDOWS KITS/10/INCLUDE/10.0.17763.0/WINRT/ will be indexed
  Folder: C:/<WORKSPACE FOLDER>/ will be indexed
  Folder: C:/PROGRAM FILES (X86)/INTEL/ONEAPI/COMPILER/LATEST/WINDOWS/INCLUDE/SYCL/ will be indexed
textDocument/didOpen: <FILE1>
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: <FILE1>
cpptools/getDocumentSymbols: <FILE1> (id: 2)
cpptools/getCodeActions: <FILE1> (id: 3)
cpptools/getFoldingRanges: <FILE1> (id: 4)
cpptools/getSemanticTokens: <FILE1> (id: 5)
textDocument/hover: <FILE1> (id: 6)
Invalid opened file instance. Ignoring IntelliSense message for file <FILE1>.
cpptools/getDiagnostics (id: 10)
```

**Additional context**
This bug might be related to #8762, so steps to reproduce should be similar.

**Possible workarounds**
- exclude step 2;

**Comment by sean-mcmanus** [comment]
The issue https://github.com/microsoft/vscode-cpptools/issues/8762 reproed when cpptools crashed. I'm so far not able to repro this issue. I'm checking if anyone else on our team is able to repro this.

**Comment by VFeoktistov** [comment]
Hi @sean-mcmanus ,
Sorry if I wasted your time mentioning the old issue. Although it gave a clue for me, so I was able to come up with the workaround. I also noticed a certain pattern in VSCode's behavior: when I change the `.code-workspace` file while I am in that workspace, it reloads the window if I move the folder at step 2 to the start of `"folders"` array or to the end. Reloading does not happen if I only move around the actual workspace folder or it's subfolders.
Language service did not crash for me - it just stays idle practically from the moment I open the workspace.

**Comment by sean-mcmanus** [comment]
So what is the folders property for the repro and what causes it to stop reproing?

I have
```
	"folders": [
        {
            "path": "."
        },
        {
            "path": "sub1"
        },
        {
            "path": "sub2"
        },
        {
            "path": "..\\siblingFolder"
        }
```

**Comment by VFeoktistov** [comment]
The folders property looks for me like this:
```json
"folders": [
        {
            "path": ".\folder1"
        },
        {
            "path": ".\folder2\sub1"
        },
        {
            "path": ".\folder2\sub2"
        },
        {
            // The initial workspace folder
            "path": ".\folder2"
        }
]
```

**Comment by sean-mcmanus** [comment]
I'm still not reproing the issue. I'll try to see if anyone else on our team is able to.

**Comment by VFeoktistov** [comment]
Yes. I see now, there is more to it than I have described here. I will try to add more details as I discover them. Unfortunately, I cannot share the workspace file and the folders, so please, bear with me.
