### ISSUE TITLE
Autocomplete not autocompleting structure member in +=, -=, ... assignments for C

### ISSUE THREAD

**Issue by Dromantor** [microsoft/vscode-cpptools#9121]
Extension Version v1.9.7
Language: C

Normal assignment: works
![grafik](https://user-images.githubusercontent.com/1822013/161061287-11e1fc24-23af-45d1-811a-13df48a4f302.png)

+=: doesn't work
![grafik](https://user-images.githubusercontent.com/1822013/161061218-3d5d558d-b7b5-4556-85dc-de41a8a76ae5.png)

Same for all other operator-assignments (I discovered it with |=).

**Comment by sean-mcmanus** [comment]
This appears to be similar to the fixed issue https://github.com/Microsoft/vscode-cpptools/issues/2184 except "+=" is used instead of "=" followed by a +, i.e. it might have the same fix, but they need to apply it to the "+=" operators too.

**Comment by sean-mcmanus** [comment]
This should be fixed with 1.10.2 (pre-release).
