### ISSUE TITLE
Can we use the IntellisenseMode (compiler) we define instead of being overridden?

### ISSUE THREAD

**Issue by rtillery** [microsoft/vscode-cpptools#9124]
Type: Feature Request

I am working on a cross-compiled project for an ARM device. Since build is done with the gcc compiler, I wanted to have VSCode use the clang compiler, so I could get both sets of error messages during development. However, even though I purposely set the "intelliSenseMode" in c_cpp_properties.json to "linux-clang-arm64", I get the notification that the C & C++ "IntelliSenseMode was changed from 'linux-clang-arm64' to 'linux-gcc-amd64'". Since C++ compiler messages are notoriously difficult to parse, it seems to me that two sets of error messages from two different compilers is likely to provide me more informative information than one.

I did find https://github.com/microsoft/vscode-cpptools/issues/8286, which says this is "by design." I understand that matching the build compiler is most likely to be desired by most devs. But I would like the option to not be overridden by the tool & utilize the clang compiler for Intellisense.

Is this a reasonable request, due to differences in compiler arguments? Would it be possible to add the ability to use a different compiler for Intellisense than compilation? Or, is there currently a way to avoid the override?

**Comment by sean-mcmanus** [comment]
The intelliSenseMode/compilerPath are just used for IntelliSense so the error messages you would get would be the same. You could still build with gcc and clang, but you'd need to choose which mode you want to run IntelliSense with -- the compiler/mode used for IntelliSense can be different from the one used for compiling. And you could have 2 configs in c_cpp_properties.json and switch between them to compare results -- usually they should give the same results, but sometimes we have bugs that only repro in one mode and not others, and you also may have some code that executes differently depending on the compiler.

**Comment by sean-mcmanus** [comment]
Yeah, you just need to set your compilerPath to the clang compiler or the equivalent if you're using compileCommands or configurationProvider. You also may need to set the appropriate compilerArgs so that it's handled as arm64.
