### ISSUE TITLE
Frequent window not responding popup

### ISSUE THREAD

**Issue by sssteja5** [microsoft/vscode-cpptools#9126]
Issue Type: <b>Bug</b>

After disabling all extensions, and enabling one by one, i notice that this extension causes frequent 'Window not responding' popup.

Extension version: 1.9.7
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-90-generic

**Comment by sean-mcmanus** [comment]
Also, is there any high CPU or memory usage from VS Code or any of its child processes like cpptools/cpptools-srv processes?

**Comment by sssteja5** [comment]
@michelleangela : 'windows not responding' happens randomly. No correlation with hover/find_reference, etc. 
I dont have a local machine and always use this extension on a remote ssh machine.
These are my extension settings
 "C_Cpp.configurationWarnings": "Disabled",
  "C_Cpp.errorSquiggles": "Enabled",
  "C_Cpp.intelliSenseEngineFallback": "Enabled",
  "C_Cpp.workspaceSymbols": "All",
  "C_Cpp.codeAnalysis.runAutomatically": false

@sean-mcmanus : Didn't notice. Will check next time i hit this issue and update here.

**Comment by michelleangela** [comment]
>I dont have a local machine and always use this extension on a remote ssh machine.

Just to rule out the Remote SSH extension, does this also occur even when the C/C++ extension is disabled on the remote machine?

**Comment by sssteja5** [comment]
No. The issue doesn't occur when disabled C/C++ extension as described before with everything else kept as it is. Hence it's narrowed down to this extension.

**Comment by michelleangela** [comment]
Could you collect a performance profile using the developer tools on VS Code? Note, the performance profile records screenshots of the session, so we recommend to use a project or sample project you wouldn't mind sharing publicly.

**Instructions to collect performance profile:**
1. Run "Developer: Toggle Developer Tools" from VS Code command palette.
2. Select "Performance" tab 
![image](https://user-images.githubusercontent.com/38734287/161834682-3e3053bb-87ca-4300-824a-04075e62ca8f.png)
3. Start recording session.
4. After repro occurs, stop recording.
5. Right click to "save profile".

**Comment by zouyonghao** [comment]
[Profile-20220517T170934.zip](https://github.com/microsoft/vscode-cpptools/files/8706895/Profile-20220517T170934.zip)

Hi @michelleangela 
I try to use the developer tools and upload the profile, you can see if it helps.

**Comment by zouyonghao** [comment]
Can we solve the performance issue, because my vscode cannot work due to this for several days.
Maybe some issues are related, like https://github.com/microsoft/vscode-cpptools/issues/9339

**Comment by michelleangela** [comment]
@zouyonghao 
The profile log doesn't show anything related to the cpptools extension. The bottleneck could be caused by Remote SSH, I suggest to post the profile logs at the Remote SSH repro https://github.com/microsoft/vscode-remote-release/issues.

In case it is related to #9339, have you tried disabling the IntelliSense cache or setting `C_Cpp.intelliSenseCacheSize` to `0` to see if that improves performance? Or does this issue occur during any formatting operations? If so, could you also try disabling formatting by the cpptools extension by setting `C_Cpp.formatting` to `Disabled`?

**Comment by zouyonghao** [comment]
@michelleangela 
Today I switch to clangd extension, and vscode does not stuck again with same other extensions.

I tried setting C_Cpp.intelliSenseCacheSize to 0, and it still stucks.
I also tried setting C_Cpp.intelliSenseEngine to Disabled, it does not stuck.
I will try C_Cpp.formatting later.

**Comment by sssteja5** [comment]
Hi,
I am no longer seeing this issue after recent vscode updates. not sure what fixed my problem.

**Comment by michelleangela** [comment]
Closing as resolved.
