### ISSUE TITLE
How to setup recursive includePath for standard c++ libraries?

### ISSUE THREAD

**Issue by omar-selo** [microsoft/vscode-cpptools#913]
I have created a c_cpp_properties.json file and added to the Linux configuration as follows:
```json
{
    "name": "Linux",
    "includePath": [
        "${localappdata}/lxss/rootfs/usr/include",
        "${localappdata}/lxss/rootfs/usr/local/include",
        "${workspaceRoot}/include"
    ],
    "defines": [],
    "intelliSenseMode": "clang-x64",
    "browse": {
        "path": [
            "${localappdata}/lxss/rootfs/usr/include",
            "${localappdata}/lxss/rootfs/usr/local/include",
            "${workspaceRoot}"
        ],
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": "$[workspaceRoot}/.vscode/.browse.VC.db"
    }
}
```
Note that I am developing on windows but using bash on windows and thus Linux configuration.

I have also added `"C_Cpp.intelliSenseEngine": "Default"` to the settings.json file and changed vscode configuration to Linux.

However I still see green squiggly lines under my includes saying 'cannot open source file "x"' for the standard c++ libraries.

I noticed however that if I include the full path of the directory containing the standard library headers (e.g. `${localappdata}/lxss/rootfs/usr/include/c++/5/`) then I don't see the squiggly lines anymore for some of the standard headers.

From my understanding browse.path is recursive but includePath is not. But does that mean that I have to include the full path for every directory that has the standard c++ include files that I need for my project?

**Comment by bobbrow** [comment]
Does [the sample c_cpp_properties.json we posted for WSL](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Windows%20Subsystem%20for%20Linux.md) help?

**Comment by omar-selo** [comment]
Works like a charm. I don't know how I missed that. 
Thanks!

**Comment by adrianmak** [comment]
@Bazalia  Which thing did u miss? I got similar problem

**Comment by sean-mcmanus** [comment]
@adrianmak What is your OS and compiler? Have you tried https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md#why-do-i-see-red-squiggles-under-standard-library-types ?
