### ISSUE TITLE
Auto refresh or single click for all repositories in Source Control 

### ISSUE THREAD

**Issue by sssteja5** [microsoft/vscode-cpptools#9133]
Type: Feature Request

For any changes in a repo, we need to manually refresh in Source Control to see the changes. Difficult to track if there are multiple changes across multiple repos. Good to have "Auto refresh or single click for all repositories in Source Control"

**Comment by michelleangela** [comment]
@sssteja5 
Did you mean to post this request on the [VS Code client repository](https://github.com/Microsoft/vscode) or an extension that provides source control features? This repository is for the C/C++ extension which provides IntelliSense and debugging features for C/C++ language.

**Comment by sssteja5** [comment]
I mean to post for vscode repository which has default source control feature where I suggested this extra add on

**Comment by sssteja5** [comment]
Reason for closing this ? Is it already implemented ? I didn't select  C/C++ extension while reporting this feature

**Comment by michelleangela** [comment]
@sssteja5
This issue was closed because this is the C/C++ extension repository and the C/C++ extension does not provide source control features.
