### ISSUE TITLE
The language server crashed 5 times in the last 3 minutes. It will not be restarted.

### ISSUE THREAD

**Issue by nishiket04** [microsoft/vscode-cpptools#9134]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `1.9.7`
- OS Version: `Windows_NT ia32 6.1.7601`
- VS Code version: `1.66.0`

The language server crashed 5 times in the last 3 minutes. It will not be restarted.

**Comment by Rayeen13** [comment]
@michelleangela 
I Tried The **Latest Vscode( User Setup, System Setup and Insider)** and Got The Same Problem.
Tried Different Versions Of C/C++ Extension from Microsoft But Still Same Thing Happened.
cpptools:
**The Language Server crashed 5 Times In The Last 3 Minutes. it Will Not Be Restarted.**

**Comment by michelleangela** [comment]
@Rayeen13 
Just to double check, in the different versions you tried, did version 1.8.4 also crashed? Versions 1.9.* had some new binaries that could be causing the crash on Windows 7.

**Comment by nishiket04** [comment]
@michelleangela i tried different versions of c/c++ and also uninstalled and re-install it.
C/C++ extension logging:
loggingLevel: Debug
cpptools/didChangeCppProperties
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu++14 -Wp,-v -E -dM -x c++ -m32  nul
Attempting to get defaults from C compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu11 -Wp,-v -E -dM -x c -m32  nul
  Folder: C:/MINGW/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/USERS/NISHIKET/DESKTOP/ will be indexed
Discovering files...
  Processing folder (recursive): C:/MINGW/INCLUDE/
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/
cpptools/getSemanticTokens: C:\Users\Nishiket\Desktop\m.c (id: 2)
cpptools/getSemanticTokens: C:\Users\Nishiket\Desktop\stribg.cpp (id: 3)
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/
  Processing folder (recursive): C:/USERS/NISHIKET/DESKTOP/
  Discovering files: 1241 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  tag parsing file: C:\Users\Nishiket\Desktop\m.c
cpptools/didChangeCppProperties
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu++14 -Wp,-v -E -dM -x c++ -m32  nul
Attempting to get defaults from C compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu11 -Wp,-v -E -dM -x c -m32  nul
  Folder: C:/MINGW/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/USERS/NISHIKET/DESKTOP/ will be indexed
Discovering files...
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
  Processing folder (recursive): C:/MINGW/INCLUDE/
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/
  Processing folder (recursive): C:/USERS/NISHIKET/DESKTOP/
  Discovering files: 1241 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  tag parsing file: C:\Users\Nishiket\Desktop\m.c
cpptools/didChangeCppProperties
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu++14 -Wp,-v -E -dM -x c++ -m32  nul
Attempting to get defaults from C compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu11 -Wp,-v -E -dM -x c -m32  nul
  Folder: C:/MINGW/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/USERS/NISHIKET/DESKTOP/ will be indexed
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
Discovering files...
  Processing folder (recursive): C:/MINGW/INCLUDE/
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/
  Processing folder (recursive): C:/USERS/NISHIKET/DESKTOP/
  Discovering files: 1241 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  tag parsing file: C:\Users\Nishiket\Desktop\m.c
cpptools/didChangeCppProperties
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu++14 -Wp,-v -E -dM -x c++ -m32  nul
Attempting to get defaults from C compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu11 -Wp,-v -E -dM -x c -m32  nul
  Folder: C:/MINGW/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/USERS/NISHIKET/DESKTOP/ will be indexed
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
Discovering files...
  Processing folder (recursive): C:/MINGW/INCLUDE/
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/
  Processing folder (recursive): C:/USERS/NISHIKET/DESKTOP/
  Discovering files: 1241 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  tag parsing file: C:\Users\Nishiket\Desktop\m.c
cpptools/didChangeCppProperties
Warning: Database safety check failed. Recreating database.
[rc=0x80004005] (DB: false, Expected: true)
Code browsing service initialized
Attempting to get defaults from C++ compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu++14 -Wp,-v -E -dM -x c++ -m32  nul
Attempting to get defaults from C compiler in "compilerPath" property: 'C:\MinGW\bin\gcc.exe'
Compiler query command line: "C:\\MinGW\\bin\\gcc.exe" -std=gnu11 -Wp,-v -E -dM -x c -m32  nul
  Folder: C:/MINGW/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/ will be indexed
  Folder: C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/ will be indexed
  Folder: C:/USERS/NISHIKET/DESKTOP/ will be indexed
cpptools/didChangeSettings
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
Discovering files...
  Processing folder (recursive): C:/MINGW/INCLUDE/
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE/
  Processing folder (recursive): C:/MINGW/LIB/GCC/MINGW32/6.3.0/INCLUDE-FIXED/
  Processing folder (recursive): C:/USERS/NISHIKET/DESKTOP/
  Discovering files: 1241 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populating include completion cache.

**Comment by michelleangela** [comment]
@nishiket04 
Could you list the versions you tried and also list the versions that worked?

For example, which version was used for the language server logging that was posted?

**Comment by nishiket04** [comment]
@michelleangela 
1.9.7, 1.8.4, 1.8.2, 1.7.1 none of them works

**Comment by michelleangela** [comment]
@nishiket04 
Thank you for listing the versions tested.

For the logs you provided from "C/C++ extension logging:", if there is logging available it means the language server is working. At the start of the process and before it crashes, could you attach a debugger to the cpptools.exe process (this is the language server) and get a call stack of the crash?

**Instructions for getting call stacks**
https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv](https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv)
