### ISSUE TITLE
Assertion failed launching remote gdb, with stop at entry true

### ISSUE THREAD

**Issue by jessicah** [microsoft/vscode-cpptools#9135]
Bug type: Debugger

**Describe the bug**
- OS and Version: Windows 10 21H2 (OS Build 19044.1586)
- VS Code Version: 1.65.2 (user setup)
- C/C++ Extension Version: 1.9.7
- When `stopAtEntry` is set to `true`, gdb aborts immediately after stopping in `main`: `/build/gdb-wIRHdd/gdb-12.0.90/gdb/value.c:1731: internal-error: value_copy: Assertion `arg->contents != nullptr' failed.`

**To Reproduce**
launch.json:
```
{
	"configurations": [
	{
		"name": "(gdb) Launch",
		"type": "cppdbg",
		"request": "launch",
		"program": "${workspaceFolder}/jam0",
		"args": [],
		"stopAtEntry": true,
		"cwd": "${workspaceFolder}",
		"environment": [],
		"externalConsole": false,
		"MIMode": "gdb",
		"setupCommands": [
			{
				"description": "Enable pretty-printing for gdb",
				"text": "-enable-pretty-printing",
				"ignoreFailures": true
			},
			{
				"description":  "Set Disassembly Flavor to Intel",
				"text": "-gdb-set disassembly-flavor intel",
				"ignoreFailures": true
			}
		]
	}
	]
}
```

**Additional context**
Debug Console: https://gist.github.com/jessicah/674070f34a3f55cfb486d59d44be3c82

**Comment by WardenGnaw** [comment]
Are you building/debugging gdb itself or debugging a different c/c++ project. 

The logs indicate that GDB is asserting, which might be a potential debug build, and it also shows its using version 12.0 which the developer branch was just created March 20th, 2022.

```
/build/gdb-wIRHdd/gdb-12.0.90/gdb/value.c:1731: internal-error: value_copy: Assertion `arg->contents != nullptr' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
/build/gdb-wIRHdd/gdb-12.0.90/gdb/value.c:1731: internal-error: value_copy: Assertion `arg->contents != nullptr' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB?
ERROR: GDB exited unexpectedly. Debugging will now abort.
```

If you are debugging your own project, I would recommend using a released version of GDB such as 11.2 or lower.

**Comment by jessicah** [comment]
Oh, my Ubuntu install comes with gdb-12. I removed, compiled and built gdb-11.2, and everything is all good. Thanks for pointing that out :)

**Comment by audetto** [comment]
I got the same issue. Is there a gdb bug report already?

**Comment by fogbank** [comment]
I've just run into the same issue, and I could at least not produce this error by uninstalling libc-dbg.

**Comment by audetto** [comment]
https://bugs.launchpad.net/ubuntu/+source/gdb/+bug/1971409

**Comment by Hoernchen** [comment]
actual gdb bug: https://sourceware.org/bugzilla/show_bug.cgi?id=28980
already fixed in gdb, but apparently not yet packaged.

**Comment by GitLuc1** [comment]
Easy temporarily fix:
https://github.com/microsoft/vscode-cpptools/issues/103#issuecomment-1151217772

**Comment by JaylinYu** [comment]
same issue here
