### ISSUE TITLE
Suggestions on code prompt will not show symbols that aren't defined

### ISSUE THREAD

**Issue by Wakotu** [microsoft/vscode-cpptools#9136]
In some cases, the code prompt function doesn't work.
such as following
```c
struct sigaction sa;
sa.sa_handler = handler;
```
When you had entered "sa.", the sa_handler option didn't occur in the prompt list.
I found that in standard definitions, "sa_handler" attribute was wrapped in a `#if... #else...#endif` block. It might be the reason why the code prompt function failed.
```c
struct sigaction
  {
    /* Signal handler.  */
#if defined __USE_POSIX199309 || defined __USE_XOPEN_EXTENDED
    union
      {
	/* Used if SA_SIGINFO is not set.  */
	__sighandler_t sa_handler;
	/* Used if SA_SIGINFO is set.  */
	void (*sa_sigaction) (int, siginfo_t *, void *);
      }
    __sigaction_handler;
# define sa_handler	__sigaction_handler.sa_handler
# define sa_sigaction	__sigaction_handler.sa_sigaction
#else
    __sighandler_t sa_handler;
#endif

    /* Additional set of signals to be blocked.  */
    __sigset_t sa_mask;

    /* Special flags.  */
    int sa_flags;

    /* Restore handler.  */
    void (*sa_restorer) (void);
  };
```

**Comment by michelleangela** [comment]
@yqy-pong-ops 
If IntelliSense completion is being used and the symbol is not defined according to IntelliSense (or under a `#define` that is not defined), then the symbol will not show in the completion results.
