### ISSUE TITLE
CPP Tools API For Extracting Header Metadata?

### ISSUE THREAD

**Issue by ComethTheNerd** [microsoft/vscode-cpptools#914]
Hello

I was wondering how my code could interface with the extension to obtain an AST (or really just info about the declarations/symbols) for a given header file? Similar to how the TypeScript compiler API provides an AST for .ts files.

Thanks

**Comment by bobbrow** [comment]
Unfortunately, there is no way to do this today.  It is also not in our plans to expose such an API at this time.
