### ISSUE TITLE
Configuration squiggles don't work with environment variables

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#9140]
Code is at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/configurations.ts#L1904 -- it's not detecting a match there. I also noticed some strange handling of `\\` and `/` when debugging.

Repro is
```
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${env:foo}/foo"
            ]
        }
    ],
    "env": {
        "foo": "C:\\somepath"
    },
```

**Comment by bobbrow** [comment]
This appears to be fixed in the latest version of the extension.
