### ISSUE TITLE
Adding extra button or Modifying the functionality of a button in vscode debug console

### ISSUE THREAD

**Issue by secondpivot** [microsoft/vscode-cpptools#9143]
Type: Feature Request

I would like to execute **-exec detach** in the debug console whenever I click the stop button in the console or add new button to bind this functionality.

**Comment by WardenGnaw** [comment]
This would be adding a [`contributes.debug.view`](https://code.visualstudio.com/api/references/contribution-points#contributes.views) and sending a DetachRequest through the DebugSession.

**Comment by subhikaran** [comment]
Hi @WardenGnaw could give me a simple example or documentation for me to clearly understand?  
I am trying to execute -exec detach command  for c++ debugger by clicking stop or adding new button to do this. 

Thanks in advance

**Comment by WardenGnaw** [comment]
You will want to modify the `package.json` to include a new view contribution using the link in my comment above.

Then you will want to use the VSCode API to grab the [activeDebugSession](https://code.visualstudio.com/api/references/vscode-api#debug).

With the [DebugSession](https://code.visualstudio.com/api/references/vscode-api#DebugSession), you can call `customRequest` and send a [DisconnectRequest](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Disconnect).

The debug adapter should already support this request, so there are no changes needed in the debug adapter, just the extension UI.

**Comment by subhikaran** [comment]
Thanks @WardenGnaw We were able to arrive at the solution with your help. Below is the code which we used in our solution

**vscode.debug.activeDebugSession.customRequest("disconnect",{
terminateDebuggee:false
});**
