### ISSUE TITLE
IntelliSense doesn't show quick info when typing

### ISSUE THREAD

**Issue by qtoyam** [microsoft/vscode-cpptools#9146]
Bug type: Language Service

**Describe the bug**
- OS and Version: Win10(2004 and 21H1)
- VS Code Version: 1.66.0
- C/C++ Extension Version: 1.9.7
- Other extensions you installed (and if the issue persists after disabling them): none
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

IntelliSense doesn't show quick info about function when typing.
![image](https://user-images.githubusercontent.com/94015161/161883915-ad19050f-b809-4468-8488-14ce3f3b1114.png)
But when mouse is hover the function, info is displayed.
![image](https://user-images.githubusercontent.com/94015161/161884056-e37118fb-9f87-4d52-b6df-04378d5ed1ba.png)

I've tried to setup all step-by-step(from this guide: https://code.visualstudio.com/docs/cpp/config-mingw) on clean virtual machine(Win10 21H1), and quick info still doesnt display when typing.

**Expected behavior**
Quick info is displayed when typing.
![image](https://user-images.githubusercontent.com/94015161/161883469-39aeb176-12c6-4bce-a2ab-85452b215ade.png)

**Code sample and logs**
- Configurations in `c_cpp_properties.json`
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:/mingw64/bin/g++.exe",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "windows-gcc-x64"
        }
    ],
    "version": 4
}

**Comment by michelleangela** [comment]
@qtoyam 
Additional information of a symbol in a suggestion list can be displayed by typing `ctrl` + `space` while a symbol is selected. Could you try `ctrl` + `space` and see if that displays more info on a suggested symbol?

**Comment by qtoyam** [comment]
@michelleangela
Yes, it works. I thought that ctrl+space will just trigger intellisense same as typing dot.
Thanks.
