### ISSUE TITLE
IntelliSense process crash detected at `do_constexpr_expression()`

### ISSUE THREAD

**Issue by adamfk** [microsoft/vscode-cpptools#9148]
Bug type: Language Service

**Describe the bug**
IntelliSense crashes at `do_constexpr_expression()`. Easy to reproduce repo: https://github.com/adamfk/vscode-cpp-bug-report-1

Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043

C/C++ for Visual Studio Code Version 1.9.7: March 23, 2022

Single tiny project. See repo below.

**Steps to reproduce**
1. clone this repo https://github.com/adamfk/vscode-cpp-bug-report-1/
2. open directory in vscode
3. open file trigger.hpp and observe IntelliSense crashing repeatedly

**Expected behavior**
No IntelliSense crash. 

**Code sample and logs**
- Code sample
https://github.com/adamfk/vscode-cpp-bug-report-1/blob/master/trigger.hpp

- Configurations in `c_cpp_properties.json`
None.

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
https://github.com/adamfk/vscode-cpp-bug-report-1/blob/master/diagnostics.txt

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
https://github.com/adamfk/vscode-cpp-bug-report-1/blob/master/logs.txt

**Additional context**
Stack trace: https://github.com/adamfk/vscode-cpp-bug-report-1/blob/master/call-stack.txt

**Comment by sean-mcmanus** [comment]
Thanks for reporting this.

The crash doesn't repro with C++17 due to different code being used with the cl.exe/msvc headers in that case, so you could switch to that as a workaround.

I've filed an internal bug on our VS parser (1515742).

**Comment by sean-mcmanus** [comment]
I believe this is fixed with 1.10.0 (pre-release) -- let us know if you're still hitting it.
