### ISSUE TITLE
clang-tidy integrated in C/C++ does not correctly recognize the type after type alias `using`, cppcoreguidelines-init-variables

### ISSUE THREAD

**Issue by nolongerwait** [microsoft/vscode-cpptools#9154]
Bug type: Language Service

**Describe the bug**
- OS and Version: macOS 12.3 (21E230)
- VS Code Version: 
```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.4.0
```
- C/C++ Extension Version: v1.9.7
- Other extensions you installed (and if the issue persists after disabling them): None
- If using SSH remote, specify OS of remote machine: Debian GNU/Linux 10

I declare a variable of type `std::map` , like `std::map<std::string, std::string>  vars`, but this type has type alias `using LOGTags = std::map<std::string, std::string>` which is declared in the referenced third party.
![kx5cVRcVla](https://user-images.githubusercontent.com/22978131/162363794-57da6b4d-e5bc-47af-93a2-60634b962e4c.png)
![0a3nWsYeXI](https://user-images.githubusercontent.com/22978131/162363806-a3ad9f81-f3e4-42b7-9fa7-44c3c1dcf964.png)

As you can see in the image above, the C/C++ extension prompts me that this variable need to initialize. But in the clang-tidy specification, the std::map type does not need to be explicitly initialized. And it is impossible for me to initialize at this time in the project, because I don't know what content it will store at this time.

When I delete the alias statement in the third party code, it can work normally.
<img width="823" alt="image" src="https://user-images.githubusercontent.com/22978131/162364280-6a90cea4-4fd1-472c-9583-e0c80a42361b.png">

**Expected behavior**

Regardless of whether the current type is aliased elsewhere, if I explicitly specify the type of the current variable, it should be inferred to be the explicitly specified type. rather than the aliases used elsewhere.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/22978131/162364187-86600b9e-aec9-43e3-a0c9-d7322d300503.png">

**Comment by nolongerwait** [comment]
Fine, why it still note me to initialise when I  have initialised the std::map
<img width="856" alt="image" src="https://user-images.githubusercontent.com/22978131/162375452-5c335d5a-c907-48dc-93fa-659be830663c.png">

**Comment by sean-mcmanus** [comment]
I'm not able to repro the "variable 'vars' is not initialized" clang-tidy error. Are you able to provide more repro info, such as a specific code sample and maybe the required settings?

The type alias on hover is a known issue with IntelliSense -- the behavior is inherited from VS. I'm not sure yet if there's a way to improve that.
