### ISSUE TITLE
Extremely slow error and syntax highlighting

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#9155]
Issue Type: <b>Performance Issue</b>

[vs code performance issue](https://youtu.be/oFlGYXuINpA)
This video displays the issue im facing.

Error highlighting for missing semicolons/commas takes forever to disappear and appear.

Syntax highlighting on variables (making them red in this case) is also painfully slow. 

The issue cannot be explained well through a small project like the one in the video but its apparent in larger projects (of 300+ lines).

Extension version: 1.9.7
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:51:26.173Z)
OS version: Linux x64 5.13.0-37-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3637)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|6, 7, 5|
|Memory (System)|15.53GB (8.75GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 6854eedf-8a64-4373-ab33-731d8f12b61f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   159	 17514	code main
    0	    32	 17516	   zygote
    0	    80	 17625	     gpu-process
    0	    32	 17517	   zygote
    0	    95	 18911	     issue-reporter
    0	    48	 17569	   utility-network-service
    0	   223	 17589	   window (helloworld.c - GetOpt - Visual Studio Code)
    0	   127	 17654	   shared-process
    0	    64	 17686	     ptyHost
    0	     0	 17807	       /usr/bin/bash
    0	    64	 17712	     fileWatcher
    0	     0	 18931	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 18932	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   127	 17670	   extensionHost
    0	    16	 17748	     /home/aneeshb/.vscode/extensions/ms-vscode.cpptools-1.9.7-linux-x64/bin/cpptools
    0	    16	 17829	       /home/aneeshb/.vscode/extensions/ms-vscode.cpptools-1.9.7-linux-x64/bin/cpptools-srv 17748 {8FC9D534-F964-485C-9426-1099479C4263}
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (helloworld.c - GetOpt - Visual Studio Code)
|    Folder (GetOpt): 3 files
|      File types: c(2)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
vscaac:30438847
pynewfile477:30463512

```

</details>

**Comment by michelleangela** [comment]
@Korokoukousei 
Could you provide a performance analysis log of the either the cpptools or cpptools-srv process that is causing a lot of CPU cycles for the larger project you're seeing the poor performance on? The logs may help show which part of the extension is causing the issue.

Instructions to capture performance analysis log are at https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues#linux.

**Comment by Korokoukousei** [comment]
![image](https://user-images.githubusercontent.com/70006643/163685350-438e265e-ed99-4e2d-8443-09143033a63e.png)
![image](https://user-images.githubusercontent.com/70006643/163685355-e30b753d-fb9d-474b-a2ea-792fe98eabce.png)
![image](https://user-images.githubusercontent.com/70006643/163685360-d30366f1-ef9f-40ff-be9c-5541ab24e96d.png)
![image](https://user-images.githubusercontent.com/70006643/163685365-e01f0b83-2ab4-4e98-80e7-cef39f733bba.png)
![image](https://user-images.githubusercontent.com/70006643/163685374-282cfd53-2b96-4363-8af5-edb9f092fa9c.png)

Here are the requested reports. Sorry for the huge delay, I was trying out other text editors to find my fit.

**Comment by Korokoukousei** [comment]
![image](https://user-images.githubusercontent.com/70006643/163685466-e47b9028-2f7f-4561-a24f-44d6c50fe1cd.png)
Heres another report i let run in the background while coding.

**Comment by Korokoukousei** [comment]
@michelleangela I'm being a bit impatient here. But I need to setup my development environment ASAP. Is this issue (post) still open or should I repost it?

**Comment by bobbrow** [comment]
Yes, this issue is still open. We're not generally at work on the weekend. Can you collect performance data on the `cpptools-srv` process that is acting slow for you?  The best thing to do is only have one cpp file open in the editor so that there is only one `cpptools-srv` process to collect the performance data for.  Unfortunately, the features you identified as being slow for you are not executing in the `cpptools` process that you captured.

**Comment by Korokoukousei** [comment]
Okay so, my problem is slow syntax highlighting and error highlighting.
The steps i followed right now are -
File >> Close Folder
Open a new instance of vs code and open an isolated folder with a single .c file
Run pidof command on cpptools-srv to get a singular pid
Run sudo perf record -a -g -d -p <pidof cpptools-srv>
Code for a while (wrote a hello world program, declared many variables, wrote a few \#include statements etc.)
Run sudo perf report -g graph

Here is the result obtained - 
![image](https://user-images.githubusercontent.com/70006643/163839093-2a5b7344-ebbe-4d5a-823b-4d92e44d7240.png)

**Comment by Korokoukousei** [comment]
Side note, I'm an extreme beginner at Linux. I would love to screenshare somehow and get instructions on how to fix my issue.

**Comment by michelleangela** [comment]
@Korokoukousei 
There doesn't seem to be anything unusual in the logs of the cpptools-srv. Was the log from a source file with small number of code lines? If not, could you try to capture logs with the large project where you usually experience slow updates of error and syntax highlighting? For the new logs, could you also expand the tree of the items with high percentage (see step #3 in https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues#viewing-the-performance-report-log-and-sending-screenshot-samples-of-the-log to expand/collapse an item).

Could you also run the command `C/C++: Log Diagnostics` and provide the logs. It will should how much memory is being used per translation unit for a source file.

Please noteit is normal for IntelliSense to update "slowly" if a translation unit is large. The larger the translation unit, then the longer it takes for IntelliSense to parse it to evaluate the code. Therefore, smaller source files may be faster to update than larger source files.

**Comment by Korokoukousei** [comment]
Unfortunately my perf graph keybinds were a bit different than what i read in the article.
I have captured two videos showing what you have asked for, uploading them to drive and attached is the drive link.

[](https://drive.google.com/drive/folders/1J8DhFZP72-HYXQ1tWyoyaurN6MQ7jaDn?usp=sharing)

**Comment by michelleangela** [comment]
Thank you for the videos of the repro. Based on the video of editing a file of 50 lines, IntelliSense is updating within 1-2 seconds as expected after an edit is completed. The expanded tree of the profiling log didn't show any stacks that appear abnormal.

There is the setting `C_Cpp.intelliSenseUpdateDelay` that controls when to start updating after editing a file. The default is 2000 milliseconds, Could you try changing it to 500 milliseconds and see if it changes the update speed after doing an edit to a file?

Do you have any other `C_Cpp.*` settings configured as well?

**Comment by Korokoukousei** [comment]
Unfortunately even turning it down to 500 doesn't match the speeds that I get while programming in JavaScript or even C# in visual studio code. I have decided to switch to vim for superior speeds and error highlighting for c/cpp.
