### ISSUE TITLE
Language server does not treat `_MT` as defined when MD/MT switch is passed to compiler

### ISSUE THREAD

**Issue by stravant** [microsoft/vscode-cpptools#9161]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.66
- C/C++ Extension Version: v1.9.7

The language server does not understand that when the `-MD`/`/MD` or `-MT`/`/MT` switch is passed to the compiler, the macro `_MT` should be defined.

**Steps to reproduce / Code Sample**
1. Create a file `test.cpp` with the following source code:
```
#if defined(_MT)
#error "TestError"
#endif
```

2. Create a `compile_commands.json` with the following:
```
[
{
    "directory": "C:/",
    "command": "cl.exe -MD -c test.cpp",
    "file": "test.cpp"
}
]
```

3. Open VSCode and set the "Compile Commands" setting to point at the `compile_commands.json`.

4. Open `test.cpp`. Observe that the contents of the block are greyed out because _MT is not being treated as defined.

5. Compile `test.cpp` from the command line using `cl.exe -MD -c test.cpp`, observe that the error **does** get thrown because _MT *is* being treated as defined.

**Expected behavior**

The language server should define the `_MT` macro when the `MD` or `MT` switch is passed to the compiler in the `compile_commands.json` for a file, and thus in the above scenario the `#error` line should not be greyed out.

See the documentation on the MD/MT switches here: https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros

**Comment by Colengms** [comment]
Hi @stravant .  I'm unable to easily reproduce this issue.  Using a simple example, I see that `_MT` is defined properly.  

From my `compile_commands.json`:
```
{
  "directory": "Z:/repos/test2/build",
  "command": "cl.exe -MD -c Z:\\repos\\test2\\test2.cpp",
  "file": "Z:\\repos\\test2\\test2.cpp"
}
```

From the log output to the C/C++ channel (with `"C_Cpp.loggingLevel": "Debug"` set): 
```
sending compilation args for Z:\repos\test2\test2.cpp
  include: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\VC\TOOLS\MSVC\14.32.31326\INCLUDE
  include: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\VC\TOOLS\MSVC\14.32.31326\ATLMFC\INCLUDE
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UM
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UCRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\SHARED
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\WINRT
  include: C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\CPPWINRT
  define: _MT
  define: _DLL
  stdver: ms_c++17
  intelliSenseMode: windows-msvc-x64
```

I suspect the issue may be related to some conflicting configuration information in your repro.  Can you provide a repro we can investigate further, such as in the form of a GitHub repo?
