### ISSUE TITLE
ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". During startup program exited with code 0xc0000139.

### ISSUE THREAD

**Issue by kd-boss** [microsoft/vscode-cpptools#9165]
Bug type: MSYS2 GDB 11.2

**Describe the bug**
- OS and Version: Windows 11 21H2
- VS Code Version: 1.66.1
- C/C++ Extension Version: 1.9.7
- Other extensions you installed (and if the issue persists after disabling them): 
C/C++ Extension Pack
C/C++ Themes
C++ Intellisense
CMake
CMake Tools
Doxygen Documentation
GitHub Pull Requests
Hex Editor
Live Share
LiveShare Audio
Makefile Tools

- A clear and concise description of what the bug is.

**To Reproduce**
*Please include a code sample and `launch.json` configuration.*
Install a recent version of MSYS2, x86_64 MinGW, and do a proper update (pacman -Syuu)
Try to debug anything. 

**Additional context**
Launch.json:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "logging": { "engineLogging": true, "trace": true, "traceResponse": true },
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "program": "C:\\Users\\kd5ea\\Documents\\YAESU\\Controller\\FT891.exe",
            "args": [],
            "stopAtEntry": false,
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "E:\\msys64\\mingw64\\bin\\gdb.exe",   
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
            
        }
    ]
}

Please note this issue is irrelevant to path formats in lauch.json. 

Relevant Logging output:

Add any other context about the problem here including log or error messages in your Debug Console or Output windows.
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
<--   C (threads-10): {"command":"threads","type":"request","seq":10}
--> R (threads-10): {"type":"response","request_seq":10,"success":true,"command":"threads","body":{"threads":[]},"seq":276}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1101) <-1012-catch-throw\r\n"},"seq":278}
1: (1101) <-1012-catch-throw
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1118) ->1012^done,bkpt={number=\"2\",type=\"catchpoint\",disp=\"keep\",enabled=\"y\",what=\"exception throw\",catch-type=\"throw\",thread-groups=[\"i1\"],times=\"0\"}\r\n"},"seq":280}
1: (1118) ->1012^done,bkpt={number="2",type="catchpoint",disp="keep",enabled="y",what="exception throw",catch-type="throw",thread-groups=["i1"],times="0"}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1118) ->(gdb)\r\n"},"seq":282}
1: (1118) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1118) 1012: elapsed time 16\r\n"},"seq":284}
1: (1118) 1012: elapsed time 16
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1118) ->&\"\\n\"\r\n"},"seq":286}
1: (1118) ->&"\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1118) ->^done\r\n"},"seq":288}
1: (1118) ->^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1118) ->(gdb)\r\n"},"seq":290}
1: (1118) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1123) <-1013-exec-run\r\n"},"seq":292}
1: (1123) <-1013-exec-run
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1130) ->=thread-group-started,id=\"i1\",pid=\"14120\"\r\n"},"seq":294}
1: (1130) ->=thread-group-started,id="i1",pid="14120"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1131) ->=thread-created,id=\"1\",group-id=\"i1\"\r\n"},"seq":296}
1: (1131) ->=thread-created,id="1",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1132) ->=thread-created,id=\"2\",group-id=\"i1\"\r\n"},"seq":298}
1: (1132) ->=thread-created,id="2",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1132) ->~\"[New Thread 14120.0x49fc]\\n\"\r\n"},"seq":300}
1: (1132) ->~"[New Thread 14120.0x49fc]\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1132) ->=thread-created,id=\"3\",group-id=\"i1\"\r\n"},"seq":302}
1: (1132) ->=thread-created,id="3",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1133) ->~\"[New Thread 14120.0x59a4]\\n\"\r\n"},"seq":304}
1: (1133) ->~"[New Thread 14120.0x59a4]\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1133) ->=thread-created,id=\"4\",group-id=\"i1\"\r\n"},"seq":306}
1: (1133) ->=thread-created,id="4",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1133) ->~\"[New Thread 14120.0x944]\\n\"\r\n"},"seq":308}
1: (1133) ->~"[New Thread 14120.0x944]\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1134) <-1014-thread-info 1\r\n"},"seq":310}
1: (1134) <-1014-thread-info 1
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1136) ->~\"[Thread 14120.0x944 exited with code 3221225785]\\n\"\r\n"},"seq":312}
1: (1136) ->~"[Thread 14120.0x944 exited with code 3221225785]\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1136) ->=thread-exited,id=\"4\",group-id=\"i1\"\r\n"},"seq":314}
1: (1136) ->=thread-exited,id="4",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1136) ->~\"[Thread 14120.0x59a4 exited with code 3221225785]\\n\"\r\n"},"seq":316}
1: (1136) ->~"[Thread 14120.0x59a4 exited with code 3221225785]\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1136) ->=thread-exited,id=\"3\",group-id=\"i1\"\r\n"},"seq":318}
1: (1136) ->=thread-exited,id="3",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1136) <-1015-thread-info 2\r\n"},"seq":320}
1: (1136) <-1015-thread-info 2
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1137) ->~\"[Thread 14120.0x4d30 exited with code 3221225785]\\n\"\r\n"},"seq":322}
1: (1137) ->~"[Thread 14120.0x4d30 exited with code 3221225785]\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1137) ->=thread-exited,id=\"1\",group-id=\"i1\"\r\n"},"seq":324}
1: (1137) ->=thread-exited,id="1",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[New Thread 14120.0x49fc]\n"},"seq":326}
[New Thread 14120.0x49fc]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1137) ->=thread-exited,id=\"2\",group-id=\"i1\"\r\n"},"seq":328}
1: (1137) ->=thread-exited,id="2",group-id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1137) ->=thread-group-exited,id=\"i1\"\r\n"},"seq":330}
1: (1137) ->=thread-group-exited,id="i1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) ->1013^error,msg=\"During startup program exited with code 0xc0000139.\"\r\n"},"seq":332}
1: (1138) ->1013^error,msg="During startup program exited with code 0xc0000139."
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) ->(gdb)\r\n"},"seq":334}
1: (1138) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) ->&\"\\n\"\r\n"},"seq":336}
1: (1138) ->&"\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) ->^done\r\n"},"seq":338}
1: (1138) ->^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) <-1016-thread-info 3\r\n"},"seq":340}
1: (1138) <-1016-thread-info 3
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) ->(gdb)\r\n"},"seq":342}
1: (1138) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) ->1014^done,threads=[]\r\n"},"seq":344}
1: (1138) ->1014^done,threads=[]
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[New Thread 14120.0x59a4]\n"},"seq":345}
[New Thread 14120.0x59a4]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) ->(gdb)\r\n"},"seq":348}
1: (1138) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) <-1017-thread-info 4\r\n"},"seq":350}
1: (1138) <-1017-thread-info 4
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) ->&\"\\n\"\r\n"},"seq":352}
1: (1138) ->&"\n"
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[New Thread 14120.0x944]\n"},"seq":354}
[New Thread 14120.0x944]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1138) ->^done\r\n"},"seq":355}
1: (1138) ->^done
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[Thread 14120.0x944 exited with code 3221225785]\n"},"seq":358}
[Thread 14120.0x944 exited with code 3221225785]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1139) ->(gdb)\r\n"},"seq":360}
1: (1139) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1139) ->1015^done,threads=[]\r\n"},"seq":362}
1: (1139) ->1015^done,threads=[]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1139) ->(gdb)\r\n"},"seq":364}
1: (1139) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1139) ->&\"\\n\"\r\n"},"seq":366}
1: (1139) ->&"\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1139) ->^done\r\n"},"seq":368}
1: (1139) ->^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1139) ->(gdb)\r\n"},"seq":370}
1: (1139) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[Thread 14120.0x59a4 exited with code 3221225785]\n"},"seq":372}
[Thread 14120.0x59a4 exited with code 3221225785]
--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[Thread 14120.0x4d30 exited with code 3221225785]\n"},"seq":374}
[Thread 14120.0x4d30 exited with code 3221225785]
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1140) 1013: elapsed time 16\r\n"},"seq":376}
1: (1140) 1013: elapsed time 16
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1141) 1014: elapsed time 7\r\n"},"seq":378}
1: (1141) 1014: elapsed time 7
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1142) Send Event AD7MessageEvent\r\n"},"seq":380}
1: (1142) Send Event AD7MessageEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1143) 1015: elapsed time 6\r\n"},"seq":382}
1: (1143) 1015: elapsed time 6
--> E (output): {"type":"event","event":"output","body":{"category":"stderr","output":"ERROR: Unable to start debugging. Unexpected GDB output from command \"-exec-run\". During startup program exited with code 0xc0000139.\r\n"},"seq":384}
ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run". During startup program exited with code 0xc0000139.
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1147) Send Event AD7ProgramDestroyEvent\r\n"},"seq":386}
1: (1147) Send Event AD7ProgramDestroyEvent
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"The program 'C:\\Users\\kd5ea\\Documents\\YAESU\\Controller\\FT891.exe' has exited with code 0 (0x00000000).\r\n\r\n"},"seq":388}
The program 'C:\Users\kd5ea\Documents\YAESU\Controller\FT891.exe' has exited with code 0 (0x00000000).
--> E (exited): {"type":"event","event":"exited","body":{"exitCode":0},"seq":390}
--> E (terminated): {"type":"event","event":"terminated","body":{},"seq":392}
--> E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"17.1.20308.3","VS.Diagnostics.Debugger.HostVersion":"17.1.20308.3","VS.Diagnostics.Debugger.AdapterId":"cppdbg","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":0}},"seq":394}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (1155) <--gdb-exit\r\n"},"seq":396}
1: (1155) <--gdb-exit
<--   C (disconnect-11): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":11}
--> R (disconnect-11): {"type":"response","request_seq":11,"success":true,"command":"disconnect","body":{},"seq":399}

**Comment by kd-boss** [comment]
This is the output of gdb for the -exec-run 
(gdb)
-exec-run
=thread-group-started,id="i1",pid="21264"
=thread-created,id="1",group-id="i1"
=thread-created,id="2",group-id="i1"
~"[New Thread 21264.0x663c]\n"
=thread-created,id="3",group-id="i1"
~"[New Thread 21264.0x496c]\n"
=thread-created,id="4",group-id="i1"
~"[New Thread 21264.0x5384]\n"
=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x00007ff7a75d180b",func="main(int, char**)",file="C:/Users/kd5ea/Documents/YAESU/Controller/FT891.cxx",fullname="/c/Users/kd5ea/Documents/YAESU/Controller/FT891.cxx",line="3998",thread-groups=["i1"],times="0",original-location="main"}
=breakpoint-modified,bkpt={number="2",type="catchpoint",disp="keep",enabled="y",what="exception throw",catch-type="throw",thread-groups=["i1"],times="0"}
=library-loaded,id="/c/WINDOWS/SYSTEM32/ntdll.dll",target-name="/c/WINDOWS/SYSTEM32/ntdll.dll",host-name="/c/WINDOWS/SYSTEM32/ntdll.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91f561000",to="0x00007ff91f768538"}]
=library-loaded,id="/c/WINDOWS/System32/KERNEL32.DLL",target-name="/c/WINDOWS/System32/KERNEL32.DLL",host-name="/c/WINDOWS/System32/KERNEL32.DLL",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91da51000",to="0x00007ff91db0c334"}]
=library-loaded,id="/c/WINDOWS/System32/KERNELBASE.dll",target-name="/c/WINDOWS/System32/KERNELBASE.dll",host-name="/c/WINDOWS/System32/KERNELBASE.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91cd21000",to="0x00007ff91d09389c"}]
=library-loaded,id="/c/WINDOWS/System32/msvcrt.dll",target-name="/c/WINDOWS/System32/msvcrt.dll",host-name="/c/WINDOWS/System32/msvcrt.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91db11000",to="0x00007ff91dbb24b4"}]
=library-loaded,id="/c/WINDOWS/System32/USER32.dll",target-name="/c/WINDOWS/System32/USER32.dll",host-name="/c/WINDOWS/System32/USER32.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91e901000",to="0x00007ff91eaab430"}]
=library-loaded,id="/c/WINDOWS/System32/win32u.dll",target-name="/c/WINDOWS/System32/win32u.dll",host-name="/c/WINDOWS/System32/win32u.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91ccf1000",to="0x00007ff91cd15024"}]
=library-loaded,id="/mingw64/bin/libfltk.dll",target-name="/mingw64/bin/libfltk.dll",host-name="/mingw64/bin/libfltk.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff8f6991000",to="0x00007ff8f6ab36b8"}]
=library-loaded,id="/mingw64/bin/libwinpthread-1.dll",target-name="/mingw64/bin/libwinpthread-1.dll",host-name="/mingw64/bin/libwinpthread-1.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff917f11000",to="0x00007ff917f25060"}]
=library-loaded,id="/mingw64/bin/libgcc_s_seh-1.dll",target-name="/mingw64/bin/libgcc_s_seh-1.dll",host-name="/mingw64/bin/libgcc_s_seh-1.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff917ef1000",to="0x00007ff917f0b060"}]
=library-loaded,id="/c/WINDOWS/System32/GDI32.dll",target-name="/c/WINDOWS/System32/GDI32.dll",host-name="/c/WINDOWS/System32/GDI32.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91eab1000",to="0x00007ff91ead849c"}]
=library-loaded,id="/c/WINDOWS/System32/ADVAPI32.dll",target-name="/c/WINDOWS/System32/ADVAPI32.dll",host-name="/c/WINDOWS/System32/ADVAPI32.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91d421000",to="0x00007ff91d4cd934"}]
=library-loaded,id="/c/WINDOWS/System32/gdi32full.dll",target-name="/c/WINDOWS/System32/gdi32full.dll",host-name="/c/WINDOWS/System32/gdi32full.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91d0a1000",to="0x00007ff91d1b14ec"}]
=library-loaded,id="/c/WINDOWS/System32/sechost.dll",target-name="/c/WINDOWS/System32/sechost.dll",host-name="/c/WINDOWS/System32/sechost.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91f261000",to="0x00007ff91f2fd4b4"}]
=library-loaded,id="/mingw64/bin/libstdc++-6.dll",target-name="/mingw64/bin/libstdc++-6.dll",host-name="/mingw64/bin/libstdc++-6.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff8f61b1000",to="0x00007ff8f6394f00"}]
=library-loaded,id="/c/WINDOWS/System32/msvcp_win.dll",target-name="/c/WINDOWS/System32/msvcp_win.dll",host-name="/c/WINDOWS/System32/msvcp_win.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91d241000",to="0x00007ff91d2dc804"}]
=library-loaded,id="/c/WINDOWS/System32/ucrtbase.dll",target-name="/c/WINDOWS/System32/ucrtbase.dll",host-name="/c/WINDOWS/System32/ucrtbase.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91d2e1000",to="0x00007ff91d3f0b20"}]
=library-loaded,id="/c/WINDOWS/System32/RPCRT4.dll",target-name="/c/WINDOWS/System32/RPCRT4.dll",host-name="/c/WINDOWS/System32/RPCRT4.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91d931000",to="0x00007ff91da4f7c8"}]
=library-loaded,id="/c/WINDOWS/System32/comdlg32.dll",target-name="/c/WINDOWS/System32/comdlg32.dll",host-name="/c/WINDOWS/System32/comdlg32.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91e7a1000",to="0x00007ff91e88b30c"}]
=library-loaded,id="/c/WINDOWS/System32/combase.dll",target-name="/c/WINDOWS/System32/combase.dll",host-name="/c/WINDOWS/System32/combase.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91d4d1000",to="0x00007ff91d8479a8"}]
=library-loaded,id="/c/WINDOWS/SYSTEM32/WSOCK32.dll",target-name="/c/WINDOWS/SYSTEM32/WSOCK32.dll",host-name="/c/WINDOWS/SYSTEM32/WSOCK32.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff906cb1000",to="0x00007ff906cb8028"}]
=library-loaded,id="/c/WINDOWS/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22000.1_none_271a8fad6a2d1b1e/COMCTL32.dll",target-name="/c/WINDOWS/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22000.1_none_271a8fad6a2d1b1e/COMCTL32.dll",host-name="/c/WINDOWS/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22000.1_none_271a8fad6a2d1b1e/COMCTL32.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff90a5f1000",to="0x00007ff90a6a12d8"}]
=library-loaded,id="/c/WINDOWS/System32/WS2_32.dll",target-name="/c/WINDOWS/System32/WS2_32.dll",host-name="/c/WINDOWS/System32/WS2_32.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91f191000",to="0x00007ff91f1fe158"}]
=library-loaded,id="/c/WINDOWS/System32/shcore.dll",target-name="/c/WINDOWS/System32/shcore.dll",host-name="/c/WINDOWS/System32/shcore.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91f321000",to="0x00007ff91f4095f0"}]
=library-loaded,id="/c/WINDOWS/System32/SHLWAPI.dll",target-name="/c/WINDOWS/System32/SHLWAPI.dll",host-name="/c/WINDOWS/System32/SHLWAPI.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91e891000",to="0x00007ff91e8ec76c"}]
=library-loaded,id="/c/WINDOWS/System32/SHELL32.dll",target-name="/c/WINDOWS/System32/SHELL32.dll",host-name="/c/WINDOWS/System32/SHELL32.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91dfb1000",to="0x00007ff91e75e550"}]
=library-loaded,id="/c/WINDOWS/System32/ole32.dll",target-name="/c/WINDOWS/System32/ole32.dll",host-name="/c/WINDOWS/System32/ole32.dll",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91dcf1000",to="0x00007ff91de8965c"}]
^running
*running,thread-id="all"
(gdb)
=library-loaded,id="/c/WINDOWS/System32/IMM32.DLL",target-name="/c/WINDOWS/System32/IMM32.DLL",host-name="/c/WINDOWS/System32/IMM32.DLL",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ff91e761000",to="0x00007ff91e790164"}]
=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x00007ff7a75d180b",func="main(int, char**)",file="C:/Users/kd5ea/Documents/YAESU/Controller/FT891.cxx",fullname="/c/Users/kd5ea/Documents/YAESU/Controller/FT891.cxx",line="3998",thread-groups=["i1"],times="1",original-location="main"}
~"\n"
~"Thread 1 hit Breakpoint 1, main (argc=1, argv=0x223cb821ee0) at C:/Users/kd5ea/Documents/YAESU/Controller/FT891.cxx:3998\n"
~"3998\t\t\tstd::string port ;\n"
*stopped,reason="breakpoint-hit",disp="keep",bkptno="1",frame={addr="0x00007ff7a75d180b",func="main",args=[{name="argc",value="1"},{name="argv",value="0x223cb821ee0"}],file="C:/Users/kd5ea/Documents/YAESU/Controller/FT891.cxx",fullname="/c/Users/kd5ea/Documents/YAESU/Controller/FT891.cxx",line="3998",arch="i386:x86-64"},thread-id="1",stopped-threads="all"
(gdb)

**Comment by kd-boss** [comment]
![image](https://user-images.githubusercontent.com/6182638/162840697-2180c62c-8e7a-4820-ba7e-4531a0a2d096.png)

**Comment by kd-boss** [comment]
odd, so how would I tell VS Code to copy the required runtime libraries to run the executable?

I'm linking with boost, fltk, and fmt. It compiles fine. Debugging not so much, and if it's because it can't find a library, it's because the library isn't in the output directory, which needs to be pulled from my mingw64 installation directory?

Also, is there any way to get this environment to multithread the cpp file compilation, similar to a make -j call?

**Comment by IKOBH** [comment]
Hi, I get the exact same error. Couldn't fix it.

**Comment by kd-boss** [comment]
@IKOBH  copy any needed dlls that you link to into the output folder of your project (right with the exe). It should launch fine after. This isn't a path variable issue for Windows, and setting your PATH environment variables likely won't help. Just make sure the executable you've built is capable of being run in a regular command shell.

**Comment by parsley72** [comment]
Is there anywhere I can get proper logging from gdb? Because this is absolutely useless.
<img width="278" alt="image" src="https://github.com/microsoft/vscode-cpptools/assets/1666601/48dfb49e-40d6-4467-89fd-90d2744ab84d">

**Comment by parsley72** [comment]
Found this: https://stackoverflow.com/a/73496411/264822
> You can open logs to see what happened:
```
"logging": {
    "moduleLoad": true,
    "engineLogging": true,
    "trace": true
},
```
I now have lots of logging.
