### ISSUE TITLE
C_Cpp.codeAnalysis.exclude fails to exclude a folder named starting with a digit

### ISSUE THREAD

**Issue by qiangmgit** [microsoft/vscode-cpptools#9166]
Bug type: General

**Describe the bug**
- OS and Version: Windows10
- VS Code Version: 1.66.1
- C/C++ Extension Version:v1.9.7
- Other extensions you installed (and if the issue persists after disabling them):None
- A clear and concise description of what the bug is.
If there is a folder named 3rdparty in the workspace, and setting C_Cpp.codeAnalysis.exclude as
    "C_Cpp.codeAnalysis.exclude": {
        "3rdparty/**": true,
this folder will still be included in the code analysis.
However, this will work
    "C_Cpp.codeAnalysis.exclude": {
        "**3rdparty/**": true,

This can be reproduced easily. It seems the glob pattern doesn't handle folder named starting with a digit well.

**Comment by qiangmgit** [comment]
Correction: this will work
However, this will work
"C_Cpp.codeAnalysis.exclude": {
"\*\*3rdparty/": true,

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. Same issue repros with C_Cpp.files.exclude. It should be fixed with our next pre-release version.

**Comment by qiangmgit** [comment]
Thanks

**Comment by sean-mcmanus** [comment]
This should be fixed with 1.10.2 (pre-release).
