### ISSUE TITLE
Clarify FOSS Access Denied Message

### ISSUE THREAD

**Issue by DeathByNukes** [microsoft/vscode-cpptools#9168]
As is mentioned in other closed issues, this extension's debugger refuses to operate when installed in VSCode forks such as VSCodium.

Apparently, this message in the debug console is supposed to communicate this fact to the user:

```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code
with Visual Studio Code, Visual Studio or Visual Studio for Mac
software to help you develop and test your applications.
-------------------------------------------------------------------
```

If my understanding is correct, please be advised that this doesn't actually inform the user that the extension is currently refusing to operate, and nothing else does either. (The debugger simply puts the above message into the console, doesn't launch the program to be debugged, and stays open endlessly.) [It is not obvious](https://youtu.be/kr4sk6rZd7o?t=3) that "Visual Studio Code" excludes all forks of Visual Studio Code, so this could lead novice users to waste large amounts of time troubleshooting, like it did in my case.

Please have the error message state that an error has occurred. Thank you.

**Comment by WardenGnaw** [comment]
I could not reproduce this with: 
- [VSCodium v1.66.1](https://github.com/VSCodium/vscodium/releases/tag/1.66.1)
- [cpptools v1.9.7](https://github.com/microsoft/vscode-cpptools/releases/download/v1.9.7/cpptools-win64.vsix)

In the debug console, you should see:
> Unable to start debugging. .NET Debugging is supported only in Microsoft versions of VS Code. See [https://aka.ms/VSCode-DotNet-DbgLicense]() for more information.

![image](https://user-images.githubusercontent.com/3953714/162830904-f555cb71-1d82-4641-a6bf-99cc5389f63e.png)
