### ISSUE TITLE
c_cpp_properties browse path adds implicit system paths

### ISSUE THREAD

**Issue by jesse-tussock** [microsoft/vscode-cpptools#917]
I'm working on an embedded arm system on Windows, so I don't want any Windows headers to be used. Configuration is below:

```
{
    "configurations": [        
        {
            "name": "Win32",
            "includePath": [
                "${workspaceRoot}"
            ],
            "defines": [
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/ti/simplelink_msp432_sdk_1_40_01_00/source",                    
                    "C:/ti/simplelink_msp432_sdk_1_40_01_00/source/third_party/CMSIS/Include",
                    "C:/ti/simplelink_msp432_sdk_1_40_01_00/kernel/tirtos/packages/ti/sysbios/posix",
                    "C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.3.LTS/include",
                    "C:/ti/simplelink_msp432_sdk_1_40_01_00/kernel/tirtos/packages",
                    "C:/ti/xdctools_3_50_02_20_core/packages",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 2
}
```

In a file I have `#include <ti/drivers/GPIO.h>`,  if I use 'Go to definition' it opens `C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063\shared\gpio.h` instead of the file that would be found through my browse path. I obviously don't have that path listed, so it is being included from elsewhere.

Do I need to change another file? How can I disable these implicit paths?

**Comment by bobbrow** [comment]
What I suspect has happened is that the Windows headers were indexed before you changed the browse.path.  We have a backlog item to clean up the database when you remove paths from the list and another one to add a command to nuke the DB and start over, but neither are complete yet.  A simple workaround for this is to change the name of the database to force it to be re-created.

Try setting `"databaseFilename": ".browse2.VC.db"`

**Comment by jesse-tussock** [comment]
That sorted it, thanks!
