### ISSUE TITLE
How to include all files of a folder, for which index is defined？

### ISSUE THREAD

**Issue by maykolo** [microsoft/vscode-cpptools#9176]
Type: Feature Request

Hello, I would like to ask, I need to check a lot of source code, after using this plugin, I can't generate the dependencies of each function, and I can't switch to the function definition and macro definition, so how can I get such information? One of the ways I look at using plugins is that the include folder path is required, but there are many includepaths in this plugin that I don't know which block to add to? Looking forward to your reply.

**Comment by sean-mcmanus** [comment]
You can use the "includePath" property in c_cpp_properties.json or the `"browse": { "path": }` property (if you want to just add global symbols without adding to the actual include path used for finding headers). There are also equivalent C_Cp.default.includePath, etc. settings.

**Comment by maykolo** [comment]
> You can use the "includePath" property in c_cpp_properties.json or the `"browse": { "path": }` property (if you want to just add global symbols without adding to the actual include path used for finding headers). There are also equivalent C_Cp.default.includePath, etc. settings.

Hello, then where should I create this c_cpp_properties.json file, I open this via vscode shortcut key (command 'C_Cpp.configurationEditJson', not found), I don't know where I should put this json file Where is it created, and I would like to ask you a question, how can the usage of this plugin be viewed more completely, rather than a simple overview? Looking forward to your reply, thank you.

**Comment by sean-mcmanus** [comment]
Sorry, for the late reply (busy with other work) -- the C/C+: Edit Configuration commands should normally work to create the c_cpp_properties.json. Yoiu may be hitting some other extension activation bug. It is created at ${workspaceFolder}/.vscode.

I'm not sure what you mean by "how can the usage of this plugin be viewed more completely" -- you can set C_Cpp.loggingLevel to "Debug" to get more diagnostics info or run the C/C++: Log Diagnostics command.
