### ISSUE TITLE
>10 GB RAM usage when parsing large project

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#9181]
Hello everyone, Good day to you,

The RAM usage peaks when cpptools is enabled in vscode. 

Below is the usage when extension is not enabled:
![image](https://user-images.githubusercontent.com/99165030/162904814-d2f6aea9-96c0-475c-a93c-85c474b2a11f.png)

2GB after few minutes:
![image](https://user-images.githubusercontent.com/99165030/162906788-6e2db7a4-554f-4e76-9fcb-0bb51e70327e.png)

6GB now, and it keeps on eating (my precious) RAM
![image](https://user-images.githubusercontent.com/99165030/162907008-aa89ad0e-9a7d-4bb3-a636-b8738b128ae0.png)

And 10GB!!!
![image](https://user-images.githubusercontent.com/99165030/162907214-d717b958-083d-4988-bdbf-fd363241a893.png)

vscode details:

Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042

the cpp tools version is v1.9.7:
![image](https://user-images.githubusercontent.com/99165030/162907593-7b9957f6-7bf9-4572-98cc-9bfadfd52da4.png)

I tried limiting the C_Cpp: Max Memory and other similar settings, which didn't make any change in the behaviour.
![image](https://user-images.githubusercontent.com/99165030/162908485-61a97048-e50a-47a2-9c9a-4233f766d227.png)

Any help appreciated!!

_Originally posted by @kunchuf in https://github.com/microsoft/vscode-cpptools/discussions/9171_

**Comment by michelleangela** [comment]
@kunchuf

Could you also provide the logs from running `C/C++: Log Diagnostics` (feel free sanitize any paths before posting)? And then try the setting `"C_Cpp.intelliSenseEngine" :"Tag Parser"` and see if the issue still reproduces.

**Comment by kunchuf** [comment]
> @kunchuf
> 
> Could you also provide the logs from running `C/C++: Log Diagnostics` (feel free sanitize any paths before posting)? 
>
>
-------- Diagnostics - 4/14/2022, 4:19:10 PM
Version: 1.9.7
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.


>
>
> And then try the setting `"C_Cpp.intelliSenseEngine" :"Tag Parser"` and see if the issue still reproduces.
>
Issue persists after setting  to Tag Parser
>
> Does your project use any large public third party libraries that we can try to reproduce the issue on our end? Is your project in a single or multiple workspace?
>
>
Single workspace. And unfortunately, no shareable third party libraries. But its not all bad news. I found the file where this issue occurs. Now I can reproduce the issue with a workspace with that single file. The language server log always stopped at that file which unfortunately cannot be shared. But I can explain its contents. It's a header file (.h) with several defines, nested structures with bit fields, macros, also conditional preprocessor statements.
I will try to change the contents of it so that I can get a problematic file which can be shared

**Comment by michelleangela** [comment]
> The language server log always stopped at that file which unfortunately cannot be shared. But I can explain its contents. It's a header file (.h) with several defines, nested structures with bit fields, macros, also conditional preprocessor statements.
I will try to change the contents of it so that I can get a problematic file which can be shared

Sounds like our tag parser leaks memory when it fails to parse that one file. If you could isolate which part of the code and create a simplified version of it, that would be helpful so we can reproduce and debug it on our side.

**Comment by kunchuf** [comment]
@michelleangela 
There you go - issue reproduced on a shareable file.
[tmp.txt](https://github.com/microsoft/vscode-cpptools/files/8495153/tmp.txt)

It is a c file, so rename with .c extension before using.

**Comment by Ursescu** [comment]
Hi all, this seems to be related to the issue that I have (the file structure looks very very similar to mine) #8898

Is this Embedded Code related (it seems like it exactly the same file but you changed the names) ????

**Comment by kunchuf** [comment]
@Ursescu
Yes, its embedded code. And yes it looks very similar to your code, though its not the same code.

**Comment by Ursescu** [comment]
Hey @michelleangela, any news regarding this issue?

**Comment by michelleangela** [comment]
@Ursescu 
Thank you for checking-in. I've sent the issue to team that manages the code base that we use for parsing. It is under their radar but they haven't had a chance to look into it as they have limited resources.

**Comment by bobbrow** [comment]
We will track this with #8898
