### ISSUE TITLE
Ability to support or ignore non-standard __declspec() attributes e.g. for embedded CodeWarrior projects

### ISSUE THREAD

**Issue by jarmisteadgal** [microsoft/vscode-cpptools#9182]
### Feature Request

I am using NXP's CodeWarrior for PowerPC to do embedded C/C++ development. The IDE's editor is very primitive compared to VS Code since it was basically EOL since the mid 2010s.

The code contains lines such as the following:

__declspec(section ".sdata") unsigned char *myarray[my_size];

This generates a Problem message of:

unknown attribute "section" C/C++ (1097)

__declspec() is used by CodeWarrior to set certain attributes, in this case, the memory section where certain data should be stored. This is used during the linking step to ensure that certain variables and other data are stored optimally based on the processor and target board architecture.

I'd really like a way to either support or ignore (via configuration file) these attributes, rather than always having a Problem being logged when in fact (to CodeWarrior's compiler at least!) this is perfectly legitimate.

When working in the embedded world there are many compilers (particularly legacy ones) that are not going to do the things that VS Code is expecting when parsing code, and so that's going to have an effect on many non-standard vendor-specific things such as __declspec() and #pragma usage.

**Comment by Colengms** [comment]
Hi @jarmisteadgal . I believe you may already be able to selectively disable errors by leveraging the `__INTELLISENSE__` macro like so:

```
#ifdef __INTELLISENSE__
    #pragma diag_suppress 1097
#endif
```

We also have a similar (but more general) feature request here: https://github.com/microsoft/vscode-cpptools/issues/2345

Is that sufficient to address the issue, or would you like to keep this feature request specifically regarding `__declspec`?

**Comment by jarmisteadgal** [comment]
I am looking for a solution that (ideally) doesn't involve changes to my source code, but which could be part of my VS Code workspace configuration settings.

Using

`#ifdef __INTELLISENSE__
    #pragma diag_suppress 1097
#endif`

is a reasonable workaround, Not great, but "done once" somewhere in every CodeWarrior project that I have. Figuring out the best place to put this might be a bit of a nuisance. Having a direct setting in the C/C++ configuration options would be *MUCH* nicer!!!

Is there a way to selectively disable certain diagnostics e.g. around the block(s) of affected code, but then to re-enable them everywhere else, i.e. to identify  "real" issues of the same type?

**Comment by Colengms** [comment]
Hi @jarmisteadgal .

> I am looking for a solution that (ideally) doesn't involve changes to my source code

You might consider putting that in a separate file, and configuring the C/C++ extension to 'force include' that file before all others, using the `-include` compiler argument in `c_cpp_properties.json`.  That way it would not impact your other sources or your build in any way.

> Is there a way to selectively disable certain diagnostics e.g. around the block(s) of affected code, but then to re-enable them everywhere else, i.e. to identify "real" issues of the same type?

If modifying the code in question would not be a problem, there is also a `diag_default` pragma.  i.e.:

```
#pragma diag_suppress 1097
  __declspec(section ".sdata") unsigned char *myarray[my_size];
#pragma diag_default 1097
```

I believe pragmas should be ignored if the attribute is unrecognized, so it may not be necessary to check `__INTELLISENSE__` and perhaps may not cause an error when actually compiled.

**Comment by jarmisteadgal** [comment]
This is great information. Thanks !!!

Are these pragmas documented somewhere "official" ?  I found some references when Google searching but nothing specific to "official" information pertaining to VS Code and/or the C/C++ extension.

I am wary that different compilers may treat unrecognized #pragma attributes differently, and will probably stick to using #ifdef ... #endif blocks just to be sure.

**Comment by Colengms** [comment]
> Are these pragmas documented somewhere "official" ? 

Unfortunately, I'm not aware of where/if these are documented, other than in issue threads in this repo.  The C/C++ extension supports these as a result of IntelliSense features being based on a C/C++ compiler front end developed by the [Edison Design Group](https://www.edg.net/).

**Comment by jarmisteadgal** [comment]
Interesting! These definitely deserve proper/better documentation, otherwise how on earth can people find them? Googling or searching these issues in GitHub really isn't an acceptable alternative.

PS: Your URL link for Edison Design Group is incorrect. It should be https://www.edg.com/
