### ISSUE TITLE
False problem report for C preprocessor macro

### ISSUE THREAD

**Issue by nordic-krch** [microsoft/vscode-cpptools#9187]
Bug type: Language Service

**Describe the bug**
In zephyr project https://github.com/zephyrproject-rtos/zephyr we are using a macro which is able to paste one of two code snippets based on the flag argument. It is a preprocessor trick derived from Linux `IS_ENABLED` macro. Macro has following syntax:
`COND_CODE_0(flag, (if_flag_code), (else_code))`, e.g. 
```
COND_CODE_0(0, (printf("000000");), (printf("1111111");))
/*Resolves to printf("0000000"); */

COND_CODE_0(1, (printf("000000");), (printf("1111111");))
/*Resolves to printf("1111111"); */
```
The problem with VSCode is analyzes the path that is being excluded by this macro and report warning for that. We have a use case where flag is a macro that calculates number of input arguments and calls different macros with different number of arguments. Something like:
```
#define MACRO_1ARG(x) printf("%d\n", x)
#define MACRO_2ARGS(x, y) printf("%d %d\n", x, y)
#define COUNT_ARGS_LESS1(...) /* Macro returns number of input arguments - 1 */
#define TEST(...) COND_CODE_0(COUNT_ARGS_LESS1(__VA_ARGS__), (MACRO_1ARG(__VA_ARGS__), MACRO_2ARGS(__VA_ARGS__))

void foo(void) {
    TEST(100);
    TEST(100, 100);
}
```
In case of `TEST(100)` arguments counting passed to `COND_CODE_0` results in cutting second path (`MACRO_2ARGS`). Code compiles fine, there is no misuse of the macro but VSCode notifies about the issue.

- OS and Version: Windows 10.0.19044
- VS Code Version: 1.66.2
- C/C++ Extension Version: 1.1.0

**Steps to reproduce**
Here is a code snippet which triggers this error:
```
#define _Z_COND_CODE_0(_flag, _if_0_code, _else_code) \
	___COND_CODE(__ZZZZ##_flag, _if_0_code, _else_code)
#define __ZZZZ0 _YYYY,

#define ___COND_CODE(one_or_two_args, _if_code, _else_code) \
	___GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)

#define ___GET_ARG2_DEBRACKET(ignore_this, val, ...) ___DEBRACKET val

#define ___DEBRACKET(...) __VA_ARGS__

#define TEST_MACRO_2(x, y) printk("%d %d", x, y)
/* Flag is fixed to 0, so second option is never compiled and shouldn't be evaluated by Intellisense */
#define TEST_MACRO3(...) _Z_COND_CODE_0(0, (printk("ss")), (TEST_MACRO_2(__VA_ARGS__)))
void test_macro_func(int x)
{
       /* Macro called with one parameter */
	TEST_MACRO3(x);
}
```
error reported:
![image](https://user-images.githubusercontent.com/16899589/163384760-39dab8cd-b0a7-4c0f-af3d-8aa3e108609e.png)

**Expected behavior**
Intellisense should figure out that given path is stripped by the preprocessor and do not report the error.

**Comment by sean-mcmanus** [comment]
The sample code doesn't compile for me with the latest gcc, clang, or cl.exe -- which compiler and compiler args are you using to compile that?
