### ISSUE TITLE
vscode becomes not responding when debugging recursive function.

### ISSUE THREAD

**Issue by renewboy** [microsoft/vscode-cpptools#919]
works well when using gdb directly.

**Comment by pieandcakes** [comment]
@zouyxdut can you provide a reproducible example and more information on what you mean by "irresponsible" ?

**Comment by renewboy** [comment]
@pieandcakes Sorry for the mistake. What I mean is not responding.

**Comment by pieandcakes** [comment]
@zouyxdut How deep in the stack are you going during recursion that it becomes unresponsive? Is it a tight loop recursion?

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
