### ISSUE TITLE
Frequent problems with the Outline feature

### ISSUE THREAD

**Issue by maykolo** [microsoft/vscode-cpptools#9194]
Bug type: Language Service

**Describe the bug**
- OS and Version:window10
- VS Code Version: v1.66.2
- C/C++ Extension Version: v1.9.7
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: Ubuntu18.04
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
When writing C language, or viewing a large C language project, when using the "Outline" function, "Cannot find symbol in document" will often appear.workspace a single project.

**Screenshots**

![image](https://user-images.githubusercontent.com/42791449/163669610-a5aec8d4-b6bb-4b09-b8c6-12d3be628a53.png)

**Comment by michelleangela** [comment]
@maykolo 
Could you enable the language server logging and provide the logs of the server? The logs may show clues about the issue. Could you also run the command `C/C++: Log Diagnostics` and copy those logs here as well?

**Comment by sean-mcmanus** [comment]
In particular, we'd be interested in any Tag Parser error messages and if it repros with particular a particular code sample or not, which would indicate a parsing bug. Or there could be a problem with the database if it repros with all files.
