### ISSUE TITLE
"go to definition" open wrong source code

### ISSUE THREAD

**Issue by zzhixin** [microsoft/vscode-cpptools#9196]
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version: 1.66
- C/C++ Extension Version: v1.9.7
- Other extensions you installed (and if the issue persists after disabling them): C/C++ extension pack

press F12 to go to definition lead wrong source code

**Steps to reproduce**

1. Cmake install OpenCV3.2 and libeigen3-dev 3.3.4
2. Create an cmake project to link opencv and **include eigen3** in CmakeList.txt
3. Create code sample below.
4. Move cursor on the function `compute` in the last line, press `F12`
5. See a peek definition from `/usr/include/eigen3/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h`

**Expected behavior**
Should see a definition in OpenCV source code.

**Code sample and logs**

- Code sample
```cpp
    std::vector<cv::KeyPoint> keypoints_1;
    cv::Mat descriptors_1; ;
    cv::Mat image1 = (cv::Mat_<double>(3, 3) << 1, 2, 3, 4, 5, 6, 7, 8, 9);
    cv::Ptr<cv::FeatureDetector> detector = cv::ORB::create();  
    cv::Ptr<cv::DescriptorExtractor> descriptor = cv::ORB::create();

    /// detect keypoints (oriented FAST)
    detector->detect(image1, keypoints_1);

    /// extract descriptor (BRIEF)
    descriptor->compute(image1, keypoints_1, descriptors_1);
```
- Configurations in `c_cpp_properties.json`
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu11",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
```
-------- Diagnostics - 2022/4/17 12:55:55
Version: 1.9.7
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu11",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/usr/local/include",
        "/usr/local/include/opencv",
        "/usr/include/eigen3",
        "/home/zhixin/slambook2_learning/orb_vo"
    ],
    "standard": "gnu++17",
    "compilerPath": "/usr/bin/x86_64-linux-gnu-g++-7",
    "compilerArgs": [
        "-g",
        "-std=gnu++1z"
    ]
}
Custom configurations:
[ /home/zhixin/slambook2_learning/orb_vo/orb_cv.cpp ]
{
    "defines": [
        "GFLAGS_IS_A_DLL=0"
    ],
    "standard": "gnu++17",
    "includePath": [
        "/usr/local/include",
        "/usr/local/include/opencv",
        "/usr/include/eigen3"
    ],
    "compilerPath": "/usr/bin/x86_64-linux-gnu-g++-7",
    "compilerArgs": [
        "-g",
        "-std=gnu++1z"
    ]
}
Translation Unit Mappings:
[ /home/zhixin/slambook2_learning/orb_vo/orb_cv.cpp ]:
    /home/zhixin/slambook2_learning/orb_vo/orb_cv.cpp
    /usr/local/include/opencv2/core.hpp *
    /usr/local/include/opencv2/core/operations.hpp *
    /usr/local/include/opencv2/features2d.hpp *
[ /usr/include/eigen3/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h ]:
    /usr/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h *
Translation Unit Configurations:
[ /home/zhixin/slambook2_learning/orb_vo/orb_cv.cpp ]:
    Process ID: 4689
    Memory Usage: 166 MB
    Compiler Path: /usr/bin/x86_64-linux-gnu-g++-7
    Includes:
        /usr/local/include/opencv
        /usr/include/eigen3
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
    Defines:
        GFLAGS_IS_A_DLL=0
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
[ /usr/include/eigen3/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h ]:
    Process ID: 4736
    Memory Usage: 17 MB
    Compiler Path: /usr/bin/x86_64-linux-gnu-g++-7
    Includes:
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
        --header_only_fallback
Total Memory Usage: 183 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 34365
```

**Screenshots**
![image](https://user-images.githubusercontent.com/40470855/163700557-79055d3f-bff2-4a9d-bc13-d964efd65fa7.png)

**Comment by Delta-in-hub** [comment]
Is this duplicated to #5499  ?

**Comment by Colengms** [comment]
Hi @zhixin-zhao .  Could you clarify if there is a specific location you are expecting "Go to definition" to navigate to in this scenario?  Does your workspace folder contain the source code to the OpenCV library?  I don't believe the extension would be capable of navigating to source files used to build the OpenCV library if they are not accessible to the extension.

**Comment by zhixin-zhao** [comment]
> Hi @zhixin-zhao . Could you clarify if there is a specific location you are expecting "Go to definition" to navigate to in this scenario? Does your workspace folder contain the source code to the OpenCV library? I don't believe the extension would be capable of navigating to source files used to build the OpenCV library if they are not accessible to the extension.

Yes. I expect the 'Go to definition' to navigate to the opencv header file installed in `/usr/local/include/opencv2/features2d.hpp`. And I'm sure it is accessible to the extension because `go to definition` can find the header declaration of `cv::Featuer2D::detect` in the exact same file.

**Comment by zhixin-zhao** [comment]
After research, I think I got the anwser. 
I should have used `go to declaration` instead of `go to definition` for a local installed library.
Maybe because eigen3 is a header only library, the extension just thought this is where the definition occurs.
Unfortunately,this is not obvious to me at beginning because vscode defaultly assign no shortcut to the command. 
HOWEVER **I hope the extension can be more smarter to avoid misleading users by go to a obvoius wrong place.** And I think it is applicable because at least in this case, using the namespace can eliminate the wrong result.

**Comment by Colengms** [comment]
Hi @zhixin-zhao .  Sorry, I didn't realize opencv is a header-only library.  It sounds you've figured this out.  The `compute` in `features2d.hpp` is indeed a declaration and not a definition.

The C/C++ extension implements a provider for `Go To Definition` and `Go To Declaration` requests from VS Code.  You might consider offering some feedback in [the VS Code repo](https://github.com/microsoft/vscode-cpptools/issues) if you have an idea to make these features more intuitive.

**Comment by zhixin-zhao** [comment]
@Colengms Thanks. By the way, just for correction, openCV is not header-only, another libary Eigen3 which is navigated to wrongly is header-only.
