### ISSUE TITLE
Disable specified error detection

### ISSUE THREAD

**Issue by xfarmer** [microsoft/vscode-cpptools#9199]
### Feature Request

Sometimes extensions report some unreasonable errors, i want to block specific error monitoring.
Such as:

`LOGI` defined as `#define LOGI(tag, fmt, ...)`
Called like `LOGI(LOG_TAG, "] \n\n");`

Then get error：
```
[{
	"resource": "xxxx.c",
	"owner": "C/C++",
	"code": "54",
	"severity": 8,
	"message": "too few arguments in invocation of macro \"LOGI\"",
	"source": "C/C++",
	"startLineNumber": 213,
	"startColumn": 39,
	"endLineNumber": 213,
	"endColumn": 40
}]
```

**Comment by michelleangela** [comment]
@xfarmer

Thank you for this feature request. There is currently an existing request for this at https://github.com/microsoft/vscode-cpptools/issues/1231. So I'll make this issue as duplicate.

In the mean time, there is suggested solution at https://github.com/microsoft/vscode-cpptools/issues/1231#issuecomment-837528890 to suppress certain errors. Could you try that solution and see if it works for your case?

**Comment by sean-mcmanus** [comment]
Our next release will have error code suppression for clang-tidy (not IntelliSense), but later we could potentially extend that to IntelliSense errors as well, see the code at https://github.com/microsoft/vscode-cpptools/blob/seanmcm/codeAnalysisFixCodeAction/Extension/src/LanguageServer/client.ts#L302 .
