### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hariharanmrgh** [microsoft/vscode-cpptools#92]
While installing c/c++  I had got an error like
"self signed certificate in certificate chain"
what can I do? please help me

**Comment by delmyers** [comment]
What OS are you using? Is this a Mac?

**Comment by pieandcakes** [comment]
@Hariharanmrgh Can you please provide more information such as your OS, when you get this error message?

**Comment by sridmad** [comment]
Please try the latest version of the extension 0.9.0. If the issue exists in the latest version please add information to the issue about OS and VSCode version.
