### ISSUE TITLE
Can not support C++ Concepts syntax when run g++ with '-std=c++17 -fconcepts'

### ISSUE THREAD

**Issue by solargg** [microsoft/vscode-cpptools#9204]
**Type: LanguageService**

**Describe the bug**

- OS and Version: **CentOS Linux release 7.9 (Final)**
- VS Code Version: **1.66.2**
- C/C++ Version: **v1.9.7**
- C/C++ Extension Pack Version: **v1.1.0**
- Does this issue involve using SSH remote to run the extension on a remote machine?: **Yes**
- IntelliSense does not support [GCC concetps](https://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros)

**Steps to reproduce**

1. Ensure `GCC 9.3.0` is available as a CMake Tools kit
2. Create new project folder
3. Create `CMakeLists.txt` with the following content:
```cmake
cmake_minimum_required(VERSION 3.15)

project(test LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(${PROJECT_NAME})

add_compile_options(-fconcepts)

target_sources(${PROJECT_NAME} PRIVATE main.cc)
```
4. Create `main.cc` with the following content:
```c++
template<typename T>
concept A = T::value || true;
 
template<typename U>
concept B = A<U*>;
 
template<class T>
constexpr bool is_meowable = true;
 
template<class T>
constexpr bool is_purrable() { return true; }
 
template<class T>
void f(T) requires is_meowable<T>; // OK

template<class T>
void h(T) requires (is_purrable<T>());

int main() {
  return 0;
}
```
`File` -> `Open folder...` -> project folder
5. Select `GCC 9.3.0` as CMake Tools kit
6. Configure project with CMake Tools
7. See `main.cc` in `Editor`, show some syntax error

**Expected behavior**
There is no syntax error.

**Additional context**

The extension correctly queries the proper GCC version with the following command line arguments:
```bash
$ -std=c++17 -fconcepts
```

**Comment by Colengms** [comment]
Hi @solargg .  Concepts were added in C++20.  I believe you will need to use:

```
set(CMAKE_CXX_STANDARD 20)
```

With this change, I no longer reproduce squiggles with the code you provided.
