### ISSUE TITLE
Wrong pretty-printing command

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-cpptools#9208]
Issue Type: <b>Bug</b>

By default, the C++ extension will greate a GDB configuration with the following:
```
			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			]
```

This doesn't enable pretty printing in GDB. What actually does is setting text to `set print pretty on`. See GDB documentation: https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_57.html

Extension version: 1.9.7
VS Code version: Code - Insiders 1.67.0-insider (a7a7f209ade96c516ce3cd9b330aa8c3db816223, 2022-04-14T05:15:18.304Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-107-generic
Connection to 'SSH: Ballz' could not be established  Canceled
Connection to 'SSH: Ballz' could not be established  Canceled
Remote OS version: Linux x64 5.4.0-107-generic

**Comment by WardenGnaw** [comment]
The cpptools extension utilizes `gdb-mi` for its debugging scenario. Modifying console text printing is not what the pretty printers the debugger enables, but rather the python pretty printers.

See more at: https://sourceware.org/gdb/onlinedocs/gdb/Pretty_002dPrinter-Introduction.html#Pretty_002dPrinter-Introduction
