### ISSUE TITLE
Automatically insert space after "//"

### ISSUE THREAD

**Issue by ShadowInks** [microsoft/vscode-cpptools#9214]
Bug type: Language Service

**Describe the bug**
- version: 1.66.2 (system setup)
- commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
- date: 2022-04-11T07:46:01.075Z
- Electron: 17.2.0
- Chromium: 98.0.4758.109
- Node.js: 16.13.0
- V8: 9.8.177.11-electron.0
- OS: Windows_NT x64 10.0.22000
- C/C++ Extension Version:1.9.7

Switch off VSCode setting Editor>Comments:InsertSpace
when i type comments in c++ code and save file
it will automatically insert space after "//"

**Steps to reproduce**

1. Switch off VSCode setting Editor>Comments:InsertSpace
2. type comments and save file, if i enable vscode-cpptools ,it will automatically add spaces after "//"
3. it won't happen when i disable vscode-cpptools 

**Expected behavior**

Do not automatically insert space  after "//"

**Code sample and logs**

- Code sample
~
- Configurations in `c_cpp_properties.json`
~
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
~
- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
~

**Screenshots**

![image](https://user-images.githubusercontent.com/42799053/164366667-91183da3-1e6f-4c71-8956-69514bbe4716.png)

**Additional context**

~

**Comment by michelleangela** [comment]
@ShadowInks 
This seems like the extension is inserting a space based on some formatting settings. What is `C_Cpp.formatting` configured to? Do you have any `C_Cpp.vcFormat.space.*` or Clang format setup?

**Comment by ShadowInks** [comment]
=_=     =_=     =_=

**Comment by ShadowInks** [comment]
> @ShadowInks This seems like the extension is inserting a space based on some formatting settings. What is `C_Cpp.formatting` configured to? Do you have any `C_Cpp.vcFormat.space.*` or Clang format setup?

![image](https://user-images.githubusercontent.com/42799053/164583094-e8e8c4a8-21bd-4563-9f9b-08813f41f29d.png)
![image](https://user-images.githubusercontent.com/42799053/164583189-69f5ef95-25ab-442d-aa69-2669646ee7ac.png)
![image](https://user-images.githubusercontent.com/42799053/164583140-285bd10b-3c89-49ad-a8bd-d1ef957e8bae.png)
![image](https://user-images.githubusercontent.com/42799053/164583239-2f3140f8-8a6f-451d-991a-b137d0bef6f1.png)

that‘s my all configs

i use clang-format to formatting code (**C_Cpp:Formatting is Default**)，but no space auto added when I run " clang-format -style=file -i {file} " in command line

**Comment by ShadowInks** [comment]
this is my .clang-format file
![image](https://user-images.githubusercontent.com/42799053/164584371-6c94b777-5d60-485a-a0de-61420267e018.png)

I'm sure this config doesn't automatically put spaces after comments

I guess there is something wrong with Editor>Comments:Insert Space, maybe because vscode-cpptools makes this switch invalid
@michelleangela

**Comment by ShadowInks** [comment]
@michelleangela  any idea about this problem?

**Comment by michelleangela** [comment]
>but no space auto added when I run " clang-format -style=file -i {file} " in command line
Is the clang-format executable that you used to run format manually the clang-format that is shipped with the extension or a different one? If it's a different one, what version is it?

I manually ran your .clang-format configuration using the clang-format that ships with the extension (located under ".vscode\extensions\ms-vscode.cpptools-1.10.0/bin/../LLVM/bin/clang-format") and it does insert space after "//".

There is the setting `C_Cpp.clang_format_path` to tell the extension which clang-format executable to use. By default, the executable that ships with the extension is used. If you have another clang-format executable that doesn't insert space when you run it manually with your .clang-format, could you try setting `C_Cpp.clang_format_path` with that other clang-format and see if that works?

**Comment by ShadowInks** [comment]
thank you  verymuch@michelleangela 

I think I know why.

It's not cpptools's bug.

Clang-format 13 will  insert space after "//",but clang-format 11 won't.
```
[20:18:03 ShadowInk@DevCloud-Docker /data]$.vscode-server/extensions/ms-vscode.cpptools-1.9.8-linux-x64/LLVM/bin/clang-format --version
clang-format version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)

[20:18:15 ShadowInk@DevCloud-Docker /data]$clang-format --version
clang-format version 11.0.0 (https://github.com/llvm/llvm-project.git e8e078c8bf7987b95298062a644bac9eed26f988)
```

The clang-format of version 11 was installed by myself., because I did not set `C_Cpp.clang_format_path` so that cpptools were not found, at last clang-format of version 13 took effect.
