### ISSUE TITLE
Enable play button for non C/C++ files

### ISSUE THREAD

**Issue by ryuukk** [microsoft/vscode-cpptools#9218]
### Feature Request

Hello

This feature is quite nice, and i use the extension to debug native code in other programming language (D, Zig)

It would be nice to have a way to enable it for every file extensions

Thanks

This feature: https://devblogs.microsoft.com/cppblog/whats-new-for-c-debugging-in-visual-studio-code/#quick-run-debug-play-button

**Comment by michelleangela** [comment]
@ryuukk
The C/C++ extension only provides IntelliSense and debugging support specifically for C and C++ languages only.

To request the play button for other languages, you would have to post the request on the repository of the extensions that support those other languages.

**Comment by michelleangela** [comment]
Closing as external issue.

**Comment by ryuukk** [comment]
@michelleangela I thought the debugger was developed by this extension, my bad!

I debug my program using the msvc debugger, through this extension even thought my program isn't written in C/C++, that is why i was thinking if launch tasks could be ran with that extension directly 

I should stop with thoughts and actually read more 😀
