### ISSUE TITLE
[feature] Prioritize the "folder" option in the menu of intelliSense.

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-cpptools#9222]
### Feature Request

There is a problem I encounter when I want to type `#include <QtCore/QCoreApplication>`.

When I type to `#include <QtCore`, it will become `#include<QtCore>/` if I just type `/`. To avoid that, I need to first press **"down"** key and then type `/`. It is because the header file `QtCore` is prior to the folder `QtCore` in the menu of intelliSense.

![image](https://user-images.githubusercontent.com/71438617/164619057-38f0cf8a-7151-4cdd-b592-29e2620b5a29.png)

### GIF

![GIF--intellisense](https://user-images.githubusercontent.com/71438617/164619277-66da3d93-49f5-42cf-bc3d-9bd8e017d680.gif)

**Comment by Colengms** [comment]
Hi @hwhsu1231 .  Thanks for bringing this to our attention.  :)

**Comment by sean-mcmanus** [comment]
This is fixed with 1.10.2 (pre-release).
