### ISSUE TITLE
Command line error: the specified language mode is incompatible with C / C + + (1027) {line 1, column 1}

### ISSUE THREAD

**Issue by wdy2580** [microsoft/vscode-cpptools#9225]
Issue Type: <b>Bug</b>

[{
	"resource": "/d:/.Develop/C_Language_Advanced_Programming/day03/src/main.c",
	"owner": "C/C++",
	"code": "1027",
	"severity": 8,
	"message": "命令行错误: 指定的语言模式不兼容",
	"source": "C/C++",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]

Extension version: 1.10.0
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (10.26GB free)|
|Process Argv|--crash-reporter-id 48393912-2052-4f44-a5c1-19d339f3edf1|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847

```

</details>

**Comment by Colengms** [comment]
Hi @wdy2580 .  Could you enable debug logging using `"C_Cpp.loggingLevel": "Debug"` and provide the content of the C/C++ output channel up to the issue?  That should provide us with the arguments we are trying to pass to the compiler that are not working as expected.

**Comment by wdy2580** [comment]
There is no way to compile the program with C / C + + plug-in, and the following errors will appear.
spawn C:\WINDOWS\system32\cmd. Exe enoent build completed with errors.
The terminal process failed to start (exit code: - 1).
This has happened before, but C / C + + plug-ins can still be compiled. And the problem automatically disappeared later, so I didn't care about it. Now it appears again.

**Comment by Colengms** [comment]
Hi @wdy2580 .  You're the first to report this.  I'm not able to easily reproduce this issue.  We need more information to understand what is happening on your machine.  Could you  provide the log output I requested in my previous comment?

I don't believe there is any circumstance in which the C/C++ extension should be attempting to invoke `cmd.exe` unless explicitly specified as a `compilerPath` in the configuration.  Could you also provide more information about how you have configured the C/C++ extension, such as the contents of your `c_cpp_properties.json`, if any?

Note that the C/C++ extension does not provide a compiler, so it is true that there is no way to compile a program with the C/C++ extension.  The C/C++ extension provides language services for C/C++ in the VS Code editor, such as IntelliSense, colorization, auto-completion, etc..  Perhaps the issue is that you have provided `cmd.exe` where a compiler path is expected?  The C/C++ extension will attempt to invoke any compiler other than `cl.exe` (MSVC), and will assume it is a gcc or clang based compiler, to extract configuration information from it.  It looks like you are using Windows, so not specifying a compiler at all should default to automatically configuring to reflect `cl.exe`.  Perhaps there is a `compilerPath` setting that currently specifies `C:\WINDOWS\system32\cmd. Exe` that can be removed from your configuration?

**Comment by wdy2580** [comment]
I used C / C + + plug-in again to generate it. It can be used normally, but it still shows the problem of incompatible language modes. And I didn't c_ cpp_ properties. json。 There is only one automatically generated tasks.json file. That's true:
I used C / C + + plug-in again to generate it. It can be used normally, but it still shows the problem of incompatible language modes. And I didn't C_ cpp_ properties. json。 There is only one automatically generated task JSON file. Its content is like this:
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc.exe 生成活动文件",
            "command": "C:\\Program Files (x86)\\.Develop\\mingw64\\bin\\gcc.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "main.c",
                "hello.c",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "调试器生成的任务。"
        }
    ],
    "version": "2.0.0"
}
This is the main process log above vscode：
[2022-04-23 00:33:05.806] [main] [info] window#load: attempt to load window (id: 1)
[2022-04-23 00:33:05.839] [main] [info] update#setState idle
[2022-04-23 00:33:05.928] [main] [info] ExtensionHostStarterWorker created
[2022-04-23 00:33:06.980] [main] [info] window#load: window reported ready (id: 1)
[2022-04-23 00:33:07.152] [main] [info] Starting extension host with pid 8744 (fork() took 14 ms).
[2022-04-23 00:33:07.153] [main] [info] ExtensionHostStarterWorker.start() took 15 ms.
[2022-04-23 00:33:35.848] [main] [info] update#setState checking for updates
[2022-04-23 00:33:36.638] [main] [info] update#setState idle
[2022-04-23 01:17:43.731] [main] [info] window#load: attempt to load window (id: 1)
[2022-04-23 01:17:44.679] [main] [info] window#load: window reported ready (id: 1)
[2022-04-23 01:17:44.809] [main] [info] Extension host with pid 8744 exited with code: 0, signal: null.
[2022-04-23 01:17:45.034] [main] [info] Starting extension host with pid 18932 (fork() took 12 ms).
[2022-04-23 01:17:45.034] [main] [info] ExtensionHostStarterWorker.start() took 12 ms.
[2022-04-23 01:23:37.983] [main] [info] window#load: attempt to load window (id: 1)
[2022-04-23 01:23:38.827] [main] [info] window#load: window reported ready (id: 1)
[2022-04-23 01:23:39.046] [main] [info] Extension host with pid 18932 exited with code: 0, signal: null.
[2022-04-23 01:23:39.124] [main] [info] Starting extension host with pid 19224 (fork() took 12 ms).
[2022-04-23 01:23:39.124] [main] [info] ExtensionHostStarterWorker.start() took 13 ms.
[2022-04-23 01:33:35.882] [main] [info] update#setState checking for updates
[2022-04-23 01:33:36.292] [main] [info] update#setState idle
[2022-04-23 01:35:39.926] [main] [info] window#load: attempt to load window (id: 1)
[2022-04-23 01:35:40.841] [main] [info] window#load: window reported ready (id: 1)
[2022-04-23 01:35:40.987] [main] [info] Extension host with pid 19224 exited with code: 0, signal: null.
[2022-04-23 01:35:41.238] [main] [info] Starting extension host with pid 18548 (fork() took 17 ms).
[2022-04-23 01:35:41.238] [main] [info] ExtensionHostStarterWorker.start() took 21 ms.

**Comment by Colengms** [comment]
Hi @wdy2580 .  The C/C++ extensions log output goes to the C/C++ output channel:

![image](https://user-images.githubusercontent.com/49173979/164769612-99742848-1a9d-457a-85da-18447df3d02c.png)

Could you provide the content of this log?

Also, could you provide all of the output from the build?  I believe that gets output to a terminal in the Terminal tab.  There should be some compilation errors indicated prior to `build completed with errors`.

**Comment by wdy2580** [comment]
Excuse me, sir. I found that there was no such problem after restarting the computer.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-cpptools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月23日(星期六) 凌晨1:34
***@***.***&gt;;
抄送:&nbsp;"2020024213 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-cpptools] Command line error: the specified language mode is incompatible with C / C + + (1027) {line 1, column 1} (Issue #9225)





 
Hi @wdy2580 .  You're the first to report this.  I'm not able to easily reproduce this issue.  We need more information to understand what is happening on your machine.  Could you  provide the log output I requested in my previous comment?
 
I don't believe there is any circumstance in which the C/C++ extension should be attempting to invoke cmd.exe unless explicitly specified as a compilerPath in the configuration.  Could you also provide more information about how you have configured the C/C++ extension, such as the contents of your c_cpp_properties.json, if any?
 
Note that the C/C++ extension does not provide a compiler, so it is true that there is no way to compile a program with the C/C++ extension.  The C/C++ extension provides language services for C/C++ in the VS Code editor, such as IntelliSense, colorization, auto-completion, etc..  Perhaps the issue is that you have provided cmd.exe where a compiler path is expected?  The C/C++ extension will attempt to invoke any compiler other than cl.exe (MSVC), and will assume it is a gcc or clang based compiler, to extract configuration information from it.  It looks like you are using Windows, so not specifying a compiler at all should default to automatically configuring to reflect cl.exe.  Perhaps there is a compilerPath setting that currently specifies C:\WINDOWS\system32\cmd. Exe that can be removed from your configuration?
