### ISSUE TITLE
We need Automatically generated "launch.json"!!!! like v1.8.4

### ISSUE THREAD

**Issue by Looong01** [microsoft/vscode-cpptools#9228]
### Feature Request

We need Automatically generated "launch.json"!!!! like v1.8.4

The latest verion of c/c++ extension cannot automatically generated "launch.json", when we press F5 or debug or run the code, after we just created a new c/c++ project.(At this time, there is no launch.json or task.json)

And this function had already been in the version 1.8.4. But you deleted it in the new version!

We need the function! It's much much useful for everyone!!!

**Comment by HiSunzhenliang** [comment]
Agreed！
