### ISSUE TITLE
Add ability to query detailed information about code elements from other extensions

### ISSUE THREAD

**Issue by PoetaKodu** [microsoft/vscode-cpptools#9229]
### Feature Request

Hello,

I'd like to write a VS Code extension that provides custom additional information about standard library functions and classes when hovered but for that, I'll need detailed information about the hovered symbol. It would be nice if I could use what is already available in the official C/C++ extension. I've seen that right now other extensions have to write custom parsers that mostly relay on regexes which are very inaccurate. The amount of information you can get using the official VS Code API is **very** limited.

To be more specific my extension will provide CppReference-like information on symbols like `find_if`, `std::fstream`, etc. but in a more readable format with examples, just as it is when you use other languages - TypeScript for example.

Thank you.

**Comment by Colengms** [comment]
Hi @PoetaKodu .  Thanks for opening this feature request.  Perhaps we could add an API that accepts an open TextDocument & position and returns information about the symbol at that position.
