### ISSUE TITLE
Restrict rename operation to current workspace folder(s)

### ISSUE THREAD

**Issue by lijh8** [microsoft/vscode-cpptools#9235]
### Environment

- OS and version: macOS 12.3.1
- VS Code: 1.66.2
- C/C++ extension: ms-vscode.cpptools v1.9.8
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

### Bug Summary and Steps to Reproduce

Bug Summary:

1. Rename by F2
2. It searches even the symbols in system library, it's dangerous because I'm root user and I may change system files by mistake because of this
3. It's slower than find & replace
4. restrict Rename to current directory, opened files or current file, make it configurable.

![Screen Shot 2022-04-25 at 16 31 47](https://user-images.githubusercontent.com/9011764/165063658-c5fbea85-687f-4560-8999-cc212d6697d6.png)

Steps to reproduce:
1. In this environment...
5. With this config...
6. Do '...'
7. See error...

### Debugger Configurations

```shell
None
```

### Debugger Logs

```shell
None
```

**Comment by Colengms** [comment]
Hi @ljhm .  Thanks for reporting this.  We can use this issue to track adding a setting to allow renaming to be restricted to files within the current workspace folder(s) (which should probably be the default).  We should also exclude files under known system include paths (that we discover when querying the compiler).

**Comment by Colengms** [comment]
https://github.com/microsoft/vscode-cpptools/issues/4102 might be related.  Rename uses Find All References under the hood.

**Comment by sean-mcmanus** [comment]
Yeah, https://github.com/microsoft/vscode-cpptools/issues/4102 is the same root issue, but it's more generalized so having this specific case open might still be useful if we wanted to do a more targeted fix.
