### ISSUE TITLE
Suggestion: Define new keyword by c_cpp_properties.json

### ISSUE THREAD

**Issue by andrea-pieretti** [microsoft/vscode-cpptools#924]
I'd like to define new keyword as i can do in Visual Studio
[](https://msdn.microsoft.com/en-us/library/zy61y8b8.aspx)

**Comment by andrea-pieretti** [comment]
https://msdn.microsoft.com/en-us/library/zy61y8b8.aspx this is an example

**Comment by sean-mcmanus** [comment]
Our extension doesn't currently implement any keyword functionality, and instead relies on the atom language-c support provided by VS Code itself, which I don't believe has any extension hook for custom keywords; however, as a workaround, you could try to modify the `Microsoft VS Code\resources\app\extensions\cpp\syntaxes\c++.json` file to add a custom keyword (e.g. `"match": "\\b(constexpr|export|mutable|typename|thread_local|foo)\\b",`), or if it's a generally used keyword, you could try adding it to the grammar at https://github.com/atom/language-c/tree/master/grammars and VS Code will eventually pick up the change.

**Comment by andrea-pieretti** [comment]
Thank you. I've modified the *.json file and it works perfectly.

**Comment by sean-mcmanus** [comment]
@andrea-pieretti FYI, it's possible when you update your VS code, your changes might be overwritten, so watch out for that. I know extension modifications get destroyed on updates, but I don't know how VS Code itself behaves.
