### ISSUE TITLE
Suppress gdb warning in the terminal ("&"warning: GDB: Failed to set controlling terminal")

### ISSUE THREAD

**Issue by rongxin-liu** [microsoft/vscode-cpptools#9248]
### Feature Request

When debugging using the integrated terminal with `gdb`, is it possible to suppress or hide this debug launch command, so it is not shown to the user?

<img width="760" alt="gdb_warning" src="https://user-images.githubusercontent.com/10591665/166000886-098891fc-c0c1-4ef1-a628-97c204275e38.png">

Or what might be causing this warning?

Thank you!

**Comment by WardenGnaw** [comment]
The message "warning: GDB: Failed to set controlling terminal" is actually a long standing bug in gdb when the debuggee's output is redirected to a tty and is harmless. When using the terminal support, we attempt to remove this message by resetting the terminal as early as possible. GDB also has a number of bugs around the display of Unicode characters which can appear as a list of numbers as you reported above.
