### ISSUE TITLE
Add Setting to Debug "Just My Code"

### ISSUE THREAD

**Issue by MBetters** [microsoft/vscode-cpptools#9250]
### Feature Request

Please add a setting called something like `C_Cpp.debugJustMyCode` that is a Boolean. When it's `true`, debugger actions like Step Into should step to the first line of the user's function body. If it's `false` (default value), debugger actions like Step Into would behave as they do now (stepping into non-user-code function calls that might be nested in arguments of the user-code function call, etc.).

There's precedent for debugging "just my code." Visual Studio does it. So does the Jupyter extension via their `jupyter.debugJustMyCode` setting.

**Comment by WardenGnaw** [comment]
Requires https://github.com/microsoft/vscode-cpptools/issues/5763
