### ISSUE TITLE
debugger quit when setting break point or switching to another thread on ubuntu 22.04 (WSL2)

### ISSUE THREAD

**Issue by pohhsu** [microsoft/vscode-cpptools#9253]
### Environment

- OS and version:  Windows 11 WSL2 Ubuntu 22.04 
- VS Code:
          Version: 1.66.2 (user setup)
          Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
          Date: 2022-04-11T07:46:01.075Z
          Electron: 17.2.0
          Chromium: 98.0.4758.109
          Node.js: 16.13.0
          V8: 9.8.177.11-electron.0
          OS: Windows_NT x64 10.0.22000
- C/C++ extension:
          C/C++ v1.9.8
- OS and version of remote machine (if applicable):
- GDB / LLDB version:
        GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
        Copyright (C) 2022 Free Software Foundation, Inc.

### Bug Summary and Steps to Reproduce

Bug Summary:
VC code debugger quits immediately after start debugging with:
  Aborted (core dumped)
  [1] + Aborted (core dumped)      "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-ns2vuk2i.3xq" 1>"/tmp/Microsoft-MIEngine-Out-br5vdh4k.oln"

Steps to reproduce:

Install Ubuntu22.04 on WSL2 on Windows 11
build main.cpp (see attached repro.zip) via
     g++ -g -O0 main.cpp 

set breakpoint on line 8

void threadFunction()
{
    std::this_thread::sleep_for(50000ms);    <--- here
}

start debugging, and it will core dump.

Note, without setting breakpoint, if you start debugging, and hit pause, then switch the thread to the 2nd thread, it will also quit.

note that using console gdb it is fine
[repro.zip](https://github.com/microsoft/vscode-cpptools/files/8595107/repro.zip)
.

### Debugger Configurations

```shell
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
//            "logging": { "engineLogging": true, "trace": true, "traceResponse": true },
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }        
    ]
}
```

### Debugger Logs

```shell
the log is attached as repro.log below
```

### Other Extensions

no other extensions were enabled. 

### Additional Information

[repro.zip](https://github.com/microsoft/vscode-cpptools/files/8595100/repro.zip)
[repro.log](https://github.com/microsoft/vscode-cpptools/files/8595114/repro.log)

**Comment by WardenGnaw** [comment]
This seems to be an error with gdb under mi mode.

From the logs:
>/build/gdb-wIRHdd/gdb-12.0.90/gdb/value.c:1731: internal-error: value_copy: Assertion `arg->contents != nullptr' failed.\\nA problem internal to GDB has been detected, further debugging may prove unreliable.
This is a bug, please report it."
 For instructions, see: https://www.gnu.org/software/gdb/bugs/

**Comment by AlbertDM** [comment]
I can replicate the same issue using GDB in VSCode in Ubuntu 22.04 natively installed. Before I was running same project in Ubuntu 20.04 and this was not happening.

When a breakpoint is set in the main thread (Thread 1), everything runs flawlessly but when the breakpoint happens to be in a different thread I get the same error as OP:

```
/build/gdb-wIRHdd/gdb-12.0.90/gdb/value.c:1731: internal-error: value_copy: Assertion `arg->contents != nullptr' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
```

**Comment by richardh538** [comment]
> I have been able so solve it, and now I can debug threaded applications with GDB 12.1 and Ubuntu 22.04:

Excellent! Thank you very much, this solved my debug issues as well.

I downloaded the pre-built package from [launchpad](
https://launchpad.net/ubuntu/+source/gdb/12.1-0ubuntu1/+build/23606376)
