### ISSUE TITLE
Not compatible with MinGW-x64

### ISSUE THREAD

**Issue by VFerguson-haikurange** [microsoft/vscode-cpptools#9255]
I've been trying to debug my c++ code with VScode and MinGW-x64 for the past few days. The tutorial I used for the setup is: https://code.visualstudio.com/docs/languages/cpp#_intellisense

No matter what I try, gcc or g++ does not show up when trying to create a build task. Windows can see the executables because the path variable has been set properly.
According to the instructions, I should see "C/C++: g++.exe build active file". When trying to run build task. There is nothing in mine. Configure default build task also has no c/c++ options.

**Comment by Colengms** [comment]
Hi @VFerguson-haikurange .  MinGW is supported, and I'm not easily able to reproduce an issue.  We don't currently have other users reporting this issue with the tutorial, that I'm aware of.

MinGW is available in many forms, so could you confirm whether you acquired it from the same source referred to in the tutorial?  Also, did you install it to the default location, or a different location?  The C/C++ extension will search for compilers when it activates, so be sure you have reloaded VS Code after installing it.

To understand what might be happening on your system, we may need more information, such as any configuration details, and logs from the C/C++ extension so we can look for any errors being reported.  Could you enable `"C_Cpp.loggingLevel": "Debug"` and provide the output of the C/C++ output channel leading up to the issue?  Also, could you provide the contents of your `c_cpp_properties.json`, if any?

You might consider installing the CMake Tools extension as well, running it's `Scan for Kits` command, and checking to see if CMake Tools was able to detect MinGW.  If neither extension can detect it, there may be an issue with how it was installed.
