### ISSUE TITLE
program not compiling

### ISSUE THREAD

**Issue by Chakradhar094** [microsoft/vscode-cpptools#9256]
c/c++ programming file is not compliling.i am unable to get c/c++ executable file

**Comment by Colengms** [comment]
Hi @Chakradhar094 .  I don't think we have enough information about your issue to be of much help.  Could you explain what exactly your are doing in your scenario, what step is failing for you, how it is failing, etc.?  Are you having an issue with build tasks, or is the issue that the compiler you are using is reporting compilation errors?

Note that the C/C++ extension is not directly involved in compiling your code source code.  It provides language services such as IntelliSense, auto-completion, colorization, etc..  The C or C++ compiler itself is an external component.
