### ISSUE TITLE
#include is not taken literally

### ISSUE THREAD

**Issue by sewbacca** [microsoft/vscode-cpptools#9258]
Bug type: Language Service

When using `#include "..."` the language server doesn't take them literally and shows a syntax error, where none is.

**Describe the bug**
- OS and Version: Windows
- VS Code Version: 1.66.2
- C/C++ Extension Version: 1.9.8
- When trying to use includes inside expressions, vscode won't take them literally and show non existing syntax errors.

**Steps to reproduce**
Where I found the error:
1. Clone [Love2D](https://github.com/love2d/love)
2. Configure project
3. Navigate to `src/modules/graphics/wrap_Graphics.cpp`
4. Scroll down to line `:45`
5. See error

Simpler case:

`main.cpp`
```cpp

#include <iostream>

const char str[] =
#include "str.txt"
;

int main(int argc, char const *argv[])
{
	std::cout << str << std::endl;
	return 0;
}

```

`str.txt`
```cpp
"Hello, world!"
```

Notice: The error vanishes, if `const char str[] = ...` is moved into `main`.

**Expected behavior**
No syntax error.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/15840247/166142295-908a3446-90ff-4a9e-8950-423d32dbda14.png)

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed internal bug 1535519 against our IntelliSense parser shared with VS.

**Comment by sean-mcmanus** [comment]
It turns out this is "by design" for performance reasons and the suggested workaround is to use
```cpp
const char str[] = {
#include "str.txt"
};
```
