### ISSUE TITLE
VSCode stuck on "Starting Build..."

### ISSUE THREAD

**Issue by realKarthikNair** [microsoft/vscode-cpptools#9259]
refer #5628  for an extended description: I am facing the exact issue

I use VSCode along with gcc to compile C code. I was using the same launch.json and tasks.json file last week too but it no longer compiles since today; it's stuck on "Starting Build..."

However, if I paste the command under "Starting Build..." directly to the terminal, the compiled binary is indeed created.

I got no help in Googling, someone please help me out

![image](https://user-images.githubusercontent.com/78267371/166162916-75026932-5e51-4520-a682-6bf9649eb44b.png)

using Pop!_OS 22.04 btw

    Linux 5.16.19-76051619-generic GNU/Linux
    1.66.2
    dfd34e8260c270da74b5c2d86d61aee4b6d56977
    x64

**Comment by realKarthikNair** [comment]
Tried the insiders build too... same issue

**Comment by Colengms** [comment]
Hi @realKarthikNair .  This looks very similar to https://github.com/microsoft/vscode-cpptools/issues/9241.  Could you confirm whether you are seeing that issue?  If so, a potential work-around would be to move the project to a path that does not contain spaces.  We should have a fix for that in our next insiders release.

If that is not the issue you are seeing, could you set `"C_Cpp.loggingLevel": "Debug"` and provide the output in the C/C++ output channel leading up to the issue?

**Comment by realKarthikNair** [comment]
@Colengms I am kind of facing the same issue and yes, the work-around removing spaces from path works!

Thank you so much

**Comment by Colengms** [comment]
Closing as a duplicate.
