### ISSUE TITLE
1: (200) Wait for connection completion.

### ISSUE THREAD

**Issue by greatmarx** [microsoft/vscode-cpptools#9262]
### Environment

- C/C++ extension:v1.9.8
- OS and version of remote machine (if applicable):
- GDB / LLDB version:x86_64-8.1.0-release-win32-seh-rt_v6-rev0

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

### Bug Summary and Steps to Reproduce

Bug Summary:
when I run F5,will occour this problem:

1: (99) LaunchOptions{"name":"(gdb) Launch","preLaunchTask":"g++.exe build active file","type":"cppdbg","request":"launch","program":"e:\\3_code\\c_code\\hello_world.exe","args":[],"stopAtEntry":false,"cwd":"E:\\3_code\\c_code","environment":[],"externalConsole":false,"MIMode":"gdb","miDebuggerPath":"D:\\Program Files\\mingw-w64\\bin\\gdb.exe","logging":{"engineLogging":true},"setupCommands":[{"description":"Enable pretty-printing for gdb","text":"-enable-pretty-printing","ignoreFailures":false}],"__configurationTarget":5,"__sessionId":"ef32c4ec-d0ca-490e-9730-8b5ac9b07945"}
1: (200) Wait for connection completion.

### Debugger Configurations

```shell
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(gdb) Launch",
            "preLaunchTask": "g++.exe build active file",//调试前执行的任务，就是之前配置的tasks.json中的label字段
            "type": "cppdbg",//配置类型，只能为cppdbg
            "request": "launch",//请求配置类型，可以为launch（启动）或attach（附加）
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",//调试程序的路径名称
            "args": [],//调试传递参数
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,//true显示外置的控制台窗口，false显示内置终端
            "MIMode": "gdb",
            "miDebuggerPath": "D:\\Program Files\\mingw-w64\\bin\\gdb.exe",
            "logging": { "engineLogging": true },
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": false
                }
            ]
        }
    ]
}

{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "g++.exe build active file",
			"command": "D:/Program Files/mingw-w64/bin/gcc.exe",
			"args": [
				"-fdiagnostics-color=always",
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "D:/Program Files/mingw-w64/bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "编译器: \"D:/Program Files/mingw-w64/bin/gcc.exe\""
		}
	]
}
```

### Debugger Logs

```shell
1: (99) LaunchOptions{"name":"(gdb) Launch","preLaunchTask":"g++.exe build active file","type":"cppdbg","request":"launch","program":"e:\\3_code\\c_code\\hello_world.exe","args":[],"stopAtEntry":false,"cwd":"E:\\3_code\\c_code","environment":[],"externalConsole":false,"MIMode":"gdb","miDebuggerPath":"D:\\Program Files\\mingw-w64\\bin\\gdb.exe","logging":{"engineLogging":true},"setupCommands":[{"description":"Enable pretty-printing for gdb","text":"-enable-pretty-printing","ignoreFailures":false}],"__configurationTarget":5,"__sessionId":"ef32c4ec-d0ca-490e-9730-8b5ac9b07945"}
1: (200) Wait for connection completion.
```

**Comment by greatmarx** [comment]
<img width="758" alt="屏幕截图 2022-05-02 173341" src="https://user-images.githubusercontent.com/42257495/166214431-94295f4b-1e5e-4d9d-ac14-699f5e69391a.png">

**Comment by WardenGnaw** [comment]
Are you able to run `D:\\Program Files\\mingw-w64\\bin\\gdb.exe e:\\3_code\\c_code\\hello_world.exe` in a command prompt?

**Comment by greatmarx** [comment]
> Are you able to run `D:\\Program Files\\mingw-w64\\bin\\gdb.exe e:\\3_code\\c_code\\hello_world.exe` in a command prompt?
<img width="499" alt="屏幕截图 2022-05-04 082716" src="https://user-images.githubusercontent.com/42257495/166608022-db8a79b3-54c7-46f6-8f25-65a3eb68b80d.png">

No, in command windows "gdb hello_world.exe" has no response. Do you think mingw-64 in my system is not ok?

**Comment by WardenGnaw** [comment]
Yes. There must have been an issue with the setup.

Does just running `gdb` without any args work?

**Comment by greatmarx** [comment]
> Yes. There must have been an issue with the setup.
> 
> Does just running `gdb` without any args work?
Thanks for your help.  I now find the reason is "D:\Program Files\mingw-w64\bin\gdb.exe" can't work. when I change the path of mingw-64  to  "D:\Program Files\mingw-w64\bin\gdb.exe" , it works well.
<img width="472" alt="屏幕截图 2022-05-04 151941" src="https://user-images.githubusercontent.com/42257495/166637683-a077111e-c168-407a-a826-146b76343cc5.png">

**Comment by l-t-m-f** [comment]
> > Yes. There must have been an issue with the setup.
> > Does just running `gdb` without any args work?
> 
> Thanks for your help. I now find the reason is "D:\Program Files\mingw-w64\bin\gdb.exe" can't work. when I change the path of mingw-64 to "D:\Program Files\mingw-w64\bin\gdb.exe" , it works well. <img alt="屏幕截图 2022-05-04 151941" width="472" src="https://user-images.githubusercontent.com/42257495/166637683-a077111e-c168-407a-a826-146b76343cc5.png">

I have the same issues but I can't understand your final answer. What did you change the path to and from?

**Comment by sean-mcmanus** [comment]
@l-t-m-f I believe they mean the current working directory needed to be set to "D:\Program Files\mingw-w64\bin" (the path would need to match your particular installation though).
