### ISSUE TITLE
Lookup errors with libc++

### ISSUE THREAD

**Issue by misha-antonenko** [microsoft/vscode-cpptools#9263]
Issue Type: <b>Bug</b>

The command I use to compile some C++ is `clang++ -std=c++2a -pthread -stdlib=libc++`. The configuration is modified accordingly to use these flags. When adding an include like `#include <utility>` to a source file, there appears an error squiggle containing several messages of kind `no member named 'abort' in namespace 'std'`.

Extension version: 1.9.8
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id de7537ee-b7ff-4aa6-9ac1-40d3f0a20bb2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: seraph|
|OS|Linux x64 5.4.0-96-generic|
|CPUs|Intel Xeon Processor (Icelake) (14 x 1999)|
|Memory (System)|13.66GB (1.93GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by misha-antonenko** [comment]
I solved this by overriding the clang-tidy includes.

<img width="598" alt="Screenshot 2022-05-02 at 18 56 19" src="https://user-images.githubusercontent.com/16488226/166265927-96f78bc6-4cd5-4fb1-b63a-446d6a5b5de7.png">

**Comment by sean-mcmanus** [comment]
Is this an error with compiling, clang-tidy, or IntelliSense?

**Comment by misha-antonenko** [comment]
I suppose clang-tidy

I recall that I solved it by attempting to override the conflicting include `-I/usr/include/x86_64-linux-gnu` in the extension settings like this:
<img width="668" alt="Screenshot 2022-05-07 at 22 05 00" src="https://user-images.githubusercontent.com/16488226/167268382-42e84d0c-dd65-450c-8b61-3e56efb96857.png">

And this brought the following errors in the tail of the extension log (while, nevertheless, effectively removing the error squiggles):
```
-D__unix__=1
-D__x86_64=1
-D__x86_64__=1
-I/usr/lib/llvm-10/include/c++/v1
-I/usr/local/include
-I/usr/lib/llvm-10/lib/clang/10.0.0/include
-I/usr/include/x86_64-linux-gnu
-I/usr/include
error: clang-tidy: Unknown command line argument '-I/usr/lib/llvm-10/include/c++/v1'.  Try: '/home/an-to-nen-ko/.vscode-server/extensions/ms-vscode.cpptools-1.9.8-linux-x64/bin/../LLVM/bin/clang-tidy --help'
clang-tidy: Did you mean '--help-list-hidden'?
clang-tidy: Unknown command line argument '-I/usr/local/include'.  Try: '/home/an-to-nen-ko/.vscode-server/extensions/ms-vscode.cpptools-1.9.8-linux-x64/bin/../LLVM/bin/clang-tidy --help'
clang-tidy: Did you mean '--use-color'?
clang-tidy: Unknown command line argument '-I/usr/lib/llvm-10/lib/clang/10.0.0/include'.  Try: '/home/an-to-nen-ko/.vscode-server/extensions/ms-vscode.cpptools-1.9.8-linux-x64/bin/../LLVM/bin/clang-tidy --help'
clang-tidy: Did you mean '--enable-check-profile'?
clang-tidy: Unknown command line argument '-I/usr/include'.  Try: '/home/an-to-nen-ko/.vscode-server/extensions/ms-vscode.cpptools-1.9.8-linux-x64/bin/../LLVM/bin/clang-tidy --help'
clang-tidy: Did you mean '--use-color'?
IntelliSense Engine = Default.
The extension will use the Tag Parser for IntelliSense when #includes don't resolve.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
  Processing folder (recursive): /usr/lib/llvm-10/include/c++/v1/
  Processing folder (recursive): /usr/lib/llvm-10/lib/clang/10.0.0/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /home/an-to-nen-ko/work_of_my_life/
  Discovering files: 20715 file(s) processed
  0 file(s) removed from database
Done discovering files.
Populating include completion cache.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
```

So this might hint at the steps to reproduce: open a project on pure Make (without cmake), set the compilation flags listed above using the 'Edit Configurations' command, and, hopefully, obtain the same error squiggles on trying to include the standard headers

**Comment by sean-mcmanus** [comment]
The clangTidy.args setting expects clang-tidy args and not clang args, i.e. https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/ , so the -I arg is causing clang-tidy to fail.

Code
```
#include <utility>

int main()
{
    std::abort();
}
```
gives error: no member named 'abort' in namespace 'std'.

Are you able to provide repro code that compiles?

**Comment by misha-antonenko** [comment]
I suppose I have found a workaround then
