### ISSUE TITLE
c_cpp_properties.json getting reset to default

### ISSUE THREAD

**Issue by JasonMiesionczek** [microsoft/vscode-cpptools#927]
When working on a C++ project, i customized the c_cpp_properties.json to add a bunch of include directories. Within a few minutes, that file was reverted back to its default state. Here is the default state of the file:

```
{
    "configurations": [
        {
            "name": "null",
            "includePath": [],
            "defines": [],
            "browse": {
                "path": [
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 2
}
```

This is running on a freshly installed Manjaro linux machine.

Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by bobbrow** [comment]
What you have posted is not what our extension uses as the default state of the file.

Do you have any other extensions installed?  CMake Tools Helper, perhaps?  This looks like a bug we've seen in that extension before.  I would suggest filing an issue in their repository.  https://github.com/maddouri/vscode-cmake-tools-helper/issues

**Comment by JasonMiesionczek** [comment]
Yes, it appears that CMake Tools Helper is to blame here. Thanks, I will correct things on my end.
