### ISSUE TITLE
When an IntelliSense process exceeds `C_Cpp.intelliSenseMemoryLimit` it's counted as a crash in telemetry

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cpptools#9274]
It looks like when an IntelliSense process exceed the memory limit imposed by `C_Cpp.intelliSense.maxMemory`, it's counted as a crash in telemetry.  Perhaps it should be counted separately, as the process may not necessarily have crashed if the limit were not imposed.

```
textDocument/hover: D:\cpptools\test\out.cpp (id: 55)
Shutting down IntelliSense server: D:\CPPTOOLS\TEST\OUT.CPP. Memory usage is 5297 MB and has exceeded the 4096 MB limit.
IntelliSense process crash detected.
```

**Comment by bobbrow** [comment]
Good find.  We should prioritize this so that we're not looking at bad data.

**Comment by Colengms** [comment]
Correction: this appears to be related to `C_Cpp.intelliSenseMemoryLimit` and not `C_Cpp.intelliSense.maxMemory`.  They seem to be two seperate methods to impose memory limits on IntelliSense.  I'll open another issue to track unifying them. `C_Cpp.intelliSenseMemoryLimit` will send `IntelliSenseMemoryUsage` telemetry, but `C_Cpp.intelliSense.maxMemory` does not.

**Comment by Colengms** [comment]
Closing this, as codebase unification will result in an equivalent memory limit being applied using an OS Job on Windows or `setrlimit()` on Linux/macOS.  That approach necessarily causes a crash, as a memory allocation fails and generates either an `std::bad_alloc` exception or a null dereference.  Since this will be indistinguishable from a crash, and because VS captures the equivalent as crashes, leave this as-is for now.
