### ISSUE TITLE
Remote VSCode - IntelliSense scans files only when opened in VSCode

### ISSUE THREAD

**Issue by sarankrishnan** [microsoft/vscode-cpptools#9275]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 Pro 
- VS Code Version: 1.66.2
- C/C++ Extension Version: v1.9.8
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: Ubuntu 20.04.4 LTS
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

When I open a C/C++ project in the remote server (Ubuntu) VSCode scans and builds the database (.browse.VC.db) only when a new file is opened in the editor. It doesn't scan the workspace and update the database in the background which leads to not finding symbols present in the unopened files. 

**Expected behavior**
VSCode could build the IntelliSense database in the background when the folder/workspace is opened. 

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang++-10",
            "cStandard": "c11",
            "cppStandard": "c++14",
            "intelliSenseMode": "${default}",
            "compileCommands": "",
            "configurationProvider": "ms-vscode.cmake-tools",
            "browse": {
                "databaseFilename": "",
                "path": [],
                "limitSymbolsToIncludedHeaders": true
            }
        }
    ],
    "version": 4
}

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

cpptools/getCodeActions:<a file present in the project/workspace > (id: 406)
cpptools/queryTranslationUnitSource:<a file present in the project/workspace > (id: 407)
textDocument/didOpen:<a file present in the project/workspace >
Checking for syntax errors:<a file present in the project/workspace >
Queueing IntelliSense update for files in translation unit of:<a file present in the project/workspace >
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols:<a file present in the project/workspace > (id: 408)
cpptools/activeDocumentChange:<a file present in the project/workspace >
cpptools/getDocumentSymbols
cpptools/getSemanticTokens:<a file present in the project/workspace > (id: 409)
cpptools/finishUpdateSquiggles
Error squiggle count: 0
Error squiggle count: 3
terminating child process: 126878
Update IntelliSense time (sec): 0.534
cpptools/getFoldingRanges:<a file present in the project/workspace > (id: 410)
cpptools/getSemanticTokens: <a file present in the project/workspace - headerfile >  (id: 411)
cpptools/getCodeActions:<a file present in the project/workspace > (id: 412)
cpptools/getFoldingRanges:<a file present in the project/workspace > (id: 413)
Shutting down IntelliSense server: <a file present in the project/workspace - previously opened file> 
textDocument/definition:<a file present in the project/workspace > (id: 414)
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange:<a file present in the project/workspace >
textDocument/didClose:<a file present in the project/workspace >

**Screenshots**

**Comment by sean-mcmanus** [comment]
Remove the `"path": []` -- that is causing the includePath to not be used as the default for workspace parsing.

Maybe we could add some better logging or a warning when this happens and/or change the default or something. We could use this issue to track that or I could open a new issue.

**Comment by sarankrishnan** [comment]
Thanks, @sean-mcmanus for the quick response. Unfortunately, it didn't help to scan and update the database. It still updates only the file which gets opened on the editor.

**Comment by sarankrishnan** [comment]
I did a bit of digging and found that the parsing of workspace hasn't happened in my remote VSCode - DB icon isn't shown even for a second on the status bar. 

https://github.com/microsoft/vscode-cpptools/blob/7fdddf23fe8b5457030ce3fbfcd2eacbb3a60efa/Extension/src/LanguageServer/ui.ts#L286

When I open the project on native windows vscode, I can see the DBIcon on the status bar after which I can navigate freely using the built database.

**Comment by sean-mcmanus** [comment]
Oh, I see you have "configurationProvider": "ms-vscode.cmake-tools" set -- we get browse path info from the CMake Tools extension in that case. Has that extension been properly configured? If you run the C/C++: Log Diagnostics command after opening a source file you can get info on the configuration, look for `Custom browse configuration: `.

**Comment by sarankrishnan** [comment]
From the log, the Custom Browse Configuration is empty. 

I cleaned up the existing workspace (.vscode) and .vscode-server. Restarted the Remote VScode and installed the extensions. This time I didn't specify the "configurationProvider" and it started to build the DB. Now all is good - I'm able to navigate across the codebase and could see the .browse.VC.db is over 500 MB (which I see is built right given the size of my project - previously it was around 20MB)

Thanks a lot for your help @sean-mcmanus - I will close this ticket.
