### ISSUE TITLE
Adding the standard library makes the parsing take a very long time

### ISSUE THREAD

**Issue by horvay** [microsoft/vscode-cpptools#928]
**OS**: Windows 10
**Project**: Amazon's Lumberyard

**c_cpp_properties.json**
```JSON
{  
   "name":"Win32",
   "includePath":[  
      "C:/Program Files (x86)/Windows Kits/10/include/10.0.15063.0/ucrt",
      "${workspaceRoot}/Principia/Game",
      "${workspaceRoot}/Principia/Modules/PrincipiaModule",
      "${workspaceRoot}/CryEngine/CryCommon",
      "${workspaceRoot}/CryEngine/CryAction",
      "${workspaceRoot}/Framework/AzGameFramework",
      "${workspaceRoot}/Engine/LmbrCentral/include",
      "${workspaceRoot}/Framework/AzFramework",
      "${workspaceRoot}/Framework/GridMate",
      "${workspaceRoot}/Framework/AzCore",
      "${workspaceRoot}/Framework/AzTest",
      "C:/w/pa/Lumberyard/1.9.0.1/3rdParty/GoogleMock/gmock-az-1.0/googlemock/include",
      "C:/w/pa/Lumberyard/1.9.0.1/3rdParty/GoogleMock/gmock-az-1.0/googletest/include"
   ],
   "defines":[  
      "_DEBUG",
      "_WIN32",
      "_WIN64",
      "NOMINMAX",
      "CODE_BASE_FOLDER=&quot;c:/w/pa/Lumberyard/1.9.0.1/dev/Code/&quot;",
      "_ITERATOR_DEBUG_LEVEL=2",
      "DEDICATED_SERVER",
      "AZ_TESTS_ENABLED",
      "BINFOLDER_NAME=&quot;Bin64vc120&quot;",
      "PLATFORM_SUPPORTS_AWS_NATIVE_SDK",
      "LY_BUILD=398643",
      "_MT",
      "_DLL"
   ],
   "intelliSenseMode":"msvc-x64",
   "browse":{  
      "path":[      ],
      "limitSymbolsToIncludedHeaders":false,
      "databaseFilename":"${workspaceRoot}/.vscode/.BROWSE.VC.DB"
   }
}
```

**settings.json**
```JSON
"files.autoSave": "afterDelay",
"C_Cpp.intelliSenseEngine": "Default",
"C_Cpp.autocomplete": "Default",
"C_Cpp.errorSquiggles": "Enabled",
"C_Cpp.intelliSenseEngineFallback": "Disabled",
"editor.detectIndentation": false,
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"
```

If I don't have the standard library in the include file like above, I get the following:
![without-stl](https://user-images.githubusercontent.com/7866855/28738256-6bdb2e90-73c0-11e7-8ef8-eef4790c02c5.gif)

The after the copy/paste, the intellesense process goes from 180m to about 55m and then back to 180m very quickly.

However, if I change my include to be the following:
```JSON
"includePath": [
    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/INCLUDE",
    "C:/Program Files (x86)/Windows Kits/10/include/10.0.15063.0/ucrt",
    "${workspaceRoot}/Principia/Game",
    "${workspaceRoot}/Principia/Modules/PrincipiaModule",
    "${workspaceRoot}/CryEngine/CryCommon",
    "${workspaceRoot}/CryEngine/CryAction",
    "${workspaceRoot}/Framework/AzGameFramework",
    "${workspaceRoot}/Engine/LmbrCentral/include",
    "${workspaceRoot}/Framework/AzFramework",
    "${workspaceRoot}/Framework/GridMate",
    "${workspaceRoot}/Framework/AzCore",
    "${workspaceRoot}/Framework/AzTest",
    "C:/w/pa/Lumberyard/1.9.0.1/3rdParty/GoogleMock/gmock-az-1.0/googlemock/include",
    "C:/w/pa/Lumberyard/1.9.0.1/3rdParty/GoogleMock/gmock-az-1.0/googletest/include"
],
```

Then I get this type of performance:
![with-stl](https://user-images.githubusercontent.com/7866855/28738280-8b1f77fc-73c0-11e7-8b55-86671ef1a78a.gif)

As you can see, the intellesense process goes from about 500m to about 180m, and then **very** slowly back up to 500m.

Is this expected behavior?

**Comment by bobbrow** [comment]
Is your editor auto-saving on paste?  Saving the file is one of the triggers that results in a full reparse of the translation unit (which releases a bunch of memory and rebuilds the AST for the source file and its dependencies).  We try to avoid doing full reparses whenever possible because it can take a long time.

The memory usage difference between having the VC folder in the includePath vs not having it does surprise me a bit, but using 500 MB in the game engine translation unit does not surprise me.

We still have work to do to get the memory usage down, but I'll want to compare what I see here with Visual Studio to see if the full reparse time is similar since we are using the same IntelliSense engine.

**Comment by horvay** [comment]
@bobbrow Thanks for your reply!

Unfortunately, I do have auto-save on (it's very nice not thinking about saving.)

I don't think the memory usage is such a big deal. VS (especially with resharper) uses much much more.

It's really the speed at which it takes to parse that makes it difficult. Because in visual studio, even with resharper installed (which is a hog,) it doesn't take that long to parse after saving in VS.

I did a test without autosave on doing the same thing, and it still took minutes of parsing when copying and pasting code.

![without-autosave](https://user-images.githubusercontent.com/7866855/28740762-08251336-73d7-11e7-8245-249dbc8a403d.gif)

I didn't show the whole thing because it would be staring at nothing for minutes :P Also my cat stepped on the spacebar.

So I tried an even simplier test. I just hit the space key (inspired by said cat,) and it still took over a minute to parse to get IntelliSense/navigation/squiggles/etc. I just get `loading...` if I try to do anything before it finishes.

![without-autosave-space-only](https://user-images.githubusercontent.com/7866855/28740790-6b065c08-73d7-11e7-8dcb-279ee055598b.gif)

I suppose my best choice then are:

- Don't use error squiggles and don't include the standard library since I mostly use Lumberyard constructs anyways
- Go back to sluggish Visual Studio #supersadface

Let me know if you have any thoughts or ideas, or further investigating I can do.

(Oh, I also turned on logging and checked, but didn't see anything that stuck out to me.)

**Comment by horvay** [comment]
I don't know if it has anything to do with anything, but without stl, it goes from 180m to 50m to 180m very quickly.

With the standard library included, it goes from 515 to 180 but then back to 515 REALLY slowly. The bigger it gets, the slower it goes.

**Comment by bobbrow** [comment]
I'd have to download the source and see what's going on, but we are using the same engine as Visual Studio minus the fact that we can't take advantage of many of their optimizations since we don't own the editor.

In that first gif in your reply, I can see that the extension is working exactly as we expect.  You edit the file and after 3 seconds of inactivity we do a fast reparse of the edited section (I saw the flame icon show up briefly and memory usage stayed at 515MB).  Then after 10 seconds of inactivity we do a full reparse to keep memory usage under control and clean up any stale squiggles that have been resolved but were potentially missed.  Saving the file short circuits this logic and goes straight to the full reparse because our assumption was that we'd have a few seconds to spare while the user stopped to think.

I think we'll need to rethink some of our assumptions here and do things differently if auto-save is on.  If memory isn't a concern, there is less of a need to reparse the whole file and we can do something more intelligent.  However, as the engine starts to use more memory, it also becomes more sluggish.  We made the engine very conservative regarding how much memory it is allowed to consume, but it is apparent that we need to adjust our heuristic or expose a setting to give more control to you depending on how disruptive the reparsing is.

**Comment by horvay** [comment]
Sounds good. I'd rather take a few gigs if it meant parsing within a few seconds

**Comment by horvay** [comment]
I researched this a bit more and I was able to narrow the problem down to one file in the MS STL.

It is C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sal.h

Looking at that file, it seems to be 200k worth of macros, so maybe the parser is having trouble with lots of macros?

Anyways, if I exclude that one file from the includes, the DB goes from 500m to about 200m and parses within about 3 seconds.

**Comment by horvay** [comment]
Is there a way to exclude a file from the included headers?

**Comment by sean-mcmanus** [comment]
Adding it to files.exclude should work, but it has other effects (i.e. it will become hidden to VS Code in other scenarios). Does that work for you? We've considered using files.watcherExclude for this, but we haven't had enough user feedback requesting that.

**Comment by horvay** [comment]
I saw the other issue where you suggested the files.exclude and tried it. It's not working for me, but maybe I'm doing it wrong. Here are the two things I've tried to add to my workspace settings:

```JSON
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/sal.h": true
    },
```

and 

```JSON
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/sal.h": true
    },
```

Neither of these stopped the parser from trying to interpret sal.h.

Is it expected behavior for the MS IntelliSense engine to joke on macros like this? (It's about 1k macros in that files, I think.) It goes from 3 seconds parsing to 2 minutes parses just from adding that one file.

**Comment by sean-mcmanus** [comment]
Oops, I didn't realize this was about the IntelliSense parsing, right? files.exclude is only respected for the Tag Parser's parsing. If your translation unit is actually using sal.h, then we can't really exclude it for compilation to succeed (well, I guess we could add code to force it to be excluded, but ideally that shouldn't be necessary).

I don't think it's expected for the IntelliSense engine to have problems with macros. We need to try to repro this...

**Comment by horvay** [comment]
I'll see if I can set up a simple project to reproduce it.

**Comment by sean-mcmanus** [comment]
Oh, it sounded like it was reproducible with just sal.h? We could also try Amazon's Lumberyard (assuming the license allows us). But the simpler the project the better :)

**Comment by horvay** [comment]
When I add sal.h to our lumberyard project, I get this behavior. However, if I add it to an empty project, it does not have this behavior.

I'm guessing it has something to do with it's use then. :(

I could zip up the project and share it with you personally if you'd like but it's not a public repo right now.

For now, I'm seeing if I can reproduce on a smaller project.

**Comment by horvay** [comment]
Also, Lumberyard is free. They make money on using AWS since it has nice integration

**Comment by horvay** [comment]
I am seeing some strange behavior. 

If I remove that sal.h it fixes the issue (creates 220m process.) However, if I remove the googlemock library and include sal.h, it also fixes the behavior (and creates a 310m process).

Both those libraries are very heavy in macros.

Is it possible it's related to the magnitude of macros? Or maybe the way they cascade..

Still trying to reproduce in a smaller project but it's proving difficult.

**Comment by horvay** [comment]
I'm starting to think it has to do with the size of a file to parse? Or total number of symbols perhaps.. at some point it just gets exponentially longer to parse.

I created a repo to try to recreate my issue: [here](https://github.com/horvay/vscode_cpp_repro_sandbox)

There is a compiler error at the top of main.cpp and the error squiggly shows up pretty fast. However, once I make a few changes, it takes longer and longer to the point where it parses indefinitely for both squiggles and hover information.

If I reduce the number of functions to about 1k, it parses in a couple of seconds.

**Comment by sean-mcmanus** [comment]
Thanks a lot for the repro. It appears to get gradually slower every time it reparses e.g. 5 sec, 10 sec, ... 45 sec...I didn't get an indefinite wait though.

**Comment by horvay** [comment]
I may have done something bad with the process in the task manager to cause the indefinite case. Thanks for looking into it!

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
