### ISSUE TITLE
Incorrect semantic token for '= default;' and '= delete;'

### ISSUE THREAD

**Issue by gtianw** [microsoft/vscode-cpptools#9281]
Bug type: Language Service

**Describe the bug**
- OS and Version:Windows 10 Pro
- VS Code Version:1.67.0
- C/C++ Extension Version:v1.9.8
- Other extensions you installed (and if the issue persists after disabling them):None
- If using SSH remote, specify OS of remote machine:Ubuntu 20.04.4 LTS
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The semantic tokens about `= default;`/`= delete;`, in copy/move assignment operator, are incorrect.

**Expected behavior**

Same as constructor/destructor.

**Code sample and logs**

- Code sample
```cpp
class MyClass
{
  public:
    MyClass()                = default;
    ~MyClass()               = default;
    MyClass(const MyClass &) = default;
    MyClass(MyClass &&)      = delete;
    MyClass &operator=(const MyClass &) = default;
    MyClass &operator=(MyClass &&) = delete;
};
```
- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

![image](https://user-images.githubusercontent.com/91190888/167132983-31f5094d-5d3a-4757-992f-22f06545a383.png)
![image](https://user-images.githubusercontent.com/91190888/167133189-4947190c-8b87-4bd2-a741-2d02345dd06c.png)
![image](https://user-images.githubusercontent.com/91190888/167133261-b90a23fd-d613-47c6-a138-3789fa18b80c.png)
The pictures above are correct，but belows are wrong.
![image](https://user-images.githubusercontent.com/91190888/167133785-9bcd3713-531e-482c-8407-e52b0084f459.png)
![image](https://user-images.githubusercontent.com/91190888/167133830-5991ed69-ec29-4786-bd43-f477ccb121fc.png)

**Additional context**

**Comment by sean-mcmanus** [comment]
The textmate scope is not semantic colorization, it's lexical coloration which comes from VS Code itself (you can verify via disabling our extension). It looks like there's an issue tracking this at https://github.com/jeff-hykin/better-cpp-syntax/issues/496 or possibly another issue on that repo (which is where VS Code gets its lexical colorization from).
