### ISSUE TITLE
Insert New Lines Between C/C++ Functions When Formatting

### ISSUE THREAD

**Issue by garbles9100** [microsoft/vscode-cpptools#9283]
Is it possible or could it be a new feature to insert a new line between C/C++ functions when formatting via methods like Shift+Alt+F?

For example, I would like to see this:
void func1()
{
}
void func2()
{
}

become this:
void func1()
{
}

void func2()
{
}

**Comment by michelleangela** [comment]
@garbles9100 
Which formatting engine are you using? The extension supports ClangFormat and vcFormat.
![image](https://user-images.githubusercontent.com/38734287/167198294-0d43bfdf-dbf2-49c4-853a-ba129aa1504e.png)

ClangFormat can be configured with these options https://clang.llvm.org/docs/ClangFormatStyleOptions.html

For vcFormat configuration, the extension has settings `C_Cpp.vcFormat.*` that can be configured. Or you can create a .editorconfig file with similar options (https://docs.microsoft.com/en-us/visualstudio/ide/cpp-editorconfig-properties?view=vs-2019).

**Comment by garbles9100** [comment]
> @garbles9100 Which formatting engine are you using? The extension supports ClangFormat and vcFormat. ![image](https://user-images.githubusercontent.com/38734287/167198294-0d43bfdf-dbf2-49c4-853a-ba129aa1504e.png)
> 
> ClangFormat can be configured with these options https://clang.llvm.org/docs/ClangFormatStyleOptions.html
> 
> For vcFormat configuration, the extension has settings `C_Cpp.vcFormat.*` that can be configured. Or you can create a .editorconfig file with similar options (https://docs.microsoft.com/en-us/visualstudio/ide/cpp-editorconfig-properties?view=vs-2019).

I believe we are using ClangFormat. There is a c_cpp_properties.json file that has "intelliSenseMode" set to "clang-x64". Other than that, I am unsure how to tell.

But it seems like you are saying that somewhere in the ClangFormat or through the .editorconfig file there is a way to achieve the formatting I described in the OP. If that is the case and I don't have to write my own formatting extension then please let me know which of the settings actually controls spacing between function implementations. I tried changing some in the .editorconfig and none of them seemed to have an effect.

**Comment by sean-mcmanus** [comment]
c_cpp_properties.json doesn't affect formatting at all. The setting is C_Cpp.formatting available via VS Code's settings UI or the settings.json/etc. You can also set C_Cpp.loggingLevel to "Debug" and check the C/C++ pane logging to look for "vcFormat" or 
"clangFormat".

**Comment by garbles9100** [comment]
Ah okay. Got it. My setting is Default which appears to be the clang-format.

**Comment by garbles9100** [comment]
So, if the default is clang-format, does that mean I have to install ClangFormat and then supply a .clang-format file and point the VS Code extension at both or is any of that included as part of the extension?

**Comment by sean-mcmanus** [comment]
We bundle a clang-tidy executable with the extension so you don't have to install it separately (13 with 1.9.8 and 14 with 1.10.2). You can supply a .clang-format file if you want -- we should auto-detect it if it exists.

**Comment by garbles9100** [comment]
When you say clang-tidy, did you mean clang-format or are you implying that clang-format is included in the clang-tidy executable?

**Comment by sean-mcmanus** [comment]
Oops, sorry, yeah, I meant clang-format (but we bundle clang-tidy as well).

**Comment by garbles9100** [comment]
Okay. I think I found what I wanted which is SeparateDefinitionStyle and seems to be available in clang-format 14 which required me to install the Pre-Release version of the extension (1.10.2).

I added a file named .clang-format to the top of my project and put the following in that file:
`BasedOnStyle: LLVM
UseTab: Never
IndentWidth: 4
TabWidth: 4
BreakBeforeBraces: Allman
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
AccessModifierOffset: -4
NamespaceIndentation: All
FixNamespaceComments: false`

That works the same as I had before.

Then I added this line:
`SeparateDefinitionStyle: Always'

When I reload VS Code and hit Shift+Alt+F while in my target file, VS Code indicates an error has occurred in the extension. I'm not sure how to see details of the extension error. Removing the added line puts the extension back in a good state.

**Comment by garbles9100** [comment]
I found the error message, but I don't think it will be helpful:
"/home/csbelcher/.vscode-server/extensions/ms-vscode.cpptools-1.10.2-linux-x64/bin/../LLVM/bin/clang-format -style=file -fallback-style=LLVM -assume-filename=TARGET_FILE"

**Comment by sean-mcmanus** [comment]
-assume-filename= is invalid. You shouldn't be using that. It's only for setting the filename that is used in regards to what language to process, such as for example test.c versus test.cpp. Can you remove that?

**Comment by sean-mcmanus** [comment]
Oh, actually, it looks like our extension is adding that. The error might have another cause, just a sec...

**Comment by garbles9100** [comment]
I figured it out. The line:
SeparateDefinitionStyle: Always
should be:
SeparateDefinitionBlocks: Always

**Comment by garbles9100** [comment]
I changed it to the latter and that works perfectly. Thanks for helping get me to the answer :D I'll just tell my team to use the Pre-Release version of your extension.

**Comment by sean-mcmanus** [comment]
Cool -- yeah, the unhelpful error messages when there's a .clang-format syntax error is a known issue (not sure if we can improve it).

**Comment by garbles9100** [comment]
Using the `SeparateDefinitionBlocks: Always` option from clang-format 14 combined with the Pre-Release version of the cpptools extension (1.10.2) solves this issue.
