### ISSUE TITLE
my system is ubuntu 18.04, my vscode version is 1.67.0，c/c++ plugin version is 1.9.8, before i install c/c++ plugin， my list members function is good, after i install plugin, my "list member" function is invalid

### ISSUE THREAD

**Issue by movie19921209** [microsoft/vscode-cpptools#9285]
Bug type: Language Service

**Describe the bug**
- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
I don't understand. Can you provide more information?
