### ISSUE TITLE
Cannot open included full paths in a new tab

### ISSUE THREAD

**Issue by ISSac25E** [microsoft/vscode-cpptools#9287]
Bug type: Language Service

note: first time posting an issue in git, let me know if something is wrong with the post. Could not find if the exact issue was opened before but I might have missed it

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.67.0
- C/C++ Extension Version: 1.9.8
- Other extensions you installed (and if the issue persists after disabling them): Arduino(v.0.4.12), ini-format(v0.1.4) (issue persisted after all extensions were disabled)
- description of issue:
cpp extension cannot open a **FULL** file path from #incude into a new tab by using "f12" (go to definition). However, cpp IntelliSense will still locate that file, ie no error squiggles for "file not found", it simply just can't open it in a new tab

**Steps to reproduce**
1. Open any cpp file and place a #include statment

2. copy the **FULL** path of any valid ".h" ".cpp" and past it into the include statement:
eg. 
#include "C:\Users\Student\Documents\ ... \somefile.h"
Make sure no error squiggles appear, ie IntelliSense should be able to locate the file with no problems

3. Now, if you try to press "f12"(go to definition) on the #include path, it will say "no definition found for ___"

4. However, if you attempt to include a file without using full path, "f12" will open the file with no problems
e.g.
#include "somefile.h"

directory overview:
parentfolder
|  main.cpp
|  somefile.h
|
Otherfolders
|
...

**Possibly Useful note**
if you "restart intelliSense for active file" and very quickly spam "f12"(go to definition) on the path, it will open the full path 
without problems. Once Intellisense has fully restarted, however, f12 won't work anymore with the same message "no 
definition found for ___"

**Expected behavior**
when you "go to definition" on a valid path, any valid path,  VS should be able to open that file in a new tab.

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. A fix should be in our next release.

**Comment by sean-mcmanus** [comment]
This is fixed with 1.10.2 (pre-release).
