### ISSUE TITLE
c_cpp_properties.json resetting automatically to default

### ISSUE THREAD

**Issue by OToL** [microsoft/vscode-cpptools#929]
Hi,

I m currently using VSCode insider and cpptools extension on MacOS and my c_cpp_properties.json file is getting reset to default (i.e. all my paths are deleted) for unknown reason while editing code or at startup.

Is it a know issue?

Manu.

**Comment by bobbrow** [comment]
This sounds like #927.  Can you take a look and confirm?  Our extension never deletes your paths.

**Comment by OToL** [comment]
It is, thanks!
